### ISSUE TITLE
[iOS][Android] `IsEnabled=false` is not reflected through style but still applied when set through parent 

### ISSUE THREAD

**Issue by marwalsch** [unoplatform/uno#10006]
### Current behavior

Let a wrapped control's `IsEnabled` property be bound to another dependency property of its parent. When the wrapping control's `IsEnabled` property is set to `false`, the property is routed through all children correctly as they are being set to disabled. However, on mobile platforms the corresponding style is not applied.
See below, buttons 1,3 and 4 are correctly disabled, while 1 lacks the visual indicator on Android and iOS.

Windows:
![Screenshot 2022-09-29 085201](https://user-images.githubusercontent.com/72074423/192962528-105c4bc3-c775-4920-9206-5b587fcd0326.png)

Mobile:
![Screenshot 2022-09-29 085438](https://user-images.githubusercontent.com/72074423/192962449-472c2981-b43c-4055-a930-9c5e9e52915b.png)

Other controls might be affected as well

### Expected behavior

The behaviour should be the same as on windows.

### How to reproduce it (as minimally and precisely as possible)

See attached sample.

### Workaround

Explicitly bind the inner control's `IsEnabled` to the outer one's as well as the additional custom dependency property.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI 4.6.0-dev.467

### Affected platforms

iOS, Android, ...?

### Reproducable sample

[Repro.zip](https://github.com/unoplatform/uno/files/9672077/Repro.zip)

**Comment by jeromelaban** [comment]
Thanks for the report. Can you provide a repro sample of the issue? For example, it's working properly here: https://playground.platform.uno/#toggle-button

**Comment by Youssef1313** [comment]
I tested on Android too and it works.

**Comment by marwalsch** [comment]
@jeromelaban @Youssef1313 Thanks for looking into it. You were both right on my instructions not being sufficient o reproduce (apologies for that). Turns out it's a niche issue that occurs only when the property is bound to a parent's custom dependency property. After some testing i realized this appliesto numerous controls, including `ToggleButton` and `Button`. I updated the issue.

**Comment by Youssef1313** [comment]
I'm able to reproduce. To save time for who will take a look next, here is the attached repro added in SamplesApp

https://github.com/unoplatform/uno/commit/7f7a6e1a54d74e2e1774f039947aabaf7e2598f0

**Comment by MartinZikmund** [comment]
@ramezgerges I think this is now probably fixed, correct?

**Comment by ramezgerges** [comment]
Yes, this should be fixed by #12884.
