### ISSUE TITLE
Stretch.Uniform create a Mosaic in Skia which is not the desirable behavior

### ISSUE THREAD

**Issue by amelield** [unoplatform/uno#10021]
### Current behavior

In Skia, Stretch.Uniform create a Mosaic. Since it is not the exepected. 
<img width="53" alt="mosaic" src="https://user-images.githubusercontent.com/46757407/193121656-1b378c2e-583b-4f04-a3bf-709bf646140a.PNG">

### Expected behavior

Stretch.Uniform should fit the content in keeping the proportions. 
<img width="45" alt="uniform" src="https://user-images.githubusercontent.com/46757407/193122700-3ca1d899-5fdf-4423-9a3b-506d528161c8.PNG">

### How to reproduce it (as minimally and precisely as possible)
Remove the if Skia wrapping around Stretch.Uniform in src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Given_ImageBrushStretch.cs. Open Uno.UI with Skia and test the When_Stretch() test in the Runtimes section of the Sample App. You may have to comment Stretch.None to have the frame stop at the right image.

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment]
The test was unskipped in #14119. This should be fixed.
