### ISSUE TITLE
[Navigation] NavigateViewModelForResultAsync .AsResult never finishes if you close content dialog by putting app in background

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#10038]
## Current behavior
![backgroundbugq](https://user-images.githubusercontent.com/90481654/193291944-e2bd1aee-ae00-4ff7-9ea3-a6a8ab6a1896.gif)

## Expected behavior

It should have the same behavior as when you just navigateback. Or the Content dialog should not close itself

## How to reproduce it (as minimally and precisely as possible)
Steps to reproduce:
Open the app,
press on the button
put the app in background
notice the button is now disabled, because task is still running.

To Make another sample app, you just need to open a contentDialog (it's important that it's a content dialog, this problem does not happen with a page) with navigateViewModelForResultAsync (...........) .AsResult and await the result.

The task never ends.

[MyAppTest2.zip](https://github.com/unoplatform/uno.extensions/files/9685275/MyAppTest2.zip)

## Environment

Nuget Package:
Uno.Extensions / winui

Package Version(s):

	  PackageReference Update="Uno.Extensions.Configuration" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Core" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Hosting" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Hosting.WinUI" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Http" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Http.Refit" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Localization.WinUI" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Logging.Serilog" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Logging.WinUI" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Navigation" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Navigation.Toolkit.WinUI" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Navigation.WinUI" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Reactive" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Reactive.WinUI" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Serialization" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Serialization.Http" Version="2.3.0-dev.69" />
	  PackageReference Update="Uno.Extensions.Serialization.Refit" Version="2.3.0-dev.69" />

Affected platform(s):

- [X] iOS (could not open it on my repro app, but it happens on another app)
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [X] 2022 (version: 17.3.4 )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by nickrandolph** [comment]
This is also related to https://github.com/unoplatform/uno.extensions/issues/768
