### ISSUE TITLE
Image control does not empty when bound field is set to null in WPF head.

### ISSUE THREAD

**Issue by Suriman** [unoplatform/uno#10048]
### Current behavior

The image control keeps previously displayed image when bound field is set to null in WPF head.

### Expected behavior

The image control should display blank.

### How to reproduce it (as minimally and precisely as possible)

Insert an image control and bind a field of type ImageSource to it.
Change the bound field to a valid image.
Change the bound field to a null value.

### Workaround

No known workaround

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.WinUI 4.5.9

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.3.5

### Anything else we need to know?

See the attahed file!
[ImageControlNotClearInWPF.zip](https://github.com/unoplatform/uno/files/9699870/ImageControlNotClearInWPF.zip)

**Comment by Youssef1313** [comment]
@MartinZikmund Is this something that will be getting fixed with your SVG work?

**Comment by MartinZikmund** [comment]
@Youssef1313 I think it should! I will test and link the issue if yes
