### ISSUE TITLE
Remove current usages of `GetRect` in UI Tests

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#10059]
These obsolete methods should not be used:

https://github.com/unoplatform/uno/blob/9ae73a42303894d084634ea018457a3974de3e8c/src/SamplesApp/SamplesApp.UITests/Extensions/QueryExtensions.cs#L83-L100

and they should be removed.

**Comment by 3NCRY9T3D** [comment]
Hi, can I work on this issue?
