### ISSUE TITLE
Investigate a performance improvement for XAML generator

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#10051]
Currently, XAML generator needs to run in design-time builds since it affects IntelliSense.

However, I don't think everything it generates will affect IntelliSense. So, I suggest investigating to split XAML generation into two phases.

#### Phase 1

- This will run in design-time builds.
- It does the very minimal amount of work.

Things that clearly should be done in this phase:

- Generate a partial declaration of `InitializeComponent` (without implementation)
- Generate the fields that are usable by developers and the code-behind (for example, `x:Name` fields)

This phase should be as fast as possible.

#### Phase 2

- This **won't** run in design-time builds.
- It does the heavy and expensive work.

It will do almost everything, except the fields that were already generated in Phase 1

-----------

This may require large refactoring to the generator. But I think it can improve the IDE responsiveness greatly.

**Comment by jeromelaban** [comment]
Indeed, it will! This is the kind of change we anticipated would be needed at some point.

**Comment by Youssef1313** [comment]
This suggestion will lose generator idempotency, which I think we don't want to do :/
It may also cause issues with HotReload.
The generator performance has already improved over time. Whenever a case is found where the generator is affecting IDE performance, we should investigate the specific case and find a performance improvement.

I think this can be closed, but I'll it to @jeromelaban to decide.

**Comment by jeromelaban** [comment]
Indempotence would still be viable, considering the generation of a design-time version would be tied to an msbuild property and not as a mutable state from the generator itself. Yet I agree, generation has become a lot faster now. Let's close for now.
