### ISSUE TITLE
Uncaught ReferenceError: twttr is not defined

### ISSUE THREAD

**Issue by mbiesiad** [unoplatform/uno#10097]
### Current behavior

`Uncaught ReferenceError: twttr is not defined` occurs after visit site.

### Expected behavior

No mentioned error

### How to reproduce it (as minimally and precisely as possible)

MINIMAL REPRO PROJECT and the STEPS TO REPRODUCE
1. Go to: https://platform.uno/
2. Open DevTools
3. Check Console - `Uncaught ReferenceError: twttr is not defined`

### Workaround

Do not look into DevTools or site

### Anything else we need to know?

Screenshot:
![image](https://user-images.githubusercontent.com/18367606/194729805-97c23e0a-89f8-4be4-b460-b76568d8ef43.png)

Best wishes,

**Comment by sasakrsmanovic** [comment]
Thank you for reporting, we will look into this.

**Comment by ivanjx** [comment]
this is caused by adblockers. not sure if it is even appropriate to report site's issue here though.

**Comment by mbiesiad** [comment]
Hi All, thanks for quick answers & messages. I know, I can see your point of view, but it should not be `Uncaught` for user view in my opinion. For me that answer is affirmative answer, because the repo has direct connection (at this moment) to mentioned site. Greetings
