### ISSUE TITLE
NuGet not working to uno

### ISSUE THREAD

**Issue by AbdalaMask** [unoplatform/uno#10101]
### Current behavior

NuGet not working to uno
![image](https://user-images.githubusercontent.com/37013638/194768588-c46050d9-295c-4016-ba8b-07affda5a2d3.png)
please help

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### IDE

Visual Studio 2022

### IDE version

17.3

**Comment by Youssef1313** [comment]
I guess this is mainly a bad/slow internet connection issue. Though you could try to close Visual Studio, and do `dotnet restore --disable-parallel` from the command line, which can work better for slow connections.

**Comment by Youssef1313** [comment]
Also can you share the contents of `nuget.config` file you have? Reducing some unnecessary feeds might help too.
