### ISSUE TITLE
Add naming style configurations to `.editorconfig`

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#10143]
This boosts productivity by letting some IDE features generate members with the correct naming conventions.

For example, in many cases I add a new parameter to a constructor, then I use the "Create and assign field" feature:

![image](https://user-images.githubusercontent.com/31348972/195985807-5bcf2af7-d3bf-4c5e-a2e0-7c7cd7d8f7d3.png)

Currently, after applying the suggestion from VS, I have to rename the private field to start with `_`
This is a bit annoying.

Note that there can be other IDE features affected, but this is the one I currently remember.

As a next step, we can enforce the naming style on build.

To tackle this issue, we need to confirm this table:

> Note *externally visible* means `public`, `protected internal`, or `protected`.
> and *non-externally visible* means `private`, `internal`, or `private protected`.

| Member                                               | Coding style                          |
| ---------------------------------------------------- | ------------------------------------- |
| All constant fields                                  | PascalCase?                           |
| Non-externally visible static fields                 | `_camelCase`? or `s_camelCase`?       |
| Externally visible static fields                     | ?                                     |
| Non-externally visible non-static fields             | `_camelCase`                          |
| Externally visible non-static fields                 | ?                                     |
| Local variables and parameters                       | `camelCase`                           |
| Local functions                                      | `camelCase`? or `PascalCase`?         |
| Type parameters                                      | `TPascalCase`                         |
| Interfaces                                           | `IPascalCase`                         |
| Types, properties, methods, events, namespaces       | `PascalCase`                          |

We can start with the following (taken from https://github.com/dotnet/efcore/blob/main/.editorconfig) and adjust per our conventions if it diverges from efcore:

```ini
## Naming styles

dotnet_naming_style.pascal_case_style.capitalization = pascal_case
dotnet_naming_style.camel_case_style.capitalization = camel_case

# PascalCase with I prefix
dotnet_naming_style.interface_style.capitalization = pascal_case
dotnet_naming_style.interface_style.required_prefix = I

# PascalCase with T prefix
dotnet_naming_style.type_parameter_style.capitalization = pascal_case
dotnet_naming_style.type_parameter_style.required_prefix = T

# camelCase with _ prefix
dotnet_naming_style._camelCase.capitalization = camel_case
dotnet_naming_style._camelCase.required_prefix = _

## Rules
# Interfaces
dotnet_naming_symbols.interface_symbol.applicable_kinds = interface
dotnet_naming_symbols.interface_symbol.applicable_accessibilities = *
dotnet_naming_rule.interface_naming.symbols = interface_symbol
dotnet_naming_rule.interface_naming.style = interface_style
dotnet_naming_rule.interface_naming.severity = suggestion

# Classes, Structs, Enums, Properties, Methods, Local Functions, Events, Namespaces
dotnet_naming_symbols.class_symbol.applicable_kinds = class, struct, enum, property, method, local_function, event, namespace, delegate
dotnet_naming_symbols.class_symbol.applicable_accessibilities = *

dotnet_naming_rule.class_naming.symbols = class_symbol
dotnet_naming_rule.class_naming.style = pascal_case_style
dotnet_naming_rule.class_naming.severity = suggestion

# Type Parameters
dotnet_naming_symbols.type_parameter_symbol.applicable_kinds = type_parameter
dotnet_naming_symbols.type_parameter_symbol.applicable_accessibilities = *

dotnet_naming_rule.type_parameter_naming.symbols = type_parameter_symbol
dotnet_naming_rule.type_parameter_naming.style = type_parameter_style
dotnet_naming_rule.type_parameter_naming.severity = suggestion

# Visible Fields
dotnet_naming_symbols.public_field_symbol.applicable_kinds = field
dotnet_naming_symbols.public_field_symbol.applicable_accessibilities = public, internal, protected, protected_internal, private_protected

dotnet_naming_rule.public_field_naming.symbols = public_field_symbol
dotnet_naming_rule.public_field_naming.style = pascal_case_style
dotnet_naming_rule.public_field_naming.severity = suggestion

# Private constant Fields
dotnet_naming_symbols.const_field_symbol.applicable_kinds = field
dotnet_naming_symbols.const_field_symbol.applicable_accessibilities = private
dotnet_naming_symbols.const_field_symbol.required_modifiers = const

dotnet_naming_rule.const_field_naming.symbols = const_field_symbol
dotnet_naming_rule.const_field_naming.style = pascal_case_style
dotnet_naming_rule.const_field_naming.severity = suggestion

# Parameters
dotnet_naming_symbols.parameter_symbol.applicable_kinds = parameter
dotnet_naming_symbols.parameter_symbol.applicable_accessibilities = *

dotnet_naming_rule.parameter_naming.symbols = parameter_symbol
dotnet_naming_rule.parameter_naming.style = camel_case_style
dotnet_naming_rule.parameter_naming.severity = suggestion

# Everything Local
dotnet_naming_symbols.everything_else.applicable_kinds = local
dotnet_naming_symbols.everything_else.applicable_accessibilities = *

dotnet_naming_rule.everything_else_naming.symbols = everything_else
dotnet_naming_rule.everything_else_naming.style = camel_case_style
dotnet_naming_rule.everything_else_naming.severity = suggestion
```

**Comment by Youssef1313** [comment]
@jeromelaban Could you please edit the table in the issue to match the convention that should be used? Thanks!

**Comment by jeromelaban** [comment]
Nice! So far, this looks fine and since most are suggestions, this has no major impact if the configuration is incorrect.
