### ISSUE TITLE
`CanOpenFlyoutByTapping`, `CanCloseFlyoutBySelectingADate`, and `PressingDoesNotOpenMenuFlyout` tests are failing

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#10165]
### Current behavior

`CanOpenFlyoutByTapping`, `CanCloseFlyoutBySelectingADate`, and `PressingDoesNotOpenMenuFlyout` tests are failing and being disabled in #10146

### Expected behavior

They should pass

**Comment by MartinZikmund** [comment]
Reopened for backport

**Comment by MartinZikmund** [comment]
Backported and done
