### ISSUE TITLE
[Gallery][Skia.GTK]Divider-When scroll down the screen is flickering for the 'Divider inside a Listview' section.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#10186]
### Current behavior

https://user-images.githubusercontent.com/74563602/196519354-ff7698f2-484f-4980-a9c6-f93eaffd8387.mp4

### Expected behavior

The screen should not flicker for 'Divider inside a Listview' section.

https://user-images.githubusercontent.com/74563602/196518716-f4adc614-51b6-4def-ad39-fbd08b6f0cfb.mp4

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app on Skia.GTK.
2. Click on “Divider” from the "Toolkit" list.
3. Scroll down the screen to go to 'Divider inside a Listview' section.
4. Notice that the Screen is flickering from the down part for the 'Divider inside a Listview' section.

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by MartinZikmund** [comment]
This has been probably fixed by https://github.com/unoplatform/uno/pull/12083, please verify

**Comment by jeromelaban** [comment]
@sakshi173

**Comment by agneszitte** [comment]
@sakshi173 I added this issue to the "Needs QA Review" list so you can review it please

@jeromelaban / @MartinZikmund  added to the current release backlog for @sakshi173 to review it but can move to other backlog depending on the outcome and priority

**Comment by sakshi173** [comment]
Verified, issue is fixed, closing it.
