### ISSUE TITLE
[Gallery][Skia.GTK]File and Folder Pickers- The Gallery app freezes and finally crashes, when click on any 'Open file or folder' option. 

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#10181]
### Current behavior

https://user-images.githubusercontent.com/74563602/196495652-dcf353f2-e6c8-41b7-b499-9858b54057fd.mp4

![F F issue](https://user-images.githubusercontent.com/74563602/196497767-d3e777cf-7bbe-4342-864c-b48f1cdcac9e.png)

### Expected behavior

Gallery App should not get freeze.
And the open File and folder should open to choose the file.
![F F correct](https://user-images.githubusercontent.com/74563602/196496448-b1c51fa1-7ee8-4c1c-8e12-df58a0c5ab4b.png)

### How to reproduce it (as minimally and precisely as possible)

Launch the Uno.Gallery app on Skia.GTK.
Click on “File and Folder Pickers” from the "Non-UI Features" list.
Click on any option 'Open File' or 'Open Files' or 'Open Images' or 'Open Folder'.
Notice that the Gallery app freezes and finally crashes.

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by jeromelaban** [comment]
I'm not able to reproduce. I'm going to make a change to the app so that the console shows up in canary builds, let's see tomorrow what will show up in the console.

**Comment by jeromelaban** [comment]
It's done in https://github.com/unoplatform/Uno.Gallery/commit/73e4ebbfbfb2066ebe1a1312ce5771be64623f90. @sakshi173 lets retry this one tomorrow, thanks!

**Comment by sakshi173** [comment]
Verified this issue is fixed, closing it.
