### ISSUE TITLE
[Android][iOS] Windows Networking Doesn't Work when using VPN

### ISSUE THREAD

**Issue by Soap-141** [unoplatform/uno#10197]
### Current behavior

The internet state is never updated when using a VPN and doesn't represent the actual internet access state.

https://user-images.githubusercontent.com/57812285/196692977-6c0c1ad0-741d-4904-b219-bd96b8fb9472.mp4

### Expected behavior

The internet state should be updated like when we aren't using a VPN.

https://user-images.githubusercontent.com/57812285/196693182-d38e9551-6282-468b-803e-82c84f5381cd.mp4

### How to reproduce it (as minimally and precisely as possible)

1. Download [UWPnetwork.zip](https://github.com/unoplatform/uno/files/9820522/UWPnetwork.zip)
2. Open the Visual Studio Solution
3. Make sure you have a VPN installed on your Android or iOS device
4. Start the application on Android or iOS
5. Disable internet
6. Notice the label changing
7. Enable internet
8. Notice label changing
9. Enable your VPN
10. Repeat steps 5 to 8

### Workaround

N/A

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Latest pre release or stable Uno packages

### Affected platforms

Android, iOS

### IDE

Visual Studio 2022

### IDE version

17.3.6

### Relevant plugins

N/A

### Anything else we need to know?

https://platform.uno/docs/articles/features/windows-networking.html

I also tried Xamarin Essentials & MAUI Essentials Connectivity features and doesn't work with a VPN.

**Comment by takla21** [comment]
Any updates on this @MartinZikmund?

**Comment by MartinZikmund** [comment]
@takla21 the Android portion of the problem may have been fixed in latest dev bits,,can you check if it works for you? I am still onto the iOS one

**Comment by takla21** [comment]
@MartinZikmund I tested the sample with the latest uno dev version 4.7.0-dev.699 and it seems to work quite well on android. Thanks!

**Comment by Soap-141** [comment]
@takla21 @MartinZikmund @jeromelaban Is iOS planned for Uno 4.9 or latter?

**Comment by jeromelaban** [comment]
@Soap-141 aside from the workaround you've found above, there's no known and reliable way to determine if a device is connected to a VPN. So at this time, we will not implement this feature for iOS.

**Comment by jeromelaban** [comment]
Let's close for now, and reevaluate if a future version of iOS provides a better way to detect VPNs.
