### ISSUE TITLE
XAML Reader is culture sensitive

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#10202]
### Current behavior

Go to https://playground.platform.uno/#147c30f8 and notice the parsing error when your browser is set to a culture on which the "comma" is used as the decimal separator.

Screenshot:
![image](https://user-images.githubusercontent.com/4174207/196759303-5d861b99-920c-4590-98f6-ea276120a34b.png)

### Expected behavior

Should work no matter the current culture.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

WebAssembly

**Comment by Youssef1313** [comment]
Looks similar to https://github.com/unoplatform/uno/issues/8466

**Comment by MartinZikmund** [comment]
@Youssef1313 did https://github.com/unoplatform/uno/pull/10337 also fix this?

**Comment by Youssef1313** [comment]
@MartinZikmund Might be. Also it could be https://github.com/unoplatform/uno/pull/11461.

I think we can close.
