### ISSUE TITLE
[Wasm] ` 'App' does not contain a definition for 'InitializeComponent'` when publishing

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#10208]
This error is still happening for VS 17.3.6 but only for publishing to Azure, but does Azure support Uno?

_Originally posted by @acrigney in https://github.com/unoplatform/uno/issues/4867#issuecomment-1284838923_

**Comment by jeromelaban** [comment]
@acrigney can you provide more details about the steps you're taking?

**Comment by acrigney** [comment]
I was able to publish to Azure ok, but the Uno App template does not include a business object project. And I am having a lot of code generation errors when I add the ToDo app one in and change the names, and references. Could you change the template to add more functional features?

**Comment by jeromelaban** [comment]
What do you mean by a business object project? Do you mean an additional library project? You should be able to add this manually pretty easily.

Do you see this particular project in Microsoft-provided templates?

**Comment by acrigney** [comment]
The To do app has a nice business object library you could add this to the
Uno app template? I have been trying to use this as a template for my
project but I am getting a lot of code generation issues.

**Comment by jeromelaban** [comment]
You can use the [Uno.Extensions app template](https://platform.uno/docs/articles/external/uno.extensions/doc/Overview/ExtensionsOverviewAndGettingStarted.html#1-installing-extension-templates) to get a similar structure. I'll be closing this issue as the original description seems to be fixed on your end. 

For additional questions on Uno,Extensions, make sure to open [a new discussion](https://github.com/unoplatform/uno/discussions)!

**Comment by acrigney** [comment]
Great stuff except I created a new solution as you said but the code generated code failed with
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Extensions' does not exist in the namespace 'PCSProducts.Uno' (are you missing an assembly reference?)	PCSProducts.Uno	C:\Projects\PCSProducts.Uno\PCSProducts.Uno\PCSProducts.Uno\Uno.Extensions.Reactive.Generator\Uno.Extensions.Reactive.Generator.FeedsGenerator\PCSProducts.Uno.Presentation.MainViewModel.g.cs	28	Active
Although I can see that the Extensions are referenced in the project. I followed all of the install instructions I will go through them again.

**Comment by acrigney** [comment]
This problem has been around for a while it seems?
https://www.reddit.com/r/csharp/comments/jy2uyi/starting_with_uno_platform_a_bit_disappointed_do/

**Comment by jeromelaban** [comment]
@acrigney please see the answer here: https://github.com/unoplatform/uno/discussions/10234
