### ISSUE TITLE
[Gallery][Android]File and Folder Pickers- App crashes when click 'Save files' button after typing file1 and file2 names, for the 'Pick folder and save to files' section

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#10219]
### Current behavior

https://user-images.githubusercontent.com/74563602/197281243-6fe7b26b-501a-4a53-abff-31ac84e7785e.mp4

### Expected behavior

Gallery app should not crash.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP.
2. Tap Burger Menu on the left top right.
3. Tap "File and Folder Pickers" from the "Non-UI Features" list.
4. Go to the 'Pick folder and save to files' section.
5. Type file contents like 'abcd' in the file1.txt section.
6. Type file contents like 'abcde' in the file2.txt section.
7. Click the 'Save files' button.
8. Click the 'Allow Access to 'Folder name' button.
9. Click the 'Allow' Button.
10. Notice that the Gallery app gets crashes.

### Affected platforms

Android

**Comment by trungnt2910** [comment]
I can reproduce this on Android when two files with the name `file1.txt` and `file2.txt` already exist in the selected folder.

This is also the case on your device according to the video you recorded.
