### ISSUE TITLE
[Perf]Microsoft.UI.Xaml.Controls.BorderLayerRenderer.InnerCreateLayers(...) is slow on Android

### ISSUE THREAD

**Issue by ebariche** [unoplatform/uno#10241]
### Current behavior

We need to write specialized bindings for Brush.GetBackgroundDrawable(...) / BorderLayerRenderer.GetOverlayDrawable(...) as they consume over 6.65s of CPU time in some apps.

![image](https://user-images.githubusercontent.com/33458222/197621466-afc6ec0f-692d-4ac5-943f-16d44ac521e8.png)

![image](https://user-images.githubusercontent.com/33458222/197621503-06ffde80-ffde-45f4-8d11-c8057fdee051.png)

### Affected platforms

Android

**Comment by MartinZikmund** [comment]
I think this also has the same problem as border rendering on Skia where each time border changes a new radii array of length 8 is allocated
