### ISSUE TITLE
[iOS] Some items in ListView are invisible when scrolling

### ISSUE THREAD

**Issue by artemious7** [unoplatform/uno#10273]
### Current behavior

On iOS, `ListView` has some invisible items when scrolling, even though the space for them is reserved. Looks like a virtualization issue.

![image](https://user-images.githubusercontent.com/16724889/198154871-a5c7933d-eb61-47b6-b9a6-10369814f10e.png)

### Expected behavior

All items should be visible.

![image](https://user-images.githubusercontent.com/16724889/198155043-3bb59471-4928-4cf9-93c0-19f01f5d8bbd.png)

### How to reproduce it (as minimally and precisely as possible)

```XAML
        <ListView ItemsSource="{Binding}">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <TextBlock Foreground="Gray" Text="{Binding}" />
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
```

[Repro.zip](https://github.com/unoplatform/uno/files/9874370/ListViewItemContainerStyleBugRepro.zip)

### Workaround

Disable ListView's virtualization, e.g. by putting it inside of a ScrollViewer or by this:

```XAML
<Page ...
      xmlns:ios="http://uno.ui/ios"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      mc:Ignorable="ios">
...
<ListView>
<ios:ListView.ItemsPanel>
    <ItemsPanelTemplate>
        <StackPanel />
    </ItemsPanelTemplate>
</ios:ListView.ItemsPanel>
</ListView>
```

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
Tested on iPhone 8 iOS 15.5 Simulator

### NuGet package version(s)

4.5.14

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.4.0 preview 2.1

**Comment by jeromelaban** [comment]
Thanks for the report. Can you validate that you're still getting this with the latest 4.6-dev bits? We've make fixes for that recently.

**Comment by artemious7** [comment]
@jeromelaban, yes, thank you. The latest dev v4.6.0-dev.977 doesn't have this bug. We'd still prefer to use a stable version. Is 4.6.0 coming soon or should we create a build with this fix?

**Comment by lesterbotello** [comment]
Hello @jeromelaban, can you please confirm which 4.4.x version was this fix backported to?

**Comment by jeromelaban** [comment]
You can generally find it out by looking at the history here: https://github.com/unoplatform/uno/commits/release/stable/4.4 and click on the checkmarks for the associated builds.

For that particular PR, it looks like it was not backported to 4.4 as it was not required after all. If you need a backport, can you open a backport issue?
