### ISSUE TITLE
[Android] When you change theme, in a listView using the default color not all items change colors

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#10285]
### Current behavior

In a listview larger than your screen, if you use the default text color, when you change theme, the textcolor of some items outside the bounds of your screen will not change colors, so, when you scroll, you end up with something like:
![image](https://user-images.githubusercontent.com/90481654/198588370-ea46ccc1-74d3-4a15-bc46-e2c4def5c0a7.png)

### Expected behavior

Just like on UWP/IOS, all text should change colors

### How to reproduce it (as minimally and precisely as possible)

[ListViewNativeColorsUWP.zip](https://github.com/unoplatform/uno/files/9888484/ListViewNativeColorsUWP.zip)

1:Open the app on android, 
2:change theme
3: scroll -Notice not all Text changed color
4: repeat step 2 and 3

### Workaround

Using custom theme colors works

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

`    <PackageReference Include="Uno.UI" Version="4.6.0-dev.984" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="4.6.0-dev.984" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.6.0-dev.984" />
    <PackageReference Include="Uno.UniversalImageLoader" Version="1.9.33" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />`

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.3.6

### Anything else we need to know?

You can also get this bug by changing the theme of your phone. I added the button to test on UWP.

**Comment by Youssef1313** [comment]
- The attached repro is quite old, so I added the necessary code to new unoapp using the latest stable templates.
- The ListView didn't render any items at all.
    - Changing `ItemsSource="{Binding Names}"` to use `x:Bind` works. Looks like we have a regression here.
    - With `x:Bind`, I can repro the theming issue.

**Comment by MartinZikmund** [comment]
Reopened for backport
