### ISSUE TITLE
[Xamarin] Uno 4.6 and later makes the linker step longer to run

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#10286]
### Current behavior

When building the basic uno app template with the latest Uno.Ui nugget, it takes around 10-15 minutes to deploy the app on a physical device 

### Expected behavior

It should take around the same time than the latest stable nugget (1-2min)

### How to reproduce it (as minimally and precisely as possible)

[BuildTimeTest.zip](https://github.com/unoplatform/uno/files/9889437/BuildTimeTest.zip)
(this is the basic uno app template with IOS deployment enabled and with latest prerelease uno nuggets)

Build on an IOS physical device with latest stable. Notice it take around 1-2 minutes.

Update nugget to latest unstable and delete bin & obj, notice it takes around 10-15 minutes to build the same app

### Workaround

I don't know any

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

`    <PackageReference Include="Uno.UI" Version="4.6.0-dev.984" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="4.6.0-dev.984" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.6.0-dev.984" />`

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.3.6

### Anything else we need to know?

The build seems to be stuck at 
build4dd42f8392a87d32eb8552348c66f5efa9b4477561d104008d50d6b5cf21697818528masou/+/xma/ping/Broker (TaskId:235)
1>  [xma][info]: The client 'Broker' has acknowledged the ping (TaskId:235)
1>  [xma][info]: Pinging client 'Broker'... (TaskId:235)
1>  [xma][info]: Sending Request Xamarin.Messaging.PingMessage to topic xma/ping/Broker (TaskId:235)
1>  [xma][info]: Received Response of Xamarin.Messaging.PingMessage to topic 

which it repeats for most of the time of the build

**Comment by jeromelaban** [comment]
Thanks. Can you [provide a binlog](https://platform.uno/docs/articles/uno-builds-troubleshooting.html)?

**Comment by Marc-Antoine-Soucy** [comment]
[buildLog1.zip](https://github.com/unoplatform/uno/files/9889793/buildLog1.zip)
Are the logs from the problematic build sufficient? Or do you also want the log with the latest stable release nuggets?

**Comment by jeromelaban** [comment]
> 

Yes, if you can include the faster build it will help, thanks.

**Comment by Marc-Antoine-Soucy** [comment]
[BuildTimeTest.zip](https://github.com/unoplatform/uno/files/9889932/BuildTimeTest.zip)

**Comment by Marc-Antoine-Soucy** [comment]
[buildlog2.zip](https://github.com/unoplatform/uno/files/9889967/buildlog2.zip)
this is the normal one

**Comment by vincentcastagna** [comment]
I would add that we don't face this issue only for physical device .The build increases regardless the target (simulator etc)

**Comment by jeromelaban** [comment]
This issue is the result of https://github.com/unoplatform/uno/pull/9808, where forcibly roslyn-based generatiopn was enabled for all targets which in turn is causing https://github.com/dotnet/linker/issues/1409 in older linker implementations (used by Xamarin).

The fix will likely be to use [`EmbedAllSources`](https://github.com/dotnet/roslyn/blob/4758c5d34f56a461ff02b884889e190bf304057e/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L99) to false in Uno.UI for Xamarin targets, so generated files don't get embedded into the symbols.

A mitigation is currently to disable the linker entirely, but the build time is still higher because there's lots more code to compile.

**Comment by vincentcastagna** [comment]
The fix was backported in Uno [4.6.39](https://www.nuget.org/packages/Uno.UI/4.6.39) .
