### ISSUE TITLE
Support for the RatingControl

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1029]
## What would you like to be added:

- https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/rating
- https://github.com/microsoft/microsoft-ui-xaml/tree/master/dev/RatingControl

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

**Comment by MartinZikmund** [comment]
Closing in favor of a newer issue #3912
