### ISSUE TITLE
Custom fonts in shared assets have inconsistent path on Android

### ISSUE THREAD

**Issue by tristanlabelle** [unoplatform/uno#10298]
### Current behavior

Add a custom font to `Project.Shared\Assets` and notice the inconsistency in paths to access it. In this example, I'm using `DancingScript.ttf` from https://fonts.google.com/specimen/Dancing+Script/about

```xaml
    <StackPanel VerticalAlignment="Top" Orientation="Vertical" Margin="20">
        <TextBlock FontFamily="ms-appx:///Assets/DancingScript.ttf#Dancing Script" Text="Works on Windows" FontSize="30" />
        <TextBlock FontFamily="ms-appx:///Assets/Assets/DancingScript.ttf#Dancing Script" Text="Works on Android" FontSize="30" />
    </StackPanel>
```

The first textblock will correctly use the custom font on Windows whereas the second will on Android.

<img width="248" alt="image" src="https://user-images.githubusercontent.com/2314287/198915712-9d2789f4-9183-48f8-86c0-2a3cbc3411d4.png">

<img width="309" alt="image" src="https://user-images.githubusercontent.com/2314287/198916196-66b91887-3bcb-4106-b6d0-0ae4c9bc3973.png">

### Expected behavior

The path that works on Windows should also work on Android, and the second path should not work.

### How to reproduce it (as minimally and precisely as possible)

[FontAssetPathBugRepro.zip](https://github.com/unoplatform/uno/files/9897433/FontAssetPathBugRepro.zip)

### Workaround

The `<FontFamily>` can be defined in a `<ResourceDictionary>` with conditional markup for Android and Windows, and then referred uniformly using `{StaticResource}` 

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.5.12

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.3.5

### Anything else we need to know?

This is due to invalid logic in the Android code:

https://github.com/unoplatform/uno/blob/574a441497e0e6faee8d389a3dbac1c40d4d7891/src/Uno.UI/UI/Xaml/Extensions/FontHelper.Android.cs#L59-L63

**Comment by tristanlabelle** [comment]
This diagnostic message illustrates the inconsistency well. `ms-appx:///Assets/BravuraText.otf` is reported not found and then `Assets/BravuraText.otf` is listed as an available asset.

> [DOTNET] [41m[30mfail[39m[22m[49m: Microsoft.UI.Xaml.FontHelper[0]
> [DOTNET]       Unable to find font
> [DOTNET]       **System.InvalidOperationException: Unable to find [ms-appx:///Assets/BravuraText.otf#Bravura Text] from the application's assets.**
> [DOTNET]          at Microsoft.UI.Xaml.FontHelper.InternalFontFamilyToTypeFace(FontFamily fontFamily, FontWeight fontWeight, TypefaceStyle style) in C:\a\1\s\src\Uno.UI\UI\Xaml\Extensions\FontHelper.Android.cs:line 84
>
> [DOTNET] [40m[1m[33mwarn[39m[22m[49m: Microsoft.UI.Xaml.FontHelper[0]
> [DOTNET]       **List of available assets: Assets/BravuraText.otf**
> [DOTNET]       Fonts/uno-fluentui-assets.ttf
> [DOTNET]       images/android-logo-mask.png
> [DOTNET]       images/android-logo-shine.png

**Comment by trungnt2910** [comment]
It has been clearly [documented](https://platform.uno/docs/articles/uno-app-solution-structure.html) that:

> Normally, your UI and business logic will go in the shared project. Bootstrapping code, packaging settings, and platform-specific code goes in the corresponding platform head. [String resources](https://platform.uno/docs/articles/features/working-with-strings.html) normally go in the shared project. [Image assets](https://platform.uno/docs/articles/features/working-with-assets.html) may go either in the shared project or under each head. **[Font assets](https://platform.uno/docs/articles/features/custom-fonts.html) must be placed under each head.**

(Emphasis mine)

However, being "documented" doesn't mean that it is _desired_ by most developers. Currently, putting a custom font in the `App.Shared/Assets/Fonts` folder works for the Windows, Skia and WASM targets, but fails for Android. I would prefer having the fonts in one location only to prevent duplicate files in the source tree.

**Comment by jeromelaban** [comment]
Yes, that's correct. For now we have not made changes to that behavior where fonts need to be included in very specific was for some platforms. Nonetheless, we've made progress on being able to package fonts in nuget packages, and this means that being able handle fonts in common locations soon.

**Comment by jeromelaban** [comment]
This is fixed by https://github.com/unoplatform/uno/pull/10797
