### ISSUE TITLE
[IOS] Lottie animation not working when AutoPlay is set to false

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#10312]
### Current behavior

![image](https://user-images.githubusercontent.com/90481654/199534860-6b9f443b-64e8-4b9f-bf2e-b6084a80e451.png)
The lottie doesnt load properly with the latest Uno.ui.Lottie nuggets, and you cannot activate it in the code behind. 

### Expected behavior

![image](https://user-images.githubusercontent.com/90481654/199535147-9439e5c1-59ed-4aff-a842-57601d45ba4b.png)
The lottie should load properly and when you make it play, it should start playing.

This was working as expected in Uno.UI.Lottie 4.3.8

The problem started in the next version: 4.4.5

### How to reproduce it (as minimally and precisely as possible)

[IOSLottie.zip](https://github.com/unoplatform/uno/files/9921988/IOSLottie.zip)

### Workaround

Using an older version of Uno.UI.Lottie.

Setting the autoplay to true also works, and if you leave the code behind, the animation only plays once.

### Works on UWP/WinUI

Yes

### Environment

Other

### NuGet package version(s)

Uno.UI.Lottie 4.4.5 - 4.7.0-dev.48

I only tried the latest pre-release and the stable versions.  I'm not sure what exact version between 4.3.8 and 4.4.5 it breaks.

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.3.6

### Anything else we need to know?

It is set to false because of this issue: 

https://github.com/microsoft/microsoft-ui-xaml/issues/1484#issuecomment-679435206

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/4.6
