### ISSUE TITLE
[iOS] Focused `TextBox` leaks

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10344]
### Current behavior

When a `TextBox` is focused, it causes a memory leak

### Expected behavior

Should not happen 

### How to reproduce it (as minimally and precisely as possible)

Enable the `TextBox_Focus_Leak` data row of `Given_FrameworkElement_And_Leak`

### Affected platforms

iOS

**Comment by jeromelaban** [comment]
The test is now enabled.

**Comment by MartinZikmund** [comment]
It is not yet unfortunately - 

![image](https://github.com/unoplatform/uno/assets/1075116/67c6c732-34b7-4cca-b123-2c029ebdf4a2)

I think I need to add `Assert.Inconclusive` in case the `LeakTestStyles` are `None`...
