### ISSUE TITLE
[Gtk] Reduce the number of assemblies in the sample rd.xml for Native AOT

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#10355]
Following https://github.com/unoplatform/uno/pull/10351, the number of assemblies found in the `rd.xml` file can be reduced or cleared based on changes made in GtkSharp.

Let's evaluate which ones can be removed and see how many features we can get running.

**Comment by kant2002** [comment]
Isn't this DOA (Done on arrival) ?

**Comment by jeromelaban** [comment]
It definitely is :D Thanks!

**Comment by jeromelaban** [comment]
Let's reopen as:
```xml
<Directives>
	<Application>
		<Assembly Name="GdkSharp">
			<Type Name="Gdk.Screen" Dynamic="Required All"/>
		</Assembly>
		<Assembly Name="GtkSharp">
			<Type Name="Gtk.WindowStateEventArgs" Dynamic="Required All"/>
		</Assembly>
	</Application>
</Directives>
```

is not enough to make the app work.

**Comment by MartinZikmund** [comment]
This is no longer relevant as GTK is kept for legacy purposes only
