### ISSUE TITLE
[Skia] Add support for `Window.ExtendsContentIntoTitleBar`

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#10368]
## What would you like to be added:

Add support for `Window.ExtendsContentIntoTitleBar` to alter the title bar of the app.

## Why is this needed:

Customized window layout.

## For which Platform:

- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)

**Comment by ivanjx** [comment]
can i use Window.ExtendsContentIntoTitleBar on windows with gtk head? my target for now is only on windows. i really want to try native aot compilation on windows. thanks.

**Comment by jeromelaban** [comment]
This PR may enable this behavior: https://github.com/unoplatform/uno/pull/13597

**Comment by manfromarce** [comment]
Could this be left open because it's not implemented in WPF?

**Comment by lindexi** [comment]
@manfromarce and @jeromelaban I add the implemented in WPF, see https://github.com/unoplatform/uno/pull/13740
