### ISSUE TITLE
Exists in both `Uno.UI` and `Microsoft.UI.Xaml.Controls`

### ISSUE THREAD

**Issue by guillaume-brouillon** [unoplatform/uno#10373]
### Current behavior

Adding reference to Uno.WinUI 4.6 to winui project of uno app project throws an error that controls exists in both uno.ui and microsoft namespaces. 
This isn't the case in uno 4.5.
This is problematic if one for example wants to use uno.winui.msal

### How to reproduce it (as minimally and precisely as possible)

create a uno app template
add reference to uno.winui.msal
try to build winui app

### Workaround

reference uno.winui.msal

### NuGet package version(s)

4.6

**Comment by jeromelaban** [comment]
Can you [provide a binlog](https://platform.uno/docs/articles/uno-builds-troubleshooting.html) of the issue?

**Comment by MartinZikmund** [comment]
@guillaume-brouillon Can you provide the binlog as requested above please?

**Comment by MartinZikmund** [comment]
@guillaume-brouillon We have not seen this issue happen recently, so I will close the issue for now. In case it occurs again, feel free to reply and reopen
