### ISSUE TITLE
Adding an item on ToDo List 

### ISSUE THREAD

**Issue by pictos** [unoplatform/uno#10378]
### Current behavior

So everything works like a charm on Windows you write a task and press the add button, it is added to the Collection and the ListView is updated. When we try to do that on mobile it crashes with this error:

![image](https://user-images.githubusercontent.com/20712372/200991695-c49f7e53-4fb2-4fba-9568-1a38111109b4.png)

looks like it's because the Converter used to change the [TextDecorations](https://github.com/angelobelchior/ToDoUnoApp/blob/main/ToDoUnoApp/ToDoUnoApp.Shared/MainPage.xaml.cs#L116-L130) 

on wasm nothing happens, I believe it fails silently.

### Expected behavior

The app doesn't crash when an item is added to the list.

### How to reproduce it (as minimally and precisely as possible)

- Checkout this repo https://github.com/angelobelchior/ToDoUnoApp
- Run the app and write something on the TextBlock
- Press the add button
- When you see the item on the list, check and uncheck the checkboxCheck out

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly, Android

### IDE

Visual Studio 2022

### IDE version

17.3.6

**Comment by jeromelaban** [comment]
This looks more like WinUI issue, where having a two-way binding here does not make sense. If the issue happens on Windows, we generally cannot change anything.

**Comment by pictos** [comment]
Thanks
