### ISSUE TITLE
When using a Converter inside a ListView it just works once 

### ISSUE THREAD

**Issue by pictos** [unoplatform/uno#10377]
### Current behavior

When we check the CheckBox of the ToDoItem the text is decorated like this but when you uncheck the TextDecoration doesn't update, if you set the breakpoint inside the converter it will hit. So the UI isn't updated. Maybe he is using it wrong(?)
Video with the actual behavior: https://youtu.be/YklgmykrPvI

### Expected behavior

The Text appearance changes when I check and uncheck the `CheckBox`

### How to reproduce it (as minimally and precisely as possible)

- Checkout this repo https://github.com/angelobelchior/ToDoUnoApp
- Run the app and write something on the TextBlock
- Press the add button
- When you see the item on the list, check and uncheck the checkbox

### Works on UWP/WinUI

No

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.6.19

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

17.3.6

**Comment by jeromelaban** [comment]
This is a windows issue, see here for a workaround: https://stackoverflow.com/a/52773734 (using a nested `Run`)
