### ISSUE TITLE
[Wasm] FocusManager does not handle the browser window losing focus

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#1037]
## Current behavior

When a `TextBox` has the focus, and the user deactivates/unfocuses the browser window, the `TextBox` does not lose focus. The `LostFocus` event is raised, but is not used by the `FocusManager`.

## Expected behavior

The TextBox properly loses focus when the browser window loses the focus.

## Environment

Nuget Package:

Package Version(s): 1.44

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by yowl** [comment]
thanks!
