### ISSUE TITLE
[WASM] `HttpClient` cannot be created after updating to .NET 7

### ISSUE THREAD

**Issue by kevin100702** [unoplatform/uno#10397]
### Current behavior

I have a .net standard 2.0 class library. Create an HttpClient in it and request data from the webapi. When I upgrade to .net 7 and have UNO.UI 4.6.19, I get the following error:

The type initializer for 'System.Net.Http.BrowserHttpHandler' threw an exception

```
System. Net. Http. HttpClientHandler.. ctor () in 
D:\ a\ Uno. DotnetRuntime. WebAssembly\ Uno. DotnetRuntime. WebAssembly\ runtime\ src\ libraries\ System. Net. Http\ src\ System\ Net\ Http\ HttpClientHandler.cs: line 38
At System. Net. Http. HttpClient.. ctor () in D:\ a\ Uno. DotnetRuntime. WebAssembly\ Uno. DotnetRuntime. WebAssembly\ runtime\ src\ libraries\ System. Net. Http\ src\ System\ Net\ Http\ HttpClient.cs: line 140
```

It works fine on .net6.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.UI.RemoteControl / Uno.WinUI.RemoteControl

### NuGet package version(s)

4.6.19

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.4

**Comment by jeromelaban** [comment]
Can you provide the version of Uno.Wasm.Bootstrap that you are using?

**Comment by michalss** [comment]
Same here, httpclient does not work net7 and wasm.

**Comment by michalss** [comment]
`webadmin.Services.WebApiService.Login [d:\Private\Projects\csharp\LOKALIZACE_NET\webadmin.project\webadmin.project\webadmin.project.Shared\Services\WebApiService.cs] Line 44	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox<webadmin.shared.UserInfo, webadmin.Services.WebApiService.<Login>d__9>.ExecutionContextCallback [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 286	JavaScript
 	System.Threading.ExecutionContext.RunInternal [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs] Line 183	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox<webadmin.shared.UserInfo, webadmin.Services.WebApiService.<Login>d__9>.MoveNext [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 324	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox<webadmin.shared.UserInfo, webadmin.Services.WebApiService.<Login>d__9>.MoveNext [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 302	JavaScript
 	System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs] Line 795	JavaScript
 	System.Threading.Tasks.Task.RunContinuations [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 3410	JavaScript
 	System.Threading.Tasks.Task.FinishContinuations [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 3386	JavaScript
 	System.Threading.Tasks.Task.FinishStageThree [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 2137	JavaScript
 	System.Threading.Tasks.Task.FinishStageTwo [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 2107	JavaScript
 	System.Threading.Tasks.Task.FinishSlow [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 1999	JavaScript
 	System.Threading.Tasks.Task.Finish [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 1988	JavaScript
 	System.Threading.Tasks.Task.TrySetException [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 3324	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder<webadmin.shared.UserInfo>.SetException [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 472	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder<webadmin.shared.UserInfo>.SetException [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 459	JavaScript
 	webadmin.services.HttpService.Post<UserInfo> [d:\Private\Projects\csharp\LOKALIZACE_NET\webadmin.project\webadmin.project\webadmin.project.Shared\Services\HttpService.cs] Line 151	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox<webadmin.shared.UserInfo, webadmin.services.HttpService.<Post>d__12<webadmin.shared.UserInfo>>.ExecutionContextCallback [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 286	JavaScript
 	System.Threading.ExecutionContext.RunInternal [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs] Line 183	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox<webadmin.shared.UserInfo, webadmin.services.HttpService.<Post>d__12<webadmin.shared.UserInfo>>.MoveNext [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 324	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox<webadmin.shared.UserInfo, webadmin.services.HttpService.<Post>d__12<webadmin.shared.UserInfo>>.MoveNext [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 302	JavaScript
 	System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs] Line 795	JavaScript
 	System.Threading.Tasks.Task.RunContinuations [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 3410	JavaScript
 	System.Threading.Tasks.Task.FinishContinuations [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 3386	JavaScript
 	System.Threading.Tasks.Task.FinishStageThree [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 2137	JavaScript
 	System.Threading.Tasks.Task.FinishStageTwo [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 2107	JavaScript
 	System.Threading.Tasks.Task.FinishSlow [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 1999	JavaScript
 	System.Threading.Tasks.Task.Finish [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 1988	JavaScript
 	System.Threading.Tasks.Task.TrySetException [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 3324	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Net.Http.HttpResponseMessage>.SetException [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 472	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Net.Http.HttpResponseMessage>.SetException [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 459	JavaScript
 	System.Net.Http.HttpClient/<<SendAsync>g__Core|83_0>d:MoveNext () [System.Net.Http.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs] Line 556	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox<System.Net.Http.HttpResponseMessage, System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d>.ExecutionContextCallback [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 286	JavaScript
 	System.Threading.ExecutionContext.RunInternal [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs] Line 183	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox<System.Net.Http.HttpResponseMessage, System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d>.MoveNext [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 324	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox<System.Net.Http.HttpResponseMessage, System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d>.MoveNext [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 302	JavaScript
 	System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs] Line 795	JavaScript
 	System.Threading.Tasks.Task.RunContinuations [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 3410	JavaScript
 	System.Threading.Tasks.Task.FinishContinuations [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 3386	JavaScript
 	System.Threading.Tasks.Task.FinishStageThree [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 2137	JavaScript
 	System.Threading.Tasks.Task.FinishStageTwo [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 2107	JavaScript
 	System.Threading.Tasks.Task.FinishSlow [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 1999	JavaScript
 	System.Threading.Tasks.Task.Finish [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 1988	JavaScript
 	System.Threading.Tasks.Task.TrySetException [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 3324	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Net.Http.HttpResponseMessage>.SetException [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 472	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Net.Http.HttpResponseMessage>.SetException [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 459	JavaScript
 	Uno.UI.Wasm.WasmHttpHandler/<SendAsync>d__2:MoveNext () [Uno.UI.Runtime.WebAssembly.dll/C/a/1/s/src/Uno.UI.Runtime.WebAssembly/WasmHttpHandler.cs] Line 95	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox<System.Net.Http.HttpResponseMessage, Uno.UI.Wasm.WasmHttpHandler.<SendAsync>d__2>.ExecutionContextCallback [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 286	JavaScript
 	System.Threading.ExecutionContext.RunInternal [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs] Line 183	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox<System.Net.Http.HttpResponseMessage, Uno.UI.Wasm.WasmHttpHandler.<SendAsync>d__2>.MoveNext [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 324	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox<System.Net.Http.HttpResponseMessage, Uno.UI.Wasm.WasmHttpHandler.<SendAsync>d__2>.MoveNext [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 302	JavaScript
 	System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs] Line 795	JavaScript
 	System.Threading.Tasks.Task.RunContinuations [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 3410	JavaScript
 	System.Threading.Tasks.Task.FinishContinuations [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 3386	JavaScript
 	System.Threading.Tasks.Task.FinishStageThree [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 2137	JavaScript
 	System.Threading.Tasks.Task.FinishStageTwo [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 2107	JavaScript
 	System.Threading.Tasks.Task.FinishSlow [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 1999	JavaScript
 	System.Threading.Tasks.Task.Finish [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 1988	JavaScript
 	System.Threading.Tasks.Task.TrySetException [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs] Line 3324	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.ValueTuple<int, string, string>>.SetException [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 472	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.ValueTuple<int, string, string>>.SetException [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 459	JavaScript
 	Uno.Threading.FastTaskCompletionSource<ValueTuple<int, string, string>>.CreateAsyncTask [Uno.Foundation.dll//home/vsts/work/1/s/src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Threading/FastTaskCompletionSource.cs] Line 368	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox<System.ValueTuple<int, string, string>, Uno.Threading.FastTaskCompletionSource.<CreateAsyncTask>d__38<System.ValueTuple<int, string, string>>>.ExecutionContextCallback [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 286	JavaScript
 	System.Threading.ExecutionContext.RunInternal [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs] Line 183	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox<System.ValueTuple<int, string, string>, Uno.Threading.FastTaskCompletionSource.<CreateAsyncTask>d__38<System.ValueTuple<int, string, string>>>.MoveNext [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 324	JavaScript
 	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox<System.ValueTuple<int, string, string>, Uno.Threading.FastTaskCompletionSource.<CreateAsyncTask>d__38<System.ValueTuple<int, string, string>>>.MoveNext [System.Private.CoreLib.dll/D/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs] Line 302	JavaScript
 	Uno.Threading.FastTaskCompletionSource<System.ValueTuple<int, string, string>>.RaiseOnCompleted [Uno.Foundation.dll//home/vsts/work/1/s/src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Threading/FastTaskCompletionSource.cs] Line 265	JavaScript
 	Uno.Threading.FastTaskCompletionSource<System.ValueTuple<int, string, string>>.TrySetException [Uno.Foundation.dll//home/vsts/work/1/s/src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Threading/FastTaskCompletionSource.cs] Line 184	JavaScript
 	Uno.Threading.FastTaskCompletionSource<System.ValueTuple<int, string, string>>.SetException [Uno.Foundation.dll//home/vsts/work/1/s/src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Threading/FastTaskCompletionSource.cs] Line 138	JavaScript
 	Uno.UI.Wasm.WasmHttpHandler.DispatchError [Uno.UI.Runtime.WebAssembly.dll/C/a/1/s/src/Uno.UI.Runtime.WebAssembly/WasmHttpHandler.cs] Line 119	JavaScript
 	mono_wasm_fire_debugger_agent_message [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.js] Line 3	JavaScript
 	$func858 [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.wasm] Line 1	JavaScript
 	$func1029 [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.wasm] Line 1	JavaScript
 	$func955 [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.wasm] Line 1	JavaScript
 	$func954 [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.wasm] Line 1	JavaScript
 	$func889 [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.wasm] Line 1	JavaScript
 	$func855 [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.wasm] Line 1	JavaScript
 	$func281 [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.wasm] Line 1	JavaScript
 	$func224 [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.wasm] Line 1	JavaScript
 	$func223 [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.wasm] Line 1	JavaScript
 	$func8122 [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.wasm] Line 1	JavaScript
 	$func2056 [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.wasm] Line 1	JavaScript
 	$func2061 [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.wasm] Line 1	JavaScript
 	$func2088 [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.wasm] Line 1	JavaScript
 	$mono_wasm_invoke_method_ref [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.wasm] Line 1	JavaScript
 	Module._mono_wasm_invoke_method_ref [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/dotnet.js] Line 14	JavaScript
 	_Uno_UI_Runtime_WebAssembly__Uno_UI_Wasm_WasmHttpHandler_DispatchError [dotnet.generated.invalid/_Uno_UI_Runtime_WebAssembly__Uno_UI_Wasm_WasmHttpHandler_DispatchError] Line 27	JavaScript
 	dispatchError [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/Uno.UI.js] Line 221	JavaScript
 	send [localhost꞉5000/package_faa713270acd76cb441e2b4df8b78913366b1fc1/Uno.UI.js] Line 195	JavaScript
`

**Comment by jeromelaban** [comment]
@michalss It looks like you're using `WasmHttpHandler`, it's now deprecated and you can use the original .NET HttpHandler. It's a different issue from the OP.

**Comment by MartinZikmund** [comment]
@kevin100702 is this still happening?

**Comment by kevin100702** [comment]
For some reason I am not using UNO WASM anymore, I will close this issue
