### ISSUE TITLE
ToolTip not showing on Skia.Wpf

### ISSUE THREAD

**Issue by maaxe** [unoplatform/uno#10401]
### Current behavior

ToolTips are not visible

### Expected behavior

ToolTips visible

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.6.19

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.3.4

**Comment by MartinZikmund** [comment]
Because tooltips are not yet completely stable, they are currently hidden behind feature flag. You can however enable them by using `FeatureConfiguration` [see here](https://github.com/unoplatform/uno/blob/0299aad257d0a1bec25706b4189e8d199e884b47/src/Uno.UI/FeatureConfiguration.cs#LL512C26-L512C26)

```
#if __SKIA__
FeatureConfiguration.ToolTip.UseToolTips = true;
#endif

**Comment by maaxe** [comment]
Thanks, that works :)

May I ask what the stability issues are, just so I know the "risks" of using them?
