### ISSUE TITLE
Unable to run Android UI tests locally

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10430]
### Current behavior

When trying to run a Android UI test locally, the following error is reported:

```
OneTimeSetUp: System.TypeInitializationException : The type initializer for 'SamplesApp.UITests.SampleControlUITestBase' threw an exception.
  ----> System.Exception : Failed to execute: C:\Program Files (x86)\Android\android-sdk\build-tools\33.0.0\apksigner.bat sign --help - exit code: 1

ERROR: JAVA_HOME is set to an invalid directory: C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25
```

Oddly, the `JAVA_HOME` variable is set correctly: 

![image](https://user-images.githubusercontent.com/1075116/201701697-f5f2eace-5eba-4173-ae0e-03d0a8954228.png)

### Expected behavior

Should work.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.4.0

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/pull/8364/files

> For Android, ensure that your system-level environment variables `JAVA_HOME` and `ANDROID_HOME` are set to the same values as the ones set in Visual Studio's Xamarin Android options panel.

@MartinZikmund Did you confirm the values are the same as Visual Studio?

**Comment by MartinZikmund** [comment]
This worked recently, so closing for now. Will reopen if I hit again
