### ISSUE TITLE
[Skia] Implement `Application.Exit`

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#10436]
### Discussed in https://github.com/unoplatform/uno/discussions/10404

<div type='discussions-op-text'>

<sup>Originally posted by **mcNets** November 11, 2022</sup>
Exit method is working now, it was solved in this PR https://github.com/unoplatform/uno/pull/10001

But compiler still throwing a warning:

`warning Uno0001: Microsoft.UI.Xaml.Application.Exit() is not implemented in Uno`</div>

## Additional details

This method is not implemented at this time, but `CoreApplication.Exit` was implemented in  https://github.com/unoplatform/uno/pull/10001. Implementing `Application.Exit` is about calling one from the other.

**Comment by mcNets** [comment]
In fact I'm using App.Current?.Exit()

**Comment by MartinZikmund** [comment]
@mcNets The warning was just false-positive and the exit flow should be working anyway. Thanks to #10457 you should no longer see the warning if you update to the latest packages 👍

**Comment by mcNets** [comment]
Thankyou! 👍
