### ISSUE TITLE
Limited support for ItemsControl.Items

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#1045]
## What would you like to be added:
`ItemsControl.Items` isn't well supported. At the moment in Uno it's normally only populated at all when setting items in XAML. (Eg `<ListView><TextBlock Text="Item1"/>...`)

Missing features:

 - [ ] `Items` should mirror `ItemsSource`
 - [ ] Adding to `Items` should update the list
 - [ ] ?

## Why is this needed:
Compatibility with UWP. In most cases it's possible to use `ItemsSource` instead, but this is a common 'gotcha.'

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

## Anything else we need to know?

Related to #2347

**Comment by jeromelaban** [comment]
Related to #2347
