### ISSUE TITLE
[Skia] Visual rendering is not smooth

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#10461]
### Current behavior

When something produces the visual to be changed like animation or size changing the surface is redrawn glitchy. 
Looks like the FPS of the rendering engine is low or the surface invalidation are made with a delay by Uno itself for performance reason?

### Expected behavior

Smooth rendering including animations

### How to reproduce it (as minimally and precisely as possible)

1. Create Skia project
2. Set background to any color than white
3, Rapidly change the window size to see that the background color is filled with a delay

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

### IDE

Visual Studio 2022

### Anything else we need to know?

Or do you have a configuration for that?

**Comment by jeromelaban** [comment]
This type of visual artifact is expected, as the rendering is not done synchronously with the window layout changes. You can see this in most applications (even browsers). 

Nonetheless, the actual duration of that artifact is something that can be improved. We have some work coming that may improve that, depending on the rendering backend being used (it's more visible with software rendering, for instance).

**Comment by jeromelaban** [comment]
The WPF head is currently not supporting hardware rendering, we intend to change that in the future. The GTK head is running with hardware rendering when available, and those artifacts should be less visible.
