### ISSUE TITLE
Setting RequestedTheme doesn't work

### ISSUE THREAD

**Issue by NGame1** [unoplatform/uno#1047]
## Current behavior

Setting Requested Theme in App.xaml  or on a Page doesn't affect. 

## Environment
Nuget Package:

UNO.UI 1.44.1
Uno.UniversalImageLoader 1.9.32
Uno.wasm.Bootstrap 1.0.0-dev.137

Package Version(s):

Affected platform(s):
- [ ] iOS (Didn't tried) 
- [ x ] Android
- [ x ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ x ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?

Windows 10 May Update
Windows 10 build 1809 UWP sdk

**Comment by jeromelaban** [comment]
This feature request is linked to #119

**Comment by carldebilly** [comment]
`Application.Current.RequestedTheme` works now.

`<element>.RequestedTheme` still not implemented yet.

**Comment by NGame1** [comment]
@carldebilly nice. Does theme based ResourceDictionaries also work?

**Comment by carldebilly** [comment]
We just published a new version of the _Windows Calculator_ which is using themes.  We also implemented a way to invoke _custom themes_ like `HighContrast` or even user-defined themes (something not available in UWP).

## Declaration
https://github.com/unoplatform/calculator/blob/6d2c7c2664fdb6124cae4560f231e6fac8f4cbd9/src/Calculator.Shared/Styles.xaml#L199

## Usage
https://github.com/unoplatform/calculator/blob/6d2c7c2664fdb6124cae4560f231e6fac8f4cbd9/src/Calculator.Shared/App.xaml.cs#L82

I'll close this issue, feel free to reopen it if you think it's required.
