### ISSUE TITLE
Red and Blue colors are swapped on Raspberry Pi Framebuffer Arm64

### ISSUE THREAD

**Issue by HakanL** [unoplatform/uno#10474]
### Current behavior

When displaying content on the Framebuffer Linux platform I'm getting red and blue swapped. If I create a button with color red then it will be blue, and vice versa. Green is correct. I have tried to just plot an image to the buffer using the FBI tool, and it's correct, so I believe the issue is with Uno. I found [this](https://github.com/unoplatform/uno/issues/8580), which could be related, maybe it's an issue with all ARM64 platform?
Suspected code lines: https://github.com/unoplatform/uno/blob/ed0a36c5bf71ccde37d9b8ee4f991b5ea8855242/src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs#L44

### Expected behavior

Red should be red and Blue should be blue

### How to reproduce it (as minimally and precisely as possible)

Display any content with blue or red colors on the Linux Framebuffer platform on RPi4. I have tested this on both CM4 (Compute Module 4) and a standard Raspberry Pi 4 board, same issue.

### Workaround

None that I'm aware of.

### Works on UWP/WinUI

Yes

### Environment

Other

### NuGet package version(s)

4.6.0-dev.962
2.3.0-dev.300 (extensions)

### Affected platforms

Skia (Linux Framebuffer)

### IDE

Visual Studio 2022

### IDE version

17.4

**Comment by jeromelaban** [comment]
Thanks for the report. Can you enable those logs for the following class `Uno.UI.Runtime.Skia.FrameBufferHost`? You can find that in the [InitializeLogger](https://github.com/unoplatform/uno/blob/0eea2c00d1d024290cb9bcfce0da76faeeab783f/src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Shared/App.xaml.cs#L117) function.

**Comment by HakanL** [comment]
Sure, I get this:
`dbug: Uno.UI.Runtime.Skia.FrameBufferHost[0]
      Display Information: 800x480 (-1,-1 mm), PixelFormat: Rgba8888, ResolutionScale: Scale100Percent, LogicalDpi: 96, RawPixelsPerViewPixel: 1, DiagonalSizeInInches: , ScreenInRawPixels: 800x480`

**Comment by HakanL** [comment]
As I was testing it from the console, I installed fbi, which is a frame buffer image viewer and it displayed the correct colors. In their source code they seem to check for little endian, I wonder if it's something like that? Maybe that would be a safer/better check than ARM64?
https://git.kraxel.org/cgit/fbida/tree/gfx.c#n24

**Comment by jeromelaban** [comment]
Thanks. Can you provide the outputs of `fbset -i` ?

**Comment by HakanL** [comment]
```
root@ef86ede:~/VSLinuxDbg/App9.Skia.Linux.FrameBuffer# fbset -i

mode "800x480"
    geometry 800 480 800 480 32
    timings 0 0 0 0 0 0 0
    rgba 8/16,8/8,8/0,8/24
endmode

Frame buffer device information:
    Name        : BCM2708 FB
    Address     : 0x3ee41000
    Size        : 1536000
    Type        : PACKED PIXELS
    Visual      : TRUECOLOR
    XPanStep    : 1
    YPanStep    : 1
    YWrapStep   : 0
    LineLength  : 3200
    Accelerator : No
```

**Comment by jeromelaban** [comment]
Interesting, so for your device, the format really is bgra. We'll need to account for this, thanks for the update.

**Comment by HakanL** [comment]
@jeromelaban Any way I can contribute to this? I don't have a good workaround to get the colors to display correctly on my RPi device. Would it be as simple as changing the check in the FB code for Arm64, assuming this is the same issue on all Arm64 devices? Or are you looking to do a different solution?

**Comment by jeromelaban** [comment]
@HakanL! The code that handles this is located here:

https://github.com/unoplatform/uno/blob/0b101cd517a9e3e71bacd75c0309c7cd6d8b8ff4/src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FrameBufferDevice.cs#L42-L52

By the specified values from fbset, it looks like we're not setting giving the right settings to Skia.

**Comment by HakanL** [comment]
With some reflection I was able to read out the blue.offset value, which on my RPi is set to 0. Looking at the code you linked to,
Here's a dump of the _screenInfo, I'm not entirely sure what the fix should be for this issue, at a quick glance is looks like the if case you linked above should be reversed, but I'm sure that's not the correct fix?
```
screenInfo: Uno.UI.Runtime.Skia.Native.fb_var_screeninfo
xres = 800
yres = 480
xres_virtual = 800
yres_virtual = 480
xoffset = 0
yoffset = 0
bits_per_pixel = 32
grayscale = 0
red
  red.offset = 16
  red.length = 8
  red.msb_right = 0
green
  green.offset = 8
  green.length = 8
  green.msb_right = 0
blue
  blue.offset = 0
  blue.length = 8
  blue.msb_right = 0
transp
  transp.offset = 24
  transp.length = 8
  transp.msb_right = 0
nonstd = 0
activate = 0
height = 4294967295
width = 4294967295
accel_flags = 0
pixclock = 0
left_margin = 0
right_margin = 0
upper_margin = 0
lower_margin = 0
hsync_len = 0
vsync_len = 0
sync = 0
vmode = 0
reserved
  reserved.FixedElementField = 0
```

**Comment by HakanL** [comment]
@jeromelaban It seems that you reversed these back in Aug: https://github.com/unoplatform/uno/commit/3dab8771a69dccc8f880f6d7a7b902b1b881653a
as part of this PR: https://github.com/unoplatform/uno/pull/9449

**Comment by jeromelaban** [comment]
This would mean that there's an additional scenario that is not yet covered. I modified those to work on a Raspberry Pi 3, specifically.

**Comment by HakanL** [comment]
What do you think about adding a way where someone can override the PixelFormat in the host options (or something along those lines)? At least until the detection routine is tweaked? FWIW I'm running this on a Raspberry CM4, but I have verified the same issue on a regular Raspberry Pi 4.

**Comment by jeromelaban** [comment]
Workarounding like this is generally not a good way to handle these scenarions. You can try building Uno by yourself to find out what happens, though.

**Comment by HakanL** [comment]
> Workarounding like this is generally not a good way to handle these scenarions. You can try building Uno by yourself to find out what happens, though.

I agree, I guess we need to dump the FB info data on a RPi3 as well so we can compare and figure out what the detection logic should look like. The change back in Aug may have fixed RPi3, but it broke RPi4 :)

**Comment by HakanL** [comment]
Here's the screeninfo on RPi 3B running 32-bit Rasp OS at default (accelerated 3d-driver loaded). Note that the 3d-driver forces 16-bit FB mode. This works fine with Uno:
```
Pixel Format: Rgb565

xres = 1920
yres = 1200
xres_virtual = 1920
yres_virtual = 1200
xoffset = 0
yoffset = 0
bits_per_pixel = 16
grayscale = 0
red
   .red.offset = 11
   .red.length = 5
   .red.msb_right = 0
green
   .green.offset = 5
   .green.length = 6
   .green.msb_right = 0
blue
   .blue.offset = 0
   .blue.length = 5
   .blue.msb_right = 0
transp
   .transp.offset = 0
   .transp.length = 0
   .transp.msb_right = 0
nonstd = 0
activate = 0
height = 320
width = 520
accel_flags = 1
pixclock = 0
left_margin = 0
right_margin = 0
upper_margin = 0
lower_margin = 0
hsync_len = 0
vsync_len = 0
sync = 0
vmode = 0
reserved
   .reserved.FixedElementField = 0
```

But if I disable the accelerated 3d-driver so the framebuffer is 32-bit then I'm getting the switched colors and this is the screen info:
```
Pixel Format: Rgba8888

xres = 1920
yres = 1200
xres_virtual = 1920
yres_virtual = 1200
xoffset = 0
yoffset = 0
bits_per_pixel = 32
grayscale = 0
red
   .red.offset = 16
   .red.length = 8
   .red.msb_right = 0
green
   .green.offset = 8
   .green.length = 8
   .green.msb_right = 0
blue
   .blue.offset = 0
   .blue.length = 8
   .blue.msb_right = 0
transp
   .transp.offset = 24
   .transp.length = 8
   .transp.msb_right = 0
nonstd = 0
activate = 0
height = 4294967295
width = 4294967295
accel_flags = 0
pixclock = 0
left_margin = 0
right_margin = 0
upper_margin = 0
lower_margin = 0
hsync_len = 0
vsync_len = 0
sync = 0
vmode = 0
reserved
   .reserved.FixedElementField = 0
```

It would be good to be able to reproduce the correct colors under 32-bit FB on RPI3, @jeromelaban do you know how your RPi3 may have been configured? I have only tested with 32-bit OS (but 64-bit on RPi4, however same issue so far). Your change is also odd, because the setting says "blue color bit offset: 0", which means it would be first = Format=Bgra8888 (B is first). And the other colors match as well. Going off the offsets indicates: BGRA, which seem to indicate that your Aug commit is incorrect.

**Comment by jeromelaban** [comment]
That's indeed correct, my RPi 4 was indeed using a 16bits color depth and I did not see the 32 bits issue.

For information, on a RPi 4, disabling the 3D acceleration mode requires the commenting of all lines `dtoverlay=` in the `/boot/firmware/config.txt` file.

**Comment by HakanL** [comment]
> For information, on a RPi 4, disabling the 3D acceleration mode requires the commenting of all lines `dtoverlay=` in the `/boot/firmware/config.txt` file.

Yup, that's how I disabled the 3D acceleration (because FB doesn't use that, and I prefer to get 24-bit colors).
Your PR looks good, but the comment in the code says "RPi 4B", but if these values are from my details above then it's actually a RPi 3B (but the first details I added were from RPi 4), just wanted to make sure the comment is accurate (even if I believe the RPi 3 and 4 will have identical values).

**Comment by jeromelaban** [comment]
Thanks. The RPi 4B 16bits comes from my own runs when validating the results, so we're good on that.

**Comment by HakanL** [comment]
Ah, good, wasn’t sure. Thanks!On Dec 15, 2022, at 8:09 PM, Jérôme Laban ***@***.***> wrote:﻿
Thanks. The RPi 4B 16bits comes from my own runs when validating the results, so we're good on that.

**Comment by HakanL** [comment]
@jeromelaban Happy to report that build dev-666 works great on my RPi CM4 set up now, correct colors displayed! Thank you!

**Comment by jeromelaban** [comment]
Thanks for the update, and thanks for the investigation!
