### ISSUE TITLE
[Skia] `TextBlock` text selection support

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#10483]
## What would you like to be added:
Text selection implementation for TextBlock

## Why is this needed:
Allow a text to be selected, copied

**Comment by Youssef1313** [comment]
This should be already supported on Wasm.
Though it's not supported on other platforms yet.

**Comment by jeromelaban** [comment]
@FrozDark we'll need more information about this, as most platforms already provide this feature. Which one are you talking about ?

**Comment by FrozDark** [comment]
> @FrozDark we'll need more information about this, as most platforms already provide this feature. Which one are you talking about ?

Sorry for late answer. Skia based platforms

**Comment by jeromelaban** [comment]
@MartinZikmund does you recent work address parts of this for Skia ?

**Comment by MartinZikmund** [comment]
@jeromelaban Not for `TextBlock` unfortunately, I made changes for `TextBox` only. This will require some custom handling for the highlighting, etc.

**Comment by jeromelaban** [comment]
Ah right, I mixed up with TextBox :) It's definitely not part of you work indeed.

**Comment by MartinZikmund** [comment]
Provisionally assigning to you @ramezgerges 😇
