### ISSUE TITLE
[uwp] ImplementedRoutedEventsGenerators is running for uap heads

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#10556]
### Current behavior

The following error happens when building on uap:

https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=62837&view=logs&j=0dc1814f-f088-5668-f0ec-a84d5db9244c&t=9e6a612c-87b8-50a4-4ec8-5ae197b4162e&l=3685

```
>D:\a\1\s\src\library\Uno.Material\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.ImplementedRoutedEvents.ImplementedRoutedEventsGenerator\Uno.Material.Ripple_ImplementedRoutedEvents.g.cs(7,33): 
error CS0234: The type or namespace name 'Xaml' does not exist in the namespace 'Uno.UI' 
(are you missing an assembly reference?) [D:\a\1\s\src\library\Uno.Material\Uno.Material.csproj]
```

### Expected behavior

Compilation runs properly.

### How to reproduce it (as minimally and precisely as possible)

Update uno.themes to the latest uno.ui.

### Workaround

None.

**Comment by jeromelaban** [comment]
@Youssef1313 could you take a look if you have some time? Thanks!

**Comment by Youssef1313** [comment]
@jeromelaban I have a `PlatformHelper.IsValidPlatform` call in the generator, so it shouldn't run 😕

**Comment by Youssef1313** [comment]
@jeromelaban I took a quick look, it looks like `<TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>` is missing in `Uno.Material.csproj` (the project that fails) when it's built under `TargetFramework=uap10.0.18362`.

Note that Xaml generator is also run for this project, it just doesn't cause problems because the generator crashes.

> Generator 'XamlCodeGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The path is not of a legal form.'
