### ISSUE TITLE
[iOS] ButtonBase commands not working with VoiceOver turned on

### ISSUE THREAD

**Issue by CBrunet2212** [unoplatform/uno#10557]
### Current behavior

When voiceover is turned on on an iOS device, the Command on a RadioButton control will not execute.

### Expected behavior

When voiceover is turned on on an iOS device, the Command on a RadioButton control would execute.

### How to reproduce it (as minimally and precisely as possible)

- Create Uno app or use UnoAppTemplate
- Anywhere, put a RadioButton control and bind to it's Command property a piece of code
- Turn on voiceOver on your device
- In the app, focus the radio button and double-tap it to select it
- Notice the command is not executed 

### Workaround

None found

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI 4.4.20

### Affected platforms

iOS

### Anything else we need to know?

There was[ a similar issue](https://github.com/unoplatform/nventive-private/issues/231) created about a year ago where a fix had been merged into Master, but looking into it now it seems like the fix is gone and the issue is still occuring.
[UnoApplicationTemplate-main.zip](https://github.com/unoplatform/uno/files/10085349/UnoApplicationTemplate-main.zip)

**Comment by silviuo** [comment]
Hello, just reviving the thread. Any updates on this? Thanks!

**Comment by kazo0** [comment]
Looks like this occurs for all ButtonBase controls on iOS
