### ISSUE TITLE
Provide `Intent` access for android pickers

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#10550]
_Originally posted by @jeromelaban in https://github.com/unoplatform/uno/discussions/10536#discussioncomment-4209072_

Access to the `Intent` used to show FileOpenPicker and FileSavePicker is not possible at this time. 

## For contributors

It may be possible provide a way to access the intent before it is started, such as:
```csharp
var disposable = FileOpenPickerHelper.RegisterOnBeforeStartActivity(
   picker, 
   intent => intent.AddFlags(Android.Content.ActivityFlags.GrantPersistableUriPermission));
```

Which would set allow the user to set a callback directly into `FileOpenPicker` for android.

Creating a class like this one:

```csharp
public static class FileOpenPickerHelper
{
   public static IDisposable RegisterOnBeforeStartActivity(FileOpenPicker picker, Action<Intent> action)
      => picker.RegisterOnBeforeStartActivity(action);
}
```

Then building the same method internally in the Open/Save picker android implementations would be sufficient.

**Comment by Manishpandey11** [comment]
Hi,
I want to work on this issue. Can you let me know How I can solve this issue

**Comment by jeromelaban** [comment]
Hi @Manishpandey11, you can start by taking a look at [how to contribute code](https://platform.uno/docs/articles/uno-development/ways-to-contribute.html#contributing-code). The rest is detailed in the issue description above.

**Comment by jp-weber** [comment]
@MartinZikmund @jeromelaban 
I would like to take the issue and create a pull request.

**Comment by MartinZikmund** [comment]
Sounds good @jp-weber , will assign you!

**Comment by Robert-Louis** [comment]
@jp-weber I'm looking at issue link to this (In fact link to your original issue ([10536](https://github.com/unoplatform/uno/discussions/10536)). How is it going on your side ?

**Comment by jp-weber** [comment]
@Robert-Louis I implemented my idea over the weekend, but I have not yet been able to test it. Maybe I will get to it this weekend.

**Comment by jp-weber** [comment]
@Robert-Louis 
I create my commit https://github.com/jp-weber/uno/commit/8c02a44a23fb5fc65eeb2442b8277ea02399a268 but I could not test the implementation yet because of dotnet workload problems.
