### ISSUE TITLE
Improve the Get Started Wizard

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10552]
## What would you like to be added:

- [ ] **Provide command line snippets to run uno-check quickly** - very important for new users
- [ ] Support light/dark theme (for dark theme VS users)
- [ ] Provide prerequisites info directly on the page
- [ ] Provide a way to send quick feedback/sign up for newsletter
- [ ] Get rid of hamburger menu and header (they don't work anyway)

![image](https://user-images.githubusercontent.com/1075116/203795685-dc728b03-2d77-42f3-ade3-b4829f40ddbc.png)

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by sasakrsmanovic** [comment]
What is the URL you are seeing the hamburger menu at?

**Comment by sasakrsmanovic** [comment]
Hamburger menu should be displayed only on mobile devices. Let me know.

**Comment by MartinZikmund** [comment]
@sasakrsmanovic This shows up in Visual Studio after a new Uno app is created - e.g.:
![image](https://user-images.githubusercontent.com/1075116/234858085-ff5116de-ae96-42c1-a456-d6c3e271db99.png)

The specific URL is https://platform.uno/docs/articles/get-started-wizard.html.

In case of Visual Studio, I think the whole top header part is unnecessary - 
![image](https://user-images.githubusercontent.com/1075116/234858256-50cf7f29-5d40-4ec8-9b58-59de5883081e.png)

Especially because when I make Visual Studio window more narrow, this happens:

![image](https://user-images.githubusercontent.com/1075116/234858434-41cb91f7-725a-45cd-b98a-1d0a1ca84594.png)
 
The hamburger button does not do anything in this case, just jumps around.

Also on the screenshot you can see the doc does not fit well into VS when dark theme is used.

**Comment by jeromelaban** [comment]
The wizards is lots better now
