### ISSUE TITLE
Add support of the ISelectionInfo in ListView

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#10560]
## What would you like to be added:
`ListView` (and `GridView`) should support the [`ISelectionInfo`](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.iselectioninfo?view=winrt-22621)

## Why is this needed:
Because it's  WinUI contact :)

## For which Platform:
- [x] WebAssembly
- [x] Android
- [x] iOS
- [x] macOS (AppKit)
- [x] Mac Catalyst
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Linux Framebuffer
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by Xiaoy312** [comment]
of note: 
for any method/property that have side effect, it is the caller's responsive it call on the ui-thread.
this is true for everything under `(Microsoft|Windows).UI.Xaml.*`
