### ISSUE TITLE
`XamlReader` can't load `Geometry`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10577]
### Current behavior

Snippet below fails with exception (`MissingMethodException` trying to find constructor of `Geometry`). Same problem most likely applies to other types - see below

### Expected behavior

Snippet below should produce an instance of `PathGeometry`.

### How to reproduce it (as minimally and precisely as possible)

```csharp
var height = 0.0f;
var leftCorner = 0.0f;
var rightCorner = 0.0f;
var scaleFactor = 1.0f;
var data = "<Geometry xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation'>F1 M0,{0}  a 4,4 0 0 0 4,-4  L 4,{1}  a {2},{3} 0 0 1 {4},-{5}  l {6},0  a {7},{8} 0 0 1 {9},{10}  l 0,{11}  a 4,4 0 0 0 4,4 Z</Geometry>";

var strOut = string.Format(
    CultureInfo.InvariantCulture,
    data,
    height - 1.0f,
    leftCorner,
    leftCorner,
    leftCorner,
    leftCorner,
    leftCorner,
    ActualWidth - (leftCorner + rightCorner + 1.0f / scaleFactor),
    rightCorner,
    rightCorner,
    rightCorner,
    rightCorner,
    height - (5 + rightCorner));

var geometry = XamlReader.Load(strOut) as Geometry;
```

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

**Comment by Youssef1313** [comment]
Same might apply for `Brush` vs `SolidColorBrush`. It looks like we need to somehow have a mapping from base types that can't be constructed to default concrete types to use.

**Comment by MartinZikmund** [comment]
@Youssef1313 agreed, most likely the problem is the same for these as well
