### ISSUE TITLE
Perf: Avoid too large structs in `DependencyPropertyGenerator`

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#10582]
The model has large structs, this is a bad practice that can hurt performance.
It's a better idea to convert these to be records.

**Comment by jeromelaban** [comment]
Interesting. Record structs will still have the same amount of data, is it the Equals/hashcode part that would make it more efficient?

**Comment by Youssef1313** [comment]
They are already record structs, the suggestion is to make them record classes
