### ISSUE TITLE
[Gallery][Skia.GTK]Checkbox(Fluent) - App gets freeze when clicking 'Indeterminate' checkbox option.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#10612]
### Current behavior

https://user-images.githubusercontent.com/74563602/204644265-05e53ab6-be2a-4347-a458-b704a4240883.mp4

![checkbox issue ‎skia](https://user-images.githubusercontent.com/74563602/204645610-8ee5decc-824b-4584-9876-3ee574d66191.png)

### Expected behavior

Gallery app should not get freeze and the indeterminate checkbox should display properly.
![checkbox correct ‎skia](https://user-images.githubusercontent.com/74563602/204646735-77948cce-2462-439a-bf04-ad20898dc10d.png)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app on Skia.GTK.
2. Click on “Checkbox” from the "UI Components" list.
3. Go to the 'Fluent' section.
4. Click on the 'Indeteminate' option multiple time
5. Notice that for the unchecked condition the indeterminate option is not correct  and app gets freeze as well.

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by jeromelaban** [comment]
Thanks! Can you check if you see something specific in the console?

**Comment by sakshi173** [comment]
@Youssef1313, could you please look into this issue as well, I tried to see the console but not able to see any message.. but this bug is still present.

**Comment by Youssef1313** [comment]
I'm not able to reproduce. @sakshi173 Anything I'm missing to reproduce?

https://user-images.githubusercontent.com/31348972/218567125-3cba7b6c-54a1-4fe0-a61d-9dfbfe9ba1df.mp4

**Comment by sakshi173** [comment]
@Youssef1313, I verified now I am also not able to reproduce it due to that closing this bug.
