### ISSUE TITLE
Add support for SettingsFlyout

### ISSUE THREAD

**Issue by avikeid2007** [unoplatform/uno#10613]

**Comment by MartinZikmund** [comment]
Hi, @avikeid2007, unfortunately `SettingsFlyout` is not supported in Windows 10 and newer, so it will not be possible to add support for it in Uno Platform - https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.settingsflyout. Most likely it should be possible to replace it with a `Flyout` and maybe use the settings  card controls from Community Labs - https://github.com/CommunityToolkit/Labs-Windows/issues/216

**Comment by avikeid2007** [comment]
> use the setting

@MartinZikmund  Thanks for your reply. I have to change my control accordingly.
