### ISSUE TITLE
[iOS] Storyboard with RepeatBehavior="Forever" stops working after coming back from background

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#10627]
### Current behavior

![ezgif com-gif-maker](https://user-images.githubusercontent.com/17461593/205323364-81e7ae1c-eb3e-4725-8040-6041f50538eb.gif)

The storyboard stops working when coming back from background

### Expected behavior

![ezgif com-gif-maker](https://user-images.githubusercontent.com/17461593/205323591-27623f40-e3f1-445d-b1ab-489d117caa50.gif)

Storyboards with `RepeatBehavior="Forever"` should continue until we stopped it.

### How to reproduce it (as minimally and precisely as possible)

- Download this sample [StoryboardForever.zip](https://github.com/unoplatform/uno/files/10142140/StoryboardForever.zip)
- Deploy on iOS
- Put the app on background
- Go back to the app.

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.7.0-dev.503

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.3.5

**Comment by MatFillion** [comment]
related: 
https://github.com/unoplatform/uno/issues/6028
https://github.com/unoplatform/uno/issues/2498
https://github.com/unoplatform/uno/issues/182

**Comment by colevass** [comment]
@jeromelaban We also got this issue on 3.11.16 for myVCA, should we create a new issue or just update this one? Also is there an eta for a fix?
