### ISSUE TITLE
AutoSuggestBox: Unable to pick suggestion with a mouse

### ISSUE THREAD

**Issue by gitstaska** [unoplatform/uno#10646]
### Current behavior

When using Skia.GTK, after clicking on suggestion with a mouse, suggestion box is dismissed but text does not change.

### Expected behavior

As in WinUI.

### How to reproduce it (as minimally and precisely as possible)

[App5.zip](https://github.com/unoplatform/uno/files/10154814/App5.zip)

### Works on UWP/WinUI

Yes

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by MartinZikmund** [comment]
@gitstaska This is now fixed in the latest bits, try updating to latest prerelease packages (e.g. 4.7.0-dev.529)
