### ISSUE TITLE
[WASM] Issues with `WebAuthenticationBroker`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10655]
### Current behavior

Trying to authenticate using `WebAuthenticationBroker` is not reliable. The `await` causes one of the following situations:

a) await completes before the authentication window closes
b) await never completes

### How to reproduce it (as minimally and precisely as possible)

[WebAuthSample.zip](https://github.com/unoplatform/uno/files/10157108/WebAuthSample.zip)

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
@carldebilly looks familiar?

**Comment by carldebilly** [comment]
Must follow the rules as specified in the doc: https://platform.uno/docs/articles/features/web-authentication-broker.html?q=webauth#usage-on-webassembly

The return url must be on the same origin for the authentication process to complete on Wasm.
