### ISSUE TITLE
Long path issues building .NET 7 Android

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10659]
### Current behavior

When building Uno.UI under .NET 7 Android, long path issues cause runtime tests build to fail, for example:

`Generation failed: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Dev\uno2\src\Uno.UI.RuntimeTests\obj\Uno.UI.RuntimeTests.netcoremobile\Debug\net7.0-android\g\ImplementedRoutedEventsGenerator\Uno_UI_RuntimeTests_Tests_Windows_UI_Xaml_Controls_ListViewPages_ListViewCollectionViewSourcePage_ImplementedRoutedEvents_g_cs.g.cs'.`

This could potentially be a problem even outside of Uno sln.

### Expected behavior

Should not fail. Maybe the generated filename for generators could be shortened?

### Works on UWP/WinUI

None

**Comment by MartinZikmund** [comment]
CC @jeromelaban @Youssef1313

**Comment by MartinZikmund** [comment]
Note long paths are enabled on my system as per uno-check

**Comment by jeromelaban** [comment]
There is not supposed to be a local file system reference to that file. Did you disable roslyn generators ?

**Comment by MartinZikmund** [comment]
Yes, indeed, had them disabled 😅 . I will probably still make a PR to shorten the namespaces for the offending classes so that it can be compiled with roslyn disabled, as that is often useful.

**Comment by jeromelaban** [comment]
I don't think you'll be able to shorten much of it though... it's probably best to put the generated files in another folder that is not getting to that length restriction.

**Comment by Youssef1313** [comment]
@MartinZikmund Why do you think it's a long path related issue? I expect `PathTooLongException` if it is. Anything I'm missing?

Also do you have a stack trace?

**Comment by MartinZikmund** [comment]
@Youssef1313 Maybe it wasn't long path, but rather too long file name? See #10667 - these changes are enough for the build to pass on my side.
@jeromelaban I have just moved some of the classes with long names directly in `Uno.UI.RuntimeTests` namespace and that was enough to avoid the problems for now.
