### ISSUE TITLE
Decrease number of startup errors

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10652]
## What would you like to be added:

Currently when Uno app is started up, several errors show up:

- `Transition` and dependency property-related
- Hotreload client-related

## Why is this needed:

This should be decreased to make for example the WASM developer tools console cleaner

## For which Platform:

All

**Comment by jeromelaban** [comment]
**Update on Hot reload**
Client error messages are generated by the browser:
```
WebSocket connection to 'wss://localhost:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```
To get rid of those messages, we'll need to determine reliably which address to connect to, without trying to connect to all the machine's available interfaces.
