### ISSUE TITLE
Provide WinUI revert tool as self-contained tool

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10654]
## What would you like to be added:

The WinUI revert tool could be useful for non-Uno projects which want to support both WinUI and UWP as part of CI - e.g. Monaco editor

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
I don't think it's good way to work with it. Using actual cross-targeting with `#if HAS_UNO_WINUI` is better suited to support both at the same time, pretty much similar to extensions or uno toolkit.
