### ISSUE TITLE
Controls are not displayed correctly

### ISSUE THREAD

**Issue by gitstaska** [unoplatform/uno#10650]
### Current behavior

On Raspberry PI 4, when using OpenGL, controls are not displayed correctly. This is what I see:

![uno 4 6](https://user-images.githubusercontent.com/1270862/205668586-26f7e9d2-a7ae-408d-bd0f-0f199d2f7e5f.png)

However, when i downgraded to UNO 4.5 (keeping SkiaSharp 2.88.3), everything works as expected.

![uno 4 5](https://user-images.githubusercontent.com/1270862/205669400-d1f60030-3147-4d99-89f2-1ddd9e552998.png)

### Expected behavior

As UNO 4.5

### How to reproduce it (as minimally and precisely as possible)

[GlTextBox.zip](https://github.com/unoplatform/uno/files/10155245/GlTextBox.zip)

### Workaround

Downgrading to 4.5 or selecting software renderer.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report! This is a very curious issue. Are you connected to a 4K screen by any chance? Does it also happen when [using software rendering](https://platform.uno/docs/articles/features/using-skia-gtk.html?q=skia#changing-the-rendering-target)?

**Comment by gitstaska** [comment]
It seems to be fixed starting of 4.8.0-dev.585

**Comment by jeromelaban** [comment]
Thanks for the update!
