### ISSUE TITLE
[WASM][Threading] DispatcherQueue.HasThreadAccess returns the wrong value

### ISSUE THREAD

**Issue by EvarDion** [unoplatform/uno#10677]
## Describe the bug
In **WASM** the extension function **DispatcherQueue.EnqueueAsync()** does not execute the supplied Task on the Main/UI thread instead it executes it on the current thread.

I think the extension function **EnqueueAsync()** is located in the package **Uno.CommunityToolkit.WinUI**

[EnqueueAsyncTest.zip](https://github.com/unoplatform/Uno.WindowsCommunityToolkit/files/10173362/EnqueueAsyncTest.zip)

- [] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work: Unknown, this is the first time I have tried using that extension function. 

## Steps to Reproduce

- I have attached a sample solution demonstrating the issue. 

-Create a new solution using the UNO application template (WINUI3)
-Enable multithreading for WASM
-On the main page, create a Task and then use Task.Run() to execute it in background.
-Use the following code to switch back to the Main thread.

 return await DispatcherQueue.EnqueueAsync(async () => await ShowDialog());

## Expected behavior
In Windows the above code executes ShowDialog() on the Main/UI thread and then returns the result back to the calling thread.

## Screenshots

**Expected**
![image](https://user-images.githubusercontent.com/18524364/206107542-1d5fb5e7-7d5d-4cbe-9692-d3f25d334afb.png)

**Problem**
![image](https://user-images.githubusercontent.com/18524364/206107235-44333a5e-cdef-4b06-a6ba-4d054766b23d.png)

## Work Around
To get around the problem in WASM (and possibly other UNO platforms) and return the result back to the calling thread, you can use **DispatcherTaskExtensions.RunTaskAsync()** as detailed here:
https://github.com/Microsoft/Windows-task-snippets/blob/master/tasks/UI-thread-task-await-from-background-thread.md

If you choose to wrap it up in your own UIThread helper class you could end up with something like this:

 ```cs
 
        /// <summary>
        /// Runs the given Task on the Main/UI thread and then returns the result to the calling thread.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="func"></param>
        /// <param name="priority"></param>
        /// <returns></returns>
        public static async Task<T> RunTaskAsync<T>(Func<Task<T>> func, DispatcherQueuePriority priority = DispatcherQueuePriority.Normal)
        {
            //if we are already on the UI Thread then just run the Task and return the result.
            if (UIThread.CurrentThreadIsUIThread())
                return await func();

            //if we are not on the UI thread then we need to run the Task via one of the dispatchers.

#if NET7_0_WINDOWS10_0_18362

            //for Windows+WinUI3 run the Task on the Dispatcher Queue.
            if (DispatcherQueue != null)
            {
                return await DispatcherQueue.EnqueueAsync(func, priority);
            }

#endif
            //For non Windows+WinUI3 Uno platforms there is a bug in the DispatcherQueue.EnqueueAsync() which runs the Task on the calling thread
            // so we need to use the Core Dispatcher instead of the Dispatcher Queue to guarantee that the Task run on the Main/UI Thread.
            if (Dispatcher != null)
            {
                return await Dispatcher.RunTaskAsync(func, ToCoreDispatcherPriority(priority));
            }

            return default(T);            
        }

        /// <summary>
        /// Convert DispatcherQueuePriority to CoreDispatcherPriority
        /// </summary>
        /// <param name="queuePriority"></param>
        /// <returns></returns>
        private static CoreDispatcherPriority ToCoreDispatcherPriority(DispatcherQueuePriority queuePriority)
        {
            switch (queuePriority)      
            {
                case DispatcherQueuePriority.Normal: return CoreDispatcherPriority.Normal;
                case DispatcherQueuePriority.Low: return CoreDispatcherPriority.Low;
                case DispatcherQueuePriority.High: return CoreDispatcherPriority.High; 
                default: return CoreDispatcherPriority.Normal;
            }            
        }
 ```

## Usage
```cs
DialogButton result = await UIThread.RunTaskAsync(async () => await ShowDialog(title, message, buttons));
```
Now running any Task on the UI thread from any other thread becomes as simple as above.

## Environment

NuGet Package(s): 
"Uno.CommunityToolkit.WinUI" Version="7.1.100" 
"Uno.CommunityToolkit.WinUI.UI" Version="7.1.100" 
"Uno.Extensions.Logging.WebAssembly.Console" Version="1.4.0" 
"Uno.WinUI.WebAssembly" Version="4.6.19"
"Uno.WinUI.RemoteControl" Version="4.6.19" 
"Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.6.19" 
"Uno.Wasm.Bootstrap" Version="7.0.3" 
"Uno.Wasm.Bootstrap.DevServer" Version="7.0.3" 
"Uno.WinUI.Lottie" Version="4.6.19" 

Package Version(s):

Windows 10 Build Number:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [X ] May 2020 Update (19041)
- [ ] Insider Build ({build_number})

App min and target version:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Insider Build ({build_number})

Device form factor:
- [ ] Windows
- [ ] macOS
- [ ] iOS
- [ ] Android
- [X ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms

Visual Studio version:

- [ ] 2017 (15.{minor_version})
- [ ] 2019 (16.{minor_version})
- [ X] 2022 (17.{minor_version})

**Comment by jeromelaban** [comment]
Thanks for the report. It looks like `DispatcherQueue.HasThreadAccess` returns an incorrect value, causing the queued task to be executed in the caller's context.

As a workaround, you can use:

```csharp
await Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, async () => await EnqueueAsyncTest());
```
