### ISSUE TITLE
Wasm xaml editor show many warn info

### ISSUE THREAD

**Issue by wuyang26** [unoplatform/uno#10675]
environment: Windows11/.Net7/Uno Platform App/Visual studio 2022 17.4.2
after create Uno.Wasm project,Open Xaml Editor,will show many warn Info,some autocomplete does not appear,but the compilation succeeded,and can run the project.
   
![DataTemplate](https://user-images.githubusercontent.com/30990704/206104373-9ea34d78-37ac-4414-a9ae-f5b87639296c.png)
![ItemsPanelTemplate](https://user-images.githubusercontent.com/30990704/206104387-a12d07f3-b6d9-4692-b34b-268a00316b90.png)
![DataGrid](https://user-images.githubusercontent.com/30990704/206104394-c3038fe4-2e5f-443d-9aff-2e746e52096c.png)
when add Page.xaml，the xaml.cs file an the xaml file can not cascade.
![view](https://user-images.githubusercontent.com/30990704/206105058-f6bb940f-9b34-4f35-bb07-1bcfa6624b49.png)

**Comment by FrozDark** [comment]
Cascade is something related VS because it happens even on pure WinUI
As for the warn wasm issue is also related to VS not supporting that, choose Windows head in the upper left of the editor

**Comment by wuyang26** [comment]
Is the warn wasm issue  related to the Multi-platform App? because create the pure desktop Winui3 project using the microsoft template,There are no warnings,the automatic hint of the code is very good.

**Comment by wuyang26** [comment]
In particular, 3rd-party controls,For example:DataGrid, when entering code, are not recognized, and the control properties can only be entered manually, not automatically,it's easy to make mistakes and very troublesome

**Comment by jeromelaban** [comment]
@wuyang26 it only happens if the upper left project selector is not on the Windows project.
