### ISSUE TITLE
Android build often fails on APT-related issues

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10686]
### Current behavior

When building `net7.0-android`, APT often fails:
```
12>Building target framework: net7.0-android
12>Resources\values\resources_resw-strings.xml : error APT2126: file not found.
12>Done building project "Uno.UI.RuntimeTests.netcoremobile.csproj" -- FAILED.
```

So far I see this most commonly with `Resources.resw` and `Transitive-ingredient01.png` in the `Uno.UI.RuntimeTests` project.

### Expected behavior

Should not fail build.

### Workaround

Clean and rebuild the project.

### Works on UWP/WinUI

None

### Affected platforms

Android

**Comment by Youssef1313** [comment]
I got a failing build today. Capturing a binlog, I see

![image](https://user-images.githubusercontent.com/31348972/225246362-8f04a6a3-ec9f-425b-8a0f-50fe3686f19f.png)

Is it incorrectly skipped somehow? @jeromelaban

**Comment by jeromelaban** [comment]
It is likely an issue coming from .NET, but caused by an interaction from our end. It could be that we're not reexecuting our targets under certain conditions, which causes this target to not re-execute properly.

**Comment by dellis1972** [comment]
I think part of the problem is that this target https://github.com/unoplatform/uno/blob/b37c50349f60299050023d614b5f82dd7daecbde/src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets#L101C91-L101C105

Does not add the `@(GeneratedFiles)` Items to the `FileWrites` ItemGroup. 
This means that if an IncrementalClean is run, the files will get deleted. 

You might need something like

```
<ItemGroup>
   <FileWrites Include="@(GeneratedFiles)" />
</ItemGroup>
```

In that target.

**Comment by dellis1972** [comment]
Some helpful info see https://learn.microsoft.com/en-us/archive/msdn-magazine/2009/february/msbuild-best-practices-for-creating-reliable-builds-part-1. Search for `FileWrites` in the document it will give an explanation of why its needed.

**Comment by jeromelaban** [comment]
@dellis1972 thanks a lot for the analysis! We'll make the changes.

**Comment by Youssef1313** [comment]
Re-opening. This reproduced for @ramezgerges on latest master with the fix from #13606

**Comment by dellis1972** [comment]
@Youssef1313 

are you able to get some binlog files for the following.

1. A log containing the error.
2. A log from the previous build.

? I'd like to take a look and see why the resw files are getting deleted. The only way to know is to have the logs from the previous build as well.

**Comment by MartinZikmund** [comment]
Reproducing to for me quite frequently 
[Fail.zip](https://github.com/unoplatform/uno/files/13259984/Fail.zip)

**Comment by Youssef1313** [comment]
> ? I'd like to take a look and see why the resw files are getting deleted. The only way to know is to have the logs from the previous build as well.

Note that we switch TFMs depending on whaf the developer is working with currently. So I would expect that a build for Skia/Wasm/iOS could be deleting these files. Then an Android build starta to fail.

**Comment by MartinZikmund** [comment]
Yes I am not switching TFMs in this app, and yet it still happens

**Comment by dellis1972** [comment]
@jeromelaban I think I might have found another issue. 

Looking at the build output provided by @MartinZikmund I see this.

```
D:\Personal\Alchemy\src\Alchemy\obj\Debug\net7.0-android\g\ResourcesGenerator\values-ar\resources_resw-strings.xml
                                   LogicalName=values-ar\resources_resw-strings.xml
                                   UnoResourceTarget=Android
```

Now if we look at the output of the `AndroidComputeResPaths` from the Android SDK WE see this

```
 D:\Personal\Alchemy\src\Alchemy\obj\Debug\net7.0-android\res\values-ar\resources_resw-strings.xml
                                     Generator=MSBuild:UpdateGeneratedFiles
                                     LogicalName=values-ar\resources_resw-strings.xml
                                     OriginalItemSpec=D:\Personal\Alchemy\src\Alchemy\obj\Debug\net7.0-android\g\ResourcesGenerator\values-ar\resources_resw-strings.xml
                                     SubType=Designer
                                     UnoResourceTarget=Android
                                     _ArchiveDirectory=obj\Debug\net7.0-android\flat\
                                     _FlatFile=values-ar_resources_resw-strings.arsc.flat
```

Note the `%(Identity)` value has changed to the `res` folder. This is not the location of the generated file. So the `aapt2 compile` call is looking at the wrong location. 
I'll look at reworking the targets to make use of the `LibraryResourceDirectories` ItemGroup, it might be a better fit for what you are trying to achieve.

**Comment by Youssef1313** [comment]
@dellis1972 Thanks so much for the investigation! ❤️
