### ISSUE TITLE
Finish SkiaSharp implementation for WASM

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#1070]
## What would you like to be added:

Finish the CanvasKit/SkiaSharp implementation started in https://github.com/nventive/skia

Specific features would be further Draw methods (like DrawArc), CanvasSize support, Tapped/PointerPressed event handling, and functional SkPicture support so we could use SkiaSharp.Extended.Svg

## Why is this needed:

This would allow unified canvas support across all Uno-supported platforms

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows

## Anything else we need to know?

With the current implementation I have also noticed some variations in scale of drawn objects between UWP and WASM

**Comment by jeromelaban** [comment]
Support for these methods has been added in recent builds of SkiaSharp.
