### ISSUE TITLE
WebView2 support for UWP apps(WinUI 2.8)

### ISSUE THREAD

**Issue by DmitryBorodiy** [unoplatform/uno#10712]
WebView2 is already available for UWP, when will it be available in UnoPlatform?

- [ - ] WebAssembly
- [ * ] Android
- [ * ] iOS
- [ * ] macOS (AppKit)
- [ * ] Mac Catalyst
- [ + ] WPF
- [ + ] Windows Universal Apps
- [ * ] Build tasks
- [ + ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report! We're already tracking the work in #4758.
