### ISSUE TITLE
[net7.0-ios] crash with SamplesApp

### ISSUE THREAD

**Issue by spouliot** [unoplatform/uno#10724]
### Current behavior

Building and running SamplesApp with `net7.0-ios` often crash at startup. This happens on both simulators and devices.

In case where it does not crash the screen remains black.

This works when using `net6.0-ios`.

### Expected behavior

No crash

### How to reproduce it (as minimally and precisely as possible)

* Clone [uno](https://github.com/unoplatform/uno)
* Inside `src/crosstargeting_override.props` set `<UnoTargetFrameworkOverride>net7.0-ios</UnoTargetFrameworkOverride>`
* On a Mac open `src/Uno.UI-netcoremobile-only.slnf` with VSfM
* Build for iOS (simulator or device)
* Run the application

### Works on UWP/WinUI

None

### NuGet package version(s)

`main` / 4.7.0-dev

### Affected platforms

iOS

### IDE

Visual Studio for Mac

### IDE version

Version 17.4.1 (build 28)

### Relevant plugins

none

### Anything else we need to know?

Running on device gave an additional hint with the log

> 2022-12-09 19:45:29.980 SamplesApp[4235:553886] error: no object of size 103788564432404912d

This would be quite a large object and it's likely an invalid/corrupted value.

[Crash report (device)](https://gist.github.com/spouliot/0f9875c5560154e29e6f73f2becdfae3)

```
34  SamplesApp                    	       0x1047a8b7c SamplesApp_netcoremobile_BindableMetadataProvider_GetBindableTypeByType_System_Type + 28953468 (BindableMetadata.g.cs:85519)
```

This is also the location where the app can _freeze_ (black screen) when a crash does not occur.

**Comment by spouliot** [comment]
The line 

```
34  SamplesApp                    	       0x1047a8b7c SamplesApp_netcoremobile_BindableMetadataProvider_GetBindableTypeByType_System_Type + 28953468 (BindableMetadata.g.cs:85519)
```

maps to this (generated) code

```sharp
var bindableType = GetBindableTypeByFullName(type.FullName);
```

so the crash likely came trying to get `FullName` on a type.

The calling frames were modified recently by https://github.com/unoplatform/uno/pull/10087
but that's over 2 months ago (so 4.6 was released) and it works on net6

Callers from `App.xaml.cs` points to `MainPage` being the type that caused the crash. Still that does not happen on smaller apps, where the same code is called.

**Comment by spouliot** [comment]
The app starts normally when `net7.0-maccatalyst` with either `maccatalyst-x64` and `maccatalyst-arm64`, which should be very similar (e.g. mono runtime and AOT) to the code executed for iOS on devices.

**Comment by spouliot** [comment]
Going back to da01d6cab79c21f5403a22636453e4a41e7d7cd4 works fine.
Time for a binary search...

**Comment by spouliot** [comment]
e31a9209b56d5c70f4ce8fe7b122e51bd9640424 works fine
31a22a04ef1991f037c51587bda9b6e58d5934ea works fine

29d0e1b3170e8889eece9df9bb9a70d6d46af14f crash [different](https://gist.github.com/spouliot/0085546ea173fcd208350224e389a085)

d29a4b45d4bf6cdcbb364fa2d270bfdd8fc2d4db crash (same)
aba453015cbe3a48b5a8fe86d9ce0093fbd5ce25 crash (same)

will resume tomorrow...

**Comment by rolfbjarne** [comment]
> [29d0e1b](https://github.com/unoplatform/uno/commit/29d0e1b3170e8889eece9df9bb9a70d6d46af14f) crash [different](https://gist.github.com/spouliot/0085546ea173fcd208350224e389a085)

> error: Failed to load AOT module 'SkiaSharp.Views.UWP' while running in aot-only mode because a dependency cannot be found or it is out of date.

that might have been a stale build.

**Comment by spouliot** [comment]
> that might have been a stale build.

quite possible, it takes a few magic incantations for VSfM to build the project. It likes to fail with builds without showing any errors.

Now 111764e28485f61130d31e35e1cc3454fe3cb8b3 crash (did not symbolicate but it match the original) and the previous commit was working last night.

That one is interesting and somehow related to the crashes. It's possible we're using a over released CGColor that would explain the corrupted values causing the crash later.

**Comment by spouliot** [comment]
Disregard the above binary search. I get different results when I tried them again. Either the problem is random or the clean builds (from VSfM) are not correct (and maybe both).

**Comment by spouliot** [comment]
Again, doing a `git clean -xfd`, avoiding VSfM and deleting the app from the phone each time

3c308bb18e18cc5a1155104f1518f213d266a840 works (that's current 4.6.19 stable release)
2d870f78f45ce0eb9b7aacac5d8d772f1db95b0b works
dd9296501cef4821ad5218b8610c3872fe02b16f works
e127d30a26e65ee91d06c424042a66ab778dd9c7 works
eabf4ade7f691369099526060e31313dd5a6a84d works
d923d64ce158777a351528e6c81ed4e07546c271 works 
6aaba0e16c34fe5aa8b0aacf4e04ac6b8d2bdab1 works 
81dc019d647bd12aab6de11a8e5297b0017e1a40 works 
2427d280d01d85910f7b546dfd84bffacd44f5d8 works
a9d1394aaf3b51336ff26bce6e7f760622597130 crash (next revision, re-confirmed twice)
f06c5fe51fc36b7fb0eafddb79e4cb2e3f2f5162 crash 
25217eae2789d468b57f61561e387558bf10c6db crash 


If I checkout HEAD and revert a9d1394aaf3b51336ff26bce6e7f760622597130 then the app works again, c.c. @jeromelaban 


### Note

Since I do everything manually I noticed several failures while trying to install the `.app`, trying again (without rebuilding) eventually installed the app properly. c.c. @rolfbjarne 

```
$ /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch --installdev ./bin/Debug/net7.0-ios/ios-arm64/SamplesApp.app

...

Installing application bundle 'com.companyname.SamplesApp' on 'Mercure (2)'
error MT1006: Could not install the application './bin/Debug/net7.0-ios/ios-arm64/SamplesApp.app' on the device: EOF Error (error: 0xe800000e).
```

It might be something with my phone, which is randomly saving the crash reports. I guess I should reboot it :)

**Comment by rolfbjarne** [comment]
> Since I do everything manually I noticed several failures while trying to install the `.app`, trying again (without rebuilding) eventually installed the app properly.

This is new... I've never seen deployment issues fixed by just trying again. My guess is that it's a problem with this device (or maybe cable?) in particular.

**Comment by spouliot** [comment]
Removing the new file `src/Uno.UI/UI/Xaml/Controls/RichEditBox/RichEditBox.cs` from https://github.com/unoplatform/uno/commit/a9d1394aaf3b51336ff26bce6e7f760622597130 make it work (at that commit).

It also works if I just remove `: Control` inside the file.

**Comment by jeromelaban** [comment]
Very interesting. So doing this does increase the use of related XAML templates, but also includes it in the BindableMetadataGenerator. Are we reaching a threshold of some code size block?

**Comment by spouliot** [comment]
> Are we reaching a threshold of some code block / method size?

Maybe? There are more than 2000 local variables (mostly booleans) in the generated "switch" method.

**Comment by spouliot** [comment]
a860abff881e4a88888eb1bee1be5d03ca59e9b7 crash
a860abff881e4a88888eb1bee1be5d03ca59e9b7 works (with `:Control` removal)

b9c5fc266fb50832a14f4e9738a61b889dcea741 works (with `:Control` removal)
b0ba0a83e212bdff74e255ad4f11d445f6524aae works (with `:Control` removal)
aba453015cbe3a48b5a8fe86d9ce0093fbd5ce25 works (with `:Control` removal)
f42b59cf2e367a07ad5e3640670bae1875f6b5ff works (with `:Control` removal)
4934a0c52adac36184837a389b74aa85261d0367 build failure (with `:Control` removal) <<<
6d26427b3dd071e20d487ee449141f24c326b350 crash (with `:Control` removal)

44b839733820e0fdf3c05d4383d428cf3685f64e crash (with `:Control` removal)
afc81e08a7cc1b6f887f000e367f8603454c4076 crash (with `:Control` removal)


So `4934a0c52adac36184837a389b74aa85261d0367` with the fix from the next commit is the next crasher. Again nothing obvious from the change itself :(

**Comment by spouliot** [comment]
f42b59cf2e367a07ad5e3640670bae1875f6b5ff works (re-confirmed above)

6d26427b3dd071e20d487ee449141f24c326b350 crash (re-confirmed above)

6d26427b3dd071e20d487ee449141f24c326b350 w/o UITests.Shared.projitems changes -> works
6d26427b3dd071e20d487ee449141f24c326b350 w/o TextBox.cs changes -> crash

so we can resume (for how long?) the binary search if we remove the changes to `UITests.Shared.projitems`

af120dee6d6f3c75668345b48854db1cacefa3e4 works
acd28c3ad679040b75efaf9bfcfbb65219db1f64 works
12e4c66ff5fb5f587fdd02f41ad52d7102f93e6d works
f395100f8b8b3cdbea1641ea22d2036e4f103f62 build errors

Local changes to get SamplesApp working. Now we need to figure out what those changes triggers...

```diff
diff --git a/src/SamplesApp/UITests.Shared/UITests.Shared.projitems b/src/SamplesApp/UITests.Shared/UITests.Shared.projitems
index 19db85277d..e553f750d3 100644
--- a/src/SamplesApp/UITests.Shared/UITests.Shared.projitems
+++ b/src/SamplesApp/UITests.Shared/UITests.Shared.projitems
@@ -2313,10 +2313,6 @@
       <SubType>Designer</SubType>
       <Generator>MSBuild:Compile</Generator>
     </Page>
-    <Page Include="$(MSBuildThisFileDirectory)Windows_UI_Xaml_Controls\TextBox\TextBox_ClipboardMethods.xaml">
-      <SubType>Designer</SubType>
-      <Generator>MSBuild:Compile</Generator>
-    </Page>
     <Page Include="$(MSBuildThisFileDirectory)Windows_UI_Xaml_Controls\TextBox\TextBox_CharacterCasing.xaml">
       <SubType>Designer</SubType>
       <Generator>MSBuild:Compile</Generator>
@@ -6545,9 +6541,6 @@
     <Compile Include="$(MSBuildThisFileDirectory)Windows_UI_Xaml_Controls\TextBox\TextBox_Binding_Null.xaml.cs">
       <DependentUpon>TextBox_Binding_Null.xaml</DependentUpon>
     </Compile>
-    <Compile Include="$(MSBuildThisFileDirectory)Windows_UI_Xaml_Controls\TextBox\TextBox_ClipboardMethods.xaml.cs">
-      <DependentUpon>TextBox_ClipboardMethods.xaml</DependentUpon>
-    </Compile>
     <Compile Include="$(MSBuildThisFileDirectory)Windows_UI_Xaml_Controls\TextBox\TextBox_CharacterCasing.xaml.cs">
       <DependentUpon>TextBox_CharacterCasing.xaml</DependentUpon>
     </Compile>
diff --git a/src/Uno.UI/UI/Xaml/Controls/RichEditBox/RichEditBox.cs b/src/Uno.UI/UI/Xaml/Controls/RichEditBox/RichEditBox.cs
index 38be9f4e55..5fca7e5384 100644
--- a/src/Uno.UI/UI/Xaml/Controls/RichEditBox/RichEditBox.cs
+++ b/src/Uno.UI/UI/Xaml/Controls/RichEditBox/RichEditBox.cs
@@ -6,7 +6,7 @@ using System.Threading.Tasks;
 
 namespace Windows.UI.Xaml.Controls
 {
-	public partial class RichEditBox : Control
+	public partial class RichEditBox
 	{
 	}
 }
```

**Comment by spouliot** [comment]
> error: Failed to load AOT module 'SkiaSharp.Views.UWP' while running in aot-only mode because a dependency cannot be found or it is out of date.

I got this message again... and the stack trace seems identical to the previous crash. Enabling more logging (`--setenv=MONO_LOG_MASK=aot --setenv=MONO_LOG_LEVEL=debug`) I got

```
default	20:04:57.163760-0500	SamplesApp	debug: AOT: FOUND method SamplesApp.netcoremobile.BindableMetadataProvider:GetBindableTypeByType (System.Type) [0x103df39c0 - 0x103df3e40 0x11c05fd3f]
default	20:04:57.167347-0500	SamplesApp	error: no object of size 195368365886982432d
```

which again points to `GetBindableTypeByType` except the abort message was the invalid size. It's possible both outputs come from the same cause (memory corruption?).

**Comment by jeromelaban** [comment]
This particular method `GetBindableTypeByType` is a huge switch case for strings, and in relatively recent compilers is what looks to be a very large constant hashtable, super fast with a zero initialization cost, but at the expense of a lot of code.

**Comment by spouliot** [comment]
It's the same method identified [earlier](https://github.com/unoplatform/uno/issues/10724#issuecomment-1349647931). 

However it's not the huge method. This one simply call the huge switch version with

```csharp
var bindableType = GetBindableTypeByFullName(type.FullName);
```

Now `GetBindableTypeByFullName` does have more than 2000 locals (mostly `bool`) but it did not seem to be reached (and I doubt it was inlined).

OTOH it would not be hard to replace the latter with a different implementation but it might just hide the real issue. The fact that MacCatalyst worked fine hints that small differences have impact.

**Comment by spouliot** [comment]
I tried to print the full name of the type. I get more methods loaded by AOT (as expected) but nothing gets printed. Which likely means

* there's no previous logs so it happens on the first type we call `GetBindableTypeByType` on
* getting `FullName` is crashing

```
default	11:12:35.171205-0500	SamplesApp	debug: AOT: FOUND method SamplesApp.netcoremobile.BindableMetadataProvider:GetBindableTypeByType (System.Type) [0x10247f9c0 - 0x10247fec0 0x11a6d3d3f]
default	11:12:35.171236-0500	SamplesApp	debug: AOT: FOUND method System.Diagnostics.Debug:WriteLine (string) [0x10f2c98e0 - 0x10f2c9940 0x114957415]
default	11:12:35.171266-0500	SamplesApp	debug: AOT: FOUND method System.Diagnostics.DebugProvider:.cctor () [0x10f2ca7b0 - 0x10f2ca850 0x1149574dd]
default	11:12:35.171295-0500	SamplesApp	debug: AOT: FOUND method System.Diagnostics.DebugProvider:WriteLine (string) [0x10f2ca1f0 - 0x10f2ca250 0x114957491]
default	11:12:35.171327-0500	SamplesApp	debug: AOT: FOUND method System.Diagnostics.DebugProvider:Write (string) [0x10f2ca080 - 0x10f2ca1f0 0x114957484]
default	11:12:35.171355-0500	SamplesApp	debug: AOT: FOUND method System.Diagnostics.DebugProvider:GetIndentString () [0x10f2ca250 - 0x10f2ca3b0 0x11495749b]
default	11:12:35.171384-0500	SamplesApp	debug: AOT: FOUND method System.Diagnostics.DebugProvider:WriteCore (string) [0x10f2ca4b0 - 0x10f2ca550 0x1149574b7]
default	11:12:35.171416-0500	SamplesApp	debug: AOT: FOUND method System.Diagnostics.DebugProvider:WriteToDebugger (string) [0x10f2ca550 - 0x10f2ca5c0 0x1149574c5]
default	11:12:35.171446-0500	SamplesApp	debug: AOT: FOUND method (wrapper managed-to-native) System.Diagnostics.Debugger:IsLogging () [0x10f2c6fe0 - 0x10f2c70c0 0x1149572d4]
default	11:12:35.171477-0500	SamplesApp	debug: AOT: FOUND method Interop/Sys:SysLog (Interop/Sys/SysLogPriority,string,string) [0x10ef8c920 - 0x10ef8cb90 0x11493d1cc]
default	11:12:35.171505-0500	SamplesApp	debug: AOT: FOUND method (wrapper managed-to-native) Interop/Sys:<SysLog>g____PInvoke|124_0 (Interop/Sys/SysLogPriority,byte*,byte*) [0x10f598ce0 - 0x10f598de0 0x114968da5]
```

if there were no crash then the following logs would look like

```
default	11:33:02.629332-0500	SamplesApp	debug: AOT: FOUND method System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1<T_CHAR>:Trim () [0x11118d000 - 0x11118d590 0x1165ec7e3]
default	11:33:02.631134-0500	SamplesApp	debug: AOT: FOUND method SamplesApp.netcoremobile.BindableMetadataProvider:GetBindableTypeByFullName (string) [0x1040acab0 - 0x10419b2d0 0x11c3e147d]
default	11:33:02.632391-0500	SamplesApp	debug: AOT: FOUND method <PrivateImplementationDetails>:ComputeStringHash (string) [0x1043c8910 - 0x1043c8a70 0x11c3ff504]
default	11:33:02.634087-0500	SamplesApp	debug: AOT: FOUND method SamplesApp.netcoremobile.MetadataBuilder_789:Build () [0x103f2c330 - 0x103f2c420 0x11c3cc00f]
default	11:33:02.634376-0500	SamplesApp	debug: AOT: FOUND method SamplesApp.netcoremobile.MetadataBuilder_789:Build (Uno.UI.DataBinding.BindableType) [0x103f2c420 - 0x103f2c710 0x11c3cc018]
default	11:33:02.634438-0500	SamplesApp	debug: AOT: FOUND method Uno.UI.DataBinding.BindableType:.ctor (int,System.Type) [0x10c3dc2b0 - 0x10c3dc460 0x1180b684d]
```

and `798` maps to `MainPage`

```csharp
// SamplesApp.netcoremobile.MetadataBuilder_789
private static object CreateInstance()
{
	return new MainPage();
}
```

**Comment by jeromelaban** [comment]
So I've poked at the bear a bit more, and it seems that just removing code from the app helps. I deleted a bunch of XAML page and the app started to work again. Could it be related to the number of types available in the overall loaded assemblies?

**Comment by spouliot** [comment]
> Could it be related to the number of types available in the overall loaded assemblies?

Possibly, but I have seen larger apps - at least in size, but it's hard to know which limit could be maxed out.

Or the difference in the app code just moved the issue elsewhere so it's not seen at startup...

The metadata definitions between the working and crashing app are not very large https://gist.github.com/spouliot/feaf959bb01306f5c6676b0cb7a736d9 but also not related to `MainPage` :|

**Comment by spouliot** [comment]
[Generating code](https://gist.github.com/spouliot/97eade5abee64dec9b781ca5bd5510ce) that produce less locals (using an array instead of 2000+ locals) workaround the crashes.

It's unclear if this (too many locals) is the root issue or if this just hides/moves the issue somewhere we are not executing at startup (e.g. in case of an unrelated memory corruption).

Since the changes are minor I think it's worth trying applying it and see if other crashes are found with more extensive testing.
