### ISSUE TITLE
ToolTip ContentControl does not show up in Skia.Gtk

### ISSUE THREAD

**Issue by thomas-visma** [unoplatform/uno#10723]
### Current behavior

The ToolTip ContentControl does not show up in the Gtk head. In other heads, for example WASM, the ToolTip does work.

### Expected behavior

As stated in [Uno Docs](https://platform.uno/docs/articles/implemented/windows-ui-xaml-controls-tooltip.html), ToolTip should be visible in Gtk.

### How to reproduce it (as minimally and precisely as possible)

1. Create minimum Uno app supporting WASM and Skia.Gtk
2. Set ToolTipService.ToolTip on the TextBlock or another control
3. Run the WASM head: ToolTip appears
4. Run the Gtk head: no ToolTip appears

Example:
`<Page
    x:Class="TooltipGtk.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TooltipGtk"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"    
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
      <TextBlock Text="Hello, world!" Margin="20" FontSize="30" ToolTipService.ToolTip="Simple ToolTip"/>
      <Button Content="I should have a tooltip" ToolTipService.ToolTip="Simple ToolTip"/>
    </Grid>
</Page>`

### Workaround

None

### Works on UWP/WinUI

Yes

### Environment

WinUI.Skia
Microsoft Windows 10 Pro
21H2 build 19044.2251

### NuGet package version(s)

```
Uno.UI.Adapter.Microsoft.Extensions.Logging {4.6.19} TooltipGtk.Wasm    
Microsoft.Windows.Compatibility             {6.0.0}  TooltipGtk.Wasm    
Uno.Extensions.Logging.WebAssembly.Console  {1.4.0}  TooltipGtk.Wasm    
Microsoft.Extensions.Logging                {6.0.0}  TooltipGtk.Wasm    
Uno.WinUI.WebAssembly                       {4.6.19} TooltipGtk.Wasm    
Uno.Wasm.Bootstrap                          {7.0.3}  TooltipGtk.Wasm    
Uno.Wasm.Bootstrap.DevServer                {7.0.3}  TooltipGtk.Wasm    
Uno.WinUI.Lottie                            {4.6.19} TooltipGtk.Wasm    
Uno.UI.Adapter.Microsoft.Extensions.Logging {4.6.19} TooltipGtk.Skia.Gtk
Uno.WinUI.Skia.Gtk                          {4.6.19} TooltipGtk.Skia.Gtk
SkiaSharp.Views.Uno.WinUI                   {2.88.3} TooltipGtk.Skia.Gtk
SkiaSharp.Skottie                           {2.88.3} TooltipGtk.Skia.Gtk
Microsoft.Extensions.Logging.Console        {5.0.0}  TooltipGtk.Skia.Gtk
Uno.WinUI.Lottie                            {4.6.19} TooltipGtk.Skia.Gtk
```

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

17.4.2

**Comment by MartinZikmund** [comment]
@thomas-visma Hi, I have checked and `ToolTips` are for now disabled by default on Skia targets (currently they are on by default only on WASM). They can be enabled by setting the `FeatureConfiguration` flag in `App` constructor in `App.xaml.cs` (for example after `InitializeComponent()`):

```csharp
#if __SKIA__
Uno.UI.FeatureConfiguration.ToolTIp.UseToolTips = true;`
#endif
```
