### ISSUE TITLE
FileOpenPicker does not work on Windows/UWP and WASM

### ISSUE THREAD

**Issue by rabejens** [unoplatform/uno#10737]
### Current behavior

When opening a `FileOpenPicker`, it crashes for WASM and Windows.

For Windows, it crashes with

```
Invalid window handle. (0x80070578)
Consider WindowNative, InitializeWithWindow
See https://aka.ms/cswinrt/interop#windows-sdk
```

WASM:

```
User did not make a selection or the file selected wasdeemed too sensitive or dangerous to be exposed to the website - TypeError: Failed to execute 'showOpenFilePicker' on 'Window': Failed to read the 'startIn' property from 'FilePickerOptions': The provided value '' is not a valid enum value of type WellKnownDirectory.
```

### Expected behavior

The file picker should show

### How to reproduce it (as minimally and precisely as possible)

1. Add a Button to a control
2. Add a `Click` event to the control
3. In Code Behind, in the `Click` method, add:
    ```csharp
    var fileOpenPicker = new FileOpenPicker();
    fileOpenPicker.SuggestedStartLocation = PickerLocationId.ComputerFolder;
    fileOpenPicker.FileTypeFilter.Add(".txt");
    fileOpenPicker.FileTypeFilter.Add(".csv");
    StorageFile pickedFile = await fileOpenPicker.PickSingleFileAsync();
    ```

### Workaround

For Windows:

1. In the Windows head's `csproy` define a new conditional compilation symbol `__WINUI__`
    ```xml
        <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
	  <DefineConstants>__WINUI__</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
	  <DefineConstants>__WINUI__</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
	  <DefineConstants>__WINUI__</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
	  <DefineConstants>__WINUI__</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|arm64'">
	  <DefineConstants>__WINUI__</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|arm64'">
	  <DefineConstants>__WINUI__</DefineConstants>
	</PropertyGroup>
    ```
2. After creating the picker, add this code (partly taken from [Microsoft](https://github.com/microsoft/CsWinRT/blob/master/docs/interop.md#windows-sdk))
    ```csharp
    #if __WINUI__
        var wh = System.Diagnostics.Process.GetCurrentProcess().MainWindowHandle;
        WinRT.Interop.InitializeWithWindow.Initialize(fileOpenPicker, wh);
    #endif
    ```

For WASM: No idea yet

### Works on UWP/WinUI

No

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly, Windows

### IDE

Visual Studio 2022

### IDE version

17.4.3

**Comment by jeromelaban** [comment]
Thanks for the report. The Windows behavior is expected, it is generally documented in WinAppSDK's repo.

For the WebAssembly behavior, [see this documentation](https://platform.uno/docs/articles/features/windows-storage-pickers.html?q=storage#security-considerations).

**Comment by rabejens** [comment]
I also found a solution for wasm: Using `PickerLocationId.DocumentsLibrary` instead of `ComputerFolder` works
