### ISSUE TITLE
The `ISelectionInfo.SelectRange` is invoked only on first item selected on skia (and most probably WASM)

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#10742]
### Current behavior

The `ISelectionInfo.SelectRange` is invoked only on first item selected on skia (and most probably WASM)

### Expected behavior

`ISelectionInfo.SelectRange` is invoked each time the selection change

### Works on UWP/WinUI

None

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

**Comment by dr1rrb** [comment]
@Xiaoy312

**Comment by Xiaoy312** [comment]
`ISelectionInfo::SelectRange(ItemIndexRange)` regardless the collection type, so long as it implements that interface.
In [the specific case of uno.extensions](https://github.com/unoplatform/uno.extensions/pull/998/files#diff-d2506e37efd9f20e2aeaa29db841840d8ca0da06812c92bd08a474832484330aR44), the ItemsSource that was received by the listview does not implemented `ISelectionInfo`, so it didnt work:
```
lv.ItemsSource.GetType().Name
"BindableListFeed`1"

lv.ItemsSource.GetType().GetInterfaces().Select(x => x.Name)
Count = 16
    [0]: "ICollectionView"
    [1]: "IEnumerable`1"
    [2]: "IEnumerable"
    [3]: "IObservableVector`1"
    [4]: "IList`1"
    [5]: "ICollection`1"
    [6]: "INotifyCollectionChanged"
    [7]: "ISignal`1"
    [8]: "IListState`1"
    [9]: "IListFeed`1"
    [10]: "ISignal`1"
    [11]: "IState"
    [12]: "IAsyncDisposable"
    [13]: "IInput`1"
    [14]: "IState`1"
    [15]: "IFeed`1"
```


Here is a working example with `ICollectionView`: [SelectionModel.zip](https://github.com/unoplatform/uno/files/10262543/SelectionModel.zip)
