### ISSUE TITLE
Add support for `ItemsControl` `Header` and `Footer`

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#10745]
_Originally posted by @michael-hawker in https://github.com/unoplatform/uno/issues/1979#issuecomment-1353769583_

We could do a bunch of extra work with a `StackPanel` and `ContentPresenter`s, but it's super simple to hook-in to the existing properties on the `ItemsPresenter` for this scenario:

```xml
     <ItemsPresenter win:Footer="{TemplateBinding ItemsFooter}"
                     win:Header="{TemplateBinding ItemsHeader}"
                     TabFocusNavigation="Local" />
```

**Comment by michael-hawker** [comment]
Thanks @jeromelaban! We stumbled upon this one by accident, we didn't even realize `ItemsPresenter` had `Header` and `Footer` properties to use. But it played really well into our new scenario for the `SettingsExpander` control and presenting an item at the end of the list. It was super simple to plug-in our new properties too, and worked like a charm in UWP and Windows App SDK:

![image](https://user-images.githubusercontent.com/24302614/207985222-f60740a5-c673-4559-a217-6a3aebb47ec8.png)

Appreciate you opening a new tracking issue for this.

**Comment by michael-hawker** [comment]
FYI, I was just looking at the Toolkit's `HeaderedItemsControl` and realized that it'll be simpler and better aligned to `ListView` if we use the `Header` property of the `ItemsPresenter` itself vs. our own `ContentPresenter`. Simplifies the visual tree for this light-weight control as well.
