### ISSUE TITLE
CornerRadius should clip its children

### ISSUE THREAD

**Issue by MatFillion** [unoplatform/uno#1074]
## Current behavior

When using something like this : 

```xml
<StackPanel CornerRadius="12"
      Background="Tomato"
      HorizontalAlignment="Center"
      VerticalAlignment="Center">
    <Rectangle Width="100"
         Height="100"
         Fill="Olive" />
 </StackPanel>
```

The Olive rectangle is clipped in Windows with Fall Creators Update and later. It was not the case in Creators Update.

## Expected behavior

Olive Rectangle should be clipped

## Environment

Nuget Package:
1.44.1

Package Version(s):

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly (not tested)
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?

Might be indirectly related to #652 (for android)

Possible work-around: Apply the same `CornerRadius` on all layers of Panels. 

But the only way to apply round corners to `<Image>` is to use it as a `ImageBrush` instead `Grid.Background`, but this adds limitiations for the stretching options. Having this bug fixed would let use use a real Image object and let the parent panel handle the round corners. 

Related work item : https://nventive.visualstudio.com/Umbrella/_workitems/edit/102336

**Comment by carldebilly** [comment]
Just checked on all platforms:

## UWP
![image](https://user-images.githubusercontent.com/4174207/85413760-38448780-b539-11ea-8505-fb79e41a8bf5.png)

## Android
![image](https://user-images.githubusercontent.com/4174207/85414251-dd5f6000-b539-11ea-82e7-c75a28934053.png)

## iOS
![image](https://user-images.githubusercontent.com/4174207/85414481-29120980-b53a-11ea-9773-202421e6388b.png)

## WASM
![image](https://user-images.githubusercontent.com/4174207/85414605-4e067c80-b53a-11ea-888c-5543567896fd.png)

So it's fixed!
