### ISSUE TITLE
messageDialog.ShowAsync() doesn't work in windows platform

### ISSUE THREAD

**Issue by garawaa** [unoplatform/uno#10757]
It works in android and web but doesn't work in windows. I also tried ContentDialog. But all popups don't work. What should I do?

**Comment by FrozDark** [comment]
Windows is handled by Microsoft itself. Ask questions about Windows (WinUI 3) there https://github.com/microsoft/microsoft-ui-xaml
btw dialogs should be XamlRoot set before show

**Comment by garawaa** [comment]
I tried some code for UWP or MAUI apps. And works. But same code does not work in uno. 
Even I can not add Uno extensions to my project.

**Comment by garawaa** [comment]
For example: 
```
            ContentDialog noWifiDialog = new ContentDialog
            {
                Title = "No wifi connection",
                Content = "Check your connection and try again.",
                CloseButtonText = "Ok"
            };

            ContentDialogResult result = await noWifiDialog.ShowAsync();
```
This simple code even does not work.

**Comment by jeromelaban** [comment]
Thanks for the report. This is a behavior specific to Windows that Uno does not have control over. You can find https://github.com/microsoft/microsoft-ui-xaml/issues/2504 that discuss this topic.
