### ISSUE TITLE
WebView Documentation

### ISSUE THREAD

**Issue by dgerding** [unoplatform/uno#1075]
## What would you like clarification on:
Is there any documentation yet for WebView?  If so, where?  Specifically, is there a mechanism for js invoking C# or vice versa via eval or some other technique?  What events, if any, are raised during DOM lifecycle and can these be interaction/injection points for JS/C# interop?

## Concern?

- [ ] Usage in industry
- [x] Clarification of capabilities
- [ ] Getting started with Uno
- [ ] Developing with Uno
- [ ] Contributing to the Uno project
- [ ] Publishing your application
- [ ] Support
- [ ] Other (please specify):

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] Windows

**Comment by davidjohnoliver** [comment]
You can refer here to see which methods & properties of WebView are implemented, as well as a link to the UWP documentation which should cover JS/C# interop: https://platform.uno/docs/articles/implemented/windows-ui-xaml-controls-webview.html

Note that the `WebView` control is not yet supported on WebAssembly or Linux.
