### ISSUE TITLE
Doc needed - Hosting Uno-Wasm applications on Amazon AWS

### ISSUE THREAD

**Issue by sasakrsmanovic** [unoplatform/uno#10768]
Hosting Uno Platform Wasm applications is possible on Amazon AWS, but documentation isn't provided. Can we please develop a document similar to those existing for Azure, Nginx and Apache to help community deploy to Azure AWS. 

Similar pages
[Hosting a WebAssembly App](https://platform.uno/docs/articles/how-to-host-a-webassembly-app.html)

**Comment by DierkDroth** [comment]
@sasakrsmanovic curious: what info for what AWS Setup would you need? 

FYI My stuff runs on AWS S3, not sure if that's what's in your focus?!?

**Comment by davidconoh** [comment]
An Amazon S3 bucket would be fine. I don't know if added functionality would demand added CodeBuild or Amplify integration :)

**Comment by MCAleckson** [comment]
I'm trying to host an Uno WASM app (.Net7) on Amplify and can't get it to build or run.  I had a .Net5 version running fine, but have long forgotten the magic words I used to make that work.  So my team could really use a document describing the setup for UNO WASM on Amplify.  Especially the build YML file contents.

**Comment by jeromelaban** [comment]
@MCAleckson if you have additional details on what happens when running on this type of hosting (error messages, browser debug logs or others) you can post some of it here, it will help to create the documentation. Thanks!

**Comment by davidconoh** [comment]
Hi @MCAleckson Here's a simple guide I followed to resolve Deploying Uno Platform WASM (.Net7) on Amazon Amplify: https://reads.davidconoh.me/hosting-uno-platform-wasm-on-aws-amplify/ 
Hope it helps :)

**Comment by davidconoh** [comment]
Thank you MCAleckson, please do mark as answer to help others with the same issue :)
