### ISSUE TITLE
SVG not rendering/crashing

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#10766]
### Current behavior

When following the instruction on this [page](https://platform.uno/docs/articles/features/svg.html), it doesnt work, and I cannot seem to figure out how to make svg images show up. On the only app where it worked (the images showed up on WinUI), the image still didnt show up on IOS and crashed the app on android.

https://github.com/unoplatform/uno/discussions/10750

### Expected behavior

The image should show up on all platform when you follow the documentation, and set the source of the image as an svg.

### How to reproduce it (as minimally and precisely as possible)

[SvgImg.zip](https://github.com/unoplatform/uno/files/10259714/SvgImg.zip)

### Workaround

None that I found

### Works on UWP/WinUI

No

### NuGet package version(s)

```
    <PackageReference Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.3" />
    <PackageReference Include="Uno.WinUI" Version="4.7.0-dev.666" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.7.0-dev.666" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.6.18" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Uno.WinUI.Lottie" Version="4.6.18" />
    <PackageReference Include="Uno.WinUI.Svg" Version="4.7.0-dev.666" />
```

### Affected platforms

Android, iOS, Windows

### IDE

Visual Studio 2022

### IDE version

17.4.1

**Comment by MartinZikmund** [comment]
@Marc-Antoine-Soucy I think one issue is that the `svg` file needs to be marked with the Build Action of `Content` in the shared project. I will investigate the errors further though.

**Comment by Marc-Antoine-Soucy** [comment]
Is it possible that it also doesnt work with uwp/xamarin?

**Comment by MartinZikmund** [comment]
Link to original discussion #10750
