### ISSUE TITLE
Crash on disabling Use Shared Runtime

### ISSUE THREAD

**Issue by NGame1** [unoplatform/uno#1076]
## Current behavior

By disabling the use shared runtime option in Android Options (Both in Debug and Release) app will crash at the startup. It means you can't get a release package for Android at all. I even tried it on a blank project too. 

## How to reproduce it (as minimally and precisely as possible)

Nuget Package:

Package Version(s):

Affected platform(s):
- [ ] iOS
- [x ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x ] 2019 (version: 16.1.3 )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Thanks for the report!

Specific things I'd like to learn about are what Android API level you are using and if you are testing in a simulator or on device. Could you please provide a test case that reproduces the issue?

**Comment by NGame1** [comment]
I'm using Android PIE (9.0) SDK and minimum supported version KitKat (4.4) and I tried on Android 4.4 emulator it has stopped working error. But On my Xiaomi Mi4 (Android 9.0 Unofficial Rom) it was OK both for install and running. But on an Xperia XA1 Ultra Android 8.0, I can't install the Release APK but I could deploy using VS2019! 
Seems there's something that fails on some devices and OK on some other ones. 
On the Android 4.4 emulator, I can't get any stack trace also to help you more about this case.

**Comment by jeromelaban** [comment]
@ngame1 Does the android logcat show anything useful ? Also, Android 4.4 is not supported at this time, there is a missing key feature that Uno uses for which we have yet to find a workaround. See https://github.com/nventive/Uno/issues/20

**Comment by NGame1** [comment]
em, That's maybe funny but I don't know how to use LogCat in VS!! I'm completely new to Android, I know UWP / WPF :D 
have to check and see if I can find anything useful. 
Also could you please let me know the minimum Android version supported by Uno? I tried on v4.4. of Android in DEBUG everything was ok

**Comment by jeromelaban** [comment]
@NGame1 no problem :) You can find the android logcat using VS: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows

**Comment by ghuntley** [comment]
@NGame1, see https://github.com/nventive/Uno/pull/1109/files

Android v4.4 (2013) has a lot of limitations that either impossible to workaround, or that make performance woeful. Android v5.x (2014) is the min supported version.
