### ISSUE TITLE
VB.NET Support?

### ISSUE THREAD

**Issue by alexthekid07** [unoplatform/uno#108]
Is there any plan to support VB.NET at all alongside C#? Or a workaround to use it?

**Comment by carldebilly** [comment]
Currently it's supporting only C# projects. If your application is using the MVVM pattern, where the logic is not in the view with only few _code behind_, migrating your view to a C# project would be easy while keeping your application code in VB.

We never tested referencing VB code, but it should work.

**Comment by francoistanguay** [comment]
At this point, there are no plans for VB.NET

**Comment by DualBrain** [comment]
> Currently it's supporting only C# projects. If your application is using the MVVM pattern, where the logic is not in the view with only few code behind, migrating your view to a C# project would be easy while keeping your application code in VB.

Is there an example somewhere demonstrating this?

Thanks.
