### ISSUE TITLE
Cannot render unicode characters in Skia WPF

### ISSUE THREAD

**Issue by adreeeyan** [unoplatform/uno#10801]
### Current behavior

Using the default template in Uno and running in Skia.WPF project.

```
<Grid>
    <TextBlock Text="你好" Margin="20" FontSize="30"/>
</Grid>
```

Produces:
![image](https://user-images.githubusercontent.com/18593260/209115535-cface479-5e94-48c2-839c-de9915dd1997.png)

### Expected behavior

Output in UWP project.
![image](https://user-images.githubusercontent.com/18593260/209115779-4afe00b9-b77a-4b29-9781-af12910a7127.png)

### How to reproduce it (as minimally and precisely as possible)

1. Create Uno Project (Uno Platform App)
2. Remove other project heads except Skia and UWP
3. In MainPage.xaml of Shared project, change Hello World with a Chinese character (e.g. 你好)
4. Run in Skia.WPF

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.UI 4.6.19

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2019

### IDE version

16.11.21

**Comment by jeromelaban** [comment]
Thanks for the report. This looks somehow related to https://github.com/unoplatform/uno/issues/6973 or https://github.com/mono/SkiaSharp/issues/401#issuecomment-347666225, but may be system dependent, or related to the default system font being used.

For Chinese characters, the font being used should contain the characters you are trying to use.

**Comment by Youssef1313** [comment]
> For Chinese characters, the font being used should contain the characters you are trying to use.

It works on Windows without this requirement, IIRC.

**Comment by adreeeyan** [comment]
@jeromelaban I can confirm that this issue is related to #6973.  
It worked when I set the FontFamily to "Microsoft YaHei UI". Thank you!

Though, same with the concerns of other people in the related issue, this should work without setting the FontFamily. It might be better for a fallback to happen if the character cannot be rendered.
- https://stackoverflow.com/a/57362436
- https://stackoverflow.com/a/48141139
