### ISSUE TITLE
Bring back support for `libvlcsharp`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10825]
## What would you like to be added:

`libvlcsharp` support for Uno Platform is not compatible with Uno Platform 4.x.

A PR was open to add support for Uno 3.x but was not finished - https://github.com/videolan/libvlcsharp/pull/167
There is also a PR to add support for WinUI - https://github.com/videolan/libvlcsharp/pull/301

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by michalss** [comment]
This is very important task :) I would preferer Adnroid, WinUI first... There is not really any other advance VideoPlayer supporting mutli platform targets.

**Comment by jeromelaban** [comment]
This was added in Uno 4.9.
