### ISSUE TITLE
Sync generator should generate attributes

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10842]
## What would you like to be added:

Almost all classes in UWP/WinUI have attributes declared. While some are not necessarily useful in Uno Platform context, some are, e.g. `[ContentProperty]`.

Sync generator should generate these automatically if they are not present in non-generated code already.

## Why is this needed:

Avoid missing attributes.

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by Youssef1313** [comment]
This should be fixed by https://github.com/unoplatform/uno/pull/11254

@MartinZikmund Feel free to re-open if there are still issues in this area.
