### ISSUE TITLE
Support for TitleBar customization

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#10874]
## What would you like to be added:

WinUI adds support for customizing the title bar (see https://learn.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=wasdk). It would be good to migrate the statusbar from toolkit (https://platform.uno/docs/articles/external/figma-docs/components/status-bar.html) to provide x-plat support for titlebar customization.

## Why is this needed:

Currently the WinUI Titlebar looks awful without customizing it (and worse on WPF) and really doesn't blend well with the material styling option.

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by nickrandolph** [comment]
cc @kazo0 thoughts?

**Comment by MartinZikmund** [comment]
@nickrandolph Which platform primarily, WPF? For WASM I have extend to title bar started here https://github.com/unoplatform/uno/pull/10029.

**Comment by nickrandolph** [comment]
My point here was to try to converge on the new winappsdk APIs for title bar. So I was thinking the iOS/Android status bar support that is in toolkit could be moved into core under this API.

**Comment by jeromelaban** [comment]
It definitely makes sense to integrate these APIs (for platforms that support it) into Uno.UI.

**Comment by manfromarce** [comment]
I think Uno should also use dark titlebars by default when dark theme is used on supported platforms. I have managed to do this using Windows-specific code on WinUi and WPF and it's not hard to do, probably can be done on MacOS and GTK too.

**Comment by lindexi** [comment]
Can TitleBar customization in GTK by use `GTK.Window.Decorated = false`?
