### ISSUE TITLE
Cannot synchronously change TextBox text from TextChanged event

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#1087]
## Current behavior

Setting the Text property of a TextBox in the TextChanged event handler does not actually change the Text value.  No error occurs.

Attempting to change the text property of a TextBox (for instance, setting it to uppercase) during TextChanged does not actually change the text value

## Expected behavior

TextBox should use the new Text value, as in UWP.

## How to reproduce it (as minimally and precisely as possible)

[WasmPlaceholderText.zip](https://github.com/nventive/Uno/files/3298021/WasmPlaceholderText.zip)

In the attached sample type any value into the textbox.  The value should be converted to uppercase using the TextChanged event.  Works in UWP.

## Environment

Nuget Package:
Uno.UI
Package Version(s):
1.45.0-dev.1833
Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
Which one are you using, the `TextChanged` or `TextChanging` event? The former is supported in Uno, the latter is not.

**Comment by peternary** [comment]
I am using TextChanged
