### ISSUE TITLE
Make style properties of `PersonPicture` overwriteable

### ISSUE THREAD

**Issue by jp-weber** [unoplatform/uno#10883]
## What would you like to be added:
The background and other properties are not overwriteable, but this should normally be the case.
## Why is this needed:
Currently the default style have a fix background and other properties for the ellipse control.

## Anything else we need to know?
The issue is also active at WinUI2:
https://github.com/microsoft/microsoft-ui-xaml/issues/6654
https://github.com/microsoft/microsoft-ui-xaml/pull/6655

**Comment by jeromelaban** [comment]
Indeed, and thanks for taking the time to create a mirrored PR! We'll merge it once the PR on the WinUI side has been merged.
