### ISSUE TITLE
RepeatBehavior count and duration syntax are not parsed correctly

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#10887]
### Current behavior

Given:
```xml
<DoubleAnimation RepeatBehavior="2x" ... />
<!-- OR -->
<DoubleAnimation.RepeatBehavior>0:30:0</DoubleAnimation.RepeatBehavior>
```
The result is a `RepeatBehavior` of type `Duration` and a duration of 0.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.9.16

### Affected platforms

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

### IDE

Visual Studio 2022

### Anything else we need to know?

"Forever", however, is handled properly.

The XamlCodeGenerator produces the following: // any text value is just copied here as-is
```cs
new global::Windows.UI.Xaml.Media.Animation.DoubleAnimation
{
	RepeatBehavior = @"2x"/* Windows.UI.Xaml.Media.Animation.RepeatBehavior/, 2x, DoubleAnimation/RepeatBehavior */,
}
```
Which is then handled by [this implicit operator](https://github.com/unoplatform/uno/blob/4.6.19/src/Uno.UI/UI/Xaml/Media/Animation/RepeatBehavior.cs#L88)...

Of note, on uwp, attempting to cast a string into `RepeatBehavior` would result in a compilation error.

**Comment by Youssef1313** [comment]
> Of note, on uwp, attempting to cast a string into `RepeatBehavior` would result in a compilation error.

I think I encountered extra implicit conversion operators in Uno few times. For now, easiest is to extend the existing implicit conversion to handle everything correctly.

But maybe we should consider a breaking change to remove all those unnecessary implicit conversions.

**Comment by Xiaoy312** [comment]
Of course, fixing the operator would be the path of least resistance.

We should, however, be fixing this on the xaml side eventually, 
so that we can also throw compilation error for illegal move like: `RepeatBehavior="asd"`.
Instead of just letting it build and not-function/throw at runtime.
