### ISSUE TITLE
Clean up / Update Template .vsconfig

### ISSUE THREAD

**Issue by dansiegel** [unoplatform/uno#10880]
## Why is this needed:

The new project template includes a .vsconfig file to help ensure that the necessary workloads are installed. This however has a number of "required" components that may be nice to have but shouldn't be required. This should be cleaned up to remove components that aren't really required.

```json
{
  "version": "1.0",
  "components": [
    "Microsoft.NetCore.Component.Runtime.3.1",
    "Microsoft.VisualStudio.Component.SQL.ADAL",
    "Microsoft.VisualStudio.Component.SQL.LocalDB.Runtime",
    "Microsoft.VisualStudio.Component.Common.Azure.Tools",
    "Microsoft.VisualStudio.Component.SQL.CLR",
    "Microsoft.VisualStudio.Component.MSODBC.SQL",
    "Microsoft.VisualStudio.Component.MSSQL.CMDLnUtils",
    "Microsoft.VisualStudio.Component.ManagedDesktop.Core",
    "Microsoft.VisualStudio.Component.SQL.SSDT",
    "Microsoft.VisualStudio.Component.SQL.DataSources",
    "Component.Microsoft.VisualStudio.Web.AzureFunctions",
    "Microsoft.VisualStudio.ComponentGroup.AzureFunctions",
    "Microsoft.VisualStudio.Component.Azure.Compute.Emulator",
    "Microsoft.VisualStudio.Component.Azure.Storage.Emulator",
    "Microsoft.VisualStudio.Component.Azure.ClientLibs",
    "Microsoft.VisualStudio.Component.Azure.AuthoringTools",
    "Microsoft.VisualStudio.Component.CloudExplorer",
    "Microsoft.VisualStudio.ComponentGroup.Web.CloudTools",
    "Microsoft.VisualStudio.Component.DiagnosticTools",
    "Microsoft.VisualStudio.Component.EntityFramework",
    "Microsoft.VisualStudio.Component.AspNet45",
  ]
}
```

## For which Platform:

- [x] Solution Templates

## Anything else we need to know?

This should be updated in both the core Uno templates and Uno.Extensions template

**Comment by Youssef1313** [comment]
They were removed in the past but are added again automatically when built locally. So, I added them again back.

I'm not sure why they are added back automatically though.

If these will be removed, we should make sure they don't get automatically added (and understand the reasons). Otherwise, they should be kept as-is.

**Comment by jeromelaban** [comment]
Related to https://github.com/unoplatform/uno/issues/9357
