### ISSUE TITLE
[4.7.0-dev.819] AndroidManifest.xml is not found where expected using new templates

### ISSUE THREAD

**Issue by spouliot** [unoplatform/uno#10890]
### Current behavior

```
/xxx/unoapp/unoapp.Mobile/unoapp.Mobile.csproj
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/32.0.476/tools/Xamarin.Android.Common.targets(517,3): Error: Specified AndroidManifest file does not exist: /xxx/unoapp/unoapp.Mobile/AndroidManifest.xml.
```

it should be looking for `unoapp/unoapp.Mobile/Android/AndroidManifest.xml`

### Expected behavior

Project should load without error.

### How to reproduce it (as minimally and precisely as possible)

```
$ dotnet new install Uno.ProjectTemplates.Dotnet::4.7.0-dev.819
$ dotnet new unoapp
```

Open the `unoapp.Mobile.csproj` inside your IDE.

### Workaround

Move `AndroidManifest.xml` to the _expected_ location.

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Solution Templates

### Anything else we need to know?

The `AndroidManifest.xml` file was moved in https://github.com/unoplatform/uno/pull/10704/files#diff-c8c5914cd3d32213162827b6d27cd795d79e7e9b11fbfd342491f5ae647d6d9a

**Comment by dansiegel** [comment]
I believe this is coming from a default value from `AndroidManifest` which we just need to override. I'm not sure if this is something that should perhaps be coming from the Uno props/targets or if we should do this in the template itself. Personally I think it should be done automatically and not be part of the template.

**Comment by jeromelaban** [comment]
This file is supposed to be overriden [by this line](https://github.com/unoplatform/uno/blob/7c727a13ed058dc8f9f8dd572f1772204abe1647/build/uno.winui.single-project.targets#L58). If it's not used, it could either mean that this file's content is not used, or that for some other reason it's no read at the proper time.

**Comment by spouliot** [comment]
I was not able to repro this with a new app template... something else is likely at play (order of operations?) to trigger this. 

Since this is something I'm doing often right now I'm closing this until I can get repro and gather more information.

**Comment by spouliot** [comment]
This situation can happen when the `bin` and `obj` directories are removed.

The easy solution, thanks to @jeromelaban, is to do a `dotnet restore`.
