### ISSUE TITLE
[iOS 15-16] ListViewItem with dynamic height can cutoff on scroll

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#10901]
### Current behavior

Items in the ListView starts to cutoff or either overlap in between themself when scrolling on a device/simulator that has iOS 16 and higher.

![listviewbug2](https://user-images.githubusercontent.com/17461593/210902105-b9207c70-142f-425e-b995-e63c3a57c5b1.gif)

<details>
<summary>still images</summary>

![image](https://user-images.githubusercontent.com/17461593/210902270-91d3bb4d-fba7-422c-b7bc-dedb09621469.png)
![image](https://user-images.githubusercontent.com/17461593/210902292-245e7808-a63b-4dc6-8da9-a12e2acd3d30.png)
![image](https://user-images.githubusercontent.com/17461593/210902311-b864440e-fabd-495b-9360-2f1737d93146.png)
</details>
Tested on a simulator Iphone 14 iOS 16.1

### Expected behavior

![expectedios2](https://user-images.githubusercontent.com/17461593/210902489-879c0814-1142-4257-9cae-5b67a2274b77.gif)

Tested on a Iphone SE iOS 14.4

### How to reproduce it (as minimally and precisely as possible)

- Download this sample [ListViewButton.zip](https://github.com/unoplatform/uno/files/10356382/ListViewButton.zip)
- Deploy on iOS with a device/simulator that uses iOS 16 or higher
- Scroll through items
  > it helps to scroll a slow as possible (prefer press-drag-release over mousewheel) and it occurs more often on scroll back (bottom to top)

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.7.0-dev.830

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.4.3

### Anything else we need to know?

In seems that the bug is worse when there are other element in the page. For instance, in the sample provided in this issues contains a simple `Button` at the bottom. On the project, I'm working on, I was able to reproduce it with a `Commandbar` as well. When I removed the button in the sample, the bug happened like once (I'm not sure if it was a fluke or could be a lead for this issue).

**Comment by takla21** [comment]
Wondering if it could be related to this https://github.com/unoplatform/uno/issues/9416

**Comment by jeromelaban** [comment]
@ajpinedam does this look familiar?

**Comment by ajpinedam** [comment]
@jeromelaban could be related to this issue https://github.com/unoplatform/uno/issues/9416 I worked on a few months ago

cc: @Xiaoy312

**Comment by takla21** [comment]
I have updates about this issues.

First, we've found out that it's not only an **iOS 16** issues. It does also happen on **iOS 15**. Not on iOS 14 though.
Second, I may have not explicitly mentionned it here, but this bugs exist currently on current stable version for (**4.5 & 4.6**)
