### ISSUE TITLE
`SimpleOrientationSensor` should not schedule on `Dispatcher`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10905]
Similarly to other sensors, the events should not be scheduled on `Dispatcher` to avoid swamping the UI thread. Only the user should decide whether using the sensor on UI thread is needed.
 https://github.com/unoplatform/uno/blob/7e3668befe70afaf9228e712e43531b0dd7720dc/src/Uno.UWP/Devices/Sensors/SimpleOrientationSensor.cs#L69-L79 ? [UWP Sample](https://github.com/microsoft/Windows-universal-samples/blob/ad9a0c4def222aaf044e51f8ee0939911cb58471/Samples/SimpleOrientationSensor/cs/Scenario1_DataEvents.xaml.cs#L140-L146)

This code is already in main, should it be changed?

_Originally posted by @Youssef1313 in https://github.com/unoplatform/uno/pull/10893#pullrequestreview-1238442737_

**Comment by jeromelaban** [comment]
It should be restored to the dispatcher using a feature flag as needed, though this particular sensors is not high-throughput so it may be too big of an issue.

Let's add it to the list of breaking changes.
