### ISSUE TITLE
The border doesn't display when set the CornerRadius on Ubuntu Desktop 22.04.1

### ISSUE THREAD

**Issue by caoyanmin** [unoplatform/uno#10906]
### Current behavior

When I set the Border's CornerRadius, the Border can display on Windows 10, but it can' display on Ubuntu Desktop 22.04.1.
`<Page x:Class="DemoApp.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:local="using:DemoApp"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      mc:Ignorable="d">

    <Grid>
        <Border Width="200"
                Height="20"
                Background="Red"
                CornerRadius="4" />
    </Grid>
</Page>
`

### Works on UWP/WinUI

None

### NuGet package version(s)

<PackageReference Include="Uno.UI.Skia.Gtk" Version="4.6.39" />

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. We've made changes for this in the latest Uno 4.7-dev builds. Could you try it out ?
