### ISSUE TITLE
[iOS][`DatePicker`] Regression: on latest pre-release builds, the native flyout is placed next to the button rather than at the bottom of the screen

### ISSUE THREAD

**Issue by marwalsch** [unoplatform/uno#10959]
### Current behavior

Uno .WinUi 4.7.0-dev.884 and higher.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/72074423/212036510-2fa7cc5d-89ff-4349-902d-d487057689ae.png)

### Expected behavior

Uno .WinUi 4.7.0-dev.503.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/72074423/212036534-dc1b8d97-7dd6-474b-bbe7-b5263d0514a4.png)

### How to reproduce it (as minimally and precisely as possible)

Create a Blank project, place a DatePicker and change the referenced package version.

### Works on UWP/WinUI

Yes

**Comment by jeromelaban** [comment]
@MartinZikmund this looks like a popup placing change, does it look familiar?

**Comment by MartinZikmund** [comment]
Indeed, must be my bad
