### ISSUE TITLE
Sample code for closing an Uno Desktop App crashes

### ISSUE THREAD

**Issue by CBrauer** [unoplatform/uno#10967]
### Current behavior

I am trying to build a desktop App with the Uno Template, using Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.4.4.

I am having trouble with your sample code on [App close confirmation in UWP – Martin Zikmund (mzikmund.com)](https://blog.mzikmund.com/2018/09/app-close-confirmation-in-uwp/).  The following code throws the error:

 
![bug](https://user-images.githubusercontent.com/1317234/212142421-4ce7d6ab-8b5e-449a-83f0-3e7e488c46fb.PNG)

Any suggestions?

Charles

### Works on UWP/WinUI

None

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

Current Version 17.4.4

**Comment by FrozDark** [comment]
Seems like it's related to Windows head (WinUI) and it's not something related to Uno itself

**Comment by jeromelaban** [comment]
It's indeed caused by `SystemNavigationManagerPreview` [not being available](https://github.com/microsoft/WindowsAppSDK/issues/2398). This is a gap in the APIs, and you may need to look at the `Window` events to get similar functionalities.

**Comment by CBrauer** [comment]
ok, will do
