### ISSUE TITLE
Tooltip does not hide when Button is clicked

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#10979]
### Current behavior

All my buttons have tooltips. There are many scenarios where the hosting UI is 'hidden' as the button is clicked and a new UI is rendered 'on top'.

Unfortunately the ToolTip stays - which is annoying as it does not make sense in the concept of the 'new' UI.
WindowsAppSDK handles those cases correctly.

Please see attached repo.

[ToolTip.zip](https://github.com/unoplatform/uno/files/10418401/ToolTip.zip)

### Expected behavior

UNO WASM should work like WindowsAppSDK.

### Workaround

None

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by FrozDark** [comment]
That's also been seen on Skia heads (GTK, WPF)

**Comment by jeromelaban** [comment]
Thanks for the repro. 

## Note for contributors
This issue is not related to hiding elements, but rather the fact that the tooltip should close when the button is clicked. Note that setting the tooltip on a `TextBlock` does not hide the tooltip when clicked.

**Comment by DierkDroth** [comment]
Thanks for clarification @jeromelaban
