### ISSUE TITLE
`SetNeedsKeyboard` public method in `Window.macOS.cs` does nothing

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#10972]
I can't see how this:

https://github.com/unoplatform/uno/blob/5ea52519c80d1fc3569cae7c261d6ec762dc8233/src/Uno.UI/Controls/Window.macOS.cs#L527-L534

will ever do anything. Both `GetNeedsKeyboard` and `NeedsKeyboard` methods are unused (and will be deleted in a PR where I remove unused private methods).

This is a breaking change since `SetNeedsKeyboard` is public

**Comment by jeromelaban** [comment]
@MartinZikmund may know.

**Comment by Youssef1313** [comment]
#11197
