### ISSUE TITLE
Panel: ArrangeOverride and MeasureOverride not working as expected

### ISSUE THREAD

**Issue by srb-milestone** [unoplatform/uno#10971]
### Current behavior

I created a small app that displays 4 images in a grid using a custom panel.
It works on WinUI but creates a weird layout with Uno:
- The first image is too big and not located at the right location. 
- The Height of the window doesn't seem to be taken into account correctly because images on the last row are rendered outside the window (depending on aspect ratio).

Android:
![image](https://user-images.githubusercontent.com/30240105/212212949-f8897082-9c6f-4f8d-a873-80f334b7e8b2.png)

Wasm:
![image](https://user-images.githubusercontent.com/30240105/212213139-568759be-9e58-4b96-98e2-04a5a342eca8.png)

Gtk:
![image](https://user-images.githubusercontent.com/30240105/212213204-db775d17-8827-4d94-993d-3544d57ea9d3.png)

### Expected behavior

Here's what it looks like on WinUI:

![image](https://user-images.githubusercontent.com/30240105/212213729-6328d13d-7ab0-41fc-bb0c-b8d9662fbc66.png)

### How to reproduce it (as minimally and precisely as possible)

[UnoBug.zip](https://github.com/unoplatform/uno/files/10407280/UnoBug.zip)

### Workaround

None found

### Works on UWP/WinUI

Yes

### NuGet package version(s)

    <PackageReference Update="Uno.Core.Extensions.Logging.Singleton"                 Version="[4.0.1]" />
    <PackageReference Update="Uno.Extensions.Logging.OSLog"                          Version="[1.4.0]" />
    <PackageReference Update="Uno.Extensions.Logging.WebAssembly.Console"            Version="[1.4.0]" />
    <PackageReference Update="Uno.UI.Adapter.Microsoft.Extensions.Logging"           Version="[4.6.19]" />
    <PackageReference Update="Uno.UniversalImageLoader"                              Version="[1.9.36]" />
    <PackageReference Update="Uno.Wasm.Bootstrap"                                    Version="[7.0.3]" />
    <PackageReference Update="Uno.Wasm.Bootstrap.DevServer"                          Version="[7.0.3]" />
    <PackageReference Update="Uno.WinUI"                                             Version="[4.6.19]" />
    <PackageReference Update="Uno.WinUI.Lottie"                                      Version="[4.6.19]" />
    <PackageReference Update="Uno.WinUI.RemoteControl"                               Version="[4.6.19]" />
    <PackageReference Update="Uno.WinUI.Skia.Gtk"                                    Version="[4.6.19]" />
    <PackageReference Update="Uno.WinUI.Skia.Linux.FrameBuffer"                      Version="[4.6.19]" />
    <PackageReference Update="Uno.WinUI.Skia.Wpf"                                    Version="[4.6.19]" />
    <PackageReference Update="Uno.WinUI.WebAssembly"                                 Version="[4.6.19]" />

### Affected platforms

WebAssembly, Android, Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by ramezgerges** [comment]
We have a problem with the way FrameworkElement overrides <Measure|Arrange>Override. Normally in your repro, calling base.<Measure|Arrange>Override shouldn't really do anything, but in Uno, it gives the first child the entire avaiable space that the Panel has. For now, a simple workaround is to return the availableSize (in MeasureOverride) and finalSize (in ArrangeOverride) and not call the base methods.
