### ISSUE TITLE
[WASM] Trying to use LiveChartsCore.SkiaSharpView.Uno.WinUI in wasm

### ISSUE THREAD

**Issue by Jonathanio123** [unoplatform/uno#11007]
### Current behavior

Trying to use Livechartsv2 in wasm following this [tutorial.](https://platform.uno/blog/livecharts-announces-support-for-uno-platform/) Works fine on gtk and windows platforms, but won't build in wasm. It fails to build after adding the nuget package 'LiveChartsCore.SkiaSharpView.Uno.WinUI'. I've tried updating all uno packages to the newest version and pre-release, none work.

I tried following the tutorial and it works fine on windows but still fails on wasm.
![image](https://user-images.githubusercontent.com/73334350/213438018-588ec5bf-b42d-4cf5-9728-6c1362f9c3a1.png)

![image](https://user-images.githubusercontent.com/73334350/213436271-ccc04729-af13-407d-98d3-8f44df45db5f.png)

### Expected behavior

Should build and run.

### How to reproduce it (as minimally and precisely as possible)

[Build Output.txt](https://github.com/unoplatform/uno/files/10456375/Build.Output.txt)

1. dotnet new --install Uno.ProjectTemplates.Dotnet and dotnet new unoapp
2. Wasm and windows platforms work
3. Add LiveChartsCore.SkiaSharpView.Uno.WinUI 
4. Windows and gtk still builds but wasm fails.
5. Add demo code, windows and gtk still builds but wasm fails

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.4.3

### Relevant plugins

ReSharperPlatformVs17

**Comment by jeromelaban** [comment]
Thank you for the report. The resolution is similar to the discussion here: https://github.com/unoplatform/uno/discussions/10806. Note that troubleshooting build errors is generally easier [using these steps.](https://platform.uno/docs/articles/uno-builds-troubleshooting.html#generating-msbuild-binary-log-files)

**Comment by Jonathanio123** [comment]
[The above link worked for me](https://github.com/unoplatform/uno/discussions/10806#discussioncomment-4717150)
Manually installing SkiaSharp.Views.Uno.WinUI in wasm platform fixed it for me.
