### ISSUE TITLE
[Android] `PipsPager` does not look normal

### ISSUE THREAD

**Issue by DmitryBorodiy** [unoplatform/uno#11026]
### Current behavior

Hello, Uno Platform devs community!
I ran into a small issue with the PipsPager control.
The next and previous page buttons look a little odd, check out this OneDrive link.

https://1drv.ms/u/s!AtFuCISL0E8dn9kBtbprJEWIwT7uvQ?e=lpJNi2]

<img width="432" alt="image" src="https://user-images.githubusercontent.com/5839577/214124336-8693bc9b-8e06-4bec-ab50-c1dd0a9fb5f1.png">

Version of Uno.UI is 4.6.19
Tested on Android device only

### Expected behavior

https://learn.microsoft.com/en-us/windows/apps/design/controls/pipspager

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.6.19

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

Latest

**Comment by MartinZikmund** [comment]
The issue is the arrow's alignment, correct?

**Comment by DmitryBorodiy** [comment]
Yeah

**Comment by DmitryBorodiy** [comment]
Previous and next buttons not working. They don't respond to touch.
