### ISSUE TITLE
Implement Accelerometer APIs

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1103]
## What would you like to be added: 
Support for the `Windows.Devices.Sensors.Accelerometer`

## Why is this needed: 
Commonly used device capability

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

**Comment by MartinZikmund** [comment]
I will implement it :-)

**Comment by ghuntley** [comment]
Lovely, thank-you.
