### ISSUE TITLE
TextBox.Text = null throws exception

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#11031]
### Current behavior

Please see attched repo and search for '!!!'

[TextBoxText.zip](https://github.com/unoplatform/uno/files/10482184/TextBoxText.zip)

WASM throws exception as per screenshot below
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26179242/214107703-a6be9623-783a-45bf-b143-e93d72743766.png">

### Expected behavior

WASM should work as WindowsAppSDK

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by Youssef1313** [comment]
Is WinUI behavior different than UWP?

I think UWP used to throw null when setting the text to null. https://github.com/unoplatform/uno/pull/1303

**Comment by marwalsch** [comment]
The issue is reproducible on iOS and Android as well.

@Youssef1313 It is, WinUI has no issue with null assignements to TextBox.Text.

**Comment by DierkDroth** [comment]
@jeromelaban @Youssef1313 thanks guys
