### ISSUE TITLE
[iOS] [Android] ItemsControl - GroupHeader does not display 

### ISSUE THREAD

**Issue by DevenCC** [unoplatform/uno#11041]
### Current behavior

Displaying a grouped ObservableCollection with a ItemsControl does not display the group header template on Android and iOS like it does on the UWP project. Displaying the same grouped ObservableCollection with a ListView display the group header template on all 3 projects.

![image](https://user-images.githubusercontent.com/2773308/214333287-6cd6b8f8-1f21-4fc6-bd9c-f3451f4578d7.png)
![image](https://user-images.githubusercontent.com/2773308/214333379-febf7eaa-51f0-4eb6-a45a-7f8c4699e2ef.png)

### Expected behavior

I would expect the ItemsControl to act similarly to the ListView in being able to display the group header template on all 3 projects

### How to reproduce it (as minimally and precisely as possible)

[UnoTest.zip](https://github.com/unoplatform/uno/files/10491461/UnoTest.zip)

### Workaround

Using [ItemsRepeater](https://learn.microsoft.com/en-us/windows/apps/design/controls/items-repeater)

### Works on UWP/WinUI

Yes

### NuGet package version(s)

 <PackageReference Include="Microsoft.UI.Xaml" Version="2.8.2" />
  <PackageReference Include="Uno.Extensions">
      <Version>2.2.0</Version>
    </PackageReference>
    <PackageReference Include="Uno.UI" Version="4.6.41" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
    <PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />

### Affected platforms

Android, iOS

### IDE

Visual Studio 2022

### IDE version

17.4.4

### Relevant plugins

n/a

### Anything else we need to know?

Using a local version of the GroupedCollectionBehavior for both controls. Only the one for ListView seems to function for all platforms. 

https://github.com/nventive/Nventive.View/blob/42cb7333cdd4ae16cd4304457e215f8fc7c548e9/src/View.Uno.Shared/Extensions/ListView/GroupedCollectionBehavior.cs

**Comment by francoistanguay** [comment]
Have you looked into using ItemsRepeater and doing the grouping "manually"?

**Comment by DevenCC** [comment]
No I haven't. I'll try the ItemsRepeater control and update this issue with that workaround if it solves the problem.

**Comment by francoistanguay** [comment]
If you have further questions, @dr1rrb  can help you.

**Comment by jeromelaban** [comment]
`ItemsRepeater` may also be an replacement for this issue.

**Comment by francoistanguay** [comment]
Yes, that's exactly ou rrecommendation: "Manual" grouping and then show your headers in  your items as you see fit.
