### ISSUE TITLE
Adding null to application settings throws

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1104]
## Current behavior

Adding a `null` value to `ApplicationData.Current.LocalSettings` throws on Android and iOS.

## Expected behavior

Adding a `null` value should be supported same way as on UWP.

## How to reproduce it (as minimally and precisely as possible)

```
ApplicationData.Current.LocalSettings.Values.Add( "something", null );
```
## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly (not tested)
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
I will fix this one :-)

**Comment by ghuntley** [comment]
Lovely, thank-you.

**Comment by MartinZikmund** [comment]
Done :-)
