### ISSUE TITLE
[Wasm] Satellite assemblies are not properly published

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#11043]
### Current behavior

In WASM, the ResourceManager.GetString uses the CultureInfo as parameter, but fails to recognise the culture passed
![image](https://user-images.githubusercontent.com/888391/214426433-f9d26ac5-f0ba-45e7-94ff-8f6e055f69b1.png)

### Expected behavior

It should return the culture passed regardless of the supported languages of the browser.

### How to reproduce it (as minimally and precisely as possible)

see example in https://github.com/paulovila/UnoLocalization/blob/master/App9/App9.Shared/MainPage.xaml.cs
[UnoLocalization-master.zip](https://github.com/unoplatform/uno/files/10494261/UnoLocalization-master.zip)

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
Localization at this time is best supported using resw, not embedded assembly resources. Are you able to use resw instead?

**Comment by paulovila** [comment]
The netstandard2 project is also referenced from WPF, therefore ```Windows.ApplicationModel.Resources.ResourceLoader              .GetForViewIndependentUse().GetString(resource);``` can't be used.
Is it possible to  re-implement ```System.Resources.ResourceManager.GetString``` , or where's the source code of this?

**Comment by jeromelaban** [comment]
Thanks. This issue is related to satellite assemblies publishing in the uno bootstrapper. Reimplementing it on your side is one option, but not necessarily the best one either.

**Comment by darenm** [comment]
@jeromelaban Sounds like this is a non-trivial issue to address on either side. Are there any plans to address this in Uno?
