### ISSUE TITLE
[Gallery][Wasm]Numberbox- Not able to type any Text(Number) for the 'Numberbox with compact spin button Placement' Textbox.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11053]
### Current behavior

![Uno Gallery numberbox issue](https://user-images.githubusercontent.com/74563602/214680694-842b62a6-430a-4697-b5b3-f500f1e7fb75.png)

https://user-images.githubusercontent.com/74563602/214661542-fc7bea3b-da65-4aab-8b56-ba3a4bcf4ff4.mp4

### Expected behavior

https://user-images.githubusercontent.com/74563602/214676528-4c84af7d-0097-442b-a9ee-b82ec83f3a62.MP4

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "NumberBox" from the "UI Componennts" list.
4. Go to  'A  Numberbox with a spin button' Section.
5. Click on the Textbox to add a number on the textbox for 'Numberbox with compact spin button Placement' sectiion
6. Observe that not able to type the text for the textbox.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by Youssef1313** [comment]
@jeromelaban I can reproduce this in Uno.Gallery, but not in SamplesApp. Got any idea what could be special with Uno.Gallery?

**Comment by jeromelaban** [comment]
This could be caused by some material themes? Maybe @agneszitte-nventive or @kazo0 have some insight on this.
