### ISSUE TITLE
`PipsPager` not rendering the same everytime

### ISSUE THREAD

**Issue by ghost** [unoplatform/uno#11068]
## Current behavior

PipsPager is not rendering all pips everytime. Sometimes, it renders just the first pip (marker) and doesn't render the rest. If you change the code to force a refresh, sometimes it renders correctly.
![image](https://user-images.githubusercontent.com/100223422/214926026-0f5774b5-2859-4bf3-ab88-792f4c9bba32.png)

## Expected behavior

Should work the same way everytime.

![image](https://user-images.githubusercontent.com/100223422/214926102-a4a73e23-e440-40df-a005-9ea5046af94f.png)

## How to reproduce it (as minimally and precisely as possible)

I just added the following code to the default code in Playground home page.

The attributes doesn't matter. Even when you just add a single pipspager with at least NumberOfPages > 0 (to have more than one pip) it will fail sometimes...

https://playground.platform.uno/#c1aa23a3

  <muxc:PipsPager x:Name="DefaultPipsPager" 
                    NumberOfPages="4" 
                    Background="Orange" 
                    Orientation="Vertical"
                    PipsPagerButtonVisibility="Visible"
                    Style="{StaticResource PipsPager}" 
    /> 

## Environment

Playground website at 2023-01-26

Nuget Package:

Package Version(s):

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ramezgerges** [comment]
Seems fixed to me. Maybe someone else should verify as well in case the repro is not consistent

**Comment by morning4coffe-dev** [comment]
@ramezgerges When the NumberOfPages is set to the original 4, I can no longer replicate this issue also. But when you set it to something like 20, it starts to break again:  

http://playground.platform.uno/#4f006ad8

https://github.com/unoplatform/uno/assets/78549750/a336e964-29f6-4540-b711-6c6bf6c7962f

**Comment by ramezgerges** [comment]
@morning4coffe-dev nice catch. Just tested on canary,  it's fixed on master through #14595. I forgot to handle the vertical case so I also submitted #14839. Thanks.
