### ISSUE TITLE
[Gallery][Wasm]CalendarDatePicker- In second click on 'select a date' option in the pop-up calendar the current year is incorrect.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11064]
### Current behavior

![Calendardatepicker wasm issue](https://user-images.githubusercontent.com/74563602/214896414-c17e61d6-3d37-4581-bfd8-2334abee372c.png)

### Expected behavior

Current year should display(2023)

![CDP-Correct](https://user-images.githubusercontent.com/74563602/214900845-dd412f2c-de62-42fe-9911-530082f6bb2a.png)

### How to reproduce it (as minimally and precisely as possible)

Open Uno Gallery APP
Click Burger Menu on the left top right.
Click "CalendarDatePicker" from the "UI Components" list.
Click two times on the 'Select a date' option.
Notice that the  current year in the pop calendar is incorrect(Displaying 1923 instead of 2023)

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by Youssef1313** [comment]
There is a Wasm-specific code here:

https://github.com/unoplatform/uno/blob/fc309f1f15808a66593811e9daacba8b432b260b/src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarDatePicker_themeresources.xaml#L80

Not sure if it's related.

**Comment by Youssef1313** [comment]
This reproduces in SamplesApp when `UnoTargetFrameworkOverride` is `net7.0` but not when it is `netstandard2.0`. Still trying to figure it out.
