### ISSUE TITLE
[Gallery][Skia.Gtk]TextBox and PasswordBox-TextBox is flickering when clicked 2nd time after typing text in the textbox.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11066]
### Current behavior

https://user-images.githubusercontent.com/74563602/214914675-efb4b746-873c-4516-9a6d-6bbc681b92f0.mp4

### Expected behavior

Screen should not  flicker.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "TextBox" from the "UI Components" list.
4. Click on any Textbox option and type some text.
5. Go to another Text Box option and for that textbox also type some text.
6. Now again click on the textbox for which the text is already typed.
7. Notice that the Textbox started flickering.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by jeromelaban** [comment]
Likely related to https://github.com/unoplatform/uno/pull/10935 /cc @MartinZikmund

**Comment by MartinZikmund** [comment]
Definitely on me
