### ISSUE TITLE
[Uno.check 1.11] Complains about Python missing, although it's installed.

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#11073]
### Current behavior

Please see screenshots below

<img width="675" alt="image" src="https://user-images.githubusercontent.com/26179242/215034000-26caf97f-ee67-413e-843c-dbb32d72b429.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/26179242/215033762-f314949b-c83b-4663-bc54-ff5918a2dc4e.png">

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
This was fixed and merged yesterday. See https://github.com/unoplatform/uno.check/pull/125

**Comment by DierkDroth** [comment]
Thanks @Youssef1313. 

To clarify: the fix would be available with Uno.check 1.12, correct?

**Comment by Youssef1313** [comment]
Yes. The fix is already in `1.12.0-dev.4`

**Comment by DierkDroth** [comment]
Thanks again @Youssef1313

**Comment by Youssef1313** [comment]
Most welcome!
