### ISSUE TITLE
document what UWPSyncTool is and how to remove generated items as part of contributing a feature

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1107]
💅 minor nitpick, that doesn't require a change. This entire file could have been reduced to

```
#pragma warning disable 108 // new keyword hiding
#pragma warning disable 114 // new keyword hiding
namespace Windows.Devices.Sensors
{
	public partial class BarometerReadingChangedEventArgs 
	{

	}
}
```

and it will be automatically done next time we re-run the UWPSyncTool. This really isn't documented anywhere and I've taken an action to 🖊 something up to make it more clear. 👍

_Originally posted by @ghuntley in https://github.com/nventive/Uno/pull/1066_

**Comment by davidjohnoliver** [comment]
This is now covered under the contributor docs on Uno's internals: https://github.com/unoplatform/uno/blob/ad6c1ca7ca0f45242e4e9b432782bc770a2663b3/doc/articles/uno-development/uno-internals-overview.md#generated-notimplemented-stubs
