### ISSUE TITLE
Error on upgrading the Microsoft.WindowsAppSDK to latest version (1.2.230118.102)

### ISSUE THREAD

**Issue by NaveenBadal** [unoplatform/uno#11087]
### Current behavior

When trying to upgrade the common project (.shared one) from 1.1.3 (which comes by default on creating) to the latest version 1.2.230118.102 or 1.2.221209.1, Error is coming stating that "Duplicate Content Items were included".

Because of this, prjoject is not getting build.
Please see the attached screenshot.
![Screenshot 2023-01-28 123605](https://user-images.githubusercontent.com/42309324/215252257-c2effbb9-7cea-45d5-b7ba-a2fc68086960.png)

### Expected behavior

Project should get upgrades to the latest version , without any error.

### How to reproduce it (as minimally and precisely as possible)

1.) Create a new project through Uno Platform Templates.
2.) Select the wasm and windows only.
3.) Now upgrade the Microsoft.WindowsAppSDK to latest version and try to build. 

Exception will come and project will not get build.

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
@NaveenBadal I'm not able to reproduce this.

![image](https://user-images.githubusercontent.com/31348972/215292323-ce2417f1-036c-4013-9fc9-b002abafd4dc.png)

Can you please upload a binary log or a repro project? Thanks!

**Comment by jeromelaban** [comment]
@NaveenBadal it's also generally a good idea to avoid opening multiple issues on the same repo. Let's continue in https://github.com/unoplatform/uno/discussions/11088
