### ISSUE TITLE
[WASM] [JSInterop] WebAssemblyRuntime.InvokeAsync() Returns null if the underlying Promise does not return a string value.

### ISSUE THREAD

**Issue by EvarDion** [unoplatform/uno#11092]
### Current behavior

If you invoke a Javascript function that returns a promise using WebAssemblyRuntime.InvokeAsync()
and that promise does not resolve to a javascript string then the value of **str** is ignored and null is returned instead.

![image](https://user-images.githubusercontent.com/18524364/215329573-9fd13680-c459-4125-8067-47f049412e45.png)

[Link to the problem source code is here](https://github.com/unoplatform/uno/blob/a2347991a4b874da01830306677fd3e5270c1901/src/Uno.UI/ts/Interop/AsyncInteropHelper.ts#L27)

### Expected behavior

Expected behavior would be for the promise result to be serialized as JSON if the **str** not a string.
failing that it should return **str.toString()**

at the very least if **str** is not actually a string then a meaningful warning should be logged in the console.

### Workaround

make sure all of your async functions that are called by **WebAssemblyRuntime.InvokeAsync()** return a promise that resolves to a string value.

### Works on UWP/WinUI

None

### NuGet package version(s)

"Uno.Wasm.Bootstrap" Version="7.0.11" 
"Uno.WinUI.Runtime.WebAssembly" Version="4.6.39" 
"Uno.WinUI.WebAssembly" Version="4.6.39" 

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by MartinZikmund** [comment]
@jeromelaban I am not sure this limitation is still relevant as we transition to `JSImport`

**Comment by jeromelaban** [comment]
It's probably still true, but InvokeJS will be deprecated soon.
