### ISSUE TITLE
`WebView.NavigateWithHttpRequestMessage` has wrong parameter type

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11099]
### Current behavior

Parameter is of type `System.Net.Http.HttpRequestMessage`

https://github.com/unoplatform/uno/blob/a911ec8288090db0cf3fd0c6a8815c612e531ab7/src/Uno.UI/UI/Xaml/Controls/WebView/WebView.cs#L147

### Expected behavior

Parameter is of type `Windows.Web.Http.HttpRequestMessage`

I added this to the breaking changes roundup issue https://github.com/unoplatform/uno/issues/8339

**Comment by jeromelaban** [comment]
Can you specify which is the declaring type?

**Comment by Youssef1313** [comment]
WebView. I edited the issue and added a link to the exact source code line.

**Comment by MartinZikmund** [comment]
Assigning this to me as well, as I am working on `WebView` changes
