### ISSUE TITLE
Avoid including pdb in NuGet packages

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11102]
https://github.com/dotnet/sourcelink/blob/main/README.md

> If you distribute the library via a package published to [NuGet.org](http://nuget.org/), it is recommended to build a [symbol package](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg) and publish it to [NuGet.org](http://nuget.org/) as well. This will make the symbols available on [NuGet.org symbol server](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#nugetorg-symbol-server), where the debugger can download it from when needed. Alternatively, you can [include the symbols in the main package](https://github.com/dotnet/sourcelink/blob/main/README.md#alternative-pdb-distribution). However, doing so is not recommended as it increases the size of the package and thus restore time for projects that consume your package.

**Comment by jeromelaban** [comment]
The benefits of such an approach are limited at this time, and it is not properly supported by Xamarin. We'll be able to migrate to this approach when we'll remove Xamarin targets.

**Comment by MartinZikmund** [comment]
@Youssef1313 @jeromelaban I think this can be addressed now for 5.x

**Comment by jeromelaban** [comment]
It may. I'm not seeing many packages using this though, so it may still be an issue.

**Comment by Youssef1313** [comment]
This may break our nuget override logic. Let's keep things as-is for now.
