### ISSUE TITLE
Warn users when using long path to app codebase

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#11117]
## What would you like to be added:

When path to app codebase is too long, it may cause weird and unexpected issues like the following when trying to publish WASM app:

![image](https://user-images.githubusercontent.com/1075116/215783532-109ac742-2a97-4e9c-a856-dc6235b46aef.png)

Guessing similar would happen when publishing the other targets.

**It would be great if Uno recognized this automatically and warned the user prominently to avoid weird behaviors.**

## Why is this needed:

Avoiding papercuts.

## For which Platform:

- [x] Build tasks
- [x] Solution Templates

**Comment by Youssef1313** [comment]
@MartinZikmund Maybe we should just remove this condition?

https://github.com/unoplatform/uno/blob/d28f39dbe71bd0db394118a3bb469c1c4ab64ee4/src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props#L475

**Comment by jeromelaban** [comment]
The problem here is more about building inside visual studio specifically, as building on linux or CLI should not display the warning.

**Comment by MartinZikmund** [comment]
https://github.com/unoplatform/uno/pull/11118#issuecomment-1410529881

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/674

> I would still suggest warning the users on Windows to move the project to shorter path, as this problem may manifest in unexpected ways, even if the paths are correctly enabled by uno-check (which does enable them, right?)

I guess if app.manifest fixes it for your repro, we should be fine.

If another case arises, we can fix it on its own.

@MartinZikmund Would you be able to test with the artifacts from #674 ?

**Comment by MartinZikmund** [comment]
Unfortunately, it is not my repro, I got it from another user, who already moved the folder up the hierarchy. But I can ask him later to try again with the updated version when this gets merged

**Comment by MartinZikmund** [comment]
Closing for now, didn't happen since.
