### ISSUE TITLE
[Windows] Hot reload not working properly with the new project layout

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#11122]
### Current behavior

With the latest solution templates, Windows App SDK hot reload does not seem to be working (even if the target is explicitly selected in the dropdown). I am guessing this will be for WinUI team to fix.

### Expected behavior

Should work.

### Works on UWP/WinUI

None

**Comment by MartinZikmund** [comment]
CC @jeromelaban

**Comment by jeromelaban** [comment]
Fixed by https://github.com/unoplatform/uno/pull/11085. net7.0-windows must be the first target framework of the list.

**Comment by oliverw** [comment]
> Fixed by #11085. net7.0-windows must be the first target framework of the list.

Care to elaborate what that means? 😄

**Comment by jeromelaban** [comment]
In the `<TargetFrameworks>` property, `net7.0-windows` needs to be the first value. This just changed in Uno 4.7.37 if you update your `dotnet new` or your Visual Studio addin.
