### ISSUE TITLE
Make `SolidColorBrushHelper` internal

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11127]
https://github.com/unoplatform/uno/blob/a2d1ce2bc68248a809c26e6f6909750439fcee71/src/Uno.UI/UI/Xaml/SolidColorBrushHelper.cs#L27

This doesn't exist in Windows and should probably be removed as a breaking change in next major release.

**Comment by MartinZikmund** [comment]
Agreed, the type causes confusion for new users
