### ISSUE TITLE
Add support for Windows.ApplicationModel.Calls.PhoneCallManager

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1114]
## What would you like to be added:

Support for some of the `PhoneCallManager` APIs

## Why is this needed:

I use it in one of my apps :-) 

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

**Comment by MartinZikmund** [comment]
I have already started implementing this ;-)

**Comment by jeromelaban** [comment]
You're on fire! ;)
