### ISSUE TITLE
[Gallery][Android]Textbox- Cursor doesn't display correctly after entering text.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11147]
### Current behavior

![Textbox issue](https://user-images.githubusercontent.com/74563602/216158033-353b73e9-f7f5-4a0a-a3e6-06fae0ad270c.png)

https://user-images.githubusercontent.com/74563602/216157618-59dd8de7-3902-494f-a00f-0c0affb6161b.mp4

### Expected behavior

https://user-images.githubusercontent.com/74563602/216158060-1c66b719-57d5-48df-bd38-f07de21be724.MP4

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "TextBox" from the "UI Components" list.
4. Click on Outlined option and type some text.
5. Wait for few second
6. Notice cursor is splitting  and blinks as broken.

### Works on UWP/WinUI

None

### Affected platforms

Android

**Comment by lesterbotello** [comment]
I'm not able to reproduce this in Android emulator or physical devices (one Pixel and one Samsung phone). I think this might have been fixed already.

**Comment by jeromelaban** [comment]
Thanks @lesterbotello let's close then. @sakshi173, can you reevaluate?
