### ISSUE TITLE
[WASM] InlineCollection.CopyTo throws exception

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#11160]
### Current behavior

Please see attached and search MainWindow.xaml.cs for '!!!'.

I'm a bit surprised:
- I would have thought there is an 'UNO not supported' warning on methods/properties which are not supported
- I wonder why it's not supported in the first place. I would have thought the implementation comes with the generic IList<> ?!?

[TextBlockInlines.zip](https://github.com/unoplatform/uno/files/10568303/TextBlockInlines.zip)

### Expected behavior

WASM should would as WindowsAppSDK

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by jeromelaban** [comment]
Thanks for the report. InlineCollection.ToArray is an Enumerable extension which uses `Microsoft.UI.Xaml.Documents.InlineCollection.CopyTo` and is the method that is not implemented.

Fixed by https://github.com/unoplatform/uno/pull/11161

**Comment by jeromelaban** [comment]
Also, for future issues, it's best if you can paste the exception in the issue directly as it enables easier triage.

**Comment by DierkDroth** [comment]
Thanks @jeromelaban
