### ISSUE TITLE
[Gallery][Android]Lamp - Slider for Brightness is missing.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11177]
### Current behavior

![Android Brightness issue](https://user-images.githubusercontent.com/74563602/216466642-cae148bf-4e21-4863-83c6-db58a8a8a35a.png)

### Expected behavior

![iOS Brightness correct](https://user-images.githubusercontent.com/74563602/216466659-e14123da-be7f-46a4-8b7a-d9090c74aab6.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "Lamp" from the "Non UI Features" list.
4. Notice that for the Lamp control section Slider for brightness is missing.

### Works on UWP/WinUI

None

### Affected platforms

Android

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/Uno.Gallery/blob/0e6d474f11aab497f0d723f2528b2cd1fe51b1da/Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/LampSamplePage.xaml.cs#L75

https://github.com/unoplatform/Uno.Gallery/blob/0e6d474f11aab497f0d723f2528b2cd1fe51b1da/Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/LampSamplePage.xaml.cs#L77-L79

Looks like brightness is only supported for iOS. Same issue will be in all other platforms.
