### ISSUE TITLE
[Gallery][iOS]PhoneCallManager- 'Show phone call settings UI' section is missing.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11179]
### Current behavior

![phonecallmanager issue](https://user-images.githubusercontent.com/74563602/216471559-566d78fa-eb70-4f05-9341-8eb84cbf4738.png)

### Expected behavior

![phonecallmanager corrrect](https://user-images.githubusercontent.com/74563602/216471586-390ac4b5-55e4-46a3-9d48-6dc318636094.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Notice that 'Show phone call settings UI' section is missing for iOS.

### Works on UWP/WinUI

None

### Affected platforms

iOS

**Comment by Youssef1313** [comment]
Currently this is expected. The API isn't yet implemented for iOS.

https://github.com/unoplatform/uno/blob/2af7e1a84fbee5008de9e4bcb8056652c4a7c600/src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Calls/PhoneCallManager.cs#L35-L36

**Comment by sakshi173** [comment]
As @Youssef1313 said the API is no yet available for iOS, I am closing this bug.
