### ISSUE TITLE
[iOS] Linked images not displaying 

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#11204]
### Current behavior

Adding an image as content with Link attribute set doesn't always work for iOS (all other targets appear to behave correctly, although haven't tested linux framebuffer or macos/catalyst).

```
<Content Include="..\dotnet_bot_link.png">
    <Link>MyImages\dotnet_bot_link.png</Link>
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</Content>
```

When referenced from XAML there is mixed results:

**Works**
`<Image Source="ms-appx:///MyImages/dotnet_bot_link.png" />`
**Doesn't work**
`<Image Source="MyImages\\dotnet_bot_link.png" />`
**Doesn't work**
`<Image Source="ms-appx:///ImageSampleApp/MyImages/dotnet_bot_link.png" />`

![image](https://user-images.githubusercontent.com/1614057/216910167-5103ae61-09b2-48a7-88dd-2fa702642454.png)

[ImageSampleApp.zip](https://github.com/unoplatform/uno/files/10660649/ImageSampleApp.zip)

### How to reproduce it (as minimally and precisely as possible)

Sample (see attached zip file) was created with the 4.7.37 version of the unoapp project template

### Works on UWP/WinUI

None

**Comment by pictos** [comment]
Just adding that macCatalyst has the same issue.

**Comment by jeromelaban** [comment]
Can you try using `TargetPath` instead of `Link` (it's generally preferred) to see if it helps?

**Comment by pictos** [comment]
Brand new repro. Enjoy while is fresh

[NewTemplate.zip](https://github.com/unoplatform/uno/files/10935250/NewTemplate.zip)
