### ISSUE TITLE
Update `Uno.UI.Adapter.Microsoft.Extensions.Logging` references in templates

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11222]
Many csproj in templates includes:

https://github.com/unoplatform/uno/blob/4092e2f08d6cbf385631a5a89c68f7036e7d4fcf/src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF/UnoQuickStart.Skia.WPF.csproj#L12

There is no 3.0.5 in nuget.org and templates are producing warning [NU1603](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1603) because of this.

**Comment by jeromelaban** [comment]
These lines are automatically updated during CI, so you're probably getting this on a local build of the templates. We could update the versions for all packages to be close to a recent version, but they'll continuously be outdated.
