### ISSUE TITLE
An invalid color is returned as a red color

### ISSUE THREAD

**Issue by spouliot** [unoplatform/uno#11229]
### Current behavior

An invalid color, e.g. something that can't be parsed, is returned as a red color for `Colors.FromArgb`

https://github.com/unoplatform/uno/blob/4092e2f08d6cbf385631a5a89c68f7036e7d4fcf/src/Uno.UWP/UI/Colors.cs#L105

### Expected behavior

Ref: https://github.com/unoplatform/uno/pull/11110#pullrequestreview-1285604621

In general invalid values throws an exception.

OTOH from previous experience (silverlight/moonlight) I know that it's often easier to debug such problem visually as the exception is not always easy to map back to the invalid value.

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
@jeromelaban thoughts? should we return "Red" or throw?

If throw, should this be done in breaking changes branch or okay to go in master?

**Comment by jeromelaban** [comment]
What does the WinUI API do in such case? I put Red originally probably because it was easier to troubleshoot, but I agree that the exception should be there, though likely better formatted :)

**Comment by Youssef1313** [comment]
Windows doesn't have such API. I'll see what the user-visible effect is (e.g, XAML parsing)

**Comment by jeromelaban** [comment]
Right, forgot about that. So then it may be a `XamlBindingHelper` behavior that we need to mimic, what happens then when invalid string is passed?
