### ISSUE TITLE
Outdated new page instructions for Frame Navigation Tutorial

### ISSUE THREAD

**Issue by elibroftw** [unoplatform/uno#11236]
## On which page?

https://github.com/unoplatform/uno/blob/4092e2f08d6cbf385631a5a89c68f7036e7d4fcf/doc/articles/guides/native-frame-nav-tutorial.md

## What's wrong?

"Blank Page" does not exist in "Add new item" popup in Visual Studio.

![image](https://user-images.githubusercontent.com/21298211/217375969-ebe3c3c7-4058-4d77-8d2b-0d2a12849e70.png)

**Comment by jeromelaban** [comment]
Thanks for the report. Indeed, it should be `Page (Uno Platform Windows App SDK)", it will be fixed by https://github.com/unoplatform/uno/pull/11238.
