### ISSUE TITLE
[Windows][Android] Frame.GoBack() cause previous page's DataContext to change

### ISSUE THREAD

**Issue by Soap-141** [unoplatform/uno#11235]
### Current behavior

On Windows (UWP & WINUI) and Android, when using `Frame.GoBack()` the previous page's `DataContext` is changed and lose it's previous value causing binding errors and the previous to not work.

On iOS, the previous page's `DataContext` is not changed.

![Animation_66](https://user-images.githubusercontent.com/57812285/217350320-cc0b2f81-5f52-4688-8d96-e211edbd03a6.gif)

### Expected behavior

On Windows (UWP & WINUI) and Android, when using `Frame.GoBack()` the previous page's `DataContext` should not change.

### How to reproduce it (as minimally and precisely as possible)

1. Download [SampleFrame.zip](https://github.com/unoplatform/uno/files/10678847/SampleFrame.zip)
2. Start the application on Windows
3. Notice the `DataContext` displayed in a `TextBlock`
4. Click on Test button
5. Click on Back button
6. Notice the `DataContext` displayed is now null

### Works on UWP/WinUI

No

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.8.0-dev.225

### Affected platforms

Android, Windows

### IDE

Visual Studio 2022

### IDE version

17.4.4

**Comment by Youssef1313** [comment]
If Android works the same as Windows (UWP/WinUI), then I don't think there is a bug.

**Comment by Soap-141** [comment]
Well it's working on iOS, it should also be working on Windows and Android.

**Comment by Soap-141** [comment]
Probably not a bug. Since Windows has it. Closingé
