### ISSUE TITLE
[WASM] CurrentUICulture gets reset to default browser's language

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#11257]
### Current behavior

In WASM, setting ```Thread.CurrentThread.CurrentUICulture``` , ```Thread.CurrentThread.CurrentCulture```  or ```ApplicationLanguages.PrimaryLanguageOverride``` to a specific culture keeps the changes only during block of code that this assignment occurs; right after, the culture is set back to the default browsers language.
In this example the culture is set at ``Loaded`` event, then if you click on the ```CheckBox``` the culture has changed
![image](https://user-images.githubusercontent.com/888391/217775627-2ad40680-f586-40e0-979d-e0ccbd9927e1.png)

 

### Expected behavior

Changes in culture should persist in  ```Thread.CurrentThread.CurrentUICulture``` , ```Thread.CurrentThread.CurrentCulture```  or ```ApplicationLanguages.PrimaryLanguageOverride``` 

### How to reproduce it (as minimally and precisely as possible)
run the following solution for both , WASM and UWP.
Notice that after clicking in the check box , the culture is not es-ES as set in the Loaded event
[App10.zip](https://github.com/unoplatform/uno/files/10697019/App10.zip)

**Comment by jeromelaban** [comment]
Thanks for the report. Please prefer attaching the sample instead of pointing to a repository (it is private).

**Comment by darenm** [comment]
@jeromelaban I know you were triaging this issue - is there any update on a resolution (I know you were leaning towards it being a .NET framework bug) or a workaround?

**Comment by jeromelaban** [comment]
We have not made significant progress on this issue. It's related to how internals of the runtime works inside the `ThreadPool` and `SynchronizationContext`, and those pieces are quite low-level for us to change.

We haven't tried yet changing `CultureInfo.DefaultThreadCurrentCulture` at the beginning of the app, and that may help working around the issue.

**Comment by paulovila** [comment]
There is no information on the language to switch at the beginning of the app, because the app needs to load and query the available language of that session.
Do you mead forcing a full reload navigating to the url with the language as a parameter?

**Comment by jeromelaban** [comment]
In all cases, the behavior of `ApplicationLanguages.PrimaryLanguageOverride` is incorrect in Uno, where it immediately (and partially) changes the language and is not persisted, whereas in WinUI it is applied on the next restart of the app.

Still, the idea behing using `CultureInfo.DefaultThreadCurrentCulture` is that it will ensure that all pieces of the runtime use the same base culture. Can you try `CultureInfo.DefaultThreadCurrentCulture` and see if it fixes the reset you observe?

**Comment by ChaseKopp6** [comment]
confirmed issue is still present

**Comment by jeromelaban** [comment]
We could not repro this issue with the latest Uno 5, .NET 8 (bootstrapper 8.0.x) using the sample attached. It is still reproducing wit the uno versions from the sample, but not using latest builds.

@ChaseKopp6 is it still happening in your app?

**Comment by ChaseKopp6** [comment]
> We could not repro this issue with the latest Uno 5, .NET 8 (bootstrapper 8.0.x) using the sample attached. It is still reproducing wit the uno versions from the sample, but not using latest builds.
> 
> @ChaseKopp6 is it still happening in your app?

Hey @jeromelaban this looks to be resolved in our app
