### ISSUE TITLE
Offer docs in Dark Theme

### ISSUE THREAD

**Issue by elibroftw** [unoplatform/uno#11260]
I'm of the opinion that docs look 10x better viewed with the dark theme. One example I can show is https://monerodocs.org/ (I added the dark theme myself).

## Concern?

- [ ] Usage in industry
- [ ] Clarification of capabilities
- [ ] Getting started with Uno
- [ ] Developing with Uno
- [ ] Contributing to the Uno project
- [ ] Publishing your application
- [ ] Support
- [x] Other (please specify):

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

**Comment by jeromelaban** [comment]
Duplicate of https://github.com/unoplatform/uno/issues/8117

Thanks for the report.
