### ISSUE TITLE
x:Bind throws null reference exception if part of a path is null with Mode=OneTime (or omitted)

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#11270]
### Current behavior

Uno throws null reference exception because part of the bind path is null
For example: {x:Bind ViewModel.Message} | Where ViewModel = null

### Expected behavior

No exception

### Workaround

Use Binding, or Mode other than OneTime

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

### IDE

Visual Studio 2022

### Anything else we need to know?

Tested on latest dev builds

**Comment by jeromelaban** [comment]
This is indeed a known issue, though the null references should not be a problem at runtime, and should only show when the debugger is breaking on all exceptions.

**Comment by FrozDark** [comment]
> This is indeed a known issue, though the null references should not be a problem at runtime, and should only show when the debugger is breaking on all exceptions.

Should I close the issue then?

**Comment by jeromelaban** [comment]
Let's keep the issue opened, this is still a problem, and is performance related.

**Comment by FrozDark** [comment]
@jeromelaban it's made me confusing. I thought it was a perfomance related to Skia but it's related to slowing down an app throwing exceptions and logging to the console in the debug
