### ISSUE TITLE
The new templates broke conditional xaml

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11282]
### Current behavior

The new templates use a class library, and when it's compiled for net7.0, we don't know if it's skia or wasm and conditional xaml for those don't work. However, conditional xaml should work on Android/iOS/macOS since they can be determined from `TargetFramework` (I have only tried Wasm and Skia though)

Conditional XAML is supposed to work per the value of `XamarinProjectType` which is set here:

https://github.com/unoplatform/uno/blob/a6eda7c5d1ab8d2b34cfc443fbd54e9432b8cf16/src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props#L71-L72

The XAML file is processed in the classlib which doesn't know `UnoRuntimeIdentifier` (in fact, if the classlib is built for net7.0, the output is cached for both wasm and skia since both are net7.0)

### Expected behavior

Conditional xaml should work the same as before with the shared project.

### Works on UWP/WinUI

None

### Anything else we need to know?

I have tried a little trick but it **didn't work**, though I thought it's worth mentioning.

In `Skia.Gtk.csproj`, reference the classlib as follows:

(Note: The same will be done for all other projects - but I was testing only for Skia to get something working first)

```xml
  <ItemGroup>
    <ProjectReference Include="..\ProjectName\ProjectName.csproj">
      <SetTargetFramework>TargetFrameworks=$(TargetFramework)</SetTargetFramework>
      <SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
      <Properties>XamarinProjectType=$(XamarinProjectType)</Properties>
    </ProjectReference>
  </ItemGroup>
```

Then in the classlib, to avoid a `GetTargetPath` error from MSBuild, I removed all the `TargetFrameworks` properties and replaced it with just `<TargetFramework>net7.0</TargetFramework>`.

**This unfortunately didn't work.**

**Comment by Youssef1313** [comment]
@jeromelaban While the trick I tried didn't fix conditional xaml, could it improve build performance in VS to force not building all TFMs of the classlib when building for a single platform?

**Comment by Youssef1313** [comment]
I started to get something working:

![image](https://user-images.githubusercontent.com/31348972/218301383-f71181f7-23d4-4e77-a7d3-3a529f8da40e.png)

It needs some adjustments though, I'm still looking into this.

**Comment by Youssef1313** [comment]
This was trickier than I thought. [This repo](https://github.com/Youssef1313/testconditional) is what I have done so far.

**Comment by Youssef1313** [comment]
Looking into a different approach.

**Comment by jeromelaban** [comment]
Conditional XAML for Wasm and Skia cannot work in class libraries as skia and wasm are both running behind the same TargetFramework. I have on my list to adjust the documentation for this.

The workaround is to use some sort of dependency injection from the Wasm and Skia heads.

**Comment by Youssef1313** [comment]
@jeromelaban I have an idea that might enable this. I'll try to prepare a PR soon. If it didn't work well, we can update the documentation.

**Comment by jeromelaban** [comment]
I don't think you'll be able to enable it, as the same binary will be present in both wasm and skia heads.

**Comment by Youssef1313** [comment]
@jeromelaban I'll make a "fake" platform identifier so that they are different binaries :)

Not 100% sure if it will work in the end, but it was promising when I was trying yesterday.

**Comment by jeromelaban** [comment]
We pondered that option a while back, but the problem is the different variation of visual studios, which will likely not understand such an msbuild construct :) It does not hurt to try, though.

**Comment by Youssef1313** [comment]
"fake" platform identifiers are now implemented with Uno.Sdk and single project :)

Closing out.
