### ISSUE TITLE
[iOS][Android] A `Xaml.Documents.LineBreak` produces a slight leading offset compared to regularly wrapped Text.

### ISSUE THREAD

**Issue by marwalsch** [unoplatform/uno#11292]
### Current behavior

The following text
```
<TextBlock TextWrapping="WrapWholeWords">
   LineBreak
<LineBreak />
   You can construct URLs and access their parts. For URLs that represent local files, you can also manipulate properties of those files directly.
<LineBreak />
   LineBreak 
</TextBlock>
```
is output like this on Windows & mobile devices respectively.

![Screenshot 2023-02-13 124128](https://user-images.githubusercontent.com/72074423/218450489-995611f7-3790-424d-b50a-4549019ef2ed.png)

![Screenshot 2023-02-13 123729](https://user-images.githubusercontent.com/72074423/218450481-6b1f912e-3b52-484a-ad28-da52cb8ebe65.png)

Note the apparent white-space leading the 2nd and 5th line (each produced by a `LineBreak`).

### Expected behavior

Line beginnings should be succinct.

### How to reproduce it (as minimally and precisely as possible)

See above

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI 4.8.0-dev.299

### Affected platforms

Android, iOS

**Comment by Youssef1313** [comment]
I think this is a XAML parsing issue. I'm going to look deeper tomorrow.
