### ISSUE TITLE
[Gallery][Skia.Gtk]Textbox- The text is not displaying correctly in multiline.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11301]
### Current behavior

![Textbox issue](https://user-images.githubusercontent.com/74563602/218544272-a6cd3a9d-0eaa-45a0-b6e9-ca543cff36e5.png)

### Expected behavior

![Textbox correct](https://user-images.githubusercontent.com/74563602/218544294-6d24ad10-b07c-4343-9c31-2f2b9690f408.png)

### How to reproduce it (as minimally and precisely as possible)

Open Uno Gallery APP
Tap Burger Menu on the left top right.
Tap on 'Textbox',  option from the "UI Component" list.
Observe that the text is not displaying correctly in multiline.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment]
@MartinZikmund Is this something that will be fixed in #10935 ?

**Comment by sakshi173** [comment]
Hi @MartinZikmund, could you please tell me is this bug fixed, I tried to reproduce it but not able to reproduce, please let me know    can I close this bug.

**Comment by MartinZikmund** [comment]
@sakshi173 yes, this is fixed now 👍👍
