### ISSUE TITLE
Add docs for Android/WASM hardware back button handling

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#11316]
## What's wrong?

We are missing docs on how to handle hardware back button, especially on Android and WASM. This should explain `SystemNavigationManager.BackRequested` event and how to use it in context of Uno. It can also note that the `BackRequested` event may get triggered on Windows as well (e.g. by Xbox controller B button or a dedicated back button on mouse)

**Comment by kazo0** [comment]
hey @MartinZikmund how can i help do this

**Comment by Dvij30** [comment]
@MartinZikmund can you please elaborate me about this issue I would like to get start with UNO platform and like to contribute in any manner

**Comment by MINEGHOST007** [comment]
@MartinZikmund  can you please elaborate me about this issue I would like to get start with UNO platform and like to contribute in any manner

**Comment by kazo0** [comment]
@MINEGHOST007 it seems that this has already been added since the issue was created: https://platform.uno/docs/articles/features/hardware-back-button.html

@agneszitte we should probably close this
