### ISSUE TITLE
Remove `PanelExtensions.cs`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#11315]
### Current behavior

Breaking change, but I don't see how this could be useful (apart from potentially causing trouble :-D )

```c#
namespace Windows.UI.Xaml.Controls
{
	public static class PanelExtensions
	{
		public static FrameworkElement Background(this FrameworkElement panel, GenericColor color)
		{
			panel.Background = new SolidColorBrush(color);
			return panel;
		}
	}
}
```

### Works on UWP/WinUI

None

**Comment by MartinZikmund** [comment]
CC @jeromelaban @Youssef1313

**Comment by jeromelaban** [comment]
This is from a very long not used piece of code :) We can remove for sure.
