### ISSUE TITLE
Slider doesn't drag around when not clicking on the thumb

### ISSUE THREAD

**Issue by Rytisgit** [unoplatform/uno#11320]
### Current behavior

The slider doesn't stick to the mouse when not clicking on the thumb of the slider. Example in wasm playground:

![wasmincorrectslider](https://user-images.githubusercontent.com/36188103/218882147-67e78b06-20e5-4110-ab58-9183367cc050.gif)

https://playground.platform.uno/#slider

### Expected behavior

The slider thumb sticks to the mouse while it is being held no matter where the slider is clicked on, like it does in a winui project:
![winuicorrectslider](https://user-images.githubusercontent.com/36188103/218882406-900a5ca2-ae9d-4b6c-95fd-006102fb9a7c.gif)

```
<Page
    x:Class="willitevenwork.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:willitevenwork"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"    
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <Grid>
            <Slider 
                    Margin="5"
                    x:Name="Seekbar" 
                    Minimum="0" 
                    Maximum="100" 
                    />
            <TextBlock Text="Hello, world!" x:Name="mytext"  Margin="20" FontSize="30" />
        </Grid>
    </Grid>
</Page>

```

or when using a normal html slider element: 
![w3correctslider](https://user-images.githubusercontent.com/36188103/218882438-24cdc52b-045d-424f-a359-b3ddc4fdce87.gif)
https://www.w3schools.com/howto/howto_js_rangeslider.asp

### How to reproduce it (as minimally and precisely as possible)

https://playground.platform.uno/#slider

### Workaround

click only on the slider thumb if you want to drag the slider

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

```
    <PackageReference Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.3" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.4.0" />
    <PackageReference Include="Uno.Toolkit.WinUI.Material" Version="2.4.2" />
    <PackageReference Include="Uno.WinUI.WebAssembly" Version="4.6.39" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.6.39" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.5.18" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="7.0.11" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="7.0.11" />
```

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by MartinZikmund** [comment]
Reopened for backport
