### ISSUE TITLE
[Skia] ProgressRing of a RefreshContainer is vertically stretched

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#11323]
### Current behavior

Currenly the refresh visualizer of a RefreshContainer is oval stretched vertically instead of being round
![12412a](https://user-images.githubusercontent.com/6670150/218966000-7ef17697-f600-491f-b72b-322bc512273d.jpg)

### Expected behavior

Round refresh progress ring

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. A simple workaround is to set a Width/Height to the control so that it does not stretch.

**Comment by FrozDark** [comment]
> Thanks for the report. A simple workaround is to set a Width/Height to the control so that it does not stretch.

But how that supposed to be?
RefreshContainer is a container for controls that has PullToRefresh feature available
I'm unlikely to set the control's size cause it would shrink an underlying control as well
It's something that related to RefreshVizualizer style template

**Comment by jeromelaban** [comment]
Ah I see. I was talking about setting the `ProgressRing` control size, not the refresh container and is probably related to https://github.com/unoplatform/uno/blob/a5ebaf0431fb4b7913a9cff7488cbe389086199f/src/Uno.UI/Microsoft/UI/Xaml/Controls/PullToRefresh/ProgressRing/ProgressRingRefreshInfoProviderAdapter.cs#L8-L8

Also, when opening issues, make sure to provide a repro or a significant portion of the repro code.

**Comment by FrozDark** [comment]
Repro
[UnoIssues.zip](https://github.com/unoplatform/uno/files/10746673/UnoIssues.zip)

**Comment by agneszitte-nventive** [comment]
@jeromelaban I think this issue is not related to the RefreshContainer directly but to the ProgressRing itself.
I open an issue with all the details as I noticed it on a few projects and it is impacting all platforms besides Windows.
https://github.com/unoplatform/uno/issues/11637
