### ISSUE TITLE
Support Windows.UI.StartScreen.JumpList

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1135]
## What would you like to be added:

Support for `Windows.UI.StartScreen.JumpList` APIs.

## Why is this needed:

Apps could then add quick actions to the app context menu on all platforms. Would be useful in many cases including Uno Calc :-) .

## For which Platform:

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [x] Windows

**Comment by MartinZikmund** [comment]
I have already started working on this

**Comment by ghuntley** [comment]
Thank-you!

**Comment by MartinZikmund** [comment]
It's in!
