### ISSUE TITLE
[Gallery][Wasm/iOS/Android] Combobox- when changing dark/light theme the label 'Placeholder' are not visible.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11382]
### Current behavior

![CB](https://user-images.githubusercontent.com/74563602/219979452-cbaed882-4bc6-4f33-8200-37a736b975c2.png)
![CB 2 issue](https://user-images.githubusercontent.com/74563602/219979576-0f40e201-efb3-4c66-a21c-bc72b5864238.png)

### Expected behavior

The label should display correctly when changing dark/light theme.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Click on the Light/Dark theme change toggle button.
4. Notice that the app is displaying in the Light/dark theme.
5. Tap "Combobox" from the "Component" list.
6. Observe that the 'Placeholder' is not changing with theme.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS

**Comment by marwalsch** [comment]
Cannot reproduce on iOS.
