### ISSUE TITLE
[macOS] ListView scrolling does not work

### ISSUE THREAD

**Issue by baskren** [unoplatform/uno#11408]
### Current behavior

ListView scrolling does not work in MacOS.  

Perhaps related to : https://github.com/unoplatform/uno/issues/8596 ?

### Expected behavior

ListView scrolling works

### How to reproduce it (as minimally and precisely as possible)

repo for minimal reproduction project: https://github.com/baskren/UnoPlatform.MacOs.ListView.NoScroll

### Workaround

None known at this time

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI: 4.7.37

### Affected platforms

macOS (AppKit)

### IDE

Visual Studio for Mac

### IDE version

 17.4.5 (build 8)

### Relevant plugins

n/a

### Anything else we need to know?

Is there a tutorial on setting up a development environment to build, debug, test Uno Platform code for issues like this (in preparation for a Pull Request)?

**Comment by jeromelaban** [comment]
Mac support coming from the .NET team is not particularly stable as of late, which causes is to delay our efforts on the `net7.0-macos target. Are you able to run with the Catalyst target instead?

**Comment by baskren** [comment]
Yes. Mac Catalyst works great. Thank you for the prompt response.

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
