### ISSUE TITLE
[WASM] TextBlock.Inlines are not formatted correctly: spaces/blanks are removed

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#11418]
### Current behavior

Please see attached repo: spaces/blanks are formatted away.

[Inlines.zip](https://github.com/unoplatform/uno/files/10802198/Inlines.zip)

### Expected behavior

WASM should work as WindowsAppSDK

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by Youssef1313** [comment]
I took a look here. Unless I'm missing something, this is quite tricky to fix. It looks like `System.Xml.XmlReader` skips whitespaces in this case. @jeromelaban Do you think this issue needs WinUI XAML parser like https://github.com/unoplatform/uno/issues/1856

**Comment by DierkDroth** [comment]
@Youssef1313 thanks for looking into.

Cuirous: isn't the `System.Xml.XmlReader` in UNO WASM working same way as with WindowsAppSDK? Meaning shouldn't we then see same problem on WindowsAppSDK as well (... which we don't)?

**Comment by jeromelaban** [comment]
@Youssef1313 yes, it is the same issue.

**Comment by noru0916** [comment]
I am Guru  and I found you on upwork.
I can help you.
So please invite me.

**Comment by jeromelaban** [comment]
## For contributors
Here's a direct link for tracking the issues in canaries: https://playgroundcanary.z19.web.core.windows.net/#6995e92d

**Comment by TopProgrammer77** [comment]
I found the reason. This is not because space is skipped by System.Xml.XmlReader. As you can test in https://playgroundcanary.z19.web.core.windows.net/#6995e92d, space is missed even when the xml:space is not preserve.

Code example is as follows.

when the first element is text (i.e. This is the first line) and xml:space="preserve"
```
<TextBlock>
    <Span xml:space="preserve" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">This is the first line <Bold>This</Bold> <Underline>text</Underline> <Italic>still</Italic> <Run>is</Run> <Bold>missing</Bold> <Hyperlink Name="test">spaces</Hyperlink></Span>
</TextBlock>
```
when the first element is text (i.e. This is the first line) and xml:space="none"
```
<TextBlock>
    <Span xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">This is the first line <Bold>This</Bold>   <Underline>text</Underline> <Italic>still</Italic> <Run>is</Run> <Bold>missing</Bold> <Hyperlink Name="test">spaces</Hyperlink></Span>
</TextBlock>
```
when the first element is not text (i.e. This is the first line) and xml:space="preserve"
```
<TextBlock>
    <Span xml:space="preserve" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Bold>This</Bold>   <Underline>text</Underline> <Italic>still</Italic> <Run>is</Run> <Bold>missing</Bold> <Hyperlink Name="test">spaces</Hyperlink></Span>
</TextBlock>
```
when the first element is not text (i.e. This is the first line) and xml:space="none"
```
<TextBlock>
    <Span  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"><Bold>This</Bold>   <Underline>text</Underline> <Italic>still</Italic> <Run>is</Run> <Bold>missing</Bold> <Hyperlink Name="test">spaces</Hyperlink></Span>
</TextBlock>
```

Overall, the issue is in wrong XamlXmlParse

**Comment by Youssef1313** [comment]
@DierkDroth Were you able to confirm if it's working now?

**Comment by DierkDroth** [comment]
Alright, it's working with latest DEV bits! @Youssef1313 @TopProgrammer77 case closed. Thanks

**Comment by DierkDroth** [comment]
@TopProgrammer77 @Youssef1313  unfortunately inlines with spaces are still not handled correctly. Please see the updated repo below and compare WASM and WindowsAppSDK

[Inlines.zip](https://github.com/unoplatform/uno/files/11844608/Inlines.zip)

**Comment by DierkDroth** [comment]
@TopProgrammer77 @jeromelaban I just ran some tests. Looking good! Thanks a lot
