### ISSUE TITLE
Polygons wont render correctly when using decimals numbers 

### ISSUE THREAD

**Issue by iurycarlos** [unoplatform/uno#11455]
### Current behavior

When using not integer numbers, polygons seams not to work properly:

### Expected behavior

First triangle should be similar to the second.

### How to reproduce it (as minimally and precisely as possible)

https://playground.platform.uno/#52ec031a

### Workaround

Using only integer numbers will work fine.

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
@iurycarlos Can you clarify please? It seems to be working correctly if I understand correctly:

![image](https://user-images.githubusercontent.com/31348972/221362028-16940181-138a-41ef-9d74-71e6eaebfc6d.png)

**Comment by iurycarlos** [comment]
Hi @Youssef1313 !!
So strange, look what i get here:

![image](https://user-images.githubusercontent.com/6876973/221364601-a42448c0-7a2d-40ba-adc0-8e79499ad139.png)
The first triangle doesn't appear because it seams to be out of the available space of the control. Sometimes we get a completely distorted image.

**Comment by Youssef1313** [comment]
@iurycarlos For this case they are both placed in a `Grid` in the same row and column, so they are on top of each other.

**Comment by iurycarlos** [comment]
Oh! In fact! However, i added the second one just to have a comparison.
Try this one:
https://playground.platform.uno/#708e01a7
![image](https://user-images.githubusercontent.com/6876973/221367683-7d34717d-ab1a-403f-87f4-428b9574ba15.png)

**Comment by Youssef1313** [comment]
![image](https://user-images.githubusercontent.com/31348972/221368007-6e7b9e0f-d592-4fa7-adef-c908fd3b509d.png)

Works for me. Not sure why it doesn't for you :(

**Comment by Youssef1313** [comment]
What browsers are you running on?

**Comment by iurycarlos** [comment]
Brave, Chrome and Edge. 

Also, in Figma Plugin, QA Version we had the same issue, that's why i had to format numbers to integer to allow previewing correctly.

**Comment by iurycarlos** [comment]
Good point @Youssef1313 ! it is about culture ...
As you asked in the chat, this is the html...

<svg id="159650" XamlType="Windows.UI.Xaml.Shapes.Polygon" XamlHandle="159650" class="uno-polygon uno-arbitraryshapebase uno-shape uno-frameworkelement uno-uielement" tabindex="-1" style="position: absolute; top: 0px; left: 0px; width: 527px; height: 786px; clip: rect(0px, 527px, 786px, 0px);"><polygon id="159634" XamlType="Windows.UI.Xaml.Wasm.SvgElement" XamlHandle="159634" tabindex="-1" class="uno-svgelement uno-uielement" points="1125,0 1507,1365 20993,1365 " style="fill: rgb(0, 0, 255); pointer-events: auto; transform: matrix(1, 0, 0, 1, 0, 0);"></polygon></svg>

The points became:
points="1125,0 1507,1365 20993,1365 "
