### ISSUE TITLE
Android release/publish totally broken

### ISSUE THREAD

**Issue by michalss** [unoplatform/uno#11457]
### Current behavior

For last week im trying to solve some issues with android release run. Issue is in debug mode everything works perfectly but in release/publish application crashing. There is not way to make an android publish application witch would not crash. I spend whole week on this, without success. Application crashing on certain points. No error, totally ignoring try catch, nothing just crash. I actually spend sometime with uno , like it, but bug took me more time then actual development. Issue can be seen only with release/publish, not in debug.. So there is not any way to publish working application to android right now.. Also did try other uno.ui version dev version, again same result..
repo: https://github.com/michalss/UnoTst.git

### Expected behavior

To be working..

### How to reproduce it (as minimally and precisely as possible)

Click on any MenuItem, or app wont even start..

### Workaround

no any possible..

### Works on UWP/WinUI

did not try

### NuGet package version(s)

    <PackageReference Include="Uno.WinUI" Version="4.8.0-dev.403" />
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.8.0-dev.403" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.8.0-dev.403" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Uno.WinUI.Lottie" Version="4.8.0-dev.403" />

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

lastest 17.5.0

**Comment by jeromelaban** [comment]
Thanks for the report. Are you able to provide any application or device logs?
