### ISSUE TITLE
Change `ShouldWriteErrorOnInvalidXaml` default to true or remove completely

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11476]
Currently, `ShouldWriteErrorOnInvalidXaml` defaults to false.

We should do one the following:

- Remove the property completely and let "true" be the only possible behavior.
- Keep the property but change its default value to "true".

Setting it to `false` can hide hard-to-diagnose issues.

This issue is most likely to be addressed in feature/breaking-changes for Uno 5

@jeromelaban Thoughts? which of the two options do you prefer?

**Comment by jeromelaban** [comment]
We could set it to true by default in 5, yes and it should be set to true inside of Uno as well, though there may be many properties that do not exist in Microsoft imported styles. @MartinZikmund may be aware of this.

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/pull/11583
