### ISSUE TITLE
`CornerRadiusFilterConverter` is missing `Scale` property in UWP builds

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11477]
### Current behavior

We have `CornerRadiusFilterConverter` in both UWP and WinUI builds.

But it's auto-generated by sync generator ONLY in WinUI builds, thus, we are missing a `Scale` property in UWP builds but the property exists as not-implemented in the generated stub for WinUI converted tree

### Works on UWP/WinUI

None

**Comment by MartinZikmund** [comment]
Will look into this one
