### ISSUE TITLE
Add support for `Compass`

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#11496]
### Current behavior

Not implemented

### Expected behavior

Implemented

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Android, iOS, Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

### IDE

Visual Studio 2022

**Comment by MartinZikmund** [comment]
The implementation can be quite similar to MAUI - https://github.com/dotnet/maui/tree/04bfb275d9401a631d3e9a1e20665e68e99b79c4/src/Essentials/src/Compass
