### ISSUE TITLE
Avoid LOH string allocations in XamlCodeGenerator

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11515]
### Current behavior

![image](https://user-images.githubusercontent.com/31348972/221691032-984d05c3-b020-42b9-8185-7c7aadbdc69a.png)

### Works on UWP/WinUI

None

**Comment by workgroupengineering** [comment]
Please, reconsider using of [Cysharp/ZString](https://github.com/Cysharp/ZString),  how suggest in  https://github.com/unoplatform/Uno.Roslyn/issues/17

**Comment by Youssef1313** [comment]
It's unclear to me whether `ZString` can indeed be an improvement, but I don't think we will want to add a dependency to the generator unless it is **very very** necessary.

**Comment by workgroupengineering** [comment]
> It's unclear to me whether `ZString` can indeed be an improvement, but I don't think we will want to add a dependency to the generator unless it is **very very** necessary.

To replace StringBuilder. `ZString`  allocated less memory. For dependency  you can merge Zstring with main assembly of generator with il-repack.

**Comment by Youssef1313** [comment]
I don't think `StringBuilder` allocations is a bottleneck here anyway. There can potentially be other areas that are more interesting to optimize.
