### ISSUE TITLE
[NPE] Expanding tree nodes twice does not show content

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#11514]
### Current behavior

![image](https://user-images.githubusercontent.com/5839577/221679449-9a5612ee-f86e-40bf-9905-900805ef96dd.png)

### Expected behavior

Items should appear

### Works on UWP/WinUI

None

### NuGet package version(s)

4.8-dev

### Affected platforms

WebAssembly

**Comment by sakshi173** [comment]
@jeromelaban, I verified but this issue is still present with current NPE Canary build. please let me know your views.

**Comment by sakshi173** [comment]
Verified that issue is fixed.

**Comment by sakshi173** [comment]
This issue is happening again due to that opening it.

![Image](https://user-images.githubusercontent.com/74563602/228406571-aa8ba122-0aa1-4951-bb8c-943b87af10cd.png)

**Comment by jeromelaban** [comment]
The behavior is actually different from the original issue, and is closer to https://github.com/unoplatform/uno/issues/11821. Let's keep track there.
