### ISSUE TITLE
Outdated documentation for Uno.Material

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11546]
## On which page?

https://github.com/unoplatform/uno/blob/master/doc/articles/guides/uno-material-walkthrough.md

## What's wrong?

Page mentions:

```xml
        <MaterialColors xmlns="using:Uno.Material" />
        <MaterialResources xmlns="using:Uno.Material" />
```

But this produces:

![image](https://user-images.githubusercontent.com/31348972/222405278-afe19ab9-3ef6-4e15-a274-4ec5efe5b382.png)

**Comment by kazo0** [comment]
Yeah we should be removing these and directing people to the new docs
