### ISSUE TITLE
VSIX template is creating Android/iOS mobile folders when these were not selected in the project wizard

### ISSUE THREAD

**Issue by rkeithhill** [unoplatform/uno#11567]
### Current behavior

This is what I select when running the new project wizard. I want to build a cross-platform **DESKTOP** application for Windows, Linux, and macOS.  I don't want any mobile targets.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/5177512/222980572-8684ce93-9876-493c-bb1e-0ae9b9962344.png">

Yet, the resulting project has a `<projname>.Mobile` folder with Android and iOS.  And also `macOS`?  Why is my desktop macOS folder in the `Mobile` folder?

<img width="164" alt="image" src="https://user-images.githubusercontent.com/5177512/222980735-41c2ce78-6867-47f6-846a-0ebca96af770.png">

### Expected behavior

Since I did not select Android and iOS, I expect them not to show up at all.  Also, I wouldn't expect the file for my macOS desktop app to be in the `Mobile` folder.  That said, I'm a total Uno n00b.  I don't think I want to use `macOS (Catalyst)` since I think that is more mobile app oriented.  So does that leave Gtk as the only way to create a desktop macOS app?  I thought there'd be a way to use NSView?

### How to reproduce it (as minimally and precisely as possible)

1. Install the Uno Project Templates vsix into VS 2022 (17.5.1)
2. Create a new project of type `UnoApp`.
3. Select the following options:
   
![image](https://user-images.githubusercontent.com/5177512/222982065-295c03eb-84d9-40dd-8a07-2851191cad26.png)

4. Click `Create` to finish the new project wizard.
5. Observe that under your `<appname>.Mobile` folder there are Android and iOS folders.
   
![image](https://user-images.githubusercontent.com/5177512/222982175-6a5f4d14-6214-40b9-9cd5-77ed33b02ef9.png)

### Workaround

I suppose the workaround is to also not pick `macOS (Catalyst)` but then the Uno new project wizard is confusing because that option appears under the `Desktop` options.

### Works on UWP/WinUI

None

### NuGet package version(s)
```powershell
PS> Get-ChildItem -file -recurse *.*proj | 
        Select-String -raw '<PackageReference\s+Include=' | 
        Foreach-Object {$_.TrimStart("<PackageReference Include=").TrimEnd("/>").Replace('"','').Replace("Version=","@ ")} | 
        Sort-Object -Unique

Microsoft.Extensions.Logging @ 6.0.0
Microsoft.Extensions.Logging.Console @ 5.0.0
Microsoft.Windows.Compatibility @ 6.0.0
Microsoft.Windows.SDK.BuildTools @ 10.0.22621.755
Microsoft.WindowsAppSDK @ 1.1.3
Microsoft.WindowsAppSDK @ 1.2.221109.1
SkiaSharp.Skottie @ 2.88.3
SkiaSharp.Views.Uno.WinUI @ 2.88.3
Uno.Core.Extensions.Logging.Singleton @ 4.0.1
Uno.Extensions.Logging.OSLog @ 1.4.0
Uno.Extensions.Logging.WebAssembly.Console @ 1.4.0
Uno.UI.Adapter.Microsoft.Extensions.Logging @ 4.7.37
Uno.UniversalImageLoader @ 1.9.36
Uno.Wasm.Bootstrap @ 7.0.11
Uno.Wasm.Bootstrap.DevServer @ 7.0.11
Uno.WinUI @ 4.7.37
Uno.WinUI.Lottie @ 4.7.37
Uno.WinUI.RemoteControl @ 4.7.37 Condition='$(Configuration)'=='Debug'
Uno.WinUI.Skia.Gtk @ 4.7.37
Uno.WinUI.WebAssembly @ 4.7.37
Xamarin.Google.Android.Material @ 1.4.0.4
```
### Affected platforms

Solution Templates

### IDE

Visual Studio 2022

### IDE version

17.5.1

### Relevant plugins

None

### Anything else we need to know?

I am new to Uno so the array of project type choices, particularly for macOS (and Linux) is a bit confusing. Also, I'm a bit confused about the difference between the `UnoApp` and `UnoApp.Xamarin` templates.

**Comment by jeromelaban** [comment]
Thanks for the report. For the android/ios folders, you can remove those by hand, it's indeed a problem of the template. As for mac Catalyst, it's expected that it is in the mobile project, there's nothing to change there. 

Note that you can make apps running on macOS with both Catalyst and Gtk heads.
