### ISSUE TITLE
Right after project creation using UnoApp VSIX template, Page, Grid, TextBlock types not found. Wrong Project set for MainPage.Xaml file.

### ISSUE THREAD

**Issue by rkeithhill** [unoplatform/uno#11571]
### Current behavior

I created a new `UnoApp` project in VS 2022 using the Uno Project Template VSIX.  Right after creation, I open up the `MainPage.xaml` file and the Error List shows a number of "type was not found" errors:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/5177512/222999530-6a980bc3-1080-4801-bc33-5aa5779e5772.png">

With these errors, Intellisense in the XAML is useless, making it very hard to author new XAML.

### Expected behavior

I would not expect to see these errors immediately after project creation using one of the Uno-provided project templates.

### How to reproduce it (as minimally and precisely as possible)

1. Install the Uno Project Templates vsix into VS 2022 (17.5.1)
2. Create a new project of type UnoApp.
3. Select the following options:

![image](https://user-images.githubusercontent.com/5177512/222999494-ff59916c-c3db-42fd-9f2f-871629dc7822.png)

### Workaround

It took me a bit to figure this out but once I changed the XAML Project dropdown to `net7.0-windows10.0.18462`, the errors go away and more importantly, IntelliSense is usable again.

<img width="583" alt="image" src="https://user-images.githubusercontent.com/5177512/222999794-3b9f6dec-1733-43ab-a93c-2ee9f9b8dc4d.png">

Why isn't this the default project for this XAML file?

### Works on UWP/WinUI

None

### Environment

Other

### NuGet package version(s)

```powershell
PS>Get-ChildItem -file -recurse *.*proj |
>         Select-String -raw '<PackageReference\s+Include=' |
>         Foreach-Object {$_.TrimStart("<PackageReference Include=").TrimEnd("/>").Replace('"','').Replace("Version=","@ ")} |
>         Sort-Object -Unique

Microsoft.Extensions.Logging.Console @ 5.0.0
Microsoft.Windows.SDK.BuildTools @ 10.0.22621.755
Microsoft.WindowsAppSDK @ 1.1.3
Microsoft.WindowsAppSDK @ 1.2.221109.1
SkiaSharp.Skottie @ 2.88.3
SkiaSharp.Views.Uno.WinUI @ 2.88.3
Uno.Core.Extensions.Logging.Singleton @ 4.0.1
Uno.UI.Adapter.Microsoft.Extensions.Logging @ 4.7.37
Uno.WinUI @ 4.7.37
Uno.WinUI.Lottie @ 4.7.37
Uno.WinUI.RemoteControl @ 4.7.37 Condition='$(Configuration)'=='Debug'
Uno.WinUI.Skia.Gtk @ 4.7.37
```

### Affected platforms

Windows, Solution Templates

### IDE

Visual Studio 2022

### IDE version

17.5.1

### Relevant plugins

None

**Comment by rkeithhill** [comment]
Here's the version (just installed it on Saturday)
<img width="460" alt="image" src="https://user-images.githubusercontent.com/5177512/223170651-1f65d73d-6d9f-4d19-905d-bc6e6a0acb76.png">

**Comment by jeromelaban** [comment]
This is an intellisense issue. Make sure to read this part of our documentation: https://platform.uno/docs/articles/get-started-wizard.html?tabs=windows#the-xaml-editor-shows-the-type-page-does-not-support-direct-content-message.
