### ISSUE TITLE
Navigation iOS Exception

### ISSUE THREAD

**Issue by Schinwinkwinsky** [unoplatform/uno#1158]
When I try to navigate between pages using...

`...
this.Frame.Navigate(typeof(NewPage));
...`

I get the following exception only on iOS.

![Anotação 2019-06-27 200505](https://user-images.githubusercontent.com/13337108/60306556-fdecde00-9916-11e9-9287-3a2c11c8259f.png)

**Comment by jeromelaban** [comment]
Thank you for your report!

To investigate further, could you provide a sample of the code you're running ?

**Comment by ghuntley** [comment]
@Schinwinkwinsky 👋 can you please provide a test case?

**Comment by Schinwinkwinsky** [comment]
i'm sorry. I don't know what happened, but I can't reproduce the error. I don't have the original project because it was just a test and I've already deleted it.

**Comment by ghuntley** [comment]
nps. I'm going to close this off as we won't be able to reproduce it. Thank-you for coming back and updating us.
