### ISSUE TITLE
[WASM] `RefreshContainer` items disappearing on scroll 

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#11581]
## Current behavior
This is how the RefreshContainer currently behaves in Gallery:

https://user-images.githubusercontent.com/78549750/222843471-978a0b80-1f36-40c2-8fbd-91997f0a9630.mp4

## Expected behavior
This is how it behaves in a new Uno project.

https://user-images.githubusercontent.com/78549750/222844018-389860c6-2d28-4cd8-8969-ce91998e0a73.mp4

## How to reproduce it (as minimally and precisely as possible)

Go to RefreshContainer sample page in Gallery and start scrolling from bottom to top.

## Environment

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by ramezgerges** [comment]
Tested on firefox and chrome, cannot reproduce. @morning4coffe-dev feel free to close if fixed.
