### ISSUE TITLE
[UI] Combox problem outside the sample app context

### ISSUE THREAD

**Issue by DiegoBillares** [unoplatform/uno#11590]
## Current behavior

Sample app has the expected aligment about it's opened the pup up combo box, although into the app conext this same combo box implementation doesn't have a correct aligment when it's opened the pop up. 

## Expected behavior

The implementation outside sample app could have correct aligment.

## How to reproduce it (as minimally and precisely as possible)

- Go to the app
- Go to the combo box page
- Open combo box
- Select different options into combo box and open it

## Environment

Nuget Package: UI.Xaml.Controls

Package Version(s): -

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [x] 2022 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Observations:

I copied the same implementation from the app to sample app for this. The principal difference is the .Net version, on the sample app is 6 and the app has 5, also I am not totally sure if there is a extension package that it's affecting this.

[EmptySampleApp.zip](https://github.com/unoplatform/uno.extensions/files/9766388/EmptySampleApp.zip)

**Comment by nickrandolph** [comment]
@MartinZikmund is this something you'd be able to assist verify the status on?

**Comment by MartinZikmund** [comment]
Which version of Uno is the problematic app using?

**Comment by jeromelaban** [comment]
@DiegoBillares could you provide a screenshot of the issue you're seeing? Also you're mentioning `.NET 5` in your own app, does it mean you're using a Xamarin based app?

**Comment by DiegoBillares** [comment]
Hello!! @jeromelaban yes, it's a xamarin based app. I will try to attach a screenshot as soon as possible.

**Comment by MartinZikmund** [comment]
@DiegoBillares Is this problem still happening?

**Comment by aliciats** [comment]
@Marc-Antoine-Soucy @Soap-141

**Comment by Soap-141** [comment]
Not sure I understand what the issue is, I could take time to download the sample and see if something is wrong.
