### ISSUE TITLE
Setting DataContext of DataTemplate's root element causes next elements to loose context until recycled

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#11600]
### Current behavior

All next element after the first one is looses bind context. Scrolling elements will restore context (I think when recycled)

![agaga](https://user-images.githubusercontent.com/6670150/223565513-29467b47-d52c-412c-9c41-3befb6edea63.jpg)

### Expected behavior

No loosing context

### How to reproduce it (as minimally and precisely as possible)

Repro
[ContextInItemsRepeaterIssue.zip](https://github.com/unoplatform/uno/files/10914322/ContextInItemsRepeaterIssue.zip)

### Workaround

Not to use DataContext

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

### IDE

Visual Studio 2022

**Comment by ramezgerges** [comment]
I remember debugging this before and the issue being present, but after some testing now, the issue does reproduce in the provided sample, but is fixed using the latest stable uno version. Pumping up the versions does not reproduce.
