### ISSUE TITLE
GridView selection icon not displayed correctly(Android)

### ISSUE THREAD

**Issue by DmitryBorodiy** [unoplatform/uno#11603]
### Current behavior

![Screenshot_20230308_002902_Aurora](https://user-images.githubusercontent.com/57910623/223570814-3f9be650-80cb-4b75-9180-3035658db54b.jpg)

The selection symbol is not displayed correctly.

### Expected behavior

The symbol of the selected item should display correctly.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.7.44

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

Latest

**Comment by jeromelaban** [comment]
Looks like and incorrect glyph is used somehow. You can define your own GridViewItem template as a workaround.
