### ISSUE TITLE
[macOS/Skia.Gtk] [menu] Multiple items remain in focused state when scrolling in the left menu

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/uno#11610]
## Current behavior
Multiple items remain in selected state when scrolling in the left menu
![Screen Shot 2021-02-04 at 5 19 49 PM](https://user-images.githubusercontent.com/38770890/107043032-6f963a80-6790-11eb-801e-c73acfd281ef.png)

## Expected behavior
A focused state should be displayed only when cursor focus on the item

## How to reproduce it (as minimally and precisely as possible)
1. From the left menu scroll to the bottom on the list
2. Scroll to the top
3. Notice some elements remain in a focused state

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by brswan** [comment]
@Xiaoy312 Created issue from the link you provided in the comment.

Issue: https://github.com/unoplatform/Uno.Gallery/issues/658

**Comment by MartinZikmund** [comment]
@sakshi173 can you check this in the latest canaries after the fix by @dr1rrb in #11966?

**Comment by dr1rrb** [comment]
FYI: I've tested the gallery for another bug, and I was no longer able to repro

**Comment by jeromelaban** [comment]
@sakshi173 could you take a look again ? Thanks!
