### ISSUE TITLE
[WASM] Launcher API does not correctly report app launch cancelation 

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#11623]
### Current behavior

The Launcher API currently reports true even if the request was cancelled by the user using the browsers prompt.

### Expected behavior

The Launcher should return false as the app was not launched.

### How to reproduce it (as minimally and precisely as possible)

```
var result = await Launcher.LaunchUriAsync(new Uri("ms-settings:sound"));

if(!result)
{
	//Show some error message
}
```
Then cancel the request for the launch. 
<img src="https://user-images.githubusercontent.com/78549750/223865725-df138fbb-d2a7-49ef-992f-43e523fdcbbf.png" width="450">

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by MartinZikmund** [comment]
@morning4coffe-dev Would you be interested in validating if there is a way to check if the launch was successful and if not, to document it please?
