### ISSUE TITLE
[Skia] ScrollViewer is nearly impossible to scroll by mouse and impossible to scroll with scrollbar buttons or line

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#11627]
### Current behavior

Currently SrollViewer behaves very awful on Skia targets. Only scrolling with thumb is relevant

### Expected behavior

Work like a charm

### How to reproduce it (as minimally and precisely as possible)

Repro
[SkiaScrollViewerIssue.zip](https://github.com/unoplatform/uno/files/10932029/SkiaScrollViewerIssue.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows)

**Comment by ramezgerges** [comment]
I've investigated this before and reproduced the issue on gtk and wpf. The issue with scrolling by mouse wheel is now fixed in #12559. Scrolling using the buttons still doesn't work and I will be looking into it.
