### ISSUE TITLE
Align Pointers behavior

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#1162]
## What would you like to be added:
Align Pointer events and Gesture (i.e. `Tapped` / `DoubleTapped`) events with UWP

## Why is this needed:
* Events are not raised in the same order
* Pointer events are not marked as handled on `ButtonBase` like UWP
* On iOS some events are mutted due to GestureRecognizers
* Capturing pointer does not behave the same way as UWP and prevent the `Slider` to work properly in a `ScrollViewer`

## For which Platform:
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

#864 
#146 
#843

**Comment by dr1rrb** [comment]
https://github.com/unoplatform/uno/pull/1014

**Comment by davidjohnoliver** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WASM ListView pointer intercept. https://github.com/unoplatform/uno/issues/843](https://trello.com/c/IeQP6RCO/34-wasm-listview-pointer-intercept-https-githubcom-unoplatform-uno-issues-843)
