### ISSUE TITLE
[Skia GTK] Inconsistent themes in the Control Templates

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#11628]
### Current behavior

Using dark theme on my machine the GTK target uses theme like it's light theme in the Control Templates

![agaga](https://user-images.githubusercontent.com/6670150/224037535-fdb363a2-9d53-4beb-beb7-da0488738a6e.jpg)

### Expected behavior

Use a correct theme

### How to reproduce it (as minimally and precisely as possible)

Repro
[GTKThemeIssue.zip](https://github.com/unoplatform/uno/files/10932076/GTKThemeIssue.zip)

### Workaround

Use light theme machine :D

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by MartinZikmund** [comment]
@FrozDark does this issue still apply for the new desktop target of Uno Platform?
