### ISSUE TITLE
[ProgressRing] Vertically stretching on all platforms besides Windows

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#11637]
### Current behavior

The ProgressRing is vertically stretching on all platforms besides Windows

- **iOS for example but it is the same for the others platforms (WASM, Skia.GTK, Android,...):**
![image](https://user-images.githubusercontent.com/16295702/224404363-eebe2d06-ca2a-4121-bb4e-7d531ac08bbb.png)

- **Windows:**
![image](https://user-images.githubusercontent.com/16295702/224405080-bd55ee71-f596-4c0b-8bd0-4f3f9df7b65b.png)

### Expected behavior

The ProgressRing behavior should match Windows

### How to reproduce it (as minimally and precisely as possible)

```
<Page x:Class="ProgressRingIssue.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:ProgressRingIssue"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      mc:Ignorable="d"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

	<Grid>
		<ProgressRing IsActive="True" />
	</Grid>

</Page>
```

### Workaround

**Use a fixed Height**

```
<Page x:Class="ProgressRingIssue.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:ProgressRingIssue"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      mc:Ignorable="d"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

	<Grid>
		<ProgressRing Height="32" 
                              IsActive="True" />
	</Grid>
</Page>
```

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

**Uno.UI: 4.9.0-dev.6**

### Affected platforms

WebAssembly, Android, iOS, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

### IDE

Visual Studio 2022

### IDE version

Version 17.5.1

**Comment by Youssef1313** [comment]
@agneszitte-nventive I can't reproduce on Wasm playground https://playground.platform.uno/#05a660c7
