### ISSUE TITLE
Central Package Management does not work with Mobile project

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#11641]
### Current behavior

When Central package management is used, the mobile project does not compile due to:

```
Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items:
 Microsoft.Windows.SDK.BuildTools;Uno.Core.Extensions.Logging.Singleton;Microsoft.WindowsAppSDK;Uno.WinUI;Microsoft.Extensions.Logging.Console.
```

Even though the `PackageReferences` definitely don't have a `Version` attribute.

### Expected behavior

Should compile

### How to reproduce it (as minimally and precisely as possible)

- Clone https://github.com/MartinZikmund/uno-11641-repro
- Try to build Mobile project

### Workaround

Not using Central Package Management

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
@MartinZikmund

https://github.com/MartinZikmund/uno-11641-repro/blob/91d4c789825d8a0c1b9f6761c3af40018981cfff/AppTest/AppTest.Windows/AppTest.Windows.csproj#L20-L24

**Comment by MartinZikmund** [comment]
@Youssef1313 That was an oversight in the repro, but I now removed the versions from the Windows csproj, but it still fails on the Mobile project. All the others compile without issues, just the Mobile one complains 🤔

**Comment by Youssef1313** [comment]
To me, looks like a NuGet bug. I opened https://github.com/NuGet/Home/issues/12480

**Comment by MartinZikmund** [comment]
@jeromelaban for reference on the reason for this change -  https://github.com/NuGet/Home/issues/12480
