### ISSUE TITLE
Flyout resets to null everything set with x:Bind and DataContext of an element in a DataTemplate is shown at

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#11647]
### Current behavior

In continuation of the comment here https://github.com/unoplatform/uno/issues/11602#issuecomment-1459516035 
I debugged of what's going on there and found out that flyout changes the size (making a measurements?) of an element it shown at for the first time when using FontIcon on button

**Worth:**
Looking at the screenshots you can notice that DataContext is null after flyout is shown

Before show
![agaga](https://user-images.githubusercontent.com/6670150/224484685-57907c22-2ba6-4898-a0f1-df52e8de10e1.jpg)

After
![12412a](https://user-images.githubusercontent.com/6670150/224484692-57992525-4401-4949-82ff-69d10cca4605.jpg)

### Expected behavior

No size changed 

### How to reproduce it (as minimally and precisely as possible)
Repro
[FlyoutFontIconIssue.zip](https://github.com/unoplatform/uno/files/10949340/FlyoutFontIconIssue.zip)

### Workaround

Restore size after show

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

### IDE

Visual Studio 2022

### Anything else we need to know?

No repro. But if it's very required I could try to create it

**Comment by MartinZikmund** [comment]
It would help if you can provide a repro as well. It is either caused by popup placement changes, or data binding

**Comment by FrozDark** [comment]
> It would help if you can provide a repro as well. It is either caused by popup placement changes, or data binding

I figured out that the issue happens using FontIcon and forgot to mention that it's not related to Skia heads only but on all Uno platforms

Repro
[FlyoutFontIconIssue.zip](https://github.com/unoplatform/uno/files/10949340/FlyoutFontIconIssue.zip)

**Comment by FrozDark** [comment]
@MartinZikmund @jeromelaban 
I've set glyph without x:Bind in XAML like this
`<FontIcon FontFamily="{StaticResource MDFontFamily}" Glyph="&#xf1d9;" />`
No issue is present then

It might be related to https://github.com/unoplatform/uno/issues/11602
My conclusion is that everything related to x:Bind and DataContext are set to null on element a flyout is shown at

**Comment by jeromelaban** [comment]
That is indeed the case. This is caused by this line:

https://github.com/unoplatform/uno/blob/e59686fa24665444622f8f40ac4a808dde2cb7f7/src/Uno.UI/UI/Xaml/Controls/Popup/Popup.cs#L154-L159

Which implicitly propagates the DataContext of the popup, which is null. Setting :
```
FrameworkPropertyMetadataOptions.AffectsArrange | FrameworkPropertyMetadataOptions.ValueDoesNotInheritDataContext
```
should prevent the `DataContext` from incorrectly flowing through.
