### ISSUE TITLE
Improve UWPSyncGenerator performance

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11657]
Idea is to split UWPSyncGenerator into two tools.

### Tool 1

This will generate a json file for the API information we want from UWP/WinUI reference. It "hopefully" will be the expensive part, but we will only run it manually when we change the reference version, which happens less frequently.

### Tool 2

It would either be an executable (same as it is currently) or an actual source generator (**only if it has an acceptable performance, otherwise it will remain executable**).

This will take the json as an input and generates the missing APIs.

### Further possible optimization

Instead of generating a single large json file, we could generate multiple json files, and let different projects deal with different json files, which may improve the performance more.

### Ensuring "Tool 1" is run

We will have a comment above the version that says the tool must be run when updating this version. This will likely be enough, but if we wanted to be more solid, we could:

- add a CI step that is only run when the reference project is changed (possibly version update), and validates that json files are up to date.
- add a cron GitHub Actions workflow that generates those json files and open a PR if they are not up to date.

**Comment by Youssef1313** [comment]
@jeromelaban What are your thoughts?

**Comment by jeromelaban** [comment]
Some update here, I've given a try to the generation parallelization, and most of the work happens during the msbuild loading of projects to create Compilation instances. It cannot be parallelized either (there's a single msbuild lock per app domain) so we can't make it go faster this way.

Creating a json file for the reference is not going to help much since we're doing it once, and that we'll be loading all the uno other projects regardless, this is where most of the time is spent.

**Comment by Youssef1313** [comment]
@jeromelaban Maybe an actual source generator gives a better performance? ie, we get rid of loading the projects with MSBuildWorkspace. I mean, all we need is the "Compilation", and we get it for free when using an actual generator.

**Comment by jeromelaban** [comment]
That could be an interesting avenue indeed, but it would not change the time spent in msbuild.

**Comment by jeromelaban** [comment]
Performance has improved significantly by loading the whole solution once.
