### ISSUE TITLE
Hot reload not working for WinAppSDK

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#11651]
### Current behavior

It seems the changes in class library .xaml are not being hot reloaded in case of WinAppSDK.

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
This is generally caused by the top left selector not being on `.Windows` when the app starts. Or is because the `-windows` target framework is not first in the library's list.

**Comment by MartinZikmund** [comment]
Actually, in my case the problem was caused by the fact that the simplified `RowDefinitions` and `ColumnDefinitions` syntax breaks WinAppSDK hot reload when used anywhere on the page 😑 . https://github.com/microsoft/microsoft-ui-xaml/issues/673#issuecomment-1471401806
