### ISSUE TITLE
[Android] `TextBox` does not offer copy/paste popup anymore

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#11665]
### Current behavior

It is no longer possible to paste into Android `TextBox` by long hold on the input. Same for `PasswordBox`.

Seen on Android, but may also be happening elsewhere (needs to be verified).

### Expected behavior

The native system context menu for copy/paste should still appear

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Android

**Comment by jeromelaban** [comment]
Related to https://github.com/unoplatform/nventive-private/issues/453
