### ISSUE TITLE
[Android] Cannot create archive file, because archive process has failed.

### ISSUE THREAD

**Issue by Berrysoft** [unoplatform/uno#1166]
I always failed to archive the Android project.

```
Nuget Package: 
Uno.UI 1.46.0-dev.2031
Uno.SourceGenerationTasks 1.31.0-dev.285/1.32.0-dev.288

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [x] 2019 Preview (version: 16.2 Preview 3)
- [ ] for Mac (version: )
```

**Comment by ghuntley** [comment]
Thanks for the report and the PR to the calculator project!

Specific things I'd like to learn about are what Android API level you are using and if you are testing in a simulator or on device. 

1. Could you please provide a test case that reproduces the issue?
2. Could you please provide [logs from logcat](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows)?

**Comment by Berrysoft** [comment]
I'm using API level 28 and testing in a simulator. It tests fine, but I cannot archive the project to create apk file.

**Comment by Berrysoft** [comment]
[ArchiveTest.zip](https://github.com/unoplatform/uno/files/3350011/ArchiveTest.zip)
It is a minimal test case. I removed other targets and some assets.
How to reproduce:
1. Select configuration to `Release`.
2. Build the project.
3. Right-click on the project in the solution explorer and click `Archive...`. (Following [this](https://devblogs.microsoft.com/xamarin/android-archiving-and-publishing-made-easy/) blog post)
4. It fails.
I'm sure it is because of the Uno library because I have succeeded in archiving a common Xamarin.Android project.

**Comment by jeromelaban** [comment]
This is a Visual Studio feature that has never been particularly stable, and testing your sample does not give any particular error aside that an error has occurred. Are you getting more errors on your side ?

**Comment by Berrysoft** [comment]
@jeromelaban No. No matter how I tried, I only get one piece of error "Cannot create archive file, because archive process has failed.", the same as the title.

**Comment by jeromelaban** [comment]
I see. The reason we have not encountered this issue is that we never use as we're using a CI instead. We're using [this modification](https://github.com/unoplatform/calculator/blob/424c809a1c88599f41032f8993293dab73d5bc37/src/Calculator.Droid/Calculator.Droid.csproj#L203) to generate the package on the build server.

Why do you need to create archives locally ?

**Comment by Berrysoft** [comment]
Well, I usually program for fun, and I only need to distribute the archives to a few users. It is very convenient to build and create archives locally.

**Comment by jeromelaban** [comment]
Got it. While we troubleshoot this, one way to generate the APK is to deploy the release project to a device, then get the APK from the `bin\release` folder.

**Comment by Berrysoft** [comment]
Thanks for your reply! I'll try it.

**Comment by Drwillard** [comment]
For anyone else getting this cryptic error message, I discovered the package signing was set up incorrectly in my project. Unchecking the "Sign the APK file using the following keystore details" under the Android Package Signing tab made this error go away.

**Comment by jeromelaban** [comment]
This issue has not been reported in recent Xamarin.Android versions.
