### ISSUE TITLE
[Gallery][Skia.Gtk]Numberbox-Entered number in each field is displaying in Password/Encrypted format. 

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11675]
### Current behavior

![Numberbox issue](https://user-images.githubusercontent.com/74563602/224877562-dbc02d25-6543-4a2c-93cd-dc9e7948d994.png)

### Expected behavior

![Numberbox correct](https://user-images.githubusercontent.com/74563602/224877593-e72d9039-e3d1-40a7-897d-ca647723eb50.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap on 'Numberbox', option from the "UI Component" list.
4. Type some number in the numberbox.
5. Observe that the entered number is displaying in Password/Encrypted format.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by FrozDark** [comment]
That should be fixed with https://github.com/unoplatform/uno/pull/11646

**Comment by sakshi173** [comment]
Verified this issue is fixed due to that closing it.
