### ISSUE TITLE
[Wasm] Disabled textbox can be edited

### ISSUE THREAD

**Issue by Wouterdek** [unoplatform/uno#1167]
## On which page?
https://playground.platform.uno/#textbox

## What's wrong?
I can edit the second, disabled, textbox by selecting the first one and then pressing tab. I would expect pressing tab to focus the next enabled element. I'm using Firefox 67.0.4 on Windows.

## Any feedback?
I'm not sure whether this is a sample issue or a framework bug.

**Comment by jeromelaban** [comment]
Thank you for the report!

I can confirm this issue happens on uno latest master.

**Comment by ghuntley** [comment]
@Wouterdek we would welcome a contribution that fixes this. Can you send in a pull-request? 👍

**Comment by Wouterdek** [comment]
Well, the issue seems to be that the HTML `disabled` attribute is not applied to the element even though `IsEnabled="False"` was specified in XAML. After a quick inspection it seems to me like [this line](https://github.com/unoplatform/uno/blob/7f4938b91ee3f172573611dcfcbde2cf1209e43c/src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.wasm.cs#L86) might have its values the wrong way around? It should be that `IsEnabled` <=> `!disabled`. There must be another error though, as all `IsEnabled="True"` textboxes do work at the moment, so I suspect the disabled attribute is simply never applied at all. However, I'm not familiar with the framework (literally saw this project first 4 days ago and tried the demo out of curiosity) so I can't really work it out further than that.

**Comment by jeromelaban** [comment]
@Wouterdek thanks for the troubleshooting. Indeed that property is inverted, but it also not applied, most probably caused by some `IsEnabled` inheritance issue.

**Comment by davidjohnoliver** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WASM Incorrectly disabled TextBox https://github.com/unoplatform/uno/issues/1167](https://trello.com/c/isRXnzmT/35-wasm-incorrectly-disabled-textbox-https-githubcom-unoplatform-uno-issues-1167)

**Comment by davidjohnoliver** [comment]
The Uno bug is fixed by #1295, once Uno.UI is updated in Uno.Playground I'll close this issue.

**Comment by carldebilly** [comment]
Has been fixed by PR #1799
