### ISSUE TITLE
Unable to Enabling native control styles globally

### ISSUE THREAD

**Issue by FlytotheMuum** [unoplatform/uno#11677]
## On which page?
https://platform.uno/docs/articles/native-styles.html#
## What's wrong?
When I Use: Uno.UI.FeatureConfiguration.Style.UseUWPDefaultStyles = false;
The Style doesn't change by switching platform.
## Any feedback?

I Use It in App.cs:

```
        public App() {
#if __IOS__ || __ANDROID__
    Uno.UI.FeatureConfiguration.Style.UseUWPDefaultStyles = false;
     //Uno.UI.FeatureConfiguration.Style.ConfigureNativeFrameNavigation(); It's working
#endif
        }

```

## AppHead.xaml
```
<local:App
	x:Class="PWeight_UnoClient.AppHead"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:PWeight_UnoClient">
	
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <!-- Load WinUI resources -->
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />


                <CupertinoColors xmlns="using:Uno.Cupertino"  />
                <CupertinoResources xmlns="using:Uno.Cupertino" />
 				<MaterialColors xmlns="using:Uno.Material" />
 				<MaterialFonts xmlns="using:Uno.Material" />
 				<MaterialResources xmlns="using:Uno.Material" />

                <!-- Load custom application resources -->
                <!-- ... -->

                <ResourceDictionary Source="ms-appx:///PWeight_UnoClient/AppResources.xaml" />
				
                <!-- Include additional resource dictionaries here, or in PWeight_UnoClient/AppResources.xaml -->				
			</ResourceDictionary.MergedDictionaries>
			
			<!-- Include additional resources here, or in PWeight_UnoClient/AppResources.xaml -->
        </ResourceDictionary>
    </Application.Resources>

</local:App>

```

## MainPage.xaml
It's viewd as Cupertino view:
```
<Button 
Content="button"
Style="{StaticResource CupertinoContainedButtonStyle}" />
```

It's always keep the same style (seems Material):
```
<Button 
Content="button"/>
```

**Comment by kazo0** [comment]
Hi @FlytotheMuum, thanks for the report!

In order for the native styles to be used globally by default, you unfortunately cannot include resources in your AppResource.xaml that also contain implicit styles for those controls. Note the last paragraph in the [documentation](https://platform.uno/docs/articles/native-styles.html#enabling-native-control-styles-globally)

> The default Uno app template includes Fluent control styles in the application. If enabling native control styles globally, these Fluent resources **should be removed** from `App.xaml`, by removing `<XamlControlsResources />` from the `Resources.MergedDictionaries` declaration.

The same logic applies for the Cupertino and Material themes, each of those ResourceDictionaries define their own implicit styles for things such as `Button`, `CheckBox`, `TextBox`, etc.

If you want to have certain controls maintain their native styles while still using Uno.Material and/or Uno.Cupertino then you would need to explicitly set the style on your control to the native one.

```xml
<Button Content="button" Style="{StaticResource NativeDefaultButton}"/>
```

You can find the keys for all native default styles in the [Generic.Native.xaml](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Style/Generic/Generic.Native.xaml) file within Uno
