### ISSUE TITLE
[Gallery][iOS]Image- Uno Image is missing for 'SVG Image' option.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11676]
### Current behavior

![Image issue](https://user-images.githubusercontent.com/74563602/224887842-3a58f9c8-ca86-46fc-a5c7-726bda03fad9.png)

### Expected behavior

![Imagge correct](https://user-images.githubusercontent.com/74563602/224887859-4322e50c-1205-4063-b23d-081313a62a39.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap on 'Image', option from the "UI Component" list.
4. Go to SVG Image option.
5. Observe that the Uno Image is missing.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment]
@MartinZikmund do you know?

**Comment by morning4coffe-dev** [comment]
I am gonna have a look into this issue. I might know where the problem is.

**Comment by MartinZikmund** [comment]
Fixed 👍 thanks @morning4coffe-dev

**Comment by sakshi173** [comment]
@MartinZikmund, I verified this issue is fixed for Skia.Gtk platform, but it is still present for iOS, due to that reopening the bug.

**Comment by MartinZikmund** [comment]
@morning4coffe-dev can you check the iOS issue please?

**Comment by morning4coffe-dev** [comment]
I couldn't do that before, but now, yes!

**Comment by sakshi173** [comment]
@agneszitte  and @MartinZikmund,  Now the same Issue is happening for Android too in the latest canary build for 5.0 please look into it

**Comment by morning4coffe-dev** [comment]
@sakshi173 Thanks for pointing this out! This is regression from the WinUI port. This PR https://github.com/unoplatform/Uno.Gallery/pull/1017 should fix it on all platforms.

**Comment by sakshi173** [comment]
@morning4coffe-dev, I retested, still this issue is present. please look into it.

**Comment by morning4coffe-dev** [comment]
I tested this on the latest master and the issue is not happening there, but when I updated all the packages to 5.1 dev the issue is there. I will take a look if anything changed there and investigate from there
