### ISSUE TITLE
[Gallery][Skia.Gtk]Textbox- Entered Text is displaying in Password/Encrypted format.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11674]
### Current behavior

![Textbox issue](https://user-images.githubusercontent.com/74563602/224876596-845a30bc-be49-40b8-b5a1-75c28bba9e22.png)

### Expected behavior

![Textbox correct](https://user-images.githubusercontent.com/74563602/224876767-5e950790-00fc-4d34-9c7d-2dcdf56f70c1.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap on 'Textbox', option from the "UI Component" list.
4. Type some text in the Textbox field.
5. Observe that the Entered Text is displaying in Password/Encrypted format.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/pull/11646

**Comment by sakshi173** [comment]
Verified this issue is fixed due to that closing it.
