### ISSUE TITLE
MedialPlayerElement Fluent style is missing font icons

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#11686]
The MediaTransport control is missing glyphs from the fluent font https://github.com/unoplatform/uno.fonts/commit/736a049aeea5c039d13aa831a850b58682aecbfb:

- Pause:
https://github.com/unoplatform/uno/blob/d582c30861daa461659fd2756dd106f397838e72/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/MediaTransportControls_themeresources.xaml#L229
- SkipBackward
https://github.com/unoplatform/uno/blob/d582c30861daa461659fd2756dd106f397838e72/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/MediaTransportControls_themeresources.xaml#L384
- Previous Track
https://github.com/unoplatform/uno/blob/d582c30861daa461659fd2756dd106f397838e72/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/MediaTransportControls_themeresources.xaml#L393
- Rewind:
https://github.com/unoplatform/uno/blob/d582c30861daa461659fd2756dd106f397838e72/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/MediaTransportControls_themeresources.xaml#L402
- Play
https://github.com/unoplatform/uno/blob/d582c30861daa461659fd2756dd106f397838e72/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/MediaTransportControls_themeresources.xaml#L411
- Fast Forward
https://github.com/unoplatform/uno/blob/d582c30861daa461659fd2756dd106f397838e72/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/MediaTransportControls_themeresources.xaml#L420
- Next Track
https://github.com/unoplatform/uno/blob/d582c30861daa461659fd2756dd106f397838e72/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/MediaTransportControls_themeresources.xaml#L429
- Skip Forward
https://github.com/unoplatform/uno/blob/d582c30861daa461659fd2756dd106f397838e72/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/MediaTransportControls_themeresources.xaml#L438
- Playback Rate
https://github.com/unoplatform/uno/blob/d582c30861daa461659fd2756dd106f397838e72/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/MediaTransportControls_themeresources.xaml#L447
- Cast
https://github.com/unoplatform/uno/blob/d582c30861daa461659fd2756dd106f397838e72/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/MediaTransportControls_themeresources.xaml#L467

**Comment by jeromelaban** [comment]
Ah right, I took the changes. Let me point to the right pieces.

**Comment by jeromelaban** [comment]
@NVLudwig it's updated!

**Comment by NVLudwig** [comment]
@jeromelaban Here is the latest font export it contains many things you don't need but that you may find interesting. All you should need is the .WOf2 file in the Fonts Folder.

1039 Glyphs including the 10 requested above

[Symbols-1039Glyphs-March18.zip](https://github.com/unoplatform/uno/files/11007435/Symbols-1039Glyphs-March18.zip)

**Comment by jeromelaban** [comment]
Merged recently

**Comment by NVLudwig** [comment]
Let me know if you need anything. I do small weekly updates to the Symbols font now, the latest has 1200 glyphs

**Comment by jeromelaban** [comment]
> @jeromelaban Were the glyph substitutions for MediaPlayerElement reverted as well?

It was yes!
