### ISSUE TITLE
`PathIcon` doesn't work on Wasm from class library

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11682]
### Current behavior

https://github.com/unoplatform/uno/blob/560a44980945eb8343025832fe0ea23941c99435/src/Uno.UI/UI/Xaml/Media/Geometry.cs#L35-L39

In a class library, the reference binary is used, so we get through `return Parsers.ParseGeometry(data);` which will crash on Wasm as there is no `GetSvgElement` implementation for `StreamGeometry` returned from `ParseGeometry`.

For this specific case, I'll find a workaround. But in general, any such code pattern in our code base could be broken. This is quite bad.

One solution is to move away from `#if`s to a runtime check (maybe https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation?view=net-7.0 could help?). This could be slower though, but no idea if it will be to an extent that it is not usable at all.

Another solution that works for me is to move back to shared projects. For me, they were much better (except for the IDE experience).

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
The reference binary should not be having an impact, that is unless the converter is not used at all because it's not in the reference API. Is that the case?

**Comment by Youssef1313** [comment]
The XAML generator makes use of the implicit conversion from string to Geometry

https://github.com/unoplatform/uno/blob/560a44980945eb8343025832fe0ea23941c99435/src/Uno.UI/UI/Xaml/Media/Geometry.cs#L33-L40

As far as I can tell, the class library is built against the reference binaries, so it doesn't go into the `#if __WASM__`

**Comment by jeromelaban** [comment]
`__WASM__` is available inside uno, so it's likely a different code path that is being executed. Can you provide a stack trace?

**Comment by jeromelaban** [comment]
There should not be any reference code executed at runtime, this looks like the root cause is somewhere else. Can you build a repro?

**Comment by Youssef1313** [comment]
Sure. I'll

**Comment by Youssef1313** [comment]
@jeromelaban I found it.

https://github.com/unoplatform/uno/blob/560a44980945eb8343025832fe0ea23941c99435/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L4912-L4917

I think a minimal repro isn't needed now as it's more clear this is a source generation error. We should always generate a string here and let the implicit conversion do the right thing at runtime.

**Comment by Youssef1313** [comment]
The thing that is still confusing to me is how any other code in xaml generator that uses `_isWasm` can work properly.

**Comment by jeromelaban** [comment]
@Youssef1313 that is fair. `_isWasm` cannot work in that case, as it will return false in a library, but the comment remains about the reference API, it should be replaced by the build process when generating the final package.

**Comment by Youssef1313** [comment]
> but the comment remains about the reference API, it should be replaced by the build process when generating the final package.

Yes. It was a wrong assumption on my side. When I found StreamGeometry, I thought that we used the incorrect code path in the implicit conversion. But, turned out we didn't use the implicit conversion at all.
