### ISSUE TITLE
`Border` with `CornerRadius` is not smooth on Android

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11685]
### Current behavior

```xml
<Border Width="200" Height="200" CornerRadius="100" BorderBrush="Red" BorderThickness="5" />
```

**Android emulator - Tablet M-DPI 10.1in Pie 9.0 - API 28 (Android 9.0 - API 28):**

![image](https://user-images.githubusercontent.com/31348972/225097229-c63173e8-daf7-4b6e-8fef-7119d7386bb9.png)

**Physical device - Xiaomi Redmi Note 7**:

![image](https://user-images.githubusercontent.com/31348972/227701701-36ea0a28-9232-4011-bec1-fb61b758d476.png)

### Expected behavior

Should be smooth

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
The above was a simplified repro. The original repro I had only reproduces on emulator but not physical device. So probably the simplified repro will reproduce only on emulator as well.

**Comment by agneszitte-nventive** [comment]
@Youssef1313 like we talked about, if you can list the emulators / physical devices that you used for your tests (+ android versions / API Level)
Any additional info that you can share like brand/model can also help in case it is challenging to repro the issue for some reason ;)
Thanks in advance :)

**Comment by Youssef1313** [comment]
Updated the issue.

**Comment by Youssef1313** [comment]
@MartinZikmund Not sure if this helps: https://medium.com/@ali.muzaffar/android-why-your-canvas-shapes-arent-smooth-aa2a3f450eb5#.kill8q45y

**Comment by MartinZikmund** [comment]
This may surely apply to shape paints - https://github.com/unoplatform/uno/blob/64fb74e411e0d85e9311593a878ff1cf25055011/src/Uno.UI/UI/Xaml/Shapes/Shape.Android.cs#L127

**Comment by Youssef1313** [comment]
I noticed this is very apparent in RadialGradientBrush sample:

![image](https://user-images.githubusercontent.com/31348972/235841289-775c0088-520e-44b5-b36b-df08acf412de.png)

**Comment by Youssef1313** [comment]
![image](https://user-images.githubusercontent.com/31348972/235842271-2bda1d01-e52a-4149-a4f7-0e675754ddd2.png)

@MartinZikmund I tried setting anti-alias in this code path, but no luck.

**Comment by MartinZikmund** [comment]
The `RadialGradientBrush` antialiasing is a separate issue apparently, opened #13261 for it.
