### ISSUE TITLE
Lottie namespace for net 6

### ISSUE THREAD

**Issue by Soap-141** [unoplatform/uno#11717]
## What would you like to be added:

 `Uno.WinUI.Lottie` require to use `xmlns:lottie="using:Microsoft.Toolkit.Uwp.UI.Lottie"`  which is the old namespace for UWP and Xamarin, while it could use the new namespace for the WinUI Lottie implementation `xmlns:lottie="using:CommunityToolkit.WinUI.Lottie"` because it would make the Xaml code cleaner.

https://www.nuget.org/packages/CommunityToolkit.WinUI.Lottie

## Why is this needed:

Cleaner code

## For which Platform:

- [ ] WebAssembly
- [x] Android
- [x] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
This is a breaking change that we'll include in Uno 5.0 (#8339)
