### ISSUE TITLE
[Docs] Add details on localization of WinAppSDK apps

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#11713]
## On which page?

As compared to UWP, packaged WinAppSDK app require removing `x-generate` from appxmanifest and listing explicitly the supported cultures. See here https://learn.microsoft.com/en-us/windows/apps/winui/winui3/localize-winui3-app . This should be mentioned in our docs as well.

**Comment by MartinZikmund** [comment]
@nickrandolph is it true that having this `Resources` file in the root of the WinAppSDK projects works around this problem?

![image](https://github.com/unoplatform/uno/assets/1075116/a4793b6b-7a1a-45be-b753-4656d75c3236)

**Comment by nickrandolph** [comment]
@MartinZikmund I'm not sure whether it addresses this specific issue. It was definitely a requirement in order to get WinUI to play ball with resources that are located in the class library for an Uno app
