### ISSUE TITLE
ToggleSwitch in IOS using Fluent Style Unexpected behavior

### ISSUE THREAD

**Issue by felipefrg** [unoplatform/uno#11731]
### Current behavior

When using the ToggleSwitch control on iOS with the Fluent style, its appearance has unexpected behavior, intermittently losing its style when clicked or swiped several times. Sometimes it loses its border, the inner circle, or even inverts the inner color that indicates whether it is in the ON or OFF position. This only happens on iOS when using the Fluent style.

https://user-images.githubusercontent.com/34286833/225896714-fcc70702-81a7-48d4-8c86-c06f30a1cd6a.mp4

https://user-images.githubusercontent.com/34286833/225896723-caab01ac-ce98-47a6-b112-273d00c7034b.mp4

### Expected behavior

The expected behavior is to have the same behavior consistently, not losing its appearance when toggling between the On and OFF values

### How to reproduce it (as minimally and precisely as possible)

[FirstProject.zip](https://github.com/unoplatform/uno/files/11001123/FirstProject.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.5.1

**Comment by marwalsch** [comment]
Related, if not duplicate: [#8636](https://github.com/unoplatform/uno/issues/8636)

**Comment by jeromelaban** [comment]
@marwalsch Indeed, it's a duplicate, thanks.
