### ISSUE TITLE
`FlipView` background not working on Android

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11740]
### Current behavior

Create a new Uno app and use this XAML code:

```xaml
    <StackPanel>
        <TextBlock Text="Text1" />
        <FlipView Width="500" Height="500" Background="Red" />
        <TextBlock Text="Text2" />
    </StackPanel>
```

![image](https://user-images.githubusercontent.com/31348972/226097375-e18ad1b2-f4a4-4a96-a48f-dbecb6b3e3dd.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/31348972/226097395-72b96a46-7c23-4442-a6c6-597ce0326d57.png)

### Works on UWP/WinUI

None

**Comment by MartinZikmund** [comment]
@ajpinedam Can you look into this one?
