### ISSUE TITLE
PropertyMetadata has wrong name in RegisterAttached

### ISSUE THREAD

**Issue by dansiegel** [unoplatform/uno#11754]
### Current behavior

When compiling for NetStandard the PropertyMetadata argument in `DependencyProperty.RegisterAttached` is `typeMetadata`. When compiling for all other platforms it is `defaultMetadata`.

### Expected behavior

The argument should be named consistent with the other platforms `defaultMetadata`

### How to reproduce it (as minimally and precisely as possible)

```cs
	public static readonly DependencyProperty FooProperty =
		DependencyProperty.RegisterAttached(
			name: "Foo",
			propertyType: typeof(string),
			ownerType: typeof(MyClass),
#if NETSTANDARD
			typeMetadata: new PropertyMetadata(defaultValue: null, propertyChangedCallback: OnFooChanged));
#else
			defaultMetadata: new PropertyMetadata(defaultValue: null, propertyChangedCallback: OnFooChanged));
#endif
```

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer)

**Comment by Youssef1313** [comment]
The name appears to be `typeMetadata` in all Uno targets?

https://github.com/unoplatform/uno/blob/d68a846dea34d878db303b779721173652e91438/src/Uno.UI/UI/Xaml/DependencyProperty.cs#L147

The name `defaultMetadata` is from Windows. We should change the name to match Windows, but likely as a breaking change.
