### ISSUE TITLE
Remove all JSInvoke uses for CSP compatibility

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#11769]

**Comment by ebariche** [comment]
InvokeJS (Count = 88)
===============
[ ] AddIns\Uno.UI.Lottie\LottieVisualSourceBase.wasm.cs(315)
    private static string InvokeJs(string[] js) => WebAssemblyRuntime.InvokeJS(string.Concat(js));
[ ] Uno.Foundation.Runtime.WebAssembly\Interop\JSObjectMetadataProvider.wasm.cs(48)
    WebAssemblyRuntime.InvokeJS(prototype);
[ ] Uno.Foundation.Runtime.WebAssembly\Interop\JSObjectMetadataProvider.wasm.cs(53)
    WebAssemblyRuntime.InvokeJS($"{_type.FullName}.createInstance(\"{managedHandle}\", \"{id}\")");
[ ] Uno.Foundation.Runtime.WebAssembly\Interop\JSObjectMetadataProvider.wasm.cs(64)
    => WebAssemblyRuntime.InvokeJS($"{_type.FullName}.destroyInstance(\"{managedHandle}\", \"{jsHandle}\")");
[ ] Uno.Foundation.Runtime.WebAssembly\Interop\Runtime.wasm.cs(328)
    return InvokeJS(command);
[ ] Uno.UI.Runtime.WebAssembly\WasmHttpHandler.cs(62)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UI.Runtime.WebAssembly\Web\Http\CookieManager.cs(56)
    WebAssemblyRuntime.InvokeJS(jsInvoke);
[ ] Uno.UI.Runtime.WebAssembly\Web\Http\CookieManager.cs(105)
    var cookies = WebAssemblyRuntime.InvokeJS("document.cookie");
[ ] Uno.UI.Runtime.WebAssembly\Xaml\UIElementWasmExtensions.cs(130)
    return WebAssemblyRuntime.InvokeJS(js);
[ ] Uno.UI\UI\Xaml\Controls\Image\Image.wasm.cs(112)
    WebAssemblyRuntime.InvokeJS("Uno.UI.WindowManager.current.setImageAsMonochrome(" + _htmlImage.HtmlId + ", \"" + 
    img.Value + "\", \"" + MonochromeColor.Value.ToHexString() + "\");");
[ ] Uno.UI\UI\Xaml\Controls\TextBox\TextBoxView.wasm.cs(115)
    => WebAssemblyRuntime.InvokeJS($"Uno.UI.WindowManager.current.selectInputRange({HtmlId}, {start}, {length})");
[ ] Uno.UI\UI\Xaml\DragDrop\DragDropExtension.wasm.cs(103)
    WebAssemblyRuntime.InvokeJS("Windows.ApplicationModel.DataTransfer.DragDrop.Core.DragDropExtension
    .registerNoOp();");
[ ] Uno.UI\UI\Xaml\FontFamilyLoader.wasm.cs(184)
    WebAssemblyRuntime.InvokeJS($"Windows.UI.Xaml.Media.FontFamily.loadFont(\"{_fontFamily.CssFontName}\",\" 
    {_fontFamily.ExternalSource}\")");
[ ] Uno.UI\UI\Xaml\FontFamilyLoader.wasm.cs(188)
    WebAssemblyRuntime.InvokeJS($"Windows.UI.Xaml.Media.FontFamily.forceFontUsage(\"{_fontFamily.CssFontName}\")");
[ ] Uno.UI\UI\Xaml\Input\FocusManager.wasm.cs(108)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UI\UI\Xaml\Input\PointerRoutedEventArgs.wasm.cs(113)
    _bootTime ??= (ulong)(double.Parse(WebAssemblyRuntime.InvokeJS("Date.now() - performance.now()"), 
    CultureInfo.InvariantCulture) * TimeSpan.TicksPerMillisecond);
[ ] Uno.UI\UI\Xaml\Media\Animation\Animators\RenderingLoopAnimator.wasm.cs(97)
    WebAssemblyRuntime.InvokeJS($"Windows.UI.Xaml.Media.Animation.RenderingLoopAnimator.createInstance(\" 
    {managedHandle}\", \"{id}\")");
[ ] Uno.UI\UI\Xaml\Media\Animation\Animators\RenderingLoopAnimator.wasm.cs(108)
    => WebAssemblyRuntime.InvokeJS($"Windows.UI.Xaml.Media.Animation.RenderingLoopAnimator.destroyInstance(\" 
    {jsHandle}\")");
[ ] Uno.UI\UI\Xaml\Media\Imaging\WriteableBitmap.wasm.cs(20)
    var value = WebAssemblyRuntime.InvokeJS("Uno.UI.WindowManager.current.rawPixelsToBase64EncodeImage(" + 
    pinnedData + ", " + PixelWidth + ", " + PixelHeight + ");");
[ ] Uno.UI\UI\Xaml\UIElement.wasm.cs(297)
    return WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\ApplicationModel\Calls\PhoneCallManager.wasm.cs(14)
    Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\ApplicationModel\Contacts\ContactPicker.wasm.cs(22)
    var isSupportedString = WebAssemblyRuntime.InvokeJS($"{JsType}.isSupported()");
[ ] Uno.UWP\ApplicationModel\DataTransfer\Clipboard.wasm.cs(57)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\ApplicationModel\DataTransfer\Clipboard.wasm.cs(63)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\ApplicationModel\DataTransfer\Clipboard.wasm.cs(69)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\ApplicationModel\DataTransfer\DataTransferManager.wasm.cs(13)
    public static bool IsSupported() => bool.TryParse(WebAssemblyRuntime.InvokeJS($"{JsType}.isSupported()"), out var result) 
    && result;
[ ] Uno.UWP\Devices\Enumeration\Internal\Providers\Midi\MidiDeviceClassProviderBase.wasm.cs(108)
    var result = InvokeJS(command);
[ ] Uno.UWP\Devices\Enumeration\Internal\Providers\Midi\MidiDeviceConnectionWatcher.wasm.cs(27)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Devices\Enumeration\Internal\Providers\Midi\MidiDeviceConnectionWatcher.wasm.cs(41)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Devices\Midi\MidiInPort.wasm.cs(35)
    WebAssemblyRuntime.InvokeJS(addListenerCommand);
[ ] Uno.UWP\Devices\Midi\MidiInPort.wasm.cs(42)
    WebAssemblyRuntime.InvokeJS(removeListenerCommand);
[ ] Uno.UWP\Devices\Midi\MidiInPort.wasm.cs(78)
    WebAssemblyRuntime.InvokeJS(removeInstanceCommand);
[ ] Uno.UWP\Devices\Midi\MidiInPort.wasm.cs(89)
    WebAssemblyRuntime.InvokeJS(initialization);
[ ] Uno.UWP\Devices\Midi\MidiOutPort.wasm.cs(41)
    InvokeJS(command);
[ ] Uno.UWP\Devices\Sensors\Gyrometer.wasm.cs(24)
    var initialized = Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Devices\Sensors\Gyrometer.wasm.cs(35)
    Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Devices\Sensors\Gyrometer.wasm.cs(41)
    Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Devices\Sensors\LightSensor.wasm.cs(15)
    var initialized = Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Devices\Sensors\LightSensor.wasm.cs(26)
    Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Devices\Sensors\LightSensor.wasm.cs(32)
    Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Devices\Sensors\Magnetometer.wasm.cs(24)
    var initialized = Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Devices\Sensors\Magnetometer.wasm.cs(35)
    Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Devices\Sensors\Magnetometer.wasm.cs(41)
    Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Gaming\Input\Gamepad.wasm.cs(29)
    var result = WebAssemblyRuntime.InvokeJS($"{JsType}.getReading({_id})");
[ ] Uno.UWP\Gaming\Input\Gamepad.wasm.cs(133)
    var serializedIds = WebAssemblyRuntime.InvokeJS(getConnectedGamepadIdsCommand);
[ ] Uno.UWP\Gaming\Input\Gamepad.wasm.cs(165)
    WebAssemblyRuntime.InvokeJS(startGamepadAddedCommand);
[ ] Uno.UWP\Gaming\Input\Gamepad.wasm.cs(171)
    WebAssemblyRuntime.InvokeJS(endGamepadAddedCommand);
[ ] Uno.UWP\Gaming\Input\Gamepad.wasm.cs(177)
    WebAssemblyRuntime.InvokeJS(startGamepadRemovedCommand);
[ ] Uno.UWP\Gaming\Input\Gamepad.wasm.cs(183)
    WebAssemblyRuntime.InvokeJS(endGamepadRemovedCommand);
[ ] Uno.UWP\Graphics\Display\DisplayInformation.wasm.cs(154)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Graphics\Display\DisplayInformation.wasm.cs(160)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Graphics\Display\DisplayInformation.wasm.cs(167)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Graphics\Display\DisplayInformation.wasm.cs(173)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Graphics\Display\DisplayInformation.wasm.cs(184)
    float.TryParse(WebAssemblyRuntime.InvokeJS(property), NumberStyles.Any, CultureInfo.InvariantCulture, out value);
[ ] Uno.UWP\Graphics\Display\DisplayInformation.wasm.cs(187)
    int.TryParse(WebAssemblyRuntime.InvokeJS(property), NumberStyles.Any, CultureInfo.InvariantCulture, out value);
[ ] Uno.UWP\Graphics\Display\DisplayInformation.wasm.cs(189)
    private static string ReadJsString(string property) => WebAssemblyRuntime.InvokeJS(property);
[ ] Uno.UWP\Helpers\ProtocolActivation.wasm.cs(75)
    var initialized = Uno.Foundation.WebAssemblyRuntime.InvokeJS(
[ ] Uno.UWP\Helpers\Theming\SystemThemeHelper.wasm.cs(21)
    var serializedTheme = WebAssemblyRuntime.InvokeJS(BaseUIXamlNamespace + ".Application.getDefaultSystemTheme()");
[ ] Uno.UWP\Media\SpeechRecognition\SpeechRecognizer.wasm.cs(95)
    var recognizeResult = WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Media\SpeechRecognition\SpeechRecognizer.wasm.cs(111)
    WebAssemblyRuntime.InvokeJS(removeInstanceCommand);
[ ] Uno.UWP\Media\SpeechRecognition\SpeechRecognizer.wasm.cs(117)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Networking\Connectivity\ConnectionProfile.wasm.cs(19)
    var result = Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Networking\Connectivity\NetworkInformation.wasm.cs(18)
    Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Networking\Connectivity\NetworkInformation.wasm.cs(24)
    Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Phone\Devices\Notification\VibrationDevice.wasm.cs(23)
    var initialized = Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Phone\Devices\Notification\VibrationDevice.wasm.cs(42)
    Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\Security\Authentication\Web\WebAuthenticationBrokerProvider.wasm.cs(16)
    var origin = WebAssemblyRuntime.InvokeJS(js);
[ ] Uno.UWP\Security\ExchangeActiveSyncProvisioning\EasClientDeviceInformation.wasm.cs(18)
    var userAgent = InvokeJS(JsType + ".getUserAgent()");
[ ] Uno.UWP\Storage\CachedFileManager.wasm.cs(30)
    WebAssemblyRuntime.InvokeJS($"Windows.Storage.Pickers.FileSavePicker.SaveAs('{file.Name}', {pinnedData}, {data.Length})");
[ ] Uno.UWP\Storage\Pickers\FileOpenPicker.wasm.cs(28)
    var isSupportedString = WebAssemblyRuntime.InvokeJS($"{JsType}.isNativeSupported()");
[ ] Uno.UWP\Storage\Pickers\FileSavePicker.wasm.cs(28)
    var isSupportedString = WebAssemblyRuntime.InvokeJS($"{JsType}.isNativeSupported()");
[ ] Uno.UWP\Storage\Pickers\FolderPicker.wasm.cs(23)
    var isSupportedString = WebAssemblyRuntime.InvokeJS($"{JsType}.isNativeSupported()");
[ ] Uno.UWP\Storage\Streams\Internal\NativeReadStreamAdapter.wasm.cs(94)
    WebAssemblyRuntime.InvokeJS($"{JsType}.close('{_streamId}')");
[ ] Uno.UWP\System\Display\DisplayRequest.wasm.cs(17)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\System\Display\DisplayRequest.wasm.cs(23)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\System\Launcher.wasm.cs(13)
    var result = WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\System\MemoryManager.wasm.cs(20)
    if (ulong.TryParse(WebAssemblyRuntime.InvokeJS(
[ ] Uno.UWP\System\Profile\AnalyticsInfo.wasm.cs(13)
    var typeString = WebAssemblyRuntime.InvokeJS($"{JsType}.getDeviceType()");
[ ] Uno.UWP\UI\Core\CoreWindow.wasm.cs(29)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\UI\Core\SystemNavigationManager.wasm.cs(16)
    WebAssemblyRuntime.InvokeJS("Windows.UI.Core.SystemNavigationManager.current.enable();");
[ ] Uno.UWP\UI\Core\SystemNavigationManager.wasm.cs(21)
    WebAssemblyRuntime.InvokeJS("Windows.UI.Core.SystemNavigationManager.current.disable();");
[ ] Uno.UWP\UI\Notifications\BadgeUpdater.wasm.cs(15)
    WebAssemblyRuntime.InvokeJS($"{JsType}.setNumber({number})");
[ ] Uno.UWP\UI\Notifications\BadgeUpdater.wasm.cs(19)
    WebAssemblyRuntime.InvokeJS($"{JsType}.clear()");
[ ] Uno.UWP\UI\Popups\MessageDialog.wasm.cs(23)
    Uno.Foundation.WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\UI\ViewManagement\ApplicationView.wasm.cs(19)
    return WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\UI\ViewManagement\ApplicationView.wasm.cs(25)
    WebAssemblyRuntime.InvokeJS(command);
[ ] Uno.UWP\UI\ViewManagement\ApplicationView.wasm.cs(36)
    var result = WebAssemblyRuntime.InvokeJS(jsEval);
[ ] Uno.UWP\UI\ViewManagement\ApplicationViewTitleBar.wasm.cs(35)
    WebAssemblyRuntime.InvokeJS(command);

InvokeJSWithInterop (Count = 4)
======================
[ ] Uno.UI\UI\Xaml\Media\Animation\Animators\RenderingLoopAnimator.wasm.cs(24)
    WebAssemblyRuntime.InvokeJSWithInterop($"{this}.EnableFrameReporting();");
[ ] Uno.UI\UI\Xaml\Media\Animation\Animators\RenderingLoopAnimator.wasm.cs(36)
    WebAssemblyRuntime.InvokeJSWithInterop($"{this}.DisableFrameReporting();");
[ ] Uno.UI\UI\Xaml\Media\Animation\Animators\RenderingLoopAnimator.wasm.cs(48)
    WebAssemblyRuntime.InvokeJSWithInterop($"{this}.SetStartFrameDelay({delayMs});");
[ ] Uno.UI\UI\Xaml\Media\Animation\Animators\RenderingLoopAnimator.wasm.cs(60)
    WebAssemblyRuntime.InvokeJSWithInterop($"{this}.SetAnimationFramesInterval();");

InvokeAsync (Count = 38)
===============
[ ] AddIns\Uno.UI.MSAL\WasmWebUi.wasm.cs(20)
    var uri = await WebAssemblyRuntime.InvokeAsync(js);
[ ] Uno.UI\UI\Xaml\Media\ImageBrush.wasm.cs(223)
    var naturalSizeResponse = await Uno.Foundation.WebAssemblyRuntime.InvokeAsync(command);
[ ] Uno.UI\UI\Xaml\Media\Imaging\BitmapImage.wasm.cs(85)
    var assets = await WebAssemblyRuntime.InvokeAsync($"fetch('{assetsUri}').then(r => r.text())");
[ ] Uno.UWP\ApplicationModel\Contacts\ContactPicker.wasm.cs(28)
    var pickResultJson = await WebAssemblyRuntime.InvokeAsync($"{JsType}.pickContacts({(multiple ? "true" : "false")})");
[ ] Uno.UWP\ApplicationModel\DataTransfer\DataTransferManager.wasm.cs(36)
    var result = await WebAssemblyRuntime.InvokeAsync($"{JsType}.showShareUI({title ?? "null"},{text ?? "null"},{uriText ?? 
    "null"})");
[ ] Uno.UWP\Devices\Midi\Internal\WasmMidiAccess.wasm.cs(28)
    var result = await InvokeAsync(command);
[ ] Uno.UWP\Security\Authentication\Web\WebAuthenticationBrokerProvider.wasm.cs(64)
    var results = (await WebAssemblyRuntime.InvokeAsync(js)).Split(new[] { '|' }, 2);
[ ] Uno.UWP\Storage\Helpers\AssetsManager.wasm.cs(34)
    var assets = await 
    WebAssemblyRuntime.InvokeAsync($"Windows.Storage.AssetManager.DownloadAssetsManifest(\'{assetsUri}\')");
[ ] Uno.UWP\Storage\Helpers\AssetsManager.wasm.cs(53)
    var assetInfo = await WebAssemblyRuntime.InvokeAsync($"Windows.Storage.AssetManager.DownloadAsset(\'{assetUri}\')");
[ ] Uno.UWP\Storage\Pickers\FileOpenPicker.wasm.cs(75)
    var nativeStorageItemInfosJson = await WebAssemblyRuntime.InvokeAsync($" 
   {JsType}.nativePickFilesAsync({multipleParameter},{showAllEntryParameter},'{fileTypeMapParameter}','{id}','{startIn}')");
[ ] Uno.UWP\Storage\Pickers\FileOpenPicker.wasm.cs(147)
    var fileCountString = await WebAssemblyRuntime.InvokeAsync(jsUploadQuery);
[ ] Uno.UWP\Storage\Pickers\FileSavePicker.wasm.cs(66)
    var nativeStorageItemInfo = await WebAssemblyRuntime.InvokeAsync(promise);
[ ] Uno.UWP\Storage\Pickers\FolderPicker.wasm.cs(40)
    var pickedFolderJson = await WebAssemblyRuntime.InvokeAsync($"{JsType}.pickSingleFolderAsync('{id}','{startIn}')");
[ ] Uno.UWP\Storage\StorageFile.native.wasm.cs(59)
    var basicPropertiesString = await WebAssemblyRuntime.InvokeAsync($"{JsType}.getBasicPropertiesAsync(\"{_id}\")");
[ ] Uno.UWP\Storage\StorageFolder.native.wasm.cs(48)
    var itemInfoJson = await WebAssemblyRuntime.InvokeAsync($"{JsType}.getPrivateRootAsync()");
[ ] Uno.UWP\Storage\StorageFolder.native.wasm.cs(105)
    var newFolderNativeInfo = await WebAssemblyRuntime.InvokeAsync($"{JsType}.createFolderAsync(\"{_id}\", \" 
   {folderName}\")");
[ ] Uno.UWP\Storage\StorageFolder.native.wasm.cs(118)
    var folderInfoJson = await WebAssemblyRuntime.InvokeAsync($"{JsType}.tryGetFolderAsync(\"{_id}\", \" 
   {WebAssemblyRuntime.EscapeJs(name)}\")");
[ ] Uno.UWP\Storage\StorageFolder.native.wasm.cs(122)
    var fileInfoJson = await WebAssemblyRuntime.InvokeAsync($"{JsType}.tryGetFileAsync(\"{_id}\", \"{WebAssemblyRuntime.EscapeJs(name)}\")");
[ ] Uno.UWP\Storage\StorageFolder.native.wasm.cs(143)
    var itemInfosJson = await WebAssemblyRuntime.InvokeAsync($"{JsType}.getItemsAsync(\"{_id}\")");
[ ] Uno.UWP\Storage\StorageFolder.native.wasm.cs(162)
    var itemInfosJson = await WebAssemblyRuntime.InvokeAsync($"{JsType}.getFilesAsync(\"{_id}\")");
[ ] Uno.UWP\Storage\StorageFolder.native.wasm.cs(174)
    var itemInfosJson = await WebAssemblyRuntime.InvokeAsync($"{JsType}.getFoldersAsync(\"{_id}\")");
[ ] Uno.UWP\Storage\StorageFolder.native.wasm.cs(231)
    var newFolderNativeInfo = await WebAssemblyRuntime.InvokeAsync($"{JsType}.createFileAsync(\"{_id}\", \" 
   {WebAssemblyRuntime.EscapeJs(actualName)}\")");
[ ] Uno.UWP\Storage\StorageFolder.native.wasm.cs(243)
    var fileInfoJson = await WebAssemblyRuntime.InvokeAsync($"{JsType}.tryGetFileAsync(\"{_id}\", \" 
   {WebAssemblyRuntime.EscapeJs(name)}\")");
[ ] Uno.UWP\Storage\StorageFolder.native.wasm.cs(247)
    var folderInfoJson = await WebAssemblyRuntime.InvokeAsync($"{JsType}.tryGetFolderAsync(\"{_id}\", \" 
   {WebAssemblyRuntime.EscapeJs(name)}\")");
[ ] Uno.UWP\Storage\StorageFolder.native.wasm.cs(281)
    var fileInfoJson = await WebAssemblyRuntime.InvokeAsync($"{JsType}.tryGetFileAsync(\"{_id}\", \" 
   {WebAssemblyRuntime.EscapeJs(name)}\")");
[ ] Uno.UWP\Storage\StorageFolder.native.wasm.cs(289)
    var folderInfoJson = await WebAssemblyRuntime.InvokeAsync($"{JsType}.tryGetFolderAsync(\"{_id}\", \" 
   {WebAssemblyRuntime.EscapeJs(name)}\")");
[ ] Uno.UWP\Storage\StorageFolder.native.wasm.cs(313)
    var result = await WebAssemblyRuntime.InvokeAsync($"{JsType}.deleteItemAsync(\"{_id}\", \" 
   {WebAssemblyRuntime.EscapeJs(itemName)}\")");
[ ] Uno.UWP\Storage\Streams\Internal\NativeReadStreamAdapter.wasm.cs(23)
    var result = await WebAssemblyRuntime.InvokeAsync($"{JsType}.openAsync('{streamId}', '{fileId}')");
[ ] Uno.UWP\Storage\Streams\Internal\NativeReadStreamAdapter.wasm.cs(81)
    var countReadString = await WebAssemblyRuntime.InvokeAsync($"{JsType}.readAsync('{_streamId}', {pinnedData}, {offset}, 
    {count}, {Position})");
[ ] Uno.UWP\Storage\Streams\Internal\NativeWriteStreamAdapter.wasm.cs(26)
    var result = await WebAssemblyRuntime.InvokeAsync($"{JsType}.openAsync('{streamId}', '{fileId}')");
[ ] Uno.UWP\Storage\Streams\Internal\NativeWriteStreamAdapter.wasm.cs(106)
    await WebAssemblyRuntime.InvokeAsync($"{JsType}.writeAsync('{_streamId}', {pinnedData}, {offset}, {count}, {Position})");
[ ] Uno.UWP\Storage\Streams\Internal\NativeWriteStreamAdapter.wasm.cs(124)
    await WebAssemblyRuntime.InvokeAsync($"{JsType}.closeAsync('{_streamId}')");
[ ] Uno.UWP\Storage\Streams\Internal\NativeWriteStreamAdapter.wasm.cs(135)
    await WebAssemblyRuntime.InvokeAsync($"{JsType}.truncateAsync('{_streamId}',{length})");
[ ] Uno.UWP\Storage\Streams\Internal\NativeWriteStreamAdapter.wasm.cs(150)
    await WebAssemblyRuntime.InvokeAsync($"{JsType}.closeAsync('{_streamId}')");
[ ] Uno.UI\UI\Xaml\DragDrop\DragDropExtension.wasm.cs(316)
    var infosRaw = await WebAssemblyRuntime.InvokeAsync($"{_jsType}.retrieveFiles({rawItemsIds})", ct);
[ ] Uno.UI\UI\Xaml\DragDrop\DragDropExtension.wasm.cs(326)
    var text = await WebAssemblyRuntime.InvokeAsync($"{_jsType}.retrieveText({itemId.ToStringInvariant()})", cts.Token);
[ ] Uno.UWP\ApplicationModel\DataTransfer\Clipboard.wasm.cs(48)
    var text = await WebAssemblyRuntime.InvokeAsync(command, ct);
[ ] Uno.UWP\Graphics\Display\DisplayInformation.wasm.cs(207)
    return WebAssemblyRuntime.InvokeAsync($"{JsType}.setOrientationAsync({(int)orientations})", ct);

mono_bind_static_method (Count = 40)
===========================
[ ] Uno.UI\ts\Clipboard.ts(64)
    (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\CoreDispatcher.ts(57)
    CoreDispatcher._coreDispatcherCallback = (<any>Module).mono_bind_static_method("[Uno.UI.Dispatching] 
    Uno.UI.Dispatching.CoreDispatcher:DispatcherCallback");
[ ] Uno.UI\ts\Guid.ts(7)
    Guid.newGuidMethod = (<any>Module).mono_bind_static_method("[mscorlib] System.Guid:NewGuid");
[ ] Uno.UI\ts\HttpClient.ts(84)
    this.dispatchResponseMethod = (<any>Module).mono_bind_static_method("[Uno.UI.Runtime.WebAssembly] 
    Uno.UI.Wasm.WasmHttpHandler:DispatchResponse");
[ ] Uno.UI\ts\HttpClient.ts(85)
    this.dispatchErrorMethod = (<any>Module).mono_bind_static_method("[Uno.UI.Runtime.WebAssembly] 
    Uno.UI.Wasm.WasmHttpHandler:DispatchError");
[ ] Uno.UI\ts\Interop\AsyncInteropHelper.ts(13)
    w.Module.mono_bind_static_method("[Uno.Foundation.Runtime.WebAssembly] 
    Uno.Foundation.WebAssemblyRuntime:DispatchAsyncResult");
[ ] Uno.UI\ts\Interop\AsyncInteropHelper.ts(15)
    w.Module.mono_bind_static_method("[Uno.Foundation.Runtime.WebAssembly] 
    Uno.Foundation.WebAssemblyRuntime:DispatchAsyncError");
[ ] Uno.UI\ts\Interop\ManagedObject.ts(7)
    ManagedObject.dispatchMethod = (<any>Module).mono_bind_static_method("[Uno.Foundation.Runtime.WebAssembly] 
    Uno.Foundation.Interop.JSObject:Dispatch");
[ ] Uno.UI\ts\MonoSupport.ts(96)
    jsCallDispatcher.dispatcherCallback = (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\WindowManager.ts(1536)
    WindowManager.getDependencyPropertyValueMethod = (<any>Module).mono_bind_static_method("[Uno.UI] 
    Uno.UI.Helpers.Automation:GetDependencyPropertyValue");
[ ] Uno.UI\ts\WindowManager.ts(1552)
    WindowManager.setDependencyPropertyValueMethod = (<any>Module).mono_bind_static_method("[Uno.UI] 
    Uno.UI.Helpers.Automation:SetDependencyPropertyValue");
[ ] Uno.UI\ts\WindowManager.ts(1584)
    WindowManager.resizeMethod = (<any>Module).mono_bind_static_method("[Uno.UI] Windows.UI.Xaml.Window:Resize");
[ ] Uno.UI\ts\WindowManager.ts(1588)
    WindowManager.dispatchEventMethod = (<any>Module).mono_bind_static_method("[Uno.UI] 
    Windows.UI.Xaml.UIElement:DispatchEvent");
[ ] Uno.UI\ts\WindowManager.ts(1592)
    WindowManager.focusInMethod = (<any>Module).mono_bind_static_method("[Uno.UI] 
    Windows.UI.Xaml.Input.FocusManager:ReceiveFocusNative");
[ ] Uno.UI\ts\WindowManager.ts(1596)
    WindowManager.dispatchSuspendingMethod = (<any>Module).mono_bind_static_method("[Uno.UI] 
    Windows.UI.Xaml.Application:DispatchSuspending");
[ ] Uno.UI\ts\Windows\ApplicationModel\DataTransfer\DragAndDropExtension.ts(18)
    DragDropExtension._dispatchDropEventMethod = (<any>Module).mono_bind_static_method("[Uno.UI] 
    Windows.ApplicationModel.DataTransfer.DragDrop.Core.DragDropExtension:OnNativeDropEvent");
[ ] Uno.UI\ts\Windows\Devices\Enumeration\Internal\Providers\Midi\MidiDeviceConnectionWatcher.ts(18)
    (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\Windows\Devices\Midi\MidiInPort.ts(30)
    MidiInPort.dispatchMessage = (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\Windows\Devices\Sensors\Gyrometer.ts(20)
    this.dispatchReading = (<any>Module).mono_bind_static_method("[Uno] 
    Windows.Devices.Sensors.Gyrometer:DispatchReading");
[ ] Uno.UI\ts\Windows\Devices\Sensors\LightSensor.ts(24)
    LightSensor.dispatchReading = (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\Windows\Devices\Sensors\Magnetometer.ts(20)
    this.dispatchReading = (<any>Module).mono_bind_static_method("[Uno] 
    Windows.Devices.Sensors.Magnetometer:DispatchReading");
[ ] Uno.UI\ts\Windows\Gaming\Input\Gamepad.ts(68)
    Gamepad.dispatchGamepadAdded = (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\Windows\Gaming\Input\Gamepad.ts(76)
    Gamepad.dispatchGamepadRemoved = (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\Windows\Graphics\Display\DisplayInformation.ts(126)
    (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\Windows\Graphics\Display\DisplayInformation.ts(137)
    (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\Windows\Media\SpeechRecognizer.ts(69)
    SpeechRecognizer.dispatchResult = (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\Windows\Media\SpeechRecognizer.ts(75)
    SpeechRecognizer.dispatchHypothesis = (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\Windows\Media\SpeechRecognizer.ts(84)
    SpeechRecognizer.dispatchStatus = (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\Windows\Media\SpeechRecognizer.ts(92)
    SpeechRecognizer.dispatchError = (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\Windows\Networking\Connectivity\NetworkInformation.ts(19)
    (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\Windows\Storage\NativeStorageItem.ts(78)
    NativeStorageItem.generateGuidBinding = (<any>Module).mono_bind_static_method("[Uno] 
    Uno.Storage.NativeStorageItem:GenerateGuids");
[ ] Uno.UI\ts\Windows\Storage\StorageFolder.ts(73)
    (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\Windows\UI\Core\SystemNavigationManager.ts(17)
    var dispatchBackRequest = (<any>Module).mono_bind_static_method("[Uno] 
    Windows.UI.Core.SystemNavigationManager:DispatchBackRequest");
[ ] Uno.UI\ts\Windows\UI\Xaml\Application.ts(21)
    Application.dispatchThemeChange = (<any>Module).mono_bind_static_method("[Uno.UI] 
    Windows.UI.Xaml.Application:DispatchSystemThemeChange");
[ ] Uno.UI\ts\Windows\UI\Xaml\Application.ts(33)
    Application.dispatchVisibilityChange = (<any>Module).mono_bind_static_method("[Uno.UI] 
    Windows.UI.Xaml.Application:DispatchVisibilityChange");
[ ] Uno.UI\ts\Windows\UI\Xaml\Input\FocusVisual.ts(28)
    FocusVisual.dispatchPositionChange = (<any>Module).mono_bind_static_method(
[ ] Uno.UI\ts\Windows\UI\Xaml\Media\FontFamily.ts(53)
    (<any>Module).mono_bind_static_method("[Uno.UI] Windows.UI.Xaml.Media.FontFamilyLoader:NotifyFontLoaded");
[ ] Uno.UI\ts\Windows\UI\Xaml\Media\FontFamily.ts(63)
    (<any>Module).mono_bind_static_method("[Uno.UI] Windows.UI.Xaml.Media.FontFamilyLoader:NotifyFontLoadFailed");
[ ] Uno.UI\ts\Windows\UI\Xaml\UIElement.Pointers.ts(26)
    UIElement._dispatchPointerEventMethod = (<any>Module).mono_bind_static_method("[Uno.UI] 
    Windows.UI.Xaml.UIElement:OnNativePointerEvent");
[ ] Uno.UI\ts\Windows\UI\Xaml\UIElement.Pointers.ts(33)
    UIElement._dispatchPointerEventMethod = (<any>Module).mono_bind_static_method("[Uno.UI] 
    Windows.UI.Xaml.UIElement:OnNativePointerEvent");
