### ISSUE TITLE
Snippets are missing from Playground

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#11780]
### Current behavior

![image](https://user-images.githubusercontent.com/1075116/227211798-912e7a2a-114b-412a-b9a1-0707ccc93f72.png)

### Expected behavior

There should be much more samples

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
This feels like a listview issue, not missing samples. I don't have that problem locally.

**Comment by sakshi173** [comment]
@jeromelaban, sorry I am not able to understand the issue properly. could you please provide more information. I checked list is displaying correctly.
![playground list](https://user-images.githubusercontent.com/74563602/227404747-79561a97-b086-4057-b6c1-e437a0796143.png)

https://user-images.githubusercontent.com/74563602/227404764-b3877237-91ef-4f0e-8de7-28d99e4a4f02.mp4

**Comment by MartinZikmund** [comment]
@jeromelaban Very weird! On my second PC I can't reproduce it either. Will check again on the PC where it happened and close if I can't repro

**Comment by MartinZikmund** [comment]
Can't repro anymore, closing
