### ISSUE TITLE
[iOS][Uno.WinUI.Lottie] The background of an animated logo turns black after navigating

### ISSUE THREAD

**Issue by Lee31416** [unoplatform/uno#11785]
### Current behavior

The background of a lottie animation is black after navigating to another page and coming back only on iOS
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/72167772/227252430-fc67231f-c82d-4dc7-904d-6018d3329ca4.gif)

### Expected behavior

The animation shouldn't change 

### How to reproduce it (as minimally and precisely as possible)

1. Download this sample [LottieBugSample.zip](https://github.com/unoplatform/nventive-private/files/11052701/LottieBugSample.zip)
2. Build the sample app for iOS
3. Look at the animated logo working properly
4. Navigate to the other page using the button
5. Notice the background turned black

### Workaround

None

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.9.0-dev.64 (Uno.WinUI)

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.5.2

**Comment by Lee31416** [comment]
Published here by error wanted to publish to uno repo

**Comment by Soap-141** [comment]
@jeromelaban @Lee31416 Just tested it's working thanks!
