### ISSUE TITLE
`FlipView` doesn't correctly display arrows

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11794]
### Current behavior

![image](https://user-images.githubusercontent.com/31348972/227499805-d27199af-df44-4182-82f2-3beccb6e224d.png)

https://playground.platform.uno/#3fd87911

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/blob/40662d99457a97e3cc3105cceb4631f265a4dbdf/src/Uno.UI.FluentTheme.v1/Resources/Version1/PriorityDefault/FlipView_themeresources.xaml#L155-L156


https://github.com/unoplatform/uno/blob/40662d99457a97e3cc3105cceb4631f265a4dbdf/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/FlipView_themeresources.xaml#L182-L183

In `C:\Users\PC\.nuget\packages\uno.fonts.fluent\2.1.0-dev.9\lib\netstandard1.0\Uno.Fonts.Fluent\Fonts\uno-fluentui-assets.ttf`, I can see 0xE0E3 symbol:

![image](https://user-images.githubusercontent.com/31348972/227502925-dc95f0d7-c28d-448a-a21e-d78938aa4956.png)

but not 0xEDDA. I don't know which font is supposed to have the "0xEDDA" symbol and why it's not properly used.

**Comment by MartinZikmund** [comment]
@NVLudwig This is a missing glyph in our icon font compared to Segoe Fluent Icons:

![image](https://user-images.githubusercontent.com/1075116/227504999-844b50d4-e6b1-43f4-9b9b-bcc57083fe80.png)

Can these glyphs be added to the icon font please?

**Comment by NVLudwig** [comment]
Done

**Comment by Youssef1313** [comment]
I'll re-test after https://github.com/unoplatform/uno.fonts/pull/30 is merged and published to NuGet.
