### ISSUE TITLE
Migrate Uno.UI to use AOT for WebAssembly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#118]
This issue is present for tracking the performance of Uno.UI on WebAssembly, linking related issues in https://github.com/mono/mono and https://github.com/nventive/Uno.Wasm.Bootstrap.

**Comment by jeromelaban** [comment]
Adding https://github.com/mono/mono/issues/9825 as a reference.

**Comment by jeromelaban** [comment]
Last update: https://gitter.im/aspnet/Blazor?at=5b60b09f20d248394f6c6e02

**Comment by jeromelaban** [comment]
AOT progress from the mono team: https://github.com/mono/mono/issues/10222

**Comment by zipswich** [comment]
Any insider news or rumor on this?  I am increasingly anxious.

**Comment by jeromelaban** [comment]
AOT is available in Uno in recent builds of the Uno bootstrapper.
