### ISSUE TITLE
Avoid `uno-fluentui-assets.ttf` in templates and use uno.fonts.fluent NuGet package instead

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11801]
### Current behavior

(Example) https://github.com/unoplatform/uno/tree/9f57900f861035b04c217f3f7a45f7c974d1de42/src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Mobile/iOS/Resources/Fonts

### Expected behavior

Use the NuGet package instead

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
cc @MartinZikmund

**Comment by jeromelaban** [comment]
This particular template is legacy and only used internally for regression testing, and is not available to end developers anymore.
