### ISSUE TITLE
[Playground][Wasm]-TreeView Data Binding- Tree view is improper, displaying item randomly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11821]
### Current behavior

https://user-images.githubusercontent.com/74563602/228112020-fdc29ed2-c346-48cb-931f-f79d32e0d77f.mp4

https://user-images.githubusercontent.com/74563602/228114125-3c251880-ef56-42a6-a73a-06828b43980f.mp4

https://user-images.githubusercontent.com/74563602/228114317-0aaf8315-baac-4224-bad2-530be6fc8ca0.mp4

### Expected behavior

The Treeview item should display properly.

### How to reproduce it (as minimally and precisely as possible)

Visit https://playgroundcanary.z19.web.core.windows.net/#passwordbox
Go to the Snippets Listview.
Click on the 'TreeView Data Binding' snippets option.
Click on all down arrow sign the Tree View randomly multiple times.
Observe that all the list Item randomly display, sometime it opens on other item list, sometime the list is not opening.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
This issue is caused by https://github.com/unoplatform/uno/pull/10281 (/cc @Xiaoy312) I'll look it up further.

**Comment by sakshi173** [comment]
@jeromelaban, I verified Issue is fixed for both NPE and Playground.
