### ISSUE TITLE
DataContext set to Null when launching Flyout

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#11835]
### Current behavior

Launching a flyout using ShowAt(targetElement) causes the DataContext on targetElement to be set to null

### Expected behavior

DataContext on targetElement shouldn't be altered (which is the case on Windows)

### How to reproduce it (as minimally and precisely as possible)

[FlyoutSampel.zip](https://github.com/unoplatform/uno/files/11097934/FlyoutSampel.zip)

Steps:
- Add view model to Page (eg record MainViewModel(string ButtonTitle) )
- Add a Button to page with content data bound (eg Content="{Binding ButtonTitle}" )
- Add click event handler for button that creates and shows flyout (eg new Flyout().ShowAt(button))
- Button data context will be set to null and the Content will be empty after pressing the button

### Works on UWP/WinUI

None

### NuGet package version(s)

4.8.15 (blank template)

### Affected platforms

WebAssembly, Android, Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### Anything else we need to know?

- Not tested on ios but would assume it probably has same issue
- Datacontext is **not** changed on Windows

**Comment by FrozDark** [comment]
Possible related https://github.com/unoplatform/uno/issues/11647
