### ISSUE TITLE
[WASM] CalendarView.SelectedDates not working

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#11830]
### Current behavior

Please see attached repo (I also left some comments in sources): the selected date would not been seen/selected on WASM. 

[CalendarView.zip](https://github.com/unoplatform/uno/files/11092673/CalendarView.zip)

### Expected behavior

WASM should work as WindowsAppSDK

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by DierkDroth** [comment]
@TopProgrammer77 @dr1rrb unforunately the fix is not working. Even worse: the latest UNO dev bits block the browser completely, it's not even responding to F12.
What am I missing?

Here is the updated repo:
[CalendarView.zip](https://github.com/unoplatform/uno/files/11397807/CalendarView.zip)

**Comment by TopProgrammer77** [comment]
Hi, @jeromelaban . I tested the solution which @DierkDroth uploaded but It worked well on my PC. But I also checked how it works on @DierkDroth 's side but it didn't work. Is the behavior different depending on the platform (win 10 and win 11) or Visual Studio version?

**Comment by jeromelaban** [comment]
@TopProgrammer77 I do not know. In general, with the browser, the OS does not matter and the difference is likely be coming from something else.

**Comment by TopProgrammer77** [comment]
Hi, @jeromelaban, @dr1rrb 
I tested on Uno.WinUI 4.9.0-dev.861 but failed.
Could you let me know the version of Uno.WinUI my pull request merged in?

**Comment by jeromelaban** [comment]
The PR updates are in 4.9.0-dev.861 and later, see here: https://dev.azure.com/uno-platform/Uno%20Platform/_build?definitionId=5&_a=summary&branchFilter=1446%2C1446%2C1446

**Comment by Youssef1313** [comment]
I tested on latest master and the sample page completely doesn't render.

There is probably an exception happened somewhere. I'll take a look.

**Comment by TopProgrammer77** [comment]
@DierkDroth said when CalendarView is rendered the CPU usage is increased. I hope this is helpful for you.

**Comment by DierkDroth** [comment]
@Youssef1313 glad you nailed it! Looking forward the fix and the next build after...

**Comment by DierkDroth** [comment]
Thanks guys. Looking forward to test this with the next build...
