### ISSUE TITLE
SamplesApp fails to run locally on Wasm

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#11853]
### Current behavior

I'm not able to run SamplesApp on Wasm, VS shows this:

 
![image](https://user-images.githubusercontent.com/31348972/228868319-9778130c-64b4-4b40-acec-6e360993f5c3.png)

And in the console window I see this crash:

![image](https://user-images.githubusercontent.com/31348972/228868515-664392d7-d221-402a-861f-08131dbd9c99.png)

This must have started with https://github.com/unoplatform/uno/pull/6906, but I don't see why it should fail on Wasm.

@jeromelaban @ebariche 

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
@ebariche It was a new code I introduced in #6909, but I don't see why it doesn't work (besides why it wasn't detected in CI)

**Comment by ebariche** [comment]
Maybe https://github.com/unoplatform/uno/pull/11838 ?

**Comment by roxk** [comment]
I can build the Sample App in WASM with commit f0110d6, VS2022 17.5.3.

**Comment by Youssef1313** [comment]
@roxk It can build, but are you able to run?

**Comment by Youssef1313** [comment]
The commit you mentioned doesn't actually have the code where I see the crash. So it's expected to run for this commit

**Comment by roxk** [comment]
My bad, thought my commit is recent enough. But yeah I could build and run on that commit.
