### ISSUE TITLE
Android sample app fails to build with VS 16.2 Preview 3

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#1186]
## Current behavior

Build fails with this error:

```
1>Assets\LockScreenLogo.scale-200.png : error APT0000: Invalid file name: It must contain only [^a-zA-Z0-9_.]+.
```

## Expected behavior

The build does not fail. This will be fixed once https://github.com/xamarin/xamarin-android/pull/3327 is fixed.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.2 Pre 3)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Closing this out and opening up an inverse issue to remind us to re-enable when VSWIN has shipped that fix.

**Comment by ghuntley** [comment]
Closing this out and opening up an inverse issue to remind us to re-enable when VSWIN has shipped that fix.
