### ISSUE TITLE
[Droid] QueryUriSupportAsync returns basic website link as NotSupported

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#11862]
### Current behavior

When I use the QueryUriSupportAsync on Android and put some website like (like https://platform.uno) whenQueryUriSupportAsync returns NotSupported. This issue is not present on any other platforms I have tested (Windows, WASM, Skia).

### Expected behavior

The QueryUriSupportAsync should return Supported as the Launcher API works without any problem - it opens the browser and the desired website. 

### How to reproduce it (as minimally and precisely as possible)

https://github.com/morning4coffe-dev/uno-platform-testing/tree/doti/querysupportasync-droid-bug

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by Youssef1313** [comment]
This is interesting. There is a runtime test already which runs on Android for the exact same scenario:

https://github.com/unoplatform/uno/blob/3da1a742d740f8db0a6e78bfe34dfd937a62ce89/src/Uno.UI.RuntimeTests/Tests/Windows_System/Given_Launcher.cs#L35-L43

**Comment by Youssef1313** [comment]
@morning4coffe-dev Which Android version are you running against? Can you try on Android 9 and see if it works or not, as CI is supposed to be on Android 9 AFAIK.

Knowing whether this issue is dependent on Android version can help

**Comment by morning4coffe-dev** [comment]
@Youssef1313 Sure! I have tested this on Android 12 and 13.

**Comment by morning4coffe-dev** [comment]
Update: I have tested it on Android 9 and it works as intended. So this seems like an issue of the newer versions of Android.

**Comment by MartinZikmund** [comment]
@morning4coffe-dev wanna try to fix this one? 😉

**Comment by morning4coffe-dev** [comment]
From quite thorough research on this there was a change to permissions on Android. The best possible solution is just to add info about the new requirements to our documentation. Another would be to use a possible bug where instead of canLaunch try to launch the link and then catch the error.
