### ISSUE TITLE
APT2260: resource drawable/splash_screen .. not found.

### ISSUE THREAD

**Issue by cmonto** [unoplatform/uno#11875]
### Current behavior

In projects created from new uno platform 4.8 template, randomly getting APT2260 in Android. The way to reproduce in my machine is to run windows head in 'Debug' 'Any Platform' and after that switch to Mobile head and try to debug Android app in 'Debug' 'Any Platform' - the deployment to emulator fails with message "There were deployment errors. Continue?"

### Expected behavior

Project should compile and run.

### How to reproduce it (as minimally and precisely as possible)

[UnoApp1.zip](https://github.com/unoplatform/uno/files/11131788/UnoApp1.zip)

### Workaround

Clean after switching to mobile head and then build and debug.

### Works on UWP/WinUI

None

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.5.3

**Comment by Youssef1313** [comment]
Can you update to latest uno -dev packages?

**Comment by Youssef1313** [comment]
For reference, https://github.com/unoplatform/uno/pull/11860 should have fixed this.

**Comment by MartinZikmund** [comment]
Closing as fixed, feel free to reopen if happens again
