### ISSUE TITLE
Lock on web page navigation from WASM app

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#11871]
### Current behavior

In WASM when navigating to an external web page either programmatically or via a hyperlink the app becomes frozen and will not respond to further inputs. Sometimes after a new build the navigation will work twice but not more than that.

This does not happen in Windows, Android or iOS

### Expected behavior

After closing the web page navigated to, the app should be responsive to user input

### How to reproduce it (as minimally and precisely as possible)

A sample project can be found here
https://github.com/BrianDT/UnoWebNavigationIssue.git

The sample app has one button and one hyperlink, navigate by either, close the web page navigated to and try and navigate again.

### Workaround

None found

### Works on UWP/WinUI

None

### NuGet package version(s)

Uno 4.8.15

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.5.3

**Comment by jeromelaban** [comment]
I've tried to reproduce with the playground, and I'm not able to https://playground.platform.uno/#d47c8ad1.

What you do mean by not responsive to user input? What happens when you resize the browser window? if the content resizes properly, the app is not frozen but is doing something else.

**Comment by BrianDT** [comment]
I agree the issue does not seem to occur in the playground.

When the issue occurs the content does not resize properly.

After some further investigation the issue seems only to occur when running from Visual Studio initiated from the Start button. It does not happen if the Start without debugging button is used. It makes no difference if the build is a Debug or Release build.

**Comment by jeromelaban** [comment]
Interesting. This could be a debugger issue.

**Comment by BrianDT** [comment]
Sample updated to Uno 5.2.175
Confirmed Resolved

**Comment by jeromelaban** [comment]
Thanks for the update!
