### ISSUE TITLE
[WASM/Skia] `AutoSuggestBox` scroll doesn't follow selected item 

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#11876]
### Current behavior

When using arrows to navigate through AutoSuggestBox's suggested items the scroll does not follow the selected item. 

https://user-images.githubusercontent.com/78549750/229382764-943c4b0f-2440-4b73-8f5c-99fd3dd2632a.mp4

### Expected behavior

The scroll should follow the selected item as it does on UWP.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

WebAssembly, Skia

**Comment by ramezgerges** [comment]
Pretty sure this is the same problem as #12964
