### ISSUE TITLE
Add support for Windows.Storage.FileIO and Windows.Storage.StorageFile

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1187]
## What would you like to be added:

- https://docs.microsoft.com/en-us/uwp/api/windows.storage.fileio
- https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile

- https://github.com/unoplatform/uno/blob/master/src/Uno.UWP/Generated/3.0.0.0/Windows.Storage/FileIO.cs
- https://github.com/unoplatform/uno/blob/master/src/Uno.UWP/Generated/3.0.0.0/Windows.Storage/StorageFile.cs

## Why is this needed:

https://gitter.im/uno-platform/Lobby?at=5d1dc6f326206b667c88f970

## For which Platform:

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows

## Anything else we need to know?

The main thing to keep in mind is how iOS and Android behave differently related to file-system sandboxing aka "special folders". The Storage APIs that return Paths are implemented, it's only the APIs that do access the files themselves that are not, mainly because System.IO does it properly cross platform. The only part that is currently implemented is the ability to open a file, then transform it from an IRandomAccessStream to a System.IO.Stream

**Comment by MartinZikmund** [comment]
I'd love to take a look at this, although after 19th July, after I hand out my master thesis :-D .

**Comment by MartinZikmund** [comment]
This should be fairly complete now, feel free to open additional issues for specific features as needed :-) .
