### ISSUE TITLE
New project does not have for Windows the Deploy checked

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#11872]
### Current behavior

![image](https://user-images.githubusercontent.com/1608424/229305608-628f972c-4d9d-42da-ae72-53b20ca55d62.png)

Visual Studio does not start the debug session

### Expected behavior

Debugging app after the deployment
![image](https://user-images.githubusercontent.com/1608424/229305664-d0086ec5-557a-432e-9db5-bf681f4691ac.png)

### How to reproduce it (as minimally and precisely as possible)

New wizard, select everything as default options

### Works on UWP/WinUI

None

### Affected platforms

Windows

### IDE

Visual Studio 2022

**Comment by MartinZikmund** [comment]
Great catch!

**Comment by nickrandolph** [comment]
This has been fixed in next version of the wizard - it should be set by default in the current release but if the post-creation tasks get interrupted (eg by a build) Windows won't get set as deployable.
