### ISSUE TITLE
ENHANCEMENT: Uno Platform project templates VisualStudio Extension for VisualStudio for ARM

### ISSUE THREAD

**Issue by baskren** [unoplatform/uno#11888]
## What would you like to be added:

Uno Platform project templates VisualStudio Extension for VisualStudio for ARM

## Why is this needed:

OK, this is a want, not a need.  For the last couple of months, I've been using a M2 MBP running VisualStudio for ARM in Windows for ARM in a Parallels VM [now that this configuration is officially supported by Microsoft](https://support.microsoft.com/en-us/windows/options-for-using-windows-11-with-mac-computers-with-apple-m1-and-m2-chips-cd15fd62-9b34-4b78-b0bc-121baa3c568c).  IT IS AWESOME!  For example Windows (UWP or WinUI) app build times are much at least 2x faster than they were in bootcamp on my fully configured 16" i9 2020 MBP - and the fan isn't running all the time.

So, for right now, every new project I create, I have to do a `dotnet new unoapp ...` from the command line.  Which is a bummer because the new Uno Platform project template system is very awesome.  If I want that level of control over the new project creation experience, then I have to dust off my 6 year old i5 HP laptop.

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [X] Solution Templates

## Anything else we need to know?

1. How to port templates to ARM: https://devblogs.microsoft.com/visualstudio/now-introducing-arm64-support-for-vs-extensions/
2. You guys are awesome and Uno is a super platform!
3. I'd do a pull request for this but I just wasn't sure I was looking in the right places (for the location of the project templates VS extension).   After 10 minutes, I decided it might be faster to contact you and ask for some help - if you could to point me in the right direction, I'd be happy to try!

**Comment by jeromelaban** [comment]
Thanks for offering to help! The code for the Wizard is currently closed source, so we'll take a look on our end. Thanks for the links !

**Comment by queequac** [comment]
I am also owner of a Windows Dev Kit 2023 who could not find the Uno extension for ARM64.

Quick work around for everyone:
(1) Rename the VSIX to ZIP, extract the whole content
(2) Open extension.vsixmanifest in an editor of your choice. Remove both occurences of `<ProductArchitecture>amd64</ProductArchitecture>`. This will make the extension installable on any architecture. (Alternatively you could most likely add `<ProductArchitecture>amd64</ProductArchitecture>`, shouldn't matter)
(3) Rezip and rename back to VSIX extension.

Now I am able to install the extension. And it also runs the wizard without any exceptions or problems and creates projects.
Obviously the extension and the contained wizard are fine with being emulated and updating the manifest does the job. :)

Best, Roland

**Comment by jeromelaban** [comment]
Thanks for the update, this will be useful!

**Comment by baskren** [comment]
AWESOME!!!  IT WORKS!!

Thanks @queequac !

**Comment by rfabre** [comment]
Thanks @queequac !
I will reuse this trick.
