### ISSUE TITLE
ENHANCEMENT: .NET6 and .NET7 supported by Uno.WinUI.Maps 

### ISSUE THREAD

**Issue by baskren** [unoplatform/uno#11908]
## What would you like to be added:

.NET7 support by Uno.WinUI.Maps 

## Why is this needed:

Can't use Uno.WinUI.Maps with Uno.WinUI projects that target .NET7

## For which Platform:

- [ ] WebAssembly
- [x] Android
- [x] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

Nuget.org Dependencies:
<img width="886" alt="image" src="https://user-images.githubusercontent.com/2528888/230112501-d2cc1d22-9ee5-4621-890f-f55433c25587.png">

Nuget.org Frameworks:
<img width="945" alt="image" src="https://user-images.githubusercontent.com/2528888/230112792-1e212e6c-5b39-40e2-b2eb-c34590222b4a.png">

`dotnet restore` results:
```
Package Uno.WinUI.Maps 4.8.15 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package Uno.WinUI.Maps 4.8.15 supports:
  - monoandroid12.0 (MonoAndroid,Version=v12.0)
  - monoandroid13.0 (MonoAndroid,Version=v13.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
Package Uno.WinUI.Maps 4.8.15 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package Uno.WinUI.Maps 4.8.15 supports:
  - monoandroid12.0 (MonoAndroid,Version=v12.0)
  - monoandroid13.0 (MonoAndroid,Version=v13.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
Package Uno.WinUI.Maps 4.8.15 is not compatible with net7.0-ios16.1 (.NETCoreApp,Version=v7.0). Package Uno.WinUI.Maps 4.8.15 supports:
  - monoandroid12.0 (MonoAndroid,Version=v12.0)
  - monoandroid13.0 (MonoAndroid,Version=v13.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
Package Uno.WinUI.Maps 4.8.15 is not compatible with net7.0-ios16.1 (.NETCoreApp,Version=v7.0). Package Uno.WinUI.Maps 4.8.15 supports:
  - monoandroid12.0 (MonoAndroid,Version=v12.0)
  - monoandroid13.0 (MonoAndroid,Version=v13.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
Restore failed.
```

**Comment by jeromelaban** [comment]
Thanks for the report! We're tracking the issue here: https://github.com/unoplatform/uno/issues/67. At this time, using MapsUI is a possible choice.
