### ISSUE TITLE
Toolkit docs wrong Improve this page link

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#11916]
## On which page?
https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls/AutoLayoutControl.html?q=autolayout
and
All pages under Toolkit

## What's wrong?
The Improve this page link takes you to a currently not existing page on GitHub.
<img width="618" alt="image" src="https://user-images.githubusercontent.com/78549750/230381590-89fc7fe2-1c36-4249-9293-e4dfe09db014.png">

**Comment by MartinZikmund** [comment]
Probably for @kazo0

**Comment by kazo0** [comment]
Looks like we need to change the default branch in the config to `main` :)
