### ISSUE TITLE
[WASM] Images randomly disappear

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#11920]
## Current behavior
<img width="868" alt="image" src="https://user-images.githubusercontent.com/78549750/230379947-2044ef62-bea9-40a4-9563-862e893d04cb.png">

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
The console does not show anything related to images not loading.

**Comment by agneszitte** [comment]
@jeromelaban I am currently not able to reproduce this issue locally with the latest package versions or even using while testing the canary for Gallery
@sakshi173 Let me know if you are able to reproduce the issue on your side

@morning4coffe-dev let us know if you are still able to reproduce the issue, please
And if so:
- What browser/version are you using?
- Do you have any additional repro steps/info that you can share with us?
- Are you using https://gallery.platform.uno/ to replicate the issue or building Uno Gallery locally (if so what version of Uno.UI are you using please?)

Here are the details for the browser I used for my tests:
- **Google Chrome**: Version 112.0.5615.138 (Official Build) (64-bit)
- **Google Chrome Canary**: Version 115.0.5739.0 (Official Build) canary (64-bit)
- **Edge**: Version 112.0.1722.64 (Official Build) (64-bit)
- **Firefox**: Version 112.0.2 (Official Build) (64-bit)

**Comment by sakshi173** [comment]
@agneszitte, I tried to reproduce this bug  and not able to reproduce it. Its working for me. Below is the screenshot , its working fine.
![Image correct](https://user-images.githubusercontent.com/74563602/235256581-f2c1dd9e-6476-4ef9-873e-0f53dcb64824.png)

**Comment by jeromelaban** [comment]
Let's close then.
