### ISSUE TITLE
Authenticode Signing aka Digital Signatures for Assemblies

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1193]
## What would you like to be added:

![image](https://user-images.githubusercontent.com/127353/60727117-7a6b6680-9f80-11e9-842e-923edfb173d3.png)

## Why is this needed:

- Certainty that assemblies used in an application were produced by the project CI
- Certainty that assemblies used in an application have not been tampered with

nb: This is completely different to strongnaming, please do not discuss strongnaming in this issue.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

## Anything else we need to know?

- https://github.com/dotnet/SignService

**Comment by ghuntley** [comment]
Looks like it is already implemented, nice work @jeromelaban!

![image](https://user-images.githubusercontent.com/127353/60727544-7e4bb880-9f81-11e9-8a48-95457047fcff.png)

I'll keep this issue open as it needs to be documented on the website.

**Comment by jeromelaban** [comment]
Binaries are now signed
