### ISSUE TITLE
`XamlRoot.RasterizationScale` is not using the proper value

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#11944]
`XamlRoot.RasterizationScale ` should not be using `RawPixelsPerViewPixel` but rather `LogicalDpi`, where on android both do not return the same value.

https://github.com/unoplatform/uno/blame/c4fbd49bfd09ed05de653ae98c545c49f9002ae1/src/Uno.UI/UI/Xaml/XamlRoot.cs#L93

@MartinZikmund you wrote that property originally, do you remember why you chose that `DisplayInformation` property ?

---

This seems to return the Pixels per View Pixel:
`(float)DisplayInformation.GetForCurrentView().ResolutionScale / 100.0f;`

This seems not to work:
`(float)DisplayInformation.GetForCurrentView().RawPixelsPerViewPixel;`

_Originally posted by @inforithmics in https://github.com/unoplatform/uno/discussions/11943#discussioncomment-5581569_

**Comment by Youssef1313** [comment]
> @MartinZikmund you wrote that property originally, do you remember why you chose that DisplayInformation property ?

@jeromelaban I think he didn't 😄 https://github.com/unoplatform/uno/commit/8ff10bf2346ea713162754fd62cbd9061776c3bf#diff-a20b40e66ac03b21a752da6b4fd33edc083920eebc0c9a55b883292b4548e64a

**Comment by Youssef1313** [comment]
It was originally mentioned in https://github.com/unoplatform/uno/issues/7944

**Comment by pauldendulk** [comment]
Some input. I don't have all the background knowledge but my guess is that this is a bug in the API 33 implementation (in either Uno or SkiaSharp). A Pixel 5 has a XamlRoot.RasterizationScale of 2.75 on API 30 (in Uno but also in Xamarin.Android). The same Pixel 5 has a XamlRoot.RasterizationScale of 2.8135 on API 33 (on Uno, but on Xamarin.Android it is still 2.75). To investigate this I would figure out what causes the difference. 

Then there seems to be another issue (or other symptom of the same issue) and that is that the scale does not have the effect it should. We work with IgnorePixelScaling, so we scale with 2.8125, but that scale is too large for the screen, 2.75 is still too large, 2.0 seems to work out correctly, but I see no reason why it should be 2.0.

**Comment by pauldendulk** [comment]
There is no XamlRoot.LogicalDpi. 

This is in API 33:
![image](https://user-images.githubusercontent.com/963462/231539919-94a7bec0-44ca-46df-9dd7-480f640d4020.png)

This is on API 31:
![image](https://user-images.githubusercontent.com/963462/231540085-ac6725dd-a731-400c-a68c-e711f2aa6b5b.png)

There is a LogicalDpi for DisplayInformation

This is on API 33:
![image](https://user-images.githubusercontent.com/963462/231541062-d80135f9-6234-478f-9a3a-8906b70a861a.png)

This is on API 31:
![image](https://user-images.githubusercontent.com/963462/231543119-9df17188-494f-4d36-8d19-4fe9412a2ba4.png)

**Comment by carldebilly** [comment]
> Then there seems to be another issue (or other symptom of the same issue) and that is that the scale does not have the effect it should. We work with IgnorePixelScaling, so we scale with 2.8125, but that scale is too large for the screen, 2.75 is still too large, 2.0 seems to work out correctly, but I see no reason why it should be 2.0.

@pauldendulk: The reason why it was 2.0 is very very simple: the result of a calculation were using integer instead of a float, turning 2.xx into 2.0 ;-)

**Comment by pauldendulk** [comment]
@carldebilly ah, so it really is explained by the api version. Thanks for the clear explanation and getting to the bottom of this!

**Comment by pauldendulk** [comment]
I can confirm this is fixed with 4.9.0-dev.580. It also does not break the workaround, although after the release we will revert back to `XamlRoot.RasterizationScale` because that seems to be what is supposed to be used on WinUI. Apart from `Height` most other values are the same now:
 
API 33 on Pixel 5:
![image](https://user-images.githubusercontent.com/963462/232426403-44c986cb-068b-462d-ab54-8569e144f5a7.png)

API 31 on Pixel 5:
![image](https://user-images.githubusercontent.com/963462/232427050-b898dd9b-1042-42a2-8aa9-ff43a4fc502c.png)
