### ISSUE TITLE
Create New Project Wizard - adds Tests even if unchecked

### ISSUE THREAD

**Issue by get-flat** [unoplatform/uno#11964]
### Current behavior

Startup type: Default - Customize

(Both Tests and UITests unchecked)
![Bez tytułu](https://user-images.githubusercontent.com/74671895/231721976-88e1199e-de9f-42c2-816f-2a16bde4e9e3.png)

Solution view:
![folders](https://user-images.githubusercontent.com/74671895/231722331-1095fbd6-91df-49bf-a4ee-bba2d35dc9eb.png)

### Expected behavior

It would be cool (if possible of course) if the Tests projects weren't added.

### Works on UWP/WinUI

None

### Affected platforms

Solution Templates

### IDE

Visual Studio 2022

### IDE version

17.5.4

### Relevant plugins

Extensions: Uno Platform 4.8.9.10

**Comment by nickrandolph** [comment]
This has been fixed already in the next release of the wizard.
