### ISSUE TITLE
[Gallery][iOS]AutoSuggestBox- The searched word is not able to select and not displaying for the 'Default' section.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11961]
### Current behavior

https://user-images.githubusercontent.com/74563602/231643628-93bd3582-38f0-4617-8cb4-57861d2ba9bc.MP4

### Expected behavior

https://user-images.githubusercontent.com/74563602/231644464-6aa74947-ed2a-46d3-b23a-ff2b5fc9f50e.mp4

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "AutoSuggestBox" from the "UI Component" list.
4. Type any component related letters like 'Ch' for default section.
5. The component list related to word display in the dropdown.
6. Try to click on any word from the displayed list for example 'Checkbox'.
7. Notice that displayed word is not able to choose and nothing is displaying in the searched box.

### Works on UWP/WinUI

None

### Affected platforms

iOS

**Comment by Soap-141** [comment]
Having the same issue in one of our applications.
