### ISSUE TITLE
Custom splash screen not working in UNO

### ISSUE THREAD

**Issue by LiftTrack** [unoplatform/uno#11968]
### Current behavior

I am trying to use a custom splash screen. I have implemented the solution according to your shared documentation.
Attaching the source code, Please have a look and provide me the solution.

[SampleCode.zip](https://github.com/unoplatform/uno/files/11222955/SampleCode.zip)
![SplashScreenIssue](https://user-images.githubusercontent.com/119324311/231784172-ebdb7823-cd6a-4dcd-abc3-658978dbbc59.png)
![CommentedCode](https://user-images.githubusercontent.com/119324311/231784185-6d62b012-ac0b-4058-884a-a442f46d8216.png)

### Expected behavior

It should work according.

### Works on UWP/WinUI

None

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.5.0

**Comment by pictos** [comment]
Hey @LiftTrack, there's an issue with the docs that will fix right now. The rest of the documentation around the SplashScreen is under the `Shared project` tab, you find it [here](https://platform.uno/docs/articles/external/uno.resizetizer/doc/using-uno-resizetizer.html?tabs=sharedproject).

Follow the instructions after 
> Next, some adjustments are needed on Android, Windows, and iOS. Let's start with Android.

**Comment by LiftTrack** [comment]
Hi,

1. Templates are not building. It is throwing an error.
2. I tried to use the code by creating another sample but it is not working.
   attaching screenshot and code for help. Please use this code and let me know my mistake. 
 
![SplasScreen_17April](https://user-images.gi
[SplashScreen.zip](https://github.com/unoplatform/uno/files/11247423/SplashScreen.zip)
thubusercontent.com/119324311/232414646-50acb75f-44b7-4e8e-80af-b9ea89fe2a11.png)

**Comment by LiftTrack** [comment]
Hi,

Please find the attachment.
Source Code:-
[SplashScreen.zip](https://github.com/unoplatform/uno/files/11247446/SplashScreen.zip)

Image :-
![SplasScreen_Implementation](https://user-images.githubusercontent.com/119324311/232416444-9c040b9f-9be4-4c0d-b07e-cf14ad6b360b.png)

**Comment by jeromelaban** [comment]
Can you provide a [binlog of the build error](https://platform.uno/docs/articles/uno-builds-troubleshooting.html), it will help us troubleshoot further. Thanks!

**Comment by pictos** [comment]
@LiftTrack as I mentioned the rest of the instructions to use the Splash screen generated by Resizetizer are on the `Shared project tab`, on the screenshot below you can see what you should add/modify on your `Style.xml` file.

<img width="836" alt="Screenshot 2023-04-17 at 10 55 10" src="https://user-images.githubusercontent.com/20712372/232505432-fed21377-92a5-4724-8c46-8fcc01cb4e26.png">

**Comment by LiftTrack** [comment]
Hi,

Please, look into my shared source code. If I follow your suggestions then I am receiving the following error, when I run my source code.

Attaching screenshot for help

![SplashScreenError](https://user-images.githubusercontent.com/119324311/232509301-24e6ff05-8c7a-4780-9ad9-c56710b09e6c.png)

**Comment by pictos** [comment]
@LiftTrack I'll try the code on my end and return to you asap

**Comment by pictos** [comment]
@LiftTrack , first of all, your project doesn't have the `Uno.Resizetizer` package installed as you can see in the screenshot below:
![image](https://user-images.githubusercontent.com/20712372/232516674-53996ee2-cfac-4319-86d9-e89f9356f22e.png)

Did you create this project using the latest version of our template? Because if so the Resizetizer should be added there.

So, the errors that you get aren't related to Resizeter but with android, maybe the values aren't correct (?)

After adding the package and adding the info on the correct places (you can find those on our docs) I could make it work.

> Note
> There's an situation that when the debugger is attached the android will not show the splash screen, but if you start the app from the mobile device the splash screen will be shown.

[SplashScreen_updated.zip](https://github.com/unoplatform/uno/files/11251477/SplashScreen_updated.zip)

**Comment by LiftTrack** [comment]
Hi,

I installed the latest UNO extension on my visual studio.
Thanks for the source code update, I have used your updated code. But still, it is not loading the splash screen. I have run this code on an emulator and on Android mobile. Please find the attachment.

https://user-images.githubusercontent.com/119324311/232536942-637eccbe-5662-4b16-acac-011bc1904b67.mp4

**Comment by pictos** [comment]
@LiftTrack, the splash screen is shown at second 16 on your video.

**Comment by LiftTrack** [comment]
Hi,


Thanks for the update. It is showing in the center of the screen. Is it possible to show a splash screen in full mobile size,  means in full-screen size according to the size of the mobile.? Also if I want to use a **video file** as a splash screen then how can it be implemented? 


Thanks
Sanjay

**Comment by LiftTrack** [comment]
Hi,

There is a problem with the splash screen, It is working in the emulator which has an Android version above 12+ but when I run it on my mobile android version is 12, not working. What should I do about it?

Please find the attachment.


https://user-images.githubusercontent.com/119324311/232722824-55033083-9d38-4ebd-997d-0a0287ae2771.mp4


https://user-images.githubusercontent.com/119324311/232722853-6f870151-aa9c-4e4f-8aca-526da51ca025.mp4

![MobileVersion](https://user-images.githubusercontent.com/119324311/232723136-5c4c0459-5a98-4b9b-a7cd-8702d5ce3b2a.png)

![EmulatorVersion](https://user-images.githubusercontent.com/119324311/232723156-b9200704-7dcc-4907-b8b8-600ddc91eef4.png)

**Comment by pictos** [comment]
@LiftTrack not sure you read or understand what I mentioned [here](https://github.com/unoplatform/uno/issues/11968#issuecomment-1511504370), as a note. When you launch your app from VS there's a chance the SplashScreen will not show, but if you start your application on your device (going to apps and tapping on your application) then the SplashScreen should be shown. If don't please let me know

**Comment by LiftTrack** [comment]
Hi,

Thanks for the update. It is showing in the center of the screen. Is it possible to show a splash screen in full mobile size, means in full-screen size according to the size of the mobile.? Also if I want to use a video file as a splash screen then how can it be implemented?

Thanks
Sanjay

**Comment by pictos** [comment]
Hey @LiftTrack, using the Resizetizer you can't provide a video as an asset, and there are a couple of platforms that don't support it, you need to look at each one and implement it manually. The splash screen is full-screen size, but on android for example, the image is presented in the center of the screen, following google guide lines. If you need something more specific you probably may want to implement it by yourself and per platform

**Comment by pictos** [comment]
Since we solved the problem that you raised when you opened this issue. I'll close it (:
