### ISSUE TITLE
VisualStateGroup "CommonStates" does not work properly for ToggleButton

### ISSUE THREAD

**Issue by GRDias** [unoplatform/uno#11979]
### Current behavior

Unfortunately, when you design a ToggleButton, the common state doesn't "reset" itself like it does under native UWP or WinUI 3, so it's very difficult to design such controls.

### Expected behavior

Behavior like native UWP respectively WinUI 3.

### How to reproduce it (as minimally and precisely as possible)

http://playground.platform.uno/#5a88ab17
This code works properly on UWP and WinUI 3 but not on Uno.WinUI

### Workaround

None found so far

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Skia (GTK on Linux/macOS/Windows), Windows

**Comment by Youssef1313** [comment]
### Initial investigation

Scenario:

- Start with normal state
- Move mouse over to get into pointer over state
- Press to get into pressed state
- Release to get into checked pointer over state

What happens in reality:

- Normal state is okay
- When we go to PointerOver state, we call stop on the `DoubleAnimationUsingKeyFrames` associated with `normal_` TextBlock, then Begin and Play on the one associated with `pointerOver_`
- When we go to pressed state, we call stop on the `DoubleAnimationUsingKeyFrames` associated with `pointerOver_`, then Begin and Play on the one associated with `pressed_`
- Now, when we release and we try to go into `PointerOver` followed directly by going to `CheckedPointerOver`
    - When we go to PointerOver, we Stop `pressed_` and Begin (but not Play) PointerOver
    - When we go to CheckedPointerOver, we stop `pointerOver_`, begin `checkedPO_`, play `pointerOver_`, then play `checkedPO_`, and then we appear to be both in CheckedPointerOver and PointerOver states.
