### ISSUE TITLE
Update to latest WindowsAppSDK 1.3 corrupts the solution

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#11972]
### Current behavior

After updating to latest WindowAppSDK I now get errors below when trying to build my project.
I'm not sure where to start looking? Is this UNO? Is this Microsoft?

```
5>C:\Users\dierk\.nuget\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(537,17): error MSB4064: The "PrecompiledHeaderFile" parameter is not supported by the "CompileXaml" task loaded from assembly: Microsoft.UI.Xaml.Markup.Compiler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b from the path: C:\Users\dierk\.nuget\packages\microsoft.windowsappsdk\1.2.230313.1\tools\net472\Microsoft.UI.Xaml.Markup.Compiler.dll. Verify that the parameter exists on the task, the <UsingTask> points to the correct assembly, and it is a settable public instance property.
5>C:\Users\dierk\.nuget\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(504,9): error MSB4063: The "CompileXaml" task could not be initialized with its input parameters.
```

### Works on UWP/WinUI

None

**Comment by nickrandolph** [comment]
@DierkDroth I've seen a couple of issues recently where the WinAppSdk nuget package has been corrupted. Try removing the folder from the nuget cache (ie this folder C:\Users\dierk\.nuget\packages\microsoft.windowsappsdk\1.3.230331000) and forcing a rebuild.

**Comment by DierkDroth** [comment]
@nickrandolph thanks for this suggestion. Unfortunately it did not help ... issue persists :-(

**Comment by nickrandolph** [comment]
A couple of context questions:
- Which version of uno are you targeting
- Is this a new project, or an existing project (the relevance here is around whether you're using shared project or a class library for the main views/logic of the application)
- Is this build error only for the windows target project?

**Comment by DierkDroth** [comment]
Thanks again @nickrandolph 
- please see screenshot below (WindowsAppSDK and WASM heads only)
- solution file is > 2 years old (of course updated massively over time)
- yes

Thinking: could it be related to [this](https://github.com/unoplatform/uno/pull/11969)?

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26179242/231931941-e54060fd-7506-4905-bc88-dbec1e55cb36.png">

**Comment by Youssef1313** [comment]
I don't think https://github.com/unoplatform/uno/pull/11969 is related.

Cleaning the solution *may* help, in addition to cleaning the NuGet cache that @nickrandolph mentioned. Also try restarting Visual Studio (possible delete the `.vs` folder, just in case - I have seen cases where VS goes into a bad state solvable only by deleting `.vs` folder)


If it is still not working, we need a repro, or at least a binlog that *may* help understand what is happening.

**Comment by DierkDroth** [comment]
Thanks @Youssef1313 

Yes, I already cleared the .vs folder + NuGet cache and restarted VS -> problem persists.
Here are the binlogs. Hope, they would show what's going wrong. Thanks

[msbuild.zip](https://github.com/unoplatform/uno/files/11228756/msbuild.zip)

**Comment by Youssef1313** [comment]
@DierkDroth The `.Gui.Windows.csproj` is still referencing the older version:

```xml
<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.2.230313.1" />
```

You need to update it too.

**Comment by DierkDroth** [comment]
Stupid me :-( Sorry for the noise. Thanks @Youssef1313

**Comment by Youssef1313** [comment]
Happy to help!

**Comment by DierkDroth** [comment]
FYI (not related to the very 'issue'): Today I experienced random crashes where the external VS debugger triggered in. I did not dig into but am suspicious that there (again) is more trouble related to WebView2 (which I'm using heavily). 
Oh well ... "what's new with this version? New bugs!" ... I will try again on next WindowsAppSDK hot fix ...
