### ISSUE TITLE
[Android] Implement InternalActivate to delay first draw of application until Activate is called

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#11974]
## What would you like to be added:

The Window class has an [InternalActivate](https://github.com/unoplatform/uno/blob/d077eaf8b9337c55c0fd9e912e65f99088a3ab9d/src/Uno.UI/UI/Xaml/Window.cs#L212) partial method which should be implemented by each platform to determine when the first draw of the window should occur. This is not implemented on Android and should be to control when the splash screen is dismissed and the first draw of the application content occurs

## Why is this needed:

Other platforms implement the InternalActivate method on the Window class in order to control the first draw of the application (eg [iOS](https://github.com/unoplatform/uno/blob/d077eaf8b9337c55c0fd9e912e65f99088a3ab9d/src/Uno.UI/UI/Xaml/Window.iOS.cs#L79-L82) and [wasm](https://github.com/unoplatform/uno/blob/d077eaf8b9337c55c0fd9e912e65f99088a3ab9d/src/Uno.UI/UI/Xaml/Window.wasm.cs#L134-L137) ) but Android does not. 

Currently Android will display the first content of the application as soon as it's available to be drawn, rather than waiting for the Activate method to be called. This means that the native splash screen will be dismissed prematurely.

## For which Platform:

- [ ] WebAssembly
- [X] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by nickrandolph** [comment]
Linking related PR: https://github.com/unoplatform/uno/pull/11864

**Comment by MartinZikmund** [comment]
Fixed for the remaining targets by https://github.com/unoplatform/uno/pull/11864
