### ISSUE TITLE
dotnet build does not work but msbuild compiles just fine

### ISSUE THREAD

**Issue by inforithmics** [unoplatform/uno#12013]
### Current behavior

1) dotnet new unoapp --name Mapsui.Samples.Uno.Winui -preset=blank -server=false

Failure: 

2) dotnet build --configuration Debug /p:Platform=x64 Mapsui.Samples.Uno.WinUI\Mapsui.Samples.Uno.WinUI.Windows\Mapsui.Samples.Uno.WinUI.Windows.csproj

```
MSB4062: The "Microsoft.Build.Packaging.Pri.Tasks.ExpandPriContent" task could not be loaded from the assembly C:\Pro
gram Files\dotnet\sdk\7.0.300-preview.23179.2\\Microsoft\VisualStudio\v17.0\AppxPackage\\Microsoft.Build.Packaging.Pri.
Tasks.dll
```

Success:
2) msbuild -p:Configuration=Debug -p:Platform=x64 Mapsui.Samples.Uno.WinUI\Mapsui.Samples.Uno.WinUI.Windows\Mapsui.Samples.Uno.WinUI.Windows.csproj

### Expected behavior

dotnet build --configuration Debug /p:Platform=x64 Mapsui.Samples.Uno.WinUI\Mapsui.Samples.Uno.WinUI.Windows\Mapsui.Samples.Uno.WinUI.Windows.csproj

works without failure.
Intrestingly the msbuild version works.

### How to reproduce it (as minimally and precisely as possible)

1) dotnet new install uno.templates
2) dotnet new unoapp --name Mapsui.Samples.Uno.Winui -preset=blank -server=false
3) dotnet build --configuration Debug /p:Platform=x64 Mapsui.Samples.Uno.WinUI\Mapsui.Samples.Uno.WinUI.Windows\Mapsui.Samples.Uno.WinUI.Windows.csproj

### Workaround

msbuild -p:Configuration=Debug -p:Platform=x64 Mapsui.Samples.Uno.WinUI\Mapsui.Samples.Uno.WinUI.Windows\Mapsui.Samples.Uno.WinUI.Windows.csproj

### Works on UWP/WinUI

No

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.8.24 (4.9 dev builds don't work too)

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

17.5

### Relevant plugins

Resharper, Github Copilot (Don't matter because it doesn't work on the commandline it works in the ide)

### Anything else we need to know?

Checkin were i applied the workaround.

https://github.com/Mapsui/Mapsui/pull/1968/commits/8c623be379d91308fa1b785c7f680612266b6604

**Comment by jeromelaban** [comment]
Thanks for the report.

This is unfortunately expected. `dotnet build` is not supported by winappsdk apps at this time: https://github.com/microsoft/WindowsAppSDK/issues/3548. You'll need to build using `msbuild` on Windows in the meantime.

**Comment by inforithmics** [comment]
Then this is a regression because the old .net 6 win app sdk Version worked with dotnet build.
