### ISSUE TITLE
.net 7.0. Image Source behaves differently when running the `{appname}.Windows.csproj (unpackaged)`

### ISSUE THREAD

**Issue by Spiix5** [unoplatform/uno#12032]
### Current behavior

If you have a xaml user control and the files (.xaml, .cs) are not kept in the root directory of the shared project (so for example /Views/TopBar.xaml and /Views/TopBar.xaml.cs) and you want to add an Image that shows a .png file from the /Assets directory of the shared project, the 'Source' property of the xaml Image tag behaves differently when running the .Windows project as opposed to the .Mobile (Android) or .Skia.Wpf projects.

The .Windows project, the Source path expects a path relative to the Topbar.xaml file, so in this case that would be ../Assets/image.png
The .Mobile (Android) and .Skia.Wpf projects expect this path to be relative to the shared project root, so Assets/image.png. As I understand, this is what the documentation says [https://platform.uno/docs/articles/features/working-with-assets.html](url) 

Example:
The project structure:
![image](https://user-images.githubusercontent.com/131491955/233735731-e521e979-a7aa-4ffb-90a4-a3efdc9067ad.png)

MainPage.xaml

<Page x:Class="SurveyApp.MainPage"
	xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	xmlns:local="using:SurveyApp"
	xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
	xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
	xmlns:views="using:SurveyApp.Views"
	mc:Ignorable="d"
	Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

	<StackPanel>
        <Image Source="Assets/image.png" Stretch="Uniform" Width="50" Height="50" HorizontalAlignment="Left" />
        <views:TopBar/>
        <TextBlock Text="Hello Uno Platform" />
	</StackPanel>
</Page>

TopBar.xaml
<UserControl
    x:Class="SurveyApp.Views.TopBar"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:SurveyApp.Views"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Height="64">

	<Grid Background="#006D5B">
		<Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto"/>
            <ColumnDefinition/>
            <ColumnDefinition Width="Auto"/>
		</Grid.ColumnDefinitions>
    
        <Border BorderThickness="1" Background="Beige" BorderBrush="Black">
            <Image Source="Assets/image.png" Stretch="Uniform" Width="50" Height="50" Grid.Column="0" />
        </Border>
		

        <Grid HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Background="AliceBlue" Grid.Column="1"/>
    </Grid>
</UserControl>

Produces the following when running with the SurveyApp.Windows as startup project
![image](https://user-images.githubusercontent.com/131491955/233736016-543b1fa2-35d6-4779-82b7-c2b92768468c.png)

And Produces the following when running with either SurveyApp.Skia.Wpf or SurveyApp.Mobile (on Android) as startup project
![image](https://user-images.githubusercontent.com/131491955/233736235-e3c21677-88c4-49a3-941e-cbae7cc824f2.png)

And when we change TopBar.xaml to this:

<UserControl
    x:Class="SurveyApp.Views.TopBar"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:SurveyApp.Views"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Height="64">

	<Grid Background="#006D5B">
		<Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto"/>
            <ColumnDefinition/>
            <ColumnDefinition Width="Auto"/>
		</Grid.ColumnDefinitions>
    
        <Border BorderThickness="1" Background="Beige" BorderBrush="Black">
            <Image Source="../Assets/image.png" Stretch="Uniform" Width="50" Height="50" Grid.Column="0" />
        </Border>
		

        <Grid HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Background="AliceBlue" Grid.Column="1"/>
    </Grid>
</UserControl>

This produces the following when running with the SurveyApp.Windows as startup project
![image](https://user-images.githubusercontent.com/131491955/233736502-0ba937f3-ff35-4183-acfb-6c05a4fcd923.png)

And Produces the following when running with either SurveyApp.Skia.Wpf or SurveyApp.Mobile (on Android) as startup project
![image](https://user-images.githubusercontent.com/131491955/233736589-67c2b92a-9d93-455e-9285-6239f3afad7b.png)

Please note that the SurveyApp.Windows was always ran as Unpacked. 

### Expected behavior

The Image Source property behaviour is the same across all target projects. Preferably relative to the project file and not the source file. So as the documentation described.

### How to reproduce it (as minimally and precisely as possible)

[SurveyApp.zip](https://github.com/unoplatform/uno/files/11299377/SurveyApp.zip)

### Workaround

- Put every control and view in the shared project root
- Making your own image loading code and binding the Image sources to properties in the code behind 
- Making plaftorm-specific versions of every control

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI.Skia.Wpf 4.8.24
Uno.WinUI 4.8.24
Uno.UniversalImageLoader 1.9.36

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

17.5.3 and 17.5.4

### Relevant plugins

I don't think any plugins are relevant to this issue.

**Comment by MartinZikmund** [comment]
I suspect this is a WinUI specific issue we have no control over, do you agree @pictos @jeromelaban ?

**Comment by jeromelaban** [comment]
Indeed, this is likely a behavior that we can't fix. Resources management from libraries for unpackaged apps is not finalized at this time, though maybe 1.4 did improve that behavior.

My guess would be this particular issue: https://github.com/microsoft/microsoft-ui-xaml/issues/7651
