### ISSUE TITLE
[Android] AnalyticsInfo DeviceFamily returns as Mobile on Tablet device

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#12045]
### Current behavior

When testing out an app on an Android Tablet (not sure about iOS) emulator the AnalyticsInfo.VersionInfo.DeviceFamily returns as Android.Mobile.

![image](https://user-images.githubusercontent.com/78549750/233869880-de4e0269-e7ae-4ee9-8f48-32e2d94714f9.png)

### How to reproduce it (as minimally and precisely as possible)

```
public bool IsMobile()
{
      var deviceFamily = AnalyticsInfo.VersionInfo.DeviceFamily;
      return deviceFamily.Contains("Mobile");
}

public bool IsTablet()
{
      var deviceFamily = AnalyticsInfo.VersionInfo.DeviceFamily;
      return deviceFamily.Contains("Tablet");
}
```

And run the app on a Tablet device.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Looks like this is a net6 specific behavior, and it is curious to see `AnalyticsInfo.VersionInfo.DeviceFamily` returning this value. Could you take a look at this property?

**Comment by Youssef1313** [comment]
https://developer.android.com/guide/topics/large-screens/support-different-screen-sizes

These will be important when fixing this.

![image](https://user-images.githubusercontent.com/31348972/234188788-34597e9e-c6ca-4acd-8a77-953fc278cc23.png)

![image](https://user-images.githubusercontent.com/31348972/234188911-7a33a3ef-dfab-49a7-9025-562d7916a513.png)
