### ISSUE TITLE
`Viewbox` does not scale `TextBox` content in edit mode under Gtk/WSL

### ISSUE THREAD

**Issue by GRDias** [unoplatform/uno#12052]
### Current behavior

Viewbox is not scaling the TextBox content in edit mode. 
Is working for Windows but not for Linux.

### Expected behavior

Viewbox scales TextBox content also in edit mode

### How to reproduce it (as minimally and precisely as possible)

Not working for Linux:
http://playground.platform.uno/#0260becf

### Works on UWP/WinUI

Yes

### Environment

Other

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. This is currently a known issue as the implementation of textbox still uses a native overlay that cannot be resized. We're tracking this in https://github.com/unoplatform/uno/issues/9417.

**Comment by MartinZikmund** [comment]
This should be quite easy to add - applying the scale transform based on the `Viewbox`

**Comment by Youssef1313** [comment]
It should be fixed now with the new TextBox, I think
