### ISSUE TITLE
Remove the implicit string cast operator for `Point`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#12067]
### Current behavior

```csharp
Point _lastPosition = new Point();
global::System.Diagnostics.Debug.WriteLine("New position " + _lastPosition);
```

Throws `System.FormatException: Input string was not in a correct format.`, because the code is trying to convert "New position" to a `Point` instance.

### Expected behavior

Should not happen.

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
@jeromelaban Ok in `master` or should be in breaking changes?

**Comment by jeromelaban** [comment]
@Youssef1313 it should be in breaking changes, as it may impact source generation (somehow).
