### ISSUE TITLE
Webview2 is not displayed when running on Android

### ISSUE THREAD

**Issue by yegor-pelykh** [unoplatform/uno#12071]
### Current behavior

Webview2 control is not displayed when running on Android.
Instead, an empty space is displayed.
This is reproduced even in the simplest project.

### Works on UWP/WinUI

Yes

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. Make sure to fill all the fields that present in the issue template, particularly the package versions.

**Comment by yegor-pelykh** [comment]
Hi @jeromelaban
Which packages exactly?
This is my first day trying to use Uno, for now I don't know what information is important.
Uno was installed today, so apparently I'm using the latest versions.
And this bug is reproduced stable, you can try it yourself.

**Comment by yegor-pelykh** [comment]
Even if in an empty project I add a line to the MainPage.xaml:
```xaml
<WebView2 Source="http://google.com" />
```
and then build for Android and run it on the device / emulator, then it will be reproduced.

Empty space instead of WebView2 control.

**Comment by jeromelaban** [comment]
Thanks. This feature is not yet available in Uno 4.8, the version Uno.WinUI package version in your csproj. We'll be releasing support for WebView2 in Uno 4.9 (https://github.com/unoplatform/uno/pull/10794).

**Comment by jeromelaban** [comment]
There isn't, no, since the support is already merged for the next Uno version. You can try by using the experimental packages, if you'd like.

**Comment by yegor-pelykh** [comment]
Ah, it's clear now, thanks.

**Comment by yegor-pelykh** [comment]
@jeromelaban, just few additional questions:
1) When will the next version be released (with WebView2)?
2) How to use experimental packages? Is it enough to just upgrade the nuget packages to prerelease? Or is something else required?
