### ISSUE TITLE
[WASM] TreeView drag/drop not working

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#12079]
### Current behavior

Please see attached repo:
- expand root node '111'
- try to drag sub-node '111-a' e.g. to root node '333'

-> you'll get a 'forbidden' icon and dragging is not working

Is that expected?

[TreeViewDrag.zip](https://github.com/unoplatform/uno/files/11329125/TreeViewDrag.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by jeromelaban** [comment]
## Note for contributors
This sample can reproduce the issue: https://playgroundcanary.z19.web.core.windows.net/#treeview

**Comment by TopProgrammer77** [comment]
@jeromelaban, @Youssef1313  , While fixing this issue, I've faced following problems.
1. Implementing `IInsertionPanel` interface. https://github.com/unoplatform/uno/blob/13a6addff3f9b19dd1773b6d9ea1577d81cff41a/src/Uno.UI/Microsoft/UI/Xaml/Controls/TreeView/TreeViewList.cs#L197
Which class does implement `IInsertionPanel`? ItemsStackPanel?



2. Definition of `IInsertionPanel :: GetInsertionIndexes` function.
https://github.com/unoplatform/uno/blob/13a6addff3f9b19dd1773b6d9ea1577d81cff41a/src/Uno.UI/Microsoft/UI/Xaml/Controls/TreeView/TreeViewList.cs#L207

Is it possible to resolve the issue 1, 2 in **TreeViewList** (without using `IInsertionPanel` and `GetInsertionIndexes`)

3. Animation of TreeView items
    i.e. when I drag item1 to the point between item2 and item3, item2 should move to the position of item1.
- first
![image](https://github.com/unoplatform/uno/assets/122166904/a3b1c958-d426-49f9-b01e-b0647f3eba4c)

- next
![image](https://github.com/unoplatform/uno/assets/122166904/ea2fc9b7-f4b7-4037-a5c7-cc1b4632316a)

Which function do I resolve this issue in?
[UpdateDropTargetDropEffect](https://github.com/unoplatform/uno/blob/13a6addff3f9b19dd1773b6d9ea1577d81cff41a/src/Uno.UI/Microsoft/UI/Xaml/Controls/TreeView/TreeViewList.cs#L305C5-L305C30)? or [base.base.OnDragOver(args)](https://github.com/unoplatform/uno/blob/13a6addff3f9b19dd1773b6d9ea1577d81cff41a/src/Uno.UI/Microsoft/UI/Xaml/Controls/TreeView/TreeViewList.cs#L307)?

**Comment by DierkDroth** [comment]
@jeromelaban @Youssef1313 I appreciate that @TopProgrammer77 is working on that issue. Would you mind providing him the info he needed to resume hit work?

Thanks in advance

**Comment by DierkDroth** [comment]
@TopProgrammer77 @dr1rrb I confirm the fix is working. Thanks for working on it.

Now looking forward to get the animation working as well ...
