### ISSUE TITLE
CanvasSize implementation does not match SkiaSharp implementation

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#1209]
## Current behavior

The Uno.SkiaSharp.Views implementation of CanvasSize returns different values than the SkiaSharp implementation.

## Expected behavior

CanvasSize should be consistent between the two packages.

## How to reproduce it (as minimally and precisely as possible)

[CanvasSizeSample.zip](https://github.com/unoplatform/uno/files/3369188/CanvasSizeSample.zip)

With the attached sample, launch the UWP project and see that CanvasSize is identical between the SkiaSharp implementation and a custom implementation.  In Android/iOS/WASM these two values are different.

## Environment

Nuget Package:
Uno.SkiaSharp.Views
Package Version(s):
1.68.0-uno.221
Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
The issue lies in the support for `IgnorePixelScaling` where the value used on iOS/Android is incorrect.

**Comment by ghuntley** [comment]
Confirmed fixed in the latest pre-releases. Thank-you for the clear and concise test case @peternary.
