### ISSUE TITLE
[Gallery]Card- when changing theme Cards are not getting properly refreshed.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12104]
### Current behavior

https://user-images.githubusercontent.com/74563602/235043911-435fc1e6-1156-4db7-baab-e3eba4abda76.mp4

![card issue](https://user-images.githubusercontent.com/74563602/235044407-872f85a8-0609-4e76-ad41-efa3a898206c.png)

### Expected behavior

![card correct](https://user-images.githubusercontent.com/74563602/235044423-a97267b9-ca80-4488-b233-48a01893f52b.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP .
2. Click/tap Burger Menu on the left top right.
3. Click/tap "Card from the "Component" list.
4. Click on the theme toggle button.
5. Notice that theme change to dark theme.
6. Observe that cards are not getting refreshed with changing theme.
7. 

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
@kazo0 does this look familiar?

**Comment by ahmedabdelkabier** [comment]
@sakshi173 I tested the latest version on the main branch and it seems to be working fine
I think you are trying to work with an old version.

**Comment by sakshi173** [comment]
@jeromelaban , @Youssef1313 still I am able to reproduce this defect with latest canary build.
![Card issue  updates](https://github.com/unoplatform/uno/assets/74563602/56ac3c0a-595d-4e5d-81ba-9bffe2054192)

**Comment by Youssef1313** [comment]
@jeromelaban Is that build outdated somehow?

**Comment by jeromelaban** [comment]
It's not, canary is building properly (today's still pending though as we need an interop fix in Uno).

**Comment by sakshi173** [comment]
Hi @jeromelaban, still this issue is happening in canary build, I am not sure it has been fixed for canary build or not.

**Comment by kazo0** [comment]
@sakshi173 the fix for this hasn't been merged yet (https://github.com/unoplatform/uno.toolkit.ui/pull/582) having some build issues

**Comment by sakshi173** [comment]
@kazo0 Thanks for the confirmation.

**Comment by sakshi173** [comment]
I Verified this issue is fixed due to that closing it.
