### ISSUE TITLE
Hot Reload documentation doesn't mention Rider status

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#12117]
## What would you like clarification on:

https://platform.uno/docs/articles/features/working-with-xaml-hot-reload.html should mention the status of Hot Reload support on Rider.

originally asked by @ahmedabdelkabier 

## Concern?

- [ ] Usage in industry
- [ ] Clarification of capabilities
- [ ] Getting started with Uno
- [x] Developing with Uno
- [ ] Contributing to the Uno project
- [ ] Publishing your application
- [ ] Support
- [ ] Other (please specify):

## For which Platform:

- [x] WebAssembly
- [x] Android
- [x] iOS
- [x] macOS (AppKit)
- [x] Mac Catalyst
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Linux Framebuffer
  - [x] Tizen
- [x] Windows

**Comment by agneszitte** [comment]
@jeromelaban I think we can now close this issue based on the latest details added recently for Rider:
https://github.com/unoplatform/uno/blob/master/doc/articles/features/working-with-xaml-hot-reload.md
