### ISSUE TITLE
Support for AndroidX

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#1217]
##  What would you like to be added:
AndroidX support: https://developer.android.com/jetpack/androidx/migrate

## For which Platform:

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows

**Comment by ghuntley** [comment]
See also: 
- https://github.com/xamarin/xamarin-android/issues/1709

**Comment by carldebilly** [comment]
https://github.com/unoplatform/uno/issues/2016
