### ISSUE TITLE
[WASM] CheckBox.Unchecked fired ~1 minute *after* it was removed from the visual tree/DOM

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#12182]
### Current behavior

This is weird one. I don't have a repo at this time and I doubt I will be able to create one, since the case is so weird that I suspect it would involved multiple 'obscure' conditions to trigger.

I'm tring to describe the case:
- I have a few `CheckBox `instances on a `StackPanel` which ultimately is hosted by a **Uno.UI.Toolkit.ElevatedView**. Basically I'm simulating a mode dialog (I don't think that matters here, but anyway...)
- as I remove the `StackPanel `from the visual tree I will see that `.Unchecked` for the first `CheckBox` child on the `StackPanel` is fired (I confirmed by tracing)
- the `CheckBox `is not bound to anything but just listed the the `Children` collection. 
- it appears I only could reproduce the problem if the `CheckBox` was checked as the 'dialog' was closed. If feels like there would be some logic in place: "OK, this thing is closed. Now there is a checkbox which is/was checked. We have to uncheck it to clear things up." (pure speculation obviously)

Here is a snippet:
```
new CheckBox
{
HorizontalAlignment     = HorizontalAlignment.Center,
IsChecked                      = Common.Session.Current.IsExpertMode,
Margin                           = new Thickness(24, 8, 0, 0),
VerticalAlignment          = VerticalAlignment.Center,
Visibility                         = (Gui.MainPage.IsPortraitMode ? Visibility.Collapsed : Visibility.Visible),
}
```
.. there really is nothing extraordinary.

What's going on there? How could an event for `CheckBox `ever be fired after it's removed from the visual tree/DOM???

### Works on UWP/WinUI

No

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by Youssef1313** [comment]
Do you have a stack trace?

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/blob/973e25e499f9c173395820fb8976719d4f9fd765/src/Uno.UI/UI/Xaml/Controls/Primitives/ToggleButton.cs#L102

Looking suspicious?

**Comment by DierkDroth** [comment]
If that would be fired *after* the `CheckBox `is removed from the visual tree/DOM, then: yes

**Comment by Youssef1313** [comment]
@DierkDroth Can you confirm whether this is reproducible if you add this block of code?

```csharp
#if HAS_UNO
Windows.UI.Xaml.FrameworkTemplatePool.IsPoolingEnabled = false;
#endif
```

**Comment by DierkDroth** [comment]
@Youssef1313 I get this error when trying to compile
```
4>C:\Users\dierk\Documents\unusual-src\Unusual.Gui.Shared\Gui\MainPage.cs(2429,1,2429,38): error CS0234: The type or namespace name 'FrameworkTemplatePool' does not exist in the namespace 'Windows.UI.Xaml' (are you missing an assembly reference?)

```

**Comment by Youssef1313** [comment]
The class is there and public:

https://github.com/unoplatform/uno/blob/2ceb77caade7d621734b827f41bf82939017d071/src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs#L75

Can you attach a binlog?

**Comment by DierkDroth** [comment]
@Youssef1313 your suspicion was right: the problem is caused by `OnTemplateRecycled` (see stacktrace below)

[localhost-1683349945798.zip](https://github.com/unoplatform/uno/files/11411338/localhost-1683349945798.zip)

**Comment by DierkDroth** [comment]
> The class is there and public:
> 
> https://github.com/unoplatform/uno/blob/2ceb77caade7d621734b827f41bf82939017d071/src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs#L75
> 
> Can you attach a binlog?

I'm on WindowsAppSDK (+ .NET 7) if that helps

**Comment by Youssef1313** [comment]
@DierkDroth Is the checkbox inside a template?

**Comment by DierkDroth** [comment]
@Youssef1313 I don't even know what a template is. Sorry, I'm not used 'that kinda stuff'

**Comment by Youssef1313** [comment]
Like, a ControlTemplate? e.g in XAML:

```csharp
<ControlTemplate TargetType="StackPanel">
    <CheckBox />
</ControlTemplate>
```

or if you used it in a control template from the C# code behind?

or how you are creating these checkboxes?

I'm still trying to look without a repro, but it would be very helpful if you provided a repro.

**Comment by DierkDroth** [comment]
No, I'm using using any `ControlTemplate` knowingly...

**Comment by DierkDroth** [comment]
I suspect `Uno.UI.Toolkit.ElevatedView` leaves some stuff 'active' even when removed from the visual tree/DOM.

**Comment by Youssef1313** [comment]
How are you removing the StackPanel? Setting `elevatedView.ElevatedContent` to null? or something else?

**Comment by DierkDroth** [comment]
Here is the tree of visual elements:
- `UnusualElevatedView `(custom modal dialog implementation: basically a simple `Grid`)
- UnusualElevatedView .Children holds a `Border`
- Border.Child is `Uno.UI.Toolkit.ElevatedView`
- .ElevatedContent is a Grid with more children, multiple levels deep and ultimatelty a `StackPanel` with the offending `CheckBox`

When closing the dialog, the `UnusualElevatedView  `is removed from the visual tree/DOM

Hope this helps.

**Comment by DierkDroth** [comment]
Thanks guys. Will run a test as the build is available.

**Comment by DierkDroth** [comment]
@Youssef1313 this fixed the issue I encountered. Thanks
