### ISSUE TITLE
Support for iOS 13

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#1218]
##  What would you like to be added:
Upcoming support for iOS 13

## For which Platform:

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows

**Comment by ghuntley** [comment]
See also:
- https://docs.microsoft.com/en-us/xamarin/ios/platform/ios13/get-started

**Comment by ghuntley** [comment]
See also:
- https://docs.microsoft.com/en-us/xamarin/ios/platform/ios13/

**Comment by hugo0991** [comment]
URGENT ! - Microsoft Authenticator does not work using iOS 13, see photo attached.

![image0](https://user-images.githubusercontent.com/49957111/61472348-e0c19300-a949-11e9-91ab-cdab29e2d56a.png)
