### ISSUE TITLE
Transitive Roboto dependency doesn't work under Linux when using `dotnet publish`

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#12184]
## Current behavior

Transitive Roboto dependency doesn't work under Linux when using `dotnet publish`. I haven't tried an explicit dependency yet, but it will likely work.

Also, the same scenario works correctly under Windows. So it happens only when `dotnet publish` is run on Linux.

My use case was deploying Wasm app via GitHub Actions, and simply switching `ubuntu-latest` to `windows-latest` worked.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by jeromelaban** [comment]
Moving to uno, as it's likely to be a transitive content publishing issue. 

Does it happen with a simple dotnet new unoapp?

**Comment by Youssef1313** [comment]
@jeromelaban Yup. It should be easily reproducible on Linux. After investigating, it turned out the problem is that uprimarker isn't detected because case mismatch between the dll in the package in the uprimarker file. So, the condition here will be false for roboto.

https://github.com/unoplatform/uno/blob/973e25e499f9c173395820fb8976719d4f9fd765/src/SourceGenerators/Uno.UI.Tasks/Content/uno.ui.tasks.assets.targets#L136-L139

![image](https://user-images.githubusercontent.com/31348972/236555893-dc9e056b-d6c7-4a5d-97e2-0cb4d2e2b59c.png)
