### ISSUE TITLE
Custom titlebar does not work with `unpackaged` 

### ISSUE THREAD

**Issue by SongOfYouth** [unoplatform/uno#12186]
### Current behavior

when build with Packaged,It works well,but not with unpackaged.

### How to reproduce it (as minimally and precisely as possible)

set the property `ExtendsContentIntoTitleBar` as `true`:
`App._window!.ExtendsContentIntoTitleBar = true;`

### Works on UWP/WinUI

Yes

### Environment

Other

### NuGet package version(s)

Uno.Resizetizer = 1.0.2
Uno.WinUI = 4.8.15
Microsoft.WindowsAppSDK = 1.2.230313.1
Microsoft.Windows.SDK.BuildTools = 10.0.22621.755
Uno.Material.WinUI = 2.5.3
Uno.Extensions.Authentication.WinUI = 2.3.2
Uno.Extensions.Reactive.WinUI = 2.3.2
Microsoft.Extensions.Logging.Console = 6.0.0
Uno.Core.Extensions.Logging.Singleton = 4.0.1
Uno.UI.Adapter.Microsoft.Extensions.Logging = 4.8.15

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

17.5.3

**Comment by FrozDark** [comment]
Welcome https://github.com/microsoft/microsoft-ui-xaml/issues

**Comment by nickrandolph** [comment]
I've tried reproducing this issue and I'm not seeing any exception or runtime failure when setting this property. Can you provide either repro steps, or even a sample project that demonstrates this issue.

**Comment by wangrd** [comment]
> I've tried reproducing this issue and I'm not seeing any exception or runtime failure when setting this property. Can you provide either repro steps, or even a sample project that demonstrates this issue.

Do you build and run it with "UnPackaged"? if so, you will can't drag the titlebar or click the tittlebar button.

**Comment by ritt-app** [comment]
[ExtendsContentIntoTitleBarRepro.zip](https://github.com/unoplatform/uno/files/11609391/ExtendsContentIntoTitleBarRepro.zip)
Running into the same problem. Here is a minimum repro. No build or runtime exceptions, but the titlebar cannot be dragged and the maximize, minimize and close buttons are not accessible.

**Comment by MartinZikmund** [comment]
This issue is Windows App SDK specific, as `ExtendsIntoTitleBar` is not supported in Uno Platform and unpackaged mode is available only on WinAppSDK. Please open this issue on https://github.com/microsoft/WindowsAppSDK
