### ISSUE TITLE
[iOS] ProgressRing doesn't collapse

### ISSUE THREAD

**Issue by pdecostervgls** [unoplatform/uno#1220]
## Current behavior

Setting ```Visibility="Collapsed"``` on a ProgressRing element keeps it visible on iOS

## Expected behavior

The ProgressRing is hidden (collapsed).

## How to reproduce it (as minimally and precisely as possible)

```
<StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
    <TextBlock>Here be ProgressRing</TextBlock>
    <ProgressRing Width="200" Height="200" Foreground="Red" IsActive="True" Visibility="Collapsed"/>
</StackPanel>
```
## Environment

Nuget Package: 

Uno.UI: 1.46.0-dev.2135

Affected platform(s):
- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.1.5)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by pdecostervgls** [comment]
Functional workaround is to surround ProgressRing with Grid element and set that as collapsed.

**Comment by ghuntley** [comment]
Confirmed reproducible with `1.46.0-dev.2340`

## ios

![image](https://user-images.githubusercontent.com/127353/62117054-956e9380-b2fe-11e9-96dd-9fbaa986b44e.png)

## uwp

![image](https://user-images.githubusercontent.com/127353/62113935-ea0f1000-b2f8-11e9-8cf8-bd32909dcfa3.png)

## android

![image](https://user-images.githubusercontent.com/127353/62114067-2fcbd880-b2f9-11e9-9be4-ba060849e7ab.png)


## wasm

![image](https://user-images.githubusercontent.com/127353/62114189-79b4be80-b2f9-11e9-94bc-f0c33e8193eb.png)
