### ISSUE TITLE
[iOS] support TransformToVisual() from different parents tree

### ISSUE THREAD

**Issue by ajpinedam** [unoplatform/uno#12250]
### Current behavior

Currently, if doing `TransformToVisual()` from elements found in different parents (ViewControllers), the results are not correct.

### How to reproduce it (as minimally and precisely as possible)

Will provide a sample project later

### Workaround

N/A

### Works on UWP/WinUI

None

### Affected platforms

iOS

### IDE

Visual Studio 2022

### Anything else we need to know?

This is an edge case found during the development of this PR https://github.com/unoplatform/uno/pull/11792

**Comment by MartinZikmund** [comment]
This scenario should no longer be a problem as `Popup` is now using the same visual tree as the rest of the UI on iOS (`PopupRoot`)
