### ISSUE TITLE
[Android/iOS] Cannot save selection from DatePicker

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#12262]
### Current behavior

![ezgif com-video-to-gif](https://github.com/unoplatform/uno/assets/17461593/6c1c90d7-e55e-4d8a-8e0d-641187cfbac7)

Even when having `two-way` binding in the `SelectedDate` property, I'm not able to receive the value from the binding.

```xaml
<DatePicker SelectedDate="{Binding Date, Mode=TwoWay}"
					Header="Date of Birth"
					HorizontalAlignment="Stretch" />
```

```cs
private DateTimeOffset? _date = DateTimeOffset.Now;
        public DateTimeOffset? Date
        {
            get => _date;
            set
            {
                _date = value;

                if (value < DateTimeOffset.Now.AddYears(-18))
                {
                    if (string.IsNullOrEmpty(Validation))
                    {
                        Validation = "Good!";
                    }
                }
                else
                {
                    if (!string.IsNullOrEmpty(Validation))
                    {
                        Validation = string.Empty;
                    }
                }

                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Date)));
            }
        }
```

### Expected behavior

![winuiexpected](https://github.com/unoplatform/uno/assets/17461593/ad95ba98-f56e-46ec-b908-0884ce548f63)

### How to reproduce it (as minimally and precisely as possible)

- Download this sample [DatePickerSelect.zip](https://github.com/unoplatform/uno/files/11454154/DatePickerSelect.zip)
- Deploy on android/iOS
- Change the date for any date 18 years in the past minimum.
- A "Good!" text should display below the datepicker

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.9.0-dev.1033

### Affected platforms

Android, iOS

### IDE

Visual Studio 2022

### IDE version

17.4.3

**Comment by Marc-Antoine-Soucy** [comment]
This also prevents us from updating UNO in a different project than the one this issue was originally opened for.

**Comment by Robert-Louis** [comment]
It is fixe on Uno.WinUI 4.9.0-dev.1136. @Marc-Antoine-Soucy can you try to update the project to this version to see if it unblock you ?

**Comment by Soap-141** [comment]
@Robert-Louis Just tested it's working, I made a backport request for 4.8.

**Comment by techfooninja** [comment]
I believe I'm hitting this in WASM, too, in case that helps. I haven't tried the dev packages yet to see if it resolves my issue, but I will now.

**Comment by techfooninja** [comment]
Can confirm - updating to Uno.WinUI 4.9.0-dev.1153 fixes the binding issue for me.
