### ISSUE TITLE
`NavigationView` shows nested items if `IsEpanded = true` in `LeftCompact` mode on load

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#12272]
### Current behavior

Currently nav view is showing expanded nested items in LeftCompact mode on load while they should not be visible and shown only in flyout when parent item is invoked. Any manipulation with items restores it's behaviour as it should

Reason why I'm not using workaround explicity setting IsExpanded = false is that I'm using Auto mode and when it's auto set to LeftCompact on load it shows that nested items

### Expected behavior

Non visible nested items in LeftCompact mode

### How to reproduce it (as minimally and precisely as possible)

Repro:
[NavigationViewUnoIssues.zip](https://github.com/unoplatform/uno/files/11460208/NavigationViewUnoIssues.zip)

### Workaround

Don't explicity expand items

### Works on UWP/WinUI

None

### NuGet package version(s)

Uno 4.9.0 dev.1033

### Affected platforms

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

### Anything else we need to know?

Tested on Skia only but should other platforms have the same issue

**Comment by MartinZikmund** [comment]
@ramezgerges Maybe something that could be interesting for you?

**Comment by ramezgerges** [comment]
@FrozDark Could you please test with the 5x branch?
