### ISSUE TITLE
[Gallery][iOS/Android]Typography( Fluent and Cupertino)-For Typography examples, 'Size/Line Height' text is truncating at the end.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12279]
### Current behavior

![typography cupertino issue](https://github.com/unoplatform/uno/assets/74563602/27443562-6202-4170-8938-7605a775eb02)
![typography Fluent issue](https://github.com/unoplatform/uno/assets/74563602/d944f0bf-de89-4769-ab20-573682bed9cf)

### Expected behavior

The  Text should not truncate at the end.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "Typography" from the "Theming" list.
4. Notice that for each example the Size/Line Height text is truncating at the end.

### Works on UWP/WinUI

None

### Affected platforms

Android, iOS

**Comment by MartinZikmund** [comment]
@morning4coffe-dev can you handle this one please?

**Comment by morning4coffe-dev** [comment]
@MartinZikmund Sure!

**Comment by morning4coffe-dev** [comment]
This was fixed back in May with the https://github.com/unoplatform/Uno.Gallery/pull/709
