### ISSUE TITLE
NavigationView collapses expanded nested items whenever any item is invoked in LeftMinimal mode

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#12273]
### Current behavior

Explicity setting IsExpanded = true doesn't work as well
Uno collapses nested items at any circumstances

Same behaviour in Auto mode set auto to LeftMinimal

One issue to add is that chevron is static. Doesn't change it's state
### Expected behavior

No collapsing items in LeftMinimal mode

### How to reproduce it (as minimally and precisely as possible)

Repro:
[NavViewCollapsingUnoIssues.zip](https://github.com/unoplatform/uno/files/11460233/NavViewCollapsingUnoIssues.zip)

### Workaround

None

### Works on UWP/WinUI

Yes

### NuGet package version(s)

Uno 4.9.0 dev.1033

### Affected platforms

Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

### IDE

Visual Studio 2022

### Anything else we need to know?

Tested on Droid and Skia targets only and seems like other platforms have the same issue

**Comment by MartinZikmund** [comment]
@ramezgerges same here, could be similar to the recent changes?

**Comment by ramezgerges** [comment]
@FrozDark Could you please test with the 5x branch? It does indeed reproduce for the latest 4x branch, but it's not reproducing on master for me.
