### ISSUE TITLE
RoutedEventArgs.OriginalSource is null in button click

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#1227]
## Current behavior

When a button's click handler is called RoutedEventArgs.OriginalSource is null

## Expected behavior

RoutedEventArgs.OriginalSource should match UWP behavior and be populated.

## How to reproduce it (as minimally and precisely as possible)

[App12.zip](https://github.com/unoplatform/uno/files/3386481/App12.zip)

Click the provided button.  In UWP the OriginalSource is non-null, in all other platforms it is null.

## Environment

Nuget Package:
Uno.UI
Package Version(s):
1.46.0-dev.2135
Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Thanks for the great repro. I can confirm on iOS, Android and WebAsm when clicking on the button `RoutedEventArgs` is null but is not the case on UWP. Investigating...

**Comment by dr1rrb** [comment]
This has been fixed by https://github.com/unoplatform/uno/pull/1256

I'm closing the issue, feel free to re-open it if there is any issue.
