### ISSUE TITLE
[WASM] Latest UNO bits no longer building after latest .NET workload updates

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#12282]
### Current behavior

Binlog and screenshots attached

Would you have any idea what's going on?

<img width="867" alt="image" src="https://github.com/unoplatform/uno/assets/26179242/6a51d9d1-7923-43a0-be4e-0483cab470db">

<img width="1280" alt="image" src="https://github.com/unoplatform/uno/assets/26179242/7d19eb68-175c-4b52-a494-8effe1b6e19a">

<img width="867" alt="image" src="https://github.com/unoplatform/uno/assets/26179242/572832d2-e1d1-49bb-a659-ed582d01af74">

[msbuild.zip](https://github.com/unoplatform/uno/files/11466556/msbuild.zip)

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by jeromelaban** [comment]
This is likely related to https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/717. It will be fixed in 7.0.24 which will be released in a few hours. Feel free to reopen if this does not help.

**Comment by DierkDroth** [comment]
Thanks for you speedy reply @jeromelaban. I'll test as it's available.

**Comment by DierkDroth** [comment]
@jeromelaban I confirm issue is fixed with 7.0.24 bootstrap. Thanks
