### ISSUE TITLE
[VS preview] Build errors when iOS agent is not connected

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#12281]
When building with VS 2022 Preview 6, the build may fail when the hosted agent is not connected.

### Discussed in https://github.com/unoplatform/uno/discussions/12277

<div type='discussions-op-text'>

<sup>Originally posted by @proficad May 12, 2023</sup>
VS 2022 preview on Windows 11
I followed the tutorial on this page:
https://platform.uno/docs/articles/get-started-vs-2022.html

and I see these errors in the Error panel:
```
Error	CS8012	Referenced assembly 'UnoApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' targets a different processor.	UnoApp1.Mobile (net7.0-ios)	D:\projects\UnoApp1\UnoApp1\UnoApp1.Mobile\CSC	1	Active
```
</div>

**Comment by jeromelaban** [comment]
@proficad this is indeed an issue with the preview bits of VS. Can you confirm that it works properly with stable releases ?

Also, if you connect your visual studio to a mac, the error should disapear.

**Comment by jeromelaban** [comment]
Another workaround is to remove this line in the `Directory.Build.props` from your project:

https://github.com/unoplatform/uno.templates/blob/a25562b0d04b19d5ee61b9220aa93010bf7e1835/src/Uno.Templates/content/unoapp/Directory.Build.props#L39

**Comment by proficad** [comment]
Removing that line helped.
Thanks!
Vaclav
