### ISSUE TITLE
How optimistic on future Composition API support

### ISSUE THREAD

**Issue by seanocali** [unoplatform/uno#1229]
I have a very large and complex UWP project.  I’m trying to decide if I want to start porting it to Uno.  My project contains 4 or 5 custom controls that rely heavily on Composition API and 2 of them rely on Win2D.  How realistic is it to expect these would work on Android or iOS in the near future?  I know it’s in the roadmap but that could be pie in the sky wishlist afaik.

**Comment by ghuntley** [comment]
howdy @seanocali, glad to hear that you are considering porting your UWP application over to Uno. You'll find which APIs are currently implemented over [here on the website](https://platform.uno/docs/articles/implemented-views.html).

Your question came up in the planning session this morning. As for timings, that's a tricky question to answer. It's looking as if the composition is multiple months (4+ min) away before this can be picked up unless someone contributes the implementation or things change behind the scenes (and things have been changing rapidly lately). When you see what we have in store I'm sure you'll understand and be quite excited. 

If you'd like to help out with contributing to the project let me know as there's time reserved in every sprint for pairing with folks who help out.


ps. I've raised https://github.com/unoplatform/uno/issues/1239 to track Win2D.

**Comment by seanocali** [comment]
Thanks for filling me in!
