### ISSUE TITLE
[iOS] Build error: The build signature could not be verified due to an error.

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#12299]
### Current behavior

When connected to mac build host:

16:28:32:076	5>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.4.7054\tools\msbuild\iOS\Xamarin.Messaging.Build.targets(139,3): warning : The build signature could not be verified due to an error. If your build fails, please try rebuilding the solution. Error details: One or more errors occurred.
16:28:33:075	5>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7054\tools\msbuild\iOS\Xamarin.Shared.targets(1746,3): error : MessagingRemoteException: An error occurred on client Build1647054 while executing a reply for topic xvs/build/16.4.7054/execute-task/{AppName}/3387f8b002fDetectSdkLocations
16:28:33:075	5>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7054\tools\msbuild\iOS\Xamarin.Shared.targets(1746,3): error : ArgumentNullException: Value cannot be null.
16:28:33:075	5>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7054\tools\msbuild\iOS\Xamarin.Shared.targets(1746,3): error : Parameter name: path2
16:28:33:075	5>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7054\tools\msbuild\iOS\Xamarin.Shared.targets(1746,3): error :
16:28:33:153	5>Done building project "UnoApp181.Mobile.csproj" -- FAILED.
![image](https://github.com/unoplatform/uno/assets/1614057/4a792f4d-cd75-4031-8c99-2c2433f1ecad)

### Expected behavior

No build errors

### How to reproduce it (as minimally and precisely as possible)

dotnet new unoapp -preset blank
Open app in VS
Make sure VS is paired
Attempt to rebuild all projects

### Workaround

Detach mac build agent will allow Mobile project to build

### Works on UWP/WinUI

Yes

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.5.5

### Relevant plugins

Microsoft Visual Studio Professional 2022
Version 17.5.5
VisualStudio.17.Release/17.5.5+33627.172
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA052
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.5.320.55692
ASP.NET and Web Tools

AvaloniaPackage Extension   1.0
AvaloniaPackage Visual Studio Extension Detailed Info

Azure App Service Tools v3.0.0   17.5.320.55692
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.5.320.55692
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.5.2-3.23171.7+d17f741546fad2786cbd6394d08619544e53a36d
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.3 (main@2a4517a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub Copilot   1.82.1.0 (v1.82.1.0@10c323cc0)
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

GitHub Copilot Agent   1.82.15 (v1.82.0)

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.5.9 (11975e6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.5.2.2316603+9f1b6856460af1e592d387ebef416eadddac453f
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.2.40120.0
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20105.2003
TypeScript Tools for Microsoft Visual Studio

Uno Platform Extension   1.0
Uno Platform Extension to create cross-platform apps using iOS, Android, mac Catalyst, Skia and WebAssembly.

Visual Basic Tools   4.5.2-3.23171.7+d17f741546fad2786cbd6394d08619544e53a36d
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.5.0.173 (d17-5@33e727c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.5.3.46 (remotes/origin/d17-5@e4dd80b2bb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.5.41 (ba80d05)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.0.0 (d17-5/797e2e1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/main@149d70fe
    SQLite: xamarin/sqlite/3.40.0@fdc1e34
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77

Xamarin.iOS and Xamarin.Mac SDK   16.2.0.5 (7738c90c9)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by MartinZikmund** [comment]
Are you able to test this on VS Preview?

**Comment by MartinZikmund** [comment]
@nickrandolph do you think we can close this for now if you haven't encountered this since?

**Comment by nickrandolph** [comment]
Yep I think so
