### ISSUE TITLE
Building Uno.UI.BindingHelper.Android - The command exited with code 1.

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1230]
## Current behavior

```
Error	CS0246	The type or namespace name 'UnoViewGroup' could not be found (are you missing a using directive or an assembly reference?)	SamplesApp.Droid	N:\uno\dev\src\SamplesApp\UITests.Shared\Windows_UI_Xaml_Controls\Button\Buttons.xaml.cs	13	Active
Error	MSB3073	The command ""C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\bin\javac.exe" -g -source 1.8 -d .\obj\Debug\MonoAndroid90\\unoclasses -target 1.8 -J-Dfile.encoding=UTF8 -classpath "%ProgramFiles(x86)%\Reference Assemblies\Microsoft\Framework\MonoAndroid\v9.0\mono.android.jar;obj\Debug\MonoAndroid90\\__library_projects__\Xamarin.Android.Support.Annotations\library_project_imports\support-annotations.jar" -bootclasspath "C:\Program Files (x86)\Android\android-sdk\platforms\android-28\android.jar" -encoding UTF-8 .\Uno\UI\*.java" exited with code 1.	Uno.UI.BindingHelper.Android	N:\uno\dev\src\Uno.UI.BindingHelper.Android\Uno.UI.BindingHelper.Android.csproj	141	
```

## Expected behavior

- Clone unoplatform/uno
- Load the Android solution filter
- It just works

## How to reproduce it (as minimally and precisely as possible)

- Clone unoplatform/uno
- Load the Android solution filter
- Right click build `Uno.UI.BindingHelper.Android`
- 😢 

## Environment

- 🎉 I am able to build API 16 to 28 applications and deploy to API 16 to 28 emulators.
- 👀 `C:\Users\ghuntley\AppData\Local\Xamarin\zips` was empty (I've since [pre-populated it with zips according to](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/resolving-library-installation-errors)).
- ⚠️ `src\Uno.UI.BindingHelper.Android\obj\Debug\MonoAndroid90\unoclasses` is empty.
- ⚠️ `C:\Users\ghuntley\AppData\Local\Xamarin\Android.Support.v4` does not exist.
- 👀 I do not have Android Studio installed.

![image](https://user-images.githubusercontent.com/127353/61197552-e7b58f00-a718-11e9-81c2-18c5ffe2760e.png)

![image](https://user-images.githubusercontent.com/127353/61197562-f8660500-a718-11e9-9599-943e6b385687.png)

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: Latest Stable and Latest Preview)
- [ ] for Mac (version: )

## Anything else we need to know?

I haven't been able to build `Uno.UI.BindingHelper.Android` since reinstalling my computer.

**Comment by jeromelaban** [comment]
This looks like either invalid xamarin.android nuget packages or bin/obj invalid content.

Are there some other messages before that ?

**Comment by ghuntley** [comment]
@jeromelaban paired with me a couple hours ago to troubleshot. If you experience this issue right click on the project and click "Rebuild" (even if you have never build the project before). The root cause of this issue isn't known yet so will be keeping it open.

![image](https://user-images.githubusercontent.com/127353/61266309-a71c4b00-a7d6-11e9-88c9-85c00b50ed27.png)

**Comment by jeromelaban** [comment]
Fixed in recent Uno builds.
