### ISSUE TITLE
Unable to animate the `Canvas.Top` or `Canvas.Left` attached properties

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#12301]
### Current behavior

Animation of the canvas top or left attached properties does not work on WASM, Android and iOS.

---
        <Storyboard x:Name="SimpleStoryboard">
            <DoubleAnimation Storyboard.TargetName="Thing" 
                             Storyboard.TargetProperty="(Canvas.Top)"
                             From="{x:Bind VM.Y, Mode=OneWay}" To="20.0" Duration="0:0:5"/>
        </Storyboard>
---

On button press

this.SimpleStoryboard.Begin();

Works perfectly well on WinUI

### Expected behavior

In the sample the red ball should animate vertically up the screen.

### How to reproduce it (as minimally and precisely as possible)

Reproduced in sample at https://github.com/BrianDT/UnoCanvasOffsetAnimationIssue

### Workaround

Adding EnableDependentAnimation="true" to the DoubleAnimation works for WASM and iOS

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.8.33

### Affected platforms

All targets

### IDE

Visual Studio 2022

### IDE version

17.5.5

### Relevant plugins

None

**Comment by BrianDT** [comment]
> Looks like a dupe of #8613

@Youssef1313 Superficially looks the same but actually not. #8613 suggests that if you add 
                             EnableDependentAnimation="true"

To the DoubleAnimation then the problem can be worked around.
This works for WASM but is not true for Android where the EnableDependentAnimation has no effect and it still does not work. Jury is still out on iOS.

Even for WASM, there is no suggestion under #8613 that anybody has raised a WinUI issue indicating that WinUI should require the EnableDependentAnimation property set to work, which makes be thing that if WinUI is correct the workaround is just covering up what is still an issue.

**Comment by MartinZikmund** [comment]
Yes, will close #8613 in favor of this one, as it is more broad, affecting all targets

**Comment by dr1rrb** [comment]
@BrianDT  The `EnableDependentAnimation` is a UWP/WInUI flag which is `false` by default and indicates if animations that are invalidating the layout (i.e. causing Measure/Arrange phases) are allowed or not (cf. https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.animation.doubleanimation.enabledependentanimation?view=winrt-22621#whats-considered-a-dependent-animation). 

I assume that this flag has to be set to `true` to animate the `Canvas.<X|Y>` on Windows, and we should align Uno's behavior with Windows (even if currently we are not running animation independently of the UI thread on Skia and Wasm).

**Comment by BrianDT** [comment]
@dr1rrb I absolutely agree that Uno's behavior should align with Windows, that was the point I was trying to make. The point is that Windows **Does Not Require** the EnableDependentAnimation flag set for the animation to run, so I was questioning why it was required in Uno.

**Comment by BrianDT** [comment]
A sequence of changes to the sample has enabled the iOS build to be investigated. The path has been shortened, the provisioning profile has been reset and changes from the latest templates incorporated.
The sample now shows that if EnableDependentAnimation="true" the iOS build executes as expected.
Therefore, in summary:
Windows OK
Android Fail
iOS OK with workaround
WASM OK with workaround

**Comment by BrianDT** [comment]
@dr1rrb The suggestion to use a Translation Transform for the animation is a good one. This works absolutely fine on Windows and WASM, but has a minor issue on Android and a slightly bigger issue on iOS.

The sample has been updated to include the alternative animation. In the sample only the Translate.Y is animated.

On Android when the animation completes the Translate.X is set to 0 so the target object that has been moved shifts to the left of the screen.

On iOS the Translate.X is set to 0 as soon as the animation starts so the target object moves up the left-hand side of the screen.
