### ISSUE TITLE
PrimaryLanguageOverride setting shared between skia applications

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#12320]
### Current behavior

Create two different applications
Set PrimaryLanguageOverride in one application
Run other application and not PrimaryLanguageOverride is also set.

### Expected behavior

Applications maintain separate values for PrimaryLanguageOverride

### Works on UWP/WinUI

None

### Anything else we need to know?

Currently skia applications use a common location for all settings. 
This will be resolved by [this PR](https://github.com/unoplatform/uno/pull/12314) but as this is breaking changes, will be 5.0 timeline
Fix for PrimaryLanguageOverride would be to use an app specific key for looking up the settings value.
Furthermore this would also provide separation for local debugging wasm applications. Currently if you create and debug two wasm applications that happen to use the same port (eg https://localhost:5000), they will access the same settings and thus the same value for PrimaryLanguageOverride. Even in 5.0 timeline when the fix for skia appdata is merged, we should keep the app specific key for PrimaryLanguageOverride to avoid confusion when debugging wasm applications.

**Comment by jeromelaban** [comment]
This is fixed in latest master, since settings storage is now app-id specific.
