### ISSUE TITLE
Loading fonts fails on Wasm when the browser uri is altered (e.g, navigation)

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#12323]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/31348972/ad7fa7fd-aa80-4eb4-bfa3-c3657fe1ebe6)

Note: the font is packaged correctly, but the url isn't supposed to have "/Main" (which comes from navigation routes)

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
This is expected, there's a bootstrapper feature for that: https://platform.uno/docs/articles/external/uno.wasm.bootstrap/doc/features-deep-linking.html

**Comment by Youssef1313** [comment]
Should we have this in the templates when extensions navigation is selected? cc @nickrandolph @dansiegel 

Also we probably should doc this in uno.extensions navigation (cc @lukeblevins)

**Comment by nickrandolph** [comment]
Yes, and I think we had this back on the original extensions template, so need to add it to the unoapp template.
