### ISSUE TITLE
[Gallery][Wasm/iOS/Android] MediaPlayerElement does not play a local source

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno#12331]
### Current behavior

MediaPlayerElement does not play a local source for Wasm, iOS, and Android 

(Still waiting on [Skia support](https://github.com/unoplatform/uno/issues/12240#top) to be done to test on this platform)

### Expected behavior

MediaPlayerElement should play a local source like on Windows

### How to reproduce it (as minimally and precisely as possible)

- Open Uno Gallery APP
- Click Burger Menu on the left top right (if the menu is not already opened)
- Click "MediaPlayerElement" from the "UI Components" list.
- Launch the second sample:
 "**MediaPlayerElement sample using PosterSource, TransportControls, and a local file with mp4 forma**t"
- Try to play the video
- Observe that the video is not playing

```
			<MediaPlayerElement x:Name="MediaPlayerElementSample2"
								Source="ms-appx:///Assets/Videos/Getting_Started_with_Uno_Platform_for_Figma.mp4"
								PosterSource="ms-appx:///Assets/Thumbnails/Getting_Started_with_Uno_Platform_for_Figma.png"
								AreTransportControlsEnabled="True"
								AutoPlay="False"
								MaxWidth="720" />
```

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI/Uno.WinUI: 4.9.0-dev.1113
Uno.UI.MediaPlayer.WebAssembly/Uno.WinUI.MediaPlayer.WebAssembly: 4.9.0-dev.1113

### Affected platforms

WebAssembly, Android, iOS

### IDE

Visual Studio 2022

### IDE version

17.5.5

**Comment by sakshi173** [comment]
@agneszitte and @jeromelaban, still this issue is present.
