### ISSUE TITLE
[Gallery][Wasm/iOS/Android] MediaPlayerElement with ShowAndHideAutomatically=false only work once

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno#12341]
### Current behavior

MediaPlayerElement with ShowAndHideAutomatically  set to **false** only works the first time on Wasm, iOS, and Android

(Still waiting on [MediaPlayer Skia](https://github.com/unoplatform/uno/issues/12240) to be done to test on this platform)

![f0c8277ea7b3fd5224a7b6a909b0f428](https://github.com/unoplatform/uno/assets/16295702/1308dca5-9e30-4899-bcae-a3ad7da69f2a)

### Expected behavior

MediaPlayerElement with ShowAndHideAutomatically set to **false** should work every time like on Windows
If ShowAndHideAutomatically is set to false the transport controls area should not be hidden all the time

**Windows:**
![279d425508e7c5116456f6f7669b90c6](https://github.com/unoplatform/uno/assets/16295702/79b8d255-6ed2-4b82-9995-a63e2986baa1)

### How to reproduce it (as minimally and precisely as possible)

- Open Uno Gallery APP
- Click Burger Menu on the left top right (if the menu is not already opened)
- Click "MediaPlayerElement" from the "UI Components" list.
- Launch the fourth sample:
  **"MediaPlayerElement sample using customizable options"**
- Check 
  - **AreTransportControlsEnabled**
  - **IsCompact** 
- Make sure **ShowAndHideAutomatically**  is **unchecked** and all the other options also
- Play the video, and notice the transport controls do not hide (like they should)
- Pause the video
- Play the video again
- Observe that the transport controls are hidden this time

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI/Uno.WinUI: 4.9.0-dev.1113
Uno.UI.MediaPlayer.WebAssembly/Uno.WinUI.MediaPlayer.WebAssembly: 4.9.0-dev.1113

### Affected platforms

WebAssembly, Android, iOS

### IDE

Visual Studio 2022

### IDE version

17.5.5

**Comment by rafael-rosa-knowcode** [comment]
Now it is working.
The PR https://github.com/unoplatform/uno/pull/12372 fixed the problem.
