### ISSUE TITLE
CalendarDatePicker - popup theme is not following app theme

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12348]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/ae52f3c3-b247-4154-b9a9-bc276ef64b2f

### Expected behavior

Calendar should properly refreshed.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "CalendarDatePicker" from the "UI component" list.
4. Go to Cupertino section.
5. click on the calendar.
6. Click on to dark/light theme toggle button.
7. Notice that when changing theme Calendar are not properly refreshing.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Skia (GTK on Linux/macOS/Windows)

**Comment by Robert-Louis** [comment]
Also happen with fluent theme.

**Comment by agneszitte** [comment]
reopened for backport https://github.com/unoplatform/uno/pull/13215

**Comment by agneszitte** [comment]
@MartinZikmund switching this issue for QA review as all the backports are now merged

@sakshi173 if you can please test this one `tomorrow`, thanks in advance

**Comment by sakshi173** [comment]
This issue is resolved, closing it.

**Comment by agneszitte** [comment]
Thanks @sakshi173
