### ISSUE TITLE
[Gallery][iOS] MediaPlayerElement with ShowAndHideAutomatically set to true will hide the transport controls outside of the control area

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno#12343]
### Current behavior

MediaPlayerElement with ShowAndHideAutomatically set to true will hide the transport controls outside of the control area for iOS

(Still waiting on [MediaPlayer Skia](https://github.com/unoplatform/uno/issues/12240) to be done to test on this platform)

![image](https://github.com/unoplatform/uno/assets/16295702/28086e3d-ccf9-458b-95c1-eab4716593fd)
![3e40ec852099aced8da1b1cad4a42c2c](https://github.com/unoplatform/uno/assets/16295702/405cf72a-bd7d-40b5-9158-020b3f25a8e8)

### Expected behavior

MediaPlayerElement with ShowAndHideAutomatically set to true should hide the transport controls inside the control area like on Windows

![60a678e066a5a5ee29517f412e054864](https://github.com/unoplatform/uno/assets/16295702/13d53b2c-e1c9-4b57-8021-307db4e38b03)

### How to reproduce it (as minimally and precisely as possible)

- Open Uno Gallery APP
- Click Burger Menu on the left top right (if the menu is not already opened)
- Click "MediaPlayerElement" from the "UI Components" list.
- Launch the fourth sample:
  **"MediaPlayerElement sample using customizable options"**
- Check 
  - **AreTransportControlsEnabled**
  - **IsCompact** 
  - **ShowAndHideAutomatically**
- And uncheck all the other options
- Play the video
- Observe that during the animation to hide the transport controls you can see part of the controls outside of the MediaPlayerElement area

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI/Uno.WinUI: 4.9.0-dev.1113

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.5.5

**Comment by Xiaoy312** [comment]
could no repro
![12343 proof](https://github.com/unoplatform/uno/assets/2359550/a33604ff-ffe1-4748-afeb-5adf0379a256)
