### ISSUE TITLE
[Gallery][Skia.Gtk]Infobadge-For 'Numeric Value' textbox when type Number and press Enter Nothing is happening.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12363]
### Current behavior

![Infobade enter issue](https://github.com/unoplatform/uno/assets/74563602/0863b3c4-222d-44c8-b061-ecc5ae6d4032)

### Expected behavior

![Infobadge enter correct](https://github.com/unoplatform/uno/assets/74563602/584825ef-1fa5-45ee-844e-16a7c49456a5)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "Infobadge" from the "UI Component" list.
4. Type some number inside 'Numeric Value' textbox.
5. press Enter key.
6. Notice that when type Number and press Enter Nothing is happening.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by agneszitte** [comment]
@sakshi173 seems fixed with latest 5.X packages @silviuo shared with me, can you please re-test this issue

**Comment by sakshi173** [comment]
Verified this issue is fixed closing it.
