### ISSUE TITLE
`RemoteControl` restore issues

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#12366]
### Current behavior

**Issue from https://stackoverflow.com/questions/76174753/uno-platform-remotecontrol-the-uno-winui-remotecontrol-or-uno-ui-remotecontrol**

I have been struggling to get the RemoteControl to consistently work for my WebAssembly head. I created the project using the built-in Uno project wizard. I am running on the following platforms:

Windows 10 21H2 dev machine (19044.2728)
Visual Studio 2022 Professional (17.5.5)
Uno.WinUI.WebAssembly (4.8.33)
Uno.WinUI.RemoteControl (4.8.33)
Uno.Wasm.Bootstrap (7.0.20)
Uno.Wasm.Bootstrap.DevServer (7.0.20)
I frequently (but not 100% of the time) get this error in the Uno Platform output window:

[INFO] The Uno.WinUI.RemoteControl or Uno.UI.RemoteControl package has not been restored yet, retrying...

I've tried the following with no consistent results of success:

Restarting Visual Studio
Closing the solution and re-opening
Unloading the project and re-loading
Restoring nuget packages for the solution (i.e. right-click solution and select "Restore NuGet Packages")
Opening a vanilla, new solution with a new, blank Uno app in it, then switching back to my solution (this one works ~20% of the time)
Increasing filesystem permissions on my packages folder for all users on the machine
Is there some additional logging for Uno/Uno.WinUI.RemoteControl I can view? I don't even know where to start troubleshooting, so any pointers are welcomed.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by techfooninja** [comment]
which version of the VSIX should I be looking for?

**Comment by jeromelaban** [comment]
Thanks for the update. The vsix version 4.9.16 is now published and contains the fix for this issue.

**Comment by techfooninja** [comment]
awesome. I just updated to 4.9.17.18 and haven't seen the issue yet. I suppose if I see it again it's best to open a new issue instead of re-activating this one?
