### ISSUE TITLE
Hot Restart for .NET 6+ apps

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#12388]
## What would you like to be added:

Hot Restart support for .NET 6+ apps, based on the [Xamarin.Forms hack detailed in this blog post](https://platform.uno/blog/hot-restart-available-in-uno-platform).

The original workaround tricking VS to recognize a Xamarin.Forms app was as follows:
```csharp
public class Application 
{ 
  // This is the main entry point of the application. 
  static void Main(string[] args) 
  { 
    // if you want to use a different Application Delegate class from "AppDelegate" 
    // you can specify it here. 
    UIApplication.Main(args, null, typeof(App)); 
  } 
} 
 
#if DEBUG 
public class HotRestartDelegate : Xamarin.Forms.Platform.iOS.FormsApplicationDelegate 
{ 
  public override bool FinishedLaunching(UIApplication uiApplication, NSDictionary launchOptions) 
  { 
    Windows.UI.Xaml.Application.Start(_ => new App()); 
    return base.FinishedLaunching(uiApplication, launchOptions); 
  } 
} 
#endif
```

We may be able to find a similar hack based on Maui's app delegate.

**Comment by Strypper** [comment]
The problem is `Xamarin.Forms.Platform.iOS` even though I installed Xamarin.Form nuget 4.8 in my IOS project

**Comment by jeromelaban** [comment]
Thanks. It's not possible to install Xamarin.Forms in a .NET 6+ app, which why the workaround does not work anymore.

**Comment by Strypper** [comment]
Can you provide a way to deploy Uno app on a physical device? I tried 
1. Hot restart
2. Deploy remote device from visual studio connected to Mac M1 and the Mac M1 is connected to physical iPhone - error: `Verification of iOS environment is running. Please try again in a moment.`
3. Deploy from Mac M1 to the physical device (This maybe not supported latest Xcode version) - 
![image](https://github.com/unoplatform/uno/assets/32596308/f8f9dc4b-83dc-4ad1-8268-78bb495b23d5)

**Comment by jeromelaban** [comment]
The setup of your app is using a distribution profile, which cannot be used for development. You can find information about [this here](https://learn.microsoft.com/en-us/dotnet/maui/ios/device-provisioning/). If you still have problems with building your app, make sure to create a [separate discussion](https://github.com/unoplatform/uno/discussions), and not this specific issue.

**Comment by jeromelaban** [comment]
https://github.com/unoplatform/uno/pull/12894 will add support for hot restart.
