### ISSUE TITLE
CalendarView down button icon is invalid

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#12387]
### Current behavior

![Screenshot_2023-05-22-15-24-02-098_com frozdark jupiter trade-edit](https://github.com/unoplatform/uno/assets/6670150/99b02327-9588-4ed4-b3d7-4a19371357a2)

### Expected behavior

Correct down button

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno 4.9.0 dev 1053

### Affected platforms

Android

### Anything else we need to know?

Tested android only

**Comment by Youssef1313** [comment]
Reported on Wasm and Skia https://github.com/unoplatform/uno/issues/12399

**Comment by Youssef1313** [comment]
```xml
                                <Button x:Name="PreviousButton" Grid.Column="1" Content="&#xEDDB;" FontFamily="{ThemeResource SymbolThemeFontFamily}" FontSize="8" IsTabStop="True" Padding="1" Foreground="{TemplateBinding Foreground}" HorizontalContentAlignment="Center" IsEnabled="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=TemplateSettings.HasMoreContentBefore}" Style="{StaticResource NavigationButtonStyle}" />
                                <Button x:Name="NextButton" Grid.Column="2" Content="&#xEDDC;" FontFamily="{ThemeResource SymbolThemeFontFamily}" FontSize="8" IsTabStop="True" Padding="1" Foreground="{TemplateBinding Foreground}" HorizontalContentAlignment="Center" IsEnabled="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=TemplateSettings.HasMoreContentAfter}" Style="{StaticResource NavigationButtonStyle}" />
```

@NVLudwig This looks like an incorrect glyph in font file?

**Comment by Youssef1313** [comment]
Oh looks like it's already fixed in latest uno.fonts.fluent package
