### ISSUE TITLE
[Gallery][Wasm/Skia] MediaPlayerElement sample using a playlist not working

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno#12394]
### Current behavior

The MediaPlayerElement sample using a playlist is not working on Wasm and Skia

### Expected behavior

The MediaPlayerElement sample using a playlist should work on Wasm and Skia like the other platforms

### How to reproduce it (as minimally and precisely as possible)

- Open Uno Gallery APP
- Click Burger Menu on the left top right (if the menu is not already opened)
- Click "MediaPlayerElement" from the "UI Components" list.
- Launch the fifth sample:
  **"MediaPlayerElement sample using a playlist"**
- Observe that the MediaPlayerElement sample doesn't work

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI/Uno.WinUI: 4.9.0-dev.1113
Uno.UI.MediaPlayer.WebAssembly/Uno.WinUI.MediaPlayer.WebAssembly: 4.9.0-dev.1113

### Affected platforms

WebAssembly, Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

17.5.5

### Anything else we need to know?

Proper support for MediaPlayerElement using a playlist needs to be added for Wasm and Skia

**Comment by sakshi173** [comment]
@agneszitte and @jeromelaban , I am seeing this issue is still present.

**Comment by MartinZikmund** [comment]
Waiting for backport #13176

**Comment by agneszitte** [comment]
@sakshi173 if you can review this issue `tomorrow` please

**Comment by sakshi173** [comment]
@agneszitte still this issue is present.

**Comment by sakshi173** [comment]
@agneszitte and @MartinZikmund, this issue is still present.

**Comment by agneszitte** [comment]
Re-Open for backport PR

**Comment by agneszitte** [comment]
@sakshi173 this issue can be tested again on Monday

**Comment by sakshi173** [comment]
Verified this issue is fixed closing it.
