### ISSUE TITLE
Win2D API backend

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1239]
## What would you like to be added:

https://microsoft.github.io/Win2D/html/Introduction.htm

## Anything else we need to know?

> I have a very large and complex UWP project. I’m trying to decide if I want to start porting it to Uno. My project contains 4 or 5 custom controls that rely heavily on Composition API and 2 of them rely on Win2D. How realistic is it to expect these would work on Android or iOS in the near future? I know it’s in the roadmap but that could be pie in the sky wishlist afaik.

https://github.com/unoplatform/uno/issues/1229

**Comment by francoistanguay** [comment]
There's no plan to support Win@D x-plat.

**Comment by SebastianStehle** [comment]
Will there be a counterpart / similar library for immediate render mode and large rendering surfaces?

**Comment by jeromelaban** [comment]
SkiaSharp does the job pretty well at this point, [see a sample here](https://github.com/unoplatform/Uno.Samples/tree/master/UI/SkiaSharpTest).

**Comment by lextm** [comment]
Just started to create a Win2D compatibility shim based on SkiaSharp, so that project migration can be less painful,

https://github.com/lextudio/Uno2D

More tuning is needed to make it a full drop-in replacement.
