### ISSUE TITLE
Please inplement IAsyncOperation<ContentDialogResult>

### ISSUE THREAD

**Issue by iosub** [unoplatform/uno#124]
Hi
ContentDialog login = new LoginDialog();
var UserResult = await login.ShowAsync();

generated error

he member IAsyncOperation<ContentDialogResult> ContentDialog.ShowAsync() is not implemented in Uno. occurred

**Comment by yowl** [comment]
Is there any recommended alternative why we wait for this, a slideout or an overlay for example?

**Comment by JasonWeise** [comment]
I have just run into this limitation myself today when needing to display an "Alert" dialog to users with WASM.
Is there a likely timeline for if/when this would be implemented (ContentDialog).

I'd rather use an official solution than hack something together and if it "won't be far away" then I am happy to wait 

Thanks in advance.

**Comment by jeromelaban** [comment]
@JasonWeise if you need to display a simple message, there's `MessageDialog` which is currently implemented, there's also `Flyout`, and `Popup`.

**Comment by JasonWeise** [comment]
@jeromelaban thanks for the advice, I did try MessageDialog but I need to implement a sort of confirmation dialog (it is an alert with a confirmation to go ahead with the process or not) and I think I can only really do this with ContentDialog - unless you know how to add and capture multiple buttons on MessageDialog.

**Comment by MatFillion** [comment]
MessageDialog supports multiple commands/buttons and when you await `ShowAsync(ct)` you get which button was clicked. Unlike for iOS/Android, uno's wasm implementation of MessageDialog ignores the commands set on the dialog and only creates a "ok" command.
https://github.com/nventive/Uno/blob/aaa4238952fca2a23e5b3f95ea22c5d933133e0e/src/Uno.UWP/UI/Popups/MessageDialog.wasm.cs

**Comment by yowl** [comment]
For wasm, I did it with an overlay, relevant files attached.  Its not perfect but looks ok.
 In MainPage.xaml.cs, in the ctor start with
```
        public MainPage()
        {
            this.InitializeComponent();
            DialogService.Instance.Dialog = overlayContentDialog;
```
[uwp.zip](https://github.com/nventive/Uno/files/3017962/uwp.zip)
