### ISSUE TITLE
x:Bind fails when binding to inherited method

### ISSUE THREAD

**Issue by ritt-app** [unoplatform/uno#12415]
### Current behavior

When I use x:Bind to bind to non-generated, but inherited methods, build will fail with errors similar to:

CSC : error UXAML0001: Failed to find Button_Click on xBindInheritedMethodRepro.Class2

If in the child class, I create an override wrapper around the base class method, then it works. Interestingly, this is not an issue if I target only Windows.

### Expected behavior

x:Bind should not fail.

### How to reproduce it (as minimally and precisely as possible)

[xBindInheritedMethodRepro.zip](https://github.com/unoplatform/uno/files/11565368/xBindInheritedMethodRepro.zip)
- Create a new Uno platform app project 
- Create a class, say Class1, with method Button_Click() 
- x:Bind a button click event to a Class1 object -> Okay
- Create a second class, Class2, that inherits from Class1
- x:Bind a button click event to a Class2 object -> Build fails

### Workaround

Create an override wrapper around the base class method.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by Youssef1313** [comment]
Backport is done.
