### ISSUE TITLE
Arabic characters doesn't render in Skia's TextBlock with Roboto font

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#12446]
### Current behavior

In a new app with Material theme, add `<TextBlock Text="مرحبا!" />`, it renders like this:

![image](https://github.com/unoplatform/uno/assets/31348972/ef8e4cc9-c267-4b01-8cf5-2dce197483d8)

Yes, Roboto doesn't support Arabic, but this works in all other platforms, possibly because there is a font fallback mechanism.

This issue affects TextBox, but only when unfocused. It should be the same root cause, since an unfocused TextBox just shows a TextBlock on Skia. However, the shown TextBlock is internal, and it's not easy to change its font and the font set on TextBox is currently not reflected on TextBlock.

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
@jeromelaban @MartinZikmund We might need to get #6975 back?

**Comment by Youssef1313** [comment]
Generally, the workaround is to set FontFamily to something supporting Arabic, but for the TextBox case, there doesn't seem to be any workaround. The `DisplayBlock` used internally by TextBox never sets the font, and it's not publicly accessible.

**Comment by jeromelaban** [comment]
@Youssef1313 I don't think #6975 will help for TextBox indeed. As for supporting fallback, we'll need that, indeed though we'll need to validate perfomance to make sure we do not regress.

**Comment by Youssef1313** [comment]
@jeromelaban #6975 *should* fix it for TextBox, the problem for TextBox happens only when unfocused, which means that the visible element is just a TextBlock. Things work properly when focused (Sorry, I forgot to mention this in the issue description - I'll edit it now)
