### ISSUE TITLE
x:Bind to `DependencyProperty` does not use C# setter

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#12459]
I have some issues when binding to a `DependencyProperty` in WPF. Windows works fine, but in WPF the property is never updated. Am I doing something wrong or is this a bug? 🐛  

I've attached a small repro!

[DependencypropertyFail.zip](https://github.com/unoplatform/uno/files/11591700/DependencypropertyFail.zip)

_Originally posted by @maaxe in https://github.com/unoplatform/uno/discussions/12457_

**Comment by Youssef1313** [comment]
@jeromelaban Looks like a duplicate of https://github.com/unoplatform/uno/issues/9886.

I think we can close one in favor of the other.

**Comment by jeromelaban** [comment]
Indeed, I missed it because of the missing tag :) Let's close.
