### ISSUE TITLE
[Gallery][Wasm]Toggleswitch- Switch knob is displaying in Wrong direction for 'ON' Position.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12486]
### Current behavior

![Toggleswitch issue](https://github.com/unoplatform/uno/assets/74563602/7a6375f3-dd0a-4188-bd68-6a92d1d8e9c5)
![Toggleswitch issue cupertino](https://github.com/unoplatform/uno/assets/74563602/dff3e17a-975d-42b9-9d35-b5aebfc26b40)

https://github.com/unoplatform/uno/assets/74563602/3fb800d8-2fcb-45c8-9cd5-bd1349bec681

### Expected behavior

switch Knob should display correctly for the 'ON' position.
![Toggleswitch correct](https://github.com/unoplatform/uno/assets/74563602/720b4aa5-e7a7-40c9-ad0d-e427ff17aa6b)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap "Toggleswitch" from the "Component" list.
3. Observe that when go to the toggleswitch control first time  the switch knob shows in the wrong direction for 'ON' position and for disabled option it is showing in wrong direction for 'ON' position. 

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by Youssef1313** [comment]
The first thing I'd try here is to disable template pooling in Gallery and see if this starts working.

**Comment by jeromelaban** [comment]
This indeed feels like a template pooling issue, likely because there's no binding on the button and the state is not reset properly.

**Comment by agneszitte** [comment]
@sakshi173 can you review this issue with the latest changes versions please

**Comment by sakshi173** [comment]
@agneszitte, yes this issue is still present with latest canary for Fluent and Cupertino.
![toggleswitch material](https://github.com/unoplatform/uno/assets/74563602/8d39a350-afbe-4727-ba45-61de2c23ef11)
![toggleswitch cupertino issue](https://github.com/unoplatform/uno/assets/74563602/6d37d93f-23ab-4216-8a62-d9324b8a2b95)

**Comment by ramezgerges** [comment]
About the Cupertino buttons, it seems that the know shows in the right direction once the pointer hovers over it, so it might be a simple invalidation missing somewhere.

**Comment by agneszitte** [comment]
@MartinZikmund do you also have some feedback for this issue please ?

**Comment by Youssef1313** [comment]
Let's see if https://github.com/unoplatform/uno/pull/13269 will fix it.

**Comment by Youssef1313** [comment]
I think this is now fixed and already backported. @sakshi173 @agneszitte Can you please confirm and close the issue?

**Comment by sakshi173** [comment]
@Youssef1313 , yes, this issue is fixed, closing it.
