### ISSUE TITLE
`MenuFlyout.DataContext` is not propagated to child items when flyout is closed

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#12490]
### Current behavior
MenuFlyout does propagate DataContext change to child elements only when flyout is opened.

In Opening event to correctly propagate DataContext you have to set it null before setting actual value
```
private void Flyout_Opening(object sender, object e)
        {
            if (sender is MenuFlyout flyout && flyout.Target is FrameworkElement elem)
            {
#if HAS_UNO
                // Propagation only when null
                flyout.DataContext = null; 
                flyout.DataContext = elem.DataContext;
#endif
            }
        }
```

But when it's opened it's propagating DataContext well
```
private void Flyout_Opened(object sender, object e)
        {
            if (sender is MenuFlyout flyout && flyout.Target is FrameworkElement elem)
            {
#if HAS_UNO
                flyout.DataContext = elem.DataContext;
#endif
            }
        }
```

![uno](https://github.com/unoplatform/uno/assets/6670150/04c553e4-08d8-4a74-8d99-d93c4d60a297)

Related to https://github.com/unoplatform/uno/issues/11599

### Expected behavior
WinUI does propagate DataContext to child items of MenuFlyout at any state

![winui](https://github.com/unoplatform/uno/assets/6670150/527d5482-4e66-48c2-b595-79bcdfe4759f)

### How to reproduce it (as minimally and precisely as possible)

Repro
[FlyoutUnoAppIssues.zip](https://github.com/unoplatform/uno/files/11624502/FlyoutUnoAppIssues.zip)

### Workaround
Use conditional syntax and set DataContext to null explicity

### Works on UWP/WinUI

Yes

### NuGet package version(s)

Uno 4.10.0-dev.111

### Affected platforms

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

### IDE

Visual Studio 2022

**Comment by ramezgerges** [comment]
This seems to be a problem with the fact that the menuflyout is a static resource, so what happens is that all the menuflyouts are infact the same object, so when the last button sets the datacontext, the (singular) menuflyout inherits that datacontext and that affects all the other buttons. It is still very weird that manually setting the datacontext in IsOpening doesn't work (and that it works if you set to nulll first).
