### ISSUE TITLE
"Get Started on VS Code" page is confusing and (possibly) out of date

### ISSUE THREAD

**Issue by mrlacey** [unoplatform/uno#12506]
## On which page?

https://platform.uno/docs/articles/get-started-vscode.html

I was working through trying to set up running a new WASM app entirely through VSCode (on Windows) by following the instructions.
I didn't look at the sections for using VSCode on other operating systems or running on other device platforms.

I noticed the following:

## What's wrong?

~~In the "Verify your developer environment" there's a note that:
`When using a Visual Studio Preview version, you will need to run uno-check --pre.`
But this is a doc about using VSCode. Does this refer to a preview version of Visual Studio **Code**? Do I need to have (does the document expect that I have) a version of Visual Studio installed as well?~~

~~In the section "Developing an Uno Platform project > Create the project", it begins with "Let's start by updating the Uno project templates."
Surely this should be "Let's start by **installing** the Uno project templates."~~

~~In the Important callout, the text "In such operating system, you'll need to ...." should be something like "If using such an operating system, ...."
It might also be beneficial to show the full suggested command (so the reader can easily copy it) rather than relying on them to edit it manually.~~

~~In the "Prepare the application" section:~~

~~There's a callout stating, "For this command to work you need to previously have configured Visual Studio Code to be launched from the terminal." 
But will the reader know how to do this? 
What if this hasn't previously been configured?~~

~~Step 2 says, `Visual Studio Code will ask to restore the NuGet packages.`
But this didn't happen for me. 
Does this mean I've got something configured wrong? How do I address this? Does it matter?
I got a separate prompt that I need to install `Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension`, but this isn't in the prerequisites.
What is the full list of extensions that need to be installed?~~

~~The header "Modify the template" doesn't seem to make sense.
What's the template being modified?
This is modifying the content of the page.~~

~~In the section "Run and Debug application > WebAssembly"
The first step is "In the debugger section of the Code activity bar - Select Debug (Chrome, WebAssembly)"
What is the "Code activity bar"? I even went to [the VSCode docs](https://code.visualstudio.com/docs/getstarted/userinterface) and that didn't help. Please use the official name and/or add an image to make it clear.
Here's my editor. What is the "Code activity bar"?
![image](https://github.com/unoplatform/uno/assets/189547/fad920e8-4e2b-4eb4-b9b3-d99bfb903e4d)~~

~~The next (sub)step is "If needed, the project from MyApp.sln to MyApp.Wasm.csproj"
Do what to (or with?) the project? 
How will I tell if it is needed?
And, changing the project from the solution to a project? This is very confusing, and not only from the bad grammar.~~

~~Not knowing what to change, I did nothing and moved on to the next step and pressed `F5`.
After a few seconds of a browser opening and remaining on the "about:blank" page, I got the following error message in a dialog:~~

```ascii
Unable to launch browser: "Could not open ws://localhost:5000/_framework/debug/ws-proxy?browser=ws%3A%2F%2F127.0.0.1%3A52418%2Fdevtools%2Fbrowser%2F4ccd7ad5-ee3f-4a64-8f58-42eaa1151b91"
```

~~There was a button with the option to `Open 'launch.json'` so I tried that, but there was nothing obvious there to suggest what I should do or change.~~

~~I was able to launch the app from the "Run and Debug" window.~~

~~I then followed steps 3 & 4, and the breakpoint was it. (It didn't hit anything as the wording of the step implied.)~~

~~Now what?
Following the steps, this seems a very strange place to leave me as a newbie.
I've got as far as the breakpoint being hit.
Do I stop there?
Does this prove something? Other than that the breakpoint can be hit?
Where do I go for debugging information/help/assistance if it's not hit?~~

As the next section was "Using code snippets" I tried to follow these steps.
None of snippets initially worked as described.
I know tab completions exist and behave like this in VS, but in VSCode, I found I had to wait a few seconds after typing `page` for the autocomplete list to be displayed and _then_ I could press the tab (or enter) key to insert the snippet.

This took a few seconds to be displayed:
![image](https://github.com/unoplatform/uno/assets/189547/6ba645d8-5d49-400c-bd1e-1c6edf589b96)

The document claims "`ctag` creates a new `TextBlock` close XAML tag".
"close XAML tag" isn't a standard term.
Should this be "closed XAML tag"? Technically, this is an "empty" tag.

~~In the section "Updating an existing application to work with VS Code," the two links return 404 errors.~~

**Comment by sasakrsmanovic** [comment]
cc @spouliot

**Comment by spouliot** [comment]
Wow, so much feedback. Thanks!

I'm no the original author(s), but I might be the last one who updated the doc 😒, so I'm guessing some of the intents/history behind the doc as I read thru your comments.

I'll split the changes in a few PRs - at least one for general comments and one for the WebAssembly/Windows (which I have not really used yet). We can discuss each items in the upcoming PRs 😄

**Comment by spouliot** [comment]
> In the "Verify your developer environment" there's a note that:
> When using a Visual Studio Preview version, you will need to run uno-check --pre.

This comes from a different file [doc/articles/use-uno-check-inline-windows-noheader.md](https://github.com/unoplatform/uno/blob/master/doc/articles/use-uno-check-inline-windows-noheader.md), by the way of [doc/articles/use-uno-check-inline.md](https://github.com/unoplatform/uno/blob/master/doc/articles/use-uno-check-inline.md), and is shared with the others getting started docs.

> Do I need to have (does the document expect that I have) a version of Visual Studio installed as well?

No. Maybe the wording should be different since `uno-check --pre` is not only useful for  Visual Studio on Windows.

Suggestion:

> [!NOTE]
> Alternatively you can run `uno-check --pre` to install the **preview** version of the Uno Platform. This is strongly suggested when using a Visual Studio Preview version.

**Comment by sasakrsmanovic** [comment]
Should this one be closed @spouliot  @nickrandolph

**Comment by spouliot** [comment]
@sasakrsmanovic not yet, I'll do another pass when I next test every features (like wasm/win)

**Comment by agneszitte** [comment]
@spouliot what is the status of this issue please?

**Comment by spouliot** [comment]
@agneszitte A lot has changed, starting by the structure of the doc (which was split into several files). I've strikethrough more stuff that are not an issue anymore.

The new Uno templates have changed too, so the documentation refers to an `OnClick` method that does not exist anymore. It seems the other (VS2002, Rider) documents have been shortened not to include those last steps. 

I'll update the document wrt the templates and try the remaining comments.

**Comment by spouliot** [comment]
> I found I had to wait a few seconds after typing `page` for the autocomplete list to be displayed

It's near instantaneous for me. It probably varies project-by-projects and on the system condition (like available memory). However the snippets are only extension-provided JSON definitions loaded by VS Code, there's nothing we can do about performance there.

> Should this be "closed XAML tag"? Technically, this is an "empty" tag.

Agreed. It's fixed with https://github.com/unoplatform/uno.vscode/pull/546

@agneszitte once both PR are merged I'll close this issue

**Comment by spouliot** [comment]
both PR merged, closing
