### ISSUE TITLE
[BREAKING] Adjustment of the FrameworkElement APIs to align with UWP

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#1251]
## What would you like to be added

Currently, on iOS and Android, the FrameworkElement inheritance chain is incorrect for some contols, such as `Image` or `ScrollContentPresenter`. This is related to a legacy structure that was required at some point to ease the creation of controls.

This is not required anymore, and this has the effect keeping interfaces like `IFrameworkElement` or the fact that `UIElementCollection` element types are native views instead of `UIElement`.

This will also remove most of the code that is generated in the T4 "mixins".

## Why is this needed
This will align Uno APIs to the UWP, particularly with regards to `Panel` methods.

## For which Platform:

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows

**Comment by MartinZikmund** [comment]
Will this have an adverse effect on being able to embed native views in XAML? Will there be a workaround?

**Comment by jeromelaban** [comment]
It most likely will not, as there will be an automatic “wrapping” of native view in a some sort of “PlatformControl” that will make this scenario transparent.
