### ISSUE TITLE
Can't put custom dictionary in xaml resource

### ISSUE THREAD

**Issue by HO-COOH** [unoplatform/uno#12523]
### Current behavior

Compilation error. Seems like a code-gen issue in non-UWP platforms.
```
1>C:\Users\Peter\Desktop\test\UnoApp1\UnoApp1.Mobile\Android\AndroidManifest.xml : warning XA4216: AndroidManifest.xml //uses-sdk/@android:minSdkVersion '16' is less than API-19, this configuration is not supported.
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>C:\Users\Peter\Desktop\test\UnoApp1\UnoApp1.Mobile\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\App_1e3e359cf1b3eb7940fb0feeae07a8f1.cs(99,8,99,11): error CS7036: There is no argument given that corresponds to the required parameter 'value' of 'Dictionary<string, Style>.Add(string, Style)'
1>Done building project "UnoApp1.Mobile.csproj" -- FAILED.
```

### Expected behavior

Compile successfully.

### How to reproduce it (as minimally and precisely as possible)

1. Create new project, using `.NET6 UWP` template
2. Add a new class, call `Dict.cs` in Shared project
```cs
using System;
using System.Collections.Generic;
using System.Text;
using Windows.UI.Xaml;

namespace UnoApp1
{
    public class StringToStyleDictionary : Dictionary<string, Style>
    {
    }
}
```
3. Add an entry in `App.xaml`
```
<Application
    x:Class="UnoApp1.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:UnoApp1">
	
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
                <!-- Add resource dictionaries here -->                
            </ResourceDictionary.MergedDictionaries>
            <local:StringToStyleDictionary x:Key="MyResource">
                <Style x:Key="MyStyle" TargetType="Button">

                </Style>
            </local:StringToStyleDictionary>
        </ResourceDictionary>
    </Application.Resources>

</Application>
```
4. Build and run for Android, or anything other than `UWP`
![image](https://github.com/unoplatform/uno/assets/42881734/9a26c6c9-02ee-462a-9412-5139df933991)

This same code runs in UWP
![image](https://github.com/unoplatform/uno/assets/42881734/b995f22a-c16d-4135-be40-eddb7923bf12)

### Workaround

No.

### Works on UWP/WinUI

Yes

### Environment

Uno.SourceGenerationTasks

### Affected platforms

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. You could try inheriting from ResourceDictionary instead of your own type and see if it helps.

**Comment by jeromelaban** [comment]
Thanks for the update. The original scenario is not yet supported (it's pretty rare), and it's likely related to some specifics of the source generator:
https://github.com/unoplatform/uno/blob/f2c59ebc776eab397775aa885426e56ecfa32468/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L1264
when the resource dictionary is built.
