### ISSUE TITLE
The migration guide is incomplete.

### ISSUE THREAD

**Issue by mrlacey** [unoplatform/uno#12546]
## What would you like clarification on:

The documentation on migrating from previous releases (https://platform.uno/docs/articles/migrating-from-previous-releases.html) appears to be incomplete and so is confusing.

Version 4.9 was recently released, but there is nothing in the upgrade guide about updating to use this version.

The guide does say:

> This article details the migration steps required to migrate from one version to the next.

The lack of clear documentation leads to further questions:

- Is it possible to migrate from (or to?) this version?
- Why are other (previous) versions also not listed?
- If the document only lists breaking changes, why does it not state this?
- If it was possible to update without having to do anything other than changing the version numbers, I imagine you'd state this as it could be a useful thing to tell people. So, can I assume this isn't the case?

The document also does not make it clear if the entries for each version apply if updating to that version or updating from that version.
The title of the page is "Upgrading **from** previous releases" but the details _seem_ to refer more towards upgrading **to** those versions.

## Concern?

- [ ] Usage in industry
- [x] Clarification of capabilities
- [x] Getting started with Uno
- [x] Developing with Uno
- [ ] Contributing to the Uno project
- [ ] Publishing your application
- [x] Support
- [ ] Other (please specify):

## For which Platform:

- [x] WebAssembly
- [x] Android
- [x] iOS
- [x] macOS (AppKit)
- [x] Mac Catalyst
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Linux Framebuffer
  - [x] Tizen
- [x] Windows

## Anything else we need to know?

There's also an inconsistency in headline levels that is confusing.

**Comment by jeromelaban** [comment]
Thanks, those are fair comments. The idea behind this page was to include breaking changes between significant versions. For 4.9, there's nothing specific to do, though we will be including it anyways to avoid confusion.
