### ISSUE TITLE
[Themes][Skia] TextBox and PasswordBox PointerOver triggers Text/Border jitter

### ISSUE THREAD

**Issue by silviuo** [unoplatform/uno#12544]
### Current behavior

https://github.com/unoplatform/uno/assets/10283398/7d6a3149-7167-4632-ac3e-caa0ce5b560a
https://github.com/unoplatform/uno/assets/10283398/d2eec86a-d09c-4779-95d1-4e096baa5a15

On Skia only, on hover over a filled in TextBox or PasswordBox control, the text or the border starts shaking (videos attached).
I noticed the issue on latest master. I couldn't reproduce in a sample app.

### Expected behavior

No shaking on PointerOver.

### How to reproduce it (as minimally and precisely as possible)

- open Uno.Themes
- navigate to Controls/PasswordBox or TextBox sample pages
- fill in a box
- exit Focused state and enter PointerOver state

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by MartinZikmund** [comment]
@silviuo This was observed in the sample app because it was using older version of Uno without this fix: https://github.com/unoplatform/uno/pull/12083 . It does not reproduce for me anymore in the latest master 🚀
