### ISSUE TITLE
UITest for "no date selected issue on Time Picker for IOS"

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#1255]
## What would you like to be added:
Create a UI Test for this issue #1228 

This requires this issue to be fixed first: https://github.com/unoplatform/Uno.UITest/issues/8

## For which Platform:

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows

**Comment by ghuntley** [comment]
Resolved in https://github.com/unoplatform/uno/pull/1263
