### ISSUE TITLE
[iOS] ListView display debug message during item deleting animation

### ISSUE THREAD

**Issue by Lee31416** [unoplatform/uno#12558]
### Current behavior

Only on iOS during the deleting animation of a list view item we can see a debug message indicating the path of the method deleting the item

Video : 

https://github.com/unoplatform/uno/assets/72167772/acd1897f-beb3-4d14-bddd-34ead1cc7795

### Expected behavior

There shouldn't be a message. The last item doesn't display an animation when it is deleted which is the expected  behaviour

### How to reproduce it (as minimally and precisely as possible)

1. Launch the sample app on iOS 
2. Click on any item in the list but the last one because the last item works as expected
3. Click on the delete button
4. Watch the animation displaying a message

### Workaround

None found

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.UI.RemoteControl / Uno.WinUI.RemoteControl

### NuGet package version(s)

4.8.15

### Affected platforms

iOS

### IDE

Visual Studio 2019

### IDE version

17.6.2

### Anything else we need to know?

The sample : 

[SampleUnoListViewiOSBug.zip](https://github.com/unoplatform/uno/files/11668155/SampleUnoListViewiOSBug.zip)

**Comment by takla21** [comment]
Since updating to uno `4.9.20` on our project, this bug happens more frequently

**Comment by ajpinedam** [comment]
This Issue was fixed under PR https://github.com/unoplatform/uno/pull/12873 that also fixed other issues.

Adding PR https://github.com/unoplatform/uno/pull/12913 with Runtime and Sample tests
