### ISSUE TITLE
[Gallery][Wasm/iOS/Android]MediaPlayerElement does not display Transport controls for mp3 format(Audio only) and Customizable options.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12574]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/73ad8b7d-de97-43ab-9a08-10b7dc85a9ba

![Audio only](https://github.com/unoplatform/uno/assets/74563602/73e4f98d-87d2-4100-927b-1764dec1ea27)

### Expected behavior

![Audio only correct](https://github.com/unoplatform/uno/assets/74563602/1c29e462-c0f1-4193-8356-9e361e09f9e2)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right (if the menu is not already opened)
3. Click "MediaPlayerElement" from the "UI Components" list.
4. Launch the third sample:
5. "MediaPlayerElement sample using PosterSource, TransportControls, and a URL link with mp3 format (audio only)"
6. Observe that Transport controls does not display.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, iOS, Android

**Comment by jeromelaban** [comment]
Related to https://github.com/unoplatform/uno/pull/12421

**Comment by sakshi173** [comment]
Verified this issue is fixed, closing it.
