### ISSUE TITLE
[Android] Pointer Events are not working properly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#1257]
##  Current behavior

Events raised on Android for PointerXXX are not working properly. See this issue: #1256 

## Expected behavior

Pointer events should be working properly as on iOS and Wasm.

## How to reproduce it (as minimally and precisely as possible)

See the UI Test sample added by:  #1258

## Environment

Nuget Package:

Package Version(s): 1.45

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by nickrandolph** [comment]
I literally just ran into this issue whilst creating a custom control demo.....

**Comment by jeromelaban** [comment]
It used to work partially before the giant refactoring that was done to support Routed Events.
