### ISSUE TITLE
Include old version in output after updating uno.check

### ISSUE THREAD

**Issue by mrlacey** [unoplatform/uno#12627]
## What would you like to be added:

After updating the uno.check tool, it reports the new version that is installed but does not show the previously installed version.

e.g.

```ascii
> dotnet tool update -g uno.check
Tool 'uno.check' was reinstalled with the latest stable version (version '1.12.1').
```

Knowing both version numbers can be helpful in determining what was changed if an update to the tool fixes another issue.

I encountered this as part of trying to determine why something wasn't building.
I tried updating the tool as a first step and with the expectation that I already was on the latest version.
When it told me it had installed a newer version, I became curious to know which version I was on previously.

Being able to tell know that updating fixes a specific issue could be document so others might benefit. 
THis can be more helpful than generic help advice of "update everything and hope that fixes it".

## Why is this needed:

It would help provide more information when updating uno.check fixes an issue.

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates
- [x] Other

## Anything else we need to know?

I appreciate that the current output might come from the dotnet update tool but if it is possible to add more information here it could be useful.

**Comment by jeromelaban** [comment]
Thanks for the report. Unfortunately, that message it coming from the [.NET SDK tool installer](https://github.com/dotnet/sdk/blob/05850247bb4614b6ad84ede6d9b80bf41cd70614/src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateGlobalOrToolPathCommand.cs#L268), and the only way to change this is to submit a PR there.
