### ISSUE TITLE
Can't setHtmlAttribute

### ISSUE THREAD

**Issue by electriceop3** [unoplatform/uno#12621]
### Current behavior

I have installed Uno.WinUI.Runtime.Webassembly, and can add the [HtmlElement()] attribute, but when I try to setHtmlAttribute(), I get an error saying **The type 'UIElement' is defined in an assembly that is not referenced. You must add a reference to assembly 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'**. When I install the latest version of Uno.UI, 4.9.20, it says it  **Cannot build with both Uno.WinUI and Uno.UI nuget packages referenced.**

### Expected behavior

I install Uno.Winui.Runtime.WebAssembly and am able to use both [HtmlElement()] as well as setHtmlAttribute() without any errors.

### How to reproduce it (as minimally and precisely as possible)

- Create new a new Uno App through the visual studio extension
- Install Uno.WinUI.Runtime.WebAssembly on shared and wasm projects
- Create a new class that inherits from FrameworkElement
- add this.setHtmlAttribute() into constructor
Or download this and then build for wasm: [MinmalRepo.zip](https://github.com/unoplatform/uno/files/11748076/MinmalRepo.zip)

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.9.20

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

4.8.04084

### Relevant plugins

Uno.WinUI.Runtime.WebAssembly

### Anything else we need to know?

When I add the [HtmlElement()] attribute, it adds and needs Uno.UI.Runtime.WebAssembly. This on its own does not cause any errors.

**Comment by electriceop3** [comment]
@carldebilly commented this on my Q and A, but it disappeared for some reason, so I figured I'd put it here:  
![image](https://github.com/unoplatform/uno/assets/89930031/dd889388-999a-4b0d-98e4-579435beafc1)
Look like the wrong assembly is used in this package.

**Comment by jeromelaban** [comment]
Thanks for the report, please see the answer from this discussion: https://github.com/unoplatform/uno/discussions/12616
