### ISSUE TITLE
`BreadcrumbBar` not displaying all items

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#12639]
From https://github.com/unoplatform/uno/discussions/11555

Please find attached the sample application to demonstrate the bug in breadcumbar.  The issue is when there are many entries, the flyout shows 1 entry on 1st click and all entries on 2nd click.

I am also attaching the screen capture video. 

[BreadCumBarBug.zip](https://github.com/unoplatform/uno/files/10948287/BreadCumBarBug.zip)

https://user-images.githubusercontent.com/22019325/224479624-008f20a6-c8e2-44ff-aa40-194800c6738f.mp4

_Originally posted by @jindal1979 in https://github.com/unoplatform/uno/discussions/11555#discussioncomment-5275099_

**Comment by Youssef1313** [comment]
This doesn't repro in SamplesApp for Skia at least.

**Comment by MartinZikmund** [comment]
Seems it got fixed by other changes, closing for now!
