### ISSUE TITLE
[GTK][WASM] Fluent ToggleSwitch animation when pressed isn't correct

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno#12643]
### Current behavior

Thumb moving to left side before releasing click, if `IsOn` is set to `true`:

GTK / WASM 

https://github.com/unoplatform/uno/assets/114886335/8031d46a-ab0d-4dbb-833d-b423018e1463

### Expected behavior

The thumb should only move when the click is released as it is on Android, for example:

https://github.com/unoplatform/uno/assets/114886335/ab884a63-919e-4cd5-9b5c-9a84e640438b

### How to reproduce it (as minimally and precisely as possible)

Using Uno.UI 4.10.0-dev.337, add a ToggleSwitch control with `DefaultToggleSwitchStyle` style, set `IsOn` to `True` and run the app.

### Works on UWP/WinUI

Yes

### Affected platforms

WebAssembly, Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by Youssef1313** [comment]
Related: https://github.com/unoplatform/uno/issues/12486

**Comment by kazo0** [comment]
@Youssef1313 / @jeromelaban 

We tried to disabled template pooling and it didn't seem to change anything for this specific issue


Just want to double check, we would disabled pooling by setting this to false somewhere in the App.xaml.cs?
https://github.com/unoplatform/uno/blob/50b3a69ca2ccb14795f9dc860d83043ec7a3ae69/src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs#L116

**Comment by jeromelaban** [comment]
That's correct. It may be another type of issue, maybe a race condition in animations.

**Comment by Youssef1313** [comment]
@kazo0 Are you able to isolate a small repro?

**Comment by eriklimakc** [comment]
Repro: [ToggleSwitchAnimation.zip](https://github.com/unoplatform/uno/files/11791377/ToggleSwitchAnimation.zip)

Just run it on WASM/GTK > Press and hold the ToggleSwitch. The thumb moves before releasing the click.

I didn't get to reproduce the WASM Specific issue where the thumb starts at the left side when `IsOn` is `true`. Maybe it's specific of Themes Sample. Will investigate this one more.

@Youssef1313

**Comment by Youssef1313** [comment]
> I didn't get to reproduce the WASM Specific issue where the thumb starts at the left side when IsOn is true

If you try an older Uno version, does it work? It will be perfect if you could spot which version regressed this

**Comment by Youssef1313** [comment]
> I could test and it was working is 4.9.0-dev.587. In 4.9.0-dev.877

that's good info!

This is the diff for these two versions:

https://github.com/unoplatform/uno/compare/790793c44112a9dcc2b4de97f34ce59ba57d60f9..01fae56c0feafef14f6ae8aa9a53b885621d9124

**Comment by jeromelaban** [comment]
By the looks of it. @Xiaoy312 does this look familiar?

**Comment by morning4coffe-dev** [comment]
@MartinZikmund This is the same issue I mentioned in your conversation. It can be clearly seen on inicialization in Gallery Canary on ToggleSwitch - all styles.

![image](https://github.com/unoplatform/uno/assets/78549750/62942f69-5ead-4f0e-b51f-80b9bae5aadc)

**Comment by kazo0** [comment]
This is also affecting the new Material ToggleSwitch style from [here](https://github.com/unoplatform/Uno.Themes/pull/1031)

cc: @jeromelaban

**Comment by eriklimakc** [comment]
Not sure if it's related, but on my changes for M3 ToggleSwitch (https://github.com/unoplatform/Uno.Themes/pull/1031) removing [this animation](https://github.com/unoplatform/Uno.Themes/blob/a1a58893cbe886fdb59801b1ad790100aaeb4a1d/src/library/Uno.Material/Styles/Controls/v2/ToggleSwitch.xaml#L1108) fixed the thumb in the wrong position.

cc @Youssef1313 @jeromelaban @kazo0

**Comment by MartinZikmund** [comment]
Reopened for backport

**Comment by Youssef1313** [comment]
Backport is done with https://github.com/unoplatform/uno/pull/13114

**Comment by Youssef1313** [comment]
This is reproducing on latest master.

**Comment by agneszitte** [comment]
Re-Open for backport PR

**Comment by sakshi173** [comment]
Verified this issue is fixed, closing it.

**Comment by agneszitte** [comment]
Thanks @sakshi173 really appreciated !
