### ISSUE TITLE
[Gallery][Wasm/iOS/Android]MediaPlayerElement Fastforward and Fastrewind button is not working properly for all options.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12649]
### Current behavior

when click on Fast-forward or Fast rewind button  sound of media player gets very slow and blur.

### Expected behavior

The sound should work properly when click 

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right (if the menu is not already opened)
3. Click "MediaPlayerElement" from the "UI Components" list.
4. Launch first or third sample:
5. "MediaPlayerElement sample using PosterSource, TransportControls, and a URL link with mp3 format (audio only)"
6. Click on Fastforward and Fastrewind button.
7. Notice that sound of video is get bad and does not play properly.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS

**Comment by rafael-rosa-knowcode** [comment]
The MediaPlayerElement for Android and IOS does not have the PlaybackRate implemented.
Therefore, we were unable to update the playbackrate speed as with GTK and Wasm.
So, when I had created the resource, I implemented an update to the current time position value (mediaPlayer.PlaybackSession.Position) (both up (foreward) and down (rewind)).
With that we have a time acceleration in sequence (2x, 4x,..) but the sound is not sequential (like accelerated using the PlaybackRate.)

In that case, should we remove the feature from mobile, while it's not possible to do something similar to the playbackrate update?


For the moment:
Now we limit the speed as the Windows Platform.
And we mute the audio when rewind as the windows Platform.
And we make the Pause stop the Fastforeward or FastRewind when the pause is tap, but not paused the video..
In this PR: https://github.com/unoplatform/uno/pull/12713

**Comment by MartinZikmund** [comment]
Done!

**Comment by sakshi173** [comment]
@agneszitte this issue is fixed and can close. (Only I am seeing when click Fast rewind button then sound of the video stops but the video is rewinding properly. please let me know if I need to open separate defect for that.

**Comment by agneszitte** [comment]
> @agneszitte this issue is fixed and can close. (Only I am seeing when click Fast rewind button then sound of the video stops but the video is rewinding properly. please let me know if I need to open separate defect for that.

What do you think @MartinZikmund / @rafael-rosa-knowcode ?

**Comment by jeromelaban** [comment]
Let's open an new one @sakshi173, thanks!

**Comment by sakshi173** [comment]
As @jeromelaban suggested, will open new defect for sound issue, but this issue is fixed due to that closing it.
