### ISSUE TITLE
[Gallery][iOS/Android][MediaPlayerElement] For the 'Sample using a playlist' option when click Full screen option and close the mobile and reopen it, gallery app getting freeze.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12659]
### Current behavior

click on 'sample using playlist 'and then play video and then click full screen option and let the video keep on running.
Now close the mobile and again open it, the app opens automatically and the gallery app gets freeze.
https://github.com/unoplatform/uno/assets/74563602/4b5b50cb-0e4d-4b6f-b3e6-7e53babe5fad

### Expected behavior

The video should automatically get paused and the close button should display to close the window.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right (if the menu is not already opened)
3. Click "MediaPlayerElement" from the "UI Components" list.
4. Launch the last sample:
5. "MediaPlayerElement sample using a Playlist.
6. Click on start button to start video.
7. Now flip the mobile.
8. Click on the 'Full Screen' option.
9. Close the mobile.
10. Open mobile.
11. Notice that the same mediaplayer window where we stopped but the screen got freeze for app and there is no option to go back or close the current window in the gallery app.(due to that the only option to close the gallery app and reopen it.)

### Works on UWP/WinUI

None

### Affected platforms

iOS
Android

**Comment by rafael-rosa-knowcode** [comment]
I've tried it on the emulator and on the local device.
And failed to reproduce the situation.

**Comment by agneszitte** [comment]
@sakshi173 can you double check if you are still able to reproduce this issue please 
If so, can you share with @rafael-rosa-knowcode the additional details
Thanks in advance

**Comment by sakshi173** [comment]
@rafael-rosa-knowcode and @agneszitte , Yes still I am able to reproduce this issue. 
Please look the video and Screenshot, when open the Gallery app there is no back button or close button or anything to close the window.

https://github.com/unoplatform/uno/assets/74563602/90cd129b-184e-405e-b536-68103d03a1d5

![mediaplayer issue pic](https://github.com/unoplatform/uno/assets/74563602/aa70d0c0-ae48-4479-b245-6a0fb52601cd)

**Comment by rafael-rosa-knowcode** [comment]
Thanks @sakshi173.
Now I understand the problem.
When we enter fullscreen mode, the button to go back from fullscreen is not appearing. 
Soon we couldn't leave the screen and we had to close the application.
This issue will be resolved with PR https://github.com/unoplatform/uno/pull/13169

**Comment by MartinZikmund** [comment]
Reopened for backport

**Comment by sakshi173** [comment]
@agneszitte, Still this issue is present, please let me know is it available to retest today or need to test tommorow.

**Comment by sakshi173** [comment]
@rafael-rosa-knowcode and @agneszitte is I need to retest it rightow or wait as Rafael said will be fix on the PR.

**Comment by agneszitte** [comment]
Re-Open for Backport PR

**Comment by sakshi173** [comment]
This **issue is resolved when we follow the suggest steps. ** attached is the video for the working scenario.

https://github.com/unoplatform/uno/assets/74563602/31447d96-cbe4-4122-977c-199f9314c5ab


1. Open Uno Gallery APP
2. Click Burger Menu on the left top right (if the menu is not already opened)
3. Click "MediaPlayerElement" from the "UI Components" list.
4. Launch the last sample:
5. "MediaPlayerElement sample using a Playlist.
6. Click on start button to start video.
7. Now flip the mobile.
8. Click on the 'Full Screen' option.
9. Close the mobile.
10. Open mobile.
11. Notice that the same mediaplayer window where we stopped but the screen got freeze for app and there is no option to go back or close the current window in the gallery app.(due to that the only option to close the gallery app and reopen it.)

**Comment by MartinZikmund** [comment]
This is only relevant to native, and full screen support will be reworked
