### ISSUE TITLE
[Gallery][Wasm/Android/iOS]MediaPlayerElement , Fastforward and Fastrewind buttons are not similar to windows.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12651]
### Current behavior

![Fastforward](https://github.com/unoplatform/uno/assets/74563602/653a340a-0392-4fd2-b5f0-99b4fdd25edf)

### Expected behavior

Fastforward and Fastrewind buttons should be similar to windows.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right (if the menu is not already opened)
3. Click "MediaPlayerElement" from the "UI Components" list.
4. Launch the fourth sample:
5. "MediaPlayerElement sample using customizable options"
6. Check AreTransportControlsEnabled and IsFastForwardButtonVisible and IsFastRewindButtonVisible option and uncheck all the other options
7. Observe that Fastforward and Fastrewind buttons are different from Windows.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by Robert-Louis** [comment]
@sakshi173 the arrow look similar in latest

Android 

![image](https://github.com/unoplatform/uno/assets/16021239/0f4e1d1f-68e2-411d-9fe2-5319924dbb17)

iOS 

![image](https://github.com/unoplatform/uno/assets/16021239/0925f0f5-b643-4e0d-a12b-9782d80fb0f0)

UWP 
![image](https://github.com/unoplatform/uno/assets/16021239/3a462e3b-06a5-4f4a-9b2d-77d7feac9bd0)

**Comment by Robert-Louis** [comment]
@sakshi173 can you confirm on your side that there are now similar ?

**Comment by sakshi173** [comment]
@Robert-Louis, I am not able to  verify this issue as the Gallery canary build is crashing for windows platform.

**Comment by rafael-rosa-knowcode** [comment]
Follow the Windows Version. Looks similar on the last.

![image](https://github.com/unoplatform/uno/assets/116665025/729c0fdd-819e-48f8-b0b8-ac3a44ce4179)

**Comment by agneszitte** [comment]
> @Robert-Louis, I am not able to verify this issue as the Gallery canary build is crashing for windows platform.

@sakshi173 Windows Gallery canary should be fixed in the next canary build

**Comment by sakshi173** [comment]
@MartinZikmund,  the Fast forward and rewind button are displaying in the windows version as present in the below screenshot. could you please confirm is it only on Microsoft side or if it is related to the Uno style version of the code for windows?
![image](https://github.com/unoplatform/uno/assets/74563602/a79421d6-4ab7-4875-98f9-2795ca79048e)

**Comment by sakshi173** [comment]
@MartinZikmund, please let us know your comments on this issue.

**Comment by agneszitte** [comment]
@sakshi173. @MartinZikmund will check if we are not missing the two icons in the Uno.Fluent font
He will keep us updated

**Comment by agneszitte** [comment]
@sakshi173 seems to be a bug on the Microsoft side for the icon (if tested on Windows 10), we just checked with @MartinZikmund.
With Windows 11 it is fine (cf. screenshot below)
![image](https://github.com/unoplatform/uno/assets/16295702/aba61a61-5b77-4c89-a220-7dff6d6a9a65)
We will report it and link it to this issue.
But it is not an Uno-related issue, so I am closing this issue.

---

Related code on the Microsoft side
![image](https://github.com/unoplatform/uno/assets/16295702/7578047d-ba4e-4d1e-8252-0e83f7d73eb0)
VS
![image](https://github.com/unoplatform/uno/assets/16295702/4ccca5ba-49d3-43a4-8b6c-da75c09fd269)
