### ISSUE TITLE
[Gallery][Wasm] MediaPlayerElement, [X] Close button does not work for customizable option once click on the last sample option.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12653]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/c4524125-9d8b-4b66-95b0-392126b428a1

![Close button](https://github.com/unoplatform/uno/assets/74563602/7d4f2f98-72f4-4f71-9691-8be9957e4e36)

### Expected behavior

When click close button, mediaplayer window for Customizable option should get close.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right (if the menu is not already opened)
3. Click "MediaPlayerElement" from the "UI Components" list.
4. Click on the last sample:
5. "MediaPlayerElement sample using a Playlist.
6. Observe that the nothing is happening.
7. Now click on the 4th sample
8. "MediaPlayerElement sample using customizable options"
9. Check and uncheck some options.
10. Click on the close[X] button on the left top side.
11. Notice that close button is not working.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by rafael-rosa-knowcode** [comment]
Feature items/playlist is just implemented for __ANDROID__ || __IOS__ || __MACOS__

![image](https://github.com/unoplatform/uno/assets/116665025/fc7b1fc3-0451-4dd4-a0b5-381f64f8eff8)

So in the Sample 5 (Playlist) we just show the first video.
And as requested we disable the feature on unsupported platform, so the Sample 5, playlist, do not show on other platforms.

![image](https://github.com/unoplatform/uno/assets/116665025/05ea6257-19b1-4482-8180-4dd616f3fbe9)

And i add the references to test the MediaPlayer Skia on windows

**Comment by rafael-rosa-knowcode** [comment]
This problem cannot happen again.
Because we validate if the playlist is being implemented.

![image](https://github.com/unoplatform/uno/assets/116665025/efd8f3de-d5c8-45c6-b853-eb8f3676c5fa)

**Comment by agneszitte** [comment]
Thanks for the verification @rafael-rosa-knowcode, closing this issue then

**Comment by agneszitte** [comment]
Waiting for Backport PRs to be merged before closing the issue

**Comment by agneszitte** [comment]
@sakshi173 if you can verify this issue `tomorrow` please

**Comment by sakshi173** [comment]
@agneszitte, this issue is still present.

**Comment by agneszitte** [comment]
Re-Open for backport PR

**Comment by agneszitte** [comment]
@sakshi173 this issue can be tested again on Monday

**Comment by sakshi173** [comment]
This issue is fixed, closing it.
