### ISSUE TITLE
Load assets error in Android

### ISSUE THREAD

**Issue by Suriman** [unoplatform/uno#12667]
### Current behavior

The svg images fail to load on Android platform.

### Expected behavior

All assets supported by Uno load correctly on all platforms.

### How to reproduce it (as minimally and precisely as possible)

Open the attached project and compile it. Execute the Android project and all the images are loaded except the Svg.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI 4.9.20
[UnoAssetsAndroid.zip](https://github.com/unoplatform/uno/files/11821501/UnoAssetsAndroid.zip)

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.6.3

**Comment by jeromelaban** [comment]
Thanks for the report. Do you notice any error messages in the app output?

**Comment by ADD-Eugenio-Lopez** [comment]
There aren´t any error or exception in the output window.

**Comment by Youssef1313** [comment]
I'm seeing the same behavior for WinUI and Android.

WinUI:

![image](https://github.com/unoplatform/uno/assets/31348972/c228b271-5013-4780-9d26-37f3cf3cf0b0)

Android:

![image](https://github.com/unoplatform/uno/assets/31348972/71550a11-fe23-41b7-b6db-c7cf96c7975a)

Can you please clarify?

**Comment by ADD-Eugenio-Lopez** [comment]
We find the problem that if a SVG is in the App it can be loaded, but when the SVG is in a library it cannot be loaded:
WinUI:
![image](https://github.com/unoplatform/uno/assets/50919329/6fbd643e-8a59-4758-902f-cdb2299d6442)
Android:
![image](https://github.com/unoplatform/uno/assets/50919329/be5bdc46-adb0-4f7e-9c0f-e76e46f0f07a)

**Comment by Youssef1313** [comment]
@ADD-Eugenio-Lopez Are these screenshots from the original repro? If not, can you please update the repro?

**Comment by ADD-Eugenio-Lopez** [comment]
Yes, they are executing the original repro.

**Comment by Youssef1313** [comment]
Well, then for some reason I'm not able to reproduce. @MartinZikmund Any idea?

**Comment by jeromelaban** [comment]
@ADD-Eugenio-Lopez when running the sample that fails under the debugger, could you share the complete output of the debug window? We may be able to find something additional.

**Comment by Suriman** [comment]
Here is the log:
[AndroidOutput.txt](https://github.com/unoplatform/uno/files/11884872/AndroidOutput.txt)

**Comment by Youssef1313** [comment]
```
[DOTNET] [41m[30mfail[39m[22m[49m: Uno.Helpers.DrawableHelper[0]
[DOTNET]       Couldn't find drawable with key: Assets_Icons_help
[DOTNET] [41m[30mfail[39m[22m[49m: Microsoft.UI.Xaml.Media.Imaging.SvgImageSource[0]
[DOTNET]       To use SVG on this platform, make sure to install the Uno.WinUI.Svg package.
[DOTNET] [41m[30mfail[39m[22m[49m: Microsoft.UI.Xaml.Media.Imaging.SvgImageSource[0]
[DOTNET]       To use SVG on this platform, make sure to install the Uno.WinUI.Svg package.
[DOTNET] [41m[30mfail[39m[22m[49m: Uno.Helpers.DrawableHelper[0]
[DOTNET]       Couldn't find drawable with key: Uno_Library1_Assets_Icons_dashboard_vector
[DOTNET] [41m[30mfail[39m[22m[49m: Microsoft.UI.Xaml.Media.Imaging.SvgImageSource[0]
[DOTNET]       To use SVG on this platform, make sure to install the Uno.WinUI.Svg package.
```

**Comment by ADD-Eugenio-Lopez** [comment]
We insert the package reference to Uno.WinUI.Svg version 4.9.20 in the project UnoApp1.Mobile and the result is the same without the recommendation to include tha package:
![image](https://github.com/unoplatform/uno/assets/50919329/11d622f1-779a-4b05-b284-9d8846b6e3aa)

**Comment by ADD-Eugenio-Lopez** [comment]
We have tried to add in the project UnoApp1.Mobile the package SkiaSharp.View.Uno.WinUI verion 2.88.3 and the package Svg.Skia version 0.5.18 but the result is the same.

**Comment by jeromelaban** [comment]
Thanks for the update. Could you provide a [binlog of the build](https://platform.uno/docs/articles/uno-builds-troubleshooting.html) on your machine?

**Comment by Suriman** [comment]
Sure, here are the binary logs:
[BinLogs.zip](https://github.com/unoplatform/uno/files/11913644/BinLogs.zip)

**Comment by jeromelaban** [comment]
The binlogs helped. There are two issues at play here:
1. The assembly that contains the assets is not referenced in code, making its content not propagated to the packaged app. Adding a `typeof(UnoLibrary1.Class1).ToString();` is enough to get the assets available.
2. It seems that for some reason, the `.` in `Uno.Library1` is causing issues in the name resolution. Removing the `.` will make the assets load properly.

While we may not fix the first issue, as it's relatively rare to have "assets only" libraries, the second part is problematic. We'll let you know when a fix is available.

**Comment by ADD-Eugenio-Lopez** [comment]
We have removed the . in the name of the library Uno.Library1 in the repro and with that it has been enough to correctly see the SVG icon in Android, it has not been necessary to reference it in code.
![image](https://github.com/unoplatform/uno/assets/50919329/c0f0d8f9-f809-41ad-b054-62556fc9413e)
That the fix is solved so that it supports a . in the name of the packages is necessary for us since in many of our projects we have a . in its name.

**Comment by jeromelaban** [comment]
@ADD-Eugenio-Lopez thanks for the update. https://github.com/unoplatform/uno/pull/12886 will the project name issue.

**Comment by ADD-Eugenio-Lopez** [comment]
I have tried to update the repro nugets with the latest version and I have detected that Android now does not show the SVG of the assets included in UnoApp1:
![image](https://github.com/unoplatform/uno/assets/50919329/8fd0ad6f-84fe-4567-9339-2b75cf496fe6)
I know that the issue has been closed, but I think it may be due to the fix to be able to see the SVG in libraries that contain a period.

**Comment by jeromelaban** [comment]
Thanks for the update. 

In your sample, the `help.svg` image is included as an `UnoImage`. This means that in the app, it's not an `svg` anymore, as it has been converted to a set of multi-resolution `png` images. You'll need to load this asset using `ms-appx:///UnoApp1/Assets/Icons/help.png` instead.

**Comment by ADD-Eugenio-Lopez** [comment]
Thanks for the answer.

Yes, using the help.png it works, but if we eliminate the use of UnoImage to have only SVG available, the icon is not shown and in the rest of platforms (Wasm and WinUI) it is visible, in addition until the update of the FIX the SVG was visible, that's why it indicated this change in behavior.

**Comment by ADD-Eugenio-Lopez** [comment]
I have tried to unistalling the app and reinstall the application, but the result is the same. I have tried to install the app in other device and in an emulator but ever time the result is the same, it doesn't show the help.svg.

**Comment by jeromelaban** [comment]
@ADD-Eugenio-Lopez thanks for the update. Per #12925, the cache may not necessarily be cleaned and cause the issue.

Can you provide the output logs of the app?

**Comment by Suriman** [comment]
Sure @jeromelaban:
[AndroidOutput2.txt](https://github.com/unoplatform/uno/files/12112082/AndroidOutput2.txt)

**Comment by jeromelaban** [comment]
Thanks. Yes, this is the same cause as the previously, the cache is incorrect. An update from https://github.com/unoplatform/uno/pull/12945 will help.
