### ISSUE TITLE
[Gallery][WASM/iOS][MediaPlayerElement] 'Exit Full screen' Icon is not displaying correctly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12660]
### Current behavior

![full screen icon](https://github.com/unoplatform/uno/assets/74563602/56ea9435-4afa-49d1-ab9d-35aa44d762c7)

### Expected behavior

The Icon should display correctly.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right (if the menu is not already opened)
3. Click "MediaPlayerElement" from the "UI Components" list.
4. Launch the fourth sample:
5. "MediaPlayerElement sample using customizable options"
6. Click on the Full screen option on the Transportcontrol bar.
7. Notice that the 'Exit Full screen' icon is not displaying correctly.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, iOS

**Comment by MartinZikmund** [comment]
Reopened for backport

**Comment by sakshi173** [comment]
@rafael-rosa-knowcode , @agneszitte, @jeromelaban, @MartinZikmund ,Still this issue is present.
Below is the screenshot. please let me know your views.
![mediaplayer 1](https://github.com/unoplatform/uno/assets/74563602/33c317d7-236d-4126-93e3-e0d7721103a5)

**Comment by agneszitte** [comment]
Re-Open for backport PR

**Comment by sakshi173** [comment]
@agneszitte I retested this defect and its working fine for WASM but still issue is present for iOS.
![mediaplayer 3](https://github.com/unoplatform/uno/assets/74563602/22513196-a873-4bb6-93f5-1955887b6d47)
![mediaplayer 4](https://github.com/unoplatform/uno/assets/74563602/68b0263e-c9aa-452b-8f36-10510c8b5c32)

**Comment by MartinZikmund** [comment]
Full screen support will be reworked in a separate issue
