### ISSUE TITLE
[Gallery][Android][MediaPlayerElement] 'Exit Full screen' Icon is missing or not displaying.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12661]
### Current behavior

![exit sceen android issue](https://github.com/unoplatform/uno/assets/74563602/634f6252-7dec-4c2e-bb4a-a0d4f4af076b)

### Expected behavior

'Exit full screen' Icon should display.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right (if the menu is not already opened)
3. Click "MediaPlayerElement" from the "UI Components" list.
4. Launch the fourth sample:
5. "MediaPlayerElement sample using customizable options"
6. Click on the Full screen option on the Transportcontrol bar.
7. Notice that the 'Exit Full screen' icon is not displaying.

### Works on UWP/WinUI

None

### Affected platforms

Android

**Comment by MartinZikmund** [comment]
Reopened for backport

**Comment by sakshi173** [comment]
@MartinZikmund, @agneszitte and @jeromelaban I am not able to retest this defect as the "MediaPlayerElement sample using customizable options" is not opening. below is the video for this issue.

https://github.com/unoplatform/uno/assets/74563602/9b50edd0-d157-42b6-9023-225586f2eb25

**Comment by agneszitte** [comment]
> @MartinZikmund, @agneszitte and @jeromelaban I am not able to retest this defect as the "MediaPlayerElement sample using customizable options" is not opening. below is the video for this issue.

@sakshi173 when https://github.com/unoplatform/uno/issues/12697 will be closed, you will be able to properly re-test this issue

**Comment by sakshi173** [comment]
Verified this issue is fixed, closing it.

**Comment by agneszitte** [comment]
Thank you @sakshi173 !
