### ISSUE TITLE
Uno (.NET 6, UWP) WASM is .NET 5

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#12675]
## Current behavior
When using the Uno Platform App (.NET 6, UWP) the WASM project that got generated did not display in the VS explorer and when opening the project, I noticed that it is on .NET 5. 

## Environment
Uno VS Extension: 4.9.13.13

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- 2022 (version: 17.6.3)

**Comment by nickrandolph** [comment]
@morning4coffe-dev  I've moved this issue to the Uno repository which is where the legacy templates are maintained. 
For new projects we are encouraging developers to use the Uno Platform App solution template unless you specifically need the UWP target platform

**Comment by MartinZikmund** [comment]
I think this issue is no longer relevant, can we close @morning4coffe-dev ?

**Comment by jeromelaban** [comment]
It's now targeting net8.
