### ISSUE TITLE
[Gallery][Wasm/Android/iOS]Button(Fluent)-Both 'Back' buttons size are similar but for windows the sizes for Back buttons are different

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12673]
### Current behavior

![button issue](https://github.com/unoplatform/uno/assets/74563602/ad5f61a6-63f3-47e7-96cc-ba9f78de308e)

### Expected behavior

![back button same size correct](https://github.com/unoplatform/uno/assets/74563602/5d542b92-16fd-411a-9700-8903209fcb6e)

### How to reproduce it (as minimally and precisely as possible)

Launch the Uno.Gallery app on Skia.GTK.
Click on “Button” from the "Component" list.
Go to the fluent section.
Go to Back button section.
Notice that both Back buttons size are similar but for windows the sizes for back buttons are different

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS

**Comment by jeromelaban** [comment]
@kazo0 does this look familiar?

**Comment by agneszitte** [comment]
@jeromelaban / @sakshi173 I am closing this issue as it is a WinUI issue, @lesterbotello opened an issue for it on their repo
https://github.com/unoplatform/uno/issues/12673
