### ISSUE TITLE
[Gallery][Wasm]Button(Fluent)-Disabled back button are not displaying as Disabled.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12672]
### Current behavior

![button issue 2](https://github.com/unoplatform/uno/assets/74563602/b2279767-e242-4ab8-afb5-d66649e06251)
![button issue](https://github.com/unoplatform/uno/assets/74563602/7adfd386-1a07-400b-bcde-d0d3fb7dbbec)

### Expected behavior

The disabled 'Back button' should display as disabled.

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app on Skia.GTK.
2. Click on “Button” from the "Component" list.
3. Go to the fluent section.
4. Go to Back button section.
5. Notice that Disabled back button are not displaying as Disabled.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by lesterbotello** [comment]
This is related to #12673, it will be fixed by #12774

**Comment by MartinZikmund** [comment]
Is this still relevant? @lesterbotello

**Comment by Youssef1313** [comment]
It looks like this have been fixed

![image](https://github.com/unoplatform/uno/assets/31348972/3652cf67-97ff-4c01-90d8-70c5c924d971)
