### ISSUE TITLE
[Skia] ImageFailed event not being raised on Image

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#12689]
### Current behavior

[v4.9.20 of Uno]
Attach ImageFailed event handler to Image control
Set ImageSource to a Uri that doesn't exist
ImageFailed is never triggered

### Expected behavior

For any given source either ImageLoaded or ImageFailed should be raised

### Works on UWP/WinUI

None

### Anything else we need to know?

4.8 release (ImageFailed is raised): https://github.com/unoplatform/uno/blob/d1ab57edac0b5eb78a8b4530155838aa959001bb/src/Uno.UI/UI/Xaml/Controls/Image/Image.skia.cs#L76-L83

4.9 release (ImageFailed is not raised): https://github.com/unoplatform/uno/blob/23026f4dc08ed3efc5c2e50ce6302baa86644cca/src/Uno.UI/UI/Xaml/Controls/Image/Image.skia.cs#L74

**Comment by Youssef1313** [comment]
I have wrote a failing test that seems related to this: https://github.com/unoplatform/uno/pull/12441
