### ISSUE TITLE
Stack traces of exceptions are not complete

### ISSUE THREAD

**Issue by NGame1** [unoplatform/uno#1272]
## Current behavior
Stack traces are showing like this:
In Android: 

```
"  at System.Enum.HasFlag (System.Enum flag) [0x00043] in <3a61d48d66dd458fa0b64990b6c8f8cc>:0 \n  at …"

`AndroidEnvironment.UnhandledExceptionRaiser += AndroidEnvironment_UnhandledExceptionRaiser;`

private void AndroidEnvironment_UnhandledExceptionRaiser(object sender, RaiseThrowableEventArgs e)
        {
            var exce = e.Exception;
            e.Handled = true;
        }

```

## Expected behavior
Should show the exception trace completely

Nuget Package:

Package Version(s): dev 2288

Affected platform(s):
- [ ] iOS(Not tested)
- [x] Android (Tested on Android 9)
- [ ] WebAssembly(Not tested)
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.1.6 )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Howdy @ngame1. 

The `AndroidEnvironment_UnhandledExceptionRaiser` eventhandler isn't designed to recover from an exception. It's a place of last resort you can use to do things such as flushing logs to disk. Setting `e.Handled = true` isn't going to save your application. See remarks at https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.unhandledexception?redirectedfrom=MSDN&view=netframework-4.8#remarks

Can you please provide a repro of the code that's creating the stack traces? It's important to clarify if these are coming from mono or from java.
