### ISSUE TITLE
Upgrading to `5.0.0-dev.1155` shows System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#12735]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/31348972/0d9bd123-066b-45af-b24c-f95c7b1532b5)

### Expected behavior

It should work.

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
@jeromelaban I investigated this.

It fails at `global::Uno.UI.RemoteControl.RemoteControlClient.Initialize(GetType());` in the AppHead.InitializeComponent generated code.

![image](https://github.com/unoplatform/uno/assets/31348972/28ce3432-6854-4479-8c92-b9608a527656)

**Comment by Youssef1313** [comment]
Commented out the remote control package reference, but then the app is just black:

![image](https://github.com/unoplatform/uno/assets/31348972/89870861-b298-4acd-ae5f-277042a0059f)

**Comment by jeromelaban** [comment]
Yes, you'll need to update all dependencies to 5.0 compatible bits

**Comment by Youssef1313** [comment]
For TabBar it works properly after updating toolkit. But the RemoteControl error is the only strange thing because I'm using the same version as Uno.WinUI `5.0.0-dev.1155`.

**Comment by jeromelaban** [comment]
Fixed in latest.
