### ISSUE TITLE
pack the project with `dotnet pack` get a error

### ISSUE THREAD

**Issue by SongOfYouth** [unoplatform/uno#12738]
### Current behavior

got a error : unable to load task Microsoft.Build.Packaging.Pri.Tasks.ExpandPriContent from "C:\Program Files\dotnet\sdk\7.0.202\\Microsoft\VisualStudio\v17.0\AppxPackage\\Micro soft.Build.Packaging.Pri.Tasks.dll “

### How to reproduce it (as minimally and precisely as possible)

pack the project with command 'dotnet pack'

### Works on UWP/WinUI

No

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI 4.9.17
CommunityToolkit.Mvvm 8.2.0

### Affected platforms

Build tasks

### IDE

Visual Studio 2022

### IDE version

17.5.3

**Comment by SongOfYouth** [comment]
If pack it by vs2022, it works, but the version of output package always is '1.0.0' even I have set the Properties `Version` and `PackageVersion` to `2.0.1` in msbuild task which before `BuildOnlySettings` task.

**Comment by jeromelaban** [comment]
Thanks for the report. This is a WinAppSDK issue, please see the discussion here: https://github.com/unoplatform/uno/discussions/12471.
