### ISSUE TITLE
Unable to launch app on Android

### ISSUE THREAD

**Issue by NGame1** [unoplatform/uno#1273]
## Current behavior
App fails on launch with the following error
```Unhandled Exception:

System.ArgumentException: The argument type, 'Android.Views.SystemUiFlags', is not the same as the enum type 'Android.Views.StatusBarVisibility'.```

Trace
"  at System.Enum.HasFlag (System.Enum flag) [0x00043] in <3a61d48d66dd458fa0b64990b6c8f8cc>:0 \n  at …"
```

Nuget Package:
Package Version(s):
1.46.0-dev2288 || 1.46.0-dev2670

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Thanks for the report!

Could you please provide a test case that reproduces the issue?

ps. What Android API level  are you using? Are you experiencing this on a simulator on a device?

**Comment by jeromelaban** [comment]
This is most likely fixed by #1270

**Comment by NGame1** [comment]
@ghuntley my target is Android Pie (API Level 28)
@jeromelaban nice.

**Comment by davidjohnoliver** [comment]
#1270 is merged, this should be fixed now.

**Comment by NGame1** [comment]
Yes but in latest build another issue started!
Unhandled Exception:

Java.Lang.NoClassDefFoundError: md567cff875f28d20379ac19e960a3af0b6/LayoutProvider_GlobalLayoutProvider

Trace:
"  at Java.Interop.JniEnvironment+Types.FindClass (System.String classname) [0x00114] in <3beddfcb1eb…"

**Comment by davidjohnoliver** [comment]
> Yes but in latest build another issue started!
> Unhandled Exception:
> 
> Java.Lang.NoClassDefFoundError: md567cff875f28d20379ac19e960a3af0b6/LayoutProvider_GlobalLayoutProvider
> 
> Trace:
> " at Java.Interop.JniEnvironment+Types.FindClass (System.String classname) [0x00114] in <3beddfcb1eb…"

If you clean and rebuild your app do you still get the error?

**Comment by NGame1** [comment]
Yes I tried it before. Didn't worked. Reverting back to 2264 only helped me

**Comment by davidjohnoliver** [comment]
@NGame1 I'm unable to repro with latest Uno (2302). There was a change to `GlobalLayoutProvider` in #850, but it's a private class so there shouldn't be a binary breaking change.

If you uninstall the app from your device and then re-deploy, do you still have the issue? Are you able to repro in a newly-created project?

**Comment by NGame1** [comment]
@davidjohnoliver please give me a direct contact way I will send my current solution to you.

**Comment by davidjohnoliver** [comment]
@NGame1 You can DM me in our Gitter channel: https://gitter.im/uno-platform/Lobby

**Comment by NGame1** [comment]
I test it using the latest release 2253 it's now fine. 
But it didn't work on 2311.

**Comment by NGame1** [comment]
I found this new error
![image](https://user-images.githubusercontent.com/19765248/61810634-e1c85800-ae54-11e9-955c-e67b645187a0.png)

**Comment by davidjohnoliver** [comment]
The 2253 release was actually a special feature branch (feature.iosTouches.2253) - 2311 is currently the latest version. We've removed 2253 from NuGet to avoid confusion.

**Comment by ghuntley** [comment]
Thank you!
