### ISSUE TITLE
C# Edit and Continue doesn't work on Android

### ISSUE THREAD

**Issue by NGame1** [unoplatform/uno#1274]
## Current behavior
When trying to use C# edit and continue it show the following error
![image](https://user-images.githubusercontent.com/19765248/61588978-3b145b00-abb9-11e9-9852-86d7ad166e6c.png)

Nuget Package:
Package Version(s):
V1.46.0-dev2264

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Howdy @NGame1, can you please attach a test case that reproduces this issue?

**Comment by andreinitescu** [comment]
Should edit and continue work in Android?

**Comment by NGame1** [comment]
@andreinitescu It doesn't work on Mono? 🤔 
I don't know really.
I saw on Xamarin it had a live player and somehow xaml editing work on it that doesn't work on UnO.
But really don't know about C# edit and continue.

**Comment by ghuntley** [comment]
> Should edit and continue work in Android?

Nice catch. No, C# Edit & Continue does not work with Xamarin.Android or Uno w/Android.
