### ISSUE TITLE
[WASM] not support `AssemblyDependencyResolver`

### ISSUE THREAD

**Issue by SongOfYouth** [unoplatform/uno#12759]
### Current behavior

When i new a AssemblyDependencyResolver object, i have got a `System.PlatformNotSupportedException: Operation is not supported on this platform.`, 

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by Youssef1313** [comment]
I think it's not something we control:

https://github.com/dotnet/runtime/blob/2a22adba0b94308a87c41323d26f915a82c74a18/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyDependencyResolver.PlatformNotSupported.cs#L9-L28

**Comment by SongOfYouth** [comment]
> I think it's not something we control:
> 
> https://github.com/dotnet/runtime/blob/2a22adba0b94308a87c41323d26f915a82c74a18/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyDependencyResolver.PlatformNotSupported.cs#L9-L28
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/2d93c2965c6a1e855423ae051adb9385bc4695cd8f1eacd74cfbe08c3059b393/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f376161323133326631623537663630386661326435646538366637653637393930373063323530306339343031656462396232626364396331333766353966382f646f746e65742f72756e74696d65"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyDependencyResolver.PlatformNotSupported.cs at 2a22adba0b94308a87c41323d26f915a82c74a18 · dotnet/runtime](https://github.com/dotnet/runtime)**.NET is a cross-platform runtime for cloud, mobile, desktop, and IoT apps. - runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyDependencyResolver.PlatformNotSupported.c...

Thanks for reply, you are right, i'll close this issue.
