### ISSUE TITLE
UWPSyncGenerator generates invalid syntax for Dependency Properties

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1275]
## Current behavior

`UWPSyncGenerator` generates invalid syntax for Dependency properties.

For normal dependency properties:

    nameof(Property)", typeof(...)

Note the `"` (remanant after replacing string literal with `nameof`)

For attached dependency properties `nameof` cannot be used, as there is no property with such name available.

## Expected behavior

Generated syntax should be valid.

## How to reproduce it (as minimally and precisely as possible)

Run `UWPSyncGenerator`, observe the generated files which contain dependency properties.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
I will fix this.

**Comment by ghuntley** [comment]
doh. This is my fault. Thanks for spotting this and sending in the PR.

**Comment by jeromelaban** [comment]
We'll have to get this tool to run during CI to avoid those issues.
