### ISSUE TITLE
Visual Studio Extension launching multiple .NET Host processes

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#12764]
### Current behavior

Visual Studio extension triggers multiple instances of the Remote Control server process
eg
![image](https://github.com/unoplatform/uno/assets/1614057/d57fc4b0-db52-4b02-a6d3-09bd34ce27ca)

### Expected behavior

Only a single instance of the Remote Control server process should be launched

### Works on UWP/WinUI

None

**Comment by luckypong** [comment]
I also have more than 400 processes running and killing them each time with taskkill.
If you don't clear it, VS will use more than 95% memory.
It seems like 10 are created every second.
The remotecontrol.host.dll seems to keep running.

**Comment by agneszitte** [comment]
Issue fixed with https://github.com/unoplatform/uno.studio/pull/330
Fix available with latest VS Uno Platform Project Template version **4.9.17.18**
(cc @luckypong)

**Comment by iurycarlos** [comment]
Exactly the same here still happening with 4.9.17.18.

**Comment by doum-vigeant-nventive** [comment]
This issue doesn't occur anymore to me after updating to 4.9.17.18 and restarting my pc.

**Comment by agneszitte** [comment]
Related discussion : https://github.com/unoplatform/uno/discussions/12775

**Comment by agneszitte** [comment]
> Exactly the same here still happening with 4.9.17.18.

Normally related to this issue https://github.com/unoplatform/uno/issues/12784, fixed with https://github.com/unoplatform/uno/pull/12785 & https://github.com/unoplatform/uno/pull/12801
