### ISSUE TITLE
ApplicationData.Current.LocationSettings bug

### ISSUE THREAD

**Issue by NGame1** [unoplatform/uno#1276]
## Current behavior
My sample code that doesn't work
```
internal class AppSettingsHelper
    {
        private static StorageFolder AppLocalSettingsFolder => ApplicationData.Current.LocalFolder;
        private static ApplicationDataContainer AppSettings => ApplicationData.Current.LocalSettings;

        public static AppInternalSettingsCore AppInternalSettings => AppSettings.Values["AppInternalSettings"] == null ? new AppInternalSettingsCore() : JsonConvert.DeserializeObject<AppInternalSettingsCore>(AppSettings.Values["AppInternalSettings"].ToString());
        
        public static int ApplicationTheme
        {
            get => AppInternalSettings.ApplicationTheme;
            set
            {
                AppInternalSettingsCore c = AppInternalSettings;
                c.ApplicationTheme = value;
                AppSettings.Values["AppInternalSettings"] = JsonConvert.SerializeObject(c);
            }
        }

        public static bool FirstLaunch
        {
            get => AppInternalSettings.FirstLaunch;
            set
            {
                AppInternalSettingsCore c = AppInternalSettings;
                c.FirstLaunch = value;
                AppSettings.Values["AppInternalSettings"] = JsonConvert.SerializeObject(c);
            }
        }
    }
```
It fails with the following error 
"Operation is not valid due to the current state of the object."
Trace:
"  at Windows.Storage.ApplicationDataContainer+SharedPreferencesPropertySet.get_Item (System.String k…"

It has a workaround, fortunately.
Change the below line:
`public static AppInternalSettingsCore AppInternalSettings => AppSettings.Values["AppInternalSettings"] == null ? new AppInternalSettingsCore() : JsonConvert.DeserializeObject<AppInternalSettingsCore>(AppSettings.Values["AppInternalSettings"].ToString());`
 with this one:
`public static AppInternalSettingsCore AppInternalSettings => AppSettings.Values.ContainsKey("AppInternalSettings") == false ? new AppInternalSettingsCore() : JsonConvert.DeserializeObject<AppInternalSettingsCore>(AppSettings.Values["AppInternalSettings"].ToString());`

Nuget Package:
Package Version(s):V1.46.0-dev2264

Affected platform(s):
- [ ] iOS (Not Tested)
- [x] Android
- [ ] WebAssembly
- [ ] Windows (Not Tested)
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Howdy @NGame1, can you please provide a project that reproduces this? ie. `File -> New Uno Application -> <implement repro in the Android project>`

**Comment by MartinZikmund** [comment]
Does the same code run under UWP without exception?

**Comment by NGame1** [comment]
@MartinZikmund yes it does. In UWP if it can't find a key it will return null. 
@ghuntley Yes I will create a sample repro for you

**Comment by MartinZikmund** [comment]
I will try to reproduce in unit tests

**Comment by MartinZikmund** [comment]
@NGame1 Can you verify this has been fixed in latest preview build :-) ?

**Comment by NGame1** [comment]
@MartinZikmund In reality no. My current project can not run on build 2311.

**Comment by ghuntley** [comment]
@NGame1 can you open another issue that shares with us what's preventing you from using build 2311? Thanks.
