### ISSUE TITLE
Visual Studio not recognizing "Page" or "Grid" when Uno App re opened giving error Type Page not found

### ISSUE THREAD

**Issue by AlistairMcKinnon** [unoplatform/uno#12776]
### Current behavior

Create New Uno Platform App in Visual Studio
Open MainPage.xaml, make small amendment by adding a TextBox
Hover over "Page", it says Microsoft.UI.XAML.Controls.Page
Run Windows version, everything works fine.
Run Android version on attached Android device, works fine
Close Visual Studio
Open Visual Studio
Re open App
Now MainPage.xaml underlines Page and Grid and says type not found are you missing an assembly.

### Expected behavior

When App reopened, it should recognise Page and Grid as part of Microsoft.UI.XAML.Controls.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen), Windows

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. Could you indicate which version of visual studio you are using? (17.?) Also, could you take a screenshot of your visual studio when this happens?

**Comment by MartinZikmund** [comment]
This is because you always need to select Windows as the target in the top left dropdown here in the XAML code window - 
![image](https://github.com/unoplatform/uno/assets/1075116/e6a6cac7-6ee3-4ee1-bac4-48da8ca40033)

**Comment by MartinZikmund** [comment]
See https://github.com/unoplatform/uno/issues/8774 for more info
