### ISSUE TITLE
[Droid] `MenuFlyoutSubItem` get out of screen for the first time shown

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#12771]
### Current behavior

When flyout submenu shown for the first time it gets outside of the screen
![flyout issue](https://github.com/unoplatform/uno/assets/6670150/0d9594bc-199e-4864-a9dc-4aaf5a963614)

### Expected behavior

Flyout shown inside screen

### How to reproduce it (as minimally and precisely as possible)

Repro:
[FlyoutUnoIssue.zip](https://github.com/unoplatform/uno/files/11936012/FlyoutUnoIssue.zip)

### Workaround

Open menu second time

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno 4.9.26

### Affected platforms

Android

**Comment by ramezgerges** [comment]
Just tried this. It reproduces on android, but not on wasm or skia.
