### ISSUE TITLE
[Droid] `ItemsRepeater` is failing to layout in Expander when expanded second time

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#12770]
### Current behavior

When expander opens second time ItemsRepeater inside has invisible items when items get out of viewport of a parent scrollviewer

![items repeater issue](https://github.com/unoplatform/uno/assets/6670150/a0d401fa-4794-4414-b3d1-06a52057fa31)

### Expected behavior

All items layouted

### How to reproduce it (as minimally and precisely as possible)

Repro:
[Uploading ItemsRepeaterIssue.zip…]()

### Workaround

Manipulate scrollviewer to reforce layout

### Works on UWP/WinUI

None

### NuGet package version(s)

Uno 4.9.26

### Affected platforms

Android

**Comment by dr1rrb** [comment]
Hey @FrozDark, thanks for the report.

The link to the "repro" is pointing to the issue itself. Do you have a repro to share with us?

**Comment by FrozDark** [comment]
> Hey @FrozDark, thanks for the report.
> 
> The link to the "repro" is pointing to the issue itself. Do you have a repro to share with us?

My bad

[ItmsRepeaterUnoIssues.zip](https://github.com/unoplatform/uno/files/12078927/ItmsRepeaterUnoIssues.zip)

**Comment by dr1rrb** [comment]
FYI, I actually noticed the same issue on Windows:

![image](https://github.com/unoplatform/uno/assets/8635919/745a50fc-6342-4f23-9aeb-46a171e860bf)

Scrolling or resizing the window is enough to cause make items to appear (like on Android). Most probably the same as https://github.com/microsoft/microsoft-ui-xaml/issues/7738

**Comment by dr1rrb** [comment]
Hey @FrozDark so I was finally able to find a patch/hack for windows, please have a look here https://github.com/microsoft/microsoft-ui-xaml/issues/7738#issuecomment-1644341914

For the Android version, since I updated to the latest version of Uno (5.0.0-dev.1482), I'm no longer able to repro. Let me know if it's still an issue for you.
