### ISSUE TITLE
Both Uno.UI.MSAL and Uno.WinUI.MSAL are targeting UAP

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#12822]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/31348972/331896e4-f430-4929-9b9f-a9c0737b3463)

![image](https://github.com/unoplatform/uno/assets/31348972/7baf8fbd-cd68-4951-8dfa-4c28e48aa53c)

The WinUI flavor of the package should be using `net7.0-windows10.0.19041.0`

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
That's indeed incorrect, thanks for spotting it!
