### ISSUE TITLE
Always false conditions in Uno.UI.Svg project

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#12825]
`In Uno.UI.Svg.netcoremobile.csproj`, there is the following:

```xml
	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-android'">
		<PackageReference Include="SkiaSharp.NativeAssets.Android" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-ios'">
		<PackageReference Include="SkiaSharp.NativeAssets.iOS" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-maccatalyst'">
		<PackageReference Include="SkiaSharp.NativeAssets.MacCatalyst" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-macos'">
		<PackageReference Include="SkiaSharp.NativeAssets.macos" />
	</ItemGroup>
```

Are these package references needed?

They are included in nuspec, but if we are building without them, should we be removing it both from the csproj and nuspec?

@MartinZikmund Any idea?

**Comment by jeromelaban** [comment]
They're likely needed, yes. If it compiles and runs, it's because there's another SkiaSharp dependency in the head project of an solution that includes them already. It's a conversion issue for net7-8 that we can adjust.
