### ISSUE TITLE
[Hot Reload] Manual way to start remote control service

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#12849]
## What would you like to be added:
Either documentation or a change that allows for the remote control service to be started manually

## Why is this needed:
There are two scenarios for this:
- When authoring runtimetests in the Uno solution for hot reload it's necessary to have the remote control service running.
- When runtimetests for hot reload are run as part of the CI pipeline it's necessary to have remote control service running

In both cases the sequence would be:
- Manually start the remote control service
- Launch the runtime tests.
Some how the address/port of the remote control service needs to be passed into the runtime tests when it's launched.

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?
Note: one workaround for needing to start the remote control service manually when authoring runtimetests from within visual studio, is to have a project in the solution that depends on the remote control nuget package. Assuming that the vsix is installed, this is enough to start the remote control service when the solution loads

**Comment by jeromelaban** [comment]
Implemented as part of HR automated tests: https://github.com/unoplatform/uno/blob/2af701b4898314eef255f6a6c84ac437d596568c/src/Uno.UI.RuntimeTests/Tests/HotReload/Given_HotReloadWorkspace.cs#L30
