### ISSUE TITLE
[Breaking] ViewExtensions is probably unintentionally public

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#12841]
### Current behavior

https://github.com/unoplatform/uno/blob/4e62e2b32bdfb72154b560000e5e1c567c8ba9fb/src/Uno.UI/Extensions/ViewExtensions.visual-tree.cs#L26

I guess it should be internal.

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
It may need to be public because of debugger constraints /cc @Xiaoy312

**Comment by Youssef1313** [comment]
We *could* expose some methods publicly, sure.

Just wanted to make sure this was intentional. So let's close.
