### ISSUE TITLE
Combobox disappears when reopened

### ISSUE THREAD

**Issue by headslash** [unoplatform/uno#12845]
### Current behavior

Opening Combobox with Binding in Itemsource works like it should. Dropdown opens with all options. You select one, it binds back like it should.
You reopen it to select something else and...
The whole view that it is in disappears. There is no way other than resetting the application or reloading it to reset it.

I found it while working on a bigger application that uses smaller generated views that could include comboboxes. in those cases it would delete the childview altogether.

I replicated in a minimalistic/same enviroment in the MainPage.
Both the combobox with or without binding has the same issue.

This is in .net7.

recreating this in .net6 does not give the same issue.

### Expected behavior

Using a combobox for a second time works like it should, not removing the view altogether

### How to reproduce it (as minimally and precisely as possible)

[UnoApp1 - example.zip](https://github.com/unoplatform/uno/files/12002132/UnoApp1.-.example.zip)

### Workaround

Instead of using
```xaml
<ComboBox ItemsSource="{x:Bind Title}"/>
```

using  
```xaml
<ComboBox Grid.Row="3">  
            <ComboBoxItem>ComboBox Item #1</ComboBoxItem>
            <ComboBoxItem IsSelected="True">ComboBox Item #2</ComboBoxItem>
            <ComboBoxItem>ComboBox Item #3</ComboBoxItem>
</ComboBox>
```

Does work but bindings are not really an option in my case.

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

all current updated stable versions
no extra ones

Unoplatform extension 4.9.12.12
using .net7

### Affected platforms

WebAssembly, Skia (WPF), Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

17.6.2

### Relevant plugins

none

**Comment by jeromelaban** [comment]
Thanks for the report. In the repro sample you're providing, you're using a string as the input, and this is not supported by WinUI.

Is your original issue using the same "string" binding as the item source?

**Comment by headslash** [comment]
The string binding was just a simple way to make an example because it has the exact same response as the other inputs.
which are string[] (at the start of the project for simplicity) and later ObservableCollection<string>.
In both cases I have problems with the disappearing Views.

I also tested both Binding and x:Bind but those still gave the issue regarding the disappearing views while still functioning properly.

**Comment by headslash** [comment]
I'm an idiot, sorry first time doing a propper issue, This is not professional. My bad.

**Comment by headslash** [comment]
in both webassembly and skia.wpf.
Both have the issue

**Comment by jeromelaban** [comment]
Thanks for the update.

## Note for contributors

It seems that for some reason, the contents of the Frame is getting cleared when opening the popup for the second time. This does not repro in  the playground (http://playground.platform.uno/#ef1ff7f8). It is not related to `x:Bind` nor material theming.
