### ISSUE TITLE
[WASM] FlipView scroll bars are visible

### ISSUE THREAD

**Issue by silviuo** [unoplatform/uno#12889]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/10283398/d38e8b1d-d085-406f-9f4b-cf03b85596d2)

In the latest package versions, the FlipView shows horizontal/vertical scroll bars.

### Expected behavior

Scroll bars are not visible.

### How to reproduce it (as minimally and precisely as possible)

http://playground.platform.uno/#553281e6
[SampleApp.zip](https://github.com/unoplatform/uno/files/12044121/SampleApp.zip)

### Works on UWP/WinUI

Yes

### NuGet package version(s)

"Uno.Resizetizer" Version="1.2.0-dev.4"
"Microsoft.Windows.Compatibility" Version="7.0.0"
"Uno.Toolkit.WinUI" Version="4.0.0-dev.49"
"Uno.Toolkit.WinUI.Material" Version="4.0.0-dev.49"
"Uno.Wasm.Bootstrap" Version="8.0.0-dev.228"
"Uno.Wasm.Bootstrap.DevServer" Version="8.0.0-dev.228"
"Uno.WinUI.WebAssembly" Version="5.0.0-dev.1392"
"Uno.WinUI.RemoteControl" Version="5.0.0-dev.1392" Condition="'$(Configuration)'=='Debug'"
"Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.0-dev.1392"
"CommunityToolkit.Mvvm" Version="8.1.0"
"Uno.Extensions.Logging.WebAssembly.Console" Version="1.6.0-dev.2"
"Microsoft.Extensions.Logging.Console" Version="7.0.0"

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.6.3

**Comment by jeromelaban** [comment]
@ajpinedam is this something you've see? @silviuo could you try to reproduce in the playground and canary playground?

**Comment by silviuo** [comment]
Hi @jeromelaban, I had attached a sample app and posted a playground link in the repro steps. I didn't realize that when I saved the snippet it linked to the non-canary playground. Here is the updated link for the canary one:
https://playgroundcanary.z19.web.core.windows.net/#553281e6

The issue is only visible on the canary.

**Comment by ajpinedam** [comment]
@silviuo  thanks for the information and for the sample.

@jeromelaban  No, I haven't seen that before. It seems the logic to hide the scrollbars is broken. I can check it out.

**Comment by Youssef1313** [comment]
@ajpinedam I'll take a look. Will see if I find something interesting.
