### ISSUE TITLE
[Skia][5.0] Button Width Version 

### ISSUE THREAD

**Issue by rafael-rosa-knowcode** [unoplatform/uno#12885]
### Current behavior

When we set the width of the button and run the project on a GTK platform, the button only start with 1 pixel.

The gray on the image is just to show the space of the Button

![image](https://github.com/unoplatform/uno/assets/116665025/0857b7d5-e7de-4e3d-ac3c-a044a6804465)

Works fine on wasm and Android, or the last previous version.

![image](https://github.com/unoplatform/uno/assets/116665025/55ceedaa-47b6-4043-9bc6-24f52d8d979c)

### Expected behavior

That GTK display the Button like other platforms or the older versions.

![image](https://github.com/unoplatform/uno/assets/116665025/55ceedaa-47b6-4043-9bc6-24f52d8d979c)

### How to reproduce it (as minimally and precisely as possible)

Remove the current Uno.Templates.
```csharp
dotnet new uninstall Uno.Templates
```

Install the new Uno.Template
```csharp
dotnet new install Uno.Templates
```

Create a new Blank project
```csharp
dotnet new unoapp -preset blank -o MySampleButtonWidth
```

Set the GTK platform as the StartUp.

* Open the file Directory.Packages.props
and replace all references to the "4.9.17" (or the "Uno.WinUI") version for 5.0.0-dev.1392 (or the last for now https://www.nuget.org/packages/Uno.WinUI/)
```xml
<PackageVersion Include="Uno.WinUI" Version="4.9.17" />
to
<PackageVersion Include="Uno.WinUI" Version="5.0.0-dev.1392" />
```

* And update the Program.cs and remove the ", args" from the GktHost.

From
```csharp
var host = new GtkHost(() => new AppHead(), args);
```
To
```csharp
var host = new GtkHost(() => new AppHead());
```

* Change the MainPage.xaml

```xml
<Page x:Class="MySampleButtonWidth.MainPage"
	xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	xmlns:local="using:MySampleButtonWidth"
	xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
	xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
	mc:Ignorable="d"
	Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

	<StackPanel HorizontalAlignment="Center"
				VerticalAlignment="Center">

		<VisualStateManager.VisualStateGroups>
			<VisualStateGroup x:Name="ButtonStates">
				<VisualState x:Name="CustomPointerEntered">
					<VisualState.Setters>
						<Setter Target="btn.Width" Value="500" />
					</VisualState.Setters>
				</VisualState>
				<VisualState x:Name="CustomPointerExited">
					<VisualState.Setters>
						<Setter Target="btn.Width" Value="300" />
					</VisualState.Setters>
				</VisualState>
			</VisualStateGroup>
		</VisualStateManager.VisualStateGroups>

		<Grid Background="Gray">
			<Button  x:Name="btn" Content="VisualStateManager Width Test" Width="300"/>
		</Grid>
	</StackPanel>
</Page>

```

And the file MainPage.xaml.cs

```csharp
namespace MySampleButtonWidth;

public sealed partial class MainPage : Page
{
	public MainPage()
	{
		this.InitializeComponent();
		Loaded += MainPage_Loaded;
	}
	private void MainPage_Loaded(object sender, RoutedEventArgs e)
	{
		btn.PointerEntered += (sender, e) =>
		{
			VisualStateManager.GoToState(this, "CustomPointerEntered", true);
		};

		btn.PointerExited += (sender, e) =>
		{
			VisualStateManager.GoToState(this, "CustomPointerExited", true);
		};
	}
}

```

And rebuild the soluction and Run.

The VisualStateManager is just to show that the Button start with Width 1, but if we change for other value it works.
So pass the mouse over the start of the Gray area.

### Workaround

Use visua state for change the Width

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

<Project ToolsVersion="15.0">
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
    <PackageVersion Include="Microsoft.Windows.Compatibility" Version="7.0.0" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.3.230602002" />
    <PackageVersion Include="SkiaSharp.Skottie" Version="2.88.3" />
    <PackageVersion Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.3" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageVersion Include="Uno.Extensions.Logging.OSLog" Version="1.4.0" />
    <PackageVersion Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.4.0" />
    <PackageVersion Include="Uno.Resizetizer" Version="1.1.0" />
    <PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.0-dev.1392" />
    <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
    <PackageVersion Include="Uno.Wasm.Bootstrap" Version="7.0.23" />
    <PackageVersion Include="Uno.Wasm.Bootstrap.DevServer" Version="7.0.23" />
    <PackageVersion Include="Uno.Wasm.Bootstrap.Server" Version="7.0.23" />
    <PackageVersion Include="Uno.WinUI" Version="5.0.0-dev.1392" />
    <PackageVersion Include="Uno.WinUI.RemoteControl" Version="5.0.0-dev.1392" />
    <PackageVersion Include="Uno.WinUI.Skia.Gtk" Version="5.0.0-dev.1392" />
    <PackageVersion Include="Uno.WinUI.WebAssembly" Version="5.0.0-dev.1392" />
    <PackageVersion Include="Xamarin.Google.Android.Material" Version="1.8.0" />
  </ItemGroup>
</Project>

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

Version 17.6.4 or Version 17.7.0 Preview 2.0

**Comment by rafael-rosa-knowcode** [comment]
@MartinZikmund , @nickrandolph asked me to tag you.
Can you check if I'm doing something wrong?

CC:  @iurycarlos

**Comment by rafael-rosa-knowcode** [comment]
Created Project

[MySampleButtonWidth.zip](https://github.com/unoplatform/uno/files/12042881/MySampleButtonWidth.zip)

**Comment by Youssef1313** [comment]
@rafael-rosa-knowcode I assume this is a regression?
