### ISSUE TITLE
Cannot launch/debug an uno project with android Q

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#1289]
## Current behavior

- Debugger gets detach from app process
- Application crash or display a blank app

## Expected behavior

- Display an uno application on android Q emulator
- Can debug an uno app on an android Q emulator 

## How to reproduce it (as minimally and precisely as possible)

- Load the projects provided in this issue
- Deploy it on an android Q emulator
- When the debbuger gets detach, reopen the application "App" from the device 

## Environment

Nuget Package: Uno.UI

Package Version(s): 1.45.0-beta.1859

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version 16.2.0 preview 4.0: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?

You can retreive a small uno project to test this issue.

[uno_project_android_q.zip](https://github.com/unoplatform/uno/files/3419282/uno_project_android_q.zip)

**Comment by MartinZikmund** [comment]
Can you try running on Visual Studio 2019 stable instead of preview? Preview 4.0 seems to have a lot of issues with Android

**Comment by jeromelaban** [comment]
This was fixed with Android 10 support.
