### ISSUE TITLE
Replace `__NETSTD__` with `__WASM__ || __SKIA__` for clarity

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#12904]
Currently, `__NETSTD__` appears to mean "Wasm or Skia" if I understand correctly. Maybe we should replace it for clarity?

**Comment by MartinZikmund** [comment]
It also includes `__NETSTD_REFERENCE__` if I am not mistaken.

**Comment by MartinZikmund** [comment]
Done!
