### ISSUE TITLE
[GTK/WPF] Add support for getting other ApplicationModel.Package properties

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#12937]
## What would you like to be added:
Add support for more properties inside ApplicationModel.Package.

## Why is this needed:
Currently the ApplicationModel.Package supports only a small number of properties. It would be nice if it supported Description and others too.

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Linux Framebuffer
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
@morning4coffe-dev are there any other relevant ones or can we close?

**Comment by morning4coffe-dev** [comment]
@MartinZikmund I think it would be cool to have some of the other ones like Dependencies also, but not sure if there si going to be a way to get it. Let's discuss this on the sync today.

**Comment by MartinZikmund** [comment]
Closing for now as the most important ones were implemented, we can expand further with new issues
