### ISSUE TITLE
iOS/Android Can't subscribe to FrameworkElement.DataContextChanged

### ISSUE THREAD

**Issue by abrull** [unoplatform/uno#1296]
## Current behavior

When subscribing to `DataContextChanged` event I get the following build error

> Error CS0123 No overload for 'ExtendedTextControl_DataContextChanged' matches delegate 'TypedEventHandler<DependencyObject, DataContextChangedEventArgs>'

## Expected behavior

You should be able to subscribe to DataContextChanged event on Android and IOS

## How to reproduce it (as minimally and precisely as possible)

Simple Subscribe to DataContextChanged on any Framework element and try to build
## Environment

Nuget Package:
Uno.UI 
Package Version(s):
1.44.1
Affected platform(s):
- [ x] iOS
- [x ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by abrull** [comment]
I just realized that on Android and iOS in the even handler the sender is `DependencyObject` and on UWP the sender is `FrameworkElement` so I just created different event handlers for each platform

**Comment by ToddGlodek** [comment]
Ah, that's a great suggestion..  
I'm still noticing this on version 2.0.0 (Monday, May 11, 2020 (5/11/2020) ).
