### ISSUE TITLE
Implement `ColumnMajorUniformToLargestGridLayout`

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#12996]
## What would you like to be added:
[`ColumnMajorUniformToLargestGridLayout`](https://learn.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.primitives.columnmajoruniformtolargestgridlayout?view=winui-2.8)

## Why is this needed:
https://github.com/unoplatform/uno/issues/12820

## For which Platform:
- [x] WebAssembly
- [x] Android
- [x] iOS
- [x] macOS (AppKit)
- [x] Mac Catalyst
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Linux Framebuffer
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?
WinUI source code: https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/RadioButtons/ColumnMajorUniformToLargestGridLayout.cpp

**Comment by Youssef1313** [comment]
@dr1rrb This is looking implemented already? https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml.Controls.Primitives/ColumnMajorUniformToLargestGridLayout.cs

**Comment by dr1rrb** [comment]
Oh ... apparently I didn't look close enough in Uno's code 😅
