### ISSUE TITLE
Content Dialog fullscreen issues

### ISSUE THREAD

**Issue by mathieuwilsonnv** [unoplatform/uno#1299]
## Current behavior

There are various small issues when setting the FullSizeDesired property to true.

On iOS : The border disappears on the lower end of the screen, so bottom left, bottom, and bottom right side. 
On Android : The top and bottom edges of the dialog are cut off. The ContentDialog is not actually fullscreen like on iOS, we can see the previous page at the top and the android navigation bar bar at the bottom. This seems to only happen when using the in-screen android navigation bar.

## Expected behavior

On iOS: We see the border all around the dialog.
On Android : Dialog is displayed in it's entirety, nothing cut off.

## How to reproduce it (as minimally and precisely as possible)

- Start the Uno Gallery / Uno Playground project
- Go to the ContentDialog section
- Press on the Terms and Conditions button
- Observe
(On Android, you have to make sure you have the navigation bar on your screen)

## Environment

iOS 11 , iPhone 6+
Android 7, Galaxy S8+

Nuget Package:
Uno.UI

Package Version(s):
1.46.0-dev.2260

Affected platform(s):
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?
Screenshots

Android with navigation bar
![image](https://user-images.githubusercontent.com/44030932/61818782-90ea3c80-ae1f-11e9-8fa3-b2e2fde35187.png)

Android no bar:
![image](https://user-images.githubusercontent.com/44030932/61819278-a875f500-ae20-11e9-868f-f65a5c19f73f.png)

IOS
![cd](https://user-images.githubusercontent.com/44030932/61818998-179f1980-ae20-11e9-9d6b-d11fc508231d.png)

**Comment by davidjohnoliver** [comment]
Contributor notes:
 - the sample referenced in the issue description is in this unmerged PR: https://github.com/unoplatform/Uno.Playground/pull/57
 - the `FullSizeDesired` property is simply not implemented at all in Uno, for any platform (though the `[NotImplemented]` property is incorrectly omitted)
