### ISSUE TITLE
[xBind] Implicit `BindBack` may fail when part of the path is `null`

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#13009]
### Current behavior

Given the following expression: 
```
Text="{x:Bind Path=ViewModel.Username, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"`
```
If a bind back happens when the ViewModel property is null, an NRE will happen, on the following line:

```
.BindingApply(__that, (___b, __that) => 
 /*defaultBindModeOneWay ViewModel.Username*/ global::Uno.UI.Xaml.BindingHelper.SetBindingXBindProvider(___b, __that, ___ctx => ___ctx is MyView ___tctx 
   ? (TryGetInstance_xBind_2(___tctx, out var bindResult2) 
       ? (true, bindResult2) 
       : (false, default))
   : (false, default), 

   (___ctx, __value) => { if(___ctx is MyView  ___tctx) ___tctx.ViewModel.Username = (string)global::Microsoft.UI.Xaml.Markup.XamlBindingHelper.ConvertValue(typeof(string), __value); } , new [] {"ViewModel.Username"}))
```

and `___tctx.ViewModel.Username` is not validated for null reference.

### Expected behavior

Null reference in the path is handled properly/

### Works on UWP/WinUI

None

### NuGet package version(s)

4.9.26

**Comment by Youssef1313** [comment]
*Could* be related to https://github.com/unoplatform/uno/blob/38d27864d94a5304652b4800f0096d2e9cc30ccf/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/Utils/XBindExpressionParser.cs#L31-L32

I'll double check.

**Comment by MartinZikmund** [comment]
I have small repro in dev/mazi/xbind-twoway-null, the test passes, but NRE is thrown and swallowed

**Comment by Youssef1313** [comment]
@MartinZikmund For the test to crash, you need:

```csharp
var oldFeatureValue = FeatureConfiguration.BindingExpression.HandleSetTargetValueExceptions;
try
{
    // test goes here.
}
finally
{
    FeatureConfiguration.BindingExpression.HandleSetTargetValueExceptions = oldFeatureValue;
}
```
