### ISSUE TITLE
[Internal analyzer][Performance] Don't call DP getters multiple times in the same code block

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#13001]
Calling DP getter could be quite expensive. It can happen that we do that more than once in the same code block, so, having an analyzer to warn against this pattern and suggest extracting the value to a local variable could have a good impact on performance.

@jeromelaban Thoughts?

**Comment by jeromelaban** [comment]
It would be interesting. Inside of Uno, most of the time, moving to a generated property will remove that issue, but can make sense for end-users.

**Comment by Youssef1313** [comment]
@jeromelaban So it should be a public analyzer instead of internal?

**Comment by Youssef1313** [comment]
Reading a DP is now quite fast enough. It's not worth implementing this now, I think
