### ISSUE TITLE
[Skia][Islands] NRE on RaiseEvent inside InitiateKeyDownBubblingFlow

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#13006]
### Current behavior

When using the SampleApp I noticed this issue, where when I type into any TextBox I get NRE on originalSource.RaiseEvent inside InitiateKeyDownBubblingFlow
![image](https://github.com/unoplatform/uno/assets/78549750/a8b55b32-5fb2-4b32-b363-8f98201e4358)

### How to reproduce it (as minimally and precisely as possible)

1. Go to the SampleApp
2. Run Uno Islands sample
3. Type into any TextBox

### Works on UWP/WinUI

None

### Anything else we need to know?

This issue has been discussed internally with Martin.

**Comment by morning4coffe-dev** [comment]
CC @MartinZikmund

**Comment by MartinZikmund** [comment]
This is fixed now
