### ISSUE TITLE
[Android] Empty Current Window Bounds if it's not Loaded

### ISSUE THREAD

**Issue by Soap-141** [unoplatform/uno#13023]
### Current behavior

Since `Uno 4.10`, if the current window is not loaded we can't get the bounds.

### Expected behavior

We should be able to get the window bounds even if it's not loaded (like we could before).

### How to reproduce it (as minimally and precisely as possible)

1. Download [WindowBounds.zip](https://github.com/unoplatform/uno/files/12176713/WindowBounds.zip)
2. Start the application on Android
3. Notice the values displayed

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Latest 4.10 preview.

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.6.5

### Anything else we need to know?

I used Xamarin and Uno 4.10 because our production project is still using Xamarin.

**Comment by jeromelaban** [comment]
@MartinZikmund sounds familiar?

**Comment by Soap-141** [comment]
@jeromelaban I tried with DisplayInformation and it could be fine but would required another update on our side. If fixable in Uno do it please, otherwise notify me.

**Comment by MartinZikmund** [comment]
@Soap-141 I'm working on this one, hopefully will have a fix soon

**Comment by MartinZikmund** [comment]
Important note - because we aligned the window lifecycle with WinUI/UWP, the window is now "created" later - so while my fix will ensure the bounds are initialized, it is possible the size will still change afterwards - so make sure to subscribe to `SizeChanged` for those cases

**Comment by MartinZikmund** [comment]
Backported and closing!

**Comment by Soap-141** [comment]
Working thanks!
