### ISSUE TITLE
TextBox does not clear when binding set to null

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1302]
## Current behavior

After the recent changes in `TextBox` controls, it appears that when the data bound source is set to `null` the `TextBox` does not clear itself. Instead, it stays filled out with the previous input.

Example C#:

    public class TestItem
    {
        public string Text { get; set; } 
    }

    public TestItem Test { get; private set; } = new TestItem();

    private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
    {
         Test = new TestItem();
         OnPropertyChanged(nameof(Test));
    }

and XAML:

    <StackPanel Padding="20" Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <TextBox Text="{x:Bind Test.Text, Mode=TwoWay}" />
        <Button Click="ButtonBase_OnClick" Content="Clear" />
    </StackPanel>
    

## Expected behavior

Same as UWP, the `TextBox` should clear when `Text` binding source is set to `null`

## How to reproduce it (as minimally and precisely as possible)

Simple repro app is here: https://github.com/MartinZikmund/UnoNullTextBoxBug

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
Good find Martin!

**Comment by MartinZikmund** [comment]
@davidjohnoliver Thanks for the superfast fix!
