### ISSUE TITLE
[PipsPager][Fluent] Both arrow buttons point the same way.

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#13032]
### Current behavior

Both the previous and the next button point in the same direction
![image](https://github.com/unoplatform/uno/assets/90481654/6fe59e21-90ef-4578-8f1a-93ce55eab73d)

### Expected behavior

They should both point outwards like on WinUI
![image](https://github.com/unoplatform/uno/assets/90481654/b390b3e9-8b40-4757-bc50-0f1c68793817)

### How to reproduce it (as minimally and precisely as possible)

http://playground.platform.uno/#4faa5804
[BasicApp.zip](https://github.com/unoplatform/uno/files/12186062/BasicApp.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

```
<PackageReference Include="Uno.Resizetizer" Version="1.2.0-dev.19" />
		<PackageReference Include="Microsoft.Windows.Compatibility" Version="7.0.0" />
		<PackageReference Include="Uno.Wasm.Bootstrap" Version="8.0.0-dev.230" />
		<PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="8.0.0-dev.230" />
		<PackageReference Include="Uno.WinUI.WebAssembly" Version="5.0.0-dev.1634" />
		<PackageReference Include="Uno.WinUI.RemoteControl" Version="5.0.0-dev.1634" Condition="'$(Configuration)'=='Debug'" />
		<PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.0-dev.1634" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0" />
		<PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.6.0-dev.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
```

### Affected platforms

WebAssembly, Android, iOS
(all Uno platforms tested)
### IDE

Visual Studio 2022

### IDE version

Version 17.6.0

**Comment by Marc-Antoine-Soucy** [comment]
@MartinZikmund

**Comment by Youssef1313** [comment]
That is a wrong glyph in font file (uno.fonts.fluent 2.2.2).

![image](https://github.com/unoplatform/uno/assets/31348972/277a0e77-27ce-4830-9744-2bcb160a7921)

**Comment by NVLudwig** [comment]
@Youssef1313 hmmmm Current version of the Uno symbols font seem to have the correct glyphs and unicodes for all carets
<img width="1274" alt="image" src="https://github.com/unoplatform/uno/assets/29584087/131d649c-e1fa-47d6-8c38-e20aa84f178b">

Are you referencing this one: https://platformuno.sharepoint.com/:u:/s/UnoPlatform/ES1TP36KTQtLmEeg3NAGz2QBWbXcHGTB2jz3KvPOjmxXGQ?e=uXGEKC

**Comment by Youssef1313** [comment]
Thanks @NVLudwig. uno.fonts was just behind the latest updates.
