### ISSUE TITLE
Revise `Duration` implementation

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#13039]
### Current behavior

https://github.com/unoplatform/uno/blob/b7f825067627465061588550b0b6ddb320e4b7ab/src/Uno.UI/UI/Xaml/Duration.cs#L51-L58

### Expected behavior

`Add` only handles TimeSpan durations. This doesn't look correct. Same for `Subtract`.

### Works on UWP/WinUI

None

**Comment by MartinZikmund** [comment]
Reopened for backport

**Comment by Youssef1313** [comment]
Backport is merged. Closing this.
