### ISSUE TITLE
[Gallery-4X][Wasm]ColorPicker- ColorPicker box is not displaying any color

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13062]
### Current behavior

![colorpicker issue](https://github.com/unoplatform/uno/assets/74563602/d1ab78b8-a7d1-429f-8c82-513510e8aa02)

### Expected behavior

![colorpicker issue correct](https://github.com/unoplatform/uno/assets/74563602/e3609369-fdb9-4597-9217-238b19da1c51)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "ColorPicker" from the "Component" list.
4. Observe that the ColorPicker box is not displaying any color.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by Youssef1313** [comment]
This is a tough issue. It's not reproducible locally in SamplesApp legacy/4x or the 4.10 Gallery canary.

Being not reproducible makes it a lot harder to debug.

One important observation here is that the spectrum rectangle has `Fill` set to "transparent". This shouldn't be the case. Tried to track down why could this happen, but it's a bit hard.

**Comment by agneszitte** [comment]
@Youssef1313 verifying if it is an AOT/Interpreter related issue for Gallery 4x

**Comment by Youssef1313** [comment]
![image](https://github.com/unoplatform/uno/assets/31348972/b2cbf43c-10dc-48ad-a8a1-3b492ad402b1)

Should be fixed now.

**Comment by agneszitte** [comment]
Thank you @Youssef1313, ready for QA @sakshi173

**Comment by sakshi173** [comment]
Verified this issue is fixed, closing it.
