### ISSUE TITLE
[Gallery][Wasm]Toggleswitch- In Dark theme for 'ON' position switch knob is not displaying in purple color.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13068]
### Current behavior

![toggleswitch issue](https://github.com/unoplatform/uno/assets/74563602/f6f4ac99-ffb4-4831-91be-b3288773e0b2)

### Expected behavior

![toggleswitch correct](https://github.com/unoplatform/uno/assets/74563602/a8a4ba30-6446-4113-84cf-ab4215b2eb84)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Make sure that the App is in dark theme mode.
4. Tap "Toggleswitch" from the "Component" list.
5. Go to the Material section.
6. Observe that or 'ON' position switch knob is not displaying in purple color.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Skia (GTK on Linux/macOS/Windows)

**Comment by agneszitte** [comment]
@kazo0 , @sakshi173 closing this issue as we now have the new M3 ToggleSwitch in place

**Comment by sakshi173** [comment]
This issue is not valid now due to that closing it.
