### ISSUE TITLE
Embed .NET MAUI controls in Uno Platform (WinUI, Android, iOS, MacCatalyst only)

### ISSUE THREAD

**Issue by manfromarce** [unoplatform/uno#13086]
## What would you like to be added:
Embedding .NET MAUI controls in the Windows (WinUi), Android, iOS and MacCatalyst targets should be possible via [MAUI native embedding](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/native-embedding) because the target frameworks are the same, but it's not easy to accomplish since the project structure is different. It would be nice if Uno included a component called e.g. MauiControlHost along with the documentation needed to make it work.

## Why is this needed:
This feature would be useful because several vendors such as DevExpress, Syncfusion and Telerik provide a good amount of .NET MAUI controls now. Being able to use these in Uno would fill in some gaps at least on 4 major platforms (and the WASM target can already embed JS components), while still having access to the Uno benefits over MAUI (pixel-perfect, WinUI controls, ...).

## For which Platform:

- [x] Windows
- [x] Android
- [x] iOS
- [x] Mac Catalyst
- [ ] macOS (AppKit)
- [ ] WebAssembly
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Build tasks
- [ ] Solution Templates

**Comment by manfromarce** [comment]
Thank you! My application will need PDF viewing/annotation capabilities, so I've been experimenting with different 3rd-party controls and embedding options and found that Syncfusion MAUI PdfViewer within an Uno application would be the best option overall.
I don't have the time or experience to implement this "host" component myself, but I could test it and provide feedback if you'll have an experimental version to share in the future.

**Comment by francoistanguay** [comment]
We'll keep you posted. We're a few weeks away from our next release so I'd recommend you follow our upcoming announcements... just in case :)

**Comment by MartinZikmund** [comment]
Maybe we can close now 🙃 ?
