### ISSUE TITLE
XamlReader fails to parse add resources to custom ResourceDictionaries with a nested ResourceDictionary property

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#13099]
### Current behavior

Given the following custom `ResourceDictionary` class:

```cs
namespace MyTestApp;
public class TestCustomResourceClass : ResourceDictionary
{
	public ResourceDictionary MyDict { get; set; }
}
```

The following XAML will fail to parse when attempting to add a resource to the nested `MyDict` `ResourceDictionary`

```xml
<tests:TestCustomResourceClass xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
							   xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
							   xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
							   xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
							   xmlns:tests="using:MyTestApp"
							   mc:Ignorable="d">
	<tests:TestCustomResourceClass.MyDict>
		<ResourceDictionary>
			<Color x:Key="MyColor">Red</Color>
		</ResourceDictionary>
	</tests:TestCustomResourceClass.MyDict>
</tests:TestCustomResourceClass>

```

Results in a NullReferenceException at [this line](https://github.com/unoplatform/uno/blob/02e639a9f6bfaf6f7d1f75df0677cf985dd9a159/src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs#L698)

### Expected behavior

Should work

### Works on UWP/WinUI

Yes

**Comment by kazo0** [comment]
Whoever takes this on, please ping me as this branch should have a good start on this: https://github.com/unoplatform/uno/tree/dev/sb/xamlreader-bugs

**Comment by MartinZikmund** [comment]
Reopened for backport
