### ISSUE TITLE
Filter OnLaunched call only for ApplicationActivity-derived Activities

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1309]
##  What would you like to be added:

The `OnActivityStarted` handler in `NativeApplication` triggers the `OnLaunched` event on `Application` class when any activity is started. This is a problem as when a splash screen activity is added **before** the main `ApplicationActivity`, the app will crash when `Frame` initialized as the Uno resources were not loaded.

## Why is this needed:

To add Android XML layout-based splash screen to apps (for example following [this ](https://mallibone.com/post/lets-improve-that-xamarin-forms-startup-experience) tutorial)

## For which Platform:

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows

**Comment by jeromelaban** [comment]
What kind of problem does that raise? Is it because of some use of the `ContextHelper` ?

**Comment by MartinZikmund** [comment]
@jeromelaban It crashes on

```
rootFrame = new Frame();
```

With the following exception:

> Java.Lang.NullPointerException: 'Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference'

**Comment by pdecostervgls** [comment]
I'm not completely sure about the underlying reasons why it doesn't work, but I support this issue because I am trying to get a splash screen implemented too.

**Comment by MartinZikmund** [comment]
@pdecostervgls For a temporary workaround you can implement it similarly to the uno calculator - https://github.com/unoplatform/calculator/blob/uno/src/Calculator.Droid/Resources/values/Styles.xml - set the splash screen as the background of the whole window.
