### ISSUE TITLE
Show UWP target/min version dialog when creating new Uno project

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1310]
**This enhancement idea is from my friend @VitezslavImrysek , all credit goes to him 👍 !**

## What would you like to be added:

When a UWP project is created, VS presents a dialog window which asks for the target/min version. The same dialog can be triggered by adding a `Microsoft.VisualStudio.WinRT.TemplateWizards` reference in the project template. This even takes care of generating a temporary certificate for development.

## Why is this needed:

To make creating of a new Uno app project in line with UWP and let users choose version beforehand.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] Windows

**Comment by jeromelaban** [comment]
@MartinZikmund good idea indeed !

**Comment by MartinZikmund** [comment]
@jeromelaban the catch here is that the UWP wizard has a different dll version for VS 2017 vs VS 2019, so this will likely require to have two different versions of the extension, is that a problem?

**Comment by MartinZikmund** [comment]
As we will now have a platform picker dialog from #8762 and future projects will be mostly WinAppSDK based, this is probably no longer needed, closing 👍
