### ISSUE TITLE
`AncestorsDictionary` should be pooled

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#13110]
`AncestorsDictionary` is instantiated and then disposed at the end of the method. Pooling can help improve performance.

On SamplesApp startup, we create about 1,544 AncestorsDictionary instances, totalling 37,056 bytes.

**Comment by Youssef1313** [comment]
Is this created only on the main thread? In this case it could be a static singleton dictionary that gets cleared when finished up with. So we might not need pooling.

**Comment by jeromelaban** [comment]
> Is this created only on the main thread? In this case it could be a static singleton dictionary that gets cleared when finished up with. So we might not need pooling.

Yes, it's only on the main thread, and the method creating it should not be reentrant either.
