### ISSUE TITLE
[Android][MediaPlayerElement] Blank space in MediaControlsCommandBar

### ISSUE THREAD

**Issue by Robert-Louis** [unoplatform/uno#13123]
### Current behavior

In fluent mode the compact MediaControlsCommandBar have a big white space in the left where the buttons should be.

<img width="281" alt="dropout android mediaplayeur" src="https://github.com/unoplatform/uno/assets/16021239/38fd6e8c-96ed-44c7-b38d-b6797ec7b2e5">

### Expected behavior

The blank space should be fill by buttons

### How to reproduce it (as minimally and precisely as possible)

- clone or fetch latest Uno.UI repo
- launch sample app in skia
- go to MediaPlayer page
- select fluent style then refresh
- reduce the window until buttons start to dropout
- the last buttons at right being crop

### Works on UWP/WinUI

None

### Affected platforms

Android

**Comment by MartinZikmund** [comment]
Reopened for backport
