### ISSUE TITLE
`PackageVersion` constructor with 4 ushort paramaters representing Major, Minor, Build, Revision is not available

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#13139]
### Current behavior

Constructor with 4 ushort paramaters representing Major, Minor, Build, Revision of Windows.ApplicationModel.PackageVersion is not available in Uno while WinUI has

### Expected behavior

Constructor of Windows.ApplicationModel.PackageVersion with 4 ushort paramaters representing Major, Minor, Build, Revision

![packageversion](https://github.com/unoplatform/uno/assets/6670150/a0440704-c7d1-448a-a5f4-bd35e4d52d8c)

### Workaround
Create wrapper

### Works on UWP/WinUI

Yes

### Affected platforms

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

**Comment by Youssef1313** [comment]
Can you please clarify @FrozDark ?

`PackageVersion` is a struct, so the parameterless constructor is actually always publicly visible (enforced by C# language rules).

**Comment by FrozDark** [comment]
> Can you please clarify @FrozDark ?
> 
> `PackageVersion` is a struct, so the parameterless constructor is actually always publicly visible (enforced by C# language rules).

Sorry, I meant this one
![packageversion](https://github.com/unoplatform/uno/assets/6670150/2f69b0e9-a5b8-43ac-9570-28f9355532f1)

**Comment by Youssef1313** [comment]
Interesting. This doesn't show up in the doc https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.packageversion?view=winrt-22621.

**Comment by MartinZikmund** [comment]
It was WinUI only
