### ISSUE TITLE
[Wasm] AOT releases fail when using latest Uno using default project settings

### ISSUE THREAD

**Issue by assassin316** [unoplatform/uno#13138]
### Current behavior

The Wasm project head has the default settings in place, and compiling in Release gives the following error:

`System.Exception: Failed to execute the linker`

Looking at the binlog gives the following error:

![image](https://github.com/unoplatform/uno/assets/17514380/754a24b6-44e5-4d6c-ba2a-adafca420e85)

### Expected behavior

AOT release in Wasm should compile.

### How to reproduce it (as minimally and precisely as possible)

1. Using latest Uno Platform extension, create a new project: **Uno Platform App (Xamarin, UWP)**
2. Change to **Release** mode
3. Rebuild the **Wasm** head
4. Project will compile successfully
5. Now update all Uno nuget packages to latest version (_stable_)
6. Re-build the **Wasm** head
7. Compilation fails with `System.Exception: Failed to execute the linker`

### Workaround

Don't upgrade Microsoft.Windows.Compatibility greater than 6.0.7

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.9.45

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by assassin316** [comment]
Here is it with Diagnostic output. Thanks.

[Wasm_Release_AnyCPU_Build_2023-08-14T18_59_11.8657923-04_00.binlog.zip](https://github.com/unoplatform/uno/files/12340133/Wasm_Release_AnyCPU_Build_2023-08-14T18_59_11.8657923-04_00.binlog.zip)

**Comment by assassin316** [comment]
I may have found something that helps. I verified this on my project and a blank project as well, after upgrading all my packages except for the logging ones, I then downgraded Microsoft.Windows.Compatibility (which is on the Wasm head) back down to 6.0.7 which compiles correctly in Release Any version higher (7.0.0 and above) causes the issue.

![image](https://github.com/unoplatform/uno/assets/17514380/6e342049-7343-4253-8ad8-cc459cb68d99)

**Comment by jeromelaban** [comment]
Here's what the binlog is showing:

```
[00:00:23.5527976] ILLink: error IL1009: Assembly reference 'System.Windows.Extensions' could not be resolved.
```

This is indeed related to `Microsoft.Windows.Compatibility`, and changing versions may help.
