### ISSUE TITLE
[Android] ButtonBase.Click not working anymore

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#1315]
# Bug Report

## Expected behavior
`ButtonBase.Click` should work out of the box.
Currently, need to add a handler to `.Tapped` for the click to work properly.

## Regression
It's a regression of PR #1014 

Affected platform(s):
- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

**Comment by jeromelaban** [comment]
Fixed ?
