### ISSUE TITLE
Revert workaround in FlyoutPresenter template

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#13153]
https://github.com/unoplatform/uno/blob/c54d094cd93862e2d47b01b2fdf3d6fca6c287c5/src/Uno.UI/UI/Xaml/Style/Generic/FlyoutPresenter.xaml#L55-L56

The above seems like a workaround to lack of support of TemplateBinding of attached properties which is already fixed. I think the workaround can be removed.

**Comment by agneszitte** [comment]
Re-Open for backport PR
