### ISSUE TITLE
_UnoGeneratePriMarker sometimes does nothing when it runs before _UnoAssetsGetCopyToPublishDirectory

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#13167]
### Current behavior

Builds get flaky and sometimes and fail with errors similar to: 

> C:\hostedtoolcache\windows\dotnet\sdk\7.0.306\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): error NU5019: File not found: 'D:\a\1\s\src\library\Uno.Toolkit.Cupertino\bin\Uno.Toolkit.WinUI.Cupertino\Release\net7.0-ios\Uno.Toolkit.WinUI.Cupertino.uprimarker'. [D:\a\1\s\src\library\Uno.Toolkit.Cupertino\Uno.Toolkit.WinUI.Cupertino.csproj]

**Note that this error can go away with restarts, so it's a race condition**

### Workaround

Without this workaround target, what happens is that `_UnoGeneratePriMarker` is sometimes run before `_UnoAssetsGetCopyToPublishDirectory` and finds `ContentWithTargetPath` being empty, so it does nothing
Then later, `_UnoAssetsGetCopyToPublishDirectory` is run and `ContentWithTargetPath` is now added, and NuGet packaging now expects the `.uprimarker` to be present

```xml
<Target Name="_WorkaroundBuildFlakiness"
		BeforeTargets="_UnoGeneratePriMarker">
	<ItemGroup>
		<ContentWithTargetPath Include="@(_TransitiveItemsToCopyToOutputDirectory)">
			<TargetPath>%(TargetPath)</TargetPath>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</ContentWithTargetPath>
	</ItemGroup>
</Target>
```

### Works on UWP/WinUI

None

**Comment by agneszitte** [comment]
(cc @Youssef1313 / @jeromelaban )

**Comment by kazo0** [comment]
[toolkit-build-packages.zip](https://github.com/unoplatform/uno/files/12334828/toolkit-build-packages.zip)
