### ISSUE TITLE
[Android] App bounds extend to full screen, including navigation bar area

### ISSUE THREAD

**Issue by NGame1** [unoplatform/uno#1319]
## Current behavior
![image](https://user-images.githubusercontent.com/19765248/62116031-bae3a900-b2ce-11e9-8663-bdbf67492ebc.png)
Software navigation bar buttons pop up on the application screen.

## Expected behavior
The navigation bar should have a black background at the bottom of the screen and should be separated from the application's UI. 
Applications built with 2264 NuGet are functioning normally bu after 2330 I see this issue.

Nuget Package:
Package Version(s):
dev2330 and 2340

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
This was a breaking change to align the behaviour of Android with iOS. By default now your app UI extends to the whole screen, including translucent navigation bars. This allows you to set a full-screen background for example. Obviously this is not desirable for buttons, text etc, so we provide the `VisibleBoundsPadding` attached property: https://github.com/unoplatform/uno/blob/master/src/Uno.UI.Toolkit/VisibleBoundsPadding.md

Sample:

```
<UserControl x:Class="Uno.UI.Samples.Controls.SampleChooserControl"
            xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
            xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
            xmlns:toolkit="using:Uno.UI.Toolkit">
    <Grid toolkit:VisibleBoundsPadding.PaddingMask="All">
    </Grid>
</UserControl>
```

**Comment by NGame1** [comment]
After setting it to All nothing changed!
Also bottom, Top and etc.

**Comment by davidjohnoliver** [comment]
cc @XiaotianNetlift

**Comment by NGame1** [comment]
As an update, I should say seems the behaviour is reverted to the old one.
dev 2895

**Comment by MartinZikmund** [comment]
This should now behave correctly, plus `VisibleBoundsPadding` is documented well, closing for now.
