### ISSUE TITLE
`CommandBar` Popup renders incorrectly on initial load, and has wrong vertical offset on all loads

### ISSUE THREAD

**Issue by ramezgerges** [unoplatform/uno#13213]
### Current behavior

Normally, CommandBars have a "SecondaryCommands" button that expands the bar and opens a popup with a list of secondary commands when pressed, like this
![2d04ac44-d20e-4932-983a-105de7a1c511](https://github.com/unoplatform/uno/assets/66218781/5b661c07-29fd-4258-aa7f-f180909c3e31)
What actually happens on Uno is this
![29ce9adf-1e76-4d16-aef8-47051d77b624](https://github.com/unoplatform/uno/assets/66218781/5ba342b2-c637-4c7d-9ff2-f2ed26841c50)

The popup is opened where a collapsed CommandBar would be, not where an expanded one is.

Also, on the initial render, the Popup doesn't take its full correct width, but is only wide enough to contain the words "Like" and "Dislike", without the right padding present in the above screenshots

### Expected behavior

![2d04ac44-d20e-4932-983a-105de7a1c511](https://github.com/unoplatform/uno/assets/66218781/5b661c07-29fd-4258-aa7f-f180909c3e31)

### How to reproduce it (as minimally and precisely as possible)

<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
		<Grid.RowDefinitions>
			<RowDefinition Height="Auto"/>
			<RowDefinition Height="*"/>
			<RowDefinition Height="Auto"/>
		</Grid.RowDefinitions>

		<TextBlock Text="Hello, world !" Margin="20" FontSize="30" />
		
		<CommandBar Grid.Row="2">
			<AppBarToggleButton Icon="Shuffle" Label="Shuffle" Click="AppBarButton_Click" />
			<AppBarToggleButton Icon="RepeatAll" Label="Repeat" Click="AppBarButton_Click"/>
			<AppBarSeparator/>
			<AppBarButton Icon="Back" Label="Back" Click="AppBarButton_Click"/>
			<AppBarButton Icon="Stop" Label="Stop" Click="AppBarButton_Click"/>
			<AppBarButton Icon="Play" Label="Play" Click="AppBarButton_Click"/>
			<AppBarButton Icon="Forward" Label="Forward" Click="AppBarButton_Click"/>

			<CommandBar.SecondaryCommands>
				<AppBarButton Label="Like" Click="AppBarButton_Click"/>
				<AppBarButton Label="Dislike" Click="AppBarButton_Click"/>
			</CommandBar.SecondaryCommands>

			<CommandBar.Content>
				<TextBlock Text="Now playing..." Margin="12,14"/>
			</CommandBar.Content>
		</CommandBar>

	</Grid>

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
This should be working now.
