### ISSUE TITLE
Support Dark and HighContrast in SystemResources.xaml

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1323]
## What would you like to be added:

Uno currently has support for the light theme resources only. Now that `ThemeResource` support exists, Dark and HighContrast could be added, too.

## Why is this needed:

To quote Lego Batman:

> I only work in black. And sometimes, very very dark grey.

Also, `HighContrast` is very important for accessibility

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

**Comment by MartinZikmund** [comment]
@davidjohnoliver Is the `SystemResources.xaml` autogenerated somehow or is it enough to bring the same set of `x:Key` resources for the new themes in manually?

**Comment by davidjohnoliver** [comment]
@MartinZikmund I don't think it's autogenerated, it's fine to copy missing values manually. 

tbh I don't know where dark resources are defined by UWP. I see `<ResourceDictionary x:Key="Light">` in the system `generic.xaml` but don't see the precise equivalent for dark/high contrast. Do you know?

**Comment by MartinZikmund** [comment]
@davidjohnoliver interestingly enough dark resources are in the "Default" section, so there is only Default, Light and HighContrast.

**Comment by MartinZikmund** [comment]
Tried this, but I am not sure which resources are Uno specific and which can be reused from Windows, so leaving this for now, if someone else may want to take this.

**Comment by MartinZikmund** [comment]
I was looking into this a bit more. Copy-pasting matching resources from UWP will produce mostly working app, except for a two issues:

- `TextBlock` foreground stays black even for `RequestedTheme=Dark`  (the default `Foreground` is hardcoded in the dependency property) - not sure how to fix this
- There are some missing resources even in the light theme, but also many resources which are present in different files outside of `SystemResources.xaml`, is there a reason to have them in separate XAML resource dictionaries, @jeromelaban ? I understand it is useful to have the control templates/styles separate, but colors and brushes could all be in `SystemResources.xaml` and in such case we could practically take the whole UWP `ThemeDictionaries` element and paste it as-is to `SystemResources.xaml`

**Comment by jeromelaban** [comment]
@MartinZikmund copy and pasting should be mostly right, but it has to come from the proper generic,xaml version (17763 in case). I did something similar for the CommandBar/AppBar in https://github.com/unoplatform/uno/pull/1623. For the TextBlock, this may have to do with @davidjohnoliver's work on styling, particularly with the ImplicitTextBlock's behavior.

The separation in SystemResources.xaml is mostly historical, where most should fit in a single file like the generic.xaml, and I'm questioning my choice of moving the AppBar/CommandBar to a different file to make it more manageable, yet diverge from the original styles...

By looking at WinUI 2.0, it seems that styles are now co-located with their respective control code, which makes a lot more sense.

**Comment by MartinZikmund** [comment]
@jeromelaban I resolved the `TextBlock` problem by setting the appropriate foreground value based on the theme with dependency property default value precedence (thus overwriting the default Black, but not interfering with further styling)

**Comment by MartinZikmund** [comment]
#1628 implements this

**Comment by MartinZikmund** [comment]
Do-ne! 🎉🎉🎉🎉
