### ISSUE TITLE
SVG image is cropped when using a margin 

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#13262]
I have an Image:
![image](https://github.com/unoplatform/uno/assets/69314237/c904e0fd-dc69-43e8-a733-743d01e8ca5f)

```XML
<Grid ColumnDefinitions="70,Auto,20">
    <Image Grid.Column="0" Source="ms-appx:///SomeApp/Assets/Icons/test1.svg" Stretch="Uniform"/>
</Grid>
```
I`m trying to use Margin for my image:
![image](https://github.com/unoplatform/uno/assets/69314237/e9e4e70c-e30c-4d0b-88a2-d376ce21c569)

```XML
<Grid ColumnDefinitions="70,Auto,20">
    <Image Grid.Column="0" Source="ms-appx:///SomeApp/Assets/Icons/test1.svg" Stretch="Uniform" Margin="3"/>
</Grid>
```
But its just cropping my image.
I`am expecting that it should be like the following example:
```XML
<Image Grid.Column="0" Source="ms-appx:///SomeApp/Assets/Icons/test1.svg"
		ui:VisualExtensions.Scale="0.5,0.5,0"
		ui:VisualExtensions.NormalizedCenterPoint="0.5,0.5"
		Stretch="Uniform"/>
```
![image](https://github.com/unoplatform/uno/assets/69314237/fe248af8-bcd9-48d2-98c6-2204435226d3)

But, as you can see its also cropping my image from the bottom and right side.
![image](https://github.com/unoplatform/uno/assets/69314237/35a97737-9cc2-4b62-82f7-0dc5e36294ae)

How can I fix that?

Repro: https://github.com/limeniye/UnoImageCropping

[UnoImageCropping-main.zip](https://github.com/unoplatform/uno/files/12342965/UnoImageCropping-main.zip)

_Originally posted by @limeniye in https://github.com/unoplatform/uno/discussions/13144_

**Comment by jeromelaban** [comment]
@limeniye could you specify which platform you're having the issue with? Also did you test with multiple platforms and does it work with windows?

**Comment by limeniye** [comment]
@jeromelaban  WinUI

**Comment by jeromelaban** [comment]
Got it. If it's windows only, it's a winui repository issue, make sure to open an issue there. I'll keep this opened until we can know that the uno targets fail as well.

**Comment by limeniye** [comment]
1. I've tested this problem at WinUI framework -- the same problem.
2. I've tried to find a similar discussion or issue at [microsoft-ui-xaml](https://github.com/microsoft/microsoft-ui-xaml) but I didn't.
3. Currently, I created discussion at repo and waiting for some answer.

**Comment by MartinZikmund** [comment]
@limeniye Can you please confirm this does not happen on non-Windows targets? In such case we can close this issue

**Comment by limeniye** [comment]
@MartinZikmund, currently I can't.

I'am trying to do the same with **Skia.Wpf**, but I don't see the image:
![image](https://github.com/unoplatform/uno/assets/69314237/45319e92-4150-4d18-94d8-2c8a8fda5b45)

```XML
<Grid x:Name="AddNewGrid" ColumnDefinitions="70,Auto,20">
    <Border Background="Red" Grid.Column="0"/>

    <Image Stretch="Uniform">
        <Image.Source>
            <SvgImageSource UriSource="ms-appx:///UnoAppNetSeven/Assets/Icons/new.svg" />
        </Image.Source>
    </Image>
    <TextBlock Grid.Column="1" Text="New" VerticalAlignment="Center"/>
</Grid>
```

For **Wasm** I have the following errors:
![image](https://github.com/unoplatform/uno/assets/69314237/ab8b2138-ac39-4934-be67-8342eae9e41f)

[SvgImageSample.zip](https://github.com/unoplatform/uno/files/12661943/SvgImageSample.zip)

**Comment by agneszitte** [comment]
@limeniye I have answered the discussion you opened on the Microsoft repo with a workaround for Windows.
https://github.com/microsoft/microsoft-ui-xaml/discussions/8754#discussioncomment-7074363
Now regarding Uno, you can have something much simpler using **Uno.Resizetizer** with the SVG file ([Documentation here to learn more about UnoImage](https://platform.uno/docs/articles/external/uno.resizetizer/doc/using-uno-resizetizer.html?tabs=classlib%2CAndroid#unoimage)) and that is already set up with our templates. For the sample app I created below I used our "Blank" template using our Wizard to easily create a new project.

Here is the sample on Windows:
![image](https://github.com/unoplatform/uno/assets/16295702/a5da497d-5f85-4b97-8753-c94dab0108c7)

But also working well on the other platforms:
- WASM
![image](https://github.com/unoplatform/uno/assets/16295702/b64348b6-2684-491d-876b-f1679c12328f)
- Android
![image](https://github.com/unoplatform/uno/assets/16295702/d92bf874-d5ef-416b-9198-1fa7cbb053e7)
- iOS
![image](https://github.com/unoplatform/uno/assets/16295702/f07f4eff-b673-47d9-a92e-2ec2ba6d0d2c)

@jeromelaban, @MartinZikmund, @pictos 
I have noticed an issue with Skia.GTK when testing
![image](https://github.com/unoplatform/uno/assets/16295702/68a50cde-97dd-4646-9f5b-886f7cb2bdcd)

**Comment by limeniye** [comment]
Good day, @agneszitte! 
Thank you for your answer.
Indeed, it works well as I expected 🥳🥳🥳🥳

**Comment by agneszitte** [comment]
@jeromelaban / @MartinZikmund / @pictos  should we open a separate issue for the svg that is a bit pixellated using uno.resizetizer/unoimage on Skia (can be reproduced with the [TestSvg.zip](https://github.com/unoplatform/uno/files/12805579/TestSvg.zip) sample app) ? Or do we already have a similar issue opened for this ?
