### ISSUE TITLE
XAML Application.RequestedTheme setting not generated

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1327]
## Current behavior

When user specifies `RequestedTheme` for application in `App.xaml`, it is not reflected in the generated `.g.cs` file for the XAML and hence the `RequestedTheme` property is not set to the user-selected option - it is always set to `Light`.

## Expected behavior

When the user sets `RequestedTheme` to `Dark`, it should be reflected in the generated `.g.cs`, In addition, it would be practical if this was generated *only* when the theme is set explicitly, as otherwise the system "default" theme should be used.

## How to reproduce it (as minimally and precisely as possible)

Create a Uno app, go to `App.xaml` and add `RequestedTheme="Dark"`. Observe the generated `.g.cs` does not contain the assignment and at runtime `Application.Current.RequestedTheme` is `Light`.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [x] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by kazo0** [comment]
I can take this if no one is looking into it yet

**Comment by MartinZikmund** [comment]
@kazo0 hi, sorry this is already resolved as part of #1628

**Comment by MartinZikmund** [comment]
Completely forgot to link this to the PR :-)

**Comment by MartinZikmund** [comment]
Do-ne! 🎉🎉🎉🎉
