### ISSUE TITLE
[Wasm] InfoBar not displaying the foreground "i" of the "Informational" Severity icon

### ISSUE THREAD

**Issue by silviuo** [unoplatform/uno#13283]
### Current behavior

On the [Canary](https://playgroundcanary.z19.web.core.windows.net/) and the [Staging](https://delightful-meadow-0abf9930f-staging.eastus2.1.azurestaticapps.net/) builds, the "Informational" Severity icon does not display the foreground "i".

![image](https://github.com/unoplatform/uno/assets/10283398/689c8f32-a03d-4995-b236-26a556a9d8cc)

### Expected behavior

The [Prod](https://playground.platform.uno/) build displays correctly:

![image](https://github.com/unoplatform/uno/assets/10283398/b3299390-cda2-41af-bd86-30601d89ddc6)

### How to reproduce it (as minimally and precisely as possible)

Visit 
https://playgroundcanary.z19.web.core.windows.net/#info-bar
and 
https://delightful-meadow-0abf9930f-staging.eastus2.1.azurestaticapps.net/#info-bar

### Works on UWP/WinUI

None

### Anything else we need to know?

For all other types of severity ("Success", "Warning", "Error"), the icon displays correctly on all three builds.

**Comment by Youssef1313** [comment]
The glyph exists even in the old Uno.Fonts.Fluent 2.0.0. Not sure from where Playground is trying to get the glyph.

**Comment by Youssef1313** [comment]
This is now fixed.
