### ISSUE TITLE
[Playground][Wasm] CalendarView 'down arrow' displayed as 'up arrow'

### ISSUE THREAD

**Issue by silviuo** [unoplatform/uno#13282]
### Current behavior

On the [Prod](https://playground.platform.uno/) Playground only, the down arrow icon shows as the up arrow: 

![image](https://github.com/unoplatform/uno/assets/10283398/5d86122b-f869-48b0-bddf-df82092b9609)

### Expected behavior

On the [Canary](https://playgroundcanary.z19.web.core.windows.net/) and the [Staging](https://delightful-meadow-0abf9930f-staging.eastus2.1.azurestaticapps.net/) builds, the icon is displayed correctly:

![image](https://github.com/unoplatform/uno/assets/10283398/120f6465-4d91-4517-aa9f-c00cbdb90953)

### How to reproduce it (as minimally and precisely as possible)

Visit https://playground.platform.uno/#date-and-time

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
Playground should probably be updated to use the latest `Uno.Fonts.Fluent`

**Comment by Youssef1313** [comment]
Since this works on canary and staging, I think it's an issue that has already been resolved.

@jeromelaban When do we update the production one?

**Comment by jeromelaban** [comment]
We'll be updating the playground soon, thanks.

**Comment by agneszitte** [comment]
> We'll be updating the playground soon, thanks.

@carldebilly this can be updated at the same time as https://github.com/unoplatform/uno/issues/13025 please ;)

**Comment by agneszitte** [comment]
Playground updated, so closing this issue
