### ISSUE TITLE
Uno SamplesApp failing with VS Dev tunnels

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#13289]
### Current behavior

I tried running the Wasm SamplesApp inside Uno via Dev tunnels on my phone to test sensor API, but I am getting a bunch of Failed to fetch errors. 
In console it throws many CORS errors like this:

`Access to fetch at '[https://global.rel.tunnels.api.visualstudio.com/auth/github?pb=package_Microsoft.Extensions.Logging.clr'](https://global.rel.tunnels.api.visualstudio.com/auth/github?pb=package_Microsoft.Extensions.Logging.clr%27) (redirected from '[https://devtunnels.ms/package/managed/Microsoft.Extensions.Logging.clr')](https://devtunnels.ms/package/managed/Microsoft.Extensions.Logging.clr%27)) from origin 'https://devtunnels.ms' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.` 

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.6.5

**Comment by Youssef1313** [comment]
https://github.com/microsoft/dev-tunnels/issues/284
