### ISSUE TITLE
Checkboxes not present for GridView with multiple selection

### ISSUE THREAD

**Issue by manfromarce** [unoplatform/uno#13295]
### Current behavior

When SelectionMode is multiple and IsMultiSelectCheckBoxEnabled=True:
- in the stable version (4.9.45) checkboxes are not present
- in the latest dev version (5.0.0-dev.2060) selection boxes are displayed for selected items (missing for unselected items), but the tick icon is not visible

This issue occurs for GridView while ListView is fine. I could only test Android, WASM and Skia GTK/WPF.

### Expected behavior

- Checkboxes with a tick icon should be present for selected items
- Empty selection boxes should still be displayed and clickable for unselected items to match the WinUi behavior

### How to reproduce it (as minimally and precisely as possible)

[UnoApp1.zip](https://github.com/unoplatform/uno/files/12369553/UnoApp1.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.9.45 / 5.0.0-dev.2060

### Affected platforms

WebAssembly, Android, iOS, Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report!

**Comment by limeniye** [comment]
Needs review

**Comment by sasakrsmanovic** [comment]
@manfromarce - did you see the fix implemented by @limeniye ? https://github.com/unoplatform/uno/pull/13349 . It would be great if we could get you to test it please. Would you have time for that please?

**Comment by manfromarce** [comment]
Yes, I will test it asap.

**Comment by manfromarce** [comment]
@limeniye PR looks good to me, the only thing is that the checkbox should have an accent color background to match the WinUI style:
![image](https://github.com/unoplatform/uno/assets/45036600/344d8fba-34e0-410b-b9c6-653938530cb9)
From WinUI 3 gallery:
![image](https://github.com/unoplatform/uno/assets/45036600/e498ee95-6dcc-481c-a1d3-d026536f1704)

**Comment by limeniye** [comment]
@manfromarce, yes, I'am fully agree with you.
But my task for to fix the problem.
After the merge I'll create discussion to ask about this style difference.
I'll be grateful to implement new checkbox'es styles for ListViewItem and GridViewItem as i WinUI.

**Comment by ramezgerges** [comment]
Fixed in #13349
