### ISSUE TITLE
[Issue(IssueTracker.Github, issueNumber, description, PlatformAffected.[Android|iOS|UWP|WASM])]

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1329]
# What would you like to be added:

I had a look through the codebase and didn't spot a pattern for correlating automated UI tests back to issue numbers. Over at the Xamarin Forms project they are using a convention such as:

```csharp
[Issue(IssueTracker.Github, 2, "Issue Description", PlatformAffected.Default)]
public MyCoolTest : TestBase
{
  ...
}
```

Wondering if folks would be 👍 or 👎 for introducing this pattern into the Uno codebase and using it to correlate defect resolution (tests) back to the original defect. The Xamarin.Forms implementation is over at https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.CustomAttributes/TestAttributes.cs#L51 

## Why is this needed:

It came to mind whilst implementing the test for the XAML source generator as part of fixing https://github.com/unoplatform/uno/issues/1321. "How do I leave a note to the future developer/maintainer why this empty class was added to this project?" and it's importance.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows

**Comment by jeromelaban** [comment]
Attributes are nice if the point is to get those at runtime, but if the point is to have a source-based tool, we can use a comment convention for that, it'll avoid adding weight to the final binary.

**Comment by davidjohnoliver** [comment]
I like this idea, either as standard comments or attributes.

**Comment by ghuntley** [comment]
I like attributes because it's a super easy convention is enforced by tooling thus consistent. 

Question: Is adding [not too much] weight to the final binary for SamplesApp/the tests a concern?

![image](https://user-images.githubusercontent.com/127353/62270210-ca9ef100-b478-11e9-878c-57dd643d956e.png)

**Comment by carldebilly** [comment]
I don't think referencing "external" issue numbers from code is a good idea. If the code is forked to another repository for whatever reason, those numbers will be noise.

Correct solution would be something absolute like an URL.

**Comment by XiaotianNetlift** [comment]
We could use different overloads to build the absolute path:

	[Issue(IssueTracker.Uno, 2, "Issue Description", default)]
	public IssueAttribute(IssueTracker type, int id, string description, PlatformAffected platforms)
	{
		this.Url = type switch
		{
			IssueTracker.Uno => $"https://github.com/unoplatform/uno/issues/{id}",
			IssueTracker.Private => $"https://github.com/unoplatform/private/issues/{id}",
			IssueTracker.UnoFork => $"https://github.com/xiaoy312/uno-fork/issues/{id}",
			_ => throw new ArgumentException(),
		};
	}

	[Issue(IssueTracker.External, @"asd.com\qwe\312", "Issue Description", default)]
	public IssueAttribute(IssueTracker type, string url, string description, PlatformAffected platforms) { }

**Comment by MartinZikmund** [comment]
This should be applicable to both UI and runtime tests
