### ISSUE TITLE
Consider updating the linker shipped with Uno packages

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#13293]
We ship the linker from https://github.com/unoplatform/uno/tree/master/src/SourceGenerators/Uno.UI.Tasks/external/linker

This hasn't been updated for long. So we lose any bug fixes done by dotnet/runtime, and also any potential performance improvements (e.g, https://github.com/dotnet/linker/pull/3094).

**Comment by jeromelaban** [comment]
We actually should be removing the linker entirely, now that there's a nuget package we can use instead. https://nuget.info/packages/Microsoft.NET.ILLink.Tasks/8.0.100-1.23067.1. It's not clear if that package will keep being used, though, as it's not been updated in a while.

**Comment by Youssef1313** [comment]
> It's not clear if that package will keep being used, though, as it's not been updated in a while.

The last package update is 9 days ago. It's not showing as the last version on NuGet due to strange versioning:

![image](https://github.com/unoplatform/uno/assets/31348972/5e2a0d77-1cfa-4176-854c-578275dcfbcd)

So yes, if we can use this package it will be great so that we easily get the updates.

**Comment by Youssef1313** [comment]
We no longer ship linker with our packages.
