### ISSUE TITLE
[ToggleSwitch/GTK/WASM] Thumb in wrong position when adding Shadows

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno#13303]
### Current behavior

While working with ShadowContainer and adding ToggleSwitch styles I came across this problem where the Thumb gets in the wrong position on GTK and WASM. It works on Windows. 

I isolated my style in the following repro:

[ToggleSwitchShadowRepro.zip](https://github.com/unoplatform/uno/files/12381777/ToggleSwitchShadowRepro.zip)

Please don't mind the project name and the mixed colors.

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
Thank you @eriklimakc
I'll take a look!

**Comment by agneszitte** [comment]
@Mergifyio backport legacy/4x
