### ISSUE TITLE
[Skia] has a bad scaling when the screen scaling is at 200%

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#13304]
### Current behavior

When your screen is at 200% scaling, the skia window takes 2 times the space, but the app remains the same size.
![image](https://github.com/unoplatform/uno/assets/90481654/d8a55763-2430-4ce1-9239-22cc53861fec)

### Expected behavior

The app should take the space of the whole window.

### How to reproduce it (as minimally and precisely as possible)

Put your screen at 200% scaling (maybe the screen being 4k is also important? I only have one screen to test this on, so, I'm not sure)
![image](https://github.com/unoplatform/uno/assets/90481654/5b5670c4-6708-435f-b4e0-9e653bbe9f0b)
Open an app like Uno.Gallery, Uno.Theme,  Uno.Toolkit or the app below on skia.gtk
[BasicApp.zip](https://github.com/unoplatform/uno/files/12383457/BasicApp.zip)

### Workaround

Put your screen at a diffrent scale?

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

```
<PackageReference Include="Uno.Material.WinUI" Version="3.0.0-dev.339" />
<PackageReference Include="Uno.Resizetizer" Version="1.2.0-dev.32" />
<PackageReference Include="Uno.WinUI.Skia.Gtk" Version="5.0.0-dev.2127" />
<PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0" />
<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
<PackageReference Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.4-preview.96" />
<PackageReference Include="SkiaSharp.Skottie" Version="2.88.3" />
<PackageReference Include="Uno.WinUI.RemoteControl" Version="5.0.0-dev.2127" Condition="'$(Configuration)'=='Debug'" />
<PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.0-dev.2127" />
```

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

17.6.5

**Comment by agneszitte** [comment]
cc @jeromelaban

**Comment by jeromelaban** [comment]
@Marc-Antoine-Soucy what's the culture of your system?

**Comment by Marc-Antoine-Soucy** [comment]
Can you expand a bit more on what you mean by culture? 
![image](https://github.com/unoplatform/uno/assets/90481654/75895637-e0c1-48ae-bf49-6c7108c1013a)
![image](https://github.com/unoplatform/uno/assets/90481654/0815d190-cd17-4aa5-b8e0-db98ff0715a6)
I feel like this is not what you're asking, but just in case.

**Comment by Marc-Antoine-Soucy** [comment]
I know I have a fairly old Version of windows 10 because I just learned today I only get the security upgrade automatically, I am going to update it in a few minutes. Could it be related?

**Comment by jeromelaban** [comment]
It may, but I'd still be surprised :) Let me know what that does.

**Comment by Marc-Antoine-Soucy** [comment]
It didnt do anything, I still get the bug, have a nice weekend :)
