### ISSUE TITLE
[Gallery-4X][All platform]Combo box- The Combobox size is small due to that Combobox+Icon text is bit truncating from top.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13339]
### Current behavior

![combobox issue](https://github.com/unoplatform/uno/assets/74563602/b56f18d3-176d-43ea-b254-187da553337e)
![checkbox-4X issue 2](https://github.com/unoplatform/uno/assets/74563602/ec3fad67-f8df-4306-872b-cce9a557613c)

### Expected behavior

![combobox correct](https://github.com/unoplatform/uno/assets/74563602/328c691a-0384-40c2-a83e-dabe4dafa326)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app on WASM.
2. Click on “ComboBox” from the "Component" list.
3. Go to the Material section.
4. click on the 'Placeholder' or 'Combobox+Icon'
5. Notice that the size of Combobox are small and the text 'Combobox+ Icon' is truncating after selecting option from combo list.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
@sakshi173 which platform is this issue for? The title says Wasm and the text says Skia. I'm not reproducing the issue on Wasm, so I'd guess this is a Skia issue?

**Comment by jeromelaban** [comment]
@sakshi173 thanks. Indeed this is a release blocker. @kazo0 @agneszitte

**Comment by sakshi173** [comment]
Verified this issue is fixed, closing it.

**Comment by agneszitte** [comment]
Thanks @sakshi173 !
