### ISSUE TITLE
TextBlock with red background and Text="██████████" doesn't have uniformally colored pixels

### ISSUE THREAD

**Issue by ramezgerges** [unoplatform/uno#13333]
### Current behavior

The colors in "█" should be uniformally reddish (the exact color should be `#C09090`. Surprisingly, there appears to be 2 specific pixel column that're a little bit redder (`#C49494`).
![MicrosoftTeams-image (2)](https://github.com/unoplatform/uno/assets/66218781/10cde1c4-1c78-4089-97d1-7eb5d6eb54df)
![MicrosoftTeams-image](https://github.com/unoplatform/uno/assets/66218781/8981801d-0ebf-4084-854a-b2cbb00bd86c)
![MicrosoftTeams-image (1)](https://github.com/unoplatform/uno/assets/66218781/0a67db0a-121d-47b8-8bcc-c577b5b74416)

### Expected behavior

The content should be uniformally red.

### How to reproduce it (as minimally and precisely as possible)

Check out the `FrameworkElement_Opacity` Page in RuntimeTests.

### Works on UWP/WinUI

Yes

**Comment by MartinZikmund** [comment]
@ramezgerges is it possible you hit the "gap" between the two characters? And because of antialiasing it contained a mix of the black and red?

**Comment by ramezgerges** [comment]
I initially thought so too, but from the screenshots above, the differently-coloured pixels are right in the middle of a █, so I don't think that's the case.

**Comment by MartinZikmund** [comment]
@ramezgerges I think this might be really it. The reason they seem to join together could be just antialiasing/sub-pixel snapping somehow. I guess this can be closed for now, unless we discover it elsewhere
