### ISSUE TITLE
[Gallery-4X][All Platform]RadioButton(Material)-Size of Radiobutton is too small.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13352]
### Current behavior

![RadioButton issue](https://github.com/unoplatform/uno/assets/74563602/5f21809f-6c9f-4c12-90bf-a50e4ff57c17)

### Expected behavior

![RadioButton correct](https://github.com/unoplatform/uno/assets/74563602/0bfe101c-f60f-4b0c-b7a6-a946da1da999)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app on WASM/Skia.Gtk. for 4X version.
2. Click on “RadioButton” from the "Component" list.
3. Go to the Material section.
4. Notice that the size of RadioButton are too small.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Skia (GTK on Linux/macOS/Windows)

**Comment by jeromelaban** [comment]
@sakshi173 could you also include if this is only a 4x bug? This would help prioritize the issues. Thanks!

**Comment by sakshi173** [comment]
@jeromelaban yes this is only 4X bug.

**Comment by kazo0** [comment]
Related to missing backport, kicking off a new canary build for 4x to be re-tested

**Comment by sakshi173** [comment]
verified this issue is fixed with latest canary build, closing it.
