### ISSUE TITLE
[Gallery-4X][All Platform] Slider(Material)-Track color is not similar as present for Gallery 5X and windows version.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13356]
### Current behavior

![slider Material issue 2](https://github.com/unoplatform/uno/assets/74563602/0f2a42ed-b893-4f80-841a-aebfb37fafbe)
![slider Material issue](https://github.com/unoplatform/uno/assets/74563602/5c8efd4e-e46d-4402-bf53-df8a7b9a8ff0)

### Expected behavior

![slider Material correct](https://github.com/unoplatform/uno/assets/74563602/3c3518fd-fe01-4fbd-8e16-698afe4c0e3f)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app  for 4X version.
2. Click on “Slider” from the "Component" list.
3. Go to the Material section.
4. Notice that the slider track color is displaying grey but for 5X and window version it is in white color.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS, Skia (GTK on Linux/macOS/Windows)

**Comment by agneszitte** [comment]
fyi @kazo0, @jeromelaban

**Comment by kazo0** [comment]
This may be the same issue as the [combobox issue](https://github.com/unoplatform/uno/issues/13339) caused by the missing backport, will double check

**Comment by kazo0** [comment]
@sakshi173 is this one still happening with latest 4x canaries?
