### ISSUE TITLE
NavigationViewBackRequestedEventArgs does not exist in UWP projects

### ISSUE THREAD

**Issue by scottkuhl** [unoplatform/uno#1336]
## Current behavior

I have a class that tries to catch the back navigation on NavigationView.

`_navigationView.BackRequested += OnBackRequested;`

...

```
        private void OnBackRequested(NavigationView sender, WinUI.NavigationViewBackRequestedEventArgs args)
        {
            NavigationService.GoBack();
        }
```

I get a build error on the UWP project, but not the WASM project: 

The type or namespace name 'NavigationViewBackRequestedEventArgs' does not exist in the namespace 'Windows.UI.Xaml.Controls' (are you missing an assembly reference?)	

I have referenced the Uno.Core, Uno.UI and Uni.Microsoft.Xaml.Behaviors.Interativity in the UWP project and the Uno.Wasm.Boostrap, Uno.UI and Uni.Microsoft.Xaml.Behaviors.Interativity in the Wasm project.

## Expected behavior

NavigationViewBackRequestedEventArgs should be available in the Windows.UI.Xaml.Controls namespace in UWP projects.

## How to reproduce it (as minimally and precisely as possible)

1. Create a new Uno template project.
2. Add a class called ShellViewModel to the shared project.
3. Reference NavigationViewBackRequestedEventArgs as a method parameter.
4. Build the UWP project.

```
using Windows.UI.Xaml.Controls;

namespace App1.Shared
{
    class ShellViewModel
    {
        private void OnBackRequested(NavigationView sender, NavigationViewBackRequestedEventArgs args)
        {
        }
    }
}
```

## Environment

Nuget Package: 1.28.0

Package Version(s):

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?

I am new to Uno, so it's quite possible I am doing something wrong.

**Comment by davidjohnoliver** [comment]
What are the target and minimum versions of Windows for your UWP head? Make sure the minimum is at least 1803.

From the [NavigationView docs](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview):


Windows version | SDK version | Value added
-- | -- | --
1803 | 17134 | BackRequested

**Comment by davidjohnoliver** [comment]
Seems like the default Uno template sets both to [1709 (16299)](https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj#L27).

We should probably consider increasing these defaults to 1809 (17763), the API version that Uno is currently [referenced against](https://github.com/unoplatform/uno/blob/master/src/Uno.UWPSyncGenerator.Reference/Uno.UWPSyncGenerator.Reference.csproj#L19).

**Comment by scottkuhl** [comment]
That was the issue.  Thanks.
