### ISSUE TITLE
[Gallery-4X and 5X][WASM/Skia.Gtk]-Swipecontrol- For few swipe control 'Icon' and for few other swipe control 'Label' is not visible.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13360]
### Current behavior

![swipecontrol issue 2](https://github.com/unoplatform/uno/assets/74563602/1cd22edf-4b83-43af-9842-606b937b96f8)
![swipecontrol issue 1](https://github.com/unoplatform/uno/assets/74563602/30fb8625-32b4-4737-ab41-84532a884c56)

### Expected behavior

![swipecontrol correct 2](https://github.com/unoplatform/uno/assets/74563602/658979ae-6548-4fca-883a-baf6da8c9ef4)
![swipecontrol correct 1](https://github.com/unoplatform/uno/assets/74563602/a861d626-1689-439b-a26f-d852e1d4bc02)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app for 4X  or 5X version.
2. Click on “SwipeControl” from the "Component" list.
3. Swipe on the right side for the 'swipe to reveal action' option.
4. Notice that for the swiped control  for 'Accept' Icon is missing and for 'Flag' Label is missing.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment]
This was fixed for 5x in https://github.com/unoplatform/uno/pull/13692

@agneszitte @jeromelaban Do we want to backport?

**Comment by jeromelaban** [comment]
@Youssef1313 not at this time.

**Comment by sakshi173** [comment]
Verified that issue is fixed, closing it.
