### ISSUE TITLE
[Gallery-4X][All Platform]VariableSizedWrapGrid control screen is blank.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13362]
### Current behavior

![Variablesize issue](https://github.com/unoplatform/uno/assets/74563602/b57ce246-e3c0-42a7-84a7-634aeb7ed5e2)

### Expected behavior

![Variablesize correct](https://github.com/unoplatform/uno/assets/74563602/44bfff43-7470-4d2f-93ab-b08fa5cab4f4)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app for 4X version.
2. Click on “VariableSizedWrapGrid” from the "Component" list.
3. Notice that the for VariableSizedWrapGrid  control the screen is empty.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS, Skia (GTK on Linux/macOS/Windows)

**Comment by jeromelaban** [comment]
@dr1rrb did you fix this one in master? I recall fixes around this.

**Comment by dr1rrb** [comment]
Yeah I did some fix: the issue was when the IR was not visible on load ... not sure if it applies to this case ?

**Comment by jeromelaban** [comment]
It may, and since this is tested on the 4x canary. Let's close this one as 5.0 done.

**Comment by agneszitte** [comment]
> It may, and since this is tested on the 4x canary. Let's close this one as 5.0 done.

FYI @sakshi173 it will be only for 5x
