### ISSUE TITLE
[Gallery-4Xand 5X][WASM/Skia.Gtk] PersonPicture- Circle to display 'BadgeNumber' is incorrect.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13377]
### Current behavior

![personpicture issue](https://github.com/unoplatform/uno/assets/74563602/3fa8c1f9-a020-4407-949d-3047b42e3625)

### Expected behavior

![RadioButton correct](https://github.com/unoplatform/uno/assets/74563602/cdde5151-7873-4bd6-bef8-f458d896da46)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app for 4X or 5X version.
2. Click on “Person Picture ” from the "UI Component" list.
3. Notice that for person picture displaying 'BadgeNumber is not in circle shape.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment]
Looks like a duplicate of https://github.com/unoplatform/uno/issues/7508 ? This is happening on 5x as well.

**Comment by sakshi173** [comment]
@Youssef1313, yes its dduplicate, I was not able to find the old one, so thought to reopen it, closing it now.
