### ISSUE TITLE
BorderThickness implementation issue

### ISSUE THREAD

**Issue by NGame1** [unoplatform/uno#1338]
## Current behavior
BorderThickness="5" work s fine and give me a border like this
![image](https://user-images.githubusercontent.com/19765248/62451339-58355600-b783-11e9-88c1-b53319987f7b.png)
But if you use Left, Top, Right, Bottom or LeftRight, TopBottom overrides if will fail.
![image](https://user-images.githubusercontent.com/19765248/62451565-c0843780-b783-11e9-8822-496bb8aacf16.png)
The border thickness always looking for the Top value. 
For Example BorderThickness="5,0" gives you a thick red border but BorderThickness="0,5" gives you a border with 5px thickness at all sides. Also the same problem in Left, Top, Right, Bottom override. It also looking to Top value only and it ignores all other values.

Package Version(s):
1.46.195-dev.2388

Affected platform(s):
- [x] iOS (Not tested)
- [x] Android
- [ ] WebAssembly (Not tested)
- [ ] Windows (Not tested)
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Sorry to hear that. Can you please a minimal test case that reproduces this?

**Comment by MartinZikmund** [comment]
This actually reproduces with the `NonUniformThicknessandRadius` sample in our Samples app

**Comment by NGame1** [comment]
Same issue on IOS but seems the IOS behavior is not similar to Android.

**Comment by dr1rrb** [comment]
This should now be fixed on iOS

**Comment by MartinZikmund** [comment]
Seems to work correctly now on all targets, closing :-) .
