### ISSUE TITLE
[Gallery-4X][All Platform] Infobadge-'Numeric Value', 'Style', 'Opacity' sections are missing.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13396]
### Current behavior

![infobadge issue](https://github.com/unoplatform/uno/assets/74563602/8c4466ef-7113-4e05-9ee0-c470e03e61b8)

### Expected behavior

![infobadge correct](https://github.com/unoplatform/uno/assets/74563602/f1b1208f-fd6d-417c-bb5a-b2701b6f4181)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app for 4X version.
2. Click on “Infobadge” from the "UI Component" list.
3. Notice that the 'Numeric Value', 'Style', 'Opacity' sections are missing.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS, Skia (GTK on Linux/macOS/Windows)

**Comment by jeromelaban** [comment]
@MartinZikmund did we fix anything for infobadge in 5x?

**Comment by sakshi173** [comment]
@jeromelaban, the Numeric Value, style and opacity options are missing for 4X not for 5X.

**Comment by agneszitte** [comment]
@jeromelaban, @kazo0 is this one only for 5x also or missing backport ?
https://github.com/unoplatform/Uno.Gallery/pull/671

**Comment by jeromelaban** [comment]
I don't think we need to backport fixes such as these, unless it makes QA easier. We're not going to be publishing the 4x gallery builds.

**Comment by agneszitte** [comment]
@sakshi173 this new sections will be available for 5x only, not part of 4x
