### ISSUE TITLE
[Gallery-4X][All Platform]Textblock is available for 'cupertino', but its not available in  5x and windows version of gallery.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13397]
### Current behavior

![textblock issue](https://github.com/unoplatform/uno/assets/74563602/c9b6ffe6-02fc-48a5-bc52-0cf0a5d78f5d)

### Expected behavior

![textblock correct](https://github.com/unoplatform/uno/assets/74563602/08818151-eb10-469f-b24f-44a03238f6ff)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app for 4X version.
2. Click on “TextBlock” from the "UI Component" list.
3. Notice that the Textblock is present for both 'Fluent' and 'Cupertino'.
4. Check same thing in gallery 5x version or Window version.
5. Notice that Textblock is present only for 1 section.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS, Skia (GTK on Linux/macOS/Windows)

**Comment by jeromelaban** [comment]
I can repro. @kazo0 is this something that is expected? Maybe it was not supposed to be the to begin with?

**Comment by agneszitte** [comment]
@kazo0 I will let you verify the latest changes for this one

**Comment by kazo0** [comment]
Missing a backport of https://github.com/unoplatform/Uno.Gallery/pull/807

**Comment by agneszitte** [comment]
@sakshi173 you will be able to retest this one tomorrow please (Wednesday)

**Comment by sakshi173** [comment]
Verify issue is fixed, closing it.
