### ISSUE TITLE
Corner Radius Limited to half of edge

### ISSUE THREAD

**Issue by iurycarlos** [unoplatform/uno#13392]
### Current behavior

Corner readius greater than half of the edge is been limited to the half of the Edge.
 
Result from Uno (Canary Playground at 2023/08/24)

http://playground.platform.uno/#b89dd277

### Expected behavior

Result from Xaml Studio:

![image](https://github.com/unoplatform/uno/assets/6876973/92911ea1-f3f9-4454-b8e5-21903eb36d6f)

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
Related: https://github.com/unoplatform/uno/issues/10263

**Comment by iurycarlos** [comment]
@agneszitte @jeromelaban @carldebilly @rafael-rosa-knowcode 
No Uniform CornerRadius

**Comment by jeromelaban** [comment]
@iurycarlos this is the behavior found in the latest 5.0 canary: https://playgroundcanary.z19.web.core.windows.net/#b89dd277.

**Comment by iurycarlos** [comment]
Exactly!
We can see that the behavior is slightly different:
![image](https://github.com/unoplatform/uno/assets/6876973/53dfc0f6-0245-4f71-9119-3eb979295c28)
What i could see is Uno doesn't reproduce radii greater than half of the smallest dimension.

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/pull/13682 will likely fix this.

**Comment by iurycarlos** [comment]
Thanks @Youssef1313 !
Fixed by #13682 
as canary result ilustrate here:

![image](https://github.com/unoplatform/uno/assets/6876973/f42a5c1d-cb4e-4abb-af70-4330bbdf3b5b)

**Comment by Youssef1313** [comment]
Thanks for confirming this @iurycarlos!
