### ISSUE TITLE
[Gallery-4X and 5X][All Platform]Pipspager- Pips are displaying in white color in light theme but for windows pips displaying in dark color.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13398]
### Current behavior

![pipspager issue](https://github.com/unoplatform/uno/assets/74563602/521df69e-f146-4443-aea7-0b063aff506e)

### Expected behavior

![pipspager correct](https://github.com/unoplatform/uno/assets/74563602/80b48f88-f501-4c50-b815-4c68626ef03f)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app for 4X or 5X version.
2. Click/tap Burger Menu on the left top right.
3. Ensure that the Gallery app is in Day Mode.
4. Click on “PipsPager” from the "UI Component" list.
5. Notice that pips are displaying in white color instead of dark color(similar to window version).

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS, Skia (GTK on Linux/macOS/Windows)

**Comment by agneszitte** [comment]
@kazo0  I think we now need to have a "Material" tab + "Fluent" tab for the samples for PipsPager

**Comment by kazo0** [comment]
There seems to be an issue with `muxc:` specific controls here. They are not included in the `XamlControlsResources` dictionary so they are not overriding the implicit styles defined in Material. These styles would need to be explicitly "reset" in the App.xaml to make sure the global app style for the control is not the Material one by default

We would need to add `<Style TargetType="muxc:PipsPager" />`  to the App.xaml to ensure the default Fluent PipsPager style is used, along with any other `TargetType="muxc:..."` controls that we have Material styles for in Gallery

**Comment by jeromelaban** [comment]
Indeed, they're not in the fluent v2 dictionary: https://github.com/unoplatform/uno/tree/master/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault.

That's very curious. @MartinZikmund do you recall why that is?

**Comment by agneszitte** [comment]
> Indeed, they're not in the fluent v2 dictionary: [`master`/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault](https://github.com/unoplatform/uno/tree/master/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault?rgh-link-date=2023-08-29T01%3A58%3A03Z).
> 
> That's very curious. @MartinZikmund do you recall why that is?

Workaround is in place now @kazo0 but can you open an issue for Uno please so it can be investigated/discussed?

**Comment by kazo0** [comment]
@agneszitte they also aren't there on Windows so I don't think they're supposed to be

**Comment by agneszitte** [comment]
> @agneszitte they also aren't there on Windows so I don't think they're supposed to be

Hum I see, let's see if @MartinZikmund has additional comments for this (cc @jeromelaban)

**Comment by sakshi173** [comment]
@agneszitte, Not sure is this fixed or not, its not getting cleared with the all the above comments. 
I retested defect and still these are present for 4X and 5X. below is the screenshot.
![pipspager issue](https://github.com/unoplatform/uno/assets/74563602/4cc405b8-a56b-47b9-9ef5-27ca78f26828)

**Comment by kazo0** [comment]
@MartinZikmund For Windows, adding [this ResourceDictionary](https://github.com/unoplatform/Uno.Gallery/blob/master/Uno.Gallery/Uno.Gallery.Shared/Views/Styles/FluentOverrides.xaml) after the `XamlControlsResource` declaration, like we're doing [here](https://github.com/unoplatform/Uno.Gallery/blob/4c17511b559aa8c847fa91bb8019883a56c9a2bf/Uno.Gallery/Uno.Gallery.Shared/Views/Styles/SamplePageLayout.xaml#L235-L236) seems to workaround this issue but it doesn't work on Uno platforms, maybe there's an Uno issue there on how it resolved the style based on `TargetType`?

I might be looking at old documentation but I feel like [this article](https://platform.uno/docs/articles/features/using-winui2.html) gives the impression that `XamlControlsResources` is where the WinUI 2.x+ control styles should live anyway in Uno platforms. So maybe it makes sense to move them there only then?

**Comment by jeromelaban** [comment]
Indeed, `XamlControlsResources` is essentially required in apps, though for uno's own tests it's not. We could have the tests that require those resources to be in the system styles to use `XamlControlsResources` explicitly to fix this.

**Comment by MartinZikmund** [comment]
Sounds good, will take care of this 👍

**Comment by MartinZikmund** [comment]
This is now no longer an issue as we are using fluent by default in Samples app
