### ISSUE TITLE
Popup is in wrong namespace, has wrong inheritance

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#134]
- Uno's Popup class is in the Windows.UI.Xaml.Controls namespace, it should be in the Windows.UI.Xaml.Controls.Primitives namespace;
 - It inherits from PopupBase. It should inherit directly from FrameworkElement.

The first is easy to fix (albeit a breaking change), the latter is more involved and requires finding a different way to share code between Popup and PopupBase.

**Comment by jeromelaban** [comment]
This can be used a Workaround:

```csharp
#if NETFX_CORE
using Popup = Windows.UI.Xaml.Controls.Primitives.Popup;
#else
using Popup = Windows.UI.Xaml.Controls.Popup;
#endif
```

**Comment by Youssef1313** [comment]
This is fixed in api-alignments branch:

https://github.com/unoplatform/uno/blob/feature/api-alignments/src/Uno.UI/UI/Xaml/Controls/Popup/Popup.cs

Probably should be closed. @davidjohnoliver @jeromelaban
