### ISSUE TITLE
[NET6.0] [Mac Catalyst] Unable to submit to .pkg file to the App Store due to missing icon 

### ISSUE THREAD

**Issue by jbtdevgit** [unoplatform/uno#13427]
### Current behavior

All details are in the discussion. I am unable to submit using both net6.0 old and new templates
Unable to upgrade to .net7.0 for now, if there are any other work arounds, gladly be insightful.
https://github.com/unoplatform/uno/discussions/13342

### Expected behavior

Should be able to submit to AppStore

### How to reproduce it (as minimally and precisely as possible)

In the discussions https://github.com/unoplatform/uno/discussions/13342

- Create new `net6.0` uno project, new template or legacy either way.
- Publish and submit to appstore

### Workaround

Upgrade to .net7.0

### Works on UWP/WinUI

None

### Environment

Visual Studio for Mac / Mac Catalyst

### Affected platforms

Mac Catalyst

### IDE

Visual Studio for Mac

**Comment by jeromelaban** [comment]
Thanks for the report.

The only significant difference in both your samples is:

(net7 on the left, net6 on the right)
![image](https://github.com/unoplatform/uno/assets/5839577/5fb9a5b4-43ca-4853-8468-d4853fe30422)

If there's another difference, it's not from the sources and may be related to a behavior from .NET 6 which is now out of support.

Can you explain again why are you unable to upgrade to .NET 7 ?

**Comment by jbtdevgit** [comment]
> 

There are packages that we are using that are out of support in .NET7.0, which we are unable to upgrade that we need.

**Comment by jeromelaban** [comment]
Thanks for the update. What kind of issues are you getting with .NET 7, specifically? In practice, `net6.0` packages should be compatible without much difference when the app head is targeting `net7.0`.

If get that you're prefer not upgrading, but it looks like the issue is coming from the .NET SDK and we won't be able to fix it.

**Comment by jbtdevgit** [comment]
> Thanks for the update. What kind of issues are you getting with .NET 7, specifically? In practice, `net6.0` packages should be compatible without much difference when the app head is targeting `net7.0`.
> 
> If get that you're prefer not upgrading, but it looks like the issue is coming from the .NET SDK and we won't be able to fix it.

I see, thanks. If that's the case we can now close the issue, and most likely we would try to upgrade to .net7.0 and see how it goes.
