### ISSUE TITLE
[iOS] SamplesApp won't open searched page

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#13446]
### On which page?

Any page in SamplesApp

### What's wrong?

When searching for a specific page while a different one is already open the app won't show it.

https://github.com/unoplatform/uno/assets/78549750/8c25a8de-2c75-401d-a7f5-0dd41ff385f6

Repro:
1. Open a random page in SamplesApp
2. Go to SEARCH and search for some page
3. Try to open it -> it closes the navigation bar and the old page still stays

**Comment by jeromelaban** [comment]
@morning4coffe-dev is this for the 4x or master branch?

**Comment by morning4coffe-dev** [comment]
@jeromelaban master

**Comment by jeromelaban** [comment]
Can you take a look at this for your next tasks? Thanks!

**Comment by morning4coffe-dev** [comment]
I retested the initial issue on my iOS emulator and I can't seem to reproduce it anymore. I have created a new issue for Martin's suggestion and I am closing this one.
