### ISSUE TITLE
[net7.0][mono][iOS] AOT fails for CommunityToolkit.WinUI.UI.dll

### ISSUE THREAD

**Issue by jbtdevgit** [unoplatform/uno#13454]
### Current behavior

Hi,

AOT compilation fails when running for assembly CommunityToolkit.WinUI.UI.dll for net7-ios.

Running the command `dotnet publish -f net7.0-ios -c Release` 
gives the following error:
`error : Failed to AOT compile CommunityToolkit.WinUI.UI.dll, the AOT compiler exited with code 134`

I think this is somewhat similar to the issue https://github.com/dotnet/runtime/issues/90032 but i've tried the workaround in the issue and it did not worked.

### Expected behavior

Build succeeds

### How to reproduce it (as minimally and precisely as possible)

Pull down the sample repo

https://github.com/jbtdevgit/UnoApp1_Test
Run `dotnet publish -f net7.0-ios -c Release` 

### Works on UWP/WinUI

None

### Environment

Other

### NuGet package version(s)

Uno.CommunityToolkit.WinUI.UI.Behaviors Version="7.1.100"
Uno.CommunityToolkit.WinUI.UI.Controls Version="7.1.100"

### Affected platforms

iOS

### IDE

Visual Studio for Mac

### IDE version

17.6 Preview (17.6 Build 1569)

**Comment by jeromelaban** [comment]
Thanks for the report. This is not an issue we can fix on Uno's end and there's no other known workaround than what is specified in https://github.com/dotnet/runtime/issues/90032 (Adding the `TrimmableAssembly` or upgrade to net8 preview 7).

**Comment by jeromelaban** [comment]
It will be in the `.Mobile` project. As for VS Mac not being supported, you can try out with our vscode extension.

**Comment by jbtdevgit** [comment]
> It will be in the `.Mobile` project. As for VS Mac not being supported, you can try out with our vscode extension.

Nope, both doesn't work, I used the latest vs 2022 preview (windows) and have .net8 preview 7 still gives the same error.
