### ISSUE TITLE
Gallery-5X and 4X][Wasm,iOS,Android] ShadowContainer- Text is 'Incorrect' written for 'Disabled' and 'Indeterminate' for checkbox. 

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13450]
### Current behavior

![texxt spelling issue](https://github.com/unoplatform/uno/assets/74563602/354087c3-2db1-4c69-979a-54e0dd45ddba)

### Expected behavior

![texxt spelling correct](https://github.com/unoplatform/uno/assets/74563602/0e2e8714-3605-4cdd-a37f-0c73f0e4cfff)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app for 4X or 5X version.
2. Click on “ShadowContainer” from the "Toolkit" list.
3. Go to Neumorphic section.
4. Choose 'checkbox' option from the combo list.
5. Notice that the 'Disabled' and 'Indeterminate' spelling is incorrect.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS

**Comment by agneszitte** [comment]
Re-Open for backport

**Comment by agneszitte** [comment]
@sakshi173 this issue can be tested tomorrow please

**Comment by sakshi173** [comment]
Verified this issue is fixed, closing it.
