### ISSUE TITLE
Implement Compass

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1347]
## What would you like to be added:

`Windows.Devices.Sensors.Compass` APIs

## Why is this needed:

🗺

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

## Anything else we need to know?

iOS has dedicated Compass sensor, but Android and WASM might need manual implementation based on Accelerometer + Magnetometer

**Comment by MartinZikmund** [comment]
Have this started locally, waits for #1346

**Comment by carldebilly** [comment]
#1346 is merged ;-)

**Comment by MartinZikmund** [comment]
Closing in favor of #11496
