### ISSUE TITLE
Update API Sync to WinAppSDK 1.4

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#13470]
### What would you like to be added

https://github.com/unoplatform/uno/discussions/13469#discussion-5578771

Current version is:
https://github.com/unoplatform/uno/blob/dd5e1d9f4eb0e558a46aa2151d69b3b9ff31f49b/src/Uno.UWPSyncGenerator.Reference/Uno.UWPSyncGenerator.Reference.csproj#L123

**Comment by Youssef1313** [comment]
Will do after https://github.com/unoplatform/uno/pull/13867

**Comment by MartinZikmund** [comment]
This will be useful for newer APIs like #14853
