### ISSUE TITLE
Adding `Uno.WinUI.Lottie` to WinUI target causes build error

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#13482]
### Current behavior

Create a new Uno app using the blank template (eg `dotnet new unoapp -preset blank -o LottieTestApp`) and then move the Lottie package reference in the class library so that it applies to all targets (by default it's in the non-winui block). Build the class library raises the following exception:

1>C:\temp\extdev\LottieTestApp\LottieTestApp\LottieTestApp.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null.'
1>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5167,5): error MSB3030: Could not copy the file "C:\temp\extdev\LottieTestApp\LottieTestApp\obj\Debug\net7.0-windows10.0.19041\MainPage.xbf" because it was not found.
1>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5167,5): error MSB3030: Could not copy the file "C:\temp\extdev\LottieTestApp\LottieTestApp\obj\Debug\net7.0-windows10.0.19041\AppResources.xaml" because it was not found.
1>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5167,5): error MSB3030: Could not copy the file "C:\temp\extdev\LottieTestApp\LottieTestApp\obj\Debug\net7.0-windows10.0.19041\AppResources.xbf" because it was not found.
1>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5167,5): error MSB3030: Could not copy the file "C:\temp\extdev\LottieTestApp\LottieTestApp\obj\Debug\net7.0-windows10.0.19041\MainPage.xaml" because it was not found.
1>Done building project "LottieTestApp.csproj" -- FAILED.

### Expected behavior

Uno.WinUI.Lottie should be referenced by any Uno target without it causing build errors 

### Works on UWP/WinUI

None

### Anything else we need to know?

Suggestion would be to add an empty entry for WinUI so that the winui target doesn't pick up the net7 library (and hence an invalid reference to to Uno.WinUI)

**Comment by jeromelaban** [comment]
Adding an empty entry will not be enough, because it will not be specific enough to exclude only WinAppSDK (wpf and winappsdk both use `net7.0-windows`). 

We would need to add a targets file that excludes the references from the package based on something like https://github.com/unoplatform/uno/blob/6e569bcd2c62b2679d92819fe298604cadd3b486/build/nuget/uno.winui.props#L7. which it fragile in itself.

**Comment by jeromelaban** [comment]
It's indeed not needed anymore.
