### ISSUE TITLE
Align FrameBufferHost namespace

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#13484]
### Current behavior

`FrameBufferHost` namespace isn't consistent with `GtkHost` and `WpfHost`.

### Expected behavior

Consistency.

### Works on UWP/WinUI

None

**Comment by nickrandolph** [comment]
When this is merged we'll need to update Samples and Template repositories (and probably Toolkit and Extensions since they both have sample projects)

**Comment by jeromelaban** [comment]
@Youssef1313 could you take a look at updating all the relevant uno.samples in the canary branch (There may not be that many), as well as updating uno.templates ?

**Comment by Youssef1313** [comment]
Sure. I'll do that.

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno.templates/pull/313
