### ISSUE TITLE
Vertical Slider gets set to inverted value when tapped

### ISSUE THREAD

**Issue by pdecostervgls** [unoplatform/uno#1350]
## Current behavior

When a vertical slider gets tapped at the 20% point, the thumb moves towards the 80% point

## Expected behavior

The vertical slider value reflects the position it was tapped at.

## How to reproduce it (as minimally and precisely as possible)

1. Goto Uno samples > Slider > Slider_Simple
2. Tap the vertical slider at around the 20% position from the bottom
3. Observe the value being set to the 80% point from the bottom

## Environment

Uno.UI Samples App

Affected platform(s):
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.1.6)
- [ ] for Mac (version: )

**Comment by ghuntley** [comment]
❤️ @pdecostervgls, thanks for jumping in and opening up a pull-request.

**Comment by carldebilly** [comment]
@pdecostervgls @ghuntley @davidjohnoliver Is this issue fixed?  The PR is merged.

**Comment by pdecostervgls** [comment]
@carldebilly Yes, I believe it is fixed with the merging of that PR.

**Comment by carldebilly** [comment]
Perfect.  I'll close this issue.  Reopen it (or open a new one) if you see a regression.
