### ISSUE TITLE
[Android] ItemsControl not resizing properly

### ISSUE THREAD

**Issue by rafael-rosa-knowcode** [unoplatform/uno#13539]
### What would you like to be added

In this issue 
https://github.com/unoplatform/uno.toolkit.ui/issues/798
we found that in some case the ItemsControl was not resizing correctly.
When we switched to ItemsRepeater the situation normalized and the resize worked.

So the ShadowContainer, in that case, was correctly stretching when the content was changed to be larger but if the content was then shrunk, the ShadowContainer does not resize:

See Shadow Builder control inside of the Toolkit sample app:

![shadowcontainerstretch](https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/bc0b52d2-2dad-4bb1-a1f8-bc8a2f04fd8a)

Or Attached to this Issue is a Project showing the case.

https://github.com/unoplatform/uno/assets/116665025/e1d2cfcb-99f7-40b7-8a55-fb1b39359311

Project

[UnoAppBlankSample.zip](https://github.com/unoplatform/uno/files/12541339/UnoAppBlankSample.zip)

### Why is this needed

we need to find out why the ItemsControl was not resized

### For which platform

Android

**Comment by Youssef1313** [comment]
Is it Android only?

**Comment by rafael-rosa-knowcode** [comment]
@Youssef1313 Attached a project with the situation happening
