### ISSUE TITLE
error UVSC0001: Building for net7.0-ios is not supported on win32-x64

### ISSUE THREAD

**Issue by rakeshghumatkar** [unoplatform/uno#13567]
### On which page?

MyApp06.Mobile.csproj

### What's wrong?

I am getting the error when trying to run uno app for Mobile. I have updated UNO template and using default UNO application.

Creating application using command : dotnet new unoapp -o MyApp06 -preset=blank -platforms android ios maccatalyst wasm gtk --vscode

Let me know if you need any additional information. If you have any idea feel free to shared,
Thanks in Advanced

**Comment by jeromelaban** [comment]
Thanks for the report. Can you [provide a binlog](https://platform.uno/docs/articles/uno-builds-troubleshooting.html) or your build ?

**Comment by rakeshghumatkar** [comment]
Hi @jeromelaban,
This is my build.
<img width="654" alt="image" src="https://github.com/unoplatform/uno/assets/88374586/90310e6b-add0-4875-8e16-97b272f6b9bf">

**Comment by jeromelaban** [comment]
Thanks. By the looks of it, there does not seem to be a problem in the command line. Where do you see the error that you originally mentioned?

**Comment by rakeshghumatkar** [comment]
I want to try Android, so what configuration is required?

**Comment by jeromelaban** [comment]
Android should be working fine. What happens when you select `net7.0-android` and the android emulators in the bottom status bar?

**Comment by rakeshghumatkar** [comment]
I can not see the android emulator in status bar.
<img width="959" alt="image" src="https://github.com/unoplatform/uno/assets/88374586/cfa5a621-85c5-4298-9c8b-30a8008b9576">

but I have enabled the emulator by F1 => emulator => View Android emulator => Pixel_3a_API_34_extension_level_7_x86_64

**Comment by rakeshghumatkar** [comment]
I have created new uno app, I am targeting only android app using following command : 
dotnet new unoapp -o MyAndroidApp -preset=blank -platforms android --vscode

Its build successfully
<img width="647" alt="image" src="https://github.com/unoplatform/uno/assets/88374586/2612bd80-475c-47ee-8886-65dabd699e25">

When I try to run and debug getting same error for android too.

<img width="464" alt="image" src="https://github.com/unoplatform/uno/assets/88374586/f347619e-3cde-4c1b-96f2-4787e91a2679">

**Comment by rakeshghumatkar** [comment]
Tried, getting same issue.
