### ISSUE TITLE
[Android] The app crashes with a null exception when you press next on a textbox

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#13574]
### Current behavior

![NextNullexception](https://github.com/unoplatform/uno/assets/90481654/7a98bcfc-3ecc-45b9-91cd-8178b5ffe050)

### Expected behavior

The app should not crash

### How to reproduce it (as minimally and precisely as possible)

```
<TextBox />

<TextBox />
```
[BasicApp.zip](https://github.com/unoplatform/uno/files/12560228/BasicApp.zip)

### Workaround

I do not know any

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

```
<PackageReference Include="Uno.Resizetizer" Version="1.2.0-dev.32" />
<PackageReference Include="Uno.WinUI" Version="5.0.0-dev.2468" />
<PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0" />
<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
<PackageReference Include="Uno.Extensions.Logging.OSLog" Version="1.6.0" />
<PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.0-dev.2468" />
<PackageReference Include="Uno.WinUI.RemoteControl" Version="5.0.0-dev.2468" Condition="'$(Configuration)'=='Debug'" />
````

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.6.5

**Comment by Youssef1313** [comment]
This will be fixed in https://github.com/unoplatform/uno/pull/13527

**Comment by agneszitte** [comment]
@Marc-Antoine-Soucy can you please verify this issue now that #13527 is merged please
