### ISSUE TITLE
(iOS) ProgressRing Inside DataTemplate not working

### ISSUE THREAD

**Issue by ajpinedam** [unoplatform/uno#13578]
### Current behavior

When using a ProgressRing inside a data template is not animating.

![uno_progressring_animation](https://github.com/unoplatform/uno/assets/1900897/5a1c67ef-44f3-4c45-aca0-ffda9239b706)

### Expected behavior

https://github.com/unoplatform/uno/assets/1900897/b3bb3c55-d502-4703-aa22-3549808c2f0f

_No response_

### How to reproduce it (as minimally and precisely as possible)

A page with the following structure

```xml
<Grid Padding="10,50,10,0" RowDefinitions="Auto,*" Background="White"> 
    <!-- it works -->
    <ProgressRing Grid.Row="0"
                    Foreground="Red"
                    Height="50"
                    Width="50" />

        <ListView Grid.Row="1"
                ItemsSource="abcdefghi"
                SelectionMode="None"
                Padding="0,20,0,0">
        <ListView.ItemTemplate>
            <DataTemplate>
                <StackPanel Margin="0,5">
                    <!-- not working-->
                        <ProgressRing Foreground="Orange" Height="50" Width="50" />
                </StackPanel>
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>
</Grid>
```

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI 4.9.17

### Affected platforms

iOS

### IDE

Visual Studio Code, Visual Studio for Mac

### IDE version

VS for Mac 17.6.3 (build 421)

**Comment by jeromelaban** [comment]
Does it do the same inside an ItemsControl ?

**Comment by jeromelaban** [comment]
Interesting. This could be a trick of ListView, which creates a "bitmap" of its contents.

**Comment by ajpinedam** [comment]
We upgraded to the latest Uno Stable Version (Uno 4.10.17), and the problem with the `ProgressRing` inside the `ListView` is no longer there.

I tried to find what the problem could have been, but it makes no sense at this point to spend any more time on it.

Closing this issue.

cc: @jeromelaban

**Comment by jeromelaban** [comment]
It may be related to https://github.com/unoplatform/uno/pull/11842.
