### ISSUE TITLE
Workshop: Mastering Uno

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1357]
## What would you like to be added:

Build a workshop that can be used at Unoconf, at hackathons and meetups that teaches folks everything they need to build applications with Uno.

## Why is this needed:

So we don't have to repeat ourselves and to provide folks with a step by step way to build their first Uno application.

## Anything else we need to know?

The course is being scaffolded over at https://github.com/unoplatform/workshop/tree/master/mastering-uno

**Comment by MartinZikmund** [comment]
I would definitely suggest including some guidance on surfacing native controls in Uno - for example I was trying to include Google AdMob in my Uno app and it was a bit challenging to get right. I expect more developers will need to do similar task as well.

**Comment by ghuntley** [comment]
I agree!

**Comment by ghuntley** [comment]
The workshop has been released and is open-source 🎉 

https://github.com/unoplatform/workshops
