### ISSUE TITLE
[Windows] Multiple layout phase for TextBox

### ISSUE THREAD

**Issue by roubachof** [unoplatform/uno#13579]
### Current behavior

When layouting a text box with self sizing, and a static text, there are multiple layout passes (2 or 3) and the textbox width is changing as observed in this repro sample when we monitor the text box size (just have a look at the output).

### How to reproduce it (as minimally and precisely as possible)

Run the sample on windows target and monitor the output.

[LayoutIssue.zip](https://github.com/unoplatform/uno/files/12561699/LayoutIssue.zip)

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Windows

**Comment by MartinZikmund** [comment]
Is this issue to align the behavior with Windows? Otherwise I think this would be something for the WinUI team to fix
