### ISSUE TITLE
[WASM] Bootstrap did not load app on mobile

### ISSUE THREAD

**Issue by easy28** [unoplatform/uno#13591]
### Current behavior

Uno.Wasm.Bootstrap version 8.0.0-dev.277 
ExecutionMode : InterpreterAndAot  

App did not load on mobile safari or mobile chrome.    also noticed  https://gallery.platform.uno/   did not load on mobile.

Uno.Wasm.Bootstrap version 8.0.0-dev.138 and before can load app correctly.

### Expected behavior

Load wasm app on mobile correctly.

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
Thanks for the report. Can you indicate which platform you're using? Recent builds of .NET 8 enable SIMD by default, and some older browsers don't support that. 

You can check [this table](https://webassembly.org/roadmap/) on the "Fixed-width SIMD" to determine the minimum version supported.

**Comment by jeromelaban** [comment]
Thanks for the report. Indeed there's an issue, but it may not be related to the bootstrapper.

## Note for contributors

Here's the stack trace:

![image](https://github.com/unoplatform/uno/assets/5839577/f1f48553-9b59-49e4-8bdd-3243c9864d98)

And the actual exception is:

![image](https://github.com/unoplatform/uno/assets/5839577/7ceb2929-3115-4c66-8a31-68df74fc3673)

This looks like a TSImport/CSP related issue.

**Comment by jeromelaban** [comment]
The issue looks like a memory corruption for arm64 specifically, and the location of the error changes on every build on the gallery. On desktop the app is working properly on x64, but not on arm64.

![image](https://github.com/unoplatform/uno/assets/5839577/a8e44c1e-f0f6-438c-bfa2-7cfa0ef59edf)

The Url is never suppose to look that way:

https://github.com/unoplatform/uno/blob/4c0adf8c66516197fde93ebbd859569cb8ae0c5b/src/Uno.UI.FluentTheme.v2/XamlControlsResourcesV2.cs#L27

Which would mean that the string is altered somehow, and cause this check to fail:

https://github.com/unoplatform/uno/blob/4c0adf8c66516197fde93ebbd859569cb8ae0c5b/src/Uno.UI/UI/Xaml/ResourceResolver.cs#L542

**Comment by easy28** [comment]
Uno.Wasm.Bootstrap 8.0.0-dev.152  is OK .  Has error when  Uno.Wasm.Bootstrap >= 8.0.0-dev.192

**Comment by jeromelaban** [comment]
This issue seems to have been addressed in recent Safari builds (both iOS and macOS arm64), closing for now.
