### ISSUE TITLE
[vscode] Deployment does not work when there's a space in the path

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#13600]
Terminal logs
<img width="651" alt="image" src="https://github.com/unoplatform/uno/assets/88374586/6dd101c2-7870-4874-8c0f-ac212fe34583">

_Originally posted by @rakeshghumatkar in https://github.com/unoplatform/uno/issues/13567#issuecomment-1714042869_

**Comment by jeromelaban** [comment]
@rakeshghumatkar let's continue here. Can you provide the same screenshot for the terminal window?

**Comment by rakeshghumatkar** [comment]
This is terminal window screenshot 

<img width="963" alt="image" src="https://github.com/unoplatform/uno/assets/88374586/405c5c16-cd5f-43b1-9bae-db1dedd83ef0">

Saying targeting multiple framework but I only targeting net7.0-android 

<img width="650" alt="image" src="https://github.com/unoplatform/uno/assets/88374586/b974bbd6-da2d-49ce-80bf-d8c28a0a6860">

**Comment by rakeshghumatkar** [comment]
Now I am getting tone of problems 

[{
	"resource": "/d:/net core MVC/UnoApp/MyAndroidApp/MyAndroidApp.Mobile/obj/Debug/net7.0-android/designtime/Resource.designer.cs",
	"owner": "csharp",
	"code": "CS0234",
	"severity": 8,
	"message": "The type or namespace name 'Resource' does not exist in the namespace 'MyAndroidApp' (are you missing an assembly reference?) [MyAndroidApp.Mobile]",
	"source": "csharp",
	"startLineNumber": 33,
	"startColumn": 4,
	"endLineNumber": 33,
	"endColumn": 33
}]

<img width="709" alt="image" src="https://github.com/unoplatform/uno/assets/88374586/a8537d87-05a0-4cbd-9eb6-a6da0af67281">

**Comment by spouliot** [comment]
The `.csproj` for the Android (only) project is under the `AndroidApp.Mobile` directory.

> AndroidApp.Mobile > § MyAndroidApp.Mobile.csproj

but you're trying to run from the parent directory

> D: \net core MVC\UnoApp\MyAndroidApp>

which likely has more than one `.csproj`, like the shared uno projects.

Try `dotnet run` from the `AndroidApp.Mobile` directory.

**Comment by rakeshghumatkar** [comment]
Getting same error

<img width="734" alt="image" src="https://github.com/unoplatform/uno/assets/88374586/7e09de5e-afd7-4f16-a38f-b9468e50979e">

**Comment by jeromelaban** [comment]
Thanks. It seems that you are running commands on the command line, rather than using VS Code's debugging features. Is that correct?

The steps you should be following are detailed here: https://platform.uno/docs/articles/get-started-vscode.html?tabs=windows%2Candroiddebug#mobile-targets-ios-android-mac-catalyst.

**Comment by rakeshghumatkar** [comment]
Did that also getting the first posted error ...

<img width="953" alt="image" src="https://github.com/unoplatform/uno/assets/88374586/ae477bd5-e42e-4569-b4af-33d2a0f9894f">

**Comment by spouliot** [comment]
> The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe-Command donet build D:\net core MVC\UnoApp\MyAndroidApp\MyAndroidApp.Mobile \MyAndroidApp.Mobile.csproj -f:net7.0-android

This still shows spaces in the path... have you updated the Uno extension to v0.9.24 ?

**Comment by jeromelaban** [comment]
Close this issue as it's fixed in latest 0.9.24. If you find other issues, let's create another discussion

**Comment by rakeshghumatkar** [comment]
Yes, I am using updated uno platform version 0.9.24 
<img width="691" alt="image" src="https://github.com/unoplatform/uno/assets/88374586/5460738b-ce9c-4481-875e-a696b8c01d2f">
