### ISSUE TITLE
document and provide examples of marshaling data between JavaScript and .NET

### ISSUE THREAD

**Issue by BenDerPan** [unoplatform/uno#1361]
## What would you like to be added:
I am trying to use uno build a [Emitter](https://github.com/emitter-io/emitter) web example, and I want to make emitter connection with C# backend( [Emitter .Net SDK](https://www.nuget.org/packages/emitter) )without any javascript, is this the best way? if it's not, how can I use C# backend communicate with javascript),  I don't known how can I do that, the [websocket](https://websockets-wasm.platform.uno/) example is great, and I wish there is a emitter example too, then we can know how to write a self designed protocol network communication application with uno.
## Why is this needed:
there are some cross-platform applications which have multi-language client SDK (include .net and js), and some developer are not very familiar with  js+html5+css (just like me), I wish this can help more people to get the key point on how to use uno build kinds of web application, especially use different network protocol(such as grpc, mqtt.etc)
## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows

**Comment by ghuntley** [comment]
Howdy BenDerPan!


> I am trying to use uno build a Emitter web example, and I want to make emitter connection with C# backend( Emitter .Net SDK ) without any javascript, is this the best way? 

It's the best way, because it's the most simple as it removes the need to marshall data between C# and Javascript. 

Looking at the [Emitter source code](https://github.com/emitter-io/csharp/blob/master/Emitter.nuspec#L40
) and they have a [netstandard TFM defined](https://docs.microsoft.com/en-us/dotnet/standard/frameworks). I newed up a brand application for Uno using the template wizard and was able to successfully install Emitter install into all of the TFM heads (apps).

Thus, in theory all that remains is to author the business logic into the shared project and configure it to communicate with your Emitter C# backend.

Hope that provides you with some insights and a clear path forward. I'm going to leave this issue open as a reminder that documentation on how to marshall between .NET and JavaScript when using webassembly requires improvements. 

ps. The source code for the websockets demo can be found at https://github.com/unoplatform/Uno.Wasm.WebSockets. 

pps. If you are looking for a example using Uno w/data then check out the "Universal Azure DevOps App" at https://platform.uno/code-samples/ which demonstrates persistence, authorization and CRUD style REST queries.

**Comment by BenDerPan** [comment]
@ghuntley  thank you, but I am not sure if  I am understand , in the Uno.Wasm.WebSockets example, there is a "WasmWebSockets.js" , should I write a "emitter.js" like that too?

**Comment by BenDerPan** [comment]
@ghuntley I write a simple test, but there is exception when I try to connect the emitter server, Is this the problem of emitter itself? 
### Exception
```shell
System.TypeInitializationException: The type initializer for 'Emitter.Connection' threw an exception. ---> System.PlatformNotSupportedException: System.Net.Dns:GetHostEntry is not supported on this platform.
mono.js:1   at System.Net.Dns.BeginGetHostEntry (System.String hostNameOrAddress, System.AsyncCallback requestCallback, System.Object stateObject) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mcs/class/System/System.Net/Dns.cs:190 
mono.js:1   at (wrapper delegate-invoke) System.Func`4[System.String,System.AsyncCallback,System.Object,System.IAsyncResult].invoke_TResult_T1_T2_T3(string,System.AsyncCallback,object)
mono.js:1   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncImpl[TArg1] (System.Func`4[T1,T2,T3,TResult] beginMethod, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, TArg1 arg1, System.Object state, System.Threading.Tasks.TaskCreationOptions creationOptions) [0x000ed] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs:919 
mono.js:1   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsync[TArg1] (System.Func`4[T1,T2,T3,TResult] beginMethod, System.Func`2[T,TResult] endMethod, TArg1 arg1, System.Object state) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs:839 
mono.js:1   at System.Net.Dns.GetHostEntryAsync (System.String hostNameOrAddress) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mcs/class/System/System.Net/Dns.cs:493 
mono.js:1   at Emitter.MqttNetworkChannel..ctor (System.String remoteHostName, System.Int32 remotePort, System.Boolean secure, System.Security.Cryptography.X509Certificates.X509Certificate caCert, System.Security.Cryptography.X509Certificates.X509Certificate clientCert, Emitter.MqttSslProtocols sslProtocol, System.Net.Security.RemoteCertificateValidationCallback userCertificateValidationCallback, System.Net.Security.LocalCertificateSelectionCallback userCertificateSelectionCallback) <0x30797b8 + 0x00034> in <baa9e8977f10437ca5f49c9ec02cfccb>:0 
mono.js:1   at Emitter.MqttClient.Init (System.String brokerHostName, System.Int32 brokerPort, System.Boolean secure, System.Security.Cryptography.X509Certificates.X509Certificate caCert, System.Security.Cryptography.X509Certificates.X509Certificate clientCert, Emitter.MqttSslProtocols sslProtocol, System.Net.Security.RemoteCertificateValidationCallback userCertificateValidationCallback, System.Net.Security.LocalCertificateSelectionCallback userCertificateSelectionCallback) <0x3077ec0 + 0x0015e> in <baa9e8977f10437ca5f49c9ec02cfccb>:0 
mono.js:1   at Emitter.MqttClient..ctor (System.String brokerHostName, System.Int32 brokerPort, System.Boolean secure, System.Security.Cryptography.X509Certificates.X509Certificate caCert, System.Security.Cryptography.X509Certificates.X509Certificate clientCert, Emitter.MqttSslProtocols sslProtocol) <0x309af98 + 0x00028> in <baa9e8977f10437ca5f49c9ec02cfccb>:0 
mono.js:1   at Emitter.MqttClient..ctor (System.String brokerHostName, System.Int32 brokerPort) <0x309aec0 + 0x00014> in <baa9e8977f10437ca5f49c9ec02cfccb>:0 
mono.js:1   at Emitter.Connection..ctor (System.String broker, System.Int32 brokerPort, System.String defaultKey) <0x309ac98 + 0x00066> in <baa9e8977f10437ca5f49c9ec02cfccb>:0 
mono.js:1   at Emitter.Connection..ctor () <0x309a5c8 + 0x0000a> in <baa9e8977f10437ca5f49c9ec02cfccb>:0 
mono.js:1   at Emitter.Connection..cctor () <0x309a588 + 0x00000> in <baa9e8977f10437ca5f49c9ec02cfccb>:0 
mono.js:1    --- End of inner exception stack trace ---
```
### My simple test code:
```C#
 private async void BtnSendMsg_Click(object sender, RoutedEventArgs e)
        {
            Emitter.Connection connection = new Connection(broker: "localhost", brokerPort: 8080, defaultKey: "lbbvo7YyBoSqAQpSgxIvNBAMTP3gy9wZ");
            try
            {
                await Dispatcher.RunAsync(
                Windows.UI.Core.CoreDispatcherPriority.Normal,
                () => tbOutput.Text = $"{Environment.NewLine}=============================================={Environment.NewLine}Connecting ...{Environment.NewLine}");
                connection.Connect();

                connection.On("lbbvo7YyBoSqAQpSgxIvNBAMTP3gy9wZ", "test/", async (c, msg) =>
                {
                    await Dispatcher.RunAsync(
                     Windows.UI.Core.CoreDispatcherPriority.Normal,
                     () => tbOutput.Text = $"{Environment.NewLine}=============================================={Environment.NewLine}Recv Msg: {msg.ToString()}{Environment.NewLine}");

                    Console.WriteLine($"Received Unknown Channel Message, Channel={c}");
                });
            }
            catch (Exception ex)
            {
                await Dispatcher.RunAsync(
                   Windows.UI.Core.CoreDispatcherPriority.Normal,
                   () => tbOutput.Text = $"{Environment.NewLine}=============================================={Environment.NewLine}Connection error {ex}{Environment.NewLine}");
            }
        }
```

**Comment by ghuntley** [comment]
That exception is coming from https://github.com/mono/mono/blob/master/mcs/class/System/System.Net/Dns.cs#L190

**Comment by BenDerPan** [comment]
@ghuntley  the browser doesn't support raw TCP/UDP connection, only support websockets/http(s)/webRTC, so if we use uno target webassembly, we have to use the standard web browser support sockets. 
 thank you :)

**Comment by BenDerPan** [comment]
by the way, I know emitter has javascript client [Javascript/TypeScript SDK](https://github.com/emitter-io/javascript) too, can I use uno to build the UI, and connect the data socket with emitter js, if so, any help for doing this?

**Comment by BenDerPan** [comment]
@ghuntley  Hey, I build a emitter library [Uno.Emitter](https://github.com/BenDerPan/Uno.Emitter]) which support Uno Wasm and it's based on Uno.Wasm.Websocket, I build a simple example which can work now, but it's not perfect now(need docs, more features like other emitter client libraries). I hope Uno.Emitter can be a member of Uno-Platform :).
when I upload my beta release to nuget, there is a problem of package id reserved.
`Uno.Emitter.1.0.0-beta1.nupkg  This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID.`

if this project can join in, let me know :), or I will change the package ID, such as `BenDerPan.Uno.Emitter`.

**Comment by BenDerPan** [comment]
@ghuntley  the example app [demo](https://github.com/BenDerPan/Uno.Emitter/tree/master/src/Example/EmitterApp)

**Comment by ghuntley** [comment]
Thanks Ben, I'll be in a position from next week onwards to look at this. UnoConf is in less than 72 hours! 🎉

**Comment by BenDerPan** [comment]
Best wishes for UnoConf！！！: )  👍 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by davidjohnoliver** [comment]
there's now an extensive tutorial on interop between JavaScript and .NET with Uno here: https://platform.uno/docs/articles/interop/wasm-javascript-1.html
