### ISSUE TITLE
[Android 10 Api 29] Text of TextBlock inside modal appears for 1 second and disappears after

### ISSUE THREAD

**Issue by Lee31416** [unoplatform/uno#13625]
### Current behavior

We have a modal with 1 icon 2 textblock and 1 button. When opening the modal while logged in our app everything displays fine and the text appears as it should but when doing the same thing when not logged in the text appears and then disappears. 

![image](https://github.com/unoplatform/uno/assets/72167772/08052e10-f649-489c-a36d-e283576bd257)

### Expected behavior

The content of the modal should appears and stays where its at. 

![image](https://github.com/unoplatform/uno/assets/72167772/cfc0336a-b757-442a-8cf2-05242948dda3)

### How to reproduce it (as minimally and precisely as possible)

1. Create an App with account logic
2. Open a modal after login validation but before showing the next page.
3. Emulate the app on Android 10 Api 29 
4. Observe that the text in the middle of the page disappears while the top and bottom content doesn't budge.

### Workaround

I googled and found that in winui the textblock doesn't have a background property anymore the workaround that fixes this issue is giving the textblock a border with a background color different then transparent. 

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.10.13

### Affected platforms

Android

### IDE

Visual Studio 2019

### IDE version

17.6.2

**Comment by jeromelaban** [comment]
Thanks for the report. 

Make sure to include a repro sample so we're looking at the same behavior.

**Comment by Lee31416** [comment]
@jeromelaban For the time being, we don't have the time to create a sample because it would be quite complicated and require a couple hours to do so. Maybe in the future we will create one and send it but for now that's all we can give for this issue. I'd be happy to answer any questions if it helps

**Comment by jeromelaban** [comment]
Thanks. Unfortunately, without a repro we're not able to investigate the issue further on our side.

What you can do is try to alter your application to see what can trigger this behavior by changing the XAML, such as changing properties, removing parents, changing animations, changing content and so on.

**Comment by Youssef1313** [comment]
Another thing to try is to at least understand why it disappears. Is it that `Text` is set to `string.Empty` somehow? If you hook into `TextChanged` event, are you able to see it being triggered with NewValue being empty? If so, the stack trace for that *may* help.

**Comment by MartinZikmund** [comment]
@Lee31416 Any further information you could provide use here please?

**Comment by Lee31416** [comment]
Didn't have time to work on doing a sample for this since. Sorry
