### ISSUE TITLE
Uno android application is not working in vs code

### ISSUE THREAD

**Issue by rakeshghumatkar** [unoplatform/uno#13622]
### Current behavior

I have created new uno app, I am targeting only android app using following command :
dotnet new unoapp -o MyAndroidApp -preset=blank -platforms android --vscode

Its build successfully
![image](https://github.com/unoplatform/uno/assets/88374586/48aadbd7-b490-4acb-ae1a-68d551682c75)

When I try to run and debug getting this error 
![image](https://github.com/unoplatform/uno/assets/88374586/c2b21c63-717c-48d8-92f1-0e30616626ea)

Terminal logs
<img width="653" alt="image" src="https://github.com/unoplatform/uno/assets/88374586/016a5d55-a47a-456a-918e-9a6fc9de3bbf">

This is my lunch.json file configuration for Mobile Platform
{
"name": "Uno Platform Mobile",
"type": "Uno",
"request": "launch",
// any Uno* task will do, this is simply to satisfy vscode requirement when a launch.json is present
"preLaunchTask": "Uno: android | Debug | android-x64"
}
and I am using latest uno extension version v0.9.24

### Expected behavior

The expected behavior should be display "UNO Hello World".

### Workaround

Step 1) use the cmd to create new Uno project for android : dotnet new unoapp -o MyAndroidApp -preset=blank -platforms android --vscode

Step 2) In the status bar, select the MyApp.Mobile project - by default MyApp.sln is selected.

Step 3) To the right of MyApp.Mobile, click on the target framework to select net7.0-android | Debug

Step 4) Enabled the emulator by F1 => emulator => View Android emulator => Pixel_3a_API_34_extension_level_7_x86_64 

Step 5) Tab on "Run & Debug UNO Mobile Platform" 

### Works on UWP/WinUI

None

### IDE version

vs code

**Comment by jeromelaban** [comment]
Thanks.

I'm not sure to understand the workaround, as it is the default way to go as documented in our site. What's the difference?

We've also mentioned to try in a folder that does not have spaces in it, can you try that to be sure it's not hiding something else. Move your project in in `d:\temp` or something similar and try again.

Still, we have a missing change for spaces in the path that will be published soon.

**Comment by spouliot** [comment]
> Step 4) Enabled the emulator by F1 => emulator => View Android emulator => Pixel_3a_API_34_extension_level_7_x86_64

There's nothing named like `View Android emulator` inside the Uno extension for VSCode. This is likely coming from a different extension you have installed.

To select an Android emulator (for Uno) you can use the UI (in the status bar) or the `Uno Platform: Select the device for execution` command (with `F1`).

**Comment by rakeshghumatkar** [comment]
> > Step 4) Enabled the emulator by F1 => emulator => View Android emulator => Pixel_3a_API_34_extension_level_7_x86_64
> 
> There's nothing named like `View Android emulator` inside the Uno extension for VSCode. This is likely coming from a different extension you have installed.
> 
> To select an Android emulator (for Uno) you can use the UI (in the status bar) or the `Uno Platform: Select the device for execution` command (with `F1`).

thanks 

> Thanks.
> 
> I'm not sure to understand the workaround, as it is the default way to go as documented in our site. What's the difference?
> 
> We've also mentioned to try in a folder that does not have spaces in it, can you try that to be sure it's not hiding something else. Move your project in in `d:\temp` or something similar and try again.
> 
> Still, we have a missing change for spaces in the path that will be published soon.

**Thanks for the help, issue is resolved now**

**Comment by rakeshghumatkar** [comment]
> > Step 4) Enabled the emulator by F1 => emulator => View Android emulator => Pixel_3a_API_34_extension_level_7_x86_64
> 
> There's nothing named like `View Android emulator` inside the Uno extension for VSCode. This is likely coming from a different extension you have installed.
> 
> To select an Android emulator (for Uno) you can use the UI (in the status bar) or the `Uno Platform: Select the device for execution` command (with `F1`).

**Thank You!**
