### ISSUE TITLE
Implement GridSplitter or equivalent

### ISSUE THREAD

**Issue by retupmoc258** [unoplatform/uno#13636]
### What would you like to be added

There may already be an equivalent option, but I could not find one. The GridSplitter class should be easily integratable with the existing Grid class. It enables dynamic resizing of the Grid from the user. It's the simple "Click and drag" event handling that tracks the movement of the click and changes the size of the Grid elements based on the position of the pointer/touch. Implementation should be relatively easy as most features are designed to access the properties of the Grid it is attached to. Most of the work would probably be in the implementation of the event handler with the native controls. The class should support WPF and UWP out of the box

### Why is this needed

Being able to resize parts of a view is incredibly handy in many modern applications. Being able to do so with natural user actions is far superior to inventing alternatives that will only clitter the screen. It should be possible (probably without too much effort) to implement this feature on all platforms, or at least most major platforms (I do not know as much about the Linux OS systems).

### For which platform

All

**Comment by limeniye** [comment]
Hello @retupmoc258!
Thank you for your question.
I can be wrong but I see that ```GridSplitter``` are implemented on [CommunityToolkit.WinUI.UI.Controls](https://learn.microsoft.com/en-us/dotnet/api/communitytoolkit.winui.ui.controls?view=win-comm-toolkit-dotnet-7.0), but not inside the Uwp or WinUI.
Also I see that ```GridSplitter``` are implemented on [Uno.CommunityToolkit.WinUI.UI.Controls](https://github.com/unoplatform/Uno.WindowsCommunityToolkit/blob/1ab328371a1309d08767c2b3d9ef74b39183fe40/CommunityToolkit.WinUI.UI.Controls.Layout/GridSplitter/GridSplitter.cs#L16).

Did you try the following steps:
```XML
    <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
        <PackageReference Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2"/>
    </ItemGroup>
    <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'windows'">
        <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls" Version="7.1.200-dev.6.gf657bb2e91"/>
    </ItemGroup>
```

```XML
xmlns:ui="using:CommunityToolkit.WinUI.UI.Controls"
```

```XML
<ui:GridSplitter/>
```

**Comment by retupmoc258** [comment]
Hi.  That is nice to hear, but I specifically selected tags for every platform, not just Windows.  I don't know why those tags didn't get placed anywhere... that's kind of annoying.

I tried to do just what you said and that implemented about 3 dozen errors after a rebuild... though I don't know that all of them were caused by these changes.  I tried to add the code to the csproj file, but I couldn't find one matching what you gave.  I found just one, so I used that.  The page can't find those namespaces, though, even after a few builds and rebuilds.  So that doesn't appear to be helping.

I tried the test code you linked to, and it likewise has similar issues.  Any namespace that is declared there for an object that isn't fully implemented by Uno won't find the namespace.  I don't know of anything else I can do about that.

It could be the setup for the file I'm using.  Anyway, long story short: There were lots of errors and I couldn't get it to work.  What I want would be an option that works on all platforms, too, not just Windows.

**Comment by limeniye** [comment]
![GridSplitter](https://github.com/unoplatform/uno/assets/69314237/d3015ea1-fa1c-4841-92d5-aa6ab13dc37f)

```XML
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="*" />
        <RowDefinition Height="Auto" />
        <RowDefinition Height="*" />
    </Grid.RowDefinitions>

    <Rectangle Grid.Row="0" Fill="Red"/>
    <controls:GridSplitter Grid.Row="1" />
    <Rectangle Grid.Row="2" Fill="Blue"/>
</Grid>
```

[GridSplitterSample.zip](https://github.com/unoplatform/uno/files/12671867/GridSplitterSample.zip)

**Comment by limeniye** [comment]
Ok, is that answered?

**Comment by retupmoc258** [comment]
Yes, that appears to work on other systems.  I suppose that makes me wonder why Uno does not say that it implements the GridSplitter at all.
