### ISSUE TITLE
Invalid file name: It must contain only [^a-zA-Z0-9_.]+. and File name cannot contain '.' other than for specifying the extension

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1364]
## Current behavior

When creating a brand new application via the Uno Solution templates blank image assets are created. The filenames of these images are no longer compatible with Xamarin.Android.

## Expected behavior

1. File -> New Uno Solution
1. Compile Android Application
1. Compilation success

## How to reproduce it (as minimally and precisely as possible)

1. File -> New Uno Solution
1. Compile Android Application
1. Compilation errors

## Environment

Nuget Package: master

Package Version(s):

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?

https://developercommunity.visualstudio.com/content/problem/671088/regression-invalid-file-name-it-must-contain-only.html

> Hi Geoffrey,
> 
> This is exactly the issue [1] I linked to in my previous comment. The Uno platform (for some reason) is including those content files into the AndroidResource item group. This is done by this code in the Uno platform itself.
>
> https://github.com/unoplatform/uno/blob/1c9b25893aa65d5736b7cfae8e253bd3c54a5c12/src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets#L36
> 
> The good news is that those items DO have a `LogicalName` metadata item which does have a valid filename. So once the fix above is released the app will compile as normal. As I stated in my previous comment this will only effect projects using aapt2. So to work around this issue you can put the following in your csproj
> 
> ```<AndroidUseAapt2>false</AndroidUseAapt2>```
> 
> or use
> 
> ```/p:AndroidUseAapt2=false```
> 
> on the command line.
> 
> [1] https://github.com/xamarin/xamarin-android/commit/e0145d1937a8e1230489b5df93b8883308e17683#diff-f8b51db87afcb0cc430594eb134bf41a

**Comment by ghuntley** [comment]
Closing off as has been merged as part of https://github.com/unoplatform/uno/pull/1383

**Comment by godrose** [comment]
@ghuntley 
Still happens to me
Env.: Windows 10 X64 , VS 2019 16.3
Repro steps:

1. Use Uno Platform App template
2. Update to the latest pre-release `Uno` packages
3. Compile

Expected: It just works
Actual: It doesn't (the same invalid file name error)

**Comment by ghuntley** [comment]
howdy @godrose, please add https://github.com/unoplatform/uno/pull/1383/files#diff-52c74e8822fe84d5af09976a7745e1f2R23 until https://github.com/unoplatform/uno/issues/1382 is resolved. If that doesn't resolve please open a new GitHub issue as discussions on closed issues don't raise notifications.
