### ISSUE TITLE
Samples app icons on Android are getting clipped

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#13652]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/1075116/93a72bc2-ed44-4dae-b4ee-f5007a984fc3)

### Works on UWP/WinUI

None

**Comment by MartinZikmund** [comment]
CC @Youssef1313 maybe related to your changes?

**Comment by Youssef1313** [comment]
I have a fix PR already. It is just missing a test to get merged.
