### ISSUE TITLE
xaml can't analyze symbols

### ISSUE THREAD

**Issue by lld1995** [unoplatform/uno#13666]
### Current behavior

lastest version make some bug with vs2022
and uno-check always report "Windows App SDK C# Templates is not installed"
![image](https://github.com/unoplatform/uno/assets/17978390/babd47b9-4905-44ad-8d4e-8ff1d51dec3e)

![image](https://github.com/unoplatform/uno/assets/17978390/36146dd8-c77c-4d35-be70-d8c5918760cd)

### Works on UWP/WinUI

None

**Comment by lld1995** [comment]
i have set .net7.0-windows,but it still can't analyze

**Comment by lld1995** [comment]
i temporarily set xmlns="clr-namespace:Microsoft.UI.Xaml.Controls;assembly=Uno.UI" to solve this issue

**Comment by jeromelaban** [comment]
Thanks for the report. You can find a [workaround here](https://platform.uno/docs/articles/get-started-wizard.html?tabs=windows#the-xaml-editor-shows-the-type-page-does-not-support-direct-content-message).

**Comment by lld1995** [comment]
> Thanks for the report. You can find a [workaround here](https://platform.uno/docs/articles/get-started-wizard.html?tabs=windows#the-xaml-editor-shows-the-type-page-does-not-support-direct-content-message).

it may a new issue,it doesn't present at last,when i update vs ,it shows
