### ISSUE TITLE
xaml can't analyze symbols when vs update to 17.7.4

### ISSUE THREAD

**Issue by lld1995** [unoplatform/uno#13677]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/17978390/418c6668-b7d0-4d57-beb3-3f527ccce6be)

![image](https://github.com/unoplatform/uno/assets/17978390/b597c398-06c8-4639-8bb6-f8cd31a32643)

it may something changed,but uno not do it?

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
Thanks for the report. Other than what was specified in https://github.com/unoplatform/uno/issues/13666, we do not have any work around at this time.

**Comment by lld1995** [comment]
ok,thanks
