### ISSUE TITLE
[Android] Disposing DefaultSharedPreferences will make Uno throw "Handle must be valid" on next SharedPreference access

### ISSUE THREAD

**Issue by KikkoMax** [unoplatform/uno#13686]
### Current behavior

Any call to dispose the object returned by Android.Preferences.PreferenceManager.GetDefaultSharedPreferences will make further attempts from uno to access shared preferences to throw a "Handle must be valid" exception.

### Expected behavior

Uno should be able to access the shared preferences correctly.

### How to reproduce it (as minimally and precisely as possible)

```
ApplicationData.Current.LocalSettings.Values.TryGetValue("test",
	out var savedValue);

// Will make handle invalid on next ApplicationData.Current.LocalSettings.Values.TryGetValue call
using (var z = Android.Preferences.PreferenceManager.GetDefaultSharedPreferences(Android.App.Application.Context))
{
	var y = z.GetString("test", "s");
};

// Won't make handle invalid
//var z2 = PreferenceManager.GetDefaultSharedPreferences(Android.App.Application.Context);
//var y2 = z2.GetString("test", "s");

ApplicationData.Current.LocalSettings.Values.TryGetValue("test",
	out var savedValue2);
```

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.10.13

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.7.4

### Relevant plugins

Resharper version 2023.2.1

**Comment by KikkoMax** [comment]
[Uno.UI.zip](https://github.com/unoplatform/uno/files/12653542/Uno.UI.zip)
[Uno.WinUI.zip](https://github.com/unoplatform/uno/files/12653543/Uno.WinUI.zip)

Code is found in MainPage.xaml.cs

**Comment by antoine-hebert** [comment]
Hello,

Thanks for the fast reply!

Actually, we're not explicitly disposing the instance, Xamarin.Essentials is:
https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/Preferences/Preferences.android.cs

It also looks like MAUI implementation hasn't changed and is also disposing:
https://github.com/dotnet/maui/blob/main/src/Essentials/src/Preferences/Preferences.android.cs

If PreferenceManager instance can actually be disposed, shouldn't you guys make sure you have a valid instance? Not doing so basically renders Uno incompatible with Essentials (MAUI or Xamarin).

Thanks!

**Comment by jeromelaban** [comment]
That makes sense, then we'll avoid keeping a reference, as it MAUI does it always.

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/4.10 legacy/4x
