### ISSUE TITLE
Nested MergedDictionaries not being included in XAML code gen

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#13724]
### Current behavior

Reinitializing a ResourceDictionary (A) and attempting to override resources that are referenced in A by adding a second ResourceDictionary (B) to A's MergedDictionaries does not work

Given the following xaml:

```xml
<StackPanel HorizontalAlignment="Center"
			VerticalAlignment="Center"
			Spacing="20">

	<Button Background="{ThemeResource MyBrush}"
			Content="Should Be Red"
			Width="200"
			Height="200" />

	<Border>
		<Border.Resources>
			<SolidColorBrush x:Key="MyBrush" Color="Blue" />
		</Border.Resources>
		<Button Background="{ThemeResource MyBrush}"
				Width="200"
				Content="Should Be Blue"
				Height="200" />
	</Border>

	<Border>
		<Border.Resources>
			<ResourceDictionary>
				<ResourceDictionary.MergedDictionaries>
					<ResourceDictionary Source="ms-appx:///UnoApp67/Styles/MyBrush.xaml">
						<ResourceDictionary.MergedDictionaries>
							<ResourceDictionary Source="ms-appx:///UnoApp67/Styles/MyColorGreen.xaml" />
						</ResourceDictionary.MergedDictionaries>
					</ResourceDictionary>
				</ResourceDictionary.MergedDictionaries>
			</ResourceDictionary>
		</Border.Resources>
		<Button Background="{ThemeResource MyBrush}"
				Width="200"
				Content="Should Be Green"
				Height="200" />
	</Border>
</StackPanel>
```

Where `MyBrush` is originally setup to use Red as its color in the AppResources.xaml:

```xml
<ResourceDictionary.MergedDictionaries>
	<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
	<ResourceDictionary Source="ms-appx:///UnoApp67/Styles/MyColorRed.xaml" />
	<ResourceDictionary Source="ms-appx:///UnoApp67/Styles/MyBrush.xaml" />
</ResourceDictionary.MergedDictionaries>
```

Where MyBrush.xaml contains:

```xml
<ResourceDictionary.ThemeDictionaries>
	<ResourceDictionary x:Key="Light">
		<SolidColorBrush x:Key="MyBrush" Color="{StaticResource MyColor}" />
	</ResourceDictionary>
	<ResourceDictionary x:Key="Default">
		<SolidColorBrush x:Key="MyBrush" Color="{StaticResource MyColor}" />
	</ResourceDictionary>
</ResourceDictionary.ThemeDictionaries>
````

Gives us the following mismatch of behavior compared to Windows:

![Screenshot 2023-09-20 150451](https://github.com/unoplatform/uno/assets/4793020/7e7e626f-7db5-4fd0-9e33-35574ff1d26d)

### Expected behavior

We should see the same behavior as Windows where the third Button is also Green.

### How to reproduce it (as minimally and precisely as possible)

[UnoApp67.zip](https://github.com/unoplatform/uno/files/12676751/UnoApp67.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI 4.10.13

### Affected platforms

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer)

### IDE

Visual Studio 2022

**Comment by ramezgerges** [comment]
There is actually a deeper problem. Even if you remove the initial loading of `MyBrush` and `MyColorRed` in `AppResources.xaml`, the color will be transparent (or non-existent).
```xaml
		<Border>
			<Border.Resources>
				<ResourceDictionary>
					<ResourceDictionary.MergedDictionaries>
						<ResourceDictionary Source="ms-appx:///Assets/Styles/MyBrush.xaml">
							<ResourceDictionary.MergedDictionaries>
								<ResourceDictionary Source="ms-appx:///Assets/Styles/MyColorGreen.xaml" />
							</ResourceDictionary.MergedDictionaries>
						</ResourceDictionary>
					</ResourceDictionary.MergedDictionaries>
				</ResourceDictionary>
			</Border.Resources>
			<Button Background="{ThemeResource MyBrush}"
				Width="200"
				Content="Should Be Green"
				Height="200" />
		</Border>
```

I'm not really sure why exactly. Even worse, If you remove the nested MergedDictionaries, like this:
```xaml
		<Border>
			<Border.Resources>
					<ResourceDictionary Source="ms-appx:///Assets/Styles/MyBrush.xaml">
						<ResourceDictionary.MergedDictionaries>
							<ResourceDictionary Source="ms-appx:///Assets/Styles/MyColorGreen.xaml" />
						</ResourceDictionary.MergedDictionaries>
					</ResourceDictionary>
			</Border.Resources>
			<Button Background="{ThemeResource MyBrush}"
				Width="200"
				Content="Should Be Green"
				Height="200" />
		</Border>
```
`MyColorGreen` will be read, but not `MyBrush`. This time the color will be the default grey

**Comment by kazo0** [comment]
@ramezgerges and those situations don't match whatever happens on Windows?

**Comment by ramezgerges** [comment]
Yes. As far as I've tested, the button should be green in all cases.

**Comment by ramezgerges** [comment]
I've edited my comment above. The second repro is not correct and actually matches Windows. The first one is as I said. I double checked now

**Comment by kazo0** [comment]
This issue seems to be surrounding the fact that the MergedDictionaries aren't included when pushing onto the XamlScope of the ResourceResolver.

So if I were to change the AppResources in the sample to:

```xml
<ResourceDictionary.MergedDictionaries>
	<!-- Load WinUI resources -->
	<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
	<ResourceDictionary Source="ms-appx:///UnoApp71/Styles/MyBrush.xaml">
		<ResourceDictionary.MergedDictionaries>
			<ResourceDictionary Source="ms-appx:///UnoApp71/Styles/MyColorRed.xaml" />
		</ResourceDictionary.MergedDictionaries>
	</ResourceDictionary>
</ResourceDictionary.MergedDictionaries>
```
 

I get this on Windows:
![image](https://github.com/unoplatform/uno/assets/4793020/d8adedee-f65d-4951-ac63-235177465749)

but this on Skia
![image](https://github.com/unoplatform/uno/assets/4793020/51fd02a0-2fdc-483f-9182-6b33119cebac)

because the MergedDictionaries aren't being taken into consideration, it falls back to searching the entire assembly for the MyColor resource and it just so happens to hit the MyColorGreen dict first so it makes the first one green as well

You can see that when it materializes the lazy MyBrush resource, the scope that it pushes onto the ResourceResolver is the MyBrush.xaml dict without its MergedDictionaries:

![image](https://github.com/unoplatform/uno/assets/4793020/e7a6d80e-4a7e-4cad-bb9c-9c9065465738)

**Comment by kazo0** [comment]
I'm seeing that nested MergedDictionaries aren't being parsed properly as part of the xaml code gen

So this xaml in appresources

```xml
<ResourceDictionary.MergedDictionaries>
        <!-- Load WinUI resources -->
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
        <ResourceDictionary Source="ms-appx:///UnoApp71/Styles/MyBrush.xaml">
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="ms-appx:///UnoApp71/Styles/MyColorRed.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </ResourceDictionary.MergedDictionaries>
```

Results in this generated code

```csharp
internal global::Microsoft.UI.Xaml.ResourceDictionary AppResources_3931c5840e5cf3841ef699ae79d393cd_ResourceDictionary
{
    get
    {
        if (_AppResources_3931c5840e5cf3841ef699ae79d393cd_ResourceDictionary == null)
        {
            _AppResources_3931c5840e5cf3841ef699ae79d393cd_ResourceDictionary = 
            new global::Microsoft.UI.Xaml.ResourceDictionary
            {
                IsParsing = true,
                MergedDictionaries = {
                new global::Microsoft.UI.Xaml.Controls.XamlControlsResourcesV2()
                {
                }
                ,
                // Source not resolved statically, falling back on external resource retrieval.
                global::Uno.UI.ResourceResolver.RetrieveDictionaryForSource("ms-appx:///UnoApp71/Styles/MyBrush.xaml", "AppResources.xaml")
                ,
                },
            }
            ;
            _AppResources_3931c5840e5cf3841ef699ae79d393cd_ResourceDictionary.Source = new global::System.Uri("ms-resource:///Files/AppResources.xaml");
            _AppResources_3931c5840e5cf3841ef699ae79d393cd_ResourceDictionary.CreationComplete();
        }
        return _AppResources_3931c5840e5cf3841ef699ae79d393cd_ResourceDictionary;
    }
}
```

**Comment by Youssef1313** [comment]
@kazo0 @jeromelaban I'm fixing part of the issue in https://github.com/unoplatform/uno/pull/13788. I'm not really sure about the XamlScope issue though.

**Comment by Youssef1313** [comment]
@kazo0 I see you opened #13799 and making this issue specific to the nested MergedDictionaries bug, so marking my PR as a fix for this issue.

**Comment by kazo0** [comment]
I have split these into two issues for now and will create a more relevant repro for https://github.com/unoplatform/uno/issues/13799 and this current issue can be related only to the XAML code gen
