### ISSUE TITLE
[Gallery][Wasm]ColorPicker- ColorPicker box is not displaying any color.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13754]
### Current behavior

![colorpickerr 5 issue](https://github.com/unoplatform/uno/assets/74563602/3a644fa9-207d-472d-b3ce-df2037e387aa)

### Expected behavior

![colorpicker 5 correct](https://github.com/unoplatform/uno/assets/74563602/ec7ab4c1-77fb-444a-9d6d-782319114a7b)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "ColorPicker" from the "Component" list.
4. Observe that the ColorPicker box is not displaying any color.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
Thanks @sakshi173, could you tell which version of galllery you used? 4x or dev? I'm not reproducing.

**Comment by sakshi173** [comment]
@jeromelaban , with latest canary build I am also not able to reproduce it, not sure why was I got this in previous build,
As now I am not able to reproduce it due to that closing it.
