### ISSUE TITLE
Blog posts, Talks and Podcasts that feature Uno

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1375]
👋 Howdy folks, if you see a blog post, talk or podcast that features Uno please share (even if you are the author of the content) below as a comment. 👇

# Blog Posts

## About Uno

- https://hackernoon.com/cross-platform-mobile-apps-with-net-and-uno-dee2b024281d
- https://www.freecodecamp.org/news/uno-platform/

## Getting Started with Uno

- https://keyholesoftware.com/2019/08/12/using-c-xaml-uno-platform-to-build-one-codebase-cross-platform-apps/
- https://nicksnettravels.builttoroam.com/post-2019-03-10-getting-started-with-platform-uno-aspx/
- https://nicksnettravels.builttoroam.com/post-2018-06-15-building-a-tipcalc-using-platform-uno-aspx/

## Using Uno

- https://nicksnettravels.builttoroam.com/uwp-splitview/
- https://nicksnettravels.builttoroam.com/uno-as-a-pwa/

## Libaries

- http://www.lhotka.net/weblog/UnoPlatformAndWebAssemblyWithCSLAV5.aspx

## Contributing to Uno

- https://blog.mzikmund.com/2019/03/contributing-to-the-uno-platform-part-1/
- https://blog.mzikmund.com/2019/04/contributing-to-the-uno-platform-part-2/
- https://blog.mzikmund.com/2019/04/contributing-to-uno-platform-part-3/

# Xamarin Forms on Webassembly

- https://javiersuarezruiz.wordpress.com/2019/10/16/xamarin-forms-en-la-web-con-webassembly-y-uno/

# UnoConf

- https://blog.mzikmund.com/2019/09/unoconf-2019/

# Podcasts

> On this episode of Eat Sleep Code, Jérôme Laban, Uno Platform CTO talks about the prospects of using Uno to create cross platform .NET applications. Jérôme also discusses the use of WebAssembly by Uno and what WebAssembly means for deploying .NET to the web.
https://www.stitcher.com/podcast/eat-sleep-code-the-official-telerik-podcast/e/60719171

- [Herding Code 239: Jerome Laban on Uno Platform
](https://herdingcode.com/herding-code-239-jerome-laban-on-uno-platform/)

> With Uno, you can build native apps and Web Assembly apps using WinRT (UWP) APIs. In this episode, Daniel is talking with Jérôme Laban, the CTO of Uno Platform about what Uno is, the history of Uno, the current state of Uno and much more. 
- [App In The Cloud • Episode 6](https://share.transistor.fm/s/6fe1a0c2)

# Talks

- [Jérôme Laban at Xamarin Developer Summit on the future of WebAssembly and .NET](https://youtu.be/t1cQsenAmNo?t=1049)
- [Microsoft Build: Building WebAssembly apps with Microsoft's stack - Lessons from the trenches](https://www.youtube.com/watch?v=mhoEqkJQlkY)
- [Meet the Uno Platform UWP everywhere | Martin Zikmund | MSP Czech & Slovakia](https://www.youtube.com/watch?v=NHFbPItDaDc)

**Comment by MartinZikmund** [comment]
I had a live webinar on Uno for Microsoft Student Partners - https://youtu.be/NHFbPItDaDc

**Comment by ghuntley** [comment]
@all-contributors please add @rockfordlhotka for his blogpost at http://www.lhotka.net/weblog/UnoPlatformAndWebAssemblyWithCSLAV5.aspx

**Comment by ghuntley** [comment]
@all-contributors please add @rockfordlhotka for his blog at http://www.lhotka.net/weblog/UnoPlatformAndWebAssemblyWithCSLAV5.aspx

**Comment by ghuntley** [comment]
@all-contributors please add @nickrandolph for his blog at https://nicksnettravels.builttoroam.com/uno-as-a-pwa/

**Comment by sakkshm** [comment]
Hey, do you have a repository of your website which I can contribute to!
I want to contribute for hacktoberfest and i am interested in web development and graphics!

**Comment by mizzleinetimi** [comment]
https://www.freecodecamp.org/news/uno-platform/

**Comment by ghuntley** [comment]
Xamarin Forms on WebAssembly — https://javiersuarezruiz.wordpress.com/2019/10/16/xamarin-forms-en-la-web-con-webassembly-y-uno/

**Comment by kaki104** [comment]
This is a YouTube video provided in Korean.

Creating a simple RSS reader using Uno Platform
Part1 : youtu.be/CQBfyTSV5uc
Part2 : youtu.be/WVN1SgKOGvI

What is UNO Platform?
youtu.be/li47OqE0tNI
