### ISSUE TITLE
Make the .NET Core 2.2 SDK requirement for WebAssembly more obvious

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1376]
> I had the same exact problem, but in my case the root cause was that the [.NET Core 2.2 SDK](https://dotnet.microsoft.com/download/visual-studio-sdks) wasn't installed. But no helpful errors pointed me to that!

_Originally posted by @andrewleader in https://github.com/unoplatform/uno/issues/983#issuecomment-520531020_

**Comment by ghuntley** [comment]
Howdy @andrewleader, I've broken your comment out into a new feedback issue. Can you please confirm that you experienced this when creating a brand new application via the Uno Platform Solution templates? 

If so, there maybe some things we can do. There's now a feature in Visual Studio for Windows where projects can specify which Visual Studio features/payloads should be installed. I was thinking, maybe Uno could create the appropriate files to configure Visual Studio for Windows to prompt if `.NET Core 2.2 SDK` is not installed.

**Comment by andrewleader** [comment]
Correct @ghuntley, this was when creating a brand new app using the Uno Platform Solution templates. I was trying out Uno for the first time, specifically for a web project where I already had a lot of great UWP code I could re-use :)

That sounds like a great solution! Thanks for being active on the feedback!!

**Comment by ghuntley** [comment]
Thanks @andrewleader, https://github.com/unoplatform/uno/pull/1384 has been opened to implement your feedback and we'll be doing release soon as part of https://github.com/unoplatform/uno/issues/1381 to make File -> New Application just work and put more people on the path to success by default ✨

**Comment by carldebilly** [comment]
@ghuntley We should considerer to migrate to 3.0, since 2.2 is not LTS.
