### ISSUE TITLE
[GTK][RatingControl] `RaisePropertyChangedEvent` not implemented error

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno#13765]
### Current behavior

When trying to use RatingControl on Skia.GTK, the control doesn't work. I get this error:

![image](https://github.com/unoplatform/uno/assets/114886335/9babf7d1-6d85-49b1-8e2b-035094e80eb3)

The link mentioned:

https://platform.uno/docs/articles/uno-notimplemented-types.html#m=Microsoft.UI.Xaml.Automation.Peers.AutomationPeer.void%20AutomationPeer.RaisePropertyChangedEvent%28AutomationProperty%20automationProperty%2C%20object%20oldValue%2C%20object%20newValue%29

### Expected behavior

RatingControl to work like in the other platforms.

### How to reproduce it (as minimally and precisely as possible)

[RatingControl-Gtk-Repro.zip](https://github.com/unoplatform/uno/files/12701778/RatingControl-Gtk-Repro.zip)

### Works on UWP/WinUI

Yes

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by MartinZikmund** [comment]
Fixed now!
