### ISSUE TITLE
Webview2 not rendering in Android and iOS

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#13770]
### Current behavior

Related to https://github.com/unoplatform/uno/issues/13605
Able to render `WebView2` with a simple page see _simplePage in the sample, but unable to render _richTextPage.

### Expected behavior

Render `WebView2`

### How to reproduce it (as minimally and precisely as possible)

Sample: [ForGab2.zip](https://github.com/unoplatform/uno/files/12704740/ForGab2.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.0.0-dev.2779

### Affected platforms

Android, iOS

### IDE

Visual Studio 2022

### IDE version

17.7.4

**Comment by jeromelaban** [comment]
@carlh98 can you explain what you mean by not rendering? Is there an error? is the content not showing at all?

/cc @MartinZikmund

**Comment by darenm** [comment]
Here is an updated version of the sample.
[DM-ForGab2.zip](https://github.com/unoplatform/uno/files/12704965/DM-ForGab2.zip)

Here are how the assets are organized. I have updated the html to use relative rather than absolute paths.
![image](https://github.com/unoplatform/uno/assets/1674843/22540a7c-642b-44dd-883a-249e4fe96f6e)

Android render:
![image](https://github.com/unoplatform/uno/assets/1674843/f2ea9301-2bc3-4174-8d38-c49300802af5)

Output in the console log:

```text
[OpenGLRenderer] Davey! duration=1171ms; Flags=1, FrameTimelineVsyncId=4917, IntendedVsync=4485022419830, Vsync=4485955753126, InputEventId=0, HandleInputStart=4485970806217, AnimationStart=4485970807923, PerformTraversalsStart=4485970876065, DrawStart=4486172639217, FrameDeadline=4485039086496, FrameInterval=4485970633800, FrameStartTime=16666666, SyncQueued=4486177107448, SyncStart=4486177687769, IssueDrawCommandsStart=4486178240062, SwapBuffers=4486191441239, FrameCompleted=4486194703777, DequeueBufferDuration=2671, QueueBufferDuration=579714, GpuCompleted=4486194671760, SwapBuffersCompleted=4486194703777, DisplayPresentTime=21474836488, 
[EGL_emulation] eglCreateContext: 0x7d7532778090: maj 2 min 0 rcv 2
[AndroidProtocolHandler] Unable to open asset URL: file:///android_asset/ForGab2/Assets/richtext/page/js/jquery.min.js
[AndroidProtocolHandler] Unable to open asset URL: file:///android_asset/ForGab2/Assets/richtext/page/css/font-awesome.css
[AndroidProtocolHandler] Unable to open asset URL: file:///android_asset/ForGab2/Assets/richtext/page/css/richtext.min.css
[AndroidProtocolHandler] Unable to open asset URL: file:///android_asset/ForGab2/Assets/richtext/page/js/jquery.richtext.js
[chromium] [INFO:CONSOLE(22)] "Uncaught ReferenceError: $ is not defined", source: file:///android_asset/ForGab2/Assets/richtext/page/index.html (22)
[EGL_emulation] app_time_stats: avg=460.76ms min=25.74ms max=1313.07ms count=3
[ProfileInstaller] Installing profile for com.companyname.ForGab2
```

**Comment by MartinZikmund** [comment]
Please see the documentation here (not published yet on our docs site): https://github.com/unoplatform/uno/blob/master/doc/articles/controls/WebView.md#navigating-to-web-content-in-the-application-package

The reason why the page does not load is that the files are not stored in the correct location - as the docs mention, the files need to be moved (either as as copy or as linked files) into the native locations for each platform - e.g. `Assets` on Android or `Resources` on iOS - then the file paths should be correct and the linked scripts and styles should load correctly.

**Comment by MartinZikmund** [comment]
Please verify if this helps, happy to provide further help if not!

**Comment by carlh98** [comment]
iOS
![image](https://github.com/unoplatform/uno/assets/7770915/da1978cb-cce1-4a1a-8a87-9ec50b1c8d93)

**Comment by darenm** [comment]
looks like either the css resolution of  the toolbar font isn’t working

**Comment by carlh98** [comment]
@MartinZikmund Here's the updated sample
[ForMartin.zip](https://github.com/unoplatform/uno/files/12728653/ForMartin.zip)

**Comment by MartinZikmund** [comment]
I have investigated and found the following:

1. The web files should be removed from the class library completely - instead they should really be just in the platform projects - e.g. remove from `ForGab2` and put the folder in `ForGab2.Windows` as well:

![image](https://github.com/unoplatform/uno/assets/1075116/f4030c2c-56b0-4f23-9037-e898c6101bb7)

2. Adjust the `SetVirtualHostNameToFolderMapping` as follows:

```csharp
Inline.CoreWebView2?.SetVirtualHostNameToFolderMapping
(
    "ForGab2",
    "richtext",
    CoreWebView2HostResourceAccessKind.Allow);
```

Here the second parameter is the folder name in each platform project - e.g. in root on Windows, in `Assets` on Android and in `Resources` on iOS.

3. The file URI now becomes `string _richTextPage = @"http://ForGab2/page/index.html";`
4. Finally, it seems that on Android the `WebMessageReceived` event occurs on a different thread, which causes an exception - I will fix that within Uno, but for now you can work around it safely:

```csharp
private async void Inline_WebMessageReceived(WebView2 sender, CoreWebView2WebMessageReceivedEventArgs args)
{
    if (!DispatcherQueue.HasThreadAccess)
    {
        DispatcherQueue.TryEnqueue(Microsoft.UI.Dispatching.DispatcherQueuePriority.Normal, () =>
        {
            Inline_WebMessageReceived(sender, args);
        });
        return;
    }

    // ... rest of the method here
```

**Comment by darenm** [comment]
@MartinZikmund Thanks - in your testing was the webfont correctly resolved and the toolbar button icons correctly displayed? In @carlh98 screenshot we can see the "square of disappointment" being displayed on the buttons.

**Comment by MartinZikmund** [comment]
@darenm Please make sure all the links within the files are using relative URLs. While full URL works with Windows, it is not possible to achieve this flexibility on mobile targets, so in the `font-awesome.css` the font `url()` should include for example `url('fontawesome-webfont.ttf?v=4.7.0') format('truetype')`

**Comment by MartinZikmund** [comment]
[ForGab2.zip](https://github.com/unoplatform/uno/files/12767918/ForGab2.zip)

Here is the updated version with the changes above, should hopefully work correctly!

**Comment by carlh98** [comment]
Thank you @MartinZikmund !

Android:
![image](https://github.com/unoplatform/uno/assets/7770915/6273f375-6690-4fe4-8340-311fb46edf4e)

iOS:
![image](https://github.com/unoplatform/uno/assets/7770915/e000959d-86b5-454a-afa1-6c16b7231b55)

cc: @darenm

**Comment by jeromelaban** [comment]
@carlh98 does the documentation need to be updated to reflect this ?

**Comment by carlh98** [comment]
It might be an issue regarding VS, but setting the build action was giving me problems.

In the sample that Martin just sent, he set the Build Action in the Mobile.csproj for iOS and Android instead of in Properties.
![image](https://github.com/unoplatform/uno/assets/7770915/8555820f-04ea-441f-9191-0d23903159d5)

![image](https://github.com/unoplatform/uno/assets/7770915/c08e1673-cb8d-4905-9809-8238b22a0b89)

Also for Android, AndroidAsset is not available in the list of properties and when I wrote it directly in the properties it gave me the following error

```
An error has occurred while saving the edited properties listed below:
	Build Action
One or more values are invalid. The item type 'AndroidAsset' is not supported by this project item provider.
```

**Comment by MartinZikmund** [comment]
Will update a docs with additional details 👍

**Comment by MartinZikmund** [comment]
It turns out that on Windows there is a difference in behavior for packaged vs. unpackaged apps. To enable this to work correctly in both, use the following:

![image](https://github.com/unoplatform/uno/assets/1075116/175f8858-a4a3-4eed-836f-378146f85f3b)

The `Package.Current` property either is not null (packaged app) or throws (unpackaged app). Then based on that the path to the files must be either relative or absolute.

In addition, you need to make sure all of the web files in the `Windows` project are marked as `Content` and set to `Copy if Newer`, as they are not copied to the output location unless the app is packaged.

![image](https://github.com/unoplatform/uno/assets/1075116/62341f39-b557-443e-849a-231c5fb7a3ba)

**Comment by darenm** [comment]
It is never simple, is it? Thanks for the update.

**Comment by Guidemarcus** [comment]
This new setup seems to push me into the right direction, but I am still not getting what I want on all platforms. Every time I try to navigate to my local file, I am finding this error message
![image](https://github.com/unoplatform/uno/assets/17101674/18418929-9a31-42c1-a327-ddd86a2f7db3)

I tried adding a delay before this and the navigation, but without success. Do you guys have an idea about why I am getting this?

@MartinZikmund

**Comment by Guidemarcus** [comment]
nvm, it seems like I was forgetting this
await RichTextBoxWebView.EnsureCoreWebView2Async();

I am getting close. I can show a Test.html file with "Hello World" in it. I am seeing a blank page when showing the index.html that is suppose to show the RichTextBox. I will continue my investigation tomorrow
