### ISSUE TITLE
Uno.[UI|WinUI].[Foldable|Maps] should support both net7.0 and net8.0

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#13786]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/31348972/c22bc87c-aef5-4d8e-b74b-7c87cc4c11fd)

![image](https://github.com/unoplatform/uno/assets/31348972/3ccac4cd-8880-44ca-9ef1-a0e012708748)

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
@jeromelaban I can take a look if this is a 5.0 candidate

**Comment by Youssef1313** [comment]
This is a CI race condition. The build that finishes last will end up being the package. This is because we are relying on `GeneratePackageOnBuild`. This package should use a nuspec file so that different artifacts from different jobs are "merged" together into a single package.

**Comment by Youssef1313** [comment]
If we are going to build net7.0 and net8.0 together in the same job soon, that should be sufficient to fix this issue.

**Comment by jeromelaban** [comment]
Let's revisit once we can merge packages with net8 RC 2.

**Comment by MartinZikmund** [comment]
Does this need to be looked into for 5.0?

**Comment by Youssef1313** [comment]
@MartinZikmund Likely 5.1 after we update to RC 2
