### ISSUE TITLE
Uno.UI build has UNOB0003 warnings

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#13780]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/31348972/a996e833-53d0-48d7-9c2b-8a403ce741a7)

### Expected behavior

These warnings shouldn't be there.

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
For fixing this, we'll need to rename the iso codes to their updated versions as the existing ones are netfx compatible only.
