### ISSUE TITLE
ComboBox display value member property path when nothing selected

### ISSUE THREAD

**Issue by JhonH3avy** [unoplatform/uno#1387]
## Current behavior

The ComboBox is displaying the value member property path when there is nothing selected.

## Expected behavior

The ComboBox should display nothing when there is no item selected.

## How to reproduce it (as minimally and precisely as possible)

Repo link: https://github.com/JhonH3avy/DeletableComboBoxUnoSandbox.git

## Environment
Nuget Package: 
- Uno.UI 1.46.199-dev2445

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.2.1)
- [ ] for Mac (version: )

Relevant plugins
- [x] Resharper (version: 183.0)

## Anything else we need to know?

The problem I think may be related to dynamic binding. The repo has a complete way to reproduce the problem, but there is no clear way to know what part is making the binding fail and the ComboBox instead of displaying the ValueMember property is displaying the Name property of the ViewModel.

**Comment by carldebilly** [comment]
The fix has been merged into "master" branch, Package v`1.46.221-dev.2630`
