### ISSUE TITLE
Layouts with lots of buttons are taking too much time to load

### ISSUE THREAD

**Issue by JhonH3avy** [unoplatform/uno#1388]
## Current behavior

A page that have a great number of control takes too much to load.

## Expected behavior

The page should take the same amount of time to load as in the UWP solution.

## How to reproduce it (as minimally and precisely as possible)

Repo link: https://github.com/JhonH3avy/ControlLoadingPerformance.git

## Environment

Nuget Package:
- Uno.UI: 1.46.199-dev2445 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version:16.2.1)
- [ ] for Mac (version: )

Relevant plugins
- [x] Resharper (version:183.0)

## Anything else we need to know?

The repo has four pages that have different amounts of controls, the more controls the page have the time to load the page grows apparently linearly.

**Comment by jeromelaban** [comment]
This issue may have been significantly improved by the use of AOT or PG-AOT. Is it still the case ?

**Comment by JhonH3avy** [comment]
I don't know for sure, but I am going to try it. Is there a current way of implementing AOT like a blog post or something to follow?

**Comment by jeromelaban** [comment]
The most recent one will be this one: https://platform.uno/blog/profile-guided-aot-in-uno-platform-reduces-package-size-by-50. Note that you'll have [to setup WSL](https://github.com/unoplatform/Uno.Wasm.Bootstrap#required-configuration-for-aot-mixed-mode-or-external-bitcode-support-compilation-on-windows-10).
