### ISSUE TITLE
[WASM] Support TextBox.InputScope to allow input restrictions

### ISSUE THREAD

**Issue by JhonH3avy** [unoplatform/uno#1389]
## What would you like to be added:
An input control that only accepts numbers. For example it can be an input control like TextBox but with the option to only recieve numbers. This is done in Android and iOS.

## Why is this needed:
There are complex forms that need specific input and user could be confused over the the way they should give input, so it can give like a safe way to users to enter the respective input.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows

## Anything else we need to know?
Telerik have a control that can do this, but sadly this control is not currently working on WASM.

**Comment by Youssef1313** [comment]
UWP doesn't do ANY validation or restriction for the allowed input. The correct behavior is to just change the software keyboard. (not sure if it's possible in Web, will check)

**Comment by Youssef1313** [comment]
Fixed in https://github.com/unoplatform/uno/pull/7074
