### ISSUE TITLE
[MacOS] [Android/iOS] Unable to start a debug of unoapp in VS code when following documentation

### ISSUE THREAD

**Issue by GabrielChouinardLetourneau** [unoplatform/uno#13899]
### Current behavior

When creating a project `unoapp` following the steps in the [Get Started on VS Code](https://platform.uno/docs/articles/get-started-vscode.html?tabs=windows%2Candroiddebug). On Mac, it seems like [the Mobile Targets step ](https://platform.uno/docs/articles/get-started-vscode.html?tabs=windows%2Candroiddebug#mobile-targets-ios-android-mac-catalyst) is not feasible. As seen in this screenshot, there is no way to select the solution we want to debug.

![Screenshot 2023-10-04 at 2 46 20 PM](https://github.com/unoplatform/uno/assets/37672082/82174252-bf53-40b4-9d97-badcbbda5db1)

### Expected behavior

We should be able to debug from scratch with the `unoapp` template following that documentation entry

### How to reproduce it (as minimally and precisely as possible)

1. Open a Terminal.

2. Install the tool by running the following command from the command prompt:
`dotnet tool install -g uno.check`

- To update the tool, if you already have an existing one:
`dotnet tool update -g uno.check`

3. Run the tool from the command prompt with the following command:
`uno-check`
If the above command fails, use the following:
`~/.dotnet/tools/uno-check`

4. Install the Uno project templates
`dotnet new install Uno.Templates`
- Then inside the same terminal, type the following to create a new project:
`dotnet new unoapp -o MyApp -preset=blank -platforms android ios --vscode`

5. Follow the rest of the instructions (skipping WASM, GTK) in the documentation until the `Mobile Targets`

### Works on UWP/WinUI

None

### Environment

Other

### NuGet package version(s)

- Microsoft.Extensions.Logging.Console: 7.0.0
- Uno.Core.Extensions.Logging.Singleton: 4.0.1
- Uno.Extensions.Logging.OSLog: 1.4.0
- Uno.Resizetizer: 1.1.3
- Uno.UI.Adapter.Microsoft.Extensions.Logging: 4.10.22
- Uno.UniversalImageLoader: 1.9.36
- Uno.WinUI: 4.10.22
- Uno.WinUI.Lottie: 4.10.22
- Uno.WinUI.RemoteControl: 4.10.22
- Xamarin.Google.Android.Material: 1.9.0.2

### Affected platforms

Android, iOS

### IDE

Visual Studio Code

### IDE version

1.82.3

### Relevant plugins

VS code extensions:

- **Uno Platform: v0.9.25**\
- **C#: v2.4.4**

### Anything else we need to know?
I am trying to use VS code on MacOS for a project that has not migrated to WinUI and that is still using the (UWP, Droid, iOS)
_No response_

**Comment by jeromelaban** [comment]
Thanks for the report. There may be a specific issue with Omnisharp. What's do you see in the Omnisharp log?

**Comment by GabrielChouinardLetourneau** [comment]
@jeromelaban the logs are looking like this currently when we open the folder's project: 
```
Starting OmniSharp server at 10/4/2023, 3:20:11 PM
    Target: /Users/gabriel.chouinard@nventive.com/Documents/Repos/VScode-UnoGabarit/VScode-UnoGabarit.sln

OmniSharp server started with .NET 7.0.401
.
    Path: /Users/gabriel.chouinard@nventive.com/.vscode/extensions/ms-dotnettools.csharp-2.4.4-darwin-arm64/.omnisharp/1.39.7-net6.0/OmniSharp.dll
    PID: 17918

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 4 MSBuild instance(s)
            1: .NET Core SDK 7.0.401 17.7.3 - "/usr/local/share/dotnet/sdk/7.0.401/"
            2: .NET Core SDK 7.0.308 17.6.10 - "/usr/local/share/dotnet/sdk/7.0.308/"
            3: .NET Core SDK 6.0.414 17.3.2 - "/usr/local/share/dotnet/sdk/6.0.414/"
            4: .NET Core SDK 6.0.122 17.0.1 - "/usr/local/share/dotnet/sdk/6.0.122/"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 7.0.401 17.7.3 - "/usr/local/share/dotnet/sdk/7.0.401/"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/gabriel.chouinard@nventive.com/Documents/Repos/VScode-UnoGabarit'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/gabriel.chouinard@nventive.com/Documents/Repos/VScode-UnoGabarit/VScode-UnoGabarit.sln'.
[warn]: OmniSharp.MSBuild.ProjectSystem
        Found project that doesn't exist on disk: /Users/gabriel.chouinard@nventive.com/Documents/Repos/VScode-UnoGabarit/VScode_UnoGabarit/VScode_UnoGabarit.csproj
[warn]: OmniSharp.MSBuild.ProjectSystem
        Found project that doesn't exist on disk: /Users/gabriel.chouinard@nventive.com/Documents/Repos/VScode-UnoGabarit/VScode_UnoGabarit.Base/VScode_UnoGabarit.Base.csproj
[warn]: OmniSharp.MSBuild.ProjectSystem
        Found project that doesn't exist on disk: /Users/gabriel.chouinard@nventive.com/Documents/Repos/VScode-UnoGabarit/VScode_UnoGabarit.Mobile/VScode_UnoGabarit.Mobile.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/gabriel.chouinard@nventive.com/Documents/Repos/VScode-UnoGabarit'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/gabriel.chouinard@nventive.com/Documents/Repos/VScode-UnoGabarit' on host 17875.```

**Comment by jeromelaban** [comment]
It looks like omnisharp can't find the files from the template for some reason. Do the files mentioned actually exist?

**Comment by GabrielChouinardLetourneau** [comment]
Yes they are exisiting, could it be related to the naming of the project? I will try creating another project with a name without hyphen/-.

**Comment by GabrielChouinardLetourneau** [comment]
@jeromelaban It was indeed related to the naming of the app itself, I tried using the `MyApp` that is in the documentation, I was able to debug and deploy on my physical Android device

**Comment by jeromelaban** [comment]
Could it be that you used a space in the name of the project?

**Comment by jeromelaban** [comment]
Great! Thanks. We haven't found way to prevent this from the command line at this time. Let's keep track in https://github.com/unoplatform/uno.templates/issues/94

**Comment by GabrielChouinardLetourneau** [comment]
Thank you for your time as well!
