### ISSUE TITLE
[Image][Wasm][Regression]  Stretch="Uniform" does not work as intended

### ISSUE THREAD

**Issue by Robert-Louis** [unoplatform/uno#13905]
### Current behavior

In canary Playground we can see that Image Stretch="Uniform"  does not behave as intended

https://playgroundcanary.z19.web.core.windows.net/#6c7b7eb2

### Expected behavior

Working on current Playground 

https://playground.platform.uno/#6c7b7eb2

### How to reproduce it (as minimally and precisely as possible)

https://playground.platform.uno/#6c7b7eb2

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by Youssef1313** [comment]
@Robert-Louis That is not a regression. It's actually a bug fix.

Following shows the result on WinUI.

![image](https://github.com/unoplatform/uno/assets/31348972/550a4657-e6aa-4600-b295-b0e2b388c9b3)
