### ISSUE TITLE
[ElevatedView][WASM] Strange behavior with ElevatedView Border

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno#13904]
### Current behavior

Some controls using ElevatedView like Chips have a strange border, looks like it's duplicated somehow. I'm guessing it's related to [this change in ElevatedView](https://github.com/unoplatform/uno/commit/17282ef74cdf2149a45c5855efb1fcf6608f4fa2#diff-19b9e2d9bd6dbd4102198c213f43066c721cf44996f7a19705bb43219f90e378). The issue is WASM specific and is reproducible by updating Uno packages to latest.

![image](https://github.com/unoplatform/uno/assets/114886335/5f24bcc6-5316-45c3-80bf-eade69ad4f98)

This is affecting the Figma Plugin and Gallery.

Related to https://github.com/unoplatform/Uno.Themes/issues/1229

### How to reproduce it (as minimally and precisely as possible)

Repro:
[ChipsElevatedView-Repro.zip](https://github.com/unoplatform/uno/files/12820553/ChipsElevatedView-Repro.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

We fist noticed the issue in **Uno 5.0.0-dev.3361**. 

But it's present in latest **Uno 5.0.0-dev.3369** packages.

### Affected platforms

WebAssembly

### Anything else we need to know?

Not sure if this is useful, but if I inspect the page and find the ElevatedView element in HTML and change its border-width to 0px I have the right border. So the border would be duplicated?

![image](https://github.com/unoplatform/uno/assets/114886335/0caf863a-da3d-4584-9b23-ca54f1d80a17)

**Comment by agneszitte** [comment]
Related issue: https://github.com/unoplatform/Uno.Themes/issues/1229

**Comment by weitzhandler** [comment]
Here's a comparison

Figma plugin:

![image](https://github.com/unoplatform/uno/assets/2716316/8b8cb65f-d2b1-4ab6-8d80-587362f41254)

Android:

![image](https://github.com/unoplatform/uno/assets/2716316/66a09962-19d6-45b4-84b3-80a487fd46e6)

**Comment by Youssef1313** [comment]
@weitzhandler This issue was specifically for Wasm. Can you open a new issue for the Android behavior?

**Comment by weitzhandler** [comment]
Might need to open a new Adnroid-specific issue, but for the time being I'm reopening this one.

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/issues/14094
