### ISSUE TITLE
WPF set PointerCursor is not working

### ISSUE THREAD

**Issue by lld1995** [unoplatform/uno#13950]
### Current behavior

Button is always arrow

### Expected behavior

Button change to my set

### How to reproduce it (as minimally and precisely as possible)

Just create a new uno project

```csharp
using Windows.UI.Core;

namespace UnoApp3
{
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
            CoreWindow.GetForCurrentThread().PointerCursor = new CoreCursor(CoreCursorType.Wait, 0);
        }
    }
}
```

### Works on UWP/WinUI

None

### NuGet package version(s)

Uno.WinUI version is 4.10.26

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

**Comment by Youssef1313** [comment]
Support for this was supposed to be added in https://github.com/unoplatform/uno/pull/4079.

**Comment by lld1995** [comment]
> Support for this was supposed to be added in #4079.

but this version is not working

**Comment by Youssef1313** [comment]
Yeah, sorry if my comment is confusing. It's meant as a quick starting point of investigating the issue.

**Comment by lld1995** [comment]
i fount out that 4.9 D:\opensource\uno\src\Uno.UWP\UI\Core\CoreWindow.skia.cs has method
`public CoreCursor PointerCursor
{
	get => _coreWindowExtension?.PointerCursor ?? new CoreCursor(CoreCursorType.Arrow, 0);
	set
	{
		if (_coreWindowExtension != null)
		{
			_coreWindowExtension.PointerCursor = value;
		}
	}
}`

but version 4.10 ,the method was missed

**Comment by Youssef1313** [comment]
@lld1995 It just moved to another file: [CoreWindow.Pointers.Managed.cs](https://github.com/unoplatform/uno/blob/master/src/Uno.UWP/UI/Core/CoreWindow.Pointers.Managed.cs). So not really missing.

**Comment by lld1995** [comment]
> @lld1995 It just moved to another file: [CoreWindow.Pointers.Managed.cs](https://github.com/unoplatform/uno/blob/master/src/Uno.UWP/UI/Core/CoreWindow.Pointers.Managed.cs). So not really missing.

oh, but it use IUnoCorePointerInputSource? _pointerSource, WpfCorePointerInputSource property PointerCursor is not NotImplemented. please fixed it

**Comment by lld1995** [comment]
And i guess gtk or other platforms also have kind of problem.

**Comment by lld1995** [comment]
> I tested on Gtk and it's working as expected. This is Wpf only which I'm fixing in #13959. Thanks for reporting this @lld1995 !

ok,thanks!

**Comment by Youssef1313** [comment]
Let's keep it open until my PR is merged
