### ISSUE TITLE
[WASM] `TextWrapping` doesn't work properly in Safari

### ISSUE THREAD

**Issue by TopProgrammer77** [unoplatform/uno#13957]
### Current behavior

I attached the example. 
[1.zip](https://github.com/unoplatform/uno/files/12874716/1.zip)
[2.zip](https://github.com/unoplatform/uno/files/12880793/2.zip)

Here, I used 
```
TextBlock.TextWrapping="NoWrap"
TextBlock.TextTrimming="CharacterEllipsis" 
```

On Safari browser v17
![image](https://github.com/unoplatform/uno/assets/122166904/81198431-45fa-4a1c-ad6d-c5021ec469b6)

As you can see in the picture, the height of textblock is wrong.
This works on Chrome and other browser, even also old version of Safari.
But this doesn't work properly only on Safari 17.

### Expected behavior

On UWP,

![image](https://github.com/unoplatform/uno/assets/122166904/891ce272-8f5b-4a1c-83e4-2be1e80d98fa)

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
May be related to https://github.com/unoplatform/uno/issues/7974

**Comment by DierkDroth** [comment]
@jeromelaban FYI
The issue @TopProgrammer77 reported is on Safari only. The same UNO WASM code (and HTML) does not exhibit that problem on Chrome.
And in fact the case here is 'no wrap' + 'trimming' (please see [your comment here](https://github.com/unoplatform/uno/issues/7974#issuecomment-1028106831))

**Comment by TopProgrammer77** [comment]
@jeromelaban 
I realized that this is only TextWrapping issue, not related to TextTrimming.
You can check here https://github.com/unoplatform/uno/files/12880793/2.zip
Here, I removed the TextTrimming and only used TextWrapping but same issue was occured.
I attached the video.

- On Chrome
![Chrome(1)](https://github.com/unoplatform/uno/assets/122166904/0f96856d-cbc4-44c7-9dde-19681874f950)

- On Safari
![Safari(1)](https://github.com/unoplatform/uno/assets/122166904/bf509004-ea1a-4e5b-b3ff-8a906709f3c3)

**Comment by TopProgrammer77** [comment]
> May be related to #7974

In the example of #7974 , When I removed the TextTrimming, The behavior of WASM is same with UWP

**Comment by DierkDroth** [comment]
@jeromelaban thanks. You made my day! 

I'll run some tests as a new build is available.
