### ISSUE TITLE
[iOS] x:Load Z-Order is incorrect

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#13966]
A user has reported that using `x:Load` on UI elements on iOS can be swapped in the tree to an incorrect Z order.

## Affected version

5.0.0-dev.3447

**Comment by jeromelaban** [comment]
@jsinsel could you provide a similar looking XAML structure where the `x:Load`-marked item is located? Thanks!

**Comment by jsinsel** [comment]
`<Grid>
    <Border />
    <Border  x:Load... />
    <Border  x:Load... />
 </Grid>
    `
    
    Something like this causes the issue.  I can try a repro if desired.
