### ISSUE TITLE
Add multi-`XamlRoot` support for drag and drop

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#13982]
### What would you like to be added

Currently drag and drop is allowed only within the initial `Window`.

### Why is this needed

We should support drag and drop across `XamlRoot` boundaries

### For which platform

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer)

**Comment by agneszitte** [comment]
@MartinZikmund could this be related to the multi-window work?

**Comment by MartinZikmund** [comment]
@agneszitte missed this one, it is, but it is not done yet afaik, as it still has several rooted dependencies. Will need to investigate.
