### ISSUE TITLE
PathGeometry not working WASM

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#1399]
## Current behavior

PathGeometry objects do not render for WASM

## Expected behavior

PathGeometry objects should render.

## How to reproduce it (as minimally and precisely as possible)

Open + run the attached project.  In UWP the geometry renders properly, in WASM the PathGeometry objects are empty.

[PathGeometryTest.zip](https://github.com/unoplatform/uno/files/3516477/PathGeometryTest.zip)

## Environment

Nuget Package:
Uno.Core

Package Version(s):
1.29.0-dev.93

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
It has been implemented in https://github.com/unoplatform/uno/pull/1919
I'll close this issue.
