### ISSUE TITLE
WASM Platform must not target netstandard2.0

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#14]
The current WebAssembly target is currently using netstandard 2.0 for deployment.

This is fine for now as Uno does not support .NET Standard 2.0 as a platform target, so wasm specific code is using NETSTANDARD2_0 to target it.

This should be addressed somehow by https://github.com/NuGet/NuGet.Client/pull/2159.  

Update: https://github.com/NuGet/Home/issues/8186

**Comment by weitzhandler** [comment]
Is this why Prism and other libraries can't be added to the .NET Standard project?

**Comment by jeromelaban** [comment]
This is the main reason, yes. Many libraries do have an actual .NET Standard 2.0 target, and making it an alias of WebAssembly is a recipe for confusing users.

That being said, it's possible to make Uno specific packages but the ultimate goal would be to have only one package for Prism.Windows, for instance.

**Comment by weitzhandler** [comment]
Do you mean Prism.Windows, or Uno.Prism.Windows, the general one or a dedicated one? Obviously the general one is what would be best for everybody.

**Comment by weitzhandler** [comment]
[Related](https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md).

**Comment by jeromelaban** [comment]
This issue is no longer relevant, as `netstandard2.0` is now a generic platform, used by WebAssembly and Skia.
