### ISSUE TITLE
[WASM] FolderPicker not working on Firefox

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#14006]
### Current behavior

Appears FolderPicker is not working on FireFox: the Windows UI to pick a fodler is not shown. No problem using Chrome though.
Here is a repo:
[FolderPicker.zip](https://github.com/unoplatform/uno/files/12999633/FolderPicker.zip)

And here is a [link ](https://resources-dev.unusual-suite.com/test/FolderPicker/publish) to test.

This is latest UNO and latest Firefox on latest Windows 11.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by MartinZikmund** [comment]
This is unfortunately not possible on Firefox so far, as the browser did not implement support for the File System Access API yet - [see here](https://caniuse.com/?search=showDirectoryPicker). However, you can check if the support is available at runtime and if it is not available, you can still inform the user that the feature requires a different browser for example - see [our docs](https://platform.uno/docs/articles/features/windows-storage-pickers.html#checking-whether-file-system-access-api-is-supported).

**Comment by DierkDroth** [comment]
@MartinZikmund thanks for your feedback. That helps me to add a few checks + user info.

What would be the equivalent features to `showDirectoryPicker `to check for `FileSavePicker `and `FileOpenPicker` in [your link above](https://caniuse.com/?search=showDirectoryPicker)?

**Comment by MartinZikmund** [comment]
@DierkDroth that's in the linked docs: `FileSystemAccessApiInformation.IsFolderPickerSupported` at runtime checks for this
