### ISSUE TITLE
Button does not not support CornerRadius

### ISSUE THREAD

**Issue by pdecostervgls** [unoplatform/uno#1401]
## Current behavior

```
<Button CornerRadius="12" Background="Red">
    <TextBlock>Button Element with CornerRadius</TextBlock>
</Button>
```
The above snippet doesn't work on Target versions before 1809. After 1809 it doesn't represent a rounded button on iOS and Android.

## Expected behavior

Represents a rounded button

## How to reproduce it (as minimally and precisely as possible)

```
<Button CornerRadius="12" Background="Red">
    <TextBlock>Button Element with CornerRadius</TextBlock>
</Button>
```

## Environment

Nuget Package:
* Uno.UI: 1.46.196-dev.2429

Affected platform(s):
- [x] iOS
- [ ] Android
- [x] WebAssembly (Probably, Didn't test)
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.1.6)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?

As stated before, this feature is only supported on UWP from version 1809 onwards.

**Comment by pdecostervgls** [comment]
I'll have to revisit this issue, since I currently have an app on Android which does have rounded buttons.

**Comment by carldebilly** [comment]
Should be fixed with https://github.com/unoplatform/uno/issues/1074
