### ISSUE TITLE
`MediaPlayerElement` speed selector doesn't work correctly

### ISSUE THREAD

**Issue by iurycarlos** [unoplatform/uno#14012]
### Current behavior

Using https://playgroundcanary.z19.web.core.windows.net/#d6d823b1
If we select any speed greater than 1x it will work.
However, if we select a smaller than 1 x it will not affect the playback. 

Then, if we change from 0,25 to 0,5, for exemple, it will accelerate the speed, probably it is multiplying for (0,5 / 0,25).

### Expected behavior

Playback speed should work correctly

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
Thanks, let's code then!
