### ISSUE TITLE
SwipeControl is not implemented in Uno

### ISSUE THREAD

**Issue by pdecostervgls** [unoplatform/uno#1402]
## Current behavior

SwipeControl is not implemented in Uno.

## Expected behavior

SwipeControl is implemented in Uno.

## Environment

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

**Comment by ghuntley** [comment]
:wave: The path forward here involves porting the WinUI control from C++ to C#. The source for SwipeControl is available at https://github.com/microsoft/microsoft-ui-xaml/tree/master/dev/SwipeControl and it can be incorporated into Uno as it is licensed under MIT. 

The process is quite manual at the moment and folks have been investigating how to make it less so via https://github.com/xoofx/CppAst. Anyway here's some of my personal notes from going through the process myself. I hope they help - the intention is to turn them into contributing to Uno documentation in the future.

## what's involved

1. Create a folder under `Uno.UI.UI.Xaml.Controls.[ControlName]`
1. Progressively turn the `Uno.UI/Generated/3.0.0.0` [implementation](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/SwipeControl.cs) into an empty class.
5. Progressively turn `Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Automation.Peers` into an empty class. Destination for implementation is `Uno.UI.UI.Xaml.Automation\Peers`

## reference example

https://github.com/unoplatform/uno/pull/1033/files

## guidelines

When porting from C++ to C#, stay with C++ idioms. Don't refactor and make the code feel like .NET. A developer should be able to eyeball the .NET implementation, compare against the WinUI C++ implementation and be able to incorporate bug-fixes or features by eyeballing the WinUI source code.

It's really important to include the WinUI gitsha in the initial commit message ie "this is the SwipeControl from winui master at gitSha". 

## notes

- .idl contains the dependency properties
- .h contains the header definition.
- .cpp contains the meat and veggies
- .xaml contains the visual definitions.

### find and replace

The first pass of porting a control involves doing a bunch of find and replace operations, here's the common ones:

Properties, members and events:

```    
"global::Windows.UI.Xaml.DependencyProperty" -> "DependencyProperty"
"global::Windows.UI.Xaml.Controls." -> ""
"global::Windows.Foundation.Metadata.ApiInformation" -> "ApiInformation"
```

Control:

```
"SetDefaultStyleKey(this);" -> "DefaultStyleKey = GetType();"
"__RP_Marker_ClassById(RuntimeProfiler::ProfId_RatingControl);" -> ""
"std::min" -> "Math.Min"
"std::max" -> "Math.Max"
"winrt::unbox_value<int>" -> "(int)"
"winrt::unbox_value<string>" -> "(string)"
"winrt::unbox_value<float>" -> "(float)"
"winrt::unbox_value<double>" -> "(double)"
"(ItemInfo().try_as<winrt::RatingItemFontInfo>())" -> "(ItemInfo is RatingItemFontInfo)"

"m_dispatcherHelper.RunAsync(" -> "Dispatcher.RunAsync("
```

### eventhandlers

**convention**

Add them in `MyCoolControl.Events.cs`

**disposal**

Add eventhandlers to Serial (if order matters) or Composite (if you need a bucket) disposables and then dispose the disposable. 

### default values

Keep an eye out for the default values and ensure the csharp codegen impl matches, it should but check.

```
String Caption { get; set; };
[MUX_DEFAULT_VALUE("1")]
Int32 InitialSetValue { get; set; };
[MUX_DEFAULT_VALUE("true")]
Boolean IsClearEnabled { get; set; };
Boolean IsReadOnly { get; set; };
[MUX_DEFAULT_VALUE("5")]
Int32 MaxRating { get; set; };
[MUX_DEFAULT_VALUE("-1")]
Double PlaceholderValue { get; set; };
RatingItemInfo ItemInfo { get; set; };
[MUX_DEFAULT_VALUE("-1")]
Double Value { get; set; };
```

ie

```
public static DependencyProperty InitialSetValueProperty { get; } =
    DependencyProperty.Register(
        "InitialSetValue", typeof(int),
        typeof(RatingControl),
        new FrameworkPropertyMetadata(<<< DEFAULT VALUE HERE >>>, OnStaticPropertyChanged));
```

### dependency properties

Defined in the controls interface definition (`MyCoolControl.IDL`)

### tracker_ref

When porting, the only ref that should stay is weak ref. Microsoft's ref counting implementation is at https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/inc/tracker_ref.h

Typically you can change:

`tracker_ref<winrt::TextBlock> m_captionTextBlock{ this };`

To:

`private TextBlock m_captionTextBlock;`

**Comment by pdecostervgls** [comment]
Wow, That is indeed a lot of work. Thanks for writing out your thoughts and observations. They'll come in handy.

**Comment by davidjohnoliver** [comment]
This will be a tricky one as it's using [VisualInteractionSource](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.interactions.visualinteractionsource) which is not implemented in Uno yet. Currently Manipulation events aren't implemented either (#221).

**Comment by ghuntley** [comment]
howdy @pdecostervgls, been doing some splunking and it turns out nventive has a conceptually similar control to SwipeControl which uses platform-specific manipulation code. It's ios/android only and what we use internally while manipulation or gestures aren't implemented. Here's the code, it's released under MIT - https://gist.github.com/ghuntley/4f31a4cf55426b545ce630d3f52fabbc

**Comment by DierkDroth** [comment]
@jeromelaban what are nventive's plans to support SwipeControl/SwipeItem for iOS and Android?

Posts above suggest there would be an alternate solution for iOS and Android? Is that solution recommendable at this point?

**Comment by jeromelaban** [comment]
@DierkDroth this control has not been prioritized above what's been published to this thread. The original control uses some features that not yet available in Uno. We'll be able to port it once those are implemented.

**Comment by DierkDroth** [comment]
Thanks for your feedback, @jeromelaban

**Comment by pdecostervgls** [comment]
> howdy @pdecostervgls, been doing some splunking and it turns out nventive has a conceptually similar control to SwipeControl which uses platform-specific manipulation code. It's ios/android only and what we use internally while manipulation or gestures aren't implemented. Here's the code, it's released under MIT - https://gist.github.com/ghuntley/4f31a4cf55426b545ce630d3f52fabbc
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0aeb324a3445c618a67c0140da8216d28af304fa/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f67697374732f676973742d6f672d696d6167652e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> Gist**[code released under MIT](https://gist.github.com/ghuntley/4f31a4cf55426b545ce630d3f52fabbc)**code released under MIT. GitHub Gist: instantly share code, notes, and snippets.

@ghuntley @jeromelaban I just got to attempting to work with this, I noticed that there is no `SwipeControl` class in your gist, do you have any guidance on how to use this on the XAML side?

**Comment by dr1rrb** [comment]
This is now implemented https://github.com/unoplatform/uno/pull/5700 🎉
