### ISSUE TITLE
[Perf] [XamlGenerator] Extract `Split` parameter into a static array

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#14021]
### Current behavior

https://github.com/unoplatform/uno/blob/54b5f499474079519c26b3268a921c9b58b00ad2/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileParser.cs#L195

![image](https://github.com/unoplatform/uno/assets/31348972/1a0ce75d-4142-41df-8778-e74617a94cb4)

### Expected behavior

This char array should be allocated only once.

It's not very significant, but good to fix.

### Works on UWP/WinUI

None

**Comment by Sweetdevil144** [comment]
Hey @Youssef1313 , I would like to work on it

**Comment by Youssef1313** [comment]
Sure!! You can go ahead!

**Comment by Sweetdevil144** [comment]
Thanks. Get you give me a brief of this issue along with it's significance.

**Comment by Sweetdevil144** [comment]
@Youssef1313 Created a PR for the same !!
Can you check it out and report ANY errors if any?!
🙂
