### ISSUE TITLE
`ResourceDictionary` x `KeyValuePair` convert code generation 

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno#14025]
### Current behavior

Works fine on UWP, but in other platforms (even WinUI) I'm getting a code generation error when trying to use a `<ResourceDictionary>` in a Dependency Property:

```
>C:\UnoPlatform\Uno.Themes\src\samples\UWP\Uno.Themes.Samples.Skia.Gtk\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\ButtonSamplePage_ffaf46608a7221259020a046294eeefc.cs(133,37,149,11): error CS1503: Argument 1: cannot convert from 'Windows.UI.Xaml.ResourceDictionary' to 'System.Collections.Generic.KeyValuePair<object, object>'
````

DP
```
public static DependencyProperty ColorPaletteProperty { [DynamicDependency(nameof(GetColorPalette))] get; } = DependencyProperty.RegisterAttached(
    "ColorPalette",
    typeof(ResourceDictionary),
    typeof(ThemeExtensions),
    new PropertyMetadata(default, OnColorPaletteChanged));
```
XAML
```
<Button Content="Outlined"
        Style="{StaticResource MaterialFilledButtonStyle}">
    <um:ThemeExtensions.ColorPalette>
        <ResourceDictionary>
            <Color x:Key="PrimaryColor">Yellow</Color>
            <Color x:Key="OnPrimaryBrush">Green</Color>
        </ResourceDictionary>
    </um:ThemeExtensions.ColorPalette>
</Button>
```

### How to reproduce it (as minimally and precisely as possible)

Here's a dummy repro:
[ResourceDict-Repro.zip](https://github.com/unoplatform/uno/files/13044554/ResourceDict-Repro.zip)

### Works on UWP/WinUI

Yes

**Comment by Youssef1313** [comment]
> Works fine on UWP, but in other platforms (even WinUI) I'm getting a code generation

@jeromelaban From the description it seems it's supported in UWP but not WinUI. We can't control what happens on WinUI anyway. So do we need to do anything here at all?

**Comment by eriklimakc** [comment]
I mean, you get the same error in a Uno App running on Windows (WinUI), the error is still in `Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator ...`

 But you are able to do that in a WinUI App like:
 
[WinUI.zip](https://github.com/unoplatform/uno/files/13046077/WinUI.zip)

 cc @Youssef1313

**Comment by jeromelaban** [comment]
If it's not supported by WinUI, we can close. @eriklimakc @kazo0 do we need to track something here in toolkit for the scenario you were trying to reach?

**Comment by Youssef1313** [comment]
@jeromelaban I confirmed it's supported by WinUI.
