### ISSUE TITLE
famous "Type Page was Not Found" Issue!

### ISSUE THREAD

**Issue by aliajboy** [unoplatform/uno#14058]
### Current behavior

I have This Issue on .Net 7 and Nothing Helps. 
Here, See for your selves:
![Untitled](https://github.com/unoplatform/uno/assets/73298440/812613ae-507c-447c-8f90-6f9c37ca65c0)

It doesn't matter what I select in Dropdown, It always Shows Error. 

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows), Windows

### IDE

Visual Studio 2022

### IDE version

17.7.5

**Comment by aliajboy** [comment]
surprisingly I just update uno.check and run it again, Then reboot and everything is ok now!

**Comment by jeromelaban** [comment]
Thanks for the update. We're also awaiting for an update in Visual Studio which will fix most of this issue very soon.
