### ISSUE TITLE
Unthemed custom colors not rendering as ThemeResource, only static 

### ISSUE THREAD

**Issue by iurycarlos** [unoplatform/uno#14088]
### Current behavior

Custom unthemed colors (generated by the Figma Plugin, for example) are not being rendered if they are ThemeResource instead Static.

Is that an expected behaviour? Should they be always static?

 
  <Color x:Key="MyCustomFirstColor">#B910A8</Color>
  
  <SolidColorBrush x:Key="CustomSecondBrush" Color="{ThemeResource CustomSecondColor}" />
  <SolidColorBrush x:Key="MyCustomFirstBrush" Color="{ThemeResource MyCustomFirstColor}" />

Color only renders if we replace the last line by:

  <SolidColorBrush x:Key="MyCustomFirstBrush" Color="{StaticResource MyCustomFirstColor}" />

In fact, at https://learn.microsoft.com/en-us/windows/apps/design/style/xaml-theme-resources
![image](https://github.com/unoplatform/uno/assets/6876973/c3afaa31-7d8f-4a73-bc92-51b358df0381)

It says we can't use ThemeResources inside Themed Dictionaries, but it doesn't seem the case.

### Expected behavior

Should render as Theme or StaticResource

### How to reproduce it (as minimally and precisely as possible)

To reproduce the error, just create a new app, go to the ColorPaletteOverride and change it accordingly the sample code.
Use the color in any control.

### Works on UWP/WinUI

None

**Comment by kazo0** [comment]
@iurycarlos can you show me the xaml for what you are trying to do, I'm not sure I follow

**Comment by kazo0** [comment]
@iurycarlos is it rendering on a window sapp?

**Comment by iurycarlos** [comment]
It is the default code generate by Plugin.
I think there's a discussion about it in our private chat.

![image](https://github.com/unoplatform/uno/assets/6876973/921cb61e-e414-45bc-a575-ed04ab4b7adb)

I didn't tested it recently in new template versions. I will check it.

**Comment by iurycarlos** [comment]
For some reason, it is failing also for line 73, as well. The CustomSecondBrush must use Static instead ThemeResource to work.

**Comment by jeromelaban** [comment]
@iurycarlos can you create a small repro for this? It will be easier to understand what's missing.
