### ISSUE TITLE
Throw the full exception when page navigation fails

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1409]
## What would you like to be added:

When navigation to a page fails (`OnNavigationFailed`) an exception is thrown with the name of the page that failed to load. The actual reason why the exception is thrown is swallowed. This behavior hides root causes and makes troubleshooting new applications harder, especially on the WebAssembly head - so let's fix it.

![image](https://user-images.githubusercontent.com/127353/63545048-dc505180-c569-11e9-8fea-ebd608bf9e2a.png)

https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs#L90

Instead of:

```csharp
throw new Exception("Failed to load Page " + e.SourcePageType.FullName);
```

Change it to something like:

```csharp
throw new Exception($"Failed to load {e.SourcePageType.FullName}: {e.Exception}");
```

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [x] Solution Templates

## Anything else we need to know?

Going to leave this as a `help wanted` and `good first issue`. Hopefully someone (you?) comes along and helps out 👍

**Comment by TopperDEL** [comment]
I did it - was very simple, though I needed some time to figure out how to do the PR.

**Comment by ghuntley** [comment]
Fixed by https://github.com/unoplatform/uno/pull/1413
