### ISSUE TITLE
[TextBox][Android] OnEditorAction raises KeyUp twice

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#14106]
### Current behavior

https://github.com/unoplatform/uno/blob/69abdbfa4bcd5ad488ac5278cc45c43368422f5d/src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs#L558-L559

### Expected behavior

I think first one should be KeyDownEvent

### Works on UWP/WinUI

None

**Comment by MartinZikmund** [comment]
It was a copy-paste mistake, intention was to trigger down and up after, because previously the code just triggered up, which was inconsistent
