### ISSUE TITLE
Exceptions while changing cursor color in Android P

### ISSUE THREAD

**Issue by artemious7** [unoplatform/uno#1411]
## Current behavior
When run on Android P it will throw a few exceptions, because there's no such field as "mCursorDrawable".
It throws java.lang.NoSuchFieldException and then NullReferenceException's (when we enable to stop the debugger on every C# exception in Visual Studio, not only uncaught ones) and when the element gets unloaded (for example, the page is navigated from) it throws NullReferenceException's and doesn't handle it, so the app crashes.

## Expected behavior
It should not throw, and the feature should work in Android P now.

The change is based on 
https://stackoverflow.com/a/52564925

## How to reproduce it (as minimally and precisely as possible)
I didn't have time to make a repro :-( sorry

## Environment

Nuget Package:
Uno.UI
Package Version(s):
v1.45.0

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?
Pull request: https://github.com/unoplatform/uno/pull/1392

**Comment by Youssef1313** [comment]
This was supposed to be fixed in https://github.com/unoplatform/uno/pull/1392.

@jeromelaban Should this get closed?
