### ISSUE TITLE
WUX NavigationView should not be included in WinUI build

### ISSUE THREAD

**Issue by dansiegel** [unoplatform/uno#14123]
### Current behavior

NavigationView and related types are currently in the Windows.UI.Xaml.Controls namespace in the Uno.WinUI assembly.
![image](https://github.com/unoplatform/uno/assets/3860573/c9642870-7dce-4a6b-9b26-540813fb9cff)

![image](https://github.com/unoplatform/uno/assets/3860573/81b8ebe5-4231-4768-a86f-44044d8421e8)

### Expected behavior

NavigationView and associated types should be in the Microsoft.UI.Xaml.Controls namespace the same as they are in WinUI

![image](https://github.com/unoplatform/uno/assets/3860573/ea4a8b38-c223-4cc5-bb3b-db9e3cd7a29c)

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.0

### Affected platforms

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer)

### IDE

Visual Studio 2022

**Comment by Youssef1313** [comment]
@jeromelaban Will we want to take this breaking change for Uno 5?

**Comment by jeromelaban** [comment]
@Youssef1313 yes, that would make sense.
