### ISSUE TITLE
Docs CI shouldn't need to run "Setup" stage

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#14140]
### What would you like to be added

I don't think docs CI needs to run this stage nor gitversion. This change would save 3 minutes:

![image](https://github.com/unoplatform/uno/assets/31348972/36b8eeca-b3b9-413a-b589-d5762645ca5e)

### Why is this needed

Faster CI

### For which platform

N/A

**Comment by jeromelaban** [comment]
It does, because it validates pieces that are not validated when only docs are changed.
