### ISSUE TITLE
Strict type resolution fails when namespace is not on the top-level element

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#14161]
### Current behavior

The following xaml fails when `UnoEnableXamlFuzzyMatching` is set to false:

```xml
      <embed:MauiHost x:Name="MauiHostElement"
              xmlns:embed="using:Uno.Extensions.Maui"
              xmlns:controls="using:Uno5TestMauiEmbed01.MauiControls"
              Source="controls:EmbeddedControl" />
```

`embed:MauiHost` is considered as not available when building.

### Expected behavior

The compilation succeeds,

### Workaround

Move the namespace `controls` definition on the root element of the file.

### Works on UWP/WinUI

None

### NuGet package version(s)

5.0-dev

**Comment by Youssef1313** [comment]
In general, the generator is able to figure out the namespace when it's not in top-level element.

The following test is passing:

```csharp
	[TestMethod]
	public async Task When_Namespace_Is_On_Nested_Element()
	{
		var xamlFiles = new[]
		{
			new XamlFile(
				"MainPage.xaml",
				"""
				<Page x:Class="TestRepro.MainPage"
					  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
					  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
					  xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006">

					<Grid>

						<local:MyStackPanel xmlns:local="using:TestRepro" />

					</Grid>
				</Page>
				"""),
		};

		var test = new Verify.Test(xamlFiles)
		{
			TestState =
			{
				Sources =
				{
					"""
					using Windows.UI.Xaml.Controls;

					namespace TestRepro
					{

						public sealed partial class MyStackPanel : StackPanel { }

						public sealed partial class MainPage : Page
						{
							public MainPage()
							{
								this.InitializeComponent();
							}
						}
					}
					"""
				}
			}
		}.AddGeneratedSources();

		await test.RunAsync();
	}
```

So it's looking like there is something very specific going on here.

**Comment by Youssef1313** [comment]
@jeromelaban 

https://github.com/unoplatform/uno/blob/16f9aa9c02070a404be8f73be198f0a0dc24880b/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs#L551-L561

We are calling `GetType("controls:EmbeddedControl")`, which has absolutely no context about the surrounding XAML and we use `_fileDefinition.Namespaces` for resolution in this code path.

Looking closer, I think we will need to find a way to store namespaces as we encounter them here:

https://github.com/unoplatform/uno/blob/16f9aa9c02070a404be8f73be198f0a0dc24880b/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileParser.cs#L375-L379
