### ISSUE TITLE
Skia build fails with `The "RuntimeAssetsSelectorTask_v0" task was not found`

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#14189]
### Current behavior

```
44>C:\Users\PC\Desktop\uno\build\nuget\uno.winui.runtime-replace.targets(50,3): error MSB4036: The "RuntimeAssetsSelectorTask_v0" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64" directory.
44>Done building project "UnoIslands.Skia.Wpf.csproj" -- FAILED.
```

This is likely related to https://github.com/unoplatform/uno/pull/14122

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
I had to change the build sequence, it seems to be causing issues in the build odering with Uno.UI.Tasks. If you build Uno.UI.Tasks first, it should work properly. We'll need to adjust that soon, still.

**Comment by jeromelaban** [comment]
You may need to close VS first (so all msbuild instances get closed) the build the uno.ui.tasks first after opening VS.

Overall, I wonder if there's an issue with design-time builds. The problem may be that msbuild caches resolution failure per msbuild process, then never reevaluates it.

**Comment by limeniye** [comment]
>You may need to close VS first (so all msbuild instances get closed) the build the uno.ui.tasks first after opening VS.
I've tried the following steps:
- I cloned uno repo
- I changed **UnoTargetFrameworkOverride** and global.json to net 8.0

After, I opened new solution without some cash.
Without build anything I already see this problem:
![image](https://github.com/unoplatform/uno/assets/69314237/4dac1358-e05b-4307-8f6d-ce5bd0646c71)

After that I did the same as in the [last reply](https://github.com/unoplatform/uno/issues/14189#issuecomment-1827407574).
And result is the same.

**Comment by Youssef1313** [comment]
@limeniye Can you please test with PR #14585?

**Comment by limeniye** [comment]
```
git clone --branch Youssef1313/fix-build-skia https://github.com/unoplatform/uno
```
All is the same.

**Comment by Youssef1313** [comment]
@limeniye Maybe a similar change is needed for a project different than UnoIslands.Skia.Wpf? Can you please clarify which project exactly fails to build with this PR?

**Comment by limeniye** [comment]
@Youssef1313, That's was for **SamplesApp.Skia.Wpf** & **UnoIslands.Skia.Wpf**.
But that's quite interesting.

I closed changes from your branch and opened **master** in another solution.

Without your changes I have the following errors stack for **UnoIslands.Skia.Wpf**:

![image](https://github.com/unoplatform/uno/assets/69314237/98d413a0-9cbf-4b8f-a29e-3e96af5aaa24)

```
30>R:\limeniye_uno_latest\build\nuget\uno.winui.runtime-replace.targets(50,3): error MSB4036: The "RuntimeAssetsSelectorTask_v0" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64" directory.
30>Done building project "UnoIslands.Skia.Wpf.csproj" -- FAILED.
30>R:\limeniye_uno_latest\build\nuget\uno.winui.runtime-replace.targets(50,3): error MSB4036: The "RuntimeAssetsSelectorTask_v0" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64" directory.
30>Done building project "UnoIslands.Skia.Wpf.csproj" -- FAILED.
```

But, after that I closed VS with the master branch and opened solution with your branch again and this errors was disappeared.

**Comment by Youssef1313** [comment]
Probably some VS caching issues that got invalidated in between somehow.

If you encountered this again, let us know please.

In case that happened, the first thing I would do is to check which project that fails and do a similar change as #14585 in that specific project. If the project already references Uno.UI.Tasks properly, then getting us a binlog will be of much help.

**Comment by limeniye** [comment]
@Youssef1313 , thanks!
Btw, I copy-pasted your changes to the **SamplesApp.Skia.Wpf** and that's fixed this https://github.com/unoplatform/uno/discussions/14569 problem

**Comment by limeniye** [comment]
If I rebuild the **UnoIslands.Skia** the problem is appear again. But if I rebuild the **UnoIslands.Skia.Wpf** the problem is disappear. 
I have moved the code by @Youssef1313 to the **UnoIslands.Skia**. And now **UnoIslands.Skia** rebuilds well, but **UnoIslands.Skia.Wpf** is not. It looks like this code should be both in **UnoIslands.Skia** and **UnoIslands.Skia.Wpf**

With the **SamplesApp.Skia** it doesn't works the same. After the add this code-lines to the **SamplesApp.Skia** the **SamplesApp.Skia.Wpf** is fixing automaticly.

I have create the draft for fix **SamplesApp.Skia.Wpf** https://github.com/unoplatform/uno/pull/14592
