### ISSUE TITLE
JumpList crashes on Android if it contains an item with null Description

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1418]
## Current behavior

If `Description` is not filled out on any item, trying to call `JumpList.LoadCurrentAsync`  causes a `ArgumentNullException`

## Expected behavior

Should not crash.

## How to reproduce it (as minimally and precisely as possible)

- Create `JumpListItem` and leave `Description` empty (do not set it).
Restart app and call `JumpList.LoadCurrentAsync` - app will crash.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
My bad, I will tackle this.

**Comment by HanamiM** [comment]
Martin told me I should try this :-)
