### ISSUE TITLE
Make Uno.[Win]UI.<Lottie|DevServer> packages to work also on windows

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#14196]
### What would you like to be added

We should add a `_._` file and remove all dependencies on windows target.

### Why is this needed

Adding a reference to this packages in the core "library project" (from our app template) will break the windows build. Reference has to be conditional to NOT windows.

### Anything else we need to know?

Even if our app template does include those reference conditionally to NOT windows, any dev that would add those references later in their app development (or while updating an exciting project) will encounter some weird build error:

### Lottie
The windows head project build will fail with 
```
1>MyApp.Windows.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null.'
1>C:\Users\David\.nuget\packages\microsoft.windowsappsdk\1.4.231008000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(931,9): error MSB3030: Could not copy the file "obj\x64\Debug\net7.0-windows10.0.19041.0\win-x64\AppHead.xbf" because it was not found.
```

### DevServer
When adding `MainWindow.EnableHotReload();`
```
error CS0012: The type 'Window' is defined in an assembly that is not referenced. You must add a reference to assembly 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'.
```

**Comment by LITTOMA** [comment]
Any updates on this issue? My Windows project is not built since updated to latest version of Uno.

**Comment by LITTOMA** [comment]
Hello?

**Comment by LITTOMA** [comment]
It's exactly the same as what @dr1rrb mention in the post. The error output for me is like:

```
1>MyApp.Windows.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null.'
1>C:\Users\David\.nuget\packages\microsoft.windowsappsdk\1.4.231008000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(931,9): error MSB3030: Could not copy the file "obj\x64\Debug\net7.0-windows10.0.19041.0\win-x64\AppHead.xbf" because it was not found.
```

**Comment by jeromelaban** [comment]
This is unfortunately not enough to troubleshoot your issue. If you have either Uno.WinUI.Lottie or Uno.WinUI.DevServer included in your `.Windows` project, try removing them.

**Comment by LITTOMA** [comment]
Hi @sasakrsmanovic . I tried to remove Uno.WinUI.Lottie package from the windows project. However another error occurs on build: 
`WMC1006	Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null.'	`

**Comment by jeromelaban** [comment]
Thanks. Can you provide a [binlog](https://platform.uno/docs/articles/uno-builds-troubleshooting.html) of your build? It will help troubleshoot further.

**Comment by jeromelaban** [comment]
Yes, this has been fixed by the uno.sdk. Thanks!
