### ISSUE TITLE
Slider Style override fails

### ISSUE THREAD

**Issue by NGame1** [unoplatform/uno#1420]
## Current behavior
Control Style overriding fail at build (At least slider style overriding)

    <UserControl
        x:Class="HomeControlApp.Shared.Widgets.ACWidgetUC"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:local="using:HomeControlApp.Shared.Widgets"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:UC="using:HomeControlApp.Shared.Widgets"
        mc:Ignorable="d"
        d:DesignHeight="300"
        d:DesignWidth="400">
    
        <UserControl.Resources>
            <ResourceDictionary>
                <ResourceDictionary.MergedDictionaries>
                    <ResourceDictionary Source="/Styles/Generic.xaml"/>
                </ResourceDictionary.MergedDictionaries>
                <LinearGradientBrush x:Key="GreenGradiantBrush" StartPoint="0,0" EndPoint="1,1">
                    <GradientStop Color="#519c61"/>
                    <GradientStop Color="#419b55"/>
                </LinearGradientBrush>
                
                
        
        <Style TargetType="Slider" x:Key="MySlider">
            <Setter Property="Background" Value="{ThemeResource SliderTrackFill}" />
            <Setter Property="BorderThickness" Value="{ThemeResource SliderBorderThemeThickness}" />
            <Setter Property="Foreground" Value="{ThemeResource SliderTrackValueFill}" />
            <Setter Property="FontFamily" Value="{ThemeResource ContentControlThemeFontFamily}" />
            <Setter Property="FontSize" Value="{ThemeResource ControlContentThemeFontSize}" />
            <Setter Property="ManipulationMode" Value="None" />
            <Setter Property="UseSystemFocusVisuals" Value="{StaticResource UseSystemFocusVisuals}" />
            <Setter Property="FocusVisualMargin" Value="-7,0,-7,0" />
            <Setter Property="IsFocusEngagementEnabled" Value="True" />
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="Slider">
                        <Grid Margin="{TemplateBinding Padding}">
    
                            <Grid.Resources>
                                <Style TargetType="Thumb" x:Key="SliderThumbStyle">
                                    <Setter Property="BorderThickness" Value="0" />
                                    <Setter Property="Background" Value="{ThemeResource SliderThumbBackground}" />
                                    <Setter Property="Template">
                                        <Setter.Value>
                                            <ControlTemplate TargetType="Thumb">
                                                <Border
                                                    Background="{TemplateBinding Background}"
                                                    BorderBrush="{TemplateBinding BorderBrush}"
                                                    BorderThickness="{TemplateBinding BorderThickness}"
                                                    CornerRadius="4" />
                                            </ControlTemplate>
                                        </Setter.Value>
                                    </Setter>
                                </Style>
                            </Grid.Resources>
    
                            <VisualStateManager.VisualStateGroups>
                                <VisualStateGroup x:Name="CommonStates">
                                    <VisualState x:Name="Normal" />
    
                                    <VisualState x:Name="Pressed">
    
                                        <Storyboard>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="HorizontalTrackRect" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTrackFillPressed}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="VerticalTrackRect" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTrackFillPressed}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="HorizontalThumb" Storyboard.TargetProperty="Background">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderThumbBackgroundPressed}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="VerticalThumb" Storyboard.TargetProperty="Background">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderThumbBackgroundPressed}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="SliderContainer" Storyboard.TargetProperty="Background">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderContainerBackgroundPressed}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="HorizontalDecreaseRect" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTrackValueFillPressed}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="VerticalDecreaseRect" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTrackValueFillPressed}" />
                                            </ObjectAnimationUsingKeyFrames>
                                        </Storyboard>
                                    </VisualState>
    
                                    <VisualState x:Name="Disabled">
    
                                        <Storyboard>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="HeaderContentPresenter" Storyboard.TargetProperty="Foreground">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderHeaderForegroundDisabled}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="HorizontalDecreaseRect" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTrackValueFillDisabled}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="HorizontalTrackRect" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTrackFillDisabled}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="VerticalDecreaseRect" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTrackValueFillDisabled}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="VerticalTrackRect" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTrackFillDisabled}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="HorizontalThumb" Storyboard.TargetProperty="Background">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderThumbBackgroundDisabled}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="VerticalThumb" Storyboard.TargetProperty="Background">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderThumbBackgroundDisabled}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="TopTickBar" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTickBarFillDisabled}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="BottomTickBar" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTickBarFillDisabled}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="LeftTickBar" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTickBarFillDisabled}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="RightTickBar" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTickBarFillDisabled}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="SliderContainer" Storyboard.TargetProperty="Background">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderContainerBackgroundDisabled}" />
                                            </ObjectAnimationUsingKeyFrames>
                                        </Storyboard>
                                    </VisualState>
    
                                    <VisualState x:Name="PointerOver">
    
                                        <Storyboard>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="HorizontalTrackRect" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTrackFillPointerOver}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="VerticalTrackRect" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTrackFillPointerOver}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="HorizontalThumb" Storyboard.TargetProperty="Background">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderThumbBackgroundPointerOver}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="VerticalThumb" Storyboard.TargetProperty="Background">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderThumbBackgroundPointerOver}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="SliderContainer" Storyboard.TargetProperty="Background">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderContainerBackgroundPointerOver}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="HorizontalDecreaseRect" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTrackValueFillPointerOver}" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="VerticalDecreaseRect" Storyboard.TargetProperty="Fill">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource SliderTrackValueFillPointerOver}" />
                                            </ObjectAnimationUsingKeyFrames>
                                        </Storyboard>
                                    </VisualState>
    
                                </VisualStateGroup>
                                <VisualStateGroup x:Name="FocusEngagementStates">
                                    <VisualState x:Name="FocusDisengaged" />
                                    <VisualState x:Name="FocusEngagedHorizontal">
    
                                        <Storyboard>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="SliderContainer" Storyboard.TargetProperty="(Control.IsTemplateFocusTarget)">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="False" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="HorizontalThumb" Storyboard.TargetProperty="(Control.IsTemplateFocusTarget)">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="True" />
                                            </ObjectAnimationUsingKeyFrames>
                                        </Storyboard>
                                    </VisualState>
                                    <VisualState x:Name="FocusEngagedVertical">
    
                                        <Storyboard>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="SliderContainer" Storyboard.TargetProperty="(Control.IsTemplateFocusTarget)">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="False" />
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="VerticalThumb" Storyboard.TargetProperty="(Control.IsTemplateFocusTarget)">
                                                <DiscreteObjectKeyFrame KeyTime="0" Value="True" />
                                            </ObjectAnimationUsingKeyFrames>
                                        </Storyboard>
                                    </VisualState>
    
                                </VisualStateGroup>
    
                            </VisualStateManager.VisualStateGroups>
    
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="*" />
                            </Grid.RowDefinitions>
    
                            <ContentPresenter x:Name="HeaderContentPresenter"
                                Grid.Row="0"
                                Content="{TemplateBinding Header}"
                                ContentTemplate="{TemplateBinding HeaderTemplate}"
                                FontWeight="{ThemeResource SliderHeaderThemeFontWeight}"
                                Foreground="{ThemeResource SliderHeaderForeground}"
                                Margin="{StaticResource SliderTopHeaderMargin}"
                                TextWrapping="Wrap"
                                Visibility="Collapsed"
                                x:DeferLoadStrategy="Lazy"/>
                            <Grid x:Name="SliderContainer"
                                Grid.Row="1"
                                Background="{ThemeResource SliderContainerBackground}"
                                Control.IsTemplateFocusTarget="True">
                                <Grid x:Name="HorizontalTemplate" MinHeight="{ThemeResource SliderHorizontalHeight}">
    
                                    <Grid.ColumnDefinitions>
                                        <ColumnDefinition Width="Auto" />
                                        <ColumnDefinition Width="Auto" />
                                        <ColumnDefinition Width="*" />
                                    </Grid.ColumnDefinitions>
    
                                    <Grid.RowDefinitions>
                                        <RowDefinition Height="{ThemeResource SliderPreContentMargin}" />
                                        <RowDefinition Height="Auto" />
                                        <RowDefinition Height="{ThemeResource SliderPostContentMargin}" />
                                    </Grid.RowDefinitions>
    
                                    <Rectangle x:Name="HorizontalTrackRect"
                                        Fill="{TemplateBinding Background}"
                                        Height="{ThemeResource SliderTrackThemeHeight}"
                                        Grid.Row="1"
                                        Grid.ColumnSpan="3" />
                                    <Rectangle x:Name="HorizontalDecreaseRect" Fill="{TemplateBinding Foreground}" Grid.Row="1" />
                                    <TickBar x:Name="TopTickBar"
                                        Visibility="Collapsed"
                                        Fill="{ThemeResource SliderTickBarFill}"
                                        Height="{ThemeResource SliderOutsideTickBarThemeHeight}"
                                        VerticalAlignment="Bottom"
                                        Margin="0,0,0,4"
                                        Grid.ColumnSpan="3" />
                                    <TickBar x:Name="HorizontalInlineTickBar"
                                        Visibility="Collapsed"
                                        Fill="{ThemeResource SliderInlineTickBarFill}"
                                        Height="{ThemeResource SliderTrackThemeHeight}"
                                        Grid.Row="1"
                                        Grid.ColumnSpan="3" />
                                    <TickBar x:Name="BottomTickBar"
                                        Visibility="Collapsed"
                                        Fill="{ThemeResource SliderTickBarFill}"
                                        Height="{ThemeResource SliderOutsideTickBarThemeHeight}"
                                        VerticalAlignment="Top"
                                        Margin="0,4,0,0"
                                        Grid.Row="2"
                                        Grid.ColumnSpan="3" />
                                    <Thumb x:Name="HorizontalThumb"
                                        Style="{StaticResource SliderThumbStyle}"
                                        DataContext="{TemplateBinding Value}"
                                        Height="24"
                                        Width="8"
                                        Grid.Row="0"
                                        Grid.RowSpan="3"
                                        Grid.Column="1"
                                        FocusVisualMargin="-14,-6,-14,-6"
                                        AutomationProperties.AccessibilityView="Raw" />
                                </Grid>
                                <Grid x:Name="VerticalTemplate" MinWidth="{ThemeResource SliderVerticalWidth}" Visibility="Collapsed">
    
                                    <Grid.RowDefinitions>
                                        <RowDefinition Height="*" />
                                        <RowDefinition Height="Auto" />
                                        <RowDefinition Height="Auto" />
                                    </Grid.RowDefinitions>
    
                                    <Grid.ColumnDefinitions>
                                        <ColumnDefinition Width="{ThemeResource SliderPreContentMargin}" />
                                        <ColumnDefinition Width="Auto" />
                                        <ColumnDefinition Width="{ThemeResource SliderPostContentMargin}" />
                                    </Grid.ColumnDefinitions>
    
                                    <Rectangle x:Name="VerticalTrackRect"
                                        Fill="{TemplateBinding Background}"
                                        Width="{ThemeResource SliderTrackThemeHeight}"
                                        Grid.Column="1"
                                        Grid.RowSpan="3" />
                                    <Rectangle x:Name="VerticalDecreaseRect"
                                        Fill="{TemplateBinding Foreground}"
                                        Grid.Column="1"
                                        Grid.Row="2" />
                                    <TickBar x:Name="LeftTickBar"
                                        Visibility="Collapsed"
                                        Fill="{ThemeResource SliderTickBarFill}"
                                        Width="{ThemeResource SliderOutsideTickBarThemeHeight}"
                                        HorizontalAlignment="Right"
                                        Margin="0,0,4,0"
                                        Grid.RowSpan="3" />
                                    <TickBar x:Name="VerticalInlineTickBar"
                                        Visibility="Collapsed"
                                        Fill="{ThemeResource SliderInlineTickBarFill}"
                                        Width="{ThemeResource SliderTrackThemeHeight}"
                                        Grid.Column="1"
                                        Grid.RowSpan="3" />
                                    <TickBar x:Name="RightTickBar"
                                        Visibility="Collapsed"
                                        Fill="{ThemeResource SliderTickBarFill}"
                                        Width="{ThemeResource SliderOutsideTickBarThemeHeight}"
                                        HorizontalAlignment="Left"
                                        Margin="4,0,0,0"
                                        Grid.Column="2"
                                        Grid.RowSpan="3" />
                                    <Thumb x:Name="VerticalThumb"
                                        Style="{StaticResource SliderThumbStyle}"
                                        DataContext="{TemplateBinding Value}"
                                        Width="24"
                                        Height="8"
                                        Grid.Row="1"
                                        Grid.Column="0"
                                        Grid.ColumnSpan="3"
                                        FocusVisualMargin="-6,-14,-6,-14"
                                        AutomationProperties.AccessibilityView="Raw" />
                                </Grid>
    
                            </Grid>
    
                        </Grid>
    
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
    
                
            </ResourceDictionary>
        </UserControl.Resources>
    
        <Grid Padding="30,0" CornerRadius="30" BorderThickness="3" BorderBrush="{StaticResource GreenGradiantBrush}">
            <Grid.RowDefinitions>
                <RowDefinition Height="45"/>
                <RowDefinition Height="*"/>
            </Grid.RowDefinitions>
            
            <Grid Grid.Row="0">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="30"/>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="45"/>
                </Grid.ColumnDefinitions>
                <Image Source="ms-appx:///Assets/LockScreenLogo.scale-200.png" Height="30" Grid.Column="0"/>
                <TextBlock Text="Cooling" Foreground="#519c61" Grid.Column="1"/>
                <ToggleSwitch IsOn="True" Foreground="{StaticResource MyTestingOrangeColor}" Grid.Column="2"/>
            </Grid>
    
            <Grid Grid.Row="1">
                <Slider Style="{StaticResource MySlider}" Minimum="0" Maximum="2"/>
            </Grid>
    
        </Grid>
    </UserControl>
    
error :
'ACWidgetUC.StaticResources' does not contain a definition for 'SliderThumbStyle'	HomeControlApp.Droid	obj\Debug\80\g\XamlCodeGenerator\ACWidgetUC_71acb7accbd706e6236f5de02d7441b8.g.cs	

Nuget Package:

Package Version(s):
tried on dev2498 and 2525

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [x] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.2.3)
- [ ] for Mac (version: )

Attachment
and here is repro
[UnoRepro.zip](https://github.com/unoplatform/uno/files/3537120/UnoRepro.zip)

**Comment by TopperDEL** [comment]
Just guessing as I stumble across a similar Problem: might it be because LinearGradientBrush is not yet implemented in Uno?
Try removing it and see if it works. I have a DataTemplate that is (silently) not working if I have a LinearGradientBrush in it.

**Comment by NGame1** [comment]
> Just guessing as I stumble across a similar Problem: might it be because LinearGradientBrush is not yet implemented in Uno?
> Try removing it and see if it works. I have a DataTemplate that is (silently) not working if I have a LinearGradientBrush in it.

No Gradient colors are just working fine in Uno for me. 
![image](https://user-images.githubusercontent.com/19765248/63641838-0751b700-c6ca-11e9-9810-24e2445f17e7.png)

**Comment by TopperDEL** [comment]
Ok - this Looks as it is not Implemented yet:
https://github.com/unoplatform/uno/blob/6f7e23f71084cc7e785fbd0838d04eeeffe7f5e9/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media/LinearGradientBrush.cs

And this within my DataTemplate is not working:
<Grid.BorderBrush>
                <LinearGradientBrush StartPoint="0,0" EndPoint="1,1">
                    <GradientStop Color="{StaticResource GreenColor}" Offset="0"/>
                    <GradientStop Color="{StaticResource GreenColor}" Offset="0.15"/>
                    <GradientStop Color="White" Offset="0.15"/>
                    <GradientStop Color="White" Offset="1"/>
                </LinearGradientBrush>
            </Grid.BorderBrush>-->

**Comment by NGame1** [comment]
> GreenColor

Where you defined the GreenColor resource. If it is in App.xaml that's why
Then I should refer you to the #1237 

This code

    <Grid BorderThickness="20">
        <Grid.BorderBrush>
            <LinearGradientBrush StartPoint="0,0" EndPoint="1,1">
                <GradientStop Color="Blue" Offset="0.25"/>
                <GradientStop Color="Purple" Offset="0.5"/>
                <GradientStop Color="Yellow" Offset="0.75"/>
                <GradientStop Color="Red" Offset="1"/>
            </LinearGradientBrush>
        </Grid.BorderBrush>
		<TextBlock Foreground="Red" Text="Hello, world !" Margin="20" FontSize="30" />
    </Grid>
and this result
![image](https://user-images.githubusercontent.com/19765248/63642259-de352480-c6d1-11e9-988c-fea93e81d119.png)

remember when you set border brush you should set BorderThickness too.
hope this help you

**Comment by davidjohnoliver** [comment]
@NGame1 At the moment Uno doesn't support per-page/per-control style definitions (#119). Generally you should define your styles in a separate file within a top-level `ResourceDictionary`.

@TopperDEL The generated code can be a bit confusing. 
```csharp
	#if false || false || false || false || false
	[global::Uno.NotImplemented]
	#endif
	public  partial class LinearGradientBrush 
```

Note that the `[NotImplemented]` attribute is actually excluded by the conditional for all platforms, indicating that `LinearGradientBrush` _is_ implemented. However you may have run into a particular XAML syntax that Uno doesn't like.
