### ISSUE TITLE
Revise `Xamarin.AndroidX.Legacy.Support.V4` dependency

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#14209]
### What would you like to be added

I'm not sure if we really need this dependency.

### Why is this needed

See https://github.com/dotnet/maui/pull/12232 where this change has improved app size.

**Comment by jeromelaban** [comment]
It is likely that we don't, and we could remove it from net8.

**Comment by Youssef1313** [comment]
@jeromelaban Only net8.0? Do we need it for net7.0?

**Comment by jeromelaban** [comment]
The problem of modifying net7 is that it would cause a break in the dependency chain for projects that is not necessary. Changing in net8 only makes it clear that the upgrade requires that change, and it's not too late to do that I think.
