### ISSUE TITLE
Creating a library makes Visual Studio hang forever

### ISSUE THREAD

**Issue by ST-Apps** [unoplatform/uno#1422]
## Current behavior

Creating a library using Visual Studio template makes Visual Studio hang forever.

## Expected behavior

Creating the library should create the library and add it to the solution.
I can create and run an app, I only can't create a shared library.

## Environment

Nuget Package:

Package Version(s):
Templates version is 1.45.0.1862

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [X] 2019 (version: 16.2.3)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?

I'm not sure that this is the right place to post about this issue, but templates are in this repo so I decided to post it here.

**Comment by ghuntley** [comment]
Howdy Stefano, sorry to hear that. This GitHub issue is the right place to share feedback it's always good to know about problems folks are experiencing. It might be a Visual Studio for Windows or configuration issue on your end though. I'm also running 16.2.3 w/1.45.0.1862 but haven't experienced this. Have tried creating a new app and a new library. Let's go through some basics shall we?

1. What does the lockup look like, at what stage and can you define forever? Any screenshots would help.

2. Please open a feedback report to Microsoft. Head on over to the menu below, when prompted to start a new session of Visual Studio and to record it please do so. Once that session is launched create the project.

![image](https://user-images.githubusercontent.com/127353/63661323-7a0f7f00-c7fd-11e9-908a-6a4b43542119.png)

3. Head to Help -> About Visual Studio and share the contents from "Copy Info" back here on GitHub.

![image](https://user-images.githubusercontent.com/127353/63661415-d07cbd80-c7fd-11e9-8f3f-1fe70a6e6767.png)

4. Do you have any other extensions installed into Visual Studio?

**Comment by RCTycooner** [comment]
This seems similar to my issue I posted yesterday (I didn't find this thread back then, my apologies for the duplicate)
https://github.com/unoplatform/uno/issues/1482

A solution was posted over there, suggesting it is an issue with the nuget cache.

**Comment by ghuntley** [comment]
Going to close this one out and keep https://github.com/unoplatform/uno/issues/1482 open instead.
