### ISSUE TITLE
Automate extracting resources from a running WinUI 3 app

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#14223]
### What would you like to be added

Automate extracting resources from a running WinUI 3 app. See https://gist.github.com/MartinZikmund/fd68639c0a887e7753b02ed41addbd3c for a sample.

### Why is this needed

Parity with WinUI 3

**Comment by MartinZikmund** [comment]
CC @ramezgerges, will be useful for TextBox PR as well

**Comment by Youssef1313** [comment]
Most resources are expected to be in the public WinUI sources. @MartinZikmund We should close for now?
