### ISSUE TITLE
[Gallery][Skia.Gtk] Lightweight styling-'Material', 'Fluent' option and 'Default', 'Override' buttons are not displaying. 

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#14251]
### Current behavior

![lightweight styling issue](https://github.com/unoplatform/uno/assets/74563602/6228fa91-9887-426c-952c-1200efdc030c)

### Expected behavior

![lightweight styling correct](https://github.com/unoplatform/uno/assets/74563602/1edb3480-0909-4124-8334-8252bede9de7)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app.
2. Click on “Lightweight Styling” from the "Ui Component" list.
3. Notice that 'Material', 'Fluent' option and 'Default', 'Override' buttons are not displaying. 

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by Xiaoy312** [comment]
related or duplicate of: #14250

**Comment by sakshi173** [comment]
Okay, closing this one.
