### ISSUE TITLE
Add manifest.json in the default Uno WASM app solution template

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1426]
## What would you like to be added:

1. https://twitter.com/mzikmunddev/status/1165163264398901248?s=12
1. https://nicksnettravels.builttoroam.com/uno-as-a-pwa/

## Why is this needed:

![image](https://user-images.githubusercontent.com/127353/63660668-c3120400-c7fa-11e9-9770-5a40c0b48ccd.png)

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [x] Solution Templates

**Comment by jeromelaban** [comment]
The main issue for this is about firefox's cache invalidation, particularly during debugging sessions. 

Related https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/102

**Comment by gagandeepp** [comment]
CAn you assign this to me?

**Comment by jeromelaban** [comment]
This issue depends on https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/102 as it introduces a difficult workflow for debugging.

**Comment by pranav1698** [comment]
Hey @jeromelaban @ghuntley I would like to work on this issue

**Comment by ghuntley** [comment]
@pranav1698, I've assigned the issue to you and you'll be able to start on it but we won't be able to merge the PR until https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/102 is resolved however.

**Comment by sonnemaf** [comment]
Any news on this issue? I would love to be able to make my WASM app a PWA.

**Comment by MartinZikmund** [comment]
@jeromelaban as the linked issue is fixed, is this just about adding a sample manifest to the project template or something else must be done?

**Comment by jeromelaban** [comment]
It's only about adding the manifest in the default template. I've had mixed feelings about this, mainly because PWAs can cause trouble during development with caching. Could be enabled only in release.

**Comment by gagandeepp** [comment]
I have added the manifest.json file,please let me know the icons and text you need to be added to this

**Comment by gagandeepp** [comment]
https://github.com/unoplatform/uno/pull/4248

Please review this and let me know

**Comment by sasakrsmanovic** [comment]
@pranav1698  Let us know if you will need help with this one. I''ll make a poiont to check in with you in a few days to see how it is going as we are opening up this issue for all Hacktoberfest 2022 participants
