### ISSUE TITLE
`TextBlock.IsTextTrimmed` property does not change and `TextBlock.IsTextTrimmedEvent` does not fire on the Web or mobile

### ISSUE THREAD

**Issue by c-npolyak** [unoplatform/uno#14266]
### Current behavior

There is currently no way to detect a condition when the text width does not fit its parent since IsTextTrimmed property and the corresponding event are not implemented: https://platform.uno/docs/articles/implemented/windows-ui-xaml-controls-textblock.html#not-implemented-properties.

Please, add this functionality it is badly needed.

### Expected behavior

The event should fire and the property should change. 

### Workaround

No known workarounds 

### Works on UWP/WinUI

Yes

**Comment by Xiaoy312** [comment]
on wasm, we can compare these properties of the textblock element: 
- .scrollWidth, .scrollHeight
- .clientWidth, .clientHeight

^ this approach works with .Text="string" or inline string literals/inline runs, mixed with linebreak
