### ISSUE TITLE
Adding Name to a Resource fails on build

### ISSUE THREAD

**Issue by NGame1** [unoplatform/uno#1427]
## Current behavior
this code is fine:

    <UserControl.Resources>
        <LinearGradientBrush x:Key="TurnedOnLightGradiantColor" StartPoint="0,0.5" EndPoint="1,0.5">
            <LinearGradientBrush.GradientStops>
                <GradientStop Color="#897de3" Offset="0.5"/>
                <GradientStop Color="#764294" Offset="1"/>
            </LinearGradientBrush.GradientStops>
        </LinearGradientBrush>
        <LinearGradientBrush x:Key="TurnedOffLightGradiantColor" StartPoint="0,0.5" EndPoint="1,0.5">
            <LinearGradientBrush.GradientStops>
                <GradientStop Color="LightGray" Offset="0.5"/>
                <GradientStop Color="DarkGray" Offset="1"/>
            </LinearGradientBrush.GradientStops>
        </LinearGradientBrush>
    </UserControl.Resources>

but if you add a name it will fail

    <UserControl.Resources>
        <LinearGradientBrush x:Name="TurnedOnLightGradiantColorName" x:Key="TurnedOnLightGradiantColor" StartPoint="0,0.5" EndPoint="1,0.5">
            <LinearGradientBrush.GradientStops>
                <GradientStop Color="#897de3" Offset="0.5"/>
                <GradientStop Color="#764294" Offset="1"/>
            </LinearGradientBrush.GradientStops>
        </LinearGradientBrush>
        <LinearGradientBrush x:Name="TurnedOffLightGradiantColorName" x:Key="TurnedOffLightGradiantColor" StartPoint="0,0.5" EndPoint="1,0.5">
            <LinearGradientBrush.GradientStops>
                <GradientStop Color="LightGray" Offset="0.5"/>
                <GradientStop Color="DarkGray" Offset="1"/>
            </LinearGradientBrush.GradientStops>
        </LinearGradientBrush>
    </UserControl.Resources>

The name 'nameScope' does not exist in the current context	HomeControlApp.Droid	\obj\Debug\80\g\XamlCodeGenerator\LightWidgetUC_9e91f51bbe3d28fd457787006913b69b.g.cs
![image](https://user-images.githubusercontent.com/19765248/63674401-b80ba380-c7fb-11e9-9843-3cbd5a6d55c2.png)

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [x] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by lextm** [comment]
There is no feasible workaround if controls such as `MenuFlyoutItem` are used with `x:Load`. Example,

```
            <MenuFlyoutItem
                x:Name="SidebarPinItem"
                x:Uid="BaseLayoutItemContextFlyoutPinToSidebar"
                x:Load="False"
                Click="{Binding PinItem_Click}"
                Tag="PinItem_FlyoutItem"
                Text="Pin to sidebar">
                <MenuFlyoutItem.Icon>
                    <SymbolIcon Symbol="Pin" />
                </MenuFlyoutItem.Icon>
            </MenuFlyoutItem>
```

If we change that to 

```
            <MenuFlyoutItem
                x:Key="SidebarPinItem"
                x:Uid="BaseLayoutItemContextFlyoutPinToSidebar"
                x:Load="False"
                Click="{Binding PinItem_Click}"
                Tag="PinItem_FlyoutItem"
                Text="Pin to sidebar">
                <MenuFlyoutItem.Icon>
                    <SymbolIcon Symbol="Pin" />
                </MenuFlyoutItem.Icon>
            </MenuFlyoutItem>
```
then Uno XAML code generator works, but UWP will fail with error message,

```
Error

Element must have x:Name attribute specified since it uses x:Load.
Files_Uno.UWP
E:\files-uwp\Files_Uno\Files_Uno.Shared\UserControls\LayoutModes\GenericFileBrowser.xaml
254
```

Therefore, this issue must be fixed

**Comment by jeromelaban** [comment]
It may be adjusted by #3183.

/cc @davidjohnoliver

**Comment by davidjohnoliver** [comment]
Yes this works correctly with #1766. I'll add a test for it.
