### ISSUE TITLE
Can't build abstract base class deriving from `Page`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#14273]
### Current behavior

Also reported as .NET Android issue here - https://github.com/xamarin/xamarin-android/issues/8484, suspecting the issue is on .NET side, but also reporting here for investigation.

### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

VS 17.7.6

### Description

In my project I used the following classes:

```csharp
public partial class GameView : ViewBase<GameViewModel>
{
}

public class GameViewModel : PageViewModel
{
}

public class PageViewModel
{
}

public abstract partial class ViewBase<TViewModel> : Page
    where TViewModel : PageViewModel
{
    protected ViewBase()
    {
    }
}
```

This compiles fine on all platforms except for Android where I get various "illegal character" errors in the build output:

> 2>obj\Debug\net7.0-android\android\src\Alchemy\Views\GameViewBase.java(5,32): javac.exe error JAVAC0000:  error: illegal character: '`'
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\GameViewBase.java(5,32): javac.exe error JAVAC0000: 	extends Alchemy.Views.ViewBase`1[Alchemy.Views.ViewBase`1+TViewModel]
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\GameViewBase.java(5,32): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\GameViewBase.java(5,57): javac.exe error JAVAC0000:  error: illegal character: '`'
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\GameViewBase.java(5,57): javac.exe error JAVAC0000: 	extends Alchemy.Views.ViewBase`1[Alchemy.Views.ViewBase`1+TViewModel]
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\GameViewBase.java(5,57): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(1,31): javac.exe error JAVAC0000:  error: illegal character: '`'
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(1,31): javac.exe error JAVAC0000: package Alchemy.Views.ViewBase`1[Alchemy.Views;
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(1,31): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(4,31): javac.exe error JAVAC0000:  error: illegal character: '`'
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(4,31): javac.exe error JAVAC0000: public abstract class ViewBase`1+TViewModel]
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(4,31): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(14,79): javac.exe error JAVAC0000:  error: illegal character: '`'
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(14,79): javac.exe error JAVAC0000: 		mono.android.Runtime.register ("Alchemy.Views.ViewBase`1, Alchemy", ViewBase`1+TViewModel].class, __md_methods);
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(14,79): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(14,82): javac.exe error JAVAC0000:  error: not a statement
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(14,82): javac.exe error JAVAC0000: 		mono.android.Runtime.register ("Alchemy.Views.ViewBase`1, Alchemy", ViewBase`1+TViewModel].class, __md_methods);
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(14,82): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(14,92): javac.exe error JAVAC0000:  error: ';' expected
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(14,92): javac.exe error JAVAC0000: 		mono.android.Runtime.register ("Alchemy.Views.ViewBase`1, Alchemy", ViewBase`1+TViewModel].class, __md_methods);
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(14,92): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(14,99): javac.exe error JAVAC0000:  error: <identifier> expected
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(14,99): javac.exe error JAVAC0000: 		mono.android.Runtime.register ("Alchemy.Views.ViewBase`1, Alchemy", ViewBase`1+TViewModel].class, __md_methods);
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(14,99): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(18,2): javac.exe error JAVAC0000:  error: illegal start of expression
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(18,2): javac.exe error JAVAC0000: 	public ViewBase`1+TViewModel] (android.content.Context p0)
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(18,2): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(18,17): javac.exe error JAVAC0000:  error: illegal character: '`'
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(18,17): javac.exe error JAVAC0000: 	public ViewBase`1+TViewModel] (android.content.Context p0)
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(18,17): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(18,30): javac.exe error JAVAC0000:  error: <identifier> expected
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(18,30): javac.exe error JAVAC0000: 	public ViewBase`1+TViewModel] (android.content.Context p0)
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(18,30): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(18,59): javac.exe error JAVAC0000:  error: ';' expected
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(18,59): javac.exe error JAVAC0000: 	public ViewBase`1+TViewModel] (android.content.Context p0)
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(18,59): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(21,30): javac.exe error JAVAC0000:  error: illegal character: '`'
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(21,30): javac.exe error JAVAC0000: 		if (getClass () == ViewBase`1+TViewModel].class) {
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(21,30): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(21,33): javac.exe error JAVAC0000:  error: not a statement
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(21,33): javac.exe error JAVAC0000: 		if (getClass () == ViewBase`1+TViewModel].class) {
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(21,33): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(21,43): javac.exe error JAVAC0000:  error: ';' expected
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(21,43): javac.exe error JAVAC0000: 		if (getClass () == ViewBase`1+TViewModel].class) {
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(21,43): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(21,50): javac.exe error JAVAC0000:  error: <identifier> expected
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(21,50): javac.exe error JAVAC0000: 		if (getClass () == ViewBase`1+TViewModel].class) {
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(21,50): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(22,37): javac.exe error JAVAC0000:  error: <identifier> expected
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(22,37): javac.exe error JAVAC0000: 			mono.android.TypeManager.Activate ("Alchemy.Views.ViewBase`1, Alchemy", "Android.Content.Context, Mono.Android", this, new java.lang.Object[] { p0 });
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(22,37): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(22,39): javac.exe error JAVAC0000:  error: illegal start of type
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(22,39): javac.exe error JAVAC0000: 			mono.android.TypeManager.Activate ("Alchemy.Views.ViewBase`1, Alchemy", "Android.Content.Context, Mono.Android", this, new java.lang.Object[] { p0 });
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(22,39): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(22,148): javac.exe error JAVAC0000:  error: not a statement
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(22,148): javac.exe error JAVAC0000: 			mono.android.TypeManager.Activate ("Alchemy.Views.ViewBase`1, Alchemy", "Android.Content.Context, Mono.Android", this, new java.lang.Object[] { p0 });
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(22,148): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(22,150): javac.exe error JAVAC0000:  error: ';' expected
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(22,150): javac.exe error JAVAC0000: 			mono.android.TypeManager.Activate ("Alchemy.Views.ViewBase`1, Alchemy", "Android.Content.Context, Mono.Android", this, new java.lang.Object[] { p0 });
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(22,150): javac.exe error JAVAC0000:
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(22,152): javac.exe error JAVAC0000:  error: illegal start of type
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(22,152): javac.exe error JAVAC0000: 			mono.android.TypeManager.Activate ("Alchemy.Views.ViewBase`1, Alchemy", "Android.Content.Context, Mono.Android", this, new java.lang.Object[] { p0 });
2>obj\Debug\net7.0-android\android\src\Alchemy\Views\ViewBase`1[Alchemy\Views\ViewBase`1+TViewModel].java(22,152): javac.exe error JAVAC0000:

The invalid generated Java source looks as follows:

```java
package Alchemy.Views.ViewBase`1[Alchemy.Views;


public abstract class ViewBase`1+TViewModel]
	extends crc6499cc3f8d6dc23bc6.Page
	implements
		mono.android.IGCUserPeer
{
/** @hide */
	public static final String __md_methods;
	static {
		__md_methods = 
			"";
		mono.android.Runtime.register ("Alchemy.Views.ViewBase`1, UnoLibrary1", ViewBase`1+TViewModel].class, __md_methods);
	}


	public ViewBase`1+TViewModel] (android.content.Context p0)
	{
		super (p0);
		if (getClass () == ViewBase`1+TViewModel].class) {
			mono.android.TypeManager.Activate ("Alchemy.Views.ViewBase`1, UnoLibrary1", "Android.Content.Context, Mono.Android", this, new java.lang.Object[] { p0 });
		}
	}

	private java.util.ArrayList refList;
	public void monodroidAddReference (java.lang.Object obj)
	{
		if (refList == null)
			refList = new java.util.ArrayList ();
		refList.add (obj);
	}

	public void monodroidClearReferences ()
	{
		if (refList != null)
			refList.clear ();
	}
}

```

### Steps to Reproduce

I have created a very simple repro here https://github.com/MartinZikmund/dotnet-android-javac-issue

1. Clone
2. Open in VS
3. **Try to build the Android project - fail**

### Did you find any workaround?

No

### Works on UWP/WinUI

None

### Affected platforms

Android

**Comment by MartinZikmund** [comment]
CC @Youssef1313 maybe you have some idea? Seems awfully lot like the nested classes issue we had

**Comment by Youssef1313** [comment]
I don't think it is on our end 😕

**Comment by christianfo** [comment]
I am getting the same issue with all my classes deriving from Page. Uno version 5.0.19.
Any suggestion for a workaround?

**Comment by MartinZikmund** [comment]
@Youssef1313 maybe this is the problem https://github.com/xamarin/xamarin-android/issues/8484#issuecomment-1796521969

**Comment by Youssef1313** [comment]
@MartinZikmund Wow! Let me investigate it on our side then. I couldn't imagine we could alter the behavior this way.

**Comment by Youssef1313** [comment]
Based on the info from the xamarin-android issue, this is a regression from #13861
