### ISSUE TITLE
Add `__CROSSRUNTIME__` to Uno app template

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#14274]
### What would you like to be added

To compile a given file for Skia & WASM only, users currently have to do something like:

```csharp
#if HAS_UNO && !__ANDROID__ && !__IOS__ && !__MACOS__
```

It would be great to be able to say just `__CROSSRUNTIME__` to target Skia & WASM

### Why is this needed

Ease of use.

**Comment by Youssef1313** [comment]
UNO_REFERENCE_API is already there I think and can be used with the same semantics.
I think having two constants with the same meaning might be confusing for users.

**Comment by MartinZikmund** [comment]
To me `__CROSSRUNTIME__` feels more aligned with the other constants, but that is just personal preference - indeed I forgot that this one exists. On the other hand if we get something like https://github.com/unoplatform/uno.templates/issues/391 in, then a combo of `__CROSSRUNTIME__` and `.crossruntime.cs` would probably make more sense

**Comment by Youssef1313** [comment]
Then we will probably need to deprecate UNO_REFERENCE_API in a future major release maybe Uno 6.

**Comment by MartinZikmund** [comment]
It seems the `UNO_REFERENCE_API` is broken somehow - when I select iOS as target, it still applies 👀👀👀 

![image](https://github.com/unoplatform/uno/assets/1075116/48da1965-936e-4743-96f8-23bfb1e50e13)

**Comment by Youssef1313** [comment]
@MartinZikmund https://github.com/unoplatform/uno/blob/bf635913241e2f20d58c9ae477ad7de6e7ab86ed/build/nuget/uno.winui.common.targets#L59-L61

This condition is wrong :/ :/

**Comment by Youssef1313** [comment]
The wrong condition was corrected in https://github.com/unoplatform/uno/pull/14282.

And, now with Single Project, I think users can do `__WASM__ || __SKIA__` normally.
