### ISSUE TITLE
Date.MinValue doesn't display in TextBlock WASM

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#14289]
### Current behavior

When binding a Date property set as Date.MinValue, the TextBox is unable to display the data as in WinUI
![image](https://github.com/unoplatform/uno/assets/888391/028194f0-0a4a-4346-a707-0c8f509b5e3d)

### Expected behavior

It should display _01/01/0001 00:00:00_ instead of empty

### How to reproduce it (as minimally and precisely as possible)

Added sample

[UnoAppDefaultDate.zip](https://github.com/unoplatform/uno/files/13260936/UnoAppDefaultDate.zip)

### Works on UWP/WinUI

Yes

### Affected platforms

WebAssembly

**Comment by Youssef1313** [comment]
Can you try updating to latest version? This seems to be have already been fixed at some point.

**Comment by Youssef1313** [comment]
As this doesn't seem reproducible on latest stable version, I'm going to close. @paulovila In case you got a repro on latest stable, please re-open and upload the repro project.
