### ISSUE TITLE
ColorAnimation is not supported

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#143]

**Comment by MartinZikmund** [comment]
If this is not yet worked on, I would try to take a look

**Comment by davidjohnoliver** [comment]
@MartinZikmund No one is actively working on this, go for it. :)

You can look at the `AnimatorFactory` class used by `DoubleAnimation` to get an idea of how Uno leverages native animations.

**Comment by MartinZikmund** [comment]
Thank you for the tip! Looking forward to getting more familiar with the UI side 😀

**Comment by MatFillion** [comment]
This will be so good for button states !

You can evaludate if you want to include support for `ColorAnimationUsingKeyFrames` or skip it for now and only support `ColorAnimation`. I'm not sure of the effort/complexity involved for key frames

**Comment by davidjohnoliver** [comment]
This is needed for selection states in the WCT DataGrid (https://github.com/unoplatform/uno/issues/1943) to be displayed.
