### ISSUE TITLE
Discuss whether mergedstyles.xaml should be git-ignored

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#14318]
This specific file is somewhat annoying for version control. I'm not sure if it should be git-ignored?

@MartinZikmund @jeromelaban ?

**Comment by MartinZikmund** [comment]
Yes please 😂

**Comment by jeromelaban** [comment]
The reason for that file to be present is a globbing problem, not a git problem. If we remove that file, it will not be present on initial build and may cause separate issues.

We can try fixing those issues, though.

**Comment by Youssef1313** [comment]
Over the time, our build infrastructure have had large refactorings/improvements. I wonder if this would still be a problem. And anyways, if it's, I agree we could try fixing them as you mentioned.

I'll take to ignore it and see if any issues arise either in local builds or in CI.
