### ISSUE TITLE
[Gallery][All Platforms] DataGrid- DataGrid column details are missing.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#14337]
### Current behavior

![Data grid issue](https://github.com/unoplatform/uno/assets/74563602/d190faf1-b9fc-4e00-ab69-37904de1886f)

### Expected behavior

![Data grid correct](https://github.com/unoplatform/uno/assets/74563602/29ba4c5e-cdd1-4ffa-b502-f62260643cc2)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app.
2. Click on “DataGrid” from the "Community Toolkit" list.
3. Notice that DataGrid column details are missing.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS, Skia (GTK on Linux/macOS/Windows)

**Comment by jeromelaban** [comment]
This looks like a recent addition. @agneszitte @kazo0

**Comment by jeromelaban** [comment]
This is actually related to a recent uno 5 change that requires a new build of community toolkit. The latest canary will have this, can you check later @sakshi173 when [this build is passed](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=101257&view=results) ?

**Comment by sakshi173** [comment]
Verified this issue is fixed, due to that closing it.
![image](https://github.com/unoplatform/uno/assets/74563602/93b520b6-72c4-4a85-a6f3-04f188ad44dc)
