### ISSUE TITLE
Script sections are rendering incorrectly when inside a tab

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#14358]
### What would you like clarification on

https://platform.uno/docs/articles/get-started-with-linux.html?tabs=ubuntu1804#setting-up-for-linux

<img width="508" alt="image" src="https://github.com/unoplatform/uno/assets/5839577/b1b40d86-fead-4293-9553-dea1e58ee682">

### Concern

None

**Comment by Youssef1313** [comment]
Root cause is likely this negative margin:

https://github.com/unoplatform/uno/blob/2d9c2bd2b4beaaf9e9873dfb919cd9e745a1e85b/doc/templates/uno/main.scss#L372-L378

**Comment by jeromelaban** [comment]
This is not fixed by the latest builds of docfx.
