### ISSUE TITLE
[anyplat] MarkupExtension::ProvideValue() is forced into .ToString() by xaml source-gen

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#14361]
### Current behavior

This code below will throw on uno:
```
public class ResponsiveExtension : MarkupExtension
{
    protected override object? ProvideValue(IXamlServiceProvider serviceProvider) => Orientation.Horizontal;
}

<StackPanel Orientation="{local:Responsive}">
	<TextBlock Text="A" />
	<TextBlock Text="B" />
	<TextBlock Text="C" />
</StackPanel>
```

### Expected behavior

^ should work like on windows.

### How to reproduce it (as minimally and precisely as possible)

[responsive_value.zip](https://github.com/unoplatform/uno/files/13299572/responsive_value.zip)

### Workaround

n/a

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI@5.0.31

### Affected platforms

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Build tasks

### IDE

Visual Studio 2022

### Anything else we need to know?

generated code:
```
c6.Orientation = 
    (global::Microsoft.UI.Xaml.Controls.Orientation)Convert.ChangeType(
        (((global::Microsoft.UI.Xaml.Markup.IMarkupExtensionOverrides)new global::SampleMarkupExtensions.ResponsiveExtension())
            .ProvideValue(global::Uno.UI.Helpers.MarkupHelper.CreateParserContext(c6, typeof(global::Microsoft.UI.Xaml.Controls.StackPanel), "Orientation", typeof(object))))
            ?.ToString(),
        typeof(global::Microsoft.UI.Xaml.Controls.Orientation)
    );
```

https://github.com/unoplatform/uno/blob/5.0.19/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L4680-L4683
^ doesnt seem right.

Since we know on Windows that calling `Convert.ChangeType("Horizontal", typeof(Orientation))` will throw.
And obiviously, `.ToString()` and `Convert.ChangeType(text, type)` isn't a safe way to convert?
We could be losing context or performance for complex type.
The very least we should be check if the returned value is of the desired type before attempt to "convert":
```
boxed is T value ? value : Convert.ChangeType(boxed?.ToString(), typeof(T))
```

**Comment by Youssef1313** [comment]
It seems we can just replace `Convert.ChangeType` with `XamlBindingHelper.ConvertValue`? We also shouldn't need to call `ToString` at all.
