### ISSUE TITLE
[Android] Layout trigger arrange phase multiple time

### ISSUE THREAD

**Issue by Robert-Louis** [unoplatform/uno#14373]
### Current behavior

Android layout phase make panel passe more than one time in the arrange phase :

- Performance issue
- the final size change sometime between the pass causing layouting issue
- the final size pass to the arrange phase differ from the other platform causing layouting issue 

In the following example in Android the arrange go three time in the black shape returning in width size 400, then 100, then 400 
In windows it's just go one time with a value of 100

Windows : 
![image](https://github.com/unoplatform/uno/assets/16021239/a5c5fd78-3617-46ef-a6e9-cf33009f1a40)

android: 
![image](https://github.com/unoplatform/uno/assets/16021239/a20a1720-28fa-40c8-a46c-df56509f9efc)

sample app (too big to attach)
https://we.tl/t-ujU1tMKeji

### Expected behavior

- go one time in the arrange phase
- have the same result as the other platforms

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
The underlying android phases may cause this behavior, though it may still be triggered by multiple `InvalidateMeasure` invocations.

**Comment by agneszitte** [comment]
@jeromelaban note that this issue is adding regressions on Android with AutoLayout for the generated code
(cf. https://github.com/unoplatform/uno.toolkit.ui-private/issues/7)

**Comment by Youssef1313** [comment]
@Xiaoy312 I have a runtime test for this already in #14902

**Comment by Robert-Louis** [comment]
[LayoutIssue_.zip](https://github.com/unoplatform/uno/files/13813595/LayoutIssue_.zip)

I missed some bin /obj :)
here a cleaner repro

**Comment by Youssef1313** [comment]
@Robert-Louis I confirmed that the last repro you uploaded works well when updating Uno to latest dev with the fix from #14902 🎉 

However, you may still see the arrange happening multiple times.

![image](https://github.com/unoplatform/uno/assets/31348972/c015a724-3d6f-45b0-a1f7-ec1fd2f69cac)

**Comment by Robert-Louis** [comment]
@Youssef1313 that great ! thanks you !
