### ISSUE TITLE
build error when reference a  multi-level dependency nuget package of uno

### ISSUE THREAD

**Issue by SongOfYouth** [unoplatform/uno#14379]
### Current behavior

There are tow uno libary package `PkgA` and `PkgB`,and a uno project `ProC`, the `PkgB` refered `PkgA`, and `ProC` refered `PkgB`, there is a error: Can not copy the file xxxx\.nuget\packages\ `PkgB` \0.1.0\lib\net6.0-windows10.0.19041\ `PkgA`\Controls\BaseCommandPanel.xbf” when build the project `ProC`, but the xbf file is blong to `PkgA`!

### Works on UWP/WinUI

None

### NuGet package version(s)

```xml
<PackageReference Include="Uno.WinUI" Version="4.10.26" />
```

### IDE

Visual Studio 2022

### IDE version

17.6.6

**Comment by SongOfYouth** [comment]
[UnoLibrary1.zip](https://github.com/unoplatform/uno/files/13314751/UnoLibrary1.zip)
Just pack UnoLibrary1 and UnoLibrary2, then build UnoLibrary3, all of them build with debug.

**Comment by jeromelaban** [comment]
Thanks for the report. This is an issue coming from WinAppSDK: https://github.com/microsoft/microsoft-ui-xaml/issues/8857, you 'll find a workaround there.

**Comment by SongOfYouth** [comment]
> Thanks for the report. This is an issue coming from WinAppSDK: [microsoft/microsoft-ui-xaml#8857](https://github.com/microsoft/microsoft-ui-xaml/issues/8857), you 'll find a workaround there.

Thanks a lot.
