### ISSUE TITLE
[Docs] `Application Data and Settings` page is missing image

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#14390]
### On which page?

https://platform.uno/docs/articles/features/applicationdata.html

### What's wrong?

![image](https://github.com/unoplatform/uno/assets/78549750/cebcaaf3-0974-4bc2-b6ae-e933966fa4bc)

### Any feedback?

In the source code seems to be one tho -> https://github.com/unoplatform/uno/blob/master/doc/articles/features/applicationdata.md/#L1

**Comment by morning4coffe-dev** [comment]
CC @MartinZikmund

**Comment by Youssef1313** [comment]
This is due to:

https://github.com/unoplatform/uno/blob/0379f372ebbf431209ee9bc4a6725a199efff49f/doc/docfx.json#L16-L26

and the extension of the image being `jpeg`
