### ISSUE TITLE
System.InvalidCastException thrown on Android when loading page with an EntranceThemeTransition 

### ISSUE THREAD

**Issue by christianfo** [unoplatform/uno#14422]
### Current behavior

Add the following to MainPage.xaml in a boilerplate Uno application (as generated by the template):
```
    <Page.Transitions>
        <TransitionCollection>
            <EntranceThemeTransition/>
        </TransitionCollection>
    </Page.Transitions>
```

Run the application on Android. As the page loads the following exception is thrown:
```
[DOTNET]       OnNativeLoaded failed in FrameworkElementMixins
[DOTNET]       System.InvalidCastException: Specified cast is not valid.
[DOTNET]          at Microsoft.UI.Xaml.Media.Animation.EntranceThemeTransition.get_FromHorizontalOffset() in C:\a\1\s\src\Uno.UI\UI\Xaml\Media\Animation\EntranceThemeTransition.cs:line 25
[DOTNET]          at Microsoft.UI.Xaml.Media.Animation.EntranceThemeTransition.AttachHorizontalTranslateAnimation(Storyboard storyBoard, IFrameworkElement element, TimeSpan beginTime) in C:\a\1\s\src\Uno.UI\UI\Xaml\Media\Animation\EntranceThemeTransition.cs:line 92
[DOTNET]          at Microsoft.UI.Xaml.Media.Animation.EntranceThemeTransition.AttachToStoryboardAnimation(Storyboard sb, IFrameworkElement element, TimeSpan beginTime, Int32 xOffset, Int32 yOffset) in C:\a\1\s\src\Uno.UI\UI\Xaml\Media\Animation\EntranceThemeTransition.cs:line 144
[DOTNET]          at Microsoft.UI.Xaml.Media.Animation.Transition.OnElementLoaded(Object sender, RoutedEventArgs e) in C:\a\1\s\src\Uno.UI\UI\Xaml\Media\Animation\Transition.cs:line 52
[DOTNET]          at Microsoft.UI.Xaml.FrameworkElement.OnLoaded() in C:\a\1\s\src\Uno.UI\Mixins\Android\FrameworkElementMixins.g.cs:line 672
[DOTNET]          at Microsoft.UI.Xaml.Controls.Control.OnLoaded() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:line 466
[DOTNET]          at Microsoft.UI.Xaml.Controls.ContentControl.OnLoaded() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ContentControl\ContentControl.cs:line 312
Thread finished: <Thread Pool> #8
[DOTNET]          at Microsoft.UI.Xaml.Controls.Page.OnLoaded() in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Page\Page.mux.cs:line 23
[DOTNET]          at Microsoft.UI.Xaml.FrameworkElement.PerformOnLoaded() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.Android.cs:line 55
[DOTNET]          at Microsoft.UI.Xaml.FrameworkElement.OnNativeLoaded() in C:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.Android.cs:line 40
```
Though this does not stop the application from working, the animation is not playing.

The exception is thrown from this getter in src\Uno.UI\UI\Xaml\Media\Animation\EntranceThemeTransition.cs:
```
		public double FromHorizontalOffset
		{
			get { return (double)this.GetValue(FromHorizontalOffsetProperty); }
			set { this.SetValue(FromHorizontalOffsetProperty, value); }
		}
```
`GetValue()` appears to return a boxed `float` (System,Single), not a boxed `double` (System.Double), and the conversion to `double` throws the exception. However, the dependency property is properly defined as a `double` as shown below, so I would expect GetValue to return a boxed `double`.
```
		// Using a DependencyProperty as the backing store for FromHorizontalOffset.  This enables animation, styling, binding, etc...
		public static DependencyProperty FromHorizontalOffsetProperty { get; } =
			DependencyProperty.Register("FromHorizontalOffset", typeof(double), typeof(EntranceThemeTransition), new FrameworkPropertyMetadata(40f));
```

### Expected behavior

No exception to be thrown and the animation to play, as it does in WinUI3.

### How to reproduce it (as minimally and precisely as possible)

Copy the few lines of XAML shown in the description to the MainPage.xaml of a boilerplate Uno app, as generated by the App project template.

### Workaround

Remove the animation on affected platforms.

### Works on UWP/WinUI

None

### NuGet package version(s)

5.0.41 and 5.1.0-dev.469

### Affected platforms

Android

### IDE version

VS 17.7.6

### Anything else we need to know?

I only checked this on Android. I do not know if it reproes on WASM or iOS.

**Comment by jeromelaban** [comment]
Thanks for the report!

## Note for contributors

It looks like the default value for that property is incorrect:

https://github.com/unoplatform/uno/blob/4452c3ea9b4d5214594f2f96fd5606d9b1354141/src/Uno.UI/UI/Xaml/Media/Animation/EntranceThemeTransition.cs#L31

**Comment by christianfo** [comment]
Under certain conditions, this exception prevents the `Loaded` event handler from being called on a given page. This happens on 3 of my 5 different page types when navigating to these pages. I have not figured out what the difference is between those that work and those that don't, but removing the entrance animation on those pages where `Loaded` is not fired makes it fire again.

**Comment by christianfo** [comment]
@jeromelaban, this indeed appears related to the default value passed in the registration. I hit this in another case where I was passing a float literal as default value to `Register` for a property registered as `double`. It looks like the default value is stored with the System type inferred from the literal, not the registered type. So, if we have for example:
```
DependencyProperty.Register(0.0f, typeof(double), ...)
```
if no other value has been assigned to the property, the default value returned by GetValue is a System.Single, which can't be directly cast to double. Once a value of type `double` is assigned to the property, the issue goes away.

In WinUI3, the default value appears to be internally converted to the registered type for the property (`double` in the example above) and returned as such from GetValue.

**Comment by jeromelaban** [comment]
Thanks. I validated against WinUI, and there's no implicit conversion for the default value. It has to be of the appropriate type.

**Comment by christianfo** [comment]
Thanks @jeromelaban. You are correct indeed, I was mistaken. The behavior is the same in WinUI. Nonetheless, it might explain the original bug I reported here.
Also, I realized the code in my previous comment was incorrect. I fixed it for the record.
