### ISSUE TITLE
Uno.Dsp.Tasks.targets Error  : "Unknown generator '{Generator}' for file '{File}'."

### ISSUE THREAD

**Issue by paulquinn** [unoplatform/uno#14431]
### Current behavior

Creating new Uno Platform project from up to date template (package 5.0.22) on Mac (Apple Silicon) and build. The build fails with: 

```
Uno.Dsp.Tasks.targets(20,3): Error  : "Unknown generator '{Generator}' for file '{File}'."
System.FormatException: Input string was not in a correct format. Failure to parse near offset 20. Expected an ASCII digit.
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.Format(String format, Object[] args)
   at Microsoft.Build.Framework.LazyFormattedBuildEventArgs.FormatString(String unformatted, Object[] args)
```

### Expected behavior

The build succeeds.

### How to reproduce it (as minimally and precisely as possible)

- Download Uno.Check on Mac (Apple Silicon)
- Run uno-check, fix all errors 
- Create new Uno Platform project, open, update packages and compile

I've tried this on 2 macs (one new and an older model), both have the same behaviour.

I've also tried with _uno-check --preview-major_ , fixing errors and creating a new project: same behaviour.

### Works on UWP/WinUI

No

### IDE

Rider macOS

### IDE version

2023.2.3

### Anything else we need to know?

I've tried with both dotnet 7 and 8 sdks: they both exhibit the same behaviour.

**Comment by jeromelaban** [comment]
Thanks for the report! 

This is definitely not supposed to happen. Could you attach the csproj that you created that yields this error?

**Comment by paulquinn** [comment]
Sure - see here: [UnoApp1.zip](https://github.com/unoplatform/uno/files/13366007/UnoApp1.zip)

**Comment by paulquinn** [comment]
Actually, cleaning and recompiling, I get the same overall result, but with a more detailed error: 

Uno.Dsp.Tasks.targets(20,3): Error  : "Unknown generator '{Generator}' for file '{File}'."
System.FormatException: Input string was not in a correct format. Failure to parse near offset 20. Expected an ASCII digit.
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.Format(String format, Object[] args)
   at Microsoft.Build.Framework.LazyFormattedBuildEventArgs.FormatString(String unformatted, Object[] args)

**Comment by carldebilly** [comment]
@paulquinn Found the error! It's in the following line:

```
<UnoDspImportColors Include="Styles\*.zip" Generator="False"/>
```

Allowed generators are "XAML" and "CSharp". A fix with better error message (and possible values) is waiting to be merged and published. You can expect it soon, but it won't fix your problem. The real fix is to use an appropriate generator or remove/comment this line if you don't want to use that feature.
