### ISSUE TITLE
x:Bind, Mode=OneWay to a private, protected or internal member of the code-behind class does not work

### ISSUE THREAD

**Issue by christianfo** [unoplatform/uno#14432]
### Current behavior

Given this XAML class:
```
<Page
    x:Class="UnoApp7.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:UnoApp7">

    <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
      <TextBlock Text="Hello Uno Platform "/>
      <TextBlock Text="This line should not be visible!" Visibility="{x:Bind IsVisible, Mode=OneWay}"/>
  </StackPanel>
</Page>
```
And the code behind:
```
namespace UnoApp7
{
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }

        private bool IsVisible => false;
    }
}
```
The output on Android is as follow:
```
Hello Uno Platform
This line should not be visible!
```
Indicating that the binding to private member `IsVisible` did not work correctly. 
Making `IsVisible` public fixes the problem, but making it `protected` or `internal` does not.
Removing `Mode=OneWay` and defaulting to `OneTime` fixes the problem.
I also tested `Mode=TwoWay` with a `TextBox` and that also does not appear to work.

Here is a more complete repro. None of these bindings work correctly.
```
<Page
    x:Class="UnoApp7.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:UnoApp7">

    <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
      <TextBlock Text="Hello Uno Platform "/>
      <TextBlock Text="This line should not be visible!" Visibility="{x:Bind IsVisible, Mode=OneWay}"/>
      <Button IsEnabled="{x:Bind IsButtonEnabled, Mode=OneWay}" Content="Button should be disabled"/>
      <TextBlock Text="{x:Bind Text, Mode=OneWay}"/>
      <TextBox Text="{x:Bind Text, Mode=TwoWay}"/>
      <ListView ItemsSource="{x:Bind Items, Mode=OneWay}"/>
    </StackPanel>
</Page>
```
```
namespace UnoApp7
{
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }

        private bool IsVisible => false;
        private bool IsButtonEnabled => false;
        private string Text { get; set; } = "Bound text";
        private List<string> Items => new List<string> { "Item 1", "Item 2", "Item 3" };
    }
}
```

### Expected behavior

To successfully bind with `x:Bind` and `Mode=OneWay` or `Mode=TwoWay` to a static, protected or internal member of the code-behind, as is the case with `Mode=OneTime` and is also the case in WinUI3.

### How to reproduce it (as minimally and precisely as possible)

See code in "Current behavior" section.

### Workaround

Make the bound source public. 

### Works on UWP/WinUI

None

### NuGet package version(s)

Uno 5.0.41 (or 5.1.0-dev.469)
WinAppSDK 1.4.231008000

### Affected platforms

Android

### IDE version

VS 17.7.6

### Anything else we need to know?

I have only tried on Windows and Android. Presumably WASM and iOS have the same behavior as Android, but I have not verified.

**Comment by christianfo** [comment]
Title was incorrectly stating 'static' instead of 'private'. Fixed.

**Comment by christianfo** [comment]
Added repro sample app.

**Comment by jeromelaban** [comment]
Thanks for the update!

## Note for contributors

This is likely caused by an invocation to:
https://github.com/unoplatform/uno/blob/5cd6262014b5a0bfe007b20b2955ec232a45acaf/src/Uno.UI/DataBinding/BindingPropertyHelper.cs#L138
Which is not using the `allowPrivateMembers` when used through `x:Bind`.

**Comment by Youssef1313** [comment]
![image](https://github.com/unoplatform/uno/assets/31348972/a4324ee1-c834-43d3-9130-a3dc67a308d8)

Looks like it's already the case :/

**Comment by jeromelaban** [comment]
@Youssef1313 but is the property returned properly? If it is, then there's another location where we might ignore private members incorrectly (there are other methods in this class that take `includePrivateMembers`).

**Comment by Youssef1313** [comment]
![image](https://github.com/unoplatform/uno/assets/31348972/ac819fca-68bc-41cb-8707-e8cd116809be)

**Comment by jeromelaban** [comment]
This would mean that some how:

https://github.com/unoplatform/uno/blob/5cd6262014b5a0bfe007b20b2955ec232a45acaf/src/Uno.UI/DataBinding/BindingExpression.cs#L122-L127

Is not populating the list properly. It may very well be inside of the `ValueType` property.

**Comment by Youssef1313** [comment]
`ValueType` wasn't calculated properly because `allowPrivateMembers` was ignored in certain code path. I'll get a PR soon after writing a test.
