### ISSUE TITLE
docs: reverse order or workshops

### ISSUE THREAD

**Issue by sasakrsmanovic** [unoplatform/uno#14437]
In the left navigation menu there are docs listings;  tube player being listed ahead of simple calc. 

Can we please have Simple Calc listed first, followed by Tube Player one?

**Comment by sasakrsmanovic** [comment]
![Image](https://github.com/unoplatform/uno/assets/33944563/0f17fcad-d054-4a2f-ae6e-212fec5a84e4)

**Comment by agneszitte** [comment]
@jeromelaban / @sasakrsmanovic since it is already ordered differently with the latest doc changes, I am closing this issue.
![image](https://github.com/unoplatform/uno/assets/16295702/572ed5bc-dd49-4d47-a65d-f312fbf29fcb)
