### ISSUE TITLE
Uno.WinUI is missing .Net 8 Windows lib output.

### ISSUE THREAD

**Issue by IsmailHassani** [unoplatform/uno#14449]
### Current behavior

Building/running the .net 8 windows head generates an error.
```
C:\Users\ismai\.nuget\packages\microsoft.windowsappsdk\1.4.231008000\buildTransitive\MrtCore.PriGen.targets(657,5): error MSB4096: The item "C:\Users\ismai\.nuget\packages\uno.winui\5.0.48/lib/net7.0-windows10.0.19041.0/Uno.UI.Toolkit.pri" in item list "PackagingOutputs" does not define a value for metadata "ProjectName".  In order to use this metadata, either qualify it by specifying %(PackagingOutputs.ProjectName), or ensure that all items in this list define a value for this metadata.
```

When i check the nuget package i see a missing net8.0-windows folder under lib
![image](https://github.com/unoplatform/uno/assets/7172716/687fffea-4035-4cae-aa55-9ee6be55c5c6)

### Expected behavior

Should run out of the box

### Works on UWP/WinUI

None

### NuGet package version(s)

5.0.48

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

17.8

**Comment by jeromelaban** [comment]
Thanks for the report. net8 missing is generally not a problem, though https://github.com/unoplatform/uno/issues/14448 may be somehow related but this is not showing in our standard tests for net8.0 builds.

This may also be caused by https://github.com/microsoft/microsoft-ui-xaml/issues/8857. Are you building a library?

**Comment by IsmailHassani** [comment]
Yes, I'm building a library for the Uno platform. But the error occurs in a sample project referencing this library.

**Comment by jeromelaban** [comment]
Then this will be https://github.com/microsoft/microsoft-ui-xaml/issues/8857. Can you try adding the workaround specified there?
