### ISSUE TITLE
Hot Reload of XAML stopped working after upgrade to Uno5, .NET8 and VS 17.8

### ISSUE THREAD

**Issue by HakanL** [unoplatform/uno#14458]
### Current behavior

I can't get hot reload of XAML to work in my application any more (it used to work fine). I've upgraded to Uno 5, .NET8 and Visual Studio 2002 17.8. Yes, I know it would've been better to just upgrade one part, but I did a system upgrade of all the parts, the app is running, but hot reload stopped working.

### Expected behavior

Changes to XAML should update the running application.

### How to reproduce it (as minimally and precisely as possible)

I haven't tested this in a new application, but this used to work fine in my current application. I'm hoping we can troubleshoot the issue as-is.

### Works on UWP/WinUI

No

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia, Uno.UI.DevServer / Uno.WinUI.DevServer

### NuGet package version(s)

<PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
<PackageReference Include="Uno.Diagnostics.Eventing.Providers" Version="2.1.0" />
<PackageReference Include="Uno.Dsp.Tasks" Version="1.2.8" />
<PackageReference Include="Uno.Extensions.Authentication.WinUI" Version="3.0.11" />
<PackageReference Include="Uno.Extensions.Configuration" Version="3.0.11" />
<PackageReference Include="Uno.Extensions.Logging.Serilog" Version="3.0.11" />
<PackageReference Include="Uno.Extensions.Logging.WinUI" Version="3.0.11" />
<PackageReference Include="Uno.Extensions.Navigation.Toolkit.WinUI" Version="3.0.11" />
<PackageReference Include="Uno.Extensions.Navigation.WinUI" Version="3.0.11" />
<PackageReference Include="Uno.Material.WinUI" Version="4.0.6" />
<PackageReference Include="Uno.Resizetizer" Version="1.2.1" />
<PackageReference Include="Uno.Toolkit.WinUI" Version="5.0.17" />
<PackageReference Include="Uno.Toolkit.WinUI.Material" Version="5.0.17" />
<PackageReference Include="Uno.WinUI" Version="5.0.48" />

### Affected platforms

Skia (GTK on Linux/macOS/Windows), Windows

### IDE

Visual Studio 2022

### IDE version

17.8

### Anything else we need to know?

I get this in the debug window when I save the XAML, so it seems to detect that a change has occured:
```
15:56:14.587 DBG [Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor] Skipping file reload
15:56:14.591 DBG [Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor] Skipping file reload
```

And this is what I have in the "Uno Platform" output window:
```
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views\g2hlhny0.kwz~ changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views\HomePage.xaml changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views\g2hlhny0.kwz~ changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views\g2hlhny0.kwz~ changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views\g2hlhny0.kwz~ changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views\HomePage.xaml~RFa1d727f.TMP changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views\HomePage.xaml~RFa1d729e.TMP changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views\HomePage.xaml~RFa1d729e.TMP changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views\HomePage.xaml changed
[DEBUG] dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
[DEBUG]       File C:\Projects\DMXCore\100\Software\Shared\Views\g2hlhny0.kwz~ changed
```

**Comment by HakanL** [comment]
FWIW I ran into [this issue](https://github.com/dotnet/sdk/issues/36666), but the workaround seemed to have worked for me.

**Comment by HakanL** [comment]
I looked at the [troubleshooting tips](https://platform.uno/docs/articles/features/working-with-xaml-hot-reload.html?tabs=vswin%2Cskia), I can't find the RemoteControl.g.cs file (there is no RemoteControl analyzer node in my Shared project).

**Comment by jeromelaban** [comment]
Thanks for the updates. Which platform are you trying hot reload on? 

Could you set this line to `Trace`:
https://github.com/unoplatform/uno.templates/blob/f5574085f6abaa3dc220511f1ee2b0dcb1cad846/src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Shared/AppHead.xaml.cs#L101

As well as this line:

https://github.com/unoplatform/uno.templates/blob/f5574085f6abaa3dc220511f1ee2b0dcb1cad846/src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Shared/AppHead.xaml.cs#L72

This will show more information from your app. Can you post those here?

**Comment by HakanL** [comment]
It seems that it reports that it's disabled:
```
...
2023-11-19 22:29:34.752 DBG [Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor] ProjectConfigurationAttribute=C:\Projects\DMXCore\100\Software\DMXCore100.Skia.Gtk\DMXCore100.Skia.Gtk.csproj, Paths=4
2023-11-19 22:29:34.754 VRB [Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor] 	- C:\Projects\DMXCore\100\Software\Base
2023-11-19 22:29:34.754 VRB [Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor] 	- C:\Projects\DMXCore\100\Software\Shared
2023-11-19 22:29:34.756 VRB [Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor] 	- C:\Projects\DMXCore\100\Software\Shared\Styles
2023-11-19 22:29:34.758 VRB [Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor] 	- C:\Projects\DMXCore\100\Software\Shared\Views
2023-11-19 22:29:34.764 VRB [Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor] ServerMetadataUpdates Enabled:False DebuggerAttached:True BuildingInsideVS: True unorid: Skia
2023-11-19 22:29:34.768 VRB [Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor] Partial Hot Reload Enabled:False unoRuntimeIdentifier:Skia targetFramework:net8.0 buildingInsideVisualStudio:net8.0 debuggerAttached:True
2023-11-19 22:29:34.770 VRB [Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor] XamlReader Hot Reload Enabled:False targetFramework:net8.0
2023-11-19 22:29:34.773 VRB [Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor] Metadata Updates runtime capabilities: Baseline AddMethodToExistingType AddStaticFieldToExistingType AddInstanceFieldToExistingType NewTypeDefinition ChangeCustomAttributes UpdateParameters GenericUpdateMethod GenericAddMethodToExistingType GenericAddFieldToExistingType
...
2023-11-19 22:31:28.917 DBG [Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor] Skipping file reload
2023-11-19 22:31:28.921 DBG [Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor] Skipping file reload
```

**Comment by HakanL** [comment]
I have this in my code:
```
                window.EnableHotReload();
```

which is set from the builder:
```
                window = builder.Window;
```

Any if I set a breakpoint on that line then it hits.

**Comment by jeromelaban** [comment]
Thanks. If nothing else is showing, this would mean that you have not enabled C# hot reload on file save. Make sure to press the "hot reload" button (the red flame) or enable hot reload on save.

**Comment by HakanL** [comment]
Ahh, yes, that was it. I used to have the flag "Hot reload on save" turned on, now it was off for some reason. It would be great if the DevServer in Uno could warn about this, to help ignorant developers like myself :)
