### ISSUE TITLE
Fresh app crashes at startup with "Operation is not valid due to the current state of the object."

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#14459]
### Current behavior

I created a new Uno-app for Net8 with MVUX and Custom Authentication. On first startup it crashes at ``Host = await builder.NavigateAsync<Shell>()``:

![image](https://github.com/unoplatform/uno/assets/1833242/ffe54beb-5366-4127-be16-b1302f818a21)

Any ideas what this might be? Is it a Wizard-Configuration, that is not often used? Did I miss something? I cannot really see where my issue comes from.

Here is my sample:
[UnoStartupCrash.zip](https://github.com/unoplatform/uno/files/13399882/UnoStartupCrash.zip)

### Expected behavior

The app starts up - I did not yet change anything from the Wizard-Generated code

### How to reproduce it (as minimally and precisely as possible)

Create a new app with these settings:
- Customize Default
- Net8
- Remove WebAssembly and GTK
- MVUX
- XAML
- Remove Server-project
- Custom Authentication
- Github Actions

### Workaround

None, yet

### Works on UWP/WinUI

No

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

17.8

**Comment by TopperDEL** [comment]
I see - I was missing an implementation of IAuthenticationService. It would be nice to maybe add a stub with the wizard and crash there with somethin like a NotImplementedException. Otherwise the error message is confusing.

Closing this issue, though.

**Comment by formalist** [comment]
@TopperDEL could you please add some details/lines of code of your solution? Thank you.

**Comment by TopperDEL** [comment]
I think it was basucally this line:
https://github.com/TopperDEL/Shardinator/blob/0ad5e61bc9ce47bd618dc1d26baca2ceb5c290fb/Shardinator/App.cs#L71

**Comment by formalist** [comment]
Actually, I think it was this one:

https://github.com/TopperDEL/Shardinator/blob/0ad5e61bc9ce47bd618dc1d26baca2ceb5c290fb/Shardinator/App.cs#L64

`services.AddSingleton<IAuthenticationService, StorjAuthenticationService>();`

Thanks!

**Comment by TopperDEL** [comment]
You're right! But there is another custom Implementation created by thw wizard, which I deleted. This could have been used, too. But I didn't know how. 🙈😅
