### ISSUE TITLE
5.0.48: ProgressRing does not render in iOS and Android

### ISSUE THREAD

**Issue by baskren** [unoplatform/uno#14465]
### Current behavior

In version 5.0.48, the ProgressRing does not render in iOS and Android.  It does render in WASM and Windows.

<details>
<summary>**iOS Screen Shot**</summary>
![image](https://github.com/unoplatform/uno/assets/2528888/e8e02c5a-7bff-41dd-a0f4-23152fc5aa10)
</details>

<details>
<summary>**ANDROID Screen Shot**</summary>
![Screenshot_1700414182](https://github.com/unoplatform/uno/assets/2528888/8232e61c-cbaf-4504-87dc-0f87f4cfab81)
</details>

**NOTES**
1. In iOS, **Application Output** is continuously flooded with the following three messages:
```text
2023-11-19 10:33:22.337675-0500 MyApp.Mobile[76872:1033086] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x600002be4ae0> to GL_RENDERBUFFER 1
2023-11-19 10:33:22.338009-0500 MyApp.Mobile[76872:1033086] Failed to make complete multisample framebuffer object 8cd6
2023-11-19 10:33:22.338160-0500 MyApp.Mobile[76872:1033086] Failed to make complete framebuffer object 8cd6
```
2. MacCatalyst or MacOS: Unknown since VSMacARM Builds fail when targeting these frameworks.  
3. As of yet, cannot build anything but WASM and Skia.GTK in VSCodeMac : https://github.com/unoplatform/uno/discussions/14460

### Expected behavior

ProgressRing renders as it does in Windows and WASM

<details>
<summary>**WINDOWS screen shot**</summary>
<img width="455" alt="image" src="https://github.com/unoplatform/uno/assets/2528888/45b5eeec-0be6-4b20-9ba9-b995352dff14">
</details>

<details>
<summary>**WASM screen shot**</summary>
<img width="506" alt="image" src="https://github.com/unoplatform/uno/assets/2528888/b8358a9f-2f79-4c00-8926-f49853e1e70f">
</details>

### How to reproduce it (as minimally and precisely as possible)

Simple demo project: https://github.com/baskren/ProgressRingDemo

### Workaround

None found as of yet.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.0.48

### Affected platforms

Android, iOS

### IDE

Visual Studio 2022, Visual Studio for Mac

### IDE version

VSMAC ARM: 17.6.7 (build 417), VS2022 ARM: Version 17.8.0  

### Relevant plugins

n/a

**Comment by jeromelaban** [comment]
Thanks for the report. This is indeed a regression, we'll take a look.

**Comment by jeromelaban** [comment]
This issue is caused by https://github.com/unoplatform/uno/pull/13839, @ajpinedam found that the SKSwapChainPanel does not measure/arrange itself properly anymore. We'll need to make a PR to SkiaSharp to address this behavior for developers using SKSwapChain panel directly in Uno 5.

**Comment by baskren** [comment]
Thanks!
