### ISSUE TITLE
Unusual label appearing on iOS

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1449]
## Current behavior

This is a very unusual problem which my brother spotted while testing my Uno-based app.

For some reason it randomly displayed a label with view model name at the bottom of the view (don't mind the WASM namespace, that is an accidental rename issue):

![image](https://user-images.githubusercontent.com/1075116/63969263-c5e25280-caa1-11e9-8fab-3b6481a46a99.png)

I haven't been able to reproduce the problem and he wasn't either after restarting the app. There is no `TextBlock` control at that location in XAML.

The ad control at the bottom is a AdMob ad, which I have implemented only for iOS and Android and which I am adding to the page dynamically in a platform-specific `#if` directive. The view itself is a `Grid` with two rows, the ad control is the only control residing in the second row.

AdControl.iOS.cs:

```
#if __IOS__
using Google.MobileAds;
using System;
using System.Collections.Generic;
using System.Text;
using UIKit;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml;
using CoreGraphics;

namespace SmsTicket.Core.Controls
{
    public partial class AdControl : ContentControl
    {
        public AdControl()
        {
            HorizontalContentAlignment = HorizontalAlignment.Stretch;
            VerticalContentAlignment = VerticalAlignment.Stretch;
            Background = SolidColorBrushHelper.Red;
            Width = AdSizeCons.LargeBanner.Size.Width;
            Height = AdSizeCons.LargeBanner.Size.Height;
            Windows.UI.Xaml.Window.Current.Activated += Current_Activated;            
        }

        private void LoadAd()
        {
            var adView = new BannerView(AdSizeCons.LargeBanner)
            {
                AdUnitID = "......",
                RootViewController = GetVisibleViewController()
            };
            adView.LoadRequest(GetRequest());
            Content = adView;
        }

        Request GetRequest()
        {
            var request = Request.GetDefaultRequest();
            // Requests test ads on devices you specify. Your test device ID is printed to the console when
            // an ad request is made. GADBannerView automatically returns test ads when running on a
            // simulator. After you get your device ID, add it here
            request.TestDevices = new[] { Request.SimulatorId.ToString() };
            return request;
        }

        UIViewController GetVisibleViewController()
        {
            UIViewController rootController;
            if (UIApplication.SharedApplication.KeyWindow == null)
            {                
                return null;
            }
            else
            {
                rootController = UIApplication.SharedApplication.KeyWindow.RootViewController;
            }

            if (rootController.PresentedViewController == null)
                return rootController;

            if (rootController.PresentedViewController is UINavigationController)
            {
                return ((UINavigationController)rootController.PresentedViewController).VisibleViewController;
            }

            if (rootController.PresentedViewController is UITabBarController)
            {
                return ((UITabBarController)rootController.PresentedViewController).SelectedViewController;
            }

            return rootController.PresentedViewController;
        }

        private void Current_Activated(object sender, Windows.UI.Core.WindowActivatedEventArgs e)
        {
            LoadAd();
        }
    }
}
#endif
```

Any idea what could cause this unusual behavior?

## Expected behavior

No label displayed.

## How to reproduce it (as minimally and precisely as possible)

Hard to say... I can provide the app source code if it may help.

From the looks of it it seems like the `ContentControl` displayed not only its `Content` but also the `ToString()` of its data binding.

## Environment

Package Version(s): 1.46.202-dev.2508

Affected platform(s):
- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This looks like an invalid binding operation. This can sometimes happen as a result of re-binding, or because a datatemplate value is being databound. 

You can try forcefully setting the DataContext to null, so it does not get propagated down from the parent.

**Comment by ghuntley** [comment]
Let us know if you can reproduce it @MartinZikmund. 👍

**Comment by MartinZikmund** [comment]
Couldn't yet. Will let you know if I do find a way to reproduce

**Comment by MartinZikmund** [comment]
Hasn't occured since, closing for now.
