### ISSUE TITLE
[TreeView] When Dragging and Dropping the TreeViewItem, TreeView.DragItemsCompleted is not called in `.NET 8` WASM

### ISSUE THREAD

**Issue by TopProgrammer77** [unoplatform/uno#14498]
### Current behavior

When Dragging and Dropping the `TreeViewItem`, `TreeView.DragItemsCompleted` is not called in .NET 8 WASM, but it works in previous version.
[1.zip](https://github.com/unoplatform/uno/files/13428550/1.zip)

### Works on UWP/WinUI

None

### NuGet package version(s)

```
<Project ToolsVersion="15.0">
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="8.0.0-rc.2.23479.6" />
    <PackageVersion Include="Microsoft.Windows.Compatibility" Version="8.0.0-rc.2.23479.10" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.4.231008000" />
    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageVersion Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.7.0" />
    <PackageVersion Include="Uno.Resizetizer" Version="1.2.1" />
    <PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.48" />
    <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
    <PackageVersion Include="Uno.Wasm.Bootstrap" Version="8.0.4" />
    <PackageVersion Include="Uno.Wasm.Bootstrap.DevServer" Version="8.0.4" />
    <PackageVersion Include="Uno.Wasm.Bootstrap.Server" Version="8.0.4" />
    <PackageVersion Include="Uno.WinUI" Version="5.0.48" />
    <PackageVersion Include="Uno.WinUI.Lottie" Version="5.0.48" />
    <PackageVersion Include="Uno.WinUI.DevServer" Version="5.0.48" />
    <PackageVersion Include="Uno.WinUI.WebAssembly" Version="5.0.48" />
  </ItemGroup>
</Project>

```

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.8

**Comment by DierkDroth** [comment]
Thanks for isolating @TopProgrammer77.

**Comment by jeromelaban** [comment]
We haven't investigated this issue yet, and we can't say if it's a regression or not, or related to .NET 8 either.

@TopProgrammer77 you mention a previous version, which is it? In general .NET versions don't affect the app's behavior, so it may only be related to an uno version change. Finding which version changed the behavior will help.

**Comment by DierkDroth** [comment]
Thanks @jeromelaban 

I'll task @TopProgrammer77 to see if he could fix it. I know for sure that the feature worked before and now no longer does...

**Comment by TopProgrammer77** [comment]
> @TopProgrammer77 you mention a previous version, which is it? In general .NET versions don't affect the app's behavior, so it may only be related to an uno version change. Finding which version changed the behavior will help.

I realized that it isn't related to .NET 8. I tested on .NET 7 and also uno 4, same issue was reproduced.
