### ISSUE TITLE
Invalid links in **Contributing to Uno Platform** 

### ISSUE THREAD

**Issue by baskren** [unoplatform/uno#14522]
### On which page?

https://platform.uno/blog/contributing-to-uno-platform-from-novice-to-expert/#get-started

### What's wrong?

The following links shown point to https://chat.openai.com as a host, instead of https://platform.uno:
<img width="911" alt="image" src="https://github.com/unoplatform/uno/assets/2528888/74d47f7a-a615-472d-9aa0-f9cfc2abc79b">

First link:
- should be: https://github.com/unoplatform/uno/blob/master/CODE_OF_CONDUCT.md
- is: https://chat.openai.com/c/link-to-code-of-conduct

Second link:
- maybe should be: https://platform.uno/docs/articles/uno-development/uno-internals-overview.html
- is: https://chat.openai.com/c/link-to-uno-codebase

**Comment by mtmattei** [comment]
This was fixed internally. Thanks for reporting.

**Comment by baskren** [comment]
Thank you @mtmattei
