### ISSUE TITLE
XamlFileGenerator.RewriteNamespaces is a large contributor to GC time in Visual Studio

### ISSUE THREAD

**Issue by davkean** [unoplatform/uno#14527]
### Current behavior

Visual Studio's new high-GC telemetry, [discussed here](https://twitter.com/davkean/status/1672295235026829312), has captured an issue with XamlFileGenerator.RewriteNamespaces where it is allocating a very large amount of data in a short space of time in the wild. At its worst case, we caught it allocating at a rate of 1174 MB/second over 60 seconds, for a total of about 80 GB within the devenv process. We saw this approx. 80 times over the past 90 days with a medium allocation rate of 229 MB/second.

![image](https://github.com/unoplatform/uno/assets/1103906/3c353730-a374-4080-8e5d-ae57258ae05f)

The overwhelming allocations on this path is the use of regex, which appears to be capturing a fairly simple pattern:

https://github.com/unoplatform/uno/blob/5cd6262014b5a0bfe007b20b2955ec232a45acaf/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L4572-L4575

### Expected behavior

Can we write this path to be almost allocation free with exception to the string replacement?

1) Use a simple parser to capture the pattern you are looking for
2) Build a simple cache that maps from unqualified -> fully qualified namespace that is shared for the project. I imagine its pretty common for the same namespaces to be used repeatibility throughout a lot of XAML.

### How to reproduce it (as minimally and precisely as possible)

This was caught by telemetry, there is no available repro project.

### Works on UWP/WinUI

None

### NuGet package version(s)

While I can manually gather the versions numbers if needed (it takes a bit of work), I can see the latest version of the code still has this problem - so its not related to the package version.

### Affected platforms

Build tasks

### IDE

Visual Studio 2022

### IDE version

All versions

**Comment by Youssef1313** [comment]
Thank you for the detailed information @davkean!

**Comment by Youssef1313** [comment]
I've got a fix for this: https://github.com/unoplatform/uno/pull/14534.
