### ISSUE TITLE
Support MediaSource.CreateFromStream() for MediaPlayerElement

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#14549]
### What would you like to be added

I need to play a video where I only have a stream available. Therefore I would need to have MediaSource.CreateFromStream() to be added.

### Why is this needed

I'm loading videos from a cloud storage, where I only get a Stream but no URI.

### For which platform

Android, iOS

**Comment by Youssef1313** [comment]
Related: https://github.com/unoplatform/uno/pull/13162

**Comment by TopperDEL** [comment]
Oh, I searched the issues but did not find something related. Sorry!
Closing this referencing #12812
