### ISSUE TITLE
`GridView` with `Header` and `HeaderTemplate` renders incorrectly starting with 5.0.19

### ISSUE THREAD

**Issue by lukasf** [unoplatform/uno#14543]
### Current behavior

The header seems to be rendered twice: Once on the left of the grid view (which takes away most of the size), and once on top of the list view where it belongs.

![Screenshot_1700772040](https://github.com/unoplatform/uno/assets/2306201/74ff61f4-02fb-4136-8138-ff6315c98402)

### Expected behavior

This is how it looks like up to latest 4.x

![Screenshot_1700770660](https://github.com/unoplatform/uno/assets/2306201/7f4d3b4c-dfa2-43d5-b4d0-4a3eec0a606a)

### How to reproduce it (as minimally and precisely as possible)

Just add a GridView with Header and HeaderTemplate. Watch how header is rendered twice.

### Workaround

-

### Works on UWP/WinUI

Yes

### NuGet package version(s)

5.0.19 and up

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. 

Could you still provide a repro sample? Also, can you try wit the latest dev builds?

**Comment by lukasf** [comment]
Here is a minimal repro. Note how the header is displayed twice on Android. UWP is fine. The WASM head would not come up for me. Latest 5.1 dev still shows the same bug.

[Uploading UnoHeader.zip…]()

**Comment by jeromelaban** [comment]
Thanks for the repro!

**Comment by lld1995** [comment]
Is the same issue ? #14597

**Comment by lukasf** [comment]
This looks very different to me. Different control, different kind of template, different render result issue. I don't think that these are related.

**Comment by Youssef1313** [comment]
@Xiaoy312 Is this fixed?

**Comment by jeromelaban** [comment]
It should be yes. The backport is coming, it's available in latest 5.1-dev bits.
