### ISSUE TITLE
[Flipview] Flipview broken after upgraded Uno.WinUI to 5.xxx

### ISSUE THREAD

**Issue by DosangGu** [unoplatform/uno#14551]
### Current behavior

When using Flipview, I expected to see only one item appers, but previous and next item also appears.
In 4.xxx version, I could only find one item.

```xaml
<Page x:Class="UnoFlipviewBugReproduce.Presentation.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:UnoFlipviewBugReproduce.Presentation"
      xmlns:uen="using:Uno.Extensions.Navigation.UI"
      xmlns:utu="using:Uno.Toolkit.UI"
      xmlns:um="using:Uno.Material"
      NavigationCacheMode="Required"
      Background="{ThemeResource BackgroundBrush}">

  <Grid utu:SafeArea.Insets="VisibleBounds" Background="Black">
    <Grid.ColumnDefinitions>
      <ColumnDefinition Width="0.5*"/>
      <ColumnDefinition Width="180"/>
      <ColumnDefinition Width="0.5*"/>
    </Grid.ColumnDefinitions>
    <utu:NavigationBar Content="{Binding Title}" />

    <FlipView Grid.Column="1" HorizontalAlignment="Center" VerticalAlignment="Center" Background="Green">
      <FlipView.Items>
        <Image Source="https://uno-website-assets.s3.amazonaws.com/wp-content/uploads/2023/05/12135417/logo.png"/>
        <Image Source="https://uno-website-assets.s3.amazonaws.com/wp-content/uploads/2023/05/12135417/logo.png"/>
        <Image Source="https://uno-website-assets.s3.amazonaws.com/wp-content/uploads/2023/05/12135417/logo.png"/>
        <Image Source="https://uno-website-assets.s3.amazonaws.com/wp-content/uploads/2023/05/12135417/logo.png"/>
        <Image Source="https://uno-website-assets.s3.amazonaws.com/wp-content/uploads/2023/05/12135417/logo.png"/>
      </FlipView.Items>
    </FlipView>
  </Grid>
</Page>
```

![image](https://github.com/unoplatform/uno/assets/102457336/221aa9a9-24aa-4703-9fe2-1c1e4cd9d672)

### Expected behavior

Only one focused item should appears

### How to reproduce it (as minimally and precisely as possible)

Checkout my bug reproducing repo.
<https://github.com/DosangGu/UnoFlipviewBugReproduce>

Reproduced using .net7 and .net8(check branches)

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

`Uno.WinUi` 5.0.48

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
@ajpinedam does this look familiar?

**Comment by sang-hyeon** [comment]
same issue here.

**Comment by DosangGu** [comment]
Are there any temporary solutions for this issue? I need some features(like enhanced hot reload) of Uno 5.0.

**Comment by jeromelaban** [comment]
@DosangGu there isn't at this time, we'll provide updates to this issue when we will.

**Comment by DosangGu** [comment]
Still facing the issue with version `5.0.152`. When do you expect the fix shipped?
