### ISSUE TITLE
Adding <WasmShellEnableThreads>true</WasmShellEnableThreads> to WASM project causes execution to abort.

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#14559]
### Current behavior

Execution aborts with the following in the log file
Setting UNO_BOOTSTRAP_MONO_RUNTIME_MODE=Interpreter
Setting UNO_BOOTSTRAP_MONO_PROFILED_AOT=False
Setting UNO_BOOTSTRAP_LINKER_ENABLED=False
Setting UNO_BOOTSTRAP_DEBUGGER_ENABLED=True
Setting UNO_BOOTSTRAP_MONO_RUNTIME_CONFIGURATION=Release
Setting UNO_BOOTSTRAP_MONO_RUNTIME_FEATURES=threads
Setting UNO_BOOTSTRAP_APP_BASE=package_1b0a2652755d2df18ade863b01ab41ba67521906
Setting UNO_BOOTSTRAP_WEBAPP_BASE_PATH=/
Setting UNO_BOOTSTRAP_MAX_THREADS=4
Unable to set option 'no-jiterpreter-traces-enabled' as it's read-only.
Debugging hotkey: Shift+Alt+D (when application has focus)
Registering service worker for /
Aborted()
Service Worker Registered

The browser console output is attached,
![Screenshot 2023-11-24 165506](https://github.com/unoplatform/uno/assets/4189260/2ebb969b-78af-4797-bde0-0822de1df04d)

### Expected behavior

WASM Threading should be available

### How to reproduce it (as minimally and precisely as possible)

Reproduced in repo:
https://github.com/BrianDT/UnoWASMThreadingIssue.git

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

<PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
<PackageVersion Include="Microsoft.Windows.Compatibility" Version="7.0.5" />
<PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
<PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.4.231008000" />
<PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
<PackageVersion Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.7.0" />
<PackageVersion Include="Uno.Resizetizer" Version="1.2.1" />
<PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.48" />
<PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
<PackageVersion Include="Uno.Wasm.Bootstrap" Version="8.0.4" />
<PackageVersion Include="Uno.Wasm.Bootstrap.DevServer" Version="8.0.4" />
<PackageVersion Include="Uno.Wasm.Bootstrap.Server" Version="8.0.4" />
<PackageVersion Include="Uno.WinUI" Version="5.0.48" />
<PackageVersion Include="Uno.WinUI.Lottie" Version="5.0.48" />
<PackageVersion Include="Uno.WinUI.DevServer" Version="5.0.48" />
<PackageVersion Include="Uno.WinUI.WebAssembly" Version="5.0.48" />

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.7.7

**Comment by BrianDT** [comment]
Sample updated to net8 and Uno.SDK 5.4.10
Issue confirmed as resolved or no longer present.
Please close.

**Comment by jeromelaban** [comment]
Support for threading is experimental and might fail like you just way and broken in net9. It's may be that support will come back in net10.
