### ISSUE TITLE
Sample description not showing

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#14586]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/31348972/7e721164-b69a-4ef2-af1a-fc455d094a0b)

![image](https://github.com/unoplatform/uno/assets/31348972/22f88f1f-5b28-4d8f-97ab-710e0544e09c)

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
I think this feature was lost along the way. It's supposed to be shown by the `SampleControl` class, but does not anymore.

**Comment by MartinZikmund** [comment]
I think it should be added under the "i" button in the top navbar. Can you look into that, @morning4coffe-dev ?

**Comment by Youssef1313** [comment]
It was in the very bottom of screen IIRC
