### ISSUE TITLE
cant compile xaml file

### ISSUE THREAD

**Issue by cconner100** [unoplatform/uno#14582]
### Current behavior

I am getting this error on compilation

D:\source\ZiiDMS\ZiiDMSApp\Client\ZiiDMSApp\ZiiDMSApp\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.Xam
lCodeGenerator\ZtShellPage_1417a2ab143b14d67a03ae0ce9ec7b98.cs(221,264): error CS0118: '___tctx' is a variable but is u
sed like a type [D:\source\ZiiDMS\ZiiDMSApp\Client\ZiiDMSApp\ZiiDMSApp\ZiiDMSApp.csproj::TargetFramework=net8.0-android
]

I try to look and see what file its generating but i cant find it.  This is happening with all platforms.

Any idea of what i am doing wrong? something wrong with my nugets?

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
Thanks for the report @cconner100. It will be hard to help without providing a repro. Can you please upload a repro? Thank you!

**Comment by cconner100** [comment]
Here is a quick sample,

This was built using the Uno VS template and .net 8.  Take a look at MainPage.xaml, line 25 seems to be the issue.  This sample is not meant to be runnable, just compile to show the issue.

Also why do i get this warning when i use the template

warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): win10-arm64, win10-x64, win10-x86. Affected libraries: Microsoft.WindowsAppSDK. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.

[XamlCompileError.zip](https://github.com/unoplatform/uno/files/13482929/XamlCompileError.zip)

**Comment by nickrandolph** [comment]
@cconner100 w.r.t. the WindowsAppSDK warning - We're still waiting for Microsoft to fix the WindowsAppSDK for .NET 8.0. In the meantime you can remove the warning by adding `<UseRidGraph>true</UseRidGraph>` to the Windows target and the Windows case in the class library

**Comment by nickrandolph** [comment]
This would appear to be the culprit:

      `Header="{x:Bind ((ContentControl)ViewModel.Selected).Content, Mode=OneWay}"`

I haven't investigated as to whether this was what you intended, but this is causing the compilation issue

**Comment by cconner100** [comment]
Yes i know, FYI this worked in net7 uno 4 but not in the net8 and uno 5.  Also if i change this from x:Bind to binding it goes away

Thanks
