### ISSUE TITLE
When the namespace of a class that extends from Windows.UI.Xaml.DependencyObject contains "Uno", the solution fails to build.

### ISSUE THREAD

**Issue by DysnomianC** [unoplatform/uno#1462]
## Current behavior

When the namespace of a class that extends from `Windows.UI.Xaml.DependencyObject` contains "Uno" there are compile errors in the generated file, eg:

> The type or namespace name 'UI' does not exist in the namespace 'MyProject.Uno' (are you missing an assembly reference?)

in project `MyProject.Uno.iOS` and file `MyDependencyObject.cs`.

## Expected behavior

Project to build with no compile errors.

## How to reproduce it (as minimally and precisely as possible)

Create new uno project called "MyProject.Uno".
Create a new class in `MyProject.Uno.Shared` that extends `Windows.UI.Xaml.DependencyObject`.
Build the solution.
[MyProject.Uno.zip](https://github.com/unoplatform/uno/files/3567741/MyProject.Uno.zip)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.3.0 Preview 2.0)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?

Should be able to be fixed by prefixing the namespace `Uno` in generated files with `global::`.

The generated code currently looks like:
```private Uno.UI.DataBinding.ManagedWeakReference _selfWeakReference;
Uno.UI.DataBinding.ManagedWeakReference IWeakReferenceProvider.WeakReference 
{
	get
	{
		if(_selfWeakReference == null)
		{
			_selfWeakReference = Uno.UI.DataBinding.WeakReferencePool.RentSelfWeakReference(this);
		}
		
		return _selfWeakReference;
	}
}
```

It should look like 
```private global::Uno.UI.DataBinding.ManagedWeakReference _selfWeakReference;
global::Uno.UI.DataBinding.ManagedWeakReference IWeakReferenceProvider.WeakReference
{
	get
	{
		if (_selfWeakReference == null)
		{
			_selfWeakReference = global::Uno.UI.DataBinding.WeakReferencePool.RentSelfWeakReference(this);
		}

		return _selfWeakReference;
	}
}
```

**Comment by ghuntley** [comment]
Howdy @DysnomianC. We'd greatly appreciate it if you could send in a pull-request. This document (WIP) should help you out https://gist.github.com/ghuntley/a9bf61f0184d3b040c9a46f43dfc7280#cross-targeting-override. Let us know if you experience any friction or have any questions.

**Comment by ghuntley** [comment]
Lovely 💖💖

**Comment by DysnomianC** [comment]
Thanks for including this change and guiding me through the process. 😄
