### ISSUE TITLE
Clicked buttons bound to `ICommand` using `CanExecute` don't show their updated status

### ISSUE THREAD

**Issue by HakanL** [unoplatform/uno#14633]
### Current behavior

I have a button that when it's clicked should be disabled (so it can only be pressed once). I have it bound to a `ICommand` which is using the RelayCommand from CommunityToolkit.Mvvm. The command handler sets the `CanExecute` to false, which should make the button have the disabled state. This works if I'm controlling a different button's CanExecute, but not the button that's pressed. I've linked a simple example that shows the issue below. Clicking the On and Off buttons should toggle the states of the On/Off button to indicate that when it's On the On-button should be disabled. The button in the middle is updated correctly. The CanExecute functionality works (i.e. when it's false the command's handler isn't executed), but I want the button to also have the disabled state.
I'm pretty sure this worked in Uno4, but I haven't re-tested.

### Expected behavior

When `CanExecute` is set to false (and the Notify method is called) the button should have the disabled state, even if it was the button that was clicked that set the property.

### How to reproduce it (as minimally and precisely as possible)

https://github.com/HakanL/Uno5-Button-Command-Issue

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageVersion Include="SkiaSharp.Skottie" Version="2.88.6" />
    <PackageVersion Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.6" />
    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageVersion Include="Uno.Material.WinUI" Version="4.0.6" />
    <PackageVersion Include="Uno.Dsp.Tasks" Version="1.2.8" />
    <PackageVersion Include="Uno.Resizetizer" Version="1.2.1" />
    <PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.64" />
    <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
    <PackageVersion Include="Uno.WinUI" Version="5.0.64" />
    <PackageVersion Include="Uno.WinUI.DevServer" Version="5.0.64" />
    <PackageVersion Include="Uno.WinUI.Lottie" Version="5.0.64" />
    <PackageVersion Include="Uno.WinUI.RemoteControl" Version="5.0.48" />
    <PackageVersion Include="Uno.WinUI.Skia.Gtk" Version="5.0.64" />
    <PackageVersion Include="Uno.Toolkit.WinUI" Version="5.0.17" />
    <PackageVersion Include="Uno.Toolkit.WinUI.Material" Version="5.0.17" />

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

17.8

### Anything else we need to know?

Only tested on Skia (Win+Linux GTK).

**Comment by HakanL** [comment]
Hmm, @jeromelaban that's odd, the buttons I press don't change the enabled status, only the button with the text "Button" changes. But it's the same in WinUI, but still strange. This is what it looks like for me, using the repo linked above, note how both On and Off are enabled at the same time:
![image](https://github.com/unoplatform/uno/assets/407941/527c9a3c-3ed2-49ed-8d05-aca01b4cb6a0)

Skia on Windows 11, but I get the same issue on Linux GTK.

**Comment by limeniye** [comment]
I saw similar problems in MAUI.
https://github.com/dotnet/maui/issues/9753
https://github.com/dotnet/maui/issues/8877
https://github.com/dotnet/maui/pull/12488

The main problem, as I understand it, was the VisualState changing after raising the CanExecuteChanged event.
I created the two solutions:

[MaterialButtonCanExecuteSample.zip](https://github.com/unoplatform/uno/files/13579779/MaterialButtonCanExecuteSample.zip)

[DefaultButtonCanExecuteSample.zip](https://github.com/unoplatform/uno/files/13579793/DefaultButtonCanExecuteSample.zip)

https://github.com/unoplatform/uno/assets/69314237/cf30047c-5059-4338-8a1a-0d440e2d5d75

At first glance, the result confirms the similarity of the problems.

**Comment by HakanL** [comment]
@limeniye Good find, I've only tried it with Material. Is there a workaround you can think of that I can apply? I don't really care too much about the animations, but I would like to keep the look and feel of the Material.

**Comment by HakanL** [comment]
@limeniye That's a good suggestion, but I'm getting this error when running the code above, what am I missing? `System.NotSupportedException: 'Collection was of a fixed size.'`

**Comment by limeniye** [comment]
@HakanL, I guess the IList is immutable

```C#
    private void RemoveFocusStates(Button button)
    {
        var childElement = VisualTreeHelper.GetChild(button, 0) as FrameworkElement;
        var visualStateGroups = VisualStateManager.GetVisualStateGroups(childElement);
#if !WINDOWS
        List<VisualStateGroup> newVisualStates = new List<VisualStateGroup>(2);
#endif
        for (int i = 0; i < visualStateGroups.Count; i++)
        {
#if WINDOWS
            if (visualStateGroups[i].Name == "FocusStates")
            {
                visualStateGroups.RemoveAt(i);
                break;
            }
        }
#else
            if (visualStateGroups[i].Name != "FocusStates")
            {
                newVisualStates.Add(visualStateGroups[i]);
            }
        }
        VisualStateManager.SetVisualStateGroups(childElement, newVisualStates);
#endif
    }
```
