### ISSUE TITLE
[UWP] Cannot compile "Internal compiler error: Microsoft.NetNative.targets 697"

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#1463]
Hi,

I tried to convert my app from UWP/C# to Uno.
Uno/UWP compiles ok in Debug, but in Release compilation fails.

Error: Internal compiler error: Object reference not set to an instance of an object. C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\1.7.3\tools\Microsoft.NetNative.targets 697

More detailed build log:
I have some clues:
1> Dependency "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes".
1> Could not resolve this reference. Could not locate the assembly "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1> Dependency "System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes".
1> Could not resolve this reference. Could not locate the assembly "System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
(...) - all with 'referenced in Uno.Core' information.

I tried some solutions:
1) change "minimum version" to 17139 (from 10536): compilation OK. It doesn't fail when "minium version" is 16299 or newer.
As this app is 'dedicated' to phones, UWP should be much lower, i.e. max 14393, so this workaround is not for me.

2) I changed max version from 17763 to 17134, and two nugets: .Net core from 6.2.9 to 6.0.1 and Uno Core from 1.28.2 to 1.20.2. Build OK. 

3) So I update versions one by one, and get this:
 If Uno.Core is 1.28 ("latest stable"), build fails. If I downgrade Uno.Core to 1.27, build succeeded.

**Comment by ghuntley** [comment]
Thanks for reaching out!

Sorry to hear you are experiencing troubles porting your application. We'd like to work with you and help make it possible. Are you able to cut up your application to min-viable which reproduces this issue and share it with us? If you can't share your application then create a new app using the Uno solution wizard and reproduce it in there.

**Comment by pkar70** [comment]
App is very small, I can send it in ZIP file - but it looks like "hard coded" (in Uno.Core 1.28) reference to version 2.0.5.0 (of mscorlib, system...).

**Comment by ghuntley** [comment]
Can you please attach it to GitHub or push it to a repository? https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

**Comment by pkar70** [comment]
[BackupSMS_Uno.UWPShared.zip](https://github.com/unoplatform/uno/files/3574975/BackupSMS_Uno.UWPShared.zip)
I think these files should be enough.

Changing reference Uno.Core from 1.27.0 to 1.28.0
changes "build OK" to build "Error: Internal compiler error: Object reference not set to an instance of an object."

Visual Studio version info:
Microsoft Visual Studio Community 2017 
Version 15.9.15
VisualStudio.15.Release/15.9.15+28307.812
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA012
.NET Portability Analyzer   1.1.10808.0
Application Insights Tools for Visual Studio Package   8.14.20131.1
ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET Core Razor Language Services   15.8.31590
C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Common Azure Tools   1.10
Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
JavaScript Language Service   2.0
JavaScript Project System   2.0
JavaScript UWP Project System   2.0
Microsoft JVM Debugger   1.0
Microsoft MI-Based Debugger   1.0
Microsoft Visual C++ Wizards   1.0
Microsoft Visual Studio VC Package   1.0
MLGen Package Extension   1.0
Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
NuGet Package Manager   4.6.0
ProjectServicesPackage Extension   1.0
ResourcePackage Extension   1.0
ResourcePackage Extension   1.0
TypeScript Tools   15.9.30718.2001
Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Visual Studio Code Debug Adapter Host Package   1.0
Visual Studio Tools for Universal Windows Apps   15.0.28307.718
VisualStudio.Mac   1.0
Xamarin   4.12.3.83 (d15-9@23fa80172)
Xamarin Designer   4.16.30 (e0af99a34)
Xamarin Templates   1.1.128 (6f5ebb2)
Xamarin.Android SDK   9.1.7.0 (HEAD/ba9da7a76)
Xamarin.iOS and Xamarin.Mac SDK   12.4.0.64 (9c8d8e0)

**Comment by ghuntley** [comment]
@pkar70 since creating/using the virtual machine, have you run into this problem?

**Comment by pkar70** [comment]
As it works with Uno.Core 1.27.0, I almost forgot about this problem...
Just tried: build within VM, VStudio 2019, release x86, Uno.Core 1.28.0. Same error.
Changing back to 1.27.0: build OK.

**Comment by jeromelaban** [comment]
Is it still the case now ?

**Comment by pkar70** [comment]
As I'm stick to my fork of Uno, without updating it, I didn't test it with newer versions.

**Comment by jeromelaban** [comment]
You can reopen this issue if this still happens.
