### ISSUE TITLE
`ListView` or `GridView` with an `ItemTemplateSelector` and an `ItemContainerStyle` not rendering correctly.

### ISSUE THREAD

**Issue by christianfo** [unoplatform/uno#14662]
### Current behavior

When applying an `ItemTemplateSelector` and an `ItemContainerStyle` to a `ListView` or a `GridView`, the rendering on WASM and Android is incorrect, showing the item type instead of the item content.

For example, for a GridView presenting items of type `UnoApp9.ItemViewModel`:
![Screenshot1](https://github.com/unoplatform/uno/assets/15091389/c201e697-51da-4b89-8584-0ebfd4678df2)

### Expected behavior

The expected rendering is like this (as it is on Windows):
![Screenshot2](https://github.com/unoplatform/uno/assets/15091389/43cfa748-39bd-4c97-9dc1-2daec74632a4)

Note that
- removing the ItemContainerStyle produces the expected rendering,
- replacing the ItemTemplateSelector by a single template also produces the expected rendering.

### How to reproduce it (as minimally and precisely as possible)

Reduced repro: [UnoApp9.zip](https://github.com/unoplatform/uno/files/13537050/UnoApp9.zip)

It contains a couple of `DataTemplate`'s:
```
        <DataTemplate x:Key="GreenTemplate" x:DataType="local:ItemViewModel">
            <Border Background="LightGreen">
                <TextBlock Text="{x:Bind Text}" HorizontalAlignment="Center" VerticalAlignment="Center" />
            </Border>
        </DataTemplate>

        <DataTemplate x:Key="RedTemplate" x:DataType="local:ItemViewModel">
            <Border Background="LightPink">
                <TextBlock Text="{x:Bind Text}" HorizontalAlignment="Center" VerticalAlignment="Center"/>
            </Border>
        </DataTemplate>
```
for this data type:
```
    public class ItemViewModel
    {
        public string Text { get; set; } = "";
        public bool IsRed { get; set; } = false;
    }
```
And an `ItemTemplateSelector` selecting one of the templates based on the data:
```
        <local:ItemTemplateSelector x:Key="ItemTemplateSelector" 
              RedTemplate="{StaticResource RedTemplate}" GreenTemplate="{StaticResource GreenTemplate}"/>
```
implemented as follow:
```
    public class ItemTemplateSelector : DataTemplateSelector
    {
        public DataTemplate RedTemplate { get; set; } = default!;
        public DataTemplate GreenTemplate { get; set; } = default!;

        protected override DataTemplate SelectTemplateCore(object item, DependencyObject container)
        {
            var model = (item as ItemViewModel)!;
            return model.IsRed ? RedTemplate : GreenTemplate;
        }
    }
```
An item container style
```
        <Style x:Key="ItemContainerStyle" BasedOn="{StaticResource DefaultGridViewItemStyle}" TargetType="GridViewItem">
            <Setter Property="Width" Value="100"/>
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="GridViewItem">
                        <ListViewItemPresenter 
                            Content="{TemplateBinding Content}" 
                            ContentTemplate="{TemplateBinding ContentTemplate}" 
                            CornerRadius="20"/>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
```
Note that I explicitly bound `ContentTemplate` and `Content` of the `ListViewItemPresenter` to the template as indicated as 
a workaround for bug [7446](https://github.com/unoplatform/uno/issues/7446).

And a ListView or GridView utilizing all of the above:
```
        <GridView
            ItemsSource="{x:Bind Items}"
            ItemTemplateSelector="{StaticResource ItemTemplateSelector}"
            ItemContainerStyle="{StaticResource ItemContainerStyle}"/>
```

### Workaround

None known at this time.

### Works on UWP/WinUI

None

### NuGet package version(s)

    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
    <PackageVersion Include="Microsoft.Windows.Compatibility" Version="7.0.5" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.4.231008000" />
    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageVersion Include="Uno.Extensions.Logging.OSLog" Version="1.7.0" />
    <PackageVersion Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.7.0" />
    <PackageVersion Include="Uno.Resizetizer" Version="1.2.1" />
    <PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.64" />
    <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
    <PackageVersion Include="Uno.Wasm.Bootstrap" Version="8.0.4" />
    <PackageVersion Include="Uno.Wasm.Bootstrap.DevServer" Version="8.0.4" />
    <PackageVersion Include="Uno.Wasm.Bootstrap.Server" Version="8.0.4" />
    <PackageVersion Include="Uno.WinUI" Version="5.0.64" />
    <PackageVersion Include="Uno.WinUI.Lottie" Version="5.0.64" />
    <PackageVersion Include="Uno.WinUI.DevServer" Version="5.0.64" />
    <PackageVersion Include="Uno.WinUI.WebAssembly" Version="5.0.64" />
    <PackageVersion Include="Xamarin.Google.Android.Material" Version="1.10.0.1" /

### Affected platforms

WebAssembly, Android

### IDE

Visual Studio 2022

### IDE version

VS 17.7.6

### Anything else we need to know?

I have not tested on iOS but presumably reproes in the same way.

**Comment by lld1995** [comment]
Is the same issue ? #14597

**Comment by christianfo** [comment]
Looks different to me. Different symptoms and no ItemContainerStyle involved in [14597](https://github.com/unoplatform/uno/issues/14597) afaikt.

**Comment by jeromelaban** [comment]
Related to #857
