### ISSUE TITLE
`DependencyProperty.GetProperty` is being accessed on a thread pool worker instead of UI thread

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#14673]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/31348972/b78c1c5b-433e-492d-8617-62588e891e98)

When running `When_Source_Changes` test, `DependencyProperty.GetProperty` gets accessed on a thread pool worker, which can create a race condition since `DependencyProperty.GetProperty` assumes it's only accessed by UI thread.

The root cause for that is:

![image](https://github.com/unoplatform/uno/assets/31348972/9342fad1-161f-438b-84b9-4a4279add75c)

### Expected behavior

I think this should be queued to dispatcher instead?

We need to confirm WinUI behavior, whether `LoadCompleted` is always invoked on the UI thread or not.

cc @ahmed605 

### Works on UWP/WinUI

None

**Comment by ahmed605** [comment]
Seems like the event is always called on the dispatcher of the UI thread, yeah
And if there's no dispatcher exists for the current thread when calling this API it returns/throws `RPC_E_WRONG_THREAD`

**Comment by Youssef1313** [comment]
Thanks @ahmed605 for confirming.

So, the following four lines are what should be enqueued to the dispatcher?

https://github.com/unoplatform/uno/blob/c56e433c153a2328baff6afdaac607df16c3ad29/src/Uno.UI/UI/Xaml/Media/LoadedImageSurface.skia.cs#L75

https://github.com/unoplatform/uno/blob/c56e433c153a2328baff6afdaac607df16c3ad29/src/Uno.UI/UI/Xaml/Media/LoadedImageSurface.skia.cs#L95

https://github.com/unoplatform/uno/blob/c56e433c153a2328baff6afdaac607df16c3ad29/src/Uno.UI/UI/Xaml/Media/LoadedImageSurface.skia.cs#L102

https://github.com/unoplatform/uno/blob/c56e433c153a2328baff6afdaac607df16c3ad29/src/Uno.UI/UI/Xaml/Media/LoadedImageSurface.skia.cs#L133

**Comment by ahmed605** [comment]
Yeah, that should be correct
