### ISSUE TITLE
AnalyticsInfo is not implemented

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#1468]
## What would you like to be added:
`Windows.System.Profile.AnalyticsInfo`

## Why is this needed:
To check the `VersionInfo.DeviceFamily` (like `VersionInfo.DeviceFamily == "Windows.Mobile"`)

## For which Platform:
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

**Comment by MartinZikmund** [comment]
`DeviceForm` is clear, but what should it return for `DeviceFamily`? Something like `Android.Mobile`, etc.?

**Comment by MartinZikmund** [comment]
Done 😀
