### ISSUE TITLE
[Skia] `TextBox` PlaceholderText is vertically centered with specific Height

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#14705]
### Current behavior

PlaceholderText on TextBox is vertically centered by default on Skia when specific Height is set.
![image](https://github.com/unoplatform/uno/assets/78549750/13389f1c-13ca-4812-a7aa-1693bda61f6c)

### Expected behavior

Should be on top as the Text
![image](https://github.com/unoplatform/uno/assets/78549750/6ac14d93-15f1-401e-86eb-9a08fe11fb7e)

### How to reproduce it (as minimally and precisely as possible)

```
<TextBox PlaceholderText="Give it a description..."
   Height="120" />
```

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Latest Uno 5.0 and
```<PackageVersion Include="Uno.WinUI" Version="5.1.0-dev.755" />```

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer)

**Comment by jeromelaban** [comment]
Thanks. This is expected at this time and will evolve once https://github.com/unoplatform/uno/issues/9417 improves.
