### ISSUE TITLE
[Skia] Double click to highlight doesn't work on `TextBox` with AcceptsReturn 

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#14707]
### Current behavior

When using AcceptsReturn on TextBox in Skia, I am not able to use double click to select my inputted text, mostly it automatically deselects it 
https://github.com/unoplatform/uno/assets/78549750/8fba4212-bf48-4de2-a862-a3d31febb3e1

### Expected behavior

The text should be easily highlightable with double click. 

### How to reproduce it (as minimally and precisely as possible)

```
<TextBox AcceptsReturn="True" />
```

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Latest Uno 5.0 and
```<PackageVersion Include="Uno.WinUI" Version="5.1.0-dev.755" />```

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer)

**Comment by jeromelaban** [comment]
Thanks. This is expected at this time and will evolve once https://github.com/unoplatform/uno/issues/9417 improves.

**Comment by ramezgerges** [comment]
This has been added to the managed skia textbox a while ago along with triple-click to select lines.
