### ISSUE TITLE
VS Code does not get source generator code

### ISSUE THREAD

**Issue by microhobby** [unoplatform/uno#14710]
### Current behavior

Setting for example a `Name` property does not set the code behind and the analyzer tells that the symbol does not exist.

### Expected behavior

Setting for example a `Name` property should generate the code behind and be accessible on their respective `.xaml.cs`.

### How to reproduce it (as minimally and precisely as possible)

- using VS Code
- set a `Name` property on `.xaml`
- try to access this identifier on the `.xaml.cs`

### Workaround

Restart the `omnisharp` seems to work. But it's annoying and slow.
On the previous version of the Uno we had the `UnoUIUseRoslynSourceGenerators` that when set to `false` also fixed this on the VS Code, but now appears that the v5 does not have it anymore.

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Using the new template for Uno 5

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio Code

### IDE version

1.84.2

**Comment by jeromelaban** [comment]
Thanks for the report.

Indeed, it's not working properly (omnisharp is not handling refreshes properly), and we're working on getting the support for C# devkit, which should hopefully make this issue go away.

In the meantime, changing the csproj (adding a space in a node) is enough to get omnisharp to reevaluate everything properly.

**Comment by spouliot** [comment]
The latest version (0.12) of the [Uno Platform extension for VS Code is out](https://platform.uno/blog/announcing-c-dev-kit-support-and-linux-android-debugging-support-for-uno-platform-vs-code-extension/). It support C# Dev Kit which works fine with your scenario. Please try it and let us know!
