### ISSUE TITLE
Error when trying to use `CommunityToolkit.WinUI.Controls.SettingsControls`

### ISSUE THREAD

**Issue by cconner100** [unoplatform/uno#14739]
### Current behavior

Uno 5 platform, .Net8 system.

I have a sub project that is including the CommunityToolkit.WinUI.Controls.SettingsControls.  My package references are like this

```
   <PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" />
    <PackageReference Include="Uno.WinUI" />
    <PackageReference Include="Uno.Resizetizer" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Uno.Extensions.Configuration" />
    <PackageReference Include="Uno.Extensions.Logging.WinUI" />
    <PackageReference Include="Uno.Toolkit.WinUI" />
    <PackageReference Include="Uno.Extensions.Core.WinUI" />
    <PackageReference Include="Uno.Extensions.Hosting.WinUI" />
    <PackageReference Include="Uno.Extensions.Navigation.Toolkit.WinUI" />
    <PackageReference Include="Uno.Extensions.Navigation.WinUI" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
```

I can compile windows output just fine but when i compile the mobile project i get this error

```
D:\Mobile\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.Binda
bleTypeProviders.BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs(3674,91): error CS0433: The type 'CameraHel
per' exists in both 'CommunityToolkit.WinUI.Helpers, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Commun
ityToolkit.WinUI, Version=7.1.0.0, Culture=neutral, PublicKeyToken=4aff67a105548ee2' [D:\source\ZiiDMSV2\Applications\C
lient\ZiiDMSApp\ZiiDMSApp.Mobile\ZiiDMSApp.Mobile.csproj::TargetFramework=net8.0-android]
```

My mobile platform has the following package references
```
 <ItemGroup>
    <PackageReference Include="Uno.WinUI" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Uno.Extensions.Configuration" />
    <PackageReference Include="Uno.Extensions.Logging.WinUI" />
    <PackageReference Include="Uno.Toolkit.WinUI" />
    <PackageReference Include="Uno.Extensions.Hosting.WinUI" />
    <PackageReference Include="Uno.Extensions.Localization.WinUI" />
    <PackageReference Include="Uno.Extensions.Navigation.Toolkit.WinUI" />
    <PackageReference Include="Uno.Extensions.Navigation.WinUI" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Uno.Extensions.Logging.OSLog" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" />
    <PackageReference Include="Uno.WinUI.DevServer" Condition="'$(Configuration)'=='Debug'" />
  </ItemGroup>
```

Finally my head app has this for package references
```
    <PackageReference Include="Uno.WinUI" />
    <PackageReference Include="Uno.Resizetizer" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Uno.Extensions.Configuration" />
    <PackageReference Include="Uno.Extensions.Logging.WinUI" />
    <PackageReference Include="Uno.Toolkit.WinUI" />
    <PackageReference Include="Uno.Extensions.Core.WinUI" />
    <PackageReference Include="Uno.Extensions.Hosting.WinUI" />
    <PackageReference Include="Uno.Extensions.Localization.WinUI" />
    <PackageReference Include="Uno.Extensions.Navigation.Toolkit.WinUI" />
    <PackageReference Include="Uno.Extensions.Navigation.WinUI" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Microsoft.Graph" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" />
    <PackageReference Include="Microsoft.Identity.Client" />
```

I dont see where i reference CommunityToolkit.WinUI.Helpers

any clues?

thanks

### Expected behavior

Compile with out error

### Works on UWP/WinUI

Yes

### Environment

Other

### NuGet package version(s)

```
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.2.1" />
    <PackageVersion Include="CommunityToolkit.WinUI" Version="7.1.2" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.0.230907" />
    <PackageVersion Include="CommunityToolkit.WinUI.UI" Version="7.1.2" />
    <PackageVersion Include="CommunityToolkit.WinUI.UI.Animations" Version="7.1.2" />
    <PackageVersion Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2" />
```

```
    <PackageVersion Include="Uno.CommunityToolkit.WinUI" Version="7.1.200" />
    <PackageVersion Include="Uno.CommunityToolkit.WinUI.UI" Version="7.1.200" />
    <PackageVersion Include="Uno.CommunityToolkit.WinUI.UI.Animations" Version="7.1.200" />
    <PackageVersion Include="Uno.CommunityToolkit.WinUI.UI.Controls" Version="7.1.200" />
```

### Affected platforms

Android, iOS, Mac Catalyst

**Comment by ogarvey** [comment]
> The current version of Community Toolkit does not support Uno 5.x yet. I have a issue to track this here [CommunityToolkit/Windows#281](https://github.com/CommunityToolkit/Windows/issues/281)

Is there anything we can do locally in the meantime if we were to build the packages from source? I tried recreating a simple existing app after seeing the 5.0 Launch Webinar, but it fell apart and refused to build as soon as I added a DataGrid as described here: https://platform.uno/docs/articles/uno-community-toolkit.html?tabs=tabid-winui

**Comment by jeromelaban** [comment]
@ogarvey you can view a DataGrid sample here: https://github.com/unoplatform/Uno.Samples/tree/master/UI/UnoWCTDataGridSample

**Comment by ogarvey** [comment]
> @ogarvey you can view a DataGrid sample here: https://github.com/unoplatform/Uno.Samples/tree/master/UI/UnoWCTDataGridSample

That doesn't appear to be doing anything different to what I was doing previously.

Unfortunately that doesn't even build but with a different error to the one I receive when trying to add the DataGrid. 
![image](https://github.com/unoplatform/uno/assets/994386/8103575f-eaf4-403f-b245-b550ea5c441a)

```xml
<!-- Include the Community Toolkit -->
	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
		<PackageReference Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2" />
	</ItemGroup>
	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'windows'">
		<PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls" Version="7.1.100" />
	</ItemGroup>
```


Even just adding the PackageReference above to a new project, as per the csproj in the example seems to break the build. 

![image](https://github.com/unoplatform/uno/assets/994386/bb1e1489-9a1f-450a-8471-cf5ca1f6cfe2)
![image](https://github.com/unoplatform/uno/assets/994386/76f1ce02-072d-415c-95f4-7168b983c511)
![image](https://github.com/unoplatform/uno/assets/994386/7f5ab530-3085-4360-884c-d0061edecad6)

Removing the package version doesn't help any either.

**Comment by jeromelaban** [comment]
Thanks for the update. Indeed, the sample does not build properly in visual studio (after [this change](https://github.com/microsoft/WindowsAppSDK/issues/3842)). It will be fixed by https://github.com/unoplatform/Uno.Samples/pull/623. You can take a look at the changes and repeat them in your version.

Still, you see to be having a lot of other errors that seem to indicate nuget restore errors. In general, it's best to look at the build output than the error window. Can you create another build and [post the binlog](https://platform.uno/docs/articles/uno-builds-troubleshooting.html)?

**Comment by ogarvey** [comment]
> Thanks for the update. Indeed, the sample does not build properly in visual studio (after [this change](https://github.com/microsoft/WindowsAppSDK/issues/3842)). It will be fixed by [unoplatform/Uno.Samples#623](https://github.com/unoplatform/Uno.Samples/pull/623). You can take a look at the changes and repeat them in your version.
> 
> Still, you see to be having a lot of other errors that seem to indicate nuget restore errors. In general, it's best to look at the build output than the error window. Can you create another build and [post the binlog](https://platform.uno/docs/articles/uno-builds-troubleshooting.html)?

Thanks for the link to the fix, I'll take a look at that. 

As for the build errors, I've managed to resolve those after adding the toolkit package versions to the Directory.Packages.props file in the root project directory.

**Comment by jeromelaban** [comment]
Thanks for the updates!

**Comment by cconner100** [comment]
Curious what was the fix a new update to uno? not sure if i understand what was fixed

**Comment by jeromelaban** [comment]
@cconner100 there's no update to uno needed, it's only a matter of updating the packages to the right versions (see https://github.com/unoplatform/Uno.Samples/pull/623). You also mentioned that you resolved it on your end.
