### ISSUE TITLE
Include Reference Link to the Playground and Gallery in each Control Documentation.

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno#14746]
Details from @rafael-rosa-knowcode:

The purpose of the change requested in the issue is

- publicize the sensational resources we have at the Gallery (https://gallery.platform.uno/) ,
- publicize the Playground (https://playground.platform.uno/) ,
- facilitate the use of controls,
- improve the look of documentation by showing more content
- allow users who are browsing the page to understand how the feature works (Gallery) and how it can be applied (Playground).

Reference on the docs Navigation: Reference => UI => Controls => [Implemented Views ](https://platform.uno/docs/articles/implemented-views.html) 
Include reference in each document on the Implemented Views page.

> Note: Only when it already exists in the Playground and when it exists in the Gallery.

The link Reference would be included on the specific control page.

- A simple visualization of what it would look like would look like this (but the design department may suggest another version)

![Image](https://github.com/unoplatform/uno/assets/116665025/8eedf24a-d4d4-421d-a8b1-6a56b4932613)

- The suggested text is:

To better understand how it works, you can use the Gallery here [ link https://gallery.platform.uno/#combobox]
Or run your own Playground tests here [ link https://playground.platform.uno/#combobox] .

PR https://github.com/unoplatform/uno/pull/14833

______________________________________________________________________________

- [x] For direct access to a Gallery page to happen, the project needs to be updated to allow access using tags. As already happens with Playground.

On the playground: https://playground.platform.uno/#combobox
Suggested feature: https://gallery.platform.uno/#combobox

Branch on Gallery dev/ramr/issueUno14746-addHashRedirect

PR: https://github.com/unoplatform/Uno.Gallery/pull/1054

**Comment by rafael-rosa-knowcode** [comment]
To redirect to the playground we can use saved snippet.

**Comment by rafael-rosa-knowcode** [comment]
Waiting for https://github.com/unoplatform/Uno.Gallery/pull/1054

**Comment by rafael-rosa-knowcode** [comment]
https://github.com/unoplatform/Uno.Gallery/pull/1054 merged.
