### ISSUE TITLE
[Docs] Tabs doesn't get properly deselected

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#14767]
### On which page?

ex. https://platform.uno/docs/articles/external/uno.resizetizer/doc/using-uno-resizetizer.html

### What's wrong?

When I click through the tabs, they sometimes don't get properly deselected. 

https://github.com/unoplatform/uno/assets/78549750/7530f3a7-f50f-42b0-86bd-330d246c3d7c

**Comment by morning4coffe-dev** [comment]
CC @sasakrsmanovic

**Comment by agneszitte** [comment]
fyi @jeromelaban, @nickrandolph

**Comment by agneszitte** [comment]
@morning4coffe-dev  Not happening anymore with the latest changes (prod or staging).
I will close this issue but feel free to re-open it with more details if you are still noticing the issue.
