### ISSUE TITLE
`unoapp-uwp-net6` is no longer net6

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#14775]
### Current behavior

Currently, there is no `unoapp-uwp` template, and `unoapp-uwp-net6` is actually net7.0

We should rename `unoapp-uwp-net6` to just `unoapp-uwp`

**Note**: This issue is intentionally in the main repo rather than `Uno.Templates` repo. It requires cross-repo changes, including changes to https://github.com/unoplatform/uno/tree/53019630e7edca315e82cad97308d5379db2f069/src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-uwp-net6, and changes in Uno.Templates as well as updating the wizard.

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
The templates have been moved to uno.templates, this will be adressed there.
