### ISSUE TITLE
Image does not inherits from FrameworkElement

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#1477]
## What would you like to be added:
The `Image` control should inherit from `FrameworkElement` instead of `UIImageView` on iOS and `ImageView` on Android

## Why is this needed:
To be able to manipulate images like any other controls

## For which Platform:
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows

## Notes:
This needs to be fixed prior to https://github.com/unoplatform/uno/issues/401

**Comment by francoistanguay** [comment]
Fixed in 3.0
