### ISSUE TITLE
[Docs] Unfinished Hot Reload page 

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#14797]
### On which page?

https://platform.uno/docs/articles/uno-development/uno-internals-hotreload.html

### What's wrong?

![image](https://github.com/unoplatform/uno/assets/78549750/2ed367d6-4dda-4d22-a04f-e129e112d72e)

### Any feedback?

Internal discussion [Uno Teams](https://teams.microsoft.com/l/message/19:787ad1de1af24252b9041bcbd4ec1ca3@thread.tacv2/1701740910865?tenantId=a297d6c0-b635-41a3-b1e3-558efe71e413&groupId=f55cdec8-036b-4efa-8e1a-c4129ba9bf12&parentMessageId=1701740910865&teamName=Uno%20Platform&channelName=Docs%20and%20Getting%20Started&createdTime=1701740910865)

**Comment by agneszitte** [comment]
cc @jeromelaban

**Comment by jeromelaban** [comment]
This is expected, this is an internal dev hot reload page. There's now a top-level redirection to the user-facing docs.
