### ISSUE TITLE
[WASM] It is no longer possible see selected `TextBox` content

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#14806]
### Current behavior

It seems the selection highlight is not functional in WASM:

![selection](https://github.com/unoplatform/uno/assets/1075116/d191fb11-4dc4-4782-ae73-ae37bae56cf9)

It seems that the highlight itself is invisible and hence it is not possible to see which part of the text is selected. But the selection does happen still.

### Expected behavior

Should work correctly.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
@MartinZikmund is this in firefox?

**Comment by jeromelaban** [comment]
Maybe related to https://github.com/unoplatform/uno/pull/14132 ? This was merged yesterday. @Youssef1313

**Comment by Youssef1313** [comment]
Maybe could be related.

**Comment by MartinZikmund** [comment]
Retested in different browser, and it works. Apparently it is a bug in my Edge version! 😅

**Comment by Youssef1313** [comment]
@MartinZikmund Nice Edge bug timing with the recent change #14132 😄

**Comment by jeromelaban** [comment]
This is failing for me on the latest edge dev, I'll test the canary to see if it's there as well.

**Comment by jeromelaban** [comment]
It's broken in Edge Canary (121.0.2275.0), Chrome Canary (122.0.6182.0)

**Comment by Youssef1313** [comment]
Doesn't repro in Edge 120.0.2210.61 (Official build) (64-bit) 👀

**Comment by jeromelaban** [comment]
Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1504444

**Comment by jeromelaban** [comment]
Related to https://github.com/w3c/csswg-drafts/issues/6641 as well.

**Comment by jeromelaban** [comment]
[Per this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=1504444#c26), the chromium change has been moved back to experimental flags. Verified working in Chrome Canary 122.0.62000.0.

**Comment by MartinZikmund** [comment]
https://github.com/orgs/community/discussions/50295#discussioncomment-5574958 just more information I found, weird one
