### ISSUE TITLE
How\where to configure BaseURL for Wasm app that uses WasmHttpHandler

### ISSUE THREAD

**Issue by wallyh010** [unoplatform/uno#1481]
How\where to configure BaseURL (http://localhost:8080) for Wasm app that uses WasmHttpHandler?
Something like App.config or Web.config?
Is there a file in \bin\Debug\netstandard2.0\dist that can be configured for example?

And once the value is configured, how is it loaded in App.xaml.cs ?

Sorry to ask about something that should be so simple, but I've read the documentation, looked at the examples and cannot see where application configuration is done. I have an app that successfully calls a Web API 2 REST service.  This app and related service works on my local IIS server, but I want to deploy it to a test server, but in order for this to work, I need to be able to configure the BaseURL for the REST API.  Thanks.

- what version of uno and what platforms you are using it with?
Uno.UI (1.46.214-dev.2589)

- what do you like?
Ease of UI development

thanks.

**Comment by ghuntley** [comment]
Howdy @wallyh010, thanks so much for opening up the issue. It's actionable feedback to the team that documentation needs to improve. 👍 

Over at https://github.com/nventive/Uado you'll find an application which demonstrates how to conditionally switch HttpHandlers on a per-platform basis. We'll be moving it shortly over to https://github.com/unoplatform to improve discoverability:

![image](https://user-images.githubusercontent.com/127353/64324080-06dde800-d009-11e9-9da0-5a716fec923a.png)

Key snippets that you'll find interesting and show you how to do a rest client w/baseurl configuration:
- https://github.com/nventive/Uado/blob/master/src/Uno.AzureDevOps/Uno.AzureDevOps.Shared/Framework/Http/UnoHttpClientHandler.cs
- https://github.com/nventive/Uado/blob/master/src/Uno.AzureDevOps/Uno.AzureDevOps.Shared/Module.cs#L26

Over at https://github.com/unoplatform/uno/blob/master/src/Uno.UI.Wasm/WasmHttpHandler.cs you'll find the implementation where looking at the base type reveals that - `WasmHttpHandler : HttpMessageHandler` is a standard HttpClient primitive which means you can do things such as:

- https://thomaslevesque.com/2016/12/08/fun-with-the-httpclient-pipeline/
- https://github.com/ghuntley/HttpClientDiagnostics

**Comment by ghuntley** [comment]
If you have any other q's about documentation, please raise a new GitHub issue. I'm going to leave this one open as `help wanted`. Our documentation is over at https://github.com/unoplatform/uno/tree/master/doc - if this helped we'd <3 a documentation pull-request.

**Comment by wallyh010** [comment]
I see that UnoHttpClientHandler conditionally inherits from a Wasm, IOS or Android HttpClientHandler; however, the URI for the BaseAddress for the associated HttpClient is created using hard-coded internal constants which are compiled into the code which is what I don't want.

public const string AzureDevOpsRepositoryPath = "https://dev.azure.com/"; //<-- Configure externally
public const string BaseAzureDevOpsApiUrl = "https://app.vssps.visualstudio.com/";<-- Configure externally

I am not using azure and the BaseAddress may change depending on the environment in which the application is hosted.  

I want to store values like "https://dev.azure.com/" and "https://app.vssps.visualstudio.com/" externally in some sort of editable text file such as .config, .json or .xml so these values can be changed depending the on the deployment hosting target.

Thanks.

**Comment by ghuntley** [comment]
Ah, so you are after insights how to do https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationmanager.appsettings but on WebAssembly?

**Comment by wallyh010** [comment]
Something like that; however, I don't think ConfigurationManager works in UWP applications and therefore will not work in the Wasm app either.  My research indicates that a possible solution involves adding a configurable text file to Assets; however, this strategy has failed because StorageFile.GetFileFromApplicationUriAsync is not implemented in Uno.Ui. 
The following blog article describes what I'm trying to accomplish, but with the Wasm head.  
https://johnthiriet.com/xamarin-loading-a-configuration-file/#
Thanks.

**Comment by ghuntley** [comment]
There's no support for post-compile AppSettings at this point, but we cadd support for it in the [bootstrapper](https://github.com/unoplatform/Uno.Wasm.Bootstrap). https://github.com/unoplatform/uno/issues/1500 has been raised to track this.

**Comment by wallyh010** [comment]
Thank you for your time in addressing this issue.

**Comment by ghuntley** [comment]
Have been thinking about this some more. It's possible to pass in configuration into webassembly applications via the query string. It's not ideal but if you are looking for a solution right now do something like this:

```csharp
if (!string.IsNullOrWhiteSpace(e.Arguments))
{
  var parameters = HttpUtility.ParseQueryString(e.Arguments);
  var theme = (parameters.GetValues("Theme") ?? parameters.GetValues("theme"))?.FirstOrDefault();
  if(theme != null)
  {
    Uno.UI.ApplicationHelper.RequestedCustomTheme = theme;
  }
}
```

This was lifted from the calculator app.

**Comment by wallyh010** [comment]
Do you know if there is a way to get the hostname (my.domain.com) from a WebAssembly application?

**Comment by wallyh010** [comment]
This works:
During deployment, update uno-config.js to include:
    config.environmentVariables["hostname"] = "my.domain.com";

In App.OnLaunch() call:
    var hostName = Environment.GetEnvironmentVariable("hostname");

**Comment by yowl** [comment]
If you want the url where your wasm comes from you could do:
```
            var indexUrl = Uno.Foundation.WebAssemblyRuntime.InvokeJS("window.location.href;");
            Console.WriteLine(indexUrl);
            var distIndex = indexUrl.IndexOf("wasm/netstandard2.0/dist/");
            var baseUrl = distIndex > -1 ? indexUrl.Substring(0, distIndex) : indexUrl;
```
With some stripping to get up to where your index.html is.

**Comment by wallyh010** [comment]
That's awesome! I was just looking for "javascript interop" today for this very reason, but could not find the details for how to do it.  Thanks for that solution.

**Comment by wallyh010** [comment]
An alternative method for getting the base url of the running Wasm app:

`        private static string GetBaseUrl()
        {
            var baseUrl = BaseUrl;
#if __WASM__
            var indexUrl = Uno.Foundation.WebAssemblyRuntime.InvokeJS("window.location.href;");
            Uri uri = new Uri(indexUrl);   
            baseUrl = $"{uri.Scheme}://{uri.Host}:{uri.Port}";
#endif
            return baseUrl;
        }
`

**Comment by ghuntley** [comment]
> If you want the url where your wasm comes from you could do:
> 
> ```
>             var indexUrl = Uno.Foundation.WebAssemblyRuntime.InvokeJS("window.location.href;");
>             Console.WriteLine(indexUrl);
>             var distIndex = indexUrl.IndexOf("wasm/netstandard2.0/dist/");
>             var baseUrl = distIndex > -1 ? indexUrl.Substring(0, distIndex) : indexUrl;
> ```
> 
> With some stripping to get up to where your index.html is.

Thanks for sharing!

**Comment by francoistanguay** [comment]
Pretty sure this is resolved.
