### ISSUE TITLE
Platform AWS Amplify WASM Uno Code Maintenance

### ISSUE THREAD

**Issue by davidconoh** [unoplatform/uno#14856]
### On which page?

https://reads.davidconoh.me/hosting-uno-platform-wasm-on-aws-amplify/

### What's wrong?

It's been a while since the last maintenance notice on the subject tutorial linked to Hosting Uno Platform WASM on AWS Amplify by David Onoh logged:

![nventive_platform_aws_wasm_uno_maintenance_issue_thumbnail_davidconoh](https://github.com/unoplatform/uno/assets/20891707/c42ee474-5785-46c5-bc76-1a2f8a476963)

```
Developer note: It doesn't work on my computer.
```

A FEW UPGRADE DETAILS:
- Investigate, refactor and update codebase to support the latest version of the underlying .NET SDK toolkit for deployment and pull request.
- Update documentation and links to point to a more robust and accessible resource for promotion and marketing.

For further reference moving forward, more details have been submitted to corporate for investigation and as required_

### Any feedback?

More details have been submitted to corporate for investigation and as required, for further reference moving forward.

**Comment by davidconoh** [comment]
@sasakrsmanovic and @mtmattei always sending me newsletter on other baclayed complains... Who's gonna fix this?! ⚠️

**Comment by MartinZikmund** [comment]
@davidconoh as this is a community tutorial, we don't have influence over its content. If you need a more up to date version, the author will need to update the linked article, so the best way forward would probably be to contact the author directly.
