### ISSUE TITLE
[WASM] HttpClient response content is blocked until full content received

### ISSUE THREAD

**Issue by lld1995** [unoplatform/uno#14872]
### Current behavior

```
HttpClient req = new HttpClient();
HttpResponseMessage res = null;
if (method == "POST")
{
    HttpRequestMessage hrm = new HttpRequestMessage();
    hrm.Method = HttpMethod.Post;
    hrm.RequestUri = new Uri(url);
    HttpContent hc = null;
    if (argDic == null)
    {
    }
    else
    {
        byte[] b = Encoding.UTF8.GetBytes(argDic.ToJson());
        hc = new ByteArrayContent(b);
        hrm.Content = hc;
        hc.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");
    }
    res = await req.SendAsync(hrm,HttpCompletionOption.ResponseHeadersRead);
}
else
{
    res = await req.GetAsync(new Uri(url));
}
Console.WriteLine("try get stream...");
s = await res.Content.ReadAsStreamAsync();
Console.WriteLine("get stream ok");
```

When server send part of body, res can get immediately ,but await res.Content.ReadAsStreamAsync() is blocked until end.

### Expected behavior

Same as WPF/GTK/....   It can get part of content during the request.

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. 

This API is coming from the .NET SDK, and Uno does not have control over it. There may already be an issue in the https://github.com/dotnet/sdk repo, we suggest to search there.
