### ISSUE TITLE
Contribution Gitpod Fails to Initialize

### ISSUE THREAD

**Issue by SerratedSharp** [unoplatform/uno#14899]
### On which page?

https://platform.uno/docs/articles/features/working-with-gitpod.html

### What's wrong?

When opening this gitpod in "Contributing to Uno using Gitpod":
![image](https://github.com/unoplatform/uno/assets/97156524/90bde0ff-7234-4d9f-998b-f2c1b4370428)

I get this error while it is initializing.  I've tried deleting and recreating workspace with same result.
![image](https://github.com/unoplatform/uno/assets/97156524/f0bb108f-867c-4b9e-b40f-e7cc8f36da02)

I also tried selecting larger image with same result:
![image](https://github.com/unoplatform/uno/assets/97156524/bdf1b8f4-7019-47a6-8b5f-34d5d196926e)

Can anyone else confirm they are getting same issue with this Gitpod?

**Comment by DevTKSS** [comment]
@jeromelaban as I am currently researching for using docker, I seen the gitpod uno docs are still stating the https://github.com/gitpod-io/gitpod/issues/5090 which is here on on their side closed. could we get the docs for this updated?
