### ISSUE TITLE
Subscribing to `EffectiveViewportChanged` in `ContentPresenter` will break `VerifyPipsPagerButtonUIABehavior`

### ISSUE THREAD

**Issue by ramezgerges** [unoplatform/uno#14925]
### Current behavior

Merely adding `EffectiveViewportChanged += (_, _) => { }` to the constructor in ContentPresenter.skia.cs will break the runtime test `VerifyPipsPagerButtonUIABehavior`. I've failed to pinpoint the exact cause of the problem. This arose while debugging #14783. I haven't tested whether this is a problem only when subscribing in the constructor, or if it's a more general problem. I also haven't tested whether this is a problem on other (not skia) platforms.

### Expected behavior

VerifyPipsPagerButtonUIABehavior should still pass.

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
Lifecycle changes **may** have an effect here.

**Comment by Youssef1313** [comment]
@ramezgerges Can you re-test this with latest master?

**Comment by ramezgerges** [comment]
Seems to be working fine now.
