### ISSUE TITLE
Implement Windows.UI.Input.PointerUpdateKind

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1492]
## What would you like to be added:

https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.pointerupdatekind

## Why is this needed:

https://github.com/unoplatform/Uno.Xamarin.Forms/pull/9#discussion_r321335826

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

## Anything else we need to know?

https://github.com/unoplatform/uno/blob/master/src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Input/PointerUpdateKind.cs

**Comment by dr1rrb** [comment]
The implementation is done in https://github.com/unoplatform/uno/issues/1492
