### ISSUE TITLE
Wasm: ContentDialog Closing support

### ISSUE THREAD

**Issue by yowl** [unoplatform/uno#1494]
## What would you like to be added:
The Closing event
## Why is this needed:
To get parity with UWP and allow scenarios where the closing should be prevented

## For which Platform:

- [ ] iOS
- [ ] Android
- [x ] WebAssembly
- [ ] Windows

## Anything else we need to know?

See https://github.com/yowl/UnoStandardRefTest2/tree/contentdialog-closing for an example

**Comment by ghuntley** [comment]
Looks like GitHub raised two issues during creation. Closing this as duplicate of https://github.com/unoplatform/uno/issues/1495
