### ISSUE TITLE
Add support for `CalendarView`

### ISSUE THREAD

**Issue by yowl** [unoplatform/uno#1496]
## What would you like to be added:
CalendarView https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.CalendarView

## Why is this needed:
There is no alternative giving a similar compact view

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows

**Comment by ghuntley** [comment]
`CalendarView` isn't [currently implemented on any platform](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/CalendarView.cs). Noted, your preference for `WebAssembly` first.

**Comment by yowl** [comment]
I'll see if the Telerik one will come up.

**Comment by yowl** [comment]
Telerik progress can be seen in https://github.com/unoplatform/uno/issues/1550
