### ISSUE TITLE
[WASM] Suggestion is not selected when pressing down arrow key in suggestion list of AutoSuggestBox

### ISSUE THREAD

**Issue by TopProgrammer77** [unoplatform/uno#14965]
### Current behavior

This is the AutoSuggestBox issue on WASM.
When typing keyword to text box of AutoSuggestBox, SuggestionList popup will come.
Here, when I press down arrow key once, the first suggestion isn't selected. 
But then when I press up arrow key, last suggestion is selected. 
As a result, the down arrow key doesn't work in suggestion list of AutoSuggestBox

### How to reproduce it (as minimally and precisely as possible)

[1.zip(updated)](https://github.com/unoplatform/uno/files/13861864/1.zip)

### Works on UWP/WinUI

None

### NuGet package version(s)

5.1.0-dev.1219

**Comment by DierkDroth** [comment]
@jeromelaban @MartinZikmund this is a regression on UNO 5.1.latest vs. UNO 5.0 where it worked no problem. Fortunately my tester and @TopProgrammer77 found and isolated the issue before 5.1 was released.

**Comment by ramezgerges** [comment]
I couldn't reproduce this. The linked repro has nothing to do with AutoSuggestBox, so I suspect it's linked incorrectly. @TopProgrammer77 @DierkDroth please revise the issue.

**Comment by DierkDroth** [comment]
@ramezgerges I just tried the ZIP file which @TopProgrammer77 attached above: it appears to be the wrong ZIP file.

@TopProgrammer77 could you please double check and make sure you uploaded the correct repo file? Thanks

**Comment by TopProgrammer77** [comment]
@ramezgerges , @DierkDroth 
Sorry I uploaded wrong repo before.
I updated it. https://github.com/unoplatform/uno/files/13861864/1.zip

**Comment by DierkDroth** [comment]
Thanks @TopProgrammer77 

@ramezgerges can you now reproduce the issue?

**Comment by ramezgerges** [comment]
Yes, thanks.

**Comment by DierkDroth** [comment]
Great! Thanks for your feedback @ramezgerges and sorry for the confusion.
