### ISSUE TITLE
Replace `SamplesApp.UWP.Design` with a `WinUI.Design` project

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#14987]
### What would you like to be added

The project is no longer useful - either should be removed completely, or replaced by a `WinUI.Design`

**Comment by Youssef1313** [comment]
It may still be needed in case VS IntelliSense didn't work nicely though. 😕

**Comment by MartinZikmund** [comment]
Yes, I think IntelliSense could be the main reason to keep it, but not sure how much of a use is there for it (you can still build the sample within Windows slnf

**Comment by jeromelaban** [comment]
It was needed because of shared projects, but it may not be needed anymore with winui 3.
