### ISSUE TITLE
Run runtime tests in Fluent theme context

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#15005]
### What would you like to be added

We are currently running runtime tests in UWP styles context by default. These styles are not actually used by 99% of the apps, so it may make more sense to make fluent the default, and switch to UWP only when needed (opposite of what we are doing now)

### Why is this needed

Better test coverage

**Comment by MartinZikmund** [comment]
Do you agree @jeromelaban @Youssef1313 @ramezgerges?

**Comment by Youssef1313** [comment]
Yeah I think that makes sense.

**Comment by jeromelaban** [comment]
It probably will make sense to switch to fluent altogether, I don't think anyone uses the system theme now for uwp.
