### ISSUE TITLE
[Docs] long link without a break in TIP can cause bad rendering

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#15049]
> Probably not much related to those changes, but I am seeing some differences in sizing:
>
> ![image](https://github.com/unoplatform/uno/assets/78549750/c8fc12a8-302f-48b6-ae97-18213eaceaeb)
>
> master:
>
> ![image](https://github.com/unoplatform/uno/assets/78549750/628934a8-a5a7-478c-afd4-04b87a13cfad)

_Originally posted by @morning4coffe-dev in https://github.com/unoplatform/uno/issues/15026#issuecomment-1889906846_

**Comment by agneszitte** [comment]
(We moved away from bare links for hyperlinks in this PR for Uno core https://github.com/unoplatform/uno/pull/15122)
But in case for some reason we have another one, this will need to be fixed at the doc website styling level.

**Comment by agneszitte** [comment]
Similar issue here where we moved away from bare links until a proper fix/solution is found:
https://github.com/unoplatform/uno.extensions/pull/2156

**Comment by agneszitte** [comment]
Closing this issue as the mentioned ones are now fixed. We would be able to open another issue in case additional ones are found.
