### ISSUE TITLE
`OnNavigatedFrom` is not called when moving away from `RatingControlPage` sample causing a leak

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#15059]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/31348972/a9e6034c-6b45-48d0-b618-0a5c67115ef6)

This is not hit causing a memory leak.

### Expected behavior

It should probably be hit.

Or, if it's correct behavior that it's not hit, we should unsubscribe in Unloaded

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
This is a composite issue.

1. We are serializing `SampleChooserContent` array for recent samples to save recents when the app is next opened. The property `UsesFrame` has an internal setter and that causes issues with Newtonsoft.Json failing to set UsesFrame properly. We end up having the sample with UsesFrame in that case. This is unlikely to be an issue for CI I think. What happens in local dev is first open of `RatingControlPage` happens with frame navigation properly, and it's serialized properly to `SampleChooserFileAddress.Samples.LRU`. Then, if you close and re-open samples app and try to open it from recents, it won't open with frame navigation, and if you opened another sample to force serializing, it will be serialized incorrectly this second time. This is easy to fix.
2. Even when it's opened with frame navigation, it's leaking because we create new frame for every page we navigate to, and not re-using the same frame. This means that we are not going to get `OnNavigatedFrom`.

**Comment by MartinZikmund** [comment]
Great catch! I would say we don't necessarily need to reuse the frame, but need to make sure to navigate away from the sample when we are switching to something else (e.g. by setting `Content = null` on the frame)
