### ISSUE TITLE
Warn the user when `skia:` and `wasm:` prefixes are used in non-cross-runtime library

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#15064]
### Current behavior

When the user applies `skia:` and `wasm:` prefixes in a non-cross-runtime library, it will not be applied correctly. We should either prevent or at least warn the user about this.

### Expected behavior

User should be informed

### Works on UWP/WinUI

None

**Comment by MartinZikmund** [comment]
Closely related to #15021 as well

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/pull/15217#issuecomment-2073264757
