### ISSUE TITLE
docs / ci: Update CI to include the creation of intermediary assets required for styling docfx

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#15077]
### What would you like to be added

The source design files should be added to the Uno repo
The docs CI process should be updated to include the transformation of the source design files into the intermediary assets required by docfx 

### Why is this needed

Currently when changes are done to the styling for docs (ie for docfx) there is an external process that's run to generate the new style assets. 

For example this change: https://github.com/unoplatform/uno/pull/14793/files#diff-1c2141a962dfa86e1de7c0348b9fbc041854bb4e473d165e453c8a183152e5ff

It's important that these processes are run as part of the CI pipeline for Uno docs to remove any dependencies on external dev teams/processes

**Comment by agneszitte** [comment]
(Related ticket [here](https://dev.azure.com/nventive/UNO%20Marketing/_workitems/edit/297259/))

**Comment by rfabre** [comment]
I created a PR for that: #16957
