### ISSUE TITLE
[Docs site] Code header doesn't appear when using unknown language identifier on a codefence

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#15084]
### On which page?

No specific page

### What's wrong?

When adding a code snippet with language identifier such as `dotnetcli`, `output`, `text`, `paths`, etc, the code header doesn't appear.

**Comment by agneszitte** [comment]
@Youssef1313 this issue was fixed by https://github.com/unoplatform/uno/issues/15084 but if you noticed any residual issues, please let me know

**Comment by Youssef1313** [comment]
@agneszitte This seem to refer to this issue rather than PR. If you can link the PR for futyre reference that will be great!

**Comment by agneszitte** [comment]
> @agneszitte This seem to refer to this issue rather than PR. If you can link the PR for future reference that will be great!

@Youssef1313 thank you for noticing, I just noticed I copy the wrong link in my previous message
Here is the related PR: https://github.com/unoplatform/uno/pull/16972
