### ISSUE TITLE
ColorPicker is not rendering the color spectrum

### ISSUE THREAD

**Issue by SafeAt-Malc** [unoplatform/uno#15082]
### Current behavior

<img width="274" alt="ColorPicker error" src="https://github.com/unoplatform/uno/assets/128640291/e854b628-f8c9-4ef7-ab7a-0d9280639b97">

Our application was fully working with the Color picker up until we recently updated. The color picker does still function as far as the slider and putting a hex code in, but the spectrum will not display and is not responsive to input. We are using Microsoft.UI.Xaml

We're using Uno version 5.0.118 All NuGet packages are up to date as well.

### Expected behavior

The color picker spectrum should show.

### Workaround

We have not found a workaround.

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
Thanks. We're not reproducing this issue, either with 5.0.118, 5.0.143 or 5.1-dev bits.

Could you:
- Tell which browser you're using, which version, and which OS you're running on?
- Provide portions of the debugger logs of the browser? There may be errors there.
- Tell if you are you running in lockdown/enhanced security modes?

**Comment by jeromelaban** [comment]
Could you also tell if the color picker is working for you here: https://playgroundcanary.z19.web.core.windows.net/#398ee199. This is the uno playground canary with the latest 5.1-dev bits.

**Comment by SafeAt-Malc** [comment]
The playground does render the code and creating a fresh project also renders the color spectrum. It looks like there is something else conflicting with our code, so I will keep troubleshooting. Thank you so much for your time!

**Comment by jeromelaban** [comment]
@SafeAt-Malc thanks for the update! Still, if may be that we're missing something that breaks your app. Could you let me know about the questions I asked in https://github.com/unoplatform/uno/issues/15082#issuecomment-1894364200?

**Comment by SafeAt-Malc** [comment]
-We've built on multiple browsers and OSs including Windows 10 and 11 on Brave v1.61.116 and Chrome v120.0.6099.217
-We do have some errors
<img width="494" alt="Error screenshot 2" src="https://github.com/unoplatform/uno/assets/128640291/6f13c9eb-2da3-4f90-98ba-ff5873f497b8">
<img width="562" alt="Error screenshot" src="https://github.com/unoplatform/uno/assets/128640291/dd5f8696-7e4f-4229-bd05-e9832d49f77a">

-No lockdown or security modes

**Comment by jeromelaban** [comment]
Thanks for the update. This looks like an internal error of the runtime. Did you enable any optimization feature, compile with AOT or similar?

**Comment by SafeAt-Malc** [comment]
We don't have AOT on. We do have "Optimize code" checked on release but not on debug.

**Comment by jeromelaban** [comment]
Are you able to create a repro of the code that is you're using that is causing this issue?

**Comment by SafeAt-Malc** [comment]
My team and I are chasing down some troubleshooting leads right now, so I'll get back on the thread when we find something one way or the other. Thanks!

**Comment by SafeAt-Malc** [comment]
Update on this: We found what seems to be a memory leak related to a binding on an observable collection. It seems like the color picker being bound to this collection was related to the issue and we were able to get it working again.
