### ISSUE TITLE
`When_ThemeChange` is flaky on Wasm

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#15093]
### Current behavior

Test is flaky on Wasm. Disabling in https://github.com/unoplatform/uno/pull/15094.

### Expected behavior

Should be enabled back.

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
Let's merge this issue into #9080

**Comment by Youssef1313** [comment]
Added a bullet point in #9080. Closing this one.
