### ISSUE TITLE
[Droid][WASM] CommandBar isn't visible

### ISSUE THREAD

**Issue by crogeniks** [unoplatform/uno#1509]
## Current behavior

The `Command` bar doesn't show up properly in WASM and Android

- WASM 
-- `Command` bar is visible, but Icons are clipped(not 100% reproducible)
-- 
![image](https://user-images.githubusercontent.com/1256256/64554562-abae3d00-d309-11e9-9a17-8aea66c1ed8c.png)
-- Opening the Secondary Commands does "nothing" and freeze the `CommandBar`

- Android
-- Command bar is visible, but shows the Secondary Commands
-- 
![image](https://user-images.githubusercontent.com/1256256/64554922-4c046180-d30a-11e9-8a65-d93eb2faf96c.png)

## Expected behavior

- WASM
-- don't freeze after opening the secondary commands

- Android
-- Show all AppBarButtons

## How to reproduce it (as minimally and precisely as possible)
Sample project :
[CommandBar.zip](https://github.com/unoplatform/uno/files/3591930/CommandBar.zip)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [ ] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Howdy @crogeniks. 

The clipping on symbols on WebAssembly is likely related to https://github.com/unoplatform/uno/issues/1332 or https://github.com/unoplatform/uno/issues/693. Maintenance of glyphs is currently quite manual and there's a issue open over at https://github.com/unoplatform/uno/issues/967 to automate the processes.

In case you missed it - CommandBar [has two modes](https://platform.uno/docs/articles/controls/CommandBar.html#modes), on Android it can't be fully customized like other templatable controls would. By switching to `XamlDefaultCommandBar` you can replicate UWP's CommandBar. It is templatable and supports a template that's almost identical to UWP's default CommandBar.

Thanks for providing a repro, will need to revisit this at a later date as we are busy [preparing for UnoConf](https://unoconf.com). I see you are from Montreal - will see you there?

ps. The following are worth checking out if you intend to send in a pull-request:

- [CommandBar documentation and quirks](https://platform.uno/docs/articles/controls/CommandBar.html)
- [CommandBar implementation](https://github.com/unoplatform/uno/tree/master/src/Uno.UI/UI/Xaml/Controls/CommandBar)
- [CommandBar integration tests](https://github.com/unoplatform/uno/tree/master/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar)

**Comment by pkar70** [comment]
How can I change CommandBar mode to XamlDefaultCommandBar?

**Comment by pkar70** [comment]
And, in SecondaryCommands, AppBarToggleButton is not shown (only AppBarButton). At least in Android.

**Comment by TopperDEL** [comment]
> How can I change CommandBar mode to XamlDefaultCommandBar?

I've asked me the same Question just a second ago. The documentation talks About different modes, but it is not clear how to set them.

**Comment by ghuntley** [comment]
> How can I change CommandBar mode to XamlDefaultCommandBar?

That's good feedback — have raised issue to improve clarity of the documentation. The modes can be switched between by changing the control templates.

```
<Style TargetType="CommandBar" BasedOn="XamlDefaultCommandBar" />

<Style TargetType="CommandBar" BasedOn="NativeDefaultCommandBar" />
```

The default modes for Uno are configured via https://github.com/unoplatform/uno/blob/935a845df9540d5b626538453a34b815bdebaa83/src/Uno.UI/UI/Xaml/Style/Generic/GenericStyles.cs#L25

**Comment by pkar70** [comment]
But...
`    <Page.Resources>
        <Style TargetType="CommandBar" BasedOn="NativeDefaultCommandBar" />
    </Page.Resources>
`
ends with:
Implicit styles in inline resources are not supported (Page, Line 1:2)

**Comment by davidjohnoliver** [comment]
@pkar70 You need to put it in a standalone `ResourceDictionary` file or in `Application.Resources`.

**Comment by TopperDEL** [comment]
This is still not working for me. It keeps saying "The property Binding.BasedOn is unkown."

**Comment by HaoLife** [comment]
> This is still not working for me. It keeps saying "The property Binding.BasedOn is unkown."

NativeDefaultCommandBar needs conditional compilation, he only supports ios and Android

**Comment by scpc0609** [comment]
If I use the below code, it does compile and code generation fails.
<Style TargetType="CommandBar" BasedOn="NativeDefaultCommandBar" />

If I use the below code, I that does compile but crashes the App at start.
    <xamarin:Style TargetType="CommandBar" xamarin:BasedOn="{StaticResource XamlDefaultCommandBar}"/>

I get exception at runtime: "The resource XamlDefaultCommandBar cannot be found".

What is the proper way to enable XamlDefaultCommandBar.

Also is there a guidance for people who want to create their own implementation of CommandBar without using any of the two variants available?

**Comment by ramezgerges** [comment]
This isn't reproducing for me on Android or WASM, although there is a (probably separate) clipping issue that I just opened.
