### ISSUE TITLE
[skia] Issue with `SKXamlCanvas` - Process Crashes when Exceptions are Thrown in `PaintSurface` Event Triggered by Background Thread

### ISSUE THREAD

**Issue by lindexi** [unoplatform/uno#15123]
### Current behavior

I am writing to report an issue I am experiencing with the use of SKXamlCanvas. The problem arises when any exception is thrown within the PaintSurface event, particularly when this event is triggered by a background thread. This situation leads to a crash of my process.

### Expected behavior

The expected behavior is that the application should continue to function normally and be able to collect the exception, even if any exception is thrown in the PaintSurface event. Ideally, this could be achieved through the TaskScheduler.UnobservedTaskException event.

### How to reproduce it (as minimally and precisely as possible)

To reproduce this issue, please follow the steps below:

1. Add SKXamlCanvas to xaml.
2. Subscribe to the PaintSurface event of SKXamlCanvas and throw an exception in the event implementation method.
3. Call the Invalidate method of SKXamlCanvas from a background thread.

You can find my demo in https://github.com/lindexi/lindexi_gd/tree/dde76effc23ebb9ee974b6ec276b242c39a50bdf/JagobawearjiNeewhiqakerki

### Works on UWP/WinUI

None

### Anything else we need to know?

I fixed the issues in https://github.com/mono/SkiaSharp/pull/2720

Reference: https://github.com/unoplatform/uno/discussions/15097

Reference: https://github.com/dotnet/runtime/issues/76367

**Comment by jeromelaban** [comment]
Background thread manipulations of the `SKXamlCanvas` are not supported at this time.

**Comment by lindexi** [comment]
Thank you @jeromelaban . Fix by https://github.com/mono/SkiaSharp/pull/2720

**Comment by jeromelaban** [comment]
Thanks for the fix!!
