### ISSUE TITLE
The [NotImplemented] attribute is missing from `BottomAppBar`

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1514]
## Current behavior

From https://github.com/unoplatform/uno/issues/1479#issuecomment-529615549

> The documentation is in error on this one. Those docs are built by a tool which looks for the `[NotImplemented]` attribute, which is missing from `BottomAppBar`.
> 
> In reality there's no existing code to support this feature, that's why it counts as an enhancement rather than a bug.

## Expected behavior

1. Inspect https://github.com/unoplatform/uno/tree/master/src/Uno.UI/UI/Xaml/Controls/Page and https://github.com/unoplatform/uno/tree/master/src/Uno.UI/UI/Xaml/Controls/AppBar
1. If the implementation does not exist then for each not implemented member in https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/Page.cs and https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/AppBar.cs add the `[NotImplemented]` attribute.

For example:

```
#if __ANDROID__ || __IOS__ || NET461 || __WASM__ || __MACOS__
		[global::Uno.NotImplemented]
		public  object Example
		{
			get
			{
				return (object)this.GetValue(ExampleProperty);
			}
			set
			{
				this.SetValue(ExampleProperty, value);
			}
		}
		#endif
```

## Environment

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?

Opening this up as a `help wanted` as a super easy issue to introduce new contributors to how the documentation is generated. If this remains open for too long then one of the members of the core team should pick it up and implement.

**Comment by HrushikeshBodas** [comment]
@ghuntley can you assign this to me?

**Comment by ghuntley** [comment]
Welcome @HrushikeshBodas. ICYMI - https://github.com/unoplatform/workshops/blob/master/uno-bootcamp/modules/07-Working-with-Uno/README.md#-walk-through-the-code-base has a bunch of information about the internals of Uno and will be useful knowledge to have as part of sending in a PR.
