### ISSUE TITLE
"●" masking issue when setting FontFamily of PasswordBox control in Non-Windows.

### ISSUE THREAD

**Issue by luckypong** [unoplatform/uno#15156]
### Current behavior

hello.

I'm currently developing with WinUI3 and testing with a non-Windows project, and I'm asking about a masking issue with PasswordBox.

When FontFamily is set to a non-English font and the visual -state becomes normal after entering the password, masking disappears.

The test was conducted in two styles.
1) Default Style
     - Control Style: DefaultPasswordBoxStyle
     - Control FontFamily: non-English(Unicode) OTF Font.
2) Custom Style
     - Control Style: DefaultPasswordBoxStyle2
     -Setter FontFamily: XamlAutoFontFamily
     - PlaceholderTextContentPresenter FontFamily: non-English(Unicode) OTF Font

Is this a bug? Or 2) Please answer whether I should create a Style and use it.
Or is there a problem on MS Xaml side?

https://github.com/unoplatform/uno/assets/11326846/20560952-5398-4bbf-ac97-38392c304043

wasm

PasswordBox
Normal - not showing masking.
Focused - not showing masking.
ContentDialog
Title - not showing string.
NavigationView
Header - showing default fontfamily.
wpf, gtk

PasswordBox
Normal - not showing masking.
Focused - showing masking.
ContentDialog, NavigationView
Title,Header - showing squares not string.
android

Android seems to be fine.
ios, mac

I couldn't test iOS because I don't have a device, but it seems to be the same as Android.

_Originally posted by @luckypong in https://github.com/unoplatform/uno/discussions/14822_

### Expected behavior

Must be implemented identically to PasswordBox on the Window Platform.

### How to reproduce it (as minimally and precisely as possible)

sample app.

[UnoApp5.zip](https://github.com/unoplatform/uno/files/13685579/UnoApp5.zip)

Testing by running on all platforms except Windows.

### Workaround

Applying custom styles breaks Fluent styles.

How to pin the PasswordBox ContentElement element font family to XamlAutoFontFamily.

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI 5.0.143

### Affected platforms

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer)

### IDE

Visual Studio 2022

### IDE version

17.8.5

**Comment by MartinZikmund** [comment]
@ramezgerges added you to check the skia part, but it seems an issue is on Android and iOS too

**Comment by luckypong** [comment]
I think the contentelement fontfamily of passwordbox should be set to xamlautofontfamily because user fonts may not have ●(small)

**Comment by MartinZikmund** [comment]
That makes sense, we could switch to that font family for the dots, and back to the user font family for password reveal

**Comment by ramezgerges** [comment]
@luckypong On fonts that don't have a certain glyph, the textbox should fall back to any font that has the glyph available (such as the default font). I see that the repro is using an early 5x version. Could you please upgrade to the latest packages and try again? I tested in a new app and it doesn't reproduce.

**Comment by luckypong** [comment]
@ramezgerges This time, I tested it because I was planning to distribute it as an Android app, but it is still not displayed in version 5.1.75.

![image](https://github.com/unoplatform/uno/assets/11326846/0eb08c4e-f51a-4f10-9551-6ff6bae01933)

**Comment by ramezgerges** [comment]
@luckypong Is that on Skia? I just changed your repro app to use 5.2.0-dev.1280 and it works fine, although it seems that there's an unrelated font size issue.

**Comment by luckypong** [comment]
Hello, @ramezgerges
The problem occurred on Skia, Android, etc., but not on WinUI Windows platforms.
The screenshot above appears to have been confirmed in WPF.

FontFamily is being bypassed by forcibly setting XamlAutoFontFamily.

**Comment by ramezgerges** [comment]
Can I get a repro app? The one above seems to work fine with 5.2.0-dev.1280.

**Comment by ramezgerges** [comment]
Update on the font size problem. Surprisingly, it's not a problem. It's just that `GyeonggiTitleOTF_Light` has ridiciously large bullet flyphs.

**Comment by luckypong** [comment]
Hello, @ramezgerges 

sample repro app.

[UnoApp8_Sample.zip](https://github.com/unoplatform/uno/files/14504249/UnoApp8_Sample.zip)

**Comment by ramezgerges** [comment]
As mentioned above, the new sample doesn't work with the older 5.1.65 version, but works with 5.2.

**Comment by luckypong** [comment]
We will use the trial version for internal testing, and for the distribution version we will force FontFamily settings as mentioned above.
I think it will be necessary to update when a stable version is released in the future.
Thank you. @ramezgerges
