### ISSUE TITLE
Add support for `SkiaVisual`

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#15166]
### What would you like to be added

Add support for a composition level `SkiaVisual`, which can allow third parties to use `SkiaSharp` in a constrained visual.

### Why is this needed

Faster implementation of the `SKXamlCanvas`, and hardware acceleration for such controls, or custom visuals based on `SkiaVisual`.

### Anything else we need to know?

Such an API cannot be provided at the XAML level for threading concerns.

A similar implementation for a visual is [`TextVisual`](https://github.com/unoplatform/uno/blob/6fe692ccbff5a7ba25f2e0c9ca85002daad8cc6d/src/Uno.UI/UI/Xaml/Controls/TextBlock/TextVisual.skia.cs#L21), for which there's currently no publicly available API.

**Comment by lindexi** [comment]
Before the SkiaVisual added, we can use the hack code to implemente the same functionality. The demo code: https://github.com/lindexi/lindexi_gd/tree/5db72c3d67f121becefb5c4e8a0eacd5099c4198/KefalurcilaybelJallbuderenajel

See https://github.com/unoplatform/uno/discussions/15097#discussioncomment-8169007

**Comment by jeromelaban** [comment]
Thanks for the update. The hack you're suggesting is about exposing an API that is not meant to be exposed in the first place. We need a `SkiaVisual` in order for Uno.WinUI to expose an API that SkiaSharp and any other animplementation can use reliably.

**Comment by lindexi** [comment]
Good job!

**Comment by agneszitte** [comment]
@jeromelaban, @rafael-rosa-knowcode can @jhanvi03 or @Darsh0307 should test the sample app for this new support?

**Comment by jeromelaban** [comment]
@agneszitte yes, the uno samples app contains a new sample for WPF and X11.

**Comment by ramezgerges** [comment]
@agneszitte @jeromelaban Not yet. The work is pretty much done but I removed it from #16621 because the PR was getting too big and we wanted to merge the GLCanvasElement work. I will open another PR for SKCanvasElement.

**Comment by agneszitte** [comment]
Thanks for the info @ramezgerges, let them know when it will be ready for QA when it will be done please
I imagine this will be the same answer for https://github.com/unoplatform/private/issues/349#issuecomment-2334164149 ?
