### ISSUE TITLE
Graduate these repositories from nventive to unoplatform on GitHub

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1522]
## What would you like to be changed:

For each one of these GitHub repositories move them to the `unoplatform` organization.

First pass:
- [x] https://github.com/nventive/Uado
- [x] https://github.com/nventive/Uno.CodeGen
- [x] https://github.com/nventive/Uno.Core
- [x] https://github.com/nventive/Uno.PackageDiff
- [x] https://github.com/nventive/Uno.MonoAnalyzers

Second pass:
- [ ] https://github.com/nventive/Elmish.Uno
- [ ] https://github.com/nventive/Uno.BenchmarkDotNet
- [ ] https://github.com/nventive/Uno.ColorCode-Universal
- [ ] https://github.com/nventive/Uno.Diagnostics.Eventing
- [ ] https://github.com/nventive/Uno.GettingStartedTutorial
- [ ] https://github.com/nventive/Uno.LottieSample
- [ ] https://github.com/nventive/Uno.MvvmCross
- [ ] https://github.com/nventive/Uno.Prism
- [ ] https://github.com/nventive/Uno.RayTraceBenchmark
- [ ] https://github.com/nventive/Uno.ReactiveUI
- [ ] https://github.com/nventive/Uno.Roslyn
- [ ] https://github.com/nventive/Uno.RoslynQuoter
- [ ] https://github.com/nventive/Uno.RoslynTransform
- [ ] https://github.com/nventive/Uno.Rx.NET
- [ ] https://github.com/nventive/Uno.SQLitePCLRaw.Wasm
- [ ] https://github.com/nventive/Uno.UI.Sample.Banner
- [x] https://github.com/nventive/Uno.UI.Toolkit.SL
- [ ] https://github.com/nventive/Uno.UITests.Helpers
- [ ] https://github.com/nventive/Uno.WindowsStateTriggers
- [ ] https://github.com/nventive/Uno.Xaml-Controls-Gallery
- [ ] https://github.com/nventive/Uno.XamlBehaviors
- [ ] https://github.com/nventive/Uno.sqlite-net
- [ ] https://github.com/nventive/Uno.sqlite-wasm
- [ ] https://github.com/nventive/uno.mvvmlight

## Why is this needed:

Complete the move to the unoplatform organization and improve discoverability of these repositories.

## Anything else we need to know?

If the repository is active, move the repository and re-setup CI.

If the repository is inactive or should be retired, move the repository, update the README.md with directions and then enable the GitHub archive mode on the repository.

**Comment by MatFillion** [comment]
I triaged the most urgent ones to the top of the list and removed docker.

**Comment by jeromelaban** [comment]
First pass is done.

**Comment by jeromelaban** [comment]
The projects have been moved.
