### ISSUE TITLE
[Gallery][iOS][MediaPlayerElement]- App crashes when click Close(X) button for any of the MediaPlayerElementSample option.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#15254]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/61f5fd04-bdd0-4c66-bb69-60105526fea3

### Expected behavior

App should not crashes and the screen should close when click close button.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right (if the menu is not already opened)
3. Click "MediaPlayerElement" from the "UI Components" list.
4. Launch the first or second sample.
5. Click close(X) button on the top left side.
6. Notice that not able to do any thing on the app.
7. close the app and try to reopen it.
8. Notice that get message , 'Uno Gallery crashed'

### Works on UWP/WinUI

None

### Affected platforms

iOS

**Comment by jeromelaban** [comment]
Verified cause by https://github.com/unoplatform/uno/pull/14492 (FYI @Youssef1313)

**Comment by jeromelaban** [comment]
https://github.com/unoplatform/uno/pull/15361 fixes part of the issue, but there is still a layout loop issue with an unstable layout calculation that invokes `OnVideoRectChanged` continuously, causing a freeze of the app:

https://github.com/unoplatform/uno/blob/0b961e5ec81b2dc6862355b48ce24efafe5d66cb/src/Uno.UWP/Media/Playback/MediaPlayer.iOSmacOS.cs#L390-L398

Scheduling the raise of `NaturalVideoDimensionChanged` makes the app not freeze, but still continuously calculates new sizes.

**Comment by ajpinedam** [comment]
The issue occurs when using a MPE inside the ShowMeTheXAML and the Height is not explicitly set.

ShowmeTheXaml is a ContentControl with some logic to show the XAML set as the Content. It might also be reproducible from regular ContentControl.
