### ISSUE TITLE
[Android] Canvas resource crashes application with NullPointerException

### ISSUE THREAD

**Issue by Asfiroth** [unoplatform/uno#15279]
### Current behavior

when adding a Canvas resources and debugging the application on android it crashes whit this error `java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference`. On iOS applications deploys and shows as expected.

### Expected behavior

On Android it should take the resource and render it as it does on iOS.

### How to reproduce it (as minimally and precisely as possible)

Sample app to test 
[CanvasAndroidIssue.zip](https://github.com/unoplatform/uno/files/14105153/CanvasAndroidIssue.zip)

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia, Uno.UI.DevServer / Uno.WinUI.DevServer

### NuGet package version(s)

"Uno.WinUI" Version="5.1.31"
"Uno.WinUI.DevServer" Version="5.1.31"

### Affected platforms

Android

### IDE

Rider macOS

### IDE version

2023.3.3

**Comment by jeromelaban** [comment]
Thanks for the report.

While this is not necessarily expected for this particular XAML to fail this way, it's generally not a good practice to place UIElement directly in a resource dictionary, as they may end up being placed in multiple parents causing a failure at this time.

It's generally best to wrap the content in a `DataTemplate` which is then included in the dictionary. It is then used as a `ContentControl.Template` and can be so multiple times on screen.

**Comment by Asfiroth** [comment]
Hi @jeromelaban, 
thanks for the answer, I'll try it that way to check if the issue persists.

**Comment by Asfiroth** [comment]
Hi @jeromelaban

I tried this approach and wrapped the canvas in a `DataTemplate`, now I got this error: `System.NotSupportedException: TypeConverter cannot convert from Microsoft.UI.Xaml.DataTemplate.` for Android, iOS, MacCatalyst.
Also tried wrapping the Canvas inside a `Viewbox` to see if it made any change but got same result.

Refer to this project [CanvasAndroidIssue.zip](https://github.com/unoplatform/uno/files/14112993/CanvasAndroidIssue.zip)

**Comment by jeromelaban** [comment]
My apologies, I wrote `ContentControl.Template`, but it should have been `ContentControl.ContentTemplate`.

**Comment by Asfiroth** [comment]
Yes, it was odd to have `Template` property there. Anyway that did the trick, thanks a lot.
