### ISSUE TITLE
Lottie Implementation

### ISSUE THREAD

**Issue by mcocaroUX** [unoplatform/uno#15295]
### On which page?

https://platform.uno/docs/articles/features/Lottie.html?tabs=winui

### What's wrong?

I'm working on a proyect using WinUI. I installed Uno.WinUI.Lottie but it does not contain a definition for LottieVisualSource. Is that the correct package?

**Comment by jeromelaban** [comment]
The namespace in the docs in correct. Searching for the namespaces for this type, you'll find it's here:


https://github.com/unoplatform/uno/blob/e3b635dfc5bdceb810df048e2383f92622664928/src/AddIns/Uno.UI.Lottie/LottieVisualSource.cs#L10

**Comment by Youssef1313** [comment]
If you are referring to the WinAppSDK project, you need to use `CommunityToolkit.WinUI.Lottie` package instead.
