### ISSUE TITLE
Flyout Wont work on Wasm / SKIA

### ISSUE THREAD

**Issue by iurycarlos** [unoplatform/uno#15291]
### Current behavior

Flyout is failing to appear right after 5.1 update.
 

### Expected behavior

Flyout should appear as expected.

### How to reproduce it (as minimally and precisely as possible)

1. Update UNO-Check
2. Run uno-check to make sure to have the latest template
3. Create a sample app and add a button with a flyout. In my case I just added a TextBlock inside the flyout.
   ``` xml
      <Button Content="Bottom">
        <Button.Flyout>
          <Flyout Placement="Bottom" >
            <TextBlock Text="Testing the Flyout" Foreground="Red" />
          </Flyout>
        </Button.Flyout>
      </Button>
      <Button Content="Top">
        <Button.Flyout>
          <Flyout Placement="Top" >
            <TextBlock Text="Testing the Flyout" Foreground="Red" />
          </Flyout>
        </Button.Flyout>
      </Button>
      <Button Content="None">
        <Button.Flyout>
          <Flyout>
            <TextBlock Text="Testing the Flyout" Foreground="Red" />
          </Flyout>
        </Button.Flyout>
      </Button>
   ```
   [SNIPPET IN PLAYGROUND](https://playground.platform.uno/#8131614b)
4. Run it on Skia (to have console logs easily)
5. Right after clicking the button you will got an error like:

![image](https://github.com/unoplatform/uno/assets/6876973/82b2a0aa-c1ac-4dc7-919f-7accb3c2f982)

Important and curiously:

If you resize the window, you will get the following message at next button click:

warn: Microsoft.UI.Xaml.Controls.Primitives.PopupPanel[0]
      anchorSize is 0
     
And now, if you click the button again, the flyout will appear

### Works on UWP/WinUI

None

**Comment by iurycarlos** [comment]
In case it helps, the version which started the issue is : 

5.1.0-dev.1459

**Comment by carldebilly** [comment]
> Related to #15240. A workaround is to remove the NaN that you likely have in your styles.

@jeromelaban, it's doing that in a brand new app, so which style should be overriden to fix it?

**Comment by Youssef1313** [comment]
Fix is backported.

https://github.com/unoplatform/Uno.Themes/pull/1342
