### ISSUE TITLE
`netstdref` XAML conditional should work properly for net7.0 and net8.0

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#15303]
### Current behavior

Currently, `netstdref` only works if `UnoRuntimeIdentifier` is identified as Skia or Wasm.

I think it should work for class library where target framework is just `netX.0`

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
@Youssef1313 let's revisit this soon with updates on uno.sdk.
