### ISSUE TITLE
[WASM] Grid-XXXX: Invalid measured size [-Infinity;YYY]. NaN or Infinity are invalid desired size.

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#1535]
# Bug
The following exception can appear on WASM:
```
mono.js:1 Uncaught Error: System.InvalidOperationException: Grid-756977: Invalid measured size [-Infinity;853]. NaN or Infinity are invalid desired size.
```

## How to reproduce it (as minimally and precisely as possible)
Coming from the following XAML code:

``` xml
<Grid>
	<Grid.ColumnDefinitions>
		<ColumnDefinition Width="*" MinWidth="40" />
		<ColumnDefinition Width="Auto" />
	</Grid.ColumnDefinitions>

	<ListView Grid.Column="1" />
</Grid>
```
* If you remove the `MinWidth`, the problem will go away.

## Affected platform(s):
- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] Windows

Package version `1.46.228-dev.2681`

**Comment by Youssef1313** [comment]
@carldebilly I couldn't reproduce. Can you please upload a repro or close this one if it was already fixed?

**Comment by carldebilly** [comment]
@Youssef1313 do you realize this is a 2 years old bug ? ;-) I'm pretty sure it's irrelevant now: I'll close it :-).
