### ISSUE TITLE
[Gallery][Skia.Gtk] Launcher- For the ‘Launch URI or website’ function, there is no response when the ‘Launch’ button is clicked.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#15369]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/b26dd698-2541-40b3-9343-8db05c105268

### Expected behavior

https://github.com/unoplatform/uno/assets/74563602/d9fbcf55-e4ca-4ac5-aa3a-86e8ce40d781

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left Top right.
3. Tap "launcher" from the "Non Ui Features" list.
4. Click on the 'Launch' Button.
5. Notice that there is no response when the ‘Launch’ button is clicked.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by ramezgerges** [comment]
fixed by https://github.com/unoplatform/uno-private/pull/328
