### ISSUE TITLE
[Skia] TextBox: Cancel BeforeTextChanging moves cursor in front of text

### ISSUE THREAD

**Issue by maaxe** [unoplatform/uno#15372]
### Current behavior

Cancelling BeforeTextChanging moves cursor in front of text

### Expected behavior

Cursor stays on current position

### How to reproduce it (as minimally and precisely as possible)

Add the handler to a textbox and dismiss the new input

E.g:
```
        public void TextBox_BeforeTextChanging(TextBox sender, TextBoxBeforeTextChangingEventArgs args)
        {
            args.Cancel = !double.TryParse(args.NewText, out double _);
        }
```

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

5.1.31

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.8

**Comment by ramezgerges** [comment]
This doesn't reproduce for me. @maaxe could you upload a complete repro project?

**Comment by maaxe** [comment]
@ramezgerges 

[UnoApp1.zip](https://github.com/unoplatform/uno/files/14345674/UnoApp1.zip)

Also tested with the latest dev builds (5.2.0-dev.757) and can reproduce it there also
