### ISSUE TITLE
[droid] BitmapIcon (in AppbarButton in AppBar) not scaled

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#1540]
## Current behavior
Icon is cropped, not scaled.

## Expected behavior
Icon is scaled.

## How to reproduce it (as minimally and precisely as possible)
Add icon to Assets subdirectory, e.g. 48x48 px

>         <AppBar ClosedDisplayMode="Compact" >
>      <StackPanel Orientation="Horizontal">
>                   <AppBarButton Label="Ikonka">
>                        <AppBarButton.Icon>
>                            <BitmapIcon UriSource="ms-appx:///Assets/ikonka.png" />
>                        </AppBarButton.Icon>
>                    </AppBarButton>
>                </StackPanel>
>         </AppBar>

In AppBarButton, about half of icon is displayed (upper half).

## Environment

Nuget Package: 1.45.0
Package Version(s):

Affected platform(s):
- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [X] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

**Comment by jeromelaban** [comment]
This issue is most likely fixed in the latest dev packages. Could you check again ?
