### ISSUE TITLE
[Playground][Wasm] Slider- As the cursor moves within the vertical slider range, the thumb also drags along the slider.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#15428]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/11f4517e-c845-4a0e-a27c-7077d14c6b91

### Expected behavior

The Thumb should drag on the slider only when cursor is pressed on the thumb.

### Workaround

1. Visit https://playgroundcanary.z19.web.core.windows.net/#passwordbox
2. Go to the Snippets combobox
3. Click on 'Slider' snippets option.
4. Go to vertical slider section.
5. Put anywhere cursor on the screen but not on the slider.
6. Notice that the as the cursor moves within the vertical slider range, the thumb also drags along the slider.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
@sakshi173 this is the expected behavior. You can validate that it is doing the same with windows by using the Xaml Studio app on the Windows Store.
