### ISSUE TITLE
Using localSettings issue

### ISSUE THREAD

**Issue by Victel** [unoplatform/uno#15430]
### Current behavior

UNO WinUI "ApplicationDataContainer localSettings = Windows.Storage.ApplicationData.Current.LocalSettings;" causing 
System.InvalidOperationException: 'Operation is not valid due to the current state of the object.' HResult -2147009196 from WinRT.Runtime

### Works on UWP/WinUI

None

**Comment by limeniye** [comment]
Hello @Victel! 
Thank you for the report.
See the following replay: https://stackoverflow.com/a/72412511/16493575

**Comment by Victel** [comment]
Hello @limeniye and thank you for so prompt response!
Unfortunately, using ApplicationDataManager instead doesn't change anything.
Also, replay https://stackoverflow.com/a/72412511/16493575 you are mentioning refers to System.TypeInitializationException while I'm encountering System.InvalidOperationException, needless to say that I'm using absolutely fresh Uno project built by latest VS 2022 v.17.8.5.
The Best!

**Comment by limeniye** [comment]
Currently, I'm not at home.
But try to change ``Windows.`` namespace to ``Microsoft``

**Comment by daredloco** [comment]
Are you running it for a Windows target? This exception will be thrown if you run/compile it unpackaged, but will work if you package it.

From @pictos on Discord:

> If you're compiling/running your app as Unpackage this's the expected behavior... I tried on my end and for Package version the code works

https://discord.com/channels/1182775715242967050/1182775715729526908/1200562603144003656

**Comment by Victel** [comment]
Yes, it works on Windows target packaged.
Thanks.

**Comment by igiona** [comment]
I'm experiencing the same issue, and using a packaged app seems to solve the problem for me as well.
On the other hand, none of the Uno docs about settings seems to mention this, e.g.:

https://platform.uno/docs/articles/features/settings.html

It would be nice to get the hint there ;)
