### ISSUE TITLE
Recommendations to WebServer configuration for hosting WebAssembly applications

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1544]
## What would you like clarification on:

Opening in response to [feedback in Gitter](https://gitter.im/uno-platform/Lobby?at=5d7bb4fda6f4896449fbb423) where Igor didn't have a smooth experience with hosting a Uno application on nginx.

Most webservers don't [yet] know how to properly serve WebAssembly applications and execution will fail with errors such as:

> "wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'."

Over at https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/UnoSolutionTemplate/Wasm/wwwroot/web.config#L17 we ship examples for hosting on IIS or via Azure. Generalized guidance is required in our documentation.

Related:

- https://github.com/WebAssembly/design/issues/981
- https://gist.github.com/WesThorburn/62ea13952749d6563ce2fb15b45f1ba8

## Concern?

- [x] Hosting Uno Applications

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows

**Comment by RanadeepPolavarapu** [comment]
I'll tackle this.
