### ISSUE TITLE
XAML / C# hot reload does not work on debian linux

### ISSUE THREAD

**Issue by sarosigy** [unoplatform/uno#15467]
### Current behavior

When starting an app, the error messages appears:

fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 192.168.34.190.
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 192.168.1.108.
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 192.168.100.1.
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get any remote control server endpoint from the IDE.

### Expected behavior

XAML and C# hot reload should work

### How to reproduce it (as minimally and precisely as possible)

dotnet new unoapp -sw:false -mobile:false -slf:false -vs -s -wpm -ho -f:net7.0 
Run vscode
Hit F5

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

```  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageReference Include="Uno.WinUI" Version="4.7.56" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='net7.0-windows10.0.18362'">
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.1.3" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.22000.24" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.22000.24" />
  </ItemGroup>
```
And
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Uno.WinUI.Skia.Gtk" Version="4.7.56" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.7.56" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.7.56" />
    <PackageReference Include="Uno.WinUI.Lottie" Version="4.7.56" />
    <PackageReference Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.3" />
    <PackageReference Include="SkiaSharp.Skottie" Version="2.88.3" />
  </ItemGroup>
```
And
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="6.0.0" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.4.0" />
    <PackageReference Include="Uno.WinUI.WebAssembly" Version="4.7.56" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.7.56" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.7.56" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="7.0.11" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="7.0.11" />
    <PackageReference Include="Uno.WinUI.Lottie" Version="4.7.56" />
  </ItemGroup>
```

### Affected platforms

WebAssembly, Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio Code

### IDE version

1.86.1

### Relevant plugins

C# v2.18.15 (pre-release)
C# Dev Kit v1.3.10
Uno Platform v0.12.0

### Anything else we need to know?

The launch json fragment:
```json
    {
      // Use IntelliSense to find out which attributes exist for C# debugging
      // Use hover for the description of the existing attributes
      // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
      "name": "Debug (Chrome, WebAssembly)",
      "type": "msedge",
      "request": "launch",
      "url": "http://localhost:5000",
      "webRoot": "${workspaceFolder}/Project.Wasm",
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "timeout": 30000,
      "server": {
        "runtimeExecutable": "dotnet",
        "program": "run",
        "outputCapture": "std",
        "timeout": 30000,
        "cwd": "${workspaceFolder}/Project.Wasm"
      }
    },
```

**Comment by sarosigy** [comment]
error CS0246: The type or namespace name 'GtkHost' could not be found (are you missing a using directive or an assembly reference?)

Here:
```csharp
using System;
using GLib;
using Uno.UI.Runtime.Skia;

namespace Project.Skia.Gtk
{
	public sealed class Program
	{
		static void Main(string[] args)
		{
			ExceptionManager.UnhandledException += delegate (UnhandledExceptionArgs expArgs)
			{
				Console.WriteLine("GLIB UNHANDLED EXCEPTION" + expArgs.ExceptionObject.ToString());
				expArgs.ExitApplication = true;
			};

			var host = new GtkHost(() => new AppHead());

			host.Run();
		}
	}
}
```

**Comment by sarosigy** [comment]
The issue is the same:

Uno.UI.js:3716
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 192.168.34.190.
_bound_js_globalThis_console_error:7
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 192.168.1.108.
_bound_js_globalThis_console_error:7
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 192.168.100.1.
_bound_js_globalThis_console_error:7
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get any remote control server endpoint from the IDE.

The referenced assemblies are:
```
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageReference Include="Uno.WinUI" Version="5.1.52" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Uno.WinUI.DevServer" Version="5.1.52" />
```
And (for wasm)
```
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="6.0.0" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.7.0" />
    <PackageReference Include="Uno.WinUI.DevServer" Version="5.1.52" />
    <PackageReference Include="Uno.WinUI.WebAssembly" Version="5.1.52" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.1.52" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="7.0.8" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="7.0.8" />
    <PackageReference Include="Uno.WinUI.Lottie" Version="5.1.52" />
```
Or for Skia.GTK:
```
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Uno.WinUI.DevServer" Version="5.1.52" />
    <PackageReference Include="Uno.WinUI.Skia.Gtk" Version="5.1.52" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.1.52" />
    <PackageReference Include="Uno.WinUI.Lottie" Version="5.1.52" />
    <PackageReference Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.7" />
    <PackageReference Include="SkiaSharp.Skottie" Version="2.88.7" />
```

Is the .Net 8 upgrade mandatory?

**Comment by jeromelaban** [comment]
.NET 8 is best for hot reload, yes, as there are many more scenarios supported with it.

Could you provide the logs from the "Uno Platform - Hot Reload" message window?

**Comment by sarosigy** [comment]
Pr[Info] Launching remote control server (Port:42189, Path:/home/george/.nuget/packages/uno.winui.devserver/5.1.52/buildTransitive/../tools/rc/host/net8.0/Uno.UI.RemoteControl.Host.dll)
dbug: Uno.UI.RemoteControl.Host.IdeChannel.IdeChannelServerProvider[0]
      No IDE Channel ID specified, skipping

dbug: Microsoft.AspNetCore.Hosting.Diagnostics[3]
      Hosting starting

dbug: Microsoft.AspNetCore.Hosting.Diagnostics[4]
      Hosting started

dbug: Microsoft.AspNetCore.Hosting.Diagnostics[13]
      Loaded hosting startup assembly Uno.UI.RemoteControl.Host

Hosting environment: Production
Content root path: /home/george/source/Project

Now listening on: http://[::]:42189
Application started. Press Ctrl+C to shut down.

Is it just IPv6?

**Comment by sarosigy** [comment]
The ```netstat | grep 42189``` gives blank result.

**Comment by jeromelaban** [comment]
Thanks. It's listening on v4/v6, so no issues there.

For application to read the proper port to connect to, the extension generates a file named "RemoteControl.config" in the obj folder of the project selected in the status bar. Are you selecting the ".Wasm" project ?

**Comment by sarosigy** [comment]
Hmm...
No, up to now I couldn't because the .Net 8 problem...

**Comment by jeromelaban** [comment]
This would explain why hot reload does not work. You need select the same project you're debugging with. What's the issue with .NET 8?

**Comment by sarosigy** [comment]
Just the other thread.
Now, it's installed, I got a different error message:

Failed to initialize compilation workspace: System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor.<>c.<ObserveSolutionPaths>b__20_2(String p) in /agent/_work/1/s/src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.MetadataUpdate.cs:line 100
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor.ObserveSolutionPaths(Solution solution) in /agent/_work/1/s/src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.MetadataUpdate.cs:line 84
   at Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor.<>c__DisplayClass19_0.<<InitializeInner>b__0>d.MoveNext() in /agent/_work/1/s/src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.MetadataUpdate.cs:line 65

Checking this now.

**Comment by sarosigy** [comment]
Increased the number of inotify instances.
Still has problems:
```
....
....
Loaded [Microsoft.ApplicationInsights, Version=2.21.0.429, Culture=neutral, PublicKeyToken=31bf3856ad364e35] from [/usr/share/dotnet/sdk/8.0.101/Microsoft.ApplicationInsights.dll]

Searching for [Microsoft.DotNet.PlatformAbstractions, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60] from [/home/george/.nuget/packages/uno.winui.devserver/5.1.52/tools/rc/processors/net8.0]

Searching for [Uno.Xaml, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null] from [/home/george/.nuget/packages/uno.winui.devserver/5.1.52/tools/rc/processors/net8.0]

[Verbose] Could not find document with path /home/george/source/Project/Project/pageLogin.xaml in the workspace.

dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
      File /home/george/source/Project/Project/pageLogin.xaml changed

dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
      File /home/george/source/Project/Project/pageLogin.xaml changed

dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
      File /home/george/source/Project/Project/pageLogin.xaml changed
dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
      File /home/george/source/Project/Project/pageLogin.xaml changed

[Verbose] Could not find document with path /home/george/source/Project/Project/pageLogin.xaml in the workspace.

dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
      File /home/george/source/Project/Project/pageLogin.xaml.cs changed
dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
      File /home/george/source/Project/Project/pageLogin.xaml.cs changed

[Output] Found 0 metadata updates after 00:00:00.2747869
```
Debug window, after trying to set breakpoints in source:
```
Breakpoint warning: The source code is different from the original version.
To allow this breakpoint to be hit: Add '"requireExactSource": false' to launch.json and restart debugging. - /home/george/source/Project/Project/pageLogin.xaml.cs:49
Breakpoint warning: The source code is different from the original version.
To allow this breakpoint to be hit: Add '"requireExactSource": false' to launch.json and restart debugging. - /home/george/source/Project/Project/pageLogin.xaml.cs:51
```

**Comment by sarosigy** [comment]
Now it is slightly different, but the result is the same (Skia.GTK)
```
Searching for [Microsoft.DotNet.PlatformAbstractions, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60] from [/home/george/.nuget/packages/uno.winui.devserver/5.1.52/tools/rc/processors/net8.0]

Selecting first occurrence of assembly [Microsoft.DotNet.PlatformAbstractions, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60] which can be found at [/home/george/.nuget/packages/uno.winui/5.1.52/analyzers/dotnet/cs/Microsoft.DotNet.PlatformAbstractions.dll]

Searching for [Uno.Xaml, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null] from [/home/george/.nuget/packages/uno.winui.devserver/5.1.52/tools/rc/processors/net8.0]

Selecting first occurrence of assembly [Uno.Xaml, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null] which can be found at [/home/george/.nuget/packages/uno.winui/5.1.52/analyzers/dotnet/cs/Uno.Xaml.dll]

dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
      File /home/george/source/Project/Project/pageLogin.xaml changed
dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
      File /home/george/source/Project/Project/pageLogin.xaml changed

[Output] Found 1 metadata updates after 00:00:03.2444506

dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
      File /home/george/source/Project/Project/pageLogin.xaml.cs changed

dbug: Uno.UI.RemoteControl.Host.HotReload.ServerHotReloadProcessor[0]
      File /home/george/source/Project/Project/pageLogin.xaml.cs changed

[Output] Found 1 metadata updates after 00:00:00.2970452
```
But the result is the same:
```
Breakpoint warning: The source code is different from the original version.
To allow this breakpoint to be hit: Add '"requireExactSource": false' to launch.json and restart debugging. - /home/george/source/Project/Project/pageLogin.xaml.cs:49
Breakpoint warning: The source code is different from the original version.
To allow this breakpoint to be hit: Add '"requireExactSource": false' to launch.json and restart debugging. - /home/george/source/Project/Project/pageLogin.xaml.cs:51
Breakpoint warning: The source code is different from the original version.
```

**Comment by sarosigy** [comment]
Oh, wait, I just found in the Output:
```

fail: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
      Hot Reload is not supported when the debugger is attached.
```
It means, that if I press F5, I am not able to utilize hot reload? I have to detach, make changes (won't it stop the whole hot reload process??), and reattach to debug?

**Comment by jeromelaban** [comment]
Thanks for the updates. 

> It means, that if I press F5, I am not able to utilize hot reload? I have to detach, make changes (won't it stop the whole hot reload process??), and reattach to debug?


Indeed, at this time, debugging and hot reload are not supported by a limitation of the .NET runtime (see [the hotreload docs here](https://platform.uno/docs/articles/features/working-with-xaml-hot-reload.html?tabs=vswin%2Cskia#vs-code)). Improvements are coming for some platforms though the evolutions of the C# Dev Kit from Microsoft.

> Now it is slightly different, but the result is the same (Skia.GTK)

For the Skia.Gtk head, make sure to select the "Skia.Gtk" debug configuration to start the application. Also, can you show what's in the "Debug Console" output when you start the app and perform a hot reload?

> Debug window, after trying to set breakpoints in source:

For the debugger messages, where do you see those messages, in VS Code? Is it in the debug console? It could also be related to the selection of the active debugger.

**Comment by sarosigy** [comment]
For the second start, the Crtl-F5 did the trick.
Now I can see changes made in XAML.

However, continue the debugging is still impossible, but as you said, it must be the limitation of the current tools:
```
Failed to attach to process: Attaching a .NET debugger to this process is not allowed because code changes have been applied. The process must be restarted to allow debugging.
```

Summary:
- After updating to the newest Uno components,
- Using .Net 8 in order to be able to select the appropriate project in vscode
- Increasing the inotify instances
- And not debugging the project
The hot reload works.

Thank you, very much, for your help and time!

**Comment by jeromelaban** [comment]
Thanks for the troubleshooting!

Could you provide the command you used so update the inotify instances? We'll be able to hint the user at changing this value in our vscode plugin.

**Comment by sarosigy** [comment]
inotify instances:
You have to modify the '/etc/sysctl.conf' file, add (or modify if already exists) line:
```
fs.inotify.max_user_instances=16384
```
And restart.
It should be a big enough number, the bigger the solution the bigger the number of files to be watched.

Side note to the whole .Net 7 / 8 and Uno upgrade problems:

I was sure that I had the newest 'dotnet new' templates. I ran 'dotnet new update' and it showed nothing to update.
The options of the 'dotnet new unoapp' listed:
```
 -f, --framework <net6.0|net7.0>                    The target framework for the project.
                                                     Type: choice
                                                       net6.0  Target net6.0
                                                       net7.0  Target net7.0
                                                     Default: net7.0
```
So I thought, maybe .Net 8 is not an option currently.

After checking the instructions to create a new project I saw very different options, e.g.:
```
 -tfm <net8.0>                             Select the .NET version of your solution
                                            Type: choice
                                              net8.0  Target .NET 8.0 (Long Term Support)
                                            Default: net8.0
```

Because it is not Window only, I began some research, and I found that I had the templates for '**Uno.ProjectTemplates.Dotnet**', while the current templates are '**Uno.Templates**'. The 'dotnet new uninstall' will show it.

If someone would run into this kind of issue maybe check which templates are installed :)

**Comment by jeromelaban** [comment]
Thanks! For the template errors, in theory, uno.check is supposed to fix this, but it looks like it should also be uninstalling the legacy versions of the templates. Good feedback!

Thanks for the inodes change, we'll make some modifications to our extensions.
