### ISSUE TITLE
Server project fails to build on linux

### ISSUE THREAD

**Issue by sarosigy** [unoplatform/uno#15469]
### Current behavior

 *  Executing task: dotnet: build /home/george/source/Project/Project.Server/Project.Server.csproj 

dotnet build /home/george/source/Project/Project.Server/Project.Server.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary 
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Project -> /home/george/source/Project/Project/bin/Debug/net7.0/Project.dll
  Project.Wasm -> /home/george/source/Project/Project.Wasm/bin/Debug/net7.0/Project.Wasm.dll
/usr/share/dotnet/sdk/7.0.100/Microsoft.Common.CurrentVersion.targets(5150,5): error MSB3024: Could not copy the file "/home/george/source/Project/Project.Server/obj/Debug/net7.0/apphost" to the destination file "bin/Debug/net7.0/Project.Server", because the destination is a folder instead of a file. To copy the source file into a folder, consider using the DestinationFolder parameter instead of DestinationFiles. [/home/george/source/Project/Project.Server/Project.Server.csproj]

 *  The terminal process terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

### Expected behavior

It should build.

### How to reproduce it (as minimally and precisely as possible)

1. dotnet new unoapp -sw:false -mobile:false -slf:false -vs -s -wpm -ho -f:net7.0
2. dotnet build in Server project folder

### Works on UWP/WinUI

None

### NuGet package version(s)

```
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageReference Include="Uno.WinUI" Version="4.7.56" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='net7.0-windows10.0.18362'">
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.1.3" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.22000.24" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.22000.24" />
  </ItemGroup>
```
And
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="6.0.0" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.4.0" />
    <PackageReference Include="Uno.WinUI.WebAssembly" Version="4.7.56" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.7.56" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.7.56" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="7.0.11" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="7.0.11" />
    <PackageReference Include="Uno.WinUI.Lottie" Version="4.7.56" />
  </ItemGroup>
```

### Affected platforms

Build tasks

### IDE

Visual Studio Code

### IDE version

1.86.1

### Relevant plugins

C# v2.18.15 (pre-release)
C# Dev Kit v1.3.10
Uno Platform v0.12.0

### Anything else we need to know?

The machine is debian bookworm, .Net 7 installed

**Comment by jeromelaban** [comment]
Thanks for the report. Could you validate with .NET 8 (`net8.0` target framework), there were a few changes in .NET 8 that may fix this issue.

**Comment by sarosigy** [comment]
After moving to .Net 8 it compiles. Thank you!
