### ISSUE TITLE
[WASM] CalendarView is '1 day off' on German Windows settings

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#15486]
### Current behavior

I got reports by customers that CalendarView is off by one day (1st screenshot below - this is **UNO Gallery** = no repo required). All impacted users are on Windows 11 with default German settings (2nd screenshot below).

I tried to reproduce (I'm running English US settings on my Windows 11 by default - and switched to German settings), but could not reproduce?!? Go figure...

Nevertheless the issue is factual.

Speculating: default German settings are going with .FirstDayOfWeek = Monday - which is not reflected on the actual UNO gallery UI - and might contribute to the problem.

![UNO1](https://github.com/unoplatform/uno/assets/26179242/1af9bbe6-f667-412d-8dbd-7ff7a7114e18)
![UNO2](https://github.com/unoplatform/uno/assets/26179242/45ba5f88-5e90-4bad-a95a-995420f28f3d)

### Expected behavior

CalendarView should work correctly.

### How to reproduce it (as minimally and precisely as possible)

See UNO gallery

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by DierkDroth** [comment]
Thanks @Youssef1313.

I asked the impacted users to run some tests and will report back...

**Comment by Youssef1313** [comment]
Thank you!

Also, could you mention the Uno NuGet package version you're using in your app?

**Comment by DierkDroth** [comment]
@Youssef1313 please see below

Note: the issue is independent from my actual app + UNO version, since it's reproducible with the UNO gallery.

<img width="1280" alt="image" src="https://github.com/unoplatform/uno/assets/26179242/6ce8acd8-ed24-482a-9a06-5932eea1ad5b">

**Comment by Youssef1313** [comment]
There was a recent change in this area that went into 5.2.0-dev.541 (which is not included in https://gallery.platform.uno but is included in https://unogallerycanary.z27.web.core.windows.net/).

**Comment by DierkDroth** [comment]
@Youssef1313 here is the feedback from one of my German users:
- the UNO canary links fixes the issue where the dates are '1 day off' -> good
- however, CalendarView still is not working correctly on German PCs where the default is .FirstDayOfWeek=Monday(=Montag) -> bad
 
Please see the screenshots below from the PC of my German user
- 1st: UNO canary
- 2nd: Windows settings -> .FirstDayOfWeek=Monday(=Montag)
- 3rd: for comparison reasons the WinUI3 version of my app where .FirstDayOfWeek=Monday is rendered correctly

![UNO1](https://github.com/unoplatform/uno/assets/26179242/468f033f-87c6-48ef-81dd-ee998283983b)
![UNO2](https://github.com/unoplatform/uno/assets/26179242/8d791cdb-b417-4c66-98f4-4e42039677ca)
![UNO3](https://github.com/unoplatform/uno/assets/26179242/0457fb25-3461-4e2c-b605-741694fe2e6c)

**Comment by DierkDroth** [comment]
Thanks for follow up @Youssef1313 

No, I'm not setting `CalendarView.FirstDayOfWeek` in my app. I would expect that in that default case UNO WASM CalendarView would behave like WinUI3 CalendarView (please see 3rd screenshot): OS settings (here: Windows settings) are respected.

**Comment by Youssef1313** [comment]
I'm not seeing the same behavior on WinUI:

![image](https://github.com/unoplatform/uno/assets/31348972/95bc6349-ce3d-4881-bba7-ca90d213deb5)

**Comment by DierkDroth** [comment]
@Youssef1313 do you have a link for that app? I could ask my customer to run it on their machine to further analyzer the issue...

**Comment by DierkDroth** [comment]
Also: Are you sure .FirstDayOfWeek is not hard coded to Sunday on that app?

**Comment by Youssef1313** [comment]
Yes, I think FirstDayOfWeek isn't hard-coded. I also tried in a new blank WinUI app.

This is the WinUI 3 Gallery (you can find it in the Store)

**Comment by Youssef1313** [comment]
@jeromelaban for the backport question. The PR that fixed it is https://github.com/unoplatform/uno/pull/15234

**Comment by Youssef1313** [comment]
@DierkDroth The fix for the "1 day off" problem is backported and available in in 5.1.62.

Is the FirstDayOfWeek still an issue?

**Comment by DierkDroth** [comment]
Thanks @Youssef1313. I'll check it out when doing my next build...

**Comment by DierkDroth** [comment]
@Youssef1313 the German user reported that the issue would be fixed. Thanks for taking care
