### ISSUE TITLE
CommandBar's Primaryin Commands don't show

### ISSUE THREAD

**Issue by HaoLife** [unoplatform/uno#1548]
## Current behavior

 CommandBar does not show primaryinCommands in the 1.45.0 version and 1.46.x latest version, and this feature is displayed normally in 1.44.1.

The reason is to add a style
> <xamarin:Style BasedOn="{StaticResource NativeDefaultFrame}" TargetType="Frame" />

## Expected behavior
PrimaryinCommands Normal Display

## Environment

Nuget Package:

Package Version(s):
 1.45.0  - 1.46.x

Affected platform(s):
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by pkar70** [comment]
Try BitmapIcon type.
FontIcon/SymbolIcon/PathIcon are not implemented (yet), and there is breaking change between 1.44 and 1.45 - in 1.45, if there is any Icon, Label is not showed (Content takes precedence over Label).

**Comment by HaoLife** [comment]
Is it ok if I don't set the Content and Icon properties?
