### ISSUE TITLE
ContentDialog **Java.Lang.NoSuchFieldException:** 'No field mDrawableForCursor in class Landroid/widget/Editor

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#15481]
### Current behavior

When I call ContentDialog.ShowAsync(), I got
`**Java.Lang.NoSuchFieldException:** 'No field mDrawableForCursor in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)'`

### Expected behavior

ContentDialog working.

### How to reproduce it (as minimally and precisely as possible)

a) extension method

    public static async Task<string> InputBoxAsync(this FrameworkElement oPage, string message, string defaultText = "", string buttonContinue = "Continue", string buttonCancel = "Cancel")

    {

        TextBox textBox = new TextBox
        {
            AcceptsReturn = false,
            Text = defaultText,
            IsSpellCheckEnabled = false
        };
        if (await new ContentDialog
        {
            Content = textBox,
            PrimaryButtonText = buttonContinue,
            SecondaryButtonText = buttonCancel,
            Title = message,
            XamlRoot = oPage.XamlRoot
        }.ShowAsync() != ContentDialogResult.Primary)
        {
            return "";
        }

        return textBox.Text;
    }`
(in Uno class library with "multiplatform" word in name, not with "crossplatform")

and in code:

      private async void uiDownload_Click(Object sender, RoutedEventArgs e)
      {
        String sUserAgent = "QuizKurs 123";

        String sLink = await this.InputBoxAsync("Podaj ID quizu:");
        if (sLink == "") return;
    (...)

My full code:
https://github.com/pkar70/EduQuiz/tree/master/QuizKursUno
and library, as Nuget (unpublished yet):
https://github.com/pkar70/MyLibs/tree/master/pkar.Uno.Extensions

(but same problem exists when classlib is not used, and this helper method is in mainpage.xaml.cs)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.1.52

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.9.0

**Comment by jeromelaban** [comment]
Thanks for the report.

I tested the code that you provided, and it's showing up properly for me:

<img width="421" alt="image" src="https://github.com/unoplatform/uno/assets/5839577/54f05ce2-317c-4cff-9857-2540499f21f2">


In the debugger, can you break on all exception when clicking on the button? It may show more details in your setup.

**Comment by pkar70** [comment]
I can confirm: when I run this app on Android 11 (inside BlueStacks 5), it works. And same apk doesn't work on Android 9 (also inside BlueStacks 5). So, maybe adding some test on ShowAsync() for Android version, and throwing exception with message that Android version is too low, would be beneficient.
