### ISSUE TITLE
Msix installer broken after upgrade to latest uno/uno.sdk/.net 8

### ISSUE THREAD

**Issue by hamada-applicita** [unoplatform/uno#15492]
### Current behavior

We previously created msix installers for our uno windows app using the below command line and everything worked fine

`msbuild.exe "path/to/uno.sln" /p:configuration="Release" /p:VisualStudioVersion="17.0" /p:AppxBundlePlatforms=x64 /p:GenerateAppxPackageOnBuild=true /p:AppxBundle=Never /p:UapAppxPackageBuildMode=SideLoadOnly /p:AppxPackageSigningEnabled=fasle /p:AppxPackageDir="C:\Code\app\AppxPackages" `

After upgrading from .net 7 to .net 8 as well as latest uno and uno.sdk the same command line still produces the msix but the app crashes on startup. The only error I can get is from the event log

```
Faulting application name: UnoApp1.Windows.exe, version: 1.0.0.0, time stamp: 0x65a80000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3930, time stamp: 0x9141f979
Exception code: 0xc000027b
Fault offset: 0x000000000012db22
Faulting process ID: 0x6104
Faulting application start time: 0x01da6023a0051583
Faulting application path: C:\Program Files\WindowsApps\UnoApp1_1.0.0.0_x64__h21bem17p9w1p\UnoApp1.Windows.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 1ffb248d-9dea-4b31-9e09-90dba8267c53
Faulting package full name: UnoApp1_1.0.0.0_x64__h21bem17p9w1p
Faulting package-relative application ID: App
```

Crucially, on the same machine, if instead of running the msbuild command line I open Visual studio and right click->Package and Publish the created msix works fine and the app runs. This tells me it is not to do with the setup of the machine but the command line used to create the installer.

### Expected behavior

Providing the correct command(s) needed to create a functioning msix installer

### How to reproduce it (as minimally and precisely as possible)

I recreated this using a uno windows application created from latest templates

then running the command

`msbuild.exe "path/to/uno.sln" /p:configuration="Release" /p:VisualStudioVersion="17.0" /p:AppxBundlePlatforms=x64 /p:GenerateAppxPackageOnBuild=true /p:AppxBundle=Never /p:UapAppxPackageBuildMode=SideLoadOnly /p:AppxPackageSigningEnabled=fasle /p:AppxPackageDir="C:\Code\app\AppxPackages" `

Installing the produced msix

Run the app, crashes on startup

### Works on UWP/WinUI

None

### Affected platforms

Windows

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report.

We'll investigate, though this seems like a WinAppSDK issue.

**Comment by jeromelaban** [comment]
@hamada-applicita In the `csproj` that contains the AppResources.xaml, can you add the following:

```xml
<PropertyGroup>
  <EnableCoreMrtTooling>true</EnableCoreMrtTooling>
</PropertyGroup>
```

And let us know if this helps?

**Comment by hamada-applicita** [comment]
Thankyou @jeromelaban 

This setting has fixed our windows installer. The app now runs without crashing after install.

We did have CI processes that use `dotnet build` that started failing because of this setting. I had to switch our CI builds to use `msbuild `instead of `dotnet build` as a workaround.

dotnet build fails with 
`error MSB4062: The "Microsoft.Build.Packaging.Pri.Tasks.ExpandPriContent" task could not be loaded from the assembly`

which is an error ive seen in the past and workaround using `EnablePreviewMsixTooling`

It would be nice to properly understand what these various settings do but i cant find anything from MS on them. Can you add anything esp around the dotnet build/msbuild discrepancy

**Comment by jeromelaban** [comment]
`dotnet build` is not officially supported by microsoft at this time. There are ways to get around it, but it disables features that are critical to most apps. The official workflow from microsoft [is this one](https://learn.microsoft.com/en-us/windows/apps/package-and-deploy/ci-for-winui3?pivots=winui3-packaged-csharp#step-3-set-up-your-workflow).

**Comment by hamada-applicita** [comment]
thanks for that info - ive not seen that example before.

I think we can close this one

**Comment by sasakrsmanovic** [comment]
Should this issue be closed @hamada-applicita ?

**Comment by hamada-applicita** [comment]
yes we can close - appreciate the quick response

**Comment by jeromelaban** [comment]
@sasakrsmanovic no, we need to make a change in Uno to avoid the workaround.
