### ISSUE TITLE
Telerik RadCalendar date selection not working

### ISSUE THREAD

**Issue by JhonH3avy** [unoplatform/uno#1550]
## Current behavior

The calendar at the moment of selection of any date, the calendar selects incorrectly the date and sometimes jump to the next month. This behavior is currently happening in the Uno fork of the Telerik controls repo, but, if I try to implement the control using the control projects directly the behavior changes, so the event of date selection is not event being called, so there is no date selection in a custom usage of the control.

## Expected behavior

Date selection should occur through mouse click as normally expected of the control in its counterpart of UWP.

## How to reproduce it (as minimally and precisely as possible)

Uno Telerik control fork:
https://github.com/unoplatform/Uno.Telerik.UI-For-UWP
Custom implementation:
https://github.com/JhonH3avy/DatePickerControl

## Environment

Nuget Package:
Uno.UI 1.46.230-dev.2711
Package Version(s):

Affected platform(s):
- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?

I think this issue has some relation with the size of the control, because the implementation example has an automatic size that occupies all the space it can and in my implementation it has a fixed sized, but when I change the size in the implematation example to something similar to the fixed size I use, the issue behavior change to the second I described.

**Comment by JhonH3avy** [comment]
This problem persist on Uno.UI -> 2.1.0-dev.1345
And the RadCalendar even that is showing fine, there is still an PointerPressedEvent error at the date selection moment.

**Comment by francoistanguay** [comment]
No plans to work on this at this point of time unfortunately.
