### ISSUE TITLE
[iOS][Android] UIElement implements INotifyPropertyChanged

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#1551]
## Current behavior
On iOS and Android, the base class of `UIElement` (`BindableUIView` on Android and `BindableView` for iOS) implements the `INotifyPropertyChanged` **but**:

1. UWP's `UIElement` does not implements this interface
1. The event is **NOT** raised by any sub class (and especially not by the `DependencyProperty`)

## Expected behavior
`UIElement` does not implement this interface

## Environment
Nuget Package: Uno.UI
Package Version(s): 1.46

Affected platform(s):
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio: _irrelevant_
Relevant plugins: _none_

**Comment by carldebilly** [comment]
@dr1rrb Is this issue fixed by the PR #2168?

**Comment by dr1rrb** [comment]
@carldebilly you're a bit forward ... this PR doesn't exists yet
