### ISSUE TITLE
Intellisense in VS2022 not working when the Windows head is not included

### ISSUE THREAD

**Issue by AlleSchonWeg** [unoplatform/uno#15517]
### Current behavior

Hi,
i created a basic Uno project (iOS and Android Head) with the latest VS Version (17.9.0). In the xaml files intellisense is not working. VS reports this errors:
![image](https://github.com/unoplatform/uno/assets/6727366/1cf51618-3215-412c-90cd-b10078afec2d)
Also InitializeComponent in the cs file is marked as not known. I can compile the project successfully. I tried to clean solution, delete bin/obj and restart VS. But the problem persists.

### Expected behavior

No errors.

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

5.1.56

### Affected platforms

Android, iOS

### IDE

VS Enterprise

### IDE version

17.9.0

**Comment by jeromelaban** [comment]
Thanks for the report.

There's indeed an issue with XAML intellisense in Visual Studio, and it only seems to happen when there isn't a `.Windows` project in the solution.

We'll be looking into this but in the meantime, create your solution with the Windows head, even if you don't intend to use it.

**Comment by lindexi** [comment]
@AlleSchonWeg After you created the `.Windows` project, you can get the XAML intellisense by set it to the `.Windows` project, as the image shown:

![](https://github.com/unoplatform/uno/assets/16054566/283b99c7-d738-42fc-a3e2-6ddfb325d13b)

**Comment by AlleSchonWeg** [comment]
Thank you. After creating a new solution with windows intellisense works. 
Should i close this issue?

**Comment by jeromelaban** [comment]
Let's keep track of this issue in https://developercommunity.visualstudio.com/t/XAML-Intellisense-does-not-recognize-typ/10595884

**Comment by AlleSchonWeg** [comment]
Thanks for the fix. When and how will the fix be available?
