### ISSUE TITLE
Text selection color is sometimes incorrect

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#15528]
### Current behavior

I have the following in my `TextBox` in samples app Playground:

```xml
<Grid>
 <ComboBox  xmlns:my="using:Uno.UI.RuntimeTests.Tests.ComboBoxTests" Margin="0 20 0 0">
    <ComboBox.Items>
      <ComboBoxItem Content="a" />
      <ComboBoxItem Content="b" />
      <ComboBoxItem Content="c" />
      <ComboBoxItem Content="d" />
      <ComboBoxItem Content="e" />
      <ComboBoxItem Content="f" />
      <ComboBoxItem Content="g" />
      <ComboBoxItem Content="h" />
      <ComboBoxItem Content="i" />
      <ComboBoxItem Content="j" />
      <ComboBoxItem Content="k" />
      <ComboBoxItem Content="l" />
    </ComboBox.Items>
  </ComboBox>
  </Grid>
```

With various selections, colors happen incorrectly:

![image](https://github.com/unoplatform/uno/assets/1075116/127b75a6-80b5-42a0-940b-cc8f1e062f4b)

![image](https://github.com/unoplatform/uno/assets/1075116/fe1204f0-511e-40bf-b989-0011cffac9fc)

Here I started the selection from cursor position just after the `\` to the left, which made the `>` disappear

![image](https://github.com/unoplatform/uno/assets/1075116/059e1936-2544-49c8-a2ca-2889b190efcc)

### Works on UWP/WinUI

None

**Comment by ramezgerges** [comment]
This is a ligature problem. Cascadia Code (which is the font used in the playground sample) contains ligatures, so the text rendering engine is treating `/>` as one character, which `/` being the one in control, i.e. if `/` is selected, then `/>` color is wholly changed to white, hence the disappearing `>` effect. If only `>` is selected, it's as if neither is selected, so `>` remains black. There doesn't seem to be anything we can do here. SkiaSharp and HarfBuffSharp doesn't seem to support configuring ligatures,

**Comment by MartinZikmund** [comment]
I just saw SixLabors.Fonts - could this benefit us in any way (as alternative to Harfbuzz maybe?)

**Comment by ramezgerges** [comment]
I don't think so. Skia internally uses HarfBuzz. So the problem is mostly within skia, not with our harfbuzz logic.

**Comment by ramezgerges** [comment]
I was wrong about this. We can disable ligatures with HarfBuzz and that will provide us with non-ligatured glyphs that can then be used with SKTextBlobs. Obviouslly, it would be better to have full ligature support, but we can settle for at least not breaking on fonts with ligatures.
