### ISSUE TITLE
[Android] `ApplicationView.GetForCurrentView().Bounds` ignores the translucent navigation bar

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#15520]
### Current behavior

With `windowTranslucentNavigation` set to `true`

`ApplicationView.GetForCurrentView().VisibleBounds.Bottom` is the same as `MainWindow!.Bounds.Bottom`
```
#if __ANDROID__ || __IOS__
        var full = App.Instance.MainWindow!.Bounds;
        var bounds = ApplicationView.GetForCurrentView().VisibleBounds;

        var bottomPadding = full.Bottom - bounds.Bottom;
#else
        var bottomPadding = 0;
#endif
```

![image](https://github.com/unoplatform/uno/assets/17461593/2178e09d-762e-4a99-bf32-751b8fa59536)

![Screenshot_20240216-134423](https://github.com/unoplatform/uno/assets/17461593/deff5201-7a80-48bb-b179-c1d1e8aba4bc)

### Expected behavior

For the same code on iOS, those two values are different which helps us avoiding phone edges

![image (1)](https://github.com/unoplatform/uno/assets/17461593/0f1bd7fe-bd51-418d-8c2b-c7f66cd23e33)

### How to reproduce it (as minimally and precisely as possible)

- Download this sample [BottomBoundsIssue.zip](https://github.com/unoplatform/uno/files/14316630/BottomBoundsIssue.zip)
- Deploy on Android

### Workaround

Waiting for `ApplicationView.GetForCurrentView().VisibleBoundsChanged` event to be raised to ensure that it gets the appropriate values

```cs
public Page()
{
#if __ANDROID__
	ApplicationView.GetForCurrentView().VisibleBoundsChanged += OnVisibleBoundsChanged;
#else
	InitializeSafeArea();
#endif
}

private void OnVisibleBoundsChanged(ApplicationView sender, object args)
{
	ApplicationView.GetForCurrentView().VisibleBoundsChanged -= OnVisibleBoundsChanged;
	InitializeSafeArea();
}

private void InitializeSafeArea()
{
#if __ANDROID__ || __IOS__
	var full = App.Instance.CurrentWindow.Bounds;
	var bounds = ApplicationView.GetForCurrentView().VisibleBounds;

	var bottomPadding = full.Bottom - bounds.Bottom;
#else
	var bottomPadding = 0;
#endif

	if (bottomPadding > 0)
	{
		SafeAreaRow.Height = new GridLength(bottomPadding);
	}
}
```

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.1.56

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.7.7; 17.10.0 Preview 1.0

### Anything else we need to know?

On our project, it started to happen when we've updated uno from 4.8.39 to 4.10.34

Related issue #12007

**Comment by jeromelaban** [comment]
This also feels similar to https://github.com/unoplatform/nventive-private/issues/510, what do you think @kazo0?

**Comment by kazo0** [comment]
Looks to be a timing issue with when the VisibleBounds is grabbed. If I place a button in the page and cause it to call `InitializeSafeArea` on click, I see the right values:

![Screenshot_1708364514](https://github.com/unoplatform/uno/assets/4793020/c0edd02a-c503-44ab-bfdc-9074c49482e6)


But for some reason the VisibleBounds looks to still be reporting as if we are on the splashscreen and displaying fullscreen

**Comment by jeromelaban** [comment]
It may be that the code relying on VisibleBounds should react on the Window.Size changed.

**Comment by kazo0** [comment]
@takla21 what about hooking to `ApplicationView.GetForCurrentView().VisibleBoundsChanged`?

**Comment by kazo0** [comment]
Ah, it seemingly also depends on when you call `MainWindow.Activate()` in the `App.cs`, so placing that call before the navigation to `MainPage` is performed will avoid [this issue](https://github.com/unoplatform/uno/issues/15521) but we are still stuck with the Windos Bounds being equal to the VisibleBounds at that point

@MartinZikmund this looks to be related to multi-window changes

**Comment by takla21** [comment]
@kazo0 so subscribing to `ApplicationView.GetForCurrentView().VisibleBoundsChanged` works too. However, is it expected to be the permanent solution? Like, I tried to do the same on iOS and that event isn't being called at all.
