### ISSUE TITLE
[Android][iOS] `ApplicationView.GetForCurrentView().VisibleBounds` returns a Rectangle with all values set to 0

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#15521]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/17461593/2d995e7e-3d8c-4038-b9c4-046e36614082)

For instance, when having this logic to set the bottom bar
```cs
#if __ANDROID__ || __IOS__
        var full = App.Instance.MainWindow!.Bounds;
        var bounds = ApplicationView.GetForCurrentView().VisibleBounds;

        var bottomPadding = full.Bottom - bounds.Bottom;
#else
        var bottomPadding = 0;
#endif

        TestTextBlock.Text = bottomPadding.ToString();
        if (bottomPadding > 0)
        {
            SafeAreaRow.Height = new GridLength(bottomPadding);
        }
```

```xaml
<Grid>
  <Grid.RowDefinitions>
    <RowDefinition Height="*" />
    <!-- SafeAreaRow.Height is set in code behind -->
    <RowDefinition x:Name="SafeAreaRow"
                   Height="0" />
  </Grid.RowDefinitions>

  <TextBlock x:Name="TestTextBlock"
             FontSize="20"
             VerticalAlignment="Center" />

  <Border Background="Red"
          Grid.Row="1" />
</Grid>
```

it looks like this
![Screenshot_20240216-134700](https://github.com/unoplatform/uno/assets/17461593/71c5d950-b5a3-49ee-bd1e-18c7376ba66b)

### Expected behavior

![image (1)](https://github.com/unoplatform/uno/assets/17461593/91146172-7c2b-4be0-b15e-cea187f6a0c9)
`ApplicationView.GetForCurrentView().VisibleBounds` should return a `Rect` with the dimension of the screen excluding phone edges.

### How to reproduce it (as minimally and precisely as possible)

- Download this sample [BottomBoundsIssue-latest.zip](https://github.com/unoplatform/uno/files/14316759/BottomBoundsIssue-latest.zip)
- Deploy on Android/iOS

### Workaround

N/A

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.2.0-dev.683

### Affected platforms

Android, iOS

### IDE

Visual Studio 2022

### IDE version

17.10.0 Preview 1.0

### Anything else we need to know?

I've found this bug while trying to create a sample for this issue #15520

**Comment by jeromelaban** [comment]
This feels similar to https://github.com/unoplatform/nventive-private/issues/510, what do you think @kazo0?
