### ISSUE TITLE
[WASM] Controls inside a disabled ContentControl are not disabled

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#1559]
## Current behavior

In WASM a custom ContentControl's child elements are not disabled if the ContentControl itself is disabled.  In UWP disabling the ContentControl disables the children as well.

## Expected behavior

WASM behavior should match UWP.

## How to reproduce it (as minimally and precisely as possible)

In the attached project there are 3 controls - one regular TextBox, one disabled TextBox, and one ContentControl containing a Textbox.  In UWP the PointerEntered event only fires for the enabled TextBox, but in WASM the PointerEntered event fires for both the enabled TextBox and the TextBox inside the disabled ContentControl.
[DisabledControl.zip](https://github.com/unoplatform/uno/files/3626458/DisabledControl.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
1.29.0-dev.93
Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
Problems reported for Wasm described in this issue has been addressed and fixed in PR #1799.

Other problems for iOS & Android are moved to a new issue, #1800.

We can consider this issue as fixed.
