### ISSUE TITLE
`NavigationView` `MenuItems` not refreshing correctly on iOS or Android

### ISSUE THREAD

**Issue by cconner100** [unoplatform/uno#15608]
### Current behavior

On Windows i can change the menu items and the UI reflects these changes. with the same code they do not get updated on iOS or Android.  Attached is a small repro of the issue.  When runnin on any platform, open the Level 1 menu to show the sub menu items, then click Add item to home, it will add a new item to the list (works on windows) and then you can click Clear items from home (works on windows) both of these do not work on iOS or Android.

[NavigationViewTest.zip](https://github.com/unoplatform/uno/files/14381651/NavigationViewTest.zip)

### Expected behavior

I would expect the iOS and Android menus items to reflect the changes like they do in windows

### Workaround

None that i can find at this point

### Works on UWP/WinUI

Yes

### Environment

Other

### IDE

Visual Studio 2022, Visual Studio Code, Rider macOS

**Comment by MartinZikmund** [comment]
This might uncover some `ItemsRepeater` issue we don't handle

**Comment by ramezgerges** [comment]
This is also a problem on Skia and on WASM.
