### ISSUE TITLE
Frequent `AccessViolationException`

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/uno#15607]
### Current behavior

When running the Gtk head of a newly generated app it crashes often with the following `AccessViolationException` (no StackTrace):

![image](https://github.com/unoplatform/uno/assets/2716316/e17b376a-7967-457e-b076-3b2683bc60e2)

Here's what's printed to console:  
![image](https://github.com/unoplatform/uno/assets/2716316/605dc4d0-986a-4340-b822-ca7a55e7cdfc)

### Expected behavior

No exceptions.

### How to reproduce it (as minimally and precisely as possible)

1. Create a new project using wizard
2. Set Skia.Gtk as default head
3. Run app
4. Press any keyboard key while app focused

### Works on UWP/WinUI

Yes

### NuGet package version(s)

5.2.0-dev.880

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

17.9.1

**Comment by jeromelaban** [comment]
Gtk support is now legacy, using the new Desktop head is more stable
