### ISSUE TITLE
[droid] Support CommandParameter on AppBarButton

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#1562]
## Current behavior

A set CommandParameter on a AppBarButton ist not available on Android (don't know About iOs and WASM).

## Expected behavior

A CommandParameter is usable like on UWP.

## How to reproduce it (as minimally and precisely as possible)

Add an AppBarButton like this:

```xaml
<AppBarButton Label="Add photo..." Command="{x:Bind _vm.UploadFileCommand}" CommandParameter="Photo"/>
```
The string "Photo" is available within the command on UWP, but not on Android.
## Environment

Nuget Package: v1.46.228-dev.2681

Package Version(s):

Affected platform(s):
- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ajpinedam** [comment]
@TopperDEL  I followed your steps and could not reproduce the issue you reported. 

I am sending a string value as a `CommandParameter` and I am successfully receiving it as part of the `Command` execution.

Could you please update with your `Command` implementation.

Also, are you using any MVVM Framework? If so, which one and version.

Thanks.

**Comment by TopperDEL** [comment]
Strange. I can clearly reproduce it. I'm using no MVVM-Framework. You can see my coding here:

https://github.com/TopperDEL/uplink.net/blob/0d62407980c8d8151a80c265291032dec0c261a0/uplink.NET/uplink.NET.Sample/uplink.NET.Sample.Shared/Pages/BucketContentPage.xaml#L16

Did you try it on Android?

**Comment by ajpinedam** [comment]
Yes, tested on Android and the rest of the platforms. Used both the latest stable **1.45.0** but also the version you are using **1.46.28-dev.2681**

Will check your code. Thanks for the update @TopperDEL

**Comment by TopperDEL** [comment]
Damn it, I found my error.

On Android I'm using a click-handler (see https://github.com/TopperDEL/uplink.net/blob/70ccd6a4b44f35e07daac2fc18a4a236f5a8cb0c/uplink.NET/uplink.NET.Sample/uplink.NET.Sample.Shared/Pages/BucketContentPage.xaml.cs#L43) as the command did not work for whatever reason (have to check that again). But there I'm providing my null-value.

PICNIC - Problem in Chair not in Code

Sorry!

**Comment by ajpinedam** [comment]
@TopperDEL  Good! I missed that one! Nice you found it.
