### ISSUE TITLE
Explicit calls to `Measure` on UIElement cause layouting inconsistencies

### ISSUE THREAD

**Issue by ramezgerges** [unoplatform/uno#15644]
### Current behavior

On WinUI, it seems that when a `Measure` is explicitly called on an element with an availableSize != LastAvailableSize, it not only measures itself, but also its parent is measured (at least). On Uno's side, only the element itself is measured. Note however, that calling measure with LastAvailableSize won't measure anything both on WinUI or on Uno.

I found this while porting SplitView (#15585), and it seems that this might be a recurring problem with WinUI-ported controls that seem to explicitly call `Measure` with unexpected `availableSize`. I saw a similar problem with CommandBar a while back, although that doesn't seem to be an issue anymore.

### How to reproduce it (as minimally and precisely as possible)

```xaml
<StackPanel Orientation="Horizontal">
    <StackPanel x:Name="sp" Width="200">
      <TextBlock x:Name="tb" Text="small" />
      <ContentControl HorizontalContentAlignment="Center">
        <TextBlock Text="small" />
      </ContentControl>
    </StackPanel>
  <StackPanel Grid.Column="1">
    <Button Content="Whatever1" Click="Button_Click" />
    <Button Content="Whatever2" Click="Button_Click_2" />
  </StackPanel>
</StackPanel>
```

```csharp
public sealed partial class MainPage : Page
{
    public static FrameworkElement MeasuredElement;
    public MainPage()
    {
        this.InitializeComponent();
        MeasuredElement = sp;
    }

    private void Button_Click(object sender, RoutedEventArgs e)
    {
        tb.Text = "very very very very very very very very very very very very very very very very very very very very very very very very wide";
    }

    private void Button_Click_1(object sender, RoutedEventArgs e)
    {
        tb.Text = "small";
    }

    private void Button_Click_2(object sender, RoutedEventArgs e)
    {
        MainPage.MeasuredElement.Measure(LayoutInformation.GetAvailableSize(MainPage.MeasuredElement) with { Width = 1000 });
    }
}
```

press the first button and then the second button. The second textblock should not move after you press the second button.

### Works on UWP/WinUI

None

**Comment by ramezgerges** [comment]
Investigation details: it seems that it's not strictly related to availableSize being different, but with desiredSize changing. When calling Measure with a different availableSize that yields the same desiredSize, the parent of the element doesn't get measured again, which makes sense.

**Comment by Youssef1313** [comment]
Relevant pieces from WinUI source:

![image.png](https://github.com/unoplatform/uno/assets/31348972/80914c54-1b11-4d16-a4fc-971e5893f717)
