### ISSUE TITLE
Add "too long path" detection mechanism

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#1564]
Sometimes when a user is cloning a project from github, the default location could be in a place where the path would be too long and will cause problem during the compilation.

Those errors are hard to detect and the error message is unclear.

## What would you like to be added:
Add a "too long path" detection mechanism to warn the user when it's compiled from a very long path.

## For which Platform:

- [X] iOS
- [X] Android
- [X] WebAssembly
- [X] Windows
- [X] Every other project types

## Anything else we need to know?
That's a 1-billion dollar bug from Windows.

**Comment by kharaone** [comment]
isn't that supposed to be not an issue anymore on windows 10 + .net 4.6.2+ ?

**Comment by geisterfurz007** [comment]
Whereabouts would a check like that need to be added?  
I know this isn't labeled Good first issue but I would still love to try and help out with this :)
