### ISSUE TITLE
Double 'Clear Text' Button in TextBox on MS Edge for WASM Project

### ISSUE THREAD

**Issue by Yortw** [unoplatform/uno#1569]
## Current behavior

When running the module 9 sample app from the Uno Workshop, targeting WASM and running in the *Edge* browser, the text field will show two separate 'clear' buttons. One provided by edge and one provided by Uno (or the control style in the app?). The Uno button clears the text and removes both buttons, however the Edge button clears the text but leaves the Uno clear button visible.

![image](https://user-images.githubusercontent.com/6725891/65352654-4890a480-dc3f-11e9-9394-f6c98066556f.png)

## Expected behavior
Ideally only one clear button should be shown within the textbox. Failing that, both buttons should work the same way.

## How to reproduce it (as minimally and precisely as possible)

Open the module 9 'todo' app from the Uno Workshop repo.
Switch to the WASM target and start without debugger.
If Edge is not your default browser, open Edge and navigate to the url for the app.
Click in the 'new to do item' textbox and type some text (don't press enter).
Notice two X buttons are displayed at the right of the text field.

## Environment

VS2019, Edge, WASM.

Nuget Package/Version:
Uno.Core 1.29.0-dev.93
Uno.UI 1.46.230-dev.2711
Uno.Wasm.Bootstrap 1.0.0-dev.302

Affected platform(s):
- [ ] iOS
- [ ] Android
- [X ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [X ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?
Advised to log this as an issue by Uno team members.

**Comment by ghuntley** [comment]
<3 Thanks for raising this.

**Comment by smikis** [comment]
Seems like good first issue to tackle. Can I take this?

**Comment by jeromelaban** [comment]
@smikis Sure, let us know what you find here !

**Comment by smikis** [comment]
I added class which hides additional clear button for input fields in  Internet Explorer / Edge. Please advice if I did something wrong and I'll try to fix it

**Comment by Youssef1313** [comment]
@MartinZikmund @jeromelaban Let's get this one closed. Should be already fixed in https://github.com/unoplatform/uno/pull/6807.
