### ISSUE TITLE
`TakeScreenshot` throws `AccessViolationException`

### ISSUE THREAD

**Issue by HakanL** [unoplatform/uno#15738]
### Current behavior

I have a Skia Gtk host and I'm trying to take a screenshot of the current window. When calling `host.TakeScreenshot(filePath)` I'm getting an `AccessViolationException` error.

I have tried using Gdk.Pixbuf as well, and it works sometimes, but after a few attempts I get the `AccessViolationException` exception again (and my app crashes). This is the code for using Gdk.Pixbuf:
```
var window = host.Window.Window;
using var pixBuf = new Gdk.Pixbuf(window, 0, 0, window.Width, window.Height);
pixBuf.Save(tempFile, "png");
```

### Expected behavior

A screenshot is taken and saved to the file

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

<PackageReference Include="Uno.Extensions.Authentication.WinUI" Version="4.0.0" />
<PackageReference Include="Uno.Extensions.Configuration" Version="4.0.0" />
<PackageReference Include="Uno.Extensions.Logging.Serilog" Version="4.0.0" />
<PackageReference Include="Uno.Extensions.Logging.WinUI" Version="4.0.0" />
<PackageReference Include="Uno.Extensions.Navigation.Toolkit.WinUI" Version="4.0.0" />
<PackageReference Include="Uno.Extensions.Navigation.WinUI" Version="4.0.0" />
<PackageReference Include="Uno.Material.WinUI" Version="4.1.1" />
<PackageReference Include="Uno.Resizetizer" Version="1.3.0" />
<PackageReference Include="Uno.Toolkit.WinUI" Version="5.1.7" />
<PackageReference Include="Uno.Toolkit.WinUI.Material" Version="5.1.7" />
<PackageReference Include="Uno.WinUI" Version="5.1.80" />

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. This API is not particularly well supported, and you should be using `RenderTargetBitmap` instead.

**Comment by HakanL** [comment]
Thanks @jeromelaban, something that should be easy, but I can't seem to figure it out, how can I save a PNG from a `RenderTargetBitmap`?

**Comment by Youssef1313** [comment]
@HakanL See https://github.com/unoplatform/uno/blob/b59b360f05e713da1f01a5b3c761fa140de56221/src/Uno.UI.RuntimeTests/Helpers/RawBitmap.cs#L150-L164

**Comment by HakanL** [comment]
@Youssef1313 Thanks! It seems this class isn't made available in the Nuget packages, is there something that can save the image via something in Uno, or do I basically have to copy this class (plus the ImageHelper which is `internal`)?

**Comment by Youssef1313** [comment]
Yes it's not public as it's not a WinUI API. You'll need to copy it, but I think you don't really need the `ImageHelper` class. Here is a simplified version:

```csharp
	public class RawBitmap
	{
		private byte[]? _pixels;
		private readonly double _implicitScaling;

		private RawBitmap(RenderTargetBitmap bitmap, UIElement renderedElement, double implicitScaling)
		{
			Bitmap = bitmap;
			RenderedElement = renderedElement;
			_implicitScaling = implicitScaling;
		}

		public static async Task<RawBitmap> From(RenderTargetBitmap bitmap, UIElement renderedElement, double? implicitScaling = null)
		{
			implicitScaling ??= renderedElement.XamlRoot?.RasterizationScale ?? 1;
			var raw = new RawBitmap(bitmap, renderedElement, implicitScaling.Value);
			await raw.Populate();

			return raw;
		}

		public double ImplicitScaling => _implicitScaling;

		public Size Size => new(Width, Height);

		public int Width => (int)(Bitmap.PixelWidth / _implicitScaling);
		public int Height => (int)(Bitmap.PixelHeight / _implicitScaling);

		/// <summary>
		/// The rendered UIElement
		/// </summary>
		public UIElement RenderedElement { get; }

		/// <summary>
		/// Gets the underlying <see cref="RenderTargetBitmap"/>.
		/// Be aware this might not be the same as of the current state of the RawBitmap (cf. <see cref="MakeOpaque"/>).
		/// Prefer to use the <see cref="GetImageSource"/>.
		/// </summary>
		internal RenderTargetBitmap Bitmap { get; }

		/// <summary>
		/// Enables the <see cref="GetPixel(int, int)"/> method.
		/// </summary>
		/// <returns></returns>
		internal async Task Populate()
		{
			_pixels ??= (await Bitmap.GetPixelsAsync()).ToArray();
		}

#if __SKIA__
		internal async Task Save(string path)
		{
			if (_pixels is null)
			{
				throw new InvalidOperationException("Populate must be invoked first");
			}

			await using var file = File.OpenWrite(path);

			var img = SkiaSharp.SKImage.FromPixelCopy(new SkiaSharp.SKImageInfo(Bitmap.PixelWidth, Bitmap.PixelHeight, SkiaSharp.SKColorType.Bgra8888, SkiaSharp.SKAlphaType.Unpremul), _pixels);

			img.Encode(SkiaSharp.SKEncodedImageFormat.Png, 100).SaveTo(file);
		}
#endif
```

Usage will be:

```csharp
var renderTargetBitmap = new RenderTargetBitmap();
await renderTargetBitmap.RenderAsync(yourElement);
var bitmap = await RawBitmap.From(renderTargetBitmap, yourElement);
bitmap.Save(filePath);
```

**Comment by HakanL** [comment]
Got it, wasn't sure if there was a different way, I tried to go down the path of SoftwareBitmap, this is much better, works great now, thank you!

**Comment by HakanL** [comment]
@jeromelaban It's possible the AccessViolationException was due to me calling it on a non-UI thread, but it may be worthwhile to add a sanity-check so it doesn't crash. I actually ran into the same issue with the `RenderTargetBitmap`, which is of course my fault, but it's easy to forget :)

**Comment by MartinZikmund** [comment]
@HakanL as GTK is in legacy support mode, I will close this issue, as we will not likely be addressing it

**Comment by HakanL** [comment]
@MartinZikmund Is there any documentation on how to upgrade from GTK to Desktop? I've tried to create a new application using the templates, but since my real application is like 2 years old, the differences are quite big (single project, etc) and it's hard to figure out a good starting point. Could I perhaps start with just changing GtkHost to SkiaHostBuilder?

**Comment by jeromelaban** [comment]
@HakanL Let's continue in https://github.com/unoplatform/uno/discussions/17571.
