### ISSUE TITLE
[Droid]TextBox.CharacterCasing is not respected

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#1574]
## Current behavior
If I set the Property CharacterCasing on TextBox via XAML (e.g. to "Lower"), it works on UWP but not on Android. Did not test WASM and iOs.

## Expected behavior
The CharacterCasing is respected on Android, too.

## How to reproduce it (as minimally and precisely as possible)
Add a TextBox to a page and set it's CharacterCasing to "Lower". On UWP you can't enter uppercase Characters. On Android, the upperace characters are shown.

## Environment

Nuget Package: v1.46.230-dev.2733

Package Version(s):

Affected platform(s):
- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?
See Remarks [here](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.textbox.charactercasing?view=netframework-4.8). Maybe the characters are entered programmatically on Android?

**Comment by ajpinedam** [comment]
@ghuntley  @davidjohnoliver Would you assign this one to me?
