### ISSUE TITLE
[Skia.GTK] New app does not render well on macOS

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#15744]
### Current behavior

- I followed the starter guide to setup VS Code and Uno Platform on a Mac.
- I created a default app.
- When debugging this app, the UI does not look like the Windows version. There is a rectangle at the bottom right corner.

![image](https://github.com/unoplatform/uno/assets/1608424/8a61d710-3a47-4387-84c6-46da18653582)

### Expected behavior

Same as Windows

### How to reproduce it (as minimally and precisely as possible)

Follow the guide: https://platform.uno/docs/articles/create-an-app-vscode.html?tabs=skiagtk

### Works on UWP/WinUI

None

### Environment

Other

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio Code

### IDE version

Latest VS Code

**Comment by jeromelaban** [comment]
Thanks for the report! We're aware of this issue and we're working on it.

**Comment by MartinZikmund** [comment]
@ArchieCoder GTK has now been deprecated in favor of our new Skia Desktop support which is native on macOS. Please switch to this new target and this issue will no longer occur.
