### ISSUE TITLE
REST API call using refit is not working on WASM

### ISSUE THREAD

**Issue by anaselhajjaji** [unoplatform/uno#1575]
Using the sample app: https://github.com/anaselhajjaji/UnoBench

## Current behavior

Running the WASM version of the app leads to an empty screen.

## Expected behavior

The list should be shown as for UWP app.

## How to reproduce it (as minimally and precisely as possible)

Run the WASM sample => empty screen.

## Environment

Nuget Package:

![image](https://user-images.githubusercontent.com/3309485/65390494-8cfa6e00-dd2d-11e9-999f-5fd5f36c89d1.png)

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by anaselhajjaji** [comment]
I fixed it myself, I found that for http calls we should use Uno.UI.Wasm.WasmHttpHandler()
Automatically, we shouldn't expect refit working to simplify rest api call.
I updated my sample in github: https://github.com/anaselhajjaji/UnoBench

**Comment by ghuntley** [comment]
Howdy @anaselhajjaji see https://github.com/anaselhajjaji/uno-platform-sample/issues/1
