### ISSUE TITLE
`InfoBar` missing Fluent warning icon

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#15794]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/78549750/06ae626d-79c5-49d8-91a7-82482c5cfea5)

### Expected behavior

![image](https://github.com/unoplatform/uno/assets/78549750/8502fb42-40a1-4287-b29e-24978cf4b740)

### Works on UWP/WinUI

Yes

### Affected platforms

Android, iOS
Desktop (Skia)
WASM

**Comment by morning4coffe-dev** [comment]
The Glyph `&#xF13C;` seems to be missing on all Uno targets

**Comment by MartinZikmund** [comment]
@NVLudwig would it be possible to add this glyph to Uno.Fluent icon font please?

**Comment by NVLudwig** [comment]
Done :)

**Comment by agneszitte** [comment]
> @NVLudwig would it be possible to add this glyph to Uno.Fluent icon font please?

@MartinZikmund https://github.com/unoplatform/uno.fonts will need to be updated?

**Comment by MartinZikmund** [comment]
Yes, got the updated font from @NVLudwig , will make PR

**Comment by agneszitte** [comment]
@jeromelaban, @MartinZikmund Uno.Fonts [2.4.0-dev.6](https://www.nuget.org/packages/Uno.Fonts.Fluent/2.4.0-dev.6) was released. We would need to release a new stable package for Uno.Fonts and [update the version in the Uno repo](https://github.com/search?q=repo%3Aunoplatform%2Funo+version%3D%222.3.0%22&type=code) as well right?

**Comment by jeromelaban** [comment]
We can make a release yet, it seems that other changes are needed.

**Comment by agneszitte** [comment]
> We can make a release yes, it seems that other changes have been merged.

@jeromelaban We have https://github.com/unoplatform/uno.fonts/pull/39 and https://github.com/unoplatform/uno.fonts/pull/41 as changes since the last stable
