### ISSUE TITLE
Support Keyboard shortcuts don't work for Skia Desktop

### ISSUE THREAD

**Issue by Suriman** [unoplatform/uno#15796]
### Current behavior

When hovering the TabViewItem tab, a ToolTip with the TabViewItem's Header text should be shown but don't. Also, the Ctrl+F4 shortcut for closing the current tab doesn't work.

### Expected behavior

The ToolTip shows up and the keyboard shortcuts work.

### How to reproduce it (as minimally and precisely as possible)

[WpfToolTipsShortcuts.zip](https://github.com/unoplatform/uno/files/14695408/WpfToolTipsShortcuts.zip)

 1. Open the attached solution and compile it.
 2. Execute it in Skia.WPF head.
 3. Hover the TabViewItem tab.
 4. Compare with WinUI so you can see the difference.

### Workaround

No known workaround.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.WinUI 5.1.80

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.9.2

**Comment by sasakrsmanovic** [comment]
[WpfToolTipsShortcuts.zip.txt](https://github.com/unoplatform/uno/files/14539402/WpfToolTipsShortcuts.zip.txt)
Here is the file Suriman wanted to attach; he had troubles attaching it.

**Comment by ramezgerges** [comment]
@sasakrsmanovic The file you sent is actually a text file with "attachment was removed"

**Comment by jeromelaban** [comment]
@Suriman the repro you provided is not the right one. You should be able to attach it here as a zip, using drag and drop. Make sure to follow [these steps for creating a repro](https://platform.uno/docs/articles/uno-howto-create-a-repro.html?tabs=windows-vs).

**Comment by jeromelaban** [comment]
@ramezgerges the repro is now attached.

**Comment by brinko99** [comment]
ToolTips are disabled by default. See: https://platform.uno/docs/articles/feature-flags.html#tooltips

Enable them with the `FeatureConfiguration.ToolTip.UseToolTips` flag.

```
public AppHead()
{
    FeatureConfiguration.ToolTip.UseToolTips = true;
    this.InitializeComponent();
}
```

Incidentally, it is usually suggested to use the `__SKIA__` build constant as below. But this has never worked for me...

```
#if __SKIA__
        FeatureConfiguration.ToolTip.UseToolTips = true;
#endif
```

**Comment by ADD-Noureddine-Maachi** [comment]
This works properly, thank you so much!

What about the Ctrl + F4 shortcut that shows up in the tooltip? Does not work for Skia but it works for WinUI. I mentioned this in the description of the issue.

Thanks in advance!

**Comment by agneszitte** [comment]
> What about the Ctrl + F4 shortcut that shows up in the tooltip? Does not work for Skia but it works for WinUI. I mentioned this in the description of the issue.

fyi @jeromelaban, @MartinZikmund

**Comment by MartinZikmund** [comment]
This requires keyboard accelerators API, I have PR draft for that, will finish it as soon as possible

**Comment by MartinZikmund** [comment]
This is implemented via https://github.com/unoplatform/uno/pull/15245 (includes `TabView` support)

**Comment by ADD-Noureddine-Maachi** [comment]
I've tried it and it works fine! Thanks @MartinZikmund 😊

**Comment by MartinZikmund** [comment]
Awesome, closing!
