### ISSUE TITLE
Receiving "warning : Didn't find UnoSplashScreen."

### ISSUE THREAD

**Issue by IneedHelp** [unoplatform/uno#15790]
### Current behavior

I'm getting this warning in VS 2022 latest preview version (uno sdk 5.1.87):
C:\Users\Me\.nuget\packages\uno.resizetizer\1.3.0\build\Uno.Resizetizer.wasm.targets(9,3): warning : Didn't find UnoSplashScreen.
after adding the Uno.WinUI.Runtime.WebAssembly to a Uno WASM project

### Expected behavior

not to get the warning

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
@pictos does this look familiar?

**Comment by pictos** [comment]
@IneedHelp can you provide a sample project? I tried on my end and couldn't reproduce the issue.
![image](https://github.com/unoplatform/uno/assets/20712372/a45b2ccd-0af2-4f94-a2d0-dcf234b3e0ac)


Maybe, on your project you're not using `UnoSplashScreen` and because of that it shows up for you?

**Comment by pedrojesus-work** [comment]
@IneedHelp can you provide a sample project? I tried on my end and couldn't reproduce the issue.
![image](https://github.com/unoplatform/uno/assets/20712372/a45b2ccd-0af2-4f94-a2d0-dcf234b3e0ac)


Maybe, on your project you're not using `UnoSplashScreen` and because of that it shows up for you?

**Comment by IneedHelp** [comment]
@pedrojesus-work I apologize, I haven't provided the full details as a couple of weeks ago I was still discovering a lot about Uno and how it works. So basically, I am getting this warning when using the `Uno.WinUI.Runtime.WebAssembly` package to a referenced project:

![image](https://github.com/unoplatform/uno/assets/1366970/b1876f25-300b-43b7-b6bb-7577b61124b4)

In your case, try adding it to:
![image](https://github.com/unoplatform/uno/assets/1366970/643de211-d4d1-4004-b864-dcd579be06a2)
and then compile.

**Comment by pedrojesus-work** [comment]
@jeromelaban after adding the `Uno.WinUI.Runtime.WebAssembly` package on the shared class lib. the `UnoRuntimeIdentifier` becomes `WebAssembly` for all targets (android, ios, windows, etc), is that the correct behavior?

[binlog.zip](https://github.com/unoplatform/uno/files/14651894/binlog.zip)
[UnoApp13.zip](https://github.com/unoplatform/uno/files/14651912/UnoApp13.zip)

**Comment by IneedHelp** [comment]
> @jeromelaban after adding the `Uno.WinUI.Runtime.WebAssembly` package on the shared class lib. the `UnoRuntimeIdentifier` becomes `WebAssembly` for all targets (android, ios, windows, etc), is that the correct behavior?
> 
I think I have noticed a problem with this and I had to explicitly exclude `Uno.WinUI.Runtime.WebAssembly` package from the net8windows10 target, otherwise it would cause issues with some conditional compilation.

**Comment by jeromelaban** [comment]
@pedrojesus-work it's expected that `Uno.WinUI.Runtime.WebAssembly` will do what you noticed, it also should never be added explicitly.

**Comment by pedrojesus-work** [comment]
cc @IneedHelp

**Comment by jeromelaban** [comment]
@IneedHelp can you provide a [sample that reproduces the issue](https://platform.uno/docs/articles/uno-howto-create-a-repro.html?tabs=windows-vs)? It looks like we're not able to.

**Comment by IneedHelp** [comment]
@jeromelaban I wanted to have a separate library containing utility functions which involve CSS, so I had to add `Uno.WinUI.Runtime.WebAssembly`

**Comment by jeromelaban** [comment]
@IneedHelp Thanks. Your separate class library needs to be referenced only from the wasm head, and no other projects. This means that you'll need to have some sort of interface based dependency injection to be able to use that code from other projects in the solution.

This is something that we're currently adjusting for 5.2 to make those scenarios easier.

**Comment by IneedHelp** [comment]
> @IneedHelp Thanks. Your separate class library needs to be referenced only from the wasm head, and no other projects. This means that you'll need to have some sort of interface based dependency injection to be able to use that code from other projects in the solution.

I'm a bit confused about this. I need to use methods such as `Microsoft.UI.Xaml.UIElementWasmExtensions.SetCssStyle` of the `Uno.WinUI.Runtime.WebAssembly` in the shared library, where all the XAML stuff happens, and attributes such as `Uno.UI.Runtime.WebAssembly.HtmlElementAttribute.HtmlElementAttribute` also in the shared library (and referenced libraries), so it would seem a bit difficult to do that if I add `Uno.WinUI.Runtime.WebAssembly` only to the WASM project.
