### ISSUE TITLE
ComboBox doesn't open inside a ContentDialog

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#1583]
## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
Fixed for WASM by #1566. Not working on Android, not tested on iOS.

**Comment by e-leoni** [comment]
Same problem for me in Android.
How can I solve it?

**Comment by jeromelaban** [comment]
Android currently uses native popups, which prevents this from working properly. You can change this by setting this flag to false:
https://github.com/unoplatform/uno/blob/4821fbe7f39634bb87cbcf9c973fc7b52e8741e4/src/Uno.UI/FeatureConfiguration.cs#L224

**Comment by e-leoni** [comment]
@jeromelaban I set
`Uno.UI.FeatureConfiguration.Popup.UseNativePopup = false;`
in Onlaunched and it works.
Thank you very much for help me.
Do you know a way to show HTML formatted text into a textbox?

**Comment by MartinZikmund** [comment]
Native popups are not used anymore, so this can be closed.
