### ISSUE TITLE
[WASM] How to get rid of RemoteControlClient errors while viewing WASM page locally?

### ISSUE THREAD

**Issue by IneedHelp** [unoplatform/uno#15849]
### Current behavior

Is there any way to get rid of these errors when viewing WASM locally without having to filter out errors in the browser console?
![bvm0y](https://github.com/unoplatform/uno/assets/1366970/b89f786f-17cb-47a6-87e8-821b056924e4)

### Expected behavior

Not to get those errors in the browser console which are apparently cause by `Uno.UI.RemoteControl.RemoteControlClient` attempting to make some connections on different interfaces.

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
Thanks for the report. At this time, aside from removing the Uno.WinUI.DevServer package, there isn't any way to avoid those errors. We're exploring options on how to reduce that, though.

**Comment by IneedHelp** [comment]
I understand, thank you for the responding.
