### ISSUE TITLE
TransformToVisual should rely on Visual's total matrix

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#15854]
### What would you like to be added

Currently the `UIElement.TransformToVisual`(https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.transformtovisual?view=winrt-22621) is implemented by walking up (and down) the tree of `UIElement` and computing the transform matrix based on captured layouting values, `RenderTransform`, scrolling offsets etc.

But on skia, where we properly draw an position each item by our own, we already have that exact matrix available on [`SKCanvas.TotalMatrix`](https://learn.microsoft.com/en-us/dotnet/api/skiasharp.skcanvas.totalmatrix?view=skiasharp-2.88) (which basically represents the "visual to root transform").

We should capture it on each rendering loop and use it in the `TransformToVisual` implementation.

### Why is this needed

This would make the `TransformToVisual` incredibly faster and, as those is used a lot in input dispatching, also make the inputs much faster.

**Comment by dr1rrb** [comment]
> IIRC, when I attempted to do this previously, there was a problem when `TransformToVisual` is called **after** arrange but **before** render. For this scenario, we don't yet have the matrix.

Who is calling the `TransformToVisual` ? I would assume it's only because we are not yet synchronizing pointer events with the render as it should.

For instance if we change a `RenderTransform` and invoke `TransformToVisual` right after (and before the change is being rendered) on windows, does the transform is already take in consideration or not?

**Comment by Youssef1313** [comment]
@dr1rrb In runtime tests, I had a test which adds something to window content, and after it's arranged but before it's rendered, TransformToVisual didn't produce the right matrix. The same test passed on WinUI.

Maybe on WinUI it could be that it has done both arrange and render while in our case only arrange was done? But either way, we won't want to regress this if it currently works correctly.

**Comment by ramezgerges** [comment]
#15875 had a lot of failing tests because of this, mostly to do with scrolling and EVP. For instance, `SystemFocusVisual` uses `TransformToVisual` to set its offset. Besides, `TransformToVisual` is public, so we wouldn't want to break it.

I tested on WinUI and the effect is immediate with `RenderTransform` (and I'm assuming everything else).
