### ISSUE TITLE
`HitTest` should rely on `Visual`

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#15855]
### What would you like to be added

The hit-testing algorithm should rely on `Visual` instead of `UIElement`'s position. Basically on Windows, the hist tests is all about "does the element as draw something non transparent on the given pixel".

### Why is this needed

* It would improve performance by allowing us to properly hit-test on the compositor thread (when we will finally have it - https://github.com/unoplatform/uno/issues/15854  might be needed first) in sync with the frame currently visible, dispatch to `InteractionTracker` if relevant or pushing it to the `UIElement` on UI thread.
* Fix issue with `Shape` hit-testing : a `Shape` should be hit-testable only on drawn pixels, not on the whole "drawing area/rectangle" like it is currently

**Comment by ramezgerges** [comment]
Two observations:
* >Basically on Windows, the hist tests is all about "does the element as draw something non transparent on the given pixel".
  
  This isn't entirely accurate. If, for example, you draw a transparent shape, you can still receive pointer events on it. It's more like "does the element draw *something* on the given pixel?".
  
* > Fix issue with Shape hit-testing : a Shape should be hit-testable only on drawn pixels
  Actually, we can rely ONLY on shape hit-testing. In other words, we can view each element as a collection of shapes, and an element can be hit if one of its shapes contains with the given pixel.
  If we get this to work, we can drop `IsViewHit` and `HitTestability.Invisible`. An element is either `Visible` or `Collapsed`, and HitTest(element) should be true if it's both Visible and it contains a shape containing the pixel as mentioned earlier.
