### ISSUE TITLE
Icons in Listview slow to Update

### ISSUE THREAD

**Issue by ramezgerges** [unoplatform/uno#15861]
I have a strange issue, which I'm not sure if it's something I'm doing, or a bug. I have a page with a ListView, which then has a WrapPanel from the community toolkit. I'm displaying Toolkit Cards in it with an icon, two lines of text. It looks like this, works great:
![image](https://github.com/unoplatform/uno/assets/407941/98fae925-dd2f-4944-9829-b6dfadc6c3ba)

If I click on one of the cards, I'm navigating to a sub menu, which is essentially the same view, but with a new instance of a view model (that has a new set of menu items, in a `ObserverableCollection`). The issue is that for a split second (which is more obvious on a RPi that is slower to process) the icons from the first list of menu items are used on the new list. It looks like this:
![image](https://github.com/unoplatform/uno/assets/407941/b5b8f146-7c92-419b-97e8-c540262af464)

But the next "frame" shows the correct icons:
![image](https://github.com/unoplatform/uno/assets/407941/ff2f4f3a-179b-4b49-9b0d-87aac0e0ebe6)

I can't figure out why this happens. I've traced the code, I get my new instance of the VM, I set the list of menu items, it never has the old icons with the new menu items. It's like the icons are cached or something. Is there a workaround where I can pause screen refresh until everything is updated, or another way to solve it? It looks strange when the icons changed after the menu is updated.

_Originally posted by @HakanL in https://github.com/unoplatform/uno/discussions/14047_

**Comment by ramezgerges** [comment]
Related to #8607

**Comment by ramezgerges** [comment]
@HakanL There are multiple parts to the issue:

* I've tried to cleverly get an image placeholder to work using back buffers and loading events, but ultimately, the thing that worked was wrapping the `Image` of interest in a grid that contains another `Image` with the placeholder. The placeholder image should be first in the wrapper grid (or have a lower `Canvas.ZIndex`, which works only on skia). This way, the placeholder will show up and then become covered by the actual image. Note that this will only work with opaque images. You can probably set the visibility of the placeholder image to Collapsed in a callback to the actual image's `ImageOpened` event. This only works for images that are set once, not for images that might have a changing `Source`, but that might be enough for some use cases. I couldn't find a more robust or general solution.

* Besides placeholders, if you want to keep the area of the image intact when the `Source` changes until it loads, you can set the `Width` and `Height` of the image, which will keep the image are occupied even if the image hasn't been loaded yet.

* The previous points were also problematic on WinUI. The only difference in Uno was that changing the image `Source` would cause the previous image to stay there until the new image loads, instead of clearing. This PR fixes this.

Let us know if this works for you.

**Comment by HakanL** [comment]
@ramezgerges Thanks for the suggestions. I ended up setting the image width/height for the avatar in the grid and now at least the text of the cards don't move around, so this is pretty good to me. My preference would still be to "freeze" the UI until everything is loaded so it would just nicely flip over.
