### ISSUE TITLE
[WASM] FontIcon `AddBold (&#xF8AA;)` not display

### ISSUE THREAD

**Issue by SongOfYouth** [unoplatform/uno#15873]
### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
@SongOfYouth Thanks for reporting this. Can you please upload a repro project?

**Comment by Youssef1313** [comment]
@NVLudwig It looks like we are missing a glyph in the font file.

@SongOfYouth As a workaround, you can use `<FontIcon Glyph="&#xE710;" />`. It's not really the same glyph but quite close.

**Comment by SongOfYouth** [comment]
> @NVLudwig It looks like we are missing a glyph in the font file.
> 
> @SongOfYouth As a workaround, you can use `<FontIcon Glyph="&#xE710;" />`. It's not really the same glyph but quite close.

Yes, i have handled it the same way.

**Comment by MartinZikmund** [comment]
Moving this to Fonts, CC @NVLudwig

**Comment by NVLudwig** [comment]
@MartinZikmund I think you might have to update to the latest version of the font it's already there for you :)

**Comment by MartinZikmund** [comment]
@SongOfYouth Please try updating the `Uno.Fonts.Fluent` package in your project, as @NVLudwig mentions, the glyph should be there 👍

**Comment by NVLudwig** [comment]
Closing the issue but feel free to reopen if I missed something
