### ISSUE TITLE
[WASM] `ComboBox` dosn't display anything when having a SelectedValue set via binding the `ItemsSource`

### ISSUE THREAD

**Issue by SongOfYouth** [unoplatform/uno#15881]
### Current behavior

A detault SelectedItem will be set to the bindinged property when the ItemsSource of combobox bindinged on windwos or else, but it not on wasm.

### Affected platforms

WebAssembly

**Comment by SongOfYouth** [comment]
And the event `SelectionChanged` occursed at the same time where ItemsSource bindinged even the combobox haven't displayed anything!

**Comment by jeromelaban** [comment]
Thanks for the report! Could you create a [repro sample](https://platform.uno/docs/articles/uno-howto-create-a-repro.html?tabs=windows-vs)?

**Comment by AdriaanLarcai** [comment]
Can confirm this is happening in our project as well.

**Comment by SongOfYouth** [comment]
[WasmSample.zip](https://github.com/unoplatform/uno/files/14647252/WasmSample.zip)
@jeromelaban @AdriaanLarcai

**Comment by jeromelaban** [comment]
## Note for contributors

This particular issue is caused by the ComboBox resetting the selected index when the collection changed, as discussed during [this live stream](https://www.twitch.tv/videos/2096154426), something that WinUI does not do. The assumption is that WinUI keeps the locally set value, regardless of its validity, and applies it to the new collection.

A workaround could be to force the selected value via a binding once the itemssource has been set.

**Comment by SongOfYouth** [comment]
> ## Note for contributors
> This particular issue is caused by the ComboBox resetting the selected index when the collection changed, as discussed during [this live stream](https://www.twitch.tv/videos/2096154426), something that WinUI does not do. The assumption is that WinUI keeps the locally set value, regardless of its validity, and applies it to the new collection.
> 
> A workaround could be to force the selected value via a binding once the itemssource has been set.

Note that the SelectionChanged event triggered twice with the resetting.

**Comment by SongOfYouth** [comment]
> ## Note for contributors
> This particular issue is caused by the ComboBox resetting the selected index when the collection changed, as discussed during [this live stream](https://www.twitch.tv/videos/2096154426), something that WinUI does not do. The assumption is that WinUI keeps the locally set value, regardless of its validity, and applies it to the new collection.
> 
> A workaround could be to force the selected value via a binding once the itemssource has been set.

Note that the SelectionChanged event triggered twice with the resetting.
