### ISSUE TITLE
Updating a text block in ListView would cause flickering effect

### ISSUE THREAD

**Issue by libra34567** [unoplatform/uno#15917]
### Current behavior

1. Uno platform targeting windows
2. Have a textBlock under listView
3. In model keep updating the content of textBlock
4. The flicker would appear

https://github.com/unoplatform/uno/assets/6408562/a0c861c7-d73d-4547-9e37-49b811ac8da0

### Expected behavior

Not flicker

### How to reproduce it (as minimally and precisely as possible)

Simply run the project in visual studio

[multi-agents-client.zip](https://github.com/unoplatform/uno/files/14639486/multi-agents-client.zip)

### Workaround

not yet found

### Works on UWP/WinUI

None

### Affected platforms

Windows

### IDE

Visual Studio 2022

**Comment by MartinZikmund** [comment]
As this is a WinUI issue, I think it can be closed. @libra34567 please open the issue on https://github.com/microsoft/microsoft-ui-xaml/
