### ISSUE TITLE
Unable to define XML namespaces directly on controls in XAML

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno#15927]
### Current behavior

We are getting an error at the moment when XML namespaces are directly defined on a control

```
1>CSC : error UXAML0001: The type controls:EmbeddedControl could not be found
1>C:\Dev\Samples\MauiSampleApp\MauisampleApp\MainPage.xaml(17,6,17,6): error UXAML0001: An error was found in Grid
1>C:\Dev\Samples\MauiSampleApp\MauisampleApp\MainPage.xaml(11,4,11,4): error UXAML0001: An error was found in StackPanel
1>C:\Dev\Samples\MauiSampleApp\MauisampleApp\MainPage.xaml(1,2,1,2): error UXAML0001: An error was found in Page
1>CSC : error UXAML0001: Processing failed for file C:\Dev\Samples\MauiSampleApp\MauisampleApp\MainPage.xaml (Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in Page ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in StackPanel ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in Grid ---> System.InvalidOperationException: The type controls:EmbeddedControl could not be found
1>C:\Dev\Samples\MauiSampleApp\MauisampleApp\MainPage.xaml.cs(7,14,7,33): error CS1061: 'MainPage' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)
```

Related XAML:
```
<Page x:Class="MauisampleApp.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:MauisampleApp"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      xmlns:maui="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:not_maui="http://notmaui"
      mc:Ignorable="d not_maui"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
  <StackPanel HorizontalAlignment="Center"
              VerticalAlignment="Center">
    <TextBlock AutomationProperties.AutomationId="HelloTextBlock"
               Text="Hello Uno Platform"
               HorizontalAlignment="Center" />
    <maui:Grid>
      <embed:MauiHost x:Name="MauiHostElement"
                      xmlns:embed="using:Uno.Extensions.Maui"
                      xmlns:controls="using:MauisampleApp.MauiControls"
                      Source="controls:EmbeddedControl" />
    </maui:Grid>
    <not_maui:Grid>
      <TextBlock AutomationProperties.AutomationId="NotMauiTextBlock"
                 Text="Alternative content for Non-Maui targets"
                 HorizontalAlignment="Center" />
    </not_maui:Grid>
  </StackPanel>
</Page>
```

### Expected behavior

There should be no error

### How to reproduce it (as minimally and precisely as possible)

[MauiSampleApp.zip](https://github.com/unoplatform/uno/files/14641504/MauiSampleApp.zip)
- Launch the attached sample app
- Try to launch and run the sample app for the maui supported platforms
- Notice the error

### Workaround

Moving the  XML namespaces at the page level for example

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

5.1.50

### Affected platforms

All

### IDE

Visual Studio 2022

### IDE version

Version 17.9.2

### Relevant plugins

None

**Comment by Youssef1313** [comment]
We have hit something similar before which we made work for the specific scenario we encountered. We will need to fix it properly this time.

The previous fix was https://github.com/unoplatform/uno/pull/14173 which is mostly a workaround that needs to be reverted/cleaned-up as part of fixing this issue.

FYI @nickrandolph

**Comment by agneszitte** [comment]
> We have hit something similar before which we made work for the specific scenario we encountered. We will need to fix it properly this time.
> 
> The previous fix was #14173 which is mostly a workaround that needs to be reverted/cleaned-up as part of fixing this issue.
> 
> FYI @nickrandolph

@Youssef1313 how much work do you estimate to fix it properly?
@nickrandolph until a proper fix is made, maybe we can move the current namespace in the current tutorial doc for Maui Embedding?

**Comment by Youssef1313** [comment]
I'll take a look. It's probably not a large change as I was initially expecting

**Comment by agneszitte** [comment]
> I'll take a look. It's probably not a large change as I was initially expecting

Thanks a lot for the help on this one @Youssef1313, I will be able to give it a try and let you know if I notice anything else

**Comment by agneszitte** [comment]
@Darsh0307 if you can test if this one is fixed with latest please

**Comment by Darsh0307** [comment]
This one is completely working fine because i was able to run for DevExpress.
