### ISSUE TITLE
Publishing wasm failed with dependency injection

### ISSUE THREAD

**Issue by wch1618** [unoplatform/uno#15947]
### Current behavior

If project created without dependency injection, the project will published successfully, otherwise failed with error:
CSC (0,0): Error CS2012: Unable to open 'xxx. Wasm. dll' for writing -- 'The file' xxx. Wasm. dll 'is currently in use by another process and therefore cannot be accessed by that process.' (source message : CSC(0,0): 错误 CS2012: 无法打开“xxx.Wasm.dll”进行写入 --“文件“xxx.Wasm.dll”正由另一进程使用，因此该进程无法访问此文件。”)
I am very certain that none of my other processes have opened that file.

### Works on UWP/WinUI

None

### NuGet package version(s)

Uno.Extensions.Hosting.WinUI 4.0.0

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.9.3 17.9.4

### Anything else we need to know?

vs extension of uno platform is 5.1.22.4
uno-check pass

**Comment by jeromelaban** [comment]
Thanks for the report. Can you provide [a repro sample](https://platform.uno/docs/articles/uno-howto-create-a-repro.html?tabs=windows-vs)?
