### ISSUE TITLE
[Skia] TreeView drag glyphs issue

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/uno#15955]
### Current behavior

The glyph shows a block between items on Skia heads

![6wDEvy5KRg](https://github.com/unoplatform/uno/assets/2716316/e27182f6-a029-4d73-9dab-e438c74e2656)

### Expected behavior

![vDc5hjQC9h](https://github.com/unoplatform/uno/assets/2716316/47abd4dc-fd98-4870-81e9-03d3e03d8c82)

### How to reproduce it (as minimally and precisely as possible)

[TreeViewRepro.zip](https://github.com/unoplatform/uno/files/14665585/TreeViewRepro.zip)

### Works on UWP/WinUI

Yes

### NuGet package version(s)

5.1.87

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer)

### IDE

Visual Studio 2022

**Comment by ramezgerges** [comment]
I've investigated this on WinUI and there is some bizarre behaviour. It appears that you can't get a DragEnter without also getting a DragOver. To confirm this further, I've timed it and it seems that the timing between the DragEnter and the following DragOver is a LOT shorter than between any two consecutive DragOver events (e.g. when dragging across an element), so it seems that they're fired together in sequence. It seems that `DragEnter.AcceptedOperation` is pretty much completely irrelevant when `DragOver.AcceptedOperation` is also set in its callback, as it will always be the one to take effect. This is what is causing the reported issue: if we hit DragEnter without directly following up with DragOver, we can end up with an AcceptedOperation 
```
DragOver Microsoft.UI.Xaml.Controls.TreeView False 2015470515 Move 18:01:22.941000
DragOver Microsoft.UI.Xaml.Controls.TreeView False 2015469587 Move 18:01:23.002224
DragOver Microsoft.UI.Xaml.Controls.TreeView False 2015471155 Move 18:01:24.762124
DragEnter Microsoft.UI.Xaml.Controls.TreeViewItem False 2015469235 None 18:01:24.927082  <-- notice the time delta
DragOver Microsoft.UI.Xaml.Controls.TreeViewItem True 2015470771 None 18:01:24.929193  <-- notice the time delta
DragOver Microsoft.UI.Xaml.Controls.TreeViewItem True 2015472435 None 18:01:25.357450
```
Another observation is that "dropping" (i.e. PointerReleased when over an element with AllowDrop) will also fire a DragOver before firing the DragDrop event.

Also, it seems that `TreeViewItem` sometimes (but not always) handles the `DragOver` event, but the WinUI Source doesn't set `args.Handled` anywhere in the `DragOver` callback inside `TreeViewItem`, so I'm not sure where it's coming from.

There is some other crazy behaviour on WinUI itself where the direction that you enter the TreeViewItem from can affect the values for AcceptedOperation, but we can leave that for later.

**Comment by weitzhandler** [comment]
If I remember correctly `e.Handled` is completely ignored and the event chain still carries on.

**Comment by dr1rrb** [comment]
> It appears that you can't get a DragEnter without also getting a DragOver

It's not surprising, I had to same for pointers: I make sure to always inject a "move" between "pressed" and "released".

**Comment by weitzhandler** [comment]
@nickrandolph 
I've just experienced this issue again.

While experimenting with the TreeView template I've set the TreeView's Background property to Black to see if it takes effect and noticed something funny, on the v1 the background turned completely black while on v2 there are spaces between elements. These spaces could be explaining why this issue occurs.

**Comment by weitzhandler** [comment]
Since I can't reproduce with plain example I'll re-close this issue for the time being.
