### ISSUE TITLE
[Skia] TreeView drag and drop issues

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/uno#15950]
### Current behavior

The drag and drop behavior doesn't work properly.
When pressing down button to and starting to drag, it would not always start the drag operation and would sometimes ignore it.

### Expected behavior

When clicking and dragging an item in TreeView it should always start a drag operation when enabled.

### How to reproduce it (as minimally and precisely as possible)

[Repro.zip](https://github.com/unoplatform/uno/files/14664101/Repro.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.1.87

### Affected platforms

Observed on: Skia (WPF), Skia (GTK on Linux/macOS/Windows)
Might occur on FrameBuffer as well.

### IDE

Visual Studio 2022

**Comment by nickrandolph** [comment]
cc @jeromelaban / @martin / @dr1rrb can we get this prioritised as a blocker for the treeview

**Comment by ramezgerges** [comment]
Nevermind, I am able to reproduce now. It seems to be most consistent after a successful drag&drop operation.
