### ISSUE TITLE
System.Drawing.Color isn't available for iOS

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#1596]
## Current behavior

System.Drawing.Color isn't available for iOS
![image](https://user-images.githubusercontent.com/16295702/65538664-cc63be80-ded5-11e9-9ffe-315eb3274572.png)

## Expected behavior

System.Drawing.Color should be available for iOS like it's already available for UWP/Android/Wasm.

## Environment

Package Version(s): Uno.UI 1.45.0

Affected platform(s):
- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: 15.9.8)
- [ ] 2019 (version: )
- [ ] for Mac (version: )

**Comment by jeromelaban** [comment]
`System.Drawing.Color` should not be used anywhere in the Uno API set. Aside from that, this is a Xamarin-specific issue.

**Comment by Cheesebaron** [comment]
System.Drawing.Color is available if you add OpenTK as a Framework Reference. 

```xml
 <ItemGroup Condition=" $(TargetFramework.StartsWith('xamarin.ios')) ">
    <Reference Include="OpenTK-1.0" />
</ItemGroup>
```

If Uno,UI or some other library is using System.Drawing.Color, you should probably consider adding this dependency.

**Comment by davidjohnoliver** [comment]
Underlying Xamarin issue: https://github.com/xamarin/xamarin-macios/issues/5273

I think we can close this as it's not Uno-related, it doesn't affect the Uno/WinUI API set, and there's not much we can do about it.
