### ISSUE TITLE
[Gallery][WASM]Listing issue-Multiple controls are displayed as selected in the Navigation view.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#15968]
### Current behavior

![Multiple controls display issue](https://github.com/unoplatform/uno/assets/74563602/b8d73cb4-940a-443f-bcce-b3c527255530)

### Expected behavior

Only the selected controls should display as Selected.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP.
2. Click Burger Menu on the left top right .
3. Click on multiple controls on the "component" list.
4. Observe that multiple controls display as selected in the Navigation view.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
@dr1rrb can you take a look?

**Comment by dr1rrb** [comment]
@sakshi173  on which browsers?

**Comment by sakshi173** [comment]
@dr1rrb I checked for Google Chome and MS Edge Browers and happening for both browsers.

**Comment by jeromelaban** [comment]
@sakshi173 thanks. Make sure to validate on Safari and Firefox as well.
