### ISSUE TITLE
Implement ListView.ScrollTo and EffectiveViewportChanged event args completely

### ISSUE THREAD

**Issue by pedrojesus-work** [unoplatform/uno#15971]
### What would you like to be added

Implement one or both methods:

- `ListView.ScrollIntoView` 
- `BringIntoViewDistanceY` from `EffectiveViewportChanged`'s EventArgs

### Why is this needed

On GTK I didn't find a way to know if a view is visible on the screen. Looking into the possibilities on winui world, I found that I've the `EffectiveViewportChanged` event, but the `BringIntoViewDistanceY` property isn't implemented on GTK.

Another approach would be to use the `ListView` and call `ListView.ScrollIntoView` that does exactly what I need, but isn't implemented on GTK.

### For which platform

Skia (WPF), Skia (GTK on Linux/macOS/Windows)

### Anything else we need to know?

[ScrollToAnItem.zip](https://github.com/unoplatform/uno/files/14672728/ScrollToAnItem.zip)

**Comment by ramezgerges** [comment]
Should be mostly fixed by #15971

**Comment by pedrojesus-work** [comment]
Sorry @ramezgerges what's the PR? Looks like you linked the issue id on your previous comment

**Comment by ramezgerges** [comment]
Oops, I meant #15916

**Comment by ramezgerges** [comment]
@pedrojesus-work #15916 seems to meet your needs, so feel free to close if so.

**Comment by ramezgerges** [comment]
@pedrojesus-work is this issue still needed?

**Comment by pedrojesus-work** [comment]
@ramezgerges, it's working on Skia, thanks for implementing it.
