### ISSUE TITLE
Showing X on editable combobox

### ISSUE THREAD

**Issue by randomroxks** [unoplatform/uno#15972]
### Current behavior

Can't seem to compile it on windows, but seems to work on mac. Which is weird. 
Anyways, the repro is simple. 
Add a combobox and define a style in AppResources.Xaml that is targetted to the combbox with triggers. 
On Mac, it seems to work, but the UI is little bit jumpy. On Windows, I get a runtime exception
Cannot locate resource from 'ms-appx:///Projects/AppResources.xaml'. [Line: 12 Position: 29]
Never the less I cannot get it to work. 
I got the same appResources exception when I did dotnet new unoapp.

### Expected behavior

see the x button on editable combobox. 

### How to reproduce it (as minimally and precisely as possible)

[Randomworks-main.zip](https://github.com/unoplatform/uno/files/14675813/Randomworks-main.zip)

### Workaround

None

### Works on UWP/WinUI

No

### IDE

Rider Windows

### IDE version

Latest

**Comment by jeromelaban** [comment]
Thanks for the report. The error :

```
Cannot locate resource from 'ms-appx:///Projects/AppResources.xaml'. [Line: 12 Position: 29]
```
is fixed by updating the latest version of Uno.

Note that for Uno targets, the editable mode for `ComboBox` is not yet supported: https://github.com/unoplatform/uno/issues/9063
