### ISSUE TITLE
[Gallery][WASM/iOS/Android]Datepicker-When clicking on the 'Set Date' button, the calendar does not open.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#15976]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/a434315f-28a1-49aa-973b-781ebd44aafb

### Expected behavior

The calendar should open.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "DatePicker" from the "Ui Component" list.
4. Click on the Set date button.
5. Notice that  When clicking on the 'Set Date' button, the calendar does not open.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, iOS

**Comment by jeromelaban** [comment]
@MartinZikmund could you take a look?

**Comment by MartinZikmund** [comment]
I'm unable to reproduce this on Canary, can you please try again @sakshi173 ?

![date](https://github.com/unoplatform/uno/assets/1075116/d1c3e7e3-74b7-4777-a203-ba680533fca6)

**Comment by MartinZikmund** [comment]
@Youssef1313 @jeromelaban can you please try it out in canary? It works in all my browsers 👀👀

**Comment by Youssef1313** [comment]
I'll take a look and let you know @MartinZikmund
