### ISSUE TITLE
Invalid XAML generation

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#15980]
### Current behavior

Using this sample: [TestInvalidBinding.zip](https://github.com/unoplatform/uno/files/14696901/TestInvalidBinding.zip), 

the following code does not build:

```xaml
<controls:DataGrid x:Name="dataGrid">
  <controls:DataGrid.RowStyle>
    <Style TargetType="controls:DataGridRow">
      <Setter Property="AutomationProperties.AutomationId"
              Value="{Binding Path=TestValue}" />
    </Style>
  </controls:DataGrid.RowStyle>
</controls:DataGrid>
```

With the error:
```
1>CSC : error UXAML0001: Processing failed for file
Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in Page --->
Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in StackPanel ---> 
System.Exception: The property Microsoft.UI.Xaml.Data.Binding.Value is unknown. Line number: 17, Line position: 12, Caller: BuildBindingOption,
```

### Works on UWP/WinUI

Yes

### NuGet package version(s)

5.1.80

**Comment by Youssef1313** [comment]
This binding isn't supposed to work. In WinUI, it compiles but will always evaluate to null.

**Comment by cwhitlatch** [comment]
@jeromelaban - It does not appear to do anything ( setting automation id on the row ). It does compile without issue.

@Youssef1313  - Thanks for fixing regardless! Likely resolves other issues.
