### ISSUE TITLE
[Android] DoubleAnimation cause clipping issue

### ISSUE THREAD

**Issue by XiaotianNetlift** [unoplatform/uno#1599]
## Current behavior
Since the [recent change](https://github.com/unoplatform/uno/pull/1373), `DoubleAnimation` causes certain controls like (`WebView`) to expand to full-screen, and ignoring its own's or parent's layout constraints (`Grid.Row`, `Grid.Column`, `Margin`, etc..).

## Expected behavior
`DoubleAnimation` should not cause any clipping issue.

## How to reproduce it (as minimally and precisely as possible)
#1600: checkout SamplesApp: `Clip` -> `DoubleAnimationClipping` 

## Environment
Nuget Package: Uno.UI
Package Version(s): Uno.UI >= 1.46.203-dev.2513

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
@XiaotianNetlift Are you able to test this?

**Comment by XiaotianNetlift** [comment]
The issue is fixed with #1726.
