### ISSUE TITLE
`BindableMetadata.g.cs` contains types which do not exist

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#15994]
### Current behavior

Getting:

```
BindableMetadata.g.cs(27360,96,27360,114): error CS0234: The type or namespace name 'SwipeRefreshLayout' does
not exist in the namespace 'AndroidX' (are you missing an assembly reference?)
```

Without `SwipeRefreshLayout` NuGet being included.

### Expected behavior

Should not happen.

### How to reproduce it (as minimally and precisely as possible)

- Clone https://github.com/MartinZikmund/SmsTicket/tree/uno-bug-repro-bindable-metadata
- Try to build `SmsTicket.Mobile`

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
@Youssef1313 can you take a look?

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/blob/e795d80927fe671e226b88eb62ea3799eb90460f/src/Uno.UI/Microsoft/UI/Xaml/Controls/PullToRefresh/Native/NativeRefreshControl.Android.cs#L24

`NativeRefreshControl` here has `SwipeRefreshLayout` as base type which comes from `Xamarin.AndroidX.SwipeRefreshLayout` NuGet package.

When compiling Uno, we get this package from `Xamarin.AndroidX.Browser` (1.0.0) → `Xamarin.AndroidX.Legacy.Support.Core.UI` (1.0.0) → `Xamarin.AndroidX.SwipeRefreshLayout` (1.1.0.18).

The package `Xamarin.AndroidX.Browser` is correctly included in nuspec, but the application didn't get `Xamarin.AndroidX.SwipeRefreshLayout`. The reason for that is that **newer** versions of `Xamarin.AndroidX.Browser` has a breaking change and they removed the dependency on `Xamarin.AndroidX.Legacy.Support.Core.UI`.

We should explicitly reference `Xamarin.AndroidX.SwipeRefreshLayout`.

**Comment by MartinZikmund** [comment]
@Youssef1313 what a puzzle :-D !
