### ISSUE TITLE
Gallery][All Platform]ToggleSwitch(Material)- When changing the Light/Dark theme, the toggle switch for 'Disabled' and 'Disabled Icon' is displayed as an enabled toggle.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#16007]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/5da55f96-78f0-4b39-a599-4d18c2494550

![Toggleswitch issue](https://github.com/unoplatform/uno/assets/74563602/e594a4d5-9589-4a28-abfd-4e9198249d31)

### Expected behavior

![Toggleswitch correct](https://github.com/unoplatform/uno/assets/74563602/98b0690e-a05a-40d7-9161-12ec2b521f4e)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app.
2. Click on “Toggleswitch” from the "UI Component" list.
3. Change theme from Light to Dark.
4. Notice that the toggle switch for 'Disabled' and 'Disabled Icon' is displayed as an enabled toggle.
5. 

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS

**Comment by jeromelaban** [comment]
@kazo0
