### ISSUE TITLE
[Gallery][Android/iOS]Combobox(Material & Fluent)- The previously selected list item is not displayed as highlighted.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#16009]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/a7935805-c7e4-47d3-b65d-ab7603f7955f

### Expected behavior

https://github.com/unoplatform/uno/assets/74563602/d978e6e5-0ea4-4a16-8e6f-06387bdb4f4f

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "Combobox" from the "Component" list.
4. Go to 'Material' section.
5. select any option from combo list. 
6. Again click on combo box.
7. Notice that the previously selected list item is not displayed as highlighted.

### Works on UWP/WinUI

None

### Affected platforms

Android, iOS

**Comment by jeromelaban** [comment]
@kazo0 does this look familiar?

@sakshi173 can you validate if it's a regression from previous versions?

**Comment by kazo0** [comment]
@Youssef1313 can confirm that this is indeed only happening weirdly for the middle element in the dropdown list and it is also reproducing prior to Uno 5.2.0-dev.960

I see you already have a PR for this but FYI :)
