### ISSUE TITLE
[Gallery][All Platform]PersonPicture & Divider-When changing the Light/Dark theme, the person's image inside the circle changes with an incorrect icon

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#16006]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/e7faa164-9a87-4297-9268-a77120b1cb06

![Personpicture issue](https://github.com/unoplatform/uno/assets/74563602/e064a049-0efe-4004-b866-29dc42b471f7)
![divider issue](https://github.com/unoplatform/uno/assets/74563602/3907fdd2-07ee-4921-a690-dc644104cf76)

### Expected behavior

![Personpicture Correct](https://github.com/unoplatform/uno/assets/74563602/fcf19f4f-659c-453d-aaed-5be2f66536fb)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app.
2. Click on “PersonPicture” from the "UI Component" list.
3. Change theme from Light to Dark.
4. Notice that the person picture Icon inside the circle changed with some incorrect Icon.
5. Again change theme from Dark to light.
6. Notice that the Incorrect Icon is present.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS

**Comment by jeromelaban** [comment]
@Youssef1313 this looks like a regression, could you take a quick look?
