### ISSUE TITLE
Uno.UI can't be compiled under VS 2019.3

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1601]
## Current behavior

Compiling Uno.UI under VS 2019.3 crashes with a number of errors:

> 1>C:\Users\Martin\.nuget\packages\msbuild.sdk.extras\1.6.68\Build\LanguageTargets\CheckMissing.targets(36,5): error : The specified language targets for MonoAndroid90 is missing. Ensure correct tooling is installed for 'MonoAndroid'. Missing: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets'
> 1>Done building project "Uno.UI.BindingHelper.Android.csproj" -- FAILED.
> 1>C:\Users\Martin\.nuget\packages\msbuild.sdk.extras\1.6.68\Build\LanguageTargets\CheckMissing.targets(36,5): error : The specified language targets for MonoAndroid80 is missing. Ensure correct tooling is installed for 'MonoAndroid'. Missing: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets'
> 1>Done building project "Uno.UI.BindingHelper.Android.csproj" -- FAILED.
> 1>C:\Users\Martin\.nuget\packages\msbuild.sdk.extras\1.6.68\Build\LanguageTargets\CheckMissing.targets(36,5): error : The specified language targets for xamarinios10 is missing. Ensure correct tooling is installed for 'xamarinios'. Missing: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.CSharp.targets'
> 1>Done building project "Uno.UI.BindingHelper.Android.csproj" -- FAILED.
> 1>C:\Users\Martin\.nuget\packages\msbuild.sdk.extras\1.6.68\Build\LanguageTargets\CheckMissing.targets(36,5): error : The specified language targets for xamarinmac20 is missing. Ensure correct tooling is installed for 'xamarinmac'. Missing: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Mac\Xamarin.Mac.CSharp.targets'
> 1>Done building project "Uno.UI.BindingHelper.Android.csproj" -- FAILED.

## Expected behavior

Should not crash

## How to reproduce it (as minimally and precisely as possible)

Try to compile Uno.UI under VS 2019.3

## Environment

Nuget Package: -

Package Version(s): -

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] Windows
- [x] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 2019.3)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?

The problem is caused by old version of MSBuild.Sdk.Extras used: https://github.com/onovotny/MSBuildSdkExtras/issues/178

**Comment by MartinZikmund** [comment]
Same problem occurs when trying to build a Uno-based app with Uno class library, which also uses older version of MSBuild.Sdk.Extras. The project template should be updated as well

**Comment by ghuntley** [comment]
Related to https://github.com/unoplatform/uno/pull/1572

**Comment by MartinZikmund** [comment]
Thanks, did not notice this one

**Comment by ghuntley** [comment]
nps.

**Comment by jeromelaban** [comment]
Fixed by #1572
