### ISSUE TITLE
Converter receiving unexpected `null` value

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#16016]
### Current behavior

Converter is receiving `null` value when it should not be possible.

### Expected behavior

No `null` value

### How to reproduce it (as minimally and precisely as possible)

[uno-bug-repro-converter-null-main.zip](https://github.com/unoplatform/uno/files/14742677/uno-bug-repro-converter-null-main.zip)

### Workaround

Gracefully handle `null` values in converters.

### Works on UWP/WinUI

Yes

**Comment by ramezgerges** [comment]
This seems to be a problem not with ComboBox but something a lot deeper. I've followed the traces and managed to reduce it to this.
```xaml
	<Page.Resources>
		<local:BoolToVisibilityConverter x:Key="BoolToVisibilityConverter" />
	</Page.Resources>
	<StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
		<Button Click="Button_Click">Set</Button>
		<Button Click="Button_Click_1">Reset</Button>
		<ContentPresenter x:Name="cp">
		  <ContentPresenter.ContentTemplate>
		    <DataTemplate x:DataType="local:TestItem">
		      <TextBlock Text="Test" Visibility="{x:Bind Test, Converter={StaticResource BoolToVisibilityConverter}}" />
		    </DataTemplate>
		  </ContentPresenter.ContentTemplate>
		</ContentPresenter>
	</StackPanel>
```

```csharp
	private void Button_Click(object sender, RoutedEventArgs e)
	{
		cp.Content = new TestItem();
	}

	private void Button_Click_1(object sender, RoutedEventArgs e)
	{
		cp.Content = null;
	}
```



And then even further to:
```xaml
  <Page.Resources>
    <local:BoolToVisibilityConverter x:Key="BoolToVisibilityConverter" />
  </Page.Resources>
  <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
    <Button Click="Button_Click">Set</Button>
    <Button Click="Button_Click_1">Reset</Button>
    <TextBlock x:Name="tb"  Text="Test" Visibility="{Binding Test, Converter={StaticResource BoolToVisibilityConverter}}" />
  </StackPanel>
```

```csharp
    private void Button_Click(object sender, RoutedEventArgs e)
    {
        tb.DataContext = new TestItem();
    }

    private void Button_Click_1(object sender, RoutedEventArgs e)
    {
        tb.DataContext = null;
    }
```

Which clears any doubts about lifecycle-related problems. If you very explicitly set the DataContext of an element to null, WinUI will still not call the converter with null.

**Comment by ramezgerges** [comment]
More updates: it seems like the converter can be called with null, but only if the final property of the path is null. I.e. if you have a bindinging to `{Binding Outer.Inner, Converter=...}`,

1. If the DataContext is null, the converter won't be called.
2. if DataContext.Outer is null, the converter won't be called.
3. if DataContext.Outer.Inner is null, the converter WILL be called.

**Comment by ramezgerges** [comment]
Additionally, when we set DC to null, in Uno the ContentPresenter in the xaml snipper in the previous comment will have no children, while in WinUI, the TextBlock will continue to exist as a child of the ContentPresenter (again, visually blank, so it's like it's not there). I will have to recheck this later.
