### ISSUE TITLE
SamplesApp.Wasm does not compile on VS 2019.3

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1602]
## Current behavior

In addition to #1601 , I have found out SamplesApp.Wasm does have problem compiling due to the following line in `ImageBrush_SameWithDelay.xaml.cs`:

	Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, () => _ctx.ImgSource = "https://lh5.ggpht.com/lxBMauupBiLIpgOgu5apeiX_YStXeHRLK1oneS4NfwwNt7fGDKMP0KpQIMwfjfL9GdHRVEavmg7gOrj5RYC4qwrjh3Y0jCWFDj83jzg");

Apparently it has to be awaited, though I am surprised it is reported as a hard error, not just warning.

## Expected behavior

App compiles properly.

## How to reproduce it (as minimally and precisely as possible)

Try to compile SamplesApp.Wasm on VS 2019.3

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 2019.3)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Related to https://github.com/unoplatform/uno/pull/1572

**Comment by jeromelaban** [comment]
Fixed by #1609
