### ISSUE TITLE
ListView selected items change when removing or inserting item

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#16024]
## Current behavior
When removing or inserting an item in a ListView that is in multiple selection mode, the selected items change unexpectedly.

## Expected behavior
The ListView's selected items should stay the same after removing or adding an item.

## Environment
Tested on Uno.WinUI 5.1.87

## Sample
[ListViewGrouping.zip](https://github.com/unoplatform/uno/files/14748033/ListViewGrouping.zip)

**Comment by arianeleonard** [comment]
## Repro Steps
1. Select multiple items from different groups.
2. Collapse and expand groups by selecting their header.
3. See how selected items have changed

**Comment by Youssef1313** [comment]
I tried to reproduce, but in Uno, selection remains the same. However, on WinUI, it doesn't remain.

https://github.com/unoplatform/uno/assets/31348972/876c26c7-f879-4238-95b2-319f1a64cc0c

@arianeleonard Is this a WinUI-only issue?

**Comment by arianeleonard** [comment]
@Youssef1313 I can reproduce on WIndows, iOS and Android yes! Sorry I added that info on my original issue, but not on this one.

**Comment by Youssef1313** [comment]
Well, on Windows we can't change that behavior (and I guess iOS/Android behavior is correct if it matches WinUI). Will see if I can find an easy workaround.

**Comment by Youssef1313** [comment]
A possible workaround for Windows is to change `ListItem` like this (NOTE: I couldn't repro this on Android):

```csharp
    public class ListItem
    {
        private bool _isSelected;
        private static bool _isSelectedSuppressed;

        public bool IsSelected
        {
            get => _isSelected;
            set
            {
                if (!_isSelectedSuppressed)
                {
                    _isSelected = value;
                }
            }
        }
        public string Value { get; set; }

        internal static void SuppressIsSelectedChanges()
            => _isSelectedSuppressed = true;

        internal static void ResumeIsSelectedChanges()
            => _isSelectedSuppressed = false;
    }
```

Then, change `ExpandOrCollapseGroup` to be:

```csharp
        public void ExpandOrCollapseGroup(ListGroupItem group)
        {
            ListItem.SuppressIsSelectedChanges();
            try
            {
                using (_collectionView?.DeferRefresh())
                {
                    if (group.IsExpanded)
                    {
                        var index = _groupList.IndexOf(group) + 1;
                        ExpandGroup(group, ref index);
                    }
                    else
                    {
                        CollapseGroup(group);
                    }
                }
            }
            finally
            {
                ListItem.ResumeIsSelectedChanges();
            }
        }
```

So, basically suppress any changes to `IsSelected` while collapse/expand. @arianeleonard Is that viable for you?

**Comment by jeromelaban** [comment]
@arianeleonard note that we aim at reproducing the behavior of WinUI, which means that in general testing the behavior on windows first can tell if Uno is behaving incorrectly. If not, then finding a way around like Youssef did is generally the best way to go.
