### ISSUE TITLE
[Gallery][Skia.GTK]PasswordBox- RevealButton functionality is not working.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#16026]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/2e07c609-35a9-4db0-9d1c-bf1f28a18dc5

### Expected behavior

https://github.com/unoplatform/uno/assets/74563602/3c664bae-56e6-4998-abb5-003dda0dda51

### How to reproduce it (as minimally and precisely as possible)

1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Click/tap Burger Menu on the left top right.
3. click/tap "PasswordBox" from the "Component" list.
4. Type Text for the password box.
5. Click on the RevealButton displaying on the right side on the text box.
6. Observe that when clicking revealbutton nothing is happening.

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
@ramezgerges could you take a look?

**Comment by sakshi173** [comment]
Verified this issue is fixed.
