### ISSUE TITLE
[Gallery][Skia.GTK]ShadowContainer- When adding or deleting a new shadow option, the shadow for the content box stops displaying.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#16049]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/d88430e1-019a-4269-94e6-12f8f972c163

![shadow issue](https://github.com/unoplatform/uno/assets/74563602/062a5bd6-206c-4ca2-9449-4bbe3ececec4)

### Expected behavior

Shadow should display all the time.

https://github.com/unoplatform/uno/assets/74563602/c9737f1c-4d99-4c28-8ece-06b764972e4a

### How to reproduce it (as minimally and precisely as possible)

1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Click/tap Burger Menu on the left top right.
3. click/tap "ShadowContainer" from the "Toolkit" list.
4. Click on '+Shadow' or '-Shadow' option.
5. Notice that the shadow for the content box stop displaying.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment]
Let's validate after https://github.com/unoplatform/uno/pull/16029

**Comment by Youssef1313** [comment]
@sakshi173 Can you please verify if this is still happening?

**Comment by sakshi173** [comment]
@Youssef1313  This issue is still happening, please look into it.
![shadow issue](https://github.com/unoplatform/uno/assets/74563602/c2b1e97b-3bf1-4f3a-b3d7-33f7a9afdbe6)
