### ISSUE TITLE
[Gallery][Skia.GTK] (ShadowContainer) Button & FAB(Dark Theme)-After the first click, the buttons are not displayed as elevated or filled.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#16050]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/7181ad81-16dc-4ce0-84e9-d59a32fdbf90

![button shadow issue](https://github.com/unoplatform/uno/assets/74563602/0380c2ca-8d88-4ad6-8de5-b236951ea21b)
![FAB issue](https://github.com/unoplatform/uno/assets/74563602/74d67ccd-71c8-447f-a647-ce5baac191b6)

### Expected behavior

https://github.com/unoplatform/uno/assets/74563602/9d5174fd-0eae-48ed-b161-2b0532145e25

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app for 4X or 5X version for Android.
2. Click on “ShadowContainer” from the "Toolkit" list.
3. Go to Neumorphic section.
4. Choose 'Button' option from the combo list.
5. Click once on any 'Elevated' or 'Filled' section button.
6. Notice that after first click buttons are not displayed as elevated or filled.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment]
Let's validate after https://github.com/unoplatform/uno/pull/16029

**Comment by Youssef1313** [comment]
@sakshi173 Can you please verify if this is still happening?

**Comment by sakshi173** [comment]
Verified this issue is fixed, closing it.
