### ISSUE TITLE
[Gallery][Skia.GTK] (ShadowContainer) Chip - After the first click, the Chip functionality is not working properly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#16051]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/864a004b-d56e-4e26-9bcc-8fbeb7786469

### Expected behavior

https://github.com/unoplatform/uno/assets/74563602/6d35d534-528c-46e9-89bd-3d5646db556c

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app for 4X or 5X version for Android.
2. Click on “ShadowContainer” from the "Toolkit" list.
3. Go to Neumorphic section.
4. Choose 'Chip' option from the combo list.
5. Click once on any 'Enabled' chip option
6. Notice that  After the first click, Chip functionality is not working properly.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment]
Let's validate after https://github.com/unoplatform/uno/pull/16029

**Comment by Youssef1313** [comment]
@sakshi173 Can you please verify if this is still happening?

**Comment by sakshi173** [comment]
@Youssef1313  This issue is still happening, please look into it.
![Chip issue](https://github.com/unoplatform/uno/assets/74563602/2cb3cda3-7c88-4020-a75a-a1a74287e87a)

**Comment by Youssef1313** [comment]
@sakshi173 Can you re-validate this one?

**Comment by sakshi173** [comment]
Verified this issue is fixed, closing it.
