### ISSUE TITLE
Implement `InputInjectors` in WASM

### ISSUE THREAD

**Issue by ADD-Eugenio-Lopez** [unoplatform/uno#16055]
### What would you like to be added

Implement InputInjectors in WASM.

### Why is this needed

Because RuntimeTests projects need these classes to execute tests in WASM.

### For which platform

WebAssembly

**Comment by ADD-David-Antolin** [comment]
@dr1rrb @MartinZikmund Can you backport this to 5.3?

**Comment by MartinZikmund** [comment]
I am afraid this PR was very large, so backporting may result in many hard to resolve conflicts, what would you say, @dr1rrb? In any case, 5.4 release should happen quite soon

**Comment by dr1rrb** [comment]
Indeed, this one cannot be backported to 5.3 it's major refactor that needs deep QA (undergoing) and is one of the major improvements for 5.4 which should be released sooner than later.

**Comment by ADD-David-Antolin** [comment]
We would need a better estimation of when is going 5.4 to be stable than 'sooner than later': 1 month, two months, by November when MS releases .NET 9...

**Comment by dr1rrb** [comment]
Less than a month

**Comment by ADD-David-Antolin** [comment]
Thank you, we will be looking forward for it.
