### ISSUE TITLE
[Gallery][Skia.GTK] (ShadowContainer)Combobox, when change theme, outline for combobox stop displaying.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#16052]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/8f883247-60f5-4ffd-a690-5017f0d95ab7

![combobox issue](https://github.com/unoplatform/uno/assets/74563602/c99577a3-e865-40a9-ae9e-5dd90e239802)

### Expected behavior

https://github.com/unoplatform/uno/assets/74563602/1f4306f4-daaf-4d10-a550-f6a39847b9c2

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app for 4X or 5X version for Android.
2. Click on “ShadowContainer” from the "Toolkit" list.
3. Go to Neumorphic section.
4. Choose 'Combobox' option from the combo list.
5. change theme from light to dark.
6. Notice that when change theme, outline for Combobox stop displaying.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment]
Likely will get fixed with https://github.com/unoplatform/uno/pull/16029

**Comment by Youssef1313** [comment]
@sakshi173 Can you please verify if this is still happening?

**Comment by sakshi173** [comment]
Still this is happening
![Combobox issue](https://github.com/unoplatform/uno/assets/74563602/129877f8-a519-460e-b915-f5ce9d5298b0)

**Comment by Youssef1313** [comment]
@sakshi173 Can you re-validate this one?

**Comment by sakshi173** [comment]
@Youssef1313 , yes I a checking all, one by one

**Comment by sakshi173** [comment]
Verified this issue is fixed, closing it.

**Comment by Youssef1313** [comment]
Thank you @sakshi173!
