### ISSUE TITLE
[Skia] UIElementCollection.Move doesn't work

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/uno#16068]
### Current behavior

UIElementCollection.Move doesn't do anything.

When running the following code, `success` is false in Skia whereas it's true on Windows:

```c#
var x = new StackPanel();
x.Children.Add(new TextBlock());
x.Children.Add(new Button());
x.Children.Add(new TextBlock());
x.Children.Add(new TextBlock());
x.Children.Add(new TextBlock());

x.Children.Move(1, 3);

var success = x.Children[3] is Button;
```

![image](https://github.com/unoplatform/uno/assets/2716316/9ac7f6ce-0ed6-4e35-8a7c-0c326afc080c)

### Expected behavior

![image](https://github.com/unoplatform/uno/assets/2716316/4cc4f14e-3d90-4c12-aa28-5474871dc500)

### Workaround

Remove element and it back anew

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.1.104

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by Youssef1313** [comment]
As a workaround, you  may try to Remove then Insert the element.

**Comment by weitzhandler** [comment]
That's what we're doing.
There's one extra step to do when moving an element forward, need to -1 the
insert position to compensate for the gap the removal created.

Anyway, would be nice to have a fix.
