### ISSUE TITLE
Root element of a ControlTemplate cannot be reterived using GetTemplateChild

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#1607]
## Current behavior
When giving a name to the root element of a template, we cannot resolve it using the `GetTemplateChild` as it not registered in the `NameScope` 

## Expected behavior
It works!

## How to reproduce it (as minimally and precisely as possible)
 ```xaml
<ControlTemplate TargetType="local:MyControl">
    <Grid x:Name="PART_RootPanel">
        <Grid x:Name="PART_SubPanel" />
    </Grid>
</ControlTemplate>
```
```csharp
_rootPanel = this.GetTemplateChild("PART_RootPanel") as Panel;
_subPanel = this.GetTemplateChild("PART_SubPanel") as Panel;
```

`_rootPanel` will be `null` while `_subPanel` is resolved properly.

## Environment
Nuget Package: Uno.UI
Package Version(s): 2.0
Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio: _irrelevant_
Relevant plugins: _none_

**Comment by jeromelaban** [comment]
Issue is not present anymore in Uno 4.0.9
