### ISSUE TITLE
Cannot use WCT SettingsCard in Uno 5: MissingMethodException

### ISSUE THREAD

**Issue by lukasf** [unoplatform/uno#16073]
### Current behavior

When adding WCT SettingsControls and placing a SettingsCard in an empty UNO template page, I get an exception on Android (probably on all Non-WinUI heads):

System.MissingMethodException: Method not found: void Microsoft.UI.Xaml.FrameworkElement.remove_IsEnabledChanged(Microsoft.UI.Xaml.DependencyPropertyChangedEventHandler)

I guess this has to do with moving of the IsEnabled property from FrameworkElement to Control in Uno 5.0. But I am using latest Uno 5.1.104 and latest WCT SettingsControl. So I wonder why it still tries to use IsEnabled from FrameworkElement.

The SettingsCard and related controls are critical parts. I cannot move to Uno 5 without these.

### Expected behavior

SettingsCard should work without issues.

### How to reproduce it (as minimally and precisely as possible)

Add "CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.0.240109" NuGet package. Add SettingsCard to the MainPage of Uno Template App. Run the Mobile head on Android. See it crash.

[UnoAppSettingsCard_2024-03-31 20-11-54Z.zip](https://github.com/unoplatform/uno/files/14817623/UnoAppSettingsCard_2024-03-31.20-11-54Z.zip)

### Works on UWP/WinUI

Yes

### NuGet package version(s)

"CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.0.240109" 
"Uno.WinUI" Version="5.1.104"

### Affected platforms

Android

### IDE

Visual Studio 2022

### Anything else we need to know?

The same error occurs when using the older SettingsCard from the WCT "Labs".

**Comment by Youssef1313** [comment]
@lukasf Can you try 8.1.240328-rc?

Version `8.0.240109` was compiled against Uno 4

**Comment by lukasf** [comment]
@Youssef1313: That does not help. I upgraded to 8.1.240328-rc, but the same exception still occurs.

**Comment by jeromelaban** [comment]
@lukasf this is still being worked on in the RC bits, and is not related to Uno explicitly. You can follow the updates here: https://github.com/CommunityToolkit/Windows/discussions/383

**Comment by lukasf** [comment]
I'd also say that this is clearly related to Uno, since MUX FrameworkElement does not have IsEnabled property and never had. Only Uno 4 had it on FrameworkElement and it was removed and moved to Control (which is the correct place) in Uno 5.

@jeromelaban It would be great if you can help the WCT team get this right. SettingsCard is crucial in building a convincing settings experience.

**Comment by michael-hawker** [comment]
We do subscribe to `IsEnabledChanged` for this component here:

https://github.com/CommunityToolkit/Windows/blob/426b887898c5c8ec7ef5ed29e1b7adec7489e33b/components/SettingsControls/src/SettingsCard/SettingsCard.cs#L70-L79

But that's available on `Control`; so maybe it seems within Uno one of the places it was moved was missed with the migration that happened for alignment in Uno 5?

**Comment by jeromelaban** [comment]
@lukasf I've updated the sample updated you posted, and it's working fine on Android. Note that you may be having issues with the change in the base target for WinAppSDK from 8.1-rc, where you need to change:

```xml
<PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.5.240311000" />
```

and use `$(DotNetVersion)-windows10.0.22621.0` through out the solution instead of `windows10.0.19041.0`.

The most likely explanation is a partial build which continued to use the 8.0 version of the community toolkit, but failed because of the wasdk dependency, and still managed to get deployed.

Here's the updated sample with versions aligned: [20240402-UnoAppSettingsCard.zip](https://github.com/unoplatform/uno/files/14843731/20240402-UnoAppSettingsCard.zip)

**Comment by lukasf** [comment]
Thank you @jeromelaban, this worked indeed and now SettingsCard runs fine with Uno 5.1!
