### ISSUE TITLE
Document false positive App Store Connect issues

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1608]
## Current behavior

When publishing a Release version of my app to Apple App Store.

> ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a **NSPhotoLibraryUsageDescription** key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy). 

> Though you are not required to fix the following issues, we wanted to make you aware of them:
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use **UIWebView** APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information. 

The unusual thing is that my code does not use any photo-related Uno APIs nor any `WebView` control anywhere.

Last submission showed me only the second problem (90809) but trying today gave me 90683 as well, which blocks submission unless I provide a "fake" purpose in Info.plist. It is unusual because I have `Linker Behavior` set to `Link Framework SDKs Only` which should include the `LinkerSafe` libraries (Uno) to link as well. I tried `Link All`, but that breaks a lot of things, so I would like to avoid that.

## Expected behavior

No issues reported.

## How to reproduce it (as minimally and precisely as possible)

Can provide the source code of my app, but seems to happen randomly, as it does not use any of the mentioned APIs.

## Environment

Nuget Package: Uno.UI

Package Version(s):  v1.46.231-dev.2736

Affected platform(s):
- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 2019.3)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
The workaround is to provide purpose statements for each of the permissions, I have so far found several references of a similar problem:

- https://github.com/jamesmontemagno/PermissionsPlugin/issues/136
- https://github.com/jamesmontemagno/PermissionsPlugin/issues/112
- https://montemagno.com/optimizing-xamarin-apps-libraries-with-the-linker/

**Comment by davidjohnoliver** [comment]
We're aware of the `UIWebView` issue, it'll be fixed when this PR is merged: https://github.com/unoplatform/uno/pull/1591

I'm not sure what's triggering the `NSPhotoLibraryUsageDescription` message, I do see the same line in our apps' `Info.plist`s however.

**Comment by ghuntley** [comment]
UIWebView PR has been merged — https://github.com/unoplatform/uno/pull/1591

**Comment by MartinZikmund** [comment]
By removal of the `UIWebView` this is essentially fixed, but the `NSPhotoLibraryUsageDescription` is probably worth documenting.
