### ISSUE TITLE
[iOS] FileOpenPicker using VideosLibrary doesn't allow multiple video selection

### ISSUE THREAD

**Issue by arianeleonard** [unoplatform/uno#16096]
### Current behavior

When using FileOpenPicker's PickMultipleFilesAsync with VideosLibrary as the SuggestedStartLocation, the photo gallery opens, but none of the videos are visible, so their selection is not possible. 

### Expected behavior

When setting VideosLibrary as the SuggestedStartLocation, videos should be available for selection in the photo gallery, if not only the videos should be available for selection.

### How to reproduce it (as minimally and precisely as possible)

1. Launch this sample on iOS : 
[MultiplePhotoSelection (2).zip](https://github.com/unoplatform/uno/files/14838660/MultiplePhotoSelection.2.zip)
2. Select the "open file" button
3. See that only photos are visible in the gallery, not videos.

### Workaround

Using PickSingleFileAsync instead of PickMultipleFilesAsync

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUi : 5.2.0-dev.2160

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.9.2

**Comment by Youssef1313** [comment]
What iOS version is being run on?

It's known that this doesn't work on versions before iOS 14:

https://github.com/unoplatform/uno/blob/86d97157931f62a854af5af61d5685ed72461423/src/Uno.UWP/Storage/Pickers/FileOpenPicker.iOS.cs#L68-L79

**Comment by arianeleonard** [comment]
I have encountered this issue on iOS 17.

**Comment by Youssef1313** [comment]
FYI @ajpinedam

**Comment by ajpinedam** [comment]
Thanks @Youssef1313 , I will look into this
