### ISSUE TITLE
Add default support for WasmHttpHandler using mono-wasm selector

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#161]
Add support for default http client support through https://github.com/mono/mono/pull/10152

**Comment by jeromelaban** [comment]
Here's a sample code to use the mono backdoor for setting the default HttpMessageHandler:

```csharp
var httpMessageHandler = Type
  .GetType("System.Net.Http.HttpClient, System.Net.Http")
  .GetField(
    "GetHttpMessageHandler",
    BindingFlags.Static | BindingFlags.NonPublic
  );

httpMessageHandler.SetValue(
  null,
  (Func<HttpMessageHandler>)(() => new Uno.UI.Wasm.WasmHttpHandler())
);
```

**Comment by MelbourneDeveloper** [comment]
@jeromelaban , I can't get HttpClient to work. In .NET Core, this code works:

```cs
            var httpClient = new HttpClient();
            var response = await httpClient.GetAsync("http://services.groupkt.com/country/get/all");
            var data = await response.Content.ReadAsStringAsync();
```
I tried this in Uno:

```cs
    static void Main(string[] args)
    {
            App.HttpClient = new HttpClient(new WasmHttpHandler());
            Windows.UI.Xaml.Application.Start(_ => _app = new App());
    }

        private async void MainPage_Loaded(object sender, RoutedEventArgs e)
        {
            try
            {
                var response = await App.HttpClient.GetAsync("http://services.groupkt.com/country/get/all");
                button.Text = (await response.Content.ReadAsStringAsync());
            }
            catch(Exception ex)
            {
                button.Text = ex.ToString();
            }
        }
```

The exception I get is:

> System.Exception: NetworkError when attempting to fetch resource.  at Uno.Threading.FastTaskCompletionSource`1[T].GetResult () <0x2699888 + 0x0005e> in <4f734568ee5d4fc882e3c02b78c0cf28>:0   at Uno.Threading.FastTaskCompletionSource`1[T].CreateAsyncTask () <0x25cd998 + 0x000a4> in <4f734568ee5d4fc882e3c02b78c0cf28>:0   at Uno.UI.Wasm.WasmHttpHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x2588430 + 0x0057e> in <98b54d8c3c2044068638992450330dc8>:0   at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) <0x25737a8 + 0x00182> in <73181a0c3a9143aba3405a65287fbca2>:0   at CameraCaptureUISample.MainPage.MainPage_Loaded (System.Object sender, Windows.UI.Xaml.RoutedEventArgs e) <0x25626e8 + 0x000f0> in <b802632c0f6a4261b2275c4e3c9d94db>:0

**Comment by D-R-R** [comment]
In addition to getting the above method with making `Uno.UI.Wasm.WasmHttpHandler` the default via reflection working,  I've also had success with the `WasmHttpMessageHandler` that ships with Mono:
https://github.com/mono/mono/blob/master/sdks/wasm/framework/src/WebAssembly.Net.Http/WasmHttpMessageHandler.cs

There is code to configure it automatically (so no need for private reflection), although that didn't work for me out-of-the-box:
https://github.com/mono/mono/blob/master/mcs/class/System.Net.Http/System.Net.Http/HttpClient.wasm.cs

It turned out that it was being linked away and I just needed to add this to `LinkerConfig.xml` to preserve it:
```
	<assembly fullname="WebAssembly.Net.Http">
		<type fullname="*" />
	</assembly>
```
