### ISSUE TITLE
[Docs] Code snippet blocks not displaying properly when used in tabs

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno#16100]
### On which page?

https://platform.uno/docs/articles/get-started-vscode.html?tabs=windows%2Cubuntu1804#check-your-environment

### What's wrong?

![image](https://github.com/unoplatform/uno/assets/16295702/a2519a4e-af0a-4c75-867c-5a9a89b537bf)

### Any feedback?

Maybe related to DocFX or website styling adjustments needed, not sure.
Will need to be investigated

**Comment by agneszitte** [comment]
@jeromelaban, @Youssef1313 
I imagine it is maybe the same root cause as https://github.com/unoplatform/uno/issues/14358?

**Comment by Youssef1313** [comment]
@agneszitte I don't know if it's exactly the same, but both appear to be styling bugs in our site that the web team needs to take a look at.
