### ISSUE TITLE
[Wasm] Secondary commands do not appear in a popup in XAML CommandBar style

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#1610]
##  Current behavior
Adding secondary commands in a CommandBar does not display a flyout.

## Expected behavior
Secondary commands are displayed properly.

## How to reproduce it (as minimally and precisely as possible)
Create a CommandBar with secondary commands. See https://github.com/unoplatform/uno/pull/1609 for a basic sample.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by francoistanguay** [comment]
Fixed by new NavigationBar
