### ISSUE TITLE
Increase the target and minimum versions of Windows in the Uno solution templates

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1614]
## Current behavior

> Seems like the default Uno template sets both to [1709 (16299)](https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj#L27).
> 
> We should probably consider increasing these defaults to 1809 (17763), the API version that Uno is currently [referenced against](https://github.com/unoplatform/uno/blob/master/src/Uno.UWPSyncGenerator.Reference/Uno.UWPSyncGenerator.Reference.csproj#L19).
> 
> _Originally posted by @davidjohnoliver in https://github.com/unoplatform/uno/issues/1336#issuecomment-518028800_

## Environment

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?

Opening as a easy "help wanted" issue for hacktoberfest.

Adjust https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj#L27 to match the version used by https://github.com/unoplatform/uno/blob/master/src/Uno.UWPSyncGenerator.Reference/Uno.UWPSyncGenerator.Reference.csproj#L19. At the time when this issue was raised that is v1809 (17763).

**Comment by zzyzy** [comment]
Can I do this?

**Comment by pkar70** [comment]
I think minimum Win version should be 15063 - as this version is on (not only my) phone :)
