### ISSUE TITLE
Variables' values are not displayed when Chrome Debugging is used

### ISSUE THREAD

**Issue by godrose** [unoplatform/uno#1619]
## How to reproduce it (as minimally and precisely as possible)

1. Use BugTracker Sample
2. Start Chrome Debugging
3. Add a breakpoint inside any setter (`Type` for instance)
4. Modify issue type 

## Current behavior

The value of new issue type which is represented by `value` variable can't be displayed

## Expected behavior

The value of new issue type which is represented by `value` variable should be displayed

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.3 )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This is a work in progress by the mono team, this may get adressed by an update of the [bootstrapper](https://github.com/unoplatform/Uno.Wasm.Bootstrap) but we're still working on it.

**Comment by ghuntley** [comment]
:wave: have added a brand new GitHub issue category to track this category - `area/wasm-devtools`

**Comment by jeromelaban** [comment]
This issue is not under the control of the Uno team, and lots of work has been done in this area since then.
