### ISSUE TITLE
[Gallery][Skia.GTK](Canary)- Uno Gallery app is not displaying anything

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#16190]
### Current behavior

![gallery skia issue](https://github.com/unoplatform/uno/assets/74563602/b0da052a-b929-4585-b570-48904320cf2e)

### Expected behavior

The gallery app should display properly.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno gallery app for Skia platform.
2. Notice that the overview page is blank and not able to click on burger menu.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by agneszitte** [comment]
fyi @MartinZikmund, @Youssef1313

**Comment by Youssef1313** [comment]
Is it Gtk-specific? i.e, WPF works correctly?

In that case, it **may** be a regression from https://github.com/unoplatform/uno/pull/15811 as that's the only recent change I know of that's Gtk-specific.

**Comment by sakshi173** [comment]
Verified this issue is fixed
