### ISSUE TITLE
[Android|UnoPreview] ContentDialog crash with System.InvalidOperationException: XamlRoot was not set

### ISSUE THREAD

**Issue by jp-weber** [unoplatform/uno#16210]
### Current behavior

With the newest preview version of Uno, the app crashes consistently if a ContentDialog is opened with ```ShowAsync()```

```
System.InvalidOperationException: 'Trying to set position of the dialog before it is associated with a visual tree. This can happen if the dialog's XamlRoot was not set.'
```
https://github.com/unoplatform/uno/blob/0adcbe4d680bfaad4e8892056efa5c0bb40e8813/src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.Visuals.cs#L210

### Expected behavior

No crash.

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.3.0-dev.168

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.9.6

### Anything else we need to know?

The public version 5.1.104 works well.

**Comment by Youssef1313** [comment]
The current behavior is expected. You need to set the XamlRoot before calling `ShowAsync`

**Comment by jp-weber** [comment]
@Youssef1313 
Ah thank you😀 I have not read or noticed the changed initialisation.
