### ISSUE TITLE
Build error when Run the WASM Project in Visual Studio 2019 Preview 

### ISSUE THREAD

**Issue by TonyHenrique** [unoplatform/uno#1622]
## Current behavior

On the UNO WASM Project, when I hit the Run button, Visual Studio starts building the solution, then this error appears:

```
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/mono.js'. Physical path: 'C:\temp\UNOApp6\UNOApp6\UNOApp6.Wasm\bin\Debug\netstandard2.0\dist\mono.js'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 32.9954ms 200 application/javascript
Process is terminating due to StackOverflowException.

...

Registering service worker now
Service Worker Registered
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Threading.Timer.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Threading.Overlapped.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Failed to load resource: the server responded with a status of 502 (Bad Gateway) [http://localhost:61886/managed-84fed6ab494fcc2546401917306e94266e18f858/Microsoft.Extensions.Logging.Filter.clr]
Failed to load resource: the server responded with a status of 502 (Bad Gateway) [http://localhost:61886/managed-84fed6ab494fcc2546401917306e94266e18f858/Microsoft.Extensions.Logging.Console.clr]
Failed to load resource: the server responded with a status of 502 (Bad Gateway) [http://localhost:61886/mono.wasm]
Failed to load resource: the server responded with a status of 502 (Bad Gateway) [http://localhost:61886/managed-84fed6ab494fcc2546401917306e94266e18f858/Microsoft.Extensions.Logging.Abstractions.clr]
Failed to load resource: the server responded with a status of 502 (Bad Gateway) [http://localhost:61886/managed-84fed6ab494fcc2546401917306e94266e18f858/Microsoft.Extensions.Logging.clr]
The program '[1940] dotnet.exe' has exited with code 0 (0x0).
The program '' has exited with code -1 (0xffffffff).
```

## Expected behavior

Should Build sucessfully and open a Web Browser window with my project

## How to reproduce it (as minimally and precisely as possible)

[UNOApp6.zip](https://github.com/unoplatform/uno/files/3663091/UNOApp6.zip)

## Environment

Nuget Package:

Package Version(s):
Uno.Core 1.29.0-dev.93
Uno.UI 2.0.236-dev.2800
Uno.Wasm.Bootstrap 1.0.0-dev.302

Affected platform(s):
- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [X] 2019 (version: 16.4.0 Preview 1.0)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Seems like it was related to the VS debugger, can you confirm ?

**Comment by TonyHenrique** [comment]
F5 (Debug, Start Debugging):
![image](https://user-images.githubusercontent.com/6307623/65878402-660eee00-e364-11e9-9b95-4062e50acb72.png)

Control+F5 (Debug, Start WithoutDebugging):
![image](https://user-images.githubusercontent.com/6307623/65878545-b5551e80-e364-11e9-877d-372bf11ef97c.png)

![image](https://user-images.githubusercontent.com/6307623/65878511-a0788b00-e364-11e9-86b0-b515dcc56eb8.png)

**Comment by ghuntley** [comment]
howdy @TonyHenrique, Microsoft hasn't authored the Visual Studio integration with WebAssembly debugging yet thus it's important to start your debugging session by the "start WITHOUT debugging" menu option. See https://github.com/unoplatform/uno/blob/master/doc/articles/debugging-wasm.md for more information.
