### ISSUE TITLE
iOS Simulator : App crashes when TextBox gets focus

### ISSUE THREAD

**Issue by baskren** [unoplatform/uno#16264]
### Current behavior

iOS Simulator (both x64 and arm64), using Uno 5.0 or 5.1, .net7.0 or .net8.0, add a TextBox to a Panel and everything is fine.  As soon as the TextBox has focus, the app crashes.

This means that, if the app has a TextBox in its MainPage layout, the app crashes upon launch.

### Expected behavior

TextBox should be able to have focus without crashing the iOS simulator

### How to reproduce it (as minimally and precisely as possible)

1. Clone demo project : https://github.com/baskren/UnoTextBoxFocus_iOS_Crash
2. Build **iOS | Debug**  for an iOS Simulator (x64 or arm64)
3. Run / deploy to an iOS Simulator
4. Upon app launch, tap the [ADD TEXTBOX] button ... a new TextBox will be added 
5. Tap the TextBox (to give it focus) ... watch app crash

### Workaround

Use iOS hardware for test - less than ideal but doable.

**UPDATE** Use iOS 17.2 Simulator (see my followup comments, below).

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUi versions 5.0.34 - 5.1.104

### Affected platforms

iOS

### IDE

Visual Studio 2022, Visual Studio Code, Rider macOS

### IDE version

VSMac 7.6.10 (build 428); JetBrains Rider 2024.1 (Build #RD-241.14494.307); VisualStudio Code 1.88.1

### Relevant plugins

none

### Anything else we need to know?

Xcode Version 15.3 (15E204a)

<details>
<summary>JetBrains Rider Environment</summary>
JetBrains Rider 2024.1
Build #RD-241.14494.307, built on April 8, 2024
Licensed to Trial User
Subscription is active until May 8, 2024.
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
.NET Core v8.0.1 ARM64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.new.project.model.index.case.sensitivity=true
Non-Bundled Plugins:
  com.intellij.plugins.visualstudioformackeymap (241.14494.150)
  com.vermouthx.xcode-theme (1.6.3)
  atom-one (1.5.1)
  com.intellij.resharper.HeapAllocationsViewer (2024.1.0-eap01)
  com.berzanmikaili.intellij.monokai_pro (2.0.2c)
  com.emonadeo.tanne (0.4.0)
  monokai-pro (1.10)
  com.jetbrains.rider.android (241.14494.307)
  net.antelle.intellij-xcode-dark-theme (1.2.4)
  com.github.arm092.apricodemonokai (1.2.0)
  xndlnk.monokai (2.2)
  com.base16.shiromm.shiromm.monokai (1.1.0)
  com.samdark.intellij-visual-studio-code-dark-plus (2.8)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-241)
  com.dt.theme.vs (1.0)

</details>

<details>
<summary>VSCode Environment</summary>
Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:43:08.196Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
</details>

<details>
<summary>VSMac 2022 Environment</summary>
Visual Studio Enterprise 2022 for Mac
Version 17.6.10 (build 428)
Installation UUID: 0313dc68-6051-48f2-9d07-7df20474d1e1

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.402/Sdks
SDK Versions:
	8.0.201
	8.0.200
	8.0.100
	7.0.402
	7.0.400
	7.0.308
	7.0.307
	7.0.306
	7.0.304
	7.0.302
	7.0.203
	7.0.202
	7.0.200
	7.0.103
	7.0.102
	6.0.420
	6.0.419
	6.0.418
	6.0.417
	6.0.416
	6.0.415
	6.0.414
	6.0.413
	6.0.412
	6.0.410
	6.0.408
	6.0.407
	6.0.406
	6.0.405
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	8.0.2
	8.0.0
	7.0.12
	7.0.11
	7.0.10
	7.0.9
	7.0.7
	7.0.5
	7.0.4
	7.0.3
	7.0.2
	6.0.28
	6.0.27
	6.0.26
	6.0.25
	6.0.24
	6.0.23
	6.0.22
	6.0.21
	6.0.20
	6.0.18
	6.0.16
	6.0.15
	6.0.14
	6.0.13

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode: 15.3 22618
Build: 15E204a

Xamarin.Mac
Version: 9.3.0.23 Visual Studio Enterprise
Hash: 9defd91b3
Branch: xcode14.3
Build date: 2023-10-23 16:14:59-0400

Xamarin.iOS
Version: 16.4.0.23 Visual Studio Enterprise
Hash: 9defd91b3
Branch: xcode14.3
Build date: 2023-10-23 16:15:00-0400

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2024-03-07 20:35:36 UTC

Xamarin.Android
Version: 13.2.2.0 (Visual Studio Enterprise)
Commit: xamarin-android/d17-5/45b0e14
Android SDK: /Users/ben/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0  (API level 26)
		12.0 (API level 31)
		8.1  (API level 27)
		5.0  (API level 21)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 34.0.3
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: d9a6e87
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2024-03-07 20:35:42 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2024-03-07 20:35:42 UTC

Build Information
Release ID: 1706100428
Git revision: a5d4aa3648baa4a3f6bff645886bd51ad16c07a7
Build date: 2024-03-07 20:33:40+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 14.4.1
Darwin 23.4.0 Darwin Kernel Version 23.4.0
    Fri Mar 15 00:12:49 PDT 2024
    root:xnu-10063.101.17~1/RELEASE_ARM64_T6020 arm64

Enabled user installed extensions
Feature Switch 0.8
NuGet Package Explorer 0.12
Log Monitor 0.8
CSharp Interactive 0.5
NuGet Package Management Extensions 0.34
Project System Tools 0.13
VisualStudio View Inspector 0.9.1
Super Clean 2023.04.19.1

</details>

[Link to simulator crash .binlog file](https://github.com/baskren/UnoTextBoxFocus_iOS_Crash/blob/main/TextBoxTest.Mobile/net8.0-ios-Debug-iossimulator-x64.binlog)

**Comment by baskren** [comment]
<details>
<summary>Debug Console Crash Artifacts</summary>
ramework/UIKitCore : UIApplicationMain
	0x10e8f850a - /Users/ben/Library/Developer/CoreSimulator/Devices/3CCB38CE-8535-43D3-B033-9B07419F7196/data/Containers/Bundle/Application/BB7021CD-D47E-442F-87EE-42911C5A787C/TextBoxTest.Mobile.app/libxamarin-dotnet-debug.dylib : xamarin_UIApplicationMain
	0x10f7cd105 - /Users/ben/Library/Developer/CoreSimulator/Devices/3CCB38CE-8535-43D3-B033-9B07419F7196/data/Containers/Bundle/Application/BB7021CD-D47E-442F-87EE-42911C5A787C/TextBoxTest.Mobile.app/libmonosgen-2.0.dylib : do_icall
	0x10f7cb897 - /Users/ben/Library/Developer/CoreSimulator/Devices/3CCB38CE-8535-43D3-B033-9B07419F7196/data/Containers/Bundle/Application/BB7021CD-D47E-442F-87EE-42911C5A787C/TextBoxTest.Mobile.app/libmonosgen-2.0.dylib : do_icall_wrapper
	0x10f7bc5b6 - /Users/ben/Library/Developer/CoreSimulator/Devices/3CCB38CE-8535-43D3-B033-9B07419F7196/data/Containers/Bundle/Application/BB7021CD-D47E-442F-87EE-42911C5A787C/TextBoxTest.Mobile.app/libmonosgen-2.0.dylib : mono_interp_exec_method
	0x10f7b9d23 
- /Users/ben/Library/Developer/CoreSimulator/Devices/3CCB38CE-8535-43D3-B033-9B07419F7196/data/Containers/Bundle/Application/BB7021CD-D47E-442F-87EE-42911C5A787C/TextBoxTest.Mobile.app/libmonosgen-2.0.dylib : interp_runtime_invoke
	0x10f8a0758 - /Users/ben/Library/Developer/CoreSimulator/Devices/3CCB38CE-8535-43D3-B033-9B07419F7196/data/Containers/Bundle/Application/BB7021CD-D47E-442F-87EE-42911C5A787C/TextBoxTest.Mobile.app/libmonosgen-2.0.dylib : mono_runtime_invoke_checked
	0x10f8a809b - /Users/ben/Library/Developer/CoreSimulator/Devices/3CCB38CE-8535-43D3-B033-9B07419F7196/data/Containers/Bundle/Application/BB7021CD-D47E-442F-87EE-42911C5A787C/TextBoxTest.Mobile.app/libmonosgen-2.0.dylib : mono_runtime_exec_main_checked
	0x10f70c492 - /Users/ben/Library/Developer/CoreSimulator/Devices/3CCB38CE-8535-43D3-B033-9B07419F7196/data/Containers/Bundle/Application/BB7021CD-D47E-442F-87EE-42911C5A787C/TextBoxTest.Mobile.app/libmonosgen-2.0.dylib : mono_jit_exec
	0x10e93cbea - /Users/ben/Library/Developer/CoreSimula
tor/Devices/3CCB38CE-8535-43D3-B033-9B07419F7196/data/Containers/Bundle/Application/BB7021CD-D47E-442F-87EE-42911C5A787C/TextBoxTest.Mobile.app/libxamarin-dotnet-debug.dylib : xamarin_main
	0x10490e364 - /Users/ben/Library/Developer/CoreSimulator/Devices/3CCB38CE-8535-43D3-B033-9B07419F7196/data/Containers/Bundle/Application/BB7021CD-D47E-442F-87EE-42911C5A787C/TextBoxTest.Mobile.app/TextBoxTest.Mobile : main
	0x10d42c3e0 - Unknown
	0x2051bf366 - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x128ca514a):0x128ca513a  ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....
0x128ca514a  73 08 48 89 c7 e9 cc 99 ff ff c3 90 90 90 b8 53  s.H............S
0x128ca515a  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 b4 99  ...I....s.H.....
0x128ca516a  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  ...........I....

=============================
====================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:bool_objc_msgSendSuper <0x0009a>
	  at UIKit.UIResponder:BecomeFirstResponder <0x000e0>
	  at Microsoft.UI.Xaml.Controls.SinglelineTextBoxView:BecomeFirstResponder <0x0001c>
	  at <Module>:runtime_invoke_direct_bool__this__ <0x0013e>
	  at <unknown> <0x00000>
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:xamarin_UIApplicationMain <0x000b8>
	  at UIKit.UIApplication:UIApplicationMain <0x0006e>
	  at UIKit.UIApplication:Main <0x0015a>
	  at TextBoxTest.iOS.EntryPoint:Main <0x0002c>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00118>
	  at <unknown> <0x00000>
=================================================================
</details>

**Comment by baskren** [comment]
FWIW, [Resetting the iOS simulator](https://stackoverflow.com/a/11042584/4868078) does not fix this issue.

**Comment by baskren** [comment]
Related: https://github.com/dotnet/maui/issues/21051

**Comment by baskren** [comment]
Yep. this looks like what's going on : https://github.com/dotnet/runtime/issues/98941

UPDATED WORKAROUND : Use iOS Simulator 17.2.

**Comment by jeromelaban** [comment]
@baskren thanks for the research. Let's keep it opened for now, we'll follow this closely.

**Comment by MartinZikmund** [comment]
@baskren It seems the upstream issue was fixed, so it should be ok to close this now. If there are further issues let us know and reopen 👍

**Comment by baskren** [comment]
Will do
