### ISSUE TITLE
mono.js error in Debug mode

### ISSUE THREAD

**Issue by wallyh010** [unoplatform/uno#1627]
# What version of uno and what platforms you are using it with?
2.0.236-dev.2800

The error below occurs when using a Debug build.  Looks like a mono.js related failure.
The error does not occur when running in Release mode.

Let me know if you need more information to reproduce.

The following Exception message is caught after returning from posting to a REST API using the WasmHttpHandler.

```
Uno.UI.js:163 abort(). Build with -s ASSERTIONS=1 for more info.
(anonymous) @ Uno.UI.js:163
mono.js:1 /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mono/eglib/giconv.c:842: assertion 'str != NULL' failed
mono.js:1 Stacktrace: 

mono.js:1 Error
    at Array.ASM_CONSTS (mono.js:1)
    at _emscripten_asm_const_i (mono.js:1)


mono.js:1 ﻿* Assertion at /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mono/metadata/object.c:6791, condition `is_ok (error)' not met, function:mono_string_new_internal, Could not allocate 3404076248 bytes assembly:<unknown assembly> type:<unknown type> member:(null)
put_char @ mono.js:1
mono.js:1 System.Exception: abort(). Build with -s ASSERTIONS=1 for more info.
put_char @ mono.js:1
mono.js:1   at Uno.Threading.FastTaskCompletionSource`1[T].GetResult () <0x2aa0928 + 0x0006e> in <7ad8887b24554d28a5fe95f56a554ba2>:0 
put_char @ mono.js:1
mono.js:1   at Uno.Threading.FastTaskCompletionSource`1[T].CreateAsyncTask () <0x29c07d0 + 0x000b0> in <7ad8887b24554d28a5fe95f56a554ba2>:0 
put_char @ mono.js:1
mono.js:1   at Uno.UI.Wasm.**WasmHttpHandler**.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x29a18e8 + 0x003e6> in <1efbc17197a84996939b0c2cbb2d2e41>:0 
```

**Comment by jeromelaban** [comment]
This looks like the code is trying to allocate 3GB of memory, which is not particularly realistic.

Would you have sample that we can look at ?

**Comment by wallyh010** [comment]
The error only occurs in the Google Chrome browser.  
My Version 77.0.3865.90 (Official Build) (64-bit)

My OS: Microsoft Windows 10 Pro
My Version: 10.0.17763 Build 17763

The original error in the initial post is what is returned when running the REST service in IIS.
The solution\projects attached to this message are using IISExpress and returns the error message below which is probably just a different manifestation of the same problem.

The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

When building the attached solution, you may have to do a clean\rebuild on the Ai.ToolsApi project so the \bin\roslyn folder and associated files will be created.

The attached solution has multiple startup projects: The REST API, the UWP head and the Wasm head.  Once the pages have displayed you can just click on the Save button in the Wasm app to see the error displayed in the status bar at the bottom of the page.  The UWP app does not generate the error; however, the Wasm app does.  Please let me know if you need anything else.  Thanks.

[ToolsExp.zip](https://github.com/unoplatform/uno/files/3693601/ToolsExp.zip)

**Comment by ghuntley** [comment]
@wallyh010 do you have sample that we can look at ?

**Comment by wallyh010** [comment]
There was an error in my code.  I was attempting to deserialize (JSON) an empty string to a List<MyClass> returned from a REST API call and there was no expectation of ever returning an actual json string.

`var response = await client.SendAsync(request);
var responseData = await response.Content.ReadAsStringAsync(); //responseData = ""
var obj = JsonConvert.DeserializeObject<T>(responseData);`
The odd thing is that this was only a problem in the debug version of the Wasm head running in Chrome.  No errors were generated from either the release build of the Wasm head or the UWP app or when running the Wasm app from MS Edge or Firefox.

**Comment by ghuntley** [comment]
Thanks for replying back with these insights, it's great to hear that your problem has been resolved. If you spot anything else like this or if you have ideas how to make things better please start a discussion in a new issue (and send in a pull-request!)
