### ISSUE TITLE
[Android] The DatePickerFlyout_HasDataContextTest is failing

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#1634]
## Current behavior

The test does not pass.

## Expected behavior

See this code:
https://github.com/unoplatform/uno/blob/743aacfb78134b61b638808ccae25d9f70e1c301/src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/DatePickerTests/UnoSamples_Tests.DatePicker.cs#L20

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by NicolasChampagne** [comment]
The DatePickers child seems to have no dependencyproperties
