### ISSUE TITLE
[Gallery][All Platform]ContentDialog - When clicking inside the dialog box, the 'OK' button highlighting disappears.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#16358]
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/f7487d3e-76a5-42e9-b162-a031e551f13a

### Expected behavior

https://github.com/unoplatform/uno/assets/74563602/89ecd3a8-65f2-4321-8944-e1d66d0c920f

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "ContentDialog" from the "Component" list.
4. Click on 'Open Dialog' button for any option.
5. The Dialog box should open.
6. Now click anywhere in the opened dialog box.
7. Notice that the 'OK' button highlighting disappears.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS, Skia (GTK on Linux/macOS/Windows)

**Comment by agneszitte** [comment]
@MartinZikmund, @morning4coffe-dev I think the "Expected Result" is not correct and the current behavior is the correct one no?

**Comment by MartinZikmund** [comment]
As the expected video shows WinUI, I think it should be the correct behavior, as in our case clicking `ContentDialog` seems to unfocus the button, whereas on WinUI the button keeps the focus.

On the other hand (and that is a different issue) - I think this is Material style of dialogs while the tab says it should be fluent 🤔

**Comment by morning4coffe-dev** [comment]
I think the implementation is different Material/Fluent. In Fluent (WinUI) the Expected behavior is the correct one while with Material you are able to deselect the primary button 

https://github.com/unoplatform/uno/assets/78549750/4f3ad12a-40be-429e-b127-55de9b0ad76b

**Comment by MartinZikmund** [comment]
But as this is a style concern, I am not sure whether we keep the behavior separate in the two themes easily. On the other hand, the difference should not be a deal breaker, but we should still investigate, whether the unfocus should not be happening in Uno (as part of the popup handling)

**Comment by Youssef1313** [comment]
This happens because of https://github.com/unoplatform/uno/blob/057b269688a12c9d0a63329884b01133d02cf4d3/src/Uno.UI/UI/Xaml/Internal/InputManager.Pointers.cs#L192-L205

Ideally, this code should be removed once we have RootScrollViewer, and `ScrollViewer` itself would handle focus on pointer release, see:

![image](https://github.com/unoplatform/uno/assets/31348972/6c126256-3b47-4ccb-b632-34be7f320f65)

In the above case when inside a popup, there will be no ancestor ScrollViewer, so that's why focus shouldn't change.
