### ISSUE TITLE
Skia Localization is using incorrect culture

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#16353]
### Current behavior

As per these settings:

![image](https://github.com/unoplatform/uno/assets/1075116/1e7ff761-af28-48f0-99a3-202c0c043c81)

WinUI apps display in English, whereas GTK and WPF apps show up in Czech (for an app that has both `en` and `cs` strings.

### Expected behavior

Behavior should match

### Works on UWP/WinUI

None

**Comment by ArchieCoder** [comment]
Adding this debug output that might help

![image](https://github.com/unoplatform/uno/assets/1608424/e140602c-b8e6-4a17-8965-a1d111e669e7)
