### ISSUE TITLE
Setting Visibility of a AppBar or AppBarSeparator does not work

### ISSUE THREAD

**Issue by honzajscz** [unoplatform/uno#16369]
### Current behavior

If there is a template defined in a style for a UI control
<img width="422" alt="image" src="https://github.com/unoplatform/uno/assets/3704381/73ca1e47-5360-450b-87ee-409b1826b255">

setting the control's visibility property does not work in WASM.
<img width="422" alt="image" src="https://github.com/unoplatform/uno/assets/3704381/6365a5d1-239e-4d3d-98b8-d1b282c1c1fa">

### Expected behavior

Setting the visibility property needs to result in a corresponding visibility change for templated controls.

### How to reproduce it (as minimally and precisely as possible)

[ReproApp.zip](https://github.com/unoplatform/uno/files/15037293/ReproApp.zip)

This simple app reproduces the described behavior.
<img width="422" alt="image" src="https://github.com/unoplatform/uno/assets/3704381/f67296d9-5437-41ca-8f9b-63a95553248e">

XAML:
![image](https://github.com/unoplatform/uno/assets/3704381/e035e598-7c25-4ef6-b0fa-8f3276a39cae)

Code behind:
![image](https://github.com/unoplatform/uno/assets/3704381/7e097a43-814b-48c0-820e-4a57ad4a4472)

### Workaround

The workaround is to add a template binding to the visibility property.
<img width="422" alt="image" src="https://github.com/unoplatform/uno/assets/3704381/2d651538-6581-4766-897f-545829e25fb5">

### Works on UWP/WinUI

Works

### Environment

Win 11 Dev machine.

### NuGet package version(s)

![image](https://github.com/unoplatform/uno/assets/3704381/89f2caba-6faf-4266-b628-c519a246d3f0)

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

Version 17.9.5

### Relevant plugins

R# 2024.1

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/5.2
