### ISSUE TITLE
Breakpoints in SamplesApp can't be hit

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#16371]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/31348972/196732ce-cb79-483c-a50e-bd0ded4c11ad)

![image](https://github.com/unoplatform/uno/assets/31348972/c7d1ea86-729c-4386-8b1e-8892054d4d81)

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
cc @jeromelaban

**Comment by jeromelaban** [comment]
Caused by #16036, likely because of some symbols mangling.
