### ISSUE TITLE
[Skia macOS] Scroll bar never expands when hovered

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#16401]
### Current behavior

When hovered, the `ScrollBar` never expands, which makes it impossible to move it

![scrollbar](https://github.com/unoplatform/uno/assets/1075116/6f84e4cc-c014-474c-9fb9-a005993618c7)

### Expected behavior

Should expand when pointer is above the scroll bar area

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by spouliot** [comment]
The expansion issue has been fixed a while ago

<img width="286" alt="Screenshot 2024-11-04 at 11 31 30 AM" src="https://github.com/user-attachments/assets/4ce2889d-e2fe-49b6-82f7-ae8a9add32a3">
