### ISSUE TITLE
[Single Project][SVG - Windows]  SVG Build failing Due to Unhandled Exception and Unresolved Assembly for WASM. 

### ISSUE THREAD

**Issue by Darsh0307** [unoplatform/uno#16428]
### Current behavior

SVG is not loading properly for WebAssembly only. The latest and [new docs](https://platform.uno/docs/articles/features/svg.html?tabs=singleproject#how-to-use-svg) were followed while testing the SVG. 

The error list:- 

`1>        Task Parameter:File=obj\Debug\net8.0-browserwasm\UnoApp4.csproj.FileListAbsolute.txt
1>        Skipping write to file "obj\Debug\net8.0-browserwasm\UnoApp4.csproj.FileListAbsolute.txt" because content would not change.
1>      Done executing task "WriteLinesToFile".
1>
1>    Done building project "UnoApp4.csproj" -- FAILED.
1>  Done executing task "MSBuild" -- FAILED.
1>
1>Done building project "UnoApp4.csproj" -- FAILED.
1>
1>Build FAILED.
1>
1>C:\Users\DarshPatel\.nuget\packages\uno.wasm.bootstrap\8.0.13\build\Uno.Wasm.Bootstrap.targets(213,3): error : [00:00:00.7720875] Unhandled exception. System.Exception: Could not resolve Uno.UI.Svg
1>C:\Users\DarshPatel\.nuget\packages\uno.wasm.bootstrap\8.0.13\build\Uno.Wasm.Bootstrap.targets(213,3): error : [00:00:00.7721660]    at Driver.Resolve(String asm_name, AssemblyKind& kind) in /_/src/Uno.Wasm.Packager/packager.cs:line 247
1>C:\Users\DarshPatel\.nuget\packages\uno.wasm.bootstrap\8.0.13\build\Uno.Wasm.Bootstrap.targets(213,3): error : [00:00:00.7721740]    at Driver.Import(String ra, AssemblyKind kind) in /_/src/Uno.Wasm.Packager/packager.cs:line 318
1>C:\Users\DarshPatel\.nuget\packages\uno.wasm.bootstrap\8.0.13\build\Uno.Wasm.Bootstrap.targets(213,3): error : [00:00:00.7721756]    at Driver.Run(String[] args) in /_/src/Uno.Wasm.Packager/packager.cs:line 785
1>C:\Users\DarshPatel\.nuget\packages\uno.wasm.bootstrap\8.0.13\build\Uno.Wasm.Bootstrap.targets(213,3): error : [00:00:00.7722047]    at Driver.Main(String[] args) in /_/src/Uno.Wasm.Packager/packager.cs:line 412
1>C:\Users\DarshPatel\.nuget\packages\uno.wasm.bootstrap\8.0.13\build\Uno.Wasm.Bootstrap.targets(213,3): error : System.Exception: Failed to generate wasm layout (More details are available in diagnostics mode or using the MSBuild /bl switch)
1>C:\Users\DarshPatel\.nuget\packages\uno.wasm.bootstrap\8.0.13\build\Uno.Wasm.Bootstrap.targets(213,3): error :    at Uno.Wasm.Bootstrap.ShellTask_v22722a164cfb242bfbdc2b10248f624fa32b28c2.RunPackager() in /_/src/Uno.Wasm.Bootstrap/ShellTask.cs:line 768
1>C:\Users\DarshPatel\.nuget\packages\uno.wasm.bootstrap\8.0.13\build\Uno.Wasm.Bootstrap.targets(213,3): error :    at Uno.Wasm.Bootstrap.ShellTask_v22722a164cfb242bfbdc2b10248f624fa32b28c2.Execute() in /_/src/Uno.Wasm.Bootstrap/ShellTask.cs:line 271
1>    0 Warning(s)
1>    6 Error(s)`

### Expected behavior

The App should run and show the uno svg file as it can be seen in other platforms and show us the svg file in the application. 

For example :- 
<img width="474" alt="Screenshot 2024-04-23 at 12 29 36 PM" src="https://github.com/unoplatform/uno/assets/90713481/328e6e12-3942-4727-8313-0f3785497ac0">

### How to reproduce it (as minimally and precisely as possible)

- Create an Uno app using blank template
- Create a folder named `Svg` inside the Asset folder
- Add an SVG file inside the Svg folder. 
- Make sure that in the svg file its selected as `Content`if not the code in the .csproj file should be like this 

```
  <ItemGroup>
  <Content Include="Assets\Svg\logo.svg" />
</ItemGroup>
<ItemGroup>
  <None Remove="Assets\Svg\logo.svg" />
</ItemGroup> 
```

- Also follow the steps given on the  [SVG file docs](https://platform.uno/docs/articles/features/svg.html?tabs=singleproject#how-to-use-svg)
- Change to Wasm as the debugging target

### Works on UWP/WinUI

None

### NuGet package version(s)

Uno vsix :- 5.2.31
Uno.Templates.5.2.27

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.9.4

**Comment by jeromelaban** [comment]
@Darsh0307 can you post the project you created to reproduce the issue?

**Comment by Darsh0307** [comment]
This is the zip file in which i had the error coming. 
[UnoApp4.zip](https://github.com/unoplatform/uno/files/15080985/UnoApp4.zip)

**Comment by Darsh0307** [comment]
Now the SVG is working on all the platform when using with latest templates :- 5.2.31

**Comment by Darsh0307** [comment]
**This issue is now fixed on all platforms, no more error are coming related to Exception and Unresolved Assembly.** 



I created the sample app using the Blank template with Visual Studio Wizard.

Visual Studio Version: 
"Uno.Sdk": "5.2.108"
Uno templates:- 5.2.31
Uno VSIX :- 5.2.46.54
I tested the following platforms:

Windows - Packaged
Windows - Unpackaged
Android
iOS
MacCatalyst
WebAssembly (Chrome / Edge / Safari )
WebAssembly - IIS Express (Chrome / Edge / Safari )
Desktop (WSL)
Desktop (WSL2)


The zip file for the sample app I used for the tests:
[SVGtRIAL.zip](https://github.com/unoplatform/uno/files/15203200/SVGtRIAL.zip)
