### ISSUE TITLE
Improve documentation to provide clarity how to implement/contribute a feature

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1643]
## What's wrong?

Feedback from https://gitter.im/uno-platform/Lobby?at=5d911ee1bf625112c0038f64

> Hello. Where can I read more on how to contribute a feature? I found some steps here
https://gitter.im/uno-platform/Lobby?at=5d1dde106658420b1cf3bb23
but it was not very clear. I made Uno.UI to build successfully with my new feature, and now I want to make a NuGet package to test it locally. I found some info here
https://github.com/unoplatform/uno/blob/master/build/_HOW-TO-BUILD-AND-DEBUG-APPS.md
> Is there any single resource where I can read all I need to implement a feature?

## Any feedback?

Opening this up as `help wanted` as part of #hacktoberfest

**Comment by ghuntley** [comment]
This information is scattered between three documents:

1. https://github.com/unoplatform/uno/blob/master/build/_HOW-TO-BUILD-AND-DEBUG-APPS.md
1. https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/debugging-uno-ui.md
1. https://github.com/unoplatform/workshops/tree/master/uno-bootcamp/modules/07-Working-with-Uno

Thoughts:

- Move content from `build/_HOW-TO-BUILD-AND-DEBUG-APPS.md` into `articles/uno-development/debugging-uno-ui.md`
- Refactor `articles/uno-development/debugging-uno-ui.md`
- Add content from ttps://github.com/unoplatform/workshops/tree/master/uno-bootcamp/modules/07-Working-with-Uno into `articles/uno-development/debugging-uno-ui.md`

**Comment by ghuntley** [comment]
I highly recommend watching the following talk to glean insights to the desired outcome:

[![](http://img.youtube.com/vi/FJHsnqyvOjY/0.jpg)](http://www.youtube.com/watch?v=FJHsnqyvOjY "")

When someone is looking at the "contribute to Uno" documentation they are looking to do a "task" based outcome. The internals _may_ matter to the contributor but ultimately what they want to do is contribute to the code base. As such, the content should be structured in task based form and contain everything someone needs to know and no more. References to historical examples matter here. 

Might be a good candidate for a YouTube video.

**Comment by MartinZikmund** [comment]
I have documented my first time contribution to Uno Platform on my blog as a three-part series:
https://blog.mzikmund.com/2019/03/contributing-to-the-uno-platform-part-1/
https://blog.mzikmund.com/2019/04/contributing-to-the-uno-platform-part-2/
https://blog.mzikmund.com/2019/04/contributing-to-uno-platform-part-3/

**Comment by mkwhalen** [comment]
I'd be happy to work on this!

**Comment by Sumindar** [comment]
I am a beginner and would like to contribute to documentation kindly guide

**Comment by sakshamtaneja21** [comment]
i  would like to contribute

**Comment by harikrishnana2021** [comment]
I would like to contribute since I'm a beginner and I have the confidence to do it.

**Comment by vipulgupta2048** [comment]
Hey @ghuntley, one of the links you provided isn't working. https://github.com/unoplatform/uno/blob/master/build/_HOW-TO-BUILD-AND-DEBUG-APPS.md
I was just about to start working on this, but couldn't find this file.

**Comment by darenm** [comment]
Does this issue still need to be worked on? A few people suggested they were working on it. @ghuntley @agneszitte-nventive

**Comment by davidjohnoliver** [comment]
I don't think anyone is working on it. It's a pretty vague issue though, and the contribution docs have been expanded and tidied up since it was opened. https://platform.uno/docs/articles/uno-development/contributing-intro.html

@agneszitte-nventive Do we want to close this issue, and open new ones if there are specific problems/gaps in the contributor docs?
