### ISSUE TITLE
[iOS] Can't remove focus from Text Box by tapping outside

### ISSUE THREAD

**Issue by Soap-141** [unoplatform/uno#16462]
### Current behavior

We found a new bug in our open source canary where we can't remove focus from a `TextBox` by clicking outside on iOS.

![Animation_151](https://github.com/unoplatform/uno/assets/57812285/1b1c346c-fcad-418a-ab62-26acf1caae10)

### Expected behavior

We should be able to remove focus from a `TextBox` by clicking outside on iOS.

![Animation_152](https://github.com/unoplatform/uno/assets/57812285/77373c8b-b774-4f5d-8a35-1eb74fce23ff)

### How to reproduce it (as minimally and precisely as possible)

1. Clone this [branch](https://github.com/nventive/UnoApplicationTemplate-Canary/tree/canaries/build/dev/build_20240425.1).
2. Start the application on iOS.
3. Skip the onboarding.
4. Notice the issue in the login form.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.3.0-dev.697

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.9.6

**Comment by jeromelaban** [comment]
That's interesting, it's not reproducing in our canaries. @ajpinedam could you try to reproduce?

**Comment by ajpinedam** [comment]
@jeromelaban copied.

**Comment by ajpinedam** [comment]
@Soap-141 I tried reproducing the error with the project you provided, and I could not, either with the iOS Simulator or a real device.

Can you please provide other steps or more information?

https://github.com/unoplatform/uno/assets/1900897/44d7e0df-ccf5-4543-a2ff-1a20884785de

**Comment by Soap-141** [comment]
@ajpinedam I'll take a look, are you using iOS 17?

**Comment by ajpinedam** [comment]
> @ajpinedam I'll take a look, are you using iOS 17? Also are you tapping outside the control? Like on top of the Nice to see you again!

[Sorry for the delay]

Yes, I am running iOS 17.4.1 

Were you able to validate?

**Comment by Soap-141** [comment]
> > @ajpinedam I'll take a look, are you using iOS 17? Also are you tapping outside the control? Like on top of the Nice to see you again!
> 
> [Sorry for the delay]
> 
> Yes, I am running iOS 17.4.1
> 
> Were you able to validate?

@ajpinedam Yes I'm still able to reproduce it. Will check again Monday.

**Comment by Soap-141** [comment]
@ajpinedam I tried again on the last version and now the behaviour is different, I can unfocus a textbox and when I tap outside the password (while the focus is still on it) it goes back to the textbox.

![Animation_153](https://github.com/unoplatform/uno/assets/57812285/eca279a0-e84a-4338-bf7a-c8de89a8d96b)

**Comment by MartinZikmund** [comment]
The new behavior is consistent with WinUI, the same happens there as well. It happens because the `ScrollViewer` wrapping the login screen handles pointer released and sets focus on the first item inside, if it itself is not a tab stop. You can work around this behavior by marking the `ScrollViewer` (or even the `StackPanel` inside) a `TabStop`:

```xml
<ScrollViewer IsTabStop="True">
```
