### ISSUE TITLE
VS's project properties page crash with single-project

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#16490]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/8635919/d37ca0fe-72dc-42ba-8ac7-eb1b8a81111b)

### How to reproduce it (as minimally and precisely as possible)

1. Create a new project from the templates (5.2 single project)
2. Right click the project 
3. Try to open `Properties`

### Works on UWP/WinUI

None

**Comment by dr1rrb** [comment]
@jeromelaban

**Comment by ADD-David-Antolin** [comment]
This happens to me when the selected target framework is:
- browserwasm
- android
- ios
- maccatalyst
It shows the properties page on:
- WinUI
- desktop.

**Comment by agneszitte** [comment]
@jeromelaban open issue on VS side

**Comment by jeromelaban** [comment]
Visual studio issue: https://developercommunity.visualstudio.com/t/Project-Properties-failing-with:-System/10655592

**Comment by frogcrush** [comment]
Mine is slightly different but likely the same cause:
![image](https://github.com/unoplatform/uno/assets/6116333/bde332a6-e650-4bd2-a840-74de73b0712e)

**Comment by trydalch** [comment]
Is there a current work around? I'm trying to build/publish my first iOS release build, but it's not matching the provisioning profile. 

I'm willing to update the csproj file directly, but I don't know the schema and can't find the API reference.

**Comment by jeromelaban** [comment]
A possible workaround at this time is to keep only ios/android/catalyst target frameworks in the `TargetFrameworks` list temporarily, in order for the dialog to show up and make modifications to the project.
