### ISSUE TITLE
[iOS][Regression] SafeAreaPaddings are applied by default 

### ISSUE THREAD

**Issue by marwalsch** [unoplatform/uno#16503]
### Current behavior

This screenshot was taken with Uno.WinUI 5.1.104:

![Image (2)](https://github.com/unoplatform/uno/assets/72074423/dd082a74-2eab-484c-be68-83d5fb0c692a)

As you can see, the page's grey background reaches beyond the status bar and the dock. This behaviour is intended (at least this was the default up until now).
________________________________________________________________________________________________________________________________________

This is the same view with Uno.WinUI 5.2.94:

![Image](https://github.com/unoplatform/uno/assets/72074423/5e7597e1-75fc-4e18-b4e7-385565b9e092)

The page is enclosed by the status bar and the dock. To me it looks a lot like as id SafeAreaPaddings are enabled.

### Expected behavior

The page should reach beyond the status bar and the dock and dictate its background.

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI 5.2.94/5.3.0-dev.798

### Affected platforms

iOS

**Comment by jeromelaban** [comment]
@kazo0 does this look familiar?

**Comment by kazo0** [comment]
@marwalsch this behaviour is typically driven by:

```xml
<item name="android:windowTranslucentStatus">true</item>
<item name="android:windowTranslucentNavigation">true</item
```

In the `styles.xml` in the Android folder. Those usually shouldn't default to `true` in Uno apps. Would you be able to attach your reproduction apps as zips here? I can take a look and see what's causing this

Were these two apps just created from the Uno templates and nothing else was changed except the Uno version?

**Comment by kazo0** [comment]
Oh wait I just realized this is marked as iOS, sorry I thought those screenshots looked like an android device. Ok will investigate but would still be good to have those sample apps attached

**Comment by marwalsch** [comment]
@kazo0 I just tried this on the Android simulator. Here status bar and dock always behave as in image 2 from above, at least in 5.1.104 and several earlier releases.

I will try to break this down in a repro.

**Comment by kazo0** [comment]
@marwalsch does the page have any content in it behind the green areas?

**Comment by kazo0** [comment]
@marwalsch Also, if you would be able to post a repro project where this is happening on iOS, that would be super helpful! I Can't seem to get this to reproduce on my side. Is this happening on a physical iOS device or on the simulator as well?

**Comment by marwalsch** [comment]
@kazo0 Apologies for the delay, had plenty of interferences lately.

> @marwalsch does the page have any content in it behind the green areas?

Yes, the blackening roughly matches the original content. It shows that content is compressed along the y-Axis if you look at the space between blackened space and end of the grey background (if you look very closely). The repro makes this clearer

> @marwalsch Also, if you would be able to post a repro project where this is happening on iOS, that would be super helpful! I Can't seem to get this to reproduce on my side. Is this happening on a physical iOS device or on the simulator as well?

Is there a way to send the repro over a private channel? This way I could just strip down the affected project rather than rebuilding a new repro to avoid leakage of anything meant for the public.
I don't recall having tested this on the Simulator. It definitely is an issue on a physical iPhone 12 and SE.

**Comment by kazo0** [comment]
@marwalsch I think maybe you could push a sample app as a private repo on your GitHub and perhaps give me access to that repo only?

But first, there's a chance this _might_ have been fixed with the latest dev builds of Uno, so if you can try using version 5.3.0-dev.1256 or later and let me know?

**Comment by marwalsch** [comment]
@kazo0 The latest pre-releases indeed fixed this, I just tested it on the same devices as above.
Thanks a lot!

**Comment by kazo0** [comment]
@Youssef1313 another one fixed by the lifecycle PR. Same as https://github.com/unoplatform/uno/issues/16715
