### ISSUE TITLE
dotnet run --framework net8.0-windows10.0.19041 in VSCODE opens window but does not render UI Elements

### ISSUE THREAD

**Issue by sotoralph** [unoplatform/uno#16500]
### Current behavior

I installed the Uno Platform using the command lines and opened in VS Code. I open the terminal to the app directory and run

dotnet build

then

dotnet run --framework net8.0-windows10.0.19041

It runs and I see a blank page
<img width="941" alt="2024-04-28_18-50-58" src="https://github.com/unoplatform/uno/assets/25389628/ec70ce32-9f83-4847-afd4-949b671a9208">

I run the app inside of Visual Studio

### Expected behavior

I should see the Login Page.

### Workaround

Had to open in Visual Studio instead of VS Code for windows only. Wasm works on both VS and VSCode.

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
Thanks for the report. We're not reproducing the behavior you're showing.

`dotnet build` it [not particularly well supported](https://github.com/microsoft/WindowsAppSDK/issues/3548) by WinAppSDK at this time, which may cause the behavior you're seeing, but to be sure, could you open a `Developer Command Prompt for VS 2022` and start the app using the following:

```
msbuild /r /t:run /p:TargetFramework=net8.0-windows10.0.19041
```

**Comment by lindexi** [comment]
Thank you very much. I can build it with command line.

**Comment by TopperDEL** [comment]
Just stumbled across that issue, too. Building a library containing XAML with 'dotnet build' does not work. Switching to msbuild works neither, though.
I helped myself for the time being (don't have the time to investigate further, unfortunately) by linkin the files of my controls-library into my main-app.
