### ISSUE TITLE
The `.user` file should not override the targetframeworks if the override is not present

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#16507]
### Current behavior

If `.user` file contains an unknown target framework, inside VS the rewrite may be incorrectly reuse that TFM if it's not present in the `TargetFrameworks` list. 

### Expected behavior

Build continues to work properly even if the target frameworks list changes.

### Works on UWP/WinUI

None

### NuGet package version(s)

5.2.95

**Comment by agneszitte** [comment]
(Related discussion: https://github.com/unoplatform/uno/discussions/16504)
