### ISSUE TITLE
[Skia] Image rendering is not smooth for transparent .png

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#16519]
### Current behavior

The same transparent .png renders quite jagged on Skia targets vs other targets including WinAppSDK:

![image](https://github.com/unoplatform/uno/assets/1075116/ea381d00-66d8-429e-b420-e4cd64c705a4)

### Expected behavior

![image](https://github.com/unoplatform/uno/assets/1075116/1c05bf13-2de8-4b17-87c1-aca6abd4bcde)

### Works on UWP/WinUI

None

### Affected platforms

Skia (WPF), Skia (Linux X11), Skia (macOS), Skia (Linux Framebuffer), Skia (GTK)

**Comment by Youssef1313** [comment]
@MartinZikmund This looks like the same issue I was facing that I was going to open an issue for today :)

Image rendering will start using different APIs to ease support for Gifs starting with https://github.com/unoplatform/uno/pull/15951. So we should first evaluate if https://github.com/unoplatform/uno/pull/15951 will have any impact, and build a fix on top of that.
