### ISSUE TITLE
Pixel rounding on wasm

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#16544]
### Current behavior

Standard size
![image](https://github.com/unoplatform/uno/assets/8635919/1c334016-4fbe-4967-9aab-89f00cb9028d)

Full screen:
![image](https://github.com/unoplatform/uno/assets/8635919/1cd75b04-6809-4d04-9601-f5c763e68cca)

On Firefox grid does not appear at all, no matter the scaling

### Expected behavior

Grid visiblity is concsistent no matter the scaling

### How to reproduce it (as minimally and precisely as possible)

https://github.com/unoplatform/Uno.Samples/pull/675

### Works on UWP/WinUI

None

**Comment by dr1rrb** [comment]
@agneszitte

**Comment by agneszitte** [comment]
Did a quick test with @dr1rrb and we noticed that when changing the color for one cell we have this result:
![image](https://github.com/unoplatform/uno/assets/16295702/d31d0627-a0ed-4c70-a2bd-7b6d6e6365a4)
![image](https://github.com/unoplatform/uno/assets/16295702/3aed3a5d-4821-4c43-8e79-39f3a61509a7)

**Comment by agneszitte** [comment]
My version on WASM - Display 100%
Tested with Chrome, Chrome Canary, Edge, and Firefox
![image](https://github.com/unoplatform/uno/assets/16295702/5036ca8c-7651-415f-8285-1097de91ce05)

**Comment by agneszitte** [comment]
@dr1rrb closing this issue as we talked about the other day since we can see the lines on Windows as well. It is related to the current implementation of this sample with ItemsRepeater + Viewbox
