### ISSUE TITLE
[X11] Switch from `DllImport`s to `LibraryImport`s for better performance

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#16554]
### What would you like to be added

All bindings should be switched to `LibraryImport`:

https://github.com/unoplatform/uno/blob/2ea1c54b08f22b37e7a5ebf73d3049c4538687f1/src/Uno.UI.Runtime.Skia.X11/X11_Bindings/x11bindings_Glx.cs
https://github.com/unoplatform/uno/blob/2ea1c54b08f22b37e7a5ebf73d3049c4538687f1/src/Uno.UI.Runtime.Skia.X11/X11ApplicationHost.cs
https://github.com/unoplatform/uno/blob/2ea1c54b08f22b37e7a5ebf73d3049c4538687f1/src/Uno.UI.Runtime.Skia.X11/X11_Bindings/x11bindings_XLib.cs
https://github.com/unoplatform/uno/blob/2ea1c54b08f22b37e7a5ebf73d3049c4538687f1/src/Uno.UI.Runtime.Skia.X11/X11_Bindings/X11Helper.cs

**Comment by ramezgerges** [comment]
I have quite a few X11 PRs open, so let's put this one on hold until they merge so I don't have to deal with a million conflicts.
