### ISSUE TITLE
[WASM] TextBox Vertical Content Alignment/Padding not behaving as expected

### ISSUE THREAD

**Issue by iurycarlos** [unoplatform/uno#16568]
### Current behavior

The Fluent Textbox "vertical alignment" for its text differs between platforms:

WASM:
![image](https://github.com/unoplatform/uno/assets/6876973/8bf70df4-f058-452a-ae8e-250736765bd0)

DESKTOP:
![image](https://github.com/unoplatform/uno/assets/6876973/d7187098-fe22-408d-9b65-152b6bf3f80e)

We can observe that as long as we change the FontSize or the Height attributes, the result will be different.
Probably it is the alignment in skia that is broken, since WASM version seems correct.

### Expected behavior

The alignment should be the same in all platforms

### How to reproduce it (as minimally and precisely as possible)

Using:
Uno.Templates::5.2.31

Run:
dotnet new unoapp -o TextBoxAlignment -preset "recommended" -platforms "android" -platforms "maccatalyst" -platforms "wasm" -platforms "windows" -platforms "desktop" -platforms "ios" -theme-service False -vscode False -pwa False -theme "fluent" -presentation "mvux" -config False -di False -log "none" -nav "blank" -http False -loc False -tests "none" -toolkit False -dsp False -id "com.companyname.TextBoxAlignment" -pub "O=TextBoxAlignment"

Add this code to MainPage.xaml:

```
<TextBox VerticalContentAlignment="Center" Text="Testing Vertical Text Alignment" />

<TextBox
	VerticalContentAlignment="Center"
	FontSize="11"
	Text="Testing FontSize 11" />


<TextBox
	Height="50"
	VerticalContentAlignment="Center"
	Text="Testing height 50" />

```

### Works on UWP/WinUI

None

**Comment by kazo0** [comment]
Same strange behavior applies when trying to set a Padding on the TextBox:

```xml
<TextBox Padding="20,0,0,0" Text="Testing Padding at 20,0,0,0" />
```

<img alt="image" src="https://github.com/unoplatform/uno/assets/4793020/eb910a9b-d647-43ff-b032-b508af299dbc">

**Comment by Youssef1313** [comment]
![image](https://github.com/unoplatform/uno/assets/31348972/f6884026-07d0-4e55-a9e1-cb2c1f1d578c)

This is the behavior on WinUI, which appears to match Skia? Am I missing something?

**Comment by agneszitte** [comment]
@jeromelaban, @Youssef1313, @ramezgerges what is the status of this issue now that https://github.com/unoplatform/uno/pull/15958 is merged?

**Comment by Youssef1313** [comment]
#15958 is unrelated. The behavior on Skia is matching WinUI. The bad behavior is Wasm

**Comment by agneszitte** [comment]
> #15958 is unrelated. The behavior on Skia is matching WinUI. The bad behavior is Wasm

Yes, you are right @Youssef1313, I gave a little try on all platforms with the latest versions and only WASM has the bad behavior here. I adjusted the title of the issue.
