### ISSUE TITLE
`RatingControl.ApplyScaleExpressionAnimation` throws exception when enabled

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#16570]
### Current behavior

Currently the expression animation in `ApplyScaleExpressionAnimation` is disabled. When enabled, it throws an exception within the expression animation implementation.

### Expected behavior

Should not throw.

### How to reproduce it (as minimally and precisely as possible)

1. Clone `dev/mazi/ratingcontrol-winui3-release-1.4.2` or `master` if already merged
2. Undo Uno-specific code in `ApplyScaleExpressionAnimation`
3. Run samples app an open and `RatingControl` sample
4. The app should throw an exception

### Works on UWP/WinUI

Yes

**Comment by Youssef1313** [comment]
This is the same bug I encountered while working on RefreshContainer. The changes are in https://github.com/unoplatform/uno/pull/15630 already, I'll move them to a new PR.

**Comment by Youssef1313** [comment]
Re-opening as my PR fixed the underlying issue but didn't remove the Uno-specific workarounds.
