### ISSUE TITLE
Directive missing when adding the nuget CommunityToolkit.WinUI.UI.Controls

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#16613]
### What would you like clarification on

In this page https://platform.uno/docs/articles/uno-community-toolkit.html?tabs=tabid-winui, there is no mention that adding the references need to be done at 2 places: Directory.Packages.props and .csproj.

Directory.Packages.props needs to include the Version property and in .csproj, there is no version.

"add the following to your application" is not clear enough for someone new

### Concern

None

**Comment by jeromelaban** [comment]
This particular documentation will evolve soon with the 8.1 release of the community toolkit, which supports uno without all the tricks mentioned in this article. Using the latest pre-release mentioned here will give you a better experience: https://github.com/CommunityToolkit/Windows/discussions/383.
