### ISSUE TITLE
The extended Splashscreen rendered with Skia shows the app logo with a bad resolution

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#16641]
### Current behavior

Windows:
![image](https://github.com/unoplatform/uno/assets/1608424/0d5852ba-c24e-4aa6-8a72-b60aef2bd8dd)

Linux
<img width="457" alt="image" src="https://github.com/unoplatform/uno/assets/1608424/e01edbc7-5dfc-49e3-8325-1e2811b0bf89">

### Expected behavior

Perfect output especially when a SVG is provided

### How to reproduce it (as minimally and precisely as possible)

Use this test project [Test.zip](https://github.com/unoplatform/uno/files/15257316/Test.zip)

### Works on UWP/WinUI

None

### Affected platforms

Skia (WPF), Skia (Linux X11)

**Comment by jeromelaban** [comment]
This was fixed in 5.2.110 and later by https://github.com/unoplatform/uno/issues/16519, could you give it a try? Also, you can generally try with the latest pre-release bits to check if something was updated.

**Comment by ArchieCoder** [comment]
![image](https://github.com/unoplatform/uno/assets/1608424/e69b28b2-ca05-44db-96fe-e193fddb119a)

**Comment by Youssef1313** [comment]
@ArchieCoder You need to update the Uno.Sdk in `global.json`

**Comment by ArchieCoder** [comment]
Visual Studio is unhappy about this
https://github.com/unoplatform/uno/assets/1608424/a0fb456b-6605-4852-b0ba-545d11ddf94e

**Comment by jeromelaban** [comment]
Updating the global.json [is done with this](https://platform.uno/docs/articles/upgrading-nuget-packages.html#projects-using-the-unosdk). The global.json issue in VS is tracked here: https://github.com/NuGet/Home/issues/13127

**Comment by ArchieCoder** [comment]
5.2.110 didn't exist that's why VS was not working. 

With the command "dotnet outdated", it said 5.2.112 is the nearest version.

Setting with this version, the original bug is fixed! Thanks
