### ISSUE TITLE
[Wasm] TextBox in ListView does not accept spaces

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#16655]
### Current behavior

In https://playgroundcanary.z19.web.core.windows.net/#203f248a, it's not possible to add spaces to a TextBox.

### Expected behavior

Spaces are accepted.

### Workaround

None

### Works on UWP/WinUI

None

### NuGet package version(s)

5.2.102

### Affected platforms

WebAssembly

**Comment by dr1rrb** [comment]
> This may be related to
> 
> https://github.com/unoplatform/uno/blob/ef7b6a1e4e640f1fb9d702d3d3c5a92aff594cf0/src/Uno.UI/UI/Xaml/Controls/

If so, as this is on bubbling, we should probably just make sure that flagging this key event as handled does not cause the `preventDefault()` in native.

**Comment by jsinsel-kahua** [comment]
We'll also need Enter to behave properly for cases where the TextBox has AcceptsReturn.
