### ISSUE TITLE
Command bar icons not displayed or displayed in wrong colour.

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#1665]
The sample referred to  below contains a command bar with one icon.

On UWP the display is as expected, displaying white icons and white ellipsis on a dark background.
On Android and iOS no icon is displayed
On WASM the command bar icon is displayed, but the ellipsis does not obey the foreground colour change. The secondary menu is not displayed.

Project displaying issue at:
https://github.com/BrianDT/UnoColouredCommandBarIssue

Affected platform(s):
- [x] iOS
- [x] Android
- [/] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by BrianDT** [comment]
Clarification, primary menu items where the icon is defined as a BitmapIcon do display on iOS and Android. On iOS the ellipsis for the secondary commands are not displayed.
On Android the ellipsis are displayed but they are the wrong colour.
Importantly, the bound commands do not fire on WASM, Android or iOS.
The sample has been updated to reflect this.

**Comment by jeromelaban** [comment]
This has probably been fixed in recent builds of Uno, whether by the support monochrome Icons support, of themeing updates.

Is this issue still value for you ?

**Comment by BrianDT** [comment]
I have reviewed the functionality on all the platforms, things have improved but there are still elements that are not yet correct.
These checks were on Uno.UI build 3.0.12

IOS
Displays AppBar Icon: Yes
Displays AppBar bitmap: Yes
AppBar icons in the correct colour: Yes
Bound commands fire: Yes
AppBar Secondary Menu ellipsis displayed: Yes
AppBar Secondary Menu ellipsis in the correct colour: No
Secondary Menu displayed on ellipsis tap: No
Expands to avoids text clipping of icon text: No

Android
Displays AppBar Icon: No
Displays AppBar bitmap: Yes
AppBar icons in the correct colour: Yes
Bound commands fire: Yes
AppBar Secondary Menu ellipsis displayed: Wrong symbol
AppBar Secondary Menu ellipsis in the correct colour: No
Secondary Menu displayed on ellipsis tap: No
Expands to avoids text clipping of icon text: Yes

WASM
Displays AppBar Icon: Yes
Displays AppBar bitmap: Yes
AppBar icons in the correct colour: Yes
Bound commands fire: No
AppBar Secondary Menu ellipsis displayed: Yes
AppBar Secondary Menu ellipsis in the correct colour: No
Secondary Menu displayed on ellipsis tap: No
Expands to avoids text clipping of icon text: Yes

The sample has been updated to this build

**Comment by jeromelaban** [comment]
Thanks for the research!

**Comment by LHuss** [comment]
I'll link all the relevant issues since this one kind of turned into an epic
AppBar Secondary Menu ellipsis in the correct colour: #4396
Secondary Menu displayed on ellipsis tap: #4394 
Expands to avoids text clipping of icon text: #4397 

Regarding "Bound commands fire", in your repro [right here](https://github.com/BrianDT/UnoColouredCommandBarIssue/blob/25bb3af04f608ff662452ea8f67f3e4960d446f5/UnoColouredCommandBarIssue.Shared/Framework/UIDispatcher.cs#L85) is the issue and not supportable in wasm as the runtime is single threaded.
