### ISSUE TITLE
[Docs][Release] error : The platform 'AnyCPU' is not supported for Self Contained mode.

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno#16662]
### What would you like clarification on

Regarding this [error : The platform 'AnyCPU' is not supported for Self Contained mode.](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=124342&view=logs&j=e4c53f19-1dc0-5952-d087-a4a24555bd84&t=98a1b098-9f98-5127-03a6-7ce8a398f30f&l=66)

We need to add proper documentation to give more details on what to do:
- For CI Build, example:
https://github.com/unoplatform/Uno.Samples/commit/81817c257bae7ac3fea7cb945bbdd53973f7795a
- Locally:
You need to specify a platform in the configuration at the moment

These details should be added to the Publishing section of the documentation that needs to be added ([related details here](https://github.com/unoplatform/private/issues/400))

### Concern

Publishing your application

**Comment by MartinZikmund** [comment]
Could the release configurations be pre-generated to accommodate for this? Specifically ARM64, x86, x64

**Comment by jeromelaban** [comment]
We will not need to generate configurations, the change in #16720 will ensure that there's a default platform set properly.

**Comment by jeromelaban** [comment]
Let's close this issue and continue tracking in https://github.com/unoplatform/private/issues/400
