### ISSUE TITLE
TextBlock text shaping broke

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#16676]
>  I'll put it here. if you want to, you can open an issue. thanks
I'm referring everything such as textbox, textblock and button:
>
> ![Screenshot from 2024-05-04 16-19-42](https://github.com/unoplatform/uno/assets/73298440/ee35f2b8-0cf3-466f-baa2-f6746f2946f6)
>
> by the way, this is ubuntu 22.04 and vscode. latest version of everything

_Originally posted by @aliajboy in https://github.com/unoplatform/uno/issues/6783#issuecomment-2104703948_

**Comment by ramezgerges** [comment]
Yes, this is a known limitation of our managed TextBox: RTL languages are not supported. @jeromelaban should we prioritize this? 

Meanwhile, users can use the GTK target with `FeatureConfiguration.TextBox.UseOverlayOnSkia = true`

**Comment by Youssef1313** [comment]
Arabic renders correctly on my machine, even when explicitly setting `FontFamily` to a font that doesn't contain Arabic characters. Assigning to Ramez in case he can reproduce.

**Comment by ramezgerges** [comment]
@aliajboy Can you please give us a small repro project that showcases the problem? Make sure you're using the most recent packages.

**Comment by Youssef1313** [comment]
Segments are not calculated correctly when the font doesn't have the needed glyph, causing Arabic text to have a segment per letter, which is incorrect
