### ISSUE TITLE
[Single project] Infinite project reload loop

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#16692]
### Current behavior

After closing and reopening a solution with single project, VS got into an infinite loop of reloading the project thinking that active framework was changed.

![reloadingforever](https://github.com/unoplatform/uno/assets/1075116/7e4e6535-46cd-45a1-8406-712f54ae9245)

### Expected behavior

Should not happen

### How to reproduce it (as minimally and precisely as possible)

Not sure 🤷‍♂️ . It happened randomly, crashed VS twice and then I managed to manually switch the active framework in between somehow and then it stopped.

### Works on UWP/WinUI

None

### IDE

Visual Studio 2022

**Comment by MartinZikmund** [comment]
Also this happens during:

![image](https://github.com/unoplatform/uno/assets/1075116/a56d7b57-ac45-469e-a49f-413b3df58ca1)

![image](https://github.com/unoplatform/uno/assets/1075116/f674f00b-c01e-45f4-8b05-5251847b2b0a)

**Comment by MartinZikmund** [comment]
This then happened to my Uno Platform library:

![image](https://github.com/unoplatform/uno/assets/1075116/61a9d455-dd35-46eb-8d77-f5499328ef27)

**Comment by MartinZikmund** [comment]
Not sure if relevant, but I closed the solution when the target was WinAppSDK Packaged

**Comment by jeromelaban** [comment]
When this happens, can you zip the whole solution folder, in hopes we can reproduce later? Did it happen again later?

**Comment by jeromelaban** [comment]
There's no clear repro at this time, and it may be fixed by #16710. We'll reopen if steps become clearer.
