### ISSUE TITLE
AppBarButton with an image does not render perfectly

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#16697]
### Current behavior

The arrow from the default project shows a fuzzy arrow

<img width="505" alt="image" src="https://github.com/unoplatform/uno/assets/1608424/83d3601b-7af0-4593-9d19-555b7204e90e">

Note: the second arrow is from the original image opened with Edge then zoom

### Expected behavior

Better render of an image

### How to reproduce it (as minimally and precisely as possible)

1- Create a new project with the default option
2- Run and click on Second page

### Works on UWP/WinUI

None

### Affected platforms

Skia (WPF), Windows (WinAppSDK)

**Comment by Youssef1313** [comment]
@ArchieCoder There was recently a change in image rendering to improve these cases, which is available in the latest 5.2 stable starting with 5.2.112, and the latest 5.3 devs starting with 5.3.0-dev.841.

Can you make sure you're using a version that includes this fix?

**Comment by ArchieCoder** [comment]
@Youssef1313 I'm with "Uno.Sdk": "5.2.121".

**Comment by Youssef1313** [comment]
Thanks. Then it's different than the issue fixed recently.

**Comment by jeromelaban** [comment]
This looks like an scaled asset invalid selection. Are you running this app in more than 100% scaling?

**Comment by ArchieCoder** [comment]
@jeromelaban I'm at the recommended scaling at 150%. With a resolution of 3840x2160, it would be super hard to read at 100%.

I tried the Uno back asset in a WinUI app and it acts weird. The arrow does not scale, but the background does.

WinUI + SVG still have issues apparently https://github.com/microsoft/microsoft-ui-xaml/issues/825#issuecomment-1656381521

![image](https://github.com/unoplatform/uno/assets/1608424/ecd00528-5d46-40f9-bb82-5aabc4abe9b1)
