### ISSUE TITLE
Trailing semicolon in `UnoFeatures` shows warning in VS

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#16691]
### Current behavior

The default template generates a trailing semicolon which gets a warning in VS:

![image](https://github.com/unoplatform/uno/assets/1075116/d7fec823-9097-4bf4-aa88-5def9e10272f)

### Expected behavior

No warning

### Works on UWP/WinUI

None

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
This is not a Visual Studio error. Are you using an extension (maybe Mikayla's ?)

**Comment by MartinZikmund** [comment]
Ah that's possible, I have the MSBuild editor plugin. In that case that's not that concerning.
