### ISSUE TITLE
Investigate Padding interaction with borders and border backgrounds

### ISSUE THREAD

**Issue by ramezgerges** [unoplatform/uno#16705]
### Current behavior

Currently, the padding on an `IBorderInfoProvider` is not used to calculate the numbers for the border shape and the border background. A quick attempt found some differences between WinUI and Uno (at least skia) when Padding is added. This should be investigated after https://github.com/unoplatform/uno/pull/16562 merges

### Works on UWP/WinUI

None

**Comment by MartinZikmund** [comment]
This also should take `BackgroundSizing` property into account

**Comment by Youssef1313** [comment]
I thought padding is only considered during measure/arrange and shouldn't have any impact elsewhere 😕

**Comment by ramezgerges** [comment]
The `BorderVisualClipping` sample used to do some weird stuff if you added a `Padding` to the elements, but I'm testing it now and it seems to be... fine? I will close for now until I find an actual problem.
![image](https://github.com/unoplatform/uno/assets/66218781/dbe40900-ca3a-4735-bd06-2bd0fd734660)
