### ISSUE TITLE
UserControl does not compile with WinAppSDK

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#16708]
### Current behavior

When the WinAppSDK target is selected, my 2 UserControls don't compile:

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	WMC0001	Unknown type 'TitleWithAppControl' in XML namespace 'clr-namespace:ElementsTechnician.Presentation;assembly=Test, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'	Test	C:\Users\sebas\Downloads\ElementsTechnician\ElementsTechnician\Presentation\MainPage.xaml	111		

It compiles fine with the other targets.

### Expected behavior

It should compile with all targets.

My user control is simply a StackPanel with a TextBlock

<UserControl
    x:Class="ElementsTechnician.Presentation.TitleControl"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    x:Name="Self"
    d:DesignHeight="300"
    d:DesignWidth="400"
    mc:Ignorable="d">

    <StackPanel
        Background="Blue"
        Orientation="Horizontal"
        Padding="8">

        <TextBlock
            FontSize="30"
            Foreground="White"
            HorizontalAlignment="Center"
            Text="Blue"
            VerticalAlignment="Center" />

    </StackPanel>

</UserControl>

### How to reproduce it (as minimally and precisely as possible)

Open this sample app and compile [Test.zip](https://github.com/unoplatform/uno/files/15295907/Test.zip)

### Works on UWP/WinUI

Yes

### Affected platforms

Windows (WinAppSDK)

### IDE

Visual Studio 2022

**Comment by Youssef1313** [comment]
In `MainPage.xaml`, you have `xmlns:presentation="clr-namespace:ElementsTechnician.Presentation"`

This should be replaced by `xmlns:presentation="using:ElementsTechnician.Presentation"`

The fact that it compiles in Uno target is a behavior that we will likely change a breaking change to keep parity with WinUI

**Comment by ArchieCoder** [comment]
Good catch, I confirm it compiles. I'm puzzled how I ended up with this xmlns line. I never write this, I always use what VS/Resharper suggests. I guess one of them was wrong.

**Comment by Youssef1313** [comment]
Probably ReSharper isn't able to recognize the XAML as "WinUI" XAML if it doesn't respect `DefaultXamlRuntime`.

Or maybe this could have happened if you were typing code while restore hasn't completed, in which case, the `DefaultXamlRuntime` property isn't yet set and probably VS and/or Rider falls back to WPF flavored XAML.
