### ISSUE TITLE
Running Unoplatform application on autostart CM4

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#16719]
### Discussed in https://github.com/unoplatform/uno/discussions/16716

<div type='discussions-op-text'>

<sup>Originally posted by **wafamab** May 14, 2024</sup>
Hello, I'm trying to run a Uno Platform application on autostart with FRAMEBUFFER=/dev/fb1, but I'm encountering the following issue: 'Unhandled exception. System.InvalidOperationException: Cannot read keys when either the application does not have a console or when console input has been redirected. Try Console.Read.' Has anyone encountered this issue before?</div>

**Comment by jeromelaban** [comment]
Thanks for the report! This is indeed a behavior that is found in https://github.com/unoplatform/uno/blob/a713fc557052973a69bc9e9e491c8041ea2d7130/src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FramebufferHost.cs#L86-L87

Where the app expects to be started from a terminal, in order for it to be stopped by the user.

There could definitely be a sub-builder option in the console builder that avoids this behavior in:

https://github.com/unoplatform/uno/blob/a713fc557052973a69bc9e9e491c8041ea2d7130/src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/Builder/HostBuilder.cs#L11-L12

**Comment by eantunes1980** [comment]
Hi, I have the same problem. And our Project hungs on that point to be ordered by the customer. 
Should there be a solution soon for that?
I've tried to resolve the problem and to publish a pull request if it works, but my enviroment seems to not be correct. I have build the sources and exchanged the uno dlls from my App with the new builded. It runs without error but without displaying anything. And that without changing any code for the first test.

**Comment by jeromelaban** [comment]
This issue will be fixed by https://github.com/unoplatform/uno/pull/16750, you'll be able to test it with the uno.sdk prerelease builds once it's merged.

**Comment by eantunes1980** [comment]
Nice thank you

**Comment by wafamab** [comment]
Hello again, I want to ask if there is a new Uno.Sdk prerelease version that contains the fix for running Uno Platform applications in autostart. I tried to add this prerelease "Uno.Sdk": "5.4.0-dev.362" in global.json, but it doesn't work for me, and there is no Uno NuGet package to be updated with this version. Thank you in advance.

**Comment by jeromelaban** [comment]
You can search for the uno.sdk versions on nuget.org or https://nuget.info. The current latest prerelease is 5.4.0-dev.27.
