### ISSUE TITLE
[Desktop] scrollbar styling under net8.0-desktop is obsolete (strongly differs from current net8.0-windows10.0.19041)

### ISSUE THREAD

**Issue by kucint** [unoplatform/uno#16718]
Hi @MartinZikmund, I created a test app that supports both `net8.0-windows10.0.19041` and `net8.0-desktop`. 

when running an app under windows as net8.0-windows10.0.19041 and net8.0-desktop, I observe that scrollbar renders differently.

 `net8.0-windows10.0.19041`
![image](https://github.com/unoplatform/uno/assets/54866088/0c6dc6a1-b8ff-4d76-9082-4db7b7e50fd7)

 `net8.0-desktop`
![image](https://github.com/unoplatform/uno/assets/54866088/f7508e1b-9386-4742-af98-0d1ca0d99d18)

**Question**: Will this discrepancy be be fixed in the future release(s) or do am I missing something?

_Originally posted by @kucint in https://github.com/unoplatform/uno/discussions/16608_

**Comment by Youssef1313** [comment]
Thanks for reporting this @kucint

Indeed, currently the scollbar in Uno is using old styles. This is being tracked in https://github.com/unoplatform/uno/issues/16648. So, I'm going to close this issue as a duplicate.

You can thumbs up the existing issue and subscribe for notifications.
