### ISSUE TITLE
[iOS] PipsPager breaks app layout

### ISSUE THREAD

**Issue by mcocaroUX** [unoplatform/uno#16715]
## Current behavior

Currently when having a PipsPager+FlipView linked by SelectorExtensions at a Page and its changes it selected value, safe area (bottom and top) turns black. I could reproduce this only on iOS
Before sliding:
![Simulator_Screenshot_-_iPhone_15_-_2024-05-07_at_16 59 20](https://github.com/unoplatform/uno.toolkit.ui/assets/94198647/df870261-4b55-44ef-9a13-10510d6761b6)
After sliding:
![Simulator_Screenshot_-_iPhone_15_-_2024-05-07_at_16 59 39](https://github.com/unoplatform/uno.toolkit.ui/assets/94198647/c243a695-3a70-40fd-8797-54b6d48e5ef1)

## Expected behavior

Safe area should not be affected

## How to reproduce it (as minimally and precisely as possible)

[FlipViewSafeArea.zip](https://github.com/unoplatform/uno.extensions/files/15240447/FlipViewSafeArea.zip)

Run sample
Flip to show next image
Notice how safe area turns black

## Environment

Package Version(s):
Uno.Sdk: 5.2.108

```
<PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
<PackageVersion Include="coverlet.collector" Version="6.0.0" />
<PackageVersion Include="FluentAssertions" Version="6.12.0" />
<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
<PackageVersion Include="NUnit" Version="4.0.1" />
<PackageVersion Include="NUnit3TestAdapter" Version="4.5.0" />
<PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
<PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.2428" />
<PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.4.231219000" />
<PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
<PackageVersion Include="Uno.Extensions.Hosting" Version="4.1.21" />
<PackageVersion Include="Uno.Extensions.Hosting.WinUI" Version="4.1.21" />
<PackageVersion Include="Uno.Extensions.Logging.OSLog" Version="1.7.0" />
<PackageVersion Include="Uno.Extensions.Logging.WinUI" Version="4.1.21" />
<PackageVersion Include="Uno.Extensions.Navigation" Version="4.1.21" />
<PackageVersion Include="Uno.Extensions.Navigation.WinUI" Version="4.1.21" />
<PackageVersion Include="Uno.Extensions.Navigation.Toolkit.WinUI" Version="4.1.21" />
<PackageVersion Include="Uno.Extensions.Reactive" Version="4.1.21" />
<PackageVersion Include="Uno.Extensions.Reactive.WinUI" Version="4.1.21" />
<PackageVersion Include="Uno.Material.WinUI" Version="5.0.13" />
<PackageVersion Include="Uno.Toolkit.WinUI" Version="6.0.18" />
<PackageVersion Include="Uno.Toolkit.WinUI.Material" Version="6.0.18" />
<PackageVersion Include="Uno.Resizetizer" Version="1.4.8" />
<PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="$(UnoVersion)" />
<PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
<PackageVersion Include="Uno.WinUI" Version="$(UnoVersion)" />
<PackageVersion Include="Uno.WinUI.Lottie" Version="$(UnoVersion)" />
<PackageVersion Include="Uno.WinUI.DevServer" Version="$(UnoVersion)" />
<PackageVersion Include="Xamarin.Google.Android.Material" Version="1.10.0.2" />
<PackageVersion Include="Uno.UITest.Helpers" Version="1.1.0-dev.70" />
<PackageVersion Include="Xamarin.UITest" Version="4.3.3" />
```

- [X] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Skia (WPF)
- [ ] Skia (GTK on Linux/macOS/Windows)
- [ ] Skia (Linux Framebuffer)
- [ ] Build tasks

Visual Studio:

- [ ] 2019 (version: )
- [X] 2022 (version: )
- [ ] Visual Studio Code (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
[PipsApp.zip](https://github.com/unoplatform/uno/files/15313677/PipsApp.zip)


Simple repro app

**Comment by kazo0** [comment]
@mcocaroUX Would you be able to confirm that this is no longer occurring as of the Uno.Sdk version 5.3.0-dev.1256?

**Comment by mcocaroUX** [comment]
@kazo0 Issue is fixed on 5.3.0-dev.1256. Thank you!

**Comment by agneszitte** [comment]
@kazo0 do we need to backport something for 5.2 stable?

**Comment by jeromelaban** [comment]
@agneszitte the changes implied cannot be backported, it's related to lifecycle changes.
