### ISSUE TITLE
[HR] Reloading a control does apply outer attached properties

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#16723]
### Current behavior

When changing a property in StatusBar.xaml in a debugging session, the StatusBar will expand at max height 

https://github.com/unoplatform/uno/assets/1608424/4f1b9105-2214-43f5-aadb-1d57c532f363

### How to reproduce it (as minimally and precisely as possible)

1- Open the project [Test.zip](https://github.com/unoplatform/uno/files/15311010/Test.zip)
2- Start the debugging session
3- Open StatusBar.xaml then change line 12 to Background="Red" then click Save.

The whole StatusBar will goes max height.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Skia (WPF)

### IDE version

Latest VS Code

**Comment by jeromelaban** [comment]
Thanks the for the report!

It looks like we're not properly re-applying the attached properties from the creating site when elements are reloaded.

```
<presentation:StatusBar
    Grid.Row="1" />
```

**Comment by Youssef1313** [comment]
@ArchieCoder The attached repro project is different from the code in the video. I can't repro with the attached project. Can you check if the issue happens in the attached project, and if so, mention the line number you're modifying?
