### ISSUE TITLE
Add support for storing photos and videos without using the FileSavePicker

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#16721]
### What would you like to be added

Add support for WinUI APIs such as [KnownFolders.GetFolderAsync](https://learn.microsoft.com/en-us/uwp/api/windows.storage.knownfolders.getfolderasync?view=winrt-22621) that would provide access to saving files directly.

### Why is this needed

Once the permission has been provided, it gives a better user experience that having to go through the picker.

### For which platform

Android, iOS

**Comment by jeromelaban** [comment]
@darenm about being able to store photos without having to go through the picker, in order to be sure, do you need to list media from the library, or only to write media to the library.

**Comment by darenm** [comment]
@jeromelaban This particular scenario was related to allowing the selection of multiple media elements in the Kahua media manager and to be able to "bulk" download them and save them to the library. In this specific instance, writing to the library is all that is required.

Thinking things through, how would we manage things like name collisions for existing files, etc.?

**Comment by jeromelaban** [comment]
Thanks for the update. This really means that enumerating files from the media library is needed, as you'll have to handle collisions as well. That is unless the new API provides a way to automatically handle collisions by renaming files as needed.

/cc @MartinZikmund

**Comment by MartinZikmund** [comment]
@darenm On iOS the name collisions are handled "automagically" by the system and there is no way to influence conflicts - it just changes the name as it wishes. On Android if the same name exists, it will overwrite, and there is no warning or anything... Easiest solution is to set the file names uniquely (GUIDs, datetime + some identifier, etc.). The files are stored in an app-specific folder in case of Android.

**Comment by MartinZikmund** [comment]
@darenm for now I created a sample app that does media saving on Android and iOS, the classes can be used as-are in any Uno project

**Comment by MartinZikmund** [comment]
Closing for now, feel free to reopen if more is needed
