### ISSUE TITLE
Extended splash screen does not render perfectly with the specified solid color

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#16725]
### Current behavior

With Skia, the app starts with a white page then black page then the splashscreen color defined with <UnoSplashScreenColor>#00FF00</UnoSplashScreenColor>

With WinUI, the app starts with a black page then the splashscreen color defined with UnoSplashScreenColor, but the logo area will have a different fade in color.

2 videos (Skia and WinUI):
https://github.com/unoplatform/uno/assets/1608424/ca46556e-90f9-47dc-ab2a-09be367c44e6
https://github.com/unoplatform/uno/assets/1608424/5fe4cc1b-dd4e-4f27-b952-67d401456c16
![WinUI](https://github.com/unoplatform/uno/assets/1608424/0c85fe05-d809-45eb-bcba-c1f6935d1864)

### Expected behavior

The color should be unique from the start to the end

### How to reproduce it (as minimally and precisely as possible)

1- Create new project
2- Add <UnoSplashScreenColor>#00FF00</UnoSplashScreenColor> in the project file

Note: In ShellModel.cs in the start, I added a await Task.Delay(10000) with the goal to see the splashscreen longer, but it does not work, the navigations goes right away to the MainPage.

If you want to check the behavior, use a screen recorder and scroll manually.

[UnoAppSplash.zip](https://github.com/unoplatform/uno/files/15311537/UnoAppSplash.zip)

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Skia (WPF), Windows (WinAppSDK)

### IDE

Visual Studio 2022

**Comment by ArchieCoder** [comment]
@kazo0 FYI https://twitter.com/archiecoder/status/1788332275605627189

**Comment by agneszitte** [comment]
fyi @MartinZikmund, @Youssef1313

**Comment by MartinZikmund** [comment]
This may also be resizetizer related
