### ISSUE TITLE
Styles like colors defined in a file does not work with WinAppSDK

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#16740]
### Current behavior

The exception is thrown: 

Cannot find a Resource with the Name/Key ActionBackgroundBrush [Line: 21 Position: 21]

### Expected behavior

Resource should be found

### How to reproduce it (as minimally and precisely as possible)

Run the app using WinAppSDK target [UnoStyle.zip](https://github.com/unoplatform/uno/files/15322747/UnoStyle.zip)

It works with Desktop / Skia

### Works on UWP/WinUI

None

### Affected platforms

Windows (WinAppSDK)

### IDE

Visual Studio 2022

### IDE version

Latest VS Code

**Comment by ArchieCoder** [comment]
@kazo0 Pointed me to this bug from Microsoft. Adding a dummy resource fixes the bug.

https://stackoverflow.com/questions/44266369/xaml-resourcedictionary-not-loading-correctly-with-a-single-keyset

**Comment by agneszitte** [comment]
> @kazo0 Pointed me to this bug from Microsoft. Adding a dummy resource fixes the bug.
> 
> [stackoverflow.com/questions/44266369/xaml-resourcedictionary-not-loading-correctly-with-a-single-keyset](https://stackoverflow.com/questions/44266369/xaml-resourcedictionary-not-loading-correctly-with-a-single-keyset)

@jeromelaban, @kazo0 not sure if Microsoft has a proper issue opened for this lately.
All the previous links mentioned [here](https://stackoverflow.com/questions/44266369/xaml-resourcedictionary-not-loading-correctly-with-a-single-keyset) and [here](https://bengribaudo.com/blog/2010/08/19/106/bug-single-application-resources-entry-ignored) are not working anymore.

**Comment by ArchieCoder** [comment]
Maybe it is worth to ping them in the WinDev discord server.
