### ISSUE TITLE
[Uno Samples][IOS] CLI not working for running Sample app on simulator 

### ISSUE THREAD

**Issue by Darsh0307** [unoplatform/uno#16748]
After downloading the artificats of "ios-uitest-build" from [Uno UI CLI](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=124927&view=artifacts&pathAsName=false&type=publishedArtifacts) and then running the CLI on the terminal in order to run the app on IOS simulator `xcrun simctl install booted /Users/darshpatel/Downloads/ios-uitest-build/SamplesApp.app`

By using this i was able to even install the Samples App in the IOS simulator. 

But when i am trying to open the app, its failing unfortunately. 

https://github.com/unoplatform/Uno.Samples/assets/90713481/ae482a87-4a54-454b-b769-39465686d0fc

**Comment by agneszitte** [comment]
fyi @jeromelaban

**Comment by Dynaruid** [comment]
The issue has recently appeared in AvaloniaUI as well. When targeting the iOS simulator, building for iossimulator-x64 should allow the app to start normally.

**Comment by jeromelaban** [comment]
@Darsh0307 Unpacking the assets from skia-generic-samples-app-WinUI then run dotnet dotnet SamplesApp.Skia.Generic.dll is enough.

You may need to use wget with the url of the skia-generic-samples-app-WinUI artifact to get the file first, so work around the fact that the finder is flagging the file.
