### ISSUE TITLE
Impossible to compile in Release with the WinAppSDK Unpackaged target

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#16753]
### Current behavior

I get the following error with a brand new project or my current project:

C:\Users\USERNAME.nuget\packages\microsoft.windowsappsdk\1.5.240404000\buildTransitive\Microsoft.WindowsAppSDK.SelfContained.targets(36,9): error : The platform 'AnyCPU' is not supported for Self Contained mode.

### Expected behavior

It should compile as debug

### How to reproduce it (as minimally and precisely as possible)

1- Create new project
2- Select Release
3- F5 / Compile

### Works on UWP/WinUI

None

### Affected platforms

Windows (WinAppSDK)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. This has just been fixed in the 5.2.132 release. In general, you can also try reproducing issues by upgrading to the latest dev builds to see if it's fixed or not.

**Comment by ArchieCoder** [comment]
How to know the latest build version? It's not mentioned on GitHub.

**Comment by jeromelaban** [comment]
See in [this doc](https://platform.uno/docs/articles/upgrading-nuget-packages.html#projects-using-the-unosdk) on how to update the Uno.Sdk (don't forget to [upvote this issue](https://github.com/NuGet/Home/issues/13127)!)

**Comment by ArchieCoder** [comment]
For "big" Microsoft issue like this, I would not hold by breathe for a fix anytime soon.

What about a step in the compilation that checks once a day if a new SDK is available? It could modify global.json OR warn in the output.

**Comment by jeromelaban** [comment]
The nuget team has expressed direct interest in building this feature, so you can hold your breath a bit ;) Still, we're thinking about providing a top banner in VS to mention that there's an update in the uno.sdk.
