### ISSUE TITLE
[C# Markup] ColorPaletteOverride fails on linux

### ISSUE THREAD

**Issue by MarkWalls** [unoplatform/uno#16767]
### Current behavior

I have run UnoCheck and have 100% compliance on Linux Ubuntu 22.04.3 LTS 64 bit.
I ran the following code to create the project (Which was created by the Wizard):
```
dotnet new unoapp -o TestUno -preset "recommended" -markup "csharp" -platforms "android" -platforms "ios" -platforms "wasm" -platforms "windows" -platforms "desktop" -platforms "maccatalyst" -server  -theme-service  -ci "github" -media  -theme "material" -presentation "mvux" -config  -di  -log "serilog" -nav "regions" -http  -loc  -tests "ui" -tests "unit" -toolkit  -dsp  -id "com.testuno.TestUno" -pub "O=testuno"
```
When I tried to build the application I get this error (repeated 28 times for each of those overrides):
```
[{
	"resource": "/home/mark/git/TestUno/TestUno/Styles/ColorPaletteOverride.cs",
	"owner": "DocumentCompilerSemantic",
	"code": {
		"value": "CS0121",
		"target": {
			"$mid": 1,
			"path": "/query/roslyn.query",
			"scheme": "https",
			"authority": "msdn.microsoft.com",
			"query": "appId=roslyn&k=k(CS0121)"
		}
	},
	"severity": 8,
	"message": "The call is ambiguous between the following methods or properties: 'ResourceDictionaryBuilder.Add(ThemeResourceKey<Geometry>, string, string)' and 'ResourceDictionaryBuilder.Add(ThemeResourceKey<Brush>, string, string)'",
	"startLineNumber": 13,
	"startColumn": 6,
	"endLineNumber": 13,
	"endColumn": 9
}]
```

### Expected behavior

That the default application would work without errors with a default build created by the wizard.

### Workaround

If I comment out all of the Build.Add statements the project builds.

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### IDE

Visual Studio Code

**Comment by jeromelaban** [comment]
Thanks for the report! This is a casing issue that we missed in the DSP tooling. For now, you can uncheck the DSP option in the wizard and re-create a solution to get you further.

We'll be issuing a hotfix soon.
