### ISSUE TITLE
Skia Gtk TextBox selection (and insertion) problem

### ISSUE THREAD

**Issue by sarosigy** [unoplatform/uno#16788]
### Current behavior

The following TextBox (be aware of the font change from default) behaves badly at the later segments of texts.
```xaml
<TextBox FontSize="16" FontFamily="Noto Sans" TextWrapping="Wrap" AcceptsReturn="True" Width="400" Margin="5"/>
```
The following screenshot is doubleclicked on the word 'deserunt'.

![image](https://github.com/unoplatform/uno/assets/37872626/b8d50df9-d75e-4596-90e0-f99479846a3e)

The text when typing also inserted at wrong location, the later in the text the worse.

### Expected behavior

Skia Gtk TextBox should support to change the font from default.

### How to reproduce it (as minimally and precisely as possible)

Create a Skia Gtk project,
Insert the Multiline TextBox above (or a different one),
Be aware to **change** the default font of the TextBox
Insert a lengthy text and go to the end of the TextBox, observe the behavior

### Workaround

Use the default font.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

```csproj
    <PackageReference Include="Uno.WinUI" Version="5.2.132" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.2.132" />
    <PackageReference Include="Uno.WinUI.DevServer" Version="5.2.132" />
    <PackageReference Include="Uno.WinUI.Skia.Gtk" Version="5.2.132" />
```

### Affected platforms

Skia (Linux X11)

### IDE

Visual Studio Code

**Comment by Youssef1313** [comment]
Thanks for reporting this @sarosigy 

Can you please upload a repro? See [How to create a reproduction project (aka "repro")
](https://platform.uno/docs/articles/uno-howto-create-a-repro.html).

**Comment by sarosigy** [comment]
Here it is. Ignore the not-TextBox parts. The Skia.Gtk is up to date.

https://github.com/sarosigy/uno-lvtest

**Comment by Youssef1313** [comment]
Thanks. I'm attaching it as ZIP file to make sure it's not lost.

[uno-lvtest.zip](https://github.com/unoplatform/uno/files/15375929/uno-lvtest.zip)

**Comment by ramezgerges** [comment]
@sarosigy I can't reproduce this. Can you give us the exact text content of the textbox?
