### ISSUE TITLE
Uno.Samples link broken on "How-tos and tutorials"

### ISSUE THREAD

**Issue by axtens** [unoplatform/uno#16783]
### On which page?

https://platform.uno/docs/articles/tutorials-intro.html

### What's wrong?

In "Other examples" at the bottom of the page, clicking on
[Uno.Samples](https://platform.uno/docs/articles/uno-samples.md) goes to a 404 page.

**Comment by Youssef1313** [comment]
Thank you @axtens for noticing this. I think this is related to #16193 and https://github.com/unoplatform/Uno.Samples/pull/657 cc @agneszitte
