### ISSUE TITLE
[WASM] TextBox text selection behaves differently between WinUI and WASM

### ISSUE THREAD

**Issue by darenm** [unoplatform/uno#16780]
### Current behavior

In the circumstance where the text content of a TextBox is longer than can be displayed in a width constrained TextBox, using the mouse to select the text causes the text content to scroll on Desktop. This does not occur as expected in WASM. This occurs with a simple TextBox and a TextBox surrounded by a ScrollViewer. We are seeing this problem in a DataGrid, but this repro is simpler.

Desktop:
![TextBoxContentScrolling](https://github.com/unoplatform/uno/assets/1674843/92e3252d-aa87-4d4a-9eb0-ba211ff03709)

Web:
![TextBoxContentScrolling-web](https://github.com/unoplatform/uno/assets/1674843/4041ed17-621c-4955-a6c6-7b6cc1b5229d)

### Expected behavior

The WASM version behaves the same as the WinUI version.

### How to reproduce it (as minimally and precisely as possible)

Here's a playground link:

http://playground.platform.uno/#5ed47dfa

Here's the repro:

[UnoDatagridTextboxDragToSelect.zip](https://github.com/unoplatform/uno/files/15370150/UnoDatagridTextboxDragToSelect.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by MartinZikmund** [comment]
As @Youssef1313 investigated this, it seems that this behavior is currently not possible to influence from our side, as it is the built-in scrolling behavior of the browser. A workaround could be to keep the text entries wide enough so that the scrolling is not necessary, but apart from it seems very tricky to adjust.

**Comment by Youssef1313** [comment]
To clarify, the normal native behavior is actually that the text should scroll correctly. However, somehow this is not happening in our case. My first thought was that we are preventing the default behavior somewhere, so I went ahead and commented out all `preventDefault` usages in our code to see if it makes a difference, but still, we didn't get the desired native behavior.

It's likely something to fix on our side, but it's unclear to me why we are not getting the expected native behavior.

**Comment by MartinZikmund** [comment]
@darenm found the reason behind this, PR in progress

**Comment by darenm** [comment]
@MartinZikmund That's excellent news.

**Comment by darenm** [comment]
@jeromelaban can we back port this to 5.2?
