### ISSUE TITLE
Right click can cause an actual click if left button *was* pressed

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#16801]
### Current behavior

1. Open SamplesApp
2. Press with left mouse button anywhere outside samples list for example (DON'T release yet)
3. Move the mouse to samples list (DON'T release yet)
4. Right click (without releasing :))
5. An actual click happens
6. Now you can release 😄 

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
@Youssef1313 on which platform is this?

**Comment by Youssef1313** [comment]
Skia (Wpf at least). Haven't tested others

**Comment by jeromelaban** [comment]
@ramezgerges could you indicate some more on what is blocking to fix this issue?

**Comment by MartinZikmund** [comment]
The blocker is the following:

https://github.com/unoplatform/uno/pull/16893#issuecomment-2135711641

**Comment by Youssef1313** [comment]
It doesn't feel like a "blocker", but needs more investigation for the proper fix?
