### ISSUE TITLE
[Skia.X11] Multi-Touch support

### ISSUE THREAD

**Issue by lindexi** [unoplatform/uno#16804]
### What would you like to be added

Adding the multi-touch support to Uno.UI.Runtime.Skia.X11

### Why is this needed

See https://github.com/unoplatform/uno/issues/4309

### For which platform

Skia (Linux X11)

### Anything else we need to know?

We can use XI2 to get the touch event.

**Comment by lindexi** [comment]
I'm delighted to be involved in the development of this feature, and I'm also quite familiar with the touch and ink modules of X11.

**Comment by ramezgerges** [comment]
Thanks for your interest, @lindexi! This will probably need to follow #15799 which brings XI2 support in general.

**Comment by lindexi** [comment]
Thank you @ramezgerges . I reviewed your code and find it can easy to add the multi touch support.

**Comment by lindexi** [comment]
Reference https://github.com/unoplatform/uno/issues/17527

**Comment by ramezgerges** [comment]
Multi-touch should already be working with https://github.com/unoplatform/uno/pull/15799.
