### ISSUE TITLE
Pasting text that contains "Tab" doesn't render correctly in TextBox

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#16806]
### Current behavior

Just pasting any text that contains tabs results in something like this:

![image](https://github.com/unoplatform/uno/assets/31348972/70ea4a15-73c9-466d-bba7-b54ea463166e)

### Works on UWP/WinUI

None

**Comment by ramezgerges** [comment]
Note: this works correctly on Linux (at least on my Manjaro setup with the default Noto Sans)
