### ISSUE TITLE
DataGrid with MacOS / Skia has an issue when multiple click happens with SelectionMode=Single

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#16820]
### Current behavior

In the video, you will see multiple rows being gray out but after the mouse goes over the render fixes the bug

https://github.com/unoplatform/uno/assets/1608424/33c283df-9f0e-4877-b764-315f2269e714

### Expected behavior

One selected row at a time when SelectionMode=Single

### How to reproduce it (as minimally and precisely as possible)

Project will be sent

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.Sdk 5.2.132

### Affected platforms

Skia (macOS)

### IDE

Visual Studio Code

### IDE version

Latest VS Code

**Comment by ArchieCoder** [comment]
Project sent to @spouliot

**Comment by jeromelaban** [comment]
@ArchieCoder would you know if this happens on winappsdk as well?

**Comment by ArchieCoder** [comment]
@jeromelaban Works on winappsdk, desktop/skia and linux/skia

**Comment by spouliot** [comment]
Note that the `desktop` in `desktop/skia` means `windows`, `macos` and `linux (x11)` 😄 

`linux/skia` is a bit confusing as it could be `desktop/skia` (with X11) or the older Gtk/Skia running on Linux.

**Comment by ArchieCoder** [comment]
I just happen to see that the Skia magic is done by Microsoft. It means that any rendering skia related bugs need to go thru Microsoft .

![image](https://github.com/unoplatform/uno/assets/1608424/25afd43d-29e0-4f2f-819e-461c36b8e61e)

**Comment by jeromelaban** [comment]
@ArchieCoder that's indeed the case, though bugs in SkiaSharp/Skia are quite rare.

**Comment by agneszitte** [comment]
@jeromelaban, @spouliot not sure if it is related to https://github.com/unoplatform/uno/issues/16755#issuecomment-2125008222 in any way

**Comment by jeromelaban** [comment]
@agneszitte it's not.

**Comment by spouliot** [comment]
I can duplicate this on my Mac with `net80-desktop`.
Works fine on Win11 with `net80-desktop`, have not (yet) tried X11.
Investigating...

**Comment by spouliot** [comment]
Works fine with X11 too. This is definitively something in the Mac specific code.

The app logs shows `Touch/1` on macOS, while it mention `Mouse/1` on Windows and `Mouse/0` on X11.

```
05-22 11:35:01.285-04:00 I/Microsoft.UI.Xaml.UIElement: CommunityToolkit.WinUI.UI.Controls.Primitives.DataGridRowsPresenter: Cannot release pointer Touch/1: not captured by this control. 
```

So that's _probably_ an mouse event that is mis-categorized and the (DataGrid) control behave differently in that case.
