### ISSUE TITLE
DataGrid with MacOS / Skia has an issue with the scrollbar

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#16821]
### Current behavior

It's super hard to scroll the items of the DataGrid with MacOS / Skia only.

https://github.com/unoplatform/uno/assets/1608424/9b41d8fb-64ec-4300-bba7-62ab0b02f654

### Expected behavior

Normal scroll like the other platforms

### How to reproduce it (as minimally and precisely as possible)

Project will be sent

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Skia (macOS)

### IDE

Visual Studio Code

### IDE version

Latest VS Code

**Comment by ArchieCoder** [comment]
Project sent to @spouliot

**Comment by spouliot** [comment]
The same https://github.com/unoplatform/uno/pull/16840 also fix this... 

expect the scrollbar is pinkish ? while it's not on X11 and Windows (so I assume it's not something the app requested).

<img width="113" alt="Screenshot 2024-05-22 at 3 12 36 PM" src="https://github.com/unoplatform/uno/assets/260465/bf6a9e8b-803d-4bfb-a82d-a2c8bcc21d11">

**Comment by ArchieCoder** [comment]
First time seeing the scrollbar from the mac. Pink was not used in my code :)

**Comment by spouliot** [comment]
SampleApp's `ScrollViewer_Fluent` also seems to be more pinkish than the gtk version (with a beige background). It's also an inconsistent color (not all pixels are identical).

**Comment by spouliot** [comment]
I have opened a [different issue](https://github.com/unoplatform/uno/issues/16853) to track the pinkish color of the scrollbar.

**Comment by spouliot** [comment]
https://github.com/unoplatform/uno/pull/16887
