### ISSUE TITLE
The type Page was not found

### ISSUE THREAD

**Issue by drdec99** [unoplatform/uno#16828]
### What do you need help with?

My project suddenlly started doing this when I try to build or run

<img width="960" alt="PageNotPounf" src="https://github.com/unoplatform/uno/assets/6233336/428068d2-491d-49b5-a10f-c0783119645a">

**Comment by Youssef1313** [comment]
Thanks for reporting this @drdec99. Unfortunately, I don't think this is enough information to investigate further. Can you attach a [repro](https://platform.uno/docs/articles/uno-howto-create-a-repro.html) please?
