### ISSUE TITLE
dotnet new template has wront TargetFramework

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#16846]
### Current behavior

I've created a new uno-app like this:

`dotnet new unoapp -o MyApp --preset=recommended`

If I open the solution with visual Studio 2022 v17.10, choose WebAssembly (IIS) and hit F5, I get an error. "The value of the property 'TargetFrameworks' is inconsistent between the TargetFrameworks:

![image](https://github.com/unoplatform/uno/assets/1833242/306171c2-6a8d-42a3-b28b-fe2cc454659e)

It seems the value "net8.0" is wrong within the generated csproj:

```
<TargetFrameworks>
      net8.0-android;
      net8.0-ios;
      net8.0-maccatalyst;
      net8.0-windows10.0.19041;
      net8.0;
      net8.0-desktop;
      net8.0-browserwasm;
    </TargetFrameworks>
```

If I remove the net8.0-line, it works - but the generated MyApp.Tests.csproj fails.

### Expected behavior

The template should work without adjustments.

### How to reproduce it (as minimally and precisely as possible)

dotnet new unoapp -o MyApp --preset=recommended

Open in VS

Hit F5 and get the error.

### Workaround

Remove net8.0 and unload the test-project.

### Works on UWP/WinUI

No

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

5.2.132

### Affected platforms

Build tasks

### IDE

Visual Studio 2022

### IDE version

17.10.0

**Comment by jeromelaban** [comment]
Thanks for the report. We have a fix coming up for this today (5.3.139 or later).
