### ISSUE TITLE
[WASM] Can't build for WASM

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#16844]
### Current behavior

I migrated a Uno 5.1-app to Uno 5.2 (single project). It is working for Windows. But for WASM, I get the following exception:

```
1>f:\nuget\packages\uno.wasm.bootstrap\8.0.13\build\Uno.Wasm.Bootstrap.targets(213,3): error : System.Exception: Failed to run emscripten. More details are available in diagnostics logging mode or using the MSBuild /bl switch, see https://aka.platform.uno/msbuild-troubleshoot.
1>f:\nuget\packages\uno.wasm.bootstrap\8.0.13\build\Uno.Wasm.Bootstrap.targets(213,3): error :    bei Uno.Wasm.Bootstrap.ShellTask_v22722a164cfb242bfbdc2b10248f624fa32b28c2.RunPackager() in /_/src/Uno.Wasm.Bootstrap/ShellTask.cs:Zeile 768.
1>f:\nuget\packages\uno.wasm.bootstrap\8.0.13\build\Uno.Wasm.Bootstrap.targets(213,3): error :    bei Uno.Wasm.Bootstrap.ShellTask_v22722a164cfb242bfbdc2b10248f624fa32b28c2.Execute() in /_/src/Uno.Wasm.Bootstrap/ShellTask.cs:Zeile 271.
```

I've created a binlog and got that error right before:

![image](https://github.com/unoplatform/uno/assets/1833242/08e2b85b-6b42-4462-907b-9439a5e7cf55)

### Expected behavior

The WASM-app can be started without problems

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.2.132

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.10.0

**Comment by jeromelaban** [comment]
Thanks for the report.

This is likely not a direct change of 5.2, but likely another dependency (SetPendingApplicationException is not a method known to uno platform dependencies).

If you're able to create a repro, that would help. You can also use ILSpy to find where that method could come from, using the `bin` folder's contents.

**Comment by TopperDEL** [comment]
Oh! that was a nice hint! It comes from my own library called uplink.NET. It is not supported on WASM as it needs to PInvoke into a DLL that's not supported in the WASM-space.
I'm currently not (yet) calling into that dependency (I'm currently restructuring a lot), so this was not in my head. And it worked before I migrated from 5.1 to 5.2. So maybe there changed something with the way pinvokes get handled for WASM.

But then it's no problem of Uno. I need to find another way to use my library anyway, so this issue can be closed. Thank you!
