### ISSUE TITLE
[skia][macOS] Fluent's AcrylicBrush renders pinkish instead of grey on arm64

### ISSUE THREAD

**Issue by spouliot** [unoplatform/uno#16853]
### Current behavior

In some cases the macOS/Skia host will render scrollbar in a non-uniform pinkish color.

<img width="113" alt="Screenshot 2024-05-22 at 3 12 36 PM" src="https://github.com/unoplatform/uno/assets/260465/2f50b3c8-2928-4fe4-9d0f-468fd4af0c87">

### Expected behavior

It should be grey.

### How to reproduce it (as minimally and precisely as possible)

Run SampleApp's `ScrollViewer_Fluent` test and look at the scrollbar color.

### Workaround

None yet

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Skia (macOS)

### Anything else we need to know?

Found while fixing https://github.com/unoplatform/uno/issues/16821

**Comment by spouliot** [comment]
Enabling Fluent style inside SampleApp turns more elements pink

<img width="225" alt="Screenshot 2024-05-23 at 3 42 32 PM" src="https://github.com/unoplatform/uno/assets/260465/cd7a2a56-cf00-4391-89dc-1cfea3e76db1">

**Comment by MartinZikmund** [comment]
This feels like it could be acrylic brush related? @ahmed605 any chance something comes to mind?

**Comment by ahmed605** [comment]
Hmm seems like a wrong source is being sampled for the backdrop brush, I'm not sure where this pinkish source comes from tho

**Comment by jeromelaban** [comment]
@spouliot could it be arm64 specific?

**Comment by spouliot** [comment]
@jeromelaban maybe ? but I don't have any (at least working) x86_64 Mac to test that

**Comment by spouliot** [comment]
The rendering is correct if I switch to software rendering. IOW it happens only when using Metal.

**Comment by ahmed605** [comment]
Hm, it might be a bug in Skia's Metal renderer

**Comment by jeromelaban** [comment]
This does seem not happen on x64 (I tried [with this build](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=126359&view=artifacts&pathAsName=false&type=publishedArtifacts)):

![image](https://github.com/unoplatform/uno/assets/5839577/f47d720b-e37b-4147-9897-22a282059360)

**Comment by jeromelaban** [comment]
@Darsh0307 Unpacking the assets from `skia-generic-samples-app-WinUI` then run `dotnet dotnet SamplesApp.Skia.Generic.dll` is enough.

You may need to use `wget` with the url of the `skia-generic-samples-app-WinUI` artifact to get the file first, so work around the fact that the finder is flagging the file.

**Comment by spouliot** [comment]
<img width="697" alt="Screenshot 2024-05-27 at 11 30 56 AM" src="https://github.com/unoplatform/uno/assets/260465/f387d43d-b357-4bf5-9324-b7236ca99f39">

The acrylic brush does not seem to apply any opacity.

**Comment by spouliot** [comment]
Some of the `CompositionEffectBrush` results are also different.

![Screenshot 2024-05-27 at 1 27 22 PM](https://github.com/unoplatform/uno/assets/260465/292cfa8c-2550-47ea-ae0f-12d7e5b6039f)

GTK (software rendering) left
macOS right

**Comment by spouliot** [comment]
@ahmed605 k, thanks. I'll try to compare with X11/OpenGL... unless you have a better clue where the pink is coming from ?

I guessed there could be an incorrect (like RGBA<->ARGB) conversion somewhere that would mess the red channel, but I have not found any so far.

**Comment by ahmed605** [comment]
Apparently that pinkish color is the default color of `CAMetalLayer`, so for some reasons nothing is getting rendered on that layer so it shows its default color

This must be a Skia bug as it only happens on ARM64 but not x64

**Comment by spouliot** [comment]
> Apparently that pinkish color is the default color of CAMetalLayer, 

Ah, that rings a bell now!

The pinkish color is not uniform - so it seems the noise (png) is applied (might be on a different layer).

> This must be a Skia bug as it only happens on ARM64 but not x64

That's more and more likely. Still we need to distill a test case to open an issue.

**Comment by spouliot** [comment]
I've been trying to get Metal to show me any error (in Console.app or in code) without success. Some earlier operation(s) might be reseting the error :(

```
2024-05-27 17:08:25.706 dotnet[93443:36662072] drawInMTKView: status 2 LOG (
) ERROR (null)
```

where `2` is `MTLCommandBufferStatusCommitted`

**Comment by ArchieCoder** [comment]
FYI, after applying my trick to enable Fluent in ContentDialog, I get the pink color in the ComboBox droplist.

<img width="246" alt="Screenshot 2024-06-03 at 4 16 52 PM" src="https://github.com/unoplatform/uno/assets/1608424/d29ecc3c-84f4-4fc5-971d-aba0ae1ccb4f">

**Comment by spouliot** [comment]
@ArchieCoder yes, it comes from the AcrylicBrush used when Fluent is enabled (only on arm64 Macs). I'll update the issue title :)

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/blob/f2534bec256305bdb04d35cd397cd0d3c767abaa/src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowHost.cs#L148

https://github.com/unoplatform/uno/blob/f2534bec256305bdb04d35cd397cd0d3c767abaa/src/Uno.UI.Runtime.Skia.Gtk/Rendering/SoftwareRenderSurface.cs#L45-L53

https://github.com/unoplatform/uno/blob/f2534bec256305bdb04d35cd397cd0d3c767abaa/src/Uno.UI.Runtime.Skia.X11/X11SoftwareRenderer.cs#L42

https://github.com/unoplatform/uno/blob/f2534bec256305bdb04d35cd397cd0d3c767abaa/src/Uno.UI.Runtime.Skia.X11/X11OpenGLRenderer.cs#L81

To me, it's very unclear why these are all different. Maybe it's related?

**Comment by spouliot** [comment]
@ArchieCoder I just looked [1] at 5.2.161 does not have the fix. It was sadly released just before the workaround (for this issue) and my fix to set the app icon in the dock bar.

@jeromelaban can be produce a newer version of the 5.2 SDK ?

## [1] Steps

* Look up Uno.Sdk on nuget.com and pick your version -> https://www.nuget.org/packages/Uno.Sdk/5.2.161
* Click on "Open in NUGet Package Explorer" -> https://nuget.info/packages/Uno.Sdk/5.2.161
* Click on "View Metadata source" (up left corner)
* Look at the XML in the bottom/right corner and you'll see the repo and commit 

```xml
<repository type="git" url="https://github.com/unoplatform/uno" commit="08634c176fd4e30024fca847cc2baa8deb77bb3e" />
```

* Look at the release branch -> https://github.com/unoplatform/uno/commits/release/stable/5.2/ and find the commit used for the release
* Anything on top of that commit is not yet available in a package

**Comment by ArchieCoder** [comment]
@spouliot Thanks for the detailed info. I don't need an updated 5.2 version, but only needed a confirmation that the bug was fixed. With your information, I was able to find the latest dev version (5.4 and 5.3). In both versions, the pink bug transformed into a transparent bug.

Let me know if you need my app.

<img width="194" alt="image" src="https://github.com/unoplatform/uno/assets/1608424/cb4f1027-95c8-4c15-b2ca-2291e3c7d1ff">

**Comment by spouliot** [comment]
@ArchieCoder I still have the original version you sent me (if the bug appears there) but I did not notice the transparency issue. OTOH I'm not running with the workaround most of the time. I'll check back on this asap, thanks for the heads up!

**Comment by spouliot** [comment]
@ArchieCoder I can reproduce the new _transparency_ issue. However it happens with **and** without the workaround (it does not even execute the workaround code). 

So it's a different issue :( and maybe a regression (if that was fine before you updated). I'll open a separate issue for this one.
