### ISSUE TITLE
Request: Flyout stays open when rotating the screen

### ISSUE THREAD

**Issue by arianeleonard** [unoplatform/uno#16870]
### What would you like to be added

When a flyout is opened and the screen orientation changes (after rotating a device), the flyout stays open. It currently hides when rotating the screen.

Current behavior : 
[FlyoutDismissal.zip](https://github.com/unoplatform/uno/files/15437397/FlyoutDismissal.zip)

### Why is this needed

Important work in progress is lost when the flyout is closed.

### For which platform

Android, iOS

**Comment by jeromelaban** [comment]
@MartinZikmund does this look familiar?

**Comment by MartinZikmund** [comment]
Yes, this matches the WinUI behavior (closing light-dismissable UI when window size changes), which means it is something we cannot easily change. The recommendation is to use a `Popup` instead, or adjust the `Popup` that is created to back the `Flyout` to be non-lightdismissable. The code could look something like this:

```csharp
flyout.Opened += (s, e) =>
{
	var popup = VisualTreeHelper.GetOpenPopupsForXamlRoot(flyout.XamlRoot)[0];
	popup.IsLightDismissEnabled = false;
};
```

**Comment by arianeleonard** [comment]
Yes, this resolve the issue. Thank you!
