### ISSUE TITLE
[X11] The window flashes in Application Startup

### ISSUE THREAD

**Issue by lindexi** [unoplatform/uno#16881]
### Current behavior

The main window will flashes to Transparent and white (default window background) in Application Startup on X11 platform.

### Expected behavior

The main window can show the final background when Activated.

### How to reproduce it (as minimally and precisely as possible)

1. Create an empty UNO application
2. Running the application on X11 platform in Linux

### Works on UWP/WinUI

No

### NuGet package version(s)

```json
{
  // To update the version of Uno please update the version of the Uno.Sdk here. See https://aka.platform.uno/upgrade-uno-packages for more information.
  "msbuild-sdks":
   {
    "Uno.Sdk": "5.2.139"
  }
}

```

### Affected platforms

Skia (Linux X11)

### Anything else we need to know?

It can not fixed this issues by setting UseOpenGLOnX11 to false:

```csharp
FeatureConfiguration.Rendering.UseOpenGLOnX11 = false;
```

And I think the reason is the UNO create the X11 windows first and render delay. I add the `Console.WriteLine($"Create X11 Window {Stopwatch.GetTimestamp()} Frequency={Stopwatch.Frequency}");` in  `X11XamlRootHost.Initialize`. And then I add the code in `X11SoftwareRenderer.InvalidateRender` :

```csharp
			if (renderCount == 0)
			{
				Console.WriteLine($"First render {Stopwatch.GetTimestamp()}");
				renderCount++;
			}
```

Then I run the application and get the output : 

```
Create X11 Window  276775049460711 Frequency=1000000000
First render 276775252808388
```

It means that the interval between `Create X11 Window` and `First render` is (276775252808388-276775049460711)/1000000000*1000=203.35  milliseconds

**Comment by lindexi** [comment]
The other reason is that the `host.RootElement.XamlRoot!.Compositor.RenderRootVisual` will render some Transparent surface.

I add the code in `X11SoftwareRenderer.InvalidateRender`

```csharp
			var fileName = $"x{renderCount}.png";
			renderCount++;
			using (var skData = _bitmap.Encode(SKEncodedImageFormat.Png, 100))
			{
				var file = new FileInfo(fileName);
				using (var fileStream = file.OpenWrite())
				{
					fileStream.SetLength(0);
					skData.SaveTo(fileStream);
				}
			}
```

I run the application and get 4 image. And I find the first three images are transparent.

**Comment by ramezgerges** [comment]
@lindexi thanks for the wonderfully detailed issue!

This doesn't seem like an X11 problem. In fact, I just checked with the GTK target and it also has some "nothing" frames at the start. We can only render real frames ones the visual tree is layoutted and we can't really "rush" layoutting, so this leaves us with pretty much 2 choices:
* only open the window once the visual tree is layoutted (annoying but doable). This will add some latency between starting the application process and seeing the window pop up, but thee first frame will have stuff ready to go.
* keep the current behaviour. 

I would rather keep the time to the "first reaction" as low as possible. Even if the window has nothing, at least I know that something happened and it's only a split second before the application internally loads and shows something.

@jeromelaban @MartinZikmund thoughts?

**Comment by lindexi** [comment]
Thank you @ramezgerges . If given the opportunity, my preference would be for the first option. The current behavior may cause the user to perceive flashing windows, which can diminish the overall user experience. This could result in the app appearing less like a professional-grade product and more like a demo.

**Comment by jeromelaban** [comment]
We should still be rendering an empty surface,, using the default window color, even before anything has been layouted.

**Comment by lindexi** [comment]
> using the default window color

@jeromelaban As https://github.com/unoplatform/uno/issues/16897 says, now X11 platform will use the White color as window background. That will exacerbate the problem.

**Comment by lindexi** [comment]
And how can we solve the issue of flashes blinking when the app startup? Thank you.

The issue I am currently encountering is that my friends think the applications I develop with UNO as being too rudimentary, particularly due to the flickering startup problem, which makes the app more like a demo than a production.

But the good news is after I settings the window background to Transparent, as https://github.com/unoplatform/uno/issues/16897 says, this flicker issues was mitigated.

**Comment by MartinZikmund** [comment]
The color should match the current OS theme/root theme of the application. It seems this "flash" behavior is the same in WinUI currently:

```xml
<Window
    x:Class="App4.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="using:App4"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid x:Name="TestGrid" Background="Red"></Grid>
</Window>
```

```csharp
  public sealed partial class MainWindow : Window
  {
      public MainWindow()
      {
          this.InitializeComponent();
          TestGrid.Loading += TestGrid_Loading;
      }

      private async void TestGrid_Loading(FrameworkElement sender, object args)
      {
          Thread.Sleep(1000);
      }
}
```

When run, the background stays black for 1 second before it becomes red.

A way to avoid this should be to use a simple UI for a "splash screen" like UI - our toolkit includes `ExtendedSplashScreen` for this purpose.

@ramezgerges @jeromelaban on the other hand as long as the UI loads very fast, we should be able to display it without any flicker involved - e.g. the UI above without the `Thread.Sleep` will immediately show up with red background on WinUI.

**Comment by lindexi** [comment]
Thank you @MartinZikmund .  But I perceive a qualitative difference here. In WinUI, I suspect it doesn't render blank frames, whereas in UNO, there are instances of rendering blank frames. I believe rendering should not be carried out until the interface is ready. Rendering also consumes computational resources, and instead of wasting these resources, it would be better to allocate them to the logic of interface layout. 

Additionally, there's a hidden issue here, which is that the UI thread of UNO is not the UI thread of X11, hence there's a synchronization issue between these two threads.

**Comment by jeromelaban** [comment]
There's no notion of "blank" frame, just an empty visual tree to render. The fact that the UI thread is separate should not play a role either, as X11 is inherently multi-process.

We could add "native" support for the splash screen, which would limit the impact of that issue as there would show content even before there's any XAML being layouted. Still, one second is quite long and we should profile further to discover what's happening. 

Finally, Window.Activate is supposed to be handling this so some extents, where the window could appear only when the Loaded has been invoked.

**Comment by lindexi** [comment]
@jeromelaban Thank you. Is there a way for me to display(show) the window only after the layout is complete? I'm not care about the speed of the window display, but I do care about the visual effects of the application.

To add, a splash screen won't meet my needs because my application is designed not to require or allow a splash screen. I don't think all apps want to have splash screen.

**Comment by jeromelaban** [comment]
@lindexi [this line shows the window](https://github.com/unoplatform/uno.templates/blob/db4e5baea46e3a5e292f7a42c7c4047c6e1da0b2/src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.blank.cs#L97). If you move it to a `Loaded` handler of the window content, it should show only when the content has actually rendered.

**Comment by lindexi** [comment]
Thank you very much @jeromelaban

**Comment by lindexi** [comment]
@jeromelaban Sorry, it can not work after I move it to a `Loaded` handler of the window content.

My code is:

```csharp
    protected override void OnLaunched(LaunchActivatedEventArgs args)
    {
        MainWindow = new Window();
#if DEBUG
        MainWindow.EnableHotReload();
#endif


        // Do not repeat app initialization when the Window already has content,
        // just ensure that the window is active
        if (MainWindow.Content is not Frame rootFrame)
        {
            // Create a Frame to act as the navigation context and navigate to the first page
            rootFrame = new Frame();

            // Place the frame in the current Window
            MainWindow.Content = rootFrame;

            rootFrame.NavigationFailed += OnNavigationFailed;
        }

        if (rootFrame.Content == null)
        {
            // When the navigation stack isn't restored navigate to the first page,
            // configuring the new page by passing required information as a navigation
            // parameter
            rootFrame.Navigate(typeof(MainPage), args.Arguments);
        }

        MainWindow.SetWindowIcon();
        rootFrame.Loaded += (sender, eventArgs) =>
        {
            // Ensure the current window is active
            MainWindow.Activate();
        };
    }
```

You can find my code in https://github.com/lindexi/lindexi_gd/blob/02444de103c344f8ec0fc698ef20a1f715e1cc07/X11/UnoInk/UnoInk/App.xaml.cs#L21-L56

The behavior:

In WPF:

Nothing happend, the window will never show and the `rootFrame.Loaded` event will never rasied.

In X11:

It will show the Empty window, and the `rootFrame.Loaded` event will never rasied too. And the content of MainPage will never show.

Why the X11 can show the Empty window? Because X11 will call the XMapWindow in `X11XamlRootHost.Initialize` which will show the X11 window, see https://github.com/unoplatform/uno/blob/3c45797b34e5fa0dda4b5fe16ca14cc4c39deaea/src/Uno.UI.Runtime.Skia.X11/X11XamlRootHost.cs#L311-L345

**Comment by ramezgerges** [comment]
@lindexi I'm not sure why that didn't work on WPF, but for X11, I had to map the window earlier because we sometimes needed DPI info before `Activate` and we couldn't get any XRandR readings without first mapping the window.  We can probably work around that, but I'm not sure yet if it's worth complicating the code if the window lifecycle prevent this later-activation scenario from working anyway.

**Comment by lindexi** [comment]
Thank you @ramezgerges , it seems that I can not use the solution provided by @jeromelaban

**Comment by lindexi** [comment]
Thank you  @jeromelaban and @ramezgerges for your hard work.
