### ISSUE TITLE
The type [T] is not known by the MetadataProvider, either add the Bindable attribute or add it to the TypeMetadataConfig.xml

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1688]
## What would you like clarification on:

> "What does this error message mean? If a end user see this can they safely ignore it? What is the effect of this error message? What is the mitigation?"

## Concern?

- [x] Developing with Uno

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

## Anything else we need to know?

**Comment by tacoelho** [comment]
I´d like to try this one.

**Comment by ghuntley** [comment]
@tacoelho welcome to Uno :wave:. The change will involve improving the error message found over at https://github.com/unoplatform/uno/blob/master/src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs#L225 and potentially authoring some documentation.

@dr1rrb can provide specific insights as to what the error message means, the implications and what a user should do.

**Comment by tacoelho** [comment]
Hi @dr1rrb ! 

What types of metadata are allowed or they´re free to be defined by the user? What´s their purpose? If it´s defined by the user I understand that this message means that it wasn´t added and the error is thrown.  Could you please provide more details?

**Comment by jeromelaban** [comment]
This message is primarily a performance warning, which only happens in debug configuration.

It means that if you do not add the `[Bindable]` attribute on the mentioned type, reflection is going to be used instead. Reflection is pretty slow during lookups, and then invocations.

That being said, generic types cannot use that attribute, but this message is still displayed by the binding engine anyways. A possible solution would be to prevent this message to be displayed if the type is generic, and keep the others.

**Comment by tacoelho** [comment]
Thanks @jeromelaban I guess preventing the message to be displayed is the best way to go. I’ll work on that.

**Comment by dr1rrb** [comment]
Definitely agree that preventing the message when useless is the best solution, but we can still update the message to explain the effects (i.e. the performance hit due to the usage of the reflection).

**Comment by tacoelho** [comment]
Alright, I´ll do both. Thanks for the tips, @dr1rrb @jeromelaban

**Comment by davidjohnoliver** [comment]
Fixed by https://github.com/unoplatform/uno/pull/1711

**Comment by JochemPalmsens** [comment]
Thanks for the additional error info.
However, I'm missing how I can register types to the Metadataprovider when I'm unable to add the "Bindable" attribute. E.g. when the type is in an external package.
I would love to use the binding engine instead of reflection.
