### ISSUE TITLE
.NET 9 Preview 4: Fails to build fresh Wasm project

### ISSUE THREAD

**Issue by J05HM0N5TER** [unoplatform/uno#16892]
### Current behavior

When I create a new project (.NET 8 or 9) including the server, it fails to build the Wasm project. Seems that it has no effect on if you have the server in the project after further testing. Using the reccomended settings from https://new.platform.uno/

### Expected behavior

A fresh project builds as expected.

### How to reproduce it (as minimally and precisely as possible)

1. Create the app though: `dotnet new unoapp -o Test -preset "recommended" -tfm "net9.0" -server  -theme-service  -theme "material" -presentation "mvux" -config  -di  -log "default" -nav "regions" -http  -loc  -tests "none" -toolkit  -dsp  -id "com.companyname.Test" -pub "O=Test"` (which is the recommended, but with the server and .net 9, But I have tested it in .net 8 and it does the same thing).
2. `cd` into the `Test.Server` directory
3. Run `dotnet build`
4. It errors out. Error follows:
```log
Restore complete (0.8s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  Test.DataContracts succeeded (0.2s) → /home/user/Downloads/Test/Test.DataContracts/bin/Debug/net9.0/Test.DataContracts.dll
  Test net9.0-browserwasm failed with 1 error(s) (6.7s)
    /usr/share/dotnet/sdk/9.0.100-preview.4.24267.66/Sdks/Microsoft.NET.Sdk.StaticWebAssets/targets/Microsoft.NET.Sdk.StaticWebAssets.Compression.targets(280,5): error MSB4018: 
      The "ResolveCompressedAssets" task failed unexpectedly.
      System.InvalidOperationException: Fingerprint for '/home/user/Downloads/Test/Test/bin/Debug/net9.0-browserwasm/dist/favicon.ico' is not
       defined.
         at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.Validate()
         at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.FromTaskItem(ITaskItem item)
         at System.Linq.Enumerable.ArraySelectIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
         at System.Linq.Enumerable.ArraySelectIterator`2.ToArray()
         at Microsoft.AspNetCore.StaticWebAssets.Tasks.ResolveCompressedAssets.Execute()
         at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
         at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingCon
      text, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```
5. No working application

### Workaround

Downgrade .NET 9 preview to version 3, exact version I used is `9.0.100-preview.3.24204.13`

### Works on UWP/WinUI

None

### Environment

Uno.UI.DevServer / Uno.WinUI.DevServer

### Affected platforms

WebAssembly, Build tasks

### IDE

Visual Studio Code

### IDE version

1.89.1

### Anything else we need to know?

This is on `archlinux`, if that has any impact on this. If there is any further info that I should supply, please say. I was building wasm fine last week, but it appears that a NuGet package update broke it.

**Comment by jeromelaban** [comment]
@J05HM0N5TER thanks for the report. This may be a .NET 9 preview 4 issue. Can you try setting an SDK version in [your `global.json`](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json) to the last stable, such as 8.0.300, and see if it reproduces?

**Comment by J05HM0N5TER** [comment]
> @J05HM0N5TER thanks for the report. This may be a .NET 9 preview 4 issue. Can you try setting an SDK version in [your `global.json`](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json) to the last stable, such as 8.0.300, and see if it reproduces?

I just set it to `8.0.105`, so that my global.json now has:
```jsonc
{
  // To update the version of Uno please update the version of the Uno.Sdk here. See https://aka.platform.uno/upgrade-uno-packages for more information.
  "msbuild-sdks": {
    "Uno.Sdk": "5.3.0-dev.1451"
  },
  "sdk": {
    "version": "8.0.105"
  }
}
```
And it did build successfully. This is for the .NET 8 project, the .NET 9 version doesn't, due to it not being the correct version.

Here is the build output if it is useful:
```log
MSBuild version 17.8.5+b5265ef37 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Test -> /home/user/Downloads/Test/Test/bin/Debug/net8.0-browserwasm/Test.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:07.12
```

**Comment by jeromelaban** [comment]
Thanks. We'll be taking a look at the net9 preview issue, it's evolving quickly when getting closer to the release :)

**Comment by J05HM0N5TER** [comment]
Downgrading it did let it build successfully with .NET 9, I am now on `9.0.100-preview.3.24204.13`.

Here are the steps to downgrade it on Arch Linux, in case anybody else is looking for how to do so:
1. `git clone https://aur.archlinux.org/dotnet-preview-bin.git`
2. `cd dotnet-preview-bin`
3. `git checkout f7e158129f9c8675cc232a5751b705a6a7602603` (this was found though `git log`)
4. `make`
5. `make install`

I also had to run `sudo dotnet workload restore` for it to downgrade the workloads, so I could build it.

**Comment by jeromelaban** [comment]
Thanks for the update!

**Comment by jeromelaban** [comment]
Fixed by https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/855
