### ISSUE TITLE
Request: Flyout stays open when putting app in background

### ISSUE THREAD

**Issue by arianeleonard** [unoplatform/uno#16906]
### What would you like to be added

When a flyout is open and the app is put in the background and brought back to foreground, the flyout stays open if possible. It currently hides when the app is put in background.

Current behavior : 
[FlyoutDismissal.zip](https://github.com/unoplatform/uno/files/15474650/FlyoutDismissal.zip)

### Why is this needed

Important work in progress is lost when the flyout is closed.

### For which platform

Android, iOS

**Comment by jeromelaban** [comment]
Thanks for the report.

Popups don't close when the app is put in the background, afaik.

@MartinZikmund I recall that this behavior is dictated by the way WinUI works. Do we have a flag or another API that prevents that behavior?

**Comment by MartinZikmund** [comment]
Yes, this matches the WinUI behavior, which means it is something we cannot easily change. The recommendation is to use a `Popup` instead, or adjust the `Popup` that is created to back the `Flyout` to be non-lightdismissable. The code could look something like this:

```csharp
flyout.Opened += (s, e) =>
{
	var popup = VisualTreeHelper.GetOpenPopupsForXamlRoot(flyout.XamlRoot)[0];
	popup.IsLightDismissEnabled = false;
};
```
