### ISSUE TITLE
[skia] desktop TFM should set WinExe to hide the console

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#16905]
How am I supposed to hide this window?
![image](https://github.com/unoplatform/uno/assets/54866088/e4e1b7db-66b6-41c9-9900-41f561857af1)

_Originally posted by @kucint in https://github.com/unoplatform/uno/discussions/16898_

**Comment by jeromelaban** [comment]
@kucint This is a problem found in our Uno.Sdk, but you can work around this behavior by adding the following in your project:

```xml
    <OutputType Condition="'$(TargetFramework)'=='net8.0-desktop'">WinExe</OutputType>
```

immediately below the line of the same property.

**Comment by sbaum2s** [comment]
I am new to Uno and created a new Uno Platform App. Starting it as a Desktop Programm brings up an console window with something logged into it, closes it directly after and the App shuts down. No errors logged in the console but also i do not see a Program Window. I expected to see a normal blank Desktop window like from a WPF or Avalonia Template.

**Comment by jeromelaban** [comment]
@sbaum2s would you mind opening another issue for this and provide steps on what you're trying to do?
