### ISSUE TITLE
Indicate to add the built-in style when creating a dialog based on ContentDialog

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#16923]
### What would you like clarification on

If you create a dialog based on ContentDialog and you want the new Windows style for dialog, it's important to add the following line the the constructor:

Style = Application.Current.Resources["DefaultContentDialogStyle"] as Style;

Otherwise, you end up with a square dialog and square buttons at the bottom that don't match the app.

With the style
![image](https://github.com/unoplatform/uno/assets/1608424/ed8e04cb-5883-449c-a4fd-df1cdb46c21b)

Without the style =
![image](https://github.com/unoplatform/uno/assets/1608424/41d11c8a-9dcf-42db-88e6-c524de621d0e)

Page to modify is: https://platform.uno/docs/articles/features/dialogs.html

### Concern

Usage in industry

### Affected platforms

Skia (WPF), Skia (Linux X11), Skia (macOS), Windows (WinAppSDK)

**Comment by ArchieCoder** [comment]
I will do it later today.

**Comment by MartinZikmund** [comment]
@ArchieCoder This issue is also happening in case of WinUI correct?

**Comment by ArchieCoder** [comment]
@MartinZikmund Yes, with the Uno / WinAppSDK target.

**Comment by ArchieCoder** [comment]
@agneszitte I was not able to quickly rename the in-line commit message for each of your suggestion. It was easier to start from scratch.

New PR: https://github.com/unoplatform/uno/pull/16975

**Comment by agneszitte** [comment]
Thanks a lot again for your contribution, @ArchieCoder, really appreciated!
I have closed https://github.com/unoplatform/uno/pull/16936 in favor of https://github.com/unoplatform/uno/pull/16975 where I  pushed additional commits to fix markdown linting issues in additional some additional minor adjustments.

We will close this issue when the PR + backport PR are properly merged.
