### ISSUE TITLE
[WASM][Regression] Upgrading from 5.1 -> 5.2 completely breaks the .PointerEntered/.PointerExited handling

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#16928]
### Current behavior

I ran into an issue when upgrading my app from UNO 5.1 to UNO 5.2. It took me a while to realize that the .PointerEntered/.PointerExited is completely broken. 

I asked @TopProgrammer77 to create a simple repo (see attached): Please compare the .PointerEntered/.PointerExited events which are fired for Windows (and UNO 5.1) with UNO 5.2: UNO 5.2 is completely off as it fires events whenever the mouse pointer moves from the hosting 'control' to the hosted 'control' -> wrong.

[1.zip](https://github.com/unoplatform/uno/files/15488699/1.zip)

### Expected behavior

UNO 5.2 should not fall behind UNO 5.1 and should behave like WinUI.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by TopProgrammer77** [comment]
FYI, 
On WASM (5.2) - WRONG
![wasm](https://github.com/unoplatform/uno/assets/122166904/b6b21d5c-55e3-4503-b8fe-2f717a480ba3)

On Windows - Correct
![windows](https://github.com/unoplatform/uno/assets/122166904/1c401ccc-e855-421f-bed2-ac3cd7cea82e)

**Comment by dr1rrb** [comment]
On which browser did you test?

**Comment by DierkDroth** [comment]
This was Chrome

**Comment by DierkDroth** [comment]
@dr1rrb can you reproduce that regression?

Right now this prevents me from updating my app to 5.2 (or 5.3.dev for that matter)

**Comment by dr1rrb** [comment]
Yes I'm able to repro ... pointer exit on wasm is still annoying. Will investigate ...

**Comment by DierkDroth** [comment]
Thanks for looking into @dr1rrb.

I'd love to update to UNO 5.2.XX or 5.3.XX but am blocked by that issue...

**Comment by DierkDroth** [comment]
@francoistanguay @dr1rrb are there any plans to get this regression addressed any time soon? Wouldn't it be an option to just revert the change which broke UNO?

I'm bit a concerned that a clear regression does not appear to take priority by the UNO team...

**Comment by francoistanguay** [comment]
Yes, we will eventually fix it. Our years of collaboration should tell you that we rarely have regressions and we take them seriously. Clearly, for this specific issue, other things took priority.

Friendly reminder that, as you know, we have paid enterprise support to prioritize those types of issues.

**Comment by DierkDroth** [comment]
Thanks @francoistanguay 

As you may know I already 'paid' for getting many UNO issues fixed as I contracted @TopProgrammer77 to take care of quite a few of them. However, on this one I feel the UNO is best entitled to address it as it was introduced by the UNO team AFAIK.

**Comment by francoistanguay** [comment]
Agreed. It's in the backlog and the team been looking at it.

**Comment by DierkDroth** [comment]
@francoistanguay excellent, thanks.
FYI I just ran a quick report. [These PRs](https://github.com/unoplatform/uno/pulls?q=is%3Apr+author%3ATopProgrammer77) all had been contracted to @TopProgrammer77 by me. 

I'm looking forward the fix to test the improvements coming with the latest UNO updates.

**Comment by DierkDroth** [comment]
@dr1rrb thanks! You made my day!

Will this be available on 5.4-DEV only or also be backported to 5.3?

**Comment by francoistanguay** [comment]
We still have a lot of QA/Regression testing to do on many pointer-related issues so they will only be in 5.4 (if all goes well).

**Comment by DierkDroth** [comment]
Thanks for clarification @francoistanguay

**Comment by DierkDroth** [comment]
@francoistanguay @dr1rrb I just tested my app with latest 5.4-DEV und found that unfortunately there still are cases where the sequence of .PointerEntered and .PointerExited is not correct. In fact the original scenario - which was simplified by @TopProgrammer77 repo above - still is not working.

@francoistanguay are you aware that such cases still exist and that's what the team still is working on? I liked to understand before I invested potentially days trying to isolate in a repo for what the team already is aware of.

Thanks in advance

**Comment by dr1rrb** [comment]
Hey @DierkDroth I tried to run your sample (https://github.com/unoplatform/uno/files/15488699/1.zip) with latest version of uno:

```xml
<PackageVersion Include="Uno.WinUI" Version="5.4.0-dev.1532" />
<PackageVersion Include="Uno.WinUI.WebAssembly" Version="5.4.0-dev.1532" />
```

I see the same behavior between wasm and windows.

Could you provide more details about your issue?

**Comment by DierkDroth** [comment]
@dr1rrb after all it was easier to come up with a new repo that I have feared. Please see below and check out for the code in MainPage.xaml.cs.

Start the repo in Window (where you could please breakpoints to see that the **critical 'trace' lines are not triggered**) and press F12 to get the browser console for UNO WASM to see that the **critical 'trace' lines are triggered**.

[PointerEnteredExited.zip](https://github.com/user-attachments/files/16691243/PointerEnteredExited.zip)

**Comment by DierkDroth** [comment]
@dr1rrb can you reproduce the regression based  on my latest repo above?

Please let me know if the regression/repo is not clear or if you needed anything else from me. Thanks

**Comment by dr1rrb** [comment]
Hey @DierkDroth yes I'm able to repro, and also found a fix. It was not what I was expecting and took a bit longer, but it should be merged soon.

**Comment by DierkDroth** [comment]
Excellent! Thanks @dr1rrb

**Comment by DierkDroth** [comment]
@dr1rrb I just got around running some tests and found it's still not working - not even with the [PointerEnteredExited.zip](https://github.com/user-attachments/files/16691243/PointerEnteredExited.zip) repo from above

Please see the screenshot below for what I still experience in Chrome after updating the repo above to latest UNO 5.4  DEV
![image](https://github.com/user-attachments/assets/202e614a-2252-435f-91c1-de658932a317)
![image](https://github.com/user-attachments/assets/4593d3d1-e2af-420a-8f2f-a2f698d79436)

**Comment by dr1rrb** [comment]
@DierkDroth The minimal version is 1618. But it seems that we do have an issue with the CI (an iOS test step is failing) so we don't have any version that as been published yet.

**Comment by DierkDroth** [comment]
Thanks for clarification @dr1rrb.
