### ISSUE TITLE
Cannot generate WinUI package "The target "_GenerateAppxPackage" does not exist in the project."

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/uno#16935]
### Current behavior

Windows package generation does not work

### Expected behavior

Windows package generation works

### How to reproduce it (as minimally and precisely as possible)

```  XML
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <PackageCertificateThumbprint>B5B28DB76EE9A662DB7345D00510D039ABFE348E</PackageCertificateThumbprint>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <AppxSymbolPackageEnabled>True</AppxSymbolPackageEnabled>
    <GenerateTestArtifacts>True</GenerateTestArtifacts>
    <AppxBundle>Never</AppxBundle>
    <AppxBundlePlatforms>neutral</AppxBundlePlatforms>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
```

### Workaround

No

### Works on UWP/WinUI

No

### Environment

Other

### NuGet package version(s)

5.2.139

### Affected platforms

Windows (WinAppSDK)

### IDE

Visual Studio 2022

### IDE version

17.10.1

**Comment by agneszitte** [comment]
Hi @xperiandri did you already check the details in the documentation here https://platform.uno/docs/articles/uno-publishing-windows-packaged-signed.html ?
(More documentation is coming soon for the other platforms: https://github.com/unoplatform/uno/pull/16903)

**Comment by jeromelaban** [comment]
Thanks @agneszitte. @xperiandri, the command line is the preferred way to generated packages so far. If you can check the documentation above, let us know if this helps.

**Comment by xperiandri** [comment]
2-step build works. Thank you very much!
You just have a wrong second-step value
https://platform.uno/docs/articles/uno-publishing-windows-packaged-signed.html#considerations-for-solutions-with-class-library-projects

 as it has fewer parameters than
https://platform.uno/docs/articles/uno-publishing-windows-packaged-signed.html#package-signed-the-app

Also, the format of displaying is readable badly
![image](https://github.com/unoplatform/uno/assets/2365592/950950d4-69e7-4c7e-ad60-4c16e0f54fc0)

**Comment by xperiandri** [comment]
> thank you for your input! We'd love to help improve the documentation, but we need a bit more information to fully understand your concerns.

This comes from **Package signed the app**
`msbuild /r /p:TargetFramework=net8.0-windows10.0.19041 /p:Configuration=Release /p:Platform=x64 /p:GenerateAppxPackageOnBuild=true /p:AppxBundle=Never /p:UapAppxPackageBuildMode=Sideloading /p:AppxPackageDir="C:/temp/output/" /p:AppxPackageSigningEnabled=true`

This comes from **Considerations for solutions with class library projects**
`msbuild /p:TargetFramework=net8.0-windows10.0.19041 /p:Configuration=Release /p:Platform=x64 /p:PublishSignedPackage=true /p:AppxPackageDir="C:/temp/output/"`

The second option is incomplete and wrong. The only difference must be presence or absence of `/r` key

**Comment by xperiandri** [comment]
> Additionally, regarding the format display in the code snippet area, do you mean that it is difficult to view because you need to scroll to see the rest of the content?

Yes, scrolling is inconvinient
