### ISSUE TITLE
Differences from Avalonia

### ISSUE THREAD

**Issue by zeroonestring** [unoplatform/uno#17]
Differences from Avalonia

**Comment by jeromelaban** [comment]
I'll assuming you want a list of differences between Avalonia and Uno.

Here are a few:
- Uno uses the UWP API and XAML, whereas Avalonia uses a derivative of WPF
- Uno renders using the underlying platform, uses native controls whenever possible, particularly for input controls
- Uno supports WebAssembly, but not Linux and MacOS natively

The Avalonia people may have some more differences here:  https://github.com/AvaloniaUI/Avalonia/issues/1636

**Comment by danwalmsley** [comment]
From Avalonia side, we are all templated lookless controls, we are like a cross platform version of WPF.
We support Windows, Linux, Mac, IOS and Android. we do not support Webassembly (yet).

We do support embedding native controls, but that is very early stage work.

We have several backends for Direct2D, Skia, etc for rendering, and all our rendering is done ontop of these. So our UIs look identical on any platform its running.

**Comment by juepiezhongren** [comment]
ava's decision to not use mono is unwise

**Comment by jeromelaban** [comment]
@juepiezhongren not sure what you mean... android and iOS builds for Avalonia use Xamarin. Which platform are you talking about ?

**Comment by juepiezhongren** [comment]
sure？ it is said ava is run on core's runtime

**Comment by jeromelaban** [comment]
Yes, and CoreRT is not available on iOS and Android, so Xamarin/Mono is the only possible choice.

**Comment by carldebilly** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/587

**Comment by hossein-bakhtiari-revolut** [comment]
Now Avalonia Has WebAssembly as well
