### ISSUE TITLE
Using the `skia` XAML namespace should fail when target the SkiaSharp namespaces

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#17028]
Using `xmlns:skia=""` with any SkiaSharp namespace will cause the XAML node to be exluded on non-skia targets, causing hard-to-diagnose errors.

We should raise an error in that case and suggest a resolution, such as using another name.

**Comment by Youssef1313** [comment]
Also https://github.com/unoplatform/uno/issues/14004

**Comment by Youssef1313** [comment]
I feel like we could detect that the namespace is using `SkiaSharp` and *not* treat it as conditional XAML.

Generally, my opinion in conditional namespaces is that they shouldn't have been designed to rely on the namespace name. Instead, it should have been the namespace URI. That's a big of breaking change to take now though. But for this specific case if we detect SkiaSharp and treated it as non-conditional, I think it shouldn't be a big deal.

@jeromelaban @MartinZikmund Thoughts?

**Comment by jeromelaban** [comment]
That would also be an option. I agree that the namespaces should not have been relying on the name, but rather the URI, yet changing it would be too much of a breaking change for now.

Still, we could indeed not ignore the namespace if it's originally not in the `mc:ignorable` attribute and that it targets skiasharp namespaces.
