### ISSUE TITLE
Mute all not implemented messages and add Warnings in XAML for not implemented types uses

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#17025]
### What would you like to be added

All messages showing in the console that come from uno are generally not actionable, even though the uno packages-provided templates make use of not implemented features in XAML.

We should mute those messages down to debug level, and add a XAML generator set of warnings when explicit uses of not implemented types.

### Why is this needed

Make warnings actionable.

**Comment by Youssef1313** [comment]
We already have the UnoNotImplementedAnalyzer, so I wonder why it's not enough?

Is it not working as expected in some cases? Can we improve it?
