### ISSUE TITLE
[skia] ProgressRing does not work unless you resize the application

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#17041]
### Current behavior

See video: https://github.com/unoplatform/uno/assets/1608424/be040df4-7fc3-42a6-9bf2-2ea60c0f0f16

### Expected behavior

ProgressRing should turn as normal when IsActive=True

### How to reproduce it (as minimally and precisely as possible)

Just launch the app
[BindingBug.zip](https://github.com/user-attachments/files/15741972/BindingBug.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Regression with 5.3.0-dev.1873

### Affected platforms

Skia (WPF), Skia (macOS)

### IDE

Visual Studio 2022

### IDE version

Latest VS Code

**Comment by Youssef1313** [comment]
Thanks for reporting this @ArchieCoder. This will be fixed by #17059

**Comment by ArchieCoder** [comment]
@Youssef1313 thanks for the fast fix on this! Out of curiosity, was it caused by a recent change in SkiaCompositionSurface recently?

**Comment by Youssef1313** [comment]
I'm not sure when this started. It could be some unnecessary invalidation that was somewhere that got removed and revealed this bug.

**Comment by ArchieCoder** [comment]
@Youssef1313 what do I need to update to get your fix? I'm a bit confused about how things get updated and when. Thanks

**Comment by jeromelaban** [comment]
@ArchieCoder at this time, nothing, the build is not available yet. it will be available in the next 24h in uno.sdk 5.3-dev.xxx. The change in process is not documented yet, but it'll become clearer soon.
