### ISSUE TITLE
[Wasm][XF] The Switch renderer is not working

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#1706]
## Current behavior

The Switch control does not appear in the gallery:
https://xf-uno-wasm-staging.azurewebsites.net/

## Expected behavior

The Switch renderer is working properly.

## Environment

Nuget Package: 2.0-dev.x

Package Version(s):

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by BradChase2011** [comment]
Fyi on this, its a simple to fix as changing the style for the ToggleSwitch in Resources.xaml to use its base style:

<Style TargetType="ToggleSwitch" BasedOn="{StaticResource XamlDefaultToggleSwitch}">

**Comment by jeromelaban** [comment]
Fixed in latest.
