### ISSUE TITLE
Support for ListViewBase.ScrollIntoView (or ScrollToEnd)

### ISSUE THREAD

**Issue by mikeirvingweb** [unoplatform/uno#17089]
### Current behavior

Cannot currently scroll a list to any point programatically.

currently if I call `MessagesListView.ScrollIntoView(MessageList.Last());` then nothing happens

`Error: The member void ListViewBase.ScrollIntoView(object item) is not implemented. For more information, visit https://aka.platform.uno/notimplemented#m=Microsoft.UI.Xaml.Controls.ListViewBase.void%20ListViewBase.ScrollIntoView%28object%20item%29`

I ideally need to scroll the list to the end, to see the latest item in full, as in a chat message stream that has received new messages.

### Expected behavior

I can either scroll to a specific point, or in my case a `ScrollToEnd` would be fine / desirable.

I need this on all platforms, but more pressing are iOS, Android and Web Assembly.

### Affected platforms

WebAssembly, Android, iOS, Windows (WinAppSDK)

**Comment by mikeirvingweb** [comment]
ooh, I've not checked out that sample.. my reference project was the `ChatSignalR` project

I will check this out tomorrow. Thanks @agneszitte

**Comment by mikeirvingweb** [comment]
I have added in the `AutoScrollListViewBehavior` partial class.

Then called like this during my Page load.

```
AutoScrollListViewBehavior.SetAutoScroll(MessagesListView, true);
```

And things seem to work as I'd like right now 👌

Thanks for the tip @agneszitte 👍

**Comment by agneszitte** [comment]
> I have added in the `AutoScrollListViewBehavior` partial class.
> 
> Then called like this during my Page load.
> 
> ```
> AutoScrollListViewBehavior.SetAutoScroll(MessagesListView, true);
> ```
> 
> And things seem to work as I'd like right now 👌
> 
> Thanks for the tip @agneszitte 👍

Glad to hear it @mikeirvingweb. If you have additional feedback or comments let us know, thanks

**Comment by MartinZikmund** [comment]
`ScrollIntoView` should now be also implemented thanks to @Xiaoy312 on all targets
