### ISSUE TITLE
[X11] Performance issues about X11XamlRootHost.UpdateWindowPropertiesFromPackage

### ISSUE THREAD

**Issue by lindexi** [unoplatform/uno#17087]
### Your feedback

I find the performance issus from my demo application. I add some test code to UNO, see https://github.com/lindexi/uno/commit/59c036f79186c3634955d70a424c0b9b5ef9fb34 :

```csharp
		Console.WriteLine($"StartUpdateWindow {Environment.TickCount64} Thread={Environment.CurrentManagedThreadId}");
		UpdateWindowPropertiesFromPackage();
		Console.WriteLine($"EndUpdateWindow {Environment.TickCount64} Thread={Environment.CurrentManagedThreadId}");
```

And then I run the demo application with the special Uno assembly and find the Performance issues about `X11XamlRootHost.UpdateWindowPropertiesFromPackage`. Here is the console output text:

```
StartUpdateWindow   521364756 Thread=5
EndUpdateWindow     521364848 Thread=5
```

It means that the `X11XamlRootHost.UpdateWindowPropertiesFromPackage` cost  `521364848-521364756=92ms` on my test device.

After I remove the logo by `global::Windows.ApplicationModel.Package.Current.Logo = null;`, I find the X11 application start fast and the console output text is:

```
StartUpdateWindow 521764098 Thread=5
EndUpdateWindow   521764102 Thread=5
```

It means that the  `X11XamlRootHost.UpdateWindowPropertiesFromPackage` cost `521764102-521764098=4ms` on my test device.

**Comment by jeromelaban** [comment]
FYI, you can use [dotnet-trace](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace) to do this kind of profiling without comparing tick counts, then use [speedscope](https://www.speedscope.app/)https://www.[speedscope](https://www.speedscope.app/).app/ to analyze the results.

**Comment by lindexi** [comment]
@jeromelaban I maybe know the reason. See https://github.com/unoplatform/uno/blob/f2534bec256305bdb04d35cd397cd0d3c767abaa/src/Uno.UI.Runtime.Skia.X11/X11XamlRootHost.cs#L195-L250

**Comment by jeromelaban** [comment]
It's likely that processing this in a background task would be useful.

**Comment by ramezgerges** [comment]
I've tested this and it seems to only be a problem when using hi-res images. You should generally keep the size of the icon image small. Anyway, it should be fixed by https://github.com/unoplatform/uno/pull/17178.

**Comment by lindexi** [comment]
Thank you very much @ramezgerges
