### ISSUE TITLE
Native lottie animations may not be stopped properly on collected `AnimatedVisualPlayer`

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#17090]
### Current behavior

Errors may be showing up in the debugger log:

```
No UIElement found for htmlId "div#429266.uno-unarranged.uno-animatedvisualplayer.uno-frameworkelement.uno-uielement"
```

![image](https://github.com/unoplatform/uno/assets/5839577/4378cc13-d50f-4bf2-99dd-d80936141c5f)

This could indicate that the AnimatedVisualPlayer never stopped the DOM animations upon being collected.

### Expected behavior

Animations are removed from the DOM

### Works on UWP/WinUI

None

### NuGet package version(s)

5.2.103

### Affected platforms

WebAssembly

**Comment by darenm** [comment]
![NoUIElement](https://github.com/unoplatform/uno/assets/1674843/b7c7175c-703c-442e-8982-753040b3e5cf)
