### ISSUE TITLE
Add support for `AppWindow.Move` method

### ISSUE THREAD

**Issue by lindexi** [unoplatform/uno#17098]
### What would you like to be added

Add support for `AppWindow.Move` method

### Why is this needed

To move the window

### Anything else we need to know?

Reference https://github.com/unoplatform/uno/issues/8978

**Comment by MartinZikmund** [comment]
This feature is already in the works in https://github.com/unoplatform/uno/pull/16535, I will make sure to bring this in asap

**Comment by lindexi** [comment]
Thank you very much.

**Comment by lindexi** [comment]
Awesome ! Thank you @MartinZikmund
