### ISSUE TITLE
[WinAppSDK] Impossible to deploy with Packaged target

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#17140]
### Current behavior

I have this error when I deploy:

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		DEP0700: Registration of the app failed. [0x80080204] error 0xC00CE015: App manifest validation error: The app manifest must be valid as per schema: Line 17, Column 140, Reason: The attribute '{http://schemas.microsoft.com/appx/manifest/foundation/windows10}MaxVersionTested' on the element '{http://schemas.microsoft.com/appx/manifest/foundation/windows10}TargetDeviceFamily' is not defined in the DTD/Schema.	ElementsTechnician				

### Expected behavior

It should deploy

### How to reproduce it (as minimally and precisely as possible)

Even if I copy-paste as-is the Package.appxmanifest from a brand new project (which deploys), I still have the same error.

Please advise if I can send my project as-is.

### Works on UWP/WinUI

No

### IDE version

Latest VS

**Comment by jeromelaban** [comment]
Thanks for the report. This is an uno 5.3-dev issue, which was fixed 3 days ago. The latest uno.sdk should contain the fix.

**Comment by dansiegel** [comment]
If you set UnoResizetizerVersion to the latest dev build like the following it should fix your issue:

```xml
<PropertyGroup>
  <UnoResizetizerVersion>1.5.0-dev.106</UnoResizetizerVersion>
</PropertyGroup>
```

**Comment by ArchieCoder** [comment]
@dansiegel Confirmed, thanks.
