### ISSUE TITLE
Automatically deploy PR artifacts to a website so folks can click on a URL when reviewing the PR

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1717]
## What would you like to be added:

1. [x] Automatically build pull-requests
1. [ ] Create Azure Blob Storage
1. [ ] Create Azure DevOps deploy task
    1. [ ] Take pull-request # from GitHub and create blobstorage/$pullRequestId folder and replacing existing WASM content
    1. [ ] Take pull-request # from GitHub and create blobstorage/$pullRequestId folder and replacing existing APK content
    1. [ ] Take pull-request # from GitHub and create blobstorage/$pullRequestId folder and replacing existing ScreenShotTests (for each TFM) content
    1. [ ] [Set mime type for blobstorage/$pullRequestId for wasm to correct type](https://liftcodeplay.com/2017/11/28/how-to-fix-azure-storage-blob-content-types/).
1. [ ] [Automatically deploy pull-requests](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deploy-pull-request-builds?view=azure-devops)
1. [ ] [Comment on the pull-request with the URLs](https://marketplace.visualstudio.com/items?itemName=SOUTHWORKS.github-pr-comment)
1. [ ] Create Azure Workbooks task to delete any folders older than 90 days in the blob storage container

## Why is this needed:

Make reviewing pull-requests easier, improve productivity and quality.

## For which Platform:

- [ ] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

**Comment by MartinZikmund** [comment]
This is done now
