### ISSUE TITLE
[Wasm][XF] "System.TypeLoadException: Invalid generic instantiation

### ISSUE THREAD

**Issue by BradChase2011** [unoplatform/uno#1718]
# Current behavior

When running the Xamarin Forms target and using any styles in the forms XAML, it crashes on loading the main page.  On the IStyle.Apply and IStyle.Unapply, it crashes out with:

```
System.TypeLoadException: Invalid generic instantiation
mono.js:1   at Xamarin.Forms.Style.Xamarin.Forms.IStyle.Apply (Xamarin.Forms.BindableObject bindable) <0x65099b8 + 0x000a4> in <3d8d2930503a4b7ebc0cad8d466f1367>:0 
mono.js:1 TTT ERROR APP:  System.TypeLoadException: Invalid generic instantiation
mono.js:1   at Xamarin.Forms.Style.Xamarin.Forms.IStyle.Apply (Xamarin.Forms.BindableObject bindable) <0x65099b8 + 0x000a4> in <3d8d2930503a4b7ebc0cad8d466f1367>:0 
mono.js:1 fail: Windows.UI.Core.CoreDispatcher[0]
mono.js:1       Dispatcher unhandled exception
mono.js:1 System.TypeLoadException: Invalid generic instantiation
mono.js:1   at Xamarin.Forms.MasterDetailPage.On[T] () <0x732deb8 + 0x00014> in <3d8d2930503a4b7ebc0cad8d466f1367>:0 
mono.js:1   at Xamarin.Forms.Platform.UWP.PlatformConfigurationExtensions.OnThisPlatform[T] (T element) [0x00001] in C:\Xamarin.Forms\Xamarin.Forms.Platform.Uno\PlatformConfigurationExtensions.cs:8 
mono.js:1   at Xamarin.Forms.Platform.UWP.MasterDetailPageRenderer.UpdateMode () [0x00016] in C:\Xamarin.Forms\Xamarin.Forms.Platform.Uno\MasterDetailPageRenderer.cs:399 
mono.js:1   at Xamarin.Forms.Platform.UWP.MasterDetailPageRenderer.OnElementChanged (Xamarin.Forms.Platform.UWP.ElementChangedEventArgs`1[TElement] e) [0x000fa] in C:\Xamarin.Forms\Xamarin.Forms.Platform.Uno\MasterDetailPageRenderer.cs:172 
mono.js:1   C:\Xamarin.Forms\Xamarin.Forms.Platform.Uno\MasterDetailPageRenderer.cs:149 
mono.js:1   at Xamarin.Forms.Platform.UWP.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00029] in C:\Xamarin.Forms\Xamarin.Forms.Platform.Uno\Platform.cs:49 
mono.js:1   at Xamarin.Forms.Platform.UWP.RendererFactory.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00001] in C:\Xamarin.Forms\Xamarin.Forms.Platform.Uno\RendererFactory.cs:12 
mono.js:1   at Xamarin.Forms.Platform.UWP.VisualElementExtensions.GetOrCreateRenderer (Xamarin.Forms.VisualElement self) [0x00024] in C:\Xamarin.Forms\Xamarin.Forms.Platform.Uno\VisualElementExtensions.cs:17 
mono.js:1   at Xamarin.Forms.Platform.UWP.Platform.SetCurrent (Xamarin.Forms.Page newPage, System.Boolean popping, System.Action completedCallback) [0x000e1] in C:\Xamarin.Forms\Xamarin.Forms.Platform.Uno\Platform.cs:338 
mono.js:1   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
mono.js:1   at (wrapper delegate-invoke) <Module>.invoke_void_object(object)
mono.js:1   at Windows.UI.Core.CoreDispatcherSynchronizationContext+<>c__DisplayClass3_0.<Post>b__0 () [0x00000] in D:\a\1\s\src\Uno.UWP\UI\Core\CoreDispatcherSynchronizationContext.cs:25 
mono.js:1   at (wrapper delegate-invoke) <Module>.invoke_void()
mono.js:1   at Windows.UI.Core.CoreDispatcher.DispatchItems () [0x000fa] in D:\a\1\s\src\Uno.UWP\UI\Core\CoreDispatcher.cs:282 
```

This is in X.F code: 

```
void IStyle.Apply(BindableObject bindable)
{
...
ApplyCore(...);
}
```

I guess my question is, why would this happen on WASM but not on iOS/Droid/UWP/WPF/macOs (i run the same app on them all).  Is this a common issue that maybe I need to tell the linker to hold on to the Style class or is this an issue to solve in Forms?  Note that I have taken the code all the way down to the ApplyCore() call and it literally wont get to the first line inside of ApplyCore() (I put writeline's inside everywhere).  So some how it fails just calling the function but never entering the function.

If there is anything I can test or try to help this along, I would love to help.  Thanks much!

## Expected behavior

Be able to use styles in Forms.

## How to reproduce it (as minimally and precisely as possible)

Add a style and reference it in xaml.

## Environment

Nuget Package:
Current all the way up to building the repository from scratch and referencing directly.

Package Version(s):

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by BradChase2011** [comment]
@jeromelaban Just an fyi, I was able to get around it by adding the libraries into my linker config:

  <assembly fullname="Xamarin.Forms.Core" />
  <assembly fullname="Xamarin.Forms.Platform" />
  <assembly fullname="Xamarin.Forms.Platform.Uno" />
  <assembly fullname="Xamarin.Forms.Xaml" />

I realize we can probably just add the Xamarin.Forms.PlatformConfiguration.WindowsSpecific namespace which was causing the problem, but I didnt want to battle a bunch of others that might pop up.

**Comment by jeromelaban** [comment]
@BradChase2011 thanks for the update. 

This does help indeed, there's probably more to be done here as an application using those settings and built with AOT will be unnecessarily large. We'll keep track of that.

**Comment by jeromelaban** [comment]
If you were to be able to provide a very simple repro, it would help categorize as well. Thanks !
