### ISSUE TITLE
[X11] Add support for get the Uno's X11 window IntPtr

### ISSUE THREAD

**Issue by lindexi** [unoplatform/uno#17194]
### What would you like to be added

Add support for get the Uno's X11 window IntPtr

### Why is this needed

Now, we can use `GetNativeWindow` to get the Uno native window. But The `GetNativeWindow` will return the internal `Uno.WinUI.Runtime.Skia.X11.X11Window` type on X11 platform. And we can not easy to use it without reflection:

```csharp
#if HAS_UNO
        var x11Window = unoWindow.GetNativeWindow()!;
        var x11WindowType = x11Window.GetType();

        var x11WindowIntPtr =
            (IntPtr) x11WindowType.GetProperty("Window", BindingFlags.Instance | BindingFlags.Public)!.GetMethod!.Invoke(
                x11Window, null)!;
#else
```

You can find the above code in my demo: https://github.com/lindexi/lindexi_gd/tree/0f1d39d4f2bde2e60d790cb14302b5397ca0ae9c/UnoDemo/ChuchejairqaibalNallnowequyalgaw

### For which platform

Skia.X11

**Comment by ramezgerges** [comment]
@lindexi I'm curious, what use case do you have for this?

**Comment by lindexi** [comment]
Thank you @ramezgerges . I use it to set the owner window, and move the window now.

**Comment by jeromelaban** [comment]
@lindexi thanks. Do you need those two APIs because there are missing APIs in Uno?

**Comment by lindexi** [comment]
@jeromelaban Yeah, and I fire the issues here: https://github.com/unoplatform/uno/issues/17098

**Comment by lindexi** [comment]
Thank you @jeromelaban and @ramezgerges . And which version of UNO can I test?

**Comment by ramezgerges** [comment]
Uno.Sdk 5.4.0-dev.85 should work.

**Comment by lindexi** [comment]
Sorry @ramezgerges , I fail to get the X11NativeWindow from GetNativeWindow method. The GetNativeWindow will still return X11Window object.

The code will throw InvalidCastException:

```csharp
        try
        {
            var nativeWindow = (X11NativeWindow)MainWindow.GetNativeWindow();
            Console.WriteLine($"nativeWindow.WindowId={nativeWindow.WindowId:X}");
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
        }
```

The exception:

```
System.InvalidCastException: Unable to cast object of type 'Uno.WinUI.Runtime.Skia.X11.X11Window' to type 'Uno.UI.Runtime.Skia.X11NativeWindow'.
```

**Comment by ramezgerges** [comment]
@lindexi My bad, it's 5.4.0-dev.87 not 5.4.0-dev.85.

**Comment by lindexi** [comment]
Thank you @ramezgerges . And I can know the WindowId of X11 window by the code:

```csharp
            var nativeWindow = (X11NativeWindow)MainWindow.GetNativeWindow();
            Console.WriteLine($"nativeWindow.WindowId={nativeWindow.WindowId:X}");
```
