### ISSUE TITLE
[iOS] ProgressRing not visible when in ListView

### ISSUE THREAD

**Issue by pdecostervgls** [unoplatform/uno#1721]
## Current behavior

On iOS, the ProgressRing doesn't show when it is located within a ListView.

iOS | UWP
--- | ---
![image](https://user-images.githubusercontent.com/47024956/66198580-fcad1900-e69c-11e9-9b1f-560638b51ea8.png) | ![image](https://user-images.githubusercontent.com/47024956/66198932-d2a82680-e69d-11e9-925b-a54e77d200c4.png)

## Expected behavior

The ProgressRing gets shown when it is located in a ListView

## How to reproduce it (as minimally and precisely as possible)

```
    <StackPanel Background="{ThemeResource ApplicationPageBackgroundThemeBrush}" Padding="12">
        <TextBlock> in StackPanel</TextBlock>
        <StackPanel>
            <ProgressRing IsActive="True" Foreground="Red"/>
        </StackPanel>
        <TextBlock>ProgressRing in ListView</TextBlock>
        <ListView x:Name="testLv">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <StackPanel Orientation="Horizontal">
                        <TextBlock Text="{Binding}"/>
                        <ProgressRing IsActive="True" Foreground="Red"/>
                    </StackPanel>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    </StackPanel>
```
Don't forget to set the ItemSource in code-behind:
```
testLv.ItemsSource = new List<String> { "Alpha", "Beta", "Gamma", "Delta" };
```

## Environment

Nuget Package: 
Uno.UI: 2.0.269-dev.2966

Affected platform(s):
- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.3.2)
- [ ] for Mac (version: )

**Comment by ghuntley** [comment]
Potentially related https://github.com/unoplatform/uno/pull/1320

**Comment by carldebilly** [comment]
Just tried with latest version of Uno and it work... here's my XAML:

``` xml
<StackPanel Padding="12" Spacing="10">
	<TextBlock> in StackPanel</TextBlock>
	<StackPanel>
		<ProgressRing IsActive="True" Foreground="Red"/>
	</StackPanel>
	<TextBlock>ProgressRing in ListView</TextBlock>
	<ListView x:Name="testLv">
		<ListView.ItemTemplate>
			<DataTemplate>
				<StackPanel Orientation="Horizontal">
					<TextBlock Text="{Binding}"/>
					<ProgressRing IsActive="True" Foreground="Red"/>
				</StackPanel>
			</DataTemplate>
		</ListView.ItemTemplate>
		<ListView.Items>
			<ListViewItem>Alpha</ListViewItem>
			<ListViewItem>Beta</ListViewItem>
			<ListViewItem>Gamma</ListViewItem>
		</ListView.Items>
	</ListView>
</StackPanel>
```
Result on iOS:
![progressring-bugios](https://user-images.githubusercontent.com/4174207/84940423-cf2ec100-b0ad-11ea-8bad-543a9b372ebd.gif)

I'll close this issue as it's fixed.
