### ISSUE TITLE
SQLite Wasm update is needed

### ISSUE THREAD

**Issue by igiona** [unoplatform/uno#17217]
### Current behavior

Following 
- https://github.com/unoplatform/Uno.Samples/tree/master/UI/SQLiteSample
- https://github.com/unoplatform/uno/discussions/12926
- https://github.com/unoplatform/Uno.SQLitePCLRaw.Wasm?tab=readme-ov-file

I'm trying to implement SQLite support for my WASM application (works fine on iOS, Android and Windows).

Given that I wasn't able to find a UnoSdk.Sql or similar, I added the SQLite packages as follow:

```xml
  <ItemGroup Condition="'$(TargetFramework)'=='net8.0-browserwasm'">
    <PackageReference Include="Uno.sqlite-wasm" />
    <PackageReference Include="Uno.SQLitePCLRaw.provider.wasm" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" IncludeAssets="none" />
  </ItemGroup>
```
```
    <PackageVersion Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageVersion Include="Uno.SQLitePCLRaw.provider.wasm" Version="3.1.1" />
    <PackageVersion Include="SQLitePCLRaw.bundle_green" Version="2.1.8" />
    <PackageVersion Include="Uno.sqlite-wasm" Version="3.40.0.2" />
``` 

As soon as I try to instantiate a DBConnection (in my `OnLaunched`  event), 
```cs
var db = new SQLiteAsyncConnection(sqliteDbFilePath);
var tableInfo = db.GetTableInfoAsync(nameof(SqlLiteFeedingRecord)).GetAwaiter().GetResult()
```

I get a `System.TypeLoadException` with the the following message:

>'Could not load list of method overrides due to Method not found: int SQLitePCL.ISQLite3Provider.sqlite3_blob_open(SQLitePCL.sqlite3,SQLitePCL.utf8z,SQLitePCL.utf8z,SQLitePCL.utf8z,long,int,intptr&)'

I tried to configure `SQLitePCL` :
```
  try
  {
      SQLitePCL.Batteries_V2.Init();
  }
  catch (Exception ex)
  {
  }
```
and I get the same error message.

### Expected behavior

The DB Instance is created successfully.

It would be helpful to upgrade the SQLiteSample app to 5.2 single-project.

### Works on UWP/WinUI

Yes

### Environment

Other

### NuGet package version(s)

See above

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

Version 17.10.2

**Comment by jeromelaban** [comment]
Thanks for the report. 

The issue is not related to single project, but rather to a change in the SQLite dependencies.

We'll be fixing `Uno.SQLitePCLRaw.provider.wasm`, but in the meantime, you can add references to `SQLitePCLRaw.bundle_sqlite3` and `SQLitePCLRaw.provider.sqlite3` to their latest available versions.

The sample is updated by https://github.com/unoplatform/Uno.Samples/pull/761.
