### ISSUE TITLE
[Skia] `AutoSuggestBox` suggestions are unreadable

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#17222]
### Current behavior

When running the app via Skia Desktop, the `AutoSuggestBox` suggestions text is too dark/light to be readable (the issue is in both dark/light theme). It might be a background transparency issue? 
![image](https://github.com/unoplatform/uno/assets/78549750/212ce991-3b25-4510-8401-e7749d0dccd7)

### Expected behavior

![image](https://github.com/unoplatform/uno/assets/78549750/2c732f03-f324-4b67-98e5-429a98378ccb)

### How to reproduce it (as minimally and precisely as possible)

```xaml
    <AutoSuggestBox x:Name="autoSuggestBox"
                    Width="500"
                    Grid.Row="1"
                    PlaceholderText="Search"
                    TextChanged="AutoSuggestBox_TextChanged"
                    SuggestionChosen="AutoSuggestBox_SuggestionChosen" />
```

```csharp
    private List<string> suggestions = new List<string>
        {
            "Apple", "Banana", "Cherry", "Date", "Elderberry",
            "Fig", "Grape", "Honeydew", "Indian Fig", "Jackfruit"
        };

    private void AutoSuggestBox_TextChanged(AutoSuggestBox sender, AutoSuggestBoxTextChangedEventArgs args)
    {
        if (args.Reason == AutoSuggestionBoxTextChangeReason.UserInput)
        {
            var filteredSuggestions = suggestions.Where(item => item.StartsWith(sender.Text, StringComparison.InvariantCultureIgnoreCase)).ToList();
            sender.ItemsSource = filteredSuggestions.Count > 0 ? filteredSuggestions : new List<string> { "No suggestions found" };
        }
    }

    private void AutoSuggestBox_SuggestionChosen(AutoSuggestBox sender, AutoSuggestBoxSuggestionChosenEventArgs args)
    {
        sender.Text = args.SelectedItem.ToString();
    }
```

### Works on UWP/WinUI

Yes

### NuGet package version(s)

Uno.Sdk `5.3.0-dev.1916`

### Affected platforms

Skia (WPF), Skia (Linux X11), Skia (macOS), Skia (Linux Framebuffer), Skia (GTK)

**Comment by Youssef1313** [comment]
This may be the same issue that @Xiaoy312 is looking at.

**Comment by Xiaoy312** [comment]
@ramezgerges do you have any details on the issue to share?

**Comment by ramezgerges** [comment]
I've just started investigating now, but I've tested #17216 and it doesn't fix the problem, so it's a separate issue.

**Comment by Xiaoy312** [comment]
this is With or Without material?

**Comment by morning4coffe-dev** [comment]
@Xiaoy312 I have tested this without Material, with Fluent Recommended template.
