### ISSUE TITLE
[Android] touch events are not dispatched properly with transform

### ISSUE THREAD

**Issue by XiaotianNetlift** [unoplatform/uno#1724]
## I'm submitting a...
Bug report (I searched for similar issues and did not find one)

##  Current behavior
The origin control, where a press-hold-and-drag gesture begins, doesn't receive the `MotionEvent.ACTION_UP` or `MotionEvent.ACTION_CANCEL` event if that occurs on a region that doesn't have the same `Transform` property as the origin control along its visual tree.

## Expected behavior
The origin control, where a press-hold-and-drag gesture begins, should receive the "release"(`MotionEvent.ACTION_UP`) or the "cancel" event regardless of where that occurred.

## How to reproduce it (as minimally and precisely as possible)
[DroidMouseUpSample.zip](https://github.com/unoplatform/uno/files/3691662/DroidMouseUpSample.zip)
![mouse-up not found](https://user-images.githubusercontent.com/32882405/66228253-eeff8f80-e6ac-11e9-898d-37988ddc3f93.gif)

simplified xaml: // see attachment or comment below for full xaml
```
<Grid>
	<StackPanel>
		<StackPanel.RenderTransform>
				<!-- Essential for this bug --> 
			<TranslateTransform Y="0" />
		</StackPanel.RenderTransform>
		
		<controls:XButton Content="Press and drag" ... />
		<TextBlock Text="Hellow, world !" ... />
		<Button Content="Releasing here" ... />
		<TextBlock Text="or anywhere works" .../>
	</StackPanel>
	
	<Button Content="Releasing here and 'Up' event is lost" .../>
</Grid>
```

## Environment
```
Nuget Package: Uno.UI
Package Version(s): current
Affected platform(s): Android
Visual Studio: 2017
```

## Anything else we need to know?

**Comment by XiaotianNetlift** [comment]
Xaml:
```xaml
<Grid>
	<StackPanel Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
		<StackPanel.RenderTransform>
				<!-- Essential for this bug --> 
			<TranslateTransform Y="0" />
		</StackPanel.RenderTransform>
		
		<controls:XButton Content="Press and drag"
						Margin="20"
						FontSize="30"
						Height="50"
						Background="Red"
						HorizontalAlignment="Center" />
		<TextBlock Text="Hellow, world !"
				Margin="20"
				FontSize="30" />
		<Button Content="Releasing here" Background="Pink" Margin="30" Height="60" />
		<TextBlock Text="or anywhere works"
				Margin="20"
				FontSize="30" />
	</StackPanel>
	
	<Button VerticalAlignment="Bottom" Content="Releasing here and 'Up' event is lost" Background="Pink" Margin="30" Height="60" />
</Grid>
```

XButton.cs:
```cs
public partial class XButton : Button
{
#if __ANDROID__
	public override bool OnInterceptTouchEvent(MotionEvent e)
	{
		this.Content = e.Action.ToString();

		return base.OnInterceptTouchEvent(e);
	}

	public override bool OnTouchEvent(MotionEvent e)
	{
		this.Content = e.Action.ToString();

		return base.OnTouchEvent(e);
	}
#endif
}
```

**Comment by dr1rrb** [comment]
Please check with https://github.com/unoplatform/uno/pull/1256, it should be fixed.

**Comment by MatFillion** [comment]
Related issue : https://nventive.visualstudio.com/Umbrella/_workitems/edit/163128

**Comment by XiaotianNetlift** [comment]
Can confirm. It is fixed with #1256:
commit 5dbf8ea32e74672a6f05494a4a95d2d2d56a0e9c (HEAD -> feature/iosTouches, origin/feature/iosTouches)

**Comment by jeromelaban** [comment]
@dr1rrb related tounoplatform/uno#2091 ?

**Comment by dr1rrb** [comment]
Unfortunately, probably not. #2091 applies only to wasm for now.

**Comment by jeromelaban** [comment]
Oh. It was fixed in the branch feature/iosTouches branch, we can probably close it then.
