### ISSUE TITLE
Can not get the correct value of ActualWidth or ActualHeight after Loaded event on Desktop platform

### ISSUE THREAD

**Issue by lindexi** [unoplatform/uno#17243]
### Current behavior

We can not get ActualWidth or ActualHeight value after Loaded event on Desktop platform. It is different from WinUI's behavior.

```csharp
    public MainPage()
    {
        this.InitializeComponent();

        Loaded += MainPage_Loaded;
    }

    private void MainPage_Loaded(object sender, RoutedEventArgs e)
    {
        Debug.WriteLine($"Width={ActualWidth} Height={ActualHeight}");
    }
```

You can find the debug output `Width=0 Height=0` on Desktop platform, and `Width=1024 Height=720` on WinUI platform.

### Expected behavior

We can get the correct value of ActualWidth or ActualHeight after Loaded event on Desktop platform. The behavior is same as WinUI platform.

### How to reproduce it (as minimally and precisely as possible)

1. Create the empty UNO project.
2. Add the code in MainPage.xaml.cs:

```csharp
    public MainPage()
    {
        this.InitializeComponent();

        Loaded += MainPage_Loaded;
    }

    private void MainPage_Loaded(object sender, RoutedEventArgs e)
    {
        Debug.WriteLine($"Width={ActualWidth} Height={ActualHeight}");
    }
```

3. Run the program on Desktop platform and WinUI platform respectively.

And you can find the output in VisualStudio output window  is difference on Desktop platform and WinUI platform.

You can find my code in https://github.com/lindexi/lindexi_gd/blob/eb445bd456345de745e16e73c58f3e8f1fe48216/UnoDemo/DalekairwiJebonacaki/DalekairwiJebonacaki/MainPage.xaml.cs

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

global.json:

```json
{
  // To update the version of Uno please update the version of the Uno.Sdk here. See https://aka.platform.uno/upgrade-uno-packages for more information.
  "msbuild-sdks":
  {
    "Uno.Sdk": "5.2.161"
  }
}
```

### Affected platforms

Skia (WPF), Skia (Linux X11), Skia (macOS), Skia (Linux Framebuffer), Skia (GTK)

### IDE

Visual Studio 2022

### Anything else we need to know?

Reference : https://github.com/unoplatform/uno/issues/16120 and https://github.com/unoplatform/uno/issues/15982 and https://github.com/unoplatform/uno/issues/15841

**Comment by jeromelaban** [comment]
This behavior may have changed in latest uno.sdk previews.

**Comment by Youssef1313** [comment]
@lindexi Were you able to re-test this with the latest dev?

**Comment by Youssef1313** [comment]
Yes, but keep in mind if you're using Uno.Sdk, the SDK versioning is different from Uno.WinUI versioning. The latest SDK as of writing this comment is 5.4.0-dev.51 which is using Uno.WinUI 5.4.0-dev.464

**Comment by lindexi** [comment]
Thank you @jeromelaban and @Youssef1313 . The `5.4.0-dev.51` version Uno.Sdk fixes the behavior.

My test demo code: https://github.com/lindexi/lindexi_gd/tree/bf72c0981965bb4aed7f082ef81eed2e4b6d6913/UnoDemo/DalekairwiJebonacaki

**Comment by Youssef1313** [comment]
Thank you for confirming. Happy to know it's fixed now.
