### ISSUE TITLE
Duplicate nupkg tfms on projects with assets

### ISSUE THREAD

**Issue by ADD-David-Antolin** [unoplatform/uno#17242]
### Current behavior

When packing a Uno Library with assets, duplicate tfm are created for desktop and browserwasm inside the NuGet package. 

Using that package on an app project will result in the assets not being copied to the output directory for desktop and wasm (but it will copy for maccatalyst) and not being able to load those assets in execution.

### Expected behavior

When packing a Uno Library with assets, single tfm are created for desktop and browserwasm inside the NuGet package.

### How to reproduce it (as minimally and precisely as possible)

[UnoAssetsNugetIssue.zip](https://github.com/user-attachments/files/15911394/UnoAssetsNugetIssue.zip)

Open the attached solution.

Pack both UnoLibrary1 and UnoLibrary2 projects.

Open the .nupkg with NuGet Package Explorer.

Inside lib, UnoLibrary1 will have:
net8.0
net8.0-android34.0
net8.0-browserwasm8.0
net8.0-desktop8.0
net8.0-ios17.2
net8.0-maccatalyst17.2
net8.0-windows10.0.19041

Inside lib, UnoLibrary2 will have:
net8.0
net8.0-android34.0
net8.0-browserwasm
net8.0-browserwasm8.0
net8.0-desktop
net8.0-desktop8.0
net8.0-ios17.2
net8.0-maccatalyst17.2
net8.0-windows10.0.19041

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.2.161

### Affected platforms

WebAssembly, Skia (WPF), Skia (Linux X11), Skia (macOS), Skia (Linux Framebuffer)

### IDE

Visual Studio 2022

### IDE version

17.10.3

**Comment by Youssef1313** [comment]
I guess the `browserwasm` and `desktop` TFMs are intended for apps not library. @jeromelaban can you confirm?

**Comment by jeromelaban** [comment]
@Youssef1313 No, those tfms can also be used for libraries, assets should be handled properly.

**Comment by ADD-David-Antolin** [comment]
Tried Uno.Sdk 5.2.175 and it is still happening @jeromelaban.

![image](https://github.com/unoplatform/uno/assets/106523362/293174ad-96f4-43df-b47b-98fac8d6f8a7)

**Comment by ADD-David-Antolin** [comment]
@jeromelaban Tried with last published Uno.Sdk in NuGet (5.4.0-dev.55). Still happening:

![image](https://github.com/unoplatform/uno/assets/106523362/31008dfd-d9d2-4378-b2e8-9795833993a6)

**Comment by jeromelaban** [comment]
Indeed, it's still being built. It will be part of uno.sdk 5.4.0-dev.57 (when it [gets released on nuget](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=130648&view=logs&j=94442cc8-1cf2-5dd8-c1f8-62a13f219b71&t=8d49bcae-a79c-5f37-9cee-499df2f4b311)).

**Comment by ADD-David-Antolin** [comment]
Tried with 5.4.0-dev.57. 

![image](https://github.com/unoplatform/uno/assets/106523362/de5f18a1-6f36-414e-931c-cfb6afcf5b0c)

Seems to work (I have not tried to resolve the assets on another project but I think it makes sense that it will do).
Can we assume that this will be in 5.3? Also, we need a more precise ETA of 5.3 release.

**Comment by jeromelaban** [comment]
Yes, it will be in 5.3 and we do not have a precise ETA for 5.3, but it will be soon. There is no way to do the same for 5.2 at this time, it requires more changes that cannot be backported to 5.2.
