### ISSUE TITLE
Add a comment in csproj to facilitate when adding a package that is platform dependant

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#17259]
### Your feedback

For example, adding the nuget CommunityToolkit.WinUI.UI.Controls.DataGrid (or any from CommunityToolkit.WinUI), you need to add package in the csproj with conditions and also in Directory.Packages.props.

For a dev not familiar to this, it can be hard to find.

Feedback: quick fix for this is adding a comment in the csproj to remind a developer to modify the Directory.Packages.props. The csproj even contains comments.

Original discussion https://discord.com/channels/1182775715242967050/1182775715729526908/1253469148869165137

**Comment by ArchieCoder** [comment]
@agneszitte

**Comment by jeromelaban** [comment]
The documentation tells to do it though the csproj itself, but this can work also in the nuget package manager, which does the update by itself in both files.

**Comment by ArchieCoder** [comment]
@jeromelaban Right, adding via nuget does add it in the props file.
