### ISSUE TITLE
VisualState in a Border with CornerRadius original value as 0 fails to return to original state

### ISSUE THREAD

**Issue by iurycarlos** [unoplatform/uno#17264]
### Current behavior

When using VisualState in a Border with CornerRadius original value as 0, it fails to return to original state.

### Expected behavior

Visual state should be applied normally.

### How to reproduce it (as minimally and precisely as possible)
Using templates 5.2.41

dotnet new unoapp -o CornerRadiusVState -preset "recommended" -platforms "android" -platforms "maccatalyst" -platforms "wasm" -platforms "windows" -platforms "desktop" -platforms "ios" -theme-service False -vscode False -pwa False -theme "fluent" -presentation "mvvm" -config False -di False -log "none" -nav "blank" -http False -loc False -tests "none" -toolkit  -dsp False -id "com.companyname.CornerRadiusVState" -pub "O=CornerRadiusVState"

This is the project:

[CornerRadiusVState.zip](https://github.com/user-attachments/files/15928338/CornerRadiusVState.zip)

![visualstate_issue_test](https://github.com/unoplatform/uno/assets/6876973/111f858f-1f69-4a0f-a42e-e71c1e51f8cd)

### Workaround

If instead of zero, we use any other value, like 0.00001, it will work.

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
@iurycarlos Did you validate WinUI behavior?

**Comment by iurycarlos** [comment]
not yet. 
I just used uno templates 5.2.41 output.

**Comment by Youssef1313** [comment]
Good. Thanks for confirming.
