### ISSUE TITLE
You must have the exact version of the Windows SDK!

### ISSUE THREAD

**Issue by jojorne** [unoplatform/uno#17265]
I spent a week trying to figure out why, even with everything green in uno-check, I couldn't compile a single project. Installing and uninstalling Visual Studio several times.

Turns out there was a silent error with dotnet.  It crashed without giving an error, just a warning. This warning did not signal that the installation was half finished.

And there is this. I feel trapped, having to be forced to install another 1 GB of data (Windows 10 SDK, version 10.0.19041.0), old ones at that since I'm on Windows 11, just to make this work, just for something that uses SVG and PNG files to generate images. 😒

**Comment by jojorne** [comment]
> Thanks this is expected as `net8.0-windows` is not supported by the `uno.sdk`, only `net8.0-windows10.0.xxx` supported.
> 
> Could you provide a zip file of your project so we can determine what could be incorrect?

There's no need. I modified it just to see if it would stop asking for the SDK. I wasn't aware of .vsconfig before.

Everything is working fine.

**Comment by jeromelaban** [comment]
Thank you for the update. Feel free to open additional discussions if things are not obvious.

**Comment by jojorne** [comment]
I'm just gonna leave this here for posterity.

net8.0-windows***TargetPlatformVersion***
```
Valid TargetPlatformVersion versions for Windows:
10.0.22621.0
10.0.22000.0
10.0.20348.0
10.0.19041.0
10.0.18362.0
10.0.17763.0
10.0.22000.0
10.0.20348.0
10.0.19041.0
10.0.18362.0
10.0.17763.0
8.0
7.0

```
