### ISSUE TITLE
[Backdrop] check crashes with `NotImplementedException`

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/uno#17274]
### Current behavior

Using `Microsoft.UI.Composition.SystemBackdrops.DesktopAcrylicController.IsSupported()
or `Microsoft.UI.Composition.SystemBackdrops.MicaController.IsSupported()`
causes `NotImplementedException` to be thrown

### Expected behavior

Return `false`

### How to reproduce it (as minimally and precisely as possible)

Put
``` C#
if (Microsoft.UI.Composition.SystemBackdrops.DesktopAcrylicController.IsSupported())
{
    MainWindow.SystemBackdrop = new Microsoft.UI.Xaml.Media.DesktopAcrylicBackdrop();
}
```
or
``` C#
if (Microsoft.UI.Composition.SystemBackdrops.MicaController.IsSupported())
{
    MainWindow.SystemBackdrop = new Microsoft.UI.Xaml.Media.MicaController();
}
```
into `App.xaml.cs`

### Workaround

Use conditional compilation

### Works on UWP/WinUI

Yes

### NuGet package version(s)

5.2.161

### Affected platforms

WebAssembly, Android, iOS, Mac Catalyst, Skia (WPF), Skia (Linux X11), Skia (macOS), Skia (Linux Framebuffer), Skia (GTK)

### IDE version

17.10.3

**Comment by Darsh0307** [comment]
@MartinZikmund 

I tried with the latest 5.5 dev 

Uno.sdk/Uno.templates :- 5.5.0-dev.92

Now i am not getting the crahes when i am trying to debug with all the TFM (Wasm , Android , Dekstop , WinUI)

I am also attaching the zip file.
