### ISSUE TITLE
[Skia] Can not get the decode size of local image file from BitmapImage

### ISSUE THREAD

**Issue by lindexi** [unoplatform/uno#17285]
### Current behavior

After ImageOpened, I get the decode size from BitmapImage, and both the `DecodePixelWidth/Height` and `PixelWidth/Height` will be zero in Skia platform. And I can get the right size in WinUI platform.

### Expected behavior

We can get the decode size from BitmapImage after ImageOpened, which behavior is same as WinUI platform.

### How to reproduce it (as minimally and precisely as possible)

Repro code:

```csharp
    public MainPage()
    {
        this.InitializeComponent();

        var bitmapImage = new BitmapImage();
        var file = Path.GetFullPath("Image.jpg");
        bitmapImage.ImageOpened += (sender, args) =>
        {
            // Output zero in Skia
            // Output image size in WinUI
            System.Diagnostics.Debug.WriteLine($"DecodePixelWidth={bitmapImage.DecodePixelWidth} DecodePixelHeight={bitmapImage.DecodePixelHeight} PixelWidth={bitmapImage.PixelWidth} PixelHeight={bitmapImage.PixelHeight}");
        };
        bitmapImage.UriSource = new Uri(file);

        var image = new Image()
        {
            Source = bitmapImage,
        };
        image.Loaded += (sender, args) =>
        {
           // Both Skia and WinUI will output zero size
            System.Diagnostics.Debug.WriteLine($"ImageLoaded Width={bitmapImage.DecodePixelWidth} Height={bitmapImage.DecodePixelHeight}");
        };

        var border = new Border()
        {
            Width = 100,
            Height = 100,
            Child = image,
        };

        RootPanel.Children.Add(border);
    }
```

All my code in : 

- 5.1.80: https://github.com/lindexi/lindexi_gd/tree/e072a4c055a0101816ffa1e8ea913134db184b1e/NujawkeqefunuyeBogearfagallnuhea
- 5.2.161: https://github.com/lindexi/lindexi_gd/tree/9dbc88b944235648ea5c574f744d2917e9d01882/NujawkeqefunuyeBogearfagallnuhea

You can run my code on WinUI and Skia platform, and then you can find the difference debug output.

### Works on UWP/WinUI

None

### NuGet package version(s)

```json
{
  "msbuild-sdks": 
  {
    "Uno.Sdk": "5.1.80",
    "Microsoft.Build.NoTargets": "3.7.56"
  }
}
```

And

```json
{
  // To update the version of Uno please update the version of the Uno.Sdk here. See https://aka.platform.uno/upgrade-uno-packages for more information.
  "msbuild-sdks":
   {
    "Uno.Sdk": "5.2.161"
  }
}

```

### Affected platforms

Skia (WPF), Skia (Linux X11), Skia (macOS), Skia (Linux Framebuffer), Skia (GTK)

### Anything else we need to know?

See https://github.com/unoplatform/uno/discussions/15726

**Comment by Youssef1313** [comment]
NOTE: `PixelWidth` and `PixelHeight` properties in WinUI (WinAppSDK) has `IsPropMethodCall` flag, which basically means that it's sort of a "calculated" property.

Its implementation in WinUI is this:

```
    if (IsMetadataAvailable())
    {
        return m_imageMetadataView->GetImageMetadata()->width;
    }
    else
    {
        auto width = GetWidth();

        if (width != 0)
        {
            return width;
        }
        else
        {
            return m_retainedNaturalWidth;
        }
    }
```

We cannot yet do the exact same thing. But for sure we can get closer to the behavior and have the size set properly.

**Comment by lindexi** [comment]
Thank you very much @Youssef1313 !

**Comment by lindexi** [comment]
Good job. Problems are solved quickly!
