### ISSUE TITLE
`ResourceLoader` does not seem to handle file name-based `language` qualifier

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#17295]
### Current behavior

When `resw` files are differentiated by filename instead of folder structure:

![image](https://github.com/unoplatform/uno/assets/1075116/89287d9d-cb9a-4c51-9343-fab9981fa2b1)

It seems they are not correctly picked up by `ResourceLoader`

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
Closing in favor of https://github.com/unoplatform/uno/issues/18807 which has more information.
