### ISSUE TITLE
[Skia] `ComboBox` in `SettingsCard` renders incorrectly

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#17310]
### Current behavior

**Reproduces only on 5.3.x!!! Updating to latest dev causes https://github.com/unoplatform/uno/issues/17311 instead**

![image](https://github.com/unoplatform/uno/assets/1075116/cbb2b27f-c339-4a10-8f80-932c2a6477bb)

### Expected behavior

Should render normally

### How to reproduce it (as minimally and precisely as possible)

1. Checkout https://github.com/MartinZikmund/uno-bug-repros/tree/bug/combobox-in-wct-setting
2. Run the app on Skia Desktop

### Works on UWP/WinUI

None

**Comment by morning4coffe-dev** [comment]
Can this be related? https://github.com/unoplatform/uno/issues/17222

**Comment by morning4coffe-dev** [comment]
I can confirm this issue has indeed been fixed by https://github.com/unoplatform/uno/pull/17289 as it was also happening with other controls with Flyout. But now on the latest master all the contents disappear. I think we can close in favor of https://github.com/unoplatform/uno/issues/17311
