### ISSUE TITLE
[skia][macOS] ComboBox list background is transparent

### ISSUE THREAD

**Issue by spouliot** [unoplatform/uno#17317]
### Current behavior

ComboBox list background is transparent

https://github.com/unoplatform/uno/issues/16853#issuecomment-2187751705

### Expected behavior

ComboBox list background should **not** be transparent by default

### How to reproduce it (as minimally and precisely as possible)

SampleApp's ComboBox_Simple shows the issue

### Workaround

none

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

According to https://github.com/unoplatform/uno/issues/16853#issuecomment-2187751705 both 5.3 and 5.4 dev packages suffers from this issue.

### Affected platforms

Skia (macOS)

### Anything else we need to know?

I have not tried this (yet) on the X11 and WPF backends.

There's a few, recently opened issue, wrt ComboBox that could be related.

**Comment by spouliot** [comment]
The tip 7aac27cbd35ca463e2fc1d93762bc49f1f307057 of `release/stable/5.2` works fine (it's not transparent) and that includes the workaround for #16853.

IOW this issue is a regression (that was not backported to 5.2). I'll try to find the associated commit... c.c. @jeromelaban

**Comment by Youssef1313** [comment]
@spouliot This might be the same as https://github.com/unoplatform/uno/issues/17222

Can you try with the PR https://github.com/unoplatform/uno/pull/17289?

**Comment by spouliot** [comment]
@ArchieCoder I'm not sure which version(s) of 5.3 you used but the tip 05dbabf193fa974b26dd6ccf28dedf5521180283 of `release/stable/5.3` also works fine with me.

It does fail with `master` so it would be _normal_ for `5.4-dev` packages to have the issue.

@Youssef1313 thanks, I'll try this before trying anything else!

**Comment by spouliot** [comment]
@Youssef1313 yes, it works with PR #17289

**Comment by spouliot** [comment]
Fixed by, now merged, https://github.com/unoplatform/uno/pull/17289
