### ISSUE TITLE
[Gallery][Wasm][WCT - DataGrid] checkbox disappears in light mode and border doesn’t appear in dark mode

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno#17320]
### Current behavior

In WASM, when turning the light mode ON, checkbox in last column(Has been wanted) is not visible and wehn turning the dar mode, the border of the checkbox is not presnet.
<img width="754" alt="Screenshot 2024-06-26 at 2 55 23 PM" src="https://github.com/unoplatform/uno/assets/173818531/c02ee34c-0ce6-4151-b0ad-52d9f0da673f">

<img width="718" alt="Screenshot 2024-06-26 at 2 56 42 PM" src="https://github.com/unoplatform/uno/assets/173818531/e7a8f915-c539-4b2f-88c8-0030105502d9">

### Expected behavior

The checkbox should be visible with border in dark and light mode as shown in the snapshot below.
<img width="648" alt="Screenshot 2024-06-26 at 2 57 51 PM" src="https://github.com/unoplatform/uno/assets/173818531/fa9f4af5-d6c5-42d9-a515-7891b94b6f33">
<img width="646" alt="Screenshot 2024-06-26 at 2 58 32 PM" src="https://github.com/unoplatform/uno/assets/173818531/03f56753-9f21-438a-a2bb-430c740841b9">

### How to reproduce it (as minimally and precisely as possible)

Steps to reproduce:
1) Open wasm on windows in 'Edge'
2) Navigate to Menu 
3) Turn the toggle for 'Light Mode'
4) On Menu select click on 'Community Toolkit'
5) from 'Community Toolkit' select 'Datagrid' and check the behaviour of the data grid on right side of the window
6) Now again Navigate to Menu and turn the toggle ON for Dark Mode
7) follow steps 3 to 5 

### Works on UWP/WinUI

Yes

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
Thanks! This looks like a resource propagation issue, @Youssef1313 @kazo0 does it look familiar?

**Comment by jeromelaban** [comment]
This may be fixed by https://github.com/unoplatform/uno/pull/17647

**Comment by agneszitte** [comment]
> This may be fixed by #17647

@jhanvi03 if you can re-test with latest Gallery canary for this issue please

**Comment by jhanvi03** [comment]
Tested on MAc and winodows with Chrome and Edge browser. The check box does disappear in light mode and the border in dark mode.
![image](https://github.com/user-attachments/assets/a4cab364-b410-42a9-9ce4-8d96de1814cb)
![image](https://github.com/user-attachments/assets/51a0704a-5251-4a2d-b79f-abc924fb5c29)

**Comment by agneszitte** [comment]
> Tested on MAc and windows with Chrome and Edge browser. The check box does disappear in light mode and the border in dark mode.

@jhanvi03 just to make sure I correctly understand as I saw you completed the issue. The issue is properly fixed? You are not able to reproduce it at all?

**Comment by jhanvi03** [comment]
@agneszitte, Yes the issue seems to be fixed as i am not able to reproduce it.
