### ISSUE TITLE
[droid/WASM] DatePicker strange flyout

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#1735]
## Current behavior

`  <AppBarButton x:Uid="resDay" Label="Kalendarz" Icon="Calendar" Name="uiKalend">`
`           <AppBarButton.Flyout>`
`                       <Flyout >`
`                            <DatePicker Name="uiDay" DateChanged="uiDayAndro_Changed" />`
`                      </Flyout>`
`         </AppBarButton.Flyout>`
`    </AppBarButton>`

On tapping, displays this (WASM head)
![anniv-wasm-datepicker](https://user-images.githubusercontent.com/23451507/66274513-e01d0680-e87f-11e9-8aeb-da2dde35820e.png)
(similar is on Android)

 On Android, tapping this leads to 'normal' calendar, on WASM - not (but it can be slow PC, or something like that).

## Expected behavior
 Should display something similar to CalendarDatePicker (date with button), or date - but only once, and without time.

## How to reproduce it (as minimally and precisely as possible)
See above.

## Environment

Nuget Package:
2.0.274-dev.2985

Package Version(s):

Affected platform(s):
- [ ] iOS
- [X] Android
- [X] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [X] 2019 (version: 16.3.2)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
This issue is not relevant anymore since the DatePicker has been implemented
