### ISSUE TITLE
Uno Target Framework Error - net8.0-ios.

### ISSUE THREAD

**Issue by ward-horsfall** [unoplatform/uno#17402]
### Current behavior

Hi,

When using the Uno Target Framework I have a lot of trouble selecting the net8.0-ios framework when creating a UNO platform app.

Here are my version:

UNO Platform 5.2.56.70
Visual Studio 2022 - 17.10.3

Here are the steps I do.

1. Create a Uno Platform App (Accept all defaults for .NET 8.0) and let the template wizard complete.
2. Then I pair to Mac - it completes without error.
3. The target selector says: UnoApp79 (WinAppSDK Packaged)
4. I then try to change framework to net8.0-ios (see graphic)
5. The selector seems to have problems changing and seems to not get there and stick on
   UnoApp79 (WebAssembly).

Sometimes I can get it there if I try multiple attempts.

So my question is how to resolve this? Are there anything wrong with the steps I am doing

Thanks

Ward.

### Expected behavior

net8.0-ios framework selected

### Works on UWP/WinUI

None

### IDE

Visual Studio 2022

### Relevant plugins

UNO Platform 5.2.56.70
![Selector_Error](https://github.com/unoplatform/uno/assets/12206371/8b854272-2699-455a-885b-9b1a8ff55504)

**Comment by jeromelaban** [comment]
Thanks for the report. We've been tracking a similar behavior, but in the meantime, could you try closing the solution, delete the `*.csproj.user` file in the folder, and try loading the project again?

Also, could you provide the contents of the `Uno Platform` output window?

**Comment by ward-horsfall** [comment]
Hi jeromelaban,

Thanks for your help. I tried deleting the *.csproj.user file however the result was the same.

I have attached the log file for you to look at,

Thanks
Ward

[Build_output-UnoApp81.txt](https://github.com/user-attachments/files/16142134/Build_output-UnoApp81.txt)

**Comment by jeromelaban** [comment]
Thanks for the logs, this helps.

It feels like visual studio is trying to force the webassembly profile without Uno explicitly asking for it.

Let's try two things. 
- Could you try and upgrade the Uno.Sdk to the latest prerelease ? Update the global.json uno.sdk version to `5.4.0-dev.85`, then reload your solution, then try again to see if it helps.
- Could you try opening the `launchSettings.json` file and remove the `UnoApp81 (WinAppSDK Packaged)` entry?

**Comment by ward-horsfall** [comment]
Hi jeromelaban,

Thanks for that I will give it a try and get back with the results.

Can you clarify how I do the following part: "Could you try and upgrade the Uno.Sdk to the latest prerelease"

Then I can do the other parts and get back with the results.

Thanks

Ward

**Comment by jeromelaban** [comment]
> Can you clarify how I do the following part: "Could you try and upgrade the Uno.Sdk to the latest prerelease"

Exactly as the rest of the point above, by modifying the `global.json`. You can find [additional information here](https://platform.uno/docs/articles/upgrading-nuget-packages.html#projects-using-the-unosdk).

**Comment by jeromelaban** [comment]
Thanks for the update. We're made changes very recently, and depending on the version you tried, this may have been fixed already. Which version did you update to?

**Comment by ward-horsfall** [comment]
Hi @jeromelaban and others,

Thanks for all the great work - looks like it is all good on my end.

Thanks again,

Ward

**Comment by jeromelaban** [comment]
Thanks for the update. For the related PR, it may have been fixed in https://github.com/unoplatform/uno/pull/17542.
