### ISSUE TITLE
Visual Studio projects in solution can be a negative value

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#17475]
### Current behavior

After creating a new Uno project with VS 17.10.4 (or 17.10.3) the number of projects in the solution can go to negative values. 

![image](https://github.com/unoplatform/uno/assets/78549750/69178f5e-106f-40a0-b834-c5c660c8924c)

### How to reproduce it (as minimally and precisely as possible)

My repro: 
1. Create a new app with latest templates (Wizzard)
2. Add some dependency (in my case Mindscape.Raygun4Net.NetCore)
3. Run the project
4. Remove the dependency and run again
5. See the project number

Erik Lima's repro:
1. Create a new uno app
2. Change the target from Windows to something else like Desktop
3. Observe the number (Project number) will change
4. The more you change targets/platforms to launch more the number will change

### Workaround

Unloading the project worked in my case. Restarting VS should help.

### Works on UWP/WinUI

None

### IDE

Visual Studio 2022

### IDE version

17.10.3 or 17.10.4

**Comment by agneszitte** [comment]
@morning4coffe-dev can you add some screenshots you shared earlier in the description please.
@jeromelaban maybe you can share if other details could be helpful please.

**Comment by jeromelaban** [comment]
I do not have other details, we do not control this part of visual studio unfortunately. This is still likely related to the reloading of projects, but without a reliable repro, this will be difficult to fix.

**Comment by ArchieCoder** [comment]
Please upvote https://developercommunity.visualstudio.com/t/Number-of-projects-in-a-solution-can-hav/10702191

@jeromelaban just using a blank new Uno Platform project does the trick
