### ISSUE TITLE
[VS] Single project - doesn't build after updating Uno.Sdk

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#17495]
### Current behavior

When using VS and updating the Uno.Sdk in global.json, the project throws errors when trying to build project. It needs to be rebuilt multiple times to take effect and build the project again. This can be quite a papercut for new users when updating their projects to the latest versions.

### Expected behavior

VS should download the desired package version and build the project on the first try.

### How to reproduce it (as minimally and precisely as possible)

1. Open VS
2. Create a new Uno project with Single Project solution
3. Update the Uno.Sdk version
4. Try to build and deploy the project

### Works on UWP/WinUI

None

### IDE

Visual Studio 2022

### IDE version

17.10.4

**Comment by jeromelaban** [comment]
@morning4coffe-dev this is a known issue, it is documented that reloading the solution is required. https://platform.uno/docs/articles/features/using-the-uno-sdk.html?tabs=uno-packages#uno-platform-features

**Comment by jeromelaban** [comment]
We could still try to detect version changes in the global.json and force a project reload.

**Comment by morning4coffe-dev** [comment]
@jeromelaban Ah, the mention in the documentation is nice, but if there is a way to detect the changes would be better 👍

**Comment by jeromelaban** [comment]
Reloading the project does not help, VS is still caching the SDK version in multiple places.

**Comment by jeromelaban** [comment]
It's possible to reload VS in place, though, and this banner will do it:

![Image](https://github.com/user-attachments/assets/d46b320a-ad63-4bc1-905d-e839f9574f9d)
