### ISSUE TITLE
https://aka.platform.uno/UNOB0013 is missing

### ISSUE THREAD

**Issue by IsmailHassani** [unoplatform/uno#17508]
### Current behavior

warning UNOB0013: The net8.0 TargetFramework must not be placed first in the TargetFrameworks property in order for other platforms debugging to work. (See https://aka.platform.uno/UNOB0013)

SDK version: 5.4.0-dev.117

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
Thanks, this is expected, as the docs are not published yet for this version.
