### ISSUE TITLE
`ListView.CanReorderItems` is not identified objects inherited from `ObservableCollection`

### ISSUE THREAD

**Issue by balbarak** [unoplatform/uno#17517]
### Current behavior

ListView with `CanReorderItems=true` does not sort objects inherited from `ObservableCollection<>`

### Expected behavior

It should sort object that inherited from `ObservableCollection<>`

### Works on UWP/WinUI

None

### Affected platforms

Android, iOS

### IDE

Visual Studio 2022

### Anything else we need to know?

I think I found the problem in file
`ListViewBase.DragDrop.cs`

special this method

``` chsarp
private static bool IsObservableCollection(object src)
	=> src.GetType() is { IsGenericType: true } srcType
		&& srcType.GetGenericTypeDefinition() == typeof(ObservableCollection<>);
```

where checks is there

```
case IList list when IsObservableCollection(list):
				// The UWP ListView seems to automatically push back changes only if the ItemsSource inherits from ObservableCollection
				// Note: UWP does not use the Move method on ObservableCollection!
				ProcessMove(
					list.Count,
					list.IndexOf,
					(oldIndex, newIndex) => DoMove(list, oldIndex, newIndex));
				break;
```

**Comment by ramezgerges** [comment]
Hey @ballbarak, can we get a clear repro? I've tested some samples locally and things look to be working.

**Comment by balbarak** [comment]
Hello @ramezgerges ,

Try to create a class that inherit from `ObservableCollection` for example

```
public class TestCollection : ObservableCollection<Employee>
{

}
```

and bind this class to `ItemsSource` property for `ListView` and try drag and drop for sort like below
```
<ListView
    AllowDrop="True"
    CanDragItems="True"
    CanReorderItems="True"
    ItemsSource="{x:Bind Items, Mode=OneWay}"
    ReorderMode="Enabled"/>
```
