### ISSUE TITLE
VS: When WinUI target is not physically listed first, XAML intellisense is not working properly

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#17530]
### Current behavior

When a blank Uno app is created, IntelliSense for built-in resources, etc. is not working. that is even if one selects `net8.0-windowsxyz` as target in the top left dropdown. However, when the windows target is put first in order explicitly in the `.csproj`, it starts working correctly:

![image](https://github.com/unoplatform/uno.templates/assets/1075116/78bd24fa-8006-4357-9a10-e1a07a864fe6)

### Expected behavior

Should work out of the box

### Template Host

Visual Studio

### Host OS

Windows

### Template Options

Latest stable

### Template Version

```shell
Latest stable
```

**Comment by dansiegel** [comment]
Transferring this to the Uno repo as the issue you're reporting would be coming from the SDK not from the templates.
