### ISSUE TITLE
[Calculator][MacOS] Key remains highlighted after Click.

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno#17546]
### Current behavior

When the user presses any numbers/operators it remains highlighted. even after deleting the history it remains highlighted 

https://github.com/user-attachments/assets/3bcdeabc-b8f1-4cbe-9343-3e2db7eb7196

### Expected behavior

When the user presses/clicks any numbers/operators after the click it should not remain highlighted.

### How to reproduce it (as minimally and precisely as possible)

Steps to reproduce:

1. Install and open UNO Calculator form testFlight
2. Perform any calculation 
3. Observe the key on calculator.

### Works on UWP/WinUI

None

### Affected platforms

Mac Catalyst

**Comment by agneszitte** [comment]
@jeromelaban, @jhanvi03  I am closing this issue as it is a duplicate of this other issue:
[[MacCatalyst] Press state that stays pressed for Button and ToggleButton](https://github.com/unoplatform/uno/issues/16838#top)
 #16838
