### ISSUE TITLE
Skia drawCircle and drawPoint prevent all rendering when used on WASM

### ISSUE THREAD

**Issue by hawkerm** [unoplatform/uno#1754]
## Current behavior
Trying to use `drawCircle` or `drawPoint` with a Skia canvas on WASM causes all rendering commands to not function.

## Expected behavior
Able to draw circle or points.

## How to reproduce it (as minimally and precisely as possible)
1. Run the `SkiaSharp.Extended.Svg` example from the Uno repo in WASM, see that it works
2. At the bottom of the render [function in MainPage.xaml.cs](https://github.com/unoplatform/Uno.SkiaSharp.Extended/blob/uno/SkiaSharp.Extended.Svg/SkiaSharpUnoDemo/SkiaSharpUnoDemo.Shared/MainPage.xaml.cs) add
```
canvas.DrawCircle(100, 100, 50, new SKPaint() { Color = SKColors.Blue });
```
3. Run the project again, see that it fails, if you look at the browser console you'll see this:
```
Stacktrace: 
mono.js:1:30480
uncaught exception: abort(). Build with -s ASSERTIONS=1 for more info. Uno.UI.js:83:33
    InnerWakeUp http://localhost:54072/Uno.UI.js:83
    __setImmediate_cb http://localhost:54072/mono.js:1
ASM_CONSTS<@http://localhost:54072/mono.js:1:30462
_emscripten_asm_const_i@http://localhost:54072/mono.js:1:30789
@:wasm-function[676]:0x9328c
@:wasm-function[8094]:0x222859
@:wasm-function[8640]:0x2368bf
@:wasm-function[8638]:0x236865
@:wasm-function[8637]:0x23681e
@:wasm-function[8642]:0x23696f
@:wasm-function[1414]:0x114dc8
@:wasm-function[1412]:0x113b81
@:wasm-function[760]:0xab6fa
@:wasm-function[753]:0x9bd1e
@:wasm-function[753]:0x9b8b4
@:wasm-function[753]:0x9b8b4
@:wasm-function[753]:0x9b8b4
@:wasm-function[753]:0x9bb96
@:wasm-function[753]:0x9bb96
@:wasm-function[753]:0x9ba6c
@:wasm-function[753]:0x9bb96
@:wasm-function[753]:0x9bb96
@:wasm-function[753]:0x9b8b4
@:wasm-function[753]:0x9b8b4
@:wasm-function[712]:0x9417b
@:wasm-function[2236]:0x13bfed
@:wasm-function[5403]:0x1b68c0
@:wasm-function[5417]:0x1b711f
@:wasm-function[5469]:0x1b989d
@:wasm-function[680]:0x9333f
Module._mono_wasm_invoke_method@http://localhost:54072/mono.js:1:3993413
call_method@http://localhost:54072/mono.js:1:359211
bind_static_method/<@http://localhost:54072/mono.js:1:361572
InnerWakeUp/<@http://localhost:54072/Uno.UI.js:79:48
__setImmediate_cb@http://localhost:54072/mono.js:1:721299
```
4. If you run the UWP head, you'll see a circle as expected.

## Environment
Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.3.2)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This most likely has been fixed in recent builds of Uno and SkiaSharp. Is it still a problem ?
