### ISSUE TITLE
[Playground] Data Changes Reflect in Output Despite Auto Refresh Being Unchecked

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno#17565]
### Current behavior

When the "Auto Refresh" option is unchecked, any changes made in the data tab still reflect in the output. This behavior is unexpected as the output should remain static until manual Run

https://github.com/user-attachments/assets/382a52c0-1140-415d-83ea-6fbd7390bb2f

### Expected behavior

When the "Auto Refresh" option is unchecked, changes made in the data tab should not reflect in the output. The output should only update when the user manually clicks on Run.

### How to reproduce it (as minimally and precisely as possible)

Steps to Reproduce:

1. Open Playground on web
2. Uncheck the **Auto Refresh** CheckBox
3. From the snippet dropdown, present on top-right corner, select anything which has data
4. Make changes in **Data** tab
5. observe the output

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

### Anything else we need to know?

The same behavior is present in production as well.

**Comment by jeromelaban** [comment]
Thanks @jhanvi03. This is an expected behavior, selecting the snippet will refresh regardless of the status of the checkbox.
