### ISSUE TITLE
[Gallery][WASM][Menu] Cursor Highlights Only Sub-elements and Not Main Element

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno#17604]
### Current behavior

In the dropdown menu, the cursor highlights the sub-elements but does not highlight the main elements. Additionally, if you click on a sub-element and then click back to the main element, the cursor becomes visible.

https://github.com/user-attachments/assets/27c1a992-d81d-408d-8ef4-0b1eb6d856fb

### Expected behavior

The cursor should highlight both the main elements and sub-elements in the dropdown menu seamlessly. The cursor should remain consistent and visible when navigating between main elements and sub-elements.

### How to reproduce it (as minimally and precisely as possible)

Steps to Reproduce:

1. Open Gallery Canary on macOS or Windows in any browser.
2. In the side menu, observe the marker indicating the current page (which should be the Overview page).
3. Click on a UI element or any other option in the side menu.
4. Notice that only the dropdown menu opens, and the marker remains on the Overview page.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
Thanks @jhanvi03. This is an expected behavior because expandable elements in the Gallery are not considered selectable (they only expand/collapse), and will not get the selector shown.
