### ISSUE TITLE
`WindowActivationState` is using wrong type on Uno targets

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#17626]
### Current behavior

Currently the `WindowActivationState `on `WindowActivatedEventArgs` is using `CoreWindowActivationState` instead of `WindowActivationState` as WinUI3 does.

### Works on UWP/WinUI

Yes

### Affected platforms

WebAssembly, Android, iOS, Mac Catalyst, Skia (WPF), Skia (Linux X11), Skia (macOS), Skia (Linux Framebuffer), Skia (GTK)

**Comment by MartinZikmund** [comment]
Already included in #8339
