### ISSUE TITLE
[WASM] ... can't be started on blank solution template

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#17620]
### Current behavior

The blank solution template can't be started for WASM.

Here is what I tested (multiples times):
- created blank solution by 'dotnet new unoapp -preset=blank -o test'
- started the SLN
- added 'Standard' toolbar to VS (I don't have it on by default)
- pressed F5 -> Windows app comes up -> good
- selected 'test (WebAssembly)' on 'Standard' toolbar 
- pressed F5 -> **Windows app still comes up -> wrong**

[test.zip](https://github.com/user-attachments/files/16328496/test.zip)

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by MartinZikmund** [comment]
This behavior should be improved in the upcoming releases of Uno.Sdk and Uno Visual Studio Extension

**Comment by DierkDroth** [comment]
Thanks for following up @MartinZikmund 

However, is there any way I could start the WASM head on the current solution template at all? Or is this simply a 'no go' for now?

**Comment by MartinZikmund** [comment]
You need to select `net8.0-browserwasm` as the target framework here:

![image](https://github.com/user-attachments/assets/48252148-9915-40f9-9f6d-ad205f18549a)

After you do so, wait a moment to let Visual Studio reload the project and then you should be able to run the WASM target

**Comment by DierkDroth** [comment]
Hmm ... I'm not sure @MartinZikmund. It somehow gets stuck as per screenshot below after pressing F5.
I even tried restarting VS, but to no avail.

![image](https://github.com/user-attachments/assets/88940741-b074-4854-b9ef-cc272625d8f4)

**Comment by DierkDroth** [comment]
Ah, understand. Thanks for clarification @jeromelaban.

**Comment by MartinZikmund** [comment]
@DierkDroth were you able to start the app correctly? Can this be closed?

**Comment by DierkDroth** [comment]
@MartinZikmund honestly I gave up on trying a fresh solution template, but rather repurposed an old one to [report this issue](https://github.com/unoplatform/uno/issues/17624).

-> feel free to close this issue if you don't see any value.

**Comment by MartinZikmund** [comment]
Hopefully the launch should be working fine on latest, and I am not able to reproduce any issues on my side, so I will close for now

**Comment by DierkDroth** [comment]
No problem @MartinZikmund
