### ISSUE TITLE
[CalendarView] Significant Gap Appears in Calendar When when reaching end of calendar

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno#17635]
### Current behavior

After selecting a day at the end of the calendar and switching back to the year view, a large gap is present, disrupting the user experience and causing visual inconsistencies.

https://github.com/user-attachments/assets/250d6ff2-c146-4643-b912-27e8a7d80a7b

<img width="508" alt="Screenshot 2024-07-22 at 11 39 45 AM" src="https://github.com/user-attachments/assets/b8473330-5d43-4bfe-b898-5fee4a8e19c1">

### Expected behavior

The calendar should smoothly transition between month and year views without any large gaps or layout issues.

### How to reproduce it (as minimally and precisely as possible)

Steps to Reproduce:

1. Open Gallery in any of the web browser
2. Navigate to Menu -> UI Components -> CalenderView
3. In the calendar reach to end of years
4. Select a day
5. Go back to years
6. Observe the huge blank gap.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by rajamatt** [comment]
Findings so far: happening on Skia & Wasm, looks like we need to add some logic surrounding BringDisplayDateintoView(), more precisely the ScrollToDate(date) method should probably take in a `date` that would prevent this behavior from occuring altogether.

**Comment by agneszitte** [comment]
@jhanvi03, @Darsh0307 if you can test this issue with latest internal 5.6 stable please

**Comment by agneszitte** [comment]
I am **not** able to reproduce this issue either with:
- Gallery canary: [Wasm 🐤](https://unogallerycanary.z27.web.core.windows.net/)
- Latest **Uno.Sdk 5.6.36** with a **blank app** and `<CalendarView SelectionMode="Single" />`

--- 
Tested with:
- [Gallery Canary Wasm 🐤](https://unogallerycanary.z27.web.core.windows.net/)
- Templates/SDK: **5.6.36**
- VS version: VS 2022 (64-bit) - Version **17.13.1**
- VS VSIX: [5.6.31](https://dev.azure.com/uno-platform/uno-private/_build/results?buildId=155709&view=results)
- [BlankAppVsWizardNet9.zip](https://github.com/user-attachments/files/18877249/BlankAppVsWizardNet9.zip)
- Platform: **WebAssembly**
- OS: **Windows**
