### ISSUE TITLE
[Gallery][WASM - Sarafi Only] Menu - Menu Options Disappear After Switching Between Browser Windows

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno#17640]
### Current behavior

When a user is on UNO Gallery on 1 window and then switch to another window and comes back on same window then the option in menu disappears.

https://github.com/user-attachments/assets/1b558d52-481e-438a-b513-a14bf2f7b65d

https://github.com/user-attachments/assets/2a9cf559-5186-4167-819d-897f00b0e5a4

### Expected behavior

All the options should be visible

### How to reproduce it (as minimally and precisely as possible)

1. Open the Gallery in a browser, such as Chrome.
2. Open the Uno Gallery in another browser, like Safari.
3. Keep both browsers open simultaneously.
4. In Safari, select any component from the Gallery.
5. Switch to Chrome and stay there for a while.
6. Return to Safari without clicking anywhere.
7. Scroll up and down the menu in Safari.
8. Observe that the menu option disappears.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly [**SAFARI** only]

**Comment by MartinZikmund** [comment]
@jhanvi03 can you please make another recording? It seems it was not attached properly

**Comment by Kunal22shah** [comment]
This seems specific to Safari/ MacOS only.

**Comment by MartinZikmund** [comment]
This looks eerily similar to what we saw with `TextBoxView` in https://github.com/unoplatform/uno/pull/17665
