### ISSUE TITLE
[Gallery][WASM][UI Components] TextBlock - Last line of TextAlignment is not clearly visible

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno#17660]
### Current behavior

In each para the Last line of TextAlignment is not clearly visible. This happens only in MAC -> Chrome. Works properly in all the other browsers and also in Windows browsers.

https://github.com/user-attachments/assets/7c1b1389-2974-4726-af9c-8c0bc2acfe9e

### Expected behavior

last line of the para should not cut and clearly visible.

### How to reproduce it (as minimally and precisely as possible)

1. Open Gallery on MAC Chrome browser
2. Navigate to Menu -> UI Components -> TextBlock
3. Scroll down to TextAlignment
4. observe the last line of each para

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
@ajpinedam are you able to repro this as well?

**Comment by agneszitte** [comment]
> @ajpinedam are you able to repro this as well?

@ajpinedam were you able to repro this please?

**Comment by ajpinedam** [comment]
I could not reproduce it on my Mac. 

<img width="1537" alt="image" src="https://github.com/user-attachments/assets/400e181c-c55c-464f-9012-5fe8fdcb5a09">

I am running macOS Sonoma 14.6.1 and Chrome Version 128.0.6613.114 (Official Build) (x86_64)

cc: @jeromelaban  @jhanvi03 @agneszitte

**Comment by ajpinedam** [comment]
Tested also (just in case) in an ARM Base Mac running Sonoma 14.6.1 and got the same results

![image](https://github.com/user-attachments/assets/ab5991c5-a307-4d8a-9c0b-49b3b1b62a0e)

**Comment by agneszitte** [comment]
@jhanvi03 are you still able to reproduce this issue with latest Gallery canary?

**Comment by jhanvi03** [comment]
Closing the issue as I am unable to reproduce on Mac -> Chrome.
<img width="1069" alt="Screenshot 2024-09-05 at 5 43 49 PM" src="https://github.com/user-attachments/assets/d0ef06bf-1a78-4c24-b888-efafbd0379d4">
