### ISSUE TITLE
[MAC Catalyst][MACOS] Microsoft.UI.Xaml.UIElement related error coming when debugging.

### ISSUE THREAD

**Issue by Darsh0307** [unoplatform/uno#17680]
### Current behavior

Orignally from this issue https://github.com/unoplatform/private/issues/498#issuecomment-2248023470

We are able to run the application with debugger then there is an error like this in the run window but at the same tim.
No doubt the IDE its able to start the application.

![image](https://github.com/user-attachments/assets/089c2d49-75d7-411d-a5c4-62fa8ca57b76)

No doubt but still there is an error message and its like this 
`2024-07-23 10:19:05.961 dafrs[5988:147340] W/Microsoft.UI.Xaml.UIElement: The ManipulationMode 'TranslateX, TranslateY, TranslateInertia' is not supported by Uno. Only 'None', 'All', 'System', 'TranslateX', 'TranslateY', 'Rotate', and 'Scale' are supported. Using any other mode will not cause an error, but the corresponding manipulation event will not be generated. Note that with Uno the 'All' and 'System' are handled the same way. `

### Expected behavior

There should be no error coming in the output window when we are trying to run macos

### How to reproduce it (as minimally and precisely as possible)

Get the latest rider plugin.
Create a new application with blank template
Change configuration to Mac.
Try to run the application.
Then there will be a bunch of errors in the run window.

### Workaround

Uno rider plugin:- 1.0.5
Uno templates:- 5.3.31

### Works on UWP/WinUI

None

### IDE

Rider macOS

**Comment by agneszitte** [comment]
@Darsh0307 is this still happening with latest please?

**Comment by Darsh0307** [comment]
@agneszitte  should i test with 5.3.99 or 5.3.108 ??

**Comment by agneszitte** [comment]
> @agneszitte should i test with 5.3.99 or 5.3.108 ??

@Darsh0307 
- Uno Rider plugin version: [1.1.1 stable version](https://dev.azure.com/uno-platform/Uno%20Rider%20Addin/_build/results?buildId=137681&view=results)
- Rider latest stable version available from August 25: [Version: 2024.2.2 / Build: 242.20224.431](https://www.jetbrains.com/rider/download/#section=windows)
- Uno.SDK: 5.3.99

**Comment by Darsh0307** [comment]
The issue is no longer happening with Uno.sdk :- 5.3.99 , Rider stable version :- 2024.2.2
Uno Rider Plugin version :- 1.1.1

Closing the issue since its no longer happening.
