### ISSUE TITLE
WebView2 Issues.

### ISSUE THREAD

**Issue by GCX-Monter** [unoplatform/uno#17687]
### Current behavior

1. When clicking on external links, they continue to open inside WebView2.
2. On Android, when trying to open a video in full screen (for example, on YouTube), nothing happens. When running on Windows, the video frame stretches but does not switch to full-screen mode.
3. It is not possible to disable the zoom feature.
4. On Android, when clicking the play button on a video, a stretched gray play button icon is displayed in frame of video for a few seconds before playback begins.

### Expected behavior

1. All external links that do not contain the original domain should open in the default browser on all devices.
2. When clicking the button to open a video in full screen, the application should maximize the video window to full screen.
3. Disable the zoom on all pages.
4. While the video is loading, a simple black background should be displayed.

### How to reproduce it (as minimally and precisely as possible)

1. Open any external link from the original one.
2. Open youtube.com and try to expand any video to full screen.
3. For example open platform.uno and try zoom.
4. Open any video on youtube.

### Workaround

Unfortunately, I haven't found any workarounds.

### Affected platforms

Android, Windows (WinAppSDK)

### IDE

Visual Studio 2022

### IDE version

Visual Studuo 17.9.1, UNO 5.2

### Anything else we need to know?

Hello Uno team! For about 4 months, I have been trying to solve the above-mentioned problems, but unfortunately, I have not succeeded. I kindly ask you to help me, especially with how to make external links open in the default browser.
I really love you, and what you have developed is truly impressive. Especially the fact that you managed to implement WebView2 on mobile devices. Could you please help me find a solution, or perhaps provide an example of how to implement all of this correctly? Please do not be too harsh on me; I am relatively new to development, and I apologize in advance if I did something wrong. This is my first time reaching out with a problem on GitHub.

**Comment by jeromelaban** [comment]
Thanks for the report! Glad you're taking uno for a spin! Would you mind opening separate issues for those? We'll treat them individually.
