### ISSUE TITLE
[X11] App not visible at first startup on Uno Desktop

### ISSUE THREAD

**Issue by HakanL** [unoplatform/uno#17681]
### Current behavior

Since upgrading to Uno Desktop when my application first starts up it's all hidden, I only see the X11 background. If I tap the screen then the application is visible and works 100%. It worked fine in 5.1 (using Gtk head). I've since upgraded to single project with Uno Sdk 5.3 and changed to use Uno Desktop. I had the same issue on Uno 5.2.

The application runs on Raspberry Pi CM4 with a 800x480 touchscreen. I use X11 (via Xwayland) on Arm64 Linux.
Of course this is tricky to troubleshoot as there are multiple parts in play, but it seems that something is missing from the X11 startup that causes the application to not be visible. Noteworthy is that I have a feature to take a snapshot of the screen and it shows the correct output (but it's rendering the screen to a bitmap, so technically it's not a screenshot).
I have a VNC server on the device as well and if I VNC into it then the app shows up (but it's probably because the mouse movement causes it to be "triggered", same as a tap).

### Expected behavior

The Uno application should be visible at startup.

### How to reproduce it (as minimally and precisely as possible)

It doesn't happen on my debug device where I SSH to the device and launch the application in debug, so unfortunately I don't have a minimal repro project.

### Workaround

Going back to 5.1 (using multi-project solution) works. Haven't figured out a way to "trigger" the display yet.

### Works on UWP/WinUI

None

### NuGet package version(s)

Uno.Sdk 5.3.90
No overrides in `Directory.Build.props`

### Affected platforms

Skia (Linux X11)

### IDE

Visual Studio 2022

**Comment by ramezgerges** [comment]
Hey @HakanL, this is obviously very hard to diagnose, but we recently merged a fix to a vaguely similar problem in https://github.com/unoplatform/uno/pull/17876. Could you please try with the latest Uno.Sdk and see if that fixes the problem?

**Comment by HakanL** [comment]
@ramezgerges Yeah, I realize it's very hard to diagnose as it only happens in this environment. I was hoping there could be some obvious change from the legacy GTK to new desktop. But let me try the latest, what SDK version is that in?

**Comment by ramezgerges** [comment]
I think it should be https://www.nuget.org/packages/Uno.Sdk/5.4.0-dev.180.

**Comment by HakanL** [comment]
It worked! Thanks a lot @ramezgerges for identifying that this other fix may have been related! Can this fix be back-ported to 5.3? I have another issue with 5.4 where I can't scroll ListView/ItemsRepeater with touch any longer, would be nice to have a stable base in 5.3 that I can use.

**Comment by HakanL** [comment]
For reference, this is the scroll issue: https://github.com/unoplatform/uno/issues/17912

**Comment by ramezgerges** [comment]
@HakanL Nice! For the problem with scrolling, backporting is unlikely to fix this. Touch events are currently not implemented on X11 (see https://github.com/unoplatform/uno/pull/15799). I will add more details in the other issue.

**Comment by HakanL** [comment]
@ramezgerges Yeah, I realized that 5.3 has the same issue with scrolling. But it's good that this initial issue was resolved at least! Thanks for your help!
