### ISSUE TITLE
[Gallery][iOS][Non-UI features] Simple Orientation - App crashes while Face-down

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno#17688]
### Current behavior

The app crashes when the user keep the phone facing down. 

### Expected behavior

App should not crash and it should show 'Orientation: Facedown'

### How to reproduce it (as minimally and precisely as possible)

1. Download and install gallery form TestFlight.
2. Navigate to Menu -> Non UI Features -> Simple Orientation.
3. Click on 'Start observing orientation changes'
4. Keep the phone facing down
5. observe the app crash

### Works on UWP/WinUI

None

### Affected platforms

iOS

**Comment by agneszitte** [comment]
@jhanvi03 can you check again if this issue is still happening lately please (when latest canary available)

**Comment by jhanvi03** [comment]
The Issue still persist with latest canary version 1.6.0(2410090204.1809)

**Comment by agneszitte** [comment]
@jhanvi03, @Darsh0307 if you can test this issue with latest canary build please

**Comment by jhanvi03** [comment]
Unable to repro tested with gallery build: 1.6.0 (2501200306.1857) with iOS

https://github.com/user-attachments/assets/9700ef25-f23c-45e7-a495-6b279699533b
