### ISSUE TITLE
[Wasm][Skia] Selecting a not yet displayed item hides other items in the list

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#17695]
### Current behavior

The selection of an item in a ListView may hide other items already present in the list.

tested versions

- 5.3.0-dev.793 Fail
- 5.3.0-dev.450 Fail
- 5.3.0-dev.288 Fail
- 5.3.0-dev.170 Fail
- 5.3.0-dev.168 Fail
- 5.3.0-dev.163 Fail -> 91401cf53e84b191549dce0646919ea68c5d6f70
- 5.3.0-dev.125 Works -> 05f65026cd6d5597256ba4968df7a93b4b41aaaa
- 5.3.0-dev.100 Works

Likely caused by https://github.com/unoplatform/uno/pull/15916
### Expected behavior

All items should be visible.

### How to reproduce it (as minimally and precisely as possible)

- Use this repro: [17695-UnoApp28.zip](https://github.com/user-attachments/files/16368839/17695-UnoApp28.zip)
- Run wasm or desktop, click the "repro" button
- Notice that the first item in the list is not visible, right after the call to the `SelectedItem` invocation.

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.4-dev

### Affected platforms

WebAssembly, Skia (WPF), Skia (Linux X11), Skia (macOS), Skia (Linux Framebuffer), Skia (GTK)

**Comment by darenm** [comment]
@jeromelaban @Xiaoy312 @francoistanguay Has this been pushed out to a 5.3 build yet? We just built with what we think is latest and still see the issue.

**Comment by Xiaoy312** [comment]
Hi @darenm, the fix is unfortunately still not published for 5.3 due to CI issue. We will work on to get that resolve asap.

**Comment by Xiaoy312** [comment]
We are still waiting on QA and release approval. The earliest we can expect would be by Tuesday.
I'm sorry for this delay, and not having unblock the CI earlier.

**Comment by darenm** [comment]
Thank you for the update.
