### ISSUE TITLE
Support LinearColorKeyFrame animation

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1769]
## What would you like to be added:

`LinearColorKeyFrame` to allow animation of `Color`

## Why is this needed:

Cool gradient animations

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

**Comment by carldebilly** [comment]
Seems already implemented.  I'll close this issue and remove it from the milestone.
