### ISSUE TITLE
[Desktop] `OutputType` cannot be changed

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#17719]
### Current behavior

Setting `<OutputType>Exe</OutputType>` does not have an effect on skia desktop and still shows the console on windows.

### Expected behavior

The console does not show.

### Workaround

```xml
<Target Name="__OverrideOutputType" BeforeTargets="BeforeBuild">
  <PropertyGroup>
   <OutputType>WinExe</OutputType>
  </PropertyGroup>
</Target>
```

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

**Comment by ArchieCoder** [comment]
I put the workaround near the end of the project, but it does not work. 

![image](https://github.com/user-attachments/assets/3718f4b9-aa33-43d7-90e3-a505cd78c6c5)

**Comment by Youssef1313** [comment]
@ArchieCoder If you want to hide the console, you probably need `WinExe`?

**Comment by ArchieCoder** [comment]
@Youssef1313 I tried but it does not work

`<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>
      net8.0-windows10.0.19041;
      net8.0-desktop;
    </TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>
    <UnoSplashScreenColor>#F9F9F9</UnoSplashScreenColor>
    
    <ApplicationTitle>Elements Technician</ApplicationTitle>
    
    <ApplicationId>com.Enteligent.ElementsTechnician</ApplicationId>
    
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    
    

    
    <UnoFeatures>
      Lottie;
      Hosting;
      Toolkit;
      Logging;
      LoggingSerilog;
      Mvvm;
      Configuration;
      Http;
      Serialization;
      Localization;
      Navigation;
    </UnoFeatures>
  </PropertyGroup>

  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls.DataGrid" />
    <PackageReference Include="CommunityToolkit.WinUI.UI" />
    <PackageReference Include="WinUIEx" />
    
  </ItemGroup>
  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'windows'">
    <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls" />
    <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid" />
    <PackageReference Include="Uno.CommunityToolkit.WinUI.UI" />
    
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="MQTTnet" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Uno.Fonts.OpenSans" />
    <PackageReference Include="Zeroconf" />
  </ItemGroup>

  <Target Name="__OverrideOutputType" BeforeTargets="BeforeBuild">
    <PropertyGroup>
      <OutputType>WinExe</OutputType>
    </PropertyGroup>
  </Target>

</Project>
`

**Comment by agneszitte** [comment]
@rajamatt if you can help verify if @dansiegel changes (https://github.com/unoplatform/uno/pull/17974) will fix the issue please

**Comment by jeromelaban** [comment]
@ArchieCoder using 5.4.5, this is preventing the console from showing:

```xml
  <PropertyGroup>
    <TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst;net8.0-windows10.0.19041;net8.0-browserwasm;net8.0-desktop</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <OutputType Condition="'$(TargetFramework)'=='net8.0-desktop'">WinExe</OutputType>
```

The only linked issue is that the hot reload tooling (`MainWindow.EnableHotReload()`) is disabled incorrectly when this happens that we'll fix separately.

**Comment by ArchieCoder** [comment]
@jeromelaban Tested! Thank you a lot for this one :)
