### ISSUE TITLE
[Wasm]Uno Gallery not working in mac safari

### ISSUE THREAD

**Issue by easy28** [unoplatform/uno#17729]
### Current behavior

There is error in safari Inspector when load uno gallery site.    My uno wasm project can't load in mac safari with same error.

![image](https://github.com/user-attachments/assets/56271581-e6f8-44d2-b7dd-5eeb9790d2b7)

### Works on UWP/WinUI

None

**Comment by easy28** [comment]
Uno.UI 5.4.0-dev.974
Uno.UI.WebAssembly  5.4.0-dev.974
Uno.Wasm.Bootstrap 9.0.0-dev.104

**Comment by jeromelaban** [comment]
Thanks for the report. Which version of macOS are you using? This was likely fixed in a later version.

**Comment by easy28** [comment]
I am using macOS Ventura 13.0.1 , Safari 16.1  .    Both chrome and firefox can work on this mac,  only safari stuck.

**Comment by easy28** [comment]
I disabled the SIMD, and it works in mac safari now,   thank you!

  <PropertyGroup>
     <WasmShellEnableSimd>false</WasmShellEnableSimd>
  </PropertyGroup>
