### ISSUE TITLE
Using Button.Click handler in code behind doesn't work when used in a DataTemplate

### ISSUE THREAD

**Issue by jeanplevesque** [unoplatform/uno#1776]
## Current behavior
Button.Click handler in code behind **is not** called when the button is in a DataTemplate in the Page's Resources.

## Expected behavior
Button.Click handler in code behind **is** called when the button is in a DataTemplate in the Page's Resources.

## How to reproduce it
1. Create a new Page and add a DataTemplate in the Page.Resources.
1. In that DataTemplate add a Button and define an event handler for the Click event.
1. Write the event handler in the code behind of the Page.
1. Run the application and click the Button.
1. Notice that the event handler is invoked in UWP, but not for the other platforms.

## Environment

Nuget Package:

Package Version(s):
1.45

Affected platform(s):
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
This seems to be working now in the latest version of Uno.

**Comment by the-wazz** [comment]
not working in wasm.
