### ISSUE TITLE
Support for Headers in ListView

### ISSUE THREAD

**Issue by SuperJMN** [unoplatform/uno#1778]
## What would you like to be added:

Support for `ListView.Header`, +`ListView.HeaderTemplate`

## Why is this needed:
It helps simplify XAML layouts

## For which Platform:

- [X] iOS
- [X] Android
- [X] WebAssembly
- [ ] Windows

**Comment by davidjohnoliver** [comment]
`Header` and `HeaderTemplate` should be working on iOS and Android, are you encountering any problems on those platforms?

It's not implemented on WASM yet, see this issue for tracking: https://github.com/unoplatform/uno/issues/234
