### ISSUE TITLE
[Uno.sample][Canvas_DependentAnimation] The circle is not animating

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno#17795]
### Current behavior

The circle should be animating as per the description but it remains stable/constant.
Uno Sample version: 2507311405.31545

https://github.com/user-attachments/assets/267f1dba-2ee6-438c-be8a-d944aba18110

### Expected behavior

As per the description, the circle should be animated.

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
Duplicate of https://github.com/unoplatform/uno/issues/16971
