### ISSUE TITLE
Invalid RenderTransform rotation on paths for iOS

### ISSUE THREAD

**Issue by double28** [unoplatform/uno#178]
In ios:
![image](https://user-images.githubusercontent.com/33952312/45202186-b5423680-b2aa-11e8-85b2-699a5eb73714.png)

In uwp and andriod:
![image](https://user-images.githubusercontent.com/33952312/45202204-c5f2ac80-b2aa-11e8-9d17-2e43ebce7be4.png)

The code is exactally the same!
In uwp and andriod is right! I guess the triangle's CompositeTransform.Rotation  been Changed again after  my code run!

**Comment by double28** [comment]
the  triangle is made by path,path's Data is GeometryPath. My code is to much.If you can't find the reason,I'll make some test code and upload it next week.

**Comment by jeromelaban** [comment]
Thanks for the report! We're bound to have differences in behavior in some cases, and we're definitely interested in improving the coverage.

If you can provide a code sample of what's drawing your arrow, that'd be very helpful.

Thanks!

**Comment by double28** [comment]
In my xaml file ,
 <StackPanel x:Name="_sp" Orientation="Vertical"/>
In my cs file ,

 public SketchPage()
        {
            InitializeComponent();
            this.Loaded += SketchPage_Loaded;
        }

        void SketchPage_Loaded(object sender, RoutedEventArgs e)
        {
            _path = new Path();
            _path.Stroke = SolidColorBrushHelper.Blue;
            _path.Fill = SolidColorBrushHelper.Black;
           
            _path.Width = 120;
            _path.Height = 120;
            _sp.Children.Add(_path);
            Test();
        }

        void Test()
        {
            PathGeometry arrowData = ParseGeometry("M0,0 80,40 0,80 Z");
            _path.Data = arrowData;
            CompositeTransform tailPathTransform = new CompositeTransform();
            _path.RenderTransform = tailPathTransform;
            tailPathTransform.Rotation = -90;
        }

        static int GetCharIdx(string p_str)
        {
            string num = ",-1234567890.";
            for (int i = 0; i < p_str.Length; i++)
            {
                if (num.IndexOf(p_str[i]) < 0)
                    return i;
            }
            return -1;
        }


        public static PathGeometry ParseGeometry(string p_data)
        {
            p_data = p_data.ToUpper();
            PathGeometry pg = new PathGeometry();
            PathFigureCollection pfc = new PathFigureCollection();
            pg.Figures = pfc;
            PathFigure pf = new PathFigure();
            pf.IsFilled = true;
            pf.IsClosed = true;
            pfc.Add(pf);

            // deal the head
            p_data = p_data.TrimStart('M', ' ');
            // start point
            string first = p_data.Substring(0, GetCharIdx(p_data));
            string[] point = first.Split(',');
            pf.StartPoint = new Windows.Foundation.Point(double.Parse(point[0]), double.Parse(point[1]));
            p_data = p_data.Substring(first.Length).TrimStart();
            // the other data
            bool isOver = false;
            while (!isOver)
            {
                int pos = GetCharIdx(p_data);
                int next = 0;
                if (pos == 0)
                {
                    first = p_data.Substring(0, 1);
                    p_data = p_data.Substring(1);
                    string data;

                    switch (first)
                    {
                        case "L":
                            next = GetCharIdx(p_data);
                            data = p_data.Substring(0, next);
                            p_data = p_data.Substring(next).Trim();
                            point = data.Split(',');
                            LineSegment ls = new LineSegment();
                            ls.Point = new Windows.Foundation.Point(double.Parse(point[0]), double.Parse(point[1]));
                            pf.Segments.Add(ls);
                            break;
                        case "C":
                            BezierSegment bs = new BezierSegment();
                            next = GetCharIdx(p_data);
                            data = p_data.Substring(0, next);
                            p_data = p_data.Substring(next).Trim();
                            point = data.Split(',');
                            bs.Point1 = new Windows.Foundation.Point(double.Parse(point[0]), double.Parse(point[1]));
                            next = GetCharIdx(p_data);
                            data = p_data.Substring(0, next);
                            p_data = p_data.Substring(next).Trim();
                            point = data.Split(',');
                            bs.Point2 = new Windows.Foundation.Point(double.Parse(point[0]), double.Parse(point[1]));
                            next = GetCharIdx(p_data);
                            data = p_data.Substring(0, next);
                            p_data = p_data.Substring(next).Trim();
                            point = data.Split(',');
                            bs.Point3 = new Windows.Foundation.Point(double.Parse(point[0]), double.Parse(point[1]));
                            pf.Segments.Add(bs);
                            break;
                        case "Z":
                            isOver = true;
                            break;
                        default:
                            break;
                    }
                }
                else
                {
                    // no charater must be "L"
                    next = GetCharIdx(p_data);
                    string data = p_data.Substring(0, next);
                    p_data = p_data.Substring(next).Trim();
                    point = data.Split(',');
                    LineSegment ls = new LineSegment();
                    ls.Point = new Windows.Foundation.Point(double.Parse(point[0]), double.Parse(point[1]));
                    pf.Segments.Add(ls);
                }
            }

            return pg;
        }

in ios the  " tailPathTransform.Rotation = -90;  " must be covered.

**Comment by dr1rrb** [comment]
This is now working, closing the issue.
