### ISSUE TITLE
[Uno Sample App] Font Color Remains Dark in Dark Theme

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno#17801]
### Current behavior

When the user switches to the dark theme, the font color does not adjust appropriately and remains dark/black, making the text difficult to read against the dark background.
Uno Sample version: 2507311405.31545

https://github.com/user-attachments/assets/02f4150c-9620-4c68-8d9e-81e793f23eb4

### Expected behavior

The font color remains dark/black

### How to reproduce it (as minimally and precisely as possible)

1. Opne UnoSample app on iOS.
2. Uncheck CheckBox from dark Theme.
3. Observe the font color in the Menu.
4. Check the CheckBox for Dark Theme.
5. Observe the text color in the Menu.

### Works on UWP/WinUI

None

### Affected platforms

iOS

**Comment by jeromelaban** [comment]
Thanks for the report. This is expected at this time, it's only meant to validate inner controls, not outer controls.
