### ISSUE TITLE
[WSL] Main window does not open

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#17816]
### Current behavior

In VS, create a new template, select the WSL2 profile, start debugging. The main window does not appear.

### Expected behavior

The main window appears.

### Workaround

None

### Works on UWP/WinUI

None

### NuGet package version(s)

uno.sdk: 5.4.0-dev.170

### Affected platforms

Skia (Linux X11)

**Comment by MartinZikmund** [comment]
Reopening to track backport to 5.3
