### ISSUE TITLE
iOS Simulator: adding ProgressRing crashes app

### ISSUE THREAD

**Issue by baskren** [unoplatform/uno#17810]
### Current behavior

Add ProgressRing to iOS Simulator app's VisualTree and app crashes

### Expected behavior

No crash, just like Android (device and emulator), iOS device, MacCatalyst, WinUI, Windows-Desktop

### How to reproduce it (as minimally and precisely as possible)

DEMO REPO: https://github.com/baskren/LottieTest

STEPS TO CREATE:

- Create new blank UNO solution
- Add Button to StackPanel and `OnButtonClick` code behind
- in `OnButtonClick`, add a new ProgressRing (`IsActive=true`) to StackPanel
- Build app, targeting iOS Simulator
- Run app (in iOS Simulator), tap Button, app crashes

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

"Uno.Sdk" : "5.3.96"

### Affected platforms

iOS

### IDE

Visual Studio 2022, Rider macOS

### IDE version

JetBrains Rider 2024.1.4; Microsoft Visual Studio Community 2022 (ARM 64-bit) - Current Version 17.10.4

### Relevant plugins

n/a

**Comment by baskren** [comment]
UPDATE: By accident, I tried this using the iPhone 13 simulator, iOS 15.5, instead of the iPhone 15 simulator, iOS 17.5.  On the iPhone 13, iOS 15.5, I got the following:


https://github.com/user-attachments/assets/7abdc223-e768-41f6-aa6e-dc7b4eff2bdb

**Comment by baskren** [comment]
Looks like, for now, a work around is to test if the app is running on an iOS Simulator and then set `IsActive=false`

**Comment by ajpinedam** [comment]
@baskren Thanks for the report. 

Are you running this on a Mac with M processors (ARMs)? I am running the Sample project you attached on a Mac with Intel, but I have problems reproducing the error.

I use the iPhone 15 and iPhone 15 Pro simulators with iOS 17.5 for my tests. 

I ran the app from Rider 2024.1.4 and VsCode with Uno plugin version v0.15.4.

I could try running it on a Mac with M processors to validate there, too.

**Comment by baskren** [comment]
@ajpinedam : Glad to hear it's working for you.  I'm running on M2 MBP, using Parallels when running from VisualStudio 2022 ARM (connected via Parallels back to the same M2 for Pair2Mac) and using Rider when running in MacOS.

**Comment by baskren** [comment]
https://github.com/user-attachments/assets/8d46eac4-dce3-4ca6-a32f-7fdf6b9e0762

**Comment by baskren** [comment]
FWIW, I would be happy to do a screen share.

**Comment by ajpinedam** [comment]
> @ajpinedam : Glad to hear it's working for you.  I'm running on M2 MBP, using Parallels when running from VisualStudio 2022 ARM (connected via Parallels back to the same M2 for Pair2Mac) and using Rider when running in MacOS.

Thanks. I am getting an M2 ready to test it out. If still unable to reproduce I will take your invite for the screen sharing. 

Keep you posted and thanks again!

**Comment by ajpinedam** [comment]
@baskren finished the test on the MBP M processors, and I could reproduce the error reported. 

I will continue with the investigation.

**Comment by baskren** [comment]
@ajpinedam : Glad to hear that you're able to reproduce the problem.  Thanks for your attention!

**Comment by ajpinedam** [comment]
Upgrading to the latest iOS and using the new simulators (iOS 18.1) seems to have fixed the issue with the Progress Ring.

https://github.com/user-attachments/assets/bdc1bddc-7476-47b1-9881-b750b272a975

**Comment by ajpinedam** [comment]
Important to note: When running the same application on iOS Simulator, Version 17.5 crashes the app as reported above. When running on iOS Simulator Version 18.1, the application is unchanged; it runs successfully, as seen in the previous comment.

**Comment by jeromelaban** [comment]
Thanks, let's close for now then. It may have been caused by a .NET issue that has been fixed since then.
