### ISSUE TITLE
Window area a bit off when using Wayland

### ISSUE THREAD

**Issue by microhobby** [unoplatform/uno#17826]
### Current behavior

A simple window with:

```xaml
<Page x:Class="unozinGtk.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:unozinGtk"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

  <StackPanel
        HorizontalAlignment="Center"
        VerticalAlignment="Center">

      <TextBlock AutomationProperties.AutomationId="HelloTextBlock"
            Text="Hello Uno Platform"
            HorizontalAlignment="Center" />

  </StackPanel>
</Page>

```

Generates the following on Wayland (Weston compositor):

![image](https://github.com/user-attachments/assets/a0bcdb6f-7986-45cb-9359-82ee87b52542)

But when using X11:

![image](https://github.com/user-attachments/assets/3c7019f0-3034-4699-b19f-159d3750a371)

You can check that when using X11, the TextBlock is centered vertically and horizontally, but when using Wayland not.

### Expected behavior

Content be centered when using X11 and Wayland

### How to reproduce it (as minimally and precisely as possible)

[unozinGtk.zip](https://github.com/user-attachments/files/16483219/unozinGtk.zip)

### Workaround

Use only X11 backend

### Works on UWP/WinUI

None

### NuGet package version(s)

```xml
<Project ToolsVersion="15.0">
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageVersion Include="SkiaSharp.Skottie" Version="2.88.8" />
    <PackageVersion Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.8" />
    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.1.1" />
    <PackageVersion Include="Uno.Resizetizer" Version="1.5.2" />
    <PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.3.114" />
    <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.37" />
    <PackageVersion Include="Uno.WinUI" Version="5.3.114" />
    <PackageVersion Include="Uno.WinUI.Lottie" Version="5.3.114" />
    <PackageVersion Include="Uno.WinUI.DevServer" Version="5.3.114" />
    <PackageVersion Include="Uno.WinUI.Skia.Gtk" Version="5.3.114" />
  </ItemGroup>
</Project>
```

### Affected platforms

Skia (GTK)

### IDE

Visual Studio Code

### IDE version

v0.15.4

**Comment by jeromelaban** [comment]
Thanks for the report.

Can you validate if this issue happens with the default template from uno 5.3? This may be a GTK bug, and the new rendering from 5.3 does not use GTK anymore.
