### ISSUE TITLE
[WASM] keepalive C# generator executes in F# project

### ISSUE THREAD

**Issue by Juriyx** [unoplatform/uno#17852]
### Current behavior

Generator executes that leads to this error:
`FSC : error FS0226: The file extension of 'obj\Release\net8.0-browserwasm\unouiruntimewasm_keepalive.g.cs' is not recognized. Source files must have extension .fs, .fsi, .fsx, .fsscript, .ml or .mli. [D:\a\1\s\Console\Shared\Console.Shared.fsproj::TargetFramework=net8.0-browserwasm]`

### Expected behavior

Generator not executed

### How to reproduce it (as minimally and precisely as possible)

1. Create Uno project from template.
2. Add F# class library.
3. Replace F# class library fsproj content with Uno class library content
4. Add `<Target Name="XamlPreCompile" Condition="$(TargetFramework.Contains('windows10'))" />`
5. Add reference to F# class library.
6. Build the project in Azure DevOps using this command:
```
$msbuild = vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
$collectionOfArgs = @("$(ConsoleApp)", "/r", "/p:Configuration=$(BuildConfiguration)")
& $msbuild $collectionOfArgs
```

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.3.90

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.9.7

**Comment by Youssef1313** [comment]
Does adding `<Target Name="_ForceUnoUIRuntimeWasm" />` in the F# project file help?

**Comment by xperiandri** [comment]
> Also, why does the F# project has a reference to Uno at all? Is it meant to be a just simple class library referenced by Uno app?

Yes, but it also references WinUI namespaces like using `DispatcherQueue` type

**Comment by Juriyx** [comment]
> Does adding `<Target Name="_ForceUnoUIRuntimeWasm" />` in the F# project file help?

Hello. No, it doesn't help

**Comment by xperiandri** [comment]
Any other possible solutions?

**Comment by xperiandri** [comment]
How can we disable the generator conditionally?

**Comment by Youssef1313** [comment]
I opened #17959. I think it may still be best to not include Uno in the F# project and separate the any Uno-related logic from the F# library to the C# Uno app/library

**Comment by xperiandri** [comment]
@Youssef1313 it is smpossible as our core logic (view models) is written in F#
