### ISSUE TITLE
Is __LINUX__ missing?

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#17856]
### On which page?

https://platform.uno/docs/articles/platform-specific-csharp.html

### What's wrong?

https://platform.uno/docs/articles/platform-specific-csharp.html

I need to implement a way to launch a folder for Mac/Linux/Windows. I was looking for the way to do it for Linux.

While checking https://platform.uno/docs/articles/platform-specific-csharp.html, I didn't see a reference to Linux.

**Comment by Youssef1313** [comment]
I think the underlying OS can't be known at compile-time. So, you'll need to go with `OperatingSystem.IsXYZ()` method calls.

**Comment by ArchieCoder** [comment]
@Youssef1313 ok that's fine with me, thank you!
