### ISSUE TITLE
[ski Linux] The app does not scale properly on a laptop with a big resolution

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#17891]
### Current behavior

The app looks like this

![image](https://github.com/user-attachments/assets/2d68dc44-332f-4a1b-884e-36753edf0636)

![image](https://github.com/user-attachments/assets/fe4d7af0-f20f-4fd1-9a37-34d714c6662f)

With WinUI on my PC (3840x2160 with Scale 150%)
<img width="1916" alt="WinUI" src="https://github.com/user-attachments/assets/ee633af9-6a8d-44f0-99c8-7fa36da591f0">

With Skia Windows on my PC (3840x2160 with Scale 150%)
<img width="1916" alt="Skia Windows" src="https://github.com/user-attachments/assets/e5992c16-1fec-41a5-8ae6-9cf27b5d4064">

### Expected behavior

There should be a better ratio so elements don't look so small.

### Works on UWP/WinUI

Yes

### Affected platforms

Skia (Linux X11)

### IDE

Visual Studio 2022

**Comment by ramezgerges** [comment]
@ArchieCoder Is this on X11 or XWayland? Are all apps scaled accurately except Uno? Uno on X11 should be reading dpi values from X resources (https://wiki.archlinux.org/title/X_resources). Try setting `Xft.dpi` through `xrdb` and see if that helps. As a last resort, you should also be able to override the dpi with the `UNO_DISPLAY_SCALE_OVERRIDE` environment variable.

**Comment by ArchieCoder** [comment]
@ramezgerges here is the answers:

1- X11
2- The app that I use daily scales fine for me like Slack, Chrome and VS Code
3- We tried UNO_DISPLAY_SCALE_OVERRIDE=2 and the app looks the same
4- xftf.dpi when I tried with Jerome was 192. We don't know which value to use as a test.

**Comment by ramezgerges** [comment]
@ArchieCoder This is quite surprising. Are you using the latest packages?

**Comment by ArchieCoder** [comment]
@ramezgerges 5.3.96

**Comment by ramezgerges** [comment]
@ArchieCoder I noticed that the PR that fixes this (https://github.com/unoplatform/uno/pull/17177) was not backported successfully to 5.3. Could you try with 5.4 please? I just tested myself and it definitely works on my end on master.

It is very weird however that `UNO_DISPLAY_SCALE_OVERRIDE` doesn't work. I've testing it also and it works.

**Comment by ArchieCoder** [comment]
@ramezgerges I can confirm that it works with 5.4, thank you!
