### ISSUE TITLE
WebView2 - full screen video mode issue 

### ISSUE THREAD

**Issue by GCX-Monter** [unoplatform/uno#17933]
### Current behavior

On Android, when trying to open a video in full screen (for example, on YouTube), nothing happens. When running on Windows, the video frame stretches but does not switch to full-screen mode.

### Expected behavior

When clicking the button to open a video in full screen, the application should maximize the video window to full screen.

### How to reproduce it (as minimally and precisely as possible)

Open youtube.com or another website with video and try to expand any video to full screen.

### IDE version

Visual Studuo 17.9.1, UNO 5.2

**Comment by jeromelaban** [comment]
Thanks for the report.

Implementing such a feature requires the hosting app to manage layouting the WebView2 control instance to full screen manually, as this is not a webview2 feature. As for the behavior on Android, it may be that the site itself does not enable the "full window" feature in the same way it does on windows.

**Comment by MartinZikmund** [comment]
For full screen windowing of the app please see https://platform.uno/docs/articles/features/windows-ui-xaml-window.html#making-the-window-full-screen
