### ISSUE TITLE
Dark theme does not work for Android

### ISSUE THREAD

**Issue by zipswich** [unoplatform/uno#1794]
## Current behavior

Added RequestedTheme="Dark" to App.xaml, but the background is still white on Android 

## Expected behavior

The background should be dark. 

## How to reproduce it (as minimally and precisely as possible)

https://github.com/zipswich/AppDebugUno

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by zipswich** [comment]
This should do it.  If I remember correctly, UWP template uses it by default, and I removed it at some point when I was porting the project.
Thank you for all the work.

**Comment by MartinZikmund** [comment]
> This should do it. If I remember correctly, UWP template uses it by default, and I removed it at some point when I was porting the project.
> Thank you for all the work.

Hi, has this problem be resolved? Can we close the issue?

**Comment by zipswich** [comment]
@MartinZikmund I am sorry but I have just noticed your post.   Yes, I can confirm it is working now.  I just need to make sure the parent control of each page has `Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"`

**Comment by MartinZikmund** [comment]
> @MartinZikmund I am sorry but I have just noticed your post.   Yes, I can confirm it is working now.  I just need to make sure the parent control of each page has `Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"`

Glad to hear 👍. Hopefully this limitation will be removed soon as well.
