### ISSUE TITLE
VisualState value named "Loading" triggers compile error

### ISSUE THREAD

**Issue by yeahg-dev** [unoplatform/uno#18020]
### Current behavior

using Visual State value named "Loading" in xaml triggers Compile error.

Error Message:
> Operator '+=' cannot be applied to operands of type 'VisualState' and 'lambda expression' [/Users/moonlily/Projects/UnoVisaulStateSample/VisualStateSample/VisualStateSample/VisualStateSample.csproj]

when I commented out part that using "Loading", error has gone. 

Does name "Loading" is reserved word in Uno Platform?

### Expected behavior

Compile successfully when using Visual State value named "Loading" 

### How to reproduce it (as minimally and precisely as possible)

Use Visual State value named "Loading" in xaml like this.

```xaml
  <StackPanel utu:SafeArea.Insets="VisibleBounds"
      Spacing="8"
      HorizontalAlignment="Center"
      VerticalAlignment="Center">
      <VisualStateManager.VisualStateGroups>
            <VisualStateGroup x:Name="CustomStates">
            <!-- This makes compile error -->
            <!-- Error Message: Operator '+=' cannot be applied to operands of type 'VisualState' and 'lambda expression'  -->
                <VisualState x:Name="Loading">
                    <VisualState.Setters>
                         <Setter Target="TextLabel.Foreground" Value="Blue"/>
                    </VisualState.Setters>
                </VisualState>
            <!-- end -->
                <VisualState x:Name="Highlighted"> 
                    <VisualState.Setters>
                        <Setter Target="TextLabel.Foreground" Value="Red"/>
                    </VisualState.Setters>
                </VisualState>
            </VisualStateGroup>
      </VisualStateManager.VisualStateGroups>

      <TextBlock x:Name="TextLabel" AutomationProperties.AutomationId="HelloTextBlock"
          Text="Hello Uno Platform"
          HorizontalAlignment="Center" />
      <Button Content="Change to Highlighted State"
          Click="Button_Click_Highlighted"
          HorizontalAlignment="Center" />
      <Button Content="Change to Loading State"
          Click="Button_Click_Loading"
          HorizontalAlignment="Center" />
  </StackPanel>
```

or

you could download and run Sample project on this [repo](https://github.com/yeahg-dev/UnoVisaulStateSample)

### Workaround

Change State name "Loading" to "Loading2".
this value has compiled well.

### Works on UWP/WinUI

None

### Affected platforms

Android, iOS

**Comment by Youssef1313** [comment]
Thanks for reporting this @yeahg-dev. This is indeed a bug in the XAML generator that will be fixed by #18051
