### ISSUE TITLE
How do I vendor Uno, run my own CI and publish these artifacts internally to my own feeds?

### ISSUE THREAD

**Issue by artemious7** [unoplatform/uno#1802]
## What would you like clarification on:
I followed this guide [Overriding your local NuGet cache](https://github.com/unoplatform/workshops/tree/master/uno-bootcamp/modules/07-Working-with-Uno#overriding-your-local-nuget-cache)

It says:

> Imagine you have an application that references Uno.UI at version v1.45.0 and there's something in that particular version of the Uno Platform that needs to change because it's blocking you from shipping your application to your customers.
> By enabling <UnoNugetOverrideVersion>1.45.0</UnoNugetOverrideVersion> and building from source you'll never be in a situation where you are blocked waiting for pull-requests to be merged and a release to be cut.

Now how do I release my app using my CI in Azure Pipelines together with the Uno.UI I just built?
At this point I'm not ready to use my Uno build in productiuon, however I'd like to benefit from CI builds. And I know nothing of private NuGet feeds. Is it difficult to do?

## Concern?

- [ ] Usage in industry
- [ ] Clarification of capabilities
- [ ] Getting started with Uno
- [ ] Developing with Uno
- [ ] Contributing to the Uno project
- [x] Publishing your application
- [ ] Support
- [ ] Other (please specify):

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

## Anything else we need to know?
Asked here
https://gitter.im/uno-platform/Lobby?at=5d9f81c7fcf7602cc567b197

**Comment by jeromelaban** [comment]
CI Scripts are already available at the repo root (see `.vsts-ci.yml`) and you can use azure [devops private nuget feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops) to publish your custom packages.
