### ISSUE TITLE
[WASM][TextBox][PasswordBox] Control randomly not switching visual state when clicked

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno#18040]
### Current behavior

Sometimes when swiching the focus of `TextBox` / `PasswordBox` the control doesn't go to the right visual state.

https://github.com/user-attachments/assets/5f80bfc4-6723-4ecb-8810-effc2bb28145

### How to reproduce it (as minimally and precisely as possible)

Repro: [WasmVsBlank.zip](https://github.com/user-attachments/files/16765514/WasmVsBlank.zip)

1. Create a new uno app from the blank template
2. Add `TextBox`es / `PasswordBox`es
3. Play clicking them and observe

### Works on UWP/WinUI

Yes

**Comment by Youssef1313** [comment]
When the issue manifests, it's a parent div that received the pointer event rather than the native `input` element. Issue is also still present in 5.4 devs where managed pointers implementation is used.

**Comment by Youssef1313** [comment]
Looks like a regression from https://github.com/unoplatform/uno/pull/16982
