### ISSUE TITLE
[Android] `ms-settings:notifications` wasn't found

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#18080]
### Current behavior

When using the `ms-settings:notifications` special URI with Launcher, the app doesn't launch the desired setting with API 34. I can reproduce this on two different devices.

![image](https://github.com/user-attachments/assets/40471bdc-992a-4c6d-ae12-c1b381d02971)

### Works on UWP/WinUI

Yes

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by agneszitte** [comment]
@morning4coffe-dev, @MartinZikmund is there already something available so QA can test this with latest packages, please?

**Comment by morning4coffe-dev** [comment]
@agneszitte I am not sure how frequently the release works, but my changes are merged on master and I added a sample to SamplesApp (under Launcher) or when the dev package is available anyone should be able to use:
```
await Windows.System.Launcher.LaunchUriAsync(new Uri("ms-settings:notifications"))
```

**Comment by agneszitte** [comment]
> @agneszitte I am not sure how frequently the release works, but my changes are merged on master and I added a sample to SamplesApp (under Launcher) or when the dev package is available anyone should be able to use:

Thanks @morning4coffe-dev for the details. 
@jhanvi03 can you verify it with the uno samples app please. Like @morning4coffe-dev said it is under the "Launcher" section.
Please come back to him if you have more questions or need more details to test it.
