### ISSUE TITLE
Unloading a control which has a opened popup won't close it

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#1809]
## Current behavior
If you remove a `Popup` from the visual tree, the _actual_ popup (i.e. the overlay control) won't disapear

## Expected behavior
It get dismissed like on UWP

## How to reproduce it (as minimally and precisely as possible)
Open a `ComboBox` and navigate while it's open (like in UI tests)

## Environment
Nuget Package: Uno.UI
Package Version(s): 2.0
Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio: _irrelevant_
Relevant plugins: _none_

**Comment by MartinZikmund** [comment]
This is fixed
