### ISSUE TITLE
[WSL] Many "Here" messaging in debug output

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#18108]
### Current behavior

It seems that something in pointer handling on X11 is outputting "Here" messages in debug output:

![image](https://github.com/user-attachments/assets/05726547-96bb-46cf-a04e-54d3783a7199)

### Works on UWP/WinUI

None

**Comment by ramezgerges** [comment]
@MartinZikmund I couldn't find any "Here"s on master. Are you sure this is a problem on master?

**Comment by MartinZikmund** [comment]
It was my branch only 😅 !!
