### ISSUE TITLE
[VS Code] Stuck loading projects

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#18139]
### Current behavior

Plugin forever loading Projects?
I'm noticing that I need to always manually invoke the Select Active Project in the command palette. Otherwise it just stays stuck loading the Projects:
 
![image](https://github.com/user-attachments/assets/be2b51be-7c53-48be-b189-18198d6c1300)

I don't see anything in any of the logs

## Workaround

Reverting C# Dev Kit to 1.9.55 make projects load properly.

Use the Uninstall/Install another version to revert the update:
![image](https://github.com/user-attachments/assets/5f1372e1-a1a3-4e5c-8b0d-d33044cae67e)

**Comment by agneszitte** [comment]
@spouliot let us know if you have some input on this, please

**Comment by agneszitte** [comment]
fyi @jeromelaban seems to happen with latest Uno.Sdk 5.3.108

**Comment by agneszitte** [comment]
> fyi @jeromelaban to happen with latest Uno.Sdk 5.3.108 (cf. @mcNets comment here [#18078 (comment)](https://github.com/unoplatform/uno/discussions/18078#discussioncomment-10562320)) and normally @jhanvi03 was also able to reproduce it with Uno.Sdk 5.3.99 on her side yesterday (see her [comment here](https://github.com/unoplatform/private/issues/514#issuecomment-2334239141))

Seems related to latest VS Code update from yesterday, [August version 1.93](https://code.visualstudio.com/updates/v1_93)

**Comment by dr1rrb** [comment]
Using vs code 1.93.0 and uno extension 0.15.6 I've no issue on my side

**Comment by mcNets** [comment]
@agneszitte yes, I did.

**Comment by dr1rrb** [comment]
FYI Still failing with latest branch of our vs code extension (including with 5.3.31)

**Comment by agneszitte** [comment]
Also I just remembered that VS Code auto update by default if the default settings are not changed
https://code.visualstudio.com/Docs/supporting/faq#_how-do-i-opt-out-of-vs-code-autoupdates

**Comment by jeromelaban** [comment]
It's worth noting that this particular UI is not an Uno feature, and is provided by devkit, it's likely we won't be able to fix anything there, and will have to wait for the devkit team to fix it.

**Comment by jhanvi03** [comment]
We have tested with older/previous VS code version and C# DevKit version and issue seems to be with new version of C# Devkit.

| VS Code Version | C#DevKit Version | Project Load Issue |
|------------------|-------------------|-------------------|
| 1.92.2 | 1.10.16 | Exist     |
| 1.92.2 | 1.9.55 | Does Not Exist   |
| 1.93.0 | 1.10.16 | Exist     |
| 1.93.0 | 1.9.55 | Does Not Exist   |

**Comment by spouliot** [comment]
I filed an issue with MS last week when using a pre release version of dev kit.

Looks like they have gone ahead with the release without fixing the issue :(

**Comment by jeromelaban** [comment]
@spouliot could you link the issue please?

**Comment by mcNets** [comment]
I got the issue with 5.3.108, but if I downgrade to 5.3.99 it runs with no other actions.

I'm on 1.93.0-insider

**Comment by spouliot** [comment]
> @spouliot could you link the issue please?

https://github.com/microsoft/vscode-dotnettools/issues/1391

**Comment by spouliot** [comment]
Updating the Microsoft C# DevKit to version `1.11.9 (pre-release)` will fix the issue.

**Comment by spouliot** [comment]
Updating Microsoft C# DevKit to stable 1.11.14 works fine, closing.
