### ISSUE TITLE
Visual Studio stops responding when loading large solutions

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno#18133]
### Current behavior

VS lately is misbehaving, every time I try to open one of those "larger" solutions (TestHarness, Toolkit) it stops responding while preparing the solution:

![image](https://github.com/user-attachments/assets/740d908f-efe6-4ade-865c-d18b67f97b86)

I started disabling some extensions installed on VS to see if anything would change and after disabling the "Uno Platform" extension the solution finally loaded. Re-enabling it makes the solution hanging again. 

However, once in a while, randomly the solution loads with the "Uno Platform" extension enabled.

I use **Visual Studio Community 2022 (17.11.2)**.

### Works on UWP/WinUI

None

### IDE

Visual Studio 2022

### IDE version

17.11.2

### Anything else we need to know?

I have net9 preview, would that influence this issue somehow? Should I uninstall it?

**Comment by agneszitte** [comment]
@eriklimakc can you test with the latest Uno Platform VS Extension version 5.3.23 that was just published, please 
To let us know if you have the same issues with it. Thanks in advance for the feedback.
![image](https://github.com/user-attachments/assets/1e66179a-f699-4fad-b929-49404936c6f1)

**Comment by agneszitte** [comment]
> @eriklimakc can you test with the latest Uno Platform **VS Extension version 5.3.23** that was just published, please To let us know if you have the same issues with it. Thanks in advance for the feedback. 

Tests results from @eriklimakc with latest **VS VSIX 5.3.23**:

>Here are my attempts:
 
>TestHarness
> 1. Stopped responding
> 2. Stopped responding
> 3. Stopped responding
> 4. Stopped responding
> 5. Worked
> 6. Worked
> 7. Worked
> 8. Launched the app (to see if would change anything) > Closed and re-opened VS and it Worked
>
> After TestHarness I tried with Uno.Toolkit
> 1. Stopped responding
> 2. Stopped responding
> 3. Stopped responding
> 4. Stopped responding
> 5. Stopped responding
> 6. Stopped responding
> 7. Stopped responding
> 8. Tried git clean -fdx but still Stopped responding
>
> After trying Uno.Toolkit I went to try TestHarness again and it stopped responding.

**Comment by jeromelaban** [comment]
This issue is related to this visual studio issue: https://developercommunity.visualstudio.com/t/VS2022-17112-Hangs-on-Preparing-solut/10738726

**Comment by agneszitte** [comment]
**⁠[VS2022 17.11.2 Hangs on "Preparing solution"](https://developercommunity.visualstudio.com/t/VS2022-17112-Hangs-on-Preparing-solut/10738726)** should be fixed in: Visual Studio 2022 version **17.11.4**

Should be tested again with TestHarness or Toolkit

**Comment by jeromelaban** [comment]
This was reported as fixed by other users.
