### ISSUE TITLE
Maui version mismatch for a project created by the Uno wizard

### ISSUE THREAD

**Issue by ForkBug** [unoplatform/uno#18141]
### Current behavior

1.Create a project by uno wizard. Check Maui embedding.
2.Change $(MauiVersion) in Directory.Packages.props to "8.0.82"
3. Build the project. Failed with

`
error NU1605: Warning As Error: Detected package downgrade: Microsoft.Maui.Controls from 8.0.82 to 8.0.71. Reference the package directly from the project to select a different version. 
error NU1605:  UnoApp2 -> UnoApp2.MauiControls -> Microsoft.Maui.Controls (>= 8.0.82) 
error NU1605:  UnoApp2 -> Microsoft.Maui.Controls (>= 8.0.71)
`

### Expected behavior

Build success.

### How to reproduce it (as minimally and precisely as possible)

The code generated by the Uno wizard failed to be compiled

### Workaround

No. 

### Works on UWP/WinUI

None

### IDE

Visual Studio

### IDE version

2022

### Relevant plugins

Most recently uno

### Anything else we need to know?

It's ridiculous.

**Comment by jeromelaban** [comment]
Thanks for the report. 

It see that a recent workload update breaks this, you can [force the version](https://platform.uno/docs/articles/features/using-the-uno-sdk.html?tabs=3rd-party-packages#implicit-packages) this way:

```xml
<PropertyGroup>
   <MauiVersion>8.0.82</MauiVersion>
</PropertyGroup>
```

**Comment by ForkBug** [comment]
Where to place this? Placing it in the .csproj file or Directory.Build.props doesn't work. 
It seems like <Project Sdk="Uno.Sdk"> doesn't use Directory.Build.props.
