### ISSUE TITLE
`LocaleLanguage` Glyph missing

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#18148]
### Current behavior

&#xF2B7; is missing on all Uno targets.

### How to reproduce it (as minimally and precisely as possible)

http://playground.platform.uno/#dd0429c4

### Works on UWP/WinUI

Yes

**Comment by mcNets** [comment]
```
<FontIcon Glyph="&#xF2B7;" />
```

**Comment by NVLudwig** [comment]
This will be fixed by #https://github.com/unoplatform/uno.fonts/issues/47

**Comment by agneszitte** [comment]
@MartinZikmund, @morning4coffe-dev changes for https://github.com/unoplatform/uno.fonts/pull/50 were backported /released and available with latest stable **Uno.Fonts 2.4.5**

**Comment by jhanvi03** [comment]
Tested with sdk and Template 5.3.112 and the issue still persist:

**Code:**
`<FontIcon FontFamily="{ThemeResource SymbolThemeFontFamily}" Glyph="&#xF2B7;"/>`

![Screenshot 2024-09-20 at 11 23 48 AM](https://github.com/user-attachments/assets/3e4bf676-3d9c-4a61-8a14-d08d68e7611f)

**Comment by agneszitte** [comment]
@MartinZikmund uno.fonts version in uno should be normally updated to latest 2.4.5 stable version as well
https://github.com/search?q=repo%3Aunoplatform%2Funo%20%222.4.0%22&type=code

**Comment by agneszitte** [comment]
Re-opening issue based on @MartinZikmund's comment: https://github.com/unoplatform/uno.fonts/issues/47#issuecomment-2371365251

**Comment by agneszitte** [comment]
@MartinZikmund I will let you verify quickly a last time on your side all the icons for #18148 and https://github.com/unoplatform/uno.fonts/issues/47. This is to ensure that no icons are missing based on the latest changes. 
Once everything is properly addressed, feel free to close both issues, and we can proceed with a fresh round of QA.

**Comment by MartinZikmund** [comment]
This glyph is now working correctly.

**Comment by jhanvi03** [comment]
Tested on playground able to see the icon for `<FontIcon Glyph="&#xF2B7;" />`
![Image](https://github.com/user-attachments/assets/565a462d-c4d7-42da-9613-ac8977b30467)
