### ISSUE TITLE
PointerReleased is not invoked under certain circumstances with Android Head

### ISSUE THREAD

**Issue by zipswich** [unoplatform/uno#1815]
## Current behavior
Background is needed for PointerReleased to work on Android in the following case.
```
        <Border 
            Grid.Row="1"
            BorderThickness="2" 
            BorderBrush="Red"
            PointerReleased="border_PointerReleased" 
            >
            <!--Background="Transparent" is needed for PointerReleased to work on Android -->
            <Image Source="Assets\StoreLogo.png"
            />
        </Border>
```

## Expected behavior

It should not require Border to have Background for its PointerReleased to work in this case

## How to reproduce it (as minimally and precisely as possible)

https://github.com/zipswich/AppDebugUno

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.0.0-dev.3314

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Potentially related to https://github.com/unoplatform/uno/pull/1256

**Comment by Youssef1313** [comment]
I couldn't reproduce.

https://user-images.githubusercontent.com/31348972/130417424-cbd0e18b-1fa7-4b41-a4d4-f7d2f2d9783e.mp4

Probably this was fixed already.

**Comment by jeromelaban** [comment]
Let's close then, thanks!
