### ISSUE TITLE
[skia MacOS] GridSplitter render a "?" instead of "||"

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#18191]
### Current behavior

On MacOS, it looks like this

<img width="181" alt="Screenshot 2024-09-12 at 9 49 38 AM" src="https://github.com/user-attachments/assets/7d07da42-0c68-4315-b387-fbecab1932b6">

FYI: It looks okay on Skia Desktop

### Expected behavior

It should look like this

![image](https://github.com/user-attachments/assets/96974180-3ee9-453d-b7e9-18562dd2f648)

### How to reproduce it (as minimally and precisely as possible)

Sample project: [UnoGridSplitterApp.zip](https://github.com/user-attachments/files/16980478/UnoGridSplitterApp.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Skia (macOS)

### IDE

Visual Studio 2022

**Comment by ArchieCoder** [comment]
My colleague on her Linux laptop (her language is Chinese).

It looks like a font issue that the GridSplitter uses a font instead of an image.

![image](https://github.com/user-attachments/assets/68c3e432-e434-4052-94b5-d0b8d31f7672)

**Comment by jeromelaban** [comment]
Thanks for the report. The GridSplitter control is supposed to be using the FontIcon for rendering this particular content. You may be able to override the default template of this control to ensure that it uses the proper symbols font: "ms-appx:///Uno.Fonts.Fluent/Fonts/uno-fluentui-assets.ttf"

That being said, depending on how the template is made in the community toolkit we may be able to set an automatic override so that it always uses our font instead of falling back to a system font. (/cc @MartinZikmund)

**Comment by MartinZikmund** [comment]
I checked the latest sources and it seems that now the sizer controls are actually rendering a plain `Rectangle` instead:|

![image](https://github.com/user-attachments/assets/e7d0c7b3-612f-4dbe-8bac-094afbf65049)

@ArchieCoder are you using the latest Windows Community Toolkit packages?

**Comment by ArchieCoder** [comment]
@MartinZikmund There was nothing in the nuget Update section, but I saw this.

<img width="813" alt="image" src="https://github.com/user-attachments/assets/0d76efc0-274c-41ae-bc9a-fa9358d116d7">

I removed the deprecated nugets and added these, but now the compiler is unhappy.

![image](https://github.com/user-attachments/assets/2e7b741c-cde6-41c4-a67e-6bb1479f8b9a)

**Comment by agneszitte** [comment]
> @MartinZikmund There was nothing in the nuget Update section, but I saw this.
> I removed the deprecated nugets and added these, but now the compiler is unhappy.

Related discord discussion: [WCT errors](https://discord.com/channels/1182775715242967050/1285638155743002757)

**Comment by ArchieCoder** [comment]
After some gymnastic, I was able to migrate to 8.0. I can confirm that the GridSplitter renders nicely with MacOS. I suppose it will on Linux. Closing the issue. Thanks @MartinZikmund and @agneszitte.
