### ISSUE TITLE
New applications created using wizard has "warning XA4218" on build for Android

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#18204]
### Current behavior

Create new application using VS wizard, selecting the Blank preset.
Rebuild all targets

```
1>obj\Debug\net8.0-android\android\AndroidManifest.xml : warning XA4218: Unable to find //manifest/application/uses-library at path: C:\Program Files (x86)\Android\android-sdk\platforms\android-34\optional\androidx.window.extensions.jar
1>obj\Debug\net8.0-android\android\AndroidManifest.xml : warning XA4218: Unable to find //manifest/application/uses-library at path: C:\Program Files (x86)\Android\android-sdk\platforms\android-34\optional\androidx.window.sidecar.jar
```

### Expected behavior

There should be no warnings or errors on initial build after creating a new Uno application

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
Fixed in net9.

**Comment by Darsh0307** [comment]
@jeromelaban  , I was just wondering that i cant test this one since .net9 Preview is breaking , and not allowing me test.

**Comment by jeromelaban** [comment]
@Darsh0307 We are waiting for net9 RC2.
