### ISSUE TITLE
[Windows] App crashes when static DoubleCollection is used more than once

### ISSUE THREAD

**Issue by kucint** [unoplatform/uno#18201]
### Current behavior

create a simple app, that uses `DoubleCollection`.
if `DoubleCollection` is referenced more than ones, it causes app to crash.

I suppose the issue has nothing to do with `DoubleCollection`, but rather is related to static instantiation. I mean, using static object of another types will probably as well cause problems.

This issue occurs only on `net8.0-windows`.
`net8.0-desktop` is not affected.

### Expected behavior

using static `DoubleCollection` shall work fine.

### How to reproduce it (as minimally and precisely as possible)

create a simple app, that uses `DoubleCollection`.
if `DoubleCollection` is referenced more than ones, it causes app to crash.

```cs
public sealed partial class MainPage : Page
{
    public MainPage()
    {
        this
            .Background(ThemeResource.Get<Brush>("ApplicationPageBackgroundThemeBrush"))
            .Content(new StackPanel()
            .VerticalAlignment(VerticalAlignment.Center)
            .HorizontalAlignment(HorizontalAlignment.Center)
            .Children(
                new TextBlock()
                .Text("Hello Uno Platform!"),
                MyEllipse(),    // first instance works fine with static and local instance of DoubleCollection
                MyEllipse()     // second instance crashes when using static instance of DoubleCollection
            ));
    }

    private static readonly DoubleCollection DashedLine = [3, 2];

    private Ellipse MyEllipse() => new Ellipse()
        .Width(20)
        .Height(20)
        .StrokeThickness(1)
        .Stroke(Colors.Black)
//      .StrokeDashArray(new DoubleCollection() { 3, 2 })   // local instance works always fine
        .StrokeDashArray(DashedLine);                       // crashes when method is called twice
}
```

App crashes with following exception:
_Exception thrown: 'System.ArgumentException' in WinRT.Runtime.dll
An exception of type 'System.ArgumentException' occurred in WinRT.Runtime.dll but was not handled in user code_

repro: [UnoAppMystery.zip](https://github.com/user-attachments/files/16994155/UnoAppMystery.zip)

### Workaround

replace static instances of `DoubleCollection` with local instances

### Works on UWP/WinUI

None

### NuGet package version(s)

Version:
`Uno.Sdk": "5.3.108`

### Affected platforms

Windows (WinAppSDK)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. 

Considering this is a WinUI API issue, we may not be able to fix this issue, though we may be able to find a workaround for that particular scenario.

**Comment by kucint** [comment]
@jeromelaban thanks for investigating it.
so I have to use local instances of `DoubleCollection` rather than static instances.
it is OK.
