### ISSUE TITLE
[NPE][Mac]Text are not loading properly.

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno#18202]
### Current behavior

The font change seems to be not reflected on mac. Works fine on windows.
<img width="1369" alt="image" src="https://github.com/user-attachments/assets/8501c7ec-321c-4706-a161-918b6ab35e2d">

### Expected behavior

The font should not be Times New Roman and should match with Windows(Segoe UI).
<img width="840" alt="image" src="https://github.com/user-attachments/assets/da9b46ec-bf6a-40ad-8701-df1eae3ec938">

### How to reproduce it (as minimally and precisely as possible)

1. Open NPE on Chrome.
2. Observe the Fonts.

### Works on UWP/WinUI

None

### Affected platforms

Mac Catalyst

**Comment by jeromelaban** [comment]
This is a known issue, though it should have been fixed in the canary since the introduction of the default fonts support.

**Comment by jhanvi03** [comment]
Test Pass on Mac WASM with Version:
Package	Referenced version	Updated version
Uno.Monaco.Editor	[2.0.0-dev.50](https://www.nuget.org/packages/Uno.Monaco.Editor/2.0.0-dev.50)	[2.0.0-dev.60](https://www.nuget.org/packages/Uno.Monaco.Editor/2.0.0-dev.60)
Uno.Sdk	[5.2.175](https://www.nuget.org/packages/Uno.Sdk/5.2.175)	[5.5.0-dev.21](https://www.nuget.org/packages/Uno.Sdk/5.5.0-dev.21)
Package | Referenced version | Updated version
-- | -- | --
Uno.Monaco.Editor | 2.0.0-dev.50 | 2.0.0-dev.60
Uno.Sdk | 5.2.175 | 5.5.0-dev.21

Safari:
<img width="1252" alt="image" src="https://github.com/user-attachments/assets/33a2e02d-dd74-4508-89d6-14fecb578c8f">

Chrome:
<img width="1177" alt="image" src="https://github.com/user-attachments/assets/cf094f62-e6d0-4d66-8a6b-d1bf8f03431e">
