### ISSUE TITLE
`GridSplitter` not working

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#18215]
Greatly appreciated the quick response!   I did just that and conclude that is too simple, once you create a new project just replace the MainPage with a grid (3 columns) and try to put the GridSplitter in the middle column.  I did found that the current version (8.1.240821) you will not be able to find the expected splitters in the namespace, but as soon as you change to the previous version (8.0.240109) you will be able to see the expected splitters...   Can you please take a look on why the "current version" is not surfacing the Sizer controls?

_Originally posted by @datovy-edam in https://github.com/unoplatform/uno/discussions/18151#discussioncomment-10635952_

**Comment by agneszitte** [comment]
@MartinZikmund I will take a quick look as I am testing WCT samples at the moment while adjusting the documentation

**Comment by datovy-edam** [comment]
Note that in **version (8.0.240109)** the splitter works as expected under the Windows platform but **not under the WebAssembly platform**!  Still, all other rendered components (not the splitters) work as expected and look identical to each other...  very nice.

On another subject:
Also, the DockPanel works on the Windows platform and not under WebAssembly.  I already switch and use a StackPanel in place of the DockPanel, but it does not provide the visual I like... But works fine in both platforms.

Hope to see the splitters issues resolved soon...

**Comment by MartinZikmund** [comment]
@datovy-edam thank you for the information, we will investigate this and let you know ASAP.

**Comment by MartinZikmund** [comment]
@morning4coffe-dev can you please validate `DockPanel` and `GridSplitter` on WASM?

**Comment by morning4coffe-dev** [comment]
@MartinZikmund, @datovy-edam
I have tested this with both 8.0.240109, where the controls don't render at all on any Uno targets, and with the latest stable version, 8.1.240916, where everything works as expected across all platforms.

![image](https://github.com/user-attachments/assets/7d13d9eb-1e26-4e9f-8d1e-1269284679a8)

@datovy-edam
Are you able to use the latest stable version? There are some requirements to make this work with Windows as well. If you need help, feel free to check out my sample ([WCTControlsSample.zip](https://github.com/user-attachments/files/17553868/WCTControlsSample.zip)) and compare the .csproj file with your project.

**Comment by jeromelaban** [comment]
Thanks, let's close then!

**Comment by datovy-edam** [comment]
Titl and others,

Greatly appreciate the prompt attention, I know that you guys are very
busy... I ran the Titl provided sample project and it works as expected in
WebAssembly, I also tried desktop but it does not work there, and when I
try to select "WinAppSDK Unpackaged" it always reverts to "... Packaged"
and I couldn't test it.

I will try updating my project and see how it goes...  Again great to hear
from your team!  Uno Platform is great!!

**Comment by jeromelaban** [comment]
For the unpackaged not being selectable: https://aka.platform.uno/wasdk-maui-debug-profile-issue

**Comment by datovy-edam** [comment]
I finally got it working for both WebAssembly and WinAppSDK!

I commented out the DockPanel sample code that it was not finding under
WinAppSDK and all is now working.

Thank you guys for the support...  I hope to see more of the Uno Platform
coming-up...

Eduardo
