### ISSUE TITLE
[Calculator][WASM] URL on home page doesn't work

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno#18229]
### Current behavior

'Try Uno Platform' link on the home page and from the information page is not working. URL does work on clicking some part from the entire text.
![Screenshot 2024-09-17 at 11 46 47 AM](https://github.com/user-attachments/assets/33fa7b81-3081-438d-8df5-331f6988077a)
![Screenshot 2024-09-17 at 11 46 19 AM](https://github.com/user-attachments/assets/904aad4b-79b4-47d6-8c03-288974efbafd)

### Expected behavior

The URL should navigate user to Uno page on clicking anywhere from the marked URL part.

### How to reproduce it (as minimally and precisely as possible)

1. Open Calculator Canary on web.
2. Click on 'Try Uno Platform' from the home page
3. Observe the link will not navigate to Uno page.
4. Click on 'i' icon, first icone from top right.
5. Click on 'Windows Calculator', 'Uno Platform' & 'Try Uno Platform' URLs.
6. Observe the link will not navigate to the respective page.

### Works on UWP/WinUI

None

### Relevant plugins

<br class="Apple-interchange-newline">Package	Referenced version	Available version
Uno.Core.Extensions.Disposables	[4.0.1](https://www.nuget.org/packages/Uno.Core.Extensions.Disposables/4.0.1)	[4.0.0-dev.7](https://www.nuget.org/packages/Uno.Core.Extensions.Disposables/4.0.0-dev.7)
Uno.UI.Sample.Banner	[1.45.0-dev.64](https://www.nuget.org/packages/Uno.UI.Sample.Banner/1.45.0-dev.64)	[1.45.0-dev.64](https://www.nuget.org/packages/Uno.UI.Sample.Banner/1.45.0-dev.64)
Package | Referenced version | Available version
-- | -- | --
Uno.Core.Extensions.Disposables | 4.0.1 | 4.0.0-dev.7
Uno.UI.Sample.Banner | 1.45.0-dev.64 | 1.45.0-dev.64

Package	Referenced version	Updated version
Uno.Extensions.Logging.OSLog	[1.4.0](https://www.nuget.org/packages/Uno.Extensions.Logging.OSLog/1.4.0)	[1.9.0-dev.2](https://www.nuget.org/packages/Uno.Extensions.Logging.OSLog/1.9.0-dev.2)
Uno.Extensions.Logging.OSLog	[1.3.0-dev.3](https://www.nuget.org/packages/Uno.Extensions.Logging.OSLog/1.3.0-dev.3)	[1.9.0-dev.2](https://www.nuget.org/packages/Uno.Extensions.Logging.OSLog/1.9.0-dev.2)
Uno.Extensions.Logging.WebAssembly.Console	[1.6.0](https://www.nuget.org/packages/Uno.Extensions.Logging.WebAssembly.Console/1.6.0)	[1.9.0-dev.2](https://www.nuget.org/packages/Uno.Extensions.Logging.WebAssembly.Console/1.9.0-dev.2)
Uno.Fonts.OpenSans	[2.4.0](https://www.nuget.org/packages/Uno.Fonts.OpenSans/2.4.0)	[2.5.0-dev.9](https://www.nuget.org/packages/Uno.Fonts.OpenSans/2.5.0-dev.9)
Uno.UI	[4.2.0-dev.267](https://www.nuget.org/packages/Uno.UI/4.2.0-dev.267)	[5.5.0-dev.336](https://www.nuget.org/packages/Uno.UI/5.5.0-dev.336)
Uno.UI	[5.3.90](https://www.nuget.org/packages/Uno.UI/5.3.90)	[5.5.0-dev.336](https://www.nuget.org/packages/Uno.UI/5.5.0-dev.336)
Uno.UI.Adapter.Microsoft.Extensions.Logging	[5.3.90](https://www.nuget.org/packages/Uno.UI.Adapter.Microsoft.Extensions.Logging/5.3.90)	[5.5.0-dev.336](https://www.nuget.org/packages/Uno.UI.Adapter.Microsoft.Extensions.Logging/5.5.0-dev.336)
Uno.UI.Lottie	[5.3.90](https://www.nuget.org/packages/Uno.UI.Lottie/5.3.90)	[5.5.0-dev.336](https://www.nuget.org/packages/Uno.UI.Lottie/5.5.0-dev.336)
Uno.UI.RemoteControl	[5.3.90](https://www.nuget.org/packages/Uno.UI.RemoteControl/5.3.90)	[5.5.0-dev.336](https://www.nuget.org/packages/Uno.UI.RemoteControl/5.5.0-dev.336)
Uno.UI.Skia.Gtk	[5.3.90](https://www.nuget.org/packages/Uno.UI.Skia.Gtk/5.3.90)	[5.5.0-dev.336](https://www.nuget.org/packages/Uno.UI.Skia.Gtk/5.5.0-dev.336)
Uno.UI.WebAssembly	[5.3.90](https://www.nuget.org/packages/Uno.UI.WebAssembly/5.3.90)	[5.5.0-dev.336](https://www.nuget.org/packages/Uno.UI.WebAssembly/5.5.0-dev.336)
Uno.Wasm.Bootstrap	[8.0.20](https://www.nuget.org/packages/Uno.Wasm.Bootstrap/8.0.20)	[9.0.0-dev.120](https://www.nuget.org/packages/Uno.Wasm.Bootstrap/9.0.0-dev.120)
Uno.Wasm.Bootstrap.DevServer	[8.0.20](https://www.nuget.org/packages/Uno.Wasm.Bootstrap.DevServer/8.0.20)	[9.0.0-dev.120](https://www.nuget.org/packages/Uno.Wasm.Bootstrap.DevServer/9.0.0-dev.120)
Package | Referenced version | Updated version
-- | -- | --
Uno.Extensions.Logging.OSLog | 1.4.0 | 1.9.0-dev.2
Uno.Extensions.Logging.OSLog | 1.3.0-dev.3 | 1.9.0-dev.2
Uno.Extensions.Logging.WebAssembly.Console | 1.6.0 | 1.9.0-dev.2
Uno.Fonts.OpenSans | 2.4.0 | 2.5.0-dev.9
Uno.UI | 4.2.0-dev.267 | 5.5.0-dev.336
Uno.UI | 5.3.90 | 5.5.0-dev.336
Uno.UI.Adapter.Microsoft.Extensions.Logging | 5.3.90 | 5.5.0-dev.336
Uno.UI.Lottie | 5.3.90 | 5.5.0-dev.336
Uno.UI.RemoteControl | 5.3.90 | 5.5.0-dev.336
Uno.UI.Skia.Gtk | 5.3.90 | 5.5.0-dev.336
Uno.UI.WebAssembly | 5.3.90 | 5.5.0-dev.336
Uno.Wasm.Bootstrap | 8.0.20 | 9.0.0-dev.120
Uno.Wasm.Bootstrap.DevServer | 8.0.20 | 9.0.0-dev.120

**Comment by jeromelaban** [comment]
This likely stopped working recently. @ramezgerges could you take a look?

**Comment by Youssef1313** [comment]
It's likely a regression from managed Wasm pointers

**Comment by jhanvi03** [comment]
QA verified: Able to access the URLs
https://github.com/user-attachments/assets/64bd7729-aa6e-4b20-b625-bf27118688ee


Version:
Package	Referenced version	Available version
Uno.Core.Extensions.Disposables	[4.0.1](https://www.nuget.org/packages/Uno.Core.Extensions.Disposables/4.0.1)	[4.0.0-dev.7](https://www.nuget.org/packages/Uno.Core.Extensions.Disposables/4.0.0-dev.7)
Uno.UI.Sample.Banner	[1.45.0-dev.64](https://www.nuget.org/packages/Uno.UI.Sample.Banner/1.45.0-dev.64)	[1.45.0-dev.64](https://www.nuget.org/packages/Uno.UI.Sample.Banner/1.45.0-dev.64)
Uno.Wasm.Bootstrap	[9.0.0-dev.296](https://www.nuget.org/packages/Uno.Wasm.Bootstrap/9.0.0-dev.296)	[9.0.0-dev.122](https://www.nuget.org/packages/Uno.Wasm.Bootstrap/9.0.0-dev.122)
Package | Referenced version | Available version
-- | -- | --
Uno.Core.Extensions.Disposables | 4.0.1 | 4.0.0-dev.7
Uno.UI.Sample.Banner | 1.45.0-dev.64 | 1.45.0-dev.64
Uno.Wasm.Bootstrap | 9.0.0-dev.296 | 9.0.0-dev.122
