### ISSUE TITLE
MVVM lifecycle discrepancy

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#18228]
[UnoTextBoxBugDemo.zip](https://github.com/user-attachments/files/17030430/UnoTextBoxBugDemo.zip)
I have created a simple reproduction case for the TextBoxbug caused by this.

Enter a name and then go to second page
<img width="307" alt="image" src="https://github.com/user-attachments/assets/ff9b9b5b-562f-47b3-a496-ee1565f94665">
On the second page, the text overlaps the header. I need to "move" the mouse over the TextBox to fix it!<img width="291" alt="image" src="https://github.com/user-attachments/assets/c1eea812-ff2c-488f-a3ec-5cd74b942f2f">
<img width="299" alt="image" src="https://github.com/user-attachments/assets/ddefb454-c98f-4e84-a878-7ff46ac37d4e">

This will happen with all the TextBoxes. Try running it com Desktop or WebAssembly.

If you run it with WinAppSdk, the second screen will not open and will crash with an error.
<img width="757" alt="image" src="https://github.com/user-attachments/assets/abe69d7b-cd4f-4f66-9393-2688e4074518">

_Originally posted by @wagenheimer in https://github.com/unoplatform/uno/discussions/18222#discussioncomment-10671931_

**Comment by wagenheimer** [comment]
Using the same repro example, we encountered the same TextBox bug on Android, along with an additional error: "System.InvalidOperationException: 'The dependency property system should not be accessed from a non-UI thread.'"

**Comment by kazo0** [comment]
Looks to be similar to https://github.com/unoplatform/Uno.Themes/issues/1472

We will double check that latest stable Uno Material fixes this issue as well

**Comment by kazo0** [comment]
@MartinZikmund Would you be able to re-upload the sample .zip but zip the root folder of the solution? This .zip is missing the .sln and the global.json/directory.packages.props/directory.props/etc.

**Comment by wagenheimer** [comment]
@kazo0 Here is it.
[UnoTextBoxBugDemo.zip](https://github.com/user-attachments/files/17045854/UnoTextBoxBugDemo.zip)

**Comment by wagenheimer** [comment]
@kazo0 Here is it! Sorry for the missing files.
[UnoTextBoxBugDemo.zip](https://github.com/user-attachments/files/17045867/UnoTextBoxBugDemo.zip)

**Comment by Kunal22shah** [comment]
@wagenheimer This has been fixed in the latest packages for Uno.Material.WinUI. You should be able to use the latest stable packages for Material by placing this in your .csproj

```
<PropertyGroup>
    <UnoThemesVersion>5.1.9</UnoThemesVersion>
</PropertyGroup>
 ```
There should soon be a new Uno.Sdk 5.3.x version published that will include the latest Uno Material stable version

I tested the same with your Demo app

**Comment by wagenheimer** [comment]
It appears to be fixed now. Thank you!

**Comment by agneszitte** [comment]
> It appears to be fixed now. Thank you!

Thanks a lot for the confirmation @wagenheimer. I am closing this issue but I will update it with the related next uno.sdk 5.3 stable version that will contain the fix when it will be released

**Comment by agneszitte** [comment]
> > It appears to be fixed now. Thank you!
> 
> Thanks a lot for the confirmation @wagenheimer. I am closing this issue but I will update it with the related next Uno.Sdk 5.3.x stable version that will contain the fix when it will be released

Hi @wagenheimer, the fix is available starting with **Uno.Sdk 5.3.112**. 
(You will be able to remove the specific Uno Themes version `<UnoThemesVersion>5.1.9</UnoThemesVersion>`)
