### ISSUE TITLE
The SamplesApp branding is not consistent

### ISSUE THREAD

**Issue by HanamiM** [unoplatform/uno#1823]
## What would you like to be added:

Have the samples app name the same across all platforms.

## Why is this needed:

Better contributor experience.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by HanamiM** [comment]
@ghuntley Would "Uno Samples" be an appropriate name? @MartinZikmund will guide me through submitting this issue.

**Comment by ghuntley** [comment]
Yup "Uno Samples" is appropriate. Thanks Martin for helping!
