### ISSUE TITLE
[skia MacOS] Variable font not working

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#18232]
### Current behavior

I thought the variable font was working as expected, but it does not work when running on MacOS. Details are in the image.

<img width="1246" alt="image" src="https://github.com/user-attachments/assets/ec5b6a8e-f7cd-400d-810b-64b511669c6c">

My font is defined as this:

            <FontFamily
                x:Key="MainFont">
                ms-appx:///Assets/Fonts/Inter.ttf#Inter
            </FontFamily>

For now, it works on Skia Desktop / Linux and WinUI.

### Expected behavior

All platforms should look the same

### How to reproduce it (as minimally and precisely as possible)

Here is the Inter font file (found on Google Font site)
[Inter.zip](https://github.com/user-attachments/files/17034063/Inter.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Skia (macOS)

### IDE

Visual Studio Code

**Comment by ArchieCoder** [comment]
CC @Youssef1313 since you have worked with me on this previously.

**Comment by jeromelaban** [comment]
@ArchieCoder thanks for the report. Note that in order for variable fonts to work, you need to specify a manifest. Have you created that manifest?

**Comment by ArchieCoder** [comment]
@jeromelaban I'm in shock! First, you are right, I forgot the Inter.ttf.manifest. The shocking part is without the manifest file, my image provided in the git issue is the opposite -> **the MacOS shows the font correctly**, but the other platforms WinUI/Skia Linux/Skia Desktop are **not** correct. I'm obviously very confused.

Is this the way to declare the font name in XAML? I have "Inter.tff" even if the file does not exist.

            <FontFamily
                x:Key="MainFont">
                ms-appx:///Assets/Fonts/Inter.ttf#Inter
            </FontFamily>
            
            
![image](https://github.com/user-attachments/assets/00c01498-2306-4c11-865a-ab16963c3868)

Look at the "c" in quick with the Font viewer

![image](https://github.com/user-attachments/assets/73867716-8844-4226-b3da-82d34094d1b3)

**Comment by ArchieCoder** [comment]
@jeromelaban My bad again, I was missing the original "Inter.tff" file the one without -Regular, -Bold, etc. All platforms look the same. Apologize the the false alarm. There is still a mystery around the manifest file, but now all is good.
