### ISSUE TITLE
[Discussion] XamlIL as xaml compilation backend

### ISSUE THREAD

**Issue by maxkatz6** [unoplatform/uno#1827]
##  What would you like to be added:
This issue is just to tell you about the existence of XamlIL.
It could be good for Uno, but it also could be unnecessary or wasteful.

## Why is this needed:
- XamlIL is [faster](https://twitter.com/wieslawsoltes/status/1094612908351410177), than System.Xaml
- Produces IL instead of C#/VB, so potentially can be used with F#
- Should be [more linkable](https://github.com/AvaloniaUI/Avalonia/pull/2734#issuecomment-540706095) and useful for WASM
- For more consistency with [Avalonia](https://github.com/AvaloniaUI/Avalonia) (at least on Xaml stage) 

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

## Anything else we need to know?
I am not experienced with XamlIL, so can't help with questions.
But you can create issue on https://github.com/kekekeks/XamlIl/issues

**Comment by jeromelaban** [comment]
Thank you for initiating the discussion!

At this point, the way Uno generates C# is tied to lots of tricks made to perform compile time /  runtime optimizations (or legacy shortcuts in some cases), and replacing it is not a small task.

We are currently removing some of those shortcuts, but I'm not sure XamlIl will be a solution in mid term, as we're still waiting to see where Microsoft is going to go with WinUI 3.0, particularly with regards to the XBF file format.

As for generating IL or C# from XAML, this is a path that is not always interesting. Generating code adds significant weight of the final binary (whichever the platform) when using mono's AOT, and it also has cold-path runtime performance implications. Loading an intermediate binary format may be still interesting for the overall performance. Again, with this side of the problem, we'll have to make validations using XBF loading.

Also, I'm not familiar enough with the XamlIl parser, but the XAML used by UWP is a bit different from the one used by WPF, and there may be some portions that may not yet be compatible. More validation would be needed there.

**Comment by stevenbrix** [comment]
> We are currently removing some of those shortcuts, but I'm not sure XamlIl will be a solution in mid term, as we're still waiting to see where Microsoft is going to go with WinUI 3.0, particularly with regards to the XBF file format.

@jeromelaban I swear the stars are aligning! I've been looking at XamlIl for WinUI this past week, we've been wanting to re-architect our tooling and build something that is very similar to XamlIl. I would doubt XBF is going anywhere, we can't depend on IL since we have C++ customers. We've also heard from customers that being able to debug code-behind is helpful, especially for compiled bindings, so generating straight IL sounds possible problematic. But I don't feel super strongly there, the fact that it gets F# for free is great :)
