### ISSUE TITLE
Support for BlazorWebView in Uno

### ISSUE THREAD

**Issue by DmitryBorodiy** [unoplatform/uno#18287]
### What would you like to be added

It would be really cool if Uno apps supported BlazorWebView.

### For which platform

WebAssembly, Android, iOS, Mac Catalyst, Skia (WPF), Skia (Linux X11), Skia (macOS), Skia (Linux Framebuffer), Skia (GTK)

**Comment by jeromelaban** [comment]
Thanks for the report! We're already tracking this in https://github.com/unoplatform/uno/issues/12582.
