### ISSUE TITLE
First event handler parameter is object, not true sender

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#1830]
##Current behavior
XAML:
`<DatePicker Name="uiDay" DateChanged="uiDay_Changed" />`
.cs that can be compiled:
`private void uiDay_Changed(object sender, DatePickerValueChangedEventArgs args)`

## Expected behavior
But on UWP, event handler is:
`private void uiDay_Changed(DatePicker sender, DatePickerValueChangedEventArgs args)`

I think using syntax from UWP should be possible...

## How to reproduce it (as minimally and precisely as possible)
Use XAML element as above, and try to use second version of method header.

## Environment
Nuget Package: 1.45

Package Version(s):
Affected platform(s):
- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:
- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:
- [ ] Resharper (version: )

## Anything else we need to know?
Maybe it is 'by design', but it makes porting app to Uno harder than it should be.

Error is signaled in <page_longid>.g.cs
`var DateChanged_uiDay_Changed_That = (this as global::Uno.UI.DataBinding.IWeakReferenceProvider).WeakReference;`
`c12.DateChanged += (uiDay_Changed_sender,uiDay_Changed_e) => (DateChanged_uiDay_Changed_That.Target as MainPage)?.uiDay_Changed(uiDay_Changed_sender,uiDay_Changed_e);`

Error	CS1503	Argument 1: cannot convert from 'object' to 'Windows.UI.Xaml.Controls.DatePicker'	Anniversaries.Droid	H:\Home\PIOTR\VStudio\_Vs2017\Anniversaries\Anniversaries\Anniversaries.Droid\obj\Debug\90\g\XamlCodeGenerator\MainPage_2e4b438e191eabc098dac04eb074e589.g.cs

**Comment by Youssef1313** [comment]
`private void uiDay_Changed(DatePicker sender, DatePickerValueChangedEventArgs args)` fails on UWP for me. The `DateChanged` event is defined as `EventHandler<DatePickerValueChangedEventArgs>`. [The first parameter for it is indeed an object](https://docs.microsoft.com/en-us/dotnet/api/system.eventhandler-1?view=net-5.0). Is there anything I'm missing?

@MartinZikmund @davidjohnoliver Do you see anything here or should we close?

**Comment by jeromelaban** [comment]
This was probably fixed since the issue was opened.

**Comment by Youssef1313** [comment]
@jeromelaban The behavior stated in the issue still persists, **but** it's the same for UWP. The claim that UWP allows `DatePicker sender` looks incorrect.
