### ISSUE TITLE
NumberBox.NumberFormatter is not used on Android

### ISSUE THREAD

**Issue by borjafdezgauna** [unoplatform/uno#18308]
### Current behavior

I am binding a custom number formatter to a NumberBox component. Something like this:

```csharp
public class FloatNumberRounder : INumberFormatter2, INumberParser
{
    public string FormatDouble(double value)
    {
        return number.ToString("F1", CultureInfo.InvariantCulture); //only one fraction digit
    }

    public string FormatInt(long value)
    {
        return value.ToString();
    }

    public string FormatUInt(ulong value)
    {
        return value.ToString();
    }

    public double? ParseDouble(string text)
    {
        if (Numbers.TryParseDouble(text, out double parsedNumber))
            return parsedNumber;
        return null;
    }

    public long? ParseInt(string text)
    {
        if (Numbers.TryParseInteger(text, out int parsedNumber))
            return parsedNumber;
        return null;
    }

    public ulong? ParseUInt(string text)
    {
        if (Numbers.TryParseInteger(text, out int parsedNumber))
            return (ulong) parsedNumber;
        return null;
    }
}
```

, which I instantiate on my class:

```csharp
public INumberFormatter2 Formatter => new FloatNumberRounder ();
```

I then bind it in a DataTemplate:

```xml
<DataTemplate x:DataType="local:ValueHandlerModel">
  <StackPanel Orientation="Vertical">
    <NumberBox Value="{Binding Number, Mode=TwoWay}"
       SpinButtonPlacementMode="Inline"
       NumberFormatter="{x:Bind Formatter}"
       Style="{ThemeResource NumberBox}"/>
  </StackPanel>
</DataTemplate>
```

On Windows, it works as I expected: no matter what values I give to SmallChange and LargeChange (NumberBox), my formatter shows only one fraction digit.

On Android, an instance of FloatNumberRounder is actually instantiated, but then, when I click the arrows, none of the methods are called and, depending on the values of SmallChange/LargeChange, values show with 2 fraction digits. It is curious that, in the absence of a formatter, no random number of digits is shown due to imprecision (as it is on Windows)

### Expected behavior

I would expect the instance of NumberFormatter to be used also on Android

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report.

It should be supported by this portion:

https://github.com/unoplatform/uno/blob/b6e46046092710d42975c7e45d8f09d2a0adc755/src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox.cs#L535-L538

You may to try and see if other platforms are using it.

**Comment by borjafdezgauna** [comment]
I have been trying to build and test it on MacOS, but no luck so far... Will let you know when I manage to build it

Thanks for the response!

**Comment by borjafdezgauna** [comment]
Same behaviour on MacOS (as on Android, the custom formatter is not used)

Maybe I can try to debug that portion of the code to find out what is wrong on Android... could you please guide me? What project should I open on Windows to debug Uno on Android?

**Comment by jeromelaban** [comment]
Thanks for the update. You can find [debugging information in our docs](https://platform.uno/docs/articles/uno-development/building-uno-ui.html) and you can join our discord, the community can help as well.

**Comment by morning4coffe-dev** [comment]
I was able to reproduce the same issue on Android on my side (works on WinUI, Skia, Wasm), I will try to get more details on why the calls are not being executed. My repro:

[Formatting.zip](https://github.com/user-attachments/files/17433719/Formatting.zip)

**Comment by agneszitte** [comment]
> [Formatting.zip](https://github.com/user-attachments/files/17433719/Formatting.zip)

@jhanvi03, @Darsh0307 if you can test this issue with latest internal 5.6 stable please

**Comment by agneszitte** [comment]
I am **not** able to reproduce this issue with latest **Uno.Sdk 5.6.36**.
Behavior follows **WinAppSdk** for the other platforms now.

--- 
Tested with:
- Templates/SDK: **5.6.36**
- VS version: VS 2022 (64-bit) - Version **17.13.1**
- VS VSIX: [5.6.31](https://dev.azure.com/uno-platform/uno-private/_build/results?buildId=155709&view=results)
- [Issue18308.zip](https://github.com/user-attachments/files/18877455/Issue18308.zip)
- Platform: ** WinAppSdk, Android, iOS, WebAssembly, Desktop, Desktop WSL**
- OS: **Windows**
