### ISSUE TITLE
Hot Reload for Android cannot initialize on Mac in vscode

### ISSUE THREAD

**Issue by ardune** [unoplatform/uno#18313]
### Current behavior

Hot reload indicator says "cannot initalize" within launched app

### Expected behavior

Hot reload indicator should say "connected"

### How to reproduce it (as minimally and precisely as possible)

- I created a new uno project using dotnet new unoapp
- Open the project in vscode, set the active project, select test device (note: both emulator and physical device show the same behavior)
- Run and debug from vscode
- Let the app launch and check the hot reload indicator

### Workaround

The same process works for a windows machine for both emulator and the same device

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Android

### IDE

Visual Studio Code

### IDE version

1.93.1

## Extension Status
Extension: Dev Kit Mode
Debugger: Ready
Hot-Reload: Running on port 54689
XAML LSP: Ready

## Environment information
* Platform: darwin 24.0.0 (arm64)
* VSCode version: 1.93.1
* dotnet version: 8.0.402
* C# Extension: 'ms-dotnettools.csharp' version 2.45.25
* C# Dev Kit Extension: 'ms-dotnettools.csdevkit' version 1.10.18
* Uno Extension: 'unoplatform.vscode' version 0.16.1
* Xcode version: Xcode 15.1 Build version 15C65
* Targeting an android SDK 34 device / emulator

**Comment by agneszitte** [comment]
@ardune don't hesitate to refer to our current [documentation here](https://platform.uno/docs/articles/features/working-with-xaml-hot-reload.html?tabs=vswin%2Cwindows%2Cskia-desktop%2Ccommon-issues#supported-features-per-os) as well for Hot Reload support per OS/Platform
