### ISSUE TITLE
Two-Way x:Bind to MVVM Toolkit generated properties broken in 5.4 release (5.4.5)

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#18320]
### Current behavior

TwoWay x:Bind to a bool property generated by MVVM tookit now results in the following error:
```
error UXAML0001: Unable to find member [IsEnabled] on type [bool]
error UXAML0001: Processing failed for file P:\YourProject\YourControl.xaml (Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in UserControl ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in StackPanel ---> System.InvalidOperationException: Unable to find member [IsEnabled] on type [bool]
```
OneWay bind works fine.

### Expected behavior

Should work as it always did in version <= 5.3.x.

### How to reproduce it (as minimally and precisely as possible)

```cs
public partial class SomeModel : ObservableObject
{
    [ObservableProperty]
    private bool _isEnabled;
}
```
```xml
<ToggleSwitch IsOn="{x:Bind Model.IsEnabled, Mode=TwoWay}" OnContent="Enabled" OffContent="Disabled"/>
```

### Workaround

Don't use MVVM toolkit generated properties

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.4.5, 5.5.0-dev.66

### Affected platforms

WebAssembly, Android, iOS, Mac Catalyst, Skia (WPF), Skia (Linux X11), Skia (macOS), Skia (Linux Framebuffer), Skia (GTK)

**Comment by jeromelaban** [comment]
Thanks for the report. Can you provide a full repro? The snippet you provided is not enough to replicate the behavior.

**Comment by mikernet** [comment]
@jeromelaban  Oh, the issue appears to be that the Uno source generator "hack" that makes it work with MVVM Toolkit generated properties is broken. Use this for the model to see the problem:

```cs
public partial class SomeModel : ObservableObject
{
    [ObservableProperty]
    private bool _isEnabled;
}
```

**Comment by mikernet** [comment]
Repro project:
[Uno5NewProjectTest.zip](https://github.com/user-attachments/files/17163887/Uno5NewProjectTest.zip)

**Comment by jeromelaban** [comment]
Note that this is related to a workaround Uno has to support this feature, coming from a missing feature from roslyn https://github.com/dotnet/roslyn/issues/57239, also tracked here: https://github.com/unoplatform/uno/issues/14409.

**Comment by agneszitte** [comment]
@jeromelaban, is additional QA needed for this issue?
