### ISSUE TITLE
[Android] LaunchMode.SingleTask in MainActivity causes blank UI on relaunch (Uno 5.4 regression)

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#18325]
### Current behavior

Starting with 5.4.x, when `MainActivity` is set to `LaunchMode.SingleTask`, the app shows a blank UI if it is running persistently in the background (i.e. because it is receiving background location updates) and it is closed/swiped away and then relaunched:

https://github.com/user-attachments/assets/7fa4c6dd-e221-4d82-8ef6-0778488ee999

### Expected behavior

Same as version <= 5.3.x - app UI should restore to its previous state and show properly again after relaunch:

https://github.com/user-attachments/assets/ceed1817-f61b-4b7b-ab8a-08e6bff49275

### How to reproduce it (as minimally and precisely as possible)

```cs
[Activity(
    MainLauncher = true,
    LaunchMode = LaunchMode.SingleTask,
    ...)]
public class MainActivity : Microsoft.UI.Xaml.ApplicationActivity
```

Then run something that will keep the activity alive like a background service or background location updates, swipe away the app, then click the icon to launch it again and reactivate the activity and notice you get a blank screen.

Repro project would require large amounts of actual app code that contains all the permission request logic/UI, background location update service, etc...so if you want that then I will need to send the code privately as I can't share it publicly.

### Workaround

None

### Works on UWP/WinUI

None

### NuGet package version(s)

5.4.5, 5.5.0-dev-66

### Affected platforms

Android

**Comment by agneszitte** [comment]
@jeromelaban, @MartinZikmund  is additional QA needed for this issue?

**Comment by jeromelaban** [comment]
Yes, this is needed.

**Comment by MartinZikmund** [comment]
> @jeromelaban, @MartinZikmund is additional QA needed for this issue?

Created a manual test sample in the Samples app under Windowing category

**Comment by agneszitte** [comment]
@jhanvi03, @Darsh0307 if you can test this with latest stable version, please
