### ISSUE TITLE
[Android (maybe others)]  If app starts focused on TextBox, keyboard keeps popping up

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#18324]
### Current behavior

If the app starts on a page with a TextBox as the first focusable control then it gets automatically focused, and then anytime you click any buttons in the app, the soft keyboard keeps popping up, even if there are no textboxes on the current page.

### Expected behavior

Soft keyboard should behave correctly and not pop up anytime a button is clicked

### How to reproduce it (as minimally and precisely as possible)

Initially loaded page should have a textbox on it as the first focusable control so that it gets focus when the app first loads automatically. Go to another page and click buttons, notice that the keyboard keeps popping up.

Video:

https://github.com/user-attachments/assets/05abdf12-e0b1-49f0-8c46-6d796b7ff4d9

### Workaround

Have an invisible button above the first textbox on the initial page that loads so that it gets focus instead of the textbox when the app starts and keyboard works correctly after that.

### Works on UWP/WinUI

None

### NuGet package version(s)

5.5.0-dev.66, 5.4.5, 5.3.112, 5.3.108, 5.3.90

### Affected platforms

Android, possibly others

**Comment by mikernet** [comment]
@MartinZikmund There's something really screwy going on with textbox/keyboard focus in 5.3+. Tagging you here because it seems related to my update in https://github.com/unoplatform/uno/issues/17384.

With the invisible dummy workaround from the issue above left in place to prevent the initial scroll focus problem, the page with the textbox works ok, but now for some reason when I navigate away from that page to another page that doesn't even have a textbox, the keyboard keeps popping up:

https://github.com/user-attachments/assets/d1184a1e-fd1a-478e-88d2-46a62272d945

**Comment by mikernet** [comment]
Ok, so...to get correct behavior everywhere, I need to do all 3 of these things. If any one of them is missing, something about with focus/keyboard breaks:
- add an invisible dummy focus button to the top of the first page the app shows so that initial focus on app start is not captured by a textbox, otherwise keyboard focus behavior breaks all over the place afterwards
- disable all textboxes and password boxes on the initially shown page before navigating away, otherwise keyboard pops up on page navigations even when the destination page doesn't have any textboxes
- add an invisible dummy button to any page that has a textbox as the first focusable control, to prevent initial capture of focus on first scroll of that page

**Comment by MartinZikmund** [comment]
@mikernet Sorry for the delay, can you please create some simple repro (just two pages for example) that demonstrates this behavior?
