### ISSUE TITLE
Wrap call to WaitForFileUpdated in a try-catch for logging when timeout is exceeded

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#18335]
Since we're putting a timeout on how long to await this task, we should wrap this in a try-catch so we can log when the timeout is exceeded - this would aid debugging if we come across scenarios where the timeout is hit and we can't trace why HR isn't behaving

_Originally posted by @nickrandolph in https://github.com/unoplatform/uno/pull/18327#discussion_r1780318106_

**Comment by dr1rrb** [comment]
Done in the original PR
