### ISSUE TITLE
You must create header add-ons in WebView 2

### ISSUE THREAD

**Issue by LiberRuth** [unoplatform/uno#18330]
### What would you like to be added

A certain page is requesting authentication

```xaml
<WebView2 Headers={Binding Headers} />
```

**Comment by MartinZikmund** [comment]
Unfortunately, as we are trying to match the WinUI API surface, we cannot easily add a "custom" attribute, unless a feature is really specific to a platform. If you are able to provide a code snippet on how to adjust headers for a `WebView2` control directly in a plain WinUI app, we can look into bringing support for an API into Uno Platform targets as well
