### ISSUE TITLE
Selecting Android in Target Device Selector defaults to wasm 

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno#18349]
### Current behavior

Sometimes Android isn't being properly selected as shown in the video:

https://github.com/user-attachments/assets/b730ee50-d388-41f2-8e22-0d7d3351e4e5

### How to reproduce it (as minimally and precisely as possible)

I could repro 2x by:

1. Open VS
2. In my case Android was already selected
3. Launch emulator
4. Debug
5. Select Desktop
6. Debug
7. Try selecting Android again - it will get to the state in the video

But the third time trying to repro I didn't get the problem. Also, after recording the video I launched on Wasm and when I tried to select Android again it worked.

The solution I encountered the error: https://drive.google.com/file/d/1lcJvK1ZUmQ6_rOExc4P8NUyNr6qGkIFs/view?usp=sharing (couldn't upload here bc of size)

### Workaround

Clean solution everytime before changing target.

### Works on UWP/WinUI

None

### NuGet package version(s)

VS: 17.11.4
Uno VS Extension: 5.4.11.11
Sdk: 5.4.5
 

### IDE

Visual Studio 2022

### IDE version

17.11.4

**Comment by jeromelaban** [comment]
With 17.12, it's now only required to auto-reload the projects from/to wasm. It should work better after #18356,

**Comment by agneszitte** [comment]
@jeromelaban should @Darsh0307 test with latest the repro of this issue now that https://github.com/unoplatform/uno/pull/18356 is merged?

**Comment by jeromelaban** [comment]
Yes, this is needed.

**Comment by Darsh0307** [comment]
The issue seems to be solved in the latest version of 5.5.0-dev.92 

I tried a lof time but still i am not able to reproduce the behaviour happening on erik side. 

I tried in both Blank and recommend project by creating the project multiple times. 


So thus i can say that  the issue is solved but if possible @eriklimakc  , can you please try it once again on your side ?

**Comment by eriklimakc** [comment]
@Darsh0307 I couldn't reproduce the issue anymore either. Looks like it's resolved.

cc @agneszitte @jeromelaban

**Comment by Darsh0307** [comment]
Thanks for confirming @eriklimakc
