### ISSUE TITLE
Inconsistent use of #if __WASM__

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1834]
## Observation:

Some WebAssembly implementations use `#if __WASM__` but the majority does not.

![image](https://user-images.githubusercontent.com/127353/66728449-c3408e80-ee90-11e9-8054-33898b763da1.png)

![image](https://user-images.githubusercontent.com/127353/66728529-3ba74f80-ee91-11e9-86b5-5dd7a9ad8ac0.png)

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

What is the rule of thumb for refactoring? If `#if __WASM__` is missing - should it be added?

**Comment by jeromelaban** [comment]
It should not be used for whole files, as there is a globbing pattern in place to avoid having to place it everywhere. See here:
https://github.com/unoplatform/uno/blob/6cc46e6268ef60eb9a214719da16faa1dce3a297/src/PlatformItemGroups.props#L48

**Comment by ghuntley** [comment]
> 
> 
> It should not be used for whole files, as there is a globbing pattern in place to avoid having to place it everywhere. See here:
> 
> https://github.com/unoplatform/uno/blob/6cc46e6268ef60eb9a214719da16faa1dce3a297/src/PlatformItemGroups.props#L48

Documented over at https://github.com/unoplatform/uno/issues/1834#issuecomment-542161088
