### ISSUE TITLE
FolderPicker is supported with Skia Desktop (Windows)

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#18341]
### On which page?

https://platform.uno/docs/articles/features/windows-storage-pickers.html#_content

### What's wrong?

![image](https://github.com/user-attachments/assets/ebb33426-4be1-4b8c-976a-42143a32c142)

### Any feedback?

It works on Skia Desktop.

**Comment by MartinZikmund** [comment]
Indeed, the docs are outdated here. We will adjust!
