### ISSUE TITLE
Release 5.4.5 does not play nice with ScottPlot

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#18350]
Adding the nuget of ScottPlot requires bumping the WinAppSDKVersion. However, this leads to a crash at startup https://github.com/ScottPlot/ScottPlot/issues/4258

[UnoAppScottPlot545.zip](https://github.com/user-attachments/files/17211902/UnoAppScottPlot545.zip)

Jerome gave me tips to downgrade some part of Uno, but I'm getting compilation errors.

Someone has this suggestion https://github.com/ScottPlot/ScottPlot/issues/4273#issuecomment-2359903404

If you know how to modify the Uno project, I would appreciate.

**Comment by ArchieCoder** [comment]
This is not that easy because MVVM Toolkit requires:
10.0.22621.38

ScottPlot requires at max:
10.0.22621.34

However, we are not releasing in the next few weeks, I can stay with 5.4.0-dev.220 for some time.

PS: Good idea about the Uno Health Status.

**Comment by jeromelaban** [comment]
SkiaSharp 2.88.9-preview.2.2 fixes this issue.

**Comment by ArchieCoder** [comment]
@jeromelaban Big thank you to you and Matthew Leibowitz (can't find the tag)
