### ISSUE TITLE
[WinUI] Having the PublishProfiles like win-x64.pubxml files causes a crash when the app starts in Release

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#18367]
### Current behavior

Recently, I added the suggested profile from [win-x64.pubxml ](https://github.com/unoplatform/uno.templates/pull/981) to remove the compilation warning.

With our new release pipeline, we noticed this week the Release app does not start. In the event viewer, we see this information 
![image](https://github.com/user-attachments/assets/2fe5164c-1c8c-49ac-ab2c-330491aa0bd4)

I went back in time until I found the regression. If I remove the win-x64.pubxml, the app launches as expected.

---

Second bug related with the same subject: creating a blank app with the platforms Windows and Skia Desktop and **Fluent** will make the solution uncompilable in Release.

![image](https://github.com/user-attachments/assets/1ff62595-d9a5-44bc-8adf-8301e31067c6)

### How to reproduce it (as minimally and precisely as possible)

This sample app just showcase the compilation error as mentioned in my 2nd point above
[UnoApp1.zip](https://github.com/user-attachments/files/17231536/UnoApp1.zip)

### Works on UWP/WinUI

No

### NuGet package version(s)

5.4.5

### Affected platforms

Windows (WinAppSDK)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. The latest templates we published today contain this file now, can you validate with it?

**Comment by ArchieCoder** [comment]
@jeromelaban The updated template adds win-AnyCPU.pubxml and fixes the compilation error. There is a weird warning, but it compiles.

However, the app does not start in release (same behavior as my app).

From event viewer:
Faulting application name: UnoApp4.exe, version: 1.0.0.0, time stamp: 0x66960000
Faulting module name: Microsoft.UI.Xaml.dll, version: 3.1.6.0, time stamp: 0xeb72d9fd
Exception code: 0xc000027b
Fault offset: 0x0000000000009125
Faulting process id: 0x0x7D00
Faulting application start time: 0x0x1DB15128E4F9D2F
Faulting application path: D:\Projects\UnoApp4\UnoApp4\bin\Release\net8.0-windows10.0.19041\win-x64\AppX\UnoApp4.exe
Faulting module path: D:\Projects\UnoApp4\UnoApp4\bin\Release\net8.0-windows10.0.19041\win-x64\AppX\Microsoft.UI.Xaml.dll
Report Id: e0443043-b067-4a55-9af7-ba4c1986496b
Faulting package full name: com.companyname.UnoApp4_1.0.0.1_x64__97751s6e7dt9p
Faulting package-relative application ID: App

**Comment by ArchieCoder** [comment]
FYI, removing the PublishProfile files enables the app to run in Release, but it breaks the project in Visual Studio, the Uno targets are gone.

**Comment by jeromelaban** [comment]
I'm not reproducing the issue with UnoApp4.zip if I remove only the anycpu file. The profile files are needed overall, but the anycpu is the one that is causing trouble.

**Comment by ArchieCoder** [comment]
@jeromelaban Good news, the compilation error is gone, but it was not obvious. My first try was to setup a new VM with Uno. It was working. I was clueless about what to try next on my main PC, but I gave a try to repair my VS installation -> that fixed the issue!

I noticed that the AnyCPU publish file is not there anymore in the latest update as it was merged 👍
