### ISSUE TITLE
[Mobile][Mono] Breakpoints Not Hit When Multiple Statements Are on a Single Line

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno#18374]
### Current behavior

When debugging on Android and iOS, breakpoints set on lines with multiple statements may not function correctly. Mono has difficulties handling multiple sequence points on a single line, leading to breakpoints either misfiring or only hitting the first or last statement.

To avoid this debugging issue:

Split each statement onto its own line. For example, instead of:

```csharp
int x = 1; int y = 2;
```

or

```csharp
public object MyObject { get => _myObject; set => _myObject = value; }
```

Do:

```csharp
int x = 1;
int y = 2;
```

```csharp
public object MyObject 
{
    get => _myObject;
    set => _myObject = value;
}
```

Now, Mono will correctly hit each breakpoint as expected.

**Comment by jeromelaban** [comment]
Thanks for the report. This is not something we can fix, this is a .NET runtime feature that is not present. This is also unlikely to be fixed any time soon...

**Comment by morning4coffe-dev** [comment]
@jeromelaban Wouldn't it be good to leave this issue open for tracking in https://github.com/unoplatform/uno/issues/982? Once it's eventually fixed, we could remove the changes added in https://github.com/unoplatform/uno/pull/18373. CC @MartinZikmund @agneszitte

**Comment by jeromelaban** [comment]
There is likely already one that dates from many years ago, but it probably got closed when moving from bugzilla to github.
