### ISSUE TITLE
[WinAppSDK] Not being able to copy text to clipboard

### ISSUE THREAD

**Issue by LuisAlfredo92** [unoplatform/uno#18383]
### Current behavior

I can't copy text to clipboard on WinAppSDK, since version 5.3.108 until now on 5.4.5, it works on "Desktop", and Android, but WinAppSDK

This is the code:
```
public async Task CopyCode()
{
    var currentCode = await Code ?? string.Empty;
    var dataPackage = new DataPackage();
    dataPackage.SetText(currentCode);
    Clipboard.SetContent(dataPackage);
}
```
Debugging I realized that the code is actually executed and the `currentCode` variable actually has the expected value, but it isn't copied on that platform

With a try catch I saw that it actually throws and exception, but there isn't any details
![imagen](https://github.com/user-attachments/assets/3796ba54-f5ad-4c66-bf15-da9a9bd1b15d)

### Expected behavior

To be able to copy to the clipboard as in any other platform, or have an explicit exception to know if I'm doing something wrong

### How to reproduce it (as minimally and precisely as possible)

Just like this code
```
public async Task CopyCode()
{
    var currentCode = await Code ?? string.Empty;
    var dataPackage = new DataPackage();
    dataPackage.SetText(currentCode);
    Clipboard.SetContent(dataPackage);
}
```
1. Getting the value from an IState<string>
2. Save it inside a DataPackage
3. Try save it using the static method SetContent

### Works on UWP/WinUI

No

### Environment

Other

### Affected platforms

Windows (WinAppSDK)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report! Are you running in packaged or unpackaged debugging profile?

**Comment by LuisAlfredo92** [comment]
Packaged, I can't run unpackaged because it throws a InvalidOperationException because I use ApplicationData.Current.LocalFolder.Path

**Comment by jeromelaban** [comment]
Thanks. For this type of scenarios, the WinAppSDK target is managed by Microsoft, so there may be a bug or limitation there. You may want to take a look at the issues here: https://github.com/microsoft/WindowsAppSDK or https://github.com/microsoft/microsoft-ui-xaml.

**Comment by LuisAlfredo92** [comment]
Thanks, I found the solution on those issues, this worked:
```
    public async Task CopyCode()
    {
        var currentCode = await Code ?? string.Empty;
        var dataPackage = new DataPackage();
        dataPackage.SetText(currentCode);
#if HAS_UNO
        Clipboard.SetContent(dataPackage);
        Clipboard.Flush();
#else
        Thread thread = new(() => 
        {
            Clipboard.SetContent(dataPackage);
            Clipboard.Flush();
        });
        thread.SetApartmentState(ApartmentState.STA);
        thread.Start();
#endif
    }
```
It says that Clipboard won't work if you use it in UI thread, so I created a new one, but only for that platform. I hope this works for somebody else too
