### ISSUE TITLE
Error on Tapped and Click events in Android 5

### ISSUE THREAD

**Issue by NGame1** [unoplatform/uno#1838]
## Current behavior
Landroid/view/MotionEvent;.getActionButton()
This error happens on Tapped and Click events after 2.0.512 dev builds.
It's fine on 2.0.324
Affected platform(s):

- [ ] iOS (Not tested)
- [x] Android
- [ ] WebAssembly (Not tested)
- [ ] WebAssembly renderers for Xamarin.Forms (Not tested)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

**Comment by ghuntley** [comment]
Potentially related to https://github.com/unoplatform/uno/pull/1256

**Comment by NGame1** [comment]
Solved. 
tested on 2.0.512-dev.3449

**Comment by NGame1** [comment]
once again it happened on 2.0.512-dev.3599.
I donno if it started on this build or some other build I was a bit far from Uno Platform

**Comment by jeromelaban** [comment]
It seems that we need additional UI testing for android 5, as this still fails. @dr1rrb can you take a look at this ?
