### ISSUE TITLE
Keys added to the uno keyboard

### ISSUE THREAD

**Issue by ashah7** [unoplatform/uno#18391]
### What would you like to be added

Are you able to add the below  keys to the keyboard and release on nuget 
^
~
"
|

would be appreciated

### Why is this needed

They are missing

### For which platform

Skia (Linux X11), Skia (Linux Framebuffer)

### Anything else we need to know?

Keyboard found here

https://github.com/mcNets/UnoKeyboard

**Comment by mcNets** [comment]
@ashah7 please open an issue in UnoKeuboard repo.

Thank you @Youssef1313.

**Comment by agneszitte** [comment]
Related issue https://github.com/mcNets/UnoKeyboard/issues/8
@Youssef1313, @mcNets can we close this current uno issue then ?

**Comment by mcNets** [comment]
> Related issue https://github.com/mcNets/UnoKeyboard/issues/8
> @Youssef1313, @mcNets can we close this current uno issue then ?

Yes @agneszitte , thank you.
