### ISSUE TITLE
The need for the Svg UnoFeature is not visible enough

### ISSUE THREAD

**Issue by jojorne** [unoplatform/uno#18418]
### Your feedback

By default svg is off. This wasn't the case. Now the documentation needs to be updated, including the [new.platform.uno](https://new.platform.uno/). For instance, [Counter App](https://platform.uno/docs/articles/getting-started/counterapp/get-started-counter-xaml-mvux.html?tabs=vs)'s `Source="Assets/logo.png"` is now `"Assets/logo.svg"` and needs to be created with `dotnet new unoapp -o Counter -preset blank -presentation mvux -markup xaml -svg` for it to work.

**Comment by jojorne** [comment]
I'm closing this because the issue is deeper than I thought. 💭

**Comment by agneszitte** [comment]
@Kunal22shah  could you please verify if the Counter documentation details and related sample app are still up to date

**Comment by Kunal22shah** [comment]
@jojorne, Thanks for the details. So i re-created Counter following the docs [here](https://platform.uno/docs/articles/getting-started/counterapp/get-started-counter-xaml-mvux.html?tabs=vs) w command line (`dotnet new unoapp -preset blank -presentation mvux -markup xaml -o Counter` ) and wizard and the SVGs seem to work as expected. Can you check if you selected the `UnoImage` build action on `logo.svg`. it seem to work fine on my side with`5.4.10` SDK and latest templates .

**Comment by jojorne** [comment]
Both worked but the caveat is:
- you download the .svg file:
`curl -o Counter/Counter/Assets/logo.svg https://platform.uno/docs/articles/getting-started/counterapp/Assets/logo.svg`
- but you use the .png extension:
```csharp
new Image()
    .Width(150)
    .Height(150)
    .Source("ms-appx:///Assets/logo.png"),
```

**Comment by agneszitte** [comment]
> Both worked but the caveat is:
> 
> * you download the .svg file:
>   `curl -o Counter/Counter/Assets/logo.svg https://platform.uno/docs/articles/getting-started/counterapp/Assets/logo.svg`
> * but you use the .png extension:
> 
> ```cs
> new Image()
>     .Width(150)
>     .Height(150)
>     .Source("ms-appx:///Assets/logo.png"),
> ```

---

@jojorne to make it clearer for you there are two ways with Uno Platform to use an actual **.svg** file:

- Using a svg in the path of the Image control
  [Svg file build action = Content]

  Following this doc: [Using SVG images (platform.uno)](https://platform.uno/docs/articles/features/svg.html)

**VS**

- Using a png in the path that uses an svg file underneath with Uno.Resizetizer (UnoImage)
  [Svg file build action = UnoImage]

  Following this doc: [How-To: Get Started with Uno.Resizetizer - UnoImage](https://platform.uno/docs/articles/external/uno.resizetizer/doc/using-uno-resizetizer.html?#unoimage)
  
Details on using SVG vs PNG when using an .svg file:
- https://platform.uno/docs/articles/features/svg.html?tabs=singleproject#when-to-use-svg
- https://platform.uno/docs/articles/external/uno.resizetizer/doc/using-uno-resizetizer.html#using-svg-images-vs-png-images-with-svg-underneath

**Comment by agneszitte** [comment]
@jojorne based on the information I’ve shared above, please let me know if you’re still encountering any issues or if the documentation needs further clarification. Your feedback is incredibly valuable to us as we strive to improve the documentation for everyone using the Uno Platform. 
Any insights you can provide would be greatly appreciated!

**Comment by jojorne** [comment]
```
Using SVG images

Uno Platform supports using vector SVG graphics inside of your cross-platform applications,
using the SvgImageSource class. SVG Images can also be used through UnoImage with Resizetizer.
```
Just, uh... I see that there is no mention to [Using SVG images](https://platform.uno/docs/articles/features/svg.html) there, only to [Get Started with Uno.Resizetizer](https://platform.uno/docs/articles/external/uno.resizetizer/doc/using-uno-resizetizer.html). Look:
```
Including SVG files with the UnoImage build action will use Uno.Resizetizer to convert the
SVG file to a PNG file for each platform. The generated PNG files will be included in the
application package and used at runtime. For more information on using Uno.Resizetizer in
Uno Platform, see Get Started with Uno.Resizetizer.
```

**Comment by jojorne** [comment]
@Kunal22shah Check the [Using SVG images](https://platform.uno/docs/articles/features/svg.html) page.
```xaml
<Image Source="ms-appx:///Assets/test.svg" Stretch="UniformToFill" Width="100" Height="100" />
```
Shouldn't it be:
```xaml
<Image Source="ms-appx:///Assets/Svg/test.svg" Stretch="UniformToFill" Width="100" Height="100" />
```

**Comment by agneszitte** [comment]
> ```
> Using SVG images
> 
> Uno Platform supports using vector SVG graphics inside of your cross-platform applications,
> using the SvgImageSource class. SVG Images can also be used through UnoImage with Resizetizer.
> ```
> 
> Just, uh... I see that there is no mention to [Using SVG images](https://platform.uno/docs/articles/features/svg.html) there, only to [Get Started with Uno.Resizetizer](https://platform.uno/docs/articles/external/uno.resizetizer/doc/using-uno-resizetizer.html). Look:
> 
> ```
> Including SVG files with the UnoImage build action will use Uno.Resizetizer to convert the
> SVG file to a PNG file for each platform. The generated PNG files will be included in the
> application package and used at runtime. For more information on using Uno.Resizetizer in
> Uno Platform, see Get Started with Uno.Resizetizer.
> ```
---

@jeromelaban, @kazo0 
In the Counter tutorial, we're currently using only the SVG file through Resizetizer. 
However, as @jojorne suggested, we could also mention that using an SVG file with the .svg extension is an option. We could include a link to the relevant documentation: [How to use SVG](https://platform.uno/docs/articles/features/svg.html).

Additionally, we can clarify the differences between using SVG and PNG when working with SVG files, as explained in the following documentation links:
- [platform.uno/docs/articles/features/svg.html#when-to-use-svg](https://platform.uno/docs/articles/features/svg.html?tabs=singleproject#when-to-use-svg)
- [platform.uno/docs/articles/external/uno.resizetizer/doc/using-uno-resizetizer.html#using-svg-images-vs-png-images-with-svg-underneath](https://platform.uno/docs/articles/external/uno.resizetizer/doc/using-uno-resizetizer.html#using-svg-images-vs-png-images-with-svg-underneath)

Since Counter is the first tutorial users encounter, providing this information upfront would be beneficial I think. It will highlight the available options from the beginning.

What do you think about including this please?

**Comment by jojorne** [comment]
btw, https://new.platform.uno/ does not have the svg option.

**Comment by agneszitte** [comment]
> btw, [new.platform.uno](https://new.platform.uno/) does not have the svg option.

@jeromelaban is this an option we could add to the wizard so the Svg UnoFeatures is added instead of having to add it manually afterward?

**Comment by jojorne** [comment]
If I understand correctly, images under the Svg directory can be used directly, while the others are converted to .png, right? From Resizetizer:

Direct SVG Usage

When to Use:

    You require vector graphics to be scalable without loss of quality.
    Your app needs to dynamically change aspects of the image, such as color or size, at runtime.

How to Implement:

    Set the build action of your SVG file to Content.
    Reference the SVG file directly in the Image control's Source property.

```diff
- <Image Source="/Assets/my_vector_image.svg" />
+ <Image Source="/Assets/Svg/my_vector_image.svg" />
```

Using Svg Images

Using Uno.Resizetizer for SVG to PNG Conversion

When to Use:

    You need raster graphics to optimize performance on platforms where SVG rendering might be less efficient.
    Your app targets multiple platforms and requires consistent image rendering across all.

How to Implement:

    Set the build action of your SVG file to UnoImage.
    Uno.Resizetizer will generate PNG assets at various scales.
    Reference the generated PNG in the Image control's Source property.

```diff
- <Image Source="/Assets/Generated/my_vector_image.png" />
+ <Image Source="/Assets/my_vector_image.png" />
```

Using Uno Resizetizer

Choosing between direct SVG usage and PNG conversion with Uno.Resizetizer depends on your specific application needs. Consider factors such as platform target, performance requirements, and how you plan to manipulate the images within your app.

**Comment by jojorne** [comment]
So, it seems that it's talking about the legacy project that just setting to content is enough.

**Comment by jeromelaban** [comment]
> @jeromelaban is this an option we could add to the wizard so the **Svg** `UnoFeatures` is added directly as needed, instead of having to add it manually afterward? cf. https://platform.uno/docs/articles/features/svg.html

The point of having it as a feature is to avoid pulling assemblies that may not be needed. Still, we could enhance: 

https://github.com/unoplatform/uno/blob/0c9740ad7fbdab33839cf65dc8c9a0ce05b0a60f/src/Uno.Analyzers/UnoMissingAssemblyAnalyzer.cs#L13-L14 

To detect the use of SVGs in XAML and suggest what to do.
