### ISSUE TITLE
The FontIcons are not displayed correctly in WinUI when building in release mode

### ISSUE THREAD

**Issue by Suriman** [unoplatform/uno#18434]
### Current behavior

When an app that uses FontIcons from another project referenced by nuget and runs it on WinUI compiled in release mode, the icons are not displayed correctly.

### Expected behavior

The icons are displayed correctly.

### How to reproduce it (as minimally and precisely as possible)

1. Open the attached solution and compile the project FontIconsResources and generate a nuget.
2. Install the generated nuget in  FontIconsReleaseWinUI.
3. Execute it in any platform in debug or release.
4. Only the WinUI in release mode shows squares instead of icons.

[18434-FontIconsReleaseWinUI.zip](https://github.com/user-attachments/files/17342427/18434-FontIconsReleaseWinUI.zip)

### Workaround

No known workaround.

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI 5.4.27

### Affected platforms

Windows (WinAppSDK)

### IDE

Visual Studio 2022

### IDE version

17.11.4

**Comment by jeromelaban** [comment]
Thanks for the report. This is a WinUI issue, reproducible in a vanilla WinUI app. It is best to open an issue on the https://github.com/microsoft/microsoft-ui-xaml repository for the WinUI team to take a look.

In the meantime, you may need to copy the asset in your project and use conditional xaml to include it for winui.
