### ISSUE TITLE
[Docs] `CameraCaptureUI` with platform specifics page

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#18456]
### What would you like clarification on

Add some docs for `CameraCaptureUI` https://github.com/unoplatform/uno/discussions/18420#discussioncomment-10917951

### Concern

Developing with Uno

### Affected platforms

Android, iOS

**Comment by Youssef1313** [comment]
Side note: this is the kind of issues that https://github.com/unoplatform/uno/issues/12187 is intending to better address. cc @jeromelaban
