### ISSUE TITLE
[Docs] typo in Native Frame navigation doc pages

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#18494]
### What would you like clarification on

`SystemNavigationService` is not existing... probably meant `SystemNavigationManager`

- https://platform.uno/docs/articles/features/native-frame-nav.html
- https://platform.uno/docs/articles/controls/CommandBar.html

### Concern

None

### Additional info
possible origin of error?: doc\articles\controls\CommandBar.md
related sample initial pr: https://github.com/unoplatform/uno/pull/5457/files
related doc initial pr: [unoplatform/Uno.Samples@`da251b0` (#44)](https://github.com/unoplatform/Uno.Samples/pull/44/commits/da251b05ede3dd68e19c75646dfded23dac5c354)

**Comment by Xiaoy312** [comment]
discord user complained that said class didnt exist
at the time, i thought it was some legacy class that was deprecated, & replied that these pages were outdated
it also doesnt help that https://github.com/microsoft/WindowsAppSDK/issues/2398 was adding the confusion

**Comment by agneszitte** [comment]
> a discord user complained that said class didnt exist at the time, i thought it was some legacy class that was deprecated, & replied that these pages were outdated it also doesnt help that [microsoft/WindowsAppSDK#2398](https://github.com/microsoft/WindowsAppSDK/issues/2398) was adding the confusion

Related answer on Discord for reference:
https://discord.com/channels/1182775715242967050/1182776377955602632/1294474205420720169 
> regarding some of you questions:
> - for the theme-switching, you only need to set the ActualTheme of the XamlRoot.Content. you can find an example of it, here: https://github.com/unoplatform/uno.toolkit.ui/blob/main/samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Shell.xaml.cs#L92
    (note that this setup doesnt persist the theme between app launches. if you are in need of that features, you would need that `UseThemeSwitching` service or have to implement your own)
> - yes, both these pages are somewhat outdated unfortunately.
> - SystemNavigationManager is an api from uwp, that no longer exists in winui. i would assume that you are using a winappsdk(winui) project, in such case, just exclude the relevant code for the windows target with:
    ```cs
  #if HAS_UNO
  SystemNavigationManager...
  #endif
  ```

**Comment by agneszitte** [comment]
@Mergifyio backport release/stable/5.4
