### ISSUE TITLE
`VariableSizedWrapGrid` required on Android and iOS

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#1852]
Implementation of VariableSizedWrapGrid on Android and iOS

Currently using a VariableSizedWrapGrid in an existing UWP app to display options on part of a dashboard. The number of options varies according to privileges, data availability etc.
Currently a tile per available option is created on a wrapgrid acting as the ItemsPanel of an ItemsControl.
The tiles are dynamically sized to display nicely regardless of the panel size.

- [ x] iOS
- [ x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Design image included
![Dashboard design](https://user-images.githubusercontent.com/4189260/66825286-ea0acd80-ef41-11e9-8954-c28652a89749.png)

**Comment by MartinZikmund** [comment]
Done!
