### ISSUE TITLE
XAML files in the `Platforms` folder are not filtered

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#18538]
### Current behavior

`.xaml` files placed in the `Platforms` folder are not filtered per platform, while `.cs` are properly included in their respective platforms.

### Expected behavior

All files placed in the `Platforms` folder are filtered.

### Works on UWP/WinUI

None

**Comment by alove-kahua** [comment]
As a workaround for now, I'm globally removing all XAML in the Platforms tree like so:
`<Page Remove="Platforms\**\*.xaml" />`

Then I'm adding the XAML in the Choose for each platform.  Here is the one for Windows:
`<Page Include="Platforms\Windows\**\*.xaml" />`
