### ISSUE TITLE
Change button colour

### ISSUE THREAD

**Issue by y0ur-valentine** [unoplatform/uno#18558]
### Current behavior

When you maximize the application window, and when you return it to its original state, the buttons change color to white.
![Снимок экрана 2024-10-23 200448](https://github.com/user-attachments/assets/623d0891-e5ab-4972-901e-b81d88abb1e7)
![Снимок экрана 2024-10-23 200508](https://github.com/user-attachments/assets/89e4177a-49a1-4e0d-931b-10add2bd2b79)
![Снимок экрана 2024-10-23 200540](https://github.com/user-attachments/assets/ea2919c1-4b45-431a-b973-b4b4f655e876)

### Expected behavior

The buttons do not change their color.

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Skia (WPF), Skia (Linux X11), Skia (Linux Framebuffer), Skia (GTK)

### IDE

Visual Studio 2022

### IDE version

17.11.5

**Comment by jeromelaban** [comment]
Thanks for the report. Can you tell which target framework you're using to run the app ?

**Comment by y0ur-valentine** [comment]
> Спасибо за отчет. Можете ли вы сказать, какой целевой фреймворк вы используете для запуска приложения?

net8.0-desktop
![image](https://github.com/user-attachments/assets/6c6d40db-c0ca-4a93-a366-b474927a056d)

**Comment by MartinZikmund** [comment]
@y0ur-valentine can you please provide a `.zip` of a minimal repro that can be tested against? Unfortunately we cannot easily reproduce the problem otherwise.
