### ISSUE TITLE
FileIO.ReadTextAsync(IStorageFile) not implemented in Uno

### ISSUE THREAD

**Issue by JanabiSoft** [unoplatform/uno#186]
FileIO.ReadTextAsync(IStorageFile) not implemented in Uno
What is the replacement, please how can I access a file to read text from it.

**Comment by jeromelaban** [comment]
We have not implemented this yet because `System.IO.File` is already working on all platforms. You can adjust your code to use it and you should be good to go.

**Comment by JanabiSoft** [comment]
thanks

**Comment by MartinZikmund** [comment]
PR #2484 implements this
