### ISSUE TITLE
`AppWindow.Position` and `Size` should be in physical pixels

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#18638]
### Current behavior

`Position` and `Size` should be in physical points (e.g. not divided by `RasterizationScale`). Similarly `Move` and Resize` methods on `AppWindow` expect physical sizing as parameters.

### Works on UWP/WinUI

None

**Comment by MartinZikmund** [comment]
@ramezgerges I have done the WPF part in #18637, can you please check if we are handling it correctly on Linux?

For clarity, the `AppWindow.Position` and `AppWindow.Size` should be physical, but `Window.Bounds` should be scaled.

**Comment by ArchieCoder** [comment]
Does your Window position feature follow what WinUIEx do with a verification that the position is visible? This is useful when a user changes his monitor setup.

Thanks for adding this feature. I use it already.
