### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by arshadkazmi42** [unoplatform/uno#1864]
## On which page?
[README.md](https://github.com/unoplatform/uno/blob/master/README.md#uno-features)

## What's wrong?
Link to `MVVM Light Toolkit`, `Prism`, `ColorCode-Universal`, `The Xaml Controls Gallery (Source).` (source link) is broken.

## Any feedback?
If someone can provide the correct URL, I can send a PR for this

**Comment by ghuntley** [comment]
Thanks for the heads up @arshadkazmi42, those links are indeed 404 but won't be once https://github.com/unoplatform/uno/issues/1522 is completed. Let's leave them as is and I'll follow up with folks internally about expediting the move.
