### ISSUE TITLE
File new project with issues

### ISSUE THREAD

**Issue by saint4eva** [unoplatform/uno#1865]
## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

![image](https://user-images.githubusercontent.com/3264826/66909373-8e554880-f004-11e9-8b9e-805da8249eef.png)

**Comment by ghuntley** [comment]
Howdy @saint4eva that looks like a network connectivity issue during restoring packages from NuGet. Are you behind a firewall or enterprise proxy server? Can you please try again on a different internet connection or once again on the same connection.

**Comment by MartinZikmund** [comment]
I have seen this happen on slow or unstable connections before during very first NuGet restore.
