### ISSUE TITLE
Uno.Sdk should implicitly support SourceLink for library projects

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#18668]
### What would you like to be added

SourceLink "just works" without having to reference source link packages in MS SDK when using .net 8+. Uno.Sdk requires adding references to source link packages explictly.

### Why is this needed

Reduce friction from moving over from MS SDK.

### For which platform

WebAssembly, Android, iOS, Mac Catalyst, Skia (WPF), Skia (Linux X11), Skia (macOS), Skia (Linux Framebuffer), Skia (GTK), Windows (WinAppSDK)

**Comment by jeromelaban** [comment]
The uno.sdk is using the official Microsoft.Net.Sdk which provides this feature. How do you see that this is not supported by default?

**Comment by mikernet** [comment]
It requires the SourceLink nuget package to be added AFAICT. MS SDK does not.

**Comment by jeromelaban** [comment]
Sure, but how to do you see that it's not working? How do you validate that sourcelink is not enabled in your package?

**Comment by mikernet** [comment]
Hmm...can't repro now on a new project. Maybe something else was the issue before.
