### ISSUE TITLE
Tools folder missing causing WebAssembly publish errors

### ISSUE THREAD

**Issue by dongle-the-gadget** [unoplatform/uno#18670]
### Current behavior

Uno created a `%USERPROFILE%\.uno\emsdk\$(Project Name)` junction to `$(Project Path)\tools`, however the `tools` folder didn't exist leading to an error when running `dotnet publish -r browser-wasm`:
```
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\9.0.0-rc.2.24473.5\Sdk\BrowserWasmApp.targets(236,5): error : Emscripten from the workload is missing some paths: $(EmscriptenUpstreamBinPath)=C:\Users\Dongle\.uno\emsdk\UnoApp1\bin\ . Emscripten SDK is required for building native files.
```

### Expected behavior

Uno should create the `tools` folder and successfully publish.

### How to reproduce it (as minimally and precisely as possible)

1. Create an Uno app by the Visual Studio extension. Select the Blank app template, then change Framework to .NET 9, and Platforms to WebAssembly only.
2. Run `dotnet publish -r browser-wasm` on the project folder.
3. See the error

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

`Uno.Sdk` 5.5.32

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.12 Preview 5

**Comment by dongle-the-gadget** [comment]
Okay turns out this is a .NET issue, running `dotnet workload repair wasm-tools` fixed it.

**Comment by jeromelaban** [comment]
Thanks for the update. Note that publishing an uno app is done using https://platform.uno/docs/articles/uno-publishing-webassembly.html#packaging-your-app-using-the-cli, without specifying the runtime identifier (`-r`).
