### ISSUE TITLE
[publish] Cross arch winappsdk arm64 should not fail

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#18682]
I have a build pipeline with github actions that automatically builds for Win-ARM64 (and others). After updating to Uno 5.5 (from 5.4) it fails with this error:

`C:\Users\runneradmin\.nuget\packages\uno.sdk.extras\5.5.10\buildTransitive\Uno.Sdk.Extras.Publish.Windows.targets(19,3): error : Cross publishing self-contained WPF applications is not supported. `

The corresponding command in my YAML is:

```
- name: Build MAUI Windows arm64
   run: dotnet publish MyApp.csproj -c Release -f net8.0-windows10.0.19041 -p:Platform=arm64 -r win-arm64 --self-contained /p:GenerateAppxPackageOnBuild=true
```

Any ideas?

_Originally posted by @TopperDEL in https://github.com/unoplatform/uno/discussions/18681_

**Comment by cconner100** [comment]
I am also seeing this now on our x64 architecture builds.  Builds fine in vs2022

if I put it back to 5.3.108 it will build fine in x64 and arm64

My builds are done on a Mac running parallels in windows arm64

here is my build command
msbuild .\ZiiDMSAppMoc\ZiiDMSAppMoc.csproj /p:Configuration=Debug /p:Platform=x64   /p:GenerateAppxPackageOnBuild=true /p:AppxBundle=Never /p:UapAppxPackageBuildMode=SideLoading /p:AppxPackageDir=C:/temp/output/ /p:AppxPackageSigningEnabled=true /p:TargetFramework=net8.0-windows10.0.22621

**Comment by jeromelaban** [comment]
This will be fixed in an upcoming release of the Uno.SDK. In meantime, you can add the following to get you going: 

```xml
<PropertyGroup>
<UnoSdkExtrasVersion>5.5.11</UnoSdkExtrasVersion>
</PropertyGroup>

**Comment by cconner100** [comment]
works thanks ever so much
