### ISSUE TITLE
Adding Uno.Extensions.Maui.WinUI.Markup automatically if they use MAUI and C# markup

### ISSUE THREAD

**Issue by LuisAlfredo92** [unoplatform/uno#18700]
## What would you like to be added:
Adding Uno.Extensions.Maui.WinUI.Markup automatically automatically when you use MAUI Embedding and C# Markup

## Why is this needed:
Not to have to install it manually and deal with versions that can cause problems with Uno.Extensions.Maui.WinUI, and to be there since the beginning when creating a C# Markup project like other extensions

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [x] Build tasks

## Anything else we need to know?
I can add it myself, I'll do it

**Comment by jeromelaban** [comment]
Thanks for the report and effort to make a contribution!

This is a change that needs to be made in unoplatform/uno. It's managed directly by this block:

https://github.com/unoplatform/uno/blob/f9a5c1fe38aca7da9cac6787dea40cd34f11ed73/src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.targets#L42-L45

And most likely needs an additional block that checks for maui as well.
