### ISSUE TITLE
CalendarDatePicker displays date in a strange format on android if DateFormat is used

### ISSUE THREAD

**Issue by DavidM29** [unoplatform/uno#18717]
### Current behavior

If DateFormat is set on CalendarDatePicker, the date is displayed strangely on android. Works correctly on windows.
![image](https://github.com/user-attachments/assets/5a824213-654b-42ed-96d4-69f0d4c0cfe4)

### Expected behavior

Date should be displayed on android as it is displayed on windows.

### How to reproduce it (as minimally and precisely as possible)

- Add CalendarDatePicker on a page.
- Set DateFormat, for example `DateFormat="{}{day.integer}/{month.integer}/{year.full}"`.
- Choose any date on android.

Here is the small repro project:
[UnoApp1.zip](https://github.com/user-attachments/files/17645722/UnoApp1.zip)

### Workaround

Have not found any workarounds.

### Works on UWP/WinUI

Yes

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.11.4

**Comment by morning4coffe-dev** [comment]
@DavidM29 I've confirmed this issue, thank you for reporting it! It is happening only when using .integer on day and month on all Uno targets. I've created a PR https://github.com/unoplatform/uno/pull/18948 which should fix this issue.

**Comment by DavidM29** [comment]
Hello @morning4coffe-dev, tested this on latest `Uno.Sdk` (`5.5.56`) and it looks same as before. When will this fix be available?

**Comment by morning4coffe-dev** [comment]
@DavidM29 I think it will be available on 5.6+, can you try with Uno.Sdk [5.6.0-dev.298](https://www.nuget.org/packages/Uno.Sdk/5.6.0-dev.298)? I have also opened a follow-up PR which will also address time formatting issues https://github.com/unoplatform/uno/pull/19099

**Comment by agneszitte** [comment]
@jhanvi03, @Darsh0307 if you can test this issue with latest internal 5.6 stable please

**Comment by agneszitte** [comment]
I am **not** able to reproduce this issue with latest **Uno.Sdk 5.6.36**.
Behavior follows **WinAppSdk** for the other platforms now.

--- 
Tested with:
- Templates/SDK: **5.6.36**
- VS version: VS 2022 (64-bit) - Version **17.13.1**
- VS VSIX: [5.6.31](https://dev.azure.com/uno-platform/uno-private/_build/results?buildId=155709&view=results)
- [Issue18717.zip](https://github.com/user-attachments/files/18877616/Issue18717.zip)
- Platform(s): **WinAppSdk, Android, iOS, WebAssembly, Desktop, Desktop WSL**
- OS: **Windows**
