### ISSUE TITLE
Proper ProgressRingTemplateSettings implementation for WASM

### ISSUE THREAD

**Issue by gevart** [unoplatform/uno#1872]
## What would you like to be added:
Proper ProgressRingTemplateSettings implementation for WASM

## Why is this needed:
ProgressRing for Wasm was implemented with a stub for ProgressRingTemplateSettings in order to allow the default UWP style to work. For instance, it now has hard-coded parameters like EllipseDiameter or MaxSideLength. But I guess this is not a proper way to implement this class.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by xperiandri** [comment]
So does it work at all with any default setup? It crushed my app

**Comment by xperiandri** [comment]
``` XAML
<tc:Loading
    x:Name="loading"
    Grid.RowSpan="5"
    Grid.ColumnSpan="3"
    Background="#33000000"
    IsLoading="{Binding IsActive, ElementName=progressRing}">
    <ProgressRing
        x:Name="progressRing"
        Width="100"
        Height="100"
        HorizontalAlignment="Left"
        VerticalAlignment="Top"
        IsActive="True" />

</tc:Loading>
```
This progress ring does not appear on Android. Is it the same issue?

**Comment by gevart** [comment]
> This progress ring does not appear on Android. Is it the same issue?

I don't think so. This issue is WASM-only and, as far as I remember, ProgressRing worked on Android even a year ago.

**Comment by jeromelaban** [comment]
`Windows.UI.Xaml.ProgressRing` is now being deprecated in favor of `Microsoft.UI.Xaml.ProgressRing`.

**Comment by xperiandri** [comment]
WinUI 2+?

**Comment by francoistanguay** [comment]
Yes, we're now supporting WinUI ProgressRing.
