### ISSUE TITLE
[Desktop] DragStarting called on parent control rather than on child control

### ISSUE THREAD

**Issue by kucint** [unoplatform/uno#18765]
### Current behavior

This bug is present only on `Desktop` Framework, `WinAppSDK` works fine.

Create an `UIElement` that contains another `UIElement`.

![image](https://github.com/user-attachments/assets/7ccadcdb-dc22-4632-aa15-cb459ef38169)

Both of them have `DragStarting` event handler attached.
**Bug**: When the child is being dragged, the parent's handler is called rather than child's one.

```xaml
<Page x:Class="UnoDragStartingApp.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:UnoDragStartingApp"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <Frame
        BorderThickness="1"
        BorderBrush="Black"
        Background="LightCoral"
        Width="400"
        Height="300"
        HorizontalAlignment="Center"
        VerticalAlignment="Center"
        CanDrag="True"
        DragStarting="Frame_DragStarting">
        <Rectangle
            Fill="LightBlue"
            Stroke="Black"
            StrokeThickness="1"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
            Width="100"
            Height="80"
            CanDrag="True"
            DragStarting="Rectangle_DragStarting"/>
    </Frame>
</Page>
```

```cs
public sealed partial class MainPage : Page
{
    public MainPage()
    {
        this.InitializeComponent();
    }

    private void Frame_DragStarting(UIElement sender, DragStartingEventArgs args)
        => Debug.WriteLine("Frame_DragStarting");

    private void Rectangle_DragStarting(UIElement sender, DragStartingEventArgs args)
        => Debug.WriteLine("Rectangle_DragStarting");
}
```

I suppose, the same incorrect behavior is to be observed on others handlers like:
- DropCompleted
- DragEnter
- DragLeave
- PointerReleased
- ... other

### Expected behavior

When the child element is being dragged, the child's handler shall be called rather than parent's one.

### How to reproduce it (as minimally and precisely as possible)

MINIMAL REPRO PROJECT: [UnoDragStartingApp.zip](https://github.com/user-attachments/files/17703608/UnoDragStartingApp.zip)

STEPS TO REPRODUCE:
- run the App under `Desktop` Framework
- drag child element.
- observe that `Frame_DragStarting` method is called, expected `Rectangle_DragStarting` method is called

### Works on UWP/WinUI

Yes

### NuGet package version(s)

`"Uno.Sdk": "5.5.32"`

### Affected platforms

Skia (WPF)

**Comment by agneszitte** [comment]
@jhanvi03, @Darsh0307 if you can test this issue with latest internal 5.6 stable please
