### ISSUE TITLE
[WASM] Images inside of Borders are not getting clipped

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#18771]
### Current behavior

As of Uno.Sdk 5.6.0-dev.148, Images are not getting clipped properly on WASM

As a small sample, here is some XAML:

```xml
<utu:AutoLayout CornerRadius="4"
                Width="328"
                Background="Red">
  <Border Height="144">
    <Image Source="ms-appx:///Assets/Images/air_fryer_french_fries.png"
           VerticalAlignment="Center"
           HorizontalAlignment="Center"
           Stretch="UniformToFill" />
  </Border>
  <StackPanel>
    <TextBlock Text="Air Fryer French Fries" />
    <TextBlock Text="Air fryer french fries are the perfect way to make fries at home.." />
  </StackPanel>
</utu:AutoLayout>
```

It used to render like this:
![image](https://github.com/user-attachments/assets/035be8b4-1927-4f59-b409-758fcfb5c3ae)

Now it looks like this:
![image](https://github.com/user-attachments/assets/424dbd1e-aab4-41e0-b5e5-bd9e399ead1e)

Sample repro: 
[UnoApp103.zip](https://github.com/user-attachments/files/17733785/UnoApp103.zip)

**Comment by agneszitte** [comment]
@jhanvi03, @Darsh0307 if you can test this issue with latest internal 5.6 stable please
