### ISSUE TITLE
Uno-check 1.26.1.0 states there were a problem detected, but no problems are shown

### ISSUE THREAD

**Issue by digger73** [unoplatform/uno#18776]
### Current behavior

Updated VS2022 (17.12.0) to newest release along with uno-check.
Running uno-check results in:
`! There were one or more problems detected.
Please review the errors and correct them and run uno-check again.`

But no problems are shown during the checks. See below screenshot. Running uno-check again doesn't change the below result.

![image](https://github.com/user-attachments/assets/1b4090ab-0dc8-4260-9067-c6e0e0a40322)

### Expected behavior

If an problem is detected it would be shown by uno-check

### How to reproduce it (as minimally and precisely as possible)

Update VS2022 to 17.12.0
Update uno-check to 1.26.1.0
Run uno-check, the described behavior occurs.

### Works on UWP/WinUI

None

### IDE

Visual Studio 2022

### IDE version

17.12.0

**Comment by jeromelaban** [comment]
Thanks for the report, can you run using `--verbose` ?

**Comment by digger73** [comment]
> Thanks for the report, can you run using `--verbose` ?

Just done that, which results in:
`Install the [8.0.401] .NET SDK or update [C:\Users\dlerche.SUZLON\AppData\Local\Temp\uno-check-a749ae0e\global.json] to match an installed SDK.

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
System.Exception: Workload command failed: `dotnet workload update --print-rollback`
  at async (ValueTuple<string, string, string>[[]] id) DotNetCheck.DotNet.DotNetWorkloadManager.GetInstalledWorkloads()
     in /_/UnoCheck/DotNet/DotNetWorkloadManager.cs:102
  at async Task<DiagnosticResult> DotNetCheck.Checkups.DotNetWorkloadsCheckup.Examine(SharedState history) in
     /_/UnoCheck/Checkups/DotNetWorkloadsCheckup.cs:95
  at async Task<int> DotNetCheck.Cli.CheckCommand.ExecuteAsync(CommandContext context, CheckSettings settings) in
     /_/UnoCheck/CheckCommand.cs:178
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Checkup had Error status: dotnetworkloads-8.0.401

dotnetworkloads-8.0.401: Workload command failed: `dotnet workload update --print-rollback`
! There were one or more problems detected.
Please review the errors and correct them and run uno-check again.

Press Enter to finish...
`

If have attached the comple uno-check with --verbose.
[Uno Platform Check v1.26.1.log](https://github.com/user-attachments/files/17733195/Uno.Platform.Check.v1.26.1.log)

**Comment by jeromelaban** [comment]
Thanks. This explains the issue. .NET 9 has been released as part of 17.12, and .NET 8 is not present on your system anymore. We'll be publishing a new update of uno.check today, but in the meantime, can you try running:

```
dotnet tool update -g uno.check --version 1.27.0-dev.8
```

Then run uno-check again?

Thanks!

**Comment by digger73** [comment]
Did the visual studio update through VS Help->"check update" functionality in the VS UI.
