### ISSUE TITLE
 [WASM] TextBox does not properly keep the focus when in a Flyout/Popup

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#18790]
### Current behavior

Please see repo below: when upgrading from UNO 5.2 -> 5.3 the AutoSuggestBox is screwed up when clicking before starting to type: the selection logic no longer works. Same when updating the repo to .NET 9 and latest UNO 5.5.

[Minimal.zip](https://github.com/user-attachments/files/17743891/Minimal.zip)

@jeromelaban my team and I again spent a lot of time chasing down this regression. Together with the other regressions I reported earlier ([here ](https://github.com/unoplatform/uno/issues/18599)and [here](https://github.com/unoplatform/uno/issues/16928)) we're still forced to stay with UNO 5.1 (!). I'm happy to continue investing resources and time in chasing down UNO regressions, but I also would appreciate if the regressions would be taken care of in not too far future. Thanks in advance

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

**Comment by DierkDroth** [comment]
@jeromelaban to be clear: this is not just an issue but a regression. As such, this was working before and now no longer is working.

**Comment by jeromelaban** [comment]
Thanks. This is not an AutoSuggestBox issue, but rather a focus issue for textbox when located in a flyout/popup.

This s a specialized repro: https://playgroundcanary.z19.web.core.windows.net/#92ea19af which uses Uno 5.6-dev.

**Comment by DierkDroth** [comment]
Thanks @jeromelaban. That makes sense, since we saw 'weird' issues related to `TextBox `on `Flyouts` as well, but it ultimately was more efficient for us to isolate the issue on `AutoSuggestBox `... interesting

Nevertheless this is a regression, correct?

**Comment by DierkDroth** [comment]
Thanks for taking care @ramezgerges. We'll run tests as a build is available...

**Comment by DierkDroth** [comment]
@ramezgerges I just upgraded to 5.5.87 but found that the issue persists. Am I missing?

**Comment by ramezgerges** [comment]
This PR is not in any stable release (yet). It can try with a recent dev version (e.g. 5.6.0-dev.1063).

**Comment by DierkDroth** [comment]
@jeromelaban @ramezgerges thanks for clarification.
