### ISSUE TITLE
[DOTNET9] dotnet build causes error MSB4057: The target "_GetRestoreSettingsPerFramework" does not exist in the project.

### ISSUE THREAD

**Issue by EricKwon94** [unoplatform/uno#18796]
[UnoApp2.zip](https://github.com/user-attachments/files/17760707/UnoApp2.zip)

### Error Message
error MSB4057: The target "_GetRestoreSettingsPerFramework" does not exist in the project.

### Issue Summary:
When `net9.0-browserwasm` is included in the `TargetFrameworks`of the .csproj file, the following build commands fail:
`dotnet build UnoApp2.csproj -c:Release -f:net9.0-android -r:android-arm64`
`dotnet build UnoApp2.csproj -c Release -f net9.0-ios -r iossimulator-x64`

### Error Details:
- The build fails specifically when using -r:android-arm64 or -r:iossimulator-x64.
- If net9.0-browserwasm is removed from TargetFrameworks, the commands work correctly.
- The issue does not occur if the -r (runtime identifier) option is omitted.
- This problem does not occur with .NET 8; the same project builds successfully with .NET 8.

### Environment
.NET SDK Version: 9.0
VisualStudio 17.12.0
Windows 11

### Expected behavior

The project should build successfully with .NET 9 using the specified commands, regardless of whether `net9.0-browserwasm` is included in the `TargetFrameworks`.

### Works on UWP/WinUI

None

### Affected platforms

Android, iOS

### IDE

Visual Studio 2022, Visual Studio Code

**Comment by jeromelaban** [comment]
Thanks for the report.

This is likely a .NET SDK bug that we may not be able to fix from our end.

Still, in the meantime, it's best to set the RuntimeIdentifiers property:

```
dotnet build -c Release -f net9.0-ios -p:RuntimeIdentifiers=iossimulator-x64
```

**Comment by EricKwon94** [comment]
### Debugging Issue on Mac + VSCode with iOS Simulator
When debugging on Mac using VSCode with the iOS Simulator, the `-r:iossimulator-arm64` option is forcibly applied.
This causes the error mentioned above, making it impossible to debug in this setup.

Is there any way to resolve this issue?
Should I modify specific settings or apply additional flags?

Thank you in advance for your help! 🙏

**Comment by agneszitte** [comment]
@jhanvi03, @Darsh0307 if you can test this issue with latest internal 5.6 stable please
