### ISSUE TITLE
[Desktop] ColorAnimation not working

### ISSUE THREAD

**Issue by kucint** [unoplatform/uno#18802]
### Current behavior

On `Desktop` framework: `ColorAnimation` is not working
On `WinAppSdk` framework: works fine

```xaml
<Grid BorderThickness="3">
    <Grid.BorderBrush>
        <SolidColorBrush x:Name="SelectionFrameBorderBrush" Color="Transparent" />
    </Grid.BorderBrush>
    
    <VisualStateManager.VisualStateGroups>
        <VisualStateGroup x:Name="SelectionStates">
            <VisualState x:Name="Selected">
                <Storyboard>
                    <ColorAnimation Storyboard.TargetName="SelectionFrameBorderBrush" Storyboard.TargetProperty="Color" To="Red" Duration="0:0:0.2" />
                </Storyboard>
            </VisualState>
            <VisualState x:Name="Normal">
                <Storyboard>
                    <ColorAnimation Storyboard.TargetName="SelectionFrameBorderBrush" Storyboard.TargetProperty="Color" To="Transparent" Duration="0:0:0.2" />
                </Storyboard>
            </VisualState>
        </VisualStateGroup>
    </VisualStateManager.VisualStateGroups>

    <CheckBox Content="CheckBox"
              HorizontalAlignment="Center"
              VerticalAlignment="Center"
              IsChecked="False"
              Checked="CheckBox_Checked"
              Unchecked="CheckBox_Unchecked">
  </CheckBox>
</Grid>
```

```cs
  private void CheckBox_Checked(object sender, RoutedEventArgs e)
      => VisualStateManager.GoToState(this, "Selected", true);

  private void CheckBox_Unchecked(object sender, RoutedEventArgs e)
      => VisualStateManager.GoToState(this, "Normal", true);
```

### Expected behavior

On `Desktop` framework: `ColorAnimation` of brush opacity shall work as on `WinAppSdk`

### How to reproduce it (as minimally and precisely as possible)

MINIMAL REPRO PROJECT : [UnoColorAnimationApp.zip](https://github.com/user-attachments/files/17773839/UnoColorAnimationApp.zip)

STEPS TO REPRODUCE
- Run the app
- click on checkbox 
  - on `WinAppSdk` all is fine, animated Red Border appears
  - on `Desktop`: Red Border appears but without animation
     ![image](https://github.com/user-attachments/assets/dbaad1ab-444e-47e8-bad8-cab20f7ffb5a)

### Works on UWP/WinUI

Yes

### NuGet package version(s)

`"Uno.Sdk": "5.5.43"`
`"version": "9.0.100"` // dotnet

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

**Comment by agneszitte** [comment]
@jhanvi03, @Darsh0307 if you can test this issue with latest internal 5.6 stable please

**Comment by jhanvi03** [comment]
Verified with SDK/Template 5.6.11: A red border appears with animation when the checkbox is checked on both Desktop and WinAppSDK.

https://github.com/user-attachments/assets/48b7d826-8fec-4b3d-8f01-06fe9b543aee

**Comment by kucint** [comment]
Great! thanks!
