### ISSUE TITLE
[Android] Cannot use assets with a name starting with digits

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#1881]
## Current behavior
Using a shared asset that contains a number does not work, and no errors are provided.

## Expected behavior
As android does not support such assets names, the build should fail on such names.

## Additional information
To address this issue, taking a look at the `Uno.UI.Tasks` project where the generation of the assets happens can be useful. Failing the build at this point may be the best location.

## Environment

Nuget Package: 2.0-dev.x

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by consolelogreece** [comment]
I would like to try this one. Do I need to check for digits at the start of the asset name, or an digits at all inside the asset name?

**Comment by artemious7** [comment]
Hasn't this bug already been fixed?

I can see there was an attempt to fix this bug in PR #1903, which later was closed by another PR #3288. And #3288 says that the new behavior is "Android resources starting with a number or containing invalid characters **are now supported**."

**Comment by jeromelaban** [comment]
Yes, it's been fixed. All invalid characters are now mapped to `_` so that it works properly with android's naming scheme. Thanks for looking into it!
