### ISSUE TITLE
Cannot set Height/Width on custom Controls in UWP

### ISSUE THREAD

**Issue by NGame1** [unoplatform/uno#1882]
## Current behavior
```

            <GridView x:Name="GridItems" HorizontalAlignment="Center" SelectionMode="None" IsItemClickEnabled="True" Grid.Row="2" VerticalAlignment="Center">
                <GridView.ItemContainerStyle>
                    <Style TargetType="GridViewItem">
                        <Setter Property="Margin" Value="0"/>
                        <Setter Property="Padding" Value="1.5"/>
                    </Style>
                </GridView.ItemContainerStyle>
                <GridView.ItemTemplate>
                    <DataTemplate x:DataType="appmodels:GroupAddressClass">
                        <local:LightWidgetUC Title="{x:Bind Name}" win:Height="90" win:Width="90" Icon="&#xE924;" ios:Height="90"  ios:Width="90" android:Height="85" android:Width="85"/>
                    </DataTemplate>
                </GridView.ItemTemplate>
            </GridView>
```
Unknown member 'Height' on element 'LightWidgetUC'
Android and IOS properties are fine. only win: gives error
Nuget Package:
2.0.512-dev.3455

Package Version(s):

Affected platform(s):

- [ ] iOS 
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report? Could you provide the full build error ?

**Comment by NGame1** [comment]
build output: 
1>------ Skipped Build: Project: HomeControlApp.iOS, Configuration: Debug iPhone ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: HomeControlApp.UWP, Configuration: Debug x86 ------
3>------ Build started: Project: HomeControlApp.Wasm, Configuration: Debug Any CPU ------
2>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\Widgets\RoomItemPreviewUC.xaml(348,68): XamlCompiler error WMC0011: Unknown member 'Height' on element 'LightWidgetUC'
2>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\Widgets\RoomItemPreviewUC.xaml(348,84): XamlCompiler error WMC0011: Unknown member 'Width' on element 'LightWidgetUC'
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\Widgets\RoomItemPreviewUC.xaml.cs(33,14,33,22): warning CS0108: 'RoomItemPreviewUC.IsLoaded' hides inherited member 'FrameworkElement.IsLoaded'. Use the new keyword if hiding was intended.
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\Models\AppModels\GroupAddressClass.cs(55,50,55,65): warning CS0067: The event 'GroupAddressClass.PropertyChanged' is never used
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\Helpers\ModbusHelper.cs(12,21,12,42): warning CS0414: The field 'ModbusHelper._iswaitingforresponse' is assigned but its value is never used
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\App.xaml.cs(82,21,82,45): warning Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PreviousExecutionState is not implemented in Uno
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\App.xaml.cs(124,28,124,61): warning Uno0001: Windows.ApplicationModel.SuspendingOperation.GetDeferral() is not implemented in Uno
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\App.xaml.cs(126,13,126,30): warning Uno0001: Windows.ApplicationModel.SuspendingDeferral.Complete() is not implemented in Uno
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\App.xaml.cs(91,17,91,37): warning Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PrelaunchActivated is not implemented in Uno
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\Helpers\ApplicationSettingsHelper.cs(108,19,108,40): warning Uno0001: Windows.Storage.FileIO.WriteTextAsync(Windows.Storage.IStorageFile, string, Windows.Storage.Streams.UnicodeEncoding) is not implemented in Uno
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\Helpers\ApplicationSettingsHelper.cs(108,87,108,131): warning Uno0001: Windows.Storage.Streams.UnicodeEncoding.Utf8 is not implemented in Uno
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\Helpers\ApplicationSettingsHelper.cs(108,87,108,126): warning Uno0001: Windows.Storage.Streams.UnicodeEncoding is not implemented in Uno
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\Helpers\ApplicationSettingsHelper.cs(112,31,112,67): warning Uno0001: Windows.Storage.StorageFolder.GetFilesAsync() is not implemented in Uno
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\Helpers\ApplicationSettingsHelper.cs(116,34,116,54): warning Uno0001: Windows.Storage.FileIO.ReadTextAsync(Windows.Storage.IStorageFile, Windows.Storage.Streams.UnicodeEncoding) is not implemented in Uno
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\Helpers\ApplicationSettingsHelper.cs(116,61,116,105): warning Uno0001: Windows.Storage.Streams.UnicodeEncoding.Utf8 is not implemented in Uno
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\Helpers\ApplicationSettingsHelper.cs(116,61,116,100): warning Uno0001: Windows.Storage.Streams.UnicodeEncoding is not implemented in Uno
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\Widgets\ACWidgetUC.xaml.cs(45,30,45,50): warning Uno0001: Windows.UI.Xaml.FrameworkElement.Tag is not implemented in Uno
3>C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Shared\Widgets\ACWidgetUC.xaml.cs(47,30,47,72): warning Uno0001: Windows.UI.Xaml.FrameworkElement.Tag is not implemented in Uno
3>HomeControlApp.Wasm -> C:\Users\ngame\source\repos\ThreeIdiots\HomeControlApp\HomeControlApp\HomeControlApp.Wasm\bin\Debug\netstandard2.0\HomeControlApp.Wasm.dll
3>Restore completed in 55.93 ms for C:\Users\ngame\AppData\Local\Temp\mono-wasm-11f75e52606\packager_build\packager2.csproj.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.6.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
3>Done building project "packager2.csproj" -- FAILED.
3>Done building project "HomeControlApp.Wasm.csproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 1 up-to-date, 1 skipped ==========

Also this is another error:
XDG0032	The property "Height" does not exist in the "http://schemas.microsoft.com/winfx/2006/xaml/presentation" namespace.

Same errors for both Height and Width properties

**Comment by NGame1** [comment]
Isn't it possible to add another namespace for it like android and IOS for Win too

**Comment by jeromelaban** [comment]
The Windows XAML parser is not that maleable, unfortunately.

**Comment by davidjohnoliver** [comment]
@NGame1 It's possible to avoid this error by specifying the owner of the property:
```xaml
		<local:LightWidgetUC Title="{x:Bind Name}"
							 win:FrameworkElement.Height="90"
							 win:FrameworkElement.Width="90"
							 Icon="&#xE924;"
							 ios:Height="90"
							 ios:Width="90"
							 android:Height="85"
							 android:Width="85" />
```

**Comment by NGame1** [comment]
> @NGame1 You can resolve this error by specifying the owner of the property:
> 
> ```
> 		<local:LightWidgetUC Title="{x:Bind Name}"
> 							 win:FrameworkElement.Height="90"
> 							 win:FrameworkElement.Width="90"
> 							 Icon="&#xE924;"
> 							 ios:Height="90"
> 							 ios:Width="90"
> 							 android:Height="85"
> 							 android:Width="85" />
> ```


I used <Win:DataTemplate> <androi:DataTemplate> and ios one but your solution is so much better. Really tricky. Thanks

**Comment by jeromelaban** [comment]
For conditional XAML support, please follow https://github.com/unoplatform/uno/issues/789
