### ISSUE TITLE
TemplatedParent not resolved correctly in Button.Flyout

### ISSUE THREAD

**Issue by juliecantin** [unoplatform/uno#1884]
## Current behavior

Inside the content of a Button.Flyout, a binding with TemplatedParent as the RelativeSource will fail.

## Expected behavior

A binding with TemplatedParent will resolve correctly.

## How to reproduce it (as minimally and precisely as possible)

https://github.com/jcantin-nventive/templated-parent-binding
Launch the app and click on the "Click me" button

- On UWP, the value displayed is 5, which is expected

- On iOS/Android, the value displayed is "The binding has failed", which accurately describes the situation.

The crux of the issue is the custom control [style](https://github.com/jcantin-nventive/templated-parent-binding/blob/master/TemplatedParentBinding/TemplatedParentBinding.Shared/MainPage.xaml)

## Environment

Nuget Package:

Package Version(s): 1.45.0

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [x] 2017 (version: 15.9.11)
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by amaid** [comment]
This issue also exists in WASM where TemplatedParent isn't being resolved correctly in WASM but working in UWP

Repro steps: 
1. Create an ContentControl.
2. Define datatemplate for the ContentTemplate and bind it to any TemplatedParent property, in my case its just simple string.
as follows:

XAML:
```xaml
<ContentControl x:Name="MainContent" HorizontalContentAlignment="Stretch" Grid.Row="1">
            <ContentControl.ContentTemplate>
                <DataTemplate>
                    <TextBlock Foreground="#000000" Text="{Binding Path=DataContext, RelativeSource={RelativeSource TemplatedParent}, Mode=OneWay,FallbackValue='Binding failed'}"/>
                </DataTemplate>
            </ContentControl.ContentTemplate>
        </ContentControl>
```


Output
![image](https://user-images.githubusercontent.com/15306909/141745244-da0aaef1-28a7-4242-b26a-69c8a7f88908.png)
