### ISSUE TITLE
[wasm] Drag gestures starting from above/with existing selection are not captured correctly

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#18854]
### Current behavior

On WebAssembly, when there is selection _underneath or around_ a control that typically uses drag gesture (eg: ScrollBar or Slider), the drag gesture will only work for the 1st frame/tick/delta, subsequent pointer capture events are lost, and there is an undesired browser dragging preview following the cursor:
![wasm selection drag](https://github.com/user-attachments/assets/626e72e8-f70f-4f2f-8b50-1b5254fb23cc)

### Expected behavior

^ probably shouldn't happen?
at least, there should be an easy way to disable this behavior, whether this would be disabled by default is subject of discussion

### How to reproduce it (as minimally and precisely as possible)

```xml
<StackPanel Spacing="16">
    <TextBlock Text="selectable text: // select from here" IsTextSelectionEnabled="True" />

    <!-- some controls that typically use drag gestures -->
    <Slider />
    <ScrollBar Orientation="Horizontal" IndicatorMode="MouseIndicator" />

    <TextBlock Text="selectable text: // to there"  IsTextSelectionEnabled="True" />
</StackPanel>
```
- goto: https://playgroundcanary.z19.web.core.windows.net/#f68b7cf6
- select from the 1st textblock to the 2nd textblock
- try to drag with the slider's or the scrollbar's thumb
- notices the drag work very poorly

### Workaround

from the javascript side, call `e.preventDefault()` in the `pointerdown` event handler of any impacted control

just run this command from the dev console of the browser:
```js
document
	.querySelector('[xamltype$=ContentControl]')
	.querySelectorAll('[xamltype$=ScrollBar], [xamltype$=Slider]')
	.forEach(x => x.addEventListener('pointerdown', e => e.preventDefault()))
```

### Works on UWP/WinUI

No

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI@5.5.37

### Affected platforms

WebAssembly

**Comment by dr1rrb** [comment]
Humm, actually able to repro ... but on edge only!

**Comment by agneszitte** [comment]
@jhanvi03, @Darsh0307 if you can test this issue with latest internal 5.6 stable please
