### ISSUE TITLE
`net9.0-browserwasm` build raising a WasmAssembliesToBundle error with Uno Library

### ISSUE THREAD

**Issue by SongOfYouth** [unoplatform/uno#18860]
### Current behavior

when build for browserwasm, it raises `WasmAssembliesToBundle item is empty. No assemblies to process` error.

### How to reproduce it (as minimally and precisely as possible)

Add a net9.0 Uno Library and build it.

### Works on UWP/WinUI

None

### Environment

Other

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.12.0

**Comment by SongOfYouth** [comment]
with my attempt, net9.0-browserwasm only works for `<OutputType>exe</OutputType>` but not `<OutputType>Library</OutputType>`

**Comment by jeromelaban** [comment]
Thanks for the report, this is fixed in https://github.com/unoplatform/uno/pull/18806, a service release will be available soon.

**Comment by SongOfYouth** [comment]
> ```
> <IsBrowserWasmProject>false</IsBrowserWasmProject>
> ```

Thanks fort the timly reply, and it works!
