### ISSUE TITLE
wasm not support the FrameworkReference of Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by SongOfYouth** [unoplatform/uno#18874]
### Current behavior

When build a net9.0-browserwasm project, add a FrameworkReference in .csproj:
```xml
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```
it raise an error:
dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(495,5): error NETSDK1082: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.

### Expected behavior

can be built noninductively.

### Works on UWP/WinUI

None

### Environment

Other

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by SongOfYouth** [comment]
> Thanks for the report.
> 
> This is done on purpose as the tooling included in aspnetcore is not compatible with the wasm environment. Could you explain why you need this?

I have used some abstractions of aspnetcore to create webapi request code on client at net8 or earlier,since netstandard is not avaliable begin net8. now i removed them.

**Comment by jeromelaban** [comment]
If you removed them, you do not need the framework reference anymore, correct?

**Comment by SongOfYouth** [comment]
> If you removed them, you do not need the framework reference anymore, correct?

Yes. but it may be a common problem wheether referencing the  aspnetcore framewrork or winform (for winui at net9 as we know).
