### ISSUE TITLE
The Uno Platform VS extension use of the VisualStudio.Extensibility model is misconfigured

### ISSUE THREAD

**Issue by matteo-prosperi** [unoplatform/uno#18882]
### Your feedback

Hello,
I'm Matteo from the Visual Studio Extensibility team in Microsoft. I work on the new [VisualStudio.Extensibility](https://learn.microsoft.com/en-us/visualstudio/extensibility/visualstudio.extensibility/visualstudio-extensibility?view=vs-2022) model.

I noticed that the [Uno Platform](https://marketplace.visualstudio.com/items?itemName=unoplatform.uno-platform-addin-2022) VS extension references the [VisualStudio.Extensibility packages](https://www.nuget.org/packages/Microsoft.VisualStudio.Extensibility#readme-body-tab) and it even includes the `.vsextension/extension.json` that is used to declare capabilities of a VisualStudio.Extensibility extension.

I also noticed that the `extension.vsixmanifest` file is not correctly configured if you want to leverage any VisualStudio.Extensibility features.

If you are interested in exploring using the VisualStudio.Extensibility capabilities, I would gladly provide any guidance you may need.

Thanks
Matteo

**Comment by MartinZikmund** [comment]
@matteo-prosperi thank you for this nice offer! Tagging @jeromelaban and @nickrandolph

**Comment by matteo-prosperi** [comment]
@jeromelaban, I noticed that the `<Installation>` tag in the `extension.vsixmanifest` doesn't include
```
<Installation ExtensionType="VSSDK+VisualStudio.Extensibility">
```
which is documented [here](https://learn.microsoft.com/en-us/visualstudio/extensibility/visualstudio.extensibility/get-started/in-proc-extensions?view=vs-2022#package-manifest) (that entire doc page is probably very relevant to what you may be trying to achieve).

There aren't build errors for this type of misconfiguration since you are likely handcrafting your VSIX content and vsixmanifest, which is an advanced scenario. The Visual Studio template described [here](https://learn.microsoft.com/en-us/visualstudio/extensibility/visualstudio.extensibility/get-started/create-your-first-extension?view=vs-2022) is the best place to start with authoring an extension that uses both VisualStudio.Extensibility and VSSDK. But some of the scenarios you may be looking at may be more advanced and currently undocumented. Feel free to reach out to discuss what are your goals.

**Comment by jeromelaban** [comment]
Thanks for the hints! Looks like we were only missing the `ExtensionType`. 

So far, this extension is adding simple menus and show  top "info bars" to the user. The rest is managed separately by add-ons that are coming from nuget packages.

**Comment by jeromelaban** [comment]
@matteo-prosperi making the ExtensionType change causes this specific build error:

```
VSSDK : error VSSDK1062: Schema validation error for extension.vsixmanifest'. The 'ExtensionType' attribute is not declared. 
```

Would you know what we could be missing?

**Comment by matteo-prosperi** [comment]
Most likely, you need to use a newer version of the Microsoft.VSSDK.BuildTools package which would be aware of the new attribute in the vsixmanifest. Anything starting with the stable 17.9 package should work

**Comment by matteo-prosperi** [comment]
Other things that you will need to fix: a VisualStudio.Extensibility extension is supposed to package some of it's own dependencies (you can look at what DLLs are packaged in the VSIX created by your VisualStudio.Extensibility project). So you will need to add those. Since those are .NET 8 assemblies, it's preferable to put the VisualStudio.Extensibility extension DLL and its dependencies in a separate folder to avoid collisions and confusion with the VSSDK assemblies for the rest of your extension. You will then need to update the path of the DLL in the extension.json to match the new path.

**Comment by jeromelaban** [comment]
Thanks @matteo-prosperi! We've been able to integrate the change, we'll be publishing an update soon!
