### ISSUE TITLE
[Linux Skia] can not scale by accessibility "large text" properly and left white border

### ISSUE THREAD

**Issue by HeZeBang** [unoplatform/uno#18884]
### Current behavior

When "Large Text" accessibility is turned on, the elements won't be scaled properly. The elements rendered wrongly and left white border like below:

![image](https://github.com/user-attachments/assets/2f44932f-96b1-454f-8da7-df8b133537fb)

![image](https://github.com/user-attachments/assets/f1581b29-6e96-4c80-ba4f-d1e9c48a1ecf)

While the cursor recognition is still "correct", as the button can be clicked just in the center of the window, which means there's just rendering problem.

![image](https://github.com/user-attachments/assets/39129a8b-4512-454c-b12e-f6a7f9506565)

> Test on manjaro with Gnome 46.5 + wayland

### Expected behavior

The elements should be rendered correctly.

### How to reproduce it (as minimally and precisely as possible)

`dotnet new unoapp` and debug with `Uno Platform Desktop Debug`

### Workaround

Switch off accessibility

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Skia (Linux X11)

### IDE

Visual Studio Code

**Comment by ramezgerges** [comment]
@HeZeBang X11 scaling on XWayland is known to be problematic, and I'm not sure what the "Large Text" feature specifically does and how it gets translated from Wayland into the X11 world, but I've opened the PR that _might_ fix your issues. Let us know if it doesn't.
