### ISSUE TITLE
Cannot override inherited member 'BindableUIView.Dispose(bool)'

### ISSUE THREAD

**Issue by kakone** [unoplatform/uno#1888]
Hello,

I inherit from the Control class and I would like to override the Dispose(bool disposing) method to free up some things. In Android, there is no problem but in iOS, the method is marked 'sealed' (due to this [line](https://github.com/unoplatform/uno/blob/342eaf1d69f790cbf865039d51678a9b4bac1fbd/src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs#L593) I think).

Why is it 'sealed' ? Could you remove it ?

Cordially,
Stephane.

**Comment by jeromelaban** [comment]
Hi @kakone! Thanks for this report!

Unfortunately no, this method is sealed on purpose, as depending on it can create very erratic behaviors on iOS as well as Android, as both do use it to perform unmanaged cleanup.

If you need still this method, you can declare your own by resetting the inheritance chain using the `new` keyword.
