### ISSUE TITLE
[Android] Pressing Buttons with native styles crashes the app

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#1891]
## How to reproduce it (as minimally and precisely as possible)

```xaml
<Button xamarin:Style="{StaticResource NativeDefaultButton}"/>
```

Press button

(Same observed for RadioButton, CheckBox etc with native styles)

## Current behavior

App crashes

## Expected behavior

Preferably, doesn't crash, button does button things

## Notes

Seems to be a regression from #1256 .

Crash comes from here: https://github.com/unoplatform/uno/blob/2570a96d808f84613e33c090d31d3af45e8b8123/src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.Android.cs#L52

`_nativeEvent` is null.

## Environment

Nuget Package: 

Package Version(s): 2.0.512-dev.3461

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
There is no UI Test validation of this scenario, one testing native resources should be added.
