### ISSUE TITLE
使用geolocator.GetGeopositionAsync() 出现   No Network Location Provider is installed!NLP is necessary for network location fixes

### ISSUE THREAD

**Issue by Xiaolei97** [unoplatform/uno#18946]
### Current behavior

使用geolocator.GetGeopositionAsync() 获取位置信息时出现No Network Location Provider is installed!NLP is necessary for network location fixes 
![0a559268b87c53c82b94b26073f1697](https://github.com/user-attachments/assets/1187e0f7-84f5-4e96-85cb-11aee159a4f0)

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
Thanks for the report. This message is not coming from Uno and most likely is from the OS itself. Is there something specific for this device that could cause this?
