### ISSUE TITLE
Remove the space between "world" and "!" in default template

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1895]
## What would you like to be added:

Is is a super-minor issue, but it is triggering my OCD for a while now 😀 . There is a space between the "world" and "!" in the default Uno solution template's MainPage.xaml.

## Why is this needed:

OCD

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [x] Solution Templates

**Comment by MartinZikmund** [comment]
I will let @HanamiM do this as a Hacktoberfest issue 👍

**Comment by MartinZikmund** [comment]
Oh, @ghuntley seems we got 3 PRs 😅 . What now?

**Comment by ghuntley** [comment]
@MartinZikmund typically - merge whichever one matches the quality bar and doesn't have merge conflicts 😅

**Comment by ghuntley** [comment]
@MartinZikmund btw _lovely_ work. It's important to create easy issues like this one - even if they take more time than fixing the problem yourself.
