### ISSUE TITLE
NET9 WebAssebmly and Skia

### ISSUE THREAD

**Issue by navio-n** [unoplatform/uno#18953]
### Current behavior

Added Skia Feature to <UnoFeatures>

Error:
CompileError: WebAssembly.compileStreaming(): Compiling function #16743:"mono_ppdb_load_file" failed: expected 0 elements on the stack for fallthru, found 4 @+6151113

### Expected behavior

Should be able to add Skia to NET9

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by navio-n** [comment]
Where to put that?
Thank you

**Comment by jeromelaban** [comment]
See an example here: https://github.com/unoplatform/Uno.Gallery/blob/86ace9002dba747d020575fa2eb003b9da58b51e/Uno.Gallery/Uno.Gallery.csproj#L179

**Comment by navio-n** [comment]
I removed Condition=" $(NETCoreSdkVersion.Contains('rc.2')) and it works. Thanks
