### ISSUE TITLE
XamlCodeGenerator - Attached property of nullable int type

### ISSUE THREAD

**Issue by kakone** [unoplatform/uno#1896]
Hello,

In my Uno class library (using the last prerelease of Uno.UI), I have a custom attached property like this :
```csharp
public partial class NullableIntHelper
{
    public static readonly DependencyProperty NullableIntProperty = DependencyProperty.RegisterAttached(
         "NullableInt", typeof(int?), typeof(NullableIntHelper), new PropertyMetadata(0));
    public static int? GetNullableInt(DependencyObject d)
    {
        return (int?)d.GetValue(NullableIntProperty);
    }
    public static void SetNullableInt(DependencyObject d, int? value)
    {
        d.SetValue(NullableIntProperty, value);
    }
}
```

If I use it in a XAML file (`local:NullableIntHelper.NullableInt='19'`), I have an exception with the XamlCodeGenerator :
```
System.Exception: Unable to convert 19 for NullableInt with type int?
MSBUILD : error :    at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildLiteralValue(INamedTypeSymbol propertyType, String memberValue, XamlMemberDefinition owner, String memberName, String objectUid)
```

If I use an int value instead of int?, there is no problem.

Cordially,
Stephane.

**Comment by jeromelaban** [comment]
Thanks for the report!

Indeed, it seems nullable types need to be handled in the type converter here:
https://github.com/unoplatform/uno/blob/8f776ba4616b9eb2e3bbca201b434adc2243f677/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L2986

**Comment by ghuntley** [comment]
@kakone are you comfortable with sending in a pull-request to the `XamlFileGenerator`?

**Comment by kakone** [comment]
Yes, I'm going to look at this source code and I will send a PR.
