### ISSUE TITLE
[Desktop] Translation not working when window shown for the first time

### ISSUE THREAD

**Issue by kucint** [unoplatform/uno#18998]
### Current behavior

Create simple app, exactly as [learn.microsoft.depth-shadow](https://learn.microsoft.com/en-us/windows/apps/design/layout/depth-shadow#themeshadow-in-other-elements) proposes it:

```xaml
<ScrollViewer>
    <Grid Background="White">
        <Grid.Resources>
            <ThemeShadow x:Name="SharedShadow" />
        </Grid.Resources>

        <Grid x:Name="BackgroundGrid" Background="{ThemeResource ApplicationPageBackgroundThemeBrush}" />

        <Rectangle x:Name="Rectangle1" Height="100" Width="100" Fill="Turquoise" Shadow="{StaticResource SharedShadow}" />

        <Rectangle x:Name="Rectangle2" Height="100" Width="100" Fill="Turquoise" Shadow="{StaticResource SharedShadow}" />
    </Grid>
</ScrollViewer>
```

```cs
private void MainPage_Loaded(object sender, RoutedEventArgs e)
{
    /// Add BackgroundGrid as a shadow receiver and elevate the casting buttons above it
    SharedShadow.Receivers.Add(BackgroundGrid);

    Rectangle1.Translation += new Vector3(0, 0, 16);
    Rectangle2.Translation += new Vector3(120, 0, 132);
}
```

On `WindowsAppSDK` it shows two rectangles as expected:
![image](https://github.com/user-attachments/assets/40dbcb08-22ca-4d9f-b966-d37044eb1f9d)

On `Desktop` it shows two rectangles that overlap:
![image](https://github.com/user-attachments/assets/0c3ae4dc-1efe-4474-af86-6fd1eb160f9c)

Then, resize the main window to trigger content refresh: two rectangles are shown as expected:
![image](https://github.com/user-attachments/assets/62323090-63d3-496c-81ec-8667fd182243)

### How to reproduce it (as minimally and precisely as possible)

MINIMAL REPRO PROJECT: [UnoShadowApp.zip](https://github.com/user-attachments/files/18008249/UnoShadowApp.zip)

### Works on UWP/WinUI

Yes

### NuGet package version(s)

`"Uno.Sdk": "5.5.49"`

### IDE

Visual Studio 2022

**Comment by agneszitte** [comment]
@jhanvi03, @Darsh0307 if you can test this issue with latest internal 5.6 stable please
