### ISSUE TITLE
System.TypeInitializationException when using SkiaSharp in net9.0-browserwasm

### ISSUE THREAD

**Issue by nksharma1999** [unoplatform/uno#18994]
### Current behavior

Platform: net9.0 wasm

<img width="337" alt="image" src="https://github.com/user-attachments/assets/4205ed2f-fba4-44e0-9506-b5e40abd079d">

### Error

System.TypeInitializationException: The type initializer for 'SkiaSharp.SKFontStyle' threw an exception.
 ---> System.DllNotFoundException: libSkiaSharp
   at SkiaSharp.SKFontStyle..ctor(Int32 weight, Int32 width, SKFontStyleSlant slant)
   at SkiaSharp.SKFontStyle..ctor(SKFontStyleWeight weight, SKFontStyleWidth width, SKFontStyleSlant slant)
   at SkiaSharp.SKFontStyle.SKFontStyleStatic..ctor(SKFontStyleWeight weight, SKFontStyleWidth width, SKFontStyleSlant slant)
   at SkiaSharp.SKFontStyle..cctor()
   --- End of inner exception stack trace ---

### Expected behavior

Required UI:
<img width="829" alt="image" src="https://github.com/user-attachments/assets/1a121ef2-ffbf-42c0-b487-655658670bcc">

### How to reproduce it (as minimally and precisely as possible)

1. Run the provided code in a net9.0-browserwasm project.
2. Observe the error in the console.

Code: 

```
private ObservableCollection<PieSeries<int>> CreatePieSeries() {
	var systemValues = new[] { random.Next(1, 100), random.Next(1, 100), random.Next(1, 100) };
	var fillColors = new[] { 
		TurbineStatusColorCodes.SYSTEM_NOT_OK_COLOR,
		TurbineStatusColorCodes.SYSTEM_OK_COLOR,
		TurbineStatusColorCodes.NOCOMM_COLOR 
	};
	var labelColors = new[] { SKColors.White, SKColors.Black, SKColors.Black };

	return PieChartHelper.CreatePieSeries(systemValues, fillColors, labelColors);
}
```

```
public static class PieChartHelper {
	private const int MAX_RADIAL_COLUMN_WIDTH = 10;
	private const int DATA_LABELS_FONT_SIZE = 7;
	private const string FONT_FAMILY = "Arial";


	public static ObservableCollection<PieSeries<T>>? CreatePieSeries<T>(T[] values, string[] colors, SKColor[] labelColors) {
		if (values == null || colors == null || labelColors == null) {
			return null;
		}

		var minLength = Math.Min(values.Length, Math.Min(colors.Length, labelColors.Length));

		var pieSeries = new ObservableCollection<PieSeries<T>>();

		for (var i = 0; i < minLength; i++) {
			try {
				pieSeries.Add(CreatePieSeriesItem(values[i], colors[i], labelColors[i]));
			}
			catch (Exception ex) {
				Console.WriteLine($"Error creating PieSeries item: {ex}");
			}
		}

		return pieSeries;
	}


	private static PieSeries<T> CreatePieSeriesItem<T>(T value, string fillColor, SKColor labelColor) {
		try {
			return new PieSeries<T> {
				Values = new[] { value },
				MaxRadialColumnWidth = MAX_RADIAL_COLUMN_WIDTH,
				Fill = new SolidColorPaint(SKColor.Parse(fillColor)),
				DataLabelsPaint = new SolidColorPaint(labelColor) {
					SKTypeface = SKTypeface.FromFamilyName(FONT_FAMILY, SKFontStyle.Bold)
				},
				DataLabelsSize = DATA_LABELS_FONT_SIZE,
				DataLabelsFormatter = point => point.Coordinate.PrimaryValue.ToString()
			};
		}
		catch (Exception ex) {
			Console.WriteLine(ex);
			return new PieSeries<T>();
		}
	}
}
```

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by MartinZikmund** [comment]
@nksharma1999 Are you referencing the `SkiaSharp.Views.Uno.WinUI` NuGet package in your `.csproj`?

**Comment by nksharma1999** [comment]
@MartinZikmund i am using `LiveChartsCore.SkiaSharpView.Uno.WinUI`

**Comment by jeromelaban** [comment]
@nksharma1999 you mention a provided project, but it does not seem to be attached. Can you provide it?
