### ISSUE TITLE
error : Member modifier 'static' must precede the member type and name	UnoApp1 (net8.0-desktop)	 

### ISSUE THREAD

**Issue by blackholeearth** [unoplatform/uno#19015]
### Current behavior
 

i created new project.    Edit Proj File -> 
disabled  everyplatform except   --desktop  (which i assume is wpf)  .. 

i only want it to work on  wpf  ... its not running...  

i see this error 

`````````
Error (active)	
CS1585	
Member modifier 'static' must precede the member type and name	UnoApp1 (net8.0-desktop)	

D:\..........\UnoApp1\UnoApp1\obj\Debug\net8.0-desktop\Uno.Extensions.Markup.Analyzers\Uno.Extensions.Markup.Analyzers.Generators.HotReloadModuleInitializerGenerator\UnoApp1.MarkupModuleInitializer.g.cs	13	

``````````

question?
does this  work for only wpf   ,,,,  witout installing   maui workload..

currently i only installed desktop workload.
win11 latest sdk

**edit**
i have installed maui .. i am still getting error..

i think this is related to generators.. its generating buggy code..  

### Expected behavior

it should work..

### How to reproduce it (as minimally and precisely as possible)

create a uno porject >  press f5  

### Environment  

windows 11

### NuGet package version(s)

![Adsız](https://github.com/user-attachments/assets/6ba3afe8-c626-4d8b-b11c-a0eb797c9495)

### Affected platforms

Skia (WPF)

### IDE

vs 2022   - v17.11.5

![image](https://github.com/user-attachments/assets/60ddfe32-bccf-4787-bea9-8f053fec1b7d)

**Comment by DevTKSS** [comment]
did you run uno-check successfully?

**Comment by blackholeearth** [comment]
the point is .. i dont wanna download maui or android sdk s which i will not use ....
i want to start lean  just with deskotp platform  wpf or winforms ...... with LESS GB downloads to waste...

if i like uno plat... i might go ALL in...    Download those big SDK Files,,, LATER..
 
-------------

> did you run uno-check successfully?

yes it finds missing things . 

![unochc](https://github.com/user-attachments/assets/41c0f1df-da06-413f-9a55-1e27df87ac2b)

**Comment by blackholeearth** [comment]
**i think this is full command which i dont need... but here you go...**


**cmd::**  uno-check  

yes it finds missing things . 

 
![1](https://github.com/user-attachments/assets/643fc14b-040a-4437-a8c3-d2a3dcc89d26)
![2](https://github.com/user-attachments/assets/6133d340-70c9-46ea-a8c8-bcadd1524dc6)
![3](https://github.com/user-attachments/assets/275633ea-c1f4-44ea-ba88-1f0785eb2d45)

**Comment by DevTKSS** [comment]
Dont know if this is even possible to not do, but could you update your visual studio at least (e.g. from its installer) and install the uno extension from the vs marketplace? this could maybe add the needed uno sdk, which seems to also be skipped
if this not works, someone of the uno team might have a look on your case, dont know if it is possible to do what you want

**Comment by DevTKSS** [comment]
Just read "winforms" somewhere in your text...
Dont know if you read this already in docs or similar, uno is mostly building on top of winui and wpf is supported via skia as far as i know (no .net Framework, check uno docs for that). I am normally building to desktop target instead of directly windows, but the main difference beside the targets themselves you should look into is the markup for ui you want to use (in my own opinion xaml has more resources so far) which is xaml or c# and the application structure you might want to use. For the structure, you can also choose codebehind, but very less guides are doing so and the mvvm might be a good start. Then you will have to choose your ui styles library which is material 3 (google made) or fluent, but as far as i did see, you have more options when choosing material because of the theme resources you can define more freely

**Comment by DevTKSS** [comment]
@blackholeearth would you mind to maybe add comments to your issue here instead of changing its title every few hours/every day? What you are described later is not at all matching the title so maybe you should update this and also add the issue you are confronted with at latest state here as comment for possible uno team members to better& more quickly see whats up to this issue, so they can help you at best they can

**Comment by blackholeearth** [comment]
issue is unrelated tto wpf ... ,,  i still see that error , even if i create  new uno App from Scratch... i think its about  nuget dll version mismatch.....   

uno cant understand that...

i just  gave up this. wont use ...

trying to learn maui  CS markup. from james monte.... from youtube... ...

can close this if you want...

**Comment by jeromelaban** [comment]
@blackholeearth It looks like you're having some sort of .NET version mismatch when building. We're currently upgrading our experience to make uno-check more specialized to the solution you're building, but could you try running this:

```
uno-check --tfm net9.0-desktop
```

This will run only for the desktop. The "wpf" target you've been using has been deprecated in Uno 5.3.

Once you've

**Comment by blackholeearth** [comment]
[msbuild.zip](https://github.com/user-attachments/files/18100689/msbuild.zip)

**Comment by jeromelaban** [comment]
Thanks for the update!

It looks like there's something in the environment that causes this issue to happen, and could you go there: 

![image](https://github.com/user-attachments/assets/0fcb93e7-d48b-491f-b138-c40411786104)

And post the contents of the file that opens when you double click on it?

Thanks!

**Comment by blackholeearth** [comment]
````csharp

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoApp1
{
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
    ınternal static partial class __MarkupModuleInitializer
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        public static void Initialize()
        {
            #if !IS_HOT_RELOAD_DISABLED && (DEBUG || IS_HOT_RELOAD_ENABLED)
	var isHotReloadEnabled = true;
#else
	var isHotReloadEnabled = false;
#endif
	global::Uno.Extensions.Markup.Internals.ModuleConfiguration.Configure("UnoApp1", isHotReloadEnabled);        }
    }
}


````

**Comment by jeromelaban** [comment]
This is a **very** interesting bug! I'm guessing that you're on a Turkish system, which may explain why there's the `ınternal ` instead of `internal`.

It should be easy to fix, we'll take a look and push a new update to our Uno 5.5.

Thanks for the troubleshooting!

**Comment by blackholeearth** [comment]
so should i wait new vs2022 uno extension update??

or just wait it in the nuget packages??

**Comment by jeromelaban** [comment]
It will be an [uno.sdk package](https://platform.uno/docs/articles/upgrading-nuget-packages.html#projects-using-the-unosdk) update.
