### ISSUE TITLE
Adding MauiEmbedding to an existing project needs to be updated for single-project Uno Apps

### ISSUE THREAD

**Issue by trydalch** [unoplatform/uno#19076]
### On which page?

https://platform.uno/docs/articles/external/uno.extensions/doc/Overview/Maui/MauiOverview.html

### What's wrong?

All new uno apps are created using the single-project architecture. The docs should explain how to add maui embedding to apps using this architecture.

**Comment by jeromelaban** [comment]
Thanks for the report. Indeed, this particular document is not up-to-date and was likely found through the web.

You can find the up-to-date version of [this document here](https://platform.uno/docs/articles/external/uno.extensions/doc/Learn/Maui/MauiOverview.html?tabs=single-project).

We're working on this particular incorrect search behavior in another issue (https://github.com/unoplatform/uno/issues/12356).
