### ISSUE TITLE
How to stop KI from running & failing on a forked uno repo? Its very annoying!

### ISSUE THREAD

**Issue by DevTKSS** [unoplatform/uno#19072]
### Current behavior

After forking uno repo for my last PR it seems to contantly run some KI and fail minimum 1x per day? Sometimes even more. Also its generating some UWP Branch without me telling it or the fork would have included such things.
Could someone please help me with this? I would even just delete it, if I could, SO Annoying is this messageing on a thing I cant even fix because of not knowing how.

### Expected behavior

like the PR before, just no KI running and failing? Not beeing messaged for "no Response" which I not even understand?

### How to reproduce it (as minimally and precisely as possible)

Feel free to take a look, its running all day long frequently... please make it stop
https://github.com/DevTKSS/uno

### Workaround

dont know... delete my mail from github and my e-mail account also? no, I do not have a realistic workaround

### Works on UWP/WinUI

None

### Affected platforms

Build tasks

### Anything else we need to know?

What I already did is sync all branches i see there
tryed to delete the self creating uwp thing, not possible
looked up uno docs for PR things, which told to rebase. on Github web there is nothing named rebase, all I can do is doing the sync so its up to date not behind or ahead but the ki keeps running so the uwp thing is now again ahead...
the one i did for the link fix, which has been resolved now from @morning4coffe-dev thanks, can also be deleted, what should have been done from ki if it would have been merged, but there is not told what to do if its not and obsolete.
The last one for adding doc content on the converters -> community toolkit seems to be the one throwing the fail, where I also have had done the sync but now it told me right this second, failed again. The text i wanted to add is included in the PR of it for not going lost...
Please could anyone help?

![Screenshot 2024-12-13 200741](https://github.com/user-attachments/assets/4b28b903-b253-4ab4-975c-459a884f4f84)
![Screenshot 2024-12-13 200818](https://github.com/user-attachments/assets/690e3e9a-bb99-403b-954e-d323e3e6d9a4)

**Comment by jeromelaban** [comment]
This makes sense, we'll change the actions so that they only run when on the main repo. You'll need to update the master branch so the change are picked up when done.
