### ISSUE TITLE
How do you implement data virtualization in FlipView, ListView, and GridView

### ISSUE THREAD

**Issue by scpc0609** [unoplatform/uno#1925]
## What would you like clarification on:

Consider a gallery app that wants to show an album of 1000+ images in a GridView / ListView. Without the presence of DataContextChanged, ContainerContentChanging how would you implement Bitmap loading for only the items that are realized?

Again consider a FlipView to open and show these images. Without the set of events above how would you keep only limited number of Bitmaps in memory as the number of realized items in FlipView?

Without virtualization, such scenarios are impossible to implement for mobile devices.

Hint: Xamarin Forms provide Appearing and Disappearing events for such scenarios, and in UWP either one can use the above events or use Data virtualization using ranges.

## Concern?

- [ ] Usage in industry
- [X ] Clarification of capabilities
- [X ] Getting started with Uno
- [ X] Developing with Uno
- [ X] Contributing to the Uno project
- [ ] Publishing your application
- [ ] Support
- [ ] Other (please specify):

## For which Platform:

- [ X] iOS
- [ X] Android
- [ ] WebAssembly
- [ ] Windows

**Comment by jeromelaban** [comment]
Thanks for your interest in Uno!

I'm not sure about the premises of the question. Virtualization is supported on all platforms for the `ListView` and `GridView` controls, and the materialization of items, images included support that scenario. Could you provide an example of what you're trying to acheive ?

For specifics, the `DataContextChanged` event is available on any `DependencyObject`, and `GridView`/`ListView` or any `ItemsControl` provides methods for implementers to perform custom virtualization (e.g. `ItemsControl.PrepareContainerForItemOverride`).

`ContainerContentChanging` is not implemented, though that's not a very complex event to implement, given the internals already do the work properly.

**Comment by scpc0609** [comment]
Hi Jerome, Thanks for your response. I am referring to Data Virtualization.

Consider the following Item class:
```
    public class Item
    {
        public string Path { get; set; } //Actual code does Notify Property Changed
        public BitmapImage Image { get; set; } //Actual code does Notify Property Changed

        public async void LoadImage()
        {
            var image = new BitmapImage();
            //Load a scaled BitmapImage
            image.DecodePixelWidth = 100;
            await image.SetSourceAsync(ImageStreamLoader.GetImageStream(this.Path));
            this.Image = image;
        }

        public void UnloadImage()
        {
            this.Image = null;
        }
    }
```
I have to call `LoadImage()` when the Item is realized  and `UnloadImage()` when the item is unrealized. Usually when you scroll through virtualized collection views, the `ContainerContentChanging `event is fired as containers are recycled, and I can call `LoadImage()` on the new Item and `UnloadImage()` on the old Item in the container (content property). This way it is possible to keep only a limited number of `BitmapImage` in memory.

I got from the documentation link https://platform.uno/docs/articles/implemented/windows-ui-xaml-frameworkelement.html that `DataContextChanged `is not implemented, but it actually is!!! when I tried in code. Unfortunately, it is not going to serve my purpose as from this event I can't get the old Data context, but only what it has changed to. Hence, I can't unload image for the item that has been unrealized.

Is deriving the itemscontrol classes to prepare the container the only option in Uno at this moment?

Also it seems BitmapImage.DecodePixelWidth is not supported on all platforms.

Can you please point me to gallery style sample with large number of images if you have one?

**Comment by davidjohnoliver** [comment]
As @jeromelaban mentioned, the `ContainerContentChanging` event shouldn't be too much work to implement, and we're more than happy to guide you through the process if you're interested in contributing.

My first approach in the scenario you describe would probably be to have an attached property inside the item template which is bound to the path and creates your `Item` object. Then you simply unload the previous `Item` whenever the attached property value changes.

**Comment by cmonto** [comment]
Hi David, will give it a try to go thru CONTRIBUTING.md and ramp up on the codebase. Would appreciate any form of guidance / docs to navigate through the codebase.

**Comment by davidjohnoliver** [comment]
Hi @cmonto , some good articles to get started are [Building and debugging Uno.UI](https://platform.uno/docs/articles/uno-development/debugging-uno-ui.html) and [Working with sample applications](https://platform.uno/docs/articles/uno-development/working-with-the-samples-apps.html).

**Comment by ghuntley** [comment]
Howdy @cmonto, in addition to above I'd recommend stopping by and having a look at https://github.com/unoplatform/workshops/tree/master/uno-bootcamp/modules/07-Working-with-Uno#visual-studio-solution-filters which explains how to get a productive devloop going.

**Comment by davidjohnoliver** [comment]
`ContainerContentChanging` is now supported, so I will close this issue. Note that `ISupportIncrementalLoading` is also supported. Please open a new issue if you'd like to request support for data virtualization-related APIs such as `IItemsRangeInfo`.
