### ISSUE TITLE
ResourceLoader.GetForCurrentView().GetString() does not support /[file]/[name] format

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#1928]
## Current behavior
ResourceLoader.GetForCurrentView().GetString("/file/name") return empty string
As including here png file doesnt work ("something went really wrong, and we can't process that file"), check these screenshots:
[android](http://beskid.geo.uj.edu.pl/p/ssc/android.png)
[wasm](http://beskid.geo.uj.edu.pl/p/ssc/wasm.png)

## Expected behavior
return of value "name" from "file.resw" - as in UWP.
[uwp](http://beskid.geo.uj.edu.pl/p/ssc/uwp.png)

## How to reproduce it (as minimally and precisely as possible)
I don't know how to include .zip file here...
[repro](http://beskid.geo.uj.edu.pl/p/ssc/TestUnoResw.zip)

Shared\Strings\en\Resources.resw (only not default lines)
`  <data name="resUniq" xml:space="preserve">`
`    <value>Uniq text from Resources</value>`
`  </data>`
`  <data name="t1t" xml:space="preserve">`
`    <value>text from Resources</value>`
`  </data>`

Shared\Strings\en\tezy.resw (only not default lines)
`  <data name="t1t" xml:space="preserve">`
`    <value>text fom Tezy</value>`
`  </data>`
`  <data name="tezyUniq" xml:space="preserve">`
`    <value>Uniq text from tezy</value>`
`  </data>`

Shared\MainPage.xaml

`<Page
    x:Class="TestUnoResw.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TestUnoResw"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d" Loaded="Page_Loaded">`
`    <StackPanel Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">`
` <TextBlock Name="uiText" Text="Should be resources.resw" Margin="20" FontSize="30" />`
`  <TextBlock Name="uiTextUniq" Text="Should be resources.resw (not in tezy)" Margin="20" FontSize="30" /> `
`        <TextBlock Name="uiTextTezy" Text="Should be tezy.resw" Margin="20" FontSize="30" VerticalAlignment="Bottom" />`
`        <TextBlock Name="uiTextTezyUniq" Text="Should be tezy.resw (not in Resources)" Margin="20" FontSize="30" VerticalAlignment="Bottom" />`
`    </StackPanel> `
`</Page>`

Shared\MainPage.xaml.cs (only not default methods )

`        public static string GetLangString(string sMsg)`
`        {`
`            if (string.IsNullOrEmpty(sMsg))`
`                return "";`
` `
`            string sTmp = Windows.ApplicationModel.Resources.ResourceLoader.GetForCurrentView().GetString(sMsg); `
`            if (string.IsNullOrEmpty(sTmp)) return "should be " + sMsg;`
`            return sTmp;`
`        }`

`        private void Page_Loaded(object sender, RoutedEventArgs e)`
`        {`
`            uiText.Text = GetLangString("t1t");`
`            uiTextUniq.Text = GetLangString("resUniq");`
`            uiTextTezy.Text = GetLangString("/tezy/t1t");`
`            uiTextTezyUniq.Text = GetLangString("/tezy/tezyUniq");`
`        }`

## Environment
Nuget Package:
2.0.512-dev.3530

Affected platform(s):
- [ ] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:
- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:
- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thank you for the report!

At this point, the `/[name]/[resourcename]` format is not yet supported. If you want to get the resources from a different file, using `ResourceLoader.GetForCurrentView("tezy")` is supported.

At this point, the [`ResourceLoader`](https://github.com/unoplatform/uno/blob/6f7e23f71084cc7e785fbd0838d04eeeffe7f5e9/src/Uno.UWP/ApplicationModel/Resources/ResourceLoader.cs#L41) class should be adjusted to take this format into account.

**Comment by jeromelaban** [comment]
Also, that format is supported from the XAML, it is not supported from an unnamed resource loader, see here for the code that handles it:

https://github.com/unoplatform/uno/blob/8f776ba4616b9eb2e3bbca201b434adc2243f677/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L3035

**Comment by pkar70** [comment]
Thanks for this hint. It allows me to write quick and simple PR for this.

**Comment by pkar70** [comment]
Functionality was added 8 XI 2019.
