### ISSUE TITLE
Flyout does not light dismiss in the same way as UWP on Android.

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#1929]
On UWP a flyout will light dismiss when a button on the flyout is pressed, this does not happen on Android.

The flyout only dismisses when the screen outside the flyout is tapped

A sample that reproduces the issue can be found here:
https://github.com/BrianDT/UnoFlyoutIssue

Package Version(s):
Uno.UI: 2.0.512-dev.3530

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Have not  been unable to determine if the issue also exists on iOS because on iOS button tap on a flyout does not execute the button command. This will be raised as a separate issue.

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by XiaotianNetlift** [comment]
related: https://github.com/unoplatform/uno/issues/2677
might be fixed with: https://github.com/unoplatform/uno/pull/2678?

**Comment by BrianDT** [comment]
Confirmed still an issue in 3.6.6
