### ISSUE TITLE
Buttons on a flyout on iOS do not execute their commands

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#1930]
Commands bound to a button on a flyout are not executed when the button is tapped on iOS.

## Expected behavior

The execute action of the command should be called

## How to reproduce it (as minimally and precisely as possible)

A sample that reproduces the issue can be found here:
https://github.com/BrianDT/UnoFlyoutIssue

## Environment

Nuget Package:
Package Version(s):
Uno.UI: 2.0.512-dev.3530

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

When this issue is resolved, confirm that #1929 does not also apply.

**Comment by jeromelaban** [comment]
Thanks for the report!

This looks like an `x:Bind` issue more than the button not executing the command. It's more than likely that a "normal" binding will work. 

You could do so by assigning the command to a tag outside the flyout, and use an element binding instead: 
```xaml
<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
      <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
        <Border 

                x:Name="outerBorder" 
                Tag="{x:Bind VM.DoStuffCommand}"

                BorderBrush="Black" BorderThickness="1" Padding="8"
                Background="LightGray" CornerRadius="2"
                Tapped="Open_Flyout">
          <TextBlock Text="Tap me" Margin="20" FontSize="30" />

          <FlyoutBase.AttachedFlyout>
            <Flyout x:Name="flyout" LightDismissOverlayMode="On">
              <Button Command="{Binding Tag, ElementName=outerBorder}" HorizontalAlignment="Right">
                <Button.Template>
                  <ControlTemplate>
                    <Border BorderBrush="Blue" BorderThickness="1" Padding="16" Background="LightBlue" CornerRadius="8">
                      <StackPanel Orientation="Horizontal">
                        <SymbolIcon Symbol="Contact" />
                        <TextBlock Text="Then Tap this" Margin="8,0,0,0"/>
                      </StackPanel>
                    </Border>
                  </ControlTemplate>
                </Button.Template>
              </Button>
            </Flyout>
          </FlyoutBase.AttachedFlyout>
        </Border>
```

To fix this, this is most likely an issue in the flyout management, where the propagation of "compiled bindings" is not done properly, as flyouts are not part of the visual tree specified in the XAML.

**Comment by BrianDT** [comment]
OK that's a good work-around.
I actually prefer going straight to the viewmodel via the control
<Page
    x:Name="control"
                            <Button Command="{Binding ElementName=control, Path=DataContext.DoStuffCommand}" HorizontalAlignment="Right">

and avoid the Tag as this is just a cut down version of the full case of a flyout with more than one button on it.
I have updated the sample to demonstrate that this option works.

However there is a slightly odd interaction with the pop up message that requires two taps to press the OK button, the first seems to dismiss the flyout, and the 2nd activates the OK. This is not a problem if a manual dismiss is done.

Regards

Brian

on behalf of Visual Software Systems Ltd


 

This email is intended solely for the addressee(s) and the information it contains is confidential. If you are not the intended recipient; 

 (a) please delete this email and inform the sender as soon as possible, and 

 (b) any copying, distribution or other action taken or omitted to be taken in reliance upon it is prohibited and may be unlawful. 

 
 

    On Wednesday, 23 October 2019, 12:58:57 BST, Jérôme Laban <notifications@github.com> wrote:  
 
 
Thanks for the report!

This looks like an x:Bind issue more than the button not executing the command. It's more than likely that a "normal" binding will work.

You could do so by assigning the command to a tag outside the flyout, and use an element binding instead:
<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
      <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
        <Border 

                x:Name="outerBorder" 
                Tag="{x:Bind VM.DoStuffCommand}"

                BorderBrush="Black" BorderThickness="1" Padding="8"
                Background="LightGray" CornerRadius="2"
                Tapped="Open_Flyout">
          <TextBlock Text="Tap me" Margin="20" FontSize="30" />

          <FlyoutBase.AttachedFlyout>
            <Flyout x:Name="flyout" LightDismissOverlayMode="On">
              <Button Command="{Binding Tag, ElementName=outerBorder}" HorizontalAlignment="Right">
                <Button.Template>
                  <ControlTemplate>
                    <Border BorderBrush="Blue" BorderThickness="1" Padding="16" Background="LightBlue" CornerRadius="8">
                      <StackPanel Orientation="Horizontal">
                        <SymbolIcon Symbol="Contact" />
                        <TextBlock Text="Then Tap this" Margin="8,0,0,0"/>
                      </StackPanel>
                    </Border>
                  </ControlTemplate>
                </Button.Template>
              </Button>
            </Flyout>
          </FlyoutBase.AttachedFlyout>
        </Border>
To fix this, this is most likely an issue in the flyout management, where the propagation of "compiled bindings" is not done properly, as flyouts are not part of the visual tree specified in the XAML.

**Comment by MatFillion** [comment]
Is it the same issue as #1884

**Comment by BrianDT** [comment]
Retested on 3.6.6 the buttons now seem to work; however, the text does not display because the MaxWidth is not retrieved from the templated parent. 
As Android the flyout does not dismiss automatically on button press, where as it does on UWP.

**Comment by BrianDT** [comment]
Confirmed resoled in 4.6.18
Please close
The templated parent issue mentioned above will be raised elsewhere if significant, in this case it is not because it can easily be implemented in a different way.

**Comment by jeromelaban** [comment]
Thanks!
