### ISSUE TITLE
[Wasm] Incorrect TextBlock text trimming

### ISSUE THREAD

**Issue by zipswich** [unoplatform/uno#1937]
## Current behavior

Drop the following TextBlock in any app:

```
<TextBlock x:Name="debug"
           Grid.Column="0" 
            TextTrimming="WordEllipsis"
            FontSize="56"
            FontWeight="Light"
            TextWrapping="NoWrap"
            Text="Test Results"
            VerticalAlignment="Center" 
            HorizontalAlignment="Center"
                />
```
You see the following from the UWP head:
![image](https://user-images.githubusercontent.com/6095671/67358515-ab22dc00-f52e-11e9-85c0-91865340b155.png)
but the following from the WASM head:
![image](https://user-images.githubusercontent.com/6095671/67358527-b5dd7100-f52e-11e9-81f4-18905d1578b3.png)

## Expected behavior

They should be consistent on all platforms.

## How to reproduce it (as minimally and precisely as possible)

Use the above way to reproduce it

## Environment

Nuget Package: Uno.UI 

Package Version(s): 2.0.512-dev.3459

Affected platform(s): 

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
If you copy the exact same `<TextBlock>` multiple times in the same page, do you get the same result for all of them?

**Comment by zipswich** [comment]
```
        <StackPanel>
            <TextBlock 
           Grid.Column="0" 
            TextTrimming="WordEllipsis"
            FontSize="56"
            FontWeight="Light"
            TextWrapping="NoWrap"
            Text="Test Results"
            HorizontalAlignment="Center"
                />
            <TextBlock 
           Grid.Column="0" 
            TextTrimming="WordEllipsis"
            FontSize="56"
            FontWeight="Light"
            TextWrapping="NoWrap"
            Text="Test Results"
            HorizontalAlignment="Center"
                />
            <TextBlock 
           Grid.Column="0" 
            TextTrimming="WordEllipsis"
            FontSize="56"
            FontWeight="Light"
            TextWrapping="NoWrap"
            Text="Test Results"
            HorizontalAlignment="Center"
                />
        </StackPanel>
```
![image](https://user-images.githubusercontent.com/6095671/67446142-92253400-f5dd-11e9-91fe-ee5edf24e65f.png)

**Comment by carldebilly** [comment]
I'm not able to reproduce this problem.  I started a new Uno project from scratch and put your `XAML`  in the `mainpage.xaml` and it's working.

- Are you using a special font? It looks like a classic problem (#693).
- Do you have the problem in all tested browsers / platforms?
- Do you still have the problem when you deactivate the Measure Cache ? (https://github.com/unoplatform/uno/blob/master/src/Uno.UI/FeatureConfiguration.cs#L186)
   ``` csharp
   FeatureConfiguration.IsMeasureCacheEnabled = false;
   ```

**Comment by zipswich** [comment]
https://github.com/zipswich/AppDebugUno
This is my generic debug app, so you can ignore all other elements.

**Comment by zipswich** [comment]
![image](https://user-images.githubusercontent.com/6095671/67506190-a22f2900-f65a-11e9-8790-977e167406c2.png)
