### ISSUE TITLE
Add support for Control Manipulation overrides

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#1940]
## What would you like to be added:
Support for `Control.ManipulationStarted`, `Control.ManipulationDelta`, etc...

## Why is this needed:
The `GridSplitter` control needs support for those events.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?
https://github.com/unoplatform/Uno.WindowsCommunityToolkit/issues/38

**Comment by dr1rrb** [comment]
This has been fixed by https://github.com/unoplatform/uno/pull/2046
