### ISSUE TITLE
DateTime.Now gets UTC instead of local time for WASM

### ISSUE THREAD

**Issue by zipswich** [unoplatform/uno#1941]
## Current behavior
**Minor Issue**
DateTime.Now gets UTC instead of local time for WASM as UWP.

## Expected behavior

DateTime.Now should get local time for WASM.

## How to reproduce it (as minimally and precisely as possible)

Debug.WriteLine(DateTime.Now.ToString());

## Environment

Nuget Package: Uno.UI

Package Version(s):  2.0.512-dev.3459

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by gahag** [comment]
Can I have an attempt at this?
