### ISSUE TITLE
Datagrid control missing

### ISSUE THREAD

**Issue by bbrittonHHL** [unoplatform/uno#1943]
## What would you like to be added:
A datagrid control based on Microsoft.Toolkit.Uwp.UI.Controls.DataGrid.
## Why is this needed:
Need to present and handle data in a spreadsheet style.
## For which Platform:

- [ ] iOS
- [ ] Android
- [x ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by yowl** [comment]
This issue is "most-wanted" for a while now, is there any chance it will get looked at "soon" ?

**Comment by davidjohnoliver** [comment]
This is a round-up of Uno issues affecting the WCT `DataGrid`:

Selecting a cell:
 - [WASM] Tapped event isn't called on nested child https://github.com/unoplatform/uno/issues/2843

Cell/row/column selected state:
 - [All] ColorAnimation is not supported https://github.com/unoplatform/uno/issues/143

Resizing columns:
 - [iOS] Calling InvalidateMeasure() on a descendant during measure can go infinite https://github.com/unoplatform/uno/issues/2842

Editing a cell:
 - [All] Control.Focus() should recursively check children https://github.com/unoplatform/uno/issues/2845
 - [All] `FocusManager.GetFocusedElement()` is null within `Control.LostFocus` callback https://github.com/unoplatform/uno/issues/2846
 - [WASM] `IsTabStop` is ignored https://github.com/unoplatform/uno/issues/2138

**Comment by francoistanguay** [comment]
More details [Here](https://platform.uno/blog/uno-platform-and-windows-community-toolkit-datagrid-tabview-and-expander-with-sample-code/)
