### ISSUE TITLE
Run UNO on linux using cli and vscode

### ISSUE THREAD

**Issue by Mo-ha-mmed** [unoplatform/uno#1947]
Just a quick question and i hope the answer will be yes otherwise i hope it will be on the roadmap

Can you start using uno in Linux ?
Can you start using uno only by using the cli and vscode ?

I think the key for uno to success is to get inspired by flutter development workflow using minimal requirements

**Comment by aboimpinto** [comment]
I follow the guide in https://platform.uno/docs/articles/get-started-vscode-wasm.html and didn't work for me.

I had to install the Uno.ProjectTemplates.Dotnet::2.3.0-dev.123 to have the unoapp available for the CLI.

When I do "don't build", this is what I get:
dotnet build
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 9.14 sec for /home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj.
/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Shared/App.xaml.cs(56,9): warning Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PreviousExecutionState is not implemented in Uno [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Shared/App.xaml.cs(65,8): warning Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PrelaunchActivated is not implemented in Uno [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Shared/App.xaml.cs(98,19): warning Uno0001: Windows.ApplicationModel.SuspendingOperation.GetDeferral() is not implemented in Uno [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Shared/App.xaml.cs(100,4): warning Uno0001: Windows.ApplicationModel.SuspendingDeferral.Complete() is not implemented in Uno [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
  unoTestBed.Wasm -> /home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/bin/Debug/netstandard2.0/unoTestBed.Wasm.dll
  Downloading mono-wasm-1add5cbc06a to /tmp/mono-wasm-1add5cbc06a.zip
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.18/build/Uno.Wasm.Bootstrap.targets(124,5): error : System.ComponentModel.Win32Exception (8): Exec format error [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.18/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.18/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.18/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.Start() [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.18/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v8add3fd92e26891863414b9fa407830081f7d732.RunProcess(String executable, String parameters, String workingDirectory) in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 421 [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.18/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v8add3fd92e26891863414b9fa407830081f7d732.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 522 [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.18/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v8add3fd92e26891863414b9fa407830081f7d732.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 166 [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]

Build FAILED.


hope this can help
Paulo Aboim Pinto

**Comment by jeromelaban** [comment]
@aboimpinto Thanks for the report! This is actually already fixed, but not by the default template, we'll be updating that.

In the meantime, you'll need to update to the latest `Uno.Wasm.Bootstrap` and `Uno.Wasm.Bootstrap.DevServer` packages (1.2.0-dev.37) for the build to work properly.

Which will be a good time to close this issue as it's now implemented in the latest dev bits, once the template will be updated :)

**Comment by aboimpinto** [comment]
thanks for the answer and for the quick fix but looks like updating the boostrap packages  isn't enough

$   dotnet build
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 25.81 ms for /home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj.
/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Shared/App.xaml.cs(46,9): warning Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PreviousExecutionState is not implemented in Uno [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Shared/App.xaml.cs(55,8): warning Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PrelaunchActivated is not implemented in Uno [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Shared/App.xaml.cs(88,19): warning Uno0001: Windows.ApplicationModel.SuspendingOperation.GetDeferral() is not implemented in Uno [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Shared/App.xaml.cs(90,4): warning Uno0001: Windows.ApplicationModel.SuspendingDeferral.Complete() is not implemented in Uno [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
  unoTestBed.Wasm -> /home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/bin/Debug/netstandard2.0/unoTestBed.Wasm.dll
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.37/build/Uno.Wasm.Bootstrap.targets(124,5): error : System.ComponentModel.Win32Exception (2): No such file or directory [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.37/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.37/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.37/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.Start() [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.37/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v4ccfd1daded8808c1c60acf351657c5d5caa7ea2.RunProcess(String executable, String parameters, String workingDirectory) in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 431 [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.37/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v4ccfd1daded8808c1c60acf351657c5d5caa7ea2.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 532 [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.37/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v4ccfd1daded8808c1c60acf351657c5d5caa7ea2.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 167 [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]


I still have the same issue ...

**Comment by jeromelaban** [comment]
Do you have mono installed, and can you run `mono --version` ?

**Comment by jeromelaban** [comment]
If not, you can install it by running this script: https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/master/src/Uno.Wasm.Bootstrap/build/scripts/dotnet-setup.sh

**Comment by aboimpinto** [comment]
looks like not

In the page 
https://platform.uno/docs/articles/get-started-vscode-wasm.html
the pre-requirements just mention VSCode and not mono...

going to install too

**Comment by jeromelaban** [comment]
That's fair, we'll adjust the docs.

**Comment by aboimpinto** [comment]
don't have the Windows errors but still not working

$  dotnet build
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 28.56 ms for /home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj.
  unoTestBed.Wasm -> /home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/bin/Debug/netstandard2.0/unoTestBed.Wasm.dll
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.37/build/Uno.Wasm.Bootstrap.targets(124,5): error : System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (0x80131621) [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.37/build/Uno.Wasm.Bootstrap.targets(124,5): error : File name: 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.37/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v4ccfd1daded8808c1c60acf351657c5d5caa7ea2.GeneratePWAContent(StringBuilder extraBuilder) [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.37/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v4ccfd1daded8808c1c60acf351657c5d5caa7ea2.GenerateHtml() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 1238 [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.37/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v4ccfd1daded8808c1c60acf351657c5d5caa7ea2.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 172 [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.37/build/Uno.Wasm.Bootstrap.targets(124,5): error :  [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
/home/esqueleto/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.37/build/Uno.Wasm.Bootstrap.targets(124,5): error :  [/home/esqueleto/myDevelop/unoTestBed/unoTestBed.Wasm/unoTestBed.Wasm.csproj]
