### ISSUE TITLE
[Android] ContentDialog fails to display on navigation to new page.

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#1951]
On Android when navigating to a new page if a ContentDialog shown in code triggered by the Loaded event is not displayed.

## Expected behavior

The dialog should be displayed.

## How to reproduce it (as minimally and precisely as possible)

A sample that reproduces the issue can be found here:
https://github.com/BrianDT/UnoDialogIssues

Nuget Package:
Uno.UI: 2.0.512-dev.3570

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

**Comment by jeromelaban** [comment]
This issue is related to https://github.com/unoplatform/uno/issues/2895, as the dialog box is closed by the previous popup being dismissed. The adjustments made to handle the loaded/unloaded events properly will fix this issue.

**Comment by BrianDT** [comment]
Still an issue in version Uno.UI 3.6.6, sample updated.

**Comment by BrianDT** [comment]
Confirmed resolved in Uno 4.6.19
Sample updated to validate
Please close

**Comment by jeromelaban** [comment]
Thanks for the update!
