### ISSUE TITLE
On WASM the MessageDialog display is incomplete

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#1953]
On WASM MessageDialog actions are not trigged and only one button is displayed.

## Expected behavior

All buttons should be displayed and the actions should be triggered on button press

## How to reproduce it (as minimally and precisely as possible)

A sample that reproduces the issue can be found here:
https://github.com/BrianDT/UnoDialogIssues

Nuget Package:
Uno.UI: 2.0.512-dev.3570

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

**Comment by jeromelaban** [comment]
Thank you for the report! 

Could you paste a screenshot of what you seeing ?

**Comment by BrianDT** [comment]
![Uno_Issue_1955](https://user-images.githubusercontent.com/4189260/67666913-ac0ba180-f964-11e9-93a8-554a8cbd4e4b.PNG)

**Comment by jeromelaban** [comment]
Ah! Yes. This is a known issue that was not yet fixed. The current implementation uses the default javascript `alert` dialog, which does not provide the ability to add additional buttons. See #1124 

At the time, Uno did not support `ContentDialog` but it is now. MessageDialog could now be implemented using it.

I'll close this issue as a duplicate.
