### ISSUE TITLE
Add support for EmailManager

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1965]
## What would you like to be added:

The `EmailManager` API

## Why is this needed:

📧

## For which Platform:

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by pkar70** [comment]
Is there any progress?

**Comment by MartinZikmund** [comment]
@pkar70 Yes, quite good, I have a version done, just need to create sample UI for it, then will make a PR

**Comment by pkar70** [comment]
So, what is expected 'time of arrival'? :)

**Comment by MartinZikmund** [comment]
Let's say PR this weekend 😉

**Comment by MartinZikmund** [comment]
Done
