### ISSUE TITLE
Geolocation on Android

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#1967]
## Current behavior
RequestAccessAsync() returns GeolocationAccessStatus.Allowed, but trying to use Geolocation throws exception (no permission) - but in Manifest, permission is correct (ACCESS_FINE_LOCATION)

## Expected behavior
No exception.

I tried to dig into problem, and found [this info](https://stackoverflow.com/questions/33865445/gps-location-provider-requires-access-fine-location-permission-for-android-6-0/33866959)
But I never do any program for Android environment directly (only using Uno), so it would be hard for me adding appropriate code.

## Environment

Nuget Package: 2.0.512.3599

Package Version(s):

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
You may need an additional permission in the application, such as `ACCESS_COARSE_LOCATION`.

**Comment by pkar70** [comment]
Both (FINE and COARSE) has attribute "Protection level: dangerous" (see https://developer.android.com/reference/android/Manifest.permission.html#ACCESS_COARSE_LOCATION). And digging internet for solution I found that COARSE is 'included' in FINE, so it is unnecessary to add COARSE if someone declares FINE.

**Comment by jeromelaban** [comment]
Which version of Android are you testing on?

**Comment by pkar70** [comment]
Android 8.1 Go.

**Comment by jeromelaban** [comment]
In such case, it may be related to system permissions. Check that the application was given access in the devices settings.

**Comment by jcantin-nventive** [comment]
@pkar70 I believe this issue is now resolved, thanks to some fixes in Uno. Could you confirm on your end that you are able to use Geolocator with the latest version of Uno on Android?

**Comment by pkar70** [comment]
Yes, changes in permissionhelper allows to correctly implement RequestAccessAsync, and  #3891 make better Geopoint.
Although #2536 have more functionality than current Uno implementation, I think this Issue can be closed.
