### ISSUE TITLE
Improve Android startup performance

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#1968]
## What would you like to be added:

The startup performance on Android is significantly worse than on similarly performant iOS device. I think some profiling is needed to bring the Android performance on par with iOS.

## Why is this needed:

To make Uno apps launch quicker on Android.

## For which Platform:

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
Haven't tried VS 16.4 Preview yet, however, even when using AOT and LLVM, the startup of the app is still quite slow. I am happy to provide additional info from source code to any time measurements 🙂

**Comment by francoistanguay** [comment]
Not an Uno-specific issue.
