### ISSUE TITLE
Support for Svg

### ISSUE THREAD

**Issue by MatFillion** [unoplatform/uno#1982]
## What would you like to be added:
WinUI has [SvgImageSource](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.svgimagesource) which lets you display svg assets.
## Why is this needed:
Usage of SVGs helps making apps as small as possible and also scale better to various screen sizes
## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?
If we add this, we would probably want to make sure svg assets are supported in shared code, if not already supported. (see #1839)

Here is an example of SVG support in Wasm: https://playground.platform.uno/#2be09f62

- iOS does have minimal in-box support for SVG
- macOS support has not been investigated
- Android would need to use GlideX or similar to provide this feature. This would be a replacement for UniversalImage Loader that uno uses for its templates.

**Comment by rdagglis** [comment]
Definitely a great feature to have.

**Comment by Massimo37** [comment]
As an FYI, currently already working in both UWP and WASM:

![svg](https://user-images.githubusercontent.com/36633246/70261536-a32a9e80-1760-11ea-9115-915881e10a55.jpg)

**Comment by Massimo37** [comment]
A good in UWP for image scaling on an `SvgImageSource`:

https://stackoverflow.com/a/51241460/973342

**Comment by matizk144** [comment]
The same issue with macOs and Skia (Linux)

**Comment by SuperJMN** [comment]
Nice to have. Our project uses SVG for everything in the GUI.

**Comment by MartinZikmund** [comment]
This is now supported
