### ISSUE TITLE
Missing XML comments in generated code

### ISSUE THREAD

**Issue by kakone** [unoplatform/uno#1983]
## Current behavior

In the generated code, some methods doesn't have XML comments. It's problematic when we generate documentation file in our Uno project (even more when we treat warnings as errors). 
Example (perhaps it's the only missing one, I have not looked at everything) : https://github.com/unoplatform/uno/blob/0cd7a3c2d3b6a8eb96b64cf4156dbb04a350e4f0/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs#L432

## Expected behavior

All public or protected generated methods should have an XML comment.

## How to reproduce it (as minimally and precisely as possible)

Set `<GenerateDocumentationFile>true</GenerateDocumentationFile>` in an Uno project

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.0.512-dev.3629

**Comment by kakone** [comment]
I'm going to look at the missing comments, I will send a PR.

**Comment by francoistanguay** [comment]
Is there something left to do or can this be closed?
