### ISSUE TITLE
[Android] Grid Row Height not taking height of Image with Stretch UniformToFill

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#1985]
## Current behavior

The row is not taking into account the height of the image, when the height of the row is smaller than the image with Stretch UniformToFill, the image is shown outside the area of the row.

## Expected behavior

The image should reside inside the row of the grid.

## How to reproduce it (as minimally and precisely as possible)
Display an image with Stretch UniformToFill in a row with an height smaller than the image 
Use the following sample: [ImageSample.zip](https://github.com/unoplatform/uno/files/3785263/ImageSample.zip)

## Environment

Nuget Package:
Uno.UI 2.0.512-dev.3599
Uno.UniversalImageLoader 1.9.32

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

https://dev.azure.com/nventive/Umbrella/_workitems/edit/164402

**Comment by jeromelaban** [comment]
This issue has been present for a long time, so this may not be the same issue we're looking for.

**Comment by carldebilly** [comment]
Should be fixed by PR #2123
