### ISSUE TITLE
[WASM] GradientLinearBrush is not working on Rectangle

### ISSUE THREAD

**Issue by soriyathach** [unoplatform/uno#1992]
## Current behavior

A rectangle with a GradientLinearBrush is black while it has the right gradient on UWP and other platforms.

## Expected behavior

The gradient should be displayed on the rectangle.

## How to reproduce it (as minimally and precisely as possible)

The color:
`<LinearGradientBrush x:Key="PrimaryGradientBrush" 
                         StartPoint="1,1" 
                         EndPoint="0,0">
        <GradientStop Color="{StaticResource blueberry}" 
                      Offset="0" />
        <GradientStop Color="{StaticResource dark_sky_blue}" 
                      Offset="1" />
    </LinearGradientBrush>`

The rectangle is black on wasm:
`<not_wasm:Rectangle Fill="{StaticResource PrimaryGradientBrush}"
				RadiusX="2"
				VerticalAlignment="Center"
				Height="4"
				Grid.Column="0" />`

However it's working on a border:
`<wasm:Border Background="{StaticResource PrimaryGradientBrush}"
			CornerRadius="2"
			VerticalAlignment="Center"
			Height="4"
			Grid.Column="0" />`

## Environment

Nuget Package:

Package Version(s):
UNO.UI 1.46.196-dev.2440

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.2.0)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
Rectangle are rendered as _SVG_ on Wasm. It's not working because currently only `SolidColorBrush` is supported on svg elements.

**Comment by Youssef1313** [comment]
@carldebilly Was this already fixed?

https://github.com/unoplatform/uno/blob/4984da284be0b245b1268d0375a85d7bc2b32408/src/Uno.UI/UI/Xaml/Shapes/Shape.wasm.cs#L94-L102

**Comment by carldebilly** [comment]
Yep that's a very old bug and not relevant anymore: I'll close it.
