### ISSUE TITLE
Unable to use Uno.UI.WpfHost package

### ISSUE THREAD

**Issue by ibebbs** [unoplatform/uno#2000]
## Current behavior

Issue 1. Difficulties adding reference to Uno.UI.WpfHost
Issue 2. Unable to build WPF project referencing Uno.UI.WpfHost

## Expected behavior

Issue 1. Following the instructions [here](https://platform.uno/docs/articles/uno-development/working-with-uno-wpf-host.html) fails at the step `Reference the Uno.UI.WpfHost package` with the error:
  > The package 'System.IO.Compression.ZipFile' tried to add a framework reference to 'System.IO.Compression.FileSystem' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Installation should succeed

Issue 2. After installing Uno.UI.WpfHost (see below for how I resolved issue 1) I receive numerous errors about App.xaml and MainWindow.xaml specifying different base classes (resulting from generated classes of same name I believe).
Compilation should succeed

## How to reproduce it (as minimally and precisely as possible)

Issues 1 & 2 can be reproduced by following the steps outlined in 'Using the Uno.UI.WpfHost package' [here](https://platform.uno/docs/articles/uno-development/working-with-uno-wpf-host.html).

## Environment

Nuget Package:

Uno.UI.WpfHost 

Package Version(s):

v1.45.0 (also affects latest pre-release 2.0.512-dev.3661)

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [*] Windows
- [*] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [*] 2019 (version: 16.3.4)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

To resolve issue 1 above I manually installed the following packages first:
* System.Runtime v4.3.0 
* System.Numerics.Vectors v4.3.0
* System.IO.Compression.FileSystem v4.3.0
* System.Reactive v4.1.0

I was then able to successfully install Uno.UI.WpfHost v1.45.0

A reproduction of issue 2 can be found in [this repository](https://github.com/ibebbs/WpfWasmHost2).

**Comment by jeromelaban** [comment]
Thanks for opening this issue!

At this point, the WPF host is an experiment that does not work properly. It is unstable and is quite complex to get to build properly.

What do you need this for ?

**Comment by ibebbs** [comment]
Hi Jerome,

Well, TBH, I had hoped to use the WPF host for exactly it's stated purpose; specifically to aid debugging a WASM head.

I followed the instructions [here](https://platform.uno/docs/articles/debugging-wasm.html) about "Using the WebAssembly C# Debugger" but didn't see the Sources displayed as it suggested I should. I therefore thought I'd give the Uno.UI.WpfHost a shot instead.

If you feel that the Uno.UI.WpfHost is not a viable debugging tool for users of the Uno platform at the current time, may I suggest that you remove it from - or mark it as such in - the documentation? Having it there in it's current form suggests it should be usable and I spent a good (well, actually pretty frustrating ;0) couple of hours trying to get it to work.

I no longer have a desperate need for this tool - or the documentation - to be fixed (I resorted to a 'Debug' textblock in the UI) but thought I'd raise the issue and provide a reproduction in case it was of use.

**Comment by carldebilly** [comment]
I agree it should be removed... or, at least, the code removed from `master` because it's not very useful -- yet.

**Comment by hampoelz** [comment]
Had the same problem, but was able to "solve" it by adding all the dependencies separately and at last the `Uno.UI.WpfHost` package, but now I get the following error message when I build the project:

> Die Abhängigkeit von Assembly "Uno.UI.RemoteControl, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null" kann nicht aufgelöst werden, da sie nicht vorher geladen wurde. Beim Verwenden der ReflectionOnly-APIs müssen abhängige Assemblys vorher geladen oder über das ReflectionOnlyAssemblyResolve-Ereignis bei Bedarf geladen werden.

**Comment by schmitch** [comment]
actually we are looking into WPF because of the `NotifyIcon` class, which UWP does not support.

**Comment by jeromelaban** [comment]
The packages are now deprecated and removed from publication
