### ISSUE TITLE
ComboBox does not take Window.VisibleBounds to position its popup

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2007]
## Current behavior
The popup opened by a ComboBox does not take into account the VisibleBounds property when determining the position of the popup.

On Android, the issue appears if the following style is provided:
```xml
<item name="android:windowTranslucentStatus">true</item>
```

## Expected behavior
The popup is properly aligned with the position of the ComboBox, particularly when there is not enough room above to display all items.

## How to reproduce it (as minimally and precisely as possible)

- Use the following sample: [ComboBoxVisibleBoundsPosition.zip](https://github.com/unoplatform/uno/files/3795321/ComboBoxVisibleBoundsPosition.zip)
- On android, run the sample application
- Select the first item of the combo box
- Reopen the ComboBox
- Notice the popup is incorrectly aligned:

![image](https://user-images.githubusercontent.com/5839577/67976502-94dee500-fbec-11e9-98be-9f9e4f89ef2d.png)

The issue is most likely related to:
https://github.com/unoplatform/uno/blob/7825de377d0a630b620c04b7de238b126340a7e8/src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs#L444

## Environment
Package Version(s): 2.0.512-dev.3668

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Reopened in https://nventive.visualstudio.com/67eedefd-9293-4f70-a624-89ecbe8ad34f/_workitems/edit/160058

**Comment by davidjohnoliver** [comment]
Remaining issue is not an Uno bug, see discussion in https://nventive.visualstudio.com/Umbrella/_workitems/edit/160058

**Comment by jeromelaban** [comment]
@davidjohnoliver should be closed ?

**Comment by davidjohnoliver** [comment]
> @davidjohnoliver should be closed ?

Yes
