### ISSUE TITLE
TextBlock crashes on Android 10

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#2016]
## Current behavior

When the default Uno Hello World app is retargeted to Android 10, it crashes during startup due to `TextBlock`.

The reported error is `System.InvalidOperationException: 'Sequence contains no elements'`. It occurs in `TextBlock.Android.cs` on [this line](https://github.com/unoplatform/uno/blob/5d41569f5a10c316599e1660613f1a4af2806a99/src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.Android.cs#L74) due to the fact that the LINQ query does not return any such constructor.

## Expected behavior

App does not crash.

## How to reproduce it (as minimally and precisely as possible)

Create new Uno Platform solution and change the Android app target to Android 10 (Q). Try to run the application and observe it crashes.

## Environment

Nuget Package: latest preview

Package Version(s): latest preview

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Looks like this one may be a problem. We’re using this then grey listed API to be able to have max line support along with proper wrapping and trimming.

I reported this API as used in google’s bug tracker, and it looks like it was never taken into account.

Can you check if there are newer APIs that are available on that? 

/cc @MatFillion

**Comment by jeromelaban** [comment]
Looks like API 23 added a builder that may provides what we need: https://developer.android.com/reference/android/text/StaticLayout.Builder.html
