### ISSUE TITLE
The default font of Uno does not supports unicode glyphs

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#202]
## I'm submitting a...
- Bug report (I searched for similar issues and did not find one)

## Current behavior
The `🡄` is replaced by a `?` on iOS

## Expected behavior
As I didn't changed the default font and it works on UWP, it should also work on on iOS and Android.

## Minimal reproduction of the problem with instructions
`<Textblock Text="🡄" />`

## Environment
Nuget Package: Uno.UI
Package Version(s): 1.40.0-dev.374

Affected platform(s):
- [x] iOS
- [?] Android
- [?] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio: _Irrelevant_ 
- [x] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins: _None_
```

**Comment by jeromelaban** [comment]
Closing in favor of #3011
