### ISSUE TITLE
[Droid]TextBox state doesnt stay as "Focused" when clicked

### ISSUE THREAD

**Issue by XiaotianNetlift** [unoplatform/uno#2021]
## Current behavior
On android, when an `TextBox` receive a click, it enters the `Focused` state and immediately resets by to `Normal` state.

## Expected behavior
The `TextBox` should stay in the `Focused` state until the focus on lost, like on uwp.

## How to reproduce it (as minimally and precisely as possible)
[repro165743.zip](https://github.com/unoplatform/uno/files/3806469/repro165743.zip)
![uno-pointer-events](https://user-images.githubusercontent.com/32882405/68165774-59b31d80-ff2e-11e9-8783-e4ed311e92cb.gif)

## Environment
Nuget Package: Uno.UI
Package Version(s): 2.0.512-dev.3672
Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [x] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] ~~Resharper (version: )~~

## Anything else we need to know?
Internal issue: 
- https://nventive.visualstudio.com/Umbrella/_workitems/edit/164262
- https://nventive.visualstudio.com/Umbrella/_workitems/edit/166092

**Comment by XiaotianNetlift** [comment]
```
// [droid] clicking on CustomTextBox once
11-04 17:32:16.863 D/Repro165743( 4414): CustomTextBox.States_CurrentStateChanged: Normal -> PointerOver
11-04 17:32:16.875 D/Repro165743( 4414): CustomTextBox.States_CurrentStateChanged: PointerOver -> Focused
11-04 17:32:16.890 D/Editor  ( 4414): setInputTypeforClipTray(): 0
11-04 17:32:16.906 I/ViewRootImpl( 4414): ViewRoot's Touch Event : ACTION_UP
11-04 17:32:16.913 D/Repro165743( 4414): CustomTextBox.States_CurrentStateChanged: Focused -> Normal

// [uwp] clicking on CustomTextBox once
CustomTextBox.States_CurrentStateChanged: Normal -> PointerOver
CustomTextBox.States_CurrentStateChanged: PointerOver -> Focused
```

**Comment by jeromelaban** [comment]
There are most probably missing FocusManager tests missing there: 
https://github.com/unoplatform/uno/blob/0430120103d6552443e2db7c5e0aaebcce059b2e/src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/FocusManagerTests/UnoSamples_Tests.FocusManager.cs#L16
