### ISSUE TITLE
Windows.Devices.Geolocation.Geolocator.Dispose on Android

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#2028]
## Current behavior
There is difference between UWP/Uno Geolocator. On Android, it requires Dispose(), on UWP - not.

## Expected behavior
Same behaviour, so code would not require changes (#if/#endif  bracketed Dispose).

## How to reproduce it (as minimally and precisely as possible)
`Windows.Devices.Geolocation.Geolocator oDevGPS = new Windows.Devices.Geolocation.Geolocator();`
and look for message IDE0067 from intellisense.

## Environment

Nuget Package: 2.0.311

Package Version(s):
Affected platform(s):
- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:
- [ ] 2017 (version: )
- [X] 2019 (version: 16.3.2)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
The trick here will be to avoid inheriting the `Geolocator` from `Java.Lang.Object` and instead create a separate class as "listener", which will then be disposed of internally within the `Geolocator` logic.

**Comment by pkar70** [comment]
While implementing this change, consider also #2536  :)

**Comment by MartinZikmund** [comment]
This is now resolved
