### ISSUE TITLE
Facebook login integration

### ISSUE THREAD

**Issue by xinapstrink** [unoplatform/uno#203]
Hi, is facebook login integration possible? Theres any example?

**Comment by jeromelaban** [comment]
Thanks for your interest in the Uno Platform! 

The support for facebook can be done through the standard APIs, and standard authentication techniques with the WebView control should be enough, using the `Xamarin.Facebook.Android` and `Xamarin.Facebook.iOS` packages. For WebAssembly, the recipe has yet to be defined.

**Comment by egarim** [comment]
Is there a recipe for webassembly?

**Comment by jeromelaban** [comment]
This space has been improving recently with the integration of MSAL.NET. There's an in-progress PR on the topic: https://github.com/unoplatform/uno/pull/3262

/cc @carldebilly
