### ISSUE TITLE
ContextFlyout support

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#2031]
## What would you like to be added:
ContextFlyout support
<https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.contextflyout>

## Why is this needed:
ContextFlyout is something I use in most of my apps...

## For which Platform:

- [X] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by carldebilly** [comment]
This would be a great feature. The missing part is a _long press_ gesture recognizer.

**Comment by pkar70** [comment]
Long press gesture is "given" in Android - it has onLongClick() .
To not call "standard" onClick() together with onLongClick() :
https://stackoverflow.com/questions/4402740/android-long-click-on-a-button-perform-actions

**Comment by carldebilly** [comment]
Yep, but it needs to be implemented on all platforms to be useful :-)

> @dr1rrb it's on your plate?

**Comment by pkar70** [comment]
Not really... Maybe someone only needs UWP and Android?

And on all platforms without longClick, RightClick - it can be something like:
OnNativeTap() { lastTapTime = datetime.now }
OnNativeUntap() {if ((datetime.now - lastTapTime).totalseconds > 0.7) invoke(RightTap); else invoke(LeftTap);}

**Comment by pkar70** [comment]
Now, we have RightTapped event, so first step toward ContextFlyout  is done :)
