### ISSUE TITLE
LostFocus missing from UpdateSourceTrigger enum

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#2033]
The `UpdateSourceTrigger` enum is missing the `LostFocus` value, causing compile errors if it's referenced.

It should be added and marked with the `[NotImplemented]` attribute.

https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.updatesourcetrigger

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by 06needhamt** [comment]
Hi All

I am interested in contributing a fix for this issue. As a first time contributor are there any CLA’s I need to agree to?

**Comment by weitzhandler** [comment]
Can this one be closed?

**Comment by jeromelaban** [comment]
Yes, this can be closed, though the feature itself is not implemented.
