### ISSUE TITLE
[WASM] Textbox height decreases\collapses when text is entered

### ISSUE THREAD

**Issue by wallyh010** [unoplatform/uno#2034]
## Current behavior
Textbox height decreases\collapses when text is entered

## Expected behavior
Textbox height remains unchanged when text is entered

## How to reproduce it (as minimally and precisely as possible)
Enter text into textbox and textbox height will decrease

## Environment
Nuget Package:  Uno.UI
Package Version(s): Introduced in 2.0.512-dev.3728.  Bug did not occur in 2.0.512-dev.3683.
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
  - [x] Chrome
  - [x] Edge
  - [x] Firefox
  - [ ] Safari (Did not check)
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [x] Resharper (version: 2019.2.2)

Example:
![collapsedtextbox](https://user-images.githubusercontent.com/29922778/68309973-45ca0180-007d-11ea-9974-09d96476c95b.png)

Related: 
- https://github.com/unoplatform/uno/issues/867
- https://github.com/unoplatform/uno/issues/1561

**Comment by carldebilly** [comment]
Thanks @wallyh010 for reporting this bug.

The way it's designed in HTML, a `<input type="text" />` won't _measure_ itself according to its content. The size of an input in HTML is coming from the layout, not its content.

But... it seems possible to change this behavior, I just found [somebody did this on Codepen](https://codepen.io/Momciloo/pen/bpyMbB).

**Comment by carldebilly** [comment]
Related to https://github.com/unoplatform/uno/issues/1561

**Comment by jeromelaban** [comment]
@carldebilly was not fixed by #1561
