### ISSUE TITLE
MVVM example which can work with reactiveui and webassembly

### ISSUE THREAD

**Issue by BenDerPan** [unoplatform/uno#2041]
## What would you like to be added:
I want to build an app with uno, and hope to do it with reactiveui mvvm.
## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] Windows

## Anything else we need to know?
I tried [do-uno-mvvm](https://nicksnettravels.builttoroam.com/do-uno-mvvm/), it seems outdated, finnally I make it work, but I don't know if it's a best way. reactiveui is a nice mvvm framework, can I use it in uno, especially work with webassembly ?

**Comment by jeromelaban** [comment]
Thanks for asking @BenDerPan!

You can use this sample coming from the ReactiveUI samples repository: https://github.com/reactiveui/ReactiveUI.Samples/tree/master/uno

**Comment by BenDerPan** [comment]
great!
