### ISSUE TITLE
[iOS] Textblock crashes

### ISSUE THREAD

**Issue by baptiste-nv** [unoplatform/uno#2051]
# Current behavior
Crashes related with TextBlock occurs on iOS with following stacktrace

EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

`0  [AppName]                          0x102a33754 Windows_UI_Xaml_Controls_TextBlock_LayoutTypography_Windows_Foundation_Size + 310 (D:\a\1\s\src\Uno.UI\UI\Xaml\Controls\TextBlock\TextBlock.iOS.cs:310)
1  ???                            0x16f3f1818 (Missing)
2  [AppName]                          0x102a32a4c Windows_UI_Xaml_Controls_TextBlock_ArrangeOverride_Windows_Foundation_Size + 150 (D:\a\1\s\src\Uno.UI\UI\Xaml\Controls\TextBlock\TextBlock.iOS.cs:150)
3  [AppName]                          0x1028c72ec Windows_UI_Xaml_FrameworkElement_FrameworkElementLayouter_ArrangeOverride_Windows_Foundation_Size + 609 (D:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.cs:609)
4  [AppName]                          0x102a5e5a8 Windows_UI_Xaml_Controls_Layouter_Arrange_Windows_Foundation_Rect + 232 (D:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Layouter\Layouter.cs:232)
5  [AppName]                          0x1028c1614 Windows_UI_Xaml_FrameworkElement_LayoutSubviews + 59 (D:\a\1\s\src\Uno.UI\UI\Xaml\FrameworkElement.iOS.cs:59)
6  [AppName]                          0x101ae9a38 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 4386708024
7  [AppName]                          0x1040a9c9c mono_jit_runtime_invoke + 3051 (mini-runtime.c:3051)
8  [AppName]                          0x10412dd20 mono_runtime_invoke_checked + 2942 (object.c:2942)
9  [AppName]                          0x104131638 mono_runtime_invoke + 2996 (object.c:2996)
10 [AppName]                          0x100b9fc14 native_to_managed_trampoline_4(objc_object*, objc_selector*, _MonoMethod**, unsigned int) + 154 (registrar.m:154)
11 [AppName]                          0x100ba1a08 -[Windows_UI_Xaml_FrameworkElement layoutSubviews] + 10456 (registrar.m:10456)
12 UIKitCore                      0x1bc6c577c -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1380
13 QuartzCore                     0x19363db7c -[CALayer layoutSublayers] + 184
14 QuartzCore                     0x193642b34 CA::Layer::layout_if_needed(CA::Transaction*) + 324
15 QuartzCore                     0x1935a1598 CA::Context::commit_transaction(CA::Transaction*) + 340
16 QuartzCore                     0x1935cfec8 CA::Transaction::commit() + 608
17 QuartzCore                     0x19350e2a4 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 324
18 QuartzCore                     0x1935d73e8 display_timer_callback(__CFMachPort*, void*, long, void*) + 272
19 CoreFoundation                 0x18efaaf0c __CFMachPortPerform + 188
20 CoreFoundation                 0x18efd2758 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
21 CoreFoundation                 0x18efd1ea4 __CFRunLoopDoSource1 + 440
22 CoreFoundation                 0x18efccc5c __CFRunLoopRun + 2140
23 CoreFoundation                 0x18efcc0e0 CFRunLoopRunSpecific + 436
24 GraphicsServices               0x191245584 GSEventRunModal + 100
25 UIKitCore                      0x1bc21cc00 UIApplicationMain + 212
26 [AppName]                          0x101c47618 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 4388140568
27 [AppName]                          0x101ba764c UIKit_UIApplication_Main_string___intptr_intptr + 79 (UIApplication.cs:79)
28 [AppName]                          0x101ba753c UIKit_UIApplication_Main_string___string_string + 64 (UIApplication.cs:64)
29 [AppName]                          0x101ba7608 UIKit_UIApplication_Main_string___System_Type_System_Type + 69 (UIApplication.cs:69)
30 [AppName]                          0x100c31a84 [AppName]_Application_Main_string__ + 1 (<unknown>:1)
31 [AppName]                          0x101ae9a38 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 4386708024
32 [AppName]                          0x1040a9c9c mono_jit_runtime_invoke + 3051 (mini-runtime.c:3051)
33 [AppName]                          0x10412dd20 mono_runtime_invoke_checked + 2942 (object.c:2942)
34 [AppName]                          0x104133c04 mono_runtime_exec_main_checked + 4846 (object.c:4846)
35 [AppName]                          0x10408a174 mono_jit_exec + 1211 (driver.g.c:1211)
36 [AppName]                          0x1041f0688 xamarin_main + 485 (monotouch-main.m:485)
37 [AppName]                          0x100be4f94 main + 307 (main.m:307)
38 libdyld.dylib                  0x18ea8abb4 start + 4`

## Expected behavior
No Crash

## How to reproduce it (as minimally and precisely as possible)
Internal project

## Environment

Nuget Package:
Uno.UI 1.46.196-dev.2440

Affected platform(s):

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [X] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Can you link to the internal issue please ?
