### ISSUE TITLE
Samples Apps updates to Uno 2.0

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2071]
Update sample applications to Uno 2.0 tracking:

Active canaries: 
https://dev.azure.com/uno-platform/Uno%20Platform/_dashboards/dashboard/96ce9c93-d547-4732-8262-8682415292a1

- [ ] https://playground-staging.platform.uno
   https://github.com/unoplatform/Uno.Playground/pull/85 2.0.512-dev.4178

- [ ] https://xamlcontrolgallery-xamlcontrolgallery-staging.azurewebsites.net
   https://github.com/unoplatform/Uno.Xaml-Controls-Gallery/pull/54 2.0.512-dev.4178

- [ ] https://raytracermonoaot-staging.azurewebsites.net
   - https://github.com/unoplatform/Uno.RayTraceBenchmark/pull/14
- [ ] https://uno-wct-uno-wct-staging.azurewebsites.net
   https://github.com/unoplatform/Uno.WindowsCommunityToolkit/pull/73 2.0.512-dev.4178
- [ ] https://xamlbehaviors-staging.azurewebsites.net
- [ ] https://uno-telerik-ui-uno-telerik-ui-staging.azurewebsites.net
- [ ] https://calculator-wasm-staging.azurewebsites.net
   2.0.512-dev.4178
- [ ] https://uno-gallery-aot-uno-gallery-staging.azurewebsites.net
- [ ] https://xf-uno-wasm-staging.azurewebsites.net/
- [ ] https://uno-roslynquoter-staging.azurewebsites.net
- [ ] https://winstatetrigwasmstaging.z13.web.core.windows.net
- [ ] https://uno-lottie-staging.azurewebsites.net
- [ ] https://skiasharp-wasm-staging.azurewebsites.net/
- [ ] https://uno-azuredevops-staging.azurewebsites.net/
- [ ] https://rpncalculator-wasm-staging.azurewebsites.net

**Comment by carldebilly** [comment]
@jeromelaban Would be nice to should the Uno.UI version in the playground somewhere...
