### ISSUE TITLE
[Android] image_stretch_full_wider test is incorrect

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2072]
## Current behavior

The behavior of the image_stretch_full_wider test is incorrect.

## How to reproduce it (as minimally and precisely as possible)

View the image_stretch_full_wider UI Test.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

https://dev.azure.com/nventive/Umbrella/_workitems/edit/164298/

**Comment by agneszitte-nventive** [comment]
Working to do a repro sample for this one, and will do a repro also for #92 after that

**Comment by agneszitte-nventive** [comment]
[UnoImageSample.zip](https://github.com/unoplatform/uno/files/3852787/UnoImageSample.zip)

**Comment by carldebilly** [comment]
Should be fixed by PR #2112 producing version v`2.0.512-dev.3992`.

**Comment by MatFillion** [comment]
@jeromelaban @carldebilly internal issue has fix failed.
