### ISSUE TITLE
C# Edit and Continue not Working in UWP Head

### ISSUE THREAD

**Issue by Giss47** [unoplatform/uno#2078]
I have replicated the Demo by Mr.  Jerome Laban in UnoConf Livestream in September. I have the latest UNO.UI package and the latest Extension for UNO template. I have looked into the settings for debugging and nothing caught my eye. I have used the same settings on a stand alone UWP project created and built in VS 2019 Enterprise 19.3.9
. The C# E&C is working with no problems. 
Any Ideas!

![UNO](https://user-images.githubusercontent.com/43903770/68742912-8e3f6d00-05f1-11ea-8167-dd9654152b52.jpg)

**Comment by jeromelaban** [comment]
Hi @Giss47 this is an issue that is being tracked by microsoft here: https://developercommunity.visualstudio.com/content/problem/705494/without-any-changes-to-source-files-edits-were-mad.html

We suggest you follow this issue instead.

**Comment by Giss47** [comment]
Thank you and have a great day
