### ISSUE TITLE
[Android] Clipping behavior regression

### ISSUE THREAD

**Issue by crogeniks** [unoplatform/uno#2083]
##  Current behavior

- Horizontal Stackpanel doesn't take the full width in a grid column
- Image doesn't clip in a vertical StackPanel

![image](https://user-images.githubusercontent.com/1256256/68785735-9d7fe400-060c-11ea-97b7-727b80b08152.png)

## Expected behavior

UWP screenshot :
![image](https://user-images.githubusercontent.com/1256256/68785849-c607de00-060c-11ea-8377-35bedbdc9dfa.png)

## How to reproduce it (as minimally and precisely as possible)

Open and run the following sample
[App3.zip](https://github.com/unoplatform/uno/files/3842448/App3.zip)

## Environment

Nuget Package:

Package Version(s): Latest dev (2.0.512-dev.3895)

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

**Comment by crogeniks** [comment]
As additional information, the Horizontal StackPanel doesn't have any issue in a 8.1 emulator

![image](https://user-images.githubusercontent.com/1256256/68795415-ea6cb600-061e-11ea-8c23-5f0190b67d40.png)

The image clipping issue is still present.

**Comment by carldebilly** [comment]
Fixed in latest dev version.
