### ISSUE TITLE
TextBox Content Template doesn't apply properly

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#2095]
## Current behavior
when setting a default style of a TextBox, which overrides the ContentTemplate, it doesn't respond to mouse events nor focus
## Expected behavior
the TextBox should respond accor
## How to reproduce it (as minimally and precisely as possible)

[TextBoxTemplateIssue.zip](https://github.com/unoplatform/uno/files/3853106/TextBoxTemplateIssue.zip)

## Environment
WASM

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This is regression was introduced by #1726
