### ISSUE TITLE
[iOS] DatePickerFlyout SelectedDate crash

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2096]
## Current behavior

In iOS12 and 13, when the DatePickerFlyout is called, the date is January-2-1, when we change the selected date to January-1-1, the app crashes.

Note:
In iOS11, when the DatePickerFlyout is called, the date is December-31-1, when we change the selected date to January-1-1, the app does not crash.

## Expected behavior

In iOS12 and 13, when we change the selected date to January-1-1, the app does not crash

## How to reproduce it (as minimally and precisely as possible)

[DatePickerSelectedDateSample.zip](https://github.com/unoplatform/uno/files/3852535/DatePickerSelectedDateSample.zip)

## Environment

Nuget Package: Uno 1.45

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks! Is there an internal issue for this one ?

**Comment by carlh98** [comment]
Not at the moment, I found it while working on the other issue

**Comment by carlh98** [comment]
In iOS 11, 12 and 13, the app displays January-1-1 and does not crash when we change the date
