### ISSUE TITLE
Top-level Self-binding DataContext in Page is not working

### ISSUE THREAD

**Issue by Daoting** [unoplatform/uno#212]
## I'm submitting a...

 - Bug report (I searched for similar issues and did not find one)   
 

## Current behavior

TextBox does not support text binding in iOS. UI is no response when include text binding.
`<TextBox Text="{Binding Title}" />`

## Environment

```
Nuget Package: 

Package Version(s): 

Affected platform(s):
- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by MatFillion** [comment]
Thank you @Daoting for your report.

Typically I bind the Text property of TextBox using 
```xml
<TextBox Text="{Binding FirstName, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" />
```

Could you provide your code snippets? (XAML and C# DataContext) It would help use understand and reproduce your issue.

**Comment by Daoting** [comment]
xaml:
```
dt:PageWin
    x:Class="Dt.Sample.TestDemo1"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    xmlns:dt="using:Dt.Base">

    <TextBox Text="{Binding Title}" />
</dt:PageWin>
```

Code:
```
    public sealed partial class TestDemo1 : PageWin
    {
        public TestDemo1()
        {
            InitializeComponent();
            DataContext = this;
        }
    }
```


Title's define:
```
    public partial class PageWin : ContentControl, IWin
    {
        public readonly static DependencyProperty TitleProperty = DependencyProperty.Register(
            "Title",
            typeof(string),
            typeof(PageWin),
           new PropertyMetadata("No Title"));
           
           
        public string Title
        {
            get { return (string)GetValue(TitleProperty); }
            set { SetValue(TitleProperty, value); }
        }
    }
```

It cannot load the ui that include text binding. Thanks.

**Comment by jeromelaban** [comment]
There may be an issue with self-DataContext binding. Can you try with a sub-object, or using `x:Bind` ?

**Comment by morning4coffe-dev** [comment]
I have tested this one with Android, everything there seems to work as expected now. I will test with the team on iOS as well.

**Comment by rajamatt** [comment]
@morning4coffe-dev On iOS control appears and binding is working.

![image](https://github.com/user-attachments/assets/a2761051-ece3-4bd9-b3b0-589983fd0ab5)

**Comment by morning4coffe-dev** [comment]
Thanks @rajamatt! This is the same behavior I am seeing on WinUI and Android as well. Can we close @MartinZikmund?

**Comment by MartinZikmund** [comment]
Yes, closing!
