### ISSUE TITLE
[all platforms] Image clipping is incorrect

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2122]
## Current behavior

- https://unoplayground-staging.azurewebsites.net/#701c1d0c
![image](https://user-images.githubusercontent.com/5839577/69175947-c0aa0800-0ad2-11ea-9f1b-8b68ec001b37.png)

- https://unoplayground-staging.azurewebsites.net/#cards
![image](https://user-images.githubusercontent.com/5839577/69175968-c9024300-0ad2-11ea-97a0-aaa48724d66c.png)

## Expected behavior

The images should be clipped properly

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
Should be fixed by PR #2123
