### ISSUE TITLE
[WCT] Top menu selector is misplaced

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2126]
## Current behavior

In the Windows Community Toolkit:
![image](https://user-images.githubusercontent.com/5839577/69184142-42edf880-0ae2-11ea-9661-fcb3a1f95aaf.png)

Package Version(s):2.0.512-dev.3976

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dr1rrb** [comment]
This is 2 level bug:
1. `ItemsStackPanel` is not stretching items properly:  https://github.com/unoplatform/uno/issues/2136
2. `ListView` is able to scroll while it should not: https://github.com/unoplatform/uno/issues/2111

Closing this bug in favor of the 2 others.
