### ISSUE TITLE
ViewBox is altering the RenderTransform of its child

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#2135]
## Current behavior
When a UI element in a `ViewBox` is applied a rotation transform, the transform is overwritten by the `ViewBox`
~~When a UI element is applied a rotation transform, for example over a border, the transform moves it across the X and Y , but doesn't rotate it~~
## Expected behavior
It should rotate  the control as shown in the image:
![image](https://user-images.githubusercontent.com/888391/69341829-37c1d680-0c62-11ea-8dc8-d945eb937d97.png)
## How to reproduce it (as minimally and precisely as possible)
clone https://github.com/SuperJMN/UnoSimpleCalc/tree/Rotation
checkout the **Rotation** branch
and see the difference between UWP and WASM

## Environment

Affected platform(s):

- [?] iOS
- [?] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

**Comment by dr1rrb** [comment]
When I was investigating the pointer issue with the `ViewBox`, I notice that our current implementation is [modifying the `RenderTransform` of it child](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Controls/ViewBox/Viewbox.cs#L101), which is probably not valid!

In your sample, I would assume that if you add an extra border between the [`ViewBox` and the `Border` with the rotate transform](https://github.com/SuperJMN/UnoSimpleCalc/blob/Rotation/UnoSimpleCalc/UnoSimpleCalc.Shared/MainPage.xaml#L12), the rotation applies:

![image](https://user-images.githubusercontent.com/8635919/69347852-36cd7c80-0c43-11ea-8128-eaf761828db5.png)

Note: I also had to set the `RenderTransformOrigin=".5,.5"`, but it was like UWP.

I update the bug details accordingly.

**Comment by paulovila** [comment]
Also note that when you rotate a button the clicking area does not rotate
```xml
<ItemsControl.ItemTemplate>
    <DataTemplate x:DataType="viewModels:ButtonViewModelBase">
        <Button VerticalAlignment="Stretch" HorizontalAlignment="Stretch"
                Command="{Binding }" Content="{Binding Text}" >
            <Button.RenderTransform>
                <CompositeTransform Rotation="-22.246"/>
            </Button.RenderTransform>
        </Button>
    </DataTemplate>
</ItemsControl.ItemTemplate>
```
![image](https://user-images.githubusercontent.com/888391/69379418-58148400-0ca8-11ea-9176-0f528060ef87.png)
So if you click in the corners of the button it doesn't work

**Comment by dr1rrb** [comment]
Fixed ... commit coming soon
