### ISSUE TITLE
[Wasm] Add support for IsTabStop (TextBox Reveal and Clear)

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2138]
## Current behavior

Tapping on a `TextBox` delete button does not work the first time.

## Expected behavior

Tapping on the button deletes the `TextBox` content.

## How to reproduce it (as minimally and precisely as possible)

Use the `TextBox_DeleteButton_Automated` UI Test.

The reason this behavior happens is caused by the fact that the delete button takes the focus and does not respect the `IsTabStop="false"` property. Clicking the button makes it disappear because the `TextBox` loses focus, making it lose its ability to click.

A proper implementation of the Focus chain is required to get the proper behavior.

## Environment

Nuget Package:

Package Version(s): 2.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
This seems to be fixed by older focus improvements.
