### ISSUE TITLE
ValueConverters Library isn't usable in Uno

### ISSUE THREAD

**Issue by SuperJMN** [unoplatform/uno#214]
https://github.com/thomasgalliker/ValueConverters.NET

Concretely, I've had troubles when tried to use the `BooleanToVisiblityConverter` and `EnumToObjectConverter`

It's a pity, because it contains a big collection of useful and flexible value converters.

Please, take a look to it. I'm very interested in it.

**Comment by jeromelaban** [comment]
Thanks for the report, we'll take a look!

**Comment by MartinZikmund** [comment]
Most of these converters are now available as part of https://learn.microsoft.com/en-us/windows/communitytoolkit/helpers/converters,. which is compatible with Uno Platform
