### ISSUE TITLE
Animation in code crashes on iOS

### ISSUE THREAD

**Issue by rdagglis** [unoplatform/uno#2148]
## Current behavior

Running an animation in code on iOS causes a crash. In my test, I simply define a TranslateTransform.

## Expected behavior

Running an animation in code on iOS should not crash.

## How to reproduce it (as minimally and precisely as possible)

I've created a sample project:

[https://github.com/rdagglis/UnoErrors](https://github.com/rdagglis/UnoErrors)

## Environment

Nuget Package: **Uno.UI 2.0.512-dev.3683**

Affected platform(s):

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

## Anything else we need to know?

The code that creates the animation is located in a Canvas control:

[https://github.com/rdagglis/UnoErrors/blob/master/UnoErrors/UnoErrors.Shared/MyCanvas.cs](https://github.com/rdagglis/UnoErrors/blob/master/UnoErrors/UnoErrors.Shared/MyCanvas.cs)

**Comment by Massimo37** [comment]
@jeromelaban I was able to repro this easily. If you'd like I can take this bug and investigate it.

**Comment by jeromelaban** [comment]
@Massimo37 yes please, thanks very much!

**Comment by Massimo37** [comment]
@jeromelaban so essentially it stems from the dependency property not being found:

![crash-source](https://user-images.githubusercontent.com/36633246/69645247-dd46c280-1033-11ea-81fb-dbdd0972e84e.jpg)

The TranslateTransform is looking for "TranslateTransform.X" instead of "X" as the property in the property cache. If you know of anything I can investigate, feel free to let me know.

**Comment by jeromelaban** [comment]
This generally means that the format of the property is either incorrect, or not found. What's the original path of the property ? (e.g. are there parentheses)

**Comment by Massimo37** [comment]
@jeromelaban 

     "(UIElement.RenderTransform).(TranslateTransform.X)"

**Comment by jeromelaban** [comment]
Interesting, then it feels like both an invalid parsing issue, as well as an failure to find what TranslateTransform is.
