### ISSUE TITLE
[Calculator][Wasm][Chrome] Memory not displaying numbers correctly

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/uno#2155]
### Repro Steps
Go to https://calculatorcanary.z27.web.core.windows.net/
Select Standard calculator
Select Memory from the top right corner
Enter in a value of at least two numbers 
Press M+
Notice that the number in the memory section is not on the same line

### Current Results

![image](https://user-images.githubusercontent.com/49959074/69459615-2e0ea080-0d40-11ea-9e50-bb99e9b1fb3b.png)

### Expected Results

![image](https://user-images.githubusercontent.com/49959074/69459638-3cf55300-0d40-11ea-8a3d-fc7995a5b340.png)

**Comment by dr1rrb** [comment]
This seems to be the same bug as https://github.com/unoplatform/private/issues/106
