### ISSUE TITLE
[Calculator][Android] Last drop-down option isn't visible for some converters

### ISSUE THREAD

**Issue by Hpancha** [unoplatform/uno#2157]
### **Steps To Reproduce:**

1. Launch an UNO Calculator app on Android device.
2. Select any converter from **Volume,** **Weight and Mass,** or **Data**
3. Put the app in the landscape mode.
4. Select the drop-down for 1st value and scroll all the way down.
5. Observe the last option.

### **Actual behavior:**

- The last option for the drop-down does not appear and it's cutting from the bottom. 
- I could reproduce this issue only in 2 devices. May be it's related to the edge screen of the phone but I'm still not sure.
- This issue doesn't occur for the drop-down of 2nd value.

### **Expected behavior:**

- User can see all the options clearly without any trimming issue.

### **Attachment:**

![trimming_issue](https://user-images.githubusercontent.com/51453677/69457495-27c9f580-0d3b-11ea-8e55-a66465e54a53.jpg)

### **Device and Application Information:**
 - **OS Build:** android
 - **Build Version:** 1.2.0-uno.558
 - **Devices:**  Samsung Note 10+ (9), Samsung S10+ (9)

### **Note:**
- Refer the attached image to get better idea.

**Comment by sakshi173** [comment]
This issue is fixed. Below is the screenshot.
![calc2](https://user-images.githubusercontent.com/74563602/120375476-d7950180-c2e8-11eb-8faa-0d66622dd00c.png)

**Comment by Youssef1313** [comment]
@MartinZikmund Should this get closed based on @sakshi173 comment?

**Comment by sakshi173** [comment]
Verified issue is fixed, closing.
