### ISSUE TITLE
[ios] Keypad is zooming in by changing any calculator 

### ISSUE THREAD

**Issue by Hpancha** [unoplatform/uno#2159]
### **Steps To Reproduce:**

1. Launch an UNO Calculator app on any ios device.
2. Now change the type of the calculator by selecting from the burger menu.
3. Observe the keypad.

### **Actual behavior:**

- The keypad is zooming in every time the user changes the calculator type.

### **Expected behavior:**

- The keypad has to be stable as appear in Android app.

### **Attachment:**

[Keypad_issue.zip](https://github.com/unoplatform/calculator/files/3880314/Keypad_issue.zip)

### **Device and Application Information:**
 - **OS Build:** ios 13
 - **Build Version:** 1.2.0-uno.572
 - **Devices:**  iPhone XR (13)

### **Note:**
- Refer the attached video to get better idea.

**Comment by jeromelaban** [comment]
As weird as it is, this is not a bug. This may get changed when we update to a later version of the original source.
