### ISSUE TITLE
[ios] The converter drop menu doesn't have any close button

### ISSUE THREAD

**Issue by Hpancha** [unoplatform/uno#2164]
### **Steps To Reproduce:**

1. Launch an UNO Calculator app on Android device.
2. Select any converter from the burger menu.
3. Now open the dropdown menu and try to close it by tapping outside the menu. 

### **Actual behavior:**

- User can't close the drop down menu by tapping anywhere on the screen and also there is no close button.

### **Expected behavior:**

- Once the user select any drop down option then it should close the drop down menu.

### **Attachment:**

[drop-down_issue.zip](https://github.com/unoplatform/calculator/files/3880816/drop-down_issue.zip)

### **Device and Application Information:**
 - **OS Build:** ios 
 - **Build Version:** 1.2.0-uno.558
 - **Devices:**  iPhone XR (13.2), iPhone Xs Max (12)

### **Note:**
- Refer the attached video to get better idea.

**Comment by dr1rrb** [comment]
This has already been fixed by https://github.com/unoplatform/calculator/pull/235
