### ISSUE TITLE
[Calculator][iOS] The pressed state stays on any key for any keypad in any kind of calculator and converter

### ISSUE THREAD

**Issue by Hpancha** [unoplatform/uno#2165]
### **Steps To Reproduce:**

1. Launch an UNO Calculator app on Android device.
2. Open **Programmer** calculator.
3. Now pressed any keys with double fingers frequently.
4. Now observe the keypad buttons.

### **Actual behavior:**

- The hover state stays there on any key by just pressing keys multiple time. 

### **Expected behavior:**

- The hover state should not remain there even after pressing the keys multiple times.

### **Attachment:**

**Actual Result:**

![Scientific_calculator](https://user-images.githubusercontent.com/51453677/69444259-fee73780-0d1d-11ea-8f21-c2a69a8b244b.PNG)
![Standard_calculator](https://user-images.githubusercontent.com/51453677/69444260-fee73780-0d1d-11ea-9dcc-7e1cc4392e05.PNG)
![Length_Converter](https://user-images.githubusercontent.com/51453677/69444262-fee73780-0d1d-11ea-82e8-54471cf0b235.PNG)

### **Device and Application Information:**
 - **OS Build:** any ios
 - **Build Version:** 1.2.0-uno.558
 - **Devices:**  iPhone XR (13.2), iPhone XS Max (12)

### **Note:**
- Refer the attached images to get better idea.

**Comment by dr1rrb** [comment]
Should be fixed by https://github.com/unoplatform/uno/pull/2445
