### ISSUE TITLE
ContentControl's  ContentTemplate attribute bingding a null ContentTemplate,but content is not null,the content shows in Andriod but show nothing in ios.

### ISSUE THREAD

**Issue by double28** [unoplatform/uno#217]
## I'm submitting a...

 Bug report (I searched for similar issues and did not find one) 
 

## Current behavior

I defined an usercontrol ,the ContentTemplate  using an templatebinding,but the binding template is null. In Andriod ,the content of this control shows well,but in ios,it show nothing.

## Expected behavior

I wish it show the same just like in Androd when it run in ios.

## Environment

```
Nuget Package: 

Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ enterprise ] 2017 (version: 15.7.1)
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by jeromelaban** [comment]
Thanks for the report!

iOS and Android are behaving a bit differently in this regard. For what I remember, a ContentControl with a null template is supposed to be showing nothing, but Uno for Android may have a special case defined that we call the 

https://github.com/nventive/Uno/blob/7d372d8a4c29e4fb008b7bfad5fe1d90fca287bf/src/Uno.UI/UI/Xaml/Controls/ContentControl/ContentControl.cs#L414


which makes it show content anyways. This was used to reduce the number of view in the visual tree in Android 4.4 and below, but is less used nowadays.

Did you try on Windows to determine the proper behavior ?

**Comment by double28** [comment]
It works in uwp,the content can be show as in andriod. I want it show the content in ios as well as in andriod an uwp even there is no contenttemplate, I dot't know wether is it make sense!

**Comment by jeromelaban** [comment]
This indeed should work. Could you create a sample from the Uno Platform Visual Studio template that demonstrates the issue ? Thank you!

**Comment by jeromelaban** [comment]
This has been addressed in recent builds Uno.
