### ISSUE TITLE
Canvas webgl and opengl es?

### ISSUE THREAD

**Issue by Thaina** [unoplatform/uno#218]
## I'm submitting a...
- Feature request
- Documentation issue or request

Can we make a 3D game in uno ? Is it possible to have canvas object with webgl in browser and opengles in mobile with one set of api?

**Comment by jeromelaban** [comment]
Thanks for you interest in the Uno Platform !
- For iOS and Android, you can use any Xamarin (non-forms) library which provies OpenGL access.
- For WebAssembly, this is a bit different. You can use any kind of HTML and Javascript, for we have yet to add support for a **NativeHTMLView** control which would allow for adding arbitrary HTML from the xaml. That being said, it's posible to use javascript Eval and manipulate any kind of Javascript library.
