### ISSUE TITLE
[Calculator][Android-Wasm] Calculator does not resize correctly in Landscape

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/uno#2182]
## Current behavior

![calculator android landscape bad](https://user-images.githubusercontent.com/49959074/69558642-8d55f600-0f76-11ea-99b0-ac1ea67263ba.gif)

## Expected behavior

![calculator android landscape good](https://user-images.githubusercontent.com/49959074/69558919-0ead8880-0f77-11ea-8f30-ed1b7b7b9b18.gif)

## How to reproduce it (as minimally and precisely as possible)

Open Chrome on Android device
Visit https://calculatorcanary.z27.web.core.windows.net/
Rotate device to Landscape mode
Notice that Calculator does not resize correctly

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by sakshi173** [comment]
The screen is not fully displaying , but not able to reproduce the issue in similar way.
Below is the screenshot of the current issue.
![calc](https://user-images.githubusercontent.com/74563602/120370611-cea13180-c2e2-11eb-8f75-ac7729e25dd3.png)

**Comment by sakshi173** [comment]
Verified , Closing
