### ISSUE TITLE
[Calculator][Wasm][Chrome] Selecting Programmer Calculator does not change title

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/uno#2184]
## Current behavior

![calculator title change](https://user-images.githubusercontent.com/49959074/69564167-82a05e80-0f80-11ea-80ce-997a02275926.gif)

## Expected behavior

![image](https://user-images.githubusercontent.com/49959074/69564189-8b913000-0f80-11ea-94a1-dfe366cd88d4.png)

## How to reproduce it (as minimally and precisely as possible)

Visit https://calculatorcanary.z27.web.core.windows.net/
Open burger menu
Select Programmer
Notice that Calculator changes to Programmer however the title remains Standard

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Interpreter issue, most likely fixed in latest mono. Closing for now.
