### ISSUE TITLE
[Calculator][MacOS][Safari] Site stays at Calculator Splash Screen

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/uno#2187]
## Current behavior

Webpage remains at Calculator Splash Screen

## Expected behavior

Webpage should load Calculator correctly

## How to reproduce it (as minimally and precisely as possible)

Using Safari visit https://calculatorcanary.z27.web.core.windows.net/
Notice that page stays at splash screen

## Environment

MacOS 10.15.1
Safari 13.0.3

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Interpreter build has some issues in safari, most likely fixed in later builds of mono. Closing for now.
