### ISSUE TITLE
ItemsControl.ContainerFromItem returns null when it shouldn't

### ISSUE THREAD

**Issue by SuperJMN** [unoplatform/uno#2198]
## Current behavior

`ItemsControl.ContainerFromItem` returns **null** when it shouldn't.

## Expected behavior

`ItemsControl.ContainerFromItem` must return the container of a given item.

## How to reproduce it (as minimally and precisely as possible)

1. Paste this code in a new Uno Platform application:

```
 public partial class MyItemsControl : ItemsControl
    {
        public IEnumerable<DependencyObject> Containers => Items.Select(ContainerFromItem);

        protected override DependencyObject GetContainerForItemOverride()
        {
            return new MyContainer();
        }

        protected override bool IsItemItsOwnContainerOverride(object item)
        {
            return item is MyContainer;
        }
    }

    public partial class MyContainer : ContentControl
    {
    }

    public class Item
    {
    }
```
2. Inside **MainWindow.xaml**, put this XAML
```
<Page
    x:Class="App1.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App1"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:app1="using:App1"
    mc:Ignorable="d">

  <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <app1:MyItemsControl x:Name="my">
      <local:Item></local:Item>
      <local:Item></local:Item>
      <local:Item></local:Item>
    </app1:MyItemsControl>
  </Grid>
</Page>
```
3. Inside MainWindow.xaml.cs, put this.
```
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
            this.Loaded += OnLoaded;
        }

        private void OnLoaded(object sender, RoutedEventArgs e)
        {
            var items = my.Containers.ToList();
        }
    }
```

4. Set a breakpoint after the `var items = my.Containers.ToList();` line in order to inspect its value.
5. Execute the application in UWP. The items list will contain 3 instances of type `MyContainer`. Thanks OK.
6. Execute the application in Android. The list will contain 3 **null** references.

## Environment

Package Version(s):
Latest to date (pre-release)

Affected platform(s):

- [ ] iOS
- [X] Android
- [X] WebAssembly (I assume that it fails in WASM, too, although I haven't been able to debug it)
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

We need to ensure that calling to ContainerFromItem from an instance of ItemsControl (not a derived class) returns a `ContentPresenter`.

**Comment by MartinZikmund** [comment]
This is now fixed on both Android and WASM
