### ISSUE TITLE
Please implement Manipulation Event

### ISSUE THREAD

**Issue by Daoting** [unoplatform/uno#221]
## I'm submitting a...

  
 - Feature request

## Current behavior

Manipulation Event is very useful in many scenarios. For example, switch tab page.

## Environment

```
Nuget Package: 

Package Version(s): 

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by davidjohnoliver** [comment]
Indeed Manipulation events would be very useful to have to support gesture interactions.

For the specific example you give of building a tabbed control, the FlipView could potentially be used as a base since it supports swipe gestures on UWP, iOS, and Android.

**Comment by ghuntley** [comment]
Related - https://github.com/unoplatform/uno/pull/1256

**Comment by dr1rrb** [comment]
I close this issue as it is now merged in master, feel free to open a new one if you have any problem.
