### ISSUE TITLE
[Android, iOS] The page background cannot be changed

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#2210]
## Current behavior
![Screenshot_20191127-152705_Backgroundsample](https://user-images.githubusercontent.com/17461593/69757317-bae3a080-112a-11ea-8f4e-0e82a415e758.png)

## Expected behavior
Result in UWP
![result UWP](https://user-images.githubusercontent.com/17461593/69757335-c46d0880-112a-11ea-8cf6-fa4eda65899a.PNG)

## How to reproduce it (as minimally and precisely as possible)

Create a new Uno sample 
Go to the main page and change the Page background 

![pageconde](https://user-images.githubusercontent.com/17461593/69757358-d189f780-112a-11ea-91d7-3030abb44f0d.PNG)

## Environment

Nuget Package: 1.45.0

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version:16.3.2)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Massimo37** [comment]
@takla21 Does it work if you set the background to the root element instead (the Grid) ??

**Comment by takla21** [comment]
Yeah, we can just set the background color of the grid like you said. But my point is that we can set the background of a page for UWP but not for Android and iOS. We should be able to have the same results on all platforms.

**Comment by MartinZikmund** [comment]
Related to #1674

**Comment by davidjohnoliver** [comment]
`Page` is a unique control in UWP/WinUI, it should render its Background itself (unlike every other control that relies upon an element in its template to show the background). We should fix this in Uno.
