### ISSUE TITLE
[Android] Button in Control does not emit Tapped events

### ISSUE THREAD

**Issue by jcantin-nventive** [unoplatform/uno#2238]
## Current behavior

When a Button is part of a Control, it does not emit its Tapped events on Android.

## Expected behavior

A Button always emits its Tapped events correctly.

## How to reproduce it (as minimally and precisely as possible)

Launch the app from [this repo](https://github.com/jcantin-nventive/control-button-tapped).
Tap on the button to the bottom left
If the Tapped event is received, the button's content changes to "Tapped event detected!"

## Environment

Nuget Package:

Package Version(s): 1.45.0

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [x] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
@jcantin-nventive this was fixed in latest 2.0-beta bits. Could you validate that ?

**Comment by jcantin-nventive** [comment]
> @jcantin-nventive this was fixed in latest 2.0-beta bits. Could you validate that ?

Yes, it is fixed in 2.0.512-beta.18!
