### ISSUE TITLE
Breaking change in Launcher.LaunchUri

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2239]
## Current behavior

A breaking change was introduced in https://github.com/unoplatform/uno/pull/2040, for which the return type of `Launcher.LaunchUri` came from `Task<bool>` to `IAsyncOperation<bool>`.

This change should have been caught by https://github.com/unoplatform/Uno.PackageDiff but wasn't. A new test case needs to be added.

While a valid change, the timing is not appropriate, as we'll be making as many breaking changes as possible in a single update to minimize the impact of those changes downstream (see https://github.com/unoplatform/uno/issues/2240).

## Expected behavior

A new change has to be added to restore the signatures modified by https://github.com/unoplatform/uno/pull/2040.

## Environment

Package Version(s): 2.1.0-dev.58

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
Oh sorry, I haven't noticed it changed at all 😶

**Comment by jeromelaban** [comment]
No worries ;) And with threading that's coming, it'll go away!
