### ISSUE TITLE
[Android] PasswordBox displays the password instead of dots

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2241]
## Current behavior

When you display a PasswordBox that has a InputScope converter, the password is not hidden with dots

## Expected behavior

When you display a PasswordBox that has a InputScope converter, the password is hidden with dots

## How to reproduce it (as minimally and precisely as possible)

Launch the sample and see that the password is visible

Sample:
[PasswordBoxDots.zip](https://github.com/unoplatform/uno/files/3913540/PasswordBoxDots.zip)

## Environment

Nuget Package:
Uno.UI 2.1.0-dev.58

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by NicolasChampagne** [comment]
The inputscope converter code was not able to parse InputScopeValueName enum, in project fix to the converter solves this issue.

https://dev.azure.com/nventive/_git/JeanCoutu/pullrequest/25428?_a=overview
https://dev.azure.com/nventive/_git/JeanCoutu/pullrequest/25429?_a=overview

**Comment by NicolasChampagne** [comment]
Converter that works:

`public class FromStringToInputScopeConverter : IValueConverter
	{
		public object Convert(object value, Type targetType, object parameter, string language)
		{
			var inputString = value as string;
			var inputScope = default(InputScopeNameValue);

			if ( !inputString.Equals(string.Empty) && Enum.TryParse<InputScopeNameValue>(inputString, out inputScope))
			{
				return new Windows.UI.Xaml.Input.InputScope()
				{
					Names = { new InputScopeName((inputScope as InputScopeNameValue?).Value) }
				};
			}

			return null;
		}

		public object ConvertBack(object value, Type targetType, object parameter, string language)
		{
			throw new NotSupportedException();
		}
	}`
