### ISSUE TITLE
Pointer events has wrong location when in a ViewBox on Android

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#2257]
## Current behavior
Pointer location are not valid

## Expected behavior
As UWP

## How to reproduce it (as minimally and precisely as possible)
```xaml
<Grid Background="#FF583793">
        <Viewbox  Stretch="Uniform" StretchDirection="Both">
            <Canvas x:Name="mainCanvas" Height="800" Width="800" Background="#FFA0ACA5" Margin="50,50,50,50" PointerPressed="UIElement_OnPointerPressed">
                <TextBlock x:Name="tblInfos" Height="64" Canvas.Left="10" Canvas.Top="10" Text="TextBlock" TextWrapping="Wrap" Width="780" FontSize="20" FontWeight="Bold"/>
                <TextBlock x:Name="tblInfos2" Height="64" Canvas.Left="10" Canvas.Top="63" Text="TextBlock" TextWrapping="Wrap" Width="780" FontSize="20" FontWeight="Bold"/>
                <Border x:Name="letter" BorderThickness="1" BorderBrush="Black" Height="200" Canvas.Left="50" Canvas.Top="300" Width="500" Background="#FF8D7E3B" HorizontalAlignment="Stretch"/>
            </Canvas>
        </Viewbox>

    </Grid>
```
```cs
        private void UIElement_OnPointerPressed(object sender, PointerRoutedEventArgs e)
        {
            var posCanvas = e.GetCurrentPoint(mainCanvas).Position;
            var posLetter = e.GetCurrentPoint(letter).Position;
            tblInfos.Text = $"canvas x:{posCanvas.X} y:{posCanvas.Y}";
            tblInfos2.Text = $"letter x:{posLetter.X} y:{posLetter.Y}";

        }
```

## Environment
Nuget Package: **Uno.UI**
Package Version(s): **2.0**
Affected platform(s):

- [?] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio: **_irrelevant_**
Relevant plugins: **_none_**

## Anything else we need to know?
https://stackoverflow.com/questions/59027861/content-not-centered-in-viewbox-and-incorect-mouse-coord-in-viewbox

**Comment by agneszitte-nventive** [comment]
@jeromelaban / @dr1rrb 
I also noticed a bug that when using the pointer event on a specific area (in this case a Path Control), on iOS/Android/WASM you can click outside of this area and the pointer event is still triggered compared to UWP where the event is only working in this specific area.
I tried to comment the <ViewBox /> around the content, but it's still the same.

Do you want to open another issue for that with a repro sample?
