### ISSUE TITLE
Bindings property when using x:Bind

### ISSUE THREAD

**Issue by oakrefactory** [unoplatform/uno#2260]
## What would you like to be added:
A Bindings property of a usercontrol, generated by the compiler, when adding x:Bind bindings.
## Why is this needed:
This is needed to be able to access the x:Bind bindings defined in XAML. When a datacontext changes, the bindings need to be updated. In UWP this is fixed easily by calling Bindings.Update() in the DataContextChanged eventhandler in the code behind.
## For which Platform:

- [ ] iOS
- [ ] Android
- [ x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?
I am just developing for UWP and WebAssembly, but maybe this applies also for other platforms other than UWP and WebAssembly

**Comment by jeromelaban** [comment]
Thanks for your suggestion!

Related to https://github.com/unoplatform/uno/issues/347
