### ISSUE TITLE
The touch target is not as big as the Button

### ISSUE THREAD

**Issue by Guidemarcus** [unoplatform/uno#2268]
## Current behavior

When setting the MinHeight and the height of a button, if the MinHeight is greater than the Height, the touch target will be as big as the Height and the button will be as big as the MinHeight.

## Expected behavior

The touch target should be as big as the button.

## How to reproduce it (as minimally and precisely as possible)

Create a Button and set the MinHeight with a greater value than the height.
[ButtonContentOff.zip](https://github.com/unoplatform/uno/files/3928422/ButtonContentOff.zip)

## Environment

Uno.UI 2.1.0-dev.90; VS2017

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] ~~WebAssembly~~
- [ ] ~~WebAssembly renderers for Xamarin.Forms~~
- [ ] ~~Windows~~
- [ ] ~~Build tasks~~
- [ ] ~~Solution Templates~~

Visual Studio:

- [x] 2017 (version: )
- [x] 2019 (version: )
- [ ] ~~for Mac (version: )~~

Relevant plugins:

- [ ] ~~Resharper (version: )~~

https://dev.azure.com/nventive/Umbrella/_workitems/edit/168844

**Comment by jeromelaban** [comment]
Related to #2270
