### ISSUE TITLE
A child element is not limited to its parent layout

### ISSUE THREAD

**Issue by Guidemarcus** [unoplatform/uno#2271]
## Current behavior

A child element is not limited to its parent's frontiers. ex : A child element should not have a bigger height than its parents. It should be limited to its parent.

## Expected behavior

A child element should be limited to its parent layout.

## How to reproduce it (as minimally and precisely as possible)

Put a big image in a small grid. Fix the height of the grid to 15 for example.
[MissingImage.zip](https://github.com/unoplatform/uno/files/3929119/MissingImage.zip)

## Environment

Uno.Ui 2.1.0-dev.90

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [x] 2017 (version: 15.9.16 )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Guidemarcus** [comment]
Potential fix from @carldebilly https://github.com/unoplatform/uno/pull/2270

**Comment by MartinZikmund** [comment]
Works now 🚀
