### ISSUE TITLE
[Android] ScrollViewer inside ListView bugs the horizontal scrolling

### ISSUE THREAD

**Issue by jcantin-nventive** [unoplatform/uno#2287]
## Current behavior

When a horizontal scrolling gesture includes vertical scrolling, then the horizontal scrolling stops being recognized, even if we resume horizontally scrolling in the same gesture.

## Expected behavior

Horizontal scrolling is recognized.

## How to reproduce it (as minimally and precisely as possible)

Launch the app from [this repo](https://github.com/jcantin-nventive/button-horizontal-scroll).
Try to scroll the items horizontally with a gesture that includes a bit of diagonal movement (not perfectly horizontal).
This works fine on iOS but not on Android.

## Environment

Nuget Package: Uno.UI

Package Version(s): 1.45.0 and 2.1.0-dev.189

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [x] 2017 (version: 15.9.11)
- [x] 2019 (version: 16.4.0 preview 6.0)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jcantin-nventive** [comment]
I'm no longer able to repro this issue in my samples. I'll keep looking into it but will close this for the moment

**Comment by jcantin-nventive** [comment]
After futher investigations, I've reproduced the issue in the sample and I'm reopening the issue.

**Comment by davidjohnoliver** [comment]
Brief investigation results: this seems to initially work as expected, then something falls into a bad state and the inner ScrollView no longer captures the gesture properly.

**Comment by davidjohnoliver** [comment]
Updated the sample to latest Uno and haven't been able to repro.

@jcantin-nventive wasn't this fixed by #2338?

**Comment by jcantin-nventive** [comment]
> Updated the sample to latest Uno and haven't been able to repro.
> 
> @jcantin-nventive wasn't this fixed by #2338?

If I remember correctly, my PR helped but didn't entirely solve the issue.

If it's now fixed, that's good.

**Comment by davidjohnoliver** [comment]
The attached repro definitely seems to be fixed. I'll close this issue, feel free to reopen it if you notice the bug occurring in a different context. :)
