### ISSUE TITLE
[iOS] Image loading concurrency issue

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#2295]
## Current behavior
When loading many times the same image (check any `Image_Stretch_` samples on the SampleApp) at the same time, sometimes none of them are loading.

![image](https://user-images.githubusercontent.com/4174207/70568480-fbe5a700-1b65-11ea-8429-4fd0ec23725b.png)

## Expected behavior
Images should all appear.

## How to reproduce it (as minimally and precisely as possible)
Check latest version of SampleApps on iOS (check previous screenshot)

## Environment

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by carldebilly** [comment]
This bug has been found while introducing the new samples pages in this PR: #2252, but it's unclear if it's a regression of this PR or an existing bug.

**Comment by MartinZikmund** [comment]
Works fine now :-) .
