### ISSUE TITLE
[WASM] Some Runtime Tests fail on WASM

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#2314]
These failures were uncovered by https://github.com/unoplatform/uno/pull/2301 - previously async tests weren't reporting failures.

 - MeasureOverride_With_Nan_In_Grid(), Cannot measure [Windows.UI.Xaml.Controls.Grid] with NaN - added by https://github.com/unoplatform/uno/pull/2175

 - When_MinWidth_SmallerThan_AvailableSize(), Assert.AreEqual failed. Expected:&lt;[110;15]&gt;. Actual:&lt;[50;15]&gt;. - added by https://github.com/unoplatform/uno/pull/2270

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
Why it's not blocking the CI?

**Comment by davidjohnoliver** [comment]
> Why it's not blocking the CI?

Failing `async` tests in `Uno.UI.RuntimeTests` were being incorrectly passed, https://github.com/unoplatform/uno/pull/2301 fixed this

**Comment by MartinZikmund** [comment]
This is now fixed
