### ISSUE TITLE
Linux support for Uno for embedded use

### ISSUE THREAD

**Issue by jerkstorecaller** [unoplatform/uno#2318]
## What would you like to be added:
Linux support for Uno

## Why is this needed:
Embedded apps span many industries, from SCADA panels to robot control interfaces to marketing kiosks. Due to how cheap and powerful hardware has become, many embedded systems are moving away from real-time OSes (or no OSes), to running on Linux. And we are seeing a migration away from C/C++ for the productivity boost. With .NET going open-source and supporting Linux as a 1st class citizens, C# will see a lot of adoption in that field, at least for non-UI services.

There is currently no established solution to have a rich UI written in C# running on Linux (aside from Unity which is not open-source, and which requires relatively beefy hardware anyway). Uno could fill that void if it were to provide Linux support.

WebAssembly is not a good solution as the application has no direct access to the filesystem, or hardware like the serial port, or perform arbitrary TCP/IP operations like UDP broadcast. It would require a native companion daemon on localhost to expose all these operations through an HTTP interface for the WebAssembly app, complicating the codebase. In other words embedded developers who need these things aren't gonna use WebAssembly.

Here is an example of the sort of embedded UI that people currently use Qt for: 
![image](https://user-images.githubusercontent.com/58572326/70828062-976e5600-1db8-11ea-91bd-54eb47c2e184.png)

**Comment by jeromelaban** [comment]
Thanks for the use case! This is indeed on our radar, though we need to make some structural changes to Uno, which in many ways can align with how .NET 5.0 will allow for packaging.

At this point, the closest would be an abstraction based on Skia, which is already available on many platforms.

I'll reference this issue in an larger epic.

**Comment by greatawesome** [comment]
Will Uno Platform 3.0 take care of this scenario? What sort of restrictions might be run into as far as device support goes?

**Comment by jeromelaban** [comment]
Linux support is already part of the dev branch of Uno. As far as restrictions, it's not clear yet, but it's at least tied to the platforms supported by Skia/SkiaSharp and .NET Core 3.1/5.

You can give it a try with: https://github.com/unoplatform/uno/blob/master/doc/articles/get-started-with-linux.md

**Comment by francoistanguay** [comment]
Closing this issue now that 3.0 is announced. Hope you'll give our Linux Preview Support a try and provide feedback!
