### ISSUE TITLE
Bad issue url

### ISSUE THREAD

**Issue by urodolf** [unoplatform/uno#2325]
Recently I created an issue on GitHub by following the steps in the URL:
https://github.com/unoplatform/Uno.Xamarin.Forms.Platform
At the bottom of the URL is a link to create the issues that directs you to:
https://github.com/xamarin/Xamarin.Forms/issues
As Jerome Laban comments, the issues should be created in:
https://github.com/unoplatform/uno/issues/new/choose

**Comment by jeromelaban** [comment]
Thanks for reporting this!
