### ISSUE TITLE
Uno platform fails in Xamarin.forms solution 

### ISSUE THREAD

**Issue by urodolf** [unoplatform/uno#2326]
Creating a new project of Uno Platform into a Xamarin Forms solution following the steps of the url
https://github.com/unoplatform/Uno.Xamarin.Forms.Platform

The UWP platform runs correctly but it cannot compile the Wasm project.
First there is an error from a ILoggerFactory because it does not implement the AddConsole(LogLevel.Trace), then I downgrade the package Microsoft.Extensions.Logging.Console to version 2.2.0.
Now the error is in the Linker beacuse failed to resolve Xamarin.Forms.Platform.UWP.CarouselViewRenderer

## Steps to Reproduce

1. Creates a Xamarin.Forms solution.
2. Add Uno platform project.
3. Update all nuget references to the last version.
4. Downgrade the nuget of Microsoft.Extensions.Logging.Console to version 2.2.0.

## Basic Information
- Xamarin:
    Xamarin.Forms Version 4.4.0.991220-pre3
    Xamarin Essentials Version 1.3.1
- Platform Target Frameworks: 
  - Uno Platform:
     Uno.WasmBootstrap version 1.1.0-dev.391
     Uno.Wasm.Bootstrap.Cli version 1.0.0-dev.302
     Uno.Xamarin.Forms.Platform version 4.3.0-uno.141
     Uno.UI versin 2.1.0-dev.192
     Microsoft.Extensions.Logging.Filter version 1.1.2
     Microsoft.Extensions.Logging.Console version 2.20
- UWP Platform:
    Microsoft.NetCore.UniversalWindowsPlatform version 6.2.9
    TargetPlatformVersion = TargetPlatformMinVersion = 10.0.16299.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

**Comment by jeromelaban** [comment]
@urodolf thanks for reporting this issue.

A few things:
- Xamarin.Forms 4.4 is not yet supported, you may need to downgrade to 4.3.
- The bootstrapper 1.1-dev is not in stable condition yet, use 1.0.10
- `Microsoft.Extensions.Logging.Console` needs to be downgraded to 1.1.1 (the only version that does not make implicit use of threads, which is not yet compatible with mono for WebAssembly)

You mentioned in the other issue that there was a linker issue. After changing the above packages, could you try rebuilding the application using the `detailed` logging level in visual studio ?

**Comment by urodolf** [comment]
When I compile with verbosity to Minimal the error was into the linker: 
 - System.Exception: Failed to execute the linker
 - Uno.Wasm.Bootstrap\ShellTask.cs line 530
 - Uno.Wasm.Bootstrap\ShellTask.cs line 148
When  I put the verbosity to Diagnostic in addition to the previous error another appears into Mono:
 - Fatal error in Mono CIL Linker
 - Mono.Linker.MarkException: Error processing method: 'System.Void Xamarin.Forms.Paltform.UWP.CarouselViewRenderer::OnElementPropertyChanged (System.Object, System.ComponentModel.PropertyChangedEventArgs)' in assembly: 'Xamarin.forms.Platform.Uno.dll' ---> MonoCecil.ResolutionException: Failed to resolve Xamrin.Forms.BindableProperty Xamarin.Forms.CarouselView::NumberOfSideItemsProperty

**Comment by urodolf** [comment]
Thanks for all.
When I change the version and I build the project I tell you the results.

**Comment by urodolf** [comment]
I downgrade:
- Xamarin.Forms to version 4.3.0.991250.
- Uno.Wasm.Bootstrap to version 1.0.10
- Microsoft.Extensions.Logging.Console to version 1.1.1

Now open a browser windows the Uno platform logo appears, then the Xamarin logo appears, which is what you see when you run the UWP project and does not continue, it stops there although the Visual Studio seems to respond correctly.

**Comment by jeromelaban** [comment]
@urodolf thank you for the update.

At this point, this seems like an issue at runtime. Do you see any logging message in the browser debugger window ?

**Comment by urodolf** [comment]
![image001](https://user-images.githubusercontent.com/50919329/71088544-f9570300-219e-11ea-847f-da34e0bb998b.png)

**Comment by jeromelaban** [comment]
Thanks! You'll need to change the `NavigationFailed` handler to show the proper exception content, in `OnNavigationFailed`.

**Comment by urodolf** [comment]
Thanks!
The exception message is "The type initializer for 'Registry' threw an exception."

**Comment by jeromelaban** [comment]
Would you have a more extensive stack trace ? `Registry` can come from many places.

**Comment by urodolf** [comment]
The stack trace of the exception:
at DryIoc.container..ctor (DryIoc.Rules rules, DryIoc.IScopeContext scopeContext) <0x35b4840 + 0x00018> in <877ffb82dc5345a4ba6a7dd486ec5c7>:0

**Comment by jeromelaban** [comment]
This explains. It could be a linker issue, could you try adding the DryIoc assemblies to the `LinkerConfig.xml` file ? Also, you may need to add other assemblies or projects from your solution.

**Comment by urodolf** [comment]
I add some assemblies in LinkerConfig.xml:

- DryIoc
- Dryioc.Microsoft.DependecyInjection
- Prism
- Prism.Forms
- Prism.DryIoc.Forms
- Xamarin.Forms.Core

Now all error desapear except one:
fail: Windows.UI.Xaml.UIElement[0]
The member event PointerEventHandler UIElement.PointerWheelChanged is not implemented in Uno.

**Comment by jeromelaban** [comment]
If there are no more exceptions, this means that there's another exception happening that is hidden, or not displayed. Maybe enabling tracing in one of those libraries may help. 

Trying to reduce the code that is executed may help finding what's working and what's not.

**Comment by urodolf** [comment]
After test different forms and projects I open two different issues more especifis for the problems I have found:
https://github.com/unoplatform/uno/issues/2421
https://github.com/unoplatform/uno/issues/2422

**Comment by weitzhandler** [comment]
https://github.com/PrismLibrary/Prism/pull/2054

**Comment by babakmdi** [comment]
![image](https://user-images.githubusercontent.com/65450661/89568407-80dda900-d838-11ea-92ea-373e4121cb63.png)
 Hi, I Always Have This Errors, And I Did Not Know Why, I Cant Run A Project , Or Build

**Comment by francoistanguay** [comment]
Should be fixed with XF5 support. With upcoming MAUI, no more work will be put on XF/WASM
