### ISSUE TITLE
ItemsControl.Items doesn't reflect the correct items

### ISSUE THREAD

**Issue by SuperJMN** [unoplatform/uno#2346]
## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Should I close this issue ? :)

**Comment by SuperJMN** [comment]
Oops! I must have created it by mistake!
