### ISSUE TITLE
[iOS]TextBlock with extra spacing issue

### ISSUE THREAD

**Issue by XiaotianNetlift** [unoplatform/uno#2358]
# Current behavior
TextBlock has extra spacing at the bottom in some conditions (see repro step).

## Expected behavior
TextBlock only takes the space required.

## How to reproduce it (as minimally and precisely as possible)
[TextBlockSpacing169216.zip](https://github.com/unoplatform/uno/files/3979696/TextBlockSpacing169216.zip)
```xaml
<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="*" />
        <ColumnDefinition Width="*" />
    </Grid.ColumnDefinitions>
    <Grid.Resources>
        <DataTemplate x:Key="TextItemTemplate">
            <Border BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="{Binding}" TextWrapping="Wrap" />
            </Border>
        </DataTemplate>
    </Grid.Resources>
    
    <ScrollViewer Grid.Column="0">
        <!-- fail -->
        <Grid Margin="16">
            <ItemsControl ItemsSource="{Binding}" ItemTemplate="{StaticResource TextItemTemplate}" />
        </Grid>
    </ScrollViewer>
    <ScrollViewer Grid.Column="1">
        <!-- workaround: ok -->
        <Border Padding="16">
            <Grid>
                <ItemsControl ItemsSource="{Binding}" ItemTemplate="{StaticResource TextItemTemplate}" />
            </Grid>
        </Border>
    </ScrollViewer>
</Grid>
```
![image](https://user-images.githubusercontent.com/32882405/71108471-2a303b80-2191-11ea-9930-ae32ea763cb6.png)

## Environment
Nuget Package: Uno.UI
Package Version(s): 2.1.0-dev.333
Affected platform(s):
- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:
- [ ] ~~Resharper (version: )~~

## Anything else we need to know?
https://nventive.visualstudio.com/Umbrella/_workitems/edit/169216

**Comment by carldebilly** [comment]
Fixed.  Published as `Uno.UI` `v2.1.0-dev.628`: https://www.nuget.org/packages/Uno.UI/2.1.0-dev.628
