### ISSUE TITLE
TabView is not supported

### ISSUE THREAD

**Issue by SuperJMN** [unoplatform/uno#2371]
TabView from the Windows Community Toolkit is not supported in any platform (except UWP)

**Comment by jeromelaban** [comment]
The TabView should be working per recent modifications. Could you paste here what's not working ?

**Comment by FrancoisM** [comment]
I dont know if the correct term is to say that it is not supported but the end result is that if my only page is 

```
<controls:TabView>
        <controls:TabViewItem Header="Info">
            <TextBlock Text="Test"/>
        </controls:TabViewItem>
    </controls:TabView>
```

then for wasm, I get stuck at the launch screen.

I'm on `Uno.Microsoft.Toolkit.Uwp.UI.Controls` version 5.1.0-build.200.gf9c311b069.

I'd be happy to provide more details and help resolve that issue but I have no clue where to start looking as there is no error whatsoever that I can grab on to start investigating.

**Comment by FrancoisM** [comment]
I'm trying to fix TabView (from WCT not WinUI) for wasm.
So far here's what I found:

- RepeatButton style => breaks
- TabView_SizeChanged => breaks as ActualWidth is not supported yet
- ItemContainerGenerator.ItemsChanged += ItemContainerGenerator_ItemsChanged; => ItemContainerGenerator is not supported

**Comment by davidjohnoliver** [comment]
@FrancoisM 
 - `ActualWidth` is supported, but it may not be being set with the same timing on Uno as on UWP
 - As of... ooh about 5 mins ago, `RepeatButton` has been added with @jeromelaban 's PR https://github.com/unoplatform/uno/pull/2290, you might want to retest once the new NuGet package has been created :)
 - `ItemContainerGenerator` is indeed not supported yet

**Comment by FrancoisM** [comment]
Last issue found:
<VisualStateGroup x:Name="DragStates"> => breaks

I heven't looked into why yet.

I think I've reviewed it all.

**Comment by FrancoisM** [comment]
I don't know what `ItemsGenerator` is to be honest.
But for the usage of items not bounded and directly entered in xaml that [line](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/362d8194c0626411104d7655040aaf93298d4284/Microsoft.Toolkit.Uwp.UI.Controls/TabView/TabView.cs#L56):
`ItemContainerGenerator.ItemsChanged += ItemContainerGenerator_ItemsChanged;`
can be removed without any impacts.

**Comment by FrancoisM** [comment]
Also, I didn't figure out why yet but the Back/Forward buttons of the scrollviewer that displays tabs don't work.

**Comment by jeromelaban** [comment]
This is fixed in the latest dev bits of WCT.
