### ISSUE TITLE
[WASM] Can't debug WASM: Could not load Mono.WebAssembly.DebuggerProxy

### ISSUE THREAD

**Issue by chris-makaio** [unoplatform/uno#2372]
## Current behavior

When following the documented steps here
https://github.com/unoplatform/uno/blob/master/doc/articles/debugging-wasm.md/

starting the application will show:

> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:5000/_framework/debug/ws-proxy?browser=ws://localhost:9222/devtools/page/E702D91056F681074F7FE76A70F8914B
> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
>       An unhandled exception has occurred while executing the request.
> System.IO.FileNotFoundException: Could not load file or assembly 'Mono.WebAssembly.DebuggerProxy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

## Expected behavior

We should be able to debug the app in Chrome Canary

## How to reproduce it (as minimally and precisely as possible)

Apply the documented steps to the current QuickStart master

## Environment

Nuget Package:

Package Version(s):
```
    <PackageReference Include="Uno.UI" Version="2.0.512-beta.6" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="2.0.512-beta.6" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="1.0.10" />
    <DotNetCliToolReference Include="Uno.Wasm.Bootstrap.Cli" Version="1.0.8" />
```

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16..4.1)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by chris-makaio** [comment]
compiling the recent Uno.Wasm.Bootstrap and using it as a custom package solves this

**Comment by jeromelaban** [comment]
This is  indeed fixed in recent builds of the bootstrapper.

**Comment by jasonkolodziej** [comment]
@chris-makaio Hi there I am having the same issue when following the documented steps here
https://github.com/unoplatform/uno/blob/master/doc/articles/debugging-wasm.md/ (whether it's with Canary or normal chrome). Is there something else I should be looking at? I am quite stumped.

on:  **Microsoft Visual Studio (Windows) v16.8.4**

`UnoTemplate.Wasm.csproj`
```xml
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <MonoRuntimeDebuggerEnabled>true</MonoRuntimeDebuggerEnabled>
    <DefineConstants>$(DefineConstants);TRACE;DEBUG</DefineConstants>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
<!-- Omitted for brevity -->
  <ItemGroup>
    <!-- Note that for WebAssembly version 1.1.1 of the console logger required -->
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Filter" Version="1.1.1" />
    <PackageReference Include="Uno.UI.WebAssembly" Version="3.5.0-dev.182" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="3.5.0-dev.182" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="2.0.0-dev.148" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="2.0.0-dev.148" />
  </ItemGroup>
```
Output from `ASP.NET Core Web Server`
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 52.2203ms 200 application/javascript
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:53207/_framework/debug?url=http%3A%2F%2Flocalhost%3A53207%2F  
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 2288.1291ms 302 text/html
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:53207/_framework/debug/ws-proxy?browser=ws://localhost:9222/devtools/page/1094D0AA5418D2353BF33945202FB094  
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: Could not load file or assembly 'Mono.WebAssembly.DebuggerProxy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Mono.WebAssembly.DebuggerProxy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Uno.Wasm.Bootstrap.Cli.DebuggingProxy.DebuggerHostExtensions.DebugWebSocketProxyRequest(ILoggerFactory loggerFactory, HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Uno.Wasm.Bootstrap.Cli.DebuggingProxy.DebuggerHostExtensions.DebugWebSocketProxyRequest(ILoggerFactory loggerFactory, HttpContext context)
   at Uno.Wasm.Bootstrap.Cli.DebuggingProxy.DebuggerHostExtensions.<>c__DisplayClass0_0.<UseDebugHost>b__0(HttpContext context, Func`1 next) in D:\a\1\s\src\Uno.Wasm.Bootstrap.Cli\DebuggingProxy\DebugHostExtensions.cs:line 56
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.WebSockets.WebSocketMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 36.1841ms 500 text/plain
```

FYI: from the browser side when I type `Alt+Shft+D` the chrome dev tools pop up but says the websocket is disconnected.

**Comment by dSanchezKlages** [comment]
I get the same error when i put the following line in the launchsettings.json:

      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",

When i remove the line, the program starts without an error
