### ISSUE TITLE
BitmapImage.SetSource is inconsistent between platforms

### ISSUE THREAD

**Issue by SuperJMN** [unoplatform/uno#2377]
Giving this converter that converts `bytes[]` to a `BitmapImage()`

```
    public class ByteArrayToImageConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, string language)
        {
            if (!(value is byte[] bytes))
                return null;

            var image = new BitmapImage();

#if WINDOWS_UWP
            using (var stream = new InMemoryRandomAccessStream())
            {
              image.SetSource(stream);
              var s = stream.AsStreamForWrite();
              s.Write(bytes, 0, bytes.Length);
            }
#else
            using (Stream stream = new MemoryStream(bytes))
            {
                image.SetSource(stream);
            }
#endif
            return image;
        }

        public object ConvertBack(object value, Type targetType, object parameter, string language)
        {
            throw new NotImplementedException();
        }
    }
```

The WINDOWS_UWP part and the part for other platforms is **symmetric**. However, when trying in, for instance, Android, this code produces the following exception:

> **System.ObjectDisposedException:** : 'Can not access a closed Stream.'

As a workaround, the converter should be written as:

```
    public class ByteArrayToImageConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, string language)
        {
            if (!(value is byte[] bytes))
                return null;

            var image = new BitmapImage();

#if WINDOWS_UWP
            using (var stream = new InMemoryRandomAccessStream())
            {
              image.SetSource(stream);
              var s = stream.AsStreamForWrite();
              s.Write(bytes, 0, bytes.Length);
            }
#else
            Stream stream = new MemoryStream(bytes);
            image.SetSource(stream);
#endif
            return image;
        }

        public object ConvertBack(object value, Type targetType, object parameter, string language)
        {
            throw new NotImplementedException();
        }
    }
```

Please, notice that the #else part no longer encloses the stream in a `using` block, so the stream isn't disposed.

I don't know what are the implications of this, but I would like to point out that the stream should be disposed eventually. We need to ensure that the resources are freed properly.

I would like to put into consideration that this converter raises the concert of SetSource not behaving the same between platforms, not only in the abstractions used, but also regarding the life cycle of the underlying stream.

I personally think this should be improved.

**Comment by jeromelaban** [comment]
There are two issues here:
- The fact that SetSource can take a .NET Stream where the UWP one cannot. This is somehow temproary until Uno supports more of the `IRandomAccessStream` features.
- The fact that SetSource does not capture the stream right away. Indeed it is not, and that's definitely an issue.

For the second part, interetingly, `SetSourceAsync` is already creating a copy of the original stream:

https://github.com/unoplatform/uno/blob/8dcc6f2d3aa5d57fd3ee96efe5fe73855a45a0da/src/Uno.UI/UI/Xaml/Media/Imaging/BitmapSource.cs#L58-L76

This should be an easy fix.

**Comment by francoistanguay** [comment]
@TopperDEL  Do you need help completing the related PR?

**Comment by TopperDEL** [comment]
I just do not find the time, currently, to finish it. I would have to digg into the Unit-Tests for this. Would love to do it - but to be realistic I won't be able to finish it currently. Sorry for this!

**Comment by francoistanguay** [comment]
No worries, just wanted to make sure we weren't doing parallel efforts. Will check at some point if team can pick up on your PR. Thanks for all the work so far!

**Comment by jeromelaban** [comment]
Fixed in master.
