### ISSUE TITLE
MasterDetailsView fails on collapse with FocusManager.FindFirstFocusableElement not implemented

### ISSUE THREAD

**Issue by SuperJMN** [unoplatform/uno#2378]
## Current behavior

When the available space becomes less than minimum width, the `MasterDetailsView` hides the **master sidebar**. That's expected. However, in this scenario, a Exception is thrown when this happens.

## How to reproduce it (as minimally and precisely as possible)

1. Clone this repo's specific commit: https://github.com/SuperJMN-Zafiro/UnoDesigner/commit/b5e9dbfba1ede59ec729795b5ed34ac3ae06768c
2. Run **the Android head**.
4. Switch the emulator to portrait mode
3. Click on New document
4. Move the Slider (the gray vertical bar) to the left until the exception is thrown.
> DependencyObject FocusManager.FindFirstFocusableElement(DependencyObject searchScope) is not implemented in Uno.'

## Demo of the issue:

![Dr34GxNMGF](https://user-images.githubusercontent.com/3109851/71310224-d4b69180-2411-11ea-984b-abde132794a8.gif)

## Environment

Package Version(s):
Uno.UI 2.1.0-dev.384

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [X] Resharper (version: 2019.3.1)

**Comment by jeromelaban** [comment]
The source of the issue really is that `FocusManager.FindFirstFocusableElement` is not implemented. 

https://github.com/unoplatform/uno/blob/73028f53aa4483ca06d6abef1c9c63381b27527b/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Input/FocusManager.cs#L55-L58

I'll adjust the issue title

**Comment by jeromelaban** [comment]
It's most probably a similar implementation to 

https://github.com/unoplatform/uno/blob/8dcc6f2d3aa5d57fd3ee96efe5fe73855a45a0da/src/Uno.UI/UI/Xaml/Input/FocusManager.cs#L39
