### ISSUE TITLE
[Android] Letters in the textbox are trimmed from the bottom

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2396]
## Current behavior

Letters inside a textbox are trimmed from the bottom

## Expected behavior

Letters inside a textbox should be full and not trimmed

## How to reproduce it (as minimally and precisely as possible)

[TextBoxContentTrim.zip](https://github.com/unoplatform/uno/files/3999003/TextBoxContentTrim.zip)

## Environment

Nuget Package:
Uno.UI: 2.1.0-dev.408

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

The bottom part of letters like 'p' and 'j' are a little bit trimmed from the bottom in UWP and iOS, but in Android we can't differentiate between a 'g' and a 'q' .

**Comment by carlh98** [comment]
Framework work item:
https://dev.azure.com/nventive/Umbrella/_workitems/edit/170661

**Comment by carldebilly** [comment]
@carlh98 I run your sample on UWP and the test is trimmed in the same way... so it's more an evolution than a regression ;-).

The only problem is there's no vertical scrolling on Windows and there's one on Android.

## Android
This is the reported bug...
![image](https://user-images.githubusercontent.com/4174207/72281917-8445e480-3609-11ea-9511-07c73331bb25.png)

## Windows
![image](https://user-images.githubusercontent.com/4174207/72281930-91fb6a00-3609-11ea-9fda-f1e0b7e0a5e4.png)
Very similar to Android, except no vertical scrolling.

## iOS
![image](https://user-images.githubusercontent.com/4174207/72282062-df77d700-3609-11ea-9d1e-8bac7d1713a1.png)
No vertical scrolling like on Windows.

## Wasm
![image](https://user-images.githubusercontent.com/4174207/72282252-41384100-360a-11ea-84a9-2f872fb2cda4.png)
No clip + non-working scroll at the end (cropped for the view here)

**Comment by carldebilly** [comment]
Issue closed as it's not considered as a regression, more a platform-alignment.
