### ISSUE TITLE
[iOS][Android] The clear button does not appear when text is present

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2397]
## Current behavior

When you enter text in a TextBox, the clear button does not appear

## Expected behavior

When you enter text in a TextBox, the clear button is displayed

## How to reproduce it (as minimally and precisely as possible)

[TextBoxContentTrim.zip](https://github.com/unoplatform/uno/files/3999090/TextBoxContentTrim.zip)

## Environment

Nuget Package:
Uno.UI

Package Version(s):
2.1.0-dev.481

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carlh98** [comment]
Framework work item:
https://dev.azure.com/nventive/Umbrella/_workitems/edit/170666

**Comment by carldebilly** [comment]
It has not been tested yet, but the package [Uno.UI v`2.1.0-dev.1090`](https://www.nuget.org/packages/Uno.UI/2.1.0-dev.1090) contains fixes related to this issue and it should be tested again on this version.

**Comment by carlh98** [comment]
I've tested in Android and iOS, the fix is present in Uno.UI 2.1.0-dev.1113
