### ISSUE TITLE
ApplicationViewTitleBar.BackgroundColor support on WASM

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#2400]
## What would you like to be added:

ApplicationViewTitleBar.BackgroundColor support on WASM

## Why is this needed:

Theming app

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by carldebilly** [comment]
@MartinZikmund I think you can now close this, as it will be soon published as `Uno.UI v2.1.0-dev.486`
