### ISSUE TITLE
How to use EF Core to access a remote DB (behind a middle tier service like ASP.NET Core / WEB API 2 / OData)?

### ISSUE THREAD

**Issue by formalist** [unoplatform/uno#2405]
Hello, I know this is not the right place to make support requests, but I already [tried ](https://stackoverflow.com/questions/59438533/how-to-use-ef-core-to-access-a-remote-db-behind-a-middle-tier-service-like-asp) without success (until now) on StackOverflow, and since in my opinion this should interests many developers, and there is very little on the Internet about it (as far as I know), please let me try.

The problem is that with UNO you could have your code running in the UWP head of your app on a Windows PC, located on the internal company network, thus accessing a (let's say) SQL Server database 'directly', through the Microsoft.EntityFrameworkCore.SqlServer provider. 
AND the very same code could run also in the Android/iOS head on a mobile device, connected to a 4G network, then accessing the same DB through a middle tier service (like ASP.NET Web Api, OData, etc.).

The goal is to have the same Entity Framework code run unchanged in both scenarios, that is, something like:

```
using (var dbCtx = new ChristmasPartyDBContext())
{
  var newAttendee = new Attendee { FirstName = "John", LastName = "Smith" };
  dbCtx.Attendees.Add(newAttendee);
  dbCtx.SaveChanges();
}
```
it would be 'just' a matter of using a different Provider for the DB Context, depending on network 'position'.

In the many examples/scenarios available online, the two situations are always treated differently, with different code/approaches: in the middle-tier scenario, the code to access the DB is something like:

```
    HttpClient httpClient = CreateHttpClient(token);  
    HttpResponseMessage response = await httpClient.GetAsync(uri);  

    await HandleResponse(response);  
    string serialized = await response.Content.ReadAsStringAsync();  

    TResult result = await Task.Run(() =>   JsonConvert.DeserializeObject<TResult>(serialized, _serializerSettings));  
```

that is, making an HTTP request, reading the 'string' response, and de-serializing into objects. No EF Core.

As i was saying, the solution would lie in having an EF Core Database Provider for 'behind middle-tier DBs'. And, as matter of fact, it exists. I found [this:](http://cdn.cdata.com/help/RDE/ado/pg_efCoreConsoleApp.htm) it's an 'ADO.NET Provider for OData', it connects to OData services, and comes with an EF Core provider. The downside is that it's proprietary software, and it currently [costs](https://www.cdata.com/drivers/odata/order/ado/) between 799$/Year and 1999$/Year.

Any other free/more affordable solutions/ideas…?

**Comment by bartvdbilt** [comment]
@formalist this looks to me like an ovious thing to do which nobody has throught off. Very nice idea. For UNO this would be important also I guess in the case of WebAssembly deployments where there is no access to the local database either. I found this project on [DataTableOData](https://github.com/delradie/DataTableOData) which uses [DataTables](https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable?view=netframework-4.8). Since I am new to UNO no sure of this is supported. Would this work to your opinion?

**Comment by jeromelaban** [comment]
Looks like https://azure.microsoft.com/en-us/services/app-service/mobile/ could offer some sort of solution for you.

In any case, this is some type of infrastructure that Uno does not provide (as neither does UWP/WinRT), but we can make sure that Uno does not get in the way of such implementations either.

**Comment by formalist** [comment]
> I found this project on [DataTableOData](https://github.com/delradie/DataTableOData) which uses [DataTables](https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable?view=netframework-4.8).

It's interesting, but uses DataTables, that is, kind of 'old style' data access technology. But if it's suitable for you...

>  Since I am new to UNO no sure of this is supported. Would this work to your opinion?

...quoting @jeromelaban 's underlying words: "we can make sure that Uno does not get in the way" :-)

**Comment by formalist** [comment]
@jeromelaban thank for your answer,

 > Looks like https://azure.microsoft.com/en-us/services/app-service/mobile/ could offer some sort of solution for you.

I suppose you're referring to [Hybrid Connections](https://azure.microsoft.com/en-us/resources/videos/azure-app-service-with-hybrid-connections-to-on-premises-resources/), or other solutions that 'simulate' (or just provide) a VPN.  Well, it'll work, of course. From the app's point of view, you're always 'directly' connected to the DB, that is, always using Microsoft.EntityFrameworkCore.SqlServer (maybe only changing the connection string, depending on app's network location (intranet/internet)).

But it requires an Azure subscription, and maybe you are just required to access existing Web Apis like those Visual Studio can easily generate/scaffold to allow basic CRUD operations on a database table ([see here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)). And since this is a common scenario, I though it could've been kind of straightforward (for Microsoft, at least) to provide an EF Provider for those somewhat 'standard' CRUD Web Apis... 

> In any case, this is some type of infrastructure that Uno does not provide (as neither does UWP/WinRT)

Of course, and I don't expect that :-) I'm asking here only because this issue could be(come) common among Uno's (but not only) users. Again, I'm kind of surprised that seemingly no one raised this issue so far... (and not just among Uno's users)

> but we can make sure that Uno does not get in the way of such implementations either.

Highly appreciated :-) (and let me take the opportunity to thank you for all your amazing work, and to wish you a happy new year)

**Comment by jeromelaban** [comment]
@formalist Thank you, and happy new year to you as well.

**Comment by francoistanguay** [comment]
Unrelated to Uno specifically. If you need more guidance, feel free to reach out on Discord or open an Uno-realted issue.
