### ISSUE TITLE
[Wasm][TextBox] IsReadonly does not work properly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2408]
## Current behavior

Using TextBox.IsReadonly does not set the native element as readonly, even if:
https://github.com/unoplatform/uno/blob/a95e800500f907cda03847403672c26bd7b005b3/src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.wasm.cs#L85-L98

is there to do so. This also means that this UI Test is not validating this property in all scenarios:

https://github.com/unoplatform/uno/blob/a95e800500f907cda03847403672c26bd7b005b3/src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs#L131

## Expected behavior

The TextBox is readonly when requested.

## Environment

Nuget Package: 2.1-dev

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
Fixed
