### ISSUE TITLE
ApplicationDataContainer Class methods are not implemented

### ISSUE THREAD

**Issue by avikeid2007** [unoplatform/uno#2414]
## Current behavior

Throwing exception=>"The member ApplicationDataContainer ApplicationDataContainer.CreateContainer(string name, ApplicationDataCreateDisposition disposition) is not implemented in Uno".

## Expected behavior

The methods and properties of this class support creating, deleting, enumerating, and traversing the container hierarchy.

## How to reproduce it (as minimally and precisely as possible)
[ApplicationDataContainer ](https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdatacontainer) Class methods are not implemented
https://github.com/unoplatform/uno/blob/master/src/Uno.UWP/Generated/3.0.0.0/Windows.Storage/ApplicationDataContainer.cs

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
I will take a look at this

**Comment by jeromelaban** [comment]
@avikeid2007 `ApplicationDataContainer` is mostly used through `ApplicationData`: 

https://github.com/unoplatform/uno/blob/6927750e398683a01db98d97061ff0413467c1ed/src/Uno.UWP/Storage/ApplicationData.cs#L13-L19

What do you need those APIs for ?

**Comment by MartinZikmund** [comment]
I think the API allows creating "sub-groups" of related settings, or at least that is how I used it sometime in the past.

**Comment by avikeid2007** [comment]
> RoamingSettings

**Comment by avikeid2007** [comment]
> @avikeid2007 `ApplicationDataContainer` is mostly used through `ApplicationData`:
> 
> https://github.com/unoplatform/uno/blob/6927750e398683a01db98d97061ff0413467c1ed/src/Uno.UWP/Storage/ApplicationData.cs#L13-L19
> 
> What do you need those APIs for ?

@jeromelaban Want to persist small amount of data at [UWP],[Android] &[WASM]. UWP works fine but need to do same with Android & WASM. I do not want to use any in-memory database. 
[https://github.com/avikeid2007/oClock/blob/dev/oClock/oClock.Shared/ViewModels/ClockViewModel.cs](https://github.com/avikeid2007/oClock/blob/dev/oClock/oClock.Shared/ViewModels/ClockViewModel.cs)

**Comment by jeromelaban** [comment]
@avikeid2007 thanks. Going through `Windows.Storage.ApplicationData.Current.LocalSettings` should be enough for this, you should not be needing to create an additional container for that.

You should be able to use it directly here:  https://github.com/avikeid2007/oClock/blob/f97e5236293a60f0ac91d298836a2ac546c8663b/oClock/oClock.Shared/ViewModels/ClockViewModel.cs#L121

What does the LocalSettingsHelper do ?

**Comment by avikeid2007** [comment]
> @avikeid2007 thanks. Going through `Windows.Storage.ApplicationData.Current.LocalSettings` should be enough for this, you should not be needing to create an additional container for that.
> 
> You should be able to use it directly here: https://github.com/avikeid2007/oClock/blob/f97e5236293a60f0ac91d298836a2ac546c8663b/oClock/oClock.Shared/ViewModels/ClockViewModel.cs#L121
> 
> What does the LocalSettingsHelper do ?
> 
> > <img alt="" width="48" src="https://avatars2.githubusercontent.com/u/11132795?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[avikeid2007/oClock](https://github.com/avikeid2007/oClock)**Uno Clock Application. Contribute to avikeid2007/oClock development by creating an account on GitHub.

@jeromelaban Thanks for reply. I am doing same in LocalSettingsHelper as you suggest. In Android App, when i am going get or set Containers value, it is throwing exception "The member IReadOnlyDictionary<string, ApplicationDataContainer> ApplicationDataContainer.Containers is not implemented in Uno."  at here:
[https://github.com/avikeid2007/oClock/blob/avnish/AddApplicationData/oClock/oClock.Shared/ViewModels/ClockViewModel.cs#L86](https://github.com/avikeid2007/oClock/blob/avnish/AddApplicationData/oClock/oClock.Shared/ViewModels/ClockViewModel.cs#L86)

LocalSettingsHelper :-
[https://github.com/avikeid2007/oClock/blob/avnish/AddApplicationData/oClock/oClock.Shared/Helpers/LocalSettingsHelper.cs#L17](https://github.com/avikeid2007/oClock/blob/avnish/AddApplicationData/oClock/oClock.Shared/Helpers/LocalSettingsHelper.cs#L17)

**Comment by jeromelaban** [comment]
This is what is supposed to be working: 

https://github.com/unoplatform/uno/blob/2a143fd479271cbf3f93ddd0e30cec871028b23a/src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs#L852

Does your help do something similar?

**Comment by avikeid2007** [comment]
@jeromelaban  Thanks for your support. Working fine for me.
