### ISSUE TITLE
Xamarin with Custom Controls in uno Platform

### ISSUE THREAD

**Issue by urodolf** [unoplatform/uno#2422]
A project has been created that contains 3 forms to test the behavior of Uno platform with Xamarin.
A form (Form2) contains a label and works correctly.
Another form (Form3) contains an entry, a button and a label. The button event takes the contents of the entry and shows it on the label and it works correctly.
The last form (Form1) contains a custom control that contains an entry and a button that, when pressed, the contents of the Entry are published in an ExitText property and the form contains a Label that shows the value returned by the custom control. This form works correctly in the UWP project but when running on Uno platform the entry value is not obtained correctly and the empty label is displayed.

Package Version(s):
- Xamarin: 
  - Xamarin.Forms Version 4.3.0.991250.
  - Xamarin Essentials Version 1.3.1
- Platform Target Frameworks: 
  - Uno Platform: 
    - Uno.WasmBootstrap version 1.0.10
    - Uno.Wasm.Bootstrap.Cli version 1.0.0-dev.302
    - Uno.Xamarin.Forms.Platform version 4.3.0-uno.141
    - Uno.UI versin 2.1.0-dev.192
    - Microsoft.Extensions.Logging.Filter version 1.1.2
    - Microsoft.Extensions.Logging.Console version 1.1.1
- UWP Platform: 
  - Microsoft.NetCore.UniversalWindowsPlatform version 6.2.9
  - TargetPlatformVersion = TargetPlatformMinVersion = 10.0.16299.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.2)
- [ ] for Mac (version: )

**Comment by jeromelaban** [comment]
Thanks for the report! Could you create a sample application from the default Xamarin.Forms templates to reproduce the issue, and attach it to this issue ?

Thanks!

**Comment by Suriman** [comment]
Hi, I'm a colleague of @urodolf. The sample that reproduces the issue is here. Thanks!
[Main2.zip](https://github.com/unoplatform/uno/files/4019562/Main2.zip)

**Comment by urodolf** [comment]
The difference in the execution between UWP and Uno platform can be seen in the attached images, since the traces should show the data in the same way but as observed when using a custom control, the value entered in the Entry is not obtained.
![Uno_Form1](https://user-images.githubusercontent.com/50919329/71732786-6bd70c80-2e48-11ea-9d9b-ed066e698d30.PNG)
![Uno_Form3](https://user-images.githubusercontent.com/50919329/71732787-6bd70c80-2e48-11ea-9b9e-6048bbae028d.PNG)
To change the used form you must change the line 18 in the file app.xaml.cs in the project AlternativeMain.

**Comment by Suriman** [comment]
@francoistanguay We appreciate the sincerity in this matter. Microsoft does not intend to give web support to XF or .NET MAUI (the support through Blazor is not valid because it requires the use of HTML and CSS), therefore, companies that want to continue using XAML and C # only for development in desktop and web, we are clear that the way to follow is UNO Platform. The big difference and the strong point of UNO Platform in front of .NET MAUI is the support to WASM. Please keep this strategy going in the future.

**Comment by francoistanguay** [comment]
For sure! This is exactly our point. XF WASM Renderers was an experiment and all of our users preferred to port their code to Uno (pretty straightforward) instead of having the extra level of indirection with XF -> UWP -> Uno -> WASM.

Let us know if you need help with your Uno endeavours!
