### ISSUE TITLE
RightTapped event

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#2423]
## What would you like to be added:

Support the `RightTapped` event.

## Why is this needed:

So that [@fonssonnemans can build Uno Minesweeper ](https://twitter.com/fonssonnemans/status/1213088076379164672?s=20)😉 . 

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by carldebilly** [comment]
Would be nice for https://github.com/unoplatform/uno/issues/2031

**Comment by jeromelaban** [comment]
Right Tapped is a tricky one. It's an easy one for Wasm, but not so much for iOS and Android. Should this be mapped to a long press ?

**Comment by pkar70** [comment]
I think for Android it is very simple. Yes, long press should be used.
For macOS, it should be easy also (guessing from https://www.imore.com/how-change-mouse-settings-your-mac , which mention right click).

**Comment by MartinZikmund** [comment]
I think long press is the equivalent on Android. iOS preferred force touch for similar actions, but now force touch seems to be going away so... Tap and hold it is. It also matches the behavior on UWP touch.

**Comment by dr1rrb** [comment]
Actually it's pretty easy to build as we already have the `IsRightButtonPressed` info when supported by the platform, i.e. [Android](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.Android.cs#L122) and [WASM](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.wasm.cs#L114). 

I also agree that we have to map it to a long press ... as it's the UWP behavior: [_"RightTapped for a touch action results from processing an action that remains in one place for a certain amount of time"_](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.righttapped)

For iOS indeed we also should probably link it to the "force touch", but I would however make it configurable through a feature flag.

**Comment by dr1rrb** [comment]
BTW, linked to this event it would be nice to also implement this: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.holding 

But this is probably a bit more tricky to get, especially with a mouse where we might not get any "pointer move" while holding (which means that we probably cannot just rely on a bunch of move to detect when we reached the delay, but instead we will have to start a timer, handle it's cancellation, validate the perf impact, etc.)

**Comment by dr1rrb** [comment]
FYI, I did it this afternoon while waiting for my build, I'll merge it soon
