### ISSUE TITLE
SkiaSharpTest.Wasm stalls at launch

### ISSUE THREAD

**Issue by baskren** [unoplatform/uno#2428]
## Description 

Trying to learn about using Uno.SkiaSharp.Views in a Uno.Wasm app.  Cloned Uno.Samples repo and opened the UI/SkiaSharpTest/SkiaSharpTest.sln in VisualStudio 2019 (environment information provided, below).  Successfully build and ran Android and UWP platform versions. Successfully built Wasm platform version.  When going to run Wasm platform version (either w/ or w/o debugging), the app freezes.  Platform differences noted in Observed Behavior

## Expected Behavior

App completes splash screen and displays "Skia Sharp" label in the center of the window with a yellow background.

## Observed Behavior

Console errors shown below for their respective browsers

### Microsoft Edge 44.18362.449.0

App freezes at UNO Splash Screen

```
0: Imported WebAssembly.Table initial size (4096) is smaller than declared (8192)   mono.js (1,10139)
```

### Chrome Version 79.0.3945.88 (Official Build) (64-bit)

- Paused in debugger popup appears 
- clicking CONTINUE arrow once causes UNO Splash screen to disappear and the below error to appear in the browser's console:

```
uno-bootstrap.js:163 Error: System.ArgumentException: An item with the same key has already been added. Key: Windows.UI.Xaml.Data
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (:54185/TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x0015a] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:572 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (:54185/TKey key, TValue value) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:240 
  at Microsoft.Extensions.Logging.FilterLoggerSettings.Add (:54185/System.String categoryName, Microsoft.Extensions.Logging.LogLevel logLevel) <0x2cb0bd8 + 0x0001c> in <d0a6beabffb24cf1bec19ccd5e89f63a>:0 
  at SkiaSharpTest.Wasm.Program.ConfigureFilters (:54185/Microsoft.Extensions.Logging.ILoggerFactory factory) [0x00001] in C:\Users\ben\Development\Uno\Uno.Samples\UI\SkiaSharpTest\SkiaSharpTest\SkiaSharpTest.Wasm\Program.cs:28 
  at SkiaSharpTest.Wasm.Program.Main (:54185/System.String[] args) [0x00001] in C:\Users\ben\Development\Uno\Uno.Samples\UI\SkiaSharpTest\SkiaSharpTest\SkiaSharpTest.Wasm\Program.cs:21 
    at Object.call_method (mono.js:1)
    at Object.call_static_method (mono.js:1)
    at Object.mainInit (uno-bootstrap.js:160)
    at checkDone (uno-bootstrap.js:371)
    at processDependency (uno-bootstrap.js:396)
    at Object.execCb (require.js:5)
    at e.check (require.js:5)
    at e.<anonymous> (require.js:5)
    at require.js:5
    at require.js:5
```

## Packages

Tried with both the default NuGet packages in the repo as well as with the following upgrades:

 - Uno.UI v2.0.528
 - Uno.Wasm.Bootstrap v1.0.10

## Environment

Microsoft Visual Studio Enterprise 2019
Version 16.4.2
VisualStudio.16.Release/16.4.2+29613.14
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA022
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.4.457.38025
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.4.457.38025
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.4.457.38025
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.4.457.38025
Azure Functions and Web Jobs Tools

C# Tools   3.4.1-beta4-19610-02+c4e5d138903b899477649a17f197abd2bcb22f9e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CleanBinAndObjCommand Extension   1.1.0
CleanBinAndObjCommand Visual Studio Extension Detailed Info

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JoinLines Extension   1.0
JoinLines Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.21016.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.87+gbb515bf382
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.5.24 (1fafd7e)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61912.09160
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.11031.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.4.1-beta4-19610-02+c4e5d138903b899477649a17f197abd2bcb22f9e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.4.0-beta.19556.5+e7597deb7042710a7142bdccabd6f92b0840d354
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.4.000.307 (d16-4@e031886)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.4.0.464 (remotes/origin/d16-4@4abf337c3)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.4.25 (579ee62)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.1.1.0 (d16-4/f2c9364)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: bef1e63
    Java.Interop: xamarin/java.interop/d16-4@c4e569f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK   13.8.3.0 (0d8fe21)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by baskren** [comment]
For the sake of development, Edge beta is acceptable.  Since the planned release date is Jan 15, 2020, this isn't show stopper.

 Is there a place where quirks like this are cataloged?  It's likely I missed it and It would have been a huge time saver (1.5 days) if I had known.

**Comment by jeromelaban** [comment]
There are not many issues with the old Edge, but we're not cataloging those much.

The one you reported is new, for sure. Yet as a general rule, testing on multiple browsers when an invalid behavior is happening is a good troubleshooting technique.
