### ISSUE TITLE
[iOS] Invalid clipping during animations

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2441]
##  Current behavior

Clipping on animated elements may be incorrectly applied or removed when the animation finishes

## Expected behavior

Proper clipping is applied.

## How to reproduce it (as minimally and precisely as possible)

~~https://dev.azure.com/nventive/Umbrella/_workitems/edit/171047~~
https://dev.azure.com/nventive/Umbrella/_workitems/edit/176701

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

https://nventive.visualstudio.com/Umbrella/_workitems/edit/171047
https://dev.azure.com/nventive/Umbrella/_workitems/edit/176701

**Comment by dr1rrb** [comment]
This is probably linked to https://github.com/unoplatform/uno/issues/2542 
Assigning @carldebilly in order to validate/invalidate
