### ISSUE TITLE
502.5 Bad gateway error running basic wasm app

### ISSUE THREAD

**Issue by bzuillsmith** [unoplatform/uno#2463]
## Current behavior
 IIS attempts to run the wasm project and gets a 502.5 error
I followed the instructions for getting started with Uno and I can run the UWP app, but not the WASM app.
## Expected behavior

Should run fine

## How to reproduce it (as minimally and precisely as possible)

I simply am using the project template

## Environment

Nuget Package:
The template came with the following
`Uno.UI 2.0.530`
`Uno.UI.Remote 2.0.530`
`Uno.Wasm.Bootstrap 1.0.10`

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [x] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

I'm not an expert with IIS but I am able to run a basic Web application from the VS templates without any issue.

.NET Core 2.2.8 is installed

**Comment by jeromelaban** [comment]
Thank you for opening this issue.

A few things:
- Can you provide a screenshot of the 502 error ? 
- Also, when running the application, in the "run application" instead of "IIS Express" can you try selecting `YourApp..Wasm` instead and tell us what you see in the console window ?

**Comment by bzuillsmith** [comment]
![image](https://user-images.githubusercontent.com/1412248/72207940-14412e00-3452-11ea-8a27-e0c680cf93bf.png)

Not totally sure I know what you mean about the "run application". But the ASP.NET Core Server output shows multiple lines of
`App1.Wasm> Version for package `Uno.Wasm.Bootstrap.Cli` could not be resolved.`

The Build output before running shows

    1>------ Build started: Project: App1.Wasm, Configuration: Debug Any CPU ------
    1>C:\Users\bzuil\source\repos\App1\App1\App1.Shared\App.xaml.cs(62,21,62,45): warning
Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PreviousExecutionState is not implemented in Uno
    1>C:\Users\bzuil\source\repos\App1\App1\App1.Shared\App.xaml.cs(71,17,71,37): warning 
Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PrelaunchActivated is not implemented in Uno
    1>C:\Users\bzuil\source\repos\App1\App1\App1.Shared\App.xaml.cs(104,28,104,61): warning Uno0001: Windows.ApplicationModel.SuspendingOperation.GetDeferral() is not implemented in Uno
    1>C:\Users\bzuil\source\repos\App1\App1\App1.Shared\App.xaml.cs(106,13,106,30): warning Uno0001: Windows.ApplicationModel.SuspendingDeferral.Complete() is not implemented in Uno
    1>App1.Wasm -> C:\Users\bzuil\source\repos\App1\App1\App1.Wasm\bin\Debug\netstandard2.0\App1.Wasm.dll
    1>Restore completed in 1.06 ms for C:\Users\bzuil\AppData\Local\Temp\mono-wasm-f5cfc67c8ed\packager_build\packager2.csproj.
    1>packager2 -> C:\Users\bzuil\AppData\Local\Temp\mono-wasm-f5cfc67c8ed\packager2.exe
    1>Done building project "App1.Wasm.csproj".
    ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
    ========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by jeromelaban** [comment]
Thank you. This is generally caused by some .NET Core versions mismatches with Visual Studio, but we're still chasing the reason for this to happen.

When I say run the application, I'm talking about:

![image](https://user-images.githubusercontent.com/5839577/72210705-7c613580-348d-11ea-8954-39542ef875da.png)

Instead of `IIS Express`, select the name of your application, then start the application.

**Comment by bzuillsmith** [comment]
Ok, will try that later today when I get back to it. How does it select the .net core version to use? I don't think I have anything higher than 2.2.8 installed. Had 2.1 previously

**Comment by jeromelaban** [comment]
About the version selection, that part is unclear, and in some cases, having another VS version installed alters the behavior of the first instance of VS.

**Comment by bzuillsmith** [comment]
Ah yes, I see now that I have .NET 3.1 installed but missed it the first time around. Running the project directly shows it is loading 3.1 DLLs.  I guess I need to figure out how to force it to 2.2

**Comment by bzuillsmith** [comment]
Ok, I may have figured out how to target the correct .net core version with a `global.json`. Now I've got another problem. It says it requires MS Build 16 and VS 2017 runs on MS Build 15. I was under the impression that Uno doesn't have full support on VS 2019 because the extensions don't show up for me on there:
![image](https://user-images.githubusercontent.com/1412248/72215647-7e95b500-34ca-11ea-8876-7b949222893e.png)
Also the first getting started page page says that Uno requires VS 2017 15.5+ but there is no mention of the requirements for Wasm.

Based on the above,
1) Are there extensions for VS2019? Where do I download them?
2) I think a special note should be added for Wasm on that page that there are higher requirements
3) I'm late the the .NET Core game because I often work in WPF and legacy code, but a mention of the global.json to target .NET Core 2.2 when 3.0 is installed might be nice. I'm not totally sure this is the solution since I haven't gotten it running yet, but I assume it is.

**Comment by bzuillsmith** [comment]
Ok got it working in VS 2019 with a global.json and after installing the extension manually (downloaded via the web).

Extensions were found via the web browser without an issue [here](https://marketplace.visualstudio.com/search?term=uno&target=VS&category=Tools&vsVersion=&subCategory=All&sortBy=Relevance). Must be a VS 2019 bug. 

Maybe just take a look at suggestions 2 and 3 in my last post and then feel free to close.

**Comment by jeromelaban** [comment]
Thanks for the update.

- About the extension, it is compatible with vs2019, and for some odd reason the search in "Manage extensions" does not work. Will have to follow-up on that during the week. You downloaded it [from the proper place](https://marketplace.visualstudio.com/items?itemName=nventivecorp.uno-platform-addin).
- About `global.json` it is not clear if specifying a version there impacts IIS Express as well, but if that works in your case, it can definitely be a way to alter the behavior. One of the reason we are not specifying that file is caused by the inability to specify a wildcard version, but this has been fixed and will be provided by https://github.com/dotnet/designs/pull/71.
