### ISSUE TITLE
[Android]When build an Android project, then a lot of errors are there on Error List 

### ISSUE THREAD

**Issue by runceel** [unoplatform/uno#2464]
## Current behavior

When build an Uno Project, there are a lot of errors on Error List:

![image](https://user-images.githubusercontent.com/79868/72212783-3906d580-3526-11ea-87b7-19950610fcb3.png)

All errors are from Resource.designer.cs of Android project.
But, even if the errors are, the app can be run and debug.

## Expected behavior

No errors.

## How to reproduce it (as minimally and precisely as possible)

1. Create an Uno Platform project on VS 2019
2. Select [Build] -> [Build Solution]

## Environment

Nuget Package:

Package Version(s):
2.0.530

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [x] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.2)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

I edited the Android project file to fix the errors:
1. Unload the Android project
2. Open the project file
3. Add following line to under the first PropertyGroup tag:
    ```xml
    <AndroidUseManagedDesignTimeResourceGenerator>False</AndroidUseManagedDesignTimeResourceGenerator>
    ```
4. Reload the project
5. Re-build the project

And related issue is reported on StackOverlow(This is a Xamarin issue):
https://stackoverflow.com/questions/50593906/ambiguous-reference-intellisense-error-from-resource-designer-cs

**Comment by jeromelaban** [comment]
Thanks for the report. Indeed, this would be an easy change in the templates.
