### ISSUE TITLE
Allow Style.BasedOn to be set to {x:Null}

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#2470]
## Current behavior
if I declare a style as 
```xml
 <Style x:Key="MaterialDesignRaisedButton" TargetType="Button" BasedOn="{x:Null}">
```
the solution fails to compile because it generates this code:
```csharp
 public static global::Windows.UI.Xaml.Style MaterialDesignRaisedButton
        {
            get
            {
                if(!_MaterialDesignRaisedButtonInitialized)
                {
                    __MaterialDesignRaisedButtonBackingField = 
                        new global::Windows.UI.Xaml.Style(typeof(global::Windows.UI.Xaml.Controls.Button))
                        {
                            BasedOn = (global::Windows.UI.Xaml.Style)#Error // NullExtension could not be found.,
                            Setters = 
                            {
                            }
                        }
                        ;
                    _MaterialDesignRaisedButtonInitialized = true;
                }
                return __MaterialDesignRaisedButtonBackingField;
            }
        }
```
## Expected behavior
I'm not sure if setting BasedOn to null is equivalent to not generate the setting code at all. What I'm sure is that it should compile.

## Environment
Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

**Comment by davidjohnoliver** [comment]
Guidance for contributors: this one will involve making modifications to the [XamlFileGenerator](https://github.com/unoplatform/uno/blob/master/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs) class. You can enable [debugging ](https://github.com/unoplatform/uno/blob/02e9e9552dbcd2810a2e845aec4f8fe8bbc6ab68/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs#L95)and [source-method annotation](https://github.com/unoplatform/uno/blob/02e9e9552dbcd2810a2e845aec4f8fe8bbc6ab68/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs#L46) in the `XamlCodeGeneration` class.

Don't forget to [add a unit test](https://platform.uno/docs/articles/contributing/guidelines/creating-tests.html#net-framework-unit-tests-unouitests) in `Uno.UI.Tests`. :)

**Comment by kazo0** [comment]
Is this issue still a thing now that the Styles work that Jerome mentioned is done?

**Comment by davidjohnoliver** [comment]
@kazo0 It's probably still happening, it most likely requires a special case for the Xaml generation that was left out of the Styles work. But test it out in a blank app and see, maybe it works :)
