### ISSUE TITLE
Allow white spaces in the resource dictionary keys

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#2471]
## Current behavior
When I declare a style as
```xml
<Color x:Key="Blue GreyPrimary50">#eceff1</Color>
```
the uno project fails to compile the following generated code:
```
// Source ..\..\..\..\..\..\..\MainDemo.Uno.Shared\Themes\MaterialDesignColor.BlueGrey.Named.xaml (Line 3:4)
public static global::Windows.UI.Color Blue GreyPrimary50 { get; } = 
Windows.UI.ColorHelper.FromARGB(255, 236, 239, 241)        ;
```

## Expected behavior
resource dictionary keys should be able to contain white spaces, and the generated code should be able compile accordingly with some escape character as UWP does

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

**Comment by davidjohnoliver** [comment]
Thanks for the report!

This will _probably_ be fixed by https://github.com/unoplatform/uno/pull/1766, since resource entries are no longer converted to static properties (with attendant naming restrictions).

**Comment by davidjohnoliver** [comment]
I verified that this works properly with Uno 3.0. https://github.com/unoplatform/uno/commit/3e4d1aa4a63bb6e13078a4fd25c2d3f1b3086243
