### ISSUE TITLE
Xamarin.Forms Editor and Label not rendering correctly

### ISSUE THREAD

**Issue by chrisevans9629** [unoplatform/uno#2473]
## Current behavior
The Labels and Editor are not rendering correctly:
![image](https://user-images.githubusercontent.com/33850520/72272017-89953600-35ed-11ea-88b2-f2ec2ecc934f.png)
It looks like the editor is not filling to the parent control (left) and the labels are not respecting my newlines/returns.  My guess is that the labels are rendered as ```<p/>``` and not ```<pre>test</pre>```

## Expected behavior
This is what it should look like (UWP)
![image](https://user-images.githubusercontent.com/33850520/72272076-a7fb3180-35ed-11ea-974a-99ae57151b78.png)

## How to reproduce it (as minimally and precisely as possible)
Below is the xaml for the main page of my project that has the issue above
```xml
<ContentPage Title="Normal">
        <Grid Margin="10">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*"></ColumnDefinition>
                <ColumnDefinition Width="*"></ColumnDefinition>
            </Grid.ColumnDefinitions>
            <Grid.RowDefinitions>
                <RowDefinition Height="*"></RowDefinition>
                <RowDefinition Height="*"></RowDefinition>
                <RowDefinition Height="Auto"></RowDefinition>
            </Grid.RowDefinitions>
            <Editor Grid.Column="0" Grid.RowSpan="2" Text="{Binding Code}"/>
            <ScrollView Grid.Column="1" Grid.Row="0">
                <Label  Text="{Binding Xaml}"/>
            </ScrollView>
            <ScrollView Grid.Column="1" Grid.Row="1">
                <Label Text="{Binding CSharp}"/>
            </ScrollView>
            <Label Grid.Column="0" Grid.ColumnSpan="2" Grid.Row="2" TextColor="Red" Text="{Binding Error}"/>
        </Grid>

    </ContentPage>
```
You can see a sample of the error here:
https://github.com/chrisevans9629/Evans.XamlTemplates/tree/updateXamarinForms

You should be able to just run the Wasm project

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.2)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by francoistanguay** [comment]
No plans to work on this at this point unfortunately.
