### ISSUE TITLE
Selected Item Color doesn't change back to default

### ISSUE THREAD

**Issue by chrisevans9629** [unoplatform/uno#2475]
## Current behavior
![unoex2](https://user-images.githubusercontent.com/33850520/72275959-95d0c180-35f4-11ea-8832-51d3ef2c21e0.gif)

## Expected behavior
![unoex](https://user-images.githubusercontent.com/33850520/72275986-9f5a2980-35f4-11ea-83bc-4387d65c9b75.gif)

## How to reproduce it (as minimally and precisely as possible)
1. Create a new xamarin.forms project
2. Selected Tabbed Page
3. Add wasm project
4. Run

I created a sample here:
https://github.com/chrisevans9629/UnoTest
## Environment

Nuget Package:
```xml
<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Filter" Version="1.1.1" />
		<PackageReference Include="Uno.Xamarin.Forms.Platform" Version="4.3.4" />
		<PackageReference Include="Uno.Wasm.Bootstrap" Version="1.0.10" />
		<DotNetCliToolReference Include="Uno.Wasm.Bootstrap.Cli" Version="1.0.0-dev.302" />
```
Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.2)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thank you for the report!

Could you try installing the latest dev `Uno.UI` nuget package and check if this issue is still present ?

Thanks!

**Comment by chrisevans9629** [comment]
I installed `<PackageReference Include="Uno.UI" Version="2.1.0-dev.679" />` and looks like the issue is still occurring
![issue](https://user-images.githubusercontent.com/33850520/72347462-e4866600-369d-11ea-9479-d678dc2d7d9b.gif)

**Comment by jeromelaban** [comment]
@chrisevans9629 thanks for the validation!

**Comment by chrisevans9629** [comment]
Happy to help! :smile:
