### ISSUE TITLE
[IOS, Wasm] Tests.FocusManager_FocusDirection UI Tests do not pass (for Left, Right and Previous and Next) for IOS and all for WASM(for Left, Right and Previous,Up,Down and Next)

### ISSUE THREAD

**Issue by manpreetkaurnventive** [unoplatform/uno#2476]
## Current behavior

All Tests.FocusManager_FocusDirection UI Tests do not pass (for Left, Right, Up, Down, Previous and Next) for Wasm.

## Expected behavior

All UI tests for Tests.FocusManager_FocusDirection should pass 

## How to reproduce it (as minimally and precisely as possible)

See the code here :
https://github.com/unoplatform/uno/blob/7c166c8d136e5e05c773812ea8e69e9ffad54d14/src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/FocusManagerDirectionTests/UnoSamples_Tests.FocusManagerDirection.cs

SamplesApp.UITests.Windows_UI_Xaml.FocusManagerDirectionTests.UnoSamples_Tests.FocusManager_FocusDirection_**Down**_Validation

SamplesApp.UITests.Windows_UI_Xaml.FocusManagerDirectionTests.UnoSamples_Tests.FocusManager_FocusDirection_**Left**_Validation

SamplesApp.UITests.Windows_UI_Xaml.FocusManagerDirectionTests.UnoSamples_Tests.FocusManager_FocusDirection_**Previous**_Validation

SamplesApp.UITests.Windows_UI_Xaml.FocusManagerDirectionTests.UnoSamples_Tests.FocusManager_FocusDirection_**Next**_Validation

SamplesApp.UITests.Windows_UI_Xaml.FocusManagerDirectionTests.UnoSamples_Tests.FocusManager_FocusDirection_**Up**_Validation

SamplesApp.UITests.Windows_UI_Xaml.FocusManagerDirectionTests.UnoSamples_Tests.FocusManager_FocusDirection_**Right**_Validation

## Environment

Nuget Package: 

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [X] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

**Comment by MartinZikmund** [comment]
Now passing everywhere 👍
