### ISSUE TITLE
[iOS] TextBlock.FontSize failed to inherit from parent element

### ISSUE THREAD

**Issue by Daoting** [unoplatform/uno#2487]
## Current behavior
If you do not set the `TextBlock.FontSize`, font size is always 11.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report! Could you create a sample that demonstrates this issue ? 

This line is the option that controls inheritance, so I'm a bit surprised that his does not work:
https://github.com/unoplatform/uno/blob/024eebddd33ac0dfa6b6d8ea0871d5c6effc9f12/src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs#L286

**Comment by Daoting** [comment]
I'm sorry, I was mistaken.
