### ISSUE TITLE
AutoMapper fails to load in WebAssembly

### ISSUE THREAD

**Issue by SuperJMN** [unoplatform/uno#2493]
I'm using AutoMapper in 2 of my projects. The problem is exclusive to WebAssembly.

## Current behavior

When loading the WASM head, this is shown in the browser console.

![image](https://user-images.githubusercontent.com/3109851/72555331-a4d99d00-389c-11ea-8df8-88072dd0f4b3.png)

Relevant line is here:
https://github.com/AutoMapper/AutoMapper/blob/8959bd4e8fe1538184e32e7e0ba29b0a3ce1fa82/src/AutoMapper/Mappers/EnumToEnumMapper.cs#L33

### Stack Trace

> System.Exception: Failed to load Globaleris.MainPage: System.TypeInitializationException: The type initializer for 'AutoMapper.Mappers.EnumToEnumMapper' threw an exception. ---> System.InvalidOperationException: Sequence contains no matching element
> mono.js:1   at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0000c] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/external/corefx/src/System.Linq/src/System/Linq/First.cs:27 
> mono.js:1   at AutoMapper.Mappers.EnumToEnumMapper..cctor () [0x00000] in C:\projects\automapper\src\AutoMapper\Mappers\EnumToEnumMapper.cs:33 
> mono.js:1    --- End of inner exception stack trace ---
> mono.js:1   at AutoMapper.Mappers.MapperRegistry.Mappers () [0x00000] in C:\projects\automapper\src\AutoMapper\Mappers\MapperRegistry.cs:16 
> mono.js:1   at AutoMapper.Configuration.MapperConfigurationExpression..ctor () [0x00049] in C:\projects\automapper\src\AutoMapper\Configuration\MapperConfigurationExpression.cs:18 
> mono.js:1   at AutoMapper.MapperConfiguration.Build (System.Action`1[T] configure) [0x00000] in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:286 
> mono.js:1   at AutoMapper.MapperConfiguration..ctor (System.Action`1[T] configure) [0x00000] in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:60 
> mono.js:1   at Globaleris.Composition..ctor () [0x0005d] in D:\Repos\SuperJMN\Globaleris\Globaleris\Globaleris.Shared\Infrastructure\Composition.cs:32

## Expected behavior

The application should start just right

## How to reproduce it (as minimally and precisely as possible)

I'll try to provide one later 😅

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [X] Resharper (version: 2019.3.1)

## Anything else we need to know?

We might ping @jbogard to ask him for help regarding AutoMapper in WASM.

**Comment by jeromelaban** [comment]
This definitely looks like a linker issue. To validate, can you try [disabling the linker](https://github.com/unoplatform/Uno.Wasm.Bootstrap#linker-configuration-1) ?

**Comment by SuperJMN** [comment]
Disabling the linker fixed the problem! 

`<WasmShellILLinkerEnabled>false</WasmShellILLinkerEnabled >`

and others as well. The Grace container also works like a charm. Thanks!

**Comment by jeromelaban** [comment]
Overall, knowing what to link out would be know would be necessary, as disabling the linker prevents the Wasm AOT from working.
