### ISSUE TITLE
WASM: Double Animation Stops After 1 or 2 iterations

### ISSUE THREAD

**Issue by MuzafarZargar** [unoplatform/uno#2498]
## Current behavior

I have created double animation with repeat behavior set to forever. 
Applied the animation to  Render Transform 
Attached Render Transform to textbox. 
The target move as expected but stops after one or two iterations  

## Expected behavior

The animation should move for ever as according to repeat behavior (it does so in UWP)

## How to reproduce it (as minimally and precisely as possible)

Create a single page with following XAML and Code Behind

## XAML
``` xml
<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition />
        </Grid.RowDefinitions>
        <TextBlock Text="Hello, world!" Margin="20" FontSize="30" 
                   x:Name="text"/>
        
        <Button VerticalAlignment="Center" HorizontalAlignment="Center"
                Content="Click ME" Grid.Row="1" Click="Button_Click">
        </Button>
    </Grid>
```
## Code Behind
``` csharp
            var ts = new TranslateTransform();
            text.RenderTransform = ts;
            var da = new DoubleAnimation();
            da.To = 500;
            da.RepeatBehavior = RepeatBehavior.Forever;
            da.Duration = TimeSpan.FromSeconds(5);
            Storyboard.SetTarget(da, ts);
            Storyboard.SetTargetProperty(da, "X");
            var sb = new Storyboard();
            sb.Children.Add(da);
            sb.Begin();
```
## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android // working flawlessly
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report !

@dr1rrb does it ring a bell ?

**Comment by dr1rrb** [comment]
Unfortunately no 😕
