### ISSUE TITLE
[Android] LinearGradientBrush needs starting point of 0

### ISSUE THREAD

**Issue by jcantin-nventive** [unoplatform/uno#2505]
## Current behavior

When the starting point is, for instance, (0.5, 0.5), the LinearGradientBrush goes in both directions even when it's meant to only go from the middle of the screen to the bottom.

![image](https://user-images.githubusercontent.com/43351943/72745296-6f270380-3b7d-11ea-8447-fa44db7d770d.png)

## Expected behavior

The LinearGradientBrush goes to the bottom when that's the direction it's given, as it does on UWP and iOS.

![image](https://user-images.githubusercontent.com/43351943/72744832-5538f100-3b7c-11ea-89da-61098b5c34ae.png)

## How to reproduce it (as minimally and precisely as possible)

```
<Grid>
		<Grid.Background>
			<LinearGradientBrush StartPoint="0.5,0.5"
								 EndPoint="0.5,1">
				<GradientStop Offset="0"
							  Color="Transparent" />
				<GradientStop Offset="1"
							  Color="Black" />
			</LinearGradientBrush>
		</Grid.Background>
	</Grid>
```

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.0.530 and 2.1.0-dev.769

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Workaround: Set the StartPoint at (0.5, 0) and add GradientStops as needed

**Comment by MatFillion** [comment]
Thank you for the report!

As a workaround for now you can add an extra `GradientStop `and `StartPoint `of the gradient at 0

```
<Grid>
	<Grid.Background>
		<LinearGradientBrush StartPoint=**"0.5,0"**
				 EndPoint="0.5,1">
			<GradientStop Offset="0"
				 Color="Transparent" />
                        <GradientStop Offset=**"0.5"**
				Color="Transparent" />
			<GradientStop Offset="1"
				 Color="Black" />
		</LinearGradientBrush>
	</Grid.Background>
</Grid>
```

**Comment by TonyHenrique** [comment]
I think I am observing a similar issue, the gradient is not the same direction (origin?):
using this code
```
<Grid.Background>
    <LinearGradientBrush EndPoint="0.5,1" StartPoint="0.5,0">
        <GradientStop Color="#FF084A78" Offset="0"/>
        <GradientStop Color="White" Offset="1"/>
    </LinearGradientBrush>
</Grid.Background>
```
and
```
<Button.Background>
    <LinearGradientBrush EndPoint="0.5,1" StartPoint="0.5,0">
        <GradientStop Color="#FF65FF81" />
        <GradientStop Color="White" Offset="1"/>
    </LinearGradientBrush>
</Button.Background>
```
On Visual Studio it appears this way:
![image](https://user-images.githubusercontent.com/6307623/81421066-42482d80-9127-11ea-914d-3f1d16a73d06.png)

But on the Web Browser it appears this way:
![image](https://user-images.githubusercontent.com/6307623/81421086-48d6a500-9127-11ea-81ca-9b7f3d198449.png)

**Comment by Youssef1313** [comment]
I re-tested and I'm now seeing the correct behavior.

![image](https://user-images.githubusercontent.com/31348972/135045375-8f6e54d9-783c-454f-9ec4-1f0ef2d989e6.png)

@jeromelaban This probably should be closed?

**Comment by jeromelaban** [comment]
Thanks for the testing @Youssef1313.
