### ISSUE TITLE
[iOS] `ListView` Item not binding properly

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2509]
## Current behavior

We have a ListView with 5 Items, one is < x:String > and the rest are < ListViewItem >

In iOS and Wasm, one of the < ListViewItem > is not displaying the value.

In Android, only < x:String > is displayed, none of the < ListViewItem > are displaying the value.

## Expected behavior

The values of the ListViewItems should all be displayed

## How to reproduce it (as minimally and precisely as possible)

Sample:
[ListViewDisplayBinding.zip](https://github.com/unoplatform/uno/files/4087746/ListViewDisplayBinding.zip)

## Environment

Nuget Package:
Uno.UI

Package Version(s):
2.1.0-dev.769

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

In iOS and Wasm, the issue is related to scrolling

The issue is present in Uno.UI 1.45.0

There's no internal issue at the moment

**Comment by davidjohnoliver** [comment]
Confirmed on iOS still present with 3.1.0-dev.115

**Comment by carlh98** [comment]
With Uno.UI 3.6.0-dev.174,
In Wasm and Android the value are shown correctly
In iOS the values are not shown correctly

**Comment by jeromelaban** [comment]
I don't recall, but is there an internal issue associated to this ?

**Comment by carlh98** [comment]
For this issue and #2510, there are no internal issue, I found them while investigating an other issue, priority are low for both

**Comment by carlh98** [comment]
Issue present in iOS with Uno.UI 4.3.0-dev224

**Comment by carlh98** [comment]
Fixed with Uno.WinUI 4.9.20
