### ISSUE TITLE
[iOS][WASM] `ListView` Item should not display the style of the `DataTemplate`

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2510]
## Current behavior

We have a ListView with 5 Items, one is < x:String > and the rest are < ListViewItem >

< ListViewItem > displays the style of the data template

## Expected behavior

< ListViewItem > should not display the style of the data template

## How to reproduce it (as minimally and precisely as possible)

Sample:
[ListViewDisplayBinding.zip](https://github.com/unoplatform/uno/files/4087746/ListViewDisplayBinding.zip)

## Environment

Nuget Package:
Uno.UI

Package Version(s):
2.1.0-dev.769

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

The issue is present in Uno.UI 1.45.0

There's no internal issue at the moment

**Comment by davidjohnoliver** [comment]
Confirmed on iOS still present with 3.1.0-dev.115

**Comment by carlh98** [comment]
With Uno.UI 3.6.0-dev.174,
In Wasm and iOS, the style is not shown correctly
In Android, the style is shown correctly

**Comment by jeromelaban** [comment]
Thanks, is there an internal issue associated ?

**Comment by carlh98** [comment]
Issue present in iOS and Android with Uno.UI 4.3.0-dev224 (did not test wasm)

**Comment by carlh98** [comment]
Fixed with Uno.WinUI 4.9.20
