### ISSUE TITLE
The Bindable attribute is missing and the type [Windows.UI.Xaml.UnsetValue] is not known by the MetadataProvider. Reflection was used instead of the binding engine and generated static metadata. Add the Bindable attribute to prevent this message and performance issues.

### ISSUE THREAD

**Issue by Daoting** [unoplatform/uno#2512]
## What would you like to be added:
Reference [#1688](https://github.com/unoplatform/uno/issues/1688). This message is primarily a performance warning. I have added the `[Bindable]` attribute on the mentioned type. But `Windows.UI.Xaml.UnsetValue` is a internal class.
```
[Windows.UI.Xaml.Data.Bindable]
internal class UnsetValue : IEquatable<UnsetValue>
```
## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks ! Indeed, this is not a useful message.

Fixing this should be done by ignoring completely the `UnsetValue` type in the [`BindingPropertyHelper`](https://github.com/unoplatform/uno/blob/024eebddd33ac0dfa6b6d8ea0871d5c6effc9f12/src/Uno.UI/DataBinding/BindingPropertyHelper.cs) methods.
