### ISSUE TITLE
[iOS] Please support for TransformGroup on iOS

### ISSUE THREAD

**Issue by Daoting** [unoplatform/uno#2513]
## What would you like to be added:
Please add support for `TransformGroup` on iOS.
## For which Platform:

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by dr1rrb** [comment]
This were expected to work, but indeed there is a small bug that prevent them to render properly. I've fixed it, and added some UI test in order to prevent such regression.
