### ISSUE TITLE
[WASM] Clipping issue when a child is transformed

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#2514]
## Current behavior
When a child is transformed, the clipping is disabled

## Expected behavior
Clips as WinUI

## How to reproduce it (as minimally and precisely as possible)
In the sample app, check the "Gesture Recognizer/[Double|Right]TappedTests"

WASM:
![image](https://user-images.githubusercontent.com/8635919/72816224-d2746c80-3c35-11ea-9391-199a2979b97c.png)

WinUI:
![image](https://user-images.githubusercontent.com/8635919/72816236-d99b7a80-3c35-11ea-916b-1bc4786e3df6.png)

## Environment
Nuget Package: Uno.UI
Package Version(s): 2.0
Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio: _irrelevant_
Relevant plugins: _none_

**Comment by Youssef1313** [comment]
This might already be fixed.
