### ISSUE TITLE
[iOS] [Android][WASM] Arbitrary background shown when root view is transparent

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#2522]
## Current behavior

On iOS the default background color must be set per-control or text can appear as the same color and not visible.

## Expected behavior

iOS should work like UWP and Android

## How to reproduce it (as minimally and precisely as possible)

Launch the attached project in iOS and observe that one half of the app does not appear to have text.  Launch in UWP and Android and observe that both halves of the screen contain text.
[TestFontColor.zip](https://github.com/unoplatform/uno/files/4099854/TestFontColor.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
2.1.0-dev.826
Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
This is actually caused by #1674 . When that one is fixed, this will start working as well.

**Comment by DierkDroth** [comment]
@jeromelaban curious: any update on this issue?

**Comment by DierkDroth** [comment]
Thanks for your feedback.

**Comment by davidjohnoliver** [comment]
I'm not able to reproduce the issue, using iPhone 11 simulator. I can see both texts:
![image](https://user-images.githubusercontent.com/8270914/84818670-da69ea00-afe4-11ea-848f-8d2ab5a96ab4.png)

Were you testing on a physical device?

In any case if you don't have a background on the root element of the app (or another element that takes up the entire screen), you will 'see through' the app to whatever default background the system decides to show. This may give strange behaviour on other platforms as well, for example on Android, [if a native splash screen is configured](https://github.com/unoplatform/uado/blob/master/src/Uno.AzureDevOps/Uno.AzureDevOps.Droid/Resources/values/Styles.xml#L15), you will see the splash screen showing through.

We could potentially adjust somehow to force a consistent background, but it'd be a breaking change. For now, until https://github.com/unoplatform/uno/issues/2210 is fixed, the preferred solution is the one Martin suggests, to set the desired default background on the root `Grid`.

**Comment by DierkDroth** [comment]
@davidjohnoliver thanks for your follow up. iOS is not our priority at that time. As soon as this changes @peternary will revisit the issue and provide his feedback/findings.
