### ISSUE TITLE
[Android] Editing a `TextBox` located in a `Popup` may crash the app

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2533]
## Current behavior

Opening a `ContentDialog` which contains a `TextBox` may crash the app with the following exception:

```
EditView android.view.WindowManager$BadTokenException: Unable to add window
```

## Expected behavior

The application does not crash and editing the `TextBox` works.

## Workaround

Set `FeatureConfiguration.Popup.UseNativePopup` to false.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

The issue arises when the OS is trying to add the Copy/Past dialog, and does not seem to find where to place it.

**Comment by trungnt2910** [comment]
With quite a few ComboBox-related duplicate issues closed, and the main issue quite hard to find using GitHub's search, I'd say this deserves some documentation.

Furthermore, why are native Popups the default, when they are currently faulty? This forces developers to write platform-specific code every time.

**Comment by Youssef1313** [comment]
![issue2533](https://user-images.githubusercontent.com/31348972/135033349-ed3eca06-072b-4816-9ab1-ba095fbf7c64.gif)

I wasn't able to reproduce. @jeromelaban Is there anything needed more than the sample in SamplesApp to reproduce this?
