### ISSUE TITLE
[Android / iOS / WASM] TextBlock.HorizontalTextAlignment is not working

### ISSUE THREAD

**Issue by YGuerin** [unoplatform/uno#2540]
## Current behavior
TextBlock.HorizontalTextAlignment doesn't work on Android, iOS and WASM

## Expected behavior
TextBlock.HorizontalTextAlignment should work the same way it's working on UWP

## How to reproduce it (as minimally and precisely as possible)
Create a new Uno project and replace the default Hello World TextBlock by this one:
```
<TextBlock Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
	   HorizontalTextAlignment="Center"
	   TextWrapping="Wrap"
	   Margin="20"
	   FontSize="16" />
```

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.0.532

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
UWP
![HorizontalTextAlignment_UWP](https://user-images.githubusercontent.com/11750340/73179063-91ba9e80-40e0-11ea-95ee-19a243e0e26e.png)

Android
![HorizontalTextAlignment_Android](https://user-images.githubusercontent.com/11750340/73179033-86677300-40e0-11ea-9728-714f7c43f964.jpg)

iOS
![HorizontalTextAlignment_iOS](https://user-images.githubusercontent.com/11750340/73179039-8a939080-40e0-11ea-86ff-72f94030b128.jpg)

WASM
![HorizontalTextAlignment_WASM](https://user-images.githubusercontent.com/11750340/73179082-98491600-40e0-11ea-9fc2-ceb4ad5f85fc.png)

**Comment by alextrepa** [comment]
Fixed in #3472
