### ISSUE TITLE
[Android] HorizontalAlignement issue when image is inside a button

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2541]
## Current behavior

When an image is inside a button, HorizontalAlignment is not applied

## Expected behavior

When an image is inside a button, HorizontalAlignment is applied

## How to reproduce it (as minimally and precisely as possible)

Sample: [ButtonImageAlignment.zip](https://github.com/unoplatform/uno/files/4118709/ButtonImageAlignment.zip)

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.1.0-dev.878

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

There's no issue with VerticalAlignment

Internal issue:
https://nventive.visualstudio.com/Umbrella/_workitems/edit/172832

**Comment by carldebilly** [comment]
It has not been tested yet, but the package [Uno.UI v`2.1.0-dev.1090`](https://www.nuget.org/packages/Uno.UI/2.1.0-dev.1090) contains fixes related to this issue and it should be tested again on this version.

**Comment by carlh98** [comment]
The issue is present with Uno.UI 2.1.0-dev.1113

**Comment by carldebilly** [comment]
[PR #2679](https://github.com/unoplatform/uno/pull/2679) has been merged, producing `Uno.UI` v`2.1.0-dev.1371` which should be available soon on Nuget there: <https://www.nuget.org/packages/Uno.UI/2.1.0-dev.1371>. This issue could be fixed by those changes and need to be tested again with this version of `Uno.UI`.

**Comment by carlh98** [comment]
@carldebilly
The issue is present with Uno.UI 2.1.0-dev.1371
