### ISSUE TITLE
[Android] Stretched stroked Ellipse isn't correctly centered inside a Grid

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#2547]
## Current behavior

Stretched stroked Ellipse isn't correctly centered inside a Grid on Android

[Android]
![image](https://user-images.githubusercontent.com/16295702/73288396-eafdfd00-41c8-11ea-873b-e1fdb3e24dba.png)

## Expected behavior

Stretched stroked Ellipse should correctly be centered inside a Grid on all platforms

[UWP]
image
![image](https://user-images.githubusercontent.com/16295702/73288333-c99d1100-41c8-11ea-867d-2e9a47440be2.png)

## How to reproduce it (as minimally and precisely as possible)

_**[Sample repro solution in attachment of this issue]**_

`<Grid Background="DarkBlue">

		<Grid Height="74"
			  Width="74"
			  VerticalAlignment="Center"
			  HorizontalAlignment="Center">

			
			<Ellipse VerticalAlignment="Stretch"
					 HorizontalAlignment="Stretch"
					 Fill="White" />

			
			<Ellipse VerticalAlignment="Stretch"
					 HorizontalAlignment="Stretch"
					 Stroke="Red"
					 StrokeThickness="2"
					 Fill="Transparent"
					 Margin="2" />
		</Grid>
	</Grid>
`

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.1.0-dev.878

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: 16.4.1)
- [ ] for Mac (version: )

Related issue: https://nventive.visualstudio.com/Umbrella/_workitems/edit/173232

## Anything else we need to know?

Another bug related to Ellipse on iOS: #2542

**Comment by agneszitte-nventive** [comment]
Sample repro solution
[EllipseNotVisibleOniOSAndStrokedEllipseNotCenteredOnAndroid.zip](https://github.com/unoplatform/uno/files/4123713/EllipseNotVisibleOniOSAndStrokedEllipseNotCenteredOnAndroid.zip)

**Comment by carldebilly** [comment]
@agneszitte-nventive
It has not been tested yet, but the package [Uno.UI v`2.1.0-dev.1090`](https://www.nuget.org/packages/Uno.UI/2.1.0-dev.1090) contains fixes related to this issue and it should be tested again on this version.

**Comment by agneszitte-nventive** [comment]
@carldebilly Sample solution tested with https://www.nuget.org/packages/Uno.UI/2.1.0-dev.1090 and it's still the same.

**Comment by carldebilly** [comment]
Fixed by PR #2608 - will be present in package [`Uno.UI v2.1.0-dev.1166`](https://www.nuget.org/packages/Uno.UI/2.1.0-dev.1166)
