### ISSUE TITLE
[iOS][Android] The Top Margin of the Textbox is not applied

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2550]
## Current behavior

The value of the Top Margin of the Textbox is not applied correctly.
In the sample, the Top Margin of the Textbox has a value of 0 but the value applied is greater than 0.

## Expected behavior

The Top Margin of the Textbox should be applied.

## How to reproduce it (as minimally and precisely as possible)

Sample: [TextBoxMargin.zip](https://github.com/unoplatform/uno/files/4124797/TextBoxMargin.zip)

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.0.532

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Issue is not present in Uno.UI 1.45.0

Internal issue: https://dev.azure.com/nventive/Umbrella/_workitems/edit/168381

**Comment by carldebilly** [comment]
@carlh98
It has not been tested yet, but the package [Uno.UI v`2.1.0-dev.1090`](https://www.nuget.org/packages/Uno.UI/2.1.0-dev.1090) contains fixes related to this issue and it should be tested again on this version.

**Comment by carlh98** [comment]
I've tested and confirm the fix in Android and iOS
