### ISSUE TITLE
Implement TextBox on macOS

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#2551]
## What would you like to be added:

`TextBox` on macOS

## Why is this needed:

⌨

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
In progress

**Comment by MartinZikmund** [comment]
Had to leave this one for a while, required additional fixes in other places. Now in better shape, finally able to display and accept input as well as play nicely with theming. But a quite a few things are still missing, so will take a bit more work

**Comment by jeromelaban** [comment]
@MartinZikmund make sure to sync up with @ajpinedam, he's also looking at this.

**Comment by ajpinedam** [comment]
@MartinZikmund  I have made a good advance on this one. Tell me when we could sync if you want. Any input would be appreciated.

**Comment by MartinZikmund** [comment]
@ajpinedam oh, I didn't know that. I'm currently in Japan, will return on 14th March, so let's plan some call regarding this, will ping you on Twitter

**Comment by MatFillion** [comment]
@ajpinedam @jeromelaban  this should be closed? We have it working in the gallery so I assume it's done =D

**Comment by MartinZikmund** [comment]
Closing it :-)
