### ISSUE TITLE
[iOS] Border with CornerRadius and BorderThickness not displayed correctly

### ISSUE THREAD

**Issue by jcantin-nventive** [unoplatform/uno#2555]
## Current behavior

When a Border has a CornerRadius and a BorderThickness, it is displayed differently in iOS when compared to UWP and Android.

UWP
![image](https://user-images.githubusercontent.com/43351943/73385014-5c59b080-429a-11ea-9bc0-1c507e74fd7d.png)

iOS (some of the corner is visible)
![image](https://user-images.githubusercontent.com/43351943/73385053-6a0f3600-429a-11ea-9801-b62611b3ca5f.png)

## Expected behavior

When a Border has a CornerRadius and a BorderThickness, it is displayed uniformly in UWP and iOS.

## How to reproduce it (as minimally and precisely as possible)

Use this sample [app](https://github.com/jcantin-nventive/corner-radius), which uses very simple XAML

```
<Grid Margin="50">
		<Rectangle Fill="Blue"
				   HorizontalAlignment="Stretch"
				   VerticalAlignment="Stretch"
				   Margin="4" />

		<Border BorderThickness="4"
				CornerRadius="10"
				BorderBrush="Red"
				HorizontalAlignment="Stretch"
				VerticalAlignment="Stretch" />

		<Ellipse Width="16"
				 Height="16"
				 HorizontalAlignment="Left"
				 VerticalAlignment="Top"
				 Fill="#8800ff00"
				 Margin="4,4,0,0" />

		<Ellipse Width="24"
				 Height="24"
				 HorizontalAlignment="Left"
				 VerticalAlignment="Top"
				 Fill="#88888800" />
	</Grid>
```

## Environment

Nuget Package:

Package Version(s): Uno.UI both 2.0.532 and 2.1.0-dev.941

Affected platform(s):

- [x] iOS
- [ ] Android (although it's not displayed correctly in 2.0.532, it is displayed correctly in 2.1.0-dev.941)
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [x] 2017 (version: 15.9.11)
- [x] 2019 (version: 16.4.3)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by agneszitte-nventive** [comment]
@jeromelaban @MatFillion I'm able to see top corners not displaying correctly on Cards using images on iOS

**Comment by agneszitte-nventive** [comment]
@jcantin-nventive / @jeromelaban / @MatFillion 
I'm not able to reproduce the issue with latest dev (3.0.0-dev.1388)

![image](https://user-images.githubusercontent.com/16295702/89466517-fb77cd00-d741-11ea-8a5b-89f84724ee8b.png)
![image](https://user-images.githubusercontent.com/16295702/89466543-04689e80-d742-11ea-8290-c047ee62342e.png)
