### ISSUE TITLE
[Android]TextBox.InputScope=Number causes cursor to reset when entering non-numeric character

### ISSUE THREAD

**Issue by XiaotianNetlift** [unoplatform/uno#2557]
#  Current behavior
Given this textbox, `<TextBox InputScope="Number" />`, upon entering any non-numeric character the cursor position resets to back 0.

## Expected behavior
Same as uwp, the cursor position should not reset.

## How to reproduce it (as minimally and precisely as possible)
```xaml
<TextBox InputScope="Number" />
```

## Environment
Nuget Package: Uno.UI
Package Version(s):  2.1.0-dev.943
Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:
- [ ] Resharper (version: )

## Anything else we need to know?
Workaround: The same issue does not happen with if `InputScope="TelephoneNumber"` were used instead.
Somewhat related: https://github.com/unoplatform/uno/issues/2038
https://nventive.visualstudio.com/Umbrella/_workitems/edit/166205

**Comment by XiaotianNetlift** [comment]
Of note, as of written, SampleApp -> TextBox -> Input_InputScope_Number is currently missing the attribute `InputScope`. Do not use it to confirm this issue, at least not until https://github.com/unoplatform/uno/pull/2558 is completed.

**Comment by duke7553** [comment]
I was able to reproduce this bug in a small Android app for testing with the latest Uno.UI package (3.7.4)

@Xiaoy312 Can confirm that entering a non-numeric character (e.g. space, hyphen) still resets the TextBox cursor position.

@jeromelaban FYI

**Comment by duke7553** [comment]
I'm also interested if this behavior is normal in Android apps. It seems that our implementation of TextBox for android includes an implementation of Android's BaseInputConnection. Is it technically possible to override the platform behavior there to feel like WUX?

**Comment by jeanplevesque** [comment]
Still happens on Uno.UI 3.11.0-dev.487

**Comment by agneszitte-nventive** [comment]
> Still happens on Uno.UI 3.11.0-dev.487

The issue should be closed normally, 
Tested in TZ and with Uno.Material 1.2.0 / Uno.UI 4.0.11, the issue is fixed.
( cc @jeromelaban / @jeanplevesque )
