### ISSUE TITLE
Add a way to break out of this property's recursion.

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#2568]
#### Currently on:
+ **Commit**:  e61a1da0df49d2d93e32d71e2801fd84689bb007
+ **File**:    [src/Uno.UWP/Devices/Geolocation/Geopoint.cs](https://github.com/unoplatform/uno/blob/e61a1da0df49d2d93e32d71e2801fd84689bb007/src/Uno.UWP/Devices/Geolocation/Geopoint.cs)
+ **LineNum**: [16](https://github.com/unoplatform/uno/blob/e61a1da0df49d2d93e32d71e2801fd84689bb007/src/Uno.UWP/Devices/Geolocation/Geopoint.cs#L16)

**Comment by pkar70** [comment]
Ok, but... It is issue on current master, at commit level e61a1da, and not from this commit?
Really line 16? `public GeoshapeType GeoshapeType => GeoshapeType.Geopoint;` ? Where recursion is there? GeoshapeType is simple enum...
