### ISSUE TITLE
NavigationView Header isn't displayed on WASM and iOS

### ISSUE THREAD

**Issue by runceel** [unoplatform/uno#2582]
## Current behavior

NavigationView Header isn't displayed on WASM and iOS heads.

Repro XAML file is as below:

```xml
<Page
    x:Class="NavigationViewSample.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:NavigationViewSample"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:android="http://uno.ui/android"
    xmlns:ios="http://uno.ui/ios"
    xmlns:wasm="http://uno.ui/wasm"
    xmlns:win="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:toolkit="using:Uno.UI.Toolkit"
    mc:Ignorable="d android ios wasm">

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <NavigationView x:Name="navigationView" 
                        android:IsPaneOpen="False"
                        ios:IsPaneOpen="False"
                        toolkit:VisibleBoundsPadding.PaddingMask="All"
                        Header="Title bar">
        </NavigationView>
    </Grid>
</Page>
```

The screen capture:
![image](https://user-images.githubusercontent.com/79868/73605595-846f4980-45e3-11ea-91ce-d07a0de4cd8c.png)

Similer issue: https://github.com/unoplatform/uno/issues/466

When browser width is became to narrowest, then Header is appered. 

![image](https://user-images.githubusercontent.com/79868/73605754-a5d13500-45e5-11ea-907b-80bf2a716356.png)

## Expected behavior

Header is displayed on all platforms.

## How to reproduce it (as minimally and precisely as possible)

1. Create a Uno Platform project
2. Change Content of MainPage to following:
```xml
<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <NavigationView x:Name="navigationView" 
                    Header="Title bar">
    </NavigationView>
</Grid>
```
3. Run on iOS or WASM

A repository for reporoduce: https://github.com/runceel/NavigationViewSample

## Environment

Nuget Package:
- Uno.UI

Package Version(s):
- Uno.UI 2.1.0-dev.951

Affected platform(s):

- [x] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.3)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report!

The header title should be displayed properly, given that it is manipulated here:
https://github.com/unoplatform/uno/blob/6c425f49593c581607c75d560985b2ecc25beb5a/src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.cs#L2979

A validation would be to determine if this code is executed.

**Comment by jabak** [comment]
What is the status of this item apart from being open. I can see it was removed from To do in Uno 2.2. What does that mean? Will it be part of Uno 3.x To do instead? I could take a look at it and try fixing it if it makes sense?

**Comment by jeromelaban** [comment]
@jabak for now this item has not be prioritized, but if you want to take a look at it, please do!

Backporting items is based on the complexity and compatibility of the change.

**Comment by jabak** [comment]
@jeromelaban I will take a look at it during the upcoming weekend.

**Comment by jabak** [comment]
Update:

Okay finally got the iOS debugging to work. Not exactly a smooth process to get that working 😑 

Anyway I can confirm that this line of code is hit and showHeader is "true" at that point:  VisualStateManager.GoToState(this, showHeader ? "HeaderVisible" : "HeaderCollapsed", false /*useTransitions*/); 

So I think there's something going on with VisualStateManager. Will do a debug session later tonight to see if that is the case.

**Comment by jeromelaban** [comment]
You can enable the logging for `VisualStateGroup` state changes, it may help troubleshooting this issue.

**Comment by jabak** [comment]
How to I Enable logging for VisualStateGroup state changes?

**Comment by jabak** [comment]
Ahhh.. The VisualStateManager code tells me what I need to know. I need to enable loglevel Debug for the VisualStateManager type.

**Comment by jabak** [comment]
@davidjohnoliver @jeromelaban  I know you've assigned the task to me but I'm struggling to find the time to get this issue fixed. The last few months have been to busy like h.... To many projects and very limited time to dedicate to contributing.

So I can't make any promises. 

I did manage to find some time yesterday to debug. The VisualStateGroup log didn't reveal anything unusual unfortunately. But when clicking around I did notice that when resizing the browser windows the WASM solution started behaving in an unusual way. At the the visual state point where the navigation view is supposed to collapse to icons only sidebar a strange clickable black/gray box is suddenly layered on top of the content area and thus hiding the header text. So I think the header text is there but is getting hidden by some unwanted unknown "control". When clicking on that control it disappears and the header text is revealed as it's supposed to. 

I've not had the time to verify if that's also the case with iOS.

**Comment by codeinstinct** [comment]
Just wanted to add information about a bug related to this.
When we select dark theme by 
```
<Application
    x:Class="App9.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App9"
    RequestedTheme="Dark">
</Application>
```

The NavigationView Header appears incorrectly (a white band) on the wasm side.

Dark theme
![Improper](https://user-images.githubusercontent.com/1712514/90633377-91801d00-e243-11ea-8fd8-2c34851ea4a9.png)

Normal theme (light)
![Proper](https://user-images.githubusercontent.com/1712514/90633379-9218b380-e243-11ea-9927-65dc06df7da8.png)

**Comment by jabak** [comment]
Is the "white band" clickable? If so what happens when clicked?

**Comment by MartinZikmund** [comment]
@runceel @jabak This should now work with the new WinUI `NavigationView`. If you encounter any issues, please reopen this issue/create a new one and link it to this one.
