### ISSUE TITLE
TwoWay x:Bind doesn't work

### ISSUE THREAD

**Issue by runceel** [unoplatform/uno#2587]
## Current behavior

TwoWay x:Bind doesn't work even without BindBack property.

## Expected behavior

Synchronize value between source to target the same as UWP.

## How to reproduce it (as minimally and precisely as possible)

1. Create a ViewModel class that is implemented INotifyPropertyChanged interface.
2. Define a property type is the ViewModel.
3. Define two way x:Bind on the XAML such as `{x:Bind ViewModel.PropertyA, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}`.

## Environment

Nuget Package:
- Uno.UI

Package Version(s):
- Uno.UI 2.1.0-dev998

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.3)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

I created a repository for repro.
https://github.com/runceel/TowWayXBind

And I recorded behaviors on each platform:

### UWP
It works.
![xbinduwp](https://user-images.githubusercontent.com/79868/73632461-1c7e3900-469f-11ea-9fa3-0da7ad102d55.gif)

### Android
It doesn't work.
![xbinddroid](https://user-images.githubusercontent.com/79868/73632608-88f93800-469f-11ea-8adf-6ccfd29018df.gif)

### WASM
It doesn't work.
![xbindwasm](https://user-images.githubusercontent.com/79868/73632647-acbc7e00-469f-11ea-9cd0-3b3035e608ae.gif)

**Comment by MartinZikmund** [comment]
I can confirm I am seeing this problem too.

**Comment by agneszitte-nventive** [comment]
(Other related x:Bind issu : https://github.com/unoplatform/uno/issues/2693)
