### ISSUE TITLE
[Android] Support HingeAngleSensor

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#2598]
## What would you like to be added:

`HingeAngleSensor` on Android

## Why is this needed:

Surface Uno, Duo, Neo!

## For which Platform:

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
@MartinZikmund you should be able to use `ApiExtension` to enable that scenario. Let me know how this goes :)

**Comment by jeromelaban** [comment]
(docs: https://github.com/unoplatform/uno/blob/e61a1da0df49d2d93e32d71e2801fd84689bb007/doc/articles/uno-development/api-extensions.md)

**Comment by MartinZikmund** [comment]
Merged, closing
