### ISSUE TITLE
[Android][iOS] Scrolling is not updating the Selected item/index correctly

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2606]
## Current behavior

When you scroll horizontally in a PeekingFlipView the Selected Item/Index is not updated correctly, most of the time it's not updated at all.

## Expected behavior

When you scroll horizontally the Selected Item/Index is updated correctly

## How to reproduce it (as minimally and precisely as possible)

Sample: 
[PeekingFlipViewSelection.zip](https://github.com/unoplatform/uno/files/4162118/PeekingFlipViewSelection.zip)

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.1.0-dev.1141

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Internal issue: https://nventive.visualstudio.com/Umbrella/_workitems/edit/173495
TouchDown on the item is not triggering the animation.
Early investigating indicates that the issue is from TransformToVisual in src/Uno.UI/UI/Xaml/UIElement.cs

**Comment by jeromelaban** [comment]
The source issue was closed, closing this one as well.
