### ISSUE TITLE
Default FontSize for TextBlock does not match UWP

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#2609]
## Current behavior

On Android, iOS and macOS the default `FontSize` is 11.

## Expected behavior

On UWP the `FontSize` defaults to 11, but "somehow" it is overriden to 15.

I have noticed WASM has this: https://github.com/unoplatform/uno/blob/1ad96bc145a343724515f44d1d79bb3d14c0c881/src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml#L22

Shouldn't this be declared for all platforms for now? The default font is very small.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

**Comment by davidjohnoliver** [comment]
I included this breaking change in the yet-to-be-merged Styles overhaul: https://github.com/unoplatform/uno/pull/1766/files#diff-c5ebe965390a0665769925876a509e40R284

**Comment by davidjohnoliver** [comment]
The default `TextBlock.FontSize` in Uno is now `15`. 

However, on UWP 1809 and above (which the Uno solution template now targets), the default `FontSize` seems to've changed to 14... so this issue is still valid.
