### ISSUE TITLE
Slow startup on Android using Uno 2.0

### ISSUE THREAD

**Issue by lukasf** [unoplatform/uno#2612]
## Current behavior

A simple "Hello World" app using Uno 2.0, published on a highend Android device (SnapDragon 845) takes about 4 seconds to start on a debug build. That is way too much for an app that only renders a TextBlock. On a release build with full AOT still takes 2 seconds. That is without debugger attached, of course. The Android emulator also shows very slow startup.

## Expected behavior

I would expect startup times to be very close to what a Xamarin.Android app takes. A blank app using Xamarin.Android only takes 2 seconds to start on the same device, the release build more like 1 second. The release build here is even without AOT - adding AOT or Startup Tracing would probably further improve startup times.

## How to reproduce it (as minimally and precisely as possible)

Create a new Uno app using the latest Uno default templates and nuget packets. This will only render a "Hello World" TextBlock.

For comparison, create a new Xamarin.Android app using the default "single page" template. Startup times are a whole lot better.

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.0.532

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.4)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

I am not 100% sure, but I think that I have seen faster startup when I tried this end of last year, using Uno 1.4.

**Comment by MartinZikmund** [comment]
Related to #1968

**Comment by francoistanguay** [comment]
Should be re-tested with latest release and net6.
