### ISSUE TITLE
[WASM] ListView_ExpandableItem and ListView_ExpandableItemLarge UI Tests don't pass

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#2615]
## Current behavior 

ListView_ExpandableItem and ListView_ExpandableItemLarge UI Tests don't pass for WASM

## Expected behavior

ListView_ExpandableItem and ListView_ExpandableItemLarge UI Tests should pass for all platforms

## How to reproduce it (as minimally and precisely as possible)

See these UI TESTS: 
- SamplesApp.UITests.Windows_UI_Xaml_Controls.ListViewTests.ListViewTests_Tests.ListView_ExpandableItem_ExpandMultipleItems
- SamplesApp.UITests.Windows_UI_Xaml_Controls.ListViewTests.ListViewTests_Tests.ListView_ExpandableItem_ExpandSingleItem
- SamplesApp.UITests.Windows_UI_Xaml_Controls.ListViewTests.ListViewTests_Tests.ListView_ExpandableItemLarge_ExpandHeader_Validation
- SamplesApp.UITests.Windows_UI_Xaml_Controls.ListViewTests.ListViewTests_Tests.ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation

## Environment

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

Related PR : https://github.com/unoplatform/uno/pull/2456 (WASM platform ignored for now until this issue is fixed)

**Comment by davidjohnoliver** [comment]
Closing this out in favour of more specific issues:

 - `ListView_Expandable_Item` tests: `AtIndex()` isn't supported by Uno.UITest on WASM - https://github.com/unoplatform/Uno.UITest/issues/47
 - `ListView_Expandable_Item_Large` tests: `ListView.Header` isn't yet implemented for WASM - https://github.com/unoplatform/uno/issues/1979
