### ISSUE TITLE
Add cross-platform splash screen to the default project template

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#2616]
## What would you like to be added:

After writing article on setting up splash screens in Uno, I realized, that it could actually be part of the default template with all platforms using the `SplashScreen.scale-200.png`. This way the experience would match UWP from the first moment.

## Why is this needed:

Easy to set up splash screen.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by pkar70** [comment]
Where is this article?

**Comment by MartinZikmund** [comment]
https://blog.mzikmund.com/2020/02/splash-screen-in-uno-platform-apps/

**Comment by pkar70** [comment]
I recompiled three my apps with Uno 945, and with splash screen implemented using your method. In two apps everything is ok. In third app, splash screen stays after loading MainPage.

**Comment by pkar70** [comment]
I found problem source.
MainPage.xaml, `<Grid`, must have attribute Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
When this attrib is placed in `<Page`, splashscreen doesn't disappear and stays forever.

**Comment by morning4coffe-dev** [comment]
Is this issue still relevant, now that we use Resizetizer for icon and [splashscreen](https://platform.uno/docs/articles/external/uno.resizetizer/doc/using-uno-resizetizer.html?tabs=singleproject%2CAndroid#unosplashscreen)?

**Comment by jeromelaban** [comment]
This is handled by resizetizer, yes!
