### ISSUE TITLE
The text verticalPosition of textbox is not center

### ISSUE THREAD

**Issue by double28** [unoplatform/uno#262]
## I'm submitting a...

 Bug report (I searched for similar issues and did not find one)  
 

## Current behavior

The verticalAlignment of textbox's text is not center,It's hard to position the text to center.

## Expected behavior

Deal the content of textbox,position the content.

## Environment

```
Nuget Package: 

Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by double28** [comment]
Given the FontSize is not change, I can use Padding to make the text at center! Why the VerticalContentAlignment property not work?

**Comment by davidjohnoliver** [comment]
Could you provide some sample code and specify on which platform you encountered the bug?

If I try the following:
```` xaml
			<TextBox Height="60"
					 Text="Entered text"
					 VerticalContentAlignment="Center"/>
````

The text still appears at the top of the TextBox even on UWP.
