### ISSUE TITLE
Project templates are missing template tags

### ISSUE THREAD

**Issue by dotMorten** [unoplatform/uno#2620]
## Current behavior
Currently the Uno templates doesn't have template tags:

![image](https://user-images.githubusercontent.com/1378165/74092789-d6015380-4a7d-11ea-92ab-2b38a8213ffa.png)
This means when you filter by for instance C#, the templates are no-where to be found.

In VS2017 templates was filtered by their location in a set of folders. With VS2019U1+ this has been controlled by tags instead.

## Expected behavior

Tags should be displayed and you should be able to discover the templates by filtering

## How to reproduce it (as minimally and precisely as possible)

Open the new project dialog. Noticed the templates doesn't have tags as highlighted in photo above. Filter by for instance `C#` and they'll not be listed any longer.

## Environment

VS16.4 and VS16.5p2

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [x] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
Feature documented here: https://docs.microsoft.com/en-us/visualstudio/ide/template-tags?view=vs-2019

**Comment by MartinZikmund** [comment]
Will close this now as PR is merged :-)
