### ISSUE TITLE
Unpredictable Style Change from Button in WebAssembly via Xamarin.Forms and Uno Platform

### ISSUE THREAD

**Issue by berkbb** [unoplatform/uno#2623]
## Current behavior

I'm developing a cross platform Xamarin.Forms app. Now, I added the experimental support for WebAssembly via Uno Platform.

In Uno platform, WebAssembly UI depends on UWP UI. As you see at the bottom, I have a button on my ContentPage and it responds the size change and don't miss the current proposition.However, in WebAssembly, the button's text goes to right as you see:

https://i.stack.imgur.com/lTdaF.png
https://i.stack.imgur.com/B7iLL.png
https://i.stack.imgur.com/IJeH4.png
https://i.stack.imgur.com/nlcfX.png

## Expected behavior

Button must be act same as UWP in WebAssembly.

## How to reproduce it (as minimally and precisely as possible)

**My special ContentView item inside a ScrollView and StackLayout combine like this:**

```
            <Grid x:Name="ResultGrid" Grid.Row="1">
                <StackLayout>
                    <ScrollView x:Name="Scroller" >
                        <StackLayout x:Name="DataStack" Margin="30" />
<!-- Contentview added inside DataStack via code . -->
                    </ScrollView>
                </StackLayout>

            </Grid>
```
**My ContentView:**

```
<?xml version="1.0" encoding="UTF-8"?>
<ContentView xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="ACM_SearchEngine_xFormsWASM.UserControls.SearchResultCapsule" >
  <ContentView.Content>
        <Grid x:Name="ResultDataViewer" Margin="0,10">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="Auto" />
                <ColumnDefinition Width="*" />
                <ColumnDefinition Width="Auto" />
            </Grid.ColumnDefinitions>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto" />
                <RowDefinition Height="Auto" />
            </Grid.RowDefinitions>

            <Frame BackgroundColor="#4CB8C282" BorderColor="#343434" CornerRadius="10" Grid.RowSpan="2" Grid.ColumnSpan="3"></Frame>
            <Image x:Name="FileLogo" Margin="10" Source="Assets\journalcover_small.png" Grid.RowSpan="2" Grid.ColumnSpan="1" WidthRequest="96" HeightRequest="96" />
            <Button x:Name="Buy_Button" Text="Satın Al" FontAttributes="Bold" TextColor="#e2e2e2" BackgroundColor="#2A52BE" FontFamily="Segoe UI" Grid.Column="2" Grid.ColumnSpan="1" Grid.RowSpan="1"  CornerRadius="5"  VerticalOptions="Start" HorizontalOptions="Center" FontSize="15.667" Grid.Row="0" Margin="0,10,10,0" WidthRequest="100" />
            <Label x:Name="Issue_TitleMonthYear_Label" FontSize="18.667" FontAttributes="Bold" FontFamily="Segoe UI Bold" Grid.Column="1" Grid.ColumnSpan="1" Grid.RowSpan="1" Margin="10"></Label>
            <Label x:Name="IssueNumber_Label" Text="1" FontSize="18.667" FontAttributes="Bold" FontFamily="Segoe UI Bold" Grid.RowSpan="2" Grid.ColumnSpan="1" VerticalOptions="Center" HorizontalOptions="Center" VerticalTextAlignment="Center" HorizontalTextAlignment="Center" Margin="0,8,0,0" ></Label>
            <Label x:Name="ArticlesList_Label" TextType="Html" Margin="10" Grid.Column="1" Grid.ColumnSpan="1" Grid.Row="1" Grid.RowSpan="1" FontSize="15.667" TextColor="#36454F" FontFamily="Segoe UI Bold" FontAttributes="Italic"  />
        </Grid>
    </ContentView.Content>
</ContentView>
```
**The adding code block is:**

```
 private void ContentPage_Appearing(object sender, EventArgs e)
        {
            SearchKeyword_Title.Text = string.Format("'{0}'  anahtar kelimesi arama sonuçları:", search_keyword);


            var z = new SearchCapsule_IssueCreator(32, SearchCapsule_IssueCreator.Months.Eylül.ToString(), SearchCapsule_IssueCreator.Months.Ekim.ToString(), 2020, "");

            var t = new SearchCapsule_IssueCreator(21, SearchCapsule_IssueCreator.Months.Nisan.ToString(), SearchCapsule_IssueCreator.Months.Mayıs.ToString(), 2020, "");

            z.AddArticle("XAML - HTML dönüşümü nasıl yapılır ?", 15, 20);
            z.AddArticle("Bu bir test yazısıdır.", 45, 60);

            t.AddArticle("UNO Platform Hakkında.", 3, 10);
            t.AddArticle("Deneme 1-2-3.", 22, 30);

            var x = new SearchResultCapsule(z);

            var y = new SearchResultCapsule(t);

            DataStack.Children.Add(x);
            DataStack.Children.Add(y);

        }
```

## Environment

Nuget Package:

Uno.Xamarin.Forms.Platform
Uno.Wasm.Bootstrap
Microsoft.Extensions.Logging.Filter
Microsoft.Extensions.Logging.Console
NETStandard.Library
Xamarin.Essentials
NETStandard.Library
Xamarin.Forms
Microsoft.NETCore.UniversalWindows
Xamarin.Essentials

Package Version(s):

Id            |        Versions
--            |           --
Uno.Xamarin.Forms.Platform | {4.3.4}
Uno.Wasm.Bootstrap | {1.0.10}
Microsoft.Extensions.Logging.Filter | {1.1.1}
Microsoft.Extensions.Logging.Console | {1.1.1}
NETStandard.Library | {2.0.3}
Xamarin.Essentials | {1.3.1}
NETStandard.Library | {2.0.3}
Xamarin.Forms | {4.3.0.908675}
Microsoft.NETCore.UniversalWindows | {6.1.9}
Xamarin.Essentials | {1.3.1}

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ X] WebAssembly
- [ X] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ X] 2019 (version: 16.4 )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by ajpinedam** [comment]
Hi @berkbb !

I copied all the data you provided (thanks for that) into a project but unfortunately, I could not replicate the issue. 

Would be possible to have your project shared so that I can run the same solution?

Also, would you try something else? Please create a new page with only a button inside a grid in it, you can even use the code from the button above.

```
<Button x:Name="Buy_Button" 
        Text="Satın Al" 
        FontAttributes="Bold" 
        TextColor="#e2e2e2" 
        BackgroundColor="#2A52BE" 
        FontFamily="Segoe UI"         
        CornerRadius="5"  
        VerticalOptions="Start" 
        HorizontalOptions="Center" 
        FontSize="15.667" 
        Margin="0,10,10,0" 
        WidthRequest="100" />
```

Run it and tell us if you see the same issue.

**Comment by berkbb** [comment]
Hi @ajpinedam ,

You can download my project copy form here: https://is.gd/0loHAT

I preview it both Chromium Microsoft Edge and Google Chrome. Always same issue occurred. I will try your suggestion also. Thanks.

**Comment by berkbb** [comment]
Hi again @ajpinedam ,
It's running perfectly in new solution. What is going on my project , I cannot solve yet :) I did not do anything different.

**The ContentPage:**

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="App1.MainPage">

    <Grid>
        <Button x:Name="Buy_Button" 
        Text="Satın Al" 
        FontAttributes="Bold" 
        TextColor="#e2e2e2" 
        BackgroundColor="#2A52BE" 
        FontFamily="Segoe UI"         
        CornerRadius="5"  
        VerticalOptions="Center" 
        HorizontalOptions="Center" 
        FontSize="15.667" 
        Margin="0,10,10,0" 
        WidthRequest="100" />
    </Grid>
</ContentPage>
```



![WASM](https://user-images.githubusercontent.com/23173536/74131408-4c749180-4bf5-11ea-80a0-835d467020ef.png)
![UWP](https://user-images.githubusercontent.com/23173536/74131414-4e3e5500-4bf5-11ea-8174-37c900f360a1.PNG)

**Comment by ajpinedam** [comment]
@berkbb  I tried downloading the project but the link is dead.

I added a Scrollview to the project, as you did, but I have not been able to reproduce it. Maybe I don't have the whole picture of the issue.

**Comment by berkbb** [comment]
Issue still continues :) Xamarin.Forms projection don't have this issue. I assume that problem is on Uno.Uı VS template.
