### ISSUE TITLE
UWP Project template has invalid/expired certificate 

### ISSUE THREAD

**Issue by dotMorten** [unoplatform/uno#2624]
## Current behavior

When you use the project template to create a new project, you get the following warning from the UWP project:

> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(2652,5): warning APPX0108: The certificate specified has expired. For more information about renewing certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.

## Expected behavior

No warnings generated / certificate up to date (ie using the template wizard to generate it)

## How to reproduce it (as minimally and precisely as possible)

Create a new project using the Uno application template.
Build the UWP project.

## Environment

Windows

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Windows
- [ ] Build tasks
- [x] Solution Templates

Visual Studio:

- [x] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
Will close this now, as PR is merged :-) .
