### ISSUE TITLE
[WASM] SkiaSharp DrawLine and DrawCircle methods not working

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#2635]
## Current behavior

Both DrawLine and DrawCircle methods fail when used in WASM

## Expected behavior

Methods should draw line and circle respectively.

## How to reproduce it (as minimally and precisely as possible)

In UWP in the attached project, test the various draw buttons - observe that all will produce the appropriate image on the canvas.

In WASM test the buttons again, observe that both DrawLine and DrawCircle fail, while the others work as expected.

[SkiaSharpLine.zip](https://github.com/unoplatform/uno/files/4182778/SkiaSharpLine.zip)

## Environment

Nuget Package:
Uno.SkiaSharp.Views
Uno.SkiaSharp.Wasm
Package Version(s):
 1.68.0-uno.293
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the repro. I can repro that Circle and Line have an issue as well.
