### ISSUE TITLE
[WASM] Setting ComboBox height breaks layout

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#2637]
## Current behavior

If you set the height for a combobox in WASM then the contained text is off-center.  This happens even if you set a ComboBox to its default height manually.

## Expected behavior

Text should be centered correctly, as in UWP.

## How to reproduce it (as minimally and precisely as possible)

Open the attached project in UWP and observe that, when an object is selected, the text is center in all 3 columns.  Columns 1 and 3 should have identical height values displayed if you click the corresponding button.

Open the attached project in WASM and observe that ComboBoxes 1 and 3 have contents centered incorrectly.  ComboBox 2 - the only one without Height specified manually - is correct.  Click the corresponding buttons and observe that all 3 ComboBoxes have matching heights.

Note: ComboBox 3 includes entire style manually as suggested for a separate [styling issue](https://github.com/unoplatform/uno/issues/2404).

[LayoutTest.zip](https://github.com/unoplatform/uno/files/4185783/LayoutTest.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
2.1.0-dev.1181
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This is cause by a layout regression, thank you for the sample.

/cc @carldebilly

**Comment by peternary** [comment]
Fixed!
