### ISSUE TITLE
[WASM] Textblock clipping incorrect if value updated after initial draw.

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#2638]
## Current behavior

If a TextBlock has its bound value updated then clipping is not applied properly to the new value in WASM.

## Expected behavior

Text trimming behavior should kick in on updated values where appropriate.

## How to reproduce it (as minimally and precisely as possible)

In the attached project start in UWP - note that values, when too long for their space, are ellipse trimmed.  Start the project in WASM and observe that text simply overflows to the right.

[TextTrimmingTest.zip](https://github.com/unoplatform/uno/files/4186742/TextTrimmingTest.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
2.1.0-dev.1192
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
Do you have nearby a repro snippet for this bug?

**Comment by peternary** [comment]
Repro now attached

**Comment by jeromelaban** [comment]
I can reproduce the issue with the attached sample, thank you.

**Comment by jeromelaban** [comment]
Fixed by https://github.com/unoplatform/uno/pull/2671

**Comment by DierkDroth** [comment]
@jeromelaban excellent thanks. @peternary will look into asap.
