### ISSUE TITLE
[WASM] SkiaSharp SVG does not redraw after initial draw.

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#2639]
## Current behavior

If an SVG has been used to populate a canvas in SkiaSharp then using a new SVG to repaint the canvas does not result in a new image drawn to screen.

## Expected behavior

Canvas should contain image from new SVG data

## How to reproduce it (as minimally and precisely as possible)

Start the attached project in UWP, and observe that clicking on the icon will cause it to alternate between 2 svg paths.  Start the project in WASM and observe that clicking the icon has no effect.

[SvgUpdate.zip](https://github.com/unoplatform/uno/files/4187161/SvgUpdate.zip)

## Environment

Nuget Package:
Uno.SkiaSharp.Wasm.Svg
Package Version(s):
1.60.0-uno.173
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks peter for the sample.

In that sample, it seems that the `Invalidate()` method is not called in the `SvgView.Path` setter for Wasm, preventing the canvas from refreshing. Is this is the original intent ?

**Comment by peternary** [comment]
I had missed that, it was part of another test.  Closing the issue.
