### ISSUE TITLE
[macOS] Implement ShowPhoneCallUI

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#2641]
## What would you like to be added:

`ShowPhoneCallUI` API on WASM and macOS using the `tel:` URI scheme.

## Why is this needed:

Uno.Xamarin.Essentials

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
WASM is already implemented, removing it from issue

**Comment by MartinZikmund** [comment]
Done.

**Comment by jeromelaban** [comment]
You can use the "[Fixes](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)" syntax to auto-close issues.
