### ISSUE TITLE
ListView Header with no HeaderTemplate set has wrong font size

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#265]
## I'm submitting a...

Bug report
 

## Current behavior

ListView Header with no HeaderTemplate set has wrong font size.

## Expected behavior

Right font size.

## Minimal reproduction of the problem with instructions

Add following to a blank app:
```` xaml
			<ListView Header="0123"
					  ItemsSource="012345678"
					  Height="200" />
````

On Windows, header and items will have same font size. On Uno the header has a smaller font.

## Environment

Nuget Package: 

Package Version(s): 

Affected platform(s):
- [x] iOS
- [x] Android
- [ ] WebAssembly  (not tested)
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

## Workaround
Set the HeaderTemplate and explicitly set the desired font size.

**Comment by zachary-thomas-115** [comment]
Hey I would be willing to work on this!

**Comment by davidjohnoliver** [comment]
> Hey I would be willing to work on this!

Great! The first step would be to verify that the bug still occurs, some of the relevant code has changed since it was reported and it may have been fixed already.

**Comment by Youssef1313** [comment]
@davidjohnoliver Looks like it's already fixed:

![image](https://user-images.githubusercontent.com/31348972/135615656-392d5329-3c08-4801-80fd-c12f5255aefa.png)

I think we can close this one.
