### ISSUE TITLE
How to Publish Xamarin.Forms Projected WASM App to FTP Correctly.?

### ISSUE THREAD

**Issue by berkbb** [unoplatform/uno#2651]
I'm developing a WASM app with Xamarin.Forms & UNO Platform. When I use the "Publish" section in WASM project with destination FTP, the WASM created web app looks unfamiliar with debug app. My custom fonts and images disappeared and app cannot run second time. Debug mode is on IIS, my FTP server is Linux hosting js and php enabled.

Is this the problem?

What is the correct method of publishing the WASM app to FTP ? Thanks.

**Comment by jeromelaban** [comment]
@berkbb at this point, the deployment instructions are meant for IIS based servers, because of the web.config file placed at the root of the site.

If you want support for another server, you'll need to provide support for some additional mime types, particularly for the `.wasm` and `.clr` files extension:

https://github.com/unoplatform/uno/blob/8f7f1e19de1c2e03989f54b074d36f3c74e925e9/src/SolutionTemplate/UnoSolutionTemplate/Wasm/wwwroot/web.config#L17-L21

**Comment by berkbb** [comment]
@jeromelaban How can I find mimetypes for linux hosting ? Also it is enough to run the app on Linux based FTP server ? Thanks.

**Comment by jeromelaban** [comment]
The mimetypes I provided are the ones you need to set, using the appropriate configuration for your environment. 

What web server software are you using on your hosting server?

**Comment by berkbb** [comment]
LiteSpeed Web Server 

Apache Version | 2.4.41
-- | --
PHP Version | 5.6.40


![2D0EACAD-DFF6-48AA-8F1B-AEF125319EBB](https://user-images.githubusercontent.com/23173536/74560502-be433700-4f77-11ea-8453-c4876b7f66c3.jpeg)

**Comment by jeromelaban** [comment]
I do not know this server software specifically, you'll probably be able to find documentation of how to add mime types configuration.

Could you also post a screenshot of the app when hosted there, as well as browser logs, if any ?

**Comment by berkbb** [comment]
Sure @jeromelaban . I will send it tomorrow. Thanks.

**Comment by berkbb** [comment]
Hi @jeromelaban. These settings for mime are right ? Thanks.
![Ekran Resmi 2020-02-15 10 09 29](https://user-images.githubusercontent.com/23173536/74583768-8d94e900-4fdb-11ea-8fff-504b4c7b606e.png)

**Comment by berkbb** [comment]
Hi @jeromelaban . App runs only on Opera. Other browsers gives error like this. I also added the opera screenshot and console output. Thanks.

**Opera:**
![opera](https://user-images.githubusercontent.com/23173536/74585385-1c5e3180-4fed-11ea-9009-593e0fc2d25e.png)
[opera_output.txt](https://github.com/unoplatform/uno/files/4208254/opera_output.txt)

**Chrome:**
![chrome](https://user-images.githubusercontent.com/23173536/74585397-2b44e400-4fed-11ea-8309-ee2e1b279288.png)

**Edge-Chromium:**
![edge-chromium](https://user-images.githubusercontent.com/23173536/74585399-2da73e00-4fed-11ea-8198-0809353b867a.png)

**Safari:**
![safari](https://user-images.githubusercontent.com/23173536/74585400-30099800-4fed-11ea-96f9-be75bc14413b.png)

**Firefox:**
![firefox](https://user-images.githubusercontent.com/23173536/74585404-326bf200-4fed-11ea-91c4-57ed3e75dec2.png)

**Comment by jeromelaban** [comment]
Thank you. This really looks like a mimetype issue. If you look in the network tab, for the "mono.wasm" file, you'll probably see that the content is not a binary file, but most likely something else.

**Comment by berkbb** [comment]
The mime types I set are correct?

**Comment by jeromelaban** [comment]
My apologies, I did not see that message. Then can you paste here the response codes from the network tab ?

**Comment by berkbb** [comment]
Sure. You are right. "mono.wasm" seems buggy ?
![Ekran Resmi 2020-02-15 20 35 43](https://user-images.githubusercontent.com/23173536/74592534-61a55200-5033-11ea-8dae-68f2c1a8f241.png)
[error.txt](https://github.com/unoplatform/uno/files/4208824/error.txt)

How can I fix it ? Thanks.

P.S: Opera Screenshots ( Running in opera, the custom set mimetypes seems OK for Opera ? )
![Ekran Resmi 2020-02-15 20 43 32](https://user-images.githubusercontent.com/23173536/74592612-06279400-5034-11ea-9f57-bdfe265133fd.png)
![Ekran Resmi 2020-02-15 20 43 53](https://user-images.githubusercontent.com/23173536/74592613-0a53b180-5034-11ea-841b-3362ac8718a7.png)

**Comment by berkbb** [comment]
You can also debug thee app from [here.](http://acmsearch.babadogan.net/)
 App is loaded to FTP and runnig only on Opera :)

**Comment by jeromelaban** [comment]
This is very curious. I've tried your url and it seems to work properly in Edge, Chrome and Firefox on Windows.

Maybe it's a cache issue ? In the network tab in Chrome, could you check the `Disable cache` and try again ?

**Comment by berkbb** [comment]
Hi,

Are  macOS and iOS browsers the main problem ? The app cannot load with Safari on iOS also.
![4B057520-9DD1-4007-BBF0-2980A8F0815C](https://user-images.githubusercontent.com/23173536/74600290-5a685d80-50a0-11ea-8b68-25dad6fd234c.png) 
I will try it. Is my app have a problems with “mono.wasm” ? Very interesting, only Opera on macOS loading some clr and pdb files on macOS. In addition, chromium Edge on Windows cannot run the app unless in debug mode with IIS. Very frustrating:(

**Comment by berkbb** [comment]
Hello. This is running for me except mobile browsers on iOS and Android  ( It never opens on mobile.) [Hosting site](http://acmsearch.babadogan.net/)

>  In the network tab in Chrome, could you check the Disable cache and try again ?  


For make app working, should I clear the browser caches ? 

I uploaded the app to Azure Web App also. App on Azure works perfectly on desktop browsers without any hassle. You can access Azure Web App from [here](https://acmsearch.azurewebsites.net/).
**Both azure web app and hosting:**

- It opened extreme slowly on Android.
- Not opened in iOS.


How can I fix it on mobile? Thanks.

**Comment by jeromelaban** [comment]
I do not know how your web server works, so there may be issues with caching there (particularly with regards to the etag header).

About Android and iOS, web assembly is still young, and mono is still running with the interpreter mode if you build it using default settings. This means it will slower that the native iOS/Android counterpart, or when running with mono AOT.

For iOS, WebKit is quite far behind in terms of wasm support and performance, and the module size limit is pretty low is you've noticed. Improvements are coming in the 1.1-dev branch of the Uno Bootstrapper, so the situation should improve then.

**Comment by berkbb** [comment]
@jeromelaban I wish, it is so important for me now. I'm waiting 1.1 
impatiently :) Thanks for fast, bold and kindly support 👍 :)

**Comment by jeromelaban** [comment]
You can already try the 1.1 dev branch, it's available on nuget. If you find something let us know!

**Comment by berkbb** [comment]
Not solved in Uno.Wasm.Bootstrap 1.1.0 dev-418:(
