### ISSUE TITLE
Can I use XAMLSourceGenerator to convert WPF/UWP XAML to equivalent code?

### ISSUE THREAD

**Issue by ekalchev** [unoplatform/uno#2653]
I am researching the options to convert WPF/UWP XAML to source code to avoid parsing BAML in runtime.  I found Uno has XAMLSourceGenerator, I wonder if this code can be adapted to do what I need to?

**Comment by jeromelaban** [comment]
Thanks for your question. 

The XAML Generator is indeed doing what you're describing, though it's doing it in a way that suited for the Uno implementation (e.g. using uno specific methods for features that are not supported by the WinUI public API).

In those cases, you may need to change those calls to something else if it's somehow available.

The tooling is not made to be used as a standalone generator, so you'll need to create an Uno project and get the files from the `obj/xx/g/xamlgenerator` folder.
