### ISSUE TITLE
UNO Default VS Template New Project has errors

### ISSUE THREAD

**Issue by aammfe** [unoplatform/uno#2654]
Hello!!
I m facing errors With File new Project in VS 2019.
I just create it and while restoring showing these errors,
I m using latest VS. 
![image](https://user-images.githubusercontent.com/11896817/74585084-cd1efd80-4ffa-11ea-8d3e-5b54633ea899.png)

**Comment by jeromelaban** [comment]
Thanks for opening the issue!

Do all projects build ? 

Those are generally intellisense errors that may appear until the restore is fully complete (it seems there's a restore error in your status bar).

**Comment by aammfe** [comment]
Yes Actually its Restore issue.
![image](https://user-images.githubusercontent.com/11896817/74623431-6a4a7500-5166-11ea-9e31-f6dd55d3ca20.png)

My internet connection is working but why its failed to download ?
is there anything missing ?

**Comment by jeromelaban** [comment]
Can you try running this command at the root of the solution:

`msbuild /r /t:restore /bl`

and see if you're getting different errors ?

**Comment by aammfe** [comment]
manually deleted _bin_ and _obj_ folders and then run upper command still errors.
![image](https://user-images.githubusercontent.com/11896817/74672912-08265a00-51d0-11ea-8b38-af1139e62cd1.png)

**Comment by jeromelaban** [comment]
Does VS 2019 still show the errors you mentioned orignally ?

**Comment by aammfe** [comment]
> Does VS 2019 still show the errors you mentioned orignally ?

yes

**Comment by hawkerm** [comment]
I hit different errors with the new project template in VS 2019 16.5.2, templates v2.0.532.6.

I couldn't run the WASM project first, I then tried the UWP one and that worked. Then the WASM would build and run but give me this error in the browser:

```
DirectoryNotFoundException
Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root, ExclusionFilters filters)
Uno.Wasm.Bootstrap.Cli.Server.Startup.Configure(IApplicationBuilder app, IConfiguration configuration) in Startup.cs
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

**Comment by jeromelaban** [comment]
@hawkerm if you update to the latest bootstrapper (1.2-dev) that error should disapear. Make sure to follow this for the upgrade: https://github.com/unoplatform/Uno.Wasm.Bootstrap#upgrading-from-previous-versions-of-the-unowasmbootstrap-package

**Comment by hawkerm** [comment]
Thanks @jeromelaban, now I'm getting:
```
HTTP Error 502.5 - Process Failure

Common causes of this issue:
The application process failed to start
The application process started but then stopped
The application process started but failed to listen on the configured port
```

Debug output
```
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[13544] dotnet.exe' has exited with code -2147450740 (0x8000808c).
```

And in the webserver:
```
Error:
  An assembly specified in the application dependencies manifest (dotnet-unowasm.deps.json) was not found:
    package: 'System.Security.Cryptography.Pkcs', version: '4.5.0'
    path: 'runtimes/win/lib/netcoreapp2.1/System.Security.Cryptography.Pkcs.dll'
```

I  tried adding that package to the references, but same error occured.

**Comment by jeromelaban** [comment]
This is odd. If you updated to the bootstrapper 1.2, the runtime used to run the dev server is 3.1. This may mean that there's still a reference to the 1.1 bootstrapper. Could you paste PackageReference parts of your wasm project ?

**Comment by francoistanguay** [comment]
Is this still valid with Uno 3.0 or can we close this?
