### ISSUE TITLE
"RangeError: Maximum call stack size exceeded " error for WebAssembly project on WKWebView & WebView

### ISSUE THREAD

**Issue by berkbb** [unoplatform/uno#2657]
## Current behavior

Hello.
 My WebAssembly app which is projected from Xamarin.Forms runs perfectly on desktop browsers however not working properly on mobile browsers for iOS and Android both [here](http://acmsearch.babadogan.net/) and [here.](https://acmsearch.azurewebsites.net/)

**Both azure web app and hosting:**

-  It opened **extreme slowly** on **Android**.
- Not **opened in iOS**.

If I open my web apps with Chrome on iOS with physical device (It uses WKWebView also.), I got this error:

> "RangeError: Maximum call stack size exceeded"

![74633901-c36cd580-5173-11ea-8641-0e4b3a8e890a](https://user-images.githubusercontent.com/23173536/74640646-f49fd280-5180-11ea-9321-1e688c156700.jpeg)

```
http://acmsearch.azurewebsites.net/

LOGMONO_WASM: Loaded: System.Numerics.dll
LOGMONO_WASM: Loaded: Mono.Security.dll
LOGMONO_WASM: Loaded: System.dll
LOGMONO_WASM: Loaded: System.Xml.dll
LOGMONO_WASM: Loaded: ACM_SearchEngine_xFormsWASM.Wasm.dll
LOGMONO_WASM: Loaded: System.Core.dll
LOGMONO_WASM: Loaded: WebAssembly.Net.WebSockets.dll
LOGMONO_WASM: Loaded: System.Drawing.Common.dll
LOGMONO_WASM: Loaded: System.Net.Http.dll
LOGMONO_WASM: Loaded: WebAssembly.Net.Http.dll
LOGMONO_WASM: Loaded: mscorlib.dll
LOGMONO_WASM: Loaded: WebAssembly.Bindings.dll
LOGMONO_WASM: Loaded: System.Runtime.Serialization.dll
LOGMONO_WASM: Loaded: System.ServiceModel.Internals.dll
LOGMONO_WASM: Loaded: System.Xml.Linq.dll
LOGMONO_WASM: Loaded: Uno.Xaml.dll
LOGMONO_WASM: Loaded: Uno.Foundation.dll
LOGMONO_WASM: Loaded: Uno.Core.dll
LOGMONO_WASM: Loaded: Microsoft.Extensions.Logging.Abstractions.dll
LOGMONO_WASM: Loaded: System.Collections.Immutable.dll
LOGMONO_WASM: Loaded: Microsoft.Extensions.Logging.dll
LOGMONO_WASM: Loaded: Microsoft.Practices.ServiceLocation.dll
LOGMONO_WASM: Loaded: Uno.dll
LOGMONO_WASM: Loaded: Xamarin.Forms.Platform.Uno.dll
LOGMONO_WASM: Loaded: Xamarin.Forms.Core.dll
LOGMONO_WASM: Loaded: ACM_SearchEngine_xFormsWASM.dll
LOGMONO_WASM: Loaded: Xamarin.Forms.Platform.dll
LOGMONO_WASM: Loaded: Uno.UI.Wasm.dll
LOGMONO_WASM: Loaded: Xamarin.Forms.Xaml.dll
LOGMONO_WASM: Loaded: Xamarin.Essentials.dll
LOGMONO_WASM: Loaded: Uno.UI.dll
LOGMONO_WASM: Loaded: Microsoft.Extensions.Logging.Console.dll
LOGMONO_WASM: Initializing mono runtime
LOGMONO-WASM: Runtime is ready.
ERRORRangeError: Maximum call stack size exceeded.

http://acmsearch.babadogan.net/

LOGMONO_WASM: Loaded: Mono.Security.dll
LOGMONO_WASM: Loaded: System.dll
LOGMONO_WASM: Loaded: System.Numerics.dll
LOGMONO_WASM: Loaded: ACM_SearchEngine_xFormsWASM.Wasm.dll
LOGMONO_WASM: Loaded: WebAssembly.Net.WebSockets.dll
LOGMONO_WASM: Loaded: System.Core.dll
LOGMONO_WASM: Loaded: WebAssembly.Bindings.dll
LOGMONO_WASM: Loaded: System.Drawing.Common.dll
LOGMONO_WASM: Loaded: WebAssembly.Net.Http.dll
LOGMONO_WASM: Loaded: System.Net.Http.dll
LOGMONO_WASM: Loaded: System.ServiceModel.Internals.dll
LOGMONO_WASM: Loaded: System.Xml.Linq.dll
LOGMONO_WASM: Loaded: System.Xml.dll
LOGMONO_WASM: Loaded: Uno.Xaml.dll
LOGMONO_WASM: Loaded: Uno.Foundation.dll
LOGMONO_WASM: Loaded: Microsoft.Extensions.Logging.Abstractions.dll
LOGMONO_WASM: Loaded: Uno.Core.dll
LOGMONO_WASM: Loaded: System.Runtime.Serialization.dll
LOGMONO_WASM: Loaded: mscorlib.dll
LOGMONO_WASM: Loaded: System.Collections.Immutable.dll
LOGMONO_WASM: Loaded: Uno.dll
LOGMONO_WASM: Loaded: Microsoft.Extensions.Logging.dll
LOGMONO_WASM: Loaded: Microsoft.Practices.ServiceLocation.dll
LOGMONO_WASM: Loaded: Xamarin.Forms.Core.dll
LOGMONO_WASM: Loaded: Xamarin.Forms.Platform.dll
LOGMONO_WASM: Loaded: ACM_SearchEngine_xFormsWASM.dll
LOGMONO_WASM: Loaded: Xamarin.Essentials.dll
LOGMONO_WASM: Loaded: Uno.UI.Wasm.dll
LOGMONO_WASM: Loaded: Xamarin.Forms.Xaml.dll
LOGMONO_WASM: Loaded: Microsoft.Extensions.Logging.Console.dll
LOGMONO_WASM: Loaded: Xamarin.Forms.Platform.Uno.dll
LOGMONO_WASM: Loaded: Uno.UI.dll
LOGMONO_WASM: Initializing mono runtime
LOGMONO-WASM: Runtime is ready.
ERRORRangeError: Maximum call stack size exceeded.
```
Also, I got these errors if I open web apps on iOS Simulator:

![74611354-11e68980-510c-11ea-96b3-a8d43041e3d9](https://user-images.githubusercontent.com/23173536/74640782-2dd84280-5181-11ea-9fec-69d4c8688e53.png)
![74611356-1612a700-510c-11ea-8b91-9d81f4a0c931](https://user-images.githubusercontent.com/23173536/74640842-4cd6d480-5181-11ea-9173-87c79b794e2e.png)

[ConsoleiOS.txt](https://github.com/unoplatform/uno/files/4212848/ConsoleiOS.txt)
 How can I fix this ? Thanks.

## Expected behavior

App must run properly on iOS WKWebWiew and Android WebView.

## How to reproduce it (as minimally and precisely as possible)

Try open web apps from [here](http://acmsearch.babadogan.net/) and [here.](https://acmsearch.azurewebsites.net/) with mobile browser and gather log please.

## Environment

Nuget Package:

Package Version(s):
Uno.Xamarin.Forms.Platform
Uno.Wasm.Bootstrap
Microsoft.Extensions.Logging.Filter
Microsoft.Extensions.Logging.Console
NETStandard.Library
Xamarin.Essentials
NETStandard.Library
Xamarin.Forms
Microsoft.NETCore.UniversalWindows
Xamarin.Essentials

Affected platform(s):

Id | Versions
-- | --
Uno.Xamarin.Forms.Platform | {4.3.4}
Uno.Wasm.Bootstrap | {1.0.10}
Microsoft.Extensions.Logging.Filter | {1.1.1}
Microsoft.Extensions.Logging.Console | {1.1.1}
NETStandard.Library | {2.0.3}
Xamarin.Essentials | {1.3.1}
NETStandard.Library | {2.0.3}
Xamarin.Forms | {4.3.0.908675}
Microsoft.NETCore.UniversalWindows | {6.1.9}
Xamarin.Essentials | {1.3.1}

- [ ] iOS
- [ ] Android
- [ X] WebAssembly
- [X ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ X] 2019 (version: 16.4)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This may be fixed in the 1.1-dev branch of the Uno.Wasm.Bootstrap package.

**Comment by berkbb** [comment]
@jeromelaban  I wish, it is so important for me now.  Thanks for support 👍 :)

**Comment by berkbb** [comment]
Not solved in Uno.Wasm.Bootstrap 1.1.0 dev-418:(

**Comment by jeromelaban** [comment]
It's most likely related to https://github.com/mono/mono/issues/18646
