### ISSUE TITLE
Assets with dashes (-) in their filenames are not bundled on Android

### ISSUE THREAD

**Issue by MatFillion** [unoplatform/uno#2665]
## Current behavior
Have an asset with a dash in the shared project. We're expecting it to be bundled in an Android app, just like it is on iOS, UWP and wasm.

We observe a log while building
```
Couldn't convert C:\Users\mathieu.fillion\source\repos\assets\assets.Shared\Assets\s-s-nNM9dALmmOQ-unsplash.jpg to an Android resource path.

1>  Skipping 'C:\Users\mathieu.fillion\source\repos\assets\assets.Shared\Assets\s-s-nNM9dALmmOQ-unsplash.jpg' as it's not supported on android.
```
But that's fairly "silent" of an error.
At runtime, we get this log
```
02-17 14:46:52.936 I/mono-stdout( 9012): [41m[30mfail[39m[22m[49m: Windows.UI.Xaml.Media.ImageSource[0]
[41m[30mfail[39m[22m[49m: Windows.UI.Xaml.Media.ImageSource[0]
      Couldn't find drawable with key: s-s-nNM9dALmmOQ-unsplash
02-17 14:46:52.943 I/mono-stdout( 9012):       Couldn't find drawable with key: s-s-nNM9dALmmOQ-unsplash
```

If you inspect the .apk you'll notice the image isn't there.

## Expected behavior

We should try to fail at compile time or be safe and convert the invalid "dash" proactively. (it could be tricky as anywhere we need to access that resource we would need to pass through the same conversion)

## How to reproduce it (as minimally and precisely as possible)

[assets.zip](https://github.com/unoplatform/uno/files/4216392/assets.zip)

## Environment

Nuget Package:Uno.UI 2.0

Package Version(s): 2.0

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Theres this file covering this issue. I am wondering which part is missing 
https://github.com/unoplatform/uno/blob/3a65166f03d266b6ae0127c9ddf070dd43d7eea8/src/Uno.UI/Services/AndroidResourceNameEncoder.cs

**Comment by jeromelaban** [comment]
This isse might be fixed by https://github.com/unoplatform/uno/pull/1903

**Comment by jeromelaban** [comment]
Fixed by https://github.com/unoplatform/uno/pull/3288
