### ISSUE TITLE
Please make a list of all UWP controls and mark what's available in Uno

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/uno#267]
Hi,

Please implement a table of all UWP controls (maybe of the prominent toolkits as well), and mark which of them is/isn't available in Uno.
In addition, it should be pointed out what features aren't yet implemented in specific controls.

Related: https://github.com/Microsoft/WindowsTemplateStudio/issues/2658

**Comment by davidjohnoliver** [comment]
This is now available!

The list is here: https://platform.uno/docs/articles/implemented-views.html
