### ISSUE TITLE
[Android] Image with a margin doesn't appear

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2676]
## Current behavior
The image does not appear when there's a margin

## Expected behavior

The image appears when there's a margin

## How to reproduce it (as minimally and precisely as possible)

Sample: 
[ImageDisplay.zip](https://github.com/unoplatform/uno/files/4233201/ImageDisplay.zip)

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.1.0-dev.1282

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Internal issue : https://nventive.visualstudio.com/Umbrella/_workitems/edit/174661

**Comment by jeromelaban** [comment]
related to #2679 ? @carldebilly
