### ISSUE TITLE
[Android] Ellipse is slightly cropped (top, bottom, left and right)

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2681]
## Current behavior

In a StackPanel, ellipses are cropped, when you remove the StackPanel surrounding the Grid, only the ellipse with Height="Auto" is cropped

![20200220_163503](https://user-images.githubusercontent.com/7770915/74982398-0b089100-5402-11ea-94b8-4367b25b4695.png)

## Expected behavior

Ellipses are not cropped in a StackPanel or with Height="Auto"

## How to reproduce it (as minimally and precisely as possible)

Sample:
[EllipseCrop.zip](https://github.com/unoplatform/uno/files/4233133/EllipseCrop.zip)

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.1.0-dev.1286

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Internal issue : https://nventive.visualstudio.com/Umbrella/_workitems/edit/174619

**Comment by MatFillion** [comment]
@dr1rrb You could retest this using latest Uno, I think it's solved.
