### ISSUE TITLE
Uno WASM for Xamarin Forms Can't build when third party Xamarin Forms controls are added 

### ISSUE THREAD

**Issue by DamienDoumer** [unoplatform/uno#2683]
## Current behavior
Uno Wasm for Xamarin Forms functions well when the UWP project does not include third party controls which are external to Xamarin Forms. 
But when I add a third party control, I can't run the WASM app anymore. Because the wasm project constantly throws errors stating it does not find the namespace of the related third party control.

## Expected behavior
WASM project should build and run smoothly even with third party Xamarin forms plugins added to the UWP project. Or please specify a way to deal with this behavior these build errors 

## How to reproduce it (as minimally and precisely as possible)
- Create a Xamarin Forms projectt
- Add uno wasm
- Add a third party Xamarin Forms plugin to the solution. example (PancakeView)
- Use the control in one of your views and make sure this control targets UWP
- Build the wasm project
- You can't build

Here is a sample project with the issue: https://github.com/DamienDoumer/UnoThirdPartyXFormControlBugRepro

## Environment

Xamarin Forms

Nuget Package:
Uno.Xamarin.forms.platform
Uno.Wasm.Bootstrrap

Package Version(s):
4.3.4
1.0.10

Affected platform(s):

- [x] WebAssembly renderers for Xamarin.Forms

Visual Studio:

- [ ] 2019 (version: )

**Comment by jeromelaban** [comment]
Thank you for your report!

In general control libraries that contain renderers cannot work as-is because the renderers must be available for uno-wasm as well.

In the case of PanCakeView, https://github.com/unoplatform/uno/issues/2322 was about making it work on wasm.

You're mentioning the app does not build, could you paste the build error as well ?

**Comment by DamienDoumer** [comment]
OK, the build error I get is obviously due to the fact that there is no renderer for the third party control. 
The error states: 

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'PancakeViewRenderer' could not be found (are you missing a using directive or an assembly reference?)	XamarinWebAssembly.Wasm	

To resolve it, I just removed the `PancakeViewRenderer` from the renderer assemblies in the UWP project. as shown below:
`
var assembliesToInclude = new List<Assembly>();
                //assembliesToInclude.Add(typeof(PancakeViewRenderer).GetTypeInfo().Assembly);
                Xamarin.Forms.Forms.Init(e, assembliesToInclude);
`
This doesn't only occur on pancake view, but apparently controls using custom renderers. 
Wouldn't it be better if the wasm project just ignored these custom renderers if they are absent in the wasm project ?

**Comment by jeromelaban** [comment]
I'm not sure how Uno can do anything in that context. The renderers are available for specific platforms and not for wasm. The error your mentioning seems to be in user code, it's not modifiable by the Uno tooling.

**Comment by DamienDoumer** [comment]
Ok, I get it.
