### ISSUE TITLE
Add support for Flyouts to WASM

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#2685]
## What would you like to be added:

It would be useful for WASM to support flyouts in a fashion similar to UWP

## Why is this needed:

WASM UIs can closely mimic UWP, so context-sensitive flyouts would let WASM builds more closely align with UWP builds.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the request. Flyouts are already supported by Uno on Wasm, so I'm not sure to understand what would be missing here.

Would you have a screenshot or sample of what's missing ?

**Comment by peternary** [comment]
Hm, it's simply not coming up for me in WASM

Sample here, right-clicking the green square pulls a context menu in UWP but not WASM

[App27.zip](https://github.com/unoplatform/uno/files/4237526/App27.zip)

**Comment by jeromelaban** [comment]
Got it. Right, ContextFlyouts and Menu Flyouts are not supported at this time, thanks for the details.

**Comment by peternary** [comment]
We require the ability to place the flyout at the exact location of the Pointer/Touch event, and I believe that is only supported by the MenuFlyout

**Comment by DierkDroth** [comment]
@jeromelaban basically @peternary is trying to implement a context menu.

**Comment by DierkDroth** [comment]
Excellent @jeromelaban . @peternary will test asap
