### ISSUE TITLE
x:DefaultBindMode="OneWay" is not supported on all platforms

### ISSUE THREAD

**Issue by zipswich** [unoplatform/uno#2693]
## Current behavior

x:DefaultBindMode="OneWay" has no effect for iOS/Android while it works perfectly for UWP [and WASM (as a bug at the moment)].
![ios DefaultBindMode issue](https://user-images.githubusercontent.com/6095671/75263927-a1e79b80-57bc-11ea-9832-208b5dd255c7.gif)

## Expected behavior

x:DefaultBindMode="OneWay"  should work
![UWP normal behavior for DefaultBindMode ](https://user-images.githubusercontent.com/6095671/75263940-a7dd7c80-57bc-11ea-802b-2367a4dfe6a7.gif)

## How to reproduce it (as minimally and precisely as possible)
Repro:
https://github.com/zipswich/AppDebugUno

## Environment

Nuget Package:
Uno.UI

Package Version(s):
2.1.0-dev.1338

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly (working as a bug at the moment)
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
In fact this is not yet implemented on any platform, in case of WASM it seems to be a bug instead, that x:Binds now behave as `TwoWay`, even when they are not

**Comment by zipswich** [comment]
> in case of WASM it seems to be a bug instead, that x:Binds now behave as `TwoWay`
That is a surprise. I need to keep this in mind.  Microsoft's choice of 'OneTime" as the default is irrational unless the **initialization** of "OneWay" binding is significantly more expensive.

**Comment by agneszitte-nventive** [comment]
I updated the content of this issue to reflects the latest info, thanks so much @MartinZikmund & @zipswich :) !
Other related PR for x:Bind (https://github.com/unoplatform/uno/pull/2702)

**Comment by jeromelaban** [comment]
@zipswich OneWay is more expensive than OneTime for sure, even in Uno. OneWay and TwoWay need to hook to `INotifyPropertyChanged` and `DependencyProperty` changes.

**Comment by zipswich** [comment]
Is the hooking process quite expensive or the actual calling of handlers of INotifyPropertyChanged expensive.  My original understanding was the latter.  The handlers are never called (at least for my apps) for those bindings that need only one-time binding because their values are not changed.  If it is the former, then I can understand the rationale.

**Comment by jeromelaban** [comment]
@zipswich hooking can be expensive, as it needs to be done on all levels. It's not particularly expensive perf binding, but if there are many, it can add up :)
