### ISSUE TITLE
[WASM] Assigning values from static variables in object initializers can cause logic failures

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#2696]
## Current behavior

In WASM, if you use an object initializer to assign a value from a static property to one of the object properties it can cause a preceding 'if' statement to evaluate incorrectly.

## Expected behavior

'if' statements should behave predictably.

## How to reproduce it (as minimally and precisely as possible)

Launch the attached project in UWP and observe that clicking either button results in a "null tests passed" message.  Launch in WASM and observe that clicking the button including object instantiation fails.  In the console you can further observe that while string1 and string2 independently evaluate as not being null or empty, if evaluated together they will return that one of them was null or empty.

All logic behaves consistently in the method that does not assign a value from a static property in an object initializer.

[App28.zip](https://github.com/unoplatform/uno/files/4252432/App28.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
2.1.0-dev.1338
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thank you for the repro case.

From what I can see, this was a linker issue (adding `<WasmShellILLinkerEnabled>false</WasmShellILLinkerEnabled>` fixes the issue), but it has already been fixed in a more recent build of mono.

I'll make an update of the runtime in a bootstrapper update.

**Comment by DierkDroth** [comment]
Thanks for taking care @jeromelaban. @peternary will look into asap.

**Comment by peternary** [comment]
Working for me as of latest version!
