### ISSUE TITLE
[iOS/Android/WASM] IsChecked value does not behave the same when using a converter

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#2706]
## How to reproduce it (as minimally and precisely as possible)

https://github.com/agneszitte-nventive/IsCheckedUnoIssue

## Current behavior

 IsChecked (RadioButton) value does not behave the same when using a converter

**Detailed Logs**

> syntax: $"FromEqualityToBool.Convert: {value} + {parameter} -> {returnValue}"
> syntax: $"FromEqualityToBool.ConvertBack: {value} + {parameter} -> {returnValue ?? "null"}"

### UWP

== on-load: this.DataContext = new MainViewModel() { SelectedTab = "TAB1" };
FromEqualityToBool.Convert: TAB1 + TAB1 -> True
FromEqualityToBool.Convert: TAB1 + TAB2 -> False
// TAB1 is selected

== selecting TAB2
FromEqualityToBool.ConvertBack: True + TAB2 -> TAB2
FromEqualityToBool.Convert: TAB2 + TAB1 -> False
// TAB2 is selected

== selecting TAB1
FromEqualityToBool.ConvertBack: True + TAB1 -> TAB1
FromEqualityToBool.Convert: TAB1 + TAB2 -> False
// TAB1 is selected

### Android/iOS (and normally similar behavior for the same steps for WASM)

== on-load: this.DataContext = new MainViewModel() { SelectedTab = "TAB1" };
FromEqualityToBool.Convert: TAB1 + TAB1 -> True
FromEqualityToBool.Convert: TAB1 + TAB2 -> False
// TAB1 is SelectedTab

== selecting TAB2
FromEqualityToBool.Convert:  + TAB2 -> False            **// value is null** ([CallStackValueNull.txt](https://github.com/unoplatform/uno/files/4269448/CallStackValueNull.txt))
FromEqualityToBool.ConvertBack: True + TAB2 -> TAB2
FromEqualityToBool.Convert: TAB2 + TAB1 -> False
// **nothing** is selected

== selecting TAB2 again
FromEqualityToBool.ConvertBack: True + TAB2 -> TAB2
// TAB2 is selected

== selecting TAB1
FromEqualityToBool.Convert:  + TAB1 -> False            **// value is null** ([CallStackValueNull.txt](https://github.com/unoplatform/uno/files/4269448/CallStackValueNull.txt))
FromEqualityToBool.ConvertBack: True + TAB1 -> TAB1
FromEqualityToBool.Convert: TAB1 + TAB2 -> False
// **nothing** is selected

== selecting TAB1 again
FromEqualityToBool.ConvertBack: True + TAB1 -> TAB1
// TAB1 is selected

## Expected behavior

 IsChecked (RadioButton) value should behave the same when using a converter

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.0.532 & 2.1.0-dev.1345

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.1)
- [ ] for Mac (version: )

**Comment by jeromelaban** [comment]
Thanks! This should be relatively easy to reproduce in a Unit Test.

**Comment by iury-kc** [comment]
After upgrading the Uno version to the latest, i couldn't reproduce the error.
Probably the issue was already solved by any other correction. 

![image](https://user-images.githubusercontent.com/100223422/164042836-a8107cb1-ae89-42be-9b6e-6b67ae03f8f8.png)
![image](https://user-images.githubusercontent.com/100223422/164042901-403e7732-403e-4d3a-9234-de17ece3bafb.png)
![image](https://user-images.githubusercontent.com/100223422/164042958-fb9b7baa-d906-4267-9e82-669bcdf25ad8.png)

I tried using 4.1.9 and last dev preview. Both work on Droid, iOS and Wasm as well as UWP.

**Comment by iury-kc** [comment]
@agneszitte-nventive  @jeromelaban I think it could be closed, as the problem doesn't exist anymore on stable version.

**Comment by jeromelaban** [comment]
Thanks @iury-kc !
