### ISSUE TITLE
[WASM] DatePicker is broken

### ISSUE THREAD

**Issue by SuperJMN** [unoplatform/uno#2712]
`DatePicker` is producing weird issues in the WASM head. 2 different problems are listed and are possibly related in this issue report.

# Issue 1

1. Create an empty Uno Platform application
2. in the MainPage.xaml replace the content to just a `DatePicker`

```
<Page ...>
    <DatePicker />
</Page>
```

3. Run the WASM head.
4. Nothing is rendered!

# Issue 2

1. Create an empty Uno Platform application
2. in the MainPage.xaml, add this as content

```
<Page
    x:Class="SampleApp.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:controls="using:Microsoft.Toolkit.Uwp.UI.Controls"
    mc:Ignorable="d" DataContext="{Binding Source={StaticResource Composition}, Path=Root}">

    <controls:MasterDetailsView>
        <controls:MasterDetailsView.NoSelectionContentTemplate>
            <DataTemplate>
                <DatePicker />
            </DataTemplate>
        </controls:MasterDetailsView.NoSelectionContentTemplate>
    </controls:MasterDetailsView>

</Page>
```

3. Run the WASM head.
4. The application will break on startup!

If you open the dev menu, you will see this error:

![image](https://user-images.githubusercontent.com/3109851/75617044-14a89c00-5b5a-11ea-95d8-aa740c2279e7.png)

# Packages
    <PackageReference Include="Uno.UI" Version="2.1.0-dev.1402" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="2.1.0-dev.1402" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="1.1.0-dev.422" />
    <DotNetCliToolReference Include="Uno.Wasm.Bootstrap.Cli" Version="1.0.10" />
    <PackageReference Include="Reactive.Wasm" Version="1.2.2" />
    <PackageReference Include="ReactiveUI.Uno" Version="11.2.1" />

**Comment by XiaotianNetlift** [comment]
This is caused by datepicker's control-template. #2707 partially addressed this by fixing the template.

However, the selector for datepicker will requires additional works, either by re-implementing it from scratch, or use a native wrapper for datepicker using `<input type='date' />`, or mix of both.

**Comment by yowl** [comment]
There's a few date control issues, notably https://github.com/unoplatform/uno/issues/365.

**Comment by SuperJMN** [comment]
It seems the DatePicker is still broken 
![image](https://user-images.githubusercontent.com/3109851/87242754-dab4a400-c42f-11ea-848a-1e8f6e5e84d3.png)

While it renders this, no interaction is possible.

**Comment by sakshi173** [comment]
Verified, Issue is fixed and closing.

**Comment by davidbuckleyni** [comment]
Seems to be an issue in uwp the date picker is not opening for me
