### ISSUE TITLE
[Android] ScrollViewer content clipping is incorrect after navigating to another page

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2714]
## Current behavior

Scrollviewer content is incorrectly clipped.

## Expected behavior

The content is not clipped.

## How to reproduce it (as minimally and precisely as possible)

[Bug-2714.zip](https://github.com/unoplatform/uno/files/4273368/Bug-2714.zip)

Note that the clipping issue only happens on the second page, and only if the content is set in a delayed way (e.g. through a binding).

## Environment

Nuget Package: 2.1-dev

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

https://dev.azure.com/nventive/Umbrella/_workitems/edit/175353
https://dev.azure.com/nventive/Umbrella/_workitems/edit/175742
https://dev.azure.com/nventive/Umbrella/_workitems/edit/174643

**Comment by carldebilly** [comment]
Important regression has been identified in the PR https://github.com/unoplatform/uno/pull/2736#issuecomment-595274167

Look like it's been fixed... let's see the CI output.
