### ISSUE TITLE
WinUI TreeView

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#2720]
## What would you like to be added:

The `TreeView` control.

## Why is this needed:

🌳🌲🎄🎋🌴

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
Some features the PR on Freeview support depend on #2347 and #2346 being fixed

**Comment by DierkDroth** [comment]
@MartinZikmund I appreciated your work on that issue. Is there any ETA on when TreeView would become available in WASM?

**Comment by MartinZikmund** [comment]
> @MartinZikmund I appreciated your work on that issue. Is there any ETA on when TreeView would become available (in WASM)?

I want to update the code to the latest master on WinUI side. In addition, I think the control uses Items collection for list view, which is currently not in sync with Items Source in Uno, so that could be a problem, that would need to be resolved first.

**Comment by DierkDroth** [comment]
Thanks for the update @MartinZikmund

**Comment by chingucoding** [comment]
Is the [documentation](https://platform.uno/docs/articles/implemented/windows-ui-xaml-controls-treeview.html) for this control up to date? It seems that almost nothing is supported on other platforms.

**Comment by MartinZikmund** [comment]
> Is the [documentation](https://platform.uno/docs/articles/implemented/windows-ui-xaml-controls-treeview.html) for this control up to date? It seems that almost nothing is supported on other platforms. (@MartinZikmund since you implemented it)

This is docs for the Windows.UI version of the control - the Microsoft.UI version is fully supported 👍

**Comment by chingucoding** [comment]
Oh dang I see, awesome to hear it's fully supported, thanks @MartinZikmund ! Would it make sense to point people to the MUXC Treeview given that that is more advanced than the WUXC one?

**Comment by MartinZikmund** [comment]
@chingucoding I think when you attempt to use the WUXC version, you will get a runtime error. On the other hand, the documentation for these WUX controls which are implemented in MUX should be updated, will make an issue for it.
