### ISSUE TITLE
Support development on Mac and Linux

### ISSUE THREAD

**Issue by ILAgent** [unoplatform/uno#2730]
Many people use Mac as a main development station. Do you have any plans to support that?

**Comment by jeromelaban** [comment]
For MacOS, please see #626 for development using VS for Mac, as for Linux, there's a missing piece for the experience to be smoother (XAML Language Service), but runtime support for Linux is being considered.

**Comment by francoistanguay** [comment]
We've published guidance [here](https://platform.uno/docs/articles/get-started.html)
