### ISSUE TITLE
How to add UNO in existing xamarin PCL project

### ISSUE THREAD

**Issue by tusharpawar2585** [unoplatform/uno#2731]
How to add UNO library in existing xamarin PCL project.
I have tried as per document and use command to add UNO. I'm able to add but when I run application then it throws exception that /index.htlm page not found. And if I add UWP project reference in .Wasm project then it will gives .netstadard2.0 error while building app.

**Comment by jeromelaban** [comment]
Thanks for the report. Could you provide with more information, such as the build errors ?

**Comment by tusharpawar2585** [comment]
![15833044588718383037358045747378](https://user-images.githubusercontent.com/22341084/75852519-2f0c9f00-5e12-11ea-9b3f-66612b2cd310.jpg)

**Comment by tusharpawar2585** [comment]
![1583304528374619109074885791512](https://user-images.githubusercontent.com/22341084/75852589-58c5c600-5e12-11ea-923a-8e53d79429fd.jpg)

**Comment by tusharpawar2585** [comment]
![15833045733602035003420554752515](https://user-images.githubusercontent.com/22341084/75852623-6e3af000-5e12-11ea-842e-58bc186d1b80.jpg)

**Comment by tusharpawar2585** [comment]
I have created sample PCL project then I have added Uno using two commands as mentioned in UNO documentation. Then I run application and then I get above screen shot error.

**Comment by tusharpawar2585** [comment]
If I add UWP in .Wasm project then I get below error

Project UnoSample.UWP is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project UnoSample.UWP supports: uap10.0.16299 (UAP,Version=v10.0.16299)

**Comment by tusharpawar2585** [comment]
Can you please help how to add UNO in existing xamarin PCL project created in VS2019. Else can you share one uno project sample using PCL.

**Comment by jeromelaban** [comment]
Does this project work for you: https://github.com/unoplatform/RpnCalculator ?
