### ISSUE TITLE
Add support for the Popup.IsLightDismissEnabled

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#2743]
## What would you like to be added:
[Popup.IsLightDismissEnabled](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.popup.islightdismissenabled)

## Why is this needed:
Light dismiss is broken in Uno:
* https://github.com/unoplatform/uno/issues/2682
* https://github.com/unoplatform/uno/issues/2677
* https://github.com/unoplatform/uno/issues/1950
* https://github.com/unoplatform/uno/issues/1929
* https://github.com/unoplatform/uno/issues/1631

## For which Platform:
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by davidjohnoliver** [comment]
Closing this, `Popup.IsLightDismissEnabled` has been implemented for a while now.
