### ISSUE TITLE
[WASM] Mouse clicks are not working reliably

### ISSUE THREAD

**Issue by gevart** [unoplatform/uno#2749]
## Current behavior

When the Wasm app starts, at first all mouse clicks (both left and right, but hovering is ok) are not working. Then after several failed clicks it suddenly just starts working and after that will work as expected.

## Expected behavior

Mouse clicks should work reliably, as it was with Uno.UI 2.0.324 and lower.

## How to reproduce it (as minimally and precisely as possible)

I managed to reproduce it with forked Uno.QuickStart soluition [here](https://github.com/gevart/Uno.QuickStart) with 3 changes:

- Updated UWP target to Windows 1903 on solution load
- Replaced 'Hello world' TextBlock with a Button which has Clicked event changing it's Content (to show that it's not being called for the first several clicks)
- Updated all Uno NuGet packages to the latest versions

After this I've recorded the video of what's [happening](https://github.com/gevart/Uno.QuickStart/blob/master/UnoWasm.swf?raw=true). This is on Chrome v80.

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.0.512 and later

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.5)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dr1rrb** [comment]
Issue found ... I'm a bit ashamed  ![oups](https://media.giphy.com/media/cjzkCDL3jZTZB6ki1B/giphy.gif "oups")
