### ISSUE TITLE
[iOS] Syncfusion Xamarin.iOS LineChart render issue on first load

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#2752]
## How to reproduce it (as minimally and precisely as possible)

https://github.com/agneszitte-nventive/LineChartRenderIssue

## Current behavior

The Syncfusion Xamarin.iOS LineChart doesn't render properly on first load (even with fixed Height and Width).

## Expected behavior

The LineChart should render properly on all platforms.

## Environment

Nuget Package: Uno.UI 

Package Version(s): 2.0.532

Affected platform(s):

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: 16.4.5)
- [ ] for Mac (version: )

**Comment by agneszitte-nventive** [comment]
As a workaround for now, we can customize the measurement logic of the inner SFChart.

Also we noticed that the page containing the control freezes the App if it's collapsed by adding more logic

**Comment by agneszitte-nventive** [comment]
Related issue : https://github.com/unoplatform/uno/issues/2768

**Comment by davidjohnoliver** [comment]
This issue was resolved by subclassing `SFChart` and overriding the `SizeThatFits()` method:
```
		public override CGSize SizeThatFits(CGSize size)
		{
			base.SizeThatFits(size);
			// Return supplied size, this is called by Uno's measurement logic
			return size;
		}
```

The deeper issue is that Uno assumes, when layouting non-Uno views, that `SizeThatFits()` will return a meaningful value, whereas in practice that isn't always the case. Possibly we should be trying to interpret the constraints system instead.
