### ISSUE TITLE
[Android] FontIcon Doesn't Render Symbol Font

### ISSUE THREAD

**Issue by ahoefling** [unoplatform/uno#2766]
## Current behavior
Using the `Segoe MDL2 Assets` fonts built into UWP doesn't work on Android `FontIcons`. Depending on the use-case the app will crash or show invalid icons.

<details><summary>Screenshot on UWP</summary>

![image](https://user-images.githubusercontent.com/17751436/76246953-17b82200-6215-11ea-90a7-c34e9ba1b93e.png)
</details>

<details><summary>Screenshot on Android</summary>

![image](https://user-images.githubusercontent.com/17751436/76246893-f820f980-6214-11ea-897f-9da5fa54ebfd.png)
</details>

## Expected behavior
I expect the `Segoe MDL2 Assets` to be loaded in Uno Projects by default so you can use the same assets in UWP right out of the box.

This is related to other issues reported to Symbol Icons not working, but the asset file is different:
* Related: #225
* Related: #273
* Related: #1332

This problem is different from the related items as it uses the official `Segoe MDL2 Assets` where the other GitHub issues use the related font `winjs-symbols.ttf#Symbols`. 

## How to reproduce it (as minimally and precisely as possible)
[Uno_Bug_FontIcon.zip](https://github.com/unoplatform/uno/files/4308449/Uno_Bug_FontIcon.zip)

## Workaround
If you install the font manually to the android project you can specify the platform path to the font and everything will work correctly

```xml
<FontIcon android:FontFamily="ms-appx:///Assets/Fonts/SegMDL2.ttf" win:FontFamily="Segoe MDL2 Assets" Glyph="&#xEB51;" Width="50" Height="50" />
```

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.0.532

Affected platform(s):

- [ ] iOS (untested)
- [x] Android
- [ ] WebAssembly (untested)
- [ ] WebAssembly renderers for Xamarin.Forms (untested)
- [ ] macOS (untested)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.2.5)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: N/A)

## Anything else we need to know?
I was able to provide a workaround by downloading the font from the official microsoft docs and adding it to the android project.

* [Microsoft Docs](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font)
* [Font Download](https://aka.ms/SegoeFonts)

**Comment by jeromelaban** [comment]
Thanks for your report, I'll close this issue in favor of https://github.com/unoplatform/uno/issues/3011
