### ISSUE TITLE
[Android] Incorrect UIElement.Measure behavior

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2767]
## Current behavior

Invoking `UIElement.Measure` may not have the same behavior as `UIElement.MeasureElement`.

## How to reproduce it (as minimally and precisely as possible)

TBD

https://dev.azure.com/nventive/Umbrella/_workitems/edit/175789

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
@jeromelaban Is it intentionnally closed??
