### ISSUE TITLE
VS2019 Xaml Designer not showing up for UNO platform

### ISSUE THREAD

**Issue by howardtech** [unoplatform/uno#2772]
I came across an issue I just finished installing the Uno Platform Extensions for VS2019 and when I try to open Xaml designer for MainPage.xaml it says this item does not support previewing. I have the .net core framework 2.2 installed and everything according ot the get started page form the UNO platform site but VS refused to open up designer to see the UI is there a bug or am I missing some references?

**Comment by jeromelaban** [comment]
Thanks for the feedback. This is a known editor issue: https://developercommunity.visualstudio.com/content/problem/587976/xaml-intellisense-does-not-start-properly-on-proje.html you can try the workaround mentioned there.

**Comment by howardtech** [comment]
No problem and thanks for the response unfortunately when I went to the link you provided none of the solutions work the only time I am able to get Xaml Designer and intellesense to work is when I cut the MainPage.Xaml and move it under the UWP head. I thought that it suppose to stay under the share project folder? Is the workaround is to work within the UWP Head and then move it back to share project folder? I have posted/uploaded screenshot below please note the highlighted areas.
<img width="1115" alt="VS1" src="https://user-images.githubusercontent.com/36555116/76475703-27cb2f80-63d6-11ea-99ef-4b2ae95fee86.PNG">
<img width="1120" alt="VS2" src="https://user-images.githubusercontent.com/36555116/76475706-2863c600-63d6-11ea-82a7-60ce8e5c5c4a.PNG">

**Comment by howardtech** [comment]
> Thanks for the feedback. This is a known editor issue: https://developercommunity.visualstudio.com/content/problem/587976/xaml-intellisense-does-not-start-properly-on-proje.html you can try the workaround mentioned there.

No problem and thanks for the response unfortunately when I went to the link you provided none of the solutions work the only time I am able to get Xaml Designer and intellesense to work is when I cut the MainPage.Xaml and move it under the UWP head. I thought that it suppose to stay under the share project folder? Is the workaround is to work within the UWP Head and then move it back to share project folder? I have posted/uploaded screenshot below please note the highlighted areas.
<img width="1115" alt="VS1" src="https://user-images.githubusercontent.com/36555116/76475849-a32ce100-63d6-11ea-8569-1d2623dc54c4.PNG">
<img width="1120" alt="VS2" src="https://user-images.githubusercontent.com/36555116/76475850-a3c57780-63d6-11ea-873b-3b6b049d6552.PNG">

**Comment by jeromelaban** [comment]
For the designer to work, you'll need to select the UWP project at the top, close then reopen the file (the other targets don't have a designer at this time)

**Comment by howardtech** [comment]
HI and thanks for the response i'm a little confused do you mean unload the UWP project?  I tried to unload and reload and I still get the same results. The only workaround that seem to work is to cut/move the MainPage.Xaml file under the UWP Head, edit the app via designer, and then move it back under shared and build the solution for it to reflect across all platform. I tested this out yesterday and it seem to work. I wonder if VS2019 is not understanding that is an Xaml under the Share project folder?

**Comment by jeromelaban** [comment]
You need to select the UWP project here:

![image](https://user-images.githubusercontent.com/5839577/76557321-ba6cdc80-6471-11ea-8339-e99bb9463e54.png)

Then close the file, and reopen it. The designer will then appear.

**Comment by howardtech** [comment]
Ah gotcha that works and thanks for the explanation! Also for the quick response looking forward to exploring this awesome platform that you created I already created a test app using UNO and I love it already :)

**Comment by jeromelaban** [comment]
Thanks! If you have other questions, please do so through StackOverflow: https://stackoverflow.com/questions/tagged/uno-platform

If you find bugs, this is the right place: https://github.com/unoplatform/uno/issues/new/choose

**Comment by howardtech** [comment]
you're welcome and thanks for the links I have bookmarked them :)

**Comment by LeftTwixWand** [comment]
I had the same problem. I had "Uno Platform Solution Templates" extension for Visual Studio installed.
Then I had installed UNO templates for dotnet and create a new project from console. 
And it starts working for me:
**_dotnet new -i Uno.ProjectTemplates.Dotnet
dotnet new unoapp_**

**Comment by sigmarsson** [comment]
@jeromelaban when do you estimte the non-UWP heads can use the xaml designer?

**Comment by sgf** [comment]
UWP is as bad as WPF. UNO relies on UWP, so give up.
