### ISSUE TITLE
[iOS] VisibleBoundsPadding not applied properly after a rotation

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2775]
## Current behavior

Rotating a device when the `VisibleBoundsPadding` is used may lead to an invalid lingering padding.

## Expected behavior

The padding is applied properly when rotating the device.

## How to reproduce it (as minimally and precisely as possible)

TBD
https://dev.azure.com/nventive/Umbrella/_workitems/edit/176714

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeremiethibeault** [comment]
+1 I think I have the same issue when rotating the iOS device. The CommandBar doesn't take into account the applied visible bounds padding.
