### ISSUE TITLE
[DatePicker] functionality for DayVisible, MonthVisible and YearVisible are missing

### ISSUE THREAD

**Issue by XiaotianNetlift** [unoplatform/uno#2780]
# What would you like to be added:
functionality of:
- DatePicker.DayVisible
- DatePicker.MonthVisible
- DatePicker.YearVisible

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?
The `DependencyProperty`-ies themselves are implemented, but their functionality is not.

https://dev.azure.com/nventive/Umbrella/_workitems/edit/30577

**Comment by MartinZikmund** [comment]
This is working now as we support the same feature set as WinUI `DatePicker`.
