### ISSUE TITLE
[IOS] DoubleTap event does not fire

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#2813]
The DoubleTap event does not fire in iOS builds.  Appears to work on all other platforms.  To test, in attached sample project double-tap the green grid - text is updated on all platforms but iOS.

[App30.zip](https://github.com/unoplatform/uno/files/4330567/App30.zip)

Using Uno.UI version 2.2.0-dev.131

**Comment by dr1rrb** [comment]
FYI, this has been broken when I added the support for multi-touch. The pointer ID was the same for all pointers of the same type (finger vs. pen vs. mouse), now they are different for each, but are also different for each press/release sequence (i.e. each time you release the pointer it changes it ID) (cf. https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.iOS.cs#L34). 

I need to figure a way to track them properly (which does seems to be supported on iOS), and if not possible, I'll have to adjust the `GestureRecognizer` specifically for iOS to track only the type of the pointer.

I'll also update the UI test engine to allow tests of double tap to prevent those kind of issue in future updates.
