### ISSUE TITLE
DataContext not inherited in DataTemplate

### ISSUE THREAD

**Issue by Avid29** [unoplatform/uno#2818]
## Current behavior

The child item in a DataTemplate without specified DataContext has no DataContext

## Expected behavior

When a single item is in a DataTemplate, it should automatically get the DataContext for that DataTemplate

## How to reproduce it (as minimally and precisely as possible)

<DataTemplate>
    <ContentControl/>
    
</DataTemplate>

## Environment

UWP

Nuget Package:

Package Version(s): Uno.Core

Affected platform(s): 1.29
- [ ] Windows

Visual Studio:

- [ ] 2019 (version: 16.4.4)

**Comment by jeromelaban** [comment]
Thanks for the report! This is most likely related to #857, I'll close this issue as a duplicate.
