### ISSUE TITLE
[iOS] Animations cancellation is not working properly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2827]
## Current behavior

Canceled animations may cause invalid default states.

## Expected behavior

Canceled animations reset to their proper state.

## How to reproduce it (as minimally and precisely as possible)

https://dev.azure.com/nventive/Umbrella/_workitems/edit/176386

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dr1rrb** [comment]
This has been fixed by https://github.com/unoplatform/uno/pull/6792
