### ISSUE TITLE
Symbol Icon Home not showed in WASM NavigationViewItem

### ISSUE THREAD

**Issue by SERWare** [unoplatform/uno#2834]
## Current behavior

Home Symbol Icon in NavigationItem is showed in UWP but not WASM. Other Symbol Icons (not Home) are showed in both platforms: UWP and Wasm.

## Expected behavior

Home Symbol Icon showed in WASM Platform.

## How to reproduce it (as minimally and precisely as possible)

Show a NavigationView control as Content of Page with several NavigationItem and Home SymbolIcon in one Item.

    <NavigationView>
        <NavigationView.MenuItems>
            <NavigationViewItem Icon="Home">
                <NavigationViewItem Icon="Accept"/>
            </NavigationViewItem>
        </NavigationView.MenuItems>
    </NavigationView>

UWP local machine start will show Home and Accept SymbolIcons. WASM IIS Express start will show Accept SymbolIncon but blank instead of Home SymbolIcon.

Affected platform(s):

(iOS and Android not tested)

- [ ] iOS
- [ ] Android
- [* ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ *] 2017 (15.9.17 )

**Comment by jeromelaban** [comment]
Thanks for the issue. This may be related to Fonts. Could you provide a screenshot of the sample you are using ?

Here's the sample in the playground: https://playground.platform.uno/#5d7156cd

**Comment by SERWare** [comment]
> Thanks for the issue. This may be related to Fonts. Could you provide a screenshot of the sample you are using ?
> 
> Here's the sample in the playground: https://playground.platform.uno/#5d7156cd

I'm testing WASM on Chrome and Microsoft Edge (not yet Chromium version).

NOTE. I'm using Spanish Versions.

WASM Sample with blank instead of Home Icon

![UnoWASMHomeSymbolProblem](https://user-images.githubusercontent.com/12097222/77188495-5e8bfe80-6ad6-11ea-99ec-f41facbfa928.PNG)

UWP Sample showing Home Icon

![UnoUWPHomeSymbolProblem](https://user-images.githubusercontent.com/12097222/77189041-3c46b080-6ad7-11ea-8889-d76c22916fb2.PNG)

**Comment by SERWare** [comment]
Maybe not related but there's another WASM NavigationView problem: Header not shown.

Header in Uno WASM PlayGround:

![UnoWASMPlayGroundHomeHeaderProblem](https://user-images.githubusercontent.com/12097222/77223285-76f22c80-6b5b-11ea-8902-942066083157.PNG)

No Header when IIS Express executed:

![UnoWASMHomeHeaderProblem](https://user-images.githubusercontent.com/12097222/77223294-95f0be80-6b5b-11ea-843b-2b60334024a7.PNG)

**Comment by jeromelaban** [comment]
I see. The font used by Uno is not the same one as the one Microsoft uses in UWP (a license issue),, and that icon may not be as the same character as the others.

It looks like we'll need to make a mapping here:
https://github.com/unoplatform/uno/blob/d10ec0242b0343cf9ca8e35da9917b773d091144/src/Uno.UI/UI/Xaml/Controls/FontIcon/FontIcon.cs#L58

when the [open symbols](https://github.com/microsoft/fonts/tree/master/Symbols) font is used.

**Comment by SERWare** [comment]
> I see. The font used by Uno is not the same one as the one Microsoft uses in UWP (a license issue) and that icon may not be as the same character as original one.
> 
> It looks like we'll need to make a mapping here:
> https://github.com/unoplatform/uno/blob/d10ec0242b0343cf9ca8e35da9917b773d091144/src/Uno.UI/UI/Xaml/Controls/FontIcon/FontIcon.cs#L58
> 
> when the [open symbols](https://github.com/microsoft/fonts/tree/master/Symbols) font is used.

First, simple turnaround that works in WASM: programmatically create the icon with:

`new SymbolIcon(Symbol.Home)`

Do we need to make the mapping as users or will it be included in any Uno library?

Thanks

**Comment by jeromelaban** [comment]
This is an interesting finding. Adding Home explicitly should have the same effect as creating a `SymbolIcon`. This may hide another issue then.

**Comment by SERWare** [comment]
> This is an interesting finding. Adding Home explicitly should have the same effect as creating a `SymbolIcon`. This may hide another issue then.

I don't know... this test is NavigationView generated in code and assigned to Page.Content after InitializeComponent. It shows the Home icon.

![UnoWASMHomeSymbolCodeCreated](https://user-images.githubusercontent.com/12097222/77233624-04a83900-6ba9-11ea-8d83-5995c80e16c6.PNG)

**Comment by kakone** [comment]
**Home** was set as the default symbol in the **SymbolIcon.Symbol** dependency property but the inner **FontIcon.Glyph** property was not set.
The PR fixes this issue, and set the **Emoji** as the default symbol (like in the **SymbolIcon** UWP class).

**Comment by jeromelaban** [comment]
Let's close this issue in favor of https://github.com/unoplatform/uno/issues/3011, as the is original issue for what's mentioned in this one.

**Comment by SERWare** [comment]
Ok, thank you.

**Comment by kakone** [comment]
> Let's close this issue in favor of #3011, as the is original issue for what's mentioned in this one.

I'm not agree, it's not the same problem. As you said : "This may hide another issue then". And it is, there is a bug in the SymbolIcon class.

**Comment by jeromelaban** [comment]
You're right, I'll reopen this issue!
