### ISSUE TITLE
[Android] ListViewItem height may be incorrect

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2835]
## Current behavior

Some ListView content may not have the proper height.

## How to reproduce it (as minimally and precisely as possible)

https://dev.azure.com/nventive/Umbrella/_workitems/edit/177256

## Environment

Nuget Package: 2.1

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
Internal issue couldn't be reproduced with latest packages
