### ISSUE TITLE
[iOS] Button content alignment may be incorrect

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2836]
## Current behavior

Button content alignment may be incorrect, given specific margins and alignments.

## How to reproduce it (as minimally and precisely as possible)

TBD

## Environment

Nuget Package: 2.2

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

https://dev.azure.com/nventive/Umbrella/_workitems/edit/177339

**Comment by carldebilly** [comment]
PR https://github.com/unoplatform/uno/pull/2828 has been merged. Will produce Uno.UI v2.2.0-dev.194 which should be available on Nuget soon there: https://www.nuget.org/packages/Uno.UI/2.2.0-dev.194
