### ISSUE TITLE
Raise UWP target to 18362

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#2840]
## What would you like to be added:

Update UWP target to version 18362.

## Why is this needed:

Referencing `Microsoft.UI.Xaml` from the SamplesApp to use MUX controls.

After done, enable

- MUX RuntimeTests
- XamlRoot runtime test

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Done in 3.0

**Comment by MartinZikmund** [comment]
@jeromelaban while the target in Samples app is raised, the target framework for UWP is 17763 in the libraries. Can this be raised to 18362? It would be very useful as it would allow adding Microsoft.UI.Xaml to Uno.UI.RuntimeTests, so that the API tests could run on UWP too.

**Comment by jeromelaban** [comment]
The samples app should be aligned with the API used by the rest of uno (19041 currently). I recall it was not added because the CI servers did not support it properly at the time, but this may not be the case anymore. Does it work locally ?

**Comment by MartinZikmund** [comment]
@jeromelaban just hit this in #4846 - the `Uno.RuntimeTests` (and some other places in the source) have target framework `uap10.0.17763` so newer APIs like `ActualSize` are not available. Can I raise the `TargetFramework` for these?

**Comment by jeromelaban** [comment]
Sure, that makes sense :)
