### ISSUE TITLE
[macOS] Support for Image

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2844]
##  What would you like to be added:

Add support for `Windows.UI.Xaml.Controls.Image` for macOS.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by ajpinedam** [comment]
Closing issue since PR with the fix was already merged
