### ISSUE TITLE
[Wasm] ProgressBar not working properly

### ISSUE THREAD

**Issue by hampoelz** [unoplatform/uno#2849]
## Current behavior

The ProgressBar only loads up to the value `1921896` (maximum is `12974952`) until the WASM spash screen is changed. (I use latest Pre-Release)

![76168248-36afa900-616e-11ea-9020-f405801f698d](https://user-images.githubusercontent.com/28979769/77151757-f1a54400-6a96-11ea-8e0f-c548ecbb09e3.png)

## Expected behavior

The ProgessBar should load completely. For example like at https://calculator.platform.uno/

![76168260-4a5b0f80-616e-11ea-8eac-4c8b92818cad](https://user-images.githubusercontent.com/28979769/77151772-f9fd7f00-6a96-11ea-9cf1-0b8bf2e1f327.png)

## How to reproduce it (as minimally and precisely as possible)

- Create a new Uno Cross Platform App
- Update Nuget Packages
- Start the wasm project

## Environment

Nuget Package: `Uno.Wasm.Bootstrap`

Package Version(s): `1.1.0-dev.426`

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: -)
- [ ] for Mac (version: )

Relevant plugins:

- [x] Resharper (version: -)

## Anything else we need to know?

I've already created an issue on the Uno.Wasm.Bootstrap GitHub page, but it seems to be dead there ...
https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/176

**Comment by hampoelz** [comment]
Update: Apparently the ProgressBar only loads incorrectly when the configuration is set to Debug in VS

**Comment by MartinZikmund** [comment]
@hampoelz Can you please verify if this is still an issue?
