### ISSUE TITLE
[iOS][Android] ElevatedView does not appear in ContentControl

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2853]
## Current behavior

When you have the control ElevatedView from Uno.UI.Toolkit in a FieldValidationView (ContentControl).
In iOS, the app crashes at start time.
In Android, the control does not appear.

## Expected behavior

The control should be displayed in iOS and Android

## How to reproduce it (as minimally and precisely as possible)

Open the following sample:
[ElevatedViewSample.zip](https://github.com/unoplatform/uno/files/4360997/ElevatedViewSample.zip)

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.2.0-dev.189

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Internal Issue: https://nventive.visualstudio.com/Umbrella/_workitems/edit/168664
iOS crash file: 
[crash-elevatedview-ios.txt](https://github.com/unoplatform/uno/files/4361479/crash-elevatedview-ios.txt)

**Comment by carlh98** [comment]
@carldebilly

**Comment by jeromelaban** [comment]
Can you add the anonymized stack of the exception ?

**Comment by carlh98** [comment]
Thread 0 Crashed:: tid_303  Dispatch queue: com.apple.main-thread
0   com.nventive.parkland             0x000000010ab3cb2c sgen_gchandle_get_target + 12 (sgen-gchandles.c:287)
1   com.nventive.parkland             0x000000010aa3245f mono_gchandle_get_target_handle + 15 (handle.c:417)
2   com.nventive.parkland             0x000000010aa4cd1c ves_icall_System_GCHandle_GetTarget_raw + 60 (icall-def.h:752)
3   ???                               0x000000010fc13ec5 0 + 4559290053
