### ISSUE TITLE
UNO Platform XAML Errors

### ISSUE THREAD

**Issue by aaamirrr2000** [unoplatform/uno#2859]
UNO Platform is giving error "The type 'Page' does not support direct content." and "'MainPage' does not contain a definition for 'InitializeComponent' ...." but running correctly on UWP, Wasm, Android, etc. What is the solution? When this issue will be resolved?

**Comment by jeromelaban** [comment]
Thanks for the report! This is a Visual Studio issue, which will be fixed when the C# Source Generator feature is going to be added. As a workaround, for C# once you have built the project, closing the solution and opening it again will fix the intellisense errors.

For XAML, there is no workaround yet, except setting the editor active project to the UWP project.

You can follow VS related issues here: https://github.com/unoplatform/uno/issues/982
