### ISSUE TITLE
FrameworkElement.DataContextChanged has different signature from UWP

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#2870]
## Current behavior

`DataContextChanged` event has a different signature in Uno than in UWP. If it is not intentional, maybe it could be added to #2240 ?

UWP uses:
```
TypedEventHandler<FrameworkElement, DataContextChangedEventArgs>
```

While Uno has:
```
TypedEventHandler<DependencyObject, DataContextChangedEventArgs>
```

Is this difference intentional?

## Expected behavior

The event handler is the same.

## How to reproduce it (as minimally and precisely as possible)

Attach a DataContextChanged event to page in UWP project head. Notice that other platforms now fail to compile until changed to DependencyObject.

## Environment

Nuget Package: latest

Package Version(s): latest

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Indeed, thanks Martin!

**Comment by ToddGlodek** [comment]
**Workaround**
As suggested by @abrull

I just realized that on Android and iOS in the even handler the sender is DependencyObject and on UWP the sender is FrameworkElement so I just created different event handlers for each platform

I did it like this...
`
public DrawingSurface()
{
this.InitializeComponent();
DataContextChanged += this.DrawingSurface_DataContextChanged;
}

#if WASM
private void DrawingSurface_DataContextChanged(DependencyObject sender, DataContextChangedEventArgs args)
#else
private void DrawingSurface_DataContextChanged(FrameworkElement sender, DataContextChangedEventArgs args)

#endif
{
}

**Comment by jeromelaban** [comment]
Yes, thanks for the update. This is a breaking change that has not been integrated into Uno yet. We're generally batching those as part of larger set of breaking changes so it does not break dependents too often.

**Comment by MartinZikmund** [comment]
Similar difference is for `Loading` event as well
