### ISSUE TITLE
[iOS] The flyout background does not occupy the full space of the screen

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2871]
## Current behavior

The background of the flyout does not occupy the full space of the screen, we can see a white space at the bottom

## Expected behavior

The background of the flyout should occupy the full space of the screen

## How to reproduce it (as minimally and precisely as possible)

Open the sample and click on "Click Me" to show the flyout
Sample: 
[FlyoutPresenter.zip](https://github.com/unoplatform/uno/files/4371514/FlyoutPresenter.zip)

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.2.0-dev.204

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Internal issue : https://nventive.visualstudio.com/Umbrella/_workitems/edit/168937

On Uno.UI 1.45.0, the placement full is not in effect in iOS

**Comment by MatFillion** [comment]
Was fixed in project by using 
`LightDismissOverlayMode="On"` on the Flyout and updating the `FlyoutPresenterStyle` not create a fake dim anymore.

**Comment by Xiaoy312** [comment]
There is still a measure/arrange issue here on ios where the flyout is unable to fully use the entire screen estate. While the background issue can be bypassed with:
- `LightDismissOverlayMode="On"`; and
- `<StaticResource x:Key="FlyoutLightDismissOverlayBackground" ResourceKey="SomeDarkishColor" />`.
I guess this workaround is acceptable for centered flyout, albeit it still centers the content just a little bit higher than it should.

**Comment by Xiaoy312** [comment]
Replaced with #2984. Both of the same nature, but other one has no workaround like this.
