### ISSUE TITLE
WASM NavigationView not displaying Header

### ISSUE THREAD

**Issue by SERWare** [unoplatform/uno#2875]
## Current behavior

NavigationView not displaying Header on WASM IIS executed project.

![UnoWASMHomeHeaderProblem](https://user-images.githubusercontent.com/12097222/77404121-8cf92a80-6db1-11ea-97d0-21a1aa9e518c.PNG)

## Expected behavior

NaviationView displaying Header on Uno Playgrond

![UnoWASMPlayGroundHomeHeaderProblem](https://user-images.githubusercontent.com/12097222/77404167-9da9a080-6db1-11ea-98fb-bd0b51acf4ac.PNG)

## How to reproduce it (as minimally and precisely as possible)

Create and Navigate to:

    <Page
    x:Class="Uno.MainPage" 
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Uno"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <NavigationView Header="HEADER">
        <NavigationView.MenuItems>
            <NavigationViewItem Icon="Add" Content="Add"></NavigationViewItem>
            <NavigationViewItem Icon="Accept" Content="Accept"></NavigationViewItem>
        </NavigationView.MenuItems>
        <TextBlock Text="CONTENT" FontSize="20"></TextBlock>
    </NavigationView>

    </Page>

## Environment

Package Version(s): Last stable

Affected platform(s):

- [ ] iOS
- [ ] Android
- [* ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Works on Windows, not tested iOS, Android, MacOS

Visual Studio:

- [* ] 2017 (version: 15.9.17)
- [ ] 2019 (version: )
- [ ] for Mac (version: )

## Anything else we need to know?

Tested on Spanish idiom Chrome, Edge (pre-chromium version) Navigators

**Comment by jeromelaban** [comment]
Thanks for opening the issue. For some reason, it seems that the NavigationView is hiding the Header, but also not positioning it properly. Adding `AlwaysShowHeader="True"` shows the header.

**Comment by SERWare** [comment]
> Thanks for opening the issue. For some reason, it seems that the NavigationView is hiding the Header, but also not positioning it properly. Adding `AlwaysShowHeader="True"` shows the header.

Ok, It works on Chrome and Edge.

Thank you

**Comment by francoistanguay** [comment]
Should now use the MUX NavView.
