### ISSUE TITLE
[Android] TextBlocks in a StackPanel are cropped when dimensions are changed

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2879]
## Current behavior

TextBlocks in a StackPanel are cropped horizontally or vertically after dimensions are changed

## Expected behavior

TextBlocks in a StackPanel are not cropped when the dimensions are changed

## How to reproduce it (as minimally and precisely as possible)

Press the "Click Me" button multiple times to display the red stackpanel on the right (invisible at start)

Sample: [TextCropped.zip](https://github.com/unoplatform/uno/files/4382466/TextCropped.zip)

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.2.0.dev-256

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Internal issue: 
https://nventive.visualstudio.com/Umbrella/_workitems/edit/177488

**Comment by carldebilly** [comment]
@carlh98 
Cause of the problem has been found and a fix is on the way.  Probably this evening or tomorrow with more details.
