### ISSUE TITLE
[iOS] ScrollViewer are not being implemented AddHandler & RemoveHandler on iOS

### ISSUE THREAD

**Issue by Daoting** [unoplatform/uno#2887]
## Current behavior
`_scrollViewer.AddHandler(PointerPressedEvent, _pressedHandler, true);`
AddHandler & RemoveHandler won't work for events on iOS.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
This may be fixed in the current version of Uno, since ScrollViewer and its public ScrollContentPresenter are now fully managed FrameworkElements. Could you revalidate and let us know?
