### ISSUE TITLE
CommandBar documentation contains private links

### ISSUE THREAD

**Issue by MatFillion** [unoplatform/uno#289]
## I'm submitting a...
Documentation issue

## Current behavior
Multiple links in https://github.com/nventive/Uno/blob/master/doc/articles/working-with-commandbar.md have links to private articles/documentation.

## Expected behavior
All links are working and/or replaced with accessible information

## Minimal reproduction of the problem with instructions
Go to https://github.com/nventive/Uno/blob/master/doc/articles/working-with-commandbar.md and click on links (most are at the end of the document)

**Comment by darenm** [comment]
@agneszitte-nventive I can't find this document in the repo, so this issue may now be moot.

**Comment by jeromelaban** [comment]
Indeed, the [new document](https://github.com/unoplatform/uno/blob/master/doc/articles/controls/CommandBar.md) does not contain such internal links. Thanks for looking this up @darenm !
