### ISSUE TITLE
[iOS][Android][Wasm] The textBox inside ElevatedView is not displayed

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2891]
## Current behavior
The textBox inside the ElevatedView is not displayed.
Also in Wasm, the margin does not work on the right side

## Expected behavior

The textBox inside the ElevatedView is displayed.
In Wasm, the margin works all around the control

## How to reproduce it (as minimally and precisely as possible)

[ElevatedViewSample.zip](https://github.com/unoplatform/uno/files/4389661/ElevatedViewSample.zip)

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.2.0-dev.260

Affected platform(s):

- [x] iOS
- [x] Android
- [ x WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Internal Issue: https://nventive.visualstudio.com/Umbrella/_workitems/edit/168664

**Comment by carldebilly** [comment]
Fix merged in "beta 2.1" and published as Uno.UI v2.1.0-beta.142
