### ISSUE TITLE
OnLoaded and OnUnloaded are protected (breaking change)

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#2897]
## Current behavior

`OnLoaded` and `OnUnloaded` events are currently marked as `protected`

## Expected behavior

`OnLoaded` and `OnUnloaded` events can be `internal` only.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
@jeromelaban This can probably be included in the breaking changes rollup

**Comment by jeromelaban** [comment]
Indeed, thanks Martin!
