### ISSUE TITLE
WASM: "The RunCommand property is not defined"

### ISSUE THREAD

**Issue by MikePelton** [unoplatform/uno#2912]

**Comment by jeromelaban** [comment]
Thanks Mike for opening this issue.

Can you try following these upgrade steps: https://github.com/unoplatform/Uno.Wasm.Bootstrap#upgrading-from-previous-versions-of-the-unowasmbootstrap-package

**Comment by MikePelton** [comment]
Hi Jerome - apologies - I thought I'd abandoned this bug report but some part of it seems to have survived! I was having trouble getting WASM breakpoints to work as per your post of March 30th. I never succeeded but can't put the time in to give you all the info you'd need; as a suggestion (in case anyone else struggles) it might help if you listed the specific versions of the Uno packages your code runs against as it all went wrong for me after I updated those. It's a great project and I look forward to working with it in future!

**Comment by jeromelaban** [comment]
Thanks for the feedback! I'll validate that again to fix it, as it's evolving very quickly :)
