### ISSUE TITLE
[WASM] Add support for IsIndeterminate to ProgressBar

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#2914]
## What would you like to be added:

Indeterminate Progressbar animation for WASM

## Why is this needed:

Many web-based operations rely on a delayed response (like a server response) for which a determinate progressbar is inappropriate.  An indeterminate progressbar would be ideal for such scenarios.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by carldebilly** [comment]
Done in PR https://github.com/unoplatform/uno/pull/3083

**Comment by peternary** [comment]
Confirmed working on latest

**Comment by DierkDroth** [comment]
@jeromelaban, @peternary and I confirmed it's no longer working on iOS nor WASM: there is no animation, instead we just get a "horizontal bar".

@peternary is sure this was working properly in June. 

Is this a regression?
