### ISSUE TITLE
[macOS] Add support for Clipboard

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2915]
## What would you like to be added:
Support for some clipboard operations: https://github.com/unoplatform/uno/tree/b5b72029852d558abc367c54556afed4fdf07ef7/src/Uno.UWP/ApplicationModel/DataTransfer

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

Related #626

**Comment by MartinZikmund** [comment]
This should be on par with other platforms since #2577

**Comment by MartinZikmund** [comment]
Now fully implemented on macOS
