### ISSUE TITLE
[macOS] Add support for WebView

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2916]
## What would you like to be added:
Add support for the `WebView` control

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

Related #626

**Comment by MartinZikmund** [comment]
Have this one in progress.

**Comment by jeromelaban** [comment]
Thanks @MartinZikmund !
