### ISSUE TITLE
`MarkupExtensionReturnType` should not be strict

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#2919]
## Current behavior

Suppose the following XAML Markup extension:

```
[MarkupExtensionReturnType(ReturnType = typeof(int))]
public class FontIcon : MarkupExtension
{
    public string Glyph { get; set; }

    protected override object ProvideValue()
    {
        return new Windows.UI.Xaml.Controls.FontIcon()
        {
            Glyph = Glyph,
            FontFamily = new Windows.UI.Xaml.Media.FontFamily("Segoe UI")
        };
    }
}
```

And refer to it in XAML:

```
xmlns:ex="...."`

<AppBarButton Icon="{ex:FontIcon Glyph=A}" />
```

Although the `MarkupExtensionReturnType` is clearly wrong, UWP does not care and is able to properly compile and run the app. It seems the attribute has mainly "documentation" purpose.

## Expected behavior

Compilation should pass, and the sample should run properly.

## How to reproduce it (as minimally and precisely as possible)

1. Create the XAML extension mentioned above.
2. Attempt to use it.

## Environment

Nuget Package: 3.9

Package Version(s: 3.9

Affected platform(s):

All

**Comment by Youssef1313** [comment]
@MartinZikmund Can you attached a zipped repro please?

The source generator generated the following for me:

```csharp
					new global::Windows.UI.Xaml.Controls.AppBarButton
					{
						IsParsing = true
						,
						// Source ..\..\..\..\..\..\..\Issue2919.Shared\MainPage.xaml (Line 13:10)
					}
					.MainPage_a74593188e9fc804267f506c1c4ad9a7_XamlApply((MainPage_a74593188e9fc804267f506c1c4ad9a7XamlApplyExtensions.XamlApplyHandler1)(c1 => 
					{
						c1.Icon = (Issue2919.FontIcon)((global::Windows.UI.Xaml.Markup.IMarkupExtensionOverrides)(new global::Issue2919.FontIcon {  })).ProvideValue();
												global::Uno.UI.FrameworkElementHelper.SetBaseUri(c1, "file:///C:/Users/PC/Desktop/Repros/Issue2919/Issue2919.Shared/MainPage.xaml");
						c1.CreationComplete();
					}
					))
					,
```

It's a compile-time error since return type `FontIcon` doesn't match the type of `AppBarButton.Icon` (`
Windows.UI.Xaml.Controls.IconElement`) which I assume is expected.

**Comment by MartinZikmund** [comment]
@Youssef1313 updated description with the actual bug issue 👍

**Comment by Youssef1313** [comment]
Thanks. Will work on it now :)

**Comment by Youssef1313** [comment]
Fixing in #6695. Thanks again for the clarification @MartinZikmund
