### ISSUE TITLE
[UWP] The controls inside the ElevatedView are not displayed

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2924]
## Current behavior

The TextBox and the Grid inside the ElevatedView are not displayed

## Expected behavior
The TextBox and the Grid inside the ElevatedView are displayed

## How to reproduce it (as minimally and precisely as possible)
Open the sample:
[ElevatedViewSample.zip](https://github.com/unoplatform/uno/files/4428848/ElevatedViewSample.zip)

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.2.0-dev.374

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Internal issue:
https://nventive.visualstudio.com/Umbrella/_workitems/edit/168664

PS:
The controls are displayed in iOS, Android and Wasm

**Comment by MatFillion** [comment]
Regressed with Uno 2.4 or 3.0. Was working fine in 2.3

**Comment by carlh98** [comment]
Issue is solved with 3.0.0-dev.414
