### ISSUE TITLE
Create a branded icon for Uno app template

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#2934]
## What would you like to be added:

The default Uno Platform app solution template generates apps with generic Android, iOS, WASM icons. It would be nice to have a branded experience.

For example: 

![image](https://user-images.githubusercontent.com/1075116/78462345-62707100-76d1-11ea-99c6-35aff1472eac.png)

## Why is this needed:

First user experience & coolness factor!

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by Youssef1313** [comment]
@MartinZikmund Is this fixed now?

![image](https://user-images.githubusercontent.com/31348972/128390719-475060ba-f101-46b1-9897-5ac095119fe9.png)

**Comment by MartinZikmund** [comment]
@Youssef1313 no, unfortunately not - while the template itself has an icon in the VS dialog, this issue is to track a default icon for the generated apps themselves (e.g. Android app icon, iOS app icon, etc.). I have asked @sasakrsmanovic to check whether the graphics could provide us some nice icons for this purpose 🙂

**Comment by sasakrsmanovic** [comment]
Here it is attached @MartinZikmund 
[Uno_App_Icon.zip](https://github.com/unoplatform/uno/files/7035014/Uno_App_Icon.zip)
