### ISSUE TITLE
Uno take some WS requests with wrong ip address

### ISSUE THREAD

**Issue by MikiraSora** [unoplatform/uno#2960]
Uno take some WS requests with wrong ip address.

## Current behavior

![image](https://user-images.githubusercontent.com/7549173/78800323-e4bca600-79ed-11ea-9b95-a2685f3e0f6f.png)
![image](https://user-images.githubusercontent.com/7549173/78800368-f43bef00-79ed-11ea-879e-d1b938a5292f.png)

## How to reproduce it (as minimally and precisely as possible)
Switch to WASM target project . Build and Run.

## Environment

ipconfig:
```
PS C:\Users\MikiraSora> ipconfig

Windows IP 配置


以太网适配器 以太网 6:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

以太网适配器 以太网 7:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

以太网适配器 以太网 8:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

以太网适配器 以太网 9:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

以太网适配器 VirtualBox Host-Only Network #3:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::bd0e:3a7e:3755:5945%12
   IPv4 地址 . . . . . . . . . . . . : 192.168.166.2
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . :

无线局域网适配器 本地连接* 1:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

无线局域网适配器 本地连接* 13:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

无线局域网适配器 本地连接* 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

以太网适配器 VMware Network Adapter VMnet1:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::30df:7976:d2d7:1456%7
   IPv4 地址 . . . . . . . . . . . . : 192.168.28.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . :

以太网适配器 以太网:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::d1f4:19d8:8e98:2ed0%34
   IPv4 地址 . . . . . . . . . . . . : 192.168.0.105
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.0.1

无线局域网适配器 WLAN:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
PS C:\Users\MikiraSora>
```

Package Version(s):
![image](https://user-images.githubusercontent.com/7549173/78801129-d6bb5500-79ee-11ea-8d6b-f2ecd4b2dd70.png)

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thank you for your report. This is an expected behavior, generated by the "RemoteControl" component, used for the HotReload feature. Browsers connectivity features are somehow limited, and it's necessary to try and reach the available addresses of the machine to connect to it.
