### ISSUE TITLE
[macOS] RenderTransforms are not applied on initial load

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#2971]
## Current behavior

`UIElement` with `RenderTransform` declared in XAML initially shows up without any transform. Any change then applies the transform.

## Expected behavior

Transforms should be applied immediately.

## How to reproduce it (as minimally and precisely as possible)

Samples app Transform sample Basic_Automated.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
I have spend over an hour on this but without success so far :-( . Maybe someone will be more lucky. The problem is probably the same as [here](https://stackoverflow.com/questions/33868943/calayer-transform-doesnt-apply-if-nsview-isnt-created-yet-at-the-moment). Unfortunately even putting a "re-initialization" step within DidMoveToSuperview did not do the trick, whereas adding any small delay (Task.Delay) before the operation had fixed the problem.

**Comment by MartinZikmund** [comment]
@dr1rrb Am I assuming correctly that your PR fixes this issue?

**Comment by dr1rrb** [comment]
Yes @MartinZikmund , I didn't saw this issue, it has been fixed by https://github.com/unoplatform/uno/pull/3759. Even if I'm not really satisfied by the code, it seems that we don't have any other options on macOS, so I'm closing this issue.
