### ISSUE TITLE
After upgrading NuGet Packages, unable to start UNO WASM project.

### ISSUE THREAD

**Issue by TonyHenrique** [unoplatform/uno#2974]
## Current behavior

After upgrading NuGet Packages, unable to start UNO WASM project.
![image](https://user-images.githubusercontent.com/6307623/79084494-7425ca00-7d0a-11ea-9289-475f6009bafa.png)

## Expected behavior

The application should run.

## How to reproduce it (as minimally and precisely as possible)

I installed Uno Platform Solution Templates from Visual Studio -> Extensions, then ran it a few times. Then I upgraded the NuGet packages, then the Project does not start anymore.

## Environment

Nuget Package:

Package Version(s):
Microsoft.Extensions.Logging.Console
1.1.1

Microsoft.Extensions.Logging.Filter
1.1.1

NETStandard.Library
2.0.3

Uno.UI
2.1.37

Uno.UI.RemoteControl
2.1.37

Uno.Wasm.Bootstrap
1.2.0-dev.18

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ X ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ X ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Can you validate that your also have the `Uno.Wasm.Bootstrap.Dev` package installed, and that you have removed the `Uno.Wasm.Bootstrap.Cli` package reference ?

**Comment by TonyHenrique** [comment]
The Uno.Wasm.Bootstrap.Dev package is not installed. (I can not find it) . What I have installed is Uno.Wasm.Bootstrap 1.2.0-dev.18

I did not remove the Uno.Wasm.Bootstrap.Cli . It is not present.

![image](https://user-images.githubusercontent.com/6307623/79088633-89eebb80-7d19-11ea-86ea-b089bc45f23b.png)

![image](https://user-images.githubusercontent.com/6307623/79088700-be627780-7d19-11ea-8df5-20c7be6c2b9e.png)

**Comment by jeromelaban** [comment]
Make sure to follow those steps: https://github.com/unoplatform/Uno.Wasm.Bootstrap#upgrading-from-previous-versions-of-the-unowasmbootstrap-package. The DevServer package is https://www.nuget.org/packages/Uno.Wasm.Bootstrap.DevServer/1.2.0-dev.18

**Comment by TonyHenrique** [comment]
Hey, after I installed **Uno.Wasm.Bootstrap.DevServer** 1.2.0-dev.18  it worked! 
(Please update the *Uno Platform Solution Templates* with the latest versions, so this does not happen to beginners)

**Comment by jeromelaban** [comment]
Beginners generally don't update to latest dev packages. I see that you have stable packages for the rest, why did you update this one to pre-release ?

**Comment by TonyHenrique** [comment]
I installed the Uno Platform Solution Templates extension, created a new project.
I have the habit to Manage Nuget Packages for Solution, select all, Update.

![image](https://user-images.githubusercontent.com/6307623/79090017-afca8f00-7d1e-11ea-8ec0-5f0b0ecce488.png)

Then got those installed, but was missing the Uno.Wasm.Bootstrap.DevServer, which I installed after following the instructions you gave me on this issue.
![image](https://user-images.githubusercontent.com/6307623/79090065-d688c580-7d1e-11ea-9fff-a7b50a086277.png)

**Comment by jeromelaban** [comment]
I see. In the last stable release of the vsix, the bootstrap package is version 1.0.5, is that the one you get when creating a new app from the templates?

**Comment by TonyHenrique** [comment]
I got it following these instructions:
https://platform.uno/docs/articles/get-started.html
It came from the Extensions manager inside Visual Studio.

I did not download the stable release of the vsix from here. I can do that if you ask.
