### ISSUE TITLE
Under WASM a transparent rectangle is displayed as black.

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#2982]
## Current behavior

The rectangle is displayed with a black fill.

## Expected behavior

A transparent rectangle with no border should be effectively invisible.

## How to reproduce it (as minimally and precisely as possible)

Reproduced in a sample project here:
https://github.com/BrianDT/UnoGeometryIssues

## Environment

Nuget Package: 
Uno.UI
Package Version(s):
2.2.0-dev.445
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dr1rrb** [comment]
Yep, I fixed the same bug for `Fill=Null` : https://github.com/unoplatform/uno/pull/2692/files#diff-25e28283e04aa43d10d70dbd0e5f1610R98

But here we should fall in [the `SolidColorBrush` case](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Shapes/Shape.wasm.cs#L83) which was edited for the last time when you changed the color encoding: https://github.com/unoplatform/uno/commit/018dcdd733e6d4169ba688cecf5a9a01ba2fc8c4

So yes it sound familiar, but no I don't have idea ... I'll try to look at it while I'm working on shapes.

**Comment by dr1rrb** [comment]
I'm not sure where the black `Rectangle` should appear (tried with Uno 2.2.0-dev.445 (the version when this bug has been opened); 2.4; and latest 3.1.0-dev.115: I was not able to get it on any version)

But as the application behaves as UWP (except for the resizing issue #2983 when I clikc the `Click Me` button), I assume the issue has been fixed.

![image](https://user-images.githubusercontent.com/8635919/91370600-c6104d80-e7dc-11ea-9ae7-c5ead337d9b5.png)

If you still encounter an issue, feel free to re-open it.
