### ISSUE TITLE
does support scan QRCode ?

### ISSUE THREAD

**Issue by BenDerPan** [unoplatform/uno#2991]
## What would you like to be added:
I can use CameraCaptureUI to capture picture now, but I must click the system taking picture button to take a picture, can I skip this step, just get the picture by code when we need to scan a qrcode? 

#### my test code:
```C#
                var captureUI = new CameraCaptureUI();
                captureUI.PhotoSettings.Format = CameraCaptureUIPhotoFormat.Jpeg;
                captureUI.PhotoSettings.CroppedSizeInPixels = new Size(200, 200);

                var photo = await captureUI.CaptureFileAsync(CameraCaptureUIMode.PhotoOrVideo);
```
## For which Platform:

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Windows

**Comment by jeromelaban** [comment]
At this point, Uno does not support something else but this capture mode.

If you want to decode QR codes, you may want to use native libraries such as zxing https://devblogs.microsoft.com/xamarin/barcode-scanning-made-easy-with-zxing-net-for-xamarin-forms/

**Comment by mokhtarsoholi** [comment]
hi i am using zxing in xamarin but its not worked in wasm 
![image](https://user-images.githubusercontent.com/20678483/97846671-96f9e900-1d03-11eb-8ffd-ebd2df9e83e3.png)

**Comment by jeromelaban** [comment]
@mokhtarsoholi ZXing is not supported under wasm at this point.

**Comment by mokhtarsoholi** [comment]
So how we can scan qr code in unoplatform

**Comment by jeromelaban** [comment]
@mokhtarsoholi this is a question for StackOverflow, would you mind asking it there: https://stackoverflow.com/questions/tagged/uno-platform Thanks !
