### ISSUE TITLE
Unable to update a styled dependency property during ApplyTemplate 

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2993]
## Current behavior

When the WCT LayoutTransformControl is using in a templated control, the following property assignment gets ignored :

https://github.com/unoplatform/Uno.WindowsCommunityToolkit/blob/92ec334a631684d6793af8935c0f2c7bb401f6ad/Microsoft.Toolkit.Uwp.UI.Controls/LayoutTransformControl/LayoutTransformControl.cs#L81 

The precedence override gets set to ImplicitStyle, forcing the value to keep its currently assigned local value.

## Expected behavior

The property can be set properly.

## How to reproduce it (as minimally and precisely as possible)

Use the `ExpanderControl` WCT sample (without the workaround at the end of the `OnApplyTemplate` method).

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Related to #119

**Comment by davidjohnoliver** [comment]
Should have been fixed by https://github.com/unoplatform/uno/pull/3405
