### ISSUE TITLE
[Android] `ScrollBar` in `MouseIndicator` mode does not appear properly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#3009]
## Current behavior

Selecting a `ScrollBar` thumb in `MouseIndicator` mode fails to show the thumb properly.

## How to reproduce it (as minimally and precisely as possible)

See the `UnoSamplesTests_ScrollBar.ScrollBar_HorizontalThumb` UI test.

## Environment

Nuget Package:

Package Version(s): 2.2-dev

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dr1rrb** [comment]
Still an issue with Uno 4.0.11

**Comment by ramezgerges** [comment]
This doesn't reproduce for me.
