### ISSUE TITLE
ToggleMenuFlyoutItem is not rendered

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#3012]
## Current behavior
At least in context:
`<Page><Grid><<StackPanel><AppBarButton><AppBarButton.Flyout><MenuFlyout><ToggleMenuFlyoutItem` , ToggleMenuFlyoutItem is not rendered.
But MenuFlyoutItem is rendered correctly.

## Expected behavior
ToggleMenuFlyoutItem working - as in 2.1.0-dev.945.

## How to reproduce it (as minimally and precisely as possible)

    <Page
    x:Class="KrakTram.Odjazdy"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:KrakTram"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:win="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:not_win="http://uno.ui/not_win"
    mc:Ignorable="d not_win" Loaded="Page_Loaded" >
    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <Grid.RowDefinitions>
            <RowDefinition Height="*" />
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>
        <not_win:Grid Grid.Row="1" Name="uiAndroBottom" Margin="0,10,0,0">
            <StackPanel Orientation="Horizontal" >
                <AppBarButton Icon="Sort" Label="Sort" >
                    <AppBarButton.Flyout>
                        <MenuFlyout>
                            <MenuFlyoutItem Text="not toggle"  />
                            <ToggleMenuFlyoutItem x:Name="uiSortLine" Text="byLine" IsChecked="True"/>
                        </MenuFlyout>
                    </AppBarButton.Flyout>
                </AppBarButton>
            </StackPanel>
        </not_win:Grid>
    </Grid>
    </Page>

## Environment

Nuget Package: 2.1.37

Package Version(s):

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by pkar70** [comment]
Is there any hopes for correcting this problem?

**Comment by MartinZikmund** [comment]
Will check this

**Comment by jeromelaban** [comment]
Don't, I have an update pending for this, build has delayed it.

**Comment by MartinZikmund** [comment]
Ok ✅

**Comment by pkar70** [comment]
For #3151 also? :)
