### ISSUE TITLE
Support ms-appx-web: URIs in WebView

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3024]
## What would you like to be added:

`ms-appx-web` can be used to reference package files from WebView control in UWP.

## Why is this needed:

Better feature parity.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by carldebilly** [comment]
This is a duplicate of https://github.com/unoplatform/uno/issues/2998  --- closing.
