### ISSUE TITLE
Tooltip `DataContext` is not propagated properly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#3028]
## Current behavior

The datacontext of the host of the ToolTip does not propagate the value properly.

## How to reproduce it (as minimally and precisely as possible)

https://playgroundcanary.z19.web.core.windows.net/#ccd0d76f

```xaml
<Button Content="{Binding}">
  <ToolTipService.ToolTip>
    <ToolTip Content="{Binding}" Width="350" Height="60"/>
  </ToolTipService.ToolTip>
</Button>
```

## Workaround

Forwarding the `DataContext` manually using an ElementName can be used as a workaround:

```xaml
<Button Content="Test"  x:Name="buttonTest">
  <ToolTipService.ToolTip>
    <ToolTip DataContext="{Binding DataContext, ElementName=buttonTest}" Content="{Binding message}" Width="350" Height="60"/>
  </ToolTipService.ToolTip>
</Button>
```
## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by ramezgerges** [comment]
This looks fixed to me.

```xaml
	<Button x:Name="btn" Content="{Binding}" DataContext="button DC">
		<ToolTipService.ToolTip>
			<ToolTip x:Name="tt" Content="{Binding}" Width="350" Height="60"/>
		</ToolTipService.ToolTip>
	</Button>
```

![image](https://github.com/unoplatform/uno/assets/66218781/0c6545b1-033e-428e-9d84-d6e15fcadf4f)

I also tried setting the DataContext in the code behind instead of directly in the xaml. Still works.
