### ISSUE TITLE
Expander don't work on Droid

### ISSUE THREAD

**Issue by p4r4d0xNL** [unoplatform/uno#3030]
## Current behavior

On Android Builds the Expander has no function. It won't display correct and you can't do anything with it. On UWP everything is fine. 

## Expected behavior

Expanding, collapse, show Content and Title. 

## How to reproduce it (as minimally and precisely as possible)

New Uno Platform Project. Insert the XAML Sample from UWP Toolkit UWP and run it on Android with the current developement Nuget Paket of Uno.Toolkit.Uwp.UI.Controls. 

    <Grid Background="Black">
        <ScrollViewer>
            <StackPanel Margin="20">
                <controls:Expander x:Name="Expander1" VerticalAlignment="Top" Margin="0,0,0,10"
                           Header="This is the header - expander 1"
                           HorizontalContentAlignment="Stretch"
                           IsExpanded="False"
                           ExpandDirection="Down">
                    <Grid>
                        <TextBlock HorizontalAlignment="Center"
                       TextWrapping="Wrap"
                       Text="This is the expanded content"
                       VerticalAlignment="Center" />
                    </Grid>

                    <controls:Expander.ContentOverlay>
                        <Grid Height="120">
                            <TextBlock Text="This is the content overlay"
                         HorizontalAlignment="Center"
                         VerticalAlignment="Center" />
                        </Grid>
                    </controls:Expander.ContentOverlay>
                </controls:Expander>

                <controls:Expander x:Name="Expander2" VerticalAlignment="Top" Margin="0"
                           Header="This is the header - expander 2"
                           HorizontalContentAlignment="Stretch"
                           IsExpanded="True"
                           ExpandDirection="Right">
                    <Grid Height="256"
                Background="Green">
                        <TextBlock HorizontalAlignment="Center"
                       TextWrapping="Wrap"
                       Text="This is the expanded content without a content overlay"
                       VerticalAlignment="Center"
                       Foreground="Violet" />
                    </Grid>
                </controls:Expander>
            </StackPanel>
        </ScrollViewer>
    </Grid>

## Environment

Uno.Core => v2.0.0-dev.7
Uno.Microsoft.Toolkit.Uwp.UI.Controls => v6.1.0.-build.71.g38c59ea2a0
Uno.UI => v2.3.0-dev.2
Uno.UI.RemoteControl => v2.3.0-dev.2
Uno.UniversalImageLoader => v1.9.32
Uno.Wasm.Bootstrap => v1.2.0-dev.24
NETStandard.Library => v2.0.3
Microsoft.NETCore.UniversalWindowsPlatform => v6.2.10
Microsoft.Extensions.Logging.Filter v1.1.2
Microsoft.Extensions.Logging.Console => v1.1.1

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version:  16.5.4)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

**Comment by francoistanguay** [comment]
Isn't this working now and should be closed?

**Comment by MartinZikmund** [comment]
This should be working using the WinUI Expander.
