### ISSUE TITLE
Uno Platform Solution Templates extension cause VS to not load extensions

### ISSUE THREAD

**Issue by yowl** [unoplatform/uno#3037]
## Current behavior

Load a solution and VS never completes the background tasks.  Some solutions are ok but e.g. https://github.com/dotnet/corert/ exhibits the problem.

![image](https://user-images.githubusercontent.com/2720041/80011344-5cc8a880-8491-11ea-8caa-1a39c12ab315.png)

## Expected behavior

Extension should load

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ x] Windows
- [ ] Build tasks
- [ x] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ x] 2019 (version: 16.5.4)
- [ ] for Mac (version: )

Relevant plugins:

- [ x] Resharper (version: 2020.1)

**Comment by jeromelaban** [comment]
This could be related to nuget packages, the Uno extension waits for packages to be loaded to analyze if it needs to do something.

**Comment by yowl** [comment]
Could be, not sure how I can tell if that is the case.

**Comment by jeromelaban** [comment]
That solution is a very large one, so that could be related. That can ease the reproduction.

**Comment by yowl** [comment]
LOL  You should open LLVM, it has 579 projects

**Comment by francoistanguay** [comment]
Closing this for now. @yowl , please let us know if you still experience something similar with the latest & greatest.
