### ISSUE TITLE
TextBlock: Run Inlines not rendered within Span

### ISSUE THREAD

**Issue by bricelam** [unoplatform/uno#3041]
## Current behavior

This XAML...
```xml
<TextBlock><Span>Where <Italic>did</Italic> my text go?</Span></TextBlock>
```
...renders like this on Android, iOS, and WASM:

![image](https://user-images.githubusercontent.com/1226749/80056007-02066f80-84d8-11ea-806d-979387dae990.png)

## Expected behavior

It should look the same as UWP:

![image](https://user-images.githubusercontent.com/1226749/80056087-3a0db280-84d8-11ea-81df-b9767a483357.png)

## How to reproduce it (as minimally and precisely as possible)

1. Copy XAML fragment into a new Uno project
2. Run

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.3.0-dev.7

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] (***untested***) WebAssembly renderers for Xamarin.Forms
- [ ] (***untested***) macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.6 Preview 3)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Only `<Run>` items seem to be affected. `<Bold>`, `<Underline>`, and `<Italic>` are all preserved.

**Comment by bricelam** [comment]
Oh funny, adding it programmatically after InitializeComponent works.
```cs
textBlock1.Inlines.Add(
    new Span
    {
        Inlines =
        {
            new Run{Text = "Where "},
            new Italic
            {
                Inlines =
                {
                    new Run { Text = "did" }
                }
            },
            new Run { Text = " my text go?"}
        }
    });
```
Result:

![image](https://user-images.githubusercontent.com/1226749/80057881-8e1a9600-84dc-11ea-8c89-79a9e9f316ec.png)

**Comment by bricelam** [comment]
Looks like an issue in the parser. This code...
```cs
var span = (Span)XamlReader.Load(
    "<Span xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\">Where <Italic>did</Italic> my text go?</Span>");
textBlock1.Inlines.Add(span);
```
...renders a bit more:

![image](https://user-images.githubusercontent.com/1226749/80058376-f0c06180-84dd-11ea-86c9-6ef8045e0b8f.png)

**Comment by davidjohnoliver** [comment]
Thanks for the investigation! Indeed as you identified this is a parser problem, specifically a limitation of the Xaml parser we're currently using which doesn't handle the nested tags.

The workaround for the moment is to define all the `Inlines` explicitly:
```xaml
<TextBlock><Run>Where </Run> <Italic>did</Italic> <Run> my text go?</Run></TextBlock>
```
