### ISSUE TITLE
[XAML] ConverterParameter with string literal is not parsed properly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#3049]
## Current behavior

The following XAML does not get generated properly:

```xaml
<TextBlock Text="{x:Bind Item.StartedAt,Converter={StaticResource StringFormatConverter},ConverterParameter='Started: {0:MMM dd, yyyy hh:mm tt}',Mode=OneWay}" />
```

where the ConverterParameter does not get parsed properly and is concatenated to the paramaterless group of a binding.

## Environment

Nuget Package: 2.2.0

**Comment by TheRusstler** [comment]
A note which might be helpful.

After updating to Uno 2.2, on iOS the ConverterParameter appears to produce additional unicode left/right arrow `↔` characters at the start and end of the string. 

For example: `ConverterParameter='MyParameter'` produces "↔MyParameter↔" to the converter

**Comment by jeromelaban** [comment]
Indeed, the unicode character is supposed to be used as a workaround for xbind parsing , but the ConverterParameter reader does not remove it properly. Thanks for the update!
