### ISSUE TITLE
WASM: Flow URL into OnActivated

### ISSUE THREAD

**Issue by bricelam** [unoplatform/uno#3053]
## What would you like to be added:

I'd love to be able to access the URL that was used to serve the WASM app. Ideally, the same code could be used for both WASM and UWP.

```cs
public partial class App
{
    protected override void OnActivated(IActivatedEventArgs args)
    {
        if (args.Kind == ActivationKind.Protocol)
        {
            var url = ((ProtocolActivatedEventArgs)args).Uri;
            // TODO: Process URL
        }
    }
}
```

## Why is this needed:

My primary goal here is to handle OpenID Connect callbacks (and I have no idea what I'm doing), but this functionality is generally useful for all web applications--even Uno Playground leverages URLs.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

'Nuff said.

**Comment by bricelam** [comment]
Looks like the query string is already available via `LaunchActivatedEventArgs.Arguments`.

**Comment by jeromelaban** [comment]
Thanks for the report! Indeed, the playground uses this:

https://github.com/unoplatform/Uno.Playground/blob/1197f6956da8c8a9df86cfe4c949ee632bd8100d/src/Uno.Playground.WASM/FragmentHavigationHandler.cs

To handle fragments, which should be somehow included in Uno to support this scenario.

**Comment by bricelam** [comment]
So it turns out that serving the app from arbitrary URLs is not a good idea. 🙂 All the asset paths get messed up and the app fails to load. It could probably be made to work, but just using a query string parameter (`/?action=login-callback`) was much easier.

**Comment by MartinZikmund** [comment]
This can be closed for now, as query strings are supported and protocol activation is also available 🚀
