### ISSUE TITLE
[iOS/Droid]Border is incorrectly rendered with partial CornerRadius and partial BorderThickness 

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#3071]
## Current behavior

Border is incorrectly rendered with partial CornerRadius and partial BorderThickness:
- android: ![image](https://user-images.githubusercontent.com/2359550/80422292-eb7f6000-88ab-11ea-94db-41967a7f0e19.png)
- ios: ![image](https://user-images.githubusercontent.com/2359550/80422257-defb0780-88ab-11ea-94ad-e85a07126669.png)

## Expected behavior

Border should render correctly with partial CornerRadius and partial BorderThickness:
- uwp: ![image](https://user-images.githubusercontent.com/2359550/80422430-22557600-88ac-11ea-98b7-c26d2f7112d2.png)
- wasm: ![image](https://user-images.githubusercontent.com/2359550/80422391-123d9680-88ac-11ea-8da4-33315157afe5.png)

## How to reproduce it (as minimally and precisely as possible)
```
	<Page.Resources>
		<Style x:Key="MaterialTextBoxStyle"
			   TargetType="TextBox">
			<Setter Property="MinHeight" Value="64" />
			<Setter Property="Template">
				<Setter.Value>
					<ControlTemplate TargetType="TextBox">
						<Grid>
							<Grid.ColumnDefinitions>
								<ColumnDefinition Width="32" />
								<ColumnDefinition Width="Auto" />
								<ColumnDefinition Width="*" />
							</Grid.ColumnDefinitions>
							<!-- . ╭─ Label          Label ──╮      Label        ╭─ Label ──╮ -->
							<!-- . │ Content    +   Content  │ + │ Content  │ => │ Content  │ -->
							<!-- .                               ╰──────────╯    ╰──────────╯ -->
							<!-- Top Left, Top Right, Bottom Half borders:-->
							<Border Grid.Column="0" BorderBrush="Black" Margin="8,8,0,24" BorderThickness="1,1,0,0" CornerRadius="16,0,0,0" />
							<Border Grid.Column="2" BorderBrush="Black" Margin="0,8,8,24" BorderThickness="0,1,1,0" CornerRadius="0,16,0,0" />
							<Border Grid.Column="0" Grid.ColumnSpan="3" BorderBrush="Black" Margin="8,24,8,8" BorderThickness="1,0,1,1" CornerRadius="0,0,16,16" />
							<!--<Border Grid.Column="0" BorderBrush="Black" Margin="8,8,0,24" BorderThickness="1,1,0,0" CornerRadius="0,0,0,0" />-->
							<!--<Border Grid.Column="2" BorderBrush="Black" Margin="0,8,8,24" BorderThickness="0,1,1,0" CornerRadius="0,0,0,0" />-->
							<!--<Border Grid.Column="0" Grid.ColumnSpan="3" BorderBrush="Black" Margin="8,24,8,8" BorderThickness="1,0,1,1" CornerRadius="0,0,0,0" />-->

							<ContentPresenter x:Name="HeaderContentPresenter" Grid.Row="0" Grid.Column="1" Margin="8,0"  
											  Content="{TemplateBinding Header}"
											  ContentTemplate="{TemplateBinding HeaderTemplate}"/>
							<ScrollViewer x:Name="ContentElement" Grid.Column="0" Grid.ColumnSpan="3" Margin="16" />
						</Grid>
					</ControlTemplate>
				</Setter.Value>
			</Setter>
		</Style>
	</Page.Resources>

	<StackPanel Background="{ThemeResource ApplicationPageBackgroundThemeBrush}" Margin="0,100,0,0">
		<TextBox Header="this is header"
				 Text="ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh"
				 PlaceholderText="placeholder text"
				 Style="{StaticResource MaterialTextBoxStyle}" />
	</StackPanel>
```

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.2.0

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Nice solution! Indeed this is not working well :)

**Comment by agneszitte-nventive** [comment]
Closing this issue as it's fixed with latest Uno dev versions (tested with **4.2.0-dev.205**)
Border is now correctly rendered with partial CornerRadius and partial BorderThickness like for UWP.
![image](https://user-images.githubusercontent.com/16295702/156643865-37173a86-2f1f-4528-8dc2-00bff23b3bbe.png)
(cc @jeromelaban)
