### ISSUE TITLE
Support for BadgeNotification

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3080]
## What would you like to be added:

Support for numeric badge notifications

## Why is this needed:

UWP feature

## For which Platform:

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

Android and WASM don't have such API

**Comment by NGame1** [comment]
Android
![image](https://user-images.githubusercontent.com/19765248/90295414-31cdee80-de9e-11ea-86e3-43b962e0b3a7.png)

https://developer.android.com/training/notify-user/badges
