### ISSUE TITLE
Add support for Microsoft.UI.Xaml NuGet package

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3085]
## What would you like to be added:

Uno support for Microsoft.UI.Xaml NuGet package.

## Why is this needed:

The Windows UI Library contains new and updated controls that are desirable in an Uno application.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
This is already in progress :-) . Once WinUI 3 hits open-source, many additional controls will be added as well!

**Comment by MartinZikmund** [comment]
This can be closed, we are adding up-to-date support for WinUI as we go. If you require a specific control, please create an issue and we will track it 🎉
