### ISSUE TITLE
[macOS] Add support for MediaPlayer

### ISSUE THREAD

**Issue by ajpinedam** [unoplatform/uno#3091]
## What would you like to be added:
MediaPlayer support

## Why is this needed:
Feature parity

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
@ajpinedam I have already an open PR for this - https://github.com/unoplatform/uno/pull/3021

**Comment by ajpinedam** [comment]
Thanks @MartinZikmund ! Will close this one. Also updated #626  with your ticket :)
