### ISSUE TITLE
SharedAssets.md - @(Content) build action is not supported

### ISSUE THREAD

**Issue by scottkuhl** [unoplatform/uno#3095]
## Current behavior

The default template produces a warning on the Droid project.

@(Content) build action is not supported	... Shared\Assets\SharedAssets.md		

## Environment

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

## Anything else we need to know?

You can fix the issue by changing the build action on SharedAssets.md from Content to None.

**Comment by jeromelaban** [comment]
Thanks for the report! 

This is an quick change that can be done here: 

https://github.com/unoplatform/uno/blob/4332fdcc719abd986cec8e9963c585fd96409e21/src/SolutionTemplate/UnoSolutionTemplate/Shared/UnoQuickStart.Shared.projitems#L32
