### ISSUE TITLE
Replace winjs-symbols.ttf with Fluent UI Icons

### ISSUE THREAD

**Issue by scottkuhl** [unoplatform/uno#3096]
## What would you like to be added:

Replace the older WinJS based symbols with newer symbols in [Fluent UI](https://developer.microsoft.com/en-us/fluentui#/resources).

## Why is this needed:

To keep icons in Uno up to date with the icons being used by Microsoft.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [x] Solution Templates

## Anything else we need to know?

See the Fabric assets license in the WebFluentFonts download to determine if there are licensing issues that need to be resolved.

**Comment by jeromelaban** [comment]
Thanks @scottkuhl, this is a great find! This may possibly solve the issues with symbols fonts.

Let move this discussion over #3011.
