### ISSUE TITLE
Support embedded resource fonts

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3097]
## What would you like to be added:

Xamarin.Forms 4.6 [introduced cool support](https://montemagno.com/xamarin-forms-custom-fonts-everywhere/) for having `TTF` fonts as embedded resources. This would be beneficial as an option in Uno Platform as well, especially to make font sharing in cross-platform manner even easier.

## Why is this needed:

Easy x-plat fonts.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Adding fonts as embedded resources may not be the best way to work add support for it, particularly if the content is not removed on linking, as it may end up downloading the font even if it is not used. 

This could be addressed by adding async support for `Windows.Storage`.

**Comment by MartinZikmund** [comment]
Font loading is now vastly improved, this issue is no longer needed
