### ISSUE TITLE
Uno UI on the server?

### ISSUE THREAD

**Issue by xsteel2003** [unoplatform/uno#31]
Thanks very much for uno support for webassembly. I am a UWP developer and I am now anxious to distribute some of my features in a browser.
But webassembly currently has a fatal problem: it starts to run too slowly. The first time you want to download up to 10M of data from the server.

I also noticed a project Ooui: https://github.com/praeclarum/Ooui , which provides another way to run XAML and run Xamarin.Forms on a server. In this way, the speed is very fast, really great! Reference: https://github.com/praeclarum/Ooui/wiki/Xamarin.Forms-on-the-Web .

But I'm a UWP developer and I'm not familiar with Xamarin.Forms. I hope uno can run on the server. Is this feasible?

**Comment by jeromelaban** [comment]
Thanks for your interest! 

The current performance is not to be considered at the moment. The current releases of the mono runtime are using the Interpreted mode, which is about 300x to 400x slower than the upcoming AOT mode. Onc AOT is available, we anticipate a massive useability improvement.

As for running on the server, the inner layers of Uno may be too chatty and synchronous for it to be a valid scenario. The goal of wasm is to make it run on the client, so we're going to have to wait for AOT to make all this better!

**Comment by Qvazar** [comment]
I would also like Uno on the server like Ooui. Don't think Ooui is going to continue, so I might have to put my hopes into Uno

**Comment by Flem100** [comment]
I would also like Uno on the server, the same way as Ooui. But sadly I think Ooui is dead, so I might have to put my hopes into Uno :).

**Comment by jeromelaban** [comment]
For now, we have prioritized any work for server-side Uno. What would be your use case?
