### ISSUE TITLE
NavigationView bugs on for all uno platforms

### ISSUE THREAD

**Issue by scpc0609** [unoplatform/uno#3102]
## Current behavior

1. When NavigationView items are grouped using NavigationViewItemHeader, the icons get offset by several pixels
![Screenshot_20200504-204212](https://user-images.githubusercontent.com/10222090/80983004-ad54e400-8e49-11ea-94db-22bef1154464.png)

2. NavigationViewItemHeader items are clickable and gets selected.
![Screenshot_20200504-204146](https://user-images.githubusercontent.com/10222090/80983151-e0977300-8e49-11ea-912f-6eb883a6467c.png)

3. NavigationView does not obey PaneDisplayMode="LeftCompact", so by default in mobile the Portrait Layout is messed up with overlapped hamburger menu
![Screenshot_20200504-204309](https://user-images.githubusercontent.com/10222090/80983305-0c1a5d80-8e4a-11ea-92ea-984fb06e5c3d.png)

## Expected behavior

1. MenuItem icons should not have a left margin and the icons should be fully visible in compact mode. Headers should not be visible at all in compact mode, but just add a vertical spacing of about 4 pixels. In Open mode, left margin should be absent for both Headers and MenuItems

2. Header Items should not be clickable and should not get selected

3. NavigationView should obey PaneDisplayMode. eg. Setting this to LeftCompact should show the pane even when the Page width is small. This used to work fine in earlier version of uno platform (eg. Uno.UI 2.1.37) but broken in recent builds.

## How to reproduce it (as minimally and precisely as possible)

Reproduce with attached Project:
[UnoApp1.zip](https://github.com/unoplatform/uno/files/4575594/UnoApp1.zip)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ X] iOS
- [ X] Android
- [ X] WebAssembly
- [ ?] WebAssembly renderers for Xamarin.Forms
- [ ?] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
@scpc0609  This should now work with the new WinUI `NavigationView`. If not, please reopen.
