### ISSUE TITLE
[macOS] Add support to Calculator

### ISSUE THREAD

**Issue by ajpinedam** [unoplatform/uno#3103]
## What would you like to be added:
Add the macOS head to the Calculator and make it run

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
@ajpinedam Maybe move this issue to https://github.com/unoplatform/calculator/issues directly, so it at its home :-)

**Comment by jeromelaban** [comment]
It's present here to make it easier to track as it may require changes in Uno.

**Comment by MartinZikmund** [comment]
I see, ok 👌
