### ISSUE TITLE
WinUI 3.0 namespaces alignment

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#3109]
This issue tracks the updates needed to align Uno with WinUI 3.0 namespaces.

This repository will entirely be converted to WinUI 3.0 namespaces, and a new Uno.WinUI package will be created as a result. To preserve the backward compatibility, the existing Uno.UI package will still be generated through a CI phase and tooling that will convert back to the UWP/WinUI 2.0 namespaces where appropriate.

Additional details will be included in this issue as the implementation progresses.

**Comment by pkar70** [comment]
What does it mean to using Uno as a tool to port UWP app to Android platform?

**Comment by carldebilly** [comment]
Solution to use WinUI in a Uno project: https://github.com/unoplatform/uno/blob/master/src/SamplesApp/SamplesApp.Shared/App.xaml.cs#L85_L87
