### ISSUE TITLE
StorageFolder.CreateFile with CreationCollisionOption.ReplaceExisting does not empty an existing file

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#3123]
## Current behavior

` var storageFile = await ApplicationData.Current.LocalFolder.CreateFileAsync(LocalSettingsKey, CreationCollisionOption.ReplaceExisting);`

will not empty an existing file if it already exists.

## Expected behavior

The file is emptied properly, and new data can be written to it.

## Environment

Nuget Package: 2.3-dev

**Comment by MelbourneDeveloper** [comment]
@jeromelaban it would probably also be good to implement the method:

`ApplicationData.Current.LocalFolder.GetFilesAsync()`

**Comment by pkar70** [comment]
Implemented in #2774
