### ISSUE TITLE
Uno msbuild target

### ISSUE THREAD

**Issue by msangtarash** [unoplatform/uno#3131]
## What would you like to be added:

Uno msbuild target

## Why is this needed:

As a library author, I create Xamarin forms control and renderers as followings:

netstandard2.0 build target => MyAwsomeControl.cs
monoandroid10.0 build target => MyAwsomeControl.renderer.droid.cs
Xamarin.iOS10 build target => MyAwsomeControl.renderer.iOS.cs
uap10.0.17763 build target => MyAwsomeControl.renderer.uwp.cs

In monoandroid10.0 + Xamarin.iOS10 + uap10.0.17763 I've access to OS api + Xamarin Forms
In netstandard2.0 I reference Xamarin Forms

Everything works like a charm in xamarin forms apps. In Uno/XF application, I can use that for android/iOS/UWP parts but not for wasm part.

I can solve this issue by referencing uno.ui in netstandard2.0 build of my library, but this is not a good idea.

If uno had msbuild target, I was able to to handle my scenario as followings:

uno.2.2 build target => Re use MyAwsomeControl.renderer.uwp.cs + Add a reference to uno.ui nuget package to make that code built.

I can also use #if uno to disable MyAwsomeControl.renderer.uwp.cs parts which are not implemented in Uno

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [X] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

Most xf controls have the same project structure as mine. By providing that msbuild target, we can easily port xf controls to uno platform. (I'm talking about those which have uwp support)

**Comment by jeromelaban** [comment]
Thanks for the feedback!

This is unfortunately something that is not under Uno's control. WebAssembly is aliased as netstandard2.0, and will most likely stay that way for a while, even in the .NET 5 timeframe.

If you're creating a Renderer for WebAssembly, the only thing you can do at this point is use the netstandard 2.0 target framework to create your renderer.

I understand that you may not not want to take a dependency on Uno for netstandard 2.0, and the only way to do this is to create a different renderer package, specific to WebAssembly.

**Comment by ysmoradi** [comment]
> This is unfortunately something that is not under Uno's control. WebAssembly is aliased as netstandard2.0, and will most likely stay that way for a while, even in the .NET 5 timeframe.

I understand.

Have you ever tried to tell them how awful is this design? Even watchOS has its own target framework!

Another question. How the Tizen team was able to create tizen40 target framework?

**Comment by jeromelaban** [comment]
I understand what you mean here, and the Tizen team worked with Microsoft closely to add support for this. 

Yet it's also now recognized as a problem as far as the nuget design of TargetFrameworks is concerned. For example `monoandroid10.0` only defines the Android API level, but not the .NET SDK being used, which causes lots of trouble for backward or forward compatibility, and repeatable builds.

As far as WebAssembly is concerned, here's the [reasoning behind this in an design article](https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md#why-is-the-tfm-callednet50-browserandnet50-wasm) from the .NET team.

**Comment by jeromelaban** [comment]
We've started adjusting the object model a target frameworks for Skia and WebAssembly, which will both use the same binary API. Other platforms Xamarin based targets will still use their own (iOS/Android/macOS).
