### ISSUE TITLE
ComboBox causes performance issues

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3144]
## Current behavior

`ComboBox` has some performance issues:

- Loading page with a combo box is slower
- Loading a list with many items causes a crash
- Adding items one by one freezes UI thread (even if the combo is not open)

I am hitting these issues when porting MIDI samples from UWP Samples repo. In one case, the sample needs to fill the combo with 16k items, which makes the app freeze up. The original code added the items one by one, which was an issue even with 120 items. Replacing the whole items source makes 120 items manageable, but 16k crashes it completely.

## Expected behavior

No crashing :-) 

## How to reproduce it (as minimally and precisely as possible)

- Create a combobox, bind it to `ObservableCollection<int>` and add 120 items in a for-loop.
- Create a combobox, bind it to `ObservableCollection<int>` which has 16k items.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
On Android and iOS this is a known issue, ComboBox isn't virtualized (https://github.com/unoplatform/uno/issues/556, https://github.com/unoplatform/uno/issues/1133).

On WASM it is virtualized, though. (`ObservableCollection` is only naively supported on WASM however)

**Comment by mb751** [comment]
Is the work around given in issue #556, namely:

`			<not_win:ComboBox.ItemsPanel>
				<ItemsPanelTemplate>
					<ItemsStackPanel />
				</ItemsPanelTemplate>
			</not_win:ComboBox.ItemsPanel>`

Still working? I have tried to use this in iOS & android, and both platforms are failing to display properly.

**Comment by MartinZikmund** [comment]
Same issue as #556, closing
