### ISSUE TITLE
[WASM] VS Debugging does not work if using SkiaSharp

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3150]
## Current behavior

If you have installed the Uno.SkiaSharp.Views and Uno.SkiaSharp.Wasm nuget packages and configured the LinkerConfig.xml for them then Visual Studio will no longer hit breakpoints during debugging.

## Expected behavior

Debugging should work as it does without these packages installed.

## How to reproduce it (as minimally and precisely as possible)

In the attached solution, launch the wasm project in Debug mode.  Set a breakpoint in the OnClick method in MainPage.xaml.cs and observe that it is not hit when the button is clicked.  Remove the SkiaSharp-related packages and remove references to same packages from LinkerConfig.xml.  Rebuild the wasm project and launch in debug mode, and observe that now the breakpoint is hit when you click the button.

[App44.zip](https://github.com/unoplatform/uno/files/4622074/App44.zip)

## Environment

Nuget Package:
Uno.UI

Package Version(s):
2.3.2

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by peternary** [comment]
Note: only tested in Intepreter, not AOT.

**Comment by jeromelaban** [comment]
This issue will be fixed by https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/214

**Comment by peternary** [comment]
Not working in AOT, confirmed on attached project with latest NuGet packages.  Should a separate issue be logged for this?

**Comment by jeromelaban** [comment]
Debugging will not work with AOT, only using the interpreter. It's a documented mono restriction, and it's unlikely to work any time soon (it's not available for mono for iOS/Android either).

**Comment by DierkDroth** [comment]
Thanks for clarification @jeromelaban
