### ISSUE TITLE
Other IDEs and OSs support

### ISSUE THREAD

**Issue by ILAgent** [unoplatform/uno#3152]
Many developers prefer Mac or even Linux as a workstation. To be competitive you definitely must support other IDEs on other platforms.

**Comment by jeromelaban** [comment]
Thanks for the feedback! We're looking at other operating systems for sure, we already support VS for mac for iOS, Android and WebAssembly development, and VS Code for macOS and Linux development: https://github.com/unoplatform/uno/blob/master/doc/articles/get-started-vscode-wasm.md

We're not done adding support, though, more is coming!

**Comment by ILAgent** [comment]
Thank you, I see only possibility to use VS code for wasm development. Can you please share info about vs4mac support?

**Comment by jeromelaban** [comment]
We've released the preview support for macOS here, with some documentation: https://platform.uno/blog/announcing-uno-platform-2-4-macos-support-and-windows-calculator-on-macos

**Comment by francoistanguay** [comment]
We had doc as to how to start with the various IDEs here 
[https://platform.uno/docs/articles/get-started-vs.html](Docs)
