### ISSUE TITLE
[WASM] Canvases do not behave correctly in ListView

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3153]
## Current behavior

Canvases in a ListView exhibit strange behavior in WASM.  Add canvases will cause the entire ListView to 'flicker,' and canvases that are not getting redrawn will often render the contents of other canvases when scrolling, or sometimes render partial content from other canvases.

Tested in Interpreter mode

## Expected behavior

Canvases should behave as in UWP

## How to reproduce it (as minimally and precisely as possible)

Start the attached project in WASM and observe that the listview flickers as canvases are added.  Scroll up and down and note that canvases which should be empty contain full or partial contents of other canvases.

[CanvasTestRows.zip](https://github.com/unoplatform/uno/files/4624205/CanvasTestRows.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
2.3.2
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
The flickering when an item is added to the list is probably down to the fact that `ObservableCollection` is only naively supported on WASM - I created a separate issue for that here: https://github.com/unoplatform/uno/issues/3258

It sounds like there's still other things going on though that need to be investigated, so I'll leave this issue open too. I notice that the sample is using `SkiaSharp` - could that be a factor?

**Comment by peternary** [comment]
I do believe the issue is particular to SkiaSharp, possibly due to the overhead of the canvas drawing logic as opposed to rendering a more normal UWP control.  I believe this is especially true of the situation wherein one canvas' contents are displayed in place of another canvas - I have not encountered similar behavior in any listviews relying on standard UWP controls.

**Comment by DierkDroth** [comment]
@davidjohnoliver thanks for your continued effort to get the/styling issues straightened out. Is there any progress on that issue?

**Comment by davidjohnoliver** [comment]
Update on this issue: the 'flicker' when a new item is added to the list should be resolved now that [proper `ObservableCollection` support is merged](https://github.com/unoplatform/uno/pull/3444), and performance in general should be better.

The issue that `SKXamlCanvases` are incorrectly showing the contents of other canvases is a bug coming from SkiaSharp, that the `SkCanvas` passed to the `OnPaintSurface()` method is being recycled from a previous view without being cleared.

We plan to fix it, but for now the workaround is to make sure to always clear the canvas, ie change the code in `RandomCanvas` to the following:

```csharp
		protected override void OnPaintSurface(SKPaintSurfaceEventArgs e)
		{
			SKCanvas canvas = e.Surface.Canvas;
			canvas.Clear(SKColors.White);

			if (!isOnLocal)
				return;
			...
```

**Comment by jeromelaban** [comment]
@davidjohnoliver the canvas clearing is already fixed in `Uno.SkiaSharp` latest dev. Apologies, I forgot to mention this on this thread.

**Comment by DierkDroth** [comment]
@peternary confirmed the original issue is fixed now in interpreter mode (he could not test AOT for unrelated reason)
