### ISSUE TITLE
BugTracker sample wasm: wrong components behaviour 

### ISSUE THREAD

**Issue by pkostaki** [unoplatform/uno#3158]
## On which page?
Main page
## What's wrong?
 - Chrome: DataBinding for slider "effort" failds on _(Chrome 81.0.4044.138 )_
 - Edge:  doesn't work selection of combobox items _(Microsoft Edge 44.18362.449.0;Microsoft EdgeHTML 18.18363)_

**Comment by jeromelaban** [comment]
Thanks for the report @pkostaki, the chrome issue will be fixed as part of the 2.4 release (Fixed in https://github.com/unoplatform/uno/pull/3166).

For Edge, we're mostly validating he behavior using the newer (Chromium based) Edge, as there are are too many issues using the old one.

**Comment by kaki104** [comment]
WIP value of Status is not displayed.
However, if I click the combo box, the WIP value is placed in the middle.

My browser is Chromium based Edge
Microsoft Edge is up to date.
Version 81.0.416.77 (Official build) (64-bit)
