### ISSUE TITLE
[Android][CheckBox] Native CheckBox requires two taps to change state (first nav only)

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/uno#3163]
## Current behavior

![CheckBox two taps](https://user-images.githubusercontent.com/49959074/81989075-91e89680-960a-11ea-892d-87ad90896b48.gif)

## Expected behavior

User should only have to tap once to activate checkbox

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.4

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.5.5)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
Seems similar to https://github.com/unoplatform/uado/issues/214

**Comment by StewartPolsky** [comment]
Unable to reproduce on latest build

**Comment by marwalsch** [comment]
I'm running into the exact same issue on Uno.WinUI 4.1.0-dev.480. 

Upon first interaction the animation transitions back into it's initial state once, while the value of `IsChecked` is changed correctly. This causes the value to be permanently out of sync with it's visual reflection. This happens regardless of initial value or whether `IsThreeState `is enabled.

Reproducible for me on API version 26 and 30 on physical device and simulator respectively.
