### ISSUE TITLE
[ios] [android] CommandBar overlapping with NavigationView

### ISSUE THREAD

**Issue by Matt932** [unoplatform/uno#3169]
## Current behavior

CommandBar title and Navigation View "Hamburger" Button are overlapping.

https://user-content.gitter-static.net/7dab50c3af451f2be72b2ccbfed388d691438ea6/68747470733a2f2f7331322e64697265637475706c6f61642e6e65742f696d616765732f3230303531332f726e6f34353932732e706e67

## Expected behavior

The commandbar title should be placed next to the hamburger button

## How to reproduce it (as minimally and precisely as possible)

Create a page with a NavigationView and an CommandBar inside. The CommandBar should represent a header with a title. Then run the application on ios or android.

## Environment

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] WebAssembly
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by francoistanguay** [comment]
Do you have sample XAML / repro for this by any chance?

**Comment by Matt932** [comment]
Solved it! There was a problem with the margin.
