### ISSUE TITLE
x:Bind to type in default namespace in DataTemplate generates invalid code

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3171]
## Current behavior

When `x:DataType` is set to `Color` and the `DataTemplate` contains a `SolidColorBrush` with `Color="{x:Bind}"`, invalid code is generated.

## Expected behavior

Valid code should be generated, as on UWP.

## How to reproduce it (as minimally and precisely as possible)

Enter the following XAML:

```
<ItemsControl ItemsSource="{Binding Something}">
    <ItemsControl.ItemTemplate>
        <DataTemplate x:DataType="Color">
            <FontIcon Glyph="A">
                <FontIcon.Foreground>
                    <SolidColorBrush Color="{x:Bind}" />
                </FontIcon.Foreground>
            </FontIcon>
        </DataTemplate>
    </ItemsControl.ItemTemplate>
</ItemsControl>
```

Launch app on UWP - observe it launches normally.

Compile for Android, iOS, WASM or macOS. Observe the following error:

> The type or namespace name 'Color' could not be found (are you missing a using directive or an assembly reference?)

```
c5.SetBinding(global::Windows.UI.Xaml.Media.SolidColorBrush.ColorProperty, 
    new Windows.UI.Xaml.Data.Binding{ Mode = BindingMode.OneTime }.Apply(
       ___b => /*defaultBindModeOneTime*/ 
          global::Uno.UI.Xaml.BindingHelper.SetBindingXBindProvider(
             ___b, null, ___ctx => 
                      ___ctx is Color ___tctx ? (object)(___tctx) : null, null )));
```

The `Color` type reference should be fully qualified for the code to compile properly.

## Environment

Nuget Package: latest

Package Version(s): latest

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks Martin! Good find.
