### ISSUE TITLE
Unable to build WASM project with SkiaSharp: WSL is required for this build but could not be found.

### ISSUE THREAD

**Issue by ZeProgFactory** [unoplatform/uno#3173]
## Current behavior
Unable to build without errors:
[Build.log.txt](https://github.com/unoplatform/uno/files/4639233/Build.log.txt)

## Expected behavior
Build without errors.

## How to reproduce it (as minimally and precisely as possible)
Take lastest VS2019 with latest UNO Extension,
generate an new UNO Solution,
for commodity I remove iOS, Mac & Android,
build WASM project -> **OK**

Add  `Uno.SkiaSharp.Views 1.68.0-uno.298` and `Uno.SkiaSharp.Wasm 1.68.0-uno.298` to the WASM project 
and rebuild -> **KO**

## Environment
VS 2019 Enterprise - Windows 10 pro

Nuget Package:
Uno.SkiaSharp.Views 
Uno.SkiaSharp.Wasm 

Package Version(s):
Uno.SkiaSharp.Views 1.68.0-uno.298 
Uno.SkiaSharp.Wasm 1.68.0-uno.298 

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:
none

**Test solution**
[TestUNO.zip](https://github.com/unoplatform/uno/files/4639255/TestUNO.zip)

**Comment by jeromelaban** [comment]
Thanks for the report. As the error message mentions, you'll need to install WSL for this to work properly:
```
System.InvalidOperationException: WSL is required for this build but could not be found.
```

You can find the documentation here: https://github.com/unoplatform/uno.wasm.bootstrap#required-configuration-for-aot-mixed-mode-or-external-bitcode-support-compilation-on-windows-10

Additionally, to use SkiaSharp with the 1.2.0 version of the bootstrapper, you'll need the version 2.80 dev builds.
