### ISSUE TITLE
Support for `Windows.Devices.Radios.Radio.GetRadiosAsync`

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#3176]
## What would you like to be added:
Windows.Devices.Radios.Radio.GetRadiosAsync() as a way to check if Bluetooth is supported.

## Why is this needed:
Because I'm using it in my UWP apps.

## For which Platform:
- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?
I will implement it in Uno in this week.

**Comment by MartinZikmund** [comment]
This is merged
