### ISSUE TITLE
Add screen orientation support on WASM

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3177]
## What would you like to be added:

Support for screen orientation via [Screen.orientation API](https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation).

Can also include screen orientation locking/unlocking (`AutoRotationPreferences` in UWP)

## Why is this needed:

Feature parity

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by Youssef1313** [comment]
@MartinZikmund Was that implemented with #3589?

**Comment by MartinZikmund** [comment]
While the screen orientation events are implemented, orientation locking is not yet supported (`AutoRotationPreferences`). This could be implemented using `ScreenOrientation.lock()` and `ScreenOrientation.unlock()` in JS
