### ISSUE TITLE
Cannot Change Accent Color for WASM on Uno 2.4

### ISSUE THREAD

**Issue by berkbb** [unoplatform/uno#3191]
Hi,
I defined a new accent color in App.xaml lke this:

```
Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
            </ResourceDictionary.MergedDictionaries>
            <Color x:Key="SystemAccentColor">#FFCB2128</Color>
            <Color x:Key="AcmGreen">#FFB8C282</Color>
            <Color x:Key="AcmPink">#FFE672A4</Color>
            <Color x:Key="AcmPurple">#FF71749E</Color>
            <Thickness x:Key="PivotItemMargin">0</Thickness>

        </ResourceDictionary>
       
    </Application.Resources>
```
It works on UWP app:
![Ekran Resmi 2020-05-19 14 04 36](https://user-images.githubusercontent.com/23173536/82319348-1146e300-99da-11ea-8066-7d507a2519e2.png)

However, Accent Color stays default blue on WASM Page (Edge Chromium -  81.0.416.77)

![Ekran Resmi 2020-05-19 14 07 51](https://user-images.githubusercontent.com/23173536/82319482-510dca80-99da-11ea-9322-99f8061868f2.png)

## Current behavior

The accent color on WASM do not match with UWP version which defined in App.xaml.

## Expected behavior

The accent color on WASM should match with UWP version which defined in App.xaml.

## How to reproduce it (as minimally and precisely as possible)

1. Create a new UNO app. Add custom accent color definition to App.xaml. 
2. Add an element to UI which supports accent color.
3. Compare the accent color for this element on both WASM and UWP.

## Environment

Nuget Package:

Package Version(s):
                   
Uno.UI.RemoteControl                {2.4.0}                                                                                          
Uno.Wasm.Bootstrap                  {1.2.0}                                                                        
Uno.Wasm.Bootstrap.DevServer        {1.2.0}                                                          
Microsoft.Extensions.Logging.Filter {1.1.2}                                                                                       
Microsoft.Extensions.Logging.Con... {1.1.1}                                                                           
NETStandard.Library                 {2.0.3}                                                                                       
Uno.UI                              {2.4.0}                                                                                  
Microsoft.NETCore.UniversalWindo... {6.2.10}                                                                                   
Microsoft.Extensions.Logging.Con... {1.1.1}                                                                                     
Microsoft.Extensions.Logging.Filter {1.1.2}                                                                  
Microsoft.UI.Xaml                   {2.4.0}                                                                                        
Uno.Core                            {2.0.0}                                  
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [X] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [X] Resharper (version: 2020.1.2 )

**Comment by jeromelaban** [comment]
This issue is related to #1766. /cc @davidjohnoliver

**Comment by davidjohnoliver** [comment]
Indeed, this is something that should be supported once #1766 is merged.

**Comment by berkbb** [comment]
Thanks. https://stackoverflow.com/questions/61889917/cannot-change-accent-color-for-wasm-on-uno-2-4 partially solves it. I'm waiting excitedly for merge of the [PR](https://github.com/unoplatform/uno/pull/1766) :)
