### ISSUE TITLE
DisplayMemberPath not working on custom control template for ListView

### ISSUE THREAD

**Issue by athulkuloorsurendran** [unoplatform/uno#3195]
## Current behavior

If using a ListView with a style defined elsewhere the DisplayMemberPath property is not used. Works if no style is set.

## Expected behavior

DisplayMemberPath should work in UWP and WASM while using inside a user control 

## How to reproduce it (as minimally and precisely as possible)
Build attached project and test on WASM to see issue. Note that removing the style from the ListView resolves the problem.

https://filebin.net/hw3sjgiqkwjgj1ig
## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
The filebin link seems to've expired. If you still have the original repro, could you share it with us either as a GitHub repository or an attached zip file?
Thanks!

**Comment by carldebilly** [comment]
The fix has been merged in Uno.UI v3.1.0-dev.375
