### ISSUE TITLE
About startup time

### ISSUE THREAD

**Issue by yunusefendi52** [unoplatform/uno#32]
I am thrilled with Uno because, well, it's about UWP, but there is currently one main concern that I am worried about, that is startup time, https://github.com/nventive/Uno.QuickStart is about 4-5 seconds on Android, and then there is https://github.com/nventive/Uno.Playground which takes about 15-18 seconds. Maybe you guys could investigate it before going any deeper.

Note: I am using android phone Xiaomi 5A

Thank you for investing your time with this.. 😄

**Comment by jeromelaban** [comment]
Thanks for your interest!

Are you running a binary you built yourself ? If this is the case, AOT is disabled in debug, which impacts significantly the startup time.

**Comment by 5yunus2efendi** [comment]
I am sorry for the delay.

No, I just download Uno Gallery on Play Store.

**Comment by ghuntley** [comment]
Closing this out due to old age, please open a new GitHub issue if you have performance concerns with a later release.
