### ISSUE TITLE
Uno need more publicity

### ISSUE THREAD

**Issue by Daoting** [unoplatform/uno#3202]
## What would you like to be added:
Actually Uno seems far more attractive and relevant than .net MAUI, from every aspect, but it's a lot less known.

**Comment by tesar-tech** [comment]
Yes. The MAIU. I was personally hoping that uno guys, along with Microsoft, came up with something big on BUILD2020. Now MAUI seems like direct competitor of UNO. Same principles, but based on xamarin, not on UWP. 

So question is - how is it gonna be with UNO and MAUI?

**Comment by pkar70** [comment]
Some time ago was rumors about removing Live Tile functionality from Windows (Windows 10X? I don't remember details). It seems like Microsoft wants to remove all own solutions, and be only Android (Xamarin?) compatible.
But I prefer UWP :)

**Comment by Daoting** [comment]
C# and XAML:   wpf -> silverlight -> uap -> uwp -> winui + reunion
So allow winui/reunion cross platform is uno's next target. Perhaps uno is project rereunion.

**Comment by NickAcPT** [comment]
Maybe both will be able to coexist.

I feel like the unified project system they'll have over on .NET Multi-platform App UI would benefit everyone.

And seeing that it'll be cross-platform, Uno would probably benefit from that, since they could use the cross-platform APIs implemented by Xamarin.

**Comment by francoistanguay** [comment]
I believe our position was explained at UnoConf 2.0 in how we want to be able to control every pixel, on every platform. I agree we'll always need more publicity and the best way is by showcasing the apps you're all building with Uno. We have a great relationship with the WinUI team and they do their best to promote us as well.

Will close the issue for now but feel free to continue to share your thoughts and your successes!
