### ISSUE TITLE
BugTracker binding error

### ISSUE THREAD

**Issue by kaki104** [unoplatform/uno#3204]
## On which page?
https://platform.uno/docs/articles/getting-started-tutorial-1.html
## What's wrong?
    private int effort;
    public int Effort
    {
        get => effort;
        set => SetProperty(ref effort, value);
    }

=>
        private double effort;
        public double Effort
        {
            get => effort;
            set => SetProperty(ref effort, value);
        }

A binding error occurs because the slider's value property is not of type int (Android, WASM).
## Any feedback?
I like very much UNO Platform~

**Comment by jeromelaban** [comment]
Thanks for the feedback! This should be fixed by updating to the 2.4 Uno.UI package. Which version is installed in your code ?

**Comment by kaki104** [comment]
I just checked the version.
This project is made from Uno 2.2 template.
So, I created a new project with the Uno 2.4 template and tested it again, everything was fine.
Thank you.
