### ISSUE TITLE
DataBinding Not Show Correctly in WASM 

### ISSUE THREAD

**Issue by berkbb** [unoplatform/uno#3205]
Hi,
I have ListView on my Page. I have some bindings from a different class named SearchCapsule. It's values comes from SQL Server with EF Core on  .NET Standard project (I attached this project via local Nuget resource, because it is in different solution)

Binding IssueNumber is a  static number, comes from constructor:
```
 <TextBlock x:Name="IssueNumber_TextBlock" Margin="0,0,0,0" Text="{Binding IssueNumber}"
                                       VerticalAlignment="Center" HorizontalAlignment="Center"
                                       TextAlignment="Center" FontFamily="Noto Sans Display" FontSize="20" FontWeight="Bold"  Foreground="Black" />  
```

Other bindings values are coming after  a process inside of the SearchCapsule class. Fore example; this button's content comes in different format ("Buy" in EN, "Satın Al" in TR) based on language identifier ("EN" or "TR") in SearchCapsule constructor.
```
 <Button x:Name="Buy_Button" Content="{Binding ButtonName}" Grid.Column="2" HorizontalAlignment="Center"
                                Margin="10,10,10,10" VerticalAlignment="Center" CornerRadius="{StaticResource ButtonCornerRadius}"
                                FontSize="16" Click="Buy_Button_ClickAsync" Background="{StaticResource AcmGray}" FontFamily="Noto Sans Display" FontWeight="Normal" >
                                    <Button.Foreground>
                                        <SolidColorBrush Color="{StaticResource Jet}"/>
                                    </Button.Foreground>
                                </Button>
```

The full XAML Code:
```

    <ListView x:Name="ResultList" ScrollViewer.VerticalScrollBarVisibility="Disabled">
                    <ListView.ItemTemplate>
                        <DataTemplate>
                            <Grid x:Name="ResultDataViewer" Margin="10,10,10,10">

                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="Auto" />
                                    <ColumnDefinition Width="*" />
                                    <ColumnDefinition Width="Auto" />
                                </Grid.ColumnDefinitions>
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="Auto" />
                                    <RowDefinition Height="*" />
                                </Grid.RowDefinitions>
                                <Rectangle x:Name="BackRectangle" Grid.RowSpan="2" StrokeThickness="2" RadiusX="5" RadiusY="5"
                                   Stroke="{StaticResource CapsuleStroke}"
                                   Grid.ColumnSpan="3" Fill="{StaticResource CapsuleBackground}" />
                                <Grid x:Name="IssueLogoGrid" HorizontalAlignment="Center" Margin="10,10,10,10" Grid.RowSpan="2"
                              VerticalAlignment="Top">
                                    <Image x:Name="FileLogo" Source="/Assets/journalcover.png" Grid.ColumnSpan="1" Width="96"
                                   Height="96" VerticalAlignment="Stretch" HorizontalAlignment="Stretch" />
                                    <TextBlock x:Name="IssueNumber_TextBlock" Margin="0,0,0,0" Text="{Binding IssueNumber}"
                                       VerticalAlignment="Center" HorizontalAlignment="Center"
                                       TextAlignment="Center" FontFamily="Noto Sans Display" FontSize="20" FontWeight="Bold"  Foreground="Black" />
                                </Grid>
                                <Button x:Name="Buy_Button" Content="{Binding ButtonName}" Grid.Column="2" HorizontalAlignment="Center"
                                Margin="10,10,10,10" VerticalAlignment="Center" CornerRadius="{StaticResource ButtonCornerRadius}"
                                FontSize="16" Click="Buy_Button_ClickAsync" Background="{StaticResource AcmGray}" FontFamily="Noto Sans Display" FontWeight="Normal" >
                                    <Button.Foreground>
                                        <SolidColorBrush Color="{StaticResource Jet}"/>
                                    </Button.Foreground>
                                </Button>
                                <TextBlock x:Name="Issue_FullHeader_TextBlock" Grid.Column="1" Grid.ColumnSpan="1"
                                   Grid.RowSpan="1" Margin="10,10,10,10" Text="{Binding FullIssueHeader}"
                                  FontWeight="Medium"
                                   HorizontalAlignment="Stretch" VerticalAlignment="Center" TextAlignment="Left" FontSize="20" FontFamily="Noto Sans Display" Foreground="Black" TextWrapping="Wrap" />
                                <ListView x:Name="Articles_ListBox" Margin="10,10,10,10" Grid.Row="1" Grid.Column="1"
                  ItemsSource="{Binding ArticleTitles}" FontStyle="Italic" SelectionMode="None"
                  FontWeight="Medium" Grid.ColumnSpan="2" FontFamily="Noto Sans Display" FontSize="22" Foreground="Black" IsEnabled="False">
                                    <ListView.ItemContainerStyle>
                                        <Style TargetType="ListViewItem">
                                            <Setter Property="HorizontalContentAlignment" Value="Stretch" />
                                            <Setter Property="Foreground" Value="Black" />
                                        </Style>
                                    </ListView.ItemContainerStyle>
                                </ListView>
                            </Grid>
                        </DataTemplate>
                    </ListView.ItemTemplate>
                    <ListView.ItemContainerStyle>
                        <Style TargetType="ListViewItem">
                            <Setter Property="HorizontalContentAlignment" Value="Stretch" />
                        </Style>
                    </ListView.ItemContainerStyle>
                </ListView>
```

## Current behavior

Values are showing correct after binding in UWP:
![1](https://user-images.githubusercontent.com/23173536/82479198-b8ab3f00-9ada-11ea-8a79-5f03f5fd872e.jpg)

![1all](https://user-images.githubusercontent.com/23173536/82479184-b6e17b80-9ada-11ea-8109-f6df868b1187.jpg)

Values are showing incorrect after binding in WASM. Only static IssueNumber is shown. On All results page, list's count seeme 0, but as you see, UWP shows correctly.:

![2](https://user-images.githubusercontent.com/23173536/82480621-bea21f80-9adc-11ea-9086-6b97b67b6957.jpg)
![2all](https://user-images.githubusercontent.com/23173536/82480634-c1047980-9adc-11ea-873d-5113fc63ef08.jpg)

## Expected behavior

WASM and UWP data binding will be same.
## How to reproduce it (as minimally and precisely as possible)

Make a data binding UWP ad look it on WASM.

## Environment

Nuget Package:

Package Version(s):
Uno.UI.Lottie {2.4.0}
Uno.UI.RemoteControl {2.4.0}
Uno.Wasm.Bootstrap {1.2.0}
Uno.Wasm.Bootstrap.DevServer {1.2.0}
Microsoft.Extensions.Logging.Filter {1.1.2}
Microsoft.Extensions.Logging.Con... {1.1.1}
NETStandard.Library {2.0.3}
Uno.UI {2.4.0}
Microsoft.NETCore.UniversalWindo... {6.2.10}
Microsoft.Extensions.Logging.Con... {1.1.1}
Microsoft.Extensions.Logging.Filter {1.1.2}
Microsoft.UI.Xaml {2.4.0}
Uno.Core {2.0.0}
Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [X] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version:16.6.0 )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the feedback! Is the code you're binding to in another assembly ?

**Comment by berkbb** [comment]
Yes. It is on different namespace and project. It is a net standard project which includes ef core operations and wrappers. It enables sql server operations for a different uwp admin app. This uno app is a search app for WASM for with same dataset , it needs to connect the same database. So, I publish net standard project as a nupkg and add locally to this project. All of the operations runs correctly on UWP but not on WASM.

**Comment by jeromelaban** [comment]
This is most likely a linker issue then. Can you try adding your project assembly name in the LinkerConfig.xml file ?

**Comment by berkbb** [comment]
Thanks. Sure. I will try it tomorrow.

**Comment by berkbb** [comment]
I addet it as:

`<assembly fullname="ACM_Search_AdminApps.Shared" />`

Now, it shows correctly on WASM:

![Ekran Resmi 2020-05-21 20 38 30](https://user-images.githubusercontent.com/23173536/82588182-11dea580-9ba3-11ea-9d02-6b87c89112af.png)


However, I cannot pull data from SQL database with same project assemble on WASM.

**Same pages for SQL pull data page on:**
_Wasm_
![Ekran Resmi 2020-05-21 20 40 07](https://user-images.githubusercontent.com/23173536/82588430-77329680-9ba3-11ea-8d01-473ba3206e6f.png)
_UWP_
![Ekran Resmi 2020-05-21 20 40 36](https://user-images.githubusercontent.com/23173536/82588464-831e5880-9ba3-11ea-8e69-95b8f62285f0.png)
Does WASM not support data operations? How beautiful UWP works too :)

**Comment by jeromelaban** [comment]
TCP Sockets are not available in WebAssembly/JavaScript, so the best way there is to use a WebApi endpoint to access the database. You're probably getting an exception in the browser logs that's telling you something along those lines.

**Comment by berkbb** [comment]
Understood. I dont know Jscript have no TCP / UDP. Using a Asp core web api will solve it ? Can I detect is app running on WASM ? I will check the browser outputs. Thanks for fast support.

**Comment by berkbb** [comment]
Using a Asp core web api and Microsoft CORS NuGet package solves it. Thanks.
