### ISSUE TITLE
[WASM] Issues with DataGrid support

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3206]
## Current behavior

DataGrid performance in WASM particularly poor as size of datasets grows larger.  This is both rendering an updated collection and resizing columns for an existing collection.

Arrows to indicate ascending/descending sort do not appear in column headers.

Chevron to collapse a group is cut off (the chevron to expand a group looks fine).

Columns do not autosize correctly when using a DatePicker in a DataGridTemplateColumn.

Rightmost header gridline appears to be twice the thickness of other header gridlines.

None of these issues are present in UWP.

## Expected behavior

Performance should improve and layout should match UWP.

## How to reproduce it (as minimally and precisely as possible)

Build and observe the described issues in WASM.  Build and observe that issues are not present and performance is much improved in UWP.

[UnoDatagrid.zip](https://github.com/unoplatform/uno/files/4658702/UnoDatagrid.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
3.0.0-dev.51
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by francoistanguay** [comment]
Given all the perf improvements in net6 and latest Uno upcoming release, I would close this for now and would need to be retested as needed. Thanks!
