### ISSUE TITLE
Innovation vs Stability

### ISSUE THREAD

**Issue by mrlacey** [unoplatform/uno#3210]
Wow! 3 releases (2.3, 2.4 & 3.0) in 8 days, you're moving fast. 
But on the other hand, that is a lot of change to deal with from a consumer perspective.

With no public roadmap* it's hard to plan work around when releases (will) happen.
Lots of change happening too frequently can also raise concerns about the stability, maturity, and reliability of the platform. :/

*I know about the [project plan](https://github.com/orgs/unoplatform/projects/1) but most of it is private, it doesn't have dates on it, and it hasn't been updated since before 2.3 was released.

I have a client who I'm talking with about an app and the conversation is going back and forth between using UWP and Xamarin. The issue of "Uno just seem like they're jumping on every new thing that comes along. Can we be confident they will be around and able to support something we start using now?" has come up.

**Comment by robloo** [comment]
It's true Uno Platform doesn't want to get into a situation where new features are added on an unstable base. That's what Xamarin Forms has been doing for years and it results in a buggy, hard-to-fix codebase. Hopefully a lot of focus will go on stability.

That said, the project still needs features to get to parity with UWP. On top of that, it's a big transitional time for all of WinUI going to 3.0 so you will see an unnaturally large amount of changes over the next year. It's going to be tricky even for Windows UWP apps to keep up and make sure the switch to WinUI 3.0 is done in a 'stable' way without too many regressions.

I don't think the amount of changes recently is an issue. If anything it illustrates the commitment to getting Uno up-to-speed. I would pitch it to your clients in a different way and say the number of changes shows the strong push to get to feature parity. The code is also open source and we all can look at bugs and fix regressions. Open source is a big positive to ensure future support.

**Comment by pkar70** [comment]
How you would write "roadmap", as (at least part of) changes/additions to Uno are in form of PR from programmers using Uno who wants specific feature for own purposes, not planned before?
E.g. someone get idea of writing app that is using call history, so he implements call history.... but this app was not planned before.

**Comment by francoistanguay** [comment]
@mrlacey , this is something we continuously have top of mind. The team worked extremely hard and pushed a lot of innovation out recently. Once you get to play with it, hopefully you will see it contains the same stability as what we had shipped before, if not better. We've also been refactoring large pieces of code to better align with WinUI. 

All in all, with the 6 years we've been putting into this already, and the quality of the team, we believe we're heading in the right direction, that we're here to stay and that ultimately, by having you ship quality solutions to your customers, we will together prove that this platform has its unique and well-deserved place in the market.

In all cases, the team was heads down in macOS release and WinUI 3.0 alignment, while working on major stability improvements. Now that this is "behind us", I think we can do a better job at better communicating a roadmap and will welcome all the feedback you have.

As always, please continue to push us, provide valuable feedback and feel free to reach out directly.

**Comment by mrlacey** [comment]
Understood. Can we at least get an idea of plans future releases (major and minor)?

**Comment by francoistanguay** [comment]
We're working on the updated backlog/roadmap right now. Will keep you posted. But you can see through some of the talks that things top of mind are:

- Closing as many open issues as possible
- Basic SkiaSharp support, 
- Shipping MSAL support
- Exploring new programming models, 
- Releasing some of the major Styles/Resources refactoring, 
- Enhancing Shapes support, 
- Closing the gap on some controls like TreeView, 
- Improving docs where useful

**Comment by francoistanguay** [comment]
Matt, we're in the process of creating and reviewing milestones for 3.1, 3.2, ... Hopefully will provide the clarity over what we're working on (bugs, coverage, ...)
