### ISSUE TITLE
[ProgressRing] ProgressRing stops animating after a page navigation

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#3212]
I have encountered a different topic, I don't know it is a bug or not. ProgressRing get stuck and won't turn around the background again after a page navigation. It looks a frozen progress ring :)

_Originally posted by @berkbb in https://github.com/unoplatform/uno/issues/3193#issuecomment-631553494_

Also on SO: https://stackoverflow.com/questions/62018364/progressring-stops-animating-after-a-page-navigation-on-uno-2-4-wasm

**Comment by berkbb** [comment]
I forgot specify which project is affected, ProgressRing seems ok on UWP, the real issue seems on WASM.
