### ISSUE TITLE
error APPX0501: error C00CE169: App manifest validation error

### ISSUE THREAD

**Issue by egarim** [unoplatform/uno#3214]
## Current behavior

After you create the project its impossible to compile it the first time
## Expected behavior

After the solution is created, all projects should compile
## How to reproduce it (as minimally and precisely as possible)

Create a new uno-prism application and compile the UWP project
## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x ] Windows
- [ ] Build tasks
- [x ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x ] 2019 (version: 16.5.4)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This issue has been fixed in the 2.4 release of the templates. Can you try running this an create another solution:

```
dotnet new -i Uno.ProjectTemplates.Dotnet::2.4
```

and let us know if that fixed it ?

**Comment by egarim** [comment]
@jeromelaban  Thanks now its working
