### ISSUE TITLE
ElementName binding on a UserControl does not work

### ISSUE THREAD

**Issue by andrewD123** [unoplatform/uno#3218]
## Current behavior

WASM  Binding on a User control does not work but the same code on a page works fine.
Works on UWP.

## Expected behavior

Binding to work like UWP.
## How to reproduce it (as minimally and precisely as possible)
build a user control with binding.  I  used dependency property ienumerable<string>
and bound to a combobox.  I use the same code on a page vs user control and page works but user control does not.
I have a default page and I added the new page and new user control to the page and the page code works but not usercontrol

Create WASM project.
Create new page
Create new usercontrol
add binding code to both.
Add page to main page.
add usercontrol to main page.
## Environment

Nuget Package:
latest build
Package Version(s):
latest build
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )
[unoTest.Shared.zip](https://github.com/unoplatform/uno/files/4669049/unoTest.Shared.zip)

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Looks like this issue is related to #61. Could you apply the workaround specified there and let us know ?

**Comment by andrewD123** [comment]
UnoSkipUserControlsInVisualTree did not work.

**Comment by jeromelaban** [comment]
Could you provide a full sample of your project ?

**Comment by andrewD123** [comment]
yes but its large. 
https://drive.google.com/open?id=1agZz1AXJzUNW40wfq8w-jxhLx35rYft9


<blockquote><img src="https://ssl.gstatic.com/docs/doclist/images/icon_14_generic_favicon.ico" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://drive.google.com/file/d/1agZz1AXJzUNW40wfq8w-jxhLx35rYft9/view?usp=drive_open&usp=embed_facebook">testapp.zip</a></strong></div></blockquote>

**Comment by jeromelaban** [comment]
Thanks for the update. This looks like there's something specific with the binding engine.

As a workaround, and better way to do so, you can write the following:

```xaml
<ComboBox x:Name="comboBox" Margin="90,58,0,0" d:LayoutOverrides="VerticalAlignment" Width="130" ItemsSource="{x:Bind MyProperty}"/>
```

There's still an issue with ElementName binding for some reason, but you'll be able to get your binding working properly.

**Comment by andrewD123** [comment]
other than chaning to x:bind did you do anything else?  I still can't get it to work with this change.

**Comment by andrewD123** [comment]
Looks like it does not work with a DP but it does work with ObservableCollection

**Comment by andrewD123** [comment]
Binding only works if its DP is not in a class.
https://drive.google.com/file/d/1DVqTfE5Y2hw9M902Ps5MgkL7zy3wsOkg/view?usp=sharing
Something is still not working correct.

**Comment by andrewD123** [comment]
Looks like if you use a class and binding by name the values still does not work.
https://drive.google.com/file/d/1DVqTfE5Y2hw9M902Ps5MgkL7zy3wsOkg/view?usp=sharing

**Comment by andrewD123** [comment]
Also if it helps I have mainpage with a Frame control that has a page.  In that page has a user control.
x:bind does not work unlike the demo app I put on this ticket.  I am not sure due the the layers of pages and controls this is causing an issue.

**Comment by jeromelaban** [comment]
A new build of the package has been published, can you revalidate ? x:Bind may still be needed.
