### ISSUE TITLE
System.ComponentModel.Win32Exception (8): Exec format error  when compiling uno webassembly in ubunto 20.04 with VSCode

### ISSUE THREAD

**Issue by egarim** [unoplatform/uno#3220]
## Current behavior

I'm testing support for visual studio code, I'm fallowing the tutorial show in here https://platform.uno/blog/announcing-uno-platform-support-for-visual-studio-code/
when I try to run the app as shown in the section Run the sample Application I get the following error
System.ComponentModel.Win32Exception (8)

## Expected behavior

To the project to compile successfully 
## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Visual studio code for ubuntu 
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-31-generic snap

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
I'm using ubuntu 20.04 as OS

**Comment by egarim** [comment]
Build log
[VsCodeUbuntu20_04_UnotWebAssembly.zip](https://github.com/unoplatform/uno/files/4672551/VsCodeUbuntu20_04_UnotWebAssembly.zip)

**Comment by jeromelaban** [comment]
Can you try updating to the latest dotnet templates :
```
dotnet new -i Uno.ProjectTemplates.Dotnet::2.4
```

And let us know if a new project generates the same error ?

**Comment by egarim** [comment]
Hi @jeromelaban  I updated the templates, the error is still the same

**Comment by MicBoucinha** [comment]
I am having the same issue on Ubuntu 18.04, even with the latest templates. Followed the tutorial on the documentation.

**Comment by jeromelaban** [comment]
This is odd. Can you make sure that the bootstrapper is using version 1.2.0 ?

See an example here:

https://github.com/unoplatform/uno/blob/386ff3a55401fedae774cb55ffd4c3fbbdd15c0b/src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj#L49-L50

**Comment by MicBoucinha** [comment]
Yes, confirmed. Those are the versions.

**Comment by jeromelaban** [comment]
@MicBoucinha do you have the exact same error as mentioned above ?

```
/home/joche/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.18/build/Uno.Wasm.Bootstrap.targets(124,5): error : System.ComponentModel.Win32Exception (8): Exec format error [/home/joche/Desktop/uno/MyApp/MyApp.Wasm/MyApp.Wasm.csproj]
/home/joche/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.18/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/home/joche/Desktop/uno/MyApp/MyApp.Wasm/MyApp.Wasm.csproj]
/home/joche/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.18/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/home/joche/Desktop/uno/MyApp/MyApp.Wasm/MyApp.Wasm.csproj]
/home/joche/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.18/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.Start() [/home/joche/Desktop/uno/MyApp/MyApp.Wasm/MyApp.Wasm.csproj]
/home/joche/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.18/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v8add3fd92e26891863414b9fa407830081f7d732.RunProcess(String executable, String parameters, String workingDirectory) in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 421 [/home/joche/Desktop/uno/MyApp/MyApp.Wasm/MyApp.Wasm.csproj]
/home/joche/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.18/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v8add3fd92e26891863414b9fa407830081f7d732.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 522 [/home/joche/Desktop/uno/MyApp/MyApp.Wasm/MyApp.Wasm.csproj]
/home/joche/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.18/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v8add3fd92e26891863414b9fa407830081f7d732.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 166 [/home/joche/Desktop/uno/MyApp/MyApp.Wasm/MyApp.Wasm.csproj]
```

**Comment by MicBoucinha** [comment]
Only the version changed which is not dev.18.

```
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error : System.ComponentModel.Win32Exception (2): No such file or directory [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.Start() [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.RunProcess(String executable, String parameters, String workingDirectory) in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 447 [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 548 [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 169 [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
```

**Comment by jeromelaban** [comment]
@MicBoucinha your error message is different though, as the error is saying that there's no such file or directory.

Could you run `dotnet run /bl` in the `/TestingUno/TestingUno.Wasm` folder, and post here the resulting `msbuild.binlog` file ?

**Comment by MicBoucinha** [comment]
Apologies, I didn't notice that difference.

I used the `dotnet build /bl` command to get the file which is attached and the output ran is:

```
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/3.1.300/MSBuild.dll -consoleloggerparameters:Summary -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/usr/share/dotnet/sdk/3.1.300/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/usr/share/dotnet/sdk/3.1.300/dotnet.dll -maxcpucount -restore -verbosity:m /bl ./TestingUno.Wasm.csproj
  Determining projects to restore...
  All projects are up-to-date for restore.
  TestingUno.Wasm -> /TestingUno/TestingUno.Wasm/bin/Debug/netstandard2.0/TestingUno.Wasm.dll
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error : System.ComponentModel.Win32Exception (2): No such file or directory [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.Start() [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.RunProcess(String executable, String parameters, String workingDirectory) in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 447 [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 548 [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 169 [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]

Build FAILED.

/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error : System.ComponentModel.Win32Exception (2): No such file or directory [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.Start() [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.RunProcess(String executable, String parameters, String workingDirectory) in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 447 [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 548 [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 169 [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.67
```

[msbuild.zip](https://github.com/unoplatform/uno/files/4688934/msbuild.zip)

Please let me know if you need more information.

Thanks!

**Comment by jeromelaban** [comment]
I see. In you case, you're missing the mono installation. 

Can you try executing this:
`$HOME/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/scripts/dotnet-setup.sh"`

The bootstrapper is missing these checks for Linux, we'll add those.

**Comment by MicBoucinha** [comment]
Hi,

After installing the latest Mono it now compiles with no errors, only the following warnings:

```
/TestingUno/TestingUno.Shared/App.xaml.cs(98,19): warning Uno0001: Windows.ApplicationModel.SuspendingOperation.GetDeferral() is not implemented in Uno [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/TestingUno/TestingUno.Shared/App.xaml.cs(56,9): warning Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PreviousExecutionState is not implemented in Uno [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/TestingUno/TestingUno.Shared/App.xaml.cs(65,8): warning Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PrelaunchActivated is not implemented in Uno [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
/TestingUno/TestingUno.Shared/App.xaml.cs(100,4): warning Uno0001: Windows.ApplicationModel.SuspendingDeferral.Complete() is not implemented in Uno [/TestingUno/TestingUno.Wasm/TestingUno.Wasm.csproj]
```
Now I can continue to explore Uno Platform in Linux.

Thanks so much for your help.

**Comment by egarim** [comment]
> @MicBoucinha your error message is different though, as the error is saying that there's no such file or directory.
> 
> Could you run `dotnet run /bl` in the `/TestingUno/TestingUno.Wasm` folder, and post here the resulting `msbuild.binlog` file ?

I ran that command as you said and the file was not generated but this is the output of the console after I ran the command 

joche@joche-GE72-2QD:~/Desktop/uno/MyApp/MyApp.Wasm$ dotnet run /bl 
/home/joche/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error : System.ComponentModel.Win32Exception (2): No such file or directory [/home/joche/Desktop/uno/MyApp/MyApp.Wasm/MyApp.Wasm.csproj]
/home/joche/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/home/joche/Desktop/uno/MyApp/MyApp.Wasm/MyApp.Wasm.csproj]
/home/joche/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/home/joche/Desktop/uno/MyApp/MyApp.Wasm/MyApp.Wasm.csproj]
/home/joche/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at System.Diagnostics.Process.Start() [/home/joche/Desktop/uno/MyApp/MyApp.Wasm/MyApp.Wasm.csproj]
/home/joche/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.RunProcess(String executable, String parameters, String workingDirectory) in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 447 [/home/joche/Desktop/uno/MyApp/MyApp.Wasm/MyApp.Wasm.csproj]
/home/joche/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 548 [/home/joche/Desktop/uno/MyApp/MyApp.Wasm/MyApp.Wasm.csproj]
/home/joche/.nuget/packages/uno.wasm.bootstrap/1.2.0/build/Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 169 [/home/joche/Desktop/uno/MyApp/MyApp.Wasm/MyApp.Wasm.csproj]

The build failed. Fix the build errors and run again.
joche@joche-GE72-2QD:~/Desktop/uno/MyApp/MyApp.Wasm$

**Comment by jeromelaban** [comment]
@egarim could you post the `msbuild.binlog` file as well ?

**Comment by egarim** [comment]
> @egarim could you post the `msbuild.binlog` file as well ?
What should be the location of that file? I did a search system-wide and I don't have it

**Comment by jeromelaban** [comment]
The file should be located next to the csproj file, generated by the `/bl` or `-bl` parameter.

**Comment by MicBoucinha** [comment]
In my case I had to run `dotnet build /bl` (build instead of run).

**Comment by jeromelaban** [comment]
This issue was fixed in latest builds of the bootstrapper.
