### ISSUE TITLE
CORS Error on Uno WebAssembly with ASP.NET Core REST API Service

### ISSUE THREAD

**Issue by berkbb** [unoplatform/uno#3232]
## Current behavior

Hi,
I got these error on WebAssembly with Uno Platform.

> Access to fetch at 'https://localhost:44318/api/search/bebek/TR' from origin 'http://localhost:49917' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I got some data responses as a JSON file from API service. The UWP app do it without error:

```
//_savedSearchList = await _dbService.SearchAsync(_keyword, _sentLanguageArgument);  // Normal database connection for UWP.

                //_savedSearchList = await _dbService.SearchAsync(_keyword, _sentLanguageArgument);  // Normal database connection for UWP.

                //Get search list for webservice.
                var link_search = $"https://localhost:44318/api/search/{_keyword.ToLower()}/{_sentLanguageArgument}";



                using (HttpClient client = new HttpClient())
                {
                    HttpResponseMessage response = await client.GetAsync(link_search);
                    Debug.WriteLine($"Http Status Code for Connection: {response.StatusCode}");
                    if (response.IsSuccessStatusCode)
                    {
                        var jsonString = await response.Content.ReadAsStringAsync();
                        _savedSearchList = JsonConvert.DeserializeObject<List<SearchResultCapsule>>(jsonString).OrderBy(t => t.IssueNumber);



                        if (_savedSearchList.Count() != 0)
                        {

                            ResultList.ItemsSource = _savedSearchList;
                            NoResult_Grid.Visibility = Visibility.Collapsed;
                        }
                    }
                }

```

What is the real problem on WebAssembly ? And how can I fix it ? Thanks.

## Expected behavior

CORS should allow the WebAssembly app for fetching.

## Environment

Nuget Package:

Package Version(s):
Uno.UI.Lottie {2.4.0}
Uno.UI.RemoteControl {2.4.0}
Uno.Wasm.Bootstrap {1.2.0}
Uno.Wasm.Bootstrap.DevServer {1.2.0}
Microsoft.Extensions.Logging.Filter {1.1.2}
Microsoft.Extensions.Logging.Con... {1.1.1}
NETStandard.Library {2.0.3}
Uno.UI {2.4.0}
Microsoft.NETCore.UniversalWindo... {6.2.10}
Microsoft.Extensions.Logging.Con... {1.1.1}
Microsoft.Extensions.Logging.Filter {1.1.2}
Microsoft.UI.Xaml {2.4.0}
Uno.Core {2.0.0}
ACM_Search_AdminApss_Shared {1.1.0}

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [X] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version:16.6 )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by berkbb** [comment]
It solved via Microsoft CORS package.

**Comment by kaki104** [comment]
> It solved via Microsoft CORS package.
Can you tell us in more detail?

**Comment by rizaanlakay** [comment]
Any details around this? Having the same issue.

**Comment by berkbb** [comment]
You can solve it via using Cors package on your server app (I splve with this documentation), details are here: https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-5.0
