### ISSUE TITLE
ProgressRing custom colors

### ISSUE THREAD

**Issue by berkbb** [unoplatform/uno#3234]
## Current behavior

Hi,

 I know globally modifying theme colors with template binding way [not supported in Uno yet.](https://stackoverflow.com/questions/61889917/cannot-change-accent-color-for-wasm-on-uno-2-4) (I tried it for ToggleSwitch, now ToggleSwitch custom style runs perfectly both on UWP and WASM). So, I prepared a custom style for WinUI 2.4 ProgressRing in a same way. I gathered the default style of ProgressRing from WinUI Github repo and customize it:

```
 <!-- Default style for Microsoft.UI.Xaml.Controls.ProgressRing -->
            <Style x:Key="AcmProgressRing" TargetType="controls:ProgressRing">
                <Setter Property="Foreground" Value="{StaticResource AcmPink}" />
                <Setter Property="Background" Value="{StaticResource AcmPurple}" />
                <Setter Property="IsHitTestVisible" Value="False" />
                <Setter Property="HorizontalAlignment" Value="Center" />
                <Setter Property="VerticalAlignment" Value="Center" />
                <Setter Property="MinHeight" Value="16" />
                <Setter Property="MinWidth" Value="16" />
                <Setter Property="IsTabStop" Value="False" />
                <Setter Property="Width" Value="32" />
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="controls:ProgressRing">
                            <Grid x:Name="LayoutRoot" Background="Transparent">
                                <VisualStateManager.VisualStateGroups>
                                    <VisualStateGroup x:Name="CommonStates">
                                        <VisualState x:Name="Active">
                                            <Storyboard>
                                                <DoubleAnimation
                                            Storyboard.TargetName="LayoutRoot"
                                            Storyboard.TargetProperty="Opacity"
                                            To="1"
                                            Duration="0:0:0.15" />
                                            </Storyboard>
                                        </VisualState>
                                        <VisualState x:Name="Inactive">
                                            <Storyboard>
                                                <DoubleAnimation
                                            Storyboard.TargetName="LayoutRoot"
                                            Storyboard.TargetProperty="Opacity"
                                            To="0"
                                            Duration="0" />
                                            </Storyboard>
                                        </VisualState>
                                    </VisualStateGroup>
                                </VisualStateManager.VisualStateGroups>
                                <!-- AnimatedVisualPlayer for Lottie -->
                                <controls:AnimatedVisualPlayer x:Name="IndeterminateAnimatedVisualPlayer" AutoPlay="false" Stretch="fill"/>

                            </Grid>
                        </ControlTemplate>
                    </Setter.Value>
                </Setter>
            </Style>
```

_**My ProgressRing is:**_

`    <controls:ProgressRing x:Name="Waiter" Width="50" Height="50" Style="{StaticResource AcmProgressRing}" IsActive="True"/>`

**_As you see, the style runs correctly on UWP:_**
![Ekran Resmi 2020-05-26 10 20 07](https://user-images.githubusercontent.com/23173536/82871592-82d2e400-9f3a-11ea-95f3-48d653dec5d2.png)

**_However, WASM shows default style :(_** 

![Ekran Resmi 2020-05-26 10 22 48](https://user-images.githubusercontent.com/23173536/82871941-fbd23b80-9f3a-11ea-9861-ec4b45859c4c.png)

## Expected behavior

WinUI ProgressRing's style on WASM must match with UWP style.

## How to reproduce it (as minimally and precisely as possible)

Add a winUI ProgressRing to MainPage.xaml and stylize it with custom style in App.xaml. Now, conmpare the view on UWP vs on WASM.
## Environment

Nuget Package:

Package Version(s):

Uno.UI.RemoteControl                {2.4.0}                                                                                                                 
Newtonsoft.Json                     {12.0.3}                                                                                                   
Uno.UI.Lottie                       {2.4.0}                                                                                                             
Uno.Wasm.Bootstrap                  {1.2.0}                                                                                                    
Uno.Wasm.Bootstrap.DevServer        {1.2.0}                                                                                                                            
ACM_Search_AdminApps.Shared         {1.1.0}                                                                                                                            
Microsoft.Extensions.Logging.Filter {1.1.2}                                                                                                                  
Microsoft.Extensions.Logging.Con... {1.1.1}                                                                                                                         
NETStandard.Library                 {2.0.3}                                                                                                        
Uno.UI                              {2.4.0}                                                                                                              
ACM_Search_AdminApps.Shared         {1.1.0}                                                                                                                  
Microsoft.NETCore.UniversalWindo... {6.2.10}                                                                                                       
Microsoft.Extensions.Logging.Con... {1.1.1}                                                                                                                        
Microsoft.Extensions.Logging.Filter {1.1.2}                                                                                                                  
Microsoft.Toolkit.Uwp.UI.Lottie     {6.0.0}                                                                                                               
Microsoft.UI.Xaml                   {2.4.2}                                                                                                   
Newtonsoft.Json                     {12.0.3}                                                                                                        
Uno.Core                            {2.0.0}                                    
Affected platform(s):

- [x] iOS
- [x] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [X] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: 16.6)
- [ ] for Mac (version: )

Relevant plugins:

- [X] Resharper (version: 2020.1.3)

**Comment by carldebilly** [comment]
I just added "iOS" & "Android" to your list of affected platforms: right now you cannot change the variables inside a Lottie animation like it's done on UWP to change the colors of the ProgressRing.

**Comment by carldebilly** [comment]
This feature is now available in [Uno.UI v3.4.0-dev.222](https://www.nuget.org/packages/Uno.UI/3.4.0-dev.222)
@agneszitte-nventive @berkbb
