### ISSUE TITLE
[HotReload] Enhance experience by integrating with `InitializeComponent`

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#3239]
## Current behavior

Reloading a XAML with codebehing does not work properly.

## Environment

Nuget Package: 3.0-dev

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
@jeromelaban  Is this still relevant?

**Comment by jeromelaban** [comment]
It's fixed, thanks.
