### ISSUE TITLE
[UITesting] Add UI Test project in dotnet new and vsix experiences

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#3241]
## What would you like to be added:

Add a `dotnet new` and VSIX Uno.UITest project experience, using the structure provided by Uno.UITest.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [x] Solution Templates

**Comment by Youssef1313** [comment]
I'm going to try with this one :)

**Comment by Youssef1313** [comment]
@jeromelaban Actually there is already a dotnet new template:

https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-uitest/.template.config/template.json

Is the needed work to make it available in VSIX? or I'm missing something?

**Comment by Youssef1313** [comment]
For reference, it was added in https://github.com/unoplatform/uno/pull/5058.

**Comment by Youssef1313** [comment]
@jeromelaban I just noticed the template actually exists in VS.

![image](https://user-images.githubusercontent.com/31348972/136048887-58a6154b-eb40-4592-9b4d-ed4ba8c3dca5.png)

However, I can't see anything related in VSIX2019 or VSIX2022 projects. The only related thing is `vs-2017.3.host.json` in `Uno.ProjectTemplates.Dotnet`.

I had though this project is only for command line.

**Comment by jeromelaban** [comment]
It exists because it's present in the dotnet new templates if installed by the user.
