### ISSUE TITLE
Attached properies don't work with UserControl (DependencyProperty.RegisterAttached)

### ISSUE THREAD

**Issue by jeanplevesque** [unoplatform/uno#3243]
## Current behavior

Attached properties don't work on `UserControl` like they work on  `Control`.

## Expected behavior

Attached properties work on `UserControl` like they work on any other `Control`.

## How to reproduce it (as minimally and precisely as possible)

1. Create an attached property (using `DependencyProperty.RegisterAttached`).
1. Create a `UserControl`.
1. Use the attached property on the `UserControl`.
1. Update the attached property via regular binding.
1. Notice that the `propertyChangedCallback` isn't called.
  You'll also notice an System.InvalidCastException in BindableMetadata.g.cs if you have the exceptions attached.

Note that using the following workaround doesn't fix the bug:
```xml
<UnoSkipUserControlsInVisualTree>false</UnoSkipUserControlsInVisualTree>
```

## Workaroud
Create a class (like "AttachableUserControl") that inherits from `UserControl` and use that everywhere you would use `UserControl`.

## Environment

Nuget Package:

Package Version(s): 2.1.37

Affected platform(s):

- [x] iOS (yes, tested)
- [x] Android (yes, tested)
- [ ] WebAssembly (not tested)
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS (not tested)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

**Comment by jeromelaban** [comment]
I'm not able to reproduce this issue with neither 2.1.37 or the latest 3.0 dev bits. Here's the sample I used: 
[UserControlTest2.zip](https://github.com/unoplatform/uno/files/4711035/UserControlTest2.zip).

**Comment by jeromelaban** [comment]
Scratch that. The property is not attached to the proper object, it's attached to the first element of the usercontrol, not the user control itself.
