### ISSUE TITLE
[Android] TextBlock inside Viewbox may not update correctly

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#3248]
## How to reproduce it (as minimally and precisely as possible)

1. Update https://github.com/unoplatform/calculator to latest Uno
2. Launch on Android
3. Navigate to a Converter page (eg Volume)
4. Enter numbers

## Current behavior

Value and converted value displays don't update (note however the 'supplementary' values do update)

## Expected behavior

Values should update

## Notes

Preliminary debugging: the managed `TextBlock.Text` value is being set correctly, but `TextBlock.MeasureOverride()` and `ArrangeOverride()` never get called. They do not get called because the `IsLayoutRequested` of the parent has gotten stuck in a bad state.

This seems to be the result of recent changes to `Viewbox`, https://github.com/unoplatform/uno/commit/cfe88c8446e818e8fbd9cac615e968b5c7447edc and https://github.com/unoplatform/uno/commit/cfe88c8446e818e8fbd9cac615e968b5c7447edc - reverting those two commits removes the bug.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
@dr1rrb

**Comment by carldebilly** [comment]
@sakshi173 could you assess if this bug still present?

**Comment by sakshi173** [comment]
@carldebilly , I verified this issue is fixed.
