### ISSUE TITLE
AutoCompleteBox and Other TextBox's Style Cannot Match With UWP on WASM.

### ISSUE THREAD

**Issue by berkbb** [unoplatform/uno#3264]
## What would you like to be added:
Hi, I customize the font and corner radius of AutoCompleteBox. The style of AutoCompeteBox looks like it should be seen in UWP.

```
  <AutoSuggestBox x:Name="KeywordSearchBox" CornerRadius="{StaticResource OverlayCornerRadius}"
                        RequestedTheme="Dark"
                        FontFamily="Noto Sans Display" FontWeight="Normal" FontSize="16" 
                        MaxWidth="300" QueryIcon="Find" VerticalAlignment="Stretch" HorizontalAlignment="Stretch" Margin="0,10,0,10" />
```
**UWP Style:**
![1](https://user-images.githubusercontent.com/23173536/83230665-d7709c00-a192-11ea-9f8e-1e75954231c8.jpg)

**WASM Style:**
![2](https://user-images.githubusercontent.com/23173536/83231309-fb80ad00-a193-11ea-9f9a-5b8ba9e19815.jpg)

## Why is this needed:

The styles of a lot of components match with UWP style in WASM project. However, AutoCompleteBox and other TextBox's style match seems to be forgotten.

## For which Platform:

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
The current styles that are applied in Uno are dating a bit, and are not matching the latest UWP styles. We're going to be adopting the styles coming from WinUI 2.4+ soon, which will ensure that the visual aspect of controls will be appropriate. I'm closing this issue in favor of https://github.com/unoplatform/uno/issues/3264

**Comment by robloo** [comment]
In favor of #3291 I think.
