### ISSUE TITLE
Skia rendering

### ISSUE THREAD

**Issue by ILAgent** [unoplatform/uno#3267]
Please consider rendering on the canvas through Skia. Xamarin doesn't look promising. Nobody wants to use it nowadays.

**Comment by jeromelaban** [comment]
Thanks for your feedback! 

Regardless of the use of Xamarin bindings (and not Xamarin.Forms, which is not used by Uno, native rendering is particularly important for native interactions such as accessibility and IME features, but also where native controls look and feel is required.

Yet, we recognize that it does not fit for every use case, particularly for Linux, and we're looking at adding support for Skia rendering.

You can follow this work on https://github.com/unoplatform/uno/issues/670
