### ISSUE TITLE
Strings from resource files break XAML code generator

### ISSUE THREAD

**Issue by lextm** [unoplatform/uno#3272]
## Current behavior

Compilation of macOS project failed with error messages,

```
Error
CS1912
Duplicate initialization of member 'Text'
textblockbug.macOS
C:\Users\lextm\source\repos\textblockbug\textblockbug.macOS\obj\iPhoneSimulator\Debug\g\XamlCodeGenerator\MainPage_dd738e8ee0557d8547c78fbde055b8a1.g.cs
75
Active
```
and 
```
Error
CS1003
Syntax error, ',' expected
textblockbug.macOS
C:\Users\lextm\source\repos\textblockbug\textblockbug.macOS\obj\iPhoneSimulator\Debug\g\XamlCodeGenerator\MainPage_dd738e8ee0557d8547c78fbde055b8a1.g.cs
75
Active
```

## Expected behavior

macOS project should compile successfully.

## How to reproduce it (as minimally and precisely as possible)
1. Clone https://github.com/lextm/textblockbug
1. Compile and run its UWP project to confirm it's working.
1. Compile its macOS project and observe the compilation errors.

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.4.0

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.6.0)
- [ ] for Mac (version: )

**Comment by Xiaoy312** [comment]
This is a limitation with the xaml parser that uno is currently using. The situation here is a bit complicated with nesting, implicit content and localization all into play.

In the mean time, you can workaround this issue by moving the *implicit content* into the `Text` property:
```diff
-<Span xml:space="preserve"><Run x:Uid="SettingsAboutWebsite">Website: </Run><Hyperlink NavigateUri="https://github.com/QL-Win/QuickLook">Link</Hyperlink></Span>
+<Span xml:space="preserve"><Run x:Uid="SettingsAboutWebsite" Text="Website: " /><Hyperlink NavigateUri="https://github.com/QL-Win/QuickLook">Link</Hyperlink></Span>

**Comment by Xiaoy312** [comment]
related: #3041

**Comment by jeromelaban** [comment]
Thanks @Xiaoy312! This is indeed something that will be addressed once we migrate to the System.Xaml parser.
