### ISSUE TITLE
FontWeight class does not match UWP definition

### ISSUE THREAD

**Issue by lextm** [unoplatform/uno#3273]
## Current behavior

Uno's `FontWeight.Weight` is read only.

https://github.com/unoplatform/uno/blob/2.4.0/src/Uno.UWP/UI/Text/FontWeight.cs#L14

## Expected behavior

It should be read/write, as UWP defines it like

https://docs.microsoft.com/en-us/uwp/api/windows.ui.text.fontweight.weight?view=winrt-19041

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.4

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.6.0)
- [ ] for Mac (version: )

## Anything else we need to know?
There is also a type mismatch, as UWP's `Weight` is `ushort`, while Uno uses `int`.

**Comment by jeromelaban** [comment]
Thanks for the report! Indeed, it should not be read-only, and that's an easy adjustment.
