### ISSUE TITLE
Full Width Issue on WASM for iOS WKWebView If Device Status is Landscape.

### ISSUE THREAD

**Issue by berkbb** [unoplatform/uno#3275]
## Current behavior

WASM project is looking good on iOS WKWebView on iPhone X if device is Portrait. However, if I reposition the device as landscape, big white empty areas shown On both sides of the screen.

**Portrait:**

![IMG_0593](https://user-images.githubusercontent.com/23173536/83349840-6cfd5e80-a340-11ea-9c46-f1f5a23a16a8.PNG)

**Landscape:**

![IMG_0594](https://user-images.githubusercontent.com/23173536/83349842-6f5fb880-a340-11ea-92b2-51bd5df96376.PNG)

**If I reposition the device as Portrait:**

![IMG_0595](https://user-images.githubusercontent.com/23173536/83349844-72f33f80-a340-11ea-9545-6bc67d7a3a91.PNG)

## Expected behavior

Full screen WASM on iOS devices like iPhone X if device is landscape.

## How to reproduce it (as minimally and precisely as possible)

Create a new Uno project from template and try it's WASM project on iOS (Not iPadOS) WKWebView while device is landscape. Issue will throw on smaller screen devices like iPhone X (I used).
## Environment

Nuget Package:

Package Version(s):

Uno.UI.RemoteControl                {2.4.0}   
Newtonsoft.Json                     {12.0.3} 
Uno.UI.Lottie                       {2.4.0}
Uno.Wasm.Bootstrap                  {1.2.0} 
Uno.Wasm.Bootstrap.DevServer        {1.2.0}
ACM_Search_AdminApps.Shared         {1.1.0} 
Microsoft.Extensions.Logging.Filter {1.1.2}
Microsoft.Extensions.Logging.Con... {1.1.1} 
NETStandard.Library                 {2.0.3}
Uno.UI                              {2.4.0} 
ACM_Search_AdminApps.Shared         {1.1.0}
Microsoft.NETCore.UniversalWindo... {6.2.10}
Microsoft.Extensions.Logging.Con... {1.1.1}
Microsoft.Extensions.Logging.Filter {1.1.2}
Microsoft.Toolkit.Uwp.UI.Lottie     {6.0.0}
Microsoft.UI.Xaml                   {2.4.2}
Newtonsoft.Json                     {12.0.3}
Uno.Core                            {2.0.0}
Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: 16.6)
- [ ] for Mac (version: )

Relevant plugins:

- [X] Resharper (version: 2020.3.1 )

**Comment by jeromelaban** [comment]
Thanks for the report!

This is something that is generally handled using the [`VisibleBoundsPaddingBehavior`](https://github.com/unoplatform/uno/blob/a13c7b2ecbbf70facf1533ba9f0740c364a7a590/doc/articles/features/VisibleBoundsPadding.md) on the other platforms, but it's not yet implemented on WebAssembly.

## For the contributors

Implementing this requires updating the default body style from the bootstrapper, and provide an implementation for the `ApplicationView.VisibleBounds` property.

**Comment by berkbb** [comment]
Hi, adding a new .css and .js file on load is fix my problem on landscape.

**CSS:**

```
body {
    background-color: #B8C282 !important;
    padding: 20px;
    padding-top: env(safe-area-inset-top);
    padding-right: env(safe-area-inset-right);
    padding-bottom: env(safe-area-inset-bottom);
    padding-left: env(safe-area-inset-left);
}
@supports(padding: max(0px)) {

    body {
        background-color: #B8C282 !important;
        padding-left: max(20px, env(safe-area-inset-left));
        padding-right: max(20px, env(safe-area-inset-right));
        padding-bottom: max(20px, env(safe-area-inset-bottom));
        padding-top: max(20px, env(safe-area-inset-top));
    }
}
```
**JS:**
```
// Edititng the viewport meta for notch.    https://stackoverflow.com/questions/2568760/is-it-possible-to-use-javascript-to-change-the-meta-tags-of-the-page
document.querySelector('meta[name=viewport]').setAttribute('content', 'width=device-width,minimum-scale=1.0,initial-scale=1.0,maximum-scale=1.0,user-scalable=no,viewport-fit=cover');
```


![Ekran Resmi 2020-06-02 20 34 32](https://user-images.githubusercontent.com/23173536/83552026-cd8fc580-a511-11ea-94c5-7d67315e95fe.png)


However, as you seen, if I rotate the device to re-portrait again. the html tag shrinks upwards. If I did pinch and zoom --> zoom out , returns to its true size. It seems a Uno.css problem. What will the exact solution @jeromelaban @carldebilly ? Thanks. 

P.S: You can try it on iOS Webkit - Safari with this [link](https://acmsearch.azurewebsites.net/)
