### ISSUE TITLE
dotnet new wasmxfhead Generation Issue

### ISSUE THREAD

**Issue by IgorAtDigi** [unoplatform/uno#3285]
Hello,

I am pretty new to the Uno Platform and wanted to test "Uno Platform WebAssembly support for Xamarin Forms". I followed the instructions on: https://github.com/unoplatform/uno/blob/master/doc/articles/get-started-dotnet-new.md 

As soon as I execute "dotnet new wasmfxhead", in the solution-folder, I see that the project "xamarinApp.Wasm" is generated, but shortly after that I get an Exception with the message
"Could not find project or directory `UnoQuickStart.Wasm`."

I use the uno platform templates 2.4. 

Here is the full output of the command:
______________________________________________________________
The template "Uno Platform WebAssembly Head for Xamarin.Forms" was created successfully.

Processing post-creation actions...
Adding project reference(s) to solution file. Running dotnet sln E:\Projects\xxx\Main\xxx\xxx.sln add UnoQuickStart.Wasm
Failed to add project(s) UnoQuickStart.Wasm to solution file E:\Projects\xxx\Main\xxx\xxx.sln
Output from command:
Usage: dotnet sln <SLN_FILE> add [options] <PROJECT_PATH>

Arguments:
  <SLN_FILE>       The solution file to operate on. If not specified, the command will search the current directory for one.
  <PROJECT_PATH>   The paths to the projects to add to the solution.

Options:
  --in-root               Place project in root of the solution, rather than creating a solution folder.
  -s, --solution-folder   The destination solution folder path to add the projects to.
  -h, --help              Show command line help.

Could not find project or directory `UnoQuickStart.Wasm`.
______________________________________________________________
Maybe someone knows what this is about.

Thanks in advance.

**Comment by jeromelaban** [comment]
Indeed it's not working properly. 

As workaround, you can manually add the Wasm project that was added in the solution.
