### ISSUE TITLE
Implement UWP lifecycle events

### ISSUE THREAD

**Issue by pdecostervgls** [unoplatform/uno#3286]
## What would you like to be added:
The ```Application.Suspending``` and ```Application.Resuming``` lifecycle events as described in: https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Application to get notifications when the app is suspending.

## Why is this needed:
I'm working on an app where a Bluetooth Connection need to be terminated the moment the app suspends.

## For which Platform:

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?
https://blogs.windows.com/windowsdeveloper/2016/04/28/the-lifecycle-of-a-uwp-app/

**Comment by jeromelaban** [comment]
Thanks for the report!

Those events are implemented on both iOS and Android. Could you tell us what's not working there ?

**Comment by pdecostervgls** [comment]
My apologies, I understood from our conversation on gitter that they weren't. I'll go implement it and let you know if I run into issues.

**Comment by pdecostervgls** [comment]
Seems like they are indeed implemented as you said. It all works now.
