### ISSUE TITLE
 Value was either too large or too small for a UInt32 Error on iOS WKWebView

### ISSUE THREAD

**Issue by berkbb** [unoplatform/uno#3287]
## Current behavior

Hi,

I have an Uno WebAssembly app at [here](https://acmsearch.azurewebsites.net/), you can try it now.
 Button click events **not fire and doing nothing sometimes** both on iOS and iPadOS WKWebview. They rarely work without problems. Sometimes cleaning web cache from Settings / Safari / Advanced Settings is solves problem. Unfortunately, this error is coming up again soon.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23173536/83558683-0cc31400-a51c-11ea-8586-eef73e548b0e.gif)

 I have not any issue on desktop browser, the app running smoothly. I have iPhone X, iPad and iPhone 6. . The app works rarely without problems on X. Seems not run on others. The WebAssembly log on iOS is here:

[click.log](https://github.com/unoplatform/uno/files/4719089/click.log)

Is it depends on device RAM size on Apple Device ? The app runs just perfectly on Android WebView.
## Expected behavior

iOS WKWebView should run the application smoothly like a desktop browser.

## How to reproduce it (as minimally and precisely as possible)

You can try at [here](https://acmsearch.azurewebsites.net/)

## Environment

Nuget Package:

Package Version(s):

Uno.UI.RemoteControl {2.4.0}
Newtonsoft.Json {12.0.3}
Uno.UI.Lottie {2.4.0}
Uno.Wasm.Bootstrap {1.2.0}
Uno.Wasm.Bootstrap.DevServer {1.2.0}
ACM_Search_AdminApps.Shared {1.1.0}
Microsoft.Extensions.Logging.Filter {1.1.2}
Microsoft.Extensions.Logging.Con... {1.1.1}
NETStandard.Library {2.0.3}
Uno.UI {2.4.0}
ACM_Search_AdminApps.Shared {1.1.0}
Microsoft.NETCore.UniversalWindo... {6.2.10}
Microsoft.Extensions.Logging.Con... {1.1.1}
Microsoft.Extensions.Logging.Filter {1.1.2}
Microsoft.Toolkit.Uwp.UI.Lottie {6.0.0}
Microsoft.UI.Xaml {2.4.2}
Newtonsoft.Json {12.0.3}
Uno.Core {2.0.0}

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: 16.6.1 )
- [ ] for Mac (version: )

Relevant plugins:

- [X] Resharper (version: 2020.3.1 )

**Comment by jeromelaban** [comment]
This issue was fixed in Uno 2.4.4 by https://github.com/unoplatform/uno/pull/3245

**Comment by berkbb** [comment]
I'm encountered a issue like it on iPhone 6. Fix in Uno.UI 2.4.4 and later is seems working on iPhone X, iPad Pro 2016 vs. which are have at least 2 GB Ram. Is iPhone 6's 1 GB RAM causes it ? You can test it with my[ WebAssembly app on Azure](https://acmsearch.azurewebsites.net).

[iPhone6.log](https://github.com/unoplatform/uno/files/4730237/iPhone6.log)

![ezgif com-optimize](https://user-images.githubusercontent.com/23173536/83761303-cb974500-a67e-11ea-91d4-5fdb66098d58.gif)
