### ISSUE TITLE
Import the WinUI 2.4 Styles

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#3291]
## What would you like to be added:

The styles included in Uno are dating from a mix of previous versions from UWP. Aligning with the WinUI 2.4+ styles is needed to align the visual aspect of controls.

This issue is dependent on #1766

## Related
- https://github.com/unoplatform/uno/issues/3264

**Comment by davidjohnoliver** [comment]
_Note for contributors:_
This essentially entails adding a `XamlControlsResources` resource dictionary, containing the WinUI 2.x default styles, to allow for the same usage as on UWP (https://docs.microsoft.com/en-us/windows/apps/winui/winui2/getting-started):

```xaml
<Application>
    <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
    </Application.Resources>
</Application>
```

**Comment by davidjohnoliver** [comment]
The Fluent styles are now available - see https://github.com/unoplatform/uno/blob/master/doc/articles/features/fluent-styles.md for instructions on using them
