### ISSUE TITLE
Upgrade android usage to avoir deprecated APIs

### ISSUE THREAD

**Issue by jeanplevesque** [unoplatform/uno#3304]
## What would you like to be added:

The deprecated APIs listed below (screenshot) should not be used.

## Why is this needed:

The pre-launch report from Google Play Store outputs the following warnings:

![image](https://user-images.githubusercontent.com/39710855/83766421-6a557e80-a64a-11ea-9687-d89276ff0108.png)

## For which Platform:

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

This is using Uno.UI version 1.45.

**Comment by jeromelaban** [comment]
Thanks for the report! This is fixed in Uno 2.4.x with Android10 support.

**Comment by jeanplevesque** [comment]
Great! Thank you :)
