### ISSUE TITLE
[android]ImageSource does not support direct Stream assignment

### ISSUE THREAD

**Issue by 1106245966** [unoplatform/uno#3307]
`avatar.Source = new ImageSource(file.GetStream())`
report errors “ImageSource does not support direct Stream assignment”

**Comment by jeromelaban** [comment]
Thanks for the report! 

This is not a WinUI supported operation and will be removed soon. You can use [BitmapImage.SetSourceAsync](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.bitmapsource.setsourceasync?view=winrt-19041) instead.
