### ISSUE TITLE
Windows Community Toolkit fails after update to latest preview Uno.UI package

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3315]
## Current behavior

After upgrading Uno.UI to the latest version (3.0.0-dev.412), using Uno.Microsoft.Toolkit.Uwp (6.1.0-build.71.g38c59ea2a0) causes build error on Android and iOS:

```
Mono.Linker.MarkException: Error processing method: 
'System.Void Microsoft.Toolkit.Uwp.UI.Controls.GlobalStaticResources/<>c::
<get_SystemControlVSNotificationButtonBackgroundBrush___HighContrast>b__89_0(
Windows.UI.Xaml.Media.SolidColorBrush)' in assembly: 'Microsoft.Toolkit.Uwp.UI.Controls.dll' 
---> Mono.Cecil.ResolutionException: Failed to resolve Windows.UI.Color
 Uno.UI.GlobalStaticResources::get_SystemColorWindowColor()
```

## Expected behavior

No build error.

## How to reproduce it (as minimally and precisely as possible)

Reference latest preview version of Uno.UI and Uno.Microsoft.Toolkit.Uwp packages.

## Environment

Nuget Package: Uno.UI

Package Version(s): 3.0.0-dev.412

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
It's expected, we'll be updating it to use the proper version soon.

**Comment by dp901** [comment]
Upgrading to the latest Uno.UI (3.0.0-dev618) gives me a different error, I don't know if this is part of the same problem: 
`Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Void Microsoft.Toolkit.Uwp.UI.Controls.DataGridComboBoxColumn::set_FontWeight(Windows.UI.Text.FontWeight)' in assembly: 'Microsoft.Toolkit.Uwp.UI.Controls.DataGrid.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Int32 Windows.UI.Text.FontWeight::get_Weight()`

**Comment by jeromelaban** [comment]
@dp901 yes, this is expected as well, it will be fixed in the same batch.

**Comment by EdBlacker** [comment]
We'd like to use MSAL so we need to upgrade beyond 3.0.0-dev.471, but we also use the toolkit and after upgrading to v3.0.0-dev.636 we get
Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Object Microsoft.Toolkit.Uwp.UI.Controls.GlobalStaticResources::get_TabViewItemHeaderBackground()' in assembly: 'Microsoft.Toolkit.Uwp.UI.Controls.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Windows.UI.Xaml.Media.SolidColorBrush Uno.UI.GlobalStaticResources::get_SystemControlTransparentBrush()	
\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets	124

**Comment by jeromelaban** [comment]
The latest published packages for Uno.Microsoft.Toolkit.* are now compatible with the latest Uno 3.0 dev bits.
