### ISSUE TITLE
[WASM] Cannot load theme resources programmatically

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3331]
## Current behavior

In WASM attempting to load a theme resource with something like,

Windows.UI.Xaml.Application.Current.Resources["SystemAltHighColor"]

returns null.  This worked previously, verified in version 2.4.0.

## Expected behavior

WASM should load resources programmatically.

## How to reproduce it (as minimally and precisely as possible)

Launch the attached project, and notice that Grid background is correctly changed from green to SystemAltHighColor.  Launch the project and notice that Grid remains green, with error message in console regarding null object.

[App48.zip](https://github.com/unoplatform/uno/files/4747226/App48.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
3.0.0-dev.414
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by DierkDroth** [comment]
@jeromelaban FYI this is a regression which is getting in our way to finally get AOT working.

**Comment by davidjohnoliver** [comment]
@peternary @DierkDroth Thanks for the report, this will be fixed ASAP.
