### ISSUE TITLE
[WASM] Cannot attach event handler in ItemContainerStyle DataTemplate

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3332]
## Current behavior

Assigning an event handler to a control defined a Template defined inside an ItemContainerStyle will cause the control to fail at runtime.

This is a regression, worked previously in 2.4.0

## Expected behavior

Event handler should be correctly attached.

## How to reproduce it (as minimally and precisely as possible)

Launch the attached project in UWP and observe that the ListView renders correctly.  If desired, place a breakpoint in the OnRowPointerPressed method of MainPage.Xaml.cs and observe that it is hit.

Launch the same project in WASM and observe that the ListView does not render.

[ItemContainerEvent.zip](https://github.com/unoplatform/uno/files/4747431/ItemContainerEvent.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
3.0.0-dev.414
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by DierkDroth** [comment]
@davidjohnoliver would be great if you could look into that one as well. Thx

**Comment by jeromelaban** [comment]
@DierkDroth this is a different issue. Can you make sure this one is referenced in your list ? Thanks!

**Comment by DierkDroth** [comment]
@jeromelaban it's already on the list.
