### ISSUE TITLE
[any-plat][NavigationView] burger menu button width is bugged when light-dismissed

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#3339]
## Current behavior
The `NavigationView`'s burger menu (`TogglePaneButton`) button width is bugged when light-dismissed:
![Uno Material header dissapear](https://user-images.githubusercontent.com/49959074/83568891-b640e000-a4f1-11ea-95dd-40cac4695933.gif)

## Expected behavior
Should not happen.

## How to reproduce it (as minimally and precisely as possible)
1. choose one:
   1. launch SampleApp & navigate to: NagivationView > NavigationViewSample
   2. build & launch https://github.com/unoplatform/Uno.Material
2. tap the `≡` burger menu button
3. tap anywhere on the right dark area to light-dismiss
4. press the header area (or, press and hold to observe the hit-box)
\---
to reset this behavior, just open and close it normally via the on-screen `<-` back button.

## Environment

Nuget Package: Uno.UI
Package Version(s): 3.0.0-feature.styles-compat.216

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio: 2019
Relevant plugins: n/a

## Anything else we need to know?
workaround: you can change the menu button's and its container's background to transparent to prevent the header from being blocked.
see also: https://github.com/unoplatform/Uno.Material/issues/121

**Comment by davidjohnoliver** [comment]
Can you check with latest Uno master? (There's no need to be on the feature package any more, the Styles changes have been merged.) There was a bug with the NavigationView TogglePaneButton width that was already fixed.

**Comment by Xiaoy312** [comment]
The issue is still present with `3.0.0-dev.414`.
