### ISSUE TITLE
Prism template relies on myget version of Prism.DryIoc.Uno and recent versions don't work on iOS

### ISSUE THREAD

**Issue by MatFillion** [unoplatform/uno#3349]
Seems like 2 issues:
1- recent versions of Prism.DryIoc.Uno have problems on iOS
2- the template relies on -ci packages only available in a myget feed.

## Current behavior
Current template includes a nuget.config file to add a nuget feed.
If you remove the nuget.config you get this log
```
NU1603: BenefitsPlatform.Droid depends on Prism.DryIoc.Uno (>= 8.0.0.1717-ci) but Prism.DryIoc.Uno 8.0.0.1717-ci was not found. An approximate best match of Prism.DryIoc.Uno 8.0.0.1740-pre was resolved.
NU1603: BenefitsPlatform.iOS depends on Prism.DryIoc.Uno (>= 8.0.0.1717-ci) but Prism.DryIoc.Uno 8.0.0.1717-ci was not found. An approximate best match of Prism.DryIoc.Uno 8.0.0.1740-pre was resolved.
NU1603: BenefitsPlatform.Uwp depends on Prism.DryIoc.Uno (>= 8.0.0.1717-ci) but Prism.DryIoc.Uno 8.0.0.1717-ci was not found. An approximate best match of Prism.DryIoc.Uno 8.0.0.1740-pre was resolved.
```
And also the shell.xaml never displays on iOS

## Expected behavior

Recent versions of Prism.DryIoc.Uno work fine on iOS
Template relies on packages available on nuget.org (ideally?)

## How to reproduce it (as minimally and precisely as possible)

Create a template using the dotnet new. Remove nuget.config
## Environment

Nuget Package: template 2.4

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
The iOS issue was fixed by https://github.com/PrismLibrary/Prism/pull/2139. The version issue is still pending.

**Comment by francoistanguay** [comment]
Can this be closed?

**Comment by jeromelaban** [comment]
Fixed
