### ISSUE TITLE
Uno Lottie compiles with error for Android

### ISSUE THREAD

**Issue by Massimo37** [unoplatform/uno#3354]
## Current behavior

Following the docs for using Lottie with AnimatedVisualPlayer:

[Lottie For Uno](https://github.com/unoplatform/uno/blob/371e78adf6ec6305c84ce9262e665871f03f1dd2/doc/articles/features/Lottie.md)

the following error occurs on compilation:

`Xamarin\Android\Xamarin.Android.Common.targets(1660,2): error XA2002: Can not resolve reference: `Lottie.Android`, referenced by `Uno.UI.Lottie`.`

## Expected behavior

Project should compile normally.

Compile attached project

[LottieSample.zip](https://github.com/unoplatform/uno/files/4771295/LottieSample.zip)

## Environment

Nuget Packages:

**Uno.UI** 2.2.0
**Uno.UI.Lottie** 2.2.0
**Microsoft.UI.Xaml** 2.4.2
**Microsoft.Toolkit.Uwp.UI.Lottie** 6.0.0

Affected platform(s):

- [X] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

**Comment by jeromelaban** [comment]
Could you add the Uno.UI version you tested ?

**Comment by Massimo37** [comment]
Done 👍

**Comment by Massimo37** [comment]
Updated description since similar error occurs on iOS as well.
