### ISSUE TITLE
MSAL: not working for AAD B2C on Wasm

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#3355]
# Bug
Using AzureAD B2C on Wasm will lead to a problem with CORS accessing the final token call.

This bug is well described by @ibebbs on this issue: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1865

Nuget Package: `Uno.UI.MSAL`

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by ibebbs** [comment]
@carldebilly, the Azure AD B2C team have deployed an update which seems to resolve this issue (I was successfully able to use MSAL.net from WASM to authenticate). I've requested that AzureAD/microsoft-authentication-library-for-dotnet#1865 be closed and think this one can be closed now too.
