### ISSUE TITLE
[WASM] ComboBoxItem doesn't stretch horizontally

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#3357]
Related GitHub Issue: https://github.com/unoplatform/Uno.Material/issues/12

## Current behavior

ComboBoxItem doesn't stretch horizontally for WebAssembly.

**WASM**
![image](https://user-images.githubusercontent.com/16295702/84520940-4b866600-aca2-11ea-8eb6-0791f2f88f50.png)

**UWP**
![image](https://user-images.githubusercontent.com/16295702/84520685-f185a080-aca1-11ea-91c9-b7ea355c8fab.png)

**Android**
![image](https://user-images.githubusercontent.com/16295702/84520758-0b26e800-aca2-11ea-851b-1c2171f8c482.png)

**iOS**
![image](https://user-images.githubusercontent.com/16295702/84520811-1da12180-aca2-11ea-906c-ac28e316c7d2.png)

## Expected behavior

ComboBoxItem should stretch horizontally by default like for the other platforms.

## How to reproduce it (as minimally and precisely as possible)

```
<ComboBox MinWidth="150"
		  HorizontalAlignment="Left"
		  PlaceholderText="TestPlaceholder">
			<ComboBoxItem Content="A"
						  Background="DeepPink" />
			<ComboBoxItem Content="B" />
			<ComboBoxItem Content="C" />
</ComboBox>
```

## Environment

Nuget Package: Uno.UI

Package Version(s): 3.0.0-dev.476

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: 16.5.4)
- [ ] for Mac (version: )

**Comment by agneszitte-nventive** [comment]
The issue seems to be at the ItemsPresenter/CarouselPanel level
![image](https://user-images.githubusercontent.com/16295702/84522059-f2b7cd00-aca3-11ea-888a-5c5b2850daab.png)

**Comment by agneszitte-nventive** [comment]
Other related ComboBox Issue : https://github.com/unoplatform/uno/issues/3358

**Comment by agneszitte-nventive** [comment]
@jeromelaban / @davidjohnoliver after some investigation in Uno, here is what I found.
**CarouselPanel** for **WASM** is using **ItemsStackPanelLayout** that is based on **VirtualizingPanelLayout**.

And for the ShouldBreadthStretch

**Comment by agneszitte-nventive** [comment]
@jeromelaban / @davidjohnoliver after some investigation in Uno, here is what I found.
**CarouselPanel** for **WASM** is using **ItemsStackPanelLayout** that is based on **VirtualizingPanelLayout**.

And for the **VirtualizingPanelLayout**, **ShouldBreadthStretch** is set to **false** because it's inside a popup in the case of the **ComboBox**.

Related to this previous PR(https://github.com/unoplatform/uno/pull/2745) in regards to this previous issue(https://github.com/unoplatform/uno/issues/2680).

If I change the **ShouldBreadthStretch** value to **true**, it fixes my current issue but I'm able to see the previous issue.

I'm in the process of finding a solution that can accommodate both issues at the same time.
i.e. not having the width of the popup bigger than the ComboBox, but still having the ability to stretch the content inside the popup.

**Comment by agneszitte-nventive** [comment]
@davidjohnoliver / @jeromelaban 
I'm not currently working on it anymore. Will come back to it if I have the time.
Feel free to grab the issue in the meantime.

**Comment by MatFillion** [comment]
@StewartPolsky is this still an issue?
