### ISSUE TITLE
[All Platforms] ComboBox PlaceholderText is not displayed by default

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#3358]
## Current behavior  

ComboBox PlaceholderText is not displayed by default when starting with a new Uno Solution without any additional styles.

**UWP**
![image](https://user-images.githubusercontent.com/16295702/84522792-4676e600-aca5-11ea-89c0-70e0ad80f6c8.png)

**iOS**
![image](https://user-images.githubusercontent.com/16295702/84522834-5393d500-aca5-11ea-9b26-e9904d414493.png)

**Android**
![image](https://user-images.githubusercontent.com/16295702/84522899-6b6b5900-aca5-11ea-8a53-043e6f048311.png)

**WASM**
![image](https://user-images.githubusercontent.com/16295702/84522950-8342dd00-aca5-11ea-9666-044f3b262522.png)

## Expected behavior

ComboBox PlaceholderText should be displayed with the default Uno style like in UWP

## How to reproduce it (as minimally and precisely as possible)

Start with a new Uno Project (Without any additional style for the ComboBox) and use a ComboBox with the PlaceholderText property.

```
<ComboBox MinWidth="150"
		  HorizontalAlignment="Left"
		  PlaceholderText="TestPlaceholder">
			<ComboBoxItem Content="A" />
			<ComboBoxItem Content="B" />
			<ComboBoxItem Content="C" />
</ComboBox>
```

## Environment

Nuget Package: Uno.UI

Package Version(s): 3.0.0-dev.476

Affected platform(s):

- [X] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: 16.5.4)
- [ ] for Mac (version: )

**Comment by Xiaoy312** [comment]
Related to: #1055

The PlaceholderTextBlock, nested under the ContnetPrenter, didnt inherit the TemplatedParent properly, thus causing its text TemplateBinding to fail.
