### ISSUE TITLE
[WASM] Files not persisted

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3376]
## Current behavior

Files created in WASM are not persisted

## Expected behavior

Files should be persisted across sessions

## How to reproduce it (as minimally and precisely as possible)

Launch the attached project and click the button.  On first click, a file is created.  Subsequent clicks read the file.  Reload the page and click the button, observing that it has created a new file.

[TestLocalStorageWASM.zip](https://github.com/unoplatform/uno/files/4782504/TestLocalStorageWASM.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
3.0.0-dev.484
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

Files and folders from `Environment.GetFolderPath(Environment.SpecialFolder.Personal)` folder are not persisted.

You'll need to write in `Windows.Storage.ApplicationData.LocalFolder` or `Windows.Storage.ApplicationData.RoamingFolder`.

**Comment by DierkDroth** [comment]
@jeromelaban thanks for the work around. We'll give it a try.

**Comment by peternary** [comment]
Even with workaround there are still some issues with file persistence, as @jeromelaban suggested it may be related to files being persisted to IndexedDB periodically rather than immediately.

**Comment by jeromelaban** [comment]
@peternary did the fix for IndexDB address this issue as well ?

**Comment by peternary** [comment]
@jeromelaban Yes, files appear to be persisting properly at the moment.
