### ISSUE TITLE
[WASM] VS debugger sometimes unable to step forward

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3381]
## Current behavior

In some circumstances the VS debugger can hit a breakpoint but be unable to step forward.

Call stack from issue:

WriteLine [c:\Users\PNary\Documents\ninjatrader-8\NinjaTrader.Core.Shared\Core\Trace.cs] Line 446	JavaScript
WriteLine [System.dll//__w/1/s/mono/mcs/class/referencesource/System/compmod/system/diagnostics/TraceInternal.cs] Line 487	JavaScript
WriteLine [System.dll//__w/1/s/mono/mcs/class/referencesource/System/compmod/system/diagnostics/Trace.cs] Line 249	JavaScript

## Expected behavior

Debugger should work as expected.

## Environment

Nuget Package:
Uno.UI
Package Version(s):
3.0.0-dev.482
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by francoistanguay** [comment]
Not an Uno issue.
