### ISSUE TITLE
CornerRadius bug

### ISSUE THREAD

**Issue by seanocali** [unoplatform/uno#3386]
## Current behavior
Any XAML file that has CornerRadius="x x x x" and doesn't use commas, the g.cs file generated doesn't add them to the C# code, causing compile errors.
![Annotation 2020-06-16 142839](https://user-images.githubusercontent.com/16900871/84830089-b7880780-afdd-11ea-9a4b-41ff3594c064.jpg)

This does not manifest when building UWP. It happens with Droid and WASM. I am unable to test with iOS or macOS at this time.
## How to reproduce it (as minimally and precisely as possible)
In a XAML view, create a Grid with the property:
`<Grid CornerRadius="0 40 40 0" />` No commas separating.
Then build Droid or WASM.

## Environment

Nuget Package:
lastest preview since 6/15/2020
Package Version(s):
lastest preview since 6/15/2020

Affected platform(s):

- [ ] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.6.2)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
Had no idea this was possible :-D ! It actually works with `Thickness` too

**Comment by jeromelaban** [comment]
The implementation of this parsing is done here:

https://github.com/unoplatform/uno/blob/d9323226b6060eee1b7763b88b2a082da971510f/src/Uno.UI/UI/Xaml/ThicknessConverter.cs#L30

And here:

https://github.com/unoplatform/uno/blob/57f998d64455a9083aca06e565df6eeb9b9a1660/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L3822

This issue is curious as there's an explicit support for spaces, so it must be a somehow different path.

**Comment by MartinZikmund** [comment]
@jeromelaban I fixed it for `CornerRadius` in `XamlFileGenerator` as that is not `Thickness` and it previously just put the same string in the constructor. I haven't updated it in the converter class however. `ThicknessConverter` does not have support for spaces yet, should it be added there too?

**Comment by seanocali** [comment]
@MartinZikmund I actually tried to fix it yesterday using Gitpod, I just made a BuildCorderRadius method similar to the BuildThickness one. But I couldn't figure out how to send a PR. I'll try and read up on how to contribute here in the future.

**Comment by MartinZikmund** [comment]
@seanocali sorry, didn't know you wanted to fix it yourself 😊. It surprised me spaces are supported in UWP so I implemented it as part of the investigation.

For contributions, I recommend forking the repo, creating a branch and you can then make pull request from your fork. I wrote three articles on contributing to Uno [on my blog](https://blog.mzikmund.com/2019/03/contributing-to-the-uno-platform-part-1/), maybe some of it could be useful 👍

**Comment by jeromelaban** [comment]
@MartinZikmund indeed, the converter does not have support for spaces, and that may be useful when bindings or template bindings are involved.

**Comment by MartinZikmund** [comment]
> @MartinZikmund indeed, the converter does not have support for spaces, and that may be useful when bindings or template bindings are involved.

I will add spaces support for Thickness and CornerRadius in the converter too
