### ISSUE TITLE
Switching theme at runtime does not apply to visual states

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3388]
## Current behavior

When theme is switched at runtime, it does not apply to visual states of controls - for example button pressed.

## Expected behavior

New theme should apply everywhere.

When theme

## How to reproduce it (as minimally and precisely as possible)

Consider the following page content:

    <Grid x:Name="Grid" Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
       <Button x:Name="Button">Click</Button>
    </Grid>

And make sure `App.xaml` has no `RequestedTheme` set:

```
Application
	x:Class="SamplesApp.App"
	xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
```

Run the app on Android in light theme, then switch to dark theme via the action center. Notice the page changes background and button changes its colors. However, when the button is pressed it "disappears" because it still uses the "light" theme of pressed visual state.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
This is probably for @davidjohnoliver 😇

**Comment by MartinZikmund** [comment]
Seems that it is not only with visual states - with the Messages sample app (https://github.com/MartinZikmund/messages-multiplatform-uno-sample) I have noticed that changing theme at runtime does not apply new text color to the "Messages" header on the right pane - I think I saw it on Android specifically

**Comment by jeromelaban** [comment]
if you have a stack trace to share, that may help for similar issues.

**Comment by MartinZikmund** [comment]
I rushed as it was like 2 AM so I did not capture it, but will retry and find it 👍

**Comment by davidjohnoliver** [comment]
> Seems that it is not only with visual states - with the Messages sample app (https://github.com/MartinZikmund/messages-multiplatform-uno-sample) I have noticed that changing theme at runtime does not apply new text color to the "Messages" header on the right pane - I think I saw it on Android specifically. 

Thanks for the poke Martin! Any idea why that text header might be failing to update? I know I missed the visual-state case, but it seems like there's another case I missed as well.

**Comment by MartinZikmund** [comment]
@davidjohnoliver Really hard to say, I just noticed that while most texts changed, this one didn't unless I restarted the app. I will check again later to confirm if I just didn't miss something.
