### ISSUE TITLE
[iOS][UWP] ElevatedView is not displayed

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#3401]
## Current behavior

ElevatedView is not displayed

## Expected behavior
ElevatedView should be displayed

## How to reproduce it (as minimally and precisely as possible)

Sample: 
[ElevatedViewDisplay.zip](https://github.com/unoplatform/uno/files/4800292/ElevatedViewDisplay.zip)

## Environment

Nuget Package: Uno.UI

Package Version(s): 3.0.0-dev.593

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

No internal issue, found this bug while looking at 
https://dev.azure.com/nventive/Umbrella/_workitems/edit/186386

**Comment by Xiaoy312** [comment]
For ios, the attached sample is working. The shadow may be a bit faded to see:
![image](https://user-images.githubusercontent.com/2359550/86659423-d6affe80-bfb7-11ea-942e-fcd26af223c3.png)

If you add `ShadowColor="Black"`, it is much easier to see:
![image](https://user-images.githubusercontent.com/2359550/86659101-92bcf980-bfb7-11ea-899d-ff20e77cf2fd.png)

But, uwp isnt working...
