### ISSUE TITLE
[Android] ElevatedView elavation cropping issue

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#3404]
## Current behavior

The elevated view corners are cropped with a 90 degree angle

## Expected behavior

The elevated view corners are rounded

## How to reproduce it (as minimally and precisely as possible)

Sample: 
[ElevatedViewDisplay.zip](https://github.com/unoplatform/uno/files/4800356/ElevatedViewDisplay.zip)

## Environment

Nuget Package: Uno.UI

Package Version(s): 3.0.0-dev.593

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Internal issue : https://dev.azure.com/nventive/Umbrella/_workitems/edit/186386

**Comment by carldebilly** [comment]
This is caused by the `<ScrollViewer>` around the ElevatedView, which is always clipping on Uno. The workaround is to let breath space for the shadow in the layout.

**Comment by carldebilly** [comment]
@carlh98 Could we close this issue?

**Comment by MatFillion** [comment]
@carldebilly but behavior is different on android, can we fix that?

**Comment by carlh98** [comment]
Fixed in Android with Uno.UI 3.6.0-dev.174
