### ISSUE TITLE
Uno.SourceGeneration 2.0 is not compatible with REFIT 5.X

### ISSUE THREAD

**Issue by vincentcastagna** [unoplatform/uno#3408]
## Current behavior

Uno.SourceGeneration is not compatible with Refit 5.X

See this SO post for more info : https://stackoverflow.com/questions/61599385/refit-5-0-with-uno-platform-fails-with-missingmethodexception

## Expected behavior

Compatibility with Refit 5.X

## How to reproduce it (as minimally and precisely as possible)

- Uno Project with Refit 5.X reference

Nuget Package:

Uno 2.4>
Refit 5.X

Affected platform(s):

- [x] ALL
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Here's the issue in Refit: https://github.com/reactiveui/refit/issues/942

**Comment by jeromelaban** [comment]
Once https://github.com/reactiveui/refit/pull/943 is published to nuget.org, the manual resolution for this issue is to add the lines below in all projects that reference `Uno.UI` or `Uno.SourcegenerationTasks` directly or indirectly, below the first existing `PropertyGroup` block:

```xml
<PropertyGroup>
   <!-- Workaround for https://github.com/unoplatform/uno/issues/3408 for Refit 5 to work alongside Uno SourceGeneration -->
   <RefitDisableGenerateRefitStubs Condition="'$(BuildingInsideUnoSourceGenerator)'!=''">true</RefitDisableGenerateRefitStubs>
</PropertyGroup>
```

**Comment by francoistanguay** [comment]
Can this be closed?

**Comment by jeromelaban** [comment]
No, there's still an update to make in uno.sourcegeneration for this to work.
