### ISSUE TITLE
Numeric element IDs in WASM are not compatible with CSS

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3409]
## What would you like to be added:

Uno currently generates numeric IDs for elements, which however cannot be referenced by CSS rules normally:

For example this does not work:

    #423506::selection { ... } 

While this does:

    [id='423506']::selection { ... }

## Why is this needed:

To be able to style pseudo-selectors for elements.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by carldebilly** [comment]
Hi @MartinZikmund,

  I agree they are not CSS compliant.  But the real question is: why would you want to target those IDs? They are memory offset for their conterparts in managed code (GC Handles). You should not hard-code CSS files on those IDs.

**Comment by MartinZikmund** [comment]
The issue I am facing is I need to style `::selection` of a specific TextBox, which cannot be done with in line style. Is there a way to do this without directly using the ID?

**Comment by carldebilly** [comment]
You can dynamically add a CSS class to the control and target it using this class.

**Comment by francoistanguay** [comment]
Should this be closed or still valid?

**Comment by MartinZikmund** [comment]
I would still suggest making the IDs start with a letter - could be something like `uno-423506` for example to ensure the result is a valid markup

**Comment by Youssef1313** [comment]
This should be closed per https://github.com/unoplatform/uno/pull/6828#issuecomment-905432230.
