### ISSUE TITLE
[WASM] Must implement control class in both C# and XAML for use of StaticResources

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3412]
## Current behavior

If you have a custom control that does not implement the underlying class in the c# declaration (instead of just in XAML) then bindings for properties of the underlying control can fail at runtime.

## Expected behavior

Project should build successfully even if control type is only declared in XAML, as in UWP.

## How to reproduce it (as minimally and precisely as possible)

Attempt to build the attached project in WASM and notice that it fails.  If you examine the build output, you will see that there is an error converting 'object' to 'Thickness'.  In MyUserControl1.xaml.cs append ': UserControl' to the class declaration and attempt building in WASM again - it will build successfully.  Alternately, removing the BorderThickness property in MainPage.xaml will fix building as well.

Note that UWP will build successfully build in all above mentioned cases.

[ResourceBinding.zip](https://github.com/unoplatform/uno/files/4805914/ResourceBinding.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
3.0.0-dev.618
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

The default templates created by visual studio generally include the class in the code behind, which is why this does not happen more. The workaround is to always add the base type in the code behind.

**Comment by DierkDroth** [comment]
Thanks @jeromelaban, my guys confirmed the work around is viable for us. You could close this issue.

**Comment by jeromelaban** [comment]
Thanks @DierkDroth. We'll keep this issue opened as this eventually needs to be fixed.

**Comment by sigmarsson** [comment]
Is there currently a way to register a `UserControl` as View in the Prism view-model locator ?

e.g. the SettingsDialog cannot be found here :

![image](https://user-images.githubusercontent.com/43340959/120646688-10181500-c47a-11eb-9d41-58d8f80527ab.png)

and is being declared as 

![image](https://user-images.githubusercontent.com/43340959/120646816-30e06a80-c47a-11eb-86b1-bd9a9fea446d.png)

**Comment by mterwoord** [comment]
@jeromelaban Could you give a hint as to where to (start) look(ing) to implement at least the warning?

**Comment by jeromelaban** [comment]
@mterwoord I've updated my comment with additional details
