### ISSUE TITLE
[WASM] ScrollBar does not minimize/expand with mouseover

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3422]
## Current behavior

In UWP the scrollbar, by default, starts minimal and then expands on MouseOver.  In WASM, the scrollbar is always expanded.

## Expected behavior

Scrollbar should hide/expand as in UWP

## How to reproduce it (as minimally and precisely as possible)

Sample of the issue [here](http://playground.platform.uno/#e6898656).

## Environment

Nuget Package:
Uno.UI
Package Version(s):
3.0.0-dev.620
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks! What's the use case ? Is it a problem because you'd want the scrollbars to disappear ?

## Note to contributors
The current support of scrollbars only uses the browser's native variant. The ScrollViewer control does not provide this implementation yet and should be modified to use the recent addition of `ScrollBar`.

**Comment by DierkDroth** [comment]
We wanted to have the exact same UI experience on UWP as on WASM. Believe that's one of the Unique Selling Points of UNO, no?

**Comment by jeromelaban** [comment]
@DierkDroth I'm not saying this should not happen. I'm looking for a scenario to understand the needs and guide properly while this feature gets implemented.

**Comment by DierkDroth** [comment]
The scenario would be having the same UX on UWP and WASM (and other supported platforms).

**Comment by peternary** [comment]
Scrollbar expands on mouseover in latest
