### ISSUE TITLE
[wasmxfhead] Unable to build the generated wasm project

### ISSUE THREAD

**Issue by codeinstinct** [unoplatform/uno#3430]
## Current behavior

Unable to build wasm project generated from ```dotnet new wasmxfhead```

## Expected behavior

Able to build & launch wasm project generated from ```dotnet new wasmxfhead```

## How to reproduce it (as minimally and precisely as possible)

Repro Project is [here](https://github.com/codeinstinct/MyUnoFromXF)

Steps:
1) Create standard XF project, with solution in same folder.
2) Ignore ios, android projects and only select "UWP".
3) Run dommand ```dotnet new wasmxfhead```
4) Project gets generated but isn't automatically added to solution. Add it via visual studio.
5) Build all projects
6) Error as seen below:
![uno-wasmxfhead-2](https://user-images.githubusercontent.com/1712514/85425452-d31f7f00-b596-11ea-85a3-7f5268ad2dba.png)

## Environment

Nuget Package: 

Package Version(s):

![uno-wasmxfhead-3](https://user-images.githubusercontent.com/1712514/85425708-2396dc80-b597-11ea-9ebf-0352aababead.png)

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

I'm unable to understand where to start looking to handle this error. Upon running the ```dotnet new wasmxfhead``` command, i see the following error.

```
\repro\unoxf\MyUnoFromXF>dotnet new wasmxfhead
The template "Uno Platform WebAssembly Head for Xamarin.Forms" was created successfully.

Processing post-creation actions...
Adding project reference(s) to solution file. Running dotnet sln \repro\unoxf\MyUnoFromXF\MyUnoFromXF.sln add UnoQuickStart.Wasm
Failed to add project(s) UnoQuickStart.Wasm to solution file \repro\unoxf\MyUnoFromXF\MyUnoFromXF.sln
Output from command:
Usage: dotnet sln <SLN_FILE> add [options] <PROJECT_PATH>

Arguments:
  <SLN_FILE>       The solution file to operate on. If not specified, the command will search the current directory for one.
  <PROJECT_PATH>   The paths to the projects to add to the solution.

Options:
  --in-root               Place project in root of the solution, rather than creating a solution folder.
  -s, --solution-folder   The destination solution folder path to add the projects to.
  -h, --help              Show command line help.



Could not find project or directory `UnoQuickStart.Wasm`.
```

**Comment by codeinstinct** [comment]
Update:

I've resolved the issue & gotten the wasm project working in the browser.

You can see the changes made in the [other branch](https://github.com/codeinstinct/MyUnoFromXF) .

Summary of changes:
- Downgraded Xamarin.Forms to 4.3.x
- Added nuget Packages in wasm project by comparing with RPN calculator sample by Uno Team.
- Installed 2 developer packs while wrestling with other sample projects: 4.6.2 & 4.7 .

I'm listing them here but I'm not sure which combination of changes have fixed the problem.

Hoping the tooling matures soon to guide us with precise errors.

**Comment by jeromelaban** [comment]
Thanks for the report ! 

Could you indicate which version of the templates are installed ? (or which command you used to install the templates)

**Comment by codeinstinct** [comment]
Yeah, sure,
The **master** branch was created with ```dotnet new -i Uno.ProjectTemplates.Dotnet::*```
The **feature-experimentWith2.1Templayes** branch was created with ```dotnet new -i Uno.ProjectTemplates.Dotnet::2.1``` .

**Comment by jeromelaban** [comment]
For this issue, the template is not functioning properly, and here are the workarounds, as of Uno.UI 2.4.4:
- For the project not being added, add the project manually in the solution (this is fixed in master)
- For the subsequent build error, you'll need to downgrade the whole solution's `Xamarin.Forms` package to version **4.5.0.356**, and the `Uno.Xamarin.Forms.Platform` package has to be **4.5.0-uno.569** (this will avoid linker errors).
