### ISSUE TITLE
Toggleswitch.Header doesn't work

### ISSUE THREAD

**Issue by seanocali** [unoplatform/uno#3437]
## Current behavior
Assigning a value to a Toggleswitch Header has no effect in anything other than UWP.

## How to reproduce it (as minimally and precisely as possible)
`<ToggleSwitch Header="Hello World" />`

## Environment

Nuget Package: Uno.UI

Package Version(s): 3.0.0-dev.636

Affected platform(s):

- [ ] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.6.2)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by pkar70** [comment]
See PR#2563 .

**Comment by pkar70** [comment]
Why close? Problem is real, and it seems that my PR would not be merged :)

**Comment by seanocali** [comment]
Ok, so this is my understanding from that conversation (please correct me if I'm wrong).  You changed the ContentPresenter.Visibility to Visible but Jerome  said that can't work because it needs to be Collapsed at startup because otherwise it will be removed from the visual tree if someone uses x:Load, and that the UWP control itself must set it somewhere else.

The Slider uncollapses it in the OnHeaderChanged event:
[https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Controls/Slider/Slider.cs](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Controls/Slider/Slider.cs)

Can't the ToggleSwitch be made to do the same?

**Comment by davidjohnoliver** [comment]
@seanocali Exactly :)

**Comment by pkar70** [comment]
I think this is resolved by #3494
