### ISSUE TITLE
[UWP] Content of ElevatedView not showing up

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/uno#3440]
## Current behavior

On UWP the content of the ElevatedView is not visible. (Bottom of the page)
![image](https://user-images.githubusercontent.com/64613932/85752901-ca839180-b6d9-11ea-951f-ef5261c6e26f.png)

## Expected behavior

Content of the ElevatedView should be visible. (Bottom of the page)
![image](https://user-images.githubusercontent.com/64613932/85752962-d8391700-b6d9-11ea-8538-aea9d0e66c19.png)

## How to reproduce it (as minimally and precisely as possible)

Use ElevatedView with content in a UWP project.

## Environment

Nuget Package:

Package Version(s): Uno.UI 2.4.4

Affected platform(s):UWP

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This will be fixed once an update to 2.4.4 is published (soon)
