### ISSUE TITLE
[iOS] Missing shadow when using ElevatedView

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/uno#3441]
## Current behavior

ElevatedView is missing it's shadow. (Bottom)
![image](https://user-images.githubusercontent.com/64613932/85766570-2acc0080-b6e5-11ea-906b-7f074822d5ef.png)

## Expected behavior

ElevatedView as a shadow around it's content.
![image](https://user-images.githubusercontent.com/64613932/85766878-7383b980-b6e5-11ea-85c6-ae29104a1278.png)

## How to reproduce it (as minimally and precisely as possible)
Use an ElevatedView in a iOS project.

## Environment

Nuget Package: Uno.UI 2.4.4

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
@MaximeDion-Work Could you point me to repro XAML? Many improvements in PR https://github.com/unoplatform/uno/pull/3557, but unsure it could fix this problem.

**Comment by MaximeDion-Work** [comment]
Yup it's good thanks.
