### ISSUE TITLE
[Android/iOS] The button height does is not adapting to its child's height

### ISSUE THREAD

**Issue by Guidemarcus** [unoplatform/uno#3442]
[HeightIssue.zip](https://github.com/unoplatform/uno/files/4833107/HeightIssue.zip)

## Current behavior

On UWP, the height of a button will adapt to its child even if the button has a specified height. On a mobile device, the content of a button will be cut off if the content is bigger than the defined button height.

## Expected behavior

Same as UWP.

## How to reproduce it (as minimally and precisely as possible)

Look at linked uno project

## Environment

Nuget Package: default uno project

Package Version(s): 2.4

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
-

**Comment by jeromelaban** [comment]
@carldebilly would this looks like a `MaxHeight`/`MaxWidth` issue template issue ?

**Comment by carldebilly** [comment]
This issue is not present anymore in Uno.UI 3.7.x
