### ISSUE TITLE
[WASM] NavigatedTo/Loaded/Loading do not fire in correct order

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3448]
## Current behavior

In Wasm, a Page's Loaded and Loading events fire before OnNavigatedTo override.

## Expected behavior

OnNavigatedTo should fire first, as in Uwp

## How to reproduce it (as minimally and precisely as possible)

Start the attached project in Wasm and observe in the console log that Loading fired first, followed by Loaded and then OnNavigatedTo.  If you set breakpoints in Uwp, you can observe that OnNavigatedTo fires first.  This Uwp behavior is also documented [here](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.page.onnavigatedto?view=winrt-19041#remarks)

[NavigationView.zip](https://github.com/unoplatform/uno/files/4838875/NavigationView.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
3.0.0-dev.636
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
This problem is already tracked in #2895 and #1478, please upvote/comment there to help prioritize them 👍 .
