### ISSUE TITLE
Android template project targets old SDK

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3457]
## What would you like to be added:

 The template project for Android targets SDK 26, I can be raised to 29.

## Why is this needed:

More up to date.

## For which Platform:

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by pkar70** [comment]
It is not so simple as to change in template.
Some methods (calls to Android) would be 'obsolete', or even 'removed'.

**Comment by MartinZikmund** [comment]
It should be fine as Uno already targets Android 10 - https://github.com/unoplatform/uno/blob/6dffb1a3b8a99ceaf28368943822f87f30393c30/src/Uno.UI/Uno.UI.csproj#L3
