### ISSUE TITLE
Back Button Missing on iOS, macOS and Chrome

### ISSUE THREAD

**Issue by MelbourneDeveloper** [unoplatform/uno#3459]
This issue is a stub that points to an issue on a private repo:
https://github.com/MelbourneDeveloper/UnoUdemyCourse/issues/5

Sorry that I couldn't move this issue directly into this repo. Github doesn't have that functionality. Next time I will create the issue here.

@francoistanguay @carldebilly @jeromelaban

**Comment by jeromelaban** [comment]
Thanks for the report. On iOS, the back button is part of the native templates. On macOS and WebAssembly, the back button does not exist out of the box in WinUI and must be implemented manually.

**Comment by MelbourneDeveloper** [comment]
How do we implement the back button with the native template on iOS?

Are you saying there is no back button on macOS?

**Comment by francoistanguay** [comment]
Christisn, is this considered closed?

**Comment by MelbourneDeveloper** [comment]
@francoistanguay the back button can be implemented on iOS, Android, and Firefox. However, as far as I know, it doesn't exist on Chrome, or macOS. Is there a plan to implement it?

**Comment by francoistanguay** [comment]
Both our Gallery and Ch9 apps and wasm apps are working afaik. Guidance should be sufficient there. If somehow it doens't work for you, let me know and we can reopen an issue in Uno.Material or Ch9.

**Comment by MelbourneDeveloper** [comment]
@francoistanguay , I haven't seen those samples. Where I can grab those?

**Comment by francoistanguay** [comment]
Both mentioned during our talk at UnoConf, and both on our website :)
https://platform.uno/ch9
https://github.com/unoplatform/Uno.Gallery
https://gallery.platform.uno/

**Comment by MelbourneDeveloper** [comment]
@francoistanguay if these have back buttons, then problem solved. I'll check it out and get back to you.
