### ISSUE TITLE
[iOS] Multi-lines TextBox still scrolling up when typing with a hardware keyboard

### ISSUE THREAD

**Issue by MelbourneDeveloper** [unoplatform/uno#3460]
When typing on an iPhone using a hardware keyboard:
![ezgif-1-046feaf8efdb](https://user-images.githubusercontent.com/8635919/86480788-b1ec2a80-bd1c-11ea-9c6f-1fcd5ea063c0.gif)

Original issue: https://github.com/MelbourneDeveloper/UnoUdemyCourse/issues/6

* This bug not present on an iPad
* Reproduced in the simulator by checking the option "connect hardware keyboard"
* Present on all tested version of iOS and all published version of Uno
* Caused by: https://github.com/unoplatform/uno/blob/9951318da823751c67d34a439d07165d5fe1d0a8/src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxView.iOS.cs#L74L77 
*  this code has been added to Uno by this commit: <https://dev.azure.com/nventive/Umbrella/_git/Uno.UI/commit/021b978aa5b2b8ce03f56f9d9b8dd3935f5f066b>(2016-06-08)

Update, here's the original change (in Window.iOS.cs):
<img width="1612" alt="image" src="https://user-images.githubusercontent.com/5839577/212716871-3e5a824c-ed2d-4a43-a919-e4a4fc3eadda.png">

In MultilineTextBoxView.iOS.cs:
<img width="1622" alt="image" src="https://user-images.githubusercontent.com/5839577/212716952-ed36902d-8a9e-412f-b0b4-fc947d359cb3.png">

**Comment by jeromelaban** [comment]
Thanks for opening the issue. It would be more interesting to have the full content of the issue so it's visible to all contributors.

**Comment by carldebilly** [comment]
I reproduced the bug easily...  just create a new Uno App, and run the following XAML on any iPhone emulator:

``` xml
<TextBox TextWrapping="Wrap" AcceptsReturn="True" />
```

Works well on a iPad, but on iPhone on each keystroke will move up the text and you'll need to rescroll it down to see it.

* It has not been tested on a real device yet. It could be present only on emulators.
* Reproduced on all tested iOS version (oldest on my workstation is iOS 11.2)
* Reproduced on very old Uno.UI version... even on v`1.45`

**Comment by carldebilly** [comment]
The problem has been related to the usage of the "hardware keyboard" in the simulator. Still need to check if it's happening on an actual device with a hardware keyboard.

**Comment by dr1rrb** [comment]
I'm able to pro with bluetooth keyboard on an iPhone X
![ezgif-1-046feaf8efdb](https://user-images.githubusercontent.com/8635919/86480788-b1ec2a80-bd1c-11ea-9c6f-1fcd5ea063c0.gif)

**Comment by MartinZikmund** [comment]
@ajpinedam any ideas how to address this one 🤔 ?

**Comment by carldebilly** [comment]
@MartinZikmund It's related to very old legacy code from the very first versions of Uno... The fix will be easy to do, it's just involving a lot of testing.

**Comment by spouliot** [comment]
I don't recall something identical (to the keyboard) but the links to the code hints at a "state" fight between code pieces (one iOS and the other likely Uno) for the cursor position, where each one is being displayed. 

It's possible that, under the "normal" case, a not-quite-valid value is received (e.g. from iOS) before an updated-and-correct value **and** only the last is displayed.
