### ISSUE TITLE
Date Time Discrepancy

### ISSUE THREAD

**Issue by MelbourneDeveloper** [unoplatform/uno#3461]
This issue is a stub that points to an issue on a private repo:
MelbourneDeveloper/UnoUdemyCourse#7

Sorry that I couldn't move this issue directly into this repo. Github doesn't have that functionality. Next time I will create the issue here.

@francoistanguay @carldebilly @jeromelaban

**Comment by jeromelaban** [comment]
Thanks for opening this issue. If would be preferable to have the full content of the issue in this repo.

Time zones may not be implemented properly in mono, causing this issue.

**Comment by jeromelaban** [comment]
This issue is mono related: https://github.com/mono/mono/issues/15260
