### ISSUE TITLE
Following instructions for Xamarin forms and get same error each time

### ISSUE THREAD

**Issue by westacotta** [unoplatform/uno#3465]
## On which page?
https://github.com/unoplatform/Uno.Xamarin.Forms.Platform

## What's wrong?
Following the exact instructions for creating a first app using xamarin forms and uno, i always get the following issue with "failed to execute the linker"

I have made no code changes at all.

1>------ Build started: Project: App4.Wasm, Configuration: Debug Any CPU ------
1>C:\Users\andy\source\repos\App4\App4.UWP\App.xaml.cs(45,17,45,58): warning Uno0001: Windows.UI.Xaml.DebugSettings.EnableFrameRateCounter is not implemented in Uno
1>C:\Users\andy\source\repos\App4\App4.UWP\App.xaml.cs(62,21,62,45): warning Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PreviousExecutionState is not implemented in Uno
1>C:\Users\andy\source\repos\App4\App4.UWP\App.xaml.cs(101,28,101,61): warning Uno0001: Windows.ApplicationModel.SuspendingOperation.GetDeferral() is not implemented in Uno
1>C:\Users\andy\source\repos\App4\App4.UWP\App.xaml.cs(103,13,103,30): warning Uno0001: Windows.ApplicationModel.SuspendingDeferral.Complete() is not implemented in Uno
1>App4.Wasm -> C:\Users\andy\source\repos\App4\App4.Wasm\bin\Debug\netstandard2.0\App4.Wasm.dll
1>Determining projects to restore...
1>All projects are up-to-date for restore.
1>packager2 -> C:\Users\andy\AppData\Local\Temp\mono-wasm-f5cfc67c8ed\packager2.exe
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.0.10\build\Uno.Wasm.Bootstrap.targets(125,5): error : System.Exception: Failed to execute the linker
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.0.10\build\Uno.Wasm.Bootstrap.targets(125,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v1be21f07f93cd3a369c95001065dbda54db9dca8.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 529
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.0.10\build\Uno.Wasm.Bootstrap.targets(125,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v1be21f07f93cd3a369c95001065dbda54db9dca8.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 149

**Comment by jeromelaban** [comment]
Thanks for the report!

You can see more information when setting the logging level of visual studio to `Normal`, here:

![image](https://user-images.githubusercontent.com/5839577/86023148-4abb3700-b9f9-11ea-83cc-71207463f6de.png)

**Comment by westacotta** [comment]
Thanks for this.  got round that issue now, i noticed there was a prompt to update one of the wasm packages.

Seems to build and now get the following in the browser:

System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.

**Comment by jeromelaban** [comment]
This last error generally happens when the build did not finish properly. Make sure to use to "rebuild" the WebAssembly project.

**Comment by westacotta** [comment]
hmm unfortunately not.  seems to occur after full rebuilds as well

**Comment by jeromelaban** [comment]
Does index.html file exist in the `debug\netstandard2.0\dist` folder ? If it does, it could be that IIS Express does not provide the file properly, restarting it could help (in the windows tray icons).

**Comment by westacotta** [comment]
nope.  doesn't look like the build is generating an index.html file at all

**Comment by jeromelaban** [comment]
Can you try deleting the bin and obj folders, then rebuild ?

**Comment by westacotta** [comment]
ok so after a full clean out and rebuild.
I'm not getting a dist directory created at all.

Build says it "succeeded"

**Comment by jeromelaban** [comment]
Thank you. In a `Developer Command Prompt`, navigate to the `App4.Wasm`, then run the following command: `msbuild /r /bl`. This will generate a file named `msbuild.binlog`. Could you post this file ?

**Comment by westacotta** [comment]
Here you go

[msbuild.zip](https://github.com/unoplatform/uno/files/4846853/msbuild.zip)

**Comment by jeromelaban** [comment]
For some reason, it looks like the Uno.Wasm.Bootstrap package was not restored properly or not installed.

Can you validate that you have the "Uno.Wasm.Bootstrap` 1.2.0 and  `Uno.Wasm.Bootstrap.DevServer` 1.2.0 installed, and that the line `DotNetCliToolReference` in the `Wasm.csproj` file is removed ?

Also, if you installed the uno templates with `dotnet new -i Uno.ProjectTemplates.Dotnet::2.0`, try updating to the latest templates using `dotnet new -i Uno.ProjectTemplates.Dotnet` (without the version).

**Comment by westacotta** [comment]
ok yes the Uno.Wasm.Bootstrap was missing the DotNetCliToolReference was still in the csproj.

Removed those and updated the template.

Now get a linker error
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error : 
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error : Unhandled **Exception: Mono.Linker.MarkException: Error processing method: 'System.Void Xamarin.Forms.Platform.UWP.CarouselViewRenderer::UpdatePosition(System.Int32)' in assembly: 'Xamarin.Forms.Platform.Uno.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.CarouselView::SetCurrentItem(System.Object)**

Full stack:

1>  Activator call 'System.Object System.Activator::CreateInstance(System.Type)' inside 'System.Object Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder::<ProcessMemberElements>g__BuildInstance|16_0(Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder/<>c__DisplayClass16_0&)' was detected with 1st argument expression which cannot be analyzed
1>  Reflection call 'System.Type System.Type::GetType(System.String)' inside 'System.Type Windows.UI.Xaml.Markup.Reader.XamlTypeResolver/<>c__DisplayClass29_0::<SourceFindType>b__0()' was detected with argument which cannot be analyzed
1>  Reflection call 'System.Type System.Type::GetType(System.String)' inside 'System.Type Windows.UI.Xaml.Markup.Reader.XamlTypeResolver/<>c__DisplayClass29_0::<SourceFindType>b__1()' was detected with argument which cannot be analyzed
1>  Reflection call 'System.Type System.Type::GetType(System.String)' inside 'System.Type Windows.UI.Xaml.Markup.Reader.XamlTypeResolver/<>c__DisplayClass29_0::<SourceFindType>b__2()' was detected with type name `` which can't be resolved.
1>  Activator call 'T System.Activator::CreateInstance()' inside 'T Windows.UI.Xaml.Controls.DeferralManager`1::GetDeferral()' is not supported
1>  Activator call 'System.Object System.Activator::CreateInstance(System.Type)' inside 'Windows.UI.Xaml.Controls.Page Windows.UI.Xaml.Controls.Frame::CreatePageInstance(System.Type)' was detected with 1st argument expression which cannot be analyzed
1>  Reflection call 'System.Type System.Type::GetType(System.String)' inside 'Windows.UI.Xaml.DependencyProperty Uno.UI.ToolkitHelper::GetProperty(System.String,System.String)' was detected with argument which cannot be analyzed
1>  Reflection call 'System.Reflection.EventInfo System.Type::GetEvent(System.String)' inside 'System.Boolean Uno.UI.DataBinding.BindingPropertyHelper::InternalIsEvent(System.Type,System.String)' was detected with argument which cannot be analyzed
1>  Reflection call 'System.Reflection.PropertyInfo System.Type::GetProperty(System.String,System.Reflection.BindingFlags)' inside 'System.Reflection.PropertyInfo Uno.UI.DataBinding.BindingPropertyHelper::GetPropertyInfo(System.Type,System.String,System.Boolean)' was detected with argument which cannot be analyzed
1>  Reflection call 'System.Reflection.FieldInfo System.Type::GetField(System.String,System.Reflection.BindingFlags)' inside 'System.Reflection.FieldInfo Uno.UI.DataBinding.BindingPropertyHelper::GetFieldInfo(System.Type,System.String,System.Boolean)' was detected with argument which cannot be analyzed
1>  Reflection call 'System.Reflection.FieldInfo System.Type::GetField(System.String)' inside 'Windows.UI.Xaml.DependencyProperty Uno.UI.DataBinding.BindingPropertyHelper::FindAttachedProperty(System.Type,System.String)' was detected with argument which cannot be analyzed
1>  Reflection call 'System.Type System.Type::GetType(System.String,System.Boolean)' inside 'System.Boolean Uno.UI.DataBinding.BindingPropertyHelper::FastStringToTypeConvert(System.Type,System.String,System.Object&)' was detected with argument which cannot be analyzed
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error : Fatal error in Mono IL Linker
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error : Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Void Xamarin.Forms.Platform.UWP.CarouselViewRenderer::UpdatePosition(System.Int32)' in assembly: 'Xamarin.Forms.Platform.Uno.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.CarouselView::SetCurrentItem(System.Object)
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.ProcessQueue()
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    --- End of inner exception stack trace ---
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.ProcessQueue()
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.Process()
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Pipeline.Process(LinkContext context)
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Driver.Run(ILogger customLogger)
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Driver.Main(String[] args)
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error : System.Exception: Failed to execute the linker
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 664
1>  C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 168
1>Done building target "BuildDist" in project "App4.Wasm.csproj" -- FAILED.
1>
1>Done building project "App4.Wasm.csproj" -- FAILED.
1>
1>Build FAILED.
1>
1>C:\Users\andy\source\repos\App4\App4.UWP\App.xaml.cs(45,17,45,58): warning Uno0001: Windows.UI.Xaml.DebugSettings.EnableFrameRateCounter is not implemented in Uno
1>C:\Users\andy\source\repos\App4\App4.UWP\App.xaml.cs(62,21,62,45): warning Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PreviousExecutionState is not implemented in Uno
1>C:\Users\andy\source\repos\App4\App4.UWP\App.xaml.cs(101,28,101,61): warning Uno0001: Windows.ApplicationModel.SuspendingOperation.GetDeferral() is not implemented in Uno
1>C:\Users\andy\source\repos\App4\App4.UWP\App.xaml.cs(103,13,103,30): warning Uno0001: Windows.ApplicationModel.SuspendingDeferral.Complete() is not implemented in Uno
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error : Fatal error in Mono IL Linker
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error : 
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error : Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Void Xamarin.Forms.Platform.UWP.CarouselViewRenderer::UpdatePosition(System.Int32)' in assembly: 'Xamarin.Forms.Platform.Uno.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.CarouselView::SetCurrentItem(System.Object)
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.ProcessQueue()
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    --- End of inner exception stack trace ---
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.ProcessQueue()
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.Process()
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Pipeline.Process(LinkContext context)
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Driver.Run(ILogger customLogger)
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Driver.Main(String[] args)
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error : System.Exception: Failed to execute the linker
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 664
1>C:\Users\andy\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 168
1>    4 Warning(s)
1>    20 Error(s)
1>
1>Time Elapsed 00:00:31.07
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by jeromelaban** [comment]
Thanks, this is generally caused by a mismatch in Xamarin Forms versions. Which version are you referencing ? At this point, Uno is aligned with X.F 4.5

**Comment by westacotta** [comment]
4.5.  This is a freshly installed VS2019

**Comment by jeromelaban** [comment]
And what version of `Uno.Xamarin.Forms.Platform` are you referencing in your Wasm project ?

**Comment by westacotta** [comment]
4.3.4 Which seems to be the only version available in the NuGet selector

**Comment by jeromelaban** [comment]
Right, you'll need to check the pre-release box first to use a later version.

**Comment by westacotta** [comment]
so I did get it working last night but not with the 4.5 version of uno.  I need to go back and experiment as it was pretty rough and ready how i was trying to get it working so I need to work out exactly what I did.
The Uno instructions for Xamarin Forms as they stand don't work straight out of the box.  I've tried several wizard generated, clean projects and followed the instructions, all with the same results.  

Areas I noticed were items Uno.Wasm.Bootstrap not being added to the wasm project, DotNetCliToolReference being left behind in the csproj and having to play about with versions xamarin forms to get it to work.

Even after this , I have only got as far as the splash screen being shown and no actual xaml defined content.

I will try and work out the steps when I get time and report back.

is there a sample project for xamarin forms that can be used as a starter project?

**Comment by jeromelaban** [comment]
Indeed, the instructions are not up to date if you are having this many issues. Did you follow [this one](https://github.com/unoplatform/uno/blob/master/doc/articles/get-started-dotnet-new.md#uno-platform-webassembly-support-for-xamarin-forms) or [this one](https://github.com/unoplatform/Uno.Xamarin.Forms.Platform#getting-started) ?

You can browse [this project](https://github.com/unoplatform/RpnCalculator) with recent updates.

**Comment by westacotta** [comment]
So i gave the Rpn calculator a go last night and all builds and runs as expected.

Will try and work out the differences between that and following both sets of those instructions and get back to you

**Comment by Kwiyos** [comment]
@westacotta  hi, im having the same issues with you as well, since you fixed it would you mind sharing your current combination of versions for all the packages? thanks!

**Comment by francoistanguay** [comment]
Any update on this we can take action on?

**Comment by westacotta** [comment]
Unfortunately I haven’t been able to spend any time on this for a while.
