### ISSUE TITLE
[WASM] Unhandled exception does not trigger event

### ISSUE THREAD

**Issue by Daoting** [unoplatform/uno#3473]
## What would you like to be added:
Unhandled exception does not trigger `Application.UnhandledException` or `AppDomain.UnhandledException` event.
## Why is this needed:
Handle unhandled exceptions in the same way as other platforms
## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
Closing in favor of https://github.com/unoplatform/uno/issues/6569
