### ISSUE TITLE
Generate fully qualified array type in RemoteControl.g.cs

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3480]
## Current behavior

Based on this [StackOverflow question](https://stackoverflow.com/q/62676355/732221) - it seems the `RemoteControlGenerator` could fully specify the type name (`new string[]`) [here ](https://github.com/unoplatform/uno/blob/4088deaf722a39d9b4d468d99e898832b14bea8f/src/SourceGenerators/Uno.UI.SourceGenerators/RemoteControl/RemoteControlGenerator.cs#L74) to avoid this compilation error.

## Expected behavior

No compilation error in `RemoteControl.g.cs`

## How to reproduce it (as minimally and precisely as possible)

As described in SO question.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Fixed in recent builds.
