### ISSUE TITLE
Windows.Storage.Pickers.FileOpenPicker does not work in Wasm.

### ISSUE THREAD

**Issue by xsteel2003** [unoplatform/uno#35]
As I said, I now migrate some of UWP's functionality to the browser, thanks to Uno's support for WebAssembly.
I need to open a local file in my browser. In UWP, the following code works fine:

` 
Windows.Storage.Pickers.FileOpenPicker fileOpenPicker = new Windows.Storage.Pickers.FileOpenPicker();
            fileOpenPicker.FileTypeFilter.Add(".jpg");

            var jpgFile =await fileOpenPicker.PickSingleFileAsync();

            if (jpgFile!=null)
            {
                tb_filename.Text = jpgFile.Name;
            }
`
But the above code does not work in Wasm. Does this alternative code work? Thank you!

**Comment by Ali-YousefiTelori** [comment]
how we can run typescript in c# code and how use browser file chooser?

**Comment by MartinZikmund** [comment]
Closing in favor of https://github.com/unoplatform/uno/issues/4028
