### ISSUE TITLE
It doesn't locate my dictionary resources

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#3504]
## Current behavior

Currently, it doesn't recognize my dictionary resources on Android, iOS, and WASM. Therefore it's either not apply my custom style (WASM) or simply crash the app on start (iOS and Android)

**Actual result (WASM)**
![wasnerror](https://user-images.githubusercontent.com/17461593/86600698-69c44680-bf6e-11ea-9a3c-c0d7aad10505.jpg)

**Actual result (Android & iOS)**
![androiderror](https://user-images.githubusercontent.com/17461593/86600724-721c8180-bf6e-11ea-8248-2ebc5e4bc5e6.jpg)

## Expected behavior

It should be able to recognize my dictionary resource on all platform like UWP and at the same time apply my custom style

**Expected result (UWP)**
![uwpsuccess](https://user-images.githubusercontent.com/17461593/86600830-95473100-bf6e-11ea-9424-f705766d0cc3.jpg)

## How to reproduce it (as minimally and precisely as possible)

[sample](https://github.com/unoplatform/uno/files/4879335/resourcedictionnarysample.zip)
Open the sample
Deploy on any of those platforms (Android, iOS or WASM)

## Environment

Nuget Package: Uno.UI

Package Version(s): 3.0.0-dev692

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version:16.6.2 )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
The problem was that the `Link` property was set for the `ResourceDictionary` Xaml files in the Uno head `.csproj` files, but it was not set for `App.xaml`:
```xml
    <ApplicationDefinition Include="..\Uno.Gallery.UWP\App.xaml" Visible="False" />
    <Page Include="..\Uno.Gallery.UWP\Views\**\*.xaml" Visible="False">
      <Link>Views\%(RecursiveDir)%(FileName)%(Extension)</Link>
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
```

This meant that the relative paths of the `ResourceDictionary` files with respect to `App.xaml` were not the same on the Uno heads as on UWP, so the `Source` couldn't be resolved.

The fix is to set `Link` for `App.xaml` so the relative path in `ResourceDictionary.Source` can be resolved successfully:
```xml
    <ApplicationDefinition Include="..\Uno.Gallery.UWP\App.xaml" Link="App.xaml" Visible="False" />
```
