### ISSUE TITLE
CheckBoxes appear strange when IsChecked=null

### ISSUE THREAD

**Issue by jcantin-nventive** [unoplatform/uno#3513]
## Current behavior

CheckBoxes appear strange when IsChecked=null (indeterminate); it looks like there's a square inside the other square.

## Expected behavior

CheckBoxes appear normallywhen IsChecked=null (indeterminate)

## How to reproduce it (as minimally and precisely as possible)

Create a new Uno app, add a checkbox, set IsChecked={x:null} and launch on WASM or iOS.

## Environment

Nuget Package: 

Package Version(s): 3.0.0-dev.719

Affected platform(s):

- [x] iOS
- [ ] ~~Android~~ (could not test)
- [x] WebAssembly
- [ ] ~~WebAssembly renderers for Xamarin.Forms~~ (could not test)
- [ ] ~~macOS~~ (could not test)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [x] 2017 (version:15.9.11 )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MatFillion** [comment]
![image](https://user-images.githubusercontent.com/7029537/86941574-1854bc80-c112-11ea-8092-6565726b00c2.png)

**Comment by XiaotianNetlift** [comment]
Looks like invalid character for the font:
https://github.com/unoplatform/uno/blob/cde2aa3fd60ec274b53772d6093720511da817b8/src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml#L3657-L3659

The checked counterpart has platform specific attributes:
```xml
win:Glyph="&#xE001;"
xamarin:Glyph="&#xE10B;"
```

**Comment by MatFillion** [comment]
Should be ok now with the new uno fluent font
