### ISSUE TITLE
Binding TestBox.Text property using `OneWay` mode is ignored by binding engine

### ISSUE THREAD

**Issue by MelbourneDeveloper** [unoplatform/uno#3522]
![Untitled Project](https://user-images.githubusercontent.com/16697547/87213347-af668200-c367-11ea-8ee5-ce38e7249ee0.gif)

## Current behavior

Binding mode is defaulting to TwoWay on WASM while UWP is OneWay

## Expected behavior

Binding mode defaults to OneWay - and should honor it.

## How to reproduce it (as minimally and precisely as possible)

Run sample. UWP is one way, but WASM is TwoWay

https://www.dropbox.com/s/qxkd4qwuo8q8imd/DataBinding.zip?dl=0

## Environment

Windows

Nuget Package:

```xml
  <ItemGroup>
    <!-- Note that for WebAssembly version 1.1.1 of the console logger required -->
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Filter" Version="1.1.1" />
    <PackageReference Include="Uno.UI" Version="2.4.0" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="2.4.0" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="1.2.0" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="1.2.0" />
  </ItemGroup>
```

Affected platform(s):

- [X] iOS
- [X] Android
- [X] WebAssembly
- [X] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MelbourneDeveloper** [comment]
@jeromelaban

**Comment by carldebilly** [comment]
Just reproduced easily on the Playground on this address:
https://playground.platform.uno/#6549dbf7

**Comment by carldebilly** [comment]
This bug has been fixed. Thanks for reporting it!
Fix available in `Uno.UI` v`3.1.0-dev.50`.
