### ISSUE TITLE
macOS release builds seem to depend on QTKit

### ISSUE THREAD

**Issue by mattleibow** [unoplatform/uno#3524]
## Current behavior

When building a macOS app in release configuration, I get a warning about referencing QTKit.

```
  Target _CompileToNative:
    /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/bin/mmp @/Users/runner/work/1/s/output/samples/Basic/Uno/SkiaSharpSample.macOS/obj/Release/response-file.rsp -q
     -q
     -q
     -q
     
    MMP : warning MM5220: Skipping framework 'QTKit'. It is prohibited (rejected) by the Mac App Store [/Users/runner/work/1/s/output/samples/Basic/Uno/SkiaSharpSample.macOS/SkiaSharpSample.macOS.csproj]
  Done building target "_CompileToNative" in project "SkiaSharpSample.macOS.csproj".
```

I am not sure exactly what/where this comes from. All I have added in my sample is Uno, I have a macOS app building/archiving fine in release.

## Expected behavior

Not have the app reference QTKit.

## How to reproduce it (as minimally and precisely as possible)

Still going to create a minimal sample, but I got a binlog that may be helpful now:
[msbuild.zip](https://github.com/unoplatform/uno/files/4909671/msbuild.zip)

I have my PR that works, just get a build warning. There is a lot of sample assets, but not much extra code: 
https://github.com/mono/SkiaSharp/pull/1396

**EDIT**

Here is a sample:

[Archive.zip](https://github.com/unoplatform/uno/files/4909730/Archive.zip)
Binlog: [msbuild.binlog.zip](https://github.com/unoplatform/uno/files/4909731/msbuild.binlog.zip)

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.4.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: https://gist.github.com/mattleibow/89a0c715b8b527bc22b7cddea3c34f34)

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks Matthew!

I don't believe Uno is having any explicit dependency on QTKit (the sample app inside of uno [does not generate this message](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=17228&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=e7472d04-b09e-59b7-6e25-156b34b46add&l=2606)).

I wonder if it could be related to https://github.com/unoplatform/uno/pull/3021. If this is the case, it would mean that a media playback app would not be allowed on the store ?

**Comment by mattleibow** [comment]
@jeromelaban  I updated the issue with a minimal sample that does this, and added the new binlog

**Comment by mattleibow** [comment]
That PR adds AVFoundation, which is fine for macOS.

**Comment by MartinZikmund** [comment]
@ajpinedam adding you here, not urgent, but if anyone has a chance to debug this, then it is you 😀

**Comment by jeromelaban** [comment]
It looks like this issue may be addressable with the new "feature"-based linking of .NET 6.

**Comment by ajpinedam** [comment]
@jeromelaban  @MartinZikmund  @mattleibow  this issue [#5152](https://github.com/xamarin/xamarin-macios/issues/5152) from the the `xamarin.macios` repository has some information related to this warning.

The warning seems to be harmless when you are not shipping the app to the App Store, in case you are the app could get rejected. To resolve this issue they suggest adding some kind of [linking](https://docs.microsoft.com/en-us/xamarin/mac/deploy-test/linker#platform-linking)

[This direct comment](https://github.com/xamarin/xamarin-macios/issues/5152#issuecomment-580887921) on the issue has more information.

**Comment by jeromelaban** [comment]
Let's close this issue for now then.
