### ISSUE TITLE
[Android] BitmapIcon foreground property does not change the icon's color

### ISSUE THREAD

**Issue by NicolasChampagne** [unoplatform/uno#3533]
## Current behavior
Bitmap icon remains black

## Expected behavior
Bitmap icon should be the color of its set foreground property

## How to reproduce it (as minimally and precisely as possible)
Open uno sample app in android navigate to BitmapIcon_Generic.xaml and notice all icon are black and the button on the page has no effect.

## Environment

Nuget Package:

Package Version(s):
Latest master
Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MatFillion** [comment]
@LHuss let us know when your PR is merged so we can close this :)
