### ISSUE TITLE
Creating a Control Template

### ISSUE THREAD

**Issue by bdovaz** [unoplatform/uno#3534]
## On which page?

https://platform.uno/docs/articles/using-uno-ui.html#creating-a-control-template

## What's wrong?

1. In the code part inherits from "Control" class but in XAML part in inhertis from "UserControl" class.
2. In ControlTemplate class doesn't use "TargetType" attribute.
3. In the code part is missing the constructor with the "InitializeComponent" method:

public MyUserControl() {
    InitializeComponent();
}

Please check that docs part and compile and test it.

**Comment by jeromelaban** [comment]
Thanks for the report !

**Comment by bdovaz** [comment]
@jeromelaban you partially fixed this, it only has been the third point fixed.
