### ISSUE TITLE
[iOS] TimePicker ClockIdentifier Property autoresets to its default value after first pressed.

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#3541]
## Current behavior

![timepicker](https://user-images.githubusercontent.com/17461593/87475794-64609f00-c5f3-11ea-818a-6ff0477d33be.gif)
When I changed the property ClockIdentifierProperty into 24HourClock, it seems to works at first, but when you tap the TimePicker, it automatically resets to its default value (12HourClock).

## Expected behavior

We should be able to change the ClockIdentifier Property correctly on all platforms.

## How to reproduce it (as minimally and precisely as possible)

[ClockIndentifierSample.zip](https://github.com/unoplatform/uno/files/4921396/ClockIndentifierSample.zip)
Open the sample
Deploy on iOS
Tap on the second TimePicker

## Environment

Nuget Package: 

Package Version(s): Uno.UI: 3.0.0-dev.783

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version:16.4.5)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Xiaoy312** [comment]
fixed PR#3705
