### ISSUE TITLE
[WASM] Setting Template for ComboBoxItem breaks use of DisplayMemberPath

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3545]
## Current behavior

In WASM, if you use a ComboBoxItem style that sets Template then DisplayMemberPath does not work correctly.

## Expected behavior

ComboBox should still display content based on DisplayMemberPath, as in UWP

## How to reproduce it (as minimally and precisely as possible)

Launch the attached project in UWP and observe that the ComboBox, when clicked, displays the values assigned to String1.  Launch the project in WASM and observe that the content is not displayed, just the class name.

[ComboBoxSample.zip](https://github.com/unoplatform/uno/files/4925283/ComboBoxSample.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
3.0.0-dev.783
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
# Initial Investigations

## Problematic code
XAML:
``` xml
<ComboBox x:Name="box" DisplayMemberPath="Content" />
```
C#:
``` csharp
box.ItemsSource = new Test[] { new Test(), new Test(), new Test() };
[...]
public class Test
{
  public Content { get; } = Gruid.NewGuid().ToString();
}
```
## Platforms
This bug can be reproduced on all tested Uno platforms (Wasm, iOS & Android)
### Android
![combobox-bug-android](https://user-images.githubusercontent.com/4174207/90172975-bb33d280-dd71-11ea-8aa8-741696d2ef44.gif)
### iOS
![combobox-bug-ios](https://user-images.githubusercontent.com/4174207/90172996-c38c0d80-dd71-11ea-8704-a825a459c442.gif)
### Wasm
![combobox-bug-wasm](https://user-images.githubusercontent.com/4174207/90173064-db639180-dd71-11ea-8490-21ba30458737.gif)

**Comment by carldebilly** [comment]
Found the source of the problem: the _control template_ of the `ComboBoxItem` has been redefined in the `App.xaml` of the repro application.

In this template, a `TemplateBinding` is missing for the `ContentTemplateSelector`.

It should work unchanged as it's working in UWP, but right now the work-around is to set that TemplateBinding...

```
<ContentPresenter x:Name="ContentPresenter"
                  Content="{TemplateBinding Content}"
                  ContentTransitions="{TemplateBinding ContentTransitions}"
                  ContentTemplate="{TemplateBinding ContentTemplate}"
                  ContentTemplateSelector="{TemplateBinding ContentTemplateSelector}"
                  Foreground="{TemplateBinding Foreground}"
                  HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
                  VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
                  Margin="{TemplateBinding Padding}" />
```

**Comment by carldebilly** [comment]
https://github.com/unoplatform/uno/issues/3195 could be related to this issue.

**Comment by carldebilly** [comment]
The fix has been merged in Uno.UI v3.1.0-dev.375

**Comment by peternary** [comment]
Appears fixed in latest!
