### ISSUE TITLE
macOS Dark Theme: TextBox foreground not visible when typing

### ISSUE THREAD

**Issue by christosk92** [unoplatform/uno#3556]
If macOS is on dark mode and you have a textbox control, the foreground of the textbox changes to white, rendering the text not visible. 
Ex:

White Theme:
![image](https://user-images.githubusercontent.com/13438702/87712790-1025fe00-c75e-11ea-9273-f4911d89b35e.png)

Dark Theme:
![image](https://user-images.githubusercontent.com/13438702/87712909-39df2500-c75e-11ea-83d6-86168cdfce21.png)
![image](https://user-images.githubusercontent.com/13438702/87712920-3d72ac00-c75e-11ea-92e8-e892792dab31.png)

OS: macOS Catelina 10.15.5
Uno: Uno.UI 3.0.0 -dev.646 ( this issue also occurs on the stable builds)

**Comment by agneszitte-nventive** [comment]
Once Uno.UI 3.1.0-dev.41 is published, give it a try and let us know.
