### ISSUE TITLE
[Android/IOS/WASM] Cannot update style of WinUI ProgressBar

### ISSUE THREAD

**Issue by NicolasChampagne** [unoplatform/uno#3558]
## Current behavior
If you update the style of a the WinUI ProgressBar it becomes unusable on all other platforms but uwp

## Expected behavior
Updating style should work on all platforms.

## How to reproduce it (as minimally and precisely as possible)
Open Uno.Material
Go to branch dev/nich/progress-bar to see behavior of the ProgressBar

Other ways to see the behavior.
Uncomment the page.resource style on ProgressBarSamplePage.xaml
or simply add a foreground to the winui:ProgressBar and see that it does not function anymore.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
**Added two ProgressBars without styling at the bottom of the ProgressBarSamplePage.xaml to compare the behavior**

**Comment by carldebilly** [comment]
If we replace the `{StaticResources xxx}` values in the page with the correct colors, it works. Seems related to resources.

I also notice you're binding a `<Color />` to a `Brush` property. @davidjohnoliver?

**Comment by davidjohnoliver** [comment]
> I also notice you're binding a `<Color />` to a `Brush` property. @davidjohnoliver?

Well, it's probably that.

Converting `Color` to `SolidColorBrush` doesn't seem to be covered here (though the inverse is): https://github.com/unoplatform/uno/blob/master/src/Uno.UI/DataBinding/BindingPropertyHelper.FastConvert.cs
