### ISSUE TITLE
[ANDROID/IOS/WASM] PasswordBox RevealButton doesn't show expected UWP behavior

### ISSUE THREAD

**Issue by NicolasChampagne** [unoplatform/uno#3562]
## Current behavior
Clicking on the PasswordBox and typing shows the RevealButton.

## Expected behavior
Clicking On or Typing into a PasswordBox that previously contained Text should not show the RevealButton.

> The value of this property is not the only factor that determines whether a password reveal button is visible to the user. Other factors include whether the control is displayed above a minimum width, whether the PasswordBox has focus, and whether the text entry field contains at least one character. The password reveal button is shown only when the PasswordBox receives focus for the first time and a character is entered. If the PasswordBox loses focus and then regains focus, the reveal button is not shown again unless the password is cleared and character entry starts over.
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.passwordbox.passwordrevealmode?view=winrt-19041#peek-mode

<blockquote><img src="https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png" width="48" align="right"><div><strong><a href="https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.passwordbox.passwordrevealmode">PasswordBox.PasswordRevealMode Property (Windows.UI.Xaml.Controls) - Windows UWP applications</a></strong></div><div>Gets or sets a value that specifies whether the password is always, never, or optionally obscured. </div></blockquote>

## How to reproduce it (as minimally and precisely as possible)
Open the SampleApp 
Go to Sample Page TextBox -> PasswordBox_RevealScroll

Interact with PasswordBox

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
This is expected behaviour:
> The value of this property is not the only factor that determines whether a password reveal button is visible to the user. Other factors include whether the control is displayed above a minimum width, whether the PasswordBox has focus, and whether the text entry field contains at least one character. The password reveal button is shown only when the PasswordBox receives focus for the first time and a character is entered. If the PasswordBox loses focus and then regains focus, the reveal button is not shown again unless the password is cleared and character entry starts over.
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.passwordbox.passwordrevealmode?view=winrt-19041#peek-mode

**Comment by NicolasChampagne** [comment]
@davidjohnoliver If this is the expected behavior, then should an issue be opened that it is not occuring on all other platforms?

**Comment by davidjohnoliver** [comment]
@NicolasChampagne Yes that's legit :)
