### ISSUE TITLE
ElevatedView doesn't work if the background is set with a template binding

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#3563]
## Current behavior

![Screenshot_20200717-111008_ElevatedViewSample](https://user-images.githubusercontent.com/17461593/87801866-5e9ad180-c81e-11ea-8987-e6ae3687843c.jpg)
When we use the template binding to set the background of the elevated view, we don't see the shadow In the screenshot above, we use the template binding for the red square (first square)

On Wasm, the yellow square doesn't have his shadow effect either. Also, I found another issue with the height and width property getting ignored #3564 

## Expected behavior

We should be able to see the elevation even if the background is setted with a templatebinding.

## How to reproduce it (as minimally and precisely as possible)

[ElevatedViewSample.zip](https://github.com/unoplatform/uno/files/4938582/ElevatedViewSample.zip)
Open the sample
Deploy on any platform

## Environment

Nuget Package:

Package Version(s): Uno.UI: 3.0.0-dev.873

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS Doesn't work because of this issue #3551  
- [ ] Windows Doesn't work because of this issue #3539 
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.6.2)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
@takla21 Please recheck after pr #3557

**Comment by takla21** [comment]
Sorry for the delay. Basically I tried to update my sample with the latest dev version (3.0.0-dev.392) and the issue is still occurring on all platform. Moreover, I seeing nothing on wasm. I'm not sure if it's me or an issue with Uno.UI.Webassembly. 
[ElevatedViewSampleUpdate.zip](https://github.com/unoplatform/uno/files/4967339/ElevatedViewSampleUpdate.zip)
