### ISSUE TITLE
[WASM] Elevated Width and Height are not working

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#3564]
## Current behavior

The Height and Width property of the ElevatedView is ignored on Webassembly
![wasmelevetedview](https://user-images.githubusercontent.com/17461593/87805669-b851ca80-c823-11ea-8b36-7d156d57407d.jpg)

## Expected behavior

We should be able to set the height and width of an ElevatedView.
![uwpsize](https://user-images.githubusercontent.com/17461593/87805680-bdaf1500-c823-11ea-9862-ba554050600d.jpg)

## How to reproduce it (as minimally and precisely as possible)

[ElevatedViewSizeSample.zip](https://github.com/unoplatform/uno/files/4938723/ElevatedViewSizeSample.zip)
Open the sample on VS2019
Deploy on WASM

## Environment

Nuget Package:

Package Version(s): Uno.UI: 3.0.0-dev.873

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version:16.6.2)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

**Comment by carldebilly** [comment]
On Wasm, there is another problem: the shadow is properly displayed (you can see it by pressing F12), but the parent element is clipping it.
