### ISSUE TITLE
JSObjectHandle.Create() for nested classes generate bad JS

### ISSUE THREAD

**Issue by mattleibow** [unoplatform/uno#3568]
## Current behavior

I have a nested class:

```csharp
class SKSwapChainPanel {
  public SKSwapChainPanel() {
    var jsInterop = new SKSwapChainPanelJsInterop(this);
  }
  class JsInterop : IJSObject {
    public JsInterop(SKSwapChainPanel swap) {
      Handle = JSObjectHandle.Create(this);
    }
  }
}
```

The generated JS under the hood is badly formed and I get an error when it is constructed:

```
dotnet.js:2425 ﻿Error #1 "ReferenceError: JsInterop is not defined" executing javascript: "SkiaSharp.Views.UWP.SKSwapChainPanel+JsInterop.createInstance("18178", "1")"
```

In addition, the class that is really generated is not in a class:
```
SkiaSharp.Views.UWP.JsInterop
```

## Expected behavior

The process should work and be defined as `SkiaSharp.Views.UWP.SKSwapChainPanel.JsInterop`

## How to reproduce it (as minimally and precisely as possible)

Just declare the class and create it.

## Environment

Nuget Package: 1.4.0-dev.7

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Closing in favor of JSImport/JSExport new .NET 7 features.
