### ISSUE TITLE
[WASM] DisplayInformation.DpiChanged is not implemented

### ISSUE THREAD

**Issue by mattleibow** [unoplatform/uno#3569]
I notice the `DpiChanged` event is not implemented. It would be nice to get that working, especially with graphics libraries.

In a comment, there is a link to:
https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

That has a demo of some way to handle this.

**Comment by MartinZikmund** [comment]
@jeromelaban I will take care of this
