### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by pashmak73** [unoplatform/uno#3571]
Hi,
I'm new in Uno,
I've installed it and created an empty project to test it.
When I press f5 to build the project, VS gives me this errors:
![image](https://user-images.githubusercontent.com/46992431/87862841-92ced900-c969-11ea-81b6-cb57ae520b5b.png)

(All nuget packages restored successfully)

what should I do?

Thanks in advance

**Comment by jeromelaban** [comment]
Thanks for the report! It seems that your project has spaces in its name. Can you try creating one without spaces and let us know ?

**Comment by pashmak73** [comment]
@jeromelaban
Thanks.
It fixed my problem.
