### ISSUE TITLE
[ANDROID/IOS/WASM] Flyout Placement, differences between all platforms and UWP

### ISSUE THREAD

**Issue by NicolasChampagne** [unoplatform/uno#3582]
## Current behavior
UWP flyout placement respects its definition
Other platforms show a different flyout placement compared to UWP.

## Expected behavior
All platforms should show the same flyout placement that respects the choice of the placement choice.
No matter the size and original placement of the anchor.

## How to reproduce it (as minimally and precisely as possible)
- See sample app placements 
- See Uno.Material "See Xaml" buttons

## Environment
Latest packages/master

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
- Placement= Full,Auto, and LeftEdgeAlignedBottom show differently on platforms (**TESTED**)

**Comment by peternary** [comment]
A current issue is that attaching and displaying a flyout programmatically has inconsistent positioning between Uwp and WASM.

[FlyoutPosition.zip](https://github.com/unoplatform/uno/files/5283881/FlyoutPosition.zip)

**Comment by peternary** [comment]
Confirmed fixed in latest
