### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by pashmak73** [unoplatform/uno#3583]
Hi,
Sorry for title.
I just some questions.
As I read in the docs, we shouldn't update Microsoft.Extensions.Logging.Console.

1. Can I update Microsoft.NETCore.UniversalWindowsPlatform package? 
2. I've tested FileOpenPicker, it seems it's not working in android, I did some digging in uno source code and it seems it's not implemented. Is there any way to support it or suggest a replacement for it?
3. There is an FFmpeg wrapper for uwp called [FFmpegInteropX](https://github.com/ffmpeginteropx/FFmpegInteropX), do you guys have any plans to add it?
4. Is there any support for win2d.uwp library?
5. I'm planning to use Uwp Toolkit (uno ported) should I add it to all projects or UWP one only?

Thanks in advance.

**Comment by pkar70** [comment]
FileOpenPicker: see PR#2896

**Comment by jeromelaban** [comment]
@pkar70 thanks for the reminder. You still need to adress the comments in that PR.

**Comment by jeromelaban** [comment]
@pashmak73 thanks for your interest in Uno.

1. Yes you can.
2. Not it's not implemented yet. You can use the native features for it, depending on the platform.
3. No plans yet. What scenarion are you interested in with ffmpeg ?
4. No, not at this point. You can use Skia instead.
5. You can follow this example: https://github.com/unoplatform/Uno.Samples/tree/master/UI/WCTTabView/TabViewSample
