### ISSUE TITLE
Port Sharpnado.Shadows to Uno

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#3586]
# Port Sharpnado.Shadows to Uno

Repo is there: https://github.com/roubachof/Sharpnado.Shadows

## For which Platform:

- [X] iOS
- [X] Android
- [X] WebAssembly
- [X] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- ~~[ ] Windows~~

**Comment by MartinZikmund** [comment]
I guess this can be closed in favor of other shadow tasks in progress 😉? @roubachof
