### ISSUE TITLE
[iOS] Date picker buttons to confirm and cancel are not visible

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#3593]
## Current behavior

The button "Done" and "Cancel" on the date picker are not visible

## Expected behavior

The button "Done" and "Cancel" on the date picker are visible

## How to reproduce it (as minimally and precisely as possible)

Sample:
[DatePickerCropped.zip](https://github.com/unoplatform/uno/files/4957461/DatePickerCropped.zip)

## Environment

Nuget Package: Uno.UI

Package Version(s): 3.0.0-dev.899

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

No Internal issue

**Comment by Xiaoy312** [comment]
addressed by #3688
