### ISSUE TITLE
[WASM] Hiding VerticalScrollBar in ScrollViewer also hides HorizontalScrollBar

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3594]
## Current behavior

If you set VerticalScrollBarVisibility="Hidden" in a ScrollViewer then the HorizontalScrollBar also becomes hidden, though you can still interact with it by clicking in the appropriate area.

## Expected behavior

HorizontalScrollBar appearance should be independent of VerticalScrollBar.

## How to reproduce it (as minimally and precisely as possible)

In the sample [here](http://playground.platform.uno/#8a508c88) you can see two sample uses of ScrollViewer, the only difference being that the top one has  VerticalScrollBarVisibility="Hidden" set.

In the top sample notice that the HorizontalScrollBar is also hidden, though clicking and dragging in the area you would expect it to appear works.

## Environment

Nuget Package:
Uno.UI
Package Version(s):
3.0.0-dev.899
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Fixed by https://github.com/unoplatform/uno/pull/4193

**Comment by peternary** [comment]
Confirmed fixed
