### ISSUE TITLE
HotReload not working with space in username

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#3601]
## Current behavior
HotReload does not work with an Uno-Solution of the username contains a space.

## Expected behavior
HotReload should work in all cases.

## How to reproduce it (as minimally and precisely as possible)
I found out that it depends on where the Nuget-Package-Cash resides. So one easy way to test it should be to change the NUGET_PACKAGES-environment-variable to a path containing spaces. the default value on my machine was `global-packages: C:\Users\Prename Surname\.nuget\packages\`. You can see that path with the command `nuget locals all -list`. You can change it as documented [here ](https://docs.microsoft.com/de-de/nuget/consume-packages/managing-the-global-packages-and-cache-folders) by chaning the NUGET_PACKAGES-variable.
In my case after rebuilding the solution and restoring the packages HotReload worked on Android again, UWP is still not working, though. A "normale" UWP-App has HotReload and I did not yet find the differences.

## Environment

Nuget Package: Uno.UI.RemoteControl

Package Version(s): v3.0.0-dev-783

Affected platform(s):

- [X] iOS (assumed)
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: 16.6.5)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Note for contributors 

This is the location where is issue lies: https://github.com/unoplatform/uno/blob/3442621d558b783bd5a227de0e61e7edf72c9a31/src/Uno.UI.RemoteControl.VS/EntryPoint.cs#L188

**Comment by jeromelaban** [comment]
Thanks for the report!

For the UWP hot reload, the issue is here: https://developercommunity.visualstudio.com/comments/1078811/view.html. The workaround is not pretty at all, but at least it works.

**Comment by jeromelaban** [comment]
I updated the issue with additional details on the issue.
