### ISSUE TITLE
[IOS] Timepicker is not visible when application is in dark mode

### ISSUE THREAD

**Issue by NicolasChampagne** [unoplatform/uno#3606]
## Current behavior
Timepicker is not visible when application is in dark mode

## Expected behavior
Timepicker is visible when application is in dark mode

## How to reproduce it (as minimally and precisely as possible)
Switch phone to dark mode and open a timepicker from the Uno SampleApp

## Environment

Nuget Package:

Package Version(s):
Latest master 

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carlh98** [comment]
With Uno.UI 3.0.0-dev.1143, the timepicker is visible in darkmode, but now it's not visible in Light Mode, the prompt is black in light mode

**Comment by NicolasChampagne** [comment]
Yes, as pr in uno is up to fix the issue since monday. https://github.com/unoplatform/uno/pull/3641
