### ISSUE TITLE
VS4Mac fails to load Uno.UI solution

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#3609]
## Current behavior

VS4Mac fails to open the `Uno.UI.sln` solution.

## Expected behavior

The solution loads properly.

## Workaround

Before opening `Uno.UI-vs4mac-macos-only.sln`, delete the following lines:

https://github.com/unoplatform/uno/blob/dd552676811bf1fcf09c882b6ea76af7b0943fae/src/PlatformItemGroups.props#L42-L44 

https://github.com/unoplatform/uno/blob/dd552676811bf1fcf09c882b6ea76af7b0943fae/src/PlatformItemGroups.props#L48-L50

https://github.com/unoplatform/uno/blob/dd552676811bf1fcf09c882b6ea76af7b0943fae/src/PlatformItemGroups.props#L54-L56

https://github.com/unoplatform/uno/blob/dd552676811bf1fcf09c882b6ea76af7b0943fae/src/PlatformItemGroups.props#L60-L62

Make sure to set the crosstargeting file to `xamarinmac20`.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
Another workaround is to use Jetbrains Rider, that handles it well.

**Comment by jeromelaban** [comment]
Fixed in recent VS builds
