### ISSUE TITLE
[WASM] Implement FrameworkElement.Tag

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3616]
## What would you like to be added:

FrameworkElement.Tag support for WASM

## Why is this needed:

Sometimes it is desirable to add small additional information to a given control.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report Peter.

While the property is marked as not implemented, its behavior is the correct one. We'll remove the marker.

**Comment by peternary** [comment]
No longer seeing the warning as of latest, appears fixed.
