### ISSUE TITLE
[Wasm] ImageBrush Stretch property is not applied

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#3621]
## Current behavior

ImageBrush Stretch property is not applied (Uniform, Fill and UniformToFill)

## Expected behavior

ImageBrush Stretch property should be applied

## How to reproduce it (as minimally and precisely as possible)

Sample:
[ImageBrushSample.zip](https://github.com/unoplatform/uno/files/4972877/ImageBrushSample.zip)

## Environment

Nuget Package:
Uno.UI
Uno.UI.WebAssembly

Package Version(s):
3.0.0-dev.956

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

No internal issue

**Comment by MatFillion** [comment]
@carldebilly  is this related to https://github.com/unoplatform/uno/pull/3719 ?

**Comment by carldebilly** [comment]
@MatFillion Yep it is. Only `Fill` stretch mode works yet. If you need another stretch mode, you should use an `<Image>` instead.

**Comment by carlh98** [comment]
Issue present in Wasm for 3.6.0-dev.167
