### ISSUE TITLE
Update Uno.Core dependency Microsoft.Extensions.Logging to version 3+

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/uno#3624]
## What would you like to be added:
`Uno.Core` depends on `Microsoft.Extensions.Logging` 1.1.1 but must depend on 3.1.6

## Why is this needed:
Modern `Microsoft.Extensions.Hosting` (version 3+) allows building a host similar to ASP.NET Core in any app (UWP, Xamarin, WPF etc.) with all the logging and dependency injection. See my sample at https://andrii.visualstudio.com/Elmish.Uno
But having a dependency on the old API (version 1.1.1) of `Microsoft.Extensions.Logging` requires to implement workarounds like
``` C#
var loggerFactory = serviceProvider.GetRequiredService<ILoggerFactory>();
var _loggerFactoryField =
    typeof(global::Uno.Extensions.LogExtensionPoint)
        .GetField("_loggerFactory", System.Reflection.BindingFlags.NonPublic
                                    | System.Reflection.BindingFlags.Static);
_loggerFactoryField.SetValue(null, loggerFactory);
```
And I assume can cause issues on AOT and WASM platforms.

## Affected packages
**Uno.Core 2.0.0**

## For which Platform:

- [X] iOS
- [X] Android
- [X] WebAssembly
- [X] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [X] Windows
- [X] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the issue. Updating Uno.Core is not needed, and what you're looking for is `ServiceLocator.Current`, which provides the value set in `_loggerFactory`. Try setting this property with the appropriate service locator instead of using reflection.

**Comment by xperiandri** [comment]
But I don't want to get the instance of `ILooggerFactory` but replace Uno's instance of `ILooggerFactory` with my instance of `ILooggerFactory` which is from package v 3.1.6

**Comment by xperiandri** [comment]
``` C#
private readonly IServiceProvider serviceProvider;
private IServiceScope scope;

serviceProvider =
    Host.CreateDefaultBuilder()
        .ConfigureServices(ConfigureServices)
        .ConfigureServices(configurePlatformServices ?? (_ => { }))
        .ConfigureLogging(ConfigureFilters)
        .Build()
        .Services;
scope = serviceProvider.CreateScope();

**Comment by jeromelaban** [comment]
Indeed, and upgrading the package version wont change much for that. What could be done though is update `Uno.Core` to provide the ability to set the logger factory without having to provide a `ServiceLocator`, and that does not need the increase the version of the loggers.

**Comment by xperiandri** [comment]
That would be great
