### ISSUE TITLE
[WASM][ComboBox] Item is not stretching properly on WASM

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/uno#3639]
## Current behavior

Item doesn't stretches fully in the combo box popup.

![image](https://user-images.githubusercontent.com/64613932/88572722-a6cfa600-d00d-11ea-9137-cf6178862a7f.png)

## Expected behavior

Item stretches fully in the combo box popup.

## How to reproduce it (as minimally and precisely as possible)

Open Uno Material, then navigate to the combo box page. 

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by agneszitte-nventive** [comment]
@MaximeDion-Work an issue was already open for this on Uno: https://github.com/unoplatform/uno/issues/3357
(cc @jeromelaban / @davidjohnoliver )
