### ISSUE TITLE
TextWrapping="Wrap" does not seem to work for TextBox on Android:

### ISSUE THREAD

**Issue by zipswich** [unoplatform/uno#3648]
## Current behavior

TextWrapping="Wrap" does not seem to work for TextBox on Android:

## Expected behavior

TextWrapping="Wrap" should work for TextBox on Android:

## How to reproduce it (as minimally and precisely as possible)

```
<ScrollViewer Grid.Row="2">
            <TextBox  
                HorizontalAlignment="Center"
                TextWrapping="Wrap"
                MaxWidth="720"
                MinWidth="360"
                Padding="8"
                IsReadOnly="True"
                Text="{x:Bind sAbout}"
                />

        </ScrollViewer>
```

## Environment

Nuget Package: Uno.UI 

Package Version(s): 3.0.0-dev.1113

Affected platform(s): Android

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by abrull** [comment]
Any updates on this?

**Comment by Youssef1313** [comment]
The code seems to unconditionally set layout parameters to wrap content:

https://github.com/unoplatform/uno/blob/ee021917bc51f5c5b243389166386efc836875a7/src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.Android.cs#L59-L63

Surprised that this doesn't work 😕
