### ISSUE TITLE
Enhance documentation on how to use native control styles

### ISSUE THREAD

**Issue by SetTrend** [unoplatform/uno#3649]
# What would you like clarification on:

I read that Uno renders all controls in Windows style and there is an option somewhere deep in Uno to have some of the controls render in native OS style.

I believe it's crucial to be able to switch an application's (or page's) property to render controls using native styles wherever applicable (and to be able to switch back to Windows style again whenever felt necessary).

Can you please prominently describe how to switch between native rendering and Windows style rendering in the FAQ and the documentation?

## Concern?

- [ ] Usage in industry
- [ ] Clarification of capabilities
- [X] Getting started with Uno
- [X] Developing with Uno
- [ ] Contributing to the Uno project
- [ ] Publishing your application
- [ ] Support
- [ ] Other (please specify):

## For which Platform:

- [X] iOS
- [X] Android
- [ ] WebAssembly
- [X] macOS
- [ ] Windows

**Comment by davidjohnoliver** [comment]
Agreed this an important Uno feature. There's a starting point here https://github.com/unoplatform/uno/blob/master/doc/articles/using-uno-ui.md#using-styles addressing Uno 3.0+ support for native styles.

**Comment by SetTrend** [comment]
Excellent!

From the referenced documentation I'm not quite sure whether I will be able to render UWP style only for particular pages, or even particular elements only.

**This is my use case:**

In general, I would prefer to render native controls throughout my app. For one, I presume they will be rendered faster; and for two, the user is acquainted to this controls style and will prefer this style.

Then, there may be a "sophisticated" page in my app where I want all controls to adhere to my fancy custom UWP style. Or there may be only a single grid in a page where I want my fancy styles to apply.

Can this be done, too? Is there something like a style attribute I can add to XAML elements to switch mode?

Perhaps my question is stupid. I'm new to UWP, please forgive my ignorance if it is.

**Comment by davidjohnoliver** [comment]
This is actually straightforward to do for single elements. You can assign a `StaticResource` (a resource, such as a style, a brush, or control template, defined elsewhere in Xaml) to the `Style` property, and Uno's native and UWP styles all have associated StaticResources following the naming convention in the link. So in your example it would be:
```xaml
<NativePresenterArea>
  <ToggleSwitch not_win:Style="{StaticResource NativeDefaultToggleSwitch}"/>
</NativePresenterArea>

<!-- or -->

<UwpPresenterArea>
  <ToggleSwitch not_win:Style="{StaticResource XamlDefaultToggleSwitch}"/>
</UwpPresenterArea>
```

See [here](https://platform.uno/docs/articles/platform-specific-xaml.html) for an explanation of the `not_win` prefix.

There's no out-of-the-box way to say 'all controls within this page should have UWP/native styling' at the moment.

**Comment by SetTrend** [comment]
Fascinating! Thanks a lot for this very helpful information!

Would you suggest to keep this issue open as a reminder for adding your valuable information to the FAQ? Or should this issue rather be closed?

**Comment by davidjohnoliver** [comment]
Let's keep it open, it's a valid documentation request and the info does belong in [the docs](https://github.com/unoplatform/uno/tree/master/doc/articles), not just in an issue comment ;)

**Comment by agneszitte-nventive** [comment]
@davidjohnoliver For now the info could be added under [articles](https://github.com/unoplatform/uno/tree/master/doc/articles) into a new howto file right ?

**Comment by davidjohnoliver** [comment]
@agneszitte-nventive Indeed :) Something like `using-native-styles.md` in that folder.

**Note for contributors:** As mentioned in an earlier comment, expanding the material [here](https://github.com/unoplatform/uno/blob/master/doc/articles/using-uno-ui.md#using-styles) would be a good basis.

There are also [a couple more configuration methods added recently](https://github.com/unoplatform/uno/blob/bfcfb791913d9ac80967b60293941796d2dee36d/src/Uno.UI/FeatureConfiguration.cs#L289-L310) which can be documented.

**Comment by michael-hawker** [comment]
@davidjohnoliver this just came up as [a question in the UWP Community Discord Server](https://discord.com/channels/372137812037730304/550416151172087808/819865469515071539). Glad to see like you're picking this up again soon, as I think some of the previous links above have changed/moved?
