### ISSUE TITLE
[WASM]Classes that inherit Path cannot be drawn after upgrading from v2.4.4 to v3.0.0-dev.1002

### ISSUE THREAD

**Issue by Daoting** [unoplatform/uno#3654]
## Current behavior
Many graphics in my chart library inherit from Path. Now they cannot be drawn. For example:
```
    public partial class Bar : Path, ICustomClipping
    {
        protected override bool Render(RenderContext rc)
        {
           ...
            PathGeometry geometry = new PathGeometry();
            PathFigure pf = new PathFigure();
            pf.Segments.Add(new LineSegment { Point = new Point() });
            pf.Segments.Add(new LineSegment { Point = new Point(rect.Width, 0) });
            pf.Segments.Add(new LineSegment { Point = new Point(rect.Width, rect.Height) });
            pf.Segments.Add(new LineSegment { Point = new Point(0, rect.Height) });
            pf.Segments.Add(new LineSegment { Point = new Point() });
            geometry.Figures.Add(pf);
            Data = geometry;

            Canvas.SetLeft(this, rect.X);
            Canvas.SetTop(this, rect.Y);
           ...
            return true;
        }
        ...
    }
```
The html is:
```
  <div id="480322" xamltype="Dt.Charts.Bar" xamlhandle="480322" class="uno-bar uno-plotelement uno-path uno-arbitraryshapebase uno-shape uno-frameworkelement uno-uielement" tabindex="-1" style="clip: rect(-1px, 41.4639px, 370.21px, -1px); position: absolute; top: 35.79px; left: 157.721px; width: 0.5px; height: 0.5px;">
   <path id="480290" xamltype="Windows.UI.Xaml.Wasm.SvgElement" xamlhandle="480290" tabindex="-1" class="uno-svgelement uno-uielement uno-clippedToBounds" d="M 0,0 L 0,0 L 40.4638888888889,0 L 40.4638888888889,369.21 L 0,369.21 L 0,0" style="fill: rgb(206, 186, 99); stroke: rgb(116, 101, 36); stroke-width: 1px; transform: matrix(1, 0, 0, 1, 0, 0);"></path>
  </div>
```
Path.Data is right, it seems that the svg tag is missing.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Daoting** [comment]
I have an example to remind not to forget. Thanks. @jeromelaban @dr1rrb 
[ForUno](https://github.com/Daoting/ForUno)
Set the break point [here](https://github.com/Daoting/ForUno/blob/f65fb19d27c4a65656297cff4e5dfaf83f82ca9e/Dt.Charts/PlotElement/Bar.cs#L34). After starting, click on the five-point star in Figure 1, and then click on the first item in Figure 2.

**Comment by Daoting** [comment]
Is there a plan to fix this bug?  Thanks. @jeromelaban @dr1rrb

**Comment by jeromelaban** [comment]
@Daoting not in the short term. Have you tried debugging Uno to find out what happens ?
