### ISSUE TITLE
Document native Frame navigation with Uno

### ISSUE THREAD

**Issue by mkwhalen** [unoplatform/uno#3660]
## What would you like clarification on:
Outline the steps and best practices for adding page navigation in the shared project. 

## Concern?

- [ ] Usage in industry
- [ ] Clarification of capabilities
- [ ] Getting started with Uno
- [X ] Developing with Uno
- [ ] Contributing to the Uno project
- [ ] Publishing your application
- [ ] Support
- [ ] Other (please specify):

## For which Platform:

- [X ] iOS
- [X ] Android
- [X ] WebAssembly
- [X ] macOS
- [X ] Windows

**Comment by christosk92** [comment]
Could you please elaborate what you mean with Page navigation?
You should just be able to call[ `Frame.Navigate(Type)` ](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.frame.navigate?view=winrt-19041).

**Comment by davidjohnoliver** [comment]
**Note for contributors:** This should cover the native Frame navigation mode supported on Android and iOS, which integrates with the native navigation patterns on those platforms, and document the characteristics and limitations of the native navigation.

The native behaviour and limitations are already rather exhaustively documented for [CommandBar (and AppBarButton)](https://github.com/unoplatform/uno/blob/master/doc/articles/controls/CommandBar.md), what's mainly missing is a higher-level overview and how-to guide. (With Uno 3.1 calling [this method](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/FeatureConfiguration.cs#L293) should suffice to enable native frame navigation.)
