### ISSUE TITLE
[WASM] Indeterminate ProgressBar looks static

### ISSUE THREAD

**Issue by jcantin-nventive** [unoplatform/uno#3673]
## Current behavior

A ProgressBar with IsIndeterminate=True simply looks like a gray bar on WASM, whereas there is a nice animation on UWP.

## Expected behavior

A ProgressBar with IsIndeterminate=True has a nice animation similar to the one on UWP.

## How to reproduce it (as minimally and precisely as possible)

```
<ProgressBar IsIndeterminate="True" />
```

https://github.com/jcantin-nventive/JCantinUnoTestApp/tree/dev/juca/latest-dev

## Environment

Nuget Package: Uno.UI.WebAssembly

Package Version(s): v3.0.0-dev.1153

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.3)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MatFillion** [comment]
Is it the same issue with the winui:ProgressBar ?

**Comment by jcantin-nventive** [comment]
> Is it the same issue with the winui:ProgressBar ?

No, this only occurs with the basic ProgressBar

**Comment by francoistanguay** [comment]
We'll only support the WinUI 2.X ProgressBar moving forward unless absolutely required..
