### ISSUE TITLE
[WASM] NavigationView becomes blank when window is resized

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#3700]
## Current behavior

The NavView Pane content becomes blank after you resized your window
![nav](https://user-images.githubusercontent.com/17461593/89189493-0974f480-d56e-11ea-9831-bdb68937e976.gif)

## Expected behavior

The NavView should not become blank.

## How to reproduce it (as minimally and precisely as possible)

- Download this sample [NavigationViewSample.zip](https://github.com/unoplatform/uno/files/5016306/NavigationViewSample.zip)
- Deploy the sample on webassembly
- Navigate to any of the pages
- Resize window to minimum width
- Close the NavigationView
- Maximize the window
- Open the NavigationView
- Notice that the NavigationView is blank

## Environment

Nuget Package: Uno.UI.WebAssembly

Package Version(s): 3.0.0-dev.1294

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.6.2)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dr1rrb** [comment]
This has been fixed by https://github.com/unoplatform/uno/pull/3748
