### ISSUE TITLE
[WASM] Favicon is not loaded anymore

### ISSUE THREAD

**Issue by vincentcastagna** [unoplatform/uno#3701]
## Current behavior

 - Favicon does not work 

## Expected behavior

- Favicon to work 

## How to reproduce it (as minimally and precisely as possible)

- Run a wasm project, put favicon.ico and so in the assets folder. Favicon is not displayed. 

This issue has been introduced since changes in the WASM boostraper (cc : @carldebilly @jeromelaban ) and **we would need it for Channel 9 .**

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MakanWG** [comment]
@vincentcastagna Is it just the favicon ? I noticed on one of my projects that after a clean, no Image in the Asset folder (shared or project specific) is displayed anymore in Wasm with the newest versions of the Bootstraper. Couldn't pinpoint wich version exactly though

**Comment by carldebilly** [comment]
This issues is fixed in the `Uno.Wasm.Bootstrap` package v`1.4.0-dev.45`.
