### ISSUE TITLE
Default style properties are not carried over when declaring a new style

### ISSUE THREAD

**Issue by benventive** [unoplatform/uno#371]
## I'm submitting a...
Bug report (I searched for similar issues and did not find one) 

## Current behavior
Declaring a style doesn't keep the default style properties that are not overriden

## Expected behavior
Setting a style with only certain properties should keep the default style properties

## Minimal reproduction of the problem with instructions
Use the following style in an Uno app:
```
<Style x:Key="TextBoxStyle"
           TargetType="TextBox">
	<Setter Property="BorderThickness"
                     Value="1" />
	<Setter Property="BorderBrush"
                     Value="DarkGray" />
</Style>
```
The TextBoxes will show up without a template.

## Environment
**Nuget Package:**
Uno.UI

**Package Version(s):** 
1.42.0-dev.334

**Affected platform(s):**
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

**Visual Studio:**
- [ ] 2017 (version: )
- [x] 2017 Preview (version: 15.9.0 Preview 6.0)
- [ ] for Mac (version: )

**Comment by davidjohnoliver** [comment]
Falls under #119

**Comment by benventive** [comment]
One workaround I've found is to base the style on [the Uno one](https://github.com/nventive/Uno/blob/8dcc6f2d3aa5d57fd3ee96efe5fe73855a45a0da/src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml).
For example, in the case of the TextBox described in this issue:
```
<Style x:Key="TextBoxStyle"
       xamarin:BasedOn="{StaticResource XamlDefaultTextBox}"
       TargetType="TextBox">
  <Setter Property="BorderThickness"
          Value="1" />
  <Setter Property="BorderBrush"
          Value="DarkGray" />
</Style>
```
