### ISSUE TITLE
Setting Foreground of BitmapIcon does not apply on some platforms

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3710]
## Current behavior

On some platforms (e.g. Android), setting `Foreground` on a `BitmapIcon` does not apply the color properly.

## Expected behavior

Color should be applied.

## Environment

Nuget Package: latest

Package Version(s): latest

Affected platform(s):

Tested on Android, but maybe others are affected as well.

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by Youssef1313** [comment]
@MartinZikmund Here is the current behavior on Android:

![image](https://user-images.githubusercontent.com/31348972/130322669-756f8f0b-6afd-4b1e-9c31-816fabaa2c56.png)

Can you elaborate more? Isn't it currently correct?

**Comment by MartinZikmund** [comment]
That seems OK, let's close then
