### ISSUE TITLE
NavigationView selection indicator is duplicated

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3711]
## Current behavior

As user clicks items in `NavigationView` the selection indicator rectangle gets duplicated on each clicked item.

## Expected behavior

There should be only one single indicator.

## How to reproduce it (as minimally and precisely as possible)

Create `NavigationView` with multiple menu items and run on Android.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

Tested on Android, others might be affected too.

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Which version of Uno did you try it with? It should have been fixed with latest master.

**Comment by MartinZikmund** [comment]
Wasn't the absolute latest, will check

**Comment by MartinZikmund** [comment]
Verified this is fixed in latest version, closing :-) .
