### ISSUE TITLE
[iOS][CommandBar] AppBarButton with complex content causes freeze/no data context set 

### ISSUE THREAD

**Issue by vincentcastagna** [unoplatform/uno#3712]
## Current behavior

- Using CommandBar.PrimaryCommands with an AppBarButton that defines its content with a control (Path, TextBlock, Image etc ...) causes the AppBarButton to not have any DataContext. This issue drags with it another one that causes a strange behavior when using AdaptiveTrigger/RotationPreferences (the command bar causes the app to freeze when rotating to landscape), CommandBar.IsVisible = Collapsed for example. 

## Expected behavior

- Can use Path, TextBlock etc as AppBarButton content, with right DataContext and no freeze on iOS when rotating to landscape and or using AdaptiveTrigger on CommandBar 

## How to reproduce it (as minimally and precisely as possible)

```
<CommandBar.PrimaryCommands>
	<AppBarButton x:Name="AboutButton"
				   Command="{Binding ToAboutPage}">
				<Path Style="{StaticResource InfoIconPath}"
				            VerticalAlignment="Center" />
	</:AppBarButton>
</CommandBar.PrimaryCommands>
```

**WORKAROUND** : 

```
<CommandBar.PrimaryCommands>
        <ios:AppBarButton x:Name="AboutButton"
				        Command="{Binding ToAboutPage}">
				<AppBarButton.Icon>
					<BitmapIcon UriSource="ms-appx:///Assets/Icon.png" />
				</AppBarButton.Icon>
			</ios:AppBarButton>
</CommandBar.PrimaryCommands>
```

## Environment

Nuget Package:

Package Version(s):

Uno 3.0 dev 1253

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
@vincentcastagna is this still an issue? And are we talking about the XAML CommandBar or the native CommandBar?

**Comment by kazo0** [comment]
@vincentcastagna  can you try and repro with the latest verisons of Uno? I can't seem to repro this one
