### ISSUE TITLE
[Android/WASM] TextBlock MaxLines is not correctly taking into account while having a fixed Width

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#3714]
## Current behavior 

Use the TextBlock MaxLines property while setting a fixed width and notice that you are able to see all the lines for Android/WASM.

**UWP**
![image](https://user-images.githubusercontent.com/16295702/89323943-795daa80-d654-11ea-8c7b-a47936bea1c2.png)

**iOS**
![image](https://user-images.githubusercontent.com/16295702/89324174-e07b5f00-d654-11ea-9024-e0481aa6865f.png)

**Android**
![image](https://user-images.githubusercontent.com/16295702/89324246-fab53d00-d654-11ea-8690-b1ca825f1d09.png)

**WASM**
![image](https://user-images.githubusercontent.com/16295702/89323826-53380a80-d654-11ea-8a05-0308e5e56be3.png)

## Expected behavior

MaxLines property should be correctly supported like for UWP/iOS even with a fixed width.

## How to reproduce it (as minimally and precisely as possible)

```
<TextBlock Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
				   MaxLines="4"
				   TextWrapping="Wrap"
				   Width="200" />
```

## Environment

Nuget Package: Uno.UI

Package Version(s): 3.0.0-dev.1359

Affected platform(s):

- [ ] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: 16.5.4)
- [ ] for Mac (version: )

**Comment by carldebilly** [comment]
Update: the Android version should be fixed by PR #4448
