### ISSUE TITLE
[WASM] ToggleSwitch mouseover looks incorrect with fluent styles

### ISSUE THREAD

**Issue by jcantin-nventive** [unoplatform/uno#3720]
## Current behavior

When we mouseover the ToggleSwitch, the white dot in the toggle disappears. This occurs when we use <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" /> in the latest version.

![image](https://user-images.githubusercontent.com/43351943/89428128-0e6eab00-d70a-11ea-90b6-3bbbd4bd5085.png)

vs

![image](https://user-images.githubusercontent.com/43351943/89428190-1d555d80-d70a-11ea-9e7a-e1de4e19849e.png)

## Expected behavior

When we mouseover the ToggleSwitch, the toggle does not lose its white dot.

## How to reproduce it (as minimally and precisely as possible)

https://github.com/jcantin-nventive/JCantinUnoTestApp/tree/dev/juca/toggle-switch-mouseover
Launch the app on WASM.
Hover the mouse over the toggle switch.

## Environment

Nuget Package: Uno.UI.WebAssembly

Package Version(s): 3.0.0-dev.1388

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.3)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MatFillion** [comment]
Also happens on MacOS
internal reference: https://nventive.visualstudio.com/Uno%20Gallery/_workitems/edit/191240
