### ISSUE TITLE
[iOS] NavigationView automatically opens the pane when we rotate the device

### ISSUE THREAD

**Issue by jcantin-nventive** [unoplatform/uno#3729]
## Current behavior

When we launch an app on iOS with a NavigationView with IsPaneOpen=true, and then rotate the device and arrive to a different state, the pane automatically opens. It then stays open as we rotate back to the original position.

Note: We have similar behavior on WASM but I wasn't able to reproduce it in the sample.

## Expected behavior

Rotating the device does not automatically the pane.

## How to reproduce it (as minimally and precisely as possible)

https://github.com/jcantin-nventive/JCantinUnoTestApp/tree/dev/juca/split-view-state

Launch the app and rotate the device.
IsPaneOpen becomes true and you can see the gray light dismiss overlay.

## Environment

Nuget Package: Uno.UI 

Package Version(s): 3.0.0-dev.1117 and 3.0.0-dev.1388

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.3)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Xiaoy312** [comment]
Can no longer be reproduced with `Uno.UI@4.0.11`. `IsPaneOpen` remains the same on device rotation.
