### ISSUE TITLE
Hi, I Always Have This Errors, And I Did Not Know Why, I Cant Run A Project , Or Build

### ISSUE THREAD

**Issue by babakmdi** [unoplatform/uno#3731]
![image](https://user-images.githubusercontent.com/65450661/89570934-1a5a8a00-d83c-11ea-919d-cfcbb7b107cf.png)

**Comment by francoistanguay** [comment]
Have you followed the steps for our Getting Started? What version of VS/Uno/.net sdk are you using?

Do you have a sample repro?
