### ISSUE TITLE
Missing Project Subtype UWP error

### ISSUE THREAD

**Issue by PylotLight** [unoplatform/uno#3740]
## Current behavior

Shows error when creating new project.

## Expected behavior

Creates new UWP project without error.

## How to reproduce it (as minimally and precisely as possible)

Download UNO templates, open VS2019 and create new UNO App, get error on creation.
All other projects complete, but UWP does not get created.

## Environment

![image](https://user-images.githubusercontent.com/7006124/89612210-939cc000-d8c2-11ea-9faa-dc4bc1e092c3.png)

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [X] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: 16.7)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by PylotLight** [comment]
Did a full repair of VS and reinstall of UNO templates with no success.

**Comment by AathifMahir** [comment]
Same issue here as well

![Screenshot 2020-08-10 005014](https://user-images.githubusercontent.com/17165402/89740110-bb974980-daa3-11ea-80c3-54131a2bafef.png)

**Comment by PylotLight** [comment]
It was due to missing package content for me @AathifMahir 
Make sure you have the correct packages added:
![image](https://user-images.githubusercontent.com/7006124/89743670-be685d80-dae8-11ea-8b5d-299e11dd9577.png)
