### ISSUE TITLE
MapControl is not displaying

### ISSUE THREAD

**Issue by nnikos123** [unoplatform/uno#3741]
I tried to use the mapcontrol on android following your detailed instructions

after putting the GoogleMapsApiKey in the manifest file compiling and deploying the app , map is not visible.
Same thing after upgrading from v2.4.4 to the latest 3.0.0-dev.1493.
So basically mapcontrol is not working

Now, while  compiling the android project I noticed the following line in the vstudio output window:

C:\uwp\UNO\App1\App1.Droid\obj\Debug\90\android\AndroidManifest.xml : warning XA4218: Unable to find //manifest/application/uses-library at path: C:\Program Files (x86)\Android\android-sdk\platforms\android-28\optional\com.google.android.maps.jar

Actually, there is no such file in the above mentioned folder and I am sure that I have installed all sdk & build tools. 
Other controls in android target work fine.

Also, if Xamarin.AndroidX.Lifecycle.LiveData goes from 2.1.0 to 2.2.0.1 my app crashes.

Is there any working out of the box sample of mapcontrol on android to test it?

thanks

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

**Comment by jeromelaban** [comment]
@davidjohnoliver you mentioned that this issue could be closed and that the missing part is samples ?

**Comment by davidjohnoliver** [comment]
Yes - this is fixed now in Uno 3.3. There's some additional integration now needed (adding `MapResources` to `Application.Resources`) which is more fully detailed in https://platform.uno/docs/articles/controls/map-control-support.html . It's also updated to depend on the latest Play Services.

For a working sample you can check the one in the `Uno.Samples` repository: https://github.com/unoplatform/Uno.Samples/tree/master/UI/MapControlSample
