### ISSUE TITLE
Add support for `CalendarDatePicker`

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#3750]
## What would you like to be added:
CalendarDatePicker.

## Why is this needed:
Because I'm using it in my projects.

## For which Platform:

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by robloo** [comment]
Definitely an important one to add. I wonder if there would be performance problems re-implementing this entirely in C#/XAML once WinUI 3.0 source is available. Calendars have a lot of elements in them and I'm not sure performance would be what it needs to be? Should it be a fully managed control or should it integrate with native calendars on each platform?

**Comment by robloo** [comment]
Also linking to your past PR https://github.com/unoplatform/uno/pull/2079

**Comment by pkar70** [comment]
Best part is that it WAS implemented - previous implementation of Uno.DatePicker looks like UWP.CalendarDatePicker. To make my PR, I simply copy all code and XAML from Uno.DatePicker to Uno.CalendarDatePicker, and change type in DateChanged event (between nullable and not nullable type).
My PR was created months before Uno.DatePicker was changed to look like UWP.DatePicker...

**Comment by francoistanguay** [comment]
Clearly something we want to tackle asap. We already looked at it and started the work. It's a massive control but we're not worried by performance, just the sheer volume of the implementation.

Once we publish a  tentative roadmap, you can count for it to be in.

**Comment by pkar70** [comment]
Why "massive control"? It is very simple control (at least, on Android; below 300 lines of code). Many months ago I copied control logic from "DatePicker" (when it looks like UWP CalendarDatePicker), changed type of DateChanged event (between nullable and not nullable type), create PR with it, and I'm using it in my Uno apps (published e.g. on Amazon and Google store). It was not merged, though, because I have problems with creating test.

**Comment by robloo** [comment]
@pkar70  Don't forget that CalendarDatePicker uses CalendarView for the calendar. CalendarView is not a simple control and has features you might not expect. In addition, for this control to meet performance requirements, there added complexities such as phased rendering. I'm assuming the CalendarView is going to be implemented instead of using the native calendar on each platform which explains the 'massive' wording. Also don't forget all the different types of calendar systems for the various cultures.

https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/calendar-view

**Comment by pkar70** [comment]
Why? CalendarDatePicker could use, at least on Android, similar Android control (DatePicker). So, Uno should only wrap Android.DatePicker, or convert between UWP syntax and Android.DatePicker syntax.

**Comment by francoistanguay** [comment]
Agreed that if a platform (Android), we could implement CalendarDatePIcker for this platform specifically. Our goal however is to port WinUI/UWP CalendarView first to make sure we have an option that also works on various Desktops and WASM. Then, through styling, you can tap into the Android Native Picker if you prefer. The same way we've done it for Date Picker in the past.

**Comment by robloo** [comment]
Great work! I think this was the last major missing set of controls :)

**Comment by francoistanguay** [comment]
Yup. 244 files later. Amazing work by the team and incredible reuse from the original creators!
