### ISSUE TITLE
[WASM] Theme resources not picked up in UserControl

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3753]
## Current behavior

Consider the following XAML:

```
<UserControl.Resources>
        <ResourceDictionary>
            <ResourceDictionary.ThemeDictionaries>
                <ResourceDictionary x:Key="Default">
                    <SolidColorBrush x:Key="HeaderBackground" Color="#111" />
                </ResourceDictionary>
                <ResourceDictionary x:Key="Light">
                    <SolidColorBrush x:Key="HeaderBackground" Color="#EEE" />
                </ResourceDictionary>
            </ResourceDictionary.ThemeDictionaries>
        </ResourceDictionary>
    </UserControl.Resources>
    <Grid Padding="12" Background="{ThemeResource HeaderBackground}">
    ...
```

Currently, this will keep the `Grid` background transparent.

## Expected behavior

In UWP, this will correctly use the right `HeaderBackground` resource based on current theme.

## How to reproduce it (as minimally and precisely as possible)

See above.

## Workaround

Put the theme resources in `<Application.Resources>`

## Environment

Nuget Package: Uno.UI

Package Version(s): 3.0.0-dev.1515

Affected platform(s):

Seen on WASM, probably applies everywhere.

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

**Comment by kevmoens** [comment]
I had the same issue with AppBarButtons
<Application
    x:Class="LicensingActivationSite.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:LicensingActivationSite">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.ThemeDictionaries>
                <ResourceDictionary x:Key="Dark">
                    <SolidColorBrush x:Key="AppBarButtonForegroundPointerOver" Color="White"/>
                    <SolidColorBrush x:Key="AppBarButtonForegroundPressed" Color="#46a8e2"/>
                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPointerOver" Color="Black"/>
                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPressed" Color="Black"/>
                </ResourceDictionary>
                <ResourceDictionary x:Key="Light">
                    <SolidColorBrush x:Key="AppBarButtonForegroundPointerOver" Color="White"/>
                    <SolidColorBrush x:Key="AppBarButtonForegroundPressed" Color="#46a8e2"/>
                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPointerOver" Color="Black"/>
                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPressed" Color="Black"/>
                </ResourceDictionary>
            </ResourceDictionary.ThemeDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>

**Comment by kevmoens** [comment]
I had the same issue with AppBarButtons
`<Application
    x:Class="LicensingActivationSite.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:LicensingActivationSite">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.ThemeDictionaries>
                <ResourceDictionary x:Key="Dark">
                    <SolidColorBrush x:Key="AppBarButtonForegroundPointerOver" Color="White"/>
                    <SolidColorBrush x:Key="AppBarButtonForegroundPressed" Color="#46a8e2"/>
                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPointerOver" Color="Black"/>
                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPressed" Color="Black"/>
                </ResourceDictionary>
                <ResourceDictionary x:Key="Light">
                    <SolidColorBrush x:Key="AppBarButtonForegroundPointerOver" Color="White"/>
                    <SolidColorBrush x:Key="AppBarButtonForegroundPressed" Color="#46a8e2"/>
                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPointerOver" Color="Black"/>
                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPressed" Color="Black"/>
                </ResourceDictionary>
            </ResourceDictionary.ThemeDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
`

**Comment by kevmoens** [comment]
I had the same problem with AppBarButtons
'<Application
    x:Class="LicensingActivationSite.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:LicensingActivationSite">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.ThemeDictionaries>
                <ResourceDictionary x:Key="Dark">
                    <SolidColorBrush x:Key="AppBarButtonForegroundPointerOver" Color="White"/>
                    <SolidColorBrush x:Key="AppBarButtonForegroundPressed" Color="#46a8e2"/>
                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPointerOver" Color="Black"/>
                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPressed" Color="Black"/>
                </ResourceDictionary>
                <ResourceDictionary x:Key="Light">
                    <SolidColorBrush x:Key="AppBarButtonForegroundPointerOver" Color="White"/>
                    <SolidColorBrush x:Key="AppBarButtonForegroundPressed" Color="#46a8e2"/>
                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPointerOver" Color="Black"/>
                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPressed" Color="Black"/>
                </ResourceDictionary>
            </ResourceDictionary.ThemeDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
'

**Comment by kevmoens** [comment]
I had the same problem with AppBarButtons
`<Application

    x:Class="LicensingActivationSite.App"

    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"

    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"

    xmlns:local="using:LicensingActivationSite">

    <Application.Resources>

        <ResourceDictionary>

            <ResourceDictionary.ThemeDictionaries>

                <ResourceDictionary x:Key="Dark">

                    <SolidColorBrush x:Key="AppBarButtonForegroundPointerOver" Color="White"/>

                    <SolidColorBrush x:Key="AppBarButtonForegroundPressed" Color="#46a8e2"/>

                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPointerOver" Color="Black"/>

                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPressed" Color="Black"/>

                </ResourceDictionary>

                <ResourceDictionary x:Key="Light">

                    <SolidColorBrush x:Key="AppBarButtonForegroundPointerOver" Color="White"/>

                    <SolidColorBrush x:Key="AppBarButtonForegroundPressed" Color="#46a8e2"/>

                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPointerOver" Color="Black"/>

                    <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPressed" Color="Black"/>

                </ResourceDictionary>

            </ResourceDictionary.ThemeDictionaries>

        </ResourceDictionary>

    </Application.Resources>

</Application>
`

**Comment by davidjohnoliver** [comment]
@kevmoens Could you please open a separate [bug report](https://github.com/unoplatform/uno/issues/new?labels=kind%2Fbug%2C+triage%2Funtriaged&template=bug-report.md) with a fuller description of the issue you encountered? It's probably a separate issue from the one @MartinZikmund is reporting.

**Comment by davidjohnoliver** [comment]
Contributor note: I could repro this on WASM but not iOS, it seems to be a platform-specific issue (bizarrely).
