### ISSUE TITLE
Stack panel content alignment differs on Android

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3755]
## Current behavior

Consider the following XAML:

```
<ScrollViewer Padding="12" Grid.Row="1">
    <StackPanel Spacing="4">
        <ContentControl Margin="0,12" IsEnabled="{x:Bind Model.IsLoaded, Mode=OneWay}">
            <StackPanel Spacing="6" Width="240" Orientation="Vertical" BorderBrush="Gray" BorderThickness="2" Padding="12">
                <TextBox Header="Arguments" Text="{x:Bind Model.NewItem.Arguments, Mode=TwoWay}" />
                <TextBox Header="Display name" Text="{x:Bind Model.NewItem.DisplayName, Mode=TwoWay}" />
                <TextBox Header="Description" Text="{x:Bind Model.NewItem.Description, Mode=TwoWay}" />
                <ComboBox Header="Icon" ItemsSource="{x:Bind Model.Icons}" SelectedItem="{x:Bind Model.NewItem.Logo, Mode=TwoWay}">
                    <ComboBox.ItemTemplate>
                        <DataTemplate>
                            <BitmapIcon UriSource="{Binding}" Width="40" ShowAsMonochrome="False" />
                        </DataTemplate>
                    </ComboBox.ItemTemplate>
                </ComboBox>
                <Button IsEnabled="{x:Bind Model.IsLoaded, Mode=OneWay}" Command="{x:Bind Model.AddItemCommand}">Add item</Button>
            </StackPanel>
        </ContentControl>
    </StackPanel>
</ScrollViewer>
```

When launched on Android, the `ContentControl` is centered within the page.

## Expected behavior

In UWP, `ContentControl` is aligned to the left.

## Workaround

Manually align the control.

## How to reproduce it (as minimally and precisely as possible)

See above

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

Tested on Android, maybe happens on others as well.

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by dr1rrb** [comment]
Seems linked to https://github.com/unoplatform/uno/issues/3347

**Comment by dr1rrb** [comment]
Closing this one in favor of https://github.com/unoplatform/uno/issues/3347 (as it's already linked to an issue of another private project)
