### ISSUE TITLE
WASM splash screen not stretched uniformly

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3756]
## Current behavior

WASM Splash screen image is not stretched uniformly

![Screenshot_20200809-212620.jpg](https://user-images.githubusercontent.com/1075116/89740233-39009100-da87-11ea-922f-cd655545c0ab.jpg)

## Expected behavior

Should be stretched uniformly. 

## How to reproduce it (as minimally and precisely as possible)

Create a blank app and open on phone

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Which version of the packager are you using ?

**Comment by MartinZikmund** [comment]
@jeromelaban Where can I see the packager version? I have `Uno.Wasm.*` packages at v1.4.0-dev.16,
