### ISSUE TITLE
Using `global` as namespace prefix breaks x:Bind 

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#3777]
## Current behavior

Using :
```
xmlns:global="using:System.Globalization"
```
fails with :

```
1>MSBUILD : error : Generation failed: System.AggregateException: One or more errors occurred. --->  Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.NameSyntax'. ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.NameSyntax'.
```

## Expected behavior

The build works properly

## Environment

Nuget Package: 3.0

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

The current implementation of Uno x:Bind support uses roslyn to parse the expression, and `global` has a special meaning. The input string is not sanitized properly, leading to parsing errors.

**Comment by Youssef1313** [comment]
@jeromelaban @MartinZikmund I wasn't able to reproduce this. Can you please check if this was already fixed or attach a repro? Thanks!

**Comment by Youssef1313** [comment]
Pinging @jeromelaban

**Comment by jeromelaban** [comment]
The original repro was along those lines:

```xaml
<Page
    x:Class="xBindGlobalRepro.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:global="using:System.Globalization"
    xmlns:sys="using:System"
    xmlns:local="using:xBindGlobalRepro"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
		<TextBlock Text="{x:Bind sys:String.Format(global:CultureInfo.CurrentCulture, '{0}', MyInteger)}" />
    </Grid>
</Page>
```

But it looks like we've fixed it somehow. Let's close it then.
