### ISSUE TITLE
Theme resources not picked up in AppBarButton

### ISSUE THREAD

**Issue by kevmoens** [unoplatform/uno#3780]
## Current behavior

I added styling for AppBarButtons.  In the UWP project this creates a hover effect to the AppBarButtons.  In Wasm the display doesn't react to the hover.
`<Application
x:Class="LicensingActivationSite.App"

xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"

xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"

xmlns:local="using:LicensingActivationSite">

<Application.Resources>

    <ResourceDictionary>

        <ResourceDictionary.ThemeDictionaries>

            <ResourceDictionary x:Key="Dark">

                <SolidColorBrush x:Key="AppBarButtonForegroundPointerOver" Color="White"/>

                <SolidColorBrush x:Key="AppBarButtonForegroundPressed" Color="#46a8e2"/>

                <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPointerOver" Color="Black"/>

                <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPressed" Color="Black"/>

            </ResourceDictionary>

            <ResourceDictionary x:Key="Light">

                <SolidColorBrush x:Key="AppBarButtonForegroundPointerOver" Color="White"/>

                <SolidColorBrush x:Key="AppBarButtonForegroundPressed" Color="#46a8e2"/>

                <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPointerOver" Color="Black"/>

                <SolidColorBrush x:Key="AppBarButtonRevealBackgroundPressed" Color="Black"/>

            </ResourceDictionary>

        </ResourceDictionary.ThemeDictionaries>

    </ResourceDictionary>

</Application.Resources>
` 

## Expected behavior

When I hover over the AppBarButtons it should change to black background and white foreground.

## How to reproduce it (as minimally and precisely as possible)

        <CommandBar Grid.ColumnSpan="2" Background="#46a8e2" IsOpen="True" IsSticky="False"  >
            <CommandBar.PrimaryCommands>
                <AppBarButton x:Name="ActivationCode" Label="Request Activation Code" Width="100"  IsEnabled="False" Foreground="White"/>
                <AppBarButton x:Name="VerificationCode" Label="Enter Verification Code" Width="100"  Foreground="White"/>
            </CommandBar.PrimaryCommands>
        </CommandBar>

## Environment

Nuget Package:

Package Version(s):
Uno.UI 2.4.0
Uno.Core 2.0.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by francoistanguay** [comment]
This should be fixed by 3.0 and there are no plans to retrofit this to 2.4. Is this an active project and if so, could you possibly migrate to 3.0?

**Comment by kevmoens** [comment]
I upgraded to 
Nuget Package:

Package Version(s):
Uno.UI.WebAssembly 3.0.12
Uno.Core 2.0.0

and I reproduced the issue:

**Comment by francoistanguay** [comment]
Oh, thanks for the quick feedback. The team will look at this asap!
