### ISSUE TITLE
Can't create a 'Cross-Platform Library (Uno Platform)' using the 3.0 Templates

### ISSUE THREAD

**Issue by sonnemaf** [unoplatform/uno#3794]
I can't create 'Cross-Platform Library (Uno Platform)' using the 3.0.5.8 Solution Templates in Visual Studio 2019. I get this error message.

**The element <PackageReference> beneath element <Project> is unrecognized.  C:\Users\Fons\source\repos\KillerSudoku2\ReflectionIT.Uno\ReflectionIT.Uno.csproj**

## Current behavior
See screenshot

![image](https://user-images.githubusercontent.com/9335559/90114182-ab58c600-dd52-11ea-9044-5044961a3f23.png)

## Expected behavior

A class library in my current or new solution

## How to reproduce it (as minimally and precisely as possible)

Create a new Solution and select the 'Cross-Platform Library (Uno Platform)' template. Enter a name and click the Create button.

## Environment
Visual Studio 2019

**Comment by jeromelaban** [comment]
Thanks for the report! We'll look into this.

**Comment by sonnemaf** [comment]
Hi @jeromelaban, 

Can you send me the content of an Empty .csproj file of a Uno ClassLibrary? I can then continue my development of KillerSudoku.

Thx,

**Comment by jeromelaban** [comment]
Of course, it's this file (which the PR above will change):

https://github.com/unoplatform/uno/blob/a6af858a0f58dbc1a00cad21761e28629c96da9c/src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.csproj
