### ISSUE TITLE
ItemsControl: template recreated multiple times

### ISSUE THREAD

**Issue by baptiste-nv** [unoplatform/uno#382]
## I'm submitting a...
Bug report 

## Current behavior
When using an ItemsControl, item templates are created multiple times. 
Resources used by extra items seem to be not properly released.

ListView seems to be affected as well.

## Expected behavior
Item template should be instantiated only one time.
If recreated, resources need to be properly released.

## Environment
Nuget Package: 
Uno.UI 1.42.0-dev.392

Affected platform(s):
- [X] iOS
- [X] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [X] 2017 (version: )
- [X] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

Internal issue: https://nventive.visualstudio.com/Umbrella/_workitems/edit/139686

**Comment by baptiste-nv** [comment]
Some investigation results:
- Items?.Clear(); in OnItemsSourceChanged triggers SetNeedsUpdateItems(), which causes 2 calls on UpdateItems instead of 1
- ItemsPanelRoot.Children.UpdateWithResults in UpdateItems() does not compare items (or their containers) properly, which causes performance issue as everything is recreated each time
- ResetDataContextOnFirstLoad in ContentPresenter causes subsequent calls for unknown reason, as DataContext is cleared then reset with same content

**Comment by davidjohnoliver** [comment]
@jeromelaban @baptiste-nv any idea if this has been fixed?

**Comment by davidjohnoliver** [comment]
Confirmed fixed (see tests in https://github.com/unoplatform/uno/pull/4609).
