### ISSUE TITLE
[WASM] WebSocket connection failed

### ISSUE THREAD

**Issue by ushenkodmitry** [unoplatform/uno#3821]
## Current behavior

On launching WASM app i'm seeing default splash screen and errors in console
WasmWebSockets.js:21 WebSocket connection to 'ws://169.254.179.193:63847/rc' failed: Error in connection establishment: net::ERR_ADDRESS_UNREACHABLE
![image](https://user-images.githubusercontent.com/16700959/90332006-d432c280-dfc1-11ea-9c7d-3ef051534c71.png)

## Expected behavior

My app main screen and no errors in the console.

## How to reproduce it (as minimally and precisely as possible)

1. Update any existing (i think so) Uno app from 2.4 to 3.0.0
2. Run WASM head

## Environment

Nuget Package:

Package Version(s):
```
    <PackageReference Include="ReactiveUI.Uno" Version="11.5.26" />
    <PackageReference Include="Splat.Microsoft.Extensions.DependencyInjection" Version="9.5.20" />
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls" Version="6.1.0-build.191.gc988bdd4ff" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="3.1.0-dev.8" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.WebAssembly" Version="3.0.5" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="1.4.0-dev.24" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="1.4.0-dev.24" />
```

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

I had an application that was built with 2.4 version of Uno. It was running with no error. After updating to the latest i'm starting to see it. It is pretty simple application just to try Uno features on WASM. With no any additional configuration being made.

**Comment by jeromelaban** [comment]
Thanks for the report. Those errors are generated by the `Uno.UI.RemoteControl` in debug, as the application is trying to connect to the XAML Hot Reload server. You can safely ignore those errors.

**Comment by ushenkodmitry** [comment]
Will something terrible happen with my app when this URL become reachable?
)
Its quiet strange to me that the app is trying to connect to unknown ws
endpoint.

вс, 16 авг. 2020 г. в 20:05, Jérôme Laban <notifications@github.com>:

**Comment by jeromelaban** [comment]
All these addresses are part of your machine's local network interfaces, so no, nothing will happen if they become reachable.
