### ISSUE TITLE
Cross Platform Library project creation using the 3.0.5.8 templates fails with the message “The element <PackageReference> beneath element <Project> is unrecognized.”

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#3833]
## Current behavior

Unable to create a Uno Library Project  using the templates

## Expected behavior

Project should be created
## How to reproduce it (as minimally and precisely as possible)

Try and create a project in an existing solution

## Environment

VS 2019 Professional 16.7.1

Nuget Package:

Package Version(s): 
Templates 3.0.5.8

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.7.1)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
![template issue](https://user-images.githubusercontent.com/4189260/90410381-32cf6d80-e0a2-11ea-8f08-0e1a94bdad9e.PNG)

**Comment by jeromelaban** [comment]
Fixed in https://github.com/unoplatform/uno/pull/3802, it's going to be published soon. You can use [this as a reference](https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.csproj).
