### ISSUE TITLE
Support Windows Community Toolkit

### ISSUE THREAD

**Issue by FrancoisM** [unoplatform/uno#384]
Can you please support the [Windows Community Toolkit Expander control](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/expander)?

**Comment by weitzhandler** [comment]
Very compelling!

**Comment by robloo** [comment]
Was this ever implemented? According to the blog post below it was.

https://platform.uno/blog/uno-platform-and-windows-community-toolkit-datagrid-tabview-and-expander-with-sample-code/

> Uno Platform now includes a bunch of fixes and feature enhancements that unlock more of WCT for mobile and web. While we have supported WCT for a long time now on https://windowstoolkit-wasm.platform.uno, in this blog post we’ll highlight some of the WCT controls you’ll now be able to use with Uno.
>
> WCT Expander running on Web (via WebAssembly), iOS, Android, and soon macOS

Then there seems to be an open bug https://github.com/unoplatform/uno/issues/3030 saying it doesn't actually work.

**Comment by jeromelaban** [comment]
@robloo we added support for the community toolkit, yet there are controls that do not work on all platforms, Expander being one (e.g. it works on iOS/Wasm). If you find a control/feature that does not work, let us know by opening an issue.

**Comment by MartinZikmund** [comment]
This can be closed, for further missing features we will open separate issues.
