### ISSUE TITLE
[iOS, Android, WASM] NumberBox features are not fully integrated

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/uno#3851]
## Current behavior

Certain features like header, placeholder text and SpinButtonPlacementMode="Compact" are not supported like on UWP. 

![image](https://user-images.githubusercontent.com/64613932/90672654-72be5e00-e224-11ea-8812-2328f850a815.png)

## Expected behavior

UWP

![image](https://user-images.githubusercontent.com/64613932/90672076-92a15200-e223-11ea-89fd-6a7a5ec4daec.png)

## How to reproduce it (as minimally and precisely as possible)

```
<Page x:Class="Uno.Gallery.Views.Samples.NumberBoxSample"
	  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	  xmlns:local="using:Uno.Gallery.Views.Samples"
	  xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
	  xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
	  xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
	  mc:Ignorable="d">

	<StackPanel>

		<muxc:NumberBox Value="0" />

		<muxc:NumberBox Header="Enter a number:"
						Value="0" />
		
		<muxc:NumberBox PlaceholderText="1+2^2" />
		
		<muxc:NumberBox Value="0"
						SmallChange="10"
						LargeChange="100"
						SpinButtonPlacementMode="Inline" />

		<muxc:NumberBox Value="0"
						SmallChange="10"
						LargeChange="100"
						SpinButtonPlacementMode="Compact" />
	</StackPanel>
</Page>

```

## Environment

Nuget Package: Uno.UI 3.0.0-dev.1535

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

NumberBox documentation
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/number-box

**Comment by robloo** [comment]
The NumberBox code in Uno was imported from WinUI Release 2.3.191129002 (2237b09d9ba6052414ddccf3d61316de20564303). There were some pretty big fixes adopted for WinUI 2.4 related to NumberBox. It will be a good idea to update NumberBox to the latest WinUI code and see if the above issue(s) are fixed. It might also be a good idea to wait a few months until https://github.com/microsoft/microsoft-ui-xaml/issues/3158 is complete.

**Comment by MaximeDion-Work** [comment]
Issues still persist on Uno.UI 3.1.0-dev.215

**Comment by francoistanguay** [comment]
Can we check this again now that Popup has been moved?

**Comment by marwalsch** [comment]
Compact mode seems to work in 4.0.1 using WinUI. There is a missing inline icon visible though (which could be removed altogether as interacting with the input anywhere opens the input).

![image](https://user-images.githubusercontent.com/72074423/155972305-1234fc00-683a-4340-8d2c-b0374349b07e.png)


![image](https://user-images.githubusercontent.com/72074423/155972014-c5358da6-cefd-4c27-8186-b09f3b05fa9d.png)

**Comment by jeromelaban** [comment]
Could be related to https://github.com/unoplatform/uno/pull/7257
