### ISSUE TITLE
Add support for `CoreWindow.KeyDown`

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#386]
## I'm submitting a...
- Feature request

## Expected behavior
Add support for CoreWindow.KeyDown. This issue may be helper by the merging of #160.

## Environment
Nuget Package: 1.42

## Sample

```csharp
protected override void OnAttached()
{
   CoreWindow.GetForCurrentThread().KeyDown += OnKeyDown;
}

private void OnKeyDown(CoreWindow sender, KeyEventArgs args)
{
     if (args.VirtualKey == Windows.System.VirtualKey.Enter && AssociatedObject.Command?.CanExecute(null) == true)
     {
        AssociatedObject.Command.Execute(null);
     }
}
```

**Comment by carldebilly** [comment]
The problem with this one is the support on Android. What is the use case?

**Comment by yowl** [comment]
This perhaps?  

https://github.com/nventive/Uno.Telerik.UI-For-UWP/blob/7be75b0ffacf176eddbce6feecb1193f322b0575/Controls/Input/Input.UWP/NumericBox/RadNumericBox.cs#L686

Or is the TextBox KeyDown not the same as CoreWindow KeyDown?

**Comment by paulovila** [comment]
The use case is when you want to implement the default action on a screen , let's say in a login window, after you type the password you should be able to press Enter key and that automatically should be able to trigger a command, which can be enabled or disabled depending on the UI.

**Comment by yowl** [comment]
Another use case is the arrow keys to navigate combo box and also the delete key to clear a bound combobox, e.g. with the xaml:
```
<ComboBox x:Name="cmb" ItemsSource="{Binding Items}" SelectedItem="{Binding SelectedItem, Mode=TwoWay}"></ComboBox>
```
and the code behind:
```
        public MainPage()
        {
            Items = Enumerable.Range(0, 5).Select(i => i.ToString()).ToList();
            this.InitializeComponent();
            DataContext = this;

            cmb.KeyDown += DeletableComboBoxKeyDown;
        }

        void DeletableComboBoxKeyDown(object sender, KeyRoutedEventArgs e)
        {
            if (e.Key == VirtualKey.Delete || e.Key == VirtualKey.Back)
            {
                SelectedItem = null;
            }
        }
        public List<string> Items { get; set; }

        public static readonly DependencyProperty SelectedItemProperty = DependencyProperty.Register(
            "SelectedItem", typeof(object), typeof(MainPage), new PropertyMetadata(default(object)));

        public object SelectedItem
        {
            get { return (object)GetValue(SelectedItemProperty); }
            set { SetValue(SelectedItemProperty, value); }
        }
```
In UWP you can select an item in the combo and press delete to clear it.  This should be possible in wasm.

**Comment by yowl** [comment]
Further investigation on trying to get a workaround for KeyRoutedEventArgs  and trying to hook it up using `RegisterHtmlEventHandler("keydown", OnSimpleEvent);` has so far been fruitless as the `EventArgs` parameter when `OnSimpleEvent` is called is null.

**Comment by yowl** [comment]
The following does work however on an individual control
```
            comboBox.AddHandler(UIElement.KeyDownEvent, keyDownHandler, true);
```
