### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by pashmak73** [unoplatform/uno#3880]
Hi,
First thank you for your awesome work.

You've added a lot of UI features, but you didn't add the most important thing in all platforms. Working with files/folders is very messy, mostly is not implemented, I've seen some PRs for android, you can merge it to the master branch or change somethings in their code and merge it.

https://github.com/unoplatform/uno/pull/2773
https://github.com/unoplatform/uno/issues/508
https://github.com/unoplatform/uno/issues/3215
https://github.com/unoplatform/uno/pull/2774/

I don't know how Uno works, That's why I don't know where should I start .  if you give me some information to get starting to help these PRs I really appreciate it.
 
Thanks in advance

**Comment by francoistanguay** [comment]
Most of these should've been tackled If something is missing, please open a specific issue.
