### ISSUE TITLE
Add target platforms selection in project templates

### ISSUE THREAD

**Issue by YBAZAN** [unoplatform/uno#3885]
## What would you like to be added:
By default, when we create a new Uno application project, a project is generated for all platforms. However, we may target specific platforms. It would avoid having many head projects not fitting with the goal of the development.

It should be the same for the cross-platform shared project template.

## Why is this needed:
This is not a big deal, but it would improve the global impression of Uno. 

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [x] Solution Templates

**Comment by francoistanguay** [comment]
This is available at the command line with "dotnet new". Is this enough?

**Comment by YBAZAN** [comment]
Thanks for the indication, François. I've searched in the documentation and eventually found information about using the CLI to generate projects.

Maybe a suggestion about it: it is under VS Code section. You may set a CLI section independent from the IDE and put the different options in a table, like we use to see in Microsoft docs site. 

I still think that integrating platforms selection in the VS templates (through the extension) make sense. But we have another way to do it, so it's absolutely not a priority.

Last point, the FAQ in the documentation is... wow... I mean it needs a refresh, but it's another topic...

**Comment by francoistanguay** [comment]
Totally agree that short term, we need to update CLI docs asap (It's planned for next week).
Then we'll explore how we could enhance the solution template creation in the IDE.
Thanks!
