### ISSUE TITLE
Implement StorageFile.GetFileFromApplicationUriAsync

### ISSUE THREAD

**Issue by edparitor** [unoplatform/uno#3887]
## What would you like to be added:
Please implement StorageFile.GetFileFromApplicationUriAsync with it's support for ms-appx Uris.

## Why is this needed:
I've been trying to reintroduce the ImageCropper to the WCT sample apps.  The sample app had to jump through 2 different hoops on iOS and Android in order to open a stream on the images in the Assets folder:
https://github.com/edparitor/Uno.WindowsCommunityToolkit/commit/d1182006318feea7ccbef03f29061bb1d8e87093
and this only worked because the resource was an image.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?
I can see that other issues have mentioned that this is used in the wild to retrieve files that aren't images - ie configuration files

**Comment by MartinZikmund** [comment]
This one will be trickier, as the application assets on Android/macOS are not _actually_ files with a path, so we will need to introduce some abstraction here (especially to make sure it works with other existing APIs which depend on `StorageFile`).
