### ISSUE TITLE
[iOS] Height of the CommandBar is ignored

### ISSUE THREAD

**Issue by Guidemarcus** [unoplatform/uno#3892]
## Current behavior

The CommandBar is visible, but does not have an actual height. The content of the page goes under the CommandBar making the content not entirely visible.

## Expected behavior

The content of the page should be entirely visible.

## How to reproduce it (as minimally and precisely as possible)

[CommandBar.zip](https://github.com/unoplatform/uno/files/5131578/CommandBar.zip)

## Workaround

OnAppLaunch:
```csharp
#if __IOS__
			// Workaround for #193628: [iOS] Height of the CommandBar is ignored
			// This is the actual height of the CommandBar on iOS: https://platform.uno/docs/articles/controls/CommandBar.html
			var commandBarHeight = 44;
			// This is just below the status bar.
			var bounds = ApplicationView.GetForCurrentView().VisibleBounds;
			// We've seen cases where the Top is reported as 0 when it's actually 20.
			var top = Math.Max((double)bounds.Top, 20);
			resources.Add("CommandBarHeight", top + commandBarHeight);
#endif
```

In the definition of the CommandBar style:
```xaml
<ios:Setter Property="Height"
                   Value="{StaticResource CommandBarHeight}" />
```

## Environment

VS2019 16.7.2

Nuget Package: Uno.UI -> 3.0.11

Package Version(s): 

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Same thing happened on ch9. This bug might have been introduced by https://github.com/unoplatform/uno/commit/b3361cce9f4279f54a2a90db3f14febd708775fb (still need to be confirmed)

**Comment by YGuerin** [comment]
@carldebilly Just test Uno 1.45.0 and Uno 3.0.12. The result is the exact same. You shouldn't consider that as a regression

**Comment by carldebilly** [comment]
It seems this bug has been introduced by the PR#431 (still need to be confirmed).

**Comment by jeanplevesque** [comment]
This is still happening on latest canaries, projects are still required to make workarounds.

https://github.com/unoplatform/nventive-private/issues/165

**Comment by jeanplevesque** [comment]
It's happening on Uno.UI **3.5.0-dev392** as well as **3.1.14**.
