### ISSUE TITLE
Add support for MarkupExtension

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#39]
See for details: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.markup.markupextension

**Comment by weitzhandler** [comment]
Would love to see it. Pretty important to me. Please implement.

**Comment by weitzhandler** [comment]
Would love to see it.

**Comment by assassin316** [comment]
Any ETA on this ???

**Comment by ghuntley** [comment]
@assassin316, if you have the time and willingness to help out then it'll happen sooner. The team has reserved time in every sprint to mentor folks on how to contribute features to Uno. Let me know if you are keen.

**Comment by davidjohnoliver** [comment]
#901 just added some samples, it didn't implement the feature.

**Comment by Massimo37** [comment]
@weitzhandler No, that sample simply shows what features are working with x:Bind and what works with MarkExtension. When you run it, it'll show "feature not supported" for MarkupExtension when running in Android and iOS (as well as "feature not supported" for x:Bind on functions).

**Comment by weitzhandler** [comment]
Oh I see.
Well @ghuntley what does it take to implement this feature? I believe it's in the XAML parser isn't it? Can we import it from [WPF](https://github.com/dotnet/wpf) now that's it's been open sourced?

**Comment by weitzhandler** [comment]
Very compelling feature. Many of my converters are declared as Markup extensions (for example: `IsEnabled="{Binding IsBusy, Converter={c:BooleanConverter Switch=True}}"`)

**Comment by assassin316** [comment]
I agree, MarkupExtensions can open up more possibilities for developers to customize their xaml.

**Comment by michael-hawker** [comment]
@weitzhandler agree with @Massimo37 I didn't realize you could do converters with markup extensions 🎉, I thought you would at least still have needed the bits they hadn't implemented yet from WPF for that. I totally want to convert all our Toolkit ones now... almost...

[This WPF example](https://github.com/Hybrid-SyntaX/Automated-Attendance-System-Using-Face-Recognition/blob/master/code/AAS.GUI.Converters/Converters/BooleanConverter.cs) looked pretty simple, so I tried something similar out quick... That turned into a long fight with VS on how to escape character in XAML, which turned into a [VS bug here](https://developercommunity.visualstudio.com/content/problem/742146/markupextension-is-not-properly-closed-error-in-uw.html). 😒

[Finally though, I made my new `BooleanToTextConverter` work!](https://gist.github.com/michael-hawker/6d49e014015a8e122670437bd5c20fc1) But only when using `Binding`; `x:Bind` seems to assume it should be looking for a static resource for `Converter` and throws an exception at run-time. 😒 

🦙 As for other samples, I have this [sample one](https://gist.github.com/michael-hawker/becf8c1b9f781a91eeebb747c2955233) and we had added some in the [toolkit](https://github.com/windows-toolkit/WindowsCommunityToolkit/tree/master/Microsoft.Toolkit.Uwp.UI/Extensions/Markup) as well.

FYI @LyalinDotCom @jevansaks

**Comment by XamlFlair** [comment]
@michael-hawker  As of now the support for MarkupExtension wouldn't work with the OnDevice markup extension of the WCT, simply for the fact that it doesn't specify the MarkupExtensionReturnType attribute. I would need to look into that further to see if can be optional.

**Comment by Massimo37** [comment]
@michael-hawker  I was unable to repro your x:Bind issue you mentioned, I copied your converter and tried it with an x:Bind and it worked without error. 🤨

**Comment by michael-hawker** [comment]
@massimo37 strange, I'm on 18362 and get this error at runtime:
```
System.Runtime.InteropServices.COMException: Unspecified error

Error: Resource Dictionary Key can only be String-typed or Type-typed values.
   at System.Runtime.InteropServices.WindowsRuntime.IMap`2.Lookup(K key)
   at System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.Lookup[K,V](IMap`2 _this, K key)
   at System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.Indexer_Get[K,V](K key)
   at MarkupExtensionTest.MainPage.MainPage_obj1_Bindings.LookupConverter(String key
```

**Comment by Massimo37** [comment]
@michael-hawker  Can you provide me with a sample project that produces this error?

**Comment by michael-hawker** [comment]
Just change the 2nd binding in my gist above to this:

```
<TextBlock Text="{x:Bind MyToggle.IsOn, Converter={local:BooleanToTextConverter TrueText=Hello\&#x2C; I\&#x27;m True!, FalseText='Not True!'}}"/>
```

**Comment by Massimo37** [comment]
Thanks, I'll report back once I have something 👍
