### ISSUE TITLE
[WASM] Some Uno APIs are spuriously reported as not implemented in class library projects

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#3905]
## How to reproduce it (as minimally and precisely as possible)

1. Create a new class library with latest Uno library template
2. Add the following:
```csharp
	partial class MyControl : Control
	{
		public void DoSomething()
		{
			this.Width = 26;
		}
	}
```
3. Make sure `netstandard2.0` is selected in top left dropdown

## Current behavior
![image](https://user-images.githubusercontent.com/8270914/91600361-d1c35780-e935-11ea-81fc-c7f2efda8e5e.png)

## Expected behavior
No warning

## Workaround

Ignore the warnings

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.4.3 and  16.8.0pr1)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Arlodotexe** [comment]
Looks like it's also happening on Droid

**Comment by jeromelaban** [comment]
@Arlodotexe it should not happen on Android. Do you have an example of property that's incorrectly reported ?

**Comment by Arlodotexe** [comment]
Seems I had mistaken another bug for this one, please disregard my previous comment.
