### ISSUE TITLE
Code indicates it should be removed

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#3908]
The following source code in the project file indicates it should be removed. The current minimum version of VS for building Uno is 16.3 [documented here](https://platform.uno/docs/articles/uno-development/debugging-uno-ui.html).

https://github.com/unoplatform/uno/blob/4a0915d1c2651b19b388f9f0e9d94ca6f04f4cdd/src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.csproj#L148-L153

For people looking at this file in the future I think we need to either:
 1. Remove the code
 2. Remove the comment

**Comment by jeromelaban** [comment]
We'll remove this code as part of moving to .NET 6
