### ISSUE TITLE
wasm ListView is very slow.

### ISSUE THREAD

**Issue by yowl** [unoplatform/uno#391]
## I'm submitting a Feature request 

Improve speed of ListView

## Current behavior
Take the UnoApp template and replace the attached files.  Run on the wasm head and click the button.  Its very slow to render.

## Expected behavior
I understand the interpreter is slow, but this looks like something else.

## Minimal reproduction of the problem with instructions
Replace the attached files in the Uno  template app

## Environment
Firefox
```
Nuget Package: 
Uno.Ui
Package Version(s): 
1.42.0
Affected platform(s):
- [ ] iOS
- [ ] Android
- [x ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x ] 2017 (version: 15.9.2


[UnoApp.Shared.zip](https://github.com/nventive/Uno/files/2617869/UnoApp.Shared.zip)

)
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by yowl** [comment]
[UnoApp.Shared.zip](https://github.com/nventive/Uno/files/2617878/UnoApp.Shared.zip)

**Comment by jeromelaban** [comment]
The performance of the list view has improved significantly since this issue, going further when combined with the Interpreter and AOT.
