### ISSUE TITLE
WinUI `TeachingTip`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3911]
## What would you like to be added:

WinUI `TeachingTip` control.

## Why is this needed:

WinUI parity.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by sigmarsson** [comment]
@MartinZikmund when is it gonna be available or is it already in any 3.7*dev* pkg ?

**Comment by MartinZikmund** [comment]
Unfortunately not yet. While the code is ported, it will require quite a few Uno-specific adjustments to properly show up. I'm hoping this can be finished for 3.8

**Comment by MartinZikmund** [comment]
This control is highly dependent on `Popup`, so it is quite tricky to get it working currently, until we rewrite popups significantly

**Comment by sigmarsson** [comment]
@MartinZikmund , okay it isn't very essential control, so we can either substitute or wait if you could estimate a version number please.

**Comment by MartinZikmund** [comment]
Quite hard to say... 3.9 is unlikely, possibly 3.10, but probably will take a while to make it work just right on all platforms

**Comment by DierkDroth** [comment]
@MartinZikmund appears latest UNO compiles TeachingTip fine with .NET 6 + WindowsAppSdk. Does this means it's supported now?

If not, shouldn't I get a warning (there is none)?

**Comment by FrozDark** [comment]
Is it ready to be implemented?

**Comment by DierkDroth** [comment]
@MartinZikmund thanks. I actually replaced the TeachingTip as while back by some custom code. Nevertheless, it's definitely great to have it supported.

> Popup placement support.

This rang a bell: I'm desperately waiting to get support for [the shadow effect on Flyouts](https://github.com/unoplatform/uno/pull/6362)s, since they look plain and horrible on WASM. Is there any chance now with the above mentioned 'popup' support.

**Comment by MartinZikmund** [comment]
> @MartinZikmund thanks. I actually replaced the TeachingTip as while back by some custom code. Nevertheless, it's definitely great to have it supported.
> 
> > Popup placement support.
> 
> This rang a bell: I'm desperately waiting to get support for [the shadow effect on Flyouts](https://github.com/unoplatform/uno/pull/6362), since they look plain and horrible on WASM. Is there any chance now with the above mentioned 'popup' support.
> 

Shadows are a bit tricky, as they interfere with clipping on some targets. Hence to add elevation to popups, we will probably need to wrap them in elevated view. But it is definitely something we want to take care of soon. Will create an issue specifically for this

**Comment by DierkDroth** [comment]
Thanks @MartinZikmund

I saw that you guys made [progress on ElevatedView](https://github.com/unoplatform/uno/pull/11121). Would it make sense if I tried that to get same shadow effect for my Flyouts on WASM?

**Comment by BertrandDeSaintBezier** [comment]
Any news on how the implementation is progressing ? :D

**Comment by ACheekyBeluga** [comment]
😮 how soon can we expect this to be released ?
