### ISSUE TITLE
Memory leak in iOS when using x:Bind from View to View Model

### ISSUE THREAD

**Issue by rc65** [unoplatform/uno#3914]
## Current behaviour

When navigating between screens in an Uno iOS app the garbage collector is unable to dispose of references to previous views and their view models. This results in the memory footprint of the application increasing linearly as a user navigates between views. Ultimately this results in the app being killed by iOS to prevent it from degrading the device's performance.

Below are some images of the Xamarin Profiler's output comparing the app when using a binding and when the binding is removed. I have included images as there seems to be a bug preventing the Xamarin Profiler from saving session files. 🤦‍♂️ 

You can see that the app is able to reclaim memory over time when the binding is not used, whereas it cannot seem to do so when the binding is used. You can also see that the allocations don't seem to be collected as live count is equal to the total count when usually there should only be one live allocation.

| App using binding (has memory leak) | App not using binding (no memory leak) |
| ----------- | ----------- |
|<img width="1904" alt="MemoryLeakSnapshotsScreenshot" src="https://user-images.githubusercontent.com/9903380/91711942-b72fef00-eb7e-11ea-8796-689c59322ac6.png">|<img width="1904" alt="NoMemoryLeakSnapshotsScreenshot" src="https://user-images.githubusercontent.com/9903380/91711972-c4e57480-eb7e-11ea-9055-5969ed8282b6.png">|
|<img width="1904" alt="MemoryLeakAllocationsScreenshot" src="https://user-images.githubusercontent.com/9903380/91712001-d2026380-eb7e-11ea-83ae-5a97e64144a1.png">|<img width="1904" alt="NoMemoryLeakAllocationsScreenshot" src="https://user-images.githubusercontent.com/9903380/91712029-dcbcf880-eb7e-11ea-9326-e39688cb6305.png">|

## Expected behavior

The references to previous views should be garbage collected once the screen has been navigated away from which should prevent the application from being forcefully killed by iOS.

## How to reproduce it (as minimally and precisely as possible)

Minimal reproducible example: https://github.com/rc65/UnoMemoryLeakExample

Run these steps while using the [Xamarin Profiler](https://docs.microsoft.com/en-us/xamarin/tools/profiler/?tabs=macos) to watch the memory footprint increase linearly as you continue to navigate between the pages.

1. Run the application on an iOS device from Visual Studio for Mac.
2. Click the button on the main page of the app to navigate to the secondary page.
3. Click the button on the secondary page to navigate to the main page.
4. Repeat steps 2 and 3 ad nauseum (around 20-30 times will increase memory usage to ~30MB).
5. Stop repeatedly navigating and do nothing for however long you would like.
6. Take snapshots every 30 seconds or so in the Xamarin Profiler tool and see that the memory footprint remains roughly the same forever.

It's the `TextBlock` binding to the view model in the `SecondaryPage.xaml` that causes the view and view model to never be garbage collected. You can see the binding code [here](https://github.com/rc65/UnoMemoryLeakExample/blob/3b499b41bba4a73d96adb182742830dd8b0bf1e0/UnoMemoryLeakExample/UnoMemoryLeakExample.Shared/SecondaryPage.xaml#L21-L24).

You can remove the binding and set it to something like

```xaml
<TextBlock
    HorizontalAlignment="Center"
    FontSize="50"
    Text="This is not bound to the view model." />
```

and then rerun the `Steps to Reproduce` listed above and you will see that the memory leak no longer occurs.

## Workaround

We have been unable to find one so far. Things tried include:

1. Setting the view model attribute to `null` in the page's `OnNavigatedFrom` function.
1. Called `this.ClearBindings()` and `this.SuspendBindings()` in the page's `OnNavigatedFrom` function.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): Uno.UI 3.0.12 (also 3.1.0-dev.144 (latest pre-release))

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [x] Visual Studio for Mac (version: 8.7.4 (build 38))
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by francoistanguay** [comment]
Thanks for the good catch and the amazing issue details, team will look into it asap.
