### ISSUE TITLE
Dead Links in the Building and Debugging Uno.UI Page

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#3918]
## On which page?

https://platform.uno/docs/articles/uno-development/debugging-uno-ui.html

## What's wrong?

There are some dead links:

https://platform.uno/src/Uno.CrossTargetting.props
https://platform.uno/src/crosstargeting_override.props.sample
https://platform.uno/src/Directory.Build.targets
https://platform.uno/build/Uno.UI.nuspec

## Any feedback?

For the first 3 links, couldn't these just be switched to the github repo?

**Comment by robloo** [comment]
If someone from the team gives direction on how the links should be fixed I would be happy to put in a PR. It looks like the website had a copy of the source code and build files in directories that have been moved.

**Comment by agneszitte-nventive** [comment]
@robloo the full url is needed for the link to work both on the platform.uno website and also the github documentation.
We are making the changes directly in the github repo in the related markdown files and after the new changes are merged the changes will be pushed later on into the website.
You can check my current PR as an example for the next time you will need to fix dead links in the documentation:
https://github.com/unoplatform/uno/pull/3920

**Note:** I'm currently checking what we should have in the doc details for https://platform.uno/build/Uno.UI.nuspec as there is no more Uno.UI.nuspec file currently. I will update my PR with the proper change for it after that.

**Comment by robloo** [comment]
Ok, I see now that the links assumed the page accessed from the github repo. As soon as it is hosted on another side it breaks down. What confused me is actually clicking the link resolved to "platform.uno" so I assumed the code was also hosted on the website or something.
