### ISSUE TITLE
Can't add value converter in Cross-Platform Library

### ISSUE THREAD

**Issue by stefanolson** [unoplatform/uno#3925]
## Current behavior

Error CS0234: The type or namespace name 'Data' does not exist in the namespace 'Windows.UI.Xaml' (are you missing an assembly reference?)

When using an IValueConverter in a Cross-Platform Library

## Expected behavior

Should build fine.

## How to reproduce it (as minimally and precisely as possible)

Create a new uno project. Within the project create a new 'Cross-Platform Library'.  In the class library class, insert the following code:
`using System;
using Windows.UI.Xaml.Data;

namespace ClassLibrary
{
    public class Class1:IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, string language)
        {
            throw new NotImplementedException();
        }

        public object ConvertBack(object value, Type targetType, object parameter, string language)
        {
            throw new NotImplementedException();
        }
    }
}
`
Can provide sample if needed.

## Workaround

None known

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.7.2 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [X] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

Can you build the library using `msbuild /r /bl` and post the binlog file ?

**Comment by stefanolson** [comment]
Sure. Enclosed.
[msbuild.zip](https://github.com/unoplatform/uno/files/5158349/msbuild.zip)



Thanks.

**Comment by jeromelaban** [comment]
Thanks. This looks like a missing UWP SDK installation. Can you try using `uap10.0.17763` or any other version that is installed on your machine ?

**Comment by stefanolson** [comment]
Yes, looks like you are right.  Weirdly, In the issue I raised yesterday, there was a little yellow error symbol beside UAP 10.0.16299. Not so with the class library:
![image](https://user-images.githubusercontent.com/1751192/91965138-2e72a800-ed64-11ea-8589-1229df08ab7a.png)

Anyway, think this can be closed now?

**Comment by jeromelaban** [comment]
Cross-targeted libraries are not well supported by VS for UWP, but this will change with .NET 5. Thanks for the troubleshooting.
