### ISSUE TITLE
[iOS] TimePicker and TimePickerFlyout are not Launching when navigating back to the page

### ISSUE THREAD

**Issue by abrull** [unoplatform/uno#3930]
## Current behavior

When using TimePicker or TimePickerFlyout if you navigate away from the page **before** the TimePicker was launched and then navigate back to the page then it’s impossible to launch the TimePicker or TimePickerFlyout again. This is what I get in the output [TimePickerErrorLog.txt](https://github.com/unoplatform/uno/files/5159078/TimePickerErrorLog.txt)

## Expected behavior

When navigating back to the page it should be possible to launch the TimePicker

## How to reproduce it (as minimally and precisely as possible)

https://github.com/abrull/TimePickerFlyoutTest

## Environment

Nuget Package:
- [ ] Uno.UI 

Nuget Package Version(s):
3.0.12
Affected platform(s):

- [ x] iOS

IDE:

- [ ] Visual Studio 2017 (version: )
- [ x] Visual Studio 2019 (version:16.7.1 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by abrull** [comment]
@jeromelaban will this be pushed into Uno.ui 3.1 or being a hotfix be added to previous versions?

**Comment by jeromelaban** [comment]
It will be backported to 3.0, we'll batch it with other changes soon.
