### ISSUE TITLE
[Android] InvokedItem/InvokedItemContainer of NavigationView always seems to be null, preventing navigation using a passed parameter

### ISSUE THREAD

**Issue by surya-sk** [unoplatform/uno#3934]
## Current behavior
When using a NavigationView with an ItemInvoked(NavigationView sender, NavigationViewItemInvokedEventArgs args) event handler, args.InvokedItem/InvokedItemContainer always seem to be null, so selected a NavigationViewItem results in doing nothing. I can report the same behavior for SelectionChanged as well. 

## Expected behavior
When a NavigationViewItem is invoked, args.InvokedItem should be the item, which makes retrieving its properties (such as Tag) possible.  

## How to reproduce it (as minimally and precisely as possible)
Repro report: Create a NavigationView  and bind it to a source with MenuItemsTemplate , an ItemInvoked event handler and in the event handler, try and access the invoked NavigationViewItem

Steps:
-Create a NavigationView.
-Set MenuItemsSource to a data model.
-Create a MenuItemTemplate and assign a value from the ItemsSource to the Tag property
-Create a ItemInvoked event handler
-Try to access the invoked NavigationViewItem (ex: string Item = args.InvokedItemContainer.Tag.ToString())
-Send the retrieved value to another page and show it there (ex: Frame.Navigate(typeof(Page2), Item))
-Build and run the app on the Android emulator

## Workaround
Haven't figured one out that still uses the NavigationView

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.7.1)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Xiaoy312** [comment]
Related SO issue: https://stackoverflow.com/questions/63699773/unable-to-get-invokeditemcontainer-working-with-android
\---
Tried to repro the issue with:
```
<NavigationView ...
				ItemInvoked="NavView_ItemInvoked" 
				MenuItemsSource="{x:Bind games}">
	<NavigationView.MenuItemTemplate>
		<DataTemplate x:DataType="data:Game">
			<NavigationViewItem Tag="{x:Bind id, Mode=TwoWay}" Content="{x:Bind GameName}" Icon="Play"/>
```

It seems that `NavigationViewItemInvokedEventArgs.InvokedItemContainer` will be null when using `NavigationViewItem` as the data-template. If we replace this with a `TextBlock`, `InvokedItemContainer` will be an instance of `NavigationViewItem`. However, `InvokedItem` was never observed to be null; it is always an instance of `Game` (or the item type of `x:Bind games`).

Here are the version that I tested on:
- Uno.UI \@ 3.0.12
- Uno.UI \@ 2.4.4
- Uno.UI \@ 2.4.9

Sample: [NavViewInvokedItemContainer.zip](https://github.com/unoplatform/uno/files/5293559/NavViewInvokedItemContainer.zip)

**Comment by MartinZikmund** [comment]
@surya-sk Can you confirm this now works with the new WinUI `NavigationView` please?

**Comment by surya-sk** [comment]
Yep, created a new project and the WinUI NavigationView seems to register the events. Glad to see WinUI controls in Uno!

**Comment by MartinZikmund** [comment]
@jeromelaban do we want to fix this issue for WUX `NavigationView` or can it be closed, as this scenario works with MUX `NavigationView`?

**Comment by jeromelaban** [comment]
I don't think there's a need for it, MUX is the way to go now. Let's close it.
