### ISSUE TITLE
Add documentation for the creation of cross-targeted libraries

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#3938]
The creation of cross-targeted libraries is not documented, and there are a few known issues around its use:

- Add references [may fail](https://github.com/unoplatform/uno/issues/3909)
- [There is no detection of the installed UWP SDK](https://github.com/unoplatform/uno/issues/3925), and the version used by the project must match an installed version
- Conditionals are [not handled properly by the UI](https://github.com/unoplatform/uno/issues/3932)
- There is no [UI for adding references to assemblies](https://github.com/unoplatform/uno/issues/3938) that are not part of the default set of xamarin assemblies .
- Document [how to use the Add Item](https://github.com/unoplatform/uno/issues/3969) menu in VS
- UWP head min version [must match the library's target framework version](https://github.com/unoplatform/uno/issues/4018).

**Comment by davidjohnoliver** [comment]
see also https://github.com/unoplatform/uno/issues/3923 ;)

**Comment by ramtinak** [comment]
Can you please share a open source library that made it via uno?

**Comment by jeromelaban** [comment]
@ramtinak what are you looking for as an example for library ? Any particular feature or configuration ?

**Comment by ramtinak** [comment]
@jeromelaban anything! I just want to learn how it works.  And how can I do it.

**Comment by jeromelaban** [comment]
Here's a basic control library: https://github.com/unoplatform/Uno.Samples/tree/master/UI/ControlLibrary
