### ISSUE TITLE
How can I reference System.Xml.Linq in a 'Cross-Platform Library'

### ISSUE THREAD

**Issue by stefanolson** [unoplatform/uno#3941]
## Current behavior

Trying to use XElement in a cross-platform library won't build the xamarin/mono targets.

Get an error:
error CS1069: The type name 'XElement' could not be found in the namespace 'System.Xml.Linq'. This type has been forwarded to assembly 'System.Xml.Linq, Version=2.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' Consider adding a reference to that assembly.

## Expected behavior

Should build.

## How to reproduce it (as minimally and precisely as possible)

Create a new uno project. Within the project create a new 'Cross-Platform Library'. In the class library class, insert the following code:
'using System.Xml.Linq;

namespace ClassLibrary
{
    public class Class1
    {
        public void Func()
        {
            XElement xElement = new XElement("test");
        }
    }
}'

Then build. XElement is part of .net standard, so I'd expect it to build. The UWP and .netstandard targets seem ok (Although resharper didn't seem to like XElement in UWP until it added Microsoft.NETCore.UniversalWindowsPlatform (6.2.9) to the packages under UAP 10.0.18362. I now have no idea how to remove that).

The error suggest that you should add an assembly to the xamarin/mono targets, but I can't find a way to do that, the only options are add project reference or shared project reference. 

I attempted to add System.Xml.Linq as a nuget package, but that appeared under .net standard and UWP, but not mono/xamarin targets.

So not sure if this is a bug or just something that should be added to the documentation. I'm not entirely clear on what the right procedure is.

## Workaround

None currently

## Environment

Nuget Package:
- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.7.2 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [X] Resharper (version: 2020.2 )

## Anything else we need to know?

May need to be added to the list in here if there is a workaround: https://github.com/unoplatform/uno/issues/3938

**Comment by jeromelaban** [comment]
Thanks for the report. There's indeed no UI support to add references to cross-targeted libraries, particularly the ones for iOS/Android/macOS. 

In order to add the reference, you'll need to add the following: 

```xml
<ItemGroup Condition="'$(TargetFramework)'=='xamarinmac20' or '$(TargetFramework)'=='xamarinios10' or '$(TargetFramework)'=='monoandroid10.0'">
   <Reference Include="System.Xml.Linq" />
</ItemGroup>
```

You can find out the list of available assemblies by opening the `Add Reference` dialog on the iOS/Android/macOS heads.

Once again, this scenario will improve significantly once Xamarin migrates over .NET 5.
