### ISSUE TITLE
Add support for the MUX NavigationView control

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#3942]
## Current behavior

For the WinUI 2.x compatible API set of Uno, the `NavigationView` is only available in WUX, and not MUX. This creates incompatibilities in code for users depending on the MUX version of this control.

## Expected behavior

Using both MUX and WUX navigation view should work.

## Workaround

Use `#if HAS_UNO` conditionals to use the WUX version with Uno, and the MUX version with UWP.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by robloo** [comment]
I'm curious, is the existing WUX NavigationView a port of the windows-ui-xaml codebase? Or is a new port needed to get the latest NavigationView features working.

**Comment by jeromelaban** [comment]
The current implementation is a port of the WUX version, so it's mostly a matter of compiling those classes twice, probably with a bit of regex replace during the build.

**Comment by robloo** [comment]
> The current implementation is a port of the WUX version
You mean "MUX" here I'm assuming?

Should we just copy the code for now? It seems the Microsoft.UI.Xaml version should be the master and code moved to that directory if code is already ported from the windows-ui-xaml. Then when the big cleanup for WinUI 3.0 finally happens in a year or so the duplicate code will just get deleted and the Microsoft.UI.Xaml version is the only one remaining.

**Comment by robloo** [comment]
I'm going to run into the same situation but reversed for the ColorPicker. I had a thought: I havn't tried in C# but perhaps we can just create the new classes in the other namespace and then just derive them from the actually implemented classes in the other namespace. This would be fastest I think, also node code duplication or generation required.

**Comment by jeromelaban** [comment]
Support added in Uno 3.4.
