### ISSUE TITLE
Default font does not look right on systems without Segoe UI

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3954]
## Current behavior

When WASM Uno app is loaded in Tesla browser, the default font is generic Times New Roman.

![ds](https://user-images.githubusercontent.com/1075116/92138294-7c43ea80-ee0e-11ea-968d-350ae58b5372.png)

## Expected behavior

A nicer font should be rendered (OpenSans?)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Prerequisites:
- https://github.com/unoplatform/uno/issues/2502
- Single font name for multiple font files
- https://github.com/unoplatform/uno/issues/4864
- https://github.com/unoplatform/uno/issues/693
- Package font in one file ?

**Comment by MartinZikmund** [comment]
Seems this is a general issue on systems without Segoe UI (e.g. macOS)
![image](https://user-images.githubusercontent.com/1075116/106296526-17bc7880-6252-11eb-9c08-52c919d6902d.png)

**Comment by MartinZikmund** [comment]
This could be implemented along with #3588

**Comment by fangeles02** [comment]
Hi, I've found a free font similar to Segoe UI from other forums, if you could consider it.
WeblySleek UI [http://fontpro.com/weblysleek-ui-font-9838](url)

![image](https://user-images.githubusercontent.com/26376969/129006168-c58a0046-38b2-4f10-a1c9-8466b2b943f8.png)

**Comment by MartinZikmund** [comment]
Same problem occurs on other OS/browsers - e.g. Safari on iOS

**Comment by nor0x** [comment]
any solution - setting a global font via css unfortunately doesn't solve this issue

**Comment by MartinZikmund** [comment]
Yes, this is something we need to address asap... I will be working on the icon font and will try to look into this as well. Microsoft is suggesting https://docs.microsoft.com/en-us/typography/font-list/selawik as the open-source alternative to Segoe UI, so that could be a potentially viable solution

**Comment by MartinZikmund** [comment]
Thisis also a problem for mobile browsers - for example `{ThemeResource TitleTextBlockStyle}` renders very bold typeface on Android as compared to desktop browser

**Comment by mikernet** [comment]
I like the "system native" font selection fallbacks for one of the apps I'm working on, but something odd happens on macos+chrome where font-weight is completely ignored, which doesn't seem to happen with any other combination of browsers/platforms/targets as far as I can tell.

When I check chrome dev tools and select an element, it says `font-family: "Segoe UI"` and shows that it is actually rendering Helvetica Neue, but font-weight does not do anything. If I change `font-family` directly to Helvetica Neue then the text bolds just fine.

**Comment by mikernet** [comment]
I also noticed that if it falls back to `sans-serif` (i.e. if you remove the `Helvetica Neue` fallback) then it renders times new roman, which might be related to the initial problem. If I change font-family to `sans-serif` in chrome dev tools then it shows a suitable font.
