### ISSUE TITLE
`NavigationView` no longer applies font color to hamburger menu

### ISSUE THREAD

**Issue by jtnumberfive** [unoplatform/uno#3957]
The code below was working correctly until 3.0 dev release 405(I did not check all of the releases- so it may have been broken earlier).  The hamburger menu icon no longer applies the color as defined below.  The color is correctly applied ]to the settings icon and any other item added the nav view.  The hamburger icon just stays black in light mode and white in dark mode.  The issue applies to both the IOS and the Android versions of my app(Note- I am not using the UWP Version).  To reproduce the issue- this is the code I have. 
Create a Navigation View like this:

```
 <NavigationView x:Name="NavView"
                      Loaded="NavView_Loaded"
                      ItemInvoked="NavView_ItemInvoked"
                      PaneDisplayMode="LeftCompact" IsPaneOpen="False"
                      IsBackButtonVisible="Collapsed"
                      BackRequested="NavView_BackRequested"
                      Foreground="{StaticResource NavigationViewItemForeground}"
                      Background="{StaticResource NavigationViewDefaultPaneBackground}"
                     Grid.Row="1"   CompactPaneLength="60" >
</NavigationView>
```

Create a Resource Dictionary like so:

```
<ResourceDictionary.ThemeDictionaries>
 <ResourceDictionary x:Key="Dark">
            <SolidColorBrush x:Key="NavigationViewItemForeground" Color="Green"/>
            <SolidColorBrush x:Key="NavigationViewItemForegroundSelected" Color="Green"/>
            <SolidColorBrush x:Key="NavigationViewItemForegroundSelectedPointerOver" Color="Green"/>
            <SolidColorBrush x:Key="NavigationViewItemForegroundPressed" Color="Green"/>
            <SolidColorBrush x:Key="NavigationViewItemForegroundSelectedPressed" Color="Green"/>
            <SolidColorBrush x:Key="NavigationViewSelectionIndicatorForeground"  Color="DarkOrange" />
        </ResourceDictionary>
        <ResourceDictionary x:Key="Light">
            <SolidColorBrush x:Key="NavigationViewDefaultPaneBackground" Color="#FFF2F2F2"/>
            <SolidColorBrush x:Key="NavigationViewItemForeground" Color="Green"/>
            <SolidColorBrush x:Key="NavigationViewItemForegroundSelected" Color="Green"/>
            <SolidColorBrush x:Key="NavigationViewItemForegroundSelectedPointerOver" Color="Green"/>
            <SolidColorBrush x:Key="NavigationViewItemForegroundPressed" Color="Green"/>
            <SolidColorBrush x:Key="NavigationViewItemForegroundSelectedPressed" Color="Green"/>
            <SolidColorBrush x:Key="NavigationViewSelectionIndicatorForeground"  Color="DarkOrange" />
          </ResourceDictionary>
    </ResourceDictionary.ThemeDictionaries>
```

**Comment by MartinZikmund** [comment]
@davidjohnoliver I have tested this and it seems to be a resources-related issue. While the resource names match the `{ThemeResource}` bindings in `NavigationView` and `PaneToggleButtonStyle` , they are resolved using the built-in resources, not using the overrides on the Page.

**Comment by Xiaoy312** [comment]
You should be able to modify this through the [`NavigationView.PaneToggleButtonStyle` property](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview.panetogglebuttonstyle?view=winrt-22000):
```xml
<NavigationView.PaneToggleButtonStyle>
    <Style BasedOn="{StaticResource PaneToggleButtonStyle}" TargetType="Button">
        <Setter Property="Foreground" Value="Red" />
    </Style>
</NavigationView.PaneToggleButtonStyle>
```
note that this button also have mouse-over/pressed states that change the foreground as well, so you would need to override the template as well.
It is recommended to pass to muxc::NavigationView now, and the same solution above work as well.
For the muxc version of said control template, it can be found here: 
https://github.com/microsoft/microsoft-ui-xaml/blob/7ec5fb5b8c85ebe04d8498ee89f26d1b5259d948/dev/NavigationView/NavigationView_rs1_themeresources.xaml#L331-L404
