### ISSUE TITLE
Issues creating custom controls

### ISSUE THREAD

**Issue by stefanolson** [unoplatform/uno#3962]
## Current behavior

You receive a message "Fail to run wizard". See below for picture:
![image](https://user-images.githubusercontent.com/1751192/92212099-8d135f80-eee5-11ea-8f73-1124b6f11c5b.png)

Also, when building the android version, you receive the following error:
CustomControl1.cs(16,25,16,39): error CS0260: Missing partial modifier on declaration of type 'CustomControl1'; another partial declaration of this type exists

Now this point I haven't created the themes folder, so I don't know if that's an issue.  But it also happens when using the control in a cross-platform library (my real issue)

## Expected behavior

Creates themes folder (doesn't actually exist) and xaml file and a generic.xaml if needed and should build under android.

## How to reproduce it (as minimally and precisely as possible)

Create a new uno project.  Right click on the Shared library, add, new item,  Choose templated control, default name of CustomControl1.cs.  Click add. Receive error.

Build, receive the other error.

## Workaround

Manually create the themes folder and file for the first issue. Not sure about the second.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.7.2 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [X] Resharper (version: 2020.2 )

**Comment by jeromelaban** [comment]
At this point, the only item template that is compatible without modifications with Uno is the `Page` template. It's available in the "Uno Platform" section when the Uno Platform VSIX is installed. The others are either Windows specific, or WPF specific.

The partial error is also expected at this point, all controls built with Uno must have the partial qualifier for the source generator to work properly.

We'll add those specifics to the documentation.
