### ISSUE TITLE
Should HAS_UNO apply to WASM & Skia?

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3971]
## Current behavior

Code within `#if HAS_UNO` in `Uno.UI.RuntimeTests.Skia` is not compiled when building `netstandard2.0` target.

## Expected behavior

Possibly should be included

## How to reproduce it (as minimally and precisely as possible)

Us `#if HAS_UNO` in `Uno.UI.RuntimeTests.Skia`

## Workaround

Use `#if HAS_UNO || __SKIA__ || __WASM__`

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
HAS_UNO is not defined inside of Uno, be could probably add it in [CrossTargeting.props](https://github.com/unoplatform/uno/blob/master/src/Uno.CrossTargetting.props) for non-uap targets.
