### ISSUE TITLE
Possible wrong namespace urls in doc

### ISSUE THREAD

**Issue by birbilis** [unoplatform/uno#3972]
At https://github.com/unoplatform/uno/blob/master/doc/articles/platform-specific-xaml.md/#L1
in the documentation (for "Platform-specific XAML markup in Uno" doc page), several namespace urls start with http:/uno (with a single slash). Is this a typo or on purpose?

**Comment by davidjohnoliver** [comment]
It's a typo that should be fixed, thanks for pointing it out!

Note that in current versions of Uno, those misformed urls or _any_ namespace urls will still work - as that doc states:

> For prefixes which will be excluded on Windows (e.g. android, ios), the actual namespace is arbitrary, since the Uno parser ignores it.

Ie, the actual name of the prefix (`wasm`, `android` etc) is what Uno's parser cares about, not the url.

**Comment by davidjohnoliver** [comment]
Fixed by https://github.com/unoplatform/uno/pull/4559
