### ISSUE TITLE
ComboBox SelectedValuePath not binding

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#3995]
## Current behavior

The ComboBox binding to Items through the properties ```SelectedValuePath``` ```DisplayMemberPath```

## Expected behavior
The Items should be displayed in the combo box, the selected item showing the text  bound to the ```DisplayMemberValuePath``` and should select the item in the ```SelectedValuePath``` property

## Repro

```xaml
     <ComboBox  ItemsSource="{x:Bind SomeOptions}"
                           SelectedValue="{x:Bind SomeOption, Mode=OneWay}"
                           SelectedValuePath="Option"
                           DisplayMemberPath="Text" />
```

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly

**Comment by carldebilly** [comment]
The fix has been merged in Uno.UI v3.1.0-dev.375
