### ISSUE TITLE
[iOS] AppBarButton placed inside a native Command doesnt receive Click event.

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#3997]
## Current behavior

On iOS, the `AppBarButton` in a native `CommandBar` (via `NativeCommandBarPresenter`) is not working. Its `AppBarButton::Click` event is not fired when clicked. This same works nicely on uwp, android or wasm.

## How to reproduce it (as minimally and precisely as possible)
SampleApp: Launch app > CommandBar > Native > try to press any button
[IosAppBarButtonHandler.zip](https://github.com/unoplatform/uno/files/5191388/IosAppBarButtonHandler.zip): Launch app > try to press any button.

## Workaround
n/a

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.4.5)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
Seems to be working in latest Uno. Also now works for the Toolkit `NavigationBar`

CommandBar:
![commandBarClick](https://user-images.githubusercontent.com/4793020/152186438-35f27026-c39e-4b96-9590-1ec38a21f136.gif)

NavigationBar
![navbarClick](https://user-images.githubusercontent.com/4793020/152186465-094ff76e-fc18-4d42-88e5-13be2cd5bfe3.gif)


NavigationBar's black foreground for the button is another issue
