### ISSUE TITLE
[Android] FileOpenPicker

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4016]
## What would you like to be added:

Support for `FileOpenPicker`.

## Why is this needed:

UWP parity

## For which Platform:

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by pkar70** [comment]
See #2896.

**Comment by MartinZikmund** [comment]
@pkar70 Yes, I am aware of the PR, I will address the comments, add tests and finalize it 👍

**Comment by pkar70** [comment]
Could you make changes in "my" PR, or only add comments to it?

**Comment by MartinZikmund** [comment]
Unfortunately can't add commits there (don't have permissions 🤔). I will base the PR on your branch and add commits though.

**Comment by MartinZikmund** [comment]
@pkar70 Oh! I take that back, seems I have permission now! Good, no need for new PR then 😀 !
