### ISSUE TITLE
Can't seem to reference a custom control in a cross-platform library from a shared project 

### ISSUE THREAD

**Issue by stefanolson** [unoplatform/uno#4018]
## Current behavior

Application will not build with the following error:
3>------- Started building project: UnoTester.UWP
3>C:\temp\uno\UnoTester\UnoTester\UnoTester.Shared\MainPage.xaml(11,10): Error WMC0003 XamlCompiler: A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null.

When referencing a control in a cross-platform library from xaml.

## Expected behavior

Application should build.

## How to reproduce it (as minimally and precisely as possible)

Create a new uno project. Within the project create a new 'Cross-Platform Library'. On the class library in the Solution Explorer, right click on the Shared library, add, new item, Choose templated control, default name 
of CustomControl1.cs. Click add. Receive error (that's ok, ignore it).

In mainpage.xaml add a reference to the control:
<shared:CustomControl1/>

Build UWP, receive the above error. (Droid/Wasm build fine)

Project to repeat with enclosed.

## Workaround

Now known.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
[UnoTester.zip](https://github.com/unoplatform/uno/files/5198607/UnoTester.zip)
- [X] Visual Studio 2019 (version: 2019.7.2 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [X] Resharper (version: 2020.2)

**Comment by jeromelaban** [comment]
Thanks for the report. Does this solution work on your end ? https://github.com/unoplatform/Uno.Samples/tree/master/UI/ControlLibrary

It's demonstrating this specific scenario.

**Comment by stefanolson** [comment]
I downloaded the zip file from Uno.Samples.  

But when I try and build it can't build it, get the following errors (Uno.Ui is 2.3.0-dev.80):
1>C:\temp\Uno.Samples-master\UI\ControlLibrary\XamlControlLibrary\MyTemplatedControl.cs(7,47,7,54): error CS0246: The type or namespace name 'Control' could not be found (are you missing a using directive or an assembly reference?)
1>C:\temp\Uno.Samples-master\UI\ControlLibrary\XamlControlLibrary\MyTemplatedControl.cs(32,36,32,70): error CS0246: The type or namespace name 'DependencyPropertyChangedEventArgs' could not be found (are you missing a using directive or an assembly reference?)
1>C:\temp\Uno.Samples-master\UI\ControlLibrary\XamlControlLibrary\MyTemplatedControl.cs(21,26,21,44): error CS0246: The type or namespace name 'DependencyProperty' could not be found (are you missing a using directive or an assembly reference?)

**Comment by jeromelaban** [comment]
This looks like a nuget restore error. What does an explicit nuget restore on the solution tell you ?

**Comment by stefanolson** [comment]
They seemed to be all references to older versions of both UNO and UWP. So I've manually updated them all and then done to restore and still got the same problem.

**Comment by stefanolson** [comment]
Seeing this warning:
0>C:\Program Files\dotnet\sdk\3.1.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(257,5): Warning NETSDK1023: A PackageReference for 'Microsoft.NETCore.UniversalWindowsPlatform' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs

**Comment by jeromelaban** [comment]
Thanks for the troubleshooting. Could you attach the solution you've created from your steps ? Thanks.

**Comment by stefanolson** [comment]
Attaching original one (Which I thought I had attached with the initial report but may not have been)
[UnoTester.zip](https://github.com/unoplatform/uno/files/5198732/UnoTester.zip)

**Comment by jeromelaban** [comment]
Thank you. 

This is cause by a issue of library development when using cross-targeted libraries and UWP, where the version defined in the library (uap10.0.18362 in your sample), does not match the min version set in the UWP project (10.0.17736). This causes the project system to use the netstandard 2.0 Uno.UI binaries, and confuses the UWP toolchain.

To fix the issue, make sure to align the min version of the UWP head with the target framework used in the library.

We'll add this specificity to the upcoming documentation.

**Comment by stefanolson** [comment]
Thanks!  Sorry about the number of issues I'm finding!  Every time I feel it's nearly working I seem to find another problem...

**Comment by jeromelaban** [comment]
Thanks keeping up, that's very valuable for the community. Let us know if there's anything else suspicious!
