### ISSUE TITLE
[WASM] FileOpenPicker

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4028]
## What would you like to be added:

Support for `FileOpenPicker` on WASM

- Native - #5323
- Upload-based - [TBD]

## Why is this needed:

UWP parity

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

Part of #508

**Comment by michalss** [comment]
is there any progress on this ?

**Comment by MartinZikmund** [comment]
**Resources:**
- https://web.dev/file-system-access/

**Comment by MartinZikmund** [comment]
This will require two separate approaches:

1. Based on `<input type="file" />` performing an "upload" - this will match the current WASM implementation of `FileSavePicker` and will have wide support across all browsers\
2. Full-fledged filesystem access solution based on the new File System Access APIs in JS, which is not fully supported yet, but has huge potential
