### ISSUE TITLE
[macOS] ScollViewer cannot scroll horizontally

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#4033]
## Current behavior

When you set `HorizontalScrollMode` to `Enabled` and `HorizontalScrollBarVisibility` to `Visible`, we still can't scroll horizontally.
![actual result](https://user-images.githubusercontent.com/17461593/92943369-aefa6e00-f420-11ea-9723-866a928a0d48.jpg)

## Expected behavior

When you set `HorizontalScrollMode` to `Enabled` and `HorizontalScrollBarVisibility` to `Visible`, we should be able to see a scrollbar and be able to scroll horizontally.

## How to reproduce it (as minimally and precisely as possible)

- Add this into your sample
```xaml
<ScrollViewer  HorizontalScrollMode="Enabled"
			 HorizontalScrollBarVisibility="Visible">
		<StackPanel Spacing="10"
				    Orientation="Horizontal">
			<TextBlock Text="item" />
			<TextBlock Text="item" />
			<TextBlock Text="item" />
			<TextBlock Text="item" />
			<TextBlock Text="item" />
			<TextBlock Text="item" />
			<TextBlock Text="item" />
			<TextBlock Text="item" />
                        <TextBlock Text="item" />
			<TextBlock Text="item" />
			<TextBlock Text="item" />
			<TextBlock Text="item" />
	</StackPanel>
</ScrollViewer>
```
- Deploy on MacOS

## Workaround

N/A

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.0.0-dev.1533

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.6.2)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dr1rrb** [comment]
This has most probably been fixed by the refactor of the `ScrollViewer` for macOS

**Comment by dr1rrb** [comment]
This is now fixed
