### ISSUE TITLE
[WASM] `ScrollView` doesn't set its height correctly with `ItemsControl` inside

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#4034]
## Current behavior

As you can see, we don't see the items inside the itemscontrol fully. 
![wasm](https://user-images.githubusercontent.com/17461593/92958886-0278b600-f439-11ea-940b-28a38d6665b4.jpg)

## Expected behavior

![uwp](https://user-images.githubusercontent.com/17461593/92966532-b8e29800-f445-11ea-8faa-3169d449d616.jpg)

## How to reproduce it (as minimally and precisely as possible)

Download [ScrollViewerHeight.zip](https://github.com/unoplatform/uno/files/5210874/ScrollViewerHeight.zip)
Deploy on WASM

## Workaround

N/A

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.1.0-dev.288

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.6.2)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment]
![image](https://github.com/unoplatform/uno/assets/31348972/86b0d43b-c341-467f-8694-751de8bef007)

This is the behavior I'm seeing currently. @takla21 Can you confirm if there is still an issue here?

**Comment by Youssef1313** [comment]
@takla21 Can you please confirm if this issue is fixed? Thanks!
