### ISSUE TITLE
SkiaSharp.Views was restored using .NetFramework rather than .NetCore

### ISSUE THREAD

**Issue by MatthewrKurtz** [unoplatform/uno#4036]
Developing a Skia.Gtk project, I get the following warning for the SkiaSharp.Views (2.80.0) dependency of the Uno.Ui.Sia.Gtk nuget (3.1.0-dev.288) package

This may be causing UI elements like combo boxes to not display correctly (Instead of showing the chevron on the right hand side, it instead displays a gray rectangle).

Found this issue when transferring the tutorial project to a Raspberry Pi 3 B+ running raspbian (debian 10 arm).

Warning	NU1701	Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.	UnoTemplateApp.Skia.Gtk	

The following link may be of assistance:
[https://forums.xamarin.com/discussion/163411/why-cant-i-use-skiasharp-views-in-netstandard2-0-project](https://forums.xamarin.com/discussion/163411/why-cant-i-use-skiasharp-views-in-netstandard2-0-project)

**Comment by jeromelaban** [comment]
This issue is actually not the same as the Xamarin.Forms one, and really is a SkiaSharp issue. The missing piece here is that SkiaSharp does not have a netcoreapp3.x/net5 target, for which @mattleibow maybe be interested in.

In the meantime, the warning is not a problem at runtime and you can add `<NoWarn>$(NoWarn);NU1701</NoWarn>` in the first `PropertyGroup` of the Skia project head to suppress it.

**Comment by mattleibow** [comment]
@MatthewrKurtz  @jeromelaban  There is actually a netcoreapp target - but not in that package. I originally wanted to have one big package for all desktop, but this causes issues with requiring the app to reference all the WinForms, WPF, GTK 2 and GTK 3 :)

So, for the desktop platforms, there are a few separate packages:
 - https://www.nuget.org/packages/SkiaSharp.Views.WPF _(netcoreapp3.0 and net462)_
 - https://www.nuget.org/packages/SkiaSharp.Views.WindowsForms _(netcoreapp3.0 and net462)_
 - https://www.nuget.org/packages/SkiaSharp.Views.Gtk2 _(net462)_
 - https://www.nuget.org/packages/SkiaSharp.Views.Gtk3 _(netstandard2.0)_

**Comment by Youssef1313** [comment]
I see the dependency was removed in https://github.com/unoplatform/uno/pull/6102. Is there anything else to do?
