### ISSUE TITLE
Default alignment does not match UWP

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4038]
## Current behavior

The `Uno.UI.FeatureConfiguration.Control.UseLegacyContentAlignment` is set to `false` and based on the `DependencyPropertyMixins.tt` the default `HorizontalContentAlignment`, `VerticalContentAlignment` is set to `Center`.

```
.Class("Control")
   .Property("HorizontalContentAlignment", "HorizontalAlignment", 
      "(Uno.UI.FeatureConfiguration.Control.UseLegacyContentAlignment ? 
       HorizontalAlignment.Left : HorizontalAlignment.Center)")
   .Property("VerticalContentAlignment", "VerticalAlignment", 
      "(Uno.UI.FeatureConfiguration.Control.UseLegacyContentAlignment ? 
       VerticalAlignment.Top : VerticalAlignment.Center)")			
```

## Expected behavior

UWP's default `HorizontalContentAlignment` is `Left` ([docs](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.horizontalcontentalignment?view=winrt-19041)) and `VerticalContentAlignment` is `Top` ([docs](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.verticalcontentalignment?view=winrt-19041))

Seems like the "legacy" behavior is actually the correct behavior 🤔

## How to reproduce it (as minimally and precisely as possible)

N/A

## Workaround

Explicitly set the `HorizontalContentAlignment` and `VerticalContentAlignment`.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment]
@MartinZikmund I looked into this, and unless I'm missing something, the UWP docs are incorrect.

```csharp
        public static void Test()
        {
            foreach (Type type in
                Assembly.GetAssembly(typeof(Control)).GetTypes()
                .Where(myType => myType.IsClass && !myType.IsAbstract && myType.IsSubclassOf(typeof(Control))))
            {
                // NOTE: Nothing under this if condition was validated.
                if (
                    type == typeof(ButtonBase) // No available public constructor. TODO: Create a derived class and access the protected ctor to validate manually.
                    || type == typeof(Selector) // No ctor at all. Can get private/internal ctor with reflection and test with it??
                    || type == typeof(SelectorItem) // No available public constructor. TODO: Create a derived class and access the protected ctor to validate manually.
                    || type == typeof(DatePickerFlyoutPresenter) // No ctor at all. Can get private/internal ctor with reflection and test with it??
                    || type == typeof(ListViewBase) // No available public constructor. TODO: Create a derived class and access the protected ctor to validate manually.
                    || type == typeof(ListViewBaseHeaderItem)
                    || type == typeof(InkToolbarToolButton)
                    || type == typeof(InkToolbarPenButton)
                    || type == typeof(InkToolbarToggleButton)
                    || type == typeof(InkToolbarMenuButton)
                    || type == typeof(ListPickerFlyoutPresenter)
                    || type == typeof(MenuFlyoutItemBase)
                    || type == typeof(NavigationViewItemBase)
                    || type == typeof(PickerFlyoutPresenter)
                    || type == typeof(RangeBase)
                    || type == typeof(LoopingSelector)
                    || type == typeof(LoopingSelectorItem)
                    || type == typeof(PivotHeaderItem)
                    || type == typeof(TimePickerFlyoutPresenter)
                    )
                {
                    continue;
                }

                var controlObject = (Control)Activator.CreateInstance(type);
                if (controlObject.HorizontalContentAlignment != HorizontalAlignment.Center)
                { // Add breakpoint here. It's never hit.

                }
            }
        }
```

**Comment by Youssef1313** [comment]
I'll retry with `GetValue` instead of accessing the property directly "just in case".

**Comment by MartinZikmund** [comment]
@Youssef1313 Thanks for the verification, it seems correct. I will close 👍 !
