### ISSUE TITLE
HttpClient should be injectable to accomodate WASM build

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#404]
Provided that we have an autogenerated web client built in a .Net Standard 2.0 dll with [NSwaggerStudio](https://github.com/RSuter/NSwag/) , and wanted to use it in a WASM by adding a reference, the call to HttpClient.SendAsync fails with:

> System.PlatformNotSupportedException: Operation is not supported on this platform.
> mono.js (1,36297)
>   at System.Net.WebProxy.CreateDefaultProxy () <0x473a0c0 + 0x00008> in <a930e7965b7d4246901dc8d46db89d69>:0

By now you need to set  the GetHttpMessageHandler function to a WasmHttpHandler by reflection. I'm not quite sure why this can not set by default as part of the autogenerated code of the WASM head, but then, another option is to implement a **WasmMessageInvoker** class inheriting from **HttpMessageInvoker**, which can be interchanged in netStandard because HttpClient inherits from HttpMessageInvoker. 

 
Affected platform(s):
- [X] WebAssembly Uno.Wasm.Bootstrap (1.0.0-dev.121)

Visual Studio
- [x] 2017 (version: )
- [x] 2017 Preview (version: )
```

**Comment by MartinZikmund** [comment]
@jeromelaban isn't this fixed by any chance?

**Comment by jeromelaban** [comment]
This is not needed anymore, thanks :)
