### ISSUE TITLE
[iOS][MenuFlyoutSubItem] Sub menu doesn't open when clicking a MenuFlyoutSubItem

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/uno#4049]
## Current behavior

MenuFlyoutSubItem do not open a sub FlyoutMenu

![image](https://user-images.githubusercontent.com/64613932/93106363-2e38ad80-f67e-11ea-861c-5eb3d8d805fc.png)

## Expected behavior

MenuFlyoutSubItem open a sub FlyoutMenu

## How to reproduce it (as minimally and precisely as possible)

Launch app Uno.Gallery app
Navigate to Flyout
Select the "Nested MenuFlyout" sample
Select "Send Feedback"
Notice that no icon appear on the left of the MenuFlyoutItems

## Workaround

None

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): Uno.UI 3.0.0-dev.1533

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.6.2)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by agneszitte-nventive** [comment]
The issue is normally fixed, tested Gallery locally with latest Uno stable packages

iPhone Simulator 11 Pro Max iOS 15
Uno.UI 4.0.11
Uno.Material / Uno.Cupertino 1.2.0

If you can double-check @sakshi173, please

**Comment by sakshi173** [comment]
This issue is not happening, but getting another issue and raised another bug for this.
