### ISSUE TITLE
Commandbar Global Back button animation  is not smooth

### ISSUE THREAD

**Issue by HaoLife** [unoplatform/uno#405]
After the introduction of Frame style page navigation will appear animation effect is not smooth, as before and after the page will have a certain amount of time overlap appears

I use the following styles：

	<ios:Style x:Key="NativeDefaultFrame"
			   TargetType="Frame">
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="Frame">
					<NativeFramePresenter Background="{TemplateBinding Background}" />
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</ios:Style>

	<android:Style x:Key="NativeDefaultFrame"
				   TargetType="Frame">
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="Frame">
					<NativeFramePresenter Background="{TemplateBinding Background}" />
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</android:Style>

	<win:Style x:Key="NativeDefaultFrame"
			   TargetType="Frame">
		<Setter Property="HorizontalContentAlignment"
				Value="Stretch" />
		<Setter Property="IsTabStop"
				Value="False" />
		<Setter Property="VerticalContentAlignment"
				Value="Stretch" />
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="Frame">
					<ContentPresenter Content="{TemplateBinding Content}"
									  ContentTemplate="{TemplateBinding ContentTemplate}"
									  ContentTransitions="{TemplateBinding ContentTransitions}"
									  Background="{TemplateBinding Background}"
									  BorderBrush="{TemplateBinding BorderBrush}"
									  BorderThickness="{TemplateBinding BorderThickness}"
									  Padding="{TemplateBinding Padding}"
									  HorizontalContentAlignment="{TemplateBinding HorizontalContentAlignment}"
									  VerticalContentAlignment="{TemplateBinding VerticalContentAlignment}" />
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</win:Style>

	<Style TargetType="Frame"
		   BasedOn="{StaticResource NativeDefaultFrame}" />

## Minimal reproduction of the problem with instructions

Navigation -> GoBack ->Navigation  ->GoBack

## Environment

```
Nuget Package: 
Uno.UI

Package Version(s): 
>=1.40

Affected platform(s):
- [ x ] iOS
- [ x ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ x ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by jeromelaban** [comment]
Thanks for submitting the issue!

About the background overlapping, it's generally caused by the page not having a background color.

As for the smoothness, this is odd, particularly for iOS. Is your source or target page complex ?

**Comment by jeromelaban** [comment]
Got it. Are you testing in Debug or Release builds ?

**Comment by HaoLife** [comment]
I forgot, remember is the release version. But I'm using the release version in other examples.

**Comment by HaoLife** [comment]
Let me add the reasons for this problem.
The animation effect is used in the NativeFramePresenter 
if (GetIsAnimated(oldEntry))
{
     await oldPage.AnimateAsync(GetExitAnimation());
     oldPage.ClearAnimation();
 }
The core issue may not be animation, but thread. Will the switch from await method to background thread cause the problem of UI thread?

**Comment by jeromelaban** [comment]
The code for the presenter has changed since this issue. Is this still valid ?
