### ISSUE TITLE
Add WriteableBitmap support for Skia

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4059]
## What would you like to be added:

Add support for `WriteableBitmap` on Skia.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

Posted originally here: https://stackoverflow.com/questions/63923809/writeablebitmap-doesnt-render-on-linux-but-works-on-uwp-and-wasm/63923898#63923898

**Comment by Louis-Antoine-Blais-Morin** [comment]
Hi, 

Is there any easy replacement for WriteableBitmap that is now supported on Skia.GTK (Linux)?

The goal is to efficiently take an array of byte representing the pixel colors (raw data) and display it on screen.
The image needs to be refreshed from raw data many times a second, with low CPU usage, if possible.

**Comment by jeromelaban** [comment]
Not at this point, but we're looking at implementing this pretty soon.

**Comment by robloo** [comment]
I didn't realize this wasn't implemented in Skia. The ColorPicker depends on WriteableBitmap although you probably know that already.

**Comment by robloo** [comment]
Avalonia already implemented this in Skia. It looks fairly straightforward and code is MIT.

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Skia/Avalonia.Skia/WriteableBitmapImpl.cs
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Media/Imaging/WriteableBitmap.cs

**Comment by jeromelaban** [comment]
Yes this is a fairly easy implementation, not much interactions to do with Skia. The rest is mostly about interacting with Image and other parts of WinUI.
