### ISSUE TITLE
[Android] Navigation view is rendering incorrectly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#406]
## I'm submitting a...
- Bug report

## Current behavior
From this thread : https://gitter.im/uno-platform/Lobby?at=5c033b54500e8e372846e12e

The following Xaml does not display properly:
```xml
<Page
    x:Class="TestApp.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TestApp"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

        <NavigationView x:Name="NavigationViewControl" PaneDisplayMode="Top" HorizontalContentAlignment="Center" >
            <NavigationView.MenuItems>
                <NavigationViewItem HorizontalAlignment="Center" Content="First Item" x:Name="A" Icon="Accept"/>
                <NavigationViewItem Content="Second Item" x:Name="B" Icon="Save" />
                <NavigationViewItem Content="Third Item" x:Name="C" Icon="Calendar"/>
            </NavigationView.MenuItems>
        </NavigationView>
    </Grid>
</Page>
```
![image](https://user-images.githubusercontent.com/5839577/49376266-b5e54000-f6d4-11e8-9c01-1d111e2be2d7.png)

## Expected behavior
The above Xaml displays properly.

## Environment
Nuget Package: 1.42.0

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks
```

**Comment by TonyHenrique** [comment]
On Wasm this issue also is happening:
![image](https://user-images.githubusercontent.com/6307623/51793618-fbd4f680-21a1-11e9-8595-16ddbde18097.png)

On UWP it renders correctly
![image](https://user-images.githubusercontent.com/6307623/51793620-0b543f80-21a2-11e9-88c9-e4a4c7d88b8e.png)

**Comment by jeromelaban** [comment]
At present time, the `PaneDisplayMode.Top` is not supported.

**Comment by MartinZikmund** [comment]
This is fixed now, by utilizing the new WinUI `NavigationView`.
