### ISSUE TITLE
Obsolete tutorial guide for Xamarin.Forms

### ISSUE THREAD

**Issue by jingliancui** [unoplatform/uno#4065]
## On which page?
https://platform.uno/docs/articles/howto-use-uno-in-xamarin-forms.html#initialize

## What's wrong?
Obsolete tutorial guide for Xamarin.Forms (.Net Standard Library).

MainActivity.cs:
```
......
Uno.UI.ContextHelper.Current = Xamarin.Essentials.Platform.CurrentActivity;
LoadApplication(new App());  
```          

App.cs:
```
public App()
        {
            new Windows.UI.Xaml.Application();
            
            InitializeComponent();

            MainPage = new MainPage();
        }
```

MainPage.xaml:
```
<Label Text="Xamarin.Forms Label"></Label>
        <android:TextBlock Text="Android Uno Platform TextBlock" />
```

result:
Android textblock not shown

## Any feedback?
Is there any other way to use uno's controls in Xamarin.Forms ?

**Comment by SnowPowerCore** [comment]
Hello, +1

**Comment by sang-hyeon** [comment]
+1

**Comment by jingliancui** [comment]
Now is how from forms to MAUI

**Comment by jingliancui** [comment]
hello team, is any update on this?

**Comment by sasakrsmanovic** [comment]
Hello @jingliancui . This tutorial is indeed obsolete as this is not a supported approach for a long time now. We have provided migration documentation at https://platform.uno/docs/articles/guides/xf-migration/overview.html and will be removing the one you linked. Thanks for pointing that out.
