### ISSUE TITLE
Add support for RevealBackgroundBrush

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#408]
## I'm submitting a...
- Feature request

## Current behavior
The `RevealBackgroundBrush` is not supported.

## Expected behavior
The `RevealBackgroundBrush` is supported to show blurred content.

## Environment
Nuget Package: 1.42

**Comment by MartinZikmund** [comment]
Could we for now do a partial implementation of Reveal and Acrylic just using the `FallbackColor` property? That way it would work exactly the same way as `SolidColorBrush` until it is implemented properly, but would not require conditional XAML.

**Comment by jeromelaban** [comment]
Yes, it would be a better implementation. Also, adding an acrylic like brush is not far from reach, so it would serve as a base.

**Comment by Youssef1313** [comment]
Microsoft's documentation for this says:

> `RevealBackgroundBrush` is available for use in the operating systems specified in the Requirements section. However, we do not recommend its use as it may be altered or unavailable in subsequent versions.

Since it's not recommended by Microsoft (as far as I understand), do we need to implement it?

**Comment by MartinZikmund** [comment]
Microsoft seems to be avoiding reveal for the new styles and the reveal highlight docs were also removed from design docs. As long as we properly use the `FallbackColor`, it should be ok.

**Comment by MartinZikmund** [comment]
Closing as `Reveal` should not be used anymore
