### ISSUE TITLE
[Wasm] Add support for ImageBrush

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#409]
## I'm submitting a...
- Feature request 

## Current behavior
Setting the Brush property of a border to an `ImageBrush` does not work.

## Expected behavior
Setting the Brush property of a border properly shows the source image.

## Environment
```
Nuget Package: 1.42

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks
```

**Comment by davidjohnoliver** [comment]
This is preventing the `ColorPicker` control from working on WASM, because it's using an ImageBrush with a WriteableBitmap to draw the color spectrum.
