### ISSUE TITLE
[Prism] Can't find ElementName in UserControl with ShowDialog.

### ISSUE THREAD

**Issue by kaki104** [unoplatform/uno#4100]
Hi

Today I installed template 410 and created a project using the command dotnet new unoapp-prism -o UnoPrism410.

The reason for creating a new project was to output UserControl using DialogService, but to check that there was no binding using ElemenetName on the screen.

```
        <ListView ItemsSource="{Binding Texts}"
                  x:Name="TextListView2">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <Grid>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition/>
                            <ColumnDefinition Width="Auto"/>
                        </Grid.ColumnDefinitions>
                        <TextBlock Text="{Binding}"/>
                        <Button Grid.Column="1" Content="Test2" 
                                Command="{Binding DataContext.TestCommand, ElementName=TextListView2}"/>
                    </Grid>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>

```
In the above code, ElementName=TextListView2 was found in Uwp app and command bound, but binding is not available on Android and iPhone.
This phenomenon is thought to occur only in the UserControl output using DialogService.

I couldn't test it on the WebAssembly project.

## Current behavior

In UWP app, when you click the Test2 button, TestCommand is executed.
It does not work on Android and iPhone.

## Expected behavior

TestCommand should be executed on all platforms.

## How to reproduce it (as minimally and precisely as possible)

I put the sample project here.
https://github.com/kaki104/UnoPrism410

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Uno.UI, Uno.UI.RemoteControl, Uno.UI.WebAssembly : v3.1.0-dev.410
Uno.Wasm.Bootstrap : 1.3.0
Uno.Wasm.Bootstrap.DevServer : 1.3.0

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.7.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. For troubleshooting, if you add this in your `DataTemplate`, what do you see:

```xaml
<StackPanel>
   <TextBlock Text="{Binding, ElementName=TextListView2}"/>
   <TextBlock Text="{Binding DataContext, ElementName=TextListView2}"/>
</StackPanel>
```

**Comment by kaki104** [comment]
I don't see anything on both of them in the android emulator.

```
        <ListView ItemsSource="{Binding Texts}"
                  x:Name="TextListView2">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <Grid>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition/>
                            <ColumnDefinition Width="Auto"/>
                        </Grid.ColumnDefinitions>
                        <TextBlock Text="{Binding}"/>
                        <StackPanel Grid.Column="1">
                            <TextBlock Text="{Binding ElementName=TextListView2}"/>
                            <TextBlock Text="{Binding DataContext, ElementName=TextListView2}"/>
                        </StackPanel>
                    </Grid>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>

```
