### ISSUE TITLE
Docs: Sample for using Push Notifications

### ISSUE THREAD

**Issue by sasakrsmanovic** [unoplatform/uno#4104]
Create a sample or guide on using Push Notifications in Uno Platform - what needs to be done on Uno side vs underlaying stack (xamarin or dotnet5)

**Comment by MartinZikmund** [comment]
Closing in favor of #4104

**Comment by davidjohnoliver** [comment]
@MartinZikmund you just closed 4104 in favour of 4104 :p

**Comment by MartinZikmund** [comment]
Ah! Different favor 😀 - #3661
