### ISSUE TITLE
Docs - how to host Uno WASM in http://ASP.NET Core

### ISSUE THREAD

**Issue by sasakrsmanovic** [unoplatform/uno#4118]
From twitter via https://twitter.com/bricelambs/status/1286314895537893376

**Comment by ToddGlodek** [comment]
I am imagining that this would work in a similar fashion to the way Silverlight apps are deployed. What we found with Silverlight is that a large enterprise ended up building several separate apps to manage each line of business problem through independent dev/test/deploy pipelines. There would typically be a collection of shared controls/services used by all the projects,

Seeing how this works for Uno (even if it is just a visual diagram) would be very useful.

**Comment by jeromelaban** [comment]
I think it can, now that we have the server project.
