### ISSUE TITLE
[Android] ScrollViewer will scroll by itself to a button

### ISSUE THREAD

**Issue by Guidemarcus** [unoplatform/uno#4122]
## Current behavior

A ScrollViewer with a button inside will scroll to it if it is not in the field of view of the user. On Android only.

## Expected behavior

The ScrollViewer should stay at the top whatever its content.

## How to reproduce it (as minimally and precisely as possible)

[ScollAndroid.zip](https://github.com/unoplatform/uno/files/5269210/ScollAndroid.zip)

## Workaround

Add  BringIntoViewOnFocusChange="False" to the ScrollViewer

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [x] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.0.12

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
[See](https://stackoverflow.com/questions/64035494/how-can-i-stop-android-scrollviewer-to-scroll-itself-to-its-first-button-child) the `BringIntoViewOnFocusChange` property.
