### ISSUE TITLE
IOS 14 and WASM DateTimePicker cant select a new Date on Uno.Gallery

### ISSUE THREAD

**Issue by iosub** [unoplatform/uno#4131]
I dont know if this is a new issue with iOS14 but the DateTimePicker and TimePicker does not have enough place to select a new date

There is a new api for iOS14 check on https://www.andyibanez.com/posts/new-uidatepicker-ios14/

## How to reproduce it (as minimally and precisely as possible)

just Open Uno.Gallery and go to DateTimePicker example on iOS

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Uno 3.0.17

Affected platform(s):

- [X ] iOS
- [ ] Android
- [X ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by iosub** [comment]
Hi, More info
https://github.com/xamarin/Xamarin.Forms/issues/11963

**Comment by iosub** [comment]
https://github.com/muak/AiForms.SettingsView/issues/130

**Comment by jeromelaban** [comment]
Could you paste a screenshot of what you're seeing, I'm not seeing any problem with it at the moment on iOS 14.

**Comment by iosub** [comment]
![1](https://user-images.githubusercontent.com/1330995/94209092-be22f680-fecb-11ea-84b8-fc623bd4696e.png)

The Wheels is so down that you cant change the date

Also you have more examples on https://github.com/muak/AiForms.SettingsView/issues/130

**Comment by jeromelaban** [comment]
Which version of the Uno.Material library are you using ?

**Comment by iosub** [comment]
Just for the test I was using unoplatform/dev/madi/datepicker-style

anyway you can reproduce easy with
 
     <StackPanel Orientation="Vertical">
         <DatePicker x:Name="Test1" />
         
     </StackPanel

**Comment by jeromelaban** [comment]
Thanks. This is probably only happening when building for iOS 14 specifically, and does not happen when the app is built with previous versions of the SDK.

**Comment by iosub** [comment]
Hi
Yes I have tested with xcode 11 and Xamarin ios 11 and https://github.com/unoplatform/Uno.Gallery works .. The problem is with xcode 12 and xamarin sdk 12
