### ISSUE TITLE
Add support for WebRTC

### ISSUE THREAD

**Issue by edparitor** [unoplatform/uno#4138]
## What would you like to be added:
I'd really like to have Uno.WebRTC available as the basis for cross-platform streaming/conferencing apps

## Why is this needed:
Part of our Uno app will allow educators to offer virtual/video lessons. The simplest way to offer this as a cross-platform solution is to develop a website, launch the url on the client and rely on browser support.  However, it would be great to be able to write this within the native apps.

WebRTC.org has C++ libraries for android, ios and windows. MS have adapted/wrapped this for UWP https://github.com/webrtc-uwp.  So developing the solution within our app would be possible, but time consuming.  There are cross-platform libraries already, such as icelink, to speed that up, but they have a cost and they would still need to be worked into each head.

An entirely Uno based solution would be great.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by dbruning** [comment]
https://github.com/sipsorcery-org/sipsorcery would be a great starting point for this.

**Comment by hawkerm** [comment]
There's also this library which does Blazor/Xamarin support: https://github.com/melihercan/WebRTCme

**Comment by jeromelaban** [comment]
We added a sample for this a while back: https://github.com/unoplatform/uno/blob/2ff49c81fa406425f39850cc061971818fa82a2c/doc/articles/uno-samples.md#webrtc

**Comment by Dreamwalker666** [comment]
> We added a sample for this a while back: https://github.com/unoplatform/uno/blob/2ff49c81fa406425f39850cc061971818fa82a2c/doc/articles/uno-samples.md#webrtc
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/132453438/7fcbaf80-9f86-11e9-9d5c-1feea63c9a2e"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[uno/uno-samples.md at 2ff49c81fa406425f39850cc061971818fa82a2c · unoplatform/uno](https://github.com/unoplatform/uno)**Build Mobile, Desktop and WebAssembly apps with C# and XAML. Today. Open source and professionally supported. - uno/uno-samples.md at [2ff49c8](https://github.com/unoplatform/uno/commit/2ff49c81fa406425f39850cc061971818fa82a2c) · unoplatform/uno

This only covers webassembly doesn't it, how does this work for the other platforms requested in the main issue?

**Comment by edparitor** [comment]
@Dreamwalker666 It's true that I was hoping for a lower level integration on some more platforms
