### ISSUE TITLE
Fix ListViewItem.cs Directory

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#4139]
## What would you like to be improved:

I notice a ListView directory containing ListViewItem.cs that seems out of place. Shouldn't this be in controls inside the ListView directory there?

![image](https://user-images.githubusercontent.com/17993847/94179352-61dbba80-fe6a-11ea-9f3e-c7d5982f197f.png)

## Why is this needed:

Code quality improvement

## For which Platform:

All

**Comment by davidjohnoliver** [comment]
Guidance for contributors: Remember to do a git 'rename' operation to preserve the source history for the file. :)

**Comment by robloo** [comment]
@kazo0 Already made this change it looks like, thanks!
