### ISSUE TITLE
[WASM] Cannot build if using SkiaSharp

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#4150]
## Current behavior

If you attempt to build a WASM project that uses SkiaSharp the build fails with an error similar to,

[00:00:00.1132190] ninja: error: '/mnt/c/Users/user/.nuget/packages/uno.skiasharp.wasm/2.80.0-uno.483/build/netstandard2.0/libSkia/libSkiaSharp.a', needed by '/mnt/c/Users/user/Documents/project/project.Wasm/obj/Debug/netstandard2.0/dist_work/dotnet.js', missing and no known rule to make it

Last known good version was 3.1.0-dev.327

## Expected behavior

Build should work as expected.

## How to reproduce it (as minimally and precisely as possible)

Attempt to build the attached project in Wasm

[SkiaSharpBuild.zip](https://github.com/unoplatform/uno/files/5284700/SkiaSharpBuild.zip)

## Workaround

Rolling back Uno packages to  3.1.0-dev.327 resolves issue

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.1.0-dev.472
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Make sure to try with the latest bootstrapper 1.4 if you were using a dev version, this was a regression introduced recently.
