### ISSUE TITLE
TextBox memory leak in iOS

### ISSUE THREAD

**Issue by TheRusstler** [unoplatform/uno#4168]
## Current behavior

The `Windows.UI.Xaml.Controls.TextBox` is never garbage collected on iOS. Similar to [#3914](https://github.com/unoplatform/uno/issues/3914), but no binding is required to produce this leak, simply place a TextBox control in a Page, then navigate away. 

The [Memory Instances counter](https://platform.uno/docs/articles/uno-development/debugging-uno-ui.html#enable-memory-instances-counter) shows the TextBox control is not being collected. One instance persists for each navigation:
<img width="1498" alt="Screenshot 2020-09-28 at 18 21 12" src="https://user-images.githubusercontent.com/8938396/94465519-8f4c9f00-01af-11eb-8ce4-3822f268072f.png">

Below are some images of the Xamarin Profiler's output showing the control persisting forever.

<img width="1498" alt="Screenshot 2020-09-28 at 18 21 07" src="https://user-images.githubusercontent.com/8938396/94466370-dbe4aa00-01b0-11eb-8dff-5e8ad8d236b2.png">

<img width="1498" alt="Screenshot 2020-09-28 at 18 22 02" src="https://user-images.githubusercontent.com/8938396/94466376-de470400-01b0-11eb-8316-08df4d0d350f.png">

When inspecting the last snapshot, you can see that 30 `Windows.UI.Xaml.Controls.TextBox` are *Persisted*, meaning that they are not being released, which results in a memory leak.

## Expected behavior

On navigating back from a page, instances of the TextBox control in the previous page should be released, resulting in no memory leak.

## How to reproduce it (as minimally and precisely as possible)

Minimal reproducible example: https://github.com/TheRusstler/UnoMemoryLeakExample

Run these steps while using the [Xamarin Profiler](https://docs.microsoft.com/en-us/xamarin/tools/profiler/?tabs=macos) to watch the memory footprint increase linearly as you continue to navigate between the pages.

1. Run the application on an iOS device from Visual Studio for Mac.
2. Click the button on the main page of the app to navigate to the secondary page.
3. Click the button on the secondary page to navigate to the main page.
4. Repeat steps 2 and 3 ad nauseum (around 20-30 times will increase memory usage to ~30MB).
5. Stop repeatedly navigating and do nothing for however long you would like.
6. Take snapshots every 30 seconds or so in the Xamarin Profiler tool and see that the memory footprint remains roughly the same forever.
7. View the Console to see multiple "**Inactive binder references**" of `Windows.UI.Xaml.Controls.TextBox`, one persisting for each navigation.

## Workaround

We have been unable to find one so far.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): Uno.UI 3.0.17, Uno.UI 3.1.0-dev.485

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [x] Visual Studio for Mac (version: 8.7.8 (build 4))
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report!

**Comment by jeromelaban** [comment]
I'm not able to repro this issue with the [template pooling disabled](https://github.com/unoplatform/uno/blob/d76d01da5178f8fae6dc9c538b4554736981908b/doc/articles/Uno-UI-Performance.md#frameworktemplatepool). Can you try on your end by either waiting [about a minute](https://github.com/unoplatform/uno/blob/ab420570f72ff0ceb5fcc77f2337fc379187515d/src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs#L110) to take a snapshot ? You can also try [disabling the template pool](https://github.com/unoplatform/uno/blob/ab420570f72ff0ceb5fcc77f2337fc379187515d/src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs#L115) altogether.

**Comment by TheRusstler** [comment]
Thanks for looking into this & all your incredible work with Uno. 

I disabled template pooling, and ran the same test. There are 30 TextBox controls left over as before.

Were you able to repro using the example: https://github.com/TheRusstler/UnoMemoryLeakExample ?

Let me know if I can provide any more assistance - I will try to find a fix myself, but it looks like a tough first issue!

<img width="659" alt="Screenshot 2020-09-29 at 08 46 36" src="https://user-images.githubusercontent.com/8938396/94534620-1f322d80-0230-11eb-97e7-478a6a7315e4.png">
<img width="1498" alt="Screenshot 2020-09-29 at 08 45 57" src="https://user-images.githubusercontent.com/8938396/94534610-1d686a00-0230-11eb-99c2-7ffff55dd5a9.png">
<img width="1498" alt="Screenshot 2020-09-29 at 08 46 14" src="https://user-images.githubusercontent.com/8938396/94534615-1e999700-0230-11eb-9e80-58ab7adaa783.png">
<img width="1498" alt="Screenshot 2020-09-29 at 08 46 20" src="https://user-images.githubusercontent.com/8938396/94534618-1e999700-0230-11eb-9dce-c9df8aaef8ef.png">

**Comment by jeromelaban** [comment]
Thanks for the troubleshooting. One important part of the memory profiling is finding the roots. In general, when looking at the leaking objects, it's possible to find out the path of what causing the leak, for a specific instance. Could you paste a sceenshot of that as well ?

**Comment by jeromelaban** [comment]
The source of the issue is caused by the "Delete Button" inside of a TextBox:

![image](https://user-images.githubusercontent.com/5839577/94560927-50f7c400-0231-11eb-9aeb-9f8d83688a86.png)

It contains a command that creates a hard between the TextBox and the Button instances, which I'll be fixing.
