### ISSUE TITLE
Problems when publishing to Azure

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#4176]
When publishing to Azure:
.nuget\packages\uno.wasm.bootstrap\1.4.0-dev.45\build\Uno.Wasm.Bootstrap.targets(128,2): Error : Failed to create directory \bin\Debug\netstandard2.1\dist]
Because of this, publishing always fails.

**Comment by jeromelaban** [comment]
A new package is available (Uno.UI 3.1.0-dev.553) which fixes the file locking problem you mentioned earlier. 

I've been trying to reproduce the missing `web.config` file, without much luck.

Could you try running in a "Developer Command Prompt", the following:
```bash
msbuild /r /t:Publish /bl /p:Configuration=Release yourproject.csproj
```

This will create another binlog file, could you post it here ? Thanks.

**Comment by HavenDV** [comment]
web.config was originally skipped in the project I used as a template for some reason.
But, I think that perhaps some kind of check is needed for this file, which will prevent publication if the web.config file is omitted

**Comment by jeromelaban** [comment]
Indeed. What do you mean by "skipped" ? Was it not in the csproj file or wwwroot folder ?

**Comment by HavenDV** [comment]
It was not in the wwwroot folder. I still haven't figured out how this could have happened because the official examples contain it. I think it was my mistake.

**Comment by jeromelaban** [comment]
Thank you for the update. Do you have any other publishing issue or can this issue be closed ?

**Comment by HavenDV** [comment]
Thanks for answering the questions. I was able to successfully publish the app using your advice.
