### ISSUE TITLE
WCT: iOS -Android  close icon does not show on tabview

### ISSUE THREAD

**Issue by iosub** [unoplatform/uno#4181]
WCT: iOS -Android  close icon does not show on tabview

## How to reproduce it (as minimally and precisely as possible)

add tabview from WCT to a solution and run on Android or iOS, the close icon of the tab is not show

## Workaround
replease the font  `&#xE711;` for a `  <SymbolIcon Symbol="Cancel" />` on TabView.xaml
`  <Button
      x:Name="CloseButton"
      x:Uid="/Microsoft.Toolkit.Uwp.UI.Controls/Resources/WindowsCommunityToolkit_TabView_CloseButton"
      Style="{StaticResource TabViewItemCloseButtonStyle}">
      <SymbolIcon Symbol="Cancel" />
  </Button>`

Suggestion change the rectangle style from Top to Bottom to be in sync with most tabs controls

`<Rectangle
    x:Name="SelectionIndicator"
    Height="2"
    Margin="0,-1"
    VerticalAlignment="Bottom"
    Fill="{ThemeResource TabViewSelectionIndicatorForeground}"
    Opacity="0" />`
## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ X] iOS
- [X ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ X] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by robloo** [comment]
The WCT toolkit TabView has largely been replaced by the WinUI version. The WinUI TabView port is already in-progress here: https://github.com/unoplatform/uno/pull/3876. You might want to consider switching to this version of the control when ready.

**Comment by MartinZikmund** [comment]
This is now working in the new WinUI `TabView`
