### ISSUE TITLE
Incorrect TextBlock measure in Grid

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/uno#4212]
Having 2 states

![image](https://user-images.githubusercontent.com/2365592/94974423-31091e80-0517-11eb-9e8a-3232d81a91f5.png)
![image](https://user-images.githubusercontent.com/2365592/94974428-36feff80-0517-11eb-934f-61ac9ea42c1a.png)

In the portrait, mode measure happens incorrectly

![image](https://user-images.githubusercontent.com/2365592/94974505-762d5080-0517-11eb-97fa-bd49cc39162e.png)

The same happens on WASM

When launched then shinked:
![image](https://user-images.githubusercontent.com/2365592/94975569-c8bc3c00-051a-11eb-95b5-7d7bf83372ac.png)

When shrinked then launched:
![image](https://user-images.githubusercontent.com/2365592/94975590-dbcf0c00-051a-11eb-9875-8fe050fc3fe3.png)
![image](https://user-images.githubusercontent.com/2365592/94975655-05883300-051b-11eb-96e0-3476457de7a2.png)

See source at https://github.com/xperiandri/Elmish.Uno/blob/622fba4da5e2e691cac6f7e39773d26241f4a149/src/Samples/Samples.Shared/SingleCounterPage.xaml#L96

## Current behavior

When a piece of UI moves from one row and column of a `Grid` to another, then the row width is not recalculated

## Expected behavior

`Grid` recalculates on children `Grid.Row` or `Grid.Column` changes

## How to reproduce it (as minimally and precisely as possible)

https://github.com/xperiandri/Elmish.Uno/
SimpleCounter sample

## Workaround

Maybe invalidating measure in code will work.

## Environment

NuGet Package:
- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

NuGet Package Version(s):
``` XML
<PackageReference Include="Elmish" Version="3.1.0" />
<PackageReference Include="FSharp.Control.FusionTasks" Version="2.0.2" />
<PackageReference Include="Uno.Core" Version="2.0.0" />
<PackageReference Include="Uno.UI" Version="3.0.17" />
```

Affected platform(s):

- [X] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Grid.Row and Colunms updates generally work properly, but StateTriggers may not. Could you validate that the Grid.Row/Columns values are what you expect by adding a TextBlock like this in the xaml : 
```xaml
<TextBlock Text="{Binding (Grid.Row), ElementName=grid}" />
```

**Comment by xperiandri** [comment]
![image](https://user-images.githubusercontent.com/2365592/95131242-66577b80-0766-11eb-9649-1f7ace1ba96e.png)

Value changes. Otherwise, the grid wouldn't go to the down row

**Comment by xperiandri** [comment]
The issue is that measure is not invalidated. Maybe because of Grid.Row/Column are set as animation

**Comment by jeromelaban** [comment]
I'm not sure of what I see here, does the TextBlock displayed value change when the visual state changes ?

**Comment by xperiandri** [comment]
Yes, the number 1 in the top left corner is what you have asked to add

**Comment by xperiandri** [comment]
![image](https://user-images.githubusercontent.com/2365592/95132168-ff3ac680-0767-11eb-9762-6e7a75368666.png)

Here it is `0`

**Comment by jeromelaban** [comment]
Thanks. If you can create a repro using the default Uno templates, It would help significantly.

**Comment by xperiandri** [comment]
You are welcome
[App2.zip](https://github.com/unoplatform/uno/files/5343486/App2.zip)
I don't understand why did you ask about that as it is a plain XAML. Which anyone can copy from https://github.com/xperiandri/Elmish.Uno/blob/622fba4da5e2e691cac6f7e39773d26241f4a149/src/Samples/Samples.Shared/SingleCounterPage.xaml and paste into a new project.

The key point of issue is https://github.com/xperiandri/Elmish.Uno/blob/7c8325737995306036c131f93dcfbdef6834b83c/src/Samples/Samples.Shared/SingleCounterPage.xaml#L14
When `HorizontalAlignment="Center"` then measure is incorrect.

**Comment by jeromelaban** [comment]
Thanks for the repro. We need those to avoid spending time recreating the issue that is generally not obvious. 

In this case, the issue is not that the measure is not happening, but rather than the grid measures the textblock incorrectly. We're going to be updating the grid's source with the original WinUI's code, and this kind of behavior will disapear.

**Comment by xperiandri** [comment]
Cool!
