### ISSUE TITLE
What dependency injection frameworks work with WASM? 

### ISSUE THREAD

**Issue by asusralis** [unoplatform/uno#4214]
I'm on the latest version of UNO. I've tried both Autofac and Zenject and both make WASM hang up at its loading screen. Both work on UWP. Is there a specific reason for this? What dependency injection frameworks are others using?

**Comment by jeromelaban** [comment]
@asusralis Thanks for your question. Would you mind asking it on StackOverflow here: https://stackoverflow.com/questions/tagged/uno-platform ? Thanks !
