### ISSUE TITLE
StorageFile.GetFileFromApplicationUriAsync WASM iOS (Safari/Chrome) not working 

### ISSUE THREAD

**Issue by stevozilik** [unoplatform/uno#4224]
## Current behavior

Following the guide on how to expose static resources [link](https://github.com/unoplatform/uno/blob/master/doc/articles/features/windows-storage.md#support-for-storagefilegetfilefromapplicationuriasync)

When calling **StorageFile.GetFileFromApplicationUriAsync(...Uri..)**, the method throws :System.ApplicationException:

GetUriResourceStreamAsync error getting 'Assets/Images/checkeredGrid_9x39.png':System.ApplicationException
  at Windows.Storage.Helpers.AssetsManager.DownloadAsset (System.Threading.CancellationToken ct, System.String assetPath) [0x001a7] in C:\a\1\s\src\Uno.UWP\Storage\Helpers\AssetsManager.wasm.cs:55
  at Windows.Storage.StorageFile.GetFileFromApplicationUriAsyncTask (System.Threading.CancellationToken ct, System.Uri uri) [0x00052] in C:\a\1\s\src\Uno.UWP\Storage\StorageFile.wasm.cs:27
  at Windows.Foundation.AsyncOperation`1[TResult].BuildTaskAsync (System.Func`2[T,TResult] taskBuilder) [0x000a8] in C:\a\1\s\src\Uno.Foundation\AsyncOperation.TResult.cs:38

**The Asp Net Core server is contacted, and serving the file as expected:**
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://[url]/package_16824659ed8ac944290d18830007b00ef8daeb53/Assets/Images/checkeredGrid_9x39.png  
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Information: Sending file. Request path: '/package_16824659ed8ac944290d18830007b00ef8daeb53/Assets/Images/checkeredGrid_9x39.png'. Physical path: 'C:\code\UnoApp2\UnoApp2\UnoApp2.Wasm\bin\Debug\netstandard2.0\dist\package_16824659ed8ac944290d18830007b00ef8daeb53\Assets\Images\checkeredGrid_9x39.png'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 10.6702ms 200 image/png

## Expected behavior

On PC the same WASM web clients works in all Browsers as expected, the requested resource 'Assets/Images/checkeredGrid_9x39.png' stream is provided. 

## How to reproduce it (as minimally and precisely as possible)
https://github.com/unoplatform/uno/blob/master/doc/articles/features/windows-storage.md#support-for-storagefilegetfilefromapplicationuriasync

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia 
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [x] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
.nuget\packages\uno.ui\3.1.0-dev.565\lib\netstandard2.0\Uno.dll
Affected platform(s):

- [x] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.7.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

In the dist folder, there's an uno-assets.txt file, which contains all the available files. Could you validate that the path you're requesting is in this file ?
