### ISSUE TITLE
Add support for cross-targeted fonts

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4228]
## What would you like to be added:

The ability to place fonts in the shared projects and be automatically set to the appropriate item type.

## Why is this needed:

Avoid duplication of fonts across heads.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by pdecostervgls** [comment]
@jeromelaban I've implemented this for iOS and Android, kinda stuck on how to handle this for WebAssembly.
WASM would require us to generate a custom font-face with data URL of the contents of the .woff2 file, not sure how practical that would be.

**Comment by jeromelaban** [comment]
Yes, indeed we would need a way to convert a TTF font to woff2 first, or to be able to detect that a both a file named .ttf and .woff2 are the same logicall font, and that only one of the two needs to be used on wasm.

This issue is also related to https://github.com/unoplatform/uno/issues/693.

**Comment by pdecostervgls** [comment]
Even if we could pull that off, we would subject the Fonts.css file to be only editable by the CSS generator. Also, Could we extract the font-face name from the font files?

**Comment by jeromelaban** [comment]
We can adjust the bootstrapper to properly support the addition of specific files. As for the extraction of the font-face name, I do not know if there are existing libraries that do this easily. Do you know of one ?

**Comment by pdecostervgls** [comment]
@jeromelaban I found https://github.com/RazrFalcon/ttf-parser, which should be able to read the font family based on the examples they provided. Dont know how using a C/Rust tool would work with MSBuild though
