### ISSUE TITLE
ANDROID ComboBox inside a ContentDialog error Failed to raise 'PointerReleasedEvent': Android.Views.WindowManagerBadTokenException

### ISSUE THREAD

**Issue by iosub** [unoplatform/uno#4230]
## Current behavior

 ComboBox inside a ContentDialog error Failed to raise 'PointerReleasedEvent': Android.Views.WindowManagerBadTokenException

## How to reproduce it (as minimally and precisely as possible)

create a ContentDialog and Place a ComboBox 
I have add an Example project and the output log

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno 3.0.12
Affected platform(s):

- [X] Android
[TextComboBoxContentDialog.zip](https://github.com/unoplatform/uno/files/5344569/TextComboBoxContentDialog.zip)

- [X] Visual Studio 2019 (version: )
Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thank you for the report. This is a duplicate of this issue https://github.com/unoplatform/uno/issues/2533. A workaround is available in this issue.
