### ISSUE TITLE
Not able to select the items in the ComboBox with the use of SelectedItem="{Binding [SelectedColorItem], Mode=TwoWay}"

### ISSUE THREAD

**Issue by pallavichaudhari** [unoplatform/uno#4236]
## Current behavior
I have bound a State to the ComboBox SelectedItem property 
SelectedItem="{Binding [SelectedColorItem], Mode=TwoWay}"
 private State<ColorItem> SelectedColorItem => this.States().Create<ColorItem>(this.Feeds().Attach(() => ColorItems.Select(ci => ci.FirstOrDefault())));

## Expected behavior

Whatever item is selected through the State; that particular item should get selected always. It gets selected for the first time, but when I visit the same page, although the list is available but that item is not selected. 

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. Did the issue get resolved ?
