### ISSUE TITLE
The License link is broken

### ISSUE THREAD

**Issue by dev-bre** [unoplatform/uno#4238]
What is the license for this platform?

**Comment by jeromelaban** [comment]
Thanks for the report. Would you mind telling which link ? The link on the GitHub page directs to the [License.md](https://github.com/unoplatform/uno/blob/master/License.md) file.

**Comment by dev-bre** [comment]
If you look at the repo from the GitHub Android app, you will see "other" for license with a broken link.

**Comment by jeromelaban** [comment]
I'm not seeing this (nor in the iOS app), could you post a screenshot of this ?

**Comment by dev-bre** [comment]
There you go:

![Screenshot_20201009-072135.png](https://user-images.githubusercontent.com/905984/95550018-227fa300-0a00-11eb-829d-f32a13ab4794.png)

**Comment by jeromelaban** [comment]
Thanks, and where does it lead to ?

**Comment by dev-bre** [comment]
To this link:

https://choosealicense.com/licenses/other/

Which is a 404 as I previously stated.

Hope this helps.

**Comment by jeromelaban** [comment]
We are not able to reproduce this issue, the link is appearing properly in the app. This is also not something we cannot adjust on our end since github automatically picks up the License.md file.
