### ISSUE TITLE
x:Bind is raising an error when binding against a Constant

### ISSUE THREAD

**Issue by Massimo37** [unoplatform/uno#4247]
## Current behavior

Using x:Bind against a constant is raising an error:

`error CS7000: Unexpected use of an aliased name`

## Expected behavior

Using x:Bind against a constant shouldn't raise an error, works perfectly in UWP.

## How to reproduce it (as minimally and precisely as possible)

1. Create the following class:

```cs
namespace UnoApp
{
	public static class Constants
	{
		internal const int INT_VALUE = 5;
	}
}
```

2. Add the following in any Xaml page:

```xml
xmlns:app="using:UnoApp"

<TextBlock Text="{x:Bind app:Constants.INT_VALUE}" />
```

## Workaround

Change `internal const int INT_VALUE = 5;` to `internal static int INT_VALUE { get; } = 5;`

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [X] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.0.17

Affected platform(s):

- [X] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

The generated code is using `global::` as an instance property (look at `___tctx.global::` below):

`global::Uno.UI.Xaml.BindingHelper.SetBindingXBindProvider(___b, this, ___ctx => ___ctx is global::UnoApp.MainPage ___tctx ? (object)(___tctx.global::UnoApp.Constants.INT_VALUE) : null, null )`

**Comment by jeromelaban** [comment]
## Note for contributors

This issue is most likely caused by this function:
https://github.com/unoplatform/uno/blob/master/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L3519

Which does not recognize constants as non-instance members of a type.
