### ISSUE TITLE
Project Templates for (Desktop/Mobile/(Web)) projects

### ISSUE THREAD

**Issue by Rogardo** [unoplatform/uno#4258]
## What would you like to be added:
It would be neat to have project templates for single targets. A Desktop template that targets a pure Desktop projekt (Linux, Mac, Windows), a mobile Template only for mobile (Android, IOS, UWP) maybe both with a additional checkbox (option) for Web.

## Why is this needed:
I'm very interested in UNO for porting my WPF Projects to Linux. My current projects a pure desktop solutions and I don't need very time the full mobile project overload.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [X] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the suggestion!

You can do this currently with the `dotnet new` experience, but not in the VS IDE experience (though VS 16.8 may change this).

You can view the options here: https://github.com/unoplatform/uno/blob/master/doc/articles/get-started-dotnet-new.md#dotnet-new-templates-for-uno-platform
 
by using `dotnet new unoapp -h`
