### ISSUE TITLE
Refactoring: enable #nullable in XamlFileGenerator

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#4286]
## What would you like to be added:
`#nullable enable` in `XamlFileGenerator.cs` and `XamlFileGenerator.Reflection.cs`

## Why is this needed:
This class is particularly prone to NRE-related bugs (eg: https://github.com/unoplatform/uno/pull/4284) as it has a huge number of code paths and in practice it's hard to test all possible scenarios encountered in user code. 

So far we've usually added nullable-awareness to existing code in the course of doing other work, but the file in question is sufficiently large to justify a standalone PR, for clear visibility and discussion of the resultant refactoring.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by daniel-shuy** [comment]
I'd like to work on this

**Comment by davidjohnoliver** [comment]
@daniel-shuy Just to give some context, the class in question is 5k lines of code. ;) Working on this issue would call for a detailed understanding of Uno's Xaml parsing and `XamlFileGenerator` specifically, to know which nullability semantics to apply in each case.

That said if you feel like you're up to it, you're welcome to give it a shot :)

**Comment by daniel-shuy** [comment]
@davidjohnoliver haha yeah I just realized how gargantuan a task this is after starting on it. I think I'll create an initial PR for it, but will require someone who is familiar with the Xaml parsing to thoroughly check if I'm handling the nulls correctly.

**Comment by Youssef1313** [comment]
This was fixed in https://github.com/unoplatform/uno/pull/5591. I believe it can be closed.
