### ISSUE TITLE
x:Bind to second-level method generates invalid code

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4298]
## Current behavior

Using `QuerySubmitted="{x:Bind ViewModel.SearchBreeds}"` generates:
```csharp
var QuerySubmitted_ViewModel.SearchBreeds_That = (this as global::Uno.UI.DataBinding.IWeakReferenceProvider).WeakReference;
c3.QuerySubmitted += (_sender,_args) => (QuerySubmitted_ViewModel.SearchBreeds_That.Target as MainPage)?.ViewModel.SearchBreeds();
```

The generated variable name contains a `.` and is not valid C#.

## How to reproduce it (as minimally and precisely as possible)

```xaml
        <AutoSuggestBox Grid.Row="1" PlaceholderText="Search for breed" QueryIcon="Find" 
                        Width="300" Margin="4,20" HorizontalAlignment="Left"
                        Text="{x:Bind ViewModel.SearchTerm, Mode=TwoWay}"
                        QuerySubmitted="{x:Bind ViewModel.SearchBreeds}"
                        />
```
## Environment
Nuget Package Version(s): 3.1

## Note to contributors

This issue is most likely related to this, where the path name is not sanitized properly:

https://github.com/unoplatform/uno/blob/b36c12803cda613cf9d5089099bc25512a8076b3/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L3017-L3029

**Comment by darenm** [comment]
@jeromelaban I see the sanitization method in the same source file. If you can assign this to me, I'll take a shot at a PR.
