### ISSUE TITLE
[WASM] GUID is not converted to DeserializeObject.

### ISSUE THREAD

**Issue by kaki104** [unoplatform/uno#4300]
## Current behavior

Microsoft's Contoso app is being changed to Uno Platform.
Conversion works normally in UWP and Android projects, but the following phenomenon occurs only in WASM projects.
Only the id part of json is not parsed.

```
        private async void OnTest()
        {
            var result = await _contosoRepository.Customers
                .GetJObjectAsync(Guid.Parse("E7E9AF6E-503A-444B-B596-004C32DE93BF"));
            Result = result.ToString();
            Customer = result.ToObject<Customer>();
        }
```
```
        <RelativePanel>
            <TextBlock 
                x:Name="PageTitle"
                Text="Home"
                Style="{StaticResource TitleTextBlockStyle}" />

            <Button
                x:Name="TestButton"
                Content="Test"
                Command="{Binding TestCommand}"
                RelativePanel.Below="PageTitle"/>

            <TextBlock
                x:Name="TestResult"
                RelativePanel.Below="TestButton"
                Text="{Binding Result}"/>
            
            <TextBlock
                x:Name="TestCustomer"
                RelativePanel.Below="TestResult">
                <Run Text="{Binding Customer.Id}"/>
                <Run Text="{Binding Customer.FirstName}"/>
                <Run Text="{Binding Customer.LastName}"/>
                <Run Text="{Binding Customer.Company}"/>
                <Run Text="{Binding Customer.Email}"/>
            </TextBlock>

        </RelativePanel>

```
![errorwasm](https://user-images.githubusercontent.com/2314443/96419487-2ea10700-122f-11eb-9dde-2f5fe6bad794.png)

## Expected behavior

Normal output from uwp app
I want the id value to be converted to guid.
![okuwp](https://user-images.githubusercontent.com/2314443/96419893-b71fa780-122f-11eb-9b45-9d544ed05b7e.png)

## How to reproduce it (as minimally and precisely as possible)

https://github.com/kaki104/UnoContoso
After downloading the source, run the wasm project and click the test button on the home screen.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [x] Other: Prism

Nuget Package Version(s):

- Newtonsoft.Json v12.0.3
- Prism.Core v8.0.0.1850-pre
- Prism.DryIoc.Uno v8.0.0.1850-pre
- Uno.Core v2.0.0
- Uno.Microsoft.Toolkit.Uwp.UI.Controls v6.1.0-build.191.gc988bdd4ff
- Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid v6.1.0-build.191.gc988bdd4ff
- Uno.Microsoft.Xaml.Behaviors.Uwp.Managed v2.0.2-uno.79
- Uno.UI v3.1.0-dev.715
- Uno.UI.RemoteControl v3.1.0-dev715
- Uno.UI.WebAssembly v3.1.0-dev.715
- Uno.UniversalImageLoader v1.9.32
- Uno.Wasm.Bootstrap v1.3.4
- Uno.Wasm.Bootstrap.DevServer v1.3.4
- Uno.WindowsStateTriggers v1.1.1-uno.132

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. This issue is most likely not related to Uno, but rather in a difference of behavior in the libraries that are used. 

Could you try and trim down the issue to simpler solution ? Thanks!

**Comment by kaki104** [comment]
We made the tests as simple as possible. It was confirmed that the Id value is entered normally in WASM.
Let's look again for the cause of the UnoContoso project. I'll share if I find the cause.

**Comment by kaki104** [comment]
I found the cause. It seems that an error occurs in the WASM project when DeserializeObject is performed using the model in the .NetStandard project.

After moving the model to the Shared project and executing it, the result is displayed normally.

Shouldn't I create a model in the .NetStandard project and use it? Since the model is also used in the service project, should it be used after making it as Uno Class Labrary?

[UnoPrismTest.zip](https://github.com/unoplatform/uno/files/5403273/UnoPrismTest.zip)

**Comment by kaki104** [comment]
I made a Blazor app and tested it. The results were printed normally.

```

@page "/counter"
@inject HttpClient Http
@using Newtonsoft.Json
@using UnoPrismTest.Models

<h1>Counter</h1>

<p>Result: @json</p>

<p>Customer: @customer</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private string json = string.Empty;
    private string customer = string.Empty;

    private async void IncrementCount()
    {
        var response = await Http.GetAsync("https://unocontososervice20201016190520.azurewebsites.net/api/customer/e7e9af6e-503a-444b-b596-004c32de93bf");
        json = await response.Content.ReadAsStringAsync();
        var c = JsonConvert.DeserializeObject<Customer>(json);
        customer = JsonConvert.SerializeObject(c);
    }
}

```
![image](https://user-images.githubusercontent.com/2314443/96559079-89059a80-12f7-11eb-8e37-51d4d4eceeb8.png)

**Comment by jeromelaban** [comment]
Thanks. This is most likely a linker issue, here's some [documentation about this](https://github.com/unoplatform/uno/blob/fd289afdd32a1051951fbc15174cd560b0447aa1/doc/articles/using-uno-ui.md#using-the-illinker-for-webassembly) currently being added to the documenation https://github.com/unoplatform/uno/pull/4328.

**Comment by kaki104** [comment]
DeserializeObject has been successfully completed after checking and modifying using the method you provided.
Added assembly name of .NET Standard project to LinkerConfig.xml.
Thank you very much :)

```
<linker>
  <assembly fullname="UnoContoso.Wasm" />
  <assembly fullname="Uno.UI" />
  <assembly fullname="System.Core">
	<!-- This is required by JSon.NET and any expression.Compile caller -->
	<type fullname="System.Linq.Expressions*" />
  </assembly>
	<assembly fullname="UnoContoso.Models"/>
</linker>

```
