### ISSUE TITLE
XamlCodeGenerator does  generate an empty XamlApply handler when using Attached property and MarkupExtension

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#4302]
## Current behavior

Generate an empty XamlApply handler

## Expected behavior

Generate a valid XamlApply handler

## How to reproduce it (as minimally and precisely as possible)
[attached at this issue](https://github.com/unoplatform/uno/files/5401133/TUno.zip)
```xml
<Page
    x:Class="TUno.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TUno"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:l="clr-namespace:TUno.Shared"
    mc:Ignorable="d">

    <StackPanel Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
		<TextBlock Text="Hello, world!" Margin="20" FontSize="30" />
        <TextBlock Text="{l:SimpleMarkupExtension}"/>
        <TextBlock l:MarkupExtensionTestBehavior.CustomText="{l:SimpleMarkupExtension}"/>
    </StackPanel>
</Page>

```
```csharp
		new global::Windows.UI.Xaml.Controls.TextBlock
		{
			IsParsing = true
			,
			// Source ..\..\..\..\..\..\..\TUno.Shared\MainPage.xaml (Line 14:10)
		}
		.MainPage_2352af257e94b31b51e27227d91583e9_XamlApply((MainPage_2352af257e94b31b51e27227d91583e9XamlApplyExtensions.XamlApplyHandler0)(c2 => 
		{
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(c2, "file:///C:/Users/Utente/Source/Repos/TUno/TUno/TUno.Shared/MainPage.xaml");
			c2.CreationComplete();
		}
		))
```

## Workaround
**none**

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [x] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): **3.0.12** and **3.2.0-dev.93**

Affected platform(s):

- [ ] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [x] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: **16.7.6**)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
**none**

**Comment by workgroupengineering** [comment]
I found the problem. When using a shared project if using the namespace declaration `clr-namespace: TUno.Shared` code generator cannot retrieve type information. To solve the issue using:
```xaml
<Page
....
   xmlns:l="using:TUno.Shared">
</Page>
```

**Comment by jeromelaban** [comment]
Thanks for the update.
