### ISSUE TITLE
NavigationViewPaneDisplayMode.LeftCompact is incorrectly marked as not implemened

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4303]
## Current behavior

This type `NavigationViewPaneDisplayMode` should be moved to the correct location, without the `NotImplemented` attribute as it is properly implemented:

https://github.com/unoplatform/uno/blob/fe8f8a762bb95072bd186f6c61926f908131887a/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/NavigationViewPaneDisplayMode.cs#L9

## Environment

Nuget Package Version(s): 3.1

**Comment by Youssef1313** [comment]
@jeromelaban This was fixed in https://github.com/unoplatform/uno/pull/4400.
