### ISSUE TITLE
[Android] Linker failure when using Uno.UI.BaseActivity.OnRetainCustomNonConfigurationInstance

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4307]
## Current behavior

When using Uno.UI.BaseActivity::OnRetainCustomNonConfigurationInstance, the linker mail fail with the following error:

```
error XALNK7000: Mono.Linker.MarkException: Error processing method:
'Java.Lang.Object Uno.UI.BaseActivity::OnRetainCustomNonConfigurationInstance()' in assembly: 'Uno.UI.dll' 
---> Mono.Cecil.ResolutionException: Failed to resolve Java.Lang.Object AndroidX.Activity.ComponentActivity::OnRetainCustomNonConfigurationInstance() 
```

## Expected behavior

The build succeeds.

## Workaround

Add an explicit reference to the `Xamarin.AndroidX.Activity` package in the android head.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.2

## Contributor notes

The package `Xamarin.AndroidX.Activity` references should be added in the [nuspec file](https://github.com/unoplatform/uno/blob/master/build/Uno.WinUI.nuspec).

**Comment by agneszitte-nventive** [comment]
@MatFillion / @jeromelaban I can help to add the missing reference in the nuspec file if you want?

**Comment by jeromelaban** [comment]
@agneszitte-nventive of course!
