### ISSUE TITLE
Hierarchical NavigationView

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4317]
Add support for the Hierachical NavigationView

**Comment by robloo** [comment]
As you mentioned previously, this depends on ItemsRepeater support #3192. Just linking here.

**Comment by robloo** [comment]
Would this implement PaneDisplayMode = NavigationViewPaneDisplayMode.Top? That's needed for desktop scenarios now.

It's also probably best to re-port this from WinUI. There were so many changes done with refactoring and adding hierarchical support that finding the changes and ensuring they are added in the correct spot could be quite difficult. If help is needed porting this control from c++/WinRT just let me know.

**Comment by jeromelaban** [comment]
The Top mode is available, though there are some small artifacts such as the position of the selection border. What leads you to think this mode does not work ?

**Comment by robloo** [comment]
@jeromelaban I get warnings that it is unsupported during build (I am still a ways away from a successful build overall so cant test it).

Looking at the source it indeed doesn't seem implemented:

 https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/NavigationViewPaneDisplayMode.cs

**Comment by jeromelaban** [comment]
The enum was not moved, but it's used: https://github.com/unoplatform/uno/blob/61947101c5810d2a4e213540c98c65cec0b8dfe0/src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.cs#L1523

**Comment by robloo** [comment]
Yea, I noticed that this weekend when I got Android builds working and the top mode worked. I was basing the assumption that it wasn't supported off the build warning. I'll make a PR to move that enum over this week.
