### ISSUE TITLE
[Wasm] ProgressBar IsIndeterminate is not working 

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4327]
@jeromelaban, @peternary and I confirmed it's no longer working on iOS nor WASM: there is no animation, instead we just get a "horizontal bar".

@peternary is sure this was working properly in June. 

Is this a regression?

_Originally posted by @DierkDroth in https://github.com/unoplatform/uno/issues/2914#issuecomment-710102648_

**Comment by DierkDroth** [comment]
To clarify: this is iOS as well

**Comment by jeromelaban** [comment]
The `Windows.UI.Xaml.Control.ProgressBar` is not implemented completely, and only works properly when using native styles on iOS and Android. This control is being deprecated in favor of the WinUI 2.4 `Microsoft.UI.Xaml.Controls.ProgressBar` which is completely implemented in Uno.

In short, this code now works:
```xaml
<Page
    x:Class="App100.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:mux="using:Microsoft.UI.Xaml.Control"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

	<StackPanel>
		<mux:ProgressBar IsIndeterminate="true" />
	</StackPanel>
</Page>
```

**Comment by DierkDroth** [comment]
@jeromelaban @peternary confirmed this is working, thanks.

However, [this ](https://github.com/mono/SkiaSharp/pull/1458)prevents us switching our solution to WinUI 3 :-(

**Comment by jeromelaban** [comment]
@DierkDroth you do not need to switch to WinUI 3.0 to use the new ProgressBar, you only need to [use WinUI 2.x which is compatible with current UWP code](https://docs.microsoft.com/en-us/windows/apps/winui/#windows-ui-2x-library).

**Comment by DierkDroth** [comment]
Thanks @jeromelaban
