### ISSUE TITLE
Please provide a Getting Started tutorial for developers new to UWP

### ISSUE THREAD

**Issue by Cross22** [unoplatform/uno#433]
## I'm submitting a...
Documentation issue or request

## Current behavior
Getting Started link goes to a general description of the Uno Platform, not a Getting Started example. There is a link to installation instructions but those are still very high level. 

## Expected behavior
Detailed step-by-step instructions on how to get a Uno application up & running. As another example from the QuickStart guide: 
"Update to the latest nuget package named Uno.UI, make sure to check the pre-release box." <-- for UWP/C# developers this might be helpful, as a C++ engineer though I spent a considerable amount of time searching for the relevant settings (and then it still did not work). Screenshots are worth at least a 1000 words.

**Comment by weitzhandler** [comment]
Uno is essentially UWP. The advantage is that it can run on 3 more platforms.  
Really what you need to learn is [UWP](https://docs.microsoft.com/en-us/windows/uwp/get-started/), then, be aware to some features that are not yet implemented/supported on the other platforms, and avoid using them or implement them yourself.

**Comment by Cross22** [comment]
Thank you for the link. It's not so much the UWP concepts that I am concerned about, but really the details of setting up the environment so it works with Uno.

**Comment by weitzhandler** [comment]
[Whoa](https://platform.uno/docs/articles/get-started.html), I think this issue can be closed now.

**Comment by ghuntley** [comment]
Agreed, especially since the workshops from unoconf have been open-sourced -> https://github.com/unoplatform/workshops/tree/master/uno-bootcamp
