### ISSUE TITLE
Add Windows.UI.Xaml.CreateDefaultValueCallback Support

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#4347]
## What would you like to be added:

Support for [Windows.UI.Xaml.CreateDefaultValueCallback](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.createdefaultvaluecallback)

## Why is this needed:

When a property is not value-type, suppling a default value should be done using a CreateDefaultValueCallback() delegate to ensure a new instance is created for every DependencyObject.

This is used to implement SelectedItems properties in custom controls (a partial measure since read-only dependency properties are not supported in WinUI).

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

Source location:
 * [CreateDefaultValueCallback.cs](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/CreateDefaultValueCallback.cs)
 * [PropertyMetadata.cs](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/PropertyMetadata.cs)

**Comment by robloo** [comment]
I'm curious why this hasn't been implemented yet? Is there an Uno-specific work-around? Is there an architectural issue caused by the way Uno implements dependency properties?

**Comment by jeromelaban** [comment]
Thanks for the report!

There's isn't any particular issue for that member, it's just never been requested :) Yet it definitely makes sense to implement it.

**Comment by robloo** [comment]
@jeromelaban Thanks for the feedback. I can imlement this then.

Would the correct place be here in the get accessor:
https://github.com/unoplatform/uno/blob/5c53c2f37df48c9d74bd2ef34afe58bc7e43760e/src/Uno.UI/UI/Xaml/PropertyMetadata.cs#L123-L131

If an internal `_defaultValueCallback` is present (a new field I would add) that would simply be invoked and the value returned. If not, the existing `_defaultValue` field would be returned.

It looks like changing it here would be enough for all code paths but I'm no where close to familiar with this code base :)

**Comment by jeromelaban** [comment]
This could be the proper location, though we must be certain that getting that property actually invokes `CreateDefaultValueCallback` every time, and that there's no caching involved.

**Comment by dr1rrb** [comment]
Be aware that based on my lastest tests and according to the doc:

> instead of a fixed constant default value in any case where the default value of a dependency property might be **thread-bound**

the callback is invoked only once **per thread** and not for each new instance of the owning control. To my understanding that as been designed to allow usage of `DependencyObject` as default value in a multi-window app (i.e. multi UI thread / dispatcher).

**Comment by robloo** [comment]
That's interesting. I wonder how there hasn't been an issue in the past on some custom controls that use this. Perhaps because only one custom control is used at a time... Either I completely misunderstood how this behaves over the years or they changed the docs to make a bug a feature.

**Comment by Youssef1313** [comment]
Will take a look :)
