### ISSUE TITLE
False positive not implemented warnings for some APIs

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4365]
## Current behavior

When some APIs which are not implemented on NETSTD_REFERENCE are used, they are reported as warnings even though the target is WASM. Is there a way around this?

![image](https://user-images.githubusercontent.com/1075116/97086126-c6cd3080-1621-11eb-95e1-1e326b099ae8.png)

## Expected behavior

No warnings.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
If the code built is in a library, this should not happen. The analyzer checks for the parameters of the NotImplemented attribute to determine this. If it's in a library, then the situation is a bit more fuzzy.

**Comment by francoistanguay** [comment]
@Youssef1313  Do you have an open PR for this? @jeromelaban thought you might've looked at this...
