### ISSUE TITLE
Support for GuidHelper

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4366]
## What would you like to be added:

`Windows.Foundation.GuidHelper`

## Why is this needed:

UWP parity.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by pkar70** [comment]
This is very, very simple to implement, as we have System.Guid implemented.
{
 Windows.Foundation.GuidHelper.Empty => System.Guid.Empty;
 Windows.Foundation.GuidHelper.CreateNewGuid() => System.Guid.NewGuid();
 Windows.Foundation.GuidHelper.Equals(Guid, Guid) =>System.Guid.Equals(Guid, Guid);
}

:)

**Comment by MartinZikmund** [comment]
@pkar70 Agreed, just published the PR :-) .
