### ISSUE TITLE
Many CS8032 warnings due to Microsoft.CodeAnalysis

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4373]
## Current behavior

Using the latest version of Uno, the Error List shows a number of warnings related to Microsoft.CodeAnalysis:

>An instance of analyzer Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator cannot be created from C:\Users\Martin\.nuget\packages\uno.ui\3.2.0-dev.79\analyzers\dotnet\cs\Uno.UI.SourceGenerators.dll: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..

## Expected behavior

No warnings.

## How to reproduce it (as minimally and precisely as possible)

Install Uno.UI 3.2.0-dev.256 in an app and compile.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.2.0-dev.256

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Which target are you building, on which version of VS?

**Comment by MartinZikmund** [comment]
> Which target are you building, on which version of VS?

Latest stable VS, WASM target

**Comment by jeromelaban** [comment]
This looks like an older build of Uno in the error, could you make sure the latest is used ?

**Comment by jeromelaban** [comment]
Is this still a problem ?
