### ISSUE TITLE
Missing NuGet Uno.UI.Skia.Gtk & Uno.UI.Skia.Wpf v3.1.6 packages

### ISSUE THREAD

**Issue by akordowski** [unoplatform/uno#4375]
I created a brand new project via the `dotnet new unoapp -o MyApp` command. After opening the solution in VS 2019 I got the errors:

* Unable to find a stable package Uno.UI.Skia.Wpf with version (>= 3.1.6)
* Unable to find a stable package Uno.UI.Skia.Gtk with version (>= 3.1.6)

Then I checked the NuGet feeds for `Uno.UI.Skia.Wpf` and `Uno.UI.Skia.Gtk`. The version 3.1.6 for both packages is not available via NuGet. Can you provide them please?

**Comment by jeromelaban** [comment]
Thanks for the report! 

Indeed, those packages were not properly propagated to nuget.org. It's now validating and should be available shortly.

Apologies for the misconfiguration, and let us know how this goes for you!
