### ISSUE TITLE
WASM: Expander and DataGrid not working

### ISSUE THREAD

**Issue by alove-kahua** [unoplatform/uno#4377]
## Current behavior

Using an Expander and DataGrid causes the following exception:
System.InvalidOperationException: [LayoutTransformControl-17554"PART_LayoutTransformer"/PART_LayoutTransformer: Invalid measured size -Infinity,-Infinity. NaN or Infinity are invalid desired size.

## Expected behavior

Layout works correctly.

## How to reproduce it (as minimally and precisely as possible)

Fails for example in a Grid or even a StackPanel.

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition />
            <RowDefinition />
        </Grid.RowDefinitions>

        <controls:Expander />
        <controls:DataGrid Grid.Row="1" />
    </Grid>

## Workaround

None.

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by robloo** [comment]
I don't think this is only for WASM. In Android I have an a few expanders stacked on top of each other in an accordion layout. I get the same type of exception.

**Comment by carldebilly** [comment]
PR https://github.com/unoplatform/uno/pull/4453 has been merged. It could fix this issue too.

**Comment by robloo** [comment]
@alove-kahua Just note that #4453 implements the WinUI expander (Windows.UI.Xaml). You will have to switch to this implementation instead of the UWP community toolkit's version (which should be deprecated anyway).
