### ISSUE TITLE
[iOS]: Various issues with AutoSuggestBox

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#4382]
##  Current behavior
Start attached in VS and compare UWP and (incorrect) iOS behavior:
1) Text display not initialized (but is blank) on startup (as binding is activated)
2) Can't type small chars, only capital chars work
3) .TextChanged with .Reason = .UserInput is thrown right as the binding is activated -> wrong, should be .Reason = .ProgrammaticChange
4) Selecting item on drop down does not update the text display

Relates issues which I have seen in other scenarios:
- the selection drop down pops up right on start (but text display is blank)
- typing chars does not popup the drop down at all

[UnoAutoSuggestBox.zip](https://github.com/unoplatform/uno/files/5437736/UnoAutoSuggestBox.zip)

## Expected behavior
Should work like UWP

## Environment
Latest Uno packages

Affected platform(s):

- [x ] iOS (I recommend checking other platforms as well)
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ x] Visual Studio 2019 (version: latest)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by Youssef1313** [comment]
> Text display not initialized (but is blank) on startup (as binding is activated)

This one is likely to be fixed in https://github.com/unoplatform/uno/pull/6992

**Comment by DierkDroth** [comment]
Thanks for the update @Youssef1313

**Comment by DierkDroth** [comment]
I'm closing this in favour of #7778 where AutoSuggestBox still has issues.
