### ISSUE TITLE
VSIX templates extension is displayed in Tools category instead of Templates

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/uno#4393]
![image](https://user-images.githubusercontent.com/2365592/97222473-215bbd80-17d7-11eb-834b-7a96340017e4.png)

**Comment by xperiandri** [comment]
https://marketplace.visualstudio.com/items?itemName=BrushtailTechnology.xamarinforms1&ssr=false#qna

**Comment by jeromelaban** [comment]
The category of the VSIX cannot be changed once it's been set in the store. It'll stay this way for now.
