### ISSUE TITLE
CommandBar - Secondary Menu not opening

### ISSUE THREAD

**Issue by LHuss** [unoplatform/uno#4394]
## Current behavior
Clicking the ellipsis does not open the secondary menu

## Expected behavior
Secondary menu should open and display submenu on ellipsis click.

## How to reproduce it (as minimally and precisely as possible)
* Clone https://github.com/LHuss/UnoCommandBarIssues
* Build & run project
* Click ellipsis.
* Notice that button lables show up, but secondary menu does not.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.0.12

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.6.5)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
Issue to epic #1665

**Comment by kazo0** [comment]
This should now be fixed with the WinUI import of CommandBar
