### ISSUE TITLE
[iOS] CommandBar - AppBarButtons do not vertically expand to accomodate labels

### ISSUE THREAD

**Issue by LHuss** [unoplatform/uno#4397]
## Current behavior
When the secondary menu is opened and labels are shown, the labels are slightly clipped.

## Expected behavior
When opening the secondarymenu on ios, the appbarbuttons should slightly expand vertically expand so as not to clip the labels

## How to reproduce it (as minimally and precisely as possible)

```
<CommandBar Margin="12,0,0,0" Background="Gray">
    <CommandBar.PrimaryCommands>
        <AppBarButton Icon="Setting" Label="Settings"
                              />
    </CommandBar.PrimaryCommands>
    <CommandBar.SecondaryCommands>
        <AppBarButton Label="About" Name="About"
                          />
        <AppBarButton Label="Sign out" Name="SignOut"
                          />
    </CommandBar.SecondaryCommands>
</CommandBar>
```
## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.0.12

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.6.5)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
Issue to epic #1665

**Comment by kazo0** [comment]
This should be fixed now that we imported the WinUI CommandBar

![image](https://user-images.githubusercontent.com/4793020/149006257-a246b282-a0cc-406b-a575-543a054354eb.png)
