### ISSUE TITLE
Add support for UIElement.ActualSize

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4398]
## What would you like to be added:

`UIElement.ActualSize`

## Why is this needed:

UWP parity.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
@MartinZikmund in which control do you need this ? I remember you mentioning it.

**Comment by MartinZikmund** [comment]
I think it was used in `RatingControl`. It should be just equivalent of `ActualWidth` and `ActualHeight`, so it seemed like a quick addition

**Comment by jeromelaban** [comment]
Indeed it does. Thanks!
