### ISSUE TITLE
BadgeNotification for WASM & Tizen

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4404]
## What would you like to be added:

Support for Badge notification on WASM & Tizen.

## Why is this needed:

UWP parity.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
Tizen: https://docs.tizen.org/application/web/api/latest/device_api/mobile/tizen/badge.html
WASM: https://web.dev/badging-api/

**Comment by jeromelaban** [comment]
Very nice ;)
