### ISSUE TITLE
NavigationView: Loaded and ItemInvoked problem on WASM

### ISSUE THREAD

**Issue by Zodt** [unoplatform/uno#4407]
# Issue info

The loaded and ItemInvoked properties are formed incorrectly in the generated file for WASM

var ItemInvoked_ViewModel.ItemInvokedCommand_That = (this as global::Uno.UI.DataBinding.IWeakReferenceProvider).WeakReference;
						c17.ItemInvoked += (_sender,_args) => (ItemInvoked_ViewModel.ItemInvokedCommand_That.Target as ShellPage)?.ViewModel.ItemInvokedCommand();
						var Loaded_ViewModel.LoadedCommand_That = (this as global::Uno.UI.DataBinding.IWeakReferenceProvider).WeakReference;
						c17.Loaded += (_sender,_e) => (Loaded_ViewModel.LoadedCommand_That.Target as ShellPage)?.ViewModel.LoadedCommand();

## Expected behavior

Everything starts correctly on UWP

## How to reproduce it (as minimally and precisely as possible)

Create a project and add the Loaded or ItemInvoked attribute to the NavigationView  tag on the XAML page.

## Environment

Nuget Package:
- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl

Nuget Package Version(s): Last

Affected platform(s):

- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms

IDE:

- [ ] Visual Studio 2019 (version: Last)

Relevant plugins:

- [ ] Resharper (version: Last)

**Comment by jeromelaban** [comment]
Thanks for the report. There is already https://github.com/unoplatform/uno/pull/4369 being worked on to take care of https://github.com/unoplatform/uno/issues/4298. 

I'll close this one as a duplicate.
