### ISSUE TITLE
[WASM] Add support for SvgImageSource.SetSourceAsync

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#4417]
## What would you like to be added:

Implement SetSourceAsync for SvgImageSource

## Why is this needed:

Loading SVG assets at runtime permits operations like adjusting colors or sizes using string interpolation.  Since setting Stroke and Fill for Image controls is not supported, this would be a way to alter colors for SVG elements at runtime.

Included sample of desired functionality in UWP.

[LoadSvgFromString.zip](https://github.com/unoplatform/uno/files/5459865/LoadSvgFromString.zip)

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report. 

This issue is being tracked in #1982. Closing this one as a duplicate.

**Comment by davidjohnoliver** [comment]
Note: initial work on this will focus on WASM, which is the easiest target to implement.

**Comment by peternary** [comment]
Verified as working in latest
