### ISSUE TITLE
Android: ComboBox Flyout Doesn't Always Render Properly

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#4418]
## Current behavior

Opening a ComboBox repeatedly can cause rendering glitches caused by incorrect Flyout Background placement (ComboBoxItem placement seems correct).

![image](https://user-images.githubusercontent.com/17993847/97608345-9ce08900-19e8-11eb-8d1f-5035bdd200e0.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/17993847/97608635-f8127b80-19e8-11eb-8739-463228a95056.png)

## How to reproduce it (as minimally and precisely as possible)

 * Open a ComboBox on Android multiple times. 
 * Sometimes it's necessary to click between items at the beginning/end of the list before the glitch is apparent. 
 * This seems to become worse as the flyout position changes.

## Workaround

None

## Environment

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.1.6

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This issue is similar to #3357. 

/cc @davidjohnoliver

**Comment by davidjohnoliver** [comment]
@jeromelaban Not really, there's no problem with the flyout placement in #3357 , just the items, which is a `ListView` bug. On Android the `ComboBox` just uses a `StackPanel` to show the items so it's not related.
