### ISSUE TITLE
WinUI Expander

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#4425]
## What would you like to be added:

The Expander control from WinUI 2.x should be ported over as soon as the PR is merged. I know I'm getting ahead of things, slightly :)

## Why is this needed:

Uno has pre-release support for the Expander from the Windows Community Toolkit. However, this expander has never quite worked right and currently crashes on most platforms. Related issues below:

 * https://github.com/unoplatform/uno/issues/4377
 * https://github.com/unoplatform/uno/issues/3030
 * https://github.com/unoplatform/uno/issues/384

Porting over from WinUI is not only necessary for future code compatiblity, but also should hopefully provide a better foundation to debug and stabilize expander support in Uno.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

I will port this over myself as soon as the PR is merged in WinUI 2.x repo. Track it here: https://github.com/microsoft/microsoft-ui-xaml/pull/3492

**Comment by MartinZikmund** [comment]
Assigned to you 👍

**Comment by MartinZikmund** [comment]
@robloo It's in! https://github.com/microsoft/microsoft-ui-xaml/pull/3492

**Comment by robloo** [comment]
Awesome! I will open a PR today :)

**Comment by robloo** [comment]
@MartinZikmund I'll still open the PR. However, this control still appears to be WIP in a few places. We might be creating more work for ourselves porting controls over before being officially released in WinUI.

In this case, I'm hoping this solves some issues and makes the expander usable in Uno. So I would still have done this one quickly reguardless.

**Comment by MartinZikmund** [comment]
@robloo I try to track the commit numbers for each of the files, so then it should be easy to diff with the latest version :-) . And it is also cool that we have blazing fast support for new bits :-)

**Comment by robloo** [comment]
@MartinZikmund Yes, pros and cons, lol. I don't have infinite time to copy code over though so maybe if we copied code even a few weeks before release by WinUI it would be smarter :) Then we would still have support even before official release and probably get rid of needing to do 2-3 diffs and porting the changes.

> I try to track the commit numbers for each of the files

I track these as well. I'm going to actually commit a .txt file so we can start officially tracking this in the repo itself (and so we don't need to dig through commit history too). This will be needed to automate this in the future as well.

**Comment by robloo** [comment]
The Expander was made public https://github.com/microsoft/microsoft-ui-xaml/pull/4148 so WinUI considers it done.

I'm guessing you all were aware from backchannel conversations that was happening which is why you pushed Expander to completion and closed it here.
