### ISSUE TITLE
Top Level event handlers may not be generated properly

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#4429]
## Current behavior

If a layout change (like adding content) is made in the Opened event handler for a Flyout then it is not reflected properly.

## Expected behavior

UI elements added in Opened handler should be properly displayed, as in UWP

## How to reproduce it (as minimally and precisely as possible)

Launch the attached project in UWP and click the button - observe that Flyout contains the ListView.  Launch in WASM and click the button - observe that flyout is empty.

[FlyoutSize.zip](https://github.com/unoplatform/uno/files/5465881/FlyoutSize.zip)

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.2.0-dev.382
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
## Note for contributors

The issue is related to the generation of the registration code for the top-level element event handlers, which are not generated.

**Comment by peternary** [comment]
Appears working in latest
