### ISSUE TITLE
Clarify Segoe MDL2 Assets Font Family Usage

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#4435]
## What would you like to be added:

Running a previously UWP App in Uno, certain glyphs were not appearing correctly.

As a UWP-only code base, XAML such as `FontFamily="Segoe MDL2 Assets"` and code such as `FontFamily = new FontFamily("Segoe MDL2 Assets")` was throughout the source. However, even in UWP this is considered bad practice and instead UWP apps should generally use the `SymbolThemeFontFamily` -- fair enough. Source code was updated.

~This still didn't work on Android though (and likely all other platforms). It was also necessary to specially define this resource key -- and it has to be done for each head separately considering how fonts currently work in Uno:~

```xaml
<android:FontFamily
    x:Key="SymbolThemeFontFamily">ms-appx:///Assets/Fonts/uno-fluentui-assets.ttf#Symbols</android:FontFamily>
```

So pulling it all together:

 1. ~Support the `SymbolThemeFontFamily` resource key automatically in Uno. Define this in the Uno fluent styles for every head.~
 2. Modify all Uno Fluent UI styles to remove direct usage of "Segoe MDL2 Assets". This is kind-of a bug in the UWP source but within Uno it won't work correctly. (searching within https://github.com/unoplatform/uno/blob/master/src/Uno.UI.FluentTheme/themeresources.xaml returns results such as `<FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE8C1;" />`.
 3. Update the docs to clearly recommend using SymbolThemeFontFamily

## Why is this needed:

So symbol glyphs work right out-of-the-box if UWP apps correctly use `SymbolThemeFontFamily `

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything Else

For point number 2 above, it should also be possible to update the WinUI source directly.

**Comment by robloo** [comment]
As usual, as soon as I file an issue things start behaving :) It appears Uno does correctly support the SymbolThemeFontFamily. I'm not sure why it wasn't working originally but I assume it was a mistake on my part. Points 2 and 3 are still valid.

**Comment by robloo** [comment]
Note that upstream WinUI just fixed usage of the font name directly (https://github.com/microsoft/microsoft-ui-xaml/pull/3923). It is now using the symbol font resource instead. Whenever Uno applies the latest styles (likely after the Windows design refresh) this should fix the issue (except for the docs).

@MartinZikmund clarified the docs for this which may be enough: https://github.com/unoplatform/uno/commit/5aa1202ad88c9f4f57ea8cf9268af9721c06f9c4

**Comment by robloo** [comment]
@MartinZikmund Are Fluent v1 styles getting updated as well with #6374? I'm still not entirely sure how Uno organizes default control styles so that's hard for me to confirm with certainty. If so, this issue can be closed as I'm sure that PR is going to get merged.

As stated, upstream WinUI fixed all default styles and is now using `SymbolThemeFontFamily` directly (except for a few places in UI tests). Uno will pull in all of these updates at least for Fluent 2 with the big 2.6 style updates as far as I'm aware.

**Comment by Youssef1313** [comment]
Should this be closed?

**Comment by robloo** [comment]
> Should this be closed?

Yes, I think so. With your commit to fix Fluent v1 and the release of Fluent v2 I think all instances of this have been fixed!
