### ISSUE TITLE
uno cant get api request and photo and fonts

### ISSUE THREAD

**Issue by mokhtarsoholi** [unoplatform/uno#4436]
hi i am using uno platform in xmarin forms i have many problem when i use unp pls help me

1- uno font not load pls see screenshot and font in uwp is worked but in web not worked
![Screenshot (50)_LI](https://user-images.githubusercontent.com/20678483/97815144-58cbdd80-1ca1-11eb-821a-5dff606fb921.jpg)
2-photo not load in web
![Screenshot (51)](https://user-images.githubusercontent.com/20678483/97815182-9e88a600-1ca1-11eb-89e4-0d8d24ee010f.png)
![Screenshot (52)](https://user-images.githubusercontent.com/20678483/97815187-a5171d80-1ca1-11eb-9261-cd7b5e98d252.png)
3- web api rest not work in web i am using web api rest to get some data from online datbase and web api project its upload on host and i am not using local iis but i have this error
![image](https://user-images.githubusercontent.com/20678483/97815228-d2fc6200-1ca1-11eb-86cf-512d41da7b2e.png)

**Comment by jeromelaban** [comment]
Thanks for the report. Is this issue a duplicate of  https://github.com/unoplatform/uno/issues/4437 ?

**Comment by mokhtarsoholi** [comment]
yes its duplicate when publish that issue i got erorr i think its not publish
