### ISSUE TITLE
api - fonts - images not worked in uno platform xamarin for,s

### ISSUE THREAD

**Issue by mokhtarsoholi** [unoplatform/uno#4437]

**Comment by mokhtarsoholi** [comment]
hi i have some problem with uno in xamarin forms

1- fonts not work pls see the screenshots
![Screenshot (50)_LI](https://user-images.githubusercontent.com/20678483/97815289-2ff81800-1ca2-11eb-9b6a-6a47e7353753.jpg)
2-photo not work in web project
![Screenshot (51)](https://user-images.githubusercontent.com/20678483/97815297-3c7c7080-1ca2-11eb-9507-8a217526c19d.png)
![Screenshot (52)](https://user-images.githubusercontent.com/20678483/97815299-3e463400-1ca2-11eb-9ccf-aa2d6da4e28c.png)
3- web api rest not work i using online web api not local iis and my web api project its upload on host
![Screenshot (53)](https://user-images.githubusercontent.com/20678483/97815311-5918a880-1ca2-11eb-824f-8ac8aef36893.png)

**Comment by jeromelaban** [comment]
Thanks for the report.

Could you provide all the information provided in the default bug template, so we can determine the status of this issue : https://github.com/unoplatform/uno/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

**Comment by mokhtarsoholi** [comment]
this is nuget package i used
![Screenshot (54)](https://user-images.githubusercontent.com/20678483/97845105-5ef1a680-1d01-11eb-8b28-3fb6c61e78ef.png)
i use vs2019
and i upadate all of package to last vaersion

**Comment by mokhtarsoholi** [comment]
hello again i solve all of problem except 1 of them i use custom font in xamarin form with exportfont in assemblyinfo and its work in android - ios - uwp but in wasm project not worked and rtl not worked
i expect this output
![Screenshot (52)_LI](https://user-images.githubusercontent.com/20678483/97852319-d3314780-1d0b-11eb-946e-7ce4a0ec93a3.jpg)

**Comment by jeromelaban** [comment]
Fonts are currently handled differently in WebAssembly, you'll need to take a look at the documentation for this: https://github.com/unoplatform/uno/blob/master/doc/articles/features/custom-fonts.md#custom-fonts-on-webassembly
