### ISSUE TITLE
how publish wasm project

### ISSUE THREAD

**Issue by mokhtarsoholi** [unoplatform/uno#4441]
hi i create xamarin forms app and then add uno platform to solution and its work very well on local iis but when i publish it and upload to iis and run it appear error about web config pls guide me how publish project
![image](https://user-images.githubusercontent.com/20678483/97855874-adf30800-1d10-11eb-97cf-6333e6714a96.png)

**Comment by jeromelaban** [comment]
Thanks for the report. We do not have published guidance for local IIS, only to publish on Azure.

This issue is a duplicate. I'll close this issue in favor of this one: https://github.com/unoplatform/uno/issues/1423

**Comment by mokhtarsoholi** [comment]
I cant upload project on plask? Or other windows host for online using

**Comment by jeromelaban** [comment]
We do not have instructions to upload on this service. If you're willing to contribute and achieve this, you can update https://github.com/unoplatform/uno/blob/master/doc/articles/how-to-host-a-webassembly-app.md.

**Comment by mokhtarsoholi** [comment]
wasm must upload on linux host or windows host? can we upload project on linux host?

**Comment by mokhtarsoholi** [comment]
hi again i trace file and then i see web.config file has problem pls check my file this is web.config file when i searched for my error code in microsoft docs [](https://docs.microsoft.com/en-us/troubleshoot/iis/http-error-500-19-webpage) in this doc my code error is 0x8007000d so i need to Delete the malformed XML element fromthe Web.config file.


`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.web>
    <customErrors mode="Off"/>
  </system.web>

  <system.webServer>

    
    <urlCompression doStaticCompression="false" doDynamicCompression="false" dynamicCompressionBeforeCache="false" />

    <staticContent>
      <remove fileExtension=".dll" />
      <remove fileExtension=".wasm" />
      <remove fileExtension=".woff" />
      <remove fileExtension=".woff2" />
      <mimeMap fileExtension=".wasm" mimeType="application/wasm" />
      <mimeMap fileExtension=".clr" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".pdb" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
      <mimeMap fileExtension=".woff2" mimeType="application/font-woff" />

      
      <mimeMap fileExtension=".json" mimeType="application/octet-stream" />
    </staticContent>

    <rewrite>
      <rules>
        <rule name="Lookup for pre-compressed brotli file" stopProcessing="true">
          <match url="(.*)$"/>
          <conditions>
            
            <add input="{HTTP_ACCEPT_ENCODING}" pattern="br" />
            
            
            <add input="{REQUEST_URI}" pattern="^(?!/_compressed_br/)(.*)$" />

            
            <add input="{DOCUMENT_ROOT}/_compressed_br/{C:0}" matchType="IsFile" negate="false" />
          </conditions>
          <action type="Rewrite" url="/_compressed_br{C:0}" />
        </rule>

        <rule name="Lookup for pre-compressed gzip file" stopProcessing="true">
          <match url="(.*)$"/>
          <conditions>
            
            <add input="{HTTP_ACCEPT_ENCODING}" pattern="gzip" />
            
            
            <add input="{REQUEST_URI}" pattern="^(?!/_compressed_gz/)(.*)$" />
            
            
            <add input="{DOCUMENT_ROOT}/_compressed_gz/{C:0}" matchType="IsFile" negate="false" />
          </conditions>
          <action type="Rewrite" url="/_compressed_gz{C:0}" />
        </rule>
      </rules>

      <outboundRules>
        <rule name="Adjust content encoding for gzip pre-compressed files" enabled="true" stopProcessing="true">
          <match serverVariable="RESPONSE_CONTENT_ENCODING" pattern="" />
          <conditions>
            <add input="{REQUEST_URI}" pattern="/_compressed_gz/.*$" />
          </conditions>
          <action type="Rewrite" value="gzip"/>
        </rule>
        <rule name="Adjust content encoding for brotli pre-compressed files" enabled="true" stopProcessing="true">
          <match serverVariable="RESPONSE_CONTENT_ENCODING" pattern="" />
          <conditions>
            <add input="{REQUEST_URI}" pattern="/_compressed_br/.*$" />
          </conditions>
          <action type="Rewrite" value="br"/>
        </rule>
      </outboundRules>
    </rewrite>
  </system.webServer>
</configuration>`
