### ISSUE TITLE
Android Multi-Line TextBlock Incorrect Horizontal Scrolling 

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#4455]
## Current behavior

I have a TextBlock with multi-line content inside a ScrollViewer. All content can be displayed without scrollbars and none are shown. However, horizontally, it is still possible to scroll a small amount left/right causing the text to clip.

![ex](https://user-images.githubusercontent.com/17993847/97608113-4b37fe80-19e8-11eb-8ba6-865c4d3e6c92.gif)

## Expected behavior

It should not be possible to scroll left/right clipping the text to the sides.

## How to reproduce it (as minimally and precisely as possible)

 1. Add a TextBlock inside a ScrollViewer
 1. Make sure the ScrollViewer's horizontal scroll bar is disabled
 1. Add multi-line text to the TextBlock it does not need to be long enough to trigger vertical scrolling
 1. Attempt to scroll left/right horizontally on the TextBlock. It will be possible without a scrollbar visible causing the text to be clipped to the sides.

## Workaround

None found

## Environment

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.1.6

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
@dr1rrb would this have been introduced by recent scrollviewer changes ?

**Comment by dr1rrb** [comment]
Should not, it's on android while my changes was only for skia and wasm. 

BTW I see that the text is effectively a bit too large, so it make sense that the `ScrollViewer` enables its horizontal scrolling: 
![image](https://user-images.githubusercontent.com/8635919/98598192-13fb0480-22a8-11eb-862a-982330a6c04e.png)

@jeromelaban Did we changed the default font?

**Comment by robloo** [comment]
I don't see this one anymore so am closing it. It's possible it was due to nuances with a Pivot control parent as well.
