### ISSUE TITLE
error web.config when publish wasm project

### ISSUE THREAD

**Issue by mokhtarsoholi** [unoplatform/uno#4461]
hi i am develop xamarin forms app then add wasm project on this now i want publish wasm project but when publish it and upload on host erorr on web.config  when i searched for my error code in microsoft docs in this doc my code error is 0x8007000d so i need to Delete the malformed XML element fromthe Web.config file but i dont know what must delete. pls help me

web.config file contains this code : 
`
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.web>
    <customErrors mode="Off"/>
  </system.web>

  <system.webServer>

    
    <urlCompression doStaticCompression="false" doDynamicCompression="false" dynamicCompressionBeforeCache="false" />

    <staticContent>
      <remove fileExtension=".dll" />
      <remove fileExtension=".wasm" />
      <remove fileExtension=".woff" />
      <remove fileExtension=".woff2" />
      <mimeMap fileExtension=".wasm" mimeType="application/wasm" />
      <mimeMap fileExtension=".clr" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".pdb" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
      <mimeMap fileExtension=".woff2" mimeType="application/font-woff" />

      
      <mimeMap fileExtension=".json" mimeType="application/octet-stream" />
    </staticContent>

    <rewrite>
      <rules>
        <rule name="Lookup for pre-compressed brotli file" stopProcessing="true">
          <match url="(.*)$"/>
          <conditions>
            
            <add input="{HTTP_ACCEPT_ENCODING}" pattern="br" />
            
            
            <add input="{REQUEST_URI}" pattern="^(?!/_compressed_br/)(.*)$" />

            
            <add input="{DOCUMENT_ROOT}/_compressed_br/{C:0}" matchType="IsFile" negate="false" />
          </conditions>
          <action type="Rewrite" url="/_compressed_br{C:0}" />
        </rule>

        <rule name="Lookup for pre-compressed gzip file" stopProcessing="true">
          <match url="(.*)$"/>
          <conditions>
            
            <add input="{HTTP_ACCEPT_ENCODING}" pattern="gzip" />
            
            
            <add input="{REQUEST_URI}" pattern="^(?!/_compressed_gz/)(.*)$" />
            
            
            <add input="{DOCUMENT_ROOT}/_compressed_gz/{C:0}" matchType="IsFile" negate="false" />
          </conditions>
          <action type="Rewrite" url="/_compressed_gz{C:0}" />
        </rule>
      </rules>

      <outboundRules>
        <rule name="Adjust content encoding for gzip pre-compressed files" enabled="true" stopProcessing="true">
          <match serverVariable="RESPONSE_CONTENT_ENCODING" pattern="" />
          <conditions>
            <add input="{REQUEST_URI}" pattern="/_compressed_gz/.*$" />
          </conditions>
          <action type="Rewrite" value="gzip"/>
        </rule>
        <rule name="Adjust content encoding for brotli pre-compressed files" enabled="true" stopProcessing="true">
          <match serverVariable="RESPONSE_CONTENT_ENCODING" pattern="" />
          <conditions>
            <add input="{REQUEST_URI}" pattern="/_compressed_br/.*$" />
          </conditions>
          <action type="Rewrite" value="br"/>
        </rule>
      </outboundRules>
    </rewrite>
  </system.webServer>
</configuration>

`

**Comment by jeromelaban** [comment]
Thanks for the report.

This is most likely caused by some missing configuration in your IIS. Can you validate that the URL rewriter module has been installed ?
