### ISSUE TITLE
handle platform running wasm project

### ISSUE THREAD

**Issue by mokhtarsoholi** [unoplatform/uno#4462]
hi first i thanks about your perfect framework.
i develop xamarin forms application then add wasm using uno platform on that now i have a question can i manage project Behavior on each platofrm like chorm on android and chorme on windows i want do different work.
can i do?

**Comment by jeromelaban** [comment]
Thanks for your question. Could you post it on StackOverflow instead: https://stackoverflow.com/questions/tagged/uno-platform, so the community can benefit from the answer?
