### ISSUE TITLE
[WASM] Build fails if trying to use ThemeResource inside Flyout

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#4463]
## Current behavior

If a control inside a Flyout makes use of a ThemeResource WASM will fail to build.

## Expected behavior

WASM should build and resource be applied appropriately.

## How to reproduce it (as minimally and precisely as possible)

Attempt to build the attached project in both UWP and Wasm.  Notice that UWP builds and performs as expected, but WASM refuses to build.

[WasmThemeResource.zip](https://github.com/unoplatform/uno/files/5490446/WasmThemeResource.zip)

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.2.0-dev.434
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by DierkDroth** [comment]
@jeromelaban this is pretty much WASM show stopper for us.
