### ISSUE TITLE
x:Bind event to method does not generate parameters properly

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4478]
## Current behavior

When using `x:Bind` event to method for nested method (for example `x:Bind ViewModel.MyMethod`), the method's parameters are not properly generated in the `g.cs`:

```
c6.ItemClick += (_sender,_e) => (ItemClick_ViewModel_OpenAdventDay_That.Target as MainPage)?.ViewModel.OpenAdventDay();
```

The reason is that [here ](https://github.com/unoplatform/uno/blob/f943d1b45c3bd1fc14bac332282c4d731a833c70/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L3012) in the source generator, only the direct target is searched for the method, not the actual path that contains it (`eventTarget` is `ViewModel.MyMethod`):

```
targetContext.sourceType.GetMethods().FirstOrDefault(m => m.Name == eventTarget)?.Parameters.Any() ?? false;
```

## Expected behavior

The parameters should be generated.

## How to reproduce it (as minimally and precisely as possible)

Suppose the following ViewModel:

```
public class ViewModel
{
    public void MyMethod(object sender, RoutedEventArgs args) { }
}
```

On `MainPage.xaml`:

```
public MainPage
{
   ...
   
   public ViewModel Model { get; } = new ViewModel();
}
```

And following `x:Bind`:

```
<Button Click="{x:Bind ViewModel.MyMethod}" />
```

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

**Comment by enkodim** [comment]
x:Bind events to methods seems to be broken in general currently:

`public sealed partial class LoginView : Page
{
        public void Login()
        {
            ....
        }
}
`

in Page:
`<Button Click="{x:Bind Login }">LOGIN</Button>`

Generates this code:

`

.LoginView_678e59242d332951ce9daaa101dc8e5a_XamlApply((LoginView_678e59242d332951ce9daaa101dc8e5aXamlApplyExtensions.XamlApplyHandler0)(c0 => 

					{

						var Click_Login _That = (this as global::Uno.UI.DataBinding.IWeakReferenceProvider).WeakReference;

						c0.Click += (_sender,_e) => (Click_Login _That.Target as LoginView)?.Login ();

						this._component_0 = c0;
`
-note extra Click_Login, which causes build to fail

**Comment by MartinZikmund** [comment]
Thank you for the example 👍

**Comment by jeromelaban** [comment]
It feels like the space after the login is being problematic, thanks for the example!
