### ISSUE TITLE
Uno.UI doesn't work with Xamarin.Forms projects

### ISSUE THREAD

**Issue by SnowPowerCore** [unoplatform/uno#4489]
## Current behavior
Currently, if i follow [this](https://github.com/unoplatform/uno/blob/master/doc/articles/howto-use-uno-in-xamarin-forms.md) guide, controls not showing at the end. Some of them (i was able to reveal TextBlock) show after Hot Reloading. ToggleSwitch doesn't show at any try. When i click on TextBlock area, i receive NullReferenceException ([stacktrace](https://gist.github.com/SnowPowerCore/0aedaf8b3ecb3f6c7b415b31af946d46)).

## Expected behavior
All controls are visible, without Hot Reloading, inside of Xamarin.Forms project.

## How to reproduce it (as minimally and precisely as possible)
- Download XF sample project solution [.zip](https://1drv.ms/u/s!Aqlu8InmsjYZgdYakEgbRULqB1aofA?e=SuQId9);
- Follow /XamUNO project's MainPage.xaml file to edit controls;
- Launch application;
- Try to Hot Reload, you will see TextBlock appearing;
- Try to click on its area: you should receive exception;

## Workaround
`-`

## Environment
- Visual Studio 2019 16.7.7

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
- Uno.UI: v. 3.1.6;
- Xamarin.Forms: v. 4.8.0.1560;
Affected platform(s):

- [x] Xamarin.Forms

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.7.7)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by francoistanguay** [comment]
SUpport was updated to XF5 a few releases ago.
