### ISSUE TITLE
[iOS] ScrollViewer does not apply margin of its Content properly

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/uno#4500]
## Current behavior

TopMargin gets added to BottomMargin of a Textblock when inside a ScrollViewer  on iOS
![image](https://user-images.githubusercontent.com/64613932/98738937-82a69380-2376-11eb-9a2b-65a1b2cea5af.png)

## Expected behavior

The margin around the TextBlock should be even on all sides.

## How to reproduce it (as minimally and precisely as possible)

```
<Page x:Class="Repro1.MainPage"
	  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	  xmlns:local="using:Repro1"
	  xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
	  xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
	  mc:Ignorable="d">

	<Grid Background="White">
		<ScrollViewer Width="100"
					  HorizontalAlignment="Center"
					  VerticalAlignment="Center"
					  Background="Pink">

			<TextBlock Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt" 
					   TextWrapping="Wrap"
					   Margin="20,20,20,20"/>
		</ScrollViewer>
	</Grid>
</Page>
```

## Workaround

Use padding on scrollviewer instead

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.7.6)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by agneszitte-nventive** [comment]
Repro sample code (with Uno.UI v3.1.6 / or Uno.UI latest dev)
Having a ScrollViewer inside a panel with a Margin display the issue.

```
<Grid Background="LightBlue">
		<ScrollViewer>
			<!-- Same issue if we replace the StackPanel with a Grid/Border here -->
			<!-- Same issue also with or without BorderBrush and BorderThickness -->
			<StackPanel Background="White"
						BorderThickness="1"
						BorderBrush="DeepPink"
						VerticalAlignment="Top"
						Margin="14,20">
				<Button Content="Test"
						HorizontalAlignment="Stretch" />
			</StackPanel>
		</ScrollViewer>
	</Grid>
```

Seems like any element with a Margin inside a ScrollViewer will add some extra space at the bottom

**Comment by agneszitte-nventive** [comment]
Issue still happening with latest Uno.UI stable 4.0.11 and latest dev 4.1.0-dev.305
![image](https://user-images.githubusercontent.com/16295702/149235780-e8171a88-e628-40cc-bdee-f5ec968d4639.png)

Investigating

**Comment by agneszitte-nventive** [comment]
Debugging is still in progress.
While adding more UI tests for this issue, I also noticed that in some scenarios for iOS the margin will double in size or not be present at all. 
![image](https://user-images.githubusercontent.com/16295702/149823913-ce799f67-9ba0-4517-840f-42852fa7df31.png)
![image](https://user-images.githubusercontent.com/16295702/149823952-ebf7f403-a77f-45d4-9516-993e07f2ffa0.png)
![image](https://user-images.githubusercontent.com/16295702/149823790-8ea9bffd-4b68-43dc-9097-9dff6b84e618.png)

For WASM, in some scenarios we can see similar issues
![image](https://user-images.githubusercontent.com/16295702/149821299-70f9b535-907b-4793-bc7d-8998264572ea.png)
![image](https://user-images.githubusercontent.com/16295702/149821360-e5c14fa5-09c5-4a9e-b059-83924f644a0d.png)

I will also double-check the others platforms.
(cc @jeromelaban)
