### ISSUE TITLE
Binding with ElementName is not working from within a DataTemplate 

### ISSUE THREAD

**Issue by DerekRaven** [unoplatform/uno#4505]
## Current behavior

Unable to bind using ElementName within a DataTemplate to a source that exists within the page

UWP result (working):
![image](https://user-images.githubusercontent.com/12374297/98860977-7d0e8380-2432-11eb-8122-a05518566978.png)

iOS result (identical result on AND)
![image](https://user-images.githubusercontent.com/12374297/98861029-9adbe880-2432-11eb-84fd-ddb925dc1411.png)

## Expected behavior

Binding source and path is valid on AND/iOS

## How to reproduce it (as minimally and precisely as possible)

[ElementNameBindingSample.zip](https://github.com/unoplatform/uno/files/5526581/ElementNameBindingSample.zip)

Snippet of template and page content:
````
<DataTemplate x:Key="NumberItemTemplate">
	<StackPanel>
		<TextBlock Text="{Binding}" />
		<TextBlock>
			<Run Text="Parent =" />
			<Run Text="{Binding Path=DataContext, ElementName=NumbersListView}" />
		</TextBlock>
	</StackPanel>
</DataTemplate>

<StackPanel Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
	<TextBlock FontSize="20"
		          Margin="20"
			  TextWrapping="Wrap">
		<Run Text="DataContext =" />
		<Run Text="{Binding Path=DataContext, ElementName=NumbersListView}" />
	</TextBlock>
		
	<ListView x:Name="NumbersListView" 
			ItemsSource="{Binding Numbers}"
			ItemTemplate="{StaticResource NumberItemTemplate}" />
</StackPanel>
````

## Workaround

Avoid binding to ElementName. Ex: Include reference to desired source in the list item's model 

## Environment

Nuget Package: Uno.UI 3.2.0

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.5.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
@davidjohnoliver it's this what you fixed ?

**Comment by agneszitte-nventive** [comment]
Also if it's not already fixed, WASM should be tested for this issue.

**Comment by davidjohnoliver** [comment]
@jeromelaban @agneszitte-nventive This is a separate issue, because it occurs on Android as well. (#4495 was very iOS-specific)
