### ISSUE TITLE
[Enhancement][Spec] x:Command

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#4508]
## What would you like to be added:
Simplify the use of commands without the need to define a property, through conventions chosen by the developer.

#### XAML
```xaml
  <Button Content="Do" Command={x:Command ViewModel.Do} CommandParameter="true"/>
```

#### Code-Behind
```csharp
  public MyViewModel ViewModel { get=>(MyViewModel)DataContext; }
```

#### ViewModel
```csharp
  partial class MyViewModel 
  {
      bool CanDo(object parameter)
      {
           var result = false;
           ....
           return result;
      }

      void Do(object paramter)
      {
           ...
      }

     void DoException(object sender, ExcutionExcetionArg arg )
     {
          if (arg.Exception is FatalException  fatal )
          {
             .....
             arg.Cancel = true;
          }
          else if ( arg.RaetryCount < 3 )
          {
             // LOG 
          }
          else
          {
              arg.Cancel = true;
          }
     }
  }
```
in the example above:
 - when the button is pressed, the Do method of MyViewModel is invoked. 
 - If an exception is raised during the execution of the do method, the DoException method is called. 
 - The enabling status of the Button is controlled by the CanDo method.
 - The CanDo and DoException methods are optional. 
 - Name of methods (Do,CanDo,DoException  ) is defined by the conventions chosen by the developer.

### Conventions:

Conventions are attributes that can be defined at the method, class, and assembly level

#### List of Conventions

| Name | Description | Level | Multiuse
:--|:--|:--|:--
| CammandName | defines the name of the property generated by the source code generator, the default is the same passed as x:Command with the Command postfix | Execute method, class, assembly | false
| CommandExecutteName |  defines the name of the method invoked by the Command execution, the default is the same passed as x:Command  | class , assembly | false
| CommandCanExecutteName |  defines the name of the method that triggers the execution of the command, the default value is the same as passed as x:Command with prefix Can | class , assembly | false
| CommandExceptionName | defines the name of the method that the command invokes if an exception occurs during the execution of the execute method, the default value is the same passed as x:Command suffixed with Exception | class , assembly | false
| CommandAllowsMultipleExecutions | if it is false, the multiple execution of the command is disabled. | Execute method, class , assembly | false
| CommnadContinueOnCapturedContext | If set to true continue on captured context; this will ensure that the Synchronization Context returns to the calling thread. If set to false continue on a different context; this will allow the Synchronization Context to continue on a different thread | Execute method , class , assembly | false
| DependsOn | If the class in which the CanExecute method is defined is a subclass of INotifyPropertyChanged, it indicates the name of the property that triggers the validation of the CanExecute method | CanExecute method | true

#### Execute:

```csharp 
  void CommandExecutteName (object parameter) 
  {
  }
```
or

```csharp 
  Task CommandExecutteName (object parameter) 
  {
     ....
  }
```
or

```csharp 
  ValueTask CommandExecutteName (object parameter) 
  {
    ...
  }
```

#### CanExecute:

```csharp 
  bool CommandCanExecutteName (object parameter) 
  {
     ...
  }
```

#### CommandException:

```csharp 
  void CommandExceptionName(object sender, ExcutionExcetionArg arg) 
  {
     ...
  }
```

## How to works:
The source code generator generates a property with the name defined by the CommandName convention that returns ICommand and gives it control in the XamlApply method.

### Example of code generation:
MyViewModel.hash.cs
```csharp    
  internal ICommand DoCommand { get=> new Command(Do,CanDo,DoException );  }
```
Mypage.hash.cs
```csharp    
  b1.Command = this.ViewModel.Command
```
### Why generate a property in ViewModel?
Because it allows you to access private methods without using reflection.

## Why is this needed:
Speed up the implementation of commands in the ViewModel

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the suggestion!

As a general rule, we do not add features that are not part of WinUI, but this would be something that will interest the WinUI team [on their repository](https://github.com/Microsoft/microsoft-ui-xaml).

**Comment by workgroupengineering** [comment]
Thanks for the reply,
Sorry, I didn't know your policies.
I close the issue.
