### ISSUE TITLE
[WASM] TextBox placeholder text is aligned incorrectly

### ISSUE THREAD

**Issue by ebariche** [unoplatform/uno#4511]
Seems to occur on larger displays.

![image](https://user-images.githubusercontent.com/33458222/98994528-f32bec80-24fd-11eb-8442-d51eb7312736.png)

**Comment by jeromelaban** [comment]
Fixed by #4982

**Comment by sakshi173** [comment]
Verified and Issue is Fixed
![Gallery Textbox](https://user-images.githubusercontent.com/74563602/105551383-a9ffd200-5cd0-11eb-8c2c-a069a94d2a5b.png)
