### ISSUE TITLE
Net5 Lozalization does not work 

### ISSUE THREAD

**Issue by iosub** [unoplatform/uno#4514]
changing the Culture does not work on Net5
 string Lan = "es-ES";
            CultureInfo.CurrentUICulture = new CultureInfo(Lan);
            CultureInfo.CurrentCulture = new CultureInfo(Lan);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(Lan);
            Thread.CurrentThread.CurrentCulture = new CultureInfo(Lan);

it allways display in IV Format so the DateFormat  does not change and the Resource is allways in EN

Use the project included, run in Net2
Steps to reproduce
![Net2](https://user-images.githubusercontent.com/1330995/99027377-5acd5080-256d-11eb-86fe-1f18069f2411.gif)

Now Change to Net5
![Ne5](https://user-images.githubusercontent.com/1330995/99027422-789ab580-256d-11eb-859c-ca1fb85ba22d.gif)

I have add a Sample Proyect 
[App1.zip](https://github.com/unoplatform/Uno.Wasm.Bootstrap/files/5534690/App1.zip)

**Comment by jeromelaban** [comment]
Thanks for the issue !

This is not known, we'll look into it!

**Comment by iosub** [comment]
hi,

I have found a way to made localization to work

I have add on wasm 
`<WasmShellEnableNetCoreICU>true</WasmShellEnableNetCoreICU>`
and in the LinkerConfig
` <assembly fullname=" System.Globalization" />`

now the localization works

Uno.UI.WebAssembly ver 3.4.0-dev.131
Uno.Wasm.Bootstrap 2.0.0-dev.97

**Comment by jeromelaban** [comment]
Indeed it works, but it creates a memory corruption, see https://github.com/dotnet/runtime/issues/45224.

**Comment by iosub** [comment]
Hi, any update on this?

**Comment by jeromelaban** [comment]
It should work a lot better with the uno bootstrapper 2.0.0-dev.115. Can you try and let us know ? You should not  need `<WasmShellEnableNetCoreICU>true</WasmShellEnableNetCoreICU>` anymore.

**Comment by iosub** [comment]
I have just try it, and now it works without adding `<WasmShellEnableNetCoreICU>true</WasmShellEnableNetCoreICU>`

and `<assembly fullname=" System.Globalization" />`

Great!

**Comment by jeromelaban** [comment]
Excellent! I'll this issue then as it was fixed by https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/314
