### ISSUE TITLE
using <WasmPWAManifestFile> modifies paths in project's manifest.json, producing undesired paths in index.html

### ISSUE THREAD

**Issue by baskren** [unoplatform/uno#4519]
## Current behavior

 I have WASM app for which I want to setup as a WPA.  To do this, I have the following settings in that project's `.csproj`:

```xml
    <WasmShellIndexHtmlPath>$(MSBuildThisFileDirectory)\wwwroot\index.html</WasmShellIndexHtmlPath>
    <WasmPWAManifestFile>manifest.json</WasmPWAManifestFile>
```

The `manifest.json` file is in the project root folder.  Part of the content of that file (before compiling) is:

``` json
   ...
  "icons": [
      ...
    {
      "src": "../icons/1024.png",
      "sizes": "1024x1024",
      "type": "image/png"
    },
      ...
   ],
   ...
```

Which, upon compiling, produces the following lines in the `<head>` of `myproject.wasm/bin/release/netstandard2.0/dis/index.html`

```html
<meta name="apple-mobile-web-app-capable" content="yes">
<link rel="apple-touch-icon" href="./package_ecda50a444fe007bd3195064d10f820dfeda9004/../icons/1024.png" />
```

which, upon first glance, appears to be exactly what I want to happen.  However, when looking again at the `manifest.json` file, its contents have been changed as a result of compilation:

``` json
   ...
  "icons": [
      ...
    {
      "src": "package_ecda50a444fe007bd3195064d10f820dfeda9004/../icons/1024.png",
      "sizes": "1024x1024",
      "type": "image/png"
    },
      ...
   ],
   ...
```
This behavior is undesirable because, if I do not manually undo the changes to `manifest.json`, more changes will accumulate upon each recompile.  For example, at the next recompile,  `myproject.wasm/bin/release/netstandard2.0/dis/index.html` will have the following line:

```html
<meta name="apple-mobile-web-app-capable" content="yes">
<link rel="apple-touch-icon" href="./package_e11a60e979122979c2c9d5b53e5869a635db73d1/package_ecda50a444fe007bd3195064d10f820dfeda9004/../icons/1024.png" />
```

... and `manifest.json` will have the following modifications:

``` json
   ...
  "icons": [
      ...
    {
      "src": "package_e11a60e979122979c2c9d5b53e5869a635db73d1/package_ecda50a444fe007bd3195064d10f820dfeda9004/../icons/1024.png",
      "sizes": "1024x1024",
      "type": "image/png"
    },
      ...
   ],
   ...
```

## Expected behavior

Compiling the WASM project does not modify the developer's `manifest.json` file in the project.

### demo project: 

https://github.com/baskren/Uno.Wasm.manifest.json_pathGenIssue

### steps to reproduce

1. Clone demo project
2. Examine paths in `icons` list in `manifest.json` in WASM project's root folder
2. Set build target to `ProgWebApp.Wasm`
3. Build
4. Note changes to paths in `icons` list in `manifest.json` in WASM project's root folder. 
5. Examine `href` path in `apple-touch-icon` link in `ProgWebApp.Wasm/bin/debug/netstandard2.0/dist/index.html`.
6. Rebuild 
7. Note cumulative changes to paths in `icons` list in `manifest.json` in WASM project's root folder. 
8. Note cumulative change to `href` path in `apple-touch-icon` link in `ProgWebApp.Wasm/bin/debug/netstandard2.0/dist/index.html` results in broken link.

## Workaround

Manually edit out changes to `manifest.json` after every compilation.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: Version 16.8.1)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report!

 Indeed, that's not a proper behavior, the modified file is not the right one in the bootstraper, most likely [in this method](https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/6ed96d146c70bd1a325eb4f430aa4c62b6e00ebb/src/Uno.Wasm.Bootstrap/ShellTask.cs#L1649).

**Comment by baskren** [comment]
thanks @jeromelaban .  I'll move the issue to Uno.Wasm.bootstrap.

**Comment by jeromelaban** [comment]
No need to move it, here is fine :)
