### ISSUE TITLE
Start App on Linux (Raspbian OS) not working

### ISSUE THREAD

**Issue by raphibolliger** [unoplatform/uno#4524]
## Current behavior

If I create a fresh Uno App on my Raspberry PI I can build it but then it always shows the following Exception:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at Uno.UI.Runtime.Skia.GtkHost.Run()
   at MyUnoApp.Skia.Gtk.Program.Main(String[] args) in /home/pi/Desktop/MyUnoApp/MyUnoApp.Skia.Gtk/Program.cs:line 19
```

## Expected behavior

App should start.

I know that it is not a Ubuntu installation. But maybe anyone can help with a little advice to start Uno Platform on a Raspberry PI.

## How to reproduce it (as minimally and precisely as possible)

I followed this steps: https://github.com/unoplatform/uno/blob/master/doc/articles/get-started-with-linux.md#setting-up-for-linux
GTK is installed. I have no further ideas how to solve this issue.
This little tutorial shows only the steps for Ubuntu. I tryed it on a Raspberry PI with Raspbian OS. This is a Debian and not Ubuntu system. Maybe it could be the problem.

## Environment

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [x] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )
- [x] Text Editor and Console

## Anything else we need to know?
Maybe it's just a problem of Raspbian OS. But at the moment I can not see the difference or what is missing on my Raspbian installation due to a Ubuntu installation.

**Comment by jeromelaban** [comment]
Thanks for the report! 

The documentation is meant for Ubuntu and we're probably missing steps for raspbian.

Can you try running this :
```
sudo apt-get install libgtk-3-dev
```

And see if it runs better ?

**Comment by raphibolliger** [comment]
Also installed this. Sorry I forgot to mention this in my initial issue description.
But I receive also the same Exception when I run the app with `dotnet run`

**Comment by jeromelaban** [comment]
Thanks. What's the output of `whereis libgdk-3.so.0` ?

**Comment by raphibolliger** [comment]
Output: libgdk-3.so: /usr/lib/i386-linux-gnu/libgdk-3.so.0 /usr/lib/i386-linux-gnu/libgdk-3.so

**Comment by microhobby** [comment]
@raphibolliger As long as I know Raspbian runs Linux ARM. Are you sure that the command was executed in Raspbian? I don't have a Raspberry Pi available on my desk right now but I have a Toradex Verdin (ARM64). And the output is:

```
libgdk-3.so: /usr/lib/aarch64-linux-gnu/libgdk-3.so.0
```

Saw the `aarch64` on the path is the expected for my ARM64 hardware, the `i386` (old x86 32bit) is not the architecture expected for libraries on Raspbian. Maybe you are installing the packages for the wrong architecture? 🤷‍♂️

**Comment by jeromelaban** [comment]
aarch64 could be an issue indeed, but it would be odd that apt were to install for a different arch. 

GtkSharp loads up those dlls here:
https://github.com/GtkSharp/GtkSharp/blob/bc3a55f71b2850032ed3f592a382bb9a4783be7d/Source/Libs/Shared/GLibrary.cs#L59

Which in turns uses this:
https://github.com/GtkSharp/GtkSharp/blob/7dbde29178d7d58b4f2d0a11a54f05704110c4c7/Source/Libs/Shared/FuncLoader.cs#L77

Do any other Gtk app run on your device ?

**Comment by radutomy** [comment]
Working on my RPi 3 - latest version Raspbian OS 32 bit.

`whereis libgdk-3.so.0`
`libgdk-3.so: usr/lib/arm-linux-gnueabihf/libgdk-3.so /usr/lib-arm-linux-gnueabihf/libgdk-3.so.0`

![image](https://user-images.githubusercontent.com/454451/100021211-0a5dba80-2dd9-11eb-83d9-df3eb0e421f9.png)

**Comment by GF-Huang** [comment]
See this please #4840

**Comment by MartinZikmund** [comment]
@raphibolliger Is this still not working for you?
