### ISSUE TITLE
Uno 3.2 Code Generation with FontIcon

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#4528]
## Current behavior

After upgrading to Uno 3.2 an app would no longer compile. The XAML code generator is now converting:

```xaml
<PivotItem.Header>
  <FontIcon
    Glyph="&#xE76D;"
    Width="109" />
</PivotItem.Header>
```

Into:

```csharp
c20.Header = (Windows.UI.Xaml.Controls.FontIcon)((global::Windows.UI.Xaml.Markup.IMarkupExtensionOverrides)(new global::Microsoft.Toolkit.Uwp.UI.Extensions.FontIconExtension { Glyph = ""/* string/string, , FontIcon/Glyph */, Width = 109d/* double/, 109, FontIcon/Width */ })).ProvideValue();
global::Uno.UI.FrameworkElementHelper.SetBaseUri(c20, "file:///...Button.xaml");
```

The error is:

![image](https://user-images.githubusercontent.com/17993847/99194687-fb2e9b00-274e-11eb-8444-8c34692fba9f.png)

## Expected behavior

Why is the Windows community toolkit being used here? I do pull that NuGet into the app for DataGrid and Expander but it shouldn't be used to construct a FontIcon. This appears to be an issue resolving types.

It should just instantiate a normal FontIcon setting the Width property available in all FrameworkElement derived classes.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.2.0

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE: 

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (Version 16.7.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
**Note for contributors:** Most likely an unwanted side-effect of this PR: https://github.com/unoplatform/uno/pull/4355

**Comment by robloo** [comment]
@workgroupengineering Is this something you can look at since its related to your PR? 

First, I wonder why this logic is applicable here? Extension methods shouldn't be involved in this case.

If this logic is still needed, I think we should match first by exact name. Only if there are no exact matches will it consider matched with/without Extension in the name.

**Comment by workgroupengineering** [comment]
Hi, you shouldn't be concerned because FontIcon is a control. I'll check as soon as possible.

**Comment by davidjohnoliver** [comment]
No worries @workgroupengineering , I'll take a look at this issue so we can get a hotfix out asap. :)

**Comment by robloo** [comment]
@davidjohnoliver Thanks! Confirmed this is now fixed.
