### ISSUE TITLE
Getting-Started-Tutorial-2 bugTracker project android exception

### ISSUE THREAD

**Issue by jzlhll** [unoplatform/uno#4530]
E/AndroidRuntime( 8681): Process: BugTracker.BugTracker, PID: 8681
E/AndroidRuntime( 8681): java.lang.UnsatisfiedLinkError: dlopen failed: library "libmonosgen-2.0.so" not found
E/AndroidRuntime( 8681): 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
E/AndroidRuntime( 8681): 	at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime( 8681): 	at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:99)
E/AndroidRuntime( 8681): 	at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:48)
E/AndroidRuntime( 8681): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5338)
E/AndroidRuntime( 8681): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4912)
E/AndroidRuntime( 8681): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4852)
E/AndroidRuntime( 8681): 	at android.app.ActivityThread.access$1500(ActivityThread.java:178)
E/AndroidRuntime( 8681): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1531)
E/AndroidRuntime( 8681): 	at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime( 8681): 	at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime( 8681): 	at android.app.ActivityThread.main(ActivityThread.java:5650)
E/AndroidRuntime( 8681): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8681): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 8681): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
E/AndroidRuntime( 8681): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

## How to reproduce it (as minimally and precisely as possible)

Just build and run the demo.
 
Run on android studio for mac. And the real android device.

**Comment by jeromelaban** [comment]
Thanks, this is generally caused by a Xamarin.Android error. 

Can you try the following (uninstall the app on the device/simulator before trying):
- Deleting the bin/obj folders, restart visual studio and try deploying again ?
- If it still does not work, can you try disabling the "Shared runtime" or "Fast Deploy" in the Xamarin.Android project ?
