### ISSUE TITLE
Some tests of TabView are not passing

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#4558]
## Current behavior
Some tests of `TabViewTests` has been disbaled

## Expected behavior
🙃

## How to reproduce it (as minimally and precisely as possible)
Enable tests

## Workaround
Do nothing

## Environment
Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.3
Affected platform(s): 
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
Indeed 😂😂😂

![image](https://user-images.githubusercontent.com/1075116/99811052-e8e4a080-2b44-11eb-95a5-4ccfa6e16e5e.png)

**Comment by MartinZikmund** [comment]
Closing in favor of #4255
