### ISSUE TITLE
Update and improve Working with Themes doc

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#4568]
## On which page?
https://github.com/unoplatform/uno/blob/master/doc/articles/features/working-with-themes.md

## What's wrong?
 - information is out of date, doesn't reflect improvements/fixes in Uno 3.0
 - information is confusing ("As in UWP, the default theme is Dark, but in the case of Uno we use Light for all supported systems, as that is the default on all except Windows." - wut (possibly this is a confusion between the Default theme in a ResourceDictionary, vs the 'default theme' from a user perspective?))

**Comment by MartinZikmund** [comment]
Closing in favor of #11544
