### ISSUE TITLE
[WASM] Cannot build if using SkiaSharp

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#4571]
## Current behavior

Versions of Uno.Wasm.Bootstrap later than 1.4 will not build if using SkiaSharp

Issue had been logged previously here: https://github.com/unoplatform/uno/issues/4150

## Expected behavior

Should be able to build with SkiaSharp

## How to reproduce it (as minimally and precisely as possible)

Attempt to build a project using Uno.Wasm.SkiaSharp with Uno.Wasm.Bootstrap > 1.4

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
There are currently no significant changes in Uno bootstrapper over 1.4 and 1.5 (those are not marked stable), you can continue using the 1.3.5 bootstrapper.

The bootstrapper 2.0 updates are including net5 changes, which are currently being worked on.

**Comment by peternary** [comment]
Is there any ETA or workaround for being able to use SkiaSharp and net5?

**Comment by jeromelaban** [comment]
Not at this point. 

We continue working to adding features and support for .NET 5, we'll let you know once it's progressed to add support for Skia.

**Comment by peternary** [comment]
Appears working in latest
