### ISSUE TITLE
Simple NumberBox Header fails to show up

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4572]
## Current behavior

The NumberBox header fails to show up in the following example:

```
        <winui:NumberBox
            HorizontalAlignment="Stretch"
            Header="Test"
            Maximum="28"
            Minimum="22"
            SpinButtonPlacementMode="Inline"
            Value="{x:Bind ViewModel.AdventLength}" />
```

## Expected behavior

Should show up

## How to reproduce it (as minimally and precisely as possible)

See above

## Workaround

-

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Didn't you make a change for this recently ?
