### ISSUE TITLE
Can't build UWP with Uno Platform 3.3

### ISSUE THREAD

**Issue by stefanolson** [unoplatform/uno#4573]
## Current behavior

Can't build UWP with Uno 3.3. After updating to the 3.3 templates and creating a new project and asked that I want to install a whole heap of things to visual studio which I did.  At some point after that it's no longer building the UWP target in visual studio

## Expected behavior

Should build

## How to reproduce it (as minimally and precisely as possible)

Create a new project. Build. Error:
".nuget\packages\microsoft.net.uwpcoreruntimesdk\2.2.9\tools\CoreRuntime\Microsoft.Net.CoreRuntime.targets(136,5): error MSB3774: Could not find SDK "Microsoft.VCLibs, Version=14.0"."

## Workaround

None.  Attempted to repair visual studio as suggested here: https://github.com/microsoft/microsoft-ui-xaml/issues/3620#issuecomment-729799877. But no different :-(

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [X] Windows
- [X] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.8.2 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. 

How are your creating the templates ? Through the vsix or the dotnet new experience ?

**Comment by stefanolson** [comment]
vsix in Visual Studio create new project

**Comment by jeromelaban** [comment]
Does building a standard UWP project work? If so, could you provide the binlog as well ?

**Comment by stefanolson** [comment]
Just tried.  Sadly now building UWP is completely broken :-(  Not even a brand-new app will build. Wonder whether this was to do with installing visual studio 16.9 preview. I did manage to run a Uno 3.3 UWP app yesterday.

**Comment by stefanolson** [comment]
I've enclosed the log for a just a plain UWP app (to avoid all the other Uno projects confusing things).  But does look like another visual studio rather than Uno issue :-(
[msbuild.zip](https://github.com/unoplatform/uno/files/5570700/msbuild.zip)

**Comment by jeromelaban** [comment]
Yes indeed, if an UWP app does not build, there's not much Uno can do... That being said, this library is part of the WinUI 3.0 Preview 3, if I'm not mistaken. Have you installed it (or not) ?

**Comment by stefanolson** [comment]
I think I installed an older version of the Win Ui Preview. I'll try and update to preview 3 in case it helps. Thanks.
