### ISSUE TITLE
Can't build non-UWP with Uno 3.3

### ISSUE THREAD

**Issue by stefanolson** [unoplatform/uno#4574]
## Current behavior

Building any target except UWP has an error related to the source generation task.

## Expected behavior

Should build

## How to reproduce it (as minimally and precisely as possible)

Create new project. Build. Following errrors:
"Build started...
1>------ Build started: Project: UnoApp2.Skia.Wpf, Configuration: Debug Any CPU ------
2>------ Build started: Project: UnoApp2.Droid, Configuration: Debug Any CPU ------
3>------ Skipped Build: Project: UnoApp2.iOS, Configuration: Debug iPhoneSimulator ------
3>Project not selected to build for this solution configuration 
4>------ Build started: Project: UnoApp2.UWP, Configuration: Debug x86 ------
5>------ Build started: Project: UnoApp2.Wasm, Configuration: Debug Any CPU ------
6>------ Skipped Build: Project: UnoApp2.macOS, Configuration: Debug iPhoneSimulator ------
6>Project not selected to build for this solution configuration 
7>------ Build started: Project: UnoApp2.Skia.Gtk, Configuration: Debug Any CPU ------
8>------ Build started: Project: UnoApp2.Skia.Tizen, Configuration: Debug Any CPU ------
7>C:\temp\UnoApp2\UnoApp2\UnoApp2.Skia.Gtk\UnoApp2.Skia.Gtk.csproj : warning NU1701: Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
1>C:\Users\stefa\.nuget\packages\uno.sourcegenerationtasks\3.0.0-dev.18\build\netstandard1.0\Uno.SourceGenerationTasks.targets(134,2): error MSB4062: The "Uno.SourceGeneratorTasks.SourceGenerationTask_vde509e56d03942e472a27a2cc0dea77fdf221ebf" task could not be loaded from the assembly C:\Users\stefa\.nuget\packages\uno.sourcegenerationtasks\3.0.0-dev.18\build\netstandard1.0\..\Dev15.0\netcoreapp3.1\Uno.SourceGeneratorTasks.vde509e56d03942e472a27a2cc0dea77fdf221ebf.dll. Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
1>Done building project "UnoApp2.Skia.Wpf.csproj" -- FAILED.
9>------ Build started: Project: UnoApp2.Skia.Wpf.Host, Configuration: Debug Any CPU ------
7>C:\Users\stefa\.nuget\packages\uno.sourcegenerationtasks\3.0.0-dev.18\build\netstandard1.0\Uno.SourceGenerationTasks.targets(134,2): error MSB4062: The "Uno.SourceGeneratorTasks.SourceGenerationTask_vde509e56d03942e472a27a2cc0dea77fdf221ebf" task could not be loaded from the assembly C:\Users\stefa\.nuget\packages\uno.sourcegenerationtasks\3.0.0-dev.18\build\netstandard1.0\..\Dev15.0\netcoreapp3.1\Uno.SourceGeneratorTasks.vde509e56d03942e472a27a2cc0dea77fdf221ebf.dll. Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
7>Done building project "UnoApp2.Skia.Gtk.csproj" -- FAILED.
8>C:\Users\stefa\.nuget\packages\uno.sourcegenerationtasks\3.0.0-dev.18\build\netstandard1.0\Uno.SourceGenerationTasks.targets(134,2): error MSB4062: The "Uno.SourceGeneratorTasks.SourceGenerationTask_vde509e56d03942e472a27a2cc0dea77fdf221ebf" task could not be loaded from the assembly C:\Users\stefa\.nuget\packages\uno.sourcegenerationtasks\3.0.0-dev.18\build\netstandard1.0\..\Dev15.0\netcoreapp3.1\Uno.SourceGeneratorTasks.vde509e56d03942e472a27a2cc0dea77fdf221ebf.dll. Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
8>Done building project "UnoApp2.Skia.Tizen.csproj" -- FAILED.
9>C:\temp\UnoApp2\UnoApp2\UnoApp2.Skia.Wpf.Host\UnoApp2.Skia.Wpf.Host.csproj : warning NU1701: Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
5>C:\Users\stefa\.nuget\packages\uno.sourcegenerationtasks\3.0.0-dev.18\build\netstandard1.0\Uno.SourceGenerationTasks.targets(134,2): error MSB4062: The "Uno.SourceGeneratorTasks.SourceGenerationTask_vde509e56d03942e472a27a2cc0dea77fdf221ebf" task could not be loaded from the assembly C:\Users\stefa\.nuget\packages\uno.sourcegenerationtasks\3.0.0-dev.18\build\netstandard1.0\..\Dev15.0\netcoreapp3.1\Uno.SourceGeneratorTasks.vde509e56d03942e472a27a2cc0dea77fdf221ebf.dll. Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
5>Done building project "UnoApp2.Wasm.csproj" -- FAILED.
9>CSC : error CS0006: Metadata file 'C:\temp\UnoApp2\UnoApp2\UnoApp2.Skia.Wpf\bin\Debug\netstandard2.0\UnoApp2.Skia.Wpf.dll' could not be found
9>Done building project "UnoApp2.Skia.Wpf.Host_n1v1tynf_wpftmp.csproj" -- FAILED.
9>Done building project "UnoApp2.Skia.Wpf.Host.csproj" -- FAILED."

## Workaround

None. Have reinstalled the Uno platform template and created another new project and have the same problem.

## Environment

Nuget Package Version(s):

Affected platform(s):

- [X] iOS
- [X] Android
- [X ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [X ] macOS
- [X ] Skia
  - [X ] WPF
  - [X ] GTK (Linux)
  - [X ] Tizen
- [ ] Windows
- [X ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.8.2 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thank you for the report. 

Could you provide the `msbuild.binlog` file created when running `msbuild /r /bl yousolution.sln` ? Thanks!

**Comment by stefanolson** [comment]
Sure. Enclosed
[msbuild.zip](https://github.com/unoplatform/uno/files/5570489/msbuild.zip)

**Comment by jeromelaban** [comment]
For some reason, your machine has `DOTNET_HOST_PATH` defined globally which breaks the uno.sourcegenerator detection for .NET Core. Is this variable defined at the user or machine level ?

**Comment by stefanolson** [comment]
Yes, that’s a new thing – because asp.net core 2.2 builds broke when vs 16.8 came out (many people with this issue). That was the only way I could keep building. I’ll remove it now..

**Comment by jeromelaban** [comment]
Where did you find this specific technique ?

**Comment by stefanolson** [comment]
here I think: https://developercommunity.visualstudio.com/content/problem/1224054/aspnet-core-22-framework-project-fails-to-build.html

**Comment by stefanolson** [comment]
Removing that works. So I can now build Uno (non UWP) bits, but not my website. Such fun :-)

**Comment by jeromelaban** [comment]
I'll push an update thanks @davkean's insights on msbuild's built-in variables :)
