### ISSUE TITLE
Static Resources in app.xaml not being found/used

### ISSUE THREAD

**Issue by stefanolson** [unoplatform/uno#4575]
## Current behavior

If you use a static resource found in app.xaml from a page the resource is not rendered, so presumably not found. If you add the resource to the page it works.

## Expected behavior

The resource should be used from app.xaml.
[UnoApp2.zip](https://github.com/unoplatform/uno/files/5573028/UnoApp2.zip)

## How to reproduce it (as minimally and precisely as possible)

Run enclosed project. Note icon isn't there. Uncomment the ControlTemplate in mainpage.xaml and it appears. 

## Workaround

Include in the page.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.8.2)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report!

The issue here is that the App.xaml does not contain a `Resources` property:

```xaml
<Application
    x:Class="UnoApp2.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:UnoApp2">
	<Application.Resources>
		<ControlTemplate x:Key="ArmedButtonTemplate" TargetType="ContentControl">
			<Viewbox>
				<Canvas Width="24" Height="24">
					<Path Fill="{TemplateBinding Foreground}" Data="M12,17A2,2 0 0,0 14,15C14,13.89 13.1,13 12,13A2,2 0 0,0 10,15A2,2 0 0,0 12,17M18,8A2,2 0 0,1 20,10V20A2,2 0 0,1 18,22H6A2,2 0 0,1 4,20V10C4,8.89 4.9,8 6,8H7V6A5,5 0 0,1 12,1A5,5 0 0,1 17,6V8H18M12,3A3,3 0 0,0 9,6V8H15V6A3,3 0 0,0 12,3Z" />
				</Canvas>
			</Viewbox>
		</ControlTemplate>
	</Application.Resources>
</Application>
```

In general, we suggest that the issues are compared to the original UWP behavior. In this case, the XAML could not be parsed by the UWP head, which is using the original Microsoft tooling.
