### ISSUE TITLE
PropertyChanged does not update all bindings with null

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4576]
## Current behavior

When property name of `PropertyChanged` notification is `null`, bindings are not updated.

## Expected behavior

Similarly to when property name is `string.Empty`, all bindings on that object should be updated.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
To confirm it works in UWP, here is the XAML generated code - it checks `IsNullOrEmpty` here:

![image](https://user-images.githubusercontent.com/1075116/99869566-69021900-2bcc-11eb-9745-04808099895e.png)

**Comment by jeromelaban** [comment]
That's the generated code for `x:Bind`, but does it work with a normal binding ?

**Comment by MartinZikmund** [comment]
@jeromelaban ha, that's the trick!

![image](https://user-images.githubusercontent.com/1075116/99881763-f751bb80-2c1b-11eb-959b-9b4f08ebd4cc.png)

So it works with `x:Bind` as they fixed it there, but `Binding` is still "broken" 😄
