### ISSUE TITLE
Skia.Gtk rendering problem

### ISSUE THREAD

**Issue by meta-space** [unoplatform/uno#4578]
I followed the Bugtracker tutorial on the Uno Platform getting started page

For some reason even simple text boxes don't seem to get rendered correctly on the Skia.Gtk backend.

## Current behavior

The TextBox does not contain any text, the slider does not show any label. [Screenshot](https://i.imgur.com/g7Nuo9o.png)

## Expected behavior

The Skia.Gtk backend should produce the same look and feel

## How to reproduce it (as minimally and precisely as possible)

https://platform.uno/docs/articles/getting-started-tutorial-2.html

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
 Uno.UI.Skia.Gtk" Version="3.3.0"

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [x] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.1)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [x] Resharper (version: 2020.2)

## Anything else we need to know?

I think I followed the tutorial. !'ve run the sample on WSL (running Ubuntu 18.04) as well as a real Debian buster machine. GUI renders the same on both.

**Comment by jeromelaban** [comment]
Thanks for the report! Skia `TextBox` is not yet supported (cannot be interacted with or display text), you can follow this issue for updates: #4319. I'll close this issue as a duplicate.

**Comment by meta-space** [comment]
Thanks for the quick response! Are there workarounds to address this?

Can you point me to the Uno.Skia.Gtk repository?

**Comment by jeromelaban** [comment]
There are no workarounds for this at this point, and this repository is the home for Uno.Skia.Gtk. Implementing a TextBox is quite tricky and we're still evaluating options on how to implement this.
