### ISSUE TITLE
Improve back navigation handling on iOS

### ISSUE THREAD

**Issue by jeanplevesque** [unoplatform/uno#4580]
## What would you like to be added:
I would like to see a unified and improved way of handling back navigation.
Ideally, I would like to use the [SystemNavigationManager](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.systemnavigationmanager) on all platforms. This currently works on Android, but not on iOS.

### Proposed behavior
1. Tapping the back button in a `CommandBar` would result in `SystemNavigationManager.BackRequested` being called.
1. Doing a back swipe gesture would result in a `Frame.GoBack()` like it's currently doing (so `SystemNavigationManager.BackRequested` **would not** be called).
1. Enabling/disabling the iOS back swipe gesture **would not** be done via `CommandBar`.

## Why is this needed:
Right now, platform specific code needs to be added every time we want to override the back navigation action (to show a prompt for example).
- The platform specific code is complex:
  - It requires developers to define a new `AppBarButton` with a ViewModel command bound to it.
    - This results in having platform specific code in both XAML and C# for the `AppBarButon` and the command implementation respectively.
  - It requires developers to add a visual asset that looks exactly like the native iOS back glyph.
    - Even with a good looking glyph, the horizontal alignment is different between the native one and the custom one.

### iOS Back Gesture
On top of its UI features, [the iOS CommandBar is also responsible for the back swipe gesture](https://platform.uno/docs/articles/controls/CommandBar.html#navigationcommand).
I suggest that this responsibility be separated from the `CommandBar` and be more explicit.

Implementation suggestions:
- An attached property with a clear name on `Page`.
- A global static `{ get; set; }` property. (This solution would allow easy-to-implement reusable recipes that don't require developers to adjust the xaml of each page.)

## For which Platform:

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
As discussed, can you point to the code in apps that should not be there ?

**Comment by jeanplevesque** [comment]
Here's a example of a simple CommandBar (that should have the native look) in a page that overrides the back action.
For iOS, we must use `toolkit:CommandBarExtensions.NavigationCommand` and create a new button that looks like the native one.
However for Android and UWP, we rely on `SystemNavigationManager` and the code in `toolkit:CommandBarExtensions.NavigationCommand` is not necessary.

```xml
<CommandBar Content="The title">

	<!-- This is the code that shouldn't be there. -->
	<toolkit:CommandBarExtensions.NavigationCommand>
		<AppBarButton ub:ActiveButtonBaseBehavior.Command="{Binding [Cancel]}">
			<android:AppBarButton.Icon>
				<BitmapIcon UriSource="ms-appx:///Assets/Icons/icn_back.png" />
			</android:AppBarButton.Icon>
			<ios:AppBarButton.Icon>
				<BitmapIcon UriSource="ms-appx:///Assets/Icons/icn_back.png" />
			</ios:AppBarButton.Icon>
			<win:AppBarButton.Icon>
				<BitmapIcon UriSource="ms-appx:///Assets/Icons/icn_back.png" />
			</win:AppBarButton.Icon>
		</AppBarButton>
	</toolkit:CommandBarExtensions.NavigationCommand>
</CommandBar>
```

**Comment by davidjohnoliver** [comment]
@kazo0 Will this be addressed by your work on NavigationBar? Can you give a brief update?

**Comment by francoistanguay** [comment]
This is addressed by NavigationBar and possible Extensions.Navigation

**Comment by jeanplevesque** [comment]
> This is addressed by NavigationBar and possible Extensions.Navigation

@francoistanguay Can you at least point to the doc that explains the new API?

**Comment by francoistanguay** [comment]
This? https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls/NavigationBar.html?q=navigationbar#maincommand
