### ISSUE TITLE
Azure DevOps-pipeline fails with fresh Uno-Template

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#4581]
## Current behavior
If I create a bare new Uno App from the VS-Template and create a "classic" Azure DevOps Pipeline for the iOs-Head, it fails with the error "Uno.SourceGenerationTasks.targets(134,2): error : In-process generation is not supported". If I use the new wizard-based YAML-pipeline it works.

So I'm not sure if this is a very important issue. I am fine with the YAML-Definition. The error itself is unclear to me, thoug, and I'm not sure what might be the real issue here. It might even be a misunderstanding from my side about build pipelines, VMs and such - I am by now means a DevOps-pro!

## Expected behavior
The build should work in both cases or the error should be clearer.

## How to reproduce it (as minimally and precisely as possible)
Create a new Uno App from the VS-template.
Publish it on Github.
Create a new Azure Pipeline and select "classic":
![image](https://user-images.githubusercontent.com/1833242/99846452-9f14ae00-2b76-11eb-9f88-f9b1ded1f0aa.png)

## Workaround
Use the "new pipeline"-mode.

## Environment
Azure DevOps

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks! Can you provide a screenshot of the tasks added to the pipeline definition ?

**Comment by TopperDEL** [comment]
![image](https://user-images.githubusercontent.com/1833242/99847151-e64f6e80-2b77-11eb-9eaa-ef66c8c439ee.png)

**Comment by jeromelaban** [comment]
This task is probably setting options that are not supported. If you can create a binlog file, that will help troubleshoot.

**Comment by TopperDEL** [comment]
Sorry, I do not know what exactly you mean or how I could do this.

**Comment by jeromelaban** [comment]
To create a binlog, you'll have to provide the `$(build.artifactstagingdirectory)\build.binlog` to msbuild. I'll create a file that you can download from your artifacts, which you can post here.

**Comment by TopperDEL** [comment]
Hm, I don't get that parameter provided for msbuild. In the pipeline I do not find any way to set it.

**Comment by jeromelaban** [comment]
I do not know the inner workings of this task, but the Azure Devops team is moving away from this type of pipelines. Is it not possible for you to use yaml pipelines ?

**Comment by TopperDEL** [comment]
It is! As I said, the other one (the new one) is working for me.

So, lets simply close this issue as it only belongs to a build definition that is no more up to date and might as well be a config error on my side.
