### ISSUE TITLE
Quotes in item content are not handled properly

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4584]
## Current behavior

Consider the following:

```
<ListView>
  <RadioButton x:Name="TheRadioButton">"I'm really a Radio Button"</RadioButton>
  <x:String>I'm just a string</x:String>
  <Button>And I'm a Button!</Button>
</ListView>  
```

Building this under Uno causes invalid generated code:

```
...

new global::Windows.UI.Xaml.Controls.RadioButton
{
	IsParsing = true
	,
	Name = "TheRadioButton",
	// Source ..\..\..\..\..\..\..\App8.Shared\MainPage.xaml (Line 12:10)
	Content = ""I'm really a Radio Button""
	,
}
```

Notice the duplicated double quotes in `Content` value. Note that using `&quot;` does not help.

## Expected behavior

Should build successfully.

## How to reproduce it (as minimally and precisely as possible)

See above.

## Workaround

Set the value from code-behind.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment]
@MartinZikmund Sorry, just noticed you self-assigned this issue after I opened a PR.
