### ISSUE TITLE
Cannot use multi-platform library for UWP anymore

### ISSUE THREAD

**Issue by IsmailHassani** [unoplatform/uno#4592]
## Current behavior
After creating a multi-platform library nuget package I got several errors when referenced to an Uno application (UWP head).
Mostly the error manifests itself in a weird error:
```
CS0012	The type 'Application' is defined in an assembly that is not referenced. You must add a reference to assembly 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'.	ISynergy.Display.UWP	C:\Projects\I-Synergy\src\ISynergy.Display\ISynergy.Display.Shared\App.xaml.cs	39	Active
```

After inspection of the nuget package, a strange thing showed up.
I decompiled the actual dll (UAP 18362) and where i expected a NetCore2 assembly it shows a XamarinAdroid assembly

## nuget version 2020.1287.1
```
[assembly: AssemblyCompany("International Intelligence")]
[assembly: AssemblyConfiguration("release")]
[assembly: AssemblyCopyright("Copyright (c) 2008-2020 International Intelligence")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyProduct("I-Synergy Framework")]
[assembly: AssemblyTitle("ISynergy.Framework.UI")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: CompilationRelaxations(8)]
[assembly: Debuggable(,)]    // JustDecompile was unable to locate the assembly where attribute parameters types are defined. Generating parameters values is impossible.
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: TargetFramework(".NETCore,Version=v5.0", FrameworkDisplayName=".NET for Windows Universal")]
```
## nuget version 2020.1327.1
```
[assembly: AssemblyCompany("International Intelligence")]
[assembly: AssemblyConfiguration("release")]
[assembly: AssemblyCopyright("Copyright (c) 2008-2020 International Intelligence")]
[assembly: AssemblyDescription("I-Synergy UI Framework for Uno Platform Applications")]
[assembly: AssemblyFileVersion("2020.1327.1.0")]
[assembly: AssemblyInformationalVersion("2020.1327.1")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/I-Synergy/I-Synergy.Framework")]
[assembly: AssemblyProduct("I-Synergy Framework")]
[assembly: AssemblyTitle("ISynergy.Framework.UI")]
[assembly: AssemblyVersion("2020.1327.1.0")]
[assembly: CompilationRelaxations(8)]
[assembly: Debuggable(,)]    // JustDecompile was unable to locate the assembly where attribute parameters types are defined. Generating parameters values is impossible.
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: ResourceDesigner("ISynergy.Framework.UI.Resource", IsApplication=false)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: TargetFramework("MonoAndroid,Version=v10.0", FrameworkDisplayName="Xamarin.Android v10.0 Support")]
[assembly: UsesPermission("android.permission.READ_EXTERNAL_STORAGE")]
```

The only thing i changed is moving .nuspec info to the .csproj for better version update handling.
It looks like the build is messing some stuff up.

## Expected behavior
This error should not occur and UWP build should work.

## How to reproduce it (as minimally and precisely as possible)
The repo should be found [here: https://github.com/I-Synergy/I-Synergy.Framework](https://github.com/I-Synergy/I-Synergy.Framework)
This is connected to the Azure Devops pipeline where it builds this repo and creates the [nuget packages](https://www.nuget.org/packages/I-Synergy.Framework.UI/).

When you create a new Uno application an reference this nuget package you should change the following files:
- App.xaml
```
<app:BaseApplication
    x:Class="App9.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:app="using:ISynergy.Framework.UI">

</app:BaseApplication>
```
- App.xaml.cs
```
public sealed partial class App : BaseApplication
    {
        /// <summary>
        /// Initializes the singleton application object.  This is the first line of authored code
        /// executed, and as such is the logical equivalent of main() or WinMain().
        /// </summary>
        public App() : base()
        {
#if NETFX_CORE
            InitializeComponent();
#endif
        }

        protected override void ConfigureLogger(ILoggerFactory factory) { }

        public override Task HandleException(Exception ex, string message)
        {
            Debug.WriteLine(ex.Message);
            return Task.CompletedTask;
        }
```
The onlaunched method can be removed because it's already handled in the library.

When you try to run this project (UWP head) you get this error.

## Environment

Nuget Package:
- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [X] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [X] Other: I-Synergy.Framework.UI

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [X] Windows
- [X] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

## Build log
[https://dev.azure.com/i-synergy/I-Synergy.Framework/_build/results?buildId=3089&view=results](https://dev.azure.com/i-synergy/I-Synergy.Framework/_build/results?buildId=3089&view=results)
[https://dev.azure.com/i-synergy/90d7e0d9-70d5-4309-b5e2-d9353380d5c5/_apis/build/builds/3089/logs/27](https://dev.azure.com/i-synergy/90d7e0d9-70d5-4309-b5e2-d9353380d5c5/_apis/build/builds/3089/logs/27)

**Comment by jeromelaban** [comment]
Thanks for the report.

Are you able to reproduce this issue in a simple sample app ?

**Comment by IsmailHassani** [comment]
Yes i created a new Uno Application to test this.

**Comment by IsmailHassani** [comment]
Hi guys,
I found the solution. It seems it has to do how I build my project with MSBuild in Azure Devops.
Instead of the default **bin\Debug** folder, I use a custom one to be able to publish the nupkg to the artifacts directory.

The property that is now used is **OutputPath**, however setting it from the CLI makes it a global property and overrules the automatic appending of the output path. This causes msbuild to overwrite existing library dll's by the next target platform.
In my case it was the Android version,

The workaround is to make an intermediate property that is global and consume it from the project.
Add this to your project file inside a PropertyGroup:
```
<OutputPath>$(BaseOutputPath)</OutputPath>
```
My msbuild command was:
```
msbuild ISynergy.Framework.UI.csproj /nr:false /p:OutputPath=C:\Temp\Output /p:platform="AnyCpu" /p:configuration="debug"
```
It should be changed to:
```
msbuild ISynergy.Framework.UI.csproj /nr:false /p:BaseOutputPath=C:\Temp\Output -restore /p:platform="AnyCpu" /p:configuration="debug"
```
