### ISSUE TITLE
Can open any XAML window at design time.

### ISSUE THREAD

**Issue by dmitrybv** [unoplatform/uno#4593]
## Current behavior
Created simple UnoApp 
and started to change MainPage.xaml
After I try to change View type from UWP to to something else 
https://platform.uno/docs/articles/Assets/quick-start/xaml-intellisense.png
I got error - ‘Empty path name is not legal’

And design window disappeared.
So now I can' open any XAML window  at design time.
It always displays an error ‘Empty path name is not legal’

![sshot-158](https://user-images.githubusercontent.com/29243748/99928877-20796580-2d5c-11eb-8ed2-659ae91dc51b.png)

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: Version 16.9.0 Preview 1.0)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
This is unfortunately an ongoing bug in Visual Studio (see [here](https://developercommunity.visualstudio.com/content/problem/889907/uwp-hot-reload-does-not-work-for-xaml-files-in-a-s.html), closed as fixed, not really fixed completely yet). Maybe we should raise a new issue there to make sure they don't forget about it.

Try to use[ this workaround](https://platform.uno/docs/articles/get-started-wizard.html#the-xaml-editor-may-be-empty) to see if it helps. It is also possible to right-click the XAML file, choose Open with... and then use a plain XML editor. However, IntelliSense is lost this way...

**Comment by dmitrybv** [comment]
>The XAML editor may be empty
>The XAML editor may be empty when the active editor project is not UWP.

>To work around this issue, close all XAML editors, open a C# file and select 'UWP' in the top left drop-down list of the text editor sector. Once selected, re-open the XAML file

This workaround works. Thanks.

**Comment by radutomy** [comment]
Same problem here. Where is the top left drop-down list exactly? I can't seem to find it.

**Comment by dmitrybv** [comment]
![sshot-159](https://user-images.githubusercontent.com/29243748/100023445-0c824200-2df6-11eb-8ec8-37798bd19807.png)

**Comment by MartinZikmund** [comment]
Hopefully Microsoft fixes this sooner than later...

**Comment by MartinZikmund** [comment]
I have opened a new VS feedback for this [here](https://developercommunity.visualstudio.com/content/problem/1267071/trying-to-open-xaml-files-shows-empty-path-name-is.html), please upvote to get their attention 🙂

**Comment by jeromelaban** [comment]
The editor also fails for other reasons, I also opened [this issue](https://developercommunity.visualstudio.com/content/problem/1266894/uwp-xaml-intellisense-fails-when-using-shared-proj.html).

**Comment by GF-Huang** [comment]
> > The XAML editor may be empty
> > The XAML editor may be empty when the active editor project is not UWP.
> 
> > To work around this issue, close all XAML editors, open a C# file and select 'UWP' in the top left drop-down list of the text editor sector. Once selected, re-open the XAML file
> 
> This workaround works. Thanks.

Not work.

**Comment by jeromelaban** [comment]
Note that Visual Studio 16.9 Preview 2 fixes parts of this issue, and Preview 3 is likely to fix it completely.

**Comment by mddifilippo89** [comment]
As a work around simply right click the xaml page and choose Open With > Html Editor > Set as Default

**Comment by RichieSams** [comment]
Confirmed that Preview 3 fixed this issue for me

**Comment by MartinZikmund** [comment]
This is now working well :-)
