### ISSUE TITLE
Pointer events on iOS don't work correctly

### ISSUE THREAD

**Issue by jeanplevesque** [unoplatform/uno#4602]
## Current behavior

Pointer events on iOS don't work correctly.
Setting `PointerRoutedEventArgs.Handle = true` doesn't have the correct behavior for `UIElement.PointerPressed`.

## Expected behavior

Pointer events work correctly on all platforms.

## How to reproduce it (as minimally and precisely as possible)

[PointerEventsRepro.zip](https://github.com/unoplatform/uno/files/5585799/PointerEventsRepro.zip)
Compare the attached repro project between iOS and other platforms (tested with Android, UWP).
Touch the _handle_ and try to swipe the drawer up and down.
You'll notice that on iOS, you have to release the touch, then touch again outside the handle for the drawer to move.

## Workaround

Look for `#if` in `DrawerView.cs` to find the workarounds.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.1.0-beta.65

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeanplevesque** [comment]
I got to say however that there used to be more problems around pointer events and updating to a newer version fixed a few... so that's nice :)

**Comment by dr1rrb** [comment]
This is now working properly with uno 4.0.11 (most probably fixed by https://github.com/unoplatform/uno/pull/6511)
