### ISSUE TITLE
Button Control stucking During Click - Skia GTK Linux

### ISSUE THREAD

**Issue by microhobby** [unoplatform/uno#4603]
## Current behavior

See the gif comparisons between a UWP application and a Skia GTK while the user performs several clicks on a Button:

**UWP**
![aavjVPQwrH](https://user-images.githubusercontent.com/2633321/100017814-3f0e4980-2dba-11eb-8ad8-12e4fa1a77b4.gif)

**Skia GTK**
![AOxUaN3SpS](https://user-images.githubusercontent.com/2633321/100017868-50575600-2dba-11eb-933d-96c686d35356.gif)

There is a small gap of ~1s between one click and another.
I also realized that the problem may not be linked that there is a stuck or a long task being performed because if the second click happens in the same place without moving the pointer after a longer interval, even then the click is not computed:

![nbQwrWduRg](https://user-images.githubusercontent.com/2633321/100018642-8943fa80-2dbb-11eb-8919-7d0624eee5cb.gif)

If I change the focus of the button or make a third click is that the click is computed.

## Expected behavior

Clicks should be computed at the same speed as the UWP project.

## How to reproduce it (as minimally and precisely as possible)

- Create a cross-platform app
- Add a grid and a button to the MainPage.xaml
- Execute and try to run several clicks on the button

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [x] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
## Note to contributors

This issue is touch probably related as it generally appears when the pointers are raised by GTK as touch events (whether through WSL display app) or through a physical touch screen.

**Comment by microhobby** [comment]
I cloned the branch `dev/dr/ptReleaseSkia`, compiled it and using the `dll`s generated from the build on my project I definitely say that the PR #4606 solves this.
Thanks @dr1rrb !
