### ISSUE TITLE
[WebAssembly] .NET 5 support

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4613]
This epic keeps track of the .NET 5 support related issues.

## dotnet/runtime stability issues

_Blockers_:
- https://github.com/dotnet/runtime/issues/57141

_Important_:
1. Profiled AOT Stack Crawling https://github.com/dotnet/runtime/issues/47996
1. NIY opcode issue https://github.com/dotnet/runtime/issues/47275

_Others_:
1. libICU memory corruption https://github.com/dotnet/runtime/issues/45224 (Related to https://github.com/unoplatform/uno/issues/4514)
1. FullAOT issue (exception filter): https://github.com/dotnet/runtime/issues/50609
1. FullAOT issue (exception filter) with `CancellationTokenSource.ExecuteCallbackHandlers` https://github.com/dotnet/runtime/issues/46855
1. AOT Epic https://github.com/dotnet/runtime/issues/48079

## dotnet/runtime performance issues
_Blockers_:
1. https://github.com/dotnet/runtime/issues/56309
1. https://github.com/dotnet/runtime/issues/54272

_Important_:
1. try/finally performance https://github.com/dotnet/runtime/issues/50783
1. PG-AOT foreach performance https://github.com/dotnet/runtime/issues/48179

**Uno Issues**:
N/A

**Fixed**:
1. ~~Linker performance https://github.com/mono/linker/issues/918~~
1. ~~https://github.com/dotnet/runtime/issues/53380~~
1. ~~AOT Dedup issue https://github.com/dotnet/runtime/issues/50508~~
1. ~~AOT LLVM error: https://github.com/dotnet/runtime/issues/50561~~
1. ~~Unknown memory corruption https://github.com/dotnet/runtime/issues/48814~~
1. ~~Unknown memory corruption https://github.com/dotnet/runtime/issues/51207~~
1. ~~Interpreter memory corruption https://github.com/dotnet/runtime/issues/51406~~
1. ~~Nullable<T> performance https://github.com/dotnet/runtime/issues/48126~~
1. ~~Generics performance https://github.com/dotnet/runtime/issues/50757#issuecomment-813764063~~
1. ~~AOT memory corruption https://github.com/dotnet/runtime/issues/50202~~
1. ~~AOT JitHelper issue https://github.com/dotnet/runtime/issues/51113~~
1. ~~Large app AOT error https://github.com/dotnet/runtime/issues/49875~~
1. ~~Native Exception frames support under AOT https://github.com/dotnet/runtime/issues/44628~~
2. ~~Linker SQLite issue https://github.com/mono/linker/issues/1919~~
- ~~Interpreter issue with EF Core https://github.com/dotnet/runtime/issues/49415~~
- ~~Linker error: https://github.com/dotnet/runtime/issues/49874 (https://github.com/unoplatform/uno/issues/5520)~~
- ~~PG-AOT Exception handling corruption dotnet/runtime#47334~~
- ~~PG-AOT failure with dedup: https://github.com/dotnet/runtime/issues/49648~~
- ~~PG-AOT Generic methods performance https://github.com/dotnet/runtime/issues/48163~~
- ~~Return value JS String interning issue: https://github.com/dotnet/runtime/issues/48345~~
- ~~PG-AOT stack corruption issue https://github.com/dotnet/runtime/issues/47887~~
- ~~`ResourceManager` fails under AOT https://github.com/dotnet/runtime/issues/45698~~
- ~~Unknown corruption when using `Assembly.Load` under AOT https://github.com/dotnet/runtime/issues/46613~~
- ~~`Type.GetType()` fails under AOT https://github.com/dotnet/runtime/issues/45078~~
- ~~`Assembly.Load` for loaded assemblies https://github.com/dotnet/runtime/issues/44269~~
- ~~Unknown Interp/AOT transition memory corruption https://github.com/dotnet/runtime/issues/44270~~
- ~~Assertion runtime/src/mono/mono/mini/aot-compiler.c:3563 https://github.com/dotnet/runtime/issues/45548~~

**Comment by DierkDroth** [comment]
@jeromelaban your post above is very valuable. 

I clicked through the items and found that an update to reflect latest WindowsAppSDK + .NET could help
- some items appear to be closed
- may be there are other/new ones?!?

**Comment by jeromelaban** [comment]
@DierkDroth We'll be updating this for .NET 7 as we go.
