### ISSUE TITLE
TreeViewItem hover/selection states are not visible

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#4620]
## Current behavior

TreeViewItem has nothing to indicate mouse over/selection states.

## Expected behavior

TreeViewItem's mouse over/selection states should be clearly visible.

## How to reproduce it (as minimally and precisely as possible)
- launch SampleApp
- navigate to TreeView -> TreeViewBasics
- check "FL" to enable Fluent style
- click (icon: refresh) button
- mouse over/select the TreeView items

## Workaround
override resources like: TreeViewItemBackgroundPointerOver, TreeViewItemBackgroundPressed, etc...

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):  3.4.0-dev.137

Affected platform(s): // only tested WebAssembly

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.7.7)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
```
Found TreeViewItemBackgroundPointerOver (SolidColorBrush): [SolidColorBrush [Color: 00000019;00000000;00000000;00000000]]
Found SystemControlHighlightListLowRevealBackgroundBrush (SolidColorBrush): [SolidColorBrush [Color: 00000019;00000000;00000000;00000000]]
Found SystemListLowColor (Color): [Color: 00000019;00000000;00000000;00000000]

Found TreeViewItemBackgroundPressed (SolidColorBrush): [SolidColorBrush [Color: 00000033;00000000;00000000;00000000]]
Found SystemControlHighlightListMediumRevealBackgroundBrush (SolidColorBrush): [SolidColorBrush [Color: 00000033;00000000;00000000;00000000]
Found SystemRevealListMediumColor (Color): [Color: 0000002E;00000000;00000000;00000000]
Found SystemListMediumColor (Color): [Color: 00000033;00000000;00000000;00000000]
```

**Comment by MartinZikmund** [comment]
This was fixed by #6071
