### ISSUE TITLE
Issues Microsoft.UI.Xaml.Controls.TabView in WASM  

### ISSUE THREAD

**Issue by s-beltz** [unoplatform/uno#4628]
## Current behavior

We deal with the following issues when using a Microsoft.UI.Xaml.Controls.TabView in WASM:

- Property ForeGround is not applied. UWP shows the correct ForeGround color, WASM keeps default value of "Black".
- When binding TabItemsSource to an ObservableCollection<SomeViewModelType>, tabs are not rendered.
- When setting TabItemsSource in code, a databound TabStripFooter is not rendered anymore.

## Expected behavior

- ForeGround is applied to inactive tabs as in UWP.
- TabItemsSource can be bound via x:Bind
- TabStripFooter is displayed regardless of the way TabItemsSource is set (in code/databindig)

## How to reproduce it (as minimally and precisely as possible)

1. Download repro app
2. Start **Apliconus.Uno.IssueRepro.Uwp** project to see the minimal desired layout:
![image](https://user-images.githubusercontent.com/57802605/100638068-e0a21780-3333-11eb-8fe4-9eb4534f03e2.png)
3. Start **Apliconus.Uno.IssueRepro.Uwp** project to observe the issues:
![image](https://user-images.githubusercontent.com/57802605/100638555-73db4d00-3334-11eb-9101-0a8f20f05ef5.png)
As you can see in this screenshot the ForeGround isn't applied to inactive tabs, the TabStripFooter is missing in the first TabView and lastly the TabViewItems in the second TabView aren't rendered.
[Apliconus.Uno.IssueRepro.zip](https://github.com/unoplatform/uno/files/5617287/Apliconus.Uno.IssueRepro.zip)

Code for the first TabView can be found in file RibbonControl.xaml (UserControl). TabItemsSource is set in code in RibbonControl.Loaded event.

The second TabView is embedded in MainPage.xaml. In this case we have binding expression for TabView.TabItemsSource.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI 3.3.0
Microsoft.UI.Xaml 2.4.3

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.7.6)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Let's close this issue and follow up on individual issues here: https://github.com/unoplatform/uno/issues/4874, https://github.com/unoplatform/uno/issues/4875, https://github.com/unoplatform/uno/issues/4876
