### ISSUE TITLE
ContentDialog Doesn't Show Buttons or Content

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#4631]
## Current behavior

The close button is not shown in the ContentDialog in Android.

![image](https://user-images.githubusercontent.com/17993847/100655990-0c180880-331a-11eb-8021-28f23f02e440.png)

Edit: With further testing, it's apparent that Primary and Secondary buttons also don't work. Worse, in some cases the Content doesn't appear at all and the dialog is a blank popup. I wonder if ContentDialog is implemented at all.

## Expected behavior

![image](https://user-images.githubusercontent.com/17993847/100656087-2c47c780-331a-11eb-8b27-da764f089642.png)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.3.0

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
This seems to be working properly now, @robloo if you find some issues, please reopen.

**Comment by robloo** [comment]
It does work now, thanks for closing
