### ISSUE TITLE
Issues Microsoft.Toolkit.Uwp.UI.Controls.DataGrid in WASM

### ISSUE THREAD

**Issue by s-beltz** [unoplatform/uno#4634]
## Current behavior

When using Microsoft.Toolkit.Uwp.UI.Controls.DataGrid with **AutoGenerateColumns=False** and adding DataGridTemplateColumns and DataGridColumnHeaderStyle in code we see the following issues in WASM builds
- Column headers aren't displayed correctly don't evaluate their binding. Instead it seems that **ViewModel.ToString()** is displayed.
- Cells are rendered empty.

The UWP build works as expected.

## Expected behavior

- Databinding of ColumnHeaderStyle is evaluated.
- Cell content is rendered accordingly to binding expression.

## How to reproduce it (as minimally and precisely as possible)

1. Download attached repro app.
[apliconus-uno-datagrid-issue.zip](https://github.com/unoplatform/uno/files/5621414/apliconus-uno-datagrid-issue.zip)
2. Start WASM app:
![image](https://user-images.githubusercontent.com/57802605/100718979-4c2fc780-33bc-11eb-8abc-19501bd3a445.png)
3. Start UWP app:
![image](https://user-images.githubusercontent.com/57802605/100719037-62d61e80-33bc-11eb-9520-d0b1de734260.png)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI 3.3.0
Microsoft.Toolkit.Uwp.UI.Controls.DataGrid 6.1.1
Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid 6.1.0-build.191.gc988bdd4ff

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.7.6)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
@s-beltz thanks for the report. We've made many changes in Uno and WCT regarding the DataGrid, and those issues may have been fixed already. Would you mind validating it's the case for you ?

**Comment by s-beltz** [comment]
@jeromelaban we opened the issue with Uno 3.3.0. It seems that things are working fine since Uno 3.4.0. We also added BindableSupport for a couple of ViewModel classes. We now can see the cells content in WASM.

Thank you!
