### ISSUE TITLE
Fully templated dialog control throws exception on creation

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#4639]
## Current behavior

On calling ShowAsync the following exception is raised

System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

## Expected behavior

The content dialog should be displayed

## How to reproduce it (as minimally and precisely as possible)

Can be reproduced by running the sample located here:
https://github.com/BrianDT/UWPTemplatedContentDialogIssue.git

## Workaround

None obvious

## Environment

Nuget Package:
Not sure could be Uno.Core

Nuget Package Version(s):
3.3.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.2)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report! Errors raised by UWP are not something we can fix. It would be best to report this on the WinUI repository: https://github.com/Microsoft/microsoft-ui-xaml

**Comment by MartinZikmund** [comment]
Closing this as it is a WinUI issue and it is open on their side
