### ISSUE TITLE
Fully templated dialog control displayed before ShowAsync is called when defined inline in XAML

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#4641]
## Current behavior

The control is displayed in the location it is defined.
When ShowAsync is called the content dialog is displayed in the wrong location.

## Expected behavior

The control should not be displayed until ShowAsync is called.

## How to reproduce it (as minimally and precisely as possible)

Can be reproduced by running the sample located here:
https://github.com/BrianDT/UWPTemplatedContentDialogIssue.git

## Workaround

Could probably be controlled with visibility, however this would not correct the positioning issue.

## Environment

Nuget Package:
Not sure

Nuget Package Version(s): 3.3.0

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.2)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by BrianDT** [comment]
The 'control displayed before ShowAsync' part of this issue no longer occurs in 4.6.19
The display part has been separately raised in #10333 
Please close

**Comment by jeromelaban** [comment]
Thanks!
