### ISSUE TITLE
Please do something 

### ISSUE THREAD

**Issue by fisforfaheem** [unoplatform/uno#4645]
Flutter is being used by millions to start programming while no one know UNO please invest in marketing and doing something amazing... like flutter does! make it super simple and easier to make apps in UNO like flutter and make a comaprison vidoes etc. and make people know about you please

**Comment by pkar70** [comment]
But... Flutter is for new app, and you have to use new language. It is totally different than Xamarin (for new app, but in known language) and Uno (single, existing app, works in all environments).

**Comment by sasakrsmanovic** [comment]
Couldn't agree more and we are on it. Trying to mobilize the troops to do exactly that. Are you, or anyone else, interested in helping out? Please respond in this thread and we will divvy up the work among those who are interested. Also, feel free to reach out to sasha@platform.uno

**Comment by fisforfaheem** [comment]
Yes, I am! i want to use uno as flutter but uno seems so private etc

**Comment by fisforfaheem** [comment]
can uno use flutter?

**Comment by fisforfaheem** [comment]
anyway! i hope UNO become default! and hurt .net 6 to the core! and make
flutter sorry!
