### ISSUE TITLE
WinUI 3 preview 3 NavigationView not working

### ISSUE THREAD

**Issue by LeftTwixWand** [unoplatform/uno#4648]
## Current behavior

When I'm creating a new unoapp-winui and trying to use NavigationView - got an error:

**Windows.UI.Xaml.Markup.XamlParseException: 'The text associated with this error code could not be found.**

**Cannot find a Resource with the Name/Key TabViewButtonBackground [Line: 10 Position: 6]'**

But for Blank App from [WinUI 3 Project Templates](https://marketplace.visualstudio.com/items?itemName=Microsoft-WinUI.WinUIProjectTemplates) it works normaly.

## How to reproduce it

 - dotnet new unoapp-winui
 - Add NavigationView component to MainPage.xaml
```XAML
<Page
    x:Class="MyApp.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <NavigationView/>
</Page>
```
- Run

## Workaround

UWP target version: 2004 Build 19041
UWP min version: 1809 Build 17763
Installed Windows SDK: 1809, 1903, 2004

## Environment

Nuget Package:
- [x] Uno.UI
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

**Microsoft.WinUI version 3.0.0-preview3.201113.0
Uno.UI version 3.3.0**

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows 10 version 20H2, OS build 19042.63
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.0 Preview 1)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report! 

It looks like it would be related to missing `App.xaml` content. Can you try using the `App.xaml` resources found in the working app ?

**Comment by LeftTwixWand** [comment]
I've just added this code to `App.xaml`, and it starts working:
```XAML
<Application.Resources>
     <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>
</Application.Resources>
```
