### ISSUE TITLE
Intellisense not recognizing xaml x:Name attribute as property

### ISSUE THREAD

**Issue by Greg-Freeman** [unoplatform/uno#4654]
## Current behavior

When I created the project from the Uno Platform Solutions Template in Visual Studio on Windows, adding the x:Name attribute to elements in the XAML was not detected by Intellisense in the code behind.
## Expected behavior
Intellisense detects x:Name attributes in the code behind as properties on the class

## How to reproduce it (as minimally and precisely as possible)
I had this issue from the start after creating the solution from Uno Platform Solutions Template, but have since resolved it, so I no longer have the example. Mostly I am posting the workaround below as documentation for others that may run into this, as I have seen other bug reports with people having this issue.

## Workaround

After a lot of googling, I found some others had a similar issue on this [thread](https://developercommunity.visualstudio.com/content/problem/587976/xaml-intellisense-does-not-start-properly-on-proje.html).

The solution that ended up working for me was to delete the MainForm.xaml file in the shared project and recreate it under the UWP project. I then moved the file from the UWP project back into the shared project and everything started working. I tried all the steps suggested in the Getting Started tutorial and none worked.

## Environment

Nuget Package:

- [x ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
PM> Get-Package | Select-Object Id, Version | Where-Object {$_.Id -like "uno*"}

Id                           Version
--                           -------
Uno.UI.RemoteControl         3.3.0  
Uno.Wasm.Bootstrap           1.3.4  
Uno.Wasm.Bootstrap.DevServer 1.3.4  
Uno.UI                       3.3.0  
Uno.UI.WebAssembly           3.3.0  
Uno.UI.RemoteControl         3.3.0  
Uno.UI.Skia.Tizen            3.3.0  
Uno.UI                       3.3.0  
Uno.UI.RemoteControl         3.3.0  
Uno.UI                       3.3.0  
Uno.UI.Skia.Wpf              3.3.0  
Uno.UI.RemoteControl         3.3.0  
Uno.UI                       3.3.0  
Uno.UI.Skia.Wpf              3.3.0  
Uno.UI                       3.3.0  
Uno.UI.RemoteControl         3.3.0  
Uno.Core                     2.0.0  
Uno.UI                       3.3.0  
Uno.UI                       3.3.0  
Uno.UI.RemoteControl         3.3.0  
Uno.UI                       3.3.0  
Uno.UI.RemoteControl         3.3.0  
Uno.UniversalImageLoader     1.9.33 

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ x] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x ] Visual Studio 2019 (version: 16.8.2)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thank you for the report. This is a visual studio issue, for which the resolution can be found here: https://github.com/unoplatform/uno/blob/master/doc/articles/get-started-wizard.md#initializecomponent-or-xname-variable-is-not-available-in-code-behind

You can follow the other known issues in this document, and in the global list of issues we're tracking: https://github.com/unoplatform/uno/issues/982.

**Comment by Greg-Freeman** [comment]
Thanks for the link. 

> Thank you for the report. This is a visual studio issue, for which the resolution can be found here: https://github.com/unoplatform/uno/blob/master/doc/articles/get-started-wizard.md#initializecomponent-or-xname-variable-is-not-available-in-code-behind
> 
> You can follow the other known issues in this document, and in the global list of issues we're tracking: #982.
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/132453438/7fcbaf80-9f86-11e9-9d5c-1feea63c9a2e"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[unoplatform/uno](https://github.com/unoplatform/uno)**Build Mobile, Desktop and WebAssembly apps with C# and XAML. Today. Open source and professionally supported. - unoplatform/uno

Thanks for the link. I did try those solutions and it wasn't resolving the problem. However, I think doing that as well as deleting the .suo files then restarting VS may have ultimately been the thing that did the trick. Unfortunately I went through a lot of additional troubleshooting steps so I'm not sure the exact thing that ultimately resolved it for me. I may dig into it a bit further and be more methodical about it if I and find the time.

**Comment by Greg-Freeman** [comment]
steps above seemed to work
