### ISSUE TITLE
NavigationView HeaderTemplate not displaying in WASM head

### ISSUE THREAD

**Issue by yowl** [unoplatform/uno#466]
## I'm submitting a...

 - Bug report (I searched for similar issues and did not find one) 
 

## Current behavior
NavigationView Header is missing in wasm

## Expected behavior
header should appear (Button with Login text)

## Minimal reproduction of the problem with instructions
Download https://github.com/yowl/UnoStandardRefTest/tree/missingheader and run the wasm head.

I think on previous versions of Uno.UI this is working.

## Environment

```
Nuget Package: 
Uno.UI
Package Version(s): 1.43.0-dev.564

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ x] 2017 (version:15.9.4 )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by yowl** [comment]
Actually this is fine, there's something else causing the header to not display, so will close this and open when I get a repro

**Comment by MartinZikmund** [comment]
This is now fixed with the new WinUI `NavigationView`
