### ISSUE TITLE
Wasm: Crash using NavigationView with dynamic items and incorrect layout.

### ISSUE THREAD

**Issue by alove-kahua** [unoplatform/uno#4661]
## Current behavior
Adding a new NavigationItem with a removed NavigationItem's DataContext, causes the layout to be shifted to the right.  After adding, clicking, then removing the Navigation item, eventually it will hang for a period of time and finally crash.  Both of these issues work correctly in UWP.

## Expected behavior
1. The layout of Item 2 looks correct (the text should not get shifted to the right). In our current app, we have a layout that includes an icon.  The icon shows twice in the NavigationItem when this happens.

2. No crash should occur.

## How to reproduce it (as minimally and precisely as possible)
I have made a project to reproduce the issue.  Clicking the Start button at the top begins to add and remove rapidly Item 2, this is just for speeding up the scenario.  Then try to click the Item 2 that keeps getting added, eventually it will hang then crash.

[TestNavigationView.zip](https://github.com/unoplatform/uno/files/5644405/TestNavigationView.zip)

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Additional full stacktrace:
[navview-failure.txt](https://github.com/unoplatform/uno/files/5660520/navview-failure.txt)

**Comment by jeromelaban** [comment]
Sample app repro for the items with the incorrect layout. This may be the cause for the invalid recursion.

https://github.com/jeromelaban/uno/commit/1d3f15be42064a0b6a5fc82e27df00d98aa695e4
