### ISSUE TITLE
Linebreak in textblock not displaying correctly

### ISSUE THREAD

**Issue by Greg-Freeman** [unoplatform/uno#4663]
## Current behavior

Linebreak in a text block is displaying as a square box in built application but correctly in the designer. I have seen some other bug reports like this one but not for WPF explicitly. I figured I'd put it here for visibility either way.

## Expected behavior

Correctly display newline

## How to reproduce it (as minimally and precisely as possible)

![image](https://user-images.githubusercontent.com/5956516/101198357-f6138c00-3628-11eb-8212-f57798c1590b.png)

![image](https://user-images.githubusercontent.com/5956516/101198448-18a5a500-3629-11eb-9140-dfba26ae3a1a.png)

```
<Page
    x:Class="ThermostatGui.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:ThermostatGui"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{StaticResource DefaultAppBackgroundBrush}">

    <TextBlock TextAlignment="Center">
         This does <LineBreak/> not work
     </TextBlock>
</Page>
```

## Workaround

Stacked panel with 'n' separate items

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thank you for the report! 

TextBlock is currently only able to display single lines of text, you can follow the progress of this support in https://github.com/unoplatform/uno/issues/4309

**Comment by MartinZikmund** [comment]
Line breaks now display properly in Skia targets
