### ISSUE TITLE
XAML enum parsing should handle improper casing

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4666]
## Current behavior

Consider the following XAML:

```
<SymbolIcon Symbol="Slideshow" />
```

This causes compile error on Uno. The reason is the actual enum member is called "Slide**S**how", but code gen produces "Slideshow".

## Expected behavior

Should compile.

## How to reproduce it (as minimally and precisely as possible)

See above.

## Workaround

Use proper casing in XAML.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by workgroupengineering** [comment]
I have try on 0e1042cd4d1f722b2d3586fd0819dce80f4660d6 and it work.

**Comment by MartinZikmund** [comment]
Indeed, works now!
