### ISSUE TITLE
[Doc] Outdated and redundent doc

### ISSUE THREAD

**Issue by Banyc** [unoplatform/uno#4671]
## On which page?

<https://platform.uno/blog/announcing-uno-platform-support-for-visual-studio-code>

vs.

<https://platform.uno/docs/articles/get-started.html#vs-code>

## What's wrong?

<https://platform.uno/blog/announcing-uno-platform-support-for-visual-studio-code> is outdated.

## Any feedback?

Add a link to <https://platform.uno/blog/announcing-uno-platform-support-for-visual-studio-code> which directs to <https://platform.uno/docs/articles/get-started.html#vs-code>

**Comment by jeromelaban** [comment]
Thank you for the report!

We've updated the site.
