### ISSUE TITLE
[WASM] VSCode Unbound breakpoint

### ISSUE THREAD

**Issue by Banyc** [unoplatform/uno#4672]
## Current behavior

The breakpoint set on function `OnClick` is dark rather than red, which won't fire when the button is clicked.

## Expected behavior

The breakpoint should fire on click.

## How to reproduce it (as minimally and precisely as possible)

Follow <https://platform.uno/docs/articles/get-started.html#vs-code>.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [x] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

SDK list:

- `3.1.401`
- `5.0.100`

Verison of extension JavaScript Debugger (Nightly): `v2020.11.2617`

Version of extension "C#": `v1.23.6`

**Comment by jeromelaban** [comment]
Thank you for the report.

Could you indicate which version of the Uno.UI package you are using ?

**Comment by Banyc** [comment]
@jeromelaban It might be `3.3.0` found by a quick search on the whole project. Sorry for missing that important info.

**Comment by jeromelaban** [comment]
Thank you. Also forgot to ask, on which platform are you running vscode ?

**Comment by Banyc** [comment]
@jeromelaban It is on WIndows.

**Comment by Banyc** [comment]
This might be an issue with the vscode since I have encountered a similar issue on a blazorserver project.

**Comment by jeromelaban** [comment]
Thank you for the update. 

Indeed, Uno does not do much in this area so it may be specific to OmniSharp's support for Wasm debugging.

**Comment by jeromelaban** [comment]
This is fixed in Uno 4.0 and later
