### ISSUE TITLE
Popup in ControlTemplate of a custom control does not display at top left corner in Wasm

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno#4683]
## Current behavior

Create a custom control with a popup control.  Notice how it displays at the top-left corner when running in uwp.  In wasm, it displays with the popup's top-left corner in the center of the custom control.

## Expected behavior

Same behavior as uwp.

## How to reproduce it (as minimally and precisely as possible)

Please see attached project on #4660 

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by darenm** [comment]
I see a similar issue if the browser is resized after the initial display of a PopUp.
![image](https://user-images.githubusercontent.com/1674843/102554201-8918e100-4081-11eb-86e9-bed25a829844.png)
![image](https://user-images.githubusercontent.com/1674843/102554224-9635d000-4081-11eb-837b-db4c6082606d.png)
