### ISSUE TITLE
ComboBox selection not shown after load

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4686]
## Current behavior

Consider the following:

```
<ComboBox x:Name="TabWidthComboBox" AutomationProperties.Name="TabWidthComboBox" Margin="4,0,0,0" SelectedIndex="0" SelectionChanged="TabWidthComboBox_SelectionChanged">
	<ComboBoxItem Content="Equal"/>
	<ComboBoxItem Content="SizeToContent"/>
	<ComboBoxItem Content="Compact"/>
</ComboBox>
```

When the page with this is loaded, it looks like this:

![image](https://user-images.githubusercontent.com/1075116/101505093-43b72e00-3974-11eb-8a4b-f5b5ce2f5e17.png)

## Expected behavior

On UWP the selected item ("Equal") is shown.

## How to reproduce it (as minimally and precisely as possible)

Open "TabViewPage" sample (in `TabView` section of Samples app).

## Workaround

Use `{x:Bind}` to set the selected value (but not `{Binding}`, that seemed not to work too)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment]
Taking a look at this one.

**Comment by MartinZikmund** [comment]
Should work now #9340
