### ISSUE TITLE
Path shapes being drawn with a phantom transparent StrokeThickness

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#4688]
When drawing a `Path` on the screen, it seems there is a small gap between the `Path` itself and its neighboring views even when there is no `Margin` or `Padding` applied anywhere. See screenshots below

## Current behavior
Notice the green background of the `Grid` that is "leaking" through the edges of the blue `Path`
![Screenshot_1607454794](https://user-images.githubusercontent.com/4793020/101531865-c71b5400-3961-11eb-9793-8dc8fbdb4683.png)

## Expected behavior
Below is a screenshot from the same app running in UWP
![UWPPath](https://user-images.githubusercontent.com/4793020/101531912-d26e7f80-3961-11eb-822e-12df2055ec9b.PNG)

## How to reproduce it (as minimally and precisely as possible)

```xml
<Grid Background="Lime">
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto" />
        <RowDefinition Height="Auto" />
        <RowDefinition Height="Auto"/>
    </Grid.RowDefinitions>

    <Border Height="200"
            Background="Red" />

    <Rectangle Grid.Row="1" Height="300" Fill="Blue"/>
    <Border Height="800"
                Grid.Row="2"
            Background="Red" />
</Grid>
```

## Workaround

Current workaround is to set `StrokeThickness="0"` on the Path and then everything looks good

## Environment
- [x] Uno.UI
Nuget Package Version(s): 3.3.0 and 3.4.0-dev.latest

Affected platform(s):

- [x] iOS
- [x] Android

**Comment by Xiaoy312** [comment]
https://github.com/unoplatform/uno/blob/66999254a82ca50fa88372806541e8dcbb50b1af/src/Uno.UI/UI/Xaml/Shapes/Shape.cs#L91-L102

The workaround seems to be the necessary fix, since [the default value should be 0](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.shapes.shape.strokethickness?view=winrt-19041).

**Comment by kazo0** [comment]
Relates to #4509
