### ISSUE TITLE
Using a binding proxy inside a DataGrid column header does not work in Wasm

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno#4701]
## Current behavior

We use a dependency object defined in resources to access the current viewmodel inside a DataGrid column header.  Binding to this works in UWP, but not in Wasm.

## Expected behavior

Binding to a DependencyObject in resources works in Wasm.

## How to reproduce it (as minimally and precisely as possible)

Attaching a repro sln.
[App1.zip](https://github.com/unoplatform/uno/files/5668186/App1.zip)

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Xiaoy312** [comment]
You can also access the `DataContext` of `DataGrid` from from `DataGridColumnHeader`'s `DataContext`.
And, since `DataContext` is normally inherited from the parent control, you can just bind to it without having to use a binding proxy:
```diff
<ControlTemplate TargetType="primitives:DataGridColumnHeader">
    <Grid Background="{TemplateBinding Background}">
        <StackPanel
            Margin="{TemplateBinding Padding}"
            HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
            VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
-            DataContext="{Binding Source={StaticResource BindingProxy}, Path=Value}"
            Orientation="Horizontal">

+            <!-- Here {Binding} points to TestViewModel -->
            <CheckBox IsChecked="{Binding IsEnabled}" />
```

**Comment by jsinsel** [comment]
Thanks for pointing that out, it does work.  Coming from WPF, it wasn't expected since it doesn't work there.
