### ISSUE TITLE
Invalid CommandBar binding Command

### ISSUE THREAD

**Issue by HaoLife** [unoplatform/uno#471]
I used the MVVM binding command to CommandBar, but it didn't work, I used click and Use command in button was valid, and when I opened the log view, I found that the log had executed "raising command" but did not execute the command.

At the same time, the CommandBar on iOS does not show

## Minimal reproduction of the problem with instructions
<AppBarButton Icon="Delete" Label="delete"  Command="{x:Bind TestCommand}"/>

## Environment

Nuget Package: 
Uno.UI

Package Version(s): 
1.42.0  and above

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by HaoLife** [comment]
This issue occurs because the Uno.Analyzers compiler is bound to a binding error.

Example：

>     <CommandBar  Margin="0,20,0,0" DefaultLabelPosition="Right" Background="Transparent"  OverflowButtonVisibility="Collapsed">
>         <AppBarButton Icon="Delete" Label="delete"  Command="{x:Bind TestCommand}"/>
>         <AppBarButton Icon="ReShare" Label="test" Click="Button_Click" />
>     </CommandBar>
>     <Button Margin="0,5" Content="test command"  Command="{x:Bind TestButtonCommand}"/>
>     
>     <TextBlock Text="{Binding Title}" />


Compiler:



>     new global::Windows.UI.Xaml.Controls.CommandBar
>     {
>     	Margin = new global::Windows.UI.Xaml.Thickness(0,20,0,0),
>     	DefaultLabelPosition = Windows.UI.Xaml.Controls.CommandBarDefaultLabelPosition.Right,
>     	Background = SolidColorBrushHelper.Transparent,
>     	OverflowButtonVisibility = Windows.UI.Xaml.Controls.CommandBarOverflowButtonVisibility.Collapsed,
>     	// Source ..\..\..\..\..\..\..\UnoControlsSample.Shared\Controls\CommandBarPage.xaml (Line 27:14)
>     	PrimaryCommands = 
>     	{
>     		new global::Windows.UI.Xaml.Controls.AppBarButton
>     		{
>     			Icon = new Windows.UI.Xaml.Controls.SymbolIcon { Symbol = Windows.UI.Xaml.Controls.Symbol.Delete},
>     			Label = "delete",
>     			// Source ..\..\..\..\..\..\..\UnoControlsSample.Shared\Controls\CommandBarPage.xaml (Line 28:18)
>     		}
>     		.CommandBarPage_6f909572f43966eaff9b10af4188dd72_XamlApply((CommandBarPage_6f909572f43966eaff9b10af4188dd72XamlApplyExtensions.XamlApplyHandler1)(c5 => 
>     		{
>     			c5.SetBinding(global::Windows.UI.Xaml.Controls.AppBarButton.CommandProperty, new Windows.UI.Xaml.Data.Binding{ Path = @"TestCommand", CompiledSource = this });
>     												}
>     		))
>     		,
>     		new global::Windows.UI.Xaml.Controls.AppBarButton
>     		{
>     			Icon = new Windows.UI.Xaml.Controls.SymbolIcon { Symbol = Windows.UI.Xaml.Controls.Symbol.ReShare},
>     			Label = "test",
>     			// Source ..\..\..\..\..\..\..\UnoControlsSample.Shared\Controls\CommandBarPage.xaml (Line 29:18)
>     		}
>     		.CommandBarPage_6f909572f43966eaff9b10af4188dd72_XamlApply((CommandBarPage_6f909572f43966eaff9b10af4188dd72XamlApplyExtensions.XamlApplyHandler1)(c6 => 
>     		{
>     			c6.Click += Button_Click;
>     		}
>     		))
>     		,
>     	}
>     }



The question is, in this sentence,  "This", he's the CommandBar object.
c5.SetBinding(global::Windows.UI.Xaml.Controls.AppBarButton.CommandProperty, new Windows.UI.Xaml.Data.Binding{ Path = @"TestCommand", CompiledSource = this });

**Comment by jeromelaban** [comment]
The support for x:Bind has improved significantly, please open an other issue if there is still a problem.
