### ISSUE TITLE
Adding SkiaSharp.Views.Uno to Gtk and Wpf heads references Wasm variant and crashes at runtime.

### ISSUE THREAD

**Issue by mterwoord** [unoplatform/uno#4713]
## Current behavior

I'm trying to use the `SKXamlCanvas` from `SkiaSharp.Views.Uno`. 
I created a new uno solution using the dotnet templates, added the canvas to the mainpage. 
Referencing the nuget version 2.80.2 makes the code compiling, but at runtime, I get the error that the assembly `Uno.UI.Wasm` cannot be found.

## Expected behavior

The app should just run, and show any drawn content.

## How to reproduce it (as minimally and precisely as possible)

Create a new uno solution using `dotnet new unoapp`.
Add a reference to the `SkiaSharp.Views.Uno` nuget package, in the Gtk and Wpf projects. 
Run both projects.

## Workaround

No workaround known to me.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [X] Other: SkiaSharp.Views.Uno

Nuget Package Version(s):
- All latest, 3.3.0 for uno, 2.80.2 for Skia.

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [X] Skia
  - [X] WPF
  - [X] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report. 

SkiaSharp.Views is not yet supported when using the Skia head. A bit of structure is needed for SkiaSharp to be exposed properly, and it's not available yet.

I'll this issue to the Skia issues tracking : https://github.com/unoplatform/uno/issues/4309

**Comment by jeromelaban** [comment]
Will be fixed by https://github.com/mono/SkiaSharp/pull/1634

**Comment by jeromelaban** [comment]
Fixed in latest SkiaSharp preview
