### ISSUE TITLE
[Rider] Creating new solution makes a not-working Android head

### ISSUE THREAD

**Issue by mterwoord** [unoplatform/uno#4714]
## Current behavior

I created a new solution using `dotnet new unoapp`. Next thing I did was trying to debug the Android head in Rider.

## Expected behavior

The app should just start. This does work in Visual Studio.

## How to reproduce it (as minimally and precisely as possible)

1. Create a new solution using `dotnet new unoapp`. 
2. Open the solution in Rider.
3. Select the Android project as startup project.
4. Hit Debug and wait for the error to show up.

5. Open the solution in Visual Studio.
6. Select the Android project as startup project.
7. Hit Debug and wait for the error to show up.

## Workaround

Debug android in Visual Studio.

## Environment

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Latest on everything

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [X] Rider Windows (version: 2020.3 EAP 10)
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
Thank for the report. This may be a Rider specific issue.

Could you provide the error that the IDE is showing ?

**Comment by mterwoord** [comment]
Shoot. Completely forgot. Sorry.

It shows the following message in the Event Log:
`Error running 'Frontend.Droid': Failed to parse Activity Name`

**Comment by amolds** [comment]
I'm encountering the exact same error on a Mac.  I created a brand new Xamarin Forms project.  I can run the iOS head project.  However, launching the Android project from Rider results in the error listed above... Opening the exact same solution in Visual Studio for Mac I am able to run the Android project.  I've seen comments eluding to changing the ToolSet and Build / MSBuild version.  Currently mine is set to Auto detected (15.0.). I go back to why does it work in VS but not in Rider "out of the box."  I would love to see this resolved.  Thanks.

**Comment by Sergiu-Cosmin** [comment]
hello, 

having the same issue on Mac, with a Xamarin Forms project, the iOS project works fine, but the Android project says successfully installed but then I get ```Failed to parse Activity Name``` error when trying to link to the debugger, if I look on my emulator I see the app installed and it runs fine but I cannot debug it because of this error.

with VS for mac the same solution works fine, my ToolSet and Build / MSBuild version is set to autodetect and is on version 16.0, my emulator is running Android 10 and the targetSdk in my project is 29

**Comment by jeromelaban** [comment]
@Sergiu-Cosmin could you show the errors logs you've getting ?
