### ISSUE TITLE
Disabled tab in TabView is not visually distinctive

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4722]
## Current behavior

Disabled tab looks the same as other tabs in `TabView`

## Expected behavior

Should look different (as in UWP)

## How to reproduce it (as minimally and precisely as possible)

See the `TabViewPage` in Samples app. There is a disabled tab in the top `TabView` control.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by Youssef1313** [comment]
For some reason I'm not able to reproduce this issue.

![image](https://user-images.githubusercontent.com/31348972/126868714-5f931ac7-1966-409c-a21b-1b443f2f81e9.png)

**Comment by MartinZikmund** [comment]
@Youssef1313 It does not reproduce on UWP, but on other platforms it should (for example WASM)
