### ISSUE TITLE
[XAML Controls Gallery][Wasm][Chrome] No indicator is present for What's New Tab when first landing on page. 

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#4739]
## How to reproduce it (as minimally and precisely as possible)

1. Open the link https://xcgcanary.z27.web.core.windows.net/
2. Observe Indicator is present for the What's New tab when first landing on-page.

## Current behavior
No indicator is present for the What's New Tab when first landing on-page.

## Expected behavior
Indicator Should present for the What's New tab when first landing on-page.

**Attachment:**
**Actual Result:**
![XAML Controls Gallery Issue](https://user-images.githubusercontent.com/74563602/102114768-9d05de00-3e08-11eb-87eb-f00e61dea15f.png)

**Expected Result:**
![XAML Controls Gallery correct](https://user-images.githubusercontent.com/74563602/102114784-a1ca9200-3e08-11eb-8794-c2924a3d95b2.png)

## Environment

Nuget Package:

Package Version(s):
https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=22698&view=results

Affected platform(s):
- [ ] Windows

**Comment by dr1rrb** [comment]
This is probably linked to https://github.com/unoplatform/uno/issues/4906 and https://github.com/unoplatform/uno/issues/4786

**Comment by sakshi173** [comment]
Verified, Issue is Fixed -- Closing

Below is the screenshot.
![xaml 1](https://user-images.githubusercontent.com/74563602/106812595-ebcc3900-663d-11eb-8952-2e30d2cad65d.png)
