### ISSUE TITLE
Alignment issues & height issues for `TextBox` on macOS

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4740]
## Current behavior

The alignment and sizing of `TextBox`-based controls on macOS differs from other targets.

## Expected behavior

Sizing should match other platforms.

## How to reproduce it (as minimally and precisely as possible)

Clone https://github.com/MartinZikmund/Uno.ConwaysGameOfLife and run on macOS. Notice the alignment of controls below buttons does not match other platforms.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by carldebilly** [comment]
@ajpinedam Solution should be checked again after the merge of https://github.com/unoplatform/uno/pull/5217

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
