### ISSUE TITLE
[WASM] Implement DataPackage.Properties, DataPackageView.Properties, and DataPackageOperations for drag/drop support

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#4751]
## What would you like to be added:

Support for the drag-related DataPackage and DataPackageView properties members, along with DataPackageOperations.

## Why is this needed:

Drag/drop support will often require additional data about the controls being dragged and dropped.

Sample project demonstrating use of minimal desired implementation attached.  Color blocks may be moved between grids, though one grid only accepts a specific color block.

[DragDropRequirements.zip](https://github.com/unoplatform/uno/files/5710885/DragDropRequirements.zip)

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by dr1rrb** [comment]
This should not be too difficult to add, however as a workaround for now, you can use the [`DataPackage.SetData(string, object)`](https://github.com/unoplatform/uno/blob/master/src/Uno.UWP/ApplicationModel/DataTransfer/DataPackage.cs#L34) to add some custom content.
