### ISSUE TITLE
Navigation View Footer bug 

### ISSUE THREAD

**Issue by Strypper** [unoplatform/uno#4755]
## Current behavior
Navigation View cut off the content at the footer 

![image](https://user-images.githubusercontent.com/32596308/102589178-330b7280-4141-11eb-9913-0ef22d498cd7.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/32596308/102589237-49193300-4141-11eb-8b4b-a7de9da1e716.png)

## How to reproduce it (as minimally and precisely as possible)

Use NavigationView DisplayMode **LeftCompact**

## Workaround

No workaround for this

## Platform

Android: bug
IOS: not tested yet
MacOS: not tested yet
UWP: Normal
WASM: Normal
WPF: Normal

**Comment by jeromelaban** [comment]
Thank you for the report.

Were currently updating Uno to include a more recent version of the `NavigationView` control in https://github.com/unoplatform/uno/pull/4667. Once it is released, this issue may be revalidated.

**Comment by MartinZikmund** [comment]
@Strypper Out of curiosity, can you try the new `NavigationView` from Uno 3.4 (using the `Microsoft.UI.Xaml.Controls` namespace)?

**Comment by dr1rrb** [comment]
Hi @Strypper , I'm unable to reproduce with latest version of Uno with the "old version" (i.e. WUX). If you still encounter the issue, I would recommend you to move to the "new version" (in the `Microsoft.UI.Xaml.Controls` namespace), or please create a repro.
