### ISSUE TITLE
Cannot build UWP when include xmlns:skia

### ISSUE THREAD

**Issue by Strypper** [unoplatform/uno#4756]
## Current behavior
UWP can't be built

## Expected behavior
Build UWP normal

## How to reproduce it (as minimally and precisely as possible)
Include xmlns:skia="https://schemas.microsoft.com/winfx/2006/xaml/presentation"
and include skia in mc:Ignorable:"d skia"

Affected platform(s):
- [x] Windows - UWP

**Comment by jeromelaban** [comment]
Thanks for the report.

This is not something that uno can fix (it's the original Microsoft tooling), but the namespace can be changed.

Try with `xmlns:skia="http://uno.ui/skia"` instead.

**Comment by Strypper** [comment]
> xmlns:skia="http://uno.ui/skia"

Thanks you for your respond this workaround work
