### ISSUE TITLE
Support for WebView2

### ISSUE THREAD

**Issue by ghost** [unoplatform/uno#4758]
## What would you like to be added:
We would like to be able to use Uno to host Web content on iOS, Android and macOS devices.  The WinUI WebView2 component offers all that we need to terms of features, especially the JavaScript <--> C# environment interaction.

## Why is this needed:
We have *a lot* of web-based code which at the moment we run on a variety of platforms.  We use a Xamarin Forms based container at the moment for iOS and Android but would like to move to Uno as the container environment.

## For which Platform:
- [x ] iOS
- [x ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by davecarlisle** [comment]
We're in the same boat. Would love to see this moved up the priority list. It's the last remaining item for some key apps as we look to a possible path of flipping to WinUI and leveraging Uno. The sooner the better!  :)

**Comment by wangrd** [comment]
@jeromelaban Do you have any plan about it? It's been tow years...

**Comment by mnasers** [comment]
If would be great if this functionality was available in UNO platform and my company could move on from Xamarin.Forms.

**Comment by francoistanguay** [comment]
Work has already started and we hope to have an initial version within the next few weeks.
