### ISSUE TITLE
bugfix for markup extensions cause error "type x:Bind is used like a markup extension but does not derive from MarkupExtension"

### ISSUE THREAD

**Issue by fabiozehnder** [unoplatform/uno#4766]
## Current behavior

I upgraded Uno nuget packages from 3.1.6 to 3.3.0 and the Droid project doesn't compile anymore. The error is in a couple of pages using Windows.UI.Xaml.Controls.NavigationView with a custom DataTemplateSelector.  The issue is in the NavigationViewItem.Icon Glyph binding. Source generation fails.
## Expected behavior

Don't throw source generation exception.
## How to reproduce it (as minimally and precisely as possible)

<Page.Resources>
        <ResourceDictionary>
            <controls1:MenuItemTemplateSelector x:Key="selector" >
                <controls1:MenuItemTemplateSelector.ItemTemplate>
                    <DataTemplate x:DataType="controls1:MenuIcon">
                        <controls:NavigationViewItem 
                                Content="{x:Bind Title}">

                            <controls:NavigationViewItem.Icon>
                                <FontIcon android:FontFamily="ms-appx:///Assets/Fonts/SegMDL2.ttf" 
                                          not_android:FontFamily="Segoe MDL2 Assets" 
                                          Glyph="{x:Bind Glyph}" />

                            </controls:NavigationViewItem.Icon>
                        </controls:NavigationViewItem>
                    </DataTemplate>
                </controls1:MenuItemTemplateSelector.ItemTemplate>
            </controls1:MenuItemTemplateSelector>
        </ResourceDictionary>
    </Page.Resources>

this is the DataTemplateSelector:
[ContentProperty(Name = "ItemTemplate")]
    class MenuItemTemplateSelector : DataTemplateSelector
    {
        public DataTemplate ItemTemplate { get; set; }

        //public string PaneTitle { get; set; }

        protected override DataTemplate SelectTemplateCore(object item)
        {
            return item is Separator ? SeparatorTemplate : item is Header ? HeaderTemplate : ItemTemplate;
        }

        protected override DataTemplate SelectTemplateCore(object item, DependencyObject container)
        {
            return item is Separator ? SeparatorTemplate : item is Header ? HeaderTemplate : ItemTemplate;
        }

        internal DataTemplate HeaderTemplate = (DataTemplate)XamlReader.Load(
            @"<DataTemplate xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation'>
                   <NavigationViewItemHeader Content='{Binding Name}' />
                  </DataTemplate>");

        internal DataTemplate SeparatorTemplate = (DataTemplate)XamlReader.Load(
            @"<DataTemplate xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation'>
                    <NavigationViewItemSeparator />
                  </DataTemplate>");
    }

## Environment

Nuget Package:

- [vx] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [x ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [x ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x ] Visual Studio 2019 (version:16.8.3 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

This was fixed in recent dev builds and will be included in the upcoming Uno 3.4 release.

**Comment by legistek** [comment]
@jeromelaban would you mind pointing out the commit that fixed this so I can see what you did? I'm experimenting with some XAML trickery (albeit not with Uno in this particular case) and encountering the same issue. Thanks!

**Comment by jeromelaban** [comment]
It's likely to be this one: https://github.com/unoplatform/uno/pull/4561, but it's very specific to uno.

**Comment by legistek** [comment]
Thank you! Yes I realized later this wasn't about Intellisense, sorry.
I noticed that in the current Uno release you still need to have the XAML editor set to the UWP project in order to get any Intellisense working. Based on [this issue you raised with MS](https://developercommunity2.visualstudio.com/t/xaml-intellisense-does-not-use-contentpropertyattr/587980?from=email&viewtype=all#T-ND1352366) on the Visual Studio Community board I take it it's still an uphill climb to get Intellisense really fully working properly with custom XAML?

**Comment by jeromelaban** [comment]
It's getting there! 16.10 has improved the situation significantly, and we're tracking additional issues (for markup extensions specifically).

**Comment by legistek** [comment]
I know! I just tried out 16.10 myself and `ContentPropertyAttribute` seems to be working great. And `XmlnsDefinitionAttribute` already works. But `MarkupExtension` is the white whale. I can't figure out how Intellisense magically decides if my CLR type is derived from the "real" `MarkupExtension` or not. Public key token maybe? Driving me nuts. I've tried `TypeForwardedFrom` and dozens of other things.

Sorry this is so off topic LOL. I'm working on a XAML -> Blazor compiler. (Shhhh ;)) If I figure this issue out I'll let you know cause it would really be nice for Uno too not to have to have a UWP project to use Intellisense.

**Comment by legistek** [comment]
FYI @jeromelaban I opened a ticket for `MarkupExtension` [here](https://developercommunity.visualstudio.com/t/xaml-intellisense-does-not-use-markupextension-def/1358220?from=email) in case you want to weigh in. I think MS is under the impression that it would be too difficult to support `Binding` and `StaticResource` because of all the platform-specific logic (such as property paths or resource keys, support for F12, etc) but I feel like just recognizing the CLR types without would be a huge step forward and certainly sufficient for me at least.

**Comment by sigmarsson** [comment]
I experience this error with the Uno version as :

```
      <PackageReference Include="DryIoc.dll" Version="4.8.8" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="7.0.0-preview.3.22175.4" />
      <PackageReference Include="Microsoft.Windows.Compatibility" Version="6.0.0" />
      <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.3.0" />
      <PackageReference Include="Uno.WinUI.WebAssembly" Version="4.3.0-dev.170" />
      <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.3.0-dev.170" Condition="'$(Configuration)'=='Debug'" />
      <PackageReference Include="Uno.Wasm.Bootstrap" Version="4.0.0-dev.107" />
      <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="4.0.0-dev.107" />
```


![image](https://user-images.githubusercontent.com/43340959/168442150-19d57597-d013-4b11-8861-356f06284d16.png)

![image](https://user-images.githubusercontent.com/43340959/168442167-840feabc-b729-4743-be50-b7e4068acb73.png)

Windows desktop head works properly.
