### ISSUE TITLE
Support for newer versions of Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4767]
## What would you like to be added:

A workaround to support newer versions of `Microsoft.Extensions.Logging`.

## Why is this needed:

This is a common pain point of new Uno developers who upgrade all packages to latest stable version, which breaks app compilation.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
This new nuget package will be used to address this issue: https://github.com/unoplatform/uno.extensions.logging
