### ISSUE TITLE
Android: Border render wrong behavior itself and it's child

### ISSUE THREAD

**Issue by Strypper** [unoplatform/uno#4771]
This is the border I use 

```
                    <Border VerticalAlignment="Bottom" HorizontalAlignment="Stretch"
                            Padding="10">
                        <Border.Background>
                            <media:AcrylicBrush TintOpacity="0.2" AlwaysUseFallback="False"/>
                        </Border.Background>
                        <!--<TextBlock HorizontalAlignment="Center" VerticalAlignment="Center" 
                                   Text="UNDER CUT" FontSize="40" FontWeight="Bold" 
                                   HorizontalTextAlignment="Center" TextAlignment="Center"/>-->
                        <Rectangle Width="100" Height="100" Fill="Red" HorizontalAlignment="Center" VerticalAlignment="Center"/>
                    </Border>

```

As you can see I put the textblock and a rectangle inside it for better demonstration, so let talk about the border itself first. On UWP and WASM they render perfectly. But on Android the border render to be a very weird **Height** and **Width**,  bigger than I want, and then the child inside it place on the right-top corner. The Child element cannot be center or position with any of the **HorizontalAlignment** and **VerticalAlignment** and the reason why I include the text in there because I believe that the 
HorizontalTextAlignment="Center" and TextAlignment="Center" not being apply. I don't know about this, it's really hard to tell when the position is not working but I think it's something you guys should re-check see if it got effected 
## Current behavior

- Border displayment with HorizontalAlignment and VerticalAlignment not working
- Child inside border displayment is not working HorizontalAlignment and VerticalAlignment
![image](https://user-images.githubusercontent.com/32596308/102705260-1776a800-42b8-11eb-8b80-b09b0a019ea8.png)

## Expected behavior

Opposite of the Current behavior
UWP - WASM - WPF got it right 
![image](https://user-images.githubusercontent.com/32596308/102705241-c8c90e00-42b7-11eb-94da-c3b6fc2afd54.png)

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ?] iOS
- [ x] Android
- [ Ok] WebAssembly
- [ ?] WebAssembly renderers for Xamarin.Forms
- [ ?] macOS
- [ ?] Skia
  - [ Ok] WPF
  - [ ?] GTK (Linux)
  - [ ?] Tizen
- [ Ok] Windows

IDE:
- [ ] Visual Studio 2019 (version: )

**Comment by jeromelaban** [comment]
Thank you for the report. 

Could you:
- Add a screenshot of the UWP behavior as well as what you're seeing in UWP on Windows ?
- Add the  package version information 

Thanks!
