### ISSUE TITLE
[Epic] WinUI 3 third-party libraries support

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4774]
This epic is tracking the issues related to the support of the WinUI 3.0 APIs when using the Uno.WinUI package.

- [ ] Prism Library
- [ ] Xamarin.Forms Uno Renderers
- [ ] Windows Community Toolkit
- [ ] Xaml Behaviors

**Comment by MartinZikmund** [comment]
This is no longer relevant, Prism is supported, Community Toolkit is getting first-party support, Xaml Behaviors is supported
