### ISSUE TITLE
Localization does not change upon language selection - VS Version 16.8.3 - Uno 3.3.0 (ver. immediately before 3.4)

### ISSUE THREAD

**Issue by poepoe12002** [unoplatform/uno#4791]
## Current behavior

I followed the MS Doc: [https://docs.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest] in order to experiment with localization.  I created side by side projects, Uno (UWP) and UWP.  The same same folder / file hierarchy (String\en-US | de-DE\Resources.resw) in both projects.  Problem occurs when I add the de-DE folder and resourses file.
I set my computer's language to DE.  

Running the UWP reflects the language change whereas UNO(UWP) does not.   Please look in to this.  Let me know if I'm incorrect.

## Expected behavior

When running the UNO app the correct resources file should be chosen based on my OS language selection. (en-US or de-DE)

## How to reproduce it (as minimally and precisely as possible)

-----XAML in both projects:

```
  <Grid Background="{ThemeResource SystemChromeHighColor}">
    <StackPanel Margin="0,30,0,0" Orientation="Vertical">
      <TextBlock
        x:Uid="Greeting" HorizontalAlignment="Left" Foreground="Blue" />
      <TextBlock
        x:Uid="Farewell" HorizontalAlignment="Left" Foreground="Red" />
    </StackPanel>
  </Grid>
```

-----Resources files in both projects:
String\en-US\Resources.resw file contains:
Name                    Value
Application.Text    UdemyFinley
Farewell.Text         Goodbye
Greeting.Text        Hello

String\de-DE\Resources.resw file contains:
Name                    Value
Application.Text    UdemyFinley
Farewell.Text         Auf Wiedersehen
Greeting.Text        Hallo

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thank you for the report.

Could you provide a full sample of this issue, starting off of the Uno Project templates ? 

Note that Uno is not present when running the UWP project on Windows.

**Comment by poepoe12002** [comment]
Just did this anew.  Need to read and try a few things first.

**Comment by poepoe12002** [comment]
VS 16.8.4 - Uno 3.4.0.3
I created a new solution and had no problems.  Works on every platform I tried.  I used a different computer for this, so when I get home I will review the original code on that PC to see what the problem might have been.  Thanks.

**Comment by jeromelaban** [comment]
Thanks for the update. I'll close this issue for now, if you get additional information about your machine, please reopen this issue or open a new one.
