### ISSUE TITLE
MUX:NavigationView Incorrect Top Content Padding

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#4793]
## Current behavior

Using the new MUX NavigationView available in Uno 3.4, some display modes have content padding at the top that prevents the Content from appearing next to the hamburger menu.

![image](https://user-images.githubusercontent.com/17993847/103021502-3a9f9280-4518-11eb-949a-478493402c38.png)

This issue does not exist in Uno's Windows.UI.Xaml version of the control.

## Expected behavior

The "Accounts" title should appear next to the hamburger menu and the 'Edit' Button should be at the top. There should be no top content padding in NavigationViewPaneDisplayMode.LeftMinimal.

![image](https://user-images.githubusercontent.com/17993847/103021693-91a56780-4518-11eb-896c-cf7fdc594c2c.png)
(image from UWP)

## How to reproduce it (as minimally and precisely as possible)

 1. Create a navigation view with PaneDisplayMode = Microsoft.UI.Xaml.Controls.NavigationViewPaneDisplayMode.LeftMinimal
 2. Add any NavigationView.Content with top vertical alignment
 3. The Content is always below the hamburger menu

## Workaround

Negative margins I would expect.

## Environment

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):3.4.0

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
Thanks for the report, will check it 👍
