### ISSUE TITLE
MUX: NavigationView Does Not Select first NavigationViewItem

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#4794]
## Current behavior

Using the new MUX NavigationView in Uno 3.4, after the NavigationView loads for the first time, the selection indicator is not visible. The selected NavigationViewItem content is correctly shown -- only the indicator isn't visible.

![image](https://user-images.githubusercontent.com/17993847/103022117-4e97c400-4519-11eb-86b7-06a2bef93070.png)

I would guess this has something to do with animations.

## Expected behavior

The selection indicator should appear. 

![image](https://user-images.githubusercontent.com/17993847/103022220-8b63bb00-4519-11eb-874c-3f8068eb818b.png)

## How to reproduce it (as minimally and precisely as possible)

As described above.

## Workaround

Not tested, probably setting the selection a second time? Although in manual testing it appears a different NavigationViewItem must be selected and navigated to before selection will be valid.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.4.0

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
My guess it is due to the fact that due to different lifecycle of controls the `NavigationView` items we needed a workaround in which items are initialized late. And that may in turn cause the selection to be omitted. I will look into that

**Comment by robloo** [comment]
Hm, sounds like it might be tricky then. Regardless,, thanks a lot for taking the time to upgrade NavigationView. Its very nice to finally be able to share the same control with UWP.

**Comment by MartinZikmund** [comment]
@robloo thanks! Yes, it is a quite a bit trickier, especially as the control lifecycle differs between different targets, so it is tricky to get it just right to work on all of them but I think I am getting there slowly 😀

**Comment by navio-n** [comment]
I am having problems with first-time selection on both UWP and Android when using MVVM, data binding, and MenuItemTemplates:

...
MenuItemsSource="{x:Bind ViewModel.NavigationItems}"
SelectedItem="{x:Bind ViewModel.SelectedNavigationItem, Mode=TwoWay}">
...

            <muxc:NavigationView.MenuItemTemplate>
                <DataTemplate x:DataType="vm:MenuItem">
                    <muxc:NavigationViewItem Content="{x:Bind Title}">
                        <muxc:NavigationViewItem.Icon>
                            <SymbolIcon Symbol="{x:Bind Symbol}" />
                        </muxc:NavigationViewItem.Icon>
                    </muxc:NavigationViewItem>
                </DataTemplate>
            </muxc:NavigationView.MenuItemTemplate>

It doesn't work when programmatically going through pages also. Works only when clicking on the menu items. I found multiple issues about this so I am not sure where to post the issue?
