### ISSUE TITLE
Nested MenuFlyout (MenuFlyoutSubItem) LightDismiss Freezes the UI

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#4795]
## Current behavior

With nested MenuFlyoutItems (example below) the flyouts show correctly. However, if no selection is made and a click is made outside the flyout (to light dismiss) the flyout stays open. The UI locks up and no press is received anywhere else, even on the menu items.

Note that this issue only occurs when the MenuFlyoutSubItem is open.

```xaml
                    <Button.Flyout>
                        <MenuFlyout
                            Placement="Bottom">
                            <MenuFlyoutItem />
                            <MenuFlyoutSeparator />
                            <MenuFlyoutItem />
                            <MenuFlyoutSubItem>
                                <MenuFlyoutSubItem.Icon>
                                    <FontIcon  />
                                </MenuFlyoutSubItem.Icon>
                                <MenuFlyoutItem  />
                            </MenuFlyoutSubItem>
                        </MenuFlyout>
                    </Button.Flyout>
```

## Expected behavior

Should LightDismiss, no lockup

## How to reproduce it (as minimally and precisely as possible)

See above

## Workaround

None

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.4.0

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by robloo** [comment]
Possibly fixed by #5640, will test when I get a chance

**Comment by MartinZikmund** [comment]
@robloo were you able to retest this sometime?

**Comment by robloo** [comment]
Not yet, I'm still on an older 3.6.x build and was waiting for 3.8 to do another round of testing.

**Comment by robloo** [comment]
Tested again with 3.8.6 and the issue is still present. Light dismiss of a `MenuFlyoutSubItem` will completely freeze the UI.

**Comment by robloo** [comment]
So this issue no longer crashes the app. However, it is impossible to light dismiss a MenuFlyoutSubItem. The menu flyout simply will not close if you click outside of the menu. The only way to close the menu once the MenuFlyoutSubItem is opened is to make a selection.

Note that this issue doesn't happen for MenuFlyoutItem which works correctly. It is only in nested menus.

**Comment by jeromelaban** [comment]
Have you tried disabling native popups? This is likely related.

**Comment by robloo** [comment]
I made sure to disable native popups using:

```xaml
<Button.Flyout>
  <MenuFlyout
    Placement="Bottom"
    not_win:UseNativePopup="False">
     <!-- elements removed -->
  </MenuFlyout>
</Button.Flyout>
```

and also in the App constructor just in case:

```csharp
        public App()
        {
            this.InitializeComponent();

#if !NETFX_CORE
            // For Uno Platform apps, make sure to configure UWP styles instead of platform-native
            Uno.UI.FeatureConfiguration.Style.UseUWPDefaultStyles = true;
#endif
        }
```

Functionality was not changed:

![asdfasdf](https://user-images.githubusercontent.com/17993847/128546235-966d04b2-1a3e-424c-81da-550454e44ddb.gif)

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/blob/d97a9b606a201857bd514fdacd1bc95fb70604a7/src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyoutSubItem.cs#L274

Changing this to `true` causes the item to be light dismissed correctly. But light dismiss doesn't delegate to parents (ie, you'll have to do multiple clicks to completely dismiss the whole menu. Every click dismisses the inner-most open child)

**Comment by dr1rrb** [comment]
> 
> 
> https://github.com/unoplatform/uno/blob/d97a9b606a201857bd514fdacd1bc95fb70604a7/src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyoutSubItem.cs#L274
> 
> Changing this to `true` causes the item to be light dismissed correctly. But light dismiss doesn't delegate to parents (ie, you'll have to do multiple clicks to completely dismiss the whole menu. Every click dismisses the inner-most open child)

The dismiss-layer is handle directly `Popup` level (https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Controls/Popup/Popup.cs#L78) while it should be handled `PopupRoot` and/or `PopupPanel`, and clicking out of popups should dismiss all of them at once. Wondering however what is the behavior if a open a dismissable and a non dismissable popup and the same time.

**Comment by ramezgerges** [comment]
This doesn't reproduce and is tested in https://github.com/unoplatform/uno/blob/master/src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/MenuFlyoutTests/MenuFlyoutTests.cs#L202.
