### ISSUE TITLE
Setting Pivot.SelectedItem in Code Doesn't Update UI

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#4796]
## Current behavior

Setting the Pivot.SelectedItem property in code doesn't seem to update the UI. The item can only be selected by pressing it manually.

## Expected behavior

Should be possible to set Pivot.SelectedItem from code directly. 

## How to reproduce it (as minimally and precisely as possible)

```csharp
this.SettingsPivot.SelectedItem = this.LicensesPivotItem;
```

```xaml
<Pivot x:Name="SettingsPivot">
  <PivotItem x:Name="OtherPivotItem" />
  <PivotItem x:Name="LicensesPivotItem" />
</Pivot>
```

## Workaround

None tested

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.4.0

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment]
Note: `SelectedIndex` has the same issue (I presume it's the same root cause, but just noting to test both when fixing this)

**Comment by robloo** [comment]
Pivot was causing a few different issues including this one. Additonally, it is being removed from WinUI3. Therefore, my codebase moved to a TabView variant that functions more like a TabControl instead. This means this issue is no longer a concern on my end so I won't be following it closely. I'm not even sure if it has since been fixed.
