### ISSUE TITLE
MUX: Uno 3.4 NavigationView iOS and MacOS does not show all items

### ISSUE THREAD

**Issue by iosub** [unoplatform/uno#4798]
## Current behavior
On iOS And MacOS this example shows only the first item
`<Grid>`
`      <muxc:NavigationView x:Name="nvSample" IsTabStop="False">`
` <muxc:NavigationView.MenuItems>`
` <muxc:NavigationViewItem Content="Menu Item1" Tag="SamplePage1" />`
`  <muxc:NavigationViewItem Content="Menu Item2" Tag="SamplePage2" />`
`  </muxc:NavigationView.MenuItems>`
`  </muxc:NavigationView>`
`</Grid>`
![ios](https://user-images.githubusercontent.com/1330995/103059783-5d788800-45a6-11eb-89d0-5efc35a56202.png)

## Environment

Nuget Package:

- [x ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI 3.4
Affected platform(s):

- [x ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x ] macOS

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
@iosub Can you try setting `VerticalAlignment` to `Stretch` on the `NavigationView`? It should default to it, but I just want to check if it has any effect.

**Comment by iosub** [comment]
Hi

Yes I have try but it doesn't work.

I have found a workaround 
I have move the NavigationView from the Mainpage to another page.
On the MainPage I have set..
`   <Grid unoutils:VisibleBoundsPadding.PaddingMask="All" Background="Azure">`
` <Grid.RowDefinitions>`
` <RowDefinition Height="100"/>`
` <RowDefinition Height="*"/>`
` </Grid.RowDefinitions>`
`   <Button Content="ClickMe" Grid.Row="0" x:Name="ClickUX"/>`
` <Frame Grid.Row="1" x:Name="CTUX"  />`

and in the click event of the Button
`   this.CTUX.Navigate(typeof(Testpage));`

Now it works on iOS and Mac
![iosfix](https://user-images.githubusercontent.com/1330995/103131009-55504380-469f-11eb-9da2-6846d0c76bcf.png)
![mac](https://user-images.githubusercontent.com/1330995/103131011-55e8da00-469f-11eb-8714-32a39218dd09.png)

Hope you get a way to fixit with this information

THANK YOU!!

**Comment by MartinZikmund** [comment]
The problem can be reproduced in the SamplesApp by replacing the content of `MainPage` with:

```
<mux:NavigationView x:Name="NavigationViewControl" PaneDisplayMode="LeftMinimal">
	<mux:NavigationView.MenuItems>
	  <mux:NavigationViewItem IsSelected="True" Content="A" x:Name="A" />
	  <mux:NavigationViewItem Content="B" x:Name="B" />
	  <mux:NavigationViewItem Content="C" x:Name="C" />
	</mux:NavigationView.MenuItems>
	<mux:NavigationView.FooterMenuItems>
		<mux:NavigationViewItem Content="D" x:Name="D" />
	</mux:NavigationView.FooterMenuItems>
	<mux:NavigationView.Content>
	  <TextBlock Text="Test" Style="{ThemeResource HeaderTextBlockStyle}" />
	</mux:NavigationView.Content>
</mux:NavigationView>
```

Notice that after launch on iOS, the control loads in upper left corner and cannot be interacted with. Also note several stack traces in the debug output.

Interestingly, the problem also occurs when the control is added after the fact.

```
<Grid x:Name="RootGrid">
</Grid>
```

```
private async void MainPage_Loaded(object sender, RoutedEventArgs e)
{
	await Task.Delay(111);
	Microsoft.UI.Xaml.Controls.NavigationView navView = new Microsoft.UI.Xaml.Controls.NavigationView();
	navView.MenuItems.Add(new Microsoft.UI.Xaml.Controls.NavigationViewItem() { Content = "A" });
	navView.FooterMenuItems.Add(new Microsoft.UI.Xaml.Controls.NavigationViewItem() { Content = "A" });
	RootGrid.Children.Add(navView);
}
```

In this case the control loads properly its upper part, but the `FooterMenuItems` do not show up until the screen is rotated for example.

**Comment by dr1rrb** [comment]
FYI, PR #4977 fixes the stacktrace you noticed @MartinZikmund and fixed the issue when dynamically adding the `NavView` in the tree, but unfortunately the issue still occurs the `NavView` is in the start page of the app. Will continue investigation a bit later.
