### ISSUE TITLE
ThreadPoolTimer.CreatePeriodicTimer issue migrating from Uno 3.1.6 to Uno 3.4.0

### ISSUE THREAD

**Issue by fabiozehnder** [unoplatform/uno#4804]
## Current behavior

Using ThreadPoolTimer.CreatePeriodicTimer to schedule a periodic body of commands, those are executed only the first time.
## Expected behavior

The execution of the body must occur cyclically with the interval given as input.
## How to reproduce it (as minimally and precisely as possible)

myTimer = ThreadPoolTimer.CreatePeriodicTimer(
                    async (source) =>
                    {
                        await ReceiveMessagesFromDeviceAsync(cts.Token);
                    }
                    , TimeSpan.FromMinutes(1));
## Workaround

Simply switch to:

_myTask = Task.Run(async () =>
            {
                while (true)
                {
                    _myTaskCt.ThrowIfCancellationRequested();
                    try
                    {
                        {...}
                    }
                    catch (Exception ex)
                    {
                        {...}
                    }
                    await Task.Delay(500);
                }
            }, _myTaskCt);
## Environment

Nuget Package:

- [ x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [x ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x ] Visual Studio 2019 (version: 16.9.0 preview 2.0)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report!

This is a very curious issue as the code for this has not changed in a very long while. Would you mind creating a sample application from the Uno templates that reproduces the issue as closely as possible ? It'll help making sure there's nothing else that is impacting the behavior.
