### ISSUE TITLE
Support for MessageDialog in Skia

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4810]
## What would you like to be added:

Support for `MessageDialog` in Skia targets.

Maybe it would be worth considering rebuilding `MessageDialog` for all targets to use Uno UI, to have a unified experience. Currently native UI is used, which does not fit well with the rest of the app. A unified UI could be just based on `ContentDialog`, which is already available.

## Why is this needed:

UWP parity

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
When fixed, please re-enable showing dialog in SamplesApp `App.OnActivated`

**Comment by trungnt2910** [comment]
Any updates on this issue? I really hate adding hacks and stuff for Gtk and WPF to make the shared code run.

**Comment by MartinZikmund** [comment]
I think the easiest way to implement this is to use an extension interface and to implement the UI using `ContentDialog` in Uno.UI. This way the dialog would look the same on all existing and future targets and would reduce the need for platform-specific code. `MessageDialog` is discouraged by Microsoft anyway, so this sounds like a fair deal to me.

**Comment by trungnt2910** [comment]
We still have to handle the `Commands` button and stuff, which WPF natively supports, and so does Gtk, so I still think that a native implementation would be easier (I have been using reflection hacks to add it as an extension to my apps, but it looks quite ugly).

**Comment by MartinZikmund** [comment]
@trungnt2910 my only objection against "native" `MessageDialog` is that it looks quite out of place in a "WinUI" app but it is true that it looks out of place in case of UWP too :-D . Would you be interested in trying to implement this for WPF or GTK?

**Comment by trungnt2910** [comment]
I do have a full, standard-conforming implementation for GTK.
WPF supports 3 buttons, just like the docs, but it provides no options for changing the buttons' labels, so we must either mess up with Win32 API or implement our own form (I'd rather use a ContentDialog in this situation).
Or we might implement a basic "Yes" "No" "Cancel" "Ok" dialog (just like in WASM?)

**Comment by jeromelaban** [comment]
We probably should be providing a way for the MessageDialog to be implemented by default with something coming from Uno.UI so it because available by default for platforms that don't provide a native implementation. (wasm is a good one as the `alert` is pretty limited)

**Comment by sakshi173** [comment]
Verified this issue is fixed, Closed.
![Message Dialog](https://user-images.githubusercontent.com/74563602/159703056-1727b223-a07f-4f6e-8900-53fadd809ca0.png)
