### ISSUE TITLE
DisplayAttribute not found

### ISSUE THREAD

**Issue by stefanolson** [unoplatform/uno#4821]
## Current behavior

Error when building:
Error CS0246: The type or namespace name 'DisplayAttribute' could not be found (are you missing a using directive or an assembly reference?)

## Expected behavior

Should build.

## How to reproduce it (as minimally and precisely as possible)

1.	Create new Uno App
2.	Add System.ComponentModel.Annotations nuget package to all projects
3.	Add this code:
```
public enum CustomMessageBoxButtons
    {
        Ok,
        [Display(Description = "Yes, No")]
        YesNo,
#if WPF
        [Display(Description = "Yes, No, Cancel")]
#endif
        YesNoCancel,
#if WPF
        [Display(Description = "Ok, Cancel")]
#endif
        OkCancel
    }

```
4.	Build
5.	Error:
0>C:\temp\uno\UnoApp\UnoApp\UnoApp.Shared\MainPage.xaml.cs(35,10): Error CS0246: The type or namespace name 'DisplayAttribute' could not be found (are you missing a using directive or an assembly reference?)
0>C:\temp\uno\UnoApp\UnoApp\UnoApp.Shared\MainPage.xaml.cs(35,10): Error CS0246: The type or namespace name 'Display' could not be found (are you missing a using directive or an assembly reference?)
0>C:\temp\uno\UnoApp\UnoApp\UnoApp.Shared\MainPage.xaml.cs(35,18): Error CS0246: The type or namespace name 'Description' could not be found (are you missing a using directive or an assembly reference?)

See enclosed project: [UnoApp.zip](https://github.com/unoplatform/uno/files/5763937/UnoApp.zip)

## Workaround

None yet

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF

  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.8.3 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [X] Resharper (version: 2020.3)

**Comment by jeromelaban** [comment]
The error you're getting is likely to be on iOS/Android/macOS. You need to explicitly add a reference to `System.ComponentModel.Annotations` for these targets.

**Comment by stefanolson** [comment]
Thanks. From my first quick test that appears to solve it when it is in the shared library (e.g: the sample app).  However in my actual case, this is in a class library. How do I explicitly add a reference in a class library? Can't find a way to do that currently under each of the platform types in the class library. The really weird thing here is that I've got very similar code referencing that attribute which works fine in a separate class library in my solution, so don't understand why in this class library it doesn't work and the other one it does...

**Comment by stefanolson** [comment]
Right, I see that I've somehow added System.ComponentModel.DataAnnotations in assemblies for each target in the other class library. So there must be a way to do it.  I'll see if I can figure it out.

**Comment by stefanolson** [comment]
Ok. Workaround/Solution is:
<ItemGroup Condition="'$(TargetFramework)'=='xamarinmac20' or '$(TargetFramework)'=='xamarinios10' or '$(TargetFramework)'=='monoandroid10.0'  or '$(TargetFramework)'=='monoandroid90'">
		<Reference Include="System.ComponentModel.DataAnnotations" />
	</ItemGroup>
