### ISSUE TITLE
Older Android versions support

### ISSUE THREAD

**Issue by radutomy** [unoplatform/uno#4825]
Goal is to create an app that targets Android 8.1 (hardware is limited to this Android version)

## Current behavior

Dropping the Droid project's version from 10 to 8.1 results in a long list of errors.

## Expected behavior

Targeting an older Android version should yield a better experience, based on Uno's minimum platform requirements.

## How to reproduce it (as minimally and precisely as possible)

`dotnet new unoapp`

In the Droid project drop the target framework to Android 8.1:

![image](https://user-images.githubusercontent.com/454451/103643621-ed2a1900-4f4c-11eb-9f7e-4a1614df7f04.png)

You'll get the following errors:

![image](https://user-images.githubusercontent.com/454451/103641877-4d6b8b80-4f4a-11eb-87c3-37fb78d9cd03.png)

Notice Nuget package `Uno.UniversalmageDownloader` is not supporting Android 8.1, so we've downgraded it from `1.9.33` to `1.9.32`. Doing so yields the following errors:

![image](https://user-images.githubusercontent.com/454451/103644212-e8199980-4f4d-11eb-8742-9de5f3d55d75.png)

## Environment

Affected platform(s):

- [x] Android

IDE:

- [x] Visual Studio 2019 (version: 16.8.3)

**Comment by davidjohnoliver** [comment]
The minimum Android SDK supported by the current version of Uno.UI is Android 10. That's also the minimum version currently allowed by the Play Store for new apps and updates.

Do you **really** need to build with the Android 8.1 SDK? You say that your app needs to run on Android 8.1 devices, but apps built against the latest SDK should normally run fine on devices running older versions of Android. Nothing should preclude you from building an Uno Android app targeting Android 11 and running it on an Android 8.1 device.

**Comment by radutomy** [comment]
Our target hardware are not mobile phones, but rather custom industrial devices that use Android 8.1 as a base OS. 
I'm not sure what the implications are if building for Android 11 and deploying on older Android version (I'm not a mobile developer), but it's good to know you think this is not an issue.

Also on this topic, correct me if I'm wrong, but I find Uno's documentation to be a bit misleading here:

https://platform.uno/docs/articles/getting-started/requirements.html#android

> Android has several API settings that determine your application's compatibility. As a rule of thumb, always use the latest Android SDK Tools and Android API platform during development as you can target older Android versions while using the latest SDK.

One can infer from the last part that it is indeed possible to target older Android versions by changing the SDK target, but this is clearly not possible without having errors, as seen in my previous post.

**Comment by pkar70** [comment]
But also maximum (or, if you prefer, current) Android version on Kindle devices is 7.1 (https://en.wikipedia.org/wiki/Amazon_fire). And Kindle devices has life expectancy not half-year, but multi-years. 
But this is broader problem: "only for newest devices", or "also older devices". From ecological point of view, writing software for older devices means that people are not forced to throw away devices (and pollute environment). Yes, I know, many devices hasn't replaceable battery, so you have to throw it away and buy new device every year or so. But not only Kindle is designed to lasts for many years.

**Comment by davidjohnoliver** [comment]
> @davidjohnoliver
> 
> Can you clarify why the following statements seem to contradict each other?

Because they're too imprecise :)

The first statement should read that Uno no longer supports *compiling with the Android 9 SDK*. The second statement should read that Uno apps *run on Android 5 devices* (be it a phone, a Kindle Fire, or any other Android device). Both statements are true.

[This article](https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd) might help to explain the distinction.

**Comment by radutomy** [comment]
Thank you, it makes sense now. Closing this.
