### ISSUE TITLE
SymbolIcon on iOs: if bound via x:Bind only shows Smiley

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#4831]
## Current behavior
I have some buttons in my app that are bound to dynamically changing symbols. On iOs those buttons only show "smileys". Buttons with a SymbolIcon as Content that uses a statically-set Symbol work as expected.
![image](https://user-images.githubusercontent.com/1833242/103665862-3346a300-4f74-11eb-8a77-5e0bf274cf03.png)

## Expected behavior
The bound Symbol gets set on iOs, too.

## How to reproduce it (as minimally and precisely as possible)
Please have a look at this repo: [here](https://github.com/TopperDEL/NutzMich). The iOs-Head can be started directly and after the introduction should lead you to the main screen showing some contents. Directly above you should see buttons with smileys instead of "real" symbols.

## Workaround
None currently

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.4.0

Affected platform(s):

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report. 

Would you mind creating a smaller repro for the application so it's easier to pinpoint ?

**Comment by TopperDEL** [comment]
Will do! My first attempt is working, but is also not exactly the same. Might be related to binding to an observablecollection or doing the binding in a DataTemplate, which is not yet implemented in my repro.

**Comment by TopperDEL** [comment]
Hm, it is working in my repro-repo: https://github.com/TopperDEL/SymbolIconBindingTest
But it's still not working in my real app. The only difference is that in my production app the ItemsControl with the Symbol-binding is itself within another DataTemplate. It has this structure:

NavigationView->HeaderTemplate->DataTemplate->ItemsControl->ItemTemplate->DataTemplate->Button->Content->SymbolIcon->Binding

Any other ideas? I see if I can extend the repro and see if it shows the same error then - but it gets more and more complex and so my original production-app could be used, also.

**Comment by TopperDEL** [comment]
^^ @jeromelaban

**Comment by jeromelaban** [comment]
Thanks for the repro (even if not working). Does the SymbolIcon binding working in your application in other less complex location ?

**Comment by TopperDEL** [comment]
I do not have other Binding to SymbolIcons in that app. I just have some static set icons (like in the screenshot above the Add-Symbol +).

**Comment by jeromelaban** [comment]
Got it. Could you also try with normal bindings, if possible ?

**Comment by TopperDEL** [comment]
I've just added a simple Button with a SymbolIcon as content that is bound to a value on my view - and it also shows the Symbol. So it does not seem to be related to DataTemplates and such. But it is still embedded in a part of the NavigationView. I'll try adding it to a place outside of a NavigationView.

**Comment by TopperDEL** [comment]
It also shows the smiley if it is the only thing on the page. Seems something is wrong with that project. Any idea where to start searching @jeromelaban ?

**Comment by jeromelaban** [comment]
It probably means that the font is somehow not set properly. Can you diff your csproj with the one created by the default Uno project template ?

**Comment by TopperDEL** [comment]
The csproj-files do not differ except that I have set the lang-version to 8 in my app. But the embedding of the font is the same.
I found out that my font differed from the one in the template. But even if I replace it in my app with the new one from the template it shows the same error.

**Comment by jeromelaban** [comment]
Is the font file the same ? We updated it at some point, you may have an earlier version.

**Comment by TopperDEL** [comment]
There must be something in my app that reacts weird. I had the other issue where an async button-click-handler does not get invoked - the exact same coding is working on another page, where the button is NOT within a datatemplate.

**Comment by TopperDEL** [comment]
> Is the font file the same ? We updated it at some point, you may have an earlier version.

As said above, it was different. But I replaced it with the one from the template and it is still not working.

**Comment by TopperDEL** [comment]
Is that relevant: "Failed to apply Font XamlAutoFontFamily"? @jeromelaban

**Comment by TopperDEL** [comment]
I'm using Uno.Material. Might that affect it?

**Comment by TopperDEL** [comment]
I've updated the repro to be as close to the original one as possible - but now it doesn't build anymore and I can't find the reason.
@jeromelaban: Maybe you see the issue?
Otherwise I'm still completely lost with that Smiley-Symbols-Issue. I think I have to switch to a different implementation for this as this is the last bit preventing that app from going to the store.

**Comment by jeromelaban** [comment]
I don't know what may be causing the issue without a repro, unfortunately. 

Did you try using `{Binding}` as I suggested before ? Also a `SymbolIcon` is backed by a TextBlock: 

SymbolIcon: 
https://github.com/unoplatform/uno/blob/ef5961fd9bf1fb6c617de6842ff4cc3643fdf47b/src/Uno.UI/UI/Xaml/Controls/SymbolIcon/SymbolIcon.cs#L11

And FontIcon:
https://github.com/unoplatform/uno/blob/2ca896e4a213c4181cecf5725ddc715dfe784aaf/src/Uno.UI/UI/Xaml/Controls/FontIcon/FontIcon.cs#L17

You can try putting an explicit TextBlock with the font symbol directly.

**Comment by TopperDEL** [comment]
It's working with "Binding" instead of "x:Bind"! Weird, I thought I've definitely tested it. But it's ok then, from my point of view.

Thanks @jeromelaban for not giving up on me. :)
