### ISSUE TITLE
[Skia] Single file publishing fails at runtime

### ISSUE THREAD

**Issue by GF-Huang** [unoplatform/uno#4840]
I had build an app.

![image](https://user-images.githubusercontent.com/4510984/103722293-971bab00-500a-11eb-87d0-a16684784df4.png)

But the doc say `cd xxx.Skia.Gtk`, it is a file not a directory, how to cd it?

![image](https://user-images.githubusercontent.com/4510984/103722345-b61a3d00-500a-11eb-8f6c-43a83628d0a1.png)

**Comment by GF-Huang** [comment]
Still not work.

![image](https://user-images.githubusercontent.com/4510984/103722829-d1397c80-500b-11eb-8b3f-309e823f8305.png)

**Comment by jeromelaban** [comment]
Thanks for the report. 

Which version of Uno.UI are you using ?

**Comment by GF-Huang** [comment]
My project was created by `Uno Platform Solution Templates`. I delete some platform project which I don't need, I think this does not cause this issue.

![image](https://user-images.githubusercontent.com/4510984/103727785-1ca55800-5017-11eb-8506-486efa479a4b.png)

![image](https://user-images.githubusercontent.com/4510984/103727824-39419000-5017-11eb-9ee2-100ebfe82bcd.png)

**Comment by microhobby** [comment]
@GF-Huang how are you publishing the project to run on the target?

**Comment by microhobby** [comment]
@GF-Huang I can reproduce this only when I select the `Self-contained` and `single file` option:

![image](https://user-images.githubusercontent.com/2633321/103734116-02915880-4fca-11eb-95a1-3f4ab8ce9c9a.png)

![image](https://user-images.githubusercontent.com/2633321/103734076-ea213e00-4fc9-11eb-9974-3f1a76d9aab6.png)

Selecting only the `Self-contained` and making sure not select the `Produce single file` works:

![image](https://user-images.githubusercontent.com/2633321/103734246-52701f80-4fca-11eb-83e9-cb6c0f0585bc.png)

**Comment by GF-Huang** [comment]
Yes, I use `linux-arm` and `single file` publish.

**Comment by GF-Huang** [comment]
When I not select `single file`, issue solved. But Is there any workaround for `single file`? Or any deploy solution for Linux?

**Comment by jeromelaban** [comment]
Got it, thanks for the troubleshooting. Single file is not yet supported, but we intend to add support for it soon. I'll rename this issue to track this.
