### ISSUE TITLE
Add support for ApplicationLanguages.Languages

### ISSUE THREAD

**Issue by ajpinedam** [unoplatform/uno#4856]
## What would you like to be added:
Add the support of the `Windows.Globalization.ApplicationLanguages.Languages` for non-mobile platforms.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by carldebilly** [comment]
This is implemented in the PR #4956
