### ISSUE TITLE
Add support for WinUI UniformGridLayout

### ISSUE THREAD

**Issue by ajpinedam** [unoplatform/uno#4859]
## What would you like to be added:

Add support for `Microsoft.UI.Xaml.Controls.UniformGridLayout`

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by sigmarsson** [comment]
Is it feasible to roll this out with 3.8 ?

**Comment by davidjohnoliver** [comment]
> Is it feasible to roll this out with 3.8 ?

Good news - this was added recently (https://github.com/unoplatform/uno/pull/5714), so it will indeed be available in 3.8.
