### ISSUE TITLE
AssemblyVersion and FileVersion always 255.255.255.255

### ISSUE THREAD

**Issue by queequac** [unoplatform/uno#4865]
## Current behavior

All assemblies have the same file and assembly version of 255.255.255.255 when looking at the file properties or when checking the assembly at runtime.
This prevents checking or retrieving the currently referenced version of Uno at runtime (which I do for all my open source dependencies to give some details in the app's about page - where only Uno shows up with always the same wrong number mentioned above.)
Furthermore the strong assembly name is not unique for different releases.

## Expected behavior

All assemblies should actually have the correct file and assembly version of the associated Uno release, such as 3.4.0

## How to reproduce it (as minimally and precisely as possible)

Look at the DLL's version in explorer's file properties dialog.
Or check  `new AssemblyName(assembly.FullName).Version`

## Workaround

Unfortunately none.

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): all

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report. The versioning is explicitly handled this way to avoid quirks around version management. The dependency management is donc through nuget, and only there.

If you need to get the Uno version, you can use the InformationalVersion attribute, which contains the full version, including the hash.

We will not strong-sign assemblies either, for the same reasons of version management I mentioned above.

Also, if you need to validate for specific features, you can use the `ApiInformation` class, which provides the ability to determine f if a type, method or property is implemented by Uno.

Is there another reason for which you need to know the version at runtime ?

**Comment by queequac** [comment]
Thanks for clarification, Jérôme.

Not sure if I really like the handling, since it makes identifying the actual version somehow tricky and showing a wrong/invalid version all over the places is little bit of a mess... but for my concrete use case I can take that info from the InformationalVersion attribute.

**Comment by jeromelaban** [comment]
This is a handling that differs from common versioning indeed, but aligns with the handling done by WinRT.

We may revisit this once all Uno supported targets are running on .NET 6 and later, but it will take at least two years until the compatibility with Xamarin.iOS/Android/macOS is not needed anymore.
