### ISSUE TITLE
[WASM] Incorrect scope of RadioButton groups

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#4868]
## Current behavior

All the radio buttons that are rendered on the page with the same `GroupName` are grouped together, even if they are in different user controls.

## Expected behavior

`RadioButtion` groups with the same name in different user controls should not be considered a single group but rather separate groups (like in UWP).

## How to reproduce it (as minimally and precisely as possible)

Add a radio button to a page with `GroupName="A"`. Add a radio button with the same group name to a user control and then add two of those user controls to the page. Notice that all 3 radio buttons are grouped together. They should be 3 separate groups.

## Workaround

Write code after `InitializeComponent()` in the user controls that assigns a unique ID to that user control (i.e. via an incremented static field), then iterate over all the radio buttons and adds that unique ID to each group name.

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

v3.4.0 and v3.5.0-dev.76

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report!

This is indeed an incorrect behavior, though in the meantime, would the `RadioButtons` control make sense for your scenario ?

**Comment by mikernet** [comment]
No problem. We just implemented the workaround indicated above for now.

**Comment by MartinZikmund** [comment]
@mikernet I have tested your repo case and it seems the radio buttons are still grouped even on Windows (only one radio button from the 9 displayed on page can be selected at once):

**GroupNameUserControl.xaml**

```
<StackPanel>
    <RadioButton GroupName="A" Content="1" />
    <RadioButton GroupName="A" Content="2" />
    <RadioButton GroupName="A" Content="3" />
</StackPanel>
```

**MainPage.xaml**
```
<StackPanel Padding="12">
    <StackPanel>
        <RadioButton GroupName="A" Content="1" />
        <RadioButton GroupName="A" Content="2" />
        <RadioButton GroupName="A" Content="3" />
    </StackPanel>
    <local:GroupNameUserControl />
    <local:GroupNameUserControl />
</StackPanel>
```

Does this match your scenario or did you mean something different?

**Comment by mikernet** [comment]
Haha...whatever I was doing before I could swear there was a behavioral difference between UWP and Uno because I only needed the workaround code on Uno platform builds. Looking back through source control it might have actually been a UWP bug allowing multiple radio buttons in the same group to be checked if they are all disabled because you're right, it does group them together across controls.

I'll close this for now :)
