### ISSUE TITLE
TabView Foreground property is not applied

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4874]
## Current behavior

Property ForeGround is not applied. UWP shows the correct ForeGround color, WASM keeps default value of "Black".

## Expected behavior

Foreground is applied to inactive tabs as in UWP.

## How to reproduce it (as minimally and precisely as possible)

See https://github.com/unoplatform/uno/issues/4628

## Workaround

None

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
So far I have discovered that WinUI 2.5 no longer shows the correct `Foreground` either, although I am not sure what causes this between 2.4.3 and 2.5.

The "correct" way to change foreground is shown in one of the samples:

```xaml
<controls:TabViewItem x:Name="SecondTab" Header="SecondTab" IsClosable="True">
	<controls:TabViewItem.Resources>
		<!-- Do not remove or change this! We are verifying this resource in a TabView InteractionTest. -->
		<SolidColorBrush x:Key="TabViewItemHeaderForeground" Color="#FF008000" />
	</controls:TabViewItem.Resources>
	<controls:TabViewItem.IconSource>
		<controls:SymbolIconSource Symbol="Shop"/>
	</controls:TabViewItem.IconSource>

	<StackPanel Padding="16">
		<TextBlock>Shop text</TextBlock>
		<Button Content="SecondTabButton" AutomationProperties.Name="SecondTabButton"/>
	</StackPanel>
</controls:TabViewItem>
```

Unfortunately, this approach does not work in Uno either due to #4881
