### ISSUE TITLE
Binding to TabView.TabItemsSource is not working

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4875]
## Current behavior

When binding `TabItemsSource` to an `ObservableCollection`, tabs are not rendered.

## Expected behavior

TabItemsSource can be bound via x:Bind

## How to reproduce it (as minimally and precisely as possible)

See https://github.com/unoplatform/uno/issues/4628

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
I think this could now be working after the `Items-ItemsSource` adjustments, I will check

**Comment by MartinZikmund** [comment]
So the binding itself is working after updating to latest Uno, but the content of the tabs is not correctly bound. Will investigate further
