### ISSUE TITLE
TabView.TabStripFooter does not work when used from code-behind

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4876]
## Current behavior

When setting TabItemsSource in code, a databound TabStripFooter is not rendered anymore.

## Expected behavior

TabStripFooter is displayed regardless of the way TabItemsSource is set (in code/databindig)

## How to reproduce it (as minimally and precisely as possible)

See https://github.com/unoplatform/uno/issues/4628

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
@s-beltz It seems the `TabStripFooter` is now working when I updated to latest Uno.UI preview (3.5.0-dev.80). Can you check if is ok, or some additional adjustments are needed? Thanks!

**Comment by s-beltz** [comment]
@MartinZikmund I opened the issue for Uno.UI 3.3.0. 
It seems that Uno.UI 3.4.0 already fixed this issue. So yes, currently everything works as expected and this issue can be closed. Thanks for your support!
