### ISSUE TITLE
BitmapImage.SetSource does not clone its input

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#4878]
## Current behavior
When I update my app from Uno.UI 3.3.0 to Uno.UI 3.4.0 (and the pre-release 3.5.0*) my Image-Bindings in a list view do not show any image anymore. I did not change anything else.
The interesting part is: I have an issue with the SymbolIcons as mentioned [here](https://github.com/unoplatform/uno/issues/4831) and that gets resolved when updating to a newer Uno-UI.version than 3.3.0.

So either I have Symbols or I see me images - but not both...

The images are bound within a DataTemplate, as is the Symbol. I'll may try to use a "Binding" instead of "x:Bind" - but it works with 3.3.0 - so this is a regression.

## Expected behavior
The Images are shown again.

## How to reproduce it (as minimally and precisely as possible)
That's the tricky part - I'm not sure and the app is quite complex. [This](https://github.com/TopperDEL/NutzMich) is the app and it's currently easier for me to just link it. Clone the latest version and start it - after the welcome screen you should see a list of items - they have no images but the button above show a Refresh-Symbol. Now go back to Uno.UI on the iOs-Head and start again - the list now shows images but the Refresh-Icon changed to a smiley.

I searched around if there are any changes between bot Uno-Version that might point to this error, but I could not find any.

## Workaround
None yet

## Environment

Nuget Package:

- [X] Uno.UI 3.3.0 / 3.4.0
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

Can you try databinding the image source to a TextBlock to see if the data is provided properly?

**Comment by TopperDEL** [comment]
Ok, the Binding seems to not be the problem. It probably is the BitmapImage and it's SetSource-Method. If I change that to SetSourceAsync - it works. I'll see if I find a change there - but the fix is easy and does not break anything.

**Comment by jeromelaban** [comment]
Are you using `SetSource` explicitly when the issue happens ?

**Comment by TopperDEL** [comment]
Not sure what you mean with "explicitly" here. Technically I'm Binding to a Base64-encoded image that I convert to a `BitmapImage `in a ViewModel-Property. And I did this via `SetSource `before which worked until (including) 3.3.0. Since 3.4.0 it does not work anymore. So I changed it to `SetSourceAsync `and that works again.

**Comment by jeromelaban** [comment]
Got it. Could be related to the changes done by this class: https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Media/Imaging/BitmapSource.cs#L80-L83

**Comment by TopperDEL** [comment]
Not sure if I can add anything here. Just for reference: [this](https://github.com/TopperDEL/NutzMich/blob/323d449901a240905ce064c966e63ea22b2cc972/NutzMich.Shared/Models/AttachmentImage.cs#L31) has been the problematic line. It stated `SetSource` before. As it seems RandomAccessStreams are now supported on Uno, I will change that implementation anyways as the temporary MemoryStream there is no longer necessary.

But I'm still wondering why `SetSource` does not work anymore as it should be the same logic however I call the methods. But maybe I don't see something relevant.

If I can help or add information, let me know! For me the issue is resolved by switching to `SetSourceAsync`.
