### ISSUE TITLE
WebView not available on Mac OS - "No view of type UnoWKWebView found in children"

### ISSUE THREAD

**Issue by slewallen** [unoplatform/uno#4889]
## Current behavior

Adding a simple entry for WebView to a xcml file, such as:

<WebView x:Name="webView1" Source="https://www.apple.com"/>

... results in no WebView being rendered and the following in the console:

fail: Windows.UI.Xaml.Controls.WebView[0]
      No view of type UnoWKWebView found in children, are you missing one of these types in a template ? 

The same exact code works fine on iOS.

## Expected behavior

The WebView is rendered and the failure message is no longer produced.

## How to reproduce it (as minimally and precisely as possible)

Create a simple sample project via:

dotnet new unoapp -o MyProject --skia-wpf=false

Then make the MainPage.xaml:

<Page
    x:Class="MyProject.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:MyProject"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
		<TextBlock Text="Hello, world!" Margin="20" FontSize="30" />
        
        <WebView x:Name="webView1" Source="https://www.apple.com"/>

        <Button x:Name="button1">My Button String</Button>
    </Grid>
</Page>

## Workaround

None known.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ X] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ X] Visual Studio for Mac (version: 8.8.5 (build 18))
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Details of install:

Visual Studio Community 2019 for Mac
Version 8.8.5 (build 18)
Installation UUID: 0ce68fa8-f942-4210-b5fd-6ed2c81ba6d3
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

Mono Framework MDK
Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

Roslyn (Language Service)
3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

NuGet
Version: 5.8.0.6860

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/5.0.102/Sdks
SDK Versions:
	5.0.102
	5.0.100
	3.1.405
	3.1.404
	3.1.402
	3.1.302
	3.1.100
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.2
	5.0.0
	3.1.11
	3.1.10
	3.1.8
	3.1.6
	3.1.0
	2.1.23
	2.1.22
	2.1.20

.NET Core 3.1 SDK
SDK: 3.1.405

Xamarin.Profiler
Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 12.3 (17715)
Build 12C33

Xamarin.Mac
Version: 7.2.0.3 (Visual Studio Community)
Hash: c51fabee8
Branch: xcode12.3
Build date: 2020-12-10 21:05:04-0500

Xamarin Designer
Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

Xamarin.iOS
Version: 14.8.0.3 (Visual Studio Community)
Hash: c51fabee8
Branch: xcode12.3
Build date: 2020-12-10 21:05:05-0500

Xamarin.Android
Version: 11.1.0.26 (Visual Studio Community)
Commit: xamarin-android/d16-8/a36ce73
Android SDK: /Users/slewallen/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

Microsoft OpenJDK for Mobile
Java SDK: /Users/slewallen/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

Android Device Manager
Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

Build Information
Release ID: 808050018
Git revision: e83d51ec050ffcdd573462fc1889b58cfe1a5ad5
Build date: 2021-01-07 14:45:50-05
Build branch: release-8.8
Xamarin extensions: e83d51ec050ffcdd573462fc1889b58cfe1a5ad5

Operating System
Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
MonoGame Extension 3.8.0.1641

**Comment by jeromelaban** [comment]
Thanks for the report.

The code for this control is mostly shared between iOS and macOS, and the behavior should be very similar.

## Note to contributors

The style for this control is this one: 
https://github.com/unoplatform/uno/blob/6d82ed0d052a74fa580f246a5ea51374fb1b38cc/src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml#L8389-L8397

but the NativeWebView control is not implemented:
https://github.com/unoplatform/uno/blob/6d82ed0d052a74fa580f246a5ea51374fb1b38cc/src/Uno.UI/UI/Xaml/Controls/WebView/NativeWebView.macOS.cs#L8-L11

And implementation would require a implementation similar to this one:
https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Controls/WebView/NativeWebView.iOS.cs#L7-L9
