### ISSUE TITLE
Integrate Mapsui Maps into Uno Platform

### ISSUE THREAD

**Issue by wjax** [unoplatform/uno#4891]
## What would you like to be added:
Integrate mapsui into the uno platform control catalog
https://github.com/Mapsui/Mapsui
## Why is this needed:
Mapsui is a full featured map control supporting layers, entities, animations and geographical information. 
It already works in xamarin so it may not be too difficult to adapt it to Uno
## For which Platform:

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
This is an interesting library, thanks for sharing.

For now, there's a missing piece (#4713 and https://github.com/unoplatform/uno/issues/4309) in our Skia backend that does not provide access to SkiaSharp, but we'll make updates to provide that support in both Uno and the official SkiaSharp.

**Comment by jeromelaban** [comment]
Uno support is present in 4.0 beta builds of mapsui.

**Comment by wjax** [comment]
This is so great. Thanks @jeromelaban and Paul from Mapsui.
