### ISSUE TITLE
ContentTemplate not applied to Button when using TextBlockButtonStyle

### ISSUE THREAD

**Issue by s-beltz** [unoplatform/uno#4909]
## Current behavior

When using **ThemeResource TextBlockButtonStyle** on a Button element ContentTemplate will not be applied on non UWP platforms.

```
<Button Style="{ThemeResource TextBlockButtonStyle}"
                    Content="{x:Bind Path=DefaultViewModel, Mode=OneWay}"
                    ContentTemplate="{StaticResource HeaderButtonDataTemplate}"
                    VerticalAlignment="Center"
                    HorizontalAlignment="Center"
                    Margin="50" />
```

UWP:
![image](https://user-images.githubusercontent.com/57802605/104617379-aa261f00-568b-11eb-9e0c-b904bc71abb9.png)

Non UWP platforms:
![image](https://user-images.githubusercontent.com/57802605/104617518-d17cec00-568b-11eb-95a0-a337cbeae6de.png)

## Expected behavior

ContentTemplate is applied also on non UWP platforms.

## How to reproduce it (as minimally and precisely as possible)

Repro-App:
[apliconus-uno-datatemplate-issue.zip](https://github.com/unoplatform/uno/files/5815608/apliconus-uno-datatemplate-issue.zip)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
    Uno.UI Version="3.4.0"

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
**Note to contributors**: This is most likely this bug manifesting: https://github.com/unoplatform/uno/issues/857

The workaround in Uno is to explicitly template-bind `ContentPresenter.ContentTemplate` in the `TextBlockButtonStyle`: https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml#L8409

(see eg https://github.com/unoplatform/Uno.WindowsCommunityToolkit/pull/120/files)
