### ISSUE TITLE
 [Uno Gallery][Combobox] The text is not left aligned for the combobox list

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#4910]
**How to reproduce it**
1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Click on “Combobox” item from the list.
3. Observe the text is not left aligned for combobox.

**Current behavior**
The text is not left aligned and displaying in center for combo box list. 

**Expected behavior**
The text should be left aligned for combo box list.

**Attachment:**
**Actual Result:**
![error 1](https://user-images.githubusercontent.com/74563602/104631804-c2d20d00-566a-11eb-9e3b-01c30ae2b9f7.png)

 **Expected Result:**
![correct combobox](https://user-images.githubusercontent.com/74563602/104631829-cd8ca200-566a-11eb-8931-31e42d5c604d.png)

Environment
Nuget Package:

**Package Version(s):**
https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=23486&view=results
Affected platform(s):
Windows

**Comment by jeromelaban** [comment]
The issue is caused by https://github.com/unoplatform/uno/pull/4411

**Comment by carldebilly** [comment]
I confirmed the problem is around the "MaxLines" feature of the TextBlock:
https://playgroundcanary.z19.web.core.windows.net/#01191b1f

**Comment by sakshi173** [comment]
**Verified, Issue is Fixed -- Closing**


![Gallery combobox](https://user-images.githubusercontent.com/74563602/105552728-57271a00-5cd2-11eb-98f8-8a940ef2b3e6.png)
