### ISSUE TITLE
[Uno Gallery] Listview item name display is not left aligned on the top of the page.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#4912]
**How to reproduce it**

1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Click on any item from the listview item list ( for example “CommandBar” tab)
3. Observe the “CommandBar” name display on the top of the page is not left aligned and displaying in center.

**Current behavior**
The Item name is not left aligned and displaying in center on the top of the page.

**Expected behavior**
The Item name should be display as left aligned on the top of the page.

**Attachment:**
**Actual Result:**
![error item name](https://user-images.githubusercontent.com/74563602/104634237-5a852a80-566e-11eb-9614-655a3c8285df.png)

**Expected Result:**
![correct item name](https://user-images.githubusercontent.com/74563602/104634257-5fe27500-566e-11eb-8c25-390a912281f7.png)

Environment
Nuget Package:

**Package Version(s):**
https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=23486&view=results

**Affected platform(s):**
Windows

**Comment by jeromelaban** [comment]
Fixed by #4982

**Comment by sakshi173** [comment]
**Verified, Issue is Fixed -- Closing**

Below is the screenshot.
![Gallery listview display](https://user-images.githubusercontent.com/74563602/105723057-553ca100-5ef4-11eb-8a23-fc6505947f3c.png)
