### ISSUE TITLE
[iOS] ViewBox issues

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#4918]
## Current behavior

Content gets cut off in some situations, or not sized correctly in others.

## How to reproduce it (as minimally and precisely as possible)

**Example 1:**
https://playground.platform.uno/#730b1510

Now put that `ViewBox` into a `UserControl` on iOS, set the `Width` of the user control to `140` and notice that only a small portion of the content in the top left part of the user control is showing, the rest is cut off:

![image](https://user-images.githubusercontent.com/1700111/104718830-839ecd00-56f9-11eb-8594-ec3efee42797.png)

**Example 2:**
http://playground.platform.uno/#a5e0fed0

What that inner `Grid` actually looks like when put into a `Page` on iOS:

![image](https://user-images.githubusercontent.com/1700111/104723152-d037d780-56fc-11eb-80f3-827281e7e6ca.png)

If you replace the `Rectangle` in this example with an `Image` with the same dimensions, the whole image renders but it is sized into that small area instead of the whole `ViewBox`.

## Workaround

None.

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

v3.4.0 / v3.5.0-dev.94

Affected platform(s):

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report.

## Note for contributors

This issue may be related to the way `RenderTransform` is handled on iOS: 
https://github.com/unoplatform/uno/blob/fd59d975c40c0da117feca4ca8a0e082cbae2d57/src/Uno.UI/UI/Xaml/Controls/ViewBox/Viewbox.cs#L60-L64

**Comment by mikernet** [comment]
Thanks for this @carldebilly ! When is this expected to show up in a dev build of Uno.UI?

**Comment by mikernet** [comment]
Okay, I see why I thought this wasn't in the dev build yet - it seems to be somewhat fixed but I'm still getting weird layout issues.

Upon further investigation, it may be more related to the `Grid` and `ViewBox` interaction problem I posted in https://github.com/unoplatform/uno/issues/4919 but I'm not sure. Example:

```xml
<Page
    x:Class="App.Client.Roots.TestRoot"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App.Client.Roots"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="White">

    <ScrollViewer>
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="*" MinHeight="80" />
                <RowDefinition Height="Auto"/>
                <RowDefinition Height="*" />
            </Grid.RowDefinitions>

            <Viewbox MaxWidth="180" Margin="105,20,105,0">
                <Rectangle Stroke="Red" StrokeThickness="10" Fill="Black" Width="443" Height="367"/>
            </Viewbox>

            <Rectangle Fill="Blue" Grid.Row="1" Height="1000"/>
        </Grid>
    </ScrollViewer>
</Page>
```

What it should look like:

![image](https://user-images.githubusercontent.com/1700111/106846395-ca3d7280-667a-11eb-936a-70a6ef196e0a.png)

What it does look like:

![image](https://user-images.githubusercontent.com/1700111/106846430-d6c1cb00-667a-11eb-9bd0-e277e9ef7afc.png)

**Comment by carldebilly** [comment]
@mikernet correct me if I'm wrong, but this bug is already tracked by https://github.com/unoplatform/uno/issues/4919

**Comment by mikernet** [comment]
I'm not sure if this is the same issue or not. I thought it might be but this seems different. In the WASM issue the box is cut off and center aligned, where-as in this iOS issue it left aligns and does not cut off. It may be related though, not sure.

**Comment by carldebilly** [comment]
Ok so that would be a new issue for iOS.

**Comment by mikernet** [comment]
It may be possible that fixing #4919 will also fix this issue - I think the grid row `MinSize` is not being properly respected, which is causing the cutting off there, and could be causing the vertical space in the `ViewBox` to get messed up and thus creating this alignment issue. If you want I will open another iOS issue to make sure it is tracked and link the two issues together to indicate they may be related.
