### ISSUE TITLE
[WASM] Grid+ViewBox Layout Issue

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#4919]
## Current behavior

Something odd is happening with `Grid` and `ViewBox` layouts where it cuts off parts of rows.

## How to reproduce it (as minimally and precisely as possible)

http://playground.platform.uno/#45314d2f

Notice as you shrink the window height it cuts off the box on the top.

The top box should never get cut off - this is what it should look like (i.e. how UWP looks):

![image](https://user-images.githubusercontent.com/1700111/104729620-b3080680-5706-11eb-8341-985d363abb9b.png)

## Workaround

None.

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

3.4.0 and 3.5.0-dev.94

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by carldebilly** [comment]
Seems related to the `<Grid>` logic.
