### ISSUE TITLE
[Android] ElementName binding within a Flyout breaks other bindings in that Flyout

### ISSUE THREAD

**Issue by EmperorXLII** [unoplatform/uno#4922]
## Current behavior

On Android, using an ElementName binding in a flyout breaks other bindings.

## Expected behavior

All bindings work, regardless of platform or visual hierarchy.

## How to reproduce it (as minimally and precisely as possible)

Page demonstrating issue:
```xaml
<Page
    x:Class="FlyoutDataContextIssue.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <Button DataContext="data context value">
        <TextBlock>
            <Run Text="DataContext: "/><Run Text="{Binding}"/>
            <LineBreak/>
            <Run Text="Length: "/><Run Text="{Binding Length}"/>
        </TextBlock>
        <Button.Flyout>
            <Flyout x:Name="FlyoutElement">
                <!--<Border>-->
                <StackPanel>
                    <TextBlock>
                        <Run Text="DataContext: "/><Run Text="{Binding}"/>
                        <LineBreak/>
                        <Run Text="Length: "/><Run Text="{Binding Length}"/>
                    </TextBlock>
                    <Button
                        Content="Button"
                        CommandParameter="{Binding ElementName=FlyoutElement}"/>
                </StackPanel>
                <!--</Border>-->
            </Flyout>
        </Button.Flyout>
    </Button>
</Page>
```
The top-level Button and the Flyout contain the same TextBlock content, but only the top-level bindings show content on Android due to the ElementName binding on the Button within the Flyout:
![Screenshot_20210116-120258](https://user-images.githubusercontent.com/6126715/104819436-238c5180-57f3-11eb-9110-bdaaa2908271.jpg)

## Workaround

Wrapping the Flyout content in a Border fixes the bindings (similar to #4626).

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

- 3.4.0

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report !
