### ISSUE TITLE
how fix to

### ISSUE THREAD

**Issue by AbdalaMask** [unoplatform/uno#4923]
![image](https://user-images.githubusercontent.com/37013638/104819660-9cad9800-5837-11eb-81e1-b883dfa6d976.png)

**Comment by AbdalaMask** [comment]
RadialGradientBrush not using to uap

**Comment by jeromelaban** [comment]
Thanks for the report! 

You will need to add WinUI 2.5 Library: https://docs.microsoft.com/en-us/windows/apps/winui/winui2/getting-started to access this class on the UWP head.

**Comment by AbdalaMask** [comment]
When you add it to a project Uno 

Gets wrong

How to use it through a library Uno
Thanks for replying

**Comment by jeromelaban** [comment]
Thanks for your answer.

Can you provide a sample project (using the default visual studio Uno templates) that reproduces the issue ? Thanks!

**Comment by AbdalaMask** [comment]
[repos.zip](https://github.com/unoplatform/uno/files/5827987/repos.zip)
this

**Comment by AbdalaMask** [comment]
is fixed

**Comment by AbdalaMask** [comment]
Has the problem been found?
jeromelaban
