### ISSUE TITLE
Nested measure on `ListView` may cause duplicate items

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4925]
## Current behavior

`TabView` source calls `UpdateLayout` on one of the children of `TabView`. When this happens during Measure of `TabListView`, it causes nested call of measure, so all items are constructed twice which breaks things like selection (first item cannot be unselected). Due to the differences in control lifetime, `UpdateLayout` call is not needed in Uno, but the underlying issue still persists.

This may be caused by the fact that `OnContainerChanging` is called during the measure phase.

This problem is applicable to `ListView` in general, not only for `TabViewListView`

## Expected behavior

Nested measure call should not produce duplicate set of items.

## How to reproduce it (as minimally and precisely as possible)

Uncomment `tabContentPresenter.UpdateLayout()` in `TabView.cs` and debug `TabViewItemsSourceTests` page. Add a breakpoint in the `TabViewItem` constructor and observe that it is called too many times. Also notice that first item cannot be unselected - because it is in fact just a duplicate of the actual first item.

## Workaround

-

## Environment

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

May be on other targets too.

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by ramezgerges** [comment]
Just tested. Doesn't seem to be a problem anymore. The constructor is called exactly 4 times in the sample page and the first tab is selected (and is selectable).
