### ISSUE TITLE
Templates not realized reliably when using ItemsRepeater inside TabView 

### ISSUE THREAD

**Issue by s-beltz** [unoplatform/uno#4935]
## Current behavior

The combination of TabView and ItemsRepeater shows a couple of oddities on different platforms. 

The attached repro app produces on UWP the following output
![image](https://user-images.githubusercontent.com/57802605/104930606-a94ffe80-59a5-11eb-8c05-3db1f61416ca.png)

All non-UWP platforms have one or more issues: 

Issue | UWP | iOS | Android | WASM
-- | -- | -- | -- | --
Initial Selection | Yes | No | No | No
Top TabView/   DataTemplate | Yes | Not on first TabViewItem | Yes | Yes
Top TabView/ Horizontal ItemsRepeater | Yes | No (only first Button) | No (only first Button) | Yes
Bottom TabView/Frame/ VirtualizingLayout   ItemsRepeater | Yes | First TabViewItem is empty | Initially only one item; all items   on second activation | Yes

## Expected behavior

Template resolution and layout according to UWP sample screenshot above.

## How to reproduce it (as minimally and precisely as possible)

1. Download sample app [UnoTabViewRepro 2021-01-14.zip](https://github.com/unoplatform/uno/files/5830960/UnoTabViewRepro.2021-01-14.zip)
2. Start platform specific project (e.g. Android):
Initial selection on Android:
![image](https://user-images.githubusercontent.com/57802605/104931042-32673580-59a6-11eb-88a1-91344d4eecd3.png)
After changing selection on Android once:
![image](https://user-images.githubusercontent.com/57802605/104931180-5b87c600-59a6-11eb-8e36-9788f22c19b4.png)
After changing selection on Android twice:
![image](https://user-images.githubusercontent.com/57802605/104931229-6a6e7880-59a6-11eb-88db-05ecfed2d511.png)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI 3.4.0

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

@jeromelaban we provided this issue as a high level issue for all our ItemsRepeater/TabView problems. All issues can be reproduced using the attached repro app. If you need decomposed issues for better triaging please let us know. Thank you!

**Comment by dr1rrb** [comment]
This is probably linked to https://github.com/unoplatform/uno/issues/4742
