### ISSUE TITLE
Touch support for Skia GTK backend

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4936]
## What would you like to be added:

- [ ] Touch support for the GTK head
- [ ] ScrollViewer support for Scrolling

**Comment by mterwoord** [comment]
Any suggestions for making scrolling working somehow? (While waiting for this?)

For example, Is it possible to make the scrollbar of the scrollviewer wider, so it's usable for touch?

**Comment by jeromelaban** [comment]
The scrolling works using the mouse wheel at this point.

**Comment by mterwoord** [comment]
I know, works like a charm on Windows. My raspberry touch screen doesn't do mouse wheel sadly. Any work arounds for now?

**Comment by jeromelaban** [comment]
There are no workarounds for now.
