### ISSUE TITLE
[Gallery][Wasm][hi-dpi] Fluent TextBox placeholder position is incorrect

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4937]
## Current behavior

![image](https://user-images.githubusercontent.com/5839577/104936115-18176280-597a-11eb-8fb2-85e54356c2d6.png)

**Comment by jeromelaban** [comment]
Duplicate of https://github.com/unoplatform/uno/issues/4511

**Comment by sakshi173** [comment]
**Verified Issue is Fixed -- Closing**

![Gallery Textbox](https://user-images.githubusercontent.com/74563602/105551755-02cf6a80-5cd1-11eb-9e36-fdb7f0d47257.png)
