### ISSUE TITLE
[Gallery][Wasm] Card content is cutoff

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4938]
## Current behavior

![image](https://user-images.githubusercontent.com/5839577/104936996-45b0db80-597b-11eb-804e-79dc3ad33878.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/5839577/104937090-62e5aa00-597b-11eb-8544-ab1e8b515ed1.png)

**Comment by davidjohnoliver** [comment]
Looks like the ellipsis is not applied

**Comment by jeromelaban** [comment]
Fixed by #4982

**Comment by sakshi173** [comment]
**Now issue is resolved and its working fine.** 
Below is the screenshot.

![card display](https://user-images.githubusercontent.com/74563602/105752833-c771ad80-5f15-11eb-8045-a57dbf04348a.png)
