### ISSUE TITLE
[Gallery][Wasm] Unchecked Material Radio button is not working properly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4939]
## Current behavior

![image](https://user-images.githubusercontent.com/5839577/104937969-6fb6cd80-597c-11eb-8068-1200addb875f.png)

Clicking the Unchecked `RadioButton` does not get selected properly

## Expected behavior

The `RadioButton` is selected properly.

**Comment by jeromelaban** [comment]
Fixed by #4946

**Comment by sakshi173** [comment]
**Verified, Issue is Fixed -- Closing**

Below is the screenshot.
![gallery radio button unchecked](https://user-images.githubusercontent.com/74563602/105722306-85377480-5ef3-11eb-933f-4738aa11e3a7.png)
