### ISSUE TITLE
[WASM] Mouse-over the checked <CheckBox> makes the check dissapear

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#4940]
## How to reproduce it (as minimally and precisely as possible)
1. Open https://unogallery-wasm-staging.azurewebsites.net/
2. Check the "Overview" pane
3. Go to __CheckBox__ section
4. Put mouse cursor over __Checked__ or __Indeterminate__ control
5. Overve the checked visual status of the control changing

![image](https://user-images.githubusercontent.com/4174207/104937564-ea331d80-597b-11eb-8ed1-66fc804e622a.png)

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by jeromelaban** [comment]
Fixed by #4946

**Comment by sakshi173** [comment]
Verified, Issue is Fixed -- Closing

Below is the screenshot.
![checbox correct](https://user-images.githubusercontent.com/74563602/106809958-50859480-663a-11eb-98bd-94792d51e50b.png)
