### ISSUE TITLE
[WASM] RadioButton visual state incorrect

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#4941]
## How to reproduce it (as minimally and precisely as possible)
1. Open https://unogallery-wasm-staging.azurewebsites.net/
2. Check the "Overview" pane
3. Go to __RadioButton__ section
4. Click __Unchecked__
5. Overve the checked state of the __Checked__ control is changed to unchecked, but the __Unchecked__ should go to checked visual state
![image](https://user-images.githubusercontent.com/4174207/104937902-53b32c00-597c-11eb-948d-3fa5b4e28db3.png)

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by jeromelaban** [comment]
Fixed by #4946

**Comment by sakshi173** [comment]
**Verified, Issue is Fixed -- Closing**


![gallery radio button](https://user-images.githubusercontent.com/74563602/105553848-33fd6a00-5cd4-11eb-959a-077c289bfc9d.png)
![gallery radio button 2](https://user-images.githubusercontent.com/74563602/105553960-67d88f80-5cd4-11eb-8548-84964b839f58.png)
