### ISSUE TITLE
[WASM] Checkbox status only visible when hovering with pointer

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#4943]
## How to reproduce it (as minimally and precisely as possible)
1. Open https://unogallery-wasm-staging.azurewebsites.net/
2. Check the "CheckBox" pane in __Material__ mode
3. Go to __Default__ section
4. Click on __UNCHECKED__
5. Observe checked visual state is only visible when the mouse is over the control
![image](https://user-images.githubusercontent.com/4174207/104938629-55c9ba80-597d-11eb-88a4-5431d93ad9c2.png)

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by jeromelaban** [comment]
Fixed by #4946

**Comment by sakshi173** [comment]
Verified, Issue is Fixed -- Closing

Below is the screenshot.
![checbox correct](https://user-images.githubusercontent.com/74563602/106669688-05a44800-657a-11eb-8870-7a34e94e138b.png)
