### ISSUE TITLE
[WASM][Gallery][High-DPI] Incorrect Fluent Button/ComboBox height

### ISSUE THREAD

**Issue by ebariche** [unoplatform/uno#4945]
![image](https://user-images.githubusercontent.com/33458222/104957691-a0a6fa80-599c-11eb-8f87-2cb43fc5c98d.png)

![image](https://user-images.githubusercontent.com/33458222/104957776-c7653100-599c-11eb-98f6-a9848acc8b48.png)

**Comment by sakshi173** [comment]
Verified, Issue is Fixed -- Closing

Below is the screenshot.
![Combobox correct](https://user-images.githubusercontent.com/74563602/106669292-7303a900-6579-11eb-94bf-8b5f80c98507.png)
