### ISSUE TITLE
Initial TabView selection not working when using x:Bind

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4948]
## Current behavior

This issue covers the first problem in #4935 - `SelectedItem` not being shown in `TabView` when bound via `x:Bind`

## Expected behavior

Should work as in UWP.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] All
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
Fixed :-)

**Comment by jeromelaban** [comment]
@MartinZikmund which PR fixed it ?

**Comment by MartinZikmund** [comment]
> @MartinZikmund which PR fixed it ?

This one https://github.com/unoplatform/uno/pull/4896
