### ISSUE TITLE
[WASM] .Header on Slider not working

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#4974]
https://playground.platform.uno/#ea60fc78

``` xml
<StackPanel Orientation="Vertical" Spacing="10" Margin="10">
		<Slider Minimum="10" Maximum="1600" Value="350" x:Name="slider">
			<Slider.Header>
				<TextBlock>Header <Run Text="{Binding Value, ElementName=slider}" /></TextBlock>
			</Slider.Header>
		</Slider>
</StackPanel>
```
## Current result
![image](https://user-images.githubusercontent.com/4174207/105186062-4d998880-5aff-11eb-97a6-6e3cd1ec7aa0.png)
(using playground)

## Expected result
![image](https://user-images.githubusercontent.com/4174207/105186096-57bb8700-5aff-11eb-835e-79cdc08bbd47.png)
(using XAML Studio)

## Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by davidjohnoliver** [comment]
Note: the Header appears as expected when using the default Fluent style for Slider, so this is probably a matter of adjusting the UWP style.
