### ISSUE TITLE
[iOS] Calculator text is not aligned properly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4976]
## Current behavior

![image](https://user-images.githubusercontent.com/5839577/105202251-c7397280-5b0f-11eb-8184-0a8c57803b40.png)

## Expected behavior

The text should not be shifted to the right.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.5-dev

Affected platform(s):

- [x] iOS

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
This bug is a regression introduced by PR https://github.com/unoplatform/uno/pull/4749 implementing Effective Viewport

**Comment by sakshi173** [comment]
**Verified, Issue is Fixed -- Closing**
![calc correct](https://user-images.githubusercontent.com/74563602/107135049-94d89500-68c5-11eb-8d75-051615d6dda9.png)
