### ISSUE TITLE
Run on Server

### ISSUE THREAD

**Issue by CyborgDE** [unoplatform/uno#4983]
Thanks very much for uno support for webassembly. I am a WPF developer and I am now anxious to distribute some of my features in a browser.
But webassembly currently has a fatal problem: it starts to run too slowly. The first time you want to download up to 10M of data from the server.

I also noticed a project Ooui: https://github.com/praeclarum/Ooui , which provides another way to run XAML on a server. In this way, the speed is very fast, really great! Reference: https://github.com/praeclarum/Ooui/wiki/Xamarin.Forms-on-the-Web .

## For which Platform:

- [ ] iOS
- [ ] Android
- [x ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for your feedback!

This issue has been discussed here: https://github.com/unoplatform/uno/discussions/4963, and the answer is still valid.
