### ISSUE TITLE
[WASM] PaneFooter disappears after resizing for WUX NavView in Top mode

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#4985]
## How to reproduce it (as minimally and precisely as possible)

1. Create a new Uno app
2. Add the Xaml below
3. Launch the app
4. Resize the browser window to be smaller

Xaml:

```xaml
	<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
		<NavigationView x:Name="NavView"
						PaneDisplayMode="Top"
						IsSettingsVisible="False"
						IsBackEnabled="{Binding ElementName=ContentFrame, Path=CanGoBack}">
			<NavigationView.MenuItems>
				<NavigationViewItem x:Name="HomeMenuItem"
									Content="Home"
									Tag="HomePage" />
				<NavigationViewItem Content="Time Entry"
									Tag="TimeEntryPage" />
				<NavigationViewItem Content="Reports"
									Tag="ReportsPage" />
				<NavigationViewItem Content="Admin"
									Tag="AdminPage" />
				<NavigationViewItem Content="About"
									Tag="AboutPage" />
			</NavigationView.MenuItems>
			<NavigationView.PaneFooter>
				<TextBlock VerticalAlignment="Center"
						   Margin="12,0"
						   Text="LOGIN CONTROL PLACEHOLDER" />
			</NavigationView.PaneFooter>
			<ScrollViewer>
				<Frame x:Name="ContentFrame"
					   Padding="12,0,12,24"
					   IsTabStop="True"/>
			</ScrollViewer>
		</NavigationView>
	</Grid>
````

## Current behavior

PaneFooter text is cut off on first load. After resizing the window, it disappears completely.

## Expected behavior

Text fully displays at all times

## Workaround

Use MUX NavView?? (not tried yet)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.5.0-dev.147

Affected platform(s):

Only tested on WASM

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by darenm** [comment]
WinUI 2.x version of `NavigationView` does not exhibit this issue.

- Microsoft.UI.Xaml - 2.6.0-prerelease.210113001
- Uno.UI - 3.5.0-dev.151

**Comment by francoistanguay** [comment]
Moving on with MUX
