### ISSUE TITLE
[iOS] Status bar on dark mode cannot be changed to black programmatically even after disabling dark mode

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#4992]
## Current behavior
The status bar is currently not changing to black. 

![act](https://user-images.githubusercontent.com/17461593/105395934-4fda1080-5bed-11eb-934e-d5022625760d.gif)

## Expected behavior
The first page statusbar should be black and the second page status bar should be white

![excp](https://user-images.githubusercontent.com/17461593/105395948-52d50100-5bed-11eb-88da-68763df1f08e.gif)

## How to reproduce it (as minimally and precisely as possible)

- Download sample [StatusBarDarkMode.zip](https://github.com/unoplatform/uno/files/5851517/StatusBarDarkMode.zip)
- Make sure your iphone (or simulator) is in dark mode
- Deploy  
- Navigate back and forth between the two pages

## Workaround

N/A

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.5.0-dev.151

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
I've made sure that I've set UIViewControllerBasedStatusBarAppearance to false

```xml
<!-- opt out of dark mode -->
<key>UIUserInterfaceStyle</key>
<string>Light</string>
<!-- disabled  UIViewControllerBasedStatusBarAppearance -->
<key>UIViewControllerBasedStatusBarAppearance</key>
<false/>
```

**Comment by francoistanguay** [comment]
Dont we have https://github.com/unoplatform/uno/issues/4554 ?

**Comment by takla21** [comment]
I'm not sure to understand exactly what `UISettings` can help me to change the status bar programmatically independently of the theme. Maybe that's the point of the issue mentioned, but it seems that it's used to check the current theme colors and a changed color event.

**Comment by jeromelaban** [comment]
I don't think Uno is doing anything in that space. Could be an iOS native behavior when disabling theming.

**Comment by agneszitte-nventive** [comment]
@jeromelaban So far after few tests, the issue is happening since iOS 13 with the new dark mode feature.
I found this at the moment for Xamarin.Forms => https://forums.xamarin.com/discussion/178248/change-ios-status-bar-text-color-while-dark-mode-is-activated

**Comment by jeromelaban** [comment]
As a workaround, you can use this:

```
UIApplication.SharedApplication.StatusBarStyle = UIStatusBarStyle.DarkContent;
```

We'll make modifications to Uno to use this in StatusBar.
