### ISSUE TITLE
[WASM/iOS/Android]: no warning for missing .FlowDirection support

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#5014]
I understand FrameworkElement.FlowDirection is not supported. However, I would expect to see a 'not implemented' warning for e.g. this code:
`var o = new ToggleSwitch { FlowDirection = FlowDirection.RightToLeft };`

What am I missing?

**Comment by jeromelaban** [comment]
Thanks Dierk,

Your specific example shows an Uno code analyzer issue were "inline" property initializers are not processed properly:

![image](https://user-images.githubusercontent.com/5839577/105757684-49fd6b80-5f1c-11eb-9c18-1d405764901e.png)

The first statement should be flagged but is not, and the second is.

I'll open an issue.

**Comment by jeromelaban** [comment]
Let's track https://github.com/unoplatform/uno/issues/5029 instead.

**Comment by DierkDroth** [comment]
Thanks, appreciated
