### ISSUE TITLE
[Proposal] Change the visibility of the Windows.UI.Xaml.Markup.MarkupExtension ProvideValue method from protected to public to avoid casting

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#5024]
## What would you like to be added:

remove casting from Custom MarkupExtension to Windows.UI.Xaml.Markup.IMarkupExtensionOverrides to get access to ProvideValue method.

## Why is this needed:

micro optimization

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
While this would simplify the generated code, I am not sure whether it would have a big performance impact otherwise. What we definitely should do however, is to remove `NotImplemented` from the `ProvideValue` method

**Comment by workgroupengineering** [comment]
@MartinZikmund @jeromelaban Can i do this?

**Comment by jeromelaban** [comment]
@workgroupengineering Do you have an example of the code that you're referring to?

**Comment by workgroupengineering** [comment]
Simple app like [Mark.zip](https://github.com/unoplatform/uno/files/10449092/Mark.zip) generate

```csharp
					.MainPage_c2ed24c83b547df432aed8108c2d2b1f_XamlApply((MainPage_c2ed24c83b547df432aed8108c2d2b1fXamlApplyExtensions.XamlApplyHandler0)(c0 => 
					{
						c0.Text = (string)Convert.ChangeType((((global::Microsoft.UI.Xaml.Markup.IMarkupExtensionOverrides)new global::Mark.MyMark()).ProvideValue(global::Uno.UI.Helpers.MarkupHelper.CreateParserContext(c0, typeof(global::Microsoft.UI.Xaml.Controls.TextBlock), "Text", typeof(object))))?.ToString(), typeof(string));
						global::Uno.UI.FrameworkElementHelper.SetBaseUri(c0, "file:///C:/Users/Utente/Source/Repos/Mark/Mark/Mark.Shared/MainPage.xaml");
						c0.CreationComplete();
					}
```
if ProvideValue is public, we don't need to cast IMarkupExtensionOverrides
