### ISSUE TITLE
[Proposal] Generic IMarkupExtensionOverrides

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#5025]
## What would you like to be added:
avoid casting
## Why is this needed:
micro optimization

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thank you for your feedback.

Is this API available in UWP or WinUI ? We generally don't add public interfaces if the contract is not present there to begin with.

**Comment by workgroupengineering** [comment]
I don't know, but in xamarin.forms it exists.

**Comment by MartinZikmund** [comment]
@workgroupengineering I suggest adding this feedback to WinUI GitHub repo, so that it is implemented there first and we can add it afterwards too. The problem with adding such Uno-specific features is that they would not compile under UWP.

**Comment by MartinZikmund** [comment]
Closing this issue for now, please provide this as a proposal to WinUI, as they must add this first.
