### ISSUE TITLE
Not implemented members are not flagged when initialized inline

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#5029]
## Current behavior

Given the following code:
```csharp
var o = new ToggleSwitch { 
   FlowDirection = FlowDirection.RightToLeft
};

var d = o.FlowDirection;
```

only the second usage of the `FlowDirection` property is flagged as not implemented, where both should be.

## Expected behavior

Both uses should be flagged as not implemented.

## Environment

Nuget Package Version(s): 3.5-dev

**Comment by Youssef1313** [comment]
There is a good chance this is fixed in https://github.com/unoplatform/uno/pull/6550. Will add a test and fix if it's not already.
