### ISSUE TITLE
PagerControl ItemsRepeater mode not working

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#5030]
## Current behavior
The `PagerControl` ItemsRepeater mode is not working properly, as only one button is displayed even when multiple are being generated.

## Expected behavior

Multiple buttons should be displayed.

## Workaround

Use other modes.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

Tested on Skia/WASM, possibly does not work on other platforms either.

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
So to clarify, WebAssembly is actually showing the buttons, but then they start disappearing when clicked and the selection does not move 😂
![image](https://user-images.githubusercontent.com/1075116/105842601-bb99f000-5fd6-11eb-8e7d-a7743c6d71aa.png)

**Comment by MartinZikmund** [comment]
Test `VerifyNumberPanelButtonUIABehavior` can be enabled after this is fixed.

**Comment by dr1rrb** [comment]
Could be linked to https://github.com/unoplatform/uno/issues/4742 and https://github.com/unoplatform/uno/issues/4935
