### ISSUE TITLE
[Gallery][Android/iOS] Burger Menu is not displaying correctly

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5031]
**How to reproduce it**

Open Uno Gallery APP for Canary 
Check the Burger Menu on the top left of the page. 
Observe Burger Menu is not displaying correctly.

**Current behavior**
Burger Menu is not displaying correctly.

**Expected behavior**
Burger Menu and Arrow sign should display correctly.

Attachment:
**Actual Result:**
**Motorola g(7) – 9**
![Gallery burger menu G7](https://user-images.githubusercontent.com/74563602/105776943-7f638280-5f37-11eb-94e5-652dd559e33c.png)
**Samsung S8 - 8.0**
![Gallery burger menu S8](https://user-images.githubusercontent.com/74563602/105776959-868a9080-5f37-11eb-8897-ed4cc5cbb8aa.png)

**Expected Result:**
**Samsung S8 - 8.0**
![Gallery burger menu S8 Correct](https://user-images.githubusercontent.com/74563602/105776966-8be7db00-5f37-11eb-86d1-2b1a24c574e9.png)

**Environment**
**Nuget Package:**
Uno.UI | 3.5.0-dev.80 | 3.5.0-dev.182

 **Version(s):**
Version 1.4.3 (580)

**Device:**
Samsung S8 - 8.0
Motorola g(7) – 9

**Affected platform(s):**
Android

**Comment by carldebilly** [comment]
@ajpinedam @sakshi173 Were this fixed by PR https://github.com/unoplatform/Uno.Gallery/pull/91?

**Comment by Xiaoy312** [comment]
not sure, but unoplatform/Uno.Gallery#101 will.

**Comment by carldebilly** [comment]
@ajpinedam It has been merged ;-)

**Comment by sakshi173** [comment]
Verified, Issue is Fixed -- Closing
![burger menu display](https://user-images.githubusercontent.com/74563602/107135460-eb939e00-68c8-11eb-8411-2d3c86c27df7.png)
