### ISSUE TITLE
[Gallery][WASM] Scrollbar hinders NavigationViewItem selection

### ISSUE THREAD

**Issue by ebariche** [unoplatform/uno#5034]
![image](https://user-images.githubusercontent.com/33458222/105818061-6f25c480-5f84-11eb-855b-8f58748a3a5c.gif)

![image](https://user-images.githubusercontent.com/33458222/105819640-6d5d0080-5f86-11eb-8e65-f99c42d5476f.png)

**Comment by jeromelaban** [comment]
Is it a regression ?

**Comment by ebariche** [comment]
Hard to say ! Maybe ?

**Comment by davidjohnoliver** [comment]
Not a recent regression, same behaviour in gallery.platform.uno.

It's normal that the scroll bar blocks input - same as UWP. What's weird is:
 1. The scroll bar is too wide - 48 px vs 16 px
 2. It's invisible!

@dr1rrb Any idea for this one?

https://unogallerycanary.z27.web.core.windows.net/

**Comment by dr1rrb** [comment]
No real idea for this one unfortunately.

I noticed also that we are able to have multiple "hover" states when exiting control by the right / scroll bar ... I would assume that even if invisible, the `ScrollBar` is handling the pointer events.

![ScrollBarNavView](https://user-images.githubusercontent.com/8635919/106756987-de8f5a00-65fd-11eb-82d6-c9554f851709.gif)

**Comment by sakshi173** [comment]
Not able to reproduce it.
