### ISSUE TITLE
[Gallery][Wasm] TypeError: Cannot read property 'DisableFrameReporting' of undefined

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#5038]
## Current behavior

The following error happens when hovering over the navigation view items:
```
Error #1 "TypeError: Cannot read property 'DisableFrameReporting' of undefined
```

## Expected behavior

No error.

## Environment

https://dev.azure.com/uno-platform/1dd81cbd-cb35-41de-a570-b0df3571a196/_build?definitionId=93

**Comment by kazo0** [comment]
Happening as of 3.5.0-dev.171 as a result of the PR: #4994

**Comment by kazo0** [comment]
Relates to #3736
