### ISSUE TITLE
Flyout menu for Android head has excessive gap

### ISSUE THREAD

**Issue by vskotatko** [unoplatform/uno#5047]
I have a MenuFlyout that is BottomEdgeAlignedRight. However, on one of my test devices, there's a large gap between the button and the flyout.

Here's the XAML:

```
<Grid ...>
  <Grid.RowDefinitions>
    <RowDefinition Height="35" />
  </Grid.RowDefinitions>

  <Grid.ColumnDefinitions>
    <ColumnDefinition Width="*" /> <!-- tab -->
    <ColumnDefinition Width="35" /> <!-- action button -->
    <ColumnDefinition Width="35" />
    <ColumnDefinition Width="35" />
  </Grid.ColumnDefinitions>

  ...

  <Button
    Grid.Column="3"
    Padding="10" >
    <Image Source="ms-appx:///Assets/icons/more_menu_white.png" />
    <Button.Flyout>
      <MenuFlyout Placement="BottomEdgeAlignedRight">
        <MenuFlyoutItem Text="Item 1" Click="OnItem1Clicked" />
        <MenuFlyoutItem Text="Item 2" Click="OnItem2Clicked" />
        <MenuFlyoutItem Text="Item 3" Click="OnItem3Clicked" />
      </MenuFlyout>
    </Button.Flyout>
  </Button>
</Grid>

```

Here are some screen shots. As you can see, there's a small gap on UWP and my Android 5 device. But for Android 10, there's a huge gap. I presume the small gaps are by design.

**Windows 10**
![windows10](https://user-images.githubusercontent.com/74079144/106019707-ce183600-6077-11eb-9967-707053f5b788.png)

**Android 5**
![android5](https://user-images.githubusercontent.com/74079144/106019772-dff9d900-6077-11eb-8238-e6ce0cc4e7fb.png)

**Android 10**
![android10](https://user-images.githubusercontent.com/74079144/106019807-e8521400-6077-11eb-8ad1-5c2b0191e60d.jpg)

**Comment by jeromelaban** [comment]
Thanks for the report. 

The popup system being used here is the native one, which may cause this issue. Can you try setting this in your project (App.xaml ctor):
```
FeatureConfiguration.Popup.UseNativePopup = false;
```

and let us know ?

**Comment by vskotatko** [comment]
How do I reference FeatureConfiguration ? Intellisense doesn't suggest 
anything. I tried prefixing it with Uno.UI. and that isn't recognized, 
either.
Peri

<< Annoyed by leaf blowers ? https://quietcleanseattle.org/ >>

------ Original Message ------

**Comment by MartinZikmund** [comment]
It should be in `Uno.UI`. It is available on Uno targets only though:

#if !WINDOWS_UWP
    Uno.UI.FeatureConfiguration.Popup.UseNativePopup = false;
#endif

**Comment by vskotatko** [comment]
That works - the dropdown displays with a small gap, like on the other 
devices. The #if made the compilation difference, I didn't realize that 
the statement needed to be conditional.

Peri

<< Annoyed by leaf blowers ? https://quietcleanseattle.org/ >>

------ Original Message ------

**Comment by MartinZikmund** [comment]
This is no longer relevant, as the native styles are deprecated
