### ISSUE TITLE
[Gallery][Android/iOS]<Fluent><CheckBox> Image inside Checkbox is displaying incorrectly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5048]
**How to reproduce it**

1. Open Uno Gallery APP for canary.
2. Check the **"Overview"** pane for Fluent.
3. Go to **"Checkbox"** section.
4. Observe the image inside checkbox for “Checked”, “Indeterminate” is displaying incorrectly.
OR
5. Click "CheckBox" option from Burger Menu.
6. Go to "Default" section.
7. Observer the image inside checkbox for “Checked”, “Indeterminate” are displaying incorrectly.

**Current behavior**
The image inside checkbox for “Checked”, “Indeterminate” is displaying incorrectly.

**Expected behavior**
The image inside checkbox for “Checked” and “Indeterminate” should display correctly.

**Attachment:
Actual Result:**
**Motorola g(7) – 9**
![gallery checbox display G7 wrong](https://user-images.githubusercontent.com/74563602/106020439-c4033100-6091-11eb-8105-9b98aa473949.png)
**Samsung S8 - 8.0**
![gallery checbox display s8 wrong](https://user-images.githubusercontent.com/74563602/106020503-d8dfc480-6091-11eb-8623-f492e39e6ae8.png)
![checkbox issue new](https://user-images.githubusercontent.com/74563602/106046690-97124680-60b0-11eb-821d-1b31d6f00983.png)

**Expected Result:**
**Samsung S8 - 8.0**
![gallery checbox display s8 correct](https://user-images.githubusercontent.com/74563602/106020555-e5fcb380-6091-11eb-8308-365f4a28218e.png)

**Environment
Nuget Package:**
Uno.UI 3.5.0-dev.223

**Version(s):**
Version 1.4.3 (582)

**Device:**
Samsung S8 - 8.0
Motorola g(7) – 9

**Affected platform(s):**
Android

**Comment by jeromelaban** [comment]
Fixed in recent builds

**Comment by sakshi173** [comment]
Verified, Issue is Fixed -- Closing

Below is the screenshot.
![checbox image correct 1](https://user-images.githubusercontent.com/74563602/106670890-9fb8c000-657b-11eb-93a8-44cb474c8a5d.png)
![checbox image correct 2](https://user-images.githubusercontent.com/74563602/106670897-a2b3b080-657b-11eb-9eb6-e75dd0827be1.png)
