### ISSUE TITLE
[Gallery][Android/iOS]<Fluent><Button> Back button is not displaying correctly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5050]
**How to reproduce it**
1. Open Uno Gallery APP for canary.
2. Check the "**Overview**" pane for Fluent.
3. Go to **Button** section.
4. Observe the Back Button image Below the "Text Button" is not displaying correctly.
                          OR
5. Click "Button" option from Burger Menu.
6. Go to "Back Button" section.
7. Observer Both back button image is displaying incorrectly.

**Current behavior**
The Back Button Image  is displaying incorrectly.

**Expected behavior**
The  Back Button image should display correctly.

**Attachment:
Actual Result:**
**Motorola g(7) – 9**
![g7 button arrow](https://user-images.githubusercontent.com/74563602/106024286-a041ea00-6095-11eb-9001-d6e707a263a3.png)

**Samsung S8 - 8.0**
![s8 button arrow](https://user-images.githubusercontent.com/74563602/106024309-a637cb00-6095-11eb-9d7d-f7b160c69619.png)
![back button issue](https://user-images.githubusercontent.com/74563602/106045798-70074500-60af-11eb-845d-63cee5763494.png)

**Expected Result:
Samsung S8 - 8.0**
![s8 button arrow correct](https://user-images.githubusercontent.com/74563602/106024325-aafc7f00-6095-11eb-89e2-050623f09970.png)

**Environment
Nuget Package:**
Uno.UI 3.5.0-dev.223

**Version(s):**
Version 1.4.3 (582)

**Device:**
Samsung S8 - 8.0
Motorola g(7) – 9

**Affected platform(s):**
Android

**Comment by jeromelaban** [comment]
Fixed in recent builds

**Comment by sakshi173** [comment]
Verified, Issue is Fixed -- Closing

Below is the screenshot.
![back button](https://user-images.githubusercontent.com/74563602/106902352-ba4b8000-66c6-11eb-8aa8-ae59ed7c22fc.png)
