### ISSUE TITLE
[Gallery][Android/iOS]<Fluent><TextBox> Clear button inside Textbox is displaying incorrectly while typing some text in textbox.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5051]
**How to reproduce it**
1. Open Uno Gallery APP for canary.
2. Check the **"Overview"** pane for Fluent.
3. Go to **"Textbox"** section.
4. Type text inside textbox.
5. Observe that the Clear button inside Textbox is displaying incorrectly.
6.          OR
7. Click "TextBox" option from Burger Menu.
8. Go to "**Default**" or "**Header**" section.
9. Type some text inside textbox.
10. Observe that the Clear button inside Textbox is displaying incorrectly.

**Current behavior**
The Clear button inside Textbox is displaying incorrectly while typing some text in textbox.

**Expected behavior**
The Clear button for "Textbox" should display correctly.

**Attachment:
Actual Result:**
**Samsung S8 - 8.0**
![textbox s8 wrong](https://user-images.githubusercontent.com/74563602/106026623-0e87ac00-6098-11eb-8b3b-2a44c0d29bea.png)
![textbox type issue](https://user-images.githubusercontent.com/74563602/106053644-09872480-60b9-11eb-9833-3e1e955c3c93.png)

**Expected Result:
Samsung S8 - 8.0**
![textbox s8 correct](https://user-images.githubusercontent.com/74563602/106026643-147d8d00-6098-11eb-8290-642dbbba2118.png)

**Environment
Nuget Package:**
Uno.UI 3.5.0-dev.223

**Version(s):**
Version 1.4.3 (582)

**Device:**
Samsung S8 - 8.0
Motorola g(7) – 9

**Affected platform(s):**
Android

**Comment by jeromelaban** [comment]
Fixed in recent builds

**Comment by sakshi173** [comment]
Verified, Issue is Fixed -- Closing

Below is the screenshot.
![clear button](https://user-images.githubusercontent.com/74563602/106912758-52e6fd80-66d1-11eb-83e7-600274549721.png)
