### ISSUE TITLE
[Gallery][Android/iOS]<Material><TextBox> Image for Textbox is displaying incorrectly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5052]
**How to reproduce it**

1. Open Uno Gallery APP for canary.
2. Check the "Overview" pane for Material.
3. Go to "Textbox" section.
4. Observe the image for "Filled with icon" and "Outlined with icon" option  is not displaying correctly.
5.              OR
6. Click "TextBox" option from Burger Menu.
7. Go to "Default" or "Outline" section.
8. Observe that the image for "With icon" option is not displaying correctly.

**Current behavior**
The image for "Filled with icon" and "Outlined with icon" option of TextBox is displaying incorrectly.

**Expected behavior**
The image for "Filled with icon" and "Outlined with icon" option of TextBox should display correctly.

**Attachment:
Actual Result:
Motorola g(7) – 9**
![g7 material text box image wrong](https://user-images.githubusercontent.com/74563602/106028985-9f5f8700-609a-11eb-8eff-a03d47d78e99.png)
![textbox material issue](https://user-images.githubusercontent.com/74563602/106048705-38020100-60b3-11eb-9224-8d9c152cead3.png)
**Samsung S8 - 8.0**
![s8 material text box image wrong](https://user-images.githubusercontent.com/74563602/106029023-a8e8ef00-609a-11eb-8ac7-5ebab1c11d25.png)

**Expected Result:
Samsung S8 - 8.0**
![s8 material text box image correct](https://user-images.githubusercontent.com/74563602/106029031-ac7c7600-609a-11eb-951f-1492b7d863d7.png)

**Environment
Nuget Package:**
Uno.UI 3.5.0-dev.223

**Version(s):**
Version 1.4.3 (582)

**Device:**
Samsung S8 - 8.0
Motorola g(7) – 9

Affected platform(s):
Android

**Comment by jeromelaban** [comment]
Fixed in recent builds

**Comment by sakshi173** [comment]
Verified, Issue is Fixed -- Closing

Below is the screenshot.
![textbox correct](https://user-images.githubusercontent.com/74563602/107127932-abf89200-6887-11eb-812c-cb733b9ddcbb.png)
