### ISSUE TITLE
[Gallery][Android/iOS]<Material><CheckBox> Not able to uncheck the checkbox once it is checked.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5053]
**How to reproduce it**

1. Open Uno Gallery APP for canary.
2. Check the "Overview" pane for Material.
3. Go to **"CheckBox"** section.
4. Try to uncheck "Checked" checkbox.
5. Observe that the "Checked" checkbox is showing checked again and not able to uncheck the checkbox.
                           OR
6. Click "CheckBox" option from Burger Menu.
7. Go to "Default" or "Secondary" section.
8. Observe that the "Checked" checkbox is showing checked again and not able to uncheck the checkbox.

Current behavior
**Current behavior**
 The "Checked" checkbox is showing checked and not able to uncheck the checkbox.

**Expected behavior**
 The "Checked" checkbox should show as uncheck.

**Attachment:
Actual Result:**
![checkbox issue](https://user-images.githubusercontent.com/74563602/106034415-e81a3e80-60a0-11eb-9314-f82df292e77d.png)
![checkbox material](https://user-images.githubusercontent.com/74563602/106047451-a47c0080-60b1-11eb-8f29-a695583793cd.png)

**Expected Result:**
![checkbox correct](https://user-images.githubusercontent.com/74563602/106034425-ebadc580-60a0-11eb-94ba-5386ee54a6fd.png)

**Environment
Nuget Package:**
Uno.UI 3.5.0-dev.223

**Version(s):**
Version 1.4.3 (582)

**Device:**
Samsung S8 - 8.0
Motorola g(7) – 9

**Affected platform(s):**
Android

**Comment by jeromelaban** [comment]
This issue seems related visual states executions.

**Comment by jeromelaban** [comment]
Commenting out `CheckedPressed` checkbox visual state works around the issue.

**Comment by jeromelaban** [comment]
Caused by https://github.com/unoplatform/Uno.Material/pull/392

**Comment by sakshi173** [comment]
Still issue is present.
**Verified in the Below Version**
Android -- Version 1.4.3 (400672)
iOS-- Version 1.4.3(672)

**Comment by sakshi173** [comment]
Verified, Issue is Fixed -- Closing

Below is the screenshot.
![CB correct](https://user-images.githubusercontent.com/74563602/107577352-52ae9c80-6bc0-11eb-954e-f6e7113c8f5d.png)
