### ISSUE TITLE
[Gallery][Android]The text part is truncated.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5060]
How to reproduce it

1. Open Uno Gallery APP for canary.
2. Go to "**StandardBottomSheet**" section.
3. Observe the text is truncated at the end of the text.

**Current behavior**
The text is truncated and the whole text is not visible.

**Expected behavior**
The whole text should display.

Attachment:
Actual Result:
![text cut issue 2](https://user-images.githubusercontent.com/74563602/106060819-89fe5300-60c2-11eb-9a2a-e967d78e8ce1.png)
![text truncate](https://user-images.githubusercontent.com/74563602/106180956-fd5b9f80-616a-11eb-8be3-c98ae92a2169.png)

Environment
Nuget Package:
Uno.UI 3.5.0-dev.223

Version(s):
Version 1.4.3 (582)

Device:
Samsung S8 - 8.0
Motorola g(7) – 9

Affected platform(s):
Android

**Comment by jeromelaban** [comment]
@sakshi173 I'm not able to reproduce this. Could be device specific. Could you retry with the latest canary ?

**Comment by sakshi173** [comment]
Verified, Issue is Fixed -- Closing

Below is the screenshot.
![Card text correct](https://user-images.githubusercontent.com/74563602/106817305-acedb180-6644-11eb-8ec9-1e382b1515e2.png)
