### ISSUE TITLE
[Gallery][Android] Flipview Arrow sign direction is incorrect.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5063]
**How to reproduce it**

1. Open Uno Gallery APP for canary.
2. Go to "**FlipView**" section.
3. Observe the arrow direction for item 1 and Item 4 Swipe is incorrect.

**Current behavior**
The arrow direction for item 1 and Item 4 Swipe is incorrect.

**Expected behavior**
The arrow direction for item 1 and Item 4 Swipe should vice versa.

**Attachment:
Actual Result:**
![flipview ar1 issue](https://user-images.githubusercontent.com/74563602/106062265-8c61ac80-60c4-11eb-912a-6641bb90c047.png)
![flipview ar2 issue](https://user-images.githubusercontent.com/74563602/106062277-908dca00-60c4-11eb-9152-aae7ab66ec85.png)

**Expected Result:**
![flipview ar1 correct](https://user-images.githubusercontent.com/74563602/106062323-9edbe600-60c4-11eb-82d6-d81e3b87240b.png)
![flipview ar2 correct](https://user-images.githubusercontent.com/74563602/106062331-a13e4000-60c4-11eb-810b-46712037eeaa.png)

**Environment
Nuget Package:**
Uno.UI 3.5.0-dev.223

**Version(s):**
Version 1.4.3 (582)

**Device:**
Samsung S8 - 8.0
Motorola g(7) – 9

**Affected platform(s):**
Android

**Comment by Xiaoy312** [comment]
The static text is just written that way. I would assume the arrow is pointing to the direction that your finger should swipe.
This really boils down how you would read it:
O swipe in that direction to see more items
X more items in that direction, swipe to see

**Comment by jeromelaban** [comment]
@Xiaoy312 is it actually not fixed ? :)

**Comment by Xiaoy312** [comment]
There is no problem on that page. The arrow should be indicative of the swipe direction. So the "Actual Result" is correct.
It appears that Sakshi was comparing to the store version, which had the arrow direction wrong, but that was corrected in https://github.com/unoplatform/Uno.Gallery/commit/ed6b633e2b3a26be58d512a782debb3d36e4d37a

**Comment by sakshi173** [comment]
According to Xiao comment the store Version requirement is wrong and the New requirement is correct . Then considering that fact  this is not valid bug and closing it.
