### ISSUE TITLE
Adjust the Reference API Assembly comparer for WinUIAPI mismatches

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#5075]
Ground work for #2240 to find additional changes to apply to the codebase.

- [ ] Adjust the Reference API Assembly comparer for WinUIAPI mismatches
- [ ] Update #2240 with the list of needed changes
- [ ] Update the CI to detect invalid API changes (starting from current state)

**Comment by MartinZikmund** [comment]
@jeromelaban I think this is now done as part of CI, so this can be closed?

**Comment by jeromelaban** [comment]
It now done yes. Thanks!
