### ISSUE TITLE
Generator does not undersand px suffix for grid row and colum size

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/uno#5081]
`CSC : warning CS8785: Generator 'XamlCodeGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'AggregateException' with message 'One or more errors occurred.'`

## Current behavior

Generator crashes

## How to reproduce it (as minimally and precisely as possible)

``` XML
<RowDefinition Height="120px" />
<ColumnDefinition Width="120px" />
```

## Workaround

Remove `px` suffix

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [X] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.4

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [X] Build tasks
- [ ] Solution Templates

**Comment by carldebilly** [comment]
On Windows, anything after the numeric value is simply ignored.

**Comment by Youssef1313** [comment]
> On Windows, anything after the numeric value is simply ignored.

Should `*` be an exception?
