### ISSUE TITLE
Add support for new Fluent styles from MUX

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#5082]
## What would you like to be added:

Since version 2.6, you can specify whether your app wants to use "old" fluent styles or new ones:

This provides "old" styles (2.5):

```
<Application.Resources>
            <XamlControlsResources Version="WinUI_2dot5" xmlns="using:Microsoft.UI.Xaml.Controls" />
</Application.Resources>
```

![image](https://user-images.githubusercontent.com/1075116/106379211-a47a4a00-63aa-11eb-9e4f-502a96372346.png)

And this the shiny new 2.6 styles:

```
<Application.Resources>
            <XamlControlsResources Version="Latest" xmlns="using:Microsoft.UI.Xaml.Controls" />
</Application.Resources>
```

![image](https://user-images.githubusercontent.com/1075116/106379227-b825b080-63aa-11eb-9e07-ca1e41fdac8f.png)

## Why is this needed:

New fluent styles!

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by robloo** [comment]
Is there any info when 2.6 styles are going to be pulled into the Uno Platform? 

This is especially relevant with 2.6 being released today. I think WinUI3 is using the same styles and templates so there shouldn't be a lot of additional additional work required after this big update for Windows 11.

This is a pretty big change and all the default templates and resources need to be updated. I know Uno has a lot of specially adjusted XAML to disable unsupported features as well. I'm willing to help with this as needed. I will also finish up the Expander style updates PR now that 2.6 is ready.

**Comment by MartinZikmund** [comment]
Closing in favor of #6747
