### ISSUE TITLE
"System.InvalidOperationException: Error while unstacking precedence. Should be ExplicitStyle, got ."

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#5096]
## Current behavior

The following exception may happen, using PG-AOT:

```
dotnet.js:2050       Failed to apply binding to property [DependencyPropertyDetails(ContentTemplate)] on [Windows.UI.Xaml.Controls.ContentPresenter] (Error while unstacking precedence. Should be ExplicitStyle, got .)
dotnet.js:2050 System.InvalidOperationException: Error while unstacking precedence. Should be ExplicitStyle, got .
dotnet.js:2050    at Windows.UI.Xaml.DependencyObjectStore.<>c__DisplayClass94_0.<OverrideLocalPrecedence>b__0()
dotnet.js:2050    at Uno.Disposables.AnonymousDisposable.Dispose()
```

## Expected behavior

No exception.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
Looking at the code involved, it seems like we're not putting the Dispose() call that  pops the precedence from the stack in a `finally` block on WASM (for performance reasons):

https://github.com/unoplatform/uno/blob/ec9c14ac2bc17e41f4969da3342d561b3fd85e83/src/Uno.UI/UI/Xaml/DependencyObjectStore.cs#L494-L499

I'd speculate that an earlier exception from `SetValue()` (presumably from an attempt to set a local value, nested somewhere within the application of the `Style`?) prevents the dispose from happening and puts the precedence override stack in a bad state, which causes this error the next time it tries to pop the stack. Hard to know without a repro though.

**Comment by jeromelaban** [comment]
This error can happen when : 

https://github.com/unoplatform/uno/blob/b0e183958374831b9fdb6b5f0f929eb38a060b81/src/Uno.UI/UI/Xaml/Style/Style.cs#L62

executes the dispose, which fails and hides the original exception.
