### ISSUE TITLE
Add support for BitmapSource.SetSourceAsync

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#510]
## I'm submitting a...

  
 - Feature request

## Current behavior
The API SetSourceAsync for Windows.UI.Xaml.Media.Imaging.BitmapSource is not supported.

## Expected behavior
The API SetSourceAsync for Windows.UI.Xaml.Media.Imaging.BitmapSource is supported.

## Minimal reproduction of the problem with instructions
Try to set a Byte[] of an Image to a BitmapImage like this:
```
var bytes =  //get Bytes of an Image...
BitmapImage bitmapImage = new BitmapImage();
await bitmapImage.SetSourceAsync((new MemoryStream(bytes)).AsRandomAccessStream());
```

## Environment

```
Nuget Package: 

Package Version(s): 

Affected platform(s):
- [X] iOS
- [X] Android
- [X] WebAssembly (not relevant for me)
- [ ] Windows
- [ ] Build tasks

**Comment by YBAZAN** [comment]
Any news on it?

**Comment by MartinZikmund** [comment]
@TopperDEL @YBAZAN This API is now implemented, closing this issue. If you encounter issues with it, please reopen the issues/create a new one.

**Comment by BertrandDeSaintBezier** [comment]
I'm getting an exception raised `System.Runtime.InteropServices.COMException: ""` when calling `await bitmapImage.SetSourceAsync((new MemoryStream(bytes)).AsRandomAccessStream());` 🤔

Has anyone run into this issue ??

**Comment by TopperDEL** [comment]
Not sure, what you are doing - and maybe I'm totally wrong. But you may try to use a deferral:

```
var deferral = e.GetDeferral();
try
{
   //your image-code
}
finally
{
    deferral.Complete();
}
```

**Comment by BertrandDeSaintBezier** [comment]
Where is this `GetDeferral()` method coming from ? Sorry, I'm not faamiliar with this particular pattern

**Comment by TopperDEL** [comment]
Me neither - but that worked for me. :)
In my case it comes from `DragEventArgs`, but I assume it comes from `RoutedEventArgs`.

**Comment by BertrandDeSaintBezier** [comment]
Unfortunately the method isn't being called directly by the UI 😓 but rather is triggered from outside the app. I suspect it has something to do with the fact that the SetSourceAsync is happening inside of a dispatcherQueue call so that it happens on the UI thread
