### ISSUE TITLE
Add support for Stream.AsRandomAccessStream()

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#511]
## I'm submitting a...

  
 - Feature request

## Current behavior
The API AsRandomAccessStream() for System.IO.Stream is not supported.

## Expected behavior
The API AsRandomAccessStream() for System.IO.Stream is supported.

## Minimal reproduction of the problem with instructions
Try to convert a MemoryStream to a RandomAccessStream:
```
(new MemoryStream(bytes)).AsRandomAccessStream());
```

## Environment

```
Nuget Package: 

Package Version(s): 

Affected platform(s):
- [X] iOS
- [X] Android
- [X] WebAssembly (not relevant for me)
- [ ] Windows
- [ ] Build tasks

**Comment by YBAZAN** [comment]
Any news on it ?

**Comment by MartinZikmund** [comment]
This is now implemented and working.
