### ISSUE TITLE
[iOS][macOS]<Animation> RotateTransform and ScaleTransform is not rotating at proper position when using absolute center

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5111]
**How to reproduce it**
1. Open Uno Gallery APP for canary.
2. Click "Animation" option from Burger Menu.
3. Click “Start ” Button in “RotateTransform + Opacity” section  and in "ScaleTransform" section.
4. Observe that the green square and Blue square rotating outside the rectangle.

**Actual Result:**
The green square and Blue square is rotating and moving at wrong position in rectangle.

**Expected Result:**
The green square and Blue square should rotate and move at correct position in rectangle.

**Attachment:
Current behavior**
![20210204 ios animation offcenter](https://user-images.githubusercontent.com/2359550/106986977-81e58980-673a-11eb-8b62-0ac2883decd2.gif)

**Expected behavior**
![animation correct 1](https://user-images.githubusercontent.com/74563602/106647773-61140d00-655d-11eb-8b0d-67a966b5b6f6.png)
![animation correct 2](https://user-images.githubusercontent.com/74563602/106647786-640efd80-655d-11eb-8fb9-9dae3c0da048.png)

**Version(s):**
Version 1.2.4 (739)

**Device:**
iphone 12 - 14.1

**Affected platform(s):**
iOS

**Comment by dr1rrb** [comment]
This issue occurs only when using an absolute center. 

# Workaround
Use a relative center (i.e. use the `RenderTransformOrigin` instead of `<Rotate|Scale>Transform.Center<X|Y>`).

**Comment by dr1rrb** [comment]
This issue is also present on macOS https://github.com/unoplatform/Uno.Gallery/issues/120

**Comment by sakshi173** [comment]
Verified with latest canary build, bug is fixed, closing it.
