### ISSUE TITLE
[Gallery][iOS]By Default App is opening in Night Mode.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5112]
**How to reproduce it**
1. Open Uno Gallery APP for canary.
2. Observe that by Default App is opening in Night mode.

**Actual Result:**
The app is opening in Night mode.

**Expected Result:**
The app should open in Day mode.

**Attachment:
Current behavior**
![night mode](https://user-images.githubusercontent.com/74563602/106648547-6f165d80-655e-11eb-872a-fd549ddaf316.png)

**Expected behavior**
![day mode](https://user-images.githubusercontent.com/74563602/106648573-7473a800-655e-11eb-81e2-90c5f0b2ca93.png)

**Version(s):**
Version 1.2.4 (739)

**Device:**
iphone 12 - 14.1

**Affected platform(s):**
iOS

**Comment by davidjohnoliver** [comment]
@sakshi173 Did you test this on a physical device, or using the simulator?

**Comment by sakshi173** [comment]
@davidjohnoliver Using a physical device.

**Comment by kazo0** [comment]
@sakshi173 On the physical iOS device, is the system set to dark or light theme in the System Settings of the phone? The Gallery app should be respecting whatever theme that the system is set to.

**Comment by sakshi173** [comment]
@kazo0 the Nightshift option is off in my iOS device.
![night shift off](https://user-images.githubusercontent.com/74563602/106652575-a63b3d80-6563-11eb-8b6b-0462fbbc9242.png)
![night shift 2](https://user-images.githubusercontent.com/74563602/106652582-a89d9780-6563-11eb-9d9c-6a3a40875c68.png)

**Comment by kazo0** [comment]
So looking at those settings, the phone is set to Dark mode, which means the Gallery will automatically open in Dark mode, not light. Which is expected.

![image](https://user-images.githubusercontent.com/4793020/106652843-0500b700-6564-11eb-82f8-39ea52612331.png)

**Comment by sakshi173** [comment]
@kazo0  Yes verified it now and changed it .. Thanks for clarification and its not bug now... I am closing it.

**Comment by sakshi173** [comment]
This is not the bug, ios setting was in night mode, Now resolved, closing the issue

**Comment by sakshi173** [comment]
Issue is resolved - Changed ios settings.
