### ISSUE TITLE
SwipeControl crashes on android with that exception

### ISSUE THREAD

**Issue by dim-37** [unoplatform/uno#5113]
## Current behavior

[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_call_static_float_method_a'.
[Mono] Probing 'java_interop_jnienv_call_static_float_method_a'.
[Mono] Found as 'java_interop_jnienv_call_static_float_method_a'.
[41m[30mfail[39m[22m[49m: Uno.UI.DataBinding.BindingPropertyHelper[0]
      The [PickedServices] property getter does not exist on type [Windows.UI.Xaml.Controls.Grid]
[41m[30mfail[39m[22m[49m: Windows.UI.Xaml.Controls.SwipeControl[0]
      The member SwipeControl.SwipeControl() is not implemented in Uno.
[41m[30mfail[39m[22m[49m: Windows.UI.Xaml.Controls.SwipeItems[0]
      The member SwipeItems.SwipeItems() is not implemented in Uno.
[41m[30mfail[39m[22m[49m: Windows.UI.Xaml.Controls.SymbolIconSource[0]
      The member SymbolIconSource.SymbolIconSource() is not implemented in Uno.
**System.NullReferenceException:** 'Object reference not set to an instance of an object.'

## Expected behavior
No exception

## How to reproduce it (as minimally and precisely as possible)
ListPage.xaml
MainPage.xaml

[TestApp.zip](https://github.com/unoplatform/uno/files/5913258/TestApp.zip)

## Workaround
No

## Environment

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.9.0 Preview 3.0 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

## Anything else we need to know?
ListPage.xaml works on UWP but didn't work on Android

**Comment by xperiandri** [comment]
As I understand `SwipeControl` is not yet implemented, right?
https://platform.uno/docs/articles/implemented-views.html#not-yet-implemented
It is a very necessary control!

**Comment by francoistanguay** [comment]
It is now implemented so you should give it a try!
