### ISSUE TITLE
[wasm]Canvas does not draw internal sub-canvas

### ISSUE THREAD

**Issue by Daoting** [unoplatform/uno#5115]
## Current behavior
```
	<Grid>
		<Canvas>
			<Canvas>
				<Border x:Name="BBorderInCanvas" Background="Red" Height="100" Width="100" />
			</Canvas>
			<Border Background="Blue" Canvas.Top="20" Canvas.Left="50" Height="50" Width="50" />
			<StackPanel Canvas.Top="100" Canvas.Left="50">
				<Border Background="Yellow" Height="50" Width="50" />
				<Border Background="DarkGray" Height="50" Width="50" />
			</StackPanel>
		</Canvas>
		<Border x:Name="BBorderOutCanvas" Background="Green" HorizontalAlignment="Center"  Height="50" Width="50"/>
	</Grid>
```
The border `BBorderInCanvas` does not appear.
There are a lot of these nestings in my chart project.

## Workaround

MeasureOverride always return zero in [Canvas.Layout](https://github.com/unoplatform/uno/blob/dfe50c7a340809f9d082a04dba05776d0ad238a7/src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.Layout.cs#L24).
If the chidren collection contains canvas, the canvas will not be arraged in wasm. 
Modified to
```
		protected override Size MeasureOverride(Size availableSize)
		{
			double maxWidth = 0, maxHeight = 0;

			MeasureOverridePartial();
			foreach (var child in Children)
			{
				if (child is _View)
				{
					var measuredSize = MeasureElement(child, new Size(double.PositiveInfinity, double.PositiveInfinity));

					maxHeight = Math.Max(maxHeight, measuredSize.Height + GetTop(child as DependencyObject));
					maxWidth = Math.Max(maxWidth, measuredSize.Width + GetLeft(child as DependencyObject));
				}
			}
			// It will not be arranged if always return zero.
			return new Size(maxWidth, maxHeight);
		}
```
The chart is ok.
![image](https://user-images.githubusercontent.com/29876815/106686130-cd961700-6604-11eb-93fc-3c58272abcc0.png)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Daoting** [comment]
Is there a plan to fix this bug? I use it more. Thanks. @jeromelaban @MartinZikmund

**Comment by jeromelaban** [comment]
The behavior of the Canvas in Uno is different with regards to clipping. Your best bet is to set the size of the canvas based on the children. You can probably do this by overriding the canvas.
