### ISSUE TITLE
[Windows] CommandBar Default Style isn't applied correctly

### ISSUE THREAD

**Issue by zangai** [unoplatform/uno#512]
## I'm submitting a...

Regression (a behavior that used to work and stopped working in a new release)
  
 

## Current behavior
The CommandBar Element on UWP doesn't render text with the right font sizing and paddings.

## Expected behavior
The CommandBar Element on UWP renders with the right font sizing and paddings.

## Minimal reproduction of the problem with instructions

Reproduction project is at repo: https://github.com/zangai/Uno-CommandBarStyleRepro

## Environment

```
Nuget Package: 
Microsoft.NETCore.UniversalWindowsPlatform | 6.1.7
Uno.UI | 1.43.0-dev.667

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by davidjohnoliver** [comment]
We don't have any control over how the `CommandBar` renders on Windows. 

Please post a bug report at https://wpdev.uservoice.com/forums/110705-universal-windows-platform
