### ISSUE TITLE
[Gallery][Wasm] TextBox icon is missing

### ISSUE THREAD

**Issue by ebariche** [unoplatform/uno#5122]
## ACTUAL
![image](https://user-images.githubusercontent.com/33458222/106799877-c46d7000-662d-11eb-923b-3e90dfe02267.png)

## EXPECTED
![image](https://user-images.githubusercontent.com/4174207/106804612-a0149200-6633-11eb-830b-5360895fcacc.png)

https://unogallery-wasm-staging.azurewebsites.net/

**Comment by carldebilly** [comment]
## Initial investigation
This icon is shown by using an [attached property](https://github.com/unoplatform/Uno.Material/blob/c2860661be29ae4530f45782e2425a920f1e6849/src/library/Uno.Material/Extensions/ControlExtensions.cs#L13_L17) set [on the `<TextBox>` control](https://github.com/unoplatform/Uno.Material/blob/c2860661be29ae4530f45782e2425a920f1e6849/src/library/Uno.Material/Styles/Controls/TextBox.xaml#L167_L176).

The following binding expression doesn't seems to work - this might be the cause of the non-displaying icon.
```
 Content="{Binding Path=(extensions:ControlExtensions.Icon), RelativeSource={RelativeSource TemplatedParent}}"
```

## At runtime
At runtime, we can see the following in the console output:
```
fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
    The [Uno.Material.Extensions:ControlExtensions.Icon] property getter does not exist on type [Windows.UI.Xaml.Controls.TextBox]
```

Note: it works on iOS & Android.

**Comment by sakshi173** [comment]
Verified, Issue is Fixed -- Closing
![textbox correct](https://user-images.githubusercontent.com/74563602/107134912-37901400-68c4-11eb-98f8-8a23516d5b32.png)
