### ISSUE TITLE
Visual Studio with Uno.UI is too slow and hogs a lot of memory

### ISSUE THREAD

**Issue by IsmailHassani** [unoplatform/uno#5124]
## Current behavior
I noticed that visual studio comes to a halt after using it for an half hour.
It gets almost to a state that it’s unusable. Many plugins crashes and even disabling or uninstalling them doesn’t solve it.
Especially the code completion seems to suffers at first.
Also the memory and CPU usage is absurdly high.
I noticed also that the Roslyn Code Analysis Service and the Uno.SourceGenerator are causing this issue.

[My ticket at visualstudio.com](https://developercommunity2.visualstudio.com/t/visual-studio-is-too-slow-and-hogs-a-lot-of-memory/1326252)

## Workaround
By disabling the code analysis, visual studio is instantly using less cpu and memory

## Environment
Nuget Package:
- [ X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [X ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): Latest stable

Affected platform(s):

- [ ] iOS
- [X ] Android
- [ X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [X ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ X] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
Thanks for the update. Can you specify which version of the uno.ui nuget package you are using ?

Also can you validate if this happens with the latest dev packages of Uno ?

**Comment by IsmailHassani** [comment]
Hi @jeromelaban, i'm using version 3.4.0
I'll check if this still happens with the dev-versions.

**Comment by IsmailHassani** [comment]
@jeromelaban It seems that the Uno.SourceGeneration.Host process still uses a lot of memory and also is not killed after the buid
![image](https://user-images.githubusercontent.com/7172716/106928271-4b484880-6713-11eb-93da-2d35231c2f7b.png)

**Comment by IsmailHassani** [comment]
@jeromelaban And this is after i close visual studio.
It looks like the Uno.SourceGeneration.Host is keeping Visual Studio alive after closing it.

![image](https://user-images.githubusercontent.com/7172716/106928820-e6d9b900-6713-11eb-8170-c52dd8e82174.png)

**Comment by jeromelaban** [comment]
Thanks for the update. It's not keeping VS alive, but since those processes were created through VS, they're flagged as part of.

This issue is not something that we can address until .NET 6 is available for Android/iOS. You can disable persistent processes (even if they close after about 10 minutes) by setting this: 

```xml
<PropertyGroup>
  <UnoSourceGeneratorUseGenerationController>false</UnoSourceGeneratorUseGenerationController>
</PropertyGroup>
```

to your project file.

Note that this is fixed when using .NET 5 (WebAssembly and Skia) as the source generation is done by the compiler itself.

**Comment by IsmailHassani** [comment]
@jeromelaban Ok thank you i will try that.

**Comment by xperiandri** [comment]
@IsmailHassani do you have any extensions or analyzers installed? Like CodeRush or Microsoft.CodeAnalysis.NetAnalyzers.

**Comment by IsmailHassani** [comment]
No, no analyzers that I added myself. The strange thing is that something is making vs slower in time till it crashes. I disabled code lens, Rosslyn analyzer and removed even the uno templates.

**Comment by xperiandri** [comment]
Uno Templates is just a set of templates. Not something that Visual Studio loads as code

**Comment by IsmailHassani** [comment]
@xperiandri I know, but wanted to disable all extensions (also GhostDoc and any preview extension).

**Comment by IsmailHassani** [comment]
After struggling for weeks I noticed, that these issues especially rise when using Uno.
I'm out of fresh ideas.

**Comment by fangeles02** [comment]
There are times that my PC will shut off, either the operating system crashed because of this issue.

**Comment by jeromelaban** [comment]
@fangeles02 did you apply the workaround specified here: https://github.com/unoplatform/uno/issues/5124#issuecomment-773468396 ?

**Comment by jeromelaban** [comment]
Closing in favor of https://github.com/unoplatform/uno/issues/7506.
