### ISSUE TITLE
Content not clipped when rounded border is semi-opaque

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#5126]
## Current behavior

Consider the following:

```
<Border BorderThickness="4"
    x:Name="MainBorder"
    CornerRadius="10"
    BorderBrush="#33FF0000">
			<Grid>
				<Rectangle Fill="Green"
                           Height="16"
                           Width="16"
                           HorizontalAlignment="Left"
                           VerticalAlignment="Top" />
```

Notice the green rectangle is clipped on WASM, even though it is not on UWP:

![image](https://user-images.githubusercontent.com/1075116/106902750-72921c00-66f9-11eb-9461-ec89f61fb991.png)

## Expected behavior

Should be clipped.

## How to reproduce it (as minimally and precisely as possible)

See above.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by carldebilly** [comment]
@MartinZikmund I just tested on the playground: https://playground.platform.uno/#c04005c9 -- [also on canary](https://playgroundcanary.z19.web.core.windows.net/#c04005c9)

... and it seems clipped enough for me.

**Comment by MartinZikmund** [comment]
@carldebilly I thought the border should clip even the inner side, but Steve mentioned it should not, so this was a false positive 😀

**Comment by carldebilly** [comment]
Wait...  you specified the problem was with the "WebAssembly" version of the nuget package, but the affected platform is Skia...
@MartinZikmund

Wasm:
![image](https://user-images.githubusercontent.com/4174207/106897781-65f1d180-66c1-11eb-9bf7-735827c70a81.png)


... and I just ran the same XAML in XAML Studio and I got this:
![image](https://user-images.githubusercontent.com/4174207/106897737-55415b80-66c1-11eb-98ed-ff6617c739e7.png)

**Comment by MartinZikmund** [comment]
@carldebilly then WASM is wrong 😀 . This is how it looks on UWP:

![image](https://user-images.githubusercontent.com/1075116/106902598-4e363f80-66f9-11eb-8eb9-560625f4bbe4.png)

**Comment by Youssef1313** [comment]
Removing `overflow: hidden` make this case matches UWP. But it seems `overflow: hidden` is required (see https://github.com/unoplatform/uno/pull/4283)

**Comment by carldebilly** [comment]
This should be fixed by PR #6803 :-)

**Comment by Youssef1313** [comment]
@carldebilly Testing on Wasm playground, this is the result:

![image](https://user-images.githubusercontent.com/31348972/210093477-1247aa3f-4455-4674-8a71-8dd9a71fdccf.png)

It doesn't seem to match https://github.com/unoplatform/uno/issues/5126#issuecomment-773320276

**Comment by jeromelaban** [comment]
It looks like @MartinZikmund fixed it in recent border rendering changes!
