### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by programmer8396** [unoplatform/uno#5127]
## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [x] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by programmer8396** [comment]
Ubunut 14.04, python 2.7, libreoffice 4.2.8.2

![Screenshot from 2021-02-04 19:12:20](https://user-images.githubusercontent.com/57538011/106903490-f3e5b080-66f1-11eb-8fdc-016ef8cd7c8a.png)

I tried :
**sudo apt-get install libreoffice python-genshi python-cairo python-lxml python-setuptools
sudo apt-get install libreoffice-script-provider-python
easy_install uno**

helped me to remove uno import error.

Please as  python_uno support for python2.7  removed is there any way to get it and python3-uno isn't support my project

**Comment by carldebilly** [comment]
Hi @programmer8396, I think you reached the wrong repo...  here's it's Uno Platform, a cross-platform UI framework based on Microsoft WinUI.

Python-Uno is totally unrelated to us :-)
