### ISSUE TITLE
[Gallery][Wasm] CheckBox and RadioButton doesn't render properly after theme switch.

### ISSUE THREAD

**Issue by ebariche** [unoplatform/uno#5133]
![chk](https://user-images.githubusercontent.com/33458222/106937344-a403eb00-66eb-11eb-8c52-9cb1915cad91.gif)
![RB Gallery](https://user-images.githubusercontent.com/74563602/107159483-59d67000-695e-11eb-83e3-d8180e1945ec.png)

**Comment by davidjohnoliver** [comment]
Notes: Not a regression; seems to only occur on WASM.

**Comment by sakshi173** [comment]
Verified, Issue is Fixed, Closing.
