### ISSUE TITLE
[Gallery][Wasm] ModalStandardBottomSheet shifts the page up

### ISSUE THREAD

**Issue by ebariche** [unoplatform/uno#5136]
![modal-btm-sh-drag](https://user-images.githubusercontent.com/33458222/106942214-e7615800-66f1-11eb-8803-6c85ea8248b9.gif)

**Comment by carldebilly** [comment]
## Investigations
Thanks to @florentcm, we diagnosed the scrolling seems to code from the first `<ScrollViewer />` in the app. If you open the browser debugging tools (F12), you can see the scrolled element is the child of the `ScrollContentPresenter` element in the DOM:

![image](https://user-images.githubusercontent.com/4174207/107273402-024b0980-6a1d-11eb-95da-4ee9862358d4.png)

![image](https://user-images.githubusercontent.com/4174207/107273544-31fa1180-6a1d-11eb-9f6e-08915799c414.png)
``` javascript
document.getElementById("402546").scrollTop
362
```

**Comment by francoistanguay** [comment]
Control is deprecated. Being replaced by Drawer.
