### ISSUE TITLE
[Gallery][Skia.GTK] Samples from OverviewPage appear to be blank

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#5137]
## Current behavior

![image](https://user-images.githubusercontent.com/2359550/106945032-52f8f480-66f5-11eb-9a81-79a8a402ef94.png)
Samples from OverviewPage appear to be blank (for both Material or Fluent tab)

## Expected behavior

Should not happen.

## How to reproduce it (as minimally and precisely as possible)

Launch the Uno.Gallry app on Skia.GTK

## Environment

Nuget Package: Uno.UI.Skia.Gtk
Nuget Package Version(s):  3.5.0-dev.256
Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [ ] WPF
  - [x] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
This will be fixed by update to latest Uno - fixed by https://github.com/unoplatform/uno/pull/5129

**Comment by sakshi173** [comment]
issue is fixed, closing
