### ISSUE TITLE
[Gallery][Wasm] StandardBottomSheet sample is broken

### ISSUE THREAD

**Issue by ebariche** [unoplatform/uno#5138]
![btm-sh-broken](https://user-images.githubusercontent.com/33458222/106946875-b2580400-66f7-11eb-85ee-afadb7486e61.gif)

**Comment by carldebilly** [comment]
Seems related to https://github.com/unoplatform/uno/issues/5136

**Comment by francoistanguay** [comment]
Control is deprecated. Being replaced by Drawer.
