### ISSUE TITLE
[Gallery][Wasm] Multiline Fluent TextBox is not the same as UWP

### ISSUE THREAD

**Issue by ebariche** [unoplatform/uno#5142]
Wasm

![image](https://user-images.githubusercontent.com/33458222/106955293-0ddbbf00-6703-11eb-9106-1b48a8f8dec1.png)

UWP

![image](https://user-images.githubusercontent.com/33458222/106955373-2ba92400-6703-11eb-8c8b-4f4913273e51.png)

**Comment by sakshi173** [comment]
Verified, issue is fixed, Closing.
