### ISSUE TITLE
Issues regarding Pivot control

### ISSUE THREAD

**Issue by Mohsens22** [unoplatform/uno#5144]
## Current behavior

When using a pivot with binding, after the page loads, all of the contents of all pages are stacked onto each other.
![image](https://user-images.githubusercontent.com/22152065/106963452-db0ee680-6755-11eb-9434-89e312dd1ace.png)

Problem number 2:
When using pivot controls, something similar to #5125 happens.

## Expected behavior

The expected behavior is that it normally loads the data from the binding and shows  it properly, just like UWP.

## How to reproduce it (as minimally and precisely as possible)
See this code:
http://playground.platform.uno/#aed77628

## Workaround

Workaround for binding issue: initialize a 10-100 millisecond delay from the load of the page/ViewModel to binding.
Workaround for display issue: Create a custom pivot template and get rid of the scroll viewer inside it.

## Environment

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [x ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [x] Visual Studio 2019 (version: Latest)

**Comment by carldebilly** [comment]
It's very strange because changing the data will fix the problem. Look like a state problem.

**Comment by Mohsens22** [comment]
![image](https://user-images.githubusercontent.com/22152065/107161652-53261800-69b3-11eb-980d-133e869a12c5.png)
Things in Skia are way worse

**Comment by Mohsens22** [comment]
It doesn't even show the default two-way bound data

**Comment by ajpinedam** [comment]
Hi @Mohsens22 thank you for reporting this issue and also for providing an easy way to reproduce it. 

I see you selected Android as one of the affected platforms, is this correct?

I was capable of reproducing the error using the code you provided on both Skia and WASM but I haven't been able to reproduce it on Android (Pixel XL Android 10).

Anyways I will be looking to fix this, just wanted to make sure we are fixing all the affected platforms.

Andres
