### ISSUE TITLE
[ios/droid][Gallery][ListView] odd behavior with SelectedItem

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#5147]
## Current behavior

![20210204 listview selecteditem](https://user-images.githubusercontent.com/2359550/106986218-eb649880-6738-11eb-8bab-37e4f95963ab.gif)
ios/droid: despite having SelectedItem set initially, the textblock is not showing
droid (right): 1st item cannot be selected (presumably it is already selected, but visually it tells another story)
ios (middle): 1st item is always selected. you have to select it again, before it can be deselected

**Comment by Youssef1313** [comment]
Possibly related issue: https://github.com/unoplatform/uno/issues/4686,

**Comment by jeromelaban** [comment]
Works properly on gallery latest.
