### ISSUE TITLE
[Wasm] Attached properties should not be linked-out

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#5153]
## Current behavior
Since attached properties are resolved using a bunch of reflection, their `Get`/`Set` static methods may get linked-out in applications.

## Expected behavior
We should find a way to prevent this linker removal from happening.

## Workaround
Currently we need to add them to LinkerConfig.xml

## Environment
WASM

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
The linker now contains features to handle this properly. See https://github.com/unoplatform/uno/pull/10608
