### ISSUE TITLE
[Gallery][Android/WASM] Flyout, Combobox, Textbox, Animation is not showing properly after theme switch.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5166]
## Current behavior
![Flyout changing day mode issue](https://user-images.githubusercontent.com/74563602/107088004-4db9a980-67ca-11eb-977c-a1e3b044d506.png)
![CB material issue](https://user-images.githubusercontent.com/74563602/107089384-88bcdc80-67cc-11eb-829d-58a8a8fa3021.png)
![CB Fluent issue](https://user-images.githubusercontent.com/74563602/107089399-8fe3ea80-67cc-11eb-85a3-6e78e061cd01.png)
![animation wasm issue](https://user-images.githubusercontent.com/74563602/107160452-45957180-6964-11eb-85fd-662434604fe3.png)

## Expected behavior
![flyout correct](https://user-images.githubusercontent.com/74563602/107088015-514d3080-67ca-11eb-9557-78ef78cb8dc4.png)

## How to reproduce it 

1. Open Uno Gallery APP for canary.
2. Change theme from Day mode to Night mode.
3. Click "Flyout" or "Combobox" option from Burger Menu. 
4. Again Change theme from Night mode to Day mode.
5. Observe that for Flyout and "Combobox" the details are not displaying correctly.

## Environment

Package Version(s):
Version 1.4.3 (400661)

Affected platform(s):

- [ ] Android

**Comment by davidjohnoliver** [comment]
Note: also occurs on WASM, not a regression there

**Comment by davidjohnoliver** [comment]
Investigation notes: 
 - Fluent ComboBox has issues with this line: `Foreground="{Binding PlaceholderForeground, RelativeSource={RelativeSource TemplatedParent}, TargetNullValue={ThemeResource ComboBoxPlaceHolderForeground}}"`. Fluent TextBox may be the same thing (not verified)

**Comment by carldebilly** [comment]
@davidjohnoliver So it's a binding problem?

**Comment by davidjohnoliver** [comment]
@carldebilly There is a problem and it involves a binding, so you could call it a binding problem

**Comment by davidjohnoliver** [comment]
The Flyout and Animation sample frames are fixed by #5194. ComboBox and TextBox still need to be fixed.

**Comment by Guidemarcus** [comment]
This is occuring on Uno.Themes as well.

**Comment by davidjohnoliver** [comment]
> This is occuring on Uno.Themes as well.

@Guidemarcus can you provide more detail?

**Comment by sakshi173** [comment]
Verified, issue is fixed, closing
