### ISSUE TITLE
CommandBar's Foreground property affects NavigationCommand's icon

### ISSUE THREAD

**Issue by yannik-beaulieu-ia** [unoplatform/uno#5167]
## Current behavior

Property `Foreground` of `CommandBar` applies given color to `NavigationCommand`'s icon on Android. [Documentation](https://platform.uno/docs/articles/controls/CommandBar.html#foreground) doesn't seem to mention `Foreground` affecting anything other than the `CommandBar`'s title color.

Android:
![NavigationCommand Foreground (Android)](https://user-images.githubusercontent.com/77288515/107088481-01229e00-67cb-11eb-9994-d37554042a5b.jpg)

Doesn't happen on iOS:
![NavigationCommand Foreground (iOS)](https://user-images.githubusercontent.com/77288515/107088491-0849ac00-67cb-11eb-82ed-3d65fb6da714.jpeg)

## Expected behavior

`Foreground` should only affect title and behave the same on all supported platforms.

## How to reproduce it (as minimally and precisely as possible)

1. Add a `Foreground` color to a `CommandBar` that has a `NavigationCommand` with an icon
2. Build and deploy to an Android device/emulator
3. Notice the `CommandBar`'s `Foreground` color is applied to `NavigationCommand`'s icon

Example: 
``` XAML
<CommandBar Content="Quotes" Foreground="Magenta">
	<toolkit:CommandBarExtensions.NavigationCommand>
		<AppBarButton Command="{Binding NavigateBack}">
			<AppBarButton.Icon>
				<BitmapIcon UriSource="ms-appx:///Assets/Image_Example.png" />
			</AppBarButton.Icon>
		</AppBarButton>
	</toolkit:CommandBarExtensions.NavigationCommand>
</CommandBar>
```

Sample project: https://github.com/yannik-beaulieu-ia/UnoApplicationTemplate

## Workaround

No known workaround at the moment.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.4.0

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [X] Resharper (version: 2020.2.4)

## Anything else we need to know?

A documentation update would be nice if this is a known issue or intended behavior.

**Comment by davidjohnoliver** [comment]
How does UWP behave in that case?

**Comment by yannik-beaulieu-ia** [comment]
Looks like the color isn't applied to the icon but the icon is also black instead of blue and white.

![image](https://user-images.githubusercontent.com/77288515/107798880-b5bc4280-6d2a-11eb-98d1-a0a0ef7b6b73.png)
