### ISSUE TITLE
[Gallery][Android] When Components and Features options of Burger list are expended, scroll is slow. 

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5172]
## How to reproduce it
1. Open Uno Gallery APP for canary.
2. Click Burger Menu on the left top right.
3. Click "Components" or "Features" from the Burger Menu list/
4. Scroll the "Components" or "Features" list.
5. Observe the scrolling is not happening properly.

## Current behavior
![scroll bar](https://user-images.githubusercontent.com/74563602/107123668-c40ee800-686c-11eb-8315-4788bb00187a.png)

## Expected behavior
![scroll bar correct](https://user-images.githubusercontent.com/74563602/107123670-ca9d5f80-686c-11eb-91c0-21fc1ebf10e9.png)

**Environment
Nuget Package**:
Uno.UI 3.5.0-dev.471

**Version(s):**
Version 1.4.3 (400672)

Device:
Samsung S8 - 8.0
Motorola g(7) – 9

**Affected platform(s):**
Android

**Comment by MartinZikmund** [comment]
Tested this and except for a small bottom padding the NavView does show all items. The padding is caused by footer items repeater, I will make a PR to set its size to 0 to make the padding smaller. The main issue then is performance during the scrolling

**Comment by sakshi173** [comment]
Still issue is present.
Verified on Version:-
Version 1.4.3 (400713)
Feb 09, 2021 at 22:34
52.63 MB

**Comment by sakshi173** [comment]
Still issue is present.
Verified on Version:-
Version 1.4.3 (400713)
Feb 09, 2021 at 22:34
52.63 MB

**Comment by MartinZikmund** [comment]
Seems fixed, can you check please @sakshi173 🙂?
