### ISSUE TITLE
[Gallery][iOS]<DatePicker> On Date Calendar "Cancel" and "Done" button get freezes when try to change the date second time

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5174]
## Current behavior

https://user-images.githubusercontent.com/74563602/107136756-07507180-68d4-11eb-878f-a0f4f4ff7544.MOV

## Expected behavior
Everytime "Cancel" and "Done" button should work and Date should get change everytime.
![datepicker correct](https://user-images.githubusercontent.com/74563602/107137021-66af8100-68d6-11eb-82f5-2aae2d962c27.png)

## **How to reproduce it** 

1. Open Uno Gallery APP for canary.
2. Click "DatePicker" option from Burger Menu.
3. Click on date box in "Default" section
4. Choose any date from calendar.
5. Click "Done" button.
6. Click on date box again
7. Choose any other date again
8. Click "cancel" or "Done" button
9. Observe that "Cancel" and "Done" is not working.

Version(s):
Version 1.4.3 (672)

Device:
iphone 12 - 14.1

Affected platform(s):
iOS

**Comment by carldebilly** [comment]
This will be fixed by https://github.com/unoplatform/uno/pull/4956

**Comment by sakshi173** [comment]
Issue is fixed, closing
