### ISSUE TITLE
[Gallery][iOS/WASM] <Fluent> Nested flyout is not displaying properly when changing theme in Day and Night mode multiple times

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5175]
## Current behavior
![flyout nightmode](https://user-images.githubusercontent.com/74563602/107138047-db3aed80-68df-11eb-9fef-302d01efe80a.png)

## Expected behavior
![flyout night mode correct](https://user-images.githubusercontent.com/74563602/107138117-6a480580-68e0-11eb-8be4-5e5124493c96.png)

## How to reproduce it 

1. Open Uno Gallery APP for canary.
2. Click "Flyout" option from Burger Menu.
3. Change theme from Day mode to Night mode.
4. Click “Help”, "Open", "Options" Button in "Flyout" section.
5. Observe the Nested flyout is not displaying correctly.

Version(s):
Version 1.4.3 (672)

Device:
iphone 12 - 14.1

Affected platform(s):
iOS

**Comment by davidjohnoliver** [comment]
This seems to be fixed with latest Uno... I am not sure why? Maybe changes w.r.t. DataContext propagation in flyouts?

**Comment by sakshi173** [comment]
Verified, Issue is fixed, Closing.
