### ISSUE TITLE
[Gallery][iOS]<ListView> In "SelectedItem" two color sections are hightlighting together.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5177]
## Current behavior

![listview ios issue](https://user-images.githubusercontent.com/74563602/107138937-a92c8a00-68e5-11eb-97d6-e22b280d305f.png)

## Expected behavior
![listview correct](https://user-images.githubusercontent.com/74563602/107138940-b34e8880-68e5-11eb-9feb-91cade883128.png)

## How to reproduce it

1. Open Uno Gallery APP for canary.
2. Click "ListView" option from Burger Menu.
3. Check "SelectedItem section.
4. Observe that two colors sections are highlighting together.

Environment
Nuget Package:

Version(s):
Version 1.4.3 (672)

Device:
iphone 12 - 14.1

Affected platform(s):
iOS

**Comment by davidjohnoliver** [comment]
(Very rapid) investigation notes: Probably related-ish to https://github.com/unoplatform/uno/issues/4686 (it looks like setting SelectedIndex=0 is causing the selection visual state to be applied, but the SelectedItem is seemingly not set). Should probably be tackled together with https://github.com/unoplatform/uno/issues/4686.
