### ISSUE TITLE
[Gallery][WASM]ExpandingBottomSheet- When expanding code box, footer information overlap the Toggle Minimal Sheet button.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5180]
## Current behavior
![expandingbottomsheet issue 1](https://user-images.githubusercontent.com/74563602/107172143-a176ef00-6992-11eb-9316-bdffc2314cc6.png)

## Expected behavior
The toggle Minimum sheet should not overlap with footer infomation

## How to reproduce it 
1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Click on “ExpandingBottomsheet” option from the Burger menu.
3. Click "<>" sign to expand code.
4. Scroll the page upto end.
5. Observe that the Toggle Minimum sheet is overlapping footer information.

Affected platform(s):
Windows

**Comment by Xiaoy312** [comment]
Just a minor problem with how the page is constructed. The sample, toggle, and bottom-sheet are all inside a grid.

**Comment by sakshi173** [comment]
Verified, Issue is Fixed -- Closing.

**Comment by sakshi173** [comment]
Verified, issue is fixed, closing.
