### ISSUE TITLE
Windows.UI.Color ToString does not behave the same as UWP

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#5189]
See https://docs.microsoft.com/en-us/uwp/api/windows.ui.color?view=winrt-19041#tostring-behavior-for-color

Calling ToString on a Color should behave like so:
A=255, R=0, G=128, B=255 is "#FF0080FF".

## Current behavior

For a Color with properties: A=255, R=0, G=128, B=255
Uno's ToString for Color returns a string of [Color: 000000FF;00000000;00000080;000000FF] 

## Expected behavior

For a Color with properties: A=255, R=0, G=128, B=255
Uno's ToString for Color should return a string of #FF0080FF

## Environment

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
Fixed in #6437
