### ISSUE TITLE
[Skia] `TextBlock` styling may not be applied reliably for multiline text

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5191]
## Current behavior

The `This paragraph contains an hyperlink that wraps over multiple lines, surrounded by regular text.` one is probably missing an underline for part of the hyperlink.

![image](https://user-images.githubusercontent.com/31348972/187835293-5c027d95-7177-475d-b9c8-921a965874cb.png)

## Expected behavior
"Uno Platform" should display and work as hyperlink.

## How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app on Skia.GTK
2. Click on “HyperlinkButton” option from the list.
3. Observe "Uno Platform" is not displaying as hyperlink and not working as hyperlink when clicking it.

Nuget Package: Uno.UI.Skia.Gtk

Affected platform(s):
GTK (Linux)

IDE:
Visual Studio 2019 (version: )

**Comment by sakshi173** [comment]
Hyperlink is working for HyperlinkButton, But issue is still present for **Official documentation** and due to that reopening the issue.
![office documentation issue](https://user-images.githubusercontent.com/74563602/111719543-781f6d80-8832-11eb-8c63-3f6a72dce5fd.png)

**Comment by sakshi173** [comment]
Hyperlink is working for HyperlinkButton, But issue is still present for Official documentation and due to that reopening the issue.
![office documentation issue](https://user-images.githubusercontent.com/74563602/112053868-46a4eb80-8b2b-11eb-93e5-14862b9da7f6.png)

**Comment by sakshi173** [comment]
Still the hyperlink is not working for **official Documentation**

![Hyperlink issue](https://user-images.githubusercontent.com/74563602/128752004-8e157fc0-4c17-4a72-b179-2aadf4011e7b.png)

**Comment by MartinZikmund** [comment]
The issue is currently the fact that `Hyperlink` within `TextBlock` on Skia is not supported. Changed the title accordingly.

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/blob/92bd1e47034a5cb879b6e3201cd56bf067f50807/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_Hyperlink.xaml#L80

![image](https://user-images.githubusercontent.com/31348972/187835293-5c027d95-7177-475d-b9c8-921a965874cb.png)

Looks like it's working now?

@sakshi173 Can you confirm?

**Comment by Youssef1313** [comment]
The `This paragraph contains an hyperlink that wraps over multiple lines, surrounded by regular text.` one is probably missing an underline for part of the hyperlink.

**Comment by jeromelaban** [comment]
> The This paragraph contains an hyperlink that wraps over multiple lines, surrounded by regular text. one is probably missing an underline for part of the hyperlink.



@sakshi173 can you open an issue specifically for this?

**Comment by sakshi173** [comment]
@jeromelaban, sorry I didn't get it exactly, but now the issue is the link **Official Documentation** is missing for WASM and Skia.Gtk and I can raise a separate issue for that, please let me know your views.

**Comment by jeromelaban** [comment]
@sakshi173 Actually, let's keep as is in this issue, after looking again at the issue.

**Comment by MartinZikmund** [comment]
![Uploading image.png…]()

This is now working!

**Comment by MartinZikmund** [comment]
<img width="350" alt="image" src="https://github.com/unoplatform/uno/assets/1075116/e575b4e5-865c-440b-9415-62f467f96750">

This is now working!
