### ISSUE TITLE
NavigationView: PaneToggleButton style is not working correctly

### ISSUE THREAD

**Issue by LeftTwixWand** [unoplatform/uno#5193]
## Current behavior
I'm trying to customize NavigationView, by changing Setting icon and PaneToggleButton.
Using Blend I've got source code of NavigationView and put it into separated RecourceDictionaty:
```XAML
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" 
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <Style x:Key="PaneToggleButtonStyle" TargetType="Button"/>
    <Style  TargetType="NavigationView">
    <!--And here I'm changing NavigationViewItem for settings-->

    <NavigationViewItem x:Name="SettingsNavPaneItem" Grid.Row="8">
        <NavigationViewItem.Icon>
            <BitmapIcon UriSource="ms-appx:///Assets/Settings.png" ShowAsMonochrome="False"/>
        </NavigationViewItem.Icon>
    </NavigationViewItem>

</ResourceDictionary> 
```
And refer it at `App.xaml`
```XAML
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="Styles/NavigationViewStyle.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
```

For UWP it forks normal, but using UNO I've got some problems. Hamburger button just stops showing.

![image](https://user-images.githubusercontent.com/50652041/107388183-3b0edf80-6afe-11eb-92f9-9c8a920e8877.png)

## How to reproduce it (as minimally and precisely as possible)

git clone https://github.com/LeftTwixWand/UnoApp.git
git checkout c838ff5cefeba808d87cb8eea35040844528532e

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [x] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.4.0
Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [ ] WPF
  - [x] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: latest)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
Not sure about the reason for the issue yet, but can you try the same with the new `Microsoft.UI.Xaml.Controls.NavigationView`? We added support for it in 3.4.0 and it should be more stable than the old `Windows.UI.Xaml` version.

**Comment by LeftTwixWand** [comment]
I've installed Microsoft.UI.Xaml v2.5.0 and added reference to `App.xaml`:
```XAML
<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
```
But for Skia.Gtk project, NavigationView is just disappeared.
Repository link: [github.com/LeftTwixWand/UnoApp](github.com/LeftTwixWand/UnoApp)

**Comment by MartinZikmund** [comment]
This is now working properly with the new WinUI `NavigationView`. The issue with it not appearing has been fixed too 🚀
