### ISSUE TITLE
[Gallery][Skia.GTK]Progress Ring/Bar page is blank.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5206]
## Current behavior
![prog Ring issue](https://user-images.githubusercontent.com/74563602/107551048-c55b5000-6b9f-11eb-816f-6d54eb93b55c.png)

## Expected behavior
![prog Ring correct](https://user-images.githubusercontent.com/74563602/107551056-c8564080-6b9f-11eb-964c-3b2657b5cc9f.png)

## How to reproduce it (as minimally and precisely as possible)
Launch the Uno.Gallry app on Skia.GTK
Click on “Progress Ring/Bar” item from the list.
Observe the Page is blank.

Nuget Package: Uno.UI.Skia.Gtk

Affected platform(s):
GTK (Linux)

IDE:
Visual Studio 2019 (version: )

**Comment by kazo0** [comment]
@sakshi173 Should we close this one or can you still get it to happen?

**Comment by TrevorDArcyEvans** [comment]
Happening for me too on:
Linux Mint 20.1

**Comment by sakshi173** [comment]
@kazo0 I pulled the latest code and now this issue is not happening.
![PR Bar correct](https://user-images.githubusercontent.com/74563602/107824916-3d687800-6d50-11eb-8cec-d4a1ae5da58d.png)
