### ISSUE TITLE
[Android] TextBox with InputScope as CurrencyAmount move the cursor on the left when pressing comma.

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#5207]
## Current behavior
As you can see, the cursor moves to the left after pressing the comma.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17461593/107552043-0142e500-6ba1-11eb-8f06-534c8485839a.gif)

## Expected behavior

It should not move the cursor what so ever after pressing the comma by default. This behavior does not happend on neither xamarin.classic nor native.

Xamarin.Classic [TextBoxCurrency_Xamarin.zip](https://github.com/unoplatform/uno/files/5960428/TextBoxCurrency_Xamarin.zip)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17461593/107552231-2f282980-6ba1-11eb-85d5-1a6613459655.gif)

Native [TextBoxCurrency_Native.zip](https://github.com/unoplatform/uno/files/5960431/TextBoxCurrency_Native.zip)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17461593/107552364-68609980-6ba1-11eb-8aa0-5ba0c64d262c.gif)

## How to reproduce it (as minimally and precisely as possible)

Download this sample [TextBoxCurrency_Uno.zip](https://github.com/unoplatform/uno/files/5960440/TextBoxCurrency_Uno.zip)
Deploy on Android
Try to enter "2,2"

## Workaround

I mean I could use a similar InputScope (for instance `NumberFullWidth`) for now. Ideally, I would need a way to import what works on the xamarin sample into my project as a workaround but I couldn't figure it out if it's even possible.

```xml
<EditText
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:digits="1234567890,." // <-- Have this one too, so I can actually press the comma key.
        android:inputType="numberDecimal" // <-- If I could somehow use this one.
        android:text="" />
```

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.6.0-dev.27

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment]
Possibly duplicate of https://github.com/unoplatform/uno/issues/2557

**Comment by Youssef1313** [comment]
The issue here is the InputScope in UWP just changes the touch screen keyboard, but don't do any validation. However, Android's `inputType` does validation and don't allow entering `,` for example. (I'm not sure how Uno managed to enter the comma while it's completely disallowed in Android)

We need a way to only change the keyboard, but without doing validation. I didn't manage to do that in native Android.

**Comment by francoistanguay** [comment]
Can we test again @takla21  ?

**Comment by takla21** [comment]
Yeah I've tested on the latest dev uno version 4.1.0-dev.283 and the issue is gone.
