### ISSUE TITLE
Make updated TabView samples

### ISSUE THREAD

**Issue by manfromarce** [unoplatform/uno#5211]
## What would you like to be added:
Basic TabView sample that just shows how to use it in a shared project.

## Why is this needed:
It's unclear on which platforms TabView is supported and which dependencies are needed. I added Microsoft.UI.Xaml.Controls but I get a lot of errors in Visual Studio 2019.

## For which Platform:
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] iOS
- [x] Android
- [x] macOS
- [x] Windows
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen

**Comment by MartinZikmund** [comment]
@manfromarce hey, `TabView` should work across all platforms, what issues do you encounter specifically? Can you send some minimal repro?

**Comment by manfromarce** [comment]
Hi, I had added some wrong nuget packages and Visual Studio failed to compile but creating a new solution and referencing Microsoft.Ui.Xaml package in every project solved the issue. Thanks for your help
