### ISSUE TITLE
`NavigationView` without settings item has additional bottom padding

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#5212]
## Current behavior

`NavigationView` control has additional bottom padding when there is no settings item compared to UWP.

## Expected behavior

No additional padding.

## How to reproduce it (as minimally and precisely as possible)

Add `NavigationView` with many primary menu items, but no footer items and no settings item.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by morning4coffe-dev** [comment]
@MartinZikmund @dr1rrb I don't think I see any issue with `Uno.Sdk 5.3.0-dev.1827`. I tested on all platforms (except iOS) and everywhere it seems the same as WinUI:

https://github.com/unoplatform/uno/assets/78549750/57678fc5-bf4c-47e9-89ea-448e8b3c54aa
