### ISSUE TITLE
[iOS] FileSavePicker

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#5229]
Part of #3215

## What would you like to be added:

`FileSavePicker` on iOS.

## Why is this needed:

💾

## For which Platform:

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
@jeromelaban As "save picker" experience is not available on iOS, I thought we could have iOS go through the same implementation as Skia - by default it would not be available, but if you implemented[ `IFileSavePickerExtension`](https://github.com/unoplatform/uno/blob/master/src/Uno.UWP/Storage/Pickers/Internal/IFileSavePickerExtension.skia.cs) you could then use the `FileSavePicker` without any `#if __IOS__` branching. I would provide the example `IFileSavePicker` implementation that I was mentioning before in `Uno.Samples` on in a separate repo, so developers who would want to use the picker on iOS could just copy-paste the `IFileSavePickerExtension` implementation, adjust it to their liking and use it in their project. The only downside would be that the `IFileSavePickerExtension` would need to be made `public`, but as a result we could have a complete solution without "platform specifics".

**Comment by jeromelaban** [comment]
Makes sense! Yes, let's document that and we can put the api public.
