### ISSUE TITLE
[Skia.WPF] FolderPicker

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#5233]
# Waiting for https://github.com/dotnet/wpf/issues/7689

Part of #3916

## What would you like to be added:

`FolderPicker` on WPF

## Why is this needed:

📁

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [x] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
**Resources:**
- https://github.com/dotnet/wpf/issues/438
- https://github.com/dotnet/wpf/pull/4039

**Comment by MartinZikmund** [comment]
Seems that the only really usable solution would be to integrate **Ookii Dialogs** - https://github.com/ookii-dialogs/ookii-dialogs-wpf/. This would add an additional dependency to WPF head. Alternative would be to add Windows.Forms Folder browser, but that one is far less functional and would add the whole Windows.Forms framework, which would be even costlier.

**Comment by miloush** [comment]
How is that more usable than other solutions, and what functionality is the Windows.Forms folder browser missing to be "far less functional"?

Users can already add Ookii dependency to their projects if desired, so I am not really sure how forcing it onto everyone is addressing the issue. Furthermore, you would be duplicating types and functionality already existing in the framework.

Are you suggesting WPF currently does not have a dependency on Windows.Forms?
