### ISSUE TITLE
[Gallery][Skia.GTK]Date Picker page is blank. 

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5236]
## Current behavior
![Datepicker issue](https://user-images.githubusercontent.com/74563602/107826506-ffb91e80-6d52-11eb-9c0a-c9ad014c5625.png)

## Expected behavior
Date Picker should display properly.

## How to reproduce it 
1. Launch the Uno.Gallry app on Skia.GTK
2. Click on “DatePicker” item from the list.
3. Observe the Page is blank.

Nuget Package: Uno.UI.Skia.Gtk

Affected platform(s):
GTK (Linux)

IDE:
Visual Studio 2019 (version: )

**Comment by MartinZikmund** [comment]
@sakshi173 is this still not working now?

**Comment by Youssef1313** [comment]
I cannot reproduce:

![image](https://user-images.githubusercontent.com/31348972/133970540-2053b560-a2f3-465b-a6cf-a0098d57353a.png)


@sakshi173 Can you confirm please? Thanks :)

**Comment by sakshi173** [comment]
Yes @Youssef1313, it is fixed. you can close it.

**Comment by Youssef1313** [comment]
I don't have access to. @jeromelaban Can you close?
