### ISSUE TITLE
[iOS]: iOS head no longer loading after clearing the NuGet cache

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#5241]
I had to clear the NuGet cache since the Telerik installation messed up my Visual Studio setup ... :-(

Now the iOS head no longer loads: "The 'XamarinIOSPackage' package did not load correctly ". I get a similar issue on a brand new UNO solution. Activity log file attached

Any idea how to resolve the issue?

Thanks in advance

[ActivityLog.zip](https://github.com/unoplatform/uno/files/5978075/ActivityLog.zip)

**Comment by jeromelaban** [comment]
@DierkDroth clearing the nuget cache is generally not causing this specific issue, but rather a visual studio issue in itself.

You can try building the application from the command line by using `msbuild /r youapp.csproj`, but in all likelyhood, repairing visual studio make be a better option.

**Comment by xperiandri** [comment]
Try to install Clear MEF Cache extension and clear it.
If it does not help try to restore Visual Studio.

**Comment by DierkDroth** [comment]
- I repaired Visual Studio
- installed and ran the Clear MEF Cache extension
... but am getting still the same error.

Please advise. Thanks

**Comment by xperiandri** [comment]
It means that Xamarin.iOS is corrupted. Try uninstalling and installing back Xamarin workload

**Comment by DierkDroth** [comment]
I completely uninstalled + reinstalled the workload "Mobile development with .NET" but still am getting the error above when I'm trying to add back the iOS head to my existing solution.

**Comment by xperiandri** [comment]
Then whole Visual Studio is corrupted

**Comment by DierkDroth** [comment]
I don't think so: I just a complete uninstall + reinstall of VS 2019 Professional and am getting the same error still and can't add back the iOS project to my solution

**Comment by DierkDroth** [comment]
@jeromelaban I even downloaded and installed the 'Uno Platform Solution Templates' again and am still getting the error above as I tried to create a brand new Uno app. In addition I now get the error below - which may provide further details

Please advise. Thanks


![image](https://user-images.githubusercontent.com/26179242/108164710-37282200-70e9-11eb-80f9-6c955c0ef028.png)

**Comment by jeromelaban** [comment]
@DierkDroth this is a Visual Studio related issue, which generally means that the Xamarin workload has not been installed or is disabled. Aside from repairing and/or reinstalling visual studio, there's nothing more we can suggest.

**Comment by DierkDroth** [comment]
@jeromelaban to make sure we're on the same page: there is no "Xamarin workload" available in Visual Studio -> Tools -> Get Tools and Features -> Workload tab. There only is "Mobile development with .NET" - which I have checked and installed

Am I looking at the wrong place? Do you mean something different?

**Comment by jeromelaban** [comment]
@DierkDroth this is the xamarin workload, it just changed names. While it is checked, it's not loading for some reason, which repair or reinstall is likely to fix.

**Comment by DierkDroth** [comment]
@jeromelaban I 
- repaired complete VS -> did not help
- then completely uninstalled VS + reinstalled VS + reinstalled workloads -> did not help

I'm dead in the water

**Comment by jeromelaban** [comment]
@DierkDroth this is only something that the Microsoft support can help you with, unfortunately. It's likely that there's something in your system state that prevents the Xamarin addins from working properly. [Microsoft forums](https://social.msdn.microsoft.com/Forums/en-US/home) or [VS Community](https://developercommunity.visualstudio.com/) may be of help there.

**Comment by DierkDroth** [comment]
For anyone running into that problem: [this ](https://developercommunity.visualstudio.com/comments/1326579/view.html)did resolve the issue for me
