### ISSUE TITLE
multiple errors  trying to create UNO UWP app example following UNO getting started instructions

### ISSUE THREAD

**Issue by billwoo** [unoplatform/uno#5242]
]
## Current behavior

A problem was encountered creating the sub project 'UnoApp_1.Droid'.  The project file 'C:\Users\test_user\Desktop\Google Drive\VS 2016\UnoApp_1\UnoApp_1.Droid\UnoApp_1.Droid.csproj' cannot be opened.

There is a missing project subtype.
Subtype: '{EFBA0AD7-5A72-4C68-AF49-83D382785DCF}' is unsupported by this installation.

---------------------------
A problem was encountered creating the sub project 'UnoApp_1.macOS'.  The project file 'C:\Users\test_user\Desktop\Google Drive\VS 2016\UnoApp_1\UnoApp_1.macOS\UnoApp_1.macOS.csproj' cannot be opened.

There is a missing project subtype.
Subtype: '{A3F8F2AB-B479-4A4A-A458-A89E7DC349F1}' is unsupported by this installation.
---------------------------

NPM errors

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1605	Detected package downgrade: Uno.Core from 2.2.0 to 2.1.0. Reference the package directly from the project to select a different version. 
 UnoApp_1.UWP -> Uno.UI 3.5.1 -> Uno.Core (>= 2.2.0) 
 UnoApp_1.UWP -> Uno.Core (>= 2.1.0)	UnoApp_1.UWP	C:\Users\test_user\Desktop\Google Drive\VS 2016\UnoApp_1\UnoApp_1.UWP\UnoApp_1.UWP.csproj	1	
Warning	NU1701	Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.	UnoApp_1.Skia.Gtk	C:\Users\test_user\Desktop\Google Drive\VS 2016\UnoApp_1\UnoApp_1.Skia.Gtk\UnoApp_1.Skia.Gtk.csproj	1	
Warning	NU1701	Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.	UnoApp_1.Skia.Wpf.Host	C:\Users\test_user\Desktop\Google Drive\VS 2016\UnoApp_1\UnoApp_1.Skia.Wpf.Host\UnoApp_1.Skia.Wpf.Host.csproj	1	
Warning	NU1605	Detected package downgrade: Uno.Core from 2.2.0 to 2.1.0. Reference the package directly from the project to select a different version. 
 UnoApp_1.UWP -> Uno.WinUI 3.6.0-dev.62 -> Uno.Core (>= 2.2.0) 
 UnoApp_1.UWP -> Uno.Core (>= 2.1.0)	UnoApp_1.UWP	C:\Users\test_user\Desktop\Google Drive\VS 2016\UnoApp_1\UnoApp_1.UWP\UnoApp_1.UWP.csproj	1	
Warning		C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Tizen\VisualStudio\Tizen.NET.ProjectType.targets is not exist.\
 you need to check if 'Visual Studio for Tizen' is installed	UnoApp_1.Skia.Tizen	C:\Users\test_user\.nuget\packages\tizen.net.sdk\1.1.6\build\Tizen.NET.Sdk.VisualStudio.targets	27	
Warning		C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Tizen\VisualStudio\Tizen.NET.ProjectType.props is not exist.
 you need to check if 'Visual Studio for Tizen' is installed	UnoApp_1.Skia.Tizen	C:\Users\test_user\.nuget\packages\tizen.net.sdk\1.1.6\build\Tizen.NET.Sdk.VisualStudio.targets	26	

## Expected behavior

a   usable app

## How to reproduce it (as minimally and precisely as possible)

follow UNO getting started instructions

## Workaround

unknown

## Environment

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ?] Tizen
- [x ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [x ] Visual Studio 2019 (16.8.5: )

Relevant plugins:

- [x ] Resharper (2021,1  EAP: )

**Comment by xperiandri** [comment]
Looks like you have an old Visual Studio or do not have some components installed

**Comment by jeromelaban** [comment]
Thanks for the report. Make sure to install the Xamarin workload: https://platform.uno/docs/articles/get-started-vs.html#prerequisites

**Comment by AdemYuksel** [comment]
> Rapor için teşekkürler. Xamarin iş yükünü yüklediğinizden emin olun: [https://platform.uno/docs/articles/get-started-vs.html#preconditions](https://platform.uno/docs/articles/get-started-vs.html#prerequisites)
> 
> > <img alt="" width="48" src="../images/UnoLogoSmall.png">**[Visual Studio'ya Başlarken](https://platform.uno/docs/articles/get-started-vs.html#prerequisites)**

Thanks you for answer. How can I forget! 😃

**Comment by billwoo** [comment]
Thix issue is not resolved. I do not use Xamarin.

**Comment by jeromelaban** [comment]
@billwoo You'll need to provide more information about what you're seeing. It's likely different from this issue.
