### ISSUE TITLE
All sorts of text input are broken in Skia.WPF

### ISSUE THREAD

**Issue by Mohsens22** [unoplatform/uno#5243]
## Current behavior

![image](https://user-images.githubusercontent.com/22152065/107906619-c5c06600-6f66-11eb-8ebf-fd86194a9f33.png)

Skia fails to show the content of textboxes. In my case, my text block has a two-way bind to my view model.

## How to reproduce it (as minimally and precisely as possible)

Just make a simple textbox and two-way bind it to a property, run the Skia.WPF head and see the issue

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [x] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: Latest)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

## Anything else we need to know?

In the meanwhile please test the autosuggestbox of UWP and see if it works. In my case, it doesn't work in any platform

**Comment by MartinZikmund** [comment]
Hey, sorry, text input is unfortunately not yet supported in Skia targets. The issue is tracked here - #4319, it will be worked on soon.
