### ISSUE TITLE
How to integrate WinUI

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#5247]
We need to adjust the template to have it by default and also adding documentation

**Comment by davidjohnoliver** [comment]
For the documentation, the steps for enabling WinUI 2 are basically laid out here: https://platform.uno/docs/articles/features/fluent-styles.html

but they're not very discoverable for people looking for 'enable WinUI'

**Comment by MartinZikmund** [comment]
WinUI styles are now enabled by default, so this may be closed, correct? @agneszitte-nventive @davidjohnoliver

**Comment by davidjohnoliver** [comment]
They are, and the documentation was added: https://platform.uno/docs/articles/features/using-winui2.html
