### ISSUE TITLE
[Controls] Hub control

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/uno#5249]
## What would you like to be added:

`Hub` and `HubSection` controls

## Why is this needed:
Hub is always used for the home page of an app.

## For which Platform:

- [X] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by xperiandri** [comment]
We need it for the next project. If someone can have a look at what to do and make a short introductory call, I can try to handle this

**Comment by MartinZikmund** [comment]
I think it will be best to port this control directly from WinUI when available

**Comment by xperiandri** [comment]
Isn't it available yet?

**Comment by xperiandri** [comment]
@jeromelaban any plans about that?

**Comment by MartinZikmund** [comment]
@xperiandri unfortunately this control is not yet open source, but we can see if we could replicate it somehow.

**Comment by francoistanguay** [comment]
Control is obselete. No plan to implement.

**Comment by xperiandri** [comment]
So what is recommended to use instead?

**Comment by francoistanguay** [comment]
https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Hub?view=winrt-22000#remarks
