### ISSUE TITLE
RefreshContainer/RefreshVisualizer controls

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/uno#5251]
## What would you like to be added:
`RefreshContainer` and `RefreshVisualizer` controls

## Why is this needed:
It is the common way to implement the highly necessary _pull to refresh_ feature.

## For which Platform:

- [X] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
Closing in favor of #2697
