### ISSUE TITLE
[GTK] Implement FileOpenPicker

### ISSUE THREAD

**Issue by manfromarce** [unoplatform/uno#5268]
## What would you like to be added:

Support for FileOpenPicker on Linux (Skia Gtk).

## Why is this needed:

- parity with UWP
- work are already in progress for FileOpenPicker on other platforms, it would be nice if Linux was also supported

## For which Platform:
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [x] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?
Part of #508

**Comment by jeromelaban** [comment]
Thanks for the report! /cc @MartinZikmund
