### ISSUE TITLE
[Android] [ListView] SelectedItem property doesn't get updated on selection changed

### ISSUE THREAD

**Issue by pdecostervgls** [unoplatform/uno#527]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)
 

## Current behavior
After selection a ListViewItem from a ListView, the property bound to Selecteditem of the ListView doesn't get changed on Android. Works on UWP.

## Expected behavior
The property bound to the ListView's SelectedItem DP should get changed.

## Minimal reproduction of the problem with instructions
Repro project @ https://github.com/pdecostervgls/Uno-SelectionChangedRepro

## Environment

```
Nuget Package: 
Uno.UI : 1.43.0-dev.714

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: 15.9.5)
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by jeromelaban** [comment]
There's a https://github.com/nventive/Uno/issues/212 with the use of the `DataContext` property set to`this`, which breaks bindings. 

Could you try extracting the code with the ChosenItem property in another class, and set the DataContext to that ?

**Comment by pdecostervgls** [comment]
The repo is updated with the extracted version, which also fixes this issue. I'll create a new issue regarding the order of event firing.

**Comment by jeromelaban** [comment]
After investigating a bit, the behavior of UWP is different depending if the selection is changed from the UI or programmatically. When done programmatically, the bindings to the `Selector.SelectedItem` property are updated **after** the event is raised, but when the list is interacted with by the user, the bindings are updated **before**. 

Replicating this exact behavior is not an easy task as it may have important side effects in the DependencyObject behavior. I suggest you do not rely on this behavior, but rather on the properties of the list themselves.

In the process, I found out that the `SelectionChanged` event is raised twice, which will be adjusted.
