### ISSUE TITLE
Non-unique template names when viewed on VS for Mac

### ISSUE THREAD

**Issue by mrlacey** [unoplatform/uno#5270]
## Current behavior

The template names do not distinguish between an app and a test app when viewed in VS for Mac.

![image](https://user-images.githubusercontent.com/189547/108372671-f4547000-71f6-11eb-8e93-68fd34b691b0.png)

Of the entries in the screenshot, the lower one creates a test app, and the upper one creates an actual Uno app with multiple heads and a shared project. But how would you know?

## Expected behavior

The names of each template clearly indicate what it does and how it is different from the other option(s)

## How to reproduce it (as minimally and precisely as possible)

- Install the templates on a Mac (`dotnet new -i Uno.ProjectTemplates.Dotnet`)
- Go to "File > New Solution" in VS for Mac

## Workaround

Pick one and hope it's what you want.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Template Version: **3.5.1**

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [x] Visual Studio for Mac (version: 8.8.9 (build 10))
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Looks like we're having a duplicate name in our dotnet new template, [here](https://github.com/unoplatform/uno/tree/master/src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content).

**Comment by ebariche** [comment]
Fixed by #5551
