### ISSUE TITLE
[CH9][Android] Burger Menu is not displaying correctly

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5276]
## Current behavior
![ch9 burger issue](https://user-images.githubusercontent.com/74563602/108419650-cd9b3700-7200-11eb-8687-ebc3b20f7f2b.png)

## Expected behavior
Burger list should display correctly

## How to reproduce it 
Open CH9 APP for Canary.
Check the Burger Menu on the top left of the page.
Observe Burger Menu is not displaying correctly.

Version(s):
Version 1.4.3 (400726)

Device:
Samsung S8 - 8.0
Motorola g(7) – 9

Affected platform(s):
Android

**Comment by MartinZikmund** [comment]
@sakshi173 can you check whether this is still broken please?

**Comment by Youssef1313** [comment]
@sakshi173 Can you please confirm whether you're still able to reproduce this?

I couldn't reproduce:

![image](https://user-images.githubusercontent.com/31348972/133971527-428ada06-47e8-492e-b9b2-34620dd78f3f.png)

**Comment by sakshi173** [comment]
I don't have current build to verify this. but ya its very old bug. I think its fixed, @Youssef1313, you can close it.

**Comment by Youssef1313** [comment]
I don't have access to. @jeromelaban Can you close?
