### ISSUE TITLE
[Gallery][Android] StandardBottomSheet cant be opened by click, only dragging works.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5277]
## Current behavior
![SBS issue](https://user-images.githubusercontent.com/74563602/108429227-b0b93080-720d-11eb-9099-4fc7c48f4702.png)

## Expected behavior
Sheetheader should open properly.

## How to reproduce it 
Open Uno Gallery APP for canary.
Click Burger Menu on the left top right.
Click "StandardBottomsheet" from the Burger Menu list
Click on the "sheetHeader" option
Observe the SheetHeader is not opening.

Version(s):
Version 1.4.3 (400726)

Device:
Samsung S8 - 8.0
Motorola g(7) – 9

Affected platform(s):
Android

**Comment by Xiaoy312** [comment]
The control, as it is implemented now, only support dragging, not click to expand.
Looking at the [specs from material.io](https://material.io/components/sheets-bottom#expanding-bottom-sheet), there are no mention of "standard" bottom sheet should be able to do that. Although, without prior experience with the control, the first attempt to use it is to click on it and hope that it expands?
@kazo0 Any thought on this?

**Comment by sakshi173** [comment]
As suggested, Control is deprecated. Being replaced by Drawer. closing it.
