### ISSUE TITLE
LinkerFatalErrorException - Error processing method 'Microsoft.Extensions.Logging.Logger.BeginScope<TState>(TState)'

### ISSUE THREAD

**Issue by Dimigergo** [unoplatform/uno#5279]
## Current behavior

Exception during wasm project build.
And BTW the Microsoft.AspNetCore.App dependency has a warning mark.

## How to reproduce it (as minimally and precisely as possible)

- Create an Uno platform project.
- Make wasm project to .net5 according to this [link](https://platform.uno/blog/uno-platform-3-2-net-5-c-9-support-and-net-5-webassembly-aot-support/) (center of the page: Experiment with the .NET 5 WebAssembly support for Uno)
- Create a .netstandard2.1 class library ("MLR.WiPlan.Shared.Proto")
- Reference it to the wasm project
- Update all nuget package to latest (see in screenshot) except Microsoft.Extension.Logging, and Filter.
- Build wasm project.

The entire diagnostic build log is found here from the output window: 
[wasm_build.txt](https://github.com/unoplatform/uno/files/6008498/wasm_build.txt)
The exception is at line 88183 and of course the end of the build.

The package versions can be checked in this screenshot:
![wasm_build](https://user-images.githubusercontent.com/11498949/108475695-55308680-7291-11eb-8b2e-9877579e8c25.png)

## Environment

- Windows 10 Pro (20H2)

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.0 Preview 4.0)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Microsoft Visual Studio Professional 2019 Preview
Version 16.9.0 Preview 4.0
VisualStudio.16.Preview/16.9.0-pre.4.0+31004.235
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA607
Microsoft Visual C++ 2019

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.9.677.50750
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2107702+c4adaa061f13292143de82a96c71341e50bc4032
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.677.50750
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.677.50750
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.9.677.50750
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.9.0-4.21104.8+2fc92d84e746c3aab75f0930278ea6675cd5bb5c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40201.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62102.01130
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

UnoPlatformPackage Extension   1.0
UnoPlatformPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.9.0-4.21104.8+2fc92d84e746c3aab75f0930278ea6675cd5bb5c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.9.000.258 (d16-9@82c3a34)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.309 (remotes/origin/9a5259fb55e54a445c145ab5ea29c04a418deed2@9a5259fb5)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.65 (0020050)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.0.21 (d16-9/93eab59)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@d6d86b2
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@9d8924d

Xamarin.iOS and Xamarin.Mac SDK   14.14.1.0 (17845a189)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by Dimigergo** [comment]
Just some additional information:

When I commented this line the build is OK, but when I uncommented it the build fails.
![wasm_build_2](https://user-images.githubusercontent.com/11498949/108482934-67fb8900-729a-11eb-8129-423e7f4517a5.png)

In the Shared.Proto netstandard2.1 project file the grpc tool line is:
`<Protobuf Include="Protos\author.proto" GrpcServices="Both" />`
It generates the GrpcAuthor.cs which has the `GetAuthorAsync` method what is called from uno shared project.

**Comment by jeromelaban** [comment]
Thanks for the report. This looks like a external issue to Uno in the .NET Linker.

We'll probably need to report this to the .NET team, but you;ll need to provide a repro sample for this issue to move forward.

**Comment by Dimigergo** [comment]
Thanks for the reply! I have made a small solution, where you can see the wasm project has the linker error.
And if you commented the Shared project CMainViewModel.cs line 69 the build will be succesfull.

[wasm_linker_bug.zip](https://github.com/unoplatform/uno/files/6021891/wasm_linker_bug.zip)

**Comment by jeromelaban** [comment]
Thanks for the repro. This seems like in internal dependency in the logging packages and it can be fixed by adding this dependency:

```
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
```

Note that we're moving Uno to use later versions of the logging framework in #4767.

**Comment by Dimigergo** [comment]
Thanks for the workaround, it is perfect solution!
