### ISSUE TITLE
EventHandler Leak: System.AssemblyLoadEventHandler . += Uno.Xaml.XamlSchemaContext

### ISSUE THREAD

**Issue by calvinhsia** [unoplatform/uno#5284]
Hi,

I'm on the Visual Studio Perf & Rel team and I've noticed from analyzing a few customer low memory dumps that there appears to be a leak.

System.AssemblyLoadEventHandler . += Uno.Xaml.XamlSchemaContext

The Avg # of XamlSchemaContext eventhandlers subscribed to AssemblyLoadEventHandler is 21,814, with a max of 129,504

Internal Microsoft bug 
Bug 1281062: EventHandler Leak: System.AssemblyLoadEventHandler . += Uno.Xaml.XamlSchemaContext

see also https://github.com/calvinhsia/PerfGraphVSIX/blob/master/PerfGraphVSIX/CodeSamples/LeakDemos/LeakyEvent.cs

**Comment by jeromelaban** [comment]
@calvinhsia Thanks very much for the report and troubleshooting, we'll look into it!

**Comment by jeromelaban** [comment]
@calvinhsia this is an interesting issue, while the fix is an easy one, the fact that you've noticed this as part of devenv is more troubling, as it is supposed to run out-of-proc. Was it actually inside devenv.exe ? 

If this is the case, and by any chance, would you still have the images details (e.g. informational version of the Uno.Xaml assembly)? That would be of great help!

Thanks again :)

**Comment by calvinhsia** [comment]
Hi Jerome, yes, I found this issue in Devenv.exe.
Do you still need more details? like getting the asm version? I noticed you closed this issue...

**Comment by jeromelaban** [comment]
@calvinhsia Yes I closed the issue as we pushed an update to our dev channel.

If you've seen this in devenv.exe, then there's definitely something that does not fit. If you can get the assembly versions it'll help troubleshooting this further.

Thanks a lot!

**Comment by calvinhsia** [comment]
`44240000 44274000   Uno_Xaml   (deferred)             
    Image path: C:\Users\RoverCoder\AppData\Local\Temp\VS\AnalyzerAssemblyLoader\7aa5e68dac454f968bcfb5aacbb2885e\8\Uno.Xaml.dll
    Image name: Uno.Xaml.dll
    Browse all global symbols  functions  data
    Using CLR debugging support for all symbols
    Has CLR image header, track-debug-data flag not set
    Image was built with /Brepro flag.
    Timestamp:        FB6AFC19 (This is a reproducible build file hash, not a timestamp)
    CheckSum:         00031ACB
    ImageSize:        00034000
    File version:     255.255.255.255
    Product version:  0.0.0.0
    File flags:       0 (Mask 3F)
    File OS:          4 Unknown Win32
    File type:        2.0 Dll
    File date:        00000000.00000000
    Translations:     0000.04b0
    Information from resource tables:
        CompanyName:      Uno.Xaml
        ProductName:      Uno.Xaml (netstandard2.0 )
        InternalName:     Uno.Xaml.dll
        OriginalFilename: Uno.Xaml.dll
        ProductVersion:   3.4.0+Branch.release-stable-3.4.Sha.1c38eefd2c555a028e0f5803cc5a053fdab4490d.1c38eefd2c555a028e0f5803cc5a053fdab4490d
        FileVersion:      255.255.255.255
        FileDescription:  Uno.Xaml
        LegalCopyright:   nventive
`

**Comment by calvinhsia** [comment]
![image](https://user-images.githubusercontent.com/15060143/108765193-591a0e00-7508-11eb-9cdf-9e3842ca16f1.png)

**Comment by calvinhsia** [comment]
![image](https://user-images.githubusercontent.com/15060143/108765414-97173200-7508-11eb-99cb-a7aa795cc6ba.png)

**Comment by jeromelaban** [comment]
Thanks a lot!

**Comment by calvinhsia** [comment]
are you saying that the uno.xaml.dll assembly that is loaded in the VS devenv process should not be loaded at all? 
Fixing that would certainly remove the leak from devenv.exe.

**Comment by jeromelaban** [comment]
Yes, the assembly should always be loaded in a separate process (`Uno.SourceGeneration.Host.exe`). The only case that comes to mind would be when the Android tooling is used (in line with this issue): https://github.com/dotnet/project-system/issues/4494. 

In some unknown conditions, the Android tooling will still be executed in-proc, maybe that's the key.

**Comment by davkean** [comment]
Android builds are on legacy project system, which still does in-proc builds.
