### ISSUE TITLE
Cannot derive from sealed type Window

### ISSUE THREAD

**Issue by vadd98** [unoplatform/uno#5286]
## Current behavior

I'm developing a WinUI 3 project. I have a window in a xaml, which is the main window of the project. On Windows I have no problem, by the way on MacOS I get the error "Cannot derive from sealed type Window".

## Expected behavior

Being able to derive from Window.

## How to reproduce it (as minimally and precisely as possible)

Create a window xaml and try to build.

## Workaround

Nothing.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.5

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [x] Visual Studio for Mac (version: 8.8.3 )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

At of Uno 3.5, the `Window` class is not the same as the one found in WinUI 3.0, and cannot be used directly in XAML.

You can refer to the unoapp-winui sample for an example application that does not rely on `Window` in XAML.

**Comment by vadd98** [comment]
Thanks for your suggestion. 
By the way, is it possible to know if this feature will be implemented in next versions? 
Actually my app is particular relying on the Window xaml, so I'd like to know if I can just wait for next Uno versions or if I have to rewrite the logic referring to the unoapp-winui sample

**Comment by jeromelaban** [comment]
We will implement the missing APIs in future release, to align with the WinUI windowing contract.

**Comment by MartinZikmund** [comment]
This is done now
