### ISSUE TITLE
[Calculator][WASM] All Converter options are not opening.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5293]
## Current behavior

https://user-images.githubusercontent.com/74563602/108648890-3cd78c00-748a-11eb-95cd-d7c9bfa8855b.mp4

## Expected behavior
![Converter issue](https://user-images.githubusercontent.com/74563602/108648866-321cf700-748a-11eb-91cc-69990ef7e14d.png)

## How to reproduce it (as minimally and precisely as possible)

Open Chrome on Android device.
Visit https://calculatorcanary.z27.web.core.windows.net/
Click Burger menu.
Click any option from the "Converter" calculator for example (Length, Area, Speed)
Notice that any of the "Converter" options is not opening.

Environment
Nuget Package:

Package Version(s):

Affected platform(s):
 WebAssembly

**Comment by jeromelaban** [comment]
Fixed in today's canary.

**Comment by sakshi173** [comment]
Verified, Issue is fixed for the below canary build.
https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=26384&view=results
![calc wasm correct](https://user-images.githubusercontent.com/74563602/112055322-13635c00-8b2d-11eb-8962-978ea795de89.png)
