### ISSUE TITLE
TreeView is marked as not implemented

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#5295]
[Here ](https://platform.uno/docs/articles/implemented-views.html)it says TreeView would not be supported.
[Here ](https://platform.uno/blog/uno-platform-3-1-released-linux-new-winui-controls-prism-8-0-and-more/)it says TreeView is released.

Which is one right? Thanks

**Comment by jeromelaban** [comment]
There are two APIs for `TreeView`, one in `Windows.UI.Xaml.Controls.TreeView` and another one in `Microsoft.UI.Xaml.Controls.TreeView`. We implemented the latter, and uses the source from WinUI 2.5.

**Comment by DierkDroth** [comment]
Thanks @jeromelaban. It might help if [this page](https://platform.uno/docs/articles/implemented-views.html) would be amended accordingly
