### ISSUE TITLE
inconsistency on NavigationView being open or closed between platforms

### ISSUE THREAD

**Issue by JuggernOtt81** [unoplatform/uno#5312]
## Current behavior

NavigationView is not consistent between platforms.
even with `<NavigationView IsPaneOpen="False"/>` in UWP and wasm it's the opposite of iOS and Droid.
on debug build, uwp and wasm default is closed, but when given the False property, it's open.
on iOS and Droid, it's open by default and is only closed when given the False property. 

## Expected behavior

default i think should be closed across platforms, but surely it should be consistent when explicitly telling it to be not open.

## How to reproduce it (as minimally and precisely as possible)

```xml
<Page
    x:Class="Stripper.Uno.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Stripper.Uno"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid>
        <NavigationView IsPaneOpen="False"/>
        <StackPanel Padding="50">
            <TextBlock Text="Hello, World!" Margin="20" FontSize="30" HorizontalAlignment="Center"/>
            <Button HorizontalAlignment="Center">
                <Button.Content>
                    Let's GO!
                </Button.Content>
            </Button>
        </StackPanel>
    </Grid>
</Page>
```

## Workaround

unknown

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [x] Other: i have all available projects in this solution

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [x] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x ] Windows
- [ ] Build tasks
- [ ] Solution Templates

maybe more? i don't have all these to test on.

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.6)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

![mismatch uno](https://user-images.githubusercontent.com/34386218/108950386-279e6100-7634-11eb-876e-de2639c1aba8.png)

**Comment by jeromelaban** [comment]
Thanks for the report.

Could you validate if the issue also exists when using the `Microsoft.UI.Xaml.Controls.NavigationView` version of the control ?

We will not be updating this control in the long run (same as Microsoft) as the newer version gets all the newer features.
