### ISSUE TITLE
Document Uno.Material

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#5334]
Should include:
 - feature entry for Uno.Material
 - how-to for integrating Uno.Material into an app
 - small sample app using Uno.Material (eg single-page app with Material-styled controls)

The documentation content can largely be taken from the [Uno.Themes readme](https://github.com/unoplatform/Uno.Themes/blob/master/README.md) and incorporated into the Uno docs site. 

The sample app should go in Uno.Samples.

**Comment by MartinZikmund** [comment]
@Xiaoy312 I guess this can be closed now?
