### ISSUE TITLE
[ListView] SelectedItem property gets updated after SelectionChanged fires

### ISSUE THREAD

**Issue by pdecostervgls** [unoplatform/uno#534]
## I'm submitting a...

- Bug report (I searched for similar issues and did not find one) 
 

## Current behavior
When an item gets selected in a ListView, the system first triggers the SelectionChanged events and then updates the SelectedItem property.

## Expected behavior
The SelectedItem property would be updated before the SelectionChanged event fires. Like the UWP head does.

## Minimal reproduction of the problem with instructions
Repro project @ https://github.com/pdecostervgls/Uno-SelectionChangedRepro

## Environment

```
Nuget Package: 
Uno.UI : 1.43.0-dev.714

Affected platform(s):
- [x] iOS
- [x] Android
- [?] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: 15.9.5)
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by peternary** [comment]
This does not appear to be an issue currently, but I ran into the same problem with SelectedValue

**Comment by peternary** [comment]
Confirmed resolved for SelectedValue
