### ISSUE TITLE
ImageSource.ImageSource()' is inaccessible due to its protection level in Uno.WinUI

### ISSUE THREAD

**Issue by vadd98** [unoplatform/uno#5340]
## Current behavior

I have a Theme.xaml in which I defined the default settings for light theme and dark theme. I have some ImageSource in it because I need to change some images in the app on the theme change. On Windows it works flawlessly, but on Mac I get the error: 'ImageSource.ImageSource()' is inaccessible due to its protection level (CS0122).

## Expected behavior

Being able to put ImageSource in xaml.

## How to reproduce it (as minimally and precisely as possible)

1) Create a <ResourceDictionary.ThemeDictionaries> 
2) Put an ImageSource in it
3) Try to build

## Workaround

None

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): Uno.WinUI 3.5

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [x] Visual Studio for Mac (version: 8.8.10)
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment]
@vadd98 Can you please check with the latest dev version (currently 3.11.0-dev.130)?

If this is still an issue, can you provide a repro? Thanks!

**Comment by Youssef1313** [comment]
@vadd98 Can you re-check please?

**Comment by francoistanguay** [comment]
@ebariche  Wouldnt that be fixed by the breaking changes in 4.0?

**Comment by Youssef1313** [comment]
@francoistanguay I don't think it's related. The constructor in UWP is not public. The thing is that XAML generation should not try to instantiate `ImageSource`.

**Comment by francoistanguay** [comment]
Ok but then is it fixed by the linked PR above or it's still an issue?

**Comment by Youssef1313** [comment]
@francoistanguay I think it's fixed. I tried to reproduce with this `App.xaml`:

```xml
<Application
    x:Class="TestImgSrc.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TestImgSrc">
	
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
            </ResourceDictionary.MergedDictionaries>

            <ResourceDictionary.ThemeDictionaries>
                <ResourceDictionary x:Key="Default">
                    <ImageSource x:Key="MyImgSrc">Hello/Hi.jpg</ImageSource>
                </ResourceDictionary>
            </ResourceDictionary.ThemeDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>

```

The related part of the generated code is:

```csharp
			// ThemeDictionaries
			Resources.ThemeDictionaries["Default"] = 
			new global::Uno.UI.Xaml.WeakResourceInitializer(this, __ResourceOwner_2 => 
				new global::Windows.UI.Xaml.ResourceDictionary
				{
					[
					"MyImgSrc"
					] = 
					"Hello/Hi.jpg"/* Windows.UI.Xaml.Media.ImageSource/Windows.UI.Xaml.Media.ImageSource, Hello/Hi.jpg, /_UnknownContent */					,
				}
			)
			;
```

We no longer try to access the `ImageSource` constructor.

**Comment by jeromelaban** [comment]
Thanks for the validation @Youssef1313 !
