### ISSUE TITLE
Svg images don't load on Uno.WinUI on MacOS

### ISSUE THREAD

**Issue by vadd98** [unoplatform/uno#5350]
## Current behavior

If i put an <Image> in a xaml on MacOS and I set a svg as source it loads empty. If I convert the svg to png and set the png as source, it loads correctly.

## Expected behavior

Being able to load an svg image.

## How to reproduce it (as minimally and precisely as possible)

1) Insert an <Image> in a xaml
2) Set a svg as source

## Workaround

Use png. By the way using png creates problem with scaling.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): Uno.WinUI 3.5.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [x] Visual Studio for Mac (version: 8.8.3)
- [ ] Rider Windows (version: )
- [x] Rider macOS (version: 2020.3)
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
SVGs are not yet supported on both iOS and macOS, see #1982. I'll close this issue in favor of the other.
