### ISSUE TITLE
[Gallery][Android/iOS] DatePicker- Default year to choose date from calendar is 1921.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5363]
## Current behavior
![datepicker android](https://user-images.githubusercontent.com/74563602/109560736-3d83aa00-7aaa-11eb-85a9-f2296b2b372d.png)

## Expected behavior

![datepicker correct](https://user-images.githubusercontent.com/74563602/109560753-42485e00-7aaa-11eb-8be1-200e45249091.png)

## How to reproduce it (as minimally and precisely as possible)
1. Open Uno Gallery APP 
2. Click Burger Menu on the left top right.
3. Click "DatePicker" from the "Component" list.
4. Click on the "Day" in the Default section."
5. Observe that the default calendar open of 1921 instead of 2021.

Version(s):
Version 1.4.3 (400738)
Mar 01, 2021 at 11:21

Device:
Samsung S8 - 8.0
Motorola g(7) – 9

Affected platform(s):
Android

**Comment by sakshi173** [comment]
Issue is fixed for Android, Verified for Samsung S8 - 8.0.
But the same issue is happening for **iOS (DatePicker-  Native)** 
Below is the screenshot.
![datpicker iOS](https://user-images.githubusercontent.com/74563602/111207044-8b66da80-859f-11eb-9a50-c6f88c0e015b.png)

Version
1.4.3(745)

**Comment by sakshi173** [comment]
Issue is still present for iOS, reopening the bug.

Verified on for the below build.


Version
1.4.3(747)

**Comment by sakshi173** [comment]
@kazo0 I revalidated this issue for the below build and it is fixed now.

Version 1.4.3 (749)

**Comment by jeromelaban** [comment]
Should we close ?

**Comment by sakshi173** [comment]
Yes

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by sakshi173** [comment]
Verified, Issue is fixed, closing

**Comment by sakshi173** [comment]
Verified, Issue is fixed, closing
