### ISSUE TITLE
Conditional WASM/Skia `xmlns` doesn't work inside of a library

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#5372]
Creating an issue on GitHub to track this issue

## Current behavior

Using conditional XAML with the `wasm:` or `skia:` prefix does not work when compiling inside of an Uno Library

## How to reproduce it (as minimally and precisely as possible)

1. Create a new Uno Library
2. Add the following code:

```xml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
					xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
					xmlns:wasm="http://uno.ui/wasm"
					xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
					xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
					mc:Ignorable="d wasm">
	<wasm:Style x:Key="MaterialToggleSwitchStyle"
				TargetType="ToggleSwitch">
                  ....
 	</wasm:Style>
</ResourceDictionary>
```

3. Notice that the Style is not created in the generated code

## Workaround

Use a Cross-Runtime Library?

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider macOS (version: )
- [ ] Rider Windows (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Xiaoy312** [comment]
But, possibly we could adjust the project to generate multiple `netstandard` packages? ala Uno.UI with Uno.UI.WebAssembly & Uno.UI.Skia
An other option could be to have runtime conditional xaml?: `xaml_uri_or_using_namespace?is_platform(platform0[,platform1...])`

**Comment by jeromelaban** [comment]
There's already support for this using Cross-Runtime libraries.

**Comment by baskren** [comment]
For reference: https://stackoverflow.com/questions/70994056/uno-platform-cross-platform-library-if-conditional-for-wasm

**Comment by jeromelaban** [comment]
This may actually change with `net8.0-browser`, we'll need to reevaluate at that time.

**Comment by MartinZikmund** [comment]
@jeromelaban Darsh is now doing https://github.com/unoplatform/Uno.Themes/issues/1298, what should we do for `wasm:` and `skia:` prefixes in the docs? Should we explicitly mention it works in cross-runtime libraries only? Plus, should we have a `crossruntime:` prefix?

**Comment by MartinZikmund** [comment]
The problem gets worse because if someone now uses `not_wasm` or `not_skia` in non cross-runtime library, it is evaluated to true, which is very confusing. Maybe we should make the compilation fail unless the library is cross-runtime library and `wasm` or `skia` prefixes are used OR we just make `wasm`==`skia`==`crossruntime` in non-cross runtime libraries

**Comment by jeromelaban** [comment]
@MartinZikmund this scenario is particularly broken now that `net8.0-browser` is not slated to be included in .NET. Failing the compilation is likely to be an important breaking change.

At this time, the easiest way to handle this particular scenario is to make custom user controls that switch using runtime conditions (by detecting wasm), or to use state triggers to switch values.

The more complex way is to use cross-runtime libraries.

**Comment by MartinZikmund** [comment]
@jeromelaban I think this can now be closed with Uno.Sdk, correct?

**Comment by jeromelaban** [comment]
Indeed, we can close now.
