### ISSUE TITLE
ScrollBar isn't shown when pointer enters the ScrollBar area in Uno.WinUI on MacOS

### ISSUE THREAD

**Issue by vadd98** [unoplatform/uno#5373]
## Current behavior

I'm using Uno.WinUI on MacOS. I have a view with a ScrollViewer. I can scroll the content with the trackpad using the two fingers gesture with no problem. By the way, if I want to scroll the view holding and manipulating the ScrollBar using the mouse pointer, I can't because if I move the pointer in the ScrollBar area it doesn't show up.

## Expected behavior

Being able to move scroll without using gestures or mouse wheel.

## How to reproduce it (as minimally and precisely as possible)

1) Insert a ScrollViewer in a xaml
2) Try to scroll moving the pointer on the ScrollBar area, without using trackpad gestures or mouse wheel

## Workaround

None

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.5.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [x] Visual Studio for Mac (version: 8.8.3)
- [ ] Rider Windows (version: )
- [x] Rider macOS (version: 2020.3)
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This issue may be addressed by https://github.com/unoplatform/uno/pull/5322 (cc @dr1rrb)

**Comment by dr1rrb** [comment]
Hi @vadd98, I think that was using the "native" scrollbar, then it's a macOS behavior that you can configure in macOS settings => General => Show scroll bars => Always (https://stackoverflow.com/questions/51019237/replacing-or-modifying-scroll-bar-so-it-is-always-visible-on-macos)

But in https://github.com/unoplatform/uno/pull/5322 we replaced them by "managed" scroll bars which have the save behavior as WinUI / UWP (i.e. they appears when you move your mouse over the ScrollViewer's viewport). I'm closing this issue, feel free to re-open it if you still have an issue.
