### ISSUE TITLE
`MenuFlyout` doesn't work in Uno.WinUI on macOS

### ISSUE THREAD

**Issue by vadd98** [unoplatform/uno#5381]
## Current behavior

I added a MenuFlyout to a User-Control in a xaml, by the way when I launch the app on MacOS and I try to show it right-clicking on the User-Control nothing happens.

## Expected behavior

MenuFlyout has to be shown.

## How to reproduce it (as minimally and precisely as possible)

1) Add a MenuFlyout to a control in xaml
2) Try to show it in app

## Workaround

None.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): Uno.WinUI 3.5.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [x] Visual Studio for Mac (version: 8.8.3)
- [ ] Rider Windows (version: )
- [x] Rider macOS (version: 2020.3)
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
