### ISSUE TITLE
`AutoReverse` in animations doesn't work in Uno.WinUI on macOS

### ISSUE THREAD

**Issue by vadd98** [unoplatform/uno#5382]
## Current behavior

I'm using storyboards with the AutoReverse property set to true in order to make an ellipse enlarge and then come back to its original size. By the way, when the animation ends it doesn't reverse, instead it begins again.

## Expected behavior

Animations have to reverse their behaviour when AutoReverse property is set to true.

## How to reproduce it (as minimally and precisely as possible)

1) add a storyboard in xaml with the AutoReverse property set to true
2) start the animation

## Workaround

Control manually the reversing of the animation, reversing it step by step using keyframes.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): Uno.WinUI 3.5.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [x] Visual Studio for Mac (version: 8.8.3)
- [ ] Rider Windows (version: )
- [x] Rider macOS (version: 2020.3)
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Avid29** [comment]
Any progress? 

I'm currently looking to use AutoReverse in a control poised for toolkit labs: https://github.com/CommunityToolkit/Labs-Windows/pull/275, and I've had to alter it to restrict features on Uno.

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
