### ISSUE TITLE
Control is moved by animation when it begins in Uno.WinUI on macOS

### ISSUE THREAD

**Issue by vadd98** [unoplatform/uno#5383]
## Current behavior

When a Storyboard begins the animated control is automatically moved to another position. In particular, it is moved in the upper-left direction. 

## Expected behavior

The animated control has to stay in its original position when the Storyboard begins

## How to reproduce it (as minimally and precisely as possible)

1) animate a control using a Storyboard in xaml
2) start the Storyboard

## Workaround

None

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): Uno.WinUI 3.5.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [x] Visual Studio for Mac (version: 8.8.3)
- [ ] Rider Windows (version: )
- [x] Rider macOS (version: 2020.3)
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
