### ISSUE TITLE
NavigationView control is not as fluid as it should

### ISSUE THREAD

**Issue by Guidemarcus** [unoplatform/uno#5394]
## Current behavior

The application is not as responsive as it is on UWP. The NavigationView is slow and it is hard to interact with it.

## Expected behavior

Scrolling should be fluid, pressing a button inside a ItemsRepeater inside a NavigationView should not be hard to press.

## How to reproduce it (as minimally and precisely as possible)

The issue is really visible on Uno.Themes (https://github.com/unoplatform/Uno.Themes) on any Android device.

## Workaround

Simplify the view as much as possible. I tried it here in Uno.Themes (https://github.com/unoplatform/Uno.Themes/pull/513/commits/a6770e9a9da822698e2c2f0bb34cd361234c4b8e). iOS is much better, but Android is still hard to use.

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI: 3.6.0-dev.275

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.6)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Guidemarcus** [comment]
Uno.Themes has its own set of issues 
- https://github.com/unoplatform/Uno.Themes/issues/497
- https://github.com/unoplatform/Uno.Themes/issues/500

**Comment by Guidemarcus** [comment]
@davidjohnoliver as we discussed. I am not sure in which project you want this. I will let you decide.

**Comment by Guidemarcus** [comment]
Our QA team also reports that the performance issues were also spotted on Uno.Gallery, but not as bad as Uno.Themes

**Comment by davidjohnoliver** [comment]
> @davidjohnoliver as we discussed. I am not sure in which project you want this. I will let you decide.

Thanks @Guidemarcus ! The Uno repo is the right place for this issue. One key detail that's missing is which version of Uno.UI was tested?

**Comment by Guidemarcus** [comment]
Updated

**Comment by jeromelaban** [comment]
Can you try again with recent Uno dev builds, see if it helps ?

**Comment by francoistanguay** [comment]
@Guidemarcus  Can you please try again and close if you cannot repro with 3.6 or dev?

**Comment by robloo** [comment]
3.6.6 still seems slow to open the NavigationView and make a selection. The first load is the worst as could be expected; however, even subsequent opening of the menu lags, button press as well. I will try again after 3.8 is released.

**Comment by francoistanguay** [comment]
We`ve seen great perf improvements on NavView with current dev builds that will lead to 3.8 next week! Please give it a try once we release!

**Comment by robloo** [comment]
This is much better in 3.8.6.

The first load of the side pane (when in `LeftMinimal` PaneDisplayMode) still has a small delay; however, it is several times faster than before. It's not enough to be a concern anymore.

Subsequent loads of the side pane are perfectly smooth!

**Comment by jeromelaban** [comment]
Thanks for the update! Good to know performance updates had a positive impact !

**Comment by francoistanguay** [comment]
Closing for now with all the recent updates. Let us know if somehow it should be reopened with an actual repro.
