### ISSUE TITLE
Wasm System.DllNotFoundException: libc,  on var co =  new System.Net.CookieContainer();

### ISSUE THREAD

**Issue by iosub** [unoplatform/uno#540]
## I'm submitting a...

 Bug report (I searched for similar issues and did not find one) 
 

## Current behavior
with this code
var co =  new System.Net.CookieContainer();
 I get

System.DllNotFoundException: libc
mono.js:1   at (wrapper managed-to-native) System.Net.NetworkInformation.CommonUnixIPGlobalProperties.getdomainname(byte[],int)
mono.js:1   at System.Net.NetworkInformation.CommonUnixIPGlobalProperties.get_DomainName () [0x0000b] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mcs/class/System/System.Net.NetworkInformation/UnixIPGlobalProperties.cs:60 
mono.js:1   at System.Net.CookieContainer..ctor () [0x0003a] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mcs/class/referencesource/System/net/System/Net/cookiecontainer.cs:122 
mono.js:1   at App3.MainPage.Test_Click (System.Object sender, Windows.UI.Xaml.RoutedEventArgs e) [0x00013] in C:\MSP\uno\httpclient\App3\App3\App3.Shared\MainPage.xaml.cs:40 

## Environment

```
Nuget Package: 
Uno.UI 1.43.738
Uno.Wasm.Bootstramp 1.0.0.0.159
Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [X ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ X] 2017 (version: ) 15.9.6
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by jeromelaban** [comment]
This means that it is not implemented by mono at this time, this will take a runtime update.

**Comment by iosub** [comment]
Hi

var co = new System.Net.CookieContainer(); works on iOS and Android..

So is this just a lack of mono wasm support ?

**Comment by yowl** [comment]
As a workaround you can set cookies manually, e.g. `request.Headers.Add("Cookie", authToken);`

**Comment by iosub** [comment]
Sorry for the question if is to simple but I'm new in this ..

How /where do you implement your workaround for this code ?

var co = new System.Net.CookieContainer(); 

Thank you

**Comment by yowl** [comment]
Something like
```
        protected async Task<TResult> ExecuteRestJsonGet<TResult>(string requestUri, string authToken)
        {
            HttpResponseMessage response;
            var httpClient = ServiceHttpClientFactory.Instance.HttpClient;
            string content = "";

            httpClient.DefaultRequestHeaders.Accept.Clear();
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            using (var requestMessage = new HttpRequestMessage(HttpMethod.Get, requestUri))
            {
                if (!string.IsNullOrWhiteSpace(AuthToken))
                {
                    httpClient.DefaultRequestHeaders.Add("Cookie", authToken);
                }
                response = await httpClient.SendAsync(requestMessage);
```

**Comment by ramezgerges** [comment]
This doesn't reproduce for me.
