### ISSUE TITLE
WASM: Two way x:Bind on textbox not working on iOS Safary

### ISSUE THREAD

**Issue by Mohsens22** [unoplatform/uno#5402]
## Current behavior

If you create a textbox, apply a two way x:Bind and open it from Safari iOS, you'll notice that when changing textbox content, it won't effect the ViewModel property.

## How to reproduce it (as minimally and precisely as possible)

Example? Sure.
```xaml
<TextBox VerticalAlignment="Center" x:Name="millisec"  HorizontalAlignment="Right" MinWidth="90"
                         Text="{x:Bind ViewModel.Quantum,Mode=TwoWay}" InputScope="Number" PlaceholderText="1s-4s"/>
```
```c#
        //using ReactiveUI;
        //using ReactiveUI.Fody.Helpers;
        [Reactive]
        public int Quantum { get; set; }
```

## Environment

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Bootstrap: V2.0 Latest Dev
Uno.UI: 3.5 Stable
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: Latest)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. 

Could you try to reproduce the behavior in a sample application, so we're sure to track the same issue ?
