### ISSUE TITLE
`Slider` in Droid only allows negative values if the Minimum property is set to a negative value

### ISSUE THREAD

**Issue by jasonxz** [unoplatform/uno#5403]
## Current behavior

When setting the Minimum property of a Slider to a negative number, the Maximum is automatically set to 0.

## Expected behavior

Setting the Minimum should not affect the Maximum as long as the Minimum is less than or equal to the set Maximum.

## How to reproduce it (as minimally and precisely as possible)

The following XAML will produce a Slider with Minimum of -500 and a Maximum of 0 (even though Maximum is explicitly set to 500).
`<Slider Margin="4,0" Maximum="500" Minimum="-500"/>`
[Carousel.zip](https://github.com/unoplatform/uno/files/6094736/Carousel.zip)

## Workaround

If you set Minimum **before** Maximum, this works correctly:
`<Slider Margin="4,0" Minimum="-500" Maximum="500"/>`

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.6)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
This seems to be working correctly now
