### ISSUE TITLE
`Unloaded` event in `ContentDialog` is fired when the `ContentDialog` is opened in Uno.WinUI on MacOS

### ISSUE THREAD

**Issue by vadd98** [unoplatform/uno#5404]
## Current behavior

When I show a ContentDialog on MacOS, the Unloaded event is fired as soon as the ContentDialog is showed. I underline that even though the Unloaded event is fired the ContentDialogs remains visible.

## Expected behavior

Unloaded event has to be fired only when the ContentDialog is hidden.

## How to reproduce it (as minimally and precisely as possible)

1) Create a ContentDialog containing a subscription to the Unloaded event
2) Show the ContentDialog

## Workaround

None

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.5.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [x] Visual Studio for Mac (version: 8.8.3)
- [ ] Rider Windows (version: )
- [x] Rider macOS (version: 2020.3)
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This issue is likely to be related to https://github.com/unoplatform/uno/issues/2895

**Comment by Youssef1313** [comment]
I can't reproduce in Skia. Maybe it's macOS specific?
