### ISSUE TITLE
x:Bind Working for UWP but not WASM, Droid, etc

### ISSUE THREAD

**Issue by NBull92** [unoplatform/uno#5414]
## Current behavior

I've currently run into an issue where I usually assign a region to a ContentControl, by calling the region name by a static that is stored within a class of static region names.

My WPF XAML code, from Shell.xaml:

    <ContentControl Grid.Row="0" 
                    VerticalAlignment="Bottom" 
                    HorizontalAlignment="Stretch" 
                    Margin="0,0,0,11" 
                    prismRegions:RegionManager.RegionName="{x:Static blankCore:RegionNames.VehicleHeaderRegion}"/>

However, this does not work, due to x:Static not existing in UWP (Unknown type 'Static' in XML namespace). Therefore, after looking at some documentation on UWP, I have used x:Bind and now the code looks like this:

    <ContentControl Grid.Row="0" 
                    VerticalAlignment="Bottom" 
                    HorizontalAlignment="Stretch" 
                    Margin="0,0,0,11" 
                    prismRegions:RegionManager.RegionName="{x:Bind blankCore:RegionNames.VehicleHeaderRegion}"/>

This is compiling and running for UWP, but upon switching to WASM or Android, I get various errors in a generated file:

    c32.SetBinding(global::Prism.Regions.RegionManager.RegionNameProperty, new Windows.UI.Xaml.Data.Binding{ Mode = BindingMode.OneTime }.Apply(___b =>  /*defaultBindModeOneTime*/ global::Uno.UI.Xaml.BindingHelper.SetBindingXBindProvider(___b, this, ___ctx => ___ctx is global::BlankApp1.Shared.Views.Shell ___tctx ? (object)(___tctx.global::BlankApp1.Core.RegionNames.AuthenticateRegion) : null, null )));

The error is as follows:
![6wkKR](https://user-images.githubusercontent.com/8153150/110306344-a1035f80-7ff5-11eb-8852-704e1b81d20b.png)

My current static class of RegionNames is as follows:

    namespace BlankApp1.Core
    {
        public class RegionNames
        {
            public static string VehicleListRegion= "VehicleListRegion";
            public static string AuthenticateRegion = "AuthenticateRegion";
            public static string VehicleHeaderRegion = "VehicleHeaderRegion";

            /// ...
        }
    }

## Expected behavior

- Create a new blank app, using the Prism Template.
- Create a new class called RegionNames
- Add in the statis strings, shown above.
- In the Shell.xaml, add the code ContentControl code snippet above, that uses x:Bind
- Build for UWP and see it load without issue
- Build for another platform, I used WASM and Android. 
- See errors load in the genereat shell file code.

## How to reproduce it (as minimally and precisely as possible)

If you follow the steps above in teh screenshots, you'll get the error.

## Workaround

Currently there does not appear to be a workaround.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
I had originally  added this to stack a couple of months ago: https://stackoverflow.com/questions/65656969/replacement-for-xbind-working-for-uwp-in-uno-platform-but-not-wasm-droid-etc. Aplogies I completely forgot to add this issue then as requested.

I've only used UWP, WASM and Android, as I don't have the ability to test the other platforms

**Comment by jeromelaban** [comment]
Thanks for the report. If you can create a repro case with a sample app, it'll be most helpful. We've tried to create one for a similar case, without much success.  Thanks!

**Comment by NBull92** [comment]
Hi @jeromelaban I've uploaded my test project for this to google drive. Please find it at this link: https://drive.google.com/file/d/1_bXvJ83UOyhMvOjfp76x53a3A9S6iahD/view?usp=sharing

**Comment by jeromelaban** [comment]
Thanks! This issue was fixed a while back, and you only need to update to a more recent build of the Uno.UI packages (3.5.x will do fine).

**Comment by NBull92** [comment]
Superstar. Thank you :)

**Comment by sasakrsmanovic** [comment]
@NBull92 We are curious what you are building and/or if we could feature it. Your GitHub profile says you are currently working on ImprezGarage. Are you taking ImprezGarage cross-platform with Uno?

**Comment by NBull92** [comment]
@sasakrsmanovic. Indeed that is the one I am working on. As it's a side project for me, I am not sure how long it'll take me. But it is my 2021 goal to do it :) You can happily feature it, that's for sure.
