### ISSUE TITLE
Wasm head not appearing. 

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#5432]
1. 
![image](https://user-images.githubusercontent.com/43340959/110642965-d9e93300-81b3-11eb-89df-0753d18cdd8e.png)

2.
![image](https://user-images.githubusercontent.com/43340959/110643014-e9687c00-81b3-11eb-8276-693d75b12235.png)

3.
![image](https://user-images.githubusercontent.com/43340959/110643087-00a76980-81b4-11eb-8dc0-7fe6b3cf4059.png)

I select the Wasm head but it is not appearing in the solution. 

![image](https://user-images.githubusercontent.com/43340959/110643212-23398280-81b4-11eb-8700-b893d806a8dc.png)

**Comment by jeromelaban** [comment]
Thanks for the report. Try using the [vsix installation instead](https://platform.uno/docs/articles/get-started-vs.html#installing-the-uno-platform-solution-templates-with-visual-studio), as the support for dotnet new templates in visual studio is not yet fully supported.

**Comment by sigmarsson** [comment]
![image](https://user-images.githubusercontent.com/43340959/110645638-70b6ef00-81b6-11eb-9592-3d6a94cf964b.png)

Have both.

**Comment by jeromelaban** [comment]
I see, try using another template then, don't use the "Cross-platform app (WinUI)" one for now.

**Comment by sigmarsson** [comment]
![Uploading image.png…]()

**Comment by jeromelaban** [comment]
Thanks. This looks like a specific issue to your setup, try creating a project using `dotnet new unoapp` using the command line instead for now.

**Comment by jeromelaban** [comment]
You can also remove the `dotnet new` templates altogether using this:

```
dotnet new -u Uno.ProjectTemplates.Dotnet
```

**Comment by sigmarsson** [comment]
Cool. Reinstalled the temps and became okay. Merci.
