### ISSUE TITLE
CornerRadius doesn't behave the same as UWP when very large

### ISSUE THREAD

**Issue by jeanplevesque** [unoplatform/uno#5440]
## Current behavior

iOS & Android:
![image](https://user-images.githubusercontent.com/39710855/110697054-d193f680-81b9-11eb-8263-cbb9ba3204cd.png)

## Expected behavior

UWP:
![image](https://user-images.githubusercontent.com/39710855/110696652-5599ae80-81b9-11eb-9b66-ea093aa9f96e.png)

## How to reproduce it (as minimally and precisely as possible)

```xml
<Border CornerRadius="128"
	Width="128"
	Height="64"
	Background="Black" />
```

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): **3.5.1**

Affected platform(s):

- [x] iOS
- [x] Android

The following were not tested.

- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.6)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

This strategy of making elliptic borders is useful for scale up animations because the Border draws better.
A scaled up Ellipse becomes pixelated and a scaled up Border doesn't become pixelated.

**Comment by mikernet** [comment]
`3.6.0-dev` also developed a worse regression at some point after 3.5.1, at least on iOS where I am currently testing - if you do something like:

```xml
<Border Margin="20" 
        CornerRadius="9999"
	Width="128"
	Height="64"
	Background="Black" />
```

The shape starts to do very odd things like adding a wide shape on top of the circle that spans across the page.

**Comment by agneszitte-nventive** [comment]
Same issue on Skia

**Comment by kazo0** [comment]
I'm not sure if this was ever working but I might have broken things from these commits where I was playing around with the inner radius of the border:

https://github.com/unoplatform/uno/commit/81654c156f42c1048fb17dbb7bb6d621a87cd3ae
https://github.com/unoplatform/uno/commit/f5bdc415c40c03ab9e8c0c872cb7154ac7cabb49

**Comment by agneszitte-nventive** [comment]
> I'm not sure if this was ever working but I might have broken things from these commits where I was playing around with the inner radius of the border:
> 
> [81654c1](https://github.com/unoplatform/uno/commit/81654c156f42c1048fb17dbb7bb6d621a87cd3ae) [f5bdc41](https://github.com/unoplatform/uno/commit/f5bdc415c40c03ab9e8c0c872cb7154ac7cabb49)

Thanks @kazo0 I will take a look at the commits

**Comment by Youssef1313** [comment]
I'm looking into a fix for Wasm

**Comment by Youssef1313** [comment]
Wasm is working correctly now in #9958.

To add some information, this issue happens when CornerRadius is greater than Width/2 or greater than Height/2

Basically, the clipping works as follows:

![image](https://user-images.githubusercontent.com/31348972/192154035-d71ef9f0-97b5-4bab-a7a6-e8e8c2f04942.png)

This elliptic clipping turns into circular only if `CornerRadius < HalfWidth && CornerRadius < HalfHeight`

**Comment by MartinZikmund** [comment]
Closing this in favor of #10263. This is already supported on Skia correctly, but the same approach needs to be added to other targets as well
