### ISSUE TITLE
Build and deploy to macOS with remote login (like iOS)

### ISSUE THREAD

**Issue by manfromarce** [unoplatform/uno#5443]
## What would you like to be added:

This is probably related to Visual Studio but it would be great if we could build and deploy macOS applications from Visual Studio for Windows using remote login like Xamarin.iOS does.

## Why is this needed:

This would make cross-platform desktop app development a lot easier because Visual Studio for Mac doesn't support UWP either, so we have to use both of them.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report. This is not an Uno specific issue but rather a .NET issue, and it may be addressed to be addressed when going .NET 6 with Catalyst.
