### ISSUE TITLE
[WASM] DatePicker does not work

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#5448]
## Current behavior

Clicking the `DatePicker` does not pop anything up.

## Expected behavior

Date selection should be shown.

## How to reproduce it (as minimally and precisely as possible)

Just add a DatePicker anywhere to a WASM project: https://playground.platform.uno/#c07a7e1b

## Workaround

None.

## Environment

Chrome/Edge/Firefox latest.

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.5.0, 3.5.0-dev.385, 3.5.1, whatever version Uno Playground uses.

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report. Can you also specify which version of Uno you tested with ?

**Comment by mikernet** [comment]
Ah...updated to latest dev and it seems to be working.
