### ISSUE TITLE
[VS 2019 Mac] Missing project types

### ISSUE THREAD

**Issue by ericleroy01** [unoplatform/uno#5451]
## Current behavior
Uno projects type are only displayed under "Web and Console App" section and duplicated

![Capture d’écran 2021-03-12 à 08 40 50](https://user-images.githubusercontent.com/15108986/110910660-f307f600-8311-11eb-84a2-965d65c44110.png)

## Expected behavior
1. Should not be duplicated
2. Missing iOS, Android, etc...dedicated project template

## How to reproduce it (as minimally and precisely as possible)
1. Xcode 12.4 fresh install
2. VS 2019 Mac 8.9.1 fresh install
3. install Uno Template by using <i>dotnet new -i Uno.ProjectTemplates.Dotnet</i> command
1. Start VS 2019 Mac
2. Open New Solution Window

## Workaround
use <i>dotnet new unoapp -o ProjectName</i> command

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [x] Windows
- [ ] Build tasks
- [x] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [x] Visual Studio for Mac (version: 8.9.1)
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
I tried to uninstall/reinstall uno templates => does not work

**Comment by MartinZikmund** [comment]
@jeromelaban I think this is no longer relevant and can be closed
