### ISSUE TITLE
[Android][WebView] Videos inside webviews can't be watched. Only audio is available.

### ISSUE THREAD

**Issue by fperreaultnv** [unoplatform/uno#546]
## I'm submitting a...
Bug report

## Current behavior
[Android][WebView] Videos inside webviews can't be watched. Only audio is available.

## Expected behavior
Videos inside webviews should play, with video and sound.

## Minimal reproduction of the problem with instructions
1. Start a fresh Android app project. Make sure you have hardwareAccelerate="true" in the manifest, or in the ApplicationAttribute.
2. Have a WebView, and set the source to your favorite youtube video page.
3. When the web page load, click play.
4. Notice the sound plays, but the video does not.

## Environment
Nuget Package: Uno.UI

Package Version(s):  v1.42.0

Affected platform(s):
- [ ] iOS
- [x ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

**Comment by davidjohnoliver** [comment]
Possibly same cause as #851 (hardware acceleration disabled by Uno)

**Comment by carldebilly** [comment]
This bug has been fixed by PR #3392 the fix should be available in Uno.UI v3.0.0-dev.605
