### ISSUE TITLE
Trouble getting rid of build errors and warnings in template

### ISSUE THREAD

**Issue by Luk164** [unoplatform/uno#5468]
## Current behavior

The following screenshot shows the errors and warnings:
![image](https://user-images.githubusercontent.com/30559213/111157934-c2d18900-8597-11eb-80b8-e12f53e74a17.png)

I have tried the common rebuilding/restarting VS outlined in common issue. This removed a few of the errors/warnings, but the ones in the screenshot stayed.

## Expected behavior

Creating a fresh project shows no errors or warnings. (Note: The workaround of building and restarting VS is not a big deal)

## How to reproduce it (as minimally and precisely as possible)

Create a fresh template and build.

## Workaround

None. While the other projects build and launch successfully, the ones mentioned do not build at all. Unloading them hides the issue of course, but it also means I lose that particular platform.

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [X] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
- Uno.Core 2.2.0
- WASM.Bootstrap 1.3.4
- UniversalImageLoader 1.9.33
- 3.5.1 for the others
- Exactly as in template except for cote. Updating Core removed some warnings

Affected platform(s):

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [X] Skia
  - [ ] WPF
  - [X] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [X] Build tasks
- [X] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.9.1)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [X] Resharper (version: 2020.3.3) Note: I manually excluded all files that were showing any warnings/errors

## Anything else we need to know?

I am new to this platform so there is a chance I made some sort of rookie mistake.

**Comment by jeromelaban** [comment]
Thanks for the report!

Would you have changed the project name after creating it ? Also, can you try adding this to your Skia project :

```
<PropertyGroup>
   <UnoUIUseRoslynSourceGenerators>false</UnoUIUseRoslynSourceGenerators>
</PropertyGroup>
```

For the other errors, the Skia.View warning is expected, as for the other one [see this](https://platform.uno/docs/articles/get-started-wizard.html#initializecomponent-or-xname-variable-is-not-available-in-code-behind).

**Comment by Luk164** [comment]
@jeromelaban Ok, that seems to have helper. This is what I am getting now and everything builds pretty well, though I have no way of testing IOS or MAC. Screenshot:
![image](https://user-images.githubusercontent.com/30559213/111197612-f673d980-85be-11eb-997d-9e224d0722ec.png)

**Comment by Luk164** [comment]
@jeromelaban Update, after a rebuild the errors have started popping back up together with the new ones, which is a bit weird. Cleaning solution had no effect.

**Comment by Luk164** [comment]
My bad, was writing an update and accidentally closed the issue. The update turned out to be a bug in VS
