### ISSUE TITLE
The WebAssembly Threading not works as expected

### ISSUE THREAD

**Issue by mnikonov** [unoplatform/uno#5469]
## Current behavior

I have tried to update [WasmThreading](https://github.com/jeromelaban/Wasm.Samples/tree/master/Threading/WasmThreading) example to the latest dev version of Bootstrap

```xml
<PackageReference Include="Uno.Wasm.Bootstrap" Version="2.0.0-dev.167" />
<PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="2.0.0-dev.167" PrivateAssets="all" />
```

after that console log start showing incorrect Thread id order sequence

﻿[tid:1] Startup
[tid:1] Waiting for completion source
[tid:2] Thread begin
[tid:2] Got task result, raising event
[tid:2] Main thread exiting
[tid:2] Waiting for event
[tid:2] Got event, terminating thread 

## Expected behavior

Same as was described in blog [article](https://platform.uno/blog/webassembly-threading-in-net/)

[tid:1] Startup
[tid:1] Waiting for completion source
[tid:2] Thread begin
[tid:2] Waiting for event
[tid:1] Got task result, raising event
[tid:1] Main thread exiting
[tid:2] Got event, terminating thread 

## Workaround

I'm not sure for 100% but seems that this issue appeared after 1.3.0 bootstrapper version. So, workaround for threading is to use versions of bootstrap <= 1.3.0

## Environment

Nuget Package:

- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [x] Uno.Wasm.Bootstrap / Uno.Wasm.Bootstrap.DevServer

Nuget Package Version(s):

- Uno.Wasm.Bootstrap 2.0.0-dev.167
- Uno.Wasm.Bootstrap.DevServer 2.0.0-dev.167

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (16.10.0)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [x] Resharper (2020.3)

## Anything else we need to know?

In my next project this issue has completely different behaviour. It not enteres to Thread body at all, I have added logging per line and getting next console output log 

﻿[tid:1] Run
[tid:1] var t = new Thread
[tid:1] t.Start

This project has next configuration 

```xml
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
    <MonoWasmRuntimeConfiguration>threads-release</MonoWasmRuntimeConfiguration>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <MonoRuntimeDebuggerEnabled>true</MonoRuntimeDebuggerEnabled>
    <DefineConstants>$(DefineConstants);TRACE;DEBUG;__WASM__</DefineConstants>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

...

  <PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" Version="2.80.3-preview.40" />
    <PackageReference Include="SkiaSharp.Views.Uno" Version="2.80.3-preview.40" />
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid" Version="6.1.0-build.207.gcac670e618" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="3.5.1" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.WebAssembly" Version="3.5.1" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="2.0.0-dev.167" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="2.0.0-dev.167" PrivateAssets="all" />
```

**Comment by jeromelaban** [comment]
Thanks for the report.

Threading support is experimental in .NET and is currently somehow available when target `netstandard 2.0`. It has not yet been enabled in .NET 6.

**Comment by mnikonov** [comment]
Hi, @jeromelaban Thanks for a quick response. The project is targeted to netstandard 2.0 and not uses .NET5 or .NET6. I would appreciate any help on this issue. The problem mainly related bootstrapper version. Actually, what I need to do is to render list of big images using skiasharp, because wasm is single thread on attempt to load big file main thread become blocked and to workaround that I have had plan to move bitmap loading logic to background

**Comment by mnikonov** [comment]
according to **threading in its backlog** topic not only me having need to have support of SkiaSharp + Threading. One thread behaviour significantly limits uno + wasm in usecase scenarious :(. If you are writing new app using Blazor that's one story, but, when you are trying to port desktop application it completely different
