### ISSUE TITLE
[anyplat][Slider] doesnt update its visual when its Maximum/Minimum is changed.

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#5472]
## Current behavior

`Slider` doesnt update its visual when its `Maximum`/`Minimum` is changed.

## Expected behavior

`Slider`'s visual should be updated accordingly when its `Maximum`/`Minimum` is changed.

## How to reproduce it (as minimally and precisely as possible)
Sample: [SliderKnobPlacement.zip](https://github.com/unoplatform/uno/files/6144692/SliderKnobPlacement.zip)

- launch the sample
- use the combo-box to adjust the slider's Maximum
- *notices the knob remains at the same position*
![20210315 slider knob placement](https://user-images.githubusercontent.com/2359550/111223263-4cdb1b00-85b3-11eb-9eaa-cb81ac5ace6a.gif)

```xml
<StackPanel>
	<TextBlock>TestSlider.Value: <Run Text="{Binding ElementName=TestSlider, Path=Value}" /></TextBlock>
	<TextBlock>TestSlider.Minimum: <Run Text="{Binding ElementName=TestSlider, Path=Minimum}" /></TextBlock>
	<TextBlock>TestSlider.Maximum: <Run Text="{Binding ElementName=TestSlider, Path=Maximum}" /></TextBlock>
	<Slider x:Name="TestSlider"
			Value="2"
			Minimum="0"
			Maximum="4" />

	<ComboBox ItemsSource="3456789"
				SelectionChanged="UpdateSliderMaximum" />
</StackPanel>
```
```cs
private void UpdateSliderMaximum(object sender, SelectionChangedEventArgs e)
{
	var combo = (ComboBox)sender;
	var value = int.Parse(combo.SelectedValue.ToString());

	TestSlider.Maximum = value;
}
```

## Workaround
Manually invoke `Slider.ApplyValueToSlide` by reflection when `Slider.MinimumProperty` or `Slider.MaximumProperty` has been changed:
```cs
private static void OnApplyMinMaxBindingFixChanged(Slider control, DependencyPropertyChangedEventArgs e)
{
#if !WINDOWS_UWP
    if ((bool)e.NewValue)
    {
        TryApplyValueToSlide();
        control.RegisterPropertyChangedCallback(Slider.MinimumProperty, (s, e) => TryApplyValueToSlide());
        control.RegisterPropertyChangedCallback(Slider.MaximumProperty, (s, e) => TryApplyValueToSlide());
    }

    void TryApplyValueToSlide()
    {
        try
        {
            // original code: @OnValueChanged
            //	if (!_isInDragDelta && HasXamlTemplate) ApplyValueToSlide();

            // HasXamlTemplate will be checked in ApplyValueToSlide
            if (!Reflection<Slider>.GetField<bool>(control, "_isInDragDelta"))
            {
                Reflection<Slider>.Invoke(control, "ApplyValueToSlide");
            }
        }
        catch (Exception ex)
        {
            typeof(SliderBehavior).Log().Error("Failed to force invoke Slider refresh.", ex);
        }
    }
#endif
}
```

## Environment
Nuget Package: Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
Nuget Package Version(s): Uno.UI @ 3.1.0-beta.82, 3.6.0-dev.435
Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] macOS
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
IDE: Visual Studio 2019 (version: 16.8.5)
Relevant plugins: N/A

**Comment by MartinZikmund** [comment]
This should be fixed now that WinUI Slider was ported
