### ISSUE TITLE
[Gallery][Skia.GTK]ToggleSwitch-The toggleswitch button are same for Material, Fluent.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5477]
## Current behavior
![Toggleswitch](https://user-images.githubusercontent.com/74563602/111339243-fd95f880-864d-11eb-9527-06a125ffd1e0.png)

## Expected behavior
![Toggleswitch correct](https://user-images.githubusercontent.com/74563602/111339263-01297f80-864e-11eb-9100-23f5a62801fe.png)

## How to reproduce it (as minimally and precisely as possible)
1. Launch the Uno.Gallry app on Skia.GTK
2. Click on “ToggleSwitch” from the "Component" list.
3. Observe the Toggleswitch buttons are same for Material and  Fluent.

Nuget Package: Uno.UI.Skia.Gtk

Affected platform(s):
GTK (Linux)

IDE:
Visual Studio 2019 (version: )

**Comment by agneszitte-nventive** [comment]
The issue is normally fixed, tested Gallery locally with latest Uno stable packages

Uno.UI 4.0.11
Uno.Material / Uno.Cupertino 1.2.0

If you can double-check @sakshi173 , please

**Comment by sakshi173** [comment]
This issue is resolved closing.
