### ISSUE TITLE
Microsoft.UI.Xaml.Controls.NavigationView styling issues with nested NavigationViewItems

### ISSUE THREAD

**Issue by s-beltz** [unoplatform/uno#5478]
## Current behavior

When using nested NavigationViewItems in Microsoft.UI.Xaml.Controls.NavigationView expander on non-leaf items is missing and indentation of sub-items is not correct.

UWP:
![NavigationView_UWP-20200316](https://user-images.githubusercontent.com/57802605/111342101-6b581980-867a-11eb-8be0-79ed6bf30686.PNG)

Android:
![NavigationView_Android-20200316](https://user-images.githubusercontent.com/57802605/111342200-81fe7080-867a-11eb-87c4-d5054fcaee68.PNG)

WASM:
![NavigationView_WASM-20200316](https://user-images.githubusercontent.com/57802605/111342235-8c206f00-867a-11eb-9c94-9d1a288684d0.PNG)

## Expected behavior

- Expander is displayed for all platforms
- Correct indentation for sub-items

## How to reproduce it (as minimally and precisely as possible)

[UnoNavigationViewRepro_2021-03-16.zip](https://github.com/unoplatform/uno/files/6150524/UnoNavigationViewRepro_2021-03-16.zip)

## Workaround

[https://github.com/unoplatform/uno/issues/5265#issuecomment-788338614](url)
## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
- Uno.UI Version="3.6.0-dev.435"
- Microsoft.UI.Xaml Version="2.5.0"

Affected platform(s):

- [ ] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.6)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
Will be fixed by 5461

**Comment by MartinZikmund** [comment]
Fixed 👍
