### ISSUE TITLE
Grid alignment issues on Android & WASM

### ISSUE THREAD

**Issue by DStephensJr** [unoplatform/uno#5480]
## Current behavior
Grid alignment of items is not consistent on Android and WASM.  UWP works as expected.  Android and WASM align left rather than center.  Also do not honor 50* & 25* row sizing either.  

## Expected behavior
Consistent appearance on Android and WASM as on UWP. Center alignment and confined to columns.  Respect for * height proportions.

## How to reproduce it (as minimally and precisely as possible)

https://playground-wasm.azurewebsites.net/#dc711291

## Workaround

None found.

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
Noob in UNO/UWP
Mac & iOS & other variants were not tested due to availability.

**Comment by jeromelaban** [comment]
Thanks for the update.

We're going to merge this issue with #4231, which tracks all these layout problems with the current Grid implementation.
