### ISSUE TITLE
Please port BladeView(from Community toolkit) to Wasm

### ISSUE THREAD

**Issue by michalss** [unoplatform/uno#5481]
## What would you like to be added:
BladeView Control

## Why is this needed:
It is very nice control, besides i need it  :)

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Fixed in WCT 7.0 (which not available yet for Uno)

https://github.com/unoplatform/Uno.WindowsCommunityToolkit/pull/131
