### ISSUE TITLE
[iOS] DatePicker Text/Background Color

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#5482]
On some devices (i.e. the iOS simulators), the native `UIDatePicker` that shows up when you click the `DatePicker` has a white background and dark/black text. On every physical device I have tested so far, it shows up white on white which makes reading the values almost impossible.

How are these colors determined?

This happens with `Uno.UI.FeatureConfiguration.DatePicker.UseLegacyStyle` both on and off.

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): v3.5.1, v3.6.0-dev.445

Affected platform(s):

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
System light, with RequestedTheme dark:
![image](https://user-images.githubusercontent.com/5839577/111633520-fac11200-87cb-11eb-84df-edb802b96d04.png)

**Comment by mikernet** [comment]
Are there any workarounds you can think of for this?

**Comment by jeromelaban** [comment]
There are no app resources I can think of, but you can take a look at the code here, it may give yiou some hints:

https://github.com/unoplatform/uno/blob/dfd49a23a62ecca1c3c2b000fc1ed6b4732c1169/src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerSelector.iOS.cs#L36

**Comment by mikernet** [comment]
Is there a way to disable the native control and just use the UWP flyout instead?

**Comment by mikernet** [comment]
That almost works....except the highlighted value alignment is all off:

![image](https://user-images.githubusercontent.com/1700111/113335880-9043c200-92f3-11eb-9f0c-4528bf0f3f3f.png)

**Comment by mikernet** [comment]
Setting the flyout placement to `Full` to force it to the middle of the screen seems to have no effect on iOS, still behaves the same as the screenshot above (works on UWP):
```cs
<DatePicker Name="DateOfBirthPicker" Date="{x:Bind Data.DateOfBirthDTO, Mode=TwoWay}" ios:UseNativeStyle="false">
    <FlyoutBase.AttachedFlyout>
        <DatePickerFlyout Placement="Full"/>
    </FlyoutBase.AttachedFlyout>
</DatePicker>
```

**Comment by jeromelaban** [comment]
This last issue is tracked here: https://github.com/unoplatform/uno/issues/5345

**Comment by jeromelaban** [comment]
Fixed by https://github.com/unoplatform/uno/pull/9005
