### ISSUE TITLE
ScrollBar on WASM does not change to active color

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#5487]
## Current behavior

When ScrollBar is in "wide" state in WASM, it only has the default color, even when hovered or clicked.

![image](https://user-images.githubusercontent.com/1075116/111446337-925f2b80-870c-11eb-9f7f-4d5156f35cb6.png)

## Expected behavior

Color should change when mouse hovers and when clicked.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment]
@MartinZikmund I can see the same behavior on UWP. So probably this is okay?

**Comment by Youssef1313** [comment]
Hmm.. In an Uno app, using UWP head, the appearance changes on hover/press. However, in a pure UWP, this is not the case. Overall, there is a difference in appearance regarding the thickness and rounded corners in both cases.

@MartinZikmund Does that sound related to https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Controls/ScrollBar/ScrollBar.xaml ?

**Comment by MartinZikmund** [comment]
@Youssef1313 the appearance should not be affected by Uno - I think the difference you may see in UWP is that it does not use WinUI (does not have `XamlControlsResources` in `Application.xaml`) - can you check if that is the case please?

**Comment by Youssef1313** [comment]
@MartinZikmund Both have:

```xml
	<Application.Resources>
		<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
	</Application.Resources>

```

**Comment by MartinZikmund** [comment]
That is odd, Uno should not affect UWP styles at all. Can you post screenshot of the difference you see please?

**Comment by MartinZikmund** [comment]
Oh, and is the version of the Microsoft.UI.Xaml.Controls package the same for both cases?

**Comment by Youssef1313** [comment]
@MartinZikmund That was it! So back to the original issue, the more recent version on a pure UWP doesn't change color on hover/press. Should we just port the xaml file from mux repo just to match the rest of the appearance (it won't have color changes matching WinUI)?

**Comment by MartinZikmund** [comment]
The more recent version is WinUI 2.6 which we don't support yet, so this fix would be specifically for the "old one" for now.

**Comment by jeromelaban** [comment]
@MartinZikmund is this fixed with fluent v2 ?

**Comment by MartinZikmund** [comment]
This is indeed fixed.
