### ISSUE TITLE
Vertical sizing issue WASM/Android/iOS

### ISSUE THREAD

**Issue by s-beltz** [unoplatform/uno#5490]
## Current behavior

We observe a vertical sizing issue on non UWP platforms that produces infinite height for elements that size correctly on UWP.

UWP:
![Infinite-Height-UWP](https://user-images.githubusercontent.com/57802605/111436428-427b6700-8702-11eb-86a8-bf1a2bfc6dff.PNG)

WASM:
![Infinite-Height-WASM](https://user-images.githubusercontent.com/57802605/111436440-48714800-8702-11eb-90ae-8e3dd44196e3.PNG)

Android:
![Infinite-Height-Android](https://user-images.githubusercontent.com/57802605/111436460-4c9d6580-8702-11eb-99c1-cdf287a6c1ff.PNG)

## How to reproduce it (as minimally and precisely as possible)

Repro is showing the mentioned problem on non UWP platforms.
[UnoNavViewSample-infinite-height-2021-03-17.zip](https://github.com/unoplatform/uno/files/6155504/UnoNavViewSample-infinite-height-2021-03-17.zip)

## How to avoid

Adding a fixed height to the Grid in MainPage.xaml line 80 will avoid the problem. 
This is not a solution that we could use in general, as items need to size correctly respecting the surrounding container's dimensions.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI Version="3.6.0-dev.459"

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.2)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
May be related #4231

**Comment by jeromelaban** [comment]
The Grid control has been updated to match WinUI's behavior, and is likely to have fixed this issue. If it still happens, let us know.
