### ISSUE TITLE
Setting TextBox.Foreground produces NullReferenceException on Android device

### ISSUE THREAD

**Issue by s-beltz** [unoplatform/uno#5491]
## Current behavior

If setting TextBox.Foreground property Android devices will produce the following NullReferenceException:

```
Java.Lang.NoSuchFieldException   Message=No field mCursorDrawableRes in class Landroid/widget/TextView; (declaration of 'android.widget.TextView' appears in /system/framework/framework.jar!classes3.dex)
$exception    {System.NullReferenceException: Object reference not set to an instance of an object. 
at Windows.UI.Xaml.Controls.TextBoxView+EditTextCursorColorChanger.SetCursorColor (Android.Widget.EditText editText, Windows.UI.Color color) [0x00012] 
in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\TextBox\TextBoxView.Android.cs:162 }    System.NullReferenceException
```

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI Version="3.6.0-dev.459"

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.2)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
@s-beltz Having trouble reproducing this one, does this result in an application crash? I see the code that is being referenced is wrapped in a try/catch so it shouldn't be throwing an exception. 

Which version of the Uno.UI package are you using?

**Comment by s-beltz** [comment]
@kazo0 we observed this exception only on real hardware (Lenovo Tab M10) . The simulator does not show the exception. We last tested with Uno.UI  "3.6.0-dev.459"

**Comment by ibebbs** [comment]
Also seeing this issue on physical hardware (Honor View 20) but I'm not [explicitly] setting the foreground. It happens just by having an empty `<TextBox/>` element in the XAML and seems to screw up subsequent layout of the page.

I've tried both v3.5.1 & v3.6.6 of Uno.UI.

A [broader search](https://duckduckgo.com/?t=ffab&q=%22No+field+mCursorDrawableRes+in+class+Landroid%2Fwidget%2FTextView%22&ia=web) provides a couple of hits related to Material design. Could it be related?

**Comment by davidjohnoliver** [comment]
@ibebbs Uno's Material implementation is all XAML-based, so it's probably not directly related to the other reports.

Can you post the exact stack trace you're getting? It's strange that it should interrupt the layout, since as @kazo0 said the attempt to set the native caret foreground is wrapped in a `try/catch` and it's expected that it should fail (harmlessly) on some devices.
