### ISSUE TITLE
Cannot build wasm with SkiaSharp.Svg

### ISSUE THREAD

**Issue by vojta-kuchar-454** [unoplatform/uno#5493]
## Current behavior
I'm trying to render an svg file using SkiaSharp in a web browser. Simple line drawing in SkiaSharp works without problems with both wasm project and UWP. If, however, I will try to add the Uno.SkiaSharp.Wasm.Svg or Uno.SkiaSharp.Wasm.Extended libraries. So the project for wasm reports this error `System.Exception: Failed to generate AOT layout (More details are available in diagnostics mode or using the MSBuild /bl switch)
   v Uno.Wasm.Bootstrap.ShellTask_v5d2d19ce79e265c1a9724572ffa21b86e8483fd5.RunPackager() v D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:řádek 748
   v Uno.Wasm.Bootstrap.ShellTask_v5d2d19ce79e265c1a9724572ffa21b86e8483fd5.Execute() v D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:řádek 214	App1.Wasm	C:\Users\Petr\.nuget\packages\uno.wasm.bootstrap\2.0.0-dev.180\build\Uno.Wasm.Bootstrap.targets	172	
`. But in UWP, everything runs as it should. Thank you in advance for your help.

### Source Files
[Project](https://drive.google.com/drive/folders/14U1LEQGaI0I3DejaoCOQafofr1JRUcFA?usp=sharing)
[Log file](https://raw.githubusercontent.com/vojta-kuchar-454/files/main/log.txt)
[Desired result](https://github.com/vojta-kuchar-454/files/blob/main/Sn%C3%ADmek%20obrazovky%202021-03-17%20100447.png)

## Environment
Nuget Packages and versions:
Uno.Wasm.Bootstrap: 2.0.0dev.180
Uno.SkiaSharp.Wasm.Svg: 1.60.0-uno173
Uno.SkiaSharp.Wasm.Extended: 1.60.0-dev173
SkiaSharp.NativeAssets.WebAssembly: 2.80.3-preview.40
SkiaSharp.Views.Uno: 2.80.3-preview.40
SkiaSharp.Svg: 1.60.0
SkiaSharp.Views: 2.80.2
SkiaSharp.Extended: 1.60.0

### Affected platform(s):

- [ ]  iOS
- [ ]  Android
- [x]  WebAssembly
- [ ]  Windows

### Visual Studio

- [ ]  2017 (version: )
- [x]  2019 (version: 16.8.4)
- [ ]  for Mac (version: )

Relevant plugins

 Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. 

It's not possible to mix Uno.SkiaSharp.Wasm.Svg and SkiaSharp.Svg, but it's likely that you only need to remove `Uno.SkiaSharp.Wasm.Svg` and `Uno.SkiaSharp.Wasm.Extended` from your project.

If it still does not build, please create a simple repro project and attach it to this issue.
