### ISSUE TITLE
ApplicationLanguages.PrimaryLanguageOverride not implemented in Uno

### ISSUE THREAD

**Issue by chingucoding** [unoplatform/uno#5498]
## What would you like to be added:
[ApplicationLanguages.PrimaryLanguageOverride](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.applicationlanguages.primarylanguageoverride?view=winrt-19041) should be implemented to have feature parity with WinUI.
## Why is this needed:

This is needed to allow app developers let the user choose the language of the app instead of using the default system language.

## For which Platform:

- [ ] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Other platforms not tested.

## Anything else we need to know?

Not sure why exactly, but this [test](https://github.com/unoplatform/uno/blob/master/src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_DatePicker.cs#L126) uses this method despite it not being available in all platforms

**Comment by chingucoding** [comment]
Tried this with 3.5.1 and Uno.Core 2.1

**Comment by MartinZikmund** [comment]
@chingucoding can you try with the latest preview Uno.UI NuGet? @carldebilly implemented this while working on `DatePicker` :-)

**Comment by chingucoding** [comment]
Just tried and it worked in the latest dev build, thanks @MartinZikmund! Is there an approximate timeline when this will land in a stable build?

**Comment by MartinZikmund** [comment]
> Just tried and it worked in the latest dev build, thanks @MartinZikmund! Is there an approximate timeline when this will land in a stable build?

That's a secret, but not far away 😉😉😉 !

**Comment by chingucoding** [comment]
Haha, I see, thank you @MartinZikmund! Closing this now since it is not far away :P
