### ISSUE TITLE
[Android] ComboBox in Flayout can't be open

### ISSUE THREAD

**Issue by Mik1mak** [unoplatform/uno#5519]
## Current behavior

ComboBox neasted in flayout don't show dropdown list after tap.

## How to reproduce it (as minimally and precisely as possible)
![image](https://user-images.githubusercontent.com/29757080/111882238-e12eee80-89b4-11eb-9c28-1f85309e015c.png)

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

This issue is related to https://github.com/unoplatform/uno/issues/2533. Can you try the workaround specified in that issue?

**Comment by Mik1mak** [comment]
The Workaround from #2533 solved my problem.  Thank you.
