### ISSUE TITLE
[Linux Mint 20] Rider doesn't recognize 'InitializeComponent()' and XAML syntax

### ISSUE THREAD

**Issue by julewczka** [unoplatform/uno#5523]
## Current behavior

Rider doesn't recognize "InitializeComponent()' in App.xaml.cs and MainPage.xaml.cs.
![Screenshot from 2021-03-21 19-43-02](https://user-images.githubusercontent.com/66321464/111916955-b5c40680-8a7d-11eb-86a2-02beb88bd3dc.png)

Also syntax and error highlighting for xaml files is completely missing.
![Screenshot from 2021-03-21 19-42-08](https://user-images.githubusercontent.com/66321464/111916932-9200c080-8a7d-11eb-80bb-66cc2b145893.png)

How I created the project:
dotnet new unoapp -o TourPlanner -ios=false -android=false -macos=false -uwp=false -skia-wpf=false -st=false -wasm=false

However, when running the project, it behaves how it should. It is building and executing the "Hello World"-Application without any errors.

## Expected behavior

Syntax highlighting for xaml files should work and 'initializeComponent()' should be recognized.

## How to reproduce it (as minimally and precisely as possible)

1. go to Terminal and paste following command:
dotnet new unoapp -o TourPlanner -ios=false -android=false -macos=false -uwp=false -skia-wpf=false -st=false -wasm=false

2. open the solution with Rider

## Workaround

I didn't find any, however, running the program works

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [ ] WPF
  - [ x] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )
- [x] Rider Linux Mint 20 (version: 2020.3.2)

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
@julewczka please report this to JetBrains here https://youtrack.jetbrains.com/issues/RIDER?_ga=2.215312791.1864367963.1622716578-1490417664.1621438012 . We will be happy to upvote your feedback so post the link here afterwards, please 😉
