### ISSUE TITLE
WASM MSAL Auth does not work with B2CAuthority

### ISSUE THREAD

**Issue by endintiers** [unoplatform/uno#5527]
## Current behavior

Uno app using an MSAL PublicClientApplication including .WithB2CAuthority(Authentication.Authority) to utilise AD B2C signup-signin flow.

Droid and UWP versions work fine. WASM Version returns an invalid token: Token info is there, signature is invalid (from debug).

In code new JwtSecurityToken(authResult.IdToken); works in Droid and UWP, throws an exception in WASM.

## Expected behavior

Returned token should be valid in WASM as well as the other targets.

## How to reproduce it (as minimally and precisely as possible)

Requires an Azure B2C AD.
Create a signup-signin flow.
Create an application
Change the sample MSAL App to use the Azure AD B2C client (WASM works fine so far)
Change the shared PublicClientApplication constructor adding  .WithB2CAuthority(Authentication.Authority) before .RedirectUri

Authentication.Authority is of the form: $"{AuthorityBase}{Policy}";
Where AuthorityBase is like: @"https://{b2cADName}.b2clogin.com/tfp/{b2cADName}.onmicrosoft.com/"
And Policy is like: "B2C_{appName}_signup_signin"; (the name of the flow)

This should now use the flow fine in Droid and UWP but fail in WASM.

## Workaround

Haven't got one yet - perhaps manually restructure the token by creating a valid signature? Not sure if this is possible on the client.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [X] Other: Uno.UI.MSAL

Nuget Package Version(s):
All the latest Stable

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.9.2 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

I had a look at the Uno.Microsoft.Identity.Client fork but ran out of time (other projects... many) - seems to be a bit out of date?
Anyway there were no tests there for  .WithB2CAuthority that I could see.

Probably a serialization issue?

**Comment by endintiers** [comment]
Further info. I don't want to post a full token, but if I authenticate with UWP and WASM as the same user, buy the time the Id Token gets back to the C# code there are strange characters in the WASM version. Consider these two snippets, from the same area I believe it seems to go bad in the middle of the oid (a guid):
**UWP:** 90aW1lIjoxNjE2NDg0OTYyLCJvaWQiOiIzMDRlYTI4Ni01YjQ3LTRhMTYtOWJiOS05ZDA0ZDNjMjdkYWUiLCJuYW1lIjoiQ2hyaXMgSGV3aXR0IChMaXZ
**WASM:** 90aW1lIjoxNjE2NDg0NzYzLCJvaWQiOiIzMDRlYTI4Ni01YjQ3LTRhMTYtOWJiOS05ZDA0…uX25hbWUiOiJDaHJpcyIsImZhbWlseV9uYW1lIj

**Comment by endintiers** [comment]
There is also a different bug in MSAL. PublicClientApplication.AcquireTokenInteractive when using WithB2CAuthority.

Even in UWP, the returned token has an invalid signature. I tried doing exactly the same thing in Xamarin and yep: signature is invalid when the response is from B2CAuthority and valid when the response is from native AD (same behavior as in Uno).

So I guess I could log the "invalid signature" bug in Xamarin - that might help track down the issue (if there is a relationship).

The "WASM" issue that is the point of this bug can't be tested in Xamarin Forms of course.

I'll check the returned token in Blazor WASM for an invalid signature as well.

**Comment by endintiers** [comment]
**More information and a workaround.**

I tried a few different JWT libraries but could not construct a valid jwttoken from the encoded token in Uno/WASM, even though it was fine in all the other Uno targets - **_perhaps the implementation of Base64Decode in Mono is different?_**

I suspect the "invalid signature" was a red herring. The signature can only be valid if you have the shared secret. The header says it is RS256 but I think that's wrong - its HS256 

What I did finally was to just ignore the header and signature and turn the payload into a dictionary, including a local implementation of Base64Decode so as not to rely on any library. This solves my problem.

`            var tokenBits = authResult.IdToken.Split('.');
            if (tokenBits.Length < 2)
            {
                throw new ApplicationException($"Bad Token {authResult.IdToken}");
            }

            var payloadJson = Encoding.UTF8.GetString(Base64UrlDecode(tokenBits[1]));
            var payloadData = JObject.Parse(payloadJson);
            var payloadDict = JsonConvert.DeserializeObject<Dictionary<string, object>>(payloadJson);

            var name = (string)payloadDict["name"];

......................

        private static byte[] Base64UrlDecode(string input)
        {
            var output = input;
            output = output.Replace('-', '+'); // 62nd char of encoding
            output = output.Replace('_', '/'); // 63rd char of encoding
            switch (output.Length % 4) // Pad with trailing '='s
            {
                case 0: break; // No pad chars in this case
                case 2: output += "=="; break; // Two pad chars
                case 3: output += "="; break; // One pad char
                default: throw new System.Exception("Illegal base64url string!");
            }
            var converted = Convert.FromBase64String(output); // Standard base64 decoder
            return converted;
        }`

**Comment by jeromelaban** [comment]
Thanks for the update. If on WebAssembly your TargetFramework is `netstandard2.0`, you may want to try with `net5.0`, migrating your project [like this](https://github.com/unoplatform/uno/blob/master/doc/articles/migrating-from-previous-releases.md#migrating-webassembly-projects-to-net-5). The .NET 5 implemenation is likely to be closer (or equivalent) to UWP.

**Comment by carldebilly** [comment]
@endintiers are you able to confirm if it works using `net5.0` on your side, since it's using the _dotnet_ codebase instead of Mono... ? Please close this issue if the bug is fixed.

**Comment by endintiers** [comment]
@carldebilly I tried it in WASM with net5 (using Uno.Wasm.* v2.02 and another try with v2.1.0-dev.53)
Still fails to construct a JwtSecurityToken.
Specific problem code as follows:
```
        private void TransitionToAuthenticated(AuthenticationResult authResult)
        {
            var token = new JwtSecurityToken(authResult.IdToken);
            ......
```
You can prob. figure out where that goes... The authResult is from AD B2C, UWP version works fine.

Exception Message is:
IDX12729: Unable to decode the header 'System.String' as Base64Url encoded string. jwtEncodedString: 'System.String'.

**Comment by jeromelaban** [comment]
This looks like a .NET issue, as all classes involved are out of Uno sources. You may want to open an issue in the related repositories.

**Comment by endintiers** [comment]
@jeromelaban Since it isn't a problem for me as I have a work-around, AFAIK this can be closed. Its good that we have the work-around code here just in case someone else sees it. I don't have the time at the moment to do any more debug on it and it is a very edge case.
