### ISSUE TITLE
Getting these exceptions when opening UnoPlatform project in vs19

### ISSUE THREAD

**Issue by Barshan-Mandal** [unoplatform/uno#5539]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Uno.Core 2.1.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-x64. Package Uno.Core 2.1.0 supports:
  - net46 (.NETFramework,Version=v4.6)
  - net5.0 (.NETCoreApp,Version=v5.0)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - netstandard2.1 (.NETStandard,Version=v2.1)
  - uap10.0.15063 (UAP,Version=v10.0.15063)	unoplatform.UWP	C:\Users\SCS\source\repos\unoplatform\unoplatform.UWP\unoplatform.UWP.csproj	1	
Error	NU1202	Package Uno.Core 2.1.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393). Package Uno.Core 2.1.0 supports:
  - net46 (.NETFramework,Version=v4.6)
  - net5.0 (.NETCoreApp,Version=v5.0)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - netstandard2.1 (.NETStandard,Version=v2.1)
  - uap10.0.15063 (UAP,Version=v10.0.15063)	unoplatform.UWP	C:\Users\SCS\source\repos\unoplatform\unoplatform.UWP\unoplatform.UWP.csproj	1	
Error	NU1202	Package Uno.Core 2.1.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-x86. Package Uno.Core 2.1.0 supports:
  - net46 (.NETFramework,Version=v4.6)
  - net5.0 (.NETCoreApp,Version=v5.0)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - netstandard2.1 (.NETStandard,Version=v2.1)
  - uap10.0.15063 (UAP,Version=v10.0.15063)	unoplatform.UWP	C:\Users\SCS\source\repos\unoplatform\unoplatform.UWP\unoplatform.UWP.csproj	1	
Error	NU1202	Package Uno.Core 2.1.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-x86-aot. Package Uno.Core 2.1.0 supports:
  - net46 (.NETFramework,Version=v4.6)
  - net5.0 (.NETCoreApp,Version=v5.0)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - netstandard2.1 (.NETStandard,Version=v2.1)
  - uap10.0.15063 (UAP,Version=v10.0.15063)	unoplatform.UWP	C:\Users\SCS\source\repos\unoplatform\unoplatform.UWP\unoplatform.UWP.csproj	1	
Error	NU1202	Package Uno.Core 2.1.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-x64-aot. Package Uno.Core 2.1.0 supports:
  - net46 (.NETFramework,Version=v4.6)
  - net5.0 (.NETCoreApp,Version=v5.0)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - netstandard2.1 (.NETStandard,Version=v2.1)
  - uap10.0.15063 (UAP,Version=v10.0.15063)	unoplatform.UWP	C:\Users\SCS\source\repos\unoplatform\unoplatform.UWP\unoplatform.UWP.csproj	1	
Error	NU1202	Package Uno.Core 2.1.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-arm-aot. Package Uno.Core 2.1.0 supports:
  - net46 (.NETFramework,Version=v4.6)
  - net5.0 (.NETCoreApp,Version=v5.0)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - netstandard2.1 (.NETStandard,Version=v2.1)
  - uap10.0.15063 (UAP,Version=v10.0.15063)	unoplatform.UWP	C:\Users\SCS\source\repos\unoplatform\unoplatform.UWP\unoplatform.UWP.csproj	1	
Error	NU1202	Package Uno.Core 2.1.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-arm64-aot. Package Uno.Core 2.1.0 supports:
  - net46 (.NETFramework,Version=v4.6)
  - net5.0 (.NETCoreApp,Version=v5.0)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - netstandard2.1 (.NETStandard,Version=v2.1)
  - uap10.0.15063 (UAP,Version=v10.0.15063)	unoplatform.UWP	C:\Users\SCS\source\repos\unoplatform\unoplatform.UWP\unoplatform.UWP.csproj	1	
Error	NU1202	Package Uno.Core 2.1.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-arm. Package Uno.Core 2.1.0 supports:
  - net46 (.NETFramework,Version=v4.6)
  - net5.0 (.NETCoreApp,Version=v5.0)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - netstandard2.1 (.NETStandard,Version=v2.1)
  - uap10.0.15063 (UAP,Version=v10.0.15063)	unoplatform.UWP	C:\Users\SCS\source\repos\unoplatform\unoplatform.UWP\unoplatform.UWP.csproj	1

**Comment by carldebilly** [comment]
You should update your project to support at least UAP 15063.

**Comment by Barshan-Mandal** [comment]
how?????????

**Comment by jeromelaban** [comment]
Thanks for your report. Could you recreate this issue [using this template](https://github.com/unoplatform/uno/issues/new?assignees=&labels=kind%2Fbug%2C+triage%2Funtriaged%2C+difficulty%2Ftbd&template=bug-report.md), and fill the fields ? We need more information to help you fix this issue.

**Comment by Barshan-Mandal** [comment]
yes

**Comment by Barshan-Mandal** [comment]
I am not good at english..please help me

**Comment by Barshan-Mandal** [comment]
I am not good at english..please help me..i am only 8 years old

**Comment by jeromelaban** [comment]
Sure. Create an issue by going [here](https://github.com/unoplatform/uno/issues/new?assignees=&labels=kind%2Fbug%2C+triage%2Funtriaged%2C+difficulty%2Ftbd&template=bug-report.md), and fill the required fields, particularly the version numbers. We'll discuss it this new issue.

**Comment by Barshan-Mandal** [comment]
Please make it for me
