### ISSUE TITLE
CommonStates not applied on `NumberBox`

### ISSUE THREAD

**Issue by Guidemarcus** [unoplatform/uno#5543]
## Current behavior

Properties modified by CommonStates inside NumberBox style are not applied. This issue might be happening on other winui controls.

## Expected behavior

Properties modified by CommonStates inside NumberBox style should be applied. (UWP is working fine/as expected)

## How to reproduce it (as minimally and precisely as possible)

LINE 26 of MainPage.xaml
[NumberBoxState.zip](https://github.com/unoplatform/uno/files/6184005/NumberBoxState.zip)

## Workaround

use states inside each (RepeatButton and TextBox)

## Environment

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI : 3.7.0-dev.2

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.2)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment]
I'm on this one.
