### ISSUE TITLE
wasm: ComboBox is unreasonably slow 

### ISSUE THREAD

**Issue by yowl** [unoplatform/uno#555]
## I'm submitting a...

 - Feature request 

## Current behavior
Using the repo at 
A UWP combobox with 2000 items can have its datacontext set in 0.1s
The same code in wasm takes 90 seconds (debugger not open).
In the DOM it hasn't created the popup items yet which is good, so what its doing is unknown, and seems unnecessary.  In a LOB app combos are often used to lookup between keys and names and sometimes never opened so doing preparation (if that's what it's doing) for opening is not wanted and inefficient.

## Expected behavior
When not opening the combo, performance should be acceptable even in interpreted mode, after all the screen just has an empty combo

## Minimal reproduction of the problem with instructions
download https://github.com/yowl/UnoStandardRefTest/tree/comboperf and run in UWP and wasm and observe the performance.

## Environment

```
Nuget Package: 
    <PackageReference Include="Uno.UI" Version="1.43.0-dev.746" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="1.0.0-dev.159" />
Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ x] WebAssembly
- [x ] Windows
- [ ] Build tasks

Visual Studio
- [ x] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by pkar70** [comment]
I have similar problem with filling Combobox on Android.
