### ISSUE TITLE
`TimePicker` from WinUI

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#5553]
Adapt the WinUI's TimePicker to Uno

- [ ] Add native TimePicker ui test (https://github.com/unoplatform/uno/pull/5720)

## Related issues

- [iOS] TimePicker Property MinuteIncrements is not working #3540
- TimePicker does not use WinUI template #5990
- [iOS][Android] TimePicker, HasTimeStates are not working #4123
- [Gallery][Android]<TimePicker> TimePicker features are not working. #5366
- https://github.com/unoplatform/uno/issues/6658

**Comment by nrjmatta** [comment]
Hi, We are upgrading our UWP Project to UNO, any tentative date when this TimePicker would be available?

Thanks

Neeraj

**Comment by abenadar** [comment]
I wonder if there's any chance of seeing the TimeChanged event being fired and/or the Time property being implemented independently of actually translating the entire control  from UWP.  I don't know whether this is technically possible but that would at least make the control usable in  basic manner.

**Comment by jeromelaban** [comment]
@abenadar It's a change that should be relatively easy to implement. Changing:
https://github.com/unoplatform/uno/blob/58acd6e60bdc37320a9b6be1fae863978059a020/src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.cs#L268-L271

To raise this event that is currently not implemented:
https://github.com/unoplatform/uno/blob/58acd6e60bdc37320a9b6be1fae863978059a020/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TimePicker.cs#L171-L185

**Comment by jeromelaban** [comment]
It would look like this yes!

```csharp
 public  event global::System.EventHandler<global::Windows.UI.Xaml.Controls.TimePickerValueChangedEventArgs> TimeChanged;
 ``` 
 would even be simpler.

**Comment by abenadar** [comment]
Are these changes sufficient for a PR?

**Comment by jeromelaban** [comment]
@abenadar it's likely, but you can try it with this: https://platform.uno/docs/articles/uno-development/debugging-uno-ui.html#debugging-uno-in-another-application

**Comment by abenadar** [comment]
Courtesy of @Youssef1313: [9650](https://github.com/unoplatform/uno/pull/9650).

**Comment by agneszitte** [comment]
(cc @MartinZikmund)

**Comment by MartinZikmund** [comment]
@NVLudwig In progress, see PR 👍

**Comment by NVLudwig** [comment]
@MartinZikmund 
Reference for [Material](https://m3.material.io/components/time-pickers/overview)
MAterial [Figma file](https://www.figma.com/community/file/1035203688168086460/material-3-design-kit) for Time picker was updated in January as well
