### ISSUE TITLE
[Gallery][Android/iOS]Cupertino- PasswordBox  while writing text for password, the eye sign is missing to see the password.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5558]
## Current behavior
![passwordbox issue](https://user-images.githubusercontent.com/74563602/112358169-762c3300-8ca6-11eb-8f63-4685dca9a2a9.png)

## Expected behavior
![passwordbox correct](https://user-images.githubusercontent.com/74563602/112358182-7af0e700-8ca6-11eb-82c1-eef1f4749f42.png)

## How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click/tap Burger Menu on the left top right.
3. Click/tap "PasswordBox"  from the "Component" list.
4. Type Text for the passwordbox
5. Observe that while writing text for password, the eye sign is missing to see the picture.

Affected platform(s):
 iOS
 Android
 WebAssembly
 macOS
 Skia
Version(s):
Android
Version 1.4.3 (400749)
Mar 23, 2021 at 11:49
iOS
Version 1.4.3(749)

Device:
Samsung S8 - 8.0
Motorola g(7) – 9
iPhone 12 - 14.1

**Comment by kazo0** [comment]
This is by design that there should be no icon to view the password text. The fact that there is one on WASM is a bug itself. Notice that there are "double" icons on WASM for the Material PasswordBox. This should be raised as a separate issue. @sakshi173, ping me if you want me to explain further

**Comment by sakshi173** [comment]
As per above comment, This is not the bug, Closing.
