### ISSUE TITLE
[Gallery][Skia.Gtk]Cupertino -Slider and ProgressBar -Missing shadow for slider indicator and for ProgressBar.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5561]
## Current behavior
![Slider Gtk issue](https://user-images.githubusercontent.com/74563602/112363460-e5f0ec80-8cab-11eb-987d-8fccc40a2b81.png)
![progressbar skia issue](https://user-images.githubusercontent.com/74563602/112373343-3de12080-8cb7-11eb-89f4-11cba794aa8d.png)

## Expected behavior
![Slider  Skia correct](https://user-images.githubusercontent.com/74563602/112363498-f012eb00-8cab-11eb-8810-8d2f051a2420.png)

## How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app on Skia.GTK
2. Click on “Slider” item from the component list.
3. Observe shadow for slider indicator

Nuget Package: 
Uno.UI.Skia.Gtk

Affected platform(s):
GTK (Linux)

IDE:
Visual Studio 2019 (version: )

**Comment by kazo0** [comment]
This is currently not supported no Skia. Being tracked by https://github.com/unoplatform/uno/issues/4309
