### ISSUE TITLE
[Gallery][Wasm] PasswordBox -While writing text for password, 2 reveal icons are present for Material, Fluent and Cupertino.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5570]
## Current behavior
![passwordbox issue](https://user-images.githubusercontent.com/74563602/112481385-56037f00-8d4d-11eb-8f98-0b3014cfb743.png)

## Expected behavior
![passwordbox correct](https://user-images.githubusercontent.com/74563602/112481401-5b60c980-8d4d-11eb-85bb-f4c37a6fe525.png)

## How to reproduce it (as minimally and precisely as possible)

1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Click/tap Burger Menu on the left top right.
3. Click/tap "PasswordBox" from the "Component" list.
4. Type Text for the passwordbox.
5. Observe that while writing text for password, an extra eye icon is present for Material, Fluent and Cupertino.

Affected platform(s):
Windows

**Comment by agneszitte-nventive** [comment]
@sakshi173 Can you double check this issue please to see if you are still able to reproduce it please ? 
On my side I'm not seeing this issue at the moment.

**Comment by agneszitte-nventive** [comment]
I synced up with @sakshi173 and the issue cannot be reproduced with the latest canary version. 
Issue closed and ready to be QA'ed.

**Comment by sakshi173** [comment]
Verified, Issue is fixed, closing.

**Comment by sakshi173** [comment]
@agneszitte-nventive - The issue is again showing with the latest canary version.
https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=32606&view=results

Build 1.5.0-canaries-dev.774

![reveal issue](https://user-images.githubusercontent.com/74563602/131569562-1e9d5197-0d22-4bde-8173-4dafe168764d.png)

**Comment by sakshi173** [comment]
Now this issue is resolved with new build of canaries.
https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=32757&view=results.
1.5.0-canaries-dev.774
