### ISSUE TITLE
Application.Resources vs Page.Resources

### ISSUE THREAD

**Issue by Dimigergo** [unoplatform/uno#5571]
## Current behavior

![dg_2](https://user-images.githubusercontent.com/11498949/112482222-1a31df00-8d78-11eb-8b4e-cc0ecfd1c371.png)

## Expected behavior

![dg_1](https://user-images.githubusercontent.com/11498949/112481970-d939ca80-8d77-11eb-8c2b-9f2dad929757.png)

## How to reproduce it (as minimally and precisely as possible)

Include Microsoft.Toolkit.Uwp.UI.Controls (7.0.0 release and all of the Uno library is 3.7.0-dev.23) :
`xmlns:controls="using:Microsoft.Toolkit.Uwp.UI.Controls"`

Use the control in a Page:
`<controls:DataGrid`...

If I use these lines in the page resources, which has the datagrid control, it works perfect.
```
<Page.Resources>
    <SolidColorBrush x:Key="DataGridCellFocusVisualPrimaryBrush" Color="Transparent"/>
    <SolidColorBrush x:Key="DataGridCellFocusVisualSecondaryBrush" Color="Transparent"/>
</Page.Resources>
```
![dg_1](https://user-images.githubusercontent.com/11498949/112481905-c6bf9100-8d77-11eb-8af1-66938f661209.png)

...but when I try to these in App.xaml it won't work as I expected.
```
<Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
            </ResourceDictionary.MergedDictionaries>
            <vm:CViewModelLocator x:Key="Locator" />

            <SolidColorBrush x:Key="DataGridCellFocusVisualPrimaryBrush" Color="Transparent"/>
            <SolidColorBrush x:Key="DataGridCellFocusVisualSecondaryBrush" Color="Transparent"/>
            
        </ResourceDictionary>
    </Application.Resources>
```
![dg_2](https://user-images.githubusercontent.com/11498949/112482296-333a9000-8d78-11eb-94ca-98550aa6b477.png)

## Environment

All of the Uno library is 3.7.0-dev.23

Microsoft Visual Studio Professional 2019 Preview
Version 16.10.0 Preview 1.0
VisualStudio.16.Preview/16.10.0-pre.1.0+31025.218
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

**Comment by Dimigergo** [comment]
Hello!

In UWP project.

**Comment by davidjohnoliver** [comment]
If it occurs on UWP, it's not an Uno bug, since Uno is only used for non-UWP targets.

You may want to report the issue on the Windows Community Toolkit repo.
