### ISSUE TITLE
[Gallery][iOS]Toggleswitch  is not in correct shape for Material.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5578]
## Current behavior

![Toggleswitch material issue](https://user-images.githubusercontent.com/74563602/112520005-56157600-8d71-11eb-93ed-0c3bc23c425e.png)

## Expected behavior
![Toggleswitch material correct](https://user-images.githubusercontent.com/74563602/112520017-5a419380-8d71-11eb-9530-5d31f82aa921.png)

## How to reproduce it (as minimally and precisely as possible)
Open Uno Gallery APP for canary.
Tap Burger Menu on the left top right.
Tap "ToggleSwitch" from the "Component" list.
Observe that the Toggleswitch are not in correct shape for material.

Version(s):
Version 1.4.3 (753)

Device:
iphone 12 - 14.1

Affected platform(s):
iOS

**Comment by agneszitte-nventive** [comment]
The issue is normally fixed, tested Gallery locally with latest Uno stable packages
- iPhone Simulator 11 Pro Max iOS 15
- Uno.UI 4.0.11
- Uno.Material / Uno.Cupertino 1.2.0

If you can double-check @sakshi173, please

**Comment by sakshi173** [comment]
The issue is resolved, Closing it.
