### ISSUE TITLE
[Gallery][Android/iOS/Wasm]<Cupertino>Textbox and Combobox - PlaceholderText disappears when switching theme

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5580]
## Current behavior
**Wasm**
![Textbox night to day mode issue](https://user-images.githubusercontent.com/74563602/112544034-ee6d2400-8d8c-11eb-9e78-63ce359a886b.png)
**Android**
![Textbox night to day mode issue-Android](https://user-images.githubusercontent.com/74563602/112544044-f200ab00-8d8c-11eb-9dbb-48569cb1c8b4.png)
**iOS**
![Textbox night to day mode issue-ios](https://user-images.githubusercontent.com/74563602/112544054-f5943200-8d8c-11eb-9efa-017a3dd1887c.png)
![combobox night mode](https://user-images.githubusercontent.com/74563602/113351561-0f8fc080-9309-11eb-9728-2e32d1710e81.png)

## Expected behavior

![Textbox night to day mode Correct](https://user-images.githubusercontent.com/74563602/112544074-fd53d680-8d8c-11eb-9d71-e37efcf5ae14.png)

## How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP for canary.
2. Change theme from Day mode to Night mode.
3. Click/Tap "Flyout" or "TextBox" option from Burger Menu.
4. Click/Tap Cupertino option.
5. Again Change theme from Night mode to Day mode.
6. Observe that for "Textbox" the details are not displaying correctly.

Affected platform(s):

 iOS
 Android
 WebAssembly
 macOS
 Skia
Version(s):
Android
Version 1.4.3 (400753)
Mar 23, 2021 at 11:49
iOS
Version 1.4.3(753)

Device:
Samsung S8 - 8.0
Motorola g(7) – 9
iPhone 12 - 14.1

**Comment by sakshi173** [comment]
Texbox Issue is fixed, but still happening for Combobox and due to that reopening it.
 Below is the screenshot of Combobox issue.
![comobox theme change issue](https://user-images.githubusercontent.com/74563602/115785786-f02b0700-a38d-11eb-81ab-b340f43425ad.png)

**Comment by jeromelaban** [comment]
@davidjohnoliver Did you have additional issues existing for this ?

**Comment by davidjohnoliver** [comment]
> @davidjohnoliver Did you have additional issues existing for this ?

I don't recall, I'll reinvestigate the `ComboBox` bug.
