### ISSUE TITLE
Invalid typeof in x:Bind with enabled nullable reference types

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#5581]
## Current behavior

With `<nullable>enable</nullable>` project, the generated code for XAML `x:Bind` may contain invalid `typeof` expression - e.g. `typeof(object?)`

```xaml
<mux:RadioButtons Grid.Row="1" ItemsSource="{x:Bind ViewModel.Themes, Mode=OneWay}" SelectedItem="{x:Bind ViewModel.SelectedTheme, Mode=TwoWay}" />
```

Code-behind

```c#
public object? SelectedTheme {get; set;}
```

Generated code (problem at `typeof(object?)`)

```c#
c3.SetBinding(global::Microsoft.UI.Xaml.Controls.RadioButtons.SelectedItemProperty, new Windows.UI.Xaml.Data.Binding{ 
Mode = global::Windows.UI.Xaml.Data.BindingMode.TwoWay/* Windows.UI.Xaml.Data.BindingMode/Windows.UI.Xaml.Data.BindingMode, 
TwoWay, Bind/Mode */,  }.Apply(___b =>  /*defaultBindModeOneTime*/ global::Uno.UI.Xaml.BindingHelper.SetBindingXBindProvider(___b, this, ___ctx => 
___ctx is global::MZikmund.App.Views.SettingsView ___tctx ? (object)(___tctx.ViewModel.SelectedTheme) : null, (___ctx, __value) =>
 { if(___ctx is global::MZikmund.App.Views.SettingsView ___tctx) ___tctx.ViewModel.SelectedTheme = 
(object?)global::Windows.UI.Xaml.Markup.XamlBindingHelper.ConvertValue(typeof(object?), __value); } , new [] {"ViewModel.SelectedTheme"})));
```

## Expected behavior

Should build ok.

## How to reproduce it (as minimally and precisely as possible)

See above.

## Workaround

Do not use nullable reference type for the bound property.

## Environment

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by Youssef1313** [comment]
It looks like this was already fixed in https://github.com/unoplatform/uno/pull/5725.

**Comment by MartinZikmund** [comment]
I will test this and close the issue if it works

**Comment by Youssef1313** [comment]
Note: it might worth adding a test for nullable value type (eg, `int?`) where it's correct and allowed to have the `?` in `typeof`.

**Comment by Youssef1313** [comment]
@MartinZikmund I've added the extra test
