### ISSUE TITLE
Binding issue for custom DataGridColumn with DataTemplate that uses a DataTriggerBehavior

### ISSUE THREAD

**Issue by alove-kahua** [unoplatform/uno#5583]
## Current behavior

The DataGrid rows show incorrect data.

## Expected behavior

The DataGrid rows show correct data.

## How to reproduce it (as minimally and precisely as possible)

[DataGridColumnIssue.zip](https://github.com/unoplatform/uno/files/6212704/DataGridColumnIssue.zip)

1. Run the Wasm project
2. Click "Set One Folder" button and the DataGrid should show one row with a TextBlock with the Text of "Folder".
3. Click "Set Two Files" button and the DataGrid is supposed to show two rows, both with TextBlocks of Text "File".  Notice instead the first row shows "Folder".

If you continue clicking the buttons, the rows flip-flop the content instead of showing the rows correctly.
Appears to be around the DataTriggerBehavior's Binding.
This behavior works correctly in the Uwp project.

## Environment

Nuget Package:

- [X ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
@alove-kahua could you try installing https://www.nuget.org/packages/Uno.Microsoft.Xaml.Behaviors.Interactivity/2.0.2-uno.83 and see it fixes this issue on your end ?
