### ISSUE TITLE
.NET Native Logging missing metadata

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#5590]
## Current behavior

After updating the `Microsoft.Extensions.Logging` libraries to latest in UWP head, the .NET Native release build of apps crashes at startup with:

> System.Reflection.MissingMetadataException: ''Microsoft.Extensions.Options.IPostConfigureOptions<>' is missing metadata.

The issue is discussed here: https://github.com/dotnet/runtime/issues/44697

## Expected behavior

Should not crash.

## How to reproduce it (as minimally and precisely as possible)

Create blank new Uno app with new templates and compile and run with Release build.

## Workaround

Add the following entries to `Default.rd.xml`:

```
<Assembly Dynamic="Required All" Name="Microsoft.Extensions.Options"/>
<Assembly Dynamic="Required All" Name="Microsoft.Extensions.Logging"/>
```

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
@jeromelaban as this will probably be an issue for all apps based on latest template, maybe these should be added to the `Default.rd.xml` there?

**Comment by keozx** [comment]
This just happened to me, but using the rd.xml didn't help, got another error:
System.MissingMethodException: 'Constructor on type 'Microsoft.Extensions.Logging.Console' not found.'

Downgrading extensions is the only solution for me as of now, considering I'm using Splat extensions as well

**Comment by xperiandri** [comment]
@keozx this is my setup that works
https://github.com/xperiandri/Elmish.Uno/blob/develop/src/Templates/SolutionTemplate/SolutionTemplate.UWP/Properties/Default.rd.xml

You must not reference `Microsoft.Extensions.Logging.Console`
https://github.com/xperiandri/Elmish.Uno/blob/977f19020188545863b38f02ca4cdcb974586b44/src/Templates/SolutionTemplate/SolutionTemplate.UWP/SolutionTemplate.UWP.csproj#L16
