### ISSUE TITLE
Exists in both Microsoft.Windows.SDK.Net and Uno

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#5594]
Why do I see these errors ?

![image](https://user-images.githubusercontent.com/43340959/112763506-fafbb180-9004-11eb-8365-6e5aefbd3392.png)

**Comment by jeromelaban** [comment]
Thanks for the report. 

Would you mind creating another issue with [this template](https://github.com/unoplatform/uno/issues/new?assignees=&labels=kind%2Fbug%2C+triage%2Funtriaged%2C+difficulty%2Ftbd&template=bug-report.md) providing more information, and provide a sample reproduction project so we can help you ?
