### ISSUE TITLE
android build error due to global static resources

### ISSUE THREAD

**Issue by JanabiSoft** [unoplatform/uno#56]
Error	CS1002	; expected 
----------.Uni.Droid 
--------------.Uni.Droid\obj\Debug\g\XamlCodeGenerator\HelpPage_9dfed88ee309a80cecea1fb464f2de5e.g.cs	303	N/A

the error happened when there is style property in the page tag that reference a static resource defined in app.xaml
so I think that the code generator generate wrong code if the page contains reference to a globally referenced style.

**Comment by jeromelaban** [comment]
This kind of issues is related to the styles management in general. In this case, this can happen if a style has been defined inside of a DataTemplate/ControlTemplate inner element.

This will be addressed as part of a Styles work.

**Comment by carldebilly** [comment]
I fail to reproduce this problem... is it possible to give code or a repro?
