### ISSUE TITLE
[WASM] Text data binding unreliable on mobile devices

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#5618]
## Current behavior

When filling out form-like data with `TextBox` controls having `TwoWay` data binding without `UpdateSourceTrigger`, the data binding is not reliable on touch-based devices.

Seems like the problem is somehow caused by focus management in regards to touch - even though the input loses focus, it seems to still have it partially and so the binding does not propagate.

## Expected behavior

Should be reliable.

## How to reproduce it (as minimally and precisely as possible)

- Open Samples app on a mobile device or in desktop browser set to simulate mobile via developer tools
- Open the TextBox - TextBox_Bindings sample
- Write something in the first box and tap on the second
- Notice the binding does not properly update the other boxes

## Workaround

Set UpdateSourceTrigger=PropertyChanged on the binding.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
@dr1rrb looks familiar ?

**Comment by MartinZikmund** [comment]
@dr1rrb Seems to be the same on Safari on iPad/iPhone, and with Firefox on Android 🤔

**Comment by MartinZikmund** [comment]
From #6338:

Add some text boxes with bindings (x:Bind or Binding - both do the same thing). Move between text boxes by tapping and entering values and notice that the bindings aren't updated.

You can see this behavior with Chrome on the desktop: load https://app.iratio.ca/test, then enter a first and last name. Click the "Sign Up" button and notice no errors are produced for the first and last name field.

Now press F12, select the iPhoneX device, refresh the page and repeat the same process, only "tapping" between fields (no tabbing with the keyboard - mouse is fine though to simulate taps). Notice that none of the text box fields get set and the error reported shows that none of the fields have been filled in.

The test project source is available here: https://github.com/mikernet/UnoTest

It appears this is related to the textbox not losing focus properly during touch events, since the textbox bindings work when they have UpdateSourceTrigger=PropertyChanged set.

**Comment by MartinZikmund** [comment]
This is now resolved, probably thanks to native focus changes and `TextBoxView` focus adjustments.
