### ISSUE TITLE
[GTK] Socket.IOControl custom KeepAlive not supported

### ISSUE THREAD

**Issue by Zilkode** [unoplatform/uno#5633]
Platform: GTK (Linux -debian)

Trying to manipulate Socket.IOControl Keep alive is not supported:
Socket.IOControl handles windows-specific control handles windows-specific control codes and is not supported on this platform

1. Establish TCP connection.
2. Source code to reproduce:
```C#
int size = Marshal.SizeOf((uint)0);

                byte[] keepAlive = new byte[size * 3];
                Buffer.BlockCopy(BitConverter.GetBytes((uint)1), 0, keepAlive, 0, size);
                Buffer.BlockCopy(BitConverter.GetBytes((uint)5000), 0, keepAlive, size, size);
                Buffer.BlockCopy(BitConverter.GetBytes((uint)5000), 0, keepAlive, size * 2, size);
                tcpClient.Client.IOControl(IOControlCode.KeepAliveValues, keepAlive, null);
```
tcpClient.Client is Socket

Setting the KeepAlive manually is essential to override the socket's default timeout which is too long when using persistent connection,

**Comment by jeromelaban** [comment]
Thanks for the report. `TcpClient` is a class [provided by the .NET runtime](https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs), and it's likely that opening an issue in [dotnet/runtime](https://github.com/dotnet/runtime) will be more interesting.

**Comment by MartinZikmund** [comment]
It seems this issue is not related to Uno Platform, closing for now
