### ISSUE TITLE
[Gallery][iOS]ToggleSwitch-The toggleswitch button are same for Material, Cupertino and Native.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5634]
## Current behavior
![toggleswitch Material](https://user-images.githubusercontent.com/74563602/113183831-78503d80-9222-11eb-9b02-1401c9696c3f.png)
![toggleswitch Cupertino](https://user-images.githubusercontent.com/74563602/113183839-7be3c480-9222-11eb-9c9f-b7d08743b59a.png)
![toggleswitch Native](https://user-images.githubusercontent.com/74563602/113183847-7edeb500-9222-11eb-9d54-9e5f827114d4.png)

## Expected behavior
The Toggle switch shape should be correct for Material and Native.

## How to reproduce it 
1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "ToggleSwitch" from the "Component" list.
4. Observe that the toggleswitch button are same for Material, Cupertino and Native.

Version(s):
Version 1.4.3(749)

Device:
iPhone 12 - 14.1

Affected platform(s):
iOS

**Comment by kazo0** [comment]
@sakshi173 Can you check on an older version if this was still happening then? Looking at the code, it seems its always been like this on iOS

**Comment by sakshi173** [comment]
@kazo0  Yes it is old issue, Actually that time I raised this bug. https://github.com/unoplatform/uno/issues/5578.
That time the Native option was not displaying at all on ios, due to that was not able to verify for Native and the issue was having with Material  and raised the bug for that only.

**Comment by agneszitte-nventive** [comment]
The issue is normally fixed, tested Gallery locally with latest Uno stable packages
- iPhone Simulator 11 Pro Max iOS 15
- Uno.UI 4.0.11
- Uno.Material / Uno.Cupertino 1.2.0

If you can double-check @sakshi173, please

**Comment by sakshi173** [comment]
The issue is resolved, closing

**Comment by francoistanguay** [comment]
@kazo0  We should probably just hide the Material/Fluent systems on iOS as we now have the desired behavior of using  the Native switch by default? Same thing with Android I would imagine.

@sakshi173 ToggleSwitch defaults to the native iOS switch on iOS. Same thing for Android.
