### ISSUE TITLE
[WASM] Windows.UI.Xaml.Controls.SymbolIcon is not implemented

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#5635]
I'm getting warning above although it says [here](https://platform.uno/docs/articles/implemented/windows-ui-xaml-controls-symbolicon.html), that SymbilIcon would be supported.

Which one is right?

**Comment by jeromelaban** [comment]
Thanks for the report. Could you specify where you're seeing this warning, and in which uno package version ?

**Comment by DierkDroth** [comment]
I'm on
- Uno.UI 3.6.6
- Uno.UI.WebAssembly 3.6.6
(should be latest official since I updated last night)

**Comment by DierkDroth** [comment]
@jeromelaban is this a false warning or is there truth to SymbolIcon not being supported?

**Comment by jeromelaban** [comment]
It's an incorrect warning, it is implemented for all platforms.

**Comment by DierkDroth** [comment]
Thanks for clarification @jeromelaban

**Comment by jeromelaban** [comment]
This will be fixed by https://github.com/unoplatform/uno/pull/6118
