### ISSUE TITLE
[Flyout] For "Help" section the Nested Flyout for "Settings" is show out of the screen

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5639]
## Current behavior
![flyout Android issue](https://user-images.githubusercontent.com/74563602/113214262-3a194500-9247-11eb-8d92-f6c9cd772b0e.png)
![flyout iOS issue](https://user-images.githubusercontent.com/74563602/113214268-3c7b9f00-9247-11eb-9ee0-05d4cf7f6903.png)

## Expected behavior
![flyout correct](https://user-images.githubusercontent.com/74563602/113214285-41d8e980-9247-11eb-8f85-72cdd29d8cca.png)

## How to reproduce it (as minimally and precisely as possible)
1. Open Uno Gallery APP for canary.
2. Click "Flyout" option from Burger Menu.
3. Click “Help” Button in “Nested MenuFlyout ” section.
4. Click/Tap the "Send Feedback" section.
5. Click/Tap the "Settings" section.
6. Observe that the flyout sections for "Settings" is hiding.

Version(s):
Android
Version 1.4.3 (400753)
Mar 30, 2021 at 22:15
iOS
Version 1.4.3(749)

Device:
Samsung S8 - 8.0
Motorola g(7) – 9
iPhone 12 - 14.1

Affected platform(s):
Android
iOS

**Comment by jeromelaban** [comment]
The issue happens on all platforms, additionally, it is showing up differently than UWP as well. UWP puts the top left of the flyout at the mouse cursor position, whereas Uno puts it bottom middle at the mouse cursor.

**Comment by sakshi173** [comment]
@jeromelaban, for Android with the current canaries build I am seeing the application gets freeze when pressing the "Settings" button on Nested Flyout. **Shall I raise a separate bug for this issue?**

https://user-images.githubusercontent.com/74563602/131721881-7a9c9fe4-ff51-400e-a2ca-07fe65bc7f2e.mp4

**Comment by jeromelaban** [comment]
@sakshi173 yes, this would be a different one.
