### ISSUE TITLE
Adding projects seems to work using visual studio

### ISSUE THREAD

**Issue by chingucoding** [unoplatform/uno#5649]
## On which page?
https://github.com/unoplatform/uno/blob/master/doc/articles/cross-targeted-libraries.md/#project-references-and-sdk-references
## What's wrong?
Docs say, adding projects as dependency doesn't work using the Visual Studio solution view but instead it should be done by manually editing the file.

**Comment by davidjohnoliver** [comment]
Can you specify what version of Visual Studio you're using, and what exactly you did to add the project?

I just tried with a new Uno library in VS 16.10 pr1, right-clicking on the 'Dependencies' header and choosing 'Add Project Reference...', and I still get an error pop-up with "Missing value for TargetPlatformWinMDLocation property."

**Comment by chingucoding** [comment]
Oh sorry, of course. I was using Visual Studio 2019 Community Edition, Version 16.9.3.

**Comment by MartinZikmund** [comment]
For now closing this issue and will keep it in the docs, as it does not work reliably. Hopefully VS will fix soon
