### ISSUE TITLE
[Docs] Cross-runtime library support

### ISSUE THREAD

**Issue by marcelwgn** [unoplatform/uno#5653]
## On which page?
https://github.com/unoplatform/uno/blob/master/doc/articles/get-started-dotnet-new.md/#uno-platform-blank-cross-runtime-library
https://github.com/unoplatform/uno/blob/master/doc/articles/platform-specific-xaml.md/#xaml-prefixes-in-cross-targeted-libraries
## What's wrong?
On the one hand, Cross-Platform libraries aren't supposed to allow distinguishing WASM from Skia while Cross-Targeted libraries are (first link), on the other hand, XAML prefixes are not to be used in Cross-Targeted libraries since WASM and Skia will evaluate to the same. So it's unclear what is true now, does a cross-targeted library support separate WASM and SKIA compilation or does the cross-platform library support that?
## Any feedback?
Reading from the docs, it is very hard to tell whether to use cross-targeted or cross-platform since there is not much of a direct comparison between those types beside the `dotnet new` docs.

**Comment by davidjohnoliver** [comment]
Indeed the documentation is not at all clear on how and when to use cross-_runtime_ libraries, we should definitely expand on that.

The short version: [cross-runtime libraries](https://platform.uno/docs/articles/get-started-dotnet-new.html#uno-platform-blank-cross-runtime-library) allow you to distinguish WASM from Skia, cross-targeted libraries don't. 

I note in passing that the template seems buggy in that the Skia project isn't included by default, I've created a separate issue for that. https://github.com/unoplatform/uno/issues/5695

**Comment by jeromelaban** [comment]
This has been changed to be more simple with Single Project and Uno 5.2
