### ISSUE TITLE
[Gallery][Wasm/Android] PasswordBox Fluent- RevealButton foreground doesnt change with theme.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5654]
## Current behavior
![password wasm issue](https://user-images.githubusercontent.com/74563602/113345496-8a081280-9300-11eb-888f-d7887a4640c9.png)

## Expected behavior
The eye icon should be visible while typing text for password.

## How to reproduce it (as minimally and precisely as possible)
1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Change theme from Day mode to Night mode.
3. Click/tap Burger Menu on the left top right.
4. Click/tap "PasswordBox" from the "Component" list.
5. Type Text for the passwordbox.
6. Observe that while writing text for password,  eye icon is not visibile.

Affected platform(s):
Windows

**Comment by agneszitte-nventive** [comment]
Fixed while updating fluent textbox resources with the latest WinUI source code [Reunion 0.5].
Related PR => https://github.com/unoplatform/uno/pull/6153

**Comment by sakshi173** [comment]
Verified the issue is fixed, Closing.
