### ISSUE TITLE
[Gallery][Wasm] Animation -ScaleTransform and TranslateTransform1 image is leaving shadow after the animation.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5655]
## Current behavior
![wasm Transform issue](https://user-images.githubusercontent.com/74563602/113347031-968d6a80-9302-11eb-9cf7-f00792eb3021.png)
![was transform issue day mode](https://user-images.githubusercontent.com/74563602/113347046-9a20f180-9302-11eb-9279-d359d6e30882.png)
![wasm Transform issue 2 new](https://user-images.githubusercontent.com/74563602/113347074-a4db8680-9302-11eb-8105-d8bb154a1926.png)

## Expected behavior
There should not be any shadow after animation.
![wasm animation correct](https://user-images.githubusercontent.com/74563602/113347316-fedc4c00-9302-11eb-8113-f70686687879.png)

## How to reproduce it (as minimally and precisely as possible)

1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. From the left menu scroll to Features section
3. Click on Animations.
4. Click on Start button for ScaleTransform and TranslateTransform
5. Notice the Image shadow is displayed after the animation.

Affected platform(s):
Windows

**Comment by agneszitte-nventive** [comment]
@sakshi173 seems to me that this issue cannot be reproduced with the latest canary.
Closing this issue so you can double-check on your side. You can re-open it in case you still notice it on your side.
(cc @jeromelaban)

**Comment by sakshi173** [comment]
@agneszitte-nventive, I checked the bug with the latest canary, and the issue is still reproducible for ScaleTransform, due to that I am reopening the bug. The bug video with the latest canary build is presented below.

https://user-images.githubusercontent.com/74563602/174352775-c8fc6f4e-c911-45a9-8275-5e8bf98c69e2.mp4

**Comment by agneszitte-nventive** [comment]
> I think I mentioned it previously, this issue is Chrome related we cannot fix it at this time.

@jeromelaban I think @sakshi173 was able to reproduce it on Edge also. Is this a Chrome related issue only or WASM issue (including all supported browsers) ?

**Comment by jeromelaban** [comment]
It's a chromium issue, both Chrome and Edge are based on that engine.
