### ISSUE TITLE
Contact.FullName returns concatenated FirstName, LastName etc. even when DisplayNameOverride is set.

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#5658]
## Current behavior
Contact.FullName returns concatenated FirstName, LastName etc. even when DisplayNameOverride is set.

## Expected behavior
DisplayNameOverride should override both DisplayName and FullName (as in UWP).

## How to reproduce it (as minimally and precisely as possible)
On UWP:
```
        Dim oCon = New Windows.ApplicationModel.Contacts.Contact
        oCon.HonorificNamePrefix = "dr"
        oCon.HonorificNameSuffix = "honSuf"
        oCon.FirstName = "Piotr"
        oCon.MiddleName = "Łukasz"
        oCon.LastName = "Karocki"
        Debug.WriteLine(oCon.DisplayName)
        Debug.WriteLine(oCon.FullName)
        oCon.DisplayNameOverride = "alamakota"
        Debug.WriteLine(oCon.DisplayName)
        Debug.WriteLine(oCon.FullName)
```

shows:
```
dr Piotr Karocki honSuf
dr Piotr Łukasz Karocki honSuf
alamakota
alamakota
```

## Workaround
None.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [X] Other: Uno.UWP

Nuget Package Version(s):

Affected platform(s):
- [X] iOS
- [X] Android
- [X] WebAssembly
- [X] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [X] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [X] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:
- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by francoistanguay** [comment]
@pkar70  Shouldnt this issue be closed if your PR is merged?

**Comment by MartinZikmund** [comment]
Yep, this is fixed 👍
