### ISSUE TITLE
Implement Windows.Devices.Radios.GetRadios

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#5660]
## What would you like to be added:
Windows.Devices.Radios.GetRadios

## Why is this needed:
To check if Bluetooth (or other Radios) are available.

## For which Platform:

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
Duplicate of #3176
