### ISSUE TITLE
Exists in both Microsoft.Windows.SDK.Net and Uno

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#5663]
## Current behavior

I have been migrating about 20-30 projects, earlier was a pure WinUI 3 preveiw 4 solution, but by today I rendered them to net5 libraries so I wish to expect the Uno heads soon be starting up.... 
So I moved the WinUI pages to the shared project and referenced in Desktop and Wasm heads. 

![image](https://user-images.githubusercontent.com/43340959/113439960-d54b1f80-93eb-11eb-9989-0d9398243644.png)

**Desktop**: 

![image](https://user-images.githubusercontent.com/43340959/113440064-fe6bb000-93eb-11eb-9e61-81520dd31476.png)

**Wasm**:

![image](https://user-images.githubusercontent.com/43340959/113440170-29ee9a80-93ec-11eb-827d-c08dd684242d.png)

**The error's contexts** 

![image](https://user-images.githubusercontent.com/43340959/113440353-8b166e00-93ec-11eb-8ea1-dcc1aefb7ee4.png)

![image](https://user-images.githubusercontent.com/43340959/113440409-9e293e00-93ec-11eb-8a5c-ceb2c67df47f.png)

(Btw, why are the Storage related bits situated in the Uno.UI package?  did not even think it was in this particular package)

![image](https://user-images.githubusercontent.com/43340959/113440563-f95b3080-93ec-11eb-8adb-6702eebeac8c.png)

The `Suspending` event ought to be neat separated by the #ifdef.

![image](https://user-images.githubusercontent.com/43340959/113440721-3aebdb80-93ed-11eb-82f6-cc4f076fcf54.png)

Throws the error again as this event arg exists in both assembly. 

**Project files**

```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>Weather.History</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x86;x64;</Platforms>
		<RuntimeIdentifiers>win10-x86;win10-x64;</RuntimeIdentifiers>
	</PropertyGroup>
```

```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5</TargetFramework>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <MonoRuntimeDebuggerEnabled>true</MonoRuntimeDebuggerEnabled>
    <DefineConstants>$(DefineConstants);TRACE;DEBUG</DefineConstants>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\SplashScreen.png" />
  </ItemGroup>
  <ItemGroup>
    <UpToDateCheckInput Include="..\Weather.History.Shared\**\*.xaml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="WasmCSS\Fonts.css" />
    <EmbeddedResource Include="WasmScripts\AppManifest.js" />
  </ItemGroup>
  <ItemGroup>
    <LinkerDescriptor Include="LinkerConfig.xml" />
  </ItemGroup>
  <ItemGroup>
    <!--
    This item group is required by the project template because of the
    new SDK-Style project, otherwise some files are not added automatically.

    You can safely remove this ItemGroup completely.
    -->
    <None Include="Program.cs" />
    <None Include="LinkerConfig.xml" />
    <None Include="wwwroot\web.config" />
  </ItemGroup>
```

## How to reproduce it (as minimally and precisely as possible)

You need something else of this environment ?

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): _Please see above the referenced Nuget packages._ 

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.10.0 Prev 1.)
![image](https://user-images.githubusercontent.com/43340959/113441212-2fe57b00-93ee-11eb-9893-197057f37420.png)

![image](https://user-images.githubusercontent.com/43340959/113441674-fa8d5d00-93ee-11eb-86a4-a573e9285a56.png)

![image](https://user-images.githubusercontent.com/43340959/113441727-1690fe80-93ef-11eb-8c38-92249ef895fb.png)

- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Windows 10 OS spec:

![image](https://user-images.githubusercontent.com/43340959/113441169-18a68d80-93ee-11eb-8ec0-e182a1ad3db5.png)

**Comment by xperiandri** [comment]
I have the same issue. What I did is moved all the stuff in Windows projects to Microsoft native packages: WCT, Behaviors, etc. and removed Uno.WinUI reference as a workaround.

**Comment by jeromelaban** [comment]
To build for Project Reunion, you'll need to reference the `Uno.WinUI.*` packages. You can get a sample for this using [the WinUI 3 `dotnet new` templates](https://platform.uno/docs/articles/get-started-dotnet-new.html#uno-platform-blank-application-for-winui-30---preview).

**Comment by sigmarsson** [comment]
I had those `Uno.WinUI.*` for Wasm as depicted as the last two ones.
Just cranked up one solution for desktop with this template, no reference for such packages are configured for the desktop head. As mine lacks them too.  
`dotnet new unoapp -o MyApp`

Really beyond me, Cleaned, VS Restart, Rebuild, now having 11446 Errors.

![image](https://user-images.githubusercontent.com/43340959/113597342-db373f80-963b-11eb-9263-6bf99d88a9f7.png)

**Comment by sigmarsson** [comment]
I had those Uno.WinUI.* for Wasm as depicted as the last two ones.
Just cranked up one solution for desktop with this template, no reference for such packages are configured for the desktop head. As mine lacks them too.
`dotnet new unoapp-winui -o MyApp`

Really beyond me, Cleaned, VS Restart, Rebuild, now having 11446 Errors.

![image](https://user-images.githubusercontent.com/43340959/113598129-f2c2f800-963c-11eb-89e7-e9c5c4c6363d.png)

These references are set up by that template :

![image](https://user-images.githubusercontent.com/43340959/113598272-2b62d180-963d-11eb-9992-facf7d14a783.png)

**Comment by sigmarsson** [comment]
[1.txt](https://github.com/unoplatform/uno/files/6273644/1.txt)
Attached the log file in case any1 has time to review it.

**Comment by jeromelaban** [comment]
If you can reproduce the issue in small sample app based on the dotnet new template, it'll help.

**Comment by sigmarsson** [comment]
Template I used : dotnet new unoapp-winui -o "Weather.History" -uwp=false -ios=false -android=false -macos=false -sw=false -sg=false
0.05% of my source : https://github.com/sigmarsson/5663

![image](https://user-images.githubusercontent.com/43340959/114015503-0bfcbc00-986a-11eb-89e6-dd769cbc0ad9.png)

Heads are starting up but throwing run time errors.

**Comment by jeromelaban** [comment]
Thanks for the repro. The error you are seeing is an intellisense error only, as the build is likely to work properly.

 For the original issue you mentioned, it is likely that you are including Uno.WinUI in library projects that are cross-targeted with WinUI 3. In such case, you'll need to conditionally include the nuget package:

```xml
  <ItemGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
    <PackageReference Include="Uno.WinUI" Version="3.6.6" />
  </ItemGroup>
```

As some of your library projects are failing to build. Ensure those build individually first.

**Comment by sigmarsson** [comment]
Cool, dependencies are compiling fine and now I am try ing to compile the Desktop head only and c only 16 errors;

![image](https://user-images.githubusercontent.com/43340959/114060862-1a60cd00-9896-11eb-8ac7-c058e54b3a36.png)

[1.txt](https://github.com/unoplatform/uno/files/6280013/1.txt)

Why is it seeking the types in both **Microsoft.WinUI Version=3.0.0.0**  and **Uno.UI Version=255.255.255.255**

**Comment by sigmarsson** [comment]
I can only succeed to launch the if I obliterate all references of **Uno.UI** package and all ones requires it. 
`		<!--<PackageReference Include="Uno.UI" Version="3.6.6" />-->`
`    <!--<PackageReference Include="Infragistics.Uno.Charts" Version="20.2.59-alpha" />-->`
Had to remove for example the Infragistics package as well , since it requires Uno.UI. Something is wrong with that package.

**Comment by jeromelaban** [comment]
Infragistics does not support Uno.WinUI yet, and making a combination of the two is likely to produce the errors you're experiencing.

Have you tried using Uno.UI instead ? (`dotnet new unoapp` instead of `dotnet new unoapp-winui`)

**Comment by sigmarsson** [comment]
I had to reference `Uno.UI` explicit since I need the `Windows.Devices.*` and `Windows.Storage` namespaces but I had to remove them.  And without having Infragistics included here, I cannot compile as long as `Uno.UI` is being referenced. 

The Infragistics issue is a separate one then.

**Comment by sigmarsson** [comment]
`App.xaml.cs(89,23): error CS1061: 'LaunchActivatedEventArgs' does not contain a definition for 'UWPLaunchActivatedEventArgs' and no accessible extension method 'UWPLaunchActivatedEventArgs' accepting a first argument of type 'LaunchActivatedEventArgs' could be found (are you missing a using directive or an assembly reference?) `


`App.xaml.cs(60,44): error CS0433: The type 'LaunchActivatedEventArgs' exists in both 'Microsoft.Windows.SDK.NET, Version=10.0.19041.10, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'`


Any1 idea why these errors occuring ?

[msbuild.zip](https://github.com/unoplatform/uno/files/6376230/msbuild.zip)

**Comment by jeromelaban** [comment]
This is happening because you have uno installed on your Windows application. Your application seems to be a mix of WinUI and UWP, and I suggest that you restart the migration from a `dotnet new unoapp` to avoid these conversion errors.

**Comment by lotrasoft** [comment]
This issue is happening for me as well. First I create a blank application which works fine, but as soon as I add Uno.Cupertino, it starts giving a lot of build errors similar to this one:

App.xaml.cs(108,50,108,69): error CS0433: The type 'SuspendingEventArgs' exists in both 'Microsoft.Windows.SDK.NET, Version=10.0.22000.24, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'

**Comment by jeromelaban** [comment]
@kazo0 have you noticed this as well?

**Comment by iury-kc** [comment]
It is happening right now in a new machine here.

I tried using: dotnet new unoapp -o ProjectName
Uno-check is ok, but WSL.
