### ISSUE TITLE
WASM symbol not correctly pointed out, Skia probably too

### ISSUE THREAD

**Issue by chingucoding** [unoplatform/uno#5664]
## On which page?
https://github.com/unoplatform/uno/blob/master/doc/articles/platform-specific-csharp.md/#if-conditionals
## What's wrong?
Using `__WASM__` as symbol works as expected, using `HAS_UNO_WASM` however does not allow code to be run when using the WASM build of an app. I was using Uno.* 3.6.6 if that helps.

This might also be the case for Skia since it is also not following the__[platform]__ pattern, haven't tried that out though.

**Comment by jeromelaban** [comment]
Thanks for the report.

This define is added automatically here:
https://github.com/unoplatform/uno/blob/3873dad8b2d82bedb49b5cee63d832870a115896/src/Uno.UI.Runtime.WebAssembly/buildTransitive/Uno.UI.Runtime.WebAssembly.targets#L11

There may be occasions where this define is not set properly. If you can provide a repro that shows the issue, it would help.

**Comment by chingucoding** [comment]
Closing now as I'm also not able to reproduce this anymore. Sorry for any confusion caused.
