### ISSUE TITLE
C# edit and continue supported platforms

### ISSUE THREAD

**Issue by chingucoding** [unoplatform/uno#5665]
## What would you like clarification on:

What platforms support C# Edit and Continue? XAML Hot reload lists the platforms that do support it, however I wasn't able to find any information on the platforms supporting C# Edit and Continue.

## Concern?

- [ ] Usage in industry
- [x] Clarification of capabilities
- [ ] Getting started with Uno
- [ ] Developing with Uno
- [ ] Contributing to the Uno project
- [ ] Publishing your application
- [ ] Support
- [ ] Other (please specify):

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [x] Windows

**Comment by mrlacey** [comment]
Note. Hot Reload support is documented at https://platform.uno/docs/articles/features/working-with-xaml-hot-reload.html

**Comment by jeromelaban** [comment]
C# Edit and Continue is only available on Windows and for UWP or Skia targets at this point. This will change when C# Hot Reload included for all targets.

**Comment by jeromelaban** [comment]
More platforms have support for C# hot reload by microsoft, particularly the support for WebAssembly,
