### ISSUE TITLE
Uno templates not removed after Uninstall

### ISSUE THREAD

**Issue by Zilkode** [unoplatform/uno#5668]
Environment: VS 2019 Pro 16.9.2 
Extensions -> Manage Extensions - > [Uno Templates] -> Uninstall.

Expected: Remove template.
Actual -> Not removing.
Reason: Not deleting .nupkg file from templates folder.

The above behavior results in multiple same templates after reinstalling Uno templates.

Workaround: 
Go to: c:\Users\[USER]\.templateengine\dotnetcli\v5.0.201\packages\
delete file: uno.projecttemplates.dotnet.x.x.x (in my case 3.6.6)

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

The `dotnet new` templates are not installed by the VS extension, but rather through the CLI using an explicit command execution of `dotnet new -i Uno.ProjectTemplates.Dotnet`.

If you need to uninstall the CLI templates, you can use `dotnet new -u Uno.ProjectTemplates.Dotnet`
