### ISSUE TITLE
Uno Doesn't load uno projects correctly in visual studio 2019 preview.

### ISSUE THREAD

**Issue by Barshan-Mandal** [unoplatform/uno#5684]
## Current behavior

Uno Doesn't load uno project in visual studio 2019 preview.

## Expected behavior

Uno project will load as usual

## How to reproduce it (as minimally and precisely as possible)

download uno template for vs19 and open a cross platform project

## Environment

visual studio community 2019 preview 16.10.0

Affected platform(s):

- [x] All

- [x] Solution Templates

IDE:

- [x] visual studio community 2019 preview 16.10.0

Relevant plugins:

- [x] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

Could you provides screenshots or logs of the errors ?

**Comment by Barshan-Mandal** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'App' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'App' could be found (are you missing a using directive or an assembly reference?)	App2.Droid, App2.Skia.Tizen, App2.Skia.Wpf, App2.Wasm, App2.iOS, App2.macOS	D:\Temporary\testprojects\vs19\App2\App2.Shared\App.xaml.cs	24	Active
Error	CS1061	'MainPage' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	App2.Droid, App2.Skia.Tizen, App2.Skia.Wpf, App2.Wasm, App2.iOS, App2.macOS	D:\Temporary\testprojects\vs19\App2\App2.Shared\MainPage.xaml.cs	14	Active
Error	XLS0414	The type 'ThemeResource' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.	App2.macOS	D:\Temporary\testprojects\vs19\App2\App2.Shared\MainPage.xaml	10	
Warning	NU1701	Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.	App2.Skia.Gtk	D:\Temporary\testprojects\vs19\App2\App2.Skia.Gtk\App2.Skia.Gtk.csproj	1	
Warning	NU1701	Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.	App2.Skia.Wpf.Host	D:\Temporary\testprojects\vs19\App2\App2.Skia.Wpf.Host\App2.Skia.Wpf.Host.csproj	1

**Comment by Barshan-Mandal** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'MainPage' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	App2.iOS, App2.macOS	D:\Temporary\testprojects\vs19\App2\App2.Shared\MainPage.xaml.cs	14	Active
Error	CS0246	The type or namespace name 'IntPtr' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Main.cs	11	Active
Error	CS0246	The type or namespace name 'JniHandleOwnership' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Main.cs	11	Active
Error	CS0246	The type or namespace name 'AssemblyTitleAttribute' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	4	Active
Error	CS0246	The type or namespace name 'AssemblyTitle' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	4	Active
Error	CS0246	The type or namespace name 'AssemblyDescriptionAttribute' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	5	Active
Error	CS0246	The type or namespace name 'AssemblyDescription' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	5	Active
Error	CS0246	The type or namespace name 'AssemblyConfigurationAttribute' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	6	Active
Error	CS0246	The type or namespace name 'AssemblyConfiguration' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	6	Active
Error	CS0246	The type or namespace name 'AssemblyCompanyAttribute' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	7	Active
Error	CS0246	The type or namespace name 'AssemblyCompany' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	7	Active
Error	CS0246	The type or namespace name 'AssemblyProductAttribute' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	8	Active
Error	CS0246	The type or namespace name 'AssemblyProduct' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	8	Active
Error	CS0246	The type or namespace name 'AssemblyCopyrightAttribute' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	9	Active
Error	CS0246	The type or namespace name 'AssemblyCopyright' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	9	Active
Error	CS0246	The type or namespace name 'AssemblyTrademarkAttribute' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	10	Active
Error	CS0246	The type or namespace name 'AssemblyTrademark' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	10	Active
Error	CS0246	The type or namespace name 'AssemblyCultureAttribute' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	11	Active
Error	CS0246	The type or namespace name 'AssemblyCulture' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	11	Active
Error	CS0246	The type or namespace name 'ComVisibleAttribute' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	12	Active
Error	CS0246	The type or namespace name 'ComVisible' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	12	Active
Error	CS0246	The type or namespace name 'AssemblyVersionAttribute' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	24	Active
Error	CS0246	The type or namespace name 'AssemblyVersion' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	24	Active
Error	CS0246	The type or namespace name 'AssemblyFileVersionAttribute' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	25	Active
Error	CS0246	The type or namespace name 'AssemblyFileVersion' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs	25	Active
Error		Unknown type 'XamlControlsResources' in XML namespace 'clr-namespace:Microsoft.UI.Xaml.Controls;assembly=Uno.UI.FluentTheme'	App2.UWP	D:\Temporary\testprojects\vs19\App2\App2.Shared\App.xaml	9	
Error	CS1061	'App' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'App' could be found (are you missing a using directive or an assembly reference?)	App2.iOS, App2.macOS	D:\Temporary\testprojects\vs19\App2\App2.Shared\App.xaml.cs	24	Active
Error	XLS0414	The type 'ThemeResource' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.	App2.macOS	D:\Temporary\testprojects\vs19\App2\App2.Shared\MainPage.xaml	10	
Warning		Found conflicts between different versions of "System.Numerics.Vectors" that could not be resolved.
There was a conflict between "System.Numerics.Vectors, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
    "System.Numerics.Vectors, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not.
    References which depend on "System.Numerics.Vectors, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Numerics.Vectors.dll].
        D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Numerics.Vectors.dll
          Project file item includes which caused reference "D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Numerics.Vectors.dll".
            System.Numerics.Vectors
    References which depend on "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [].
        C:\Users\Barshan Mandal\.nuget\packages\system.text.json\5.0.0\lib\netstandard2.0\System.Text.Json.dll
          Project file item includes which caused reference "C:\Users\Barshan Mandal\.nuget\packages\system.text.json\5.0.0\lib\netstandard2.0\System.Text.Json.dll".
            C:\Users\Barshan Mandal\.nuget\packages\system.text.json\5.0.0\lib\netstandard2.0\System.Text.Json.dll
            C:\Users\Barshan Mandal\.nuget\packages\microsoft.extensions.logging.console\5.0.0\lib\netstandard2.0\Microsoft.Extensions.Logging.Console.dll	App2.Droid			
Warning		AndroidManifest.xml //uses-sdk/@android:targetSdkVersion '29' is less than $(TargetFrameworkVersion) ''. Using API-30 for ACW compilation.	App2.Droid	D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AndroidManifest.xml		
Warning	NU1701	Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.	App2.Skia.Gtk	D:\Temporary\testprojects\vs19\App2\App2.Skia.Gtk\App2.Skia.Gtk.csproj	1	
Warning	NETSDK1137	It is no longer necessary to use the Microsoft.NET.Sdk.WindowsDesktop SDK. Consider changing the Sdk attribute of the root Project element to 'Microsoft.NET.Sdk'.	App2.Skia.Wpf.Host	C:\Program Files\dotnet\sdk\5.0.200-preview.21077.7\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets	376	
Warning	NU1701	Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.	App2.Skia.Wpf.Host	D:\Temporary\testprojects\vs19\App2\App2.Skia.Wpf.Host\App2.Skia.Wpf.Host.csproj	1	
Warning	NU1701	Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.	App2.Skia.Wpf.Host	D:\Temporary\testprojects\vs19\App2\App2.Skia.Wpf.Host\App2.Skia.Wpf.Host_vmdsye33_wpftmp.csproj	1

**Comment by jeromelaban** [comment]
Thanks for the update. If you try building the solution , does it report the same errors ?

**Comment by Barshan-Mandal** [comment]
Yes...Of course

**Comment by jeromelaban** [comment]
Thank you. Can you provide a build log following the directions here: https://platform.uno/docs/articles/uno-builds-troubleshooting.html#generating-msbuild-binary-log-files

**Comment by Barshan-Mandal** [comment]
Rebuild started...
1>------ Rebuild All started: Project: App2.Skia.Wpf, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: App2.Droid, Configuration: Debug Any CPU ------
3>------ Skipped Rebuild All: Project: App2.iOS, Configuration: Debug iPhoneSimulator ------
3>Project not selected to build for this solution configuration 
4>------ Rebuild All started: Project: App2.UWP, Configuration: Debug x86 ------
5>------ Rebuild All started: Project: App2.Wasm, Configuration: Debug Any CPU ------
6>------ Skipped Rebuild All: Project: App2.macOS, Configuration: Debug iPhoneSimulator ------
6>Project not selected to build for this solution configuration 
7>------ Rebuild All started: Project: App2.Skia.Gtk, Configuration: Debug Any CPU ------
8>------ Rebuild All started: Project: App2.Skia.Tizen, Configuration: Debug Any CPU ------
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
5>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
8>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
7>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>C:\Users\Barshan Mandal\.nuget\packages\uno.sourcegenerationtasks\3.0.0\build\netstandard1.0\Uno.SourceGenerationTasks.targets(134,2): error : Generation failed, error code Rejected
1>Done building project "App2.Skia.Wpf.csproj" -- FAILED.
9>------ Rebuild All started: Project: App2.Skia.Wpf.Host, Configuration: Debug Any CPU ------
7>D:\Temporary\testprojects\vs19\App2\App2.Skia.Gtk\App2.Skia.Gtk.csproj : warning NU1701: Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
7>Uno.UI is using Roslyn generators
2>D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2204,5): warning MSB3277: Found conflicts between different versions of "System.Numerics.Vectors" that could not be resolved.
2>D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2204,5): warning MSB3277: There was a conflict between "System.Numerics.Vectors, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
2>D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2204,5): warning MSB3277:     "System.Numerics.Vectors, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not.
2>D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2204,5): warning MSB3277:     References which depend on "System.Numerics.Vectors, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Numerics.Vectors.dll].
2>D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2204,5): warning MSB3277:         D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Numerics.Vectors.dll
2>D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2204,5): warning MSB3277:           Project file item includes which caused reference "D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Numerics.Vectors.dll".
2>D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2204,5): warning MSB3277:             System.Numerics.Vectors
2>D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2204,5): warning MSB3277:     References which depend on "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [].
2>D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2204,5): warning MSB3277:         C:\Users\Barshan Mandal\.nuget\packages\system.text.json\5.0.0\lib\netstandard2.0\System.Text.Json.dll
2>D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2204,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Barshan Mandal\.nuget\packages\system.text.json\5.0.0\lib\netstandard2.0\System.Text.Json.dll".
2>D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2204,5): warning MSB3277:             C:\Users\Barshan Mandal\.nuget\packages\system.text.json\5.0.0\lib\netstandard2.0\System.Text.Json.dll
2>D:\Barshan\Application\Developers Tool\Application\Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2204,5): warning MSB3277:             C:\Users\Barshan Mandal\.nuget\packages\microsoft.extensions.logging.console\5.0.0\lib\netstandard2.0\Microsoft.Extensions.Logging.Console.dll
9>C:\Program Files\dotnet\sdk\5.0.200-preview.21077.7\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(376,5): warning NETSDK1137: It is no longer necessary to use the Microsoft.NET.Sdk.WindowsDesktop SDK. Consider changing the Sdk attribute of the root Project element to 'Microsoft.NET.Sdk'.
9>D:\Temporary\testprojects\vs19\App2\App2.Skia.Wpf.Host\App2.Skia.Wpf.Host.csproj : warning NU1701: Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.
9>D:\Temporary\testprojects\vs19\App2\App2.Skia.Wpf.Host\App2.Skia.Wpf.Host_molxxuht_wpftmp.csproj : warning NU1701: Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.
9>Uno.UI is using Roslyn generators
4>D:\Temporary\testprojects\vs19\App2\App2.Shared\App.xaml(8,6): XamlCompiler error WMC0075: Missing Content Property definition for Element 'Application' to receive content 'Application'
4>D:\Temporary\testprojects\vs19\App2\App2.Shared\App.xaml(8,6): XamlCompiler error WMC0011: Unknown member '_UnknownContent' on element 'Application'
4>D:\Temporary\testprojects\vs19\App2\App2.Shared\App.xaml(9,10): XamlCompiler error WMC0075: Missing Content Property definition for Element 'Application' to receive content 'XamlControlsResources'
4>D:\Temporary\testprojects\vs19\App2\App2.Shared\App.xaml(9,10): XamlCompiler error WMC0011: Unknown member '_UnknownContent' on element 'Application'
9>CSC : error CS0006: Metadata file 'D:\Temporary\testprojects\vs19\App2\App2.Skia.Wpf\bin\Debug\netstandard2.0\App2.Skia.Wpf.dll' could not be found
9>Done building project "App2.Skia.Wpf.Host_molxxuht_wpftmp.csproj" -- FAILED.
9>Done building project "App2.Skia.Wpf.Host.csproj" -- FAILED.
7>App2.Skia.Gtk -> D:\Temporary\testprojects\vs19\App2\App2.Skia.Gtk\bin\Debug\net5.0\App2.Skia.Gtk.dll
7>Done building project "App2.Skia.Gtk.csproj".
5>App2.Wasm -> D:\Temporary\testprojects\vs19\App2\App2.Wasm\bin\Debug\netstandard2.0\App2.Wasm.dll
8>App2.Skia.Tizen -> D:\Temporary\testprojects\vs19\App2\App2.Skia.Tizen\bin\Debug\tizen50\App2.Skia.Tizen.dll
8>TizenTpkFiles : C:\Users\Barshan Mandal\.nuget\packages\skiasharp\2.80.2\buildTransitive\tizen40\..\..\build\tizen40\x86\libSkiaSharp.so
8>TizenTpkFiles : C:\Users\Barshan Mandal\.nuget\packages\skiasharp\2.80.2\buildTransitive\tizen40\..\..\build\tizen40\arm\libSkiaSharp.so
8>TizenTpkFiles : shared\res\Icon.png
8>TizenTpkFiles : tizen-manifest.xml
8>App2.Skia.Tizen is signed with Default Certificates!
8>App2.Skia.Tizen -> D:\Temporary\testprojects\vs19\App2\App2.Skia.Tizen\bin\Debug\tizen50\com.example.App2.Skia.Tizen-1.0.0.tpk
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(4,12,4,25): error CS0246: The type or namespace name 'AssemblyTitleAttribute' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(4,12,4,25): error CS0246: The type or namespace name 'AssemblyTitle' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(5,12,5,31): error CS0246: The type or namespace name 'AssemblyDescriptionAttribute' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(5,12,5,31): error CS0246: The type or namespace name 'AssemblyDescription' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(6,12,6,33): error CS0246: The type or namespace name 'AssemblyConfigurationAttribute' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(6,12,6,33): error CS0246: The type or namespace name 'AssemblyConfiguration' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(7,12,7,27): error CS0246: The type or namespace name 'AssemblyCompanyAttribute' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(7,12,7,27): error CS0246: The type or namespace name 'AssemblyCompany' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(8,12,8,27): error CS0246: The type or namespace name 'AssemblyProductAttribute' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(8,12,8,27): error CS0246: The type or namespace name 'AssemblyProduct' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(9,12,9,29): error CS0246: The type or namespace name 'AssemblyCopyrightAttribute' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(9,12,9,29): error CS0246: The type or namespace name 'AssemblyCopyright' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(10,12,10,29): error CS0246: The type or namespace name 'AssemblyTrademarkAttribute' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(10,12,10,29): error CS0246: The type or namespace name 'AssemblyTrademark' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(11,12,11,27): error CS0246: The type or namespace name 'AssemblyCultureAttribute' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(11,12,11,27): error CS0246: The type or namespace name 'AssemblyCulture' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(12,12,12,22): error CS0246: The type or namespace name 'ComVisibleAttribute' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(12,12,12,22): error CS0246: The type or namespace name 'ComVisible' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(24,12,24,27): error CS0246: The type or namespace name 'AssemblyVersionAttribute' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(24,12,24,27): error CS0246: The type or namespace name 'AssemblyVersion' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(25,12,25,31): error CS0246: The type or namespace name 'AssemblyFileVersionAttribute' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Properties\AssemblyInfo.cs(25,12,25,31): error CS0246: The type or namespace name 'AssemblyFileVersion' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Main.cs(11,28,11,34): error CS0246: The type or namespace name 'IntPtr' could not be found (are you missing a using directive or an assembly reference?)
2>D:\Temporary\testprojects\vs19\App2\App2.Droid\Main.cs(11,50,11,68): error CS0246: The type or namespace name 'JniHandleOwnership' could not be found (are you missing a using directive or an assembly reference?)
========== Rebuild All: 3 succeeded, 4 failed, 2 skipped ==========

**Comment by Barshan-Mandal** [comment]
[RoslynLog-9bb937d0-a6cb-488f-bc9c-0bc63c15f0da.txt](https://github.com/unoplatform/uno/files/6276145/RoslynLog-9bb937d0-a6cb-488f-bc9c-0bc63c15f0da.txt)

**Comment by jeromelaban** [comment]
Thank you, please provide the logs from the failing build following the directions in this article: https://platform.uno/docs/articles/uno-builds-troubleshooting.html#generating-msbuild-binary-log-files. It will take the form of a `.binlog` file.

**Comment by Barshan-Mandal** [comment]
I cant realize that

**Comment by Barshan-Mandal** [comment]
help me please

**Comment by jeromelaban** [comment]
@Barshan-Mandal we'd like to help you, but without the proper logs, it's not possible. Please make sure to follow the documentation I posted above.

**Comment by Barshan-Mandal** [comment]
[msbuild.zip](https://github.com/unoplatform/uno/files/6302508/msbuild.zip)

**Comment by Barshan-Mandal** [comment]
Is it okey now?

**Comment by Barshan-Mandal** [comment]
I have given the log file .now please help me

**Comment by jeromelaban** [comment]
Thanks for the logs. We don't have enough information to help you troubleshoot this issue. Does running with a stable version of visual studio and using stable packages work for you ?

**Comment by Barshan-Mandal** [comment]
No bro

**Comment by Barshan-Mandal** [comment]
please help me please

**Comment by Barshan-Mandal** [comment]
bro please help me bro

**Comment by Barshan-Mandal** [comment]
> Thanks for the logs. We don't have enough information to help you troubleshoot this issue. Does running with a stable version of visual studio and using stable packages work for you ?

yes bro.Please help me please

**Comment by Barshan-Mandal** [comment]
bro  please....help me.plz plz plz

**Comment by Barshan-Mandal** [comment]
hey....help

**Comment by MartinZikmund** [comment]
Please try updating to the latest Visual Studio Preview maybe it will resolve your issue
