### ISSUE TITLE
[Gallery][WASM] Scrollbar for NavigationViewItem selection is missing.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5690]
## Current behavior
![scrollbar issue](https://user-images.githubusercontent.com/74563602/113754445-3cfbb600-96dd-11eb-922d-632dbd74eec7.png)

## Expected behavior
![scrollbar correct](https://user-images.githubusercontent.com/74563602/113754746-8b10b980-96dd-11eb-979f-b0f3e4d9379a.png)

## How to reproduce it (as minimally and precisely as possible)
1. Open the link https://unogallerycanary.z27.web.core.windows.net/
**OR**
1. Open the link https://unogallery-wasm-staging.azurewebsites.net/
2. Click the Burgrer menu and check Scrollbar for NavigationViewItem selection.
3. Observe that the Scrollbar is missing.

Affected platform(s):
Windows

**Comment by dr1rrb** [comment]
This has been fixed in uno few weeks ago

**Comment by sakshi173** [comment]
The issue is fixed but the new issue is started when change the day/ night theme the scrollbar gets disappear.

**Comment by jeromelaban** [comment]
@sakshi173 can you open another issue for this ? It's not the same in that case because it's related to theme changing. Thanks!

**Comment by sakshi173** [comment]
@jeromelaban sure I do that, Thanks for the feedback.

**Comment by sakshi173** [comment]
Closing this bug as this issue is fixed and opening another one for the Theme changing problem.
