### ISSUE TITLE
"AllowFocusOnInteraction" does not work on Android like it does on UWP.

### ISSUE THREAD

**Issue by asusralis** [unoplatform/uno#5693]
I have a TextBox and a Button, and I want to keep the software keyboard to stay open when the Button is selected. On UWP, when I set the Button's AllowFocusOnInteraction to true the TextBox keeps focus when the Button is clicked. However, on Android the TextBox loses focus and the keyboard closes.

It seems to me like the TextBox should stay focus on both Android and UWP. If this is not a bug, however, is there a better way to keep the Android/iOS keyboard open when I click the Button?

**Comment by jeromelaban** [comment]
Thanks you for the report.

`AllowFocusOnInteraction` is not implemented on any platform at this point:

https://github.com/unoplatform/uno/blob/17605edbfab824283f3051bb39943ef7b18f3f00/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/FrameworkElement.cs#L281-L282

**Comment by asusralis** [comment]
Was there any other way to do this without that property? I can't immediately set the focus back to TextBox, that makes the keyboard look like it's closing and messes with my layout.

**Comment by jeromelaban** [comment]
At this point, there's no direct way to implement this using Uno's APIs. In general, mobile OSes don't behave that way and make this scenario difficult to implement. You may need to interact with the native platforms directly to achieve this.

**Comment by davidjohnoliver** [comment]
You can set `IsTabStop="False"` and achieve the same thing. `IsTabStop` is supported by Uno.

**Comment by MartinZikmund** [comment]
The property is now properly supported on most targets
