### ISSUE TITLE
[Gallery][Android/iOS/Wasm] PersonPicture- Gallery logo inside circle is not displaying correctly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5696]
## Current behavior
**iOS** 
![personpicture issue](https://user-images.githubusercontent.com/74563602/113891448-139d6180-9793-11eb-8cd2-4b99f6f62934.png)
**Android/Wasm**
![personpicture issue Android](https://user-images.githubusercontent.com/74563602/113891509-244dd780-9793-11eb-8a0e-89aea4399865.png)

## Expected behavior
Gallery Logo should display correctly.

## How to reproduce it (as minimally and precisely as possible)
1. Open Uno Gallery APP .
2. Click/tap Burger Menu on the left top right.
3. Click/tap "Components" from the Burger Menu list
4. Click/tap on the "PersonPicture" option.
5. Observe that Gallery logo inside circle is not displaying correctly.

Version(s):
Version 1.4.3 (763) for iOS
Version 1.4.3 (400759) for Android

Device:
iphone 12 - 14.1
Motorola g(7) – 9

Affected platform(s):
iOS
Android
Windows

**Comment by jeromelaban** [comment]
Feels like a recent issue. @sakshi173  Would you know in which canary this started to happen ? This will help troubleshoot.

**Comment by sakshi173** [comment]
@jeromelaban, Yes this is recent issue, the Build Version is present in the bug and put it here again.
**Version(s):
Version 1.4.3 (763) for iOS  (Testflight)
Version 1.4.3 (400759) for Android(AppCenter)**

**Comment by jeromelaban** [comment]
@kazo0 does it look familiar ?

**Comment by kazo0** [comment]
Should be fixed by #5621, just need to re-test when the new builds are generated following this PR (https://github.com/unoplatform/Uno.Gallery/pull/220)

**Comment by sakshi173** [comment]
Verified, Issue is fixed. Closing.
