### ISSUE TITLE
Adding items to an ItemsControl on Android is extremely slow.

### ISSUE THREAD

**Issue by asusralis** [unoplatform/uno#5701]
I have an ItemsControl defined like such:

`
<ScrollViewer x:Name="MessageItemsControl" Margin="5">
            <ItemsControl ItemsSource="{Binding Messages}">
                <ItemsControl.ItemTemplate>
                    <DataTemplate>
                        <TextBlock
                            x:Name="MainText"
                            Text="{Binding Body}"
                            TextWrapping="Wrap" />
                    </DataTemplate>
                </ItemsControl.ItemTemplate>
            </ItemsControl>
        </ScrollViewer>
`

Whenever a message is added to Messages the application noticeably freezes for at least 100ms, sometimes much more. A Message is a simple VM with three property sets. This happens on a Pixel 4a. I have only tested on Debug mode. This problem does not exist on my UWP head.

**Comment by asusralis** [comment]
I created a project that shows this. If you try to scroll or type in the text box you will notice a lot of lag. Another problem is that if I do a hot reload the program becomes near unresponsive for me. Note that this is all for Android, I have no problems with any of this on UWP.
[CollectionTest.zip](https://github.com/unoplatform/uno/files/6287335/CollectionTest.zip)

**Comment by jeromelaban** [comment]
Thanks for the report. It's best when opening issues to keep the content of the template, so we avoid asking you additional questions.

How many items do you create ? Did you consider using `ListView` or `ItemsRepeater` instead ?

**Comment by asusralis** [comment]
Did you try the project I sent you? It happens immediately. I did not try another control. Should you not use an ItemsControl on Android? This happens with a very basic setup, so I assumed this was more of a bug.

**Comment by jeromelaban** [comment]
@asusralis In general `ItemsControl` is a control that should be used sparingly for large collections as it does not recycle item templates properly, which is where `ItemsRepeater` and `ListView` do help.

**Comment by asusralis** [comment]
This happens with a list with zero elements, so it might be a bug with the control then?

**Comment by seanbeanland** [comment]
I wanted to leave a note that, when having some performance issues with `ItemsControl` in WASM, switching to an `ItemsRepeater` also cleared up the issues completely.

**Comment by jeromelaban** [comment]
This issue is fixed in Uno 4.1-dev builds.
