### ISSUE TITLE
[Gallery][Android/iOS]Last selected Menu item of  Burger list is not Hightlighting.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5704]
## Current behavior

https://user-images.githubusercontent.com/74563602/114079623-6a309b80-9878-11eb-9ae0-c29f6ca77aec.MOV

## Expected behavior

https://user-images.githubusercontent.com/74563602/114079659-761c5d80-9878-11eb-9af9-b4ba069803da.mp4

## How to reproduce it
Open Uno Gallery APP .
Click/tap Burger Menu on the left top right.
Click/tap ("Components" or "Themes" or "Features") from the Burger Menu list
Click/tap on any option of the  from "Components" like "Button" or from "Theme" like  "Typography" or  from "Features" like  Brush 
Observe that the last selected menu items of the Burger list is not Highlighting.

Version(s):
Version 1.4.3 (763) for iOS
Version 1.4.3 (400759) for Android

Device:
iphone 12 - 14.1
Motorola g(7) – 9

Affected platform(s):
iOS
Android
Windows

**Comment by francoistanguay** [comment]
@sakshi173  Is this still happening or has it been fixed?

**Comment by sakshi173** [comment]
@francoistanguay, Yes still I am able to reproduce this bug, I reproduced it last week and already informed to Martin, He is aware of this bug
![selected issue](https://user-images.githubusercontent.com/74563602/151552373-360eae40-cb01-494b-843f-a62f30d1a611.png)
.

**Comment by MartinZikmund** [comment]
I think this will be lifecycle & ItemsRepeater related. In some path of the logic the selection does not get restored due to the event ordering on Android and iOS. Will look into it
