### ISSUE TITLE
Add support for EnteredBackground/LeavingBackground

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#5708]
## What would you like to be added:

Events from the issue title 😉

## Why is this needed:

Storing/restoring state for app.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by xperiandri** [comment]
![image](https://user-images.githubusercontent.com/2365592/141862320-429c4e1c-7dde-4345-b7e4-21a4ce39c88f.png)
@jeromelaban, @MartinZikmund I think that `GetDeferral` should just return a dummy object for simplicity of usage

**Comment by xperiandri** [comment]
This is crazy bad 😄
``` C#
            this.EnteredBackground += (_,e) => onEnteredBackground(
#if WINDOWS_UWP
                e.GetDeferral().Complete
#else
                () => {}
#endif
            );
            this.LeavingBackground += (_,e) => onLeavingBackground(
#if WINDOWS_UWP
                e.GetDeferral().Complete
#else
                () => {}
#endif
            );
```

**Comment by MartinZikmund** [comment]
@xperiandri agreed! Will make that change
