### ISSUE TITLE
Uno.UI exposes too many types

### ISSUE THREAD

**Issue by jeanplevesque** [unoplatform/uno#5709]
## Current behavior

There are a lot of types exposed that are not related to UWP or WinUI.
Most them are coming from the `Uno.Core` dependency, but it's not limited to that package.
This causes issues when using other packages with conflicting dependencies (like anything using `Microsoft.Extensions.Logging.Abstractions`).

## Expected behavior

The types and packages available from the Uno project template match the ones from the Blank UWP app.
Apps should be able to use the version of `Microsoft.Extensions.Logging.Abstractions` of their choice.

## How to reproduce it (as minimally and precisely as possible)

1. Create a new UWP Blank app using the default VisualStudio template.
2. Create a new Uno app using the VisualStudio extension from Uno.
3. Compare what packages are available by default.

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [x] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
Latest bits for Uno allow the use of any version of `Microsoft.Extensions.Logging.Abstractions`. What other types are problematic ?

**Comment by jeanplevesque** [comment]
> Latest bits for Uno allow the use of any version of `Microsoft.Extensions.Logging.Abstractions`.

I don't think I understand. Is there something special we need to do?
From what I can see, the latest Uno.UI still has a reference on Uno.Core, which still has the same dependencies.

**Comment by MartinZikmund** [comment]
The Uno.Core reference is quite important, as it contains many fundamental types like `Disposables` used throughout the codebase. What specific problem does it cause for you?

**Comment by jeanplevesque** [comment]
@MartinZikmund I think Uno should be limited to the UWP/WinUI public API (plus feature flags and platform specific helpers that affect to that public API).

**Comment by jeromelaban** [comment]
Fixed by Uno 4.0
