### ISSUE TITLE
VirtualizingPanelLayout is missing the Bindable attribute

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#5710]
I do get messages like the one below in the browser console (this is on 1.3.6). Obviously we don't control the offending component. So ... how could that issue be resolved?

> The Bindable attribute is missing and the type [Windows.UI.Xaml.Controls.VirtualizingPanelLayout] is not known by the MetadataProvider. Reflection was used instead of the binding engine and generated static metadata. Add the Bindable attribute to prevent this message and performance issues.

**Comment by jeromelaban** [comment]
Thanks for the report. This is a debug only message that you can ignore, we'll make changes to include it in the generation.

**Comment by DierkDroth** [comment]
@jeromelaban I do get that warning on many of my classes as well. As per [MS docs](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.bindableattribute?view=net-5.0) this attribute is relevant for design time only anyway:
> You can use this attribute at design time only. Nothing prevents you from binding to any property during run time.

This raises the questions: what's the point of that property in the UNO runtime context and why that warning in the browser?
