### ISSUE TITLE
[WASM] `FlyoutBase.ShowAt` not working as expected

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#5716]
## Current behavior

FlyoutBase.ShowAt(FrameworkElement) does not show a Flyout on WASM.
To be more specific: it appears to work for some FrameworkElements, but not for others

## Expected behavior

WASM should work like UWP

## How to reproduce it (as minimally and precisely as possible)

Click on button in attached project on WASM and compare with UWP
[Flyout.zip](https://github.com/unoplatform/uno/files/6289245/Flyout.zip)

## Workaround

??

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x ] Visual Studio 2019 (version: latest)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
Thanks for the report and the repro sample.

**Comment by DierkDroth** [comment]
Thanks @MartinZikmund. Confirm closed.
