### ISSUE TITLE
Unhandled exception. System.Exception: Could not resolve PresentationCore :: 2.1.0-dev.48\build\Uno.Wasm.Bootstrap.targets	173	

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#5719]
## Wasm head compilation errors 

![image](https://user-images.githubusercontent.com/43340959/114277592-11a1ff80-9a2c-11eb-9e4e-5e4a55154b51.png)
 

This is the project file : 

```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5</TargetFramework>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <MonoRuntimeDebuggerEnabled>true</MonoRuntimeDebuggerEnabled>
    <DefineConstants>$(DefineConstants);TRACE;DEBUG</DefineConstants>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\SplashScreen.png" />
  </ItemGroup>
  <ItemGroup>
    <UpToDateCheckInput Include="..\Weather.History.Shared\**\*.xaml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="WasmCSS\Fonts.css" />
    <EmbeddedResource Include="WasmScripts\AppManifest.js" />
  </ItemGroup>
  <ItemGroup>
    <LinkerDescriptor Include="LinkerConfig.xml" />
  </ItemGroup>
  <ItemGroup>
    <!--
    This item group is required by the project template because of the
    new SDK-Style project, otherwise some files are not added automatically.

    You can safely remove this ItemGroup completely.
    -->
    <None Include="Program.cs" />
    <None Include="LinkerConfig.xml" />
    <None Include="wwwroot\web.config" />
  </ItemGroup>
  <ItemGroup>
    <!--<PackageReference Include="Infragistics.Uno.Wasm.Charts" Version="20.2.59-alpha" />-->
    <PackageReference Include="Microsoft.NETCore.Targets" Version="6.0.0-preview.3.21201.4" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0-preview.3.21201.4" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.0.1" />
    <PackageReference Include="Uno.WinUI.WebAssembly" Version="3.7.0-dev.195" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="3.7.0-dev.195" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="2.1.0-dev.48" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="2.1.0-dev.48" />
    <!--<PackageReference Include="Uno.UI" Version="3.6.6" />-->
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Weather.History.Abstract\Weather.History.Abstract.csproj" />
    <ProjectReference Include="..\Weather.History.AppService\Weather.History.AppService.csproj" />
    <ProjectReference Include="..\Weather.History.CrossCutting\Weather.History.CrossCutting.csproj" />
    <ProjectReference Include="..\Weather.History.Dal\Weather.History.Dal.csproj" />
    <ProjectReference Include="..\Weather.History.DataService\Weather.History.DataService.csproj" />
    <ProjectReference Include="..\Weather.History.Entity\Weather.History.Entity.csproj" />
    <ProjectReference Include="..\Weather.History.IoC\Weather.History.IoC.csproj" />
    <ProjectReference Include="..\Weather.History.Log\Weather.History.Log.csproj" />
  </ItemGroup>
  <Import Project="..\Weather.History.Shared\Weather.History.Shared.projitems" Label="Shared" Condition="Exists('..\Weather.History.Shared\Weather.History.Shared.projitems')" />
  <ItemGroup>
    <PackageReference Update="Microsoft.Windows.Compatibility" Version="6.0.0-preview.3.21201.4" />
  </ItemGroup>
</Project>
```

## How to reproduce it (as minimally and precisely as possible)

Perhaps the presence of the preview packages ? 

## Workaround

Yet undisclosed.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

```
    <PackageReference Include="Microsoft.NETCore.Targets" Version="6.0.0-preview.3.21201.4" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0-preview.3.21201.4" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.0.1" />
    <PackageReference Include="Uno.WinUI.WebAssembly" Version="3.7.0-dev.195" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="3.7.0-dev.195" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="2.1.0-dev.48" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="2.1.0-dev.48" />
```

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.10.0 Preview 1)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Perhaps  `<TargetFramework>net5</TargetFramework>` causin problems ?

[Build log](https://github.com/unoplatform/uno/files/6290341/1.txt)

**Comment by jeromelaban** [comment]
It looks like you've added a reference to a package that uses WPF somehow, which is not supported by Uno. You're also trying to use net6 packages, which are not yet tested with Uno.

**Comment by sigmarsson** [comment]
Okay, set them back down to 5 and also obliterated that Desktop build target but still witness exactly the same 9 errors as earlier. 

![image](https://user-images.githubusercontent.com/43340959/114354734-e83dbc80-9b6e-11eb-8604-be2ec4ccfb11.png)

[Build log](https://github.com/unoplatform/uno/files/6294595/1.txt)

**Comment by jeromelaban** [comment]
Can you share the build binlog as mentioned here: https://platform.uno/docs/articles/uno-builds-troubleshooting.html ?

**Comment by sigmarsson** [comment]
1. `$msbuild Weather.History.sln /bl` **without** `PackageReference Include="Uno.UI" Version="3.6.6"`

[msbuild.zip](https://github.com/unoplatform/uno/files/6296768/msbuild.zip)
![image](https://user-images.githubusercontent.com/43340959/114395820-20f48a80-9b9d-11eb-9dac-a0d40f87b5f8.png)

2. `$msbuild Weather.History.sln /bl` **with** `PackageReference Include="Uno.UI" Version="3.6.6"`

[msbuild.Uno.UI.3.6.6.zip](https://github.com/unoplatform/uno/files/6296790/msbuild.Uno.UI.3.6.6.zip)
![image](https://user-images.githubusercontent.com/43340959/114396720-27373680-9b9e-11eb-93a1-50ba6464d91b.png)

**Comment by jeromelaban** [comment]
Thanks for the binlog. You're importing a dependency to `vanara.pinvoke.gdi32`, which uses WPF. You'll need to remove it from your dependencies for this to work on WebAssembly.

**Comment by sigmarsson** [comment]
Done. Whats more, vanara* removed but still 11432 errors while building the Wasm head and those 14 errors in winUI head still vexing if Uno.UI 3.6.6 is being referenced, exhibited by #5663

**Comment by jeromelaban** [comment]
Can you post again a binlog ?

**Comment by sigmarsson** [comment]
[msbuild.Uno.UI.3.6.6.-vanara.zip](https://github.com/unoplatform/uno/files/6297625/msbuild.Uno.UI.3.6.6.-vanara.zip)

**Comment by jeromelaban** [comment]
Thanks. You cannot mix Uno.UI and Uno.WinUI in the same solution. Your project file contains this:

```
    <PackageReference Include="Uno.WinUI.WebAssembly" Version="3.7.0-dev.195" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="3.7.0-dev.195" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="2.1.0-dev.48" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="2.1.0-dev.48" />
    <PackageReference Include="Uno.UI" Version="3.6.6" />
```

You need to remove the last Uno.UI reference.

**Comment by sigmarsson** [comment]
Merci. That was helping everything to resolve on the Wasm head. 
Did you mean those *WinUI and *UI packages are exclusive incompatible for any head ?
e.g. Like these ones in the Desktop head ? 

```
<PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.5.0" />
<PackageReference Include="Uno.UI" Version="3.6.6" />
```

**Comment by jeromelaban** [comment]
That's exactly right, you cannot have both packages in a project, directly or indirectly.

**Comment by sigmarsson** [comment]
Okay. But how shall I harness the `Windows.Devices` and `Windows.Storage`  namespaces in this case ?

**Comment by jeromelaban** [comment]
If you're on the UWP project, you can use those APIs directly, they are readily available. If on non-windows platforms, you can use Uno.UI or Uno.WinUI but not both. Also you cannot use `Microsoft.ProjectReunion.WinUI` but it is already part of the `Uno.WinUI` package for the non-windows platforms.

**Comment by sigmarsson** [comment]
Okay, cool. You will introduce a new package or multiple ones later for Windows non-UWP to make `Windows.Devices` and `Windows.Storage` namespaces available. Is that true?

**Comment by jeromelaban** [comment]
Those namespaces are already available in all targets. The errors you are getting are caused by both packages (Uno.UI and Uno.WinUI) being present, you need only one.

**Comment by sigmarsson** [comment]
Would you mind I am dispatching you another binlog ? Just replaced the *WinUI pgks with Uno.UI* and got this :

[msbuild.zip](https://github.com/unoplatform/uno/files/6311692/msbuild.zip)

I can find no more refs on Uno.WinUI pkg.

**Comment by jeromelaban** [comment]
Thanks. Replacing Uno.WinUI with Uno.UI also implies moving most of the `Microsoft.UI.Xaml` to `Windows.UI.Xaml` as well (WinUI to UWP).

**Comment by sigmarsson** [comment]
Okay, changed the NS and droped Microsoft.ProjectReunion* too and now under 20 errors. 

[msbuild.zip](https://github.com/unoplatform/uno/files/6327528/msbuild.zip)

Why `TabView` cannot be found now ?

**Comment by sigmarsson** [comment]
https://stackoverflow.com/questions/60053616/tabview-suddenly-missing-from-uwp

Perhaps TabView isnt existing any more in UWP?
Shall I install the Microsoft.UI.Xaml pkg?

**Comment by sigmarsson** [comment]
Okay, `Microsoft.UI.Xaml` pkg added and hopefully the remaining error is the one exhibited in #5663

[With.Microsoft.UI.Xaml.nuget.zip](https://github.com/unoplatform/uno/files/6329161/With.Microsoft.UI.Xaml.nuget.zip)


`error CS0433: The type 'LaunchActivatedEventArgs' exists in both 'Microsoft.Windows.SDK.NET, Version=10.0.19041.10, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'`

**Comment by jeromelaban** [comment]
The `Microsoft.UI.Xaml` package cannot be added to the Uno heads, and only on the UWP head. You will have to uninstall it from the Uno heads.

**Comment by sigmarsson** [comment]
Pkg dropped.

The rest ones found in App.xaml.cs


[msbuild.zip](https://github.com/unoplatform/uno/files/6349976/msbuild.zip)

![image](https://user-images.githubusercontent.com/43340959/115536636-4fa7ea80-a29a-11eb-978d-ff27bcc50854.png)
