### ISSUE TITLE
[Skia] Support for Reveal effect

### ISSUE THREAD

**Issue by ghost1372** [unoplatform/uno#5724]
## Current behavior
Is it normal that there are no effects for the Skia.WPF.Host project?

Skia.WPF
![image](https://user-images.githubusercontent.com/9213496/114303020-17a5e800-9ae1-11eb-9af5-6b42d267652f.png)

UWP
![image](https://user-images.githubusercontent.com/9213496/114303128-b3375880-9ae1-11eb-8d4f-264c53416f43.png)

## Expected behavior

Effects like the UWP version

## Environment

Nuget Package: 3.6.6

Affected platform(s):
- [ ] Skia
  - [x] WPF

IDE:

- [x] Visual Studio 2019 (version: )

**Comment by MartinZikmund** [comment]
Unfortunately reveal is not yet implemented in any target
