### ISSUE TITLE
ThreadPoolTimer not working

### ISSUE THREAD

**Issue by trungnt2910** [unoplatform/uno#5741]
## Current behavior

ThreadPoolTimer does not seem to work on Uno platforms

## Expected behavior

ThreadPoolTimer works.

## How to reproduce it (as minimally and precisely as possible)

1. Create a Uno Project.
2. Use this code
```C#
var periodicTimer = ThreadPoolTimer.CreatePeriodicTimer((source) => System.Diagnostics.Debug.WriteLine("Looping..."), TimeSpan.FromSeconds(1));
```
On Android and WASM, this does nothing.

## Workaround
WASM: Use Javascript `setInterval`
Android: Found none.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.6.6

Affected platform(s):

- [ ] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. This will be fixed by https://github.com/unoplatform/uno/pull/5742.
