### ISSUE TITLE
[WASM] FullAOT not working with latest Uno.UI.WebAssembly and Bootstrap 1.3.6

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#5744]
## Current behavior

If you try to build and run a WASM project in FullAOT using Uno.UI.WebAssembly and Uno.Wasm.BootStrap 1.3.6 then AOT build fails with error similar to, 

>Error: System.TypeInitializationException: The type initializer for 'Uno.Foundation.Interop.TSInteropMarshaller' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.LazyHelper' threw an exception. ---> System.ExecutionEngineException: Attempting to JIT compile method 'Microsoft.Extensions.Logging.ILogger Uno.Foundation.Interop.TSInteropMarshaller/<>c:<.cctor>b__6_0 ()' while running in aot-only mode.

## Expected behavior

Should be able to use FullAOT with Uno.Wasm.BootStrap 1.3.6

## How to reproduce it (as minimally and precisely as possible)

Build the attached project in WASM Release and try to run.

[App77.zip](https://github.com/unoplatform/uno/files/6306586/App77.zip)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.7.0-dev.216
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by DierkDroth** [comment]
@jeromelaban this looks like a regression, no?

**Comment by jeromelaban** [comment]
A recent change in Uno reveals an issue in the mono/mono runtime (`netstandard2.0`), but the reason for this issue is yet clear, as it does not happen with `net5` or later.

**Comment by DierkDroth** [comment]
Understand. Thanks for your feedback @jeromelaban

**Comment by peternary** [comment]
This is still not working for me in the attached project.  Are any changes to the project file or linker config required?

**Comment by DierkDroth** [comment]
@jeromelaban just leaving a mark here so this would not go unnoticed (since the issue is closed already)

**Comment by jeromelaban** [comment]
Which build did you try with ?

**Comment by peternary** [comment]
@jeromelaban latest build, 3.7.0-dev.263

**Comment by jeromelaban** [comment]
The issue is still present, there's another change that causes this issue. In the meantime, you can keep Uno 3.6.6.

**Comment by peternary** [comment]
Confirmed working in latest
