### ISSUE TITLE
WPF application freezes unless window size changes

### ISSUE THREAD

**Issue by trungnt2910** [unoplatform/uno#5745]
## Current behavior

WPF application does not respond unless window size is constantly changed.

Before resize
![image](https://user-images.githubusercontent.com/57174311/114701435-03662300-9d4d-11eb-9d3e-d6f40a01131e.png)

After resize
![image](https://user-images.githubusercontent.com/57174311/114701448-07924080-9d4d-11eb-8476-198da2715300.png)

## Expected behavior

WPF application must have its UI updated properly.

## How to reproduce it (as minimally and precisely as possible)

1. Create a Uno Platform project.
2. Add a `Button` control to the `MainPage`.
3. Build the `Skia.WPF` target.
4. Run the app. The application should be blank.
5. Resize the application window. The button should show.

## Workaround
Found none.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.6.6

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [x] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

This problem is something WPF-specific, it does not exist on GTK.

**Comment by jeromelaban** [comment]
Thanks for the report. Could you provide the exact version of the Uno.UI package you used ?

**Comment by jeromelaban** [comment]
I cannot reproduce the issue with the latest 3.7-dev builds. It may be related to a version of windows, or an environment issue. Does it reproduce on another machine ?

**Comment by trungnt2910** [comment]
> I cannot reproduce the issue with the latest 3.7-dev builds. It may be related to a version of windows, or an environment issue. Does it reproduce on another machine ?

I'll try to rebuild with the latest prerelease when I have access to my computer.
I cannot test the issue on another machine, because I have no other devices, and no more disk space to run an emulator.

**Comment by trungnt2910** [comment]
I've tested a publish .NET core app on another device. The issue does not appear.
This might be an environment issue on my computer, so I'm closing.
Sorry to disturb you.
