### ISSUE TITLE
Add support for CalendarView on iOS and Android

### ISSUE THREAD

**Issue by mrlacey** [unoplatform/uno#5748]
## What would you like to be added:

Support for [`CalendarView`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.calendarview?view=winrt-19041&WT.mc_id=WDIT-MVP-5001397)

## Why is this needed:

To enable selecting a date range

## For which Platform:

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

This control is currently [not implemented on any platform](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/CalendarView.cs).

There's a separate request for WASM support at #1496

**Comment by pkar70** [comment]
CalendarDatePicker for Android: PR#2079.
Some time ago, Uno:DatePicker looks like UWP:CalendarDatePicker, so I just copied all logic from Uno:DatePicker, changed name to CalendarDatePicker. As I have no iOS device, I can test it only on Android.
And I'm using it in my app, Android version: https://play.google.com/store/apps/details?id=pkar.Anniversaries, original Windows version: https://www.microsoft.com/en-us/p/anniversaries/9pjw858v28w8 .

**Comment by mrlacey** [comment]
@pkar70 your app uses the [Calendar]DatePicker to select a single date. I want the Calendarview so I can select a range of dates. like below image.

![](https://help.syncfusion.com/xamarin/calendar/images/xamarin.forms-calendar-multirange.png)
[from here](https://help.syncfusion.com/xamarin/calendar/select-multiple-dates#multi-range-selection-mode)


I can see [the DatePicker wraps a partial display of the CalendarView](https://github.com/unoplatform/uno/blob/master/src/Uno.UI.FluentTheme/Resources/PriorityDefault/CalendarDatePicker_themeresources.xaml#L205) but this does not provide all functionality. It may serve as a starting point though, thanks. ;)

**Comment by jeromelaban** [comment]
Thanks for the report. This issue is being tracked as part of https://github.com/unoplatform/uno/issues/3750, I'll close this one as a duplicate.
