### ISSUE TITLE
Inconsistent ActivationKind between iOS Universal Links and Android App Links

### ISSUE THREAD

**Issue by jeanplevesque** [unoplatform/uno#5756]
## Current behavior

- Lauching the app on **iOS** via Universal Link goes through **`App.OnLaunched`** and  `IActivatedEventArgs.Kind` is **`ActivationKind.Launch`**.
- Lauching the app on **Android** via Android App Link goes through **`App.OnActivated`** and  `IActivatedEventArgs.Kind` is **`ActivationKind.Protocol`**.
   - You can get the launch uri using `ProtocolActivatedEventArgs.Uri`.

## Expected behavior

Launching the app on iOS via Universal Link should go through **`App.OnActivated`** and  `IActivatedEventArgs.Kind` should be **`ActivationKind.Protocol`**.

## How to reproduce it (as minimally and precisely as possible)

1. Override both `App.OnLaunched` and `App.OnActivated` in `App.xaml.cs`
2. Add logs in both methods.
3. Launch the app from a Universal Link on iOS and from an Android App Link on Android.
4. Compare the logs.

## Workaround

We can get the launch url by overriding `App.ContinueUserActivity` and retrieving it from `NSUserActivity.WepPageUrl`.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.6)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

## Anything else we need to know?

Setting up Universal Links and Android App Links is much easier when using Branch.io because it generates and hosts the required web files for you.

**Comment by MartinZikmund** [comment]
@jeanplevesque merged the fix, when the preview NuGet package gets published, can you please verify if the behavior is now correct 🙂 ? Thank you!

**Comment by jeanplevesque** [comment]
I will! :)

**Comment by jeanplevesque** [comment]
I just tested and it works well, thanks! 🚀
