### ISSUE TITLE
After Visual Studio updating to the version 16.10.0 Preview 2 can't build an Uno project

### ISSUE THREAD

**Issue by LeftTwixWand** [unoplatform/uno#5759]
## Current behavior

After Visual Studio updating to the version **_16.10.0 Preview 2_** and **_dotent 5.0.300-preview.21180.15_** I can't build a WinUI project, generated by the **_dotnet new unoapp-winui_** command.

I've got this error:
`Project "C:\Program Files\dotnet\sdk\5.0.104\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.NuGet.targets" was not imported by "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets" at (16,3), due to the file not existing.`

`C:\Program Files\dotnet\sdk\5.0.104\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.NuGet.targets`

But at the same time, WinUI 3 project, generated with Project Reunion template form [this Visual Studio extension](https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftProjectReunion) is working fine.

## Environment

Nuget Package:
![image](https://user-images.githubusercontent.com/50652041/114893714-a8006780-9e16-11eb-8f23-bde28d11ada4.png)

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [x] Build tasks
- [x] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.10.0 Preview 2)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

## Anything else we need to know?

In Visual Studio version 16.10.0 Preview 1 everything were working fine.

**Comment by jeromelaban** [comment]
Thanks for the report! Could you share a [binlog of the build ](https://platform.uno/docs/articles/uno-builds-troubleshooting.html#generating-msbuild-binary-log-files)?

**Comment by LeftTwixWand** [comment]
@jeromelaban, I can't upload a .binlog file here, so this is the Google Drive link:
[https://drive.google.com/file/d/1c9CJF79Jmz](https://drive.google.com/file/d/1c9CJF79JmzGbCw0SDKS22IrB5eCV6wOa/view?usp=sharing)

**Comment by jeromelaban** [comment]
Thanks! For future reference, you can zip that file an post it here, this will work.

**Comment by LeftTwixWand** [comment]
Ok)

**Comment by jeromelaban** [comment]
This issue was likely fixed in recent version of Uno and/or Visual Studio. If the issue persists, let us know.
