### ISSUE TITLE
[wasm/skia.gtk/macOS] ISupportIncrementalLoading support

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#5763]
## What would you like to be added:
`ListView` support for `ISupportIncrementalLoading`

## Why is this needed:
For infinite-scrolling.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [ ] WPF
  - [x] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
@davidjohnoliver wasn't this supported in wasm ?

**Comment by davidjohnoliver** [comment]
> @davidjohnoliver wasn't this supported in wasm ?

Nope:
https://github.com/unoplatform/uno/blob/3b86bd77eaf93994d791afe021ca2ce7c62f63ab/src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.managed.cs#L73-L76

**Comment by Xiaoy312** [comment]
related: #234
