### ISSUE TITLE
[macOS,UWP] Inconsistency between platforms in the `Image` section

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/uno#5788]
## Current behavior

**macOS**
![Screen Shot 2021-02-12 at 4 00 38 PM](https://user-images.githubusercontent.com/38770890/107822084-85d16700-6d4b-11eb-96b8-350629a167fb.png)

**UWP**
![Screen Shot 2021-02-12 at 3 55 35 PM](https://user-images.githubusercontent.com/38770890/107822116-91bd2900-6d4b-11eb-91e9-68fb92946984.png)

## How to reproduce it (as minimally and precisely as possible)

1. From the left menu select Features and click on Image on both platforms
2. Notice There is an inconsistency between platforms in the Images section

**Note:** Confirm which of the platforms has the correct expected result. Although Window seems to be adequate, the images do not match the title displayed in the section

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
Not relevant anymore, as we have new macOS backend 🚀
