### ISSUE TITLE
[Gallery][WASM/Skia.Gtk/UWP] Card-Outline of the card image is not showing properly for all the options of Elevated card and for Disabled Outlined card

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5790]
## Current behavior
**For UWP/Skia.Gtk**
![card issue UWP](https://user-images.githubusercontent.com/74563602/115453190-57f61c00-a1ed-11eb-941b-cf6dccedbd19.png)
![card issue UWP2](https://user-images.githubusercontent.com/74563602/115453208-5af10c80-a1ed-11eb-8a8b-d6b2565779cd.png)

![card issue UWP3](https://user-images.githubusercontent.com/74563602/115452842-f170fe00-a1ec-11eb-86ed-d9a74db46153.png)
**For Wasm**
![card issue](https://user-images.githubusercontent.com/74563602/115452874-f930a280-a1ec-11eb-878e-ab5e7a49d466.png)
![card issue2](https://user-images.githubusercontent.com/74563602/115452879-fafa6600-a1ec-11eb-8841-fd2b87778e1c.png)
![card issue3](https://user-images.githubusercontent.com/74563602/115452888-fd5cc000-a1ec-11eb-8947-4d0c84a442cf.png)

## Expected behavior
![card correct](https://user-images.githubusercontent.com/74563602/115453691-e66a9d80-a1ed-11eb-9b35-000fad073f3e.png)
![card correct2](https://user-images.githubusercontent.com/74563602/115453703-e8ccf780-a1ed-11eb-9edf-9cb65d577698.png)

## How to reproduce it (as minimally and precisely as possible)
Open Uno Gallery APP .
Click/tap Burger Menu on the left top right.
Click/tap "Card from the "Component" list.
Observe the outline of the card image is not showing properly for all the Elevated card and Disabled outlined card option.

Affected platform(s):
UWP
WASM
Skia.Gtk

**Comment by francoistanguay** [comment]
@MartinZikmund  What's the status with this? Has it changed since we shipped the CardContentVControl in Toolkit cc 
@kazo0  ?

**Comment by MartinZikmund** [comment]
The problem on Skia is missing shadow support, but there is a PR close to merging for that. For wasm not sure yet

**Comment by agneszitte-nventive** [comment]
@MartinZikmund I will wait for better cross-platform support for the shadow/elevation for this issue as right now the same elevation value gives different outcomes depending on the platform used.
Cf. Previous discussions we had with you and @NVLudwig. Related item: https://github.com/unoplatform/uno/issues/6183

**Comment by agneszitte-nventive** [comment]
@MartinZikmund what is the update for the support of shadow/elevation lately ?
(cc @kazo0)

**Comment by MartinZikmund** [comment]
This will probably be addressed by the shadow enhancements which are in progress

**Comment by kazo0** [comment]
@MartinZikmund you mean the toolkit shadow stuff? Unlikely as it requires skia which means it'll be in a separate package that Material won't be using :/ or do you mean shadow enhancements from within Uno?

**Comment by Youssef1313** [comment]
@sakshi173 Is this still an issue?

**Comment by sakshi173** [comment]
Verified this issue is fixed, closing it.
![Card correct](https://github.com/unoplatform/uno/assets/74563602/8a52127a-b0b2-4b04-97dc-1448643a4c79)
