### ISSUE TITLE
DataTriggerBehavior not working with Colors

### ISSUE THREAD

**Issue by mknotzer** [unoplatform/uno#5807]
Changing the value of Background or Foreground fails, Height works

`
<TextBlock Text="Test">
    <i:Interaction.Behaviors>
        <ic:DataTriggerBehavior Binding="{Binding Order.Persona.IsFavorite}" Value="true">
            <ic:ChangePropertyAction PropertyName="Background" Value="#FFFF00" />
        </ic:DataTriggerBehavior>
        <ic:DataTriggerBehavior Binding="{Binding Order.Persona.IsFavorite}" Value="true">
            <ic:ChangePropertyAction PropertyName="Height" Value="10" />
        </ic:DataTriggerBehavior>
    </i:Interaction.Behaviors>
</TextBlock>
`
Uno 3.6.6

**Comment by jeromelaban** [comment]
Thanks for the report! Would you mind adding this sample to a repro sample using the uno app template? This will avoid intepretation mistakes. On which platform did you see this ?

**Comment by mknotzer** [comment]
iOS, Android and Web. It's super easy to reproduce. A TextBlock with a Binding on a page.

**Comment by jeromelaban** [comment]
Thanks for the platforms. 

It may be easy to repro, yet sometimes contextual details matter and we need an actual repro to get those out of the way. Thanks!

**Comment by mknotzer** [comment]
[MyApp.zip](https://github.com/unoplatform/uno/files/6493021/MyApp.zip)
sorry about the delay @jeromelaban

**Comment by jeromelaban** [comment]
As an update for this issue, not that there's no `Background` property for `TextBlock`, so the trigger cannot change this.

For the Foreground, the issue is a bit different where there's some generated XAML by the Behaviors library that fails in the Uno XamlGenerator. If you use a `StaticResource` containing a SolidColorBrush instead, it may work better.

**Comment by jeromelaban** [comment]
This issue may have been fixed by #6618. Could you validate if this helped for your scenario ?
