### ISSUE TITLE
Slider not available in ListView

### ISSUE THREAD

**Issue by HaoLife** [unoplatform/uno#581]
<ListView ItemsSource="{Binding}" 
                Margin="10,10,10,0" 
                HorizontalContentAlignment="Stretch">
        <ListView.ItemContainerStyle>
            <Style TargetType="ListViewItem">
                <Setter Property="HorizontalContentAlignment" Value="Stretch" />
                <Setter Property="Padding" Value="0" />
                <Setter Property="Margin" Value="0" />
            </Style>
        </ListView.ItemContainerStyle>
        <ListView.ItemTemplate>
            <DataTemplate>
                <Slider   Minimum="0" Maximum="100" Value="{Binding Number,Mode=TwoWay}" />
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>

## I'm submitting a...
Using the slider control in ListView can not be moved as a slider, and if TextBox is used, the slider slider is normal when the editing area is textbox activated

## Environment

```
Nuget Package: 
Uno.UI
Package Version(s): 
1.43.0-*

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by davidjohnoliver** [comment]
I couldn't repro using the supplied code snippet. We fixed a `ListView` issue on Android affecting the `Slider` control in #992 . Can you retest with the latest Uno package? If you still experience the issue, could you post a complete repro? Thanks!
