### ISSUE TITLE
Focus visual states are not applied in WASM for custom style

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno#5810]
## Current behavior

Focus visual states are not applied to custom styles for buttons and other controls (combobox) in WASM.

## Expected behavior

Focus visual states applied.

## How to reproduce it (as minimally and precisely as possible)

Attaching a test project. 
[App1.Shared.zip](https://github.com/unoplatform/uno/files/6366687/App1.Shared.zip)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by agneszitte-nventive** [comment]
@jeromelaban / @MartinZikmund 
I just noticed that the focus states are not applied for the ComboBox not only on WASM but also on Android, iOS, Skia, ...
Should we have separated issues for buttons, combobox (and maybe others)? Or it's related and can be fixed at once ?

**Comment by MartinZikmund** [comment]
@agneszitte-nventive it is related, and I will try to fix all together, but if you come across another control which has issues, let me know, so I don't miss something 👍
