### ISSUE TITLE
DataGrid is non-Editable on Skia.Gtk on Ubuntu 20.04

### ISSUE THREAD

**Issue by explorest** [unoplatform/uno#5822]
## Describe the bug
Followed all the steps in getting started with DataGrid (via the VSCode tab) from here https://platform.uno/docs/articles/uno-community-toolkit.html?tabs=tabid-vscode .    The issue is not specific to VSCode --- it reproduces with dotnet CLI as well.

The DataGrid binds normally and shows the bound data normally without problems. But clicking on cells do not make them editable. They are effectively rendered readonly. I tried setting IsReadOnly=false on the DataGrid and the individual Columns, as well as,  the Mode=TwoWay on the Bindings -- but to no avail.

Clicking on any cell produces the following error to the debug console in VSCode : 
--------------------------------------------------------------------------------------------------------------
**fail:** Windows.UI.Input.GestureRecognizer[0]
      Microsoft.Toolkit.Uwp.UI.Controls.DataGridCell Inconsistent state, we already have a pending gesture for a pointer that is going down. Abort the previous gesture.
**fail:** Windows.UI.Input.GestureRecognizer[0]
      Microsoft.Toolkit.Uwp.UI.Controls.DataGridRow Inconsistent state, we already have a pending gesture for a pointer that is going down. Abort the previous gesture.
**warn:** Uno.UI.Runtime.Skia.GtkCoreWindowExtension[0]
      Pointer capture is not supported on GTK
**warn:** Uno.UI.Runtime.Skia.GtkCoreWindowExtension[0]
      Pointer capture release is not supported on GTK '...'

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:  I am using the DataGrid for the first time. So I don't know whether its regression or not. 

## Steps to Reproduce

- [ ] Can this be reproduced in the Sample App? (Either in a sample as-is or with new XAML pasted in the editor.) If so, please provide custom XAML or steps to reproduce. If not, let us know why it can't be reproduced (e.g. more complex setup, environment, dependencies, etc...)  

I am unable to build any of the samples on my Ubuntu Linux machine, though I'm able to build and run Skia.Gtk heads of my own Uno apps normally. Following is the output of running $dotnet build  in the Skia.Gtk head of the sample app:

`user@myMachine:~/Projects/Uno.WindowsCommunityToolkit/Microsoft.Toolkit.Uwp.SampleApp.Skia.Gtk$ dotnet build
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/home/user/Projects/Uno.WindowsCommunityToolkit/Microsoft.Toolkit.Uwp.SampleApp.Skia.Gtk/Microsoft.Toolkit.Uwp.SampleApp.Skia.Gtk.csproj : warning NU1701: Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
  All projects are up-to-date for restore.
/home/user/Projects/Uno.WindowsCommunityToolkit/Microsoft.Toolkit.Uwp.SampleApp.Skia.Gtk/Microsoft.Toolkit.Uwp.SampleApp.Skia.Gtk.csproj : warning NU1701: Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
  Microsoft.Toolkit -> /home/user/Projects/Uno.WindowsCommunityToolkit/Microsoft.Toolkit/bin/Debug/netstandard2.0/Microsoft.Toolkit.dll
  Microsoft.Toolkit.Uwp.DeveloperTools -> /home/user/Projects/Uno.WindowsCommunityToolkit/Microsoft.Toolkit.Uwp.DeveloperTools/bin/Debug/netstandard2.0/Microsoft.Toolkit.Uwp.DeveloperTools.dll
  Microsoft.Toolkit.Uwp.UI.Controls.DataGrid -> /home/user/Projects/Uno.WindowsCommunityToolkit/Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/bin/Debug/netstandard2.0/Microsoft.Toolkit.Uwp.UI.Controls.DataGrid.dll

Build FAILED.

/home/user/Projects/Uno.WindowsCommunityToolkit/Microsoft.Toolkit.Uwp.SampleApp.Skia.Gtk/Microsoft.Toolkit.Uwp.SampleApp.Skia.Gtk.csproj : warning NU1701: Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
/home/user/Projects/Uno.WindowsCommunityToolkit/Microsoft.Toolkit.Uwp.SampleApp.Skia.Gtk/Microsoft.Toolkit.Uwp.SampleApp.Skia.Gtk.csproj : warning NU1701: Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
    2 Warning(s)
    0 Error(s)

Time Elapsed 00:00:18.55
`

However its very simple to reproduce. 

1. Given the following environment (Sample App w/ XAML, Project with Isolated setup, etc...)
     `     
           <Page
            x:Class="u.MainPage"
            xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
            xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
            xmlns:local="using:u"
            xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
           xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
           mc:Ignorable="d"
           xmlns:controls="using:Microsoft.Toolkit.Uwp.UI.Controls"    
    >

    <Page.DataContext>
    \<local:MainViewModel/\>
    </Page.DataContext>

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
   
 
    <controls:DataGrid x:Name="dataGrid" ItemsSource="{Binding Mountains}"  
    AutoGenerateColumns="True"
    />

   </Grid>
</Page>
`  

The DataContext class MainViewModel is as follows : 
   
`   
using System.Collections.ObjectModel;
using System.ComponentModel;

namespace u
{
   

class MainViewModel
{

    public MainViewModel()
    {
            this.Mountains = new ObservableCollection<MountainInfo>
            {
                new MountainInfo{Rank=1,Mountain="Everest"},

                 new MountainInfo{Rank=2,Mountain="K-2"},

                 new MountainInfo{Rank=9,Mountain="Nanga Parbat"}
            };

    }

[Bindable(true)]
    public ObservableCollection\<MountainInfo\>  Mountains { get; set; }

    
}

     public class MountainInfo
    {
        public int Rank { get; set; }
        public string Mountain { get; set; }
        
    }

    }`

2. Go to any cell of the DataGrid
3. Click on the cell. It does NOT turn editable. 
4. Scroll down to Debug Console
5. See error
**fail:** Windows.UI.Input.GestureRecognizer[0]
      Microsoft.Toolkit.Uwp.UI.Controls.DataGridCell Inconsistent state, we already have a pending gesture for a pointer that is going down. Abort the previous gesture.
**fail:** Windows.UI.Input.GestureRecognizer[0]
      Microsoft.Toolkit.Uwp.UI.Controls.DataGridRow Inconsistent state, we already have a pending gesture for a pointer that is going down. Abort the previous gesture.
**warn:** Uno.UI.Runtime.Skia.GtkCoreWindowExtension[0]
      Pointer capture is not supported on GTK
**warn:** Uno.UI.Runtime.Skia.GtkCoreWindowExtension[0]
      Pointer capture release is not supported on GTK '...'

## Expected behavior
The DataGrid cells should be editable by default.

## Environment

```
NuGet Package(s): 

Package Version(s): 

Device form factor:
- [x] Ubuntu Linux 20.04
 
-[x] Visual Studio Code [1.55.2] -- latest version
 
```

## Additional context

2. Go to any cell of the DataGrid
3. Click on the cell. It does NOT turn editable. 
4. Scroll down to Debug Console
5. See error
**fail:** Windows.UI.Input.GestureRecognizer[0]
      Microsoft.Toolkit.Uwp.UI.Controls.DataGridCell Inconsistent state, we already have a pending gesture for a pointer that is going down. Abort the previous gesture.
**fail:** Windows.UI.Input.GestureRecognizer[0]
      Microsoft.Toolkit.Uwp.UI.Controls.DataGridRow Inconsistent state, we already have a pending gesture for a pointer that is going down. Abort the previous gesture.
**warn:** Uno.UI.Runtime.Skia.GtkCoreWindowExtension[0]
      Pointer capture is not supported on GTK
**warn:** Uno.UI.Runtime.Skia.GtkCoreWindowExtension[0]
      Pointer capture release is not supported on GTK '...'

## Environment

```
NuGet Package(s):
"Microsoft.Extensions.Logging" Version="5.0.0" 
Microsoft.Extensions.Logging.Console" Version="5.0.0" 
"Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid" Version="7.0.0" 
"Uno.UI.Skia.Gtk" Version="3.6.6" 
"Uno.UI.RemoteControl" Version="3.6.6" Condition="'$(Configuration)'=='Debug'" 
 

Package Version(s): 
Given above with the packages

Device form factor:
- [ ] Ubuntu Linux 20.04
 
Visual Studio Code [1.55.2] -- latest version
 
```

**Comment by explorest** [comment]
This issue is fixed. Data grid is fully editable.  Environment details (operating system and dev tools) are all the same as above -- just versions upgraded.   Following are the current environment details under which this issue does NOT arise: 

NuGet Package(s):

"Microsoft.Extensions.Logging" Version="5.0.0" 
Microsoft.Extensions.Logging.Console" Version="5.0.0" 
"Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid" Version="7.1.10"
"Uno.UI.Skia.Gtk" Version="4.0.11"
"Uno.UI.RemoteControl"  Version="4.0.11" Condition="'$(Configuration)'=='Debug'" 
 

Operating system:  Ubuntu Linux 20.04  -- (same version as the original issue was filed against). 
 
Visual Studio Code [1.63.2] -- (latest version)


Thank you a lot for fixing it.  I am happy to provide any further relevant details.

**Comment by jeromelaban** [comment]
Thanks for updating the issue!
