### ISSUE TITLE
SolidColorBrush on WPF/Skia isn't being reclaimed correctly

### ISSUE THREAD

**Issue by mterwoord** [unoplatform/uno#5843]
## Current behavior

See attached project. I have a `DummyColorConverter`, which produces a SolidColorBrush. The returned brushes are never correctly garbage collected, resulting in a memory leak. (In my actual project, resulted in 12GB of ram with the software running over night).

## Expected behavior

Memory usage should be stable.

## How to reproduce it (as minimally and precisely as possible)

See attached project. Run the UnoMemory.Skia.Wpf.Host project. It contains 100 cards, with each of them  a textblock of which the foreground color is determined via the color converter.
The project will run a `DispatcherTimer` which updates all textblocks, meaning they get a new Brush, and the old ones get leaked.

## Workaround

Open up `DummyColorConverter.cs`, have it return `_brush` (the code is there as comment). Now the memory usage is way better.

## Environment

Nuget Package:
- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [X] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

3.8.0-dev.45 (latest prerelease at time of writing)

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [X] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [X] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

[UnoMemoryClean.zip](https://github.com/unoplatform/uno/files/6393884/UnoMemoryClean.zip)

**Comment by jeromelaban** [comment]
After investigating a bit, the memory does not leak anymore when the ContentTemplateSelector in :

```xaml
<ContentControl Content="{Binding}" ContentTemplateSelector="{StaticResource TemplateSelector}"/>
```

It could be related to the content.

**Comment by mterwoord** [comment]
Can you elaborate your message? It seems to me you're missing a word in the first sentence..

**Comment by jeromelaban** [comment]
@mterwoord those are notes, not specifically something you need to act on :)

**Comment by mterwoord** [comment]
I found a (much) simpler memory leak case, which might very well related to this one. You prefer a new issue, or add the sample project here?

**Comment by jeromelaban** [comment]
You can add the sample here, that'll be enough, thanks!

**Comment by mterwoord** [comment]
See attached.

If you run the sample as-is, there's hardly any leakage. (Only real thing that strikes me as odd, is `Windows.UI.Xaml.DependencyPropertyDetails` which is not being reclaimed).
Now open MainPage.xaml, and uncomment line 23 and 25, meaning the previous `TextBlock` is now wrapped in a `Border`. Rerun, and some Skia stuff is leaking, which to me seems related to the border.



Now open MainPage.Xaml, 

[UnoMemory2Clean.zip](https://github.com/unoplatform/uno/files/6399598/UnoMemory2Clean.zip)

**Comment by jeromelaban** [comment]
It's is fixed in `Uno.Core` build 2.4.0-dev.2. Can you add an explicit reference to it in your project and see if this helps ?

**Comment by mterwoord** [comment]
To me it seems that SKPath is still leaking in my second test project. Created in BorderLayerRenderer.InnerCreateLayer

**Comment by jeromelaban** [comment]
Thanks, that's probably a different issue hidden by the first one. We'll keep looking.

**Comment by mterwoord** [comment]
I think the IDisposable created in BorderLayerRenderer.InnerCreateLayer isn't being disposed of correctly. I see a lot of those being kept alive as well.

**Comment by jeromelaban** [comment]
From the sample you provided, I'm not seeing any additional leak after the `Uno.Core` fix. What you're seeing may just be the GC doing its work. The `InnerCreateLayer` really is getting disposed properly, we may be looking at another issue. If you can create another repro that demonstrates the issue, it'll be most helpful.
