### ISSUE TITLE
Framebuffer support on GTK Linux

### ISSUE THREAD

**Issue by DarkArkantos** [unoplatform/uno#5847]
## What would you like to be added:
Support for GTK with frame buffer.

## Why is this needed:
There are a lot of ARM devices for payment in transportation (buses, trains, etc) using NFC and RFID cards, unfortunately, there's no good framework for developing apps for these devices. Some of them are Android or Linux. 
In the case of Linux, the toolkits are quite limited to Qt applications, this is due to the fact that those devices don't use X Window interface to display the content, they are pretty simple in terms of technology compared to a Raspberry Pi, the only way is through frame buffer. As far as I know, this feature is included in the GTK library.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [X] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

It would be awesome to support this!
I have taken a look at most of the well-known cross-platform frameworks based on C# and .NET, and none of them have support for frame buffer. I found Avalonia has support but doesn't include Android.

If this feature is considered will be really appreciated! :)

**Comment by jeromelaban** [comment]
Thanks for the feedback! You may find interesting this exampl;e, which uses the `WriteableBitmap` type: https://github.com/unoplatform/uno/blob/56d3ba98ee6cab055dc8d7c4941ce4494e20e946/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/ImageBrush_WriteableBitmap.xaml.cs#L36

You can provide an arbitrary memory buffer, that will be displayed.

Note that we're working on adding more low-level APIs to improve performance and match what WinUI is providing.

**Comment by DarkArkantos** [comment]
Thank you so much for your early response!
I was checking that fragment, and indeed it seems to be possible. But I wonder if it is possible to redirect the default output to that `WriteableBitMap`, Cuz I assume even if it is implemented this way the main output will still being the X Window. I'll be looking after any progress around this with the new low-level APIs are working on.

So far the output when you try to run it on an ARM Cortex  A9 with Linux is the following:

### When running:

```
./DemoUno.Skia.Gtk 

(DemoUno.Skia.Gtk:994): Gtk-WARNING **: Locale not supported by C library.
    Using the fallback 'C' locale.
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused

(DemoUno.Skia.Gtk:994): Gtk-WARNING **: cannot open display: 
```
### Checking the GTK library installed:

```bash
root@Scv_500:/home/fa/Console/linux-arm# dpkg -s libgtk-3-0
Package: libgtk-3-0
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 6500
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: armhf
Multi-Arch: same
Source: gtk+3.0
Version: 3.18.9-1ubuntu3.2
Provides: gtk3-binver-3.0.0
```

The device is [this one][1].
Maybe this info can be a little of help.

Thank you so much for this great job, it's really appreciated!


[1]:  https://scsoft.com/wp-content/uploads/2019/07/SCV500.pdf

**Comment by jeromelaban** [comment]
Thanks. I probably misunderstood what you meant by framebuffer support. It seems that you need the output of the whole app to an arbitrary framebuffer. At this point, this is not supported and the application needs GTK and an X server (or similar) running.

Would you have an example of application that works this way ?
