### ISSUE TITLE
Unable to set SelectedItem for a ComboBox in an editing template for a DataGridTemplateColumn in WASM

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno#5852]
## Current behavior

I have a DataGrid with a DataGridTemplateColumn where the editing template is a ComboBox.  When I put the cell into edit mode, the ComboBox popup does show.  However, when trying to click an item the popup goes away and no items are selected.

I also noticed we have a custom control in an editing template that shows a popup which exhibits the same behavior.  The popup is closed and selection not committed.

## Expected behavior

I'm able to select an item as in UWP.

## How to reproduce it (as minimally and precisely as possible)

Attaching a test project. 
[App1.Shared.zip](https://github.com/unoplatform/uno/files/6399352/App1.Shared.zip)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jsinsel** [comment]
@jeromelaban This is still happening with Uno.UI.WebAssembly 3.8.0-dev.169.  I'm using Firefox 88.0.1 (can test with another browser if you need). Below is what I'm seeing today.

Column has a value before touching it.
![image](https://user-images.githubusercontent.com/67480815/118819640-87975300-b883-11eb-97f5-f7c304602513.png)

Putting it into edit mode clears the selection.
![image](https://user-images.githubusercontent.com/67480815/118819712-9b42b980-b883-11eb-9314-adca19fb894a.png)

Popup occurs on click.
![image](https://user-images.githubusercontent.com/67480815/118819793-ae558980-b883-11eb-8844-901230a37de3.png)

Clicking an item in the popup doesn't select anything and disables edit mode.
![image](https://user-images.githubusercontent.com/67480815/118819895-c88f6780-b883-11eb-8ddb-375688bbe845.png)

**Comment by jeromelaban** [comment]
@davidjohnoliver does look familiar ?
