### ISSUE TITLE
DataTemplate against an interface defined in resources where DefaultBindMode=OneWay does not update

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno#5857]
## Current behavior

I have a Page/UserControl/ResourceDictionary(with code-behind) that has a DataTemplate with a DataType set to an interface.  The inner controls of that DataTemplate are using x:Bind.  The root XAML container has x:DefaultBindMode=OneWay set so it is expected to default all bindings to OneWay.  This is not working in the DataTemplate.

## Expected behavior

The DataTemplate bindings default to OneWay.  Works in UWP.

## How to reproduce it (as minimally and precisely as possible)

Attaching a sample project. 
[App1.Shared.zip](https://github.com/unoplatform/uno/files/6400258/App1.Shared.zip)

## Workaround

Set `x:DefaultBindMode="OneWay"` on the root element of the `DataTemplate`

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
I've added a workaround to this issue.

**Comment by jeromelaban** [comment]
For details, this bug was fixed during this livestream: https://www.youtube.com/watch?v=SM_RfeO-N-w
