### ISSUE TITLE
Adjust the icon, name of the samples app

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#587]
## I'm submitting a...
- Feature request

## Current behavior
The name and icon of the app is generic and should not be.

**Comment by MartinZikmund** [comment]
May I take this :-) ?

**Comment by MartinZikmund** [comment]
Are there some image assets for Uno that I could use?

**Comment by jeromelaban** [comment]
We have the assets internally for a similar app, It'll mainly be a copy and paste, so we'll take it :) Thanks!

**Comment by MartinZikmund** [comment]
Alrighty :-)

**Comment by jeromelaban** [comment]
You may want to check on gitter, I gave you a issue you could look at.
