### ISSUE TITLE
NuGet package override doesn't work for `Uno.UI.Runtime.Skia.Wpf` assembly

### ISSUE THREAD

**Issue by mterwoord** [unoplatform/uno#5872]
## Current behavior

I was trying to work on a simple code change, but wasn't able to use the crosstargetting_override.props file to build into my nuget packages. 

## Expected behavior

The crosstargetting approach is really neat, as it's easy to change and test things this way.

## How to reproduce it (as minimally and precisely as possible)

Set the nuget override version, and build Uno.UI.sln. Lots of things are updated, but not the Uno.Runtime.Skia.Wpf package.

## Environment

Nuget Package:
- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Master

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [X] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [X] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. Does it work for the Skia.Gtk head ?

**Comment by mterwoord** [comment]
Not sure what I messed up yesterday, but now it seems to work. I'll close this issue.

**Comment by mterwoord** [comment]
I'm reopening.

Building does change the packages, but Wpf targets don't run then. Gtk does.

**Comment by mterwoord** [comment]
It expects a different assembly version.

**Comment by MartinZikmund** [comment]
I think this is working now, can you verify please?

**Comment by mterwoord** [comment]
Sadly I can't/won't test. I decided to tackle my UI requirements differently, and am no longer using Uno.
