### ISSUE TITLE
.NET 6 Mobile support

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#5873]
This issue tracks the support for .NET 6

### Opened Microsoft issues
- https://github.com/xamarin/xamarin-android/issues/6244
- https://github.com/xamarin/xamarin-android/issues/6243
- https://github.com/xamarin/xamarin-android/issues/6700
- https://github.com/xamarin/xamarin-macios/issues/14686
- https://github.com/xamarin/xamarin-macios/issues/14711
- https://github.com/xamarin/xamarin-macios/issues/14835
- https://github.com/xamarin/xamarin-macios/issues/14855
- https://github.com/xamarin/xamarin-macios/issues/14880

### Related issues
- https://github.com/xamarin/xamarin-macios/issues/15675

### Fixed
- ~~Update catalyst excluded pieces once .NET 6 Preview 6 is released~~
- ~~Update net6.0-android Lottie support once support for monoandroidXX.XX backward compatibility is improved~~
- ~~https://github.com/unoplatform/uno/issues/6273~~
- ~~https://github.com/xamarin/xamarin-macios/issues/14065~~
- ~~https://github.com/microsoft/microsoft-ui-xaml/issues/5143~~
- ~~https://github.com/xamarin/xamarin-android/issues/6178~~
- ~~https://github.com/xamarin/xamarin-macios/issues/12426~~
- ~~https://github.com/dotnet/runtime/pull/55681~~
- ~~https://github.com/xamarin/xamarin-android/issues/5896~~
- ~~- iOS VS2022 Windows debugging issue https://developercommunity.visualstudio.com/t/unable-to-deploy-andor-debug-net6-ios-application/1476665~~
- ~~https://github.com/xamarin/xamarin-macios/issues/14812~~

**Comment by Medality** [comment]
Hi,
I see nothing here regarding MSAL's WithUnoHelpers extension, which does nothing on .NET 6/7 Mobile.
Do I need to enter an issue about it? Thanks.

**Comment by nickrandolph** [comment]
> Hi,
> I see nothing here regarding MSAL's WithUnoHelpers extension, which does nothing on .NET 6/7 Mobile.
> Do I need to enter an issue about it? Thanks.

There's no change to the MSAL library from Uno but you do need to update to the latest MSAL library from Microsoft

**Comment by Medality** [comment]
I don't understand as even the MSAL samples call WithParentActivityOrWindow. See here: https://github.com/Azure-Samples/ms-identity-dotnetcore-maui/tree/main/MauiAppWithBroker.
Am I missing something here? I had to call WithParentActivityOrWindow on my .NET 7 Android app as I kept getting an InvalidOperationException with WithUnoHelpers. Thanks for your help.

**Comment by nickrandolph** [comment]
@Medality I'll review uno support for MSAL this week and confirm what's required
