### ISSUE TITLE
[Gallery][WASM] loading time is slow when you first open the app for Canary as compare to Staging.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5875]
## Current behavior

https://user-images.githubusercontent.com/74563602/116744332-2ab52500-a9c8-11eb-81a1-cbf25143a3c3.mp4

## Expected behavior
The  performance to load the app should be better

## How to reproduce it (as minimally and precisely as possible)

1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Check the loading time of the app.
3. Open the link https://unogallery-wasm-staging.azurewebsites.net/
4. Check the loading the time of the app.
5. Compare the time for both the build.
6. Observe that the canary link is taking around 21seconds and Staging link is taking around 9seconds.
7. 

  
Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
This issue is caused by the lack of compression on the site provided by the canary hosting server. We'll have to change to use static apps to work around this.
