### ISSUE TITLE
Prevent build before fast tasks are passing

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#5883]
## What would you like to be added:

To avoid unnecessarily running long-running build, we could make the fast checks a priority - for example the conventional commits - if they fail, they will definitely require a force-push, which means a second run of the build.

## Why is this needed:

Saving up energy ⚡

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

**Comment by mterwoord** [comment]
Added bonus of this is that it frees up build agents for other builds, meaning more effective work can be done.

**Comment by jeromelaban** [comment]
Implemented in recent CI
