### ISSUE TITLE
Please add DataWriter.StoreAsync

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#5892]
## What would you like to be added:
DataWriter.StoreAsync

## Why is this needed:
I'm using it in my app (and I'm porting app to Uno).

## For which Platform:

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by rafaelrmoukc** [comment]
@jeromelaban The issue is open for Android Platform, and u add winrt label. Only to understand, we need that feature on All Plataforms or only on UWP (like native?)

Any tip?

**Comment by jeromelaban** [comment]
This is a generic class, it was opened for android but will likely only have one generic implementation.
