### ISSUE TITLE
[Gallery][MacOS/Skia.Gtk] Scrollbar for `NavigationViewItem` selection is missing and not working.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5904]
## Current behavior
**MacOS**
![scrollbar issue](https://user-images.githubusercontent.com/74563602/116925325-0acf6c80-ac27-11eb-97e0-4f2ad8a21710.png)
**Skia**
![scrollbar missing issue](https://user-images.githubusercontent.com/74563602/116925384-1fac0000-ac27-11eb-9435-6ba1544902b4.png)

## Expected behavior
![scrollbar correct](https://user-images.githubusercontent.com/74563602/116925340-102cb700-ac27-11eb-98b8-dc4d3fed1447.png)

## How to reproduce it (as minimally and precisely as possible)
Open the link https://unogallerycanary.z27.web.core.windows.net/
Click the Burgrer menu and check Scrollbar for NavigationViewItem selection.
Observe that the Scrollbar is missing for Skia
Observe that the Scrollbar is not working for MacOS.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [X] Skia
  - [ ] WPF
  - [X] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: )
- [X] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by ramezgerges** [comment]
For me, this is working fine on https://unogallerycanary.z27.web.core.windows.net/ and on Skia (I've only tested the canaries/dev branch). Can anyone else confirm?

**Comment by jeromelaban** [comment]
@sakshi173 could you verify this again ?

**Comment by sakshi173** [comment]
@jeromelaban and @ramezgerges, I verified this issue is no longer present for Skia.Gtk, I can change status to done.
