### ISSUE TITLE
[Gallery][Skia.GTK] Uno logo is not displaying correctly

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5905]
## Current behavior
![Uno Logo issue new](https://user-images.githubusercontent.com/74563602/116930065-453c0800-ac2d-11eb-974a-d4f3751c7efe.png)

## Expected behavior
![Uno Logo correct new](https://user-images.githubusercontent.com/74563602/116930116-5553e780-ac2d-11eb-8940-563999c930dd.png)

## How to reproduce it (as minimally and precisely as possible)
1. Launch the Uno.Gallry app on Skia.GTK
2. Observe the Uno Logo is not displaying correctly.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [X] Skia
  - [ ] WPF
  - [X] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by MartinZikmund** [comment]
@sakshi173 what is wrong with the GTK version please? Is it low resolution?
