### ISSUE TITLE
log4net ::  ---> System.MissingMethodException [Wasm]

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#5907]
1. Is log4net supposed to be working on Wasm head ? WD is just happy with this. 

![image](https://user-images.githubusercontent.com/43340959/116987111-efb83780-acce-11eb-84eb-4c44d336576e.png)

![image](https://user-images.githubusercontent.com/43340959/116988649-f47deb00-acd0-11eb-9e60-dc3de16fbd57.png)

2. Can I use this method in Wasm ? `FileVersionInfo.GetVersionInfo()`

**Comment by jeromelaban** [comment]
Thanks for the report. This is likely a linker issue, make sure to read this section: https://platform.uno/docs/articles/get-started-wizard.html#runtime-error-no-parameterless-constructor-defined-for-xxxx

**Comment by sigmarsson** [comment]
Yeah, switched the linker off altogether and error vanished. Merci. 

```
  <PropertyGroup>
    <WasmShellILLinkerEnabled>false</WasmShellILLinkerEnabled>
  </PropertyGroup>
```
