### ISSUE TITLE
System.Diagnostics.FileVersionInfo is not supported on Wasm

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#5916]
```
 ---> System.PlatformNotSupportedException: System.Diagnostics.FileVersionInfo is not supported on this platform.
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName) 
```

Is there an alternative of this method available on Wasm ? 

![image](https://user-images.githubusercontent.com/43340959/117038253-b4862a80-ad07-11eb-9582-04e65759ac9e.png)

**Comment by jeromelaban** [comment]
Thanks for the report. This is not a Uno issue, but rather a [.NET Runtime issue](https://github.com/dotnet/runtime). You can file an issue there instead.
