### ISSUE TITLE
[Gallery][MacOS/Skia.GTK] ExpandingBottomSheet, ModalStandardBottomSheet and NavigationView- Endless scrolling on the page and due to that Page look blank.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5919]
## Current behavior
**Skia**
![skia bottomexpandsheet issue](https://user-images.githubusercontent.com/74563602/117050151-08324d00-ace3-11eb-9fd2-3ecaf02e819d.png)
![skia modalstandardbottomsheet issue](https://user-images.githubusercontent.com/74563602/117064979-dcb85e00-acf4-11eb-866e-c95160b3f27d.png)
**MacOS**
![ExpandingBottomsheet endless issue](https://user-images.githubusercontent.com/74563602/117065025-ee016a80-acf4-11eb-8f44-b466b2bbf201.png)
![ModalStandardbottomsheet endless issue](https://user-images.githubusercontent.com/74563602/117065065-f9ed2c80-acf4-11eb-9d2a-edf16d3f9b6f.png)

## Expected behavior
![skia modalstandardbottomsheet correct](https://user-images.githubusercontent.com/74563602/117065189-299c3480-acf5-11eb-9d06-80778884ef55.png)

![skia bottomexpandsheet correct](https://user-images.githubusercontent.com/74563602/117050169-0d8f9780-ace3-11eb-9319-f0ac12d424a0.png)

## How to reproduce it (as minimally and precisely as possible)
1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Click on “ExpandingBottomSheet” option from the Burger menu.
3. Scroll the page down.
4. Observe the page is scrolling endless and due to page looks blank.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [X] Skia
  - [ ] WPF
  - [X] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by francoistanguay** [comment]
Control is deprecated. Being replaced by Drawer.

**Comment by sakshi173** [comment]
As suggested, Control is deprecated. Being replaced by Drawer. closing it.
