### ISSUE TITLE
[Gallery][MacOS] ExpandingBottomSheet and ModalStandardBottomSheet -Toggle button and Open sheet not working at all.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5923]
## Current behavior
![ExpandingBottomsheet issue](https://user-images.githubusercontent.com/74563602/117063634-18522880-acf3-11eb-96b9-c8daa30773e5.png)
![ModalStandardbottomsheet issue](https://user-images.githubusercontent.com/74563602/117063653-1e480980-acf3-11eb-886e-8df13dc9ae68.png)

## Expected behavior
![ExpandingBottomsheet correct](https://user-images.githubusercontent.com/74563602/117063805-58191000-acf3-11eb-894b-3e2cb69b9d8b.png)
![ModalStandardbottomsheet correct](https://user-images.githubusercontent.com/74563602/117063819-5e0ef100-acf3-11eb-9ad8-3d97968530de.png)

## How to reproduce it (as minimally and precisely as possible)
1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "ExpandingBottomSheet" from the "Component" list.
4. Click on "Toggle Minimal Sheet" and "+" sign.
5. Observe that both buttons are not working.
6. OR
7. Click "ModalStandardBottomSheet" from the "Component" list.
8. Click on "Open Sheet".
9. Observe that "Open Sheet" is not opening.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [X] Skia
  - [ ] WPF
  - [X] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [X] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by francoistanguay** [comment]
Control is deprecated. Being replaced by Drawer.

**Comment by sakshi173** [comment]
As suggested, Control is deprecated. Being replaced by Drawer. closing it.
