### ISSUE TITLE
Uno Platform automatic switch from Dark Mode to Light Mode

### ISSUE THREAD

**Issue by jtnumberfive** [unoplatform/uno#5926]
## Current behavior

When iOS automatically switches from Dark Mode to Light Mode or Light Mode to Dark Mode, an Uno Based app does not change to the appropriate mode.  I checked it in Android- and after the mode switched- the app would reload- launch splash screen and then display the correct mode.

## Expected behavior

When iOS changes mode automatically, the app should mirror that change.  

## How to reproduce it (as minimally and precisely as possible)

Launch an app- I was able to reproduce it with the Uno Gallery app- and then switch away from it.  Verify the device is set to automatically change from light mode to dark mode or vice versa.  What for the device to change mode, either reopen the app or switch to the app.  In my experience- about 90% of the time it would stay in whatever mode it was in- not switch to the current mode.  It would do it occasionally.

## Workaround

I don't have a workaround- other than to force close the app and reopen it.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [x] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Uno.UI = 3.8.0-dev.63
Uno.UI.RemoteControl = 3.8.0-dev.63
Microsoft.UI.Xaml = v2.6.0-prerelease.210405001

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
I think we can add a check of the current theme when the window becomes visible (which is a feature which was merged recently 😉)
