### ISSUE TITLE
Switch from Dark Mode to Light Mode or Light Mode to Dark Mode and not all styles are updated correctly

### ISSUE THREAD

**Issue by jtnumberfive** [unoplatform/uno#5927]
## Current behavior

When the app switches from Dark Mode to Light Mode or Light Mode to Dark Mode, not all coloring is updated.

## Expected behavior

When the app switches from Dark Mode to Light Mode or Light Mode to Dark Mode, all styles would update to the correct color as defined in the resource dictionary.

## How to reproduce it (as minimally and precisely as possible)
MainPage.xaml:

`<Page
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:testApp"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:Custom="using:System.Numerics"
    xmlns:toolkit="using:Uno.UI.Toolkit"
    x:Class="sampleApp.MainPage"
    mc:Ignorable="d" 
     Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <Grid Background="{StaticResource SubPageBackground}"  toolkit:VisibleBoundsPadding.PaddingMask="All" >
       <Button x:Name="BackButton" Click="Back_Click" Style="{StaticResource ButtonStyle1}">
        <SymbolIcon x:Name="backArrowIcon" Symbol="Back" Foreground="{StaticResource textForeground}" >
            <SymbolIcon.RenderTransform>
                <CompositeTransform ScaleX="1.2" ScaleY="1.2"/>
            </SymbolIcon.RenderTransform>
        </SymbolIcon>
        </Button>
    </Grid>
</Page>
`

Resource Dictionary:
`
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" 
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:testApp.Shared">

    <ResourceDictionary.ThemeDictionaries>
        <ResourceDictionary x:Key="Dark">
            <SolidColorBrush x:Key="SubPageBackground" Color="#FF3F3F3F"/>
            <SolidColorBrush x:Key="ApplicationPageBackgroundThemeBrush" Color="#FFF2F2F2"/>
            <SolidColorBrush x:Key="textForeground" Color="orange"/>
        </ResourceDictionary>
        <ResourceDictionary x:Key="Light">
            <SolidColorBrush x:Key="SubPageBackground" Color="#FFEEEEEE"/>
            <SolidColorBrush x:Key="textForeground" Color="Blue"/>
            <SolidColorBrush x:Key="ApplicationPageBackgroundThemeBrush" Color="#FFF2F2F2"/>
        </ResourceDictionary>
    </ResourceDictionary.ThemeDictionaries>
</ResourceDictionary>
`

## Workaround

Minimize applying items like Foreground and Background in the XAML.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [x] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version:16.9.4 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

I was not able to get the first batch of code to display properly.

**Comment by davidjohnoliver** [comment]
In your code, you're assigning resources using the `StaticResource` markup extension. You must use the [`ThemeResource` markup extension](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/themeresource-markup-extension) if you want the assigned resources to update when the theme changes.

If you use the following code:
```xml
	<Grid Background="{ThemeResource SubPageBackground}"
		  toolkit:VisibleBoundsPadding.PaddingMask="All">
		<Button x:Name="BackButton">
			<SymbolIcon x:Name="backArrowIcon"
						Symbol="Back"
						Foreground="{ThemeResource textForeground}">
				<SymbolIcon.RenderTransform>
					<CompositeTransform ScaleX="1.2"
										ScaleY="1.2" />
				</SymbolIcon.RenderTransform>
			</SymbolIcon>
		</Button>
	</Grid>
```

you should see the colors updating when the system changes. Note that UWP and Uno behave the same way in this regard.

**Comment by jtnumberfive** [comment]
I appreciate your help- I made the change you mentioned and it fixed almost everything.  The one area it did not fix is the Uno Material Card.  I have a Path with a fill now set to a ThemeResource - but it does not change color.  Everything else that was not changing is now.   For Example: `        <material:Card HeaderContent="Messaging"
               SubHeaderContent="Message others"
               Style="{ThemeResource MaterialOutlinedCardStyle}"
               MediaContent="placeholder"        
               Foreground="{ThemeResource SubPageTextColor}"
               Background="{ThemeResource cardBackground}"
               PointerExited="messagePageClick">
            <material:Card.MediaContentTemplate>
                <DataTemplate>
                    <Path Fill="{ThemeResource MaterialOnSurfaceBrush}" HorizontalAlignment="Center" VerticalAlignment="Center" Margin="10" Data=""/>
                 </DataTemplate>
            </material:Card.MediaContentTemplate>
        </material:Card>
`
Should I open a bug in Uno.Material for this- or is there something I am missing.

**Comment by davidjohnoliver** [comment]
@jtnumberfive It depends, does it change color in UWP, but not iOS/Android? Or does it fail to change color in UWP as well?

**Comment by jtnumberfive** [comment]
That is a good question.  I do not have a uwp had in my project to test with.

________________________________
