### ISSUE TITLE
[iOS] Image control alignments don't match UWP/Android/Wasm

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#593]
## Current behavior
Image control alignments on iOS don't match UWP/Android/Wasm

## Expected behavior
Image control alignments on iOS must match UWP/Android/Wasm

## Minimal reproduction of the problem with instructions
See UITests for the Image control that are available in the SamplesApp.

## Environment

```
Nuget Package: Uno.UI 1.43.0-dev.858

Affected platform(s):
- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [X] 2017 Preview (version: 15.9.0 Preview 4.0)
- [ ] for Mac (version: )

Relevant plugins
- [X] None
```

**Comment by jeromelaban** [comment]
Was addressed by a recent PR

**Comment by agneszitte-nventive** [comment]
Great news 👍 Thanks !!
