### ISSUE TITLE
[SwipeControl] The content layout does not render properly on Android and iOS when swiping the control

### ISSUE THREAD

**Issue by YGuerin** [unoplatform/uno#5930]
## Current behavior

When swiping the control, the left/right buttons and the item content overlap each others

## Expected behavior

Left and right buttons should appear under the content

## How to reproduce it (as minimally and precisely as possible)

[SwipeControlSample.zip](https://github.com/unoplatform/uno/files/6424980/SwipeControlSample.zip)
Remove the Border around the content template in the MainPage.xaml (line 45)

## Workaround

Add a border as the first child of the SwipeControl's content

## Environment

Nuget Package: default packages shipped in a new Uno app

Nuget Package Version(s): 3.7.3

Affected platform(s):

- [X] iOS
- [X] Android
- [ ] ~~WebAssembly~~
- [ ] ~~WebAssembly renderers for Xamarin.Forms~~
- [ ] ~~macOS~~
- [ ] ~~Skia~~
  - [ ] ~~WPF~~
  - [ ] ~~GTK (Linux)~~
  - [ ] ~~Tizen~~
- [ ] Windows
- [ ] ~~Build tasks~~
- [ ] ~~Solution Templates~~

IDE:

- [X] Visual Studio 2019 (version: 16.9.4)

## Anything else we need to know?

It's better if it's released with #5929 in a single version but this one is less critical since we have a workaround for it. Still not ideal.

**Comment by francoistanguay** [comment]
Been refactored.
