### ISSUE TITLE
support remobjects c# toolchain to android

### ISSUE THREAD

**Issue by cesarchefinho** [unoplatform/uno#5931]
What would you like to be added:

    support remobjects c# toolchain to android
 in order to generate full java bytecode for android
 and speed up application prtformance bypassing 
the cost of marshaling from c# to java. also
 remobject c# call android sdk directly
 (because it igenerate java bytecode) eliminating
 the need to use xamanin.android and making 
app smaller (one softwre layer less)

see

https://www.elementscompiler.com/elements/hydrogene/

## Why is this needed:

to obtain true native performance without jni botlenecs

## For which Platform:

- [ ] Android

**Comment by jeromelaban** [comment]
Thanks for your suggestion. 

We're not in the position to be able to change the underlying support for interop mechanisms.

**Comment by cesarchefinho** [comment]
> Thanks for your suggestion.
> 
> We're not in the position to be able to change the underlying support for interop mechanisms.

you dont need to change interop, only need to recompile using c# remobjects compiler because it already generate java bytecode and intetop doesnet exist. uyiu need only to in this compiler path call sirectly android sdk in c# and not xamarin.android api.
