### ISSUE TITLE
[Gallery][MacOS] `Flyout` - Any button for flyout like 'Flyout', 'Open', 'Options' 'Help' are not working for Material and Fluent.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5935]
## Current behavior
![flyout issue](https://user-images.githubusercontent.com/74563602/117169862-7df7f080-ad97-11eb-82a4-5dfab60f9aac.png)

## Expected behavior
![flyout correct](https://user-images.githubusercontent.com/74563602/117169885-82240e00-ad97-11eb-92bc-896c36b3cde6.png)
![flyout correct2](https://user-images.githubusercontent.com/74563602/117169898-85b79500-ad97-11eb-9b51-7e28515dd818.png)
![flyout correct3](https://user-images.githubusercontent.com/74563602/117169920-894b1c00-ad97-11eb-9cc6-fb460a011d0f.png)
![flyout correct4](https://user-images.githubusercontent.com/74563602/117169935-8cdea300-ad97-11eb-9e1a-cd1ac470c1d4.png)

## How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "Flyout" from the "Component" list.
4. Click on any button  like 'Flyout', 'Open', 'Options' 'Help'.
5. Observe that both buttons are not working.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [X] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
