### ISSUE TITLE
[Gallery][MacOS]Password box and Textbox - Not able to type text and multiline text is not displaying for Material and Cupertino,  and for Fluent double border line is present.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5937]
## Current behavior

https://user-images.githubusercontent.com/74563602/117189720-81e23d80-adac-11eb-9668-164ddb1c535b.mov

## Expected behavior
Able to type text for all the options properly.

## How to reproduce it (as minimally and precisely as possible)
Open Uno Gallery APP
Click Burger Menu on the left top right.
Click "PasswordBox" from the "Component" list.
Try to type text for the Default field.
Observe that not able to type text for Material and Cupertino and for Fluent double border line is present and also the Reveal button is missing.
OR
Click "TextBox" from the "Component" list.
Try to type text for the Default field.
Observe that not able to type text for Material and Cupertino and for Fluent double border line is present 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [X] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by OmarForever** [comment]
Is there any workaround for this issue? I would really like to use Material as the base of my application theme but currently experiencing this issue which essentially renders it unusable for MacOS.

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
