### ISSUE TITLE
[Android] Switching theme in Android settings leaves NavigationViewItems in bad state.

### ISSUE THREAD

**Issue by chingucoding** [unoplatform/uno#5939]
## Current behavior

When starting the app, opening Androids Settings and switching the theme, and then reopening the app (do not close the app, just switch to a different app), the NavigationViewItems' MenuItems have the wrong text color and are very difficult to read:

![Screenshot of Android app with navigation exposing bright text on bright background](https://user-images.githubusercontent.com/16122379/117193529-40b95000-ade3-11eb-8c05-2087d80a44d3.png)

This issue only seemed to happen on Android; WASM and UWP don't repro this.

## Expected behavior

NavigationViewItems update correctly.

## How to reproduce it (as minimally and precisely as possible)

Unfortunately, I don't have a repro app to share as I wasn't able to isolate this issue in a repro app. The bug only seemed to occur in the "bigger" context of the entire app.

## Workaround

None so far.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia 3.7.3
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [x] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl 3.7.3
- [x] Microsoft.Toolkit.Mvvm: 7.0.1
- [x] Uno.UniversalImageLoader: 1.9.33
- [x] Xamarin.Essentials: 1.6.1
- [x] Xamarin.Forms: 5.0.0.2012
- [x] ZXing.Net.Mobile: 2.4.1
- [x] ZXing.Net.Mobile.Forms: 2.4.1
- [x] sqlite-net-pcl: 1.7.335

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
@davidjohnoliver may be fixed by one of your recent updates?

**Comment by davidjohnoliver** [comment]
> @davidjohnoliver may be fixed by one of your recent updates?

There's a chance that https://github.com/unoplatform/uno/pull/5896 will have fixed it, but those changes are mostly Popup-specific so I'm not optimistic. Other than that I can't think of relevant changes that wouldn't be in 3.7.
