### ISSUE TITLE
Support remobjects c# toolchain

### ISSUE THREAD

**Issue by cesarchefinho** [unoplatform/uno#5962]
## What would you like to be added:

   Investigate use of remobjects c#  

  ( see https://www.elementscompiler.com/elements/hydrogene/ )

   Remobjects c# toolchain compiles to windows, Linux, macos, ios and for android

## Why is this needed:

  Because remobjecta compile directly to plarform native without aot, vm, jit or even interop and in android performance will be better than xamarin.android because compiled code is lready native java bytecode 

## For which Platform:

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report. As I mentioned in https://github.com/unoplatform/uno/issues/5931, this is not a product that we are willing to integrate at this point.

However, if you have an issue using this in your application, please open an other issue with a reproduction sample with the Uno app templates. Thanks !
