### ISSUE TITLE
[Gallery][Android/Wasm] StandardBottomSheet - Sheet header is opening only first time then it is not opening.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5973]
## Current behavior

https://user-images.githubusercontent.com/74563602/117671804-31d1f500-b177-11eb-860a-2d334adc4c38.mp4

## Expected behavior
The standardBottomSheet opens for every click and Drag.

## How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "StandardBottomSheet" from the "Component" list.
4. Click on the "ArrowSign" on the Sheet Header and drag on top.
5. Observe that the Sheet Header is opening first time.
6. Repeat 4th step.
7. Observe that this time sheet is not opening.

## Environment

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Canary Build:
https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=28308&view=results

**Comment by francoistanguay** [comment]
Control is deprecated. Being replaced by Drawer.

**Comment by sakshi173** [comment]
As suggested, Control is deprecated. Being replaced by Drawer. closing it.
