### ISSUE TITLE
XAML generation fails for `Binding.TargetNullValue` using `ImageSource`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#5989]
## Current behavior

When `TargetNullValue` of a `Binding` in XAML is set as a `ImageSource`, the XAML generation fails in Uno:

```
c35.SetBinding(global::Windows.UI.Xaml.Controls.Image.SourceProperty, 
   new Windows.UI.Xaml.Data.Binding{ 
        Path = @"BackgroundImagePath"/* Windows.UI.Xaml.PropertyPath/Windows.UI.Xaml.PropertyPath, BackgroundImagePath, Binding/Path */, 
        Mode = global::Windows.UI.Xaml.Data.BindingMode.OneTime/* Windows.UI.Xaml.Data.BindingMode/Windows.UI.Xaml.Data.BindingMode, OneTime, Binding/Mode */, 
        TargetNullValue = #Error // ImageSource could not be found. });
```

The problem might be a general one though, not limited to `ImageSource`.

## Expected behavior

Should generate valid code.

## How to reproduce it (as minimally and precisely as possible)

```
<Image VerticalAlignment="Center" HorizontalAlignment="Center" Stretch="UniformToFill" Opacity="0.8">
    <Image.Source>
        <Binding Path="BackgroundImagePath" Mode="OneTime">
            <Binding.TargetNullValue>
                <ImageSource>/Assets/SampleBackgrounds/BlankBackground.png</ImageSource>
            </Binding.TargetNullValue>
        </Binding>
    </Image.Source>
</Image>
```

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): latest

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by carldebilly** [comment]
I don't know of the ['[TypeConverter]'](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Media/ImageSource.cs#L24) will also be used if the `[ContentProperty]` is not defined...

**Comment by Youssef1313** [comment]
This doesn't seem specific to `TargetNullValue`. The following code works only on UWP:

```xml
<Page
    x:Class="Issue5989.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Issue5989"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <Image>
            <Image.Source>
                <ImageSource>/Assets/StoreLogo.png</ImageSource>
            </Image.Source>
        </Image>

    </StackPanel>
</Page>

```

It doesn't generate any compilation error. But the generated code just does `new ImageSource()` without setting an actual image.

**Comment by jeromelaban** [comment]
Interesting. A unit test would be interesting to validate that scenario. The generator is likely not drilling into `ImageSource` default content. It's likely that there's either a implicit converter, or a Content attribute that's missing.
