### ISSUE TITLE
ColorPicker issues in WASM

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno#5992]
## Current behavior

Add a `<ColorPicker>` to any sample project. The following occurs in WASM:
1) The color spectrum does not display even though you can click on it.
2) The track bar is not visible even though you can interact with it if you know where to click.
3) When used in a popup, opening the popup after the first time will not let you interact with the control.

![image](https://user-images.githubusercontent.com/4174207/117995280-329d8f00-b30f-11eb-8461-3c73e52ddccf.png)

## Expected behavior

Should be able to see the color spectrum and track bar.  Should be able to interact with it even when shown multiple times in a popup.

## How to reproduce it (as minimally and precisely as possible)

Attaching a sample project. 
[App1.Shared.zip](https://github.com/unoplatform/uno/files/6466633/App1.Shared.zip)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by francoistanguay** [comment]
@robloo Any of this rings a bell? Should it work? Not yet implemented?

**Comment by robloo** [comment]
@francoistanguay @jsinsel The ColorPicker was only tested to work with Android and iOS at the time. There is a known issue in Uno where image source invalidation doesn't work (at least this is the best theory). If you set an ImageBrush's ImageSource to a new WritableBitmap and then that WritableBitmap is updated asyncronously later, updates will be ignored and won't ever display. This means the color spectrum is never visible in some cases. For some reason correctly handling this source invalidation was only implemented on a few platforms. ImageBrush/ImageSource likely needs a big refactoring on all platforms as this code is inconsistent and quite messy.

The issue with the slider backgrounds not being visible may be similar. Although, I've seen evidence there has been regressions with controls derived from Slider. No idea what may be going on with Popup. Personally, I've never worked with the WASM head.

Some key pieces of code to look at:

Code where the `WriteableBitmap` representing the ColorSpectrum is is created. This is done asynchronously and may occur after the `WriteableBitmap` was already added to an `ImageBrush`/`ImageSource`.

https://github.com/unoplatform/uno/blob/e1f887cae12e3f9eb763fd9df13e1d83e23a0586/src/Uno.UI/Microsoft/UI/Xaml/Controls/ColorPicker/ColorSpectrum.cs#L1158-L1166

Code where the `WriteableBitmap` is set as the `ImageSource` of an `ImageBrush` and then the `ImageBrush` is set as the Fill of the spectrum `Rectangle` itself.

https://github.com/unoplatform/uno/blob/e1f887cae12e3f9eb763fd9df13e1d83e23a0586/src/Uno.UI/Microsoft/UI/Xaml/Controls/ColorPicker/ColorSpectrum.cs#L1601-L1609

I do not understand fully how changes are propagated by Uno itself. However, `WriteableBitmap`, `Image`, `ImageBrush` and `ImageSource` are all involved.

**Comment by robloo** [comment]
@Xiaoy312 

 1. I've noticed some regressions in sliders in newer versions of Uno, they don't seem to work at all if you derive from them new controls. 
 2. Image invalidation is still an issue and WASM may still not fully support WriteableBitmap. This affects the Spectrum and Sliders both.
 3. On other platforms, such as Android, interaction with the spectrum has also regressed. It is usually not possible to update the color by pressing on the spectrum.
 4. > Luminosity Slider tooltip is literally "Value %1!u!"
 
    ** This was a known issue** with the string formatting called out in the original PR: https://github.com/unoplatform/uno/pull/3955  (Question 1 at the end of the issue description). @MartinZikmund since then found a helper method that seems to automatically do the conversion. I can't find that comment at the moment to know which method he was talking about specifically but it should be a simple code update. We don't want to modify the WinUI strings themselves or its just going to break in the future.

 5. > ColorSpectrum dragging tooltip (nearest known color name) is missing
     
    Again, this was called out in the original PR. It is using `ColorHelper.ToDisplayName()` which isn't implemented in Uno. The algorithm to implement it is unknown and non-public. There is conditional code built into the upstream WinUI source to disable this. I used this functionality to disable it since Uno does not support it: https://github.com/unoplatform/uno/blob/a2cfd234254709d280316f5067743d8995330c3d/src/Uno.UI/Microsoft/UI/Xaml/Controls/ColorPicker/ColorSpectrum.cs#L173. https://github.com/unoplatform/uno/blob/a2cfd234254709d280316f5067743d8995330c3d/src/Uno.UI/Helpers/WinUI/DownlevelHelper.cs#L8 **Additionally, this functionality has been removed in WInUI 3 releases so I expect Uno should keep it disabled indefinitely.**

I have given up fixing all the related, secondary issues and unsupported features in Uno to get the ColorPicker to work correctly on all platforms. However, I still think the ported code is good and you won't find any issues there (it was well tested on UWP after the C++ -> C# conversion, and then well tested again on Android at the time). If you need help with the ColorPicker code specifically though I will support there. For example, I can take responsibility for number 4 but it will be a while before I get around to it.

**Comment by Xiaoy312** [comment]
![20210813 wasm color picker](https://user-images.githubusercontent.com/2359550/129427068-ecc1fe00-311f-4259-adce-1b8dc9ead090.gif)

**Comment by robloo** [comment]
@Xiaoy312 Awesome!

Note that there is a bug in the gradient (you might have fixed that already in the PR as you were adjusting code in that area). However, that is the same bug that existed in iOS.

 > The slider background gradient origins are somehow incorrect. There is a bug in iOS here it looks like as the gradient should not have a diagonal slant to it -- should be perfectly uniform horizontally.

https://github.com/unoplatform/uno/pull/3955#issuecomment-699069631
