### ISSUE TITLE
[WASM][Android] Expander issues? I'm getting a blank screen.

### ISSUE THREAD

**Issue by IsmailHassani** [unoplatform/uno#6003]
## Current behavior

If i run the UWP head i get the right UI with the bladeview i'm using. This bladeview uses the expander control from the Microsoft Toolkit.
When i run the WASM or Android head these pages are blank and i get an exception in the browser console:
![image](https://user-images.githubusercontent.com/7172716/118167989-9f0bb180-b427-11eb-887f-3248d0d0d798.png)

## Expected behavior

The UI should be the same as the UWP head.
Initially this was the case in older Uno versions.

## How to reproduce it (as minimally and precisely as possible)
[Repro.zip](https://github.com/unoplatform/uno/files/6474379/Repro.zip)
The actual sample is located under samples/ISynergy.Framework.UI with the corresponding heads

## Environment
Nuget Package:

- [X ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ X] Android
- [ X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ X] Visual Studio 2019 (version: 16.9.5)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
Thank you for the report. 

Can you make an isolated repro and attach it to the issue? Using a larger app can make the issue more difficult to diagnose. Thanks!

**Comment by IsmailHassani** [comment]
[WASM] results in a blank page.
![image](https://user-images.githubusercontent.com/7172716/118168666-61f3ef00-b428-11eb-8907-70b8d1c8ac72.png)

[UWP] As it should look.
![image](https://user-images.githubusercontent.com/7172716/118168825-910a6080-b428-11eb-94d1-819d131c0994.png)

**Comment by IsmailHassani** [comment]
> Thank you for the report.
> 
> Can you make an isolated repro and attach it to the issue? Using a larger app can make the issue more difficult to diagnose. Thanks!

I'll trim the solution back to the base projects and attach it as zip.

**Comment by jeromelaban** [comment]
Thanks again. Yet, it's still not a straigt-to-the-point repro :(

A good repro is a standalone application that shows exactly what the issue is. In that context, **create a new Uno App from the templates, add the xaml a code for the repro** and attach it to the issue. Larger repros often lead to searching what the relevant code is, which may not be easy when there's too much code.

**Comment by Xiaoy312** [comment]
I didnt get to run the sample since it was missing the .sln file, but I did notice something that could cause the issue:
```xml
    <Style TargetType="c:BladeItem">
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="c:BladeItem">
                        <ContentPresenter x:Name="ContentPresenter"
                                          Grid.Row="1"
                                          VerticalAlignment="Stretch"
                                          Background="{TemplateBinding Background}"
                                          Visibility="{TemplateBinding IsOpen}" />
```
The `ContentPresenter` could be missing these lines:
```xml
                            Content="{TemplateBinding Content}"
                            ContentTemplate="{TemplateBinding ContentTemplate}"
                            ContentTemplateSelector="{TemplateBinding ContentTemplateSelector}"
```

**Comment by IsmailHassani** [comment]
@Xiaoy312 You're idd right. I stripped away too much.
This is the runnable one.
[Repro.zip](https://github.com/unoplatform/uno/files/6478879/Repro.zip)

**Comment by IsmailHassani** [comment]
@jeromelaban I'll try to create a simpler project. ;)

**Comment by IsmailHassani** [comment]
I fixed this issue by replacing my own BladeView implementation to that of the Uno Microsoft Toolkit package.
