### ISSUE TITLE
[WASM] In .Net 5, cannot get ColumnDefiniton.ActualWidth from star widths or immediately after changing

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#6009]
## Current behavior

In WASM you cannot retrieve the ActualWidth property for a ColumnDefinition immediately after it has changed.  This may be desired for acquiring new widths from columns using Star widths after grid has been resized.

## Expected behavior

ActualWidth should be available immediately, as in UWP and preceding versions of .net

## How to reproduce it (as minimally and precisely as possible)

Launch the attached project in Uwp and observe that clicking either button reports actual column widths.  Launch in WASM and observe that the button which resizes columns immediately before checking width reports 0 for size, while the button that does not resize reports correctly.

[ColumnDefinitions.zip](https://github.com/unoplatform/uno/files/6480743/ColumnDefinitions.zip)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.8.0-dev.165
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by DierkDroth** [comment]
@jeromelaban this is the latest .NET5 show stopper...

**Comment by jeromelaban** [comment]
Thanks for the update. Note that this issue is very likely to affect `netstandard2.0` as well.

**Comment by peternary** [comment]
Ran a quick test and this is affecting netstandard2.0 code now.  However, verified in an existing project that as of Uno.UI.WebAssembly version 3.7.4 this was working.

**Comment by DierkDroth** [comment]
@jeromelaban is this expected or a regression which would be addressed soon?

**Comment by jeromelaban** [comment]
@DierkDroth is not expected, we're working on fixing it. 

FYI, we've aligned the Grid control code with WinUI's codebase, fixing a large volume of edge-cases bugs and performance issues, but doing so has introduced a few others.

**Comment by DierkDroth** [comment]
@jeromelaban excellent, thanks! Looking forward to the fix...

**Comment by davidjohnoliver** [comment]
> ActualWidth should be available immediately, as in UWP and preceding versions of .net

@peternary Thanks for the report, the regression will be fixed by https://github.com/unoplatform/uno/pull/6033 .

Just pointing out though that the `ActualWidth` that is immediately available on UWP, and on Uno once fixed, is the _old_ `ActualWidth` value, prior to the `Width` being changed. The new `ActualWidth` value which reflects the updated `Width` will not be available until after the `Grid` is re-measured. You can notice this in the sample you supplied. Wanted to make sure you're aware of this as it may have implications depending on what you're trying to do.
