### ISSUE TITLE
Windows.UI.Xaml.Markup.ContentProperty

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#6010]
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="5.0.2" />
    <PackageReference Include="Ninject" Version="3.3.4" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.1.0-dev.1" />
    <PackageReference Include="Uno.WinUI.WebAssembly" Version="3.8.0-dev.142" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="3.8.0-dev.142" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="2.1.0" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="2.1.0" />
  </ItemGroup>
```

Is the class `ContentPropertyAttribute` supposed to be located in any of these NuGet packages ?

**Comment by MartinZikmund** [comment]
In case of WinUI, the attribute is located in `Microsoft.UI.Xaml.Markup` (see [docs](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.markup.contentpropertyattribute?view=winui-3.0)).

**Comment by sigmarsson** [comment]
@MartinZikmund , ohh yeah it was the UWP namespace. MY error.

Btw, what shall i do to access the helper methods like the one depicted ?

Though it requires `Uno.Extensions` ns and Uno.Core pkg but to no avail. I building a Wasm head. 

![image](https://user-images.githubusercontent.com/43340959/118377298-addf9900-b5cc-11eb-9506-d711bc6dae5e.png)

**Comment by MartinZikmund** [comment]
Closing this in favor of #6017
