### ISSUE TITLE
Gain access to helper methods in Wasm

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#6017]
## On which page?
https://qa.website.platform.uno/docs/articles/interop/wasm-javascript-1.html
## What's wrong?
Please describe better how to gain access to helper methods. The ns Uno.Extensions is mentioned but that wasn't helping to make this.SetHtmlContent() method visible.

**Comment by MartinZikmund** [comment]
The API is available in the `Windows.UI.Xaml` namespace, have you tried adding it with `using`?

https://github.com/unoplatform/uno/blob/master/src/Uno.UI.Runtime.WebAssembly/Xaml/UIElementWasmExtensions.cs

**Comment by sigmarsson** [comment]
Yes. Now it is okay. The Studio ought to be in a better synergy with the SDK as for intellisense, output window, build errors etc. 

Thanks.
