### ISSUE TITLE
Issue with calendar picker not appearing.

### ISSUE THREAD

**Issue by davidbuckleyni** [unoplatform/uno#6018]
I love the idea of Uno and of course the future Maui but when Uno is meant to be mature and a simple date picker test fails I don't no please find steps below.

## Current behaviour
 Build a sample application with just a slider label and a button add a date picker in for good mesure

## Expected behavior

Date picker should display on all platforms.

## How to reproduce it (as minimally and precisely as possible)

https://github.com/davidbuckleyni/TestApp

## Workaround
 None that I no off

## Environment

Andriod UWP Appears to work ok just andriod issue with.

Nuget Package:

 This is a file new project basically no other nugets added

Nuget Package Version(s):
Andriod and windows only two I could test.
Affected platform(s):

- [ ] iOS
- [x ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [X ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:
Microsoft Visual Studio Community 2019 Preview
Version 16.10.0 Preview 2.1
VisualStudio.16.Preview/16.10.0-pre.2.1+31220.234
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA931
Microsoft Visual C++ 2019

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.10.341.63941
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.10.341.63941
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.10.341.63941
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.10.341.63941
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.10.0-2.21203.6+5f00f4d6ffb242a337e21a196aab0593891e430e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40405.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.10 (34b16bc)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2120507+b9076c2c2098fb1f4bac21342cff9a07bcbbc277
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62103.10080
Microsoft SQL Server Data Tools

Syncfusion ASP.NET Core (Essential JS 1) Project Templates   19.1.0.54
Provides project templates for creating an ASP.NET Core Web Application using Syncfusion Essential JS 1 components.

Syncfusion Xamarin Project Templates   13.4.0.53
A multi-project template for building iOS, Android, and Windows apps using Syncfusion Xamarin components.

Syncfusion Xamarin Toolbox   16.2.0.19
Syncfusion Essential Studio for Xamarin Toolbox Visual Studio extension.

Syncfusion.VSExtension.Troubleshooter   19.1.0.54
Add-in for Troubleshooting the Syncfusion projects.

SyncfusionMenu Extension   1.0
SyncfusionMenu Visual Studio Extension Detailed Info

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30324.2001
TypeScript Tools for Microsoft Visual Studio

UnoPlatformPackage Extension   1.0
UnoPlatformPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.10.0-2.21203.6+5f00f4d6ffb242a337e21a196aab0593891e430e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.10.0-beta.21201.8+e3f9d330035af18d6350eed6f787de114119c537
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.10.000.103 (d16-10-p2@ad1b1bb)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.76 (remotes/origin/c12e77e7a755a2f14b3b1780e7ed7b114c8963c4@c12e77e7a)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.3 (7f1bfbb)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.99.192 (main/a9a7190)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: eb4c311
    Java.Interop: xamarin/java.interop/main@a3de91e
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.2@afa0437
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@237642c

Xamarin.iOS and Xamarin.Mac SDK   14.17.2.4 (62151a4df)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by MartinZikmund** [comment]
`CalendarDatePicker` is indeed not yet supported, but it is currently being worked on. The control itself is very complex (especially to properly handle globalization), which is the reason it was not supported yet. Support is tracked here, it will be updated as soon as support is merged https://github.com/unoplatform/uno/issues/3750.

As a very temporary workaround, you should be able to use `DatePicker` control, which was added recently.
