### ISSUE TITLE
Storyboard Duration not honoured for RepeatBehavior="Forever" in WASM

### ISSUE THREAD

**Issue by stevozilik** [unoplatform/uno#6028]
## Current behavior
(Color)Animation inside Storyboard never completes even though the Storyboard Duration is elapsed ands hould terminate the animation
in WASM

## Expected behavior
(Color)Animation stops playing when Storyboard Duration interval elapsed, like in UWP

## How to reproduce it (as minimally and precisely as possible)
Same code as the Samples:
https://github.com/unoplatform/uno/blob/master/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Animation/ColorAnimation_Fill.xaml

with:
```
<Storyboard x:Name="colorStoryboard" Duration="00:00:02">
    <ColorAnimation Duration="00:00:01"
        RepeatBehavior="Forever"
		Storyboard.TargetName="TargetRectangle"
		Storyboard.TargetProperty="(Shape.Fill).(SolidColorBrush.Color)"
		From="Orange"
		To="Brown" />
</Storyboard>
```

## Environment

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by Youssef1313** [comment]
I'm seeing the same behavior in UWP and Wasm. @stevozilik  Can you elaborate more please?

![issue6028](https://user-images.githubusercontent.com/31348972/131332745-c724132c-7da9-444c-8e53-2224a23eb19a.gif)

**Comment by jeromelaban** [comment]
This issue is fixed, the event is now raised.
