### ISSUE TITLE
[iOS] DatePicker MaxYear property ignores month and day.

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#6034]
## Current behavior
Only the year in `DatePicker.MaxYear` is used when limiting the max date on `UIDatePicker`.

![current_public](https://user-images.githubusercontent.com/17461593/118695486-421f4b00-b7db-11eb-92e4-3c4400ac1658.gif)

## Expected behavior
In previous version, the `UIDatePicker` used to block month and day as well.
![expected_public](https://user-images.githubusercontent.com/17461593/118695860-a6daa580-b7db-11eb-86a8-d7931916ce7c.gif)

## How to reproduce it (as minimally and precisely as possible)

- Download this sample [DatePickerMaxDateSample.zip](https://github.com/unoplatform/uno/files/6503099/DatePickerMaxDateSample.zip)
- Deploy on iOS
- Click on the datepicker
- Select any date in the future `MaxYear = DateTimeOffset.Now`

## Workaround
N/A

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.8.0-dev.169

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
@carldebilly isn't this expected ?

**Comment by carldebilly** [comment]
Yep.  That's the expected result as it's exactly the behavior on Windows.

To have min/max dates, you'll need to use CalendarDatePicker/CalendarView: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.calendardatepicker

**Comment by jeromelaban** [comment]
@takla21 is this a regression from your end, or something you'd expect to work ?

**Comment by takla21** [comment]
@jeromelaban it's actually a regression for iOS. It used to work (blocking days and month) with the previous uno version we were using (3.1.29)

@carldebilly The thing is that it's does block days and month on android. I've updated the sample on android to the same version as android here [DatePickerMaxDateSample.zip](https://github.com/unoplatform/uno/files/6511348/DatePickerMaxDateSample.zip). So does it means that it's a bug on android?

![android](https://user-images.githubusercontent.com/17461593/118879518-d2828c00-b8be-11eb-8866-9e9a7236ce06.gif)

**Comment by carldebilly** [comment]
Yep it's a bug :-).

It should be possible to set a feature flag to bring back the old behavior.

To be honest, the "native DatePicker" is a lot closer to `CalendarDatePicker` than `DatePicker` itself. I think they should come back as _native pickers for `CalendarDatePicker`_ instead...

**Comment by carldebilly** [comment]
Duplicate of https://github.com/unoplatform/uno/issues/5575

**Comment by takla21** [comment]
Well, it seems that it's not quite implemented yet https://github.com/unoplatform/uno/issues/3750

**Comment by MartinZikmund** [comment]
Closing as duplicate
