### ISSUE TITLE
UNO0001: undeserved  ExecuteScriptAsync

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#6035]
I think the scripts are indeed invoked in spite of this warning.

![image](https://user-images.githubusercontent.com/43340959/118823825-97318e80-b8b9-11eb-9515-e85b2685e97f.png)

**Comment by jeromelaban** [comment]
Thanks for the report. WebView2 is not implemented at this time, this method is not as well. See #4758 for tracking
