### ISSUE TITLE
Compilation error with Uno Prism template

### ISSUE THREAD

**Issue by Leon99** [unoplatform/uno#6042]
## Current behavior

`Shell.xaml(10,5): XamlCompiler error WMC0010: Unknown attachable member 'ViewModelLocator.AutoWireViewModel' on element 'ContentControl'`

## Expected behavior

No compilation errors

## How to reproduce it (as minimally and precisely as possible)

Create a Uno Prism project from a supplied template

## Environment

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [x] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.6)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. Can you detail how you created your prism project (which command specifically) ?

**Comment by Leon99** [comment]
Not sure what you mean by "which command specifically" @jeromelaban. I created a new project in VS with the Uno Prism template. I think I selected only UWP and WASM targets. I can send you the generated project if you want.

**Comment by jeromelaban** [comment]
Thanks for the update. There's no "Uno Prism" template available from VS directly, unless you installed the `dotnet new` templates as well. Can you show a screenshot of the option you selected ?

**Comment by davidjohnoliver** [comment]
> Thanks for the update. There's no "Uno Prism" template available from VS directly, unless you installed the `dotnet new` templates as well. Can you show a screenshot of the option you selected ?

@jeromelaban It was probably created with the VS Prism template ;) https://marketplace.visualstudio.com/items?itemName=BrianLagunas.PrismTemplatePack

**Comment by Leon99** [comment]
@davidjohnoliver nope
@jeromelaban yep, the ones suggested somewhere in Uno docs. Can post a screenshot layer today.

**Comment by Leon99** [comment]
![image](https://user-images.githubusercontent.com/6840381/119649868-7e4f4d00-be66-11eb-936e-efc843d28184.png)
![image](https://user-images.githubusercontent.com/6840381/119649902-87401e80-be66-11eb-9f42-b5cedee416ad.png)

**Comment by jeromelaban** [comment]
Thanks for the update. This was a typo, it will be fixed in our next release. In the meantime you can fix this by using `AutowireViewModel` instead of `AutoWireViewModel`
