### ISSUE TITLE
Search results run past the bottom of the page

### ISSUE THREAD

**Issue by yoshiask** [unoplatform/uno#6049]
## On which page?
All pages with a search box

## What's wrong?
The last search result is clipped at the bottom of the page, and I cannot scroll down any further.
![image](https://user-images.githubusercontent.com/7549325/119038346-a297bf00-b978-11eb-925b-f1fafe7751a2.png)

## Any feedback?
N/A

**Comment by sasakrsmanovic** [comment]
Thank you @yoshiask . Can you tell me which browser you are on and what is your resolution. We haven't been able to reproduce this one yet. Thanks!

**Comment by yoshiask** [comment]
This Chromium Edge (90), and the resolution is 1920x1080. I should note that this was on a laptop set to 125% display scaling

**Comment by sasakrsmanovic** [comment]
Thanks, we are investigating. I can partially reproduce your experience.

**Comment by sasakrsmanovic** [comment]
@yoshiask We have fixed this issue and also improved functionality. The search now has more matches and also has a scroll bar for search results so you can select the one most suitable for your query . 
![image](https://user-images.githubusercontent.com/33944563/125817090-e6e49c8c-d32a-4bde-a6a5-a6ec6c8ee67e.png)
