### ISSUE TITLE
Enhancement debug experience in Wasm 

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#6055]
## Please enhance debugexperience in Visual Studio 16.10 Preview 4

The developer is unable to use debugger watch windows like Watch, Locals neither the Immediate Window to evalute expression and references. I keep witnessing "Busy..." for an infinite period of time while debugging an Uno Wasm application. 

![image](https://user-images.githubusercontent.com/43340959/119167845-9129e200-ba60-11eb-9d48-e911ee3c740a.png)

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

```
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="5.0.2" />
    <PackageReference Include="Ninject" Version="3.3.4" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.1.0-dev.1" />
    <PackageReference Include="Uno.WinUI.WebAssembly" Version="3.8.0-dev.198" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="3.8.0-dev.198" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="2.1.0" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="2.1.0" />
  </ItemGroup>
```

**Comment by jeromelaban** [comment]
Thanks, this issue is fixed in the upcoming 3.0 uno bootstrapper, which will be available soon.
