### ISSUE TITLE
PropertyChangedEventHandler remains null

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#6061]
## PropertyChangedEventHandler is null

1. Declare the handler

`public event PropertyChangedEventHandler PropertyChanged;`

2. Wire up the handler implicit by x:Bind

`<TextBlock Text="{x:Bind HtmlContent, Mode=OneWay}"/>`

3. Null is detected.

`PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(HtmlContent)));`

4. I rebuilt the project because I could not find referrences in the *.g.cs files on the event handler but to no avail. I think for some reason the handler is missing in the generated files. Please see the screenshot; only 1 reference is exsinting. Thank you.

![image](https://user-images.githubusercontent.com/43340959/119236019-74131300-bb35-11eb-8980-047ff07958c9.png)

![image](https://user-images.githubusercontent.com/43340959/119236063-afaddd00-bb35-11eb-9ffc-7ed6970c35a0.png)

## Expected behavior

It has worked earlier but stop doing so recently, I expect the OneWay mode shall initialize the event property. 

## Environment

Nuget Package:
```
	<ItemGroup>
		<PackageReference Include="Microsoft.ProjectReunion" Version="0.5.7" />
		<PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.5.7" />
		<PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.5.7" />
		<Manifest Include="$(ApplicationManifest)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
		<PackageReference Include="Ninject" Version="3.3.4" />
		<PackageReference Include="Uno.Core" Version="2.3.0" />
	</ItemGroup>

```- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: <!-- Please specify -->

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: ) Preview 4
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

<!-- We would love to know of any friction, apart from knowledge, that prevented you from sending in a pull-request -->

**Comment by jeromelaban** [comment]
Thanks for the report. Can you create a sample application that includes your steps ? You can use a uno app template to do so.

**Comment by sigmarsson** [comment]
@jeromelaban https://github.com/sigmarsson/6051
Thank you.

**Comment by sigmarsson** [comment]
Was my error. The inotifypropchanged interface was missing on the respective class.
