### ISSUE TITLE
Could not load file or assembly 'System.Runtime.InteropServices.WindowsRuntime, Version=4.0.3.0

### ISSUE THREAD

**Issue by cowlinb6** [unoplatform/uno#6065]
## Current behavior

When using an "Windows Application Packaging Project" project with an Uno UWP project, this fails to start with the error: 

System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'System.Runtime.InteropServices.WindowsRuntime, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=App1
  StackTrace:
   at App1.App..ctor() in C:\code\unotest2\App1\App1.Shared\App.xaml.cs:line 46
   at App1.Program.<>c.<Main>b__0_0(ApplicationInitializationCallbackParams p) in C:\code\unotest2\App1\App1.UWP\obj\x86\Debug\App.g.i.cs:line 24

Results of output window: [output.txt](https://github.com/unoplatform/uno/files/6538571/output.txt)

## Expected behavior

The project should run.

## How to reproduce it (as minimally and precisely as possible)

- Create new Uno project from Visual Studio using the "Cross-Platform App" template.
- Add a new project to the Solution of type "Windows Application Packaging Project"
- Add a reference from the "Windows Application Packaging Project" to the UWP head
- Set the "Windows Application Packaging Project" as startup
- Run the solution
- Receive the following error
![image](https://user-images.githubusercontent.com/12410874/119483308-bb272100-bd4c-11eb-8ff8-1dbf7a2f0397.png)

Example solution: [unotest2.zip](https://github.com/unoplatform/uno/files/6538543/unotest2.zip)

## Workaround

None

## Environment

Nuget Package:

- [x ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ x] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x ] Visual Studio 2019 (version: 16.10.0 Preview 4.0)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

This was originally working and looks to be related to:

https://docs.microsoft.com/en-us/dotnet/core/compatibility/interop/5.0/built-in-support-for-winrt-removed

Testing using a UWP (non Uno) project with an App Package doesn't have this issue.

**Comment by jeromelaban** [comment]
Thanks for the report. This looks like an internal issue to UWP when dealing with that specific dependency.

One workaround is to remove the Uno.UI package dependency in the UWP project.

Note that the documentation you're referring to only impacts WinUI 3 projects, not WinUI 2 UWP projects.

**Comment by cowlinb6** [comment]
I can't really use the workaround removing Uno.UI as the the actual app that had the issue has other packages dependent on this. Is there anything else we can do?

**Comment by jeromelaban** [comment]
You should be able to remove the Uno.UI package on UWP only. Which package do you depend on that needs it for UWP only ?

**Comment by cowlinb6** [comment]
https://www.nuget.org/packages/Uno.Material
https://www.nuget.org/packages/Uno.UI.RemoteControl

**Comment by cowlinb6** [comment]
Is there any other round this as it is a major blocking issue now?

**Comment by jeromelaban** [comment]
This issue is related to desktop packaging specifically, related to this: https://stackoverflow.com/questions/48211211/uwp-application-could-not-load-file-or-assembly-system-runtime-windowsruntime.

For now you can work around it by downgrading the min version to 15063 for both the UWP app and packaging app.

**Comment by jeromelaban** [comment]
I agree. The associated PR may help with this, we'll see.

**Comment by cowlinb6** [comment]
Thanks do you know when this will be available to test with?

**Comment by jeromelaban** [comment]
When it'll work, We'll let you know.

**Comment by jeromelaban** [comment]
Changing `Uno.Core` did not fix the issue. I have no idea why this is happening in desktop publishing mode, we'll ask around at microsoft to see if there's something we need to change, but that's very unclear.

In the meantime, use appx packaging if possible.

**Comment by cowlinb6** [comment]
@jeromelaban has there been any progress on this yet?

**Comment by jeromelaban** [comment]
No progress. This issue is being looked at by Microsoft.

**Comment by jeromelaban** [comment]
Got an answer from the team at Microsoft. They suggest to add the following:

```
<PropertyGroup>
    <UseAppLocalCoreFramework>true</UseAppLocalCoreFramework>
</PropertyGroup>
```

at the root the `.UWP` project (not the Package project).

This worked on your sample app, can you let us know if that helps for your project ?

**Comment by cowlinb6** [comment]
Yes looking good. Thanks @jeromelaban.

**Comment by seanocali** [comment]
> Got an answer from the team at Microsoft. They suggest to add the following:
> 
> ```
> <PropertyGroup>
>     <UseAppLocalCoreFramework>true</UseAppLocalCoreFramework>
> </PropertyGroup>
> ```
> 
> at the root the `.UWP` project (not the Package project).
> 
> This worked on your sample app, can you let us know if that helps for your project ?

Just ran into this issue today. This fix oddly worked once but then hasn't since.

**Comment by seanocali** [comment]
I don't think this is actually solved. I've been struggling with this for a while. The XML tag fix only seems to work some of the time.

Is this even Uno related? I removed the Uno packages from the UWP app. This is just a bug with shared projects on Microsoft's end, right?

**Comment by jeromelaban** [comment]
@seanocali correct, it's not Uno related. It seems to be a relation between packaging tooling and the way UWP apps are built. Shared projects are likely not being the issue here (those don't participate actively in the build), but rather some of the dependencies that have unexpected UWP SDK versions.

**Comment by seanocali** [comment]
Just an update, I solved this problem for myself by removing a project reference to a .NET Standard 2.0 library.
