### ISSUE TITLE
[Gallery][WASM] CommandBar - The Burger menu and the Navigate Back Commandbar is overlapping and the Burger menu option is not working there.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6069]
## Current behavior
![Commandbar issue](https://user-images.githubusercontent.com/74563602/119543992-47dada80-bd5f-11eb-855a-3eb2b2766402.png)

## Expected behavior
The Burger menu and command bar should not overlap.
The Burger menu should open.

## How to reproduce it (as minimally and precisely as possible)
1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Click/tap "CommandBar" from the "Component" list.
3. Click on the 'Show Samples' button for material. 
4. Observe that The Burger menu and the Navigate Back Commandbar is overlapping.
5. Click on the Burger menu and observe that nothing is happening after clicking the Burger Menu.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by akshay-zz** [comment]
![image](https://user-images.githubusercontent.com/21263939/148770686-d101ec29-c3c3-4506-9e5d-a3fb559bcfd9.png)

I tried to check this issue. But didn't found the hamburger menu. Can  @sakshi173 you please confirm the same?

**Comment by kazo0** [comment]
Looks like issue is fixed in the Canaries
https://unogallerycanary.z27.web.core.windows.net/

@sakshi173 can you confirm and close this issue?

**Comment by sakshi173** [comment]
@kazo0 yes the issue is fixed, closing.
