### ISSUE TITLE
[Gallery][WASM] TextBox- The clear sign(X) is not displaying in night mode for Fluent.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6070]
## Current behavior
![textbox issue clear sign](https://user-images.githubusercontent.com/74563602/119552221-77daab80-bd68-11eb-88a4-72d3d349214d.png)

## Expected behavior
![textbox correct](https://user-images.githubusercontent.com/74563602/119552580-afe1ee80-bd68-11eb-87ab-2772ae81c5f1.png)

## How to reproduce it (as minimally and precisely as possible)

1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Click/tap "TextBox" from the "Component" list.
3. Go to the Fluent section. 
4. Change the app in Night mode.
4. Type some text in the Default and Header section.
5. Observe that the clear sign(X) is not displaying in night mode.

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by agneszitte-nventive** [comment]
Similar bug but for PasswordBox : https://github.com/unoplatform/uno/issues/5654

**Comment by sakshi173** [comment]
Issue is fixed, verified for the version https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=31729&view=results.
