### ISSUE TITLE
[Gallery][WASM] Cupertino - when open the Gallery app, in the Overview section for Checkbox and Radiobutton the text is truncating.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6072]
## Current behavior
![Overview issue](https://user-images.githubusercontent.com/74563602/119565839-7618e400-bd78-11eb-8d19-55e32d309102.png)
![overview](https://user-images.githubusercontent.com/74563602/119565860-7add9800-bd78-11eb-87ea-7c269cc0b41e.png)

## Expected behavior
![Overview correct](https://user-images.githubusercontent.com/74563602/119565876-7fa24c00-bd78-11eb-9ade-f218b3598b68.png)

## How to reproduce it (as minimally and precisely as possible)
1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Check the Overview section.
3. Go to 'Cupertino' section
4. Go to 'Checkbox' and 'RadioButton' section
5. Observe that for CheckBox and RadioButton  the text is truncating.

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by Youssef1313** [comment]
I couldn't reproduce this:

![image](https://user-images.githubusercontent.com/31348972/131259748-c917cd4c-131d-4744-ab58-92dd8b753b67.png)

**Comment by Youssef1313** [comment]
I'm giving a look

**Comment by Youssef1313** [comment]
I wasn't able to make a minimal repro 😕

**Comment by jeromelaban** [comment]
@sakshi173 I'm not seeing this issue as well. Could you validate it again ?

**Comment by sakshi173** [comment]
Hi @Youssef1313 and @jeromelaban - I am able to reproduce it. The issue is happening for Cupertino only.
I am adding the video for reference.

https://user-images.githubusercontent.com/74563602/131351318-91dc2571-6c58-44f7-bebb-28fb2a4fe75b.mp4

**Comment by carldebilly** [comment]
Looks like a text measure caching issue.  Could be related to font-loading stuff.

**Comment by Youssef1313** [comment]
@carldebilly Exactly what I was suspecting, especially that removing the custom font doesn't trim the text.

But I'm not able to reproduce outside of the gallery app. So debugging is somewhat hard for me :)

The cache *should* be handling font correctly.

https://github.com/unoplatform/uno/blob/f9fa20de665c0c5d6e6ffe8c3b5177b0a615f191/src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.MeasureKey.cs#L22-L40

**Comment by jeromelaban** [comment]
@carldebilly  Could it be that the font is not preloaded properly in the css file ?

**Comment by carldebilly** [comment]
@jeromelaban Yep...  that's a known problem since the first days of Uno on Wasm... Referencing the font in the browser is not enough, it needs to be USED or the text won't be measured properly.  If the result is cached, you're stuck with that wrong measure forever.

A workaround would be easy to build: make sure all fonts are not only loaded, but actually used for rendering at least once before the application starts.  The easiest way to patch it is to use css pseudo-elements to draw something using those fonts.  That way they are loaded while the browser is still trying to figure out how to load the WASM runtime...  But that's definitely a patch, not an elegant implementation.

**Comment by Youssef1313** [comment]
@carldebilly When I tried to reproduce in a new Uno app, the measurement was done correctly. Does this mean for the gallery app case the measurement is done before the font is loaded, and for the new uno app case the measurement is done after the font is loaded? Why does this happen? ie, what's the real difference between both cases?

---

> The easiest way to patch it is to use css pseudo-elements to draw something using those fonts.

I'm not sure I understand how this would work. Would you please be able to explain more?

**Comment by carldebilly** [comment]
Probably just because it's a different font.

**Comment by francoistanguay** [comment]
@agneszitte-nventive  Is this fixed? @sakshi173  Can we retest?

**Comment by sakshi173** [comment]
This issue is not happening anymore, verified with the latest canary build due to that closing it.
