### ISSUE TITLE
[Gallery][All Platforms] Combobox Cupertino- The spelling of Combobox is wrong for Disabled Combobox.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6073]
## Current behavior
![Combobox issue](https://user-images.githubusercontent.com/74563602/119568728-cd6c8380-bd7b-11eb-8746-e4c4dceb7b77.png)

## Expected behavior
The spelling of Combobox should be correct.

## How to reproduce it (as minimally and precisely as possible)
Open the link https://unogallerycanary.z27.web.core.windows.net/
Click/tap "ComboBox" from the "Component" list.
Go to the Cupertino section.
Observe the spelling of Combobox for Disabled Combobox is wrong.

Nuget Package Version(s):

Affected platform(s):

- [X] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [X] Skia
  - [ ] WPF
  - [X] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by MartinZikmund** [comment]
You are right, it should be `ComboBoss` 😎
![image](https://user-images.githubusercontent.com/1075116/120624743-46956600-c461-11eb-9299-e79c9eb66a98.png)

**Comment by agneszitte-nventive** [comment]
@sakshi173 ready to be QA on canary :)

**Comment by sakshi173** [comment]
Verified, Issue Is fixed, closing.
