### ISSUE TITLE
WASM project is not created with Prism template

### ISSUE THREAD

**Issue by Leon99** [unoplatform/uno#6091]
## Current behavior

WASM project is not created with Prism template.
![image](https://user-images.githubusercontent.com/6840381/119825753-a3ad8b00-bf3a-11eb-83a9-aaa288cb064e.png)

## Expected behavior

WASM project is created with Prism template.

## How to reproduce it (as minimally and precisely as possible)

Create a Uno Prism project from a supplied template. Check WASM.
![image](https://user-images.githubusercontent.com/6840381/119825806-b1631080-bf3a-11eb-9642-f9640558255d.png)

## Environment

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [] Windows
- [ ] Build tasks
- [x] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.6)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
Fixed by https://github.com/unoplatform/uno/pull/3883
