### ISSUE TITLE
NavigationView 'Settings' text isn't localized

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#6094]
## Current behavior

The Microsoft.UI.Xaml `NavigationView`'s settings button text always shows "Settings" even if the language is changed to es-MX (Spanish, Mexico).

## Expected behavior

After changing the Android system language, I would expect the settings button text to update. Other app resources are updating just fine so I know it's not a general issue.

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.6.6

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. Can you specify which version of the navigation view you are using ? (Windows.UI.Xaml or Microsoft.UI.Xaml).

**Comment by iosub** [comment]
Just Check it and ut happens with Microsoft.UI.Xaml

**Comment by robloo** [comment]
Yes, sorry I should have stated it is `Microsoft.UI.Xaml`

**Comment by jeromelaban** [comment]
This is localized here:

https://github.com/unoplatform/uno/blob/56d3ba98ee6cab055dc8d7c4941ce4494e20e946/src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationView.cs#L1441

but there may be another issue in the resources resolution.

**Comment by Youssef1313** [comment]
The `CurrentUICulture` (somehow) is changing after being set to es-MX. Trying to figure out where does that happen but couldn't yet

**Comment by Youssef1313** [comment]
Note: for some reason I'm only able to reproduce in SamplesApp. Can't isolate a repro. @robloo Do you have a repro?

**Comment by Marc-Antoine-Soucy** [comment]
I tested on IOS, Android, it's fixed on both those platforms. I can test it on wasm and skia monday if necessary.
