### ISSUE TITLE
How to hide the keyboard when ContentDialog is shown 

### ISSUE THREAD

**Issue by AbdalaMask** [unoplatform/uno#6100]
## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

How to hide the keyboard when ContentDialog is shown

**Comment by AbdalaMask** [comment]
When Content Dialog is shown, the keyboard appears automatically
How to cancel the display of the keyboard

**Comment by jeromelaban** [comment]
@AbdalaMask The keyboard should only appear when there's a TextBox inside. If you can create a repro sample for this issue, this will help.

**Comment by MartinZikmund** [comment]
You could try to use `InputPane.TryHide()` to hide the keyboard in this case. Alternatively, you will need to set focus on a different control within the `ContentDialog` to avoid this behavior
