### ISSUE TITLE
Add Xaml UID and Name attributes to rendered web elements

### ISSUE THREAD

**Issue by jamesmcroft** [unoplatform/uno#6101]
## What would you like to be added:

When a UI is rendered for web, the generated elements should show the `x:Uid` or `x:Name` attributes in some type of format.

## Why is this needed:

Adding this functionality will make it easier to write UI tests for web projects as it is currently not easy to identify specific UI elements based on the attributes available.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jamesmcroft** [comment]
Going to have a little look into implementing this 😄

**Comment by jeromelaban** [comment]
Thanks for the report! This is actually already implemented. This is [documented here](https://github.com/unoplatform/Uno.UITest#how-to-use-unouitest-with-an-uno-platform-app), but also can be enabled with [this property](https://github.com/unoplatform/uno/blob/79aa9249b0a0c11e0dd9155d7feb216d941e86cc/src/Uno.UI/FeatureConfiguration.cs#L465).

**Comment by jamesmcroft** [comment]
Doh! I made an assumption that this would just appear as default. Thanks for the heads up @jeromelaban 👍🏻
