### ISSUE TITLE
Listview template not displaying the same between platforms

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#6130]
## Current behavior

Listview template is not displaying the same between UWP, Android and iOS

UWP
![image](https://user-images.githubusercontent.com/7770915/120338120-eb793d00-c2c1-11eb-91cc-e77b225628e6.png)

Android

![Screenshot_1622556360](https://user-images.githubusercontent.com/7770915/120338699-7b1eeb80-c2c2-11eb-85eb-8063b25685da.png)

iOS

![image](https://user-images.githubusercontent.com/7770915/120338856-98ec5080-c2c2-11eb-823b-0a17844f2411.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/7770915/120338142-f03df100-c2c1-11eb-84a4-b6745fb19521.png)

## Environment
Sample:
[ListViewTemplate.zip](https://github.com/unoplatform/uno/files/6576944/ListViewTemplate.zip)

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI 3.7.4

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] Windows

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.10.0)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carlh98** [comment]
Tried with Uno.UI 3.2.0 in Android and the issue is present

**Comment by jeromelaban** [comment]
Can you try again with Uno 3.8-dev ? (Always try with latest dev please)

**Comment by carlh98** [comment]
Issue fixed with 3.8.0-dev.302
