### ISSUE TITLE
Use GeneratedCodeAttribute in generated code

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/uno#6134]
## Current behavior

When an analyzer is used it analyses code generated by Uno and produces errors when warnings as errors are enabled.

## Expected behavior

`GeneratedCodeAttribute` is used on all generated code and no warnings for generated code are used.

## How to reproduce it (as minimally and precisely as possible)

Install DisposableFixer analyzer

## Workaround

Not known

## Environment

Nuget Package:
Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

Nuget Package Version(s): 3.7.4

Affected platform(s):

- iOS
- Android
- WebAssembly
- macOS
- Skia
  - WPF
  - GTK (Linux)
  - Tizen
- Build tasks

IDE:
-  Visual Studio 2019 (version: 16.10)

**Comment by jeromelaban** [comment]
Thanks for the report. We have not added this attribute has it prevents from debugging the generated code as well. 

You can use the `XamlGeneratorAnalyzerSuppressions` item group to suppress errors; this will add the proper attributes.

**Comment by jeromelaban** [comment]
Uno defines some for itself here: https://github.com/unoplatform/uno/blob/f6983a16bfa957981025b5d5da1b948a75a090e0/src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props#L168

**Comment by xperiandri** [comment]
What is `nventive.Usage-NV0056`?

**Comment by xperiandri** [comment]
How can I apply it to `DF0001`?

**Comment by xperiandri** [comment]
`error  : The attribute "Include" in element <XamlGeneratorAnalyzerSuppressions> is unrecognized.`

**Comment by xperiandri** [comment]
I tried
``` XML
  <ItemGroup>
    <XamlGeneratorAnalyzerSuppressions Include="DF0001"/>
    <XamlGeneratorAnalyzerSuppressions Include="DF0033"/>
  </ItemGroup>
```
No effect

**Comment by jeromelaban** [comment]
Then there's work needed. This is implemented as part of this: https://github.com/unoplatform/uno/blob/aca1a3ad9d5634b79986fa3130933f2d4f85cee4/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs#L532

**Comment by xperiandri** [comment]
Do you mean that generator must be extended to allow external suppressions?

**Comment by jeromelaban** [comment]
It's already supposed to do this, with these definitions, if it's not working, then something else is happening.
