### ISSUE TITLE
[Android] `Path` with `Stretch="UniformToFill"` in a `Grid` with row height `Auto` takes additional space

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#6139]
## Current behavior

When we add a `Path` inside a grid with a `Row.Height="Auto"` like this

```xaml
<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
	<Grid.RowDefinitions>
		<RowDefinition Height="Auto" />
		<RowDefinition Height="*" />
	</Grid.RowDefinitions>

	<Path Fill="Blue"
                  Grid.Row="0"
		  Data="{...}"
		  Stretch="UniformToFill" />

        [...]
</Grid>
```

![Screenshot_20210602-095634](https://user-images.githubusercontent.com/17461593/120502727-abcd5680-c390-11eb-86d8-02a93a6b4c44.jpg)

## Expected behavior

![actualresult](https://user-images.githubusercontent.com/17461593/120502763-b38cfb00-c390-11eb-9a0c-76e8be068d5e.jpg)

## How to reproduce it (as minimally and precisely as possible)

- Download sample [PathSample.zip](https://github.com/unoplatform/uno/files/6585426/PathSample.zip)
- Deploy on android

## Workaround

**Specific workaround that does not apply for every path data (See comment below)**
Changing Stretch property to `Uniform` works for us.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.8.0-dev.310

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

I tested the sample with the latest stable version (3.7.6) and it's actually worse on Android and iOS, so at least the latest changes helps with this issue somehow.

Android
![andriod](https://user-images.githubusercontent.com/17461593/120504414-1c28a780-c392-11eb-9a15-310cacb6a268.jpg)

iOS:
![image](https://user-images.githubusercontent.com/17461593/120504400-192db700-c392-11eb-84fe-d77759a8ff95.png)

**Comment by jeromelaban** [comment]
@takla21 Do you know if this happens with 3.9-dev ?

**Comment by takla21** [comment]
I didn't tested on 3.9-dev, since the version I listed above was the latest. I can test it with the latest 3.9-dev. I will come back with the result.

**Comment by takla21** [comment]
So I took the latest uno 3.9-dev version and it's the same result (the bug remains)

Tested on: 3.9.0-dev.418
Device: One plus 7 pro Android 10

Sample with the latest uno.ui version 
PathSampleUpdated.zip](https://github.com/unoplatform/uno/files/6869159/PathSampleUpdated.zip)

**Comment by takla21** [comment]
I forgot to add some details that may be very important for you. I actually have a workaround that works specifically on our project (Specific Path). However, the workaround does not work on the path provided in previous sample. Fortunately, the workaround is no longer needed on the latest uno version that I've tested **3.9.0-dev.418** for our specific case.

**Workaround:**
Use stretch property `Uniform` instead of `UniformToFill` is working for us.
![Screenshot_20210727-121240](https://user-images.githubusercontent.com/17461593/127192408-53546457-b64a-4c41-8b05-c28e8ac8e7ee.jpg)
Uno.UI version: **3.7.10**

**Sample with specific path with uno 3.9.0-dev.418**
[PathSampleWithActualPath.zip](https://github.com/unoplatform/uno/files/6887242/PathSampleWithActualPath.zip)

**Comment by Youssef1313** [comment]
The native Android API to calculate path bounds includes bezier control points, which isn't what we want. This may be a reason why there is an additional space.

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/pull/13378 will fix this.

Before change in PR:

![image](https://github.com/unoplatform/uno/assets/31348972/cf6dbf38-82b7-489f-9481-1cee4c42199f)


After change in PR:

![image](https://github.com/unoplatform/uno/assets/31348972/cabca5a6-1461-4022-a54a-f5ac422b09bd)
