### ISSUE TITLE
[WASM] x:Bind to a Visibility property where part of the path is null does not use FallbackValue

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno#6142]
## Current behavior

I have a control who binds it's Visibility property to a view model property path with a null value.  FallbackValue is not used and the control is still displayed in WASM, but correctly hides in UWP.

`<Button Visibility="{x:Bind ViewModel.First.IsExpanded, FallbackValue=Collapsed}" />`

## Expected behavior

Control is not visible in WASM.

## How to reproduce it (as minimally and precisely as possible)

Attaching a test project. 
[App1.Shared.zip](https://github.com/unoplatform/uno/files/6586705/App1.Shared.zip)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This issue is going to take some work to get working properly. It's also a side effect of the fact that null values in expressions may raise exceptions incorrectly, even if caught early.

As a workaround, you can use the following:

```xml
<Button DataContext="{x:Bind ViewModel}" 
        Visibility="{Binding First.IsExpanded, FallbackValue=Collapsed, RelativeSource={RelativeSource self}}" />
```
