### ISSUE TITLE
[macOS] `Panel`/`Canvas` without background still handles input

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#6146]
## Current behavior

`Panel`/`Canvas` without background still handles pointer input

## Expected behavior

Should be able to click-through to the element below it.

## How to reproduce it (as minimally and precisely as possible)

Place a `Canvas` on top of a `Button`. Notice the `Button` cannot be clicked.

```
<Grid>
  <Button>
  <Canvas HorizontalAlignment="Stretch" VerticalAlignment="Stretch" />
</Grid>
```

## Workaround

Set `IsHitTestVisible` to `false` if the scenario allows.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by ajpinedam** [comment]
@MartinZikmund  I can confirm this issue was also fixed by PR https://github.com/unoplatform/uno/pull/6645
