### ISSUE TITLE
Unknown attachable member 'ViewModelLocator.AutowireViewModel' on element 'UserControl'

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#6148]
## Current behavior

`**XamlCompiler error WMC0010: Unknown attachable member 'ViewModelLocator.AutowireViewModel' on element 'UserControl'`

![image](https://user-images.githubusercontent.com/43340959/120675459-6181cd80-c495-11eb-8870-79e25a296e47.png)

occured in xaml file : 

![image](https://user-images.githubusercontent.com/43340959/120674324-46628e00-c494-11eb-96f0-bf404a486dfa.png)

or is it a Prism or WinUI issue ?

## Environment

Nuget Package:

	<ItemGroup>
		<PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0-preview" />
		<PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.0-preview" />
		<PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.0-preview" />
		<Manifest Include="$(ApplicationManifest)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
		<PackageReference Include="Prism.DryIoc.Uno.WinUI" Version="8.1.97" />
		<PackageReference Include="Prism.Uno.WinUI" Version="8.1.97" />
		<PackageReference Include="Uno.Core" Version="2.4.0-dev.4" />
	</ItemGroup>

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.11.0 Pv 1 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This was fixed in https://github.com/unoplatform/uno/issues/6042, please see the other issue for the workaround.

**Comment by sigmarsson** [comment]
I typed it as lower-case.
