### ISSUE TITLE
[CalendarDatePicker][Playground] In the calendar last selected dates are highlighting in grey border when open the calendar to choose the date next time.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6154]
## Current behavior
![multiple date highlighted](https://user-images.githubusercontent.com/74563602/120710522-3cd52800-c48c-11eb-8524-67b8c44fe486.png)

## Expected behavior
In the calendar only the currently selected date should be highlighted in grey color.

## How to reproduce it (as minimally and precisely as possible)

1. Visit https://playgroundcanary.z19.web.core.windows.net/#4d789784
2. Click on Select a Date button.
3. Click on any date on calendar 
4. Again click on Date Button.
5. Click on any other date on calendar.
6. Observe that the Last selected dates are highlighting in grey color.

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:
- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by sakshi173** [comment]
@dr1rrb, I have tried the way you explained it. Attach is the video, could you confirm, is it correct way to do or not?

https://user-images.githubusercontent.com/74563602/121025443-2c1a0000-c773-11eb-911c-38bc8951b35f.mp4

**Comment by dr1rrb** [comment]
@sakshi173 well you don't have to un-select the previous element, otherwise yes it's seems to be the correct way
