### ISSUE TITLE
[CalendarDatePicker][Playground] The monthly calendar for year 2121 displaying only Dec month and for other months of the year the screen is blank.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6155]
## Current behavior

https://user-images.githubusercontent.com/74563602/120712804-1b297000-c48f-11eb-8ccd-c25e3e64e57d.mp4

## Expected behavior
The Monthly calendar for every year should display for all the months of the year.

## How to reproduce it (as minimally and precisely as possible)

1. Visit https://playgroundcanary.z19.web.core.windows.net/#4d789784
2. Click on Select a Date button.
3. Go to Decade view of the calendar.
4. Click on year 2121.
5. click on month and date for year 2121
6. Again open the calendar for 2121 .
7. Observe that the monthly calendar for year 2121 displaying only Dec month and for other months of the year the screen is blank.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by sakshi173** [comment]
@MartinZikmund , could you please let me know is this issue is fixed, as I am not able to reproduce it.
If the issue is fixed, please close it and let me know.

**Comment by MartinZikmund** [comment]
@sakshi173 will check

**Comment by carldebilly** [comment]
@sakshi173 @MartinZikmund Could you please check if this issue is still present?

**Comment by sakshi173** [comment]
@carldebilly , I am not getting the exact issue , but yes when choosing the year 2121 the calendar is not displaying correctly, due to that keeping this bug is open.

https://user-images.githubusercontent.com/74563602/153273917-3af2b82b-8e12-4742-92c3-013533d4cfbf.mp4

**Comment by Youssef1313** [comment]
@sakshi173 There were too many improvements to calendar-related controls. Can you check if there are any issues remaining?

**Comment by sakshi173** [comment]
Verified this issue is fixed closing it.
