### ISSUE TITLE
[CalendarDatePicker][Playground] Monthly calendar doesn't show up when already date has selected and try to choose another future year date by clicking on any year in the Decade calendar.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6160]
## Current behavior

https://user-images.githubusercontent.com/74563602/120823821-d3095c80-c525-11eb-8113-d627f95dc357.mp4

## Expected behavior
The Monthly calendar should open when clicking the Monthyear on header section.

## How to reproduce it (as minimally and precisely as possible)
1. Visit https://playgroundcanary.z19.web.core.windows.net/#4d789784
2. Click on Select a Date button.
3. Go to Decade Calendar view.
4. Choose any month and date for that selected year.
5. Again go to Decade calendar view.
6. Click on any year in the Decade calendar
7. Observe that Monthly calendar doesn't show up for the year.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by carldebilly** [comment]
## Investigations:
There's 2 found problems, the second is probably the result of the first one (to be confirmed):
1. An error 'The member int Calendar.Era is not implemented in Uno.' is raised.
    ![image](https://user-images.githubusercontent.com/4174207/121081614-f09b2800-c7aa-11eb-9719-629e4ba584fb.png)
2. A _null reference exception_ is raised:
    ![image](https://user-images.githubusercontent.com/4174207/121081737-20e2c680-c7ab-11eb-9d93-a368a8227531.png)
