### ISSUE TITLE
`CreateIconElement` should dynamically update its created `IconElement` instances

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#6168]
## What would you like to be added:

In MUX, the `IconSource.CreateIconElement` now automatically keeps track of `PropertyChanged` and updates the respective `IconElement` instances it created.

## Why is this needed:

Sync with MUX behavior.

## For contributors

Replicate the changes in this PR https://github.com/microsoft/microsoft-ui-xaml/pull/4563

## For which Platform:

All

**Comment by kaabus** [comment]
Can I contribute to this ??

**Comment by MartinZikmund** [comment]
@kaabus I am very sorry but this was addressed by https://github.com/MartinZikmund/Uno/commit/27a35b52952eb14c433a8ab603307ad23f72de1b 😶 . We needed it as one of the prerequisites for WinUI 2.6 so it was prioritized. However, there is a lot of other issues that can be tackled - see those marked [good-first-issue](https://github.com/unoplatform/uno/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) or [difficulty-starter](https://github.com/unoplatform/uno/issues?q=is%3Aopen+is%3Aissue+label%3Adifficulty%2Fstarter). Happy to help out get started when you pick one! Tag me on the issue you want to work on and I will assign it to you 🙂
