### ISSUE TITLE
[Tizen] Support for `Clipboard`

### ISSUE THREAD

**Issue by trungnt2910** [unoplatform/uno#6179]
## What would you like to be added:
Support for setting textual data to Clipboard on Skia.Gtk, Skia.WPF and Tizen.

## Why is this needed:
For platform parity with UWP.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?
Adding Support for Tizen would be **great**, however, Tizen.NET does not seem to expose any Clipboard API. It _does_ expose some for Javascript Web apps or a [native API](https://docs.tizen.org/application/native/api/mobile/5.0/group__CAPI__CBHM__MODULE.html), but it may take more work. (Even [Xamarin.Essentials does not support it](https://docs.microsoft.com/en-us/xamarin/essentials/platform-feature-support)).

**Comment by MartinZikmund** [comment]
Added Tizen too, because why not 😀

**Comment by MartinZikmund** [comment]
I think it should be ok, what do you think, @carldebilly?

**Comment by Youssef1313** [comment]
I couldn't find any native clipboard APIs for Tizen. :(

**Comment by trungnt2910** [comment]
> I couldn't find any native clipboard APIs for Tizen. :(  

For anyone interested in Tizen:
- The `TizenFX` (the official Tizen API for .NET) simply calls [DllImported](https://github.com/Samsung/TizenFX/blob/a444cb53725a48739d745ecda0f42ce931131e8b/src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs#L110) functions from [native libraries](https://docs.tizen.org/application/native/api/iot-headless/5.0/group__CAPI__NETWORK__BLUETOOTH__MODULE.html).
- The important thing is to actually know [which library](https://github.com/Samsung/TizenFX/blob/a444cb53725a48739d745ecda0f42ce931131e8b/src/Tizen.Network.Bluetooth/Interop/Interop.Libraries.cs#L21) we need to import.
- According to the docs' naming conventions, the library we're searching for might be `libcapi-cbhm.so.0` (Clipboard History Manager)? (**This is a pure guess, I can't find the official docs pointing to its name, but it's still worth trying, although I'm not responsible if you've wasted a few hours debugging the `DllNotFoundException`s**).

So the simplest way to support this function is to import the libraries, marshal the `enum`s and `struct`s, and we have full support (even before Xamarin).

But I still think `TizenFX` has a good reason for not supporting this clipboard API. It seems that this API is not portable, and only works on Mobile and IOT headed (I don't know what the latter means) devices, and not on Wearable.

I've never actually run a Hello World app on Tizen (wasted half a day of my life to install the SDKs and stuff, and another half hour to wait for Uno to build, but the app never ran), so I don't think I can work on this myself.

But still, this information might help someone.
