### ISSUE TITLE
[CalendarDatePicker][Gallery/Playground] Calendar does not work when already date has selected and try to choose another future year date by clicking on any year in the Decade calendar.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6182]
## Current behavior

https://user-images.githubusercontent.com/74563602/121022478-5ae2a700-c770-11eb-957c-f12f56e5953c.mp4

## Expected behavior
Calendar should work properly.

## How to reproduce it (as minimally and precisely as possible)

1. Visit https://playgroundcanary.z19.web.core.windows.net/#4d789784
2. Click on Select a Date button.
3. Go to Decade Calendar view.
4. Choose any month and date for that selected year.
5. Again go to Decade calendar view.
6. Click on any year in the Decade calendar
7. Observe that Random year shown in header
8. Click on up or down arrrow and try to choose another year.
9. Observe that calendar does not work at all.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by sakshi173** [comment]
Still The issue is present in gallery for **Material and Cupertino** for all the platform.

**Comment by jeromelaban** [comment]
The issue is related to Fluent in this case, not Material/Cupertino.

**Comment by sakshi173** [comment]
@jeromelaban, shall I raise a seperate bug for Material/Cupertino?

**Comment by jeromelaban** [comment]
It's the appropriate one, it's just not a material/cupertino issue.

**Comment by sakshi173** [comment]
@carldebilly, Not able to reproduce this bug, due to that closing it.
