### ISSUE TITLE
Inertia is not supported in manipulation events

### ISSUE THREAD

**Issue by jeanplevesque** [unoplatform/uno#6186]
## Current behavior

`ManipulationInertiaStarting` is not raised even when enabled.

## Expected behavior

When enabled, ManipulationInertiaStarting is raised and inertia-driven deltas are received.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android

Not tested the following platforms:
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by PhilippeAudet-Stratejia** [comment]
After testing this feature, I ran into a problem on iOS. 

When activating the inertia, the Translation Delta doesn't go down, but instead goes exponentially up, and eventualy 0.

Android and UWP are not impacted by this problem.
