### ISSUE TITLE
WinUI CommandBar

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#6195]
## What would you like to be added:

CommandBar code from WinUI should be imported

## Why is this needed:

Share CommandBar logic across all platforms

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
@kazo0 please check `area/commandbar` for many related issues. It is very likely that the port of the control will fix a lot of them at once 👍
