### ISSUE TITLE
WinUI chinese messy code

### ISSUE THREAD

**Issue by cbuduknui** [unoplatform/uno#6205]
WinUI running program, chinese code display messy code!
<TextBlock Text="你好!" Margin="20" FontSize="30" />

**Comment by jeromelaban** [comment]
Thanks for the report. Can you open an issue again using [this template](https://github.com/unoplatform/uno/issues/new?assignees=&labels=kind%2Fbug%2C+triage%2Funtriaged%2C+difficulty%2Ftbd&template=bug-report.md), and provide screenshots or repro sample ?
