### ISSUE TITLE
Unknown attachable member RegionManager.RegionName

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#6206]
## Prism attach property causing compiler error

I take this page : 

```
<Page
    x:Class="Weather.History.Pages.ConsolePage"
    xmlns:prism="clr-namespace:Prism.Mvvm;assembly:Prism.Uno"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    mc:Ignorable="d">

    <Grid>
        <Border CanDrag="True" BorderThickness="10" BorderBrush="#FFFFD700">
            <ContentControl prism:RegionManager.RegionName="ConsolePage"/>
        </Border>
    </Grid>
</Page>

```

![image](https://user-images.githubusercontent.com/43340959/121341542-0f232f80-c921-11eb-970c-689d4c19cc07.png)

I regardless face this error whether the Prism XML namespace is specified as either in this example or by using  `xmlns:prism="http://prismlibrary.com/"`

## Environment

Nuget Package:
- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

	<ItemGroup>
		<PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0-preview" />
		<PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.0-preview" />
		<PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.0-preview" />
		<Manifest Include="$(ApplicationManifest)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
		<PackageReference Include="Prism.DryIoc.Uno.WinUI" Version="8.1.97" />
		<PackageReference Include="Prism.Uno.WinUI" Version="8.1.97" />
		<PackageReference Include="Uno.Core" Version="2.4.0" />
	</ItemGroup>

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.10.0)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. 

```xml
xmlns:prism="clr-namespace:Prism.Mvvm;assembly:Prism.Uno"
```
is not supported by Uno, or WinUI.
You must using this syntax instead:
```xml
xmlns:prism="using:Prism.Mvvm"
```

**Comment by sigmarsson** [comment]
WEll, that is true, `xmlns:prism="using:Prism.Mvvm"` helps vanishing errors on Wasm but does not on WD :

![image](https://user-images.githubusercontent.com/43340959/121354162-e99d2280-c92e-11eb-890f-48414be5c238.png)

![image](https://user-images.githubusercontent.com/43340959/121354229-f7eb3e80-c92e-11eb-8b69-5ee7e648a596.png)

![image](https://user-images.githubusercontent.com/43340959/121354291-089bb480-c92f-11eb-9df8-16d56cf21616.png)
