### ISSUE TITLE
WinUI chinese code display messy code

### ISSUE THREAD

**Issue by cbuduknui** [unoplatform/uno#6208]
## Current behavior
<Page
    x:Class="UnoApp1.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:UnoApp1"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
		<TextBlock Text="你好!" Margin="20" FontSize="30" />
    </Grid>
</Page>

## Expected behavior
![0609](https://user-images.githubusercontent.com/62919343/121376555-37884980-c974-11eb-8615-9449208dba6e.png)

## Environment
Running in Windows10 System , TargetFramework net5.0-windows10.0.19041.0

Nuget Package:
- [ ] Microsoft.ProjectReunion 
- [ ] Microsoft.ProjectReunion.Foundation 
- [ ] Microsoft.ProjectReunion.WinUI
- [ ] Uno.Core

Nuget Package Version(s):
Microsoft.ProjectReunion (version: 0.5.5)
Microsoft.ProjectReunion.Foundation  (version: 0.5.5)
Microsoft.ProjectReunion.WinUI  (version: 0.5.5)
Uno.Core  (version: 2.3)
Affected platform(s):
- [ ] Windows
- [ ] Skia
- [ ]  WPF

IDE:
- [ ] Visual Studio 2019 (version: 16.10)

**Comment by jeromelaban** [comment]
Thanks for the report. This is a WinUI issue, not an Uno issue.

Make sure to start the application using the `.Package` project, and not the desktop project.

**Comment by cbuduknui** [comment]
Create project use Cross-Platform App (WinUI)(Uno Platform) template appear, use Blank App,Packaged(WinUI 3 in Desktop) create project display normal

**Comment by jeromelaban** [comment]
Thanks. It may be caused by the default encoding of the file. Can you try doing the following:

- Open the xaml file
- File / Save as, click the down arrow on the save button:
![image](https://user-images.githubusercontent.com/5839577/121383823-bd28dc80-c915-11eb-82c3-c3a3a74ee1d9.png)
- Click Save with Encoding
- In the encoding, select "Unicode (UTF-8 with signature)"
- Save the file.

Try rebuilding and let us know if this helps.

**Comment by cbuduknui** [comment]
I tried it and had no solution

**Comment by cbuduknui** [comment]
Thanks, follow your steps, problem solving
