### ISSUE TITLE
xmlns:prism="using:Prism.Mvvm" does not resolve attached propery

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#6219]
## prism:RegionManager.RegionName is unknown

Tried #6206's solution for size but to no avail. Please see screenshot beneath. Thank you.

![image](https://user-images.githubusercontent.com/43340959/121518384-b28f4580-c9f0-11eb-93ae-0088c4077d15.png)

```
	<ItemGroup>
		<PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0-preview" />
		<PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.0-preview" />
		<PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.0-preview" />
		<Manifest Include="$(ApplicationManifest)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
		<PackageReference Include="Prism.DryIoc.Uno.WinUI" Version="8.1.97" />
		<PackageReference Include="Prism.Uno.WinUI" Version="8.1.97" />
		<PackageReference Include="Uno.Core" Version="2.4.0" />
	</ItemGroup>

```

**Comment by jeromelaban** [comment]
Thanks for the report. Can you attach a sample of the application you are building?

**Comment by sigmarsson** [comment]
@jeromelaban , please take a look in [this repo](https://github.com/sigmarsson/6051) (commit 681b83ee).

**Comment by jeromelaban** [comment]
Thanks for the repro. This attached property is in the `Prism.Region` namespace, and you need to use `xmlns:prismRegions="using:Prism.Regions"` to access it.

In the future though, for Prism questions, please use the Prism repository. Thanks!
