### ISSUE TITLE
[Gallery][Android/iOS]App crashes when the calendar view is open and try to change theme from day mode to night mode.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6223]
## Current behavior

https://user-images.githubusercontent.com/74563602/121567583-bd47db80-c9ec-11eb-9663-4cc3c796e7d0.mp4

## Expected behavior
The app should not crash and the thems should change from day mode to night mode.

## How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "CalendarView" from the "Component" list.
4. Click on any dates for the material and fluent for the current month.
5. Now try to change the theme from day mode to night mode.
6. Check app crashes and stop.

Nuget Package Version(s):

Affected platform(s):

- [X] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by kazo0** [comment]
`[libc] Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xff4b9ffc in tid 18549 (ive.uno.ui.demo), pid 18549 (ive.uno.ui.demo)`

**Comment by Youssef1313** [comment]
This appears to be the same as #7098
I marked #7100 as a fix for both issues.

**Comment by sakshi173** [comment]
CalendarView control is removed for Android/iOS platforms, due to that closing this bug.
