### ISSUE TITLE
There is no way to detect a precedence change on a DependencyProperty

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#623]
## I'm submitting a...
- Feature request

## Current behavior
When the precedence of the value of a `DependencyProperty` changes, there is no way to get notify (cf. https://github.com/nventive/Uno/blob/997fc0c463e05eb8085c2c6cf39e40b6dd60bf25/src/Uno.UI/UI/Xaml/DependencyObjectStore.cs#L1322), but in some cases we need to react to this.

This is the case in transforms where we don't update the internal transform matrix while animating, we need to get notified when the precedence of the current value goes to `Local` (at the end of the animation) so we can update the matrix properly.

## Expected behavior
There a way to specify that we need to get notified (internal)

## Environment
Nuget Package: _irrelevant_
Package Version(s): _irrelevant_
Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio: _irrelevant_
Relevant plugins: _none_

**Comment by MartinZikmund** [comment]
The purpose of this was related to animations, which was fixed in https://github.com/unoplatform/uno/pull/15524 , so this can be closed unless needed for another purpose in the future.
