### ISSUE TITLE
[Gallery][Wasm] CalendarView and CalendarDatePicker- When click on the the previous or Next arrow button on header one time, the month calendar view does not change until move the cursor from the arrow.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6234]
## Current behavior

https://user-images.githubusercontent.com/74563602/121748618-48050500-cad7-11eb-80c2-1348dd474bbf.mp4

## Expected behavior
The Month should also change on the Header.

## How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "CalendarView" from the "Component" list.
4. Click on the previous arrow button on the header of the calendar.
5. Observe that the month name is not changing on header until move the cursor from the arrow.
6. 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by carldebilly** [comment]
Can't reproduce this problem on 2022-02-02 on version using Uno.UI v4.1.0-dev.583

**Comment by sakshi173** [comment]
Yes this issue is fixed now.
