### ISSUE TITLE
[Gallery][Wasm] Overview- For Cupertino, the checkbox section is not properly aligned with radiobutton and togglebutton section 

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6235]
## Current behavior
![alignment](https://user-images.githubusercontent.com/74563602/121749200-41c35880-cad8-11eb-8bdc-629400968eb5.png)

## Expected behavior
Checkbox, Radiobutton, Togglebutton should all should be correctly aligned.

## How to reproduce it (as minimally and precisely as possible)
Open Uno Gallery APP
Go to Cupertino section.
Observe that the checkbox section is not properly aligned with radiobutton and togglebutton section 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
Sounds related to a change @Xiaoy312 added a fix for recently. Could you revalidate ?

**Comment by sakshi173** [comment]
@jeromelaban, Still the issue is present.
![aligned issue](https://user-images.githubusercontent.com/74563602/151557591-f53c814c-a9c1-438f-86d3-374186cbd425.png)

**Comment by jeromelaban** [comment]
@Xiaoy312 could you point to the fix you made for this so it's documented here?

**Comment by agneszitte-nventive** [comment]
Elements are aligned with the latest canary version but also @sakshi173 and @jeromelaban don't forget that the visual states take some place that's why when in normal state they are a little on the right. See screenshot here
![image](https://user-images.githubusercontent.com/16295702/173465746-09748d9d-d54f-4e71-84bb-6755d26f5c8e.png)
