### ISSUE TITLE
Android Migrate off mCursorDrawableRes (setting cursor color on TextView) as throws error in api 29 and higher

### ISSUE THREAD

**Issue by mitchcapper** [unoplatform/uno#6240]
## Current behavior
an exception thrown on access:
`Accessing hidden field Landroid/widget/TextView;->mCursorDrawableRes:I (greylist-max-p, reflection, denied)
**Java.Lang.NoSuchFieldException:** 'No field mCursorDrawableRes in class Landroid/widget/TextView; (declaration of 'android.widget.TextView' appears in /system/framework/framework.jar!classes3.dex)'`

## Summary
So https://github.com/unoplatform/uno/blob/14c3ae67d3f52334394afa468dcf734d9cff985c/src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.Android.cs#L139  in EditTextCursorColorChanger accesses the mCursorDrawableRes field which is not supported.  It was graylisted < 29 and per 29 it is blacklisted: https://developer.android.com/about/versions/10/non-sdk-q

This is referenced in https://github.com/unoplatform/uno/issues/5491 however the PR does not remove the access to this field rather more error handling.

Officially I think the recommendation is: https://developer.android.com/reference/android/widget/TextView#setTextCursorDrawable(int)  it was only added in v29 however I understand that is now the minimum version for uno anyway so could probably just swap over to using it exclusively.

**Comment by jeromelaban** [comment]
Thanks for the report!

Curiously, this is not something that we've seen recently in apps running even on recent devices. Is this preventing the app from running, or you've only seen this message in the logs?

**Comment by mitchcapper** [comment]
it does not prevent it running, it throws a hard exception in visual studio when debugging and I would assume the code doesn't work given the fact it is blacklisted now that uno targets 29.

**Comment by mitchcapper** [comment]
Sorry I misunderstood the android sdk targetting vs minimum sdk version (or really min platform).   As uno supports back to Android 5 the existing api switch would need expanding along with some re-work:
https://github.com/unoplatform/uno/blob/14c3ae67d3f52334394afa468dcf734d9cff985c/src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.Android.cs#L145-L153

Adding one for 29 and higher using the new SetTextCursorDrawable.  The main thing would be removing the initial call to get the old mCursorDrawableRes unless version < 29 to avoid the error.

**Comment by jeromelaban** [comment]
Thanks for the investigations! Indeed this was probably done prior to API 29, where there was no replacement for this API.
