### ISSUE TITLE
Uno.WinUI support for Windows Community Toolkit

### ISSUE THREAD

**Issue by deanchalk** [unoplatform/uno#6241]
## Current behavior

I create a new Uno project with the cli:
dotnet new unoapp-winui -o InterlinkedUno
The solution built correctly
Then I added the nugget package:
Uno.Microsoft.Toolkit.Uwp.Controls.DataGrid
and when building I get this error:

Error	CS0433	The type 'SuspendingEventArgs' exists in both 'Microsoft.Windows.SDK.NET, Version=10.0.18362.10, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'	InterlinkedUno.Windows.Desktop	D:\Projects\CompetingWebTools\InterlinkedUno\InterlinkedUno.Shared\App.xaml.cs

## Expected behavior

It should build without error

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

You can only add this package on Uno projects, not on the UWP/WinUI projects. If you want to use the datagrid control, you'll need to use Microsoft.Toolkit.Uwp.Controls.DataGrid instead.

You can find an example for this here: https://github.com/unoplatform/Uno.Samples/tree/master/UI/UnoWCTDataGridSample

**Comment by deanchalk** [comment]
You need to re-open this

If you look at my issue, it clearly states that this is a Uno project NOT a UWP project

**Comment by jeromelaban** [comment]
My apologies, this is indeed not a UWP project issue.

Uno does not support the windows community toolkit for WinUI projects yet.

**Comment by jeromelaban** [comment]
My apologies, this is indeed not a UWP project issue.

Uno does not support the windows community toolkit for WinUI projects yet. I'll rename the issue so it fits the description.

**Comment by giraudremy** [comment]
Hi,

Any update about this issue ? Does uno now support Windows Community Toolkit for WinUi project ?

I have tried to reference 'uno.microsoft.toolkit.uwp.ui' but I have this error
error UNOB0001: Cannot build with both Uno.WinUI and Uno.UI nuget packages referenced.

**Comment by jeromelaban** [comment]
Support is now available in latest builds of the community toolkit: https://github.com/unoplatform/Uno.WindowsCommunityToolkit#uno-platform-port-of-windows-community-toolkit
