### ISSUE TITLE
ItemsControl - Poor performance of updates of ItemsSource when bound to ObservableCollection

### ISSUE THREAD

**Issue by kotturtech** [unoplatform/uno#6251]
## Current behavior

Use Case:

- An ItemsControl is used to display UI items
- The ItemsSource property of the ItemsControl is bound to an ObservableCollection
- The ObservableCollection may be modified dynamically at runtime.

Observe the following [screen capture](https://drive.google.com/file/d/1ZPoQPX0Tl_KRRgXgnc6fRYVHMJiul32h/view?usp=sharing) :

It can be seen that once an item is added or removed, all items flicker, as if all the items are being deleted and recreated.
Additionally, there is a noticeable delay between the clicking of add or remove buttons and the appearance of the item, and
every update there is a following output to the debug log:

> [art] Starting a blocking GC Explicit
[art] Explicit concurrent mark sweep GC freed 42014(2MB) AllocSpace objects, 0(0B) LOS objects, 37% free, 6MB/10MB, paused 333us total 8.068ms
[Mono] GC_TAR_BRIDGE bridges 13330 objects 1484717 opaque 1607175 colors 13927 colors-bridged 13308 colors-visible 13308 xref 3229 cache-hit 528 cache-semihit 27 cache-miss 619 setup 0.36ms tarjan 182.01ms scc-setup 0.77ms gather-xref 0.16ms xref-setup 0.06ms cleanup 77.87ms
[Mono] GC_BRIDGE: Complete, was running for 139.10ms
[Mono] GC_MAJOR: (Minor allowance) time 301.30ms, stw 302.07ms los size: 3072K in use: 1337K
[Mono] GC_MAJOR_SWEEP: major size: 132208K in use: 108100K

## Expected behavior

- Unrelated items are unaffected by adding or removing items from the ItemsSource collection
- Better performance is expected - User shouldn't experience any noticeable delay when adding or removing items

## How to reproduce it (as minimally and precisely as possible)

As per use case described above:

1. Create a ViewModel with a property of type: ObservableCollection that would contain the items, plus commands to add and remove items from the collection
2. Create a View that contains an ItemsControl, with its ItemsSource property bound to the property of the ViewModel.
3. Add buttons to activate the Add and Remove commands for items

The effect will be noticed particularly if the ItemTemplate is a complex one. Also, the issue is particularly acute on Android,
while on UWP with a powerful computer it isn't very noticable

## Workaround

I have created a following control as a replacement for ItemsControl in my case, and it provides satisfying performance.
Its concept may be a suggestion for a solution for this issue. The main area of interest here is the handling of the change of Items property

`
`

    [TemplatePart(Name = TP_ScrollViewer, Type = typeof(ScrollViewer))]
    [TemplatePart(Name = TP_ItemsPanel, Type = typeof(Panel))]
    public partial class DynamicItemsControl : Control
    {
        const string TP_ItemsPanel = "ItemsPanel";
        const string TP_ScrollViewer = "ScrollViewer";

        private ScrollViewer _scrollViewer;
        private Panel _itemsPanel;
        private bool _isItemsCollectionObservable;

        public DynamicItemsControl()
        {
            DefaultStyleKey = typeof(DynamicItemsControl);
        }
        public IEnumerable Items
        {
            get { return (IEnumerable)GetValue(ItemsProperty); }
            set { SetValue(ItemsProperty, value); }
        }

        public static readonly DependencyProperty ItemsProperty =
            DependencyProperty.Register("Items", typeof(IEnumerable), typeof(DynamicItemsControl), new PropertyMetadata(null,ItemsCollectionChanged));

        public DataTemplate ItemTemplate
        {
            get { return (DataTemplate)GetValue(ItemTemplateProperty); }
            set { SetValue(ItemTemplateProperty, value); }
        }

        public static readonly DependencyProperty ItemTemplateProperty =
            DependencyProperty.Register("ItemTemplate", typeof(DataTemplate), typeof(DynamicItemsControl), new PropertyMetadata(null));

        protected override void OnApplyTemplate()
        {
            _scrollViewer = (ScrollViewer)GetTemplateChild(TP_ScrollViewer);
            _itemsPanel = (Panel)GetTemplateChild(TP_ItemsPanel);
            _itemsPanel.SizeChanged += _itemsPanel_SizeChanged;
            UpdateItemVisuals();
            base.OnApplyTemplate();
        }
        private void _itemsPanel_SizeChanged(object sender, SizeChangedEventArgs args)
        {
            if (_scrollViewer == null || args.PreviousSize.Height == 0.0f && args.PreviousSize.Width == 0.0f)
                return;
            double offsetX = 0.0, offsetY = 0.0;
            if (_scrollViewer.ViewportWidth < args.NewSize.Width)
                offsetX = _scrollViewer.ScrollableWidth;
            if (_scrollViewer.ViewportHeight < args.NewSize.Height)
                offsetY = _scrollViewer.ScrollableHeight;

            if (offsetX != 0.0f || offsetY != 0.0f)
                _scrollViewer.ChangeView(offsetX, offsetY, 1.0f);
        }

        private static void ItemsCollectionChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs args)
        {
            var thisObj = (DynamicItemsControl)dependencyObject;
            if (args.OldValue != null && thisObj._isItemsCollectionObservable)
            {
                var observableCollection = (INotifyCollectionChanged)args.NewValue;
                observableCollection.CollectionChanged -= thisObj.ItemsCollectionChanged;
            }

            if (args.NewValue == null)
                thisObj._itemsPanel.Children.Clear();
            else
            {
                if (args.NewValue is INotifyCollectionChanged)
                {
                    thisObj._isItemsCollectionObservable = true;
                    var observableCollection = (INotifyCollectionChanged)args.NewValue;
                    observableCollection.CollectionChanged += thisObj.ItemsCollectionChanged;
                }
                else
                    thisObj._isItemsCollectionObservable = false;
            }

            thisObj.UpdateItemVisuals();
        }

        protected virtual ContentControl CreateItemVisual()
        {
            var result = new ContentControl();
            if (ItemTemplate != null)
                result.ContentTemplate = ItemTemplate;
            return result;
        }

        private void ItemsCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            switch(e.Action)
            {
                case NotifyCollectionChangedAction.Add:
                    {
                        foreach(var item in e.NewItems)
                        {
                            var visual = CreateItemVisual();
                            visual.Content = item;
                            _itemsPanel.Children.Add(visual);
                        }
                        break;
                    }
                case NotifyCollectionChangedAction.Remove:
                    {
                        foreach(var item in e.OldItems)
                            for(var i = 0; i < _itemsPanel.Children.Count; i++)
                            {
                                if (((ContentControl)_itemsPanel.Children[i]).Content.Equals(item))
                                {
                                    _itemsPanel.Children.RemoveAt(i);
                                    break;
                                }    
                            }
                        break;
                    }
                case NotifyCollectionChangedAction.Replace:
                case NotifyCollectionChangedAction.Move:
                case NotifyCollectionChangedAction.Reset:
                    UpdateItemVisuals();
                    break;
            }
        }

        private void UpdateItemVisuals()
        {
            if (_itemsPanel == null)
                return;
            if (Items == null)
            {
                if (_itemsPanel.Children.Count > 0)
                    _itemsPanel.Children.Clear();
                return;
            }

            var childIdx = 0;
            var itemsCount = 0;
            var existingChildrenCount = _itemsPanel.Children.Count;
            foreach (var newItem in Items)
            {
                ContentControl visual = null;
                var recyclingVisuals = childIdx < existingChildrenCount;
                if (recyclingVisuals)
                    visual = (ContentControl)_itemsPanel.Children[childIdx++];
                else
                    visual = CreateItemVisual();

                visual.Content = newItem;

                if (!recyclingVisuals)
                    _itemsPanel.Children.Add(visual);             
                itemsCount++;
            }

            if (itemsCount < existingChildrenCount)
                for (var i = itemsCount; i < existingChildrenCount; i++)
                    _itemsPanel.Children.RemoveAt(i);
        }
    }
`
`
## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI 3.7.6

Affected platform(s):
I have tested on the following platforms:
- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [X] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.9.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

There's a newer implementation of this control that may be more suited for what you need: https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.itemsrepeater?view=winui-3.0

Can you try and see if this helps for the performance aspect ?

**Comment by davidjohnoliver** [comment]
If a ListView (with default ItemsPanel of ItemsStackPanel) works in your scenario, you should also find that it has much better performance with collection updates than ItemsControl.

**Comment by kotturtech** [comment]
Hi Jerome,

I've tried what you suggested, indeed using ItemsRepeater works well in my
scenario.

Thanks for the advice :)
