### ISSUE TITLE
DatePicker VisualStateGroup "HasDateStates" does not work in Uno

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#6256]
## Current behavior

In UWP, DatePicker gives us additional visual state that we can use depending on whether the user has selected a date or not.

```xaml
<VisualStateGroup x:Name="HasDateStates">
	<VisualState x:Name="HasDate">
		<VisualState.Setters>
			<Setter Target="PlaceholderText.Visibility"
				Value="Collapsed" />
			<Setter Target="DateText.Visibility"
				Value="Visible" />
			<Setter Target="RootGrid.Background"
				Value="Green" />
		</VisualState.Setters>
	</VisualState>
	<VisualState x:Name="HasNoDate">
		<VisualState.Setters>
			<Setter Target="PlaceholderText.Visibility"
				Value="Visible" />
			<Setter Target="DateText.Visibility"
				Value="Collapsed" />
			<Setter Target="RootGrid.Background"
				Value="Red" />
		</VisualState.Setters>
	</VisualState>
</VisualStateGroup>
```

However, when used with uno, it does not seems to work.
![actual](https://user-images.githubusercontent.com/17461593/121928912-a49e3500-cd0e-11eb-8f45-b9db41aebeb6.gif)

## Expected behavior

![expected](https://user-images.githubusercontent.com/17461593/121928563-440ef800-cd0e-11eb-82ef-4edcb08a1f82.gif)

## How to reproduce it (as minimally and precisely as possible)

Download this sample [DatePickerTransition.zip](https://github.com/unoplatform/uno/files/6649958/DatePickerTransition.zip)
Deploy on any other platforms than UWP (to see the bug)
Select a date

## Workaround

Technically, manually change the visibility depending on `SelectedDate` property with a Converter works.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 

Affected platform(s): 3.9.0-dev.17

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version:16.8.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment]
@MartinZikmund Is this something that going to be fixed with your rewrite and removal of mixins?
