### ISSUE TITLE
[Gallery][Android/iOS]Button- The clicking effect is missing for Fluent and Cupertino in iOS and for Cupertino in Android

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6258]
## Current behavior

https://user-images.githubusercontent.com/74563602/121944701-f0f27080-cd20-11eb-9109-bc85e0536fd2.MOV

## Expected behavior
The Button should be clicked.

## How to reproduce it (as minimally and precisely as possible)
Open the Gallery App
Click/tap "Button" from the "Component" list.
Click on the Buttons for Fluent and Cupertino.
Observe that for the Buttons the clicking effect is missing for Fluent and Cupertino in iOS and for Cupertino in Android.

Nuget Package Version(s):

Affected platform(s):

- [X] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by sakshi173** [comment]
@MartinZikmund , Please let me know your views, is this bug valid? 
I can repro this bug but not sure, is this requirement or not.

**Comment by jeromelaban** [comment]
On iOS, the "tap" effect takes a few milliseconds to appear. You'll notice that it shows up when keeping the button pressed. @dr1rrb certainly can comment on this.

**Comment by dr1rrb** [comment]
This is native feature of iOS https://developer.apple.com/documentation/uikit/uiscrollview/1619398-delayscontenttouches You should not see any delay if your content is not in any `ScrollViewer` (or all scroll has been disabled).

**Comment by agneszitte** [comment]
@sakshi173 can you please re-test this issue with latest canaries please

**Comment by sakshi173** [comment]
Verified, this issue is fixed, closing it.
