### ISSUE TITLE
[Gallery][WASM/Android/iOS]ElevatedView- The Elevated line are not displaying properly for dp in night mode.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6259]
## Current behavior
![elevated view](https://user-images.githubusercontent.com/74563602/121957801-e50eaa80-cd30-11eb-8d25-60d5cddc3f71.png)

## Expected behavior
Line should display correctly.

## How to reproduce it (as minimally and precisely as possible)
Launch the Uno.Gallry app 
Click on “ElevatedView” from the "Component" list.
Observe that the lines are not displaying correctly for dp.

Affected platform(s):

- [X] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
The elevation is here, but darkening something which is dark is difficult to see. We could change this with another color to make it more visible, but that's not an issue for now.

**Comment by sakshi173** [comment]
As per the Jerome comment its not an issue, due to that closed it.
