### ISSUE TITLE
Redirection of the webpages seems to be broken on AsyncWebView only on Android.

### ISSUE THREAD

**Issue by ac2021-June** [unoplatform/uno#6264]
## Current behavior
User gets an unexpected error, when on the page having an AsynWebView control. When user is navigated to the page, where we have a AsyncWebView control, various re-directions happen on the page as we want the user’s session already present when we land on the final desired page. 
As we are performing various redirections, so at a given point we get URI as null (only on Android, iOS no issue), which results in an error; after 2 re-direction only on Android device. 

## Expected behavior
User should successfully land on the final desired page without any error. 

## How to reproduce it (as minimally and precisely as possible)
Perform various re-directions on AsyncWebView on an Android device.

## Workaround

None.

## Environment
All environments.

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

- "Uno.Core" - 2.2.0
- "Uno.Serialization" - 1.25.0
- "Uno.UI" - 3.6.6

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
Same code works fine on the previous version of UNO.

-  "Uno.Core"- 1.29.0
- "Uno.Serialization" - 1.24.0
- "Uno.SourceGenerationTasks" - 1.32.0
- "Uno.UI" - 1.45.0

**Comment by jeromelaban** [comment]
Thanks for the report.

In order to help troubleshoot the issue, we'll need a simple reproduction project that clearly demonstrates the issue.

To create a minimal reproduction project:
 - Create an Uno app through `dotnet new unoapp`, or through the [Visual Studio extension](https://platform.uno/docs/articles/get-started-vs.html).
 - Make sure to add the least code possible to demonstrate the issue
 - Keep all project heads, even if the platforms are seemingly not relevant to your issue
 - Remove all the `obj/bin` folders and zip the folder.
 - Attach the zip file to the issue

**Comment by renecnventive** [comment]
Reopening with Repo link. Please reach out to Rene Charbonneau for info on downloading the attached file if need.
https://nventive-my.sharepoint.com/:u:/p/rene_charbonneau/EWPutwbOk6NFm0SJfb12fD4Bv6eAPeEb1wCWhAEjjf1oWw?e=unmK8H

**Comment by ac2021-June** [comment]
Steps to reproduce alongwith the sample application shared on the shared folder.

**Comment by renecnventive** [comment]
Steps to reproduce:
1)	Run the Android application as the issue reproducible only on android device. On iOS device it works fine!
1)	Login to the application
a.	Username: ac019312
b.	Password: Test1234
c.	Environment: Development
2)	From the hamburger menu, select Flight Search menu.
3)	Click on Search Flights button.
4)	The flight search results will get display. 
5)	Now swipe left to get the + icon beneath the tile. Click on the + icon, to add it to the shopping cart widget.
6)	Once the flight is added, simply click on the “Book on the ETS” button. 
7)	The navigation due to various redirections seems to be broken on android. 
8)	Currently it works well on iOS with the current code. The same code worked well with the previous versions of UNO on both iOS and Android.


note: more streamlined sample has been requested

**Comment by ac2021-June** [comment]
When we assign value to SourceHtml, in the previous version of AsynWebView i.e. on umbrella () 
CompletionCommandArgs arg.Uri was getting assigned some value. But now in the upgraded version of the AsynWebview, the Uri is coming as null on Android and about:blank on iOS devices. So thats the reason we are able to proceed on iOS devices, but getting an error on Android device. Please suggest as what needs to be done in this case. 
![image](https://user-images.githubusercontent.com/85895535/128423333-95e96011-4a21-4aa0-917b-5247c8740870.png)

**Comment by ac2021-June** [comment]
Working nuget packages list in the project file:
  <PackageReference Include="Umbrella.Analytics.AppCenter">
      <Version>3.6.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.App.Modules.AppCenter">
      <Version>3.8.2</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.View">
      <Version>3.7.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.View.Legacy">
      <Version>3.7.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.Social.Phone">
      <Version>3.6.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.View.MessageDialog">
      <Version>3.7.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.Notifications.Local">
      <Version>3.6.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.Analytics.Core">
      <Version>3.6.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.Environment.ApplicationLauncher">
      <Version>3.6.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.Storage.Biometry.UWP">
      <Version>3.6.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.ActiveCommands.UWP">
      <Version>3.7.1</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.AsyncValue.UWP">
      <Version>3.7.1</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.StructuredContent.UWP">
      <Version>3.7.1</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.Query">
      <Version>3.7.1</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.Analyzers">
      <Version>1.5.0</Version>
    </PackageReference>

  and non working nuget packages list in the project file:
<PackageReference Include="Umbrella.Analytics.AppCenter">
      <Version>4.0.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.App.Modules.AppCenter">
      <Version>4.0.1</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.View">
      <Version>4.0.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.View.Legacy">
      <Version>4.0.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.Social.Phone">
      <Version>4.0.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.View.MessageDialog">
      <Version>4.0.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.Notifications.Local">
      <Version>4.0.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.Analytics.Core">
      <Version>4.0.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.Environment.ApplicationLauncher">
      <Version>4.0.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.ActiveCommands.UWP">
      <Version>4.0.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.AsyncValue.UWP">
      <Version>4.0.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.StructuredContent.UWP">
      <Version>4.0.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.Query">
      <Version>4.0.0</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.Analyzers">
      <Version>1.6.0</Version>
    </PackageReference>
    <PackageReference Include="UmbrellaApp.Modules.Base">
      <Version>4.0.1</Version>
    </PackageReference>
    <PackageReference Include="UmbrellaApp.Modules">
      <Version>4.0.1</Version>
    </PackageReference>
    <PackageReference Include="UmbrellaApp.Modules.Views">
      <Version>4.0.1</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.App.Tasks">
      <Version>1.10.56</Version>
    </PackageReference>
    <PackageReference Include="Umbrella.Navigation">
      <Version>4.0.0</Version>

**Comment by jeromelaban** [comment]
Thanks for the update. Are you able to reproduce this using an Uno WebView directly?

**Comment by ac2021-June** [comment]
As we are using SourceHtml here with AsyncWebView, please guide as how we would convert this control to WebView?

<uw:AsyncWebView x:Name="ETSWebView"
                         SourceMessage="{Binding [NavigationRequest]}"
                         SourceHtml="{Binding [SourceHtml]}"
                         CompletionCommand="{Binding [NavigationCompleted]}"
                         IsClearingOnUnload="True" />

**Comment by jeromelaban** [comment]
We only provide the support from the Uno controls in this repository, and AsyncWebView is not an Uno control, so if you can reproduce it with an Uno WebView, we'll be able to help.

**Comment by ac2021-June** [comment]
We figured out a workaround, hence closing the issue.
