### ISSUE TITLE
Exception thrown when using NavigationView in WinUI3 project

### ISSUE THREAD

**Issue by jaldinger** [unoplatform/uno#6266]
## Current behavior

Exception thrown when starting to debug "hello world" with NavigationView.
![image](https://user-images.githubusercontent.com/20828844/121972852-0cbe3c80-cd4a-11eb-994a-585381663394.png)

## Expected behavior

No exception should be thrown

## How to reproduce it (as minimally and precisely as possible)

Create new WinUI3 project using
`dotnet new unoapp-winui`

In MainPage.xaml, place a NavigationView in the content of Page in MainPage.xaml, e.g.:
`<NavigationView />`

Set "testapp.Windows.Package" as Startup project in Visual Studio, and x86 as Platform. 

Start Debug.

## Workaround

None that I know of.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.8.6

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.10.1)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Tried this on two different machines, but with the same software versions. Same result on both.

**Comment by jeromelaban** [comment]
Thanks for the report.

This error generally happens when the project is started through the `.Desktop` project and not the `.Package` project.

Can you validate if this happens when starting the latter ?

**Comment by jaldinger** [comment]
I don't _think_ I'm running the wrong project. But this is what it looks like:

![image](https://user-images.githubusercontent.com/20828844/122052954-475cbf00-cdb4-11eb-878d-dc29a80054f0.png)

**Comment by jeromelaban** [comment]
Thanks. Indeed, with Reunion 0.5.x, the NavigationView seems to fail.

Of you upgrade to 0.8-rc that was released yesterday, the app starts properly. You'll need to change `TargetPlatformMinVersion` to `10.0.19041.0` in the `.Package` project, as well as the `0.5.6` references.

**Comment by jaldinger** [comment]
Thanks for this info. Does upgrading the `TargetPlatformMinVersion` mean that the final app would not run on Windows 10 versions below that one? Also, is this exception something that will be fixed on Project Reunion 0.5 or should we just move to 0.8 as of now, since the roadmap says it's going to be GA in Q2/2021, which runs just for two more weeks?

**Comment by jeromelaban** [comment]
Thanks for the update.

We do not have those details about the Project Reunion support. Those would be questions for the WinUI team and repository.
