### ISSUE TITLE
[WASM] CalendarDatePicker is incorrectly marked as not implemented

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#6268]
I'm getting this warning with latest Uno.UI.WebAssembly 3.8.6 (official)
` warning Uno0001: Windows.UI.Xaml.Controls.CalendarDatePicker is not implemented in Uno`

However, [here ](https://github.com/unoplatform/uno/issues/3750) it says it would be supported.

Which one is right?

**Comment by jeromelaban** [comment]
Thanks for the report, Dierk. As in most cases, if running it gives you the proper result the message is not appropriate.

**Comment by DierkDroth** [comment]
Thanks for clarification @jeromelaban

**Comment by DierkDroth** [comment]
Also: I suggest updating [docs](https://platform.uno/docs/articles/implemented-views.html) accordingly.

**Comment by carldebilly** [comment]
@DierkDroth The documentation will be adjusted automatically since it's generated from the code.

I see you closed this issue... that's not required, the PR would have close it automatically.  Anyway that's not really a problem.

**Comment by DierkDroth** [comment]
Thanks for educating me @carldebilly
