### ISSUE TITLE
[Gallery][Wasm] Lottie- Lottie is missing.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6277]
## Current behavior
![lottie issue](https://user-images.githubusercontent.com/74563602/122117040-5cf1d900-cdf4-11eb-8115-a5e3146423ec.png)

## Expected behavior
![lottie correct](https://user-images.githubusercontent.com/74563602/122117049-60856000-cdf4-11eb-9ff1-429566c2a35b.png)

## How to reproduce it (as minimally and precisely as possible)
Open the link https://unogallerycanary.z27.web.core.windows.net/
From the left menu scroll to Features section
Click on Lottie.
Observe that the lottie is missing.

Nuget Package Version(s):
Canary Build :- 1.5.0-canaries-dev.758
https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=29748&view=results

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
This is a regression from #6232

**Comment by sakshi173** [comment]
Verified, Issue is fixed, closing
