### ISSUE TITLE
[WASM] TextBlock cuts off text in some situations

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#6282]
## Current behavior

Something since Uno.UI.WebAssembly v3.6.0-dev.378 has changed that causes some text blocks to cut off text. Notice the pivot headers and the hyperlink text at the bottom getting cut off here:

![image](https://user-images.githubusercontent.com/1700111/122212039-653e2880-ce75-11eb-82e9-201d2a33b54e.png)

## Expected behavior

On UWP it looks like this:

![image](https://user-images.githubusercontent.com/1700111/122212131-80109d00-ce75-11eb-81c7-d97b34dd2037.png)

## How to reproduce it (as minimally and precisely as possible)

```xml
<HyperlinkButton FontSize="18" HorizontalAlignment="Center" Click="OnForgotPasswordClick" Margin="0,20,0,0">
    <Border>
        <TextBlock Text="I forgot my password"/>
    </Border>
</HyperlinkButton>
```

Putting `Padding="5"` on the `TextBlock` causes the text to disappear entirely.

I am using the [Selawik font](https://www.fontsquirrel.com/fonts/selawik), not sure if that makes a difference.

## Workaround

None.

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):  v3.8.6, v3.9.0-dev.54

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report. 

If you are changing the font, the browser uses delay-loading which causes uno to misread sizes. To fix this, you'll need to [use this workaround](https://github.com/unoplatform/uno/issues/693).

Let us know if this helps.

**Comment by mikernet** [comment]
That did it, thanks :)
