### ISSUE TITLE
[WASM] HyperlinkButton underlines TextBlock content

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#6283]
## Current behavior

Looks like this in WASM:

![image](https://user-images.githubusercontent.com/1700111/122214476-21005780-ce78-11eb-99ed-0d7cafe40cf9.png)

## Expected behavior

Looks like this in UWP:

![image](https://user-images.githubusercontent.com/1700111/122214558-3b3a3580-ce78-11eb-8033-398b5e2723c3.png)

## How to reproduce it (as minimally and precisely as possible)

```xml
<HyperlinkButton>
    <TextBlock Text="I forgot my password"/>
</HyperlinkButton>
```

## Workaround

Put `TextBlock` inside a `Border`.

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): v3.6.0-dev.378, v3.8.6, v3.9.0-dev.54

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
This behavior is defined here as a best effort:

https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Controls/Button/HyperlinkButton.cs#L27-L38

We may need to revisit it to alter the behavior.

**Comment by mikernet** [comment]
Yeah, I provide an explicit textblock for content specifically to remove the underlining that hyperlink buttons otherwise do.

**Comment by Youssef1313** [comment]
@MartinZikmund You fixed this in https://github.com/unoplatform/uno/pull/6762. Can you close please?
