### ISSUE TITLE
Implicit `TextBlock` styles incorrectly affect control layout calculations

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#6284]
## Current behavior

Implicit text block styles in scope of some controls mess up layout calculations. For example, this is what comboboxes look like on `Uno.IU` platforms (iOS, WASM) when a textblock style with a large top margin is present:

![image](https://user-images.githubusercontent.com/1700111/122214897-a257ea00-ce78-11eb-8492-30c8d3a4b962.png)

Checkbox checkmarks are also offset:

![image](https://user-images.githubusercontent.com/1700111/127652397-3155995b-5a8d-4c72-80f0-7a43f889cb87.png)

## Expected behavior

Looks like this on UWP:

![image](https://user-images.githubusercontent.com/1700111/122215073-d4694c00-ce78-11eb-814a-7be4e79736f4.png)

![image](https://user-images.githubusercontent.com/1700111/127652480-cee2a7cc-b25e-42b8-b6d5-ab270f4a009a.png)

## How to reproduce it (as minimally and precisely as possible)

http://playground.platform.uno/#8edc1bb5

## Workaround

```xml
<ComboBox>
    <ComboBox.Resources>
        <Style TargetType="TextBlock"/>
    </ComboBox.Resources>
</ComboBox>
```

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): v3.6.0-dev.378, v3.8.6, v3.9.0-dev.54

Affected platform(s):

- [X] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

I'm not seeing the behavior you're reporting: https://playground.platform.uno/#8e26c2fc

Can you create a larger repro case or playground link for your issue?

**Comment by mikernet** [comment]
I'm trying to copy all my styles over to narrow it down but getting errors like "Implicit content is not supported on SolidColorBrush" and "Implicit content is not supported on Thickness" for some odd reason:

https://playground.platform.uno/#1afad173

**Comment by mikernet** [comment]
Okay. I think I found the problem: https://playground.platform.uno/#78d184a5

**Comment by mikernet** [comment]
Actually that's not true - the font size makes it do weird layout stuff when it first loads as well: https://playground.platform.uno/#78d184a5

**Comment by mikernet** [comment]
I found a workaround for now: add an empty `TextBlock` style into the `ComboBox` resources, i.e:
```xml
<ComboBox>
    <ComboBox.Resources>
        <Style TargetType="TextBlock"/>
    </ComboBox.Resources>
</ComboBox>
```

**Comment by mikernet** [comment]
Note this also affects checkbox checkmarks: https://playground.platform.uno/#7538a1cc
