### ISSUE TITLE
Visual Studio Project Template creates app that doesnt build

### ISSUE THREAD

**Issue by deanchalk** [unoplatform/uno#6288]
## Current behavior

In visual studio 2019 community (fully up to date) I create an app using the Uno WinUI template
![image](https://user-images.githubusercontent.com/11065294/122348658-4c03ad80-cf43-11eb-823a-14e5ba0f42c8.png)
But when you build this you get build errors
![image](https://user-images.githubusercontent.com/11065294/122348818-75bcd480-cf43-11eb-9fa2-1707eec62deb.png)

## Expected behavior

The project should build after creation

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ x] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ x] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

This is the template coming from the `dotnet new` installation, which behaves differently from its direct command line use.

Can you use `dotnet new unoapp-winui` instead to create the application ?
