### ISSUE TITLE
Skia.Gtk Textbox issue: caret position resets while typing and flickering on hovering

### ISSUE THREAD

**Issue by NBRizzoli** [unoplatform/uno#6289]
## Current behavior

While typing in a textbox the caret position randomly resets to the start of the text.
(Only in linux) Hovering on the textbox with the mouse also causes the height of the textbox to flicker; the flickering cotinue while writing.
While the flickering occours the caret doesn't reset, probabily the 2 issues are related.

## Expected behavior

Caret doesn't reset.
No flickering while hovering.

## How to reproduce it (as minimally and precisely as possible)

Create a new project, add a textbox.

On Windows:
 - Start the Skia.Gtk project and try typing on the textbox

On Windows with WSL2 or Linux
 - Start the Skia.Gtk, hover with the mouse on the textbox, type on the textbox.

## Workaround

No workaround found.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [ ] WPF
  - [x] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
@MartinZikmund do you know this issue still happens?

**Comment by Youssef1313** [comment]
Caret resets for me, but it happens when I type *toooooooooooo* fast.
