### ISSUE TITLE
[WASM] Add support for file drag and drop

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno#6293]
## What would you like to be added:

Add support for file drag and drop in WASM.  In UWP, you can set `AllowDrop="True"` and then hook the `DragEnter` and `Drop` events.  In the Drop event, you can see if the DragEventArgs has storage items by the following: `e.DataView.Contains(StandardDataFormats.StorageItems)`.  Then you can access the files: `await e.DataView.GetStorageItemsAsync();`

## Why is this needed:

We have requirements to allow users to drag and drop files onto certain areas of our UI and we upload them to our platform.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
It is actually now even possible to implement this using the new File System Access API (same as the more capable version of pickers), so that might allow modifying the dropped files in-place in supported browsers.
