### ISSUE TITLE
[Wasm] Uno.UI.js incorrectly requests splash screen

### ISSUE THREAD

**Issue by mmarinchenko** [unoplatform/uno#6294]
## Current behavior

First, [uno-bootstrap.js:247](https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/c849b4d6393b950440e2b045289c93ca838841b1/src/Uno.Wasm.Bootstrap/WasmScripts/uno-bootstrap.js#L247) **correctly** loads splash screen:

![image](https://user-images.githubusercontent.com/21952330/122407116-ce6b8c00-cf9a-11eb-88f5-45698c6c2e59.png)

![image](https://user-images.githubusercontent.com/21952330/122407226-e6dba680-cf9a-11eb-89c8-9ff6ca389e79.png)

---
But then, [Uno.UI.js:410](https://github.com/unoplatform/uno/blob/b3f185f07e04726c90d5777aa3302bb4b0a03965/src/Uno.UI/WasmScripts/Uno.UI.js#L412-L415) tries to do it **second time** and does it **incorrectly**:

![image](https://user-images.githubusercontent.com/21952330/122408276-ac263e00-cf9b-11eb-9665-64f77bc16ac3.png)

![image](https://user-images.githubusercontent.com/21952330/122408088-8a2cbb80-cf9b-11eb-9659-f7941f7b5d42.png)

![image](https://user-images.githubusercontent.com/21952330/122408167-9b75c800-cf9b-11eb-8408-6b672aa8e8c1.png)

---
## Expected behavior

1. Load splash screen correctly.
2. Do not try to load splash screen **twice**.

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

```xml
<PackageReference Include="Uno.UI.WebAssembly" Version="3.8.6" />
<PackageReference Include="Uno.Wasm.Bootstrap" Version="2.1.0" />
```

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.10.2)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
Thanks for the report, this is fixed in Uno 3.9-dev, and will be backported soon on Uno 3.8.x.
