### ISSUE TITLE
[WASM] Add support for Page caching in Frame controls

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno#6295]
## What would you like to be added:

Add support for `Page.NavigationCacheMode` in WASM.  

## Why is this needed:

We have pages that our users frequently use that would provide a performance increase if they were cached like they are in UWP.  It would be easier for this to be provided rather that adding a custom caching technique.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report. This is a duplicate of https://github.com/unoplatform/uno/issues/4156, let's track the other one.
