### ISSUE TITLE
Visual Studio 2022 support

### ISSUE THREAD

**Issue by LeftTwixWand** [unoplatform/uno#6307]
## What would you like to be added:
Make the VSIX extension available in Visual Studio 2022.
Now it's just not supported in the new version of VS:

![image](https://user-images.githubusercontent.com/50652041/122620981-fa6f3600-d09c-11eb-841e-e66167ecb03c.png)

Useful links:
- [Update a Visual Studio extension for Visual Studio 2022](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022)
- [Writing Visual Studio Extensions with Mads - 64bit extensions for Visual Studio 2022](https://www.youtube.com/watch?v=L8b3kFriwCs)
- [Writing Visual Studio Extensions with Mads - Splitting extensions for Visual Studio 2022](https://www.youtube.com/watch?v=-PKIPTW6km0)

**Comment by jeromelaban** [comment]
Thanks for the report! 

You can use the [`dotnet new` templates](https://platform.uno/docs/articles/get-started-dotnet-new.html) in the meantime.
