### ISSUE TITLE
Add WinUI `AnimatedIcon` for fallback scenarios

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#6309]
## What would you like to be added:

A basic implementation of WinUI `AnimatedIcon` which supports the `FallbackIconSource`

## Why is this needed:

Used in new 2.6 visual styles

## For which Platform:

All

**Comment by robloo** [comment]
@MartinZikmund How much of this was implemented? I was expecting it to work with Expander now with the 3.9.x release. However, expander still isn't animating the chevron.

https://github.com/unoplatform/uno/blob/e70c72425f5bc73cca71dee880e7a61d40b21e50/src/Uno.UI/Microsoft/UI/Xaml/Controls/Expander/Expander_themeresources.xaml#L365

![fassse](https://user-images.githubusercontent.com/17993847/127912370-9e71c129-b8ab-4c64-a62b-c861807aef57.gif)
