### ISSUE TITLE
Bug: [Android] Uno Platform App Unloads Immediately when Switching Between Apps

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#6317]
Copied from StackOverflow per @MartinZikmund's request.
https://stackoverflow.com/questions/68009034/how-to-prevent-an-uno-platform-app-from-unloading-when-switching-between-apps-on

## Current behavior

The issues is the same as described here: https://forums.xamarin.com/discussion/21400/forms-app-loses-all-state-and-boots-from-scratch-when-switching-between-apps

On Android, an Uno Platform app will be immediately unloaded and go into the background when switching between apps. This means when the Uno App is returned to by the user it must completely reload it's state. Restoring state is possible but has some serious down sides::

 * It is a performance issue
 * Why reload state if the user is simply copy/pasting from another app?
 * In some app views (such as form entry) changes aren't applied until the user presses save. This means any changes are lost as the view is reloaded. Fixing this is a big tear-up as all state information, event transient, needs to be stored at shutdown/startup.

Note that the Uno Platform's port of Windows Calculator does not have this issue. However, if the Windows Calculator goes into the background for several minutes, it seems to go into an error-state (a separate but perhaps related issue).

## Expected behavior

Ideally a solution is needed to prevent Android from unloading the app and putting in the background as soon as the user switches apps. It should only be unloaded after not being used for a while.

## Workaround

The docs in Xamarin are unclear but the only plausible solution seems to be adding android:largeHeap="true" in the Android manifest file. This is so far untested.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.8.6

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. The `largeHeap` option has been tested extensively in large apps, and it working properly.

**Comment by robloo** [comment]
Thanks for confirming that is what is being used to solve this issue on your end. Is there a good place I can add this to the docs for others?

**Comment by jeromelaban** [comment]
The default template for uno apps already contains this feature flag enabled:

https://github.com/unoplatform/uno/blob/8cff819daaa72bbe694a06ffdc21424aa186d8f4/src/SamplesApp/SamplesApp.Droid/Main.cs#L19

It be interesting to understand why setting this flag differently on your app has an impact.

**Comment by robloo** [comment]
I confirmed the `LargeHeap` attribute is being set on the application class as you stated. This is unfortunate as it likely means this is a larger concern.

I will have to spend more time on profiling the performance: Either the large heap isn't large enough, or more likely so much memory is used by the app that Android unloads it as soon as it can to free memory for other apps. This may be very difficult to fix.

**Comment by jeromelaban** [comment]
That is something you can generally debug pretty easily with the Xamarin memory profiler, but it's not a behavior we've observed on apps, even larger ones.

**Comment by jeromelaban** [comment]
Did you see anything in the logs indicating why the app may be terminated / unloaded ? Otherwise, there's not much we can do at this point.

**Comment by robloo** [comment]
Xamarin Profiler is only available in Visual Studio Enterprise and isn't worth it to upgrade to at this point. This means I won't have detailed logs to look at.

Since it seems you want to close this I will. You confirmed large heap is what is used to prevent it. However, I may reopen it if new information comes to light. In general, Android apps can't be instantly unloaded but since you don't see it in other apps I'll assume it is an issue on my end for now.

**Comment by jeromelaban** [comment]
Thanks for the update. If you find anything specific, let us know!
