### ISSUE TITLE
[WASM] obj.SetValue(FrameworkElement.WidthProperty) ignores MinWidth/MaxWidth.

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#6319]
Likewise for Height/MinHeight/MaxHeight.
The UWP, however, handles this code correctly and prevents modification.

**Comment by jeromelaban** [comment]
Thanks for the report.

Can you open another issue with [this template](https://github.com/unoplatform/uno/issues/new?assignees=&labels=kind%2Fbug%2C+triage%2Funtriaged%2C+difficulty%2Ftbd&template=bug-report.md), and provide a repro ?

**Comment by HavenDV** [comment]
It doesn't seem to work for Xaml Extensions only.
Context Code:
```cs
using System;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls.Primitives;

#nullable enable

namespace Dedoose.Extensions
{
    public static class ResizeExtensions
    {
        #region AttachedProperty : Target

        public static readonly DependencyProperty TargetProperty =
            DependencyProperty.RegisterAttached(
                nameof(TargetProperty).Replace("Property", string.Empty),
                typeof(object),
                typeof(ResizeExtensions),
                new PropertyMetadata(null, OnTargetChanged));

        public static object? GetTarget(DependencyObject element)
        {
            return element.GetValue(TargetProperty);
        }

        public static void SetTarget(DependencyObject element, object? value)
        {
            element.SetValue(TargetProperty, value);
        }

        private static void OnTargetChanged(
            DependencyObject element,
            DependencyPropertyChangedEventArgs args)
        {
            if (element is not Thumb thumb)
            {
                return;
            }

            if (args.NewValue != null)
            {
                thumb.DragDelta += Thumb_DragDelta;
            }
            else
            {
                thumb.DragDelta -= Thumb_DragDelta;
            }
        }

        private static void Thumb_DragDelta(object sender, DragDeltaEventArgs e)
        {
            if (sender is not Thumb thumb ||
                GetTarget(thumb) is not FrameworkElement obj)
            {
                return;
            }

            obj.SetValue(
                FrameworkElement.WidthProperty,
                Math.Max(0.0, obj.ActualWidth + e.HorizontalChange));
            obj.SetValue(
                FrameworkElement.HeightProperty,
                Math.Max(0.0, obj.ActualHeight + e.VerticalChange));
        }

        #endregion
    }
}
```

**Comment by jeromelaban** [comment]
Please open another issue, with the directions described there, it'll be easier to help you. Thanks!

**Comment by HavenDV** [comment]
I was unable to replicate the exact conditions in the test project. I will come back to this when I see addiction.
P.S: Add `dotnet new unoapp --install Uno.ProjectTemplates.Dotnet` the command to the installation instructions to speed up the creation of a test project if templates are not installed. 
This will also update the templates to the latest stable release, which will also eliminate issues with non-updated templates. 
If the templates are already installed and have a stable version, a new project will simply be created.

**Comment by HavenDV** [comment]
Please replace
- `dotnet new unoapp --install Uno.ProjectTemplates.Dotnet` and `dotnet new unoapp`
to 
- `dotnet new --install Uno.ProjectTemplates.Dotnet` and `dotnet new unoapp`

**Comment by HavenDV** [comment]
I want to note (just, perhaps you forgot or missed something) that the current template still contains an error
