### ISSUE TITLE
[Android] All AutoSuggestBoxs lists is opened when text property changed in the code.

### ISSUE THREAD

**Issue by eiadxp** [unoplatform/uno#6321]
## Current behavior
FOR ANDROID:

If we placed more than one AutoSuggestBox and set their ItemsSource properties, then changed in the code (or via binding) the Text properties of these AutoSuggestBoxs... All of them will open their suggestion lists when show show the page.

## Expected behvior
* The list should not be opened if the text property changed in the code unless it has focus (This is UWP behavior)
* Only one list should be opened at a time.

[App1.zip](https://github.com/unoplatform/uno/files/6695973/App1.zip)

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

As mentioned in the bug template, can you create a repro app, as well as screenshots and/or a video demonstrating the issue ?

**Comment by eiadxp** [comment]
I was able to specify the wrong behavior more accurately. I've changed the issue and attached the code file.

Best Regards

**Comment by Youssef1313** [comment]
Going to take a look at this tomorrow morning :)

It appears there are two issues here:

- The described issue open the list is opened when it shouldn't.
- The `Text` set doesn't actually show (probably it doesn't reflect on the underlying `TextBox`)
