### ISSUE TITLE
Add support for CoreWindow.GetForCurrentThread

### ISSUE THREAD

**Issue by yowl** [unoplatform/uno#633]
## I'm submitting a...

  
- Feature request

## Current behavior
This method is unsupported and throws an exception.   This will be useful for Telerik's control as they use it to get whether the key event is for "Down" 
```
            var state = window.GetKeyState(key);
            return (state & CoreVirtualKeyStates.Down) == CoreVirtualKeyStates.Down;
```

## Expected behavior
Return the current window for the current (and only in wasm) thread.

## Minimal reproduction of the problem with instructions
Add this code anywhere:
```
            var window = CoreWindow.GetForCurrentThread();
```

## Environment

```
Nuget Package: 
Uno.UI 1.43.0-dev.921
Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by jeromelaban** [comment]
This is implemented in 3.0
