### ISSUE TITLE
Update `Expander` to latest code

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#6345]
## What would you like to be added:

Update `Expander` to latest WinUI code

## Why is this needed:

Alignment

## For which Platform:

All

**Comment by robloo** [comment]
#5626 was already opened for this. Wish there was some discussion on that before this and the new PR were created.

**Comment by MartinZikmund** [comment]
@robloo sorry again, my fault. I completely forgot about that fact... We really need to do a summer cleaning of open PRs 😑
