### ISSUE TITLE
Does uno platform compliant with Microcharts（skiasharp based chart library which is typically used with xamarim forms）？

### ISSUE THREAD

**Issue by faywong** [unoplatform/uno#6354]

**Comment by MartinZikmund** [comment]
While I don't have any full example right now, the library is definitely compatible (see their README [here](https://github.com/dotnet-ad/Microcharts#compatibility)). Uno Platform is built on top of the same layers as Xamarin.Forms, so there is nothing that prevents the controls to work here too.
