### ISSUE TITLE
Haptic feedback using the Windows.Devices.Haptics not working

### ISSUE THREAD

**Issue by PhilippeAudet-Stratejia** [unoplatform/uno#6368]
## Current behavior
When sending a haptic feedback request on an android device, no vibration is perceived on the device. 

[Using this guide from the uno platform documentation](https://platform.uno/docs/articles/features/windows-devices-haptics.html), the behavior doesn't work when testing it on a physical device.

## Expected behavior
The device should be vibrating when `simpleHapticsController.SendHapticFeedback(feedbackType);` is called.

## How to reproduce it (as minimally and precisely as possible)
Setting up a button binded to a command in the viewModel or an event in the CodeBehind, and using the code mentionned above in the command, a vibration should be felt on the device when pressing the button.

A very simple app using the code mentionned above : 
[HapticFeedbackExample.zip](https://github.com/unoplatform/uno/files/6735906/HapticFeedbackExample.zip)

## Workaround

With the Xamarin.Essentials 6.1 version, a HapticFeedback object can be called to send some haptic feeedBack to the device, but this feature doesn't seem to work either. But using the Vibration class, again from Xamarin.Essentials, a vibration can be felt on the device. So using `Vibration.Vibrate(TimeSpan.FromSeconds(0.1));` creates the same thing as a haptic feedback would.

## Works on UWP/WinUI

No, but this issue is only used on mobile devices.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other:  The default packages installed with the visual studio extension template.

Nuget Package Version(s):
Uno.UI : v3.8.6
Uno.RemoteControl: v3.8.6
Uno.Core : v2.4.0

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

I cannot test this feature on iOS as I don't own a physical device, but this issue may be also on iOS.

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [x] Resharper (version: )

**Comment by davidjohnoliver** [comment]
Thanks for the report, can you tell us which device(s) and Android version(s) you tested with?

**Comment by PhilippeAudet-Stratejia** [comment]
On a samsung A71 with Android 11.

**Comment by MartinZikmund** [comment]
It seems the device does not have support for haptic feedback. The question is whether it is possible to detect this and fall back to "classic" vibration instead

**Comment by PhilippeAudet-Stratejia** [comment]
I also tried using the [xamarin essentials](https://docs.microsoft.com/en-us/xamarin/essentials/haptic-feedback?tabs=android) API for the haptic feedback : 
```chsarp
try
{
    // Perform click feedback
    HapticFeedback.Perform(HapticFeedbackType.Click);
}
catch (FeatureNotSupportedException ex)
{
    // Feature not supported on device
}
catch (Exception ex)
{
    // Other error has occurred.
}
```

But the FeatureNotSupportedException is not thrown when testing it on my device as I would have suspected. 

--- 

Using the `Windows.Devices.Haptics` API, I do get a valid feedback type from the `SimpleHapticsController` 
```csharp
var feedbackType = simpleHapticsController.SupportedFeedback.FirstOrDefault(
                        feedback => feedback.Waveform == KnownSimpleHapticsControllerWaveforms.Click);
```

From what you know, is there an other way of knowing if the device supports haptic feedback ?

**Comment by MartinZikmund** [comment]
@PhilippeAudet-Stratejia I have checked Android docs on this and unfortunately it doesn't seem there is a way to check whether haptic feedback capability is available on the device. The API does return a `bool` which probably indicates whether or not the feedback was performed, Unfortunately the Windows API does not return a `bool`, so we cannot return this value. However, you could use platform-specific code snippet:

```
#if __ANDROID__
var activity = (Activity)ContextHelper.Current;
var androidFeedback = FeedbackToAndroidFeedback(feedback);
var performed = activity.Window?.DecorView.PerformHapticFeedback(androidFeedback);
if (!performed)
{
   // Use VibrationDevice API instead
}
#endif
```

**Comment by MartinZikmund** [comment]
@PhilippeAudet-Stratejia Added the fallback in the haptics code directly, so now vibration will be used when haptics are not available 👍
