### ISSUE TITLE
DataGrid binding in macOS not working for asynchronously fetched data 

### ISSUE THREAD

**Issue by AmitEMV** [unoplatform/uno#6375]
## Current behavior

DataGrid's ItemSource is bound to a List from the ViewModel. This List is populated during load asynchronously and in this scenario, it hangs\crashes on macOS. 
The DataGrid is in a DataTemplate which is used in a ContentPresenter finally.

## Expected behavior

List will bind successfully and the app will display the bound data.

## How to reproduce it (as minimally and precisely as possible)

Simple [repo](https://github.com/AmitEMV/Binding) to reproduce the issue. Running the app reproduces the issue as there is nothing else in the code - delay is simulated for the asynchronous action and data is bound after that.

## Works on UWP/WinUI

It works in UWP, Android and Linux (SKia.Gtk) as well. Here is another [repo](https://github.com/AmitEMV/BindingUWP)  targeting these platforms for the same behaviour. 

## Environment

Nuget Package Version(s):  
Uno.UI v3.8.6. 
Prerelease for Uno.Microsoft.Xaml.Behaviors.Uwp.Managed v2.0.3-uno.95

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [x] Visual Studio for Mac (version: Enterprise)
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by AmitEMV** [comment]
I removed other project heads before checking it into Git, so they're absent in the macOS repo.

**Comment by AmitEMV** [comment]
@jeromelaban Is there any workaround that you would recommend that I can use for now?

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
