### ISSUE TITLE
Not Implemented Features

### ISSUE THREAD

**Issue by jcrlopes** [unoplatform/uno#6383]
## What would you like to be added:
Please Implement this features below for WASM projects.

Windows.UI.Xaml.UIElement.IsTapEnabled
Windows.Globalization.ApplicationLanguages
Windows.UI.Notifications.ToastNotificationManager.CreateToastNotifier()
 Windows.Storage.KnownFolders
Windows.UI.Core.CoreWindow.PointerPressed
Windows.System.Display.DisplayRequest
Windows.ApplicationModel.PackageId.Version
Windows.UI.Xaml.Controls.ListViewBase.ScrollIntoView(object)
Windows.UI.Xaml.Printing.PrintDocument.AddPage(Windows.UI.Xaml.UIElement)
 Windows.Devices.PointOfService.PosPrinter.Capabilities
Windows.UI.Xaml.Controls.TimePicker.Time
Windows.UI.Xaml.Media.Imaging.RenderTargetBitmap.PixelHeight
Windows.Graphics.Imaging.BitmapEncoder.PngEncoderId
 Windows.Security.Credentials.KeyCredential.RetrievePublicKey()

## Why is this needed:
Compiling a UWP project to WASM gives not implemented Errors for all this features above.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report! 

Can you open individual issues (as [enhancement requests](https://github.com/unoplatform/uno/issues/new?assignees=&labels=kind%2Fenhancement%2C+triage%2Funtriaged%2C+difficulty%2Ftbd&template=enhancement.md)) for all the properties and classes you've mentioned? Some are already partially implemented (or completely) and we'll need to discuss specifically the requirements.

Please make sure to add the Uno version you tested with.

**Comment by jeromelaban** [comment]
Also make sure to validate against the latest dev bits "3.9-dev.XX", in case the feature has been implemented since.
