### ISSUE TITLE
Unable to install Uno VISX on VS 2019 Enterprise

### ISSUE THREAD

**Issue by ElanHasson** [unoplatform/uno#6386]
## Current behavior

Unable to install Uno Templates VISX on Visual Studio 2019 Enterprise.

## Expected behavior

The templates should install.

## Environment

Windows 10, 21H2

Nuget Package: N/A
Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ X] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

![image](https://user-images.githubusercontent.com/234704/124424003-3dcfd280-dd34-11eb-8261-35d754882840.png)

Log:

```
7/5/2021 1:54:16 AM - Microsoft VSIX Installer
7/5/2021 1:54:16 AM - -------------------------------------------
7/5/2021 1:54:16 AM - vsixinstaller.exe version:
7/5/2021 1:54:16 AM - 17.0.1616-preview1
7/5/2021 1:54:16 AM - -------------------------------------------
7/5/2021 1:54:16 AM - Command line parameters:
7/5/2021 1:54:16 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\devenv.exe,/skuName:Enterprise,/skuVersion:16.11.31410.223,/appidname:Microsoft Visual Studio Enterprise 2019,/culture:en-US,/noep,C:\Users\elan\AppData\Local\Temp\VSIXnvsbt1wh.vsix
7/5/2021 1:54:16 AM - -------------------------------------------
7/5/2021 1:54:16 AM - Microsoft VSIX Installer
7/5/2021 1:54:16 AM - -------------------------------------------
7/5/2021 1:54:16 AM - Initializing Install...
7/5/2021 1:54:17 AM - Extension Details...
7/5/2021 1:54:17 AM - 	Identifier         : UnoSolutionTemplate.b8e0806a-a194-4442-8634-474e089e479e
7/5/2021 1:54:17 AM - 	Name               : Uno Platform Solution Templates
7/5/2021 1:54:17 AM - 	Author             : nventive
7/5/2021 1:54:17 AM - 	Version            : 3.8.6.6
7/5/2021 1:54:17 AM - 	Description        : Solution templates for Uno Platform enabled projects
7/5/2021 1:54:17 AM - 	Locale             : en-US
7/5/2021 1:54:17 AM - 	MoreInfoURL        : https://github.com/unoplatform/uno
7/5/2021 1:54:17 AM - 	InstalledByMSI     : False
7/5/2021 1:54:17 AM - 	SupportedFrameworkVersionRange : [4.5,)
7/5/2021 1:54:17 AM - 
7/5/2021 1:54:17 AM - 	SignatureState     : ValidSignature
7/5/2021 1:54:17 AM - 	SignedBy           : nventive inc.
7/5/2021 1:54:17 AM - 	Certificate Info   : 
7/5/2021 1:54:17 AM - 		-------------------------------------------------------
7/5/2021 1:54:17 AM - 		[Subject]       : CN=nventive inc., O=nventive inc., L=Montreal, S=Quebec, C=CA
7/5/2021 1:54:17 AM - 		[Issuer]        : CN=Go Daddy Secure Certificate Authority - G2, OU=http://certs.godaddy.com/repository/, O="GoDaddy.com, Inc.", L=Scottsdale, S=Arizona, C=US
7/5/2021 1:54:17 AM - 		[Serial Number] : 00AEC3A1CFB74D0A61
7/5/2021 1:54:17 AM - 		[Not Before]    : 10/4/2020 11:11:30 AM
7/5/2021 1:54:17 AM - 		[Not After]     : 12/3/2021 2:52:43 PM
7/5/2021 1:54:17 AM - 		[Thumbprint]    : 65B604DD8D2B7226B58EA15CF07171125E7C8D35
7/5/2021 1:54:17 AM - 
7/5/2021 1:54:17 AM - 	Supported Products : 
7/5/2021 1:54:17 AM - 		Microsoft.VisualStudio.Community
7/5/2021 1:54:17 AM - 			Version : [15.0,17.0]
7/5/2021 1:54:17 AM - 			ProductArchitecture : notSpecified
7/5/2021 1:54:17 AM - 
7/5/2021 1:54:17 AM - 	References         : 
7/5/2021 1:54:17 AM - 	Prerequisites      : 
7/5/2021 1:54:17 AM - 		-------------------------------------------------------
7/5/2021 1:54:17 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
7/5/2021 1:54:17 AM - 		Name         : Visual Studio core editor
7/5/2021 1:54:17 AM - 		Version      : [16.1.28811.260,17.0)
7/5/2021 1:54:17 AM - 
7/5/2021 1:54:17 AM - 		-------------------------------------------------------
7/5/2021 1:54:17 AM - 		Identifier   : Microsoft.VisualStudio.Workload.NetCrossPlat
7/5/2021 1:54:17 AM - 		Name         : Mobile development with .NET
7/5/2021 1:54:17 AM - 		Version      : [16.3.29230.54,17.0)
7/5/2021 1:54:17 AM - 
7/5/2021 1:54:17 AM - 		-------------------------------------------------------
7/5/2021 1:54:17 AM - 		Identifier   : Microsoft.VisualStudio.Workload.Universal
7/5/2021 1:54:17 AM - 		Name         : Universal Windows Platform development
7/5/2021 1:54:17 AM - 		Version      : [16.3.29102.218,17.0)
7/5/2021 1:54:17 AM - 
7/5/2021 1:54:17 AM - 		-------------------------------------------------------
7/5/2021 1:54:17 AM - 		Identifier   : Microsoft.VisualStudio.Workload.NetWeb
7/5/2021 1:54:17 AM - 		Name         : ASP.NET and web development
7/5/2021 1:54:17 AM - 		Version      : [16.3.29311.71,17.0)
7/5/2021 1:54:17 AM - 
7/5/2021 1:54:17 AM - Signature Details...
7/5/2021 1:54:17 AM - 	Extension is signed with a valid signature.
7/5/2021 1:54:17 AM - 
7/5/2021 1:54:17 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.ComputeInstallableExtensions(IStateData stateData, Boolean isRepairSupported, Boolean isExtensionPack, IDictionary`2 skuDataMapping, IList`1 installableExtensionsPaths)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Why does the supported product only show community?

**Comment by jeromelaban** [comment]
Thanks for the report.

Can you try updating your visual studio installation with the prerequisites mentioned here: 
https://platform.uno/docs/articles/get-started-vs.html

**Comment by rboehm-easysolution** [comment]
I am having the same issue after installing the workflows and using uno-check. Both with the Extension Manager and the VS Marketplace.

**Comment by jeromelaban** [comment]
Thanks. I just noticed that you've installed VS 2022 (17.0.1616-preview1 at the top) and the installer seems to be having a problem installing the extension on VS2019 instances. I do not have directions to fix this for now and this seems to be a known issue on Microsoft's side, we'll update as we know more.

You can still install the [`dotnet new` templates](https://platform.uno/docs/articles/get-started-dotnet-new.html) to get started.

**Comment by ElanHasson** [comment]
Uno check runs fine for me as well and I have all the updated components.

Everything works fine from a dotnet new perspective.

Is it even necessary to use the VISX since VS now shows dotnet templates?

What does it provide over those templates?

**Comment by rboehm-es** [comment]
I can confirm that using the VSIX Installer of 2019 does indeed install the extension.

**Comment by jeromelaban** [comment]
@ElanHasson The VSIX provides an enhanced experience with regards to the templates generation (the dotnet new template engine is missing quite a few features), and provides XAML hot reload support. Aside from this, the VSIX is not mandatory when building uno applications.

**Comment by ElanHasson** [comment]
Thanks @jeromelaban I want hot reload ☺️

**Comment by ElanHasson** [comment]
Wow that was fast @workgroupengineering! I just uninstalled VS2022 and VS2019 preview, time to reinstall :D

**Comment by jeromelaban** [comment]
@ElanHasson  It's not going to fix the issue, this is a visual studio issue, not an uno issue. If you've uninstalled VS2022, it could be that the vsix installer is still running. You'll see this at the top of the installer log.

**Comment by toddcarnes** [comment]
It doesn't install on VS 2019 Community either.
[dd_VSIXInstaller_20210706191645_2f64.log](https://github.com/unoplatform/uno/files/6773847/dd_VSIXInstaller_20210706191645_2f64.log)

**Comment by rboehm-es** [comment]
> It doesn't install on VS 2019 Community either.
> [dd_VSIXInstaller_20210706191645_2f64.log](https://github.com/unoplatform/uno/files/6773847/dd_VSIXInstaller_20210706191645_2f64.log)

After you installed the 2022 preview the VSIX installer is replaced. You either have to point to the VSIX installer of 2019 or replace it with an older version.

**Comment by toddcarnes** [comment]
Replacing the installer worked. Thanks.

**Comment by ElanHasson** [comment]
@toddcarnes  How did you replace it?

**Comment by toddcarnes** [comment]
1. Go to https://visualstudio.microsoft.com/.
2. Download the regular installer and save it to your computer.
3. Go to Settings > Apps.
4. Uninstall "Microsoft Visual Studio Installer".
5. All versions of Visual Studio will be removed from your computer.
6. Once all the Visual Studios are removed, the installer will uninstall itself too.
7. Double-click the installer you downloaded in step 1 and re-install Visual Studio.
8. Go to https://platform.uno/docs/articles/get-started-vs.html and follow the directions to install Uno.

**Comment by jeromelaban** [comment]
Uno 3.8.13 is published to the Visual Studio Marketplace and fixes this issue.
