### ISSUE TITLE
[Gallery][Skia.GTK]CalendarView and CalendarDatePicker- The monthDate option to go to annual and decade view calendar and Previous, Next arrow button on the header is not working .

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6392]
## Current behavior
https://user-images.githubusercontent.com/74563602/124506183-1d862f00-dd99-11eb-8335-b0e3a7accf2a.mp4

## Expected behavior
The monthDate, previous and next arrow on the header should work properly.

## How to reproduce it (as minimally and precisely as possible)
Launch the Uno.Gallry app on Skia.GTK
Click on “CalendarView” or "CalendarDatePicker" item from the list.
Observe that the  monthDate, previous and next arrow on the header is not working to go to annual and decade view calendar.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [X] Skia
  - [ ] WPF
  - [X] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by bstrother1** [comment]
This seems to be the same behavior happening is Skia.WPF as well. Up/Down buttons do not work in CalendarDatePicker.

**Comment by sakshi173** [comment]
@carldebilly, I retested this bug and not able to reproduce it due to that closing it.
