### ISSUE TITLE
Basic background does not take into account the active theme

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#6393]
## Current behavior
![2](https://user-images.githubusercontent.com/3002068/123758873-b2ed7300-d902-11eb-86be-654915cf8581.gif)
Differences(In WebAssembly relative to UWP):
The background is different unless explicitly set `Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"`. When testing, the system has a Dark theme installed.

## Expected behavior
![1](https://user-images.githubusercontent.com/3002068/123758878-b4b73680-d902-11eb-8e03-3c39596b17a9.gif)

## How to reproduce it (as minimally and precisely as possible)

https://github.com/HavenDV/Uno.WASM.TemplateBug
https://github.com/HavenDV/Uno.WASM.TemplateBug/commit/b6a4c8ed81b38ced515ba79add7849c00d6191d4

## Works on UWP/WinUI
Yes

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia>

Nuget Package Version(s):
- 3.8.6 and 3.9.0-dev.104

Affected platform(s):
Possible multiple, tested only on WebAssembly

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: latest)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Repro archive: [Uno.WASM.TemplateBug-master.zip](https://github.com/unoplatform/uno/files/6766201/Uno.WASM.TemplateBug-master.zip)

**Comment by jeromelaban** [comment]
## Note for contributors

To fix this, we'll need to add an overlay in the DOM that matches the current user theme and XAML App requested theme, likely by using some CSS. It's generally not visible as developers set an explicit color to the background of their window content, similar to what the default UWP Page template does:

```xaml
<Page
    x:Class="winboostraptest01.BlankPage1"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:winboostraptest01"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>

    </Grid>
</Page>
```

**Comment by MartinZikmund** [comment]
Also present on other platforms (#2522)

**Comment by MartinZikmund** [comment]
This does happen on other platforms as well (Android and iOS based on other linked issue)
