### ISSUE TITLE
[WASM] Thumb is not visible

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#6394]
## Current behavior
![2](https://user-images.githubusercontent.com/3002068/123758873-b2ed7300-d902-11eb-86be-654915cf8581.gif)
Differences(In WebAssembly relative to UWP):
Thumb is not visible

## Expected behavior
![1](https://user-images.githubusercontent.com/3002068/123758878-b4b73680-d902-11eb-8e03-3c39596b17a9.gif)

## How to reproduce it (as minimally and precisely as possible)

https://github.com/HavenDV/Uno.WASM.TemplateBug
https://github.com/HavenDV/Uno.WASM.TemplateBug/commit/b6a4c8ed81b38ced515ba79add7849c00d6191d4

## Works on UWP/WinUI
Yes

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia>

Nuget Package Version(s):
- 3.8.6 and 3.9.0-dev.104

Affected platform(s):
Possible multiple, tested only on WebAssembly

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: latest)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. 

The issue could to be that the thumb is not displayed at all, rather than being in the incorrect order. Have you tried with a border instead?

**Comment by HavenDV** [comment]
Apparently, Thumb is not visible in principle in any way. Even at https://playground.platform.uno/

**Comment by jeromelaban** [comment]
Indeed, thumb seems to have no default style (https://playground.platform.uno/#5fd1491e when using an existing style).

The fix would be to include the default thumb style from UWP.
