### ISSUE TITLE
[Gallery][Skia.GTK] PasswordBox text is not hiding the text

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6396]
## Current behavior
![paswordbox skia issue](https://user-images.githubusercontent.com/74563602/124512146-b7ec6f80-dda5-11eb-9f64-6c9c13fbc9e3.png)

## Expected behavior
![paswordbox skia correct](https://user-images.githubusercontent.com/74563602/124512169-c20e6e00-dda5-11eb-9681-f6f06797156d.png)

## How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app on Skia.GTK
2. Click on “PasswordBox” item from the list.
3. Observe that the passwordbox text is not encrypting and displaying the text.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [X] Skia
  - [ ] WPF
  - [X] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by MartinZikmund** [comment]
`PasswordBox` is not yet supported on Skia targets - https://github.com/unoplatform/uno/issues/5767

**Comment by sakshi173** [comment]
The issue is fixed, closing.
