### ISSUE TITLE
[Gallery][Wasm/Skia.Gtk] Focus - When clicking Tab and Enter key multiple time and then hit arrow keys on keyboard, the application crashes sometime.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6405]
## Current behavior
![Focus textbox issue](https://user-images.githubusercontent.com/74563602/124653538-6ad2d100-de6b-11eb-92ea-b9801a9a566d.png)
![Focus textbox issue 2](https://user-images.githubusercontent.com/74563602/124653550-6f978500-de6b-11eb-9aa8-fa590eb7d293.png)

## Expected behavior
App should not break.

## How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Go to Material or Fluent or Cupertino
4. Go to "TextBox" or  "CalendarView" section.
5. Click Tab and enter key multiple time and then arrows key on keyboard.
6. Observe that sometime the application crashes. 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Canary version:
1.5.0-canaries-dev.764

**Comment by MartinZikmund** [comment]
@sakshi173 Are you still encountering this problem? I have tested I wasn't able to reproduce it
