### ISSUE TITLE
Support Keyboard navigation for `ListView` and `ListViewItem`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#6411]
## What would you like to be added:

Currently it is not possible to navigate between `ListView` items properly using Tab/Shift+Tab nor arrow keys. It is also not possible to invoke (click) a `ListViewItem` (or similar) with `Enter`.

## Why is this needed:

Parity with UWP.

## For which Platform:

All

**Comment by jeromelaban** [comment]
@MartinZikmund, I agree, Tab will move between top level controls, not individual items (as seen in the store app, for instance). I agree for enter that needs to be supported.

**Comment by ramezgerges** [comment]
I just tested this now and it seems that this already works? The sample `ListView_ItemClick` demonstrates this.

**Comment by jeromelaban** [comment]
Let's close then! Thanks @ramezgerges!
