### ISSUE TITLE
Failed to install Uno Platform Solution Templates on Visual Studio 2019 Preview

### ISSUE THREAD

**Issue by MichaelVach** [unoplatform/uno#6416]
## Current behavior
Extension fails to install

## Expected behavior
Extension should install

## How to reproduce it (as minimally and precisely as possible)

Install Visual Studio 2019 Preview
Install Visual Studio 2022 Preview

Open Visual Studio 2019 and try to install the extension

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [X] Resharper (version:  2021.1.3)

Install Log:

7/7/2021 8:40:51 PM - Microsoft VSIX Installer
7/7/2021 8:40:51 PM - -------------------------------------------
7/7/2021 8:40:51 PM - vsixinstaller.exe version:
7/7/2021 8:40:51 PM - 17.0.1616-preview1
7/7/2021 8:40:51 PM - -------------------------------------------
7/7/2021 8:40:51 PM - Command line parameters:
7/7/2021 8:40:51 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,D:\install\Visual Studio\UnoPlatform-3.8.6.vsix
7/7/2021 8:40:51 PM - -------------------------------------------
7/7/2021 8:40:51 PM - Microsoft VSIX Installer
7/7/2021 8:40:51 PM - -------------------------------------------
7/7/2021 8:40:51 PM - Skipping product Microsoft.VisualStudio.Product.BuildTools (8e117eec) since it does not support extensions
7/7/2021 8:40:51 PM - Initializing Install...
7/7/2021 8:40:51 PM - Extension Details...
7/7/2021 8:40:51 PM - 	Identifier         : UnoSolutionTemplate.b8e0806a-a194-4442-8634-474e089e479e
7/7/2021 8:40:51 PM - 	Name               : Uno Platform Solution Templates
7/7/2021 8:40:51 PM - 	Author             : nventive
7/7/2021 8:40:51 PM - 	Version            : 3.8.6.6
7/7/2021 8:40:51 PM - 	Description        : Solution templates for Uno Platform enabled projects
7/7/2021 8:40:51 PM - 	Locale             : en-US
7/7/2021 8:40:51 PM - 	MoreInfoURL        : https://github.com/unoplatform/uno
7/7/2021 8:40:51 PM - 	InstalledByMSI     : False
7/7/2021 8:40:51 PM - 	SupportedFrameworkVersionRange : [4.5,)
7/7/2021 8:40:51 PM - 
7/7/2021 8:40:51 PM - 	SignatureState     : ValidSignature
7/7/2021 8:40:51 PM - 	SignedBy           : nventive inc.
7/7/2021 8:40:51 PM - 	Certificate Info   : 
7/7/2021 8:40:51 PM - 		-------------------------------------------------------
7/7/2021 8:40:51 PM - 		[Subject]       : CN=nventive inc., O=nventive inc., L=Montreal, S=Quebec, C=CA
7/7/2021 8:40:51 PM - 		[Issuer]        : CN=Go Daddy Secure Certificate Authority - G2, OU=http://certs.godaddy.com/repository/, O="GoDaddy.com, Inc.", L=Scottsdale, S=Arizona, C=US
7/7/2021 8:40:51 PM - 		[Serial Number] : 00AEC3A1CFB74D0A61
7/7/2021 8:40:51 PM - 		[Not Before]    : 10/4/2020 5:11:30 PM
7/7/2021 8:40:51 PM - 		[Not After]     : 12/3/2021 8:52:43 PM
7/7/2021 8:40:51 PM - 		[Thumbprint]    : 65B604DD8D2B7226B58EA15CF07171125E7C8D35
7/7/2021 8:40:51 PM - 
7/7/2021 8:40:51 PM - 	Supported Products : 
7/7/2021 8:40:51 PM - 		Microsoft.VisualStudio.Community
7/7/2021 8:40:51 PM - 			Version : [15.0,17.0]
7/7/2021 8:40:51 PM - 			ProductArchitecture : notSpecified
7/7/2021 8:40:51 PM - 
7/7/2021 8:40:51 PM - 	References         : 
7/7/2021 8:40:51 PM - 	Prerequisites      : 
7/7/2021 8:40:51 PM - 		-------------------------------------------------------
7/7/2021 8:40:51 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
7/7/2021 8:40:51 PM - 		Name         : Visual Studio core editor
7/7/2021 8:40:51 PM - 		Version      : [16.1.28811.260,17.0)
7/7/2021 8:40:51 PM - 
7/7/2021 8:40:51 PM - 		-------------------------------------------------------
7/7/2021 8:40:51 PM - 		Identifier   : Microsoft.VisualStudio.Workload.NetCrossPlat
7/7/2021 8:40:51 PM - 		Name         : Mobile development with .NET
7/7/2021 8:40:51 PM - 		Version      : [16.3.29230.54,17.0)
7/7/2021 8:40:51 PM - 
7/7/2021 8:40:51 PM - 		-------------------------------------------------------
7/7/2021 8:40:51 PM - 		Identifier   : Microsoft.VisualStudio.Workload.Universal
7/7/2021 8:40:51 PM - 		Name         : Universal Windows Platform development
7/7/2021 8:40:51 PM - 		Version      : [16.3.29102.218,17.0)
7/7/2021 8:40:51 PM - 
7/7/2021 8:40:51 PM - 		-------------------------------------------------------
7/7/2021 8:40:51 PM - 		Identifier   : Microsoft.VisualStudio.Workload.NetWeb
7/7/2021 8:40:51 PM - 		Name         : ASP.NET and web development
7/7/2021 8:40:51 PM - 		Version      : [16.3.29311.71,17.0)
7/7/2021 8:40:51 PM - 
7/7/2021 8:40:51 PM - Signature Details...
7/7/2021 8:40:51 PM - 	Extension is signed with a valid signature.
7/7/2021 8:40:51 PM - 
7/7/2021 8:40:51 PM - Searching for applicable products...
7/7/2021 8:40:51 PM - Found installed product - Global Location
7/7/2021 8:40:51 PM - Found installed product - Visual Studio Enterprise 2022 Preview
7/7/2021 8:40:51 PM - Found installed product - Visual Studio Enterprise 2019 Preview
7/7/2021 8:40:51 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by jeromelaban** [comment]
Thanks for the report. This issue is being tracked here https://github.com/unoplatform/uno/issues/6386 and is caused by the  installation of VS 2022 on your machine.
