### ISSUE TITLE
[MacOS] ContentControl with ContentControl intercepts pointer events

### ISSUE THREAD

**Issue by blindseykahua** [unoplatform/uno#6418]
## Current behavior

When a ContentControl with a ContentTemplate is in a view the user is unable to interact with any of the controls.

## Expected behavior

The UI should work normally.

## How to reproduce it (as minimally and precisely as possible)
(Attached is the following project already set up)
[TestUnoMacApp.macOS.zip](https://github.com/unoplatform/uno/files/6779645/TestUnoMacApp.macOS.zip)

- Create a blank Uno project
- In MainPage.xaml put this:

```
    <Grid>
        <Button Grid.Row="1" Content="Click Me"/>
        <ContentControl
            Grid.Row="2"
            ContentTemplate="{StaticResource UserNameTemplate}" />
    </Grid>
```

- In a file called "UserNameTemplates.xaml" include the data template like:

```
    <DataTemplate x:Key="UserNameTemplate">
        <TextBlock Text="User Name Here"/>
    </DataTemplate>
```

- You will see that the template is visible on screen with the button, but the button does not respond to the mouse clicks.

## Workaround
none

## Works on UWP/WinUI
Yes

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.Ui (3.9.0-dev-108)
Uno.UI.RemoteControl (same)

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [X] Visual Studio for Mac (version: 8.10.4 (build 11))
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by blindseykahua** [comment]
Accidentally included the Mac proj above and not the whole solution.
[TestUnoMacApp.zip](https://github.com/unoplatform/uno/files/6779683/TestUnoMacApp.zip)

**Comment by jeromelaban** [comment]
After investigation, the ContentControl placed on top seems to be intercepting the touches, where is does not happen on the other platforms. 

The following example allows for the button to be pressed, not on macOS:
```xaml
<Grid>
    <Grid.Resources>
        <DataTemplate x:Key="UserNameTemplate">
            <TextBlock Text="User Name Here"/>
        </DataTemplate>
     </Grid.Resources>
    <Button  Content="Click on me now"/>
    <ContentControl
        ContentTemplate="{StaticResource UserNameTemplate}" />
</Grid>
```
