### ISSUE TITLE
[WASM] Cannot iterate through ApplicationData.Current.LocalSettings.Values

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#6419]
## Current behavior

Attempting to iterate through ApplicationData.Current.LocalSettings.Values fails in WASM

## Expected behavior

Iteration should work, as in UWP.

## How to reproduce it (as minimally and precisely as possible)

Start the attached project in UWP and observe that clicking either button fully retrieves stored settings.  Start in WASM and observe that retrieving settings only displays values when not attempting to iterate through ApplicationData.Current.LocalSettings.Values.

[LocalSettingsIteration.zip](https://github.com/unoplatform/uno/files/6779836/LocalSettingsIteration.zip)

## Workaround

You can iterate through ApplicationData.Current.LocalSettings.Values.Keys to retrieve key values to access settings if keys are not known at design time.

## Works on UWP/WinUI

Yes

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.9.0-dev.197
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
In progress

**Comment by peternary** [comment]
iteration appears to work now
