### ISSUE TITLE
WASM: Uno.Wasm.Bootstrap ver 3.0.0-dev.101 with WasmShellMonoTempFolder gives error  The --appdir= argument is required

### ISSUE THREAD

**Issue by iosub** [unoplatform/uno#6422]
## Current behavior

WASM: Uno.Wasm.Bootstrap ver 3.0.0-dev.101 with WasmShellMonoTempFolder gives error  The --appdir= argument is required

## Expected behavior

Last version that does not give the error is  Uno.Wasm.Bootstrap ver 3.0.0-dev.87

## How to reproduce it (as minimally and precisely as possible)
`add for example
<WasmShellMonoTempFolder>C:\MSP\2018\Uno\runtime\temp</WasmShellMonoTempFolder>
`

## Environment

Nuget Package Version(s):
Uno.Wasm.Bootstrap 3.0.0-dev.101
Affected platform(s):

- [ ] iOS
- [ ] Android
- [ X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. This is an interim upgrade issue that can be fixed by cleaning the `%temp%` folder. Look for a `dotnet-runtime-XXX` folder and delete it.

**Comment by iosub** [comment]
Bingo!!! Thank you
