### ISSUE TITLE
[WASM] Add <ProgressBar IsIndeterminate="True"/> support

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#6423]
## Current behavior
IsIndeterminate property is currently ignored

## Expected behavior
A special animation should be displayed, indicating an indefinite duration

## How to reproduce it (as minimally and precisely as possible)
http://playground.platform.uno/#8e3e8e6d

## Workaround
Apparently add Visual States from UWP

## Works on UWP/WinUI
Yes

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.8.6 and 3.9.0-dev.104

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: latest)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
The `ProgressBar` control has been implemented as part of the Microsoft.UI.Xaml.Control namespace, you can use this one instead.

See here: https://playground-wasm.azurewebsites.net/#d49f6688

**Comment by HavenDV** [comment]
Oh, exactly, I forgot about it. Thank you.
