### ISSUE TITLE
About Routed events bugs

### ISSUE THREAD

**Issue by Daoting** [unoplatform/uno#643]
## I'm submitting a...

- Bug report (I searched for similar issues and did not find one)

Android:
1. It cannot route to parent element after the child element attached PointerPressed/Tapped/DoubleTapped event, event if Handled=false.

2. If the parent element AddHandler the PointerPressedEvent, it's child cannot fire PointerPressed event.

3. If the child element attached Tapped event and set Handled=true, it's parent element cannot receive event even if using AddHandler. DoubleTapped is samed

iOS:
1. The trigger sequence is different from Android. It's missing an event.
    iOS: Pressed -> Released or Pressed -> Tapped
    Android: Pressed -> Released -> Tapped

 

## Environment

```
Nuget Package: 

Package Version(s): 

Affected platform(s):
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by dr1rrb** [comment]
This has been fixed by https://github.com/unoplatform/uno/pull/1256

I'm closing the issue, feel free to re-open it if there is any issue.
