### ISSUE TITLE
[Gallery][Wasm] Focus - WASM comparison with UWP - The radioButtons and checkbox options are getting clicked when pressing enter key on keyboard for WASM but not clicking for UWP.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6433]
## Current behavior
The Focus is working for Wasm but not working for UWP for radiobutton, togglebutton and checkbox option.

## Expected behavior
It should be similar for both (WASM and UWP).

## How to reproduce it (as minimally and precisely as possible)
Open Uno Gallery APP
Click Burger Menu on the left top right.
Go to RadioButton section using Tab key on keyboard
Hit enter key on keyboard for selecting the radiobutton
Observe that radioButton is not getting clicked.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [X] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by ajpinedam** [comment]
This is fixed. Tested in the latest version of Gallery and both Windows (UWP) and WASM head have the same behaviour when interacting with the CheckBoxes and RadioButtons

Closing issue.
