### ISSUE TITLE
[NPE] Focus- Focus is not happening when using arrow key to bring the focus on some other option.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6434]
## Current behavior

https://user-images.githubusercontent.com/74563602/124989698-69410e80-e00d-11eb-8c68-8e98fb3293bf.mp4

## Expected behavior
The Focus should work properly.

## How to reproduce it (as minimally and precisely as possible)
Go to the link https://purple-pond-0688d230f.azurestaticapps.net/packages
Press Tab or Tab + Shift key on keyboard.
When the focus is on the packages selection press down arrow key on keyboard.
Observe that the focus highlighted box is not displaying properly.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Canary Version:
20210708.1

**Comment by MartinZikmund** [comment]
This is fixed.
