### ISSUE TITLE
[WPF] ConnectionProfile.GetNetworkConnectivity is Not Implemented

### ISSUE THREAD

**Issue by ahoefling** [unoplatform/uno#6435]
## Current behavior
When using the WPF Skia target and trying to retrieve the Network Connectivity it always returns `NetworkConnectivityLevel.None` and this is true for all Skia platforms. 

## Expected behavior
Retrieve the correct network state

## How to reproduce it (as minimally and precisely as possible)

This can be reproduced in the **SamplesApp** that is included in the uno platform code
1. Open app
2. On the left pane search for Windows.Networking
3. Open the connectivity test page
4. Select `Check Connectivity`

## Workaround
You can add the following code to your WPF app to access the network state
```c#
#if HAS_UNO_SKIA_WPF
  [DllImport("wininet.dll")]
  extern static bool InternetGetConnectedState(out int connectionDescription, int reservedValue);
#endif

  bool IsConnected() => InternetGetConnectedState(out _, 0);
```

The method `IsConnected()` will return true if there is network connectivity and false if there is not. 

## Works on UWP/WinUI
yes

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.9.0-dev.215 (commit hash `1f3ce908226b509b738a219738094a4ba6baee7a`)

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [x] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.10.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
I have the code change for this and want to contribute it but it appears we need to add some preprocessor directives for the Skia WPF target head. For example if I try adding the following code to `ConnectionProfile.skia.cs` it will not run
```c#
#if HAS_UNO_SKIA_WPF
  // My implementation here
#endif
``` 

I did a little investigation and started trying to update the `PlatformItemGroups.props` to support a new file extension of `*.wpf.cs` but I wasn't 100% sure the right condition to enter. I am wondering if we might need to add a new csproj for `Uno.UI` of `Uno.Skia.Wpf.csproj` which will 

Ultimately I was blocked on trying to implement this just in WPF because I wasn't sure how best to update the class `ConnectionProfile.skia.cs` so it only runs on WPF. My code sample in the workaround is the recommended solution to this.

**Comment by MartinZikmund** [comment]
@ahoefling if you want to try to implement this, you can take inspiration from `FileOpenPicker` implementation for example. The trick is that `Uno.UI` contains only Skia platform-agnostic code, and then there is an extension interface which is then implemented by `Uno.UI.Runtime.Skia.XYZ`. So for example here:

- `FileOpenPicker` implementation for Skia which just forwards call to the interface implementation - https://github.com/unoplatform/uno/blob/master/src/Uno.UWP/Storage/Pickers/FileOpenPicker.skia.cs
- Skia general `IFileOpenPickerExtension` interface - https://github.com/unoplatform/uno/blob/master/src/Uno.UWP/Storage/Pickers/Internal/IFileOpenPickerExtension.skia.cs
- WPF specific `FileOpenPickerExtension` - https://github.com/unoplatform/uno/blob/master/src/Uno.UI.Runtime.Skia.Wpf/Extensions/Storage/Pickers/FileOpenPickerExtension.cs

**Comment by ahoefling** [comment]
@MartinZikmund thanks for the tips on how to get this implemented, I wasn't fully wrapping my head around the runtime layer extensions and giving me a concrete example really helped! 

I have this working locally and a pull request is incoming

**Comment by MartinZikmund** [comment]
Closing 😉
