### ISSUE TITLE
[WASM] ScrollViewer cutting off bottom of content

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#6443]
## Current behavior

The content is clipped at the bottom of the page in some cases.

## Expected behavior

All the content should be shown,

## How to reproduce it (as minimally and precisely as possible)

Visit https://app.iratio.ca/test/ and notice the TextBlock on the bottom of the page does not get shown if the viewport is not big enough to fit the whole page. Source code is available at https://github.com/mikernet/UnoTest.

## Works on UWP/WinUI

Yes

## Environment

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.9.0-dev.54, 3.9.0-dev.220

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by dr1rrb** [comment]
Most probably linked with https://github.com/unoplatform/uno/issues/7000 (provides a workaround)

**Comment by hawkerm** [comment]
Also reproduced in the Uno Playground as mentioned here: https://github.com/unoplatform/uno/issues/7000#issuecomment-1046604463

**Comment by agneszitte-nventive** [comment]
Closing this issue as with latest Uno dev versions the text is wrapping correctly now.
#8210 PR for #7000 will take care of correctly taking into account content margin values inside the ScrollViewer for Skia and WASM (Top|Left).

The only issue left is Bottom|Right margin for WASM that still needs to be fixed for WASM. (Details [here](https://github.com/unoplatform/uno/issues/7000#issuecomment-1055865822))
But a simple workaround is available, simply by surrounding the content with the margin with a Border like that:
```xaml
<ScrollViewer>
                        <Border>
                            <StackPanel MaxWidth="400"
                                        Margin="30">
                                  ...
                            </StackPanel>
                        </Border>
</ScrollViewer>
```
