### ISSUE TITLE
[WASM] FileOpenPicker does not work correctly on Safari

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#6444]
## Current behavior

On MacOS and iOS Safari, canceling the dialog after calling `FileOpenPicker.PickSingleFileAsync()` appears to never return. On iOS Safari it doesn't return even if a file is picked.

Works fine on Chome/Edge.

## Expected behavior

Return `null` if the dialog is canceled or the file if one is picked.

## How to reproduce

Method task does not complete in the aforementioned situations:

```cs
        public async Task<Stream> GetImageStreamAsync()
        {
            // Create and initialize the FileOpenPicker
            var openPicker = new FileOpenPicker {
                ViewMode = PickerViewMode.Thumbnail,
                SuggestedStartLocation = PickerLocationId.PicturesLibrary,
            };

            openPicker.FileTypeFilter.Add(".jpg");
            openPicker.FileTypeFilter.Add(".jpeg");
            openPicker.FileTypeFilter.Add(".png");

            // Get a file and return a Stream
            StorageFile storageFile = await openPicker.PickSingleFileAsync();

            if (storageFile == null)
                return null;

            IRandomAccessStreamWithContentType raStream = await storageFile.OpenReadAsync();
            return raStream.AsStreamForRead();
        }
```

## Works on UWP/WinUI

 Yes

## Environment

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.9.0-dev.220

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
This scenario is working on Safari iOS (using https://nuget.info). If you're still having an issue with this let us know with additional details.
