### ISSUE TITLE
`ContentTemplateSelector` is not automatically propagated from `ContentControl`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#6452]
## Current behavior

Not propagated.

## Expected behavior

Should be propagated.

## How to reproduce it (as minimally and precisely as possible)

See `Button_themeresources.xaml` in FluentTheme and search for "Uno workaround".

## Workaround

Explicitly specify `TemplateBinding`:

```
ContentTemplateSelector="{TemplateBinding ContentTemplateSelector}"
```

## Works on UWP/WinUI

Yes 

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.8

Affected platform(s):

All

**Comment by MartinZikmund** [comment]
When fixed, many Uno-specific workarounds in XAML styles can be removed

**Comment by davidjohnoliver** [comment]
Closely related to this issue: https://github.com/unoplatform/uno/issues/857

The solution is going to be to import the ContentControl and ContentPresenter code.

**Comment by VincentH-Net** [comment]
> Closely related to this issue: #857
> 
> The solution is going to be to import the ContentControl and ContentPresenter code.

The workaround in issue #857 currently only binds to `Content` - see the [`FeatureConfiguration.ContentPresenter.UseImplicitContentFromTemplate` implementation](https://github.com/unoplatform/uno/blob/f1e49b0e2043f59b0342f3dbd8c880f2a1abda28/src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs#L916)

While we are waiting for the solution suggested above, would it be an option to extend the workaround to include binding to `ContentTemplateSelector` ? It would only require a couple lines of code in above location.

If not, is there another workaround for both bindings that does not have to be repeated in many places?

**Comment by jeromelaban** [comment]
There's no additional workaround available at this point for this specific issue, other than extending the feature flag to additional properties.

**Comment by VincentH-Net** [comment]
@jeromelaban thanks for confirming; for now I have my own central workaround in C# Markup 2
I will watch these issues to see when I can remove my workaround.
