### ISSUE TITLE
[Android] Setting ImageBrush on a Shape in code does not work all the time

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#6460]
# Bug Report

## This code doesn't work on Android
``` xml
<Border>
  <Rectangle x:Name="myShape" />
</Border>
```
``` csharp
myShape.Fill = new ImageBrush
{
  ImageSource = new BitmapImage { UriSource = new Uri("https://nv-assets.azurewebsites.net/tests/images/uno-overalls.jpg") }
};
```
The image won't load/display on Android.

## But this code will work
``` csharp
var imageBrush = new ImageBrush();
myShape.Fill = imageBrush;
imageBrush.ImageSource = new BitmapImage { UriSource = new Uri("https://nv-assets.azurewebsites.net/tests/images/uno-overalls.jpg");
```
When the `ImageSource` is set after the fill is assigned to the shape, it works.

This problem is only present on shapes. No problems with other controls...

## Works on UWP/WinUI
Yep. That's only on Android.

Nuget Package Version(s): 3.8.x

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by Youssef1313** [comment]
Looks like `AssignAndObserveBrush` is missing `imageBrushCallback` in the `ImageBrush` if branch. I'll add it for now and write a test, but worth some refactoring in future :)

**Comment by davidjohnoliver** [comment]
> Looks like `AssignAndObserveBrush` is missing `imageBrushCallback` in the `ImageBrush` if branch. I'll add it for now and write a test, but worth some refactoring in future :)

Brush handling in general could use thorough refactoring - https://github.com/unoplatform/uno/issues/5192 - but it's a fairly major undertaking.
