### ISSUE TITLE
[Android] Splash screen stucks on Request Permissions 

### ISSUE THREAD

**Issue by e-leoni** [unoplatform/uno#6467]
I have developed an UWP application for windows iot core. Recently I'm trying to convert it into Android with UnoPlatform.
In uwp I used a splash screen while my application connect to serial port and read data from it.
I would like to do the same with Uno and I followed this [guide](https://platform.uno/docs/articles/splash-screen.html?tabs=tabid-vswin#step-3---android) and it works.
In order to open serial port with Android I had to request permissiosn, so in MainActivity I added this code:
        
```
            UsbManager manager = (UsbManager)GetSystemService(Context.UsbService);
            UsbReciever usbReciever = new UsbReciever();
            PendingIntent mPermissionIntent = PendingIntent.GetBroadcast(this, 0, new Intent(ACTION_USB_PERMISSION), 0);
            IntentFilter filter = new IntentFilter(ACTION_USB_PERMISSION);
            RegisterReceiver(usbReciever, filter);

            foreach (var dev in manager.DeviceList)
            {
                if (dev.Value.VendorId == 4292)
                    device = dev.Value;
            }

            if (device != null)
            {
                manager.RequestPermission(device, mPermissionIntent);
                bool hasPermision = manager.HasPermission(device);
                while (!hasPermision)
                {
                    Java.Lang.Thread.Sleep(3000);
                    hasPermision = manager.HasPermission(device);
                }
                UsbDeviceConnection connection = manager.OpenDevice(device);
                if (connection == null)
                    return;
            }
```

On first launch, app requests permission to the user, and if he accepted, opens the serial port and reads data, but Splashscreen doesn't hide even if in OnLaunched method of App.xaml.cs I use this code:

  
```
            if (e.PrelaunchActivated == false)
            {
                Android.Util.Log.Debug("OnLaunched", "Redirect to Homepage");
                if (rootFrame.Content == null)
                    // When the navigation stack isn't restored navigate to the first page,
                    // configuring the new page by passing required information as a navigation
                    // parameter
                    rootFrame.Navigate(typeof(HomePage), e.Arguments);

                // Ensure the current window is active
                window.Activate();
            }
```

In LogCat I can see that HomePage's OnNavigateTo is called, but SplashScreen doesn't hide.

What am I wrong?
Can someone helps me?

Best regards,
emanuele

**Comment by jeromelaban** [comment]
Thanks for the report!

Are you able to reproduce this behavior in a sample app? It'll be easier to help you troubleshoot this issue.

**Comment by e-leoni** [comment]
Hi @jeromelaban ,
yes i'll try, but i'll need some time
