### ISSUE TITLE
WASM native focus causes problems with `AllowFocusOnInteraction`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#6471]
## Current behavior

As an example when user taps on a button, we get a native event from the browser originating in the TextBlock inside the button template - and, the actual control that should get focused is the `Button` . However, if the Button has `AllowFocusOnInteraction = false` or `IsTabStop = false`, then nothing should get focused at all. Our current implementation bubbles up to find first focusable control, which does not work properly, as it may focus something way higher above the button (like the root of the Page for example). However, if we stop bubbling at first `IsTabStop = false` or `AllowFocusOnInteraction = false` it breaks controls like `TextBox` which contains a `ScrollViewer` inside, which is also has `IsTabStop = false`. 

## Expected behavior

Should behave like UWP/WinUI.

## How to reproduce it (as minimally and precisely as possible)

See above.

## Works on UWP/WinUI

Yes

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): latest dev

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
@jeromelaban @dr1rrb This could be fixed quite easily by ignoring the `focusin` handler for Uno-based controls. Technically this should not break anything, as all built-in controls should manage their own focus by explicitly calling `this.Focus(FocusState.XYZ)` in their pointer event handlers and managed focus navigation should take care of keyboard focus. `focusin` should be useful only for native non-Uno controls. Does any scenario I am missing here come to mind?

**Comment by dr1rrb** [comment]
If I understand you wan to ignore the native `focusin` event from the browser and rely only on managed code for focus handling for uno-only element? If so, my main concern would be for "unusual inputs devices", like a TV, a game-pad or more importantly any custom device designed to help disabled people to use the app.
