### ISSUE TITLE
[Playground][Wasm][Chrome] Focus - Getting error when the focus is on Data option and write some text for data window. 

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6475]
## Current behavior
![playground issue](https://user-images.githubusercontent.com/74563602/125676506-79238324-2478-4090-a44f-0312de6563c5.png)

## Expected behavior
Should not get error message.

## How to reproduce it (as minimally and precisely as possible)
1. Visit https://playgroundcanary.z19.web.core.windows.net/#passwordbox
2. Press tab key on the keyboard.
3. Bring the focus on the 'Data' option for Canvas.
4. Observe that the Window is enabled for 'Data' to type the code.
5. Type something in the window down to 'Data'
6. Notice that getting error message.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by MartinZikmund** [comment]
This is ok, the content of the data area must be a valid JSON, otherwise an error is shown.
