### ISSUE TITLE
[WASM] FileOpenPicker.FileTypeFilter contains redundant extensions

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#6487]
## Current behavior

WASM FileOpenPicker.FileTypeFilter contains redundant extensions.
![image](https://user-images.githubusercontent.com/3002068/126006566-af759c4c-c43d-4ff1-a08a-42d02eac1813.png)

## Expected behavior

UWP behavior:
![image](https://user-images.githubusercontent.com/3002068/126006648-a3e1c604-5d65-406e-9d7c-609d98d4b3e6.png)

## How to reproduce it (as minimally and precisely as possible)

```cs
var picker = new FileOpenPicker
{
    FileTypeFilter =
    {
        ".zip",
        ".qdpx",
    },
};
var file = await picker.PickSingleFileAsync();
```

## Works on UWP/WinUI
Yes

## Environment

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.9.0-dev.311

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: latest)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by trungnt2910** [comment]
This is the same issue as #5685, was already fixed in 3.7, but somehow it resurfaced in 3.8.

**Comment by trungnt2910** [comment]
The same thing happed with `FileSavePicker` and was fixed in 3.7. I think that [these lines](https://github.com/unoplatform/uno/blob/master/src/Uno.UWP/Storage/Pickers/FileOpenPicker.wasm.cs#L83-L106) may be responsible again.

**Comment by trungnt2910** [comment]
![image](https://user-images.githubusercontent.com/57174311/126027500-fa6aff6a-9b13-43bb-8db2-67a611387738.png)
It seems like on UWP, MIME types are ignored completely. Every `FileTypeFilter` entry stands on its own, and then the last option (All Files) is the superset of all types specified.

![image](https://user-images.githubusercontent.com/57174311/126027478-66bb7190-0a8d-428e-837d-7ce07a7372a4.png)
However, on the WASM implementation, the Uno Platform seems to attempt to group related file types together, which is not consistent with UWP, and also brings the same redundant file types as mentioned in #5689

**Comment by pkar70** [comment]
It is difference between using internally file extension (UWP) and using mime-types. When mimetypes are used, if someone adds ".jpg", it is converted to "image/jpeg", and all extensions of "image/jpeg" are shown. On UWP, I can make browser to show only ".jpg" files, and not files .jpeg, .jfif etc.  It is impossible when mime-types are used.

**Comment by trungnt2910** [comment]
> It is difference between using internally file extension (UWP) and using mime-types.   

Yes, exactly. This is the same thing as mentioned in the [issue](https://github.com/unoplatform/uno/pull/5689#issuecomment-814679571) with `FileSavePicker`, and I've made a pull request to fix this by removing all dependencies on MIME types.

However, I've only recently tested with the `FileOpenPicker` in another project, and found that the same problem still exists, and found this issue before trying to open a new one.

**Comment by pkar70** [comment]
Similar problem, but for Android, #5900, waits over two months :)

**Comment by trungnt2910** [comment]
That's actually common of them. It seems that the maintainers are very busy doing stuff with the Core of the Platform, and most pull requests that don't improve critical components are ignored. Then right before a release they try to sweep a bunch of these PRs and some of mine, after waiting for 2-3 months, got merged in the same day.
