### ISSUE TITLE
[Android] `TextBox` has visual issues

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#6490]
## Current behavior

The sides of `TextBoxes` on Android seem to be slightly above and below the horizontal lines.

![image](https://user-images.githubusercontent.com/1075116/126033922-49bf46c0-0f29-4663-9444-bc6fed1946e8.png)

For WinUI styles, there is also a weird visual artifact:

![image](https://user-images.githubusercontent.com/1075116/126033908-86291d9c-424e-481e-90f2-88e02a6db499.png)

## Expected behavior

Should be perfect rectangle / rounded corner.

## How to reproduce it (as minimally and precisely as possible)

Create a plain `TextBox`

## Workaround

-

## Works on UWP/WinUI

Yes

## Environment

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.8

Affected platform(s):

Only tested on Android, maybe present elsewhere too.

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This is a very odd issue that only seems to happen on very specific emulators, and somehow not on actual devices. Is that the case for you ?

**Comment by MartinZikmund** [comment]
@jeromelaban actually happening on my devices too (Samsung Note 20). It is hard to see due to high resolution, but still there:

 ![Screenshot_20210719-145949_SamplesApp.jpg](https://user-images.githubusercontent.com/1075116/126163494-6cad52cf-e362-440d-a1e7-f79ecf62afd6.jpg)

**Comment by Youssef1313** [comment]
@MartinZikmund I can't reproduce this on emulator using Samples App:

![image](https://user-images.githubusercontent.com/31348972/129625177-9dce0783-9bbc-48a2-a6f1-0a950025e6b2.png)

![image](https://user-images.githubusercontent.com/31348972/129625206-b39af98a-5dde-4c0f-ba4b-c6b34d267655.png)

(Emulator running Android 9 (API 28))

**Comment by MartinZikmund** [comment]
@Youssef1313 It happens only on high density devices (most visible on device itself)
