### ISSUE TITLE
Back button should be collapsed on `NavigationView` on Android by default

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#6495]
## Current behavior

As per Android guidelines, back button should not be displayed in apps by default. `NavigationView` with back button visibility set to `Auto` should therefore not show back button on Android.

## Expected behavior

Matching guidelines.

## How to reproduce it (as minimally and precisely as possible)

`NavigationView` with `BackButtonVisiblity` set to `Auto`

## Workaround

Collapse manually on Android

## Works on UWP/WinUI

N/A

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by robloo** [comment]
Are you sure? Uno Platform should prioritize first fidelity with WinUI. Even this back button should function exactly the same as in WinUI not tailored specifically to a platform.

This is a slippery slope in my opinion and the question of where to draw the line in the future is very difficult if concessions like this are made. Functionality exactly the same as WinUI should be paramount. (I do realize this may be considered a special case as NavigationView is so fundamental to UIs).

**Comment by MartinZikmund** [comment]
@robloo the back button can still be set to `Visible` by setting `NavigationView.BackButtonVisibility`. I think the new solution is better, as up until now there was actually no difference between Auto and Visible. In case of Android, the design guidelines explicitly state that back button should not be shown as part of the application UI as all devices have a hardware button, so that is the reason why it really should not be there. If Android certification was similarly strict as iOS, they would most likely reject the app just for this 😀 . Currently on Xbox, the back button is not shown, as it is always available in the form of B button, so this matches the "logic" behind the Auto behavior.

**Comment by jeromelaban** [comment]
This decision is similar to adding the `VisibleBoundsPadding` behavior the navigation view as well, because that makes it work properly by default on notch-based platforms, which windows does not consider.

**Comment by robloo** [comment]
Visible bounds definitely makes sense and is required as I understand it or there would be visual errors on notched devices.

I would consider this a bit of a different case. Neverless, you convinced me it is helpful and doesnt deviate from the intention of Auto either. I still think changes like this must be done sparingly but you guys are the experts on when or when not to do it anyway :)
