### ISSUE TITLE
how using dotnet new unoapp-net6 -n UnoAppAll

### ISSUE THREAD

**Issue by AbdalaMask** [unoplatform/uno#6500]
## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

how using dotnet new unoapp-net6 -n UnoAppAll

**Comment by AbdalaMask** [comment]
not work 
![image](https://user-images.githubusercontent.com/37013638/126084990-cd1c19c2-320d-4ea3-a59a-e73f45ff9e25.png)

**Comment by AbdalaMask** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-android	EVStudio.HMIControls	C:\Users\User\source\repos\EVStudio\Controls\EVStudio.HMIControls\EVStudio.HMIControls.csproj	1

**Comment by jeromelaban** [comment]
Thanks for the report.

This feature is not yet documented and not yet finished implementing, you'll need to wait a bit for it to be useable.
