### ISSUE TITLE
[WASM] FileSavePicker.SuggestedFileName is ignored

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#6513]
## Current behavior

WASM FileSavePicker.SuggestedFileName is ignored
![image](https://user-images.githubusercontent.com/3002068/126354802-38b013fe-c334-453c-b941-e67e86ecb18e.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/3002068/126354036-5b164e76-1ee8-4bda-86c9-af0d6f96c1db.png)

## How to reproduce it (as minimally and precisely as possible)

```cs
var picker = new FileSavePicker
{
    SuggestedFileName = "test",
    FileTypeChoices =
    {
        { ".xlsx", new List<string> { ".xlsx" } },
    },
};
var file = await picker.PickSaveFileAsync();
```

## Works on UWP/WinUI
Yes

## Environment

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.9.0-dev.311

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: latest)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
I don't think there's an API for that in Javascript. @MartinZikmund do you know if that exists ?

**Comment by MartinZikmund** [comment]
It should be doable for the download picker, but the native doesn't support it yet.

**Comment by MartinZikmund** [comment]
Update - this feature is now actually available in the native picker as well - https://wicg.github.io/file-system-access/#api-showsavefilepicker , I'm on it 👍
