### ISSUE TITLE
[Epic] Multi-screen Support

### ISSUE THREAD

**Issue by tardisconsole** [unoplatform/uno#6515]
## What would you like to be added:
The ability to be able to open multiple windows from a single app.
Implementing the following classes: CoreApplication.CreateNewView, AppWindow and ProjectionManager

## Why is this needed:
Currently there is no way to add more than one window in a Uno app.  This can be particularly useful on multi-screen Windows devices, but also there are more and more Android devices being released with two screens.

## For which Platform:
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [x] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by carldebilly** [comment]
Multi-window and multi-screen are two different features.  On UWP, you have limited access to physical screens and placements of apps on them.

**Comment by agneszitte** [comment]
> Multi-window and multi-screen are two different features. On UWP, you have limited access to physical screens and placements of apps on them.

@MartinZikmund, @jeromelaban 
As @carldebilly mentioned, multi-screen is a different feature than multi-window (https://github.com/unoplatform/uno/issues/8341).
Will this Epic issue stay on pause for now?

**Comment by MartinZikmund** [comment]
Closing in favor of https://github.com/unoplatform/uno/issues/8341
