### ISSUE TITLE
[Android] Add support for Android 12 (`monoandroid12.0` and `net6.0-android31.0`)

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#6520]
From the ,NET Android Team:

_There will be a legacy Xamarin.Android 12.0 release, and a legacy 12.1 release.  which will likely be the **last** legacy release._

The subsequent SDKs will be part of .NET 6 and 7.

From the [android documentation](https://developer.android.com/distribute/best-practices/develop/target-sdk) provided here:

> Starting in November 2021, app updates will be required to target API level 30 or above and adjust for behavioral changes in Android 11. Existing apps that are not receiving updates are unaffected and can continue to be downloaded from the Play Store. Wear OS apps must continue to target API level 28 or higher.

We can safely assume that the playstore will require to have API Level 31 in November 2022, and require API Level 32 in November 2023, hereby making Xamarin apps unable to be updated unless migrated to .NET 7 or 8.

Related issues:
- [ ] Xamarin.AndroidX.Browser breaking change https://github.com/unoplatform/uno/issues/5344

**Comment by pkar70** [comment]
And what after Android 12?

**Comment by MatFillion** [comment]
After Android 12, updates will be part of .net6 (and not xamarin anymore)

**Comment by jeromelaban** [comment]
I've added a possible timeline to the issue.

**Comment by pkar70** [comment]
So, Microsoft would make .Net API-compatible with Android, skipping all their good points from UWP?

**Comment by jeromelaban** [comment]
@pkar70 I don't understand your comment, but it does not change much API wise. It's just a newer runtime.

**Comment by pkar70** [comment]
Now I have (in Uno, #2536), `_locationManager = (LocationManager)Android.App.Application.Context.GetSystemService(Android.Content.Context.LocationService);`, or in #2575, `Android.Content.ContentResolver cr = Android.App.Application.Context.ContentResolver;`
I suppose these are from Xamarin.Android?

Or, in #5961, `Android.Manifest.Permission.ReadSms;`. In "standard' Android version it is READ_SMS. Somewhere property name was changed. Not in Xamarin.Android?

**Comment by MartinZikmund** [comment]
@pkar70 The change will only be that instead of targeting `monoandroidXY.Z` you will just target `netX-android` which will contain the same API surface as you have available now in Xamarin.Android.
