### ISSUE TITLE
[iOS/Android] SwipeControl, Releasing swipe on a Button / ListItem, triggers the click

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/uno#6522]
## Current behavior

When releasing a swipe the click action of the item underneath is triggered.

## Expected behavior

Releasing a swipe should not trigger the click action.

## How to reproduce it (as minimally and precisely as possible)

Apply a SwipeControl around a LisViewItem or Button.
Start swiping then release
Notice command of of the control is triggered 

## Workaround

None

## Works on UWP/WinUI

Yes

## Environment

Nuget Package:

Uno.UI: 3.9.0-dev.307
Uno.SourceGenerationTasks 3.1.0
Uno.UI.RemoteControl: 3.9.0-dev.233

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (Version 16.9.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
@dr1rrb related to or fixed by your recent fixes ?

**Comment by dr1rrb** [comment]
Same UI, but not the same bug. Validated on Windows, indeed the button clicked is not triggered ... which is against the common rule (a `Button` clicked is raised as soon as you press and release a pointer over it, no matter how far you moved).

**Comment by dr1rrb** [comment]
A workaround would be to use the `Tapped` event on the button (so you still get the visual states of the `Button`) instead of the `Clicked/Command`. The down side is if you disable the button using the `Command.CanExecute`, you will have either:
- Use 2 commands (one databound to the `Button.Command` and used only for the `CanExecute` and another one which has to be triggered by the `Tapped` using a custom behavior and which does the effective work)
- Handle the `Disable` by your own

**Comment by dr1rrb** [comment]
BTW, I would argue about the user experience of having a `Button` inside a `SwipeControl`. Either the action should probably be a one handled by the `SwipeControl`; either it's used for non touch platform (where `SwipeControl` does nothing) and then you should either use a context menu, either show the buttons only on mouse over (like the window's mail application)

**Comment by jeanplevesque** [comment]
> BTW, I would argue about the user experience of having a `Button` inside a `SwipeControl`. Either the action should probably be a one handled by the `SwipeControl`; either it's used for non touch platform (where `SwipeControl` does nothing) and then you should either use a context menu, either show the buttons only on mouse over (like the window's mail application)

@dr1rrb I think it's pretty common to have a clickable SwipeControl.
- You click the line item to open the details page.
- You swipe to reveal actions like delete, forward, reply, etc.

**Comment by dr1rrb** [comment]
> 
> @dr1rrb I think it's pretty common to have a clickable SwipeControl.
> 
>     * You click the line item to open the details page.
> 
>     * You swipe to reveal actions like delete, forward, reply, etc.

@jeanplevesque definitively agree for the click on the line item, but in that case I would expect that we use the [`ListView.ItemClick`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewbase.itemclick?view=winrt-20348) which would avoid to databind the same command on each item.

**Comment by jeanplevesque** [comment]
@dr1rrb Oh well lets use that then :)
We put the button because the behavior was less worse than the ItemClick. If both are bugged, lets fix the right one and use the proper method.

**Comment by MatFillion** [comment]
Even if you use itemclick, itemtemplates will have buttons sometimes, for a favorite action (click on a star icon) or a quick purchase action.

**Comment by dr1rrb** [comment]
This has been fixed by https://github.com/unoplatform/uno/pull/6575

> 
> 
> Even if you use itemclick, itemtemplates will have buttons sometimes, for a favorite action (click on a star icon) or a quick purchase action.

BTW I don't argue that it has to work, but as long as you have a `SwipeControl` having a nested button looks like a bad design to me: `SwipeControl` is a way to have "quick actions" on items in a list, if you mix multiple designs for the same kind of thing, it's most probably a wrong idea.

**Comment by MatFillion** [comment]
Swipe actions are also never discoverable so there's always an alternative way to do those actions because half the people won't know you can swipe things. Odds are the alternative way is via a details page or something and not directly as a button.

**Comment by jeanplevesque** [comment]
Great! @dr1rrb is there a published Uno.UI version with the fix available?
(I know sometimes it takes a while before pipelines complete.)

**Comment by jeromelaban** [comment]
The fix is available in 3.10.0-dev.183 or later

**Comment by jeanplevesque** [comment]
The fix works, thanks! :)

**Comment by jeanplevesque** [comment]
@jeromelaban @dr1rrb I just realized that ListViews containing SwipeControls don't scroll following the update. Is there something else I need to do? (I'm on 3.10.0-dev.376)

**Comment by dr1rrb** [comment]
@jeanplevesque did you tried with the version just before (i.e. 3.10.0-dev.366), version 376 contains [some other manipulations fixes](https://github.com/unoplatform/uno/pull/6725) which might have an impact here.

**Comment by jeanplevesque** [comment]
@dr1rrb The `ListView` containing `SwipeControls` properly scrolls on version 3.10.0-dev.**366** on both iOS and Android.
Thanks for that! I'll use that version for now.
