### ISSUE TITLE
[Playground][Wasm][Chrome] The scrollbar for snippets is not working properly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6536]
## Current behavior

https://user-images.githubusercontent.com/74563602/126703571-24291a0e-88e2-44b5-b544-24c640e8fdba.mp4

## Expected behavior
The scrollbar should display and work properly.

## How to reproduce it (as minimally and precisely as possible)

1. Visit https://playgroundcanary.z19.web.core.windows.net/#passwordbox
2. Open snippets combobx.
3. Try to scrolldown or scrollup using scrollbar.
4. Observe that so many time scrollbar doesn't show up.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
Related to #6439

**Comment by jeromelaban** [comment]
Fixed by https://github.com/unoplatform/uno/pull/6599

**Comment by sakshi173** [comment]
Issue is fixed, Closing.

**Comment by sakshi173** [comment]
Verified , issue is fixed, closing.
