### ISSUE TITLE
[CalendarDatePicker][WASM] Using a CalendarDatePicker in a DataGrid column doesn't commit selected date

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno#6543]
## Current behavior

Set up a DataGrid with a DataGridTemplateColumn that has a CellEditingTemplate as a CalendarDatePicker.  When the column is editing, you can open the calendar flyout.  However, selecting a date will not commit the value to the cell's data item.

## Expected behavior

The date selected in the calendar flyout would be applied to the data item.

## How to reproduce it (as minimally and precisely as possible)

Attaching a sample project. 
[App1.Shared.zip](https://github.com/unoplatform/uno/files/6869846/App1.Shared.zip)

## Works on UWP/WinUI
No. Microsoft has a similar bug ticket, but the behavior is different.  Their flyout immediately closes whereas Uno lets you pick a date.
https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/2493

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by duke7553** [comment]
@jeromelaban Potential fix submitted upstream: https://github.com/CommunityToolkit/WindowsCommunityToolkit/pull/4148

**Comment by jeromelaban** [comment]
Updated PR : https://github.com/CommunityToolkit/WindowsCommunityToolkit/pull/4206

**Comment by jeromelaban** [comment]
The updated WCT does not show the control properly
