### ISSUE TITLE
Move from `RoslynTester` to `Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.MSTest`

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#6549]
The testing library by Microsoft provides better experience.

- Ability to set language version easily. I couldn't find a way to do that with `RoslynTester`.
- Markup syntax for better readability.

**Comment by jeromelaban** [comment]
Thanks for the suggestion! Which feature are you trying to get working with this newer testing package ?

**Comment by Youssef1313** [comment]
@jeromelaban The main thing is writing a test for "target-typed new" feature. I'm fixing the analyzer in https://github.com/unoplatform/uno/pull/6550, but can't write a test for "target-typed new".
