### ISSUE TITLE
[WASM] ThemeResources for WASM not working correctly in TabView

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#6568]
## Current behavior

In some cases WASM does not handle ThemeResource values in the same fashion as UWP.

## Expected behavior

ThemeResources should work identically.

## How to reproduce it (as minimally and precisely as possible)

Open the attached project in UWP and observe that mouseover on tabs causes appropriate color change.  Open in WASM and observe that no color change is visible on mouseover for inactive tab.

[TabHighlightStyles.zip](https://github.com/unoplatform/uno/files/6887250/TabHighlightStyles.zip)

## Works on UWP/WinUI

No

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.9.0-dev.428
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by DierkDroth** [comment]
@jeromelaban where are we at on that issue?

**Comment by jeromelaban** [comment]
I verified again, this was fixed in Uno 3.10 as part of a larger theming issue.

**Comment by peternary** [comment]
Confirmed fixed in latest
