### ISSUE TITLE
Uno.Wasm.Bootstrap 3.0.0-dev.115 and later is slower 20% than 3.0.0-dev.101

### ISSUE THREAD

**Issue by easy28** [unoplatform/uno#6577]
## What would you like to be added:
Restore the performance of 3.0.0-dev.101

## Why is this needed:
My project load in 5 seconds  when using Uno.Wasm.Bootstrap 3.0.0-dev.101 ,  but 6.3s when using Uno.Wasm.Bootstrap 3.0.0-dev.115

Tested many times, and same result , so I think dev.115 have some code caused the bad performance.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report! Can you detail what your application uses ? It is using AOT or the interpreter ?

We're tracking these issues in the .NET runtime: https://github.com/unoplatform/uno/issues/4613, which have important performance implications using AOT.

**Comment by easy28** [comment]
here is my chrome console output:

Setting UNO_BOOTSTRAP_MONO_RUNTIME_MODE=Interpreter
Setting UNO_BOOTSTRAP_MONO_PROFILED_AOT=False
Setting UNO_BOOTSTRAP_LINKER_ENABLED=True
Setting UNO_BOOTSTRAP_DEBUGGER_ENABLED=True
Setting UNO_BOOTSTRAP_MONO_RUNTIME_CONFIGURATION=release

**Comment by jeromelaban** [comment]
Thanks. If you have `UNO_BOOTSTRAP_DEBUGGER_ENABLED` many optimizations are disabled. Make sure that you only set `MonoRuntimeDebuggerEnabled ` in `Debug` configuration.

Also, can you upgrade to a more recent bootstrapper version? The .NET team may have made some additional improvements in the runtime.

**Comment by easy28** [comment]
Upgraded to 3.0.0-dev.125, still slower than 3.0.0-dev.101 about 20% .   I am comparing the "release"  build.   Above chrome console output is under "debug" build for check setting purpose.

**Comment by jeromelaban** [comment]
Thanks. Can you indicate what is slower ? Do you have any specific part of the code that has regressed ?

**Comment by easy28** [comment]
Here is a quick test ,  just Create 1000 Canvases,   The average result is (omit the first two runs) :

3.0.0-dev.125   Create Canvas:0.939s
3.0.0-dev.101   Create Canvas:0.803s

Below is my test code : 

<Canvas Width="300" Height="300" Background="Green" Name="cLast">
</Canvas>
<Button Name="btnTest" Content="Test" FontSize="30" Click="btnTest_Click" ></Button>

private void btnTest_Click(object sender, RoutedEventArgs e)
{
            DateTime dt = DateTime.Now;
            for (int i = 0; i < 1000; i++)
            {
                Canvas c = new Canvas {Width=10,Height=10,Background=new SolidColorBrush(Colors.Red) };
                c.SetValue(Canvas.LeftProperty, (double)i);
                c.SetValue(Canvas.TopProperty, (double)i);
                cLast.Children.Add(c);
            }
            Console.WriteLine("Create Canvas:" + (DateTime.Now-dt).TotalSeconds+"s");
}

**Comment by jeromelaban** [comment]
The source of this issue is https://github.com/dotnet/runtime/issues/56884. A fix will be available uno bootstrapper until an official fix can be provided by the .NET team.

**Comment by jeromelaban** [comment]
Fixed in latest bootstrapper build.
