### ISSUE TITLE
[UWP] ElevatedView is missing the default style

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#6581]
## Current behavior

The default style for `{Uno.UI.Toolkit}ElevatedView` is missing on UWP.

## How to reproduce it (as minimally and precisely as possible)

[UwpEvNotWorkingAgain.zip](https://github.com/unoplatform/uno/files/6893973/UwpEvNotWorkingAgain.zip)
```xml
		<toolkit:ElevatedView Background="White"
							  BorderBrush="DeepPink"
							  BorderThickness="2"
							  CornerRadius="8"
							  ShadowColor="Pink"
							  MaxWidth="100"
							  Elevation="10"
							  Margin="16"
							  void:Style="{StaticResource DefaultElevatedViewStyle}">
			<Border Background="SkyBlue">
				<TextBlock Text="Test"
						   Foreground="Black" />
			</Border>
		</toolkit:ElevatedView>
```
> remove the "void:" to make it visible.

## Workaround

Define a default or keyed style for the control.

## Works on UWP/WinUI
No

## Environment
Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): Uno.UI@3.10.0-dev.40

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins: n/a

## Anything else we need to know?
Looking at the visual tree, there is nothing under that control:
![image](https://user-images.githubusercontent.com/2359550/127343733-57e4189c-8f9f-42da-9c3e-3c3a8e54b029.png)

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/3.9

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/3.9
