### ISSUE TITLE
[WASM] `Canvas` incorrectly clips its children

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#6595]
## Current behavior

For the following XAML:
```xaml
<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <ScrollViewer>
            <Canvas VerticalAlignment="Center" HorizontalAlignment="Center">
                <Line X1="50" Y1="0" X2="-100" Y2="100" Stroke="Black" StrokeThickness="5" StrokeStartLineCap="Round" StrokeEndLineCap="Triangle"/>
            </Canvas>
        </ScrollViewer>
    </Grid>
```

Uno 3.9 shows the following:

![image](https://user-images.githubusercontent.com/5839577/127558897-9ec3fcb1-fd3e-49e3-90f3-512ad7944cb7.png)

## Expected behavior

UWP shows the following:

![image](https://user-images.githubusercontent.com/5839577/127558930-84422da4-fb23-463b-84ef-713f49ecbd8f.png)

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.9.1

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment]
I think this will be fixed in https://github.com/unoplatform/uno/pull/13220

**Comment by Youssef1313** [comment]
Latest canary shows this is fixed.

![image](https://github.com/unoplatform/uno/assets/31348972/8bf04dde-cd38-4e15-8a90-46061be96859)
