### ISSUE TITLE
Uno.UI.MSAL miss non .NET 6 targets

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/uno#6596]
### Compare [Uno.UI](https://www.nuget.org/packages/Uno.UI/3.9.1) target frameworks
<img src="https://user-images.githubusercontent.com/2365592/127562792-1dbc520d-0189-4f8c-b2b9-77d16a2d404a.png" alt="image" width="400" style="max-width:50%;">

### and [Uno.UI.MSAL](https://www.nuget.org/packages/Uno.UI.MSAL/3.9.1)
<img src="https://user-images.githubusercontent.com/2365592/127562854-5c58c899-bc99-411f-9f49-dd8aa4a5c1dc.png" alt="image" width="200" style="max-width:30%;">

## Expected behavior

Uno.UI.MSAL is usable on Xamarin and .NET Standard 2.0

## Environment

Nuget Package:
- Uno.UI.MSAL

Nuget Package Version(s): 3.9.1, 3.10.0

Affected platform(s):

- iOS
- Android
- WebAssembly
- macOS
- Skia
  - WPF
  - GTK (Linux)
  - Tizen
- Windows

**Comment by xperiandri** [comment]
Tizen is missing. Must it be available?

**Comment by xperiandri** [comment]
@carldebilly is it supported?

**Comment by jeromelaban** [comment]
Tizen is not supported, no.
