### ISSUE TITLE
[Wasm] Add support for LinearGradientBrush

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#660]
## I'm submitting a...
- Feature request

## Expected behavior
Add support for [LinearGradientBrush](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.LinearGradientBrush)

## Environment

```
Nuget Package: 1.43.0

Affected platform(s):
- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by carldebilly** [comment]
Different implementation (but similar) for HTML elements and SVG elements.

**Comment by davidjohnoliver** [comment]
This was completed with https://github.com/unoplatform/uno/pull/2216
