### ISSUE TITLE
[Gallery][Android/iOS] CalendarDatePicker-Wrong year display on Header for the selected year from the decade calendar and after that monthly and decade calendar does not work properly

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6603]
## Current behavior

https://user-images.githubusercontent.com/74563602/127659956-d4f996de-07b1-43ae-9ebb-040e00179251.mp4

## Expected behavior
The calendar should work properly.

## How to reproduce it (as minimally and precisely as possible)
Open Uno Gallery APP
Click Burger Menu on the left top right.
Click "CalendarView" from the "Component" list.
Click on Select a Date button.
Go to Monthly Calendar view for the current year.
Choose any month and date for that year.
Again go to Decade calendar view.
Click on any year on the decade calendar view.
Observe that some random year display instead of the selected year on the Header.

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Canary Build:**
Version 1.5.0 (400822)
Jul 27, 2021 at 22:46

**Comment by YGuerin** [comment]
This issue also occurs on iOS

**Comment by andreaSflores18** [comment]
Expected release date: Mid september

**Comment by sakshi173** [comment]
CalendarDatePicker control is removed for Android/iOS platforms, due to that closing this bug.
