### ISSUE TITLE
WinUI Expander Doesn't Clip During Expand/Collapse

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#6636]
## Current behavior

When the Microsoft.UI.Xaml Expander expands/collapses the animation isn't clipped to the content area. This means it appears overtop of the header.

![fassse](https://user-images.githubusercontent.com/17993847/127911708-53c4381c-a7d6-47ca-8e26-87687bb46da6.gif)

The expander code that should clip this is here. There is an error or something isn't implemented in Uno (likely composition related, but I'm unfamiliar with these APIs and haven't read the docs).

https://github.com/unoplatform/uno/blob/e70c72425f5bc73cca71dee880e7a61d40b21e50/src/Uno.UI/Microsoft/UI/Xaml/Controls/Expander/Expander.cs#L81-L85

## Expected behavior

See operation in UWP:

![fassse](https://user-images.githubusercontent.com/17993847/127911879-a4a491c8-6301-4bb9-856a-6c4f60f0cc40.gif)

## Workaround

none

## Works on UWP/WinUI

Yes

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.9.1

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. Fixing this requires to implement this without the composition API, replacing it with the `UIElement.Clip` property.

**Comment by robloo** [comment]
@jeromelaban Ok, easy enough. I guess I wasn't sure if standard clipping was really working yet for animations like this.

If/when I get Uno building again I'll fix this one.

**Comment by Youssef1313** [comment]
@jeromelaban The not implemented analyzer doesn't seem to be referenced/enabled for Uno.UI, and I feel it can be super powerful to detect these kind of bugs. What do you think about enabling it, figure out what bugs will exist in places where the diagnostic is produced, and then suppress the diagnostic with a link to an issue.

**Comment by carldebilly** [comment]
Inside Uno there's an interface named `ICustomClippingElement` that can be used to force the clipping mode on a specific control.
