### ISSUE TITLE
MUX DropDownButton/SplitButton/ToggleSplitButton Don't Show Chevron Glyph

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#6638]
## Current behavior

The Microsoft.UI.Xaml DropDownButton, SplitButton and ToggleSplitButton don't show the down chevron glyph. ~It instead falls back to a font besides Segoe MDL2 Assets (the Uno Equivalent).~

![image](https://user-images.githubusercontent.com/17993847/127913574-e9f7516c-6e7e-488c-bc6c-fc5e99d496a4.png)

I'm not sure where this issue happens as the code seems to be correct. This may be an issue with Resource lookup but then I wonder how any other controls work. Perhaps the glyph itself is missing from the Uno Font and we should change it to the ComboBox Unicode point.

https://github.com/unoplatform/uno/blob/e70c72425f5bc73cca71dee880e7a61d40b21e50/src/Uno.UI/UI/Xaml/Controls/DropDownButton/DropDownButton.xaml#L113-L115

## Expected behavior

The chevron should be shown.

## How to reproduce it (as minimally and precisely as possible) / Test App

See the following test application.

[DropDownButtonTest.zip](https://github.com/unoplatform/uno/files/7073184/DropDownButtonTest.zip)

## Works on UWP/WinUI

Yes

## Environment

```
Nuget Package Version(s): 3.9.1
Visual Studio 2019 Version 16.11.1
Windows 10 Pro 21H1 19043.1165
Android Emulator: Pixel 2 Q 10.0 - API 29
```

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.9.1

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Adding the missing glyph in https://github.com/unoplatform/uno.fonts is likely the way to fix this.

**Comment by robloo** [comment]
My assumption was the glyph was the same as is used in the ComboBox. However, I couldn't find the ComboBox style when I first looked (very quickly).

For my own custom controls, I use the newer 0xE70D Unicode point which Uno includes in the default symbol font. The easiest would be to switch to this newer Unicode point as nearly all chevrons are the same. That would make it a XAML-only change but then any style updates from upstream would clear the change again.

**Comment by jeromelaban** [comment]
Here's the glyph used for combobox:

https://github.com/unoplatform/uno/blob/3bff3470b445c91dd2a1150a7b90d218cc7a878b/src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml#L731

It's probably already modified somehow from the original version. We'll certainly need to readjust for the new WinUI 2.6 styles in https://github.com/unoplatform/uno/pull/6374.

**Comment by robloo** [comment]
I reproduced this issue with a brand-new, empty app so it's isn't something caused as a secondary issue. It really confuses me:

 1. Both DropDownButton and ComboBox are using the exact same Unicode point 0xE0E5 so it isn't a font issue
 1. The correct font family is specified: SymbolThemeFontFamily and I double checked spelling
 2. ComboBox is switching to a TextBlock ONLY for Android. This is suspicious and something I can't explain. Regardless, DropDownButton is already using a TextBlock.

It's like the DropDownButton style can't find the SymbolThemeFontFamily resource.

**TextBlock:**
https://github.com/unoplatform/uno/blob/e70c72425f5bc73cca71dee880e7a61d40b21e50/src/Uno.UI/UI/Xaml/Controls/DropDownButton/DropDownButton.xaml#L110-L119

**ComboBox:**
https://github.com/unoplatform/uno/blob/3bff3470b445c91dd2a1150a7b90d218cc7a878b/src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml#L723-L746

**Comment by jeromelaban** [comment]
> It's like the DropDownButton style can't find the SymbolThemeFontFamily resource.
> 

@davidjohnoliver does this sound familiar ?

**Comment by davidjohnoliver** [comment]
> > It's like the DropDownButton style can't find the SymbolThemeFontFamily resource.
> 
> @davidjohnoliver does this sound familiar ?

Not really... I'm not sure what would be going wrong here.

**Comment by robloo** [comment]
This affects MUX SplitButton and ToggleSplitButton as well, added to the description and title

**Comment by Youssef1313** [comment]
@robloo Which platform are you testing against?

The glyph shows correctly for me (at least for `[Toggle]SplitButton`) in SamplesApp on Android.

![image](https://user-images.githubusercontent.com/31348972/131259368-7a190e13-32a4-410b-be5d-4571d9e9beeb.png)

**Comment by robloo** [comment]
@Youssef1313 Thanks for taking a look. I've updated the environment section of the issue description adding more details. This is reproducible in a blank app. I never noticed this in the SamplesApp.

![image](https://user-images.githubusercontent.com/17993847/131263719-43a71171-a746-44f9-a73d-0921ccb13fbe.png)

**Comment by robloo** [comment]
@Youssef1313 I added a test application for this as well. See the issue description for the link.

**Comment by Youssef1313** [comment]
After spending the last 3 hours on this. I think I (*partially*) figured out things. (Looks a bit embarrassing to take that too much time for the small finding 😄 ):

- The MUX DropDownButton doesn't seem to be implemented in Uno.
- The sample I'm referring to in https://github.com/unoplatform/uno/issues/6638#issuecomment-907831292 is using WUXC.DropDownButton (while the sample name says MUX, which is a bit misleading).

The confusing part to me is that how using the MUXC.DropDownButton partially works in Android (ie, only the glyph doesn't show correctly) while it's completely not implemented.

**Comment by jeromelaban** [comment]
The MUX `DropDownButton` is implemented in Uno https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Controls/DropDownButton/DropDownButton.cs (from @MartinZikmund), it is the one you're referring to?

And no worries about the time ;)

**Comment by Youssef1313** [comment]
@jeromelaban Then there is some gap I'm not understanding here. I thought it should be in `Microsoft.UI.Xaml.Controls` namespace as opposed to `Windows.UI.Xaml.Controls`?

**Comment by Youssef1313** [comment]
By the way, here is a workaround (and weird behavior at the same time):

![image](https://user-images.githubusercontent.com/31348972/131549984-718db12e-117a-4573-8b11-1d2925f89655.png)

@jeromelaban Does the behavior described in the above image points to any possibilities?

**Comment by robloo** [comment]
Yea, it's always something seemingly simple that takes the most time. This one is really strange to me and it's entirely possible I'm overlooking something simple myself.

Apologies for confusion about Windows.UI.Xaml vs Microsoft.UI.Xaml namespaces. (I had momentarily forgotten these were implemented in both). In this issue I am always referring to `Microsoft.UI.Xaml.Controls` which includes the latest pre-2.5 version 1 styles as well. The repro test app is also using `Microsoft.UI.Xaml.Controls` I refer to as "MUX" and others may call "MUXC".

**Comment by robloo** [comment]
After looking at the code I agree this is very strange that it works anyway. DropDownButton is missing from the MUX controls. I thought for sure Martin ported this though. Perhaps he used the MUX source but put it in the WUX namespace?

https://github.com/unoplatform/uno/tree/master/src/Uno.UI/Microsoft/UI/Xaml/Controls

How does this work at all? Is code generation automatically adding it to the MUX namespace?

All of this said, SplitButton has the same issue but is implemented as expected: https://github.com/unoplatform/uno/tree/master/src/Uno.UI/Microsoft/UI/Xaml/Controls/SplitButton

**Comment by Youssef1313** [comment]
@robloo The repro app **is** and **is not** using `Microsoft.UI.Xaml.Controls`. You specifiy Microsoft in XAML, the source generator generates Windows, which seems like a separate bug (probably it just incorrectly falls back to any control with the name if it's not found in the given namespace).

Using Windows instead of Microsoft still reproduces the issue (which is expected since the generated code didn't change).

**Comment by robloo** [comment]
> You specifiy Microsoft in XAML, the source generator generates Windows, which seems like a separate bug (probably it just incorrectly falls back to any control with the name if it's not found in the given namespace).

Ok, that answers the big question of how this even works to begin with. DropDownButton is not implemented in Microsoft.UI.Xaml.Controls as we both noted. My guess is this is an intentional fallback though -- however unexpected it might be. I certainly think this needs to change long term: we should do what was finally decided for NavigationView and put it in the MUX directory (even though those same sources were used for WUX version).

**Comment by Youssef1313** [comment]
> however unexpected it might be

Yes it's very unexpected. At minimum, I think the generator should produce a warning. So the compilation doesn't fail but the developer is informed that the control doesn't exist in namespace X and we'll use namespace Y.

This is, however, a little bit separate from the issue here.

I think the questions are:

- How does this work correctly in SamplesApp, but not outside of it.
- How does adding a dummy empty class that derives from DropDownButton fixes the issue?

I was never able to debug an external app following [these instructions](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/debugging-uno-ui.md#debugging-uno-in-another-application), so it's hard to debug for me without reproducing in samples app 😕

**Comment by Youssef1313** [comment]
I'm very suspicious about this:

https://github.com/unoplatform/uno/blob/39e38367b7aa63e42b5acbd2af38ab23bd00350e/src/Uno.UI.FluentTheme/Resources/PriorityDefault/DropDownButton.xaml#L107-L116

**Comment by robloo** [comment]
> I was never able to debug an external app following these instructions, so it's hard to debug for me without reproducing in samples app 😕

I haven't been able to build Uno for quite some time for some reason. So I won't be able to test this locally and step into Uno source. I've had the setup working in the past on some other issues though. When I finish work on performance and work-arounds I'll have bugs like this to address. So eventually I will circle back to issues I file and spend more time on them. I decided just to file them so they are known and discussed. That said, issues like this are outside my area of knowledge and I'm not sure where to start.

**Comment by robloo** [comment]
@Youssef1313 That's almost certainly it! I was never sure about those styles and they are organized strangely to me.

https://github.com/unoplatform/uno/issues/4435
https://github.com/unoplatform/uno/pull/6374#issuecomment-882010481

Note that all occurrences of `FontFamily="Segoe MDL2 Assets"` were fixed upstream.

https://github.com/microsoft/microsoft-ui-xaml/issues/3745
https://github.com/microsoft/microsoft-ui-xaml/pull/3923

That needs to be changed here as well to `FontFamily="{ThemeResource SymbolThemeFontFamily}" `. The resources are definitely very confusing here and likely incorrect. The priority folders really need to be removed IMO.

**Comment by jeromelaban** [comment]
@robloo take a look at this video I made yesterday for building uno: https://www.twitch.tv/videos/1135290868

**Comment by robloo** [comment]
@jeromelaban Thanks, I did have the full setup working last year -- including debugging an app with Uno source. However, every few months the build breaks and I have to spend a lot of time figuring out what went wrong. Last time it broke I wasn't able to fix it within a few hours. It was at the time related to the VS issue you filed that would just silently refuse to build some projects. I'm not sure why it's so fragile.

**Comment by jeromelaban** [comment]
If you encounter this again, open an issue with the build errors, we can certainly enhance the build validations for the errors to be more explicit.

**Comment by robloo** [comment]
> If you encounter this again, open an issue with the build errors, we can certainly enhance the build validations for the errors to be more explicit.

Will do. In the issue I'm thinking of it was Visual Studio and there was nothing you could do. You filed an issue for it but I can't find it at the moment to see if it was closed.

**Comment by robloo** [comment]
Confirmed to work in Uno.UI version 3.10.7!
