### ISSUE TITLE
XamlReader.Load(string) Doesn't Resolve ThemeResource 

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#6639]
## Current behavior

XamlReader.Load will not resolve ThemeResources inside the passed XAML string. Code such as below will not find the desired font family or font size.

```csharp
            string itemXaml =
            @"<DataTemplate xmlns=""http://schemas.microsoft.com/winfx/2006/xaml/presentation"">
                <ListViewItem
                  Padding=""3,6,0,6""
                  HorizontalContentAlignment=""Stretch"">
                  <Grid>
                    <StackPanel
                      Orientation=""Horizontal""
                      Margin=""{Binding LeftOffsetPadding}"">
                      <FontIcon
                        Glyph=""&#xF418;""
                        FontFamily=""{ThemeResource AppSymbolFontFamily}""
                        FontSize=""{ThemeResource AppSymbolFontSize}""
                        VerticalAlignment=""Bottom""
                        Visibility=""{Binding IconVisibility}"" />
                      <TextBlock
                        Text=""{Binding Text}""
                        VerticalAlignment=""Bottom""
                        Margin=""5,0,0,0"" />
                    </StackPanel>
                  </Grid>
                </ListViewItem>
              </DataTemplate>";

            this.ItemsListView.ItemTemplate = XamlReader.Load(itemXaml) as DataTemplate;
```

## Expected behavior

ThemeResource resolution should work.

## Workaround

You can resolve the theme resources in C# directly using:

```csharp
var symbolFont = (FontFamily)App.Current.Resources["AppSymbolFontFamily"];
var symbolFontSize = (double)App.Current.Resources["AppSymbolFontSize"];
```

Then convert those values into a string when constructing the XAML. You essentially do your own resource lookup before loading the XAML.

```csharp
...<FontIcon
  Glyph=""&#xF418;""
  FontFamily=""" + symbolFont.Source + @"""
  FontSize=""" + symbolFontSize.ToString(CultureInfo.InvariantCulture) + @"""
  VerticalAlignment=""Bottom""
  Visibility=""{Binding IconVisibility}"" />...
```

## Works on UWP/WinUI

Yes 

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.9.1

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by rettelex3515** [comment]
#ios <# null + there should be a bill zero and stc code

**Comment by robloo** [comment]
@rettelex3515 Can you clarify? I'm not sure what your comment means.

**Comment by jeromelaban** [comment]
## Note for contributors

This feature support should be added through here: https://github.com/unoplatform/uno/blob/f56230cea1e55d5c4f723b845e835f69d8535997/src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs#L450-L460
