### ISSUE TITLE
RadialGradientBrush erorr to Binding from GradientStop Color

### ISSUE THREAD

**Issue by AbdalaMask** [unoplatform/uno#6642]
## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [x] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

RadialGradientBrush erorr to Binding from GradientStop Color
TestRadialGradientBrush
[TestRadialGradientBrush.zip](https://github.com/unoplatform/uno/files/6919872/TestRadialGradientBrush.zip)

**Comment by Youssef1313** [comment]
Hi @AbdalaMask 👋 

I downloaded the repro project you attached, but it's not clear what the issue is. You had a few compile-time errors due to undeclared members and missing using. After I fixed that, it compiled successfully with the following appearance on Wasm:

![image](https://user-images.githubusercontent.com/31348972/129028038-fe0a1cf1-4ace-4103-aa32-f4afb8a064a8.png)

Can you please add more information to the issue? Thanks!

**Comment by AbdalaMask** [comment]
https://stackoverflow.com/questions/67405178/how-can-i-dynamically-change-gradientstop-color-for-radialgradientbrush-in-uwp

**Comment by AbdalaMask** [comment]
When you change colors, they don't change
does not accept change

**Comment by AbdalaMask** [comment]
<GradientStop Color="{Binding OffColor, RelativeSource={RelativeSource Mode=TemplatedParent}}" Offset="0.5"/>
not link GradientStop Color to proprty  OffColor
![image](https://user-images.githubusercontent.com/37013638/129138918-a08d48cf-7491-4747-9491-81dfccf9bfd2.png)

**Comment by AbdalaMask** [comment]
![)6X1C5EN6J{QB)2F_Z29S}D](https://user-images.githubusercontent.com/37013638/129138970-08cb9b99-179f-4f77-aff1-34295c292a15.png)

**Comment by AbdalaMask** [comment]
![A1K_R8O5(HSZT3~)PC 17N4](https://user-images.githubusercontent.com/37013638/129139976-a9977de0-a9df-426e-a378-f6a35036ee2a.png)

**Comment by AbdalaMask** [comment]
You have to look like that

**Comment by Youssef1313** [comment]
@AbdalaMask Is your problem Uno-specific or in UWP as well?

**Comment by AbdalaMask** [comment]
All
Web
Uwp
Andrid

في الخميس، ١٢ أغسطس ٢٠٢١ ١٠:٤٧ ص Youssef Victor ***@***.***>
كتب:

**Comment by Youssef1313** [comment]
In a pure UWP app, if you get the same behavior, then Uno is behaving as expected.

**Comment by AbdalaMask** [comment]
Using wpf good

في الخميس، ١٢ أغسطس ٢٠٢١ ٤:٥٥ م Youssef Victor ***@***.***>
كتب:

**Comment by AbdalaMask** [comment]
Works well to wpf

في الخميس، ١٢ أغسطس ٢٠٢١ ٤:٥٨ م abdala Mask ***@***.***> كتب:

**Comment by Youssef1313** [comment]
WPF seems unrelated here. If UWP and WPF has different behaviors, then Uno must match UWP.

**Comment by AbdalaMask** [comment]
fix erorr
` RadialGradientBrush brush1 = new RadialGradientBrush()
                {
                    RadiusX = 0.67,
                    RadiusY = 0.67,
                    GradientOrigin = new Windows.Foundation.Point(0.6, 0.35),
                    Center = new Windows.Foundation.Point(0.6, 0.35),

                };
                brush1.GradientStops.Add(new GradientStop { Color = (Color)new ColorLightConverter().Convert(Value ? OnColor : OffColor, typeof(Color), 50, ""), Offset = 0.0 });
                brush1.GradientStops.Add(new GradientStop { Color = Value ? OnColor : OffColor, Offset = 1.0 });
                xBackground.Fill = brush1 as Brush;
`
