### ISSUE TITLE
Windows.System.Launcher.LaunchUriAsync() Throws an Exception

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#6644]
## Current behavior

The following code will crash an Android Uno App ~with a null reference exception~ after calling into the framework implementation of LaunchUriAsync(). This previously worked.

This may be related to older HTTP URLs.

```csharp
            try
            {
                var uri = new Uri("<insert HTTP URL>");
                var success = await Windows.System.Launcher.LaunchUriAsync(uri);
            }
            catch { }
```

## Expected behavior

No crash

## Works on UWP/WinUI

Yes

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.9.1

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

Can you provide the stack trace of the exception?

**Comment by robloo** [comment]
@jeromelaban Is this enough?

```
 	0xC in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:157,13	C#
 	0x6 in System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_1 at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1037,55	C#
 	0x13 in System.Threading.QueueUserWorkItemCallback.WaitCallback_Context at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1370,13	C#
 	0x73 in System.Threading.ExecutionContext.RunInternal at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:968,17	C#
 	0x4 in System.Threading.ExecutionContext.Run at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:910,13	C#
 	0x2E in System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1341,17	C#
 	0x75 in System.Threading.ThreadPoolWorkQueue.Dispatch at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:899,29	C#
 	0x0 in System.Threading._ThreadPoolWaitCallback.PerformWaitCallback at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1261,13	C#

```

System.InvalidOperationException
  Message=The application called an interface that was marshalled for a different thread.

**Comment by robloo** [comment]
Note that the URI navigation is actually successful. The link is passed to Chrom and opened after the app crashes.

**Comment by jeromelaban** [comment]
Interesting that the crash is happening this way. This specific message is raised when invoking this:

https://github.com/unoplatform/uno/blob/56d3ba98ee6cab055dc8d7c4941ce4494e20e946/src/Uno.UWP/UI/Core/CoreDispatcher.cs#L66

Which means that the original source for this is somewhere else. Can try getting the actual call site for this ? (by breaking on all exceptions)

**Comment by robloo** [comment]
I now realize that this is likely crashing as the app goes into suspended state. It may have nothing to do with opening a URL other than doing so causes the app to go to the background.

I'll hopefully provide more details soon. The suspending crash is a hard one for me to understand but will likely file a separate issue for it (likely related to deferral usage).

**Comment by robloo** [comment]
It was confirmed this is not an issue with launching the URL; therefore, I'm closing this issue. Apologies for misunderstanding where the real issue was happening.

The exception is occurring when SuspendingDeferral.Complete() is called. OnSuspending is run when the app goes to the background after it launches the URL. I'll open a separate issue for that as it does work on UWP.
