### ISSUE TITLE
[ValidationView? Textbox][Android] Binding to Text of Textbox is not properly updated

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/uno#6680]
## Current behavior

We have a textblock that displays the length of text entered in a textbox wrapped inside a validation view. On android the value displayed is not properly updated, (get stuck at 1 or 3 depending on how fast you type). 

![image](https://user-images.githubusercontent.com/64613932/128564549-90640e06-1c83-4a3b-91af-c4243bbf902f.png)

## Expected behavior

Any changes in the text of textbox should be reflected in the value displayed by the counter.

## How to reproduce it (as minimally and precisely as possible)

On android
Launch the App 
Tap on the Burger menu at the top-left
Tap on Create button
Enter text on the text entry field
Notice the counter not update. The counter remains in 1

Have some problem updating uno.UI on my repro template, this repro does not replicate the bug.
[ReproAndroidTextboxcounter.zip](https://github.com/unoplatform/uno/files/6947720/ReproAndroidTextboxcounter.zip)

## Workaround

None

## Works on UWP/WinUI
Yes

## Environment

Nuget Package:

- [x] Uno.UI ver:  v2.4.0
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. 

I cannot reproduce your issue, see this screen capture:

![6680-repro](https://user-images.githubusercontent.com/5839577/128567387-2b799691-b655-4985-bcb0-2a4cc12ad2b9.gif)

**Comment by jeanplevesque** [comment]
@MaximeDion-Work Uno.UI 2.4.0 is way too old. That's probably the reason the bug isn't reproduced.

**Comment by jeanplevesque** [comment]
@MaximeDion-Work Make sure you use the latest version of the UnoAppTemplate or the Uno Visual Studio Extension to generate the base of your sample.

**Comment by jeromelaban** [comment]
Make sure to retry with a latest build of Uno, ElementName bindings (particularly in templates) have been adjusted.

**Comment by MaximeDion-Work** [comment]
The issue is gone from the app, we are on Uno.UI 3.10.0-dev.366.
