### ISSUE TITLE
[Skia.WPF] XamlExtensions are not supported

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#6688]
```xaml
<Grid e:GridExtensions.ColumnsAndRows="*,A,*;*,A,*">
  <TextBlock 
    Grid.Column="1" 
    Grid.Row="1" 
    Text="Hello, world!" 
    FontSize="100" 
    />
</Grid>
```

## Current behavior
```
1>Uno.UI is using Roslyn generators
1>CSC : error UXAML0001: Unable to convert *,A,*;*,A,* for ColumnsAndRows with type string?
1>C:\Users\haven\Source\Repos\HavenDV\Bugs.Uno.Skia.WPF.XamlExtensionBug\Bugs.Uno.Skia.WPF.XamlExtensionBug.Shared\MainPage.xaml(1,2,1,2): error UXAML0001: An error was found in Page
1>CSC : error UXAML0001: Processing failed for file C:\Users\haven\Source\Repos\HavenDV\Bugs.Uno.Skia.WPF.XamlExtensionBug\Bugs.Uno.Skia.WPF.XamlExtensionBug.Shared\MainPage.xaml (Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: An error was found in Page ---> System.Exception: Unable to convert *,A,*;*,A,* for ColumnsAndRows with type string?
1>C:\Users\haven\Source\Repos\HavenDV\Bugs.Uno.Skia.WPF.XamlExtensionBug\Bugs.Uno.Skia.WPF.XamlExtensionBug.Shared\App.xaml.cs(41,18,41,37): error CS1061: 'App' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'App' could be found (are you missing a using directive or an assembly reference?)
1>C:\Users\haven\Source\Repos\HavenDV\Bugs.Uno.Skia.WPF.XamlExtensionBug\Bugs.Uno.Skia.WPF.XamlExtensionBug.Shared\MainPage.xaml.cs(27,18,27,37): error CS1061: 'MainPage' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)
1>Done building project "Bugs.Uno.Skia.WPF.XamlExtensionBug.Skia.WPF.csproj" -- FAILED.
```

## Expected behavior

It should work.

## How to reproduce it (as minimally and precisely as possible)
https://github.com/HavenDV/Bugs.Uno.Skia.WPF.XamlExtensionBug
[Bugs.Uno.Skia.WPF.XamlExtensionBug-main.zip](https://github.com/unoplatform/uno/files/6951315/Bugs.Uno.Skia.WPF.XamlExtensionBug-main.zip)

## Works on UWP/WinUI
Yes

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.9.7

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [x] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: latest stable)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment]
Looking into this.
