### ISSUE TITLE
Composition API backend

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#670]
## I'm submitting a...
- Feature request

## Expected behavior
The Uno platform should provide a composition-api backend for rendering, as well as platform abstractions such as input, accessibility, etc...

One of the possible backends is Skia#.

Related:
https://github.com/unoplatform/uno/issues/2318

**Comment by handicraftsman** [comment]
Skia is too large, and embedding it into web assembly applications is a very, very bad idea. Especially because most browsers (except for Firefox and Safari) are already powered by Skia.

I think we could better have some abstraction layer for defining operations we want rendering backends to execute, and use it for rendering actual UI.

**Comment by handicraftsman** [comment]
For sake of portability to other languages and rendering frontends/backends and operating systems that layer could be done as a C++ library (if msbuild supports using C++ libraries)

**Comment by jeromelaban** [comment]
That's where the UWP composition API makes sense, as it already defines that layer. We're not expecting to use it in WebAssembly at first, though, and yes, it could be done using C++.

**Comment by handicraftsman** [comment]
Nice! I will even try contributing (how i can though as i did not do GUI programming much before) if that actually gets published.

**Comment by handicraftsman** [comment]
On linux you might need 2 backends, possibly in the same library: for X11 and for Wayland - features like partial window transparency are implemented depending on windowing system.

**Comment by ghuntley** [comment]
> I have a very large and complex UWP project. I’m trying to decide if I want to start porting it to Uno. My project contains 4 or 5 custom controls that rely heavily on Composition API and 2 of them rely on Win2D. How realistic is it to expect these would work on Android or iOS in the near future? I know it’s in the roadmap but that could be pie in the sky wishlist afaik.

https://github.com/unoplatform/uno/issues/1229

**Comment by jeromelaban** [comment]
Added in Uno 3.1. Let's keep track of the support in individual issues.
