### ISSUE TITLE
Invalid comment source generation in WCT

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#6733]
## Current behavior

The compilation fails with the following errors (formatting breaks because of backquotes):

D:\a\1\s\Microsoft.Toolkit.Uwp.UI.Controls.Layout\obj\Release\xamarinmac20\g\NativeCtorsGenerator\Microsoft_Toolkit_Uwp_UI_Controls_PropertyChangeEventSource_TPropertyType__fca3e7386d803e365f0d121b8533af45.g.cs(18,52): error CS1584: XML comment has syntactically incorrect cref attribute 'Microsoft.Toolkit.Uwp.UI.Controls.PropertyChangeEventSource`1' [D:\a\1\s\Microsoft.Toolkit.Uwp.UI.Controls.Layout\Microsoft.Toolkit.Uwp.UI.Controls.Layout.csproj]
         D:\a\1\s\Microsoft.Toolkit.Uwp.UI.Controls.Layout\obj\Release\xamarinmac20\g\NativeCtorsGenerator\Microsoft_Toolkit_Uwp_UI_Controls_PropertyChangeEventSource_TPropertyType__fca3e7386d803e365f0d121b8533af45.g.cs(18,111): error CS1658: Unexpected character 'backquote'. See also error CS1056. [D:\a\1\s\Microsoft.Toolkit.Uwp.UI.Controls.Layout\Microsoft.Toolkit.Uwp.UI.Controls.Layout.csproj]
         D:\a\1\s\Microsoft.Toolkit.Uwp.UI.Controls.Layout\obj\Release\xamarinmac20\g\NativeCtorsGenerator\Microsoft_Toolkit_Uwp_UI_Controls_PropertyChangeEventSource_TPropertyType__fca3e7386d803e365f0d121b8533af45.g.cs(18,112): error CS1658: Unexpected character '1'. See also error CS1056. [D:\a\1\s\Microsoft.Toolkit.Uwp.UI.Controls.Layout\Microsoft.Toolkit.Uwp.UI.Controls.Layout.csproj]

The generated code is as follows:

```csharp
#if True
		/// <summary>
		/// Initializes a new instance of the <see cref="Microsoft.Toolkit.Uwp.UI.Controls.PropertyChangeEventSource`1"/> class.
		/// </summary>
		public PropertyChangeEventSource() { }
#endif
```

## Expected behavior

The compilation does not fail.

**Comment by jeromelaban** [comment]
@Youssef1313 Can you take a look at this one?

**Comment by Youssef1313** [comment]
Likely a roslyn bug. Will check and open a roslyn issue, and find a workaround for it for the source generator.

**Comment by jeromelaban** [comment]
It's a new regression from a recent PR, we're likely using the metadata name instead of something XML-comment friendly.

**Comment by Youssef1313** [comment]
I'm using DocumentationCommentId class for this. Opened https://github.com/dotnet/roslyn/issues/55572, and will manually handle generics. Or probably not bother at all and don't mention the class name in the comment?

**Comment by jeromelaban** [comment]
Right, removing the name is probably best.
