### ISSUE TITLE
[WASM] Using Insert to add items to ComboBox results in issues with IsSelected

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#6739]
## Current behavior

In WASM, adding items to a ComboBox using the ComboBox.Items.Insert method results in IsSelected property of a combobox item being ignored in the dropdown.  ComboBox.Items.Add works correctly.

## Expected behavior

Insert and Add should have identical behavior (matching UWP) as regards item selection.

## How to reproduce it (as minimally and precisely as possible)
Open the attached project in UWP and click both comboboxes, noticing that string3 is selected both in the combobox and in the dropdown for the combobox.

Open in WASM and observe that only the first combobox properly selects string3 in the dropdown - the other combobox selects string1, the most recently added item.

[ComboBoxSelection.zip](https://github.com/unoplatform/uno/files/6977308/ComboBoxSelection.zip)

## Works on UWP/WinUI

Yes

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.10.0-dev.324
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment]
I'm not able to reproduce. Here is what I get on Wasm.

![image](https://user-images.githubusercontent.com/31348972/129244444-b7d7a7d3-22a6-4b7c-afc2-d1ec758a01ba.png)

**Comment by Youssef1313** [comment]
Thanks for your report @peternary. I opened #6742 to fix that.
