### ISSUE TITLE
Support for `LinearGradientBrush` on borders on Android

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#6748]
## What would you like to be added:
Support for LinearGradientBrush on borders on Android
## For which Platform:

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by Youssef1313** [comment]
@MartinZikmund Can you elaborate on what's missing here?

![image](https://user-images.githubusercontent.com/31348972/129622727-5669f910-8e56-47b7-a9fe-659e279bda66.png)

**Comment by MartinZikmund** [comment]
I'm already working on this one, the current implementation does not work with `RenderTransform`
