### ISSUE TITLE
Support for `LinearGradientBrush` on borders on iOS

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#6749]
## What would you like to be added:
Support for LinearGradientBrush on borders on iOS
## For which Platform:

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by Youssef1313** [comment]
Disabled test added in https://github.com/unoplatform/uno/pull/6769 should be enabled when this gets fixed.

**Comment by MartinZikmund** [comment]
Closing in favor of #6457
