### ISSUE TITLE
Support for `LinearGradientBrush` on borders on WASM

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#6751]
## What would you like to be added:

Support for LinearGradientBrush on borders on WASM

## Why is this needed:

WinUI 2.6

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

CSS `attr` and `var` may be useful for this

**Comment by Youssef1313** [comment]
I'm taking a look at this.

**Comment by Youssef1313** [comment]
From https://css-tricks.com/almanac/properties/b/border-image/:

> Unlike some of the other border properties, `border-image` can’t be animated. It also can’t be styled with `border-radius`.

I couldn't find a workaround to support border radius for LinearGradientBrush

**Comment by MartinZikmund** [comment]
Closing in favor of #6457
