### ISSUE TITLE
Inheriting from UIView and implementing DependencyObject fails

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#6758]
## How to reproduce it (as minimally and precisely as possible)

```csharp
#if __IOS__

	partial class MyNativeView : UIKit.UIView, DependencyObject
	{

	}
#endif
```

## Current behavior

Compilation fails with:

> C:\src\djo\tests\UnoTestbed43\UnoTestbed43\UnoTestbed43.iOS\obj\iPhoneSimulator\Debug\g\DependencyObjectGenerator\UnoTestbed43_MyNativeView_1ab76d12354f82d79ece58cba20dd4d2.g.cs(242,10,242,25): error CS0122: 'BinderCollector' is inaccessible due to its protection level

## Expected behavior

Compiles

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
## Note for contributors

We don't want developers from `UIView`-inheriting classes to implement `DependencyObject` through the generators. `UIView` instances need special care with regards to children and dispose management, which are better handled through `FrameworkElement`.

We should modify the `DependencyObject` generator to fail on generation if a `UIView`/`ViewGroup` tries to implement `DependencyObject`, and suggest to use `FrameworkElement` instead.

**Comment by Youssef1313** [comment]
@jeromelaban Does this suggest that the error should be changed to be more clear?

**Comment by jeromelaban** [comment]
> @jeromelaban Does this suggest that the error should be changed to be more clear?

yes, the current error is a type not being accessible, but we need to be more clear about the original error.

**Comment by Youssef1313** [comment]
Thanks. Will work on that.
