### ISSUE TITLE
[Gallery][iOS] Combobox-Material and Cupertino-  when theme change, comboBox is not displaying correctly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6764]
## Current behavior

![combobox issue](https://user-images.githubusercontent.com/74563602/129415754-853134f4-5448-4c3f-8731-405c3f7f0bf7.png)
![combobox material](https://user-images.githubusercontent.com/74563602/133641778-64d42810-0e94-4d22-8728-f5123d793077.png)
![combobox cupertino](https://user-images.githubusercontent.com/74563602/133641793-4f08622e-392a-40b8-b3be-b479f2c32dd8.png)

## Expected behavior
The combobox list should be visible in black color.

## How to reproduce it (as minimally and precisely as possible)

1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Click Burger Menu on the left top right.
3. Click "Combobox" from the "Component" list.
4. Now to go any other option from the "Component " list.
5. Now change theme from day to Night mode.
6. Again go to "Combobox" " Cupertino option.
7. Click on the Comobox option.
8. Observe that the combobox list is not visible.

Nuget Package Version(s):

Affected platform(s):

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by sakshi173** [comment]
@davidjohnoliver, Theme issue is happening for WASM as well but  not similar as above one.
Below are the screenshot for the WASM issue.
![combobox material](https://user-images.githubusercontent.com/74563602/130113096-247f8d3e-86eb-4fa7-8b9a-2d749308e2c8.png)
![combobox cupertino](https://user-images.githubusercontent.com/74563602/130113113-4b65d800-2ee3-4ded-b837-03b658816a02.png)

**Comment by sakshi173** [comment]
@davidjohnoliver and similar type of issue is happening for Datepicker - Cupertino as well, below is the screenshot.
![datepicker cupertino](https://user-images.githubusercontent.com/74563602/130114066-e9c85dc3-8c35-4541-b210-b997ef690440.png)

**Comment by Xiaoy312** [comment]
should be fixed by one of the two prs referenced in:
https://github.com/unoplatform/private/issues/239
