### ISSUE TITLE
[Wasm] MessageDialog does not show the Title or support Command customization

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#678]
## I'm submitting a...
- Bug report

## Current behavior

- A MessageDialog created with a title does not appear in the browser.
- A MessageDialog with more than one command does not appear in the browser.
- A MessageDialog with a customized command label does not appear the browser. 

## Expected behavior

- The title should appear.
- More than one command should be possible.
- The label of a command should be customizable.

## Minimal reproduction of the problem with instructions

See https://github.com/nventive/Uno/blob/aaa4238952fca2a23e5b3f95ea22c5d933133e0e/src/Uno.UWP/UI/Popups/MessageDialog.wasm.cs#L19 and https://docs.microsoft.com/en-us/uwp/api/windows.ui.popups.messagedialog

## Environment

```
Nuget Package: 1.43.1

Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by ghuntley** [comment]
As per https://developer.mozilla.org/en-US/docs/Web/API/Window/alert and 

As per https://docs.microsoft.com/en-us/uwp/api/windows.ui.popups.messagedialog

> `MesssageDialog` is meant to be blocking of user interaction, have an optional title and can support up to 3 commands in desktop apps, or 2 commands in mobile apps. If no commands are specified, then a default command is added to close the dialog.

The current WASM implementation is a `window.alert` which does not allow for custom commands or a title thus I'm increasing the scope of this issue past title, to include custom commands.

Resolving this will mean either implementing `ContentDialog` first and making the experience similar to UWP or pushing this responsibility to shell or browser that's executing WASI.

**Comment by jeromelaban** [comment]
This feature can now be implemented using `ContentDialog`.

**Comment by MartinZikmund** [comment]
As `MessageDialog` use is discouraged by Microsoft (see https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Popups.MessageDialog?view=winrt-20348), and `ContentDialog` is now fully supported, closing this issue.
