### ISSUE TITLE
Globalization not working

### ISSUE THREAD

**Issue by Mohsens22** [unoplatform/uno#6781]
## Current behavior

When using `Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride = "fa";`  in Uno Platform's application code, the UWP head works fine, but others won't even work. 
Also intelisense gives a warning:

![Screenshot 2021-08-16 180733](https://user-images.githubusercontent.com/22152065/129572615-c9bbc8a4-f4d9-472f-abb9-a135c5a1df29.jpg)

## Expected behavior

I expect the app to change language and start using the provided resource file.

## How to reproduce it (as minimally and precisely as possible)

https://github.com/Mohsens22/Uno.Samples

## Works on UWP/WinUI
Yes

## Environment

- Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

Nuget Package Version(s):

Affected platform(s):

- Android
- WebAssembly
- Skia
  -  WPF

IDE:

- [ ] Visual Studio 2019 (Latest)

## Anything else we need to know?

The sample associated with Globalization doesn't work at all.

**Comment by carldebilly** [comment]
I just cloned you solution and tested it on both Visual Studio 2019 16.11 Preview2 and Visual Studio 2022 Preview 1 and on both I'm not getting any Uno0001 errors and the applications changes dynamically at runtime for all 3 configured languages (exception the unsupported RTL, obviously).

![Bug 6781](https://user-images.githubusercontent.com/4174207/129620205-fd3f1cd1-d31c-4da1-bf0d-603bce1f860b.gif)

**Comment by Mohsens22** [comment]
![image](https://user-images.githubusercontent.com/22152065/129698580-897b4fba-4336-4357-9842-ca70da636f10.png)
That's highly unusual because I get blank screen while testing in two different machines!

**Comment by jeromelaban** [comment]
@Mohsens22 the last screenshot looks like a theming issue. Can you force `RequestedTheme="Light"` in your `App.xaml` ?

For the PrimaryLanguageOverride, the warning is likely to be wrong (the NotImplemented attribute may need to be removed), but for the language resolution, #6469 may be related.
