### ISSUE TITLE
[SKIA] RTL Language support on WPF SKIA (Persian, Arabic etc.)

### ISSUE THREAD

**Issue by Mohsens22** [unoplatform/uno#6783]
## Current behavior and Expected behavior

In UWP when we type something in an RTL language, it shows as expected, with correct typing and flow direction and everything. But in SKIA head it does not render the text as expected. It doesn't follow the correct flow direction and it renders characters discreetly and not in a correct form. Please investigate the issue and fix it.

![Screenshot 2021-08-16 183830](https://user-images.githubusercontent.com/22152065/129576963-5f70111f-e684-4168-bf38-c8392ec1501b.jpg)

Right: The correct form in UWP
Left: The wrecked output by SKIA

## How to reproduce it 

```xaml
 <StackPanel Background="{ThemeResource ApplicationPageBackgroundThemeBrush}" FlowDirection="RightToLeft">
		<TextBlock Text="سلام به همه!" Margin="20" FontSize="30" />
        <TextBlock Margin="20" TextWrapping="Wrap" >
            زبان پارسی یک زبان چپ به راست است اما همه آن را با عربی اشتباه می گیرند!
        </TextBlock>
    </StackPanel>
```

## Works on UWP/WinUI
Yes

## Environment

- Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

Nuget Package Version(s):

Affected platform(s):

  -  WPF

IDE:

- [ ] Visual Studio 2019 (Latest)

**Comment by Youssef1313** [comment]
I'm looking into this.

**Comment by mhmd-azeez** [comment]
This issue is blocker for me as well

**Comment by Youssef1313** [comment]
@jeromelaban Can we get the PR merged soon?

**Comment by Arshia001** [comment]
I don't know Skia or the HarfBuzz library, let alone how those two interact. One thing I do know is that there's probably more to supporting bidi than what's in #6785.

Consider these scenarios (there are probably a dozen more, which I can't think of now):

* English text with embedded Persian. Entire text must be LTR, with RTL segments in the middle: 
![image](https://user-images.githubusercontent.com/7010872/152671170-ac94ca0e-25de-476e-925a-aea1a02488a2.png)
And this is how it looks when you get it wrong:
![image](https://user-images.githubusercontent.com/7010872/152671148-5f1792bc-ca0d-4357-960f-bed606894ad8.png)

* Persian text with embedded English. Entire text must be RTL (even in an LTR layout), with LTR segments in the middle:
![image](https://user-images.githubusercontent.com/7010872/152671120-450cfc13-a473-4981-b707-ac24a8712cb6.png)
Again, this is how it looks when you get it wrong:
![image](https://user-images.githubusercontent.com/7010872/152671159-ff75eaf2-151b-4e2b-88f0-af008c4f1cb7.png)

* The engine should ideally detect if a piece of text is RTL. Most of today's software decide by checking if the first character is from an RTL language such as Persian or Arabic. Android does this across its entire UI and it works well enough most of the time. There are also special Unicode characters for marking the start and end of RTL or LTR text. This is probably already handled correctly in HarfBuzz, but could be mistakenly overridden by any code that supports this scenario.

* When you have RTL text in an LTR layout and vice-versa, word order must be maintained correctly. Here's a screenshot of Avalonia getting this wrong: 
![image](https://user-images.githubusercontent.com/7010872/152670832-ad22be49-3a77-47e5-a1d7-5d4d6d02d67c.png)

**Comment by aliajboy** [comment]
It is not FIXED yet. any updates?

**Comment by Youssef1313** [comment]
@aliajboy Are you referring to TextBlock or TextBox?
In what way is it broken in your cases? (e.g., text rendering as squares? text isn't shaped? etc)

If you could add some code and images, it will be helpful to investigate further.

**Comment by jeromelaban** [comment]
@aliajboy It's best to start in a discussion with details, then we'll open issues as needed. Thanks!

**Comment by aliajboy** [comment]
I'll put it here. if you want to, you can open an issue. thanks
I'm referring everything such as textbox, textblock and button:

![Screenshot from 2024-05-04 16-19-42](https://github.com/unoplatform/uno/assets/73298440/ee35f2b8-0cf3-466f-baa2-f6746f2946f6)
