### ISSUE TITLE
CS1061 'MainPage' does not contain a definition for 'InitializeComponent' (like closed issue #4867)

### ISSUE THREAD

**Issue by MarkBrainfire** [unoplatform/uno#6797]
After setting up the minimal "Hello, world" project from the "dotnet new unoapp-winui" CLI template (which was then reduced to only WinUI, Wasm, and Droid), the MainPage.xaml.cs file flags error CS1061 (repeated as 4 identical errors for the same line?) which says: 

_'MainPage' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)_

When you hover over the red squiggle on the 'InitializeComponent' call, you get a message suggesting that this is only an issue with the Android platform:
Project.Droid - Not Available
Project.Wasm - Available
Project.Windows.Desktop - Available

All 3 platforms are generated and run (displaying the "Hello, world!" text).

Is there a way to remove this error?

Visual Studio Preview 2022 3.1
Project Reunion 0.8.1
Uno.Core 2.4.0
.Net5.0
Windows 10 Build 19042.1165

**Comment by jeromelaban** [comment]
Thanks for the report. You can find some documentation here about this issue: https://platform.uno/docs/articles/get-started-wizard.html
