### ISSUE TITLE
[Calculator][Wasm][Chrome]Calculator is displaying overlapped when changing calculator option from one to other, for example from Scientific to Standard option or vice versa.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6801]
## Current behavior
![calculator issue new](https://user-images.githubusercontent.com/74563602/129951565-2220086e-7971-4112-a512-a07ce818734d.png)

## Expected behavior
The calculator should display correctly for all the options.

## How to reproduce it (as minimally and precisely as possible)

1. Visit https://calculatorcanary.z27.web.core.windows.net/
2. Open the burger menu and change the calculator from standard to Programmer option.
3. Now again open the burger menu and change the calculator option from programmer option to Standard option.
4. Observe that calculator is displaying overlapped with programmer option.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Canary version:-
1.2.4-canaries-dev.42

**Comment by jeromelaban** [comment]
Related to https://github.com/unoplatform/uno/issues/6846

**Comment by jeromelaban** [comment]
Fixed

**Comment by sakshi173** [comment]
This issue is resolved, closing it.

**Comment by sakshi173** [comment]
This issue is resolved, closed it.
