### ISSUE TITLE
[Calculator][Wasm][Chrome]Clicking on any key is not responding for any calculator option.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6802]
## Current behavior

https://user-images.githubusercontent.com/74563602/129953580-3b5a0a00-9709-463c-b97e-49758579d324.mp4

## Expected behavior
The key should be pressed and the pressed Numeric key should be display on the top.

## How to reproduce it (as minimally and precisely as possible)
Visit https://calculatorcanary.z27.web.core.windows.net/
Click on any Numeric key or calculation key for the Standard Calculator.
Observe that the key is not pressing and nothing is happening.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Canary version:-
1.2.4-canaries-dev.42

**Comment by jeromelaban** [comment]
Looks like this could be related to some .NET runtime updates, will investigate.

**Comment by jeromelaban** [comment]
Fixed

**Comment by sakshi173** [comment]
Verified, Issue is fixed, Closing
