### ISSUE TITLE
[Gallery][Android] WebView- Application crashes when inside the Webview, click Burger menu and choose the 'Gallery' option to open.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6814]
## Current behavior

https://user-images.githubusercontent.com/74563602/130145843-96ea378b-244e-4ae5-a366-2ae216c636cd.mp4

## Expected behavior
The application should not crash and the Gallery app should open in the Webview.

## How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right .
3. Click on “WebView” from the "Features" list..
4. Click on 'Accept' button for Cookie settings option.
5. Click on the Burger menu inside the Webview.
6. Choose the Gallery option.
7. Observe that the application crashes while opening Gallery app in Webview.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
This is a good one ;) The issue actually comes from the fact that the link inside the browser is a WebAssembly app likely seems to not be supported. This is not a crash we can avoid unfortunately, as it is coming from the the platform itself.

Maybe Android 12 will help there, but until then, there's not much we can do about it.

**Comment by sakshi173** [comment]
As per Jerome comment, there is not much to do, due to that closing this bug.
