### ISSUE TITLE
How to consume ODataV4 web Api

### ISSUE THREAD

**Issue by e066377** [unoplatform/uno#6824]
## What would you like clarification on:
Hello,
I want to use Microsoft.OData.Client for UWP and WASM platforms to generate models from ODatV4 web Api with INotifyPropertyChanged interface implemented. It works without problem for UWP platfrom but for WASM it is not very clear how to introduce httpclient to the container. Setting 
 Default.Container HttpRequestTransportMode = HttpRequestTransportMode.HttpClient is not enough;

For LOB applications ODatav4 web Api is more powerful than ordinary web Api, so it will be very helpful if you can add an how-to tutorial for ODatav4 web Api usage.

## Concern?
- [X] Usage in industry
- [x] Clarification of capabilities
- [X] Getting started with Uno
- [X] Developing with Uno

## For which Platform:
- [X] WebAssembly
- [X] Windows

**Comment by jeromelaban** [comment]
Thanks for the report. 

The best way for us to help you there is to create a sample app with the Uno template, and make it work for UWP. From that point, we'll look at the working solution and try to apply it to Wasm.
