### ISSUE TITLE
[Skia.Wpf] .NET Framework 4.7.2+ issues

### ISSUE THREAD

**Issue by mmarinchenko** [unoplatform/uno#6842]
This issue continues discussion started at https://github.com/unoplatform/uno/issues/4319#issuecomment-900277156

## How to reproduce it (as minimally and precisely as possible)

1. Create new project in PowerShell:
```PowerShell
dotnet new -i Uno.ProjectTemplates.Dotnet

dotnet new unoapp -o=UnoWpfTest -w=UnoWpfTest -wasm=false -ios=false -android=false -macos=false -skia-gtk=false -st=false -skia-linux-fb=false

cd .\UnoWpfTest\
rm .\.vsconfig
rm .\global.json
```

2. Open solution in Visual Studio and agree to convert UWP head to Windows 10 2004 SDK (10.0.19041.0).

3. Remove `Program.cs` from `Skia.Wpf` container project (contains empty `Skia.Gtk` namespace).

4. Set `Skia.Wpf.Host` as Startup Project.

6. Change `Grid` to `GridView` and add `TextBox` to `MainPage.xaml` inside Shared project just below "Hello, world!" `TextBlock` (`TextBlock` has 2-tabs indent while other lines have spaces):
```XAML
    <GridView Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
		<TextBlock Text="Hello, world!" Margin="20" FontSize="30" />
        <TextBox PlaceholderText="Try to enter something" />
    </GridView>
```
7. Build `Skia.Wpf.Host` project, launch it and test `TextBox` input. Input should work. Close window.

8. Open `Skia.Wpf.Host` project file, change `TargetFramework` value from `netcoreapp3.1` to `net472`.

7. Rebuild `Skia.Wpf.Host` project, launch it and give `TextBox` another try. This time input shouldn't work.

![image](https://user-images.githubusercontent.com/21952330/130501998-98c8ea29-1ca9-4cff-b7b6-0176226c90a1.png)

[UnoWpfTest.zip](https://github.com/unoplatform/uno/files/7034273/UnoWpfTest.zip)

My suggestion is:
- to change WPF head target to `net472` as minimum .NET Standard 2.0 compliant framework according to [docs](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support) (in case the reason for WPF head to exist is native Windows 7 support)
\- or -
- to align WPF container library target with WPF head to avoid confusion related to .NET Standard 2.0 and clearly state that only modern .NET is supported even on Windows 7.

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [x] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

```XML
    <PackageReference Include="Uno.UI.Skia.Wpf" Version="3.9.7" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="3.9.7" Condition="'$(Configuration)'=='Debug'" />
```

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [x] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [x] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.11.1)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by trungnt2910** [comment]
Hmm, ran into this issue too, at least on 3.10.7. It seems that there have been some WPF template issues with the `WpfHost`, as the [`NativeOverlayLayer`](https://github.com/unoplatform/uno/blob/215593e449f15cb9a1a8a4126a42763d5911ddd4/src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs#L76), the layer that hosts `TextBox`es, is alwasy `null` on .NET Framework 4.7.2, while it is set to a valid value on .NET Core.

Anyway, it's really sad that the maintainers don't test on .NET Framework first. .NET Core and .NET 5+ is currently useless when one wants to build compact standalone WPF applications.

**Comment by trungnt2910** [comment]
Hmm, ran into this issue too, at least on 3.10.7. It seems that there have been some WPF template issues with the `WpfHost`, as the [`NativeOverlayLayer`](https://github.com/unoplatform/uno/blob/215593e449f15cb9a1a8a4126a42763d5911ddd4/src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs#L76), the layer that hosts `TextBox`es, is alwasy `null` on .NET Framework 4.7.2, while it is set to a valid value on .NET Core.

Anyway, it's really sad that the maintainers don't test on .NET Framework first. .NET Core and .NET 5+ is currently useless when one wants to build compact standalone WPF applications.

**Comment by trungnt2910** [comment]
Seems like the template is never applied!

I've tried:
```C#
    class HackedWpfHost : WpfHost
    {
        public HackedWpfHost(Dispatcher dispatcher, Func<Application> appBuilder, string[] args = null) : base(dispatcher, appBuilder, args)
        {
        }

        public override void OnApplyTemplate()
        {
            base.OnApplyTemplate();

            throw new NotImplementedException();
        }
    }
```

It causes an exception on .NET core, but not .NET Framework. 

This is bad, because the `NativeOverlayLayer` is determined [here](https://github.com/unoplatform/uno/blob/215593e449f15cb9a1a8a4126a42763d5911ddd4/src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs#L149-L154).

**Comment by trungnt2910** [comment]
I seemed to have found the issue.
When decompiling the .NET Core version, we can find:
![image](https://user-images.githubusercontent.com/57174311/133961507-341ee2b1-2ea2-4c64-bb13-bd2e96efc9d0.png)

We can find some `baml` files that contain the style required for the WpfHost to work.

However, for the .NET Framework version:
![image](https://user-images.githubusercontent.com/57174311/133961554-2a522537-5701-4492-b548-8b0b60c7023f.png)

The decompiler shows nothing!

**Comment by trungnt2910** [comment]
https://github.com/unoplatform/uno/blob/215593e449f15cb9a1a8a4126a42763d5911ddd4/src/Uno.UI.Runtime.Skia.Wpf/Uno.UI.Runtime.Skia.Wpf.csproj#L22

Is this the problem?

When you're not using WPF, `xaml` files simply get ignored....

**Comment by trungnt2910** [comment]
As a workaround, put these `xaml` lines to the WPF target (adapted from the code from the [Uno Platform](https://github.com/unoplatform/uno/blob/master/src/Uno.UI.Runtime.Skia.Wpf/Themes/Generic.xaml)).
```xaml
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:platform="clr-namespace:Uno.UI.Skia.Platform;assembly=Uno.UI.Runtime.Skia.Wpf"
    xmlns:controls="clr-namespace:Uno.UI.Runtime.Skia.WPF.Controls;assembly=Uno.UI.Runtime.Skia.Wpf">

    <Style TargetType="{x:Type platform:WpfHost}">
        <Setter Property="Template">
            <Setter.Value>
				<ControlTemplate TargetType="{x:Type platform:WpfHost}">
                    <Border Background="{TemplateBinding Background}"
                            BorderBrush="{TemplateBinding BorderBrush}"
                            BorderThickness="{TemplateBinding BorderThickness}">
						<Canvas x:Name="NativeOverlayLayer" />
                    </Border>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>

	<Style TargetType="{x:Type controls:WpfTextViewTextBox}">
		<Setter Property="SnapsToDevicePixels" Value="True" />
		<Setter Property="KeyboardNavigation.TabNavigation" Value="None" />
		<Setter Property="FocusVisualStyle" Value="{x:Null}" />
		<Setter Property="MinWidth" Value="0" />
		<Setter Property="MinHeight" Value="0" />
		<Setter Property="AllowDrop" Value="true" />
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="{x:Type controls:WpfTextViewTextBox}">
					<Border Name="Border" CornerRadius="0" Margin="{TemplateBinding Margin}" Padding="{TemplateBinding Padding}" BorderThickness="0">
						<Border.Background>
							<SolidColorBrush Color="Transparent" />
						</Border.Background>
						<Border.BorderBrush>
							<SolidColorBrush Color="Transparent" />
						</Border.BorderBrush>
						<VisualStateManager.VisualStateGroups>
							<VisualStateGroup x:Name="CommonStates">
								<VisualState x:Name="Normal" />
								<VisualState x:Name="Disabled" />
								<VisualState x:Name="ReadOnly" />
								<VisualState x:Name="MouseOver" />
							</VisualStateGroup>
						</VisualStateManager.VisualStateGroups>
						<ScrollViewer Margin="0" x:Name="PART_ContentHost" />
					</Border>
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</Style>
</ResourceDictionary>
```
