### ISSUE TITLE
[Perf] GetImplementedRoutedEvents should use a generated implementation

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#6879]
### Current behavior

The following method should be generated for types in Uno:

https://github.com/unoplatform/uno/blob/b7f19b08fd276155868e9a95c29714af80402945/src/Uno.UI/UI/Xaml/Controls/Control/Control.cs#L995

Types outside of Uno will likely still need to use reflection for types defined outside of Uno

**Comment by Youssef1313** [comment]
Does this issue suggests writing a source generator where the generated code will look something like the following?

```csharp
if (type == typeof(...))
{
    result = RoutedEventFlag.... | RoutedEventFlag.... | RoutedEventFlag....;
}
else if (type == typeof(...))
{
    result = RoutedEventFlag.... | RoutedEventFlag.... | RoutedEventFlag....;
}
.
.
.
.
else
{
    // fall back to reflection
}

```

**Comment by carldebilly** [comment]
@Youssef1313 I think it could be an overridable virtual property returning a nullable value that would be called first and run existing reflection code only when not overriden for a specific class.

That way the generator usage won't be required, but using it will increase performance.

**Comment by jeromelaban** [comment]
I was mentioning this to avoid having to provide a public API specific to this behavior, but we can try to find a proper API.
