### ISSUE TITLE
`FilePickerSelectedFilesArray.Count` shouldn't have a throwing setter

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#6885]
### Current behavior

FilePickerSelectedFilesArray.Count has a setter that always throws

### Expected behavior

It shouldn't have a setter to align with UWP.

### Works on UWP/WinUI

Yes

**Comment by jeromelaban** [comment]
This is generally the kind of breaking change that is acceptable, because the current behavior cannot work so apps are not using it, and uwp does not provide it.

**Comment by mcNets** [comment]
Hi @Youssef1313, does that solve the issue?
