### ISSUE TITLE
UWPSyncGenerator should generate private constructor when appropriate

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#6895]
### Current behavior

If the type doesn't have a public constructor, UWPSyncGenerator doesn't generate a private constructor, causing API to diverge from UWP if the developer wasn't careful enough and added the private ctor in the non-generated partial.

### Expected behavior

UWPSyncGenerator should take care of that and generate private (or internal) constructor when there is no public constructor.

**Comment by Youssef1313** [comment]
@ebariche Can you please let me know when you're done with updating the sync generator?

**Comment by Youssef1313** [comment]
Ping @ebariche. Are you working on this? If not, I can jump on it as well as other UWPSyncGenerator issues that are going to be breaking changes.

**Comment by jeromelaban** [comment]
@Youssef1313 it'll be done by elie part of similar work.

**Comment by jeromelaban** [comment]
We can do this for an Uno 5 release, yes.
