### ISSUE TITLE
[Android]: `MenuFlyoutSubItem` is not light-dismissible

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#6929]
### Current behavior

Dismissing `MenuFlyoutSubItem` by clicking outside of its bounds in Android doesn't work.

### Expected behavior

It should be dismissible.

### How to reproduce it (as minimally and precisely as possible)

Same code from https://github.com/unoplatform/uno/issues/6928 will reproduce this issue on Android.

NOTE: This reproduces ONLY for the nested `MenuFlyoutSubItem`s, not for the root one.

### Works on UWP/WinUI

Yes

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/blob/d97a9b606a201857bd514fdacd1bc95fb70604a7/src/Uno.UI/UI/Xaml/UIElement.Pointers.Android.cs#L57

This doesn't get called for the buggy case. @jeromelaban @davidjohnoliver  Any idea where to look next?

**Comment by jeromelaban** [comment]
@dr1rrb may know.

**Comment by robloo** [comment]
This is a duplicate of https://github.com/unoplatform/uno/issues/4795. Should we continue the discussion in the original issue?

**Comment by Youssef1313** [comment]
Yes it's indeed a duplicate. I'm going to close and comment on the other issue with a small pointer I found.

**Comment by dr1rrb** [comment]
> 
> 
> https://github.com/unoplatform/uno/blob/d97a9b606a201857bd514fdacd1bc95fb70604a7/src/Uno.UI/UI/Xaml/UIElement.Pointers.Android.cs#L57
> 
> This doesn't get called for the buggy case. @jeromelaban @davidjohnoliver Any idea where to look next?

This is usually just because there is another element above which handles the pointer events ... which seems to be the case according to https://github.com/unoplatform/uno/issues/4795#issuecomment-910459152
