### ISSUE TITLE
how fix Microsoft.Toolkit.Uwp.UI.Controls

### ISSUE THREAD

**Issue by AbdalaMask** [unoplatform/uno#6932]
### Current behavior

not work WebAssembly and uses only XAML
https://playground.platform.uno/#4edc3703

### How to reproduce it (as minimally and precisely as possible)

https://playground.platform.uno/#4edc3703

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. WCT controls are not available in the playground yet.

**Comment by AbdalaMask** [comment]
fix uno.Microsoft.Toolkit.Uwp.UI.Controls

**Comment by AbdalaMask** [comment]
how add icon to TreeView

**Comment by jeromelaban** [comment]
Fixed in latest dev builds of Uno Playground.
