### ISSUE TITLE
[NPE]- License- View License Terms is displaying two times for xunit.core and for all AWSSDK packages.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6945]
### Current behavior

![license issue](https://user-images.githubusercontent.com/74563602/131902860-3cbb57c8-8012-48f7-8d15-b8179e81beb4.png)

### Expected behavior

![license correct](https://user-images.githubusercontent.com/74563602/131902868-cdf98f3a-28ed-465e-b9e6-6cdfd090000e.png)

### How to reproduce it (as minimally and precisely as possible)

Open NPE https://purple-pond-0688d230f.azurestaticapps.net/
Search AWSSDK.core
Open AWSSDK.core package
Go to License section.
Click on the uper arrow button.
Observe that 'View License Terms' is displaying two times.

### NuGet package version(s)

https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=32807&view=results

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
This looks like an upstream issue as https://ci.nuget.info/packages/AWSSDK.Core/3.7.3 also shows this.

Will open an issue in the original repo :)
