### ISSUE TITLE
Uno with Wpf Chinese code display messy code

### ISSUE THREAD

**Issue by ywmoyue** [unoplatform/uno#6973]
### Current behavior

`    
    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
		<TextBlock Text="你好，世界!" Margin="20" FontSize="30" />
    </Grid>
`

### Expected behavior

![image](https://user-images.githubusercontent.com/28388300/132160518-5bfb121c-7ce7-4b30-92c2-d243a778c735.png)

### Environment

Uno.UI / Uno.UI.Skia, Uno.UI.RemoteControl / Uno.WinUI.RemoteControl

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2019

### IDE version

Microsoft Visual Studio Community 2019 16.11.2 Preview 1.0

### Anything else we need to know?

I can set fontfamily for textblock and textbox controls to solve this problem, but setting fontfamily in contentdialog is invalid.
![image](https://user-images.githubusercontent.com/28388300/132161006-a9f7c6c6-69d8-4786-9fe7-2b24a3d353d4.png)
![image](https://user-images.githubusercontent.com/28388300/132161396-b4ece76d-f8ed-42a6-a708-ffa036f092ff.png)

**Comment by Youssef1313** [comment]
Affects Gtk as well.

**Comment by Jaiganeshkumaran** [comment]
@ywmoyue For ContentDialog, you can customise the TitleTemplate to change the used font.

**Comment by ywmoyue** [comment]
> @ywmoyue对于 ContentDialog，您可以自定义 TitleTemplate 以更改使用的字体。

Thanks, I can use this method to solve the problem

**Comment by jeromelaban** [comment]
@lindexi once there's a working build for the SkiaSharp PR, we'll be able to validate if that helps.

**Comment by lindexi** [comment]
@jeromelaban Thank you and My PR is merged. Could you help me confirm this bug is fixed?

**Comment by lindexi** [comment]
@jeromelaban Can I replace the output file ?

**Comment by lindexi** [comment]
Looks like this has not been fixed in SkiaSharp 2.88.3 version

**Comment by lindexi** [comment]
But I test the demo without UNO and I find the demo code work well. Demo code: https://github.com/lindexi/lindexi_gd/tree/0dc53049b7b74e57472408db161d2c066755bace/SkiaSharp/BihuwelcairkiDelalurnere

It seems that UNO still has bugs.

**Comment by jeromelaban** [comment]
Uno is not using `SKTextBlob` to render text, but rather HarfBuzz. How does an Uno app render text with your sample now?

**Comment by lindexi** [comment]
@Jaiganeshkumaran Thank you and I just replace the output file.

**Comment by jeromelaban** [comment]
Thank you. Can you show a screenshot of the result?

**Comment by lindexi** [comment]
Yes, and I update it.

**Comment by jeromelaban** [comment]
Thanks. I see that your app is using an older version of Uno, and it not updated to [the latest version of SkiaSharp](https://platform.uno/docs/articles/features/using-skia-gtk.html?q=skiasharp#upgrading-to-a-later-version-of-skiasharp). Can you do this and post a screenshot again?

**Comment by lindexi** [comment]
@jeromelaban Yes, thank you. I'm worried that my testing method is wrong. Because my test method just replaces SkiaSharp.dll file

**Comment by lindexi** [comment]
@jeromelaban The bug still exists after I updated to 4.5.14 version

![](https://user-images.githubusercontent.com/16054566/198020206-8b4cf1fa-ec9d-4c09-9192-29181bd05ec7.png)

![](https://user-images.githubusercontent.com/16054566/198020338-7a87e4d0-897d-4575-92a9-925bcdf0f45a.png)

My demo code: https://github.com/lindexi/lindexi_gd/tree/4b484190536c301f94ee574f36925155b4a9773c/TestUnoIslands

**Comment by jeromelaban** [comment]
Make sure to [update SkiaSharp](https://platform.uno/docs/articles/features/using-skia-gtk.html?q=skiasharp#upgrading-to-a-later-version-of-skiasharp).

**Comment by lindexi** [comment]
@jeromelaban  Can I add `<PackageReference Include="SkiaSharp" Version="2.88.3" />` to update the SkiaSharp?

![](https://user-images.githubusercontent.com/16054566/198021309-17795ece-b617-4ef3-a6bf-b9660c30e262.png)

**Comment by lindexi** [comment]
![](https://user-images.githubusercontent.com/16054566/198021560-61b19baf-1755-466f-96c6-824ff7e98e8a.png)

**Comment by jeromelaban** [comment]
Great thanks for the update!

**Comment by Youssef1313** [comment]
This works in Windows without changing the FontFamily. So if this is a requirement currently, then there is still a bug here.

**Comment by lindexi** [comment]
![](https://user-images.githubusercontent.com/16054566/198024676-e0c3608b-f088-4770-b204-b563f19dd407.png)

It display messy code without set the Chinese FontFamily.

**Comment by Youssef1313** [comment]
@lindexi But it works on UWP/WinUI right? Then I think this is still a bug @jeromelaban .

**Comment by lindexi** [comment]
@Youssef1313 It works well in UWP and WPF without set the FontFamily

**Comment by jeromelaban** [comment]
@lindexi whn you say WPF, do you mean an actual WPF app, not a Uno+WPF app? Either way, Skia is using the default system font at this point, and we'll probably fix this by switching to open-sans by default.

**Comment by lindexi** [comment]
@jeromelaban I mean the raw WPF application without uno.

**Comment by lindexi** [comment]
And I think we can set the global font by style. So it doesn't need to be repaired.
