### ISSUE TITLE
Visual Studio for Mac - put Uno Platform project templates under multi-platform

### ISSUE THREAD

**Issue by JaiganeshKumaran** [unoplatform/uno#6974]
## What would you like to be added:
Today the project templates are inside the custom section in Visual Studio for Mac. Instead it would be better if it was under multi-platform where Xamarin.Forms project templates are located.

## Why is this needed:
Better discoverability for users.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [x] Solution Templates

**Comment by MartinZikmund** [comment]
We are not focusing on Visual Studio for Mac support currently, Visual Studio Code is the recommended IDE on the Mac
