### ISSUE TITLE
macOS - Settings navigation view item label missing after adding item to `FooterMenuItems`

### ISSUE THREAD

**Issue by JaiganeshKumaran** [unoplatform/uno#6978]
### Current behavior

After adding a navigation view item to FooterMenuItems in a Microsoft.UI.Xaml.Controls.NavigationView instance, the default label for the built-in settings item is gone and becomes empty.

### Expected behavior

The default label for the settings item should be always there unless the developer customises it.

### Works on UWP/WinUI

Yes

### Affected platforms

macOS

### IDE

Visual Studio for Mac

**Comment by Jaiganeshkumaran** [comment]
> Probably related to #5723 (cc @dr1rrb )

But I'm not using top navigation view, just standard left expanded.

**Comment by jeromelaban** [comment]
Could be related to localization #6094, adjusted because we made recent changes to localization resources resolution.

**Comment by MartinZikmund** [comment]
@Jaiganeshkumaran could still be related, even in this mode we sometimes can encounter problems

**Comment by Jaiganeshkumaran** [comment]
Interestingly this issue only occurs when the system language is set to a regional variant of English other than English (United States) or English (United Kingdom). Not an issue with languages other than English.

**Comment by jeromelaban** [comment]
@Jaiganeshkumaran which version of Uno are you running? If is 3.9, can you try with 3.10-dev.XX experimental builds?

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
