### ISSUE TITLE
Range selection tests are failing

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#6993]
### Current behavior

`Calling_Select_With_NegativeValues`, `Calling_Select_With_In_Range_Values`, `Calling_Select_With_Out_Of_Range_Length` and `Calling_Select_With_Out_Of_Range_Start` are failing in CI.

**Comment by jeromelaban** [comment]
@Youssef1313 Looks like those tests started failing on CI. Could you take a look?

**Comment by Youssef1313** [comment]
Will take a look. Thanks!

**Comment by Youssef1313** [comment]
@jeromelaban The failure seems very expected. The tests are run against .NET Framework 4.6.1, which doesn't have an implementation for `SelectionStart` and `SelectionLength` since the implementation is platform-specific. I think the tests should be written as runtime tests. Do you agree with that?

**Comment by jeromelaban** [comment]
Sure. The curious part is the build passed in PR, so yes let's move those as runtime tests.

**Comment by Youssef1313** [comment]
> The curious part is the build passed in PR

I think there was an issue with tests not running that you fixed? It's very possible it was fixed after the CI on my PR passed.
