### ISSUE TITLE
FontIcon does not Render Glyph that TextBlock Does

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#7003]
### Current behavior

This is a fun one, and was expected to be an easy fix but turned into a complex issue. It started out that a single Glyph was not appearing when it should. It was assumed something was wrong in the binding or viewmodels but everything checked out. A simple switch from FontIcon to TextBlock actually solved the problem - how? FontIcon uses TextBlock internally.

```xaml
    <Grid
        Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <Grid.Resources>
            <FontFamily
                x:Key="AppSymbolFontFamily">ms-appx:///Assets/Fonts/FluentSystemIcons-Regular.ttf#FluentSystemIcons-Regular</FontFamily>
        </Grid.Resources>
        <StackPanel
            Orientation="Horizontal"
            BorderBrush="Pink"
            BorderThickness="2">
            <FontIcon
                Glyph="&#xF4F8;"
                Foreground="Blue"
                FontSize="24"
                FontFamily="{ThemeResource AppSymbolFontFamily}" />
            <TextBlock
                Text="&#xF4F8;"
                Foreground="Green"
                FontSize="24"
                FontFamily="{ThemeResource AppSymbolFontFamily}" />
            <!-- This does not work -->
            <FontIcon
                Glyph="&#xFE26;"
                Foreground="Red"
                FontSize="24"
                FontFamily="{ThemeResource AppSymbolFontFamily}" />
            <!-- Yet this does -->
            <TextBlock
                Text="&#xFE26;"
                Foreground="Black"
                FontSize="24"
                FontFamily="{ThemeResource AppSymbolFontFamily}" />
        </StackPanel>
    </Grid>
```

Produces:

![image](https://user-images.githubusercontent.com/17993847/132618945-d2eb6d3b-9bb0-43ba-89b0-5fe31e44e8a3.png)

### Expected behavior

1. **FontIcon should show the red glyph for `0xFE26` in the FluentSystemIcons-Regular font. Just the same as TextBlock does**
2. There are major layout issue with StackPanel aparent in the repro app. Not all are covered by #3347
   - The StackPanel is sizing to fix the parent. StackPanel should only size to children.
   - The StackPanel is actually rendering two children on top of each other.
   - The StackPanel is not vertically aligning all children the same. Some are top, others are center -- for no aparent reason. Perhaps the font Unicode point is expecting top-to-bottom or left-to-right text ordering for other cultures.

I can break out point 2 into another issue if that seems best. It was all noticed at the same time and it's late so didn't feel like creating two :) It's entirely possible that the layout issues are causing the missing Glyph to appear off the screen as well.

### How to reproduce it (as minimally and precisely as possible)

See above XAML and attached repro:

## Repro App
[FontIconTest.zip](https://github.com/unoplatform/uno/files/7133254/FontIconTest.zip)

### Workaround

A TextBlock can be used for the FontIcon issue. The Layout issues are not easy to fix.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

3.9.1

### Affected platforms

Android

### IDE

Visual Studio 2019

**Comment by Youssef1313** [comment]
So this doesn't work.:

```xml
            <FontIcon
                Glyph="&#xFE26;"
                Foreground="Red"
                FontSize="24"
                FontFamily="{ThemeResource AppSymbolFontFamily}" />
```

But this one does?

```xml
            <FontIcon
                Glyph="&#xF4F8;"
                Foreground="Blue"
                FontSize="24"
                FontFamily="{ThemeResource AppSymbolFontFamily}" />

```

Could it be that this glyph isn't supported by the given font? The reason it may be working with `TextBox` is related to which native controls this is transformed into and whether the native control use a fallback font when the glyph doesn't exist.

This is all just guessing. Will see if I can find some way to confirm.

**Comment by Youssef1313** [comment]
I used this site: https://torinak.com/font/lsfont.html

and dropped the font file there. Both F4Fx and FE2x are there:

![image](https://user-images.githubusercontent.com/31348972/132665492-29d7e9c9-deb4-457f-83a9-2e589fb9157a.png)

![image](https://user-images.githubusercontent.com/31348972/132665609-06f7df13-7106-4c0f-a6a4-78d722e77d4b.png)

So likely my guess isn't correct 😕

**Comment by robloo** [comment]
Yea, the font is good. I am only using two different Glyphs both in a TextBlock and a FontIcon. If the glyph in the font was bad it wouldn't show in the TextBlock either. Android doesnt have any fallback fonts for these Microsoft Symbol Fonts. And finally this all works just fine on UWP as well. So it seems to be something special with this specific Unicode point itself in a FontIcon.

**Comment by robloo** [comment]
Also keep in mind FontIcon is using TextBlock internally so it really doesn't make any sense.

**Comment by Youssef1313** [comment]
@robloo It's probably not related to `FontIcon` vs `TextBlock`.

When I changed the orientation, a `TextBlock` was broken:

![image](https://user-images.githubusercontent.com/31348972/132712348-b2338409-434a-4f59-a525-d41a5e4d1307.png)


It feels like, somehow, the measuring is broken for this glyph but not the other.

**Comment by robloo** [comment]
Hm, interesting. I did have a thought layout might have something to do with this. However, that really doest explain why this glyph doesn't work specifically. Unless measure of the glyph itself is unique in some way that breaks measure/arrange passes later on.

**Comment by Youssef1313** [comment]
I thought that the measurement could have been done after the text/glyph is set but before the font is. But I made sure to set the font family first and the issue remains. So indeed that doesn't explain it. The is really very strange (and interesting 😃 )

**Comment by robloo** [comment]
Actually, we know measure/arrange is broken because of the first screenshot I added showing a TextBlock on top of another TextBlock within the StackPanel. I bet this does have to do with the internals of how text measurement is done for the glyph in question.

**Comment by Youssef1313** [comment]
Here is an interesting scenario in UWP vs Android:

![image](https://user-images.githubusercontent.com/31348972/132714118-e80a4dba-abd7-45dd-b813-ad24d35c3355.png)

![image](https://user-images.githubusercontent.com/31348972/132714265-4c581770-7a3e-4fb5-857e-ca736c67d6f9.png)

**Comment by robloo** [comment]
> Here is an interesting scenario in UWP vs Android:

I think you are actually breaking things here with an unsupported scenario. Even in UWP that doesn't make sense. It appears at first an issue with the Unicode point being interpreted in a way to change the text alignment for the blue FontIcon to RTL. This is likely because FontIcon is designed for ONLY a single Glyph. Specifying two 16-bit hex values in XAML is actually quite strange -- it normally is only done for surrogate pairs (32-bit Unicode points). However, since a surrogate pair doesn't make sense (out of the numerical range) it seems smart enough to compensate. Overall though, I'm not sure how this case is handled at all.

**Comment by robloo** [comment]
@Youssef1313 More information:

I decided to switch from StackPanel to Grid to take that out of the equation. Grid is also using the same WinUI source base so shoulnd't have these types of bugs we are seeing in StackPanel. I also added some backgrounds to each control so we could see what is where they appear even without text.

 1. The Blue FontIcon with 0xF4F8 is centered both vertically and horizontally. This may make sense as it's considered a 'graphic/icon' but I haven't checked the default style.
 2. The Green TextBlock with 0xF4F8 is left and top aligned. This may also make sense as it's considered text instead of an Icon. Again, haven't checked default styles.
 3. **The Red FontIcon with 0xFE26 is NOT shown at all. I even changed the FontSize to ensure it isn't drawn above/below something else. More, how can this be in the last column? It should be in the third colum!?**
 4. **The Black TextBlock with 0xFE26 is now right and top aligned. Indeed, it seems like this is being interpreted as right-to-left text different from other Unicode points. Additionally, this should be in the last column, not column 3.**

![image](https://user-images.githubusercontent.com/17993847/132718212-2ea9c650-5e29-4548-a610-7b4f34e947ac.png)

```xaml
<Grid
            BorderBrush="Pink"
            BorderThickness="2">
            <Grid.ColumnDefinitions>
                <ColumnDefinition />
                <ColumnDefinition />
                <ColumnDefinition />
                <ColumnDefinition />
            </Grid.ColumnDefinitions>
            <FontIcon
                Grid.Column="0"
                Glyph="&#xF4F8;"
                Foreground="Blue"
                Background="LightGray"
                FontSize="24"
                FontFamily="{ThemeResource AppSymbolFontFamily}" />
            <TextBlock
                Grid.Column="1"
                Text="&#xF4F8;"
                Foreground="Green"
                Background="Gray"
                FontSize="24"
                FontFamily="{ThemeResource AppSymbolFontFamily}" />
            <!-- This does not work -->
            <FontIcon
                Grid.Column="2"
                Glyph="&#xFE26;"
                Foreground="Red"
                Background="LightBlue"
                FontSize="32"
                FontFamily="{ThemeResource AppSymbolFontFamily}" />
            <!-- Yet this does -->
            <TextBlock
                Grid.Column="3"
                Text="&#xFE26;"
                Foreground="Black"
                Background="LightGreen"
                FontSize="24"
                FontFamily="{ThemeResource AppSymbolFontFamily}" />
        </Grid>
```

**Comment by Youssef1313** [comment]
@robloo  What I get with your sample code on Android 9 emulator:

![image](https://user-images.githubusercontent.com/31348972/132720082-b69e4654-06a2-4f47-a59a-91186c79b79e.png)

The black one shows in the last column as expected.

But, in Android 11, I'm seeing this what you're seeing:

![image](https://user-images.githubusercontent.com/31348972/132720471-f7326923-819a-498f-92ae-124ab74a5f51.png)

**Comment by robloo** [comment]
Man, this really opens up a lot of strange behavior. I did say this was a fun one, haha

@jeromelaban @dr1rrb @davidjohnoliver @carldebilly I think we are going to need some ideas pointing us in the right direction on this.

**Comment by robloo** [comment]
I had another thought: use absolute positioning for everything within a Canvas. This ensures measure/arrange bugs aren't (or shouldn't) be affecting the glyph rendering -- at least at the control level. 

This almost certainly proves there is an underlying issue measuring the glyph size or positioning itself. For the TextBlock that shows the glyph it is way off it's background. How text measurement is done in Android I'm unsure. I'm not even sure this can be fixed if Android is doing something behind the scenes we have no access to.

![image](https://user-images.githubusercontent.com/17993847/132731780-537ab6f6-bc05-4ed0-a7b7-f2f7291a0341.png)

Note that without setting the height/width to 32x32 for each control things are even more problematic. Backgrounds are missing entirely from the last two controls.

![image](https://user-images.githubusercontent.com/17993847/132731998-69f60ffd-7501-4226-a4d0-6acafa5cfc84.png)


```xaml
<Canvas
            BorderBrush="Pink"
            BorderThickness="2">
            <FontIcon
                Canvas.Top="0"
                Canvas.Left="0"
                Height="32"
                Width="32"
                Glyph="&#xF4F8;"
                Foreground="Blue"
                Background="LightGray"
                FontSize="24"
                FontFamily="{ThemeResource AppSymbolFontFamily}" />
            <TextBlock
                Canvas.Top="0"
                Canvas.Left="50"
                Height="32"
                Width="32"
                Text="&#xF4F8;"
                Foreground="Green"
                Background="Gray"
                FontSize="24"
                FontFamily="{ThemeResource AppSymbolFontFamily}" />
            <!-- This does not work -->
            <FontIcon
                Canvas.Top="0"
                Canvas.Left="100"
                Height="32"
                Width="32"
                Glyph="&#xFE26;"
                Foreground="Red"
                Background="LightBlue"
                FontSize="24"
                FontFamily="{ThemeResource AppSymbolFontFamily}" />
            <!-- Yet this does -->
            <TextBlock
                Canvas.Top="0"
                Canvas.Left="150"
                Height="32"
                Width="32"
                Text="&#xFE26;"
                Foreground="Black"
                Background="LightGreen"
                FontSize="24"
                FontFamily="{ThemeResource AppSymbolFontFamily}" />
        </Canvas>
```

**Comment by robloo** [comment]
My theory:
 1. The issue is entirely due to text measurement within TextBlock
 2. FontIcon is using the measurements from TextBlock and may be throwing out invalid values or just clipping the glyph itself. If the internal TextBlock was measuring correctly, FontIcon would work just fine.

From the following, we see that the glyph is rendered to the left of its background. It is off by approximately the width itself -- like a minus sign is switched. Like a Right-to-left issue.

![image](https://user-images.githubusercontent.com/17993847/132734651-ccca8743-c3e5-437e-99c7-f4cc9dbf4bff.png)

**Comment by davidjohnoliver** [comment]
@robloo @Youssef1313 yep you definitely have a fun one on your hands :D

I have no idea what's going on, but I suspect that looking at the layout bounds of the views in question, either with ShowLocalVisualTree() in the debugger or with the Layout Inspector from Android Studio, would be a useful next step.

**Comment by Youssef1313** [comment]
@davidjohnoliver I'm trying to attach the debugger from Android Studio to the emulator that was run from Visual Studio, but:

![image](https://user-images.githubusercontent.com/31348972/132949433-8eb99bd8-69be-493d-9707-6d6ed84ec5f2.png)

![image](https://user-images.githubusercontent.com/31348972/132949505-6c60fc19-a97b-424e-9c43-218ab5e684e0.png)

The instructions [here](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/debugging-inspect-visual-tree.md) didn't seem much detailed to me. What I did is opened `src/Uno.UI.BindingHelper.Android/Uno` directory in Android Studio, then tried both `Run → Attach to Process...` and `Run → Attach Debugger to Android Process`

Any hints?

**Comment by robloo** [comment]
I was wondering how to do the same. I highly doubt the two toolsets play nicely together. The thought I had was to take the compiled app from the Xamarin tooling and copy the .apk over to Android Studio for debugging. The hope is that would be enough to see the bounds of the underlying android controls -- of course actual debugging won't work. Not sure if or how that works though and I've never had to use Android Studio itself before.

**Comment by Youssef1313** [comment]
Yeah I actually just downloaded and installed Android Studio for this 😄

**Comment by robloo** [comment]
I had a nother thought. This repro is so simple an app could be made in Android Studio itself with a text control, the custom font and the glyph in question. If it doesn't work there we prove the bug is Android itself (differences in your screenshots between Android 9 and 11 are suspicious too). It might also be easier to find a work-around using the normal Google app development toolkit.

**Comment by Youssef1313** [comment]
@robloo Indeed!! Looks like an Android issue:

![image](https://user-images.githubusercontent.com/31348972/132959773-6126ab4d-54c2-4d0f-9a13-d8fc8350fbad.png)

**Comment by robloo** [comment]
Great confirmation! I guess I need to file an issue with Android itself. I'll try to find the correct repository for that.

Separately, I'm going to attempt rebuilding the symbols font within a few days. I'm not sure if the underlying issue is the Unicode point being out of an expected range, or somehow the glyph is formatted in a way Android can't handle. Switching to a new font with a different unicode point for the same glyph should answer that question.

**Comment by robloo** [comment]
I'm fairly certain the issue is caused by the Fluent UI System font using Unicode points it shouldn't be. The private use area only goes from U+E000–U+F8FF (the other two are outside the range we are looking at) and U+FE26 is outside that range. In fact U+FE26 is within the Combining Half Marks Blocks organized as "Continuous macrons for Coptic". Coptic is... a right-to-left language from what I can tell. Android certainly processing the glyph differently from Windows; however, I don't think it's really at fault for this.

https://en.wikipedia.org/wiki/Private_Use_Areas

**Comment by davidjohnoliver** [comment]
@robloo Very interesting findings!

Sounds like we can't do much about this (since we're stuck with the glyph positions that Microsoft chose), but we should document it as a known limitation (here https://github.com/unoplatform/uno/blob/master/doc/articles/uno-fluent-assets.md/#L1).

If you check Segoe UI (eg in FontForge) you might be lucky enough to find that the glyph is duplicated at a different (possibly better) position, that's not atypical.

**Comment by robloo** [comment]
@davidjohnoliver 

I'm using the Fluent UI System font which does not have the same Unicode points, or glyphs, as the Segoe MDL2 Assets or Segoe Fluent that the Uno symbols font is based on. If I was using the other two fonts I don't expect I would see this issue as Segoe MDL2 and Segoe Fluent stay within the private use areas correctly. https://github.com/microsoft/fluentui-system-icons/issues/321

That said, the Fluent UI System font includes many different glyph sizes so your suggested work-around is certainly a good idea. The difference in line widths would be negligible for some variants.

![image](https://user-images.githubusercontent.com/17993847/133453345-f67899eb-5e80-499c-b101-763ef639f210.png)

Additionally, there is an alternate of this symbol but it's a bit harder to recognize and doesn't match Segoe MDL2 / Segoe Fluent as well.

![image](https://user-images.githubusercontent.com/17993847/133453621-4f4e91a0-9c48-49da-ad04-3c0ab7aed28b.png)

> Sounds like we can't do much about this

I'm not so sure quite yet :)

@Youssef1313 Could you check your Android app again by moving the position of the LinearLayout to the center of the screen? Or moving the TextViews to the center (away from the left edge). I want to see if the symbol is rendered, it's just rendering to the left of the visible area in the example you gave.

If it is, there is still a fix needed in Uno. Text measuring should account for the case of a negative width (right-to-left) and shift the text over and measure the bounds correctly. This will all have to be fixed for RTL support anyway.

**Comment by robloo** [comment]
I re-build the Fluent UI System font and tried that as-is. The issue remained proving the Font itself is just fine. This can be closed as soon it's confirmed that Android isn't rendering the glyph off screen to the left. 

Summary of main points:
 1. The work-around used for now is as @davidjohnoliver suggested. A size 24 variant of the glyph exists (instead of size 20) within the private use code page. Switching to size 24 fixed the issue.
 1. Other symbol icons such as Segoe MDL2 or Segoe Fluent won't have this issue as they properly stay within the private use area (microsoft/fluentui-system-icons#321).
 1. It's possible this is 'fixed' automatically in the future when Uno has RTL support. As mentioned above, the issue is likely due to the glyph rendering RTL with negative width. However, as an accent/combining mark, perhaps it requires another character as well -- not really sure how Android handles this or the Unicode spec here.

**Comment by robloo** [comment]
I'm going to close this. It will either never be fixed or will be corrected with RTL and FlowDirection support in the future. Until then this is going to have to be accepted as a limitation -- with many work-arounds.

 * The fundamental problem is Microsoft is using a code point they shouldn't for Fluent UI System icons -- it is outside the private use area. microsoft/fluentui-system-icons#321
 * Android is treating that codepoint as it sees best and we can't control that with the current architecture of Uno on Android
