### ISSUE TITLE
Visual Studio for Mac - XAML item templates

### ISSUE THREAD

**Issue by JaiganeshKumaran** [unoplatform/uno#7006]
## What would you like to be added: Visual Studio for Mac - XAML item templates
Visual Studio for Mac doesn't currently provide UWP XAML item templates but since Uno uses the same, Uno could provide them with the extension.

## Why is this needed: For better development experience
Today to add a new page/user control/resource dictionary/resource file using Visual Studio for Mac, we need to create the files manually and set it to appropriate build action.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [x] Solution Templates

**Comment by MartinZikmund** [comment]
We are not focusing on Visual Studio for Mac support currently, Visual Studio Code is the recommended IDE on the Mac
