### ISSUE TITLE
NativeCtorsGenerator fails for nested classes

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#7014]
### Current behavior

In UWP, the following works:

```csharp
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
            Content = new MyNestedControl();
        }

        public partial class MyNestedControl : Button
        {
            public MyNestedControl()
            {
                Foreground = new SolidColorBrush(Windows.UI.Color.FromArgb(255, 255, 0, 0));
                Content = "Click me!";
            }
        }
    }
```

For Android, it generates invalid code:

```csharp
partial class MainPage.MyNestedControl
```

### Expected behavior

Generated code should be correct:

```csharp
partial class MainPage
{
    partial class MyNestedControl
    {
    }
}
```

### Works on UWP/WinUI

Yes

**Comment by Youssef1313** [comment]
This may be affecting other generators as well. Will need to double check that.
If other generators work correctly, we should extract this common functionality into a helper class.

**Comment by jeromelaban** [comment]
Thanks! Is this a regression ?

**Comment by Youssef1313** [comment]
I don't think it's a regression. The bad logic is there from the very beginning.

https://github.com/unoplatform/uno/blame/5e7bc649f92ac408d721d1a8ba3194fba35c2661/src/SourceGenerators/Uno.UI.SourceGenerators/NativeCtor/NativeCtorsGenerator.cs#L138

**Comment by davidjohnoliver** [comment]
Indeed it's a long-standing limitation that's listed in the docs: https://platform.uno/docs/articles/migrating-guidance.html#avoid-nested-classes-that-inherit-from-frameworkelement

**Comment by Youssef1313** [comment]
@davidjohnoliver I think it can be fairly easy to handle in code generation. What are other generators that needs to be updated? Are there issues with that outside the code generation area?
