### ISSUE TITLE
Changing `TextBox.Text` in code should reset the caret to the beginning

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#7016]
### Current behavior

See https://github.com/unoplatform/uno/pull/6995#issuecomment-916392149 and see modified tests in the PR.

### Expected behavior

Explained above.

### Works on UWP/WinUI

Yes

### Affected platforms

WebAssembly

**Comment by aesteves900** [comment]
After my analyse I believe it's important to put in freeze this task until the PR #[8232](https://github.com/unoplatform/uno/pull/8232) passes. There is a code intersection in the Wasm Platform to solve this issue. Can I put on Freeze this task for a while @francoistanguay?

**Comment by Youssef1313** [comment]
@aesteves900 I don't quite get the intersection you refer to. #8232 implements a separate API and doesn't seem to have any Wasm-specific code. Anything I'm missing?

**Comment by aesteves900** [comment]
@Youssef1313 , it is just to be careful because the PR that mentioned changes the behavior of Wasm to SelectionStart and SelectionLength, I need to make sure to not create a bad side effect in this PR.
