### ISSUE TITLE
[Gallery][Wasm] CalendarView - The XAML code is available through See Xaml link,  instead of the <> sign on the right side.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7023]
### Current behavior

![calendarView](https://user-images.githubusercontent.com/74563602/132955868-11cb6e7e-af92-41ac-ad32-59e7468e5240.png)

### Expected behavior

The Xaml code should display like other controls of Gallery
![calendar correct](https://user-images.githubusercontent.com/74563602/132955924-c44cee4d-36f2-4103-a56f-a600d4dc2d78.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "CalendarView" from the "Component" list.
4. Observe that the XAML code is available through See Xaml link,  instead of the <> sign on the right side.

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
Looks like it's a behavior that was changed intentionally. @kazo0 ?
