### ISSUE TITLE
[Gallery][Wasm] Fluent-PersonPicture - The Gallery Image and corner radius is incorrect.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7024]
### Current behavior

![personpicture](https://user-images.githubusercontent.com/74563602/132956540-8380e9f7-0ccf-4949-8085-a13cdc5863ac.png)

### Expected behavior

The Gallery Image and corner radius should display properly.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "PersonPicture" from the "Component" list.
4. Observe that Gallery Image and Corner radius for circle is  incorrect.

### Affected platforms

WebAssembly

**Comment by kazo0** [comment]
Affected by https://github.com/unoplatform/uno/issues/7061

**Comment by sakshi173** [comment]
Gallery Image issue is fixed but the **corner radius issue is still present.**
Verified for the below version
https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=34191&view=results

![personpicture issue](https://user-images.githubusercontent.com/74563602/135327670-53e3ff3d-fa34-474b-865a-bea49243f449.png)

**Comment by sakshi173** [comment]
Another bug(https://github.com/unoplatform/uno/issues/7508)  is opened for this issue, due to that closing it.
