### ISSUE TITLE
The default uno Android project template cannot be debugged in Visual Studio 2022 preview

### ISSUE THREAD

**Issue by ywmoyue** [unoplatform/uno#7028]
### Current behavior

![image](https://user-images.githubusercontent.com/28388300/132974334-1bf78b87-e803-488d-9d7e-96bd0c341445.png)
![image](https://user-images.githubusercontent.com/28388300/132974363-d3ba5485-2e60-43df-99a8-016462c1a950.png)

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

Microsoft Visual Studio Community 2022 Preview (64-bit) Version 17.0.0 Preview 3.1

**Comment by Youssef1313** [comment]
I think the .NET 6.0 templates aren't yet stable for usage. cc @jeromelaban to confirm

**Comment by jeromelaban** [comment]
Indeed, .NET 6 and visual studio previews are not stable, newer updates will fix this soon.

I'll close this for now as it won't be relevant very soon.

**Comment by limeniye** [comment]
Which version of Visual Studio works correctly with MAUI at this moment?

**Comment by jeromelaban** [comment]
You'd need to ask this on the MAUI repository for the best answer.
