### ISSUE TITLE
[Gallery][Wasm][Android] Material -ProgressRing/Bar - The Progress Ring is missing for 'Determinate ProgressRing' when open the ProgressRing/Bar controls.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7035]
### Current behavior

![pr](https://user-images.githubusercontent.com/74563602/132995725-963b939d-011a-4ae1-ba4f-b0753b930c8c.png)
![pr Wasm](https://user-images.githubusercontent.com/74563602/132995936-aaac53ea-b245-4f78-bb64-558bd3aef6cb.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "Progress Ring/Bar" from the "Component" list.
4. Observe that the Progress Ring is missing for 'Determinate ProgressRing' when open the progressRing/Bar controls and until don't move the slider of 'Determinate ProgressRing'.

### Affected platforms

Android

**Comment by jeromelaban** [comment]
It seems that the following method:

https://github.com/unoplatform/uno/blob/56d3ba98ee6cab055dc8d7c4941ce4494e20e946/src/Uno.UI/Microsoft/UI/Xaml/Controls/ProgressRing/ProgressRing.cs#L277

is not properly called when the progress ring value is being set while the control is not visible.

**Comment by sakshi173** [comment]
The Issue is fixed , Closing.
![progressring issue resolved](https://user-images.githubusercontent.com/74563602/135306431-f01698da-df90-4295-a80a-7189b05b7c72.png)
