### ISSUE TITLE
[Gallery][Android][Material, Fluent, Cupertino] ProgressRing/Bar - For 'Determinate ProgressRing' the Progress Ring is show full ring in the starting of the slider while move slider. 

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7036]
### Current behavior

https://user-images.githubusercontent.com/74563602/132996277-fa21aee1-b5ca-4987-9466-cf38afca3899.mp4

### Expected behavior

The Progress ring  shows according to the slider move situation.

### How to reproduce it (as minimally and precisely as possible)

Open Uno Gallery APP
Click Burger Menu on the left top right.
Click "Progress Ring/Bar" from the "Component" list.
Observe that  For 'Determinate ProgressRing' the Progress Ring is show full ring in the starting of the slider while move slider at the left side.

### Affected platforms

Android

**Comment by sakshi173** [comment]
Still Issue is present , Verified for the below Canary build.
Release 315
Version 1.5.0 (400833)
Sept 28, 2021 10:38 PM

https://user-images.githubusercontent.com/74563602/135316660-0bcee476-9cbd-4d6a-bebb-8a536727542b.mp4

**Comment by sakshi173** [comment]
@carldebilly , Still I am able to repro this bug, Please look into it.

**Comment by sakshi173** [comment]
Not able to reverify this bug as for ProgressBar/ Ring is currently not showing for Android platform.

**Comment by jeromelaban** [comment]
@Robert-Louis could you validate this issue once your PR is merged?

**Comment by agneszitte** [comment]
@sakshi173 can you test this issue with the latest versions please

**Comment by sakshi173** [comment]
This issue is fixed, closing it.
