### ISSUE TITLE
[Gallery][Wasm][Android]Fluent - ProgressRing/Bar - For 'Indeterminate ProgressBar' the Progress Bar is incorrect

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7050]
### Current behavior

https://user-images.githubusercontent.com/74563602/133082787-416e6c41-041b-4ee4-b366-58fa69f66776.mp4

### Expected behavior

The Indeterminate ProgressBar should display properly.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "Progress Ring/Bar" from the "Component" list for Fluent.
4. Observe that For 'Indeterminate ProgressBar' the Progress Bar is incorrect.

### Affected platforms

Android, WebAssembly

**Comment by carldebilly** [comment]
The _v2_ version of Fluent templates seems to be the cause of the problem.  The workaround will be to put back the _v1_ template and wait for https://github.com/unoplatform/uno/issues/3919 to be completed before reactivating the template.

**Comment by sakshi173** [comment]
Verified, Issue is fixed, Closing.
