### ISSUE TITLE
WinUI 2.6 Slider thumb should animate on pointer over

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#7052]
## What would you like to be added:

The Slider control's Thumb should animate when pointer is over/pressed. This currently does not happen in Uno, even though the style contains the appropriate DoubleAnimations.

## Why is this needed:

WinUI 2.6 alignment

## For which Platform:

All

**Comment by Youssef1313** [comment]
Note: the animation duration resources is only defined in FluentTheme

**Comment by MartinZikmund** [comment]
@Youssef1313 That should not be a problem (as the new version of the style is only there too). I rather suspect a general animation-related problem there.
