### ISSUE TITLE
[Gallery][Android] Material- Flyout - The Border is missing for the Text when click on 'Flyout' Button for 'FlyoutPresenter'

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7053]
### Current behavior

![flyout presenter issue](https://user-images.githubusercontent.com/74563602/133099852-fa018889-2611-4f66-a167-e310d10afc1d.png)

### Expected behavior

![flyout presenter correct](https://user-images.githubusercontent.com/74563602/133099878-38cbbb8c-c362-44e5-b29f-d144884ab068.png)

### How to reproduce it (as minimally and precisely as possible)

Open Uno Gallery APP
Click Burger Menu on the left top right.
Click "Flyout" from the "Component" list.
Go to 'Material' section.
Click " Flyout" button.
Observe that the border is missing for the Text.

### Affected platforms

Android

**Comment by jeromelaban** [comment]
@MartinZikmund do you know if this is supposed to happen ?

**Comment by MartinZikmund** [comment]
@jeromelaban my guess it is because the flyout in WinUI has a shadow, so it does not need the border. But will need to check

**Comment by MartinZikmund** [comment]
The border shows up for flyout in blank app, so not sure what's wrong

**Comment by sakshi173** [comment]
@MartinZikmund. Still this issue is reproducible, Please update your comments on this.

**Comment by sakshi173** [comment]
Verified issue is fixed closing.
