### ISSUE TITLE
UnoPlatformPackage.OnOpenedAsync hanging Visual Studio for large amounts of time

### ISSUE THREAD

**Issue by davkean** [unoplatform/uno#7067]
### Current behavior

I'm from the Visual Studio performance team at Microsoft and our telemetry is showing that UnoPlatformPackage.OnOpenedAsync is hanging Visual Studio calling into IVsPackageInstallerServices.GetInstalledPackages on the UI thread. Over the past 90 days, we have the following (sampled) hits:

Root Failure|Leaf Failure|Hits (Expressed)|Total Hits|Duration (75th Percentile)|Delayed Mouse Clicks|Delayed Key Strokes
---|---|---|---|---|---|---
unosolutiontemplate.vsix.2022.dll!UnoSolutionTemplate.UnoPlatformPackage+<OnOpenedAsync>d__.MoveNext|nuget.visualstudio.implementation.dll!NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages|112|951|3.32 sec|71|46

"Expressed" hits represent UI hangs where the user tried to interact with Visual Studio and their input was delayed.

### Expected behavior

There is no async equivalent of this API, however, this API can be safely called off the UI thread where it will switch to the UI thread where needed. Please avoid calling this on the UI thread.

### How to reproduce it (as minimally and precisely as possible)

This is from live Visual Studio telemetry from real world solutions and Visual Studio sessions, there is no repro solution or project.

**Comment by jeromelaban** [comment]
Thanks David for the detailed information!

The fact that the API can be call off the UI thread is particularly important indeed, thanks for mentioning it! We'll make adjustments for this.

**Comment by Youssef1313** [comment]
The API was marked obsolete recently anyway: https://github.com/NuGet/NuGet.Client/pull/4038

**Comment by jeromelaban** [comment]
Fixed in https://github.com/unoplatform/uno/pull/7066
