### ISSUE TITLE
macOS - Cutting text from colour picker's hex box not working

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [unoplatform/uno#7070]
### Current behavior

Today when cutting text (not copy) from the hex box inside a colour picker throws System.NotImplementedException.

### Expected behavior

Cut should work just like Copy.

### Works on UWP/WinUI

Yes

### Environment

Other

### Affected platforms

macOS

### IDE

Visual Studio for Mac

### IDE version

8.10.8

**Comment by jeromelaban** [comment]
Thanks for the report. Can you provide a sample XAML that you are using?
