### ISSUE TITLE
ListView first SelectedItem doesn't unhighlight when new one selected

### ISSUE THREAD

**Issue by NXTwoThou** [unoplatform/uno#7073]
### Current behavior

Go to https://gallery.platform.uno Expand "Features" on the left, click ListView, go down to "SelectedItem".  Click "Uno Blue", "Uno Purple", and "Uno Red".   "Uno Green" stays highlighted when you click the other colors.  

![image](https://user-images.githubusercontent.com/15003605/133272416-b66972a4-81e0-4215-8f17-151d425fdba7.png)

Now click "Uno Green", then "Uno Blue"(or any other of the three), now "Uno Green" will no longer be highlighted.  

![image](https://user-images.githubusercontent.com/15003605/133273093-f01a1392-d3b1-4e9d-b785-b8ff494c3e62.png)

Note, the "Foreground color" line indicates the correct single selected color even when two are highlighted.

### Expected behavior

In a single select ListView, only one should be highlighted.

### Anything else we need to know?

I'm not a Uno user.  I was just randomly browsing to see what Uno could do and found this bug.  Don't know if it's just a bug with the gallery or the base system.  I didn't see any reports so thought I'd take a few seconds to send this one in.

**Comment by jeromelaban** [comment]
Thanks for the report! This is an issue that has already been fixed and it will be available soon once Gallery app is updated.
