### ISSUE TITLE
[Gallery][Wasm/iOS/Android] Fluent - RadioButton and Toggleswitch- when theme switch the Disabled Radiobutton and Disabled ToggleSwitch is not displaying correctly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7096]
### Current behavior

https://user-images.githubusercontent.com/74563602/133508376-fe115a08-fed0-4586-855e-309fcb2fc8a1.mp4

### Expected behavior

The Radiobutton and toggleswitch should change  according to theme change.

### How to reproduce it (as minimally and precisely as possible)

Open Uno Gallery APP
Click Burger Menu on the left top right .
Click "RadioButton" Or "Toggleswitch"  from the "Component" list.
Go to Fluent section for any of the above the choosed option.
Now Change theme from day to Night mode or from Night mode to day Mode.
Observe that when theme switch the Disabled Radiobutton and Disabled ToggleSwitch is not displaying correctly.

### Affected platforms

iOS, Android, WebAssembly

**Comment by Xiaoy312** [comment]
exploded view:
![radiobtn theme issues detailed](https://user-images.githubusercontent.com/2359550/156062954-f0401af8-e6a9-49a9-a4bf-b7df40d525a2.png)
left to right: 
- starting as dark mode, toggle twice
- starting in light mode, toggle twice
