### ISSUE TITLE
[Gallery][Android/iOS] Material - RadioButton and Toggleswitch- when theme switch the  Radiobutton and  ToggleSwitch is not displaying correctly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7097]
### Current behavior

tl;dw: // @starting-with-theme $changing-to-theme
![image](https://user-images.githubusercontent.com/2359550/151195972-8e119144-e80e-4e9f-9857-c2789c3e251a.png)

Note:-
**For Material(iOS) the Toggle switch is not correct- Already raise a bug for that long time back.(https://github.com/unoplatform/uno/issues/5634)**

https://user-images.githubusercontent.com/74563602/133511342-cf78e644-2864-402c-bc95-444b1f99347a.mp4

### Expected behavior

The Radiobutton and toggleswitch should change according to theme change.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right .
3. Click "RadioButton" Or "Toggleswitch" from the "Component" list.
4. Go to Material section for any of the above the choosed option.
5. Now Change theme from day to Night mode or from Night mode to day Mode.
6. Observe that when theme switch the Radiobutton and ToggleSwitch is not displaying correctly.

### Affected platforms

iOS, Android

**Comment by jeromelaban** [comment]
@kazo0 @Xiaoy312  isn't this caused by the fact that we're using native controls for this ?
