### ISSUE TITLE
[Gallery][Wasm] CalendarView - When theme switch, the UNO Name in the Gallery image is not changing according to theme change.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7098]
### Current behavior

https://user-images.githubusercontent.com/74563602/133515766-338a607e-0610-4144-884d-d08ad585a5db.mp4

### Expected behavior

The Uno Name in Gallery Image should change according to theme change.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "CalendarView" from the "Component" list.
4. Change theme from day to Night.
5. Observe that the Uno Name in Gallery Image is not changing as per the theme change.

### Affected platforms

WebAssembly

**Comment by Youssef1313** [comment]
This recursion is going infinite:

https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs#L441-L445

causing:

![image](https://user-images.githubusercontent.com/31348972/133553700-b43207a8-a716-446a-8f08-e1c2287ac740.png)

This could be preventing some later code to execute that's responsible for changing the image.
