### ISSUE TITLE
ElevatedView not showing on all platforms.

### ISSUE THREAD

**Issue by rizaanlakay** [unoplatform/uno#7099]
### Current behavior

ElevatedView not showing any shadows on any platforms.

### Expected behavior

Expected to see shadows.

### How to reproduce it (as minimally and precisely as possible)

[ShadowTest.zip](https://github.com/unoplatform/uno/files/7175141/ShadowTest.zip)

### Works on UWP/WinUI

No

### Affected platforms

iOS, Android, WebAssembly, Windows

### IDE version

16.11.3

### Relevant plugins

Uno Version 3.10.7

**Comment by jeromelaban** [comment]
Thanks for the repro.

Here's the current way use for this feature:

```xaml
<toolkit:ElevatedView Elevation="10" Background="White" ShadowColor="Black">
	<Frame CornerRadius="10" Padding="10">
		<StackPanel>
			<Button Height="40" Width="200">Elevated Button</Button>
		</StackPanel>
	</Frame>
</toolkit:ElevatedView>
```

The documentation has been updated here: https://github.com/unoplatform/uno/blob/master/doc/articles/features/ElevatedView.md

**Comment by rizaanlakay** [comment]
Happy :) That worked perfectly.
