### ISSUE TITLE
MyProject.Windows.Package.wapproj aren't found

### ISSUE THREAD

**Issue by saigkill** [unoplatform/uno#7101]
### Current behavior

I followed the new creation command from the docs (https://platform.uno/docs/articles/get-started-winui3.html). After creation i opened Visual Studio 2022 Preview 4 and got the error "MyProject.Windows.Package.wapproj aren't found". All projects aren't loadable. 

### Expected behavior

Loading and working with the projects.

### How to reproduce it (as minimally and precisely as possible)

dotnet new -i Uno.ProjectTemplates.Dotnet
dotnet new unoapp-winui -o MyUnoApp
Open MyUnoApp in Visual Studio 2022 Preview 4

### Workaround

Currently nothing known

### Works on UWP/WinUI

No

### Environment

Other

### NuGet package version(s)

Nothing installed

### Affected platforms

Solution Templates

### IDE

Visual Studio 2022

### IDE version

17.0.0 Preview 4.0

**Comment by jeromelaban** [comment]
Thanks for the report.
 
This generally means that you're missing a component or workload to be installed in Visual Studio.

The documentation is clear about the part where you actually need to install the WinUI 3 (Reunion 0.8 SDK). Have you installed this part?

**Comment by saigkill** [comment]
Hi @jeromelaban,

yes indeed, the Reunion 0.8 SDK was already installed.

**Comment by jeromelaban** [comment]
It is installed and you're still getting the issue? In that case, I'd suggest reinstalling Visual Studio and try again. This type of project is provided by visual studio workloads, not by Uno. 

Let us know if it helps.
