### ISSUE TITLE
Fake bottom gradient should respect `BorderThickness`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#7110]
### Current behavior

The fake bottom border used on many V2 Fluent styles does not respect `BorderThickness`. When the bottom border is 0, the fake border should disappear. When it is bigger, it may also need to be adjusted.

### Expected behavior

Should look like WinUI 2.6

### How to reproduce it (as minimally and precisely as possible)

Create a `Button` with 0 `BorderThickness`. Compare UWP vs Uno under WinUI 2.6.

### Workaround

Redefine the style and remove the `BottomBorderElement`

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

3.10.7

### Affected platforms

iOS, Android, WebAssembly, WebAssembly renderers for Xamarin.Forms, macOS, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen), Windows

### IDE

Visual Studio 2022

**Comment by ritt-app** [comment]
@MartinZikmund I am running into this issue as well. Is there a fix available? Or you can elaborate on the workaround?

**Comment by MartinZikmund** [comment]
Duplicate of https://github.com/unoplatform/uno/issues/7621
