### ISSUE TITLE
[Gallery][Wasm/iOS/Android] Material - CalendarDatePicker - Border for disabled 'Select a Date' option is not showing properly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7116]
### Current behavior

![calendardatepicker issue](https://user-images.githubusercontent.com/74563602/133683366-9c7b8819-d3a3-4cb4-abb0-b7169323b771.png)

### Expected behavior

The Border for disabled 'Select a Date option should display.

### How to reproduce it (as minimally and precisely as possible)

Open Uno Gallery APP
Click Burger Menu on the left top right.
Click "CalendarDatePicker" from the "Component" list.
Go to Material Section.
Observe that Border for disabled 'Select a Date' option is not showing properly.

### Affected platforms

iOS, Android, WebAssembly

**Comment by sakshi173** [comment]
@kazo0, this issue is still present for WASM due to that not closing this bug.
For Android & iOS this issue is no more valid as CalendarDatePicker control is removed for these platforms.

**Comment by nguyeenvy** [comment]
Gallery Canary:
![Image](https://github.com/unoplatform/uno/assets/54756963/9fdc42be-5dbf-4085-8ba6-31211d3aee38)

WASM:
![Image](https://github.com/unoplatform/uno/assets/54756963/0c59f990-92bd-4abe-9e39-9084abd92032)

The border is now present. @sakshi173

**Comment by sakshi173** [comment]
This issue is fixed , closing it.
