### ISSUE TITLE
Update NumberBox from WinUI sources

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#7123]
### Current behavior

https://github.com/unoplatform/uno/pull/7122

### Expected behavior

Revert back

**Comment by Youssef1313** [comment]
I can't really imagine how porting `NumberBox` will break such a test. It's completely irrelevant. The only piece of information I could find is that things fail in `TryStaticRetrieval` (in `ResourceResolver`), but no clue how `NumberBox_v1.xaml` affects that.

**Comment by Youssef1313** [comment]
I narrowed down more to that `GetActiveThemeDictionary` is returning null. It's relying on an invalid cached (null) value.

**Comment by jeromelaban** [comment]
Indeed, that's what I found as well. It feels like we should be observing the theme dictionaries to determine if the value should be updated.

**Comment by jeromelaban** [comment]
btw, It's not the PR itself that broke the test, it just raised an unrelated issue because of initialization order... so it's not your fault ;)

**Comment by MartinZikmund** [comment]
@duke7553 was working on updating the source code of `NumberBox`. If you are updating the styles only, that should be fine, but may be useful to check with him to avoid potential conflicts 🙂

**Comment by Youssef1313** [comment]
@MartinZikmund I recall I updated everything. In case @duke7553 had already done it, it might be good idea to compare both branches to check if any of us has missed anything.
