### ISSUE TITLE
GridView Items items not visible

### ISSUE THREAD

**Issue by navio-n** [unoplatform/uno#7146]
### Current behavior

I do not see any GridView items when upgraded to the newest Uno.UI NuGet package Uno.UI 3.10.7.

### Expected behavior

Should work like on 3.9.7

### How to reproduce it (as minimally and precisely as possible)

<Page
    x:Class="UnoTestApp210907.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:UnoTestApp210907"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <GridView x:Name="Fruits">
            <x:String>Apricot</x:String>
            <x:String>Banana</x:String>
            <x:String>Cherry</x:String>
            <x:String>Orange</x:String>
            <x:String>Strawberry</x:String>
        </GridView>
    </Grid>
</Page>

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

iOS, Android

### IDE

Visual Studio 2019

**Comment by Youssef1313** [comment]
It seems to be working with me:

![image](https://user-images.githubusercontent.com/31348972/134048543-747198e5-678d-44a9-88f5-bf550cdae3bb.png)


@navio-n Can you elaborate more on the issue and/or attach a repro?

**Comment by navio-n** [comment]
Your source should be ok.

https://github.com/navio-n/UnoTestApp210907

Try the Android version only. Maybe some SDK's are different.

**Comment by jeromelaban** [comment]
Looks like this was caused by #6374.

You can work around this by using the Fluent v1 styles as follows:

```xaml
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources  ControlsResourcesVersion="Version1"  xmlns="using:Microsoft.UI.Xaml.Controls" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
```

/cc @MartinZikmund

**Comment by navio-n** [comment]
@jeromelaban It works with this workaround. Thanks
