### ISSUE TITLE
[Android] Drag events show compile errors

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#7152]
### Current behavior

`net6.0-android` target can't be compiled with these errors:
```
src\apps\Dedoose.Apps.Uno.Mobile\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\NavigationView_3efec3146d9850f0226dbede3b9033c0.cs(957,165,957,178): error CS1503: Argument 2: cannot convert from 'Windows.UI.Xaml.DragEventArgs' to 'Android.Views.View.DragEventArgs'
src\apps\Dedoose.Apps.Uno.Mobile\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\NavigationView_3efec3146d9850f0226dbede3b9033c0.cs(959,165,959,178): error CS1503: Argument 2: cannot convert from 'Windows.UI.Xaml.DragEventArgs' to 'Android.Views.View.DragEventArgs'
src\apps\Dedoose.Apps.Uno.Mobile\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\NavigationView_3efec3146d9850f0226dbede3b9033c0.cs(961,130,961,138): error CS1503: Argument 2: cannot convert from 'Windows.UI.Xaml.DragEventArgs' to 'Android.Views.View.DragEventArgs'
```

### How to reproduce it (as minimally and precisely as possible)

```xml
<views:NavigationViewBase
    AllowDrop="True"
    DragEnter="OnDragEnter"
    DragLeave="OnDragLeave"
    Drop="OnDrop"
    />
```

```cs
public void OnDragEnter(object sender, DragEventArgs e)
{
}

public void OnDragLeave(object sender, DragEventArgs e)
{
}

public void OnDrop(object sender, DragEventArgs e)
{
}
```

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

3.11.0-dev.139

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

preview 4.1

**Comment by HavenDV** [comment]
This does not apply to the code that I control. These errors appear even if you specify the fully qualified name of the type(`Windows.UI.Xaml.DragEventArgs`).

**Comment by Youssef1313** [comment]
@HavenDV Can you upload a solution where this reproduces (preferably minimal)?

**Comment by jeromelaban** [comment]
> What is the fundamental difference between the solution using `using DragEventArgs = Windows.UI.Xaml.DragEventArgs;` with the full name?

Good to see that it works. The main difference is that using statements take over the standard type resolution, forcing the `Windows.UI.Xaml.` resolution. There's a similar issue with the `Window` type on iOS, or the `Debug` class on android, for which the type needs to explicitly specified for the compilation to go through.
