### ISSUE TITLE
[Calculator][Wasm/Android] For Angle, Area and some other Converter Calculator, the last selected measure option is not highlighting, and for Android multiple measure option is displaying as selected.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7164]
### Current behavior

https://user-images.githubusercontent.com/74563602/134233150-06f39c64-eca8-49c8-9923-0c16ecb07c19.mp4

https://user-images.githubusercontent.com/74563602/134233209-753f4f2a-6121-4840-91e6-37a152bf6300.mp4

https://user-images.githubusercontent.com/74563602/134233486-c217b63d-cf70-4fab-9d73-de74c123b469.mp4

### Expected behavior

Only the last selected measure option should highlight.

### How to reproduce it (as minimally and precisely as possible)

Open Chrome on Android device
Visit https://calculatorcanary.z27.web.core.windows.net/
Go to the Converter calculator.
Choose the Angle calculator.
Click on the measure angle option.
Choose Measuring option as 'Gradian'.
Again click on the measure angle option.
Observe that the 'Gradian' is not highlighting as the previously selected measure option.

### Affected platforms

Android, WebAssembly

**Comment by jeromelaban** [comment]
I cannot repro with today's canary, can you retry ?

**Comment by sakshi173** [comment]
okay, i Retry today.

**Comment by sakshi173** [comment]
Hi @jeromelaban , I tried with the latest canary and the issue is present in that build too, For Repro please go to multiple converter and tried to changes the converter multiple times. sometime it works and sometime it does not work.
Issue is present mostly for these Converter -- **Temperature**( the down one converter), **Angle** ( the down one converter), **Energy**( The top one converter and issue is mostly happening for **Joules and Kilojoules**), Speed(The top one converter and issue is mostly happening for **Kilometers per hour and Meters Per second**). 
Again the video is also present for reference.

https://user-images.githubusercontent.com/74563602/134958846-13ab9470-92a7-4b11-9cd2-4f40b7469a82.mp4

**Comment by sakshi173** [comment]
Verified with latest canary build, Issue is fixed, closing.

https://user-images.githubusercontent.com/74563602/159054900-314f1078-4389-4193-9896-3901439ed181.mp4


https://user-images.githubusercontent.com/74563602/159056405-3f3b32d5-b3f1-49c5-881b-56ebede4cdbb.mp4
