### ISSUE TITLE
[iOS] The Flyout menu position is displayed on the left - on Device iPhone 11 - 13.3

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/uno#7175]
### Current behavior

On Device iPhone 11 - 13.3

### Expected behavior

Any other device

### How to reproduce it (as minimally and precisely as possible)

Add MenuFlyout to an AppBarButton in <CommandBar.PrimaryCommands>

### Workaround

None

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI 3.10.0-dev.632

### Affected platforms

iOS

### IDE

Visual Studio 2019

### IDE version

16.9.4

### Relevant plugins

None

**Comment by jeanplevesque** [comment]
@MaximeDion-Work Don't we also have that bug on Android on some specific devices too?

**Comment by MaximeDion-Work** [comment]
Deny says only iPhone 11
