### ISSUE TITLE
[Gallery][Skia.GTK] TimePicker - When click on 'Set Time' option nothing is happening.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7177]
### Current behavior

https://user-images.githubusercontent.com/74563602/159347538-2164c878-fa94-4f88-9dba-3e58d9382fa1.mp4

### Expected behavior

The Time picker calendar should open properly.

### How to reproduce it (as minimally and precisely as possible)

Launch the Uno.Gallry app on Skia.GTK
Click on “TimePicker” item from the 'Component' list.
Click on 'Set Time'  section.
Observe that nothing is happening .

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by sakshi173** [comment]
Still this issue is present. Please let me know the Timepicker control should be available for the Skia platform or not?

**Comment by jeromelaban** [comment]
Time picker is not yet implemented. Let's track this with https://github.com/unoplatform/uno/issues/5553. In the meantime, we should be disabling this control for the platforms where it's not implemented. @kazo0

**Comment by sakshi173** [comment]
@kazo0, Please let me know can I close this issue as Time picker component is not present for Skia platform so this bug is now irrelevant.

**Comment by agneszitte** [comment]
@MartinZikmund assigning you this issue so you can check the status of TimePicker please (sample disabled at the moment for Gallery)

**Comment by MartinZikmund** [comment]
This is fixed, as `TimePicker` was ported
