### ISSUE TITLE
[Gallery][Skia.GTK] MessageDialog- When clicking on MessageDialog options like 'Content only' message dialog is not opening.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7179]
### Current behavior

https://user-images.githubusercontent.com/74563602/134414559-a4f6f12f-60d1-4f2a-a49e-641d42e764cc.mp4

### Expected behavior

https://user-images.githubusercontent.com/74563602/134414727-0550711d-34a5-4c26-8454-daabb5f60255.mp4

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app on Skia.GTK
2. Click on “MessageDialog” item from the 'Features' list.
3. Click on 'Content only' button.
4. Observe that  the message dialog are not opening for 'Content only' option.

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment]
This is a duplicate of #4810.

It's not implemented yet for Skia:

https://github.com/unoplatform/uno/blob/33c3a26c935361432ad713c2e8debc521616c6be/src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Popups/MessageDialog.cs#L29-L35

**Comment by sakshi173** [comment]
As @Youssef1313 its duplicate of #4810. I am closing this one.
