### ISSUE TITLE
Invalid GUID parameter name in dotnet new template JSON

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/uno#7203]
### Current behavior

https://github.com/unoplatform/uno/blob/287f9785be664ca577775b1bb6b90fe68bbd26fb/src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.template.config/template.json#L46

`format` property does not work according to https://github.com/dotnet/templating/issues/1737#issuecomment-831869212 and `defaultFormat` must be used instead

### Expected behavior

GUIDs are formatted correctly within the template

### How to reproduce it (as minimally and precisely as possible)

If you change GUID format in the template to any of the supported values https://docs.microsoft.com/en-us/dotnet/api/system.guid.tostring?view=net-5.0 different from the default you will get GUID formatted with default format

### Workaround

Format GUIDs manually as now

### Environment

Other

### Affected platforms

iOS, Android, macOS, Windows, Solution Templates

**Comment by xperiandri** [comment]
If you approve the change I can prepare a pull request

**Comment by jeromelaban** [comment]
Thanks for the report and noticing the formatting issue! Sure, let's validate the new behavior, thanks!
