### ISSUE TITLE
[Skia] Native TextBox not moving when ContentDialog resized.

### ISSUE THREAD

**Issue by trungnt2910** [unoplatform/uno#7209]
### Current behavior

A `TextBox` on Skia platforms does not resize its native view when the `ContentDialog` resizes.

https://user-images.githubusercontent.com/57174311/134815135-3c18602a-56fd-4ca2-91b9-b8146b9783a9.mp4

### Expected behavior

All parts of that `TextBox` should move correctly

### How to reproduce it (as minimally and precisely as possible)

[SkiaTestContentDialogTextBox.zip](https://github.com/unoplatform/uno/files/7231668/SkiaTestContentDialogTextBox.zip)

- Press the button.
- **PASTE** some really long text. (Paste it, don't type it).
- The problem appears.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

From 3.8.3 to 3.10.7

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2019

### IDE version

16.11

### Anything else we need to know?

As Skia `TextBoxView` extensions rely on the `SizeChanged` and `LayoutUpdated` events to determine its size and position, these events must fire properly for the TextBlock to work properly.

However, they do not work, as `LayoutUpdated` fires before all control sizes are updated.
For example, this is the log produced by the sample, when I paste a some text on that block:

```
// UWP

[Debug]: 25/9/2021 8:09:05 PM    : Size Changed. New size is: 420,53.33333
[Debug]: 25/9/2021 8:09:05 PM    : Layout Updated. New position is: 238.6667,114.6667
[Debug]: 25/9/2021 8:09:05 PM    : Size Changed. New size is: 472.6667,53.33333
[Debug]: 25/9/2021 8:09:05 PM    : Layout Updated. New position is: 212,114.6667
[Debug]: 25/9/2021 8:09:05 PM    : [Follow up]: Layout Updated. New position is: 212,114.6667
[Debug]: 25/9/2021 8:09:05 PM    : [Follow up]: Layout Updated. New position is: 212,114.6667

// WASM

[Debug]: 9/25/2021 8:14:05 PM    : Size Changed. New size is: 478,52
[Debug]: 9/25/2021 8:14:05 PM    : Layout Updated. New position is: [730, 598.5]
[Debug]: 9/25/2021 8:14:05 PM    : Layout Updated. New position is: [626, 598.5]
[Debug]: 9/25/2021 8:14:05 PM    : [Follow up]: Layout Updated. New position is: [626, 598.5]
[Debug]: 9/25/2021 8:14:05 PM    : [Follow up]: Layout Updated. New position is: [626, 598.5]

// Skia.WPF

[Debug]: 25/9/2021 8:16:01 PM    : Layout Updated. New position is: [259.666687011719, 141.333343505859]
[Debug]: 25/9/2021 8:16:01 PM    : Size Changed. New size is: 474,52
[Debug]: 25/9/2021 8:16:01 PM    : Layout Updated. New position is: [259.666687011719, 141.333343505859]
[Debug]: 25/9/2021 8:16:02 PM    : [Follow up]: Layout Updated. New position is: [157.47770690918, 141.333343505859]
[Debug]: 25/9/2021 8:16:02 PM    : [Follow up]: Layout Updated. New position is: [157.47770690918, 141.333343505859]

// Skia.Gtk

[Debug]: 9/25/2021 8:23:12 PM    : Layout Updated. New position is: [405, 379.5]
[Debug]: 9/25/2021 8:23:12 PM    : Size Changed. New size is: 498,54.5390625
[Debug]: 9/25/2021 8:23:12 PM    : Layout Updated. New position is: [405, 379.5]
[Debug]: 9/25/2021 8:23:13 PM    : [Follow up]: Layout Updated. New position is: [291, 379.5]
[Debug]: 9/25/2021 8:23:13 PM    : [Follow up]: Layout Updated. New position is: [291, 379.5]
```

[Follow up] means 500ms after the event has actually fired. On all platforms, `LayoutUpdated` is fired twice, but on `Skia`, the second event still does not carry valid positions.

**Comment by trungnt2910** [comment]
Please point me some differences in the implementation of `ContentDialog` between `Skia` and other platforms. Browsing through the source code, I can see that `Skia` has the same `ContentDialog` and `Popup` implementation as other targets; therefore, I couldn't do any further analysis.

**Comment by jeromelaban** [comment]
This issue is likely not related to the `ContentDialog`, but rather to the the `TextBox` control in Skia which uses a GTK overlay mode. It's working minimally, but has issues like the one you've found.

If you try changing the size of an other type or control, say a `Border`, does the size of the `ContentDialog` change ?

**Comment by trungnt2910** [comment]
@jeromelaban 
> This issue is likely not related to the `ContentDialog`, but rather to the the `TextBox` control in Skia which uses a GTK overlay mode. It's working minimally, but has issues like the one you've found.
> 
> If you try changing the size of an other type or control, say a `Border`, does the size of the `ContentDialog` change ?

The **size** of the `ContentDialog` **always** changes properly, resizing when its contents expand.
However, the **events** are not being raised properly.

Replacing the `TextBox` with a `Border`, and resize it using
```
_border.Width = _border.ActualWidth + 100;
```
gives me this log (on Skia.WPF):
```
[Debug]: 27/9/2021 9:08:27 AM	: Size Changed. New size is: 370,50
[Debug]: 27/9/2021 9:08:27 AM	: Layout Updated. New position is: [259.666687011719, 125.882164001465]
[Debug]: 27/9/2021 9:08:27 AM	: [Follow up]: Layout Updated. New position is: [209.66667175293, 125.882164001465]
```

Again, as you can see in the sample repo, `[Follow up]` means 500ms after the actual event is raised.
When the `LayoutUpdated` content is raised, Uno still hasn't updated the `ContentDialog`'s size and position on Skia, while on other platforms (as well as UWP), `LayoutUpdated` is raised only when all numbers have been correct.

This is the real cause of this issue, I'd say `TextBoxView`'s Skia implementation should be completely correct when subscribing to the `LayoutUpdated` event. It is only faulty when this event fools the `TextBoxView` with wrong data.

**Comment by jeromelaban** [comment]
Thanks for the update
