### ISSUE TITLE
Add support for Windows.Globalization.Language.CurrentInputMethodLanguageTag

### ISSUE THREAD

**Issue by yowl** [unoplatform/uno#721]
## I'm submitting a...

  
 - Feature request 

## Current behavior
Attempts to get the `CurrentInputMethodLanguageTag` fail as its not supported

## Expected behavior
Add some means (maybe just put a setter) so that this property can be called.  This would be beneficial in getting closer to supporting Telerik's UWP controls as they (I think the numeric input) uses this.

## Minimal reproduction of the problem with instructions

Attempt to call the property.  Its marked as not supported https://github.com/nventive/Uno/blob/25d0c4adb3b98b0f201a46c2336adb78d69067a5/src/Uno.UWP/Generated/3.0.0.0/Windows.Globalization/Language.cs#L60-L63

## Environment

```
Nuget Package: 

Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ x] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by MartinZikmund** [comment]
I can do this one for Android and iOS, but not sure about WebAssembly. I think there is no way to get current input language in JavaScript. Should WebAssebly have a setter then?

**Comment by yowl** [comment]
That would be ok for me.

**Comment by MartinZikmund** [comment]
@yowl Can this be closed?

**Comment by yowl** [comment]
@MartinZikmund Yes thanks.
