### ISSUE TITLE
[WASM on iOS 12.5.4] Click event does not fire on `Button` and `HyperlinkButton`

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#7215]
### Current behavior

Clicking buttons and hyperlink buttons does not work. They gain focus but don't do anything.

### Expected behavior

The buttons should work. I know iOS 12.5.4 is a bit older but there are still tons of iPhone 6 devices out there stuck on this version and I think a web app should really work on almost anything reasonable so this is a bit of a massive problem for us. Our app needs to be universally accessible to everyone.

### How to reproduce it (as minimally and precisely as possible)

Add any Button/HyperlinkButton to any page and wire up `Click="OnButtonClick"` . The event never fires.

Test project posted to https://app.iratio.ca/test with source at https://github.com/mikernet/UnoTest.

### Workaround

None

### NuGet package version(s)

Uno.UI.WebAssembly: tested on versions ranging from 3.9.0-dev-220 to 3.11.0-dev-210.

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
We've made recent changes in this area, would you mind testing with a more recent 3.11-dev build ?

**Comment by mikernet** [comment]
Same thing on 3.11-dev.210.

**Comment by Arieldelossantos** [comment]
hey @jeromelaban i've been trying to repro this issue and apparently it only occurs on the mentioned version, the only problem is that iOS doesn't have this simulators version on xcode
![image](https://github.com/unoplatform/uno/assets/34275909/bd100788-187d-477c-b5f1-23ee57a5f0f9)

do you know where can i find this simulator version?? i haven't found it so far :/

cc: @MartinZikmund

**Comment by jeromelaban** [comment]
As it works on later versions of iOS, I don't think we need to spend time fixing this particular behavior.
