### ISSUE TITLE
[macOS][InfoBar] Icons are not displayed 

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/uno#7222]
### Current behavior

Instead of icons `InfoBar` displays a question mark on MacOS

![image](https://user-images.githubusercontent.com/2365592/134870523-3addf902-efe8-452c-8ca6-d2497d1713bc.png)

### Expected behavior

`InfoBar` displays icons the same on all platforms

### How to reproduce it (as minimally and precisely as possible)

1. Create Uno app from template
2. Add to MainPage.xaml
``` XAML
xmlns:muxc="using:Microsoft.UI.Xaml.Controls"

<muxc:InfoBar IsOpen="True" IsClosable="False" Message="As long as text is the same, no new notification is created when button is pressed multiple times, only timer starts again. But if you change the text the button will add a new notification." />
```
3. Run on MacOS 11.6

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

3.10.11

Xamarin SDK 15.0.0.*

### Affected platforms

iOS
macOS

### IDE

Visual Studio for Mac

### IDE version

8.10.9

**Comment by xperiandri** [comment]
Yes, version 1 forks fine

**Comment by xperiandri** [comment]
The same thing happens on Android
![Screenshot_1650310901](https://user-images.githubusercontent.com/2365592/163866790-16510846-3190-494a-84fc-874405362667.png)

**Comment by MartinZikmund** [comment]
This now only applies to macOS AppKit

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
