### ISSUE TITLE
`ContentDialog` `Title`/`Content` padding does not match UWP

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#7226]
### Current behavior

On non-UWP platforms (I've specifically tested iOS and WASM) the content dialogs put way too much padding inside the dialog border and not enough under the title. This what it looks like:

![image](https://user-images.githubusercontent.com/1700111/134928769-cda2b74d-7741-4051-9b45-81aea18df54d.png)

### Expected behavior

It should be padded the same as UWP:

![image](https://user-images.githubusercontent.com/1700111/134928679-a5231228-4de8-4f16-83fb-ca36ac768c46.png)

### How to reproduce it (as minimally and precisely as possible)

Create a content dialog and compare the padding.

### NuGet package version(s)

3.11.0-dev.210

### Affected platforms

iOS, WebAssembly

**Comment by mikernet** [comment]
It doesn't look like I can override the padding either for some reason. Whether I put
```xml
<Thickness x:Key="ContentDialogPadding">100</Thickness>
```
Or
```xml
<Thickness x:Key="ContentDialogPadding">0</Thickness>
```
Into `app.xaml`, nothing changes.

**Comment by mikernet** [comment]
P.S. When I look at Uno source it looks like `<Thickness x:Key="ContentDialogPadding">` is set to the same thing as UWP's default so the issue may be a layout bug or something else in the template.

**Comment by Marc-Antoine-Soucy** [comment]
![image](https://github.com/unoplatform/uno/assets/90481654/5d7dd801-b67c-42ba-b695-a095d3a47e55)
Is this enough to say this is fixed? Or should I try to make something closer to what they have?

**Comment by jeromelaban** [comment]
This is looking good! Thanks!
