### ISSUE TITLE
[iOS/Android] Suspending app closes any open `ContentDialog`

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#7228]
### Current behavior

If a `ContentDialog` is currently open and the app is suspended (i.e. the home button is clicked), the content dialog is closed for some reason, with no way to be notified that it is being closed because:

1) `OnClosing/OnClosed` does not fire on the dialog
2) The following does not work in `Application.OnSuspending` to get the open dialog because it's already closed at this point (works on UWP):
```cs
VisualTreeHelper.GetOpenPopups(Xaml.Window.Current)
                .Select(p => p.Child)
                .OfType<ReviewDialog>()
                .FirstOrDefault();
```

### Expected behavior

Don't close the dialog when the app is suspended.

### Workaround

No general workaround for all dialogs that doesn't potentially put the application into an inconsistent state. 

If no code needs to execute after `await dialog.ShowAsync()` (and ONLY in that situation) you can store the currently open dialog on an `App` property (ie. `App.OpenDialog`) and then do something like:

```cs
private async void OnResuming(object sender, object e)
{
#if __IOS__
    if (OpenDialog != null) {
        _ = await OpenDialog.ShowAsync();
        OpenDialog = null;
    }
#endif
}
```

### Works on UWP/WinUI

Yes

### NuGet package version(s)

Uno.UI v3.11.0-dev.210

### Affected platforms

iOS
Android

**Comment by mikernet** [comment]
What even happens to the `IAsyncOperation` when you're awaiting an open dialog and the app suspends? It looks to me like it never completes. Does it just get GC'd without ever firing the continuation?

**Comment by mikernet** [comment]
This also happens on Android as well.

**Comment by MartinZikmund** [comment]
This was fixed in https://github.com/unoplatform/uno/pull/11723
