### ISSUE TITLE
[iOS] Multiline TextBox in ContentDialog breaks layout and crashes app

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#7236]
### Current behavior

When a multiline textbox is added into a ContentDialog, it rapidly grows in height and pushes down the controls under it with every key that is pressed (i.e it keeps getting bigger even though no more lines are being added), and then crashes the program after some number of keystrokes. Even if `MaxHeight` or `Height` is set it will blow past that height.

### Expected behavior

Size height of the `TextBox` correctly.

### How to reproduce it (as minimally and precisely as possible)

```xml
<ContentDialog>
    <ScrollViewer>
        <StackPanel>
            <TextBox TextWrapping="Wrap" AcceptsReturn="True" />
            <Button Content="Button Under TextBox" />
        </StackPanel>
    </ScrollViewer>
</ContentDialog>
```

### Workaround

None.

### Works on UWP/WinUI

Yes

### NuGet package version(s)

v3.7.7 to v3.11.0-dev210

### Affected platforms

iOS

**Comment by jeromelaban** [comment]
Thanks for the report. Make sure to add a buildable repro, so we can take a look and reduce the possibility of side effects.

**Comment by mikernet** [comment]
I have to fix that test iOS project I have - will follow up with a repro after I do that.

**Comment by mikernet** [comment]
This might take a bit to narrow down as the code above needs something else,  just not sure what it is yet. The problem doesn't happen on WASM or UWP though. I'll let you know what I figure out.

**Comment by mikernet** [comment]
I believe this is resolved in newer builds. I will reopen if I come across it again.
