### ISSUE TITLE
[WASM] MUXC NavigationView Header displays unnecessary indentation

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#7239]
### Current behavior

![image](https://user-images.githubusercontent.com/3002068/135217936-7360f57c-95d0-40ae-8487-f6af2936e955.png)
I'm not sure what exactly the problem is. The problem is either indentation or default vertical alignment. This showed up after updating to 3.11.0-dev.242 from about 3.10.0-dev.500

### Expected behavior

![image](https://user-images.githubusercontent.com/3002068/135218145-1d6982e2-9bce-4c38-9756-72d180861aaf.png)

### How to reproduce it (as minimally and precisely as possible)
`xmlns:muxc="using:Microsoft.UI.Xaml.Controls"`

```xml
<muxc:NavigationView
  IsSettingsVisible="False"
  AlwaysShowHeader="True"
  IsTabStop="False" 
  IsPaneToggleButtonVisible="True" 
  IsPaneOpen="True" 
  IsPaneVisible="True"
  PaneDisplayMode="LeftCompact"
  >
  <muxc:NavigationView.Header>
    <TextBlock
        HorizontalAlignment="Center"
        VerticalAlignment="Center"
        Text="Test"
        />
  </muxc:NavigationView.Header>
</muxc:NavigationView>
```

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

3.11.0-dev.242

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

preview 4.1

### Anything else we need to know?

This does not work:
```xml
<Style TargetType="muxc:NavigationViewItemHeader">
  <Setter Property="VerticalAlignment" Value="Center"/>
  <Setter Property="VerticalContentAlignment" Value="Center"/>
</Style>
```

Note: In the UWP version, I used Microsoft.UI.Xaml 2.6.0-prerelease.210430001. When upgrading to 2.8.0-prerelease.210927001, the problem also appears in UWP.

**Comment by HavenDV** [comment]
Also a small question: When will Uno support switching localizations? The default system language is currently used.

**Comment by MartinZikmund** [comment]
@HavenDV multiple localizations should already be supported (we include all string resources available in WinUI). Are you having problems seeing your app localized?

**Comment by HavenDV** [comment]
@MartinZikmund I mean these apis:
```
warning Uno0001: Windows.Globalization.ApplicationLanguages.ManifestLanguages is not implemented in Uno
warning Uno0001: Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride is not implemented in Uno
warning Uno0001: Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride is not implemented in Uno
warning Uno0001: Windows.ApplicationModel.Resources.Core.ResourceContext.Reset() is not implemented in Uno
warning Uno0001: Windows.ApplicationModel.Resources.Core.ResourceManager.DefaultContext is not implemented in Uno
warning Uno0001: Windows.ApplicationModel.Resources.Core.ResourceManager.Current is not implemented in Uno
```

I am using this code in UWP to dynamic change localization:
```cs
LanguageComboBox.ItemsSource = Windows.Globalization.ApplicationLanguages.ManifestLanguages;
LanguageComboBox.SelectedItem = Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride;
LanguageComboBox.SelectionChanged += static (sender, args) =>
{
    var comboBox = (ComboBox)sender;
    var language = (string)comboBox.SelectedItem;

    Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride = language;
    Windows.ApplicationModel.Resources.Core.ResourceManager.Current.DefaultContext.Reset();

    var app = (App)Application.Current;
    app.RefreshViews(); // recreates views
};
```

**Comment by HavenDV** [comment]
Note: In the UWP version, I used Microsoft.UI.Xaml 2.6.0-prerelease.210430001. When upgrading to 2.8.0-prerelease.210927001, the problem also appears in UWP.

**Comment by Youssef1313** [comment]
@HavenDV I think this means that the styles has changed in WinUI, and Uno is using the updated styles from WinUI.

Since you're seeing that in WinUI 2.8 with the UWP head, I *think* it's best to open an issue for microsoft/microsoft-ui-xaml repo.

Regarding the not implemented APIs, it's weird that you get "PrimaryLanguageOverride" is not implemented. It's implemented (though isn't implemented correctly, but you shouldn't get a warning for that)

**Comment by HavenDV** [comment]
I will create an issue in https://github.com/CommunityToolkit/WindowsCommunityToolkit, it has nothing to do with Uno.

**Comment by HavenDV** [comment]
@MartinZikmund @Youssef1313 regarding the localization issue, I added a feature issue for discussion/tracking progress:
https://github.com/unoplatform/uno/issues/7240

**Comment by HavenDV** [comment]
https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4284
