### ISSUE TITLE
[WASM] x:Load does not show the view on subsequent property changes

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno#7244]
### Current behavior

Have a view with an element that uses x:Load bound to a view model property.  It will show/hide the first time the property changes, but subsequent changes to the property will not show the view again.

### Expected behavior

View shows every time the property is set to true.

### How to reproduce it (as minimally and precisely as possible)

Attaching a sample project.  Hit the Show button, then Close and then Show again.  The view will not be visible again.

[App1.Shared.zip](https://github.com/unoplatform/uno/files/7253682/App1.Shared.zip)

### Workaround

Use visibility bindings instead.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

PackageReference Include="Uno.Material" Version="1.0.0-dev.827" 
PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls" Version="7.1.0-build.43.g15261a775c" 
PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid" Version="7.1.0-build.43.g15261a775c" 
PackageReference Include="Uno.Microsoft.Xaml.Behaviors.Uwp.Managed" Version="2.0.3-uno.95" 
PackageReference Include="Uno.UI.WebAssembly" Version="3.11.0-dev.242" 
PackageReference Include="Uno.UI.RemoteControl" Version="3.11.0-dev.242" Condition="'$(Configuration)'=='Debug'" 
PackageReference Include="Uno.Wasm.Bootstrap" Version="3.0.0" 
PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="3.0.0" 

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

4.1

**Comment by jeromelaban** [comment]
Reopening as the issue was incorrectly linked to another PR.

**Comment by jeromelaban** [comment]
This issue also contains an additional problem, where two or more x:Load on the same property don't update the visibility properly. It'll be fixed as part of the opened PR.
