### ISSUE TITLE
[iOS] ContentDialog buttons are hidden behind the keyboard when it is open

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#7248]
### Current behavior

When a ContentDialog (with a ScrollViewer inside it) is taller than the available screen space and the keyboard is open, you can't scroll down to the dialog buttons.

This is especially problematic when combined with https://github.com/unoplatform/uno/issues/7247 on dialogs where the last textbox is multiline because the user has no easy way to dismiss the keyboard nor any way to hit the dialog buttons to continue. All they can do is scroll back up and try to find a blank space to click on, then scroll all the way back down hoping they don't focus the textbox again.

### Expected behavior

You should be able to scroll down to see the dialog buttons, even if the keyboard is currently open.

### How to reproduce it (as minimally and precisely as possible)

```xml
<ContentDialog>
  <ScrollViewer>
    <TextBox Height="800" /> <!-- or whatever height you need to push the buttons under the keyboard -->
  <ScrollViewer>
<ContentDialog>
```
Notice you can't scroll down to see the dialog buttons when the TextBox has focus - it stops just before the buttons appear.

### NuGet package version(s)

Uno.UI v3.11.0-dev.210

### Affected platforms

iOS

**Comment by jeromelaban** [comment]
Uno does not provide anything specific for this particular scenario, though you can detect if the keyboard is opened:

```csharp
InputPane.GetForCurrentView().Showing += (s, args) => ...
InputPane.GetForCurrentView().Hiding += (s, args) => ...
```

There is support for scrolling if the content is in the app layer (not the popup layer):

https://github.com/unoplatform/uno/blob/1f8d45f744a9d253c2fe0ec6b3a8bd683fd56baa/src/Uno.UI/Controls/Window.iOS.cs#L256

**Comment by mikernet** [comment]
Sorry, I'm not entirely clear on what you're saying or suggesting. On WASM you can scroll down to the buttons even if the keyboard is open. On iOS it doesn't allow that.

**Comment by mikernet** [comment]
I kinda worked around it by binding a "Done" button's opacity to the focused state of the last multiline textbox in the ContentDialog so the user can at least scroll down and dismiss the keyboard by clicking the button which then lets them click the ContentDialog buttons but this is a bit hacky and should be unnecessary IMO.
