### ISSUE TITLE
Cannot init identically named `ResourceDictionaries` from different namespaces

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#7251]
### Current behavior

```xml
<MaterialResources xmlns="using:Uno.Material" />
<MaterialResources xmlns="using:Uno.Toolkit.Material" />
```

Results in generated code:
```csharp
Resources.MergedDictionaries.Add(
	new global::Uno.Material.MaterialResources()
	{

	});
Resources.MergedDictionaries.Add(
	new global::Uno.Material.MaterialResources()
	{

	});
```

Notice they are both from the namespace `Uno.Material`

### Expected behavior

Above XAML should result in the proper ResourceDictionary from the corresponding namespace:

```csharp
Resources.MergedDictionaries.Add(
	new global::Uno.Material.MaterialResources()
	{

	});
Resources.MergedDictionaries.Add(
	new global::Uno.Material.Toolkit.MaterialResources()
	{

	});
```

### Workaround

Rename `Uno.Toolkit.Material.MaterialResources` to something other than `MaterialResources`

### Works on UWP/WinUI

Yes

**Comment by Youssef1313** [comment]
I'm going to take a look.

**Comment by Youssef1313** [comment]
@kazo0 I was unable to reproduce:

![image](https://user-images.githubusercontent.com/31348972/135481653-dd8e4be0-b25a-40c9-a492-c2b849b70b38.png)

**Comment by kazo0** [comment]
Strange, this might be a more complex issue than I thought. My example is coming from an Uno Library that itself contains a different Uno Library and Uno Library A is trying to initialize resource from it's inner Library B. I'll try and make a repro project

**Comment by MartinZikmund** [comment]
@kazo0 should we still keep this open, or is not relevant anymore?

**Comment by kazo0** [comment]
@MartinZikmund I don't think this is relevant anymore
