### ISSUE TITLE
UWP Crash on Release mode (Debug environment works fine)

### ISSUE THREAD

**Issue by assassin316** [unoplatform/uno#7254]
### Current behavior

There is an Invalid Cast that occurs in `Release` mode of UWP apps, it seems to be related to cast an `int` to `enum` value.

### Expected behavior

The application should execute normally in both `Debug` and `Release` modes.

### How to reproduce it (as minimally and precisely as possible)

I've attached two projects: `UnoTest` and `UnoTest_Older_Uno`.

`UnoTest` references the latest packages:

![nuget_newer](https://user-images.githubusercontent.com/17514380/135498868-87fbb2b4-79d8-4ee8-9bb3-63c7c220ffc7.png)

`UnoTest_Older_Uno` references older Uno packages:

![nuget_older](https://user-images.githubusercontent.com/17514380/135498921-1f24d813-a499-41e4-bc85-f8c5627da96c.png)

To reproduce, launch `UnoTest` in `Release` mode and uncheck `Optimize Code`:

![optimize](https://user-images.githubusercontent.com/17514380/135499022-7f0d9c5b-34e4-43c1-9c69-0ff2210fa57e.png)

You'll receive this error related to an invalid case of an `enum` value, which used to work in previous versions (prior to Uno 3.8.6):

![error](https://user-images.githubusercontent.com/17514380/135499065-4b804259-b444-4b07-84e4-1ed1b360bf6a.png)

The enum references is this one:

https://github.com/XamlFlair/XamlFlair/blob/59cbce90eae1c26d579f77ebecda341ed377b024/XamlFlair.Shared/Entities/AnimationKind.cs#L9

Launching `UnoTest_Older_Uno` and launching in the same manner does not produce the crash.

### Workaround

None.

### Works on UWP/WinUI

No

### NuGet package version(s)

Uno.UI 3.10.11

### Affected platforms

Windows

### IDE

Visual Studio 2019

### Anything else we need to know?

I test my app with Uno 3.8.6, crash still occurred, Uno.UI 3.5.1 is the last version where it seemed to work.

**Comment by assassin316** [comment]
[UnoTest.zip](https://github.com/unoplatform/uno/files/7261306/UnoTest.zip)
[UnoTest_Older_Uno.zip](https://github.com/unoplatform/uno/files/7261307/UnoTest_Older_Uno.zip)

**Comment by jeromelaban** [comment]
Thanks for the report. This is a .NET native related issue, and is not related to Uno.

Can you try disabling .NET Native ?

**Comment by assassin316** [comment]
Unfortunately the same  😟

![image](https://user-images.githubusercontent.com/17514380/135512082-ac0c88a2-59aa-4179-ba8b-2882173f060f.png)

**Comment by jeromelaban** [comment]
Thanks. Unfortunately, this is not something we can help with as it's UWP related.

From your samples, it seems that there are many differences in package versions there, trying to revert some of those could help.

**Comment by MartinZikmund** [comment]
Closing this as it is not a Uno-related issue. For further help, try to report at https://github.com/microsoft/microsoft-ui-xaml/
