### ISSUE TITLE
[Skia] MenuBar popup continuously resizes

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#7262]
### Current behavior

https://user-images.githubusercontent.com/46191980/135573177-69d2adfe-f99c-4b7e-86d6-9bdd6eba4f1a.mp4

Observe that the popup is resizing/flickering when opened.

### Expected behavior

The menu bar does not flicker.

### How to reproduce it (as minimally and precisely as possible)

[TestMenuBar.zip](https://github.com/unoplatform/uno/files/7267301/TestMenuBar.zip)

### Works on UWP/WinUI

Yes

**Comment by dragonDScript** [comment]
Thanks @jeromelaban

**Comment by jeromelaban** [comment]
We are not able to reproduce this issue with recent builds of uno. Could you try again with the 4.0 release and let us know ?

**Comment by dragonDScript** [comment]
Sure, just give me a few days.
