### ISSUE TITLE
[Gallery][macOS] `CalendarDatePicker` - calendar is not opening when clicking on 'Select a Date' option for Material, Fluent and Cupertino.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7274]
### Current behavior

https://user-images.githubusercontent.com/74563602/135905909-6e6be6de-27ae-4744-a11e-f434eccbca25.mp4

### Expected behavior

Calendar should open when click on 'Select a Date' Option for all.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "CalendarDatePicker" from the "Component" list.
4. Click on 'Select a Date' option.
5. Observe that calendar is not opening to choose the date.

### Affected platforms

macOS

**Comment by nguyeenvy** [comment]
This issue has been resolved in the latest Uno Gallery app on MacOS. This can be closed. @sakshi173
