### ISSUE TITLE
[Gallery][macOS] `Checkbox` - for checkbox focus does not goes off from checkbox, and sometime for `Indeterminate` and `Checked`, the only respond to the pointer on the second click.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7282]
### Current behavior

https://user-images.githubusercontent.com/74563602/136070475-c11b7e9b-48d0-45d4-8491-125aa54c86c2.mp4

### Expected behavior

The checkbox get click in first click and also focus should goes off once the checkbox is clicked.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "Checkbox" from the "Component" list.
4. Go to "Fluent" section.
5. Click on checkbox for "Unchecked" option.
6. Observe that For checkbox focus does not goes off from checkbox, and sometime for Indeterminate and Checkedbox, the only respond to the pointer on the second click.

### Affected platforms

macOS

**Comment by nguyeenvy** [comment]
I do not see this issue in Uno Gallery MacOS anymore. This may be closed @sakshi173 if you can confirm that it is resolved.

**Comment by agneszitte** [comment]
Testing is not possible at the moment, it will be fixed when we move to .NET 8
Will need to be brought back to QA Review when testing is possible again

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
