### ISSUE TITLE
[Gallery][macOS] `DatePicker` - the application is very slow, calendar opening taking around 17 seconds

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7283]
### Current behavior

https://user-images.githubusercontent.com/74563602/136083626-d7eb17a5-11ad-4de0-9529-3a362d90b3b4.mp4

### Expected behavior

The calendar should open as click on the 'Set Date' Option.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "DatePicker" from the "Component" list.
4. Click on  "Set Date" option.
5. Observe that  DatePicker  application is very slow, calendar opening taking around 17 seconds.

### Affected platforms

macOS

**Comment by nguyeenvy** [comment]
The time it takes to open isn't as long anymore. It takes me between 1-2 seconds for the calendar to open. However, the calendar still doesn't open instantly.

**Comment by agneszitte** [comment]
Testing is not possible at the moment, it will be fixed when we move to .NET 8
Will need to be brought back to QA Review when testing is possible again

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
