### ISSUE TITLE
[Gallery][macOS] `DatePicker` - for Cupertino 'Cancel' and 'Done' button is not working in calendar

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7284]
### Current behavior

Uploading mm56 (mm56) - VNC Viewer 2021-10-05 14-52-12.mp4…

### Expected behavior

The cancel and done button should work.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "DatePicker" from the "Component" list.
4. Go to "Cupertino" section.
5. Click  "Set Date" option and see the calendar open to choose the date.
6. Choose the date on calendar and click on 'Cancel' or 'Done' Button.
7. Observe that For Cupertino 'Cancel' and 'Done' button is not working in calendar.

### Affected platforms

macOS

**Comment by nguyeenvy** [comment]
This issue also seems to have been resolved now. I think we can close this also. @sakshi173

**Comment by agneszitte** [comment]
Testing is not possible at the moment, it will be fixed when we move to .NET 8
Will need to be brought back to QA Review when testing is possible again

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
