### ISSUE TITLE
[Gallery][MacOS] `DatePicker` - the selected Date, Month and year on the calendar is not displaying at the right position

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7286]
### Current behavior

https://user-images.githubusercontent.com/74563602/136091103-048f9f07-df72-4b12-98a2-527600222425.mp4

### Expected behavior

The Calendar should work properly.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "DatePicker" from the "Component" list.
4. Go to "Fluent" or 'Cupertino' or 'Native' section.
5. Click "Set Date" option and see the calendar open to choose the date.
6. Observe that the selected Date, Month and year on the calendar is not displaying correctly. 

### Affected platforms

macOS

**Comment by nguyeenvy** [comment]
It doesn't seem to be an issue in MacOS anymore. Can you check if this issue can be closed ? @sakshi173 

![Image](https://github.com/unoplatform/uno/assets/54756963/bd8ab0a4-81b2-434a-90e2-6e3768bb1e96)

**Comment by agneszitte** [comment]
Testing is not possible at the moment, it will be fixed when we move to .NET 8

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
