### ISSUE TITLE
[Android] ContentDialog sizes and positions incorrectly when keyboard is open

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#7287]
### Current behavior

Both these issues occur with `Uno.UI.FeatureConfiguration.Popup.UseNativePopup = false`.

**Issue 1:**

Most of the time when the keyboard opens, the dialogs that contain a stackpanel in a scrollviewer with alternating textblocks/textboxes do not size correctly, instead they cram into a tiny space at the top of the screen. This is what the dialog looks like with the keyboard closed:

![image](https://user-images.githubusercontent.com/1700111/146535259-ee0e6a6f-5af1-44ef-ae87-083817ebd3c3.png)

This is what it usually looks like when the keyboard opens (~80% of the time):

![image](https://user-images.githubusercontent.com/1700111/146535430-c84884f3-da87-451e-a73b-3e3d5ddbf160.png)

And this is what it looks like when it occasionally sizes correctly:

![image](https://user-images.githubusercontent.com/1700111/146535369-c4d33ba5-3bc6-4248-aece-1b9d311db74c.png)

This problem occurs when targeting Android SDK 30 or 31. It does not happen when targeting 29. You can see the problem happening in my Uno Test app (https://github.com/mikernet/UnoTest2/) if you click Login and then open one of the business dialogs and click on some of the textboxes to show the keyboard. It might take a couple of keyboard showing/hidings for the layout issue to occur.

**Issue 2:**

If you target Android SDK 29 in the uno test app mentioned above, you can observe a different sizing issue. For some fields (i.e. Business Name) it sizes correctly, with the buttons fully visible at the bottom:

![image](https://user-images.githubusercontent.com/1700111/146540404-1ff2e2bf-fb30-4f96-8b10-aaab0362f4bf.png)

For other fields (i.e. Address), the dialog sizes incorrectly and the buttons become hidden behind the keyboard:

![image](https://user-images.githubusercontent.com/1700111/146540666-af28d631-1c8a-436d-84a3-590dcf1f2748.png)

### Expected behavior

Dialogs should always size correctly when the keyboard is open.

### Works on UWP/WinUI

Yes, also works fine on iOS and WASM.

### NuGet package version(s)

Uno.UI 3.11.0-dev.290, 4.0.11, 4.1.0-dev..135

### Affected platforms

Android

**Comment by mikernet** [comment]
I can't figure out where it places the dialog and why, it just seems to jump all over the place:


https://user-images.githubusercontent.com/1700111/137423617-51b9e951-3a17-45c1-ab48-0d3b490aa7ec.mp4

**Comment by mikernet** [comment]
As per my discord discussion with @jeromelaban, here is the test matrix for various SDK and Android version combinations and their associated dialog sizing/positioning problems:

**SDK 29 (4.0.11):**
Android 9 - Dialog does not resize
Android 10 - Dialog does not resize
Android 11 - Issue 2 above
Android 12 - Issue 2 above
 
**SDK 30 (4.0.11):**
Android 9 - Dialog does not resize
Android 10 - Dialog does not resize
Android 11 - Issue 1 above
Android 12 - Issue 2 above

**SDK 31 (4.1.0-dev.147):**
Android 9 - Dialog does not resize
Android 10 - Dialog does not resize
Android 11 - Issue 1 above
Android 12 - Issue 2 above

**Comment by mikernet** [comment]
I did a bit of digging and **Issue 1** still occurs regardless of whether `GetVisualBounds()` or `GetVisualBoundsLegacy()` is used on SDK >= 30:

https://github.com/unoplatform/uno/blob/574a441497e0e6faee8d389a3dbac1c40d4d7891/src/Uno.UI/UI/Xaml/Window.Android.cs#L83-L85

**Comment by davidjohnoliver** [comment]
@mikernet Maybe you've already discovered this, but the code that adjusts the dialog position is in the `ContentDialog.AdjustVisualStateForInputPane()` method. This method compares the onscreen bounds of the dialog box, with the bounds of the soft keyboard, and tries to apply a margin to place the former just on top of the latter. It may be that the calculations here are going awry for some reason.

**Comment by mikernet** [comment]
Thanks. Jerome suggested it might be an issue with the new `GetVisualBounds` and I was looking to hack a quick fix into the app before posting an update today, so I tried forcing the SDK version to 29 so that the legacy method was always used instead, which didn't change anything. If the issue is assigned to me I'll look deeper into it, just figured I would post that so whoever takes the issue has the info.

The other spot he indicated might be at fault is https://github.com/unoplatform/uno/blob/e560a535c79dc7de9092644f537742a4d07ec6ad/src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialogPopupPanel.cs#L52

**Comment by davidjohnoliver** [comment]
I've just pushed a fix for an iOS bug, it may be that it will also impact the Android behaviour (hopefully, positively): https://github.com/unoplatform/uno/pull/7975

**Comment by mikernet** [comment]
The odd thing is that the dialog size is different each time it opens. It's usually either pushed up or almost full height, but other times it's a bit less than full height and sometimes about half-height. I'm not 100% sure about the details of how the keyboard resize occurs when targeting SDK 30+ on Android 11 devices but it looked to me like it did a sliding animation that attempts to smoothly resize the application as the keyboard slides up. Maybe has something to do with the dialog layout getting stuck at whatever point during that animation it happens to read the size? You would think that would make the dialog too big and not too small though so I don't know.
