### ISSUE TITLE
[Wasm] Build fails with "The command line is too long"

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#7299]
Building on windows with a large set of assemblies and AOT enabled fails with the following message:

```
[00:04:15.3993840] The command line is too long.
```

yes, seems to be a different error on my end  @jeromelaban - here is my most recent binlog
[log.zip](https://github.com/unoplatform/uno/files/7296671/log.zip)

_Originally posted by @nor0x in https://github.com/unoplatform/uno/issues/6152#issuecomment-936974987_

**Comment by jeromelaban** [comment]
@nor0x There's no immediate workaround for this, aside from _maybe_ reducing the number of package dependencies, or using WSL.

**Comment by nor0x** [comment]
thanks for the fast response @jeromelaban. Pushing the limits of the command line here 😂
Could i use `<MonoRuntimeMixedModeExcludedAssembly` in the csproj to exclude some of my assemblies from being AOT compiled? Unfortunately WSL is currently not an option but i will do some investigations on it. Out of curiosity is WSL1, WSL2 or Windows faster for AOT builds?

**Comment by jeromelaban** [comment]
You may try removing additional assemblies from the list to make the command line shorter, yes.

As for WSL1/2 and Windows, there aren't not many improvements in build performance. Most of the time is spent in LLVM's linker, and you can try out [these options](https://github.com/unoplatform/Uno.Wasm.Bootstrap#emscripten-linker-optimizations-flags) as a tradeoff.

**Comment by jeromelaban** [comment]
This issue has been fixed in recent 4.0.x bootstrapper builds
