### ISSUE TITLE
[iOS/macOS] Application freezes when DataGrid contains data

### ISSUE THREAD

**Issue by trungnt2910** [unoplatform/uno#7319]
### Current behavior

Application freezes when `DataGrid` contains data, either statically added or through bindings.

![Screenshot](https://media.discordapp.net/attachments/550416151172087808/894462587956232222/unknown.png?width=2880&height=1080)

### Expected behavior

Applications should work.

### How to reproduce it (as minimally and precisely as possible)

Use the `UnoWCTDataGridSample` project.
[This](https://github.com/unoplatform/Uno.Samples/tree/master/UI/UnoWCTDataGridSample) one.

### Workaround

Found none.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Tested with
`Uno.UI` from 3.6.6 to 3.10.11
`Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid` from 6.1.0 to 7.0.0

### Affected platforms

iOS, macOS

### IDE

Visual Studio 2019, Visual Studio for Mac

### IDE version

16.11

### Anything else we need to know?

For the older `DataGrid`, version 6.1.0, included in the samples, the _headers_ do show, but the data does not. For the newer `DataGrid` version 7.0.0, the app freezes _entirely_.

**Comment by jeromelaban** [comment]
This issue is likely fixed in latest uno. Can you try again and let us know ?

**Comment by jeromelaban** [comment]
Can you specify which version of the datagrid you used?

**Comment by trungnt2910** [comment]
Latest Uno released version, `Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid` version 7.1.11.
