### ISSUE TITLE
how fix color to MonoAndroid11.0 

### ISSUE THREAD

**Issue by AbdalaMask** [unoplatform/uno#7354]
### Current behavior

![Screenshot_2021-10-18-19-48-02-74_82035d2206de15b869524a1397e9b25e](https://user-images.githubusercontent.com/37013638/137782391-611731d4-c13d-454e-b0c0-bb4f6478ccda.jpg)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

3.11.0-dev.428

### Affected platforms

Android

### IDE

Visual Studio 2019

### IDE version

16.11.5

### Anything else we need to know?

![image](https://user-images.githubusercontent.com/37013638/137782720-5f16a4bc-e6cd-48a3-b562-900394a6bfe8.png)
good working to Uwp

**Comment by jeromelaban** [comment]
Thanks for the report. There is not enough information for us to help.
