### ISSUE TITLE
Unable to run unoapp mac w/o installing .net core 3.1.100

### ISSUE THREAD

**Issue by tofutim** [unoplatform/uno#7370]
### Current behavior

Probably an update to the doc would help, but it is probably better if the solution is updated somehow.
https://github.com/unoplatform/uno/blob/master/doc/articles/get-started-vsmac.md/#L1

In following the instructions, I end up with an error in VS for Mac at the top indicating I must install .NET core 3.1.100. VS has already installed every .NET core version except that one (which is a Preview). Without doing so, the mac app cannot compile.

But as you can see from my Visual Studio for Mac about, every other version had been installed.
```
.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/5.0.402/Sdks
SDK Versions:
	5.0.402
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	3.1.414
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.300
	3.1.202
	3.1.200
```

### Expected behavior

Mac app should run out of the box if VS for Mac has already updated to the latest versions of .NET Core for both 3.1 and 5.x. Additional install from Microsoft should be unnecessary.

### Workaround

The installer for 3.1.100 is available here if someone needs it:
https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-3.1.0-macos-x64-installer

### NuGet package version(s)

5.9.0.7134

### Affected platforms

macOS

### IDE

Visual Studio for Mac

### IDE version

8.10.11

### Anything else we need to know?

Visual Studio Community 2019 for Mac
Version 8.10.11 (build 8)
Installation UUID: 70f29e16-c31e-43c0-ad27-770e21ab1441
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

Mono Framework MDK
Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

Roslyn (Language Service)
3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

NuGet
Version: 5.9.0.7134

Xamarin Designer
Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/5.0.402/Sdks
SDK Versions:
	5.0.402
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	3.1.414
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.300
	3.1.202
	3.1.200
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.11
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	3.1.20
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.4
	3.1.2
	2.1.23
	2.1.18
	2.1.17

.NET Core 3.1 SDK
SDK: 3.1.414

Xamarin.Profiler
Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 12.4 (17801)
Build 12D4e

Xamarin.Mac
Version: 7.14.0.27 (Visual Studio Community)
Hash: 2566861a9
Branch: d16-10
Build date: 2021-07-27 02:34:12-0400

Xamarin.iOS
Version: 15.0.0.6 (Visual Studio Community)
Hash: 2771277e0
Branch: xcode13-ios
Build date: 2021-09-23 10:36:08-0400

Xamarin.Android
Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/tim/Library/Android/sdk
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

Microsoft OpenJDK for Mobile
Java SDK: /Users/tim/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:30:50 UTC

Android Device Manager
Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:31:08 UTC

Build Information
Release ID: 810110008
Git revision: 5467245e1f99a0c8ccdd2acea02d16c3fb65c220
Build date: 2021-10-07 10:49:46-04
Build branch: release-8.10

Operating System
Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Tue Jun 22 19:49:55 PDT 2021
    root:xnu-6153.141.35~1/RELEASE_X86_64 x86_64

**Comment by jeromelaban** [comment]
Fixed in Uno 4.1
