### ISSUE TITLE
[iOS] Weird incorrect content placement and nesting

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#7380]
### Current behavior

Something within the last several dev releases is causing an odd behavior to happen with the placement of frame content and popup content on iOS occasionally (possibly other platforms as well but I haven't run into it yet).

For example, here is a screenshot of a test content dialog that contains text boxes and a button inserting its content inside what should be a filter textbox after it is closed:

![Simulator Screen Shot - iPhone 11 - 2021-11-17 at 07 21 37 (Phone)](https://user-images.githubusercontent.com/1700111/142215773-6afec4fc-3f85-47ec-b9c3-d99d048d6082.png)

Here the dialog content has replaced the tabs and most of the content that is supposed to be on that page:

![Simulator Screen Shot - iPhone 11 - 2021-11-17 at 07 21 57 (Phone)](https://user-images.githubusercontent.com/1700111/142216015-f9ce3e29-e346-459b-88d7-555b68a0d5ca.png)

This is what that page should look like:

![Simulator Screen Shot - iPhone 11 - 2021-11-17 at 07 23 16 (Phone)](https://user-images.githubusercontent.com/1700111/142216058-26693844-d228-4beb-98bc-98f841b4a39d.png)

### How to reproduce it (as minimally and precisely as possible)

If you run the following project in an iOS simulator and click around then eventually some content will pop into a place it shouldn't be: https://github.com/mikernet/UnoTest2

## Suggested Method A:

Go to the business employees tab and click on an employee to open the test dialog, then close the dialog and repeat. You can position the list such that the mouse is over both the OK button in the dialog and over an employee in the list so you can just keep clicking to open/close the dialog without repositioning the mouse.  After 5-20 times you will notice that the dialog content nests inside itself. This is what the dialog should look like:

![Simulator Screen Shot - iPhone 11 - 2021-11-17 at 14 46 30](https://user-images.githubusercontent.com/1700111/142271784-861b355b-c2aa-4e80-a240-724c2e3b0f34.png)

This is what it looks like when it dumps itself inside itself:

![Simulator Screen Shot - iPhone 11 - 2021-11-17 at 14 45 29](https://user-images.githubusercontent.com/1700111/142271832-27c9a145-d7ca-4e68-aa10-54dca702e40d.png)

Sometimes when you open the dialog it ALMOST looks ok but you can tell that the dialog content has been placed in the wrong spot in the visual tree when the `TextBox` text is missing (just like all the other times when it ends up in the wrong spot), like this:

![Simulator Screen Shot - iPhone 11 - 2021-12-03 at 03 46 15](https://user-images.githubusercontent.com/1700111/144573176-eff02428-4ccb-4faa-bda3-a840b5d00cf2.png)

## Suggested Method B:

Click Login, click "Business Dialog 1", click "Business Dialog 2", then click "Business Page" and follow the steps above to rapidly open and close the dialog by clicking on an employee in the employee list. Notice that within 5-20 clicks the business dialog content will show instead of the test dialog content.

---

In my actual app that has a more complex visual tree, the problem manifests almost immediately within 1 or 2 dialogs being shown.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

3.11.0-dev.468, 3.11.6, 3.12.0-dev.2, 4.0.0-dev.5526, 4.0.0-dev.5612
The problem **does not** occur on 3.11.0-dev.210

### Affected platforms

iOS

**Comment by mikernet** [comment]
I just updated to 3.11.0.-dev.476 and now when I click a button that opens a dialog the old login page from the outer frame pops inside the dialog content somehow😆

**Comment by mikernet** [comment]
Nevermind, this is still definitely an issue.

**Comment by mikernet** [comment]
Updated the issue with a sample project and more info. Uno is unusable on iOS right now with this bug.

**Comment by jeromelaban** [comment]
Thanks. I see that you're adding multiple scenarios in your test app, this make it difficult to determine what needs to be tested. If you can, attaching a repro to this issue in a zip file is preferable.

**Comment by mikernet** [comment]
I'm not sure I know what you mean. 

I can only reproduce this issue with multiple page navigations, controls on each page and controls on the dialogs. This is as simple as I can get it.

**Comment by jeromelaban** [comment]
Thanks. In all cases, even if the repro is complex, making an extract and attaching to the repo is best (you might modify/delete the repo later on).

It's still preferable to make simpler repros, when possible.

**Comment by mikernet** [comment]
I mean, I can zip it up if you want, but that repo and the setup to demonstrate the issues isn't going anywhere, I specifically set it up to report/demonstrate Uno issues and reference accordingly.

A zip of it is attached.
[UnoTest2-master.zip](https://github.com/unoplatform/uno/files/7650173/UnoTest2-master.zip)

**Comment by jeromelaban** [comment]
Thanks. I tried your test app, and I'm not able to reproduce the issue, but this looks like a template pooling issue.

Can you try by adding this:
```
FrameworkTemplatePool.IsPoolingEnabled = false;
```

**Comment by mikernet** [comment]
That does indeed appear to make the issue go away.

**Comment by mikernet** [comment]
> I'm not able to reproduce the issue

I can reproduce it every time without fail following the steps outlined above exactly. If you do things in a different order then sometimes the problem does not manifest.

**Comment by mikernet** [comment]
Just FYI, in case it helps: the issue was introduced sometime `> 3.11.0-dev.210 && <= 3.11.0-dev.468`

**Comment by mikernet** [comment]
Just FYI, as per my discussion with @jeromelaban, the issue goes away if I disable template pooling so it must be related to that:
```cs
#if __IOS__ 
            FrameworkTemplatePool.IsPoolingEnabled = false; 
#endif 
```

**Comment by jeromelaban** [comment]
We've been investigating this issue, and this seems to be related to the recycling of `ScrollViewer` control templates. A fix should be coming soon.
