### ISSUE TITLE
Add support for `TextBox.Description`

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/uno#7381]
### Current behavior

`TextBox` property `Description` does nothing
<img src="https://user-images.githubusercontent.com/2365592/138572445-55bd10f6-ca3c-4014-aad0-2b608a1a7219.png" alt="image" width="40%" style="max-width: 100%;"> <img src="https://user-images.githubusercontent.com/2365592/138572493-8f3e3499-66d2-4444-aad5-2cda45eeb041.png" alt="Screenshot_1635024722" width="40%" style="max-width: 100%;">

### Expected behavior

If `Description` property is set, then it is rendered under `TextBox` via `TextBlock` within a template
<img src="https://user-images.githubusercontent.com/2365592/138572440-684e31eb-c1cf-41ad-a06b-151f342912da.png" alt="image" width="40%" style="max-width: 100%;">

### How to reproduce it (as minimally and precisely as possible)

1. Create new project
2. Add `TextBox` to `MainPage`
3. Set `Description` property
4. Run

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

3.10.*

### Affected platforms

iOS, Android, WebAssembly, macOS, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen)

### IDE version

17.0 preview 5.0

**Comment by duke7553** [comment]
It does appear that there is in fact a difference between our Generic.xaml TextBox style and that included in Windows. I'll assign this to myself to test whether parity wrt. Description is feasible on all platforms.

**Comment by xperiandri** [comment]
👏👏👏
