### ISSUE TITLE
[Gallery][Android/Wasm] - in pressed state ripple doesn't fill the entire item.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7385]
### Current behavior

![ripple issue](https://user-images.githubusercontent.com/74563602/138734171-61b375dc-c2c1-4417-b19a-38f33a1a1107.png)

### Expected behavior

In pressed state ripple should fill the entire item.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right .
3. Click on any item on the "component" list.
4. Observe that in pressed state ripple doesn't fill the entire item.

### Affected platforms

Android

**Comment by nguyeenvy** [comment]
It seems fine on WASM and Android now. 

Can you check if this issue still persists or it can be closed? @sakshi173

**Comment by sakshi173** [comment]
This issue is resolved, closing it
