### ISSUE TITLE
[macOS][ComboBox] Selection popup stays active after being closed

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#7389]
### Current behavior

With the following XAML, opening the combobox popup then closing still allows to change the active selection with an invisible selection zone.

```xaml
    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <StackPanel>
            <TextBlock Text="Hello, world!" Foreground="Red" Margin="20" FontSize="30" />
            <ComboBox>
                <ComboBoxItem>Eggs</ComboBoxItem>
                <ComboBoxItem>Potatoes</ComboBoxItem>
                <ComboBoxItem>Fruit</ComboBoxItem>
            </ComboBox>
        </StackPanel>
    </Grid>
````

### Expected behavior

Selection only happens when the popup is active.

### Workaround

None

### Works on UWP/WinUI

Yes

### NuGet package version(s)

3.11-dev.x

### Affected platforms

macOS

**Comment by MartinZikmund** [comment]
This can also be reproduced with keyboard - open the box with Enter, then select and item and close it. Now you can still use arrows to change selection

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
