### ISSUE TITLE
[WASM] Custom font with number in `FontFamily` is not working

### ISSUE THREAD

**Issue by easy28** [unoplatform/uno#7395]
### Current behavior

I load & display custom woff2 font successfully to a wasm uno project,  except some FontFamily : 2Dumb  / 1942 report / Capture It 2   etc.    All these fonts have number in FontFamily.  These fonts can be displayed in Transfonter demo page, so I think it's an uno wasm problem.    Doing further research,  if I use 2Dumb woff2 font data, and uses a different FontFamily like "abcfont", it displays correctly.  

### Expected behavior

Load and display custom font with number in FontFamily correctly.

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.0.0-dev.5407

### Affected platforms

WebAssembly

### IDE

Visual Studio 2019

### IDE version

16.11.3 Preview 1.0

**Comment by CesarRabelo** [comment]
if add ' ' in name of font that start with numbers, browser render the font correctly, check the sample.

![image](https://user-images.githubusercontent.com/790876/157793096-9c17e1c1-cc23-4008-ae07-59f7e8d4b83b.png)


![image](https://user-images.githubusercontent.com/790876/157793013-d3857313-e66a-4ff5-ad5d-8d2534690d9c.png)

**Comment by carldebilly** [comment]
That would mean [we're doing it wrong in WindowManager](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/ts/WindowManager.ts#L544) when we're using the `style.setProperty` to set the font family.  (called from [here](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/UIElement.TextHelper.wasm.cs#L93))

**Comment by carldebilly** [comment]
That can't be the right solution.  I think the right way to do it would be to set the `fontFamily` property instead of calling the `setProperty` in javascript.

Can you try to set the follwing code in the TypeScript file?
``` javascript
element.style[style] = styles[style];
```

there: https://github.com/unoplatform/uno/blob/master/src/Uno.UI/ts/WindowManager.ts#L544

**Comment by CesarRabelo** [comment]
@carldebilly I tried your suggestion and continuous with the same behavior. If I don't put quotation marks the custom font is not updated.

![sample-font-family](https://user-images.githubusercontent.com/790876/158427860-fd71e69d-9c50-4c88-acc2-5383b594e627.gif)

**Comment by jeromelaban** [comment]
This issue is fixed with the latest Uno font management: https://playgroundcanary.z19.web.core.windows.net/#a48b5af8
