### ISSUE TITLE
Detecting the host system ?

### ISSUE THREAD

**Issue by JanabiSoft** [unoplatform/uno#74]
1. Is there a way to detect which OS or platform is running my app ?
2. Does Uno support compiler directives like:  #if __ANDROID__ or similar approach.

**Comment by jeromelaban** [comment]
Most of the time, the conditional compilation directives are enough, and those are the ones provided by Xamarin, by default:  `__ANDROID__`, `__IOS__`. For Wasm, it's defined manually as `__WASM__` until nuget supports it properly.

Also, part of the information [can be found here in RuntimeInformation](https://github.com/mono/mono/blob/90b49aa3aebb594e0409341f9dca63b74f9df52e/mcs/class/corlib/System.Runtime.InteropServices.RuntimeInformation/RuntimeInformation.cs#L47)

**Comment by queequac** [comment]
Just answers the second issue for compiler directives... regarding the first question, it would be quite cool if you could add support for `Windows.System.Profile.AnalyticsInfo`, providing information about the OS and it's version.
DeviceFamily for example holds "Windows.Mobile", "Windows.Xbox" and so on. Why not add adding "Android" or even "Android.Mobile" there?

**Comment by davidjohnoliver** [comment]
This has been implemented! (https://github.com/unoplatform/uno/pull/1970 and https://github.com/unoplatform/uno/pull/2574)
