### ISSUE TITLE
GetFolderFromPathAsync support for known folders in WASM Native File System 

### ISSUE THREAD

**Issue by Arlodotexe** [unoplatform/uno#7401]
## What would you like to be added:
Support for the [GetFolderFromPathAsync](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder.getfolderfrompathasync?view=winrt-22000) API for folders that the app has browser permission to access (internal , or to access known picked folders.

## Why is this needed:
In our app, we allow the user to pick a folder to look in for music. When the app is restarted, this folder is remembered by persisting its' path across restarts so we can play from and re-scan music in that folder. Without this API, we can't scan music in the picked folder or remember it between app restarts.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
Out of curiosity - you mention you use this API with picked folders too - I would presume you would need to have `FutureAccessList` as well (unless you use broad filesystem access capability), is that correct?

**Comment by Arlodotexe** [comment]
@MartinZikmund I assume it'd be easiest to implement them both at the same time, but for our purposes we only need this API.

**Comment by MartinZikmund** [comment]
After further review I found out this is currently unfortunately not possible. The JS [File System Access API](https://wicg.github.io/file-system-access/#introduction) does not seem to provide any way to directly access or work with file system paths. It is possible to set the file picker to start in one of the known folders (desktop, pictures, etc.), but still cannot access them directly without user intervention. The solution here will be to use file picker and then persist the access using `FutureAccessList` API (at least until a way to work with file paths exists in the JS API. For now I am closing this in favor of https://github.com/unoplatform/uno/issues/5343, will prioritize that one for WASM.
