### ISSUE TITLE
StorageFile.OpenAsync() support for native file system

### ISSUE THREAD

**Issue by Arlodotexe** [unoplatform/uno#7403]
## What would you like to be added:
Support for the [StorageFile.OpenAsync](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.openasync?view=winrt-22000#Windows_Storage_StorageFile_OpenAsync_Windows_Storage_FileAccessMode_) method when running on WASM and interacting with the Native File System.

## Why is this needed:
In our app, we allow the user to pick a folder that they'd like to play music from. We must also be able to read data from these files in order to get metadata and display them.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
Can you add some code sample please? The `OpenAsync` method should be implemented.

**Comment by Arlodotexe** [comment]
Tried to get a minimal repro, and you're right, it is! Looks like I'm running into problems with TagLib#. Thanks
