### ISSUE TITLE
Offer: Docs markdown linting and spell-checking for PRs

### ISSUE THREAD

**Issue by SeanKilleen** [unoplatform/uno#7422]
I thought I would offer this in case it's useful.

I've added markdown linting and spellchecking to the NUnit docs, [the akka.net docs](https://github.com/akkadotnet/akka.net/issues/5312), and the [Marten docs](https://github.com/JasperFx/marten/issues/1919). 

This is typically done by adding a parallel job that runs the node tooling, and all of the corrections that go with a tool (the Akka .NET issue shows how I'd take this step by step).

## Proposed Steps

* [ ] Add spell-checking via cSpell #10080 
* [ ] Add markdown lint GitHub action with all rules explicitly disabled in config
* [ ] Subsequent PRs to enable rule(s) along with their fixes.

**Comment by jeromelaban** [comment]
Thanks Sean! Indeed that would be very interesting!

**Comment by Youssef1313** [comment]
I made a small progress in https://github.com/Youssef1313/uno/tree/markdownlint, anyone is welcome to work on top of it.

**Comment by MartinZikmund** [comment]
@SeanKilleen Are you planning to work on the markdown linting?

**Comment by SeanKilleen** [comment]
@MartinZikmund whoops, sorry about that! I'll bump this back up to the top of my radar.

**Comment by MartinZikmund** [comment]
No worries, was just walking through the backlog to make sure issues are still current 😊

**Comment by SeanKilleen** [comment]
@MartinZikmund double-oops! This was already completed in #10080 back in October. It was linked to this but didn't close the issue, and I forgot it was already done because I had done several projects at the same time 😅 

Going to go ahead and close this out. 👍

**Comment by SeanKilleen** [comment]
Annnnd re-opening because I realized we're talking about markdown linting and not spelling. 🤦‍♂️
