### ISSUE TITLE
Localized text resources not visible when project is in a folder with a Culture code name, e.g. "SW"

### ISSUE THREAD

**Issue by maaxe** [unoplatform/uno#7431]
### Current behavior

Localized text resources not visible if project is created in a folder with culture code name (i've tested with SW, en, pl)

### Expected behavior

Localized text resources visible

### How to reproduce it (as minimally and precisely as possible)

- Create a new project using the Multi-Platform template, in a folder with a culture code name, e.g "SW".
- Add x:Uid to a Textblock
- Add some text to the Resources file

### Workaround

Dont put project in a folder with a coulture code name :)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

v3.10.11

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2019

### IDE version

16.9.4

**Comment by jeromelaban** [comment]
Thanks for the report!

**Comment by Youssef1313** [comment]
Related: https://github.com/unoplatform/uno/issues/4657
