### ISSUE TITLE
Adaptive trigger is showing different behavior in WASM and UWP. (Incorrect behavior on WASM)

### ISSUE THREAD

**Issue by amaid** [unoplatform/uno#7439]
### Current behavior

The VisualStateTrigger loads incorrect size of the UIElement on WASM, loads correctly on the UWP app. 
This happens when MinWindowWidth is defined in two different state triggers under the same VisualStateGroups.

![image](https://user-images.githubusercontent.com/15306909/140612216-1379fdbc-462e-4957-8549-7569afffb5d5.png)

### Expected behavior

Both heads (UWP and WASM) should show same behavior if eff multiple MinWindowWidths are applied.

![image](https://user-images.githubusercontent.com/15306909/140612291-42969d32-2049-450c-b3aa-6be2ceeebf88.png)

### How to reproduce it (as minimally and precisely as possible)

1. Create an empty new uno project. 
2. Create visual state groups. 
3. One for small size and other for large size screen.
4. Create adaptive triggers for each.
5. Define the MinWindowWidths for adaptive trigger.
The xaml should look like this:

```xaml
 <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <VisualStateManager.VisualStateGroups>
            <VisualStateGroup x:Name="Sizes">
                <VisualState x:Name="Small">
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger  MinWindowWidth="0"/>
                    </VisualState.StateTriggers>
                    <VisualState.Setters>
                        <Setter Target="PART_Grid.Width" Value="100"/>
                    </VisualState.Setters>
                </VisualState>
                <VisualState x:Name="Large">
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger  MinWindowWidth="600"/>
                    </VisualState.StateTriggers>
                    <VisualState.Setters>
                        <Setter Target="PART_Grid.Width" Value="500"/>
                    </VisualState.Setters>
                </VisualState>
            </VisualStateGroup>
        </VisualStateManager.VisualStateGroups>

        <Grid x:Name="PART_Grid" Height="100" Background="Blue">
        </Grid>
    </Grid>
```

### Workaround

There are two workarounds (WASM):

1. Remove the MinWindowWidth from  VisualStateTrigger of "Small" VisualStateGroup,  so its not picked up by first. 

OR

2. Move the "Large" size VisualStateGroup to before the "Small" size VisualStateGroup.

### Works on UWP/WinUI

Yes

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022, Visual Studio 2019

### IDE version

4.8.04084

**Comment by jeromelaban** [comment]
Thanks for the report. This is indeed a behavior that is incorrect when comparing with WinUI.

**Comment by MatFillion** [comment]
most likely same as this issue https://github.com/unoplatform/uno/issues/2662

**Comment by jeromelaban** [comment]
Indeed, let's close this one.

**Comment by amaid** [comment]
> Indeed, let's close this one.

Ah yeah, it looks like #2662 is the same issue.
