### ISSUE TITLE
`InfoBar` icon on WinUI V2 styles does not have colorful background

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#7442]
### Current behavior

`InfoBar` on WinUI V2 uses two font icons superimposed on top of each other to render a color-white or color-black icon. Unfortunately, Uno does not have the same icon font so the colorful background is missing.

### Expected behavior

Icons of `InfoBar` should be colorful:

![image](https://user-images.githubusercontent.com/1075116/140660519-12a197e9-9890-4bba-a47b-35e66fef2fde.png)
![image](https://user-images.githubusercontent.com/1075116/140660524-92fe2cae-f20c-43c1-afc8-377313dd1236.png)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

iOS, Android, WebAssembly, WebAssembly renderers for Xamarin.Forms, macOS, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen)

**Comment by xperiandri** [comment]
Indeed
![Screenshot_1650310901](https://user-images.githubusercontent.com/2365592/163866979-2628a0bb-fc12-4e3e-b4d4-382551d5a638.png)

**Comment by Marc-Antoine-Soucy** [comment]
Wasm
![image](https://github.com/unoplatform/uno/assets/90481654/f0c589b9-6101-4d4d-9f04-87b157535f93)
android
![image](https://github.com/unoplatform/uno/assets/90481654/0eed9161-e359-4eaf-9568-87962232d5de)
ios: 
![image](https://github.com/unoplatform/uno/assets/90481654/97a2394c-c287-4ec9-8663-8457d0596494)
seems to be fine
