### ISSUE TITLE
Using `ContentPresenter` as `ListViewItem` template is not working 

### ISSUE THREAD

**Issue by Arlodotexe** [unoplatform/uno#7446]
### Current behavior

Nothing is rendered

![image](https://user-images.githubusercontent.com/9384894/140784544-5d94511c-99e7-4607-b937-8491de889e6f.png)

### Expected behavior

Items should render the same as it does on UWP.

![image](https://user-images.githubusercontent.com/9384894/140784580-801d77b4-7350-4f4f-af6a-947b584417cd.png)

### How to reproduce it (as minimally and precisely as possible)

On a ListView, set the item container style to:

```xaml
<ListView.ItemContainerStyle>
    <Style TargetType="ListViewItem">
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="ListViewItem">
                    <ContentPresenter />
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>
</ListView.ItemContainerStyle>
```

Minimal repro on the Uno Playground:
https://playground.platform.uno/#f419ea68

### Workaround

Remove the template setter

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI.WebAssembly Version 3.10.11

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022, Visual Studio 2019

**Comment by davidjohnoliver** [comment]
You're running afoul of this issue: https://github.com/unoplatform/uno/issues/857

The workaround is to explicitly bind the Content and ContentTemplate on the ContentPresenter:
```xml
                            <ControlTemplate TargetType="ListViewItem">
                                <ContentPresenter Content="{TemplateBinding Content}" ContentTemplate="{TemplateBinding ContentTemplate}" />
                            </ControlTemplate>
```

**Comment by Arlodotexe** [comment]
> You're running afoul of this issue: #857
> 
> The workaround is to explicitly bind the Content and ContentTemplate on the ContentPresenter:
> 
> ```
>                             <ControlTemplate TargetType="ListViewItem">
>                                 <ContentPresenter Content="{TemplateBinding Content}" ContentTemplate="{TemplateBinding ContentTemplate}" />
>                             </ControlTemplate>
> ```

@davidjohnoliver So this fixed our issue on WASM, but it also causes a crash on UWP when the debugger isn't attached, somehow. 

Had trouble using platform-specific code in the style setters, so we'll have to just remove the template setter for now.
