### ISSUE TITLE
[WASM] AppBarButton Label is not visible

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#7459]
### Current behavior

![image](https://user-images.githubusercontent.com/3002068/141124855-37217242-6254-48e0-9b1c-40aa49eb73a1.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/3002068/141125132-03a2fc97-a709-48ef-a579-7ed247aee8db.png)

### How to reproduce it (as minimally and precisely as possible)

http://playground.platform.uno/#958be021

```xml
<CommandBar
    DefaultLabelPosition="Right"
    Margin="5"
    HorizontalAlignment="Left"
    >
    <AppBarButton
        Label="Open"
        Icon="OpenFile"
        />
    <AppBarButton
        Label="Reload (discard unsaved changes)"
        Icon="Refresh"
        />
    <AppBarSeparator/>
    <AppBarButton
        Label="Save"
        Icon="Save"
        />
    <AppBarButton
        Label="Save As"
        Icon="SaveLocal"
        />
</CommandBar>
```

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

3.12.0-dev.2

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.1 preview

**Comment by jeromelaban** [comment]
This was fixed in Uno 4.0  (thanks @kazo0), though the playground is not yet updated.

![image](https://user-images.githubusercontent.com/5839577/144615357-afc40d12-52ee-4ff2-abe1-27eff2993cae.png)
