### ISSUE TITLE
ContentDialog does not remove translucent overlay when calling Hide()

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#7463]
### Current behavior

Before opening ContentDialog:
![2021-11-10_09-26-15-PM](https://user-images.githubusercontent.com/4793020/141226353-2ed4bb1f-ced2-461d-b77f-939f44b6a2ee.png)

Opened ContentDialog
![2021-11-10_09-26-24-PM](https://user-images.githubusercontent.com/4793020/141226356-505c5fe6-1520-4999-a546-81812ecfa6ce.png)

After calling ContentDialog.Hide()
![2021-11-10_09-26-29-PM](https://user-images.githubusercontent.com/4793020/141226357-656b88bb-13bb-4a66-978c-be21db6efd3b.png)

### Expected behavior

Should no have the overlay visible and page beneath should be able to receive pointer events

### Works on UWP/WinUI

Yes

**Comment by davidjohnoliver** [comment]
That's weird! Do you notice any exceptions when calling Hide() that would interrupt the process?

**Comment by kazo0** [comment]
> That's weird! Do you notice any exceptions when calling Hide() that would interrupt the process?

Nope

**Comment by davidjohnoliver** [comment]
@kazo0 and I are no longer able to repro this, closing.
