### ISSUE TITLE
Platform-specific XAML markup won't work on WCT DataGrid

### ISSUE THREAD

**Issue by mcocaroUX** [unoplatform/uno#7468]
### Current behavior

I get "XamlCompiler error WMC0011: Unknown member 'Margin' on element 'DataGrid'" when using xmlns:win="http://schemas.microsoft.com/winfx/2006/xaml/presentation". This only happens on my UWP project. It builds and runs on iOS

### Expected behavior

UWP progect builds correctly and Margin is applied

### How to reproduce it (as minimally and precisely as possible)

Just try to build this code

            <controls:DataGrid
                x:Name="dataGrid"
                ios:Margin="30,20"
                win:Margin="15"
                ItemsSource="{Binding Reports}"
                AutoGenerateColumns="False"
                GridLinesVisibility="Horizontal"
                HorizontalGridLinesBrush="{StaticResource SeparatorColor}"
                CanUserReorderColumns="False"
                RowHeight="55"/>

### Works on UWP/WinUI

No

### Environment

Other

### NuGet package version(s)

Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid v7.0.0 -iOS
Microsoft.Toolkit.Uwp.UI.Controls.DataGrid v7.0.0 -UWP

### Affected platforms

Windows

### IDE

Visual Studio 2019

### IDE version

Version 16.11.6

### Relevant plugins

None

**Comment by Youssef1313** [comment]
Can you try `win:OWNER.Margin` instead of `win:Margin`? For example:

```xaml
        <controls:DataGrid
            x:Name="dataGrid"
            ios:Margin="30,20"
            win:FrameworkElement.Margin="15"
            ItemsSource="{Binding Reports}"
            AutoGenerateColumns="False"
            GridLinesVisibility="Horizontal"
            HorizontalGridLinesBrush="{StaticResource SeparatorColor}"
            CanUserReorderColumns="False"
            RowHeight="55"/>
```

**Comment by MartinZikmund** [comment]
This can be worked around by adding a `Border` with given `Padding` around the element. Closing for now, as the issue arises on Windows, which is not in our control.
