### ISSUE TITLE
Project sqllit WebAssembly not working

### ISSUE THREAD

**Issue by AbdalaMask** [unoplatform/uno#7469]
### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by AbdalaMask** [comment]
https://user-images.githubusercontent.com/37013638/141499660-45ad82c1-96e0-41dc-a414-447cb20566b8.png

**Comment by AbdalaMask** [comment]
![141499660-45ad82c1-96e0-41dc-a414-447cb20566b8](https://user-images.githubusercontent.com/37013638/141608977-f551ec5f-1042-42cb-b812-4f3967eb881d.png)

**Comment by jeromelaban** [comment]
Duplicate of https://github.com/unoplatform/uno/issues/7469

**Comment by AbdalaMask** [comment]
How

**Comment by AbdalaMask** [comment]
https://user-images.githubusercontent.com/37013638/141499660-45ad82c1-96e0-41dc-a414-447cb20566b8.png
