### ISSUE TITLE
XAML Hot Reload does not work with VS 2022

### ISSUE THREAD

**Issue by chingucoding** [unoplatform/uno#7470]
### Current behavior

Editing a XAML file while the app is running and saving said file does not update the rendered output (tested with UWP head). This behavior is newly present with VS 2022, VS 2019 worked fine.

### Expected behavior

Hot Reload should work as in VS 2022

### How to reproduce it (as minimally and precisely as possible)

1. Create new Multiplatform Uno App (with UWP head)
2. Start the UWP head
3. Edit XAML and save file

### NuGet package version(s)

Uno.Core: 2.4.0
Uno.UI 3.10.11

### IDE

Visual Studio 2022

### IDE version

17.0.0

### Anything else we need to know?

Seems like a regression from VS 2019 where hot reload with shared projects did not work properly.

**Comment by jeromelaban** [comment]
XAML hot reload works properly in VS2022, though you still have to follow this: https://platform.uno/docs/articles/get-started-vs.html#make-sure-xaml-intellisense-is-enabled

**Comment by chingucoding** [comment]
Oh, you are totally right, thank you! Sorry about the confusion, closing now.
