### ISSUE TITLE
Support for special URIs

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#748]
## I'm submitting a...
- Feature request

## Current behavior
Special URIs like `ms-settings` etc. are not supported by the `Launcher.LaunchUriAsync` API.

## Expected behavior
When special URIs are passed into `Launcher`, the appropriate system app is launched on Android and iOS.

## Environment
Nuget Package: Latest

Package Version(s): Latest

Affected platform(s):
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by MartinZikmund** [comment]
Would you agree this would be useful addition?

**Comment by TopperDEL** [comment]
I think it would - as this would help with the "just do it like on UWP an it works"-flow.

**Comment by jeromelaban** [comment]
That would be interesting indeed. Which ones are you using ?

**Comment by MartinZikmund** [comment]
I hit it with `ms-settings`, but I guess there are other which could be implemented as well like `ms-sms` or `ms-call`

**Comment by MartinZikmund** [comment]
I have started working on this as well.

**Comment by carldebilly** [comment]
We should dress a list of interesting urls to implement.

**Comment by MartinZikmund** [comment]
@carldebilly I already had `ms-settings` implemented, made #2040 for this

**Comment by MartinZikmund** [comment]
Leaving this unassigned for now, maybe more special URIs can be implemented in the future.

**Comment by MartinZikmund** [comment]
Closing this as no other interesting special URIs are waiting to be implemented, separate issues can opened for specific use cases
