### ISSUE TITLE
Nullable Value Type bindings are broken

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#7486]
### Current behavior

As an example, a `char?` property on a user control bound to a `char?` on a view model in an `ItemsControl` or `ItemsRepeater` seems to get set correctly at first but then gets messed up when you scroll the list up and down or filter the list dynamically.

The employee list in the test project starts off like this:

![Simulator Screen Shot - iPhone 11 - 2021-11-17 at 08 48 37 (Phone)](https://user-images.githubusercontent.com/1700111/142214265-bd497f73-b02b-49c5-8b65-9a4a93150262.png)

After scrolling up and down a bunch of times or filtering the list and clearing the filter, it shows like this:

![Simulator Screen Shot - iPhone 11 - 2021-11-17 at 08 48 49 (Phone)](https://user-images.githubusercontent.com/1700111/142214396-74b37f1a-f6be-46a1-a865-b128b720d166.png)

### How to reproduce it (as minimally and precisely as possible)

See here for the `ItemsRepeater` that has a binding for a `char? ImageId`:

https://github.com/mikernet/UnoTest2/blob/cc371c25e3677aa81b8751967626cf7331fafffe/Source/UnoTest.Shared/Pages/BusinessPage.xaml?_pjax=%23repo-content-pjax-container#L101

Run the project in the iOS simulator. Click the `Login` button and then the `Business` button to get to the business page, then switch to the `Employees` tab. You can either scroll the list up and down until the images get messed up or you can type in `b` in the filter box, then backspace to clear the filter. Each time you do this the image list gets more messed up.

Here is different example that also does not work but seems related, this time with a `DateTime` control property bound to another control's `DateTime?.Value` property:

```xml
<CalendarDatePicker Name="StartDatePicker" />
<CalendarDatePicker Name="EndDatePicker" MinDate="{x:Bind StartDatePicker.Date.Value, Mode=OneWay}"/>
```

Notice that the minimum date in the second date picker does not get set.

### Workaround

None

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Every version I have tried, including `4.x-dev.latest`,  `3.11.0-dev.210`, `3.11.0-dev.476` and `3.11.6`.

### Affected platforms

iOS, Android, WebAssembly

**Comment by mikernet** [comment]
This may be a general problem with nullable value type bindings (the ImageId is a `char?` in this case).

**Comment by mikernet** [comment]
Updated with date picker example that may be related and easier to debug.

**Comment by mikernet** [comment]
Binding like this:
```cs
class Model : SomeNotifyPropChangedImplementation
{
    public List<SomeEnum> Items = new () { SomeEnum.A, SomeEnum.B };
    public SomeEnum SelectedItem { get; set; } // Notification property
}
```
```xml
<ComboBox ItemsSource="{x:Bind Model.Items}" SelectedItem="{x:Bind SelectedItem, Mode=TwoWay}"/>
```
Makes the program very grumpy:
```
![image](https://user-images.githubusercontent.com/1700111/143377304-0959723c-04e6-413c-a029-39bf90d32fde.png)
```

**Comment by hawkerm** [comment]
Ran into an issue with WASM and making a record type DependencyProperty nullable as well. Without the nullable, it works fine. With the nullable it only worked in UWP, but not WASM.

```cs
     //// Record backing data type
     public readonly record struct MyRecord(string OtherProperty);

     //// Dependency property using it in UserControl
     public MyRecord? MyProperty
        {
            get { return (MyRecord?)GetValue(MyPropertyProperty); }
            set { SetValue(MyPropertyProperty, value); }
        }

        public static readonly DependencyProperty MyPropertyProperty =
            DependencyProperty.Register(nameof(MyProperty), typeof(MyRecord?), typeof(MyUserControl), new PropertyMetadata(null, DataReady));

     //// Bind to it in XAML
     {x:Bind MyProperty.Value.OtherProperty, Mode=OneWay}
```

If I make the DP not nullable and bind with `MyProperty.OtherProperty` it works fine.
