### ISSUE TITLE
[iOS] CommandBar doesn't show contents

### ISSUE THREAD

**Issue by pdecostervgls** [unoplatform/uno#7492]
### Current behavior

I get a page with a red-backgrounded CommandBar, with no title or buttons.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/47024956/142458885-daa1c9a4-615f-4daa-b2dc-eac9b9ed957d.png)

For the sake of easy glancebility on GitHub, this is the page's XAML:
```xaml
<Page
    x:Class="UnoTestApp1.AlphaPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:UnoTestApp1"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:controls="using:Microsoft.UI.Xaml.Controls"
    xmlns:unotk="using:Uno.UI.Toolkit"
    mc:Ignorable="d unotk"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <Page.Resources>
        <Style TargetType="CommandBar">
            <Setter Property="Background" Value="Red"/>
            <Setter Property="unotk:VisibleBoundsPadding.PaddingMask" Value="Top" />
        </Style>
    </Page.Resources>
    <Grid unotk:VisibleBoundsPadding.PaddingMask="All">
        <Grid.RowDefinitions>
            <RowDefinition Height="auto"/>
            <RowDefinition Height="auto"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <CommandBar Grid.Row="0" Content="Hello World">
            <AppBarButton Label="test"/>
        </CommandBar>
        <TextBlock Grid.Row="1">Hello World</TextBlock>
        <FontIcon Grid.Row="2" HorizontalAlignment="Center" VerticalAlignment="Center" Glyph="&#x03B1;" FontSize="128" />
    </Grid>
</Page>
```

### Expected behavior

I should get a page with a red-backgrounded CommandBar with a title and button.

### How to reproduce it (as minimally and precisely as possible)

[UnoTestApp1.zip](https://github.com/unoplatform/uno/files/7564412/UnoTestApp1.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI: 3.11.6

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.0.0

**Comment by jeromelaban** [comment]
You'll need to follow this documentation: https://platform.uno/docs/articles/features/native-frame-nav.html?q=Native%20Frame%20Navigation

You're missing that part, specifically:
```csharp
#if __IOS__ || __ANDROID__
            Uno.UI.FeatureConfiguration.Style.ConfigureNativeFrameNavigation();
#endif
```

It's not linked in the general appbar documentation, so we'll change that.

**Comment by jeromelaban** [comment]
It's also available in this article: https://platform.uno/docs/articles/guides/native-frame-nav-tutorial.html?q=native%20Frame%20navigation

**Comment by pdecostervgls** [comment]
Oh alright, I knew I was missing something :)

**Comment by pdecostervgls** [comment]
I've verified this is fixed now. Thanks!
