### ISSUE TITLE
TabViewItem doesn't render header text in Skia.Gtk and in WPF.Host

### ISSUE THREAD

**Issue by zipgenius** [unoplatform/uno#7495]
### Current behavior

The header text of a TabVIewItem is rendered only in UWP but not in Skia.Gtk or in WPF.

### Expected behavior

The header text should be rendered as in UWP

### How to reproduce it (as minimally and precisely as possible)

Just add a TabView and some TabViewItems in XAML.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

3.11.6

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

17.0.1

### Anything else we need to know?

Using .net 6.

[Test_Uno_App-master.zip](https://github.com/unoplatform/uno/files/7566266/Test_Uno_App-master.zip)

**Comment by jeromelaban** [comment]
This issue is fixed in latest master.
