### ISSUE TITLE
[WASM] Canvas inside SKSwapChainPanel is wrongly positioned on displays with scaling factor different than 100% 

### ISSUE THREAD

**Issue by SeRgI1982** [unoplatform/uno#7498]
### Current behavior

SKSwapChainPanel  is drawn correctly (green background) but canvas inside this panel is not aligned to the panel top border and right border.

The same offset effect happens on our production app.
[The link directs to the video](https://drive.google.com/file/d/1quaOEoibV7ePEnIcB7RQjtZhQ7lueYwo/view?usp=sharing) 

### Expected behavior

Skia canvas should be properly aligned to borders of SKSwapChainPanel

### How to reproduce it (as minimally and precisely as possible)

- go to Windows "Display Settings",
- in section "Scale and layout" change scale to something different than 100% for ex. 125% or 150%,
- open UNO SkiaSharpTest sample,
- unload all projects except Wasm and Shared
- update UNO packages to the latest stable version (happens also on preview version or version delivered with the sample)
- if you wish you can try also update SkiaSharp packages to the latest preview version,
- to better visualize the issue, change radius to 25 in MainPage.xaml.cs in canvas.DrawCircle command
- build solution,
- Start Debugging/Start Without Debugging,
- mark checkbox 'Hardware Accelerated'
- move mouse to the top border or right border,
- SKSwapChainPanel  is drawn correctly (green background) but canvas inside this panel is not aligned to the panel top border and right border 

### Workaround

I have noticed that when I added this line:

 "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}"

to the launchSettings.json it started to work correctly when I hit 'Start Debugging'.
For 'Start without Debugging' the issue still exists.

What is more: it behaves randomly on different browsers (latest Chrome, latest Edge) and different machines (reported by other developers)

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

**[1.1.1]**  Microsoft.Extensions.Logging.Console 
**[1.1.1]**  Microsoft.Extensions.Logging.Filter
**[5.0.1]**  Microsoft.Windows.Compatibility
**[2.80.3]** SkiaSharp.NativeAssets.WebAssembly
**[2.80.3]** SkiaSharp.Views.Uno
**[3.11.6]** Uno.UI.WebAssembly
**[3.11.6]** Uno.UI.RemoteControl
**[3.0.0]**  Uno.Wasm.Bootstrap
**[3.0.0]**  Uno.Wasm.Bootstrap.DevServer

### Affected platforms

WebAssembly, Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022, Visual Studio 2019

### IDE version

VS 2022 (17.1.0 Preview 1.0), VS 2019 (16.11.6)

### Relevant plugins

VS 2019 with ReSharper version 2021.2.2
VS 2022 without ReShareper and with ReSharper version 2021.3 EAP 8

**Comment by Sasha111ua** [comment]
we also have same problem

**Comment by SeRgI1982** [comment]
I have 2 monitors (the same model - DELL U2515H)

1st monitor with resolution 2560x1440 and scaling factor 100%
2nd monitor with resolution 2560x1440 and scaling factor 125%

I have found why there is an offset for the canvas. 
SWSwapChainPanel has property ContentsScale which is taken into account during calculating space for SkiaCanvas which is a child of this panel. 
It should be calculated here:
 
https://github.com/mono/SkiaSharp/blob/80860aacf39a4ce9c403a36bd87ee414af1ba005/source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno/SKSwapChainPanel.cs#L101
 
but it seams that this logic is called only by OnLoaded method. 
OnDpiChanged is not called when I change display scaling factor or move browser window between monitors.

Based on where app was started, I am getting such values for DisplayInformation.GetForCurrentView()

1st monitor
[OnLoaded][ORIENTATION]=None | [RawDpi]=0x0 | [DiagonalSize]= | [CurrentOrientation]=Landscape | [Screen.Raw.Size]=2560x1440 | [RawPixelsPerViewPixel]=1 | **[LogicalDpi]=96** | [ResolutionScale]=Scale100Percent

2nd monitor
[OnLoaded][ORIENTATION]=None | [RawDpi]=0x0 | [DiagonalSize]= | [CurrentOrientation]=Landscape | [Screen.Raw.Size]=2048x1152 | [RawPixelsPerViewPixel]=1 | **[LogicalDpi]=96** | [ResolutionScale]=Scale100Percent 
 
As you can see, in both cases LogicalDpi is equal 96, so this is the reason why ContentsScale is always equal 1; 
 
I have made a workaround for this and it started to display canvas properly (set this property by reflection taking a proper value from JavaScript).
 
Still, there is a problem with mouse handling. 
It seams that my workaround was applied to display canvas properly but mouse click is still shifted and I don't know where it happens.

**Comment by SeRgI1982** [comment]
`CultureInfo.CurrentCulture`
[CULTURE]=pl (PL) [SEPARATOR=,]

1. `float.TryParse(WebAssemblyRuntime.InvokeJS("window.devicePixelRatio"), NumberStyles.Any, CultureInfo.CurrentCulture, out var devicePixelRatio)`
[CurrentCulture] Could not parse devicePixelRatio = 0

2. `float.TryParse(WebAssemblyRuntime.InvokeJS("window.devicePixelRatio"), NumberStyles.Any, CultureInfo.InvariantCulture, out var devicePixelRatio2)`
[InvariantCulture] Parsed devicePixelRatio = 1,25

3. `float.TryParse(WebAssemblyRuntime.InvokeJS("window.devicePixelRatio"), out var devicePixelRatio3)`
Could not parse devicePixelRatio = 0

The last approach is used by DisplayInformation.wasm.cs 
https://github.com/unoplatform/uno/blob/c78c7037a41eafc094743ebe122f480f43c912bb/src/Uno.UWP/Graphics/Display/DisplayInformation.wasm.cs#L136

Changing to approach no. 2 should fix the issue (I hope that mouse click offset also).

**Comment by jeromelaban** [comment]
Nice find! We'll definitely need to add analyzers to catch this kind of issues sooner. Thanks !
