### ISSUE TITLE
[WASM] Cannot build with Uno.SkiaSharp.Views package

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#7522]
### Current behavior

If trying to use Uno.SkiaSharp.Views building on Wasm will fail with the message, 'Unhandled exception. System.Exception: Could not resolve Uno.Core'

### Expected behavior

Uno.SkiaSharp.Views should not break build process

### How to reproduce it (as minimally and precisely as possible)

Attempt to build project, it will not build.  Removing references to Uno.SkiaSharp.Wasm/Uno.SkiaSharp.Build fixes build.
[App11.zip](https://github.com/unoplatform/uno/files/7590258/App11.zip)

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.0.0-dev.5650

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. This only happens with Uno 4.0-dev builds as there are binary breaking changes, and will be adjusted with updated builds of SkiaSharp.

**Comment by peternary** [comment]
@jeromelaban Is there any timeline for when updated SkiaSharp builds would be available?

**Comment by MartinZikmund** [comment]
@peternary Once we have stable 4.0 release, we will be able to do a SkiaSharp PR to update the dependency there 👍

**Comment by jeromelaban** [comment]
The PR is now available here: https://github.com/mono/SkiaSharp/pull/1873

**Comment by peternary** [comment]
Confirmed can build with latest SkiaSharp
