### ISSUE TITLE
[WASM] Sqlite not working

### ISSUE THREAD

**Issue by AbdalaMask** [unoplatform/uno#7524]
### Current behavior

![image](https://user-images.githubusercontent.com/37013638/143097446-f868ef6f-ccc5-4c38-89c5-7cddb6b7018a.png)
[HslStudio.zip](https://github.com/unoplatform/uno/files/7590798/HslStudio.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

WebAssembly

### IDE

Visual Studio 2019

**Comment by AbdalaMask** [comment]
not get data to textbox an combox
[٢٠٢١١١٢٣_٢٢٢٤٠١.zip](https://github.com/unoplatform/uno/files/7590841/_.zip)

**Comment by AbdalaMask** [comment]
![image](https://user-images.githubusercontent.com/37013638/143627719-b13dc527-4dd0-499f-b03c-02b3ae712f49.png)

**Comment by MartinZikmund** [comment]
Can you please provide more detailed information on what is not working? Currently we only have the screenshots and the repro sample, but that is not enough to understand what is actually happening. Ideally, provide step by step instructions.

**Comment by MartinZikmund** [comment]
Closing the issue for now as we would need further details. We have a SQLite sample here https://github.com/unoplatform/Uno.Samples/tree/master/UI/SQLiteSample, in case the issue persists, feel free to reopen and provide further repro steps.
