### ISSUE TITLE
Page OnNavigatedTo fires at the wrong time

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#7531]
### Current behavior

Given this code:
```cs
    public sealed partial class ModelAfterNavigatePage : Page
    {
        public AfterNavigateModel Model { get; private set; }

        public ModelAfterNavigatePage()
        {
            InitializeComponent();
        }

        protected override void OnNavigatedTo(NavigationEventArgs e)
        {
            Model = new AfterNavigateModel { Data = (int)e.Parameter };
        }
    }
```
```xml
<TextBlock Text="{x:Bind Model.Data}"/>
```
The model data will not show in the text block because the binding value is resolved before `OnNavigatedTo` fires.

### Expected behavior

Binding values should be resolved after page navigation so the text block should show the data.

### How to reproduce it (as minimally and precisely as possible)

See test project here: https://github.com/mikernet/UnoTest2/blob/f8b0fc2119f00869be436b1bb93c8482ba27b47d/Source/UnoTest.Shared/Pages/ModelAfterNavigatePage.xaml.cs

Click login and then click the "Model After Navigate" button, notice no value is shown in the text block.

### Workaround

Call `Bindings.Update()` or make `Model` a dependency property and set all the bindings to `OneWay`.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

3.x, 4.x-dev.latest.

### Affected platforms

iOS, Android, WebAssembly

**Comment by jeromelaban** [comment]
Thanks for the report. This issue is related to https://github.com/unoplatform/uno/issues/3519.
