### ISSUE TITLE
[Gallery][iOS]MessageDialog- For all the options of "MessageDialog" the Dialog Name is in all uppercase letters.(For other platform it is in lowercase letters.)

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7541]
### Current behavior

![messagedialog issue](https://user-images.githubusercontent.com/74563602/143625818-8c162100-e383-4296-99c0-0fa8ea6d7805.png)

### Expected behavior

![messagedialog correct](https://user-images.githubusercontent.com/74563602/143625836-4a18bc91-81d9-4440-802a-7292a32992e7.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "MessageDialog" from the "Features" list.
4. Observe that for all the options of "MessageDialog" the Dialog Name is in all uppercase letters.(For other platform it is in lowercase letters.)

### Affected platforms

iOS

**Comment by Youssef1313** [comment]
@sakshi173 The label platform/android seems wrong? or otherwise the title should mention android.

I'm also wondering how this can be related to MessageDialog specifically. These are just regular buttons which show MessageDialog when clicked.

**Comment by sakshi173** [comment]
@Youssef1313, sorry the label platform should be iOS, I have changed it.
I am not sure why it is with messageDialog only.

**Comment by Xiaoy312** [comment]
This is the expected behavior for all material buttons as introduced in unoplatform/Uno.Themes#661.

**Comment by Xiaoy312** [comment]
@sakshi173 Make sure that you update the uwp app used to determine the baseline behavior, as it should also be showing uppercase text.
