### ISSUE TITLE
how fix color this 

### ISSUE THREAD

**Issue by AbdalaMask** [unoplatform/uno#7546]
### Current behavior

![image](https://user-images.githubusercontent.com/37013638/143776617-a39d04b9-e302-4755-9070-3ef681ca3b7d.png)
help

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by AbdalaMask** [comment]
plase helppppppp

**Comment by pdecostervgls** [comment]
What is the problem here?
We don't have nearly enough information to begin helping you with this.

**Comment by AbdalaMask** [comment]
When you install the program on an Android phone, black colors appear in the tools
![143776617-a39d04b9-e302-4755-9070-3ef681ca3b7d](https://user-images.githubusercontent.com/37013638/144654700-71423008-6c04-46ec-a0e8-d7bd186635c9.png)

**Comment by AbdalaMask** [comment]
When installing the program on an Android tablet, the black colors do not appear in the tools
And it works well
![143776617-a39d04b9-e302-4755-9070-3ef681ca3b7d (1)](https://user-images.githubusercontent.com/37013638/144654975-6b3859d5-fd2c-4355-a15b-baeb979b6c0f.png)

**Comment by AbdalaMask** [comment]
![image](https://user-images.githubusercontent.com/37013638/144655061-23b0e58a-34d6-4592-a4cf-7973e0fdd623.png)
working to Uwp and WASM

**Comment by robloo** [comment]
It could be incorrect LinearGradientBrush stop/origin calculation. I've seen issues with gradients in the past several times. That said, it isn't clear if you are even using XAML here.

**Comment by AbdalaMask** [comment]
In this version 3.4 it works fine

**Comment by AbdalaMask** [comment]
plase help

**Comment by AbdalaMask** [comment]
The problem still exists in the new versions
