### ISSUE TITLE
[iOS][Android?] A white background is displayed during the transition to landscape or portrait mode (black on Android)

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/uno#7554]
### Current behavior

During rotation there is a white overlap.

![image](https://user-images.githubusercontent.com/64613932/143889195-e25c7da0-e452-4bea-8a60-95bb8f59c428.png)

![image](https://user-images.githubusercontent.com/64613932/143889260-7e3b0d85-b204-43a1-ba19-cf876406a096.png)

![image](https://user-images.githubusercontent.com/64613932/143889305-91e4ee89-0402-4a1a-b507-45b079fac594.png)

### Expected behavior

Either the App background is black or using the background color  of app.xaml or shell.xaml

### Workaround

None

[UnoApplicationTemplate.zip](https://github.com/unoplatform/uno/files/7619034/UnoApplicationTemplate.zip)

### NuGet package version(s)

Nventive.View.Uno 0.2.0-dev.9

### Affected platforms

iOS

### IDE

Visual Studio 2019

### IDE version

16.9.4

**Comment by jeromelaban** [comment]
This is likely the background of the Frame. Can you try changing it ?

**Comment by MaximeDion-Work** [comment]
Setting rootFrame.Background = new SolidColorBrush(Windows.UI.Colors.DeepPink); in OnLaunched from App.xaml.cs does not change the color of the white background.

**Comment by jeromelaban** [comment]
On iOS, native apps also have this behavior, so it's not necessarily something we can change. It could be something to change directly on the iOS Window instance.

**Comment by jeanplevesque** [comment]
@jeromelaban Could it be caused by this?
https://github.com/unoplatform/uno/blob/b7f19b08fd276155868e9a95c29714af80402945/src/Uno.UI/UI/Xaml/Window.iOS.cs#L43

**Comment by kazo0** [comment]
Setting the iOS Window Background to `UIColor.Clear` instead of `UIColor.White` makes it have black background which I feel like looks much better. I believe thats also the current behaviour for Android Uno apps as well.

![ios-rotate](https://user-images.githubusercontent.com/4793020/157476901-09eab295-2032-4e3f-a1f2-c7f2603d4af8.gif)

**Comment by jeanplevesque** [comment]
@kazo0 That already looks much better. Is this something apps can easily change from their code? If so, we could even use the app's material background color.

**Comment by kazo0** [comment]
@jeanplevesque 

The background color is set on the RootViewController's View. You should be able to grab the RootViewController from the Window with something like `Windows.UI.Xaml.Window.Current.Content.Window.RootViewController`. Maybe that will work?
