### ISSUE TITLE
Entity Framework Core not working with SQLite

### ISSUE THREAD

**Issue by AbdalaMask** [unoplatform/uno#7555]
### Current behavior

Entity Framework Core SQLite not working to
[DatabaseApplicationUno.zip](https://github.com/unoplatform/uno/files/7620297/DatabaseApplicationUno.zip)
 WebAssembly 

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by MartinZikmund** [comment]
We need more information than that it is not working, ideally step by step instructions on how to reproduce the issue.

**Comment by MartinZikmund** [comment]
Closing the issue for now as we would need further details. We have a SQLite sample here https://github.com/unoplatform/Uno.Samples/tree/master/UI/SQLiteSample, in case the issue persists, feel free to reopen and provide further repro steps.
