### ISSUE TITLE
Visual Issues with title in CommandBar

### ISSUE THREAD

**Issue by pdecostervgls** [unoplatform/uno#7558]
### Current behavior

When navigating back from a page, slowly with the back gesture, sometimes the CommandBar's text seems to be double, both moving at a different speed.
Take a look at the following .gif to see what I mean:
![mm_titlebar_gif](https://user-images.githubusercontent.com/47024956/144024673-692c576c-1978-434a-86aa-87f5ff2429e8.gif)

### Expected behavior

The transition from back button text to CommandBar title to be smooth and no double text to be visible.

### How to reproduce it (as minimally and precisely as possible)

I wasn't able to reproduce this with a clean project, because of the issues I am having with getting the CommandBar to properly render on iOS (https://github.com/unoplatform/uno/issues/7492). Therefore I deconstructed our production app to remove as much code as possbile while demonstrating the issue. It is availabe at:
[MMDeconstructed_uno.zip](https://github.com/unoplatform/uno/files/7624740/MMDeconstructed_uno.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

#### iOS:
Uno.UI: 3.5.1

#### UWP & Droid:
Uno.UI: 3.9.7

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.0.1

**Comment by jeromelaban** [comment]
@ajpinedam does it look familiar ? Maybe there two renderings of the same title element?

**Comment by pdecostervgls** [comment]
@jeromelaban @ajpinedam Should mention that updating to 3.11.6 made this issue disappear.

**Comment by jeromelaban** [comment]
We can close this issue then, otherwise you're seeing something specific.

**Comment by pdecostervgls** [comment]
Yep, sorry for wasting your time ;)
