### ISSUE TITLE
[Gallery][Wasm] Animation- For 'ScaleTransform' option after animation the Box is leaving the lines.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7560]
### Current behavior

![scaletransform](https://user-images.githubusercontent.com/74563602/144087447-4e2f3dea-2b8f-4904-9f65-3f0dbf8b74c4.png)

### Expected behavior

![scaletransform correct](https://user-images.githubusercontent.com/74563602/144087629-79aac8ba-4308-417c-9624-68c3f0679985.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "Animation" from the "Features" list.
4. Go to ScaleTransform section.
5. Tap on the Start button.
6. Observe that after animation the Box is leaving the lines.

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
This looks like a Chromium rendering issue, as it does not happen all the time.

**Comment by sakshi173** [comment]
As Jerome suggested above this issue is not able to fix due to that closed it.
