### ISSUE TITLE
[Gallery][Wasm] Chip- loading page for chip is very slow.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7562]
### Current behavior

loading page for chip is very slow.

### Expected behavior

Loading time should be similar to other controls.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP .
2. Click/tap Burger Menu on the left top right.
3. Click/tap "Toolkit" from the Burger Menu list
4. Click/tap on the "Chip" option.
5. Observe that Chip Page loading time is much more as compare to other Controls.

### Affected platforms

WebAssembly

**Comment by francoistanguay** [comment]
Latest changes will optimize that. Wont work on it specifically in the near future. Closing.
