### ISSUE TITLE
[Gallery][Wasm] Card - For Disabled Outlined card the text 'Disabled outlined' is truncating from the top.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7563]
### Current behavior

![card truncate issue](https://user-images.githubusercontent.com/74563602/144114217-861c313d-010c-4137-b466-59768e7e63ad.png)

### Expected behavior

The text should not truncate.

### How to reproduce it (as minimally and precisely as possible)

Open Uno Gallery APP .
Click/tap Burger Menu on the left top right.
Click/tap "Components" from the Burger Menu list
Click/tap on the "Card" option.
Observe that for Disabled Outlined card the text 'Disabled outlined' is truncating from the top.

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
I'm not seeing this, are you still able to reproduce @sakshi173?

**Comment by sakshi173** [comment]
@jeromelaban, Yes I am still able to reproduce it.
![card issue](https://user-images.githubusercontent.com/74563602/146578939-27c3876c-dfae-4b4d-b643-fe240293f49f.png)

**Comment by sakshi173** [comment]
Verified this issue with the latest canaries build and not able to reproduce it, due to that closing it.
![Card correct](https://user-images.githubusercontent.com/74563602/156843336-36fcf2a5-2e51-4f18-ab82-e384293e92c1.png)
