### ISSUE TITLE
[Gallery][Wasm] Combobox and Textbox(Material)- The star symbol is truncating for 'Combobox + Icon'  and 'With Icon' option.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7565]
### Current behavior

![combobox issue](https://user-images.githubusercontent.com/74563602/144115027-49050a11-f299-42df-9cd8-8d9056d8b593.png)

### Expected behavior

The Star sign display fully.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP .
2. Click/tap Burger Menu on the left top right.
3. Click/tap "Components" from the Burger Menu list
4. Click/tap on the "Combobox" option.
5. Observe that the star symbol is truncating for 'Combobox + Icon' option.

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
I cannot repro this issue. Does it still happen for you @sakshi173 ?

**Comment by sakshi173** [comment]
@jeromelaban, I am not able repro this issue now, due to that closing it.

**Comment by sakshi173** [comment]
Issue already fixed in Dec 2021, due to that closed it.
