### ISSUE TITLE
[Gallery][Wasm/iOS/Android] Flyout - For the Material 'Flyout' option the text is overlapping the whole screen.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7566]
### Current behavior

![Flyout issue](https://user-images.githubusercontent.com/74563602/144116384-4a5a3610-570c-4f65-bfc6-5d15ea7afd63.png)

### Expected behavior

The Text should display properly for the 'Flyout' option.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP .
2. Click/tap Burger Menu on the left top right.
3. Click/tap "Components" from the Burger Menu list
4. Click/tap on the "Flyout" option.
5. Click/tap 'Flyout' Button.
6. Observe that  for the Material 'Flyout' option the text is overlapping the whole screen.

### Affected platforms

iOS, Android, WebAssembly

**Comment by jeromelaban** [comment]
I can repro with the latest canary

**Comment by sakshi173** [comment]
**Verified with the latest canary, bug is fixed.**

![flyout correct](https://user-images.githubusercontent.com/74563602/158628528-9c6e777e-2044-4b10-83b7-728ee2b530e4.png)
