### ISSUE TITLE
[Figma] Cannot scroll source window horizontally

### ISSUE THREAD

**Issue by ConroyG** [unoplatform/uno#7568]
### Current behavior

I'm testing out the new figma plugin, it generates code correctly but I cannot use the horizontal scroll bar

### Expected behavior

To scroll when i try to use the horizontal bar

### How to reproduce it (as minimally and precisely as possible)

Open Figma then the uno platform material toolkit, pick any complex page and trigger the code gen, attempt to scroll

### Workaround

Resize the window so you no longer need to scroll

### Environment

Other

### Anything else we need to know?

This is on Firefox

https://user-images.githubusercontent.com/4994730/144167104-96ab9e26-8ad3-4b01-9f2d-f03ef4b097d0.mp4

**Comment by Xiaoy312** [comment]
re: https://github.com/unoplatform/Uno.Figma/issues/201
