### ISSUE TITLE
[WASM] Buttons and other active controls have "blue highlight" mobile browsers

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#7569]
### Current behavior

When a button or other clickable control is pressed with touch on mobile browser, it will get a blue highlight, which does not fit with the rest of the app design.

### Expected behavior

Should instead just follow visual states of the given element.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly, WebAssembly renderers for Xamarin.Forms

### IDE

Visual Studio 2022, Visual Studio 2019

**Comment by RadJKW** [comment]
Would like to add that this also applies to Skia.Gtk for both light and dark themes.
