### ISSUE TITLE
Uno 4 with Net6 - Mobile-Project "not compatible"

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#7570]
### Current behavior

I've updated my environment with the latest VS 2022 (17.0.2), ran uno-check until it's green and installed the uno VS templates. I then created a new project for uno with net6. It creates the project and I can see the "mobile"-project for android, ios and the others. After I close and reopen the solution, the project can't be loaded anymore with the message of being "not supported on this edition of Visual Studio". I'm using the community edition and would expect it to work there.

### Expected behavior

The project template should create a workable solution.

### How to reproduce it (as minimally and precisely as possible)

- Open VS
- Create a new app from the uno-templates using net6
- Close the solution
- open it up again => the mobile-project does not load anymore

### Workaround

Install and use Visual Studio 2022 **Preview**

### Works on UWP/WinUI

Yes

### Affected platforms

iOS, Android, macOS, Solution Templates

### IDE

Visual Studio 2022

### IDE version

17.0.2

**Comment by TopperDEL** [comment]
I have the exact same problem on a different computer.

**Comment by TopperDEL** [comment]
Might this be the reason?
https://stackoverflow.com/questions/69903517/unable-to-re-open-maui-project-in-visual-studio-2022-not-preview

**Comment by TopperDEL** [comment]
Indeed - I can confirm that the project loads and works again using the latest Visual Studio 2022 **Preview**.

**Comment by jeromelaban** [comment]
This is indeed the case: https://platform.uno/docs/articles/get-started-vs-2022.html#prerequisites
