### ISSUE TITLE
Improper Code Generation for DropShadowPanel (UWP Toolkit Control)

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#7581]
### Current behavior

Uno.UI 4.0.8 Solution fails to build with the following errors. There were no errors in 3.x.

\obj\Debug\100\g\BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs(1637,193,1637,203): error CS7069: Reference to type 'DropShadow' claims it is defined in 'Uno', but it could not be found
\obj\Debug\100\g\BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs(1638,188,1638,192): error CS7069: Reference to type 'CompositionBrush' claims it is defined in 'Uno', but it could not be found
\obj\Debug\100\g\BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs(1639,199,1639,203): error CS7069: Reference to type 'CompositionBrush' claims it is defined in 'Uno', but it could not be found

![image](https://user-images.githubusercontent.com/17993847/144474796-8d16db7f-06d6-4da4-8c53-462050a48d95.png)

### Expected behavior

Solution should build.

What is also interesting is that DropShadowPanel is unused in the application. DropShadowPanel is also now deprecated upstream.

### Workaround

None, DropShadowPanel is not used. UWP Toolkit cannot be removed from the project.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.0.8

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
This looks like a discrepancy between multiple versions of Uno (3 vs 4). Are you using dependencies like WCT or others ?

**Comment by robloo** [comment]
> This looks like a discrepancy between multiple versions of Uno (3 vs 4). Are you using dependencies like WCT or others ?

Yes, WCT 7.0. So basically the Nuget for WCT 7.0 isn't yet compatible with 4.0, makes some sense. Any estimates when this will be recompiled?

![image](https://user-images.githubusercontent.com/17993847/144477900-dff66c63-1925-40d4-981d-cc140e5922ad.png)

**Comment by robloo** [comment]
@jeromelaban 

Switching to WCT 7.1.10-preview Nugets allowed the solution to build so this was the issue. This should be fixed then once these updated builds go out of preview.

I'm going to close this issue since it will get automatically resolved at some point in the future.
