### ISSUE TITLE
ListView Items Completely Invisible

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#7582]
### Current behavior

All ListView controls in an application no longer work. There is simply nothing shown, no items are drawn on the screen. Interestingly, the scrollbar is correct and the item height is calculated properly. It is even possible to 'press' on these invisible items.

This previously worked in earlier versions of the Uno.UI 3.x series; however, it broke in later versions of Uno.UI by 3.11.6. It is not an issue with Uno.UI 4.x exclusively although it is broken there as well.

Note: An extensive update was done to Fluent version 2 styling in the app where this issue was found. It is possible that relates to this issue somehow.

![image](https://user-images.githubusercontent.com/17993847/144481699-1e7786e9-84c0-42af-92f8-9507a28914f1.png)

### Expected behavior

ListView should render it's child Item content to screen.

### Workaround

None

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.0.8

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. If you can provide repro steps, it'll help prioritize this issue.

**Comment by robloo** [comment]
> Thanks for the report. If you can provide repro steps, it'll help prioritize this issue.

I was expecting that :) I wanted to get this out before just in case anyone else has encountered it and might have some suggestions in the meantime.

Will work on a repro. Since this affects all ListView controls in the app hopefully it is easy to pull the relevant code out.

**Comment by pdecostervgls** [comment]
I'm running 3.11.6 and my ListView's and its Items render correctly. Interested in your repro.

**Comment by robloo** [comment]
So the issue is coming from a new ItemContainerStyle. When the ItemContainerStyle is not set (in XAML/C#) the ListView works just fine; but when it is modified things break. Uno didn't have issues with this in the past so something seems to have changed here or with resource lookup.

The new style is as below (using the [WinUI Library base style](https://github.com/microsoft/microsoft-ui-xaml/blob/3f179e8954e06b5c7e50f0282dda037d0a300f38/dev/CommonStyles/ListViewItem_themeresources.xaml#L174)). I'll make a repro of this.

```xaml
    <Style
        x:Key="BasicListViewItemStyle"
        BasedOn="{StaticResource DefaultListViewItemStyle}"
        TargetType="ListViewItem">
        <!-- CornerRadius added here and in the presenter -->
        <Setter
            Property="CornerRadius"
            Value="0" />
        <Setter
            Property="Template">
            <Setter.Value>
                <ControlTemplate
                    TargetType="ListViewItem">
                    <ListViewItemPresenter
                        CornerRadius="{TemplateBinding CornerRadius}"
                        ContentTransitions="{TemplateBinding ContentTransitions}"
                        Control.IsTemplateFocusTarget="True"
                        FocusVisualMargin="{TemplateBinding FocusVisualMargin}"
                        FocusVisualPrimaryBrush="{TemplateBinding FocusVisualPrimaryBrush}"
                        FocusVisualPrimaryThickness="{TemplateBinding FocusVisualPrimaryThickness}"
                        FocusVisualSecondaryBrush="{TemplateBinding FocusVisualSecondaryBrush}"
                        FocusVisualSecondaryThickness="{TemplateBinding FocusVisualSecondaryThickness}"
                        SelectionCheckMarkVisualEnabled="{ThemeResource ListViewItemSelectionCheckMarkVisualEnabled}"
                        CheckBrush="{ThemeResource ListViewItemCheckBrush}"
                        CheckBoxBrush="{ThemeResource ListViewItemCheckBoxBrush}"
                        DragBackground="{ThemeResource ListViewItemDragBackground}"
                        DragForeground="{ThemeResource ListViewItemDragForeground}"
                        FocusBorderBrush="{ThemeResource ListViewItemFocusBorderBrush}"
                        FocusSecondaryBorderBrush="{ThemeResource ListViewItemFocusSecondaryBorderBrush}"
                        PlaceholderBackground="{ThemeResource ListViewItemPlaceholderBackground}"
                        PointerOverBackground="{ThemeResource ListViewItemBackgroundPointerOver}"
                        PointerOverForeground="{ThemeResource ListViewItemForegroundPointerOver}"
                        SelectedBackground="{ThemeResource ListViewItemBackgroundSelected}"
                        SelectedForeground="{ThemeResource ListViewItemForegroundSelected}"
                        SelectedPointerOverBackground="{ThemeResource ListViewItemBackgroundSelectedPointerOver}"
                        PressedBackground="{ThemeResource ListViewItemBackgroundPressed}"
                        SelectedPressedBackground="{ThemeResource ListViewItemBackgroundSelectedPressed}"
                        DisabledOpacity="{ThemeResource ListViewItemDisabledThemeOpacity}"
                        DragOpacity="{ThemeResource ListViewItemDragThemeOpacity}"
                        ReorderHintOffset="{ThemeResource ListViewItemReorderHintThemeOffset}"
                        HorizontalContentAlignment="{TemplateBinding HorizontalContentAlignment}"
                        VerticalContentAlignment="{TemplateBinding VerticalContentAlignment}"
                        ContentMargin="{TemplateBinding Padding}"
                        CheckMode="{ThemeResource ListViewItemCheckMode}" />
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>
```

**Comment by jeromelaban** [comment]
ListViewItemPresenter is not supported by uno at this time. You'll need to use the [expanded version](https://github.com/microsoft/microsoft-ui-xaml/blob/3f179e8954e06b5c7e50f0282dda037d0a300f38/dev/CommonStyles/ListViewItem_themeresources.xaml#L230) of the ListViewItem style.

**Comment by robloo** [comment]
@jeromelaban Ah, thanks that explains it.

More info:

Before the Fluent V2 updates there was only one style provided by the WinUI library. In Fluent V2 they split apart into a `ListViewItemExpanded` and `DefaultListViewItemStyle`. These styles use different content presenters:

 1. DefaultListViewItemStyle : Uses `ListViewItemPresenter` which isn't supported by Uno
 2. ListViewItemExpanded : Uses `ContentPresenter` which is supported as you indicated.

In the past the app's customized style was based on the old style that used ContentPresenter. It then had performance optimizations stripping out a lot of unwanted functionality: https://platform.uno/docs/articles/Uno-UI-Performance.html. With the update to Fluent V2, obviously the simplified `DefaultListViewItemStyle` was now used as the base... without knowing the switch in presenter would break things.

The fix for this will be to switch back to using ContentPresenter with a heavily modified, custom style.

**Comment by robloo** [comment]
Closed as duplicate of #1444

**Comment by jeromelaban** [comment]
This is still a bug indeed, it should not be needed to specify the full style. We're going to fix this so the default is the proper one.

**Comment by jeromelaban** [comment]
Update: I look at the WinUI original file :) Uno uses the expanded style by default:

https://github.com/unoplatform/uno/blob/master/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/ListViewItem_themeresources.xaml#L172-L174

**Comment by robloo** [comment]
@jeromelaban I probably wasn't too clear above. The issue was encountered only in an app that customized the style as shown above. I wrote all of the above from an app-specific viewpoint.
