### ISSUE TITLE
Add support for TextBox.SelectedText

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#7588]
## What would you like to be added:
Add support for ```TextBox.SelectedText```
## Why is this needed:
SyncFusion makes use of this in SfInput.UWP

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by Youssef1313** [comment]
I don't see a `SelectText` method on `TextBox`. There is a `Select` and `SelectAll`, which are supposed to be supported.

**Comment by jeromelaban** [comment]
https://github.com/unoplatform/uno/blob/2cb46fcffa09d25b67d84f39fb0fd43198a7fd84/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TextBox.cs#L17

**Comment by Youssef1313** [comment]
Oh sorry, I read it `SelectText` and hence was looking only for methods. Thanks for clarifying @jeromelaban 

An implementation can be platform-independent. Since we already have the `Text`, `SelectionStart`, and `SelectionLength`. We can simply substring.

**Comment by CesarRabelo** [comment]
What's platforms are necessary implement this?

**Comment by CesarRabelo** [comment]
Probably the use of Substring(start, length) is possible in Android, Skia for IOS needs GetTextRange for Wasm is necessary use GetElement.value.substr

**Comment by carldebilly** [comment]
@CesarRabelo It depends. This property is actually providing 2 different features:
* `get`: it's getting the currently selected text. Since we already implemented `SelectionStart` and `SelectionLength` on all plarforms, there's no need to do any platform-specific code to implement it.
* `set`: it is supposed to replace the current selection by the provided text. I'm less sure if we have everything to implement it on all platforms.

**Comment by CesarRabelo** [comment]
About IOS I found this issue https://github.com/unoplatform/uno/issues/8016 probably I probably won't be able to move forward

**Comment by paulovila** [comment]
Main focus for this feature is WASM :)

**Comment by CesarRabelo** [comment]
Do you need get and set @paulovila ? If I try to set a selectedtext that is not found what's the behavior expected?

**Comment by paulovila** [comment]
If the selection is out of bounds, it should select from the beginning of the selection till the end of the text. In general, try to avoid out of bound exceptions by limiting the length of the text

**Comment by paulovila** [comment]
@CesarRabelo what happens in UWP then selecting out of bounds? 
It's hard to infer  the behaviour just from this:
```csharp
   /// <summary>Gets or sets the content of the current selection in the text box.</summary>
    /// <returns>The currently selected text in the text box. If no text is selected, the value is String.Empty.</returns>
    public extern string SelectedText { [MethodImpl(MethodCodeType = MethodCodeType.Runtime)] get; [MethodImpl(MethodCodeType = MethodCodeType.Runtime)] [param: In] set; }
    /// <summary>Gets or sets the number of characters in the current selection in the text box.</summary>
    /// <returns>The number of characters in the current selection in the text box, or 0 if there is no selection.</returns>
    public extern int SelectionLength { [MethodImpl(MethodCodeType = MethodCodeType.Runtime)] get; [MethodImpl(MethodCodeType = MethodCodeType.Runtime)] [param: In] set; }
    /// <summary>Gets or sets the starting position of the text selected in the text box. When the SelectionLength is 0 (there is no selected text), the SelectionStart property corresponds to the cursor position.</summary>
    /// <returns>The starting position of the current selection or the current cursor position.</returns>
    public extern int SelectionStart { [MethodImpl(MethodCodeType = MethodCodeType.Runtime)] get; [MethodImpl(MethodCodeType = MethodCodeType.Runtime)] [param: In] set; }
```

**Comment by CesarRabelo** [comment]
Thanks @paulovila
