### ISSUE TITLE
[iOS15] timepicker stuck on default value

### ISSUE THREAD

**Issue by CBrunet2212** [unoplatform/uno#7589]
### Current behavior

When opening the TimePicker on an iOS15 device, the wheel picker will be on whatever default value was set by the application and will not react to any user input, it's impossible to change the time.

### Expected behavior

The TimePicker would open and allow the user to set the time with the new iOS 15 wheel

### How to reproduce it (as minimally and precisely as possible)

Create a basic uno app, put a simple TimePicker control in the MainPage, launch it on an iOS15 simulator and try to change the time, it will not work.
[ios15timepicker-sample.zip](https://github.com/unoplatform/uno/files/7650799/ios15timepicker-sample.zip)

### Workaround

You can configure the application to use the legacy style timepicker in your app's App1.xaml.cs in the iOS head by adding `Uno.UI.FeatureConfiguration.TimePicker.UseLegacyStyle = true;` to the App1 constructor before InitializeComponent

### Works on UWP/WinUI

Yes

### Environment

Other

### NuGet package version(s)

Uno.UI 4.0.7

### Affected platforms

iOS

### IDE

Visual Studio 2019

### IDE version

16.11.7

**Comment by marwalsch** [comment]
I can reproduce the same behaviour with `Uno.WinUI` 4.0.11. 
![grafik](https://user-images.githubusercontent.com/72074423/148381383-def301c8-51ef-4460-9e8e-9a09d03eec39.png)
