### ISSUE TITLE
[F#] Cannot build F# project referencing Uno 4.0.* FS0226: The file extension of 'obj\Debug\net6.0\uno.reload.cookie.g.cs' is not recognized.

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/uno#7598]
### Current behavior

Uno generates empty `uno.reload.cookie.g.cs` file causing F# not to build
`error FS0226: The file extension of 'obj\Debug\net6.0\uno.reload.cookie.g.cs' is not recognized. Source files must have extension .fs, .fsi, .fsx, .fsscript, .ml or .mli.`

### Expected behavior

Uno.Core/Uno.UI/Uno.WinUI does not generate any C# file if project does not contain any XAML file

### How to reproduce it (as minimally and precisely as possible)

1. Create F# libaray targeting `net6.0`
2. Reference
``` XML
    <PackageReference Include="Uno.Core" Version="4.0.*" />
    <PackageReference Include="Uno.WinUI" Version="4.0.*" />
```
3. Build

### Workaround

No

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.0.*

### Affected platforms

iOS, Android, WebAssembly, macOS, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen)

### IDE

Visual Studio 2022

### IDE version

17.1 preview

**Comment by xperiandri** [comment]
@jeromelaban, blocking issue

**Comment by jeromelaban** [comment]
The file is created here: https://github.com/unoplatform/uno/blob/546441d12f12e27cd07fc75851039c7404efc2cf/src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props#L423

It's likely that there's a way to determine that the currently built project is not CSharp.

**Comment by xperiandri** [comment]
That is strange that it is created even though it is empty

**Comment by jeromelaban** [comment]
It's not strange, it's used in the VS Code scenario. It's generating a .cs file, so this is why F# does not like this much.

**Comment by xperiandri** [comment]
So do you suggest just adding a condition that disables the target for non C# projects?

**Comment by xperiandri** [comment]
Thanks!

**Comment by jeromelaban** [comment]
@xperiandri did this fix your build issue?

**Comment by xperiandri** [comment]
I'll check and let you know. From the change I supposed so and didn't checked yet.

**Comment by xperiandri** [comment]
Yes, builds. Checked with 4.1.0-dev.324

**Comment by WithinUA** [comment]
This happens again
The file extension of 'obj\Debug\net8.0-browserwasm\FakeGlobalUsings.g.cs' is not recognized. Source files must have extension .fs, .fsi, .fsx, .fsscript, .ml or .mli.

**Comment by jeromelaban** [comment]
@WithinUA it's best to open another issue with a repro, thanks.

**Comment by WithinUA** [comment]
We solved this with the help of <UnoDisableGenerateGlobalUsingsMock>true</UnoDisableGenerateGlobalUsingsMock> )
