### ISSUE TITLE
Ellipsegeometry not using to uno

### ISSUE THREAD

**Issue by AbdalaMask** [unoplatform/uno#7604]
### Current behavior

Ellipsegeometry not using to uno

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. We require issues to include a detailed sample of what's not working, this issue's description is unfortunately not detailed enough.

Please open another issue with all the required detailed provided.
