### ISSUE TITLE
[WASM][Skia] When using multiple layers in the Grid, the elements are opaque for clicks

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#7608]
### Current behavior

It is impossible to click on the buttons in this case:
```xml
<Grid>
    <StackPanel Orientation="Horizontal">
        <StackPanel>
            <Button Content="OpenFile" Command="{Binding OpenFile}"/>
            <Button Content="OpenFiles" Command="{Binding OpenFiles}"/>
            <Button Content="SaveFile" Command="{Binding SaveFile}"/>
            <Button Content="SaveFileAs" Command="{Binding SaveFileAs}"/>
            <Button Content="CreateTemporaryFileAndLaunch" Command="{Binding CreateTemporaryFileAndLaunch}"/>
        </StackPanel>
    </StackPanel>
    
    <views:PreviewDropView
        DataContext="{Binding PreviewDropViewModel}"
        />
</Grid>
```

### How to reproduce it (as minimally and precisely as possible)

[H.ReactiveUI.CommonInteractions-master (2).zip](https://github.com/unoplatform/uno/files/7664483/H.ReactiveUI.CommonInteractions-master.2.zip)

FileInteractionsView.xaml File tab

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.1.0-dev.32

### Affected platforms

WebAssembly, Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.1 preview

**Comment by jeromelaban** [comment]
Thanks for the report. Can you try setting `IsHitTestVisible` to False on `views:PreviewDropView` and see if this helps ?

**Comment by HavenDV** [comment]
> Thanks for the report. Can you try setting IsHitTestVisible to False on views:PreviewDropView and see if this helps ?

this does not work for either WebAssembly or Skia.WPF

**Comment by jeromelaban** [comment]
@dr1rrb does this look familiar ?

**Comment by francoistanguay** [comment]
@dr1rrb  ?

**Comment by dr1rrb** [comment]
I'm no longer able to repro on WASM with 4.1.0-dev.606, it has most probably been fixed by https://github.com/unoplatform/uno/pull/7571

Closing the issue, feel free to re-open it if you still have an issue.

**Comment by HavenDV** [comment]
Yes, it looks like this issue has been fixed.
There is still another one here, in that the PreviewDropView is not shown above the StackPanel. I will create a new issue for this.

**Comment by HavenDV** [comment]
By the way, I couldn't reopen an issue, I can only comment on closed issues
