### ISSUE TITLE
NavigationViewItem are invisible after upgrade to 4.0

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#7609]
### Current behavior

<img width="536" alt="image" src="https://user-images.githubusercontent.com/3002068/144945414-48cb94b8-58fb-4e63-b98d-779f669d8baa.png">

```xml
<muxc:NavigationView
      x:Name="NavigationControl"
      IsSettingsVisible="False"
      AlwaysShowHeader="True"
      IsTabStop="False" 
      IsPaneToggleButtonVisible="True" 
      IsPaneOpen="True" 
      IsPaneVisible="True"
      PaneDisplayMode="LeftCompact"
      d:PaneDisplayMode="Left"
      d:MenuItemsSource="{Binding NavigationItems}"
      d:FooterMenuItemsSource="{Binding FooterNavigationItems}"
      d:SelectedItem="{Binding SelectedNavigationItem}"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
      >
      <muxc:NavigationView.MenuItemTemplate>
          <DataTemplate x:DataType="system:Type">
              <muxc:NavigationViewItem 
                  Content="{x:Bind Converter={StaticResource TypeToNameConverter}}"
                  d:Content="{Binding Converter={StaticResource TypeToNameConverter}}" 
                  Icon="{x:Bind Converter={StaticResource TypeToSymbolIconConverter}}"
                  d:Icon="{Binding Converter={StaticResource TypeToSymbolIconConverter}}"
                  />
          </DataTemplate>
      </muxc:NavigationView.MenuItemTemplate>
</muxc:NavigationView>
```

### Expected behavior

<img width="305" alt="image" src="https://user-images.githubusercontent.com/3002068/144946010-e93a059b-88f9-45ec-9c2e-63c8ac4e7723.png">

### How to reproduce it (as minimally and precisely as possible)

I will provide it if required

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.1.0-dev.32

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.1 preview

**Comment by jeromelaban** [comment]
@MartinZikmund looks familiar ?

**Comment by robloo** [comment]
Is `x:DataType="system:Type"` correct? I havnt seen this technique before and usually expect an actual type like NavigationViewItem.

**Comment by HavenDV** [comment]
My view model contains:
```cs
    public IReadOnlyCollection<Type> NavigationItems { get; } = new[]
    {
        typeof(ExcerptsViewModel),
        typeof(ResourcesViewModel),
        typeof(DescriptorsViewModel),
        typeof(MemosViewModel),
        typeof(TagsViewModel),
        typeof(AnalyzeViewModel),
        typeof(TrainingViewModel),
        typeof(SecurityViewModel),
        typeof(DataSetsViewModel),
    };

    public IReadOnlyCollection<Type> FooterNavigationItems { get; } = new[]
    {
        typeof(AccountViewModel),
        typeof(ProjectsViewModel),
        typeof(LoginViewModel),
        typeof(SettingsViewModel),
    };
```

But it doesn't matter, the type can be any, usually it's ViewModel instead of System.Type

**Comment by MartinZikmund** [comment]
@HavenDV Can you create a small repro please? I tried to repro here, but could not cause the same problem: 
![image](https://user-images.githubusercontent.com/1075116/145784159-676e9634-df15-4995-82ad-58d8185e5837.png)

**Comment by HavenDV** [comment]
Yes sure, little later

**Comment by HavenDV** [comment]
I was unable to repeat the behavior in the new Uno project, so I tried to remove everything unnecessary in our project. There is still a lot to delete here, I'll deal with it tomorrow if need be.
[UnoNavigationViewBug-main.zip](https://github.com/unoplatform/uno/files/7711558/UnoNavigationViewBug-main.zip)

**Comment by HavenDV** [comment]
But I can confirm that if you roll back ReactiveUI (because it can implicitly raise the Uno version) and Uno dependencies to 3.10.11, then everything works.

**Comment by HavenDV** [comment]
Having simplified the project to a minimum, I found the problem was the dependency that BaseConverter comes from. The bottom line is that this library listed the Uno 3.4 version as a dependency. After upgrading to 4.0, or moving the BaseConverter code into the project, everything starts working.

**Comment by HavenDV** [comment]
At the same time, the implemented interface is identical in both versions of Uno, and its code is also. The problem was caused by the very fact that it was dependent on Uno 3.4.

**Comment by jeromelaban** [comment]
@HavenDV Was that interface implemented in a project present in your solutio, or in a nuget package ?

**Comment by HavenDV** [comment]
I am using converters like this:
```cs
#nullable enable

namespace Dedoose.Converters;

public class TypeToNameConverter : BaseConverter<Type?, string>
{
    #region Static methods

    public static string Convert(Type? value, object? argument)
    {
        if (value == null)
        {
            return string.Empty;
        }

        return LocalizationConverter.Convert($"{value.Name}.Name");
    }

    #endregion

    #region Constructors

    public TypeToNameConverter()
        : base(Convert)
    {
    }

    #endregion
}
```
where `BaseConverter` comes from library: https://github.com/HavenDV/H.ReactiveUI.CommonInteractions/blob/master/src/shared/H.ReactiveUI.CommonInteractions.Shared/Converters/BaseConverter.cs
It implements `Windows.UI.Xaml.Data.IValueConverter` and `ReactiveUI.IBindingTypeConverter`
