### ISSUE TITLE
Fluent controls don't respect `BorderThickness` set to 0

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#7621]
### Current behavior

Using the Fluent version 2 Style on `TextBox`, it is impossible to set` BorderThickness` to zero and have the border disappear. Consider the following code:

```xaml
        <TextBox
            x:Name="SettingsSidePaneTitleTextBox"
            PlaceholderText="Title"
            Background="Transparent"
            BorderThickness="0"
            HorizontalAlignment="Stretch"
            VerticalAlignment="Top"
            Margin="5" />
```

Produces (on Android):

**Unfocused**
![image](https://user-images.githubusercontent.com/17993847/145280574-6b339578-9872-4528-8a82-c7f7a5b9e673.png)

**Keyboard Focused**

![image](https://user-images.githubusercontent.com/17993847/145280605-bde9b927-268c-40e1-8fb6-13fdc45adb99.png)

### Expected behavior

UWP:

**Unfocused**
![image](https://user-images.githubusercontent.com/17993847/145280245-c11c46b2-7185-4e51-a482-7e14dbc45d80.png)

**Keyboard Focused**
![image](https://user-images.githubusercontent.com/17993847/145280317-2789f789-e705-42de-89ed-fd6cce95a38d.png)

### How to reproduce it (as minimally and precisely as possible)

See the repro app:
[TestApp.zip](https://github.com/unoplatform/uno/files/7694591/TestApp.zip)

### Workaround

None

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.0.9

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by robloo** [comment]
@MartinZikmund You implemented the new Fluent v2 borders for Android I believe. Do you expect this is an easy fix? Can you point in the right direction?

**Comment by MartinZikmund** [comment]
Workaround here would be to create a custom `Style` for `Button` to hide the border, but proper fix will require adjusting the customized template. I can look into this after I finish my current task

**Comment by robloo** [comment]
No rush, I was under the impression the linear gradient borders required some larger work-arounds to get working. If it was just some tweaks to the template this should be quickly solvable.

**Comment by MartinZikmund** [comment]
We were (and still are) aiming for a full workaround-less implementation for linear gradient borders (Android, iOS, macOS and Skia are actually basically ready in this regard), but getting it working on WASM is super tricky, as gradients don't play nice with corner radius, so that's why we went with this simpler solution for now until we find a reliable solution on web

**Comment by MartinZikmund** [comment]
This applies to other controls like `Button` too
