### ISSUE TITLE
[android]PasswordBox

### ISSUE THREAD

**Issue by githubxiaoa** [unoplatform/uno#7623]
### Current behavior

can't hide passwords on Android

### Expected behavior

hide passwords on Android

### Affected platforms

Android

### IDE

Visual Studio 2019

**Comment by jeromelaban** [comment]
Thanks for the report. We'll need more details about this issue. Would you mind adding the details requested in the issue creation description ?

**Comment by githubxiaoa** [comment]
![QQ截图20211209211026](https://user-images.githubusercontent.com/31387524/145402699-356c1df4-1338-4217-a456-4def18469ddb.png)
![QQ截图20211209211049](https://user-images.githubusercontent.com/31387524/145402704-2ba4de2a-a692-472b-8036-53523fa29f95.png)
![QQ截图20211209211206](https://user-images.githubusercontent.com/31387524/145402706-dcc19a3d-0217-48bd-a8d0-4a8f32dd11d4.png)

**Comment by Youssef1313** [comment]
I can ***guess*** this is a regression I made when fixing few InputScope-related issues. Specifically the following line:

https://github.com/unoplatform/uno/blob/5c9c2514365bcaef7a7b25a0a720911290193059/src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs#L237

We should have `_textBoxView.InputType = types` before or after that line.

**Currently**, `SetRawInputType` for this specific code path will likely have no effect. But leaving it as-is may prevent future bugs if the callers of `SetInputScope` get changed.

**Comment by jeromelaban** [comment]
Fixed in 4.0.9 and 4.1-dev latest.

We're missing a UI test to close this issue.

**Comment by cesarchefinho** [comment]
4.0.9 not work too... please, reopen the issue

**Comment by Youssef1313** [comment]
@cesarchefinho Can you validate with with 4.0.11 or 4.1.0-dev?

**Comment by jeromelaban** [comment]
It's fixed in 4.0.11, I mentioned 4.0.9 by mistake.
