### ISSUE TITLE
Implement Windows.UI.Core.CoreWindow.Bounds

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#7630]
## Why is this needed:
SyncFusion TimePicker places the popup on a location to present the time editor
## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly

**Comment by CesarRabelo** [comment]
Please, is possible put more informations about this issue? Does the behavior look like this? https://www.syncfusion.com/blazor-components/blazor-timepicker

**Comment by jeromelaban** [comment]
@CesarRabelo this specific property is about providing the bounds of the CoreWindow. The relation to the use made for it is not particularly relevant.

In general [this property](https://github.com/unoplatform/uno/blob/d2e1e454f52e82cd31da2719b5d1aad2a4c8c9e8/src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Core/CoreWindow.cs#L53) will need to match the behavior of `Window.Bounds`.
