### ISSUE TITLE
[Android] Removing items from ComboBox confuses the SelectedIndex

### ISSUE THREAD

**Issue by queequac** [unoplatform/uno#7632]
### Current behavior

I have a ComboBox control with several entries. Those entries are localized and set via XAML.
When I remove one of the entries, the SelectedIndex properties does not reflect the correct index anymore, but either returns -1 or the original index when the collection was created.
Also setting the selection via index is messed up afterwards.

### Expected behavior

The index reflects the correct position of the item within the Items collection.
Works correctly with Windows UWP or with Uno packages < version 4.0 (more precisely, it worked until 3.11.6)

### How to reproduce it (as minimally and precisely as possible)

Use the following XAML in a page:
```
    <StackPanel Orientation="Vertical">
        <TextBlock Text="{Binding ElementName=combo, Path=SelectedIndex}"/>
        <ComboBox x:Name="combo">
            <ComboBoxItem>One</ComboBoxItem>
            <ComboBoxItem>Two</ComboBoxItem>
            <ComboBoxItem>Three</ComboBoxItem>
        </ComboBox>
    </StackPanel>
```

And simply call in the page's code behind the following line:
`combo.Items.RemoveAt(0);`

### Workaround

Clear the collection (combo.Items.Clear()) and add items again, but that's not really fancy.😉

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.0.9

### Affected platforms

Android

### IDE

Visual Studio 2019

### IDE version

16.11.7

**Comment by carldebilly** [comment]
This should been fixed by https://github.com/unoplatform/uno/pull/8227
