### ISSUE TITLE
Passwordbox is broken after upgrade for uno 4.0x includindg 4.09

### ISSUE THREAD

**Issue by cesarchefinho** [unoplatform/uno#7633]
### Current behavior

Passwordbix show  typed characters like a normal Teedtbox in android

It works normal in uwp....

### Expected behavior

Caracters typed are showed as dots.

### Workaround

Revert to 3.x branch

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.09

### Affected platforms

Android

### IDE version

Visual studio 2019

### Anything else we need to know?

Not tested in other plataforms...need investigation.

**Comment by jeromelaban** [comment]
Thanks for the report, this is fixed in 4.0.11.
