### ISSUE TITLE
Implement  Windows.UI.Xaml.Controls.Primitives.Popup.IsOpen

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#7636]
## Implement  Windows.UI.Xaml.Controls.Primitives.Popup.IsOpen
this also contains Windows.UI.Xaml.Controls.Primitives.Popup.IsOpenProperty

## Why is this needed:
It is used in SyncFusion SfTabControl
## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS

**Comment by jeromelaban** [comment]
Fixed by https://github.com/unoplatform/uno/pull/7571
