### ISSUE TITLE
vscode extension xaml code completion doesn't work on linux

### ISSUE THREAD

**Issue by trampster** [unoplatform/uno#7639]
### Current behavior

When editing a xaml page there is no code completion

In the Uno Platform -XAML output windows it says this:

```
warn: Uno.LanguageServer.Workspace[0]
      No Roslyn worker is available
```

I'm on Ubuntu 20.04, I have .net 6 installed and the Uno Platform vscode extension installed. 

uno-check does not report any problems.

### Expected behavior

I expect to get code completion when editing my xaml files. I expect this because the Uno Platform vscode extension details says the following: 

* Code-behind navigation from a XAML file

### How to reproduce it (as minimally and precisely as possible)

1. Created a new uno project by exactly following the instructions here: https://platform.uno/docs/articles/get-started-vscode.html
2. Try and edit a xaml file 
-> no code completion

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio Code

### IDE version

1.63.0

**Comment by jeromelaban** [comment]
Thanks for the report. Can you provide the output of the "Uno Platform" output as well ?

**Comment by trampster** [comment]
Uno Platform output:

```text
Uno Platform "dotnet new" templates are already installed. The templates may be updated by running "dotnet new -i Uno.ProjectTemplates.Dotnet"
Multiple projects loaded, select one in OmniSharp
Multiple projects loaded, select one in OmniSharp
```

**Comment by jeromelaban** [comment]
Thanks. Make sure to select a specific project in the project selector: https://platform.uno/docs/articles/get-started-vscode.html#prepare-the-webassembly-application

We're going to be releasing an update that makes step more obvious.

**Comment by trampster** [comment]
I couldn't do that, there isn't anything in the status bar to select. I did delete the webassembly project so that there was no other main project option just MyApp.Skia.Gtk and MyApp.Shared

![image](https://user-images.githubusercontent.com/2063633/145888979-40ce9e5e-3fa2-48d4-8da5-fac4fdf7837f.png)

**Comment by jeromelaban** [comment]
Thanks. This likely means that the project fails to load in omnisharp. Can you take a look at the omnisharp log as well ?

**Comment by trampster** [comment]
So there was an exception there because MyApp-vsmac.slnf still referenced the missing Web Assembly project, I removed that now I get "MyApp-vsmac.slnf" selected but clicking it results in and error

```text
Extension 'ms-dotnettools.csharp' CANNOT use API proposal: quickPickSeparators.
Its package.json#enabledApiProposals-property declares: [] but NOT quickPickSeparators.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-dotnettools.csharp
```

Why is there even a vsmac file here, is it confusing vscode?

**Comment by trampster** [comment]
If I remove the vsmac file then it selects MyApp.sln, If I click that I get the same error.

**Comment by trampster** [comment]
I seem to be running into this error https://github.com/OmniSharp/omnisharp-vscode/issues/4907

Some comments say fixing sln/csproj files can make it go away, others say even fresh templates from dotnet new cause this to happen.

**Comment by jeromelaban** [comment]
Thanks, this looks like a recent issue in omnisharp: https://github.com/OmniSharp/omnisharp-vscode/issues/4937.

You can try downgrading omnisharp to an earlier release, or upgrade to the preview.

**Comment by trampster** [comment]
I can confirm that upgrading to the OmniSharp beta fixes the problem

**Comment by jeromelaban** [comment]
Thanks for the update!
