### ISSUE TITLE
Implement `Windows.UI.Xaml.Controls.Primitives.PlacementMode.*`

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#7640]
## Implement Windows.UI.Xaml.Controls.Primitives.PlacementMode.Bottom.*
PlacementMode is comprised of:

- PlacementMode.Bottom
- PlacementMode.Left
- PlacementMode.Right
- PlacementMode.Top

## Why is this needed:
Used in SyncFusion SfGrid
## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS

**Comment by MartinZikmund** [comment]
This is now supported by both popup and flyout https://github.com/unoplatform/uno/blob/26f20e971cc5f5237a88c36f9e6806158f252ebe/src/Uno.UI/UI/Xaml/Controls/Primitives/PlacementMode.cs#L6
