### ISSUE TITLE
UseUWPDefaultStyles does not seem to work

### ISSUE THREAD

**Issue by marwalsch** [unoplatform/uno#7653]
### Current behavior

Setting the `Uno.UI.FeatureConfiguration.Style.UseUWPDefaultStyles = false;`  flag in `App`'s constructor has no effect.
I tested most common UI elements but none of them seem to adopt native appearance. Instead, it seems that the following elements always rely on the native counterpart (a non-issue for me):
- The pop-up/pop-over appearing after interacting with a `Datepicker `looks unique on iOS/Andorid/UWP respectively;
- The `ProgressRing` takes the native appearance.

I installed VS2022 on a completely sterile environment and sought to Uno-Check and visual studio to have no complaints about the workloads whatsoever.

### Expected behavior

Native UI is used. 

[Sample.zip](https://github.com/unoplatform/uno/files/7719249/Sample.zip)

### Works on UWP/WinUI

Yes

### NuGet package version(s)

See attached project.

### Affected platforms

iOS, Android

### IDE

Visual Studio 2022

### IDE version

17.0.3

### Relevant plugins

Only the Uno Extension.

### Anything else we need to know?

I have additional issues as the `Commandbar` disappearing on Android upon interaction.

**Comment by davidjohnoliver** [comment]
@marwalsch With the current default Uno app template, the Fluent styles are included by default, which is probably masking the native styles used by the framework when setting `Uno.UI.FeatureConfiguration.Style.UseUWPDefaultStyles = false;`.

If you remove `<XamlControlResources />` in App.xaml, do you see native styles being used?

**Comment by marwalsch** [comment]
@davidjohnoliver Thanks for the quick response, that actually did it. However I noticed that the `AppBarButton`s are invisible on both the iOS and Android device, while the latter at least possesses an openable albeit empty context menu. I couldn't find any related issue that targets this yet.

**Comment by davidjohnoliver** [comment]
@marwalsch When using native styling, certain `AppBarButton` and `CommandBar` features aren't supported, because there's no platform equivalent. There's more info here: https://platform.uno/docs/articles/controls/CommandBar.html

If you think based on that doc that your AppBarButtons should be working, then it may be a bug, and you may want to open a new issue with the details.

**Comment by marwalsch** [comment]
@davidjohnoliver I see, I only considered the section about `AppBarButton` being the only supported element, not that most od its properties won't work as well. Thanks.
