### ISSUE TITLE
VS Code extension page snippet Grid closing tag

### ISSUE THREAD

**Issue by sarosigy** [unoplatform/uno#7660]
### Current behavior

The installed (v0.2.2) Uno Platform Extension in VS code (linux, if it is matter)
on a new .xaml page, when typing the 'page' word for snippet and pressing TAB, inserts this code (relevant parts here):

    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
       
       
    <Grid>

Observe that the `<Grid>` not ends with `</Grid>` but with `<Grid>` again.

### Expected behavior

The `<Grid>` close tag should be `</Grid>` .

### How to reproduce it (as minimally and precisely as possible)

1. Install VS code
2. Install Platform UNO extension
3. Create a page (new file, type is xaml)
4. Type page
5. Press TAB

### Workaround

Insert the missing / into Grid closing tag

### Environment

Other

### IDE

Visual Studio Code

### IDE version

1.62.3 but it doesn't matter

**Comment by jeromelaban** [comment]
Thanks for the report! We'll get a fix in place :)

**Comment by sarosigy** [comment]
Hello Jérôme,

Thank you for the quick reply. And for the fixing :)
