### ISSUE TITLE
[Gallery][Wasm] `ChipGroup` - in "Input" the last option "Item #9" is getting cut off

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7668]
### Current behavior

![ChipGroup issue](https://user-images.githubusercontent.com/74563602/146557695-6dd8000c-9117-4b4e-8b9b-d1f044233845.png)

### Expected behavior

The last button for Input should fully display.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "ChipGroup" from the "Toolkit" list.
4. Go to Input Section.
5. Observe that the "Item #9" is truncating.

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
That's probably because there's no scrollviewer. @agneszitte-nventive ?

**Comment by agneszitte-nventive** [comment]
I will verify @jeromelaban

**Comment by sakshi173** [comment]
@agneszitte-nventive, I am able to reproduce this bug. Please whenever you get time look into this issue.
![Chipgroup truncate issue](https://user-images.githubusercontent.com/74563602/159057824-53c01e9a-254d-41c6-b392-7dd1cd524f81.png)

**Comment by nguyeenvy** [comment]
I just tested on the latest Uno Gallery app on WASM and I am not able to reproduce this issue.



![Image](https://github.com/unoplatform/uno/assets/54756963/f1b8f9ea-50d9-47b2-90d9-79a419faf0c2)


@sakshi173 Can you see if you can still reproduce this issue or maybe close it?

**Comment by sakshi173** [comment]
This issue is resolved closing it.
