### ISSUE TITLE
wasm: ComboBox add support for OnDropDownOpened

### ISSUE THREAD

**Issue by yowl** [unoplatform/uno#767]
## I'm submitting a...

  
- Feature request 

## Current behavior
OnDropDownOpened is not implemented:
https://github.com/nventive/Uno/blob/6f7e23f71084cc7e785fbd0838d04eeeffe7f5e9/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ComboBox.cs#L274

## Expected behavior
This method is implemented.  This is useful when extending the ComboBox, for example to make a multiselect combobox an example of which is https://github.com/yowl/UnoMultiselectCombBox

## Minimal reproduction of the problem with instructions
Override the ComboBox and add some instrumentation to the dropdown method:

```
        protected override void OnDropDownOpened(object e)
        {
            Debug.WriteLine("drop down opened");
```
Run and open the combo, the message is not displayed in the console

## Environment

```
Nuget Package: 

Package Version(s): 
1.45.0-dev.1201

Affected platform(s):
- [X] iOS
- [X] Android
- [X] WebAssembly
```

**Comment by Youssef1313** [comment]
Looks like this was fixed in https://github.com/unoplatform/uno/pull/6184.
@jeromelaban Should it get closed?
