### ISSUE TITLE
[Skia] [Wasm] FlipView tests fail for managed implementation

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#7671]
### Current behavior

FlipView tests failing, and control doesn't currently seem to work on Wasm or Skia.

### Expected behavior

Control works.

### How to reproduce it (as minimally and precisely as possible)

At least two failures were noted:

## Runtime test:

1. Re-enable `Given_FlipView.When_Observable_ItemsSource_And_Added()`
2. Note that it fails on Skia and Wasm.

Initial investigation: on adding an item to the items source collection, the scroll is updated, but it appears that items are not fully laid out yet, and the snap points logic applies an incorrect scroll, which in turn triggers an incorrect SelectedIndex to be set.

## Sample

1. Run SamplesApp.
2. Navigate to FlipView_Button sample
3. Try to flip the FlipView
4. Notice that Button 2 doesn't appear

Note: the associated UI tests (`FlipView_Tests`) are passing, but apparently spuriously - the test simply calls WaitForElement() on Button 2, but since the items panel is a StackPanel (not virtualized), Button 2 is already present (but not visible). The test should be amended to take a screenshot and check a pixel value to make sure that the flip really happened.

### Affected platforms

WebAssembly, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen)

**Comment by Xiaoy312** [comment]
wasm test is getting re-enabled in #7768
