### ISSUE TITLE
[Skia.Wpf - Skia.Gtk] AutoSuggestBox doesn't work right

### ISSUE THREAD

**Issue by mterwoord** [unoplatform/uno#7675]
### Current behavior

I have an `AutoSuggestBox`, which contains several objects in its ItemsSource. 
When I click it, both on Wpf and on Gtk, the text box gets focused and I can start typing. After typing the first character, the dropdown/suggest popup shows up. Now the textbox loses focus and I cannot continue typing.

[AutoSuggestBoxRepro.zip](https://github.com/unoplatform/uno/files/7740598/AutoSuggestBoxRepro.zip)

### Expected behavior

I expect to be able to continue typing. 

### Works on UWP/WinUI

Yes

### NuGet package version(s)

3.11.6, 
but can also reproduce on 4.1.0-dev.152

(Also on WinUI)

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2019

**Comment by mterwoord** [comment]
At risk of being rude: @MartinZikmund Any progress on this?

**Comment by MartinZikmund** [comment]
@mterwoord Will prioritize this 👍
