### ISSUE TITLE
[Gallery][Wasm] For all the controls the Words 'Material, Fluent and Cupertino' is truncating.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7689]
### Current behavior

![name display issue2](https://user-images.githubusercontent.com/74563602/147350449-f37ff3a4-0049-4076-8f42-017ca1056a58.png)

### Expected behavior

The words should display correctly.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP.
2. Observe that for Overview the Words 'Material, Fluent and Cupertino' is truncating.

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
@agneszitte-nventive @agneszitte-nventive could it be related to a recent fonts change ?

**Comment by agneszitte-nventive** [comment]
I will check @jeromelaban

**Comment by agneszitte-nventive** [comment]
@jeromelaban I don't think it's related to a recent font change as it's displaying correctly in some places in the visual tree but not in others. (Same font, same text style - testing with 3.0.9 / 3.0.11 / latest Uno dev 4.1.0-dev.181)
![image](https://user-images.githubusercontent.com/16295702/148276724-4530f953-4922-4a95-bcc2-ec828a810c50.png)

Still investigating.

**Comment by agneszitte-nventive** [comment]
regroup weights is the issue, we need to find another way to do the workaround in Fonts.css with all these fonts or fix the main issue that forcing us to use this workaround (https://github.com/unoplatform/uno/issues/693)
