### ISSUE TITLE
Gallery][iOS] `DatePicker(Native)` - in light theme, the `Calendar` is displaying blank

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7691]
### Current behavior

![datepicker issue](https://user-images.githubusercontent.com/74563602/147356920-e99a1473-df34-4d49-82a4-b9be3995fa5a.png)

### Expected behavior

The calendar should display properly.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Change theme to Night mode.
4. Click "DatePicker" from the "Component" list.
5. Go to 'Native' section.
6. Change theme to Day mode.
7. Click "Set Date" option. 
8. Observe that in Day mode, the Calendar is not displaying correctly. 

### Affected platforms

macOS

**Comment by sakshi173** [comment]
Repro of this bug

https://user-images.githubusercontent.com/74563602/156427290-c3c90ee4-932b-493a-9fcb-c4de58e44e58.MOV

.

**Comment by carldebilly** [comment]
@sakshi173 I cannot reproduce on an emulator on iOS 13+. Which version are you using to get this bug?

**Comment by carldebilly** [comment]
Seems related to https://github.com/unoplatform/uno/issues/5482

**Comment by sakshi173** [comment]
@carldebilly, I am getting this bug for **iPhone12, Software Version 14.1**
 and canaries build(Testflight) **Version 1.5.0(883), Release Date Feb 10, 2022**
Please let me know, if you need any additional information.
![ios build](https://user-images.githubusercontent.com/74563602/157272406-92cc88e7-43d7-46c8-9159-ff41e731f17a.png)

**Comment by agneszitte** [comment]
@sakshi173 can you please re-test this one with latest canary please

**Comment by sakshi173** [comment]
I am not able to reproduce it, as the DatePicker calendar for Native(iOS) option got fully changed, due to that closing it.
![datepicker correct](https://github.com/unoplatform/uno/assets/74563602/437a3ebf-889b-4b65-b808-307d83d718ad)
