### ISSUE TITLE
Building Uno.UI version mismatch

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#7693]
## On which page?
uno/doc/articles/uno-development/building-uno-ui.md

## What's wrong?
"Visual Studio 2022 (17.0 or later)" and "install all recent UWP SDKs, starting from 10.0.17763"

## Any feedback?
 Visual Studio 2022 installer can only install SKD 18362, 19041, 20348 and 22000. No 17763.

![vs2022no17](https://user-images.githubusercontent.com/23451507/147413530-effcaf7e-51d6-4013-ad61-af0c1fdbd387.jpg)

**Comment by jeromelaban** [comment]
You'll need to install the [SDK from Microsoft's sites](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/). We'll update the documentation.
