### ISSUE TITLE
[WPF] Latest Stable DataGrid WPF MemoryLeak 

### ISSUE THREAD

**Issue by bstrother1** [unoplatform/uno#7697]
### Current behavior

Latest Version of Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid has a memory leak with WPF. The Datagrid does not load and slowly memory usage increases. Datagrid works in UWP (Though UWP uses Microsoft.Toolkit.Uwp.UI.Controls.DataGrid). 
[DataGridResizeIncorrect.zip](https://github.com/unoplatform/uno/files/7785900/DataGridResizeIncorrect.zip)
 

### Expected behavior

Datagrid loads like UWP without memory leakage. 

### How to reproduce it (as minimally and precisely as possible)

1) Use Current NuGet packages in WPF (Listed below)
2) Have a MVVM structure
3) Have a Datagrid with attached Itemsource

### Workaround

Use older version. 

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

WPF:
  PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" 
  PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" 
  PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" 
  PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0"
  PackageReference Include="Splat.Microsoft.Extensions.DependencyInjection" Version="14.1.17" 
  PackageReference Include="Uno.UI.Skia.Wpf" Version="4.0.11" 
  PackageReference Include="Uno.UI.RemoteControl" Version="4.0.11" Condition="'$(Configuration)'=='Debug'" 
  PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.0.11" 
  PackageReference Include="ReactiveUI.Fody" Version="17.1.9"
  PackageReference Include="ReactiveUI.Uno" Version="17.1.9" 
  PackageReference Include="Uno.Microsoft.Toolkit" Version="7.1.10" 
  PackageReference Include="Uno.Microsoft.Toolkit.Uwp" Version="7.1.10" 
  PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI" Version="7.1.10" 
  PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls" Version="7.1.10" 
  PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid" Version="7.1.10"
  PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.Layout" Version="7.1.10" 

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.0.4

### Anything else we need to know?

The name of this Sample Project is DataGridResizeIncorrect because it was originally meant to display a resizing issue with the Datagrid that is only occurring in WPF. I wanted to display this issue with the latest toolkit versions but the datagrid instead began to leak memory. 

Something that also occurred was Uno not having reference to DropShadow when the version was set to 7.1.10-gf3d2516805 with the latest Uno.UI.Skia.Wpf -> 4.0.11 but worked with -> 3.11.6.

**Comment by workgroupengineering** [comment]
I have same issue

**Comment by bstrother1** [comment]
Seemed to have been fixed by upgrading to:
 PackageReference Include="Uno.Microsoft.Toolkit" Version="7.1.11" 
 PackageReference Include="Uno.Microsoft.Toolkit.Uwp" Version="7.1.11"
 PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI" Version="7.1.11" 
 PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls" Version="7.1.11" 
 PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid" Version="7.1.11" 
 PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.Layout" Version="7.1.11"

**Comment by bstrother1** [comment]
This should be closed. It's fixed.

**Comment by jeromelaban** [comment]
Thanks!
