### ISSUE TITLE
NET6 Mobile projects do not load in VS with new template after closed and reopen

### ISSUE THREAD

**Issue by MarianoGomezBidondo** [unoplatform/uno#7702]
### Current behavior

When I create a new solution with Visual Studio 2022 v17.0.4 (runing with admin privileges) , with the latest version of the existing UNO extension at 2021-12-28. I use the template "Multi-Platform App (Uno Platform|net6)".

UWF and WASM projects builds OK, but Mobile gives several errors. 

If I close the solution and open it again, the MOBILE project does not load and comes out with the legend (incompatible) and a error message apears:
"Xamarin.Android for Visual Studio requires Android SDK. Please click here to configure."
If i click in message, the window "Anodrid SDK's and tools" apears and showme the instaled Sdk's (12,0, 9.0 and 8.1 versions are instaled)

I installed everything as described in https://platform.uno/docs/articles/get-started-vs-2022.html#prerequisites. I also installed and executed correctly the "uno-check".

The WASM and UWP projects work perfectly, but the MOBILE project does not.

Any idea?

**Comment by jeromelaban** [comment]
Thanks for the report. VS 17.0 is not supported for .NET 6 mobile projects. You'll need to update to VS 17.1 preview 1 (see the [prerequisites documentation](https://platform.uno/docs/articles/get-started-vs-2022.html#prerequisites) for specifics on what to install).
