### ISSUE TITLE
AppBarToggleButton.IsChecked doesn't work

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#7703]
### Current behavior

`uiSelEvent.IsChecked = true;` doesn't work (setting it to false also doesn't work).

It did work in Uno 3.8.13 (works in my Anniversaries app in Google Store, https://play.google.com/store/apps/details?id=pkar.Anniversaries)

EDIT: it works also in Uno 3.11.6, but doesn't work in 4.0.7.

### Expected behavior

Changing IsChecked from code should be (again) available.

### How to reproduce it (as minimally and precisely as possible)

Full code of my app is here:
https://github.com/pkar70/Anniversaries
Method starting in line 925 https://github.com/pkar70/Anniversaries/blob/master/Anniversaries/Anniversaries.Shared/MainPage.xaml.cs

### Works on UWP/WinUI

Yes

### Environment

Other

### NuGet package version(s)

"Uno.UI" Version="4.0.11"
"Uno.UniversalImageLoader" Version="1.9.35"
"Uno.UI.Adapter.Microsoft.Extensions.Logging" Version 4.0.11

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

Version 17.0.4

**Comment by jeromelaban** [comment]
@kazo0 looks familiar ?

**Comment by kazo0** [comment]
Hmm strange, I will take a look
