### ISSUE TITLE
[WPF] AppBarButton does not have the same behavior as UWP

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#7704]
### Current behavior

AppBarButton Label is left aligned.

![immagine](https://user-images.githubusercontent.com/12531229/147659311-629e2f5f-f470-410c-a50a-2e08540dd4e3.png)

### Expected behavior

AppBarButton Label is cente aligned.
![immagine](https://user-images.githubusercontent.com/12531229/147659082-73ff64a7-22b6-4d52-b160-ccadfbcfcdc3.png)

### How to reproduce it (as minimally and precisely as possible)

1.  Create an Uno app through VS extension
2. Add following xaml on MainPage.xaml:
   ```xml
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <CommandBar
                HorizontalAlignment="Right">
            <AppBarButton
                    Icon="OpenFile"
                    Label="Open"
                    Width="50"
                    />
            <AppBarButton
                    Icon="Save"
                    Label="Save"
                    Width="50"/>
        </CommandBar>
    </Grid>
     ``` 
3. Run app on UWP and WPF and click on `...`

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI.Skia.Wpf 4.0.11

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.1.0 Preview 1.1

**Comment by jeromelaban** [comment]
@kazo0 does this look familiar ?

**Comment by kazo0** [comment]
Looks like the `TextAlignment` property on `TextBlock` isn't implemented for Skia platforms

**Comment by jeromelaban** [comment]
See #4309
