### ISSUE TITLE
[WPF] Symbols is not consistent with UWP

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#7705]
### Current behavior

WPF Skia
![immagine](https://user-images.githubusercontent.com/12531229/147669043-de4ca4bd-ffdf-48c3-b63a-c8bc9a30a06d.png)

### Expected behavior

UWP
![immagine](https://user-images.githubusercontent.com/12531229/147669110-ea1115f1-6d1a-4a13-aa17-0d0a7306f2f4.png)

### How to reproduce it (as minimally and precisely as possible)

1. Create an Uno app through VS extension
2. Add following xaml on MainPage.xaml: 
   ```xml
       <SymbolIcon Symbol="OpenFile" Width="32" Height="32" HorizontalAlignment="Center"/> 
   ```
3. Run app on UWP and WPF 

### NuGet package version(s)

Uno.UI.Skia.Wpf 4.0.11

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.1.0 Preview 1.1

**Comment by jeromelaban** [comment]
Thanks for the report. The icons Uno is using are not the same as the ones provided by Microsoft's fonts. It may converge at some point, see https://github.com/unoplatform/uno/issues/5734 for more details.
