### ISSUE TITLE
Failed to match method call onEditorSelectionChanged

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#7724]
### Current behavior

_report from https://github.com/unoplatform/uno/discussions/7723?converting=1_

Errors like this one appear in Visual Studio:

```
Failed to match method call Microsoft.WebTools.BrowserLink.LivePreview.LivePreviewExtensionFactory.onEditorSelectionChanged
```

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
@DierkDroth Could you provide more details about what you're seeing? Where is this located, and when?

**Comment by DierkDroth** [comment]
Hmm .. tried to reproduce by clicking again through my app. No dice so far ... will keep trying to collect more info

**Comment by francoistanguay** [comment]
Is this still valid? Can we repro or should we close it?

**Comment by DierkDroth** [comment]
@francoistanguay thanks for follow up. I confirm that I no longer see this output using latest UNO 4.2 bits.
