### ISSUE TITLE
FS.syncfs operations in flight at once

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#7725]
### Current behavior

When running a Wasm application, the following warning may appear:

```
FS.syncfs operations in flight at once
```

### Expected behavior

No warning.

### How to reproduce it (as minimally and precisely as possible)

Make modifications to the virtualized file system, forcing synchronizations.

### Workaround

None.

### Note for contributors

Fixing this implies queuing calls to this method, from the timer defined above: 

https://github.com/unoplatform/uno/blob/f216b7c59b82a0619d4b561fca2343e37c041a3a/src/Uno.UI/ts/Windows/Storage/StorageFolder.ts#L94

**Comment by DierkDroth** [comment]
This I actually got again right now. Appears to be reproducible after clicking randomly through my app from 1-2 minutes.

**Comment by DierkDroth** [comment]
Excellent! Thanks @jeromelaban. I actually got it again this very minute ... :-)
