### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'DisableFrameReporting')

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#7726]
### Current behavior

When running a WebAssembly application, the following errors appear:

```
TypeError: Cannot read properties of undefined (reading 'DisableFrameReporting')
```

### Expected behavior

No error.

### NuGet package version(s)

4.0.11

**Comment by jeromelaban** [comment]
@DierkDroth would you have additional context into where/when this error appear?

**Comment by DierkDroth** [comment]
I just got this again after clicking through my app randomly for 1-2 minutes. So far this 'always' appears to show *after* I saw [this one](https://github.com/unoplatform/uno/issues/7725)

**Comment by DierkDroth** [comment]
@jeromelaban I still can't put my finger on it. However, I get it all the time. Regardless of what I'm testing in my app, it shows 100% reliable after 1-2 minutes

**Comment by DierkDroth** [comment]
Alright @dr1rrb Can't wait to test this fix. Thanks!

**Comment by DierkDroth** [comment]
I just ran some tests using latest Uno.Wasm.Bootstrap 3.2.0-dev.24 and still see this error after clicking through my app for a few minutes. 

Is that expected?

**Comment by jeromelaban** [comment]
This is fixed in Uno.UI not the bootstrapper.

**Comment by DierkDroth** [comment]
@jeromelaban now I'm confused: There is no Uno.UI package in my WASM head (below).

What am I missing?

![image](https://user-images.githubusercontent.com/26179242/151800968-32321e7d-9b01-4590-b67c-9de92a34d1c2.png)

**Comment by dr1rrb** [comment]
In you case it's `Uno.WinUI.Webassembly`

**Comment by DierkDroth** [comment]
@dr1rrb thanks for clarification. I just updated to the latest Uno.WinUI.WebAssembly 4.1.0-dev.545 and will let you know if I still it.
