### ISSUE TITLE
[Wasm] Debugger is not configured by default

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#7737]
### Current behavior

- create solution template as per [here](https://platform.uno/docs/articles/get-started-winui3.html)
- start VS 2022 and update to latest NuGet packages
- place breakpoint somewhere in App.xaml.cs
- build and start WASM

-> breakpoint not hit and tons of errors in browser console

This makes it impossible to use the template as a reference to e.g. iron out issues when migrating from older UNO versions :-(

> ​ fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint [fe80::1dbb:75df:6d18:3fe3].
eval @ unknown
​ fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 192.168.178.64.
eval @ unknown
​ fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint [fe80::2d92:3431:e709:9cfd].
eval @ unknown
​ fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 169.254.156.253.
eval @ unknown
​ fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint [fe80::51a8:9d4:f975:115d].
eval @ unknown
​ fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 169.254.17.93.
eval @ unknown
​ fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint [fe80::d4fb:71cd:dc60:a1c0].

### Expected behavior

Building a WASM project from suggested template should work no problem

### How to reproduce it (as minimally and precisely as possible)

Above

### Workaround

Unknown

### Works on UWP/WinUI

No

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Latest

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
Thanks for the report. The template is working as expected on our side, given that the debugger is configured using the [instructions here](https://platform.uno/docs/articles/debugging-wasm.html?q=inspectUri).

The errors you are specifying in this issue are not relevant to the debugger not starting, but rather for hot reload. It may indicate that the visual studio instance you are using does not have the Visual Studio Uno Platforn extension installed.

**Comment by DierkDroth** [comment]
That is interesting. Since right now I'm debugging my migrated WASM project with VS2022 + .NET6 no problem: no such errors in the browser console and breakpoint work as expected.

**Comment by jeromelaban** [comment]
Thanks. Does this mean you got it to work properly?

**Comment by DierkDroth** [comment]
No
- default UNO template: can't set breakpoint, errors in browser console as per above
- my migrated custom solution: I can set breakpoints, no such errors in browser console

Both in VS2022 + WinUI3 + .NET6

**Comment by jeromelaban** [comment]
Have you tried the steps mentioned in the documentation? We do not have enough information to troubleshoot the issue.

**Comment by DierkDroth** [comment]
No, not for now. 

The purpose of this exercise was to figure out why I don't get the UNO00001 (unsupported) warnings in my migarted custom solution. However, as per my other posts/threads I'm now confident that comparing the 'boiler plate' UNO solution template with my migrated custom solution won't tell my anything.

In any case: while messing I came across issues above and figured I should let you know.

**Comment by DierkDroth** [comment]
I believe I now know the cause of trouble: if you have 2 or more VS instances up then they might be fighting for ports. Could that be case?

I just confirmed by shutting down all VS instances - bar one - and the issue is gone.
