### ISSUE TITLE
[WASM] Keyboard tab navigation into application from address bar does not focus a control

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno#7742]
### Current behavior

We have users that are tabbing into the application from the address bar.  This doesn't appear to focus something they can interact with on the first tab.  They have to tab a second time to focus a button.

When using Chrome developer tools to view the document.activeElement, it appears to be focusing a ScrollViewer in the main Window control template outside of our MainPage.
![image](https://user-images.githubusercontent.com/67480815/148116529-85fa6976-da00-432a-b4ca-6caf047a7793.png)

![image](https://user-images.githubusercontent.com/67480815/148116631-695cb81b-2ada-4611-b705-193676318d43.png)

I've tried to look up through the visual tree on startup and disable tab stop and interaction with the ScrollViewer, but doesn't seem to fix the issue.  If this isn't a bug, is there a workaround?

### Expected behavior

First focusable control within the app would receive focus.

### How to reproduce it (as minimally and precisely as possible)

Attaching a sample sln.
[App1.Shared.zip](https://github.com/unoplatform/uno/files/7810118/App1.Shared.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

<PackageReference Include="Uno.Material" Version="1.0.3" />
<PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls" Version="7.1.0-build.45.gd2e4192c8c" />
<PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid" Version="7.1.0-build.45.gd2e4192c8c" />
<PackageReference Include="Uno.Microsoft.Xaml.Behaviors.Uwp.Managed" Version="2.0.3-uno.95" />
<PackageReference Include="Uno.UI.WebAssembly" Version="3.11.6" />
<PackageReference Include="Uno.UI.RemoteControl" Version="3.11.6" Condition="'$(Configuration)'=='Debug'" />
<PackageReference Include="Uno.Wasm.Bootstrap" Version="3.0.0" />
<PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="3.0.0" />

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

Version 17.1.0 Preview 1.0

**Comment by ChaseKopp6** [comment]
The issue that we raised this ticket for has not been resolved in our web host, bringing up in meeting tomorrow

**Comment by ChaseKopp6** [comment]
Reproducing Current Issue:

URL: https://hostmasterlaunch.devx.kahua.com/web/
Username: ckopp1010+unotest@gmail.com
Pwd: Uno1234!


1. On authentication screen click on the url bar
![image](https://user-images.githubusercontent.com/87719290/152222083-4668cf57-1726-4ba4-a76d-6c3f7eb1aaa8.png)

2. Hit Tab key, notice that the control passes directly to the email address input box (correct behavior)
3. Hit tab three more times, focus will now be on the language selection dropdown
![image](https://user-images.githubusercontent.com/87719290/152222204-cc43d296-b726-42be-a793-631fe83eb1de.png)

4. Hit tab key again, the focus should pass back to the email address input box, but instead goes to invisible control

**Comment by MartinZikmund** [comment]
@ChaseKopp6 @jsinsel Can you provide a repro which shows the issue under the latest Uno.UI release? The original repro now focuses the control correctly (with latest 4.1.8), so it would be very helpful for diagnosing the problem. Thanks!

**Comment by ChaseKopp6** [comment]
brooks was able to resolve this issue on our end, closing ticket

**Comment by jeromelaban** [comment]
Thanks for the update!
