### ISSUE TITLE
[Playground]TreeView-The Arrow sign is not properly displaying.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7757]
### Current behavior

![PG-TreeView issue](https://user-images.githubusercontent.com/74563602/148418610-b501f59d-aeea-4bdc-8ef3-5ec656ef060a.png)

### Expected behavior

The Arrow sign should display properly.

### How to reproduce it (as minimally and precisely as possible)

Visit https://playgroundcanary.z19.web.core.windows.net/#passwordbox
Go to the Snippets Listview.
Click on 'TreeView' snippets option.
Observe that the Arrow sign is not properly displaying.

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
@agneszitte-nventive @MartinZikmund this looks odd. Does it look familiar ?

**Comment by sakshi173** [comment]
**Verified with latest canary build, Issue is fixed, closing it.**

![Arrow sign](https://user-images.githubusercontent.com/74563602/158653573-6bcbc653-f410-4b56-8f9a-6c1521767f56.png)
