### ISSUE TITLE
Run Uno.QuickStart/MyApp.Skia.Linux.FrameBuffer an error occurred

### ISSUE THREAD

**Issue by zxslzx** [unoplatform/uno#7770]
## What's wrong?
Cannot run Uno.QuickStart/MyApp.Skia.Linux.FrameBuffer in Ubuntu 20.04. An exception has occurred.
![image](https://user-images.githubusercontent.com/32009362/148625336-56b09373-2b3a-4ca6-ac7d-7e65921c7cf7.png)

**Comment by jeromelaban** [comment]
Thanks for the report. This was fixed in https://github.com/unoplatform/uno/pull/7579, and will be released as part of Uno 4.1, but you can use dev (pre-release, `4.1.0-dev.247` being the current latest) builds of uno in the meantime.

**Comment by zxslzx** [comment]
> Thanks for the report. This was fixed in #7579, and will be released as part of Uno 4.1, but you can use dev (pre-release, `4.1.0-dev.247` being the current latest) builds of uno in the meantime.

Thanks very much
