### ISSUE TITLE
[WASM][WinUI] Add support for changing Window cursor

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#7777]
### Current behavior

Cursor support [as per here](https://platform.uno/docs/articles/features/cursors.html) no longer works in WindowsAppSDK.

### Expected behavior

Cursor support should work

### How to reproduce it (as minimally and precisely as possible)

Please see attached where I checked if the legacy UWP way of changing cursor still work work in UNO: it wouldn't.
The new way with ProtectedCursor would not work neither.

How could cursors be changed with UNO in WindowsAppSDK?
[Cursors1.zip](https://github.com/unoplatform/uno/files/7834541/Cursors1.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

**Comment by DierkDroth** [comment]
Got it. Thanks for your feedback @jeromelaban

**Comment by CesarRabelo** [comment]
Hi @DierkDroth could you send me more information about this issue? I Downloaded your zip and executed here on Wasm and the cursor is changing as expected.  

What template did you use to create your sample? I would like to reproduce in a new blank project to make more tests.
![image](https://user-images.githubusercontent.com/790876/157457457-7972c7a9-dbb3-47a5-ae56-5309073f585d.png)

**Comment by DierkDroth** [comment]
@CesarRabelo thanks for follow up
- I downloaded project from link I provided in my post above
- updated UNO to latest pre-release bits

-> in WASM pointers still would *not* change as  they do in WinUI

What are you doing different?

Also: I had created the project above of templates as they had been provided [here](https://platform.uno/docs/articles/get-started-winui3.html)

**Comment by carldebilly** [comment]
@DierkDroth: I just tried your packages and updated to latest released version of dependencies:
* Uno.WinUI.WebAssembly v4.1.8
* Uno.Wasm.Bootstrap v3.2.0

And here's the result:
![WasmWinUICursor](https://user-images.githubusercontent.com/4174207/157475037-8a34fe45-42fd-4709-b0f2-92cca0b386d6.gif)

From my point of view the feature is working well on WinUI/Wasm.

**Comment by michael-hawker** [comment]
This was originally tagged with WinUI? `ProtectedCursor` is still marked as unimplemented:

https://github.com/unoplatform/uno/blob/3fe3862b270b99dbec4d830b547942af61b1a1d9/src/Uno.UI/UI/Xaml/UIElement.cs#L1015-L1023

Was this issue supposed to be tracking that?
