### ISSUE TITLE
[Gallery][Skia.GTK] Overview (Cupertino) - FontWeight is not correct for the text of different controls.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7782]
### Current behavior

![Font issue](https://user-images.githubusercontent.com/74563602/156640274-aae1cd7b-0694-4d18-9331-e3ffa4f1f4fa.png)

### Expected behavior
FontWeight for the text of different controls should be correct. 
Below is the screenshot from **WASM platform** to see the correct format of the text.

![Font issue correct](https://user-images.githubusercontent.com/74563602/156639094-d9286fc2-1155-4046-947c-73d982d7b8b6.png)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app on Skia.GTK.
2. Click on “Cupertino" section on the "overview" page.
3. Observe that for different controls the text font is not correct, for Example for "Textbox" control the written text "placeholder single line" is not properly visible.

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by agneszitte-nventive** [comment]
FontWeight seems not taken into account for example for Skia for the Cupertino font
![image](https://user-images.githubusercontent.com/16295702/156626601-675ea0b6-53e0-462a-986e-77103a43b8f5.png)

Some of the rendering techniques are not yet decided for TextBlock for Skia, here are some related items that can be work on at the same time:
- https://github.com/unoplatform/uno/issues/7204
- https://github.com/unoplatform/uno/issues/5735
Related to the [[Epic] Skia Rendering Backend Support](https://github.com/unoplatform/uno/issues/4309)

**Comment by MartinZikmund** [comment]
@sakshi173 can you please verify this is fixed now?

**Comment by silviuo** [comment]
Closing as fixed. Tested on Skia.Gtk latest master on Windows.

![image](https://github.com/unoplatform/uno/assets/10283398/ca4fd487-72f3-4e34-a8bd-8623f822a06b)
![image](https://github.com/unoplatform/uno/assets/10283398/ecb9419f-5c0c-484f-9288-23321e83318e)
