### ISSUE TITLE
[Skia][WPF] await FileIO.Write errors if file does not already exist before writing

### ISSUE THREAD

**Issue by bstrother1** [unoplatform/uno#7783]
### Current behavior

Currently FileIO.WriteMethods error out with a 'could not find file ./filepathhere'. This does not occur in UWP build. Code is directly copy/pasted from https://platform.uno/docs/articles/features/windows-storage-pickers.html under FileSavePicker. 

### Expected behavior

FileIO.Write to not error out and mirror how UWP works. 

### How to reproduce it (as minimally and precisely as possible)

-Have a button
-Implement await File.IO.Write upon button click
[WritingFileWithWPF.zip](https://github.com/unoplatform/uno/files/7839627/WritingFileWithWPF.zip)

### Workaround

None

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

[WPF]
PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0"
PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" 
PackageReference Include="Uno.UI.Skia.Wpf" Version="4.0.11" 
PackageReference Include="Uno.UI.RemoteControl" Version="4.0.11" Condition="'$(Configuration)'=='Debug'"
PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.0.11" 

[WPF Host]
PackageReference Include="Uno.UI.Skia.Wpf" Version="4.0.11" 
PackageReference Include="Uno.UI.RemoteControl" Version="4.0.11" Condition="'$(Configuration)'=='Debug'" 
PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.0.11" 

[UWP]
PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform"
      6.2.11
/PackageReference
PackageReference Include="Microsoft.UI.Xaml" Version="2.6.2" 
PackageReference Include="Uno.UI" Version="4.0.11" 
PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" 
PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="5.0.0"
PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.0-dev.7"

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.0.4

**Comment by jeromelaban** [comment]
@MartinZikmund does this look familiar ?
