### ISSUE TITLE
[SyncFusion][date time picker] Popup

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#7800]
Implement Windows.UI.Xaml.Controls.Primitives.Popup.Child Windows.UI.Xaml.Controls.Primitives.Popup

## Why is this needed:
Used by Syncfusion datetime picker control
## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly

**Comment by jeromelaban** [comment]
Popup.Child is implemented in Uno 4.0: 
https://github.com/unoplatform/uno/blob/93cff21fb0d05ed8409f008e7ce904aeb0199232/src/Uno.UI/UI/Xaml/Controls/Popup/Popup.Legacy.cs#L60

Can you revalidate ?

**Comment by paulovila** [comment]
yes is showing : ) I may have seen this on the 3.X
