### ISSUE TITLE
[Gallery][iOS] DatePicker(Native) The calendar for Date picker is blank.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7822]
### Current behavior

![datepicker](https://user-images.githubusercontent.com/74563602/149556496-168228b3-a3ec-4419-b5ea-70f1bbcaacda.png)

### Expected behavior

The calendar should display properly.

### How to reproduce it (as minimally and precisely as possible)

Open Uno Gallery APP
Click Burger Menu on the left top right.
Click "DatePicker" from the "Component" list.
Go to 'Native' section.
Click on 'Enter date' option.
Observe that the calendar for Date picker is blank.

### Affected platforms

iOS

**Comment by Xiaoy312** [comment]
unable to reproduce using latest master with Uno.UI@4.2.0-dev.29
native `DatePicker` shows the native picker with the spinning wheels
`CalendarDatePicker` shows this flyout but the text are visible:
![image](https://user-images.githubusercontent.com/2359550/154995610-cbe065e1-ac1a-42d1-a425-ecaf3436db7d.png)
