### ISSUE TITLE
[Skia][WPF] RenderSize is `[0,0]` when generating the control in the event handler

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#7829]
### Current behavior

Considering a code like this:

```csharp
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            Do();
        }

        async void Do()
        {
            var border = new Border()
            {
                Background = new SolidColorBrush(Windows.UI.Colors.Red),
            };
            GeneratedContent.Children.Add(border);
            await Task.Yield();
            Console.WriteLine(border.RenderSize);
        }
```
If you run the Skia.WPF project, the line: `Console.WriteLine (border.RenderSize);` returns 0,0 in UWP works as expected.

### Expected behavior

Give RenderSize

### How to reproduce it (as minimally and precisely as possible)

- Download [Dispatcher_Issue.zip](https://github.com/unoplatform/uno/files/7874791/Dispatcher_Issue.zip)
- Add breckpoint at line `Console.WriteLine(border.RenderSize);'
- Run in UWP Project
- Click on Generate
- You can see correctly RenderSize
- Run Skia WPF
- Click on Generate
- RenderSize is 0,0

### Workaround

Add the following code at the beginning of the method how to generate the UI:

```csharp
var ctx = new Uno.UI.Dispatching.CoreDispatcherSynchronizationContext(Uno.UI.Dispatching.CoreDispatcher.Main
				, Uno.UI.Dispatching.CoreDispatcherPriority.Normal);
System.Threading.SynchronizationContext.SetSynchronizationContext(ctx);
```

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Tested on `Uno.UI 4.0.11` abd `Uno.UI 4.1.0-dev.324`

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.1.0 Preview 1.1

### Anything else we need to know?

WPF replace CoreDispatcherSynchronizationContext with own DispatcherSynchronizationContext

**Comment by Youssef1313** [comment]
On UWP, I see the size being `0, 0`:

![image](https://github.com/unoplatform/uno/assets/31348972/41ae4332-836f-4173-903d-8a7c6bfb11a6)

So I don't see what is the issue here.

**Comment by Youssef1313** [comment]
While the original report isn't reproducible, I can see that SynchronizationContext.Current is using WPF's synchronization context. Not sure how much of an issue is this though.

**Comment by Youssef1313** [comment]
If an extra breakpoint is added to `Do();` call, the behavior starts changing in UWP and an actual render size is produced, but then, the same happens with Uno as well.

**Comment by MartinZikmund** [comment]
@ebariche What do you think about the `SynchronizationContext` issue above? It seems we didn't observe the fact that WPF overrides it for us until now, which seems to indicate it does not actually cause trouble, but I am not sure
