### ISSUE TITLE
Multipage app

### ISSUE THREAD

**Issue by Mauterix** [unoplatform/uno#7832]
Hello please add Multiple pages project sample

I think multipage is neccesary 
## For which Platform:

- [* ] iOS
- [* ] Android
- [* ] WebAssembly
- [ *] WebAssembly renderers for Xamarin.Forms
- [ *] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ *] Windows

**Comment by MartinZikmund** [comment]
@Mauterix You can either use the built-in navigation facilities of UWP/WinUI (https://docs.microsoft.com/en-us/windows/apps/design/basics/navigate-between-two-pages) or use Uno.Extensions (https://github.com/unoplatform/uno.extensions/blob/main/doc/07-Navigation.md). For the basic navigation, any UWP/WinUI navigation sample works for Uno Platform as well. For Uno.Extensions usage, you can check out the Uno Commerce app (https://github.com/unoplatform/uno.extensions/tree/main/samples/Commerce)

**Comment by MartinZikmund** [comment]
Is there anything you are missing in these links that would be useful to document?
