### ISSUE TITLE
[CI] Add links to build artifacts in the PR discussion

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#7834]
## What would you like to be added:
When publish a PR, add links to build artifacts in the PR discussion. 

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
@jeromelaban I am not sure whether the pipelines are publicly accessible?

**Comment by workgroupengineering** [comment]
https://platform.uno/docs/articles/contributing/build-artifacts.html

**Comment by jeromelaban** [comment]
Those are publicly accessible, but we cannot add links to the artifacts in many configurations (e.g. forked builds). The only viable way for now is to navigate through checks.

**Comment by workgroupengineering** [comment]
This is accessible
https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=39700&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by jeromelaban** [comment]
It's already accessible, and explained in documentation, let's close this for now.
