### ISSUE TITLE
[WASM] Can't Focus to JavaScript Component after Build 4.1.0-dev.241

### ISSUE THREAD

**Issue by iosub** [unoplatform/uno#7848]
### Current behavior

After updating to Uno.UI.WebAssembly  4.1.0-dev.241 from 4.1.0-dev.225 JavaScript Component cant get Focus..
Example video

https://user-images.githubusercontent.com/1330995/149847843-b870d2a3-e63c-4045-92fc-4896eea38a08.mp4

### Expected behavior

With build 4.1.0-dev.225 it gets focus

https://user-images.githubusercontent.com/1330995/149847899-c740c4fe-dc6e-4d95-b6b6-e67da89144fe.mp4

### How to reproduce it (as minimally and precisely as possible)

here is a project sample
[TestJsControls.zip](https://github.com/unoplatform/uno/files/7885145/TestJsControls.zip)

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.1.0-dev.241

### Affected platforms

WebAssembly

**Comment by dr1rrb** [comment]
@iosub I'm still looking to get a fix for it, but FYI you can workaround this issue by setting `Uno.UI.FeatureConfiguration.FrameworkElement.UseLegacyHitTest = true;` (in the constructor of your app in `App.xaml.cs`).

**Comment by iosub** [comment]
> @iosub I'm still looking to get a fix for it, but FYI you can workaround this issue by setting `Uno.UI.FeatureConfiguration.FrameworkElement.UseLegacyHitTest = true;` (in the constructor of your app in `App.xaml.cs`).

Yes it works! thank you
