### ISSUE TITLE
x:Bind Pathless Casting (this) references cause source generator error

### ISSUE THREAD

**Issue by hawkerm** [unoplatform/uno#7893]
### Current behavior

Was using [pathless casting](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension#pathless-casting) in UWP data template to bind to the 'this' object of the data template:
```xml
<DataTemplate x:DataType="local:SomeTypeName">
  <local:MyControl MyProperty="{x:Bind (local:SomeTypeName)}"/>
</DataTemplate>
```

This gave me the following error when trying to run in WASM:

```
Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_bf38630c1c1d5b8ecc552685d35228f7.cs(914,322,914,324): error CS7000: Unexpected use of an aliased name
```

Switching out to old-style `{Binding}` syntax allowed me to compile.

### Expected behavior

Should accept the pathless casting syntax for x:Bind.

### Workaround

Switch x:Bind pathless cast to Binding if only doing direct. Not sure if there's the same issue for function binding which I'm not sure how you'd work around.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.0.11

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.0.5

**Comment by jeromelaban** [comment]
Thanks for the report! Would you have the exact type that was bound? We're looking for an exact repro, as previous ones we got were not successful.

**Comment by hawkerm** [comment]
It's my own type implemented in my project:

```cs
public partial class MyClass : ObservableObject
{
```

With a couple of simple properties (string and custom enum), nothing more.

It is being built using the new MVVM Toolkit source generators (initially V1, now V2), so maybe there's a conflict between the two source generators somehow? (If you're not seeing it with regular types?)

Though I tried switching it to a regular `ObservableObject` without the partial class and think I'm still getting the same message. So it may _not_ be related.

If I remove the pathless cast to the whole type, and instead use a specific property, then I don't get the error message.

**Comment by jeromelaban** [comment]
Thanks for the update! Yes it may seem that the parser is not handling this very well.

## Note for contributors
This is the location of the parser tests: 

https://github.com/unoplatform/uno/blob/bb3f815fc8b9ce569dd695625bc7af45587c1464/src/SourceGenerators/Uno.UI.SourceGenerators.Tests/Given_XBindRewriter.cs#L10-L31

**Comment by michael-hawker** [comment]
I think this is for any types of parentheses; so not just pathless casting, but for attached properties as well (i.e. uno only looking for function and casting scenarios):

```
"{x:Bind AdornerCanvas.(labs:FrameworkElementExtensions.ActualWidth), Mode=OneWay}"
```

Hit above in labs trying to use our helpers in the Toolkit for size binding.

From the official docs, see https://learn.microsoft.com/windows/uwp/xaml-platform/x-bind-markup-extension#attached-properties

> Text="{x:Bind Button22.(Grid.Row)}"
