### ISSUE TITLE
Implement using Windows.Web.Http.HttpClient

### ISSUE THREAD

**Issue by queequac** [unoplatform/uno#79]
Unfortunately Uno supports just .NET Standard's System.Net.HttpClient and not UWP's counterpart in the Windows namespace.

While these clients are somehow exchangeable, UWP's http client has for example HttpBaseProtocolFilter (such as for ignoring certificate errors, activating automatic decompression, etc.) my app relies on.

If it's called #uwpeverywhere, you should provide the UWP http client. :)

**Comment by jeromelaban** [comment]
Thanks for the report.

Yes, it's #uwpeverywhere, yet we still had to make choices to get to this point and in this case, we prioritized those UWP APIs implementations based on their relative presence in the .NET Standard 2.0 contract.

**Comment by MartinZikmund** [comment]
Duplicate of #5915
