### ISSUE TITLE
[WindowsAppSdk][VS2022][.NET 6] Material design not working

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#7905]
### Current behavior

The designer team which I contracted is working on a design derived from the UNO material design which I tried to setup [as per here](https://platform.uno/docs/articles/features/uno-material.html). However I'm getting tons of errors when trying to compile. Here are some samples:

`
3>C:\Users\ddroth\Documents\Unusual.CRM\Unusual.Shared\App.xaml.cs(308,17,308,22): error CS0433: The type 'Color' exists in both 'Microsoft.Windows.SDK.NET, Version=10.0.19041.22, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
3>C:\Users\ddroth\Documents\Unusual.CRM\Unusual.Shared\App.xaml.cs(310,17,310,21): error CS0433: The type 'Rect' exists in both 'Uno.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' and 'WinRT.Runtime, Version=1.4.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709'
3>C:\Users\ddroth\Documents\Unusual.CRM\Unusual.Shared\Document\DocumentSelectorGrid.cs(358,33,358,45): error CS0433: The type 'IStorageItem' exists in both 'Microsoft.Windows.SDK.NET, Version=10.0.19041.22, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
`

Also, there are errors in App.xaml as well

`
A value of type 'MaterialColors' cannot be added to a collection or dictionary of type 'IList1.	Unusual.Windows	C:\Users\ddroth\Documents\Unusual.CRM\Unusual.Shared\App.xaml	12
`

I needed to get Material design working as promoted by UNO. What would I need to do?

### Expected behavior

Material design should work as promoted

### Works on UWP/WinUI

No

**Comment by DierkDroth** [comment]
FYI for anyone who's running into that issue as well: 
- I ripped apart the Uno.Themes source solution/project
- pulled out the XAML + CS files which I needed for Material design in WinUI3 + .NET6
- applied tweaks as needed/desired (e.g. remove dependencies on Lottie and Uno.UI.Toolkit)

I'll close that issue since I'm good to go for now - although there definitely is work left for the UNO team.

**Comment by kazo0** [comment]
Re-opening and assigning to myself. Will investigate today

**Comment by kazo0** [comment]
Hi @DierkDroth! Do you by chance still have the App.xaml and App.xaml.cs files that were failing the build? I'd love to see what those files looked like at the time of the failures.

Also, was this occuring when you build the Windows head only? Or all of the projects?

**Comment by DierkDroth** [comment]
@kazo0 I'm sorry, I deleted the repo after I was able to integrate the parts which I needed in my solution.

As far as I recall I deleted anything apart from the WASM and WinUI heads. Hope this helps.

**Comment by kazo0** [comment]
I am unable to repro these exact errors when using the 4.1.0-dev### templates and having the Uno.Material.**WinUI** package installed and initialized through the App.xaml. 

I was, however, able to get similar sounding errors if I tried to use the **non-WinUI** version of Uno.Material. 
```
1>C:\src\MyBetterOtherNewApp\MyBetterOtherNewApp.Shared\App.xaml.cs(107,50,107,69): error CS0433: The type 'SuspendingEventArgs' exists in both 'Microsoft.Windows.SDK.NET, Version=10.0.19041.22, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
1>Done building project "MyBetterOtherNewApp.Windows.csproj" -- FAILED.
```

My thinking is that maybe @DierkDroth you were using the non-WinUI version of the Uno.Material NuGet package?

I can close this issue since it doesn't seem to occur on the latest versions of the template.

**Comment by DierkDroth** [comment]
Understand. Thanks for looking into anyway @kazo0 

It might help amending the docs I linked above to avoid further confusion.

**Comment by kazo0** [comment]
Ah you're right, we don't mention the Uno.Material.WinUI scenarios in the docs. I will make an issue for that
