### ISSUE TITLE
Compilation of .net6 WinUI edition broken since last two Visual Studio 2022 Preview 

### ISSUE THREAD

**Issue by cmonto** [unoplatform/uno#7913]
### Current behavior

Uno projects does not compile since Visual Studio 2022 version 17.1.0 Preview 3. If Uno.WinUI Package Reference is commented out in csproj, then the project compiles fine (can't have uno classes reference in code - hence really not a workaround). With Uno package reference the following errors come up:
`1>Uno.UI is using Roslyn generators
1>CSC : error CS2015: 'C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\analyzers\Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\analyzers\Microsoft.CodeAnalysis.NetAnalyzers.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\Uno.Analyzers.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Microsoft.ApplicationInsights.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Microsoft.DotNet.PlatformAbstractions.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Mono.Cecil.Mdb.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Mono.Cecil.Pdb.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Mono.Cecil.Rocks.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Mono.Cecil.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\System.Diagnostics.DiagnosticSource.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Uno.UI.SourceGenerators.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Uno.Xaml.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.1\analyzers\dotnet\cs\System.Text.Json.SourceGeneration.dll' is a binary file instead of a text file
1>Done building project "UnoLibrary.csproj" -- FAILED.
1>Uno.UI is using Roslyn generators
1>CSC : error CS2015: 'C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\analyzers\Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\analyzers\Microsoft.CodeAnalysis.NetAnalyzers.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\Uno.Analyzers.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Microsoft.ApplicationInsights.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Microsoft.DotNet.PlatformAbstractions.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Mono.Cecil.Mdb.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Mono.Cecil.Pdb.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Mono.Cecil.Rocks.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Mono.Cecil.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\System.Diagnostics.DiagnosticSource.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Uno.UI.SourceGenerators.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Users\username\.nuget\packages\uno.winui\4.0.11\analyzers\dotnet\cs\Uno.Xaml.dll' is a binary file instead of a text file
1>CSC : error CS2015: 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.1\analyzers\dotnet\cs\System.Text.Json.SourceGeneration.dll' is a binary file instead of a text file
1>Done building project "UnoLibrary.csproj" -- FAILED.
`

### Expected behavior

Uno projects should compile and run successfully.

### How to reproduce it (as minimally and precisely as possible)

[UnoLibrary.zip](https://github.com/unoplatform/uno/files/7940885/UnoLibrary.zip)

### Workaround

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI 4.0.11

### Affected platforms

iOS, Android

### IDE

Visual Studio 2022

### IDE version

17.1.0 Preview 4

### Anything else we need to know?

Was working fine before last two VS2022 Previews.

This was tested in two machines and was reproduced in both - one with VS2022 17.1.0 Preview 3, and other with 17.1.0 Preview 4.

**Comment by jeromelaban** [comment]
Thanks for the report, this is fixed by https://github.com/unoplatform/uno/pull/7909

**Comment by cmonto** [comment]
Any idea when this is going to be released pls? My development is stalled.

**Comment by jeromelaban** [comment]
You can use the latest Uno 4.1-dev bits. Remember that you're using preview bits, features can break easily (Uno, .NET, VS), you may want to keep using stable releases to make sure that you're not blocked.

**Comment by joshcomley** [comment]
Hi there - how can we go about using the dev bits?

**Comment by joshcomley** [comment]
Ah figured it out

    dotnet new --install Uno.ProjectTemplates.Dotnet::4.1.0-dev.511

Then new project compiles, I can work the rest out from here. Thanks!
