### ISSUE TITLE
[macOS] `RadioButtons` nested in `SplitView` not working correctly

### ISSUE THREAD

**Issue by oldnik1** [unoplatform/uno#7937]
### Current behavior

I've encountered a strange behavior with a RadioButton nested inside a SplitView on the macOS platform. It seems to not work at all. I've also checked this on Android, Windows and Linux in another project and everything seems to work fine.

### Expected behavior

RadioButtons nested in SplitView works correctly

### How to reproduce it (as minimally and precisely as possible)

Create simple project with SplitView and nest the RadioButton within.
[Sample.zip](https://github.com/unoplatform/uno/files/7957404/Sample.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.0.11

### Affected platforms

macOS

### IDE

Visual Studio 2019

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
