### ISSUE TITLE
Xaml parsing of Binding with custom converter and expression as converter parameter doesn't work

### ISSUE THREAD

**Issue by mterwoord** [unoplatform/uno#7947]
### Current behavior

I made a custom value converter and a custom markup expression. It basically allows me to bind to a boolean property, and then conditionally return 1 out of 2 values.
See attached project. 
MainPage contains 1 CheckBox and 1 TextBlock. Checking the CheckBox should make the textblock show its text bigger.

Compiling the FontSize expression gives me the following exception:

`MSBUILD : error : Generation failed: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Generation failed for Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator. System.AggregateException: Er zijn één of meer fouten opgetreden. ---> Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException: Expected '}' in the markup extension attribute: '{expressions:ConditionalValuesExpression TrueValue=24' `

### Expected behavior

At runtime, checking the checkbox should make the text in the textblock bigger. 

### How to reproduce it (as minimally and precisely as possible)

Build attached solution. 
I verified, the very same solution works fine on WinUI with MS tooling.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia, Uno.SourceGenerationTasks

### NuGet package version(s)

- Uno.WinUI*: 4.1.0-dev.542
- 

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows), Build tasks

**Comment by jeromelaban** [comment]
Thanks for the report. Would you be able to post a sample or XAML that demonstrates how to reproduce this ?

**Comment by mterwoord** [comment]
Shoot. I already had the zip. See attached
[XamlParsingBugRepro.zip](https://github.com/unoplatform/uno/files/7971263/XamlParsingBugRepro.zip)
