### ISSUE TITLE
[WindowsAppSdk][WASM] .ManipulationCompleted + .PointerReleased fired in wrong sequence

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#7951]
### Current behavior

- edit attached
- search for '!!!' and follow instructions
- start WASM and WinUI3 and observe that .PointerReleased is fired before .ManipulationCompleted on WASM **-> wrong**

[ManipulationCompleted.zip](https://github.com/unoplatform/uno/files/7965594/ManipulationCompleted.zip)

Side note: in Chrome console I again saw tons of errors (of a UNO default template created [as per here](https://platform.uno/docs/articles/get-started-winui3.html)!) which I held off wasting time trying to understand why they would show. 
You may need to resolve those before being able to get the WASM debugger working properly on the sample.

### Expected behavior

WASM should work as WinUI

### Works on UWP/WinUI

No

**Comment by DierkDroth** [comment]
@jeromelaban is there any timeline on when this would be addressed?

**Comment by jeromelaban** [comment]
We do not have a timeline for fixing this issue yet.

**Comment by DierkDroth** [comment]
Thanks for letting me know @jeromelaban

**Comment by DierkDroth** [comment]
Thanks for taking care guys. Looking forward the build which would encorporate that fix.
