### ISSUE TITLE
[WASM] Default solution template (4.0.13) has many errors in browser console log

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#7952]
### Current behavior

When setting up a test (attached) a got many new errors in the browser console (attached).
This is latest Chrome on lastest Windows 10.

[Layout.zip](https://github.com/unoplatform/uno/files/7965779/Layout.zip)
[localhost-1643540993694.zip](https://github.com/unoplatform/uno/files/7965781/localhost-1643540993694.zip)

### Works on UWP/WinUI

Yes

**Comment by MartinZikmund** [comment]
All of the errors are essentially false positives, but it would be great if we could avoid them altogether - especially for the ones we know will always happen (transitions, etc.)

**Comment by MartinZikmund** [comment]
This should now be fixed
