### ISSUE TITLE
[WindowsAppSdk][WASM] AutoSuggestBox.TextChanged: e.Reason not working

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#7957]
### Current behavior

- edit attached, find '!!!' and place breakpoint
- start WinUI and type in textbox: breakpoint not hit -> good
- start WASM and type in textbox: breakpoint is hit -> **bad**

[AutoSuggestBox2.zip](https://github.com/unoplatform/uno/files/7970271/AutoSuggestBox2.zip)

### Expected behavior

WASM should work as WindowsAppSdk: e.Reason should be set correctly

### Works on UWP/WinUI

Yes

**Comment by iury-kc** [comment]
Investigating the code, we see that the enum is not initialized (zero value) that is just UserInput.
If it is initialized as ProgrammaticChange, it returns this value everytime, unless choosing an suggestion.

I observed that OnTextBoxKeyDown is not called when the user type. Probably, the current behavior has hidden the this issue.

**Comment by DierkDroth** [comment]
@iury-kc thanks for looking into.

I'm not sure I understand: are you saying this is not a bug but working as expected?

**Comment by jeromelaban** [comment]
@DierkDroth these are observation notes, not necessarily an update that you need to take action on.

**Comment by DierkDroth** [comment]
@jeromelaban thanks for clarification.

**Comment by iury-kc** [comment]
On android, the list is not closed when AutoSuggest loose focus, like on Windows.
That prevents the Reason to be UserInput and the test fails.

**Comment by DierkDroth** [comment]
Thanks guys for working on this.

@jeromelaban I take it #8836 does not provent this working properly on Android, no? (Android is not my focus right now, but this will change in the next couple of months).
