### ISSUE TITLE
[Skia] PointerPointProperties.MouseWheelDelta isn't set

### ISSUE THREAD

**Issue by mterwoord** [unoplatform/uno#7961]
### Current behavior

Inside the `UIElement.PointerWheelChanged` event, the MouseWheelDelta is always `0`.

### Expected behavior

Inside the `UIElement.PointerWheelChanged` event, the MouseWheelDelta should reflect the actual scroll action.

### How to reproduce it (as minimally and precisely as possible)

Attach the following event handler to a page's `PointerWheelChanged` event:

```csharp
        private void OnPointerWheelChanged(object sender, PointerRoutedEventArgs e)
        {
            var point = e.GetCurrentPoint(listView);
            Console.WriteLine("Mouse wheel delta: " + point.Properties.MouseWheelDelta);

            var points = e.GetIntermediatePoints(listView);
            foreach (var item in points)
            {
                Console.WriteLine("-" + item.Properties.MouseWheelDelta);
            }
        }
```

### Workaround

I used the debugger to stop in `Microsoft.UI.Input.PointerProperties..ctor`, and copied the value from the input properties to the `this` instance, and then the correct value is shown.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.1.0-dev.461

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows)

### Anything else we need to know?

I'd be happy to make a PR for this, but I'm unsure how to build WinUI using the crosstargetting_override.props trick.

**Comment by mterwoord** [comment]
Problem is in the highlighted areas:
https://github.com/unoplatform/uno/blob/1c768b4309c93c63b388390bc41f0ced28ebc975/src/Uno.UWP/UI/Input/PointerPointProperties.cs#L16-L49

Both the method and the constructor copy properties over to an object. It misses the MouseWheelDelta.

**Comment by dr1rrb** [comment]
Thanks for the report and the investigation @mterwoord 👍

Quick notes:
* This affects only the "WinUI version" of Uno
* `XTilt` and `YTilt` are also missing

I'm about to push a commit to fix this (already had some changes in that section, so doing it on my side will avoid merge conflict :) )

**Comment by mterwoord** [comment]
@dr1rrb Your PR finally got merged. Sadly, now PointerWheelChanged even doesn't trigger anymore. So scrolling still doesn't work.

**Comment by jeromelaban** [comment]
@mterwoord I'm not observing this, the `PointerWheelChanged` event is raised properly. If you do have a more specific repro that you can provide in another issue, it'll help.

**Comment by mterwoord** [comment]
I tried once again, and now scrolling works. Weird.. 
Good news is it's fixed :-)
