### ISSUE TITLE
Cannot send client certificate from the IApiEndpointQueryContext / IServiceLocator ?

### ISSUE THREAD

**Issue by ac2021-June** [unoplatform/uno#7967]
### Current behavior

Not able to send client certificate from the IApiEndpointQueryContext / IServiceLocator.

### Expected behavior

Should be able to send client certificate from the IApiEndpointQueryContext / IServiceLocator.

### Affected platforms

iOS, Android

### IDE

Visual Studio 2019

**Comment by jeromelaban** [comment]
Closed as duplicate of https://github.com/unoplatform/uno/discussions/7966
