### ISSUE TITLE
[Gallery][WASM] CalendarView and CalendarDatePicker-Monthly calendar is blank.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7968]
### Current behavior

https://user-images.githubusercontent.com/74563602/152030035-2fbb73a1-f64c-4976-a1e5-5960ae06fa9e.mp4

![monthly calendar](https://user-images.githubusercontent.com/74563602/152030221-1b88625c-4270-48fa-aeba-365334953c75.png)

### Expected behavior

The monthly should display.

### How to reproduce it (as minimally and precisely as possible)

Open Uno Gallery APP
Click Burger Menu on the left top right.
Click "CalendarView" OR "CalendarDatePicker" from the "Component" list.
Click on the 'select a date' option
Observe that the monthly calendar is blank.

### Affected platforms

WebAssembly

**Comment by carldebilly** [comment]
@sakshi173 Unable to reproduce on 2022-02-02 using Chrome, Edge and Opera.

**Comment by sakshi173** [comment]
Not able to reproduce this issue.
