### ISSUE TITLE
[Android] Fluent theme `AppBarButton` does not render `FrameworkElement`-based `Content`

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#7970]
### Current behavior

Content of AppBarButton does not render when we have `<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />` in the `App.xaml`

Without loading the WinUI resources, the fallback style of the AppBarButton within Uno seems to work and properly displays the Content

```xml
<AppBarButton Label="Label">
    <TextBlock Foreground="Black"
                Text="TESTING" />
</AppBarButton>
```
Will only render an empty AppBarButton with its Label set:
![image](https://user-images.githubusercontent.com/4793020/152035863-47bc594c-c909-45e6-8ed3-907c6b679cb5.png)

### Expected behavior

AppBarButton should render the Content about the Label, like on iOS and when not using the FluentTheme:

![image](https://user-images.githubusercontent.com/4793020/152036518-93a68acb-cc7a-4988-ba08-fa86463eab62.png)

### Works on UWP/WinUI

Yes

### Affected platforms

Android

**Comment by MartinZikmund** [comment]
![image](https://github.com/unoplatform/uno/assets/1075116/a319d1e0-2eab-46f4-970a-35915938cb78)

Can confirm this works now!
