### ISSUE TITLE
[Docs] Add section for usage of Uno.Material/Uno.Cupertino in a WinUI/WinAppSDK app

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#7977]
## On which page?
https://platform.uno/docs/articles/features/uno-material.html
https://platform.uno/docs/articles/features/uno-cupertino.html

## What's wrong?
Documentation can be confusing for people if they are building WinUI Uno applications since there is no mention of the **Uno.Material.WinUI** and **Uno.Cupertino.WinUI** packages that should be used in that case.

related to #7905

**Comment by jeromelaban** [comment]
Should we close this ?

**Comment by MartinZikmund** [comment]
This is done
