### ISSUE TITLE
[WASM] [Skia] Changing `Padding` from `SizeChanged` handler doesn't update the layout

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#7978]
### Current behavior

Padding is not applied:
![image](https://user-images.githubusercontent.com/8270914/152196565-27e49076-d723-4e4a-a2c2-7338d9422d63.png)

Note that this means the `VisibleBoundsPadding` behavior may not work on Skia and WASM, since it updates Padding from the LayoutUpdated event. (See `Given_VisibleBoundsPadding.When_Mask_All()` test.)

### Expected behavior

Padding is applied:
![image](https://user-images.githubusercontent.com/8270914/152196643-c5aab149-d33a-4915-84d7-cfb03485bb71.png)

### How to reproduce it (as minimally and precisely as possible)

MainPage.xaml:

```xml
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <Grid x:Name="targetGrid">
            <Border Background="AliceBlue">
                <Ellipse Fill="DarkOrange" />
            </Border>
        </Grid>
    </Grid>
</Page>
```

MainPage.xaml.cs

```csharp
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
            targetGrid.SizeChanged += TargetGrid_SizeChanged;
        }

        private void TargetGrid_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            targetGrid.Padding = new Thickness(0, 34, 0, 65);
        }
    }
```

### Sample

[UnoApp1.zip](https://github.com/unoplatform/uno/files/12295373/UnoApp1.zip)

### Workaround

Dispatcher.RunAsync => InvalidateMeasure, probably

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.1.0-dev.606

### Affected platforms

WebAssembly, Skia (GTK on Linux/macOS/Windows)

**Comment by dr1rrb** [comment]
The test `When_Mask_All` fails also on Android, and has been disabled.

**Comment by ajpinedam** [comment]
It seems to be working as expected on WASM with the latest Uno Platform 

![image](https://user-images.githubusercontent.com/1900897/215891149-5db31acd-5969-4d7e-b8cd-8ec107c6b358.png)

**Comment by ajpinedam** [comment]
On Skia (WPF Host) seems to be fixed too.

|  Sans Padding | With Padding |
| :-----------: | :---------------|
|![image](https://user-images.githubusercontent.com/1900897/215892039-d4a3530c-13ff-44d3-a206-fe4285be785a.png) |![image](https://user-images.githubusercontent.com/1900897/215892090-bd2db051-da2c-40da-9e6b-cbb1891e8271.png) |

**Comment by ajpinedam** [comment]
Test `Given_VisibleBoundsPadding.When_Mask_All()` is still failing, but I noticed the test is testing something different than what is expected in this issue.

With the images above, we could validate that the Padding is being properly added when the `SizeChanged` event occurs.

**Comment by ramezgerges** [comment]
On Skia, it doesn't seem to apply the padding except after a resize.

**Comment by nguyeenvy** [comment]
I was able to reproduce this issue on both Wasm and Skia with the latest Nuget packages. I will attach the sample app in the description of this issue.

**Comment by dr1rrb** [comment]
This can be either because we are just not invalidating the measure when Padding changed. Adding the invalidate measure flag in the dependency property registration options should fix it ... but this would have impact on all platforms and probably not only en shapes so it's not really probable.

A more probable reason (but much more complex to validate and fix) it's because we are clearing the `Is<Measure|Arrange>Dirty` flags after the measure/arrange. Doing this, we cannot invalidate the layout during the layout pass which is the case here.

**Comment by dr1rrb** [comment]
BTW for the second hypothesis, a good test would to check that is changing the `Margin` property would have the same effect or not.
