### ISSUE TITLE
[WASM] File drag and drop does not work

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#7980]
### Current behavior

File drag and drop does not work for WebAssembly.
There are also weird visual issues when dragging.
![image](https://user-images.githubusercontent.com/3002068/152263194-f134be79-705f-411c-b1f2-3d76a83570fa.png)

### Expected behavior
![image](https://user-images.githubusercontent.com/3002068/152263098-a99856aa-8bf7-41e9-8afa-863483ae1a3e.png)

### How to reproduce it (as minimally and precisely as possible)
[H.ReactiveUI.CommonInteractions_Uno_DragAndDropIssue.zip](https://github.com/unoplatform/uno/files/7990996/H.ReactiveUI.CommonInteractions_Uno_DragAndDropIssue.zip)

Drag and drop any text file to TextBox.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.1.0-dev.600

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.1 preview 4

### Anything else we need to know?
DragAndDrop library implementation: https://github.com/HavenDV/H.ReactiveUI.CommonInteractions/blob/master/src/libs/H.ReactiveUI.CommonInteractions.Shared/Extensions/DragAndDropExtensions.cs

**Comment by jeromelaban** [comment]
This is not yet supported, see https://github.com/unoplatform/uno/issues/4312.

Closing as duplicate.
