### ISSUE TITLE
[Android] FolderPicker Cannot select folder that has not subolder

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#7985]
### Current behavior

 FolderPicker Cannot select folder that has not subolder
![Screenshot_1643896395](https://user-images.githubusercontent.com/12531229/152356296-afbe8e33-1f5f-4034-a8cc-a35bb0ed87d7.png)

### How to reproduce it (as minimally and precisely as possible)

1. Run SamplesApp.Droid
2. Select FolderPickerTest
3. Click on Pick Folder Buttton
4. Select a Foder that has no subfolders
5. Click on "Use this folder"
6. 3. Click on Pick Folder Buttton
7. "Use This folder" does not appear

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

master ad3420152e157dcd4e4138d2f6df54c26f4119ab

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.1.0 Preview 5

**Comment by jeromelaban** [comment]
## Note to contributors

It is likely that the issue is located in the handling of the returned value here:

https://github.com/unoplatform/uno/blob/81e9ce8aa5efc132d202777c76f900501611d163/src/Uno.UWP/Storage/Pickers/FolderPicker.Android.cs#L49-L63

**Comment by jeromelaban** [comment]
Let's close as the underlying platform does not seem to support this.
