### ISSUE TITLE
DateTimePicker flyout displays empty and then, when clicking in the chevrons it jumps to year 1921

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#7994]
### Current behavior

 Detected regression between 4.1.0-dev.471  and 4.1.0-dev.583 in DateTimePicker. The flyout displays empty and then, when clicking in the chevrons it jumps to year 1921
![image](https://user-images.githubusercontent.com/888391/152447114-986b7252-c9a9-4312-996a-1c816dd1d5a8.png)

### Expected behavior

Should display in today's month or the month that the date value is bound to

### NuGet package version(s)

Uno.UI.WebAssembly Version 4.1.0-dev.583

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
Thanks for the report. Cam you try setting this feature configuration to false:

https://github.com/unoplatform/uno/blob/81e9ce8aa5efc132d202777c76f900501611d163/src/Uno.UI/FeatureConfiguration.cs#L510

**Comment by carldebilly** [comment]
This bug is already tracked on this public issue: https://github.com/unoplatform/uno/issues/7968

**Comment by carldebilly** [comment]
Should be fixed by https://github.com/unoplatform/uno/pull/8001
