### ISSUE TITLE
CheckBox Selection is appearing incorrectly

### ISSUE THREAD

**Issue by TonyHenrique** [unoplatform/uno#80]
The CheckBox is appearing incorrectly on Android (6.0)

![screenshot_20180629-162315](https://user-images.githubusercontent.com/6307623/42113434-a148df5a-7bc1-11e8-8397-f6c9bc8c85ee.png)

**Comment by TonyHenrique** [comment]
This came from Uno Gallery on the Android Play Store.

I don't know what Uno.UI version is.

**Comment by jeromelaban** [comment]
Got it, interesting issue. Could you post which android device this is, as well as the exact Android version ?

**Comment by TonyHenrique** [comment]
Lenovo K10a40
Android 6.0
1GB RAM

It is like this
![image](https://user-images.githubusercontent.com/6307623/42113665-6dce323c-7bc2-11e8-9c93-afe3b290c60d.png)

**Comment by ghuntley** [comment]
Closing this issue out as it is quite old. If you are able to reproduce or have similar issues please open a new issue. Thankyou.
