### ISSUE TITLE
Add support for MenuFlyoutItem

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#801]
## I'm submitting a...
- Feature request

## Current behavior
`MenuItemFlyout` does not support mouse interactions and selection

## Environment

```
Nuget Package: 1.43.1

Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by MartinZikmund** [comment]
WinUI version is now part of the codebase, although there is a bug with item checkbox, will report as separate issue
