### ISSUE TITLE
Contradictorily statements in github templates

### ISSUE THREAD

**Issue by LokiMidgard** [unoplatform/uno#8022]
## On which page?

`PullRequest Template` `Documentation Issue` template

## What's wrong?

Pull request issue says
> Link to relevant GitHub issue if applicable. All PRs should be associated with an issue (GitHub issue or internal) 

Documentation issue says

>Please only use this template for reporting issues with the documentation where the fix isn't clear. We greatly appreciate it when people send in pull-requests with fixes. If there's any friction, apart from knowledge, that's preventing you from doing so please let us know below

## Any feedback?

Those two statements seem to be contradictorily. I wanted to propose a change to the getting started guide, saw the statement above, then wanted to create an issue. After all PullRequest template saied aal PRs should be associated with an issue.

Then the issue template says only open an issue when you do not know how to fix it, instead make a pull request.

**Comment by jeromelaban** [comment]
Thanks for reading the PR requirements :) Indeed, an issue is not necessarily needed for documentation. We'll clarify this.
