### ISSUE TITLE
Diagnosing Memory Issues document out of date for Uno 4

### ISSUE THREAD

**Issue by baskren** [unoplatform/uno#8026]
## On which page?
https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/troubleshooting-memory-issues.md

## What's wrong?
Reference to Uno.Extensions.Logging.Log is not present in Uno 4.0;

**Comment by baskren** [comment]
Perhaps this one is out of date as well? 

https://platform.uno/docs/articles/logging.html

**Comment by jeromelaban** [comment]
Thanks for the report. Indeed the profiling doc is not update, same for the logging doc.

**Comment by baskren** [comment]
Figured out that it works if I add 'Uno.Core' Nuget.  I'm going to take a stab at editing the docs files in question.
