### ISSUE TITLE
[NPE] Clicking on TreeView chevron expands and closes the node instantly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#8030]
### Current behavior

In [NPE canary](https://purple-pond-0688d230f.azurestaticapps.net/), clicking on the tree node expands and closes a node instantly:

![20220207-treeview-expand-chevron](https://user-images.githubusercontent.com/5839577/152826119-bf39b5ad-269e-4446-a0b0-cad3baa0495f.gif)
.

Clicking on the text next to it does not show the issue.

### Expected behavior

Tree node opens properly

### NuGet package version(s)

4.1.0-dev.724

**Comment by Xiaoy312** [comment]
by default, the TVI expands when clicked on the `>`-chevron part
however, in NPE, we wanted this "hitbox" to be the entire TVI
so, `behavior:TreeViewBehavior.AutoToggleItemExpansion` was introduced hooking into `TreeView::ItemInvoked`
in earlier version (4.0.11), clicking on `>` did not proc `ItemInvoked`,
but in the current version (4.2.0-dev.13), it nows does
\> according to uwp, TreeView::ItemInvoked **is not supposed** to proc when you click on the chevron
so now, both TVI and the behavior trigger causing this very problem

\---
note: we can sweep this issue under the rug, by adding `IsHitTestVisible="False"` onto `ExpandCollapseChevron` and rely on our behavior for the expansion.

**Comment by Xiaoy312** [comment]
the issue surfaced with #7845 (commit: 9377ad4c)
the point events, PointerPressedEvent and PointerReleasedEvent, are separate with different FrameId
i couldnt find a way to associate the two in order to ignore the 2nd
