### ISSUE TITLE
[WASM][Dark Theme] Autofill color is different from theme color

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#8046]
### Current behavior

Before autocomplete:
<img width="289" alt="image" src="https://user-images.githubusercontent.com/3002068/153125201-79a43216-36fb-4b46-95f1-04a09c59b810.png">

When trying to use chrome's autocomplete, autocomplete appears with a white background, which creates havoc along with PlaceholderText
<img width="385" alt="image" src="https://user-images.githubusercontent.com/3002068/153125178-6b08e447-3445-4053-809a-1af0f6b7ee7f.png">

### Expected behavior

The autofill color must respect the theme color or be transparent or be translucent

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.1.0-dev.724

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.1 preview 5

**Comment by KirigayaKazuto06** [comment]
Hi, I'm a new beginner and i think that i can try to solve it

**Comment by KirigayaKazuto06** [comment]
@jeromelaban, I don't know the APIs yet, but I know the base of CSS. I am ready to get acquainted or find information about CSS APIs. I also want to ask where I can find and check this bug. I don't see a registration field or a dark theme on the website now.
