### ISSUE TITLE
Uno does not support specific case with RelativeSource TemplatedParent binding

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#8049]
### Current behavior

```xml
<TextBox Text="Username">
    <TextBox.Header>
        <StackPanel>
            <TextBlock Text="Username"/>
        </StackPanel>
    </TextBox.Header>
    <TextBox.HeaderTemplate>
        <DataTemplate>
            <ContentControl
                Content="{Binding Content, RelativeSource={RelativeSource Mode=TemplatedParent}}"
                />
        </DataTemplate>
    </TextBox.HeaderTemplate>
</TextBox>
```
Binding like this is not supported by Uno. Here's my StackOverflow question about it: https://stackoverflow.com/questions/70818344/uwp-winui-override-textbox-headertemplate-so-that-it-can-display-complex-conten/70818345#70818345

### How to reproduce it (as minimally and precisely as possible)

http://playground.platform.uno/#1f901c6b

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.1.0-dev.724

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.1 preview 5

**Comment by jeromelaban** [comment]
Thanks for the report. `TemplateBinding` is behaving differently in uno currently, and this will be addressed by #1621. Close this one  as a duplicate.
