### ISSUE TITLE
UnoSolutionTemplate will not build if project name has spaces

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/uno#806]
## I'm submitting a...

Bug report
 

## Current behavior

When creating a new project using UnoSolutionTemplate (UnoPlatform-1.45.0-dev.1327.vsix), if the name has spaces in it the solution does not build.

```
4>------ Build started: Project: Test space name.Wasm, Configuration: Debug Any CPU ------
4>obj\Debug\netstandard2.0\g\XamlCodeGenerator\GlobalStaticResources.g.cs(16,12,16,17): error CS1002: ; expected
4>obj\Debug\netstandard2.0\g\XamlCodeGenerator\GlobalStaticResources.g.cs(16,27,16,28): error CS1003: Syntax error, '(' expected
4>obj\Debug\netstandard2.0\g\XamlCodeGenerator\GlobalStaticResources.g.cs(16,27,16,28): error CS1026: ) expected
4>obj\Debug\netstandard2.0\g\XamlCodeGenerator\GlobalStaticResources.g.cs(18,27,18,31): error CS0116: A namespace cannot directly contain members such as fields or methods
4>obj\Debug\netstandard2.0\g\XamlCodeGenerator\GlobalStaticResources.g.cs(18,16,18,21): error CS1514: { expected
4>obj\Debug\netstandard2.0\g\XamlCodeGenerator\GlobalStaticResources.g.cs(19,1,19,2): error CS1022: Type or namespace definition, or end-of-file expected
4>obj\Debug\netstandard2.0\g\BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs(11,27,11,31): error CS0116: A namespace cannot directly contain members such as fields or methods
4>obj\Debug\netstandard2.0\g\BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs(11,16,11,21): error CS1514: { expected
4>obj\Debug\netstandard2.0\g\BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs(12,1,12,2): error CS1022: Type or namespace definition, or end-of-file expected
4>Done building project "Test space name.Wasm.csproj" -- FAILED.
```
` error CS0246: The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)`
## Expected behavior

Solution should build regardless of spaces in project name

## Minimal reproduction of the problem with instructions

1. Create project using UnoSolutionTemplate (UnoPlatform-1.45.0-dev.1327.vsix)
2. Give project a name with a space in it
3. Attempt to build solution
4. Notice build errors

## Environment

```
Nuget Package: 
1.45.0-dev.1331
Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [x] Build tasks

Visual Studio
- [x ] 2017 (version: ) 15.9.11
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by artemious7** [comment]
This is due to RootNamespace is a copy of project name, no validation checks. If I create a project of another type in Visual Studio with spaces in its name, they are replaced with underscores "_". The same is expected here. It should also check for other invalid characters in the name and replace them.

**Comment by artemious7** [comment]
How do I build Uno Solution Templates extension? I'd like to fix this bug and debug it locally on my Windows 10

**Comment by jeromelaban** [comment]
You can open the solution [with this filter](https://github.com/unoplatform/uno/blob/master/src/Uno.UI-Wasm-hotreload-vsix-only.slnf), this will give you access to the VSIX. Then don't forget to change your debugging target: 

https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/UnoSolutionTemplate.VISX/Readme.md#debugging

**Comment by jeromelaban** [comment]
## Note to contributors

In order to prevent the solution from being create this way, at least in the VSIX templates, we can alter the behavior through the wizard extension:

https://github.com/unoplatform/uno/blob/9dd70455216babac91d0a6e8e1f50d8a7d2dfb2d/src/SolutionTemplate/UnoSolutionTemplate.Wizard/UnoSolutionWizard.cs#L13

Showing an error message when the created solution contains spaces can  be a valid workaround.
