### ISSUE TITLE
[WindowsAppSdk][WASM] SvgImageSource.SetSourceAsync not working (again). Regression

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#8080]
### Current behavior

@jeromelaban  SvgImageSource.SetSourceAsync was working as per [here](https://github.com/unoplatform/uno/issues/4417). Unfortunately there is a regression using [latest UNO templates](https://platform.uno/docs/articles/get-started-winui3.html). 

I amended @peternary's solution to demonstrate the problem: please compare WinUI and WASM.

[SetSourceAsync.zip](https://github.com/unoplatform/uno/files/8056349/SetSourceAsync.zip)

### Works on UWP/WinUI

Yes

**Comment by jeromelaban** [comment]
Thanks for the report.

This is not a regression, but rather the fact that `InMemoryRandomAccessStream` is not supported in Uno.

Use this instead:
```csharp
private async void LoadIcon(string color)
{
	byte[] byteArray = Encoding.UTF8.GetBytes($@"<svg xmlns=""http://www.w3.org/2000/svg"" enable-background=""new 0 0 24 24"" height=""24"" fill=""{color}"" viewBox=""0 0 24 24"" width=""24""><g><rect fill=""none"" height=""24"" width=""24""/></g><g><g><g><path d=""M6,14l3,3v5h6v-5l3-3V9H6V14z M11,2h2v3h-2V2z M3.5,5.88l1.41-1.41l2.12,2.12L5.62,8L3.5,5.88z M16.96,6.59l2.12-2.12 l1.41,1.41L18.38,8L16.96,6.59z""/></g></g></g></svg>");
	SvgImageSource s = new SvgImageSource();
	await s.SetSourceAsync(new MemoryStream(byteArray).AsRandomAccessStream());
	sampleImage.Source = s;
}
```

**Comment by DierkDroth** [comment]
Excellent! Thanks @jeromelaban. That got me going...
