### ISSUE TITLE
[Android/iOS] Nested `TextBox` in `Pivot` does not respect `MaxWidth`

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#8086]
### Current behavior

The following markup leads to a TextBox, that does not respect it's MaxWidth but instead gets wider and wider with every character typed. It leads to it's parent getting stretched out of the viewport:

```xaml
<Pivot Background="Green" MaxWidth="400">
        <PivotItem Header="PivotHeader">
            <Grid MaxWidth="400" Background="Red">
                <TextBox Text="Hello, world!" Margin="20" FontSize="30" MaxWidth="400"/>
            </Grid>
        </PivotItem>
</Pivot>
```

### Expected behavior

The TextBox should in all cases respect it's MaxWidth-setting.

### How to reproduce it (as minimally and precisely as possible)

See the sample-repo here: [UnoTextBoxMaxWidth-master.zip](https://github.com/unoplatform/uno/files/8061235/UnoTextBoxMaxWidth-master.zip)

### Workaround

None found, yet

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.0.11

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report! When opening issues, make sure to attach a zip file of the project instead of another repository link.


@carldebilly do you know of a workaround for this ?

**Comment by carldebilly** [comment]
@TopperDEL If you put the `MaxWidth` on the parent `<Grid>` element, are you getting the same error?

**Comment by TopperDEL** [comment]
I get the same problem, yes. You can see the original problem in this coding:
https://github.com/TopperDEL/uplink.NET.UnoHelpers/blob/8e77614ca324651a6bd3db41a81cd70b65ad05d3/uplink.NET.UnoHelpers/Views/LoginPage.xaml#L11

In the sample-repo in this issue here I reduced the visual tree to the simplest way showing that issue.

**Comment by TopperDEL** [comment]
It seems that iOs shows the same error, though I could not completely verify it yet.

**Comment by Youssef1313** [comment]
Windows:

![image](https://github.com/unoplatform/uno/assets/31348972/de83c23a-6725-4814-9098-a3bc271e2c94)

**Comment by Youssef1313** [comment]
@TopperDEL I'm not able to reproduce this. Can you confirm?

**Comment by TopperDEL** [comment]
Oh Man, how time flies by.

Sorry for my late reply - I checked again and it seems the issue is not relevant anymore. I'm closing it. Thank you @Youssef1313!
