### ISSUE TITLE
[Skia] Pointer events "fall through"

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#8087]
### Current behavior

Noticed in Skia Samples app. When the categories list is scrolled (not at the top), the click on the "Back" button falls through and causes the `ListViewItem` which is "underneath the header" to be selected.

![skiapointerfallthrough](https://user-images.githubusercontent.com/1075116/153844115-4539819d-e38f-4d06-88c5-40306d2813df.gif)

### Expected behavior

Should not happen.

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen)

### IDE

Visual Studio 2022

**Comment by dr1rrb** [comment]
This has been fixed few month ago
