### ISSUE TITLE
uno-check - .NET SDK workloads install fails

### ISSUE THREAD

**Issue by frogcrush** [unoplatform/uno#8091]
### Current behavior

.NET SDK install fails when running uno-check. uno-check is freshly installed and the latest version. Error is as follows:

```
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: Failed to validate package signing.

Verifying Microsoft.NET.Workload.Mono.ToolChain.Manifest-6.0.200.6.0.2-mauipre.1.22102.15

error: NU3004: The package is not signed.

Package signature validation failed.
```

Full trace:
![image](https://user-images.githubusercontent.com/6116333/153930972-06c5b507-44ef-4b7d-80b7-b1ab17db493e.png)

### Expected behavior

uno-check should be able to update .NET workloads so the tools can be used.

### How to reproduce it (as minimally and precisely as possible)

Run "uno-check" with Visual Studio 2022 and Visual Studio 2022 Preview installed on the machine, with appropriate things selected in Visual Studio Installer for both. Dotnet version is 6.0.200-preview.22055.15.

### Workaround

No workaround found at this time; UWP builds work fine. 

### Affected platforms

iOS, Android, macOS, Build tasks

### IDE

Visual Studio 2022

### IDE version

17.1.0 Preview 5

**Comment by jeromelaban** [comment]
Thanks for the report. Please make sure to follow this: https://github.com/unoplatform/uno/discussions/7833. This setup may still be bumpy until .NET 6 and mobile workloads are stabilized.

**Comment by frogcrush** [comment]
Okay. To try, I ran ``dotnet tool update -g uno.check --version 1.1.0-dev.22`` which updated uno-check, then ran ``uno-check`` again and the same issue occurred.

**Comment by jeromelaban** [comment]
My comment was posted before 17.1 was released, so yes it was in preview at that time. Please see the updated post here about 17.2 Preview 1: https://github.com/unoplatform/uno/discussions/7833
