### ISSUE TITLE
[macOS] `DataGrid` on a `TabView` not appearing in macOS

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#8110]
### Discussed in https://github.com/unoplatform/uno/discussions/8105

<div type='discussions-op-text'>

<sup>Originally posted by **roberuc** February 15, 2022</sup>
Smallest description of problem: I am using "Visual Studio 2019 for Mac".
(I did install "Visual Studio 2022 Preview for Mac" but later deleted it. So could be some residue problem.)
I created a template solution using the CLI (in the "Documents" folder):  dotnet new unoapp -o AU_new
Deleted the "global.json" file.
Removed a lot of Projects because I am just interested in the Shared, Mac, and iOS. (Kept just those.)

Did a Nuget restore on the solution. Set the StartUp Project to MacOS.
Had to add a couple of Nuget packages to both the macOS and iOS projects:

       Microsoft.UI.Xaml
       Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid

edited the MainPage.xml to this: 

 ```
<Page
    x:Class="AU_new.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:AU_new"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"mc:Ignorable="d"
    xmlns:uc="using:Microsoft.UI.Xaml.Controls"
    xmlns:ud="using:Microsoft.Toolkit.Uwp.UI.Controls"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <StackPanel>
        <uc:TabView>
            <uc:TabViewItem Header="A">
                <StackPanel Background="Yellow">
                <TextBlock>TabView A</TextBlock>
                </StackPanel>
            </uc:TabViewItem>
            <uc:TabViewItem Header="B">
                <StackPanel Background="Green">
                <TextBlock>TabView Ba</TextBlock>
                <ud:DataGrid Name="gridHere" SelectionMode="Extended" AutoGenerateColumns="True" Height="200" Width="600" Foreground="Black" Background="White">
                    <ud:DataGrid.Columns>
                        <ud:DataGridTextColumn Width="150" Header="col A" Foreground="Black" />
                        <ud:DataGridTextColumn Width="150" Header="col B"  />
                        <ud:DataGridTextColumn Width="150" Header="col C"  />
                        <ud:DataGridTextColumn Width="150" Header="col D"  />
                    </ud:DataGrid.Columns>
                </ud:DataGrid>
                <TextBlock>TabView Bz</TextBlock>
                </StackPanel>
            </uc:TabViewItem>
        </uc:TabView>
    </StackPanel>
</Page>
```

Compiles for macOS and iOS. Gives some warnings but it runs.
It works on iOS. In 2nd tab, the DataGrid appears with 4 columns. (Yeah!)
But on macOS, the Tab items appear but the DataGrid ends up as a big empty block of green background color.
(Side note: I can take this to a PC running Visual Studio 2019 and put this code into an Uno App, and it runs there for UWP.
I do not bring the entire solution there. Seems there are some subtle differences between the various Op Sys Projects.
But the shared common folder can be copied.  That is so freaking cool!)
Really curious what I am doing wrong on macOS?</div>

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
