### ISSUE TITLE
[WindowsAppSdk][WASM] Default template becomes unusuable with latest UNO DEV pieces

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#8131]
### Current behavior

After updating to latest UNO DEV pieces [the default template](https://platform.uno/docs/articles/get-started-winui3.html) becomes unusable (sample solution attached).
[Debugger.zip](https://github.com/unoplatform/uno/files/8094687/Debugger.zip)

Solution no longer builds due to these errors
![image](https://user-images.githubusercontent.com/26179242/154630329-231cf981-4368-4a35-b187-f96dffeb421b.png)

After upgrading the projects to .NET 6 you'll get these errors upon building:

![image](https://user-images.githubusercontent.com/26179242/154630189-91bfe86b-59ac-42ce-a37b-3a4a39751119.png)

**Comment by jeromelaban** [comment]
Building with .NET 7 is not yet supported. Either uninstall it or use a global.json configuration to use a stable .NET SDK.

**Comment by jeromelaban** [comment]
You have .NET 7 installed on your machine, see the first screenshot. Uninstall .NET 7 and see if the issue happens again.

**Comment by DierkDroth** [comment]
@jeromelaban I'm sorry, I have no idea where these pieces would be coming from, nor is .NET 7 on the list of installed programs on my machine (below), nor would I know how to uninstall that .NET7 preview

Any pointer would be appreciated. Thanks

![image](https://user-images.githubusercontent.com/26179242/154811498-d5cedceb-a335-4f73-97d5-d9c05ddacff2.png)

**Comment by DierkDroth** [comment]
@jeromelaban the issue is gone after downgrading the Microsoft NuGet packages from 7.X preview to stable 6.0.

Thanks for your support.
