### ISSUE TITLE
[Wasm] IDBFS initialization is overwriting current data

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#8157]
### Discussed in https://github.com/unoplatform/uno/discussions/8143

<div type='discussions-op-text'>

<sup>Originally posted by **giraudremy** February 20, 2022</sup>
Hi,

I follow this documentation to create file in Wasm application :
https://platform.uno/docs/articles/features/windows-storage.html

File is well created and I can read it until I close browser. When I restart browser, file is not existing...

Does roaming folder is persisted ?

I have made a sample :
[UnoApp1.zip](https://github.com/unoplatform/uno/files/8103954/UnoApp1.zip)

Write button will check if file exist and create it if not exist.
Read button will read the file in roaming folder.

if you restart browser and click to Read button, I have a FileNotFoundException
System.IO.FileNotFoundException: Could not find file '/roaming/Configuration/accounts.xml'.
File name: '/roaming/Configuration/accounts.xml' 

Why ?</div>

**Comment by giraudremy** [comment]
Hi, Does dev.100 binaries contains the fix ?

**Comment by jeromelaban** [comment]
That's correct, 4.2.0-dev.100 and later contains the fix.

**Comment by giraudremy** [comment]
Because I tried with this version and I have the same issue :
![image](https://user-images.githubusercontent.com/55281461/155280573-adf58f52-4956-43a5-b689-49ee7ce36777.png)

**Comment by jeromelaban** [comment]
I tried with your sample, and the issue is not present anymore. Can you validate if the IndexedDB is cleared a few seconds after launch on the second run (once a file is created) ? If that's the case, you may not run the latest, even if the nuget packages installed say otherwise.

**Comment by giraudremy** [comment]
Yes the IndexedDB is cleared a few seconds after launch on the second run. I also tried 4.2.0-dev.117 with same result. How I can force latest version ?

**Comment by jeromelaban** [comment]
If it still happens, it's likely that you're not running the latest builds, somehow. You can validate in the uno.ui.clr file in the output dist folder that the version (using file explorer properties) is the one you expect.

**Comment by giraudremy** [comment]
I have found 4.2.0-dev.117+Branch.master.Sha.dfb8f4eec509416042613d94d2b25b7aa3c702a6.dfb8f4eec509416042613d94d2b25b7aa3c702a6 in my uno.ui.clr file, that seem correct...

**Comment by jeromelaban** [comment]
Thanks for the update, then there's something else.

**Comment by giraudremy** [comment]
Hi, any update of this issue? I am waiting for correction to be able to implement a new functionality in my app... thank

**Comment by jeromelaban** [comment]
The initialization is incorrect for folders other than `ApplicationData.Current.LocalFolder`, you can use this folder instead as a workaround. The linked fix will be published soon.

**Comment by giraudremy** [comment]
Ok thank, it's work with ApplicationData.Current.LocalFolder
