### ISSUE TITLE
Three build-breaking issues issues (and solutions) with the "unoapp-winui-net6" project template

### ISSUE THREAD

**Issue by MGRussell** [unoplatform/uno#8162]
### Current behavior

The default `unoapp-winui-net6` build template resulted in a project that did not run on Windows until 3 issues were resolved:

### Problem 1

A build error *"This version of WindowsAppSDK requires WinRT.Runtime.dll version 1.3 or greater.
Please update to .NET SDK 5.0.205, 5.0.302, or 5.0.400 (or later)."* This is related to this discussion here: https://github.com/unoplatform/uno/discussions/7617 .

### Solution 1

The default template includes:
````
 <ItemGroup> 
 	<FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.18362.16" /> 
 	<FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.18362.16" /> 
 </ItemGroup> 
````

The solution from that discussion of updating those values 0.22 instead of 0.16 did work, but even more simply - so did removing the entire itemgroup. It seems that the issue that was working around has been resolved, and so this fix is no longer necessary.

### Problem 2
A lengthy compile-time error: *MSB3270	There was a mismatch between the processor architecture of the project being built ... and the processor architecture of the reference .... This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.*

### Solution 2
Setting the CPU type to `x86` for the build resolved this. Is it possible to deploy a 64 bit build on Windows with Uno?

### Problem 3
I was now able to build and run the program. It then immediately crashed with "`System.EntryPointNotFoundException: 'Unable to find an entry point named 'XamlCheckProcessRequirements' in DLL 'Microsoft.ui.xaml.dll'.`'". 

### Solution 3
The `.Windows.Package` and `.Windows.Desktop` projects reference different versions of the `Microsoft.WindowsAppSDK` in the template. The package project was referencing 1.0.0 (experimental) and the desktop project was referencing 1.0.0. Changing the packaging project to reference the stable version solved this.

### Expected behavior

The default template should produce a project that can be executed without errors.

### How to reproduce it (as minimally and precisely as possible)

All issues here are present in a default `dotnet new unoapp-winui-net6` template.

### Works on UWP/WinUI

No

### Environment

Windows 10 build 19044.1526

### Affected platforms

Windows, Build tasks, Solution Templates

### IDE

Visual Studio 2022

### IDE version

17.2.0 Preview 1

**Comment by jeromelaban** [comment]
Thanks for the reports. These issues have been fixed in the upcoming release, see [this file](https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-net6/UnoWinUIQuickStart.Windows/UnoWinUIQuickStart.Windows.csproj).

Note that this project template is using WinAppSDK, not Uno Platform, even if the project is created using the Uno Platform templates.
