### ISSUE TITLE
[Wasm] Unknown application freeze

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#8165]
### Current behavior

The Gallery application may freeze after a while with unknown set of conditions.

### How to reproduce it (as minimally and precisely as possible)

Probable repro:
- https://gallery.platform.uno/
- Go to the checkbox section
- Change themes (Material, Cupertino, etc..)
- Click CheckBoxes
- Change multiple times (unknown count)

The application may eventually freeze as it enters some some sort of layout loop.

See the traces captures:
[Simplified StackTrace V3.txt](https://github.com/unoplatform/uno/files/8117053/Simplified.StackTrace.V3.txt)
[StackTrace Gallery Hang V2.txt](https://github.com/unoplatform/uno/files/8117054/StackTrace.Gallery.Hang.V2.txt)
[StackTrace Gallery Hang.txt](https://github.com/unoplatform/uno/files/8117055/StackTrace.Gallery.Hang.txt)

### NuGet package version(s)

4.2-dev.x

### Affected platforms

WebAssembly

**Comment by giraudremy** [comment]
Hi,

I have similar issue in my app. Sometime, my app freeze, CPU is increase and run into an infinite loop. I think it a layout loop when I see stack trace but I don't know how to solve it or how to reproduce...

I will follow this issue

**Comment by giraudremy** [comment]
Hi,

Hello,

this patch did not fix my app freezing problem.
I don't know how to move forward on this point, when I take a break I come across this kind of stack trace :
<img width="873" alt="image" src="https://user-images.githubusercontent.com/55281461/167301383-a8abada3-e27f-4afe-a7fc-3f8cab66ec51.png">

What can I look for that might help me find the source of the problem?

**Comment by jeromelaban** [comment]
@giraudremy could you open another issue and fill all the additional details?
