### ISSUE TITLE
[Skia.Gtk][Fedora OS] Incorrect page content size

### ISSUE THREAD

**Issue by Dieveral** [unoplatform/uno#8186]
### Current behavior

On Fedora OS page content is drawn with incorrect size (bigger then bounds of the window). Some of controls are not drawn (they are above window bounds).
![Screenshot from 2022-02-24 06-48-00](https://user-images.githubusercontent.com/50696412/155528087-e5097394-b569-498f-bfca-2f215cb9c453.png)
I was changing values of Bottom offset and Right offset fields (the size of empty areas on right side and bottom side of the page).
In my case content width is bigger by 52 pixels, and height is bigger by 89 pixels then bounds of the main window.
![Screenshot from 2022-02-24 06-47-40](https://user-images.githubusercontent.com/50696412/155528734-a566ed82-2380-4246-b523-f649b0c10fa3.png)
If I change app to fullscreen mode: the width now is normal, but content height is 37 pixel bigger then window height. (89 - 52 = 37)
![Screenshot from 2022-02-24 06-48-39](https://user-images.githubusercontent.com/50696412/155529283-f74507aa-0496-4e15-8723-9a6938908f57.png)
![Screenshot from 2022-02-24 06-48-57](https://user-images.githubusercontent.com/50696412/155529301-d3b1a3f8-abb5-48ec-966e-c1645da4e304.png)

### Expected behavior

Page content should be drawn with correct size (the same as window).

### How to reproduce it (as minimally and precisely as possible)

1. Create blank uno project or take my test project: [https://github.com/Dieveral/FedoraBug](https://github.com/Dieveral/FedoraBug)
2. Build Skia.Gtk project.
3. Publish it to directory.
    Right-click on project in Solution Explorer -> Publish. I used these Profile settings:
![ProfileSettings](https://user-images.githubusercontent.com/50696412/155524895-fff2b82f-22d7-45c3-ad52-b1c0466f903d.jpg)
5. Copy publish folder to Fedora Workstation (real or virtual machine)
6. Allow Gtk file to be executed as program.
    Right-click on Gtk file -> Properties -> Permissions -> Allow executing file as program.
![Screenshot from 2022-02-24 07-38-33](https://user-images.githubusercontent.com/50696412/155527660-3ea7d739-eeff-477f-8082-b69687ea6acd.png)
7. Run Gtk file.

You can also run my published application on Fedora OS:
[FedoraBug_publish.zip](https://github.com/unoplatform/uno/files/8132650/FedoraBug_publish.zip)

### Workaround

Partially. Add empty right area with 52 pixel width and bottom area with 89 pixel height on each page. But I did not find solution to handle the change of window state to fullscreen. In fullscreen mode right area should have 0 pixel width and bottom area should have 37 pixel height.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI.Skia.GTK - 4.0.11

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2019

### IDE version

16.11.5

### Anything else we need to know?

Everything works fine in Ubuntu.

**Comment by jeromelaban** [comment]
Thanks for the report. Would you be able to validate using the dev version of Uno, 4.2-dev.100?

**Comment by Dieveral** [comment]
With Uno.UI.Skia.GTK - 4.2-dev.100. Everything works fine. :) Thanks!

**Comment by jeromelaban** [comment]
Great, thanks for the update!
