### ISSUE TITLE
VisualStudio Mac unusable with Uno Solutions : too many threads

### ISSUE THREAD

**Issue by baskren** [unoplatform/uno#8196]
### Current behavior

Editing source code files for a Uno Solution in VisualStudio Mac is unbearable.  At almost every line of code, VsMac creates dozens of more threads that appear to be orphaned.  After 10-15 minutes, VsMac has thousands of threads - and has to be restarted.

Note that it does not do this for Xamarin.Forms projects.

I'm not sure when this started happening, so I can't be much help in pinpointing when this started.  I want to say sometime in February 2022?

### Expected behavior

VisualStudio Mac does not create excessive orphaned threads during editing of source code files.

### How to reproduce it (as minimally and precisely as possible)

1. Open [sample solution](https://github.com/baskren/Uno.VsMac.OrphanedThreads) in the repo using VsMac 2019 - or just create a new Uno Solution (without the WPF, UWP, GtK and Tizen projects).
2. Open the Main.xaml.cs file
3. Open the MacOS Activity Monitor and note the number of threads

<img width="996" alt="image" src="https://user-images.githubusercontent.com/2528888/155846056-934477f4-3454-429e-be81-cff64bad2929.png">

4. Manually type (do not paste) the following code (or just any reasonable code - it won't take long) into body of `MainPage` class in Main.xaml.cs :

```
       void MethodA()
        {

        }

#if __IOS__
        void MethodB()
        {
        }
#elif __ANDROID__
        void MethodB()
        {

        }
#else
        void MethodB()
        {
        }
#endif
        void MethodC()
        {

        }

        void MethodD()
        {
            System.Diagnostics.Debug.WriteLine($"Pizza {21}");
        }

        void MethodE()
        {

        }

        void MethodF()
        {
            if (System.Console.CapsLock)
                System.Console.Write("caps");
        }

#if __IOS__
        void MethodG()
        {
        }
#endif
```

5. Note the significant increase in threads in MacOS Activity Monitor

<img width="996" alt="image" src="https://user-images.githubusercontent.com/2528888/155846201-62e7e8ec-8248-4ad4-ad32-9da4f293a98d.png">

## Things tried that did not help:

- Completely uninstall and reinstall VsMac
- Using VsMac 2022 Preview.  Issue was seen in VsMac 2022 Preview as well.  However, most recent update to VsMac 2022 preview won't open Uno Class Library projects that use `<Project Sdk="MSBuild.Sdk.Extras/3.0.22">` in project file.  I have a lot of Uno Class Library projects and am not ready to convert them to .NET6.

### Workaround

If you have a spare Mac, you could always edit/build the projects in VsWindows.  This may force me to do that but, frankly, I used to really like VsMac much better than VsWindows (30 years of Unix/Mac development makes it really hard to enjoy development in Windows).  Folks keep talking about plugins for Vi.  I wonder if that might be an option.  Used to love Vi.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

iOS project: 

```
    <PackageReference Include="Uno.UI" Version="4.0.13" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="4.0.13" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.0.13" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Uno.Extensions.Logging.OSLog " Version="1.0.1" />
```

Android project:
```
    <PackageReference Include="Uno.UI" Version="4.0.13" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="4.0.13" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.0.13" />
    <PackageReference Include="Uno.UniversalImageLoader" Version="1.9.33" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
```

### Affected platforms

iOS, macOS

### IDE

Visual Studio Enterprise 2019 for Mac

### IDE version

Version 8.10.19 (build 2)

### Relevant plugins

=== Enabled user installed extensions ===

DeepClean 1.2.5
Brute Clean 1.1
WakaTime 4.0.2

### Anything else we need to know?

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.10.19 (build 2)
Installation UUID: 4cd91936-1b00-4e8b-acb2-591869e673f4
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/6.0.102/Sdks
SDK Versions:
	6.0.102
	6.0.101
	5.0.405
	5.0.404
	3.1.416
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.2
	6.0.1
	5.0.14
	5.0.13
	3.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.416

=== .NET 5.0 SDK ===

SDK: 5.0.405

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.2.1 (19586)
Build 13C100

=== Xamarin.Mac ===

Version: 8.6.0.3 (Visual Studio Enterprise)
Hash: caa899d24
Branch: d17-1
Build date: 2022-01-16 21:16:56-0500

=== Xamarin.iOS ===

Version: 15.6.0.3 (Visual Studio Enterprise)
Hash: caa899d24
Branch: d17-1
Build date: 2022-01-16 21:16:56-0500

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 02:44:16 UTC

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Enterprise)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/ben/Library/Android/sdk
	Supported Android versions:
		5.0 (API level 21)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: Not Found

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Build Information ===

Release ID: 810190002
Git revision: 632b6ca654e2733a685bfc9c6a0686e0a317092b
Build date: 2022-02-09 13:38:14-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.2.1
Darwin 21.3.0 Darwin Kernel Version 21.3.0
    Wed Jan  5 21:37:58 PST 2022
    root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

DeepClean 1.2.5
Brute Clean 1.1
WakaTime 4.0.2

**Comment by baskren** [comment]
FWIW, this issue is no longer present.

@MartinZikmund : Bummer about VSMac.  It's still my preferred approach to M2 development for UNO.

**Comment by jeromelaban** [comment]
@baskren we're still making sure that the current support we have is working properly, but as we do not have an extension, the experience is not as good as it can be with VS Code.
