### ISSUE TITLE
[Gallery][AnyPlat] ChipGroup - Wrong chip Item gets remove from the list after removal of chip item#1

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8203]
### Current behavior

![chip group](https://user-images.githubusercontent.com/74563602/156049466-2a28d5d7-79f1-4e78-9ea8-a1fa96110d8b.png)

https://user-images.githubusercontent.com/74563602/156049566-d215fd6b-537c-4367-960a-01a8eba839ab.mp4

### Expected behavior

The clicked Chip Item no. should remove.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "ChipGroup" from the "Toolkit" list.
4. Go to Input Section.
5. First Click on “X” symbol of “Item 1 “.
6. Observe that “Item 1” gets remove from the list.
7. Now click on “X” symbol of “Item 2”.
8. Observe that “Item 3” gets remove from the list, instead of “Item 2” removal.
9. Now again click on “X” symbol of “Item 2”
10. Observe that this time “Item 4” gets remove from the list.
11. One more issue
12. Click on “X” symbol of any Item no. which is after “Item 2” for example click on “Item 6”.
13. Observe that “Item 6” is not removing. (Nothing is happening when click “X” symbol).

### Works on UWP/WinUI

working fine on uwp.

### Affected platforms

WebAssembly

**Comment by Xiaoy312** [comment]
`ItemsControl::ItemFromContainer` has some issue:
![image](https://user-images.githubusercontent.com/2359550/156196396-eef9e0d3-1f92-4d65-8b87-06f7c7faddbd.png)

**Comment by Xiaoy312** [comment]
likely to be related: https://github.com/unoplatform/uno/issues/8204

**Comment by carldebilly** [comment]
Found the cause of the problem: there is an internal attached property called `IndexForItemContainer` which needs to be refreshed after the removal operation.

**Comment by sakshi173** [comment]
Verified with latest canary, Issue is fixed, Closing it
