### ISSUE TITLE
x:Bind `OneTime` bindings value fail to be set properly when assigned in `OnNavigatedTo` event handler

### ISSUE THREAD

**Issue by hawkerm** [unoplatform/uno#8205]
### Current behavior

OneTime bindings which work fine in UWP are not working in WASM/WPF.

This appears to be an issue when setting them via the `OnNavigatedTo` event on page navigation within a frame. Bindings evaluate fine if navigation happens as part of initial load, but not on subsequent navigations.

### Expected behavior

Bindings should evaluate the same as initial load and as UWP on subsequent loads.

### How to reproduce it (as minimally and precisely as possible)

See this project created from a new uno app template: 
[UnoTestApp.NavigationBinding.zip](https://github.com/unoplatform/uno/files/8159815/UnoTestApp.NavigationBinding.zip)

It contains a MainPage with a TextBox, a button, and a Frame. And a SecondPage with some properties and textblock bindings.

1. Run the app on UWP
2. See that the properties listed match the expected values: 5, 10, 10, 15, 15, and the text from the textbox:
![image](https://user-images.githubusercontent.com/8959496/156129268-9e154590-3a71-4b9b-8328-40aaba61ba7f.png)
3. Change the text in the textbox and click the 'Refresh' button.
4. The values should be the same, though the text should now match what you typed:
![image](https://user-images.githubusercontent.com/8959496/156129315-d91f86c1-830d-4228-910a-b974e4352933.png)
5. Re-do steps 2-4 with either WASM or WPF.

(Textbox is a bit weird with initial focus on WPF host [appears blank, but if click out and in it's there], but you can see here initial load is fine:)
![image](https://user-images.githubusercontent.com/8959496/156129704-b007b5aa-5ee7-4311-9e5e-4cedf0ecdd73.png)

You can see though we get 5, 0, 0, 0, 15, blank though as result after refresh:

![image](https://user-images.githubusercontent.com/8959496/156129835-fe5f56b0-1545-4292-873a-a6ab02a0d1fe.png)

Same exact behavior on WASM (though textbox works as expected).

### Workaround

Making a DP and changing to OneWay binding may work, but didn't seem to help when dealing with an object that then needed to index into a sub-property...? i.e. if bindings were `{x:Bind SomeObject.SomeProperty}` instead.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.2.0-dev.156

### Affected platforms

WebAssembly, Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.1.0

**Comment by carldebilly** [comment]
I confirm I see the same problem here with your repro on Skia/GTK.

**Comment by hawkerm** [comment]
Thanks @carldebilly, 

I've updated the sample here to include a complex object that shows a few other scenarios broken compared to UWP:
[UnoTestApp.NavigationBinding.zip](https://github.com/unoplatform/uno/files/8166129/UnoTestApp.NavigationBinding.zip)

Should hopefully be useful for scenarios for testing a fix later.

**Comment by jeromelaban** [comment]
Thanks for the update. I've added a workaround in https://github.com/unoplatform/uno/issues/2872. I'll close this issue as it's a duplicate.
