### ISSUE TITLE
`x:Bind` casting not working with `muxc:NavigationViewItem`

### ISSUE THREAD

**Issue by hawkerm** [unoplatform/uno#8208]
### Current behavior

Not sure if just missed scenarios with #4855?

_Both of these scenarios work in UWP_:

```xml
<controls:SwitchPresenter Value="{x:Bind ((muxc:NavigationViewItem)NavView.SelectedItem).Name, Mode=OneWay}">
```

```xml
<controls:SwitchPresenter Value="{x:Bind NavView.SelectedItem.(muxc:NavigationViewItem.Name), Mode=OneWay}">
```

As called out as valid casting methods [in the docs](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension#casting)

However, they both cause invalid generated bindings when compiling on WASM/WPF:

```cs
c14.SetBinding(global::Microsoft.Toolkit.Uwp.UI.Controls.SwitchPresenter.ValueProperty, new Windows.UI.Xaml.Data.Binding{ Mode = global::Windows.UI.Xaml.Data.BindingMode.OneWay/* Windows.UI.Xaml.Data.BindingMode/Windows.UI.Xaml.Data.BindingMode, OneWay, Bind/Mode */,  }.BindingApply(___b =>  /*defaultBindModeOneTime ((global::Microsoft.UI.Xaml.Controls.NavigationViewItem)NavView.SelectedItem).Name*/ global::Uno.UI.Xaml.BindingHelper.SetBindingXBindProvider(___b, this, ___ctx => ___ctx is global::MyApp.MainPage ___tctx ? (object)(___tctx.((global::Microsoft.UI.Xaml.Controls.NavigationViewItem)NavView.SelectedItem).Name) : null, null , new [] {"((global::Microsoft.UI.Xaml.Controls.NavigationViewItem)NavView.SelectedItem).Name"})));
```

`error CS1001: Identifier expected`

And for the second one:

```cs
c14.SetBinding(global::Microsoft.Toolkit.Uwp.UI.Controls.SwitchPresenter.ValueProperty, new Windows.UI.Xaml.Data.Binding{ Mode = global::Windows.UI.Xaml.Data.BindingMode.OneWay/* Windows.UI.Xaml.Data.BindingMode/Windows.UI.Xaml.Data.BindingMode, OneWay, Bind/Mode */,  }.BindingApply(___b =>  /*defaultBindModeOneTime NavView.SelectedItem.(global::Microsoft.UI.Xaml.Controls.NavigationViewItem.Name)*/ global::Uno.UI.Xaml.BindingHelper.SetBindingXBindProvider(___b, this, ___ctx => ___ctx is global::MyApp.MainPage ___tctx ? (object)(___tctx.NavView.SelectedItem.(___tctx.global::Microsoft.UI.Xaml.Controls.NavigationViewItem.Name)) : null, null , new [] {"NavView.SelectedItem"})));
```

with `error CS1001: Identifier expected` and `error CS7000: Unexpected use of an aliased name`

### Expected behavior

Able to use a cast to bind to a NavigationViewItem property with x:Bind.

### How to reproduce it (as minimally and precisely as possible)

1. Create an uno project.
2. Add the Toolkit Primitives nugets
3. Create a NavigationView/SwitchPresenter setup:
```xml
     <muxc:NavigationView x:Name="NavView"
                         PaneDisplayMode="Top" IsBackButtonVisible="Collapsed">
        <muxc:NavigationView.MenuItems>
            <muxc:NavigationViewItem x:Name="ItemHelp">
                <muxc:NavigationViewItem.Icon>
                    <FontIcon FontFamily="{ThemeResource SymbolThemeFontFamily}" Glyph="&#xE9CE;" />
                </muxc:NavigationViewItem.Icon>
            </muxc:NavigationViewItem>
            <muxc:NavigationViewItem x:Name="ItemOther" Content="Other" Icon="Calendar"
                                     IsSelected="True"/>
            <muxc:NavigationViewItem x:Name="ItemOther2" Content="Other 2">
                <muxc:NavigationViewItem.Icon>
                    <FontIcon FontFamily="{ThemeResource SymbolThemeFontFamily}" Glyph="&#xF272;" />
                </muxc:NavigationViewItem.Icon>
            </muxc:NavigationViewItem>
        </muxc:NavigationView.MenuItems>
        <controls:SwitchPresenter Value="{x:Bind NavView.SelectedItem.(muxc:NavigationViewItem.Name), Mode=OneWay}">
            <controls:Case Value="ItemHelp">
                <local:HelpPage/>
            </controls:Case>
            <controls:Case Value="ItemOther">
                <local:OtherPage/>
            </controls:Case>
            <controls:Case Value="ItemOther2">
                <local:OtherPage2/>
            </controls:Case>
        </controls:SwitchPresenter>
    </muxc:NavigationView>
```
Use either of the binding setups provided at the top for the SwitchPresenter.
4. Run and see UWP app runs and works.
5. Try compiling for WASM/WPF, get compile error.

### Workaround

Use a regular binding expression:
```xml
<controls:SwitchPresenter Value="{Binding SelectedItem.Name, ElementName=NavView}">
```

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.2.0-dev.156

### Affected platforms

WebAssembly, Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.1.0

**Comment by sigmarsson** [comment]
```Identifier expected``` maybe an aftermath of #4766 ? I encountered a [similar issue](https://stackoverflow.com/questions/72154797)

**Comment by hawkerm** [comment]
@jeromelaban I just tried this on Uno.UI.WebAssembly stable and latest 4.7.0-dev.770 and saw this scenario failing with message:

```
VM100:1 fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
      The [(] property getter does not exist on type
```

(in WASM console in browser, Edge (seems like error message isn't parsing the binding correctly.))

My binding was:
```xml
<controls:SwitchPresenter Value="{x:Bind ((muxc:NavigationViewItem)NavMenu.SelectedItem).Content, Mode=OneWay}">
```

Works fine on UWP.

Full code which works on WASM with regular binding, but swapping with x:Bind fails:

```xml
    <muxc:NavigationView x:Name="NavMenu">
        <muxc:NavigationView.MenuItems>
            <muxc:NavigationViewItem Content="Home" Icon="Home" />
            <muxc:NavigationViewItem Content="Page 2" IsSelected="True">
                <muxc:NavigationViewItem.Icon>
                    <!--  TODO: This icon doesn't display on WASM  -->
                    <FontIcon FontFamily="{ThemeResource SymbolThemeFontFamily}" Glyph="&#xEA80;" />
                </muxc:NavigationViewItem.Icon>
            </muxc:NavigationViewItem>
        </muxc:NavigationView.MenuItems>
        <!--  {x:Bind ((muxc:NavigationViewItem)NavMenu.SelectedItem).Content, Mode=OneWay} doesn't work on WASM  -->
        <controls:SwitchPresenter Value="{Binding SelectedItem.Content, ElementName=NavMenu}">
            <controls:Case Value="Home" />
            <controls:Case Value="Page 2">
                <views:Page2 />
            </controls:Case>
        </controls:SwitchPresenter>
    </muxc:NavigationView>
```

**Comment by jeromelaban** [comment]
@hawkerm thanks for the update! I'll reopen to track this additional scenario.

**Comment by Youssef1313** [comment]
Let's see if https://github.com/unoplatform/uno/pull/12367/ is going to fix this.

**Comment by Youssef1313** [comment]
@hawkerm Would you be able to verify if it's fixed in 5.0.0-dev.1646 or later?

**Comment by ramezgerges** [comment]
I've tested this on Windows, before dev.1646 and after.

```
{x:Bind ((muxc:NavigationViewItem)NavView.SelectedItem).Name, Mode=OneWay}
```

Windows: works
Pre 1646: don't compile: error CS1001: Identifier expected
Post 1646: compiles, but doesn't give any value (e.g. I tested with a textblock and the textblock is blank)


```
{x:Bind NavView.SelectedItem.(muxc:NavigationViewItem.Name), Mode=OneWay}
```

Windows: works
Pre 1646: don't compile: error CS1001: Identifier expected
Post 1646: don't compile: error CS1001: Identifier expected

**Comment by Youssef1313** [comment]
Thanks @ramezgerges for confirming.

For the first expression (which compiles but doesn't work), I'm fixing that in https://github.com/unoplatform/uno/pull/13481

For the second expression, I'm not sure if it's worth supporting that. The syntax is ambiguous between attached properties and cast, and I believe that UWP/WinUI will first try to resolve it as attached property, and if that fails, it tries to resolve it as a cast. However, from [UWP docs for x:Bind casts](https://learn.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension#casting):

> Note: The C#-style cast syntax is more flexible than the attached property syntax, and is the recommended syntax going forward.

**Comment by jeromelaban** [comment]
Let's close this particular issue and create another enhancement one for the specific syntax that we don't support. Thanks @Youssef1313!
