### ISSUE TITLE
[iOS] ScrollViewer_Margin test is failing

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#8213]
### Current behavior

All builds are failing since https://github.com/unoplatform/uno/pull/8098 (last successful build: https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=41570&view=results).

Seems the test `ScrollViewer_Margin` is now flaky as on iOS changing `Height` then `Width` works but changing `Width` then `Height` fails.

Test is has been disabled for now on iOS: https://github.com/unoplatform/uno/commit/c971d8e503c42a81ee94a9057a7efd9f37d29cb8

**Comment by agneszitte-nventive** [comment]
Related commit from @dr1rrb to disable the test for now for iOS:
https://github.com/unoplatform/uno/commit/c971d8e503c42a81ee94a9057a7efd9f37d29cb8
