### ISSUE TITLE
[Gallery][Android]TabBar(Material)- "only" Text for the 'Content only' Tab and "Right" Icon  for 'Tab with Icon' Tab are truncating for TabBar items.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8228]
### Current behavior

![Only text truncate issue new](https://user-images.githubusercontent.com/74563602/156657781-5c2f4937-f82e-446c-9f4b-45a328e83092.png)

### Expected behavior
 right icon and 'Content only' text should not get truncate.
![only text correct](https://user-images.githubusercontent.com/74563602/156656762-35870545-910a-4551-b2a7-37bb230b9e50.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP .
2. Click/tap Burger Menu on the left top right.
3. Ensure that the Gallery app is in Day Mode.
4. Tap "TabBar" from the "Toolkit" list.
5. Go to 'Material' section.
6. Go to 'Adding Items as TabBarItems directly' section.
7. Observe that 'Right Icon' is truncating for 'Tab with Icon' Tab and 'Only' text is truncating  at the end for the 'Content Only' tab. 

### Affected platforms

Android

**Comment by sakshi173** [comment]
**Bug is not fixed**, Verified in the latest canary build, Due to that reopening it.
Version 1.5.0 (400898) ,Mar 22, 2022 at 22:36, Canary    a339922fe42f1a09ff9a02a3495b2528e8454422
![tabbar issue 2](https://user-images.githubusercontent.com/74563602/159707874-5be31cc9-13ce-45c2-a452-8b7ade0d09ce.png)

**Comment by kazo0** [comment]
@sakshi173 is this still an issue with the latest canaries?

**Comment by sakshi173** [comment]
@kazo0, I check it and let you know. Thanks!!

**Comment by sakshi173** [comment]
@kazo0,  I checked the issue is still present. and also there is another new bug --- Home Icon is not displaying correctly for all platform. I am raising it separately.

**Comment by kazo0** [comment]
@sakshi173 thanks!

Yeah the Home icon will be fixed when this merges https://github.com/unoplatform/uno.toolkit.ui/pull/434
