### ISSUE TITLE
[All] Net 6 Template dotnet ef claiming not to be supported  

### ISSUE THREAD

**Issue by bstrother1** [unoplatform/uno#8229]
### Current behavior

Attempting to Run dotnet ef on the latest Uno Net6 Template claims all the targeted frameworks under the Mobile head are not supported. 

### Expected behavior

dotnet ef to migrate 

### How to reproduce it (as minimally and precisely as possible)

Follow https://github.com/unoplatform/uno/discussions/7833 
Use VS 2022 latest Mac Preview Version
Follow https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli
Attempt Migration 

[EntityFrameworkUno.zip](https://github.com/unoplatform/uno/files/8181551/EntityFrameworkUno.zip)

### Workaround

none

### Works on UWP/WinUI

No

### Environment

Other

### NuGet package version(s)

PackageReference Include="Uno.UI" Version="4.2.0-dev.205"
PackageReference Include="Uno.UI.RemoteControl" Version="4.2.0-dev.205" Condition="'$(Configuration)'=='Debug'"
PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.2.0-dev.205" 
PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" 
PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" 
PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.0.7" 
PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.14" 
PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.14"
PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.14" 

### Affected platforms

Solution Templates

### IDE

Visual Studio 2022

### IDE version

17.0.0.7303 (The latest available to MacOS)

### Relevant plugins

uno-check -> latest
rosetta2 -> latest

### Anything else we need to know?

On an ARM64 Mac Architecture. 
Latest 6.0.2 sdk

**Comment by ebariche** [comment]
dotnet-ef throws if the target platform is not blank or windows (net6.0 or net6.0-windows in this case)

https://github.com/dotnet/efcore/blob/197479e871148acfc882cd166e8ac28a089a30c9/src/dotnet-ef/RootCommand.cs#L123
