### ISSUE TITLE
[Gallery][Android]TabBar(Material) Text color for the default selected tab is not displaying as per selected theme.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8231]
### Current behavior

**Screenshot for the Standard TabBar style page**
![text color issue](https://user-images.githubusercontent.com/74563602/156822563-fec8fcda-cd6b-4367-abbe-9d0c88521bc5.png)

**First screenshot is for the Top TabBar sample page and Bottom TabBar sample page( IN DAY MODE)**
**Second Screenshot is for the Top TabBar sample page and Bottom TabBar sample page( IN NIGHT MODE)**
![text color issue day mode](https://user-images.githubusercontent.com/74563602/156823033-4c09e674-d669-4f19-86de-3a4b408984af.png)
![Text color night mode issue](https://user-images.githubusercontent.com/74563602/156823047-99b38404-50f0-4b32-bf86-248b87b51e9b.png)

### Expected behavior

Text color for all the tabs(Support, Search)  should be correct. as per selected theme (white in Day mode, Black in night mode). 
**Screenshot for the Standard TabBar style page**
![text color correct](https://user-images.githubusercontent.com/74563602/156823596-2fc01f7a-c21e-4d35-ae60-b9edeadaeaa8.png)
Screenshot is for the Top TabBar sample page and Bottom TabBar sample page( IN DAY MODE)
![text color correct top](https://user-images.githubusercontent.com/74563602/156823618-bfb79772-2a2f-4f97-814e-21e45ff039a5.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP .
2. Click/tap Burger Menu on the left top right.
3. Ensure that the Gallery app is in Day Mode.
4. Tap "TabBar" from the "Toolkit" list.
5. Go to 'Material' section.
6. Notice that the text color for 'Support' and 'Content only' Tab is displaying in black color.
7. Click/Tap on 'SHOW TOP TABBAR SAMPLE' or 'SHOW BOTTOM TABBAR SAMPLE' button.
8. Notice that text color for 'Search' tab is displaying in black color instead of white color.

### Affected platforms

Android

**Comment by francoistanguay** [comment]
@kazo0  ?

**Comment by kazo0** [comment]
Should be fixed by https://github.com/unoplatform/uno.toolkit.ui/pull/197
