### ISSUE TITLE
[macOS] actool warning : The image set "unologo" has 8 unassigned children. 

### ISSUE THREAD

**Issue by Juriyx** [unoplatform/uno#8238]
### Current behavior

I try to build macOS .NET 6 on Azure DevOps
``` PowerShell
dotnet tool install -g Uno.Check --version 1.1.0-dev.*
uno-check --target macos -n -f --dev --ci -v --skip xcode --skip gtk3 --skip vswin --skip vsmac --skip androidemulator --manifest https://raw.githubusercontent.com/unoplatform/uno.check/main/manifests/uno.ui-preview.manifest.json

dotnet build -c Release -f net6.0-macos
```

and get

`/Users/runner/work/1/s/Client/Client.Mobile/obj/iPhoneSimulator/Release/net6.0-macos/osx-x64/actool/cloned-assets/Assets.xcassets : actool warning : The image set "unologo" has 8 unassigned children. [/Users/runner/work/1/s/Client/Client.Mobile/Transmission.Client.Mobile.csproj]`

### Expected behavior

Builds without issues

### How to reproduce it (as minimally and precisely as possible)

Create from .NET 6 template and update to Uno.UI 4.2.0-dev.217

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.2.0-dev.217

### Affected platforms

macOS

### IDE version

17.1

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
