### ISSUE TITLE
[CommandBar] Alignment of icons not working correctly in some cases

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#8254]
### Current behavior

1. Some buttons are not horizontally aligned: 

![image](https://user-images.githubusercontent.com/1075116/157029680-ecc0b41a-7ad2-4734-8405-2c6075cc0463.png)

```xaml
<CommandBar VerticalAlignment="Bottom">
    <AppBarToggleButton Icon="Shuffle" Label="Shuffle" Click="AppBarButton_Click" />
    <AppBarToggleButton Icon="RepeatAll" Label="Repeat" Click="AppBarButton_Click"/>
    <AppBarSeparator/>
    <AppBarButton Icon="Back" Label="Back" Click="AppBarButton_Click"/>
    <AppBarButton Icon="Stop" Label="Stop" Click="AppBarButton_Click"/>
    <AppBarButton Icon="Play" Label="Play" Click="AppBarButton_Click"/>
    <AppBarButton Icon="Forward" Label="Forward" Click="AppBarButton_Click"/>

    <CommandBar.SecondaryCommands>
        <AppBarButton Label="Like" Click="AppBarButton_Click"/>
        <AppBarButton Label="Dislike" Click="AppBarButton_Click"/>
    </CommandBar.SecondaryCommands>

    <CommandBar.Content>
        <TextBlock Text="Now playing..." Margin="12,14"/>
    </CommandBar.Content>
</CommandBar>
```

Note that the `Shuffle` and `RepeatAll` icons are misaligned, while the other icons are correctly centered.

2. Three dots button is not vertically aligned: 

![image](https://user-images.githubusercontent.com/1075116/157030029-e6873236-2524-4871-9790-70c0fdb6e3b7.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/1075116/157029967-5e8adafb-f9a1-4207-a114-06551e3681df.png)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

iOS, Android, WebAssembly, WebAssembly renderers for Xamarin.Forms, macOS, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen)

### IDE

Visual Studio 2022

**Comment by Youssef1313** [comment]
It works correctly for me (tested on Wasm, Gtk).

Wasm:

![image](https://user-images.githubusercontent.com/31348972/192159270-b08db313-4e31-47d1-aac2-6e9c99fab2f2.png)

Gtk:

![image](https://user-images.githubusercontent.com/31348972/192159334-50a5978a-4647-457d-baff-4713214bc53e.png)

@MartinZikmund Was this fixed recently? or is there something special to reproduce?

**Comment by MartinZikmund** [comment]
This got fixed by the text rendering rewrite , can be closed 👍
