### ISSUE TITLE
Uno Class Library with non-Windows TFM can't use <Content Include="..."/>

### ISSUE THREAD

**Issue by Arlodotexe** [unoplatform/uno#8266]
### Current behavior

If you create an Uno Class Library with some code and a small addition to the `.csproj`:

![image](https://user-images.githubusercontent.com/9384894/157145886-b13cab12-03e1-4309-83b0-c4b5bb2d50a5.png)
```xml
<ItemGroup>
	<Content Include="**\*.xaml" Exclude="bin\**\*.xaml;obj\**\*.xaml" />
	<Content Include="**\*.cs" Exclude="bin\**\*.cs;obj\**\*.cs" />
</ItemGroup>
```

This content is included in the build output and can be accessed via `StorageFile.GetFileFromApplicationUriAsync()` under UWP and WinAppSDK (`uap10.0.18362;net6.0-windows10.0.19041.0`):

![image](https://user-images.githubusercontent.com/9384894/157146146-9b6435c8-3e42-446d-aff7-8f7502a54c4e.png)
![image](https://user-images.githubusercontent.com/9384894/157146497-1f8c105d-4bce-405e-927a-3dc75517aed8.png)

However, under any other TFMs where Uno.UI is used, including `netstandard2.0`, `net6.0-ios`, `net6.0-macos` ,`net6.0-maccatalyst`, `net6.0-android`, and older TFMs that don't use NET6, the content is neither included in the final build nor accessible with `StorageFile.GetFileFromApplicationUriAsync()`:
 
![image](https://user-images.githubusercontent.com/9384894/157146341-cdad6c22-86e2-401e-a1b9-078f5ec914c2.png)

Skia.WPF:
![image](https://user-images.githubusercontent.com/9384894/157149869-7c7ff64e-e118-4d55-9d85-25a5b54f3085.png)

Skia.GTK: (WSL)
![image](https://user-images.githubusercontent.com/9384894/157146872-865ed8eb-2ad1-40fa-ad18-8cd053f84b61.png)

Droid:
![image](https://user-images.githubusercontent.com/9384894/157147483-78879714-1fbd-47bb-a289-3f7151b3a952.png)

WebAssembly:
![image](https://user-images.githubusercontent.com/9384894/157147620-2ca18de3-c23f-4760-8e9c-5c7e32e650a4.png)

### Expected behavior

Behavior should be consistent between all platforms.

### How to reproduce it (as minimally and precisely as possible)

Attached is a project with a complete, minimal repro of the issue, and should be ready-to-run assuming you've got the proper dependencies and tooling (.NET 6 / MAUI / VS 2022).

This is the same project used to create the screenshots above.
[ConsistentContentIncludeBehavior.zip](https://github.com/unoplatform/uno/files/8201991/ConsistentContentIncludeBehavior.zip)

### Workaround

The only potential workaround is to create a custom MSBuild Target that
1. Checks the head for all referenced projects
2. Checks each referenced project for any usages of `<Content Include="..."/>`
3. Manually copy the files to the project head's "Assets" folder

Then, modify all of your code to only use the Assets folder.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.0.11

### Affected platforms

iOS, Android, WebAssembly, WebAssembly renderers for Xamarin.Forms, macOS, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen)

### IDE

Visual Studio 2022

### IDE version

17.0.5

**Comment by michael-hawker** [comment]
@Arlodotexe we don't need these to be in a library specifically, but just the head/app output right? (I mean ideally it should work for both, but we don't need to bundle them specifically in a library for our scenario.)

**Comment by jeromelaban** [comment]
This issue is related to https://github.com/unoplatform/uno/issues/2502

**Comment by michael-hawker** [comment]
@jeromelaban @ajpinedam @MartinZikmund wondering if you had any insights on this issue (compared to the library specific one in #2502), since we just need it at the application level.

Is there some easier work-around we can do? We're concerned about switching/using embedded resources as we want to only access these files on demand for WASM vs. trying to load them all at application start. (As there'll be hundreds of files in our scenario for documentation/examples.)

**Comment by jeromelaban** [comment]
@michael-hawker For now, the only way to fix this is to have `Content` items injected into the building project at build time. If it's for a local project, create a build.props file that you can reference from the different heads so that the content files can be properly injected at build time. If it's for a nuget package, it's quite similar, but it needs to be registered as a `build` folder props file.

**Comment by jeromelaban** [comment]
I've added a more comprehensive workaround in https://github.com/unoplatform/uno/issues/2502#issuecomment-1111581930, so I'll close this issue as a duplicate.
