### ISSUE TITLE
XAML succinct syntax for `RowDefinitions` and `ColumnDefinitions`

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#8280]
The original implementation in WinUI uses a generic implementation for all lists, which may not be needed for the implementation needed for Grid's implementation of `RowDefinitions` and `ColumnDefinitions`.

This implementation can be included using compile-time generation in the XAML code generation, as well as a `XamlReader` implementation. 

Doc: https://github.com/microsoft/microsoft-ui-xaml-specs/blob/master/active/gridsyntax/GridSyntaxSpec.md#examples

**Comment by HavenDV** [comment]
Implementation Questions:
1. Should we differentiate between UWP/WinUI? - because only WinUI supports it, although we can support both.
2. Do we need to display an error on an error case like here - https://github.com/microsoft/microsoft-ui-xaml-specs/blob/master/active/gridsyntax/GridSyntaxSpec.md#user-error

**Comment by jeromelaban** [comment]
> 1. Should we differentiate between UWP/WinUI? - because only WinUI supports it, although we can support both.
No, let's make it available for both.

> 2. Do we need to display an error on an error case like here - https://github.com/microsoft/microsoft-ui-xaml-specs/blob/master/active/gridsyntax/GridSyntaxSpec.md#user-error. This is complicated by the fact that we need to test this and we cannot use the Uno.UI.Tests project, as a result, we need to make tests that check for the presence of a particular diagnostic after the generator is started. This issue is also raised here - [Have a good way to test source generators in error scenarios #6646](https://github.com/unoplatform/uno/issues/6646). But it's implementable within Uno.UI.SourceGenerators.Tests if we add a net6.0 target

It's indeed a problem we cannot solve yet, but let's implement it anyways for now.
