### ISSUE TITLE
[Gallery][iOS]ComboBox(Fluent) The length of the combobox is not adjusting as per the selected option from dropdown list.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8286]
### Current behavior

![combobox issue 1](https://user-images.githubusercontent.com/74563602/157520941-e8b92422-cb69-40dc-af3c-891e85774ca9.png)

https://user-images.githubusercontent.com/74563602/157520993-7d04e7ab-d68a-4d24-975b-fef946763731.MOV

### Expected behavior
**Expected result screenshot and video is from Android**

https://user-images.githubusercontent.com/74563602/157521076-80421fac-97de-4fd8-95a2-77ed0bd7b5ab.mp4

![combobox correct new](https://user-images.githubusercontent.com/74563602/157524375-e973738d-1b37-4bfb-8338-79c0941602e0.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "ComboBox" from the "Component" list.
4. Go to "Fluent" Section
5. Tap on Combobox dropdown.
6. Choose any option from dropdown list.
7. Observe that the length of the combobox is not adjusting as per the selected option from dropdown list.

### Affected platforms

iOS

### Anything else we need to know?

**The Canary Build(testflight) version is 1.5.0 (887) and tested on iphone 12 for software version 14.1**

**Comment by jeromelaban** [comment]
@sakshi173 Which platform are you taking the expected behavior from ?

**Comment by sakshi173** [comment]
@jeromelaban, The expected behavior is from Android. I will update in the Expected section.

**Comment by sakshi173** [comment]
Verified in the latest canary build, this bug is fixed, Closing it.
Canary build version 1.5.0 (898)
