### ISSUE TITLE
`DataGrid` items visible below the horizontal scrollbar

### ISSUE THREAD

**Issue by brookslindseyjr** [unoplatform/uno#8295]
### Current behavior

![image](https://user-images.githubusercontent.com/18689823/157720550-1a3fb8a1-a8fa-4b30-9622-2beebc6c63ed.png)

When the window is resized to make the horizontal scrollbar show, the scrollbar does not appear at the bottom of the content.

### Expected behavior

The scrollbar should be at the bottom of the content.

### How to reproduce it (as minimally and precisely as possible)

[App1.zip](https://github.com/unoplatform/uno/files/8225685/App1.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.0.1" />
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls" Version="7.1.11" />
    <PackageReference Include="Uno.UI.WebAssembly" Version="4.0.11" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="4.0.11" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.0.11" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="3.1.2" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="3.1.2" />
  </ItemGroup>

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

Version 17.2.0 Preview 1.0

**Comment by brookslindseyjr** [comment]
Packages:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.0.1" />
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls" Version="7.1.11" />
    <PackageReference Include="Uno.UI.WebAssembly" Version="4.0.11" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="4.0.11" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.0.11" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="3.1.2" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="3.1.2" />
  </ItemGroup>
```

**Comment by jeromelaban** [comment]
## Note for contributors:

From the sample, the following code shows that the DataGrid is not clipped:
```xaml
<UserControl
    x:Class="App1.MyControl"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App1"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    d:DesignHeight="300"
    xmlns:controls="using:Microsoft.Toolkit.Uwp.UI.Controls"
    d:DesignWidth="400">

    <Grid>
        <Grid Height="75" Background="Red">
            <controls:DataGrid x:Name="GridView"
                               Height="75"
                               VerticalAlignment="Top"
                               AutoGenerateColumns="True"
                               CanUserReorderColumns="False"
                               CanUserResizeColumns="True"
                               CanUserSortColumns="False"
                               GridLinesVisibility="None"
                               ItemsSource="{x:Bind ViewModel.Customers}"
                               ScrollViewer.HorizontalScrollBarVisibility="Auto"
                               ScrollViewer.VerticalScrollBarVisibility="Auto"
                               SelectionMode="Extended">
            </controls:DataGrid>
        </Grid>
        <!--<controls:DataGrid x:Name="dataGrid1" 
            Height="600" Width="300" Margin="12"
            AutoGenerateColumns="True"
            ItemsSource="{x:Bind ViewModel.Customers}" />-->
    </Grid>
</UserControl>
```

**Comment by jeromelaban** [comment]
This is a clipping issue, specifically for the items that layout larger than their parent's allotment.

@brookslindseyjr An immediate workaround is to set a border around the `DataGrid`, with the same Width or Height, and set a very small `CornerRadius`:

```xaml
    <Grid x:Name="topControl">
        <Grid Height="75" Background="Red">
        </Grid>
        <Border Height="75" VerticalAlignment="Top" CornerRadius="0.00001">
            <controls:DataGrid x:Name="GridView"
                               Height="75"
                               VerticalAlignment="Top"
                               AutoGenerateColumns="True"
                               CanUserReorderColumns="False"
                               CanUserResizeColumns="True"
                               CanUserSortColumns="False"
                               GridLinesVisibility="None"
                               ItemsSource="{x:Bind ViewModel.Customers}"
                               ScrollViewer.HorizontalScrollBarVisibility="Auto"
                               ScrollViewer.VerticalScrollBarVisibility="Auto"
                               SelectionMode="Extended">
            </controls:DataGrid>
        </Border>
    </Grid>
```

You can do that globally by setting the same corner radius in a DataGrid style if you have one.

**Comment by bstrother1** [comment]
Experiencing same issue with latest stable build.

**Comment by jeromelaban** [comment]
@Youssef1313 as you've worked recently on clipping, could you take a look to see if this is fixed?

**Comment by Youssef1313** [comment]
@jeromelaban Thanks for noting. I'll verify if https://github.com/unoplatform/uno/pull/13695 fixes it. I was already searching for all clipping-related issues to verify and see what will get fixed by https://github.com/unoplatform/uno/pull/13695, but I missed this one during my search.

**Comment by ChaseKopp6** [comment]
appears to be resolved

**Comment by jeromelaban** [comment]
Thanks for the update!
