### ISSUE TITLE
UWP Sync generator does not work under VS 2022

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#8304]
### Current behavior

When running UWP Sync generator under VS 2022, it tries to find `Microsoft.Windows.UI.Xaml.Common.Targets` in `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\WindowsXaml\v17.0` instead of `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\WindowsXaml\v17.0` and fails.

### Expected behavior

Should work properly

### Environment

Other

### Affected platforms

Build tasks

**Comment by Youssef1313** [comment]
@MartinZikmund The last time I worked on it was under VS 2022 following the instructions in https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/building-uno-ui.md#running-the-syncgenerator-tool. Are you following it?

**Comment by Youssef1313** [comment]
For reference, https://github.com/unoplatform/uno/pull/6856

**Comment by MartinZikmund** [comment]
@Youssef1313 you are definitely right, didn't know about those docs! Thanks!
