### ISSUE TITLE
[Android] Borders are choppy/rendering incorrectly

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#8324]
### Current behavior

On Android rounded corners are now choppy or rendering incorrectly.

``` xaml
<Button CornerRadius="20" Content="Test" ... />
```

![image](https://user-images.githubusercontent.com/1075116/158080567-820c3040-c7ba-47a7-836d-987f20226c24.png)

``` xaml
<Button CornerRadius="2" Content="Test" ... />
```

![image](https://user-images.githubusercontent.com/1075116/158080608-bfa2ad56-4580-4307-a3ea-2fa4229cb10f.png)

Notice the rounded corners show up only on the right side of the buttons, although they should be applied on all corners.

The problem was most likely introduced with https://github.com/unoplatform/uno/pull/8118. It seems the changes need to be enabled conditionally - only for straight borders without rounding. 

When fixing, make sure the changes don't break https://github.com/unoplatform/uno/issues/6490 which was fixed by #8118 (and which was, interestingly, also happening for rounded corners to some extent - see discussion on #6490)

### Expected behavior

Borders should render correctly.

Following screenshots from 4.0.13:

![image](https://user-images.githubusercontent.com/1075116/158080947-192994b6-212e-431d-b80f-95c9591081e5.png)

![image](https://user-images.githubusercontent.com/1075116/158080913-b8d9087b-0448-41ac-afc4-a3ce66eb5ac5.png)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.2. dev, works in 4.1.8

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by MartinZikmund** [comment]
Not a regression as it works in 4.1.8. Problems are appearing in 4.2 dev

**Comment by kazo0** [comment]
I believe it actually is a regression, this is 100% caused by https://github.com/unoplatform/uno/pull/8118. Looks like I was just doing the wrong thing when trying to reproduce

**Comment by MartinZikmund** [comment]
@kazo0 that's odd, I have downgraded the app where I found the problem from 4.2 dev to 4.1.8 and the problem is not happening there 🤔

**Comment by kazo0** [comment]
Hmm, I'm confused still. The shapes are definitely smooth and sexy if I remove just the `paint.AntiAlias = false` calls. Maybe that didn't get into 4.1.8 somehow?

**Comment by MartinZikmund** [comment]
@kazo0 You are right! I filtered 4.1 branch and indeed the commit is not in it!
