### ISSUE TITLE
[Calculator][MacOS] Pressed/Click numbers are not visible in the Text section from second digit onwards.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8330]
### Current behavior

![Digit display](https://user-images.githubusercontent.com/74563602/158227049-b8f4d8cd-a563-4115-b63b-3625b0976373.png)

https://user-images.githubusercontent.com/74563602/158227163-05d50982-f5b3-4e9f-bf69-859bd27308ae.mp4

### Expected behavior

![Display correct](https://user-images.githubusercontent.com/74563602/158227188-8f14a1df-64c0-4015-a2fd-d035d38b67d6.png)

https://user-images.githubusercontent.com/74563602/158227227-1b71f165-49ee-4f69-8625-7ea4fe3fdc73.mp4

### How to reproduce it (as minimally and precisely as possible)

1. Open Calculator App.
2. Observe that in the standard section.
3. Click/ press multiple numbers keys on calculator.
4. Observe that in the text section, pressed key are not displaying from second digit onwards.
5. 

### Affected platforms

macOS

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
