### ISSUE TITLE
[Calculator][MacOS] Calculation keys symbol(+ - x =) gets disappears, when hover cursor on calculation keys.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8332]
### Current behavior

![hover cursor issue1](https://user-images.githubusercontent.com/74563602/158253828-c943d1d2-1213-4421-bf7e-7d4828dae660.png)

https://user-images.githubusercontent.com/74563602/158251390-c0924086-7508-4758-9473-d1b2a72cb051.mov

### Expected behavior

![hover cursor correct](https://user-images.githubusercontent.com/74563602/158253882-ebae61de-c7da-491d-b510-1c8727d7560f.png)

https://user-images.githubusercontent.com/74563602/158251343-38e622c3-59d4-4243-a2f3-ee13ec34cb72.mp4

### How to reproduce it (as minimally and precisely as possible)

1. Open Calculator App.
2. Notice that "Standard" calculator is open.
3. Click on Calculation keys(+, -, x, =, and division sign).
4. Observe that calculation keys symbol gets disappears, when hover cursor on calculation keys.

### Affected platforms

macOS

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
