### ISSUE TITLE
[Android] When Frame stack pages, it doesn't collapse them

### ISSUE THREAD

**Issue by MediumsGate** [unoplatform/uno#8333]
### Current behavior

Hello, I started a multi-platform Xamarin project. Following the getting started tutorial on the Uno website, I implemented the frame navigation. On my android device in debug mode, the page changes from page 1 to page 2 however, tapping in the exact same spot where my button was on page 1 will add page 2 to the stack indefinitely as long as I keep tapping in that spot even though I'm on page 2. This doesn't happen in UWP.

Tutorial: https://platform.uno/docs/articles/guides/native-frame-nav-tutorial.html

Visual Studio 2022 version: 17.1.1
Uno Version: 4.1.8.36
Android target version: 12.0 (S)

Debug on android 11 - my personal device
Emulator - pixel 5 

![Nuget Packages 1](https://user-images.githubusercontent.com/94095525/158288385-5a3b0ce3-c402-4491-a4d0-c049025c1fc1.JPG)
![Nuget Packages 2](https://user-images.githubusercontent.com/94095525/158288387-8f7b214c-7a64-481a-9f3e-a3fe7c8dce06.JPG)
![Nuget Packages 3](https://user-images.githubusercontent.com/94095525/158288388-d5fa83a5-06aa-4b23-9465-167335620ba8.JPG)

### Expected behavior

I'd like to prevent the same page being added to the stack more than once.

### How to reproduce it (as minimally and precisely as possible)

[Uno Android Frame Navigation Issue.zip](https://github.com/unoplatform/uno/files/8249876/Uno.Android.Frame.Navigation.Issue.zip)

### NuGet package version(s)

![Nuget Packages 1](https://user-images.githubusercontent.com/94095525/158288385-5a3b0ce3-c402-4491-a4d0-c049025c1fc1.JPG)
![Nuget Packages 2](https://user-images.githubusercontent.com/94095525/158288387-8f7b214c-7a64-481a-9f3e-a3fe7c8dce06.JPG)
![Nuget Packages 3](https://user-images.githubusercontent.com/94095525/158288388-d5fa83a5-06aa-4b23-9465-167335620ba8.JPG)

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.1.1

### Relevant plugins

I'm using the material design library but for the project attached, I started from scratch and was able to repeat the issue without any added packages / plugins

**Comment by MediumsGate** [comment]
Forgot to add, to repeat the issue just start the project in an android emulator and click the buttons leading to the next page. if you leave your mouse in the same spot and continue to click, the last page keeps adding to the stack. same on my personal device.

**Comment by dr1rrb** [comment]
This is a regression introduced by https://github.com/unoplatform/uno/pull/7571

# Workaround
You can either:
* Set `FeatureConfiguration.FrameworkElement.UseLegacyHitTest = true;` in your app's constructor to globally fix the issue (this will however also disable the fixed made by this PR)
* Move / duplicate the background of your page to the root panel of your page (usually a `Grid`):
![image](https://user-images.githubusercontent.com/8635919/158399749-7099b6cd-55d6-4d6f-8c56-10bc1dcf9b10.png)
