### ISSUE TITLE
[Skia.Gtk] Scrolling not working on touch screen

### ISSUE THREAD

**Issue by SNival** [unoplatform/uno#8369]
### Current behavior

Not able to scroll listview using touch gesture, but works as expected with the mouse

### Expected behavior

Scrolling possible using the finger

### NuGet package version(s)

Uno.UI.Skia.Gtk 4.1.8

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### Anything else we need to know?

Tested on Raspberry PI 3, running Raspbian 10 (buster)
Seems partialy fixed in 4.2.0-dev.299 (scrolling works but the "touchable" zone seems to vary depending on the position of the visible part relative to the whole scrollable content)

[Scrolling.zip](https://github.com/unoplatform/uno/files/8281613/Scrolling.zip)

**Comment by dr1rrb** [comment]
This is most probably linked to https://github.com/unoplatform/uno/discussions/8275

**Comment by SNival** [comment]
Fixed in version 4.3
