### ISSUE TITLE
Consider using `$(SolutionFileName)` to determine the value of `UnoTargetFrameworkOverride`

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#8380]
- If `Uno.UI-iOS-only.slnf` is open, set `UnoTargetFrameworkOverride` to `xamarinios10`
- If `Uno.UI-Android-only.slnf` is open, set it to `MonoAndroid12.0`
- If `Uno.UI-net6-only.slnf` is open, keep the current behavior and let the developer specify one of `net6.0-**` TFMs.
- etc..

Two benefits I'm expecting:

- Ability to work on multiple solutions at the same time. I don't think this is possible today?
- Better development experience. One will not have to keep switching `UnoTargetFrameworkOverride` (or the number of doing so will be much smaller)

**Comment by jeromelaban** [comment]
Unfortunately, at this time, there's no property defined in visual studio when a filter has been applied, and this is the main use case for this.

**Comment by Youssef1313** [comment]
Ah, it seems the support was previously added but removed in https://github.com/dotnet/msbuild/pull/6363

FYI @rainersigwald @Forgind about this use case.

**Comment by Forgind** [comment]
I don't have a strong opinion on whether it should exist or not, but as I recall, the argument that it should not exist is that a solution filter is, as the name implies, something to filter which projects of a solution are at play, not something that should change behavior beyond that. When building the whole solution, if you set UnoTargetFrameworkOverride to xamarinios10;MonoAndroid12.0;net6.0-*, then that should ideally be the same for any solution filter. That said, reenabling it would have the benefits you mention above, hence me not having a strong opinion.

**Comment by jeromelaban** [comment]
If that property were to be added, it would help for newcomers to Uno in a big way to remove friction. Having to change an arbitrary property in a file is not particularly intuitive, thanks for details!
