### ISSUE TITLE
[macOS] Scaled resource assets are not supported

### ISSUE THREAD

**Issue by SkyeHoefling** [unoplatform/uno#8385]
### Current behavior

Displaying an `Image` using the shared `Assets` folder on macOS does not properly pull the correct file from the bundle like it does on other platforms. The code below works on other platforms but not macOS

```xml
<Image Source="ms-appx:///Assets/folder.png" />
```

### Expected behavior

When specifying the assets folder using `ms-appx:///Assets/folder.png` the system should properly load the correct scaled item from the macOS bundle.

### How to reproduce it (as minimally and precisely as possible)

1. Create new uno app using `dotnet net unoapp-winui`
2. Open Visual Studio for Mac (this entire test happens on macOS)
3. Add scaled image assets to the shared project. In my case I used `folder.scale-100.png`, `folder.scale-125.png`, `folder.scale-150.png`, `folder.scale-200.png`, and `folder.scale-300.png`
4. Add code below to MainPage.xaml
5. Launch iOS app to ensure image loads correctly
6. Launch macOS and see image is not loading correctly

**MainPage.xaml Code**
```xml
<StackPanel>
    <!-- This does not work on macOS -->
    <Image Source="ms-appx:///Assets/folder.png" />

    <!-- This works on macOS -->
    <Image Source="ms-appx:///Assets/folder.scale-300.png" />
</StackPanel>
```

**Reproduction Sample Project**
[ImageNotShowing.zip](https://github.com/unoplatform/uno/files/8309452/ImageNotShowing.zip)

### Workaround

The files are properly being included in the macOS bundle, the image loader just doesn't select the correct one. A workaround will be to manually specify the scaled image.

```xml
**MainPage.xaml Code**
```xml
<StackPanel>
    <Image Source="ms-appx:///Assets/folder.scale-300.png" />
</StackPanel>
```

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

```xml
<PackageReference Include="Uno.WinUI" Version="4.1.8" />
<PackageReference Include="Uno.WinUI.RemoteControl" Version="4.1.8" Condition="'$(Configuration)'=='Debug'" />
<PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.1.8" />
<PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
```

### Affected platforms

macOS

### IDE

Visual Studio for Mac

### IDE version

17.0 Preview (17.0 Build 8001)

### Relevant plugins

Not applicable

### Anything else we need to know?

Through my research it appears that in macOS the assets are being added correctly to the macOS bundle resources, but the Uno Platform code is not selecting the correct scaled image

**Comment by jeromelaban** [comment]
Thanks for the report! This is indeed a missing feature for macOS. Some of the code which is able to handle this is available for WebAssembly or natively on iOS, but it is neither is used for the macOS target.

**Comment by iury-kc** [comment]
Hi all!
Using Uno 4.1.9:

![image](https://user-images.githubusercontent.com/100223422/166515123-61161317-1e83-46fd-b3ae-70d96254fd10.png)

Even a simple png couldn't be loaded. 

Investigating...

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
