### ISSUE TITLE
MessageDialog is no longer native

### ISSUE THREAD

**Issue by jeanplevesque** [unoplatform/uno#8415]
## Current behavior

![image](https://user-images.githubusercontent.com/39710855/159733204-a148c526-374a-4436-87e7-2a3706b5fd22.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/39710855/159733018-c78cda26-a307-4111-a233-4caafc3f7a47.png)

## Repro rate

100%

## Impacted build / release

- Environment: Staging
- Source branch: canaries/build/dev/build_20220323.1
- Source commit: b3775be809b7cb2de4594c46f5d32257c8d84ed9
- Pipeline run : 20220323.1
- Uno.UI nuget package version (for Devs): 4.2.0-dev.423

## Last known working build / release

- Environment: 
- Source branch + CommitID: 
- Build version (for QA): 
- Uno.UI nuget package version (for Devs): 4.2.0-dev.13
- Works on the latest Uno Stable/Dev branch: No

## Affected platform(s):

- [x] iOS
- [x] Android
- [ ] ~~WebAssembly~~
- [ ] ~~MacOS~~
- [ ] ~~Windows~~
- [ ] ~~Linux~~
- [ ] ~~Build tasks~~

## Visual Studio (for devs):

- [ ] 2019 (version: )
- [ ] for Mac (version: )

## Specific cases:
- [ ] Crash (Please provide device crash logs in attachment of this issue)
- [ ] App/Animation slower (Please provide a video/GIF with comparison)
- [ ] Cryptic msbuild failure (Please provide the `msbuild.binlog` file created when running `msbuild /r /bl yousolution.sln`)

## Anything else we need to know?

https://github.com/unoplatform/nventive-private/issues/373

**Comment by MartinZikmund** [comment]
@Youssef1313 the problem is too many buttons on small screen. However the style comes from WinUI, so it should probably be adjusted there

**Comment by jeanplevesque** [comment]
This is still a problem on 4.2.0-dev.490. Is it that packages weren't released yet?

**Comment by jeromelaban** [comment]
Take a look at the builds here: https://dev.azure.com/uno-platform/Uno%20Platform/_build?definitionId=5&branchFilter=1446%2C1446%2C1446%2C1446%2C1446%2C1446, you can find the related PR.

**Comment by jeanplevesque** [comment]
It's back to normal using 4.2.0-dev.513. Thanks!
