### ISSUE TITLE
Docs(Mermaid): Mermaid version will need to be bumped when the related issue is fixed

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno#8431]
### Current behavior

There is additional whitespace above and below the flowchart diagrams.
Mermaid version will need to be bumped here when this issue is fixed : https://github.com/mermaid-js/mermaid/issues/1984.
For now, it's using the version [8.14.0](https://github.com/mermaid-js/mermaid/releases/tag/8.14.0)

![image](https://user-images.githubusercontent.com/16295702/160211762-94c07999-1b30-4751-8cf9-1d62fe2e8161.png)

### Expected behavior

No more additional whitespace above and below the flowchart diagrams.

### How to reproduce it (as minimally and precisely as possible)

Example of a page with the problem: https://platform.uno/docs/articles/uno-development/Uno-UI-Layouting-iOS.html

### Workaround

N/A 
(Already tried version 8.8.0, because the issue was introduced with version 8.8.1. But the actual syntax is not supported with this older version).

### Environment

Other

### NuGet package version(s)

Mermaid version [8.14.0](https://github.com/mermaid-js/mermaid/releases/tag/8.14.0)

### IDE

Visual Studio 2022

**Comment by MartinZikmund** [comment]
@agneszitte  is this still relevant?
