### ISSUE TITLE
VS 17.2 Preview 2: Operation is not valid due to the current state of the object

### ISSUE THREAD

**Issue by arafattehsin** [unoplatform/uno#8455]
Hi. I am using Visual Studio 2022 17.2.0 (Preview 2) and upon creating a fresh project, I am getting this. 

![image](https://user-images.githubusercontent.com/16351038/160823459-7fedd9f3-ff37-4fac-be0b-842bae58579c.png)

When I went into my repos, I can see this but it does not have a solution file.

![image](https://user-images.githubusercontent.com/16351038/160823945-55cd1bd1-31dd-400e-a66c-5472791747d3.png)

**Comment by jeromelaban** [comment]
## Note for contributors

Here's the current likely exception site:
https://github.com/unoplatform/uno/blob/aea1b9a868311b59ca27ee52175f392ec34391ea/src/SolutionTemplate/UnoSolutionTemplate.Wizard/UnoSolutionWizard.cs#L132

It's likely that VS 2022 changed its startup sequence for new projects, causing this issue.
