### ISSUE TITLE
IIncrementalGenerator support

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#8458]
## What would you like to be added:
Optimizing generator performance by adding a Roslyn 4 `IIncrementalGenerator` implementation along with the regular Roslyn 3 `ISourceGenerator`. This can improve the user experience in VS2022.
This can be done in parallel with the Roslyn 3 implementation, here is an example implementation of this in CsWin32 - https://github.com/microsoft/CsWin32/pull/355/files

## Why is this needed:
IIncrementalGenerator is a Roslyn 4 interface that allows to control the number of generations based on specific events, and also removes problems with updating the generated code (and, accordingly, with Intellisence)

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by HavenDV** [comment]
On the user side, due to the large number of Uno projects, VS IDE slowed down quite noticeably when I was working with an average project of 100-200 thousand lines of code, so I had to unload Uno projects while working and return to them only when testing. However, this is also possible because of the Shared Projects/Mobile platforms and their tools.
Have you measured how often code generation happens and how much it slows down the IDE when actually working on a large project? (I mean not building) I see telemetry, but I would like to know the real results (how much it affects the user).
I think that this has a very tangible impact on how developers feel about working with Uno and will prefer it to other platforms.

**Comment by Youssef1313** [comment]
This might be the same as https://github.com/unoplatform/uno/issues/7506. It's still possible to improve the performance without using incremental generators. I think #7506 should first be fixed, then you re-test and see if your problem is fixed.

**Comment by jeromelaban** [comment]
At this time, changing generators to support this requires to move to C# 10 for uno consumers, which is something we can't do yet. There are intermediate changes that could be done to reduce the pressure, like having a "design-time" only generation, particularly when we run the generators only to create x:Name fields for intellisense.

**Comment by HavenDV** [comment]
> At this time, changing generators to support this requires to move to C# 10 for uno consumers, which is something we can't do yet. There are intermediate changes that could be done to reduce the pressure, like having a "design-time" only generation, particularly when we run the generators only to create x:Name fields for intellisense.

I should note again that having this feature does not negate the existence of the generator for Roslyn 3.x versions. Please see how it's implemented here: https://github.com/microsoft/CsWin32/pull/355/files

**Comment by Youssef1313** [comment]
> I should note again that having this feature does not negate the existence of the generator for Roslyn 3.x versions. Please see how it's implemented here: [microsoft/CsWin32#355 (files)](https://github.com/microsoft/CsWin32/pull/355/files)
> 
> >

There are some info here https://github.com/dotnet/roslyn-analyzers/issues/5816 which should be taken into account.

**Comment by Youssef1313** [comment]
I have taken a look. It seems impossible to write this as an `IIncrementalGenerator` with the current `IIncrementalGenerator` design.

We need to use `AdditionalTextsProvider` to read the XAML files, and then while reading the XAML files, we will need to get some symbols. We can't do that without combining `AdditionalTextsProvider` with `CompilationProvider`, which is wrong/bad.

@HavenDV Let me know if you have ideas regarding that.

FYI @jeromelaban

**Comment by HavenDV** [comment]
First of all, you need to study this documentation in detail, especially about caching. I had trouble misunderstanding it when I studied generators.
https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md

Here is a small example of the correct combination of CompilationProvider and AdditionalTextsProvider:
```csharp
public void Initialize(IncrementalGeneratorInitializationContext context)
{
    var assemblyName = context.CompilationProvider.Select(static (c, _) => c.AssemblyName);
    var texts = context.AdditionalTextsProvider;

    var combined = texts.Combine(assemblyName);

    context.RegisterSourceOutput(combined, (spc, pair) =>
    {
        var assemblyName = pair.Right;
        // produce source ...
    });
}
```

**Comment by Youssef1313** [comment]
@HavenDV That is exactly what I'm referring to.

It looks impossible to have proper caching.

We don't know beforehand what we want to get out of the `CompilationProvider`.

**Comment by HavenDV** [comment]
Perhaps a list of all class names in an assembly should be used as a step for caching?

**Comment by Youssef1313** [comment]
This is going to be very expensive. In fact, we already have a `BuildLookup` in the current non-incremental implementation, which is very expensive and I'm getting rid of that in https://github.com/unoplatform/uno/pull/11074.

**Comment by HavenDV** [comment]
I think at the moment I don't have enough knowledge (both what specifically the Uno generator needs and the different kinds of providers, my use of them was pretty trivial) to advise. I would first study in detail what each provider provides and try to use that:
> CompilationProvider
AdditionalTextsProvider
AnalyzerConfigOptionsProvider
MetadataReferencesProvider
ParseOptionsProvider
SyntaxValueProvider.CreateSyntaxProvider

**Comment by Youssef1313** [comment]
I'll try to come up with some ideas and investigate if there is any viable option.

**Comment by HavenDV** [comment]
Perhaps this code will give you some ideas, it does not use the CompilationProvider but does the necessary things:
https://github.com/CommunityToolkit/dotnet/blob/main/src/CommunityToolkit.Mvvm.SourceGenerators/ComponentModel/ObservablePropertyGenerator.cs

**Comment by Youssef1313** [comment]
That is an attribute-based generator. Xaml code generator isn't attribute-based.

I'm currently checking the possibility of doing `context.CompilationProvider.Combine(..)`, and otherwise will check alternatives.

**Comment by Youssef1313** [comment]
I doubt we will be able to get a better performance with incremental generators. It will be A LOT of work with very little benefit (if any at all).

I can't really think of a pipeline that will do good caching.

**Comment by Youssef1313** [comment]
As I think we can't benefit that much from using `IIncrementalGenerator` for XAML generator, I'm going to close the issue. Feel free to re-open if you have a more concrete suggestion on an incremental pipeline. Also, if you have cases where the generator performance is causing issues, consider reporting them as we may find a way to optimize it.

**Comment by HavenDV** [comment]
> That is an attribute-based generator. Xaml code generator isn't attribute-based.

I got the idea to try make it attribute-based through .props/.targets files and create an AssemblyAttribute for each required thing. Approximate approach:
```xml
<ItemGroup>
    <AssemblyAttribute Include="Uno.XamlFileAttribute">
      <_Parameter1>%(AdditionalFiles.Identity)</_Parameter1>
      <_Parameter1_IsLiteral>true</_Parameter1_IsLiteral>
    </AssemblyAttribute>
  </ItemGroup>
```

**Comment by Youssef1313** [comment]
Attribute-based generators are those generators that look for attributes specified on something and based solely on that (or very few additional info that are easy to compute), can know what code to generate.

For the case of XAML generator, we need to query the compilation A LOT while we are reading the XAML files. It's almost that **any** change to C# code can affect the XAML-generated code. This basically means there is no good opportunity for being incremental. Instead, we can employ our own caching mechanisms when needed to improve the performance. For example, we already cache GetTypeByMetadataName calls.
