### ISSUE TITLE
[Calculator][MacOS] Changing calculator mode messes up the UI layout

### ISSUE THREAD

**Issue by ajpinedam** [unoplatform/uno#8462]
### Current behavior

When changing the Calculator Mode the UI gets all distorted

<img width="1136" alt="Screen Shot 2022-03-30 at 1 23 50 PM" src="https://user-images.githubusercontent.com/1900897/160914640-fc5f31c7-8c92-4bd8-97cd-1d0a1bccae68.png">

### Expected behavior

The UI does not get messed up when changing Calculation Mode

### How to reproduce it (as minimally and precisely as possible)

- Open Calculator on macOS
- Click on the Hamburger Menu
- Select a Calculator Mode other than the one already selected. For example: if Standard is already selected then pick Programmer or Scientific.

### Workaround

Resizing the Window

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

macOS

### IDE

Visual Studio for Mac

### Anything else we need to know?

Please disregard the different colors. I found this issue while working on something else.

https://user-images.githubusercontent.com/1900897/160914504-31a70e40-494b-459e-bf2f-57bb133025ac.mov

**Comment by jeromelaban** [comment]
Could it be related to https://github.com/unoplatform/uno/pull/5217 ?

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
