### ISSUE TITLE
[Benchmark] - Porting UNO benchmarks project to MAUI runtime.

### ISSUE THREAD

**Issue by aesteves900** [unoplatform/uno#8467]
Porting UNO benchmarks project to MAUI for Android Platform

UNO has a [repository](https://github.com/unoplatform/performance) with benchmarks projects then we need to port to MAUI to generate benchmarks between UNO and MAUI.

![image](https://user-images.githubusercontent.com/5515535/160973172-abaf16b9-27e9-43d6-b416-6671def43eaa.png)

**Comment by MartinZikmund** [comment]
@jeromelaban is this still relevant or can be closed?

**Comment by jeromelaban** [comment]
Yes, thanks!
