### ISSUE TITLE
[WASM] DataTemplate not applied / Styles ignored

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#8469]
### Current behavior

I have e.g. that ListView:
```
<ListView Grid.Row="2" ItemsSource="{x:Bind Path=_vm.OeffentlicheAuftritte, Mode=OneWay}"
                  SelectionMode="None" HorizontalAlignment="Center"
                  ItemTemplate="{StaticResource AuftrittsterminTemplate_Public}">
</ListView>
```

And I've declared a DataTemplate like this in a ResourceDictionary Resources.xaml:
```
<DataTemplate x:Key="AuftrittsterminTemplate_Public" x:DataType="contracts:AuftrittsterminPublic">
        <StackPanel Margin="0,0,0,10">
            <TextBlock Text="{Binding Showtyp}" FontWeight="Bold"/>
            <TextBlock Text="{Binding Spielort}" Margin="10,0,0,0"/>
            <TextBlock Text="{Binding Datum, Converter={StaticResource DateFormatConverter}}" Margin="10,0,0,0"/>
        </StackPanel>
    </DataTemplate>
```

And I've included it in App.xaml like this:
```
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
                <!-- Add resource dictionaries here -->
                <local:Resources/>
            </ResourceDictionary.MergedDictionaries>
            <!-- Add resources here -->
        </ResourceDictionary>
    </Application.Resources>
```

It does not get respected on WASM, though it works on UWP. I feel like I'm missing something here and have stumbled across that. But still it is not the expected way (working out of the box like it does on UWP).

### Expected behavior

The template get applied as expected and seen on UWP.

### Workaround

None, yet

### NuGet package version(s)

4.1.9

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.1.2

**Comment by jeromelaban** [comment]
Thanks for the report! Can you create a small sample application to show the behavior? This way, we'll be certain to look at the same issue.

**Comment by TopperDEL** [comment]
During my preparation of the sample application I found the error. I was including the ResourceDictionary by this line:

```
<ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
                <local:Resources/> <!-- <= HERE -->
            </ResourceDictionary.MergedDictionaries>
```

If I change that to:

`<ResourceDictionary Source="Resources.xaml"/>`

it works. Not sure if the other way should work, too (it does so on UWP), but the other way seems to be clearer and is definitely working. I'll close this issue then.

Thanks!
