### ISSUE TITLE
Crash on Uno.WinUI 4.1.9, System.MissingMethodException: System.Runtime.InteropServices.NFloat.op_Inequality

### ISSUE THREAD

**Issue by edoust** [unoplatform/uno#8472]
### Current behavior

My app uses `net6.0-maccatalyst15.2` and I updated `Uno.WinUI` from `4.1.8` to `4.1.9`.

Now the app crashes on launch with this exception:

````c#
Application Specific Information:
*** Terminating app due to uncaught exception 'System.MissingMethodException', reason: 'Method not found: bool System.Runtime.InteropServices.NFloat.op_Inequality(System.Runtime.InteropServices.NFloat,System.Runtime.InteropServices.NFloat) (System.MissingMethodException)
at UIKit.UIWindow..ctor(CGRect frame)
at Uno.UI.Controls.Window..ctor()
at Microsoft.UI.Xaml.Window..ctor()
at Microsoft.UI.Xaml.Window.InternalGetCurrentWindow()
at Microsoft.UI.Xaml.Window.get_Current()
at Microsoft.UI.Xaml.Application.<>c.<OnLeavingBackground>b__120_0()
at Microsoft.UI.Xaml.Application.RaiseLeavingBackground(Action onComplete)
at Microsoft.UI.Xaml.Application.OnLeavingBackground(NSNotification notification)
at Foundation.InternalNSNotificationHandler.Post(NSNotification s)
'
terminating with uncaught exception of type NSException
abort() called
````

### Expected behavior

The app should not crash

### Works on UWP/WinUI

No

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.1.9

### Affected platforms

macOS

**Comment by jeromelaban** [comment]
Thanks for the report. Please see this thread for fixing this: https://github.com/unoplatform/uno/discussions/7833

**Comment by edoust** [comment]
Thanks but could you please say what the fix is? 
Following discussion #8453 I ran uno-check using the specific manifest, installed .NET 6.0.300 preview and the linked versions of the preview workloads. It builds fine which it did not on 6.0.200..., just crashes with the above error message on both x64 and arm64

---
As a sidenote, uno-check runs into an endless loop on arm64 machines as it installs the x64 version of .NET SDK 6.0.300 but then fails to detect that SDK (I assume it detects the default arm64 6.0.200 installation), so .NET SDK arm64 has to be manually installed in order to get to the workload installation step

**Comment by jeromelaban** [comment]
The issue you're seeing is generally caused by misalignments between the version of Uno you're using and the version of the iOS/Calatyst/macOS which is being used to build the application. troubleshooting this is unfortunately not particularly easy until microsoft will release updated versions of their tools.

**Comment by edoust** [comment]
Can it be an issue if Nuget packages are consumed on macOS that were built on Windows (that contain Uno views but compiled using the same SDK/workload versions)?

**Comment by jeromelaban** [comment]
It generally should not. I don't have specific directions on how to fix this unfortunately, aside from digging into the binlogs to find what workloads are being used. My guess is that RC1 will help.
