### ISSUE TITLE
Add support for "Squircle"-type corner radius

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#8476]
The "Corner radius" of XAML is not enough to follow the iOS design principles of [Squircle](https://en.wikipedia.org/wiki/Squircle). Figma call them ["Corner Smoothing"](https://help.figma.com/hc/en-us/articles/360050986854-Adjust-corner-radius-and-smoothing).

## What would you like to be added:
Support for Squircle corner radius on all platforms (even UWP if possible).

## Why is this needed:
iOS/Cupertino design.

## For which Platform:

- [X] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [X] Skia
- [X] Windows

**Comment by iury-kc** [comment]
Just for information:

https://docs.microsoft.com/en-us/windows/communitytoolkit/parsers/canvaspathgeometry
