### ISSUE TITLE
[WASM] Various GCHandle zero errors in developer tools of Samples app

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#8479]
### Current behavior

Seeing various errors like this is Developer tools of Samples app on latest master, might be some unknown problem.

![gchandlezero](https://user-images.githubusercontent.com/1075116/161156461-54993b06-dbc6-4dd0-9823-0fe01aeb6281.png)

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
Do you still have the full stack trace ?

**Comment by MartinZikmund** [comment]
This was a fault of one of my PRs and was fixed subsequently - closing!
