### ISSUE TITLE
[WASM] Adjust the doc regarding HttpClient on WASM with .net6

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#8482]
## On which page?
https://platform.uno/docs/articles/howto-consume-webservices.html#task-4---create-simple-get-service-for-breed-search

## What's wrong?
The doc mentions the use of `Uno.UI.Wasm.WasmHttpHandler`, but that seems to not be necessary anymore for .Net 6. At least i stumbled across it while updating an older app to the latest Uno template using net6. I got "Value cannot be null" in a "PostAsJsonAsync"-call. It works now as expected by simply using a HttpClient-instance without that specific handler.

**Comment by jeromelaban** [comment]
Thanks for the report!
