### ISSUE TITLE
[UWP] Cannot apply Uno.Material to UWP-App

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#8484]
### Current behavior

I've added Uno.Material to the UWP head and added both lines to App.xaml like this:

```
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
                
                <MaterialColors xmlns="using:Uno.Material" />
                <MaterialResources xmlns="using:Uno.Material" WithImplicitStyles="True"/>
                
                <!-- Add resource dictionaries here -->
                <ResourceDictionary Source="Resources.xaml"/>
            </ResourceDictionary.MergedDictionaries>
            <!-- Add resources here -->
        </ResourceDictionary>
    </Application.Resources>
```

When I run the app now (without any further changes) it crashes on startup with an Exception:
`Local values are not allowed in resource dictionary with Source set [Line: 16 Position: 63]`

The position points to "WithImplicitStyles". If I remove that line, the app starts but I don't get any visual change (as expected). If I then add e.g. the style `Style="{StaticResource MaterialNoCompactMenuNavigationViewStyle}"` to a NavigationView, it crashes with that error:
`Cannot find a Resource with the Name/Key MaterialNoCompactMenuNavigationViewStyle`

So it seems UWP does not really load the style. What might be wrong? Both is working as expected on WASM.

### Expected behavior

The styles get applied like described in the doc on UWP, too.

### Works on UWP/WinUI

No

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.1.9

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

17.1.3

**Comment by kazo0** [comment]
Hi @TopperDEL, thanks for the report! This looks to be an issue that was recently fixed by this PR: https://github.com/unoplatform/Uno.Themes/pull/718

What is the version of the Uno.Material NuGet package you have installed? This should be working as of Uno.Material 1.4.0-dev.12, if not, it is definitely an issue.

**Comment by TopperDEL** [comment]
Thanks @kazo0 - the issue with "WithImplicitStyles" is resolved by using Uno.Material 1.4.0.-dev.30. But `MaterialNoCompactMenuNavigationViewStyle` still cannot be resolved.

**Comment by kazo0** [comment]
> Thanks @kazo0 - the issue with "WithImplicitStyles" is resolved by using Uno.Material 1.4.0.-dev.30. But `MaterialNoCompactMenuNavigationViewStyle` still cannot be resolved.

That style looks to have been renamed to `MaterialWUXNoCompactMenuNavigationViewStyle` quite a while ago. I do see it being used in the [SamplePage.xaml for the Theme sample app](https://github.com/unoplatform/Uno.Themes/blob/f84c56a93a162dbbfb68152a2f352b0c1b68e9c9/src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/SamplesPage.xaml#L18).

Was it from that `SamplePage.xaml` that you found that style name or is it written somewhere in the docs? If so, it meeds to be corrected.

**Comment by TopperDEL** [comment]
Yeah, the renamed style is working. I have that name from an old project where I wanted to have the design from. That project hasn't been updated for nearly two years now. :)
And I guess I saw it on the Uno.Themes-Github-page, but cannot find it there anymore. Weird. 

But I'm closing this issue then as it is resolved for me. Thank you!
