### ISSUE TITLE
Some files don't get generated with `UWPSyncGenerator`

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#8490]
### Current behavior

`BatteryReport` (for example) doesn't get updated when UWPSyncGenerator is run.

### Expected behavior

It gets updated.

**Comment by workgroupengineering** [comment]
Hi @Youssef1313,  
I don't know if it's the same problem. I had a similar problem with the following code:

https://github.com/unoplatform/uno/blob/e7bbb750a0f7009dbe77e88d376928cf103e0070/src/Uno.UWP/Graphics/Imaging/BitmapEncoder.ios.cs#L16-L21

To resol issue i changed code like this:

```csharp
		private static readonly Dictionary<Guid, Func<UIImage, NSData>> _encoderMap =
			new()
			{
				{JpegEncoderId, AsJPEG},
				{PngEncoderId, AsPNG},
			};
		private static NSData AsPNG(UIImage image) => image.AsPNG();
		private static NSData AsJPEG(UIImage image) => image.AsJPEG(1);
```

**Comment by Youssef1313** [comment]
I just tested and it's no longer an issue.
