### ISSUE TITLE
How to use Uno.Material, name space Uno.Material.Controls not found error

### ISSUE THREAD

**Issue by venu-betaacid** [unoplatform/uno#8491]
I was following How to use Uno.Material at 'https://platform.uno/docs/articles/guides/uno-material-walkthrough.html?tabs=tabid-vswin' but got stuck at section 2 step 2 as visual studio complains the name space Uno.Material.Controls not found. I searched NuGet but do not see anything related to Uno.Material.Controls.

**Comment by kazo0** [comment]
Hi @venu-betaacid, thanks for the report!

You are correct, these documentation pages surrounding Uno.Material are no longer up-to-date. The controls such as `Card`, `Divider`, `Chip`, and `ChipGroup` have now all been moved to the new [Uno Toolkit library](https://platform.uno/uno-toolkit/).

So those controls are now found in the [Uno.Toolkit.UI.Material NuGet package](https://www.nuget.org/packages/Uno.Toolkit.UI.Material/) (which itself has a dependency on the [Uno.Toolkit.UI package](https://www.nuget.org/packages/Uno.Toolkit.UI/))

An issue has been created to address those docs here: https://github.com/unoplatform/uno/issues/8475

Apologies for the confusion! We will be getting those docs up-to-date ASAP!

**Comment by kazo0** [comment]
Closing this issue as it is already being tracked by https://github.com/unoplatform/uno/issues/8475
