### ISSUE TITLE
xaml generated by Figma's Uno plugin not working

### ISSUE THREAD

**Issue by venu-betaacid** [unoplatform/uno#8500]
### Current behavior

I Created a new Visual Studio 2022 and Uno-Platform template, it works fine. But when I place replace xaml code generated by figma's uno platform plugin, the project doesn't work. Figma team suggested me follow 'https://github.com/unoplatform/uno.extensions/tree/main/samples/Commerce' to fix build error and it did but the screen (Universal Window Platform) is blank.

App.xaml
`<Application
    x:Class="App10.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App10">
	
    <Application.Resources>
        
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />

                
                <MaterialColors xmlns="using:Uno.Material"
								OverrideSource="ms-appx:///ColorPaletteOverride.xaml" />
                
                

                
                <MaterialResources xmlns="using:Uno.Material"  />
               
            </ResourceDictionary.MergedDictionaries>

            
        </ResourceDictionary>

    </Application.Resources>

</Application>`

MainPage.xaml
`<Page
    x:Class="App10.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:utu="using:Uno.Toolkit.UI"
    xmlns:local="using:App10"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <utu:AutoLayout Background="{ThemeResource MaterialBackgroundBrush}">
        <utu:AutoLayout Spacing="16" Padding="32,48,32,8" utu:AutoLayout.CounterAlignment="Center" utu:AutoLayout.CounterLength="216">
            <TextBlock Foreground="{ThemeResource MaterialOnSurfaceBrush}" Text="Welcome." utu:AutoLayout.CounterAlignment="Center" Style="{StaticResource MaterialHeadline4}" />
            <TextBlock Foreground="{ThemeResource MaterialOnSurfaceBrush}" Text="Log in to your account" utu:AutoLayout.CounterAlignment="Center" Style="{StaticResource MaterialSubtitle2}" />
        </utu:AutoLayout>
        <utu:AutoLayout Spacing="16" Padding="32,8,32,32" utu:AutoLayout.CounterAlignment="Center" utu:AutoLayout.CounterLength="404">
            <TextBox Style="{StaticResource MaterialFilledTextBoxStyle}" />
            <PasswordBox Style="{StaticResource MaterialFilledPasswordBoxStyle}" />
            <HyperlinkButton Content="Forgot password?" Style="{StaticResource MaterialHyperlinkButtonStyle}" />
            <Button Content="Login" Style="{StaticResource MaterialContainedButtonStyle}" />
        </utu:AutoLayout>
    </utu:AutoLayout>

</Page>
`
Complete code
[App10.zip](https://github.com/unoplatform/uno/files/8418669/App10.zip)

### Expected behavior

the screen should be
![image](https://user-images.githubusercontent.com/101668559/161657146-7272654b-8bd5-496e-a70d-7ca0a6bb23e6.png)

### How to reproduce it (as minimally and precisely as possible)

https://playground.platform.uno/#d6c5e151

### Works on UWP/WinUI

No

### NuGet package version(s)

Microsoft.Extensions.Logging 6.0.0
Microsoft.Extensions.Logging.Console  5.0.0
Microsoft.Extensions.Logging.Debug 5.0.0
Microsoft.NETCore.UniversalWindowsPlatform 6.2.11
Microsoft.UI.Xaml 2.6.2
Microsoft.Windows.Compatibility 5.0.0
NETStandard.Library 2.0.3
SkiaShart.Views 2.80.3
Tizen.NET 8.0.015631
Uno.Core.Extensions.Logging.Singleton 4.0.0-dev.7
Uno.Extensions.Logging.OSLog 1.0.1
Uno.Extensions.Logging.WebAssembly.Console 1.0.1
Uno.Extensions.Navigation.UI 1.0.1
Uno.Extensions.Reactive.UI 1.0.1
Uno.Material 1.3.1
Uno.Toolkit.UI 1.3.0
Uno.Toolkit.UI.Material 1.3.0
Uno.UI 4.1.9
Uno.UI.Adapter.Microsoft.Extensions.Logging 4.1.9
Uno.UI.RemoteControl 4.1.9
Uno.UI.Skia.Gtk 4.1.9
Uno.UI.Skia.Tizen 4.1.9
Uno.UI.Skia.Wpf 4.1.9
Uno.UI.WebAssembly 4.1.9
Uno.UniversalImageLoader 1.9.33
Uno.Wasm.Bootstrap 3.2.0
Uno.Wasm.Bootstrap.DevServer 3.2.0

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

Version 17.1.2

**Comment by carldebilly** [comment]
Found the cause if this issue:
* On the **WASM PLAYGROUND**: that was a problem in the way the Playground itself is compiled and the Toolkit library was partially linked-out, causing missing code. In this case it was a property setter. The problem is already fixed and deployed. If you reopen the URL of the playground version, you won't have this problem anymore.
* On **WINDOWS UWP**: there's a missing resource dictionary in your `App.xaml` file. If you add the `<ToolkitResources xmlns="using:Uno.Toolkit.UI" />` declaration [as documented here](https://github.com/unoplatform/uno.toolkit.ui#getting-started), it should work.

**Comment by francoistanguay** [comment]
It was also here in the Commerce sample app: https://github.com/unoplatform/uno.extensions/blob/1e466c56ee670531efa6e493108717fda6d43437/samples/Commerce/Commerce.Shared/App.xaml#L23
