### ISSUE TITLE
Ability to cap TextScaling

### ISSUE THREAD

**Issue by MatFillion** [unoplatform/uno#8501]
## Expected behavior

Add `double Uno.UI.FeatureConfiguration.Font.MaximumTextScaleFactor { get; set; }`.

## Why is it important ?

We can currently either support text scaling or not using `Uno.UI.FeatureConfiguration.Font.IgnoreTextScaleFactor`.
As an in-between, it would be good to support it up to a maximum value.

WCAG 2.0 states text must scale up to 200%.
_SC 1.4.4 requires text to be resizable without assistive technology up to 200 percent. To meet this requirement content must not prevent text magnification by the user._
[source](https://www.w3.org/TR/mobile-accessibility-mapping/)

iOS Allows for way more magnification than 200% and supporting this super edge case is not something we always want to do. We would like to be able to cap the text scaling to 200% in this case.

## Workaround possible?

Not really. 
## For which Platform:
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by Marc-Antoine-Soucy** [comment]
@jeromelaban Hello, is it normal that this is only for IOS.
https://github.com/unoplatform/uno/blob/a64245806b9c2700b357684fc15350da71033e70/src/Uno.UI/FeatureConfiguration.cs#L182

@takla21 @jeanplevesque

**Comment by Marc-Antoine-Soucy** [comment]
@jeromelaban Hello, is it normal that this is only for IOS.
https://github.com/unoplatform/uno/blob/a64245806b9c2700b357684fc15350da71033e70/src/Uno.UI/FeatureConfiguration.cs#L182

@takla21 @jeanplevesque

**Comment by jeromelaban** [comment]
See the documentation: https://github.com/unoplatform/uno/blob/a64245806b9c2700b357684fc15350da71033e70/doc/articles/feature-flags.md#giving-a-maximum-text-scaling-value

**Comment by jeanplevesque** [comment]
That's weird.
I would have expected the feature to be available on both platforms so that apps could set 1.5 for both iOS and Android (knowing that the scaling can be disabled completely, which is equivalent to capping at 1.0).

Also, the default value of 2.0 is a breaking change, right?
Previously, apps had no limit, and now scaling is capped at 2.0 by default, if I understand correctly?

**Comment by jeromelaban** [comment]
Yes, it's a breaking change, but true, it should be on Android as well.
