### ISSUE TITLE
ListView update fails with `Collection was modified` when using non-materialized `IEnumerable`

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#8509]
### Current behavior

I have a simple list:
` var moListPytania = new List<Pytanie>;`
then I'm using it to fill ListView:
`uiList.ItemsSource = moListPytania;`
or
`uiList.ItemsSource = from c in VBlib.MainPage.moListPytania select c'`

Within XAML DataTemplate
`<Slider Grid.Column="3" Value="{Binding iOdpowiedz, Mode=TwoWay}" Minimum="-2" Maximum="2" />`

And class for items is defined as:
`public class Pytanie
{
    public string sPytanie {get; set;}
    public int iOdpowiedz {get; set;}
    public bool bError {get; set;}
    public int iNumer {get; set;}
}`

Initially, list is presented correctly. In Uno.UWP, I can change slider value (dragging slider), and it works.
But when I try to change slider in Uno.Droid, I got exception:
`System.InvalidOperationException
  Message=Collection was modified; enumeration operation may not execute.`

### Expected behavior

App should work on Android, as it works on UWP.

### How to reproduce it (as minimally and precisely as possible)

See behaviour.

[Autyzm-master.zip](https://github.com/unoplatform/uno/files/8438473/Autyzm-master.zip)

### Workaround

None.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI 4.1.9

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

Version 17.0.5

**Comment by jeromelaban** [comment]
Thanks for the report. Please make sure to create a repro sample app so we can make sure we're talking about the same issue.

**Comment by pkar70** [comment]
Repro app: https://github.com/pkar70/Autyzm

**Comment by jeromelaban** [comment]
Thanks for the repro.

At this time, setting the ItemsSource using an `IEnumerable` is not well supported by Uno, and in general it's a best practice to provide a materialized enumerable (even with UWP). 

Try using `.ToArray()` to materialize your query.

**Comment by pkar70** [comment]
Still the same (i.e., using ToArray() doesn't make it works, still changing Slider cause exception).

**Comment by jeromelaban** [comment]
Thanks. In general, when posting exceptions, it's best to also have the full stack trace for quick diagnostics. Can you post that as well?

**Comment by pkar70** [comment]
Sorry, nothing useful.

Copy details says only:
System.InvalidOperationException
  Message=Collection was modified; enumeration operation may not execute.


![image](https://user-images.githubusercontent.com/23451507/162684687-d2ab6407-dfcf-4ec8-8878-0f2cd163fda8.png)

Last lines in output window:
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Shapes.Rectangle during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running sec04-11 09:16:46.935 W/View    ( 9971): requestLayout() improperly called by Windows.UI.Xaml.Shapes.Rectangle during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Shapes.Rectangle during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[View] requestLayout() improperly called by Windows.UI.Xaml.Controls.Grid during layout: running second layout pass
[EGL_emulation] eglMakeCurrent: 0x76387d5d5e00: ver 3 1 (tinfo 0x76387d55f460)
Loaded assembly: System.Threading.dll [External]
**System.InvalidOperationException:** 'Collection was modified; enumeration operation may not execute.'

**Comment by jeromelaban** [comment]
Right click on external code line, and check the "show external code" box.

**Comment by pkar70** [comment]
0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#
 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.Diagnostics/Debugger.cs:125,4	C#
 	0x33 in Android.Runtime.DynamicMethodNameCounter.120	C#
 	0xA in System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/throwhelper.cs:133,13	C#
 	0x13 in System.Collections.Generic.Dictionary<Windows.UI.Xaml.UIElement,Windows.UI.Xaml.UIElement.PointerCaptureTarget>.ValueCollection.Enumerator.MoveNext at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:1613,25	C#
 	0x3D in Uno.UI.Xaml.Core.RootVisual.ReleaseCaptures	C#
 	0x30 in Uno.UI.Xaml.Core.RootVisual.ProcessPointerUp	C#
 	0xE9 in Windows.UI.Xaml.UIElement.OnNativeMotionEvent	C#
 	0x94 in Windows.UI.Xaml.UIElement.OnNativeMotionEvent	C#
 	0x1E in Uno.UI.UnoViewGroup.n_OnNativeMotionEvent_Landroid_view_MotionEvent_Landroid_view_View_Z at C:\a\1\s\src\Uno.UI.BindingHelper.Android\obj\Release\monoandroid12.0\generated\src\Uno.UI.UnoViewGroup.cs:614,4	C#
 	0x23 in Android.Runtime.DynamicMethodNameCounter.120	C#
 	0xFFFFFFFFFFFFFFFF in Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_boolean_method_a	C#
 	0x79 in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualBooleanMethod	C#
 	0x65 in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualBooleanMethod	C#
 	0x38 in Android.Views.View.DispatchTouchEvent at /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-31/mcw/Android.Views.View.cs:17132,5	C#
 	0x14 in Windows.UI.Xaml.Controls.ListViewBase.DispatchTouchEvent	C#
 	0x11 in Android.Views.View.n_DispatchTouchEvent_Landroid_view_MotionEvent_ at /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-31/mcw/Android.Views.View.cs:17115,4	C#
 	0x17 in Android.Runtime.DynamicMethodNameCounter.130	C#
 	0xFFFFFFFFFFFFFFFF in Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_boolean_method_a	C#
 	0x79 in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualBooleanMethod	C#
 	0x65 in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualBooleanMethod	C#
 	0x38 in Android.App.Activity.DispatchTouchEvent at /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-31/mcw/Android.App.Activity.cs:1973,5	C#
 	0x37 in Uno.UI.BaseActivity.DispatchTouchEvent	C#
 	0x11 in Android.App.Activity.n_DispatchTouchEvent_Landroid_view_MotionEvent_ at /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-31/mcw/Android.App.Activity.cs:1957,4	C#
 	0x17 in Android.Runtime.DynamicMethodNameCounter.29	C#

**Comment by jeromelaban** [comment]
@dr1rrb Does it look familiar?

**Comment by pkar70** [comment]
Seems like under Uno 4.2.6 it works OK.
