### ISSUE TITLE
[Android] WebView doesn't display WebGL content

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#851]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)

## Current behavior

Reported in this StackOverflow question:
https://stackoverflow.com/questions/55966226/webgl-in-webview-does-not-work-in-uno-build-but-does-work-in-xamarin-build

When a page with WebGL content is viewed in the WebView, the WebGL content doesn't appear. (The rest of the page appears as normal.)

## Expected behavior

WebGL content works.

## Minimal reproduction of the problem with instructions

```xaml
<WebView Source="https://threejs.org/examples/?q=cube#webgl_geometry_cube" />
```

As diagnosed by the SO user, this occurs because in Uno [hardware acceleration is disabled](https://github.com/nventive/Uno/blob/eb1dc976117e5170d4e018f1137fd7aab2de09b0/src/Uno.UI/UI/Xaml/Controls/WebView/WebView.Android.cs#L255) on the WebView control (seemingly as a workaround for another bug). 

## Environment

Nuget Package: Uno.UI 

Package Version(s): 1.45.0-dev.1455

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
This bug has been fixed by PR #3392 the fix should be available in Uno.UI v3.0.0-dev.605
