### ISSUE TITLE
[WASM] ComboBox.ItemSource + ObservableCollection not working properly

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#8513]
### Current behavior

Please start attached on WASM:
- expand the ComboBox to see 'Item 1' and 'Item 2'
- press 'Add item' button a few times
- expand the ComboBox again to see that **empty** entries are added

This appears to be a race condition: sometimes it works, next time it doesn't. Also, changing the steps slightly coud make a positive/negative impact as well.

[ComboBoxItemSource.zip](https://github.com/unoplatform/uno/files/8442689/ComboBoxItemSource.zip)

### Expected behavior

Should work as WindowsAppSdk

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Latest official UNO bits on latest Chrome on Windows 11

**Comment by jeromelaban** [comment]
Thank for the report. This is something that was likely fixed in Uno 4.2, can you validate that it's the case?
