### ISSUE TITLE
[.NET6] Default template and VS2022 not playing nicely

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#8527]
### Current behavior

- create .NET6 solution with default template [as per here](https://platform.uno/docs/articles/get-started-winui3.html)
- edit solution using VS2022
- edit XXX.Shared/App.xaml add some random stuff + File -> Save All
- repeat step above until VS asks you for a file name (why?)
- repeat step above until VS asks you for a file name and refuses to overwrite existing App.xaml

There is appears to be some timer driven stuff going on. If you let VS sit for some minutes you may no longer run into that problem.

Note: repo not needed since you could reproduce with any new, random solution.

**Comment by jeromelaban** [comment]
Thanks for the report. This is unfortunately out of our hands, as it's visual studio's handling of XAML file which causes this. You can try opening an issue in Visual Studio's reporting tool.

**Comment by DierkDroth** [comment]
Thanks for clarification. Before reporting I tried to re produce with the pre-.NET6 UNO templates ... but failed. 

This made be believe it might be in UNO's hands...

**Comment by jeromelaban** [comment]
This has been fixed in Uno 4.2.6

**Comment by DierkDroth** [comment]
Thanks for letting me know @jeromelaban
