### ISSUE TITLE
[WASM] system theme are not detected on edge

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#8534]
### Current behavior

![image](https://user-images.githubusercontent.com/2359550/162811744-1a1dcc5a-1428-4020-a0d6-77de08378ea5.png)

### Expected behavior

^ should not happen.

### How to reproduce it (as minimally and precisely as possible)

[ElementTheme.zip](https://github.com/unoplatform/uno/files/8467007/ElementTheme.zip)
tl;dr:
```cs
public MainPage()
{
	this.InitializeComponent();
	this.Loaded += (s, e) =>
		Content = new TextBlock { Text = this.ActualTheme.ToString() };
}
```

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI.WebAssembly@4.1.8

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

Version 17.1.1

### Relevant plugins

n/a

**Comment by jeromelaban** [comment]
Which version of edge is this? It's been working properly for a while. Does it fail when you change the theme explicitly in the browser's settings ?

**Comment by MartinZikmund** [comment]
As @jeromelaban mentions, it seems you have explicitly set Edge to light theme in settings - the browser then gives precedence to the browser theme over the OS theme - 

![image](https://user-images.githubusercontent.com/1075116/162934398-a1ed3a9d-a0b3-4633-ad5d-92ca1ec52dff.png)

**Comment by lukeblevins** [comment]
@MartinZikmund I recall noticing that launching Uno WASM apps for debug in Edge (from VS) overrides my browser theme to Light from the OS adaptive option. Wondering if this is some hardcoded assumption not specific to Uno. I'm also trying to remember if the theme preference correctly persists changes after, say, relaunching the web project to create a fresh instance of Edge.
