### ISSUE TITLE
Default template raises missing `DefaultRepeatButtonStyle` missing and missing `BorderThickness` on `RootVisual`.

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#8540]
### Current behavior

See the error in https://github.com/unoplatform/uno/discussions/8539#discussion-4003955.

> warn: Uno.UI.ResourceResolver[0] Couldn't statically resolve resource DefaultRepeatButtonStyle
> warn: Windows.UI.Xaml.UIElement[0] The BorderThicknessProperty dependency property does not exist on Uno.UI.Xaml.Core.RootVisual

### Expected behavior

No style related warnings.

### Workaround

None.

### NuGet package version(s)

4.2-dev.400

**Comment by Xiaoy312** [comment]
note: warning about DefaultRepeatButtonStyle no longer appears since updated to 4.2.0-dev.605
