### ISSUE TITLE
[Skia.GTK] new template app doesn't show anything on launch when updated to latest

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#8543]
### Current behavior

using: [Uno.ProjectTemplates.Dotnet::4.1.8](https://www.nuget.org/packages/Uno.ProjectTemplates.Dotnet/4.1.8)
create the app from template: dotnet new unoapp -n PROJECT_NAME
update packages to the latest:
![image](https://user-images.githubusercontent.com/2359550/162996019-6f7577c2-19ac-4a29-8a5d-f563f60bc3a8.png)
launch the app on Skia.GTK:
get a white blank screen (even on dark mode)
> on rare occasion, we can briefly see the MainPage content displayed correctly (in dark mode) for a fraction of second before disappearing:
> ![20220412 skia gtk whitescreen](https://user-images.githubusercontent.com/2359550/163000770-7917223c-6b3c-4cd8-8dce-0bac7ad0e1cb.gif)

### Expected behavior

^ should just work

### How to reproduce it (as minimally and precisely as possible)

[WasmErrors8540.zip](https://github.com/unoplatform/uno/files/8474229/WasmErrors8540.zip)
launch Skia.Gtk head

### Workaround
use software rendering:
```cs
// in PROJECT_NAME.Skia.Gtk\Program.cs
var host = new GtkHost(() => new App(), args) { RenderSurfaceType = RenderSurfaceType.Software };
```

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI.Skia.Gtk@4.2.0-dev.605

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

Version 17.1.1

### Relevant plugins

n/a

### Anything else we need to know?

other related platforms, like skia.wpf or wasm, work fine

---

there is nothing special in the log output either:
<details>
<summary>console log</summary>

```
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 169.254.71.45.
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint [fe80::c003:b023:9e52:1637].
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 169.254.22.55.
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint [fe80::64a3:aef0:8f4a:6298].
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 169.254.98.152.
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint [fe80::6417:b33:af8:484d].
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 10.0.0.143.
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get any remote control server endpoint from the IDE.
warn: Windows.UI.Xaml.UIElement[0]
      The BorderThicknessProperty dependency property does not exist on Uno.UI.Xaml.Core.RootVisual
fail: Windows.UI.Composition.CompositionObject[0]
      The member void CompositionObject.Dispose() is not implemented in Uno.
```
</details>

not sure if related or not, one `warn`ing that used to be in 4.1.8 is not there anymore:
<details>
<summary>warn: Uno.UI.ResourceResolver[0] Couldn't statically resolve resource DefaultRepeatButtonStyle</summary>

```diff
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 169.254.71.45.
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint [fe80::c003:b023:9e52:1637].
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 169.254.22.55.
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint [fe80::64a3:aef0:8f4a:6298].
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 169.254.98.152.
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint [fe80::6417:b33:af8:484d].
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 10.0.0.143.
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get any remote control server endpoint from the IDE.
-warn: Uno.UI.ResourceResolver[0]
-      Couldn't statically resolve resource DefaultRepeatButtonStyle
warn: Windows.UI.Xaml.UIElement[0]
      The BorderThicknessProperty dependency property does not exist on Uno.UI.Xaml.Core.RootVisual
fail: Windows.UI.Composition.CompositionObject[0]
      The member void CompositionObject.Dispose() is not implemented in Uno.
```
</details>

**Comment by jeromelaban** [comment]
Try setting the GtkHost RenderMode to Software for now. There may be another issue which is OpenGL related.

**Comment by Thorocaine** [comment]
I have just decided to give Uno a try, but I am getting this problem, on Manjaro if that makes a difference.

I get a series of fail: Uno.UI.RemoteControl.RemoteControlClient[0]
followed by
free(): invalid pointer
Process finished with exit code 134.

A run dotnet new and create an unoapp, then I cd into the Ski.GTK directory, and try dotnet run.
I tried setting software rendering as suggested above, but it made no difference.

dotnet version is 6.0.108
I am not sure if there is any other info that could be useful.

**Comment by Thorocaine** [comment]
Only output is 

```
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 192.168.0.115.
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint [fe80::1714:8bf4:6b42:6af7].
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 172.21.0.1.
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint [fe80::42:9fff:fec8:f738].
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint 172.17.0.1.
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get remote control server port from the IDE for endpoint [fe80::cc89:d2ff:feaa:9fbe].
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to get any remote control server endpoint from the IDE.
```

**Comment by jeromelaban** [comment]
This is pretty close to this discussion: https://github.com/unoplatform/uno/discussions/9354. We do not yet know what the issue is on these distributions.

**Comment by jeromelaban** [comment]
Could you also try the workaround I [just posted here](https://github.com/unoplatform/uno/discussions/9354#discussioncomment-3789925)?
