### ISSUE TITLE
Page.DataContext / Page.Content are not parsed properly

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#856]
## I'm submitting a...
- Bug report

## Current behavior
The `Page.Content` and `Page.DataContext` property are not handled properly by XAML generator. Values are ignored and does not appear in the generated C#.

## Expected behavior
It works!

## Minimal reproduction of the problem with instructions
Create a page an put this:
```xaml
<Page>
   <Page.DataContext>
      <local:ViewModel />
   </Page.DataContext>

   <Page.Content>
      <TextBlock Text="{Binding}" />
   </Page.Content>
</Page>
```

## Work-around
Set the  `DataContext` in the code behind
```csharp
public MyPage()
{
    this.InitializeComponent();

	DataContext = new ViewModel();
}
```
and remove the `Page.Content` tag
```xaml
<Page>
   <TextBlock Text="{Binding}" />
</Page>
```

## Environment

Nuget Package: Uno.UI
Package Version(s): 1.45.0-dev.1450

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio: _irrelevant_
Relevant plugins: _none_

**Comment by carldebilly** [comment]
Fixed by PR #1356
