### ISSUE TITLE
[wasm] Support for resx and satellite assemblies

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#8560]
## What would you like to be added:

Support for resx and satellite assemblies for localization.

## Why is this needed:
The ability to use localization for libraries which provide standard .NET localization and don't use WinRT's `ResourceLoader`.

**Comment by jeromelaban** [comment]
This feature is now available in the 4.0-dev builds of Uno.Wasm.Bootstrap.

**Comment by KWodarczyk** [comment]
@jeromelaban  can documentation for .resx be updated please https://platform.uno/docs/articles/external/uno.extensions/doc/Overview/Localization/LocalizationOverview.html

Also it would be nice to have option "Improve Docs" so we can just put a comment if something is missing.
