### ISSUE TITLE
Windows 10 SDK (10.0.18362.0) is required to build uno

### ISSUE THREAD

**Issue by beto-rodriguez** [unoplatform/uno#8568]
## On which page?

https://platform.uno/docs/articles/get-started-vs.html

## What's wrong?

Now on VS 2022 preview 3, when you select the Universal Windows Platform development workload it installs Windows 10 SDK (10.0.190231.0) by default (Maybe because I am using Windows 11?), I realized I needed to explicitly install 10.0.18362.0 version to compile Uno.
 
![image](https://user-images.githubusercontent.com/10853349/163916668-2a553cfe-aa1b-456b-870c-487183d293b1.png)

**Comment by jeromelaban** [comment]
Thanks for the report. In theory, visual studio is supposed to ask you to install that specific version of the windows SDK, through this: https://github.com/unoplatform/uno/blob/919cd95b5a21c1390b705fb5d53519ed1a3bfa49/src/SolutionTemplate/UnoSolutionTemplate.Wizard/.vsconfig.vs17#L72. 

Did you create a project or a library?

**Comment by beto-rodriguez** [comment]
It was a library, I remember VS let me know through a dialog at top that I required extra things to be installed, but as far as I remember they were not installed even when I accepted the dialog.

Additionally I was also missing a workload, but I tried a `dotnet restore` and it suggested me the the workload I had to install.

**Comment by beto-rodriguez** [comment]
Now I tried to create a Uno project and it seems that it worked, it installed a lot of missing stuff, I guess this was my bad.

**Comment by jeromelaban** [comment]
That's actually a good insight, thanks! We do not add a `.vsconfig` for library project, mainly because it's generally added as part of the development flow where an app is created first, then a library.
