### ISSUE TITLE
Red and blue channels are inverted with Skia.Gtk on M1-based Macs

### ISSUE THREAD

**Issue by spouliot** [unoplatform/uno#8580]
### Current behavior

When using Skia.Gtk on a M1-based Mac computer the red and blue channels are inverted.

Note: I have not tried this on other platforms. It might not be limited to M1/arm64 based macs.

![Screen Shot 2022-04-20 at 2 49 32 PM](https://user-images.githubusercontent.com/260465/164301822-5cff7e9d-ff1e-4e53-a361-4576b3d6129f.png)

In the above image the orange UI elements should be blue.

### Expected behavior

The expected colours should be seen.

### How to reproduce it (as minimally and precisely as possible)

Build and run SampleApps.Sika.Gtk.csproj on a M1 Mac.

### Workaround

It seems `SKImageInfo.PlatformColorType` is returning `Rgba8888`, as documented. However it does not seems to reflect what's required.

Hardcoding this to `SKColorType.Bgra8888` _solves_ the problem.

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

git revision 919cd95b5a21c1390b705fb5d53519ed1a3bfa49
and SkiaSharp 2.88.0-preview.254 for macOS/arm64 support

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio Code

### Anything else we need to know?

# Requires SkiaSharp 2.88+

The current stable Uno (4.1.9) does not ship a working libSkiaSharp version (2.80.3) for arm64 macs.

In order to have an arm64 slice in the native library a newer, pre-release version of SkiaSharp, 2.88.x, must be used.

See https://github.com/unoplatform/uno/issues/8296 for more details.

# Diff

The following change _fix_ the issue - at least on M1-based macs, but it might break it elsewhere. I'm not _yet_ sure if this is a know issue in Skia[Sharp] / m88 bug wrt `SKImageInfo.PlatformColorType`.

```diff
diff --git a/src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs b/src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs
index 385442c3a..04dea8a3d 100644
--- a/src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs
+++ b/src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs
@@ -75,12 +75,13 @@ namespace Uno.UI.Runtime.Skia
                        var scaledWidth = (int)(width * _dpi.Value);
                        var scaledHeight = (int)(height * _dpi.Value);

-                       var info = new SKImageInfo(scaledWidth, scaledHeight, SKImageInfo.PlatformColorType, SKAlphaType.Premul);
+                       SKColorType platform = SKColorType.Bgra8888;
+                       var info = new SKImageInfo(scaledWidth, scaledHeight, platform, SKAlphaType.Premul);

                        // reset the bitmap if the size has changed
                        if (bitmap == null || info.Width != bitmap.Width || info.Height != bitmap.Height)
                        {
-                               bitmap = new SKBitmap(scaledWidth, scaledHeight, SKColorType.Rgba8888, SKAlphaType.Premul);
+                               bitmap = new SKBitmap(scaledWidth, scaledHeight, platform, SKAlphaType.Premul);
                        }

                        using (var surface = SKSurface.Create(info, bitmap.GetPixels(out _)))
```

**Comment by spouliot** [comment]
I've saved PNG for each `SKSurface` on every `OnDraw` calls and they show up as expected (blue, not orange). So I don't believe it's an internal issue inside Skia[Sharp].

It also seems that `SKImageInfo.PlatformColorType` (natively `kN32_SkColorType`) might not be a trustable value, ref: https://groups.google.com/g/skia-discuss/c/cwiiYr7eL7s?pli=1

I'm not sure a Skia fix can be expected _soonish_ (or ever) so I'll propose doing a PR that check explicitly for this condition and, when needed, set the correct SKColorType for macOS/arm64.

**Comment by jeromelaban** [comment]
Interesting pieces of information! Indeed, adjusting for now using the current platform will do until we get some proper update. Thanks!

**Comment by spouliot** [comment]
Also this only happens on `RenderSurfaceType.Software` (where the _fix_ is located). Running the sample with `RenderSurfaceType.OpenGL` is fine (at least color wise, not sure what else was be broken wrt https://github.com/unoplatform/uno/commit/487cc9e74b17f14e381df49b3ec9880b2f1cb31b).

**Comment by jeromelaban** [comment]
Are you able to run with OpenGL on mac? On my machines (x64 ones) the surface is stretched in very weird ways by Gtk, which is why it's currently disabled.

**Comment by spouliot** [comment]
I did not notice anything wrong on my M1 when I tried, but I did not know what to look for :)

I'll try again with the openGL renderer...

**Comment by spouliot** [comment]
@jeromelaban it looks good to me!

![Screen Shot 2022-04-25 at 10 35 56 AM](https://user-images.githubusercontent.com/260465/165111549-e84ff0ec-c537-4d5f-b0f5-b180e110d487.png)
![Screen Shot 2022-04-25 at 10 32 27 AM](https://user-images.githubusercontent.com/260465/165111561-429cd59f-8c37-4ed8-bd98-dfd3f82ded44.png)

Anything else I should look at ?

**Comment by jeromelaban** [comment]
Nice!! Are you able to resize the window? There's where it failed for me.

**Comment by spouliot** [comment]
That's less cute :(

![Screen Shot 2022-04-25 at 10 47 23 AM](https://user-images.githubusercontent.com/260465/165113867-e8ca5caf-5ba5-4913-9010-1e9f805ca532.png)

**Comment by jeromelaban** [comment]
Indeed! I've tried rebuilding the [GLArea manually](https://github.com/jeromelaban/uno/commit/3a73a7947fa39314060b0121466b638f428d75a6) to ease the troubleshooting, but I could not find a spot where the cairo blitting is done incorrectly for macOS.

**Comment by spouliot** [comment]
@jeromelaban I had a look, down to gtk+3 code, and have not found the issue :-(

It's clearly not an uno issue since skipping the `Render` call and drawing on the `SKSurface` behave identically. Still I have not been able to reproduce it with other Gtk samples.

Was there an open issue for this ? (since it's not really related to the original issue).

Also what's the best way to check for rendering performance ? I made a few changes/optimizations on the `SoftwareRenderSurface` that I'd like to compare to the existing code. Thanks!

**Comment by jeromelaban** [comment]
Thanks for taking a look! At this time, I don't know where to open an issue to be honest, even it if indeed feels like a Gtk+3 issue. Which samples did you try with Gtk?

As for testing the rendering performance, there's either this log:
https://github.com/unoplatform/uno/blob/da4338ddc48e0204f0badcb32bdd9ba375a91938/src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs#L110
or by using the samples app: https://github.com/unoplatform/uno/blob/650832ee5ff9da8856a818cc52b0ac821e76ac28/src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Performance/Performance_Dopes.xaml.cs#L27 (the Change test). The name in the current app is incorrect, https://github.com/unoplatform/uno/pull/8638 fixes it.

**Comment by spouliot** [comment]
It reproduce with a GtkSharp sample using a `GLArea` widget. The resizing is correct until the `GLArea` is displayed. Changing the view to another widget does not bring back the correct behaviour.

I basically copied `https://github.com/GtkSharp/GtkSharp/blob/develop/Source/Samples/Sections/Widgets/DrawingAreaSection.cs` and replaced `DrawingArea` with `GLArea`.

The native GTK sample https://github.com/ebassi/glarea-example also has the same resizing problem, so it's not a GtkSharp (e.g. incorrect bindings) issue.

It also seems to affect other people as well -> https://github.com/pemsley/coot/issues/33#issuecomment-1030825807 (long thread, still reading it)

**Comment by jeromelaban** [comment]
Interesting, thanks for the research! This means we'll likely need to do our own GL rendering over Gtk to fix this, or maybe move to Gtk4 when that becomes available.

**Comment by spouliot** [comment]
> This means we'll likely need to do our own GL rendering over Gtk to fix this

Yes, that approach should work everywhere Gtk and GL are supported.

> move to Gtk4 when that becomes available.

It's [available](https://formulae.brew.sh/formula/gtk4#default) but AFAIK there's no _complete_ GtkSharp support yet and there were mentions, in the gnome bug report, that the same/similar issues might exist in Gtk+4 (not tried).

I'm not expecting Apple to invest much in OpenGL. I might be wrong again since I did not expect OpenGL to be available _at all_ on arm64 😄

I also do not think macOS will ever be a top priority for Gtk, at least for things like GL (for same reasons as above wrt Apple). OTOH updating to Gtk+4 might bring other advantages.

An alternative approach would be to use a metal backend for macOS/Gtk. Skia supports Metal surfaces, but IIRC SkiaSharp does not expose the metal API in every platform.

Finally there's the software renderer... and the real (non Gtk) macOS backend.

**Comment by jeromelaban** [comment]
There's also the Vulkan renderer which SkiaSharp supports. Maybe we could try this route, though even there's some Vulkan support in Gtk, it's not exposed though GtkSharp.

**Comment by spouliot** [comment]
Good idea! It would require macOS users to download/install the extra [MoltenVK](https://github.com/KhronosGroup/MoltenVK/) but considering you already need other dependencies, like Gtk itself, it might not be a big issue.
