### ISSUE TITLE
[macOS] ScrollViewer do not work

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#8596]
### Current behavior

https://user-images.githubusercontent.com/12531229/164728911-6dd0deb4-7261-4353-adbe-ec398288ca69.mov

### How to reproduce it (as minimally and precisely as possible)

- edit crosstargeting_override.props and set UnoTargetFrameworkOverride to xamarinmac20
- open Uno.UI-vs4mac-macOS-only.sln
- run SamplesApp.macOS
- try Scroll

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

macOS

### IDE

Visual Studio for Mac

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
