### ISSUE TITLE
Seems like Slider.Background doesn't work

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#8611]
### Current behavior

I have:
`<Slider Grid.Column="3" Value="{Binding iOdpowiedz, Mode=TwoWay}" Minimum="-2" Maximum="2" SmallChange="1" Opacity="{Binding Value, RelativeSource={RelativeSource Self}, Converter={StaticResource KonwersjaWarningOpacity}}" Background="{Binding Value, RelativeSource={RelativeSource Self}, Converter={StaticResource KonwersjaWarningBrush}}" />`

It works under UWP head, but not under Android head.

Windows:
![ekranWinUIstd](https://user-images.githubusercontent.com/23451507/165084490-9f86f1d7-b3bb-4f79-b17a-f6b0013bc33d.jpg)

Android:
![ekranAndro](https://user-images.githubusercontent.com/23451507/165085225-c1a65ec8-d3ff-4073-8fa7-a164e6165744.jpg)

### Expected behavior

Same effect on all platforms.

### How to reproduce it (as minimally and precisely as possible)

In XAML:
```
    <UserControl.Resources>
        <local:KonwersjaWarningBrush x:Key="KonwersjaWarningBrush"/>
        <local:KonwersjaWarningOpacity x:Key="KonwersjaWarningOpacity"/>
        <local:KonwersjaVisibility x:Key="KonwersjaVisibility" />
    </UserControl.Resources>
(...)
<Slider Minimum="-2" Maximum="2" SmallChange="1" Opacity="{Binding Value, RelativeSource={RelativeSource Self}, Converter={StaticResource KonwersjaWarningOpacity}}" Background="{Binding Value, RelativeSource={RelativeSource Self}, Converter={StaticResource KonwersjaWarningBrush}}" />
```

in *cs:
```
    public partial class KonwersjaWarningBrush : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, string language)
        {
            // wejście: value = wartość Slidera
            // SettingsBool("initialMode")
            // zwraca:  Background

            int iVal = System.Convert.ToInt32(value);

            if (iVal == 0 )
                return new SolidColorBrush(Windows.UI.Colors.OrangeRed);

            return new SolidColorBrush(Windows.UI.Colors.Gray);
        }

        // ConvertBack is not implemented for a OneWay binding.
        public object ConvertBack(object value, Type targetType, object parameter, string language)
        {
            throw new NotImplementedException();
        }
    }

    public partial class KonwersjaWarningOpacity : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, string language)
        {
            // wejście: value = wartość Slidera
            // SettingsBool("initialMode")
            // zwraca:  Opacity

            int iVal = System.Convert.ToInt32(value);

            if (iVal == 0 )
                return 0.5;

            return 1;
        }

        // ConvertBack is not implemented for a OneWay binding.
        public object ConvertBack(object value, Type targetType, object parameter, string language)
        {
            throw new NotImplementedException();
        }
    }

```

### Workaround

None.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI 4.2.6

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.0.5

### Anything else we need to know?

This is part of my app:
https://github.com/pkar70/Autyz

m

**Comment by MartinZikmund** [comment]
This should be fixed when Slider is ported from WinUI (soon), will assign to myself for now
