### ISSUE TITLE
Android GetFileFromApplicationUriAsync doesn't work

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#8618]
### Current behavior

Exception `**Java.IO.FileNotFoundException:**` is thrown.

### Expected behavior

File should be 'openable'.

### How to reproduce it (as minimally and precisely as possible)

```
            Uri oPicUri = new Uri("ms-appx:///Assets/1950.gif");
            Windows.Storage.StorageFile oFile;
            try
            {  
                oFile = await Windows.Storage.StorageFile.GetFileFromApplicationUriAsync(oPicUri);
            }
            catch
            {
                return false;
            }
```
Exception: `**Java.IO.FileNotFoundException:** 'Assets/__1950.gif'`

Part of: https://github.com/pkar70/KrakTram

GIF files are present, e.g. X\KrakTram\KrakTram_Uno\KrakTram_Uno.Shared\Assets\1950.gif
On build, they are copied to X\KrakTram\KrakTram_Uno\KrakTram_Uno.Droid\obj\Debug\120\res\drawable-nodpi\__1950.gif

### Workaround

None known.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

UnoUI 4.2.6

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.0.5

**Comment by jeromelaban** [comment]
Make sure to validate first with this sample application: https://github.com/unoplatform/Uno.Samples/tree/master/UI/PackageResources

**Comment by pkar70** [comment]
Sample has no files in Assets folder, so it is not related.
Android head should work same as UWP head, and UWP head works.

**Comment by jeromelaban** [comment]
Thanks. This is likely this [Visual Studio issue](https://github.com/unoplatform/uno/discussions/5007#discussioncomment-2583741), as this has been working in Uno for a while. Apply the workaround, and make sure to [upvote the VS issue](https://developercommunity.visualstudio.com/t/HasSharedItems-is-explicitly-set-to-em/10016046) so it gets fixed.

**Comment by iury-kc** [comment]
That seams to be the same problem the unit tests for PR [https://github.com/unoplatform/uno/pull/8370](https://github.com/unoplatform/uno/pull/8370 )
The PR itself is ok, correcting the issues #5453 and #7288. The tests passed only on iOS / macOS and the reason why is the GetFileFromApplicationUriAsync not loading Assets.

**Comment by pkar70** [comment]
One more check: files are present in .apk file:
X\KrakTram\KrakTram_Uno\KrakTram_Uno.Droid\bin\Debug\pkar.KrakTram.apk\res\drawable-nodpi-v4\__1950.gif

**Comment by jeromelaban** [comment]
@pkar70 did you try with the workaround? Does it change anything?

**Comment by pkar70** [comment]
No...
a) I have no VS 2022 Preview
b) files ARE in apk
c) after Android R, accessing resources is changed (see below)
d) I would test some things by debugging :)

(After [Build.VERSION_CODES#R](https://developer.android.com/reference/android/os/Build.VERSION_CODES#R), [Resources](https://developer.android.com/reference/android/content/res/Resources) must be obtained by [Activity](https://developer.android.com/reference/android/app/Activity) or [Context](https://developer.android.com/reference/android/content/Context) created with [Context.createWindowContext(int, Bundle)](https://developer.android.com/reference/android/content/Context#createWindowContext(int,%20android.os.Bundle)). [Application#getResources()](https://developer.android.com/reference/android/content/ContextWrapper#getResources()) may report wrong values in multi-window or on secondary displays.

**Comment by jeromelaban** [comment]
Thanks. Files are in the APK but with an invalid path / file name, which points to a similar shared project related issue.

**Comment by jeromelaban** [comment]
This reminds me that files are not handled the same way as other file types. If you want images to be read by `GetFileFromApplicationUriAsync`, you need to include them as `AndroidResource`  not `AndroidAsset`. This is not something we'll be able to change, as android mangles the file names when included with nesting.

**Comment by pkar70** [comment]
I have workaround...

1) copy files from Uno\Shared\Assets\ folder to Uno\Droid\Assets folder 
 This step is required, as files in Uno\Shared\Assets\ are placed in res folder, without directory tree.

2) use this as Android replacement for `GetFileFromApplicationUri()`:

```
        private async System.Threading.Tasks.Task<Windows.Storage.StorageFile> AndroidGetFileFromApplicationUri(Uri uri)
        {
            // "ms-appx:///Assets/" + iRok + ".gif"
            // "__" + iRok + ".gif" w pkar.KrakTram.apk\res\drawable-nodpi-v4\

            if (uri.Scheme != "ms-appx")
            { // we don't handle "ms-appdata://" prefix (app root folder inside user) - limit of this implementation
                throw new InvalidOperationException("Uri is not using the ms-appx scheme");
            }

            string sFilename = uri.ToString();

            if (!sFilename.StartsWith("ms-appx:///Assets/"))
            { // limit of this implementation
                throw new InvalidOperationException("Uri is not ms-appx:///Assets/");
            }

            sFilename = sFilename.Substring("ms-appx:///Assets/".Length);

            var assetMan = Android.App.Application.Context.Assets;
            if (assetMan is null)
            {
                throw new InvalidOperationException("Cannot get AssetManager");
            }

            var outputCachePath = System.IO.Path.Combine(Android.App.Application.Context.CacheDir.AbsolutePath, sFilename);

            if (!System.IO.File.Exists(outputCachePath))
            {
                System.IO.Directory.CreateDirectory(System.IO.Path.GetDirectoryName(outputCachePath));

                using System.IO.Stream fileInApk = assetMan.Open(sFilename);
                using var output = System.IO.File.OpenWrite(outputCachePath);

                await fileInApk.CopyToAsync(output);
            }

            return await Windows.Storage.StorageFile.GetFileFromPathAsync(outputCachePath);
        }
```

**Comment by pkar70** [comment]
I don't know WHAT places files from Shared\Assets to Droid\res, and how to prevent it.

**Comment by pkar70** [comment]
So, if I add this `AndroidAsset` to `csproj` in Uno.Droid, files from `Uno.Shared\Assets` would be visible inside `apk` under `assets` folder?

**Comment by iury-kc** [comment]
Hummmm
Following the outputCachePath var, I did a shot in the dark, changing the value of PATH in:

https://github.com/unoplatform/uno/blob/da4338ddc48e0204f0badcb32bdd9ba375a91938/src/Uno.UWP/Storage/StorageFile.android.cs#L54

from 'Assets/myfile.jpeg' to only 'myfile.jpeg'  and "voilà"! Android could load perfectly the image. 

I don't know why path has the 'Assets/' since we are using outputCachePath as well.

@jeromelaban

**Comment by jeromelaban** [comment]
@iury-kc yes, that's what it's supposed to be doing somehow, but the problem is the handling of conflicts in file names. We've been trying to adjust this for a while (https://github.com/unoplatform/uno/pull/7328) but it's quite tricky.

**Comment by pkar70** [comment]
But what if I have such structure:
Assets
+- Digital
| +- 10.png
|  +- 20.png
+- Analog
| +- 10.png
|  +- 20.png

similar to https://github.com/pkar70/ZegarSloneczny/tree/master/ZegarSloneczny/pic

'Flattening' dirtree is bad.

**Comment by jeromelaban** [comment]
Flattening is what android does with resources, it's not something we can change. Assets don't have that problem, when using `AndroidAsset` solution I provided above.

**Comment by pkar70** [comment]
Still..
I have UWP app with pictures inside Assets, and GetFileFromApplicationUriAsync() doesn't work for this.
```
            Uri oPicUri = new Uri("ms-appx:///Assets/" + iRok + ".gif");
            Windows.Storage.StorageFile oFile;
            oFile = await Windows.Storage.StorageFile.GetFileFromApplicationUriAsync(oPicUri);
            Windows.UI.Xaml.Media.Imaging.BitmapImage oBmp = new Windows.UI.Xaml.Media.Imaging.BitmapImage();
            oBmp.UriSource = oPicUri;
```

And I cannot use such code for Android.
Because build moves files from Uno.Shared\Assets to \res, and GetFileFromApplicationUriAsync throws exception that file is not found.

I can replace this code with "special code for Android", but code should work correctly (or show Uno0001 warning that it is unimplemented). Maybe, in this case, there should be e.g. "Uno0002 Limited implementation for Android, works only for non-picture files, and only for ms-appx (not ms-appdata)" ? And same in all other places where Uno's implementation is somehow limited (e.g., because target platform has limits).

**Comment by jeromelaban** [comment]
Can you add a simple repro for your scenario here please (not one from your github) ? We'll make modifications to it and see what's needed.

**Comment by jeromelaban** [comment]
This is what I mean adding a simple repro: [Test8618.zip](https://github.com/unoplatform/uno/files/8575460/Test8618.zip).

The workaround for this is to add the following to the android project:
```xml
  <ItemGroup>
    <AndroidAsset Include=".\Test8618.Shared\Assets\**" Link="Assets\Assets\%(RecursiveDir)\%(FileName)%(Extension)" />
  </ItemGroup>
```
Take a look at the repro to see it in action.

**Comment by pkar70** [comment]
Thanks. In next app version, I will use this.
