### ISSUE TITLE
Microsoft.UI.Xaml.Controls.TimePicker.Header is not implemented in Uno  

### ISSUE THREAD

**Issue by cesarchefinho** [unoplatform/uno#8631]
### Current behavior

Not work in webassembly, works on all other platforms

### Expected behavior

Show Header above control

### Workaround

Not possible because i am using an library that expects Header property of control

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

uno 4.2.6

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
TimePicker is not implemented in Uno yet, see https://github.com/unoplatform/uno/issues/5553
