### ISSUE TITLE
Microsoft.UI.Xaml.Controls.TimePicker.TimeProperty is not implemented in Uno

### ISSUE THREAD

**Issue by cesarchefinho** [unoplatform/uno#8632]
### Current behavior

Not working on webassembly, all other platforms works

### Expected behavior

read timestamp from timepicker

### Workaround

none because this property is used by an third party library for twoway binding pourposes

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

uno 4.2.6

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. `TimePicker` is not implemented in Uno yet, see https://github.com/unoplatform/uno/issues/5553
