### ISSUE TITLE
Microsoft.UI.Xaml.FrameworkElement.NameProperty is not implemented in Uno

### ISSUE THREAD

**Issue by cesarchefinho** [unoplatform/uno#8633]
### Current behavior

not working on webassembly, all other platforms works

### Expected behavior

the name of the type of control in controll tree

I use this to locate the textbox in autosuggestbox control in an bidding library.

working on all plataforms, but not on webassembly

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.2.6

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
`NameProperty` is implemented in all platforms. Can you provide a specific repro for this issue? Thanks!

**Comment by cesarchefinho** [comment]
// this is the code that VS2022 warns when build webasselbly project of solution
// other platforms dont emit this wharning 

// 2> Extension.cs (1085,40,1085,69): warning Uno0001: Microsoft.UI.Xaml.FrameworkElement.NameProperty is not implemented in Uno

  private static T FindChildAutoSuggestBox<T>(DependencyObject parent)
    {
            for (int i = 0; i < VisualTreeHelper.GetChildrenCount(parent); i++)
            {
                var child = VisualTreeHelper.GetChild(parent, i);
        
                if (child is T typedChild)
                {
                    if (child.GetValue(FrameworkElement.NameProperty).ToString() == "TextBox")
                    {
                        return typedChild;
                    }
                }
        
                T inner = FindChildAutoSuggestBox<T>(child);
        
                if (inner != null)
                {
                    return inner;
                }
            }

            return default;
    }

**Comment by jeromelaban** [comment]
Thanks. It's likely that it is only a invalid warning. Does the code work?

**Comment by cesarchefinho** [comment]
on windows and on Android yes this code works ok

Webasm is crashing at startup, I will investigate more
