### ISSUE TITLE
[Android] FlipView control not displayed correctly or is missing 

### ISSUE THREAD

**Issue by Guidemarcus** [unoplatform/uno#8637]
### Current behavior

Each section/page of the control seems too big for the allocated space.

### Expected behavior

Each section should be displayed properly.

### How to reproduce it (as minimally and precisely as possible)

In this repo https://github.com/nventive/Nventive.View, it is possible to checkout dev/math/SampleImageSlideShow

otherwise, only using this
```xml
<Page.Resources>
		<DataTemplate x:Key="OnboardingItemTemplate">
			<Grid Margin="20,0"
				  Background="Red">
				<TextBlock Text="{Binding}"
						   Grid.Row="1"
						   Width="300"
						   Margin="0,8"
						   VerticalAlignment="Center"
						   HorizontalTextAlignment="Center"
						   HorizontalAlignment="Center" />
			</Grid>
		</DataTemplate>
	</Page.Resources>

<Grid toolkit:VisibleBoundsPadding.PaddingMask="Top">
		<FlipView x:Name="PART_FlipView"
				  ItemsSource="123"
				  ItemTemplate="{StaticResource OnboardingItemTemplate}" />
	</Grid>
```
### Workaround

none found

### Works on UWP/WinUI

Yes

### NuGet package version(s)

    <PackageReference Include="Uno.UI" Version="4.2.6" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="4.2.6" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.2.6" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Uno.Extensions.Logging.OSLog " Version="1.0.1" />

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.1.3

### Anything else we need to know?

It was working fine on uno.ui 4.1.9

**Comment by Guidemarcus** [comment]
@jeromelaban @ajpinedam Yes! same thing with FlipView. I guess this is the real source of the issue.

**Comment by Guidemarcus** [comment]
Set it to urgent because we would need it ASAP for the interns and new employee coming soon

**Comment by jeromelaban** [comment]
Can you post a screenshot of the issue, it'll be easier to triage. Thanks!

**Comment by Guidemarcus** [comment]
https://user-images.githubusercontent.com/17101674/165624671-c9244347-ffd4-462d-8da5-ec2f00378e88.mp4

**Comment by ajpinedam** [comment]
Thanks @Guidemarcus . I will check this out and update you.

cc:  @jeromelaban

**Comment by ajpinedam** [comment]
Pushed PR with the fix.

https://user-images.githubusercontent.com/1900897/181606559-1cfde1c0-dbd4-49fb-95c6-b6651e19d773.mp4
