### ISSUE TITLE
[WASM] Not working on Firefox

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#8640]
### Current behavior

It seems many things are not working on Firefox, for example the current playground.uno

### Expected behavior

Should work. 

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by dr1rrb** [comment]
The release version of the playground is working on my side. Is-it with latest dev? Do you have more info of what is not working?

**Comment by MartinZikmund** [comment]
I can confirm it works now. It is possible that the issues were caused by bad network connection. I can't repro anymore so let's close it for now
