### ISSUE TITLE
Code snippets not displaying in Gallery

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#8642]
### Current behavior

<img width="676" alt="image" src="https://user-images.githubusercontent.com/1075116/165753597-c92396a6-bf42-4340-9098-5a106c940f54.png">

Using https://gallery.platform.uno/

### Expected behavior

Should display code snippets.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly

**Comment by agneszitte-nventive** [comment]
Closing this bug at this is not happening anymore.
@sakshi173 feel free to re-open the bug if you notice the bug again.
(cc @jeromelaban)

**Comment by sakshi173** [comment]
Thanks @agneszitte-nventive , Yes this bug is not happening anymore, closing it.
