### ISSUE TITLE
wasm: KeyDown event does not work for Up/Down arrow keys

### ISSUE THREAD

**Issue by yowl** [unoplatform/uno#866]
## I'm submitting a...

 - Feature request 

## Current behavior
Up/Down arrow keys do not cause a KeyDown event

## Expected behavior
Up/Down arrow keys do cause a KeyDown event

## Minimal reproduction of the problem with instructions
Xaml:
```
     <TextBox KeyDown="UIElement_OnKeyDown"/>
```
Code behind:
```
        void UIElement_OnKeyDown(object sender, KeyRoutedEventArgs e)
        {
            Debug.WriteLine($"key down {e.Key}");
        }
```
Run in UWP and press the down arrow key and you get `key down Down`
Run in Wasm and press the down arrow key and you get nothing.

## Environment

```
Nuget Package:
1.45.0-dev.1457
Package Version(s):

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
@yowl This seems to work now, can you check?

**Comment by yowl** [comment]
yes, fine now, thanks
