### ISSUE TITLE
Template Studio for Uno

### ISSUE THREAD

**Issue by mmarinchenko** [unoplatform/uno#8665]
## What would you like to be added:

Recently, Microsoft folks released a bunch of [Template Studio](https://github.com/microsoft/TemplateStudio/releases/tag/v5.0) extensions for VS 2022:
* [Template Studio for WinUI](https://marketplace.visualstudio.com/items?itemName=TemplateStudio.TemplateStudioForWinUICs)
* [Template Studio for WPF](https://marketplace.visualstudio.com/items?itemName=TemplateStudio.TemplateStudioForWPF)
* [Template Studio for UWP](https://marketplace.visualstudio.com/items?itemName=TemplateStudio.TemplateStudioForUWP)

How about **_Template Studio for Uno_**? 🙂

## Why is this needed:

Today we have:
* [Uno Platform Solution Templates](https://marketplace.visualstudio.com/items?itemName=unoplatform.uno-platform-addin-2022) for Visual Studio
* [Prism Template Pack](https://marketplace.visualstudio.com/items?itemName=BrianLagunas.PrismTemplatePack) for Visual Studio which can generate Uno+Prism solution
* [Uno.ProjectTemplates.Dotnet](https://www.nuget.org/packages/Uno.ProjectTemplates.Dotnet) on NuGet.org
* [Uno.Extensions.Templates](https://www.nuget.org/packages/Uno.Extensions.Templates) on NuGet.org

All these templates evolve independently. Sometimes it's difficult to choose which is better in terms of provided patterns, or more recent, or more complete.

It's a bit confusing (especially for newcomers) and needs to be integrated into one tool with convenient UI.

## For which Platform:

- [X] Solution Templates (as an extension for Visual Studio)

## Anything else we need to know?

I'm aware that this is a non-trivial task. But I think some port of Template Studio is a good starting point to play with.

Please treat this enhancement request as an open idea. Also note that VS for Mac, VS Code, Rider, and dotnet CLI support is out of Template Studio scope.

**Comment by MartinZikmund** [comment]
I would call this done 🙃
