### ISSUE TITLE
[macOS] Resource URI is case sensitive

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#8666]
### How to reproduce it (as minimally and precisely as possible)

- Run SamplesApp.macOS(xamarinmac20)
- Select BitmapIcon_Sizing example

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

macOS

### IDE

Visual Studio for Mac

**Comment by spouliot** [comment]
https://github.com/unoplatform/uno/blob/6b8f248645beb93020990930ce3cc9e9841cca8e/src/Uno.UI/UI/Xaml/Media/ImageSource.macOS.cs#L97

is doing a case-sensitive lookup, even if the file system is not case-sensitive, reference:

> Important: The bundle interfaces consider case when searching for resource files in the bundle directory. This case-sensitive search occurs even on file systems (such as HFS+) that are not case sensitive when it comes to file names.

https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/AccessingaBundlesContents/AccessingaBundlesContents.html

**Comment by spouliot** [comment]
I have a fix for the image loading, will PR it soon.

However there's a second issue (unrelated to the load), it takes a refresh (invalidate) for the bitmap to be displayed. That one is probably best fixed in a different PR.

**Comment by spouliot** [comment]
There's a third issue as the last two bitmaps are loaded (not null) but never displayed (even after a refresh). Again not related to the case sensitiveness.

![Screen Shot 2022-05-03 at 11 32 29 AM](https://user-images.githubusercontent.com/260465/166486012-7722a066-7c10-4520-b91f-a9f6968f9c60.png)
