### ISSUE TITLE
[SamplesApp] Missing Assets and URL

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#8667]
#### Missing
- Assets/libre-camera-panorama.svg
- Assets/Diagnostics/avatar.png
- Assets/Diagnostics/movie_type_dbox.png
- Assets/Diagnostics/exclamation.png
- Assets/square100.png

#### Invalid URL
 - http://homepages.cae.wisc.edu/~ece533/images/baboon.png ([EllipsemaskingEllipseGrid.xaml](https://github.com/unoplatform/uno/blob/d690944a7f21735a4ff809565247f3547c6763c2/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/EllipsemaskingEllipseGrid.xaml#L28), [Image_With_RotateTransform](https://github.com/unoplatform/uno/blob/d690944a7f21735a4ff809565247f3547c6763c2/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Transform/Image_With_RotateTransform.xaml))
 - http://homepages.cae.wisc.edu/~ece533/images/monarch.png ([EllipsemaskingEllipseGrid.xaml](https://github.com/unoplatform/uno/blob/d690944a7f21735a4ff809565247f3547c6763c2/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/EllipsemaskingEllipseGrid.xaml#L33))
 - http://homepages.cae.wisc.edu/~ece533/images/fruits.png ([ImageBrushWithCompositeTransform.xaml](https://github.com/unoplatform/uno/blob/d690944a7f21735a4ff809565247f3547c6763c2/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/ImageBrushWithCompositeTransform.xaml#L23), [ListView_Image.xaml](https://github.com/unoplatform/uno/blob/d690944a7f21735a4ff809565247f3547c6763c2/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Image.xaml#L14-L16) )

### Works on UWP/WinUI

No

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### IDE

Visual Studio 2022

### IDE version

17.1.0 Preview 2.1

**Comment by workgroupengineering** [comment]
I would like to do a PR to correct these small problems but I don't know the size of the images. Can anyone give me some indication?

**Comment by jeromelaban** [comment]
I'd say that the size is not particularly important, 200x200 square images will likely do fine. Thanks!
