### ISSUE TITLE
[Skia.Gtk] On Windows with scale more or equal 200% application is shown only in small part of an application window

### ISSUE THREAD

**Issue by Dieveral** [unoplatform/uno#8669]
### Current behavior

On Windows with scale more or equal 200% application window is divided on 4 parts (2x2) and application is shown in the left bottom part. With scale more or equal 300% application window is devided on 9 parts (3x3) and again application is shown in the left bottom part. With scale less than 200% everything is shown fine.
![Scale_200](https://user-images.githubusercontent.com/50696412/166246266-aa6e9b24-6637-4daa-83fc-5681937af5b3.jpg)
![Scale_300](https://user-images.githubusercontent.com/50696412/166246268-a2dd5b3d-ece8-42f3-bc82-f5f1ac3ea9c1.jpg)

### Expected behavior

Application is shown on the whole application window no matter what scale is applied in display settings.

### How to reproduce it (as minimally and precisely as possible)

1. Create uno application
2. Set Scale more than 200% in display settings
3. Run Skia.Gtk project on Windows

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI.Skia.Gtk v4.2.6

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2019

### IDE version

16.11.5

**Comment by jeromelaban** [comment]
Thanks for the report. We have https://github.com/unoplatform/uno/pull/8594 to work on this. This is related to the use of the OpenGL renderer, you can temporarily disable it using the software renderer in the `Program.cs` file:

```
host.RenderSurfaceType = RenderSurfaceType.Software;
```

**Comment by Dieveral** [comment]
Thanks. I added this line before `host.Run();`
Now everything is normal.

**Comment by jeromelaban** [comment]
Fixed in Uno 4.5 prerelease bits.
