### ISSUE TITLE
wasm: TextBox layout/content alignment is different to UWP

### ISSUE THREAD

**Issue by yowl** [unoplatform/uno#867]
## I'm submitting a...

 - Bug report (I searched for similar issues and did not find one) 

## Current behavior
A `TextBox` in a `Grid` has its content centered and its clearbox (the x) width too narrow (this bit is minor).  In UWP the text is aligned top.  See the 2 attached graphics

## Expected behavior
Layout of a `TextBox` should be the same in UWP and wasm.

## Minimal reproduction of the problem with instructions
xaml:
```
<Page
    x:Class="UnoStandardRefTest3.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:UnoStandardRefTest3"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid >
        <TextBox />
    </Grid>
</Page>
```

![image](https://user-images.githubusercontent.com/2720041/57736718-a64c2900-766e-11e9-89d9-ac43b03d1f44.png)
![image](https://user-images.githubusercontent.com/2720041/57736732-b19f5480-766e-11e9-82d2-a369c956e750.png)

## Environment

```
Nuget Package:
1.45.0-dev.1457"
Package Version(s):

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
This has been fixed in PR https://github.com/unoplatform/uno/pull/1726
Also reported there: https://github.com/unoplatform/uno/issues/1561

I'm closing this issue.  Feel free to reopen it if you find any new related problem.
