### ISSUE TITLE
[Playground][wasm] NumberBox

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#8679]
### Current behavior

![image](https://user-images.githubusercontent.com/5839577/166524112-cf276a8a-80c6-42bd-89b3-9f1e9dd2b718.png)

See live in https://playgroundcanary.z19.web.core.windows.net/#numberbox

Click on the editable text zone to view the issue.

### Expected behavior

The browser's (or TextBox) delete button should not be under the spinner buttons.

### Workaround

Use fluent V1 styles

### Works on UWP/WinUI

Yes

### NuGet package version(s)

4.2.6

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
@MartinZikmund does it look familiar?

**Comment by MartinZikmund** [comment]
Yes, noticed this already, we probably don't correctly hide the delete button for NumberBox.

**Comment by jeromelaban** [comment]
Curiously, the delete button is placed properly in fluent V1.

**Comment by Youssef1313** [comment]
![image](https://github.com/unoplatform/uno/assets/31348972/d4081dfa-36a4-476c-a545-07da97d9c3dc)

![image](https://github.com/unoplatform/uno/assets/31348972/0d75f0ed-e981-474c-89e3-3d2abe26a016)

It looks like it works correctly now? @jeromelaban ?

**Comment by jeromelaban** [comment]
This was indeed fixed!
