### ISSUE TITLE
Android TV navigation with remote and focus does not work 

### ISSUE THREAD

**Issue by Delaire** [unoplatform/uno#868]
## I'm submitting a...

- Bug report

## Current behavior

- On an android phone I can click on my button and the event will be fire (clicked)
- Same code on Android TV I cant focus/or navigate to the button with the remote and thus I cant click on the button

## Expected behavior

I would like to be able to be able to navigate with the android tv remote so that I can set the focus on my button 

## Minimal reproduction of the problem with instructions
```
 <Button
            x:Name="myBtn"
            Grid.Row="1"
            Click="myBtn_Click"
            Content="My button test"
            Foreground="Black"
            IsTabStop="True" />
```

## Environment

```
Nuget Package: 1.45.0-dev.1457
Package Version(s):

Affected platform(s):
- [ ] iOS
- [x] Android 8.0 (API level 26 - Oreo)
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ x] 2017 (version: )
- [ x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Howdy @Delaire. What is the API Level you are using on your Android TV and Android Phone?

**Comment by Delaire** [comment]
Hello @ghuntley I am targeting Android 8.0 (API level 26 - Oreo), ill update my initial post with this info.
