### ISSUE TITLE
NativeCtorsGenerator do not generate ctor

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#8684]
### Current behavior

When creating xaml which has no code behind or in code behind it, implementing explicit xaml objects like [this](https://github.com/unoplatform/uno/blob/d690944a7f21735a4ff809565247f3547c6763c2/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/LoadFromBytes.xaml.cs#L14),  NativeCtorsGenerator cannot identify iOS, macOS, Android view and does not generate native ctor.

Ref. https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=45342&view=logs&j=112d7fbb-6edd-5bf4-9749-bb0e7c56bd40&t=f5e9da5e-f674-514c-bf20-be3e00b8bb45&l=26068

### Expected behavior

NativeCtorsGenerator can identify iOS, macOS, Android view and generate native ctor.

### Workaround

Add code behind  implementing explicit xaml objects ex for [LoadFromBytes.xaml](https://github.com/unoplatform/uno/blob/d690944a7f21735a4ff809565247f3547c6763c2/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/LoadFromBytes.xaml)

change code behind like this:

```diff
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Uno.UI.Samples.Controls;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Media.Imaging;
+using Windows.UI.Xaml.Controls;
using Uno.Extensions;

namespace Uno.UI.Samples.UITests.ImageTestsControl
{
	[SampleControlInfo("Image", "LoadFromBytes")]
-      public sealed partial class LoadFromBytes
+      public sealed partial class LoadFromBytes: UserControl
	{
		public LoadFromBytes()
		{
			InitializeComponent();
			Loaded += OnLoaded;
		}

		private async void OnLoaded(object sender, RoutedEventArgs e)
		{
			var assembly = typeof(LoadFromBytes).Assembly;

			var query = from name in assembly.GetManifestResourceNames()
						where name.EndsWith("mslug.png")
						select assembly.GetManifestResourceStream(name);

			using (var stream = query.First())
			{
				MyImage.Source = await CreateImageSource(stream);
			}
		}

		private async Task<ImageSource> CreateImageSource(Stream stream)
		{
			if (stream == null)
			{
				throw new ArgumentNullException(nameof(stream));
			}

			var image = new BitmapImage();

#if WINDOWS_UWP
			await image.SetSourceAsync(stream.AsRandomAccessStream()).AsTask();
#else
			var copy = stream.ToMemoryStream();
			await image.SetSourceAsync(copy);
#endif
			return image;
		}
	}
}

```

### Environment

Uno.SourceGenerationTasks

### NuGet package version(s)

master d690944a7f21735a4ff809565247f3547c6763c2

### Affected platforms

iOS, Android, macOS, Build tasks

### IDE

Visual Studio 2022, Visual Studio for Mac

### IDE version

17.1.0 Preview 2.1

**Comment by workgroupengineering** [comment]
trackback https://github.com/dotnet/roslyn/issues/57239

**Comment by jeromelaban** [comment]
Indeed, that's an issue which is difficult to fix at this time. We have a warning message which is displayed in some cases (x:Bind mainly) when code-behind does not provide a base class.

**Comment by workgroupengineering** [comment]
I have found a partial solution to the problem.

I have added GenerateAfter to NativeCtorsGenerator and it seems to work

```csharp
	[Generator]
#if NETFRAMEWORK
	[GenerateAfter("Uno.UI.SourceGenerators.XamlGenerator." + nameof(XamlGenerator.XamlCodeGenerator))]
#endif
	public class NativeCtorsGenerator : ISourceGenerator
	{
```

**Comment by jeromelaban** [comment]
Yes, it does work for Xamarin because we're using the Uno.SourceGeneration package, but it will not for net6 (roslyn hosted generators won't use this)

**Comment by workgroupengineering** [comment]
I have found a workaround for net6. Roslyn currently sorts generators by full name, so just rename NativeCtorsGenerator to make XamlCodeGenerator run after.

**Comment by jeromelaban** [comment]
Sure, but generators are still run in parallel, and the output of one is not included in the next one, iirc.
