### ISSUE TITLE
[Gallery][Catalyst] Card- All cards are partially visible for the Card control screen layout.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8687]
### Current behavior

![Card issue](https://user-images.githubusercontent.com/74563602/166740825-adf194d2-41a5-410d-8c34-9492bdcb7a52.png)

### Expected behavior

![Card Correct](https://user-images.githubusercontent.com/74563602/166741206-84dbd1c6-ea7d-40c4-b18d-0203dd81f279.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP 
2. Tap Burger Menu on the left top right.
3. Tap "Card" from the "Component" list.
4. Observe that all cards are partially visible for the Card control screen layout.

### Anything else we need to know?

Affected Platform - Mac Catalyst

**Comment by jeromelaban** [comment]
This issue is related to https://github.com/unoplatform/uno/issues/8341, because the iOS code does not use proper window size calculation:
https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Window.iOS.cs#L54-L79

**Comment by sakshi173** [comment]
Issue is fixed in latest Version(1.5.0 - 2205070319.912) . Closing it
