### ISSUE TITLE
Package required for MapControl is not published

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#869]
## Current behavior

As described by the [Uno documentation for MapControl](https://github.com/nventive/Uno/blob/master/doc/articles/controls/map-control-support.md), it depends on an additional NuGet package (to avoid bundling unnecessary dependencies for apps that don't use it). That NuGet package currently isn't published, meaning MapControl can't be used.

## Expected behavior

Uno.UI.Maps package is published

## Minimal reproduction of the problem with instructions

``` xaml
	<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
		<Grid.RowDefinitions>
			<RowDefinition Height="auto" />
			<RowDefinition Height="*" />
		</Grid.RowDefinitions>
		<StackPanel>
			<Slider Minimum="1"
					Maximum="20"
					StepFrequency=".5"
					Header="ZoomLevel"
					x:Name="zoomSlider"
					Value="12" />
		</StackPanel>
		<maps:MapControl Grid.Row="1"
						 ZoomLevel="{Binding ElementName=zoomSlider, Path=Value, Mode=TwoWay}" />
	</Grid>
```

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
The package is now published
