### ISSUE TITLE
[Gallery][iOS/Catalyst] ProgressRing/Bar -All progressing/Bar is missing.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8695]
### Current behavior

![progressring issue](https://user-images.githubusercontent.com/74563602/166829866-724d25dc-103c-4b2a-a842-3078d395ad74.png)
![Progressring ios issue](https://user-images.githubusercontent.com/74563602/166829886-f6662bd1-eb06-4ad3-b7fb-5483caa7cd38.png)

### Expected behavior

![Progressring correct](https://user-images.githubusercontent.com/74563602/166829896-673bab34-2e3a-4ca5-857a-534ed3c08e0b.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "ProgressRing/Bar" from the "Component" list.
4. Observe that all progressing/Bar is missing.

### Affected platforms

iOS

### Anything else we need to know?

Affected Platform - Mac Catalyst

**Comment by jeromelaban** [comment]
Progress ring is not yet supported on iOS (Lottie support is missing).

**Comment by sakshi173** [comment]
@jeromelaban, thanks for letting me know,  then please let me know if shall I close this bug?
