### ISSUE TITLE
[macOS] `BitmapIcon_Sizing` needs a refresh before showing the bitmaps

### ISSUE THREAD

**Issue by spouliot** [unoplatform/uno#8696]
### Current behavior

Only the text is visible when selecting `BitmapIcon_Sizing` inside `SampleApp` on macOS.

![Screen Shot 2022-05-04 at 8 07 14 PM](https://user-images.githubusercontent.com/260465/166845379-d4606baa-0f0f-4988-afa6-3392dfb80dee.png)

### Expected behavior

All six bitmaps should be visible when `BitmapIcon_Sizing` is selected.

### How to reproduce it (as minimally and precisely as possible)

Run `SamplesApp.macOS` and select `BitmapIcon_Sizing`

### Workaround

Click on the _hamburger_ icon to cause a refresh.
Most of the bitmaps (4 out of 6) will now be visible.
The missing (2) bitmaps are due to another bug (to be filed).

![Screen Shot 2022-05-04 at 8 08 17 PM](https://user-images.githubusercontent.com/260465/166845521-41c26be5-e9eb-485a-9176-77b3b343a061.png)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

git master 8acab1c2006f3173b4f645cb9127c35ee76d0e34

### Affected platforms

macOS

### IDE

Visual Studio for Mac

### IDE version

Version 17.0 Preview (17.0 build 8754)

### Anything else we need to know?

This issue was noticed when trying to duplicate https://github.com/unoplatform/uno/issues/8666

**Comment by jeromelaban** [comment]
Thanks! This may look like an issue related to this one: https://github.com/unoplatform/uno/issues/8330, where the computation of layout is broken as a result of "measure path" inclusion. @carldebilly.

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
