### ISSUE TITLE
[macOS] `BitmapIcon_Sizing` only displays 4 out of 6 bitmaps

### ISSUE THREAD

**Issue by spouliot** [unoplatform/uno#8697]
### Current behavior

Only four (out of six) bitmaps are visible (after refresh) when selecting BitmapIcon_Sizing inside SampleApp on macOS.

See https://github.com/unoplatform/uno/issues/8696 about the missing refresh/invalidation

![Screen Shot 2022-05-04 at 8 08 17 PM](https://user-images.githubusercontent.com/260465/166848357-4301f071-f832-4d12-9340-40cc702e5d4d.png)

### Expected behavior

All six bitmaps should be visible.

They all display properly if using the Gtk/Skia backend on macOS.

### How to reproduce it (as minimally and precisely as possible)

Run `SamplesApp.macOS` and select `BitmapIcon_Sizing`

### Workaround

To get the two missing bitmaps displayed you can edit the XAML file like this:

```diff
diff --git a/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BitmapIconTests/BitmapIcon_Sizing.xaml b/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BitmapIconTests/BitmapIcon_Sizing.xaml
index 3bba95ea2..b8666d402 100644
--- a/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BitmapIconTests/BitmapIcon_Sizing.xaml
+++ b/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BitmapIconTests/BitmapIcon_Sizing.xaml
@@ -33,8 +33,8 @@
                        <TextBlock Text="Should stretch but remain square, left aligned" />
                </Grid>

-               <Grid Grid.Row="1" Grid.Column="1">
-                       <BitmapIcon Width="100" Height="100" UriSource="ms-appx:///Assets/Icon.png" ShowAsMonochrome="False" />
+               <Grid Grid.Row="1" Grid.Column="1" Height="100">
+                       <BitmapIcon UriSource="ms-appx:///Assets/Icon.png" ShowAsMonochrome="False" />
                </Grid>
                <TextBlock Grid.Row="1" Grid.Column="1" Text="Should be 100x100" />

@@ -43,7 +43,7 @@
                </Grid>
                <TextBlock Grid.Row="2" Grid.Column="0" Text="Should be 30x30" />

-               <Grid Grid.Row="2" Grid.Column="1" Width="60">
+               <Grid Grid.Row="2" Grid.Column="1" Height="60">
                        <BitmapIcon x:Name="Icon60" UriSource="ms-appx:///Assets/Icon.png" ShowAsMonochrome="False" />
                </Grid>
                <TextBlock Grid.Row="2" Grid.Column="1" Text="Should be 60x60" />
```

It looks like some of the properties are not assigned (or do not have the correct effect) and that makes displaying the bitmaps impossible.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

git master https://github.com/unoplatform/uno/commit/8acab1c2006f3173b4f645cb9127c35ee76d0e34

### Affected platforms

macOS

### IDE

Visual Studio for Mac

### IDE version

Version 17.0 Preview (17.0 build 8754)

### Anything else we need to know?

This issue was noticed when trying to duplicate https://github.com/unoplatform/uno/issues/8666

**Comment by jeromelaban** [comment]
Thanks! This is likely related to https://github.com/unoplatform/uno/issues/8696 because of measure path issues.

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
