### ISSUE TITLE
[Gallery][iOS] TabBar(Material)-Floating circle button in the 'Bottom TabBar sample page' is missing

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8709]
### Current behavior

![Tabbar Fab issue](https://user-images.githubusercontent.com/74563602/167139859-b7a8c145-a1be-49c4-a433-34e55baf1636.png)

### Expected behavior

![Tabbar fab button correct](https://user-images.githubusercontent.com/74563602/167139882-19f3cb2f-2bb8-4c5a-b727-f7bb8be9a244.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP .
2. Click/tap Burger Menu on the left top right.
3. Ensure that the Gallery app is in Day Mode.
4. Tap "TabBar" from the "Toolkit" list.
5. Go to 'Material' section.
6. Click/Tap on 'SHOW BOTTOM TABBAR SAMPLE' button.
7. Notice that Floating Fab button is missing. 

### Affected platforms

iOS

**Comment by jeromelaban** [comment]
Fixes https://github.com/unoplatform/uno/issues/8709

**Comment by sakshi173** [comment]
Issue is fixed in latest Version(1.5.0 - 2205070319.912) . Closing it
