### ISSUE TITLE
[Gallery][iOS] `TimePicker` - Inital launch time is not displaying correctly

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8713]
### Current behavior

![Timepicker](https://user-images.githubusercontent.com/74563602/167210555-47ae663e-74d0-4b1b-9c2a-29b4daf64b6c.png)

https://user-images.githubusercontent.com/74563602/167209255-d7fc89b9-5208-4502-b40e-7556c4aba315.MOV

### Expected behavior

![timepicker correct](https://user-images.githubusercontent.com/74563602/167210563-1a0ec3d7-ae49-42bd-a620-874f0c744c95.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "TimePicker" from the "Component" list.
4. Observe that "Set Time" is displaying incorrectly.

### Affected platforms

iOS

**Comment by agneszitte** [comment]
@MartinZikmund I am assigning this issue so you can do the proper follow-up on the current state of TimePicker please (sample is already disabled for now in Gallery until we have something stable)

**Comment by MartinZikmund** [comment]
We don't have the managed implementation (based on UWP) but for mobile the native implementation should work. Will investigate why it does not!

**Comment by agneszitte** [comment]
@jhanvi03 if you have some time to see if this issue still occurs lately please when canary will be available

**Comment by agneszitte** [comment]
@jhanvi03, @Darsh0307 if you can test this issue with latest internal 5.6 stable please
