### ISSUE TITLE
SDK-style project template is setting build type wrong for uno-fluentui-asset.ttf

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#8735]
### Current behavior

Creating a new net6-uno-app does not load the uno-fluentui-assets.ttf font correctly on Android and iOs. A SymbolIcon with the "Add"-symbol does not show the symbol but renderes the "no image"-icon instead.

### Expected behavior

The font is loaded correctly.

### Workaround

For Android: set the build type for the font within "Mobile.cspro->Android/Assets/Fonts/uno-fluentui-assets.ttf" to "AndroidAsset". For iOs I think it would have to be BundleResource - but I cannot set this from VS.

### Works on UWP/WinUI

Yes

### NuGet package version(s)

4.2.0

### Affected platforms

iOS, Android

### IDE

Visual Studio 2022

### IDE version

17.2.0 Preview 6

**Comment by jeromelaban** [comment]
Thanks for the report. This has been fixed in uno 4.3-dev builds.
