### ISSUE TITLE
[VisibleBoundPadding] Padding from visibleBoundPadding changes when you rotate the screen with windowtranslucentStatus enabled

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#8740]
### Current behavior

![androidwithbug](https://user-images.githubusercontent.com/90481654/167697671-f02686f8-3734-4399-803f-d3f89534486e.gif)
 The padding from visiblebound padding changes when you rotate the screen to landscape and back to portrait,

### Expected behavior

![iosnotbug](https://user-images.githubusercontent.com/90481654/167697968-909e7b7f-b61e-4995-89f4-a640ccfd140b.gif)
Just like on IOS, or on android when android:windowTranslucentStatus is set to false, the padding should not change when you put the phone to portrait mode and back.

### How to reproduce it (as minimally and precisely as possible)

Open the app and rotate the screen to landscape mode. 
Put it back in portait mode.
[landscapeandroid.zip](https://github.com/unoplatform/uno/files/8664120/landscapeandroid.zip)
 

The screen needs to rotate to see the bug, so, I didnt try.

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

![image](https://user-images.githubusercontent.com/90481654/167700523-1e7278ff-2db9-4133-98c1-50e8ef51134f.png)
![image](https://user-images.githubusercontent.com/90481654/167700550-bd8b6427-bac5-4917-9180-244028ed45cb.png)

The sample I gave currently has the latest stable Uno.Ui, but the behavior is exactly the same.

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.0.6

### Anything else we need to know?

![image](https://user-images.githubusercontent.com/90481654/167700090-655564c3-b5f8-407f-bfec-f84f9ff12580.png)
If you close the screen (or put the phone to sleep? I'm not how to say it well) the padding moves in a different way as you can see in this screenshot, where the rectangle is at the right place, but the background of the grid which is supposed to surround the rectangle, is not.  

I produce this bug on a Samsung Galaxy A70 Android version 11

**Comment by kazo0** [comment]
@Marc-Antoine-Soucy Can you confirm on your side that this is no longer an issue with latest Uno?

I updated the Uno packages in your sample to latest stable and it looks to be working correctly now:
![rotate](https://user-images.githubusercontent.com/4793020/214684742-eded0292-f1b7-4bb8-a037-83c9fd6441f0.gif)

**Comment by jeromelaban** [comment]
Note that moving to [SafeArea](https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls/SafeArea.html?tabs=none) may help.

**Comment by takla21** [comment]
This issue does not happen on TZ anymore

**Comment by takla21** [comment]
The issue does not happen on our project anymoree
