### ISSUE TITLE
[Gallery][Skia.GTK] FlipView is not able to swipe left or right.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8760]
### Current behavior

![FlipView issue 1-](https://user-images.githubusercontent.com/74563602/168139177-cd45cb01-75e7-47af-9eea-2d90870ba4c6.png)

### Expected behavior

![FlipView issue-](https://user-images.githubusercontent.com/74563602/168139199-21db4a55-a2e0-4d12-abe0-20b292a75e0f.png)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app on Skia.GTK.
2. Click on “FlipView” from the "Component" list.
3. Notice that FlipView not able to swipe left or right.

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by jeromelaban** [comment]
On Skia, touch may not be supported properly for this control, but you should be able to change the active item by using the arrows on the left and right of the control.

**Comment by sakshi173** [comment]
@jeromelaban, I tried using arrows but its not working,  I am not able to make a video for Skia, due to that not able to put that.
