### ISSUE TITLE
The attachable property 'AutowireViewModel' was not found in type 'ViewModelLocator'.		

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#8773]
### Current behavior

 1. I fetched and compiled Prism and referenced to my Wasm project.  (can be found enclosed)
 2. Attempted to switch on auto view model wire.
 3. Having this build error.

![image](https://user-images.githubusercontent.com/43340959/168443975-1c9c5710-2c3c-46f0-abcf-3c08956515c2.png)

Checked also in source what I compiled the dep property is there:

![image](https://user-images.githubusercontent.com/43340959/168444007-26ebefd0-74fb-4e2d-9284-3cdf41d3e183.png)

[Prism.NetStandard.zip](https://github.com/unoplatform/uno/files/8693666/Prism.NetStandard.zip)

### Expected behavior

Attached property must be available on ```Wasm``` head like ```Windows Desktop``` head. 

### How to reproduce it (as minimally and precisely as possible)

1. Please reference the assemblies enclosed can be found. 
2. Try to swtich on the dep property. 

### Workaround

Currently only Windows Desktop compliable. 

### Works on UWP/WinUI

Yes

### NuGet package version(s)

```
    <ItemGroup>
      <PackageReference Include="DryIoc.dll" Version="4.8.8" />
      <PackageReference Include="LiveChartsCore.SkiaSharpView.Uno" Version="2.0.0-beta.220" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
      <PackageReference Include="Microsoft.Windows.Compatibility" Version="6.0.0" />
      <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.3.0" />
      <PackageReference Include="Uno.WinUI.WebAssembly" Version="4.2.6" />
      <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.2.6" Condition="'$(Configuration)'=='Debug'" />
      <PackageReference Include="Uno.Wasm.Bootstrap" Version="3.3.1" />
      <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="3.3.1" />
    </ItemGroup>
```

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

Version 17.2.0

### Anything else we need to know?

[Rep](https://github.com/sigmarsson/72045760)

**Comment by jeromelaban** [comment]
Note that the repro cannot work, since LiveChartsCore.SkiaSharpView.Uno references Uno.UI, not Uno.WinUI. LiveCharts can't yet be updated until https://github.com/mono/SkiaSharp/issues/1787 is fixed. 

Make sure to validate with Uno.UI first.

**Comment by sigmarsson** [comment]
@jeromelaban Thanks. So neither #8773 nor #8774 will resolve until [this one](https://github.com/mono/SkiaSharp/issues/1787) fixed ? (in `Uno.WinUI` flavor)

**Comment by jeromelaban** [comment]
SkiaSharp for WinUI has been released.

**Comment by volcano619** [comment]
I'm still getting this error for MAUI
