### ISSUE TITLE
[AutoSuggestBox] AutoSuggestBox not working on IOS and Android when a style is given. 

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#8793]
### Current behavior

![autocompletenotworking](https://user-images.githubusercontent.com/90481654/168679493-ea6849c1-1455-4674-b92c-53997651e75c.gif)
When I give the style in the sample to AutoSuggestBox, it doesnt work on IOS and Android, unlike on UWP. (I didnt try with other styles so far, but the default works correctly.)

### Expected behavior

![autocompleteworking](https://user-images.githubusercontent.com/90481654/168679535-cc386219-d9ff-4f5c-affe-11026c678b26.gif)
It should show the autocompleted prediction, just like it does on UWP.

### How to reproduce it (as minimally and precisely as possible)

Open the app on uwp, see that text appears below the textbox when you type something.
Open the app on android/IOS, see that nothing happens when you type something.
[AutoSuggestBoxStyling.zip](https://github.com/unoplatform/uno/files/8703350/AutoSuggestBoxStyling.zip)

You can also remove the the style, it works for IOS, android and UWP

### Workaround

I did not find any.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

![image](https://user-images.githubusercontent.com/90481654/168680196-f8bfbfb8-2d6e-4600-9593-55aacac4fbc9.png)![image](https://user-images.githubusercontent.com/90481654/168680159-51bb86fc-40cc-4511-a8c6-96dd2da01b72.png)

### Affected platforms

iOS, Android

### IDE

Visual Studio 2022

### IDE version

17.0.6

### Relevant plugins

None

**Comment by MaximeDion-Work** [comment]
Tried using the style but the issue remains.

**Comment by jeromelaban** [comment]
This style is the one you see running in the app. What do you mean by you used the style and it remains? Is it that you modified that style and you can make it work?

**Comment by MaximeDion-Work** [comment]
Sorry I thought the style you proposed was different from the current one somehow. What I tried was creating a new resource dictionary and copy pasted the style from you comment. I did not fiddle to much with it beyond some error coming from the contract7NotPresent conditional. Is there anything in the style that controls interaction between the suggestions and keyboard?

**Comment by MaximeDion-Work** [comment]
Ok, I'm the one who got mixed up. I was working on a bug where the suggestions were hidden behind keyboard. This issue was mentioned in the impediment so I assumed that we were talking about the auto suggestion results being hidden here also. My apologies for the confusion.

**Comment by jeromelaban** [comment]
So is there still an issue or not ? :)

**Comment by MaximeDion-Work** [comment]
I'm working on something now, but I'll keep you posted.

**Comment by MaximeDion-Work** [comment]
Yeah using the styles @jeromelaban provided works on all platforms

**Comment by jeromelaban** [comment]
Thanks, I'm closing this issue then.
