### ISSUE TITLE
UNO_REFERENCE_API is incorrectly defined in `net6-*` targets

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#8814]
### Current behavior

This block:
https://github.com/unoplatform/uno/blob/bf89f6d7fca9bc8ded65b238a6eee7fad3334eaa/build/uno.winui.targets#L37-L39

incorrectly defines `UNO_REFERENCE_API` when buidling for the .NET 6 mobile targets, causing Reference API definitions to be used incorrectly (SkiaSharp is impacted by this).

### Expected behavior

`UNO_REFERENCE_API` is only defined when using wasm or skia compatible targets.

**Comment by MartinZikmund** [comment]
@Youssef1313  Is this adjusted for 5x?

**Comment by Youssef1313** [comment]
Looks like it's not https://github.com/unoplatform/uno/blob/7dd4964888aeedced21ef08121ff554737cb99f5/build/nuget/uno.winui.common.targets#L59-L61

**Comment by Youssef1313** [comment]
Fixed in https://github.com/unoplatform/uno/pull/14282

**Comment by MartinZikmund** [comment]
@jeromelaban worth backporting?
