### ISSUE TITLE
[Gallery][Android/iOS/Wasm]ProgressRing/Bar- Progressring are incorrect for Determinate ProgressRing. 

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8845]
### Current behavior

https://user-images.githubusercontent.com/74563602/169608742-ce802d29-9c40-4b3c-afa0-aa8fcbd3e6fa.mp4

https://user-images.githubusercontent.com/74563602/169608759-da4a48d5-1888-4a08-b706-90010c388298.MOV

![progressring wasm issue](https://user-images.githubusercontent.com/74563602/169609725-8fb0ec8d-d906-44fb-bb12-d6ada8b84a2c.png)

### Expected behavior

https://user-images.githubusercontent.com/74563602/169609861-ab55a3cf-927e-4fb1-8f8a-b287e441af34.mp4

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "Progress Ring/Bar" from the "Component" list.
4. Observe that For 'Determinate ProgressRing' the Progress of the  Ring is not happening correctly.

### Affected platforms

iOS, Android, WebAssembly

**Comment by jeromelaban** [comment]
This is expected for now, until https://github.com/mono/SkiaSharp/pull/1987 is merged.

**Comment by sakshi173** [comment]
and @jeromelaban,  Progress Ring is missing for iOS, is that also expected?
![pr iOS issue](https://user-images.githubusercontent.com/74563602/169611316-e80e6ca7-8921-44cb-8270-0239e3e2a1a2.png)

**Comment by MartinZikmund** [comment]
@morning4coffe-dev  can you check this on non-iOS platforms?

**Comment by jeromelaban** [comment]
This issue is likely related to the fact that Skia is not available for UWP on net6+, and the gallery is UWP based. (@kazo0)

**Comment by morning4coffe-dev** [comment]
@MartinZikmund @jeromelaban Apologies for the delay; it this got lost in my inbox during my vacation. I did some testing on Android and Wasm. 

In Wasm Canary (tested on the latest version of Edge), I noticed a minor gap in the slider when set to 100. However, this gap is not very noticeable, and the progress rings is correct type:

![image](https://github.com/unoplatform/uno/assets/78549750/337b5ed0-aea7-4ced-82bd-cb9302ef8cd1)


On Android I don't see any issues with either wrong type or gap when set to 100.

![image](https://github.com/unoplatform/uno/assets/78549750/6f236241-ece0-45c1-98d0-2072ba89683c)

I couldn't test it on iOS however where the issue might be still happening.

**Comment by agneszitte** [comment]
@sakshi173 can you test with latest versions please

**Comment by sakshi173** [comment]
@agneszitte, yes, the mention issue is fixed, but as @MartinZikmund said ' a minor gap in the slider when set to 100 is happening. please let me know if I can close this defect.

**Comment by MartinZikmund** [comment]
Turns out the issue already exists https://github.com/unoplatform/uno/issues/12401 , closing this one
