### ISSUE TITLE
Avoid `RegisterPropertyChangedCallback` in `AssignAndObserveBrush` and use override instead

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#8891]

**Comment by MartinZikmund** [comment]
@Youssef1313 Can this be closed?

**Comment by Youssef1313** [comment]
@MartinZikmund There are still few AssignAndObserveBrush calls on Skia

**Comment by MartinZikmund** [comment]
@Youssef1313 are they still using the old subscription approach?
