### ISSUE TITLE
[Android][IOS] performance issue when combobox contains a lot of items

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#8897]
### Current behavior

![3combobox](https://user-images.githubusercontent.com/90481654/170576705-31bd134c-8c62-4ca1-8379-156b6f1d6b39.gif)

When navigating to a page containing several combobox with a lot of items (~250), it takes a lot of time to load the page. In the example above, I am showing this is the case even when the combobox is collapsed. The upper button leads to a page containing combobox with 5 items, while the button below leads to a page containing three combobox with 250 items. 

### Expected behavior

![comboboxuwp](https://user-images.githubusercontent.com/90481654/170578394-e2e88cee-28f4-4f4c-b267-fa43653487f1.gif)
It should ideally have little load time for both.

### How to reproduce it (as minimally and precisely as possible)

[BigComboBox.zip](https://github.com/unoplatform/uno/files/8782055/BigComboBox.zip)
The reason there are several combobox and the items are visible is to show that a: it doesnt matter that the items are collapsed or not and several combobox makes the issue worse. And also, because it mirrors a real issue I have.

### Workaround

I havent found any.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

![image](https://user-images.githubusercontent.com/90481654/170579813-5ccb75a8-b4ba-4516-bd47-e328d89ba2f2.png)
![image](https://user-images.githubusercontent.com/90481654/170579855-0b5f8c4e-b77f-4b9a-905c-56b1384f57ff.png)

 The nugget in the sample I gave is the latest stable, but I tried with the newest uno.ui (which is shown here)

### Affected platforms

iOS, Android

### IDE

Visual Studio 2022

### IDE version

17.0.6

### Anything else we need to know?

I am honestly not sure if this is a just a limitation of android or IOS, but it would be great if it could get better because it can get worse than in the sample app.

Anothing I feel is important to note is, I think it, doubling the number of items more than doubles the loading time.

**Comment by MartinZikmund** [comment]
Agreed, this is an important performance problem. We have an issue open for this - #556, so I will close this one as duplicate; but I will bump the priority on it. Please upvote #556 as well 🙂
