### ISSUE TITLE
[Gallery][Skia.GTK]PasswordBox- RevealButton  and typed text foreground does not change with theme.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8904]
### Current behavior

https://user-images.githubusercontent.com/74563602/170779444-4a646936-840a-4b17-850a-90af9075cf5c.mp4

### Expected behavior

The eye icon should be visible while typing text for the password.

### How to reproduce it (as minimally and precisely as possible)

1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Change theme from Day mode to Night mode.
3. Click/tap Burger Menu on the left top right.
4. click/tap "PasswordBox" from the "Component" list.
5. Type Text for the password box.
6. Observe that while writing the text for the password, the eye icon is not visible.

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by iurycarlos** [comment]
It is not only with Theme changing. It is relatedo to PasswordBox loosing focus.

Steps:

1 - Type something. Reveal button will appear.
2 - Set focus to other control. Reveal will disappear.
3 - Try to type something else. It will not show Reveal Button anymore.

The only way to get the reveal button back is deleting all PasswordBox content and change focus again.

**Comment by sakshi173** [comment]
Verified issue is fixed due to that closing this bug.
