### ISSUE TITLE
[iOS / Android] [AutoSuggestBox] The suggestion popup appears behind the virtual keyboard

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/uno#8926]
### Current behavior

You you start entering text in a suggestion box, the popup containing suggestion can end up behind the keyboard.
![AutoSuggest](https://user-images.githubusercontent.com/64613932/171039774-7b29c95f-084a-424c-9cc7-90386421e119.gif)

### Expected behavior

The screen should move up to accomadate the suggestion box + it's suggestion.

![image](https://user-images.githubusercontent.com/64613932/171040507-f3b837af-0350-4930-94f7-b5fb1fca7c07.png)

### How to reproduce it (as minimally and precisely as possible)

- Place a AutoSuggestBox close to the bottom of the screen.
- Start the app
- Enter Text
- Notice popup containing suggestion appears under the virtual keyboard

[AutoSuggestBoxStyling.zip](https://github.com/unoplatform/uno/files/8800099/AutoSuggestBoxStyling.zip)

### Workaround

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI-dev.254

### Affected platforms

iOS, Android

### IDE

Visual Studio 2022

### IDE version

17.1.3

### Relevant plugins

None

### Anything else we need to know?

[DevOps Issue](https://dev.azure.com/nventive/TradeZero/_workitems/edit/256124)

**Comment by MartinZikmund** [comment]
@kazo0 Probably will be related to visible bounds, so adding you here 👍

**Comment by MaximeDion-Work** [comment]
Any progress on this issue?

**Comment by marwalsch** [comment]
Same behaviour on iOS, only here the dropdown effectively cannot even be interacted with and instead closes immediately, perhaps due to the keyboard robbing its focus.


![RPReplay_Final1666780484](https://user-images.githubusercontent.com/72074423/198009977-1b2aaa41-699b-4f67-bf24-18944d113fa8.gif)

**Comment by MartinZikmund** [comment]
@marwalsch This part should now be fixed with latest Uno dev bits

**Comment by kazo0** [comment]
@MartinZikmund has this issue been fixed or is there still more to do around this?

**Comment by MartinZikmund** [comment]
@kazo0 Looking into this one now

**Comment by MartinZikmund** [comment]
This should be fixed in the latest dev bits #11459
