### ISSUE TITLE
`Popups` jumping around on pointer hover in Skia

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#8932]
### Current behavior

In some cases, `Popups` and `Flyouts` start dancing up and down when hovered over with mouse.

### Expected behavior

Should stay in one place.

### How to reproduce it (as minimally and precisely as possible)

- Open `UIElement_ContextFlyout` sample in Samples app
- Right-click the button or Slider
- Hover mouse around the flyout and it will start "dancing"

**Comment by MartinZikmund** [comment]
It seems `ScrollBar` is showing up briefly in the flyout too, so it might be related

**Comment by Youssef1313** [comment]
@MartinZikmund I'm not able to reproduce this.
