### ISSUE TITLE
Skia - ListView with Extended (or Multiple) selection checkboxes

### ISSUE THREAD

**Issue by sarosigy** [unoplatform/uno#8937]
### Current behavior

On linux platform, when setting the ListView's SelectionMode to Extended (or Multiple), and filling with items, the selection checkboxes appear only after scrolling some. In between some items are decorated, some are not. After scrolling enough, all items are decorated with the checkboxes.
![Screenshot_lvsel1](https://user-images.githubusercontent.com/37872626/171132564-ab5aca24-8861-4734-8368-e6ec159ffb2c.png)
![Screenshot_lvsel2](https://user-images.githubusercontent.com/37872626/171132588-e024c083-d537-4f68-b323-c41aff2237d2.png)
![Screenshot_lvsel3](https://user-images.githubusercontent.com/37872626/171132606-1f13795c-8b0f-4ce0-a18c-b888ddec81cc.png)

### Expected behavior

Checkboxes should appear initially.

### How to reproduce it (as minimally and precisely as possible)

Full source at link:

[uno-lvtest-master.zip](https://github.com/unoplatform/uno/files/8805098/uno-lvtest-master.zip)

### Workaround

Apart from scrolling, don't know

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI.Skia.Gtk Version="4.3.6"

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio Code

### IDE version

1.67.2

### Relevant plugins

Uno Platform 0.4.0

**Comment by ramezgerges** [comment]
@sarosigy Could you test it again using the latest version? I tried this on Skia.Gtk (although on Windows) and it doesn't seem to reproduce.

**Comment by sarosigy** [comment]
I tested it, it is OK with 4.9.42.
