### ISSUE TITLE
[Gallery][Skia.GTK] `TextBox`, `Binding` and `PasswordBox` - Typed text font color is displaying white in a light theme

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8942]
### Current behavior

![text color issue](https://user-images.githubusercontent.com/74563602/171181125-2d5f48ed-0f3b-4140-bdd7-5fc73b30ffdc.png)

https://user-images.githubusercontent.com/74563602/171182064-9c47ad87-05e0-4a5d-8042-7acb4539d362.mp4

### Expected behavior

![text color correct](https://user-images.githubusercontent.com/74563602/171181140-16e24e7b-ec2c-4d2f-8264-d96c1f332193.png)

https://user-images.githubusercontent.com/74563602/171181932-1746d16f-886a-448b-93ff-8242f76d4307.mp4

### How to reproduce it (as minimally and precisely as possible)

Launch the Uno.Gallry app on Skia.GTK.
Click on “TextBox” from the "Component" list.
Make sure that the gallery app is in light theme
Enter some text for the 'Default', 'Header', 'Multiline' textbox.
Notice that the typed text font color is displaying white in a light theme.

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by MartinZikmund** [comment]
@sakshi173 can you please check if this is still an issue or is fixed?

**Comment by sakshi173** [comment]
@MartinZikmund , I retested this issue and not able to reproduce it due to that closing it.
