### ISSUE TITLE
[Gallery][Skia.GTK] `Chip` - Inside the `XamlDisplay` control area, when scrolling up, all the chip moves to the left side and the chip gets invisible

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8947]
### Current behavior

![Image](https://github.com/unoplatform/uno/assets/74563602/5e0d4a13-5d22-4159-be1a-0a4d9248ac18)

https://user-images.githubusercontent.com/74563602/171275745-34beed72-edda-4981-b386-945512711c0d.mp4

### Expected behavior

The Chip inside the layout should not move when scrolling up and down.
https://user-images.githubusercontent.com/74563602/171276331-36c138eb-bd31-4f75-8855-f52d47803b54.mp4

### How to reproduce it (as minimally and precisely as possible)

1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Change theme from Day mode to Night mode.
3. Click/tap Burger Menu on the left top right.
4. click/tap "Chip" from the "Toolkit" list.
5. Click inside any chip XamlDisplay control area ( for example Filter)
6. Scroll up using a mouse, observe that all the chip moves to the left side and the chip gets invisible.

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by Marc-Antoine-Soucy** [comment]
So, basically, it seems like this bug is that when the items in a scrollview in SKIA do not take enough space, when you attempt to scroll, you just scroll the content there is out of bounds: 
You can see this here:
![SkiaScrollBug](https://github.com/unoplatform/uno/assets/90481654/c971c877-a42a-4d3e-bfe7-ac15dfeaa366)
![SkiaScrollBugVertical](https://github.com/unoplatform/uno/assets/90481654/82461c0b-3189-4bee-86e3-2421c9e02c73)
To reproduce the bug, all you need is a scrollview with content in it which is smaller than the space given by the scrollviewer. Here is the sample where I reproduced it with the latest nugets:

[BasicApp.zip](https://github.com/unoplatform/uno/files/11655792/BasicApp.zip)
All of the important code is in the MainPage.xaml:
```
<Page.Resources>
        <Style x:Key="HorizontalScrollViewerStyle" TargetType="ScrollViewer">
            <Setter Property="HorizontalScrollMode" Value="Auto" />
            <Setter Property="HorizontalScrollBarVisibility" Value="Auto" />
            <Setter Property="VerticalScrollMode" Value="Disabled" />
            <Setter Property="VerticalScrollBarVisibility" Value="Hidden" />
            <Setter Property="Margin" Value="0,10" />
        </Style>
    </Page.Resources>


    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        
        <ScrollViewer Style="{StaticResource HorizontalScrollViewerStyle}">
            <StackPanel Orientation="Horizontal" Spacing="8">

                <TextBlock Text="Hello, Uno platform!" FontSize="40" />

            </StackPanel>
        </ScrollViewer>
        
        <ScrollViewer Style="{StaticResource HorizontalScrollViewerStyle}" Grid.Row="1">
            <StackPanel Orientation="Horizontal" Spacing="8">

                <TextBlock Text="Hello, Uno platform! Does this still " FontSize="40" />

            </StackPanel>
        </ScrollViewer>
        
        <ScrollViewer Style="{StaticResource HorizontalScrollViewerStyle}" Grid.Row="2">
            <StackPanel Orientation="Horizontal" Spacing="8">

                <TextBlock Text="Hello, Uno platform! Does this still happpen when the " FontSize="40" />

            </StackPanel>
        </ScrollViewer>
        
        <ScrollViewer Style="{StaticResource HorizontalScrollViewerStyle}" Grid.Row="3">
            <StackPanel Orientation="Horizontal" Spacing="8">

                <TextBlock Text="Hello, Uno platform! Does this still happpen when the text is very long?" FontSize="40" />

            </StackPanel>
        </ScrollViewer>
    </Grid>
```

**Comment by jeromelaban** [comment]
@dr1rrb same here, will https://github.com/unoplatform/uno/pull/12428 help?

**Comment by sakshi173** [comment]
@Marc-Antoine-Soucy and @jeromelaban, similar type of issue is happening for SwipeControl. I am not sure its a defect or not?
If it is a defect then it is similar defect or required to create the separate defect for this. Please let me know your views.

https://github.com/unoplatform/uno/assets/74563602/a28b1a96-b455-4e3f-9f7c-67c8350cf73a

**Comment by silviuo** [comment]
https://github.com/unoplatform/uno/assets/10283398/33841137-5e43-4ecb-86ff-9dc126067d28

> @dr1rrb same here, will #12428 help?

I tried the code referenced above by Marc-Antoine in the dev/dr/skiaClip branch from PR #12428 and the issue still happens.

**Comment by dr1rrb** [comment]
> 
> > @dr1rrb same here, will #12428 help?
> 
> I tried the code referenced above by Marc-Antoine in the dev/dr/skiaClip branch from PR #12428 and the issue still happens.

Tested with my latest changes, and yes it's still failing. The issue is probably a layouting issue, not a rendering issue.

**Comment by sakshi173** [comment]
Verified this issue is fixed due to that closing it.
