### ISSUE TITLE
[Gallery][Skia.GTK]All controls- 'Official Documentation' text font color is displaying black in a dark theme and when click the link is not working.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8956]
### Current behavior

![official link issue](https://user-images.githubusercontent.com/74563602/171435326-585e631e-bb43-434a-9abd-946b4976fe16.png)

### Expected behavior

![official link correct](https://user-images.githubusercontent.com/74563602/171435960-dd41ce45-7572-4128-abd5-0fa2af7e01d9.png)

Uploading Uno Gallery - Google Chrome 2022-06-01 10-59-25.mp4…

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP.
2. Click/tap Burger Menu on the left top right. 
3. Click on the Light/Dark theme change toggle button.
4. Notice that the app is in Dark theme mode.
5. Open any control from the list. ( For example 'NavigationView')
6. Go to the 'Official documentation' link.
7. Notice the 'Official documentation' link is displayed in black color.
8. Click on the 'Official documentation' link.
9. Notice that not any new page is opening for the official document.

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by jeromelaban** [comment]
@mikernet does it look familiar? I don't recall seeing anything not working in the handling of hyperlinks colors, but maybe it's in your todo list.

**Comment by mikernet** [comment]
If you want to assign me to this issue I'll take care of it. I can also just reference this issue for the hyperlink hit testing PR as well.

**Comment by sakshi173** [comment]
@agneszitte-nventive , please check about this issue, as I discussed with you, now the link is not present for any controls of Gallery.

**Comment by agneszitte-nventive** [comment]
Thanks for the info @sakshi173, I will verify with the latest after my current priority tasks

**Comment by agneszitte-nventive** [comment]
@jeromelaban I just wanted to check for the part where @sakshi173 explain to me that the link is not present anymore for any controls on all platforms if I'm not mistaken.

**Comment by mikernet** [comment]
A fix for this is coming up soon, hang tight :)
