### ISSUE TITLE
Replace `Module.mono_bind_static_method` with `BINDING.bind_static_method`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#8959]
### Current behavior

The codebase currently uses `Module.mono_bind_static_method` which is obsolete. `BINDING.bind_static_method` should be used instead according to console logs.

### Expected behavior

No warnings in browser console.

### How to reproduce it (as minimally and precisely as possible)

Run Uno Gallery in a browser and open the developer console log.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
This issue is related to the use of the .NET 7 Wasm bootstrapper, as a result of an API change. We'll need to keep the compatibility with .NET 6 by adding a helper in Uno.UI to redirect to the proper method.

**Comment by jeromelaban** [comment]
This issue will be addressed differently with the support for .NET 7. (Using JSImport/JSExports)
