### ISSUE TITLE
[Gallery][Wasm/iOS/Android]Overview(Material) - The font size is small for the checkbox options.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8981]
### Current behavior

![Overview Checkbox issue](https://user-images.githubusercontent.com/74563602/172239121-42c43654-aafc-4e92-9c59-4c4b6038f52f.png)

### Expected behavior

![Overview Checkbox correct](https://user-images.githubusercontent.com/74563602/172241539-6763bba7-d00e-4497-845d-9e9b9503871f.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP.
2. Notice that the launching page is an "Overview" page.
3. Go to the 'Material' section.
4. Go to the 'Checkbox' option.
5. Notice that The font size for checkbox caption text is small as compared to the caption text for other controls.

### Affected platforms

iOS, Android, WebAssembly

**Comment by jeromelaban** [comment]
@Xiaoy312 @kazo0

**Comment by agneszitte-nventive** [comment]
> @Xiaoy312 @kazo0

I will take this one @jeromelaban as I started yesterday to fix some font issues not matching Uno Figma guidelines for RadioButton, ComboBox, and ToggleSwitch. I will be able to check for the other controls.

**Comment by agneszitte-nventive** [comment]
@sakshi173 The CheckBox is now using the correct font for Material M3 like RadioButton
Related PR for CheckBox: https://github.com/unoplatform/Uno.Themes/pull/794
cf. Uno Figma file for reference for the components with latest Material M3 styles
![image](https://user-images.githubusercontent.com/16295702/173619600-2cbda34b-cedd-475a-a703-96675e869903.png)
Closing this PR 
(cc @jeromelaban)
