### ISSUE TITLE
[Gallery][Wasm/Skia.GTK]ListView- The 'Foreground color' text font color is not changing for Dark theme mode.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8989]
### Current behavior

![Listview text issue](https://user-images.githubusercontent.com/74563602/172437101-9b487bf1-9366-4800-9a8e-3c6c05e1737f.png)

### Expected behavior

The 'Foreground Color' text font color should change as per the dark theme.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP.
2. Click/tap Burger Menu on the left top right.
3. Tap "Listview" from the "Features" list.
4. Click on the Light/Dark theme change toggle button.
5. Notice that the app is displaying in the Dark theme.
6. Go to the 'SelectedItem' section.
7. Observe that The 'Foreground color' text is the font is displaying in the black color and not changing as per the Dark theme mode.

### Affected platforms

WebAssembly, Skia (GTK on Linux/macOS/Windows)

**Comment by jeromelaban** [comment]
@Xiaoy312 @kazo0

**Comment by sakshi173** [comment]
Verified the issue is fixed for WASM, not able to test for skia(Last updated build was on 3rd June). Need to verify for Skia platform once receiving the latest build.
