### ISSUE TITLE
[Gallery][Android] TextBox and Binding(Material)- For 'Default' Section, the typed text is truncating from bottom.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8997]
### Current behavior

![Textbox issue‎- Photos](https://user-images.githubusercontent.com/74563602/172706480-32991697-73db-4059-8cf9-47dbf8b16342.png)

### Expected behavior

![Textbox correct‎](https://user-images.githubusercontent.com/74563602/172706524-686672c2-75e0-4026-a026-10c77e3a3a92.png)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app on Skia.GTK.
2. Click on “TextBox” from the "Component" list.
3. Enter some text for the 'Default' textbox.
4. Notice that the typed text is truncating from the bottom and the text 'Default is truncating from the top.

### Affected platforms

Android

**Comment by jeromelaban** [comment]
@agneszitte-nventive @kazo0

**Comment by agneszitte-nventive** [comment]
> @agneszitte-nventive @kazo0

@jeromelaban I will take this one and investigate
