### ISSUE TITLE
Changing a xaml file in the shared library does not trigger a wasm project rebuild

### ISSUE THREAD

**Issue by MarkStega** [unoplatform/uno#9]
I have a small project that I based on the Uno.Playground project. If I have the .Net server as the startup project, then make a change in a xaml file in the shared library, do a 'Ctrl-F5' to start without debugging, then the wasm project doesn't get rebuilt. Even just doing a build on that project results in an 'up to date' notification. I have to delete the bin directory in order to force a rebuild.

If I have the UWP project set as the startup project it gets rebuilt after a xaml file change

**Comment by jeromelaban** [comment]
This is a known issue for the change tracking, but in the case of the playground, it's simply misconfigured.

See here: https://github.com/nventive/Uno.Playground/blob/80322aec3d759d009f6a900bca4a07bc63ae6a62/Uno.UI.Demo.WASM/Uno.UI.Demo.WASM.csproj#L24 

You can point to the Xaml files coming from the shared project, and VS is going to honor that.

**Comment by ghuntley** [comment]
Closing this out as XAML Hot Reload is now in preview, check out https://platform.uno/announcing-uno-platform-2-0/ for more information.
