### ISSUE TITLE
Focus visual hint is not displayed on CheckBox and Button

### ISSUE THREAD

**Issue by TonyHenrique** [unoplatform/uno#90]
I noticed that on Web (EDGE) if we move focus to a Button or to a CheckBox using Keyboard TAB key, it does not display the Focus Visual Border / hint. On TextBox it works OK.

![uno_focus](https://user-images.githubusercontent.com/6307623/42340245-e549d0e4-8065-11e8-81fc-f5032be99fc4.png)

**Comment by TonyHenrique** [comment]
Just curiosity: Is this Focus hint (WebAssembly) too far to be fixed?

**Comment by yowl** [comment]
And ComboBox please

**Comment by jeromelaban** [comment]
Consolidating this issue with Focus Visuals support. https://github.com/unoplatform/uno/issues/3093
