### ISSUE TITLE
[Android] Resource generation fails when resw keys start with numbers or contains a '-' character

### ISSUE THREAD

**Issue by MakanWG** [unoplatform/uno#902]
## Current behavior
When a resource name starts by a number or contains a '-' the resource C# file generated by xamarin Android is full of unsuported variable names.

## Expected behavior
This should work without renaming all the problematic variables

## Minimal reproduction of the problem with instructions

*STEPS TO REPRODUCE*
Use a resw file to store strings. Add some ressources, and name some with just numbers.
Notice the build fails because of invalid variable names in the generated resources file.

## Environment

```
Nuget Package: Uno.UI

Package Version(s): 1.44.1

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [x] 2019 (version: )
- [x] for Mac (version: )

**Comment by ghuntley** [comment]
Resolved in https://github.com/unoplatform/uno/pull/903
