### ISSUE TITLE
[Gallery][MacOS Catalyst]ProgressRing, Elevated View- Margin on the right side is missing.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#9041]
### Current behavior

![progressring issue](https://user-images.githubusercontent.com/74563602/173440368-fb42873c-4332-48b6-bf41-f7890858fa53.png)

### Expected behavior

![progressring correct](https://user-images.githubusercontent.com/74563602/173440410-0e224deb-afde-4be4-8d9e-6911eb9830dc.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "Progress Ring/Bar" from the "Component" list.
4. Observe that for all ProgressRing and ProgressBar options the Margin is not present on the right side.

### Affected platforms

macOS

**Comment by agneszitte** [comment]
@jhanvi03 can you check on latest Gallery Canary if this issue is still present, please
