### ISSUE TITLE
[WASM] XAML setter converter binding build error

### ISSUE THREAD

**Issue by semenenkov** [unoplatform/uno#9050]
### Current behavior

Given VS 2019, create new UNO solution, leave only 3 projects: Shared, UWP and Wasm
Add some value converter:

```
    public class SomeConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, string language)
        {
            return (parameter ?? "").ToString();
        }

        public object ConvertBack(object value, Type targetType, object parameter, string language)
        {
            throw new NotImplementedException();
        }
    }
```
Use it in MainPage.xaml:

```
<Page
    x:Class="SetterConvertedBug.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:SetterConvertedBug"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Page.Resources>
        <local:SomeConverter x:Key="SomeConverter"/>
    </Page.Resources>

    <Grid>
        <TextBlock>
            <TextBlock.Resources>
                <Style TargetType="TextBlock">
                    <Setter Property="Text">
                        <Setter.Value>
                            <Binding Path="Whatever" Converter="{StaticResource SomeConverter}"/>
                        </Setter.Value>
                    </Setter>
                </Style>
            </TextBlock.Resources>
        </TextBlock>
    </Grid>
</Page>
```

Build.
UWP build is OK, Wasm build fails with error at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator.BuildBindingOption(XamlMemberDefinition m, INamedTypeSymbol propertyType) в C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\XamlGenerator\XamlFileGenerator.cs:line 5023

The same happens for inline binding declaration like                     
`<Setter Property="Text" Value="{Binding Path=Whatever, Converter={StaticResource SomeConverter}}"/>`
with and without converter parameter.

### Expected behavior

Build should pass

### How to reproduce it (as minimally and precisely as possible)

Steps are described in the Current behaviour, I am going also to attach sample project.

### Workaround

Not found for now

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

WebAssembly

### IDE version

VS 2019

**Comment by semenenkov** [comment]
[SetterConvertedBug.zip](https://github.com/unoplatform/uno/files/8900676/SetterConvertedBug.zip)

**Comment by jeromelaban** [comment]
This issue is likely related to https://github.com/unoplatform/uno/issues/4826

**Comment by MartinZikmund** [comment]
Closing in favor of #4826, copied the repro there for validation
