### ISSUE TITLE
[WPF] `NumberBox` steals focus and prevents editing `TextBox`

### ISSUE THREAD

**Issue by bstrother1** [unoplatform/uno#9051]
### Current behavior

Numberbox steals the focus from all other elements and prevents editing textboxes. Clicking inside the Numberbox and out temporarily fixes it before the focus is lost again. The sample project is reused so the second page is what I used to display the issue not the first. 

[ReactiveUIUnoSample.zip](https://github.com/unoplatform/uno/files/8901277/ReactiveUIUnoSample.zip)

### Expected behavior

For Numberbox not to steal focus. 

### How to reproduce it (as minimally and precisely as possible)

-Create Project
-Have Page with textboxes and a Numberbox 
-try to edit textbox
-get blank uneditable textbox

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

WPF: 
 PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" 
 PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" 
 PackageReference Include="ReactiveUI.Fody" Version="17.1.17" 
 PackageReference Include="ReactiveUI.Uno" Version="17.*" 
 PackageReference Include="Uno.UI.Skia.Wpf" Version="4.4.0-dev.239"
 PackageReference Include="Uno.UI.RemoteControl" Version="4.4.0-dev.241" Condition="'$(Configuration)'=='Debug'"

WPF.Host:
 PackageReference Include="Uno.UI.Skia.Wpf" Version="4.4.0-dev.239" 
 PackageReference Include="Uno.UI.RemoteControl" Version="4.4.0-dev.241" Condition="'$(Configuration)'=='Debug'"

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.0.4

### Anything else we need to know?

Loading the elements sometimes takes a while as well.

**Comment by bstrother1** [comment]
Does this need a better sample? Currently WPF build is unusable if you use Numberbox.

**Comment by ramezgerges** [comment]
This seems to be fixed. Let us know if it isn't.
