### ISSUE TITLE
Image name containing CA is not displayed

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#9053]
Related to https://github.com/unoplatform/nventive-private/issues/404

## Current behavior

Images that use CA without letters beside it, do not appear

## Expected behavior

Images should appear

## How to reproduce it (as precisely as possible)
Open the app

Sample:
[ImageDisplayPath.zip](https://github.com/unoplatform/uno/files/8903871/ImageDisplayPath.zip)

Output Debug:
Uno.Helpers.DrawableHelper[0]
      Couldn't find drawable with key: CA
Uno.Helpers.DrawableHelper[0]
      Couldn't find drawable with key: CA
Uno.Helpers.DrawableHelper[0]
      Couldn't find drawable with key: ca_Flag
Uno.Helpers.DrawableHelper[0]
      Couldn't find drawable with key: ca_Flag

[ImageView] Unable to find resource: 2131165184
[ImageView] android.content.res.Resources$NotFoundException: Resource ID #0x7f070000
[ImageView] 	at crc64122dcf5ad656876d.FrameworkElement.06-14 14:51:01.340 W/ImageView( 4267): 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:234)
[ImageView] 	at android.content.res.Resources.getDrawableForDensity(Resources.java:982)

## Repro rate

100%

## Impacted build / release (if info available)

- Uno.UI nuget package version (for Devs):
In the sample: 4.3.8 
In the project NFN: 3.11.9

## Affected platform(s):

- [x] iOS
- [x] Android
- [ ] ~~WebAssembly~~
- [ ] ~~MacOS~~
- [ ] Windows
- [ ] ~~Linux~~
- [ ] ~~Build tasks~~

## Visual Studio (for devs):

- [ ] 2022 (version: )

## Workaround possible ?

Add a letter before or after CA

**Comment by MartinZikmund** [comment]
Closing in favor of #9264
