### ISSUE TITLE
[Android/iOS] Using TemplateBinding in the Command parameter of a MenuFlyoutItem doesnt work

### ISSUE THREAD

**Issue by thierry-fortin1** [unoplatform/uno#9059]
### Current behavior

Using a TemplateBinding in the Command parameter of a MenuFlyoutItem, in the Style of a custom Control, doesnt work.
![menuflyoutitemtemplatebindingANDROID](https://user-images.githubusercontent.com/105242267/173900835-d244dfbb-6bcf-4513-b44a-e2bc89a8c240.gif)
TemplateBinding is used here so we can reuse this Style at multiple places in the code by giving a different command everytime.
![image](https://user-images.githubusercontent.com/105242267/173898625-ce76600e-5f5f-4a7b-bedb-e286466bdb70.png)
We use it here and give it the CustomCommand command we made in the logic Class.
![image](https://user-images.githubusercontent.com/105242267/173898566-a0158e55-0f0b-4c1b-a816-315d7ff6bcbc.png)
We see what our CustomCommand does, it modifies the page's TextBlock when the MenuFlyoutItem is clicked.
![image](https://user-images.githubusercontent.com/105242267/173902694-35b5fa36-9ecf-49af-b46a-f09ba6274544.png)
![image](https://user-images.githubusercontent.com/105242267/173903067-7413d209-3f00-4090-9cf9-62e4a34ac313.png)

### Expected behavior

Should do the same thing UWP currently does:
![menuflyoutitemtemplatebindingUWP](https://user-images.githubusercontent.com/105242267/173898965-2d359f63-2ad2-4de8-8a02-780b3a0d322e.gif)

### How to reproduce it (as minimally and precisely as possible)

Open the sample app.
Click the button.
Click the first MenuFlyoutItem (choice 1).
Notice there is text appearing above the button on UWP, but not iOS/Android.

### Workaround

Placing the MenuFlyout style (and its MenuFlyoutItems) directly in the Xaml page where it is used.
In this case, moving everything that is inside the ControlTemplate (Button -> Button.Flyout -> his 2 MenuFlyoutItem) directly inside the main grid of the app, so not using the custom control.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.UI.RemoteControl / Uno.WinUI.RemoteControl

### NuGet package version(s)

4.3.8

### Affected platforms

iOS, Android

### IDE

Visual Studio 2022

### IDE version

17.1.6

**Comment by jeromelaban** [comment]
Likely related to https://github.com/unoplatform/uno/issues/1621

**Comment by Xiaoy312** [comment]
fixed by #9452
