### ISSUE TITLE
[GTK] Expander breaking layout on expand

### ISSUE THREAD

**Issue by Cyroxin** [unoplatform/uno#9062]
### Current behavior

Layouting breaks when the Expander cannot show its expanded content after expanding. This causes the layout to break.

### Expected behavior

Layout should not break.

### How to reproduce it (as minimally and precisely as possible)

Either add the code shown in the video to the content of main page or use repro.
[Triggers.zip](https://github.com/unoplatform/uno/files/8918341/Triggers.zip)

https://user-images.githubusercontent.com/34924561/174059435-a897e606-7852-42d4-874f-785c3315ec46.mp4

### Workaround

Remove **\<ScrollViewer\>**

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

<details>
<summary>Repro:</summary>

Microsoft.Extensions.Logging Version="5.0.0" 
Microsoft.Extensions.Logging.Console Version="5.0.0"
Uno.WinUI.Skia.Gtk Version="4.4.0-dev.176"
Uno.WinUI.RemoteControl Version="4.4.0-dev.176"
Uno.UI.Adapter.Microsoft.Extensions.Logging Version="4.4.0-dev.176"

</details>

<details>
<summary>Original Project:</summary>

Microsoft.Extensions.Logging Version="5.0.0" 
Microsoft.Extensions.Logging.Console Version="5.0.0"
Uno.WinUI.Skia.Gtk Version="4.4.0-dev.261"
Uno.WinUI.RemoteControl Version="4.4.0-dev.261"
Uno.UI.Adapter.Microsoft.Extensions.Logging Version="4.4.0-dev.261"

</details>

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

17.3.0 Preview 1.1

### Anything else we need to know?

Not completely sure about this, but making the window a long vertical stripe without much width may cause the bug to not appear.

**Comment by MartinZikmund** [comment]
@Cyroxin can you please try this again on the preview packages that will be released later today? #11894 should fix this issue
