### ISSUE TITLE
[Skia] `CalendarDatePicker` `Header` Up/Down arrow and Month/Year do not work

### ISSUE THREAD

**Issue by bstrother1** [unoplatform/uno#9064]
### Current behavior

None of the header date moving elements on CalendarDatePicker work. Clicking does nothing. Working on UWP. Sample project is reused. Element is on first page. I only tested WPF and UWP. 

[ReactiveUIUnoSample.zip](https://github.com/unoplatform/uno/files/8919811/ReactiveUIUnoSample.zip)
 

### Expected behavior

Header Elements to navigate Calendar. 

### How to reproduce it (as minimally and precisely as possible)

-Create Project
-Add CalendarDatePicker element
-Try navigating through header 

### Workaround

n/a

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

WPF:
PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0"
PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0"
PackageReference Include="ReactiveUI.Fody" Version="17.1.17"
PackageReference Include="ReactiveUI.Uno" Version="17.*"
PackageReference Include="Uno.UI.Skia.Wpf" Version="4.4.0-dev.239"
PackageReference Include="Uno.UI.RemoteControl" Version="4.4.0-dev.241" Condition="'$(Configuration)'=='Debug'"

WPF.Host:
PackageReference Include="Uno.UI.Skia.Wpf" Version="4.4.0-dev.239"
PackageReference Include="Uno.UI.RemoteControl" Version="4.4.0-dev.241" Condition="'$(Configuration)'=='Debug'"

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.0.4

**Comment by ramezgerges** [comment]
This doesn't seem to reproduce for me. Can anyone else confirm?

**Comment by Youssef1313** [comment]
It can't reproduce as well. @bstrother1 Have you got a chance to test with latest Uno packages?
