### ISSUE TITLE
[Gallery][Wasm/Skia.Gtk] `Toggleswitch` (Material) - In dark theme, switch knob does not fully cover the right edge of the track for the ON state

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#9065]
### Current behavior

![toggleswitch issue1](https://user-images.githubusercontent.com/74563602/174116511-f8c1626a-933c-4e58-bbea-7e344d608b89.png)

### Expected behavior

![toggleswitch issue](https://user-images.githubusercontent.com/74563602/174116533-b77c021f-13fc-4c9d-96b7-cb42bf23f26b.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Make sure that the App is in dark theme mode.
4. Tap "Toggleswitch" from the "Component" list.
5. Go to the Material section.
6. Observe that the switch knob does not fully cover the right edge of the track for the ON state.

### Affected platforms

WebAssembly

**Comment by agneszitte-nventive** [comment]
Thanks @sakshi173 I will adjust it !

**Comment by Xiaoy312** [comment]
ON and OFF state:
![image](https://user-images.githubusercontent.com/2359550/175372451-7ef16c3a-36a6-4e36-bf08-789cc0eacd90.png)

**Comment by agneszitte-nventive** [comment]
@sakshi173 is this issue still reproducible lately please?

**Comment by sakshi173** [comment]
@agneszitte-nventive This issue is still present for ON state. below is the screenshot.
![toggleswitch issue](https://user-images.githubusercontent.com/74563602/215839294-426bec6f-ef55-46f0-b1e9-3a02dc437f00.png)

**Comment by agneszitte-nventive** [comment]
Thanks a lot fore the details @sakshi173 !

**Comment by agneszitte** [comment]
New ToggleSwitch Material 3 in progress
https://github.com/unoplatform/Uno.Themes/pull/1031
