### ISSUE TITLE
[Skia] `DataGrid` `VerticalScrollBar` inverted, slow, and jerky when scrolling with mouse

### ISSUE THREAD

**Issue by bstrother1** [unoplatform/uno#9068]
### Current behavior

In WPF the VerticalScrollBar is inverted (up is down and down is up), slow, and jerks when using a mouse. UWP does not do this. Attached project is reused from another ticket.

[DataGridResizeIncorrect.zip](https://github.com/unoplatform/uno/files/8921889/DataGridResizeIncorrect.zip)
 

### Expected behavior

VerticalScrollBar to function similarly to UWP's implementation. 

### How to reproduce it (as minimally and precisely as possible)

-Make Project
-Add Datagrid
-Enable VerticalScrollBar
-Try scrolling with mouse 

### Workaround

n/a

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

WPF:
PackageReference Include="Uno.UI.Skia.Wpf" Version="4.1.8"
PackageReference Include="Uno.UI.RemoteControl" Version="4.1.8" Condition="'$(Configuration)'=='Debug'" />
PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.1.8"
PackageReference Include="Uno.Microsoft.Toolkit" Version="7.1.11"
PackageReference Include="Uno.Microsoft.Toolkit.Uwp" Version="7.1.11"
PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI" Version="7.1.11"
PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls" Version="7.1.11"
PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid" Version="7.1.11"
PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.Layout" Version="7.1.11"

WPF Host:
PackageReference Include="Uno.UI.Skia.Wpf" Version="4.1.8"
PackageReference Include="Uno.UI.RemoteControl" Version="4.1.8" Condition="'$(Configuration)'=='Debug'"
PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.1.8"

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.0.4

### Anything else we need to know?

Still occurs with latest dev release.

**Comment by heulendoch** [comment]
Having the same issue. The required rendering time of a datagrid in wasm or anroid is really high.

**Comment by lld1995** [comment]
What a serious problem....

**Comment by ramezgerges** [comment]
Is this still reproducing on 5x? I couldn't get the repro to work for some reason but trying with a new uno app, everything seems to be working. Scrolling is not inverted. It seems to be a little bit jittery when scrolled quickly on WASM, but that's it. @bstrother1  can you please try again and update the issue?
