### ISSUE TITLE
OpenGL support detection fails on VMWare

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#9099]
_opened from https://github.com/unoplatform/uno/discussions/9097_

I built the basic sample Uno Platform app with Visual Studio 2022 on Windows.  I built for Windows and Skia.Gtk, and ran both successfully from the IDE.  After publishing each, I ran the win-x64 version from the published folder.  I copied the linux-x64 folder to Ubuntu (22.04), and tried to run it there.  What I got was:

`shaw@ubuntu22:~/Desktop/linux-x64$ ./Uno.Skia.Gtk`
`nullptr GL version string.Marshaling render signal`
`GLIB UNHANDLED EXCEPTIONSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.`
 `---> System.NotSupportedException: OpenGL is not supported in this system`
`   at Uno.UI.Runtime.Skia.OpenGLRenderSurface.TryBuildGRContext()`
`   at Uno.UI.Runtime.Skia.GLRenderSurfaceBase.UnoGLDrawingArea_Render(Object o, RenderArgs args)`
`   --- End of inner exception stack trace ---`
`   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span``1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)`
`   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)`
`   at System.Delegate.DynamicInvokeImpl(Object[] args)`
`   at System.Delegate.DynamicInvoke(Object[] args)`
`   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)`
`   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)`

I verified:
`cshaw@ubuntu22:~/Desktop/linux-x64$ glxinfo | grep "OpenGL version"`
`OpenGL version string: 4.1 (Compatibility Profile) Mesa 22.0.1`

**Comment by ChrisShawK2** [comment]
...and, that did the trick (for me, anyway!).
Thanks!

**Comment by zipgenius** [comment]
I get the same error in WSL2 Ubuntu-20.04 (Windows 11). Installing mesa-utils and libgl1-mesa-glx didn't solve for me.

**Comment by jeromelaban** [comment]
> I get the same error in WSL2 Ubuntu-20.04 (Windows 11). Installing mesa-utils and libgl1-mesa-glx didn't solve for me.

On WSL2, the automatically selected backend should be OpenGL ES. Can you try with :

```csharp
host.RenderSurfaceType = RenderSurfaceType.OpenGLES;
```

Also, can you provide the logs you're seeing?
