### ISSUE TITLE
Pointer issues with MUX `NavigationViewItems`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#9112]
### Current behavior

Under Skia (and potentially other platforms) the MUX `NavigationViewItem` causes some weird pointer behavior issues.

### Expected behavior

Should not fail.

### How to reproduce it (as minimally and precisely as possible)

1. Open `HierarchicalNavigationViewMarkup` sample under `NavigationView` section of Samples app
2. Hover over items
3. **Observe the icons jump around to left and right**
4. Open items using "collapse/expand" arrow
5. **Notice the items sometimes fail to expand on first try
6. Observe debug console
7. **Notice many Gesture- and Pointer-related exceptions.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen)

**Comment by MartinZikmund** [comment]
This might be fixed, can someone confirm please?

**Comment by ramezgerges** [comment]
Items are still failing to expand until I select something first.
