### ISSUE TITLE
[Gallery]Button(Fluent)-'Disabled Back button' is not disabled.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#9117]
### Current behavior

![Button issue](https://user-images.githubusercontent.com/74563602/175371896-3553e694-c0bb-4867-9a7e-a7d926ef32bd.png)

https://user-images.githubusercontent.com/74563602/175368707-f44a079a-c927-4b7e-bb0c-f46c5b840b69.mp4

### Expected behavior

![Button Correct](https://user-images.githubusercontent.com/74563602/175371959-9919a54d-c630-4539-ad74-311b4ba54231.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Click on “Buttons” from the "Component" list.
3. Go to the 'Fluent' section.
4. Go to the 'Back Button' section.
5. Click on the 'Disabled Back button'.
6. Notice that the 'Disabled Back button' is not disabled.

### Affected platforms

iOS, Android, WebAssembly, Skia (GTK on Linux/macOS/Windows)

**Comment by Xiaoy312** [comment]
bit of misunderstanding/confusion here
what is listed there are NavigationBackButtonNormalStyle+NavigationBackButtonSmallStyle, and neither of them is disabled
which goes against the expectation sets from previous examples where you have a enabled button followed by a dsiabled button
