### ISSUE TITLE
VSIX template is not setting the Mobile project as deployable

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#9120]
_Originally posted by @joer33304 in https://github.com/unoplatform/uno/discussions/9096_

I am still in the super simple test phase and still only have problems :( I created a new solution from the template and added the code from the UWP data grid example. XAML starts and shows the grid. Android starts the emulator and shows just the home screen.

I created a second solution with no code changes and droid shows hello world.

I went back to the non working solution and now when I start up the emulator it also shows hello world and not the grid !

I cant find any HOWTO for the mobile stuff. I am especially also interested in what needs to be done to get an app to run on iPhone. Are there any resources and why is my droid app not showing ?

**Comment by joer33304** [comment]
Jerome, as mentioned in my last post, I don't think this is an UNO bug. I did remove the mobile project from the solution to test wasm alone and then re-added. It kind of makes sense that the solution losses the deploy when removing the mobile app and does not automatically re-add it.

**Comment by jeromelaban** [comment]
Thanks @joer33304! I opened it because I recall someone mentioning it as well on discord a while back, so we'll investigate quickly to see if there's nothing fishy.

**Comment by jeromelaban** [comment]
This is now fixed in Uno 4.5.
