### ISSUE TITLE
Uno.UI fails to generate source when LangVersion = "10.0" in a netstandard2.0 library

### ISSUE THREAD

**Issue by mrlacey** [unoplatform/uno#9130]
### Current behavior

In a library project with the TargetFramework of "netstandard2.0", source files are not generated by Uno.UI when the C# language version is set to "10.0", but it does work for other values that should be treated the same (e.g. "latest" and "default")

### Expected behavior

"10.0" should be correctly recognized as a valid langVersion and treated as such.

Also,
If code generation fails it should not do so quietly. Warnings or (preferably) errors should be logged when something fails.

### How to reproduce it (as minimally and precisely as possible)

A repro project is available at https://github.com/mrlacey/UnoLangVersionIssue

- Open the project. (This is netstandard2.0 library that includes a single UserControl and a reference to `Uno.UI`)

- Edit the `UnoLangVersionIssue.csproj` file.

- Set the `LangVersion`  to "**latest**"; build the project; Show all files in Solution Explorer; see that files are generated.
- Set the `LangVersion`  to "**10.0**"; clean and rebuild the project; see that **no** files are generated.

### Workaround

It's possible to use a value that is supported but this was discovered as part of an attempt to have a single C# language version defined for an entire solution. This is to aid stability and future maintenance.
That a valid value doesn't work here means future potential support and maintenance challenges.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI 4.2.6 (latest non-prerelease release)

### Affected platforms

Build tasks

### IDE

Visual Studio 2022

### IDE version

17.2.3

### Relevant plugins

n/a

### Anything else we need to know?

This was discovered as part of work done for the Windows Community Toolkit and affects projects being worked on there.

A `LangVersion` of "**10**" (i.e. no minor version number part) does enable the expected files to be generated. But this is not the correct string value for the version. It should be "**10.0**"

**Comment by jeromelaban** [comment]
Thanks for the report! This [has been fixed](https://github.com/unoplatform/uno/blob/master/src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props#L11-L19) in Uno 4.3, where the version detection was incorrectly computed.

**Comment by mrlacey** [comment]
After updating to 3.8 I don't get any files generated under the "g" directory with any `LangVersion`.
This is also the case for 4.3.5, 4.3.6, and 4.4.0-dev.345

**Comment by jeromelaban** [comment]
Not getting any file in the `g` folder is expected, as the in-roslyn generators kick in. What do you see failing after upgrading?

**Comment by mrlacey** [comment]
Closing as due to a misinformed expectation that an alternative approach has now been found for.
