### ISSUE TITLE
[iOS][macOS] Incorrect computation for `LogicalToPhysicalPixels`

### ISSUE THREAD

**Issue by spouliot** [unoplatform/uno#9131]
### Current behavior

Given a `CGRect` of `{{X=451.5,Y=1865,Width=182,Height=30}}`

The current code returns `{{X=451,Y=1865,Width=182,Height=30}}`

Which I, like `CGRectIntegral`, believe to be incorrect 😄 

While reducing `X` to `451` is correct, it requires increasing the `Width` to cover for the half-pixel decrease of `X`.

That _temporarily_ makes `Width == 182.5` and, _integrally_, it should become `183` to fully cover the rectangle.

### Expected behavior

Given a `CGRect` of `{{X=451.5,Y=1865,Width=182,Height=30}}`

`CGRectIntegral` [1] returns `{{X=451,Y=1865,Width=183,Height=30}}`

### Anything else we need to know?

Was there a reason not to use the `CGRectIntegral` [1] API ? Scaling ?

I have not (yet) done any benchmark to see if the managed version is faster (which might be another reason). The current implementation does not show up inside Dope (even if used) so it's not AFAIK a performance (but a correctness) issue.

[1] Inside Xamarin SDK it exists as an extension method of `CGRect` called `Integral`.

**Comment by spouliot** [comment]
Another issue given a `CGRect` of `{{X=423.5,Y=741,Width=182,Height=30}}`

The current code returns `{{X=423.5,Y=741,Width=182,Height=30}}` where `X` is not an integral value. That's because all values are divided by `MainScreenScale` and, on my 4k monitor that's `2`.

`CGRectIntegral` returns `{{X=423,Y=741,Width=183,Height=30}}` which again (cutting `X` and applying it toward `Width`) seems to be correct.

**Comment by jeromelaban** [comment]
It's very likely an oversight, mostly about not knowing about `CGRectIntegral` :) This is likely introducing grid snapping errors that we may have missed or worked around overtime. Good catch!

**Comment by spouliot** [comment]
My bad, I should have added more context 😄

The mention of `CGRectIntegral` comes from the source code comments.

https://github.com/unoplatform/uno/blob/82ad32df152c601e14b0dc0f0e94b60151185be0/src/Uno.UI/Extensions/ViewHelper.iOSmacOS.cs#L131-L140

which lead me to believe it was used in earlier revision of the code - but before it was imported to the open source repo 4 years ago.

It's possible this was changed to allow some additional adjustments as this field is being used by the helper methods

https://github.com/unoplatform/uno/blob/82ad32df152c601e14b0dc0f0e94b60151185be0/src/Uno.UI/Extensions/ViewHelper.iOSmacOS.cs#L37


It could also be that the `0.5` values are acceptable for Retina display (at least 2x, not 3x). The URL from the comments is not available anymore but still accessible with the [wayback machine](https://web.archive.org/web/20161023184014/https://markpospesel.wordpress.com/2013/02/27/cgrectintegral/). TL&DR a 2x display would be pixel perfect on half pixels.


Are you able to do `git blame` on the older (pre-import) repo to see the reason why the comments and code does not match ?

Based on this I can either do a PR with `CGRectIntegral` or fix the code. In fact the code is not really bad (depending on the expected result) but it kind of assume the rect is defined as two points instead of a point with the width and height of the rectangle.

**Comment by jeromelaban** [comment]
So I dug a bit the change from 2018, and the original code was added with the comment "Border aligned bottom adds a 1 pixel line on iOS" and the previous version was:

```csharp
return new CGRect
(
  (nfloat)Math.Floor(size.X * MainScreenScale) / MainScreenScale,
  (nfloat)Math.Floor(size.Y * MainScreenScale) / MainScreenScale,
  (nfloat)Math.Ceiling(size.Width * MainScreenScale) / MainScreenScale,
  (nfloat)Math.Ceiling(size.Height * MainScreenScale) / MainScreenScale
);
```

And this was also added at that time:

```csharp
		private static double _rectangleRoundingEpsilon = 0.05;
		private static double _scaledRectangleRoundingEpsilon = _rectangleRoundingEpsilon * MainScreenScale;
		/// <summary>
		/// This is used to correct some errors when using Floor and Ceiling in LogicalToPhysicalPixels for CGRect.
		/// </summary>
		public static double RectangleRoundingEpsilon
		{
			get { return _rectangleRoundingEpsilon; }
			set
			{
				_rectangleRoundingEpsilon = value;
				_scaledRectangleRoundingEpsilon = value * MainScreenScale;
			}
		}
```

**Comment by spouliot** [comment]
Thanks for digging this up 😄 That's quite interesting 🤔

The first issue I mentioned means getting too short (by a pixel) and the code was updated to avoid an extra line... so I think they are unrelated issues. As such the use of `CGRectIntegral` would not help.

The 2nd one is likely expected, when scaling over 1x, and also preclude the use of `CGRectIntegral`. I guess the comments could be updated to include this extra bit of information.

I'll do a PR to fix this _new_ issue and I trust the tests to pick up the changes - some should be different and better.
