### ISSUE TITLE
WASM Items arrange 0,0,0,0 by a panel stays visible

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#914]
## I'm submitting a...
- Bug report

## Current behavior
Items arranged 0,0,0,0 are visible

## Expected behavior
They are hidden

## Minimal reproduction of the problem with instructions
https://github.com/nventive/calculator/pull/35

## Environment
Nuget Package: Uno.UI
Package Version(s): 1.45.0.dev.1550

Affected platform(s):
```
- [?] iOS
- [?] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks
```

Visual Studio: _irrelevant_
Relevant plugins: _none_

**Comment by carldebilly** [comment]
The patch [has been reverted recently](https://github.com/unoplatform/calculator/commit/166e873c773dd6938239df72c6b7d846d31d9e9c) because the problem is no longer valid.

FIXED / NO REPRO.
