### ISSUE TITLE
[WASM] ms-appx:// fonts are not parsed properly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#915]
## I'm submitting a...
- Bug report

## Current behavior
A font defined as follows:
```

## Expected behavior
<!-- Describe what the desired behavior would be. -->


## Minimal reproduction of the problem with instructions
<!--
For bug reports please provide a *MINIMAL REPRO PROJECT* and the *STEPS TO REPRODUCE*
-->


## Environment
<!-- For bug reports Check one or more of the following options with "x" -->

```
Nuget Package:

Package Version(s):

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
I have hit this thing when working on my app so I will fix it

**Comment by MartinZikmund** [comment]
Done.
