### ISSUE TITLE
[macOS] Dead code inside FrameworkElement.NeedsLayout setter

### ISSUE THREAD

**Issue by spouliot** [unoplatform/uno#9155]
### Current behavior

There's a _dead_ block of code

```csharp
if (ShouldInterceptInvalidate)
{
	return;
}
```

inside macOS's `FrameworkElement.NeedsLayout` property setter.

https://github.com/unoplatform/uno/blob/dfc340bd5a3ccef32623a42e3e53c2fdc743f1f8/src/Uno.UI/UI/Xaml/FrameworkElement.macOS.cs#L23-L37

That code was added inside https://github.com/unoplatform/uno/commit/1c3541bd5af62026d7a50b09eb5156502ecb0d11#diff-ec94c6881e2a58594eec363b67cdce52831deda5d60e7c24dfe1f1ceaf3f1e50

and became dead code inside
https://github.com/unoplatform/uno/commit/c8f9917899189ed9e409d4895ae44d6781335442

### Expected behavior

It should not be there... but it might need to be somewhere else as it looks like an optimization.

https://github.com/unoplatform/uno/blob/dfc340bd5a3ccef32623a42e3e53c2fdc743f1f8/src/Uno.UI/UI/Xaml/FrameworkElement.macOS.cs#L17-L21

### Affected platforms

macOS

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
