### ISSUE TITLE
[MacOS] Datagrid stops application from building Window

### ISSUE THREAD

**Issue by bstrother1** [unoplatform/uno#9161]
### Current behavior

Currently On Mac making a datagrid quietly kills the application. It doesn't crash but the Window does not appear even though the application shows as running. 

Note: Run from terminal in release mode as the build doesn't include the debug mode fix and running in visual studios causes various issues. 

[TestingDatagrid.zip](https://github.com/unoplatform/uno/files/9003752/TestingDatagrid.zip)

### Expected behavior

Datagrid to display in Window.

### How to reproduce it (as minimally and precisely as possible)

-Create Project
-Add Datagrid
- Run In project folder: dotnet build -c Release TestingDatagrid.Mobile -t:Run -f net6.0-macos
- App will launch but no Window will show

### Workaround

n/a

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

PackageReference Include="Uno.UI" Version="4.4.0-dev.302" 
PackageReference Include="Uno.UI.RemoteControl" Version="4.4.0-dev.302" Condition="'$(Configuration)'=='Debug'" 
PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.4.0-dev.302" 
PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" 
PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0"
PackageReference Include="Uno.Microsoft.Toolkit" Version="7.1.11" 
PackageReference Include="Uno.Microsoft.Toolkit.Uwp" Version="7.1.11" 
PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI" Version="7.1.11" 
PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls" Version="7.1.11" 
PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid" Version="7.1.11" 
PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.Layout" Version="7.1.11" 
PackageReference Include="ReactiveUI.Fody" Version="18.2.5"
PackageReference Include="ReactiveUI.Uno" Version="17.1.50" 
PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0"
PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" 
PackageReference Include="Splat.Microsoft.Extensions.DependencyInjection" Version="14.3.4"

### Affected platforms

macOS

### IDE

Visual Studio 2022

### IDE version

17.3 Preview (17.3 build 1038)

**Comment by jeromelaban** [comment]
Thanks for the report. Can you try downgrading to 7.1.10 for the DataGrid ?

**Comment by bstrother1** [comment]
> Thanks for the report. Can you try downgrading to 7.1.10 for the DataGrid ?

PackageReference Include="Uno.Microsoft.Toolkit" Version="7.1.10"
PackageReference Include="Uno.Microsoft.Toolkit.Uwp" Version="7.1.10"
PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI" Version="7.1.10"
PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls" Version="7.1.10"
PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid" Version="7.1.10"
PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.Layout" Version="7.1.10"

Gives same issue. Builds but Window does not display.

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
