### ISSUE TITLE
Setting AutomationId cause build error with Skia.wpf project

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#9167]
### Current behavior

Adding "AutomationProperties.AutomationId" attached property to an element prevents the MyProject.Skia.Wpf project (single project using latest unoapp template) from building. 

### Expected behavior

Adding AutomationId should not cause build error

### How to reproduce it (as minimally and precisely as possible)

- install 4.5.0 uno templates (`dotnet new --install Uno.ProjectTemplates.Dotnet::4.4.5`)
- create new application (`dotnet new unoapp -o MyAutomationApp`)
- open MyAutomationApp in VS
- add Button to MainPage with AutomationId set (eg `<Button Content="Test" AutomationProperties.AutomationId="MyButton" />`)
- build error:
1>C:\temp\MyAutomationApp\MyAutomationApp.Skia.WPF\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_f3607c1d478131166c9ca095e3d98ebc.cs(92,78,92,80): error CS1503: Argument 1: cannot convert from 'Microsoft.UI.Xaml.Controls.Button' to 'System.Windows.DependencyObject'

### Workaround

Remove the AutomationId or use not_skia prefix eg not_skia:AutomationProperties.AutomationId="SecondPageButton" - this means the AutomationId is there for ui tests etc

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno 4.5.0

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

Version 17.3.0 Preview 2.0

**Comment by bstrother1** [comment]
This is also happening with multi head projects. In addition Visual Studio claims AutomationId is not attachable to element type in the xaml.
