### ISSUE TITLE
[Skia, WASM, Android, iOS?, MAC?] ListVIew IsMultiSelectCheckBoxEnabled=false shows checkbox while WinUI doesn't

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#9192]
### Current behavior

Shows multiselection checkbox when selection mode is multiple (or extended)
![ujt3](https://user-images.githubusercontent.com/6670150/176859904-fa5e9ce4-7fb0-4183-b955-00fc6476445d.jpg)

### Expected behavior

Checkbox is hidden

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

iOS, Android, WebAssembly, Skia (WPF), Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

Preview 2.0

**Comment by MartinZikmund** [comment]
Closing in favor of #8941
