### ISSUE TITLE
Update Uno.SourceGeneration to NET 7

### ISSUE THREAD

**Issue by ebariche** [unoplatform/uno#9207]
error : Unable to find Uno.SourceGeneration.Host.dll (in C:\Users\x\
.nuget\packages\uno.sourcegenerationtasks\4.0.2\build\Dev15.0\netcoreapp3.1\..\..\..\..\Uno.SourceGeneration.Host\bin\Release\net7 or C:\Users\x\.nuget\packages\uno.sourcegenerationtasks\4.0.2\build\De
v15.0\netcoreapp3.1\..\..\host\net7

**Comment by spouliot** [comment]
The nuget package for `uno.sourcegenerationtasks` does not have a `net7` directory.

```bash
$ l ~/.nuget/packages/uno.sourcegenerationtasks/4.0.2/build/host/                                                                                                           total 0
drwxr-xr-x   7 poupou  staff   224B  5 Jul 11:39 .
drwxr-xr-x   5 poupou  staff   160B 14 Apr 20:28 ..
drwxr-xr-x  72 poupou  staff   2.3K 14 Apr 20:28 net472
drwxr-xr-x  59 poupou  staff   1.8K 14 Apr 20:28 net5
drwxr-xr-x  58 poupou  staff   1.8K 14 Apr 20:28 net6
drwxr-xr-x  61 poupou  staff   1.9K 14 Apr 20:28 netcoreapp3.1
```

For some reasons (need to find out why) the build does not try to fallback to the earlier `net6` binaries.

A quick workaround (at least on macOS/linux) is to create a `net7` symlink to the packaged code inside `net6`.

```bash
$ ln -s ~/.nuget/packages/uno.sourcegenerationtasks/4.0.2/build/host/net6 ~/.nuget/packages/uno.sourcegenerationtasks/4.0.2/build/host/net7                                 

$ l ~/.nuget/packages/uno.sourcegenerationtasks/4.0.2/build/host/                                                                                                           total 0
drwxr-xr-x   7 poupou  staff   224B  5 Jul 11:39 .
drwxr-xr-x   5 poupou  staff   160B 14 Apr 20:28 ..
drwxr-xr-x  72 poupou  staff   2.3K 14 Apr 20:28 net472
drwxr-xr-x  59 poupou  staff   1.8K 14 Apr 20:28 net5
drwxr-xr-x  58 poupou  staff   1.8K 14 Apr 20:28 net6
lrwxr-xr-x   1 poupou  staff    77B  5 Jul 11:39 net7 -> /Users/poupou/.nuget/packages/uno.sourcegenerationtasks/4.0.2/build/host/net6
drwxr-xr-x  61 poupou  staff   1.9K 14 Apr 20:28 netcoreapp3.1

$ dotnet build                                                                                                                                                              MSBuild version 17.3.0-preview-22306-01+1c045cf58 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/usr/local/share/dotnet/sdk/7.0.100-preview.5.22307.18/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/poupou/Downloads/UnoNet7/UnoNet7/UnoNet7.Wasm/UnoNet7.Wasm.csproj]
  UnoNet7.Wasm -> /Users/poupou/Downloads/UnoNet7/UnoNet7/UnoNet7.Wasm/bin/Debug/net7.0/UnoNet7.Wasm.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:06.20
```

For Windows copying the `net6` directory to a `net7` directory should also workaround the issue.

Keep in mind that refreshing the NuGet will overwrite the workaround and it will need to be reapplied again.

**Comment by spouliot** [comment]
The problem is that the dotnet version is hardcoded to the currently executing runtime.

```csharp
private static string GetNetCoreHostVersion()
	// .NET Core 3.1.3
	// .NET 5.0.0-preview.6.20305.6
	=> RuntimeInformation.FrameworkDescription.StartsWith(".NET Core") ? "netcoreapp3.1" : "net" + RuntimeInformation.FrameworkDescription.Replace(".NET ", "")[0];
```

https://github.com/unoplatform/Uno.SourceGeneration/blob/d859a37defd43065b215a0d2dd3f68f6821e5064/src/Uno.SourceGeneratorTasks.Dev15.0/Tasks/SourceGenerationTask.cs#L384-L387

If you run `dotnet build` it will use the TFM inside the `.csproj` to select a runtime. If that's 

```xml
   <TargetFramework>net7.0</TargetFramework>
```

then it will look for a `net7` directory for loading `Uno.SourceGeneration.Host.dll`.

Since the `4.0.2` nuget does not ship a `net7` specific binary then `Uno.SourceGeneration.Host.dll` is not found and the following error is reported

```
/Users/poupou/.nuget/packages/uno.sourcegenerationtasks/4.0.2/build/netstandard1.0/Uno.SourceGenerationTasks.targets(134,2): Unable to find Uno.SourceGeneration.Host.dll (in /Users/poupou/.nuget/packages/uno.sourcegenerationtasks/4.0.2/build/Dev15.0/netcoreapp3.1/../../../../Uno.SourceGeneration.Host/bin/Release/net7 or /Users/poupou/.nuget/packages/uno.sourcegenerationtasks/4.0.2/build/Dev15.0/netcoreapp3.1/../../host/net7) [/Users/poupou/Downloads/UnoNet7/UnoNet7/UnoNet7.Wasm/UnoNet7.Wasm.csproj]
```

The solution is either

* change the logic so the current (for the nuget) directory is used when a newer version is requested. That would be `net6` in this case; or
* ship a nuget that has a `net7` directory

The later is problematic since the same issue will come back for `net8` and every new major version of `dotnet`. Beside the yearly need for updates the size of the nuget will explode _likely_ needlessly.

**Comment by spouliot** [comment]
There's already a `<RollForward>LatestMajor</RollForward>` inside the 4.0.2 nuget (added in https://github.com/unoplatform/Uno.SourceGeneration/commit/51933c74c3d7f4e6dd59054a75592e9ae15aa3c6) so capping to `net6` until a newer binary is required sounds like it was the _original_ idea.
