### ISSUE TITLE
[iOS] Changing `TabBar` visual state to closed leaves a black background

### ISSUE THREAD

**Issue by arianeleonard** [unoplatform/uno#9214]
### Current behavior

When changing the TabBar visualstate to closed, a black background stays visible in it's place instead of being collapsed on iOS.

### Expected behavior

When changing the TabBar visualstate to closed, it should be translated to the bottom of the screen and it's visibility should change to collapsed.

### How to reproduce it (as minimally and precisely as possible)

1. Launch repro sample: [BottomBar.zip](https://github.com/unoplatform/uno/files/9047739/BottomBar.zip)
2. Skip the tutorial pages and login with any email and password.
3. Once logged in, select the "Profile" bottom bar button.
4. On the profile page, select the "Change password" button.
5. Notice that there is a black space where the bottom bar used to be.

### Workaround

1. Remove grid rows in Shell.xaml
2. Add safe area row to pages corresponding to the bottom bar buttons
3. Define safe area height in code behind.

Sample with workaround: 
[UnoApplicationTemplate.zip](https://github.com/unoplatform/uno/files/9047804/UnoApplicationTemplate.zip)
Branch with workaround:
https://github.com/nventive/UnoApplicationTemplate/tree/dev/arle/FixTabBar

### Works on UWP/WinUI

Yes

### Environment

Uno.UI

### NuGet package version(s)

Uno.UI : 4.2.6 (Also tested with 4.4.13, the issue is still present)

### Affected platforms

iOS

### IDE

Visual Studio 2022

**Comment by kazo0** [comment]
I seem to be able to get the black bar to display even on the older builds of the application template where `MenuRadioButton` was being used:
![bottombardadjokes](https://user-images.githubusercontent.com/4793020/177396794-a483b184-7ff2-48e0-ad00-a99d4a5731b0.gif)

**Comment by arianeleonard** [comment]
Oh, then the issue isn't with TabBar, but it seems like it is with the menu itself when it is collapsed and/or translated.

**Comment by francoistanguay** [comment]
Will you be able to either update the issue with the proper description once you've eliminated some components from the repro?

**Comment by MartinZikmund** [comment]
@arianeleonard Is this still relevant or was the issue fixed?
