### ISSUE TITLE
Unable to build WinUI-SkiaSharp on Windows project

### ISSUE THREAD

**Issue by beto-rodriguez** [unoplatform/uno#9216]
### Current behavior

I am not sure if this issue belongs here (or maybe in SkiaSharp).

I am creating a new Uno app (Uno.WinUI 4.4.13) it works properly until I add a reference to SkiaSharp (https://nuget.info/packages/SkiaSharp.Views.Uno.WinUI/2.88.1-preview.79).

I am not able to compile the project for the .Windows (WinUI) project but it works on the rest on the platforms.

It seems that the SkiaSharp package is missing the binaries at `lib/net5.0-windows10.0.18362.0`, could this be the reason for the issue?

Am I missing something else?

### Expected behavior

Compile SkiaSharp on WinUI project

### How to reproduce it (as minimally and precisely as possible)

1. Create a new app (WinUI 4.4.13)
2. Compile the windows project and it works
3. Add SkiaSharp and and Skia view and the Windows project will not compile any more.

```
<Page
    x:Class="UnoSkiaSharp.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:UnoSkiaSharp"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:views="using:SkiaSharp.Views.Windows"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <views:SKXamlCanvas x:Name="canvas" Grid.Row="1" PaintSurface="OnPaintCanvas" />
    </Grid>
</Page>
```

```
 public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }

        private void OnPaintCanvas(object sender, SKPaintSurfaceEventArgs e)
        {
            using var p = new SKPaint { Color = SKColors.Blue };
            e.Surface.Canvas.DrawText("hola", new SKPoint(100, 100), p);
        }
    }
```

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.4.13

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

17.3.0 Preview 2.0

### Anything else we need to know?

I have tried to update to previews of `Uno.WinUI` without success.

**Edit** 

The error message is: `The type or namespace name 'Windows' does not exist in the namespace 'SkiaSharp.Views' (are you missing an assembly reference?)`

**Comment by francoistanguay** [comment]
In an Uno solution, Uno isn't present on WinUI. Therefore I would assume that for your WinUI head, you need the SkiaSharp Views for WinUI, not the SkiaSharp Views for Uno

**Comment by beto-rodriguez** [comment]
Thanks for the reply, I noticed that there is a new SkiaSharp package for Uno-WinUI, I am trying to make it work without success.

This is a really simple repo https://github.com/beto-rodriguez/UnoAppSkia, I just created a new Uno app using your templates, then added a reference to `SkiaSharp.Views.Uno.WinUI` and I am not able to build the Windows project, notice it builds and runs the Mobile the GTK and the Wasm projects.

Does my repo reproduce the issue?

**Comment by francoistanguay** [comment]
Sorry, I meant I think for the WinUI head, you need to reference https://nuget.info/packages/SkiaSharp.Views.WinUI/2.88.0 , not the Uno.WinUI one.

In other words. You always need the WinUI version of a package for the WinUI head and the Uno version for all other heads.

**Comment by beto-rodriguez** [comment]
Thanks! now it works.

I am just curious will this be the way? is it in the plans to make it work like it used to in the UWP version?

I mean it would be nice to just install a NuGet package for the solution instead of a platform specific package.

**Comment by francoistanguay** [comment]
Pretty sur UWP was exactly the same :) And yes, UWP/WinUI packages aren't authored by Uno, therefore they will also be separate from Uno-specific "bridge" packages.

**Comment by beto-rodriguez** [comment]
For the previous version of LiveCharts I did not need a conditional reference, I can get successful builds now conditioning the package references, is this the way?

```
<PackageReference Condition="'$(TargetFramework)'!='net6.0-windows10.0.18362'" Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.1-preview.79" />
<PackageReference Condition="'$(TargetFramework)'=='net6.0-windows10.0.18362'" Include="SkiaSharp.Views.WinUI" Version="2.88.1-preview.79" />
```

**Comment by beto-rodriguez** [comment]
Thanks @jeromelaban.
