### ISSUE TITLE
App UI scaling is very different WPF vs. GTK vs. WinUI

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#9218]
### Current behavior

App UI size on the same system should be consistent between WPF, GTK and WinUI.

**Comment by mrlacey** [comment]
Having just noticed something similar, it looks like the scaling is the same for WPF & WinUI, but GTK doesn't apply any scaling.

**Comment by MartinZikmund** [comment]
GTK does not apply fractional scaling (e.g. does apply 100%, 200%, 400%, but not 150%)

**Comment by MartinZikmund** [comment]
In this case we just need to verify for now that the app sizing looks the same between WPF, WinUI and GTK under 100% scale and 200% scale for example.

**Comment by jeromelaban** [comment]
@MartinZikmund About fractional scaling, we will likely be forced to use OS-specific scaling detection.

**Comment by MartinZikmund** [comment]
The issue was caused by scaling not being applied properly, fixed in https://github.com/unoplatform/uno/pull/14038 and https://github.com/unoplatform/uno/pull/13993
