### ISSUE TITLE
Uno Material MenuFlyoutItem

### ISSUE THREAD

**Issue by guillaume-brouillon** [unoplatform/uno#9231]
### Current behavior

Using Uno.Material.WinUI 2.*, the text of menuflyoutitem are wrongly rendered: putting huge space between letters, so that when the text is a few letters long, it makes the app crash. 
Everything works fine using Uno.Material.WinUI 1.*

![image](https://user-images.githubusercontent.com/59391027/177841475-4c490628-3fb6-44d3-8852-b8b6f946f91b.png)

### Expected behavior

the text should be diplayed the same between the two versions
![image](https://user-images.githubusercontent.com/59391027/177841288-1acea1c2-9936-43cb-a266-0c5c2072e575.png)

### How to reproduce it (as minimally and precisely as possible)

Create a uno platform app
Add material UI
Create a button with a flyout menu

### Workaround

use version 1.*

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### IDE

Visual Studio 2022

### IDE version

17.3 preview 2

**Comment by kazo0** [comment]
[This line](https://github.com/unoplatform/Uno.Themes/blob/4ce64a407a6a8d62ba78574a58ed8c46ec351b2c/src/library/Uno.Material/Styles/Controls/v2/Flyout.xaml#L111-L112) looks to be the cause.
Seems there is an issue with setting the `CharacterSpacing` on the `FlyoutPresenter`

cc: @agneszitte-nventive / @Xiaoy312 

Thanks for the report @guillaume-brouillon!

**Comment by Xiaoy312** [comment]
accidently closed this first...
but it should be fixed with the linked PR from above
