### ISSUE TITLE
[Skia] All controls but textboxes turn black when a TextBox gets the focus

### ISSUE THREAD

**Issue by SNival** [unoplatform/uno#9244]
### Current behavior

When a page contains some TextBox, as soon as one of them gets the focus, every part of the page but the text boxes themselves turns completely black, but continues to react to mouse / touch events.

When no text box is focused, the page is well rendered again.

[BlackSurfaces.zip](https://github.com/unoplatform/uno/files/9083831/BlackSurfaces.zip)

### Expected behavior

Page displayed normaly...

Uno.UI.Skia.Gtk 4.3.6 works as expected.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.UI.Skia.Gtk 4.4.13

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### Anything else we need to know?

Tested on Raspberry Pi 3, Raspbian 10 (buster)

**Comment by MartinZikmund** [comment]
Can you please send a screenshot of what you are seeing? I cannot reproduce it on my side 🤔

**Comment by SNival** [comment]
Here is a sequence :
1) Application just started _(notice text box 1 displayed twice)_
![1 - Application start](https://user-images.githubusercontent.com/25543059/178439265-16641429-5523-4cdc-ba91-cf52e2625bb6.png)

2) Touched "text box 1" _display looks good_
![2 - touched text box 1](https://user-images.githubusercontent.com/25543059/178439400-8f43775a-8edf-408c-934f-6d0a33c33727.png)

3) Touched "text box 2", _text block and grid background turns black_
![3 - touched text box 2](https://user-images.githubusercontent.com/25543059/178439832-9ef341b3-0daa-4905-938e-84e80e81cd90.png)

4) Touched "text block zone", nothing focused, _display OK_
![4 - touched text block (nothing focused)](https://user-images.githubusercontent.com/25543059/178439931-169637f9-f0e2-4852-852e-7280c8947882.png)

5) Touched "text box 1" again, _black zones, not the same behaviour as the first touch_
![5 - touched text box 1 again](https://user-images.githubusercontent.com/25543059/178440071-c171ac67-6dd3-4472-a13f-14c03faaf70d.png)

(VNC seems to have a small problem rendering the mouse cursor)

**Comment by MartinZikmund** [comment]
This is very odd! Can you try going into the Gtk project and force-setting the renderer to Software  (see [docs ](https://platform.uno/docs/articles/features/using-skia-gtk.html#changing-the-rendering-target) for this)? Just to rule out that could be the cause

**Comment by SNival** [comment]
Everything is fine using software rendering.
I will test with our complete application to see if I can use it as a workaround...

**Comment by SNival** [comment]
Any news on this issue ?
I checked version 4.5.9, it is still present.

**Comment by jeromelaban** [comment]
@SNival Aside from having a bug in the underlying OpenGL implementation, this is not something we're able to reproduce at this time. What's the version of your Raspberry Pi board and OS ?

**Comment by SNival** [comment]
Raspberrypi OS (debian) buster v10.13, 32 bits on Raspberrypi 3B

**Comment by jeromelaban** [comment]
Raspberry Pi OS (Bullseye) 64 Bits on a RPi 3B. It would not be surprising if there were low-level OpenGL support fixes that had been included in later releases of Raspberry Pi OS.

**Comment by SNival** [comment]
I tested V4.4 on bullseye, but had absolutely no touch event at all. So I stayed on previous version of OS.
When I'll have some time I'll do a new test on latest 64 bit version with Uno 4.5
