### ISSUE TITLE
[Gallery][All Platforms]- Slider control link is missing in the component list.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#9248]
### Current behavior

![Slider issue](https://user-images.githubusercontent.com/74563602/178336473-2db78e53-3f82-45f2-99ee-17a2d16716a6.png)

### Expected behavior

Slider controls should be present in the component list.

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app.
2. Click the 'Burger Menu'.
3. Go to the 'Component list'
4. Notice that the 'Slider' Controls link is missing.

### Affected platforms

iOS, Android, WebAssembly, macOS, Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment]
It looks like the slider sample and other samples as well were disabled in https://github.com/unoplatform/Uno.Gallery/commit/34614e4ad16927d9e8a76b3f316001e567704223 with a "todo: styles not implemented"

**Comment by MartinZikmund** [comment]
This is fixed
