### ISSUE TITLE
Multiple limitations on x:Load

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#925]
## I'm submitting a...

Feature request

## Current behavior

 Currently `x:Load` in Uno:
 - doesn't support binding
 - doesn't support being toggled multiple times
 - is only applied if the Visibility is also set/bound in XAML (bug)

## Expected behavior

Supports the above

## Minimal reproduction of the problem with instructions

```xaml
<StackPanel Background="Yellow" Width="200">
			<CheckBox x:Name="LoadCheckBox" Margin="30" IsChecked="{x:Bind IsLoad, Mode=TwoWay}"/>
			<Border x:Name="LoadBorder" Width="50" Height="50" Background="Green" x:Load="{x:Bind IsLoad, Mode=OneWay}"/>
		</StackPanel>
```
Code-behind:
```chsharp
		public bool IsLoad
		{
			get { return (bool)GetValue(IsLoadProperty); }
			set { SetValue(IsLoadProperty, value); }
		}

		// Using a DependencyProperty as the backing store for IsLoad.  This enables animation, styling, binding, etc...
		public static readonly DependencyProperty IsLoadProperty =
			DependencyProperty.Register("IsLoad", typeof(bool), typeof(MainPage), new PropertyMetadata(false));
```

## Environment

Nuget Package: Uno.UI

Package Version(s): 1.45.0-dev.1560

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by Arlodotexe** [comment]
Are there plans to fix these issue / finish implementing x:Load?
