### ISSUE TITLE
Under WASM, shape resizes when the shape stroke thickness changes

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#9254]
### Current behavior

When pointer over state is actioned in the visual state manager settings and the border of an Ellipse has its size increased the size of the Ellipse should not change and a size change event should not be generated in its container. On the WASM build this is not the case, and a size change does occur.

Given that under WASM the shapes do not generate size change events when they is a valid size change, (see https://github.com/unoplatform/uno/issues/2983) It makes work-arounds particularly difficult if they do generate them when they are no supposed to.

### Expected behavior

The border thickness change should be within the boundary of the shape as it is under UWP.

### How to reproduce it (as minimally and precisely as possible)

Reproduced in a sample project here:
https://github.com/BrianDT/UnoShapeBorderIssue

### Workaround

None obvious

### Works on UWP/WinUI

Yes

### Environment

Windows 11

### NuGet package version(s)

Uno.UI.WebAssembly 4.4.13

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.2.6

### Relevant plugins

None

### Anything else we need to know?

No, sample clearly demonstrates the issue.

**Comment by BrianDT** [comment]
Confirmed as resolved in Uno.UI 4.5.9
The sample has been updated to validate this
The issue can now be closed

**Comment by jeromelaban** [comment]
Thanks for the update!
