### ISSUE TITLE
[Skia][WPF][SamplesApp] AssertIssue8641NativeOverlayInitialized silent filed

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#9259]
### Current behavior

if run SamplesApp.WPF with argument like --auto-screenshots=c:/temp/screenshots/skia-wpf-screenshots the app start but do nut run screenshots 

### Expected behavior

run screenshots 

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.3.0 Preview 2

**Comment by MartinZikmund** [comment]
@workgroupengineering  fixed this in the Runtime Tests PR
