### ISSUE TITLE
[Gallery][Skia.GTK] Image and card - pixels quality of Images is not good.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#9260]
### Current behavior

![Image issue](https://user-images.githubusercontent.com/74563602/178753741-ae42d587-65f3-4109-9e05-c4165de36511.png)
![Card image issue](https://user-images.githubusercontent.com/74563602/182231358-d0e0a2ce-e6bb-4582-a159-7c85499f2ec5.png)

### Expected behavior

![Image correct](https://user-images.githubusercontent.com/74563602/178753778-1b18a234-9150-47ae-ab98-d3d5767f7756.png)
![Card image correct](https://user-images.githubusercontent.com/74563602/182231483-34855023-03da-4f24-90d7-c6c6a3ff28c8.png)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app on Skia.GTK.
2. Click on “Image” from the "Features" list.
3. Observe that the pixels quality of the Images is not good.

### Affected platforms

Skia (Tizen)

**Comment by sakshi173** [comment]
Still this issue is present, please look into it.

**Comment by agneszitte** [comment]
@sakshi173 if you can verify if the issue is still present please with the latest versions

**Comment by sakshi173** [comment]
Verified this issue is fixed , closing it.
