### ISSUE TITLE
The project doesn't know how to run the profile <ProjectName>.Windows

### ISSUE THREAD

**Issue by Paolo55555** [unoplatform/uno#9281]
### Current behavior

When I try to run the WinUI project of a solution created with the new "Uno Platform App" template, unmodified.
The result is a message box with the message in the subject.
The WASM project runs as expected.

### Expected behavior

Obviously, the WinUI app should run.

### How to reproduce it (as minimally and precisely as possible)

Create a new solution in VS 2022 using the "Uno Platform App" (WinUI) template.
Select the WASM and WinUI platforms.
Set the Windows project as startup project
Compile and run

### NuGet package version(s)

The packages loaded by the template project. No modification, no update required.

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

17.2.6

### Relevant plugins

Plugins added to VS (and enabled):
- Markdown Editor V2 (2.0.111)
- Color Picker (1.0.1)
- Time Stamp Margin 2022 (17.0)
- Output Enhancer (1.8)

**Comment by jeromelaban** [comment]
Thanks for the report. This may sometime happen for yet unknown reasons. Have you tried with a different project, or recreating a new one? Does it happen with the latest preview of visual studio ?

**Comment by Paolo55555** [comment]
Thanks for your reply. I've updated VS to 17.3 pre 5 and the bug seems fixed. The Windows app runs correctly. 
Apparently, a side effect of some other fix. But this bug remains a spooky mystery, mostly because there's no online documentation at all on this error, only several reports, no explanation, at most some workaround. It's even impossible to know or figure out its origin. A message which seems conceived with the precise intent of hiding any clue.
No other information than "The project [The project? WTH does it mean?] doesn't know how to run the profile [Why? So what?]".
Sometimes I wonder how a software as important and crucial as VS could contain such sloppy code, and cannot find an answer.

**Comment by jeromelaban** [comment]
Thanks for the update. It also seems related to this https://github.com/unoplatform/uno/issues/9365. You may have made the change manually, which cleared the error message.

**Comment by Paolo55555** [comment]
I have not made any manual changes to the project. I only updated VS from the latest stable version to the latest preview version. I fear that, like other "mystery" bugs, it appears and disappears for unknown and unpredictable reasons. So perhaps neither my "solution" nor the #9365 one are a real solution and the risk of running into this error is still present.
