### ISSUE TITLE
`TextBlock` `Hyperlinks` should color according to theme resources

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#9287]
### Current behavior

Currently, `Hyperlink` elements nested in a `TextBlock` on iOS, macOS, Android and Skia do not get the color from the theme resources but rather either use a fixed blue color or in the case of Android they use a system color. 

### Expected behavior

Hyperlink elements should be using the theme resources that are in scope of the TextBlock, i.e. the resources with keys `HyperlinkForeground`, `HyperlinkForegroundPointerOver`, `HyperlinkForegroundPressed`.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.5.x-dev latest

### Affected platforms

iOS, Android, macOS, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen)

**Comment by MartinZikmund** [comment]
Reopened for backport

**Comment by Youssef1313** [comment]
Backport is merged
