### ISSUE TITLE
[Skia] `TextBlock` `Hyperlinks` mouse over / pressed coloring and cursor

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#9289]
## What would you like to be added:

TextBlock on Skia currently does not handle mouse over tracking to allow for hyperlinks to change color and cursor to change to a hand when the mouse is over them. They also don't change color when pressed.

Note that https://github.com/unoplatform/uno/issues/9287 should be done first so that the mouse over / pressed colors can be correctly set from theme resources.

## Why is this needed:

User experience and parity with UWP.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [X] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by ramezgerges** [comment]
Should've been closed by #13371
