### ISSUE TITLE
Android content dialog height not stretch based on content

### ISSUE THREAD

**Issue by Strypper** [unoplatform/uno#9291]
### Current behavior

Android: (Even set min height the content is displaying like 5 to 10 height)
![image](https://user-images.githubusercontent.com/32596308/179337030-ee3799e5-fd59-40cd-be98-dfbdfa463647.png)
WinUI and WASM:
![image](https://user-images.githubusercontent.com/32596308/179337049-2da29cda-4b68-46b8-b43f-85dfa902565e.png)

### Expected behavior

Content dialog on android taller

### How to reproduce it (as minimally and precisely as possible)

https://github.com/Strypper/PixelArt

1. Run this project on Android 
2. Add new art
3. The content dialog will show up like in the issue

### Workaround

No workaround

### Works on UWP/WinUI

Yes

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

Preview

**Comment by francoistanguay** [comment]
Would you be able to reproduce the issue in a smaller repro for the team to look at? A solution with just the code that doesnt work. Thank you!

**Comment by MartinZikmund** [comment]
@Strypper Can you create a small repro based on a blank app for this?

**Comment by Strypper** [comment]
I am currently occupied now
