### ISSUE TITLE
[Android] FlipView fail to arrange its content

### ISSUE THREAD

**Issue by Strypper** [unoplatform/uno#9293]
### Current behavior

Android
![image](https://user-images.githubusercontent.com/32596308/179339844-4ca34f26-1e81-4371-bbc2-6eb84fcd8e3e.png)
WinUI and WASM
![image](https://user-images.githubusercontent.com/32596308/179339882-e88942e8-cb3a-4763-80b2-87e158c4167d.png)

Component detail 
https://github.com/Strypper/PixelArt/blob/master/PixelArt/PixelArt.Shared/UserControls/Pixel2ArtFrameUserControl.xaml

### Expected behavior

Image must shrink down

### How to reproduce it (as minimally and precisely as possible)

Component detail
https://github.com/Strypper/PixelArt/blob/master/PixelArt/PixelArt.Shared/UserControls/Pixel2ArtFrameUserControl.xaml
Image that cause unable to resize down:
![Uploading Screenshot_20200704-201657.png…]()

### Workaround

No work around

### Works on UWP/WinUI

Yes

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

Preview

**Comment by Xiaoy312** [comment]
related?: #8637

**Comment by Xiaoy312** [comment]
MCVE:
```xml
<ListView MinWidth="320"
            Margin="0,15,0,0"
            HorizontalAlignment="Center"
            HorizontalContentAlignment="Center"
            ItemsSource="12345">
    <ListView.ItemTemplate>
        <DataTemplate>
            <Border>
                <FlipView Height="520" Width="300">
                    <FlipViewItem>
                        <!--<Border BorderBrush="SkyBlue" BorderThickness="5">-->
                            <ScrollViewer Height="520">
                                <Image Source="https://www.setaswall.com/wp-content/uploads/2017/10/Cosmos-Wallpaper-1080x1920-768x1365.jpg" Stretch="UniformToFill" />
    ^ uncommenting the Border and causing RemoteControl to update the ui, and in turn, fix the problem
        ^ which suggest this is very likely to be a FlipView layout issue
```

**Comment by ajpinedam** [comment]
@Strypper, we pushed a fix last night for this in another PR, could you test with tomorrow's dev build?

https://user-images.githubusercontent.com/1900897/181855094-3ffaa75d-dc15-4a4e-8b55-93bc28260bfa.mp4

**Comment by ajpinedam** [comment]
Closing. Fixed in https://github.com/unoplatform/uno/pull/9389
