### ISSUE TITLE
Android: Unable to build Release version with AOT/LLVM enabled

### ISSUE THREAD

**Issue by ThaddeusChristopher** [unoplatform/uno#9333]
### Current behavior

Deploying Release build (AOT/LLVM enabled by default) to Android fails with:

> XA5104: Could not locate the Android NDK. Please make sure the Android NDK is installed in the Android SDK Manager, or if using a custom NDK path, please ensure the $(AndroidNdkDirectory) MSBuild property is set to the custom path.

### Expected behavior

Should be able to deploy a Release build with all of the default optimizations preserved from fresh install of toolchain, Visual Studio, etc.

### How to reproduce it (as minimally and precisely as possible)

Using Visual Studio Preview

1. Generate a new cross-platform project (I did so from VS Mac first [using Uno documentation's steps](https://platform.uno/docs/articles/get-started-vsmac.html?tabs=macos), but am presently operating on Windows from the same solution)
2. Ensure you are able to deploy a Debug build successfully to a physical Android phone (this works)
3. Make sure Android Studio has the latest SDKs and NDKs installed
4. Attempt to deploy a Release build

Observe deployment fails due to NDK not found

### Workaround

None verified as of yet. Possibly something similar to what they did with Xamarin.Forms: https://github.com/xamarin/xamarin-android/issues/5499

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

Preview

### Anything else we need to know?

Release build deploys OK so long as I set these default optimizations to false:
```
    <AotAssemblies>true</AotAssemblies>
    <EnableLLVM>true</EnableLLVM>
    <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
```

I have tried installing multiple NDKs in case one of them turns out to be the one MSBuild is looking for. So far no dice. Am thinking this could be a question of a build tool somewhere in the chain not using the default NDK directory currently being employed by Android Studio Chipmunk 2021.2.1 Patch 1: `C:\Users\<username>\AppData\Local\Android\Sdk\ndk\25.0.8775105`

![image](https://user-images.githubusercontent.com/5448576/180272378-c4ac65b3-740f-4005-a8a7-07019404c95b.png)

The Internet has shown me many alternative directories these files could wind up in, such as inside Program Files, ProgramData, and `C:\Users\<username>\AppData\Local\Android\android-sdk\ndk-bundle`

I tested out dumping the NDK into a few of them but have had no luck

**Comment by queequac** [comment]
This is my standard build configuration (AoT+LLVM) for Android in production and it works without any problems on VS2022 (17.2.6, latest, but not preview) and Uno (4.4.13, latest, but not preview).

What exact versions are you using? Personally, this seems to me to be some sort of problem with your setup.

**Comment by ThaddeusChristopher** [comment]
Thank you for your interest :-)

And also for your wisdom, which led me down the correct path.

I did not know that the Android SDK/NDK must be installed via Visual Studio's in-built SDK manager instead of the official [Android Studio](https://developer.android.com/studio/install) one. This also explains why so many alternate paths for it exist on the web; different IDEs must prefer their own paths. Strange that they lack a standardized path (what a perfect world that would be...) since they share the same resources but c'est la vie.

You were right! That fixed things, placing it ultimately in MSBuild's desired path.

I suspect I'm not the only one to fall into this trap. Hopefully this issue will help others experiencing the same error messages.

Cheers!
