### ISSUE TITLE
Evaluate whether the "Universal Windows Platform" VS workload should be required

### ISSUE THREAD

**Issue by lukeblevins** [unoplatform/uno#9342]
## On which page?
https://platform.uno/docs/articles/get-started-vs-2022.html?tabs=windows

## What's wrong?
The language explicitly makes the entire "Universal Windows Platform" Visual Studio workload a requirement for setting up one's development environment. 

## Any feedback?
With the introduction of the Windows App SDK, Microsoft has [moved](https://github.com/MicrosoftDocs/windows-uwp/pull/3903) [away](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b#required-workloads-and-components) from requiring the installation of this workload to build WinUI 3 apps. We should make it clear in the docs that the UWP VS workload is only required for generating Uno solutions that need UWP support, instead of by default.

## Rationale
To promote a balanced perspective of the Windows desktop development story, consistent with Microsoft's flagship offerings. Additionally, we would save new users time and storage space when setting up their development environments for building Uno Platform apps.

## Open questions:
* Are there ANY dependencies from the UWP VS workload that are currently needed for building the Windows App SDK target, and can these be installed individually? (Notably, the latest Windows platform SDK)
* Would additional work be needed to adjust the dependencies of our solution template to reflect this change?

**Comment by lukeblevins** [comment]
CC @nickrandolph @sasakrsmanovic @jeromelaban

**Comment by jeromelaban** [comment]
Currently, we're requesting the UWP SDK because the UWP-uno templates make use of it, but it's not the default path. We probably could remove this dependency in the walkthrough and rely on the .vsconfig to suggest adding it in case of the UWP template being used. We'll need to make sure that the Windows SDKs are installed properly with the right versions.
