### ISSUE TITLE
[BUTTON] HorizontalAlignment of content wrongly applied when text

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#9361]
### Current behavior

Take this XAML:

``` xml
<StackPanel Spacing="20">
  <Button HorizontalAlignment="Stretch">123</Button>
  <Button HorizontalAlignment="Stretch" ><TextBlock Text="123" HorizontalAlignment="Stretch" /></Button>
  <Button HorizontalAlignment="Stretch" ><TextBlock Text="123" /></Button>
</StackPanel>
```

It's currently producing 3 different results, where the 2nd is left-aligned.

### Expected behavior

Put the same code in XAML Studio and those 3 text are centered.

### How to reproduce it (as minimally and precisely as possible)

https://playground.platform.uno/#adfc5e7a

### NuGet package version(s)

Uno 4.4

### Affected platforms

WebAssembly

**Comment by MartinZikmund** [comment]
Aha! This is most likely what I was seeing in #4038! I know the fix now!
