### ISSUE TITLE
Next/done button from virtual keyboard support

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#9363]
## What would you like to be added:
The possibility to add an order to fields like textboxes, so that when you press on the button '
![image](https://user-images.githubusercontent.com/90481654/180869509-a43ea764-b976-45f7-99e2-906562265713.png)
 on android, or an equivalent on IOS. You could simply give the the fields a number and when you press next, it would go the next number. When you are at the final field, the next button would become a done button that would dismiss the keyboard. 

## Why is this needed:
Convenience for the user when he is navigating a form, and because the button next is already there and it is a little confusing that it doesnt do anything. Also, we have the equivalent already kind of working on windows when you press on tab.
## For which Platform:

- [X] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by kazo0** [comment]
@Marc-Antoine-Soucy + @takla21 

Would this issue be the same ask as https://github.com/unoplatform/uno.toolkit.ui/issues/280?

Trying to get all the issues cleaned up and prioritized. Let me know if I can close this one as a duplicate of the toolkit#280 issue

**Comment by kazo0** [comment]
dupe of https://github.com/unoplatform/uno.toolkit.ui/issues/280
