### ISSUE TITLE
[Gallery][Wasm] NavigationBar-  Close(X) button is missing in light theme for 'Launch FullScreen sample'

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#9378]
### Current behavior

![Navigationbar issue](https://user-images.githubusercontent.com/74563602/181357881-26c1810e-fb98-459a-bcee-85588be47fb1.png)

### Expected behavior

![Navigationbar correct](https://user-images.githubusercontent.com/74563602/181357892-897fc26d-5bd8-4a67-9a4a-de6f21f26d88.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Click on the Light/Dark theme change toggle button.
4. Notice that the app is displaying in the Light theme.
5. Tap "NavigationBar" from the "toolkit" list.
6. Tap on the 'Launch Fullscreen Sample' button.
7. Observe that the Close button is missing on the top header.

### Affected platforms

WebAssembly

**Comment by nguyeenvy** [comment]
@sakshi173 @kazo0 Hello, once again, I tested this issue on https://unogallerycanary.z27.web.core.windows.net/ and I cannot reproduce this issue.

**Comment by nguyeenvy** [comment]
Canary:


![Image](https://github.com/unoplatform/uno/assets/54756963/311aef8f-03ce-4329-a111-8accfde59f33)


Wasm:


![Image](https://github.com/unoplatform/uno/assets/54756963/69fd4073-9059-417c-99b8-57599eea2aaf)

**Comment by nguyeenvy** [comment]
@sakshi173 @kazo0 Sorry, my mistake. I tested this in Night mode instead of Day mode. Indeed, in Day mode, it doesn't show. I will investigate this also.
