### ISSUE TITLE
WPF project doesn't build out of box in latest templates

### ISSUE THREAD

**Issue by Arlodotexe** [unoplatform/uno#9380]
### Current behavior

If you generate a blank new project with `dotnet new unoapp`, the WPF head doesn't build.

Instead, it spits out 3699 errors, with errors like

```
C:\...\Test\Test.Skia.WPF\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\GlobalStaticResources.cs(38,15): error CS0102: The type 'GlobalStaticResources' already contains a definition for '_initialized'
```

and

```
C:\...\Test\Test.Skia.WPF\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\GlobalStaticResources.cs(85,23): error CS0756: A partial method may not have multiple defining declarations
```

![image](https://user-images.githubusercontent.com/9384894/181377162-b5c50ee5-d3a4-4cc1-89f3-442910562925.png)

### Expected behavior

The WPF head should build out of box.

### How to reproduce it (as minimally and precisely as possible)

1. Update the templates
2. Run `dotnet new unoapp`
3. `cd` to the WPF head
4. `msbuild -r` on the command line.
5. Observe the errors.

### Workaround

No known workarounds

### Relevant plugins

MSBuild 17.2.1+52cd2da31

**Comment by HavenDV** [comment]
```xml
  <Target Name="RemoveDuplicateAnalyzers" BeforeTargets="CoreCompile">
    <!-- Work around https://github.com/dotnet/wpf/issues/6792 -->

    <ItemGroup>
      <FilteredAnalyzer Include="@(Analyzer->Distinct())" />
      <Analyzer Remove="@(Analyzer)" />
      <Analyzer Include="@(FilteredAnalyzer)" />
    </ItemGroup>
  </Target>
```

**Comment by jeromelaban** [comment]
Looks like the latest band release has broken some generators behaviors. Will look into it.

**Comment by jeromelaban** [comment]
This is a this https://github.com/dotnet/wpf/issues/6792 WPF issue, which will be fixed in a more recent .NET SDK release. The workarounds specified there are valid (global.json to avoid 6.0.302).
