### ISSUE TITLE
`RelativePanel` does not handle native views properly

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#9381]
### Current behavior

When native controls are inside of a `RelativePanel` they are not measured and arranged properly.

### Expected behavior

Should be arranged properly.

**Comment by jeromelaban** [comment]
I'm not too sure if we should be supporting this explicitly. We're requiring users to put native controls inside ContentControl/ContentPresenter since Uno 3 (as they're not UIElement). What's the original scenario for this?

**Comment by MartinZikmund** [comment]
@jeromelaban I noticed `MeasureElement` was used in some other panel and thought it was needed too. If native elements need to be in `ContentControl` though, then this is probably unnecessary change.
