### ISSUE TITLE
[Gallery][All Platforms] ElevatedView unification.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#9388]
### Current behavior

**WASM Light Theme**
![Wasm light theme EV](https://user-images.githubusercontent.com/74563602/181584506-d2546194-6a9c-42cc-9b01-4482750b4e3d.png)
**WASM Dark Theme**
![Wasm dark theme EV](https://user-images.githubusercontent.com/74563602/181584597-531f8f98-9b44-4329-a41b-1be04c7dbf36.png)
**Skia.GTk Light Theme**
![Skia light theme EV](https://user-images.githubusercontent.com/74563602/181584684-45f997bc-1c97-48e9-8a4a-51c4338da939.png)
**Skia.Gtk Dark Theme**
![Skia dark theme EV](https://user-images.githubusercontent.com/74563602/181584760-b1c3ae98-531f-405c-bdec-070d5ce40321.png)
**iOS Light Theme**
![iOS Light theme-](https://user-images.githubusercontent.com/74563602/181585780-a11c3ab1-c405-44bc-8020-fabdeb0f9f6a.png)
**iOS Dark Theme**
![iOS Dark theme-](https://user-images.githubusercontent.com/74563602/181585866-1c964c73-17c1-48cb-a038-5102ea9ce5cf.png)
**Android Light Theme**
![Android Light theme-](https://user-images.githubusercontent.com/74563602/181585060-aa53f9ea-cdbd-43d9-8c74-8232da9a25e4.png)
**Android Dark Theme**
![Android Dark theme-](https://user-images.githubusercontent.com/74563602/181585094-06dcf919-e950-4f0f-ab66-6c864d44e308.png)

Note:- Not able to take screenshots for MacOS Catalyst platform( Currently, the build is not working).

### Expected behavior

Elevated view should be similar and correct for all the platforms.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Click on the Light/Dark theme change toggle button.
4. Notice that the app is displaying in the Light theme.
5. Tap "ElevatedView" from the "Component" list.
6. Observe ElevatedView from 1dp to 16dp.
7. Click on the Light/Dark theme change toggle button.
8. Notice that the app is displaying in the Dark theme.
9. Tap "ElevatedView" from the "Component" list.
10. Observe ElevatedView from 1dp to 16dp.

### Affected platforms

iOS, Android, WebAssembly, Skia (GTK on Linux/macOS/Windows)

**Comment by MartinZikmund** [comment]
@sakshi173 Can you please recheck this? I think it should be now more unified after the last shadow changes

**Comment by agneszitte** [comment]
@sakshi173 I added this issue to the "Needs QA Review" list so you can review it please

@MartinZikmund added to the current release backlog for @sakshi173 to review it but can move to other backlog depending on the outcome and priority

**Comment by sakshi173** [comment]
Verified this issue is resolved for all platform due to that closing it.
![elevated view WASM](https://github.com/unoplatform/uno/assets/74563602/71775233-ac47-46fc-acf5-426e7c0cb092)
![elevated view skia](https://github.com/unoplatform/uno/assets/74563602/d60145b8-9cb3-4cc3-8228-52bfaa8757c8)
![elevated view iOS](https://github.com/unoplatform/uno/assets/74563602/1676bf71-6f5c-4e80-a5ac-7fa6b1cd4ebf)
![elevated view Android](https://github.com/unoplatform/uno/assets/74563602/3feed631-e43a-4d2e-92be-f3e43d97a7c8)
