### ISSUE TITLE
CameraCaptureUI doesn't work in unoapp-uwp-net6 project

### ISSUE THREAD

**Issue by ttustonic** [unoplatform/uno#9397]
### Current behavior

I created two test projects using 'unoapp-uwp' and 'unoapp-uwp-net6' template and copied `AndroidManifest.xml` and `MainPage `from the `CameraCaptureUISample`.
Unoapp-uwp project works fine, the same as the sample
Unoapp-uwp-net6 Android doesn't work. It throws `This operation is not supported for a relative URI.` exception on the line
`var photo = await captureUI.CaptureFileAsync(CameraCaptureUIMode.Photo);`
Is there something else, except Android manifest, that needs to be changed to make it work?

Thanks, Tom

[UwpNet6TestCapturre.zip](https://github.com/unoplatform/uno/files/9226119/UwpNet6TestCapturre.zip)

### Expected behavior

It should capture image on Android, the same as in CameraCaptureUISample, and Uwp version.

### Works on UWP/WinUI

Yes

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. Could you provide the full stack trace of the exception to help troubleshoot faster?

**Comment by ttustonic** [comment]
Hello

Here it is.

[stacktrace.txt](https://github.com/unoplatform/uno/files/9238091/stacktrace.txt)
