### ISSUE TITLE
Application on linux framebuffer not work.

### ISSUE THREAD

**Issue by zxslzx** [unoplatform/uno#9422]
### Current behavior

<img width="400" alt="Snipaste_2022-08-04_16-07-24" src="https://user-images.githubusercontent.com/32009362/182798972-62bf4533-44f6-4312-87b2-ad5a94e730c9.png">

There is no error message

### Environment

Other

### NuGet package version(s)

4.4.13

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
Thanks for the report. Can you provide more details about the OS environment and hardware you're using ?

**Comment by zxslzx** [comment]
> Thanks for the report. Can you provide more details about the OS environment and hardware you're using ?

VMware + Ubuntu20.04

**Comment by dotMorten** [comment]
This looks exactly like what happened when I got the framebuffer size / color space wrong. Run `fbset` and paste the output to confirm. Up [until a few hours ago](https://github.com/unoplatform/uno/pull/9418), only rgb32 was supported, but if you pull the latest devbuild it might work if you happen to have a 16bit buffer.

**Comment by zxslzx** [comment]
> This looks exactly like what happened when I got the framebuffer size / color space wrong. Run `fbset` and paste the output to confirm. Up [until a few hours ago](https://github.com/unoplatform/uno/pull/9418), only rgb32 was supported, but if you pull the latest devbuild it might work if you happen to have a 16bit buffer.

![Uploading Snipaste_2022-08-05_12-06-37.png…]()

**Comment by zxslzx** [comment]
> This looks exactly like what happened when I got the framebuffer size / color space wrong. Run `fbset` and paste the output to confirm. Up [until a few hours ago](https://github.com/unoplatform/uno/pull/9418), only rgb32 was supported, but if you pull the latest devbuild it might work if you happen to have a 16bit buffer.

<img width="147" alt="Snipaste_2022-08-05_12-06-37" src="https://user-images.githubusercontent.com/32009362/182999632-94d50c7e-b994-4e45-b9d2-4c6fe23b0964.png">

**Comment by jeromelaban** [comment]
@zxslzx can you try again with the [latest experimental ](https://www.nuget.org/packages/Uno.UI/4.5.0-dev.422)packages?

**Comment by zxslzx** [comment]
> @zxslzx can you try again with the [latest experimental ](https://www.nuget.org/packages/Uno.UI/4.5.0-dev.422)packages?

It's the same problem

**Comment by jeromelaban** [comment]
Thanks. This would mean that Uno is not reading the framebuffer's geometry properly for some reason. Could you make the following modifications in `App.xaml.cs` :
```
builder.SetMinimumLevel(LogLevel.Debug);
```

Then add the following:
```
builder.AddFilter("Uno.UI.Runtime.Skia.FrameBufferHost", LogLevel.Debug);
```

Then run the application, using the latest dev bits of Uno. You should see a line starting with [`Display Information:`](https://github.com/unoplatform/uno/blob/51aa3fa96bcb9a0bb427b6c1530b84e2d74a20d0/src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FramebufferHost.cs#L77-L85), could you paste it here ?

**Comment by zxslzx** [comment]
> 
There is no debug message

<img width="331" alt="1" src="https://user-images.githubusercontent.com/32009362/183334780-351efa8a-9c62-4982-925a-da7020003db2.png">

<img width="585" alt="3" src="https://user-images.githubusercontent.com/32009362/183334844-0bb7df92-4d05-4808-89e3-6e6c402756d5.png">

<img width="383" alt="2" src="https://user-images.githubusercontent.com/32009362/183334820-abddfb7b-9d24-499c-8f1a-584b98d0737a.png">

**Comment by zxslzx** [comment]
> Thanks. This would mean that Uno is not reading the framebuffer's geometry properly for some reason. Could you make the following modifications in `App.xaml.cs` :
> 
> ```
> builder.SetMinimumLevel(LogLevel.Debug);
> ```
> 
> Then add the following:
> 
> ```
> builder.AddFilter("Uno.UI.Runtime.Skia.FrameBufferHost", LogLevel.Debug);
> ```
> 
> Then run the application, using the latest dev bits of Uno. You should see a line starting with [`Display Information:`](https://github.com/unoplatform/uno/blob/51aa3fa96bcb9a0bb427b6c1530b84e2d74a20d0/src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FramebufferHost.cs#L77-L85), could you paste it here ?

dbug: Uno.UI.Runtime.Skia.FrameBufferHost[0]
      Display Information: 800x600 (-1,-1 mm), PixelFormat: Bgra8888, ResolutionScale: Scale100Percent, LogicalDpi: 96, RawPixelsPerViewPixel: 1, DiagonalSizeInInches: , ScreenInRawPixels: 800x600

**Comment by jeromelaban** [comment]
Interesting. Details are looking fine so it must be something else. Are you able to change the screen resolution so something higher? I'm not too sure about what VMWare allows.

**Comment by zxslzx** [comment]
> 
Set resolution to 1024x768.  It works.
dbug: Uno.UI.Runtime.Skia.FrameBufferHost[0]
      Display Information: 1024x768 (-1,-1 mm), PixelFormat: Bgra8888, ResolutionScale: Scale100Percent, LogicalDpi: 96, RawPixelsPerViewPixel: 1, DiagonalSizeInInches: , ScreenInRawPixels: 1024x768
warn: Uno.UI.RemoteControl.RemoteControlClient[0]
      The remote control client failed to initialize (One or more errors occurred. (Unable to connect to the remote server)). This generally means that XAML Hot Reload will not be available for this session.
<img width="512" alt="Snipaste_2022-08-09_15-07-57" src="https://user-images.githubusercontent.com/32009362/183586472-6b63955d-b3ad-452f-97a2-d7ea3f31afc6.png">

**Comment by jeromelaban** [comment]
Thanks for the update. It's likely that the framebuffer uses padding each scan lines of the framebuffer, making the blitting copy fail in this way:
https://github.com/unoplatform/uno/blob/51aa3fa96bcb9a0bb427b6c1530b84e2d74a20d0/src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/Renderer.cs#L68

This should be relatively easy to fix.

Out of curiosity, do you have a physical device which has the same issue?

**Comment by zxslzx** [comment]
> 

I tested it on a physical device without this problem.
