### ISSUE TITLE
Deriving DependencyObject under .NET 6/WPF errors with "does not implement .. 'DependencyObject.DispatcherQueue"

### ISSUE THREAD

**Issue by Arlodotexe** [unoplatform/uno#9423]
### Current behavior

This issue is suspiciously similar to #9380, but you only encounter this _after_ applying the recommended workaround to the WPF head:

```xml
  <Target Name="RemoveDuplicateAnalyzers" BeforeTargets="CoreCompile">
    <!-- Work around https://github.com/dotnet/wpf/issues/6792 -->

    <ItemGroup>
      <FilteredAnalyzer Include="@(Analyzer->Distinct())" />
      <Analyzer Remove="@(Analyzer)" />
      <Analyzer Include="@(FilteredAnalyzer)" />
    </ItemGroup>
  </Target>
```

After testing workarounds and gathering information for a few days, this doesn't seem to be related to the above issue. I can only assume there's something funky happening with the new Roslyn-based source generators in Uno.

Using the latest `dotnet new unoapp` template, if you create a class that derives `DependencyObject`:

```csharp
public sealed partial class NavigateToUriAction : DependencyObject, IAction
{
    public Uri NavigateUri
    {
        get => (Uri)GetValue(NavigateUriProperty);
        set => SetValue(NavigateUriProperty, value);
    }

    public static readonly DependencyProperty NavigateUriProperty = DependencyProperty.Register(
        nameof(NavigateUri),
        typeof(Uri),
        typeof(NavigateToUriAction),
        new PropertyMetadata(null));

    /// <inheritdoc/>
    public object Execute(object sender, object parameter)
    {
        if (NavigateUri != null)
        {
            _ = Windows.System.Launcher.LaunchUriAsync(NavigateUri);
        }
        else
        {
            throw new ArgumentNullException(nameof(NavigateUri));
        }

        return true;
    }
}
```

Then WPF head will fail to compile with the error:
```
 error CS0535: 'NavigateToUriAction' does not implement interface member 'DependencyObject.DispatcherQueue' 
```

If you manually add the code that should be getting generated (pulled from [here](https://github.com/unoplatform/uno/blob/master/src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs#L878)):
```cs
public global::Microsoft.UI.Dispatching.DispatcherQueue DispatcherQueue { get; } = global::Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread();
```

Then you get the error:
```
error CS0102: The type 'NavigateToUriAction' already contains a definition for 'DispatcherQueue' 
```

### Expected behavior

The WPF head should compile when valid code is used.

### How to reproduce it (as minimally and precisely as possible)

Repro project: [Test.zip](https://github.com/unoplatform/uno/files/9264106/Test.zip)

Note that only the WPF head has been set up for repro. Compile directly with MSBuild.

### Workaround

No known workaround. Tried forcing .NET to a version before the problematic Analyzer PR was introduced to .NET 6, but no available version of .NET 6 seems to work.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Latest default versions for `dotnet new unoapp` as of posting (4.4.13)

### Affected platforms

Skia (WPF)

**Comment by Youssef1313** [comment]
@Arlodotexe Is `NavigateToUriAction` in global namespace? Does things work if it's not in global namespace?

**Comment by Youssef1313** [comment]
@jeromelaban One of the issues here is `HAS_UNO_WINUI` not defined for the WPF head, and the source generator uses `HAS_UNO_WINUI`.

This is what gets passed to the compiler: 
`TRACE;DEBUG;NET;NET6_0;NETCOREAPP;WINDOWS;WINDOWS7_0;NET5_0_OR_GREATER;NET6_0_OR_GREATER;NETCOREAPP3_0_OR_GREATER;NETCOREAPP3_1_OR_GREATER;WINDOWS7_0_OR_GREATER;UNO_REFERENCE_API;HAS_UNO_SKIA;HAS_UNO_SKIA_WPF`

@jeromelaban Should we add `HAS_UNO_WINUI` here?  https://github.com/unoplatform/uno/blob/c94d459528296a91d0ac6cac89b3c78304f11b49/src/Uno.UI.Runtime.Skia.Wpf/buildTransitive/Uno.UI.Runtime.Skia.Wpf.targets#L7

I'll go with a different fix on the generator side anyway, but just double checking if `HAS_UNO_WINUI` is missing or intentional to not exist.

**Comment by jeromelaban** [comment]
Yes, I looked at that during a stream, but forgot to mention it. I think it's more the fact that the blocks that are already defining it are not included properly here https://github.com/unoplatform/uno/blob/6ceaab20dff19bc9c9cffa04bf1c76655a5c22e6/build/uno.winui.common.targets#L32, for some reason on Wpf.
