### ISSUE TITLE
Generated Uno app and library projects seems to contain deprecated code

### ISSUE THREAD

**Issue by hansmbakker** [unoplatform/uno#9450]
A generated Uno app project contains this piece of code:
```xml
<ItemGroup>
		<!--
		If you encounter this error message:
		
			error NETSDK1148: A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll. Please update to a newer .NET SDK in order to reference this assembly.

		This means that the two packages below must be aligned with the "build" version number of
		the "Microsoft.Windows.SDK.BuildTools" package above, and the "revision" version number
		must be the highest found in https://www.nuget.org/packages/Microsoft.Windows.SDK.NET.Ref.
		-->
		<FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.22000.25" />
		<FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.22000.25" />
	</ItemGroup>
```

A generated Uno library project contains this piece of code:

```xml
  <ItemGroup Condition="'$(TargetFramework)'=='net6.0-windows10.0.18362'">
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.1.0" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.22000.24" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.22000.24" />
  </ItemGroup>
```

I searched online to understand what it does, and found [this page](https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/5.0/override-windows-sdk-package-version) which says the syntax above is deprecated.

## What would you like to be added:

The referenced page says that the correct way to override the Windows SDK is now the syntax below. However, they also say that a better option would be to encourage people to update their .NET SDK (see `Anything else we need to now?`).

```xml
<PropertyGroup>
  <WindowsSdkPackageVersion>10.0.22000.24</WindowsSdkPackageVersion>
</PropertyGroup>
```

## Why is this needed:

> Starting in .NET 5.0.8 (which includes .NET SDK 5.0.302 and .NET SDK 5.0.205), developers targeting Windows can't use the `FrameworkReference` item to override their version of the Windows SDK targeting package. The `WindowsSdkPackageVersion` property replaces this functionality.

 
## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [x] Build tasks
- [x] Solution Templates

## Anything else we need to know?

The page also says this:

> **Note**
> We don't recommend overriding the Windows SDK version, because the Windows SDK targeting packages are included with the .NET 5+ SDK. Instead, to reference the latest Windows SDK package, update your version of the .NET SDK.

**Comment by jeromelaban** [comment]
Thanks for the feedback. This specific block is done based on the feedback from the WinUI team directly, but it would make sense to change for the newer property, indeed. We can try updating the templates and see if this works properly.

Does your application build properly when using this property?

**Comment by hansmbakker** [comment]
> Does your application build properly when using this property?

Yes, it works well. I also modified the version to `10.0.22000.26`.

**Comment by Youssef1313** [comment]
The new templates no longer have `<FrameworkReference Update...`

https://github.com/unoplatform/uno.templates/issues/72 tracks whether we actually need `WindowsSdkPackageVersion` or not. Hence, I'm closing this issue
