### ISSUE TITLE
[iOS] Disengaging focus from a `PasswordBox` after changing RevealMode duplicates and appends the input. 

### ISSUE THREAD

**Issue by marwalsch** [unoplatform/uno#9460]
### Current behavior

After changing `PasswordBox.PasswordRevealMode` the box's input is duplicated when focus is lost.

### Expected behavior

The input remains unaltered.

### How to reproduce it (as minimally and precisely as possible)

1. replicate the following setup:

    ```
          <PasswordBox
                x:Name="PasswordInput"
                PasswordChanged="OnPasswordChanged"
                PasswordRevealMode="Hidden"
                PlaceholderText="{CustomResource EnterPassword}"/>
            <CheckBox
                Content="{CustomResource ShowPassword}"
                Checked="OnRevealModeChangeRequested"
                Unchecked="OnRevealModeChangeRequested"/>
    ```
    
    ```
      private void OnRevealModeChangeRequested(object sender, RoutedEventArgs _)
            {
                if (sender is CheckBox checkBox)
                {
                    PasswordInput.PasswordRevealMode = checkBox.IsChecked == true ? PasswordRevealMode.Visible : PasswordRevealMode.Hidden;
                }
            }
    ```

2. Enter a password.
3. Check and uncheck the box to de- and reactivate the visible reveal mode. 
4. Focus the input again and hit enter/press outside the box to lose focus.
5. The input will now have been duplicated inside the box.

### Workaround

`LostFocus` **cannot** be used to overwrite as the change occurs afterwards.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUi 4.2.6

### Affected platforms

iOS

### IDE

Visual Studio 2022

**Comment by marwalsch** [comment]
Possibly related: #7400

**Comment by jeromelaban** [comment]
@marwalsch can you validate that this still happens with the latest dev packages?

**Comment by marwalsch** [comment]
@jeromelaban It doesn't!
