### ISSUE TITLE
[WASM] `CornerRadius` is wrong

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#9490]
### Current behavior

Setting a CornerRadius on an element (let's say a `<Border />`) on Wasm is leading to a too-small corner radius being applied to the element. But it works well on `<Rectangle />` -- probably because it's using a SVG element with a different way to calculate the radius.

### Expected behavior

(see playground link below) On Windows, both rectangle is having the same radius for both `<Rectangle />` and `<Border />` and the result is very similar to the `<Rectangle />` one... that would mean the problem is with the Border itself on Wasm.

### How to reproduce it (as minimally and precisely as possible)

Playground link: https://playground.platform.uno/#e78e096c

### Workaround

Doubling the value seems to produce the right result. That may be caused by a different way to calculate the radius. On Windows, the radius size seems applied to the outer part of the stroke and on HTML, it seems to be applied to the stroke path itself, so at the middle of it.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly

**Comment by niels9001** [comment]
We are running into this issue as well with the Windows Community Toolkit RangeSelector: https://github.com/CommunityToolkit/Windows/pull/44

<img width="130" alt="image" src="https://user-images.githubusercontent.com/9866362/236227797-9cc45400-f1e4-4e06-bda7-5136496e988d.png">

**Comment by niels9001** [comment]
@MartinZikmund looks like this is closed as a duplicate of itself 😅?

**Comment by MartinZikmund** [comment]
Very duplicate indeed 😂 #10263 is the right one
