### ISSUE TITLE
Linux will ever be supported?

### ISSUE THREAD

**Issue by fanoI** [unoplatform/uno#95]
De facto there is not a simple way to have a xplat UI on Linux yet, I think Uno could fill this gap.
The fact that you develop on Windows using the UWP designer is the most important thing for me.

**Comment by jeromelaban** [comment]
@fanoI thanks for your interest in the Uno Platform! For now, Linux is a target through web assembly, and possibly electron.

See the FAQ for additional details: https://github.com/nventive/Uno/blob/master/doc/articles/faq.md#does-unoui-support-linux-

**Comment by fanoI** [comment]
I've tried to use Mono as replacement of the Net Framework but sincerely the fact that exceptions does  reported the stack trace only in debug mode made no sense for me.

Probably WebAssembly is not the same thing but I had a very negative experience using Qt + HTML in Linux (the C++/Javascript bridge was in a lot of simply not working) so I would prefer a native solution.

**Comment by jeromelaban** [comment]
@fanoI That's an interesting note. I'm not sure what you mean by debug-only stack traces. Those should be available no matter the runtime mode. 

Regardless, at present time in Wasm, the runtime is functioning quite nicely and technically, the whole Uno.UI stack can run in a .net core/html setup as well, in place of mono.

Considering the Uno.UI stack always uses the underlying UI (e.g. UIKit, Android UI, HTML), which one would you prefer be targeted for linux ?

**Comment by fanoI** [comment]
Look here: https://bugzilla.xamarin.com/show_bug.cgi?id=3357

in short expections are only meaningful in debug mode in Mono, but not in release.

**Comment by fanoI** [comment]
Regarding the underlying UI probably Gnome / Gtk that should be easier as already exist C# wrapper library for it: GTK#.

**Comment by jeromelaban** [comment]
Got it. This is a Xamarin-specific default for mobile apps, which make sense considering the sensitiveness of the package size on mobile devices. 

This can be changed by including the pdbs/mdbs to my understanding, this applies as well to the wasm target (this this is still in flux because of the work in progress for the wasm debugger).

**Comment by handicraftsman** [comment]
I think Uno should still be ported to Linux too for sake of writing apps for multiple operating systems from same codebase.

There are choices like cairo (or even OpenGL, although GTK uses Cairo) on sdl2 for low-level rendering, so if you're rendering widgets on a canvas, you should check that out.

**Comment by jeromelaban** [comment]
We're looking at Skia for a common rendering engine. Though it's a very large effort, particularly regarding the building of input controls, this may be useful at first for applications that don't rely too much on this kind of APIs.

Let's follow this here: https://github.com/nventive/Uno/issues/670

**Comment by wegel** [comment]
I'm very new to Uno, so please bear with me: since Xamarin (specifically Xamarin.Forms) now supports linux targets using GTK# (see https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/gtk?tabs=windows), would it be possible to add linux support to Uno ?

I know that the FAQ states that the current objective is for the wasm target to be sufficiently performant for linux, but I still think a more "native" linux target would be nice, especially considering that every other platfform out there has it (Windows, OSX, Android, iOS); the only one really missing is linux.

Thanks!

**Comment by trampster** [comment]
Eto.Forms also supports linux using GTK#. And it supports developing on linux using vscode. Until Uno can do that it's a non starter for us.

**Comment by jeromelaban** [comment]
@trampster we announced at UnoConf in our road map that we'll make architectural changes to allow for other rendering backends to be added more easily. 

GTK# can be one of those.

**Comment by MartinZikmund** [comment]
@trampster @wegel @fanol UnoConf 2020 is next week :-) . https://unoconf.com/

**Comment by handicraftsman** [comment]
I wonder if compiling and developing on Linux will be ever supported btw... (my PC is too old to run Windows + Visual Studio fast enough, but most Linux distros work fast with any editor/ide)

**Comment by xdrie** [comment]
https://platform.uno/blog/announncing-uno-platform-3-0-linux-support-fluent-material-and-more/

It's been officially announced that Uno will have proper linux support! There are also now [official instructions](https://github.com/unoplatform/uno/blob/master/doc/articles/get-started-with-linux.md) in this repository.

**Comment by jeromelaban** [comment]
It definitely is !! ;) Let's close this issue and track individual features now.

**Comment by xdrie** [comment]
Wonderful, a great thanks to all the Uno developers!!
