### ISSUE TITLE
[WSL GTK] OpenGL support check not working correctly

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#9506]
### Current behavior

When running Samples app GTK under WSL it reported OpenGL as supported, but then `GRGlInterface.Create()` call returned `null`.

### Expected behavior

Should mark OpenGL as supported only when actually supported

**Comment by MartinZikmund** [comment]
Note to self - can repro on my desktop PC in Prague

**Comment by jeromelaban** [comment]
Related to https://github.com/unoplatform/uno/issues/9099
