### ISSUE TITLE
XAML Reader seems unable to resolve resources declared inside the same document

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#9524]
### Current behavior

Try referencing a color from a brush from the same dynamic XAML supplied to the XamlReader and the inner lookup won't be resolved.

Go to this link on the Playground: https://playground.platform.uno/#9f266f8c

Observed result:
![image](https://user-images.githubusercontent.com/4174207/185041471-d439a105-9028-4ea0-a1bb-81a45007d184.png)

### Expected behavior

Expected result: (got with XAML Studio)

![image](https://user-images.githubusercontent.com/4174207/185041518-8067d598-4867-4940-a94c-e4f24ee183a1.png)

### How to reproduce it (as minimally and precisely as possible)

Playground: https://playground.platform.uno/#9f266f8c

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno 4.4

### Affected platforms

WebAssembly

### Anything else we need to know?

Observed on Wasm, but is probably present on all platforms.

**Comment by jeromelaban** [comment]
Some investigation: http://playground.platform.uno/#6f361b84 seems to show that the `b2` resource is resolved, but the `c2` resource is not resolved properly, probably because it's in the resource dictionary as well.
