### ISSUE TITLE
[Skia] Samples app favorites and recents are not persisted

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#9534]
### Current behavior

Favorite and recent samples in Samples app are not persisted over launches. Seen on Skia, but maybe on all platforms

### Expected behavior

Should be persisted

### How to reproduce it (as minimally and precisely as possible)

Mark anything as favorite, kill app and re-run it

**Comment by trungnt2910** [comment]
This is also reproducible from WASM.
