### ISSUE TITLE
[Skia] ImageBrush is not correctly filling the image and behaves the same on every Stretch setting

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#9537]
### Current behavior

ImageBrush inside ellipse is shown incorrectly
![ujt3](https://user-images.githubusercontent.com/6670150/185405651-b57116d5-2be6-4172-b253-29c871e8bd9b.jpg)

Link to snippet: http://playground.platform.uno/#1aaceedb

### Expected behavior

ImageBrush is filling image correctly based on Stretch property
![expected](https://user-images.githubusercontent.com/6670150/185406372-6a8b5d0a-793e-4b48-a8be-48b542a86e6b.png)

### How to reproduce it (as minimally and precisely as possible)

Repro
[SkiaImageBrushIssue.zip](https://github.com/unoplatform/uno/files/9374168/SkiaImageBrushIssue.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen)

### IDE

Visual Studio 2022

### IDE version

17.3.1

### Anything else we need to know?

Tested on version 4.5.0-dev.523

**Comment by mcNets** [comment]
I believe this issue can be closed as I tried with the current version 4.6 and it works.

**Comment by jeromelaban** [comment]
Thanks!

**Comment by FrozDark** [comment]
Not working 4.6 and 4.7.0-dev.626

**Comment by jeromelaban** [comment]
Let's followup in #10740
