### ISSUE TITLE
[WPF] PasswordBox is keeping the typed password revealed while focused

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#9544]
### Current behavior

PasswordBox is showing password while focused instead of obfuscating

### Expected behavior

PasswordBox should reveal password only on pressing the eye button in it

### How to reproduce it (as minimally and precisely as possible)

Repro
[WPFPasswordBoxIssue.zip](https://github.com/unoplatform/uno/files/9379301/WPFPasswordBoxIssue.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.3.1

### Anything else we need to know?

Tested on build 4.5.0-dev.523

**Comment by Youssef1313** [comment]
I'm going to look into this.
