### ISSUE TITLE
'Method not found' when  running sync generator

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#9560]
### Current behavior

![image](https://user-images.githubusercontent.com/31348972/185786031-d1f4eecd-1839-4b7e-aed1-5aca10f21156.png)

This is similar to https://github.com/unoplatform/uno/issues/9297, but when running sync generator.

### Expected behavior

Sync generator is run successfully.

**Comment by jeromelaban** [comment]
It should have been fixed by https://github.com/unoplatform/uno/commit/92025ee92ea13efc42771bcac3eb69118d1ede00, are you latest master?

**Comment by Youssef1313** [comment]
I don't remember, but I can't reproduce again. So I'm closing this. Thanks @jeromelaban
