### ISSUE TITLE
Installing Xamarin on VStudio 2022

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#9573]
## On which page?
https://platform.uno/docs/articles/get-started-vs.html?tabs=windows

## What's wrong?
"Mobile development with .NET (Xamarin) workload installed"
There is no such workload in VStudio 2022 v17.3.1 (at least in Enterprise Edition)

## Any feedback?
Probably "individual components", "Xamarin", but I'm not sure.

(and I want to install VStudio 2022 on my laptop, and use it to develop own apps ported to Uno/Xamarin) :)

**Comment by jeromelaban** [comment]
Thanks for the report. This particular page indicates VS 2022, but it's actually VS 2019-specific, as indeed, the Xamarin workloads is now a checkbox in VS 2022. See https://platform.uno/docs/articles/get-started-vs-2022.html?tabs=windows.
