### ISSUE TITLE
Visual studio 2022 high cpu usage related to uno platform

### ISSUE THREAD

**Issue by guillaume-brouillon** [unoplatform/uno#9575]
### Current behavior

I have the latest visual studio 2022 17.3.0 preview 4 and i don’t understand why it uses so much cpu while typing.
The spike is solely due to typing in visual studio.
According to the Microsoft Support Team, this problem is due to uno source generators.
https://developercommunity.visualstudio.com/t/Visual-studio-2022-high-cpu-usage-relate/10104416?port=1025&fsid=b48e28ae-6f7e-424a-a806-9763677db79a&entry=problem&space=8&q=uno&ref=native&refTime=1661261222052&refUserId=f7fa83d9-b51c-6ae2-8643-8f22adbc60b8

### Expected behavior

CPU usage is expected to be a lot lower.

### How to reproduce it (as minimally and precisely as possible)

Create Uno app with project template.
Type anything in visual studio.
You should see spiking cpu usage.

**Comment by jeromelaban** [comment]
Thanks for the report. We're tracking this https://github.com/unoplatform/uno/issues/7506, and we have no update for this yet.
