### ISSUE TITLE
[WASM] AutoSuggestBox still not working

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#9576]
### Current behavior

@jeromelaban @iury-kc AutoSuggestBox still is not working on WASM. Please see attached repo, there are 3 issues:

1) 
- start typing 'a'
- drop down comes up -> good. Now try to press CURSOR DOWN -> does not work -> bad

2) 
- click with mouse on any option in the drop down -> e.ChosenSuggestion is of type 'String', but should be 'Author' -> bad

3) (this can't be reproduced by the repo, but I see it in my app. I was unable to isolate by a repo. There must be some side effect involved, which I was unable to put my finger on)
- after setting 
```
	s.Text		= e.ChosenSuggestion.ToString();
	s.ItemsSource	= null;
```
... in OnQuerySubmitted then .OnTextChanged is fired again with e.Reason = .UserInput. This is wrong.

Honestly, this is starting to get frustrating. I was hoping after seeing [this ](https://github.com/unoplatform/uno/issues/7778)and [this ](https://github.com/unoplatform/uno/issues/7957)being fixed that we would be good now anf AutoSuggestBox would be working. Unfortunately that's not the case and the missing AutoSuggestBox support is a road block for my project.

Is there any chance to get this addressed any time soon?
[AutoSuggestBox4.zip](https://github.com/unoplatform/uno/files/9409592/AutoSuggestBox4.zip)

**Comment by jeromelaban** [comment]
Thanks for the report. Can you clarify why you mean by "Now try to press CURSOR DOWN" ? Do you mean using the keyboard down key?

**Comment by DierkDroth** [comment]
> Do you mean using the keyboard down key?

Yes, correct. Sorry, I should have been more clear

**Comment by MartinZikmund** [comment]
@DierkDroth For the keyboard input - which are the required platforms?

**Comment by DierkDroth** [comment]
@MartinZikmund thanks for asking: for now I'm working with WASM, but early next year I will do iOS and Android as well - guess keyboard input does not matter there, but anyway...

**Comment by DierkDroth** [comment]
@MartinZikmund unfortunately even [after these changes](https://github.com/unoplatform/uno/pull/10322) AutoSuggestBox still is not working as expected.

Please see attached repo and start typing some BS text in the AutoSuggestBox + RETURN -> notice the difference between WindowsAppSDK and UNO WASM. 
I also left some comments in MainWindows.xaml.cs (pls search for !!!)

Is there any chance to get this addressed?

[AutoSuggestBox5.zip](https://github.com/unoplatform/uno/files/10040763/AutoSuggestBox5.zip)

**Comment by MartinZikmund** [comment]
@DierkDroth definitely, will look into it. We will get there 😀 !

**Comment by DierkDroth** [comment]
@MartinZikmund much appreciated. Thanks

**Comment by DierkDroth** [comment]
@MartinZikmund would you have any update on this issue? 
Would you have any idea on the timeframe this could be addressed?

Thanks in advance

**Comment by DierkDroth** [comment]
Thanks for the update @jeromelaban. I'll re-run tests using latest UNO bits.
