### ISSUE TITLE
[Android] will carsh in _window.Content=rootFrame

### ISSUE THREAD

**Issue by Cricle** [unoplatform/uno#9582]
### Current behavior

crash always

### Expected behavior

running

### How to reproduce it (as minimally and precisely as possible)

![image](https://user-images.githubusercontent.com/26201412/186309587-972b11b2-5a34-449d-a6fb-5a6f17279b60.png)
My build config

### Workaround

Running on real machine or simulator

### Works on UWP/WinUI

No

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.UI.RemoteControl / Uno.WinUI.RemoteControl

### NuGet package version(s)

```
    <PackageReference Include="Uno.UI" Version="4.5.0-dev.584" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="4.5.0-dev.584" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.5.0-dev.584" />
```
 `4.5.0-dev584`, `4.5.0-dev562`, `4.4.13`  almost all version crash

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

Microsoft Visual Studio Enterprise 2022 (64 位) - Current

### Relevant plugins

    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />

    <PackageReference Include="CommunityToolkit.Mvvm">
      <Version>8.0.0</Version>
    </PackageReference>
    <PackageReference Include="DryIoc.Microsoft.DependencyInjection">
      <Version>6.0.2</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection">
      <Version>6.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <Version>6.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http">
      <Version>6.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications">
      <Version>7.1.2</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.UI.Xaml">
      <Version>2.7.0</Version>
    </PackageReference>
    <PackageReference Include="Structing">
      <Version>1.3.1</Version>
    </PackageReference>
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid">
      <Version>7.1.11</Version>
    </PackageReference>
    <PackageReference Include="Uno.Microsoft.Xaml.Behaviors.Uwp.Managed">
      <Version>2.3.1-uno.2</Version>
    </PackageReference>

### Anything else we need to know?

```
[41m[30mfail[39m[22m[49m: Uno.UI.DataBinding.BindingPropertyHelper[0]
      The [ScrollViewer] property getter does not exist on type [Windows.UI.Xaml.Controls.TextBox]
[41m[30mfail[39m[22m[49m: Uno.UI.DataBinding.BindingPropertyHelper[0]
      The [ScrollViewer] property getter does not exist on type [Windows.UI.Xaml.Controls.PasswordBox]
[libc] Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7fda769fe0 in tid 30942 (PDA.PDA), pid 30942 (PDA.PDA)
```

**Comment by Cricle** [comment]
In dev time, I have almost no problem. But I switch to `Release` archived once, The crash will happen forever, thouse is delete bin/obj, restart vs/compute, use other version package.

**Comment by Cricle** [comment]
![image](https://user-images.githubusercontent.com/26201412/186310953-039e3844-94e0-4462-bbb4-5e701a2d921e.png)

**Comment by MartinZikmund** [comment]
@Cricle The root cause of the problem will be too find the cause of the `NullReferenceException`. Does this occur only on Android or can you reproduce on some other platform too?

**Comment by Cricle** [comment]
> @Cricle The root cause of the problem will be too find the cause of the `NullReferenceException`. Does this occur only on Android or can you reproduce on some other platform too? Can you create a small repro that shows the problem?

No, I only can try in android and uwp, but uwp is normal. I turn on/off `ABI` or `aapt2`, in rare cases, it will normally enter the app, and next start time will throw `NullReferenceException`.

**Comment by Cricle** [comment]
Problems with my code, sorry.
But I don't know why throw `NullReferenceException`.

Try `AOT` and `Tailor` compile runtime will throw `NullReferenceException`, i will commit a new issure.

![image](https://user-images.githubusercontent.com/26201412/186348927-2bd3bf75-70c7-471a-b104-2c10601a4bc0.png)
