### ISSUE TITLE
[WASM] `Loading` triggered although `FrameworkElement` is not part of the visual tree

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#9587]
### Current behavior

@jeromelaban FYI

I was chasing an issue where clearly .Loading was triggered although the FrameworkElement was not part of the visual tree. I spent > 1 hour to create a repo, but failed. Likely since the actual scenario is pretty complicated.

Anyway, from what I understand by debugging my WASM and WindowsAppSDK heads these are the contributing factors:
- there needed to be a visual tree a couple of levels deep, just 1 or 2 won't do
- remove a branch somewhere in the middle from the visual tree. The branch itself needed to be a couple of levels deep too
- now add an element to the branch -> .Loading is fired on WASM for that element -> **wrong**
- .Loading only should be fired as you again added back the branch to the visual tree. This works for WindowsAppSDK but not for WASM

I put a workaround in place for my app, but I could see this hitting me again down the road.
This is latest UNO dev bits.

FWIW

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by jeromelaban** [comment]
Thanks for the report. It may be related to https://github.com/unoplatform/uno/issues/3519, but we have not noticed this specific behavior when parts of the tree are leaving then entering the tree. You mentioned that you don't have a repro, but if you end up finding one, let us know.

**Comment by DierkDroth** [comment]
Sounds good @jeromelaban 

I liked to emphasize that the important piece of scenario above is that the branch where the element was added had to be part of the visual tree before.

**Comment by Youssef1313** [comment]
This could be fixed already

**Comment by DierkDroth** [comment]
Thanks for the update @Youssef1313

**Comment by morning4coffe-dev** [comment]
@MartinZikmund, @DierkDroth From my testing this seems to be resulting with the same behavior across targets on the latest dev Sdk `5.5.0-dev.110`. As you didn't provide concrete repro, there might have been some other issue, but from what you described, this seems to be working well now. Feel free to reopen, if you stumble upon this issue again.
