### ISSUE TITLE
[Skia] GTK OpenGL Acceleration is clipping content incorrectly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#9605]
### Discussed in https://github.com/unoplatform/uno/discussions/9581

<div type='discussions-op-text'>

<sup>Originally posted by **LISPos** August 23, 2022</sup>
I ran it in skia.gtk environment
No borders for buttons or controls are drawn.
In wasm and wpf.host , the output is normal.
A problem occurs in skia.gtk.
Is the graphics output different on linux platforms?

![b1](https://user-images.githubusercontent.com/20689998/186295365-3e521f1a-9cf8-4ee8-91d0-b52b26803f4c.PNG)
</div>

**Comment by jeromelaban** [comment]
@MartinZikmund this one is fixed, right?

**Comment by MartinZikmund** [comment]
@jeromelaban Should be by https://github.com/unoplatform/uno/pull/10455 closing 👍
