### ISSUE TITLE
`GenerateNestingContainers` puts classes in wrong order

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#9612]
### Current behavior

For `DependencyPropertyGenerator` and `DependencyObjectGenerator`, the implementation of `GenerateNestingContainers` is incorrect.

Code like this:

![image](https://user-images.githubusercontent.com/31348972/186768478-06bc7b2e-006a-4026-8938-a2e3c5aec403.png)

generates incorrect code:

![image](https://user-images.githubusercontent.com/31348972/186768619-6772d04f-a07e-4758-90a7-b6b2f08d2abc.png)

### Expected behavior

Order is of nesting is preserved.

**Comment by jeromelaban** [comment]
Nice find!
