### ISSUE TITLE
[WASM] TextBlock.Inlines not working correctly

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#9625]
### Current behavior

It's my understanding that TextBlock.Inlines should be working as per [here ](https://platform.uno/docs/articles/supported-features.html), [here ](https://github.com/unoplatform/uno/pull/6672)and [here](https://github.com/unoplatform/uno/issues/3041). Unfortunately that's not the case.

Please see attached and compare the output on WASM and WindowsAppSDK. Please modify the test string to see that regular text runs are not handled correctly. Is this still the limitation as mentioned by @davidjohnoliver?

[Inlines.zip](https://github.com/unoplatform/uno/files/9435113/Inlines.zip)

### Expected behavior

WASM should as work as WindowsAppSDK

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by Youssef1313** [comment]
I think `TextBlock` doesn't have any issues. The issue is likely caused by a `XamlReader` bug

**Comment by DierkDroth** [comment]
Thanks @Youssef1313 @jeromelaban. Appreciated
