### ISSUE TITLE
[Android][iOS] TimePicker doesn't update SelectedTime Property

### ISSUE THREAD

**Issue by Soap-141** [unoplatform/uno#9629]
### Current behavior

When the selected time is changed, the property is never updated, meaning that every binding are also not updated.

### Expected behavior

The selected time property should be updated when the user select another value.

![Animation_54](https://user-images.githubusercontent.com/57812285/186964133-6a9f2129-31da-41dc-95fb-331579c53d23.gif)

### How to reproduce it (as minimally and precisely as possible)

1. Download [SampTimePicker.zip](https://github.com/unoplatform/uno/files/9435352/SampTimePicker.zip) 
2. Start the solution
3. Start the project on WinUI
4. Select a new value for the `TimePicker`
5. Notice the `TextBlock` changed
6. Repeat steps 4 & 5
7. Start the project on Android & iOS
8. Select a new value for the `TimePicker`
9. Notice the `TextBlock` is not updated.

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

`Uno.WinU`I: 4.5.0-dev.633

### Affected platforms

iOS, Android

### IDE

Visual Studio 2022

### IDE version

17.3.2

**Comment by Youssef1313** [comment]
`SelectedTime` is marked as not implemented.

https://github.com/unoplatform/uno/blob/c94d459528296a91d0ac6cac89b3c78304f11b49/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TimePicker.cs#L81-L94

https://github.com/unoplatform/uno/blob/c94d459528296a91d0ac6cac89b3c78304f11b49/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TimePicker.cs#L136-L143

**Comment by Youssef1313** [comment]
I'm going to work on this.
