### ISSUE TITLE
[WASM] DependencyObject.ClearValue not working correctly

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#9640]
### Current behavior

Please see attached and search MainPage.xaml.cs for '!!!' (I added a few comments)

[ClearValue.zip](https://github.com/unoplatform/uno/files/9438210/ClearValue.zip)

### Expected behavior

WASM should work as WindowsAppSDK

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by DierkDroth** [comment]
@jeromelaban @Youssef1313 is there any chance to get this closed off any time soon or should I rather invest in trying to find a work around?

**Comment by jeromelaban** [comment]
We do not have a priority set for this issue yet, as the created PR draft still needs work.

**Comment by DierkDroth** [comment]
Thanks for letting me know @jeromelaban

**Comment by DierkDroth** [comment]
Confirmed closed. Thanks @jeromelaban @Youssef1313
