### ISSUE TITLE
[WASM] `Canvas.Background` rendering not working correctly

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#9651]
### Current behavior

Please see attached: Canvas.Background should be filled completely - even 'outside' of what's visible at that point.

[Canvas.zip](https://github.com/unoplatform/uno/files/9443386/Canvas.zip)

### Expected behavior

WASM should work as WindowsAppSDK

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by MartinZikmund** [comment]
Interestingly, `Canvas` does not clip similarly to other panels like `Border`. For example:

```csharp
Content = new Grid
{
	Margin = new Thickness(100),
	Height		= 100,
	Width		= App.Window.Bounds.Width,
	Background = new SolidColorBrush(Colors.Red),
	Children	=
	{
		new Microsoft.UI.Xaml.Controls.Canvas
		{
			Background			= new SolidColorBrush(Microsoft.UI.Colors.Blue),
			Height				= 400,
			HorizontalAlignment	= HorizontalAlignment.Left,
			RenderTransform		= new TranslateTransform(),
			Width				= 200,
		}
		// moving the canvas up shows that the bottom part of the canvas was not 'filled' with correct .Background brush
		//.OnLoaded((s, e) => ((s as Microsoft.UI.Xaml.Controls.Canvas).RenderTransform as TranslateTransform).Y = -0.5 * App.Window.Bounds.Height),
	},
};
```

Produces:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/1075116/190139365-e00fe315-a059-4df5-b64f-7948f4ecba68.png">

Whereas:

```csharp
Content = new Grid
{
	Margin = new Thickness(100),
	Height		= 100,
	Width		= App.Window.Bounds.Width,
	Background = new SolidColorBrush(Colors.Red),
	Children	=
	{
		new Microsoft.UI.Xaml.Controls.Border
		{
			Background			= new SolidColorBrush(Microsoft.UI.Colors.Blue),
			Height				= 400,
			HorizontalAlignment	= HorizontalAlignment.Left,
			RenderTransform		= new TranslateTransform(),
			Width				= 200,
		}
		// moving the canvas up shows that the bottom part of the canvas was not 'filled' with correct .Background brush
		//.OnLoaded((s, e) => ((s as Microsoft.UI.Xaml.Controls.Canvas).RenderTransform as TranslateTransform).Y = -0.5 * App.Window.Bounds.Height),
	},
};
```

Produces:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/1075116/190139501-bfce8823-f65d-4f7c-bcbb-e3b16cdf81ff.png">

**Comment by carldebilly** [comment]
## Reproduction in Playground + XAML Studio
Just reproduced it in the Playground: https://playground.platform.uno/#4e6b6176 with the following XAML:

``` xml
<Grid Margin="100" Height="100" Background="Red" HorizontalAlignment="Stretch">
    <Canvas Background="Blue" Width="200" MinHeight="400" HorizontalAlignment="Left" />
</Grid>
```

I also confirm it's producing the same result as @MartinZikmund's screenshots on both Uno (clipped result) and XAML Studio (expected result)

## Potential cause
I see 2 concurrent bugs in this result:

1. The `<Canvas />` is arranged to 100px instead of the expected 400px
    ![image](https://user-images.githubusercontent.com/4174207/197027877-b56f7a70-b2f7-43a0-aeb4-424e9ae6c7d8.png)
2. For some reason _a Canvas can't be clipped_ in Windows. That's something new for me and very weird. The understood rule was _a Canvas must never clip his children_.

**Comment by francoistanguay** [comment]
Can I please understand @DierkDroth  what's the use case for having a Canvas not clipped by the bounds of a parent? I too find it an odd behavior of WinUI and would like to understand the context of this.

**Comment by DierkDroth** [comment]
@francoistanguay 

Thanks again for getting back to me.

The real use case is a bit harder to describe:
- there is a (custom) calendar control showing all days of the weeks horizontally and the hours of the day vertically
- the vertical hours won't fit on screen which is why there is a ScrollViewer
- the hours legend (= Canvas) has a dedicated .Background and needed to stretch to the full .Height (including the non-visible part)
- as the ScrollViewer is scrolled up to 'see the rest of the day', you would see that the .Background of the hours legend was clipped **-> wrong**

Hope this makes it clearer. I could show you in the real app if needed.

**Comment by francoistanguay** [comment]
Yeah, I cant really understand it without a proper sample. Question was more about why Canvas needed to be within the bounds of a smaller Grid and get clipped instead of being outside it.

**Comment by francoistanguay** [comment]
Are you able to repro the issue with simpler demo/values? Without doing Windows Bounds * 2 and Render Transforms and a bunch of things?

LIke what is the CORE issue? That a Canvas contained in a Grid is Clipped by the Grid's height? Then my question is why do you need to wrap the Canvas in a Grid smaller than your Canvas?

I need a straightforward repro.

**Comment by DierkDroth** [comment]
>> why do you need to wrap the Canvas in a Grid smaller than your Canvas
@francoistanguay why do you feel the Grid is smaller than the Canvas. They both have **the same height** in my sample.

I have feeling we might not be on the same page and/or I'm misunderstanding something. Could you please clarify? Thanks

**Comment by francoistanguay** [comment]
Then put screenshots in your issue and document Actual and Expected states please.

**Comment by DierkDroth** [comment]
@francoistanguay I'm sorry but I really am not sure what you're asking for:
- expected state: what you see in my repo as WindowsAppSdk head
- actual (wrong) state: what you see in my repo as WASM head

You will notice that both are different, which demonstrates that WASM is wrong.

I could show you screenshots from my real app (actually the app is not working at this point though, since I'm transitioning some logic not related to this very problem). However, you would see that the bottom part/background is not rednered properly when it's 'moved up' (by a scrollviewer in the real app and not by code as in the repo). Is that what you're asking for? Or something else?

**Comment by francoistanguay** [comment]
I was asking for some screenshots. It helps to dispatch issues without having to download/build/inspect every single repro. Am ok with screenshots from the repro. Thanks.

**Comment by DierkDroth** [comment]
@francoistanguay thanks for clarification. 

I'll get back you with the screenshot (WindowsAppSdk + WASM to compare) of my real app when I'm doing me next round of UNO WASM testing (likely as .NET7 is released in 2 weeks).

**Comment by francoistanguay** [comment]
Ok, but honestly I'd prefer screenshots from the repro if they show the issue as well as this is what devs would start from to try to repro/fix.

One other reason am asking for more details is the original issue didnt mention ScrollViewer, and now you're mentioning it, so trying to understand the real (and simplest) issue.

**Comment by DierkDroth** [comment]
@francoistanguay ok I attached screenshots from the repo above (which you could run yourself quite easily).

This is a simplest form of the issue and at the same time close as possible to the real app.

Hope this helps.

WindowsAppSdk
<img width="951" alt="image" src="https://user-images.githubusercontent.com/26179242/198037793-d722bac5-9d0b-4350-9df6-562b7b9c2d49.png">

UNO WASM
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26179242/198037928-39aecdd9-6493-4f76-a163-126187cc97b7.png">

**Comment by DierkDroth** [comment]
@francoistanguay here is a screenshot of the rela problem in the actual app (after updating to latest UNO bits + .NET 7).

Please let me know if you needed else to see the scope of the issue. Thanks

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26179242/202693491-763379f3-7620-45c1-b00f-d04a13b72b70.png">

**Comment by DierkDroth** [comment]
@francoistanguay @carldebilly @MartinZikmund is there any chance to get this addressed?

Please let me know if it's still not clear what the problem is.

I also would appreciate if you saw a workaround and would let me know. Thanks

**Comment by Youssef1313** [comment]
#13593 might fix this

**Comment by DierkDroth** [comment]
Thanks for letting me know @Youssef1313

**Comment by DierkDroth** [comment]
@Youssef1313 thanks for the update. 

However, before quite a while I have put a work around in place for the case which I ran into. Hence, I no longer have a scenario where I could reproduce the issue and/or confirm it's fixed. Sorry...

**Comment by Youssef1313** [comment]
This is still reproducing on matser, but #13695 will fix it.
