### ISSUE TITLE
[iOS][Android] Issues with Snap Points for ListView 

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#9654]
### Current behavior

Currently, using snap points within the template for a ListView causes "phantom" scrolling to occur on Android. The very first time you swipe through/scroll a list with snap point, the items will scroll back and forth a few time before finally coming to a rest. After the initial scrolling issues, the items will begin to snap properly.

Phantom Scrolling:
![snap-bug2](https://user-images.githubusercontent.com/4793020/187242753-23b8b925-f434-47fe-bee8-e604bd29a1ee.gif)

Appears to work fine after initial random scrolling:
![snap-working2](https://user-images.githubusercontent.com/4793020/187242755-9dbeca0e-6c10-4553-bbd1-fe66b55e9819.gif)

On iOS, snapping works for the most part except it seems like I cannot snap the first element in the list. Maybe just be a sizing issue? But near the end of the GIF, you can see that the second item will always stay snapped.

![iossnap](https://user-images.githubusercontent.com/4793020/187243049-229a157e-aacf-4d8d-8cdb-f25012490e50.gif)

### Expected behavior

Snapping should occur without any glitches

### How to reproduce it (as minimally and precisely as possible)

Repro attached

[SnapSample.zip](https://github.com/unoplatform/uno/files/9446081/SnapSample.zip)

**Comment by Guidemarcus** [comment]
[PeekingFlipViewFlicker.Shared.zip](https://github.com/unoplatform/uno/files/9853976/PeekingFlipViewFlicker.Shared.zip)


Ok so for some reason, I cannot attach the whole solution. Even when deleting bin/obj folders, it is too big. Here is the shared folder with all the logic of the custom control we are using.

**Comment by kazo0** [comment]
[SnapPointSample.zip](https://github.com/unoplatform/uno/files/9856480/SnapPointSample.zip)

Attached simpler sample with just a vanilla ListView

**Comment by kazo0** [comment]
@Xiaoy312, I'm assuming https://github.com/unoplatform/uno/pull/10390 fixes part of this? At least the Android part?

**Comment by Xiaoy312** [comment]
re: https://github.com/unoplatform/uno/issues/9654#issuecomment-1326531563
it should address the oscillation on android
and snapping not working for 1st or last items on all-plat

**Comment by Xiaoy312** [comment]
@Guidemarcus https://github.com/unoplatform/nventive-private/blob/master/doc/reduce-sample-size.md

**Comment by Xiaoy312** [comment]
closing this as the PR has been merged
