### ISSUE TITLE
WasmHttpHandler crushes with ArgumentNullException in case response.payload is null

### ISSUE THREAD

**Issue by sady4850** [unoplatform/uno#9662]
### Current behavior

Currently `Uno.UI.Wasm.WasmHttpHandler` fails to process responses with null payloads

```
System.ArgumentNullException: Value cannot be null. (Parameter 's')
at System.Convert.FromBase64String(String s) in /__w/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/libraries/System.Private.CoreLib/src/System/Convert.cs:line 2565
at Uno.UI.Wasm.WasmHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\a\1\s\src\Uno.UI.Runtime.WebAssembly\WasmHttpHandler.cs:line 72
```

### Expected behavior

```
var responseContent = new ByteArrayContent(Convert.FromBase64String(response.payload));
responseMessage.Content = responseContent;
```
A 'reposponse.payload' should be checked for null before passing it to 'Convert.FromBase64String'. In case it is null `responseMessage.Content` should be just null.

### Environment

Uno.UI / Uno.UI.WebAssembly

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
Thanks for the report, The `WasmHttpHandler` is no longer required and `HttpClient` can be used (similar to https://github.com/unoplatform/uno/issues/3525#issuecomment-792353837). If you used documentation that mentioned this, can you point us to it?

**Comment by sady4850** [comment]
[Azure Authentication with MSAL](https://platform.uno/docs/articles/interop/MSAL.html) mentions `WithUnoHelpers()` which actually injects `WasmHttpFactory.Instance` which uses `WasmHttpHandler`

```
	public static class AbstractApplicationBuilderExtensions
	{
		/// <summary>
		/// Add required helpers for the current Uno platform.
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static T WithUnoHelpers<T>(this T builder)
			where T : AbstractApplicationBuilder<T>
		{
#if __ANDROID__ && !NET6_0_OR_GREATER
			(builder as PublicClientApplicationBuilder)?.WithParentActivityOrWindow(() => ContextHelper.Current as Android.App.Activity);
#elif __IOS__ && !NET6_0_OR_GREATER
			(builder as PublicClientApplicationBuilder)?.WithParentActivityOrWindow(() => Windows.UI.Xaml.Window.Current.Content.Window.RootViewController);
#elif __WASM__
			builder.WithHttpClientFactory(WasmHttpFactory.Instance);
#endif
			return builder;
		}
	}
```

**Comment by jeromelaban** [comment]
Thanks for the details!

**Comment by sady4850** [comment]
Ok, if you know it is not needed now why just not to remove it from the repo ? Or at least to mark it with `[ObsoleteAttribute]` attribute so people do not waste their time dealing with it ?

**Comment by jeromelaban** [comment]
The obsolete attribute is not an appropriate way for handling this, though we can add an analyzer to mark this type as deprecated. Let's track this with https://github.com/unoplatform/uno/issues/9665.

**Comment by sady4850** [comment]
Could you please clarify also if it is correct that WasmHttpHandler is used for handling requests in [Uno.UI.js ](https://github.com/unoplatform/uno/blob/99590422b77e8a774ca5196af0b63fa574690520/src/Uno.UI/WasmScripts/Uno.UI.js)  ?

**Comment by jeromelaban** [comment]
`WasmHttpHandler` should not be used anymore. The code present in Uno.UI.js is support for that C# class, and is not used in another condition. You can use `HttpClient` instead.
