### ISSUE TITLE
[Gallery][Skia.GTK]RadioButton(Fluent)-  Shape of the circle for radio buttons is not properly displayed as a circle.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#9671]
### Current behavior

![RB issue](https://user-images.githubusercontent.com/74563602/187536908-c6c62aed-9fa4-4f76-8dab-cf4a8a2d2cd8.png)

### Expected behavior

![RB Correct](https://user-images.githubusercontent.com/74563602/187536927-b0de0519-340b-4b6a-9f93-d4c715365e11.png)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app on Skia.GTK
2. Click on the "Radiobutton" item from the list.
3. Observe that the shape of the circle for radio buttons is not properly displayed as a circle.

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by MartinZikmund** [comment]
@jeromelaban I think this should be fixed by your recent change, right?
