### ISSUE TITLE
[WASM] PasswordBox.Visibility = Collapsed not working

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#9678]
### Current behavior

Please see attached: PasswordBox won't 'hide' as the button is clicked.

[PasswordBox.zip](https://github.com/unoplatform/uno/files/9460637/PasswordBox.zip)

### Expected behavior

WASM should work as WindowsAppSDK

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by Youssef1313** [comment]
I'll take a look.

**Comment by DierkDroth** [comment]
@Youssef1313 appreciated

**Comment by jeromelaban** [comment]
@Youssef1313 Interestingly, it only works if another control changes visibility in the same tree: https://playground.platform.uno/#a081bdde.

**Comment by DierkDroth** [comment]
Thanks @Youssef1313 @jeromelaban
