### ISSUE TITLE
`[InjectedPointer]` might be used incorrectly in UI tests

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#9697]
### Current behavior

All applications of `InjectedPointerAttribute` are in UI Tests. It looks like this attribute doesn't have any effect on UI tests. It's only used by runtime tests.

https://github.com/unoplatform/uno/blob/fe3b4d19905492963207c3107abe9fe1039af225/src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestMethodInfo.cs#L84-L95

https://github.com/unoplatform/uno/blob/fe3b4d19905492963207c3107abe9fe1039af225/src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs#L706

### Expected behavior

The attribute shouldn't be linked here:

https://github.com/unoplatform/uno/blob/fe3b4d19905492963207c3107abe9fe1039af225/src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj#L47-L49

All applications of the attribute should be revised.

cc @dr1rrb

**Comment by MartinZikmund** [comment]
I think it is intentional - the tests are then imported and run via Runtime tests too - https://github.com/unoplatform/uno/blob/aab86870f6a7c68625e08459ba88e2343fad7877/src/Uno.UI.RuntimeTests/UITestsImport.props

**Comment by Youssef1313** [comment]
Nice! I didn't know they're imported that way. Thanks @MartinZikmund. I'm going to close
