### ISSUE TITLE
FrameworkElement.ArrangeOverride incorrectly arranges the first item

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#97]
When creating a custom panel, the FrameworkElement.ArrangeOverride https://github.com/nventive/Uno/blob/ab52b7186769f80ed890741bcfa377cb6f38a7b7/src/Uno.UI/UI/Xaml/FrameworkElement.cs#L138 default implementation incorrectly arranges the first UIElement.

**Comment by carldebilly** [comment]
This issue is replaced by https://github.com/unoplatform/uno/issues/1554.  Closing this one.
