### ISSUE TITLE
Windows.Storage.Pickers download not working in Chrome

### ISSUE THREAD

**Issue by brookslindseyjr** [unoplatform/uno#9705]
### Current behavior

When initiating a download using the following sample code:
https://platform.uno/docs/articles/features/windows-storage-pickers.html#downloadupload-pickers
the file picker shows up and creates the temp file, but only downloads the file (shows up at the bottom of the browser as downloading) in Brave (1.42.97) and not in Chrome (105.0.5195.54 (Official Build) (64-bit)).

### Expected behavior

The file is downloaded in Chrome.

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI 4.4.20
Bootstrap 3.3.1

### Affected platforms

WebAssembly

### IDE version

Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.2.5

**Comment by jeromelaban** [comment]
@brookslindseyjr Can you try and see if the sample here: https://uno-ui-samplesapp-staging.azurewebsites.net (Section `Windows.Storage`, `FileSavePickerTests`) works for you? It does for me, using `DocumentsLibrary` as the start location, for instance.

**Comment by brookslindseyjr** [comment]
Yes, that worked! But is that code the same as the one in the link I posted?

**Comment by jeromelaban** [comment]
[This](https://github.com/unoplatform/uno/blob/97a414f7c4312b51fb40f207678f57aaf3e587d7/src/SamplesApp/UITests.Shared/Windows_Storage/Pickers/FileSavePickerTests.xaml.cs) is the code for that sample. Maybe it's related to the use of the native picking? Which mode are you using?

**Comment by brookslindseyjr** [comment]
Ah! The WasmPickerConfiguration.DownloadUpload mode fixed it. I'll take a look at the sample and some documentation a little more to understand the purpose of these different modes. Thanks!
