### ISSUE TITLE
IndentedStringBuilder uses Regex to perform indentation

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#9715]
### Current behavior

This method is used by `IndentedStringBuilder` and causes a lot of string allocations and performance impact by the use of Regex:
https://github.com/unoplatform/uno/blob/b671f1de73245cf57265af112bd5b3c9da4e403f/src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions/StringExtensions.cs#L242

The idea behind this feature is that if there are multiple lines, all these lines should be indented the same, but in most of the generator's use of `IndentedStringBuilder`  single line strings are created. We should be changing this code to either detect if there are actually new lines in the string to avoid the use of Regex, or simply make a second version of index called `IndentMultiLine` or similar which allows for single-line indentation to be used by `IndentedStringBuilder`.

### Anything else we need to know?

Related to https://github.com/unoplatform/uno/issues/7506

**Comment by workgroupengineering** [comment]
In oltre sostituirei, solo per il source generator,  StringBuilder con [ZStringBuilder](https://github.com/Cysharp/ZString).
