### ISSUE TITLE
Cache XAML parsing

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#9716]
### Current behavior

When using the XAML generator, in the context of Design Time, the instance of the generator is kept alive for an extended period of time, and generation performance is important. 

The XAML Generator parses XAML files on every run, but it may be that in many cases, the parsing could be cached and reused for any subsequent run.

We should be able to modify:
https://github.com/unoplatform/uno/blob/5fb1bca0614e83a5ae3a878dd48abe62a2400892/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileParser.cs#L36

to include a cache based on path and hash of the file to provide an already parsed result, likely as a static member.

It would also be important to provide a cache pruning mechanism based on last-used time (e.g. remove the file if not used after 1 hour, TBD more precisely)

### Anything else we need to know?

Related to https://github.com/unoplatform/uno/issues/7506

**Comment by Youssef1313** [comment]
@jeromelaban It looks like parsing is affected by some MSBuild properties (e.g, `ExcludeXamlNamespacesProperty` and `IncludeXamlNamespacesProperty`):

https://github.com/unoplatform/uno/blob/4666c66d75ea47c9156ea79c5d1e83465fdf570d/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileParser.cs#L120-L124

I think these should be taken into account in addition to the hash of the file.
