### ISSUE TITLE
"$(_CurrentTrimmedAndroidSDLVersion)" that evaluates to ""

### ISSUE THREAD

**Issue by inforithmics** [unoplatform/uno#9723]
### Current behavior

Build does not work following message occours

C:\Users\User\.nuget\packages\uno.ui\4.4.20\buildTransitive\net6.0-android30.0\uno.winui.common.targets(199,7): error M
SB4086: A numeric comparison was attempted on "$(_CurrentTrimmedAndroidSDLVersion)" that evaluates to "" instead of a n
umber, in condition "'$(_CurrentTrimmedAndroidSDLVersion)' < '$(UnoUIMinAndroidSDKVersion)'". [C:\GitHub\Mapsui\Mapsui.
UI.Uno\Mapsui.UI.Uno.csproj]

### Expected behavior

Compiles without Error Message

### How to reproduce it (as minimally and precisely as possible)

SourceCode:
https://github.com/Mapsui/Mapsui/pull/1695

.nuget/nuget restore Mapsui.sln

dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno/Mapsui.Samples.Uno.Mobile/Mapsui.Samples.Uno.Mobile.csproj

### Workaround

Not yet found.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.4.20 ( I tested with newest Development Version still didn't work).

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.3

### Relevant plugins

Resharper (But Fails on github Action too where no Resharper is installed).

### Anything else we need to know?

Central Package Management is used but I don't think that this is the problem

Attached BinLog where the Error occours.

[Uploading msbuild.zip…]()

What I find strange is that the Error occours in a uno.winui.common file even if it is a uno.ui project
C:\Users\User\.nuget\packages\uno.ui\4.4.20\buildTransitive\net6.0-android30.0\uno.winui.common.targets(199,7): error MSB4086: A numeric comparison was attempted on "$(_CurrentTrimmedAndroidSDLVersion)" that evaluates to "" instead of a number, in condition "'$(_CurrentTrimmedAndroidSDLVersion)' < '$(UnoUIMinAndroidSDKVersion)'". [C:\GitHub\Mapsui\Mapsui.UI.Uno\Mapsui.UI.Uno.csproj]

**Comment by jeromelaban** [comment]
It seems that your solution is using a feature we're never used before (it looks like the publishing happens automatically) causing this task to fail.

As a workaround, you can use `/p:_AndroidApiLevel=31` at the command line or set the property temporarily in your `.Mobile` csproj.

**Comment by inforithmics** [comment]
Thanks setting this in the Project File worked (When I put a condition in front it didn't work) so for me it seems that Android Targets are evaluated when not in an Android TargetFramework.
<_AndroidApiLevel>31</_AndroidApiLevel>
