### ISSUE TITLE
Mica material needed for UnoPlatform apps

### ISSUE THREAD

**Issue by DmitryBorodiy** [unoplatform/uno#9751]
Hello, Uno Platform team!
Why don't you implement Mica(WinUI) material in the Uno Platform?

[https://docs.microsoft.com/en-us/windows/apps/design/style/mica](url)

- [ + ] iOS
- [ + ] Android
- [ + ] WebAssembly
- [ + ] macOS
- [ + ] Skia
  - [ + ] WPF
  - [ + ] GTK (Linux)
  - [ + ] Tizen
- [ + ] Windows
- [ + ] Solution Templates

Thank you!

**Comment by MartinZikmund** [comment]
Mica itself is handled gracefully by adhering to light and dark theme correctly. However, we do not use the OS wallpaper as the source. This should be possible on some targets like Android, where querying the current system theme is possible. Closing this issue in favor of #8516
