### ISSUE TITLE
Community Toolkit Labs: `NavigationView` Icons are cut-off after update to new icon font

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#9772]
### Current behavior

See https://github.com/CommunityToolkit/Labs-Windows/pull/271#issuecomment-1240652925

**Comment by jeromelaban** [comment]
This may be related to font loading and proper measurement? (Where preloading may help)

**Comment by MartinZikmund** [comment]
@jeromelaban I think the preloading is already in place in the CSS-based form, so I guess it might be something else 🤔 https://github.com/CommunityToolkit/Labs-Windows/blob/main/platforms/CommunityToolkit.Labs.Wasm/WasmCSS/Fonts.css

**Comment by MartinZikmund** [comment]
Resolved thanks to @NVLudwig , closing
