### ISSUE TITLE
[Performance] Consider avoiding symbol visitors in source generators

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#9791]
https://github.com/unoplatform/uno/blob/88d7a4024ccdcaa07a6b8cd056ba55ef4e92865e/src/SourceGenerators/Uno.UI.SourceGenerators/NativeCtor/NativeCtorsGenerator.cs#L33-L34

https://github.com/unoplatform/uno/blob/88d7a4024ccdcaa07a6b8cd056ba55ef4e92865e/src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs#L32-L33

Also doing the same in #6937

Using `RegisterForSyntaxNotifications` might be more performant. It's not available in Uno.SourceGeneration, unfortunately.

We could:

- Try to implement it for Uno.SourceGeneration.
- Conditionally compile the generators, for Uno keep the existing approach, and for Roslyn use `RegisterForSyntaxNotifications`. It might be pain though.

From Roslyn Discord:

![image](https://user-images.githubusercontent.com/31348972/189491487-063b5c5e-7c23-42d8-bbdc-225695265a19.png)

![image](https://user-images.githubusercontent.com/31348972/189491514-f1753d21-b134-4b0a-a1c1-e4dbcb7071d6.png)

**Comment by jeromelaban** [comment]
Let's see what the performance improvements are with some of the latest changes I'm making with https://github.com/unoplatform/uno/pull/9784, and we may be able to remove the use of Uno.SourceGeneration altogether.

**Comment by Youssef1313** [comment]
> Let's see what the performance improvements are with some of the latest changes I'm making with https://github.com/unoplatform/uno/pull/9784, and we may be able to remove the use of Uno.SourceGeneration altogether.

Nice!! It's going to be very great if we could!

**Comment by Youssef1313** [comment]
@jeromelaban Now that #9784 is merged, was it possible to always use Roslyn generation? Is this issue can be worked on now or should I wait for something?

**Comment by jeromelaban** [comment]
I still don't know if we'll be able to do this. We'll have let https://github.com/unoplatform/uno/pull/9808 be tested a bit more until we can do something about it.

**Comment by Youssef1313** [comment]
This doesn't seem to improve performance for some unknown reason. Let's close
