### ISSUE TITLE
[Skia] The text is "jumping" when entering text in the calculator

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#9813]
### Current behavior

Open calculator on a slow Linux device (RPi3), notice that entering numbers shows the TextBlock showing the numbers is aligning left, then right, making it visually jump.

### Expected behavior

The text does not jump left to right.

### NuGet package version(s)

4.5.8

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by FrozDark** [comment]
Looks like the same but icon https://github.com/unoplatform/uno/issues/9541
