### ISSUE TITLE
Update Wasm SamplesApp to Bootstrap 3.0+ to allow easy debugging

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#9817]
https://github.com/unoplatform/uno/blob/master/doc/articles/debugging-wasm.md#using-visual-studio

> In the NuGet Package Manager, update Uno.Wasm.Bootstrap and Uno.Wasm.Bootstrap.DevServer 3.0.0 or later

Currently SamplesApp is on 2.x and can't be debugged.

This will also require SamplesApp to be on net5.0

@jeromelaban You can assign me to this if this is a change you'd like to be done :) (Edit: Opened a PR since the change is small and fast)

**Comment by jeromelaban** [comment]
Will be fixed in https://github.com/unoplatform/uno/pull/9808

**Comment by Youssef1313** [comment]
Closing as fixed.
