### ISSUE TITLE
[iOS] [VisualStudio Mac] : Builds iOS Simulator when targeting iOS device

### ISSUE THREAD

**Issue by baskren** [unoplatform/uno#9822]
### Current behavior

Applications built with VisualStudio Mac (versions 17.3.4 or 17.4 preview - build 715), when targeting iOS device, build iOS simulator code and thus fail to CodeSign (and fail to deploy):

### Visual Studio setup for Uno solution to target for iOS device:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/2528888/189898446-c5b85f54-5fb5-4fd8-ba29-2704435c7451.png">

### Resulting Build Folder:
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/2528888/189898756-de496a2a-790c-42b7-87b8-0fa0de4862b1.png">

Note that Xamarin.iOS, Xamarin.Forms for iOS, and MAUI for iOS applications do property code sign in VS Mac 17.4 preview.  This includes presenting a dialog asking for user's MacOS username and password (to get access to the user's KeyChain).  Uno Platform apps do not present the same dialog.

### Visual Studio setup for MAUI solution to target iOS device:
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/2528888/189899223-b74ac969-c162-47e7-a632-915521893914.png">

### Resulting Build Folder:
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/2528888/189899437-f9baf12e-8ba2-4145-8006-6d04b0c39080.png">

### Expected behavior

Uno Platform iOS apps can be successfully deployed to tethered iOS devices.

### Minimal demo project (just an UnoApp with no changes):
[UnoWinUI1.zip](https://github.com/unoplatform/uno/files/9556979/UnoWinUI1.zip)

### Workaround

I am so looking for one!

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

  <ItemGroup>
    <PackageReference Include="Uno.WinUI" Version="4.4.20" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.4.20" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.4.20" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
  </ItemGroup>

### Affected platforms

iOS

### IDE

Visual Studio for Mac

### IDE version

versions 17.3.4 or 17.4 preview - build 71

### Relevant plugins

none

### Anything else we need to know?

yet to find a work around

**Comment by jeromelaban** [comment]
Thanks for the report. We're currently explicitly setting the RuntimeIdentifier to:

https://github.com/unoplatform/uno/blob/9a5750449b13228fc80d71cc68b44e8ae569d1dd/src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Mobile/UnoQuickStart.Mobile.csproj#L8

And you can set it to:
```xml
<RuntimeIdentifier Condition="'$(TargetFramework)' == 'net6.0-ios'">ios-arm64</RuntimeIdentifier>
```
instead, or remove the line completely. Originally, these `RuntimeIdentifier` lines were present to ensure that running from the command line would work, but now from visual studio, this is set automatically.

**Comment by baskren** [comment]
Yikes.  I'm embarrassed that I didn't figure this out, especially given how much time I spent looking everywhere else for this.  Thank you SO MUCH!

**Comment by jeromelaban** [comment]
Thanks the for the update, let's keep this issue opened until this is fixed in the templates.
