### ISSUE TITLE
Cannot run the wasm project

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/uno#983]
## Current behavior

After generating a new template with the vsix extensions, upgrading `Uno.UI` package to 1.44.1 throughout the solution, I try to run the wasm project, the browser opens for a second and immediately closes.

The output I see in the _ASP.NET Core Web Server_ output window is:
>UnoApp1.Wasm> Version for package `Uno.Wasm.Bootstrap.Cli` could not be resolved.

I can see this line repeated 2-4 times.

The output in the _Debug_ output window is attached [here](https://gist.github.com/weitzhandler/72fd02df7ff220537145395be96de763).

Per [this](https://github.com/nventive/Uno/issues/710#issuecomment-476678533) comment I've tried updating the csproj with:

`xml
<ItemGroup>
  <PackageReference Include="Uno.UI" Version="1.44.1" />
  <PackageReference Include="Uno.Wasm.Bootstrap" Version="1.0.0-dev.281" />
  <DotNetCliToolReference Include="Uno.Wasm.Bootstrap.Cli" Version="1.0.0-dev.281" />
</ItemGroup>
`

But the error still persists.
I've tried the versions of that comment as well.

## Expected behavior

When generating an Uno app using the extension, all projects should work out of the box.

## How to reproduce it (as minimally and precisely as possible)

- Install the [templates extension](https://marketplace.visualstudio.com/items?itemName=nventivecorp.uno-platform-addin&ssr=false#review-details)
- In VS generate a new Uno app
- Set the wasm as startup project (IIS+Chrome) and run
- Check the output window, switch between _Debug_ and _ASP.NET Core Web Server_ drop downs.

## Environment

Nuget Packages and versions: 
Uno.UI: 1.44.1
Uno.Wasm.Bootstrap: 1.0.0-dev.281

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.1.1)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
@weitzhandler sorry to hear this. What version of Visual Studio are you using?

**Comment by weitzhandler** [comment]
@ghuntley Thanks for your sympathy 😊
I've updated my post, it's 16.1.1.

**Comment by PieEatingNinjas** [comment]
Experiencing the same issue, running 16.1.2.

**Comment by jeromelaban** [comment]
@weitzhandler If you start the app using Ctrl+F5, what happens ? The F5 experience is not useful for now.

**Comment by weitzhandler** [comment]
You probably meant <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>F5</kbd>, I've tried that but I get a "HTTP Error 502.5 - Process Failure" error page.
The output in the ASP.NET Core Web Server is as indicated above.

**Comment by weitzhandler** [comment]
@jeromelaban 
You probably meant <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>F5</kbd>, I've tried that but I get a "HTTP Error 502.5 - Process Failure" error page.
The output in the ASP.NET Core Web Server is as indicated above.

**Comment by sshary019** [comment]
![Annotation 2019-06-17 113854](https://user-images.githubusercontent.com/13855833/59583409-9b186d00-90f4-11e9-920d-1ec632f320d4.png)
I am getting this error when running WASM after new UNO project created.

**Comment by ghuntley** [comment]
Whatever this was, it no longer reproduces.

![image](https://user-images.githubusercontent.com/127353/61020211-4957bf80-a3e0-11e9-93ad-6e705a78019b.png)

Using the latest vsix (see https://github.com/unoplatform/uno/pull/1213/files#diff-bb469f1b15e197be6787eeb4f0a2fcce) pre-release, latest Uno.UI pre-release and latest Uno.Wasm.Bootstrap pre-release.

**Comment by ghuntley** [comment]
Thanks for letting us know folks, apologies this was open for so long!

**Comment by andrewleader** [comment]
I had the same exact problem, but in my case the root cause was that the [.NET Core 2.2 SDK](https://dotnet.microsoft.com/download/visual-studio-sdks) wasn't installed. But no helpful errors pointed me to that!
