### ISSUE TITLE
[Gallery][Wasm] Image- For 'Stretch:None' section Uno Image is not displaying when zoom in page up to 150%

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#9831]
### Current behavior

![Image issue - Outlook](https://user-images.githubusercontent.com/74563602/189991165-0b8adfa7-15cc-4bee-860f-fd387fad1a88.png)

https://user-images.githubusercontent.com/74563602/189993538-e1ab9b28-4892-472c-b97b-f86d6e075941.mp4

### Expected behavior

![Image Correct](https://user-images.githubusercontent.com/74563602/189993759-3bc46911-94f2-46a4-9d0b-c8fbaac1f275.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP.
2. Zoom in page up to 150%
3. Click/tap Burger Menu on the left top right.
4. Tap "Image" from the "Features" list.
5. Go t o the 'Stretch:None' section.
6. Notice that for 'Stretch: None' section Uno Image is not displaying.

### Affected platforms

WebAssembly

**Comment by Youssef1313** [comment]
Current behavior almost looks correct to me.

This is what happens on Windows:

![image](https://user-images.githubusercontent.com/31348972/190011177-b02660c8-1a74-4733-b7ca-5f46542bdbc2.png)

The part I'm not sure about is, when the app starts on 100% scale, the `ImageSample.scale-100.png` is loaded. However, when we zoom in to 150%, `ImageSample.scale-150.png` isn't loaded until we refresh the page.

But I think the `Image` behavior matches Windows.

**Comment by sakshi173** [comment]
Its true image is not loading until we refresh the page. I am not sure if this is fine and matches windows' behavior. @jeromelaban Could you please confirm if is this fine and if the behavior matches windows?

**Comment by jeromelaban** [comment]
Yes, it is indeed the intended behavior. Thanks @Youssef1313, @sakshi173.
