### ISSUE TITLE
XAML Generator should cache parsed resw resources

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#9844]
## What would you like to be added:

This method should use a caching technique similar to https://github.com/unoplatform/uno/pull/9727: 
https://github.com/unoplatform/uno/blob/bcf66abbaa2e55f018aed75e0af3df58fbb9adb6/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs#L600

## Why is this needed:

Improved generation performance

**Comment by Youssef1313** [comment]
@jeromelaban Do we want cache timeout here too?

**Comment by jeromelaban** [comment]
Yes, the same behavior we're using with XAML files. We can probably reuse a similar caching class.
