### ISSUE TITLE
[Gallery][Wasm/Skia.Gtk] PersonPicture- BadgeNumber display circle shape is incorrect.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#9846]
### Current behavior

![PP issue](https://user-images.githubusercontent.com/74563602/190238197-3b8bd40f-8227-495b-af28-416360568e16.png)

### Expected behavior

![PP correct](https://user-images.githubusercontent.com/74563602/190238222-abb142be-56a8-4a8d-a62b-f62262f5653b.png)

### How to reproduce it (as minimally and precisely as possible)

Launch the Uno.Gallry app 
Click on “PersonPicture” from the "Component" list.
Observe that BadgeNumber display circle's shape is incorrect

**Comment by jeromelaban** [comment]
This is a duplicate of https://github.com/unoplatform/uno/issues/7508, either close the other one or this one.

**Comment by MartinZikmund** [comment]
Closing this one in favor of the other 👍
