### ISSUE TITLE
`OutputSourceComments` property isn't used

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#9874]
This is never used:

https://github.com/unoplatform/uno/blob/cef37600284a87881762d0dfda73da6ca42a3c7c/src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props#L227-L230

In generator code, it's always true and never read from MSBuild properties:

https://github.com/unoplatform/uno/blob/cf70e8e8ec4389d80269122280b5083066724958/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs#L57

One of two actions is needed:

1. Support this property by making it compiler-visible, and using it in the generator.
2. Keep the current behavior of always outputting comments and clean up the code by removing the property from `Uno.UI.SourceGenerators.props` and removing the always-true field from generator code.

@jeromelaban Which do you prefer?

**Comment by jeromelaban** [comment]
Good find. Let's remove the conditionals and keep true as the current behavior.
