### ISSUE TITLE
Update Ch9 Sample App video feed source

### ISSUE THREAD

**Issue by sasakrsmanovic** [unoplatform/uno#9896]
Microsoft stopped Channel 9 and moved its content to MS Learn site. They also shut down the RSS feed available for all Channel 9 shows, which in turn broke the Ch9 sample app. The app needs to use different feeds in order to start working again. 

The source feed used to be this:
https://ch9-app.azurewebsites.net/api/proxy?url=https://s.ch9.ms/feeds/rss
https://s.ch9.ms/feeds/rss

Microsoft will not be opening a new RSS feed from MS Learn site, but they will share all shows on YouTube.  In order to fix the app we need to read from YouTube RSS feed for the ~20 shows consumed/implemented in Ch9  i.e. 

Microsoft Developer (our main channel): https://www.youtube.com/channel/UCsMica-v34Irf9KVTh6xx-g
Microsoft 365 Developer: https://www.youtube.com/channel/UCV_6HOhwxYLXAGd-JOqKPoQ
dotNET: https://www.youtube.com/channel/UCvtT19MZW8dq5Wwfu6B0oxw
Microsoft IoT Developers: https://www.youtube.com/channel/UCL7wy-iy_V76xxPnrIzGOZQ
DevOps on Azure: https://www.youtube.com/channel/UC-ikyViYMM69joIAv7dlMsA
Microsoft Visual Studio: https://www.youtube.com/c/visualstudio

**Comment by trungnt2910** [comment]
Hi, I would like to work on this issue, and/or [this](https://github.com/unoplatform/Uno.Ch9/issues/173) one from the Uno.Ch9 repo.

However, browsing through the repo's [code](https://github.com/unoplatform/Uno.Ch9/blob/bd082d17b2c43d9415b7244b948aaed0e2dcf889/src/Ch9/Ch9.Shared/Domain/ShowService.cs#L65), I can see that the application gets the feed details from `https://ch9-app.azurewebsites.net/api/rssfeeds`, which seems to be a private web server owned by Uno Platform.

So I guess that is where things should be updated from first, before updating these [fallback feeds](https://github.com/unoplatform/Uno.Ch9/blob/bd082d17b2c43d9415b7244b948aaed0e2dcf889/src/Ch9/Ch9.Shared/Domain/ShowService.cs#L40-L56)?

**Comment by MartinZikmund** [comment]
Closing in favor of https://github.com/unoplatform/Uno.Ch9/issues/173
