### ISSUE TITLE
TextBox text selection doesn't work when IsReadOnly is true

### ISSUE THREAD

**Issue by jeanplevesque** [unoplatform/uno#9908]
### Current behavior

Text selection doesn't work on `TextBox` when `IsReadOnly` is set to `true` on at least iOS and Android.

### Expected behavior

Text selection works on `TextBox` even when `IsReadOnly` is set to `true` on all platforms.

### How to reproduce it (as minimally and precisely as possible)

```xml
<TextBox Text="Try to select me!" IsReadOnly="True"/>
```

### Workaround

None

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI 4.4.20

### Affected platforms

iOS, Android

### IDE

Visual Studio 2022

### IDE version

17.3.4

**Comment by jeromelaban** [comment]
@jeanplevesque I don't think it ever worked that way in Uno (unless you've seen otherwise). I'm not too sure if the native controls do work that way either, but it's definitely worth taking a look.

**Comment by ajpinedam** [comment]
@jeanplevesque  

I confirmed this is not an "latest iOS problem", instead this has been Uno behaviour. 

It's possible to have the desire solution (attached a video showing an Uno app with the fix)  but we need to check if this change could be breaking other things.

https://user-images.githubusercontent.com/1900897/191896213-1c3f6780-dcde-4793-badd-254028d2640a.mp4

cc: @jeromelaban

**Comment by jeanplevesque** [comment]
Just to be clear, I'm not reporting this as a regression of any kind. Just as a bug. 😊

**Comment by ajpinedam** [comment]
Reopening for the work on the Android issue
