### ISSUE TITLE
Bindings to the SelectedDate and SelectedTime properties on the DatePicker and TimePicker controls do not apply the fallback value

### ISSUE THREAD

**Issue by ADD-Jose-Romo** [unoplatform/uno#9918]
### Current behavior

When the binding should apply the fallback value, it does not show these values and continues to show the last value.

### Expected behavior

The fallback value must be shown.

### How to reproduce it (as minimally and precisely as possible)

Open the attached project, compile and run it. On the main page, three buttons, two text boxes, a date picker and a time picker are displayed. The first two buttons are for navigating between the virtual data and the third button is to clearing the data. When you click the Clear button, the value of the date picker control and the time picker control are not cleared.
[FallbackValueOnDateTimePickerBindings.zip](https://github.com/unoplatform/uno/files/9618149/FallbackValueOnDateTimePickerBindings.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.5.9

### Affected platforms

iOS, Android, WebAssembly, macOS, Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.3.4

**Comment by carldebilly** [comment]
## Investigation
It seems the problem is related to x:Bind. If we replace (or duplicate) the `<DatePicker />` to use `{Binding}` instead of `{x:Bind}`, Uno and Windows will behave exactly the same way.
