### ISSUE TITLE
[IOS] combobox not opening

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#9943]
### Current behavior

![combobox](https://user-images.githubusercontent.com/90481654/191963062-8c84053e-9256-4625-b981-c1c302ec79ba.gif)

For some reason, in a project, the combobox simply doesnt open.

### Expected behavior

![comboboxwinui](https://user-images.githubusercontent.com/90481654/191963937-b6429a4b-a0dd-41d5-a546-3e05bca62fa0.gif)
The combobox should open like on winUI

### How to reproduce it (as minimally and precisely as possible)

[MyAppTest.zip](https://github.com/unoplatform/uno/files/9633744/MyAppTest.zip)
Unfortunately, I could not repro the issue in a repro app but this was by best attempt at it.

### Workaround

none

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

    <PackageReference Include="Uno.WinUI" Version="4.6.0-dev.116" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.6.0-dev.116" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.3.6" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
    <PackageReference Include="Uno.Extensions.Logging.OSLog" Version="1.4.0" />
    <PackageReference Include="Uno.Core" Version="4.0.1" />
    <PackageReference Include="Uno.Material.WinUI" Version="2.4.0-dev.13" />
    <PackageReference Include="Uno.Toolkit.WinUI.Material" Version="2.4.0-dev.13" />
    <PackageReference Include="Uno.Toolkit.WinUI" Version="2.4.0-dev.13" />
    <PackageReference Include="Uno.SourceGenerationTasks" Version="4.2.0-dev.6" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Uno.Extensions.Authentication" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Configuration" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Core" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Hosting" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Hosting.WinUI" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Http" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Http.Refit" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Localization.WinUI" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Logging.Serilog" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Logging.WinUI" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Navigation.Toolkit.WinUI" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Navigation.WinUI" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Navigation" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Serialization" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Serialization.Refit" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Reactive" Version="2.3.0-dev.10" />
    <PackageReference Include="Uno.Extensions.Reactive.WinUI" Version="2.3.0-dev.10" />
  </ItemGroup>

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

Version 17.3.4

### Relevant plugins

none

**Comment by jeromelaban** [comment]
The latest canary for Gallery is having the ComboBox opening properly. This could be an Uno.Theme specific issue. @kazo0 can you take a look?

**Comment by kazo0** [comment]
Yep!

**Comment by MartinZikmund** [comment]
Todo for me - figure out why https://github.com/unoplatform/uno/pull/9944 is needed as the `XamlRoot` should not be `null` (and it would break in Uno Islands scenario)

**Comment by kazo0** [comment]
@takla21 / @Marc-Antoine-Soucy 

I see this is marked as Closed in the TradeZero backlog, is this no longer a blocker?

**Comment by takla21** [comment]
@kazo0 yeah this PR mentioned above fixed our issues on our project
