### ISSUE TITLE
ListViewBase should support drag-and-drop to reorder items

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#995]
## What would you like to be added:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewbase.canreorderitems

https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlDragAndDrop

## Why is this needed:
Allow items in a list to be interactively reordered by the user.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

**Comment by dr1rrb** [comment]
Support has been added for WASM by #4386, other platforms are still to-do but won't be completed for 3.4

**Comment by jeromelaban** [comment]
Why was this item reopened? Is there something missing ?

**Comment by jeanplevesque** [comment]
I just spent 1h of screen sharing with @davidjohnoliver testing this. It's not working.

**Comment by davidjohnoliver** [comment]
This is still pending on #6725 and #6756

**Comment by jeanplevesque** [comment]
@davidjohnoliver Which version should I use to test the fixes?

**Comment by davidjohnoliver** [comment]
> @davidjohnoliver Which version should I use to test the fixes?

3.10.0-dev.399 should have the fix
