### ISSUE TITLE
Generate WinUI branch for each PR

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#9951]
## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by Youssef1313** [comment]
It might be worth considering having the branch created *on demand*, instead of each PR.
ie, PR author comments with `/winui branch` and then the branch is created.

**Comment by jeromelaban** [comment]
This will actually big fixed by https://github.com/unoplatform/uno/pull/9991, where there's going to be an artifact that will contain the converted tree for the PR. We're doing the conversion multiple times currently, and that PR will do it only once, saving time overall.
