### ISSUE TITLE
Confirm implementation of `HandleSpecialUriAsync` on iOS

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#9984]
### Current behavior

https://github.com/unoplatform/uno/blob/7cc2df180fb8b5833f3f6e05b50ac8d4ed4a8e99/src/Uno.UWP/System/Launcher.iOS.SpecialUris.cs#L22-L34

The Uri isn't used and we always use `UIApplication.OpenSettingsUrlString`. Something looks incorrect.

**Comment by jeromelaban** [comment]
As far as I remember, there was no way to discriminate the settings targets, and we chose to only open the default settings page.

**Comment by MartinZikmund** [comment]
Yes, that is the case, iOS does not allow deep-linking into specific settings pages (or at least didn't when it was implemented), so we only open settings.

**Comment by Youssef1313** [comment]
@jeromelaban @MartinZikmund So this should be closed?

**Comment by MartinZikmund** [comment]
Yes, closing 👍
