### ISSUE TITLE
Empty setters in a `VisualState` don't reset to defaults

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#9993]
### Current behavior

Empty VisualState setter has no effect but it should reset to default styled properties acording to the docs https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.visualstatemanager?view=winrt-22621#examples

### Expected behavior

Should reset to default styled properties instead of using TemplateBinding again

### Workaround

Excplicity set TemplateBinding again in the state setters to the same values but it won't work on WinUI https://github.com/microsoft/microsoft-ui-xaml/issues/7779
The workaround for that is to use the platform specific XAML markup https://platform.uno/docs/articles/platform-specific-xaml.html

Example:
```
<Application
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:not_win="http://uno.ui/not_win"
    xmlns:ui="using:Microsoft.UI.Xaml"
    mc:Ignorable="not_win">

    <Application.Resources>
        <ResourceDictionary>
             <Style x:Key="BaseImageButton" TargetType="local:ImageButton">
                <Setter Property="BackColor" Value="{ThemeResource ThemedButtonBackground}" /> />
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="local:ImageButton">
                            <Grid x:Name="PART_Panel" Background="{TemplateBinding BackColor}">
// Templated controls here
                                <VisualStateManager.VisualStateGroups>
                                    <VisualStateGroup x:Name="CommonStates">
                                        <VisualState x:Name="Normal">
                                            <VisualState.Setters>
// Use not_win markup
                                                <not_win:Setter Target="PART_Panel.Background" Value="{TemplateBinding BackColor}" />
                                            </VisualState.Setters>
                                        </VisualState>
                                        <VisualState x:Name="Pressed">
                                            <VisualState.Setters>
                                                <Setter Target="PART_Panel.Background" Value="{ThemeResource ThemedPressedBackground}" />
                                            </VisualState.Setters>
                                        </VisualState>
                                    </VisualStateGroup>
                                </VisualStateManager.VisualStateGroups>
                            </Grid>
                        </ControlTemplate>
                    </Setter.Value>
                </Setter>
            </Style>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

iOS, Android, WebAssembly, macOS, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen)

### IDE

Visual Studio 2022

### Anything else we need to know?

Tested on Skia GTK but I think it behaves the same on every uno platform

**Comment by jeromelaban** [comment]
It may be related, yes.

**Comment by DierkDroth** [comment]
@jeromelaban @Youssef1313 is there any chance to get this addressed?

Thanks in advance

**Comment by jeromelaban** [comment]
I'm not able to reproduce the issue with the steps provided above. 

The only condition of interest are that [Uno 4.6 here](https://playground.platform.uno/#98e2175a) does show a partial issue with the XamlReader that [was fixed in Uno 4.7 dev builds](https://playgroundcanary.z19.web.core.windows.net/#cf1162f9).

When creating issue, it's very important to create a fully working sample, not just portions of the code as there may be some missing context about the the behavior you're observing.

@FrozDark Can you validate that you're still getting this issue?

**Comment by Youssef1313** [comment]
@FrozDark Can you please re-validate if this is still an issue and provide a repro? Thanks!

**Comment by MartinZikmund** [comment]
@FrozDark Ping on this please

**Comment by FrozDark** [comment]
@MartinZikmund @Youssef1313 @MartinZikmund 
This is not an issue anymore. Thanks!
